# -*- mode: org; -*-

#+STARTUP: showall

#+TITLE: Eclats de vers : Accueil
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

* Eclats de vers: quelques échantillons de poésie brisée

/Des refrains, des pas de danse, de l’harmonie, quelques accords/
/brisés, quelques éclats de vers dont le fin cristal tinte sous le/
/vent, le clin d’oeil d’une lune de miel, le chant mélancolique des/
/sirènes. Mon tout fait un poème./

Troubadours, trouvères et autres ménestrels, artistes passionnés de
littérature, de poésie et de musique, artisans mathématiciens et
philosophes, soyez les bienvenus en ce castel ! Ces humbles murs, en
dépit de leur allure lointaine de citadelle austère, sont fiers
d’abriter les jardins et cascades d’une culture florissante. Vous
l’aurez compris, il s’agit d’ici d’art et de science, ces deux
chandelles inaltérables où loge une même clarté, ces deux flambeaux
que je vous propose d’unir en un astre souverain. Mais trêve de vain
bavardage ! Je devine à vos mines épuisées et aux chausses qui peinent
à vous suivre que le voyage fut long à vous mener en ces lieux ;
aussi, avant que vous ne vous égariez dans les couloirs et coulisses,
je vous invite à consulter sans plus attendre la tapisserie ci-dessous
où figure le [[*Plan du château][plan du château]], ainsi que le menu présent en haut de
chaque page, où vous trouverez sans nul doute de quoi vous sustenter.
S’il vous prenait l’envie de vous aventurer dans les passages secrets
du manoir, où règne une nuit sans lune et sans étoile, vous serez
probablement amenés à vous servir du fidèle compas de votre intuition,
qui vous permettra d’éviter les éventuels écueils. Et si vous restez
malgré tout sur votre faim spirituelle, n’hésitez pas à [[file:contact.org][tirer sur le
cordon]] ; un preux chevalier viendra alors vous aider dans votre noble
quête.


* Plan du château

#+INCLUDE: "include/menu.org"
