
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Articles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Art

** Ces fausses vraies vulgarités

Ce n'est un secret pour personne, l'être humain est porté sur la chose.
Et cela est fort heureux, car dans le cas contraire nous ne serions pas
là pour en témoigner. Mais quelle chose, me direz-vous ? Le coeur du
problème est bien là : malgré le vif intérêt que nous lui portons, ce
point vers lequel convergent nos émotions les plus intenses est
socialement soumis à la désapprobation publique. Raison pour laquelle
nous en parlons souvent en code ou à demi-mots. Ne le nions pas, il y a
là-dedans une pincée d'hypocrisie. Mais pincée n'est ni seau ni pinceau,
et il en va de l'hypocrisie comme de ces fines épices : indigeste en
surabondance, elle devient des plus savoureuses lorsqu'elle est dégustée
à petites doses de sous-entendus. Rentrons plus avant dans le vif du
sujet, avec Louise Labé qui, au 16e siècle, clamait haut et fort :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Baise m’encor, rebaise-moi et baise ;
    Donne m’en un de tes plus savoureux,
    Donne m’en un de tes plus amoureux :
    Je t’en rendrai quatre plus chauds que braise.
    ...
#+END_VERSE
#+END_CENTER

Contrairement aux apparences, elle ne réclamait pas par là publiquement
les assauts fougueux de son amant, le verbe baiser signifiant
simplement, d'après le Trésor :

Baiser : Effleurer, toucher de ses lèvres quelque partie d'une personne
(surtout la main, la joue) ou quelque objet la symbolisant.

La main et la joue, pourquoi pas, c'est un début après tout. Quoiqu'il
en soit, le double sens libidineux de ce genre de galanterie semble
n'avoir dupé personne, puisqu'il a débouché sur le sens populaire que
l'on connaît actuellement. Villon n'est pas en reste, avec toutefois la
nuance d'une teinte bucolique puisqu'il s'agit d'un cours de jardinage :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ces larges rains, ce sadinet
    Assis sur grosses fermes cuisses,
    Dedans son petit jardinet
#+END_VERSE
#+END_CENTER

Bien entendu, le terme de /sadinet/ (du latin /sapidus/, savoureux,
l'homme était connaisseur semble-t-il) désigne ici le sexe féminin, un
champ sémantique que le marquis de Sade n'aurait pas renié. Morale de
l'histoire, il n'y a pas loin du champ au jardinet en passant par la
grange. Il n'y a pas loin non plus de la grange à la guérite dont
Baudelaire nous parle dans son « Sonnet d'automne » :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Aimons-nous doucement. L'Amour dans sa guérite,
    Ténébreux, embusqué, bande son arc fatal.
    Je connais les engins de son vieil arsenal :
#+END_VERSE
#+END_CENTER

il n'avoue pas l'érection de son engin, mais bien que l'amour est à la
peine :

Bander : Tendre avec effort.

On peut bien entendu supposer maintes interprétations métaphoriques plus
ou moins emmenées à ce tercet. Toutefois, c'est le septième sens et le
plus osé que l'histoire a retenu. Et puisque l'on parle d'érection, que
l'on sache qu'il s'agit simplement de :

Erection : Action d'élever.

L'imagination laissant fièrement voltiger son drapeau au vent, la
signification populaire s'est une nouvelle fois embourbée dans les
traversins que l'on sait. Dans le même siècle, Musset se fait le chantre
de la danse, dans « À la mi-carême » :

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est alors que les bals, plus joyeux et plus rares,
    Prolongent plus longtemps leurs dernières fanfares ;
    À ce bruit qui nous quitte, on court avec ardeur ;
    La valseuse se livre avec plus de langueur :
    Les yeux sont plus hardis, les lèvres moins avares,
    La lassitude enivre, et l’amour vient au coeur.
#+END_VERSE
#+END_CENTER

Vous l'aurez compris, sa charmante valseuse n'a rien à voir avec la
bourse ! Plus tard cependant, la méta-fore houleuse s'imposera à nos
yeux ébahis. Je vous épargne le terme portuaire chanté par Renaud dans «
Le vent soufflera » :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Assise sur une bitte
    D’amarrage, elle pleure
#+END_VERSE
#+END_CENTER

les verges flagellantes :

Verge : Baguette de bois longue, fine et flexible; tige de métal longue
et fine. Verge d'un arc, d'un fouet, ...

les cons qui ne sont plus ce qu'ils étaient :

Con : Région du corps féminin où aboutissent l'urètre et la vulve.

et tout le stupre dégoulinant d'une liste exhaustive. Sachez simplement
qu'il en va de même pour bon nombre de mots de notre langue, et ce
jusqu'aux plus usuels. A moins que vous ne soyez incorrigiblement
ingénu(e) (je n'ai pas dit singe et nu(e)), si je vous dis que :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les brebis nocturnes de Lesbos broutent le soir
    Lorsque les cruches s’en vont à l’eau au ruissellement des rondelles
    Je répète ...
    Les brebis nocturnes de Lesbos broutent le soir
    Lorsque les cruches s’en vont à l’eau au ruissellement des rondelles
    Trois fois (et plus si affinité)
#+END_VERSE
#+END_CENTER

vous irez sûrement penser qu'il y a là, savane-ment caché dans les
buissons, comme un message inavouable. Vous n'aurez pas tord. Je
terminerai par cette constatation toute simple :

Vulgaire : (Vieilli ou littér.) Qui est admis, pratiqué par la grande
majorité des personnes composant une collectivité, appartenant à une
culture; qui est répandu. Qui est identique, semblable aux autres
individus, aux autres objets de son espèce. Synon. anodin, banal,
ordinaire.

Il est vrai que la vulgarité est une chose bien ordinaire.

** Sur l'art poétique de Verlaine

Depuis longtemps cette question me rongeait : comment le roi de la
chanson grise, le prince de la poésie mélodieuse en était-il arrivé à
mépriser les ailes sur lesquelles il a si brillamment voltigé. Ces vers
semblent a priori sans appel :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ô qui dira les torts de la Rime ?
    Quel enfant sourd ou quel nègre fou
    Nous a forgé ce bijou d’un sou
    Qui sonne creux et faux sous la lime ?
#+END_VERSE
#+END_CENTER

Voilà qui peut sembler paradoxal : on n'écrit pas un art poétique
incrusté de rimes tout en accusant la pauvrette. D'autant plus que, dans
le même poème, la première strophe nous donne un tout autre son de
cloche :

#+BEGIN_CENTER
#+BEGIN_VERSE
    De la musique avant toute chose,
    Et pour cela préfère l'Impair
    Plus vague et plus soluble dans l’air,
    Sans rien en lui qui pèse ou qui pose.
#+END_VERSE
#+END_CENTER

Passons sur l'impair, et retenons-en l'essentiel, à savoir la musique,
profondément liée aux assonances, allitérations et à toute forme de rime
au sens large. Ces deux strophes se révélent des plus contradictoires.
Mais où veut-il en venir ? La réponse pourrait très bien se glisser dans
la rime justement, celle qui ajuste fou à sou. Il faut savoir qu'à
l'époque ce genre de rime pauvre (c'est en fait une simple assonance)
était des plus déconseillée. Tout juste tolérée, et encore. Le bijou
d'un sou serait alors le caractère excessivement rigide de la prosodie
de l'époque, gourmande en rimes riches. Il ne nous parle donc pas de
l'abolir mais de la laisser gambader dans un style beaucoup plus souple,
délayé dans le flou artistique, la musique avant la règle, l'esprit
avant la lettre. Ce n'est qu'une hypothèse bien sûr, mais qui s'ajuste
parfaitement.

** La poésie libre

Alors là pas question de faire l'impasse, c'est non, non et encore non !
Désolé que ça tombe sur toi Fairy Tales, n'y vois rien de personnel,
mais à force d'entendre toujours les mêmes rengaines, la coupe finit par
déborder de l'eau du vase et les plombs du cable sautent ! Surtout par
temps lourd, les muses prennent vite la mouche d'orage ... donc je dis
Non !

Non, la poésie versifiée n'est pas cette créature désséchée, décrépite,
apesantie, engoncée dans un corset qui la torture. C'est une jeune
donzelle qui danse et tourbillonne, une déesse qui suit le rythme parce
qu'elle sait que le rythme suit son coeur débordant de fougue, c'est une
grande dame qui se laisse aimer par le chant lancinant des vagues, cette
source d'art pur, sublime symbiose de régularité et de fantaisie, c'est
une reine qui se plie par plaisir aux caprices de la strophe et aux
morsures du poème.

Non, le fond n'est pas plus important que la forme, le rythme et la
coloration phonétique sont déterminants. Plus que cela, ils ont une
signification qui se superpose à celle du langage. Essayez de faire
décoller de la poésie non cadencée, je vous promets bien du plaisir.
Tous les poèmes réussis que j'ai pu lire ici ou ailleurs (le ici ou
ailleurs on s'en fout, c'est juste de la broderie mimi) ont un rythme
interne qui vous entraîne et empêche le texte de couler lamentablement.
En bref, il y faut du swing, ou prévoir des bouées, ou lire un roman le
soir, assommant de préférence, ça épargne les soporifiques.

À coté de cela, nous avons devant nous une poésie qui se prétend « libre
», une poésie qui prétend enfermer ses soeurs de lyre d'un sous-entendu
trop éloquent pour ne pas être vulgaire. Et vous voudriez sans doute
qu'on les laisse croupir au couvent de l'église surréaliste, victime de
la frigidité jalouse de quelques proses bien pâles ?

Je ne sais quel disciple imbibé de cette icône de Rimbaud a inventé
cette expression pléonasmique de « poésie libre », mais excusons-le, on
a vu ce que donne l'utilisation d'absinthe sur la voix de son maître.
Les « Illuminations » portent bien leur nom, laissons-leur cela. Je ne
sais pourquoi, ce titre me fait penser aux enluminures, vous savez ces
petites bandes dessinées médiévales. Avec ce brave Rimbaud, loubard
déifié par une postérité pour le moins postérieure, c'est encore plus
facile : comme personne n'y comprend rien, il suffit de faire semblant !
Les nombreux adeptes doivent apprécier ce geste touchant dont ils
drapent leur amour-propre.

Quoiqu'il en soit, la « poésie dite libre » ne l'est pas plus qu'une
autre, et même plutôt moins puisqu'écrire en vers libres revient
actuellement à se laisser porter par le courant. La voie de la facilité
qui évite de devoir apprendre, qui fait bien, qui fait rebelle, qui fait
moderne, qui fait post mai 68. Nous sommes tous des rebelles dans un
monde de rebelles, avec de la musique de rebelle, du café de rebelle,
des boulots de rebelle, des poubelles de rebelle, de la routine de
rebelle, de l'ennui de rebelle. Nous tombons tellement d'accord sur le
principe de la rebellion qu'il n'y a même plus besoin de se rebeller,
c'est-y pas magnifique ?

Mais revenons à mai 68 et ses pavés, mai 68 et ses feux de joie bariolés
d'arc-en-ciels flower power, mai 68 et ses gentils organisateurs
casqués, mai 68 et ses futurs bourgeois à l'eau de rose, mai 68 et ses
slogans faciles. Quand je vois une ineptie du style « interdit
d'interdire », je me demande si il y avait vraiment des intellectuels
sur les barricades. À croire que trop lire de philosophie doit finir par
vous embrouiller un esprit, le bon sens le plus élémentaire passe à la
trappe.

Quel mois romanesque, vraiment ! On lui doit cette vision déformée de la
liberté, cette hantise absurde de la contrainte, ce dénigrement du
savoir, et par corollaire de tout ce qui ne ressemble pas assez au chaos
idyllique dont rêvent tous les nostalgiques de l'obscurantisme et de la
barbarie de l'époque féodale. On lui doit ce culte de la nouveauté
recyclable servi à toutes les sauces lors des fréquentes éphémérides
cosmiques où paradent des cosmétiques qui puent, on lui doit ces modes
incessantes qui tournent en rond autour du néant absolu tout en
marmonnant une litanie dogmatique, ces amas de jeunes filles
squelettiques, la téléréalité siliconée, le grand complot mondial de
l'univers, et, pire que tout, la fin de la diffusion des Cousteau sur la
deux.

Assumez, Attilas en herbe qui foulez sous vos sabots boueux l'eau
limpide de cette rigueur qui clarifie l'âme lorsqu'on l'accouple à
l'intuition ! Cessez de respecter toute règle orthographique ou
grammaticale, inventez une langue libérée que vous serez seul à
comprendre, et surtout amusez-vous bien dans votre coin. D'ailleurs je
vous déconseille d'apprendre à écrire, ça risquerait d'étouffer votre
créativité.

Assumez, fanatiques de la nouveauté bourdonnante : n'empruntez plus
aucun véhicule à roue, c'est obsolète ça, la roue. Coupez le chauffage,
le principe date de l'antiquité, et puis vendez vos quatre murs, c'est
carrément trop antédiluvien le concept de mur.

Vous voulez de la liberté ? Vous venez d'en lire, iconoclaste et
provocatrice à souhait, à contre-courant de la bien-pensance c'est vrai,
mais par franchise, non par frime. La Liberté c'est se moquer du sens du
courant m'sieurs-dames, ce n'est ni le suivre pour faire plaisir au
mouton voisin, ni ramer à contre-sens pour se donner une illusion
d'indépendance.

Qu'on se le dise, il n'est plus question de subir les adorateurs
inconditionnels du vers à mètre aléatoire sans leur demander s'il leur
arrive de danser.

⁂

Pour préciser ma pensée, la forme possède un sens propre, un peu comme
ces musiques instrumentales qui font preuve d'une telle force de
suggestion qu'elles peuvent compléter voir remplacer les paroles ; il ne
s'agit donc pas de faire passer le fond en arrière-plan, mais au
contraire de l'étendre à la suggestion qui naît de l'aspect musical d'un
poème. Aragon a écrit une fort belle ballade à ce sujet d'ailleurs, dont
le refrain est :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ce sont paroles de Grenade
#+END_VERSE
#+END_CENTER

Il fait allusion à la musique arabo-andalouse du 15e siècle qui avait
d'après lui la particularité de ne pas être systèmatiquement complétée
par un chant, ce qui n'était pas évident comme concept à l'époque.

En ce qui concerne la pensée, il est vrai qu'elle devient vite
impressionniste en poésie, l'abondance du langage imagé, détourné du
sens commun, rendant parfois les interprétations compliquées, on peut
même jouer dessus afin de donner plusieurs sens à un texte. La netteté
du discours y est en fait un paramètre sur lequel l'auteur peut jouer.

Ceci dit, je te suis sur la nécessité d'une pensée claire et rigoureuse,
celle de la philosophie et de la science au sens large.

** Les langues

[i](combien de théorèmes, en mathématique par exemple, se contredisent
les uns les autres ? ce qui est par exemple applicable en géométrie
euclidienne ne l'est pas toujours en géométrie spatiale)[/i]

Aucun malheureux, où tout s'écroulerait ! Hérésie, blasphème,
sorcellerie ! ;) Les différents types de géométries sont des objets
différents, chacune a ses propres lois. Ce qui est valable dans l'une ne
l'est pas forcément dans l'autre, nulle contradiction là-dedans.

Pour en revenir aux langues, chacune a sa propre structure, son propre
timbre, son propre réseau reliant les mots les uns aux autre via le sens
ou la sonorité. Malgré tout, il existe des familles de langues proches
les unes des autres. La question sous-jacente est : existe-t-il un
langage universel dont toutes les langues découlent ? Ce qui nous mène à
la question annexe : existe-t-il des pensées/émotions universelles
intégrées dans toutes les langues, ou presque ? Si oui, comment les
langues intègrent-elles ces notions ?

J'aurais tendance à répondre oui à la première question. Par exemple,
l'univers semble construit sur des formes récurrentes comme la dualité
cercle / onde que l'on retrouve partout, de la mécanique quantique à
l'échelle cosmique.

Le cas de l'émotion me semble encore plus évident : il suffit d'observer
un nombre suffisant de personnes pour constater que des schémas
psychologiques récurrents apparaissent. Si certains schémas semblent
culturels, d'autres ont une allure plus fondamentale. Cela n'empêche
nullement l'unicité de l'individu, mais la société semble suivre des
lois probabilistes.

Mais si certaines idées semblent être transposables sans trop de perte
d'information d'une langue à l'autre, d'autres en ressortent
complètement déformées, quand elles ne débouchent pas sur une phrase qui
n'a plus de sens. Les idées représentées par des métaphores différentes
dans les langues impliquées sont particulièrement visées par ce
phénomène.

Et nous n'avons pas encore parlé de la sonorité. Si j'en juge par
l'échange animé, nous avons chacun une réaction différente par rapport à
la musique interne d'une langue. Je dirais pour résumer que, si un
concept apparemment simple comme l'amour à le même sens global en
Français et en Anglais, la phrase « je t'aime » suggère en complément
d'autres pensées que « I love you ».

Pour utiliser une métaphore musicale (oui, encore les ondes), je dirais
que le sens fondamental est le même dans les deux langues, mais pas les
harmoniques. En clair, la mélodie est la même, mais pas l'instrument. Hé
oui, on en revient au timbre.

Le cas des trente mots signifiant neige est plus complexe. Je suppose
que certains d'entre-eux décrivent des variantes de congère, de
poudreuse, etc. Traduire dans une langue un concept qui n'existe pas
sous forme de mot demande de contourner le problème en formant une
phrase, autrement dit en projetant la pensée d'une langue vers une
autre. Et qui dit projection, dit approximation, parfois grossière. Même
le sens fondamental peut alors varier.

* Politique

#+TOC: headlines 1 local


** Les philosophies Unix et du logiciel libre sont l’avenir de la politique



** Free Software and Unix philosophies are the future of politics



** La diplomatie

Je vois que tu as en tête le cas particulier, il est vrai le plus
fréquent, où au moins une des parties ne peut être pleinement satisfaite
de l'accord. Elle est alors lésée par rapport à ce qu'elle ambitionnait,
mais y gagne généralement si on compare les termes de l'accord à la
situation antérieure. Si ce n'était pas le cas, l'accord n'aurait
probablement pas été conclu. Il y a donc relativité de la concession.
J'y reviendrai, mais je tiens tout d'abord à donner un exemple de cas où
aucune partie n'est lésée, même relativement à ses espérances.

*** Solution sans concession

Ma petite fable fait intervenir soeur Sourire et frère Soupir. Soeur
Sourire adore le jardinage et la bronzette. Frère Soupir aime le calme
et l'ombre propice à ses études. Tous deux souhaitent acheter le même
petit coin de paradis pour y construire la villa de leurs rêves, celle
de Soeur Sourire étant vous vous en doutez fort différente de celle de
frère Soupir. Le problème est qu'aucun des deux pris séparément n'a
suffisamment de fonds pour cela. Chacun souhaite emprunter la somme
nécessaire à son concurrent, mais tous deux refusent, évidemment. Vient
alors le frérot architecte qui leur propose d'acheter le terrain à deux
et d'y construire un immeuble de deux étages, concept totalement nouveau
à l'époque de notre fable. Soeur Sourire occupera le second, aura un
jardin sur le toit et du soleil à profusion, tandis que Frère Soupir
sera bien au frais, abrité par l'étage supérieur de la chaleur estivale.
Aucun d'eux n'a fait de concession, et la solution est encore supérieure
à leurs attentes.

Tout cela pour dire qu'une diplomatie idéale se doit d'être innovante.
Un tel cas peut sembler rare, mais cela doit malgré tout rester un
objectif à atteindre. Même dans une situation plus réaliste, l'idée
reste toujours de maximiser les avantages en minimisant les concessions.

*** Relativité de la concession

Pour illustrer la relativité de la concession, imaginons deux fermiers
qui exploitent un terrain commun. Ils souhaitent le vendre et trouvent
un acheteur à bon prix. Tout cela semble idyllique, mais chacun des deux
fermiers prétend avoir travaillé plus dur que l'autre depuis plusieurs
saisons, et réclame 70 % du produit de la vente. Si ils n'acceptent pas
tous deux de revenir à 50 %, la vente ne sera pas possible. Il y a alors
deux visions duales des choses.

Dans la vision psychologique, chacun des fermiers a l'impression de
devoir faire une concession pour pouvoir vendre le terrain.

Dans la vision épurée, l'alternative est simple : soit ils touchent
chacun la moitié de la vente, soit ils ne touchent rien du tout.

Dans la première situation, il y a concession. Dans la seconde, seul
apparaît le gain réalisé par rapport à l'absence d'accord.

*** Discussion

La discussion ne poursuit pas le même but que la diplomatie. Dans ce cas
nous sommes d'accord, il n'y a pas à concéder, en première lecture du
moins. Par après, on peut toujours réfléchir sur les arguments de
l'autre et voir si ils nous apportent quelque chose, je ne vois pas cela
comme une concession.

*** Respect

Ce n'est pas vraiment la propriété de la porte qui compte, si tu as un
invité qui dort chez toi, tu ne vas pas le réveiller pour aller aérer si
tu as trop chaud, simple question d'intimité.

Pour en revenir au voisin, je dirais que si tu t'abstiens d'aller le
déranger pour éviter de recevoir le lendemain le paquet cadeau de son
labrador sur ton paillasson, tu obéis alors effectivement à un pacte
tacite. Si tu t'en abstiens par empathie avant même de penser au code
social, si tu t'en abstiens parce que tu te mets à sa place et que tu
n'aimerais pas non plus qu'il fasse intrusion, l'affaire est totalement
différente. Il s'agit alors d'une conscience de l'autre, et non plus
d'obéissance, ce qui rejoint, ou plutôt étend le concept d'amour à une
notion beaucoup large. C'est assez proche de ce que tu expose avec les
« fils tremblants ».

Ah, l'amour, un des termes les plus employés, mais aussi un des plus
vagues dans sa définition. Nous avons tous nos propres acceptations de
chaque mot, mais avec celui-là, le flou est d'autant plus grand que les
concepts qu'il implique sont nombreux et interdépendants.

*** Franchise

On peut certes amener sa franchise comme on le souhaite, mais si on le
fait en blessant l'interlocuteur, on aura beau lui dire par après que la
terre est ronde, il ne le croira plus. J'exagère, mais l'esprit est
ainsi fait qu'il se défend face à ce qu'il considère comme une
agression. Même si le but n'est pas de convaincre, cette blessure
est-elle souhaitable ? On pourrait répondre non dans le cas général, oui
dans le cas ou se taire est pire. C'est une question ouverte, chacun
aura sa réponse en fonction des circonstances.

** Le marteau et ses faux cils

/La polis tique, tome 1/

« Moi, je ne suis pas Marxiste ». Cette citation, d'apparence tout à
fait anodine, prend tout son sel lorsqu'on apprend qu'elle provient de
Karl Marx lui-même. À première vue, on peut y voir une volonté de se
démarquer de l'interprétation qu'il estimait frauduleuse de certains de
ses émules. Mais on peut aussi y reconnaître le philosophe, encore plus
attaché au principe de l'idée libre qu'à ses propres théories. Car
enfin, cette phrase n'est-elle pas une façon de dire : « je ne veux pas
que l'on me suive aveuglément, je ne veux pas que l'on me suive sans
réfléchir, je ne veux pas que l'on me suive intégralement sans remettre
en question la plus infime de mes pensées, en fait je ne veux pas que
l'on me suive tout court. » ? Vue ainsi, elle se métamorphose en une
attaque virulente contre ces partis et ces religions où l'on vous
explique quoi penser, quoi critiquer, qui aimer. Une petite phrase
d'apparence banale, mais qui donne une autre dimension à l'histoire. Et,
en dépit de cette envergure, une tentative dérisoire de lutter contre la
bêtise universelle. Sans augurer d'un avenir vraisemblablement lointain,
une chose est sûre : le monde se portera mieux le jour où textes
politiques et religieux seront lus avec un minimum de discernement, une
once de distance, une pincée de philosophie. N'en déplaise à Audiard, un
intellectuel assis ira toujours plus loin qu'une bande de cons qui
tourne en rond. Oui, j'aurais bien vu Karl Marx parmi les premiers à
démolir le mur de Berlin.

Mais ce n'est pas pour demain, car, vu sous cet angle, nous sommes
toujours dans la Rome antique : du pain et du cirque, des jeux et des
joints, même combat ! Que ferait la population sans match PSG (1) - OM
(2), sans ce bon vieux manichéisme gauche - droite, sans tous ces films
où les gentils (en bleu !) affrontent les méchants (en vert !), sans
tous ces divertissements continus qui coupent une bonne partie de la
population de questions plus essentielles ? Il y aurait un risque
qu'elle commence à réfléchir, la population, et même un risque plus
sérieux qu'elle s'ennuie. Non, ne me demandez pas d'être de droite, ne
me demandez pas d'être de gauche, ne me demandez pas de m'enfermer dans
cette vue étriquée. La seule question que l'on peut légitimement se
poser est : que peut-on faire pour améliorer le fonctionnement de la
société ? Une question qui implique de dépasser le parfum initial de
rose ou de maroilles pour aller rechercher le meilleur fromage dans
chaque crémerie. Si changer le monde n'a rien de facile, la tâche paraît
soudainement aisée lorsqu'on la compare au défi titanesque qui nous
propose de le rendre meilleur.

En attendant, que constate-t-on ? Beaucoup d'agitation, de gueulante,
d'antagonisme positivement démagogique, de slogans qu'on se répète
de bouche en bouche sans passer entre les oreilles, mais point d'idées
constructives. Ces idées sans qui nous ne sommes rien et n'allons nulle
part, ces idées sans qui les révolutions n'ont jamais mené qu'à des
bains de sang inutiles, des révoltes échouant lamentablement quand
elles ne sont pas récupérées par des candidats au pouvoir absolu. Ces
idées sans qui la prise de la Bastille ne serait qu'une émeute de plus
dans l'histoire de Paris, rangée dans la même catégorie nauséeuse
que ces fêtes exprimant l'euphorie populaire de voir se consumer sur
un bûcher de vilains hérétiques responsable de tous leurs maux. Les
boucs émissaires, cela ne vous rappelle rien ? Sans idée, on ne voit
plus que de la haine, qu'une soif de violence qui se cache mal sous
la première « bonne cause » venue, et les « à bas tout » de
service s'en donnent à coeur joie. Pour les propositions, vous pouvez
repasser dans quelques millénaires, ils en seront encore à s'étriper
pour pouvoir fixer la date de la prochaine réunion.

Non, n'essayez pas de me faire croire que tout détruire une enième fois
modifierait en profondeur la nature humaine, ne venez pas me dire que cela
mettrait fin à la tendance qui est sienne de se servir de ses voisins
comme tremplin pour sa propre gloriole. Ne venez pas me raconter que vous
avez découvert le seul et unique parti qui ne pratique pas l'esprit de
clan, ne venez pas me dire que c'en serait fini de ces assemblées où
les rares bonnes décisions qui y sont prises ne le sont pas pour de
bonnes raisons. L'intérêt personnel, la mauvaise foi, la corruption,
le copinage et le népotisme sont des valeurs sûres qui ont survécu
à tous les régimes. Quant à l'arbitraire, dites-vous bien que le les
extrêmes, de mai 40 au printemps de Prague, ne sont que deux tentacules
du même hydre.

#+BEGIN_CENTER
#+BEGIN_VERSE
    (1) Parti Socialiste de Gauche
    (2) Ouvriers Militants
#+END_VERSE
#+END_CENTER

*** Réponse à la réponse de Naej **

Quelques portes ouvertes qui méritent d'être rappelées, vu que les mêmes
erreurs ont tendance à se répéter lorsque l'enveloppe change de nom.
Mais tu me parles des grandes idées comme si il n'en existait qu'une
poignée dans un vase clos ! Où que l'on aille, il semble que l'on
n'entende plus que cette pique : « tout a été dit ». Ok, alors
taisons-nous tous, c'est le choix le plus raisonnable.

Non, même sans parler de génie, il y a de petites idées qui peuvent
aider, et parfois grandir, c'est à nous tous de laisser parler notre
imagination, d'apporter notre pierre. Cela ne demande que l'audace de
penser différemment, de sortir des sentiers battus.

Je suis d'accord pour dire que l'Homme pervertit les « systèmes », on
peut d'ailleurs voir une fonction de renouvellement inévitable dans
cette caractéristique. J'y apporte toutefois une précision : il y a des
matériaux plus facilement corrodables que d'autre ... je cherche l'or.

*** Réponse à la réponse d'Hernani **

Une impressionnante leçon d'histoire, le texte à beau être long, il
semble court à la lecture.

La question que tu poses sur la dualité homme - politique est centrale.
Ce qui est sûr, c'est qu'agir sans tenir aucun compte de l'aspect humain
est courir à l'échec. Je préfère l'idée de contrats sociaux émergeant du
libre choix d'un ensemble de citoyens à la ville platonicienne peuplée
de clones où toute individualité est noyée et soumise à une autorité
illimitée.

Pour éviter que ce libre choix ne mène à des errements, l'idéal serait
de lancer chacun sur la voie de la sagesse, et c'est probablement là la
tâche la plus délicate de tout progrès social.

En ce qui concerne la globalité d'une vision politique, je crois que la
plupart des avis convergeront pour dire qu'elle devient nécessaire à
partir du moment où l'économie l'est également. Sans cela, aucune
régulation n'est possible, les monopoles sont incontrôlables et les
délocalisations sortent de leur tanière.

Tu cites les coopératives, l'idée est excellente, et il est tout à fait
possible de les rendre viable via une fiscalité avantageuse, voire même
de les accoupler avec une société commerciale classique.

Le vin avait l'air effectivement excellent

Au plaisir !

*** Réponse à la réponse de Waiméa Bay **

Un monde sans frontière, j'en ai rêvé longtemps, avant de me rendre
compte qu'on ne peut les supprimer. Regarde n'importe quelle communauté,
l'humain recrée naturellement les mêmes conditions : des clans se
forment inévitablement autour d'autant de sujets, prétextes à favoriser
ses petits copains. Or, qui dit clan, dit frontière sournoise. Quant à
l'argent, il n'est qu'une facade pour les diverses convoitises de tout
un chacun, une facade souvent moins sale que le contenu de la vitrine.
Le supprimer n'empêchera pas le tout un chacun d'envier ce qui est
enviable : la piscine du voisin, le pouvoir de son sous-fifre de chef,
la gaieté de son collègue, la femme d'Hector ou le mari d'Andromaque.
J'en passe.

** Un peu d'essence et de principe

/La polis tique, tome 2/

Dans l'article précédent, j'énonçais la question qui devrait être à la
source de toute démarche politique honnête, à savoir en substance :

« Comment peut-on organiser le fonctionnement d'une communauté afin
d'assurer au mieux le bien-être de tous et de chacun en particulier ? »

La précision est vitale, dans la mesure où il est accordé autant
d'importance à l'individualité qu'à la collectivité. Toute politique qui
négligerait l'un ou l'autre de ces deux aspects courrait au chaos ou à
la tyrannie, autrement dit à l'échec.

Sur cette dualité individu - communauté viennent se greffer quelques
principes essentiels. Avant toute chose, rien ne peut fonctionner
correctement sans la présence de règles claires, simples, identiques
pour tous et laissant à chacun le plus de liberté possible. Mais ce qui
fait vivre un groupe ce sont les intéractions entre les personnes qui le
constitue. Parmi elles, je retiendrai les valeurs qui me paraissent les
plus importantes : le partage et l'échange. Afin d'éviter ou au moins
d'atténuer les travers dans lesquels se sont enlisées trop de
civilisations, il me paraît également nécessaire de généraliser un
principe démocratique bien connu en interdisant l'accumulation de trop
de pouvoir en trop peu de mains, et ce quelle que soit la nature du
pouvoir en question : politique, économique, financier ou autre.

Pour mieux comprendre la nécessité de ces principes, choisissons
quelques modèles de société où ils n'apparaissent pas. Nous ne nous
attarderons pas sur la concentration du pouvoir, concentration qui
conduit par définition à un régime oligarchique ou autoritaire ; si
démocratie il y a, elle ne sera que de façade.

Ensuite, supposons si cela est possible une société où le partage est
interdit. C'est le règne du chacun pour soi, tout le monde il veut
garder ses petits secrets et le savoir ne se propage que très lentement.
En clair, c'est la ruine à plus ou moins long terme. Comme si cela ne
suffisait pas, toute action commune, et donc toute contestation, tout
débat est interdit. La communauté elle-même se voit niée, ce qui ne peut
déboucher que sur le chaos, cette mixture instable d'où émergent les
habituels potentats de village, de région, de province, autrement dit un
féodalisme qui comme chacun sait ne brille ni par son équité, ni par ses
capacités de progrès social.

Considérons à présent un système où l'échange est hors-la-loi. Dans le
meilleur des cas, on se retrouve avec une société égalitaire jusqu'à
l'excès où les ressources sont allouées uniformément. Il n'est pas tenu
compte des préférences de chacun, et la population fait face à un choix
cornélien : abandonner toute diversité et accepter le mal-être qui en
découle, ou développer un marché noir, fragmenté, à la merci de
monopoles, d'escrocs et de magouilleurs de tous poils. Abstraction faite
de l'aspect légal, ces marchés décentralisés, opaques, facilement
manipulables de par leur illiquidité et l'absence de régulation, ces
marchés instables et iniques sont l'une des causes de la crise
financière actuelle.

Cette situation lamentable est à l'opposé d'un marché optimal respectant
les principes de transparence et évitant toute concentration excessive
du pouvoir commercial. Le premier critère implique une centralisation et
une mise à disposition du public des informations, le second nécessite
une fragmentation fine de l'offre et de la demande.

Une bonne partie des inégalités actuelles provient d'un manque à ces
principes : les états possédant des lois anti-monopoles ne les
appliquent pas, ou pas suffisamment, à plus petite échelle les deux
boulangers du coin s'entendent trop cordialement pour se faire
concurrence, la chaîne de distribution est trop puissante par rapport au
petit fermier qu'on pousse vers la culture industrielle, etc. Au niveau
des sociétés, la main-mise des actionnaires n'est pas contrebalancée par
un pouvoir réel du personnel, les mandats croisés dans les conseils
d'administration sont aussi communs qu'en politique et pourtant personne
ne semble s'indigner des collusions d'intérêt que cela génère. Sans
compter la misère, car rien ou presque n'est fait pour aider les gens
qui dorment dans des cartons ... Si la liste est longue, les causes se
ressemblent.

Et pourtant, il existe des solutions à ces problèmes : interdire tout
cumul de mandat, qu'il soit politique, économique ou autre, développer
comme modèle commercial des sociétés contrôlées à la fois par le
personnel et les actionnaires, à mi-chemin entre la coopérative et la
société anonyme, améliorer l'ISF et éliminer les défauts qui lui sont
reprochés, etc.

Rien de tout cela ne nécessite de grands cris révolutionnaires, juste
des réformes et la détermination de la population à les faires
appliquer. Malheureusement, il semble plus facile de hurler contre des
ennemis confus comme l'économie ou le système, éternels boucs émissaires
d'une colère aveugle. Pourtant, personne n'a jamais vu cette vieille
dame ou ce mystérieux monsieur mettre la main dans nos poches ou
comploter dans les couloirs. Comme tout autre outil, ce sont des bras
humains qui les actionnent, des bras semblables aux vôtres. Ce qui nous
amène à une autre question pertinente : pourquoi les peuples
connaissent-ils si mal les rouages de l'état, pourquoi des matières
aussi importantes que le droit ou l'économie ne figurent pas ou si peu
dans les programmes scolaires ? Voilà une question qui montre du doigt
les déficiences de l'éducation et la menace que ces lacunes représentent
pour la démocratie.

*** Réponse à Hernani **

Ta cave est toujours aussi excellente Hernani ! Il est intéressant de
comparer les rôles de la campagne et de la ville dans la grèce antique
et à la fin du 18e siècle. En ce qui concerne la fragmentation du
pouvoir, j'ai pensé à ajouter les média à ma liste : ils tombent dans le
champ d'application des sociétés commerciales, mais c'est un cas
particulier important de concentration excessive. Les grands groupes se
sont encore renforcé ces dernières années, à ce train là tous les
journeaux vont finir par se ressembler si ce n'est déjà fait. On peut
également tenter de voir un autre parallélisme dans les associations
incestueuses église - monarchie // multinationales - politique. Que de
choses à dire ... trinquons aux âges d'or à venir !

*** Réponse à Justine **

Justine, je n'ai pas encore évoqué la notion de monnaie, mais dans tout
système d'échange une référence à tendance à s'imposer, et il y a une
raison mathématique à cela : il est plus simple de comparer N
possibilités par rapport à un standard que de comparer chaque
possibilité par rapport aux N autres, ce qui nous donne un ordre de
grandeur de N^{2} comparaisons.

N = 1000, ce qui n'est pas beaucoup, nous donnerait 1 million pour
N^{2}, je te laisse imaginer le bidule.

J'ai pris le parti dans ces articles d'adapter une approche à la fois
créative et pragmatique, innover tout en tenant compte des réussites et
erreurs du passé, mais je n'ai rien contre le /free your mind/ pur et
dur, tu as bien fait de le replacer au devant de la scène. N'hésite pas
si tu as des suggestions.

*** Réponse à Jean **

Jean, un cercle ou une spirale ? Les siècles se ressemblent et sont si
différents ... Je pense réellement qu'il y a comme un tournant dans
l'air, espérons qu'il sera positif. Avec le temps, tout se détourne en
effet, même dans le meilleur des mondes il y aura toujours des gens qui
n'auront rien de mieux à faire. Un système qui n'est pas capable de se
renouveler s'érodera lentement mais sûrement.

*** Réponse à Hernani **

Hernani, mais qui parle d'autogouvernement parle déjà d'une autorité de
groupe, la frontière est plus diffuse qu'on pourrait le penser à
première vue.

Le pouvoir devrait ne révéler que de l'organisation et d'un devoir
envers la collectivité, mais les symboles qui l'entourent faussent le
jeu. Tout comme argent, il prend des proportions démesurées dans
l'inconscient collectif. Il ne faut pas se leurrer, la société est d'un
naturel moutonnier qui n'attend que la première autorité crédible pour
la suivre. L'aura des hautes sphères et tout ce qu'elle confère ne fait
qu'attirer dans sa lumière des papillons qui s'y laissent prendre pour
de mauvaises raisons. D'où l'image ambiguë que ce milieu véhicule.

Pour les cataclysmes, les gouvernements ne peuvent évidemment pas grand
chose, mais ils pourraient beaucoup avec plus de créativité, comme tu le
soulignes avec Coluche (que n'a-t-il été élu président ...). Ils
pourraient plus encore si il existait une réelle coordination mondiale.
Mais une telle puissance serait à double tranchant, d'autant que les
peuples n'auraient pas un contrôle direct sur ces instances. Une «
démocratie » indirecte, on a vu ce que cela peut donner au niveau de
l'Union Européenne : des coulisses pratiques pour jouer sur plusieurs
tableaux.

** Des solutions, il y en a

Notre monde va mal, très mal. C'est être une autruche que de ne pas s'en
rendre compte. Vous voulez de vraies solutions ? En voila, chacune
correspondant à son propre problème. Quelques solutions parmi d'autres,
qui sont un début de réponse pourvu qu'elles soient pensées de manière
/globale/.

L'accroissement galopant de la population face aux ressources limitées
de notre planète. La solution est simple : un enfant par couple pendant
deux ou trois générations, et nous revenons au nombre plus raisonnable
de 1 milliard d'habitant. C'est un sacrifice (bien qu'à mon sens ce soit
un grand mot) nécessaire : il suffit d'analyser le comportement des
foules pour réaliser que la surpopulation entraîne l'aggressivité, puis
la violence, puis le masssacre. La vraie question est : préférez-vous un
enfant qui vivra bien ou trois qui courront au massacre ?

Ne signer des accords qu'économiques qu'avec les /vraies/ démocraties,
afin de faire pression sur les dictatures. L'OMC bafoue actuellement ce
principe, il suffit de voir que des dictatures en font partie, ce qui
subventionne l'exploitation des travailleurs locaux, pour ne pas dire
l'esclavagisme.

La réduction généralisée du temps de travail à 10 ou 20 heures. La
barrière des mentalités se dresse ici, encore une fois : il faut arriver
à considérer le travail, non plus comme une vertu comme c'est le cas
actuellement, mais comme ce qu'il est en réalité, c'est-à-dire une
corvée. Nous avons actuellement les moyens technologiques de nous
libérer de ces contraintes, seuls des principes arriérés nous en
empêchent.

La répartition des ressources. Point Ô combien sensible. Le système
économique actuel à ses qualités bien entendu, mais il est très
instable. Une régulation qui consisterait à pomper parmi les plus
grandes fortunes pour réinjecter parmi les plus pauvres suffirait à le
stabiliser. Il suffit d'introduire un paramètre de rapport de richesse
et la machine tournera toute seule.

Nous vivons dans un domino géant ou tout peut basculer, parfois dans des
directions imprévisibles. Même une bonne intention peut parfois
provoquer des catastrophes. Le système actuel est améliorable, mais si
on veut le modifier, il me semble essentiel de proposer des solutions
cohérentes au niveau mondial, et ne pas se contenter de réfléchir
localement (tant au niveau géographique que logique).

Vous vivez dans une démocratie. Nos ancêtres n'étaient certes pas tous
des saints (qui l'est ?) mais ils nous ont laissé cet inestimable
cadeau. Elle est malade, certes, mais il ne tient qu'à son peuple de la
revitaliser en sortant du schéma de pensée droite-gauche qui ne permets
à aucune idée nouvelle de se développer.

Vivre dans une démocratie vous donne non seulement le droit de voter (ne
ricanez pas, cela a beaucoup plus de poids que vous ne le pensez), mais
aussi de vous réunir autour d'idées semblables et de désigner vous-mêmes
vos propres candidats. Des gens que vous connaissez et dont vous savez
la valeur. Plus des barons qui donnent des consignes. Les barrières que
vous rencontrerez ne seront pas, comme vous le pensez, le manque de
moyen financier ou le mépris de la classe politique actuelle. Non, ce
sera l'intégrité de vos candidats. Quoi que vous en pensiez, la plupart
d'entre-eux ne résisteront pas à l'appel de la corruption. Ce sera aussi
l'appétit du pouvoir, l'ambition irrésistible de se retrouver au
gouvernement où vous ne seriez dans un premier temps que de la
décoration. Le vrai pouvoir est l'influence de l'ombre, pas celle des
projecteurs. Ce sera encore la volonté d'arriver au niveau national,
alors que la priorité est d'amener un maximum de pays influents à
adhérer à vos idées. Mais surtout, le principal obstacle qui se
présentera à vous, c'est qu'il est plus facile de réunir des millions de
personnes pour répandre leur haine que pour répandre leurs idées et leur
volonté de construire l'avenir.

* Finance

#+TOC: headlines 1 local

** Les raisons de l'abandon de l'étalon-or

Contrairement à une idée répandue, l'or et les autres métaux précieux
n'ont pas toujours été reconnu comme une monnaie d'échange universelle :

-  l'Égypte antique lui conférait un coté sacré, divin, et le réservait
   exclusivement aux cérémonies religieuses, et leur système économique,
   bien que très différent du nôtre, a permis à cette civilisation de
   prospérer pendant des millénaires
-  certains peuples se servaient de coquilles d'huîtres ou d'autres
   mollusques pour régler leurs transactions
-  d'autres encore utilisaient des céréales, peaux, dents, plumes, ...
-  plus près de nous, le paquet de cigarettes était fort utilisé dans le
   marché noir des pays de l'est, avant la chute du communisme

Toutes ces monnaies exotiques possédaient en communs ces critères
essentiels :

-  il fallait produire un effort de production (pêche, chasse, ...) ou
   un échange pour en obtenir
-  elle était suffisamment abondante pour permettre à l'économie de se
   développer

Quand on y réfléchit, on voit que ce sont ces conditions qui assurent la
stabilité d'un système monétaire : une monnaie gratuite ou trop
facilement accessible finit par introduire une hyper-inflation ; à
l'inverse, une liquidité insuffisante empêche l'économie de se
développer correctement.

Du fait de l'adoption pendant l'antiquité et le moyen-âge des monnaies
métalliques (or, argent, cuivre, bronze, ...), ce second point posa
régulièrement problème au fil de l'histoire : la production des mines ne
suffisait plus à alimenter la liquidité de l'économie. Les rois se
mirent alors à rogner de plus en plus la part de métaux précieux dans
les pièces afin d'en augmenter la quantité et surtout de remplir les
caisses de l'état, souvent vidées par les guerres incessantes. Le
développement des banques et de leurs produits financiers, ancêtres du
billet de banque actuel (lettre de change inventées par les templiers,
billets à ordre) apporta également une bulle d'oxygène au système, car
une banque prête généralement plus que ce qu'elle n'a en dépôt, ce qui
produit un effet multiplicateur sur la masse monétaire.

A partir du 19e siècle, le développement industriel explosif mis de plus
en plus en évidence la rareté de l'or par rapport aux besoins en
liquidités de l'économie.

Après la guerre 14, l'Allemagne, confrontée à une hyperinflation se vit
face à la nécessité de créer une nouvelle monnaie. Certes, il fallait
garantir cette monnaie par quelque chose de tangible. Oui, mais sur quoi
? Les réserves en or avaient été vidée suite au paiement exigé par le
traité de Versailles. Faute de métaux précieux, ils décidèrent donc que
la garantie serait une fraction (6 % des parts) de l'économie elle-même
: immobilier, entreprises, mines, production, ... La boucle était
bouclée et la nouvelle monnaie, le rentenmark, fut adoptée aisément par
la population.

L'ironie de l'histoire est que cette solution, adoptée comme une
rustine, se révèle en fait supérieure à la garantie or, car la valeur
des biens économiques, de loin supérieure à la quantité d'or disponible
sur la planète, permet une liquidité plus abondante et un développement
économique beaucoup plus souple.

Dernier acte, dans les années 70, où il apparaît clairement que la
quantité d'or disponible ne répond plus aux besoins économiques :
l'étalon or est abandonné par les USA, les changes deviennent flottants.

Aujourd'hui, on peut voir que, contrairement à une idée répandue, c'est
la rareté de l'or qui a provoqué sa chute en tant que monnaie. Demain,
si le système actuel apparaissait de plus en plus instable, peut-être
seront-nous amené à créer un « rentenmark » mondial.

** La vente à découvert

En ces temps de crise, les boucs émissaires fleurissent à tous les coins
de rue, et ces horribles sorciers de vendeurs à découverts figurent en
bonne position sur la liste : vilains, pas beaux, ils ont tous les
défauts que l'ignorance voudra bien lui /prêter/.

Car c'est bien de prêt qu'il s'agit : vendre à découvert revient,
directement ou indirectement, à emprunter un titre pour le vendre sur le
marché, dans le but avoué de le racheter plus tard, et surtout plus bas.
Il en résulte donc bel et bien une offre de titres surnuméraire, et il
n'en faut pas plus aux démagoges de tous les horizons pour nous sortir
des raccourcis et des conclusions simplistes, conclusions relayées par
les inévitables perroquets de service et autres volatiles toujours en
quête de perches pour se mettre en valeur.

Ainsi, la vente à découvert, ou « vade » comme on dit dans le jargon
financier, est responsable de tous les maux : cracks boursiers, crises,
récessions, épuisement des matières premières, problèmes écologiques.
Qu'on se le dise : la vade est la cheville ouvrière du grand complot
international-mondial de l'univers intergalactique ! C'est elle qui
alimente les bulles spéculatives, c'est elle qui oblige les banques à
prendre des risques inconsidérés sur des marchés illiquides et
dérégulés, c'est elle qui est la cause de la dégradation des comptes des
sociétés, c'est elle qui, point barre et sans discussion possible !

Trêve de plaisanteries et revenons à la réalité. Ce que les démagogues
ne vous disent pas, c'est que cette offre accrue implique également une
hausse de la demande. En fait, toute action vendue à découvert est
rachetée tôt ou tard, et ce d'autant plus vite que, comme tout emprunt,
l'emprunt de titre a un coût. Les intervenants ne peuvent donc pas
s'éterniser dans une vade sans voir s'amenuiser leur bénéfice ou se
creuser leurs pertes.

Les démagogues ne vous disent pas que plus la demande d'emprunt de
titres sera élevée, plus le taux d'intérêt correspondant grimpera,
rendant de moins en moins avantageuse une telle opération. La caricature
d'un marché constitué presque exclusivement de vadeurs affamés salivant
des crocs ne tient pas la route, car les taux pratiqués seraient alors
si élevés que la probabilité de gain frôlerait le zéro absolu. Avec des
taux élevés, non seulement les détenteurs d'actions ont plus intérêt à
prêter leurs titres qu'à les vendre, ce qui a pour effet d'assécher un
peu plus l'offre sur le marché au comptant, mais les intervenants ont
également tendance à acheter des titres afin de pouvoir les prêter et
d'en tirer une rémunération conséquente. Toutes choses inchangées par
ailleurs, on assisterait alors à une hausse spectaculaire des cours.

Interdire la vade n'aboutirait donc qu'à diminuer la liquidité des
marchés financiers, et par là même à diminuer l'attrait des titres
eux-mêmes. On l'a vu récemment, l'interdiction de la vente à découvert
des bancaires n'a pas le moins du monde ralenti leur chute, bien au
contraire.

Ce qui serait intéressant par contre, ce serait de permettre aux
particuliers de prêter aisément les titres qu'ils possèdent, histoire
d'arrondir les dividendes.

Si vous voulez vraiment assainir économie et finance, c'est ailleurs
qu'il vous faudra chercher. Et si nous parlions des monopoles, des
effets de leviers sans limite légale, des mandats cumulés, ce serait
plus intéressant que tous ces écrans de fumée.

** Réponse à l'argument « tu ne vends pas une maison que tu ne possèdes
pas

Une maison n'est pas liquide, ni fongible, tu n'as pas deux baraques
pareilles, ce qui n'est pas le cas des titres ou contrats standardisés.

** La face cachée de l'analyse fondamentale

On en revient toujours au même problème, une action ne peut se valoriser
que par des données futures donc inconnues, que ce soit dividendes ou
cours, autrement dit elle ne peut pas se valoriser, d'où l'extrême
volatilité dont elle souffre.

Le problème du cours présent dépendant du cours futur pose aussi le
problème d'auto-référence qui peut provoquer des exagérations à la
hausse comme à la baisse.

Sans compter que les actions n'ont pas la même valeur unitaire quand on
détient 0,01 % ou 70 % d'une société. Dans le premier cas, le dividende
prime, dans le second, c'est le bénéfice puisqu'on sait qu'on pourra le
faire sortir de la société quand on le désire.

Le titre qui permet de passer de 49,99 % à 50,01 % est en fait celui qui
a le plus de valeur intrinsèque pour le détenteur tout en n'ayant pas
d'attrait particulier pour un quelconque petit porteur.

La valorisation générique d'une action n'est donc pas seulement
inconnue, elle est inexistante.

* Délires

#+TOC:headlines 1 local

** Nominations

Pour combattre l'assèchement des nominations qui menace le site suite
aux arbitraires tours de vis monétaires que nous inflige la franchise
ultralibéraliste caviarisée, j'ai pris la décision de tout nominer. Les
grands, les petits, les affreux et les jolies, les provocateurs et les
gentils animateurs de polémique, les grandes gueules et les fantômes,
les doubles et les triples comptes, les copains et ceux que je ne peux
pas encadrer. Je pousserai même l'abnégation jusqu'aux ségolénistes et
aux sarkozistes. J'en frémis d'aise tellement je trouve mon courage
admirable. La planche à billets doux tournera, le podium croulera sous
le poids de la machine emballée. L'hyper-inflation inondera le site
d'une variante de Serge ("je te nomine, moi non plus") ! Dès demain, le
plus symbolique des commentaires auto-promotionnels s'échangera contre
des brouettes entières de nominations dans l'ascenceur fantasmagorique
de l'émotionitude lpdpienne. Que l'on pousse le surréalisme jusqu'à
l'ivresse, l'écoeurement jusqu'aux tréfonds moites de l'absurdité. Après
viendra l'apaisement sur la terre brûlée.

** Critiques et comment se taire

Pour replacer les choses dans un contexte historique, cette règle n'est
pas récente. Si je me rappelle bien, elle a été instaurée justement pour
autoriser les critiques constructives à une époque où la moindre pique
avait tendance à déraper en guerre des tranchées entre clans,
sous-clans, clans transversaux et j'en passe, un vrai nid de guêpes. A
chaque fois une vague de départ, et on repartait pour un tour. Avec ce
sigle, c'est une frontière élastique qui a été instaurée, et un
compromis entre d'un coté les hyperboles insipides et de l'autre les
réglements de compte sous couvert de critique.

** Entrée en scène

Tout cela vaudrait quelques romans fleuves en crue : parler du
funambulisme des contraires, de l'acrobatie des opposés, de la glace qui
brûle et du feu qui apaise les frissons ; des impossibilités apparentes,
des magiciens qui soufflent sur les dés du hasard, des mots-prétextes
dans lesquels on fourre toutes les bassesses avant de refermer les
tiroirs et de leurs coller des étiquettes ; des vieilles pierres où
pleurent des fantômes d'autres histoires et d'autres lieux ; des
théories fumeuses sur des sentiments trop souvent négocié sur le marché
de l'affectif pragmatique ; des fleurs qui piquent comme des guêpes, des
délires cosmiques, des lutins qui dansent la sarabande dans de longues
phrases énumératives sans queue ni tête. A propos, longues vies aux
chats, na !

#+BEGIN_CENTER
#+BEGIN_VERSE
    - oui ???

    - c’est a toi

    - hein déjà ??? mais je connais pas mon texte !!! ou est le souffleur ?

    - y en a pas

    - et comment je fais alors ???

    - tu improvises, comme tout le monde

    - ha ben je suis nul en impro moi, clavier ou pas

    - tu te démerdes, rideau !
#+END_VERSE
#+END_CENTER

#+BEGIN_CENTER
#+BEGIN_VERSE
    *******************

    Ô rage Ô désespoir, que vous dire ?
    que je suis un peu dingue, c’est évident
    que je fais des études de folie douce pour l'être encore plus, c’est peut-être une info
    que je suis souvent dans la lune, c’est facile à deviner
    que mon vrai nom c’est chimay et que j’apprécie les produits régionaux,
    c’est un secret de polichinelle
    bon ben quoi alors ?
    que je suis ravi de me retrouver parmi vous

    A vous dés lyres ...
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
