
#+STARTUP: showall

#+TITLE: Eclats de vers : Article : Délire
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Nominations

Pour combattre l'assèchement des nominations qui menace le site suite
aux arbitraires tours de vis monétaires que nous inflige la franchise
ultralibéraliste caviarisée, j'ai pris la décision de tout nominer. Les
grands, les petits, les affreux et les jolies, les provocateurs et les
gentils animateurs de polémique, les grandes gueules et les fantômes,
les doubles et les triples comptes, les copains et ceux que je ne peux
pas encadrer. Je pousserai même l'abnégation jusqu'aux ségolénistes et
aux sarkozistes. J'en frémis d'aise tellement je trouve mon courage
admirable. La planche à billets doux tournera, le podium croulera sous
le poids de la machine emballée. L'hyper-inflation inondera le site
d'une variante de Serge ("je te nomine, moi non plus") ! Dès demain, le
plus symbolique des commentaires auto-promotionnels s'échangera contre
des brouettes entières de nominations dans l'ascenceur fantasmagorique
de l'émotionitude lpdpienne. Que l'on pousse le surréalisme jusqu'à
l'ivresse, l'écoeurement jusqu'aux tréfonds moites de l'absurdité. Après
viendra l'apaisement sur la terre brûlée.

* Critiques et comment se taire

Pour replacer les choses dans un contexte historique, cette règle n'est
pas récente. Si je me rappelle bien, elle a été instaurée justement pour
autoriser les critiques constructives à une époque où la moindre pique
avait tendance à déraper en guerre des tranchées entre clans,
sous-clans, clans transversaux et j'en passe, un vrai nid de guêpes. A
chaque fois une vague de départ, et on repartait pour un tour. Avec ce
sigle, c'est une frontière élastique qui a été instaurée, et un
compromis entre d'un coté les hyperboles insipides et de l'autre les
réglements de compte sous couvert de critique.

* Entrée en scène

Tout cela vaudrait quelques romans fleuves en crue : parler du
funambulisme des contraires, de l'acrobatie des opposés, de la glace qui
brûle et du feu qui apaise les frissons ; des impossibilités apparentes,
des magiciens qui soufflent sur les dés du hasard, des mots-prétextes
dans lesquels on fourre toutes les bassesses avant de refermer les
tiroirs et de leurs coller des étiquettes ; des vieilles pierres où
pleurent des fantômes d'autres histoires et d'autres lieux ; des
théories fumeuses sur des sentiments trop souvent négocié sur le marché
de l'affectif pragmatique ; des fleurs qui piquent comme des guêpes, des
délires cosmiques, des lutins qui dansent la sarabande dans de longues
phrases énumératives sans queue ni tête. A propos, longues vies aux
chats, na !

#+BEGIN_CENTER
#+BEGIN_VERSE
    - oui ???

    - c’est a toi

    - hein déjà ??? mais je connais pas mon texte !!! ou est le souffleur ?

    - y en a pas

    - et comment je fais alors ???

    - tu improvises, comme tout le monde

    - ha ben je suis nul en impro moi, clavier ou pas

    - tu te démerdes, rideau !
#+END_VERSE
#+END_CENTER

#+BEGIN_CENTER
#+BEGIN_VERSE
    *******************

    Ô rage Ô désespoir, que vous dire ?
    que je suis un peu dingue, c’est évident
    que je fais des études de folie douce pour l'être encore plus, c’est peut-être une info
    que je suis souvent dans la lune, c’est facile à deviner
    que mon vrai nom c’est chimay et que j’apprécie les produits régionaux,
    c’est un secret de polichinelle
    bon ben quoi alors ?
    que je suis ravi de me retrouver parmi vous

    A vous dés lyres ...
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
