
#+STARTUP: showall

#+TITLE: Eclats de vers : Article : Agora
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* La diplomatie

Je vois que tu as en tête le cas particulier, il est vrai le plus
fréquent, où au moins une des parties ne peut être pleinement satisfaite
de l'accord. Elle est alors lésée par rapport à ce qu'elle ambitionnait,
mais y gagne généralement si on compare les termes de l'accord à la
situation antérieure. Si ce n'était pas le cas, l'accord n'aurait
probablement pas été conclu. Il y a donc relativité de la concession.
J'y reviendrai, mais je tiens tout d'abord à donner un exemple de cas où
aucune partie n'est lésée, même relativement à ses espérances.

** Solution sans concession

Ma petite fable fait intervenir soeur Sourire et frère Soupir. Soeur
Sourire adore le jardinage et la bronzette. Frère Soupir aime le calme
et l'ombre propice à ses études. Tous deux souhaitent acheter le même
petit coin de paradis pour y construire la villa de leurs rêves, celle
de Soeur Sourire étant vous vous en doutez fort différente de celle de
frère Soupir. Le problème est qu'aucun des deux pris séparément n'a
suffisamment de fonds pour cela. Chacun souhaite emprunter la somme
nécessaire à son concurrent, mais tous deux refusent, évidemment. Vient
alors le frérot architecte qui leur propose d'acheter le terrain à deux
et d'y construire un immeuble de deux étages, concept totalement nouveau
à l'époque de notre fable. Soeur Sourire occupera le second, aura un
jardin sur le toit et du soleil à profusion, tandis que Frère Soupir
sera bien au frais, abrité par l'étage supérieur de la chaleur estivale.
Aucun d'eux n'a fait de concession, et la solution est encore supérieure
à leurs attentes.

Tout cela pour dire qu'une diplomatie idéale se doit d'être innovante.
Un tel cas peut sembler rare, mais cela doit malgré tout rester un
objectif à atteindre. Même dans une situation plus réaliste, l'idée
reste toujours de maximiser les avantages en minimisant les concessions.

** Relativité de la concession

Pour illustrer la relativité de la concession, imaginons deux fermiers
qui exploitent un terrain commun. Ils souhaitent le vendre et trouvent
un acheteur à bon prix. Tout cela semble idyllique, mais chacun des deux
fermiers prétend avoir travaillé plus dur que l'autre depuis plusieurs
saisons, et réclame 70 % du produit de la vente. Si ils n'acceptent pas
tous deux de revenir à 50 %, la vente ne sera pas possible. Il y a alors
deux visions duales des choses.

Dans la vision psychologique, chacun des fermiers a l'impression de
devoir faire une concession pour pouvoir vendre le terrain.

Dans la vision épurée, l'alternative est simple : soit ils touchent
chacun la moitié de la vente, soit ils ne touchent rien du tout.

Dans la première situation, il y a concession. Dans la seconde, seul
apparaît le gain réalisé par rapport à l'absence d'accord.

** Discussion

La discussion ne poursuit pas le même but que la diplomatie. Dans ce cas
nous sommes d'accord, il n'y a pas à concéder, en première lecture du
moins. Par après, on peut toujours réfléchir sur les arguments de
l'autre et voir si ils nous apportent quelque chose, je ne vois pas cela
comme une concession.

** Respect

Ce n'est pas vraiment la propriété de la porte qui compte, si tu as un
invité qui dort chez toi, tu ne vas pas le réveiller pour aller aérer si
tu as trop chaud, simple question d'intimité.

Pour en revenir au voisin, je dirais que si tu t'abstiens d'aller le
déranger pour éviter de recevoir le lendemain le paquet cadeau de son
labrador sur ton paillasson, tu obéis alors effectivement à un pacte
tacite. Si tu t'en abstiens par empathie avant même de penser au code
social, si tu t'en abstiens parce que tu te mets à sa place et que tu
n'aimerais pas non plus qu'il fasse intrusion, l'affaire est totalement
différente. Il s'agit alors d'une conscience de l'autre, et non plus
d'obéissance, ce qui rejoint, ou plutôt étend le concept d'amour à une
notion beaucoup large. C'est assez proche de ce que tu expose avec les
« fils tremblants ».

Ah, l'amour, un des termes les plus employés, mais aussi un des plus
vagues dans sa définition. Nous avons tous nos propres acceptations de
chaque mot, mais avec celui-là, le flou est d'autant plus grand que les
concepts qu'il implique sont nombreux et interdépendants.

** Franchise

On peut certes amener sa franchise comme on le souhaite, mais si on le
fait en blessant l'interlocuteur, on aura beau lui dire par après que la
terre est ronde, il ne le croira plus. J'exagère, mais l'esprit est
ainsi fait qu'il se défend face à ce qu'il considère comme une
agression. Même si le but n'est pas de convaincre, cette blessure
est-elle souhaitable ? On pourrait répondre non dans le cas général, oui
dans le cas ou se taire est pire. C'est une question ouverte, chacun
aura sa réponse en fonction des circonstances.

* Le marteau et ses faux cils

/La polis tique, tome 1/

« Moi, je ne suis pas Marxiste ». Cette citation, d'apparence tout à
fait anodine, prend tout son sel lorsqu'on apprend qu'elle provient de
Karl Marx lui-même. À première vue, on peut y voir une volonté de se
démarquer de l'interprétation qu'il estimait frauduleuse de certains de
ses émules. Mais on peut aussi y reconnaître le philosophe, encore plus
attaché au principe de l'idée libre qu'à ses propres théories. Car
enfin, cette phrase n'est-elle pas une façon de dire : « je ne veux pas
que l'on me suive aveuglément, je ne veux pas que l'on me suive sans
réfléchir, je ne veux pas que l'on me suive intégralement sans remettre
en question la plus infime de mes pensées, en fait je ne veux pas que
l'on me suive tout court. » ? Vue ainsi, elle se métamorphose en une
attaque virulente contre ces partis et ces religions où l'on vous
explique quoi penser, quoi critiquer, qui aimer. Une petite phrase
d'apparence banale, mais qui donne une autre dimension à l'histoire. Et,
en dépit de cette envergure, une tentative dérisoire de lutter contre la
bêtise universelle. Sans augurer d'un avenir vraisemblablement lointain,
une chose est sûre : le monde se portera mieux le jour où textes
politiques et religieux seront lus avec un minimum de discernement, une
once de distance, une pincée de philosophie. N'en déplaise à Audiard, un
intellectuel assis ira toujours plus loin qu'une bande de cons qui
tourne en rond. Oui, j'aurais bien vu Karl Marx parmi les premiers à
démolir le mur de Berlin.

Mais ce n'est pas pour demain, car, vu sous cet angle, nous sommes
toujours dans la Rome antique : du pain et du cirque, des jeux et des
joints, même combat ! Que ferait la population sans match PSG (1) - OM
(2), sans ce bon vieux manichéisme gauche - droite, sans tous ces films
où les gentils (en bleu !) affrontent les méchants (en vert !), sans
tous ces divertissements continus qui coupent une bonne partie de la
population de questions plus essentielles ? Il y aurait un risque
qu'elle commence à réfléchir, la population, et même un risque plus
sérieux qu'elle s'ennuie. Non, ne me demandez pas d'être de droite, ne
me demandez pas d'être de gauche, ne me demandez pas de m'enfermer dans
cette vue étriquée. La seule question que l'on peut légitimement se
poser est : que peut-on faire pour améliorer le fonctionnement de la
société ? Une question qui implique de dépasser le parfum initial de
rose ou de maroilles pour aller rechercher le meilleur fromage dans
chaque crémerie. Si changer le monde n'a rien de facile, la tâche paraît
soudainement aisée lorsqu'on la compare au défi titanesque qui nous
propose de le rendre meilleur.

En attendant, que constate-t-on ? Beaucoup d'agitation, de gueulante,
d'antagonisme positivement démagogique, de slogans qu'on se répète
de bouche en bouche sans passer entre les oreilles, mais point d'idées
constructives. Ces idées sans qui nous ne sommes rien et n'allons nulle
part, ces idées sans qui les révolutions n'ont jamais mené qu'à des
bains de sang inutiles, des révoltes échouant lamentablement quand
elles ne sont pas récupérées par des candidats au pouvoir absolu. Ces
idées sans qui la prise de la Bastille ne serait qu'une émeute de plus
dans l'histoire de Paris, rangée dans la même catégorie nauséeuse
que ces fêtes exprimant l'euphorie populaire de voir se consumer sur
un bûcher de vilains hérétiques responsable de tous leurs maux. Les
boucs émissaires, cela ne vous rappelle rien ? Sans idée, on ne voit
plus que de la haine, qu'une soif de violence qui se cache mal sous
la première « bonne cause » venue, et les « à bas tout » de
service s'en donnent à coeur joie. Pour les propositions, vous pouvez
repasser dans quelques millénaires, ils en seront encore à s'étriper
pour pouvoir fixer la date de la prochaine réunion.

Non, n'essayez pas de me faire croire que tout détruire une enième fois
modifierait en profondeur la nature humaine, ne venez pas me dire que cela
mettrait fin à la tendance qui est sienne de se servir de ses voisins
comme tremplin pour sa propre gloriole. Ne venez pas me raconter que vous
avez découvert le seul et unique parti qui ne pratique pas l'esprit de
clan, ne venez pas me dire que c'en serait fini de ces assemblées où
les rares bonnes décisions qui y sont prises ne le sont pas pour de
bonnes raisons. L'intérêt personnel, la mauvaise foi, la corruption,
le copinage et le népotisme sont des valeurs sûres qui ont survécu
à tous les régimes. Quant à l'arbitraire, dites-vous bien que le les
extrêmes, de mai 40 au printemps de Prague, ne sont que deux tentacules
du même hydre.

#+BEGIN_CENTER
#+BEGIN_VERSE
    (1) Parti Socialiste de Gauche
    (2) Ouvriers Militants
#+END_VERSE
#+END_CENTER

** Réponse à la réponse de Naej **

Quelques portes ouvertes qui méritent d'être rappelées, vu que les mêmes
erreurs ont tendance à se répéter lorsque l'enveloppe change de nom.
Mais tu me parles des grandes idées comme si il n'en existait qu'une
poignée dans un vase clos ! Où que l'on aille, il semble que l'on
n'entende plus que cette pique : « tout a été dit ». Ok, alors
taisons-nous tous, c'est le choix le plus raisonnable.

Non, même sans parler de génie, il y a de petites idées qui peuvent
aider, et parfois grandir, c'est à nous tous de laisser parler notre
imagination, d'apporter notre pierre. Cela ne demande que l'audace de
penser différemment, de sortir des sentiers battus.

Je suis d'accord pour dire que l'Homme pervertit les « systèmes », on
peut d'ailleurs voir une fonction de renouvellement inévitable dans
cette caractéristique. J'y apporte toutefois une précision : il y a des
matériaux plus facilement corrodables que d'autre ... je cherche l'or.

** Réponse à la réponse d'Hernani **

Une impressionnante leçon d'histoire, le texte à beau être long, il
semble court à la lecture.

La question que tu poses sur la dualité homme - politique est centrale.
Ce qui est sûr, c'est qu'agir sans tenir aucun compte de l'aspect humain
est courir à l'échec. Je préfère l'idée de contrats sociaux émergeant du
libre choix d'un ensemble de citoyens à la ville platonicienne peuplée
de clones où toute individualité est noyée et soumise à une autorité
illimitée.

Pour éviter que ce libre choix ne mène à des errements, l'idéal serait
de lancer chacun sur la voie de la sagesse, et c'est probablement là la
tâche la plus délicate de tout progrès social.

En ce qui concerne la globalité d'une vision politique, je crois que la
plupart des avis convergeront pour dire qu'elle devient nécessaire à
partir du moment où l'économie l'est également. Sans cela, aucune
régulation n'est possible, les monopoles sont incontrôlables et les
délocalisations sortent de leur tanière.

Tu cites les coopératives, l'idée est excellente, et il est tout à fait
possible de les rendre viable via une fiscalité avantageuse, voire même
de les accoupler avec une société commerciale classique.

Le vin avait l'air effectivement excellent

Au plaisir !

** Réponse à la réponse de Waiméa Bay **

Un monde sans frontière, j'en ai rêvé longtemps, avant de me rendre
compte qu'on ne peut les supprimer. Regarde n'importe quelle communauté,
l'humain recrée naturellement les mêmes conditions : des clans se
forment inévitablement autour d'autant de sujets, prétextes à favoriser
ses petits copains. Or, qui dit clan, dit frontière sournoise. Quant à
l'argent, il n'est qu'une facade pour les diverses convoitises de tout
un chacun, une facade souvent moins sale que le contenu de la vitrine.
Le supprimer n'empêchera pas le tout un chacun d'envier ce qui est
enviable : la piscine du voisin, le pouvoir de son sous-fifre de chef,
la gaieté de son collègue, la femme d'Hector ou le mari d'Andromaque.
J'en passe.

* Un peu d'essence et de principe

/La polis tique, tome 2/

Dans l'article précédent, j'énonçais la question qui devrait être à la
source de toute démarche politique honnête, à savoir en substance :

« Comment peut-on organiser le fonctionnement d'une communauté afin
d'assurer au mieux le bien-être de tous et de chacun en particulier ? »

La précision est vitale, dans la mesure où il est accordé autant
d'importance à l'individualité qu'à la collectivité. Toute politique qui
négligerait l'un ou l'autre de ces deux aspects courrait au chaos ou à
la tyrannie, autrement dit à l'échec.

Sur cette dualité individu - communauté viennent se greffer quelques
principes essentiels. Avant toute chose, rien ne peut fonctionner
correctement sans la présence de règles claires, simples, identiques
pour tous et laissant à chacun le plus de liberté possible. Mais ce qui
fait vivre un groupe ce sont les intéractions entre les personnes qui le
constitue. Parmi elles, je retiendrai les valeurs qui me paraissent les
plus importantes : le partage et l'échange. Afin d'éviter ou au moins
d'atténuer les travers dans lesquels se sont enlisées trop de
civilisations, il me paraît également nécessaire de généraliser un
principe démocratique bien connu en interdisant l'accumulation de trop
de pouvoir en trop peu de mains, et ce quelle que soit la nature du
pouvoir en question : politique, économique, financier ou autre.

Pour mieux comprendre la nécessité de ces principes, choisissons
quelques modèles de société où ils n'apparaissent pas. Nous ne nous
attarderons pas sur la concentration du pouvoir, concentration qui
conduit par définition à un régime oligarchique ou autoritaire ; si
démocratie il y a, elle ne sera que de façade.

Ensuite, supposons si cela est possible une société où le partage est
interdit. C'est le règne du chacun pour soi, tout le monde il veut
garder ses petits secrets et le savoir ne se propage que très lentement.
En clair, c'est la ruine à plus ou moins long terme. Comme si cela ne
suffisait pas, toute action commune, et donc toute contestation, tout
débat est interdit. La communauté elle-même se voit niée, ce qui ne peut
déboucher que sur le chaos, cette mixture instable d'où émergent les
habituels potentats de village, de région, de province, autrement dit un
féodalisme qui comme chacun sait ne brille ni par son équité, ni par ses
capacités de progrès social.

Considérons à présent un système où l'échange est hors-la-loi. Dans le
meilleur des cas, on se retrouve avec une société égalitaire jusqu'à
l'excès où les ressources sont allouées uniformément. Il n'est pas tenu
compte des préférences de chacun, et la population fait face à un choix
cornélien : abandonner toute diversité et accepter le mal-être qui en
découle, ou développer un marché noir, fragmenté, à la merci de
monopoles, d'escrocs et de magouilleurs de tous poils. Abstraction faite
de l'aspect légal, ces marchés décentralisés, opaques, facilement
manipulables de par leur illiquidité et l'absence de régulation, ces
marchés instables et iniques sont l'une des causes de la crise
financière actuelle.

Cette situation lamentable est à l'opposé d'un marché optimal respectant
les principes de transparence et évitant toute concentration excessive
du pouvoir commercial. Le premier critère implique une centralisation et
une mise à disposition du public des informations, le second nécessite
une fragmentation fine de l'offre et de la demande.

Une bonne partie des inégalités actuelles provient d'un manque à ces
principes : les états possédant des lois anti-monopoles ne les
appliquent pas, ou pas suffisamment, à plus petite échelle les deux
boulangers du coin s'entendent trop cordialement pour se faire
concurrence, la chaîne de distribution est trop puissante par rapport au
petit fermier qu'on pousse vers la culture industrielle, etc. Au niveau
des sociétés, la main-mise des actionnaires n'est pas contrebalancée par
un pouvoir réel du personnel, les mandats croisés dans les conseils
d'administration sont aussi communs qu'en politique et pourtant personne
ne semble s'indigner des collusions d'intérêt que cela génère. Sans
compter la misère, car rien ou presque n'est fait pour aider les gens
qui dorment dans des cartons ... Si la liste est longue, les causes se
ressemblent.

Et pourtant, il existe des solutions à ces problèmes : interdire tout
cumul de mandat, qu'il soit politique, économique ou autre, développer
comme modèle commercial des sociétés contrôlées à la fois par le
personnel et les actionnaires, à mi-chemin entre la coopérative et la
société anonyme, améliorer l'ISF et éliminer les défauts qui lui sont
reprochés, etc.

Rien de tout cela ne nécessite de grands cris révolutionnaires, juste
des réformes et la détermination de la population à les faires
appliquer. Malheureusement, il semble plus facile de hurler contre des
ennemis confus comme l'économie ou le système, éternels boucs émissaires
d'une colère aveugle. Pourtant, personne n'a jamais vu cette vieille
dame ou ce mystérieux monsieur mettre la main dans nos poches ou
comploter dans les couloirs. Comme tout autre outil, ce sont des bras
humains qui les actionnent, des bras semblables aux vôtres. Ce qui nous
amène à une autre question pertinente : pourquoi les peuples
connaissent-ils si mal les rouages de l'état, pourquoi des matières
aussi importantes que le droit ou l'économie ne figurent pas ou si peu
dans les programmes scolaires ? Voilà une question qui montre du doigt
les déficiences de l'éducation et la menace que ces lacunes représentent
pour la démocratie.

** Réponse à Hernani **

Ta cave est toujours aussi excellente Hernani ! Il est intéressant de
comparer les rôles de la campagne et de la ville dans la grèce antique
et à la fin du 18e siècle. En ce qui concerne la fragmentation du
pouvoir, j'ai pensé à ajouter les média à ma liste : ils tombent dans le
champ d'application des sociétés commerciales, mais c'est un cas
particulier important de concentration excessive. Les grands groupes se
sont encore renforcé ces dernières années, à ce train là tous les
journeaux vont finir par se ressembler si ce n'est déjà fait. On peut
également tenter de voir un autre parallélisme dans les associations
incestueuses église - monarchie // multinationales - politique. Que de
choses à dire ... trinquons aux âges d'or à venir !

** Réponse à Justine **

Justine, je n'ai pas encore évoqué la notion de monnaie, mais dans tout
système d'échange une référence à tendance à s'imposer, et il y a une
raison mathématique à cela : il est plus simple de comparer N
possibilités par rapport à un standard que de comparer chaque
possibilité par rapport aux N autres, ce qui nous donne un ordre de
grandeur de N^{2} comparaisons.

N = 1000, ce qui n'est pas beaucoup, nous donnerait 1 million pour
N^{2}, je te laisse imaginer le bidule.

J'ai pris le parti dans ces articles d'adapter une approche à la fois
créative et pragmatique, innover tout en tenant compte des réussites et
erreurs du passé, mais je n'ai rien contre le /free your mind/ pur et
dur, tu as bien fait de le replacer au devant de la scène. N'hésite pas
si tu as des suggestions.

** Réponse à Jean **

Jean, un cercle ou une spirale ? Les siècles se ressemblent et sont si
différents ... Je pense réellement qu'il y a comme un tournant dans
l'air, espérons qu'il sera positif. Avec le temps, tout se détourne en
effet, même dans le meilleur des mondes il y aura toujours des gens qui
n'auront rien de mieux à faire. Un système qui n'est pas capable de se
renouveler s'érodera lentement mais sûrement.

** Réponse à Hernani **

Hernani, mais qui parle d'autogouvernement parle déjà d'une autorité de
groupe, la frontière est plus diffuse qu'on pourrait le penser à
première vue.

Le pouvoir devrait ne révéler que de l'organisation et d'un devoir
envers la collectivité, mais les symboles qui l'entourent faussent le
jeu. Tout comme argent, il prend des proportions démesurées dans
l'inconscient collectif. Il ne faut pas se leurrer, la société est d'un
naturel moutonnier qui n'attend que la première autorité crédible pour
la suivre. L'aura des hautes sphères et tout ce qu'elle confère ne fait
qu'attirer dans sa lumière des papillons qui s'y laissent prendre pour
de mauvaises raisons. D'où l'image ambiguë que ce milieu véhicule.

Pour les cataclysmes, les gouvernements ne peuvent évidemment pas grand
chose, mais ils pourraient beaucoup avec plus de créativité, comme tu le
soulignes avec Coluche (que n'a-t-il été élu président ...). Ils
pourraient plus encore si il existait une réelle coordination mondiale.
Mais une telle puissance serait à double tranchant, d'autant que les
peuples n'auraient pas un contrôle direct sur ces instances. Une «
démocratie » indirecte, on a vu ce que cela peut donner au niveau de
l'Union Européenne : des coulisses pratiques pour jouer sur plusieurs
tableaux.

* Des solutions, il y en a

Notre monde va mal, très mal. C'est être une autruche que de ne pas s'en
rendre compte. Vous voulez de vraies solutions ? En voila, chacune
correspondant à son propre problème. Quelques solutions parmi d'autres,
qui sont un début de réponse pourvu qu'elles soient pensées de manière
/globale/.

L'accroissement galopant de la population face aux ressources limitées
de notre planète. La solution est simple : un enfant par couple pendant
deux ou trois générations, et nous revenons au nombre plus raisonnable
de 1 milliard d'habitant. C'est un sacrifice (bien qu'à mon sens ce soit
un grand mot) nécessaire : il suffit d'analyser le comportement des
foules pour réaliser que la surpopulation entraîne l'aggressivité, puis
la violence, puis le masssacre. La vraie question est : préférez-vous un
enfant qui vivra bien ou trois qui courront au massacre ?

Ne signer des accords qu'économiques qu'avec les /vraies/ démocraties,
afin de faire pression sur les dictatures. L'OMC bafoue actuellement ce
principe, il suffit de voir que des dictatures en font partie, ce qui
subventionne l'exploitation des travailleurs locaux, pour ne pas dire
l'esclavagisme.

La réduction généralisée du temps de travail à 10 ou 20 heures. La
barrière des mentalités se dresse ici, encore une fois : il faut arriver
à considérer le travail, non plus comme une vertu comme c'est le cas
actuellement, mais comme ce qu'il est en réalité, c'est-à-dire une
corvée. Nous avons actuellement les moyens technologiques de nous
libérer de ces contraintes, seuls des principes arriérés nous en
empêchent.

La répartition des ressources. Point Ô combien sensible. Le système
économique actuel à ses qualités bien entendu, mais il est très
instable. Une régulation qui consisterait à pomper parmi les plus
grandes fortunes pour réinjecter parmi les plus pauvres suffirait à le
stabiliser. Il suffit d'introduire un paramètre de rapport de richesse
et la machine tournera toute seule.

Nous vivons dans un domino géant ou tout peut basculer, parfois dans des
directions imprévisibles. Même une bonne intention peut parfois
provoquer des catastrophes. Le système actuel est améliorable, mais si
on veut le modifier, il me semble essentiel de proposer des solutions
cohérentes au niveau mondial, et ne pas se contenter de réfléchir
localement (tant au niveau géographique que logique).

Vous vivez dans une démocratie. Nos ancêtres n'étaient certes pas tous
des saints (qui l'est ?) mais ils nous ont laissé cet inestimable
cadeau. Elle est malade, certes, mais il ne tient qu'à son peuple de la
revitaliser en sortant du schéma de pensée droite-gauche qui ne permets
à aucune idée nouvelle de se développer.

Vivre dans une démocratie vous donne non seulement le droit de voter (ne
ricanez pas, cela a beaucoup plus de poids que vous ne le pensez), mais
aussi de vous réunir autour d'idées semblables et de désigner vous-mêmes
vos propres candidats. Des gens que vous connaissez et dont vous savez
la valeur. Plus des barons qui donnent des consignes. Les barrières que
vous rencontrerez ne seront pas, comme vous le pensez, le manque de
moyen financier ou le mépris de la classe politique actuelle. Non, ce
sera l'intégrité de vos candidats. Quoi que vous en pensiez, la plupart
d'entre-eux ne résisteront pas à l'appel de la corruption. Ce sera aussi
l'appétit du pouvoir, l'ambition irrésistible de se retrouver au
gouvernement où vous ne seriez dans un premier temps que de la
décoration. Le vrai pouvoir est l'influence de l'ombre, pas celle des
projecteurs. Ce sera encore la volonté d'arriver au niveau national,
alors que la priorité est d'amener un maximum de pays influents à
adhérer à vos idées. Mais surtout, le principal obstacle qui se
présentera à vous, c'est qu'il est plus facile de réunir des millions de
personnes pour répandre leur haine que pour répandre leurs idées et leur
volonté de construire l'avenir.

* Les philosophies Unix et du logiciel libre sont l’avenir de la politique



* Free Software and Unix philosophies are the future of politics



