
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Cendres
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Que reste-t-il

#+BEGIN_CENTER
#+BEGIN_VERSE
Que reste-t-il après l’amour
Après l’ivresse et le dégoût
Que reste-t-il au petit jour
Que ces émois mis bout à bout ?

Que reste-t-il après l’orage
Et les averses de tristesse
D’un intarissable nuage
Après ce froid qui vous transperce ?

Quelques reflets sans importance
Sur un étang à demi-nu
Et cette impression insistante
D’avoir effleuré l’absolu

Cette fatigue où l’on renonce
À en comprendre un minimum
Les pieds prisonniers dans les ronces
Entre les frelons qui bourdonnent

Ceux qui plus loin que l’infini
Osèrent se contempler l’âme
Purent-ils voir le paradis
Ou le miroir d’un autre drame ?
#+END_VERSE
#+END_CENTER


* Mines de ciel

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai dû confondre avec la vie
    L’avidité de l’insouciance
    L’essence lourde des vanilles
    Avec la joie d’une mésange

    J’ai dû confondre avec le vent
    Avec l'écho des anciens rêves
    Le souffle avili des tourments
    Qui se débattent dans leur fièvre

    J’ai dû confondre avec un coeur
    L'étourderie d’un rideau rouge
    Confiant aux alizés moqueurs
    Les frêles frissons qu’elle couve

    J’ai dû confondre avec l’amour
    L’amertume ivre de naguère
    Lestée de passion et de poudre
    Prélude incessant à la guerre

    J’ai dû confondre avec le ciel
    Le sel sans lune des cristaux
    La lueur verte de la pierre
    Avec l’aurore bleue de l’eau

    J’ai dû confondre la fraîcheur
    Avec la chanson de la menthe
    Avec le grain fluide d’un choeur
    Les voix qui fusent discordantes

    J’ai dû confondre la lumière
    Avec un reflet ou un charme
    Avec le chant d’une rivière
    Le sable aride de vos larmes
#+END_VERSE
#+END_CENTER

* Au-delà

#+BEGIN_CENTER
#+BEGIN_VERSE
    Au-delà des sanglots, des larmes et des pleurs,
    Quand le coeur désséché a dépassé l’horreur
    Des rats d’eau qui s’enfuient des radeaux qui chavirent,
    Alors la consistance, écran superficiel,
    Se dissout dans l'éther ainsi qu’un simple sel
    Cristallisé au bord d’une mer de soupirs.

    Et la marée furieuse emporte sous son aile
    Houleuse tout ce qui nous semblait substanciel
    La veille. Nos projets ne sont que des épaves.
    Echoués sur le seuil brumeux de l’avenir,
    Elles ont beau scruter les nimbes et maudire,
    L’insondable néant leur a cloué l'étrave.

    Une nuit oppressante établit son empire,
    Gyroscope affolé au comble du délire,
    Compas déboussolé sans étoile ni ciel.
    Mais l’idée du néant se détruit elle-même
    Et dans l’obscurité un bouillonnement blême
    Ecrit les pulsations du rythme originel.
#+END_VERSE
#+END_CENTER

* Rêverie

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je ne saurai jamais
    Dis moi
    Quel est donc ce destin
    Qui nous tient dans ses bras
    Ou plutôt ne dis rien

    Je ne sais plus
    Dis moi
    Pourquoi es-tu venue
    Que me cachais-tu toi
    Sous ta peau pourtant nue

    Je ne me souviens plus
    Dis moi
    Quel est le nom du vent
    Où vont les pleurs aigus
    Et les noir océans

    J’ai oublié
    Déjà
    Le soupir de l’effroi
    Le souffle de l'été
    Et le son de ta voix

    Je ne saurai jamais
    Crois moi
    Le lieu des souvenirs
    Ces soufflets sur le dais
    Fatigué du désir

    Je me noie de néant
    Tu vois
    D’ailleurs rien n’est écrit
    Ma vie n’est que le vent
    De la ligne qui suit
#+END_VERSE
#+END_CENTER

* Renaissance

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je serai seul ce soir aux bras d’une inconnue
    Ecrasant sur son sein nos détresses communes
    Peut-être même que nos âmes dévêtues
    Arrêterons la course éperdue de la lune

    Je serai fou ce soir insouciant papillon
    Voltigeant au hasard comme un rêve égaré
    Echoué loin des champs dans la boue d’un sillon
    Mon vol pour refleurir les jupons délavés

    Je serai soûl ce soir coulé par vos yeux froids
    Torpillé par tribord et mon coeur n’a plus d’armes
    Remplissez à raz-bord téquila-gin-vodka
    Je boirai l’océan pour y noyer mes larmes

    Je serai mort ce soir car il me faut renaître
    Détruire l’illusion dans un cri silencieux
    Chrysalide intérieure ouvrez donc la fenêtre
    Je pars pour le soleil des sourires radieux
#+END_VERSE
#+END_CENTER

* Femme-aile

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les jeux sont faits cheveux défaits
    C’est passe impair elle te manque
    Que tu joues rouge ou noir de jais
    Tu rameras contre la banque

    Chaque espérance est un jeton
    Au bac à rat ou au poker
    Ne compte plus les médaillons
    Ou tu auras l’air d’un cocker

    Les tapis verts sont en fumée
    Quatre-cent-vingt-et-un cocktails
    Cinquante-deux cartes truquées
    Sur le snooker de la femme-aile

    Et puisqu’au bridge il faut contrer
    Sur une enchère à faible cote
    Laissons les ponts sur l’eau couler
    Et les atouts régler la note

    Il est de mise au casino
    Que les honneurs grimpent sans cesse
    Chaque pari pour un tarot
    L’enjeu avouer ses faiblesses

    Fuis devant la roulette russe
    Elle a rempli tout le chargeur
    A bout pourtant elle te couche
    Tout le barillet dans le coeur

    Chante plutôt le blues billard
    Le syncopé de l’anicroche
    Et si la bille à temps ricoche
    Tu gagneras au moins la part
#+END_VERSE
#+END_CENTER

* A fleur d'eau

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’eau qui coulait à la fleur de tes yeux
    M’a murmuré : Aurais-tu deviné ?
    C’est comme si elle avait tatoué
    En lettres d’or ton nom dans ses cheveux

    Mais c’est une encre invisible et timide
    Seuls elle et toi pouvez les déceler
    Ecume bleue sur la vague bleutée
    Un océan de cire translucide

    Et nul ne sait où commence où s’arrête
    Le fin contour de vos peaux qui se pâment
    Vos chairs fondues à ne former qu’une âme
    Ne sont qu’une ombre et qu’une silhouette

    Et vous flottez ainsi que dans un rêve
    En vous palpant de mots inavouables
    La terre est loin et vous lâchez le câble
    Pour mieux voler dans la brume des fièvres

    Vous explorez les plus sombres couloirs
    De vos envies qui couvaient sous la cendre
    La poussière aime à partout se répandre
    Dès qu’on oublie la folie au placard

    Chaude et salée je perle et m’insinue
    Je suis la crue affleurement lubrique
    Je suis rosée lorsque vos corps s’imbriquent
    Je suis la larme à boire dans les nues
#+END_VERSE
#+END_CENTER

* Armurerie

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les insouciants font des dégâts
    Losqu’on les lâche aux yeux des femmes
    Chaque pleur ajoute à leur poids
    Mais quand leurs rêves les enflamment

    Les insouciants font des dégâts
    Et pleuvent les ruisseaux de larmes
    C’est qu’ils ne réalisent pas
    Que le vol du vent est une arme

    C’est qu’ils viennent d’un autre monde
    Où l’amour déborde et inonde
    Les murs couverts de hallebardes

    Même si quand leurs coeurs sont lourds
    Leurs airs moqueurs de corps de garde
    Les font passer pour des balourds
#+END_VERSE
#+END_CENTER

* Compresseur

#+BEGIN_CENTER
#+BEGIN_VERSE
    Lorsque ton jeune loup sera un vieux filou
    Qui s’en ira chasser les bergères des plaines
    Même plus pour leur chair mais juste pour la laine
    M’aimerez-vous encore ?

    Lorsque l’audace aura épuisé les tabous
    Et que mon vers exsangue engloutira la mer
    Tellement dilué par autant de misère
    M’aimerez-vous encore ?

    Lorsqu’il aura neigé sur le toit des années
    Que le sommier croulant sera un caducée
    Lorsque je serai las de tout hors la lumière
    M’aimerez-vous encore ?

    Quand nous étoufferons sous les médicaments
    Entre anti-dépresseur et gorgées de calmants
    Quand le couchant sera arc-en-ciel de prières
    M’aimerez-vous encore ?
#+END_VERSE
#+END_CENTER

* Ma lavandière

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle était blonde, elle était belle
    Elle avait le feu aux prunelles
    Ma lavandière
    Dans l’océan des ses yeux bleus
    Nageait un scorpion venimeux
    Au coeur de pierre

    On s'était juré en silence
    Tout ce que permet l’inconscience
    Des jeux extrêmes
    Mais il n’y a qu’une lettrine
    Une mince lettre coquine
    Entre aime et haine

    A nous l’amour alphabétique
    Un M sans N un peu gothique
    Un jour sans ombre
    Mais tous les toujours se fissurent
    C’est un faux plafond de murmures
    Dans la pénombre

    Elle était ronde elle était belle
    Prenait l’ascenceur vers le ciel
    Ma lavandière
    Le doigt sur le septième étage
    Quand elle gardait dans sa cage
    Les pieds sur terre

    C'était un ballet bien réglé
    Le métronome ciselé
    Frôlait les sens
    Je n’ai rien contre la limoge
    Mais qu’ai-je à faire d’une horloge
    Dans une danse

    Sa peau embaumait la canelle
    Quant elle s’offrait sensuelle
    Gambette en l’air
    Je ne fais étant indulgent
    Aucun commentaire indécent
    Sur son derrière
#+END_VERSE
#+END_CENTER

* Les souvenirs

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tu voudrais oublier
    Tu voudrais incendier
    Ces souvenirs qui t’enchaînent
    Mais toujours ils renaissent
    Ils te hantent sans cesse
    Ces aiguillons de tes peines

    Les vieux airs ces canailles
    Transpercent ton poitrail
    Des rayons lourds du passé
    Quand ce n’est un vieux cadre
    Qui d’un vieux candélabre
    Surgit et te rit au nez

    Et toujours tu oublies
    L’une ou l’autre harpie
    Qui se dédouble inlassable
    Tu as beau leur hurler
    Laissez-moi donc en paix
    Ils te harcèlent de fables

    Les alcools somnifères
    Les fumées délétères
    Les débauches de parfums
    Jusqu’au jeune et au thé
    Tu as tout essayé
    Sans jamais en voir la fin

    Mais un jour tu sauras
    Te reconstruire un toi
    Et détruire ce fardeau
    Mais un jour tu verras
    Tu te réveilleras
    Tu seras libre à nouveau
#+END_VERSE
#+END_CENTER

* Verres brisés

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le brasier s’est éteint.
    Seul et dernier témoin,

    La cendre qui s’attarde
    Dans le creux de ma main.

    La raison se lézarde
    Dans cette fumée pâle :

    Un charbon fin et gris
    S’incruste en son cristal.

    Fuir est mon seul soucis !
    Mais sans feu tout est fade,

    Le bois est vermoulu,
    Il n’est plus de parade.

    Sans le moindre fétu
    Pour rallumer la paille,

    Le coeur décroche en vrille
    Vers l'âme qui déraille.

    Puis vient l’hiver sans vie,
    Chute vertigineuse

    Dans l’espace glacier
    Des glissantes poudreuses.

    D’autres feux vitrifiés
    Rosissent ce désert,

    Fruits flétris sous la lame
    De l’espoir qui lacère.

    Et tous sommes ces flammes
    Qu’emprisonne un bijoux ;

    Pourpre figé, nos perles
    N’ont d'éclat que du flou.

    Seul ce gel qui déferle
    Brûle encore nos corps

    Mais c’est un brûlot mort
    Sans joie et sans essor
#+END_VERSE
#+END_CENTER

* Mal à deux

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans ce mal que l’on fait à deux
    Le désir brut est le plus net
    Et chaque instant est un adieu
    Pour se rassurer de ne l'être
    Il eut fallu plus de merveilles
    Pour s’oublier dans le sommeil
    Compter les fées sur les persiennes
    Mais ta douleur était la mienne

    Si je nous dois d’avoir vécu
    C’est d’avoir écouté le vent
    Il me dit "Va !" et je l’ai cru
    Ce qu’il en reste est dans ce chant
    Il eut fallu qu’on appareille
    Vers des murmures sans oreille
    Des vagues dont on se souvienne
    Mais ta douleur était la mienne

    On pourrait croire à l’habitude
    D’avoir le coeur écartelé
    Tu le sais ces foutus préludes
    On ne s’y habitue jamais
    Il eut fallu de la folie
    Du carburant pour la magie
    Il aurait fallu ma sirène
    Mais ta douleur était la mienne

    Je les laisse aux robots sans cil
    Les crocs sanglants les nerfs d’acier
    Les poings sans coeur qui sans trembler
    Ecrasent les fruits trop fragiles
    Il aurait fallu que je mente
    Te tendre un mouchoir à la menthe
    Il aurait fallu que je tienne
    Mais ta douleur était la mienne

    Haïr l’amour aimer la haine
    Haïr la haine aimer l’amour
    Sont nos seuls choix la verve est vaine
    Au fil de tout autre discours
    Il aurait fallu que sans cesse
    Nous en glissions dans nos caresses
    Et qu'à la fin je te retienne ...
    Mais ta douleur était la mienne
#+END_VERSE
#+END_CENTER

* Lance ample

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le fier voilier plane au-dessus
    De la bombe poudrée canon
    De la poudre aux yeux des tutus
    Mais même s’il plane au-dessus
    Des ramasseuses de couillons

    Même s’il échappe aux mirages
    Allumeuses de feux de paille
    Esclaves glacées des miroirs
    Même s’il échappe aux mirages
    Avant que la nuit ne défaille

    Le faucon devrait fuir les griffes
    Qui arment les frêles colombes
    Car c’est dans l’ombre des soutifs
    Que se couvent les oeufs lascifs
    Qui fait qu'à la fin il succombe

    La mort renaît dès qu’elle meurt
    Sa naissance est son agonie
    Interminable champ de fleurs
    Le poison renaît dès qu’il meurt
    En vain ton coeur se réfugie
#+END_VERSE
#+END_CENTER

* Amarres et hautes

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le revers des étiquettes
    Des affolées aux coquettes
    Egrène un compte à rebours
    Des bas lourds à la bobine
    Ce n’est qu’intrigue et combine
    Qui n’en connaît que l'échine
    N’a jamais connu l’amour

    Chacune couve ses tours
    D’une magie sans recours
    L’oeuf duveteux se dandine
    Dans les cages des basquines
    Chante l’encor troubadour
    Qui n’en connaît que l'échine
    N’a jamais connu l’amour

    Que la voix soit de satin
    Le ton ou sec ou mutin
    Aussi beau soit le discours
    Qu’il ait neigé qu’il ait plu
    Que cela t’ait ou non plu
    Qui dit je ne t’aime plus
    N’a jamais connu l’amour

    La fuite est le seul salut
    S’abriter dans les étoiles
    Cap au large à fond de toile
    Loin du chanvre des chaluts
    Et se rappeler toujours
    Qui dit je ne t’aime plus
    N’a jamais connu l’amour

    Il a vu tant de rivages
    Lessivés par un chignon
    Des creux hauts de dix étages
    Et d’une moue les ravages
    Sur un visage mignon
    Que nul ne leste de chaîne
    Le sextant du capitaine

    Qui a toute latitude
    De retrouver le bon angle
    C’est qu’on se perd aux triangles
    Des bermudas qui dénudent
    Et des jupons qui dessanglent
    La calanque est une aubaine
    Au sextant du capitaine

    Il sait si bien la tristesse
    Les garrots de rubans bleus
    Que la folie des sagesses
    Sert à cacher la tigresse
    Qui dort dans le flot moëlleux
    Que nul ne leste de chaînes
    Le sextant du capitaine

    Tant pis si l'île est cruelle
    Si le sable n’est pas tendre
    Le désir qui se veut tendre
    Ne manque jamais de sel
    Oui quel que soit le coriandre
    La calanque est une aubaine
    Au sextant du capitaine
#+END_VERSE
#+END_CENTER

* Ronde des ailes brisées

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tu seras sans nul doute en carence d’espoir,
    Tes ailes brisées sur l’autel des illusions.
    J’errerai sûrement, recherchant dans le noir
    De l’ombre pour soigner mes futures passions.

    Puis viendra cet éclair aux cents coups de canon
    La pluie nous sera douce ainsi qu’une éclaircie.
    La tristesse, vaincue, baissera pavillon
    Effrayée par la lueur de notre folie.

    Ensemble nous boirons ces philtres d’ambroisie
    Qui tiennent pour un temps à l'écart la querelle.
    Pour un temps nous irons nu-pieds dans les orties
    Sans en sentir encor la blessure cruelle.

    Nous penserons atteindre un bonheur éternel
    Lorsque la douleur surgira de son néant.
    Notre amour dégrisée se sentira mortelle
    Et nous fuira, nous laissant seul avec le vent.

    Puis viendra l’heur sans fin des puissants ouragans
    Qui porteront des coups fatals à la voilure.
    La coque vermoulue cèdera sous les dents
    Des flots grossis de larmes, vaincue par l’usure.

    Je serai surnageant sur un radeau peu sur.
    Dans l’eau un visage imbibera ma mémoire.
    Puis j’ouvrirai les yeux, nouvelle chevelure
    Et la joie brisera tous nos anciens miroirs.

    Tu sera sans nul doute en carence d’espoir,
    Tes ailes brisées sur l’autel des illusions.
    J’errerai sûrement, recherchant dans le noir
    De l’ombre pour soigner mes futures passions.
#+END_VERSE
#+END_CENTER

* Les amours impossibles

#+BEGIN_CENTER
#+BEGIN_VERSE
    Parfois je rêve encor d’un monde parallèle
    Dans lequel mon doublon a fait cet Autre choix.
    Dans ce monde si proche, si lointain a la fois
    Je les sais qui s’enlacent au creux de notre hôtel
    S’aimant de tous leurs sens, ces autres toi et moi.

    Même sachant déjà que la fin serait triste
    Je devais essayer, il fallait tout tenter.
    J’aime mieux la faim des opus inachevés
    Au désert glacé d’un clavier sans pianiste,
    Car la fin est d'écrire et non de terminer !

    Ecrire pour écrire, et ne pas consumer
    Nos brèves vies dans des rèves d'éternité.

    Tes poisons, semble-t-il, sont plus lents que les miens.
    Plus efficaces aussi, ils rongent mes entrailles,
    Seule subsiste en moi l’absence qui tiraille.
    Tes poisons, semble-t-il, détournent des festins.

    Bien sur je guérirai, la folie m’aidera.
    Je me noierai sans peur dans ses yeux envoûtants,
    Ses doigts seront pour moi autant d'épais onguents.
    Bien sur je guérirai, tout recommencera.

    En attendant mon sang coule sur les épines
    D’un rosier rouge vif entouré de résine
    Dont les roses rétives, belles inaccessibles,
    Décorent le caveau des amours impossibles.

    Parfois je rêve encor, leurs esprits me harcèlent,
    Traversant le tunnel, leurs ondes m’ensorcèlent ...
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
