
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Cimes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Diapason

#+BEGIN_CENTER
#+BEGIN_VERSE
    L'âme est un violon qui chante sa complainte
    A travers l’air glacé des matinées d’hiver
    Le son est pur et doux nostalgique est la plainte
    Qu’il tire des flocons et des cristaux solaires

    La brume a déroulé ses rubans de coton
    Les vagues des glaciers submergent les glacières
    Et bientôt guidée par l'étrange partition
    La rigueur hivernale ouvre le frigidaire

    Les cordes chatouillées par les crins de l’archet
    Qui riaient autrefois en éclats de lumière
    Ne goûtent plus le vin qui cuve dans leur chais :
    A rondeau esseulé sonate solitaire

    Les larmes du passé sculptent des stalactites
    En regardant passer la buée éphémère
    La buée du présent s'évapore trop vite ...
    Le pas lent des coeurs lourds crisse sur les congères

    Le menu est menu le menuet muet
    Pauvre valse égarée loin de ses congénères
    La forêt du silence est un dédale épais
    Où règne sans partage un chêne solitaire

    C’est un chêne enchaîné qui murmure et qui songe
    Qui conte au vent frileux la folie des bruyères
    Que l’arbuste est un pin quand l’ombre le prolonge
    Et que parfois la nuit l’illusion exagère

    L’esprit est un titan rougeoyant sous le givre
    Qui bout dans son carcan de gel et de matière
    Déjà la neige fraîche est percée de fleurs ivres
    Et les fruits de l’automne ont germé sous la terre

    L’absurde d’un printemps dans un monde qui meurt
    Et pourtant cet espoir et pourtant ce ciel clair
    Comme un diapason dont le timbre demeure
    Comme une vibration qui remplit tout l'éther
#+END_VERSE
#+END_CENTER

* Dernière neige (haiku)

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’air en mouvement
    Siffle des rails de lumière
    Aux nues d’un étang
#+END_VERSE
#+END_CENTER

* Blizzard

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le vent soufflait de l’est en pur-sang hors d’haleine
    Et son souffle glacé moissonnait la poudreuse.
    Le vent d’est effaçait sous la neige incertaine
    Les traces balayées des plaintes silencieuses.

    L’alézan enroulant sa robe immaculée
    Embrumait la vallée de sa vague houleuse
    Et soudain succomba l’avalanche effrénée,
    Fauchée par le ressac des plages poussiéreuses.

    Apparut au milieu des plaines désolées,
    Majesté émergée du coton cristallin,
    Un arbre rayonnant de branches enneigées,
    Tel un flocon immense aux reflets argentins

    Qui fissurait le ciel trop sinistre et trop lourd
    D’un éclair persistant déversé par le jour.
#+END_VERSE
#+END_CENTER

* Dés ordonnés

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est l’impression d’un crépuscule
    Quand l’air respire de travers
    Comme un soleil qui vous accule
    L’ombre gourmande de lumière
    Est-ce midi est-ce minuit ?
    Il n’y a plus ni jour ni nuit
    Ni d’aiguille au cadran solaire

    Parmi les cartes à jouer
    Choisis ton heure sans tricher
    Au hasard celle que tu veux
    Autour de l'équateur polaire
    Tu peux même en retourner deux
    Ou toutes : ce sont des jokers
    Affolant les phases lunaires

    C’est un concert de voix sans tain
    Superposant soir et matin
    Cinq as sur un coup de poker
    Vingt en réserve dans la manche
    Qu’on soit lundi qu’on soit dimanche
    Elle tombe la neige blanche
    Sur l’orbe du cadran solaire

    Le firmament n’a plus d’horaire
    Les lunes dansent en ellipse
    Leurs oeillades sont des éclipses
    Aborbant la moindre frontière
    Adieu reflets d’or et d’argent
    Et la pénombre des croissants
    Et le clair des phases lunaires

    Voulez-vous savoir le mystère ?
    Pourquoi cette grève du temps ?
    C’est que là-haut dans le désert
    Une étoile arrose un printemps
    Des larmes chaudes d’un volcan
    Ils ne sont pas fait que de pierre
    Les coeurs des astres solitaires
#+END_VERSE
#+END_CENTER

* Neige d'octobre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Première poudre de flocons
    Première neige de coton
    Dessine les contours du vent
    Comme autant de lutins charmants

    Tel un fantôme turbulent
    Qui prend corps de vivant coton
    Le passé m’appelle envoûtant
    Et m’aspire dans le siphon

    Et m’aspire dans le siphon
    Dans les tentacules du vent
    Même neige même flocons
    Autre décor et autre temps

    Une cour de récréation
    A chaque bordée des enfants
    Le pur cristal étincelant
    Se mue en boulets de canon

    Autre décor et autre temps
    Même neige mêmes flocons
    Tel un fantôme turbulent
    Qui prend corps de vivant coton

    Tel un défilé de saisons
    Les flammes des noëls d’antan
    Rougoient dans ce ballet troublant
    Couleur de lys et de passion

    Le lys qui s’offre à la passion
    En en flot de soupirs tremblants
    Puis le soleil pâle et profond
    Vaporise l’enchantement

    Première neige de coton
    Dessine les contours du vent
    Première poudre de flocons
    Comme autant de lutins charmants
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
