
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Citations
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

 

/Note : lorsqu'aucun auteur n'est cité, c'est qu'il est anonyme ou que
je n'ai pu en retrouver la source./

 

Voir un univers dans un grain de sable, et un paradis dans une fleur
sauvage. Tenir l'infini dans la paume de la main et l'éternité dans une
heure.

William Blake

--------------

Prenez un mot, prenez-en deux faites cuire comme des oeufs, prenez un
petit bout de sens puis un grand morceau d'innocence, faites chauffer à
petit feu au petit feu de la technique, versez la sauce énigmatique
saupoudrez de quelques étoiles, poivrez et puis mettez les voiles. Où
voulez-vous donc en venir ? A écrire vraiment ? A écrire ?

Raymond Queneau

* Philosophie

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il n'y a qu'une maxime absolue, c'est qu'il n'y a
    rien d’absolu.
#+END_VERSE
#+END_CENTER

Auguste Comte, Catéchisme positiviste

--------------

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’univers m’embarrasse, et je ne puis songer
    Que cette horloge existe et n’ait pas d’horloger.
#+END_VERSE
#+END_CENTER

Voltaire, Poésies

--------------

Celui qui se perd dans sa passion perd moins que celui qui perd sa
passion.

Saint Augustin

--------------

La folie est héréditaire. Vos enfants peuvent vous la transmettre.

--------------

L'homme raisonnable s'adapte au monde. L'homme déraisonnable essaye
d'adapter le monde à lui-même. Par conséquent tout progrès dépend de
l'homme qui n'est pas raisonnable.

Bernard Shaw

--------------

Tout le monde savait que c'était impossible. Il est venu un imbécile qui
ne le savait pas et qui l'a fait.

Marcel Pagnol

--------------

Ce n'est pas parce que les choses sont difficiles que nous n'osons pas,
c'est parce que nous n'osons pas que les choses sont difficiles

Sénèque

--------------

Rien ni personne n'a tout à fait tort : même une horloge arrêtée a
raison deux fois par jour.

John Steinbeck

--------------

Le pressentiment, c'est le souvenir du futur.

Pierre Dac

--------------

Mes plus belles larmes, je les ai toujours versées en ignorant pour qui
ou pour quoi.

Frédéric Dard

--------------

L'expérience est une lanterne accrochée au dos qui éclaire le chemin
déjà parcouru.

Confucius

--------------

La liberté est comme une flêche lancée en direction du ciel... les fous
et les poètes espèrent qu'elle l'atteindra, les politiciens attendent
qu'elle retombe, les sages en aiguisent une autre.

Proverbe chinois

--------------

La vérité, c'est qu'il n'y a pas de vérités, celle-ci compris

Proverbe Shadok

--------------

Avec un escalier prévu pour la montée, on réussit souvent à monter plus
bas qu'on ne serait descendu avec un escalier prévu pour la descente.

Proverbe Shadok

--------------

Il est beaucoup plus intéressant de regarder où l'on ne va pas pour la
bonne raison que, là où l'on va, il sera toujours temps d'y regarder
quand on y sera.

Proverbe Shadok

--------------

Il n'y a pas la preuve que la puce qui vit sur la souris craigne le
chat.

Henri Michaux

--------------

Celui qui lutte contre les monstres doit veiller à ne pas le devenir
lui-même. Et quand ton regard pénètre longtemps au fond d'un abîme, lui
aussi, pénètre en toi.

Friedrich Nietzsche

--------------

Nous n'héritons pas la terre de nos ancêtres, nous l'empruntons à nos
enfants.

Antoine de Saint-Exupéry

--------------

Rien ne m'est sûr que la chose incertaine.

François Villon

--------------

Qu'est-ce que l'inspiration ? C'est d'avoir une seule chose à dire que
l'on ne soit pas fatigué de dire.

Jean Paulhan

--------------

L'oisiveté est la mère de tous les vices, mais le vice est le père de
tous les arts.

Alfred Capus

--------------

Il faut regarder l'argent de haut, mais ne jamais le perdre de vue.

André Prévot

--------------

Les vérités sont des illusions dont on a oublié qu'elles le sont.

Friedrich Nietzsche

--------------

Jupiter rend fou ceux qu'il veut perdre.

Euripide

--------------

L'appétit vient en changeant.

Richard Anonyme

--------------

Le soleil ni la mort ne se peuvent regarder fixement.

François de la Rochefoucauld

--------------

Je ne suis point cet assemblage de membres que l'on appelle le corps
humain.

René Descartes

--------------

Qui n'a pas l'esprit de son âge, de son âge a tout le malheur.

Voltaire

--------------

Il n'est point de secret que le temps ne révèle.

Jean Racine

--------------

Mais n'est-ce pas sans avoir reçu de personne aucun enseignement, mais
plutôt en étant questionné, qu'il possédera des connaissances, ayant
repris, de son propre fond, la connaissance qu'il se donne lui-même ?

Platon, Ménon

--------------

Il vaut mieux pomper d'arrache pied même s'il ne se passe rien que de
risquer qu'il se passe quelque chose de pire en ne pompant pas

Proverbe Shadok

--------------

Ce n'est qu'en essayant continuellement, que l'on finit par réussir Ou,
en d'autres termes : plus ça rate, plus on a de chance que ça marche ...

Proverbe Shadok

--------------

La culture, c'est ce qui reste quand on a tout oublié.

Proverbe Shadok

--------------

Pour guérir quelque chose qui ne marche pas ou qui fait trop de bruit,
il faut et il suffit de taper dessus avec quelque chose qui marche mieux
ou qui fait plus de bruits.

Proverbe Shadok

--------------

#+BEGIN_CENTER
#+BEGIN_VERSE
    On  n’a que  deux  vies  et  la seconde  commence  lorsqu’on
    réalise qu’on en n’a qu’une
#+END_VERSE
#+END_CENTER

Indéterminé

* Humour

Le joueur d'échecs, comme le peintre ou le photographe, est brillant...
ou mat.

Vladimir Nabokov (1899-1977)

--------------

Les gens petits sont défavorisés parce qu'ils sont les derniers à savoir
quand il pleut.

--------------

Un crabe voulait aller à la mer, il n'y arriva jamais : on lui avait dit
que c'était tout droit

--------------

Il ne faut jamais dire : Fontaine, ... Dites: Patron, un Muscadet !

Philippe Geluck

--------------

Pourquoi ne met-on pas de paniers dans les piscines ? Parce que la
corbeille a pas pied.

--------------

Le café est un breuvage qui fait dormir, quand on n'en prend pas.

Alphonse Allais

* Cynisme

S'il fallait permettre aux autres tout ce que l'on se permet à soi-même,
l'existence serait intenable.

Eugène Labiche

--------------

De tous ceux qui n'ont rien à dire, les plus agréables sont ceux qui se
taisent.

P. Desprosges

--------------

Méfiez-vous du premier mouvement, il est toujours généreux.

Charles-Maurice de Talleyrand-Perigord

--------------

Vous prouver que j'ai raison serait admettre que je puisse avoir tort.

Beaumarchais

--------------

Il y a deux genre d'avocats : ceux qui connaissent bien la loi, et ceux
qui connaissent bien le juge.

Coluche

--------------

Le berger frappe les moutons de derrière alors que ce sont ceux de
devant qui n'avancent pas.

* Amertume

La vérité sort de la bouche du muet.

--------------

Les optimistes pensent que nous vivons dans le meilleur des mondes
possibles, les pessimistes en sont intimement persuadés.

Pierre Desproges

--------------

Il faut pleurer les hommes à leur naissance et non pas à leur mort.

Montesquieu

--------------

Métaphysique mon cul, quoi de plus concret que de crever, et de le
savoir, et de ne pas aimer ça ?

François Cavanna

--------------

Deux augures ne peuvent se regarder sans rire.

Cicéron

--------------

Le désert, c'est génial à traverser : on ne voit que les gens que vous
aimez et qui vous aiment vraiment.

Nicolas Sarkosy

* Politique

Je ne crois aux statistiques que lorsque je les ai moi-même falsifiées

Winston Churchill

--------------

Il n'est aucun problème assez urgent en politique qu'une absence de
décision ne puisse résoudre.

Il n'est pas de problème dont une absence de solution ne finisse par
venir à bout.

La politique n'est pas l'art de résoudre les problèmes, mais de faire
taire ceux qui les posent.

Les promesses n'engagent que ceux qui les écoutent.

Henri Queuille

--------------

Le meilleur moyen de renverser un gouvernement, c'est d'en faire partie.

Charles-Maurice de Talleyrand-Perigord

--------------

La parole nous a été donnée pour déguiser notre pensée.

Charles-Maurice de Talleyrand-Perigord

--------------

Quand les événements nous dépassent, feignons d'en être les
organisateurs.

Pierre Desproges

--------------

Pour qu'il y ait le moins de mécontents possible il faut toujours taper
sur les mêmes.

Devise Shadok

--------------

Le carré de l'hypoténuse parlementaire est égal à la somme de
l'imbécilité construite sur ses deux côtés extrêmes.

Pierre Dac

--------------

Moi, je ne suis pas marxiste

Karl Marx

--------------

Le capitalisme, c'est l'exploitation de l'homme par l'homme. Le
communisme, c'est le contraire.

Coluche

--------------

La devise du communisme, c'est : passe moi ta montre que je te donne
l'heure.

Coluche

--------------

La démocratie plus l'ignorance populaire, c'est le plus court chemin
vers le despotisme, via la démagogie.

Marquis de Condorcet

--------------

Louer les princes des vertus qu'ils n'ont pas, c'est leur dire
impunément des injures.

François de La Rochefoucauld

--------------

Les hommes ont été plus malheureux par leur ignorance que par l'abus de
la force, ont eu plus à souffrir des fourbes que des conquérants et ont
plus à craindre les préjugés et le charlatanisme que les entreprises de
la tyrannie.

Marquis de Condorcet

--------------

Un traître est un homme politique qui quitte son parti pour s'inscrire a
un autre. Par contre, un converti est un homme politique qui quitte son
parti pour s'inscrire au votre.

Georges Clémenceau

--------------

L'ennemi est bête, il croit que l'ennemi c'est nous, alors que c'est
lui.

Pierre Desproges

--------------

La violence est le dernier refuge de l'incompétence.

Issac Asimov

--------------

Les forêts précèdent les peuples, les déserts les suivent.

François René de Chateaubriand

* Religions

Judaïsme : n.m. Religion des juifs, fondée sur la croyance en un Dieu
unique, ce qui la distingue de la religion chrétienne, qui s'appuie sur
la foi en un seul Dieu, et plus encore de la religion musulmane,
résolument monothéiste.

Pierre Desproges

--------------

On ne peut pas juger quelqu'un à ces fréquentations ; ne perdons pas de
vue que Judas avait des amis irréprochables.

Tristan Bernard

--------------

Dieu est un taquin sadique : il crée les hommes faillibles et il les
punit s'ils pèchent.

Cavanna, François

--------------

Les religions sont le nec plus ultra de l'ignorance.

Marquis de Sade

* Bétise

Le propre du génie est de fournir des idées aux crétins une vingtaine
d'années plus tard.

Guillaume Apollinaire

--------------

Je n'ai jamais rencontré d'homme si ignorant qu'il n'eut quelque chose à
m'apprendre.

Galilée

--------------

Les miroirs feraient bien de réfléchir avant de renvoyer les images.

Jean Cocteau

--------------

C'est parce que la vitesse de la lumière est supérieure à celle du son
que tant de gens paraissent brillants avant d'avoir l'air con.

--------------

Le fait que le monde soit peuplé de crétins permet à chacun de nous de
ne pas se faire remarquer.

Sim

--------------

Si les imbéciles volaient, il ferait nuit.

Fréderic Dard

--------------

"Il n'y a que les imbéciles qui ne changent pas !" disent les imbéciles
quand ils changent.

Gilbert Cesbron

--------------

Il ne faut jamais prendre les gens pour des cons mais il ne faut pas
oublier qu'ils le sont.

Les inconnus

--------------

C'est la profonde ignorance qui inspire le ton dogmatique.

--------------

Avez-vous remarqué la fréquence avec laquelle les gens se réfugient
derrière "l'humour" quand on leur fait observer qu'ils ont dit une
connerie ?

Michel Audiard

--------------

Parler pour ne rien dire ou ne rien dire pour parler sont les deux
principes majeur de tout ceux qui ferait mieux de la fermer avant de
l'ouvrir.

Pierre Dac

--------------

Il existe depuis très longtemps une immense secte d'imbéciles qui
opposent sensualité et intelligence. C'est un cercle vicieux : ils se
privent de volupté pour exalter leurs capacités intellectuelles, ce qui
a pour résultat de les appauvrir. Ils deviennent de plus en plus
stupides, ce qui les conforte dans leur conviction d'être brillants --
car on n'a rien inventé de mieux que la bêtise pour se croire
intelligent.

Amélie Nothomb

--------------

L'amour-propre est un ballon gonflé par le vent dont il sort des
tempêtes quand on y fait une piqûre.

Voltaire

--------------

Si tout ceux qui croient avoir raison n'avaient pas tort, la vérité ne
serait pas loin.

Pierre Dac

--------------

Un groupe de loups, c'est une horde. Un groupe de vaches, c'est un
troupeau. Un groupe d'hommes, c'est souvent une bande de cons.

Philippe Geluck

--------------

L'intelligence a été inventée il y a très longtemps par un type
vachement malin. La connerie, c'est autre chose, c'est une création
collective.

Philippe Geluck

--------------

Passer pour un idiot aux yeux d'un imbécile est une volupté de fin
gourmet.

Georges Courteline

--------------

La connerie c'est la décontraction de l'intelligence. C'est pour cela
que quelquefois je m'autorise à être con.

Serge Gainsbourg

Il vaut mieux mobiliser son intelligence sur des conneries que mobiliser
sa connerie sur des choses intelligentes.

Proverbe Shadok

--------------

* Social

Quelques fois il vaut mieux lâcher ses bagages que manquer le train. Les
esprits bourgeois ne savent jamais quand.

Gilbert Cesbron (1913-1979), de petites choses.

--------------

Il y a trois savoirs : le savoir proprement dit, le savoir-faire, et
puis le savoir-vivre : les deux derniers dispensent bien souvent du
premier.

Charles-Maurice de Talleyrand-Perigord

--------------

Pour arriver, il faut mettre de l'eau dans son vin jusqu'à ce qu'il n'y
ait plus de vin.

Jules Renard

--------------

Un classique c'est ce que tout le monde veut avoir lu et que personne ne
veut lire.

Mark Twain

--------------

Cette rumeur est un secret : il faut dire a tout le monde de ne le
répéter à personne.

Indéterminé

--------------

* Demoiselles

Plus je connais les hommes, plus j'aime les femmes

Frédéric Dard

--------------

Si le plus grand plaisir des hommes, c'est de se payer le corps des
femmes, je comprends que le plus grand plaisir des femmes soit de se
payer la tête des hommes.

Sacha Guitry

--------------

Une femme est comme votre ombre, courrez après, elle vous fuit ;
fuyez-la, elle vous court après.

Alfred de Musset

--------------

Joli paradoxe : la femme est le chef d'oeuvre de Dieu, surtout quand
Elle a le diable au corps.

Alphonse Allais

--------------

Le meilleur moyen de faire tourner la tête a une femme, c'est de lui
dire qu'elle a un joli profil.

Sacha Guitry

--------------

Les femmes seraient charmantes si on pouvait tomber dans leur bras sans
tomber dans leurs mains.

Ambrose Bierce

--------------

Les femmes ont à leur disposition deux armes terribles, le fard et les
larmes. Heureusement pour les hommes, elles ne peuvent pas se servir des
deux en même temps.

Marilyn Monroe

--------------

Une auto-stoppeuse est une jeune femme généralement jolie et court vêtue
qui se trouve sur votre route quand vous êtes avec votre femme.

Woody Allen

--------------

Les femmes sont tellement menteuses, qu'on ne peut même pas croire le
contraire de ce qu'elles disent.

Georges Courteline

--------------

Les femmes ressemblent aux girouettes, elles se fixent quand elles se
rouillent.

Voltaire

--------------

Femme qui abandonne sa bouche accorde sans peine le surplus

Chrétien de Troyes

* Amour

L'amour n'est pas aveugle, il est atteint de presbytie. La preuve, c'est
qu'il ne commence à distinguer les défauts que lorsqu'il s'éloigne.

Miguel Zamacoïs (1866-1955)

--------------

L'humour est une tentative pour décaper les grands sentiments de leur
connerie.

Raymond Queneau

--------------

En amour, les femmes écrivent des choses qu'elles ne diraient pas, et le
hommes disent des choses qu'ils n'écriraient pas.

François René de Chateaubriand

--------------

Les femmes ont plus de honte de confesser une chose d'amour que de la
faire.

Marguerite De Navarre

--------------

Je n'ai pas souvent assisté à des course de spermatozoïdes, mais j'ai
donné beaucoup de départs.

Olivier de Kersauson

--------------

Avant de choisir le prénom d'un garçon, pensez toujours à la femme qui
aura a le murmurer plus tard.

Jules Barbey D'Aurevilly

--------------

Ce qui est grave dans un ménage, c'est quand l'un aime et l'autre pas.
Mais s'ils ne s'aiment ni l'un ni l'autre, ils peuvent être très
heureux.

Alfred Capus

--------------

L'amour est un égoïsme à deux.

Madame De Staël

--------------

S'aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble
dans la même direction.

Antoine de Saint-Exupéry

--------------

L'amour... Il y a ceux qui en parlent et il y a ceux qui le font. A
partir de quoi, il m'apparaît urgent de me taire.

Pierre Desproges

--------------

Pourquoi perdre son temps à vouloir contredire son épouse ? Il est
beaucoup plus simple d'attendre qu'elle ait changé d'avis.

Jean Anouilh

--------------

Le mariage est une cérémonie où un anneau est placé au doigt de
l'épouse, et un autre au nez de l'époux.

Herbert Spencer

--------------

L'absence diminue les médiocres passions, et augmente les grandes, comme
le vent éteint les bougies et allume le feu.

François de La Rochefoucauld

--------------

Ma femme et moi avons été heureux vingt-cinq ans ; et puis, nous nous
sommes rencontrés.

Sacha Guitry

--------------

La pire chose que vous puissiez faire à l'homme qui vous a pris votre
femme, c'est de la lui laisser.

Sacha Guitry

* Famille

La pire colère d'un père contre son fils est plus tendre que le tendre
amour d'un fils pour son père.

Henry de Montherlant

* Finance

Aujourd'hui les gens connaissent le prix de tout et la valeur de rien.

Oscar Wilde

--------------

Dans ce siècle, il ne s'agit pas tant d'inventer quelque chose d'utile
aux autres que de les persuader qu'ils ont besoin de ce qu'on a inventé.

Gilbert Cesbron

--------------

Si on écoutait ce qui se dit, les riches seraient les méchants et les
pauvres seraient les gentils. Alors pourquoi tout le monde veut devenir
méchant ?

Coluche

--------------

Un financier vend à terme la peau de l'ours, fait courir le bruit qu'il
ne l'a pas tué : le cours s'effondre -- il rachète en sous-main.

Gilbert Cesbron

--------------

Si vous devez un million à la banque et que vous ne l'avez pas, vous ne
dormez plus. Si vous devez 100 millions à la banque et que vous ne les
avez pas, c'est votre banquier qui ne dort plus.

--------------

Qui donne aux pauvres, prête à Dieu. Qui donne a l'état, prête à rire.

Tristan Bernard

--------------

Qui vole un oeuf ferait mieux de voler un boeuf.

Francis Blanche

--------------

Vous voulez faire fortune ? Achetez toutes les consciences au prix
qu'elles valent, et revendez-les au prix qu'elles s'estiment.

Tristan Bernard

--------------

On appelle voiture d'occasion une voiture dont toutes les pièces font du
bruit sauf le klaxon.

Pierre Dac

* Art

L'idée de rimer pour les yeux n'est pas moins plaisante que le serait
celle de peindre pour le nez.

Guessard

* Science

Si vous jugez un poisson d'après son aptitude à grimper aux arbres, il
va passer sa vie entière à se croire idiot.

Albert Einstein

--------------

Heureux l'étudiant qui comme la rivière peut suivre son cours sans
quitter son lit.

--------------

La souris est un animal qui, tué en quantité suffisante dans des
conditions soigneusement contrôlées, produit une thèse de doctorat.

--------------

On s'aperçoit qu'on est devenu un spécialiste quand les choses dont on
parle avec plaisir ennuient les autres.

Gilbert Cesbron

--------------

Le jeu est la forme la plus élevée de la recherche.

Albert Einstein

--------------

Si vous ne pouvez pas expliquer quelque chose a une enfant de six ans,
vous ne le comprenez probablement pas.

Albert Einstein

--------------

La musique est une mathématique sonore, la mathématique est une musique
silencieuse.

Edouard Herriot

--------------

En fin de compte, chercher et apprendre sont en leur entier, une
remémoration.

Platon

--------------

Le plus court chemin entre deux vérités dans le domaine réel passe par
le domaine complexe.

Jacques Hadamard

--------------

Toute technologie suffisamment avancée est indistingable de la magie.

Arthur C. Clarke

--------------

Le livre de la nature est écrit en langage mathématique et quiconque
prétend le lire doit d'abord apprendre ce langage.

Galileo Galilei

--------------

Dieu est un mathématicien de tout premier ordre, et il a utilisé des
mathématiques très élaborées pour construire l'Univers.

Paul Dirac

--------------

Les trous noirs sont les endroits ou Dieu divisa par zéro.

--------------

L'homme est libre, comme la terre est immobile. Tout est combiné pour
ces illusions.

Paul Valéry

* Travail

Quand on ne travaillera plus le lendemain des jours de repos, la fatigue
sera vaincue.

Pierre Dac

--------------

L'homme n'est pas fait pour travailler, la preuve c'est que cela le
fatigue.

Voltaire

* Informatique

The UNIX way of sex:
gunzip-strip-touch-finger-mount-fsck-more-yes-umount-sleep

--------------

Il y a deux produits majeurs qui sont sortis de Berkeley : Le LSD et
BSD. Nous ne pensons pas que ce soit une coïncidence.

 

[[../index.php][Accueil]]
