
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Couleurs
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

 

 

** Yggdrasil

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il leur aura fallu l'éternité d’un songe
    Apprivoiser du coeur de tendres lendemains
    Sous les neiges en fleurs des boutons d’eau de rose
    D’un nuage élogieux le joyau souverain

    Il leur aura fallu dans leurs yeux diaphanes
    Un zeste de ciel bleu pour se perdre en chemin
    Et si peu, presque rien, à peine un filigrane
    Juste assez d’allusions pour se tendre la main

    Un mot doux mais sans tain parsemé de mystères
    Allongé frissonnant dans la baie des secrets
    Un aveu cristallin vers la jeune lumière
    Glissé dans un feuillage arrosé de reflets

    Et quand l’astre argenté nous dévoile ses charmes
    À la source où ruisselle une ardente blessure
    Pourrait-on rêver mieux comme ultime refuge
    Pourrait-on rêver mieux qu’un feuillage de larmes ?

    Car la pluie crépitante embrase le silence
    Depuis que l’arbre-monde a semé l’oiseau-lyre
    Le phénix musicien le gardien des nuances
    Aux abords des confins du royaume invisible

    C’est la magie de l’onde exaltée par les druides
    Un vertige enchanteur se révèle à nos sens
    On discerne des fées les nuisettes liquides
    Dénudées par l’averse et les ombres qui dansent

    Troublées par le rideau de l'élixir céleste
    Les nymphes délurées exhibent leurs corps fluides
    L’ondine intimidée se déhanche en souplesse
    Le jeune papillon oublie la chrysalide

    Car la pluie crépitante est une ombre qui danse
    Une voile agitée par la force d’un rire
    Un murmure éternel d’où jaillit le silence
    Et qui vibre sans cesse et sans cesse se brise

    Il leur aura fallu l'éternité d’un songe
    Pour libérer la  nuit des sangles du matin
    Un automne de fleurs, un hiver d’eau de rose
    Sous les neiges en feu apaiser leur chagrin

    Il leur aura fallu dans leurs voix diaphanes
    La douceur enchantée des flûtes de satin
    Et si peu, presque rien, à peine un filigrane
    Le langage muet d’un passé sibyllin

    Et quand l’astre transi se réchauffe en décembre
    À la source où succombe une ardente blessure
    Pourrait-on rêver mieux comme ultime lecture
    Que le livre infini de tes lèvres qui tremblent ?
#+END_VERSE
#+END_CENTER

** Midinuit

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il est midi petit coeur qui saigne
    Tout près de toi la lune se baigne
    Tout près de toi petit coeur du monde
    Il est midi dans la moiteur blonde

    Rose des blés tu montes pégase
    Rose des blés nymphe des légendes
    Les bois dorés sous tes pas s’embrasent
    Les bois dorés les champs de lavande

    Le chaume dort le ciel est de braise
    Le chaume dort sous les citronniers
    Douce fraîcheur que serait l'été
    Douce fraîcheur sans la crème fraise ?

    Le sapin songe à ses clapotis
    Aux pourpoints blancs aux manches de neige
    Aux pourpoints blancs près des pilotis
    Le sapin songe au souffle des crèches

    A la java autour des péniches
    A l’eau voilée dont l’huile pleurniche
    A la java à l’onde recluse
    A l’eau voilée cloîtrée dans l'écluse

    Au feu luisant où cuit l’artichaut
    Et au flocon venu du beffroi
    Au feu luisant brûlant sous la soie
    Et au flocon qui fond sur ta peau
#+END_VERSE
#+END_CENTER

** Mage gris

#+BEGIN_CENTER
#+BEGIN_VERSE
    Notre vaste univers n’est qu’une discothèque
    Un ouvrage tissé de reflets chatoyants
    Un seul et même éclair aux infinies facettes
    Dont l’image est partout projetée et suivant

    L’angle ou le point de vue l'épine est une rose
    Le cygne un flocon chaud perdu dans les bermudes
    L’autruche un hérisson à la barbe un peu rude
    Tout se tient tout se sait tout se métamorphose

    Le gel est un nuage aux vagues innombrables
    L’averse est la buée la neige est l’ouragan
    La marée reconstruit d’autres châteaux de fable
    La seule et même étoile est tout le firmament

    ***

    Et nous, que sommes nous, perdus dans le dédale
    De ce temple irréel où tout mène à l’étrange
    Que sommes-nous sinon les princes des rafales
    Les esclaves des flots, les frères des mésanges ?

    Que sommes-nous sinon ces éternels rêveurs
    Qui dans l’ombre complice arpentent l’idéal
    Et frôlent chaque soir les voûtes sidérales
    Portiques infinis des mondes enchanteurs ?

    Or tu es l’un d’entre-eux, toi qui appris si jeune
    La vision du silence et l’aura de l’infime
    Tu sauras retrouver la source des fontaines
    Toi qui sais que l’absurde est proche du sublime

    ***

    Oui, tu sauras renaître aux rosaces qui saignent
    Diamants ciselés que l’amour illumine
    Mais s’il vient l’incendie des colères mesquines
    Tu seras ce miroir qui reflète la haine

    Pour l’envoyer brûler ses pâles stratagèmes
    Ton feu contre le sien du philtre au talisman
    Et relier les pics escarpés de l’extrême
    Gardien de l'équilibre en ce bal tournoyant

    Pour diriger la nef il te faudra du vent
    Qui souffle sur les dés du hasard en finesse
    Pour que le couple danse il te faut la caresse
    D’une brise orbitale et d’un soleil couchant

    ***

    Tu seras le gardien des balances célestes
    Sur le faîte des ergs tu iras funambule
    Sur la dune en croissant du sable palimpseste
    Tu verras jour et nuit s’unir au crépuscule

    Jouant des vieux encens et des sons tamisés
    D’artifices en feu sur un vif trampoline
    Tu vibreras en phase avec les alizés
    Tu seras le coton des rêves d’opaline

    Mage gris des sentiers et des douces chaumines
    Tu tiendras dans tes mains cet improbable alliage
    Qui mêle le Dragon au Dauphin des naufrages
    L’incendie au glacier et la rose à l'épine
#+END_VERSE
#+END_CENTER

** Ariette

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sur quoi repose une vie
    Qu’un peu de cendre et de pluie
    Qu’un peu de cendre emportée
    Dans la tempête en furie

    De ma viole éventrée
    Flotte cette mélodie
    Sur quoi repose une vie
    Qu’un peu de cendre et de pluie

    Cette ariette délabrée
    Est le fruit de ma folie
    La chanson part en fumée
    Pour qu’un souffle l'éparpille

    Sur quoi repose une vie
    Qu’une complainte assourdie
    Quelques plumes égarées
    Dans un dédale d’envies

    Un peu de cendre et de pluie
    Comme une rose flétrie
    De ma viole éventrée
    Dans la tempête en furie

    Les colombes enlacées
    Dans leurs fragiles coquilles
    Peignent leur cage feutrée
    Mais si l’encre s'égosille

    La chanson part en fumée
    Comme une rose flétrie
    Pauvres cordes étouffées
    Sur quoi repose une vie
#+END_VERSE
#+END_CENTER

** Aux rages

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ecriras-tu cet éclair
    Vite avant qu’il ne s’efface
    Quand la lueur qui t'éclaire
    Etait un autre zig-zag

    Peux-tu attrapper la foudre
    La sceller dans une boîte
    Que le feu marque le foudre
    Aux armoiries de l’agate

    Puis dérouler le tonnerre
    Avant que le temps fatal
    Ne noie ces chants qui tonnèrent
    La voie tiédie des fractales

    Peut-être entre les dorures
    De l’enluminure éteinte
    Pourras-tu voir l’embrasure
    D’une vérité étreinte

    T’infiltrer sous l'échancrure
    En ignorant les chardons
    Et découvrir la parure
    Que te cachait le charbon

    Tu nous diras ces gargouilles
    Dont le dos écaillé bronze
    Dont le gaster qui gargouille
    Dévore ses soeurs de bronze

    La pose assoupie des sphynx
    Aux pyramidions aztèques
    L’air indolent de ces lynx
    Adorateurs de pastèques

    Les escadrons de soucoupes
    Au milieu des confitures
    Le grésillement des coupes
    Enfin la déconfiture

    Des flèches à plein carquois
    Transperçant brume et peinture
    Et le sol d’un bras narquois
    Qui t’arrache aux fioritures

    Lors que tu n’as pas écrit
    Le dixième du centième
    Pas une rame assouplie
    D’une flotte de trirèmes

    Et la patine coquette
    Qui râle pour un dièse
    Elle efface elle caquète
    Remanie la diérèse

    Indique de sa baguette
    Que le décor est trop âpre
    Qu’aux artichauts en barquette
    Elle préfère les câpres

    « Ces effluves d’ammoniac
    « Dois-je tout faire moi-même ?
    « Il faut le couvrir d’un lac
    « D’eau de rose et de bohème

    « C’est qu’on croirait un cloaque
    « Quelle horreur des frangipanes ! »
    Telle est la douceur qui claque
    Fouet parfumé de pivoines

    De peu qu’elle ne te dise
    « Es-tu sûr d’avoir vu ça ? »
    Et toi d’une encre cerise
    De signer lalilala
#+END_VERSE
#+END_CENTER

** Arc-en-ciel

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je te piquerai de mots bleus
    Et de leurs charmes venimeux
    Qui t’embrasseront langoureux

    Je t’assiégerai de mots beiges
    Nous entremêlerons nos pièges
    Dans la tiède douceur des neiges

    Je t'épargnerai les mots mauves
    Je préfère tes teintes fauves
    Au parfum terne des guimauves

    Je te voilerai de mots noirs
    Pour que tu entrevoies l’espoir
    A travers les mailles du soir

    Je te huilerai de mots jaunes
    Je te couvrirai de leur baume
    Masserai ta peau dans leur chaume

    Je te borderai de mots verts
    Mis a l’index aux monastères
    Pour hanter tes rêves d’hiver

    Je te napperai de mots roux
    A la fois sauvages et doux
    Qui s’insinuent dans les froufrous

    Je t’inonderai de mots blancs
    De ceux qui montent lentement
    Comme une marée de printemps

    Je te marquerai de mots bruns
    Pour faire couler ton chagrin
    Hors de ton corps hors de tes reins

    Je t’effeuillerai de mots roses
    De ceux qu’on dit quand tout explose
    Que l’on s’enfuit loin du morose

    J’insufflerai les mots oranges
    Dans ces pulsions qui nous démangent
    Pour fondre nos chairs dans la transe

    Je t’enflammerai de mots rouges
    Chacun de l’autre maître et gouge
    Dans l'éther surchauffé qui bouge
#+END_VERSE
#+END_CENTER

** Bleu blanc rouge

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ses cheveux irisés par un ciel de saphir,
    Son buste parsemé de perles chatoyantes,
    Son ventre secoué par l’onde luxuriante,
    La mer livre sa peau de pervenche au zéphyr.

    Sur son trône d’albâtre et de marbre éclatant,
    Vénérable empereur des dômes enneigés,
    Le vieux sommet chenu, de rayons couronnés,
    Verse dans la vallée des pleurs de diamant.

    La bûche dans le feu nous conte les aurores,
    Les couchants empourprés qu’elle a vu s’abîmer.
    La flamme est un soleil d’améthyste égaré
    Qui s’enfuit vers l’azur dès que l'âtre s’endort.

    Mais le bleu c’est aussi une larme profonde
    Qui répand le sérum des naïades blessées,
    C’est une fuite d’eau au barrage qui gronde,
    Lugubre augure avant le grand raz-de-marée.

    Mais le blanc c’est aussi la lumière spectrale
    Qui s'échappe en hurlant des livides fantômes
    Dont les coeurs tourmentés dans leurs draps de cristal
    Ont pour seuls compagnons les follets et les gnômes.

    Mais c’est aussi le sang sur les lèvres rubis
    Des succubes en rut les nuits de pleine lune,
    Le sabbat des dragons sur les coteaux maudits
    Qui crachent un enfer de fer et de rancune.
#+END_VERSE
#+END_CENTER

** Beaujoli villages

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le vigneron carillonne
    L’heure des vendanges sonne

    Les beaux raisins sont bien mûrs
    Les lourdes grappes vermeilles
    Pèsent leur poids sur la treille
    On croirait un champ de mûres

    Les vendangeurs emprisonnent
    Les coloris de l’automne

    Dans les arbres, les buissons
    La campagne se barbouille
    C’est une autre floraison
    De menthe, d’or et de rouille

    Le tonnelier assaisonne
    La brûlure de l’automne

    Les branchages déssèchés
    Illuminent, nostalgiques
    La saison mélancolique
    Aux derniers feux de l'été

    Et la bouteille emprisonne
    Les crépuscules d’automne

    Le couchant à l’agonie
    Consume l’ultime jour
    Sur terre la frénésie
    Se sublime dans l’amour

    Le liège tire-bouchonne
    Les alizés de l’automne

    Etincelantes de braises
    Les essences de framboises
    De groseilles et de fraises
    Embaument l'éther d’extase

    La jolie robe frissonne
    Des caresses de l’automne

    Ainsi que d’un corps peu sage
    S’avancerait un tétin
    La liqueur sans son corsage
    Libère l'âme du vin

    Et le nectar me tisonne
    Du miel des soleils d’automne

    Le feu coule dans la gorge
    Depuis son palais de verre
    Ensevelissant l’hiver
    Sous des champs de sucre d’orge

    Dans ma cervelle chantonnent
    Les chaudes brumes d’automne
#+END_VERSE
#+END_CENTER

** Arrière-saison

#+BEGIN_CENTER
#+BEGIN_VERSE
    Reviens-moi, ma douce Folie
    Ensemble partons
    Vers ces pays où la mélancolie
    Nous sert d’avirons

    Rejoins-moi, qu’ensemble comme avant
    Nos éclairs de rire
    Nous soit un bélier ivre de délire
    Contre les coups du temps

    Offrons-nous de l’impossible en cascade
    Laissons-nous guider par les tornades
    De nos émotions ;
    Ayons le coeur nomade,
    Ensemble rêvons

    Tu as les clefs, j’ai les tenailles
    De nos lourds boulets de grisaille
    Ne nous fait point languir,
    Cette porte de marbre noir
    Réservoir de nos cauchemars
    Qu’attends-tu pour l’ouvrir ?

    Partons pour le pays des fables
    Où tout, même la pierre, a un nom ;
    Dans ce pays d’or de sons
    La moindre auberge est une douce étable
    Lorsque la Joie s’y attable
    Et nous chante des chansons

    Tu es là, ma douce Folie
    Et je vois que tu as amené les onguents
    Pour panser mes vieilles blessures,
    Soit louée pour cette hérésie
    Contre le monotone et son code pesant.
    Adieu, mon antique robe de bure,
    Aujourd’hui je change de parure

    Le soleil décline, qu’importe
    Dans mon coeur c’est le carnaval
    Un vent étrangement musical m’apporte
    Ses chaudes couleurs automnales

    Partons pour ce pays où les arbres sont bleus
    Et les cieux émeraudes,
    Où le crépuscule n’est qu’une nouvelle aube
    Teintée d’or et de feu

    Viens, laissons là cet air rance de moisissure
    Allons regarder si, de la lune
    On aperçoit ce triste monde en miniature
    Oublions nos soucis, nos rancunes
    A nous le somptueux cellier de la luxure !
#+END_VERSE
#+END_CENTER

** Ivresse

#+BEGIN_CENTER
#+BEGIN_VERSE
    On en voit si peu
    De rosiers en fleurs
    De rosiers en feu
    Qui nous font des fleurs

    Auprès de l'étang
    Ils tremblent de lire
    Le parfum troublant
    Troublant du désir

    C’est le coeur tremblant
    Que l’ondine chaude
    Caresse le vent
    De ses émeraudes

    Car les fruits d’antan
    Fleurons à venir
    Les flocons d’argent
    Ont peur de flétrir

    Les arbres blessés
    Pleurent le printemps
    Là-bas dans les champs
    Plombés par l'été

    La chandelle vive
    Consume l’orgueil
    La frondaison ivre
    Essaime ses feuilles

    Pourtant quand le ciel
    Ne peut se dédire
    Les épis de miel
    Epicent la cire

    C’est qu’il y a tant
    De choses à dire
    Aux jours qui pourtant
    Ne cessent de fuir

    C’est qu’il y a tant
    De fleurs pour l'écrire
    Les fleurs cependant
    Ont peur de le dire

    Ont peur et pourtant
    Qui oserait rire
    Quel fol épi blanc
    Neigerait son ire ?

    La chandelle vive
    Ne peut les atteindre
    Qu’une fugitive
    Seconde à étreindre

    Là-bas dans les champs
    Au seuil d’un soupir
    Les flocons des chants
    Fondent sur la cire

    Mais le feu qui vole
    Lui seul peut enfreindre
    Les règles du sol
    Et part les rejoindre

    C’est qu’il y a tant
    De choses à vivre
    Car le ciel cinglant
    Ne cesse de rire

    De rire au soleil
    Du prochain délire
    L'éclaircie vermeille
    Aidant à sourire

    S’ils tremblent de lire
    Vivez coeurs vibrants
    C’est qu’il y a tant
    De vent à cueillir
#+END_VERSE
#+END_CENTER

** L'invisible

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tourbillonnent, tourbillonnent,
    Les feuilles de l’ancien automne ;
    Tourbillonnent, tourbillonnent,
    Encerclent l’air et l’emprisonnent.

    Encerclent l’air monochrome,
    Les feuilles de l’ancien automne ;
    Encerclent l’air monochrome,
    D’une conscience qui frissonne.

    Dans cette danse asynchrone
    Une chevelure chantonne,
    Dans cette danse asynchrone
    D’une conscience qui frissonne.

    Sur les traits flous qui se forment
    Une chevelure chantonne,
    Sur les traits flous qui se forment
    Un doux sourire s’abandonne.

    Flotte un moment le fantôme
    Dans ces couleurs qui le couronnent ;
    Flotte un moment le fantôme,
    Un doux sourire s’abandonne.

    Mais le soleil qui s'étiole
    Dans ses couleurs qui le harponne,
    Mais le soleil qui s'étiole
    Ote sa robe et sa couronne.

    L'être fluide s'évapore
    En une brise qui fredonne,
    L'être fluide s'évapore
    Dans l’infini qui l’environne.
#+END_VERSE
#+END_CENTER

** Brume

#+BEGIN_CENTER
#+BEGIN_VERSE
    La brume tombée
    Répand sa rosée
    Sans regrets et sans bruit.
    Les lampes sont pâles
    Leur lumière sale
    S'égare dans la nuit.

    Contours chaotiques
    Décor féerique
    Tout excite l’esprit.
    Là-bas, dans un coin,
    Un énorme oursin
    Qui le jour n’est qu’un buis.

    Perdus dans ce mirage
    Quelques passants enragent
    Où est donc leur foyer ?
    Nous sommes tous des ombres
    Qui hantons les décombres
    Quand vais-je déjeuner ?

    Un ivrogne joyeux
    Semble pris dans un jeu
    Il danse son bonheur.
    Alors, dans cette rue,
    Ma frayeur disparue,
    Je l’accompagne en coeur.

    Tous deux nous errons
    Fantômes un peu ronds
    Effrayant les matous ;
    Possédés de gaieté
    Criant aux attardés :
    Tu veux vivre ? Sois fou !
#+END_VERSE
#+END_CENTER

 

[[../index.php][Accueil]]

