
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Fantômes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

** Larme inconnue

#+begin_center
#+begin_verse

D’où viens-tu, larme inconnue
À la source insaisissable ?
Dont la trace, à peine émue
S’efface dans le sable ?

De quel drame millénaire
T’es-tu soudain échappée
Brusque reflet de lumière
Dans l’océan des pensées ?

Tu sembles en cet instant
Contenir tout l’univers
Et les méandres du temps
Et le rebours à l’envers

Petite perle fragile
Tu exploses de couleurs
Et tes émotions subtiles
Me font presque un peu peur

#+end_verse
#+end_center


** Souvenir d'un autre âge

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle dormait sous le duvet de plusieurs siècles
    Lorsque j’ouvris sa malle au fond du vieux grenier.
    Elle lisait un livre, une bibliothèque,
    Une plage assoupie de l’astre éternité.

    On devine un vieux rose enneigé par les âges,
    Un jeune bleu pastel parcourant la missive.
    L’encre semble orpheline et tient en une page,
    Le parchemin ondule entre les fleurs cursives.

    Elle n'était vêtue que de noir et de blanc
    Mais ses mignonnes joues coloraient son visage.
    Ses yeux noirs reflétaient le miroir d’un étang
    Où les ans asséchés n’ont pas osé d’outrages.

    La vague m’emportait de la lettre à ses lèvres,
    Je ne me souviens plus qui murmurait l'énigme,
    Mais sa vie défilait, plus réelle qu’un rêve,
    Aurais-je déchiffré cet étrange interligne ?

    Pas loin d’elle, une montre. Etait-ce sa demeure ?
    Son cadre pris au piège au verso d’un gousset
    Enchaînait-il lui même un amant et un coeur ?
    Son sourire un peu triste à jamais le taisait.

    Son regard me fixait à travers le couloir
    Du temps qui nous sépare. Alors, tout me revint :
    Sa voix, son doux parfum, et nos jeux dans le noir ...
    Je crus voir un clin d’oeil, et le jour s’est éteint.
#+END_VERSE
#+END_CENTER

** Vanille-thé

#+BEGIN_CENTER
#+BEGIN_VERSE
    De ce passé sans avenir où l’on ne plante que du sable,
    Où l’on ne sème que du bruit, où l’on n’arrose que de fables
        Une culture clairsemée,

    De cette épave qui s'échoue dans la vase alignée des siècles,
    Épique époque convoitée par l’ombre ailée de l’hypothèque
        Aux angoissantes mélopées,

    De ce passé vil et mesquin, de ces nains regroupés en sectes
    Qui noient de surcopulation, de détritus et de discours
        L’antique berceau des ancêtres,

    De ces années sans envergure où la grandeur pèse bien lourd
    Quand la féerie est si fragile, et si léger l’oubli vainqueur,
        Si apaisante la torpeur,

    De ce prélude à préhistoire, ère barbare avare d’art
    Où l'égoïsme est à la masse, et l’honnêteté une tare
        Que l’on dissimule à toute heure,

    De ce passé sans importance où l’on vénère l’apparence,
    L’hypocrisie qui réussit et le poignard de l’ignorance,
        Que t’enverrais-je qui soit pur ?

    Que t’enverrais-je qui soit pur de ces temps privés de couleurs,
    Temps qui ne font que reculer vers le néant de leurs frayeurs,
        Vers d’obscurs et d'épais murmures ?

    De ce passé qui fait la sourde oreille à l’imagination,
    Les oeufs dans les yeux d’une autruche, avance en crabe à reculons
        Que t’enverrais-je que l’azur ?

    De ce pantin désarçonné que déjà ronge le termite,
    Je ne t’enverrai que du thé à infuser dans la marmite
        Comme on découvre un diadème,

    Prends en bien soin, j’y ai mis tout, mon coeur, mon âme, et quelques rêves ;
    Il t'éclairera de lumière à l’heure où la journée s’achève,
        Car la vapeur est un poème.
#+END_VERSE
#+END_CENTER

** Et poc

#+BEGIN_CENTER
#+BEGIN_VERSE
    Deux tables dans la salle implorent qu’on s’accoude.
    La prime a de beaux yeux, deux chandeliers qui boudent,
    Quand transparente et nue, la seconde s’exhibe.

    La première est en chêne, un vieux chêne massif
    De fleurs aux parfums clairs qui étalent, lascifs,
    Les souvenirs d’antan que sa consoeur inhibe.

    En a-t-elle vraiment ou les déssèche-t-elle,
    Tel ce bouquet fané qui gîte sans attelle
    Et qui n’existe pas sur sa peau insensible ?

    De désordre, aucun signe, aucun brin de poussière
    Pour ridiculiser la pose solennelle
    Du plastique immobile agressant la lumière.

    On n’en peut dire autant de sa folle voisine
    Dont les débris épars par pleines caravelles
    Déroulent la légende emplissant sa poitrine.

    De la danse et des chants ont garni cette table,
    Scandés par les pieds fins d’une souple gazelle,
    Bien loin du verre aigri servi au connétable.

    Il suffit de souffler pour animer les fables,
    Qui y colle l’oreille entend son chuchotis
    Mais lui n’y entend rien, beugle « meuble vieilli ».

    Oui, lui, ce vil marchand, cet animal d'étable
    Prétend que de la roue l'âge efface le charme,
    Le hurle car il croît qu'éventer du vacarme

    Le peut rendre crédible ; il me dit « l’autre table
    A la cote aux égoûts du mauvais goût tendance. »
    Moi d’asséner : « je prends celle des deux qui danse. »
#+END_VERSE
#+END_CENTER

** Je voudrais

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je voudrais composer une ode nostalgique
    Pour chanter ces regards éclairs tombés à l’eau
    Lecteur tu t’en souviens de ces yeux romantiques
    Qui percèrent ton coeur de leur double carreau

    Je voudrais composer une valse classique
    Et la danser en elle au rythme de l’aurore
    Tourner tourner encore et de plus en plus vite
    Dans sa robe fleurie impatiente d'éclore

    Mais cher ami Lecteur tu connais la musique
    Ce ne fut qu’un regard un éclair dans la nuit
    Je sais que toi aussi ces beaux yeux magnétiques
    Tu voudrais bien les voir ronronner dans ton lit

    Elle se balladait dans le creux d’une crique
    Le courant t’emportait vers d’autres archipels
    Elle avait l’air rêveur doux et mélancolique
    Et toi tu n’as pas su répondre à son appel

    Où est-elle à présent sur quelle île exotique
    S’endort-elle apaisée sous la lune d’argent
    Je voudrais la croquer d’une envolée lyrique
    Mais je suis bien trop las revenons au présent
#+END_VERSE
#+END_CENTER

** L'horloger

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le Temps, ce vieux moulin qui ne rêve qu’espace,
    A dès son aube tiède assemblé une horloge
    Où son bras implacable à qui nul ne déroge
    Ecrit sur un cadran sa loi sourde et fugace.

    Actionnant le broyeur dans leur étroite loge,
    Les aiguilles stylées notent ce qui s’efface :
    Leur encre ensorcelée ne laisse nulle trace
    D’un code si fuyant qu’aussitôt il s’abroge.

    Ainsi que du poussin la fragile coquille
    Lézardée par sa fille ingrate et duveteuse,
    L’heure à peine entamée craquelle et se fendille,

    Le sablier roussit, la clepsydre se creuse ;
    Epiçons chaque grain, infusons l’eau précieuse !
    Avant que le meunier l’emporte et l'éparpille.
#+END_VERSE
#+END_CENTER

** Ruelle

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est une simple rue au détour d’un faubourg ;
    Les maisons sont en pierre et de sourdes lumières
    Risquent un oeil rougeâtre au jugement du jour.
    Les vieux volets de bois ont déclos leurs yeux verts

    Et l’on distingue encore un coeur pris par l’hiver
    Au milieu du vernis délavé par la pluie.
    Les pavés patinés hébergent la poussière
    De pas comme creusés, de fragments d’une vie.

    S'échappant d’un jet d’eau, tordant l’air de leur trille,
    Des murmures vibrants se mettent à chanter :
    « Je n'étais qu’un soupir couvé sous la mantille,
    Moi j'étais un poignard, une bourse, un baiser ... »

    Mais le soleil pâlit derrière l’horizon
    Tout s'éteint, tout se tait, et je rentre à tâtons.
#+END_VERSE
#+END_CENTER

** Voyages antérieurs

#+BEGIN_CENTER
#+BEGIN_VERSE
    Thèbes ! Je me souviens, la cité des Titans !
    J'étais scribe et peignais les immenses richesses
    Arrivées de Nubie et des ports de l'Orient.
    Des forêts de piliers narguaient de leur altesse
    Les cîmes écrasées de l’ambition humaine
    Tandis que le dieu Nil déversait ses largesses
    Sur l'Egypte imbibée des récoltes prochaines.
    Les filles du Delta, prodigues en caresses,
    Confiaient au vent léger de beaux baisers d’ivoire ;
    Les felouques vogaient, gonflées de leurs promesses ;
    Je me laissais bercer par les flots bleus et noirs.

    Athéna, souviens-toi, et l'Olympe en furie,
    La Junon colérique aigrie de jalousie ;
    La Vénus volcanique et ses monts incendiaires
    Où Mars ne fut pas seul à planter sa bannière ;
    Apollon écrivant des lettres enflammées
    Sur le coton neigeux des Muses moutonnées
    Et Diane, sa soeur, chasseresse esseulée.
    Aux fêtes de Bacchus, j’allais en dilettante,
    Riant des facéties de Pan et des Bacchantes ;
    Les pichets se jouaient des plis de ma mémoire,
    Je me laissais bercer par les vins bleus et noirs.

    Je me souviens de Rome, ivre de sa puissance :
    Les palais orgueilleux recouvraient le latium
    De marbre, de bijoux, de folle décadence.
    Par ordre du Sénat et de César auguste,
    L'Empire tout entier, sesterces et forums,
    Fleurissait sous l’aura d’un seul et même buste ;
    J’errais dans les bains chauds, les banquets d’atrium
    En regardant passer les flottes de trirèmes
    Qui menaient dix légions vers la Judée lointaine :
    Le moindre centurion courait après la gloire,
    Je me laissais bercer par les flots bleus et noirs.

    Telle est la mélopée des soupirs nostalgiques
    Enlacés dans la pierre aimante et magnétique
    Des ruines habitées par les flots bleus et noirs.
#+END_VERSE
#+END_CENTER

** Les instants

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il est de ces instants plus vifs et plus intenses
    De ceux que l’on devine avides de graver
    Leurs traits fins et précis, leur souple degradé
    Dans le creuset témoin des rires, des souffrances

    Qu’enroule notre esprit sur le tapis du temps.
    Ils se figent alors et se font oublier.
    Plus tard ils renaîtront, rappelés du passé
    Par une odeur infime égarée dans le vent.

    Ils ressortent alors du silence ou du vide
    Et l’aurore argentée dévoile l’atlantide
    Sur le trop vieux sommeil qui agitait nos sens.

    Alors, le soleil luit sans masquer les étoiles
    Et tout nous apparait : lumières, sons, ambiances
    Dans ce rêve éveillé qui traverse le voile.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
