
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Hommages
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Aux poètes nomades

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les oiseaux migrateurs les frères des nuages
    Ont l’oeil si lumineux qu’il perce l’horizon
    Fixent-ils au-delà de l’irréel rivage
    Un printemps éternel parsemé de boutons ?

    Ils puisent dans l’air pur la sage déraison
    Pour créer par le chant des paradis terrestres
    Et s’ils daignent parfois quitter l’abri céleste
    Ce n’est que pour le temps d’une courte saison

    Car jamais un soupir n’a brisé le vent d’est
    Viennent toujours l’hiver la neige et les ténèbres
    Il suffit d’une corde aux mélopées funèbres
    Pour distordre d’un trait l’harmonie de l’orchestre

    Et rayer le couchant d’un pelage de zèbre
    Aussi dès que frémit la moindre discordance
    L’appel du grand frisson leur parcourt les vertèbres
    Leurs ailes se déploient et d’un souffle ils s'élancent

    Vers d’autres méridiens où la brise est plus douce
    Abandonnant aux nuits dont les serpents s’avancent
    L'écaille de leurs oeufs d’anciennes jeunes pousses
    Roussies par le soleil pesant des décadences

    Oiseaux majestueux d’un incessant voyage
    Qui fuyez sans répit la volaille qui glousse
    Combien vous faudra-t-il essuyer de secousses
    Avant de vous poser sur un heureux rivage ?
#+END_VERSE
#+END_CENTER

* A vous tous

#+BEGIN_CENTER
#+BEGIN_VERSE
    A vous tous, insensés ! qui recherchez un but,
    Un sens à cette vie et à votre folie ;
    A vous tous qui cherchez à poursuivre la lutte
    De vos rêves brisés au pied de votre lit ;

    A vous dont les marées de rires et de pleurs
    S'écrasent sur le roc des falaises sans vie ;
    Courage ! Vous avez un océan de fleurs
    Pour bercer vos douleurs et vos mélancolies ;

    A vous qui partagez vos vers plein de douceurs,
    Vos amours, vos chagrins, vos frayeurs, vos angoisses
    Et qui les guérissez d’un baume de chaleur
    Doucement, avec tact, de peur qu’ils ne se froissent,

    Vous êtes les soleils de ma profonde nuit
    Et c’est du fond du coeur que je vous dit Merci !
#+END_VERSE
#+END_CENTER

* Marceline Desbordes-Valmore

#+BEGIN_CENTER
#+BEGIN_VERSE
    Etait-ce toi au piano ma châtelaine
    Ton parfum jusqu’ici embaume le clavier
    Des fleurs contre des fleurs oui donne et soit ma reine
    Belle rose déclose échappée du passé
    Etait-ce toi ?

    Tes vers ont traversé un peu plus de deux siècles
    Pour venir s'échouer en sanglots lourds d’orages
    Tes vers ont débordé les miens ne sont plus secs
    Mais j’ai lu dans tes yeux les lettres du courage
    Mais j’ai lu dans tes yeux

    Que tu songes le soir en déroulant tes tresses
    Souffrir faire souffir l’amour double tranchant
    Des pleurs contre des pleurs donne et soit ma maîtresse
    J'écrirai malgré toi tout ce que tu défends
    Que songes-tu ?
#+END_VERSE
#+END_CENTER

* Théodore de Banville

#+BEGIN_CENTER
#+BEGIN_VERSE
    Mais pourquoi un douzain ? Me diras-tu compère,
    Un dizain eut suffi ! C’est là ma fantaisie.
    Et puis je te l’avoue, je veux t’offir un vers
    Nouveau, fruité, joyeux, où la rime frétille.
    A toi le virtuose, à toi Roi de l’escrime,
    Je veux faire goûter ma Muse, mon amie
    Qui s’amuse à chanter et danser les quadrilles ;
    Donc je croise et j’embrasse et du plat je l’imprime !
    Et puisque ton luth d’or déridait les jets d’eaux,
    Frère, Prince, Poète, accepte ce rondeau ...
    Mais pourquoi un douzain ? Me diras-tu compère,
    Un dizain eut suffi ! Je veux t’offir deux vers.
#+END_VERSE
#+END_CENTER

* Charles Baudelaire

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le ronron enjôleur du félin affamé
    Et les griffes aiguës de sa fière maîtresse,
    La piquette à trois sous vendue par l'épicier
    Et l’atroce nausée qui attaque en traîtresse,

    De l’hiver frissonant la brume âcre et épaisse
    Qui empoisonne l’air de sa bile jauneâtre,
    Immuable relief de l’estivale ivresse
    Endormant le pays en un sommeil douceâtre,

    Le voyage au néant, vers l’aube d’hyacinthe,
    Les liqueurs de Lesbos, les opiums de Cythère,
    Les goules, les serpents, les verroteries teintes,
    Tout cela ne vaut pas un vers de Baudelaire.
#+END_VERSE
#+END_CENTER

* Théophile Gautier

#+BEGIN_CENTER
#+BEGIN_VERSE
    Un tableau d'Albertus est accroché au mur,
    Renaissance baroque encombrée de chats noirs.
    Chauve-souris, follets, spectres, restes d’armures,
    Y dansent le sabbat dans un obscur manoir.
    La toile surchargée est sciemment grotesque ;
    Une horloge arrêtée contemple l’oeuvre d’art.
    Sur la table, une plume de soie et d’ivoire
    - Secrète affinité  ? - contient autant ou presque
    De nuances de tons que l’atelier d’un maître.
    Un merle impressionné sifflote à la fenêtre,
    Posé sur le nacré marbre des arabesques.

    Théophile Gautier
    Ecrit la rose-thé.
#+END_VERSE
#+END_CENTER

* Charles Leconte de Lisle

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le Soleil de souvient du rêve de son rêve.
    La jungle, où jaillissaient des spectres séculaires
    Etouffe sous l’immense ombre crépusculaire
    Du Condor qui contemple un Temple qui s'élève.
    En bas, un champ de ruine où fleurit le mystère,
    Hanté par la légende et les Elfes des îles.
    Les Druides psalmodient les Esprits des clairières,
    Veillant sur Leïlah et son sommeil fragile.
    Les songes se marient en visions chimériques ;
    Les Nornes, les Hurleurs, les Déesses antiques
    Prennent corps même au coeur de l’insipide ville :
    C’est cela la magie de Leconte de Lisle.
#+END_VERSE
#+END_CENTER

* Le berger blanc

inspiré de la chanson /Le paradis blanc/,\\
 de Michel Berger\\

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je n’ai pas un radis mais si j’avais l’argent
    Je m’en irais construire un chalet sous le vent
    Si haut que pas un cri ne troublerait l'étang
    Je n’ai pas un radis mais si j’avais l’argent
    L’humanité vivrait un éternel printemps
    Loin des combats d’enfants et des guerres de clans
    Je n’ai pas un radis mais si j’avais l’argent
    Je m’en irais construire un chalet sous le vent

    Je manque un peu de voix mais si j’avais l’orage
    Il irait foudroyer toute idée de carnage
    Ecraser sans pitié la tyrannie sauvage
    Je manque un peu de voix mais si j’avais l’orage
    Il irait balayer l’hypocrisie sans âge
    Qui s’amuse à bâtir des déserts sans nuage
    Je manque un peu de voix mais si j’avais l’orage
    Il irait foudroyer toute idée de carnage

    Je manque un peu d’espoir mais si j’avais l’horloge
    J’inverserais le cours des eaux où l’heure loge
    Juste pour les revoir briller sous la limoge
    Je manque un peu d’espoir mais si j’avais l’horloge
    J’inventerais ce temps qu’aucun temps ne déloge
    Du sable à égréner qu’aucun siècle n’abroge
    Je manque un peu d’espoir mais si j’avais l’horloge
    J’inverserais le cours des eaux où l’heure loge
#+END_VERSE
#+END_CENTER

* Pierre de Ronsard

#+BEGIN_CENTER
#+BEGIN_VERSE
    Assieds-toi donc Ronsard,
    Assieds-toi, il faut boire !

    Nulle flèche d'Amour
    N’a résisté au vin ;
    Si ton coeur est trop lourd
    Le remède est divin !

    Assieds-toi donc Ronsard,
    Assieds-toi, il faut boire !

    Grise-toi de l'Oubli
    Des Orchidées trop fières ;
    Trinquons aux prés fleuris
    Et aux Roses légères !
#+END_VERSE
#+END_CENTER

* Fille d'automne

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle est source de paix d’espoir et de lumière
    Et s’enroule sans cesse en valses inconnues
    Ceux qui ont entrevu son âme à demi-nue
    Savent l’intensité que couve le mystère

    Elle est source d’espoir mais c’est un soleil noir
    Qui rayonne à pleins feux sans rien garder pour elle
    Tant elle est généreuse à dispenser le miel
    Qui coule de ses deux magnétiques miroirs

    Son bijou le plus beau c’est son coeur couvert d’or
    Qu’un ange langoureux sensuel et félin
    Lui sculpta au berceau en effleurant ses seins
    Et peut-être qui sait ? le reste de son corps

    Elle assemble les mots dans des musiques folles
    Pour guérir ses douleurs et hurler son amour
    Elle voudrait pouvoir renflouer d’un discours
    Les voiliers naufragés qui hantent les rigoles

    Ses jeux ses chants ses vers imprégnés de magie
    M’ont redonné le goût de croire en l’avenir
    La tendresse absolue qui sort de ses délires
    Ses amis vous diront qu’elle a changé leurs vies

    J’ai peur de te l’offrir ce contre-jour bien pâle
    Comparé aux splendeurs de ta brillante étoile
#+END_VERSE
#+END_CENTER

* Le Chat Noir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans Montmartre l’ancienne obscurcie par l’air flou
    Si tu entends le chant de rimeurs un peu gris,
    De musiciens bourrés (d’autres diraient fin saouls) ;
    Si tu résiste' aux clins des yeux mi-verts mi-gris,
    Avance' et tu verras parmi l'épais brouillard,
    Accoudée comme une habituée sur le bar,
    A deux pas de la butte, auprès de la Galette
    (Tu sais ce vieux moulin fleuri de galipettes),
    Tu entendras rouiller l’enseigne du Chat Noir.

    Si tu n’es point pédant, souteneur ou grigou,
    Si tu préfère' au jour les ombres de la nuit,
    Si ta lyre est mordante ou même sans tabou
    L’endroit est accueillant (sauf peut-être aux souris).
    Sais-tu peindre, scander, jouer ou même boire ?
    Entres, c’est là l’endroit où partager ton art !
    Si tu ne crains pas de défriser les soubrettes,
    De finir sur un banc ou mieux sur la carpette,
    Assieds-toi et commande une absinthe au Chat Noir.

    Encore à cette époque, on entend les matous
    Feutrés et ronronnants pousser l'éternel cri
    De ralliement du sage en un long miiaaawwwou.
    Leur appel donne forme aux contours de la nuit
    Sous la lune qui prend le pavé pour miroir
    Et le tam-tam des fille' errant sur le trottoir.
    Ce concert de filous aux maigres silhouettes,
    Affolant jusque dans leurs terriers les coquettes,
    C’est le fantôme du cabaret du Chat Noir.
#+END_VERSE
#+END_CENTER

* Paul Verlaine

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’automne est en deuil, finie la chanson
    Mais l'écho de ton rêve familier
    Sonne encore douze aux joyeux pinsons.

    Ectabane en feu brûle le péché
    Mais Sappho, toujours, chante les amies
    Entre deux baisers vers l'éternité.

    Les coeurs sont en pleurs dans les eaux fleuries :
    Les sanglots longs bercent les nénuphars.
    C’est ton vers impair qui pleure dans les eaux fleuries.

    La femme et la chatte ? Leur jeu continue car
    Ô joyeuse, joyeuse est la claire rengaine
    Ecrite, écrite de la plume de Verlaine.
#+END_VERSE
#+END_CENTER

* Victor Hugo

#+BEGIN_CENTER
#+BEGIN_VERSE
    Là-haut, loin dans le ciel, un aigle étend ses ailes ;
    Déjà, pour l’escorter, l’orage s’ammoncelle.
    Ses serres sont d’airain ; dans ses yeux des éclairs
    Vengent la liberté qu’un roi fort peu civil,
    Inconscient du danger, a osé mettre aux fers.
    Alors, c’est l’ouragan, le souffle de l’exil,
    L’averse vérité qui inonde la ville.

    Mais Hugo c’est aussi les palais flamboyant,
    Les rythmes, les parfums, les charmes de l’orient ;
    Puis la contemplation des feuilles de l’automne
    Où la mélancolie s’engouffre et tourbillonne ;
    Mais Hugo c’est le romantisme étincelant.
#+END_VERSE
#+END_CENTER

* Anniversaire

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sirène des radeaux et des petits poissons,
    Ne trouble plus le champ de l’eau qui te dévoile,
    Laisse entre les épis choir la constellation
    Qui accroche à ton cou sa vingt-sixième étoile.
#+END_VERSE
#+END_CENTER

* A une fée

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les mots se sentent lourds
    Aussi lourds que la glaise
    De dépit ils se taisent
    Dès que le monde est sourd

    Les vers ne sont pas mûrs
    Ils sont verts de colère
    L’inaltérable azur
    S’assombrit de poussière

    La rythmique des stances
    Prends un coup dans l'étrave
    Et se retrouve esclave
    De l’horrible substance

    Un élégie s’impose
    Au chevet d’une fée
    Quand le cafard morose
    Envahit ses pensées
#+END_VERSE
#+END_CENTER

* Les phares

#+BEGIN_CENTER
#+BEGIN_VERSE
    Baudelaire, parfums embrumés de lumière
    Murmurant le voyage à la pipe opiacée
    Qui serpente sous une lampe tamisée.
    Au balcon chante une vague crépusculaire.
    Le vin, rubis du soir empli de souvenirs,
    Retarde l’horloge tandis que ses vampires,
    Sa femme et son chat languissent dans la tanière

    Rimbaud, vaisseau obscur emporté par la nuit
    Loin du rivage calme de ses dix-sept ans.
    Des canons de couleurs surgissant de son flanc
    De leurs feux d’artifice éclairent l’infini,
    Crachent leurs voyelles vers une tour éteinte
    Et sabordent le port de sa profonde empreinte.
    S'évadant de la terre, un dormeur pousse un cri

    Verlaine, un air léger, une chanson qui sonne
    Un écho qui résonne dans nos émotions
    Douce ritournelle parcourue de frissons.
    De le ciel soit de bleu, de pluie ou bien d’automne
    Tous les sons s’amoncellent, gazouillent et voltigent
    Des gammes les plus graves aux plus frivoles tiges.
    Vertigineuse danse où le vent tourbillonne

    Charles d'Orléans, mélancolie en ballade.
    Son coeur est pris d’assaut par Tristesse et par Joie
    Dedans ses ronds d’eau clairs février, mai ondoient.
    De sa plume les Pensers ressortent nomades ;
    Abrité s’est en la forêt de Nonchaloir
    Son âme sous garde du chevalier Espoir.
    De ses douces Amours naissent ses sérénades

    Hugo, aigle juché en haut de la falaise
    Dont l’oeil perçant menace de serres d’airain
    Le roitelet cruel qui croit ne risquer rien
    Et qui se cache en vain derrière des fadaises.
    L’autan, le bois, l'étoile et la vérité fière
    Lui sont autant d’alliés et il parle au tonnerre.
    Devant lui la honte bue se sent mal à l’aise

    Mallarmé, beauté pure flottant dans l’azur
    Oiseaux angéliques enivrés d’horizons
    Des fleurs toutes couleurs et de soleil profonds
    Oranga arrosé rouge, vert framboise et mûre
    Flottent haut ses ailes dans les cieux en délire
    Ses plumes se rappellent un unique mot : fuir !
    De sa fuite l’envers nous apporte un murmure
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

