
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Journal
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Le baron noir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je suis le baron qui se vautre,
    Je suis l’homme aux mille casquettes,
    Je prends d’une main ce que l’autre
    Semble jeter aux oubliettes.

    Je suis le Roi recouvert d’or
    D’un tas de bouseux abrutis ;
    Je leur vend plus de boue encore
    Pour qu’ils en gavent leurs petits,

    Qu’elle leur bouche le cerveau
    Qu’ils soient sourds, aveugles, idiots ;
    Que leurs mains creusent leur caveau
    Tandis qu’ils flattent mon ego !

    Car je leur laisse la parole
    Pour qu’ils encensent mon saint nom ;
    Il suffit de quelques babioles
    Et ils gonflent mon beau ballon.

    Tous ces zombies votent pour moi :
    Je suis leur ampoule blafarde ;
    La nuit les fait trembler d’effroi,
    Le secret du jour je le garde.

    Dans ma belle administration
    - Il faut bien nourrir sa famille -
    Trois quart des postes sont bidons
    Le reste est là pour que ça brille.

    J’ai des sociétés pour sucer
    Les clients engorgés du bout ;
    Quelques emballages dorés
    Et le fric gicle de partout.

    Et pour soulager la misère
    J’ai quelques drogues en réserve,
    J’ai soucis de l’humanitaire :
    Ces gens dormiront mieux sous l’herbe.

    Non, je m’ennuie en vérité,
    La loi m’ouvre ses jambes en l’air ;
    Normal c’est moi qui fait voter
    Et détruit les parlementaires.

    La presse m’y est fort utile
    - La fange tache ce qu’on veut -
    Scandale au poing, elle mutile
    Et le corbeau regarde, envieux.

    Je suis la pieuvre enracinée,
    Vipère attifée en couleuvre :
    Ce tas de cendres calcinées,
    C’est ma fierté et mon chef-d’oeuvre.
#+END_VERSE
#+END_CENTER

* Le perroquet

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je suis un triste perroquet
    Qui répète ce qu’on lui dit
    Je vis dans un estaminet
    Et m’alimente de mépris

    Le vrai du faux je m’en bat l’oeil
    Moi j’imprime ce qu’on me dit
    J’arrive à voiler mon orgueil
    Dans le parfum des oeufs pourris

    Nourrissez-moi tous de scandales
    Que je puisse enfin exister
    Couronnez ma muse vénale
    En reine des prostituées

    Mon encre et mon âme sont noires
    Si je tombe à court de papier
    J’inventerai d’autres cafards
    Pour vous les coller sur le nez

    Je suis un triste perroquet
    Mes mains sont couvertes de boue
    Je salis tout ce qui me plaît
    Quand les rotatives s'ébrouent

    La diffamation est mon arme
    Les sous-entendus mon armure
    Je ferai pleuvoir d’autres larmes
    Pour me payer d’autres parures

    Les serpents se mordent la queue
    Ils n’ont pas peur de s'étouffer
    Je vous avoue je suis comme eux
    Car je n’aime pas vérifier

    Si vous voulez qu’un ciel d’azur
    Remplace mes titres crottés
    Dites que je suis une ordure
    Je m’en irai le répéter
#+END_VERSE
#+END_CENTER

* Victime de l'ombre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il fit froid cet hiver,
    Je suis mort sous un pont :
    La fin de mon calvaire,
    D’une vie de bouffon.

    L’on me dit la victime
    De cette société
    Qui, par peur de l’abîme,
    Ne s’accuse jamais.

    Je n'étais pas armé,
    Ne revendiquais rien,
    Aucun sang n’a coulé
    Dans le creux de mes mains.

    La mort sans violence
    N’intéresse personne
    - Horreur quelle indécence,
    Le bon goût lui pardonne ! -

    Je suis mort sous un pont,
    Un pont non stratégique
    Meublé de vieux cartons,
    De vide économique.

    La mort sans explosion
    Ne cadre pas très bien
    Avecque les raisons
    Des grands et leur desseins.

    Mon corps reste dans l’ombre,
    Cela vaut mieux ainsi :
    Je préfère la tombe
    Tranquille de l’oubli

    Que d'être tourmenté,
    Acteur involontaire
    Et pantin rapiécé
    Aux mains de la colère.

    Que le vautour dédaigne
    Ma viande par trop maigre
    Et de mon coeur qui saigne
    Le reste de vinaigre !
#+END_VERSE
#+END_CENTER

* Ire honnie

#+BEGIN_CENTER
#+BEGIN_VERSE
    La plume d’oie n’est pas pour les vilains :
    Déposez tout et montrez-moi vos mains !

    Pour bien écrire, il faut être archiduc,
    Bien se poudrer, porter haut la perruque.

    L’autruche ? Non ! C’est par trop provincial ;
    Le merle sent son verbe provençal ;

    Des gants de soie, des plumes de perruche
    Sont conseillées pour ne pas être cruche.

    Nous décidons, je suis roi de ce fief,
    De ce qui est, ou trop court ou trop bref,

    De ce qui est, et de ce qui n’est pas,
    Ce qui se peut, ce qui ne se peut pas,

    Et que jamais le mot félicité
    Ne peut rimer avec facilité.

    Nous décidons que nous nous savonnons
    Chaque matin des plus savants savons,

    Qu’il faut crouler sous des tonnes de livres
    Pour découvrir la clef des sources vives,

    Que nous craignons les ombres du passé,
    Qu'à leur fraîcheur, on ne peut somnoler.

    Les lisons-nous ? Nenni, nous psalmodions ;
    Je n’ai pas dit que nous les comprenions !

    Les écrits saints, nul ne peut les comprendre,
    Mais on peut bien les citer les apprendre

    Par coeur bien sûr, oui et surtout sans coeur
    Où l’on s’expose aux critiques rageurs.

    De la raison, mais nue, sans intuition
    Car l’oeil se brouille au fil des émotions !

    Nous exigeons des fauteuils sans coussins :
    Ils siéront mieux à nos pompeux bassins !

    Que chaque siège alentour soit cilice :
    De la douleur, nous en ferons un vice !

    Nous placardons que l’exécrable masse
    Naît sale et moche, ignoble et dégueulasse

    Et leur prenons le noble parchemin :
    Leurs mains sont mieux à nous tisser le lin,

    Tandis que nous, les purs aristocrates,
    Nous décrétons, du haut de nos savates,

    Que nous tenons l’unique vérité :
    Ils ont tout faux, nous sommes dans le vrai.

    Nous proclamons la vérité unique :
    Elle est frigide et porte la tunique.

    C’est là beau dogme, il reste à découvrir
    Comment il marche et comment s’en servir.

    Mais nous saurons, car nous nous savonnons
    Chaque matin des plus savants savons.
#+END_VERSE
#+END_CENTER

* Halles et gorilles

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les pourris n’ont pas de frontière
    Mais certains sont plus abordables
    On se paie le pamphlet d’hier
    Si demain se fait moins aimable

    C’est plus facile d'écraser
    Pour impressionner les gonzesses
    Une cause téléphonée
    Sans risquer ses augustes fesses

    Plus facile de ricaner
    D’un très petit que d’un trop grand
    Morale de cour de récré
    Pour les petits et grands enfants

    Osez ! Mais sans risquer de mais !
    Soyez engagés de l’orteil !
    Oubliez que tant d'êtres veillent
    Pliant sous le poids des abcès

    Tous ces gosses de mal-culture
    Ce n’est rien c’est de la musique
    De tous les temps la pourriture
    Donne à l’humanité sa trique

    Quand on n’ose pas ... on la ferme
    C’est là la moindre des décences
    La partialité ne renferme
    Que les germes de l’inconscience

    Progresser ? Non mais quelle idée !
    Chacun pour soi c’est beaucoup mieux !
    Soyons animaux en journée
    Et pâles cocus dans le pieu

    N’y pensez plus aux vrais problèmes !
    Vous ne sauriez pas les résoudre !
    Rien que d’y penser vous rend blème
    C’est plus facile d’en découdre

    Engueulez-vous pour des salades !
    Ca fera bien monter le prix !
    Puis critiquez le mec malade
    Qui spéculerait sur le riz !

    Gloire aux victimes désignées !
    Et gloire à la stupidité !
    Si ca rentre ... en bourse j’achète
    Avec ou sans la vinaigrette

    Car ce sont des valeurs très sûres
    Tout en étant des plus rentables
    De condamner d’autres luxures
    Tout en préservant son étable

    Soyez grossier c’est très tendance
    Et oubliez le poids des siècles
    Ces monstres de bibliothèques
    Qui vous pèsent trop sur la panse

    Confondez tout coton et laine
    C’est mieux pour les pelotes tendres
    Plus ça s’emmêle et plus ça rentre
    Comme me disait frère Eugène

    Qui était un fier polisson
    Souple mais très droit dans ses bottes
    Le genre à aimer le cresson
    En l’agrémentant de carotte

    Mais qui n’aurait jamais osé
    Abattre un tigre sans ses griffes
    Vendre cher sa publicité
    De ses scandales maladifs
#+END_VERSE
#+END_CENTER

* Carrefour en X

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le carrefour en X, c’est un peu en contrebas
    Du carrefour en croix.
    C’est le coin des trafiquants d’amour,
    La scène
    Obscène
    Où l’on parodie
    Le paradis.

    Et nos deux héros
    De valeur économique proche de zéro
    N’ont rien trouvé de mieux à y faire que l’amour.
    Car pour faire l’amour, il vaut mieux être deux.
    Du moins c’est nettement mieux quand on est deux.

    Elle,
    Elle vend son corps,
    Son ultime et plus précieux trésor.
    Pourquoi ? Pour se nourrir, elle
    Ou bien les gosses non déclarés
    Que son ex-prince charmant lui a laissé,
    Ou encore pour éviter la piqûre d’un scorpion affamé,
    Ou peut-être juste parce que son coeur déborde,
    Allez savoir ! Peu importe.

    Lui,
    Il est peut-être là pour oublier sa poupée en peluche,
    Ou peut-être est-il l’infortuné mari
    D’une de ces autruches
    Qui n'épousent que le pognon
    Et n’arrivent à jouir qu’en se baignant dans la gloire
    Et le pouvoir ;
    Alors autant cette fille aux mille noms
    Qui, quoi qu’on en dise, a plus d’honneur
    Et lui laisse moins d’aigreur
    Que sa perruche.
    Allez savoir ! Peu importe.

    Demain, ils auront sûrement oublié
    Que le temps d’un vertige passager
    Ils se sont évadé,
    Carrefour des paumés.

    En attendant, ils s’envolent dans la lumière,
    A cent lieues au-dessus de l’humaine misère ;
    N’arrêtons surtout pas leur exploit éthéré,
    Laissons les gerbes de leurs âmes fleurir sur le pavé,
    Carrefour des paumés.

    Passant, quand tu laisses traîner tes yeux
    Parmi les lupanars dorés,
    Quand tu les laisses rouler comme des billes de billard
    Aux abords
    Des ports
    Blafards,
    Des bars à fric et des trottoirs visqueux
    Où s’englue toute trace d’humanité,

    Avant de condamner ces hôtels fluorés
    Et ces maisons de passage
    Qui n’ont plus d'âge,
    Avant de vomir leurs désirs sulfureux
    Pour mieux oublier que tu les as avalé
    Ne fut-ce qu’un instant,

    Avant de jeter l’anathème en masse
    Sur les liasses
    De ponts et d’impasses
    Et des étals où l’on vend
    La luxure au comptant,
    N’oublie pas qu’ils sont peut-être là tous les deux,
    Au milieu des baiseurs parvenant à s’aimer,
    Carrefour des paumés.
#+END_VERSE
#+END_CENTER

* Entre deux eaux

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’athée fanatisé hurlera au mystique
    Le religieux zélé pensera l’hérétique
    Les sectes de tout poil me traiteront de fou

    Mais je continuerai à ricaner de rage

    Pour la gauche bornée suppôt capitaliste
    Pour le banquier aigri racaille communiste
    En bref idéaliste adepte des bijoux

    Mais je continuerai à ricaner de rage
    En voyant ces moutons accrochés aux pendules

    Vivre entre pour et contre en véritable artiste
    Implique les regards de travers des gens bien
    Vous savez ceux qui ont tous le même parfum

    Mais je continuerai à ricaner de rage
    En voyant ces moutons accrochés aux pendules
    Si le cordage casse attention au pelage

    Ce n'était pas une ode à tout les extrémistes
    Je n’insisterai pas sur ces doux voyageurs
    Ces poètes rêveurs dont on brise le coeur

    Mais je continuerai à ricaner de rage
    En voyant ces moutons accrochés aux pendules
    Si le cordage casse attention au pelage
    Vous risquez d’avoir l’air encor plus ridicules
#+END_VERSE
#+END_CENTER

* Cinq minutes

#+BEGIN_CENTER
#+BEGIN_VERSE
    La ville s’illumine. Un soir peut commencer.
    L’air transporte un parfum, comme un goût de réglisse.
    Les bureaux désertés, les comptoirs se garnissent
    De cols plus détendus et de jupons fripés.

    Il reste cinq minutes
    Mais nul n’a remarqué :
    Dans le ciel une étoile
    Semble nous contempler.

    L'école ouvre la vanne aux flots dépenaillés.
    Les enfants s’enfuient loin des grilles, des tutelles,
    Vers cette liberté dont ils sentent l’appel.
    Dans leur tête un repas, un jeu, une télé.

    Quatre minutes encore.
    Aucun n’a deviné.
    Dans le ciel une étoile
    Paraît avoir bougé.

    Décor, quartier pourri. Un homme est terrassé ;
    Les cents carillonant font office de glas.
    Autre rue, un viol et bientôt un trépas,
    Dernières victimes d’un monde carnassier.

    Il reste trois minutes,
    Assez pour expirer.
    L'étoile dans le ciel
    Se laisse dériver.

    Le commerçant s’endort au creux de son sommier
    Tandis que dans le port s’allument les néons,
    Phares des vieux pêcheurs qui sentent le poisson.
    L’aguicheuse secoue ses reins ensommeillés.

    Encore deux minutes
    Et tout aura cessé.
    L'étoile dans le ciel,
    C’est sûr, elle a enflé.

    Moi, je prends l’ascenceur avec la fille enceinte
    Et pense à cette vie qui ne sera jamais.
    Mon chat là-haut m’attend devant son bol de lait.
    Soudain le noir. Toutes les lampes sont éteintes.

    Pas grave : une minute
    Et tout va s'éclairer.
    Notre filante étoile
    Commence à bourdonner.

    Le missile dehors doit percer l’atmosphère,
    Premier des canassons porteurs d’apocalypse.
    Je suis chanceux, je ne verrai donc pas l'éclipse
    Ni le raz-de-marée de feu et de poussière.

    Plus ri
#+END_VERSE
#+END_CENTER

* Futur proche

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je les vois comme je vous vois
    Je suis à la fois ici et là-bas
    2050 2060 2070

    Peu importe la date exacte
    De la rupture du pacte
    Disons juste que plus rien ne pousse
    Ils sont morts
    Tous
    Ils se sont mutuellement étouffés
    Plus aucune trace d’humanité
    Dans ceux qui bougent encore
    Leur carapace a été génétiquement renforcée
    Au détriment d’un crâne plus épais
    Les savants n’ont même pas dû trop forcer
    Sur les greffes de vache à lait

    Je suis à la fois ici et là-bas
    Je les vois comme je vous vois
    2040 2050 2060

    Ils se vautrent
    Ils se marchent les uns sur les autres
    Tout en maudissant leurs parents
    De les avoir balancé d’un coup de pied au derrière
    Dans cet égoût puant
    C’est vrai que ca ne sent pas la cerise
    Et qu’on leur avais promis la lumière
    Ca ne les empêche pas d’engendrer à leur tour la bêtise
    Ils se montent les uns sur les autres
    A coup de trique au derrière
    On aurait même aperçu des hommes enceintes
    Générateurs d’apocalypse
    Ils répandent leurs gènes et leur sang
    A tous vents
    Comme on sort les poubelles le samedi
    Il y aura bien un gosse sur cent
    Qui survivra dans cette fosse "sceptique"
    Optimisme délirant
    Sûrement les vapeurs toxiques des usines chimiques
    Cà donne des hallucinations
    A la longue
    On voit des petits martiens fluorescents
    Pourtant il n’y a plus de centrale les dernières
    Ont explosé récemment

    Je les vois comme je vous vois
    Je suis à la fois ici et là-bas
    2030 2040 2050

    C’est la bousculade
    Aucune pensée cohérente ne s'échappe du chaos
    Comme dans les supermarchés quand il y a un incendie
    C’est la tornade
    Le chaos
    Ils vont tous mourir parce qu’ils se bousculent à la sortie
    L’idée de réfléchir ne leur traverse même pas l’esprit
    D’ailleurs ce mot l’académie l’a supprimé
    Il rapportait moins que la médiocrité
    Plus personne ne votait pour lui
    Plus personne n’en comprenait le sens
    D’ailleurs quelle importance

    Je suis à la fois ici et là-bas
    Je les vois comme je vous vois
    2020 2030 2040

    Le processus a déjà commencé
    Regardez autour de vous
    On en voit déjà qui grimpent dans les arbres
    Ou à défaut dans les ascenceurs
    Il ne faut déjà plus trop compter sur les élévateurs
    S’ils sont trop spirituels ils se lézardent

    Je les vois comme je vous vois
    Je suis à la fois ici et là-bas
    2010 2020 2030

    C’est là c’est ici que les avenirs se séparent
    Tout comme hier tout comme aujourd’hui tout comme demain
    Et nous sommes tous responsables
    De cette multitude d’incertain
    Ce monde ne permet l’innocence
    Que dans l’ignorance et l’inconscience
    Responsables ceux qui le voient et ne le vivent pas
    Responsables ceux qui le vivent et ne l'écrivent pas
    Responsables ceux qui l'écrivent et le ne le crient pas
    Mais le crier à qui mais le crier à quoi

    2000 2010 2020

    Au train où ça va on fonce droit au mur
    La fuite en avant ou plutôt
    La fuite vers le haut
    Des immeubles qui grattent l’azur
    Même que ça ne le fait pas rire l’azur
    Et les immeubles sont de plus en plus haut
    Normal le niveau
    De la boue monte sans cesse
    Glauque et épaisse
    C’est pour ça qu’on construit des ascenceurs en marbre
    En fait c’est un ersatz de béton peint en rose
    Mais personne ne s’en rend compte donc c’est du marbre
    Les jardins suspendus aux manettes il faut bien qu’on les arrose
    Oui tout en haut les manettes tout en haut et en bois
    Cà évite à ceux qui les manipulent
    De voir le bordel qu’ils flanquent en bas
    Dans les égoûts qui pullulent
    Et puis au milieu la caste des autruches
    La ruche des autruches et des cruches
    Très chère si votre caquetage vaut votre plumage
    Moi je me barre direct retrouver les poules d’eau
    Et comme je me sens d’humeur volage
    Je vous laisse terminer ce texte qui prend l’eau
#+END_VERSE
#+END_CENTER

* Vue de l'extérieur

Ai mis en panne en orbite proche d'une planète étrange. Les indigènes y
sont le vestige d'une civilisation très ancienne, du temps où l'humanité
n'était encore qu'un enfant capricieux et cruel. Leur immaturité dure
toute leur vie et ils semblent ne jamais parvenir à placer leur propre
ambition au sein d'une vision commune. Ce qui rend leur société
totalement déséquilibrée et instable, secouée régulièrement par des
éruptions effroyables de violence. Ils ne connaissent, visiblement pas
d'autre moyen de canaliser leur énergie. Pour preuve, plutôt que de
réguler naturellement leur nombre en fonction du nombre moyen d'enfants,
ils font preuve d'un égoïsme génétique effrayant qui les amène
rapidement en surpopulation. Ce qui amène inévitablement les problèmes
que vous savez : pollution énorme, manque d'espace, consommation des
ressources naturelles à une allure effrayante, agressivité qui les amène
tôt ou tard à des guerres de plus en plus sanglantes. Ils sont juste
capables de retarder les explosions en étouffant toute idée créative
dans une casserole à pression. N'en sortent que des légumes cuits à la
vapeur, fades et dénaturés. Ainsi, tout individu tentant de s'extirper
du carcan unidimensionnel de leur échelle de valeur ou de la bipolarité
simpliste de leur système politique se voit immédiatement aliéné par la
société et rentre bien vite dans le rang. D'ailleurs, même s'il tentait
vainement de continuer sur cette voie exténuante, le bruit de fond
abrutissant d'une litanie reprise en écho par la masse bourdonnante
aurait vite fait d'étouffer sa voix. Bien entendu, pris séparément tous
les arguments fallacieux de ce brouhaha pourraient être anéantis, mais
le nombre finit par l'emporter. Pour la même raison, vous imaginez bien
que tout ce qui constitue nuance ou contexte est soigneusement filtré et
manipulé, que tout ce qui constitue accès d'imagination est
soigneusement bridé. On évite ainsi tout déraillement intempestif du
train-train de la déesse Inertie. Leur société est morcelée en clans
qui, au lieu d'essayer de combiner les meilleurs avantages de leurs
théories respectives, gaspillent leur énergie à dénigrer le voisin et à
ériger leur propre idéologie en dogme. Leur système de répartition des
ressources est archaïque et notoirement instable, même s'il leur est
officieusement interdit d'en parler : l'amalgame avec d'anciennes
dictatures est alors mis en branle, mais ce n'est qu'un cas particulier
de la technique d'aliénation dont j'ai parlé plus haut. La balance des
revenus et des dépenses est conçue de sorte que la majorité des
habitants puisse juste passer la tête hors de l'eau. A chaque étage
social, les besoins sont crées pour s'aligner sur les moyens financiers,
par esprit d'imitation ou par menace d'exclusion. Ils sont donc
condamnés à surnager. Vous voyez que tout est programmé pour étouffer
toute imagination, comme les structures pyramidales ou sont prises les
décisions par exemple. Les frottements y sont tels qu'aucune décision
n'est jamais prise, a moins d'y aller très fort sur la dose de
lubrifiant. Ils ont instauré un culte de la laideur, la Médiocratie,
pour les aider à oublier que leur environnement est suffocant et
déshumanisé. Les abreuvoirs de la consommation leurs servent de
soporifiques en cas de poussée insupportable de lucidité. L'eau froide y
est proscrite et remplacée par des distributeurs automatique d'espoir en
pilules. Ils ont élevé tellement de temples au dieu du commerce qu'ils
ont fini par croire que le bonheur pouvait se chiffrer, et que rien ne
peut exister hors de l'argent. Les diminutions de budget de l'éducation
permettent non seulement d'alimenter les importants détournements de
fonds dont la structure a besoin pour fonctionner, mais pompe également
quelques bouffées supplémentaires d'oxygène aux velléités de la pensée.
Les voleurs ne se cachent plus dans les bois mais derrière des réseaux
de lois si denses, si chaotiques, si complexe et, pour tout dire, si
illogiques que plus personne ne s'y retrouve. Ils votent à intervalles
réguliers pour des gens qu'ils ne connaissent pas, ce qui leur évite au
moins de trop s'inquiéter pour l'avenir. Vous l'aurez compris, afin
d'éviter tout risque de contamination, je recommande la mise en
quarantaine de cet astre occupé par des barbares. Aucun vaisseau ne
devrait s'en approcher, et encore moins y atterir avant que ne s'y
développe une civilisation digne de ce nom.

Capitaine Endymion, livre de bord de la goélette d'exploration Mimosa,
en croisière aux abords de Proxima Centauri.

* Stèle

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ton âge affichait dix-sept ans
    Beaucoup trop jeune pour mourir
    L'âge d’aller cueillir aux champs
    La fleur qu’on appelle sourire
    Tu n’auras jamais dix-huit ans :
    Tu es mort pour un baladeur
    Vingt-cinq euros le prix du sang
    Sur le marché noir de l’horreur
    L’amour t’invitait au banquet
    Tu l’attendais dans cette gare
    Mais ils t’ont saigné sur le quai
    Morceau de viande à l’abattoir
    Aucun des témoins n’a bougé
    De peur de s’avancer tout seul
    Lorsqu’elle est enfin arrivée
    Rendant son coeur sur ton linceul
    Ont-ils voilé leurs yeux de rage
    En réalisant le carnage ?
    Tu es mort parce que l'Humain a abdiqué devant les fauves
    La société désagrégée a beau s’embaumer de guimauve
    La merde qu’elle a dans les yeux se nourrit d’ignorance crasse
    La porte est ouverte aux tyrans aux meutes de la pestilence
    A dix siècles d’obscurantisme aux amputés de la conscience
    Les peuples-rois n’existent plus : la masse-esclave la remplace
    Vingt-cinq euros dissimulé dans un journal
    Après le pain, les jeux, matchs truqués et dopage
    Magouilles corruption et tout le saint-tapage
    Tu vois tu n’es plus rien qu’un fait divers banal
    Qu’un assassin t'éventre au milieu d’une foule
    Prostrée paralysée qui ne réagit pas
    Ce n’est rien c’est normal et puis la presse roule
    Comme une girouette au gré des opéas
    Tout le monde s’en fout Tout le monde Pas moi
    Qui grave quelques pleurs sur ton pâle trépas
    Tu ne sauras plus rien de ces minables guerres
    De ce mal dominant qui gangrène la terre
    De ces usurpateurs qui souillent le nom Homme
    Dans la fiente hormonale et le crottin chimique
    De ce gris éternel que partout on bétonne
    De la Stupidité au col barré de fric
    Pourtant tu voulais vivre et tu avais raison
    C’est pour toi que j'écris ce calligramme horrible
    Ce symbole trop vif de déshumanité
    Pour toi et pour ces fous qui n’ont d’autre ambition
    Que d’enfouir leur angoisse avec ton cri terrible
    Pour tous ces névrosés tentés par le léthé
    Que ce poignard de Damoclès leur rappelle
    De regarder toujours plus haut vers le ciel
    Que tout seuls ils n’arriveront à rien
    C’est ensemble que l’on construit demain
    En disant Non à cette barbarie
    Intolérable et à l’hypocrisie
    Car la Vie se construit tous les jours
    Que la pointe de ce discours
    Réveille ceux qui somnolent
    Le nez planté au sol
    Yeux bouchés aussi
    En leur disant :
    "Tes enfants !
    Penses-y
    !"
#+END_VERSE
#+END_CENTER

* Un printemps sans corbeaux

#+BEGIN_CENTER
#+BEGIN_VERSE
    Vu que la bête en nous a beaucoup a apprendre,
    Vu qu’il est des printemps qui se font trop attendre,
    Vu que le marchand règne, aidé par l’alchimiste
    Qui lui forge son or dans sa cuve sinistre ;

    Vu que le prophète pactise avec le diable
    Pour séparer les peuples d’un odieux vocable
    Et tacher de carmin l’agneau pur de l'étable ;

    Vu que l'écriture n’est plus qu’enluminure
    Cautionnant le meurtre des victimes impures,
    Vu que chaque lettrine allume un beau bûcher
    De son encre de feu sur parchemin glacé,

    Vu que le paradis se vend au suicidaire
    Qui réduit en partant d’autres corps en poussière
    - Hé oui, l'éternité coûte moins qu’un salaire - ;

    Vu que la force aveugle a partout ses entrées,
    Que la démocratie n’est qu'écran de fumée
    Où dansent des valets dont le touffu verbage
    Mendie le maigre pouvoir qui leur sert de gage ;

    Vu que l’esprit de clan l’emporte sur l’esprit,
    Que l’instinct dynastique excite l’appétit
    Des nombrils suitant leur égoïsme abruti ;

    Vu que la presse ment par savante omition,
    Qu’elle a pour mécène la manipulation,
    Qu’il y a des larmes de luxe et de lumière
    Et des larmes sombres sans valeur financière

    Non vraiment je ne veux plus lire les journaux
    Avant que l’on me donne un printemps sans corbeaux.
#+END_VERSE
#+END_CENTER

* Le pouvoir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Méprisable drogue des esprits malfaisants,
    Pouvoir, sombre pouvoir, ta sombre odeur m'écoeure !
    Cette odeur de sexe dégoulinant d’argent
    Qui englue sur ta langue - ignoble puanteur ! -

    Des amoncellements de mouches et de vers,
    Cette odeur te trahit comme un mauvais alcool !
    Exécrable alcool qui jamais ne désaltère,
    Ecris la musique, la danse, les paroles
    De ton mauvais ballet. Je refuse le rôle.

    Trouve un autre dupe pour téter tes mamelles,
    Trouve un autre entonnoir espérant quelque gloire ;
    Il sera bien décu, lorsque de tes mamelles
    Il ne verra sortir qu’un poison sans mémoire
    Et puis quelques statues, vite badigonnées
    Par les pigeons vengeurs des âmes opprimées.

    Alors il saura que la foule courtisane
    S’accouple avec le trône et non avec le roi
    Et il regrettera les franches paysannes
    Dont les faveurs sans fard rosissent le minois.

    Entre deux cauchemars, deux hallucinations,
    Il verra ses sujets s’incliner de terreur
    - De terreur, je dis bien, et non d’admiration -
    Sous l'épée, seul pilier d’un palais sans chaleur.

    Oui, il sera déçu. Mais il continuera
    Car le poignard en sang que l’on laisse sécher
    Egorge le maître qui délaisse sa loi.
    Il sera déçu mais n’aura pas d’autre choix
    Que le servir encore et toujours l’abreuver
    Dans l’enfer des ses propres chaînes prisonnier.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

