
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Aubes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Hibou

#+BEGIN_CENTER
#+BEGIN_VERSE
    Juste au-dessous du ciel à deux pas des nuages
    Deux doigts noués de peur de se perdre à jamais
    Un sanglot échappé précurseur d’un orage
    Roule comme un torrent sur un tambour muet

    Alarmé par le flot du silence maussade
    Un oiseau antivol gardien de leur bonheur
    Siffle et du nid d’en face un pinson piailleur
    Leur offre une tournée au bar des sérénades

    Bientôt toute la troupe ailée couvre le bruit
    Des soupirs exaltés confiés aux draps de lin
    Et le carillon clair du clocher attendri
    Qui sonne les demies de leurs alexandrins

    Mais voilà le tonnerre en écho à leurs cris
    La foudre se détend dans un vase de soie
    Et le crépitement de la pluie sur le toit
    S'échoue sur la douceur calfeutrée de l’abri

    Ca et là un éclair dévoile la sueur
    Et les ruisseaux bleutés qui caressent les vitres
    L'étuve claire-obscure inonde avec vigueur
    La mansarde imprégnée de frissons électriques

    Ainsi passe la nuit le déluge s’apaise
    Vient la fraîche heure étrange où l’on peut contempler
    Le soleil se lever sous un ciel étoilé
    Où un timbre joyeux enveloppe la braise

    Bientôt toute la gent ailée couvre le bruit
    Des soupirs extasiés confiés au creux des reins
    Et le carillon clair des rires attendris
    Qui sonnent les demies de leurs alexandrins
#+END_VERSE
#+END_CENTER

* Gazelle

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tes seins dodus épanouis tes yeux de jade inondé d’or
    Bercent mes peurs calment mes joies dans une aubade inondée d’or

    Ne cesse jamais de rêver parmi les candides fragrances
    Les cieux aussi se sont voilés couvrant Grenade assiégée d’or

    Le sable lui-même a pleuré près d’une atlantide en errance
    Il s’est caché dans l’ombre fraîche au-dessous d’une arcade d’or

    C'était avant, longtemps avant, ce monde obscur vide de sens
    Il a depuis doré ta peau Shéhérazade teintée d’or

    Sais-tu que tes lèvres rubis océanide délivrance
    Ont le goût poivré du rivage où la muscade enlace l’or ?

    C’est l’amour qui tient la baguette et qui décide des cadences
    Ou frénétique ou apaisée satin sur sade arrosé d’or

    C’est une injection d'émotions une eau limpide qui s'élance
    Une prise de sentiments une cascade étoilée d’or

    Lorsque le soir étend sur toi une rougeur - timide avance -
    Je vois ton duvet frissonner et ton oeillade incrustée d’or

    A la faveur des alizés nous consommons d’avides danses
    Frôler c’est déjà voyager loin des rondes pailletées d’or
#+END_VERSE
#+END_CENTER

* Allégresse

#+BEGIN_CENTER
#+BEGIN_VERSE
    S’il se devait être un pari
    Je l’ai gagné au tapis vert
    De ton regard qui m’a souri
    Autant à l’endroit qu'à l’envers
    Dame passion carte mystère
    Roulette des jeux étourdis

    S’il se devait être une brise
    C’est le cyclone qui scintille
    Dans ces iris fous qui s’irisent
    Autour de tes sombres pupilles
    Comme une éclosion en furie
    Des flots de fleurs qui vaporisent

    S’il ne devait être qu’un songe
    Que s’envolent les gratte-ciels
    Dedans les moiteurs que prolongent
    Les matins qui montent au ciel
    Dans une brume sensuelle
    Il nous aura servi d'éponge

    S’il ne devait être qu’un fleuve
    A la fois calme et tourmenté
    Où les soleils souvent s’abreuvent
    Et viennent parfois y plonger
    Dauphins luisants des lacs d'été
    C’est celui de tes yeux qui pleuvent

    S’il se devait être une étoile
    Capable d'étirer le temps
    Le dilater comme un métal
    Forger un zodiaque d’argent
    Dans la fournaise d’un instant
    Elle aura brillé sous ton voile

    S’il ne devait être qu’une heure
    En croisière sur les nuages
    Laissant en aval les clameurs
    Pour leur préférer les orages
    Arborescence aux nuits sauvages
    Je l’aurai passée sur ton coeur
#+END_VERSE
#+END_CENTER

* Toison d'or

#+BEGIN_CENTER
#+BEGIN_VERSE
    Des pincées de cils vénitiens couronnent ses yeux solaires
    Deux lacs diamantés brillant de fièvre
    Vibrante invitation vers les gouffres vertigineux du mystère
    Vers les soupirs affamés qui hantent ses lèvres
    C’est comme l'élixir de gourmandise d’un chaton que l’on sèvre
    Sur ses lèvres le baiser se pâme
    Puis s’enflamme
    Puis les cheveux explosent en cascades sur son cou gorgé de sève
    Un parfum de désir s'élève
    Depuis la gorge profonde de ses seins
    Attirance de satin
    Vers ces collines pulpeuses parcourues d’avalanches de frissons
    Depuis la vallée pelotonnée jusqu’au fard des tétons
    Qui étalent leurs morsure sanguine sur la neige
    Quels doux pièges
    Que ces grenades de balcon au bord de l’explosion
    Ne pas en oublier la caresse des embruns
    Il faut descendre
    Boucler la boucle vers la source ultime le ventre
    Tendre naissance de l’univers
    Et ces promontoires galbés et cambrés en offrande
    Territoires ouverts
    Alors qu’elle me griffe le coeur en fusion de ses glaives
    Lames effilées d’un appel haletant
    Ruisselant dans la jungle primitive
    Y joindre son confluent
    Plonger dans l’abîme de cette plaie gourmande
    Dont la moindre lèvre salive
    Fendre en deux à coups de harpons les blessures brûlantes
    De nos consciences vascillantes
    Eperonner jusqu'à la garde ce canyon de chair
    Qui m’enserre
    Comme pour mieux me traire
    Fertiliser la toison d’or d’un labour sans trève
    Vibrer en phase dans l’extase alanguie d’un même rêve
    Jusqu’aux petites heures des tremblements de chair
    Où le bonheur s’achève
#+END_VERSE
#+END_CENTER

* Les plus belles lettres d'amour

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les plus belles lettres d’amour
    Prennent source aux sols désertiques
    Où la soif tord les mots balourds
    Dans les mains du manque anémique,
    Je ne t’en écrirai donc pas
    Mais les murmurerai tout bas.

    Les bijoux les plus éclatants
    Ne sont que le prix ciselé
    Des cages des oiseaux d’argent.
    Ton chant je ne veux marchander,
    Je ne t’en offrirai donc pas
    Mais ferai briller tes yeux las.

    Les étoffes les plus soyeuses
    Etouffent plus qu’elles n’attisent
    Les convoitises amoureuses
    Qui effleurent ta peau exquise,
    Je ne t’en vêtirai donc pas
    Mais réchaufferai ton corps froid.

    Les restaurants nappés de blanc
    Servent des assiettes livides
    Sur des appétits rutilants.
    Nos estomacs, eux, sont avides,
    Y dîner nous n’irons donc pas
    Mais nos lèvres pour seul repas.
#+END_VERSE
#+END_CENTER

* Une première fois

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ça commence, c’est un fleuve
    Qui déborde de son lit
    Il boit la terre neuve
    Des désirs indécis

    Bruit d'étoffes froissées
    Des lacets se délient
    Quelques rires étouffés
    Un instant de magie

    De ses plis délivrée
    La folie les unit
    La folie débridée
    Leur parle sans bruit

    Le satin enivré
    Anime l’arabesque
    L’arabesque enlisée
    Se fond en une fresque

    La dernière caresse
    Vient apaiser leur souffle
    Et alors ils paressent
    Sous le drap qui les camoufle
#+END_VERSE
#+END_CENTER

* Rosier Sauvage

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les roses toujours naissent dans le sang
    Sous un pinceau teint de tons violents
    Leurs pétales flous blessent de leurs charmes
    Les roses toujours s’arrosent de larmes

    Croissent les roseaux à l’orée des femmes
    Baignées des vapeurs du désir cuisant
    Et l’ombre s’embaume et l’aube s’enflamme
    Comme une oriflamme en un four ardent

    La corolle s’offre à la convoitise
    Caressante d’un papillon gourmand
    Le nectar s'écoule en lampées exquises
    S’y trempe la trompe et boit goulûment

    Le rosier s’irise au souffle insistant
    Qui sort haletant de la mousse vierge
    A peine embuée tout autour des berges
    Par l’orfèvrerie du ciel éclatant

    Un or rose luit au fond de l'étang
    Il attire à lui la nage câline
    D’un poisson fièvreux serti de platine
    D’où bourgeonne un fruit d’un rouge arrogant

    S'émousse la faim de vagues d’extase
    Où roule attendrie la chair en fusion
    Vient la frénésie déborde le vase
    Le plaisir ruisselle au dernier frisson
#+END_VERSE
#+END_CENTER

* Vivre c'est tournoyer

#+BEGIN_CENTER
#+BEGIN_VERSE
    Vivre c’est tournoyer les cheveux dans l’ivresse
    Portés par les courants des flots qui nous caressent
    Et se plonger dans leur douceur ;
    C’est se laisser emmener par le vent sauvage
    Plus loin que l’horizon, vers un lointain rivage
    Et s’y ébattre sans pudeur.

    C’est courrir sur la plage étourdis d’oxygène
    Fendre l’air et la vague en happant leur haleine
    Qui libère de toute entrave,
    Prendre en mains le sable, le regarder s’enfuir
    Torréfier chaque grain, infuser un plaisir
    Nuancé d’arômes suaves.

    Admirer les chaloupes qu’esquissent les filles
    Allumer son désir dans leurs yeux qui scintillent
    Sous une lune complaisante
    Se prendre au doux piège de leurs chaudes litières
    Y lover ses mains tendre et sa fière crinière
    Grisé par la chair palpitante.

    Dans l’atmosphère qui condense les secousses
    Faire virevolter corolles et frimousses
    En effeuillant leurs fins pétales ;
    Vibrer sous les battements sourds de la cadence
    S'étourdir et rouler, déphasés dans la transe
    Vers l’extase fondamentale.

    Vivre c’est se soûler d’azurs et de nuages
    C’est serrer ceux qu’on aime à l’abri des orages
    Et de la foudre aléatoire ;
    C’est écouter la pluie crépiter sur le toit
    Et raconter ce sud épargné des frimas
    Où le soleil se couche tard.

    Vivre c’est se nourrir du silence profond
    De l’arbre tourmenté qui porte sur son front
    Les échos d’un lointain passé
    C’est gravir la pente d’un lacet montagneux
    En ne se souciant pas de ce sommet teigneux
    Mais de la beauté du sentier !
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
