
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Théâtre
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Impair actrice

#+BEGIN_CENTER
#+BEGIN_VERSE
    La sultane favorite
    Nue sous la mousse soyeuse
    Tâte l’endroit où palpite
    Son coeur de pierres précieuses

    Elle peut soupirer d’aise
    Dans son bain chaud de midi
    Le roi pris dans ses fadaises
    A appliqué ses édits

    Cette rivale arrogante
    Eut le tort de la défier
    En osant être élégante
    Depuis l’oubli l’a noyée

    Il fallait qu’elle s'éteigne
    Cette trop vive chandelle
    Aujourd’hui les vagues saignent
    Aux abords des dardanelles

    Demain sa langue vorace
    Exigera d’autres têtes
    Le moindre signe d’audace
    Alourdira les requêtes

    En attendant la sultane
    Profite de l’eau fumante
    Et du parfum des gentianes
    De sa fidèle servante

    Nue sous la mousse soyeuse
    Le massage la délasse
    Evaporant l’insidieuse
    Pénombre qui la menace

    « - Tâte l’endroit où palpite
    Ces angoisses qui m'étranglent
    Explore je t’y invite
    Mon improbable triangle

    Ce naufrageur de minois
    A torpillé tant de belles
    Entretiens-le ce sournois
    Et nous vaincrons les rebelles

    Peut-être qu’alors la nuit
    Ces cauchemars de malheur
    Où mon ombre me trahit
    Fuiront vers d’autres sueurs

    La seule drogue apaisante
    Quand on est impératrice
    Est l’eau de vie intrigante
    Qui ruisselle entre ses cuisses

    Le seul calmant efficace
    Est de doser ses caprices
    Et de mêler dans la crasse
    Ses perversions et ses vices

    Vois-tu ma pire frayeur
    Est de croiser mon reflet
    Mon alter ego ma soeur
    Dans les couloirs du palais

    Elle sera j’en suis sûre
    Aussi fourbe aussi perfide
    Que moi Je sens la morsure
    De ses sourires bifides

    Partout je crois que j’entends
    Ses pas de femelle en rut
    De chaque rideau d’argent
    Jaillit un poignard de brute

    C’est pourquoi il faut vider
    De son charme l’alhambra
    Le moindre éclair de beauté
    Pourrait couver un cobra

    Vois-tu ma douce cruelle
    Même la pierre a un coeur
    Bien caché sous la dentelle
    C’est pourquoi la nuit j’ai peur

    - Consolez-vous ma princesse
    Pensez plutôt à ces proies
    Qui paieront pour nos faiblesses
    Ce sera festin de soie

    Quand nos fines incisives
    Entameront la chair crue
    De nos victimes passives
    De nos victimes déchues

    Nous boirons leur vin cuivré
    De pouvoir et d’ambition
    Seul philtre à nous enivrer
    Jusqu’aux hallucinations

    Mais avant tout nous devons
    Essaimer quelques prétextes
    Brûler les champs de limon
    De nos lèvres de silex

    Quand le terrain sera mûr
    Nous inviterons nos pairs
    Dans le temple des murmures
    Au bal masqué des vipères

    Nous pourrons nous agiter
    Dans la ronde des envies
    Sur de fausses vérités
    Sur de vraies hypocrisies

    Si quelqu’une est rayonnante
    De douceur et de tendresse
    Nous dirons qu’elle est pesante
    Surtout au niveau des fesses

    Qu’une autre soit trop tentante
    Nous la dirons insipide
    Au lit fort peu haletante
    Voire carrément frigide

    Nous camouflerons les ruines
    Laissées dans notre sillage
    Derrière la plus minime
    Eraflure de corsage

    Nos critiques parfumées
    Seront d’autant plus tranchantes
    Nous ferons plus de fumée
    Nous serons plus virulentes

    Envers celles qui pratiquent
    Ces arts subtils de harem
    Ces arts si machiavéliques
    Que nous pratiquons nous-mêmes

    Quand nous aurons dévasté
    Tous les jardins alentour
    Nous irons prendre le thé
    Dans d’autre nids de vautours

    Je connais bien des marchés
    Où l’on peut faire ses courses
    De l’omelette au dîner
    Nous viderons quelques bourses

    A nous les juteux supplices
    Et les seringues suaves
    Ne tolérons ces délices
    Qu’en nos enclos à esclaves »

    Ainsi parlaient les complices
    Eperdues dans leurs caresses
    Lorsque la voix d’un ibis
    Lança à nos chasseresses :

    « Elle peut soupirer d’aise
    Cette rivale arrogante
    Cachez-vous dans vos fadaises
    Votre vanité amantes

    Eut le tort de la défier
    Vous pouvez bien vous étreindre
    Je fais partie des brasiers
    Que nul ne pourra éteindre

    Jouissez de vos labours
    Sur votre frêle radeau
    Dans la nuit ombre du jour
    Des bougies brûlent sous l’eau »
#+END_VERSE
#+END_CENTER

* Zap

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est un terrain de football
    Où l’on jouerait du hockey
    Seul point commun le piquet
    L’un aboie l’autre miaule

    Tous jouent un jeu différent
    Avec la même baballe
    Ca court ça crie ça détale
    Sur le petit grand écran

    Coup de marteau sur la vis
    Pour bien enfoncer l'écrou
    Un goal un panier un trou
    Et que l’instinct s’assouvisse

    Dans les dégradants gradins
    Où ils dépensent leurs vies
    A marcher sur les gredins
    Qui leur bloquent le parvis

    Des croche-pieds d’opéra
    Le tout est très sexuel
    Le très précis manuel
    D’un mauvais kama-sutra

    La seule règle est de vaincre
    A coups de barils de vin
    De poudre ou de bars à tringle
    A coups de poignées de mains

    L’arbitre inscrit les enjeux
    Le sifflet joue quitte ou double
    Un temps c’est jaune un temps rouge
    Pour les verts ou pour les bleus

    L’unique but est le score
    Savoir qui est le boulet
    Savoir qui est matador
    Et que leur chaut le filet

    Ni chaud ni froid on s’en doute
    Ils n’iront pas le nier
    Un trou un goal un panier
    Vers la gloire ou la déroute

    J’ai beau surfer sur les chaînes
    De la société cynique
    C’est toujours le même cirque
    Même chevaux même arène

    Ca n’a vraiment aucun sens
    De s'étrangler dans un chiffre
    Renoncer à ses vacances
    Pour être chef d’un sous-fifre

    C’est malgré tout ce qu’ils font
    La course sur une échelle
    Pour être celui ou celle
    Qui repeindra le plafond

    C’est un escalier piégé
    Qui ne donne accès qu’au vide
    L’ambitieux y est jeté
    Par son successeur avide

    Tandis qu’aux premières loges
    On se gausse des candides
    De ces apprentis-sordides
    Qui pensaient devenir doge

    Ils se croient futés en plus
    D'écraser pour surplomber
    Détruire sans se plomber
    Demande assez bien d’astuce

    Beaucoup plus que la voisine
    A ce qu’en dit le voisin
    Qui récure sa cuisine
    Au soir et non au matin

    Alors que lui est rusé
    Un véritable sioux
    Avec ses discours usés
    Et son humour de piou-piou

    Il triche même aux impôts
    Pour racler un peu de fric
    Avant d’aller dire aux flics
    Qu’ils ne font pas leur boulot

    Quand aux élus de ses fesses
    Eux ce sont tous des salauds
    D’aller piquer dans la caisse
    Des honnêtes angelots

    Etre plus pourri que lui
    Un véritable scandale
    Pourtant s’il cherche un appui
    Il baisera leurs sandales

    Il picole il va hurler
    Avec ses copains qui brâment
    Manifeste pour la paix
    Puis rentre battre sa femme

    Si tu leur dis qu’ils sont bêtes
    Ou autre lapalissade
    Ils couvrent ta palissade
    De jurons analphabètes

    Puis brandissant leurs calibres
    Ils répliquent sans attendre
    Qu’ils ont le droit d'être libres
    D’organiser des tournantes

    Dans leurs pur-sang de garage
    Dont ils testent les ressorts
    Il est sans fin ce naufrage
    Mesquin record sur record

    Délaissant ces entrechats
    Je finirai en ermite
    La mitre rongée de mites
    Mais heureux comme un pacha
#+END_VERSE
#+END_CENTER

* Frigo

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ce monde est froid, trop froid, les larmes blondes givrent
    Sur le métal gelé qui pétrifie l’essence.
    Ce monde a peur, trop peur pour écouter ses sens :
    La panique transforme une colombe en tigre.

    Le flou ne mordra pas, il est double naissance,
    Pur magma créatif méprisant l’impossible ;
    Il est le cri, la peur, la joie d’une naissance
    Mais nier l’intuition c’est la rendre impossible.

    Je l’ai vu le néant, oui j’en ai fait mon scrible,
    Tiré tout l’arsenal, bordées de boulets rouges.
    Tous sombrés corps et bien, oubliés dans les douges,
    Saignés dieu sait pourquoi : le mal n’est pas fusible.

    Non c’est un frigidaire à vous limer les ongles
    Sans l'érailler jamais. Il dévore les songes,
    Est sournois, plus que vous, n’essayez même pas

    De le vaincre, il ferait son dîner de vos coups.
    Il n’est ni cette rose aux insensés appas
    Ni la brute stupide ou le cruel filou,

    Mais il tire les fils à chacun de nos pas.
    Qui voudra le contrer rendra son coeur fertile :
    Enfantez, dieu est là, et le mal est stérile.
#+END_VERSE
#+END_CENTER

* Echecs

#+BEGIN_CENTER
#+BEGIN_VERSE
    Trente-deux pièce' en bois sur l'échiquier en marbre
    S'échauffent doucement d’un défi immobile
    Bientôt les deux armées vont courir au massacre
    Pour le plus grand plaisir de leurs maîtres fébriles

    Tandis que les deux Rois se jaugent en silence
    Ecrasés par le poids de leur orgueil stérile
    Au centre du plateau voilà qu’un Pion s’avance
    Anonyme soldat que chaque pas mutile

    Trente-deux pièce' en bois soixante-quatre cases
    Voilà qu’un Pion s’avance et établit ses bases
    Discret et si chétif plus retors qu’on ne croit
    Et seuls les débutants le méprisent parfois

    Il est suivi de près par la Chevalerie
    Si noble de parure et si vile au dessous
    Qui traverse en riant les lignes ennemies
    Pour s’en aller causer à son ami le Fou

    Quand on parle du loup le voici qui arrive
    Et la dague jaillit de l’habit de velours
    Le destrier trahi se cabre de surprise
    Personne n’a bougé pour lui porter secours

    Transpercé par celui qu’il vient d’empoisonner
    Lui qui s’imaginait Roi de tout l'échiquier
    A présent il succombe et maudit l’ironie
    Sous l’oeil intéressé des corbeaux qui l'épient

    Les Reines prévenues exigent de savoir
    Par qui pourquoi comment est mort leur tendre amant
    L’une ne pleure pas l’hippocampe bavard
    L’autre envoie le coupable au coeur de l’autre camp

    Les canons de la Tour ne ratent pas la cible
    Qui titube affaiblie en terrain découvert
    Quel abruti ce Fou se croit-il invincible
    Une seule bordée l’enverra en enfer

    Laissons-leur cet honneur de parler sans détour
    Se battre pour se battre un Fou contre une Tour
    Leur plus grande frayeur c’est qu’on les ressuscite
    Quand ils voient un des Pions s’approcher du rang huit

    Trente-deux comploteurs sur un pays d’ardoise
    Combien en reste-t-il ils sont déjà nombreux
    A s'être fait avoir par une ombre sournoise
    A reposer en paix sur le rebord du jeu

    On retrouve une Reine au pied d’une falaise
    Accident paraît-il ou est-ce de chagrin
    Quelques-uns font semblant de croire à ces fadaises
    Mais le barde de cour chante un autre refrain

    Bientôt la capitale est envahie de hordes
    Un garde s’est vendu il a ouvert les portes
    Dans le palais en feu maculé d'écarlate
    Le piège se referme un Roi tombe c’est mat
#+END_VERSE
#+END_CENTER

* J'ai rêvé d'inhumer ...

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai rêvé d’inhumer la misère inhumaine.
    Un métier épuisant qu’espérer l’impossible :
    L’exalté tapageur est toujours pris pour cible
    Et l’astre du réel vous donne la migraine.

    Depuis toujours la vie est cisaillée au crible
    Des guerres camouflées mais quand la mort s'égrène,
    A-t-on vu un César combattre dans l’arène ?
    La loi de la colère est une armée fusible,

    Un pion sur l'échiquier dans un donjon de verre
    Qu’une main peut faucher par jeu, par distraction,
    Car si les tours d’argent ont changé de prénom
    Elles sèment toujours la poudre de l’hiver.

    Mais bien sûr tout le monde est contre les canons,
    C’est à se demander qui les mène aux frontières,
    Le vent ? Vautours grimés de paix et de lumière,
    Vos becs ensanglantés trahissent vos raisons.

    Il y a entre l’homme et l’animal un gouffre
    Profond mais si étroit qu’un pas peut le franchir.
    Quoique l’on puisse oser, quoique l’on puisse écrire,
    L’or du blé est mêlé à l’or sombre du soufre.

    La mégalomanie oublie que pour détruire,
    Pour éroder les murs de milliers de murmures,
    Pour briser les palais sous les coups des fissures,
    Un peu d’eau ou de sable et de temps peut suffire.

    Quand le conquérant qui pense avoir tout vaincu
    Se tourne vers la glace, il ne voit dans sa veste
    Par deux fois retournée que l’oeil noir de la peste
    Qui a trahi son coeur pour moins de vingt écus

    Et, enroulé autour de son long bras de fer,
    Un serpent charognard fait d’innombrables vers
    Dont l’affreux grouillement l’acclame et l’applaudit :
    Qui veut se croire grand s’entoure de petits.
#+END_VERSE
#+END_CENTER

* Triste monde

#+BEGIN_CENTER
#+BEGIN_VERSE
    Triste monde
    Tu pourris sur place
    Le vent ne souffle plus dans tes plaines
    Les chevaux repus ont renoncé à courir
    Où sont passées tes rengaines
    Et tes rondes
    Et tes sourires

    Triste monde regarde-toi dans la glace
    Tu n’as plus de reflet tu n’es qu’une ombre qui passe
    Les miroirs se déforment comme l’eau des piscines
    Lorsque la vague se mutine
    Le fond houleux te donne la nausée
    Tu préfères sans doute le verre fumé
    Enfumé comme toi qui tombes en poussière

    Dis te rappelles-tu tes chansons claires
    Joyeuses comme l’eau des fontaines
    Et ces temps où les dieux
    Ne se prenaient pas trop au sérieux
    Ces dieux anciens
    Si profondément humains
    Et nous étions presque comme eux
    Presque des dieux

    Triste monde
    L’avenir grave ses lettres creuses dans tes murs
    Ne les vois-tu pas rougeoyer dans la nuit sans lune
    Ne vois-tu pas ce feu d’or et de sang qui fait danser la blessure
    C’est celui de tes entrailles monde d’infortune

    Pauvre de toi tu n’as plus d'âme
    Tu n’oses même plus rêver
    D’ailleurs toutes ces larmes et ces cris de plaisir libérés par les femmes
    En offrande à la vie tous les chants des poètes viennent se fracasser
    Sur tes griffes de verre et de métal
    Qui labourent l’azur et blessent les étoiles

    Monde suicidaire
    Un chiffre une colonne une seule dimension
    Tu t'étouffes dans cet univers
    Que tu as toi-même créé le jour où tu as vendu tes passions
    Au nom d’un compte qui n’avoue pas son nom
    Pauvre néon sans lumière
    Vendre l’aube pour un éclair
#+END_VERSE
#+END_CENTER

* La parole des anges

#+BEGIN_CENTER
#+BEGIN_VERSE
    Arrête de chanter, frère ailé, on leur a
    Donné plus que leur part de cantiques d’amour !
    Le sang est dans leurs yeux qui tache ton velours,
    Chaque larme qui coule est  un nouveau trépas.

    C’est la mort qui suppure et infecte leurs fois
    — La pierre et le bûcher n’ont jamais eu d’humour —
    Et pour mieux protéger ceux qui ne sont pas sourds
    Des murs démesurés cloîtrent ta douce voix.

    Oui, ton encre est un vin et des plus savoureux
    Mais l’atmosphère en bas vomit un fiel haineux
    Or il suffit d’un rien, de microbes infimes,

    Que quelque fou furieux sacrifie en ton nom
    Pour aigrir le tannin des meilleurs millésimes :
    Arrête, Ami, leur sang souille nos édredons !
#+END_VERSE
#+END_CENTER

* Recette relativiste

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ne t’en tiens pas aux vérités
    Quand seuls font rêver les mensonges
    Quand dans mensonge il y a songe
    Ne t’en tiens pas aux vérités
    Quand seuls les songes les prolongent
    Balaient les écrans de fumée
    Ne t’en tiens pas aux vérités
    Quand seuls font rêver les mensonges

    Les vérités sont des menteuses
    Lorsqu’on filtre leurs étincelles
    Dans un dédale de ruelles
    Les vérités sont des menteuses
    Lorsqu’on embrase ou éteind celles
    Trop ou pas assez enjôleuses
    Les vérités sont des menteuses
    Lorsqu’on filtre leur étincelles

    Dans le moule qui vous arrange
    Meuble comme un château de sable
    Au choix des pamphlets des louanges
    Dans le moule qui vous arrange
    Marinez le tout dans des fables
    Puis saupoudrez d’invérifiable
    Dans le moule qui vous arrange
    Meuble comme un château de sable

    Ajoutez-y quelques lentilles
    Quelques loupes sur la poussière
    Pour faire valser la lumière
    Ajoutez-y quelques lentilles
    Des oeils-de-boeuf des jalousies
    Afin de cribler le mystère
    Ajoutez-y quelques lentilles
    Quelques loupes sur la poussière

    La recette est bien plus suave
    Epicée de miroirs convexes
    Et de leurs frères les concaves
    La recette est bien plus suave
    C’est un conclave un peu complexe
    Des alouettes que l’on vexe
    La recette est bien plus suave
    Epicée de miroirs convexes

    Il ne reste qu'à faire cuire
    La pâte lève d’elle-même
    C’est la magie de ce système
    Il ne reste qu'à faire cuire
    La levure c’est le délire
    C’est le moulin à vent suprême
    Il ne reste qu'à faire cuire
    La pâte lève d’elle-même
#+END_VERSE
#+END_CENTER

* Mouvement perpétuel

#+BEGIN_CENTER
#+BEGIN_VERSE
    Très loin dans l’inconnu des pays oubliés,
    Sous un ciel morcelé de plâtre par endroit,
    Un soleil enfiévré chauffe imposant le toit
    D’un balancier pesant retenant prisonnier

    Les peuples aveuglés par la faim et la soie.
    Sur la masse oscillante : apogée, décadence,
    Barbarie, renaissance imposent la cadence
    Sous les impulsions d’or de l'échappement roi.

    Ainsi, de son ressort comprimé, la vengeance
    Se détend tour par tour, dent par dent d’engrenage,
    Libérant lentement son maladif tangage
    Sur l’acier empourpré par son ignoble engeance.

    Des rivières de sang se forment dans l’orage,
    Des aubes arrosées au moulin miroitant
    Dont l’axe teint d’argent remonte, ruisselant,
    Le ressort abreuvé par son propre carnage.
#+END_VERSE
#+END_CENTER

* Mas sûr

#+BEGIN_CENTER
#+BEGIN_VERSE
    Rustique rococo, contour impressionniste
    De l'élancé roman, du polychrome antique,
    Ton pastel renaissance, humilité gothique,
    Réalisme art-déco, arabesques cubistes,
    Voici qu’est ébauchée l'étrange mosaïque.

    C’est une maison creuse et garnie de grillages
    Rouillés jusqu’au trognon d’une pomme véreuse.
    Le chouette tableau s'étend sur trois étages,
    Sans compter le grenier, ses hiboux et ses mages,
    D’où s'échappe en chuintant l’alchimie sulfureuse.

    Leur chant fait fuir la nuit les troupeaux apeurés
    Qui gagnent en tremblant l’antre des habitudes
    Où les yeux dans les yeux pour se réconforter
    Ils oublient la tondeuse et la laine arasée,
    Ils s’oublient dans le somme et dans la multitude.

    Leur vie aussi s’enfuit de l'étable à l’aut’ruche
    De l’ampoule au néon, des télés aux consoles
    De jeu. Mais pour l’amour, pour décoller du sol,
    Ils attendent la panne où le courant trébuche.
    Entourés mais tous seuls, et rien ne les console.

    Leur assemblée vivote au rez de la chaussée
    Dans un petit salon bureau, table et paillasse.
    Les pots de fleurs sont secs, les fauteuils élimés,
    Un mur en nid d’abeille, un vieux tapis rincé,
    La panoplie propice à l’ennui qui se tasse.

    Rien que de très paisible à l’oeil non averti
    Qui ne sait pas que grouille alentour du frigo
    Des légions de cafards entre les berlingots,
    Qui n’entend pas non plus l’insatiable appétit
    Des termites ronger de leurs dents de robots

    Le bois mûr des piliers soutenant les charpentes.
    Les portes, les placards, tout y passe, partout
    La pourriture broie les gonds et les verrous
    Et, sous le verni clair, des griffes d’amarante
    Giclent de l’avenir à travers les écrous.

    Qui veut sortir de là ira vers l’escalier
    Pour au pied d’icelui se retrouver nez à
    Nez avec l’atelier de dame arachnéa
    Où, pour mieux empêcher quiconque de grimper,
    Elle tisse ses lois, brode l’alinéa

    Inique en un réseau quadridimensionnel
    D’inextricables fils tricotés au hasard.
    Nul n’y comprend plus rien et même elle s'égare
    Dans ce dédale abscons. Qu’importe ! L’essentiel
    Est de barrer l’entrée du triste boulevard

    Aux rares pèlerins qui voudraient se risquer
    Au second, au pouvoir et aux folies guerrières.
    L’antichambre est gardée de zélés mercenaires
    Et l’on entend la nuit les serpents se glisser
    Entre les flots luisants des rares réverbères.

    On dit que c’est là-haut que l'âme se révèle
    Et qu’ils furent nombreux à s'égarer dans l’ombre
    Pour avoir recherché l’aurichalque du miel
    Dans le reflet cireux des frêles asphodèles
    Et l'éclat des palais dans de pâles décombres.

    Les sorciers au coeur noir, c’est ainsi qu’on les nomme,
    Se terrent loin d’eux même, évitant les étangs,
    Car l’eau glacée leur lance : « Ô toi qui fus un homme,
    Toi qui pense être roi et avoir conquis Rome,
    Vois ce qu’ont fait de toi hydre et léviathan !

    Ce sont eux les vainqueurs que ta haine nourrit,
    Nichant dans ses doigts secs les oeufs brouillés du drame.
    Trône tant qu’il est temps sur ton tas de débris,
    Ô prince d’un palais où couve l’incendie :
    Qui attise le feu n’obtiendra que des flammes !

    Vois, les rats de tous poils que tu as élevés
    Sortent de leurs égouts les yeux rouges de rage,
    Et pendant que tu ris des hiboux et des mages,
    Croyant être à l’abri derrière un mur d’acier,
    La peste se répand et inonde la cave.

    Aussi profite bien de tes chambres sans air !
    Resserre ton étau sur les peuplades mûres
    Pour la masse et la presse et jette à tes cerbères
    Quelques pépins juteux, qu’ils aient faim d’autres guerres
    Sans que leur désespoir ne piste tes blessures.

    Verse le prix du sang et l'éther sur la braise,
    Lance les boomerangs aux ouragans féroces,
    Scie ta branche, insensé, souffle sur la fournaise,
    Cloisonne pour régner, lézarde, écrase et biaise !
    Crois-tu que l'Essentiel s’achète avec un os ?

    Un jour un citron vert mordra tes plaies fragiles,
    L’acide vérité aux lames innombrables
    Plongera dans ton coeur mesquin, froid et futile,
    Et tu te souviendras qu’aussi cruel fut-il,
    Nul n’a jamais été plus malin que le diable ! »
#+END_VERSE
#+END_CENTER

* Ô déesse meurtrie

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ô déesse meurtrie, sauvage Liberté,

    Pourquoi les laisses-tu te vendre comme esclave ?
    Leurs pièges enfantins n’ont pas pu te leurrer !

    Tu subis, outragée, leurs odieux coups d'étrave,
    Mille fois violée devant ta garde autruche

    Qui t’a prostituée dans sa folle inconscience,
    Bradée au prix plancher des poupées en peluche.

    Et ces usurpateurs qui poussent l’indécence
    Jusqu'à voiler l’horreur de leurs crimes barbares

    Sous la sagesse en pleur de ta robe éventrée,
    Et ton peuple en sursis qui feint de ne rien voir !

    Dix deniers aux félons et te voilà livrée
    A l’appétit sanglant des soudards de la foi.

    Déjà, le ver fleurit entre les épis mûrs
    Qui sèmeront demain les nouveaux champs de croix.

    Le solstice d’hiver justifiera l’armure
    Qui vomira la mort au nom de la colombe

    A l’heure où les puissants se feront politesse
    En discutant du cours de l’or et de la tombe :

    Les mouchoirs parfumés sur les nez des altesses
    Ont de tout temps masqué le dépit des cadavres.

    Eux, ils prendront le thé à l’abri des tueries,
    Ennemis fraternels refugiés dans leur havre

    Pendant que leurs armées d’assassins en furie
    Leur offriront le monde en braves petits chiens.

    Ignoble marchandage, à combien la victime ?
    Et ta peau labourée, ma déesse, à combien ?

    Combien en coûte-t-il d’assister au sublime
    Spectacle du poignard s’enfonçant dans ta chair ?

    Combien pour les Vertus bafouées de ta fille
    Surprise dans le dos par l’ombre des rapières ?

    Combien pour les Vertus de la Démocratie
    Dont la cuisse en lambeau sanglote de frayeur ?

    Les traîtres l’ont droguée, regarde, elle s’endort
    Sur un tapis de cendre annonçant le malheur.

    Les tyrans du passé aux rictus de phosphore
    Sortent de leurs tombeaux aider leurs descendants,

    La haine pond ses oeufs dans le nid de l’amour,
    L’augure à l’oeil dément marmonne entre ses dents :

    « Les temps ne sont plus loin où, au pas des tambours,
    Le triomphe des chars charriera ses charniers !

    Ce sera à nouveau le règne des crapules
    Et du culte exigeant de dame Cruauté.

    Le sacrifice humain répandra ses pustules,
    La loi sera de jungle et ses mains monstrueuses

    Se soûleront sans fin des tortures bestiales
    Et du vin transparent des âmes ambitieuses.

    L’exécution sommaire, en sa pitié filiale,
    Asservira les serfs par la terreur du glaive

    Au seigneur du hameau, tribun de sa tribu,
    Qui connaît bien le poids d’une épée que l’on lève.

    Ce sera à nouveau le règne de l’obus,
    Du châtiment clanique et du négoce obscène !

    Déesse, aie pitié d’eux qui débitent ta jupe :
    Lorsqu’ils tranchent ta jambe et l’exhibent sur scène,

    C’est leur branche qu’ils scient dans ce marché de dupes.
    Ils se verront bientôt lapidés eux aussi,

    Empoisonnés sans doute ou saignés lentement
    Ou foudroyés au lit par leurs anciens amis. »

    Ainsi parla l’augure au timbre chevrotant.
#+END_VERSE
#+END_CENTER

* Fumerolles

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il faut voir la vanité gorgée de panache
    Lècher la flatterie, cette sauce qui tache
    De ses creuses caresses ;
    Et l’arrogant orgueil écraser d’un pas lourd
    Les champs de fleurs sans voir, de son regard balourd,
    Sa plus belle richesse.

    Sentir le bras hagard de la puissance obscure
    Aiguiser son tranchant, renforcer son armure
    Au puit de la misère
    Tandis que revêtu du blanc pur d’une vierge
    Son maître frénétique idolâtre des cierges
    Qui brûlent sans lumière.

    Admirer la main droite de l’hypocrisie
    Aux reflets hypnotiques engourdissant nos vies
    De leur étrange charme
    Alors que la main gauche aiguise son couteau
    Voilé dans les replis de son lâche manteau
    Imperméable aux larmes.

    Essayons de saisir l’argent aux biais fluides ;
    Ses rivières, filles fuyant le sol aride
    Des doigts frêles ou tremblants
    Mais qui se jettent, guillerettes, dans les draps
    Des fleuves verdâtres qui couvent dans leurs bras
    Le crime bouillonant.

    Lisons ces journaux aux canines aiguisées
    Où regorgent les victimes vampirisées
    Etalées à la une.
    Notons ce qui est dit, comptons les cimetières !
    Qu’ils se nourissent de ce qu’ils ont recouvert
    Du sable des lacunes.

    Ecoutons au hasard les barons fades et blêmes,
    Multiples étendards du même diadème
    Qui leur souffle tout bas~:
    " Promettez et bradez à découvert le pain
    Jusqu'à ce que les mirages de votre entrain
    Leur gave l’estomac.''

    Ne nous détournons pas de l’amère fragrance
    Défigurant de sa monstrueuse indécence
    Les beautés qu’elle vend.
    L’enfant, le sein, le coeur : tout est question de prix.
    Les corps déchiquetés s’enfoncent dans la nuit,
    Les âmes dans le vent.

    N’occultons pas la fine poudre artificielle
    Flocons de l’enfer qui déchirent la cervelle
    Lorsqu’ils fondent en verglas ;
    Ni la seringue qui garotte la raison,
    Exigeant tout : honte, démence, soumission
    De l'épave et du glas.

    Regardons sans sciller les plateaux inclinés
    Des balances gémir sous le plomb parfumé
    D’essences théatrales
    Masquant l’odeur du sang dans les labyrinthiques
    Arcanes rigides des grimoires magiques
    Esclaves du scandale.

    Terminons par ces temples aux atours de dentelle
    Abritant des démons avides et cruels
    Repus d’hémoglobine.
    Assis dans le fauteuil moltonné du pouvoir
    Ils enchaînent le vent, étranglent la mémoire
    De leurs griffes mesquines.

    Puis sortons prendre l’air loin de ces fumigènes
    Boursouflés de cendres sulfureuses et malsaines
    Qu’exhalent les cratères
    Profonds de l’inconscient aux versants opposés
    Que nos enfances éparses ont partout modelé
    Et sculpté dans la pierre.
#+END_VERSE
#+END_CENTER

* Démocratie

#+BEGIN_CENTER
#+BEGIN_VERSE
    Démocratie, prends garde
    Tes colonnes grincent sous le poids de tes lois
    Ton fade pouvoir n’est plus qu’une immense farde
    Grignoté par de meutes de rats aux abois

    Démocratie, tu dors
    D’un sommeil abruti peuplé d’un clown hilare
    Tandis que sous ta peau la vermine dévore
    Tes restes de grandeur étouffés dans le noir

    Démocratie, regardes :
    Tu marches sur le sable d’un désert stérile
    Enlève de tes yeux ces mains qui se lézardent
    Est-il déjà trop tard pour tes larmes fertiles ?

    Démocratie, descend
    De ce trône clinquant rongé par les porteurs
    Tu n’es plus qu’un outil dans les mains des puissants
    Imbibée de drogue pour noyer ta rancoeur

    Démocratie, tu croules
    Comme ces vieux châteaux jadis fiers et puissants
    Mais qui s’effondrèrent au premier coup de houle
    Sur les labyrinthes des complots malfaisants

    Démocratie, tu craques
    A chaque coup porté par ton enfant maudit :
    L’embryon glouton d’un Empire bureaucrate
    Lui-même condamné par sa lourde inertie

    Démocratie, tu cries
    Mais c’est sans espoir ta chambre est capitonnée
    Les partis et les clans te cernent de leur grille
    Et d’ici nul n’entend ton râle d’assiégée

    Démocratie, tu meurs
    J’espère que, telle l’oiseau de la légende,
    Afin de nous éviter des siècles d’horreur
    Tu renaîtras, ardente et belle, de tes cendres
#+END_VERSE
#+END_CENTER

* La violence

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle est là, invisible, à l’abri dans son antre,
    Ses griffes effilées calfeutrées sous son ventre.

    Au dehors, c’est la joie.
    Dans l’air un doux murmure
    Berce au son des hautbois
    Les frivoles ramures.
    La nature est heureuse,
    Le pinson est le roi !
    Les chansons mélodieuses
    Couvrent sa grave voix.

    Elle est là, invisible, à l’abri dans son antre,
    Ses griffes effilées calfeutrées sous son ventre.

    Son puissant maître lui a dit :
    " L’heure s’en vient de la pénombre,
    " Ce monde est vieux, est en sursis :
    " Tu peux creuser. Creuse sa tombe !
    " Répands partout tes tentacules,
    " Tes germes et tes mandibules,
    " Et ces fleurs, fruits du crépuscule,
    " Dont on ne distingue que l’ombre.''

    Elle est là, elle creuse, à l’affût dans son antre,
    Ses griffes effilées grattant la terre tendre.

    " Sème au vent clair tes parasites,
    " Ici le limon noir est riche
    " En égoïsme, en haine en friche
    " Dont le vert phosphore crépite.
    " Qu’ils s’incrustent partout,
    " Entre clans, entre époux,
    " Des palais aux égoûts
    " Jusqu’aux anciens murs qui s’effritent.''

    Elle est là, elle creuse, à l’affût dans son antre,
    Ses griffes effilées grattant la terre tendre.

    Les flancs de sa prison
    Remuent sous la pression
    Du sulfureux poison
    De son haleine épaisse.
    Soudain, le feu l’embrase,
    Telle une rouge vase,
    La lave avance et rase,
    L’animal se dépèce.

    Seule vie sur les lieux de la plaine détruite,
    Deux timides pépins d’albâtre et d’hématite.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
