
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Sérénades
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Rome antique

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il va chanter sous son balcon tous les soirs
    Le coeur hanté par ses beaux yeux mandoline
    La nuit minaude en mélodies bleu marine
    La brise est chaude, est-ce son souffle ou l’espoir ?

    Dans la pénombre où la vision s’est offerte
    La nuit maraude et vient lécher de son phare
    Les vagues d’ombre à sa fenêtre entrouverte
    La brise est chaude, est-ce son souffle ou l’espoir ?

    Elle chavire, il ne le sait mais devine
    Qu’un oiseau-lyre enflamme l’or de ses rêves
    Il va chanter pour qu’elle danse et soulève
    Son coeur hanté par ses beaux yeux mandoline

    Valsez velours, ensorcelez son ondine !
    Son enchantée a laissé choir son mouchoir
    Salves d’amour sur ses lèvres purpurines
    Il va chanter sous son balcon tous les soirs

    L’astre maraude en ronronnant comme un loir
    Au garde-flou de ses cheveux mousseline
    La brise est chaude, est-ce son souffle ou l’espoir ?
    La nuit minaude en harmonies bleu marine
#+END_VERSE
#+END_CENTER

* Chopine

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le charmant chuchotis de l’eau
    Contient toutes les voix du monde
    Les fleurs chantent dans les roseaux
    Les cordes de pluie sont fécondes

    Un jour une fée aux doigts fins
    Voyant un ruisseau embusqué
    Sous un saule aux canards laqués
    La franchit de trois bonds coquins

    Le flot en fut si enchanté
    Qu’il lui en chanta trois ronds d’eau
    Amenant sans difficulté
    Toutes les rimes des rondeaux

    De ces frissons aux parfums frais
    Délicatement déposés
    De ces trois sauts si raffinés
    Naquit la valse au teint de lait

    C’est de leur contact sensuel
    De ces trois pieds voluptueux
    Que coulèrent ces airs charnels
    Ces airs qu’on ne danse qu'à deux

    Sous une lune tamisée
    Une pleine lune de coeur
    Croissant romantique embrasé
    A l’abri d’un saule fleureur

    Mais que vois-je ? Un pétale choir
    Au goût de rose et de jasmin
    Un deux trois donne-moi la main
    Que je te rende ton mouchoir

    Parlons de tout parlons de rien
    Des ces boiseries patinées
    La nuit le soir ou le matin
    Je sens le clair de tes pensées

    Livre-moi ces doigts d’alchimiste
    Que je vis dissoudre la haine
    Pour la transformer d’un pleur triste
    En pleur de joie perle sereine

    Tu connais la magie des songes
    Qui prennent corps au cor de brume
    Chacun de tes cils les prolonge
    Chacun de tes yeux les allume

    Tu es ici quand je suis las
    Et c’est cette folle impudence
    Folie sage et dingue à la fois
    Qui fait que je crois en l’errance

    Que je compte les sceaux scellés
    Jouant à deux sur quatre mains
    En trois temps le choeur est commun
    Une brise au ciel étoilé

    Toi moi la vie et le destin
    Pour un quatuor calfeutré
    L'élégance dort sur ton sein
    D’un seul accord l’accompagner

    Comme ces pulsations de basse
    Qui frisent l’excès de vitesse
    Le tournis frôle les audaces
    Sous la caresse de l’ivresse

    C’est le vertige de trois notes
    Si tu tombes je te rattrappe
    Sens-tu ce voyage qui flotte
    Comme échappée de murs opaques

    Comme un billet doux cacheté
    Sur un clavier qui se déroule
    Quand la colombe satinée
    Près du colombage roucoule

    Jazz bleu col blanc sourire d’or
    Aux touches d’ivoire et d'ébène
    Goutte de rosée à babord
    Nacre au soleil d’une sirène
#+END_VERSE
#+END_CENTER

* Envol

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le ruisseau jase avec l’oiselle
    En un flot furieux et frivole
    Et si le lac palpe le ciel
    Il en a perdu la parole

    Oui tous deux toisent les nuages
    Et jonglent sur des filaments
    Tous deux dispersent les mirages
    A la source du firmament

    Mais le ruisseau est un oiseau
    Que le cours tourmenté emporte
    Quand le lac rêve d’un roseau
    Qui vienne frapper à sa porte

    Hélas le lotus bleu est rare
    Le papyrus reste muet
    Pas le moindre remous fluet
    Pour secouer le flot avare

    Car c’est de chant que l’oiseau vole
    Beaucoup plus haut que les nacelles
    Non de la lourdeur de ses ailes
    Tenues aux caprices d'éole

    Le ruisseau et l’oiselle épris
    Que leur importe les sentiers ?
    Les voilà déjà fa mi liés
    A se mi ré dans leurs ré si

    « - Au do do du couchant do ré
    En la c’est moi fa si la mi
    Ôtez bien tôt votre si ré
    Et venez sécher vos soucis

    Viens auprès de moi te coucher
    Que l’eau s'épanche du pichet
    J’ai mis pour mieux nous réchauffer
    Le matelas près des chenets

    - Pour payer ton joli sourire
    Je n’ai que de vaillants bisous
    Foin des bacs chiche du désir
    Dis-moi je te mets la bise où ?

    - Je la préfère au biais vert
    Commence par tâter les chais
    Viens que je te verse le verre
    Qui dans ma robe se cachait

    En la c’est moi fa si la mi
    Que demain je ne sois plus celle
    Qu’au do do daubent les pucelles
    Et poules du même acabit

    Qui demain conteront partout
    Que je n’ai pas eu froid aux jambes
    Qu’importe que leurs langues flambent
    Ma vertu si l’instant fut doux ?

    C’est la honte et non le péché
    Qui les a chassé de l'éden
    Ce qui les a fait trébucher :
    La peur de s’affronter soi-même

    Je suis une partie de nous
    Unique et multiple à la fois
    Passe dans les miens tes genoux
    Nous y retrouverons la foi

    Un autre univers sans rivaux
    Royaume de la mélodie
    Nous laisserons la nostalgie
    Vieux haillons près de la rive eau

    C’est mon désir de dame oiselle
    C’est donc un ordre mon charmant
    Viens nous sertirons d’asphodèles
    La géode du firmament »

    Le soir pose un voile discret
    Sous le duvet des hirondelles
    Qui laissent choir un peu exprès
    La nuit incrustée d'étincelles

    Le briquet ocre un temps vacille
    N’est plus qu’un pourpre liseré
    Sur un divan rose irisé
    Les dix vents posent leur résille

    Mais d’autres étoiles s’allument
    Sous le plafond bas de leur nid
    Ce sont leurs yeux qui se consument
    A se mi ré dans leurs ré si
#+END_VERSE
#+END_CENTER

* Air libertin

#+BEGIN_CENTER
#+BEGIN_VERSE
    Nous sommes de fins matelots
    Ecumeurs de bars et d’amphores ;
    Les salves de nos lourds grelots
    Visent les chaloupes du port.
    Nous allons donc au petit trot,
    Corsaires gorgés de sirop,
    Mélanger à l’eau des maillots
    Les fiers bourgeons de nos sabords.

    Nous passons au large des îles
    Peuplées d’amazones sans coeur
    Et de ces prêtresses stériles
    Adoratrices du vibreur.
    Gloire à la gourmande indocile
    Qui préfère aux plaisirs à pile
    L’affut de nos canons sans fil
    Embouchés sans fausse pudeur !

    Et lorsqu’on croise la maison
    D’une vierge de carnaval,
    On vient chanter sous son balcon
    Qu’on l’entend jouir jusqu’au bal !
    Nous sommes les tombeurs de masques,
    Insuportables et fantasques,
    Ivres de débauche et de frasques
    Du clair matin à l’aube pâle.

    Nous ne goûtons guère ces belles
    Qui confondent glace et vertu ;
    Qui, pour garder au sec leurs perles,
    Referment l’huître et le tutu !
    Vive les douces, les donzelles,
    Sus à la gueuze, à la gazelle
    Qui ne se fait point trop rebelle
    Lorsqu’on lui met la main au cul !

    Nous aimons peu ces délicates
    Qui font un rempart de leur blouse
    Lorsqu’on leur joue un air de gratte
    Aux environs de la pelouse !
    Vive ces joyeuses coquines
    Qui aiment lorsqu’on les lutine
    Et frémissent lorsqu’on butine
    Leurs infatigables ventouses !

    De la guêpière aux jaretelles
    A-t’on rien vu de plus dodu
    Qu’une culotte de dentelle
    Sur un fessier à moitié nu ?
    Vive les catins, les pucelles
    Qui nous ouvrent grand la rondelle !
    Allons croquer la fleur charnelle,
    Nous soûler au fruit défendu !
#+END_VERSE
#+END_CENTER

* Douceur vive

#+BEGIN_CENTER
#+BEGIN_VERSE
    Viens j’oublierai que je t’aime
    Le temps que le four préchauffe
    Et variations sur ce thème
    Libèrer l’instinct du fauve

    Sans savoir qu’on se connaît
    Je te prends belle inconnue
    C’est la saison des genêts
    Plus celle des ingénues

    N’y pensons plus que l’on baigne
    Le désert de pluie souvent
    Tu sais qu’un volcan qui saigne
    Répand sa cendre à tout vent

    Viens toi oublie que tu m’aimes
    Laisse flamber ton désir
    Afin que l’ouragan même
    Ne puisse éteindre un soupir

    C’est un sentiment si dense
    Qu’il pourrait nous écraser
    A moins que l’incandescence
    Le puisse canaliser

    On pourrait passer sa vie
    A se poser des questions
    Contentons-nous de l’envie
    Il n’y a d’autre raison

    Viens oublions que l’on s’aime
    Nous serons plus à notre aise
    Je ne veux pas que l’on sème
    Des verrous dans la fournaise

    Brisons le gel du respect
    Je te traiterai en chaude
    Et m’enfuirai avant l’aube
    Pour revenir juste après

    Lire sur ta peau de miel
    L’aveu muet d’un encore
    Que l’on se travaille au corps
    Pied au plancher vers le ciel

    Mais quand vient l’instant suprême
    De voguer sur l'élixir
    N’oublions pas que l’on s’aime
    Pour transcender le plaisir
#+END_VERSE
#+END_CENTER

* Sonate

#+BEGIN_CENTER
#+BEGIN_VERSE
    Parfois quand la nuit tombe et que je rêve en toi
    Nous jouons tous les deux un air au piano
    Un air à quatre mains prélude à nos ébats
    Et le désir compose un nouveau boléro

    Parfois quand la nuit tremble et qu’il fait un peu froid
    Je caresse tes joues où l’orage ruisselle
    Pour y cueillir enfin l'éclaircie l'étincelle
    De l’instant où tu viens te blottir dans mes bras

    Parfois quand la nuit brûle en vagues sensuelles
    Et que la plage s’offre à l’océan sauvage
    J’enlève tes frissons sur les dunes de miel
    Et nous voguons sans rame aux délicieux naufrages

    Mais quel que soit le temps nos rages nos passions
    Nous avons tour à tour dévoré les octaves
    Neige blé fleur et fruit l’aiguë unie au grave
    Nos voix entrelacées sur les quatre saisons
#+END_VERSE
#+END_CENTER

* Invitation

#+BEGIN_CENTER
#+BEGIN_VERSE
    Lumière éclipse éclair obscur
    Frontière floue du crépuscule
    Dis adieu aux plaines d’azur
    Bientôt les horizons basculent

    Sens-tu vibrer la frénésie
    Elle nous vient du fond des âges
    Pour nous dire ne sois sage
    Sens-tu vibrer la frénésie

    Elle nous vient du fond des âges
    Comme de l'étang le lotus
    Comme le chant des coquillages
    Qui souffle sur le papyrus

    Sur le papyrus où tu aimes
    Sur le papyrus où tu crées
    D’une page blanche un poème
    De la nuit de jais une fée

    Lumière éclipse éclair obscur
    La lune contre le soleil
    Qui va gagner rien n’est moins sûr
    Ils semblent s’entendre à merveille

    Ils jouent au loup qui chasse l’ange
    Ange loue moi loup mange moi
    Et ces deux anges se démangent
    Quel doux mélange que voilà

    Car le train du temps n’attends pas
    Ecoute siffler la vapeur
    La locomotive en chaleur
    S'ébranle sous le feu de bois

    Comme de l'étang le lotus
    Comme le chant des coquillages
    Qui souffle sur le papyrus
    Elle surgit de son naufrage

    Dès que la pénombre sauvage
    Frontière floue du crépuscule
    Invite dame libellule
    A danser entre les nuages

    Quel doux mélange que voilà
    Ils semblent s’entendre à merveille
    M’amie ne reste pas de bois
    Viens au bois cueillir des groseilles

    Car le voyage n’attends pas
    Dis adieu aux plaines d’azur
    Quand l’horizon basculera
    Nous pourrons tirer les tentures

    Sens-tu vibrer la frénésie
    Sur le papyrus où je t’aime
    Sur le papyrus où tu crées
    D’une page blanche un poème

    Dès que la pénombre sauvage
    La lune contre le soleil
    Au firmament font des ravages
    Pour nous offrir un arc-en-ciel

    Partons pour l'île des idylles
    La plage et les noix de coco
    La langueur des vagues coquines
    Et le fondant du cacao

    Ou bien au son des cornemuses
    Danser la ronde des étoiles
    Faire l’amour avec les muses
    Jusqu’au réveil de l’aube pâle

    Je serai loup tu sera l’ange
    Puis nous inverserons le jeu
    Et que plus rien ne nous dérange
    Avant d'être en gare des cieux

    Qui va gagner rien n’est moins sûr
    J’ai mis du coton sous l’essieu
    Lumière éclipse éclair obscur
    La lune au soleil a pris feu
#+END_VERSE
#+END_CENTER

* A une désenchantée

#+BEGIN_CENTER
#+BEGIN_VERSE
    Quand vous serez blasée de trop de vilénies,
    Balayée par le flux constant de l’ironie,
    Quand rien ne sera plus important que la vie,
    Me ferez-vous l’honneur d’une nuit dans mes bras ?

    Quand vous aurez vidé les flacons du désir,
    Croyant ne plus jamais craquer pour un sourire,
    Me ferez-vous l’honneur d’une nuit dans mes bras
    Que je puisse à nouveau vous regarder rougir ?

    Quand je ne serai plus ébloui par les gemmes,
    Me ferez-vous l’honneur d’une nuit dans mes bras
    Que je puisse admirer dans ces cheveux que j’aime
    Toute une galaxie constellée de poèmes ?

    Me ferez-vous l’honneur d’une nuit dans mes bras
    A l’heure où seul un oui osera me surprendre,
    A l’heure où je serai assez fou pour te prendre,
    Ton corps contre mon corps dans une passion tendre ?
#+END_VERSE
#+END_CENTER

* L'amour n'existe pas

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’amour n’existe pas
    Parfois tu hallucines
    Il est là sous tes draps
    Mais c’est juste une épine

    Derrière les courtines
    Un piège de satin
    Filet tressé de vin
    Fin et d’humeur chagrine

    Reverse-moi du vin
    Ma tristesse est vidée
    Ton nectar est divin
    Mais la coupe est criblée

    De part en part percée
    Et notre amour s’enfuit
    Ne laissant dans le lit
    Que la lie désséchée

    C’est juste un joli nid
    Un peu de paille en or
    Quelques cris dans la nuit
    Oubliés à l’aurore

    C’est l’appétit d’un corps
    Ou la soif de conquête
    Parfois on est si bête
    De chasser des trésors

    Interminable quête
    Dans les plaines démentes
    Recouvertes d’arêtes
    Et d’horizons qui mentent

    C’est juste de l’amante
    L’arrière-goût des lèvres
    Qui laisse un peu de fièvre
    Et des visions d’amande

    Non il n’existe pas
    Dès qu’un coeur dégouline
    Les vautours volent bas
    Les mouches s’agglutinent

    Et pourtant nous l’avons
    Tous aperçu un jour
    Glissant comme un savon
    Tendre comme un velours
#+END_VERSE
#+END_CENTER

* Attabulations

#+BEGIN_CENTER
#+BEGIN_VERSE
    Un simple banc dans un parc.
    Il est ivre, donc monarque
    De ses rèves qu’il embarque
    Vers un monde moins vilain.
    Le ciel est gris, peu importe,
    Il suit ce vin qui l’emporte
    Par-delà les limbes mortes,
    Les brumes et le crachin.

    Table bancale et cartons.
    L’atout ? Le coeur, sans raisons,
    Serait-il maître sinon
    D’un quartet de puissants rois ?
    L’ancien rouspète et sermonne
    Le novice le talonne
    L’autre contemple sa donne
    Le dernier trie son fatras.

    Table oblongue de banquet.
    Aidée d’amphores en grès,
    La bouteille sert d'étais
    Aux langues qui se délient.
    La chanson court dans les rues,
    Les places, les avenues,
    Attirant les ingénues
    Vers ce brasier qui pétille.

    Table ronde, rien au centre,
    Place qu’occupe en son antre
    L’honneur qui rentre son ventre
    Pour crier : ``Sus aux félons !''
    Ils jurent alors, l'épée
    Sur le coeur et la pensée
    Vers la gloire détournée
    Ou vers un seul mot : ``filons !''

    C’est un complot, salle obscure,
    Les masques servent d’armure
    Le couteau fend les dorures
    Le signal est convenu.
    Le palais dort en silence
    Mais soudain un bruit de lance !
    Tous s’immergent en cadence
    Dans un secret bienvenu.

    La cantine d’une école,
    Armée de marmots frivoles,
    Gare à la purée qui vole :
    La cuiller lance ses pierres.
    Les cafards rampent de peur
    Car le couvert est vengeur
    Les victimes, sous le beurre,
    Tachent la nappe peu fière.

    Discussion ventripotente
    Sur quelques bières ardentes
    Politique, siège en vente,
    Filles et fleurs, tout y passe.
    La gazette se relit
    Le vieux mot est ressorti
    Un reste de mousse rit
    Les moustaches se délassent.

    Bois tamisé et chandelles
    Bien sûr elle est jeune et belle
    Il tourne autour et chancelle
    Guettant la moindre ouverture.
    La lampe s'éteint, tant mieux !
    Le jour rend les coeurs frileux
    La où l’obscur amoureux
    Appose sa signature.
#+END_VERSE
#+END_CENTER

* Double écho

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je thème,
    Tu même,
    Ils sèment.

    Je suis bien loin de toi mais j’entends les échos
    De ton chant triste et clair dans le voile du soir ;
    J’entends ta faible voix malgré le chant des foires,
    Le choeur des voies lactées canonise ces mots.

    Je suis bien loin de toi et j’attends comme un sot
    Que la nuit te dévoile et nous unisse enfin.
    Je suis comme un vieux loup acculé par la faim
    Mais qui ne goûte plus que ta chair sous ses crocs !

    Je voudrais abolir les mille années-lumière,
    Parcourir d’un seul trait ce temps qui nous sépare ;
    Vois-tu je me souviens de ce sombre boudoir
    Et de ce doux contact qui franchît la frontière.

    Je cède volontiers aux charmes du mystère
    Et l'étrangeté flotte à l’entrée de tes reins ;
    Si ce pâle anneau d’or n’a retenu ta main,
    Laisse-moi le dissoudre en fredonnant ces vers.

    Je thème,
    Tu même,
    Ils sèment.

    Ton écho se reflète au fil de mon espoir,
    Dis-moi si tu le vois briller dans ton jardin.
    Dis-moi si les flocons que pleurent mon chagrin
    Libèrent sur ton sein un caressant nectar.

    Te chuchoteraient-ils que je veux te revoir ?
    Partager la morsure incendiaire du givre
    Qui t’enserre et la vaincre à coups de ce sel ivre
    Que tranpirent deux corps épousés dans le noir ?

    Nos coeurs fous ballotés par un désir sans frein,
    De l’aube des rosées aux étangs teints de cuivre,
    Jusqu'à ce qu'épuisés nos souffles se délivrent,
    Assouvir d’heur en heur notre amour clandestin,

    Veux-tu ? Ou n’ai-je seul que l’espoir d’un refrain,
    Souvenir incessant roulant comme une vague
    De ton doigt lacéré, étouffant sous sa bague,
    Avec ces quelques mots perdus dans le lointain ?

    Je thème,
    Tu même,
    Ils sèment.
#+END_VERSE
#+END_CENTER

* Randonnée

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je vous emmènerai dans ce lointain jardin
    Où l’on entend encore de joyeux lutins
    Nous nous y laisserons bercer par une brise
    La pomme y sera drôle et la cerise exquise.

    Auprès de ces ruisseaux où l’eau chante sa joie
    L’onctueuse Ondine, de sa voix de cristal
    Où se mèle en torrents clarinette et hautbois,
    Nous offrira sans doute un de ses récitals.

    La chanterelle nous contera quelque histoire
    Qui ne se peut entendre qu'à l’orée du soir.
    Les arbres bruisseront leurs ramages de rire
    Sous les taquineries d’un zéphyr en délire.

    Nous verrons sûrement ces troncs au front plissé
    Qui, des heures durant, racontent leur jeunesse
    Sous la teinte rougeâtre d’un vieux vin boisé
    Qui grise jusqu’au faîte leur sève en liesse.

    Puis la nuit étendra ses filaments pudiques
    Nous nous allongerons tout près d’une clairière
    Et là entre la terre, l’air et la rivière
    Notre feu rougira, ma sorcière lubrique.
#+END_VERSE
#+END_CENTER

* La musique

#+BEGIN_CENTER
#+BEGIN_VERSE
    La musique parle à notre âme
    Lorsqu’on prend le temps d'écouter
    Les cadences en filigrane
    Qui trament ses sons nuancés.

    Ainsi, j’eu un jour la vision
    D’une femme au pas éthéré
    Flottant dans les rythmes profonds
    Et dans les volûtes d’un thé.

    Sa robe était de pourpre et semblait une fleur
    Prise dans le siphon d’un ruisseau agité
    Tant elle tournoyait de transe et de sueur
    Dans l’extase lascive d’un corps enfiévré.

    Car elle languissait dans ses pas débridés,
    Lente autant que rapide en un souffle asynchrone,
    Flamme dorée de jade et topaze emmèlés
    Qui vibrait, tremblotante, dans l’air ceint de baumes.

    L’azur se zébrait de ses bijoux embrasés
    Par le va-et-vient de sa danse suggestive ;
    Je la suivais des yeux, tout mes sens envoûtés,
    Lorsqu’elle à filé comme une étoile impulsive.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

