
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Langueur
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Heure âge

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je cours. Je cours derrière un être qui s’enfuit.
    C’est mon double et c’est moi, il court mais il m’attend.
    Même si par instant je crois qu’il se réduit,
    Le chemin jusqu'à lui reste toujours constant.

    Malgré cette sueur sur nos corps haletants,
    Je doute. Oui le décor est si plat que je doute
    Progresser d’un orteil sur cette morne route
    Qui déroule ses lieues comme un tapis roulant.

    Ecoute le jusant qui te chuchote, écoute !
    Tu pourrais y trouver la clef du double sens,
    La pierre de corail gardienne des deux voûtes :
    Est-ce elle qui recule, est-ce toi qui avances ?

    Cela revient au même, et pourtant ! Et pourtant
    Le spectre reste là, à dix pas, paradant,
    Semblable à un bouffon, un clown un peu railleur.

    Le silence est souvent la meilleure réponse
    Mais qui est-il vraiment ce fou venu d’ailleurs ?
    Autant vouloir couler une bouée en ponce.

    Tout ce que l’on en sait, c’est qu’il s’appelle l’heure,
    Qu’il gronde quand le ciel se couvre de moustiques,
    Qu’il imite nos tacs et imite nos tics.
#+END_VERSE
#+END_CENTER

* Triangulation

#+BEGIN_CENTER
#+BEGIN_VERSE
    L'écoulement dans les gouttières
    La musique comme rivière
    Percolation de la théière
    Trois symboles de l’existence

    La paix que me chante le vent
    La frontière entre deux courants
    Le lourd tumulte des enfants
    Le contraste de l’existence

    Tous ces emprunts juste pour rendre
    Les amitiés sans bien s’entendre
    Les discussions sans se comprendre
    Solitude de l’existence

    La pluie qui borde mon ennui
    La vaste question de la nuit
    Le silence qui me poursuit
    Inquiétude de l’existence

    Questions qui fusent de la peur
    Feu d’artifice de couleurs
    Comme une apaisante chaleur
    Philosophie de l’existence

    Lorsqu’on se sent perdu et pâle
    Dans une luge qui s’emballe
    La douce étoile qui me parle
    Immense espoir de l’existence

    Tendre la main ou essayer
    Pardonner la stupidité
    Et la sienne pour commencer
    Soulagement de l’existence

    Racler des ongles tous les murs
    Jusqu'à ce que tous se fissurent
    Créer un monde d’un murmure
    Donner un sens à l’existence

    L’horrible tic-tac qui martèle
    La seconde comme un rappel
    Des accords du blues éternel
    C’est le refrain de l’existence

    Le vertige de l’infini
    N’y pas dissoudre son esprit
    Mais étendre son coeur sur lui
    Contradiction de l’existence

    Cet horizon incandescent
    Sous les nuages rougeoyant
    Est-ce le lever le couchant ?
    Dualité de l’existence

    Les croquis mouvant que dessinent
    Dans les blés de folles ondines
    Les avenirs qui dégoulinent
    C’est la source de l’existence
#+END_VERSE
#+END_CENTER

* Torpeur

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les étés se ressemblent
    Toujours la même odeur
    Un glaçon de décembre
    Qui tempère les coeurs

    Sous la neige trop vierge
    Le feu de la colère
    Les volcans sont des cierges
    Qui brûlent à l’envers

    De l’acide bouillonne
    Tout au fond du cratère
    Savamment la lionne
    Répand l’enfer sur terre

    La cire incandescente
    Bave des langues d’or
    Qui lentement descendent
    Vers la plaine qui dort

    C’est le soufre et la mort
    Toujours la même odeur
    La passion qui dévore
    La haine au fond des coeurs

    Etalage de verges
    Dressées vers l’impudeur
    Et l’amour qu’on asperge
    Qui vomit son aigreur

    Sur les fleurs délicates
    Surchargées de relents
    La sueur la peau moite
    D’un orage latent

    Qui a peur d'éclater
    Peur de qui ? Peur de quoi ?
    Serait-ce de briser
    Quelque miroir de soie ?

    Serait-ce d’effacer
    Sur les sombres parois
    Les ombres projetées
    Epouvantails du roi ?

    C’est l'écoeurant décor
    D’un laid et creux théâtre
    Une danse des corps
    D’un érotisme fade

    Qui n’avoue pas son nom
    Hypocrisie suprême !
    Que c’est beau que c’est bon
    L’orgie sans ses problèmes !

    L'âme aussi se salit
    L'âme aussi se nettoie
    Même à cent lieues d’un lit
    Même si ce n’est toi

    Dans l'éther le plus pur
    On rencontre des rats
    Les champs de moisissures
    N’ont nul besoin de draps

    Pour couvrir d’un linceul
    Le printemps endormi
    Ni briser sous la meule
    Le grain d’un pain rassis

    Tout n’est qu’un instrument
    Un tremplin vers la gloire
    Et l’amour là-dedans ?
    S’esclaffe l’encensoir

    Qui connaît l’illusion
    De ces leviers de paille
    Et le fumant sillon
    De l’incendie qui braille

    Rugissant de ferveur
    Sous les bûches offertes
    Les contre-feux moqueurs
    Enfument les carpettes

    Pour protéger le foin
    Des canailles qui tremblent
    Longue vie aux potins !
    Les étés se ressemblent
#+END_VERSE
#+END_CENTER

* Aurore onirique

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans un pays du sud
    Ecrasé de soleil
    J’ai renversé ma flûte
    Dans un silence opaque
    Mais l’ombre n’a plus cours
    Lève l’ancre appareille
    Naufragée sans recours
    Les cheveux sous la laque

    Car tout n’est qu’un éclair
    Aperçu de coté
    Le monde a l'épaisseur
    D’un papier quadrillé
    Aux nuages de fleurs
    Chaque case est un temple
    L’aurore au timbre clair
    Tranche d’une main ample

    La tranche des nuits vagues
    Fauchée par les écueils
    Sur la jetée de sel
    Mouillée de gazouillis
    La fée rose étincelle
    A chaque clapotis
    Et la lumière drague
    Le fond qui se recueille

    Comme un arbre en automne
    Sur son feuillage d’ocre
    Brûlé par les vapeurs
    Qui montent des labours
    Et nul ne s’en étonne
    Dans la torpeur des bourgs
    Chauffés par la liqueur
    Embrumés de breloques

    Où l’air s’appesantit
    Le temps cesse de battre
    Plus de vent plus de sens
    La plaine attend l’orage
    Attend sa délivrance
    Que l’atmosphère éclate
    Du verbe qui jaillit
    Rempli d’idées sauvages

    L'équilibre statique
    Contient déjà le germe
    Qui grossit dans ses reins
    Approche de son terme
    C’est la vie électrique
    D’où naît le mouvement
    D’où la crainte s'éteint
    Il n’y a de néant

    Il nia l’impensable
    Le nez enivré d’or
    Allongé sur le sable
    Les yeux dans les nuées
    Qui parsemaient le ciel
    Comme une humble buée
    La pluie vint solennelle
    Sur la terre à éclore
#+END_VERSE
#+END_CENTER

* Lancine anse

#+BEGIN_CENTER
#+BEGIN_VERSE
    Qu’entendez-vous par être ?
    Sûrement pas paraître
    Revivre l’essentiel
    Que la traction s’inverse
    L’attraction que l’on verse
    Et tomber vers le ciel

    Qu’entendez-vous par vivre ?
    La clef qui vous délivre
    Des prix sont matériels
    C’est singer les grimaces
    D’un rire brise-glace
    Et tomber vers le ciel

    Qu’entendez-vous par vendre ?
    Vendre c’est se défendre
    En encaissant du fiel
    C’est courtiser les murs
    J’aime autant les murmures
    Et tomber vers le ciel

    Qu’entendez-vous par aime ?
    Roucouler un poème
    Dérouler la dentelle
    Un stylo qui caresse
    Des poses qui paressent
    Et tomber vers le ciel

    Ton âme n’est pas lasse ?
    Je connais des palaces
    Des corps superficiels
    A pleurer des joyaux
    Rejoindre les oiseaux
    Et tomber vers le ciel

    Que te dis diamant ?
    Simplement dix amants
    Cinq jolies demoiselles
    Chevauchant l'étalon
    Et eux sur les talons
    A contempler le ciel

    Parle-moi de folie !
    Six sens qui s'émoustillent
    Conjugués au pluriel
    Voguer à travers seins
    Aux flots du traversin
    Et partir vers le ciel !
#+END_VERSE
#+END_CENTER

* Décadence

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je suis un crépuscule à l’aube du chaos,
    Un soleil frissonant réchauffe mes vieux os.

    Sur la plage cuivrée parfumée de vanille,
    L’immense ombre s’avance ainsi qu’un escargot.

    Bien que l’eau y soit douce et que dansent les filles,
    Leurs jolis bracelets ne rendent qu’un son creux :

    L’odeur de l’inutile et de l’absurdité
    Remplit l’air surchargé d’un luxe somptueux.

    Qui n’a rêvé l’accès à l’immortalité !
    L’ambroisie, le nectar, les palais olympiens ...

    Si les idées au moins ... Mais non, rien ! Rien ne reste
    Jusqu’au marbre et au grès des génies séraphins.

    Il paraît qu’il vaut mieux ainsi, que cet inceste
    Est l’ange et le bourreau de l’autel du progrès.

    Verser dans le futur la coupe du passé,
    Jour et nuit enlacés dans l'âpre eau des marais

    Ah vraiment c’est trop lent ! Ne peut-on s’en passer ?
    Non. Le cycle est le seul garant d'éternité.
#+END_VERSE
#+END_CENTER

* Nature vive

#+BEGIN_CENTER
#+BEGIN_VERSE
    Rose noire
    Rose rouge
    Qui se croisent
    Souffle court

    Jalousie
    Incendie
    Deux couleurs
    Pour deux fleurs

    Sous l'étoupe
    Des antennes
    Ombres pourpres
    Vénitiennes

    L’atmosphère
    Est épaisse
    Air de glaise
    Plus de lest

    C’est la chute
    Le plongeon
    La culbute
    Vers le fond

    Tout autour
    De leur vase
    Un orage
    Clair-obscur

    C’est un four
    Nuées noires
    Un ciel rouge
    Eclairs noirs

    Le déluge
    Délivrance
    Le temps s’use
    Sous la tente

    Désespoir
    Coeur qui bouge
    Rose rouge
    Rose noire

    L’eau s’enlise
    Cage rance
    Houle grise
    Pluie battante

    S’envoler
    Des radeaux
    Convoler
    Dans la peau

    Loin des trombes
    Camomilles
    Des momies
    Et des bombes

    Mains gigognes
    Venaisons
    Viens saisons
    Des cigognes

    Limousines
    Des enfants
    Il est temps
    Ma cousine

    Le raisin
    Se résigne
    Le déclin
    Se décline

    Rose beige
    Rose beige
    C’est la neige
    Qui s’agrège
#+END_VERSE
#+END_CENTER

* Clapotis

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est un étang maussade, un ruisseau domestique.
    D’aquatiques rongeurs éleveurs de barrages
    Ont castoraformé la rivière lyrique.

    Parmi la gent palmée de ce bocal sauvage,
    Trop fier pour se noyer, trop las pour s’envoler,
    Conscient de sa splendeur, le sieur Cygne surnage.

    Les pattes embourbées, le bec ensoleillé,
    Du saule au nénuphar, du nénuphar au saule,
    Il trotte dignement sur les flots argentés.

    C’est qu’il convoie l’ennui entre l'île et le môle,
    Dans la ménagerie qui cancane et qui glousse,
    Navetteur de l’absurde aux confins de sa piaule.

    Et puis, loin des canards dont les jeux l'éclaboussent,
    Lorsqu’il pleut assez fort pour gaver les gargouilles,
    Il vide son chagrin à l'écart, sur la mousse.

    Et ce n’est pas le chant croassant des grenouilles,
    Ni la mélancolie des narcisses de l’auge
    Qui pourraient l'égayer. Ni ce ciel qui se brouille,

    Ni, plus loin en aval, la ville qui patauge.
#+END_VERSE
#+END_CENTER

* Décor

#+BEGIN_CENTER
#+BEGIN_VERSE
    Quelques éclats de vers dispersés sur la table,
    Friselis vitrifié d’un lac de mousseline ;
    Quelques reflets brisés doucement dodelinent
    Avant de s’enliser dans le sirop d'érable.

    Quelques reflets brisés lentement se dandinent
    Sur des airs langoureux, sur des chants enfièvrés ;
    Au hasard des reliefs projetés en trois dés,
    La plume virevolte entre les damasquines.

    Sur des airs silencieux, des accords saccadés,
    Des livres enneigés de l’encre dégouline
    Dans le creuset soyeux d’une rose sanguine
    Où se fondent le rêve et la réalité.

    C’est le trèfle et le coeur, le pique et le carreau
    Qui mèlent leurs couleurs dans l'âtre d’un château
    Hanté par les esprits des cieux crépusculaires ;

    C’est l’acajou laqué des comptoirs tamisés
    Où les gemmes du vin font mousser l’or des bières ;
    C’est l’agile vapeur qui s'échappe du thé,

    Le songe qui dissout les barreaux des volières,
    Quelques mots griffonés entre l’onde et le sable,
    Quelques éclats de vers dispersés sur la table.
#+END_VERSE
#+END_CENTER

* Etincelles

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les vins de robe pourpre, essences exotiques
    Embaumant de laurier nos gorges déssechées
    Lézardant nos soucis de leurs chansons magiques
    Ambulances épiques des âmes blessées ;

    Les agiles cognacs égarant leur canelle
    En ces lointains pays où vivent des déesses,
    Ambres vieux et sages racontant leur jeunesse
    Lévitant nos esprits de leurs onguents de miel ;

    Délices volûtés, havanes enfumés
    Marc couvant les sombres secrets d’un noir café
    Déridante musique aux rythmes erratiques
    Manne de thé, d'épices, charmes féeriques ;

    Malgré vos soupirs, votre empire de caresses
    Débridant mes pensées, il faut que je confesse
    Ma plus vibrante drogue illumine une ombrelle
    Défait, j’erre dans l’abîme de ses prunelles.
#+END_VERSE
#+END_CENTER

* Crépuscule

#+BEGIN_CENTER
#+BEGIN_VERSE
    Décor. Meublé feutré, du cuivre et de l'étain.
    Lumière tamisée contournant les courtines
    Colorant les meubles d'ébène et d’acajou ;
    Epars, quelques rubis, décorant les atours.

    Voile qui dévoile, qui invite au festin,
    Traversé de lueurs, des courbes se devinent
    Sous son pâle tissus éclatant de bijoux.
    Le soleil lui dessine un brillant contre-jour.

    Dentelle qui ceinture, qui pare et soutient
    Des fruits orangés qui roulent et se dandinent
    Délicats dans le lit drappé de ses dessous.
    Délice sans balourd de grâce et de velours.

    Elle. Teintée, comme le soir qui nous étreint :
    Dessous rouges et cheveux noirs. Elle s’incline
    De son doux cil qui cligne. Point de sel ni d’ajout :
    C’est ainsi qu’elle a tout, sans fard et sans détours.
#+END_VERSE
#+END_CENTER

* La pluie

#+BEGIN_CENTER
#+BEGIN_VERSE
    La pluie murmure sa symphonie cristalline
    Sur la ville, collier perlé d’aigue-marine

    Les promeneurs, l’air effaré
    Cherchent un abri en courant,
    Les filles, les chevaux mouillés
    Libèrent leurs regards sauvages
    Comme un défi au mauvais temps.
    La nature sort de sa cage,
    J’attends à l’abri d’un auvent

    La pluie fredonne sa symphonie cristalline
    Sur la ville argentée perlée d’aigue-marine

    Pris au piège d’une cabine,
    Un homme d’une humeur chagrine
    Ecoute s'écouler les heures ruisselantes ;
    Tourbillonant sur son radeau,
    Mon âme, au fil des gouttes d’eau
    Se laisse imprégner de la rumeur apaisante

    Aujourd’hui, en concert, les perles cristallines
    Sur la ville-corail zébrée d’aigue-marine

    Sortant de leur sombre cachette,
    Les parapluies poussent de joie
    Et boivent les pleurs des nuages :
    Ils servent d'écran aux coquettes
    Et à leurs aigrettes de soie
    Gagnées au prix de tant d’ouvrage

    La ville résonne des orgues cristallines
    Sous le souffle automnal d’une brise marine

    Lassé de contempler ces cols emprisonnés,
    Je me suis décidé, j’ai franchi le rideau.
    Je n’ai plus froid. Pourtant, mon vieux pull détrempé
    Boit comme un entonnoir à travers son réseau
    Mais une flûte en moi siffle comme un roseau :
    La source grisante de l’oiseau liberté

    La ville est un torrent de trombes cristallines,
    Un long fleuve sans fin de brume aigue-marine

    Flattant les bûches qui ronronnent, qui crépitent
    Les flammes d’ocre dansent dans la cheminée.
    Du toit, des gouttières, de partout l’eau ruisselle,
    Le chagrin des sept mers s'épanche sur mes vitres.
    Sur le thé fumant flotte une essence éthérée,
    Comme la vision de l’harmonie éternelle

    La pluie murmure sa symphonie cristalline
    Sur la ville, collier perlé d’aigue-marine
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

