
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Safrans
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Effet de bord

#+BEGIN_CENTER
#+BEGIN_VERSE
    Rouler sa bosse
    Nomade en mer
    Dans un carrosse
    De dromadaires

    Faire le point
    D’eau et de vent
    Sur les coussins
    D’un vieux divan

    Joindre un turban
    Au lourd ciré
    Et à la pipe
    Un narguilé

    Ôter la cape
    Et la rapière
    Mettre le cap
    Loin des congères

    Laisser l’offrande
    Sur la banquise
    La voile prendre
    Un bain de brise

    Et la chaleur
    Mordre la voile
    Bain de vapeur
    Et de pétales

    Courir les dunes
    Vagues brûlantes
    Fleurs de lagunes
    Lunes de menthe

    Être corsaire
    Mais des corsages
    À l’abordage
    Des jarretières

    Tirer des salves
    Mais de caresses
    Salves de cils
    Des fortes tresses

    Laisser le large
    Tordre la toile
    Tâter des vergues
    Frôler l'étoile

    D’une rafale
    De roues à aubes
    D’un jet spirale
    Croiser vers l’aube

    Couvrir l'écume
    De croissants chauds
    D’iris d’agrumes
    Et de joyaux
#+END_VERSE
#+END_CENTER

* Passage à gué

#+BEGIN_CENTER
#+BEGIN_VERSE
    La plaine se déssèche, ouvrons tout grand les vannes !
    Que l’eau accumulée par tant d’années d’orage
    Se déverse à grand flots dans la gorge aux havanes !

    Que les fleuves gardés à l’abri des barrages
    Répandent d’un seul coup sur la terre assoiffée
    Le philtre des langueurs et l’onde des voyages !

    Il ne sera pas dit que l’ardente rosée
    Attisera sans fin d’un tison lacrymal
    Le supplice qui mord le creux de la vallée ...

    Il ne sera pas dit qu’un monde minéral
    Couvrira d’aiguillons la rose et l’aubépine
    Ni que le vent qui tourne à vide en ce dédale

    Sera seul chevauchant la lande et les collines ...
    Au galop ! sans tarder, l’aurore se pavane,
    Sous les nuages lourds, la lavande s’incline,

    La plaine se déssèche, ouvrons tout grand les vannes !
#+END_VERSE
#+END_CENTER

* Sulfure

#+BEGIN_CENTER
#+BEGIN_VERSE
    Horizon poussiéreux dis-moi si je suis mort
    Si ce terril en feu que l’on nomme le monde
    Est l’enfer embrumé du temps qui s'évapore
    Horizon poussiéreux dis-moi si je suis mort
    Si c’est un cauchemar ce ciel d’ocre qui gronde

    Comme un volcan cloué dans un plafond d'ébène
    Cratère nauséeux qui tangue et qui vomit
    Des pluies de cendre sèche et des torrents de haine
    Comme un volcan cloué dans un plafond d'ébène
    Vers le sol torturé crevassé et maudit

    Que reste-t-il des bois disloqués par la foudre
    Quelques troncs calcinés vestiges ricanant
    Au nez de ces sorciers qui crachent l’asthme en poudre
    Que reste-t-il des bois disloqués par la foudre
    Des jardins suspendus arrimés au néant

    Archipels dérivants comme une pierre ponce
    Qui flottez sur un lac de sable et de cailloux
    De lave refroidie déchirée par les ronces
    Archipels dérivants comme une pierre ponce
    Fracturées par le vent dites qui êtes vous

    Peut-être le produit d’une hallucination
    Ou le souffle brûlant d’un dragon colérique
    Vertige lancinant où se trouve le fond
    Peut-être le produit d’une hallucination
    Réel synthétisé sur nos corps névralgiques
#+END_VERSE
#+END_CENTER

* Désert

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai traversé des océans
    De sable fumant et aride.
    Tout n’y est qu'éclats aveuglants
    De dunes sèches et cupides
    Modelées par un vent candide.
    Un soleil jaune se reflète
    Sur la vague mouvante et vide
    Et ses myriades de piècettes.

    Il n’est qu'à voir le flot mourrant
    De la rosée fraîche et limpide
    Pour imaginer que céans,
    Caché dans son abri humide,
    Doit sucer un scorpion sordide.
    Ici, rien que des silhouettes,
    Pas d’ombre, rien qu’un teint livide
    Et ses myriades de piècettes.

    Dans ces galaxies de brillants
    La soif tenaille et l’eau acide
    Qu’offre l’oasis rutilant
    Emporte les esprits lucides
    Sur son amertume fétide.
    Le vautour sort son épuisette,
    Attiré par le ciel torride
    Et ses myriades de piècettes.

    Compère, évitons l’ouragan,
    Passons au large des aigrettes !
    Vive le ruisseau accueillant
    Loin du cliquetis des piècettes !
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

