
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Océanes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Diamant

#+BEGIN_CENTER
#+BEGIN_VERSE
    Or
    Limpide,
    Eau timide,
    Complexe accord
    De feux immortels,
    Voix grave d’un ténor,
    Résonance d'étincelles,
    Palpitation du choeur des belles,
    Débauche éclatante de lumière,
    Noyade de l’oeil dans un lac d'éclairs,
    Flocons en hiver, lucioles estivales,
    Océan enneigé sur qui flotte un brasier,
    Pétales printaniers, palette automnale,
    Reflets souriants de l’astre argenté,
    Glissade grisante de névé,
    Vibration sur le coeur des belles,
    Décadence de prunelles,
    Eclat flou d’un trésor
    Voilé de dentelles,
    Mais vient l’aurore
    Translucide,
    Avide
    D’or.
#+END_VERSE
#+END_CENTER

* Être ange

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il n’y a plus d’encre sauvage
    Les blés sont coupés dès l’automne
    Avant le givre et qui s'étonne
    Il n’y a plus d’encre sauvage
    L’eau a déserté les virages
    Et c’est du sable qu’on moissonne
    Il n’y a plus d’encre sauvage
    Les blés sont coupés dès l’automne

    Sur un sol creusé de mirages
    Le temps n’est plus qu’une momie
    Et l’atmosphère un sarcophage
    Sur un sol creusé de mirages
    Les sentiers perdent leur magie
    L'île voilée a fait naufrage
    Sur un sol creusé de mirages
    Le temps n’est plus qu’une momie

    Même tel masque à l’agonie
    Vit se briser ce loup de verre
    Sachant trop bien l’art de se vendre
    Même tel masque à l’agonie
    À laissé filer les enchères
    Tomber son rire de cassandre
    Même tel masque à l’agonie
    Vit se briser ce loup de verre

    Même tel prince de cristal
    Qui le croirait qu’il fut de chair
    Avant l’aurore des glaciers
    Même tel prince de cristal
    Qui le croirait qu’il a chanté
    Comme un jeu d’ombre et de lumière
    Même tel prince de cristal
    Qui le croirait qu’il fut de chair

    Dans ce théâtre d’impatience
    Où tout se fige et ce silence
    Qui laisse l’heure sans ressort
    Dans ce théâtre d’impatience
    Tout semble sombrer sans effort
    Rien ne s'échappe du décor
    Dans ce théâtre d’impatience
    Où tout se fige et ce silence

    Jusqu’aux nuages immobiles
    Où les cadrans sont pris au piège
    Loin des soleils d’or et de neige
    Jusqu’aux nuages immobiles
    Qui ont déboussolé les roses
    Les vagues d’art les vents moroses
    Jusqu’aux nuages immobiles
    Où les cadrans sont pris au piège

    Jusqu'au rêve âpre des rivières
    De pluie d’orage et d’océan
    Le moulin dort comme une pierre
    Jusqu'au rêve âpre des rivières
    Scrutant au loin les oiseaux blancs
    Mais rien ni l’ombre ni l'étang
    Jusqu'au rêve âpre des rivières
    De pluie d’orage et d’océan

    Car le jusant reste une eau vierge
    Rosée de candeur et d'épine
    Pourtant les remous se dandinent
    Car le jusant reste une eau vierge
    Sous le pinceau qui la dessine
    Qui la retouche et la taquine
    Car le jusant reste une eau vierge
    Rosée de candeur et d'épine

    Et la voilure attend la brise
    Comme un messie libérateur
    Le moindre éventail se déguise
    Et la voilure attend la brise
    Jamais vaincue toujours conquise
    Par le frisson de ses frayeurs
    Et la voilure attend la brise
    Comme un messie libérateur
#+END_VERSE
#+END_CENTER

* Légende

#+BEGIN_CENTER
#+BEGIN_VERSE
    Un ciel jaspé de violine
    Que de blancs bouquets d'églantine
    Traversent ça et là
    L’arôme ardent de la muscade
    Gorge la pulpe des grenades
    Imagine un peu ça

    Les sept soleils de l’arc-en-ciel
    Constellent la cité d'Ariel
    De carreaux de lumière
    Mais notre princesse est maussade
    Il pleut dans ses beaux yeux de jade
    A l’abri des paupières

    Des sept cités de l’archipel
    Elle gouverne la plus belle
    Dans son palais d’ivoire
    Mais ses étoffes de velours
    Ne lui sont plus d’aucun secours
    Quand l’envahit le soir

    Ni la caresse des jets d’eau
    Ni le vent lutin sur sa peau
    N’apaisent ses tourments
    Elle se souvient de ces soirs
    Où il émergeait du miroir
    Dans un halo d’argent

    La lune à travers les rideaux
    Les feux follets sur les créneaux
    Eclairant le donjon
    Quand elle offrait son corps de fée
    Et s’ouvrait comme une orchidée
    Sous son beau papillon

    Mais le dit miroir s’est brisé
    Un de ses elfes affolés
    A fait fuir son amant
    Il ne lui reste de ces tendres
    Instants qu’une plume et l’attente
    Qui déchire le temps

    Quand la chaleur de la canelle
    S’infiltre à travers la dentelle
    Vient pimenter ses sens
    Elle sent sous le fin coton
    La poudre rouge des dragons
    Qui lui brûle le ventre

    Dès que le dernier jour s'éteint
    Tandis que le désir l'étreint
    Qu’il ourle l'édredon
    Elle roule comme un navire
    Nef désemparée qui chavire
    Coulée par la passion

    Ni les cascades de rubis
    Ni les rivières de vin gris
    N’apaisent son chagrin
    Seule la magie de l’absinthe
    L’espoir qu’au coin du labyrinthe
    Il apparaisse enfin

    Et dans son ciel de violine
    Les nuages noirs s’enracinent
    Sa volonté s'érode
    Un jour au bord du désespoir
    Elle dit aux ondes de moire
    En leurs murs de géode

    Je suis la princesse d'Atlante
    Reine des sept îles flottantes
    Votre fille sur terre
    Mes villes de marbre et d’or blanc
    De corail et de diamant
    Débordent de lumière

    Le plus humble de mes châteaux
    Je l’ai sculpté dans un joyau
    Ensorcelé d'éclairs
    Les farfadets trolls et dragons
    Mangent dans ma main les griffons
    Subissent ma colère

    Je suis la princesse d'Atlante
    Reine des sept îles flottantes
    Votre fille sur terre
    Les géants craignent mes pouvoirs
    Mais je vous implore ce soir
    Ecoutez ma prière

    Pour vous dix coffres d'émeraude
    Si vous me portez vagues chaudes
    Par delà l’irréel
    Pour vous dix coffres de platine
    Si vous me portez vagues fines
    Au monde des mortels

    Dans le silence qui suivit
    Les oiseaux gagnèrent leurs nids
    Sans risquer un murmure
    Alors du fond des flots sauvage
    On lui répondit d’un ton grave
    Faisant trembler les murs

    Princesse garde tes joyaux
    Vois-tu près de toi ces cristaux
    C’est un échantillon
    Nous avons dans nos profondeurs
    Mais cela vaut-il une fleur
    Des palais par millions

    Va il viendra te retrouver
    Ecoute les saules pleurer
    Leurs larmes sont les tiennes
    Ignores-tu que l’océan
    Est aussi un miroir d’argent
    Va jolie magicienne

    Ceci termine le récit
    Que me fit un jour un ami
    Les yeux brillant de fièvre
    Je crus d’abord que ces merveilles
    Sortaient tout droit de la bouteille
    Qu’il lança vers la grève

    Il est parti seul à la nage
    Vers l’horizon vers le visage
    De sa charmante fée
    Il n’en est jamais revenu
    L’océan l’aurait-il vaincu
    C’est à vous d’en juger

    Douze mois après son départ
    J’ai trouvé devant mon miroir
    Cet étrange billet
    Ou bien je suis devenu fou
    Ou il est en vie après tout
    Voici donc le poulet

    La lavande couvre les mers
    Le réel et l’imaginaire
    Ont eu un bel enfant
    Une toute petite fille
    Elle se nomme Poésie
    Née au dernier printemps
#+END_VERSE
#+END_CENTER

* Livre de bord

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai voyagé sur l’océan
    Des sentiments

    Balloté entre l’ivresse
    Et la tristesse

    Il est immense et parsemé d’archipels
    C’est un ciel
    Dont la carte lapis scintille de feux blancs

    La mer souvent s’y creuse et la houle
    S’y enroule
    Sous la légende absurde du vent
    Eclatant

    Le vent y vend des promesses qu’un fou
    Ne croirait pas
    Mais lorsqu’on veut véritable un bijou
    Et même s’il ne vaut qu’un demi-clou
    On y croit

    On y croise deux grandes îles
    Peuplées de touristes fébriles :
    L'Amour et l'Amitié
    Là-bas la foule seule abonde
    Non plus aucune dune ronde
    Où aller s’isoler

    Il se dit qu’un tunnel sous-marin les relie
    Et que la nuit les fées viennent choisir leurs proies
    Parmi le sable bleu des humains assoupis
    Qui s’endort anonyme et se réveille roi
    Cependant c’est la brume
    Alentours et l'écume
    Superpose le phare aux éclairs des lamproies

    Voyageur, fuis ! Qui que tu sois
    Vieux pirate au regard lubrique
    Marchand de safran et de soie
    Loup de mer au souffle lyrique
    Héroïque jeune corsaire
    Marin de bar ou de rivière
    Veux-tu éviter la civière ?
    Fuis loin de ces eaux maléfiques !

    J’ai voyagé sur l’océan
    Des sentiments

    Il est immense et parsemé d’archipels
    C’est un ciel
    Dont la carte lapis scintille de feux blancs

    Navigue plus loin vers l’aurore
    Qu’elle soit d’or ou boréale
    Quand le septentrion s’endort
    Explore les ondes australes
    Sillonne tous les méridiens
    Choisis au hasard ton chemin
    Tu y trouveras l’infini
    Et des myriades d'îlots qui
    Ne sont sur aucun parchemin

    Accoste-les l’ombre y est fraîche
    Et l’eau de source désaltère
    Où que tu sois l'âme s’altère
    Les cascades creusent leurs brêches
    Tu laisseras un peu de toi
    Mais emporteras une crêche
    Un peu de chaume sur le toit
    Et puis tatoué sur le bras
    Un écrit à l’encre invisible
    Car certains liens sont indicibles

    Le vent y vend des promesses qu’un fou
    Ne croirait pas
    Mais lorsqu’on veut véritable un bijou
    Et même s’il ne vaut qu’un demi-clou
    On y croit

    Il se dit qu’un réseau sous-marin les relie
    Et que la nuit les fées viennent choisir leurs proies
    Parmi le sable bleu des humains assoupis
    Qui s’endort anonyme et se réveille roi
#+END_VERSE
#+END_CENTER

* Anges hélés

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il est de tous connu qu’une sainte n’y touche
    Jamais sauf exception ou bien avec un ange
    Ou bien à la rigueur contre quelque indulgence
    Après tout elle en a matelassé sa couche

    De quoi tenir un siège ou garnir une table
    Au cas où ses instincts reprendraient le dessus
    Tout séraphin n’est pas modèle de vertu
    Puis certains canapés se font si confortables

    Si bien capitonnés qu’il lui prend des envies
    De laisser sans pudeur sur sa chair au goût tendre
    L’objet de son désir s'étirer et s'étendre
    Ne vous l’ai-je pas dit ? C’est un canapé-lit

    A rendre paresseux un caféinomane
    Juste pour le plaisir de tester les coussins
    Dans ce nid de douceur plus large qu’un bassin
    A l’onde chaleureuse aux langueurs de tisane

    ***

    Il est de tous connus qu’un prêtre déluré
    Est nommé au couvent pour calmer les émeutes
    Car qui donc oserait prendre de front la meute
    S’il n’est auparavant un peu immunisé

    Ca vaut mieux se dit-il que d'être défroqué
    Et puis s’il se fatigue il lui reste confesse
    L’oreille bienveillante aux folles pêcheresses
    Qu’il pourra consoler sans oser pardonner

    L’auréole ternie le rendant plus humain
    Assez pour embrasser beaucoup trop pour juger
    Ces coeurs qui lui avouent ne jamais marchander
    L’amour contre une vie de l’or un parchemin

    Aussi il les punit d’une main sur la croupe
    De quelques mots paillards débordant de tendresse
    Et si c’est vraiment grave il les prend pour maîtresse
    N'étant pas réfractaire à ce genre d'étoupe

    ***

    Vous l’aurez compris nos deux ailés se hélèrent
    Etant assez zélés pour sillonner la grève
    De coups de vent si forts que s’agitait la sève
    Comme une mer creusée dont les flots se resserrent

    Autour de l’intrusion saillante d’un navire
    Quand la vague furieuse est ravie de rouler
    De venir se frotter sur la quille d’acier
    Victorieuse écumante aux corps qui se chavirent

    Leur fougue remua si bien le fond marin
    Que l’on entend souvent échoué sur la plage
    Le ressac du tumulte au creux d’un coquillage
    Mélancolique écho d’hier et de demain

    Voici contée l’histoire aux envoûtants parfums
    D’une ange un peu coquine et d’un archange gris
    On dit qu’un crépuscule un beau soir les saisit
    Ne laissant derrière eux que l’ombre d’un embrun
#+END_VERSE
#+END_CENTER

* Le chant des vagues

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est un chant qui ruisselle au fin-fond de l’oreille,
    Un avant-goût du sel nacré des coquillages.
    Les embruns parfumés dessinent un rivage,
    Une île d'émeraude imbibée de soleil.

    Le vent semble répondre aux cris d’une bouteille,
    Testament d’un galion acculé au naufrage.
    Il allait, pourtant fier, dans l’océan sauvage
    Mais il dort dans l’eau noire, en un profond sommeil.

    Son ancre reposait au creux d’une lagune
    Où l’eau semblait la clef d’une porte céleste,
    Un vitrail incrusté de jade et de corail ;

    Mais il voulut la fuir par une nuit sans lune
    Pour épouser l’or et les coffres de l’ouest ;
    Jalouse, elle griffa d’une insondable entaille.
#+END_VERSE
#+END_CENTER

* Ni terre ni taie

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans l’archipel de nos naufrages
    Tu le crains qu’il a chaviré
    Ce vif éclair de notre rage
    Mais si la coque s’est brisée
    Qu’il bave sa carène à l’air
    D’où vient cette mélodie claire
    Cette voix qui me vient surprendre
    Si notre chaloupe est en cendre
    D’où ce chaland qui m’est si cher ?

    Nous sommes encore à l’ancrage
    Dans l’archipel de nos naufrages
    Vergues tapies dessous les hunes
    Et le sable orange y affleure
    Comme un haut-fond sort de la brume
    Comme un des sens noyé de pleurs
    La nuit languide des lagunes
    Comment pourrait-elle nous prendre
    Si notre chaloupe est en cendre ?

    Ils se prolongent les rivages
    Dans l’archipel de nos naufrages
    Entre rideaux d’eau et salines
    Le grincement sur le tillac
    Le roulis libre des hamacs
    La complainte des balancines
    Quel est ce vent qui vient s'éprendre
    Si notre chaloupe est en cendre
    De la timide brigantine ?

    Elle est tout au fond du cirage
    Dans l’archipel de nos naufrages
    Où chaque île flottante songe
    Qu’elle est plus qu’un vaste mirage
    Même si le soir elle plonge
    Si vite qu’on s’y peut méprendre
    Jusqu'à penser sortir d’un songe
    Mais d’où vient qu’on la peut comprendre
    Si notre chaloupe est en cendre ?

    Dans l’archipel de nos naufrages
    Sens-tu jaser la valériane
    Et l’orangeade des gentianes
    Et les cascades diaphanes
    Sous le jusant des bavardages ?
    Quelle est cette chanson si tendre
    Ce canon qui sait se reprendre
    Si notre chaloupe est en cendre
    Qui relie la terre aux nuages ?
#+END_VERSE
#+END_CENTER

* Qu'as-tu, ore ?

#+BEGIN_CENTER
#+BEGIN_VERSE
    S : L'épine de l’aurore irriguait l'églantine
    A : Quand je sus que ma soeur roulait comme un radeau
    T : Mais quel mage pourrait dissoudre son fardeau,
    B : Vers quelle cendre encor vogue ma brigantine ?

    S : Quand je vis son beaupré iriser l’horizon,
    A : Je ne pus retenir une brume maussade.
    T : Quelle foudre engloutit le parfum des muscades ?
    B : Un corail amarante embrase les bisons.

    S : Depuis mon coeur se grise au gré des balancines,
    A : Le déluge déploie ses vaporeux rideaux.
    T : Aux nymphes des coussins il bâtit des châteaux,
    B : La chandelle à la menthe encense l’aubépine.

    S : Et les arcs des sept cieux arpègent les saisons ;
    A : L'émeraude s'éteint dans l'écume sauvage.
    T : Mon frère est échoué sur la soie des naufrages ;
    B : Champagne, montre-moi d’autres constellations !

    S :

    L'épine de l’aurore irriguait l'églantine
    Quand je vis son beaupré iriser l’horizon,
    Depuis mon coeur se grise au gré des balancines,
    Et les arcs des sept cieux arpègent les saisons.

    A :

    Quand je sus que ma soeur roulait comme un radeau,
    Je ne pus retenir une brume maussade.
    Le déluge déploie ses vaporeux rideaux ;
    L'émeraude s'éteint dans l'écume sauvage.

    T :

    Mais quel mage pourrait dissoudre son fardeau,
    Quelle foudre engloutit le parfum des muscades ?
    Aux nymphes des coussins il bâtit des châteaux,
    Mon frère est échoué sur la soie des naufrages.

    B :

    Vers quelle cendre encor vogue ma brigantine ?
    Un corail amarante embrase les bisons.
    La chandelle à la menthe encense l’aubépine ;
    Champagne, montre-moi d’autres constellations !
#+END_VERSE
#+END_CENTER

* Le château de sable

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je ne suis qu’un château de fin sable mouvant
    Meublé par le reflux des vagues caressantes ;
    Leur écume s'échoue, douceur évanescente,
    Je me berce aux sanglots de leurs doigts languissants.

    Meublé par le reflux des vagues caressantes,
    Mes graines d’or se noient au hasard des courants ;
    Je me berce aux sanglots de leurs doigts languissants,
    Horizon d’un îlot, épave incandescente.

    Mes graines d’or se noient au hasard des courants,
    Où les emmènent donc les eaux tourbillonnantes ?
    Horizon d’un îlot, épave incandescente,
    Vaut-il mieux la cascade ou la mort d’un étang ?

    Où les emmènent donc les eaux tourbillonnantes ?
    La sirène exaltée se pâme dans le vent,
    Vaut-il mieux la cascade ou la mort d’un étang ?
    Je préfère la mer, sa complainte haletante.

    La sirène exaltée se pâme dans le vent,
    Boire le doux limon au creux de l’indolente !
    Je préfère la mer, sa complainte haletante :
    Je ne suis qu’un château de fin sable mouvant.
#+END_VERSE
#+END_CENTER

* Naufrage

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je me laisse couler au fin-fond du chagrin
    Dans l’océan sans fond d’un naufrage sans fin.
    Dans l’eau, nul édredon, nul parfum d'évasion,
    Qu’une vase évasive étranglant l’horizon.

    Autrefois je filais, toute voiles gonflées,
    Aspirant goulûment les parfums d'évasion,
    Mais la mer abrasive, instable et assoiffée,
    A lentement rongé le bois de flottaison.

    J’ai colmaté longtemps les brêches cristallines
    Mais vains sont les espoirs, les mensongers poisons
    Des plages alanguies où la vague câline
    Berce les rêves d’or de douces illusions.

    Je suis donc remonté, titubant, sur le pont
    La barre droit au large, et droit sur l’ouragan
    Pour un dernier défi, toutes voiles au vent,
    Sous les embruns grossis d’anciennes effusions.

    Mais vains sont les espoirs, les mensongers poisons :
    Mon vaisseau a sombré dans l'écume salée.
    Le vent se moque bien des anciennes passions,
    Des palettes flétries et des fleurs délavées.

    Longtemps j’ai surnagé, tel une épave inerte,
    Avant de me laisser plonger sous l’horizon.
    Depuis je descends dans ma cage d’algues vertes
    Loin de ces rêves d’or, des riches alluvions.

    J’ai croisé des beautés en robes translucides,
    Abusé de leur vin et perdu la raison ;
    Puis la neige en coton, la lumière livide,
    Et l’obscur engloutit jusqu’au dernier rayon.

    Encore, encore, encore et toujours plus profond,
    Dans l’océan sans fond d’un naufrage sans fin,
    Sans ballast, sans bouée, vaincu par l’attraction,
    Je me laisse couler au fin-fond du chagrin.
#+END_VERSE
#+END_CENTER

* Miroirs

#+BEGIN_CENTER
#+BEGIN_VERSE
    Parallèles miroirs, portes sur l’infini,
    Deux glaces ciselées d’un pur géométrique.
    L’irrégulier bani d’un ton teint et poli,
    Reste un fluide limpide, abyssal mirifique.

    Bain bleuté de couleurs, de l’eau sombre à l’eau pâle,
    Palette valonnée ainsi qu’un fond marin
    Lissé par le roulis incessant des opales,
    Nuances veloutées de profondeurs sans fin,

    Votre onde est étrange, qu’on y puisse à la fois
    Etre le fier voilier voyageant sur vos flots
    Et cette plage triste engluée dans la voix
    D’un vent qui toujours siffle et ne dit jamais mot.

    Un monde est pris au piège entre les deux machoires,
    Réflexion rotative, ronde de reflets.
    Son nom bientôt broyé entre ces dents d’ivoire
    N’est plus qu’un nuage dispersé dans l’abstrait.

    Y a-t-il un réel ou n’est-on qu’un mirage ?
    Sommes-nous les copies de nos propres répliques,
    Vide sans substance qui pourtant se propage
    Dans les colonnades d’un palais féerique ?

    C’est au crépuscule qu’ils se laisse entrevoir,
    Au croisement de deux univers impassibles.
    Sous les distorsions des vaguelettes du soir
    Ses arceaux déformés semblent presque accessibles.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
