
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Duos
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Lune pourpre

Vinie / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le beau matou luisant qui jouait des épaules
    Roulant de ses yeux ronds comme on guette une proie
    Les dents flambant d’envie, à dévorer les pôles
    Ses babines léchant songe à dîner en roi

    C’est une faim en soie, l'éveil d’un nouveau sens,
    L’envol du fauve en cage étourdi par l’aurore
    Qui rejoint d’un seul bond la vive argente et or,
    Et s'écrase souvent, et toujours recommence

    Quand l’appétit du jeu soumet cette insatiable
    La secrète, profonde et féline nature
    Impose sa langueur, griffant sa signature
    Sur la chair de ses peurs soupire l'âme en diable

    Sauvagine traquée, prédatrice en sueur
    Qui s’enfuit lentement en semant les indices,
    Elle sent sa présence invisible et complice,
    Devine dans la nuit sa fièvre, sa fureur

    Alors que deux instincts entrent en concurrence
    En l’esprit de chacun, le trouble gagne alors
    Se livrer en patûre ou décharner ce corps
    Etre proie ou chasseur, la rencontre ou l’errance

    Et c’est la patte armée de cette ambiguité
    Qu’ils ruèrent enfin, gueule ouverte, écumante,
    L’un sur l’autre et sans lin pour mieux dresser l’attente
    Toute rouge de rage et de pleurs alternés

    De ses crocs lacérés à ses veines cruelles,
    Il lape sans pitié sa gorge qui se plie
    Alors que sur ses flancs, elle arrache sa vie
    De l’amour et la mort, c’est l’orgie éternelle
#+END_VERSE
#+END_CENTER

* Solstice d'un jour éternel

Oulipo-t'au-feu / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Absolument magnifique, triste et sombre
    Enluminé des plus belles aurores boréales
    Un coup de vent tragique avale les décombres
    Et les Titans sans Dieux retiennent l’idéal

    La quiétude trahie par la sourde colère
    Déborde en mille peurs de mes cils aveuglés
    La paupière est en feu, et, telle une panthère,
    S’agite l’ombre éclair de ceux qui seront nés

    Les éléments s’accouplent à la Terre violée
    Pour créer dans le doute un Idéal perdu
    Les larmes des hurleurs s’engouffrent, torturées,
    Dans les gorges sans nom d’un espoir qui n’est plus

    Les aphones codas résonnent dans les âmes
    Avant de se mêler à la rage au chaos
    L’arpège se dissout dans l’onde d’une gamme
    La fin est un début, le reflet un écho

    Où se mire sans tain le futur sans passé
    Pour que les nouveaux-nés grandissent en liberté
    Qu'éclosent les couleurs bourdonnantes et fluides
    Et folâtres du jeune univers apatride
#+END_VERSE
#+END_CENTER

* Fanatique

Max / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je suis un fanatique à la plume rageuse,
    Dardant mille papiers de rimes orageuses,
        De larmes, d’amertume,
    Valsant sur les débris d’un art prostitué,
    Je crache sur les noms qui sont institués
        Au sommet de la rime !

    C’est en toi que je meurs, danseuse qui m'élève
    Loin des ébats grossiers des suceuses de rêves
        Aux relents de piquette ;
    Je laisse à l’art scénique, éphémère et vénal
    L'égout dégoulinant des corruptions banales,
        Je reprends l’immortelle.

    Je m’offre à la passion, tout entier, tout en pleurs,
    Je cherche l’horizon comme il trouvait Harfleur,
        Le dos pesant de doutes,
    Quand le soleil se pose en image constante,
    Je la donne à mon oeil, cette ombre persistante,
        Que les humains redoutent.

    Je couve dans mes mains ta flamme profanée,
    Et verse l’eau de vie de leurs larmes d’années
        Sur ta juste fureur
    Car qu’importe après tout s’ils méprisent l’essence,
    C’est bien cet absolu et lui seul que j’encense,
        Jamais ses parfumeuses.

    Mon esprit se confond avec celui des morts,
    Purgeant tout son bonheur dans un lac de remords,
        Pour souffrir sans arrêt
    Puisque la lourde peine est le seul combustible,
    Qui entretient ce feu, zéphyr irréductible,
        Au dessus des marais !

    C’est en siégeant parmi ces reliques infectes
    Qu’on admire le mieux les processions d’insectes
        Ovinés et médiocres,
    Où l’on jouit enfin des laids arts de galet
    Qui clament sans en rire : "oui c’est nous les boulets !"
        Emblèmes d’une époque.

    Il nous faut vivre à part, chercher un autre asile,
    Où nos vers lumineux n’auront pas que l’exil
        Pour seule perspective,
    Mais nous retournerons sur chaque sol foulé,
    Bottés de plumes d’or pour ainsi défouler,
        Nos mots hors des enclaves !

    Tendant nos désaccords, majeurs je le confesse,
    Nous regagnons ces lieux épris des neufs déesses
        Où le sceptre est la lyre ;
    Fuir loin de l’odieux, fuir les viles infamies,
    Vers ces paradis clairs où une nymphe amie
        Sert les vins qui nous grisent !
#+END_VERSE
#+END_CENTER

* Reine essence

Ambre / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je t’aimais, le sais-tu, dans les plaines d'Assouan
    Dans les vapeurs migrées de jungles halogènes
    Dans les heures saignées à l’opium de nos gènes
    Je t’aimais au shilom de ton encre Safran !!

    Au coeur de la toundra, dans les déserts glaciaires
    Voilés par la fureur de blizzards si épais
    Que les flocons flambaient d’un désir incendiaire,
    Sous un sorbet de neige et de gel, je t’aimais.

    Ton épice en mon sein comme sel aux morsures
    Tes margelles d’osier à tes mèches d’iode
    Oh combien je prisais d’en lécher les blessures
    Pour fumer la frayeur de ton âme en exode !

    Combien de sables gris n’avons-nous enivrés
    Quand nous étions dauphins échoués dans nos songes ...
    Combien de cieux cajuns et de langueurs poivrées
    A l’heure où dans les ports l’ombre des mâts s’allonge ?

    Je t’aimais, le sais-tu, dans les salons antiques,
    Dans nos écrits voilés de jeux épistolaires,
    Telle George à Alfred, rusant les sémantiques,
    Je t’aimais dans les plis des plumes angulaires !

    Et si quelques bémols d’une valse musette
    Nous laissaient quelquefois l’un de l’autre orphelins,
    Nos encriers saignaient le temps d’une grisette,
    Tout n'était qu’un prétexte à filer le satin.

    Et tes cris et tes pleurs et tes nages indiennes
    Refluant les ressacs, à bord d’un Nautil'Us
    Emportaient nos écarts, diérèses et hiatus
    Sur un radeau moulu de laves obsidiennes

    Un volet ajouré comme un château de cartes
    Tatouait sur tes reins nos gravures anciennes
    Et nous nous retrouvions à l’abri des persiennes,
    Hors de jet des clameurs aux silences opaques.

    Je t’aimais, le sais-tu, avant notre naissance
    Avant que nos deux noms sur les fronts baptismaux
    Ne gravent de leur sang les pignons de nos maux !
    Je t’aime comme on aime en toute âme et constance !

    Je t’aimais, tu le sais, avant qu'Eve eut naissance
    Et le sérum en nous précédait le venin,
    La réconciliation précédait le chagrin,
    Je t’aime comme on aime en toute âme et constance !
#+END_VERSE
#+END_CENTER

* Vapeurs d'alcool

Amandine / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    À l’ombre de tes yeux surnagent des soleils,
    Laisse-moi de ton ciel être l’humble persienne :
    J’infiltrerai l’ennui d’un rayon bleu-vermeil,
    Réveillant d’arcs-en-cils nos prières anciennes.

    As-tu jamais rêvé d’une nuit sans aurore
    Où se noient dans l’oubli les désespoirs latents ?
    Laissant flotter là-haut les oiseaux qui pérorent,
    Nous serions à l’abri de tous leurs ouragans.

    Chaque jour notre amour est une turbulence
    Vaguement étouffée sous les pages d’un lit.
    Y puises-tu le sel d’impétueux silences,
    Brillant sans déchirer la voile qui nous lie ?

    Même les cris jaloux n’ont ici plus de prise,
    Glissant sur les je-nous de nos âmes éprises,
    Avant d'être engloutis par l’extase sereine.

    Puisqu’il faut succomber au vibrant équilibre,
    Au seuil vertigineux des passions éoliennes,
    Insufflons la vapeur à nos lèvres de givre.

    La lumière est plus belle au prisme des fontaines
    Et son sommeil léger flirtant sous les abysses
    Rallume sans un bruit le souffle de nos cuisses.
#+END_VERSE
#+END_CENTER

* Brasero

Vinie / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sur la courbe du temps d’un rire bafouée
    Que ta langueur éprise en roulements m’enlace
    Quand jaillira le vers de la chair dénouée
    Il brisera les murs de nos prisons de glace

    A tes braises fondue, mon armure de cire
    Se mêle en doux bouillons aux effluves musquées
    L'étuve suffoquée par le feu du désir
    Allume des frissons sur nos peaux déchaînées

    J’aspire la vapeur de ton cou qui quémande
    Que s’oublient les tabous, que s’infuse un baiser
    Et je boirai ta lèvre en morsures gourmandes
    Jusqu'à ce que ton coeur haletant soit grisé

    De fièvres à soupirs, tant d’envies se confondent
    Nos corps en entrelacs s’invitent à dîner
    L’emprise de l’inné doucement nous innonde
    Eperonnant à vif nos instincts confinés

    Réinventons les sens de vibrants sortilèges
    En potions d’essentiels, sauvages abandons
    Laisse rugir l'écume et dégrafe le piège
    Qui bridait la panthère au seuil de l'édredon

    Enfin que l’alchimie infinie, extatique
    Nous empoigne les reins d’une ivresse éthérée
    Pour mieux dompter l’iris dans nos yeux cycloniques
    Et noyer la pudeur dans le raz-de-marée
#+END_VERSE
#+END_CENTER

* Apogée

Flore / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je ne souffrirais point si j'étais près de toi
    A regarder le temps s'écouler de tes yeux
    Et si quelque nuée venait voiler nos cieux
    Nous nous envolerions au-dessus de ses draps

    Aux sources du soleil nul serpent n’est lové
    Juste l’air, l’eau légère, et son cours sinueux
    Dont l’accord envoûtant fredonne impétueux
    L'élégie assoupie à l’abri du névé

    Virtuose serein à libre inspiration
    Donne vie à mon ombre étourdie en sommeil
    Chante ta peine amie ta harpe est le fleuron
    Le buisson prolifique où mûrit la groseille

    La fée livra jadis au fond de ton berceau
    Cette rose épanouie aux pétales si doux
    Qu’ils frôlent mes pensées d’une offrande en ruisseau
    Dont l’arpège fleurit ton beau visage flou

    J’aspire au violon qui danse avec la lune
    Au son habile et clair ivre de tes pupilles
    Valsons jusqu'à minuit sous le croissant des dunes
    Baignés par la douceur qui naquit aux antilles

    Nos plaies se fermeront dans cette onde apaisante
    Laissant place à la fièvre où la soie s'éparpille
    Et des hauts cils en cieux à la saison quadrille
    S'éveillera la joie de l'écho qui nous hante

    Si le levant serein partage nos silences
    Le carrousel vainqueur prince libre penseur
    Voyant l'âme commune ouvrir son champ immense
    Enlacera l’audace en tout bien tout bonheur

    Puissent nos soupirs d’aise abreuvés de lumière
    Fondre comme un glaçon sur une peau brûlante
    Fondre comme un faucon dans la moiteur des serres
    Fondre ... puis rebondir sur la cime éclatante

    Eperdus dans le rêve aux flocons cristallins
    Nous nous envolerons plus haut que la tempête
    Là où rien ne résiste aux éclairs argentins
    Où chaque heure ouvre un bal d’une éternelle fête
#+END_VERSE
#+END_CENTER

* Un billet au guichet de Morphée

Sabaobab / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    De la douceur,
    même s’il faut fermer les yeux,
    même si les images lacèrent
    les paupières,
    l’inconscient,
    et balai le subconscient...

    Laisse moi rêver,
    offre moi le manège,
    ce rêve, portes ouvertes
    sur la galerie d’un songe de bohème,
    fantasmagorique,

    sans nos fantaisies,
    les rêves embrumés,
    offre moi les vapeurs,
    quand il fait plus chaud,
    là haut ...
    Fantasme agorique ...

    Sur les monts des méditations,
    dans les virages des vallons du zen ,
    entre l’encens et l’organza,
    entre ciel et terre...

    Je tutoierai les anges,
    leur demanderai de répandre,
    nos envies en toiles d’infini,
    la nuit sera nos couvertures,
    le firmament sera au bout des doigts
    de chaque étoile naîtra une plume,
    voltigeant au hasard des courants,
    ou flotte les pollens d’une liberté assoiffée,
    ou le roseau espère toujours,
    toucher le lotus au milieu du ruisseau.
#+END_VERSE
#+END_CENTER

* Ainsi soient-ils

Amandine / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans l'écrin velouté d’un coffre en acajou
    J’ai trouvé l’enivrant parfum de la lavande
    Un piment dévorant puis au coeur d’un bijou
    Un feu sombre qui couve et une fleur d’amande

    J’ai gardé un trésor qui s'était autrefois
    Dans un champ au soleil accroché à ma robe
    Un épi gorgé d’or, enveloppé de soie
    Depuis la volupté des grains d’orge m’enrobe

    Quand les vagues du soir jouent dans les plis du blé
    La plage aussi flamboie des soupirs qu’elle héberge
    Aimes-tu toi aussi d’un zodiaque ensablé
    Apaiser les tourments ardents qui te submergent ?

    C’est par ton eau suave éclaboussant la rive
    Par ta brise légère et ton chant enfiévré
    Que la terre empourprée du désir qui ravive
    Absorbe ta liqueur pour un plus bel engrais

    Ses neiges satinées se fondent en cascade
    Sur le lit du printemps qui geint sous l’indécence
    Quand son corps se dérobe et quand son coeur s'évade
    C’est un billet retour des lentes délivrances

    Au coeur de son volcan la braise incandescente
    Quitte soudain son nid et jaillit dans les airs
    Et la lave brûlante amorce sa descente
    A présent libérée s’en va mourir en mer

    Ses cheveux sur ses seins entremêlés aux siens
    Le tumulte apaisé les berce de vapeurs
    Quand soudain un frisson réveille leurs bassins
    Ils repartent nager sur leurs peaux en sueur

    Ils ont toujours en eux la faim qui les tenaille
    La dévorante envie des chaudes gourmandises
    Car leur folle passion n’est pas un feu de paille
    Plus elle est consommée et plus le feu s’attise
#+END_VERSE
#+END_CENTER

* Ciel de lit

Ambre / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le murmure du songe est une douce bise
    Qui souffle vague et floue sur l’ombre de la nuit
    Au sommeil reposant sur de frêles banquises
    Inlassable il revit les souvenirs enfuis

    Le voile est déchiré sur le jour qui rappelle
    Silhouettes nacrées aux démarches paisibles
    Sur fond d'écran lustré l’opaque se révèle
    Déliant les liesses en tourmentes fusibles

    Comme une lassitude il traîne son ennui
    Il déroule, fardé, sur les paupières closes
    Le diaphane et le noir, le silence et le bruit
    L’aurore est son écho, sa couleur est le rose

    Le murmure du songe est la brise suave
    Qui caresse la peau d’une aile diamantée
    Au retour bienheureux d’un avion, ou l'épave
    D’un train sur le départ, quai des amours blessées

    Il chante la chaleur des coussins de tendresse
    Les abandons livrés sur des barils d’amour
    Fredonne au jade clair l’orphéon des ivresses
    Ou les belles saisons d’un billet sans retour

    Injure d’un délit à raisonner l’instinct
    Dans l’envers du décor au blues d’un goéland
    La flamme consommée d’un seul sanglot s'éteint
    Au murmure du songe éperdu dans l’instant

    Les remords, les regrets, souffrances de l’après
    Sonnent à cinq cents lieues en graines diluviennes
    La pluie qui clapote en claquant sur le pavé
    Couvre la voix flouée aux allées bohémiennes

    Le chasseur aux aguets de la biche aux abois
    Laisse l’oeil à sa larme à l’orée d’un espoir
    Quand son fusil défait aux sources de l'émoi
    Explose en gerbe tendre au baume de l’ivoire

    L’océan embleui aux confins de ses rives
    Etend son vague à l'âme autour de l’horizon
    Le soleil et la lune en éclipse furtive
    S’alanguissent au loin du ciel de la raison

    Les songes chuchotés se glissent sous les draps
    Poétiques fragments tissés de vers sincères
    Par les rimes fondues d’ici en au-delà
    Aux plumes des duvets flottant dans les éthers

    Le miroir s’est cassé, le jour vient d’apparaître
    Sur ces heures bercées de minutes trop brèves
    Mais leurs paillettes d’or en débris font renaître
    Des milliers de facettes ... brillant d'éclats de rêves ...
#+END_VERSE
#+END_CENTER

* Lune et Soleil

Ambre / Chimay

** Version originale

#+BEGIN_CENTER
#+BEGIN_VERSE
    Que vois-tu donc la nuit sous ta lune jolie,
    Quand j’attends le soleil au creux de mes nuits blanches ?
    Est-il vrai qu’elle brille pleinement ou demie
    Et qu’elle peut défaillir d’une éclipse trop franche ?

    Apprends-moi à ta lune
    Je serai ton soleil

    Je la vois pleinement absorber nos envies
    Quand fusent de son ombre nos silhouettes fluides
    Et je la vois aussi s'évanouir à demi
    Quand nos pulsions succombent à nos regards languides

    Je veux être ta lune
    Apprends-moi ton soleil

    Je vois dans son ciel bleu un rayon d’indolence
    Diffusant l’irraison de la nuit des amants
    Pour souvenir mon âme au zeste d’insouciance
    M’incitant à muser, rieuse, au firmament

    Que fais-tu à ta lune
    Quand je suis au soleil ?

    Je me drape aux lueurs des étoiles flottantes,
    L’espoir de te revoir fait danser leurs chandelles
    Et je leur souffle aux joues ma flamme incandescente
    Qui consume la nuit diamantée d'étincelles

    Que fais-tu au soleil
    Quand je suis à ma lune ?

    Je me pare de l’or qu’il m’accorde en offrande
    Pour que tu me croies reine du monde de l’amour
    Et que tes lèvres aux miennes, avides et gourmandes
    S’emparent en pirate de mes plus beaux atours

    Attends-moi à ma lune
    J’irai à ton soleil

    Embrassons l’irréel pour nous rejoindre enfin
    Mouvons en immuable nos rêves chimériques
    De ton monde jusqu’au mien, allons de l’autre à l’un
    Pour raviver l’aura des amours séraphiques

    Je suis à ton soleil
    Je t’attends à ta lune

    Volons la voie lactée, fuyons vers nos demains
    Les Cieux édifieront notre éclatante éclipse
    Et nos astres enlacés déchaîneront leurs liens
    Piégeant l'éternité pour la prendre en ellipse
#+END_VERSE
#+END_CENTER

** Version retravaillée

#+BEGIN_CENTER
#+BEGIN_VERSE
    Que vois-tu à ta nuit sous la lune jolie
    Quand j’attends le soleil au creux de mes nuits blanches ?
    Est-il vrai qu’elle luit entière ou à demie
    Qu’elle peut défaillir d’une éclipse trop franche ?

    Apprends-moi à ta lune
    Je serai ton soleil !

    Je la vois pleinement absorber nos envies
    Quand de l’ombre ont fusé nos silhouettes fluides
    Je la surprends aussi s'évanouir à demi
    Quand se plient nos pulsions sous nos regards languides

    Je veux être ta lune
    Apprends-moi ton soleil !

    Je vois dans son ciel bleu un rayon d’indolence
    Diffusant l’irraison de la nuit des amants
    Pour souvenir mon âme au zeste d’insouciance
    M’incitant à muser rieuse au firmament

    Que fais-tu à ta lune
    Quand je suis au soleil ?

    Je me drape aux lueurs des étoiles flottantes,
    L’espoir de te revoir fait danser leurs chandelles
    Puis je leur souffle aux joues ma flamme incandescente
    Qui consume la nuit diamantée d'étincelles

    Que fais-tu au soleil
    Quand je suis à ma lune ?

    Je me pare de l’or qu’il m’accorde en offrande
    Que tu me croies la reine aux Iles de l'Amour
    Que ta bouche corsaire à mes lèvres gourmandes
    S’empare en flibustier de mes plus beaux atours

    Attends-moi à ma lune
    J’irai à ton soleil


    Embrassons l’irréel pour nous rejoindre enfin !
    Mouvons vers l’infini nos rêves chimériques !
    Ton monde jusqu’au mien, allons de l’autre à l’un
    Pour raviver l’aura des amours séraphiques !

    Je suis à ton soleil !
    Je t’attends à ta lune !

    Volons la voie lactée ! Fuyons vers nos demains !
    Les Cieux édifieront notre éclatante éclipse
    Nos astres enlacés déchaîneront leurs liens
    Piégeant l'éternité pour la prendre en ellipse !
#+END_VERSE
#+END_CENTER

* La barque de l'amour

Ghislaine / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    La barque de l’amour gondole vers l’enfer
    Quand le gel est de cendre au virage des brumes
    C’est l’esquif de velours aux dédales de lierre
    Qui forge les sanglots de coups sourds sur l’enclume

    A son bord l'âme sombre et cotonneuse
    Aux souvenirs enchassés dans un ciel nébuleux
    Accomplit le funeste voyage vers l’ensorceleuse
    Dont le spectre glaçant les flots est maître des lieux

    La barque de l’amour étrangle la lumière
    Quand le voile est écran et sépare l'écume
    Combien de ces folies a-t-elle assis sous pierre
    Cette ombre en robe noire écrasée d’amertume

    Elle a fait naître ces larmes pourpres au regard éteint vers le néant
    Et plonger les amours ensevelis vers les abysses
    Dans ce monde ébène où la mort lance son venin malfaisant
    La barque de l’amour pourra t elle déjouer le maléfice

    Car déjà le soleil s’enfuit sous l’horizon
    Et les coeurs naufragés vers l’ouest qui s'éteint
    Courrent sans s’arrêter au bord de la raison
    Mais en vain l’astre d’or brûle ce qu’il étreint

    Il perçe de ses rayons les ombres fuyantes et mystérieuses
    Ne laissant planer que le froid et le souffle de la peur
    Les souvenirs peuvent ils renaîtrent en cette vie ténébreuse
    Sous les eaux glacées lancinantes et leurs cri qui demeurent

    La nuit longue et sinistre étouffe le brouillard
    L’elfe ne chante plus et la magie des fées
    Se tait quand tout-à-coup un fin rayon d’espoir
    Frappe leur dos transis d’une aurore dorée

    Les ténèbres et la lumière auréolés d’une beauté diaphane
    Eloignent l’océan ensanglanté et emportent les enfers
    La barque d’amour esquisse un sourire au firmament et témoigne
    Qu’un souffle trop pesant entraîne parfois un monde de chimères

    C’est toujours du côté d’où tu ne l’attends plus
    Qu’il jaillit du chagrin ce visage attendri
    Pour déchirer la pluie d’un désir assidu
    Il suffit d’un regard céleste et tout est dit
#+END_VERSE
#+END_CENTER

* Dans la chaleur du crépuscule

Isa / Chimay

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le ciel azur serein commence à se dorer
    Enflammant l’horizon de sa douce poitrine
    Ainsi qu’un océan de désirs cadencés
    Des vagues de braises haletantes l’animent

    Les rayons du soleil commencent à se transformer
    Illuminant ainsi le monde de ces douces couleurs
    Faisant apparaître la blancheur de mon corps allongé
    Les courbes de cette femme dormant dans la chaleur

    Dans sa peau vallonnée son âme s’est glissée
    Filet d’une fontaine claire et langoureuse
    Des frissons trahissent sa voix tumultueuse
    Au souvenir de quelques étreintes incontrôlées

    Des sursauts la dénoncent, la peau frémissante
    Ses songes tourment sa vie dès lors inexistante
    Son visage de cire tel un mannequin de vitrine
    Caractérise sa tristesse ainsi que sa douceur féline

    L’onde de sa fièvre sous la soie se propage
    L’obscurité complice embrume ses désirs
    C’est un feu tamisé qui redevient sauvage
    Un soleil intérieur qui brûle et qui transpire

    Brûlant comme sa soif il se matérialise
    Et la nuit entière mélange leurs ardeurs
    N'était-ce qu’un rêve ? Pourtant à l’aube grise
    Sur le lit saccagé flotte encor son odeur
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

