
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Nocturnes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Effet d'hiver

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le ciel dormait dans son sommeil qu'éclairait d’ombre à son chevet
    La lune opale, ô pâle lune, astre ajouré tant de visages
    Que la nuit berce, aussi la brume, aussi la brise et ses reflets
    Qui nous renvoie vers un sommeil agité de givre hier sauvage.

    Un seul cristal d’orage, un seul, et qui rêvions nous d'être sages
    Sommes à chatouiller la plume, à colorier l’autre lumière,
    Couchés sur elle, elle et ses pleurs, elle et ses colères princières,
    Elle en cristal au coeur d'écume, ancestral enfant de l’orage.

    Les jeunes fleurs aiment les fleurs si les abeilles les guêpières
    Si relevées, mais sans arôme, y brûle un thé mais sans parfum
    Rien ne transpirera des flots qu’un bouc satyre et émissaire
    Comme on en livre savoureux dans les vieux livres de satin.

    Le songe ici guide son cours, ici la source est sans caprice,
    Le ciel s’endort sur du velours que ne se trouble le silence
    Dans un sommeil de peu de bruit ni de romanesques romances.

    Le rêve est pur, épris le rêve, un ange épris chante un solstice
    A ne plus aimer que le rire, à ne plus rire que d’aimer
    Jusqu'à la pluie s’il est d’hiver et jusqu’aux sourdes nuits d'été.

    Tapis dans l’ombre, un bleu tapis volant et or verse le soir,
    Il joue un air de rien, de flûte, à pétiller, fut-ce d’y croire
    Aux yeux de soie grise et dodue dans l’ombre grise du léthé.

    Un seul cristal s’il est d’hiver vous improvisera dans l’onde
    Que la nuit berce et ses reflets la lune ajourée de fleurs blondes,
    D’eau fine en fleur, d’aurore enfuie, de noeuds d'épine inachevés.
#+END_VERSE
#+END_CENTER

* La Lune fauchée

#+BEGIN_CENTER
#+BEGIN_VERSE
    - Lune, Reine des nuits, qu’attends-tu pour briller ?
    - Je suis désargentée, la fin du mois approche !
    Votre calendrier trop lent vide mes poches
    Et pour me rattraper je n’ai que février.

    Mes croissants sont éteints, je me sens nue et moche,
    Répondez mes soleils, où êtes-vous passé ?
    Là, tu vois ? Plus personne. Ils m’ont laissé tomber.
    - Non, les rêveurs sont là, ils admirent tes roches.

    - Tu te moques l’ami, mais sais-tu ce que c’est
    L’ivresse des regards, étincelants reflets
    Qui se posent sur toi ? Le sais-tu mon ami ?

    - Oui je le sais princesse et je sais la tristesse
    Et l'étrange beauté des divines faiblesses ...
    Souris, c’est si charmant quand ta joue s’arrondit.
#+END_VERSE
#+END_CENTER

* Minou le matou

#+BEGIN_CENTER
#+BEGIN_VERSE
    Des chats j’ai appris la paresse
    Et des minettes les câlins
    Je dois dire que leurs caresses
    M’ont rendu dingue du satin

    Si je suis chaud comme un lapin
    La faute en est à ces déesses
    Des chats j’ai appris la paresse
    Et des minettes les câlins

    Quand dans l’alcôve des tigresses
    J’entre furtif comme un félin
    Elles ronronnent en souplesse
    Griffes dehors dans leurs coussins

    Je dois dire que leurs caresses
    M’ont rendu dingue du satin
    M’ont rendu dingue et je ne cesse
    De réclamer d’autres festins

    Et je miaule d’allégresse
    Lové au creux du baldaquin
    La faute en est à ces déesses
    Si je suis chaud comme un lapin

    J’aime la chaleur de leurs seins
    Sous mon corps gonflé de tendresse
    Et j’ai le poil qui se redresse
    Dès que se cambrent leurs bassins

    Quand dans l’alcôve des tigresses
    Lové au creux du baldaquin
    Je glisse avec délicatesse
    Dans le velours de leurs écrins

    Dans le velouté de leurs reins
    Je bois le nectar de leurs tresses
    C’est mieux que le lait que le vin
    Le miel doré de mes maîtresses

    Au nid douillet de mes faiblesses
    Je m’incruste comme un poussin
    J’aime la chaleur de leurs seins
    Mais gare à celle qui me blesse

    Je m’enfuis au petit matin
    Par les gouttières de l’ivresse
    Libre sans collier ni sans laisse
    A la croisée d’autres destins

    Museau recensant les parfums
    Moustache lustrée en finesse
    La patte assurée du chemin
    Je glisse avec délicatesse

    Vers les balcons de ces déesses
    Dans le velours de leurs écrins
    Des chats j’ai appris la paresse
    Et des minettes les câlins
#+END_VERSE
#+END_CENTER

* Lune hivernale

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai été dormir sur la lune
    Il y fait moins froid qu’ici-bas
    Le vent glacé de la rancune
    Ne vient pas geindre sur les toits

    Quand la neige chasse la brume
    Il n’y a pas meilleur sauna
    Que la caresse de ma brune
    Sur l’oreiller et c’est pourquoi

    J’ai été dormir sur la lune
    Oublier la gifle du froid
    Nul risque d’attraper un rhume
    Dans l'édredon de ses dix doigts

    Depuis j’ai parcouru les dunes
    Jusqu’aux oasis de son choix
    C’est le paradis des agrumes
    Un bain de soleil et de soie

    Où de chaudes vapeurs d'écume
    Arrosent la plage de joie
    Nul risque d’attraper un rhume
    Il n’y a pas meilleur sauna

    Quand la neige chasse la brume
    Que l’amour près d’un feu de bois
    Et la caresse de ma brune
    Sur l’oreiller et c’est pourquoi

    Je n’attends pas la pleine lune
    Pour me régaler dans ses bras
    Je m’en vais cajoler ma brune
    Dès que les dents grincent de froid

    L'été est gravé sur les runes
    Un bain de soleil et de soie
    La face cachée des lagunes
    Et tous ses croissants sont pour moi
#+END_VERSE
#+END_CENTER

* D'une femme naît un poème

#+BEGIN_CENTER
#+BEGIN_VERSE
    D’une femme naît un poème
    Dis le sens-tu toi mon coeur battre
    Aussi brûlant qu’un café crème
    Il n’est plus l’heure d’en débattre

    Qu’y faire au ciel nous étions quatre
    J’en oublierais tous mes problèmes
    Douceur du vent tes seins de crème
    L’heure est venue de s’y ébattre

    Nuit de café lune de miel
    Fondez sur la cuillère en nacre
    Loin de nous les froides prunelles
    Je suis lassé de tout combattre

    D’une femme naît un poème
    Et si j’avais assez de temps
    Je te dirais combien je t’aime
    A en épuiser tes vingt ans

    Mais mille ans n’y suffiraient pas
    Un frisson c’est l'éternité
    Une seconde dans tes bras
    C’est un fleuve démaquillé

    Le temps n’est plus qu’un lac doré
    Baigné de soleil et de pluie
    La neige et la fleur se marient
    Sur un rond d’eau improvisé

    De ces guirlandes d’harmonie
    Il ne m’est plus qu’un diadème
    Aussi brûlant qu’un café crème
    Clair comme une étoile qui brille
#+END_VERSE
#+END_CENTER

* Demi-lunes

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sa compagne était blonde
    Sa compagne était brune
    Deux moitiés d’une lune
    Incendiant la nuit sombre

    D’une passion profonde
    Qui baignait la lagune
    Sa compagne était brune
    Sa compagne était blonde

    Deux moitiés d’une lune
    Lait doré café sombre
    Les nuages qui rôdent
    Abritaient leur écume

    Qui rosissait la brume
    D’une passion profonde
    Que leur amour allume
    Sous les vapeurs qui rôdent

    Mince voile d'écume
    La lumière et son ombre
    Unies en demi-lune
    Lait sucré café sombre

    Sa compagne était blonde
    Miel coulant sur les dunes
    Caramel qui inonde
    L’horizon qui s’allume

    Sa compagne était brune
    Une flamme profonde
    Une étoile dans l’onde
    D’une houle nocturne

    Et les deux vous embrument
    Il faut voir l’hécatombe
    Qui voudrait par les runes
    Se glisser dans la ronde

    Deux croissants qui succombent
    Deux versants d’une dune
    Deux moitiés d’une lune
    Incendiant la nuit sombre
#+END_VERSE
#+END_CENTER

* Que sont mornes ces filles

#+BEGIN_CENTER
#+BEGIN_VERSE
    Que sont mornes ces filles
    Dont les yeux seuls scintillent
    Laisse glisser en bas
    Toute la pacotille

    Fi donc des faux éclats
    De la verroterie
    Je ne veux point d'ébats
    Cerné de pacotille

    Enlève moi ce teint
    Ce rouge et ce crayon
    Cet entêtant parfum
    Ces bijoux de salon

    Que ta beauté soit bue
    Sans aucun artifice
    Je te préfère nue
    Riche de tes délices

    Je veux que cette nuit
    Ton odeur animale
    Seule emplisse le lit
    De nos fureurs bestiales

    Ainsi qu'à l’aube blême
    Ce soit ta peau qui brille
    De sueur et de crème
    Emblèmes de la vie

    Je veux à l’aube tiède
    Enfièvrer tes pupilles
    Que tout en toi me cède
    Que nos deux âmes crient
#+END_VERSE
#+END_CENTER

* Les torches

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les secrets ténébreux que cèle, silencieuse,
    L'épaisse profondeur des fosses abyssales,
    Antichambre en sommeil de chimères affreuses
    Où le phosphore luit de nos peurs ancestrales,

    Le rire cristallin des sirènes d’argent
    Dansant dans le château d’une épave engloutie,
    La lumière diffuse et bleutée qu’incendie
    Une orgie arc-en-ciel de poissons éclatants,

    L’océan qui respire et s'échoue sur la braise
    D’une plage empourprée cendrée de sable blanc,
    La lune qui s’enlise et doucement apaise
    La morsure du sel et l’orage dément
    Qui lance son écume à l’assaut des falaises,

    Le murmure assoupi des joyeuses cascades
    Dont l’eau jase et s’endort lentement, sans un cri,
    Le tumulte aérien des fraîches embrassades
    Et les flots enivrés chantant leurs sérénades
    Lorsque deux confluents gagnent un même lit,

    Les pinceaux du soleil auréolant l’ombrage
    De rosaces dorées aux franges des feuillages
    Et de colonnes de lumière,
    Le saule liseré de rideaux de dentelle,
    La nocturne lueur des mariages charnels
    Scellés à l’orée des clairières,

    Le vent avide qui s’engouffre
    Dans les cratère désolés,
    La montagne qui hurle et souffre
    De tous ses cols accidentés,
    Le glacier torturé qu'écorche
    L’arête effilée de la roche
    Le long de ses flancs mentholés

    Les lacs lissés par le silence
    Où les cirrus prennent la pose
    Se colorant de noir, de rose,
    Se regorgeant de leur prestance,
    Et les sommets immaculés,
    Ces pièges de l'éternité
    Que nul pas n’oserait souiller
    Sens en espérer la clémence

    Plus loin encor, le bleu du ciel,
    Le vertige immense du vide,
    Quelques planètes impavides
    Dans leurs orbites éternelles,
    Un soleil pâle et affaibli
    Qui n’est déjà qu’une étincelle,
    Des étoiles, hors de leur lit,
    Fonçant affolées dans la nuit
    Dans les nébuleuses d’or vert
    Et les averses d’univers,

    Tout cela je l’ai vu dans tes beaux yeux félins,
    Ces grands yeux lumineux tombés d’une comète,
    Ces caresses de soie, sortilèges célestes,
    Qui sabraient de leurs torches l’horizon éteint
#+END_VERSE
#+END_CENTER

* Anse amble

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’amour vole au-delà des mots
    Et c’est leur magie de le dire
    Le paradoxe est dans l'écho
    L’amour vole au-delà des mots
    Léger léger comme un soupir

    Virevolte le sans le dire
    Le secret s'écrit blanc sur blanc
    Pour mieux le crier sans l'écrire
    La plume est muette et s'étire
    A la naissance de l’orient

    Car c’est la folie ce je t’aime
    Comme un remous brise les rangs
    Passé le jeu la raison même
    C’est de la folie ce je t’aime
    Mais c’est plus beau mais c’est plus grand

    Cieux dans les yeux, yeux dans les cieux
    Plus rien là-haut n’est sacrilège
    On peut même écrire « nous deux »
    Sans que le doute venimeux
    Ne nous paralyse de pièges

    Brûlant tout ce qui nous sépare
    Nos regards ne mentiront pas
    Et comme vierges l’un de l’autre
    Nous referons l’amour en pluie
    Pour la première fois
#+END_VERSE
#+END_CENTER

* Problème a deux corps

#+BEGIN_CENTER
#+BEGIN_VERSE
    Si nous allions là-haut, là-haut vers les étoiles
        Aller voir si le ciel
    Contient autant d"éclat que tes sombres prunelles
    Contient assez de vent pour soulever ton voile ;

    Si nous allions très loin, plus loin que l’horizon
    Aux confins de la voie lactée
    A la recherche d’une autre constellation
    Dont les neiges te seraient un collier ?
    Si nous allions très loin, plus loin que l’horizon

    Chevaucher de planète en planète
    Agrippés aux crins d’une comète ?
    Et puis, durant de longues heures,
    Propulsés par nos émotions,
    Explorer les trois dimensions
    De l’amour en apesanteur.

    Nous irions enlacés en galaxie spirale
    Essayant dans la nuit des danses sidérales
    Sur une piste d’anneaux planétaires ;
    Sous le vague regard des géantes gazeuses,
    Des astéroïdes et des ourses frileuses
    Dans une transe interstellaire.

    Si nous allions là-haut, plus haut que de raison
    Jusqu'à n'être qu’un point dans les replis du soir,
    Jusqu'à n'être qu’un grain de désir dans le noir ?
    Ainsi, nul ne verrait le tourbillon
    De notre folie giratoire
    Lorsque j’enlèverais ta ceinture d’orion.

    L’un de l’autre les satellites,
    Nous serions chacun en orbite,
    Tournoyant de plus en plus vite,
    Et puis, durant de longues heures,
    Nos corps au bord de la fusion
    Nous explorerions l’attraction
    De l’amour en apesanteur.

    Nos ébats creuseraient dans la nuit un sillage
    De remous turbulents
    A chaque mouvement ;
    Nos ondes, dans la nuit, laisseraient un message
    Qui irait s'échouer sur de lointains étangs.

    Et lorsque le point d’orgue de nos convulsions
    Atteindrait dans de doux frissons
    De parallèles univers,
    Nous irions au-delà de l’espace et du temps
    Craquer une alumette au fond des flots béants,
    Extraire du cosmos un aveuglant éclair.

    Et dans notre étreinte furieuse,
    Astres et soleils spectateurs,
    Météores et nébuleuses
    Verraient naître une étoile soeur ;
    Propulsés par la distorsion,
    Nous irions loin vers l’horizon
    Joindre nos deux corps en fusion,
    Enflammer d’amour d’autres fleurs.

    Si nous allions là-haut, là-haut vers les étoiles ?
#+END_VERSE
#+END_CENTER

* Cinéma

#+BEGIN_CENTER
#+BEGIN_VERSE
    A la lumière écrue
    Du bar de la télé
    Quand tu bois du léthé
    Et de l’ale un peu pâle
    Que ton dernier écu
    Te dit viens on détale

    Quand tu croises la bise
    Aux portes du comptoir
    Que son baiser glacé
    Te transforme en passoire
    Quand le vent froid attise
    La morsure des fées

    Tu traînes dans la nuit
    Les brûlures du temps
    Mais sans bulle d'Osère
    La traîne des ennuis
    Et la neige d’hier
    Recouvre tes vingt ans

    Non plus de vertes fleurs
    Qui ne se nomme feuille
    Ciboulette ou cerfeuil
    L’aurore en demi-teinte
    Ne cherche plus l'étreinte
    Du colibri rieur

    L’amante religieuse
    Est paraît-il enceinte
    Et rôde malheureuse
    Entre deux apogées
    Des soupirs de l’absinthe
    Jusqu’aux cris des dragées

    Les ténèbres trimballent
    Décor en carton-plâtre
    Quelques films à dix balles
    « Le char du prince ment »
    Larmes et sentiments
    Scénarios à la hâte

    Les acteurs sont célèbres
    Pour leurs masques pédants
    On bouche comme on peut
    L’inter-gémissements
    De bouche-à-bouches creux
    Et de larmes d’ascètes

    Mais l’on ne peut avoir
    Et les deux pieds sur terre
    Et les jambes en l’air
    Que reste-t-il à croire ?
    Si tout assure et ment
    Grisons-nous de tourments !

    Qui veut douter de tout
    Doutera de ses doutes
    Même du soir qui plonge
    De l’ombre qui s’allonge
    Le coeur quoiqu’il nous coûte
    Est notre seul atout
#+END_VERSE
#+END_CENTER

* Cavalcade

#+BEGIN_CENTER
#+BEGIN_VERSE
    Aucune nuit n’est vaine et nous l’avons prouvé
    Fuyant bien au-delà des barrières ignobles
    Nous le savons tous deux les chevauchées sont nobles
    Et l’instant en lui seul contient l'éternité

    Fuyant bien au-delà des barrières ignobles
    Le mors vole au-dessus de la morosité
    Et l’instant en lui seul contient l'éternité
    Un seul grain de raisin promet tout un vignoble

    Le mors vole au-dessus de la morosité
    Gloire à tous les viveurs et oublions les sobres
    Un seul grain de raisin promet tout un vignoble
    N’attendons pas l’automne avant de s’enivrer

    Gloire à tous les viveurs et oublions les sobres
    Les ruisseaux les plus frais ont un cours débridé
    N’attendons pas l’automne avant de s’enivrer
    Ma fleur laisse le vent ôter ta jolie robe

    Les ruisseaux les plus frais ont un cours débridé
    Qui court après les jours que l'étang lui dérobe
    Ma fleur laisse le vent ôter ta jolie robe
    Aucune nuit n’est vaine allons le démontrer
#+END_VERSE
#+END_CENTER

* Nuit souveraine

#+BEGIN_CENTER
#+BEGIN_VERSE
    Jupe d'ébène
    Jambes d’ivoire
    Elle est la reine
    Du savon noir

    Brûle mes veines
    Sans le savoir
    Ah quelle veine
    J’ai de la voir

    Ma ferveur vaine
    Voudrait l’avoir
    Jupe d'ébène
    Jambes d’ivoire

    Sur sa peau lisse
    Nard et nectar
    Le satin glisse
    Je n’ose y croire

    Statue sereine
    Huilée de moire
    Ma coupe est pleine
    J’ai du trop boire

    Deux tétons règnent
    Deux raisins noirs
    Ses seins qui saignent
    Brûlent le soir

    Reprendre haleine
    Et synthétise
    Toute la scène
    Désir surprise

    Baiser sa gorge
    Qui vocalise
    Son soutien-gorge
    Chute et s’enlise

    Ses hanches daignent
    Frémir d’espoir
    Voile d'ébène
    Cuisse d’ivoire

    Sa bouche offerte
    Se laisse choir
    Sens en alerte
    Sur dents d’ivoire

    Dentelle éprise
    Mes mains s'égarent
    De convoitise
    Dans le plumard

    Corde d'ébène
    Fesses d’ivoire
    Ma souveraine
    Face au miroir

    Glace lubrique
    De lupanar
    Couple identique
    Laissons-les voir

    Le nacre perle
    Sous ses dessous
    La pluie déferle
    J’y bois mon saoul

    Bisou mouillé
    Et faim de loup
    Cordon coupé
    Chutez froufrous

    Dans la nuit chaude
    Deux ombres grises
    L’une sur l’autre
    Fleur et cerise

    Ma belle reine
    Serre sa prise
    Toison d'ébène
    Sur rose exquise
#+END_VERSE
#+END_CENTER

* La fugitive

#+BEGIN_CENTER
#+BEGIN_VERSE
    Imagine une nuit claire où la lune est pleine
    Et nous envoie du haut de son trône d'ébène
        Sa lueur évasive.

    Silencieux, les matous maraudeurs lèvent l’ancre
    Pour de sombres couloirs où la nuit se fait encre
        Et leurs ombres furtives.

    Une lame de miel enrubannée d'épices
    Déferle d’une porte où de dorés calices
        Voguent à la dérive.

    Les heures défilant, mes pensées embrumées
    Se perdent au milieu des lampes irisées
        Et des vapeurs fautives.

    Soudain je la devine, envoûtante et câline,
    Emergeant du néant, brusquement se dessinent
        Ses yeux qui me captivent .

    Son regard langoureux me frôle et me fascine,
    Ses longs cheveux hâlés imprègnent ma rétine
        De leurs ondes lascives.

    Dans un baiser fougueux, nos lèvres se délivrent
    De leur prison de froid, de leur carcan de givre,
        De l’attente plaintive.

    Emporté par l’ardeur de nos corps qui s’attirent,
    Je me sens doucement sombrer dans le délire
    Lorsque soudain elle s’esquive,
        Ma douce fugitive.

    Pourquoi a-t-elle alors voulu fuir son désir ?
    Jamais je ne saurai. Parfois ton souvenir
    Embrasse mon âme surprise,
        Ma douce fugitive ...

    " Je suis le souffle chaud de l’instant que j’attise
    " Jusqu'à ce qu’il rougoie d’intense convoitise."
    Ainsi parlait, de sa brise impulsive,
        Ma douce fugitive.
#+END_VERSE
#+END_CENTER

* Valse majeure, accords mineurs

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ame des valses enivrantes,
    Frénétique cadence,
    Ame berceuse de nos sens
    Sois belle et trépidante !

    Pique les alézans quadriges
    Des rythmes débridés ;
    Que tes abîmes effrénés
    Nous donnent le vertige !

    Que la corolle d’une ronde
    Tourbillonne sans freins,
    Que l’air vibre jusqu’au matin
    Dans ta gorge féconde ;

    Tourne, vrille jusqu’aux étoiles,
    Attelage de flous,
    Plus vite, brisons le verrou
    Qui retenait nos voiles !

    Ame des valses insistantes,
    Extatique fréquence,
    Ame de langoureuse essence
    Sois lente et caressante !

    Dévoile-nous la cruauté
    De cet horrible vide ;
    Exhibe l’espace livide
    De nos jours gaspillés !

    Détends tes cordes satinées
    Autour des épidermes,
    Que tes bras délicats se ferment
    Sur l'âme convoitée

    Plus lent, presque jusqu'à l’arrêt
    Puis repars de plus belle !
    Tout s’emballe alors jusqu’au ciel,
    La suite je la tais ...
#+END_VERSE
#+END_CENTER

* Air frivole

#+BEGIN_CENTER
#+BEGIN_VERSE
    Souvenirs.  Soirs radieux où un soleil rieur
    Glisse ses derniers feux aux vins et aux liqueurs.
    Lors, leurs robes pourpres s'éclairent de vapeurs
    Nous laissant voir l’essence de milliers de fleurs.

    Espoirs. Nuit de ripaille où les moissons respirent.
    Bercées par leurs soupirs, nos pensées s’abandonnent.
    Les épaisses murailles du château résonnent
    De nos chants enchantés d’où jaillissent les rires.

    Ivresse. Aurore grise où les désirs nous grisent.
    Le regard s'égaillant surpris par de doux yeux.
    La belle vient gaiement. Les ardeurs qu’elle attise
    S'élèvent en un brasier, tout n’est plus que le feu.

    Folie. La paille assiste à tous nos jeux paillards.
    Galbe, cuisses ambrées, on fouine dans le foin.
    Galop, croupe cambrée, on couine dans les coins.
    Mais quand vient le midi, l’on est bien moins gaillard.

    Tristesse. Journée grise où les désirs s'épuisent.
    Plus de brasier, rien que des braises.
    Nos ardeurs alourdies s’apaisent.
    Le regard ne voit plus qu’un étang qui s’irise.

    Miroir. Il perce nos mystères : il nous connaît.
    C’est un juge implacable : il lamine et perfore
    Notre âme lorsqu’il sort d’un grimoire un remord,
    D’une armoire une histoire, d’un étage un secret.

    Mais que vois-je ? Un soir radieux où un ciel rieur
    Glisse ses derniers feux aux vins et aux liqueurs.
    Lors, leurs robes pourpres s'éclairent de vapeurs
    Nous laissant voir l’essence de milliers de fleurs ...
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

