
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Grisailles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Chassé-croisé

#+BEGIN_CENTER
#+BEGIN_VERSE
    Si tu savais mon frère
    Quels déserts me transpercent
    Vers ce temple d'éphèse
    Ensablé de tristesse

    Si tu savais ces peurs
    Qui me hantent le soir
    Et ces avertisseurs
    Pépinières de poires

    Irriguées de vin chaud
    Etuves de l’hiver
    Dénouant l'écheveau
    Des nuages de chair

    Qui épousent le flanc
    Du flot où ils s’enlisent
    Tourmentés jusqu’au sang
    Par les sanglots des îles

    Si tu voyais ma soeur
    Le bouquet dans la serpe
    A travers la vapeur
    L’oeil brillant de l’averse

    Si tu voyais mais non
    Les versets sont tous vains
    Les ariettes s’en vont
    Dès que l'écho s'éteint
#+END_VERSE
#+END_CENTER

* Blues

#+BEGIN_CENTER
#+BEGIN_VERSE
    La pluie bat les carreaux les fauteuils se balancent
    Au rythme des cahots qui battent la mesure
    Le thé ne fume plus la tasse s’en bat l’anse
    Un saxophone d’or improvise l’azur

    Au rythme des cahots qui battent la mesure
    L’aiguillage choisit au hasard le voyage
    Le saxo se déhanche et danse la voiture
    Sur un tango jazzy où valsent les visages

    L’aiguillage choisit au hasard le voyage
    Voilà une éclaircie qui pleure et qui sourit
    Sur la valse jazzy d’un tango qui s’engage
    Et puis d’un coup plus rien le vide étend sa nuit

    Voilà une éclaircie qui pleure et qui sourit
    C’est à la fois la bise et la brise suave
    Et puis d’un coup plus rien le vide étend sa nuit
    Et je cherche à tâtons la clef de la charade

    C’est à la fois la bise et la brise suave
    Mais le temps saute en marche et les wagons s'éloignent
    Sur les rails d’autres trains tandis que je m'évade
    Dans le blizzard glacé et la neige qui gagne

    Mais le temps saute en marche et les wagons s'éloignent
    L’entrain qui pétillait s’enfuit vers l’horizon
    Dans le blizzard glacé et la neige qui gagne
    Je remonte la voie vers le quai de béton

    L’entrain qui pétillait s’enfuit vers l’horizon
    Tout est superficiel au travers des lucarnes
    Je remonte la voie vers le quai de béton
    La gare de triage où le givre s’acharne

    Tout est superficiel au travers des lucarnes
    Une buvette triste où l’eau ne mousse pas
    La gare de triage où le givre s’acharne
    La tasse s’en bat l’anse et mon café est froid
#+END_VERSE
#+END_CENTER

* Ténèbres

#+BEGIN_CENTER
#+BEGIN_VERSE
    Notre époque livide exècre l’harmonie
    Du gris du gris du gris charbon poudre insomnie
    Insipide cocktail de teintes dépressives

    Architecture amas de géométries froides
    Des arêtes des coins des quadrillages fades
    Passés et repassés cent fois à la lessive

    Tout est blême à l’extrême un linge étroit et roide
    Quand l'Utilité n’a de raison qu’elle-même
    Certifiée sans couleur fantaisie ni poème

    L’air a la pesanteur d’un soir sans sérénade
    Sans brise sans oeillade une nuit uniforme
    Couvre-feu vénéneux où l’encre se conforme

    Finies les azalées les orchidées timides
    Le béton le bitume à la prise rapide
    Recouvrent les allées d’une grisaille informe

    Un monde-interrupteur ignorant les nuances
    Télé en noir et blanc radio interférence
    Le binaire est le roi le chaos est la norme

    Il est bien loin le flamboiement des décadences
    Le parfum du jasmin les douces symphonies
    Et le luxe insolent des pluies de pierrerie

    Les vieux Soleils ont tous atteint la délivrance
    Laissant près du linceul de leur apothéose
    Dame Lune éplorée sous son voile morose
#+END_VERSE
#+END_CENTER

* Le chant de la colombe

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il a beaucoup plu cette nuit
    Ce soir il fait beau tout va bien
    Il a beaucoup plus dans la nuit
    Les oiseaux chantent pour demain

    J’aurais voulu chanter l’amour
    A chaque aube chaque couchant
    J’aurais voulu mais un vautour
    En a décidé autrement

    J’aurais voulu chanter toujours
    Toujours l’amour à chaque instant
    J’aurais voulu mais le temps court
    Qui me dit retourne au néant

    J’aurais voulu nier la mort
    Nier la mort et le néant
    J’aurais voulu mais le décor
    Me dit je ne suis que du vent

    Ne pas tomber dans le ravin
    Et c’est déjà bien suffisant
    Ne pas tomber et ce chemin
    Qui s’enroule comme un serpent

    J’aurais voulu tous les minuits
    Me rebaigner dans l’ignorance
    J’aurais voulu la paix l’oubli
    Mais j’entends les cris de souffrance

    Dites-moi où est la sortie
    Loin de ces effluves d’horreur
    Dites-moi où je m'égosille
    Je ne vois aucune lueur
#+END_VERSE
#+END_CENTER

* Odelette aux chandelles

#+BEGIN_CENTER
#+BEGIN_VERSE
    Danse la flamme, danse
    Que ton beau corps ondule en un vibrant appel ;
    Danse la flamme, danse
    Ton désir étincelle.

    Chante la flamme, chante
    Cet été disparu derrière l’horizon ;
    Chante la flamme, chante
    La saison des moissons.

    Berce la flamme, berce
    Mon coeur plombé par le crachin et la grisaille ;
    Berce la flamme, berce
    Que le printemps piaille.

    Vole la flamme, vole
    Emporte mes espoirs au-delà des nuages ;
    Vole la flamme, vole
    Au-dessus des orages.

    Rêve la flamme, rêve
    Le décor orangé des paradis sur terre ;
    Rêve la flamme, rêve
    Montre-moi la lumière.

    Conte la flamme, conte
    Redis-moi ce monde éclairé par trois soleils ;
    Conte la flamme, conte
    Jusqu'à l’aube vermeille.
#+END_VERSE
#+END_CENTER

* Grenier à clef

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sous un soleil fiévreux, l’aurore sans défense
    Savoure la langueur de la bise automnale.
    L'été a pris le voile, et les chiens de faïence
    Regardent défiler les bas-fonds de la cale.

    Les appas sont grippés, l’appeau prend la poussière,
    Et même le pommeau n'étreint plus la luxure.
    Sous les jupons plissés, l’araignée buissonnière
    A tissé patiemment de très chastes ceintures.

    Seul le vieux balancier d’une horloge palpite
    Non loin du canapé où ronfle tante agate.
    L’unique ombre chinoise, estampe décrépite,
    D’un matou tout mité trottine à quatre pattes.

    Là où régnait jadis une rose marine,
    Un vieux vase accroupi essuie des rots marins.
    Un loup de mer à pipe, ancien dragueur de mine-
    Oie sans cervelle songe aux meutes de catins,

    Au hurlement du vent dans les plaines de brume ...
    Que de coups de tabac, de tempêtes, de grains
    De beauté a-t-il dû traverser, et d'écume,
    Combien de naufragées les soirs de pleine lune ?

    L’horizon tourmenté lui dit : silence, on tourne
    En rond. Un peu d’eau d’as, égarons-nous de jambes !
    Mais la lingère est nue, et folle, et se détourne,
    L'âme use l’arbricot, et les flots se ressemblent.
#+END_VERSE
#+END_CENTER

* Le pays de Détresse

#+BEGIN_CENTER
#+BEGIN_VERSE
    Lorsque je me trouve en Détresse
    Hors de mes gonds et hors d’haleine
    Je confie mes pleurs à la plaine
    Et l’herbe ploie sous la tristesse.

    Sous la grisaille qui m’oppresse
    Le miel est fade et les fleurs vaines
    Lorsque je me trouve en Détresse
    Hors de mes gonds et hors d’haleine.

    Dans les brumes les plus épaisses
    Je combats des ombres malsaines
    Qui figent mon sang dans mes veines.
    Non, plus de joie ni de caresses
    Lorsque je me trouve en Détresse.
#+END_VERSE
#+END_CENTER

* Le vide

#+BEGIN_CENTER
#+BEGIN_VERSE
    Pour m’attirer dans le cellier
    Il se fait femme aux mille seins
    Dont la robe rouge foncé
    Laisse échapper un doux venin
    Mais il me guette au fond du verre
    Tapis sous la pulpe asséchée
    Des rêves de fin de soirée
    Qui refleurissent les déserts
    Ce Vide étrange qui m’enserre.

    Dans les tiroirs du souvenir
    Il brûle en ses flammes cuivrées
    De vieux billets, de jeunes rires
    Teintés de rougeurs parfumées
    Puis désintègre la matière
    Des rideaux, des tapis miteux
    Dans un gouffre vertigineux
    Qui ne s’arrête qu’aux enfers
    Ce Vide étrange qui m’enserre.

    Lorsque je ferme mes fenêtres
    Pour conserver quelque chaleur
    Je vois une main apparaître,
    Cercle de fumée sans ardeur
    Qui répand dans mon atmosphère
    De sournois soupirs assoupis,
    Poison languide de mes nuits
    Qui appesantit mes artères
    Ce Vide étrange qui m’enserre.

    A l’aube des journées stériles
    Il entame sa rotation
    Creusant dans mon âme fébrile
    Le coeur assoiffé du siphon
    Et s’incurve la terre entière
    Dans l’aspiration entraînée
    Par la spirale incontrôlée.
    C’est un tourbillon sans lumière,
    Ce Vide étrange qui m’enserre.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

