
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Scène
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Saillie

#+BEGIN_CENTER
#+BEGIN_VERSE
    - Bienvenue le bébé, un monde s’ouvre a toi
    L’on me nomme la vie, voici quelques conseils :
    Je n’offre qu’une nuit, je griffe et me débat,
    Sans attendre, prends-moi, devant que le soleil

    Ne me voit m’envoler, car je suis infidèle.
    Tu vas devoir apprendre à écrire, à compter
    Mais surtout à mentir tout drapé de dentelle.
    Sois toujours prêt à fuir, à trahir le premier,

    A rire avec l’idiot s’il porte une arme au poing,
    A poudrer le pouvoir de parfums capiteux,
    A saigner ta part dans les rivières d’or fin,
    A tous les enchaîner de maillons insidieux.

    Et méfie toi de tous, surtout de ceux qui t’aiment,
    Quant à toi n’aime pas, contente toi des phrases,
    Celles qui droguent la volonté et parsèment
    Les yeux des victimes d’abandon et d’extase.

    Tes rêves, détruis les : ils sont d’un autre monde,
    Ici est méprisé le lent vol des oiseaux.
    Garde les pieds sous terre, et ton âme féconde
    Sers-t’en pour asservir les chiens et les troupeaux.

    N’est-ce pas merveilleux, dis-moi qu’en penses-tu ?
    - Ouuuuuiiiiiiiiiiiinnnnnnnn !
    - Tu peux tout oublier, le temps de l’innocence.
    - Reuh ?
    - C’est bien !
#+END_VERSE
#+END_CENTER

* Les statues de pierre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le lait de notre enfance est déjà liquoreux,
    Dans ce marbre de miel, notre vie est gravée.
    Nos pensées, au landau, sont bien vite entravées,
    Par de sournois coussins, par des barreaux moelleux.
    Les balances pipées des berceuses s’inclinent,
    Tandis que nous rêvons, coulant des jours heureux,
    Et répandent en nous leurs effluves câlines,
    Arcs-en-ciel ombragés de jalousies mesquines.
    Déjà du nouveau-né on filtre la lumière,
    Nous sommes des Statues libres comme la pierre.

    Nous grimpons sous les murs d’un château ambitieux,
    Qu’il soit Manoir rustique ou Tour édulcorée,
    Que l’histoire engloutit à la prime marée.
    Alors, jeunes naïfs, aveuglés par les feux
    Qu’un bijou sans valeur imprime à nos rétines,
    Nous recherchons en vain le diamant précieux
    Qui pourrait délivrer nos coeurs de leurs sourdines.
    Mais, usés par le Temps et de piquantes bruines,
    Nous regagnons bientôt la douceur des clairières.
    Nous sommes des Statues libres comme la pierre.

    A l’heure où notre poil revêt un ton neigeux,
    Où le feuillage plie sous le poids des gelées,
    De pâles souvenirs en robes tamisées
    Nous rappellent l'époque et les jours délicieux
    Où, triomphalement, nous sonnions les matines.
    Vient alors du regret cet index malicieux
    Qui nous montre le champ de nos espoirs en ruines.
    Qu’ils aient été d’acier, de chaume ou de résine,
    Ils sont tous désormais recouverts par le lierre.
    Nous sommes des Statues libres comme la pierre.

    Enfant, n'écoute pas ces bruyants cimetières
    Où des robots rouillés huilés par la lésine
    Veulent forger l’esprit en séries à l’usine.
    Prends ta hache et détruis ton Enceinte de pierre !
#+END_VERSE
#+END_CENTER

* Salle de classe

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est un local - plutôt froid mais trop chaud -
    Où les songes sont tenus en cellule.
    D’un pupitre, source de tous les maux,
    Des yeux d’aigles les cernent, les acculent
    Et leur envoient leurs batteries de bulles.
    Vient l’hallali et le dernier assaut
    Puis l'école referme son étau.

    Les néons glauques flashent notre peau
    Martelant les symboles qui pullulent
    Sur la surface obscure du tableau.
    Le point-virgule se désarticule ;
    Les équations, les dates gesticulent ;
    Monstres farceurs sortis de leur chapeau.
    Puis l'école referme son étau.

    Le globe tourne à l’envers. Son fardeau
    Lui a tassé les pôles et il bouscule
    Les idées qui nous viennent du berceau.
    Près des vénitiennes, nos libellules
    S'écrasent sur les fenêtres et reculent
    Renonçant toutes à leurs lointains roseaux
    Puis l'école referme son étau.

    Horloge, aide-nous ! Belle cloche, hullule !
    Délivrez-nous de nos rôles d'émules !
    Tous aux vestiaires, vite les manteaux !
    Car l'école désserre son étau.
#+END_VERSE
#+END_CENTER

* Les anneaux de pouvoir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Aux Elfes l'Anneau d’or serti de diamants
    Dont les blancs feux brûlent les coeurs les moins ardents.
    L’auréole diaphane de leur prestance
    Se diffuse dans les feuillages les plus denses.
    C’est pour eux qu’au printemps dansent les jolies fleurs
    Sur les rythmes effrénés que le soleil cadence ;
    L’automne devant eux dévoile ses couleurs,
    Le chêne les salue de ses feuilles rieuses.
    Mais le diamant boit l'Agate capiteuse
    De l'Anneau des Anneau, irrésistible leurre.

    Aux Nains l'Anneau de bronze et le vert éclatant
    De l'émeraude née des larmes d’un volcan.
    Leurs galeries creusent les profondeurs intenses
    A la recherche d’un concentré de brillance.
    A eux la mine grise, ruisseau de sueur ;
    Les soirs heureux où ils trinquent à la quintessence
    Avec l’amitié qui leur offre sa chaleur.
    Et pourtant, épaulée par l’envie malicieuse,
    Leur émeraude effleure l'Agate soyeuse
    De l'Anneau des Anneau, irrésistible leurre.

    Aux Orcs l'Anneau de fer détrempé dans le sang
    Que versent en torrents de frêles innocents
    Dans le rubis infâme de la violence
    Dont le rouge aveuglant achète le silence.
    Le monde plie sous l’omniprésente terreur
    Qu’infligent sans pitié leurs épées et leurs lances,
    Vassales de la gloire, esclaves du vainqueur.
    Pourtant, sous leur ignoble salive fielleuse,
    Le rubis rampe devant l'Agate mielleuse
    De l'Anneau des Anneau, irrésistible leurre.

    Aux Humains, l'Anneau d’argent né dans l’océan
    De l’abîme engloutit et des cieux envoûtants
    Où le saphir trace les chemins de l’errance
    De l’esprit qui cherche vainement la puissance.
    Ils enferment dans une mortelle pâleur
    Les bijoux qu’ils palpent de leur folle imprudence.
    Pourtant, quand ils fuient loin de la gluante erreur
    Ils créent des merveilles de leurs âmes curieuses.
    Mais le saphir se vend à l'Agate coûteuse
    De l'Anneau des Anneau, irrésistible leurre.
#+END_VERSE
#+END_CENTER

* Test d'aptitude de Madame Irma

#+BEGIN_CENTER
#+BEGIN_VERSE
    Perds-tu le souvenir de tes amis d’antan
    Entre deux caisses noires
    Chèque en bois chèque en blanc
    Es-tu prêt à trahir toujours au bon moment
    A perdre la mémoire
    Et l’odeur de l’argent
    Fermes-tu les yeux sur les boîtes en fer blanc
    Lances-tu chaque soir
    Une promesse au vent
    Eclates-tu d’un rire implacable et cynique
    Quand un choeur de rêveurs
    Te parle de colchiques
    Brûles-tu l’avenir dans des complots vulgaires
    Pisses-tu sur les fleurs
    Te nourris-tu des guerres

    La boule de cristal dit que tu iras loin
    Fais de la politique et tout ira très bien
#+END_VERSE
#+END_CENTER

* Triple exemplaire

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le fonctionnaire attend sous sa lampe blafarde
    Et les rayons ratés le frappent de stupeur.
    Un café de trois jours renverse sa chaleur
    Et son dernier espoir coule sous une farde,

    Piège ou même l’oubli se noit, tant ces flots blêmes
    Inondent le monde de leur encre inutile.
    Le vide noir sur blanc se réplique lui-même
    Comme un virus obtus dont les copies défilent.

    Le cachet, ce cachot, l'écrase sous sa loi ;
    Le marqueur se reflète en son jeux de miroirs,
    Echiquier infini de classeurs, de tiroirs
    Et de papier jauni par un soleil de bois.

    Il voudrait bien hurler mais un poids dans son âme
    Cloue au sol sa complainte. Il garde son secret.
    Dans le couloir, un sergent rôde, veille et blâme
    Ceux qui osent encor sortir de leur coffret.

    Car il est prisonnier. Prisonnier des regards
    Des sous-fifres hautains et des cadres vitreux.
    Prisonnier de cette pyramide d’affreux
    Qui se regarde agiter son propre encensoir.

    Alors il se masque de réglements boîteux
    Trop étroits pour son corps, trop cassants pour son coeur
    Et brandit, menaçant, l’article poussiéreux
    Qui lui sert de massue contre tous les râleurs.
#+END_VERSE
#+END_CENTER

* Le métier

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle tresse, lassée, des lacets enlacés.
    "Entrelacs c’est assez ! Vous m’avez épuisée.
    Avisée je serais d’aller me prélasser."
    Dit-elle contemplant son oeuvre inachevée.

    Mais toujours il lui faut ouvrager sans relâches
    Tant le temps est court et tant le salaire est lâche
    Alors donc elle coud sans dégoût ni sans larmes
    Comme si le tricot l’agrippait de ses charmes

    Lorsque vous enfilez votre manteau de laine
    Pensez donc à ces mains d’une cave malsaine.
#+END_VERSE
#+END_CENTER

* Temps modernes

#+BEGIN_CENTER
#+BEGIN_VERSE
    Quelle-est donc cette foule, quelle donc cette presse ?
    Seraient-ils donc tous fous, seraient-ils en détresse ?
    On les voit tous les jours, sous l’air qui les oppresse
    Servir laborieusement l’avide déesse

    Que l’on nomme Travail. Exigeante, infidèle,
    Tous elle nous maintient sous sa coupe cruelle
    Création du passé, fardeau qui nous martelle
    Quand va-t-on adoucir ses traits osseux et grèles ?

    Ses courtisans cupides lui creusent ses rides
    Vengeresse elle fait miroiter ses caresses
    Mais ils n’obtiennent d’elle que morsures avides
    Contre cette sueur qu’elle aime et qui l’engraisse
#+END_VERSE
#+END_CENTER

* Métro

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je suis seul. La foule m'écrase, je suis seul
    Des âmes étourdies dans des corps engourdis
    Je suis seul au milieu d'écrins et de linceuls

    Tous ont laissé leurs rêves en leurs lits encor chauds
    Ils errent donc sans trèves, écrasés de soucis
    Mais leurs yeux sans lueurs ignorent les fardeaux

    Mais taisons-nous ! Toujours se fondre dans la masse
    Couleurs vives déteintes, toute vigueur éteinte
    Mais taisons-nous ! Il nous faut aligner nos traces

    Mais point de triste fin ! Un regard, tout s’efface
    Et la mélancolie, et le son de ma plainte
    Il suffit d’un regard, un regard fond la glace
#+END_VERSE
#+END_CENTER

* Avant que d'être une ombre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Avant que d'être une ombre
    Que le soleil accable
    Suivant les chemins sombres
    Tracés par ses semblables

    Avant que d’avancer
    Dans un étroit couloir
    En laissant défiler
    Les matins et les soirs

    Nous avons tous été nous-mêmes, au moins un jour
    Et non pas le pâle reflet d’un peuple en contre-jour
    Mais oui nous sommes libres ! De suivre les sentiers
    Bordés par une jungle aux fauves redoutés

    Nous avons tous vécu par nos jeux et nos rêves
    Et non pas seulement par le regard des autres

    Mais il n’en reste rien ! Tout au plus un souvenir
    Qui parfois nous revient , lorsqu’un soir de trêve
    L’on regarde la mer , assis sur une grève
    Mais il n’en reste rien , juste un pâle sourire

    Et si parfois le vent perdu de l’aventure
    Vient me souffler à l’oreille , dans un lointain murmure
    "Fichons le camp d’ici ! Ca sent le renfermé

    La poussière et l’alcool , des rumeurs
    De rumeurs , des complots , la sueur
    Et du papier brûlé"

    Je m’entends lui répondre en un vague soupir
    Si le soleil se lève demain
    Est ce pour voir comme aujourd’hui
    Le même brouillard opaque et gris
    Dans lequel se déplacent , sans âme et sans désir
    Des ombres creuses qui semblent avoir pour seul destin
    D’accomplir le pas prochain ?
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

