
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Songes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

** Entre deux songes

#+BEGIN_CENTER
#+BEGIN_VERSE
J’étais là, échoué, sur le bord de mon rêve
À écouter la nuit doucement qui s’achève.
Il faisait noir, il faisait tiède, il faisait calme,
Sous le ballet sans fin où tournent les étoiles.

L’horloge astronomique, immuable, s’étend,
Hypnose sans couleur de tout le firmament.
Perdu d’admiration pour ce cosmos étrange
Où le sourire en fleur est un astre qui danse,
Je perçois le murmure immense des rouages,
Cliquetis silencieux qui déroule les pages,

Et tandis que je sombre à nouveau dans mon rêve,
J’écoute ronronner les vagues sur la grève,
Caresse sur le dos liquide de la plage
Qui se cambre et se cabre au rythme des nuages.
#+END_VERSE
#+END_CENTER


** Poudre de songe

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tu laissais filer tes pupilles
    Dans les ruissellements d'étoiles
    Tes yeux caressaient la prairie
    Qui te répondait en rafales

    Tu laissais flotter ton regard
    Au fleuve aval de notre union
    Des reflets rêveurs des miroirs
    Affleuraient déjà nos frissons

    Tu appris à dompter le vent
    Dans un silence solitaire
    La plume dorée du couchant
    Te livrait le secret des pierres

    Nous parlions le même langage
    Celui d’une flamme qui tremble
    Brûlée d’amour mais ses ravages
    N’ont pas empêché que l’on flambe

    Tu semais la poudre des songes
    Sur chaque colline sauvage
    Et chaque tempête où tu plonges
    Vint s'échouer sur leurs rivages

    Nous les avons suivis sans crainte
    Jusqu’au crépuscule éternel
    De la douceur de nos étreintes
    Nous avons reforgé le ciel
#+END_VERSE
#+END_CENTER

** Coupe de blues

#+BEGIN_CENTER
#+BEGIN_VERSE
    Mal au coeur fuit le jour
    Galactique alambic
    Tamisons l’abat-jour
    Pour ne pas qu’il nous pique

    Le réel se décale
    Tu trouves naturel
    Parfaitement normal
    D'écrire aux hirondelles

    Des poulets au cognac
    Rôtis par le roulis
    Entre deux clapotis
    Flambés sur le tillac

    Quelques coupes de blues
    Dans les verres de vaincre
    Ils s’en vont tous par douze
    Douze tours de cylindre

    Les cactus se lézardent
    Ils sanglotent ensemble
    La dune les regarde
    L’oasis qui en tremble

    Les hivers sont changeants
    Tu voudrais voir Grenade
    Oublier dans les chants
    Les troupeaux de salades

    Les passions des vendanges
    Donnent en vieillissant
    Des crus dignes des anges
    Des vinaigres grinçants

    Quelques pichets de blues
    Dans les jarres de vaincre
    Plutôt l’arbre aux pelouses
    Aux pipeaux les vrais timbres

    Miaulement plaintif
    Modulations félines
    Plaintif impératif
    La nuit se fait câline

    Et tu te sens moins seul
    Tu parles aux fantômes
    Procession de linceuls
    Et reliques d’arômes

    L’antique trisaïeul
    Te décrit d’autres vies
    Cantiques des tilleuls
    Plusieurs ombres le suivent

    De jarre en vidrecome
    Le vidrecome en main
    A travers l’air marin
    Tout chemin mène au rhum

    Tu vas de barque en barque
    Le nez dans le brouillard
    Tu plantes ton mouchoir
    Sur un mât de fortune

    Tu es le seul monarque
    De l’esquif qui a pied
    L’appelles fin voilier
    Frégate des lagunes

    La poésie t’embrume
    Comme une aube illusoire
    Le ventre de l'écume
    Trace un sillon d’espoir

    Quelques cocktails de blues
    De flocons en flacons
    De flacons en glaçons
    De glaçons sous la blouse

    Ferme les yeux pour voir
    Tu rêves que tu rêves
    Une voix au manoir
    Et le rêve s’achève

    Elle était invisible
    Sans cheveux sans dentelle
    Conduisant sa rolls blanche
    Mais c'était bien une Elle

    Tu le sens aux fragrances
    Déroulant une écharpe
    Sillage embruns d’hermine
    Tubulure de harpe

    Quelques grappes de blues
    De champagne en mousseux
    Quelques pampres d’arbouses
    La glace est sur le feu

    Oui c'était bien une Elle
    Et pas de ton poulet
    Le désir a des ailes
    Mieux que des piolets

    L’aimant songes sont-ils
    Dans le jeu des probables
    Univers en exil
    Dans les limbes des fables

    Sont-ils la vérité
    De mondes différents
    Etranges liserés
    Perdus au fil du temps

    Quelques coupes de blues
    Dans les verres de vaincre
    Ils s’en vont tous par douze
    Douze tours de cylindre
#+END_VERSE
#+END_CENTER

** Quête

#+BEGIN_CENTER
#+BEGIN_VERSE
    Au fil de l’indomptable, aux cris stridents de l’eau,
    Voguait l'écrin sacré, voguait telle un corsaire
    La soif, ce sel pâteux des sables aurifères,
    La source inaltérée qui ronge les métaux.

    L’inassouvi s’ouvrit sur un clair de salière
    Où même les piliers d’autres temps se corrodent
    Et les musées anciens se recouvraient de lierre
    En songeant aux affreux hurlements de l’iode.

    Et toi, quel est l’effroi qui t’indique l’exode,
    Les cimes des nuées, les murailles de gel,
    Les reflets argentés au pied des citadelles,
    L’inaccessible enfin, le vent que rien n'érode ?

    La flamme pétrifiée dont l’ombrage liquide
    Ouvre dans les parois les portes d’atlantides
    Tout en laissant l'écho submerger les cavernes,

    Ensemencer le verre en l’embuant d’un souffle
    Puis peindre de ses doigts la faune des tavernes,
    Se laisser emporter par ces rêves qu’essoufflent

    Ces univers enfouis que d’autres lois gouvernent,
    L’irréel, l’impossible et l’impensable ensemble,
    Voilà ce que l’on cherche et c’est pourquoi je tremble.
#+END_VERSE
#+END_CENTER

** Les exilés du ciel

#+BEGIN_CENTER
#+BEGIN_VERSE
    Faites le plein de la voilure
    Ce soir nous partons pour la lune
    Nous n’emportons pour nourriture
    Que du vent pour chasser la brume

    Gonflez bien les voiles latines
    Qu’elles dansent pour nous ce soir
    C’est dj Cyclone aux platines
    Et cocktail Tornade au comptoir

    Nous remontons le cours du ciel
    Oui pourquoi cela vous étonne ?
    Au clair d’une lune de miel
    Entourés d'éclairs qui détonent

    Une frégate de plaisance
    Allant lutiner les houris
    Sous pavillon de complaisance
    - Le firmament nous a souri -

    Une régate sous la brise
    Voguant vers les nuages roses
    Pour le chemin pas de surprise
    Nous suivrons le parfum des roses

    Nous prendrons en stop les sirènes
    Ca les changera des grands fonds
    Quelques dauphines des six reines
    Nous envoûteront de chansons

    Nous ferons valser les étoiles
    Et leurs diamants magnétiques
    Nous irons dissiper les voiles
    Des mondes fantasmagoriques

    Nous irons cueillir la musique
    Et récolter quelques oeufs d’or
    Mais pas d’omelette cosmique
    Car les poussins sont des trésors

    Nous irons prendre les vénus
    Au piège de leurs flammes d’ocre
    Tâter de leurs draps bleus ne fut-ce
    Que pour déferler le grand foc

    Nous verrons ces neiges charnelles
    Déposer sur nos chevelures
    Les cristaux blancs de leur dentelle
    Faites le plein de la voilure

    Nous remontons le cours des songes
    Sur le fil doré des merveilles
    Nous remontons le cours des songes
    Qu’attendez-vous ? On appareille !

    Partons saisir l’insaisissable
    Le graver sur un hologramme
    Et enlevez-moi tout ce sable
    Que s’en échappe chaque gamme

    Notre ancre est lasse de mouiller
    Dans une baie noire aux flots lisses
    Quittons cette baignoire huilée
    Eperonnons toutes les drisses !

    Nous ferons valser les étoiles
    C’est dj Cyclone aux platines
    Amenez-moi toute la toile
    La rose des vents nous taquine

    Ces doux embruns qui nous parfument
    C’est la trace de son sillage
    Que son doux parfum nous embrume
    Nous guide à travers les nuages

    La barre au large et cap au ciel
    C’est cocktail Tornade au comptoir
    Sortez le chouchen et le miel
    Dame lune nous offre à boire

    Sur le fil doré des merveilles
    Le firmament nous a souri
    Qu’attendez-vous ? On appareille
    Sur le fil doré des merveilles

    Nous n’emportons pour nourriture
    Que du vent pour chasser la brume
    Faites le plein de la voilure
    Ce soir nous partons pour la lune
#+END_VERSE
#+END_CENTER

** Extension

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est vivre chaque jour comme un autre univers
    Transpercer l’illusion des pesantes routines
    Pour s’immerger sans peur aux fractales sublimes
    De l’espace et du temps chatoyants de lumière

    Labyrinthe cosmique où les murs sont miroirs
    Et se renvoient la balle agile des reflets
    Les pièces reliées par un couloir secret
    Chaque face est un monde et la chambre un manoir

    C’est murmurer existe et porte au loin tes rêves
    Il n’y a d’autre loi et le fond du mystère
    Est un écho dans un défilé circulaire
    Que tu peux créer dès que ton âme s'élève
#+END_VERSE
#+END_CENTER

** Rêve d'or

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle apparaît telle une électre
    Dans un halo pâle de spectre
    A l’heure où la nuit s'évapore
    Ma belle fée ma favorite

    Je suis glouton elle est avide
    Sa robe argentée translucide
    Me cache si peu ses trésors
    Ses trésors de fée qui palpitent

    J’entends sa chaleur envoûtante
    Murmurer des phrases troublantes
    Et son baiser brûle mon corps
    En une caresse explicite

    Elle me parle avec sa peau
    Elle chante comme un ruisseau
    Elle a ensorcelé mes songes
    De quelque magie non écrite

    Je ne sais même pas son nom
    Mais je l’ai baptisée Passion
    Et c’est bien ce feu qui nous ronge
    Mieux que tout un essaim de mites

    Les vagues d’or de ses cheveux
    S'écrasent sur le sable bleu
    Et il faut voir comme j’y plonge
    Quand ma naïade m’y invite

    A l’heure ardente des adieux
    Quand le soleil frappe mes yeux
    Coule de nos cernes rougies
    Une pluie glacée qui crépite

    Mais malgré sa voix enjôleuse
    Ses propositions langoureuses
    Le jour a soufflé les bougies
    Ma nymphe s’estompe interdite

    Et charme ou bien métamorphose
    C’est le mystère de l’hypnose
    Mais là où s’enlisait m’amie
    Ma belle fée ma favorite

    Je sens sa chaleur envoûtante
    Murmurer des phrases troublantes
    Et son baiser brûle mon corps
    De langues de feu qui crépitent
#+END_VERSE
#+END_CENTER

** Oniria

#+BEGIN_CENTER
#+BEGIN_VERSE
    Si la vie n’est qu’un rêve on ne s’en souvient plus
    Au sommeil dans une autre et qui semble un réveil
    Seul un rire taquin à l’orée de l’oreille
    Tente de révéler ce que l’oeil n’a pas vu

    L'âme le sait peut-être est-ce jamais pareil
    Quand le coeur rebondit sur la passion nouvelle
    Temple antique habité par un jeune soleil
    Oublie le défilé des saisons solennelles

    Laisse s’illuminer l’aile des demoiselles
    Sur ton âtre attendri que l'élytre s’irise
    Laisse-toi prendre au jeu de ta charmante prise
    Jusqu’au diapason des vibrations charnelles

    Tu connais la chanson depuis l’aube des mondes
    Tu te revois barbare en pincer pour ta blonde
    Tu te revois cristal épousant la rivière

    Le souvenir t’inonde et de joie et de larmes
    De rendez-vous discrets que la nuit seule éclaire
    De ces galanteries qui te laissaient sans armes

    Ecoute une voix douce entrouvre nos paupières
    Allons la retrouver mon âme au coeur brisé
    Un refrain est fait pour être chanté chanté
#+END_VERSE
#+END_CENTER

** Les six lances

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le vide est créateur. Il n’est pas un silence
    Qui n’envoie une note aiguë comme une lance.

    Des plus intenses ténèbres,
    Du plus dense des néants,
    La foudre jaillit et zèbre
    Le tapis roulant du temps :
    Nulle litanie funèbre
    Ne résiste aux éclairs blancs
    Du plus dense des néants,
    Des plus intenses ténèbres.

    Les cordes saturées frémissent d’impatience :
    Caressons de nos doigts le clavier du silence.

    Des galeries des possibles,
    La fourmilière extensible
    Lance ses dents submersibles
    A l’assaut d’autres futurs ;
    A chaque fourche son choix,
    On bifurque à chaque pas,
    Le hasard ici n’est pas
    Soumis aux lois des augures.

    Des pincées de pensées s'échappent du silence,
    Volutes de fumée qui tournent en cadence.

    L’agile magie se joue
    Des mailles de la matière,
    Aucune horrible lanière
    Ne vient flageller ses joues ;
    Ne vient flageller ses joues
    Car elle passe au travers,
    Ne vient flageller ses joues
    Des mailles de la matière.

    Autour de l’harmonium, la rosée qui condense
    Vient pincer de ses pleurs les cordes du silence.

    Et le treillis s'évapore
    Comme un songe évanescent,
    Comme un arbre transcendant
    Qui se fond dans le décor,
    Dans le décor décadent
    Qui explose les verrières
    En nuages de poussière
    Flottant au gré des courants.

    Les clefs des instruments s’accordent au silence,
    Délivrant des floppées de notes qui s’agencent.

    Disparues les tentacules
    Du réel où l’on se cogne,
    Où les obstacles bousculent
    Les fleuves qui se renfrognent ;
    Les mosaïques basculent
    Au coeur du surnaturel
    Où l’idée est une bulle
    Dans un halo irréel.

    Au creux de son hamac, la chanson se balance
    Au rythme langoureux des nuées du silence.

    L’aube et le couchant s’opposent,
    Vibrante dualité ;
    La roue des métamorphoses
    Oscille sans s’arrêter ;
    C’est le couple primordial,
    Le cycle fondamental,
    Le bouillonnement vital
    Malaxant l’infinité.

    Le chant voluptueux des cordes du silence
    Anime dans la nuit les flots de l’existence.
#+END_VERSE
#+END_CENTER

** Evasion

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je veux rêver debout afin de pouvoir rire
    Au milieu des ordures et des cafards rampants
    Des moisissures humides sur les murs branlants
    Je veux qu’un sortilège efface nos soupirs

    Je veux un florilège enneigé de ses songes
    Qu’il nous emportent en leur tourbillon fantastique
    Jusqu'à ne plus savoir, miroir énigmatique,
    Où est la vérité et où sont les mensonges

    Evitons les pièges de la monotonie
    Laissons-les donc errer, ces pensées assoiffées
    Loin de ces bals d’intrigues où les fleurs sont fanées,
    Là où les accords se répandent en harmonie

    Magie de la pensée, anime donc ces pierres
    Que l’inerte danse, que l’obscur soit lumière
    Que nos coeurs engourdis s'échauffent au vent glacé
    Qu’ils soient en plein hiver un petit coin d'été

    Je veux rêver debout afin de recouvrir
    La laideur écoeurante de l’hypocrisie,
    Les yeux vidés de ceux que je verrai souffrir
    Du manteau excentrique de la fantaisie
#+END_VERSE
#+END_CENTER

** Les cloisons de l'esprit

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans l'étrange pays des songes
    Régi par les charmes des fées
    La vérité est un mensonge
    Le mensonge une vérité

    Dans l'étrange pays des songes
    Les castels sont ensorcelés
    Le sol se transforme en éponge
    Sans prévenir l’intéressé

    Régi par les charmes des fées
    Et la magie des anciens druides
    Chaque passage est cloisonné
    Chaque miroir y est liquide

    Chaque vasque cache un siphon
    Vers une grotte sous-marine
    On y respire un air profond
    Sur une plage cristalline

    Jusqu’au faîte des vieux manoirs
    Grimpent sans fin les escaliers
    Mais la porte du vieux grenier
    Vous ramène au point de départ

    Les castels sont ensorcelés
    La vérité est un mensonge
    Chaque passage est cloisonné
    Le mensonge une vérité

    Le sol se transforme en éponge
    On y respire un air profond
    Et chaque miroir absorbé
    Inverse le cours des saisons

    Tandis que dans la cheminée
    Des trolls dansent sans se brûler
    C’est là tout le charme des fées
    Le pouvoir des anciens sorciers

    Pour accéder au labyrinthe
    Prononcez la formule elfique
    Dont les lettres cabalistiques
    Sont gravées au front de l’enceinte

    C’est la berceuse de l’esprit
    Qui le libère du réel
    Et des contraintes matérielles
    Qui rampent au pied de son lit

    La vérité est un mensonge
    Le mensonge une vérité
    Dans l'étrange pays des songes
    Régi par les charmes des fées
#+END_VERSE
#+END_CENTER

** Reflets

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le ciel est clair et je voyage
    Au pays des rêves étranges.
    Les trains y ont des ailes blanches,
    Le dôme est pur et sans nuages.

    Le voleur prête l’encolure
    Au banquier qui lève la tête,
    Réjouit par les cieux d’azur
    Qui nous invitent à la fête.

    Le juge donne sa balance
    Au pharmacien, les pieds dans l’eau.
    Le mercenaire aide les anges
    A assembler le chapiteau.

    Et le ministre, en clown joyeux,
    Conte la dernière au comptoir.
    Miroir
    Tout n’est que peine et que douloir.
    La corvée, ce vin capiteux,

    Enclos les rus dans les canaux.
    L’esprit s’abrutit dans la fange,
    Le buffle brise le roseau.
    Les litanies et les instances

    Foisonnent au pied des vaines quêtes
    Et corrodent de leurs murmures
    L’espoir gisant dans sa défaite.
    Restent pans de murs et fissures

    Et au loin un rare mirage,
    Nous suffoquons dans l’air étanche.
    Au pays des rêves étranges,
    Le ciel est sombre et je voyage.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
