
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Voyages
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1


 

 

** Charme des Indes

#+BEGIN_CENTER
#+BEGIN_VERSE
    Charme des Indes
    Douce impériale
    Epice enceinte
    De tes pétales

    Te souviens-tu
    De notre foudre
    L’amour sais-tu
    N’a su recoudre

    Les plaies ouvertes
    Qui me taraudent
    Délice serpe
    Larme lame ode

    La fureur rôde
    Folie fleuron
    Les émeraudes
    Jouent du canon

    Charme des Indes
    Reine murmure
    Epice enceinte
    D’un soleil mûr

    Ta peau fleurait
    L’or du Népal
    Gamme de ré
    Mode d’opale

    Toi comme moi
    Ont redit tu
    Sur d’autres la
    D’autres tutus

    Mais sache au moins
    Que je n’oublie
    Dans d’autres lies
    Nos petits vins

    Qui valaient bien
    Ceux qu’on se sert
    Sans s’y toucher
    Jusqu’au dessert

    Entre la dinde
    Et la perdrix
    Le ciel bouché
    L’horizon gris

    Mélancolie
    De la canelle
    Vapeur chérie
    De l’hydromel

    Poivre des Indes
    Fleur de vanille
    Piment d'étreinte
    Je ne t’oublie
#+END_VERSE
#+END_CENTER

** Et va, naissance !

#+BEGIN_CENTER
#+BEGIN_VERSE
    Soudain nous apparut au raz de l’horizon
    Cette terre promise aux moïses modernes.
    Nos âmes, de longtemps, s'étaient mises en berne,
    N’espérant plus, au bord de perdre la raison,

    Marmonnant, grommelant, geignant, pleurant, hurlant,
    Quasi à l’agonie, pour tout dire un peu tristes
    - C’est qu’il faut parfois feindre ainsi que les artistes -,
    Quand vint à nous l’escorte ailée des goélands.

    Ce n'était point le vol des mouettes braillardes,
    Des soudards titubant sous le poids du bordeaux,
    Ni le cygne emplumé ornant le bord de l’eau,
    Ni ces suisses oiseaux armés de hallebardes,

    Non, c'était là de grands, de splendides oiseaux,
    Fiers sans être orgueilleux, gracieux mais point poseurs,
    Explorant le cosmos comme on joue du roseau,
    Libres à la parfin, sans être chamailleurs.

    Et nous qui emmenions, arrimées dans la cale,
    Nos valises d’un jour avec nos peurs d’un soir,
    Nous leur avons lancé : « Nobles voix de l’espoir,
    Vous dont l’aile argentée a franchi les étoiles,

    Dont l’immense envergure embrasse tout l'éther,
    Nous direz-vous comment vous arpentez l’esprit ? »
    L’un d’eux nous répondit, comme un frère à ses frères :
    « Je suis ce voyageur qui n’est jamais parti. »

    Voilà qui était clair ! Et pourtant nous comprîmes ...
    Mais la brise à nouveau tressaille dans son rêve,
    Sa poitrine épanouie se regorge de sève ...
    Il nous faut repartir, le cap sur d’autres cimes

    Devant qu’elle s'éveille et gifle la voilure
    Pour l’avoir caressée avec trop d’insistance :
    La belle est capricieuse et son regard si dur
    Qu’on l’a vue élever des remparts d’un cil-lance.

    Recule, Hercule, avant que ne vienne un typhon !
    Quitte à nous renflouer, choisissons le naufrage,
    Que l’eau y soit feutrée, que douce y soit la plage
    Où notre fier radeau tâtera des hauts-fonds.

    Nous y déposerons nos malles et leurs rois,
    Puis nous irons au port prendre l’air et les femmes,
    Préférant pour un temps la quête de la soie
    Au vertige absolu que l’océan réclame.

    Le vent seul peut combler, peut remplacer le vent
    Et chaque grain de sable est un croissant de lune.
    Nous remonterons tous, la vague aussi, les dunes,
    Le passé du passé, proue dressée au levant.

    Les flacons répandus tairont la marée haute,
    L’histoire des glaçons, carillons des carafes.
    Ils ne nous diront pas l’alizé en carafe
    Ni le gréement en panne à mille lieues des côtes.

    Si l’esquif fend les flots, les flots fendent l’esquif,
    L’amertume et l’amer échoués l’un sur l’autre.
    Les écueils mutuels ont ce piment lascif
    Qu’ont les lits ravagés où le luxe se vautre.

    Mais voici que vient l’heure où l’encrier s'épuise,
    Ou la muse. Qui sait. Quand la plume est à sec,
    C’est que le papier plein éteint les lueurs grises.
    Adieu, donc à demain : je regagne le teck.
#+END_VERSE
#+END_CENTER

** Prophétie

#+BEGIN_CENTER
#+BEGIN_VERSE
    Mais où vont-ils tous ces vers ?
    Mais où vont-ils tous ces chants ?
    Mais où vont-ils tous ces vers
    Que l’on abandonne au vent ?

    Se gravent-ils dans la pierre
    Ou sur une onde illusoire ?
    Se gravent-ils dans la pierre ?
    Réponse au fond du brouillard.

    C’est lui le gardien du phare,
    Le maître de l’illusion.
    Quand un rêve vous égare,
    C’est qu’il effleure un bouton.

    Depuis des générations,
    Il veille sur les grimoires :
    C’est lui le gardien du phare,
    Le maître de l’illusion.

    Des vers, il en voit souvent
    Meurtris par des nuées noires
    Ou, épaves d’un regard,
    Coupés par un paravent.

    Même échoués au rivage,
    Ils espèrent l’océan
    Mais nul voilier sous le vent
    Ne vogue dans les parages,

    Parmi les essuies de plage
    Et les serres d'écrevisses,
    Pas l’ombre d’un équipage,
    Nulle marée de solstice,

    Juste le soleil en nage
    Sans la fraîcheur du matin.
    Ne te perds pas en chemin :
    Choisis bien les aiguillages

    Mais qui dirige la barre
    Sur qui pèsent mille mains ?
    Je vous attendrai au bar
    En gare du lendemain.

    Perdu au fond du brouillard
    Sur le réseau du destin,
    Je regarderai mon vin
    S'éclipser avec le soir.

    Je rêverai au passé
    Pour discerner les futurs :
    Ceux qu’on ne peut deviner
    Sans décliner l’aventure.

    Les cités d’or disparues,
    Les anciens feux d’artifices
    Renaîtront-ils au solstice,
    D’une marée imprévue ?

    Car dans les cercles de pierre,
    Les hexagones de feu
    Existe une autre lumière
    Qui ne fait pas mal aux yeux.

    Si j’en crois la prophétie
    Des poussiéreux parchemins,
    De ce jour là par magie
    S’effacera le crachin ;

    De ce jour là le chagrin
    Ne sera qu’un souvenir
    Et du sable chaque grain
    Sera le germe d’un rire

    On verra pousser les arbres
    Et les fruits de la magie ;
    Des ruisseaux de poésie
    Murmureront sur le marbre.

    Je regarderai mon vin
    S'éclipser avec le soir.
    Que faire d’autre au comptoir,
    Taverne du Lent Demain ?
#+END_VERSE
#+END_CENTER

** Sabbat ion

#+BEGIN_CENTER
#+BEGIN_VERSE
    - Etres fols qui nagez, vous roulez dans vos vices,
    Vous contenterez-vous des bas-fonds du débats,
    D’humecter de vos doigts l’aile ronde ou la cuisse ?
    C’est assez de surface, explorez les abysses !
    Oui, sondez l’insondable océan du sabbat,
    Ne vous contentez pas des bas-fonds du débat,
    Etres fols qui nagez, vous roulez dans vos vices.

    - Je vous ai vu rôder autour des catacombes ...
    Mais qu’espérez-vous donc, en traverser les murs ?
    N’allez pas déranger le royaume des ombres,
    C’est le meilleur moyen de sceller votre tombe !
    Ecoutez, le soir tombe et déjà des murmures ...
    A moins d'être bien sûrs d’en traversez les murs,
    N’allez donc plus rôder autour des catacombes.

    - Nous les traverserons, ces parois de titans,
    Hantée ou pas hantée, entrez dans la bicoque !
    Les squelettes transis, les os qui s’entrechoquent
    Et même, s’il le faut, jusqu’aux léviathans,
    Tous, nous les combattrons sans les craindre longtemps.
    Hantée ou pas hantée, entrez dans la bicoque,
    Nous les traverserons, ces parois de titans !

    Les chats gris, les chats noirs gagnent les cimetières :
    Voyez, la lune est pleine et la ronde commence.
    Les spectres, réveillés par les pas des sorcières,
    Sortent de leurs caveaux dans leurs plus beaux suaires.
    Doublez les feux follets de ces macabres danses !
    Voyez, la lune est pleine et la ronde commence :
    Les chats gris, les chats noirs gagnent les cimetières.

    Brûlez sans ralentir les feux rouges et blonds
    Des succubes de luxe aux cryptes cinq étoiles.
    Ne pensez même pas à jouer l'étalon
    Ou vous iriez tâter de leurs crocs cannibales.
    Prenez la direction de la boussole à plomb,
    Brûlez sans ralentir les feux rouges et blonds
    Des succubes de luxe aux cryptes cinq étoiles.

    Itou pour les potions des vendeurs nécrophages,
    N’allez pas inhaler les poudres sépulcrales.
    Entendez-vous le glas lugubre des otages
    Peser sur le marché ses funestes présages ?
    Au large, s’il vous plaît, des livides étals !
    N’allez pas inhaler les poudres sépulcrales
    Ni les âcres potions des vendeurs nécrophages.

    Dépassez les légions des zombies belliqueux
    Levés d’entre les morts par les nécromanciens
    Pour combler le néant et l’orgueil insidieux
    Qui leur ronge le coeur de ses griffes d’airain.
    Evitez leurs regards, ne fixez pas leurs yeux !
    Dépassez sans traîner les zombies belliqueux
    Levés d’entre les morts par les nécromanciens.

    Crachés par des dragons aux têtes de gargouilles,
    Les neuf fleuves de feu surgiront devant vous.
    Evitez de troubler les antres des fripouilles,
    La rance hypocrisie, la flatterie qui grouille
    Et traversez à gué sans donner rendez-vous
    Aux neuf fleuves de feu qui flambent devant vous,
    Crachés par des dragons aux têtes de gargouilles.

    Vous devrez vaincre encor l’aveu de vos faiblesses :
    Ses caresses, son fouet vous barreront la route.
    La peur peut s’infiltrer dès que l'âme se blesse :
    Combattez l’illusion sinon c’est la déroute !
    C’est en vous qu’est la voie pour balayer vos doutes,
    Dissiper le brouillard âpre de vos faiblesses
    Et vaincre tous ces fous qui vous barrent la route.

    Vous entrerez alors au centre de l’abîme
    Où il n’y a que vous, vous et votre reflet.
    Là, nul pandémonium, nul passeur, nul soufflet
    Attisant la douleur de démentes victimes,
    Nul cerbère aux aguets, nul élysée sublime.
    Non, il n’y a que vous, vous et votre reflet
    Et votre écho lointain au centre de l’abîme.

    Si vous entendez bien ce que dit le miroir,
    Continuez sans crainte et passez l’autre seuil.
    Le bestiaire, effrayé au son du verbe croire,
    Fuira la vérité qui brille dans le noir.
    La lumière est ton guide à travers les écueils !
    Oui, si tu entends bien ce que dit le miroir,
    Tu peux continuer et passer l’autre seuil.

    Les acteurs, le décor de l’immense hologramme,
    Lémures et furies se dissoudront soudain.
    Un leurre, composé sur des idéogrammes !
    Un simple épouvantail aux couleurs d’oriflamme !
    Tout n’est-il qu’un théâtre au ton grave ou badin ?
    Harpies, chauves-souris se dissoudront soudain,
    Suivis par le décor de l’immense hologramme.

    Tu devrais déboucher sous un dolmen antique,
    Sanctuaire ou palais, non loin des antipodes.
    Tu peux aussi voler sur les ailes d’une ode,
    Suivre le cours serein d’une géodésique
    Et, guidé par l'éclat des plus belles géodes,
    Atterrir au milieu d’une clairière antique :
    Les pyramides d’or mènent aux antipodes.
#+END_VERSE
#+END_CENTER

 

[[../index.php][Accueil]]
