
#+STARTUP: showall

#+TITLE: Eclats de vers : Physics 01 : Mécanique
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Notation


** Dérivées temporelles

Pour une fonction $x$ dépendant du temps $t$, nous utilisons la notation :

$$\dot{x} = \OD{x}{t}$$

pour la dérivée première et :

$$\ddot{x} = \OOD{x}{t}$$

pour la dérivée seconde.


** Vecteurs tridimensionnels

  - Les vecteurs tridimensionnels sont notés en gras

  - Les composantes de ces vecteurs sont notées en fonte ordinaire
    avec des indices

  - Leur norme est notée en fonte ordinaire

Voici par exemple un vecteur tridimensionnel $\mathbf{u}$, de
composantes $u_i$ et de norme :

$$u = \norme{\mathbf{u}} = \sqrt{\sum_{i=1}^3 u_i^2}$$


* Corps ponctuel

Dans ce chapitre, nous négligeons les effets mécaniques des dimensions
du corps dont nous analysons la trajectoire.

** Lois de Newton

Soit la trajectoire $\mathbf{r} : \setR \mapsto \setR^3$ qui fait
correspondre, à un instant donné $t$, la position $\mathbf{r}(t)$ d’un corps
dans l'espace tridimensionnel.

La vitesse du corps s’écrit alors :

$$\dot{\mathbf{r}} = \OD{\mathbf{r}}{t}$$

et l’accélération :

$$\ddot{\mathbf{r}} = \OOD{\mathbf{r}}{t}$$

Nous notons :

#+ATTR_HTML: :class plat
| $m$          | La masse du corps           |
| $\mathbf{F}$ | La force appliquée au corps |

Nous définissons la quantité de mouvement $\mathbf{p}$ par :

$$\mathbf{p} = m \dot{\mathbf{r}}$$

Les lois de Newton s’énoncent :

  1. En l’absence de force appliquée, un corps continue en ligne droite
     à la même vitesse

  2. Principe fondamental de la dynamique : $\dot{\mathbf{p}} = \mathbf{F}$

  3. À chaque action appliquée par un corps sur un autre, correspond
     une réaction, force égale en intensité à l’action mais appliquée
     dans la direction opposée


** Principe fondamental de la dynamique

Comme la masse du corps ne dépend pas du temps, la dérivée de la
quantité de mouvement peut s’écrire :

$$\dot{\mathbf{p}} = m \ddot{\mathbf{r}}$$

Le principe fondamental de la dynamique devient :

$$m \ddot{\mathbf{r}} = \mathbf{F}$$


** Énergie


*** Énergie cinétique

Si nous effectuons le produit scalaire du principe fondamental de la
dynamique avec $\dot{\mathbf{r}}$, nous obtenons :

$$m \ddot{\mathbf{r}} \cdot \dot{\mathbf{r}} = \mathbf{F} \cdot \dot{\mathbf{r}}$$

or :

\begin{align}
\OD{\dot{r}^2}{t}  &= \OD{}{t} \left[ \dot{\mathbf{r}} \cdot \dot{\mathbf{r}}\right]
= \OD{}{t} \sum_{i=1}^3  \dot{r}_i^2
= \sum_{i=1}^3 2 \dot{r}_i \ddot{r}_i
= 2 \dot{\mathbf{r}} \cdot \ddot{\mathbf{r}}
\end{align}

On en déduit que :

$$ \OD{}{t} \left[ \frac{\dot{r}^2}{2} \right] = \dot{\mathbf{r}} \cdot \ddot{\mathbf{r}}$$

Si nous définissons l’énergie cinétique $T$ par :

$$T = \unsur{2} m \dot{r}^2$$

nous avons :

$$\dot{T} = m \dot{\mathbf{r}} \cdot \ddot{\mathbf{r}} = \mathbf{F} \cdot \dot{\mathbf{r}}$$


*** Énergie potentielle

Quand la force appliquée $\mathbf{F}$ ne dépend que de la position
$\mathbf{r}$, il est parfois possible de trouver une énergie
potentielle :

$$U : \setR^3 \mapsto \setR$$

telle que :

$$\partial_i U = - F_i$$

ce que nous notons :

$$\deriveepartielle{U}{\mathbf{r}} = - \mathbf{F}$$

La dérivée temporelle de $U$ s’écrit alors :

$$\dot{U} = \deriveepartielle{U}{\mathbf{r}} \cdot \dot{\mathbf{r}} = - \mathbf{F} \cdot \dot{\mathbf{r}}$$


*** Énergie totale

Le principe fondamental de la dynamique peut se réécrire en fonction
des énergies cinétique et potentielle :

$$\dot{T} = - \dot{U}$$

Autrement dit, lorsque la force appliquée dépend d’une énergie potentielle :

$$\OD{}{t} \left[ T + U \right] = 0$$

L’énergie totale :

$$E = T + U$$

est donc constante :

$$\dot{E} = 0$$


** Mécanique Lagrangienne

Nous allons tenter de relier le principe fondamental de la dynamique
aux équations d’[[file:matemat-11-equadiff.org::#heading:eulerLagrange][Euler - Lagrange]]. Nous supposons que la force
appliquée peut être dérivée d’une énergie potentielle.

Comme l’énergie cinétique ne dépend pas explicitement de la position,
on a :

$$\deriveepartielle{T}{\mathbf{r}} = 0$$

Par définition, on a aussi :

$$\deriveepartielle{U}{\mathbf{r}} = - \mathbf{F}$$

La dérivée de l’énergie cinétique par rapport aux composantes de
la vitesse s’écrit :

$$\deriveepartielle{T}{\dot{r}_i} = m \dot{r}_i$$

ou, en notation vectorielle :

$$\deriveepartielle{T}{\dot{\mathbf{r}}} = m \dot{\mathbf{r}}$$

En dérivant par rapport au temps, on obtient :

$$\OD{}{t}\deriveepartielle{T}{\dot{\mathbf{r}}} = m \ddot{\mathbf{r}}$$

Par ailleurs, comme $U$ ne dépend pas explicitement de la vitesse :

$$\deriveepartielle{U}{\dot{\mathbf{r}}} = 0$$

et :

$$\OD{}{t}\deriveepartielle{U}{\dot{\mathbf{r}}} = 0$$

Définissons le Lagrangien :

$$\lagrangien = T - U$$

On a :

$$\deriveepartielle{\lagrangien}{\mathbf{r}}
= \deriveepartielle{}{\mathbf{r}}\left(T - U\right) = \mathbf{F}$$

et :

$$\OD{}{t}\deriveepartielle{\lagrangien}{\dot{\mathbf{r}}}
= \OD{}{t}\deriveepartielle{}{\dot{\mathbf{r}}}\left(T - U \right)
= m \ddot{\mathbf{r}}$$

Le principe fondamental de la dynamique peut alors s’écrire :

$$\OD{}{t}\deriveepartielle{\lagrangien}{\dot{\mathbf{r}}} = \deriveepartielle{\lagrangien}{\mathbf{r}}$$

ou :

$$\deriveepartielle{\lagrangien}{\mathbf{r}} - \OD{}{t}\deriveepartielle{\lagrangien}{\dot{\mathbf{r}}} = 0$$

Si nous connaissans les positions $\mathbf{r}(t_1)$ et
$\mathbf{r}(t_2)$ aux temps $t_1$ et $t_2$, résoudre cette équation
revient à trouver la trajectoire $\mathbf{r}$ qui minimise l’intégrale
de $\lagrangien$ entre $t_1$ et $t_2$. Nous appelons *action* cette
quantité à minimiser, et la notons :

$$\mathcal{S} = \int_{t_1}^{t_2} \lagrangien(\mathbf{r}(t),\dot{\mathbf{r}}(t))\ dt$$

*** Force et quantité de mouvement

Si on connait le Lagrangien, on peut retrouver la force par :

$$\mathbf{F} = \deriveepartielle{\lagrangien}{\mathbf{r}}$$

Comme :

$$\dot{\mathbf{p}} = m \ddot{\mathbf{r}} =
\OD{}{t}\deriveepartielle{\lagrangien}{\dot{\mathbf{r}}}$$


on retrouve la quantité de mouvement en utilisant :

$$\mathbf{p} = \deriveepartielle{\lagrangien}{\dot{\mathbf{r}}}$$


** Mécanique Hamiltonienne

Nous notons :

| $\mathcal{H}$ | Hamiltonien |


La mécanique Hamiltonienne ajoute le produit de la quantité de
mouvement par la vitesse au Lagrangien, et utilise la quantité de
mouvement au lieu de la vitesse :

$$\mathcal{H}(\mathbf{r}, \mathbf{p}, t) =
\mathbf{p}\cdot\dot{\mathbf{r}} - \lagrangien(\mathbf{r}, \mathbf{\dot{r}}, t)$$


*** Énergie

Comme :

$$\mathbf{p}\cdot\dot{\mathbf{r}} = m \dot{r}^2 = 2 T$$

on a :

$$\mathcal{H} = 2 T - \lagrangien = 2 T - (T - U) = T + U = E$$


*** Énergie cinétique et quantité de mouvement

Comme :

$$\dot{\mathbf{r}} = \frac{\mathbf{p}}{m}$$

$$\dot{r}^2 = \frac{p^2}{m^2}$$

on a :

$$T = \unsur{2} m \dot{r}^2 = \frac{p^2}{2 m}$$

et :

$$\mathcal{H} = \frac{p^2}{2 m} + U$$


*** Principe fondamental

On note que :

$$\deriveepartielle{\mathcal{H}}{\mathbf{p}} = \dot{\mathbf{r}}$$

$$\deriveepartielle{\mathcal{H}}{\mathbf{r}}
= - \deriveepartielle{\lagrangien}{\mathbf{r}}
= -F = - \dot{\mathbf{p}}$$

L’ensemble :

$$\deriveepartielle{\mathcal{H}}{\mathbf{p}} = \dot{\mathbf{r}}$$

$$\deriveepartielle{\mathcal{H}}{\mathbf{r}} = - \dot{\mathbf{p}}$$

constitue les équations de Hamilton du corps ponctuel.


* TODO Corps rigide

** TODO Cinématique



* Système de corps rigides

Nous considérons un système de $N$ corps rigides.

Soit $C$ le nombre de contraintes appliquées au système. Le nombre de
degrés de liberté du système est alors de $n = 3 N - C$.

Nous notons $m_k$ la masse du corps $k$ et $\mathbf{r}_k$ la position
du corps $k$. La force appliquée au corps $k$ sera notée
$\mathbf{F}_k$.

** Principe de d’Alembert

Nous exprimons la force $\mathbf{F}_k$ appliquée au corps $k$ comme la somme de
la force due aux contraintes $\mathbf{C}_k$ et de la force qui n’est pas due
aux contraintes $\mathbf{N}_k$ :

$$\mathbf{F}_k = \mathbf{N}_k + \mathbf{C}_k$$

Les contraintes des systèmes mécaniques sont dues à des articulations
qui empêchent certaines pièces de bouger suivant certaines directions
de translation ou de rotation.

Les forces qui maintiennent ces articulations en place sont parallèles
aux mouvements potentiels qu’elles empêchent. Elles doivent donc être
perpendiculaires aux mouvements réels observés.

Si nous choisissons de petits déplacements virtuels
$\delta\mathbf{r}_k$ qui respectent les contraintes, la condition de
perpendicularité s’exprime :

$$\mathbf{C}_k\cdot\delta\mathbf{r}_k = 0$$

Comme :

$$\sum_k \left( \mathbf{N}_k + \mathbf{C}_k - m_k \mathbf{\ddot{r}}_k  \right) = 0$$

on a :

$$\sum_k \left( \mathbf{N}_k + \mathbf{C}_k - m_k \mathbf{\ddot{r}}_k  \right) \cdot \delta\mathbf{r}_k = 0$$

Comme les forces de contraintes sont orthogonales, l’équation devient :

$$\sum_k \left( \mathbf{N}_k - m_k \mathbf{\ddot{r}}_k  \right) \cdot \delta\mathbf{r}_k = 0$$


** Coordonnées généralisées

Pour tenir compte des contraintes appliquées au système, on exprime
les positions $\mathbf{r}_i$ en fonction des coordonnées généralisées
$q_1, q_2, ..., q_n$. On note :

$$\mathbf{q} = (q_1, q_2, ..., q_n)$$

le vecteur des coordonnées généralisées. Ces coordonnées sont choisies
pour que le système respecte naturellement ses contraintes, et on peut
alors ignorér les forces qui garantissent le respect de ces contraintes.

** Annulation des points

Comme $\mathbf{r}$ dépend de $(\mathbf{q},t)$, on a :

$$\dot{\mathbf{r}} = \sum_i \deriveepartielle{\mathbf{r}}{q_i} \dot{q}_i +
\deriveepartielle{\mathbf{r}}{t}$$

En dérivant à noveau, on obtient :

$$\ddot{\mathbf{r}} = \sum_i \deriveepartielle{\mathbf{\dot{r}}}{q_i} \dot{q}_i +
\sum_i \deriveepartielle{\mathbf{r}}{q_i} \ddot{q}_i +
\deriveepartielle{\mathbf{\dot{r}}}{t}$$

Mais comme $\dot{\mathbf{r}}$ dépend de $(\mathbf{q},
\dot{\mathbf{q}}, t)$, on a aussi :

$$\ddot{\mathbf{r}} = \sum_i \deriveepartielle{\dot{\mathbf{r}}}{q_i} \dot{q}_i +
\sum_i \deriveepartielle{\dot{\mathbf{r}}}{\dot{q}_i} \ddot{q}_i +
\deriveepartielle{\mathbf{\dot{r}}}{t}$$

En égalant les deux équations, on obtient, après annulation des termes
identiques :

$$\sum_i \deriveepartielle{\dot{\mathbf{r}}}{\dot{q}_i} \ddot{q}_i =
\sum_i \deriveepartielle{\mathbf{r}}{q_i} \ddot{q}_i$$

ou :

$$\sum_i \deriveepartielle{\dot{\mathbf{r}}}{\dot{q}_i} d\dot{q}_i =
\sum_i \deriveepartielle{\mathbf{r}}{q_i} d\dot{q}_i$$

Comme cette équation est valable pour toute variation $d\dot{q}_i$, on
a :

$$\deriveepartielle{\dot{\mathbf{r}}}{\dot{q}_i} = \deriveepartielle{\mathbf{r}}{q_i} $$


** Mécanique Lagrangienne

L’équation de Lagrange devient :

$$\deriveepartielle{\lagrangien}{\mathbf{q}} - \OD{}{t}\deriveepartielle{\lagrangien}{\dot{\mathbf{q}}} = 0$$

Par analogie avec le corps ponctuel, nous appelons *force généralisée*
la quantité :

$$\mathbf{F} = \deriveepartielle{\lagrangien}{\mathbf{q}}$$

et *quantité de mouvement généralisée* la quantité :

$$\mathbf{p} = \deriveepartielle{\lagrangien}{\dot{\mathbf{q}}}$$

** Mécanique Hamiltonienne

La mécanique Hamiltonienne ajoute le produit de la quantité de
mouvement par la vitesse au Lagrangien, et utilise la quantité de
mouvement au lieu de la vitesse :

$$\mathcal{H}(\mathbf{r}, \mathbf{p}, t) =
\sum_i \mathbf{p}_i\cdot\dot{\mathbf{q}}_i - \lagrangien(\mathbf{q}, \mathbf{\dot{q}}, t)$$


*** Principe fondamental

On note que :

$$\deriveepartielle{\mathcal{H}}{\mathbf{p}} = \dot{\mathbf{q}}$$

$$\deriveepartielle{\mathcal{H}}{\mathbf{q}}
= - \deriveepartielle{\lagrangien}{\mathbf{q}}
= - \mathbf{F} = - \dot{\mathbf{p}}$$

L’ensemble :

$$\deriveepartielle{\mathcal{H}}{\mathbf{p}} = \dot{\mathbf{q}}$$

$$\deriveepartielle{\mathcal{H}}{\mathbf{q}} = - \dot{\mathbf{p}}$$

constitue les équations de Hamilton du corps ponctuel.


*** Comparaison Lagrangien et Hamiltonien

Calculons la variation du Lagrangien :

$$d\lagrangien =
\sum_i \left( \deriveepartielle{\lagrangien}{q_i}\ dq_i +
\deriveepartielle{\lagrangien}{\dot{q}_i}\ d\dot{q}_i \right) +
\deriveepartielle{\lagrangien}{t}\ dt$$

En utilisant la définition de la quantité de mouvement généralisée, on
a :

$$d\lagrangien =
\sum_i \left( \deriveepartielle{\lagrangien}{q_i}\ dq_i +
p_i\ d\dot{q}_i \right) +
\deriveepartielle{\lagrangien}{t}\ dt$$

En utilisant la dérivation par parties :

$$d\lagrangien =
\sum_i \left( \deriveepartielle{\lagrangien}{q_i}\ dq_i +
d(p_i\ \dot{q}_i) - \dot{q}_i\ dp_i \right) +
\deriveepartielle{\lagrangien}{t}\ dt$$

En réarrangeant :

$$d\left(\sum_i p_i\ \dot{q}_i - \lagrangien \right) =
\sum_i \left(- \deriveepartielle{\lagrangien}{q_i}\ dq_i +
\dot{q}_i\ dp_i \right) -
\deriveepartielle{\lagrangien}{t}\ dt$$

Le membre de gauche représente une variation de l’Hamiltonien :

$$d\mathcal{H} =
\sum_i \left(- \deriveepartielle{\lagrangien}{q_i}\ dq_i +
\dot{q}_i\ dp_i \right) -
\deriveepartielle{\lagrangien}{t}\ dt$$

On compare avec le calcul direct d’une variation de l’Hamiltonien :

$$d\mathcal{H} =
\sum_i \left(\deriveepartielle{\mathcal{H}}{q_i}\ dq_i +
\deriveepartielle{\mathcal{H}}{p_i}\ dp_i \right) +
\deriveepartielle{\mathcal{H}}{t}\ dt$$

On en déduit les équivalences suivantes :

$$\deriveepartielle{\mathcal{H}}{q_i} = - \deriveepartielle{\lagrangien}{q_i}$$

$$\deriveepartielle{\mathcal{H}}{p_i} = \dot{q}_i$$

$$\deriveepartielle{\mathcal{H}}{t} = - \deriveepartielle{\lagrangien}{t}$$

La solution qui nous intéresse vérifie l’équation de Lagrange :

$$\deriveepartielle{\lagrangien}{q_i} = \OD{}{t}\deriveepartielle{\lagrangien}{\dot{q}_i}$$

En utilisant la quantité de mouvement généralisée, nous obtenons :

$$\deriveepartielle{\lagrangien}{q_i} = \dot{p}_i$$

Les équation de Hamilton s’écrivent alors :

$$\deriveepartielle{\mathcal{H}}{q_i} = - \dot{p}_i$$

$$\deriveepartielle{\mathcal{H}}{p_i} = \dot{q}_i$$

$$\deriveepartielle{\mathcal{H}}{t} = - \deriveepartielle{\lagrangien}{t}$$
