
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Aire dans le plan
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Carré unitaire

Un carré unitaire est un carré dont la longueur du coté vaut 1.

** Définition

L’aire d’une figure géométrique $F$ est le nombre de carrés
unitaires qu’elle peut contenir. On la note :

$$ \aire(F) $$

* Rectangle

#+TOC: headlines 1 local

** Dimensions égales

TODO : preuve

Un rectangle possède deux grands et deux petits côtés. On nomme :

- longueur du rectangle la longueur de chacun des grands côtés
- largeur du rectangle la longueur de chacun des petits côtés

** Dimensions entières

Un rectangle de longueur $m \in \setN$ et de largeur $n \in \setN$ peut
contenir un tableau de carrés unitaire comprenant $m$ lignes et $n$
colonnes. Son aire vaut donc :

$$ m \cdot n $$

par définition de la multiplication dans les nombres naturels.

** Dimensions rationnelles

TODO : détailler

Dans le cas où les dimensions du rectangle sont rationnelles, on peut
utiliser une unité secondaire, définie comme une fraction de l’unité
principale. On montre alors que l’aire vaut là aussi le produit des
dimensions du rectangle.

** Dimensions réelles

Il suffit ensuite de choisir des suites de rationnels et de passer à
la limite vers une longueur $L \in \setR$ et une largeur $h \in \setR$
pour montrer que l’aire $A$ du rectangle vaut :

$$ A = L \ h $$
* Triangle

#+TOC: headlines 1 local

** Triangle rectangle

Le schéma ci-dessous représente un rectangle découpé en deux triangles
rectangles :

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-rectangle.svg]]

Que vaut l’aire $T$ du triangle rectangle $ABC$ ? On sait que l’aire
$R$ du rectangle $ABCD$ vaut :

$$ R = a \ b $$

Or, ce rectangle contient deux triangles rectangles qui ont la même
aire par symétrie : $ABC$ et $ACD$. On a donc :

$$ R = 2 \ T $$

Isolons l’aire du triangle :

$$ T = \frac{R}{2} $$

Remplaçons $R$ par son expression :

$$ T = \frac{a \ b}{2} $$

L’aire d’un triangle rectangle vaut la moitié du produit de ses
cathètes.

** Triangle acutangle

Soit le triangle acutangle $ABC$ représenté ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-acutangle.svg]]

Ce triangle peut se décomposer en deux triangles rectangles :

- $ADC$ à gauche
- $DBC$ à droite

L’aire $A_G$ du triangle rectangle $ADC$ vaut :

$$ A_G = \frac{u \ h}{2} $$

L’aire $A_D$ du triangle rectangle $DBC$ vaut :

$$ A_D = \frac{v \ h}{2} $$

L’aire totale $A_T$ du triangle $ABC$ est égale à la somme des aires
des deux triangles rectangles :

$$ A_T = A_G + A_D = \frac{u \ h}{2} + \frac{v \ h}{2} $$

ce qui nous donne :

$$ A_T = \frac{u \ h + v \ h}{2} $$

Mettons la hauteur $h$ en évidence :

$$ A_T = \frac{(u + v) \ h}{2} $$

Comme la base $b$ vaut :

$$ b = u + v $$

On a montré que l’aire du triangle $ABC$ vaut :

$$ A_T = \frac{b \ h}{2} $$

c’est-à-dire la moitié de la base multipliée par la hauteur.

** Triangle obtusangle

Soit le triangle obtusangle $ABC$ représenté ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-obtusangle.svg]]

Le rectangle $ADCE$ est de longueur $b + u$ et de largeur $h$. Son aire
vaut donc :

$$ R = (b + u) \ h $$

Pour obtenir l’aire du triangle $ABC$, il nous faut enlever les aires
des triangles rectangles $BDC$ et $ACE$.

L’aire $A_D$ du triangle rectangle $BDC$ vaut :

$$ A_D = \frac{u \ h}{2} $$

L’aire $A_G$ du triangle rectangle $ACE$ vaut :

$$ A_G = \frac{(b + u) \ h}{2} $$

L’aire $A_T$ du triangle $ABC$ est donc égale à :

$$ A_T = R - A_G - A_D = (b + u) \ h - \frac{u \ h}{2} - \frac{(b + u) \ h}{2} $$

Mettons les termes du membre de droite au même dénominateur :

$$ A_T = \frac{2 \ (b + u) \ h - u \ h - (b + u) \ h}{2} $$

Plaçons la hauteur $h$ en évidence :

$$ A_T = \frac{(2 \ b + 2 \ u - u - b - u) \ h}{2} $$

On obtient finalement :

$$ A_T = \frac{b \ h}{2} $$

c’est-à-dire la moitié de la base multipliée par la hauteur.

* Théorème de Pythagore

#+TOC: headlines 1 local

** Introduction

Soit le triangle :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/longueurs-triangle-rectangle.svg]]

Nous allons montrer une importante relation entre les longueurs $a,b,c$
en utilisant le schéma suivant :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pythagore.svg]]

Aire de chaque triangle rectangle :

$$ A_T = \frac{a b}{2} $$

Aire du grand carré d’après son côté $a+b$ :

$$ A = (a+b)^2 = a^2 + 2 \ a \ b + b^2 $$

Aire du grand carré exprimé comme la somme des aires du carré et
des triangles qu’il contient :

$$ A = c^2 + 4 \cdot A_T = c^2 + 4 \cdot \frac{a \ b}{2} = c^2 + 2 \ a \ b $$

Comme les deux expressions de $A$ sont égales, on a :

$$ a^2 + 2 \ a \ b + b^2 = c^2 + 2 \ a \ b $$

ce qui donne en simplifiant :

$$ a^2 + b^2 = c^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

La longueur $c$ étant un réel positif, on en déduit immédiatement que :

$$ c = \sqrt{a^2 + b^2} $$

** Triangles de Pythagore

Un triangle de Pythagore est un triangle rectangle où les longueurs
des trois côtés sont des nombres entiers.

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-pythagore.svg]]

La figure ci-dessus utilise une astuce algébrique pour obtenir certains
triangles de Pythagore. En effet :

\begin{align*}
A^2 + B^2
&= \left(a^2 - b^2\right)^2 + \left(2 \ a \ b\right)^2 \\
&= a^4 - 2 \ a^2 \ b^2 + b^4 + 4 \ a^2 \ b^2 \\
&= a^4 + 2 \ a^2 \ b^2 + b^4 \\
&= \left(a^2 + b^2\right)^2
\end{align*}

et finalement :

$$ A^2 + B^2 = C^2 $$

Choisir de telles expressions pour $A$, $B$, $C$ nous assure d’avoir
des longueurs qui respectent le théorème de Pythagore. De plus, si
les longueurs $a$, $b$, $c$ sont entières, les longueurs $A$, $B$,
$C$ le seront également. Le tableau suivant nous donne les premiers
triangles de Pythagore obtenus avec cette méthode.

| $a$ | $b$ | $A$ | $B$ | $C$ |
|-----+-----+-----+-----+-----|
|   2 |   1 |   3 |   4 |   5 |
|   3 |   2 |   5 |  12 |  13 |
|   4 |   1 |   8 |  15 |  17 |
|   4 |   3 |   7 |  24 |  25 |
|   5 |   2 |  20 |  21 |  29 |
|   5 |   4 |   9 |  40 |  41 |
|   6 |   1 |  12 |  35 |  37 |
|   6 |   5 |  11 |  60 |  61 |
|   7 |   2 |  28 |  45 |  53 |
|   7 |   4 |  33 |  56 |  65 |
|   7 |   6 |  13 |  84 |  85 |

** Propriétés des cathètes

Examinons le triangle rectangle ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cathetes.svg]]

L’hypothénuse $c$ y est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle rectangle principal en deux
triangles rectangles : $a,h,u$ et $b,h,c$.

*** Carré de la hauteur

Le théorème de Pythagore appliqué au triangle rectangle principal nous
donne :

$$ a^2 + b^2 = c^2 $$

On sait déjà que $c = u + v$. Par ailleurs, le théorème de Pythagore
appliqué au triangle rectangle de gauche nous donne :

$$ h^2 + u^2 = a^2 $$

Le théorème de Pythagore appliqué au triangle rectangle de droite nous
donne :

$$ h^2 + v^2 = b^2 $$

On peut se servir de ces expressions pour substituer les valeurs de $a$
et $b$ dans le triangle principal :

$$ (h^2 + u^2) + (h^2 + v^2) = (u+v)^2 $$

ou encore :

$$ 2 \ h^2 + u^2 + v^2 = u^2 + 2 \ u \ v + v^2 $$

En simplifiant, il vient :

$$ 2 \ h^2 = 2 \ u \ v $$

On obtient finalement :

$$ h^2 = u \ v $$

*** Carré des cathètes

On reprend le théorème de Pythagore dans le triangle de gauche :

$$ a^2 = u^2 + h^2 $$

et on remplace le carré de la hauteur par le produit $u\ v$ :

$$ a^2 = u^2 + u \ v $$

On met ensuite $u$ en évidence :

$$ a^2 = u \ (u + v) $$

ce qui nous donne :

$$ a^2 = u \ c $$

On utilise le même procédé dans le triangle de droite :

\begin{align*}
b^2
&= v^2 + h^2 \\
&= v^2 + u \ v \\
&= v \ (u + v) \\
\end{align*}

ce qui nous donne :

$$ b^2 = v \ c $$

*** Produit des cathètes

En multipliant les équations :

$$ a^2 = u \ c $$

$$ b^2 = v \ c $$

ensemble, on obtient :

$$ a^2 \ b^2 = u \ c \ v \ c $$

ou encore :

$$ a^2 \ b^2 = u \ v \ c^2 $$

Le produit $u \ v$ étant identique à la hauteur, on a :

$$ a^2 \ b^2 = h^2 \ c^2 $$

et finalement :

$$ a \ b = h \ c $$

* Distance entre un point et une droite

* Trapèze

* Parallélogramme

