
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Aire dans le plan
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Carré unitaire

Un carré unitaire est un carré dont la longueur du coté vaut 1.

** Définition

L’aire d’une figure géométrique $\mathcal{F}$ est le nombre de
carrés unitaires qu’elle peut contenir. On la note :

$$ \aire(\mathcal{F}) $$

* Rectangle

#+TOC: headlines 1 local

** Dimensions entières

Soit un rectangle mesurant $m$ unités de longueur et $n$ de largeur,
où $m$ et $n$ sont des nombres naturels non nuls. Le schéma ci-dessous
nous en donne un exemple avec $m = 4$ et $n = 3$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-rectangle-entiers.svg]]

On voit que ce rectangle peut contenir un tableau de carrés unitaires
comprenant $m$ lignes et $n$ colonnes. Son aire $A$ vaut donc :

$$ A = m \cdot n $$

par définition de la multiplication dans les nombres naturels. L’aire
d’un rectangle de mesures entières est donc égale au produit de sa
longueur par sa largeur.

** Dimensions rationnelles

Nous allons tenter de généraliser le résultat précédent à des
mesures rationnelles, en utilisant une unité secondaire, définie
comme une fraction de l’unité principale. Considérons un rectangle
de longueur :

$$ L = \frac{m}{i} $$

et de largeur :

$$ l = \frac{n}{j} $$

où $m,n,i,j$ sont des nombres naturels non nuls. Mettons ces deux
fractions au même dénominateur :

$$ L = \frac{m \ j}{i \ j}
\qquad \qquad \qquad
l = \frac{n \ i}{j \ i} $$

Nous allons à présent scinder l’unité principale, de longueur $1$,
en $i \cdot j$ unités secondaires. La longueur de cette unité secondaire
vaut :

$$ \sigma = \unsur{i \ j} $$

Les dimensions du rectangle peuvent se réécrire :

$$ L = (m \ j) \ \sigma $$

$$ l = (n \ i) \ \sigma $$

Notre rectangle mesure donc $m \cdot j$ unités secondaires en longueur
et $n \cdot i$ unités secondaires en largeur. Remarquons que ces
dimensions sont des nombres naturels non nuls.

Nous appelons :

- carré unitaire principal : un carré dont le côté mesure 1 unité principal
- carré unitaire secondaire : un carré dont le côté mesure 1 unité secondaire

le schéma ci-dessous nous donne un exemple de carré unitaire principal,
dont le côté mesure $i \cdot j = 6$ unités secondaires :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre-unitaire-en-unites-secondaires.svg]]

On voit qu’un carré unitaire principal peut contenir :

$$ (i \cdot j) \cdot (i \cdot j) = (i \cdot j)^2 = i^2 \cdot j^2 $$

carrés unitaires secondaires. L’aire $P$ d’un carré unitaire
principal vaut donc $i^2 \cdot j^2$ fois l’aire $S$ d’un carré
unitaire secondaire :

$$ P = (i^2 \ \ j^2) \ S $$

Isolons $S$ :

$$ S = \frac{P}{i^2 \ \ j^2} $$

Comme $P$ vaut $1$ par définition de l’aire, on a finalement :

$$ S = \unsur{i^2 \ \ j^2} = \sigma^2 $$

Exprimées en unités secondaires, les dimensions de notre rectangle
valent $m \cdot j$ et $n \cdot i$. Ce rectangle compte donc au total :

$$ m \ n \ i \ j = \frac{m \ n}{\sigma} $$

carrés unitaires secondaires. Comme l’aire de chaque carré unitaire
secondaire vaut $S = \sigma^2$, l’aire $A$ de notre rectangle vaut :

$$ A
= \frac{m \ n}{\sigma} \cdot \sigma^2
= m \ n \ \sigma = \frac{m \ n}{i \ j} $$

c’est-à-dire :

$$ A = \frac{m}{i} \cdot \frac{n}{j} $$

Le membre de droite n’est rien d’autre que le produit des dimensions
du rectangle, exprimées en unités principales :

$$ A = L \cdot l $$

L’aire d’un rectangle de mesures rationnelles est aussi égale au
produit de sa longueur par sa largeur.

** Dimensions réelles

Soit un rectangle $R$ de dimensions réelles :

- $L$ en longueur
- $l$ en largeur

On choisit des suites de rationnels $(L_n)_{n \in \setN}$ et $(l_n)_{n
\in \setN}$ telles que :

$$ \lim_n L_n = L
\qquad \qquad \qquad
\lim_n l_n = l $$

On a alors une suite de rectangles $R_n$, de dimensions $L_n$ et $l_n$
et d’aires :

$$ A_n = L_n \ l_n $$

Il est raisonnable de définir l’aire $A$ du rectangle $R$ comme la
limite de la suite des $A_n$ :

$$ A = \lim_n A_n = \lim_n (L_n \ l_n) $$

En utilisant les propriétés des limites, cette équation devient :

$$ A = \left[ \lim_n L_n \right] \cdot \left[ \lim_n l_n \right] $$

et finalement :

$$ A = L \cdot l $$

L’aire d’un rectangle de mesures réelles est aussi égale au
produit de sa longueur par sa largeur.

* Triangle

#+TOC: headlines 1 local

** Triangle rectangle

#+TOC: headlines 1 local

*** Cathètes

Le schéma ci-dessous représente un rectangle $ABCD$ découpé en deux
triangles rectangles :

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-rectangle.svg]]

Que vaut l’aire $T$ du triangle rectangle $ABC$ ? On sait que l’aire
$R$ du rectangle $ABCD$ vaut :

$$ R = a \ b $$

Or, ce rectangle contient deux triangles rectangles qui ont la même
aire par symétrie : $ABC$ et $ACD$. On a donc :

$$ R = 2 \ T $$

Isolons l’aire du triangle :

$$ T = \frac{R}{2} $$

Remplaçons $R$ par son expression :

$$ T = \frac{a \ b}{2} $$

L’aire d’un triangle rectangle vaut la moitié du produit de ses
cathètes.

*** Hypothénuse et hauteur

** Triangle acutangle

Soit le triangle acutangle $ABC$ représenté ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-acutangle.svg]]

Ce triangle peut se décomposer en deux triangles rectangles :

- $ADC$ à gauche
- $DBC$ à droite

L’aire $A_G$ du triangle rectangle $ADC$ de gauche vaut :

$$ A_G = \frac{u \ h}{2} $$

L’aire $A_D$ du triangle rectangle $DBC$ de droite vaut :

$$ A_D = \frac{v \ h}{2} $$

L’aire totale $T$ du triangle $ABC$ est égale à la somme des aires
des deux triangles rectangles :

$$ T = A_G + A_D = \frac{u \ h}{2} + \frac{v \ h}{2} $$

ce qui nous donne :

$$ T = \frac{u \ h + v \ h}{2} $$

Mettons la hauteur $h$ en évidence :

$$ T = \frac{(u + v) \ h}{2} $$

Comme la base $b$ vaut :

$$ b = u + v $$

On a montré que l’aire du triangle $ABC$ vaut :

$$ T = \frac{b \ h}{2} $$

c’est-à-dire la moitié de la base multipliée par la hauteur.

** Triangle obtusangle

Un triangle obtusangle possède deux hauteurs intérieures au triangle.
Nous pouvons bien entendu utiliser l’une d’entre-elles pour calculer
l’aire du triangle. Le procédé est le même que celui utilisé pour
le triangle acutangle. Nous allons à présent examiner la relation
entre la hauteur extérieure du triangle obtusangle et on aire.

Soit le triangle obtusangle $ABC$ représenté ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-obtusangle.svg]]

Le rectangle $ADCE$ est de longueur $b + u$ et de largeur $h$. Son aire
vaut donc :

$$ R = (b + u) \ h $$

Pour obtenir l’aire du triangle $ABC$, il nous faut enlever les aires
des triangles rectangles $BDC$ et $ACE$.

L’aire $A_D$ du triangle rectangle $BDC$ de droite vaut :

$$ A_D = \frac{u \ h}{2} $$

L’aire $A_G$ du triangle rectangle $ACE$ de gauche vaut :

$$ A_G = \frac{(b + u) \ h}{2} $$

L’aire $T$ du triangle $ABC$ est donc égale à :

$$ T = R - A_G - A_D = (b + u) \ h - \frac{u \ h}{2} - \frac{(b + u) \ h}{2} $$

Mettons les termes du membre de droite au même dénominateur :

$$ T = \frac{2 \ (b + u) \ h - u \ h - (b + u) \ h}{2} $$

Plaçons la hauteur $h$ en évidence :

$$ T = \frac{(2 \ b + 2 \ u - u - b - u) \ h}{2} $$

On obtient finalement :

$$ T = \frac{b \ h}{2} $$

c’est-à-dire la moitié de la base multipliée par la hauteur.

* Trapèze

Soit un trapèze $ABCD$ subdivisé en deux triangles :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-trapeze.svg]]

On pose :

$$ B = \abs{EF} $$

$$ b = \abs{GH} $$

Comme les bases $[E,F]$ et $[G,H]$ sont parallèles, les droites qui
les prolongent le sont aussi :

$$ (EF) \parallel (GH) $$

La distance entre ces droites est donc constante et :

$$ h = \abs{HI} = \abs{FJ} $$

On remarque que $h$ est une hauteur des triangles $EFH$ et $HFG$.

L’aire $A_G$ du triangle $EFH$ de gauche vaut :

$$ A_G = \frac{B \ h}{2} $$

L’aire $A_G$ du triangle $HFG$ de droite vaut :

$$ A_D = \frac{b \ h}{2} $$

L’aire $T$ du trapèze est égale à la somme des aires des deux
triangles :

$$ T = A_G + A_D = \frac{B \ h}{2} + \frac{b \ h}{2} $$

ou encore :

$$ T = \frac{B \ h + b \ h}{2} $$

Mettons la hauteur $h$ en évidence :

$$ T = \frac{(B + b) \ h}{2} $$

On voit que l’aire d’un trapèze est égale au produit de la base
moyenne :

$$ \mu = \frac{B + b}{2} $$

par la hauteur $h$ :

$$ T = \mu \ h $$

* Parallélogramme

