
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Aire dans le plan
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Carré unitaire

Un carré unitaire est un carré dont la longueur du coté vaut 1.

** Définition

L’aire d’une figure géométrique $\mathcal{F}$ est le nombre de
carrés unitaires qu’elle peut contenir. On la note :

$$ \aire(\mathcal{F}) $$

* Rectangle

#+TOC: headlines 1 local

** Dimensions entières

Soit un rectangle mesurant $m$ unités de longueur et $n$ de largeur,
où $m$ et $n$ sont des nombres naturels. Le schéma ci-dessous nous en
donne un exemple avec $m = 4$ et $n = 3$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-rectangle-entiers.svg]]

On voit que ce rectangle peut contenir un tableau de carrés unitaires
comprenant $m$ lignes et $n$ colonnes. Son aire $A$ vaut donc :

$$ A = m \cdot n $$

par définition de la multiplication dans les nombres naturels. L’aire
d’un rectangle de mesures entières est donc égale au produit de sa
longueur par sa largeur.

** Dimensions rationnelles

Nous allons tenter de généraliser le résultat précédent à des
mesures rationnelles, en utilisant une unité secondaire, définie
comme une fraction de l’unité principale. Considérons un rectangle
de longueur :

$$ L = \frac{m}{i} $$

et de largeur :

$$ l = \frac{n}{j} $$

où $m,n,i,j$ sont des nombres naturels non nuls. Ces mesures se font dans
une unité que nous appelons unité principale. Nous allons à présent
scinder une unité principale en $ i \cdot j $ unités secondaires. On
a donc :

$$ 1 \ \mathrm{unité\ principale} = (i \cdot j) \ \mathrm{unités\ secondaires} $$

Nous appelons :

- carré unitaire principal : un carré dont le côté mesure 1 unité principal
- carré unitaire secondaire : un carré dont le côté mesure 1 unité secondaire

le schéma ci-dessous nous donne un exemple de carré unitaire principal,
dont le côté mesure $i \cdot j = 6$ unités secondaires :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre-unitaire-en-unites-secondaires.svg]]

on voit qu’un carré unitaire principal peut contenir :

$$ (i \cdot j) \cdot (i \cdot j) = (i \cdot j)^2 $$

carrés unitaires secondaires. Exprimée en carrés unitaires secondaires,
l’aire de notre rectangle vaut :

$$ A = (m \cdot n) \ \mathrm{carrés\ unitaires\ secondaires} $$

ou encore :

$$ A = \frac{m \cdot n}{(i \cdot j)^2} \cdot (i \cdot j)^2 \quad \mathrm{carrés\ unitaires\ secondaires} $$

Comme :

$$ 1 \ \mathrm{carré\ unitaire\ principal} = (i \cdot j)^2 \quad \mathrm{carrés\ unitaires\ secondaires} $$

L’expression de l’aire devient :

$$ A = \frac{m \cdot n}{(i \cdot j)^2} = \frac{m}{i} \cdot \frac{n}{j} $$

c’est-à-dire :

$$ A = L \cdot l $$

L’aire d’un rectangle de mesures rationnelles est aussi égale au
produit de sa longueur par sa largeur.

** Dimensions réelles

Il suffit ensuite de choisir des suites de rationnels et de passer à
la limite vers une longueur $L \in \setR$ et une largeur $h \in \setR$
pour montrer que l’aire $A$ du rectangle vaut :

$$ A = L \ h $$
* Triangle

#+TOC: headlines 1 local

** Triangle rectangle

Le schéma ci-dessous représente un rectangle découpé en deux triangles
rectangles :

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-rectangle.svg]]

Que vaut l’aire $T$ du triangle rectangle $ABC$ ? On sait que l’aire
$R$ du rectangle $ABCD$ vaut :

$$ R = a \ b $$

Or, ce rectangle contient deux triangles rectangles qui ont la même
aire par symétrie : $ABC$ et $ACD$. On a donc :

$$ R = 2 \ T $$

Isolons l’aire du triangle :

$$ T = \frac{R}{2} $$

Remplaçons $R$ par son expression :

$$ T = \frac{a \ b}{2} $$

L’aire d’un triangle rectangle vaut la moitié du produit de ses
cathètes.

** Triangle acutangle

Soit le triangle acutangle $ABC$ représenté ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-acutangle.svg]]

Ce triangle peut se décomposer en deux triangles rectangles :

- $ADC$ à gauche
- $DBC$ à droite

L’aire $A_G$ du triangle rectangle $ADC$ vaut :

$$ A_G = \frac{u \ h}{2} $$

L’aire $A_D$ du triangle rectangle $DBC$ vaut :

$$ A_D = \frac{v \ h}{2} $$

L’aire totale $A_T$ du triangle $ABC$ est égale à la somme des aires
des deux triangles rectangles :

$$ A_T = A_G + A_D = \frac{u \ h}{2} + \frac{v \ h}{2} $$

ce qui nous donne :

$$ A_T = \frac{u \ h + v \ h}{2} $$

Mettons la hauteur $h$ en évidence :

$$ A_T = \frac{(u + v) \ h}{2} $$

Comme la base $b$ vaut :

$$ b = u + v $$

On a montré que l’aire du triangle $ABC$ vaut :

$$ A_T = \frac{b \ h}{2} $$

c’est-à-dire la moitié de la base multipliée par la hauteur.

** Triangle obtusangle

Un triangle obtusangle possède deux hauteurs intérieures au triangle.
Nous pouvons bien entendu utiliser l’une d’entre-elles pour calculer
l’aire du triangle. Le procédé est le même que celui utilisé pour
le triangle acutangle. Nous allons à présent examiner la relation
entre la hauteur extérieure du triangle obtusangle et on aire.

Soit le triangle obtusangle $ABC$ représenté ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-obtusangle.svg]]

Le rectangle $ADCE$ est de longueur $b + u$ et de largeur $h$. Son aire
vaut donc :

$$ R = (b + u) \ h $$

Pour obtenir l’aire du triangle $ABC$, il nous faut enlever les aires
des triangles rectangles $BDC$ et $ACE$.

L’aire $A_D$ du triangle rectangle $BDC$ vaut :

$$ A_D = \frac{u \ h}{2} $$

L’aire $A_G$ du triangle rectangle $ACE$ vaut :

$$ A_G = \frac{(b + u) \ h}{2} $$

L’aire $A_T$ du triangle $ABC$ est donc égale à :

$$ A_T = R - A_G - A_D = (b + u) \ h - \frac{u \ h}{2} - \frac{(b + u) \ h}{2} $$

Mettons les termes du membre de droite au même dénominateur :

$$ A_T = \frac{2 \ (b + u) \ h - u \ h - (b + u) \ h}{2} $$

Plaçons la hauteur $h$ en évidence :

$$ A_T = \frac{(2 \ b + 2 \ u - u - b - u) \ h}{2} $$

On obtient finalement :

$$ A_T = \frac{b \ h}{2} $$

c’est-à-dire la moitié de la base multipliée par la hauteur.

* Trapèze

* Parallélogramme

