
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Angles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Secteur angulaire

Un secteur angulaire est un ensemble de points délimité par deux
demi-droites.

* Angle

#+TOC: headlines 1 local

** Définition

Un angle $\alpha$ est défini par deux demi-droites $d$ et $f$ qui
possèdent une même origine $A$ :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/definition-angle-deux-demi-droites.svg]]

On le note :

$$ \alpha = \angle(d,f) $$

L’origine commune $A$ est appelée sommet de l’angle $\angle(d,f)$.

Il existe une ambiguïté quant au chemin emprunté par l’angle
pour aller de $d$ à $f$ : tourne-t-on dans le sens anti-horlogique ou
horlogique ? Pour lever cette ambiguïté, on trace un arc de cercle
orienté pour indiquer le sens de rotation du chemin parcouru. Dans
notre schéma, l’angle tourne dans le sens anti-horlogique.

Alternativement, étant donné un point $B \in d$ et un point $C \in f$,
le même angle peut être défini par trois points :

- le sommet $A$
- le point $B$ qui détermine la demi-droite $d = [AB)$
- le point $C$ qui détermine la demi-droite $f = [AC)$

Le schéma ci-dessous représente un angle $\alpha$ de sommet $A$
délimité par les demi-droites $d = [AB)$ et $f = [AC)$ :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/definition-angle-trois-points.svg]]

On le note :

$$ \alpha = \angleflex{BAC} $$

** Orientation

Un angle $\alpha^+$ est dit positif si il est associé à un arc de
cercle positif :

#+attr_html: :width 16%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-positif.svg]]

Un angle $\alpha^-$ est dit négatif si il est associé à un arc de
cercle négatif :

#+attr_html: :width 16%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-negatif.svg]]

Le schéma ci-dessous représente un angle dont l’orientation est
indéterminée :

#+attr_html: :width 16%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-orientation-indeterminee.svg]]

On assimile un angle indéterminé à un angle positif.

** Secteur angulaire

On associe à l’angle $\angleflex{BAC}$ le secteur angulaire
correspondant délimité par les demi-droites $[AB)$ et $[AC)$.

** Autres notations

On note :

$$ \angle(d,f) = \sphericalangle(d,f) = \measuredangle(d,f) $$

Si :

$$ d = [AB)
\qquad \qquad \qquad
f = [AC) $$

on peut aussi noter cet angle par :

$$ \angleflex{BAC} = \angle BAC = \sphericalangle BAC = \measuredangle BAC = \angleflex{BAC} $$

ou encore :

$$ \angleflex{BAC} = \angle(d,f) = \angle([AB),[AC)) $$

Lorsque les côtés de l’angle sont évidents d’après le contexte,
on le note simplement :

$$ \angleflex{A} = \angleflex{BAC} $$

* Amplitude

#+TOC: headlines 1 local

** Définition

L’amplitude d’un angle, exprimée en radians, se définit comme le
la longueur d’un arc de cercle :

- dont le centre est le sommet de l’angle
- dont le rayon vaut $1$
- qui est délimité par les côtés de l’angle

Considérons un angle $\alpha$ et traçons un arc de cercle $\Gamma$
de centre $A$, de rayon $1$ et délimités par les côtés de $\alpha$,
comme dans le schéma ci-dessous :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/amplitude-angle-cercle-unitaire.svg]]

L’amplitude $\abs{\alpha}$ est alors définie comme la longueur de
cet arc de cercle :

$$ \abs{\alpha} = \abs{\Gamma} $$

En pratique, on confond souvent un angle avec son amplitude :

$$ \alpha = \abs{\alpha} $$

** Signe

L’amplitude d’un angle est :

- positive si l’angle est positif
- négative si l’angle est négatif

** Autres notations

L’amplitude de l’angle $\angle(d,f)$ se note :

$$ \abs{\angle(d,f)} = \abs{\sphericalangle(d,f)} = \abs{\measuredangle(d,f)} $$

L’amplitude de l’angle $\angleflex{BAC}$ se note :

$$ \abs{\angleflex{BAC}}
= \abs{\angle BAC}
= \abs{\sphericalangle BAC}
= \abs{\measuredangle BAC} $$

Lorsque les côtés de l’angle sont évidents d’après le contexte,
on note simplement l’amplitude par :

$$ \abs{\angleflex{A}} = \abs{\angleflex{BAC}} $$

** Fractions d’un cercle unitaire

Lorsque l’angle parcourt un tour complet, la mesure de l’arc de
cercle est égale au périmètre entier du cercle de rayon $1$ :

$$ \mathcal{P}_1 = 2 \ \pi $$

et l’angle vaut :

$$ \tau = 2 \ \pi $$

Pour une fraction $f$ du cercle unitaire, l’angle $\alpha$ vaudra :

$$ \alpha = 2 \ \pi \ f $$

Le tableau ci-dessous recense quelques cas courants :

| Fraction | Angle         |
|----------+---------------|
| $1$      | $2 \ \pi$     |
| $1/2$    | $\pi$         |
| $1/3$    | $2 \ \pi / 3$ |
| $1/4$    | $\pi / 2$     |
| $1/6$    | $\pi / 3$     |

** Unités

#+TOC: headlines 1 local

*** Radian

Le radian est l’unité d’amplitude d’un angle définie par la
longueur d’un arc de cercle unitaire. Son symbole est :

$$ \mathrm{rad} $$

Pour un angle $\rho$, on aura donc :

$$ \rho = \rho \ \mathrm{rad} $$

En pratique, on omet souvent cette unité, car le radian est l’unité
d’angle par défaut.

*** Degrés

Un degré correspond à un arc de cercle qui parcourt $1/360^\text{ième}$
de tour :

$$ 1^\circ = \frac{2 \ \pi}{360} $$

Un tour complet vaut donc :

$$ 360^\circ = 2 \ \pi $$

En divisant cette relation par deux, on montre qu’un demi-tour vaut :

$$ 180^\circ = \pi $$

Les amplitudes en degrés et en radians étant proportionnelles, on en
déduit la valeur en degrés de n’importe quelle valeur en radians. On
a en particulier :

| Tours  | Radians     | Degrés      |
|--------+-------------+-------------|
| $1$    | $2\ \pi$    | $360^\circ$ |
| $1/2$  | $\pi$       | $180^\circ$ |
| $1/4$  | $\pi/2$     | $90^\circ$  |
| $1/6$  | $\pi/3$     | $60^\circ$  |
| $1/8$  | $\pi/4$     | $45^\circ$  |
| $1/12$ | $\pi/6$     | $30^\circ$  |
| $3/4$  | $3 \ \pi/2$ | $270^\circ$ |
| $2$    | $4 \ \pi$   | $720^\circ$ |

** Mesure et construction

On utilise une corde graduée pour :

- mesurer un angle
- tracer un angle d’amplitude donnée

Pour ce faire, on choisit une corde dont la longueur $\mathscr{L}$
est identique au périmètre d’un cercle de rayon $1$ :

$$ \mathscr{L} = 2 \ \pi $$

On place ensuite des graduations sur la corde pour la subdiviser en $N$
parties égales. Chaque partie de la corde correspond alors à un angle :

$$ \delta = \frac{2 \ \pi}{N} = \frac{360^\circ}{N} $$

Par exemple, si $N = 12$, chaque partie correspond à un angle :

$$ \delta = \frac{\pi}{6} = 30^\circ $$

Si on souhaite une précision de $1^\circ$, il faut diviser la corde en
$N = 360$ parties égales.

Pour mesurer ou tracer un angle de sommet $A$, on procède comme suit :

- on trace un cercle $\mathscr{C}$ de centre $A$ et de rayon $1$
- on place la corde le long du cercle $\mathscr{C}$
- pour mesurer un angle
  + soit $B$ l’intersection du premier côté de l’angle avec $\mathscr{C}$
  + soit $C$ l’intersection du second côté de l’angle avec $\mathscr{C}$
  + on fait tourner la corde le long de $\mathscr{C}$ pour positionner
    une graduation de la corde sur le point $B$
  + on compte le nombre de graduations inclus dans l’arc de cercle
    qui mène du point $B$ au point $C$
- pour tracer un angle
  + on trace le premier côté
  + soit $B$ l’intersection de ce premier côté avec $\mathscr{C}$
  + on fait tourner la corde le long de $\mathscr{C}$ pour positionner
    une graduation de la corde sur le point $B$
  + on compte le nombre de graduations nécessaires pour obtenir
    l’amplitude souhaitée
  + on obtient ainsi une seconde graduation, qui nous donne
    un point $C \in \mathscr{C}$
  + on trace le second côté de l’angle $[AC)$

* Classification

#+TOC: headlines 1 local

** Angles

Le tableau suivant donne les noms des angles les plus courants :

| Nom         | Nombre de tours | Angle en rad | Angle en degrés |
|-------------+-----------------+--------------+-----------------|
| angle nul   | $0$             | $0$          | $0^\circ$       |
| angle plein | $1$             | $2 \ \pi$    | $360^\circ$     |
| angle plat  | $1/2$           | $\pi$        | $180^\circ$     |
| angle droit | $1/4$           | $\pi / 2$    | $90^\circ$      |

** Intervalles

Certaines catégories d’angles sont définies par des intervalles :

| Nom            | Commentaire                                | Intervalle en rad | Intervalle en degrés    |
|----------------+--------------------------------------------+-------------------+-------------------------|
| angle aigu     | entre l’angle nul et l’angle droit exclus  | $[0,\pi/2[$       | $[0,90^\circ[$          |
| angle obtus    | entre l’angle droit exclus et l’angle plat | $]\pi/2,\pi]$     | $]90^\circ,180^\circ]$  |
| angle saillant | entre l’angle nul et l’angle plat          | $[0,\pi[$         | $[0,180^\circ[$         |
| angle rentrant | entre l’angle plat et l’angle plein        | $]\pi, 2 \ \pi]$  | $]180^\circ,360^\circ]$ |

** Sommes

Enfin, certaines paires d’angles sont caractérisées par leurs sommes :

| Nom                    | Nom de la somme | Somme en rad | Somme en degrés |
|------------------------+-----------------+--------------+-----------------|
| angles complémentaires | angle droit     | $\pi/2$      | $90^\circ$      |
| angles supplémentaires | angle plat      | $\pi$        | $180^\circ$     |

* Alignement et angle plat

Considérons trois points $A$, $B$ et $C$ aligné sur une droite $d$,
et traçons un cercle $\mathscr{C}$ de centre $B$ et de rayon $1$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/alignement-et-angle-plat.svg]]

La droite $d$ divise le cercle $\mathscr{C}$ en deux parties égales.
La longueur de l’arc de cercle $\Gamma$ vaut donc la moitié du
périmètre :

$$ \abs{\Gamma} = \frac{2 \ \pi}{2} = \pi $$

Par définition, l’amplitude $\alpha$ de l’angle $\angleflex{CBA}$
est justement égale à la longueur de $\Gamma$ (arc de cercle de centre
$B$ et de rayon $1$). L’angle $\alpha$ est donc un angle plat :

$$ \alpha = \pi = 180^\circ $$

Trois points alignés forment un angle plat.

* Angles opposés par le sommet

Examinons le schéma ci-dessous, où $a$ et $b$ sont deux droites
sécantes :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-opposes-par-le-sommet.svg]]

Les angles $\alpha$ et $\beta$ sont dits opposés par le sommet. Il en
va de même pour $\gamma$ et $\delta$.

Comme $\alpha$ et $\gamma$ forment ensemble un angle plat, on a :

$$ \alpha + \gamma = 180^\circ $$

Pareil pour $\beta$ et $\gamma$ :

$$ \beta + \gamma = 180^\circ $$

En soustrayant la seconde équation de la première, on obtient :

$$ \alpha + \gamma - \beta - \gamma = 0 $$

Les angles $\gamma$ se simplifient et on a :

$$ \alpha - \beta = 0 $$

c’est-à-dire :

$$ \alpha = \beta $$

On démontre par un raisonnement similaire que :

$$ \gamma = \delta $$

Deux angles opposés par le sommet sont donc de même amplitude.

* Droites perpendiculaires

#+TOC: headlines 1 local

** Préambule

Soit deux droites sécantes $a$ et $b$ qui se coupent en formant, du même
côté de $a$, des angles symétriques à leur points d’intersections.

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droites-perpendiculaires-raisonnement.svg]]

Comme $\alpha$ et $\beta$ sont des angles opposés par le sommet, ils
sont de même amplitude :

$$ \alpha = \beta $$

Idem pour $\alpha$ et $\gamma$ :

$$ \alpha = \gamma $$

Tous les angles situés autour de l’intersection de $a$ et $b$ sont
donc identiques.

Comme les deux angles $\alpha$ forment, avec $\beta$ et
$\gamma$, un angle plein, on a :

$$ 2 \ \alpha + \beta + \gamma = 360^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ 4 \ \alpha = 360^\circ $$

ce qui nous donne :

$$ \alpha = 90^\circ $$

Tous les angles formés par l’intersection des deux droites sont des
angles droits. Ce constat nous amène à la définition des droites
perpendiculaires.

** Définition

On dit que deux droites $a$ et $b$ sont perpendiculaires si elles sont
sécantes et se coupent en formant quatre angles droits à leur point
d’intersection. On le note :

$$ a \perp b $$

Dans un diagramme, on le signale souvent par un petit carré situé dans
un coin de l’angle, comme dans le schéma ci-dessous :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droites-perpendiculaires.svg]]

** Segments

Deux segments $[A,B]$ et $[C,D]$ sont dits perpendiculaires si ils se
coupent en formant des angles droits. On le note :

$$ [A,B] \perp [C,D] $$

* Angle et cercle

#+TOC: headlines 1 local

** Angle au centre

Soit un cercle $\mathscr{C}$ de centre $O$. Un angle au centre de
$\mathscr{C}$ est un angle :

- dont le sommet est le centre $O$ du cercle
- dont les côtés sont des rayons du cercle

Dans le schéma ci-dessous, l’angle $\alpha = \angleflex{AOB}$ est un
exemple d’angle au centre :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre.svg]]

L’angle au centre $\alpha$ définit un arc de cercle $\Gamma =
\arcdecercle{AB}$.  On dit aussi que l’angle au centre $\alpha$
intercepte l’arc de cercle $\Gamma$.

** Angle inscrit

Soit un cercle $\mathscr{C}$ de centre $O$. Un angle inscrit dans
$\mathscr{C}$ est un angle :

- dont le sommet est un point du cercle
- dont les côtés sont sécants au cercle

Dans le schéma ci-dessous, l’angle $\alpha = \angleflex{APB}$ est un
exemple d’angle inscrit :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-inscrit.svg]]

L’angle inscrit $\alpha$ définit un arc de cercle $\Gamma
= \arcdecercle{AB}$.  On dit aussi que l’angle inscrit $\alpha$
intercepte l’arc de cercle $\Gamma$.

** Angle tangent

Soit un cercle $\mathscr{C}$ de centre $O$. Un angle tangent dans
$\mathscr{C}$ est un angle :

- dont le sommet est un point du cercle
- dont un côté est sécant au cercle
- dont l’autre côté est une demi-droite tangente au cercle

Dans le schéma ci-dessous, l’angle $\alpha = \angleflex{APB}$ est un
exemple d’angle tangent :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-tangent.svg]]

* Médiatrice

La médiatrice d’un segment est la droite qui croise perpendiculairement
ce segment en son point milieu.

Le schéma ci-dessous représente une médiatrice $m$ qui croise
perpendiculairement le segment $[A,B]$ au point milieu $D$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediatrice.svg]]

* Bissectrice

La bissectrice d’un angle est la demi-droite qui passe par le sommet
de cet angle et qui le divise en deux angles de même amplitude.

Le schéma ci-dessous représente une bissectrice $b$ d’un angle
$\angleflex{BAC}$ qui passe par $A$ et divise $\angleflex{BAC}$ en deux
angles $\alpha$ d’amplitudes égales :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/bissectrice.svg]]
