
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Angles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un angle $\widehat{BAC}$ est défini par :

- un sommet au point $A$
- deux demi-droites $[AB$ et $[AC$ qui délimitent un secteur du plan

On associe également à $\widehat{BAC}$ l’ensemble des points situées
entre les deux demi-droites

Dans cet ouvrage, on appelle *côtés* d’un angle les deux demi-droites
qui le délimitent.

Le schéma ci-dessous représente un angle de sommet $A$ délimité par les
demi-droites $[AB$ et $[AC$ :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/definition-angle.svg]]

Cet angle se note aussi :

$$ \angle BAC = \widehat{BAC} $$

Lorsque les côtés de l’angle $\widehat{BAC}$ sont évidents d’après
le contexte, on le note simplement :

$$ \widehat{A} = \widehat{BAC} $$

* Amplitude

#+TOC: headlines 1 local

** Définition

L’amplitude d’un angle, exprimée en radians, se définit comme le
rapport entre :

- la longueur $l$ d’un arc de cercle
  + dont le centre est situé au sommet de l’angle
  + qui est délimité par les côtés de l’angle
- le rayon $r$ de ce même cercle

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/amplitude-angle.svg]]

Dans le schéma ci-dessus, l’amplitude $\alpha$ de l’angle
$\widehat{BAC}$ vaut :

$$ \alpha = \frac{l}{r} $$

L’amplitude de l’angle de sommet $\angle BAC$ se note :

$$ \abs{\widehat{BAC}} $$

ou encore :

$$ \abs{\angle BAC} $$

Lorsque les côtés de l’angle $\widehat{BAC}$ sont évidents d’après
le contexte, on note simplement l’amplitude par :

$$ \abs{\widehat{A}} = \abs{\widehat{BAC}} $$

En pratique, on confond souvent un angle avec son amplitude.

** Cercle unitaire

Dans un cercle unitaire, c’est-à-dire un cercle de rayon $r = 1$,
l’amplitude d’un angle $\alpha$ est liée à la longueur de l’arc
de cercle intercepté par la relation :

$$ \alpha = \frac{l}{r} = \frac{l}{1} = l $$

L’amplitude de l’angle est alors égale à la longueur de l’arc
de cercle.

** Signe

On peut donner un signe à l’amplitude d’un angle :

- un angle est dit positif si il tourne dans le sens anti-horlogique
- un angle est dit négatif si il tourne dans le sens horlogique

Dans un schéma, l’orientation d’un angle se symbolise par une flèche. Le
schéma ci-dessous représente un angle orienté positivement :

#+attr_html: :width 16%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/amplitude-angle-positif.svg]]

Le schéma ci-dessous représente un angle orienté négativement :

#+attr_html: :width 16%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/amplitude-angle-negatif.svg]]

Le schéma ci-dessous représente un angle dont l’orientation est
indéterminée :

#+attr_html: :width 16%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/amplitude-angle-indetermine.svg]]

On assimile ce dernier type d’angle à un angle positif.

** Valeurs particulières

Lorsque l’angle parcourt un tour complet, la mesure de l’arc de
cercle est égale au périmètre entier du cercle :

$$ p = 2 \ \pi \ r $$

et l’angle vaut :

$$ \tau = \frac{2 \ \pi \ r}{r} = 2 \ \pi $$

On en déduit que :

- un angle qui parcourt un tour complet vaut $2 \ \pi$
- un angle qui parcourt un demi-tour vaut $\pi$
- un angle qui parcourt un quart de tour vaut $\pi/2$

** Glossaire

On appelle :

- angle nul : un angle qui ne parcourt rien du tout, c’est-à-dire $0$ tour
  + ses deux côtés se confondent
- angle plein : un angle qui parcourt un tour complet, c’est-à-dire $2\ \pi$
- angle plat : un angle d’un demi-tour, c’est-à-à-dire $\pi$
- angle droit : un angle d’un quart de tour, c’est-à-à-dire $\pi/2$
- angle aigu : un angle compris entre l’angle nul et l’angle droit
- angle obtus : un angle compris entre l’angle droit et l’angle plat
- angle saillant : un angle inférieur à l’angle plat
- angle rentrant : un angle supérieur à l’angle plat

Deux angles sont dit :

- supplémentaires si leur somme vaut un angle plat
- complémentaires si leur somme vaut un angle droit

** Radian

Le radian est l’unité de l’amplitude un angle telle que nous venons
de la définir. Son symbole est :

$$ \mathrm{rad} $$

Pour un angle $\rho$, on aura donc :

$$ \rho = \rho \ \mathrm{rad} $$

En pratique, on omet souvent cette unité, car le radian est l’unité
d’angle par défaut.

** Degrés

#+TOC: headlines 1 local

*** Définition

L’amplitude d’un angle $\delta$ exprimé en degrés se note :

$$ \delta^\circ $$

Cette amplitude se définit par le fait qu’un tour complet vaut :

$$ 360^\circ $$

Or, ce tour complet exprimé en radians vaut également $2\ \pi$. On a
donc :

$$ 360° = 2 \ \pi $$

On en déduit directement qu’un demi-tour vaut :

$$ 180° = \pi $$

*** Tableau comparatif des radians et degrés

Les amplitudes en degrés et en radians étant proportionnelles, on en
déduit la valeur en degrés de n’importe quelle valeur en radians. On
a en particulier :

| Tours  | Radians     | Degrés      | Nom         |
|--------+-------------+-------------+-------------|
| $1$    | $2\ \pi$    | $360^\circ$ | angle plein |
| $1/2$  | $\pi$       | $180^\circ$ | angle plat  |
| $1/4$  | $\pi/2$     | $90^\circ$  | angle droit |
| $1/6$  | $\pi/3$     | $60^\circ$  |             |
| $1/8$  | $\pi/4$     | $45^\circ$  |             |
| $1/12$ | $\pi/6$     | $30^\circ$  |             |
| $3/4$  | $3 \ \pi/2$ | $270^\circ$ |             |
| $2$    | $4 \ \pi$   | $720^\circ$ |             |

* Angles opposés par le sommet

Examinons le schéma ci-dessous, où $a$ et $b$ sont deux droites
sécantes :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-opposes-par-le-sommet.svg]]

Les angles $\alpha$ et $\beta$ sont dits opposés par le sommet. Il en
va de même pour $\gamma$ et $\delta$.

Comme $\alpha$ et $\gamma$ forment ensemble un angle plat, on a :

$$ \alpha + \gamma = 180^\circ $$

Pareil pour $\beta$ et $\gamma$ :

$$ \beta + \gamma = 180^\circ $$

En soustrayant la seconde équation de la première, on obtient :

$$ \alpha + \gamma - \beta - \gamma = 0 $$

Les angles $\gamma$ se simplifient et on a :

$$ \alpha - \beta = 0 $$

c’est-à-dire :

$$ \alpha = \beta $$

On démontre par un raisonnement similaire que :

$$ \gamma = \delta $$

Deux angles opposés par le sommet sont donc de même amplitude.

* Droites perpendiculaires

#+TOC: headlines 1 local

** Préambule

Soit deux droites sécantes $a$ et $b$ qui se coupent en formant, du même
côté de $a$, des angles symétriques à leur points d’intersection.

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droites-perpendiculaires-raisonnement.svg]]

Comme $\alpha$ et $\beta$ sont des angles opposés par le sommet, ils
sont de même amplitude :

$$ \alpha = \beta $$

Idem pour $\alpha$ et $\gamma$ :

$$ \alpha = \gamma $$

Tous les angles situés autour de l’intersection de $a$ et $b$ sont
donc identiques.

Comme les deux angles $\alpha$ forment, avec $\beta$ et
$\gamma$, un angle plein, on a :

$$ 2 \ \alpha + \beta + \gamma = 360^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ 4 \ \alpha = 360^\circ $$

ce qui nous donne :

$$ \alpha = 90^\circ $$

Tous les angles formés par l’intersection des deux droites sont des
angles droits. Ce constat nous amène à la définition des droites
perpendiculaires.

** Définition

On dit que deux droites $a$ et $b$ sont perpendiculaires si elles sont
sécantes et se coupent en formant quatre angles droits à leur point
d’intersection. On le note :

$$ a \perp b $$

Dans un diagramme, on le signale souvent par un petit carré situé dans
un coin de l’angle, comme dans le schéma ci-dessous :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droites-perpendiculaires.svg]]

** Segments

Deux segments $[A,B]$ et $[C,D]$ sont dits perpendiculaires si ils se
coupent en formant des angles droits. On le note :

$$ [A,B] \perp [C,D] $$

** Construction

* Euclide

#+TOC: headlines 1 local

** Cinquième axiome

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cinquieme-axiome-d-euclide.svg]]

On voit que les angles $\alpha$, $\beta$, $\gamma$ et $\delta$ sont
situés à l’intérieur des droites $a$ et $b$. On dit que ce sont
des angles internes. On remarque que $\alpha$ et $\beta$ sont situés
du même côté de $c$, tandis que $\gamma$ et $\delta$ sont situés de
l’autre côté.

L’axiome d’Euclide stipule que si la somme des angles internes
$\alpha$ et $\beta$ est strictement inférieure à deux angles droits,
c’est-à-dire à un angle plat :

$$ \alpha + \beta < 180^\circ $$

alors les droites $a$ et $b$ sont sécantes et leur point d’intersection
se situe du même côté de $c$ que les angles $\alpha$ et $\beta$.

Cette axiome est valide dans le cadre de la géométrie euclidienne,
dont la géométrie plane fait partie.

** Corollaire

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cinquieme-axiome-d-euclide-corollaire.svg]]

Comme $\alpha$ et $\gamma$ forment ensemble un angle plat, on a :

$$ \alpha + \gamma = 180^\circ $$

ou encore :

$$ \alpha = 180^\circ - \gamma $$

Pareil pour $\beta$ et $\delta$ :

$$ \beta = 180^\circ - \delta $$

En sommant ces deux dernières équations, on obtient :

$$ \alpha + \beta = 360^\circ - \gamma - \delta $$

ou encore :

$$ \alpha + \beta = 360^\circ - (\gamma + \delta) $$

Si les angles internes $\gamma$ et $\delta$ forment ensemble un angle
strictement plus grand que l’angle plat :

$$ \gamma + \delta > 180^\circ $$

on a :

$$ \alpha + \beta < 360^\circ - 180^\circ $$

et les angles $\alpha$ et $\beta$ vérifient alors la condition de
l’axiome d’Euclide :

$$ \alpha + \beta < 180^\circ $$

Les droites $a$ et $b$ sont donc forcément sécantes.

La relation entre les quatre angles peut se réécrire :

$$ \gamma + \delta = 360^\circ - (\alpha + \beta) $$

Par conséquent, si les angles internes $\alpha$ et $\beta$ vérifient
l’axiome d’Euclide :

$$ \alpha + \beta < 180^\circ $$

la somme des angles internes situés de l’åutre côté de $c$ est
strictement supérieure à 180° :

$$ \gamma + \delta > 180^\circ $$

Les deux relations ci-dessous sont donc équivalentes entre-elles, et
impliquent que $a$ et $b$ sont sécantes.

** Conclusion

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$.

Si la somme des deux angles internes situés
d’un même côté de $c$ n'est pas égale à 180°, elle est alors :

- soit strictement inférieure à 180°, et l’axiome d’Euclide s’applique
  directement
- soit strictement supérieure à 180°, et les deux angles situés de
  l’autre côté de $c$ vérifient l’axiome d’Euclide

Dans tous les cas, les deux droites $a$ et $b$ sont forcément sécantes.

La seule possibilité pour avoir deux droites $a$ et $b$ parallèles est
donc que la somme des deux angles internes situés d’un même côté
de $c$ soit égale à 180°.

* Deux droites parallèles et une sécante

#+TOC: headlines 1 local

** Somme des angles

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-paralleles-une-secante-somme.svg]]

Si la somme des angles $\alpha$ et $\beta$ était distincte de 180°,
l’axiome d’Euclide et son corollaire nous indique que $a$ et $b$
seraient sécantes. Comme $a$ et $b$ sont parallèles, ce cas de figure
n’est pas possible et on a :

$$ \alpha + \beta = 180^\circ $$

** Sécante perpendiculaire

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec une
troisième droite $c$, elle-même perpendiculaire à $a$, comme indiqué
sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-paralleles-une-perpendiculaire.svg]]

Comme $a$ et $b$ sont parallèles, la somme des deux angles internes
situés à droite de $c$ vaut un angle plat :

$$ \alpha + 90^\circ = 180^\circ $$

On en déduit que :

$$ \alpha = 90^\circ = \frac{\pi}{2} $$

La droite $c$ est donc aussi perpendiculaire à $b$.

Une perpendiculaire à une droite $a$ est aussi perpendiculaire avec
toutes les droites parallèles à $a$.

** Angles alternes-internes

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-alternes-internes.svg]]

Les angles $\alpha$ et $\delta$ sont dits alternes-internes. Il en va
de même pour $\beta$ et $\gamma$.

Comme $a$ et $b$ sont parallèles, on doit avoir :

$$ \alpha + \beta = 180^\circ $$

On remarque aussi que les angles $\beta$ et $\delta$ forment ensemble
un angle plat :

$$ \beta + \delta = 180^\circ $$

En soustrayant la seconde équation de la première, on obtient :

$$ \alpha - \delta = 0 $$

c’est-à-dire :

$$ \alpha = \delta $$

ON montre par un raisonnement similaire que :

$$ \beta = \gamma $$

Deux angles alternes-internes sont de même amplitude.

** Angles alternes-externes

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-alternes-externes.svg]]

Les angles $\lambda$ et $\omega$ sont dits alternes-externes. Il en va
de même pour $\mu$ et $\theta$.

On remarque que les angles $\lambda$ et $\gamma$ sont opposés par le
sommet. On a donc :

$$ \lambda = \gamma $$

Les angles $\gamma$ et $\beta$ sont alternes-internes :

$$ \gamma = \beta $$

Enfin, les angles $\beta$ et $\omega$ sont également opposés par le
sommet :

$$ \beta = \omega $$

Par transitivité de l’égalité, on a finalement :

$$ \lambda = \omega $$

ON démontre par un raisonnement similaire que :

$$ \mu = \theta $$

Deux angles alternes-externes sont de même amplitude.

** Angles correspondants

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-correspondants.svg]]

Les angles $\alpha$ et $\mu$ sont dits correspondants. Il en va de même
pour :

- $\beta$ et $\lambda$
- $\gamma$ et $\omega$
- $\delta$ et $\theta$

Les angles $\alpha$ et $\delta$ sont alternes-internes :

$$ \alpha = \delta $$

D’un autre côté, les angles $\delta$ et $\mu$ sont opposés par le
sommet :

$$ \delta = \mu $$

On a donc :

$$ \alpha = \mu $$

On montre par un raisonnement similaire que :

$$ \beta = \lambda $$

$$ \gamma = \omega $$

$$ \delta = \theta $$

Deux angles correspondants sont de même amplitude.

** Synthèse

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec une
troisième droite $c$. Le schéma ci-dessous intègre tous les résultats
obtenus jusqu’à présent :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-paralleles-une-secante-synthese.svg]]

On voit qu’il ne reste plus que deux angles, $\alpha$ et $\beta$,
qui vérifient la relation :

$$ \alpha + \beta = 180^\circ $$

* Réciproque du cinquième axiome d’Euclide

#+TOC: headlines 1 local

** Énoncé

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reciproque-cinquieme-axiome-d-euclide.svg]]

Une conséquence directe du cinquième axiome d’Euclide est que,
si $a$ et $b$ sont parallèles, la somme de $\alpha$ et de $\beta$
doit faire 180°.

La réciproque est-elle vraie ? La relation :

$$ \alpha + \beta = 180^\circ $$

est-elle suffisante pour garantir que $a$ et $b$ sont parallèles ?
Nous allons prouver par l’absurde que oui.

*** Démonstration

Faisons l’hypothèse que la somme de $\alpha$ et $\beta$ vaut 180°
et supposons que $a$ et $b$ s’intersectent en un point $P$. On peut
alors construire une droite $d$, parallèle à $c$ et passant par $P$,
comme sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reciproque-cinquieme-axiome-d-euclide-absurde.svg]]

Comme $c$ et $d$ sont parallèles, nous pouvons placer sur le schéma
les angles alternes-internes égaux à $\alpha$ et à $\beta$. Les angles
$\alpha$, $\beta$ et $\gamma$ formant ensemble un angle plat, on a :

$$ \alpha + \beta + \gamma = 180^\circ $$

Si $\gamma$ est un angle nul, les droites $a$ et $b$ doivent être
confondues et sont donc parallèles. Dans le cas contraire, on a $\gamma >
0$ et :

$$ \alpha + \beta = 180^\circ $$

par hypothèse. On en conclut que :

$$ 180° = \alpha + \beta + \gamma > \alpha + \beta = 180^\circ $$

c’est-à-dire :

$$ 180° > 180^\circ $$

ce qui est manifestement une absurdité. Le point d’intersection $P$ ne
peut donc pas exister, et on a :

$$ a \cap b = \emptyset $$

La relation :

$$ \alpha + \beta = 180^\circ $$

garantit que les droites $a$ et $b$ sont parallèles.

** Corollaire

Soit deux droites $a$ et $b$, toutes deux perpendiculaires à une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reciproque-cinquieme-axiome-d-euclide-corollaire.svg]]

Par perpendicularité, les deux angles internes situés à droite de $c$
sont deux angles droits. leur somme vaut donc :

$$ 90^\circ + 90^\circ = 180^\circ $$

La réciproque du cinquième axiome d’Euclide s’applique donc, ce qui nous
garantit que les droites $a$ et $b$ sont parallèles.

Si deux droites sont perpendiculaires à une même troisième droite,
alors elles sont parallèles entre-elles.

* Angle et cercle

#+TOC: headlines 1 local

** Angle au centre

Soit un cercle $\mathscr{C}$ de centre $O$. Un angle au centre de
$\mathscr{C}$ est un angle :

- dont le sommet est le centre $O$ du cercle
- dont les côtés sont des rayons du cercle

Dans le schéma ci-dessous, l’angle $\alpha$ est un exemple d’angle
au centre :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre.svg]]

** Angle inscrit

Soit un cercle $\mathscr{C}$ de centre $O$. Un angle inscrit dans
$\mathscr{C}$ est un angle :

- dont le sommet est un point du cercle
- dont les côtés sont sécants au cercle

Dans le schéma ci-dessous, l’angle $\alpha$ est un exemple d’angle
inscrit :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-inscrit.svg]]

* Médiatrice

** Définition

** Construction

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-mediatrice.svg]]

* Bissectrice

** Définition

** Construction

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-bissectrice.svg]]
