
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Angles et cercles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Angle au centre et angle inscrit

#+TOC: headlines 1 local

** Première disposition
:properties:
:custom_id: heading:angle_au_centre_et_angle_inscrit_premiere_disposition
:end:

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-1.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Nous allons examiner la relation entre l’angle au centre :

$$ \alpha = \abs{\angleflex{AOB}} $$

et l’angle inscrit :

$$ \beta = \abs{\angleflex{APB}} $$

Les segments $[O,A]$, $[O,B]$ et $[O,P]$ étant des rayons du cercle, on
a :

$$ r = \abs{OA} = \abs{OB} = \abs{OP} $$

La somme des angles dans le triangle $POB$ nous donne :

$$ 2 \ \gamma + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - 2 \ \gamma $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ 2 \ \lambda + \theta = 180^\circ $$

ou encore :

$$ \theta = 180^\circ - 2 \ \lambda $$

Comme les angles $\alpha$, $\delta$ et $\theta$ forment ensemble un tour
complet (un angle plein), on a :

$$ \alpha + \delta + \theta = 360^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ \alpha + (180^\circ - 2 \ \gamma) + (180^\circ - 2 \ \lambda) = 360^\circ $$

Simplifions les 360°  :

$$ \alpha - 2 \ \gamma - 2 \ \lambda = 0 $$

isolons $\alpha$ :

$$ \alpha = 2 \ \gamma + 2 \ \lambda $$

et mettons les $2$ en évidence :

$$ \alpha = 2 \ (\gamma + \lambda) $$

Comme :

$$ \beta = \gamma + \lambda $$

cette équation devient :

$$ \alpha = 2 \ \beta $$

L’amplitude de l’angle au centre vaut le double de l’amplitude de
l’angle inscrit.

** Deuxième disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-2.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Nous allons examiner la relation entre l’angle au centre $\alpha$
et l’angle inscrit $\beta$.

Les segments $[O,A]$, $[O,B]$ et $[O,P]$ étant des rayons du cercle, on
a :

$$ r = \abs{OA} = \abs{OB} = \abs{OP} $$

Le triangle $PAO$ étant isocèle, on a aussi :

$$ \theta = \beta + \gamma $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ \beta + \gamma + \theta + \delta = 180^\circ $$

En tenant compte de la relation précédente, cette équation devient :

$$ \beta + \gamma + \beta + \gamma + \delta = 180^\circ $$

ou encore :

$$ 2 \ \beta + 2 \ \gamma + \delta = 180^\circ $$

La somme des angles dans le triangle $PBO$ nous donne :

$$ 2 \ \gamma + \alpha + \delta = 180^\circ $$

En soustrayant cette dernière équation de la précédente, on obtient :

$$ 2 \ \beta + 2 \ \gamma + \delta - 2 \ \gamma - \alpha - \delta = 0 $$

c’est-à-dire :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Troisième disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-3.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Nous allons examiner la relation entre l’angle au centre $\alpha$
et l’angle inscrit $\beta$.

Les angles $\alpha$ et $\delta$ forment ensemble un angle plat :

$$ \alpha + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - \alpha  $$

La somme des angles du triangle $POB$ nous donne :

$$ 2 \ \beta + \delta = 180^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ 2 \ \beta + 180^\circ - \alpha = 180^\circ $$

Simplifions les 180°  :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha  = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Conclusion

Lorsqu’un angle au centre $\alpha$ et un angle inscrit $\beta$
interceptent le même arc de cercle $\Gamma = \arcdecercle{AB}$, l’angle
au centre vaut le double de l’angle inscrit :

$$ \alpha  = 2 \ \beta $$

ce qui revient à dire que l’angle inscrit vaut la moitié de l’angle au
centre :

$$ \beta  = \frac{\alpha}{2} $$

** Corollaire

Soit deux angles inscrits $\beta$ et $\gamma$ qui interceptent le même
arc de cercle $\Gamma = \arcdecercle{AB}$. On peut choisir un angle au
centre $\alpha$ qui intercepte également $\Gamma$. On a alors :

$$ \beta = \frac{\alpha}{2} = \gamma $$

Les deux angles inscrits sont donc de même amplitude.

* Angle au centre et angle tangent

#+TOC: headlines 1 local

** Première disposition

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$, un point
$A \in \mathscr{C}$ et une droite $t$ tangente au cercle $\mathscr{C}$
au point $A$. Dans le schéma ci-dessous, l’angle au centre $\alpha$
possède les mêmes points d’intersections avec le cercle que l’angle
tangent $\beta$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-tangent-1.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
les triangles isocèles.

La somme des angles dans le triangle $OBA$ nous donne :

$$ \alpha + 2 \ \gamma = 180^\circ $$

Isolons $\alpha$ :

$$ \alpha = 180^\circ - 2 \ \gamma $$

Comme la tangente $t$ est perpendiculaire au rayon $[O,A]$, on a :

$$ \beta + \gamma = 90^\circ $$

Isolons $\gamma$ :

$$ \gamma = 90^\circ - \beta $$

Substituons cette expression de $\gamma$ dans la relation impliquant
$\alpha$ :

$$ \alpha = 180^\circ - 2 \ (90^\circ - \beta) $$

Distribuons :

$$ \alpha = 180^\circ - 180^\circ + 2 \ \beta $$

En simplifiant, on obtient finalement :

$$ \alpha = 2 \ \beta $$

** Seconde disposition

Nous reprenons les notations de la section précédente :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-tangent-2.svg]]

Nous avons déjà vu que :
.
$$ \alpha = 2 \ \beta $$

Nous allons à présent examiner la relation entre l’angle tangent
$\mu$ et l’angle au centre $\lambda$. Comme $\alpha$ et $\lambda$
forment un tour complet, on a :

$$ \lambda = 360^\circ - \alpha $$

ou encore :

$$ \lambda = 360^\circ - 2 \ \beta $$

Les angles $\beta$ et $\mu$ forment ensemble un demi-tour :

$$ \beta = 180^\circ - \mu $$

Remplaçons $\beta$ par son expression dans la relation impliquant
$\lambda$ :

$$ \lambda = 360^\circ - 2 \ (180^\circ - \mu) $$

Distribuons :

$$ \lambda = 360^\circ - 360^\circ + 2 \ \mu $$

En simplifiant, on obtient finalement :

$$ \lambda = 2 \ \mu $$

** Conclusion

Lorsqu’un angle au centre $\alpha$ et un angle tangent $\beta$
interceptent le même arc de cercle $\Gamma = \arcdecercle{AB}$, l’angle
au centre vaut le double de l’angle tangent.

On en conclut directement que l’angle tangent vaut la moitié de
l’angle au centre.

** Corollaire

Soit deux angles tangents $\beta$ et $\gamma$ qui interceptent le même
arc de cercle $\Gamma = \arcdecercle{AB}$. On peut choisir un angle au
centre $\alpha$ qui intercepte également $\Gamma$. On a alors :

$$ \beta = \frac{\alpha}{2} = \gamma $$

Les deux angles tangents sont donc de même amplitude.

* Triangle et cercle

#+TOC: headlines 1 local

** Cercle circonscrit

On dit que le cercle $\mathscr{C}$ est circonscrit au triangle
$\mathcal{T}$, ou que $\mathcal{T}$ est inscrit dans $\mathscr{C}$,
si tous les sommets de $\mathcal{T}$ appartiennent à $\mathscr{C}$.

Le schéma ci-dessous représente un triangle $\mathcal{T} = ABC$ et
son cercle circonscrit $\mathscr{C}$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-circonscrit-a-un-triangle.svg]]

** Diamètre comme côté d’un triangle inscrit
:properties:
:custom_id: heading:diametre_comme_cote_d_un_triangle
:end:

Le schéma ci-dessous représente un triangle $ABC$ dont le côté $[A,B]$
est un diamètre du cercle circonscrit $\mathscr{C}$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diametre-comme-cote-d-un-triangle.svg]]

L’angle inscrit $\beta$ intercepte le même arc de cercle $\Gamma =
\arcdecercle{AB}$ que l’angle au centre $\alpha = \angleflex{AOB}$. Comme
l’amplitude de ce dernier vaut 180°, on a :

$$ 180^\circ = 2 \ \beta $$

ou encore :

$$ \beta = \frac{180^\circ}{2} = 90^\circ $$

Le triangle $ABC$ est donc un triangle rectangle. Comme :

$$ \abs{OA} = \abs{OB} $$

le centre $O$ du cercle $\mathscr{C}$ est situé au milieu de
l’hypothénuse $[A,B]$.

** Construction d’un triangle rectangle

Nous venons de montrer que tout triangle :

- inscrit dans un cercle
- dont un des côtés est un diamètre du cercle

est un triangle rectangle. Pour construire un triangle rectangle, il suffit donc :

- de tracer un diamètre du cercle
- de choisir un troisième sommet du triangle sur le cercle
- de relier les extrémités du diamètre au troisième sommet choisi
