
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Angles et cercles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Angle au centre et angle inscrit

#+TOC: headlines 1 local

** Première disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-1.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Nous allons examiner la relation entre l’angle au centre :

$$ \alpha = \abs{\angleflex{AOB}} $$

et l’angle inscrit :

$$ \beta = \abs{\angleflex{APB}} $$

Les segments $[O,A]$, $[O,B]$ et $[O,P]$ étant des rayons du cercle, on
a :

$$ r = \abs{OA} = \abs{OB} = \abs{OP} $$

La somme des angles dans le triangle $POB$ nous donne :

$$ 2 \ \gamma + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - 2 \ \gamma $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ 2 \ \lambda + \theta = 180^\circ $$

ou encore :

$$ \theta = 180^\circ - 2 \ \lambda $$

Comme les angles $\alpha$, $\delta$ et $\theta$ forment ensemble un tour
complet (un angle plein), on a :

$$ \alpha + \delta + \theta = 360^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ \alpha + (180^\circ - 2 \ \gamma) + (180^\circ - 2 \ \lambda) = 360^\circ $$

Simplifions les 360°  :

$$ \alpha - 2 \ \gamma - 2 \ \lambda = 0 $$

isolons $\alpha$ :

$$ \alpha = 2 \ \gamma + 2 \ \lambda $$

et mettons les $2$ en évidence :

$$ \alpha = 2 \ (\gamma + \lambda) $$

Comme :

$$ \beta = \gamma + \lambda $$

cette équation devient :

$$ \alpha = 2 \ \beta $$

L’amplitude de l’angle au centre vaut le double de l’amplitude de
l’angle inscrit.

** Deuxième disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-2.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Nous allons examiner la relation entre l’angle au centre $\alpha$
et l’angle inscrit $\beta$.

Les segments $[O,A]$, $[O,B]$ et $[O,P]$ étant des rayons du cercle, on
a :

$$ r = \abs{OA} = \abs{OB} = \abs{OP} $$

Le triangle $PAO$ étant isocèle, on a aussi :

$$ \theta = \beta + \gamma $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ \beta + \gamma + \theta + \delta = 180^\circ $$

En tenant compte de la relation précédente, cette équation devient :

$$ \beta + \gamma + \beta + \gamma + \delta = 180^\circ $$

ou encore :

$$ 2 \ \beta + 2 \ \gamma + \delta = 180^\circ $$

La somme des angles dans le triangle $PBO$ nous donne :

$$ 2 \ \gamma + \alpha + \delta = 180^\circ $$

En soustrayant cette dernière équation de la précédente, on obtient :

$$ 2 \ \beta + 2 \ \gamma + \delta - 2 \ \gamma - \alpha - \delta = 0 $$

c’est-à-dire :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Troisième disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-3.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Nous allons examiner la relation entre l’angle au centre $\alpha$
et l’angle inscrit $\beta$.

Les angles $\alpha$ et $\delta$ forment ensemble un angle plat :

$$ \alpha + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - \alpha  $$

La somme des angles du triangle $POB$ nous donne :

$$ 2 \ \beta + \delta = 180^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ 2 \ \beta + 180^\circ - \alpha = 180^\circ $$

Simplifions les 180°  :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha  = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Synthèse

Lorsque les côtés d’un angle au centre ont les mêmes points
d’intersection avec le cercle que les côtés d’un angle inscrit,
l’angle au centre vaut le double de l’angle inscrit.

* Angle au centre et angle tangent

#+TOC: headlines 1 local

** Énoncé

** Corollaire

* Triangle et cercle

#+TOC: headlines 1 local

** Cercle circonscrit

On dit que le cercle $\mathscr{C}$ est circonscrit au triangle
$\mathcal{T}$, ou que $\mathcal{T}$ est inscrit dans $\mathscr{C}$,
si tous les sommets de $\mathcal{T}$ appartiennent à $\mathscr{C}$.

Le schéma ci-dessous représente un triangle $\mathcal{T} = ABC$ et
son cercle circonscrit $\mathscr{C}$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-circonscrit-a-un-triangle.svg]]

** Diamètre comme côté d’un triangle inscrit
:properties:
:custom_id: heading:diametre_comme_cote_d_un_triangle
:end:

Le schéma ci-dessous représente un triangle $ABC$ dont le côté $[A,B]$
est un diamètre du cercle circonscrit $\mathscr{C}$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diametre-comme-cote-d-un-triangle.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Le côté $[A,B]$ passe donc par le centre $O$ du cercle $\mathscr{C}$.
Les points $A$, $O$ et $B$ sont donc alignés; ce qui signifie que les
angles $\alpha$ et $\delta$ forment ensemble un angle plat :

$$ \alpha + \delta = 180^\circ $$

La somme des angles du triangle $AOC$ nous donne :

$$ \alpha + 2 \ \beta = 180^\circ $$

La somme des angles du triangle $OBC$ nous donne :

$$ \delta + 2 \ \gamma = 180^\circ $$

En sommant ces deux dernières équations, on obtient :

$$ \alpha + 2 \ \beta + \delta + 2 \ \gamma = 360^\circ $$

Faisons passer $\alpha$ et $\delta$ dans le membre de droite :

$$ 2 \ \beta + 2 \ \gamma = 360^\circ - \alpha - \delta $$

ou encore :

$$ 2 \ \beta + 2 \ \gamma = 360^\circ - (\alpha + \delta) $$

En tenant compte de l’alignement de $A$, $O$ et $B$, on obtient :

$$ 2 \ \beta + 2 \ \gamma = 360^\circ - 180^\circ = 180^\circ $$

Mettons les $2$ en évidence :

$$ 2 \ (\beta + \gamma) = 180^\circ $$

Comme :

$$ \theta = \beta + \gamma $$

notre équation devient :

$$ 2 \ \theta = 180^\circ $$

c’est-à-dire :

$$ \theta = 90^\circ $$

Le triangle $ABC$ est donc un triangle rectangle. Comme :

$$ \abs{OA} = \abs{OB} $$

le centre $O$ du cercle $\mathscr{C}$ est situé au milieu de
l’hypothénuse $[A,B]$.

*Remarque* : nous aurions aussi bien pu constater que les côtés de
l’angle inscrit $\theta$ intersectent le cercle aux mêmes points
que les côtés de l’angle au centre $\angleflex{AOB}$. Comme
l’amplitude de ce dernier vaut 180°, on obtient le même résultat
que précédemment :

$$ \theta = \frac{180^\circ}{2} = 90^\circ $$

** Construction d’un triangle rectangle

Nous venons de montrer que tout triangle :

- inscrit dans un cercle
- dont un des côtés est un diamètre du cercle

est un triangle rectangle. Pour construire un triangle rectangle, il suffit donc :

- de tracer un diamètre du cercle
- de choisir un troisième sommet du triangle sur le cercle
- de relier les extrémités du diamètre au troisième sommet choisi
