
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Angles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

* Définition

#+TOC: headlines 1 local

** Introduction

Un angle $\widehat{BAC}$ est défini par :

- un sommet au point $A$
- deux demi-droites $[AB$ et $[AC$ qui délimitent un secteur du plan

On associe également à $\widehat{BAC}$ l’ensemble des points situées
entre les deux demi-droites

Le schéma ci-dessous représente un angle de sommet $A$ délimité par les
demi-droites $[AB$ et $[AC$ :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/definition-angle.svg]]

L’angle de sommet $A$ compris entre les deux demi-droites $[AB$ et $[AC$
se note aussi :

$$ \angle BAC $$

** Amplitude

L’amplitude d’un angle, exprimée en radians, se définit comme le
rapport entre :

- la longueur $l$ d’un arc de cercle dont le centre est situé au sommet de l’angle
- le rayon $r$ de ce même cercle

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/amplitude-angle.svg]]

Dans le schéma ci-dessus, l’amplitude $\alpha$ de l’angle
$\widehat{BAC}$ vaut :

$$ \alpha = \frac{l}{r} $$

L’amplitude de l’angle de sommet $\angle BAC$ se note :

$$ \abs{\widehat{BAC}} $$

ou encore :

$$ \abs{\angle BAC} $$

En pratique, on confond souvent un angle avec son amplitude.

** Signe

Une amplitude est par définition :

- positive si l’angle tourne dans le sens anti-horlogique
- négative si l’angle tourne dans le sens horlogique

** Radian

Le radian est l’unité d’un angle tel que nous venons de le
définir. Son symbole est :

$$ \mathrm{rad} $$

Pour un angle $\rho$, on aura donc :

$$ \rho = \rho \ \mathrm{rad} $$

En pratique, on omet souvent cette unité, car le radian est l’unité
d’angle par défaut.

** Valeurs particulières

Lorsque l’angle parcourt un tour complet, la mesure de l’arc de
cercle est égale au périmètre entier du cercle :

$$ p = 2 \ \pi \ r $$

et l’angle vaut :

$$ \tau = \frac{2 \ \pi \ r}{r} = 2 \ \pi $$

On en déduit que :

- un angle qui parcourt un tour complet vaut $2 \ \pi$
- un angle qui parcourt un demi-tour vaut $\pi$
- un angle qui parcourt un quart de tour vaut $\pi/2$

** Glossaire

On appelle :

- angle nul : un angle qui ne parcourt rien du tout, c’est-à-dire $0$ tour
  + ses deux côtés se confondent
- angle plein : un angle qui parcourt un tour complet, c’est-à-dire $2\ \pi$
- angle plat : un angle d’un demi-tour, c’est-à-à-dire $\pi$
- angle droit : un angle d’un quart de tour, c’est-à-à-dire $\pi/2$
- angle aigu : un angle compris entre l’angle nul et l’angle droit
- angle obtus : un angle compris entre l’angle droit et l’angle plat
- angle saillant : un angle inférieur à l’angle plat
- angle rentrant : un angle supérieur à l’angle plat

Deux angles sont dit :

- supplémentaires si leur somme vaut un angle plat
- complémentaires si leur somme vaut un angle droit

* Degrés

#+TOC: headlines 1 local

** Définition

L’amplitude d’un angle $\delta$ exprimé en degrés se note :

$$ \delta^\circ $$

Cette amplitude se définit par le fait qu’un tour complet vaut :

$$ 360^\circ $$

Or, ce tour complet exprimé en radians vaut également $2\ \pi$. On a
donc :

$$ 360° = 2 \ \pi $$

On en déduit directement qu’un demi-tour vaut :

$$ 180° = \pi $$

** Tableau comparatif des radians et degrés

Les amplitudes en degrés et en radians étant proportionnelles, on en
déduit la valeur en degrés de n’importe quelle valeur en radians. On
a en particulier :

| Tours  | Radians     | Degrés      |
|--------+-------------+-------------|
| $1$    | $2\ \pi$    | $360^\circ$ |
| $1/2$  | $\pi$       | $180^\circ$ |
| $1/4$  | $\pi/2$     | $90^\circ$  |
| $1/6$  | $\pi/3$     | $60^\circ$  |
| $1/8$  | $\pi/4$     | $45^\circ$  |
| $1/12$ | $\pi/6$     | $30^\circ$  |
| $3/4$  | $3 \ \pi/2$ | $270^\circ$ |
| $2$    | $4 \ \pi$   | $720^\circ$ |

* Cinquième axiome d’Euclide

#+TOC: headlines 1 local

** Énoncé

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cinquieme-axiome-d-euclide.svg]]

L’axiome d’Euclide stipule que si la somme des angles $\alpha$ et
$\beta$ vaut strictement moins que deux angles droits, c’est-à-dire
moins qu’un angle plat :

$$ \alpha + \beta < 180^\circ $$

alors les droites $a$ et $b$ sont sécantes et leur point d’intersection
se situe du même côté de $c$ que les angles $\alpha$ et $\beta$.

** Corollaire

Examinons le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cinquieme-axiome-d-euclide-corollaire.svg]]

Comme $\alpha$ et $\gamma$ forment ensemble un angle plat, on a :

$$ \alpha + \gamma = 180^\circ $$

ou encore :

$$ \alpha = 180^\circ - \gamma $$

Pareil pour $\beta$ et $\delta$ :

$$ \beta = 180^\circ - \delta $$

En sommant ces deux dernières équations, on obtient :

$$ \alpha + \beta = 360^\circ - \gamma - \delta $$

ou encore :

$$ \alpha + \beta = 360^\circ - (\gamma + \delta) $$

Si les angles $\gamma$ et $\delta$ forment ensemble un angle plus grand
que l’angle plat :

$$ \gamma + \delta > 180^\circ $$

on a :

$$ \alpha + \beta < 360^\circ - 180^\circ $$

Les angles $\alpha$ et $\beta$ vérifient alors la condition de l’axiome
d’Euclide

$$ \alpha + \beta < 180^\circ $$

et les droites $a$ et $b$ sont sécantes.

On vérifie aisément que la réciproque est vraie : avoir deux angles
dont la somme est strictement inférieure à 180° d’un côté de
$c$ est équivalent à avoir deux angles dont la somme est strictement
supérieure à 180° de l’autre côté de $c$.

* Perpendicularité

On dit que deux droites $a$ et $b$ sont perpendiculaires si elles sont
sécantes et se coupent en formant des angles droits à leur points
d’intersection. On le note :

$$ a \perp b $$

Deux segments $[A,B]$ et $[C,D]$ sont dits perpendiculaires si ils se
coupent en formant des angles droits. On le note :

$$ [A,B] \perp [C,D] $$

* Angles opposés par le sommet

* Deux droites parallèles et une sécante

#+TOC: headlines 1 local

** Angles correspondants

** Angles alternes-internes

** Angles alternes-externes

* Angle et cercle

#+TOC: headlines 1 local

** Angle au centre

** Angle inscrit

** Relation

