
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Angles et cercles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Angle au centre et angle inscrit

#+TOC: headlines 1 local

** Première disposition
:properties:
:custom_id: heading:angle_au_centre_et_angle_inscrit_premiere_disposition
:end:

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$ et des points
$A, B, P \in \mathscr{C}$. Dans le schéma ci-dessous, l’angle au centre
$\alpha$ intercepte le même arc de cercle $\Gamma = \arcdecercle{AB}$
que l’angle inscrit $\beta$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-1.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

La somme des angles dans le triangle $POB$ nous donne :

$$ 2 \ \gamma + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - 2 \ \gamma $$

La somme des angles dans le triangle $POA$ nous donne :

$$ 2 \ \lambda + \theta = 180^\circ $$

ou encore :

$$ \theta = 180^\circ - 2 \ \lambda $$

Comme les angles $\alpha$, $\delta$ et $\theta$ forment ensemble un tour
complet (un angle plein), on a :

$$ \alpha + \delta + \theta = 360^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ \alpha + (180^\circ - 2 \ \gamma) + (180^\circ - 2 \ \lambda) = 360^\circ $$

Simplifions les $180^\circ$ et $360^\circ$  :

$$ \alpha - 2 \ \gamma - 2 \ \lambda = 0 $$

isolons $\alpha$ :

$$ \alpha = 2 \ \gamma + 2 \ \lambda $$

et mettons les $2$ en évidence :

$$ \alpha = 2 \ (\gamma + \lambda) $$

Comme :

$$ \beta = \gamma + \lambda $$

cette équation devient :

$$ \alpha = 2 \ \beta $$

L’amplitude de l’angle au centre vaut le double de l’amplitude de
l’angle inscrit.

** Deuxième disposition

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$ et des points
$A, B, P \in \mathscr{C}$. Dans le schéma ci-dessous, l’angle au centre
$\alpha$ intercepte le même arc de cercle $\Gamma = \arcdecercle{AB}$
que l’angle inscrit $\beta$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-2.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Le triangle $PAO$ étant isocèle, on a aussi :

$$ \theta = \beta + \gamma $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ \beta + \gamma + \theta + \delta = 180^\circ $$

En tenant compte de la relation précédente, cette équation devient :

$$ \beta + \gamma + \beta + \gamma + \delta = 180^\circ $$

ou encore :

$$ 2 \ \beta + 2 \ \gamma + \delta = 180^\circ $$

La somme des angles dans le triangle $PBO$ nous donne :

$$ 2 \ \gamma + \alpha + \delta = 180^\circ $$

En soustrayant cette dernière équation de la précédente, on obtient :

$$ 2 \ \beta + 2 \ \gamma + \delta - 2 \ \gamma - \alpha - \delta = 0 $$

c’est-à-dire :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Troisième disposition

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$ et des points
$A, B, P \in \mathscr{C}$. Dans le schéma ci-dessous, l’angle au centre
$\alpha$ intercepte le même arc de cercle $\Gamma = \arcdecercle{AB}$
que l’angle inscrit $\beta$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-3.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Les angles $\alpha$ et $\delta$ forment ensemble un angle plat :

$$ \alpha + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - \alpha  $$

La somme des angles du triangle $POB$ nous donne :

$$ 2 \ \beta + \delta = 180^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ 2 \ \beta + 180^\circ - \alpha = 180^\circ $$

Simplifions les $180^\circ$  :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha  = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Conclusion

Lorsqu’un angle au centre $\alpha$ et un angle inscrit $\beta$
interceptent le même arc de cercle $\Gamma = \arcdecercle{AB}$, l’angle
au centre vaut le double de l’angle inscrit :

$$ \alpha  = 2 \ \beta $$

ce qui revient à dire que l’angle inscrit vaut la moitié de l’angle au
centre :

$$ \beta  = \frac{\alpha}{2} $$

** Corollaire

Soit deux angles inscrits $\beta$ et $\gamma$ qui interceptent le même
arc de cercle $\Gamma = \arcdecercle{AB}$. On peut choisir un angle au
centre $\alpha$ qui intercepte également $\Gamma$. On a alors :

$$ \beta = \frac{\alpha}{2} = \gamma $$

Les deux angles inscrits sont donc de même amplitude.

* Angle au centre et angle tangent

#+TOC: headlines 1 local

** Première disposition

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$, un point
$A \in \mathscr{C}$ et une droite $t$ tangente au cercle $\mathscr{C}$
au point $A$. Dans le schéma ci-dessous, l’angle au centre $\alpha$
intercepte le même arc de cercle $\Gamma$ que l’angle tangent $\beta$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-tangent-1.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
les triangles isocèles.

Nous allons examiner la relation entre l’angle au centre $\alpha$ et
l’angle tangent $\beta$. Remarquons que ces deux angles interceptent
le même arc de cercle $\Gamma = \arcdecercle{AB}$.

La somme des angles dans le triangle $OAB$ nous donne :

$$ \alpha + 2 \ \gamma = 180^\circ $$

Isolons $\alpha$ :

$$ \alpha = 180^\circ - 2 \ \gamma $$

Comme la tangente $t$ est perpendiculaire au rayon $[O,A]$, on a :

$$ \beta + \gamma = 90^\circ $$

Isolons $\gamma$ :

$$ \gamma = 90^\circ - \beta $$

Substituons cette expression de $\gamma$ dans la relation impliquant
$\alpha$ :

$$ \alpha = 180^\circ - 2 \ (90^\circ - \beta) $$

Distribuons :

$$ \alpha = 180^\circ - 180^\circ + 2 \ \beta $$

En simplifiant, on obtient finalement :

$$ \alpha = 2 \ \beta $$

L’amplitude de l’angle au centre vaut le double de l’amplitude de
l’angle tangent.

** Seconde disposition

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$, un point
$A \in \mathscr{C}$ et une droite $t$ tangente au cercle $\mathscr{C}$
au point $A$. Dans le schéma ci-dessous, l’angle au centre $\alpha$
intercepte le même arc de cercle $\Gamma$ que l’angle tangent $\beta$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-tangent-2.svg]]

Nous allons examiner la relation entre l’angle au centre $\alpha$ et
l’angle tangent $\beta$. Remarquons que ces deux angles interceptent
le même arc de cercle $\Gamma = \arcdecercle{BA}$.

Nous avons déjà vu que :
.
$$ \alpha = 2 \ \beta $$

Comme $\alpha$ et $\lambda$ forment un tour complet, on a :

$$ \lambda = 360^\circ - \alpha $$

ou encore :

$$ \lambda = 360^\circ - 2 \ \beta $$

Les angles $\beta$ et $\mu$ forment ensemble un demi-tour :

$$ \beta = 180^\circ - \mu $$

Remplaçons $\beta$ par son expression dans la relation impliquant
$\lambda$ :

$$ \lambda = 360^\circ - 2 \ (180^\circ - \mu) $$

Distribuons :

$$ \lambda = 360^\circ - 360^\circ + 2 \ \mu $$

En simplifiant, on obtient finalement :

$$ \lambda = 2 \ \mu $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle tangent.

** Conclusion

Lorsqu’un angle au centre $\alpha$ et un angle tangent $\beta$
interceptent le même arc de cercle $\Gamma$, l’angle au centre vaut
le double de l’angle tangent.

On en conclut directement que l’angle tangent vaut la moitié de
l’angle au centre.

** Corollaire

Soit deux angles tangents $\beta$ et $\gamma$ qui interceptent le même
arc de cercle $\Gamma$. On peut choisir un angle au centre $\alpha$
qui intercepte également $\Gamma$. On a alors :

$$ \beta = \frac{\alpha}{2} = \gamma $$

Les deux angles tangents sont donc de même amplitude.

* Diamètre comme côté d’un triangle inscrit
:properties:
:custom_id: heading:diametre_comme_cote_d_un_triangle
:end:

#+TOC: headlines 1 local

** Énoncé

Le schéma ci-dessous représente un triangle $ABC$ dont le côté $[A,B]$
est un diamètre du cercle circonscrit $\mathscr{C}$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diametre-comme-cote-d-un-triangle.svg]]

L’angle inscrit $\beta$ intercepte le même arc de cercle $\Gamma =
\arcdecercle{AB}$ que l’angle au centre $\alpha = \angleflex{AOB}$. Comme
les points $A$, $O$ et $B$ sont alignés, l’amplitude de ce dernier
vaut $180^\circ$ et :

$$ \alpha = 180^\circ = 2 \ \beta $$

ou encore :

$$ \beta = \frac{180^\circ}{2} = 90^\circ $$

Le triangle $ABC$ est donc un triangle rectangle. Comme :

$$ \abs{OA} = \abs{OB} $$

le centre $O$ du cercle circonscrit $\mathscr{C}$ est situé au milieu
de l’hypothénuse $[A,B]$.

** Construction d’un triangle rectangle

Nous venons de montrer que tout triangle :

- inscrit dans un cercle
- dont un des côtés est un diamètre du cercle

est un triangle rectangle. Pour construire un triangle rectangle, il suffit donc :

- de tracer un diamètre du cercle
- de choisir un troisième sommet du triangle sur le cercle
- de relier les extrémités du diamètre au troisième sommet choisi

*** Cathète et hypothénuse

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît les longueurs d’une cathète et de
l’hypothénuse :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-cathete-et-hypothenuse-par-cercle.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{AC}$.

Voici les étapes de la construction :

1. on trace le segment $[A,C]$
2. on repère le point $O$, au milieu de $[A,C]$
3. on trace le cercle $\mathscr{C}_1$, de centre $O$ et de rayon $r = \abs{AC} / 2$
4. on trace le cercle $\mathscr{C}_2$, de centre $A$ et de rayon $\abs{AB}$
5. le point $B$ est l’intersection de $\mathscr{C}_1$ et $\mathscr{C}_2$

Il ne reste alors plus qu’à tracer les segments $[A,B]$ et $[B,C]$.

Comme le côté $[A,C]$ est un diamètre du cercle circonscrit
$\mathscr{C}_1$, l’angle $\angleflex{B}$ est automatiquement un angle
droit et le triangle $ABC$ est bien un triangle rectangle.

*Remarque* : il existe une seconde intersection entre $\mathscr{C}_1$
et $\mathscr{C}_2$, située en-dessous de $[A,C]$. Choisir cette seconde
intersection comme point $B$ produit un triangle isométrique à celui
présenté sur le schéma.

*** Hypothénuse et angle

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît la longueur de l’hypothénuse et
l’amplitude d’un angle :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-hypothenuse-et-angle-par-cercle.svg]]

On connaît la longueur $\abs{AC}$ et l’angle :

$$ \alpha = \abs{\angleflex{A}} $$

Voici les étapes de la construction :

1. on trace le segment $[A,C]$
2. on repère le point $O$, au milieu de $[A,C]$
3. on trace le cercle $\mathscr{C}$, de centre $O$ et de rayon $r = \abs{AC} / 2$
4. on trace la droite $d$, passant par $A$ et formant un angle d’amplitude $\alpha$
   avec $[A,C]$
5. le point $B$ est l’intersection de $\mathscr{C}$ et de $d$

Il ne reste alors plus qu’à tracer les segments $[A,B]$ et $[B,C]$.

*Remarque* : on aurait pu partir vers le bas pour tracer la droite
$d$, obtenant ainsi un triangle isométrique à celui présenté sur
le schéma.
