
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Céviennes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Une cévienne est une ligne droite qui passe par un sommet d’un triangle.

Nous étudions également dans ce chapitre les médiatrices, qui ne
sont pas à strictement parler des céviennes, mais restent des droites
internes importantes dans le cadre des triangles.

* Classification

#+TOC: headlines 1 local

** Médiane

Une médiane est un segment qui part d’un sommet du triangle jusqu’au
milieu du côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une médiane $m$ qui
part du sommet $C$ pour rejoindre le milieu $D$ du côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediane-triangle.svg]]

On a donc :

$$ \abs{AD} = \abs{DB} $$

** Hauteur

Une hauteur est un segment qui part d’un sommet du triangle et qui
est perpendiculaire au côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une hauteur $h$ qui
part du sommet $C$ pour rejoindre perpendiculairement le côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-triangle.svg]]

On remarque que :

- la droite $(CD)$ est l’unique droite qui passe par le sommet $C$
  et est perpendiculaire à la droite $(AB)$
- $D$ est la projection orthogonale de $C$ sur $(AB)$

Par chaque sommet d’un triangle, on peut construire une et une seule
hauteur perpendiculaire au côté opposé. Un triangle compte en tout
trois hauteurs.

*** Hauteur extérieure

Dans le cas où la hauteur progresse vers un côté du triangle adjacent à
un angle obtus, on est amené à tracer la droite qui prolonge ce côté
pour pouvoir construire la hauteur. Le schéma ci-dessous nous en donne
un exemple, avec la hauteur $h$ qui part du sommet $C$ et progresse vers
la droite $d = (AB)$ prolongeant le côté $[A,B]$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-exterieure-triangle.svg]]

Les points $A$, $B$ et $D$ sont alignés sur la droite $d$.

** Médiatrice

Une médiatrice d’un triangle est tout simplement la médiatrice d’un
des côtés.

Le schéma ci-dessous représente un triangle $ABC$ et une médiatrice $m$ qui
croise perpendiculairement le côté $[A,B]$ en son milieu :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediatrice-triangle.svg]]

** Bissectrice

Une bissectrice d’un triangle est une demi-droite dont l’origine
est un des sommets et qui coupe l’angle lié à ce sommet en deux
parties égales.

Le schéma ci-dessous représente un triangle $ABC$ et une bissectrice $b$
dont l’origine est le sommet $A$ et qui coupe l’angle $\angleflex{BAC}$
en deux angles $\alpha$ d’amplitudes égales :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/bissectrice-triangle.svg]]

* Intersections

#+TOC: headlines 1 local

** Médiatrices

Soit un triangle $ABC$ et :

- $m$, la médiatrice du côté $[A,B]$
- $p$, la médiatrice du côté $[B,C]$
- $s$, la médiatrice du côté $[C,A]$

Considérons le point d’intersection $O$ entre $m$ et $p$ :

$$ \{ O \} = m \cap p $$

Comme $O$ est sur la médiatrice $m$, ce point est équidistant de $A$
et $B$ :

$$ \abs{OA} = \abs{OB} $$

Mais $O$ est aussi sur la médiatrice $p$ et :

$$ \abs{OB} = \abs{OC} $$

On en déduit par transitivité que :

$$ \abs{OA} = \abs{OC} $$

Le point $O$ est donc également sur la médiatrice $s$ de $[A,C]$ :

$$ \{ O \} = m \cap p \cap s $$

Les trois médiatrices d’un triangle s’intersectent au même point :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/intersection-mediatrices-triangle.svg]]

** Bissectrices

Soit un triangle $ABC$ et :

- $b$, la bissectrice de l’angle $\angleflex{A}$
- $d$, la bissectrice de l’angle $\angleflex{B}$
- $f$, la bissectrice de l’angle $\angleflex{C}$

Considérons le point d’intersection :

$$ \{ O \} = b \cap d $$

et :

- $P$, projection orthogonale de $O$ sur $(AB)$
- $S$, projection orthogonale de $O$ sur $(BC)$
- $T$, projection orthogonale de $O$ sur $(CA)$

Comme $O$ est sur la bissectrice $b$, ce point est équidistant de $[AB)$
et $[AC)$, et donc des projections orthogonales correspondantes :

$$ \abs{OP} = \abs{OT} $$

Comme $O$ est sur la bissectrice $d$, on a aussi :

$$ \abs{OP} = \abs{OS} $$

On en déduit par transitivité que :

$$ \abs{OS} = \abs{OT} $$

ou, en termes de distances :

$$ \distance(O,(BC)) = \distance(O,(CA)) $$

Le point $O$ est donc également sur la bissectrice $f$ de $\angleflex{C}$.

Les trois bissectrices d’un triangle s’intersectent au même point :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/intersection-bissectrices-triangle.svg]]

* Triangle isocèle

#+TOC: headlines 1 local

** Hauteur
:properties:
:custom_id: heading:hauteur_triangle_isocele
:end:

Soit un triangle $ABC$ isocèle en $C$ et la hauteur $h$ qui part du
sommet principal $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur.svg]]

Comme $ABC$ est isocèle en $C$, on a :

$$ a = \abs{AC} = \abs{BC} $$

Les triangles rectangles $ADC$ et $BDC$ ont une cathète $h$ et leur
hypothénuse de mêmes longueurs. Ils sont donc isométriques et :

$$ \abs{AD} = \abs{BD} $$

La hauteur $h$ est donc aussi une médiane du triangle $ABC$. Au niveau
des angles, on a :

$$ \alpha = \beta $$

Les angles adjacents à la base principale $[A,B]$ sont
égaux. L’égalité du dernier angle :

$$ \lambda = \mu $$

signifie que la hauteur $h$ est aussi la bissectrice de l’angle
$\angleflex{ACB}$.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur-resolu.svg]]

En résumé :

- les deux angles adjacents à la base principale sont égaux
- la hauteur qui part du sommet principal est aussi une médiane
  + il s’agit donc d’une médiane perpendiculaire, c’est-à-dire
    d’une médiatrice
- la hauteur qui part du sommet principal est aussi la bissectrice
  de l’angle correspondant

** Médiane

Soit un triangle $ABC$ isocèle en $C$ et la médiane $m$ qui part du
sommet principal $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane.svg]]

Comme $ABC$ est isocèle en $C$, on a :

$$ a = \abs{AC} = \abs{BC} $$

Par définition de la médiane, on a :

$$ b = \abs{AD} = \abs{BD} $$

On voit que les triangles $ADC$ et $BDC$ ont leurs trois côtés de mêmes
longueurs :

- la médiane $m$, côté commun
- les côtés $[A,C]$ et $[B,C]$ de longueur $a$
- les côtés $[A,D]$ et $[B,D]$ de longueur $b$

Ils sont donc isométriques, ce qui implique que leurs angles
sont de mêmes amplitudes :

$$ \alpha = \beta
\qquad \qquad \qquad
\gamma = \delta
\qquad \qquad \qquad
\lambda = \mu $$

Nous avions déjà obtenu $\alpha = \beta$ dans la section sur
[[#heading:hauteur_triangle_isocele][la hauteur du triangle isocèle]].

Comme les points $A$, $D$ et $C$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat.

$$ \gamma + \delta = 180^\circ $$

En utilisant $\gamma = \delta$, cette relation devient :

$$ 2 \ \gamma = 180^\circ $$

c’est-à-dire :

$$ \gamma = 90^\circ $$

La médiane $m$ est donc aussi une hauteur du triangle $ABC$.

La dernière relation $\lambda = \mu$ signifie que la médiane $m$
est aussi la bissectrice de l’angle $\angleflex{ACB}$ qui part du
sommet principal.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane-resolu.svg]]

** Bissectrice

Soit un triangle $ABC$ isocèle en $C$ et la bissectrice $b$ qui part
du sommet principal $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice.svg]]

Comme $ABC$ est isocèle en $C$, on a :

$$ a = \abs{AC} = \abs{BC} $$

On voit que les triangles $ADC$ et $BDC$ ont un angle de même amplitude
$\lambda$ situé entre deux côtés de mêmes longueurs :

- la bissectrice $b$, côté commun
- les côtés $[A,C]$ et $[B,C]$ de longueur $a$

Ils sont donc isométriques et :

$$ \abs{AD} = \abs{DB} $$

La bissectrice $b$ est donc aussi une médiane du triangle $ABC$. On a
aussi :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Comme les points $A$, $D$ et $B$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat, il vient :

$$ \gamma + \delta = 2 \ \gamma = 180^\circ $$

d’où :

$$ \gamma = 90^\circ $$

La bissectrice $b$ est donc aussi une hauteur du triangle $ABC$. Notre
schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice-resolu.svg]]

** Conclusion

Nous avons établi que :

- la médiane
- la hauteur
- la bissectrice

qui partent du sommet principal d’un triangle isocèle se confondent.

Comme la médiane est perpendiculaire à la base principale, elle est
aussi sa médiatrice.

De plus, les angles adjacents à la base principale sont de même
amplitude.

** Condition suffisante

Soit un triangle $ABC$ qui possède deux angles de même amplitude sur les
sommets $A$ et $B$, et la hauteur $h$ qui part du troisième sommet $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles.svg]]

Les triangles rectangles $ADC$ et $BDC$ ont une cathète $h$ commune et
un angle non adjacent d’amplitude égale. Ces deux triangles sont donc
isométriques. On a en particulier :

$$ \abs{AC} = \abs{BC}
\qquad \qquad \qquad
\abs{AD} = \abs{BD}
\qquad \qquad \qquad
\lambda = \mu $$

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles-resolu.svg]]

On voit que :

- le triangle $ABC$ est isocèle en $C$
- la hauteur $h$ est aussi une médiane du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

*** Conclusion

Nous avons établi que :

- un triangle qui a deux angles de même amplitude est un triangle isocèle
- les deux côtés de longueur égale sont adjacents aux deux angles de même amplitude

* Triangle équilatéral

#+TOC: headlines 1 local

** Lignes confondues

Un triangle équilatéral $ABC$ est par définition isocèle en $A$, en
$B$ et en $C$. Les céviennes qui partent du même sommet :

- médiane
- hauteur
- bissectrice

sont donc confondues.

Une médiane d’un triangle équilatéral est donc aussi une médiatrice
du triangle.

** Angles

Le schéma ci-dessous représente un triangle équilatéral $ABC$ avec
ses trois angles :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-angles.svg]]

Comme $ABC$ est un cas particulier de triangle isocèle en $A$ :

$$ \abs{AC} = \abs{AB} $$

Les angles adjacents à la base principale correspondante $[B,C]$ sont
donc égaux :

$$ \beta = \gamma $$

Comme $ABC$ est un cas particulier de triangle isocèle en $B$ :

$$ \abs{BA} = \abs{BC} $$

Les angles adjacents à la base principale correspondante $[C,A]$ sont
donc égaux :

$$ \alpha = \gamma $$

Les trois angles sont donc identiques :

$$ \alpha = \beta = \gamma $$

La somme des angles de ce triangle nous donne :

$$ \alpha + \beta + \gamma = 3 \ \alpha = 180^\circ $$

On a donc :

$$ \alpha = \beta = \gamma = \frac{180^\circ}{3} = 60^\circ $$

Les angles d’un triangle équilatéral ont tous une amplitude de $60^\circ$.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède trois
angles égaux :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-condition-angles.svg]]

Comme les angles $\angleflex{B}$ et $\angleflex{C}$ sont égaux (ils
valent tous deux $\alpha$), le triangle $ABC$ est isocèle en $A$ :

$$ \abs{AB} = \abs{AC} $$

Comme les angles $\angleflex{A}$ et $\angleflex{C}$ sont égaux, le
triangle $ABC$ est isocèle en $B$ :

$$ \abs{BA} = \abs{BC} $$

Les trois côtés sont donc de longueur égale :

$$ \abs{AB} = \abs{BC} = \abs{CA} $$

Un triangle qui possède trois angles égaux est un triangle équilatéral.
