
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Céviennes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Une cévienne est une ligne droite qui passe par un sommet d’un triangle.

Nous étudions également dans ce chapitre les médiatrices, qui ne
sont pas à strictement parler des céviennes, mais restent des droites
internes importantes dans le cadre des triangles.

* Objets géométriques liés au triangle

#+TOC: headlines 1 local

** Médiane

Une médiane est un segment qui part d’un sommet du triangle jusqu’au
milieu du côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une médiane $m$ qui
part du sommet $C$ pour rejoindre le milieu $D$ du côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediane-triangle.svg]]

On a donc :

$$ \abs{AD} = \abs{DB} $$

** Hauteur

Une hauteur est un segment qui part d’un sommet du triangle et qui
est perpendiculaire au côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une hauteur $h$ qui
part du sommet $C$ pour rejoindre perpendiculairement le côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-triangle.svg]]

On remarque que :

- la droite $(CD)$ est l’unique droite qui passe par le sommet $C$
  et est perpendiculaire à la droite $(AB)$
- $D$ est la projection orthogonale de $C$ sur $(AB)$

Par chaque sommet d’un triangle, on peut construire une et une seule
hauteur perpendiculaire au côté opposé. Un triangle compte en tout
trois hauteurs.

*** Hauteur extérieure

Dans le cas où la hauteur progresse vers un côté du triangle adjacent à
un angle obtus, on est amené à tracer la droite qui prolonge ce côté
pour pouvoir construire la hauteur. Le schéma ci-dessous nous en donne
un exemple, avec la hauteur $h$ qui part du sommet $C$ et progresse vers
la droite $d = (AB)$ prolongeant le côté $[A,B]$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-exterieure-triangle.svg]]

Les points $A$, $B$ et $D$ sont alignés sur la droite $d$.

** Médiatrice

Une médiatrice d’un triangle est tout simplement la médiatrice d’un
des côtés.

Le schéma ci-dessous représente un triangle $ABC$ et une médiatrice $m$ qui
croise perpendiculairement le côté $[A,B]$ en son milieu :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediatrice-triangle.svg]]

** Bissectrice

Une bissectrice d’un triangle est une droite qui passe par un de ses
sommets et qui coupe l’angle lié à ce sommet en deux parties égales.

Le schéma ci-dessous représente un triangle $ABC$ et une bissectrice
$b$ qui passe par le sommet $A$ et coupe l’angle $\angleflex{BAC}$
en deux angles $\alpha$ d’amplitudes égales :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/bissectrice-triangle.svg]]

* Triangle isocèle

#+TOC: headlines 1 local

** Hauteur

Le schéma ci-dessous représente un triangle isocèle et la hauteur
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

On voit que les triangles rectangles $ADC$ et $BCD$ ont une cathète $h$
et leur hypothénuse de mêmes longueurs. Ils sont donc isométriques et :

$$ \abs{AD} = \abs{DB} $$

La hauteur $h$ est donc aussi une médiane du triangle $ABC$. On a aussi :

$$ \alpha = \beta $$

Les angles adjacents au côté $[A,B]$ sont égaux. L’égalité du
dernier angle :

$$ \lambda = \mu $$

signifie que la hauteur $h$ est aussi la bissectrice de l’angle
$\angleflex{ACB}$.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur-resolu.svg]]

En résumé :

- les deux angles adjacents au côté $[A,B]$ sont égaux
  + $[A,B]$ est le côté est le côté adjacent aux deux côtés égaux
- la hauteur $h$ est aussi une médiane du triangle $ABC$
  + il s’agit donc d’une médiane perpendiculaire, c’est-à-dire
    d’une médiatrice
- la hauteur $h$ est aussi la bissectrice de l’angle $\angleflex{ACB}$

** Médiane

Le schéma ci-dessous représente un triangle isocèle et la médiane
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

Par définition de la médiane, on a :

$$ b = \abs{AD} = \abs{DB} $$

On voit que les triangles $ADC$ et $BCD$ ont leurs trois côtés de mêmes
longueurs. Ils sont donc isométriques, ce qui signifie que leurs angles
sont de mêmes amplitudes. On a en particulier :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

$$ \lambda = \mu $$

Cette dernière relation signifie que la médiane $m$ est aussi la
bissectrice de l’angle $\angleflex{ACB}$.

Comme les points $A$, $D$ et $C$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat, il vient :

$$ \gamma + \delta = 2 \ \gamma = 180^\circ $$

d’où :

$$ \gamma = 90^\circ $$

La médiane $m$ est donc aussi une hauteur du triangle $ABC$.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane-resolu.svg]]

** Bissectrice

Le schéma ci-dessous représente un triangle isocèle et la bissectrice
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

On voit que les triangles $ADC$ et $BCD$ ont un angle de même amplitude
$\lambda$ situé entre deux côtés de mêmes longueurs :

- la bissectrice $b$, côté commun
- les côtés $\abs{AC}$ et $\abs{BC}$

Ils sont donc isométriques et :

$$ \abs{AD} = \abs{DB} $$

La bissectrice $b$ est donc aussi une médiane du triangle $ABC$. On a
aussi :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Comme les points $A$, $D$ et $B$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat, il vient :

$$ \gamma + \delta = 2 \ \gamma = 180^\circ $$

d’où :

$$ \gamma = 90^\circ $$

La bissectrice $b$ est donc aussi une hauteur du triangle $ABC$. Notre
schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice-resolu.svg]]

** Conclusion

Les sections qui précèdent nous montre que :

- la médiane
- la hauteur
- la bissectrice

qui partent du sommet situé entre les côtés égaux d’un triangle
isocèle se confondent. La médiane est donc perpendiculaire, ce qui en
fait aussi une médiatrice du triangle.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède deux
angles de même amplitude sur deux de ses sommets, et la hauteur $h$
qui part du troisième sommet $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles.svg]]

Les triangles rectangles $ADC$ et $BCD$ ont une cathète $h$ commune,
et un angle non adjacent d’amplitude égale. Ces deux triangles sont
donc isométriques. On a en particulier :

$$ \abs{AC} = \abs{BC} $$

$$ \abs{AD} = \abs{DB} $$

$$ \lambda = \mu $$

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles-resolu.svg]]

On voit que :

- le triangle $ABC$ est isocèle
- la hauteur $h$ est aussi une médiane du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

Un triangle qui a deux angles de même amplitude est donc un triangle isocèle.

* Triangle équilatéral

#+TOC: headlines 1 local

** Lignes confondues

Un triangle équilatéral est par définition isocèle pour n’importe
quelle paire de côtés. Par conséquent, lorsqu’elles partent du
même sommet d’un triangle équilatéral, ces lignes se confondent :

- la médiane
- la hauteur
- la bissectrice

Une médiane d’un triangle équilatéral est donc aussi une médiatrice
du triangle.

** Angles

Le schéma ci-dessous représente un triangle équilatéral $ABC$ avec
ses trois angles :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-angles.svg]]

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[B,C]$ :

$$ \abs{AC} = \abs{BC} $$

les angles associés doivent être égaux :

$$ \alpha = \beta $$

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[A,B]$ :

$$ \abs{AC} = \abs{AB} $$

les angles associés doivent être égaux :

$$ \alpha = \gamma $$

Les trois angles sont donc identiques :

$$ \alpha = \beta = \gamma $$

La somme des angles de ce triangle nous donne :

$$ \alpha + \beta + \gamma = 3 \ \alpha = 180^\circ $$

On a donc :

$$ \alpha = \beta = \gamma = \frac{180^\circ}{3} = 60^\circ $$

Les angles d’un triangle équilatéral ont tous une amplitude de $60^\circ$.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède trois
angles égaux :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-condition-angles.svg]]

Comme les angles $\angleflex{A}$ et $\angleflex{B}$ sont égaux (ils
valent tous deux $\alpha$), ce triangle est isocèle en $[A,C]$ et
$[B,C]$ :

$$ \abs{AC} = \abs{BC} $$

Comme les angles $\angleflex{A}$ et $\angleflex{C}$ sont égaux, ce
triangle est isocèle en $[A,B]$ et $[C,B]$ :

$$ \abs{AB} = \abs{BC} $$

Les trois côtés sont donc de longueur égale :

$$ \abs{AB} = \abs{BC} = \abs{AC} $$

Un triangle qui possède trois angles égaux est un triangle équilatéral.
