
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Collections
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:collections}

* Dépendances

  - Chapitre \ref{chap:ensembles} : Les ensembles

* Définition

Une collection est un ensemble d'ensembles, c'est-à-dire un ensemble
dont les éléments sont également des ensembles.

* L'ensemble des sous-ensembles

Une collection particulièrement importante est l'ensemble des sous-ensembles
d'un ensemble donné $A$. On le note :

$$\sousens(A) = \{ S : S \subseteq A  \}$$

{\em Remarque :} la notation $\sousens$ est une notation globale, vous la
retrouver dans d'autres chapitres.

* Union

Soit un ensemble $\Omega$ et une collection d'ensembles
$\mathcal{C} \subseteq \sousens(\Omega)$. On définit l'union
des ensembles-éléments de $\mathcal{C}$ par :

$$\bigcup \mathcal{C} = \{ a \in \Omega : \text{ il existe } A \in \mathcal{C} \text{ tel que } a \in A \}$$

Il s'agit donc de l'ensemble dont chaque élément appartient à au moins
un des ensembles-éléments de $\mathcal{C}$.


* Intersection

Soit un ensemble $\Omega$ et une collection d'ensembles
$\mathcal{C} \subseteq \sousens(\Omega)$. On définit l'intersection
des ensembles-éléments de $\mathcal{C}$ par :

$$\bigcap \mathcal{C} = \{ a \in \Omega : a \in A \text{ pour tout } A \in \mathcal{C} \}$$

Il s'agit donc de l'ensemble dont chaque élément appartient à tous
les ensembles-éléments de $\mathcal{C}$.


* Collection paramétrée

Soit un ensemble $X$ et la collection :

$$\mathcal{C} = \{ A(x) \in \sousens(\Omega) : x \in X \}$$

On appelle ce type de collection une collection paramétrée. L'ensemble $X$
est appelé ensemble de paramètres.


** Union

L'union de tous ces ensembles est l'ensemble dont les éléments appartiennent
à au moins un des $A(x)$, pour un certain $x \in X$ :

$$\bigcup_{x \in X} A(x) = \{ a \in \Omega : \text{ il existe } x \in X \text{ tel que } a \in A \}$$

L'intersection est l'ensemble des éléments appartenant à tous les $A(x)$,
pour tout les $x \in X$ :

$$\bigcap_{x \in X} A(x) = \{ a \in \Omega : a \in A(x) \text{ pour tout } x \in X \}$$


* Collections discrètes

Soit $A_1,A_2,A_3,...$ une collection finie ou infinie d'ensembles.
L'union de tous ces ensembles se note :

$$\bigcup_i A_i = A_1 \cup A_2 \cup A_3 \cup ...$$

L'ensemble des éléments qui sont communs à tous ces ensembles se note :

$$\bigcap_i A_i = A_1 \cap A_2 \cap A_3 \cap ...$$


** Finie

Dans le cas où la collection est finie, par exemple $A_1,A_2,...,A_n$, on note
simplement :

$$\bigcup_{i = 1}^n A_i = A_1 \cup A_2 \cup ... \cup A_n$$

ainsi que :

$$\bigcap_{i = 1}^n A_i = A_1 \cap A_2 \cap ... \cap A_n$$


** Infinie

Dans le cas où la collection est infinie, on note simplement :

$$\bigcup_{i = 1}^{+\infty} A_i = A_1 \cup A_2 \cup ...$$

ainsi que :

$$\bigcap_{i = 1}^{+\infty} A_i = A_1 \cap A_2 \cap ...$$


* Distributivité

On a :

$$A \cap \bigcup_{x \in X} B(x) = \bigcup_{x \in X} \big[A \cap B(x)\big]$$

et :

$$A \cup \bigcap_{x \in X} B(x) = \bigcap_{x \in X} \big[A \cup B(x)\big]$$

Les collections discrètes en sont un cas particulier :

#+BEGIN_CENTER
\(
A \cap \bigcup_i B_i = \bigcup_i \big[A \cap B_i\big] \\ \)

\(
A \cup \bigcap_i B_i = \bigcap_i \big[A \cup B_i\big]
\)
#+END_CENTER


* Complémentaire

Soit une collection $\{ A(x) : x \in X \} \subseteq \sousens(\Omega)$ de sous-ensembles de $\Omega$. On a :

$$\Omega \setminus \bigcup_{x \in X} A(x) = \bigcap_{x \in X} \big[\Omega \setminus A(x)\big]$$

et :

$$\Omega \setminus \bigcap_{x \in X} A(x) = \bigcup_{x \in X} \big[\Omega \setminus A(x)\big]$$

Les collections discrètes en sont un cas particulier :

#+BEGIN_CENTER
\(
\Omega \setminus \bigcup_i A_i = \bigcap_i \big[\Omega \setminus A_i\big] \\ \)

\(
\Omega \setminus \bigcap_i A_i = \bigcup_i \big[\Omega \setminus A_i\big]
\)
#+END_CENTER


