
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Complexe
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:complexes}

* Dépendances

  - Chapitre \ref{chap:naturels} : Les nombres naturels
  - Chapitre \ref{chap:entiers} : Les nombres entiers
  - Chapitre \ref{chap:rationnels} : Les nombres rationnels
  - Chapitre \ref{chap:reels} : Les nombres réels

* Nombre imaginaire

Nous avons vu que le carré d'un nombre positif est forcément positif. Par conséquent, on ne peut pas trouver de $x \in \setR$ tel que :

$$x^2 = -1$$

Il nous faut donc inventer un nouvel objet, que l'on nomme nombre imaginaire, et que l'on note $\img$, tel que :

#+begin_center
\( \img^2 = -1 \)
#+end_center

On peut dès lors étendre la définition de la racine carrée par :

$$\sqrt{-1} = \img$$

Soit $x \in \setR$. Comme l'on veut conserver les propriétés des produits et puissances, on note que :

$$(x \cdot \img)^2 = x^2 \cdot \img^2 = x^2 \cdot (-1) = - x^2$$

On a par conséquent :

$$\sqrt{-x^2} = x \cdot \img$$


** Notation

On note aussi :

$$x \img = \img x = x \cdot \img$$


** Remarque

Attention à ne pas confondre les variables « $i$ » avec le nombre imaginaire « $\img$ ».


* Définition

Nous allons à présent nous intéresser aux propriétés algébriques des couples nombre réel - nombre imaginaire. Pour tout $(a, b) \in \setR^2$, nous introduisons la notation complexe :

$$a + \img b$$

L'ensemble des nombres complexes est simplement l'ensemble des couples réel - imaginaire :

$$\setC = \{ a + \img b : \ a,b \in \setR \}$$


* Parties réelles et imaginaires

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

On nomme $a$ la partie réelle de $z$, et on la note :

$$\Re(z) = a$$

On nomme $b$ la partie imaginaire de $z$, et on la note :

$$\Im(z) = b$$

On a donc :

$$z = \Re(z) + \img \Im(z)$$


* Complexe conjugué

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

Le complexe conjugué de $z$ est le nombre donné par :

$$\conjaccent{z} = \conjugue(z) = a + \img (-b) = a - \img b$$

On a donc :

#+BEGIN_CENTER
\(
\Re(\conjaccent{z}) = \Re(z) \)

\(
\Im(\conjaccent{z}) = - \Im(z)
\)
#+END_CENTER


** Conjugué carré

Il est clair d'après la définition que :

$$\conjugue \conjugue z = z$$


* Addition

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \)

\(
y = c + \img d
\)
#+END_CENTER

Comme nous désirons conserver les propriétés de commutativité et d'associativité de l'addition, on a :

$$x + y = a + \img b + c + \img d = (a + c) + \img (b + d)$$


* Soustraction

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \)

\(
y = c + \img d
\)
#+END_CENTER

Comme nous souhaitons conserver les propriétés de la soustraction, on a simplement :

$$x + y = a + \img b - (c + \img d) = a + \img b - c - \img d = (a - c) + \img (b - d)$$


* Multiplication

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \)

\(
y = c + \img d
\)
#+END_CENTER

Comme nous voulons conserver les propriétés de la multiplication, nous écrivons :

$$x \cdot y = (a + \img b) \cdot (c + \img d) = a \cdot c + \img a \cdot d + \img b \cdot c + \img^2 b  \cdot d$$

En tenant compte de la définition du nombre imaginaire, on a :

$$x \cdot y = a \cdot c + \img a \cdot d + \img b \cdot c - b  \cdot d$$

et finalement :

$$x \cdot y = (a \cdot c - b  \cdot d) + \img (a \cdot d + b \cdot c)$$

On a donc :

#+BEGIN_CENTER
\(
\Re(x \cdot y) = \Re(x) \cdot \Re(y) - \Im(x) \cdot \Im(y) \)

\(
\Im(x \cdot y) = \Re(x) \cdot \Im(y) + \Im(x) \cdot \Re(y)
\)
#+END_CENTER


** Mixte

On en déduit le cas particulier suivant :

$$(a + \img b) \cdot c = a \cdot c + \img b \cdot c$$

** Multiplication par $\img$

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

Comme :

$$\img z = \img a + \img^2 b = \img a - b$$

on a :

#+BEGIN_CENTER
\(
\Re(\img z) = -b = - \Im(z) \)

\(
\Im(\img z) = a = \Re(z)
\)
#+END_CENTER


** Conjugué

On a :

$$\conjugue(x) \cdot \conjugue(y) = (a \cdot c - b  \cdot d) - \img (a \cdot d + b \cdot c) = \conjugue(x \cdot y)$$


* Module

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

On définit le module de $z$ par :

$$\abs{z} = \sqrt{a^2 + b^2} \ge 0$$

On voit que le module est un réel positif. Dans le cas d'un réel, le module s'identifie à la valeur absolue, ce qui justifie la notation identique.


** Conjugué

On voit que :

$$z \cdot \conjaccent{z} = (a + \img b) \cdot (a - \img b) = a^2 + b^2 + \img (a \cdot b - a \cdot b) = a^2 + b^2$$

c'est-à-dire :

$$z \cdot \conjaccent{z} = \abs{z}^2$$


* Inverse

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

Multiplions la relation $z \cdot \conjaccent{z} = \abs{z}^2$ par :

$$\left( z \cdot \abs{z}^2 \right)^{-1} = \frac{1}{z \abs{z}^2}$$

Il vient :

$$\frac{ \conjaccent{z} }{ \abs{z}^2 } = \unsur{z}$$

Nous pouvons donc évaluer l'inverse d'un nombre complexe :

$$\unsur{z} = \frac{ a - \img b }{ a^2 + b^2 } = \frac{ a }{ a^2 + b^2 } - \img \frac{ b }{ a^2 + b^2 }$$

** Inverse de $\img$

On a en particulier :

$$\unsur{\img} = -\img$$


* Division

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \)

\(
y = c + \img d
\)
#+END_CENTER

On définit la division de deux nombres complexes par :

$$\frac{x}{y} = x \cdot \unsur{y} = \frac{ x \cdot \conjaccent{y} }{ \abs{y}^2 }$$

On a donc :

$$\frac{x}{y} = \frac{(a + \img b) \cdot (c - \img d)}{c^2 + d^2}$$

ou encore :

$$\frac{x}{y} = \frac{(a \cdot c + b \cdot d) + \img (b \cdot c - a \cdot d)}{c^2 + d^2}$$


* Obtention des parties réelles et imaginaires

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

En additionnant $z$ et son conjugué, on obtient :

$$z + \conjaccent{z} = (a + \img b) + (a - \img b) = 2 a = 2 \Re(z)$$

ce qui permet d'obtenir une expression de la partie réelle :

$$\Re(z) = \unsur{2}(z + \conjaccent{z})$$

En soustrayant $z$ et $\conjaccent{z}$, on obtient :

$$z - \conjaccent{z} = (a + \img b) - (a - \img b) = 2 \img b = 2 \img \Im(z)$$

ce qui permet d'obtenir une expression de la partie imaginaire :

$$\Im(z) = \unsur{2\img}(z - \conjaccent{z})$$


** Cas particuliers

On en déduit directement que si $z = \conjaccent{z}$, on a $\Im(z) = 0$ et $z\in\setR$. Par contre, si $z = -\conjaccent{z}$, on a $\Re(z) = 0$ et $z$ est purement imaginaire.


* Puissance

Soit $n \in \setN$ avec $n \ne 0$, $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

On définit la $n^{ième}$ puissance d'un nombre complexe par :

#+BEGIN_CENTER
\(
z^0 = 1 \)

\(
z^n = z \cdot z^{n-1}
\)
#+END_CENTER


** Négatives

Les puissances négatives sont données par :

$$z^{-n} = \unsur{z^n}$$


** Racines

La $n^{ième}$ racine $x \in \setC$ de $z$ est définie par :

$$x^n = z$$

On a alors :

$$z = x^{1/n}$$


** Fractionnaires

Soit $m \in \setN$. on a simplement :

$$z^{m/n} = \left( z^{1/n} \right)^m$$


** Réelles

Soit $s \in \setR$ et une suite $\{ r_i \in \setQ : i \in \setN \}$ qui converge vers $s$. On définit :

$$z^s = \lim_{i \to \infty} z^{r_i}$$


* Ordre partiel

Soit les complexes $x,y \in \setC$ et les réels $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \)

\(
y = c + \img d
\)
#+END_CENTER

On dit que $x$ est plus petit que $y$ au sens des composantes, et on le note $x \le y$ si les deux conditions suivantes sont vérifiées :

#+BEGIN_CENTER
\(
a \le c \)

\(
b \le d
\)
#+END_CENTER


* Ordre total

Soit les complexes $x,y \in \setC$ et les réels $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \)

\(
y = c + \img d
\)
#+END_CENTER

On dit que $x$ est plus petit que $y$ et on le note $x \preceq y$ si :

$$a \strictinferieur c$$

ou si les conditions suivantes sont vérifiées :

#+BEGIN_CENTER
\(
a = c \)

\(
b \le d
\)
#+END_CENTER


* Inclusion

Pour tout $a \in \setR$, on a $a = a + \img 0 \in \setC$. On considère donc que $\setR \subseteq \setC$.


