
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Constructions de triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles quelconques

#+TOC: headlines 1 local

** Longueur des trois cotés

Le schéma ci-dessous représente la construction d’un triangle $ABC$
dont on connaît les longueurs des trois côtés :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-trois-cotes.svg]]

On connaît les longueurs $\abs{AB}$, $\abs{BC}$ et $\abs{CA}$.

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace l’arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $\abs{AC}$
3. on trace l’arc de cercle $\mathscr{C}_2$ de centre $B$ et de rayon $\abs{BC}$

Le point $C$ recherché se trouve à une distance $\abs{AC}$ de $A$ et
à une distance $\abs{BC}$ de $B$. Il doit donc coïncider avec une des
intersections de $\mathscr{C}_1$ et de $\mathscr{C}_2$. On a donc $C =
I$ ou $C = J$. Une fois ce point $C$ choisi, il ne reste plus qu’à
tracer les segments $[A,C]$ et $[B,C]$.

Les triangles $ABI$ ou $ABJ$ vérifient donc tous deux les conditions
de départ.

*** Isométrie

Par construction, les longueurs des côtés de triangles $ABI$ et
$ABJ$ sont identiques. Par symétrie, les amplitudes de leurs angles
sont également identiques. Les triangles $ABI$ et $ABJ$ sont donc
isométriques

** Côté - angle - côté

Le schéma ci-dessous représente la construction d’un triangle $ABC$
dont on connaît l’amplitude d’un angle et les longueurs des deux
côtés qui l’entourent :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-cote-angle-cote.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{AC}$ ainsi que l’angle :

$$ \alpha = \abs{\anglecirc{BAC}} $$

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ passant par $A$ et formant un angle
   d’amplitude $\alpha$ avec $[A,B]$
3. on reporte sur $d$ la distance $\abs{AC}$ en partant du point $A$, obtenant ainsi le point $C$

Il ne reste alors plus qu’à tracer les segments $[A,C]$ et $[B,C]$.

** Angle - côté - angle

Le schéma ci-dessous représente la construction d’un triangle $ABC$
dont on connaît la longueur d’un côté ainsi que l’amplitude des
angles qui l’entourent :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-angle-cote-angle.svg]]

On connaît la longueur $\abs{AB}$ ainsi que les angles :

$$ \alpha = \abs{\anglecirc{BAC}} $$

$$ \beta = \abs{\anglecirc{CBA}} $$

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ passant par $A$ et réalisant un angle
   d’amplitude $\alpha$ avec $[A,B]$
3. on trace la droite $f$ passant par $B$ et réalisant un angle
   d’amplitude $\beta$ avec $[A,B]$
4. le point $C$ recherché est l’intersection de $d$ et $f$

Il ne reste alors plus qu’à tracer les segments $[A,C]$ et $[B,C]$.

* Triangle rectangle

#+TOC: headlines 1 local

** Deux cathètes

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît la longueur des cathètes :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-deux-cathetes.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{BC}$.

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace le segment $[B,C]$ de longueur $\abs{BC}$ et perpendiculaire à $[A,B]$
3. on trace $[A,C]$ le dernier côté du triangle

** Cathète et angle

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît la longueur d’une cathète et
l’amplitude d’un angle, en plus de l’angle droit :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-cathete-et-angle.svg]]

On connaît la longueur $\abs{AB}$ ainsi que l’angle :

$$ \alpha = \abs{\anglecirc{BAC}} $$

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ passant par $B$ et perpendiculaire à $[A,B]$
3. on trace la droite $f$ passant par $A$ et formant un angle
   d’amplitude $\alpha$ avec $[A,B]$
4. le point $C$ est l’intersection de $d$ et $f$

Il ne reste alors plus qu’à tracer les segments $[A,C]$ et $[B,C]$.

** Cathète et hypothénuse

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît les longueurs d’une cathète et de
l’hypothénuse :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-cathete-et-hypothenuse.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{AC}$.

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ perpendiculaire à $[A,B]$
3. on trace l’arc de cercle $\mathscr{C}$ de centre $A$ et de rayon $\abs{AC}$
4. le point $C$ recherché est l’intersection de $d$ et de $\mathscr{C}$

Il ne reste alors plus qu’à tracer les segments $[A,C]$ et $[B,C]$.

*** En utilisant le cercle circonscrit

Nous avons vu dans la section sur
[[file:triangles.org::#heading:diametre_comme_cote_d_un_triangle][le
diamètre du cercle circonscrit comme côté d’un triangle]], que cette
configuration produit toujours un triangle rectangle. Nous allons
à présent tirer parti de cette propriété.

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît les longueurs d’une cathète et de
l’hypothénuse :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-cathete-et-hypothenuse-par-cercle.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{AC}$.

Voici les étapes de la construction :

1. on trace le segment $[A,C]$
2. on repère le point $O$, au milieu de $[A,C]$
3. on trace le cercle $\mathscr{C}_1$, de centre $O$ et de rayon $r = \abs{AC} / 2$
4. on trace le cercle $\mathscr{C}_2$, de centre $A$ et de rayon $\abs{AB}$
5. le point $B$ est l’intersection de $\mathscr{C}_1$ et $\mathscr{C}_2$

Comme le côté $[A,C]$ est un diamètre du cercle circonscrit
$\mathscr{C}_1$, l’angle $\anglecirc{ABC}$ est automatiquement un
angle droit et le triangle $ABC$ est bien un triangle rectangle.

** Hypothénuse et angle

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît la longueur de l’hypothénuse et
l’amplitude d’un angle :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-hypothenuse-et-angle.svg]]

On connaît la longueur $\abs{AC}$ et l’angle :

$$ \alpha = \abs{\anglecirc{BAC}} $$

Voici les étapes de la construction :

1. on trace la droite $d$
2. on choisit un point $A$ sur $d$
3. on trace la droite $f$ formant un angle d’amplitude $\alpha$ avec $d$ au point $A$
4. on reporte sur $f$ la distance $\abs{AC}$ en partant du point $A$, obtenant ainsi le point $C$
5. on trace la droite $g$, passant par $C$ et perpendiculaire à $d$
6. le point $B$ est l’intersection de $d$ et $g$

Il ne reste alors plus qu’à tracer les côtés du triangle.

*** En utilisant le cercle circonscrit

* Conditions d’isométrie de deux triangles

#+TOC: headlines 1 local

** Principe d’équivalence des constructions

** Divers

Pour que deux triangles soient isométriques, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

- un côté de même longueur entre deux angles de même amplitude. Par
  exemple :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

- un angle de même amplitude compris entre deux côtés de même longueur.
  Par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$
