
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Constructions géométriques
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Médiatrice
:properties:
:custom_id: heading:mediatrice
:end:

Le schéma ci-dessous illustre la construction de la médiatrice $m$
du segment $[A,B]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-mediatrice.svg]]

On définit :

$$ \mathscr{L} = \abs{AB} $$

Voici les étapes de cette méthode de construction :

1. ouvrir le compas d’un rayon $r$ à peu près compris entre
   $2 \ \mathscr{L} / 3$ et $\mathscr{L}$
  - si le rayon est trop près de $\mathscr{L}/2$, les points
    d’intersection vont être très proches, ce qui peut poser un problème
    de précision
2. tracer un arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $r$
3. tracer un arc de cercle $\mathscr{C}_2$ de centre $B$ et de rayon $r$
4. on note $D$ et $E$ les deux points d’intersections de
   $\mathscr{C}_1$ et $\mathscr{C}_2$
5. tracer la droite $m = (DE)$
6. on note $I$ le point d’intersection entre $[A,B]$ et $m$

Par construction, on a :

$$ \abs{AD} = \abs{AE} = \abs{BD} = \abs{BE} $$

Le quadrilatère $AEBD$ est donc un losange. Les segments $[A,B]$
et $[D,E]$ sont les diagonales du losange $AEBD$ : ils sont donc
perpendiculaires et se coupent en leur milieu. La droite $m = (DE)$ est
bien la médiatrice du segment $[A,B]$, et le point $I$ est son milieu :

$$ \abs{AI} = \abs{IB} $$

* Bissectrice

Le schéma ci-dessous illustre la construction de la bissectrice $b$
de l’angle $\angleflex{AOB}$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-bissectrice.svg]]

Voici les étapes de cette méthode de construction :

1. ouvrir le compas d’un rayon $r_1$
2. tracer un arc de cercle $\mathscr{C}_1$ de centre $O$ et de rayon $r_1$
  - soit $D$ l’intersection de la droite $(OA)$ avec $\mathscr{C}_1$
  - soit $E$ l’intersection de la droite $(OB)$ avec $\mathscr{C}_1$
3. ouvrir le compas d’un rayon $r_2$
4. tracer un arc de cercle $\mathscr{C}_2$ de centre $D$ et de rayon $r_2$
5. tracer un arc de cercle $\mathscr{C}_3$ de centre $E$ et de rayon $r_2$
  * le rayon de $\mathscr{C}_3$ est donc le même que celui de $\mathscr{C}_2$
6. soit $I$ l’intersection de $\mathscr{C}_2$ avec $\mathscr{C}_3$
7. tracer la droite $b = (OI)$

Par construction, on a :

$$ \abs{OD} = \abs{OE}
\qquad \qquad \qquad
\abs{DI} = \abs{EI} $$

Le quadrilatère $ODIE$ est donc un cerf-volant. La diagonale $[O,I]$
traverse les deux triangles isocèles qui composent le cerf-volant, ce
qui implique que $[O,I]$ est la bissectrice des angles situés à ses
extrémités. La droite $b = (OI)$ est bien la bissectrice de l’angle
$\angleflex{DOE} = \angleflex{AOB}$.

* Perpendiculaire à une droite passant par un point

Soit un point $A$ et une droite $d$. Le schéma ci-dessous illustre la
construction de la droite $p$, perpendiculaire à $d$ et passant par $A$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-perpendiculaire-par-un-point.svg]]

Voici les étapes de cette méthode de construction :

1. ouvrir le compas d’un rayon $R$ strictement supérieur à la distance
   entre le point $A$ et la droite $d$
  - autrement dit, assez grand pour qu’un cercle centré sur $A$ ait deux
    intersections avec $d$
2. tracer un arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $R$
3. on note $I$ et $J$ les deux points d’intersections de
   la droite $d$ avec l’arc de cercle $\mathscr{C}_1$
4. on note $\mathscr{L} = \abs{IJ}$
5. ouvrir le compas d’un rayon $r$ à peu près compris entre
   $2 \ \mathscr{L} / 3$ et $\mathscr{L}$
  - si le rayon est trop près de $\mathscr{L}/2$, les points
    d’intersection vont être très proches, ce qui peut poser un problème
    de précision
6. tracer un arc de cercle $\mathscr{C}_2$ de centre $I$ et de rayon $r$
7. tracer un arc de cercle $\mathscr{C}_3$ de centre $J$ et de rayon $r$
8. on note $K$ et $L$ les deux points d’intersections de
   $\mathscr{C}_2$ et $\mathscr{C}_3$
9. tracer la droite $p = (AL)$
10. on note $O$ le point d’intersection entre $d$ et $p$

Par construction, on a :

$$ \abs{AI} = \abs{AJ} $$

$$ \abs{LI} = \abs{LJ} $$

Le quadrilatère $AILJ$ est donc un cerf-volant. Les segments $[I,J]$
et $[A,L]$ sont les diagonales de ce cerf-volant : ils sont donc
perpendiculaires. La droite $p = (AL)$ est bien perpendiculaire à la
droite $d = (AB)$ et passe par $A$ puisque :

$$ A \in (AL) = p $$

Le point $O$ est par définition la projection orthogonale de $A$.

*Remarque* : la diagonale $[A,L]$ traverse les deux triangles isocèles qui
composent le cerf-volant, ce qui implique que $[A,L]$ est la médiatrice
de l’autre diagonale $[I,J]$.

* Parallèle à une droite passant par un point

#+TOC: headlines 1 local

** En utilisant un cercle

Soit un point $A$ et une droite $d$. Le schéma ci-dessous illustre la
construction de la droite $p$, parallèle à $d$ et passant par $A$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-parallele-par-un-point.svg]]

Voici les étapes de cette méthode de construction :

1. choisir un point $O$ distinct de $A$
2. tracer le cercle $\mathscr{C}_1$, de centre $O$ et de rayon $R = \abs{OA}$
3. on note $I$ et $J$ les deux points d’intersection
   entre $\mathscr{C}_1$ et la droite $d$
5. tracer un arc de cercle $\mathscr{C}_2$, de centre $J$ et de rayon $r = \abs{IA}$
6. on note $K$, l’intersection entre $\mathscr{C}_1$ et $\mathscr{C}_2$
7. tracer la droite $p = (AK)$

Il est clair que $p$ passe par $A$ :

$$ A \in (AK) = p $$

Il nous reste à montrer que la droite $p = (AK)$ est parallèle à $d$.
Pour cela, traçons les projections orthogonales des points $A$ et $K$
sur la droite $d$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-parallele-par-un-point-preuve.svg]]

Nous avons tenu compte dans le schéma des propriétés des angles des
triangles isocèles.

Les triangles $AIO$ et $KOJ$ on leurs trois côtés de mêmes longueurs.
Ils sont donc isométriques et :

$$ \beta = \gamma $$

Les triangles rectangles $ILA$ et $JMK$ ont un côté de même longueur
par construction :

$$ \abs{AI} = \abs{KJ} $$

Ils ont aussi un angle de même amplitude car :

$$ \angleflex{LIA} = \alpha + \beta = \alpha + \gamma = \angleflex{KJM} $$

Les triangles rectangles $ILA$ et $JMK$ sont donc isométriques, ce qui
implique que :

$$ \abs{AL} = \abs{KM} $$

Le quadrilatère $ALMK$ possède deux côtés de longueur égale qui forment
un angle droit avec un troisième côté. Ce quadrilatère est donc un
rectangle, ce qui implique que :

$$ [A,K] \parallel [L,M] $$

Les droites qui prolongent ces côtés sont aussi parallèles et :

$$ p = (AK) \parallel (LM) = d $$

*Remarque* : il existe des configuration légèrement différente de la
construction, suivant que le centre $O$ est situé au-dessus du point
$A$, ou en-dessous de la droite $d$. La démonstration est analogue à
celle que nous venons de voir.

** Perpendiculaire d’une perpendiculaire

Soit un point $A$ et une droite $d$. Le schéma ci-dessous illustre la
construction de la droite $p$, parallèle à $d$ et passant par $A$ :

#+attr_html: :width 55%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-parallele-par-un-point-perpendiculaire-d-une-perpendiculaire.svg]]

On procède comme suit :

1. tracer la droite $m$, perpendiculaire à $d$ et passant par $A$
2. tracer la droite $p$, perpendiculaire à $m$ et passant par $A$

On définit :

$$ \mathscr{L} = \abs{AB} $$

Voici les étapes détaillées de cette méthode de construction :

1. droite $m$, perpendiculaire à $d$ et passant par $A$
  1) ouvrir le compas d’un rayon $R$ strictement supérieur
     à la distance entre le point $A$ et la droite $d$
  2) tracer un arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $R$
  3) on note $D$ et $E$ les deux points d’intersections de
     la droite $d$ avec l’arc de cercle $\mathscr{C}_1$
  4) ouvrir le compas d’un rayon $r$ à peu près compris entre
     $2 \ \mathscr{L} / 3$ et $\mathscr{L}$
  5) tracer un arc de cercle $\mathscr{C}_2$ de centre $D$ et de rayon $r$
  6) tracer un arc de cercle $\mathscr{C}_3$ de centre $E$ et de rayon $r$
  7) on note $F$ et $G$ les deux points d’intersections de
     $\mathscr{C}_2$ et $\mathscr{C}_3$
  8) tracer la droite $m = (AG)$
  9) on note $H$ le point d’intersection entre $d$ et $m$
2. droite $p$, perpendiculaire à $m$ et passant par $A$
  1) ouvrir le compas d’un rayon $s$
  2) tracer un cercle $\mathscr{C}_4$ de centre $A$ et de rayon $s$
  3) on note $I$ et $J$ les deux points d’intersections de
     la droite $m$ avec le cercle $\mathscr{C}_4$
  4) ouvrir le compas d’un rayon $t$
  5) tracer un arc de cercle $\mathscr{C}_5$ de centre $I$ et de rayon $t$
  6) tracer un arc de cercle $\mathscr{C}_6$ de centre $J$ et de rayon $t$
  7) on note $K$ et $L$ les deux points d’intersections de
     $\mathscr{C}_5$ et $\mathscr{C}_6$
  8) tracer la droite $p = (KL)$

La droite $m$ étant perpendiculaire à $d$ et $p$, on a :

$$ p \parallel d $$

Par construction, $p$ est aussi la médiatrice du segment $[I,J]$. La
droite $p$ passe donc par le milieu de $[I,J]$, c’est-à-dire le
point $A$.

* Perpendiculaire au diamètre d’un cercle passant par le centre

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$. Le schéma
ci-dessous illustre la construction de la droite $p$, perpendiculaire
au diamètre $[A,B]$ et passant par le centre $O$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-perpendiculaire-diametre-cercle-par-centre.svg]]

Voici les étapes de cette méthode de construction :

1. tracer un arc de cercle $\mathscr{C}_1$, de centre $A$ et de rayon $r$
2. on note $I$ et $J$ les intersections de $\mathscr{C}$ avec $\mathscr{C}_1$
3. tracer un arc de cercle $\mathscr{C}_2$, de centre $B$ et de rayon $r$
4. on note $K$ et $L$ les intersections de $\mathscr{C}$ avec $\mathscr{C}_2$
5. tracer les segments $[A,K]$, $[A,L]$, $[B,I]$ et $[B,J]$
6. on note $M$ l’intersection de $[A,K]$ avec $[B,I]$
7. on note $N$ l’intersection de $[A,L]$ avec $[B,J]$
8. tracer la droite $p = (MN)$

Comme $[A,B]$ est un diamètre du cercle $\mathscr{C}$, on a :

$$ \abs{AO} = \abs{OB} $$

Le centre $O$ est aussi le point milieu du segment $[A,B]$.

Les triangles $AIB$, $AJB$, $AKB$ et $ALB$ sont inscrits dans $\mathscr{C}$
et ont un côté commun $[A,B]$ qui est un diamètre du cercle. Ce sont
donc tous des triangles rectangles. En plus de leur hypothénuse commune,
ils ont une cathète de même longueur car :

$$ r = \abs{AI} = \abs{AJ} = \abs{BK} = \abs{BL} $$

par construction. Ces triangles sont tous isométriques et :

$$ \alpha = \beta = \gamma = \delta $$

Les triangles $MAB$ et $NAB$ ont chacun deux angles de même amplitudes
et sont donc isocèles :

$$ \abs{MA} = \abs{MB}
\qquad \qquad \qquad
\abs{NA} = \abs{NB} $$

Le quadrilatère $ANBM$ possède deux paires de côtés adjacents de même
longueur : c’est un cerf-volant. Sa diagonale $[M,N]$ traverse les deux
triangles isocèles et est donc la médiatrice de l’autre diagonale
$[A,B]$. La droite $p = (MN)$ qui la prolonge est bien perpendiculaire
au diamètre $[A,B]$ et passe par le point $O$, milieu du segment $[A,B]$ :

$$ p \perp [A,B] \qquad \qquad O \in p $$

*Remarque* : la complémentarité des angles dans les triangles rectangles
$MAO$ et $NAO$ nous donnent :

$$ \abs{\angleflex{AMO}} = 90^\circ - \alpha = 90^\circ - \beta = \abs{\angleflex{ONA}} $$

Le triangle $AMN$ possède deux angles de même amplitude et est isocèle :

$$ \abs{MA} = \abs{NA} $$

On a finalement :

$$ \abs{MB} = \abs{MA} = \abs{NA} = \abs{NB} $$

Le quadrilatère $ANBM$ est aussi un losange.

* Cercle passant par trois points

* Cercle circonscrit d’un triangle

* Cercle inscrit d’un triangle

* Tangente à un cercle passant par un point

#+TOC: headlines 1 local

** Point situé sur le cercle

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$, et un point
$A \in \mathscr{C}$. Le schéma ci-dessous illustre la construction de
la droite $t$, tangente à $\mathscr{C}$ et passant par $A$ :

#+attr_html: :width 55%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-tangente-par-point-sur-cercle.svg]]

1. ouvrir le compas d’un rayon $R_1$
2. tracer un cercle $\mathscr{C}_1$ de centre $A$ et de rayon $R_1$
3. on note $I$ et $J$ les deux points d’intersections de $\mathscr{C}$ avec $\mathscr{C}_1$
4. construire la médiatrice de $[I,J]$
  1) ouvrir le compas d’un rayon $R_2$
  2) tracer un arc de cercle $\mathscr{C}_2$ de centre $I$ et de rayon $R_2$
  3) tracer un arc de cercle $\mathscr{C}_3$ de centre $J$ et de rayon $R_2$
  4) on note $K$ et $L$ les deux points d’intersections de
     $\mathscr{C}_2$ et $\mathscr{C}_3$
  5) tracer la droite $t = (KL)$

La droite $t$ étant la médiatrice de $[I,J]$, elle est perpendiculaire
à la droite $(IJ) = (OA)$, et donc aussi au rayon $[O,A]$. Comme $A$
est le point milieu du segment $[I,J]$, $t$ passe par $A$. La droite $t$
est donc tangente au cercle $\mathscr{C}$ en $A$.

** Point situé hors du cercle

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$, et un point
$A$ situé en dehors de $\mathscr{C}$ :

$$ \abs{OA} > r $$

Le schéma ci-dessous illustre la construction des droites $t$ et $u$,
tangentes à $\mathscr{C}$ et passant par $A$ :

#+attr_html: :width 55%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-tangente-par-point-hors-cercle.svg]]

Soit $I$ le point d’intersection entre $t$ et $\mathscr{C}$. Comme $t =
(AI)$ est perpendiculaire au rayon $[O,I]$, le triangle $AIO$ est un
triangle rectangle :

$$ \abs{\angleflex{AIO}} = 90^\circ $$

Soit le cercle $\mathscr{L}$, circonscrit au triangle $AIO$. Le centre de
$\mathscr{L}$ est situé en $M$, point milieu de l’hypothénuse $[A,O]$ :

$$ \abs{MA} = \abs{MO} $$

et son rayon vaut :

$$ R = \abs{MA} = \frac{\abs{AO}}{2} $$

Comme le point $I$ se trouve simultanément sur $\mathscr{C}$ et sur
$\mathscr{L}$, il est situé à l’intersection de ces deux cercles. Or,
$\mathscr{C}$ et sur $\mathscr{L}$ ont au total deux intersections,
le point $I$ et un autre point que nous nommons $J$ :

$$ \mathscr{C} \cap \mathscr{L} = \{ I, J \} $$

Comme $J \in \mathscr{L}$, le triangle $AJO$ est aussi inscrit dans
$\mathscr{L}$. De plus, le côté $[A,O]$ est un diamètre du cercle,
ce qui implique que $AJO$ est aussi un triangle rectangle :

$$ \abs{\angleflex{AJO}} = 90^\circ $$

La droite $u = (AJ)$ est perpendiculaire au rayon $[A,J]$ et est donc aussi
tangente au cercle $\mathscr{C}$.

Pour construire les droites $t$ et $u$ tangentes à $\mathscr{C}$
et passant par $A$, il suffit de tracer $\mathscr{L}$, de pointer les
intersections $I$ et $J$, puis de tracer :

$$ t = (AI)
\qquad \qquad \qquad
u = (AJ) $$

Voici les étapes détaillées de cette méthode de construction :

1. tracer le segment $[O,A]$
2. tracer le point $M$, milieu du segment $[O,A]$
  - par exemple en construisant la [[#heading:mediatrice][médiatrice]] de $[O,A]$
3. tracer le cercle $\mathscr{L}$, de centre $M$ et de rayon $R = \abs{MA}$
4. on note $I$ et $J$ les deux points d’intersections de $\mathscr{C}$
   et $\mathscr{L}$
5. tracer la droite $t = (AI)$
6. tracer la droite $u = (AJ)$

* Segment proportionnel

Les triangles semblables donnent une méthode pour construire un segment
de longueur proportionnelle à un segment donné. Soit le segment $[A,B]$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-d-un-segment-proportionnel.svg]]

Supposons par exemple que l’on veuille tracer un segment $[A,C]$
de longueur :

$$ \abs{AC} = \frac{7}{4} \ \abs{AB} $$

Il suffit de :

- tracer la droite $d = (AB)$ qui prolonge le segment $[A,B]$
- tracer la droite $e$, distincte de $d$ et passant par $A$
- ouvrir le compas d’un rayon $r$
- tracer des points équidistants sur $e$ en partant de $A$ et en allant de $P_1$ à $P_7$
  + tracer un arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $r$
  + on note $P_1$ le point d’intersection entre $e$ et $\mathscr{C}_1$
  + tracer un arc de cercle $\mathscr{C}_2$ de centre $P_1$ et de rayon $r$
  + on note $P_2$ le point d’intersection entre $e$ et $\mathscr{C}_2$
  + tracer un arc de cercle $\mathscr{C}_3$ de centre $P_2$ et de rayon $r$
  + on note $P_3$ le point d’intersection entre $e$ et $\mathscr{C}_3$
  + continuer ainsi jusque $P_7$
- tracer la droite $f = (P_4 B)$
- tracer la droite $g$, parallèle à $f$ et passant par le point $P_7$

Par construction, on a :

$$ r = \abs{A P_1} = \abs{P_1 P_2} = \abs{P_2 P_3} = \ldots = \abs{P_6 P_7} $$

On en conclut que :

$$ \abs{A P_4} = 4 \ r $$

$$ \abs{A P_7} = 7 \ r $$

d’où :

$$ \frac{\abs{AP_7}}{\abs{AP_4}} = \frac{7}{4} $$

Le point d’intersection $C$ entre $g$ et $d$ délimite le segment
$[A,C]$ demandé. En effet, par similarité des triangles, on a :

$$ \frac{\abs{AC}}{\abs{AB}} = \frac{\abs{AP_7}}{\abs{AP_4}} = \frac{7}{4} $$

* Racines carrées

On peut utiliser le théorème de Pythagore pour construire une suite de
segments de longueurs :

$$ \sqrt{1} = 1
\qquad \qquad \qquad
\sqrt{2} = 2
\qquad \qquad \qquad
\sqrt{3} = 3
\qquad \qquad \qquad
\sqrt{4} = 4
\qquad \qquad \qquad
\sqrt{5} = 5
\qquad \qquad \qquad
\ldots $$

Le schéma ci-dessous nous en donne un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-de-racines-carrees.svg]]

On procède comme suit :

1. on trace un carré $A P_1 T_1 B$
2. on prolonge les côtés $[A,P_1]$ et $[A,T_1]$ vers la droite
3. on trace un arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $\abs{A T_1}$
4. on nomme $P_2$ le point d’intersection entre la droite $(A P_1)$ et $\mathscr{C}_1$
5. on trace $T_2$, la projection orthogonale de $P_2$ sur $(B T_1)$
  + la droite $(P_2 T_2)$ est donc perpendiculaire à $(B T_1)$
6. on trace un arc de cercle $\mathscr{C}_2$ de centre $A$ et de rayon $\abs{A T_2}$
7. on nomme $P_3$ le point d’intersection entre la droite $(A P_1)$ et $\mathscr{C}_2$
8. on trace $T_3$, la projection orthogonale de $P_3$ sur $(B T_1)$
9. on trace un arc de cercle $\mathscr{C}_3$ de centre $A$ et de rayon $\abs{A T_3}$
10. on nomme $P_4$ le point d’intersection entre la droite $(A P_1)$ et $\mathscr{C}_3$
11. on trace $T_4$, la projection orthogonale de $P_4$ sur $(B T_1)$
12. on trace un arc de cercle $\mathscr{C}_4$ de centre $A$ et de rayon $\abs{A T_4}$
13. on nomme $P_5$ le point d’intersection entre la droite $(A P_1)$ et $\mathscr{C}_4$
14. on trace $T_5$, la projection orthogonale de $P_5$ sur $(B T_1)$
15. etc

Appliquons le théorème de Pythagore au triangle rectangle $A P_1 T_1$ :

$$ \abs{A P_2}^2 = \abs{A T_1}^2 = \abs{A P_1}^2 + \abs{P_1 T_1}^2 = 1^2 + 1^2 = 2 $$

puis au triangle rectangle $A P_2 T_2$ :

$$ \abs{A P_3}^2 = \abs{A T_2}^2 = \abs{A P_2}^2 + \abs{P_2 T_2}^2 = 2 + 1^2 = 3 $$

et ainsi de suite :

$$ \abs{A P_4}^2 = \abs{A T_3}^2 = \abs{A P_3}^2 + \abs{P_3 T_3}^2 = 3 + 1^2 = 4 $$

$$ \abs{A P_5}^2 = \abs{A T_4}^2 = \abs{A P_4}^2 + \abs{P_4 T_4}^2 = 4 + 1^2 = 5 $$

$$ \ldots $$

En prenant la racine carrée de ces relations, il vient :

$$ \abs{A P_2} = \sqrt{2} $$

$$ \abs{A P_3} = \sqrt{3} $$

$$ \abs{A P_4} = \sqrt{4} $$

$$ \abs{A P_5} = \sqrt{5} $$

$$ \ldots $$

Les segments :

$$ [A, P1], \quad [A, P_2], \quad \ldots, \quad [A, P_5], \quad \ldots $$

ont donc les longueurs souhaitées.

* Nombre d’or

