
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Constructions de polygones
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Carré

#+TOC: headlines 1 local

** D’après cinq cercles

Pour construire un carré, on peut
utiliser cinq cercles disposés comme dans une
[[file:constructions-de-mandalas.org::#heading:graine_de_vie][graine de
vie]] :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-carre-par-cinq-cercles.svg]]

Voici les étapes détaillées de cette méthode de construction :

- On dessine une
  [[file:constructions-de-mandalas.org::#heading:triquetra][triquetra]]
  formée par les cercles $\mathscr{C}_1$, $\mathscr{C}_2$ et $\mathscr{C}_3$,
  tous trois de rayon $r$
- on note $O_4$ le point d’intersection entre $\mathscr{C}_1$ et
  $\mathscr{C}_3$, distinct de $O_2$
- on note $O_5$ le point d’intersection entre $\mathscr{C}_2$ et
  $\mathscr{C}_3$, distinct de $O_1$
- on trace le cercle $\mathscr{C}_4$, de centre $O_4$ et de rayon $r$
- on trace le cercle $\mathscr{C}_5$, de centre $O_5$ et de rayon $r$
- on trace le segment $[O_1,I]$
- on trace le segment $[O_2,J]$
- on note $M$ le point d’intersection entre $\mathscr{C}_1$ et $[O_1,I]$
- on note $N$ le point d’intersection entre $\mathscr{C}_2$ et $[O_2,J]$

Comme les sommets du quadrilatère $O_1 O_2 N M$ appartiennent à des
cercles de rayon $r$ dont $O_1$ et $O_2$ sont les centres, on a :

$$ \abs{O_1 O_2} = \abs{O_1 M} = \abs{O_2 N} = r $$

On remarque également que les ensembles formés par :

- les cercles $\mathscr{C}_1$, $\mathscr{C}_3$ et $\mathscr{C}_4$
- les cercles $\mathscr{C}_2$, $\mathscr{C}_3$ et $\mathscr{C}_5$

sont tous deux des triquetras. Les
[[file:constructions-de-mandalas.org::#heading:triquetra_proprietes][propriétés
de la triquetra]] nous garantissent donc les perpendiculatirés suivantes :

$$ (O_1 I) \perp (O_1 O_2) \perp (O_2 J) $$

Le quadrilatère $O_1 O_2 N M$ possède deux côtés de même longueur,
$[O_1,M]$ et $[O_2,N]$, formant deux angles droits avec le troisième
côté $[O_1,O_2]$. C’est donc un rectangle, et ses côtés opposés
sont égaux. Comme de plus :

$$ \abs{O_1 M} = \abs{O_1 O_2} $$

Le rectangle $O_1 O_2 N M$ est aussi un carré.

* Hexagone régulier
:properties:
:custom_id: heading:hexagone_regulier
:end:

Pour construire un hexagone, on utilise l’égalité entre la longueur
du côté et le rayon du cercle circonscrit :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-hexagone.svg]]

Voici les étapes détaillées de cette méthode de construction :

1. tracer le cercle circonscrit $\mathscr{C}$ de centre $O$ et de rayon $r$
2. choisir un point $P_1$ sur $\mathscr{C}$, qui deviendra un des sommets
   de l’hexagone
3. tracer la droite $d = (O P_1)$
  + $P_1$ est par construction un point d’intersection de $d$ avec $\mathscr{C}$
  + on note $P_4$ le second point d’intersection de $d$ avec $\mathscr{C}$
4. tracer le cercle $\mathscr{C}_1$, de centre $P_1$ et de rayon $r$
  + on note $P_2$ et $P_6$ les points d’intersections de $\mathscr{C}_1$ avec $\mathscr{C}$
5. tracer le cercle $\mathscr{C}_2$, de centre $P_4$ et de rayon $r$
  + on note $P_3$ et $P_5$ les points d’intersections de $\mathscr{C}_2$ avec $\mathscr{C}$
6. tracer les côtés $[P_1,P_2]$, $[P_2,P_3]$, ..., $[P_5,P_6]$, $[P_6,P_1]$

En effet, comme $P_1$ est un sommet de l’hexagone, le diamètre
$[P_1,P_4]$ est une $2$-diagonale, ce qui implique que $P_4$ est aussi
un sommet.

Les points $P_2$ et $P_6$ sont aussi des sommets, car ils appartiennent
au cercle circonscrit et sont à distance $r$ du sommet $P_1$.

Les points $P_3$ et $P_5$ sont aussi des sommets, car ils appartiennent
au cercle circonscrit et sont à distance $r$ du sommet $P_4$.

Il suffit de relier ces six sommets :

$$ P_1, P_2, \ldots, P_6 $$

pour compléter l’hexagone régulier.

La construction ressemble à celle de la
[[file:constructions-de-mandalas.org::#heading:graine_de_vie][graine de
vie]]. La structure des angles et des longueurs est la même dans les
deux cas.

* Pentagone régulier

** Construction

** Cercle circonscrit

pentagramme
diamètres passant par les sommets et les intersections opposées

* Octogone régulier

diamètre et perpendiculaire
bissectrices

* Dodécagone régulier

hexagone
hexagramme
diamètres intersections

* Décagone régulier

pentagone
pentagramme
diamètres passant par les sommets et les intersections opposées

* Polygone à 24 côtés

