
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Constructions de triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles quelconques

#+TOC: headlines 1 local

** Longueur des trois cotés

Le schéma ci-dessous représente la construction d’un triangle $ABC$
dont on connaît les longueurs des trois côtés :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-trois-cotes.svg]]

On connaît les longueurs $\abs{AB}$, $\abs{BC}$ et $\abs{CA}$.

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace l’arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $\abs{AC}$
3. on trace l’arc de cercle $\mathscr{C}_2$ de centre $B$ et de rayon $\abs{BC}$

Le point $C$ recherché se trouve à une distance $\abs{AC}$ de $A$ et
à une distance $\abs{BC}$ de $B$. Il doit donc coïncider avec une des
intersections de $\mathscr{C}_1$ et de $\mathscr{C}_2$. On a donc $C =
I$ ou $C = J$. Une fois ce point $C$ choisi, il ne reste plus qu’à
tracer les segments $[A,C]$ et $[B,C]$.

Les triangles $ABI$ ou $ABJ$ vérifient donc tous deux les conditions
de départ.

*** Isométrie

Par construction, les longueurs des côtés de triangles $ABI$ et
$ABJ$ sont identiques. Par symétrie, les amplitudes de leurs angles
sont également identiques. Les triangles $ABI$ et $ABJ$ sont donc
isométriques

** Côté - angle - côté

Le schéma ci-dessous représente la construction d’un triangle $ABC$
dont on connaît les longueurs des côtés $[A,B]$ et $[A,C]$ ainsi que
l’amplitude de l’angle $\anglecirc{BAC}$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-cote-angle-cote.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{AC}$ ainsi que l’angle :

$$ \alpha = \abs{\anglecirc{BAC}} $$

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ passant par $A$ et formant un angle
   d’amplitude $\alpha$ avec $[A,B]$
3. on mesure sur $d$ la distance $\abs{AC}$ en partant de $A$
  - on obtient ainsi le point $C$

Il ne reste alors plus qu’à tracer les segments $[A,C]$ et $[B,C]$.

** Angle - côté - angle

Le schéma ci-dessous représente la construction d’un triangle $ABC$
dont on connaît la longueur du côté $[A,B]$ ainsi que l’amplitude
des angles $\anglecirc{BAC}$ et $\anglecirc{CBA}$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-angle-cote-angle.svg]]

On connaît la longueur $\abs{AB}$ ainsi que les angles :

$$ \alpha = \abs{\anglecirc{BAC}} $$

$$ \beta = \abs{\anglecirc{CBA}} $$

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ passant par $A$ et réalisant un angle
   d’amplitude $\alpha$ avec $[A,B]$
3. on trace la droite $f$ passant par $B$ et réalisant un angle
   d’amplitude $\beta$ avec $[A,B]$
4. le point $C$ recherché est l’intersection de $d$ et $f$

Il ne reste alors plus qu’à tracer les segments $[A,C]$ et $[B,C]$.

* Triangle rectangle

#+TOC: headlines 1 local

** Deux cathètes

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît la longueur des cathètes $[A,B]$
et $[B,C]$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-deux-cathetes.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{BC}$.

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace le segment $[B,C]$ de longueur $\abs{BC}$ et perpendiculaire à $[A,B]$
3. on trace $[A,C]$ le dernier côté du triangle

** Cathète et angle

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît la longueur des cathètes $[A,B]$
et $[B,C]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-cathete-et-angle.svg]]

On connaît la longueur $\abs{AB}$ ainsi que l’angle :

$$ \alpha = \abs{\anglecirc{BAC}} $$

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ passant par $B$ et perpendiculaire à $[A,B]$
3. on trace la droite $f$ passant par $A$ et formant un angle
   d’amplitude $\alpha$ avec $[A,B]$
4. le point $C$ est l’intersection de $d$ et $f$

Il ne reste alors plus qu’à tracer les segments $[A,C]$ et $[B,C]$.

** Cathète et hypothénuse

TODO

Le schéma ci-dessous représente la construction d’un triangle
rectangle $ABC$ dont on connaît la longueur des cathètes $[A,B]$
et $[B,C]$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-rectangle-cathete-et-hypothenuse.svg]]

On connaît les longueurs $\abs{AB}$ et $\abs{AC}$.

Voici les étapes de la construction :

1. on trace le segment $[A,B]$ de longueur $\abs{AB}$
2. on trace la droite $d$ perpendiculaire à $[A,B]$
3. on trace $[A,C]$ le dernier côté du triangle

** Hypothénuse et angle

* Conditions d’isométrie de deux triangles

#+TOC: headlines 1 local

** Principe d’équivalence des constructions

** Divers

Pour que deux triangles soient isométriques, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

- un côté de même longueur entre deux angles de même amplitude. Par
  exemple :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

- un angle de même amplitude compris entre deux côtés de même longueur.
  Par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$
