
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Constructions de mandalas
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Vesica piscis

#+TOC: headlines 1 local

** Simple

Soit deux points distincts $O_1$ et $O_2$ séparés par une
distance $r$. La vesica piscis se construit en traçant deux cercles
$\mathscr{C}_1(O_1,r)$ et $\mathscr{C}_2(O_2,r)$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-vesica-piscis.svg]]

Le nom provient de la forme du milieu, qui rappelle un poisson.

Voici les étapes de cette construction :

1. choisir deux points distincts $O_1$ et $O_2$
2. on note $r = \abs{O_1 O_2}$
3. tracer le cercle $\mathscr{C}_1$, de centre $O_1$ et de rayon $r$
4. tracer le cercle $\mathscr{C}_2$, de centre $O_2$ et de rayon $r$

Comme $r$ est la distance entre $O_1$ et $O_2$, chaque centre se trouve
sur l’autre cercle :

$$ O_1 \in \mathscr{C}_2(O_2,r)
\qquad \qquad \qquad
O_2 \in \mathscr{C}_1(O_1,r) $$

Cette figure sert de base à de nombreuses autres.

*** Propriétés

Examinons la vesica piscis ci-dessous, formée par deux cercle de rayon
$r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-vesica-piscis.svg]]

Les points $I$, $J$ et $O_2$ sont tous les trois situés sur le cercle
$\mathscr{C}_1$ et distants de $r$ :

$$ \abs{I O_2} = \abs{J O_2} = r $$

Ce sont donc trois sommets consécutifs d’un hexagone
régulier inscrit dans $\mathscr{C}_2$. Le quadrilatère
$O_1 J O_2 I$ possède donc les mêmes propriétés que le
[[file:hexagone-regulier.org::#heading:losange][losange]] que nous avons
examiné dans le chapitre sur [[file:hexagone-regulier.org][l’hexagone
régulier]].

Notre schéma devient :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-vesica-piscis-resolu.svg]]

**** Grande vesica piscis

Les propriétés de l’hexagone régulier et de ses diagonales nous
donnent aussi le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-vesica-piscis-grand-losange.svg]]

On retrouve un losange similaire à celui de l’intérieur de la
vesica piscis. En fait, ce grand losange se situe à l’intérieur
d’une grande vesica piscis, formée par les cercles $\mathscr{C}_3$
et $\mathscr{C}_4$ autour des points $I$ et $J$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-grande-vesica-piscis.svg]]

Construction :

- le cercle $\mathscr{C}_3$ est de centre $I$ et passe par $J$
- le cercle $\mathscr{C}_4$ est de centre $J$ et passe par $I$

**** Cercle intermédiaire

Soit une vesica piscis formée par deux cercles $\mathscr{C}_1$ et
$\mathscr{C}_2$ de rayon $r$ centrés aux points $O_1$ et $O_2$. On y
ajoute un cercle intermédiaire $\mathscr{C}_3$ de rayon $r$ et centré
au point $M$, milieu du segment $[O_1,O_2]$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-vesica-piscis-double.svg]]

On définit :

$$ L = \abs{K O_2} $$

Appliquons le théorème de Pythagore au triangle rectangle $K M O_2$ :

$$ L^2 = r^2 + \frac{r^2}{4} = \frac{5 \ r^2}{4} $$

On en déduit la valeur de $L$ :

$$ L = r \ \frac{\sqrt{5}}{2} $$

On obtient une valeur identique pour :

$$ \abs{K O_1} = r \ \frac{\sqrt{5}}{2} $$

** Double

Le schéma suivant illustre la construction d’une vesica piscis double :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-vesica-piscis-double.svg]]

Voici les étapes de cette construction :

1. choisir deux points distincts $O_1$ et $O_2$
2. on note $r = \abs{O_1 O_2}$
3. tracer le cercle $\mathscr{C}_1$, de centre $O_1$ et de rayon $r$
4. tracer le cercle $\mathscr{C}_2$, de centre $O_2$ et de rayon $r$
5. on note $I$ et $J$ les points d’intersections de $\mathscr{C}_1$ et $\mathscr{C}_2$
6. on note $M$ le point d’intersection des droites $(IJ)$ et $(O_1 O_2)$
7. tracer le cercle intermédiaire $\mathscr{C}_3$, de centre $M$ et de rayon $r$
8. on note $K$ et $L$ les points d’intersections de $(IJ)$ avec $\mathscr{C}_3$
9. tracer le cercle $\mathscr{C}_4$, de centre $O_1$ et passant par $K$ et $L$
10. tracer le cercle $\mathscr{C}_5$, de centre $O_2$ et passant par $K$ et $L$

Les propriétés du cercle intermédiaire nous garantissent que
$\mathscr{C}_4$ et $\mathscr{C}_5$ sont de rayon :

$$ \abs{K O_1} = \abs{K O_2} = r \ \frac{\sqrt{5}}{2} $$

* Triquétra

#+TOC: headlines 1 local

** Simple

Pour construire une triquetra, on commence par dessiner une vesica
piscis. Ensuite, on trace un cercle de même rayon dont le centre est
situé sur une des intersections des deux premiers cercles :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triquetra.svg]]

Voici les étapes de cette construction :

1. choisir deux points distincts $O_1$ et $O_2$
2. on note $r = \abs{O_1 O_2}$
3. tracer le cercle $\mathscr{C}_1$, de centre $O_1$ et de rayon $r$
4. tracer le cercle $\mathscr{C}_2$, de centre $O_2$ et de rayon $r$
5. on note $I$ et $J$ les points d’intersections de $\mathscr{C}_1$ et $\mathscr{C}_2$
6. tracer le cercle $\mathscr{C}_3$, de centre $J$ et de rayon $r$

On peut aussi choisir $I$ comme centre du troisième cercle :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triquetra-variante.svg]]

*** Propriétés

Examinons la triquetra ci-dessous, formée par trois cercle de rayon $r$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-triquetra.svg]]

Nous avons tenu compte des propriétés de l’hexagone régulier et de
ses diagonales dans la notation.

Remarquons que l’amplitude de l’angle $\angleflex{KIL}$ vaut :

$$ 3 \cdot 60^\circ = 180^\circ $$

Les points $K$, $I$ et $L$ sont donc alignés :

$$ f = (KI) = (IL) = (KL) $$

Considérons les droites $d$ et $f$, intersectées par $(I O_2)$. La
somme des angles internes situés du même côté de $(I O_2)$ vaut
$180^\circ$. Les droites $d$ et $f$ sont donc parallèles :

$$ d \parallel f $$

** Cerf-volant

* Fleur de vie et dérivés

#+TOC: headlines 1 local

** Graine de vie
:properties:
:custom_id: heading:graine_de_vie
:end:

Le schéma ci-dessous illustre la construction d’une graine de vie :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-graine-de-vie.svg]]

Voici les étapes de cette méthode de construction :

1. tracer le cercle $\mathscr{C}$, de centre $O$ et de rayon $r$
2. choisir le point $P_1$ sur $\mathscr{C}$
3. on note $P_4$ intersection de $\mathscr{C}$ avec $O P_1$
4. tracer le cercle $\mathscr{C}_1$, de centre $P_1$ et de rayon $r$
5. on note $P_2$ et $P_6$ les intersections de $\mathscr{C}$ avec $\mathscr{C}_1$
6. tracer le cercle $\mathscr{C}_4$, de centre $P_4$ et de rayon $r$
7. on note $P_3$ et $P_5$ les intersections de $\mathscr{C}$ avec $\mathscr{C}_4$
8. tracer le cercle $\mathscr{C}_2$, de centre $P_2$ et de rayon $r$
9. tracer le cercle $\mathscr{C}_3$, de centre $P_3$ et de rayon $r$
10. tracer le cercle $\mathscr{C}_5$, de centre $P_5$ et de rayon $r$
11. tracer le cercle $\mathscr{C}_6$, de centre $P_6$ et de rayon $r$

La construction ressemble à celle de
[[file:constructions-de-polygones.org::#heading:hexagone_regulier][l’hexagone
régulier]]. La structure des angles et des longueurs est la même dans
les deux cas.

** Germe de vie
:properties:
:custom_id: heading:germe_de_vie
:end:

La construction est similaire à la [[#heading:graine_de_vie][graine de
vie]], mais on ne reprend que les arcs de cercles intérieurs au cercle
principal :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-germe-de-vie.svg]]

** Flocon

En utilisant la [[#heading:graine_de_vie][graine de vie]], on peut
obtenir une structure évoquant un flocon de neige :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-flocon-de-vie.svg]]

** Moulin

Si on ne reprend qu’une moitié de chaque arc de cercle du
[[#heading:germe_de_vie][germe de vie]], on obtient une structure en
forme de moulin :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-moulin-de-vie.svg]]

** Fleur de vie

On construit une fleur de vie en partant d’une graine de vie, puis
en utilisant les nouveaux points d’intersections entre les cercles
pour tracer de nouveaux cercles de même rayon. On peut continuer ainsi
indéfiniment. En voici un exemple :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-fleur-de-vie.svg]]

** Fruit de vie
:properties:
:custom_id: heading:fruit_de_vie
:end:

Le fruit de vie se construit en étendant les diamètres de
[[file:constructions-de-polygones.org::#heading:hexagone_regulier][l’hexagone
régulier]], puis en traçant deux couches de cercles empilés autour
du cercle principal :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-fruit-de-vie.svg]]

** Cube de Metatron

Le cube de Metatron se construit en partant du
[[#heading:fruit_de_vie][fruit de vie]] et en traçant les segments qui
relient les centres des cercles. On y retrouve entre-autres des hexagones
réguliers et leurs diagonales :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-cube-de-metatron.svg]]

** Tore de vie

Le schéma ci-dessous illustre la construction d’un tore de vie :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-tore-de-vie-12.svg]]

Voici les étapes de cette méthode de construction :

- tracer le cercle $\mathscr{C}$, de centre $O$ et de rayon $r$
- tracer la graine de vie autour de $\mathscr{C}$
  + ce qui nous donne les points $P_1$, $P_2$, $\ldots$, $P_6$
- on note $I_1$, $I_2$, $\ldots$, $I_6$ les points d’intersections entre
  chaque paire de cercles parmi $\mathscr{C}_1$, $\mathscr{C}_2$, $\ldots$, $\mathscr{C}_6$
- on note $J_1$ à $J_6$ les points d’intersections entre $\mathscr{C}$
  et chacun des segments $[I_1,I_4]$, $[I_2,I_5]$ et $[I_3,I_6]$
- on trace les cercles de centres $J_1$ à $J_6$ et de rayon $r$

On peut continuer à utiliser des intersections pour tracer encore plus
de cercles dont les centres sont situés sur $\mathscr{C}$. En voici un
exemple avec $24$ cercles autour du cercle principal :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-tore-de-vie-24.svg]]

* Oeuf

#+TOC: headlines 1 local

** Oeuf et triangle 3 4 5

D’après une idée dévéloppée dans cette
[[https://youtu.be/ijPRm34blx0?si=dEvgRwaY0pDkFoEN&t=3431][vidéo
d’Howard Crowhurst]].

La construction suivante utilise des triangles de Pythagore $3,4,5$
pour tracer une forme ovoïde :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-oeuf-3-4-5.svg]]

Voici les étapes de cette méthode de construction :

1. tracer la droite $d$
2. choisir les points $A$ et $B$ sur $d$, distants de $4$ unités
3. tracer la droite $f$, perpendiculaire à $d$ au point $A$
4. on note $D$ et $E$ les points appartenant à $f$ et distants de $3$
   unités du point $A$
  - les triangles $ABD$ et $ABE$ sont des triangles $3,4,5$
5. tracer l’arc de cercle $\mathscr{C}_1$, de centre $A$ et de rayon $4$
6. tracer l’arc de cercle $\mathscr{C}_2$, de centre $E$ et de rayon $7$
  - on note $I$ l’intersection de $\mathscr{C}_2$ avec $(EB)$
7. tracer l’arc de cercle $\mathscr{C}_3$, de centre $D$ et de rayon $7$
  - on note $J$ l’intersection de $\mathscr{C}_3$ avec $(DB)$
8. tracer l’arc de cercle $\mathscr{C}_4$, de centre $B$ et passant par $I$
