
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Convergence et intégration
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:convint}

* Convergence monotone

Soit une suite de fonctions intégrables :

$$\{ u_n \in \setR^A : n \in \setR \}$$

Nous supposons que $u_n \esssuperieur 0$ pour tout $n \in \setN$ et que la suite soit essentiellement croissante :

$$u_0 \essinferieur u_1 \essinferieur u_2 \essinferieur u_3 \essinferieur ...$$

Nous supposons également que la fonction :

$$s = \sup \{ u_n : n \in \setN\}$$

est bien définie et intégrable :

$$S = \int_A s(x) \ d\mu(x) \strictinferieur +\infty$$


** Convergence des fonctions

Pour tout $n \in \setN$, on a $u_n \essinferieur u_{n + 1}$ et l'ensemble :

$$Z_n = \{ x \in A : u_n(x) \strictsuperieur u_{n + 1}(x) \}$$

est de mesure nulle. Il en va donc de même pour leur union :

$$Z = \bigcup_n Z_n$$

L'ensemble $\Phi = A \setminus Z$ est donc un sous-ensemble essentiel de $A$. Soit $x \in \Phi$. On a alors :

$$u_0(x) \le u_1(x) \le u_2(x) \le ...$$

La suite $\{ u_n(x) : n \in \setN \}$ est donc croissante et majorée par $s(x) = \sup_n u_n(x)$. Elle converge dès lors vers son supremum :

$$\lim_{n \to \infty} u_n(x) = s(x)$$


** Suite d'intégrales

On définit la suite $\{ I_n : n \in \setN \}$ par :

$$I_n = \int_A u_n(x) \ d\mu(x)$$

pour tout $n \in \setN$. Comme $u_n$ croît essentiellement avec $n$, on a $I_m \le I_n$ pour tout $m,n \in \setN$ vérifiant $m \le n$. Comme $u_n \le s$, on a aussi $I_n \le S$. On en conclut que la suite des $I_n$ converge vers son supremum et que :

$$L = \lim_{n \to \infty} I_n \le S = \int_A s(x) \ d\mu(x)$$


** Fonction étagée

Soit le réel $\epsilon \strictsuperieur 0$. Choisissons $w \in \mathcal{E}_A(s)$ telle que :

$$\int_A s(x) \ d\mu(x) \le \int_A w(x) \ d\mu(x) + \epsilon$$

Comme $w \essinferieur s$ l'ensemble :

$$N = \{ x \in A : w(x) \strictsuperieur s(x) \}$$

est de mesure nulle. Posons $\Psi = \Phi \setminus N$. La fonction $w$ étant étagée, on dispose d'une partition $\{A_1,...,A_N\}$ de $A$ et de réels $w_i$ tels que :

$$w = \sum_i w_i \cdot \indicatrice[A_i]$$

Posons $\Psi_i = A_i \cap \Psi$. Comme $\Psi \subseteq A$, les $\Psi_i$ forment une partition de $\Psi$ et on a :

$$w \cdot \indicatrice[\Psi] = \sum_i w_i \cdot \indicatrice[A_i] \cdot \indicatrice[\Psi] = \sum_i w_i \cdot \indicatrice[\Psi_i]$$

On en déduit que :

$$\int_\Psi w(x) \ d\mu(x) = \int_A w(x) \cdot \indicatrice_\Psi(x) \ d\mu(x) = \sum_i w_i \cdot \mu(\Psi_i)$$

L'intégrale étant invariante par abstraction d'un ensemble de mesure nulle, on a :

$$\int_\Psi w(x) \ d\mu(x) = \int_\Phi w(x) \ d\mu(x) = \int_A w(x) \ d\mu(x)$$

et finalement :

$$\int_A w(x) \ d\mu(x) = \sum_i w_i \cdot \mu(\Psi_i)$$


** Mesures convergentes

Choisissons un réel $\alpha$ vérifiant $0 \strictinferieur \alpha \strictinferieur 1$ et posons :

$$C_n = \{ x \in \Psi : \alpha \cdot w(x) \le u_n(x) \}$$

Soit :

\begin{align}
W_n^i &= C_n \cap \Psi_i = \{ x \in \Psi_i : \alpha \cdot w(x) \le u_n(x) \} \)

\(
X_n^i &= Z_n \cap \Psi_i = \{ x \in \Psi_i : u_n(x) \strictsuperieur u_{n + 1}(x) \}
\end{align}

Comme $X_n^i \subseteq Z_n$, on a $\mu(X_n^i) = 0$. Si $x \in W_n^i \setminus X_n^i$, on a :

$$\alpha \cdot w(x) \le u_n(x) \le u_{n + 1}(x)$$

On en déduit que $x \in W_{n + 1}^i$. Donc $W_n^i \setminus X_n^i \subseteq W_{n + 1}^i$ et :

$$\lim_{n \to \infty} \mu(W_n^i) = \mu\left( \bigcup_n W_n^i \right)$$

Comme les $W_n^i \subseteq \Psi_i$, il est clair que leur union sur $n$ est inclue dans $\Psi_i$. Soit $x \in \Psi_i$.

  - Si $s(x) = 0$, on a $0 \le u_n(x) \le s(x) = 0$ pour tout $n \in \setN$ et $u_n(x) = 0$. On a aussi $w(x) \le s(x) = 0$, d'où $\alpha \cdot w(x) \le 0 = u_n(x)$ et $x \in W_n^i$.

  - Considérons à présent le cas où $s(x) \strictsuperieur 0$. On se rappelle que $\Psi_i \subseteq \Psi = \Phi \setminus N$. Donc $x \notin N$ et on a $w(x) \le s(x)$. Multipliant cette relation par $\alpha \strictsuperieur 0$, on obtient $\alpha \cdot w(x) \le \alpha \cdot s(x)$. Soit le réel :

$$\delta = (1 - \alpha) \cdot s(x) \strictsuperieur 0$$

Sur $\Psi_i \subseteq \Psi \subseteq \Phi$, la suite des $\{ u_n(x) : n \in \setN \}$ converge vers $s(x)$. On peut donc trouver un $K \in \setN$ tel que $\abs{u_n(x) - s(x)} \le \delta$ pour tout naturel $n$ vérifiant $n \ge K$. On a alors :

$$u_n(x) \ge s(x) - \delta = s(x) - (1 - \alpha) \cdot s(x) = \alpha \cdot s(x) \ge \alpha \cdot w(x)$$

Il existe donc un naturel $n$ tel que $x \in C_n$, d'où $x \in C_n \cap \Psi_i = W_n^i$.

Notre $x$ appartient donc à l'union sur $n$ des $W_n^i$. On en conclut que $\Psi_i$ est inclu dans l'union sur $n$ des $W_n^i$. La réciproque étant également vraie, on a :

$$\bigcup_n W_n^i = \Psi_i$$

et :

$$\lim_{n \to \infty} \mu(W_n^i) = \mu(\Psi_i)$$


** Convergence des intégrales

Fixons $n \in \setN$. Comme $C_n \subseteq A$, les $W_n^i = C_n \cap \Psi_i$ forment une partition de $C_n$ et on a :

$$w \cdot \indicatrice[C_n] = \sum_i w_i \cdot \indicatrice[C_n] \cdot \indicatrice[\Psi_i] = \sum_i w_i \cdot \indicatrice[W_n^i]$$

On en déduit que :

$$\int_{C_n} w(x) \ d\mu(x) = \int_A w(x) \cdot \indicatrice_{C_n}(x) \ d\mu(x) = \sum_i w_i \cdot \mu(W_n^i)$$

En passant à la limite sur $n$, on obtient donc :

\begin{align}
\lim_{n \to \infty} \int_{C_n} w(x) \ d\mu(x) &= \sum_i w_i \cdot \lim_{n \to \infty} \mu(W_n^i) \)

\(
&= \sum_i w_i \cdot \mu(\Psi_i) \)

\(
&= \int_A w(x) \ d\mu(x)
\end{align}

Comme $\alpha \cdot w \le u_n$ sur $C_n$, on a a fortiori l'infériorité essentielle et :

$$\int_{C_n} \alpha \cdot w(x) \ d\mu(x) = \alpha \int_{C_n} w(x) \ d\mu(x) \le \int_A u_n(x) \ d\mu(x) = I_n$$

En passant à la limite sur $n$ et en multipliant par $1/\alpha$, on en déduit que :

$$\int_A w(x) \ d\mu(x) \le \unsur{\alpha} \lim_{n \to \infty} I_n = \frac{L}{\alpha}$$

Se rappelant la propriété de $w$ par rapport à $s$, on a :

$$\int_A s(x) \ d\mu(x) - \epsilon \le \int_A w(x) \ d\mu(x) \le \frac{L}{\alpha}$$

Donc :

$$S - \epsilon = \int_A s(x) \ d\mu(x) - \epsilon \le \frac{L}{\alpha}$$

Ce résultat devant être satisfait pour tout $\epsilon \strictsuperieur 0$ et pour tout $0 \strictsuperieur \alpha \strictsuperieur 1$, on a finalement $S \le L$. Mais nous avons vu précédemment que $L \le S$. On en conclut que $S = L$, c'est-à-dire :

$$\int_A \lim_{n \to \infty} u_n(x) \ d\mu(x) = \lim_{n \to \infty} \int_A u_n(x) \ d\mu(x)$$


* Convergence des sommes

Soit une suite $\{ f_n \in \setR^A : n \in \setN \}$ de fonctions intégrables essentiellement positives. Posons :

$$u_n = \sum_{i = 0}^n f_i$$

On voit que la suite des $u_n$ est croissante et essentiellement positive. Si la somme converge, on a :

$$\lim_{n \to \infty} u_n(x) = \sum_{i = 0}^{+\infty} f_i(x) = s(x)$$

pour tout $x \in A$. Si la fonction $s$ ainsi définie est intégrable, on a donc :

$$\int_A \sum_{i = 0}^{+\infty} f_i(x) \ d\mu(x) = \lim_{n \to \infty} \int_A \sum_{i = 0}^n f_i(x) \ d\mu(x)$$


* Lemme de Fatou

Soit une suite $\{ f_n \in \setR^A : n \in \setN \}$ de fonctions intégrables essentiellement positives. Posons :

$$u_n = \inf \{ f_m : m \in \setN, \  m \ge n \}$$

et supposons que la fonction $s = \sup_n u_n$ soit bien définie et intégrable. Par construction, la suite des $u_n$ est croissante et essentiellement positive. On a donc $\int_A \lim_n u_n = \lim_n \int_A u_n$, c'est-à-dire :

$$\int_A \liminf_{n \to \infty} f_n(x) \ d\mu(x) = \lim_{n \to \infty} \int_A u_n(x) \ d\mu(x)$$

Comme la limite des $U_n = \int_A u_n$ existe, on a $\liminf_n U_n = \lim_n U_n$ et :

$$\int_A \liminf_{n \to \infty} f_n(x) \ d\mu(x) = \liminf_{n \to \infty} \int_A u_n(x) \ d\mu(x)$$

Comme $u_n \le f_n$, on a $U_n \le F_n = \int_A f_n$. On en conclut que $\liminf_n U_n \le \liminf_n F_n$ :

$$\liminf_{n \to \infty} \int_A u_n(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

Rassemblant ces résultats, il vient :

$$\int_A \liminf_{n \to \infty} f_n(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$


* Convergence dominée

Soit une suite de fonctions $\{ f_n : n \in \setN \}$ intégrables sur $\Omega$. Nous supposons qu'il existe un sous-ensemble essentiel $A$ de $\Omega$ et une fonction $f : A \mapsto \setR$ telle que :

$$\lim_{n \to \infty} f_n(x) = f(x)$$

pour tout $x \in A$. Nous supposons également qu'il existe une fonction intégrable $\varphi : A \mapsto \setR$ telle que $\abs{f_n} \le \varphi$ pour tout $n \in \setN$.

Soit $x \in A$. Puisque la suite $\{ \abs{f_n(x)} : n \in \setN \}$ est inférieure à $\varphi(x)$, sa limite $\abs{f(x)}$ vérifie $\abs{f(x)} \le \varphi(x)$. On a donc $\abs{f} \le \varphi$ et $\int_A \abs{f} \le \int_A \varphi \strictinferieur +\infty$, ce qui montre que $f$ est intégrable. La majoration par $\varphi$ nous montre également que $\varphi - \max \{ f_n , -f_n \} \ge 0$, d'où :

#+BEGIN_CENTER
\(
\varphi - f_n \ge 0 \)

\(
\varphi + f_n \ge 0
\)
#+END_CENTER

On peut donc appliquer le lemme de Fatou à la suite de fonctions $\psi_n = \varphi - f_n$. On obtient :

$$\int_A \liminf_{n \to \infty} [\varphi(x) - f_n(x)] \ d\mu(x) \le \liminf_{n \to \infty} \int_A [\varphi(x) - f_n(x)] \ d\mu(x)$$

On sait que la fonction $\varphi$ ne dépend pas de $n$ et que la limite de $f_n$ existe. On a donc $\liminf_n f_n = \limsup_n f_n = \lim f_n$. Comme $\inf(-X) = -\sup(X)$, on a aussi :

$$\liminf_n (-f_n) = - \limsup_n f_n = - \lim_n f_n = -f$$

On en déduit que :

$$\int_A \liminf_n [\varphi - f_n] = \int_A \varphi - \int_A f$$

Pour le second membre, on a :

$$\liminf_n \int_A [\varphi - f_n] = \int_A \varphi + \liminf_n \left[ - \int_A f_n \right] = \int_A \varphi - \limsup_n \int_A f_n$$

On se retrouve donc avec l'inégalité :

$$\int_A \varphi - \int_A f \le \int_A \varphi - \limsup_n \int_A f_n$$

Eliminant l'intégrale de $\varphi$, il vient :

$$\int_A f(x) \ d\mu(x) \ge \limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

Appliquons à présent le lemme de Fatou à la suite de fonctions $\omega_n = \varphi + f_n$. On obtient :

$$\int_A \liminf_{n \to \infty} [\varphi(x) + f_n(x)] \ d\mu(x) \le \liminf_{n \to \infty} \int_A [\varphi(x) + f_n(x)] \ d\mu(x)$$

Utilisant les mêmes remarques que précédemment et éliminant l'intégrale de $\varphi$, il vient :

$$\int_A f(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

Rassemblant ces résultats, on en déduit que :

$$\limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

Mais on sait que $\liminf(X) \le \limsup(X)$. On conclut de ces deux inégalités que :

$$\limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x) = \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

La limite de la suite d'intégrales existe donc et :

$$\lim_{n \to \infty} \int_A f_n(x) \ d\mu(x) = \limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x) = \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

Les bornes faisant intervenir l'intégrale de $f$ deviennent :

$$\lim_{n \to \infty} \int_A f_n(x) \ d\mu(x) \le \int_A f(x) \ d\mu(x) \le \lim_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

d'où :

$$\int_A f(x) \ d\mu(x) = \lim_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

Nous venons de prouver que :

$$\int_A \lim_{n \to \infty} f_n(x) \ d\mu(x) = \lim_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

L'intégrale étant invariante sous abstraction d'un ensemble de mesure nulle, on a même :

$$\int_\Omega f(x) \ d\mu(x) = \lim_{n \to \infty} \int_\Omega f_n(x) \ d\mu(x)$$

pour autant que $f$ soit définie sur $\Omega$.


