
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Dérivées ordinaires
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:differentielles}

* Notation

Afin d’alléger les notations, nous notons :

$$ \lim_{h \to 0} = \lim_{ \substack{ h \to 0 \\ h \ne 0 } } $$

$$ \lim_{b \to a} = \lim_{ \substack{ b \to a \\ b \ne a } } $$

tout au long de ce chapitre.

* Introduction

#+TOC: headlines 1 local

** Définition

Soit un ensemble $A \subseteq \setR$. L'idée à la base de la notion
de dérivée est de linéariser localement une fonction $f : A \mapsto
\setR$ autour d'un point $a \in A$. Pour tout $h \in \setR$ suffisamment
proche de zéro, on veut donc avoir :

$$ f(a + h) - f(a) \approx D f(a) \cdot h $$

où $D f(a) \in \setR$. On demande que l'erreur donnée par :

$$ E(h) = f(a + h) - f(a) - D f(a) \cdot h $$

devienne négligeable par rapport à :

$$ D f(a) \cdot h $$

lorsque $h$ tend vers $0$. Comme $D f(a)$ ne dépend pas de $h$, il nous
suffit d'imposer que :

$$\lim_{h \to 0} \frac{E(h)}{h} = 0$$

Si ces conditions sont vérifiées, on dit que $f$ est dérivable en $a$
et que $D f(a)$ est la dérivée de $f$ en $a$. On a alors :

$$ f(a + h) - f(a) = D f(a) \cdot h + E(h) $$

ou encore :

$$ f(a + h) = f(a) + D f(a) \cdot h + E(h) $$

** Limite

Si on divise par $h$ la relation :

$$ f(a + h) - f(a) = D f(a) \cdot h + E(h) $$

on obtient :

$$ \frac{f(a + h) - f(a)}{h} = D f(a) + \frac{E(h)}{h} $$

ou encore :

$$ D f(a) = \frac{f(a + h) - f(a)}{h} - \frac{E(h)}{h} $$

En prenant la limite pour $h \to 0$, cette relation devient :

$$ \lim_{h \to 0} D f(a) = \lim_{h \to 0} \frac{f(a + h) - f(a)}{h} - \lim_{h \to 0} \frac{E(h)}{h} $$

La dernière limite du membre de droite est nulle par définition de la
dérivée. On a donc :

$$ \lim_{h \to 0} D f(a) = \lim_{h \to 0} \frac{f(a + h) - f(a)}{h} $$

Comme le membre de gauche ne dépend pas de $h$, on a simplement :

$$ D f(a) = \lim_{h \to 0} \frac{f(a + h) - f(a)}{h} $$

*** Définition équivalente

Si on pose $b = a + h$, on voit que $h = b - a$ et que la
convergence $h \to 0$ est équivalente à $b \to a$. On a donc :

$$ D f(a) = \lim_{b \to a} \frac{f(b) - f(a)}{b - a} $$

** Fonction dérivée

Si la fonction $f$ est dérivable partout sur l’ensemble $A$, le réel
$D f(a)$ existe pour tout $a \in A$. On peut donc définir la fonction
$D f$ par :

$$ D f : a \mapsto D f(a) $$

Cette fonction $D f$ est appelée dérivée de $f$.

** Opérateur de dérivation

L’opérateur de dérivation $D$ construit une dérivée $D f$ à
partir de n’importe quelle fonction dérivable $f$. Il est formellement
défini par :

$$ D : f \mapsto D f $$

pour toute fonction $f$ dérivable sur $\domaine f$.

** Notations

#+TOC: headlines 1 local

*** Notation d’Euler

La notation que nous avons utilisée jusqu’ici, qui écrit la dérivée
d’une fonction $f$ en la précédant d’un $D$ :

$$ D f $$

est la notation d’Euler.

*** Notation de Lagrange

La notation de Lagrange écrit la dérivée d’une fonction $f$ avec un
prime juste à droite du nom de la fonction :

$$ f' = D f $$

*** Notation de Newton

La notation de Newton écrit la dérivée d’une fonction $f$ en la
surmontant d’un point :

$$ \dot{f} = D f $$

*** Notation de Leibniz

Reprenons l’expression de la dérivée en $a$ sous forme de limite :

$$ D f(a) = \lim_{h \to 0} \frac{f(a + h) - f(a)}{h} $$

Si on définit :

$$ \difference f = f(a + h) - f(a) $$

$$ \difference x = (a + h) - (a) = h $$

on a schématiquement :

$$ D f(a) = \lim_{\difference x \to 0} \frac{\difference f}{\difference x} $$

La dérivée est donc la limite d’une fraction de différences. En
utilisant un delta minuscule pour désigner le fait que ces variations
tendent vers zéro, on peut noter la dérivée en $a$ par :

$$ \frac{\delta f}{\delta x}(a) = \lim_{\difference x \to 0} \frac{\difference f}{\difference x} $$

La notation de Leibniz utilise des $d$ minuscules au lieu des deltas :

$$\OD{f}{x}(a) = \lim_{h \to 0} \frac{f(a + h) - f(a)}{h}$$

ce qui nous donne une autre façon de noter la fonction dérivée :

$$\OD{f}{x} = D f $$

Cette notation permet d’obtenir intuitivement de nombreux résultats
concernant les propriétés des dérivées.

*** Notation personnelle

Dans cet ouvrage, j’utilise la notation :

$$\partial f = D f $$

que je trouve claire et compacte.

Attention, ce n’est pas une notation standard en mathématiques.

* Continuité

Soit une fonction $f : A \mapsto \setR$ dérivable sur $A$ et $a \in
A$. L'expression de $f(a + h)$ peut s'écrire :

$$f(a + h) = f(a) + f'(a) \cdot h + E(h)$$

En prenant la limite quand $h \to 0$, on a :

$$ \lim_{h \to 0} f(a + h)
= f(a) + \lim_{h \to 0} f'(a) \cdot h + \lim_{h \to 0} E(h) $$

On peut faire sortir $f'(a)$ de la limite :

\begin{align*}
\lim_{h \to 0} f(a + h)
&= f(a) + f'(a) \cdot \lim_{h \to 0} h + \lim_{h \to 0} E(h) \\
&= f(a) + f'(a) \cdot 0 + \lim_{h \to 0} E(h) \\
&= f(a) + \lim_{h \to 0} E(h)
\end{align*}

Comme :

\begin{align*}
\lim_{h \to 0} E(h)
&= \lim_{ h \to 0} h \cdot \frac{E(h)}{h} \\
&= \left[\lim_{ h \to 0} h\right] \cdot \left[\lim_{ h \to 0} \frac{E(h)}{h}\right] \\
&= 0 \cdot 0 \\
&= 0
\end{align*}

l’expression de $f(a+h)$ devient :

$$ \lim_{h \to 0} f(a + h) = f(a) $$

Si $f$ est différentiable en $a$, elle est forcément continue en $a$.

* Accroissement infinitésimal

#+TOC: headlines 1 local

** Introduction

Une variation infinitésimale est une variation aussi proche que l’on
veut de zéro. En langage des limites, on peut donc faire tendre cette
variation vers zéro.

La notation de Leibniz permet de visualiser aisément la variation
infinitésimale d’une fonction $f : A \mapsto \setR$ dérivable sur
$A$. Si on la combine avec la notation de Lagrange, on a :

$$ \OD{f}{x} = f' $$

En multipliant par la variation infinitésimale $dx$ de $x$, on a :

$$ df = f' \ dx $$

ou, plus précisément :

$$ df(x) = f'(x) \ dx $$

On retrouve aussi cette expression infinitésimale sous la forme :

$$ \delta f = f' \ \delta x $$

Cette expression nous ramène à l’approximation :

$$ \difference f \approx f' \ \difference x $$

avec une erreur qui tend vers zéro plus vite que $\difference x$.

** Variables liées

Soit deux variables $x$ et $y$ reliées par la fonction $f$ comme suit :

$$ y = f(x) $$

On a alors :

$$ dy = df $$

c’est-à-dire :

$$ dy = f' \ dx $$

** Généralisation

Soit deux variables $x$ et $y$ reliées par les fonctions $f$ et $g$
comme suit :

$$ g(y) = f(x) $$

On en déduit que :

$$ dg(y) = df(x) $$

c’est-à-dire :

$$ g'(y) \ dy = f'(x) \ dx $$

* Dérivée seconde

#+TOC: headlines 1 local

** Introduction

Soit une fonction $f : A \mapsto \setR$ dérivable sur $A$. Si la dérivée $D
f$ est elle-même dérivable, on peut évaluer la dérivée de cette dérivée :

$$ D^2 f = D D f = D (D f) $$

La fonction $D^2 f$ est appelée dérivée seconde de $f$.

** Notations

#+TOC: headlines 1 local

*** Notation de Lagrange

La notation de Lagrange écrit la dérivée seconde d’une fonction $f$
avec un double prime juste à droite du nom de la fonction :

$$ f'' = D^2 f $$

*** Notation de Newton

La notation de Newton écrit la dérivée d’une fonction $f$ en la
surmontant d’un double point :

$$ \ddot{f} = D f $$

*** Notation de Leibniz

La notation de Leibniz pour la dérivée seconde identifie les
opérateurs :

$$ \left(\OD{}{x}\right)^2 = D^2 $$

et :

$$ \OOD{}{x} = \left(\OD{}{x}\right)^2 $$

On a donc la notation :

$$ \OOD{f}{x} = D^2 f $$

ou, en $a \in \domaine f$ :

$$ \OOD{f}{x}(a) = D^2 f(a) $$

*** Notation personnelle

Dans cet ouvrage, j’utilise la notation :

$$\partial^2 f = D^2 f $$

* Dérivée d’ordre $n$

#+TOC: headlines 1 local

** Introduction

Soit $n \in \setN$. Si la fonction $f : A \mapsto \setR$ est $n$ fois dérivable sur $A$,
on appelle :

$$ D^n f $$

la dérivée d’ordre $n$ de $f$.

** Notations

#+TOC: headlines 1 local

*** Notation de Lagrange

La notation de Lagrange écrit la dérivée d’ordre $n$ d’une fonction
$f$ en plaçant un $(n)$ en indice supérieur :

$$ f^{(n)} = D^n f $$

Attention, le $(n)$ n’est pas une puissance.

*** Notation de Leibniz

La notation de Leibniz pour la dérivée d’ordre $n$ identifie les
opérateurs :

$$ \left(\OD{}{x}\right)^n = D^n $$

et :

$$ \NOD{}{x}{n} = \left(\OD{}{x}\right)^n $$

On a donc la notation :

$$ \NOD{f}{x}{n} = D^n f $$

ou, en $a \in \domaine f$ :

$$ \NOD{f}{x}{n}(a) = D^n f(a) $$

*** Notation personnelle

Dans cet ouvrage, j’utilise la notation :

$$\partial^n f = D^n f $$
