
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Dérivées partielles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:differentielles}

* Notation

Afin d’alléger les notations, nous notons :

$$ \lim_{h \to 0} = \lim_{ \substack{ h \to 0 \\ h \ne 0 } } $$

$$ \lim_{b \to a} = \lim_{ \substack{ b \to a \\ b \ne a } } $$

tout au long de ce chapitre.

* Définition

#+TOC: headlines 1 local

** Introduction

Nous allons à présent voir comment obtenir les composantes de
la différentielle dans le cas d'espaces de dimensions finies. Nous
disposons donc d'une base $(\varpi_1,...,\varpi_n)$ de $\Omega$ et d'une
base $(\phi_1,...,\phi_m)$ de $F$. Nous introduisons les composantes
$f_1,...,f_m : \Omega \mapsto F$ de $f$ telles que :

$$f(x) = \sum_{i = 1}^m f_i(x) \cdot \phi_i$$

pour tout $x \in \Omega$. Nous procédons de même pour l'erreur :

$$E(h) = \sum_{i = 1}^m E_i(h) \cdot \phi_i$$

pour tout $h \in \Omega$. Nous allons également utiliser les coordonnées $h_1,...,h_n \in \corps$ de $h$ :

$$h = \sum_{i = 1}^n h_i \cdot \varpi_i$$

Par linéarité :

$$f(a + h) - f(a) = \sum_{j = 1}^n \differentielle{f}{a}(\varpi_j) \cdot h_j + E(h)$$

Mais on peut trouver des $\Delta_{ij} \in \corps$ tels que :

$$\differentielle{f}{a}(\varpi_j) = \sum_{i = 1}^m \Delta_{ij} \cdot \phi_i$$

Injectons les expressions des composantes dans $F$. On obtient :

$$\sum_i \phi_i \cdot \left[ f_i(a + h) - f_i(a) - E_i(h) - \sum_{j = 1}^n \Delta_{ij} \cdot h_j \right] = 0$$

Par indépendance linéaire des $\phi_i$, on a alors :

$$f_i(a + h) - f_i(a) = \sum_{j = 1}^n \Delta_{ij} \cdot h_j + E_i(h)$$

pour tout $i \in \setZ(1,m)$. On nomme $\Delta_{ij}$ la dérivée partielle de $f_i$ par rapport à $\varpi_j$. On la note :

$$\partial_j f_i(a) = \deriveepartielle{f_i}{x_j}(a) = \Delta_{ij}$$

*** Attention

Ne pas confondre la frontière $\frontiere A$ d'un ensemble $A$ avec la dérivée $\partial f$ d'une fonction $f$.

** Dérivées et limites

Soit $\lambda \in \corps$. Si l'on choisit $h = \lambda \ \varpi_j$, on a $h_k = \lambda \ \indicatrice_{jk}$ et :

$$ f_i(a + \lambda \ \varpi_j) - f_i(a) = \sum_{k = 1}^n \partial_k f_i(a) \cdot \lambda \cdot \indicatrice_{jk} +  E_i(h) $$

$$ f_i(a + \lambda \ \varpi_j) - f_i(a) = \lambda \cdot \partial_j f_i(a)  +  E_i(h) $$

En divisant l'équation ci-dessus par $\lambda$ puis en faisant tendre $\lambda$ vers 0, on obtient :

$$\partial_j f_i(a) = \lim_{\lambda \to 0} \left[ \frac{f_i(a + \lambda \ \varpi_j) - f_i(a)}{\lambda} - \frac{E_i(h)}{\lambda} \right]$$

Comme l'erreur doit converger plus vite vers zéro que la norme $\norme{h}
= \abs{\lambda}$, la limite du second terme du membre de droite s'annule
et on a :

$$\partial_j f_i(a) = \lim_{\lambda \to 0} \frac{f_i(a + \lambda \ \varpi_j) - f_i(a)}{\lambda}$$

Ce qui montre que la dérivée partielle $\partial_j f_i$ est la variation de $f_i$ obtenue lorsqu'on fait varier la $j^{ème}$ variable (celle correspondant à $\varpi_j$).

** Matrice Jacobienne

On associe à la différentielle $\differentielle{f}{a}$ la matrice
Jacobienne $\partial f(a)$ de $f$ en $a$ définie par :

$$\partial f(a) = \Big( \partial_j f_i(a) \Big)_{i,j}$$

On peut alors écrire la linéarisation de $f$ sous forme de produit matriciel :

$$f(a + h) - f(a) = \partial f(a) \cdot h + E(h)$$

où $f,h,E$ sont les vecteurs colonnes associés aux grandeurs du même nom.

*** Notation

Dans le cas où la variable porte un nom par défaut, comme par exemple :

$$f : x \mapsto f(x)$$

on note aussi :

$$\deriveepartielle{f}{x}(a) = \partial f(a)$$

ou encore :

$$ \deriveepartielle{f}{x^T} = \Big( \partial_j f_i(a) \Big)_{i,j} $$

On utilise parfois la transposée de la Jacobienne :

$$\Big[ \partial f(x) \Big]^T = \deriveepartielle{f^T}{x} = \left( \deriveepartielle{f}{x^T} \right)^T$$

de composantes :

$$ \deriveepartielle{f^T}{x} = \Big( \partial_i f_j(a) \Big)_{i,j} $$

**** Plusieurs sous-variables

Lorsque plusieurs sous variables portent un nom par défaut, comme par exemple :

$$f : (x,y) \mapsto f(x,y)$$

on note aussi :

$$\deriveepartielle{f}{x}(a) = \partial_x f(a)$$

pour la Jacobienne par rapport aux variables $x = (x_1,...,x_s)$ et :

$$\deriveepartielle{f}{y}(a) = \partial_y f(a)$$

pour la Jacobienne par rapport aux variables $y = (y_1,...,y_t)$

**** Symbolique

On a aussi les notations symboliques :

$$ df_i = \sum_j \deriveepartielle{f_i}{x_j} \ dx_j $$

ou, sous forme de produit matriciel :

$$ df = \deriveepartielle{f}{x^T} \ dx $$

où $df$ représente une petite variation de $f$ suite à une petite variation $dx$ de $x$.

*** Vecteurs associés

On dispose de $n$ vecteurs représentant chacun la dérivée des
composantes de $f$ par rapport à la $j^{ème}$ variable :

$$\partial_j f(a) = \Big( \partial_j f_i(a) \Big)_i$$

et de $m$ vecteurs représentant chacun les dérivées de la $i^{ème}$
composante de $f$ :

$$\partial f_i(a) = \Big( \partial_j f_i(a) \Big)_j$$

*** Gradient

Pour des fonctions du type $f : \setR^n \mapsto \setR$, la Jacobienne
se réduit à un vecteur colonne. On dit alors que $\partial f$ est le
gradient de $f$.

* L'application dérivée

Si $f$ est différentiable en tout vecteur $a$ de $A \subseteq \Omega$,
on dit que $f$ est différentiable sur $A$. On peut alors définir une
application dérivée $\partial f : A \mapsto \matrice(\corps,m,n)$
définie par :

$$\partial f : a \mapsto \partial f(a)$$

pour tout $a \in A$. Si cette nouvelle application $\partial f$ est
également continue, on dit que $f$ est continûment différentiable. On
note $\continue^1(A,F)$ l'ensemble des fonctions continûment
différentiables de $A$ vers $F$.

* Dérivée seconde

#+TOC: headlines 1 local

** Hessienne

Soit $f : \Omega \mapsto \corps$ avec $\Omega$ de dimension finie
$n$. Supposons que $f$ est différentiable sur $A \subseteq \Omega$. La
dimension de $\corps$ sur $\corps$ étant $1$, la Jacobienne $\partial
f(a)$ se réduit à un vecteur colonne de composantes $\partial_i
f$. Si la dérivée $\partial f : A \mapsto \corps^n$ est elle-même
différentiable, on nomme l'application définie par :

$$\partial^2 f = \partial \left( \partial f \right)$$

la dérivée seconde de $f$. Il s'agit d'une fonction qui transforme
un élément de $A$ en un « vecteur colonne de vecteurs colonnes »
appartenant à $\matrice(\corps^n,n,1)$. On peut assimiler cet objet à
une matrice équivalente de taille $(n,n)$ dont les composantes sont des
éléments de $\corps$. En définitive, nous avons $\partial^2 f(a) \in
\matrice(\corps,n,n)$ pour tout $a \in A$. Cette matrice est appellée
hessienne de $f$ en $a$. Ses composantes sont données par :

$$\partial_{ij}^2 f(a) = \partial_i \left( \partial_j f \right)(a)$$

*** Notation

On note aussi :

$$\dfdxdy{f}{x_i}{x_j}(a) = \partial_{ij}^2 f(a)$$

Lorsque $i = j$, on note :

$$\dfdxdx{f}{x_i} = \dfdxdy{f}{x_i}{x_i} = \partial_{ii}^2 f(a)$$

En termes matriciels, cela donne :

$$\dblederiveepartielle{f}{x}(a) = \partial^2 f(a)$$

** Continuité

On note $\continue^2(A,\corps)$ l'ensemble des fonctions dont la dérivée
seconde est continue sur $A$.

* Dérivée d'ordre $k$

Soit $f : \corps \mapsto \corps$ et $k \in \setN$. Pour autant que la
fonction $f$ soit suffisamment dérivable, on définit par récurrence
la fonction $\partial^k f : \corps \mapsto \corps$ :

$$ \partial^0 f = f $$

$$ \partial^k f = \partial \big( \partial^{k-1} f \big) $$

La dérivée d'ordre $k$  de $f$ est donc la fonction obtenue lorsqu'on
applique un nombre $k$ de fois l'opérateur de dérivation $\partial$
à la fonction $f$ :

$$\partial^k f = (\partial \circ ... \circ \partial)(f)$$

** Ensembles

On note $\continue^k(A,\corps)$ l'ensemble des fonctions $f : A \mapsto \corps$ dont la dérivée d'ordre $k$ :

$$\partial^k f : A \mapsto \corps$$

existe et est continue sur $A$.

*** Infini

Si la dérivée $\partial^k f$ existe pour tout $k \in \setN$, on dit que $f$ est indéfiniment dérivable. On note $\continue^\infty(A,\corps)$ l'ensemble des fonctions indéfiniment dérivables.


*** Ordre $0$

On voit que $\continue^0 = \continue$.


** Homéomorphisme

On note $\homeomorphisme^k(A,\corps)$ l'ensemble des bijections $f$ de $\continue^k$ telles que la fonction $f^{-1}$ soit aussi dans $\continue^k$.


** Notations

Pour $\alpha = (\alpha_1, \alpha_2, ..., \alpha_n)$, on écrit également :

#+BEGIN_CENTER
\(
\partial^\alpha f = \partial^{\alpha_1 ... \alpha_n} f =
\partial_1^{\alpha_1} ... \partial_n^{\alpha_n} f
\)
#+END_CENTER


