
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Différentielles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:differentielles}

* Notation

Afin d’alléger les notations, nous notons :

$$ \lim_{h \to 0} = \lim_{ \substack{ h \to 0 \\ h \ne 0 } } $$

$$ \lim_{b \to a} = \lim_{ \substack{ b \to a \\ b \ne a } } $$

tout au long de ce chapitre.

* Définition

Soit les espaces vectoriels $\Omega, F$ sur $\corps$.

La notion de différentielle généralise celle de dérivée ordinaire.
On cherche à linéariser localement une fonction $f : \Omega \mapsto F$
autour d'un point $a \in \Omega$. Pour tout $h \in \Omega$ suffisamment
petit, on veut donc avoir :

$$ f(a + h) - f(a) \approx \differentielle{f}{a}(h) $$

où $\differentielle{f}{a}$ est une application linéaire de $\Omega$
vers $F$. Attention, le $f$ au-dessus du $\mathfrak{D}$ est un indice
supérieur indiquant la fonction différentiée, ce n’est pas une
puissance. On suppose que la norme de $\differentielle{f}{a}$ existe,
de sorte que nous puissions écrire :

$$\norme{ \differentielle{f}{a}(h) } \le \norme{ \differentielle{f}{a} } \cdot \norme{h}$$

On demande que la norme de l'erreur donnée par :

$$E(h) = f(a + h) - f(a) - \differentielle{f}{a}(h)$$

devienne négligeable par rapport à :

$$\norme{ \differentielle{f}{a} } \cdot \norme{h}$$

lorsque $h$ tend vers $0$. Comme la norme de la différentielle ne varie pas, il nous suffit d'imposer que :

$$\lim_{ \substack{ h \to 0 \\ h \ne 0 } } \frac{ \norme{E(h)} }{ \norme{h} } = 0$$

Si ces conditions sont vérifiées, on dit que $f$ est différentiable
en $a$ et que $\differentielle{f}{a}$ est la différentielle de $f$
en $a$. On a alors :

$$f(a + h) - f(a) = \differentielle{f}{a}(h) + E(h)$$

ou encore :

$$f(a + h) = f(a) + \differentielle{f}{a}(h) + E(h)$$

** Continuité

L'expression de $f(a + h)$ peut donc s'écrire :

$$f(a + h) = f(a) + \differentielle{f}{a}(h) + E(h)$$

En prenant la limite quand $h \to 0$, on a :

$$ \lim_{h \to 0} f(a + h) = f(a) + \lim_{h \to 0} \differentielle{f}{a}(h) + \lim_{h \to 0} E(h) $$

La norme de la différentielle étant finie :

$$ \lim_{h \to 0} \norme{ \differentielle{f}{a}(h) } \le \lim_{h \to 0} \norme{ \differentielle{f}{a} } \cdot \norme{h}$$

elle tend vers zéro avec $h$ :

$$ \lim_{h \to 0} \norme{ \differentielle{f}{a}(h) }
\le \norme{ \differentielle{f}{a} } \cdot \lim_{h \to 0} \norme{h}
= \norme{ \differentielle{f}{a} } \cdot \norme{0}
= 0$$

et donc :

$$ \lim_{h \to 0} \differentielle{f}{a}(h) = 0 $$

On a aussi :

\begin{align*}
\lim_{h \to 0} \norme{E(h)}
&= \lim_{ h \to 0} \norme{h} \cdot \frac{ \norme{E(h)} }{ \norme{h} } \\
&= \left[ \lim_{ h \to 0} \norme{h} \right] \cdot \left[ \lim_{ h \to 0} \frac{ \norme{E(h)} }{ \norme{h} } \right] \\
&= 0
\end{align*}

et donc :

$$\lim_{h \to 0} E(h) = 0$$

L’expression de $f(a+h)$ devient :

$$ \lim_{h \to 0} f(a + h) = f(a) + 0 + 0 = f(a) $$

Si $f$ est différentiable en $a$, elle est forcément continue en $a$.

* Fonctions à intégrale continue

Soit une fonction $u : A \mapsto B$. Si la fonction $v$ définie par :

$$v(x) = \int_a^x u(x) \ d\mu(x)$$

est continue, on dit que $u$ est à intégrale continue. On note
$\continue_{\mu}^{-1}(A,B)$ l'ensemble des fontions à intégrale
continue.

* Différentiabilité uniforme

On dit qu'une fonction $f$ est uniformément différentiable sur $A$
si pour tout $\epsilon \strictsuperieur 0$, on peut trouver un $\delta
\strictsuperieur 0$ tel que :

$$\abs{f(s) - f(t) - \partial f(t) \cdot (s - t)} \le \epsilon \cdot \abs{s - t}$$

quel que soit $s,t \in A$ vérifiant $\abs{s - t} \le \delta$.
