
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Dimension n
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:dimensionN}

* Dépendances

  - Chapitre \ref{chap:naturel} : Les naturels
  - Chapitre \ref{chap:entier} : Les entiers
  - Chapitre \ref{chap:rationel} : Les rationnels
  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes

* Définition

Conformément à la définition de la « puissance » d'un ensemble,
$\setN^n$ est l'ensemble des n-tuples :

$$\setN^n = \{ (m_1,m_2,...,m_n) : m_1,m_2,...,m_n \in \setN \}$$

où chaque composante $m_i$ est un naturel. On a pareillement :

$$ \setZ^n = \{ (z_1,z_2,...,z_n) : z_1,z_2,...,z_n \in \setN \} $$

$$ \setQ^n = \{ (q_1,q_2,...,q_n) : q_1,q_2,...,q_n \in \setQ \} $$

$$ \setR^n = \{ (r_1,r_2,...,r_n) : r_1,r_2,...,r_n \in \setR \} $$

$$ \setC^n = \{ (c_1,c_2,...,c_n) : c_1,c_2,...,c_n \in \setC $$

Dans la suite, nous notons :

$$\mathcal{D} = \{ \setN^n , \setZ^n , \setQ^n , \setR^n , \setC^n \}$$

On dit que les éléments de $\mathcal{D}$ sont des ensembles de dimension $n$.

* Egalité

Soit l'ensemble $A^n \in \mathcal{D}$ et $x,y \in A^n$. On a :

$$ x = (x_1,x_2,...,x_n) $$

$$ y = (y_1,y_2,...,y_n) $$

On dit que $x = y$ si et seulement si $x_i = y_i$ pour tout $i \in \{1,2,...,n\}$.

* Élément nul

Soit l'ensemble $A^n \in \mathcal{D}$. Le tuple $0_n \in A^n$ défini par :

$$ 0_n = (0,0,...,0) $$

est appelé élément nul de $A^n$.

Lorsqu’on ne risque pas de confondre l’élément nul de $A^n$ avec
celui de $A$, on peut le noter plus simplement :

$$ 0 = (0,0,...,0) $$

* Ordre partiel

Soit l'ensemble $A^n \in \mathcal{D}$ et $x,y \in A^n$. On a :

#+BEGIN_CENTER
\(
x = (x_1,x_2,...,x_n) \)

\(
y = (y_1,y_2,...,y_n)
\)
#+END_CENTER

On dit que $x \le y$ si et seulement si $x_i \le y_i$ pour tout $i \in \{1,2,...,n\}$. On le note aussi $y \ge x$.

On dit que $x \strictinferieur y$ si et seulement si $x_i \strictinferieur y_i$ pour tout $i \in \{1,2,...,n\}$. On le note aussi $y \strictsuperieur x$.


* Opérations internes

Soit l'ensemble $A^n \in \mathcal{D}$ et $x,y \in A^n$. On a :

$$ x = (x_1,x_2,...,x_n) $$

$$ y = (y_1,y_2,...,y_n) $$

pour certains $x_i,y_i \in A$.

Les opérations sur $A^n$ sont définies par la même opération
appliquée aux composantes. L'addition s'écrit donc :

$$ x + y = (x_1 + y_1 , x_2 + y_2 , ... , x_n + y_n) $$

tandis que la soustraction est donnée par :

$$ x - y = (x_1 - y_1 , x_2 - y_2 , ... , x_n - y_n) $$

** Neutre

L’élément nul de $A^n$ est le neutre pour cette addition.

* Multiplication mixte

La multiplication mixte $\cdot : A \times A^n \to A^n$ est définie par :

$$\alpha \cdot x = (\alpha \cdot x_1 , \alpha \cdot x_2 , ... , \alpha \cdot x_n)$$

pour tout $\alpha \in A$.


** Notations

On note bien entendu :

$$x \cdot \alpha = \alpha \cdot x$$

Choisissant un $\beta \in A$, on pose également :

$$\alpha \cdot \beta \cdot x = (\alpha \cdot \beta) \cdot x$$

Enfin, le signe de multiplication est souvent omis :

$$\alpha \ x = \alpha \cdot x$$


* Lien avec les fonctions

On voit clairement que ces relations et opérations sont équivalentes aux mêmes relations et opérations définies sur les fonctions :

$$\{1,2,...,n\} \mapsto \{f(1),f(2),...,f(n)\} \equiv (f_1,f_2,...,f_n)$$

associées.


* Puissance

Soit $x,y \in A^n$ avec :

$$ x = (x_1,...x_n) $$

$$ y = (y_1,...,y_n) $$

La puissance s'écrit :

$$y^x = y_1^{x_1} \cdot y_2^{x_2} \cdot \ldots \cdot y_n^{x_n}$$

* Factorielle

Soit $m = (m_1,m_2,...,m_n) \in \setN^n$. On définit :

$$m ! = m_1 ! \cdot m_2 ! \cdot ... \cdot m_n !$$
