
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Distributions
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:distribu}

* Dépendances

  - Chapitre \ref{chap:relation} : Les fonctions
  - Chapitre \ref{chap:lineaire} : Les fonctions linéaires

* Formes et fonctions

On peut toujours associer une forme linéaire $\varphi$ à une fonction intégrable quelconque $\hat{\varphi}$ en définissant :

$$\forme{\varphi}{u} = \int_A u(x) \cdot \hat{\varphi}(x) \ dx$$

Inversément, on ne pourra pas toujours trouver une fonction $\hat{\varphi}$ correspondant à une forme linéaire $\varphi$ donnée. On définira malgré tout l'intégrale généralisée en notant :

$$\int_A u(x)  \cdot \varphi(x) \ dx = \forme{\varphi}{u}$$

où il ne faut pas perdre de vue que $\varphi$ n'est pas nécessairement une fonction.


* Formes et mesures

Soit $u : A \mapsto \setR$. A toute mesure $\mu$, on peut associer une forme linéaire $\hat{\mu}$ par :

$$\forme{ \hat{\mu} }{u} = \int_A u(x) \ d\mu(x)$$

Inversément, à toute forme linéaire $\hat{\mu}$, on peut associer une fonction
$\mu : \sousens(\setR) \mapsto \setR$ par :

$$\mu(A) = \forme{ \hat{\mu} }{\indicatrice_A}$$

Toutefois, rien ne garantit que la fonction $\mu$ ainsi définie est une mesure. En particulier, rien ne garantit qu'elle soit positive.


* Fonction et forme bilinéaire

A toute fonction $\hat{K} : A \times B \mapsto F$, on peut associer une forme bilinéaire $K$ par :

$$\biforme{u}{K}{v} = \int_{A \times B} u(x) \cdot K(x,y) \cdot v(y) \ d\mu(x) \ d\nu(y)$$

pour toutes fonctions $u,v : A \mapsto B$. Inversément, à toute forme bilinéaire $K$, on peut associer une intégrale généralisée en notant :

$$\int_{A \times B} u(x) \cdot K(x,y) \cdot v(y) \ d\mu(x) \ d\nu(y) = \biforme{u}{K}{v}$$


* Définition

Nous nous intéressons ici au cas où l'espace vectoriel $E$ est un ensemble de fonctions intégrables : $E = \mathcal{F} \subseteq \lebesgue^2(\setR,\setR)$. Les limites à l'infini doivent alors forcément s'annuler

$$\lim_{x \to +\infty} u(x) = \lim_{x \to -\infty} u(x) = 0$$

pour tout $u \in \mathcal{F}$.


* Delta de Dirac

La distribution $\dirac \in F^\dual$ de Dirac est définie par :

$$\forme{\dirac}{u} = u(0)$$

pour tout $u \in F$. Elle correspond bien sûr à l'intégrale :

$$\int_\setR \dirac(x) \cdot u(x) \ dx = u(0)$$

La notation $\dirac(x)$ ne doit pas nous faire oublier qu’il ne s’agit
pas d’une fonction de $x$, mais d’une forme linéaire qui prend en
réalité une fonction $u$ en argument.

On remarque que :

$$\int_{A^2} \dirac(\xi - x) \cdot K(\xi,\eta) \cdot \dirac(\eta - y) \ d\mu(\xi) \ d\nu(\eta) = K(x,y)$$

* Dérivée

En intégrant par parties, on a :

$$ \int_{\setR} \OD{u}{x}(x) \cdot v(x) \ dx =
\lim_{a \to +\infty} \left[ u(a) \cdot v(a) - u(-a) \cdot v(-a) \right] - \int_{\setR} u(x) \cdot \OD{v}{x}(x) \ dx $$

mais comme les limites à l'infini s'annulent, cette expression se réduit à :

$$\int_{\setR} \OD{u}{x}(x) \cdot v(x) \ dx = - \int_{\setR} u(x) \cdot \OD{v}{x}(x) \ dx$$

Par extension, on définit la dérivée $\OD{u}{x}$ d'une distribution $u$ par :

$$\forme{\OD{u}{x}}{v} = - \forme{u}{\OD{v}{x}}$$

pour tout $v\in F$.

** Échelon

Comme application, considérons la fonction échelon $e_+$ :

$$ e_+(x) = \indicatrice_{[0,+\infty)} =
\begin{cases}
1 & \mbox{si  } t \ge 0 \\
0 & \mbox{si  } t < 0
\end{cases} $$

Pour tout $v\in F$, on a :

\begin{align}
\forme{\OD{e_+}{x}}{v} &= - \forme{e_+}{\OD{v}{x}} \\
&= - \int_0^{+\infty} \OD{v}{x}(x) dx
\end{align}

Appliquons à présent le théorème fondamental. Il vient :

$$\forme{\OD{e_+}{x}}{v} = - \left[\lim_{x \to +\infty} v(x) - v(0)\right] = v(0)$$

On en déduit que :

$$\OD{e_+}{x} = \dirac$$

au sens des distributions.


* Dilatation

Soit $d_a$ l'opérateur de dilatation :

$$d_a(u)(x) = u(a \cdot x)$$

où $a > 0$ est un réel strictement positif.

Le changement de variable $\xi = a \cdot x$ nous donne $d\xi = a \ dx$ et donc :

$$\int_{\setR} \hat{u}(a \ x) \ v(x) \ dx = \unsur{a} \int_{\setR} \hat{u}(\xi) \ v\left( \xi/a \right) \ d\xi$$

On définit donc l'extension de cet opérateur aux distributions par :

$$\forme{d_a(u)}{v} = \unsur{a} \forme{u}{d_{1/a}(v)}$$


* Réflexion

L'opérateur de réflexion $r$ se définit par :

$$r(u)(x) = u(-x)$$

Le changement de variable $\xi = -x$ nous donne $d\xi = -dx$ et donc :

\begin{align}
\int_{\setR} \hat{u}(-x) \ v(x) \ dx &= \lim_{a \to +\infty}\int_{-a}^a \hat{u}(-x) \ v(x) \ dx \\
&= \lim_{a \to +\infty} - \int_a^{-a} \hat{u}(\xi) \ v(-\xi) \ d\xi \\
&= \lim_{a \to +\infty} \int^{-a}_a \hat{u}(\xi) \ v(-\xi) \ d\xi
\end{align}

On définit donc l'extension de cet opérateur aux distributions par :

$$\forme{r(u)}{v} = \forme{u}{r(v)}$$

* Translation

L'opérateur de translation $t_a$ est défini par :

$$t_a(u)(x) = u(x - a)$$

Le changement de variable $\xi = x - a$ nous donne $d\xi = dx$ et donc :

$$\int_{\setR} \hat{u}(x-a) v(x) dx = \int_{\setR} \hat{u}(\xi) v(\xi+a) d\xi$$

On définit donc les extensions de cet opérateur aux distributions par :

$$\forme{t_a(u)}{v} = \forme{u}{t_{-a}(v)}$$


* Convolution

Les intégrales unidimensionnelles permettent de définir l'opérateur de convolution
$\convolution$. Soit deux fonctions $u, v : \setR \mapsto \setR$, leur convolution
est une fonction $u \convolution v : \setR \mapsto \setR$ définie par :

$$(u \convolution v)(t) = \int_{-\infty}^{+\infty} u(t-s) \ v(s) \ ds$$

pour tout $t \in \setR$.


** Dirac

En utilisant les résultats ci-dessus, on arrive facilement à :

$$\int_{\setR} u(x) \ \dirac(x-a) \ dx = u(a)$$

Comme :

$$\int_{\setR} u(x) \ \dirac(-x) \ dx = \int_{\setR} u(-x) \ \dirac(x) \ dx = u(0)$$

on en déduit que $\dirac(-x) = \dirac(x)$ et :

$$\int_{\setR} \dirac(x-y) \ u(y)  \ dy = u(x)$$

c'est-à-dire :

$$\dirac \convolution u = u$$

La distribution de Dirac est neutre pour le produit de convolution.
On peut montrer que ce neutre est unique.


* Corrélation

Les intégrales unidimensionnelles permettent de définir l'opérateur de corrélation
$\correlation$. Soit deux fonctions $u, v : \setR \mapsto \setR$, leur corrélation
est une fonction $u \correlation v : \setR \mapsto \setR$ définie par :

$$(u \correlation v)(t) = \int_{-\infty}^{+\infty} u(s+t) \ v(s) \ ds$$

pour tout $t \in \setR$.


