
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Ensembles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:ensembles}

* Dépendances

Vous êtes à la racine.

* Définition explicite

Les ensembles sont des regroupements d'objets appelés éléments.

Il existe deux méthodes permettant de définir un ensemble. Lorsqu'il
n'existe qu'un nombre fini d'éléments distincts, on peut les énumérer :

$$A = \{ a, b, c, ..., z \}$$

On dit alors que $x$ appartient à $A$, et on le note :

$$x \in A$$

si $x$ fait partie de la liste $a, b, c, ..., z$. Dans le cas contraire,
$x$ n'appartient pas à $A$, ce que l'on note par :

$$x \notin A$$


* Définition implicite

On peut aussi définir un ensemble en demandant que ses éléments respectent
certaines conditions. On dit alors que $x \in A$ si $x$ vérifie toutes
les conditions nécessaires pour appartenir à l'ensemble $A$ ou que
$x \notin A$ si au moins une des conditions n'est pas remplie. Le schéma
de ce type de définition s'écrit :

$$A = \{ x : \text{ une ou plusieurs conditions sur } x \}$$

Dans ce cas, le nombre d'éléments de l'ensemble peut être fini ou infini.


** Variante

On ajoute souvent une condition sur les éléments de l'ensemble :

$$A = \{ x \in \Omega : \text{ conditions sur } x \}$$

Dans ce cas, tout candidat $x$ doit en plus appartenir à l'ensemble $\Omega$
s'il veut appartenir à l'ensemble $A$. Cette définition est donc
équivalente à :

$$A = \{ x : x \in \Omega, \text{ conditions sur } x \}$$


* Notations

Le symbole $\exists$ signifie « il existe » et le symbole $\forall$ signifie « pour tout »


* Ensemble vide

L'ensemble vide $\emptyset = \{\}$ est un cas particulier ne contenant
aucun élément :

$$x \notin \emptyset$$

quelle que soit la nature de $x$.


* Naturels

L'ensemble des nombres naturels se construit à partir d'un élément « racine »
$0$, auquel on ajoute indéfiniment des successeurs. Le successeur de $0$
est noté $0^+$ ou $1$. On dit aussi que $0$ est le prédécesseur de $1$ et
on le note $1^- = 0$. Arrivé à l'élément $i$, on ajoute
le successeur de $i$, noté :

$$j = i^+$$

On dit aussi que $i$ est le prédécesseur de $j$ et on le note :

$$i = j^-$$

On a donc :

$$i^{+-} = j^- = i$$

et :

$$j^{-+} = i^+ = j$$

L'ensemble des objets ainsi crée est appelé l'ensemble des nombres naturels
et noté $\setN$. En l'exprimant au moyen des symboles usuels, on a dans
l'ordre de succession :

$$\setN = \{ 0,1,2,3,4,5,6,7,8,9,10,... \}$$


** Notation

On note aussi :

$$i + 1 = i^+$$

et :

$$i - 1 = i^-$$


** Element racine

L'élément $0$ est le seul naturel à de pas posséder de prédécesseur.
On l'appelle pour cette raison l'élément racine de $\setN$.

On dit aussi qu'un élément $n$ est nul pour signifier que $n = 0$.


** Ensemble discret ou dénombrable

Tout ensemble de la forme :

$$A = \{ a_k : k \in \setN \}$$

est dit discret ou dénombrable.


* Inclusion

On dit que $A$ est inclus dans $B$ et on note :

$$A \subseteq B$$

si tous les éléments de $A$ appartiennent aussi à $B$ :

$$x \in A \ \Rightarrow \ x \in B$$

On dit alors que $A$ est un sous-ensemble, ou une partie de $B$.


** Stricte

Il y a inclusion stricte :

$$A \subset B$$

lorsque $A \subseteq B $ et que les deux ensembles ne sont pas égaux,
ce que l'on note par :

$$A \ne B$$


* Egalité

Deux ensembles $A$ et $B$ sont dit égaux et on le note :

$$A = B$$

si tout élément de $A$ appartient aussi à $B$ et si tout élément de $B$
appartient aussi à $A$ :

$$x \in A \ \Leftrightarrow \ x \in B$$

ce qui revient à dire que l'on a inclusion mutuelle de $A$ et $B$ :

$$A = B \ \Leftrightarrow \ A \subseteq B \text{ et } B \subseteq A$$


** Remarque

Dans le cadre des ensembles, on ne se soucie pas de l'ordre :

$$\{a,b\} = \{b,a\}$$

ni du nombre d'apparitions d'un élément :

$$\{a,a,b\} = \{a,b\}$$


* Union

L'union de deux ensembles $A \cup B$ est l'ensemble contenant les éléments
de $A$ et les éléments de $B$. Un élément quelconque de $A \cup B$ peut
donc appartenir à $A$, à $B$ ou aux deux ensembles simultanément :

$$A \cup B = \{ x : x \in A \text{ ou/et } x \in B \}$$


** Jargon

Le « ou » mathématique est non exclusif. La proposition $a$ ou $b$ signifie
que soit $a$, soit $b$, soit ($a$ et $b$) est vérifié.


* Intersection

L'intersection $A \cap B$ est l'ensemble des éléments qui appartiennent à
la fois à $A$ et à $B$ :

$$A \cap B = \{ x : x \in A \text{ et } x \in B \}$$


** Nomenclature

Lorsque l'intersection de deux ensembles est vide,
on dit qu'ils sont disjoints.


* Association

Soit les ensembles $A,B,C$. On définit :

$$A \cup B \cup C = A \cup (B \cup C)$$

Comme les éléments de $A \cup B \cup C$ sont les éléments qui
appartiennent à au moins un des ensembles $A,B,C$, on voit que :

$$A \cup B \cup C = (A \cup B) \cup C$$

On en conclut que :

$$A \cup B \cup C = A \cup (B \cup C) = (A \cup B) \cup C$$

On définit aussi :

$$A \cap B \cap C = A \cap (B \cap C)$$

Comme les éléments de $A \cap B \cap C$ sont les éléments qui
appartiennent simultanément à $A,B,C$, on voit que :

$$A \cap B \cap C = (A \cap B) \cap C$$

On en conclut que :

$$A \cap B \cap C = A \cap (B \cap C) = (A \cap B) \cap C$$


* Commutation

On a clairement :

#+BEGIN_CENTER
\(
A \cup B = B \cup A \)

\(
A \cap B = B \cap A
\)
#+END_CENTER


* Distribution

Soit les ensembles $A,B,C$. Lorsque $x$ appartient à la fois
à $A$ et à au moins un des deux ensembles $B$ et $C$, on sait que $x$
appartient à $A$ et $B$ ou qu'il appartient à $A$ et $C$, et inversément.
On a donc :

$$A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$$

On dit que l'intersection se distribue sur l'union. On a également la relation :

$$A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$$

On dit que l'union se distribue sur l'intersection.


* Différence

La différence $A \setminus B$ est l'ensemble des éléments qui appartiennent
à $A$ mais pas à $B$ :

$$A \setminus B = \{ x : x \in A \text{ et } x \notin B \}$$


* Décomposition

Soit les ensembles $A,B$. Les éléments de $A$ sont de deux types :

  - ceux qui appartiennent également à $B$
  - ceux qui n'appartiennent pas à $B$

On en conclut que :

$$A = (A \cap B) \cup (A \setminus B)$$

On voit que les deux sous-ensembles de $A$ sont disjoints :

$$(A \cap B) \cap (A \setminus B) = \emptyset$$


** Union

Les éléments de $A \cup B$ sont de deux types :

  - ceux qui appartiennent seulement à $A$
  - ceux qui appartiennent à $B$

On en conclut que :

$$A \cup B = (A \setminus B) \cup B$$

On voit que les deux sous-ensembles de $A \cup B$ sont disjoints :

$$(A \setminus B) \cap B = \emptyset$$


* Complémentaire

Si $A \subseteq \Omega$, on dit que $C = \Omega \setminus A$ est le
complémentaire de $A$ dans $\Omega$, ou simplement que $C$ est le
complémentaire de $A$ lorsque l'ensemble $\Omega$ est évident d'après
le contexte.


** Complémentaire du complémentaire

Soit $A \subseteq \Omega$. Un élément de $\Omega$ qui n'appartient pas à $\Omega \setminus A$
appartient à $A$, et réciproquement. On a donc :

$$\Omega \setminus (\Omega \setminus A) = A$$


** Réciprocité

Soit $A \subseteq \Omega$ et son complémentaire :

$$B = \Omega \setminus A$$

En prenant le complémentaire de cette équation, on obtient :

$$\Omega \setminus B = \Omega \setminus (\Omega \setminus A) = A$$

Soit à présent $B \subseteq \Omega$ et son complémentaire :

$$A = \Omega \setminus B$$

En prenant le complémentaire de cette équation, on obtient :

$$\Omega \setminus A = \Omega \setminus (\Omega \setminus B) = B$$

On en conclut l'équivalence :

$$A = \Omega \setminus B \ \Leftrightarrow \ B = \Omega \setminus A$$


** Complémentaire d'une union

Soit un ensemble $\Omega$ et les sous-ensembles $A,B \subseteq \Omega$.
Un élément de $\Omega$ qui n'appartient pas à $A \cup B$ n'appartient ni
à $A$ ni à $B$. Il appartient donc à $\Omega \setminus A$ et à
$\Omega \setminus B$. Inversément, un élément qui appartient à
$\Omega \setminus A$ et à $\Omega \setminus B$ n'appartient ni à $A$ ni
à $B$. On a donc :

$$\Omega \setminus (A \cup B) = (\Omega \setminus A) \cap (\Omega \setminus B)$$

Le complémentaire d'une union est l'intersection des complémentaires.


** Complémentaire d'une intersection

Soit $A,B \in \Omega$. Posons :

#+BEGIN_CENTER
\(
C = \Omega \setminus A \subseteq \Omega \)

\(
D = \Omega \setminus B \subseteq \Omega
\)
#+END_CENTER

L'expression du complémentaire de $A \cup B$ devient :

$$\Omega \setminus \big[(\Omega \setminus C) \cup (\Omega \setminus D)\big] = C \cap D$$

En prenant le complémentaire des deux membres par rapport à $\Omega$,
on obtient :

$$(\Omega \setminus C) \cup (\Omega \setminus D) = \Omega \setminus (C \cap D)$$

Le complémentaire d'une intersection est l'union des complémentaires.


