
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Équivalence
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:equivalences}

* Dépendances

  - Chapitre \ref{chap:relations} : Les relations


* Définition

Une équivalence $\equiv$ sur un ensemble $A$ est une relation permettant de regrouper les éléments ayant une caractéristique similaire. Choisissons $x,y,z \in A$. Tout élément $x$ étant égal à lui-même, il doit bien entendu être équivalent à lui-même. Notre équivalence doit donc respecter la propriété :

$$x \equiv x$$

Par ailleurs, si $x$ est équivalent à $y$, l'inverse doit aussi être vrai :

$$x \equiv y \quad \Rightarrow \quad y \equiv x$$

Il est également clair que si $x$ est équivalent $y$ et que $y$ est équivalent à $z$, notre $x$ doit être équivalent à $z$. Donc :

$$x \equiv y, \quad y \equiv z \quad \Rightarrow \quad x \equiv z$$


** Relation

On peut associer une relation $R$ à toute équivalence en posant :

$$R = \{ (x,y) \in A^2 : x \equiv y \}$$

On a alors $x \equiv y$ si et seulement si $(x,y) \in R$.


** Multiple

La notation $x \equiv y \equiv z$ signifie que $x \equiv y$ et que $y \equiv z$.


* Classe d'équivalence

Soit $x \in A$. La classe d'équivalence associée à $x$ est l'ensemble des éléments de $A$ qui lui sont équivalents :

$$\mathcal{E}(x) = \{ y \in A : y \equiv x \}$$


* Ensemble quotient

Soit la relation $R \subseteq A^2$ associée à l'équivalence $\equiv$ définie sur $A$. L'ensemble quotient de $A$ par $R$ est la collection des classes d'équivalence :

$$A / R = \{ \mathcal{E}(x) \in \sousens(A) : x \in A \}$$


** Intersection

Soit $x,y \in A$.

  - Supposons que $x$ n'est pas équivalent à $y$ et choisissons un $z$ dans l'intersection :

$$z \in \mathcal{E}(x) \cap \mathcal{E}(y)$$

On doit donc avoir $x \equiv z$ et $z \equiv y$, alors que $x$ n'est pas équivalent à $y$, ce qui contredit la définition des équivalences. Par conséquent, un tel $z$ ne peut pas exister et l'intersection est vide :

$$\mathcal{E}(x) \cap \mathcal{E}(y) = \emptyset$$

  - A présent, supposons que $x$ est équivalent à $y$ et choisissons un $z \in \mathcal{E}(x)$. On a donc $z \equiv x$ et $x \equiv y$. On en déduit que $z \equiv y$, d'où $z \in \mathcal{E}(y)$ et $\mathcal{E}(x) \subseteq \mathcal{E}(y)$. Symétriquement, si $w \in \mathcal{E}(y)$, on a $w \equiv y$ et $y \equiv x$, d'où $w \in \mathcal{E}(x)$ et $\mathcal{E}(y) \subseteq \mathcal{E}(x)$. On a donc :

$$\mathcal{E}(x) = \mathcal{E}(y)$$



** Union

Quel que soit $x \in A$, tous les éléments de $\mathcal{E}(x)$ sont dans $A$ par définition. L'union :

$$E = \bigcup_{x \in A} \mathcal{E}(x)$$

est donc également inclue dans $A$. D'un autre coté, tout $x \in A$ étant équivalent à lui-même, chaque $\mathcal{E}(x)$ contient au moins $x$. On en conclut que $A$ est inclus dans $E$. La double inclusion nous montre que :

$$A = \bigcup_{x \in A} \mathcal{E}(x)$$


** Partition

On déduit de ce qui précède que la collection des classes d'équivalences :

$$\mathcal{P} = A / R$$

forme une partition de $A$. Cette constation explique la terminologie de quotient, liée à celle de division et de partition.


