
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Extréma essentiels
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:essextr}

* Dépendances

  - Chapitre \ref{chap:mesure} : Les mesures


* Bornes

Soit la fonction mesurable $f : A \mapsto \setR$.


** Supérieure

On dit que $f$ est {\em essentiellement} inférieure au réel $\sigma \in \setR$, et on le note :

$$f \essinferieur \sigma$$

si on peut trouver un sous-ensemble essentiel $S$ de $A$ tel que $f(x) \le \sigma$ en tout point $x \in S$. On a donc :

$$\mu(\{ x \in A : f(x) \strictsuperieur \sigma \}) = 0$$

On dit aussi que $f$ est essentiellement majorée par $\sigma$.


** Inférieure

On dit que $f$ est {\em essentiellement} supérieure au réel $\lambda \in \setR$, et on le note :

$$f \esssuperieur \lambda$$

si on peut trouver un sous-ensemble essentiel $S$ de $A$ tel que $f(x) \ge \lambda$ en tout point $x \in S$. On a donc :

$$\mu(\{ x \in A : f(x) \strictinferieur \lambda \}) = 0$$

On dit aussi que $f$ est essentiellement minorée par $\lambda$.


* Extrema essentiels

Soit une fonction mesurable $f : A \mapsto \setR$. Pour tout $\sigma \in \setR$, notons :

$$\Psi(\sigma) = \{ x \in A : f(x) \strictsuperieur \sigma \}$$

Comme on ne se soucie pas des ensembles de mesure nulle, on peut choisir (si elle existe) une borne supérieure $\sigma \in \setR$ telle que $f \essinferieur \sigma$, ce qui revient à imposer que $\mu(\Psi(\sigma)) = 0$. Notons :

$$\Theta = \{ \sigma \in \setR : f \essinferieur \sigma \} = \{ \sigma \in \setR : \mu(\Psi(\sigma)) = 0 \}$$

La finalité des bornes étant d'encadrer au plus près un ensemble, nous considérons l'infimum (s'il existe) des réels $\sigma$ possédant cette propriété, et nous l'appelons supremum essentiel :

$$\supessentiel_{x \in A} f(x) = \inf \Theta$$

Symétriquement, on note :

$$\Gamma(\lambda) = \{ x \in A : f(x) \strictinferieur \lambda \}$$

pour tout $\lambda \in \setR$ et :

$$\Lambda = \{ \lambda \in \setR : f \esssuperieur \lambda \} = \{ \lambda \in \setR : \mu(\Gamma(\lambda)) = 0 \}$$

Si le supremum de $\Lambda$ existe, on définit alors l'infimum essentiel par :

$$\infessentiel_{x \in A} f(x) = \sup \Lambda$$

Nous disposons donc des bornes :

#+BEGIN_CENTER
\(
\supessentiel_{x \in A} f(x) = \inf \{ \sigma \in \setR : f \essinferieur \sigma \} \\ \)

\(
\infessentiel_{x \in A} f(x) = \sup \{ \lambda \in \setR : f \esssuperieur \lambda \}
\)
#+END_CENTER


** Notation

On note aussi :

#+BEGIN_CENTER
\(
\supessentiel \{f(x) : x \in A\} = \supessentiel_{x \in A} f(x) \)

\(
\infessentiel \{f(x) : x \in A\} = \infessentiel_{x \in A} f(x)
\)
#+END_CENTER

Au besoin, la mesure $\mu$ utilisée est indiquée par :

#+BEGIN_CENTER
\(
\supessentiel_{x \in A}^\mu f(x) \\ \)

\(
\infessentiel_{x \in A}^\mu f(x)
\)
#+END_CENTER


* Existence et estimation


** Supremum essentiel

Supposons que $f$ soit essentiellement inférieure (sur $A$) à un certain $\sigma \in \setR$ et que $f$ soit essentiellement supérieure à un certain $\lambda \in \setR$ sur un ensemble $L \subseteq A$ de mesure strictement positive. On a $\sigma \in \Theta \ne \emptyset$. Pour tout $\alpha \in \setR$ tel que $\alpha \ge \sigma$, on a $\Psi(\alpha) \subseteq \Psi(\sigma)$. Comme $\mu(\Psi(\sigma)) = 0$, l'ensemble $\Psi(\alpha)$ est inclus dans un ensemble de mesure nulle. Il est donc lui-même de mesure nulle et $\alpha \in \Theta$. On en conclut que :

$$[\sigma, +\infty[ \ \subseteq \Theta$$

pour tout $\sigma \in \Theta$. Comme $f$ est essentiellement supérieure à $\lambda$ sur $L$, on peut trouver un ensemble de mesure nulle $Z \subseteq L$ tel que :

$$L \setminus Z = \{ x \in L : f(x) \ge \lambda \}$$

Comme $L \setminus Z$ est un sous-ensemble essentiel de $L$, on a $\mu(L \setminus Z) = \mu(L) \strictsuperieur 0$. Posons :

$$C = \{ x \in A : f(x) \ge \lambda \}$$

Comme $L \subseteq A$, on a $L \setminus Z \subseteq C$ et $\mu(C) \ge \mu(L \setminus Z) \strictsuperieur 0$. Soit $\beta \in \setR$ vérifiant $\beta \strictinferieur \lambda$. La condition $f(x) \ge \lambda$ implique que $f(x) \strictsuperieur \beta$. On en déduit que :

$$C \subseteq \{ x \in A : f(x) \strictsuperieur \beta \} = \Psi(\beta)$$

On a alors $\mu(\Psi(\beta)) \ge \mu(C) \strictsuperieur 0$, ce qui implique que $\beta$ ne peut pas appartenir à $\Theta$. Tous les éléments $\theta \in \Theta$ vérifient donc $\theta \ge \lambda$ et :

$$\Theta \subseteq [\lambda, +\infty[$$

Comme $\lambda \le \Theta$, l'ensemble de réels $\Theta$ est non vide et minoré. Il admet donc un infimum :

$$\supessentiel_{x \in A} f(x) = \inf \Theta$$

On se rappelle que l'inclusion $X \subseteq Y$ implique que $\inf X \ge \inf Y$. Comme $\lambda = \inf [\lambda, +\infty[$ et $\sigma = \inf [\sigma, +\infty[$, les inclusions :

$$[\sigma, +\infty[ \ \subseteq \Theta \subseteq [\lambda, +\infty[$$

nous montrent que :

$$\lambda \le \supessentiel_{x \in A} f(x) \le \sigma$$


** Infimum essentiel

Supposons que $f$ soit essentiellement supérieure (sur $A$) à un certain $\lambda \in \setR$ et que $f$ soit essentiellement inférieure à un certain $\sigma \in \setR$ sur un ensemble $S \subseteq A$ de mesure strictement positive. On a $\lambda \in \Lambda \ne \emptyset$. Pour tout $\alpha \in \setR$ tel que $\alpha \le \lambda$, on a $\Gamma(\alpha) \subseteq \Gamma(\lambda)$. Comme $\mu(\Gamma(\lambda)) = 0$, l'ensemble $\Gamma(\alpha)$ est inclus dans un ensemble de mesure nulle. Il est donc lui-même de mesure nulle et $\alpha \in \Lambda$. On en conclut que :

$$]-\infty, \lambda] \subseteq \Lambda$$

pour tout $\lambda \in \Lambda$. Comme $f$ est essentiellement inférieure à $\sigma$ sur $S$, on peut trouver un ensemble de mesure nulle $Z \subseteq S$ tel que :

$$S \setminus Z = \{ x \in S : f(x) \le \sigma \}$$

Comme $S \setminus Z$ est un sous-ensemble essentiel de $S$, on a $\mu(S \setminus Z) = \mu(S) \strictsuperieur 0$. Posons :

$$C = \{ x \in A : f(x) \le \sigma \}$$

Comme $S \subseteq A$, on a $S \setminus Z \subseteq C$ et $\mu(C) \ge \mu(S \setminus Z) \strictsuperieur 0$. Soit $\beta \in \setR$ vérifiant $\beta \strictsuperieur \sigma$. La condition $f(x) \le \sigma$ implique que $f(x) \strictinferieur \beta$. On en déduit que :

$$C \subseteq \{ x \in A : f(x) \strictinferieur \beta \} = \Gamma(\beta)$$

On a alors $\mu(\Gamma(\beta)) \ge \mu(C) \strictsuperieur 0$, ce qui implique que $\beta$ ne peut pas appartenir à $\Lambda$. Tous les éléments $\gamma \in \Lambda$ vérifient donc $\gamma \le \sigma$ et :

$$\Theta \subseteq \ ]-\infty, \sigma]$$

Comme $\sigma \ge \Lambda$, l'ensemble de réels non vide $\Lambda$ est majoré. Il admet donc un supremum :

$$\infessentiel_{x \in A} f(x) = \sup \Lambda$$

On se rappelle que l'inclusion $X \subseteq Y$ implique que $\sup X \le \sup Y$. Comme $\lambda = \sup \ ]-\infty, \lambda]$ et $\sigma = \sup \ ]-\infty, \sigma]$, les inclusions :

$$]-\infty, \lambda] \ \subseteq \Theta \subseteq \ ]-\infty, \sigma]$$

nous montrent que :

$$\lambda \le \infessentiel_{x \in A} f(x) \le \sigma$$


* Intersection

Supposons que $A$ soit de mesure strictement positive et que $\Theta \cap \Lambda \ne \emptyset$. Pour tout $\alpha \in \setR$, posons :

$$\Xi(\alpha) = \{ x \in A : f(x) = \alpha \}$$

et :

$$\Upsilon(\alpha) = \{ x \in A : f(x) \ne \alpha \}$$

Il est clair que :

$$A = \Xi(\alpha) \cup \Upsilon(\alpha)$$

Comme imposer la différence revient à imposer soit la supériorité soit l'infériorité stricte, on a :

$$\Upsilon(\alpha) = \Psi(\alpha) \cup \Gamma(\alpha)$$

Soit à présent $\alpha \in \Theta \cap \Lambda$. Comme $\mu(\Psi(\alpha)) = \mu(\Gamma(\alpha)) = 0$, leur union est également de mesure nulle :

$$\mu(\Upsilon(\alpha)) = 0$$

Si l'intersection $\Theta \cap \Lambda$ n'est pas vide, la fonction $f$ est donc essentiellement constante sur $A$ et $\Xi(\alpha) = A \setminus \Upsilon(\alpha)$ est un sous-ensemble essentiel de $A$. On a donc $\mu(\Xi(\alpha)) = \mu(A) \strictsuperieur 0$. Soit à présent $\beta \in \setR$ et supposons que $\beta \ne \alpha$. Si $f(x) = \beta$, on a forcément $f(x) \ne \alpha$, donc :

$$\Xi(\beta) = \{ x \in A : f(x) = \beta \} \subseteq \{ x \in A : f(x) \ne \alpha \}$$

L'ensemble $\Xi(\beta)$ étant inclus dans un ensemble de mesure nulle, on doit avoir $\mu(\Xi(\beta)) = 0$. Comme $\mu(\Xi(\alpha)) \strictsuperieur 0$ pour tout $\alpha \in \Theta \cap \Lambda$, $\beta$ ne peut pas appartenir à $\Theta \cap \Lambda$. On en conclut que l'intersection vérifie soit :

$$\Theta \cap \Lambda = \emptyset$$

soit :

$$\Theta \cap \Lambda = \{ \alpha \}$$

pour un certain $\alpha \in \setR$.


** Extrema

Supposons que $f$ soit essentiellement inférieure à $\sigma$ et essentiellement supérieure à $\lambda$ sur $A$ qui est de mesure strictement positive. On en déduit que les supremum et infimum essentiels existent :

#+BEGIN_CENTER
\(
S = \supessentiel \{ f(x) : x \in A \} \)

\(
I = \infessentiel \{ f(x) : x \in A \}
\)
#+END_CENTER

et que $\lambda \le \{ S,I \} \le \sigma$. Supposons que $S \strictinferieur I$ et posons $\delta = I - S \strictsuperieur 0$. Soit le réel strictement positif $\epsilon = \delta / 4$. Comme l'infimum est dans l'adhérence, on peut trouver un $\alpha \in \Theta$ tel que $\abs{\alpha - S} \le \epsilon$, d'où $\alpha \le S + \epsilon$. On a alors :

$$[\alpha, +\infty[ \ \subseteq \Theta$$

Comme le supremum est dans l'adhérence, on peut trouver un $\beta \in \Lambda$ tel que $\abs{I - \beta} \le \epsilon$, d'où $\beta \ge I - \epsilon$. On a alors :

$$]-\infty, \beta] \subseteq \Lambda$$

On voit que :

\begin{align}
S + \epsilon &= S + \frac{\delta}{4} \)

\(
I - \epsilon &= S + \delta - \frac{\delta}{4} = S  + \frac{3 \delta}{4}
\end{align}

On a donc :

$$\alpha \le S + \epsilon \strictinferieur I - \epsilon \le \beta$$

et $\alpha \strictinferieur \beta$. On a aussi :

$$[\alpha,\beta] = \ ]-\infty, \beta] \cap [\alpha, +\infty[ \ \subseteq \Theta \cap \Lambda$$

Donc $\alpha,\beta \in \Theta \cap \Lambda$ avec $\alpha \ne \beta$ ce qui impossible. Notre hypothèse est donc fausse et $I \le S$, c'est-à-dire :

$$\infessentiel_{x \in A} f(x) \le \supessentiel_{x \in A} f(x)$$


* Ordre

Soit les fonctions $f,g : A \mapsto \setR$ telles que $f \essinferieur g$.


** Supremum essentiel

On a bien entendu :

$$f \essinferieur g \essinferieur \supessentiel_{x \in A} g(x)$$

On en déduit que :

$$\supessentiel_{x \in A} f(x) \le \supessentiel_{x \in A} g(x)$$


** Infimum essentiel

On a bien entendu :

$$\infessentiel_{x \in A} f(x) \essinferieur f \essinferieur g$$

On en déduit que :

$$\infessentiel_{x \in A} f(x) \le \infessentiel_{x \in A} g(x)$$


* Addition

Soit les fonctions $f,g : A \mapsto \setR$.


** Supremum essentiel

On sait que :

#+BEGIN_CENTER
\(
f \essinferieur \sigma = \supessentiel \{ f(x) : x \in A \} \)

\(
g \essinferieur \tau = \supessentiel \{ g(x) : x \in A \}
\)
#+END_CENTER

On a donc :

$$f + g \essinferieur \sigma + \tau$$

On en conclut que :

$$\supessentiel_{x \in A} [f(x) + g(x)] \le \supessentiel_{x \in A} f(x) + \supessentiel_{x \in A} g(x)$$


** Infimum essentiel

On sait que :

#+BEGIN_CENTER
\(
f \esssuperieur \lambda = \infessentiel \{ f(x) : x \in A \} \)

\(
g \esssuperieur \gamma = \infessentiel \{ g(x) : x \in A \}
\)
#+END_CENTER

On a donc :

$$f + g \esssuperieur \lambda + \gamma$$

On en conclut que :

$$\infessentiel_{x \in A} [f(x) + g(x)] \ge \infessentiel_{x \in A} f(x) + \infessentiel_{x \in A} g(x)$$


