
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Extréma réels
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:extremaReels}

* Dépendances

  - Chapitre \ref{chap:reel} : Les nombres réels
  - Chapitre \ref{chap:interval} : Les intervalles

* Existence

Soit un sous-ensemble $A \subseteq \setR$ avec $A \ne \emptyset$. Pour tout réel $x \in A$, on note $Q(x)$ le sous-ensemble de rationnels associé.


  - Supposons que $A$ soit majoré ($\major A \ne \emptyset$). Choisissons $\mu \in \major A$ et considérons le sous-ensemble de rationnels $Q(\mu)$ associé à $\mu$. Comme $\mu \ge A$ et comme l'ordre $\le$ est dérivé de l'ordre inclusif sur les sous-ensembles de rationnels associés, on a $Q(x) \subseteq Q(\mu)$ pour tout $x \in A$. On en conclut que l'union $S$ des $Q(x)$ est inclue dans $Q(\mu)$ :

$$S = \bigcup_{x \in A} Q(x) \subseteq Q(\mu)$$

Comme $Q(\mu)$ est majoré, on peut trouver un rationnel $\sigma$ tel que :

$$S \subseteq Q(\mu) \le \sigma$$

Donc $S \le \sigma$, ce qui prouve que $S$ est majoré. D'un autre coté, comme les $Q(x)$ ne sont pas vides, il est clair que leur union $S$ n'est pas vide.

Soit $\alpha \in S$ et le rationnel $\beta \in \setQ$ vérifiant $\beta \strictinferieur \alpha$. On peut trouver un $x \in A$ tel que $\alpha \in Q(x)$. Par définition des sous-ensembles de rationnels associés aux réels, on a $\beta \in Q(x)$, donc $\beta$ appartient à l'union $S$. Enfin, si $S$ admettait un maximum $M$, on on pourrait trouver un $x \in A$ tel que $M \in Q(x)$. On aurait aussi $Q(x) \subseteq S \le M$, et donc $Q(x) \le M$, ce qui contredit la définition des réels. On en conclut que l'ensemble $S$ correspond à un réel $s$. Mais on sait que le supremum inclusif est égal à l'union :

$$S = \sup_\subseteq \{ Q(x) \in \sousens(\setQ) : x \in A \} $$

L'ordre $\le$ des réels étant dérivé de $\subseteq$, on en conclut que le supremum de $A$ existe et que :

$$s = \sup A$$

Nous avonc donc prouvé que tout sous-ensemble $A$ non vide majoré de $\setR$ admet un supremum.

  - Supposons que $A$ soit minoré ($\minor A \ne \emptyset$). Choisissons $\lambda \in \minor A$ et posons :

$$-A = \{ -x \in \setR : x \in A \}$$

Comme $\lambda \le x$ pour tout $x \in A$, on a $-\lambda \ge -x$ et $-\lambda \in \major(-A) \ne \emptyset$. L'ensemble non vide $-A$ est donc majoré et admet un supremum $S = \sup(-A)$. On a $S \ge -x$ pour tout $x \in A$, donc $I = -S \le x$ et $I \in \minor A$. Choisissons $\alpha \in \minor A$. On a $\alpha \le x$ pour tout $x \in A$, d'où $-\alpha \ge -x$ et $-\alpha \in \major(-A)$. On en déduit que $-A \le S \le -\alpha$, c'est-à-dire $\alpha \le I \le A$. Le
réel $I = -S$ est donc l'infimum de $A$ :

$$\inf A = - \sup(-A)$$

Nous avonc donc prouvé que tout sous-ensemble $A$ non vide minoré de $\setR$ admet un infimum.

* Adhérence et distance

Soit $A \subseteq \setR$ et $r \in \setR$. Soit l'ensemble :

$$D = \{ \distance(r,x) : x \in A \}$$

- Supposons que $r \in \adh A$. On a alors :

$$\distance(r,A) = \inf D = 0$$

Choisissons un réel $\delta \strictsuperieur 0$. Si on avait
$\distance(x,r) \strictsuperieur \delta$ pour tout $x \in A$, on aurait $0
\strictinferieur \delta \le D$, ce qui contredit l'hypothèse d'infimum
nul. Donc, pour tout $\delta \strictsuperieur 0$, on peut trouver un $x
\in A$ tel que $\distance(x,r) \le \delta$.

- Réciproquement, supposons que pour tout réel $\delta \strictsuperieur
0$, on puisse trouver un $x \in A$ tel que $d = \distance(x,r) \le
\delta$. Dans ce cas, on a $\delta \le d \in D$. On en conclut que
$\delta \notin \minor D$. Par contre, si $\delta \le 0$, on a $\delta \le
0 \le D$ par positivité de la distance. On en conclut que $\minor D =
\intervallesemiouvertgauche{-\infty}{0}$, d'où :

$$\distance(r,A) = \inf D = \max \minor D = \max \intervallesemiouvertgauche{-\infty}{0} = 0$$

et $r \in \adh A$.

* Eloignement


  - Supposons à présent que le supremum $S = \sup A$ existe et que l'on puisse trouver un $\delta \strictsuperieur 0$ tel que :

$$\distance(S,x) = \abs{S - x} = S - x \ge \delta$$

pour tout $x \in A$. Soit alors :

$$y = S - \frac{\delta}{2}$$

On voit que $S \strictsuperieur y$ et que :

$$y - x = (y - S) + (S - x) \ge - \frac{\delta}{2} + \delta = \frac{\delta}{2} \strictsuperieur 0$$

pour tout $x \in A$, c'est-à-dire $y \ge A$. On a donc $S \strictsuperieur y \ge A$, ce qui contredit la définition du supremum. Pour tout $\delta \strictsuperieur 0$, on peut donc trouver un $x \in A$ tel que $\distance(S,x) \le \delta$. On en conclut que $\distance(S,A) = 0$, c'est-à-dire :

$$\sup A \in \adh A$$

  - Soit l'ensemble $A$ admettant un infimum $I = \inf A$. Supposons que l'on puisse trouver un $\delta \strictsuperieur 0$ tel que :

$$\distance(I,x) = \abs{I - x} = x - I \ge \delta$$

pour tout $x \in A$. Soit alors :

$$y = I + \frac{\delta}{2}$$

On voit que $I \strictinferieur y$ et que :

$$x - y = (x - I) + (I - y) \ge \delta - \frac{\delta}{2} = \frac{\delta}{2} \strictsuperieur 0$$

pour tout $x \in A$, c'est-à-dire $y \le A$. On a donc $I \strictinferieur y \le A$, ce qui contredit la définition de l'infimum. Pour tout $\delta \strictsuperieur 0$, on peut donc trouver un $x \in A$ tel que $\distance(I,x) \le \delta$. On en conclut que $\distance(I,A) = 0$, c'est-à-dire :

$$\inf A \in \adh A$$


