
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Extrema
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:extrema}

* Dépendances

  - Chapitre \ref{chap:relations} : Les relations
  - Chapitre \ref{chap:ordres} : Les ordres

* Comparaison élément - ensemble

Soit $\le$ un ordre sur l'ensemble $\Omega$ et $A \subseteq \Omega$. Nous dirons qu'un objet $m \in \Omega$ est inférieur à l'ensemble $A$, ou que $m$ est un minorant de $A$, et nous le noterons :

$$m \le A$$

si $m \le a$ pour tout élément $a \in A$. Inversément, nous dirons que $m$ est supérieur à $A$, ou que $m$ est un majorant de $A$, et nous le noterons :

$$m \ge A$$

si $m \ge a$ pour tout élément $a \in A$ :


* Comparaison ensemble - ensemble


** En-dessous

Soit $\le$ un ordre sur l'ensemble $\Omega$ et $A,B \subseteq \Omega$.
Nous dirons que $A$ est en-dessous de l'ensemble $B$, et nous le noterons :

$$A \ensinferieur B$$

si tout élément $a \in A$ vérifie $a \le B$. Cela revient à imposer l'inégalité :

$$a \le b$$

pour tout couple $(a,b) \in A \times B$.


** Au-dessus

On dit que $A$ est au-dessus de l'ensemble $B$, et on le note :

$$A \enssuperieur B$$

si et seulement si :

$$B \ensinferieur A$$

Cela revient à imposer l'inégalité :

$$a \ge b$$

pour tout couple $(a,b) \in A \times B$.


** Remarque

Attention, ces comparaisons ne constituent pas un ordre. En particulier, un ensemble quelconque n'est en général ni au-dessus ni en-dessous de lui-même.


* Majorants et minorants

Soit $\le$ un ordre sur l'ensemble de référence $\Omega$ et $A \subseteq \Omega$. L'ensemble des majorants de $A$ est l'ensemble des éléments de $\Omega$ supérieurs à A :

$$\major A = \{ m \in \Omega : m \ge A \}$$

Si $\major A \ne \emptyset$, on dit que $A$ est majoré ou encore que $A$ est borné supérieurement. L'ensemble des minorants de $A$ est l'ensemble des éléments de $\Omega$ inférieurs à A :

$$\minor A = \{ m \in \Omega : m \le A \}$$

Si $\minor A \ne \emptyset$, on dit que $A$ est minoré ou encore que $A$ est borné inférieurement.


** Préciser l'ordre

Lorsqu'on veut préciser l'ordre $\le$ utilisé, on note :

#+BEGIN_CENTER
\(
\major_\le A = \{ m \in \Omega : m \ge A \} \\ \)

\(
\minor_\le A = \{ m \in \Omega : m \le A \}
\)
#+END_CENTER


** Comparaisons d'ensembles

On se rend compte que si $B \subseteq \Omega$ vérifie $B \enssuperieur A$, tous les éléments de $B$ sont dans l'ensemble des majorants :

$$B \enssuperieur A \ \Rightarrow \ B \subseteq \major A$$

Inversément, si $B$ est en-dessous de $A$, tous ses éléments sont dans l'ensemble des minorants :

$$B \ensinferieur A \ \Rightarrow \ B \subseteq \minor A$$


* Éléments maximaux et minimaux

On dit d'un élément $M \in A$ qu'il est maximal dans $A$ si pour tout $a \in A$ vérifiant $a \ge M$, on a $M = a$. Autrement dit, aucun élément de $A$ distinct de $M$ n'est supérieur à ce dernier. $M$ est donc le seul élément de $A$ à être supérieur (au sens large) à lui-même. On a donc $\major \{ M \} \cap A = \{ M \}$. On note $\maxim A$ l'ensemble des éléments maximaux de $A$ :

$$\maxim A = \Big\{ M \in A : \major \{ M \} \cap A = \{ M \} \Big\}$$

Symétriquement, on dit d'un élément $m \in A$ qu'il est minimal dans $A$ si pour tout $a \in A$ vérifiant $a \le m$, on a $m = a$. Autrement dit, aucun élément de $A$ distinct de $m$ n'est inférieur à ce dernier. $m$ est donc le seul élément de $A$ à être inférieur (au sens large) à lui-même. On a donc $\minor \{ m \} \cap A = \{ m \}$. On note $\minim A$ l'ensemble des éléments minimaux de $A$ :

$$\minim A = \Big\{ m \in A : \minor \{ m \} \cap A = \{ m \} \Big\}$$


** Préciser l'ordre

Lorsqu'on veut préciser l'ordre $\le$ utilisé, on note :

#+BEGIN_CENTER
\(
\maxim_\le A \\ \)

\(
\minim_\le A
\)
#+END_CENTER


* Maximum et minimum

Considérons le cas où l'on peut trouver des majorants de $A$ appartenant à $A$. Si $x,y \in A \cap \major A$, on a $x \ge y$ puisque $x$ est un majorant de $A$ et que $y \in A$. Mais on a aussi $y \ge x$ puisque $y$ est également un majorant de $A$ et que $x \in A$. On en conclut que $x = y$ et que l'intersection ne contient qu'un seul élément $M$ :

$$A \cap \major A = \{ M \}$$

On dit alors que $M \in A$ est le maximum de l'ensemble $A$ et on le note :

$$M = \max A = \max_{a \in A} a$$

A présent, supposons que l'on puisse trouver des minorants de $A$ appartenant à $A$. Supposons que $x,y \in A \cap \minor A$. On a alors $x \le y$ puisque $x$ est un minorant de $A$ et que $y \in A$. Mais on a aussi $y \le x$ puisque $y$ est également un minorant de $A$ et que $x \in A$. On en conclut que $x = y$. L'intersection ne contient donc qu'un seul élément $m$ :

$$A \cap \minor A = \{ m \}$$

On dit alors que $m$ est le minimum de l'ensemble $A$ et on le note :

$$m = \min A = \min_{a \in A} a$$


** Préciser l'ordre

Lorsqu'on veut préciser l'ordre $\le$ utilisé, on note plutôt :

#+BEGIN_CENTER
\(
\max_\le A = \max A \\ \)

\(
\min_\le A = \min A
\)
#+END_CENTER


** Maximal et minimal

Supposons que $M = \max A$ existe. On a $M \in A$. Soit $a \in A$ vérifiant $M \le a$. Par définition du maximum, on a aussi $M \ge a$, d'où $M = a$. On en conclut que le maximum est un élément maximal. A présent, soit $x \in \maxim A$. Comme $x \le M$, on en conclut que $x = M$. On a donc :

$$\maxim A = \{ \max A \}$$

Supposons que $m = \min A$ existe. On a $m \in A$. Soit $a \in A$ vérifiant $m \ge a$. Par définition du minimum, on a aussi $m \le a$, d'où $m = a$. On en conclut que le minimum est un élément minimal. A présent, soit $x \in \minim A$. Comme $x \ge m$, on en conclut que $x = m$. On a donc :

$$\minim A = \{ \min A \}$$


* Supremum et infimum

Soit un ensemble $A \subseteq \Omega$ dont le maximum $M = \max A$ existe et l'élément $b \in \Omega$ tel que $b \ge A$. Comme $M$ est un élément de $A$, on a forcément $b \ge M$. Mais d'un autre coté, $M \ge A$ par définition. Donc :

$$b \ge M \ge A$$

Comme ces relations sont valables pour tout les $b$ supérieurs à $A$, on en conclut que :

$$\major A \ge M \ge A$$

Relations qui nous disent que $M$ est le plus petit des objets supérieurs à $A$. Considérons à présent un cas plus général où nous ne supposons pas que le maximum de $A$ existe. Supposons seulement que l'on puisse trouver un $S \in \Omega$ tel que :

$$\major A \ge S \ge A$$

La première inégalité nous dit que $S$ est un minorant de $\major A$. La seconde nous dit que $S$ est un majorant de $A$, autrement dit $S \in \major A$. Les deux conditions nous permettent d'affirmer que $S$ est le minimum de l'ensemble des majorants de $A$ :

$$S = \min \major A$$

Cet élément $S$ est donc unique. On l'appelle supremum et on le note :

$$S = \sup A = \sup_{a \in A} a = \min \major A$$

Il est important de remarquer que $S$ n'appartient pas forcément à $A$. On procéde de la même façon pour étendre la notion de minimum. Si on peut trouver un $I \in \Omega$ tel que :

$$\minor A \le I \le A$$

on en conclut que $I$ est le maximum de l'ensemble des minorants de $A$ et qu'il est donc unique. On l'appelle infimum et on le note :

$$I = \inf A = \inf_{a \in A} a = \max \minor A$$


** Préciser l'ordre

Lorsqu'on veut préciser l'ordre $\le$ utilisé, on note :

#+BEGIN_CENTER
\(
\sup_\le A = \min \major A \\ \)

\(
\inf_\le A = \max \minor A
\)
#+END_CENTER


** Comparaison des bornes

Si $A$ est non vide, il suffit de choisir $x \in A$ pour se rendre compte que :

$$\inf A \le x \le \sup A$$

d'où :

$$\inf A \le \sup A$$


** Cas particulier

Dans le cas où le maximum de $A$ existe, on a par unicité $\sup A = \max A$.
Dans le cas où le minimum de $A$ existe, on a par unicité $\inf A = \min A$.


* Ensembles finis

Nous allons montrer que, sous l'hypothèse d'un ordre total, tout ensemble comportant un nombre fini d'éléments admet un maximum et un minimum. Si l'ensemble ne contient qu'un élément, soit $A_1 = \{a\}$, on a $a \le a$ et donc :

$$a = \max\{a\} = \min\{a\}$$

Supposons à présent que l'ensemble comporte deux éléments, soit $A_2 = \{a_1,a_2\}$. Si $a_1 \ge a_2$, on a $a_1 \ge \{a_1,a_2\}$. Dans le cas contraire, on a $a_2 \ge \{a_1,a_2\}$. On en déduit que :

#+BEGIN_CENTER
\(
\max\{a_1,a_2\} =
\begin{cases}
a_1 & \text{ si } a_1 \ge a_2 \)

\(
a_2 & \text{ sinon}
\end{cases}
\)
#+END_CENTER

Le minimum est donné par l'expression duale :

#+BEGIN_CENTER
\(
\min\{a_1,a_2\} =
\begin{cases}
a_1 & \text{ si } a_1 \le a_2 \)

\(
a_2 & \text{ sinon}
\end{cases}
\)
#+END_CENTER

Supposons à présent avoir démontré que tout ensemble de $n - 1$ éléments admettait un maximum et un minimum. Soit l'ensemble $A = \{a_1,a_2,...,a_{n - 1},a_n\}$ comportant $n$ éléments. L'ensemble $A_{n - 1} = \{a_1,a_2,...,a_{n - 1}\}$ contient $n - 1$ éléments et admet donc :

#+BEGIN_CENTER
\(
\sigma = \max \{a_1,a_2,...,a_{n - 1}\} \)

\(
\lambda = \min \{a_1,a_2,...,a_{n - 1}\}
\)
#+END_CENTER

Posons $\alpha = \max\{\sigma,a_n\}$. On voit que $\alpha \in A$, que $\alpha \ge \sigma \ge A_{n - 1}$ et que $\alpha \ge a_n$. On en déduit que $\alpha \ge A$. Donc :

$$\max \{a_1,a_2,...,a_{n - 1},a_n\} = \max \Big\{ \max \{a_1,a_2,...,a_{n - 1}\} , a_n \Big\}$$

Posons $\beta = \min\{\lambda,a_n\}$. On voit que $\beta \in A$, que $\beta \le \lambda \le A_{n - 1}$ et que $\beta \le a_n$. On en déduit que $\beta \le A$. Donc :

$$\min \{a_1,a_2,...,a_{n - 1},a_n\} = \min \Big\{ \min \{a_1,a_2,...,a_{n - 1}\} , a_n \Big\}$$

Tout ensemble comportant un nombre fini d'éléments et sur lequel est défini un ordre total admet donc un maximum et un minimum. De plus, la démonstration nous donne un moyen d'évaluer récursivement ces extrema.


** Notations

On note aussi :

#+BEGIN_CENTER
\(
\max_{i = 1}^n a_i = \max \{ a_1,a_2,...,a_n \} \\ \)

\(
\min_{i = 1}^n a_i = \min \{ a_1,a_2,...,a_n \}
\)
#+END_CENTER


* Infini

Il arrive qu'aucun élément de $\Omega$ ne soit un majorant de $\Omega$. On est alors amené à ajouter à l'ensemble une borne supérieure, notée $+\infty$ (ou $\infty$), telle que tout élément $a \in \Omega$ vérifie $a \strictinferieur +\infty$. Le concept de l'infini négatif, noté $-\infty$, est similaire. Il s'agit d'une borne inférieure de $\Omega$ telle que tout élément $a \in \Omega$ vérifie $a \strictsuperieur -\infty$.


** Supremum et infimum

Lorsque l'ensemble des majorants de $A$ est vide, le supremum n'existe pas. On dit
alors qu'il est infini et on le note :

$$\sup A = +\infty$$

Lorsque l'ensemble des minorants de $A$ est vide, l'infimum n'existe pas. On dit
alors qu'il est infini et on le note :

$$\inf A = -\infty$$


* Ordre et inclusion

Soit $A,B \subseteq \Omega$ avec $A \subseteq B$. Soit l'ordre $\le$ défini sur $\Omega$.


** Max - Min

Supposons que les maxima existent. Le maximum de $A$ étant dans $A$, il est aussi dans $B$. Par conséquent, le maximum de $B$ est supérieur au maximum de $A$ :

$$\max A \le \max B$$

En suivant le même raisonnement avec les minima, on obtient :

$$\min A \ge \min B$$


** Sup - Inf

A présent, ne supposons plus l'existence des maxima ou des minima, mais seulement des supremums et infimums. Tout majorant de $B$ sera aussi un majorant de $A$. On a donc :

$$\major B \subseteq \major A$$

L'ensemble $\major B$ étant inclus dans $\major A$, son minimum doit être supérieur, et on a :

$$\sup A \le \sup B$$

En répétant le même raisonnement avec les minorants, on obtient :

$$\inf A \ge \inf B$$


* Ordre, union et intersection


** Max - Min de l'union

Supposons que les maxima de $A$ et $B$ existent. Si l'ordre est total, on a soit $\max A \le \max B$, soit $\max B \le \max A$. Le maximum :

$$M = \max \{ \max A , \max B \}$$

existe donc. On voit que $M$ appartient à $A$ ou à $B$ suivant les cas, c'est-à-dire à $A \cup B$ et que :

#+BEGIN_CENTER
\(
x \le \max A \le M \)

\(
y \le \max B \le M
\)
#+END_CENTER

pour tout $x \in A$ et $y \in B$. On en conclut que $M$ majore $A \cup B$. On a donc :

$$\max \{ \max A , \max B \} = \max (A \cup B)$$

En suivant le même raisonnement avec les minima, on obtient :

$$\min \{ \min A , \min B \} = \min (A \cup B)$$


** Max - Min de l'intersection

Supposons que les maxima de $A$ et $B$ existent et que leur intersection soit non vide :

$$A \cap B \ne \emptyset$$

Si l'ordre est total, on a soit $\max A \le \max B$, soit $\max B \le \max A$. Le minimum :

$$m = \min \{ \max A , \max B \}$$

existe donc. On voit que pour tout $x \in A \cap B$ :

#+BEGIN_CENTER
\(
x \in A \ \Rightarrow \ x \le \max A \)

\(
x \in B \ \Rightarrow \ x \le \max B
\)
#+END_CENTER

On en conclut que $x \le m$. L'élément $m$ est donc un majorant de $A \cap B$. Si le maximum de l'intersection existe, on a donc :

$$\max (A \cap B) \le \min \{ \max A , \max B \}$$

En suivant le même raisonnement avec les minima, on obtient :

$$\min (A \cap B) \ge \max \{ \min A , \min B \}$$


** Sup - Inf de l'union

A présent, ne supposons plus l'existence des maxima ou des minima, mais seulement des supremums et infimums. Comme les majorant de $A \cup B$ sont ceux qui majorent tous les éléments de $A$ et tous les éléments de $B$, on a :

$$\major (A \cup B) = (\major A) \cap (\major B)$$

Il ne nous reste plus qu'à minimiser les deux membres de cette égalité. Le minimum de l'intersection étant supérieure au maximum des minima, on a :

$$\min \Big[ (\major A) \cap (\major B) \Big] \ge \max \{ \min \major A , \min \major B \}$$

et :

$$\min \major (A \cup B) \ge \max \{ \min \major A , \min \major B \}$$

c'est-à-dire :

$$\sup (A \cup B) \ge \max \{ \sup A , \sup B \}$$

En répétant le même raisonnement avec les minorants, on obtient :

$$\minor (A \cup B) = (\minor A) \cap (\minor B)$$

et :

$$\inf (A \cup B) \le \min \{ \inf A , \inf B \}$$


** Sup - Inf de l'intersection

Soit $x \in A \cap B$ et $M \in (\major A) \cup (\major B)$. On a soit :

  - $M \in \major A$ et alors $M \ge x$ car $x \in A$
  - $M \in \major B$ et alors $M \ge x$ car $x \in B$

On en déduit que :

$$(\major A) \cup (\major B) \subseteq \major (A \cap B)$$

Le minimum d'un ensemble inclus dans un autre devant être plus grand, on obtient :

$$\min \Big[ (\major A) \cup (\major B) \Big] \ge \min \major (A \cap B)$$

Comme le minimum de l'union est égal au minimum des minima, on a :

$$\min \Big[ (\major A) \cup (\major B) \Big] = \min \{ \min (\major A) , \min (\major B) \}$$

et :

$$\min \major (A \cap B) \le \min \{ \min (\major A) , \min (\major B) \}$$

On a donc par définition :

$$\sup (A \cap B) \le \min \{  \sup A , \sup B \}$$

En répétant le même raisonnement avec les minorants, on obtient :

$$\inf (A \cap B) \ge \max \{  \inf A , \inf B \}$$


