
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Fonctions étagées
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:etagee}

* Dépendances

  - Chapitre \ref{chap:fonction} : Les fonctions
  - Chapitre \ref{chap:mesure} : Les mesures

* Définition

Soit la mesure $\mu : \mathcal{T} \mapsto \setR$, l'ensemble $\Phi \in \mathcal{T}$ et $A \in \mathcal{T}$ vérifiant $A \subseteq \Phi$. On dit que la fonction $w : \Phi \to \setR$ est étagée sur $A$ si on peut trouver une collection finie $\{ A_1, ..., A_n \} \subseteq \mathcal{T}$ formant une partition de $A$ et des réels $w_i \in \setR$ tels que :

$$w(x) = \sum_{i = 1}^n w_i \cdot \indicatrice_{A_i}(x)$$

pour tout $x \in A$. On note $\etagee(A)$ l'ensemble des fonctions étagées sur $A$.


* Mesurabilité

Soit $a \in \setR$. Comme :

$$\{ x \in A : w(x) \strictsuperieur a \} = \bigcup \{ A_i : i \in \{1,...,n\}, \ w_i \strictsuperieur a \}$$

et que l'union s'opère sur un nombre fini d'ensembles, on a :

$$\{ x \in A : w(x) \strictsuperieur a \} \in \mathcal{T}$$

On a aussi :

$$\{ x \in A : w(x) \strictinferieur a \} = \bigcup \{ A_i : i \in \{1,...,n\}, \ w_i \strictinferieur a \} \in \mathcal{T}$$

Les fonctions étagées sont mesurables.


* Multiplication par une fonction indicatrice

Soit $B \subseteq A$. On a :

\begin{align}
w(x) \cdot \indicatrice_B(x) &= \sum_{i = 1}^n w_i \cdot \indicatrice_{A_i}(x) \cdot \indicatrice_B(x) \)

\(
&= \sum_{i = 1}^n w_i \cdot \indicatrice[A_i \cap B](x)
\end{align}

Soit $B_i = A_i \cap B$. La fonction $u = w \cdot \indicatrice_B$ peut se définir par :

$$u(x) = w(x) \cdot \indicatrice_B(x) = \sum_{i = 1}^n w_i \cdot \indicatrice_{B_i}(x)$$

pour tout $x \in A$. Si $i \ne j$, on a :

$$B_i \cap B_j = (A_i \cap B) \cap (A_j \cap B) = (A_i \cap A_j) \cap B = \emptyset$$

L'union des $B_i$ nous donne :

$$\bigcup_i B_i = \bigcup_i (A_i \cap B) = B \cap \bigcup_i A_i = B \cap A = B$$

On en conclut que les ensembles $B_i$ forment une partition de $B$. La fonction $u$ est donc une fonction étagée sur $B$. Comme $u$ est nulle sur $A \setminus B$, on a même :

$$u = 0 \cdot \indicatrice[A \setminus B] + \sum_{i = 1}^n w_i \cdot \indicatrice_{B_i}$$

ce qui montre que $u$ est une fonction étagée sur $(A \setminus B) \cup B = A$.


* Essentialité


** Bornes

Soit l'ensemble $M$ rassemblant les indices correspondant aux ensembles de mesure non nulle :

$$M = \{ i \in \{1,...,n\} : \mu(A_i) \strictsuperieur 0 \}$$

et l'ensemble $N$ rassemblant les indices correspondant aux ensembles de mesure nulle :

$$N = \{ i \in \{1,...,n\} : \mu(A_i) = 0 \}$$

Par positivité de la mesure, on a clairement $M \cup N = \{1,...,n\}$. Comme l'union d'ensembles de mesure nulle est également de mesure nulle, l'ensemble :

$$Z = \bigcup_{i \in N} A_i$$

vérifie $\mu(Z) = 0$. L'ensemble :

$$A \setminus Z = A \setminus \bigcup_{i \in N} A_i = \bigcup_{i \in M} A_i$$

est donc un sous-ensemble essentiel de $A$. Comme :

$$\min_{i \in M} w_i \le w(x) \in \{ w_i : i \in M \} \le \max_{i \in M} w_i$$

pour tout $x \in A \setminus Z$, on a :

$$\min \{ w_i : i \in M \} \essinferieur w \essinferieur \max \{ w_i : i \in M \}$$


** Extrema

Soit :

#+BEGIN_CENTER
\(
\alpha = \arg\max_{i \in M} w_i \in M \)

\(
\beta = \arg\min_{i \in M} w_i \in M
\)
#+END_CENTER

On a alors :

#+BEGIN_CENTER
\(
\sigma = w_\alpha = \max \{ w_i : i \in M \} \)

\(
\lambda = w_\beta = \min \{ w_i : i \in M \}
\)
#+END_CENTER

Comme $w \essinferieur \sigma$, on doit avoir :

$$\supessentiel_{x \in A} w(x) \le \sigma$$

Mais on a aussi $w = w_\alpha = \sigma$ sur $A_\alpha$, et a fortiori $w \ge \sigma$ sur $A_\alpha$, avec $\mu(A_\alpha) \strictsuperieur 0$, ce qui implique :

$$\supessentiel_{x \in A} w(x) \ge \sigma$$

Ces deux inégalités nous imposent que :

$$\supessentiel_{x \in A} w(x) = \sigma$$

Comme $w \esssuperieur \lambda$, on a :

$$\infessentiel_{x \in A} w(x) \ge \lambda$$

Mais on a aussi $w = w_\beta =\lambda$ sur $A_\beta$, et a fortiori $w \le \lambda$ sur $A_\beta$, avec $\mu(A_\beta) \strictsuperieur 0$, ce qui implique :

$$\infessentiel_{x \in A} w(x) \le \lambda$$

Ces deux inégalités nous imposent que :

$$\infessentiel_{x \in A} w(x) = \lambda$$

Les extrema essentiels d'une fonction étagée existent toujours et sont très simples à évaluer :

#+BEGIN_CENTER
\(
\supessentiel_{x \in A} w(x) = \max \{ w_i : i \in \{1,...,n\}, \ \mu(A_i) \strictsuperieur 0 \} \\ \)

\(
\infessentiel_{x \in A} w(x) = \min \{ w_i : i \in \{1,...,n\}, \ \mu(A_i) \strictsuperieur 0 \}
\)
#+END_CENTER


* Intégrale d'une mesure

L'intégrale d'une mesure $\mu : \mathcal{T} \mapsto \setR$ sur $A \in \mathcal{T}$ est simplement la mesure de $A$ :

$$\int_A d\mu(x) = \mu(A)$$


* Intégrale d'une constante

On étend la définition aux constantes $c \in \setR$ par linéarité :

$$\int_A c \ d\mu(x) = c \cdot \int_A d\mu(x) = c \cdot \mu(A)$$


** Fonction nulle

La fonction nulle peut être considérée comme la constante $0$. On a donc :

$$\int_A 0 \ d\mu(x) = 0 \cdot \int_A d\mu(x) = 0$$


* Intégrale d'une fonction étagée

Soit un ensemble $A$ et une fonction $w \in \etagee(A)$. On peut trouver des $w_i \in \setR$ et des $A_i \in \mathcal{T}$ formant une partition de $A$ et tels que :

$$w(x) = \sum_{i = 1}^n w_i \cdot \indicatrice_{A_i}(x)$$

pour tout $x \in A$. On étend la définition de l'intégrale en imposant la linéarité :

$$\int_A w(x) \ d\mu(x) = \sum_{i = 1}^n \int_{A_i} w(x) \ d\mu(x)$$

La fonction étagée $w$ étant constante et valant $w_i$ sur chaque $A_i$, on a :

$$\int_{A_i} w(x) \ d\mu(x) = \int_{A_i} w_i \ d\mu(x) = w_i \cdot \mu(A_i)$$

et finalement :

$$\int_A w(x) \ d\mu(x) = \sum_{i = 1}^n w_i \cdot \mu(A_i)$$


* Unicité

Nous allons vérifier que, pour une fonction étagée $w$ donnée, l'intégrale ainsi définie ne dépend pas de la partition utilisée. Soit les collections finies d'ensembles $A_i \in \mathcal{T}$ et $B_j \in \mathcal{T}$ telles que $\{A_1,A_2,...,A_m\}$ et $\{B_1,B_2,...,B_n\}$ forment deux partitions de $A$ et telles que l'on puisse trouver des $a_i,b_j \in \setR$ vérifiant :

$$w(x) = \sum_{i = 1}^m a_i \cdot \indicatrice[A_i](x) = \sum_{j = 1}^n b_j \cdot \indicatrice[B_j](x)$$

pour tout $x \in A$.


** Intersection des partitions

Posons $P = \{1,...,m\} \times \{1,...,n\}$ et $C_{ij} = A_i \cup B_j \in \mathcal{T}$ pour tout $(i,j) \in P$. Si $i \ne k$ ou si $j \ne l$, on a :

$$C_{ij} \cap C_{kl} = A_i \cap B_j \cap A_k \cap B_l = (A_i \cap A_k) \cap (B_j \cap B_l) = \emptyset$$

On voit également que :

#+BEGIN_CENTER
\(
\bigcup_j C_{ij} = \bigcup_j (A_i \cap B_j) = A_i \cap \bigcup_j B_j = A_i \cap A = A_i \)

\(
\bigcup_i C_{ij} = \bigcup_i (A_i \cap B_j) = B_j \cap \bigcup_i A_i = A \cap B_j = B_j
\)
#+END_CENTER

Leur union globale sur les $(i,j)$ s'écrit donc :

$$\bigcup_{i,j} C_{ij} = \bigcup_i A_i = A$$

Les $C_{ij}$ forment également une partition de $A$.

Nous savons que les $C_{ij}$ ne se chevauchent pas et que leur union sur $j$ permet de reformer les $A_i$. De même, leur union sur $i$ permet de reformer les $B_j$. On en conclut que :

#+BEGIN_CENTER
\(
\mu(A_i) = \sum_j \mu(C_{ij}) \)

\(
\mu(B_j) = \sum_i \mu(C_{ij})
\)
#+END_CENTER

et :

#+BEGIN_CENTER
\(
\indicatrice[A_i] = \sum_j \indicatrice[C_{ij}] \)

\(
\indicatrice[B_j] = \sum_i \indicatrice[C_{ij}]
\)
#+END_CENTER


** Expression alternative

Utilisant les propriétés des $C_{ij}$, la fonction $w$ peut se réécrire comme suit :

$$w(x) = \sum_{(i,j) \in P} a_i \cdot \indicatrice[C_{ij}](x) = \sum_{(i,j) \in P} b_j \cdot \indicatrice[C_{ij}](x)$$

On en conclut que :

$$\sum_{(i,j) \in P} (a_i - b_j) \cdot \indicatrice[C_{ij}](x) = 0$$


** Implication de l'égalité

Soit un couple $(i,j) \in P$ tel que $\indicatrice[C_{ij}] \ne 0$, c'est-à-dire $C_{ij} \ne \emptyset$. Soit $x \in C_{ij}$. Pour tout $(k,l) \in P \setminus (i,j)$, on a $C_{kl} \cap C_{ij} = \emptyset$ et donc $\indicatrice[C_{kl}](x) = 0$. La somme :

$$\sum_{(k,l) \in P} (a_k - b_l) \cdot \indicatrice[C_{kl}](x) = 0$$

se réduit donc à :

$$(a_i - b_j) \cdot \indicatrice[C_{ij}](x) = 0$$

On doit donc avoir $a_i - b_j = 0$, c'est-à-dire $a_i = b_j$. On pose :

$$F = \{ (i,j) \in P : C_{ij} \ne \emptyset \}$$


** Intégrales

L'intégrale évaluée sur le découpage des $A_i$ s'écrit :

$$I = \sum_i a_i \cdot \mu(A_i) = \sum_{(i,j) \in P} a_i \cdot \mu(C_{ij})$$

Mais comme $\mu(C_{ij}) = \mu(\emptyset) = 0$ pour tout $(i,j) \in P \setminus F$, on a finalement :

$$I = \sum_{(i,j) \in F} a_i \cdot \mu(C_{ij})$$

De même, l'intégrale évaluée sur le découpage des $B_j$ s'écrit :

$$J = \sum_j b_j \cdot \mu(B_j) = \sum_{(i,j) \in P} b_j \cdot \mu(C_{ij}) = \sum_{(i,j) \in F} b_j \cdot \mu(C_{ij})$$

Comme $a_i = b_j$ pour tous les couples $(i,j) \in F$, on en déduit que :

$$J = \sum_{(i,j) \in F} a_i \cdot \mu(C_{ij}) = I$$

L'intégrale d'une fonction étagée ne dépend donc pas du choix de la partition utilisée.


* Ordre

Soit les fonctions étagées $u,v \in \etagee(A)$ vérifiant $u \essinferieur v$. Soit les partitions $\{U_1,...,U_m\}$ et $\{V_1,...,V_n\}$ et les réels $u_i,v_j$ tels que :

#+BEGIN_CENTER
\(
u(x) = \sum_{i = 1}^m u_i \cdot \indicatrice_{U_i}(x) \)

\(
v(x) = \sum_{j = 1}^n v_j \cdot \indicatrice_{V_j}(x)
\)
#+END_CENTER

pour tout $x \in A$. Si $W_{ij} = U_i \cap V_j$, on sait que :

#+BEGIN_CENTER
\(
u(x) = \sum_{i,j} u_i \cdot \indicatrice[W_{ij}](x) \)

\(
v(x) = \sum_{i,j} v_j \cdot \indicatrice[W_{ij}](x)
\)
#+END_CENTER

Posons $P = \{1,...,m\} \times \{1,...,n\}$ et :

$$M = \{ (i,j) \in P : \mu(W_{ij}) \strictsuperieur 0 \}$$

Considérons le choix $(i,j) \in P$ et $x \in W_{ij}$. Comme $u$ est essentiellement inférieure à $v$, on doit avoir $u_i \le v_j$ dès que $\mu(W_{ij}) \strictsuperieur 0$, c'est-à-dire lorsque $(i,j) \in M$. Examinons à présent les intégrales. Les mesures des $W_{ij}$ s'annulant pour tout $(i,j) \in P \setminus M$, on a :

$$\int_A u(x) \ d\mu(x) = \sum_{i,j} u_i \cdot \mu(W_{ij}) = \sum_{(i,j) \in M} u_i \cdot \mu(W_{ij})$$

et :

$$\int_A v(x) \ d\mu(x) = \sum_{i,j} v_j \cdot \mu(W_{ij}) = \sum_{(i,j) \in M} v_j \cdot \mu(W_{ij})$$

La propriété $u_i \le v_j$ étant vérifiée pour tout $(i,j) \in M$, on en conclut que :

$$\int_A u(x) \ d\mu(x) \le \int_A v(x) \ d\mu(x)$$

L'intégrale conserve l'ordre essentiel entre fonctions étagées.


** Signe

Comme la fonction constante $0$ est un cas particulier de fonction étagée, l'intégrale d'une fonction étagée $u$ essentiellement supérieure à zéro est positive. De même, l'intégrale d'un fonction étagée $v$ essentiellement inférieure à zéro est négative.


** Egalité

Soit deux fonctions étagées $u,v$ essentiellement égales ($u \essegal v$). On a $u \essinferieur v$ et l'intégrale de $u$ est inférieure à l'intégrale de $v$. Mais on a aussi $u \esssuperieur v$ et l'intégrale de $u$ est supérieure à l'intégrale de $v$. On en conclut que :

$$\int_A u(x) \ d\mu(x) = \int_A v(x) \ d\mu(x)$$


* Encadrement

Soit $w \in \etagee(A)$. Comme les constantes sont des cas particuliers de fonctions étagées et que l'on a :

$$\infessentiel_{x \in A} w(x) \essinferieur w \essinferieur \supessentiel_{x \in A} w(x)$$

on en conclut en intégrant que :

$$\mu(A) \cdot \infessentiel_{x \in A} w(x) \le \int_A w(x) \ d\mu(x) \le \mu(A) \cdot \supessentiel_{x \in A} w(x)$$


* Propriétés extrémales

Soit $w \in \etagee(A)$. Si $u$ est une fonction étagée vérifiant $u \essinferieur w$, l'intégrale de $u$ est inférieure à l'intégrale de $w$. Par ailleurs, le choix $u = w \essinferieur w$ reproduit bien entendu l'intégrale de $w$. On en conclut que :

$$\int_A w(x) \ d\mu(x) = \sup \left\{ \int_A u(x) \ d\mu(x) : u \in \etagee(A), \ u \essinferieur w \right\}$$

On aboutit avec un raisonnement analogue à :

$$\int_A w(x) \ d\mu(x) = \inf \left\{ \int_A v(x) \ d\mu(x) : v \in \etagee(A), \ v \esssuperieur w \right\}$$


* Additivité

Soit les ensembles $A$ et $B$ disjoints :

$$A \cap B = \emptyset$$

et une fonction $w \in \etagee(A \cup B)$. On peut trouver des $w_i \in \setR$ et des $C_i \in \mathcal{T}$ formant une partition de $A \cup B$ et tels que :

$$w(x) = \sum_i w_i \cdot \indicatrice_{C_i}(x)$$

pour tout $x \in A$. On sait que les $A_i = C_i \cap A$ forment une partition de $A$ et que les $B_i = C_i \cap B$ forment une partition de $B$. On a aussi :

$$A_i \cap B_i = C_i \cap A \cap C_i \cap B = C_i \cap (A \cap B) = \emptyset$$

Comme :

$$C_i = C_i \cap (A \cup B) = (C_i \cap A) \cup (C_i \cap B) = A_i \cup B_i$$

on a $\indicatrice[C_i] = \indicatrice[A_i] + \indicatrice[B_i]$ et :

\begin{align}
w &= \sum_i w_i \cdot (\indicatrice[A_i] + \indicatrice[B_i]) \)

\(
&= \sum_i w_i \cdot \indicatrice[A_i] + \sum_i w_i \cdot \indicatrice[B_i]
\end{align}

Evaluons l'intégrale de $w$ sur $A \cup B$. Il vient :

\begin{align}
\int_{A \cup B} w(x) \ d\mu(x) &= \sum_i w_i \cdot \mu(A_i) + \sum_i w_i \cdot \mu(B_i) \)

\(
&= \int_A w(x) \ d\mu(x) + \int_B w(x) \ d\mu(x)
\end{align}

L'intégrale des fonctions étagées est donc additive sur les ensembles concernés.


* Propriétés diverses

Soit $u,v \in \etagee(A)$. On peut trouver des $u_i,v_j \in \setR$ et des $U_i,V_i \in \mathcal{T}$ tels que $\{U_1,...,U_n\}$ et $\{V_1,...,V_m\}$ forment des partitions de $A$ et vérifiant :

#+BEGIN_CENTER
\(
u(x) = \sum_{i = 1}^n u_i \cdot \indicatrice[U_i](x) \)

\(
v(x) = \sum_{j = 1}^m v_j \cdot \indicatrice[V_j](x)
\)
#+END_CENTER

pour tout $x \in A$. Nous avons vu que les intersections $W_{ij} = U_i \cup V_j \in \mathcal{T}$ forment aussi une partition de $A$ et qu'elles possèdent les propriétés :

#+BEGIN_CENTER
\(
\mu(U_i) = \sum_j \mu(W_{ij}) \)

\(
\mu(V_j) = \sum_i \mu(W_{ij})
\)
#+END_CENTER

et :

#+BEGIN_CENTER
\(
\indicatrice[U_i] = \sum_j \indicatrice[W_{ij}] \)

\(
\indicatrice[V_j] = \sum_i \indicatrice[W_{ij}]
\)
#+END_CENTER

Les fonctions $u,v$ peuvent donc également s'exprimer comme :

#+BEGIN_CENTER
\(
u(x) = \sum_{i,j} u_i \cdot \indicatrice[W_{ij}](x) \)

\(
v(x) = \sum_{i,j} v_j \cdot \indicatrice[W_{ij}](x)
\)
#+END_CENTER


** Espace vectoriel

Soit $\alpha,\beta \in \setR$. On voit que la fonction $w : A \mapsto \setR$ définie par :

$$w(x) = \alpha \cdot u(x) + \beta \cdot v(x)$$

est également une fonction étagée puisque :

$$w(x) = \sum_{i,j} (\alpha \cdot u_i + \beta \cdot v_j) \cdot \indicatrice[W_{ij}](x)$$

Nous venons de montrer que toute combinaison linéaire de fonctions étagées est une fonction étagée. L'ensemble $\etagee(A)$ forme donc un espace vectoriel sur $\setR$.


** Intégrale

Evaluons l'intégrale de $w$. On obtient :

\begin{align}
\int_A w(x) \ d\mu(x) &= \sum_{i,j} (\alpha \cdot u_i + \beta \cdot v_j) \cdot \mu(W_{ij}) \)

\(
&= \alpha \sum_i u_i \sum_j \mu(W_{ij}) + \beta \sum_j v_j \sum_i \mu(W_{ij}) \)

\(
&= \alpha \sum_i u_i \cdot \mu(U_i) + \beta \sum_j v_j \cdot \mu(V_j) \)

\(
&= \alpha \int_A u(x) \ d\mu(x) + \beta \int_A v(x) \ d\mu(x)
\end{align}

On en conclut que :

$$\int_A (\alpha \cdot u(x) + \beta \cdot v(x)) \ d\mu(x) = \alpha \cdot \int_A u(x) \ d\mu(x) + \beta \cdot \int_A v(x) \ d\mu(x)$$

Nous venons de prouver la linéarité de l'intégrale des fonctions étagées.


** Fonctions max et min

On voit que la fonction :

$$\max\{u,v\}(x) = \sum_{i,j} \max\{u_i,v_j\} \cdot \indicatrice[W_{ij}](x)$$

est également une fonction étagée. Il en va de même pour :

$$\min\{u,v\}(x) = \sum_{i,j} \min\{u_i,v_j\} \cdot \indicatrice[W_{ij}](x)$$


* Mesure nulle

Soit un ensemble $A$ vérifiant $\mu(A) = 0$ et une fonction $w$ étagée sur $A$ définie par :

$$w(x) = \sum_{i = 1}^n w_i \cdot \indicatrice_{A_i}(x)$$

pour tout $x \in A$. Les $w_i$ sont bien entendu des réels et les $A_i$ forment une partition de $A$. Comme les $A_i$ sont inclus dans l'ensemble $A$ qui est de mesure nulle, on a $\mu(A_i) = 0$. L'intégrale s'écrit donc :

$$\int_A w(x) \ d\mu(x) = \sum_{i = 1}^n w_i \cdot \mu(A_i) = \sum_{i = 1}^n w_i \cdot 0 = 0$$

L'intégrale d'une fonction étagée sur un ensemble de mesure nulle est nulle.


* Mesurabilité et opérations

Soit la mesure $\mu : \mathcal{T} \mapsto \setR$, l'ensemble $A \in \mathcal{T}$, une fonction mesurable $f : A \mapsto \setR$ et une fonction étagée $w \in \etagee(A)$. Considérons un choix de $w_i \in \setR$ et de $A_i \in \mathcal{T}$ formant une partition de $A$ et tels que :

$$w(x) = \sum_{i = 1}^n w_i \cdot \indicatrice_{A_i}(x)$$

pour tout $x \in A$.


** Addition

On a clairement :

\begin{align}
\{ x \in A : f(x) + w(x) \strictsuperieur a \} &= \bigcup_{i = 1}^n \{ x \in A_i : f(x) + w(x) \strictsuperieur a \} \)

\(
&= \bigcup_{i = 1}^n \{ x \in A_i : f(x) + w_i \strictsuperieur a \} \)

\(
&= \bigcup_{i = 1}^n \{ x \in A_i : f(x) \strictsuperieur a - w_i \}
\end{align}

Comme $f$ est mesurable, les ensembles :

$$F_i = \{ x \in A_i : f(x) \strictsuperieur a - w_i \}$$

appartiennent à $\mathcal{T}$. Comme l'union opère sur un nombre fini d'ensembles, on a :

$$\{ x \in A : f(x) + w(x) \strictsuperieur a \} = \bigcup_{i = 1}^n F_i \in \mathcal{T}$$

On conclut de même que :

$$\{ x \in A : f(x) + w(x) \strictinferieur a \} = \bigcup_{i = 1}^n \{ x \in A_i : f(x) \strictinferieur a - w_i \} \in \mathcal{T}$$

La fonction $f + w$ est donc mesurable. Il en va de même pour $-(f + w) = -f - w$.


** Soustraction

Comme l'opposé d'une fonction étagée est une fonction étagée :

$$-w(x) = - \sum_{i = 1}^n w_i \cdot \indicatrice_{A_i}(x) = \sum_{i = 1}^n (-w_i) \cdot \indicatrice_{A_i}(x)$$

la fonction $f - w = f + (-w)$ est également mesurable. Il en va de même pour $-(f - w) = w - f$.


