
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Fonctions
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:fonctions}

* Dépendances

  - Chapitre \ref{chap:ensembles} : Les ensembles
  - Chapitre \ref{chap:relations} : Les relations

* Définitions

Une fonction $f$ de $A$ vers $B$ associe à chaque $x \in A$ un unique élément $f(x) \in B$. On note $\fonction(A,B)$ l'ensemble des fonctions $f$ de $A$ vers $B$. On utilise aussi la notation :

$$f : A \mapsto B$$

pour préciser que $f \in \fonction(A,B)$ et :

$$f : x \mapsto f(x)$$

pour préciser que $f$ associe $x \in A$ à $f(x) \in B$. On dit que $f(x)$ est la valeur de $f$ en $x$.


** Remarque

La notation $f : A \mapsto B$ signifie que :

  - $f(x)$ est défini pour tout $x \in A$
  - $f(x) \in B$

Par conséquent, si $C \subseteq A$ et si $B \subseteq D$, la condition $f : A \mapsto B$ implique $f : C \mapsto D$.


** Synonymes

On parle indifféremment de fonction ou d'application.


* Fonctions discrètes

Dans le cas particulier où $f \in \fonction( \{ 1,2,...,N \} , B )$,
on peut associer à $f$ un nombre $(f_1,f_2,...,f_N) \in B^N$ par :

$$f_i = f(i)$$

pour tout $i \in \{ 1,2,...,N \}$. Inversément, à tout
$(f_1,f_2,...,f_N) \in B^N$, on associe une fonction $f : \{ 1,2,...,N \}
\mapsto B$ par :

$$f(i) = f_i$$

On voit donc l'équivalence :

$$\fonction( \{ 1,2,...,N \} , B ) \equiv B^N$$

** Notation

Dans le cas discret, si :

$$ D = \{ 1,2,...,N \} $$

on a :

$$ \fonction(D,B) \equiv B^N = B^{\cardinal(D)} $$

Ce constat nous inspire la notation :

$$ B^D = \fonction(D,B) $$

On généralise cette notation à des ensembles quelconques $A$ et $B$,
qu’ils soient finis ou infinis :

$$B^A = \fonction(A,B)$$

* Relation associée

On peut associer à toute fonction $f : A \mapsto B$ une relation $R \in \relation(A,B)$ définie par :

$$R = \{ (x,f(x)) : x \in A \}$$

On a clairement :

$$R(x) = \{ f(x) \}$$


* Relation inverse

Soit $f : A \mapsto B$ associée à la relation $R \in \relation(A,B)$. La
relation inverse $R^{-1} \in \relation(B,A)$ est définie par :

$$R^{-1} = \{ (f(x),x) \in B \times A : x \in A \}$$

* Fonction identité

La fonction identité $\identite : A \mapsto A$ est définie par :

$$\identite : x \mapsto \identite(x) = x$$

** Relation

La relation associée à la fonction identité s'écrit :

$$\{ (x,\identite(x)) \in A^2 : x \in A \} = \{ (x,x) \in A^2 : x \in A \}$$

La fonction identité est donc associée à la relation identité.

* Image d'un ensemble

Soit $f : A \mapsto B$. L'image d'un sous-ensemble $X \subseteq A$ par $f$ est l'ensemble des valeurs que prend $f$ en tous les éléments de $X$ :

$$f(X) = \{ f(x) : x \in X \}$$


* Image d'une fonction

Soit $f : A \mapsto B$. L'image de $f$ est l'ensemble des valeurs que prend $f$ en tous les éléments de $A$ :

$$\image f = f(A) = \{ f(x) : x \in A \}$$


* Image inverse

Soit $f : A \mapsto B$. Pour tout $y \in B$, l'image inverse est l'ensemble défini par :

$$f^{-1}(y) = \{ x \in A : f(x) = y \}$$

L'image inverse d'un ensemble $Y \subseteq B$ est définie par :

$$f^{-1}(Y) = \{ x \in A : f(x) \in Y \}$$

* Domaine

Soit un ensemble $A \subseteq \Omega$ et une fonction $f : A \mapsto B$. Le domaine de $f$ est l'ensemble des éléments de $x \in \Omega$ tels que $f(x) \in B$ existe. Autrement dit :

$$\domaine f = A$$


* Composée

Soit les fonctions $f : A \mapsto B$ et $g : B \mapsto C$.

Supposons que les grandeurs $x \in A$, $y \in B$ et $z \in C$ soient
reliées par les égalités $y = f(x)$ et $z = g(y)$. On a a alors $z
= g\left(f(x)\right)$. On définit une nouvelle fonction $g \circ f :
A \mapsto C$ associée à ce résultat par :

$$g \circ f : x \mapsto (g \circ f)(x) = g\left(f(x)\right)$$

On nomme $g \circ f$ la composée de $f$ et $g$. On note aussi :

$$g \circ f(x) = (g \circ f)(x)$$


** Association

Soit aussi $h : C \mapsto D$. On remarque que :

$$\left(h \circ (g \circ f)\right)(x) = h\left(g\left(f(x)\right)\right) = \left((h \circ g) \circ f\right)(x)$$

On note :

$$h \circ g \circ f = (h \circ (g \circ f)) = ((h \circ g) \circ f)$$


** Neutre

On constate que

$$\identite \circ f = f \circ \identite = f$$

On dit que la fonction identité est neutre pour la composition.

* Puissance

Soit une fonction $f : A \mapsto A$. La « puissance » d'une fonction est définie au moyen de la composée $\circ$ par :

$$ f^0 = \identite $$

$$ f^n = f \circ f^{n-1} $$

pour tout $n \in \setN$. On a donc en particulier $f^1 = f$ et :

$$f^n = f \circ ... \circ f$$

* Fonction constante

On associe souvent à tout élément $c \in B$ une fonction constante $\hat{c} : A \mapsto B$ définie par :

$$\hat{c}(x) = c$$

pour tout $x \in A$. On note abusivement :

$$\hat{c} = c$$


* Egalité

Deux fonctions $f,g : A \mapsto B$ sont égales si et seulement si leurs valeurs sont égales en tout point $x \in A$ :

$$f = g \quad \Leftrightarrow \quad f(x) = g(x)$$

* Produit cartésien

Soit une fonction :

$$ f : A \mapsto B^n $$

Pour chaque élément $x\in A$, la fonction produit un n-tuple :

$$ (y_1,y_2,...,y_n) = f(x) $$

Les $y_i$ étant dépendant de $x$, on peut réécrire la relation
précédente sous la forme :

$$ (f_1(x),f_2(x),...,f_n(x)) = f(x) $$

ce qui définit $n$ fonctions $f_1,f_2,...,f_n$ associée à $f$. On note
alors :

$$ f = (f_1,f_2,...f_n) $$

On dit aussi que $f_i$ est la $i^{ème}$ composante de $f$, et on le
note :

$$ f_i = \composante_i f $$

Réciproquement, les $n$ composante $f_i$ de $f$ la définissent
entièrement. C’est d’ailleurs la façon la plus courante pour
définir une fonction qui produit des n-tuples.
