
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Géométrie plane
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Point

Le point est l’élément le plus fondamental en géométrie. Les autres
objets sont définis, soit comme un ensemble de points, soit comme une
fonction agissant sur des points.

On note par convention un point par une lettre majuscule.

* Droite

Une droite $d$ est un ensemble de points alignés sur une ligne droite
infinie. On note une droite par une lettre minuscule.

Le schéma ci-dessous représente une droite $d$ :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droite.svg]]

Si on connaît deux points $A$ et $B$ appartenant à une droite $d$,
on peut aussi la définir par ces deux points $AB$. On a donc :

$$ d = AB $$

dans le schéma ci-dessous :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droite-deux-points.svg]]

* Demi-droite

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/demi-droite.svg]]

* Segment

* Distance

* Cercle

#+TOC: headlines 1 local

** Définition

Un cercle $\mathscr{C}$ de centre $C$ et de rayon $r$ est l’ensemble
des points situés à une distance $r$ de $C$.

** Périmètre du cercle

Le schéma ci-dessus représenté un cercle $\mathscr{C}$ de centre $O$,
de rayon $r$ et de diamètre $d$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-pi.svg]]

Le nombre pi, noté $\pi$, se définit comme étant le rapport constant
entre le périmètre du cercle et son diamètre. Si $p$ est le périmètre
de $\mathscr{C}$, on a donc :

$$ \pi = \frac{p}{d} $$

ou encore :

$$ p = \pi \ d $$

Comme le diamètre vaut deux fois le rayon $r$ :

$$ d = 2 \ r $$

on en déduit la forme alternative :

$$ p = 2 \ \pi \ r $$

