
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Géométrie plane
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Somme des angles d’un triangle

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/somme-angles-triangle.svg]]

La figure ci-dessus, où la droite $d$ est parallèle au côté $b$,
nous montre que la somme des angles d’un triangle vaut un angle plat,
c’est-à-dire $\pi$ :

$$ \alpha + \beta + \gamma = \pi $$

* Triangle rectangle

#+TOC: headlines 1 local

** Glossaire

Dans un triangle rectangle :

- le plus long côté est appelé hypothénuse
- les deux autres côtés, appelés cathètes, sont adjacents à l’angle droit

** Somme des angles

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/somme-angles-triangle-rectangle.svg]]

Dans le cas d’un triangle rectangle, un des angles vaut $\pi/2$ et
leur somme s’écrit :

$$ \alpha + \beta + \frac{\pi}{2} = \pi $$

ou encore :

$$ \alpha + \beta = \pi - \frac{\pi}{2} $$

et finalement :

$$ \alpha + \beta = \frac{\pi}{2} $$

** Aire

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/aire-triangle-rectangle.svg]]

Que vaut l’aire $A_T$ du triangle rectangle $T$ de côtés $a$, $b$,
$c$ ?  On sait que l’aire $A_R$ du rectangle $R$ de côtés $a$, $b$,
$d$, $e$ vaut :

$$ A_R = a \cdot b $$

Or, ce rectangle contient deux triangles identiques : $T$ et le triangle
rectangle de côtés $d$, $e$, $c$. On a donc :

$$ d = a $$

$$ e = b $$

Ces deux triangles ayant la même aire, on a :

$$ A_R = 2 \cdot A_T $$

ou encore :

$$ A_T = \frac{A_R}{2} $$

et donc :

$$ A_T = \frac{a \cdot b}{2} $$

** Théorème de Pythagore

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/pythagore.svg]]

Aire de chaque triangle rectangle :

$$ A_T = \frac{a b}{2} $$

Aire du grand carré d’après son côté $a+b$ :

$$ A = (a+b)^2 = a^2 + 2 \ a \ b + b^2 $$

Aire du grand carré exprimé comme la somme des aires du carré et
des triangles qu’il contient :

$$ A = c^2 + 4 \cdot A_T = c^2 + 4 \cdot \frac{a \ b}{2} = c^2 + 2 \ a \ b $$

Comme les deux expressions de $A$ sont égales, on a :

$$ a^2 + 2 \ a \ b + b^2 = c^2 + 2 \ a \ b $$

ce qui donne en simplifiant :

$$ a^2 + b^2 = c^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

** Triangles de Pythagore

Un triangle de Pythagore est un triangle rectangle où les longueurs
des trois côtés sont des nombres entiers.

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/triangle-pythagore.svg]]

La figure ci-dessus utilise une astuce algébrique pour obtenir certains
triangles de Pythagore. En effet :

\begin{align*}
A^2 + B^2
&= \left(a^2 - b^2\right)^2 + \left(2 \ a \ b\right)^2 \\
&= a^4 - 2 \ a^2 \ b^2 + b^4 + 4 \ a^2 \ b^2 \\
&= a^4 + 2 \ a^2 \ b^2 + b^4 \\
&= \left(a^2 + b^2\right)^2
\end{align*}

et finalement :

$$ A^2 + B^2 = C^2 $$

Choisir de telles expressions pour $A$, $B$, $C$ nous assure d’avoir
des longueurs qui respectent le théorème de Pythagore. De plus, si
les longueurs $a$, $b$, $c$ sont entières, les longueurs $A$, $B$,
$C$ le seront également. Le tableau suivant nous donne les premiers
triangles de Pythagore obtenus avec cette méthode.

| $a$ | $b$ | $A$ | $B$ | $C$ |
|-----+-----+-----+-----+-----|
|   2 |   1 |   3 |   4 |   5 |
|   3 |   2 |   5 |  12 |  13 |
|   4 |   1 |   8 |  15 |  17 |
|   4 |   3 |   7 |  24 |  25 |
|   5 |   2 |  20 |  21 |  29 |
|   5 |   4 |   9 |  40 |  41 |
|   6 |   1 |  12 |  35 |  37 |
|   6 |   5 |  11 |  60 |  61 |
|   7 |   2 |  28 |  45 |  53 |
|   7 |   4 |  33 |  56 |  65 |
|   7 |   6 |  13 |  84 |  85 |

** Propriétés des cathètes

Examinons le triangle ci-dessous :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/cathetes.svg]]

*** Produit des parties de l’hypothénuse

$$ h^2 + u^2 = a^2 $$

$$ h^2 + v^2 = b^2 $$

$$ c = u + v $$

$$ a^2 + b^2 = c^2 $$

$$ h^2 + u^2 + h^2 + v^2 = (u+v)^2 $$

$$ 2 \ h^2 + u^2 + v^2 = u^2 + 2 \ u \ v + v^2 $$

$$ 2 \ h^2 = 2 \ u \ v $$

$$ h^2 = u \ v $$

*** Carré des cathètes

\begin{align*}
a^2
&= u^2 + h^2 \\
&= u^2 + u \ v \\
&= u \ (u + v) \\
\end{align*}

$$ a^2 = u \ c $$

\begin{align*}
b^2
&= v^2 + h^2 \\
&= v^2 + u \ v \\
&= v \ (u + v) \\
\end{align*}

$$ b^2 = v \ c $$

*** Produit des cathètes

$$ a^2 \ b^2 = u \ c \ v \ c $$

$$ a^2 \ b^2 = u \ v \ c^2 $$

$$ a^2 \ b^2 = h^2 \ c^2 $$

$$ a \ b = h \ c $$
