
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Géométrie plane
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Point

Le point est l’élément le plus fondamental en géométrie. Les autres
objets sont définis, soit comme un ensemble de points, soit comme une
fonction agissant sur des points.

On note par convention un point par une lettre majuscule.

* Distance

La distance entre deux points $A$ et $B$ se note :

$$ \abs{AB} $$

Cette distance est la longueur du plus court chemin qui mène de $A$
à $B$, c’est-à-dire la longueur de la ligne droite qui les sépare.

* Droite

#+TOC: headlines 1 local

** Définition

Une droite $d$ est un ensemble de points alignés sur une ligne droite
infinie. On note une droite par une lettre minuscule.

Le schéma ci-dessous représente une droite $d$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droite.svg]]

Si on connaît deux points $A$ et $B$ appartenant à une droite $d$, on
peut aussi la définir par ces deux points. Dans le schéma ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/droite-deux-points.svg]]

la droite $d$ peut aussi se noter :

$$ (AB) $$

On a donc :

$$ d = (AB) $$

** Sécantes

On dit que deux droites $a$ et $b$ sont sécantes si elles se
croisent en un point $P$ :

$$ a \cap b = \{P\} $$

Le point $P$ est alors appelé point d’intersection de $a$ et $b$.

** Parallèles

On dit que deux droites $a$ et $b$ sont parallèles si elles ne se
croisent pas :

$$ a \cap b = \emptyset $$

ou si elles sont confondues :

$$ a = b $$

Si deux droites $a$ et $b$ sont parallèles, on le note :

$$ a \parallel b $$

* Demi-droite

Si on coupe une droite $(AB)$ en deux au niveau du point $A$, et
que l’on conserve la partie contenant le point $B$, on obtient la
demi-droite $[AB)$.

Le schéma ci-dessous donne un exemple de demi-droite :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/demi-droite.svg]]

** Origine

Le point $A$ est appelé origine de la demi-droite $[AB)$.

** Ouverte ou fermée

Il existe plusieurs variantes de demi-droite :

- un demi-droite est dite fermée si elle contient son origine $A$
  + on la note $[AB)$
- un demi-droite est dite ouverte si elle ne contient pas son origine $A$
  + on la note $]AB)$

* Segment

Si on coupe une droite $(AB)$ au niveau des points $A$ et $B, et que
l’on conserve la partie située entre $A$ et $B$, on obtient un
segment $[A,B]$.

Le schéma ci-dessous donne un exemple de segment :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/segment.svg]]

Il existe plusieurs variantes de segments :

- le segment $[A,B]$ contient les deux extrémités $A$ et $B$
- le segment $]A,B[$ ne contient ni $A$ ni $B$
- le segment $[A,B[$ contient $A$ mais pas $B$
- le segment $]A,B]$ contient $B$ mais pas $A$

** Longueur et distance

Nous avons vu que la distance entre deux points $A$ et $B$ est égale
à la longueur de la ligne droite qui sépare ces deux points. Cette
distance est donc égale à la longueur du segment $[A,B]$ :

$$ \abs{AB} = \Bigl|[A,B]\Bigr| $$

* Cercle

#+TOC: headlines 1 local

** Définition

Un cercle $\mathscr{C}$ de centre $C$ et de rayon $r$ est l’ensemble
des points situés à une distance $r$ de $C$.

** Périmètre

Le schéma ci-dessous représenté un cercle $\mathscr{C}$ de centre $O$,
de rayon $r$ et de diamètre $d$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-pi.svg]]

Le nombre pi, noté $\pi$, se définit comme étant le rapport constant
entre le périmètre du cercle et son diamètre. Si $p$ est le périmètre
de $\mathscr{C}$, on a donc :

$$ \pi = \frac{p}{d} $$

ou encore :

$$ p = \pi \ d $$

Comme le diamètre vaut deux fois le rayon $r$ :

$$ d = 2 \ r $$

on en déduit la forme alternative :

$$ p = 2 \ \pi \ r $$

