
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Géométrie différentielle
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:geometri}

* Dépendances

  - Chapitre \ref{chap:vecteur} : Les vecteurs
  - Chapitre \ref{chap:ps} : Les produits scalaires
  - Chapitre \ref{chap:tenseur} : Les tenseurs

* Indices covariants et contravariants

Les indices inférieurs (le $i$ des vecteurs $a_i^j$ par exemple) des
tenseurs sont appelés /indices covariants/.

Les indices supérieurs (le $j$ des vecteurs $a_i^j$ par exemple) des
tenseurs sont appelés /indices contravariants/.

Ne pas confondre ces /indices supérieurs/ contravariants , très
utilisés en calcul tensoriel, avec les puissances ! Dans le contexte
des tenseurs, une éventuelle puissance d'un scalaire $\theta_i^j$
serait notée au besoin par :

$$\big( \theta_j^i \big)^m = \theta_j^i \cdot ... \cdot \theta_j^i$$


* Coordonnées curvilignes

Soit l'espace vectoriel $E = \setR^n$ sur $\setR$. Les coordonnées curvilignes sont basées sur la notion de position $r$, exprimée comme une fonction de certains paramètres $x \in \setR^n$ que nous appelons « coordonnées » de $r$ :

$$r = \rho(x)$$

où $\rho : \setR^n \to \setR^n$. Nous envisageons également le cas du changement de variable. La position dépend alors d'un autre jeu de coordonnées $y \in \setR^n$ :

$$r = \sigma(y)$$

où $\sigma : \setR^n \to \setR^n$. Nous définissons les vecteurs fondamentaux $e_i$ et $e^i$ au moyen de ces fonctions :

#+BEGIN_CENTER
\(
e_i(x) = \deriveepartielle{\rho}{x^i}(x) \)

\(
e^i(y) = \deriveepartielle{\sigma}{y_i}(y)
\)
#+END_CENTER

de telle sorte que :

$$dr = \sum_i e_i \ dx^i  = \sum_i e^i \ dy_i$$

Nous supposons que $(e_1, ..., e_n)$ et $(e^1, ..., e^n)$ sont des bases de $E$.


** Courbe

Dans le cas où $x$ et $y$ ne dépendent que d'un paramètre $t \in \setR$, on a :

$$\OD{r}{t} = \sum_i e_i \ \OD{x^i}{t}  = \sum_i e^i \ \OD{y_i}{t}$$

On dit alors que la position $r$ décrit une courbe.


* Changement de variable

Si les fonctions $\rho$ et $\sigma$ sont inversibles, on a :

#+BEGIN_CENTER
\(
x = \rho^{-1}(r) = (\rho^{-1} \circ \sigma)(y) = \phi(y) \)

\(
y = \sigma^{-1}(r) = (\sigma^{-1} \circ \rho)(x) = \psi(x)
\)
#+END_CENTER

où nous avons implicitement défini $\phi = \rho^{-1} \circ \sigma$ et $\psi = \sigma^{-1} \circ \rho$. Nous notons $\deriveepartielle{x^i}{y_j}$ et $\deriveepartielle{y_i}{x^j}$ les coordonnées des dérivées de $\phi$ et $\psi$ suivant les bases formées par les $e_i$ et les $e^i$ :

#+BEGIN_CENTER
\(
\deriveepartielle{\phi}{y_j} = \sum_i \deriveepartielle{x^i}{y_j} \ e_i \)

\(
\deriveepartielle{\psi}{x^j} = \sum_i \deriveepartielle{y_i}{x^j} \ e^i
\)
#+END_CENTER

La composition des dérivées nous donne les relations :

#+BEGIN_CENTER
\(
e_i = \sum_j \deriveepartielle{r}{y_j} \ \deriveepartielle{y_j}{x^i} =  \sum_j \deriveepartielle{y_j}{x^i} \ e^j \)

\(
e^i = \sum_j \deriveepartielle{r}{x^j} \ \deriveepartielle{x^j}{y_i} =  \sum_j \deriveepartielle{x^j}{y_i} \ e_j
\)
#+END_CENTER

qui nous permettent de relier les $e_i$ aux $e^j$ et inversément.


* Produit scalaire

Les produits intérieurs entre vecteurs de base se notent habituellement :

#+BEGIN_CENTER
\(
g_{ij} = \scalaire{e_i}{e_j} \)

\(
g_i^j = \scalaire{e_i}{e^j} \)

\(
g^{ij} = \scalaire{e^i}{e^j}
\)
#+END_CENTER

Il est clair d'après les propriétés de symétrie de ce produit que :

#+BEGIN_CENTER
\(
g_{ij} = g_{ji} \)

\(
g^{ij} = g^{ji} \)

\(
g_i^j = g_j^i
\)
#+END_CENTER

Le produit scalaire de deux vecteurs $a,b\in E$ définis par :

#+BEGIN_CENTER
\(
a = \sum_i a^i \ e_i = \sum_i a_i \ e^i \)

\(
b = \sum_i b^i \ e_i = \sum_i b_i \ e^i
\)
#+END_CENTER

peut s'écrire indifféremment comme :

#+BEGIN_CENTER
\(
\scalaire{a}{b} = \sum_{i,j} g_{ij} \ a^i \ b^j \)

\(
\scalaire{a}{b} = \sum_{i,j} g^{ij} \ a_i \ b_j \)

\(
\scalaire{a}{b} = \sum_{i,j} g_j^i \ a_i \ b^j \)

\(
\scalaire{a}{b} = \sum_{i,j} g_i^j \ a^i \ b_j
\)
#+END_CENTER

Et en particulier, la longeur $ds$ d'un changement de position $dr$ vérifie :

$$(ds)^2 = \scalaire{dr}{dr} = \sum_{i,j} g_{ij} \ dx^i \ dx^j = \sum_{i,j} g^{ij} \ dy_i \ dy_j$$

De plus, les relations entre les vecteurs $e_i$ et les vecteurs $e^i$ permettent
de déduire, en utilisant la linéarité du produit scalaire :

#+BEGIN_CENTER
\(
g_{ij} = \sum_k \deriveepartielle{y_k}{x^i} \ g_j^k = \sum_{k,l} \deriveepartielle{y_k}{x^i} \ \deriveepartielle{y_l}{x^j} \ g^{kl} \)

\(
g^{ij} = \sum_k \deriveepartielle{x_k}{y^i} \ g_k^j = \sum_{k,l} \deriveepartielle{x^k}{y_i} \ \deriveepartielle{x^l}{y_j} \ g_{kl}
\)
#+END_CENTER


* Dérivées primales d'un vecteur

Nous allons à présent voir comment évolue un vecteur $a\in E$, que l'on note sous la forme :

$$a = \sum_i a^i \ e_i$$

où les coordonnées $a^i\in\setR$ tout comme les vecteurs de base $e_i$ dépendent des coordonnées
$x^i$. La règle de dérivation d'un produit nous donne :

$$da = \sum_i da^i \ e_i + \sum_k a^k \ de_k$$

La différentielle $da^i$ s'obtient directement :

$$da^i = \sum_j \deriveepartielle{a^i}{x^j} \ dx^j$$

On peut suivre la même règle avec $de_i$ :

$$de_k = \sum_j \deriveepartielle{e_k}{x^j} \ dx^j$$

Les symboles de Christoffel $\christoffel{i}{kj}$ sont définis comme
les coordonnées de $\deriveepartielle{e_k}{x^j}$ suivant la base $(e_1, ..., e_n)$ :

$$\deriveepartielle{e_k}{x^j} = \sum_i \christoffel{i}{kj} \ e_i$$

Notons que comme :

$$\deriveepartielle{e_k}{x^j} = \dfdxdy{r}{x^j}{x^k} = \dfdxdy{r}{x^k}{x^j} = \deriveepartielle{e_j}{x^k}$$

on a la symétrie :

$$\christoffel{i}{kj} = \christoffel{i}{jk}$$

On peut évaluer ces symboles si on connait par exemple les valeurs des :

\begin{align}
\scalaire{e^i}{ \deriveepartielle{e_k}{x^j} } &= \sum_m \christoffel{m}{kj} \ \scalaire{e^i}{e_m} \)

\(
&= \sum_m \christoffel{m}{kj} \ g^i_m
\end{align}

On a alors, pour chaque choix de $k,j$ un système linéaire à résoudre. Il suffit d'inverser
la matrice $G = (g^i_m)_{i,m}$ pour obtenir les valeurs des symboles.

La dérivation d'un vecteur $a\in E$ s'écrit alors :

$$da = \sum_{i,j} e_i \ dx^j \ \left[ \deriveepartielle{a^i}{x^j} + \sum_k \christoffel{i}{kj} \ a^k  \right]$$

On définit les coordonnées :

$$\gradient_j a^i = \deriveepartielle{a^i}{x^j} + \sum_k \christoffel{i}{kj} \ a^k$$

Dans le cas où les coordonnées dépendent d'un paramètre $t\in\setR$, on a :

\begin{align}
\OD{a}{t} &= \sum_{i,j} e_i \ \OD{x^j}{t} \ \left[ \deriveepartielle{a^i}{x^j} + \sum_k \christoffel{i}{kj} \ a^k  \right] \)

\(
&= \sum_{i} e_i \ \left[ \OD{a^i}{t} + \sum_{j,k} \christoffel{i}{kj} \ a^k \ \OD{x^j}{t} \right]
\end{align}


** Dérivée seconde et géodésique

Considérons le cas :

$$a = \OD{r}{t} = \sum_i e_i \ \OD{x^i}{t}$$

Les coordonnées de $a$ sont clairement $a^i = \OD{x^i}{t}$ et la dérivée seconde :

$$\OOD{r}{t} = \OD{}{t}\OD{r}{t} = \OD{a}{t}$$

s'écrit :

$$\OOD{r}{t} = \sum_{i} e_i \ \left[ \OOD{x^i}{t} + \sum_{j,k} \christoffel{i}{kj} \ \OD{x^k}{t}\ \OD{x^j}{t} \right]$$

Les courbes $x^i = x^i(t)$ vérifiant $\OOD{r}{t} = 0$ sont appelées des géodésiques.


* Dérivées duales d'un vecteur

Nous allons recommencer le même processus, écrivant cette fois  $a\in E$ sous la forme :

$$a = \sum_i a_i \ e^i$$

Les coordonnées $a_i\in\setR$ tout comme les vecteurs de base $e^i$ dépendent des coordonnées
$y_i$. En suivant la même méthode que ci-dessus, on obtient :

$$da = \sum_{i,j} e^i \ dy_j \left[ \deriveepartielle{a_i}{y_j} + \sum_k \christoffel{kj}{i} \ a_k  \right]$$


où l'on a introduit de nouveaux symboles de Christoffel, définis par :

$$\deriveepartielle{e^k}{y_j} = \sum_i \christoffel{kj}{i} \ e^i$$

Ces nouveaux symboles présentent la symétrie :

$$\christoffel{kj}{i} = \christoffel{jk}{i}$$


* Dérivées d'un tenseur

On étend simplement la notion de dérivée aux tenseurs en appliquant
la formule :

$$d(a \otimes b) = da \otimes b + a \otimes db$$

où $a$ et $b$ sont deux tenseurs d'ordre quelconque.
Par exemple, pour le tenseur :

$$T = \sum_{i,j} T^i_j \ e_i \otimes e^j$$

on a :

$$dT = \sum_{i,j} \left[ dT^i_j \ e_i \otimes e^j + T^i_j \ de_i \otimes e^j + T^i_j \ e_i \otimes de^j \right]$$

qui devient, en introduisant les symboles de Christoffel :

$$dT = \sum_{i,j} e_i \otimes e^j \left[ dT^i_j + \sum_{k,m} \christoffel{i}{mk} \ T^m_j \ dx^k + \sum_{k,m} \christoffel{mk}{j} \ T^i_m \ dy_k \right]$$


* Produit scalaire et symboles de Christoffel

Lorsqu'on différentie les $g_{ij}$, on obtient :

\begin{align}
dg_{ij} &= \scalaire{de_i}{e_j} + \scalaire{e_i}{de_j} \)

\(
&= \sum_{k,l} \christoffel{k}{il} \ g_{kj} \ dx^l + \sum_{k,l} \christoffel{k}{jl} \ g_{ik} \ dx^l
\end{align}

On en déduit que :

$$\deriveepartielle{g_{ij}}{x^l} = \sum_k \christoffel{k}{il} \ g_{kj} + \sum_k \christoffel{k}{jl} \ g_{ik}$$

Définissons :

$$\gamma_{ijl} = \sum_k \christoffel{k}{il} \ g_{kj}$$

Les propriétés de symétrie des symboles de Christoffel nous montrent que :

$$\gamma_{ijl} = \gamma_{ilj}$$

Et comme (changement de l'indice $l$ en $k$) :

$$\deriveepartielle{g_{ij}}{x^k} = \gamma_{ijk} + \gamma_{jik}$$

On en déduit :

\begin{align}
\deriveepartielle{g_{ij}}{x^k} + \deriveepartielle{g_{jk}}{x^i} - \deriveepartielle{g_{ki}}{x^j}
&= 2 \ \gamma_{jik} \)

\(
&= 2 \sum_l \christoffel{l}{jk} \ g_{li}
\end{align}

AFAIRE : LA FIN DU CHAPITRE EST A DÉBROUILLONNER


* Bases biorthonormées


** produit scalaire

Nous considérons tout au long de cette section le cas particulier où les bases
sont biorthonormées, c'est-à-dire :

$$g_i^j = \indicatrice_i^j$$

On déduit des relations liant les $g^{ij},g_{ij}$ aux $g_i^j$ que :

#+BEGIN_CENTER
\(
g_{ik} g^{kj} = \sum_{k,l,m} \deriveepartielle{y_l}{x^i}\deriveepartielle{x^m}{y_k} g_k^l g_m^j \)

\(
g_{ik} g^{kj} = \sum_{k,l,m} \deriveepartielle{y_l}{x^i}\deriveepartielle{x^m}{y_k} \indicatrice_k^l \indicatrice_m^j \)

\(
g_{ik} g^{kj} = \sum_{k} \deriveepartielle{y_k}{x^i}\deriveepartielle{x^j}{y_k} \)

\(
g_{ik} g^{kj} = \deriveepartielle{x^i}{x^j} = \indicatrice_i^j
\)
#+END_CENTER

On aurait de même :

$$g^{ik} g_{kj} = \indicatrice_j^i$$


** Coordonnées

Les coordonnées d'un tenseur de la forme :

$$T = \sum_{i,j,k,l} T_{i...j}^{k...l} e^i \otimes ... \otimes e^j \otimes e_k \otimes ... \otimes e_l$$

où il y a $m$ indices $i...j$ et $n$ indices $k...l$ s'obtiennent facilement
en utilisant la contraction double :

$$T_{i...j}^{k...l} = \dblecont{e_j \otimes ... \otimes e_i}{m}{T}{n}{e^l \otimes ... \otimes e^k}$$


* Dérivées des changements de variable

#+BEGIN_CENTER
\(
\deriveepartielle{x^i}{y_j} = \scalaire{e_i}{ \deriveepartielle{\phi}{y_j} } \)

\(
\deriveepartielle{y_i}{x^j} = \scalaire{e^i}{ \deriveepartielle{\psi}{x^j} }
\)
#+END_CENTER


** Christoffel

Tenant compte de cette identité, l'équation reliant les symboles de Christoffel
aux produits scalaires devient :

$$\christoffel{m}{jk} = \frac{1}{2}\sum_i g^{im}\left[\deriveepartielle{g_{ij}}{x^k} + \deriveepartielle{g_{jk}}{x^i} - \deriveepartielle{g_{ki}}{x^j}\right]$$


** Dérivée d'un vecteur

La relation :

$$d\scalaire{e^i}{e_j} = d\indicatrice_i^j = 0$$

nous conduit à :

#+BEGIN_CENTER
\(
\scalaire{de^i}{e_j}+\scalaire{e^i}{de_j} = 0 \)

\(
\sum_{k,l} \christoffel{ik}{l} \scalaire{e^l}{e_j} dy_k +
\sum_{k,l} \christoffel{l}{jk} \scalaire{e^i}{e_l} dx^k = 0 \)

\(
\sum_k \christoffel{ik}{l} dy_k = - \sum_k \christoffel{l}{jk} dx^m
\)
#+END_CENTER

Par ailleurs :

$$da_i = \deriveepartielle{a_i}{y_j} dy_j = \deriveepartielle{a_i}{x^j} dx^j$$

On peut donc réexprimer la dérivée duale comme :

$$da = \sum_{i,j} e^i dx^j \left[ \deriveepartielle{a_i}{x^j} - \sum_k \christoffel{k}{ij} a_k \right]$$


** Gradient

On peut également définir le gradient d'un vecteur par :

$$\gradient a = \sum_{i,j} \gradient_j a^i e_i \otimes e^j$$

de telle sorte que l'on ait :

$$da = \scalaire{\gradient a}{dr} = \gradient a \cdot dr$$



** Dérivée d'un tenseur

$$dT = \sum_{i,j,k} e_i \otimes e^j dx^k \left[ \deriveepartielle{T^i_j}{x^k} + \sum_m \christoffel{i}{mk} T^m_j - \sum_m \christoffel{m}{jk} T^i_m \right]$$

On définit alors les coordonnées :

$$\gradient_k T^i_j = \deriveepartielle{T^i_j}{x^k} + \sum_m \christoffel{i}{mk} T^m_j - \sum_m \christoffel{m}{jk} T^i_m$$


** Tenseur de courbure

Appliquons la formule de dérivation des coordonnées d'un tenseur dans le cas particulier où :

$$T^i_j = \gradient_j a^i$$

On a :

#+BEGIN_CENTER
\(
\deriveepartielle{T^i_j}{x^k} = \dfdxdy{a^i}{x^j}{x^k}
+ \sum_m \christoffel{i}{jm} \deriveepartielle{a^m}{x^k}
+ \sum_m \deriveepartielle{}{x^k}\christoffel{i}{jm} a^m \\ \)

\(

\sum_l \christoffel{i}{kl} T^l_j =
\sum_l \christoffel{i}{kl} \deriveepartielle{a^i}{x^j} +
\sum_{l,m} \christoffel{i}{kl} \christoffel{l}{jm} a^m \\ \)

\(

-\sum_l \christoffel{l}{jk} T^i_l =
-\sum_l \christoffel{l}{jk} \deriveepartielle{a^i}{x^l} -
\sum_{l,m} \christoffel{l}{jk} \christoffel{i}{lm} a^m
\)
#+END_CENTER

La somme de tous ces termes vaut $\gradient_k T^i_j = \gradient_k \gradient_j a^i$.
En interchangeant les indices $j$ et $k$, on obtient $\gradient_j \gradient_k a^i$.
On en déduit, en utilisant les propriétés de symétrie que :

$$\gradient_k \gradient_j a^i - \gradient_j \gradient_k a^i = \sum_m R^i_{m,kj} a^m$$

où les $R_{...}^{...}$ sont définis par :

$$R^i_{m,kj} = \deriveepartielle{}{x^k}\christoffel{i}{jm} - \deriveepartielle{}{x^j}\christoffel{i}{km} + \sum_l \christoffel{i}{kl}\christoffel{l}{jm} - \sum_l \christoffel{i}{jl}\christoffel{l}{km}$$

Ce sont les coordonnées du tenseur de courbure de Riemann-Christoffel.


