
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Hexagone régulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles formés par les rayons

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les rayons de
$\mathscr{C}$ reliant le centre aux sommets de l’hexagone, découpant
ainsi la figure en six triangles intérieurs :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-triangles-rayons.svg]]

Nous avons tenu compte du caractère isocèle des triangles intérieurs
dans la notation des angles.

Dans les triangles $P_1 P_2 O$ et $P_2 P_3 O$ on a :

$$ \abs{P_1 P_2} = \abs{P_2 P_3} $$

car l’hexagone est régulier et :

$$ \abs{O P_1} = \abs{O P_2} = r $$

$$ \abs{O P_2} = \abs{O P_3} = r $$

par définition du cercle circonscrit. Ces triangles ont leurs trois
côtés de mêmes longueurs et sont donc isométriques. Un raisonnement
analogue nous montre que tous les triangles intérieurs de l’hexagone
sont isométriques. On a en particulier :

$$ \alpha_1 = \alpha_2 = \ldots = \alpha_6 $$

$$ \beta_1 = \beta_2 = \ldots = \beta_6 $$

Posons :

$$ \alpha = \alpha_1 $$

$$ \beta = \beta_1 $$

Les angles $\alpha_1$, $\alpha_2$, $\ldots$, $\alpha_6$ forment ensemble
un tour complet :

$$ \sum_{i=1}^6 \alpha_i = 6 \ \alpha = 2 \ \pi $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{2 \ \pi}{6} = \frac{\pi}{3} = 60^\circ $$

La somme des angles dans le triangle $P_1 P_2 O$ nous donne :

$$ \alpha + 2 \ \beta = 60^\circ + 2 \ \beta = 180^\circ $$

En isolant $\beta$, on obtient :

$$ \beta = \frac{180^\circ - 60^\circ}{2} = 60^\circ $$

Les triangles intérieurs ont donc leurs trois angles de même amplitude :

$$ \alpha = \beta = 60^\circ $$

Ce sont donc des triangles équilatéraux. On en déduit que le côté $c$
de l’hexagone régulier est de même longueur que le rayon du cercle
circonscrit :

$$ c = r $$

Ce résultat montre aussi que les angles internes d’un hexagone valent :

$$ 2 \ \beta = 120^\circ $$

Le schéma devient donc :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-triangles-rayons-resolu.svg]]

** Diamètres

On remarque que :

$$ \abs{\angleflex{P_1 O P_4}} = 3 \ \alpha = 180^\circ $$

Les points $O$, $P_1$ et $P_4$ sont alignés, ce qui signifie que $O$
se situe sur la diagonale $[P_1, P_4]$. Cette diagonale est donc un
diamètre du cercle $\mathscr{C}$.

Un raisonnement similaire nous montre que le centre du cercle circonscrit
est situé sur toutes les diagonales qui sautent deux sommets de
l’hexagone régulier :

$$ [P_1, P_4]
\qquad \qquad \qquad
[P_2, P_5]
\qquad \qquad \qquad
[P_3, P_6] $$

Ces diagonales sont donc aussi des diamètres du cercle.

* Triangle rectangle

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-triangle-rectangle.svg]]

Le côté $[P_1, P_4]$ du triangle $P_1 P_3 P_4$ est un diamètre du
cercle. Ce triangle est donc un triangle rectangle :

$$ \angleflex{P_4 P_3 P_1} = 90^\circ $$

Comme :

$$ \abs{P_1 P_4} = \abs{P_1 O} + \abs{O P_4} = r + r = 2 \ r $$

le théorème de Pythagore nous donne :

$$ (2 \ r)^2 = r^2 + L^2 $$

ou encore :

$$ 4 \ r^2 = r^2 + L^2 $$

Isolons $L^2$ :

$$ L^2 = 4 \ r^2 - r^2 = 3 \ r^2 $$

En prenant la racine, on obtient :

$$ L = r \ \sqrt{3} $$

Un raisonnement similaire nous montre que toutes les diagonales qui sautent
un sommet de l’hexagone régulier sont de longueur $r \ \sqrt{3}$ :

$$ [P_1, P_3]
\qquad \qquad \qquad
[P_3, P_5]
\qquad \qquad \qquad
[P_5, P_1] $$

$$ [P_2, P_4]
\qquad \qquad \qquad
[P_4, P_6]
\qquad \qquad \qquad
[P_6, P_2] $$

* Grand triangle équilatéral
:properties:
:custom_id: heading:grand_triangle_equilateral
:end:

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les diagonales
$[P_1, P_3]$, $[P_3, P_5]$ et $[P_5, P_1]$ qui sautent chacune un sommet
de l’hexagone :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-grand-triangle-equilateral.svg]]

Nous avons tenu compte du caractère isocèle des triangles dans la
notation des angles.

Comme :

$$ \abs{P_1 P_3} = \abs{P_3 P_5} = \abs{P_5 P_1} = r \ \sqrt{3} $$

le triangle $P_1 P_3 P_5$ est équilatéral. Ses angles valent donc
$60^\circ$.

La somme des angles du triangle isocèle $P_1 P_2 P_3$ nous donne :

$$ 2 \ \alpha + 120^\circ = 180^\circ $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{180^\circ - 120^\circ}{2} = 30^\circ $$

Un raisonnement similaire nous montre le même résultat pour les autres
triangles isocèles entourant le grand triangle équilatéral. Ces
triangles ont donc un angle de $120^\circ$ et deux angles de $30^\circ$.

Notre schéma devient :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-grand-triangle-equilateral-resolu.svg]]

* Cerf-volant

#+TOC: headlines 1 local

** Introduction

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Si on trace un grand triangle
équilatéral $P_1 P_3 P_5$ composé de diagonales, on voit se former
le cerf-volant $P_1 P_3 P_4 P_5$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-cerf-volant.svg]]

Nous avons tenu compte dans la notation des angles :

- des résultats précédents concernant l’hexagone régulier
- des propriétés du cerf-volant, et en particulier de ses diagonales

On définit :

$$ a = \abs{I P_3}
\qquad \qquad \qquad
b = \abs{I P_1}
\qquad \qquad \qquad
c = \abs{I P_4} $$

La diagonale $[P_1, P_4]$ du cerf-volant traverse les deux triangles
isocèles qui le composent. Ce segment est donc :

- la médiatrice de l’autre diagonale $[P_3, P_5]$ :
- la bissectrice des angles $\angleflex{P_3 P_1 P_5}$ et $\angleflex{P_5 P_4 P_3}$

** Longueurs

- Par définition de la médiatrice, on a :

$$ a = \abs{I P_3} = \abs{I P_5} $$

et :

$$ \abs{P_3 P_5} = \abs{I P_3} + \abs{I P_5} = 2 \ a $$

Comme $[P_3, P_5]$ est un côté du grand triangle équilatéral, sa
longueur vaut :

$$ \abs{P_3 P_5} = r \ \sqrt{3} $$

On en déduit que :

$$ 2 \ a = r \ \sqrt{3} $$

d’où :

$$ a = \frac{r \ \sqrt{3}}{2} $$

- Le théorème de Pythagore appliqué au triangle $P_3 P_4 I$ nous donne :

$$ a^2 + c^2 = r^2 $$

Remplaçons $a$ par sa valeur :

$$ \left( \frac{r \ \sqrt{3}}{2} \right)^2 + c^2 = \frac{3 \ r^2}{4} + c^2 = r^2 $$

Isolons $c^2$ :

$$ c^2 = r^2 - \frac{3 \ r^2}{4} = \frac{r^2}{4} $$

et prenons la racine carrée :

$$ c = \frac{r}{2} $$

La longueur $c$ vaut la moitié de $r$. La diagonale $[P_3, P_5]$ coupe
donc en deux parties égales le rayon $[O, P4]$ qui passe par le sommet
intermédiaire $P_4$.

- Comme $[P_1, P_4]$ est un diamètre, on a :

$$ b + c = \abs{P_1 P_4} = 2 \ r $$

Remplaçons $c$ par sa valeur :

$$ b + \frac{r}{2} = 2 \ r $$

En isolant $b$ :

$$ b = 2 \ r - \frac{r}{2} = \frac{4 \ r - r}{2} $$

on obtient :

$$ b = \frac{3 \ r}{2} $$

** Angles

Puisque $[P_1, P_4]$ est la bissectrice de l’angle $\angleflex{P_3
P_1 P_5}$ du grand triangle équilatéral, on a :

$$ 2 \ \alpha = 60^\circ $$

c’est-à-dire :

$$ \alpha = \frac{60^\circ}{2} = 30^\circ $$

** Conclusion

Les diamètres du cercle circonscrit passant par les sommets de l’hexagone sont
les médiatrices et les bissectrices des grands triangles équilatéraux.

Comme les rayons sont inclus dans les diamètres, les rayons du cercle
circonscrit passant par les sommets de l’hexagone sont également les
médiatrices et les bissectrices des grands triangles équilatéraux.

Les diagonales sautant un sommet de l’hexagone coupent en deux
parties égales le rayon du cercle circonscrit qui passe par le sommet
intermédiaire.

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-cerf-volant-resolu.svg]]

* Hexagramme

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Si on trace toutes les
diagonales qui sautent chacune un sommet de l’hexagone, on obtient
deux triangles équilatéraux entrecroisés. Cette figure est appelée
un hexagramme :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme.svg]]

* Diagonales

Le schéma ci-dessous représente un hexagone régulier muni de toutes ses
diagonales, les diamètres du cercle et les deux grands triangles formant
un hexagramme :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-diagonales.svg]]

Le cercle est de rayon $r$. On définit les distances :

$$ a = \abs{CG}
\qquad \qquad \qquad
b = \abs{GE} $$

$$ c = \abs{OG}
\qquad \qquad \qquad
d = \abs{GD} $$

Par symétrie, on a :

$$ a = b
\qquad \qquad \qquad
\delta = \epsilon $$

$$ \alpha = \beta
\qquad \qquad \qquad
\lambda = \mu $$

Intéressons-nous à présent au triangle $CGO$.  On constate que $\delta$
et $\epsilon$ forment ensemble un angle plat de $180^\circ$ :

$$ \delta + \epsilon = 180^\circ $$

Comme ces deux angles sont égaux, on a :

$$ 2 \ \delta = 180^\circ $$

c’est-à-dire :

$$ \delta = 90^\circ $$

Le triangle $CGO$ est donc un triangle rectangle dont l’hypothénuse
vaut :

$$ \abs{OE} = r $$

** Angles

Les angles non droits du triangle rectangle $CGO$ étant complémentaires,
on a :

$$ \alpha = 90^\circ - 60^\circ = 30^\circ $$

Comme l’angle $\alpha + \lambda$ est l’un des angles du triangle
équilatéral $OCD$, on a :

$$ \alpha + \lambda = 60^\circ $$

c’est-à-dire :

$$ \lambda = 60^\circ - \alpha = 60^\circ - 30^\circ = 30^\circ $$

et :

$$ \mu = \lambda = 30^\circ $$

On a donc finalement :

$$ \alpha = \beta = \lambda = \mu = \frac{\pi}{6} = 30^\circ $$

** Longueurs

Le triangle $CGO$ étant un triangle rectangle, on a :

$$ a = r \ \sin 60^\circ = r \ \frac{\sqrt{3}}{2} $$

La longueur $L$ du côté $[C,E]$ du triangle $ACE$ vaut donc :

$$ L = \abs{EC} = a + b = 2 \ a $$

c’est-à-dire :

$$ L = r \ \sqrt{3} $$

La longueur du plus petit côté du triangle $CGO$ vaut :

$$ c = r \ \cos 60^\circ = \frac{r}{2} $$

Comme :

$$ c + d = \abs{OD} = r $$

on a aussi :

$$ d = r - c = r - \frac{r}{2} = \frac{r}{2} $$

Le segment $[C,E]$ divise le rayon $[O,D]$ en deux.

** Conclusion

Par symétrie, on peut appliquer le même raisonnement aux autres côtés
du triangle $ACE$, et ainsi montrer que le triangle $ACE$ est un triangle
équilatéral de côté $L = r \ \sqrt{3}$.

Il en va de même pour le triangle $DFB$. Les deux grands triangles
formant l’hexagramme, $ACE$ et $DFB$, sont donc équilatéraux.

Par symétrie et invariance sous rotation d’un sixième de tour
($60^\circ$), il est clair que le triangle équilatéral $ACE$ contient
six triangles isométriques à $CGO$ (en incluant $CGO$ lui-même). Ces
triangles possèdent donc les mêmes angles et les mêmes longueurs
de côtés.

Soit $T$ un des deux triangles équilatéraux $ACE$ ou $DFB$
formant l’hexagramme. Nous avons montré que :

- les rayons du cercle divisent les angles de $T$ en deux angles égaux
  de $30^\circ$
- les angles situés entre les pointes de $T$ et les côtés de l’hexagone
  sont également de $30^\circ$
- les côtés de $T$ divisent les rayons du cercle en deux parties
  égales de longueur $r/2$
- réciproquement, les rayons du cercle divisent les côtés de $T$
  en deux parties égales de longueur $r \ \sqrt{3} / 2$

Le schéma devient :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-diagonales-resolu.svg]]

* Hexagramme ancien

Le schéma ci-dessous représente un hexagone régulier muni de toutes ses
diagonales, les diamètres du cercle et les deux grands triangles formant
un hexagramme :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-ancien.svg]]

Nous avons tenu compte de la symétrie dans la notation des longueurs
et des angles.

Le cercle est de rayon $r$. On définit les distances :

$$ a = \abs{HD}
\qquad \qquad \qquad
c = \abs{HG} $$

** Triangles compris entre l’hexagramme et les côtés de l’hexagone

Examinons à présent le triangle $CJB$. Nous avons vu précédemment
que les angles compris entre les triangles de l’hexagramme ($ACE$
et $DFB$) et les côtés de l’hexagone valent $30^\circ$. On a donc :

$$ \lambda = 30^\circ $$

Le troisième angle $\theta$ vaut donc :

$$ \theta = 180^\circ - 2 \cdot 30^\circ = 120^\circ $$

Les cinq autres triangles compris entre les côtés de l’hexagone et
l’hexagramme sont par symétrie isométriques à $CJB$.

** Pointes de l’hexagramme

Examinons à présent les triangles formés aux pointes de l’hexagramme.

Le triangle $DFB$ étant équilatéral, ses angles valent $60^\circ$
et en particulier :

$$ \gamma = 60^\circ $$

La somme des angles dans le triangle $HID$ nous donne :

$$ 2 \ \alpha + \gamma = 2 \ \alpha + 60^\circ = 180^\circ $$

c’est-à-dire :

$$ \alpha = \frac{180^\circ - 60^\circ}{2} = 60^\circ $$

Le triangle $HID$ est donc aussi un triangle équilatéral et :

$$ a = 2 \ c $$

La longueur du côté $[E,C]$ peut s’écrire :

$$ 2 \ a + 2 \ c = 2 \ a + a = 3 \ a $$

Or, $[E,C]$ est un des côtés du triangle équilatéral $ACE$ et est
donc de longueur $r \ \sqrt{3}$ :

$$ 3 \ a = r \ \sqrt{3} $$

ce qui nous donne la valeur de $a$ :

$$ a = r \ \frac{\sqrt{3}}{3} $$

La longueur du troisième côté du triangle $HID$ vaut :

$$ \abs{HI} = 2 \ c = a = r \ \frac{\sqrt{3}}{3} $$

Les côtés du triangle $DFB$ divisent en trois parties égale
le côté $[E,C]$ du triangle $ACE$.

** Conclusion

Les triangles compris entre les côtés de l’hexagone et l’hexagramme
ont des angles aigus de $30^\circ$ et un angle obtus de $120^\circ$.

Les pointes de l’hexagramme sont des triangles équilatéraux de
côté $r \ \sqrt{3}/3$, c’est-à-dire le tiers du côté des triangles
formant l’hexagramme.

Soit $T_1$ et $T_2$ les deux triangles formant l’hexagramme.
Les côtés de $T_1$ divisent en trois parties égales les côtés de
$T_2$, et vice versa.

Le schéma devient :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-resolu-ancien.svg]]

* Nombre d’or

Le schéma ci-dessous représente un hexagone régulier muni de ses
diagonales :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-nombre-d-or.svg]]

Nous avons tenu compte de la symétrie dans la notation des longueurs
et des angles.

Le cercle est de rayon $r$. On définit les distances :

\begin{align*}
a &= \abs{OI} \\
b &= \abs{GI} = \abs{IH} \\
c &= \abs{OG} = \abs{OH} \\
d &= \abs{IJ} \\
e &= \abs{GH} \\
f &= \abs{GJ}
\end{align*}

Nous avons vu précédemment que les côtés des grands triangles
équilatéraux formant l’hexagramme coupent le rayon en deux parties
égales. On a donc :

$$ c = \frac{r}{2} $$

** Triangles rectangles

Les deux angles $\delta$ forment ensemble un angle plat :

$$ 2 \ \delta = 180^\circ $$

d’où :

$$ \delta = 90^\circ $$

Les triangles $GOI$, $OHI$ et $OJI$ sont donc des triangles rectangles.

*** Triangle $OHI$

Dans le triangle rectangle $OHI$, on a par définition du cosinus :

$$ a = c \ \cos 60^\circ = \frac{r}{2} \ \cos 60^\circ $$

Comme le cosinus de $60^\circ$ vaut $1/2$, cette équation devient :

$$ a = \frac{r}{2} \cdot \unsur{2} = \frac{r}{4} $$

Le sinus nous donne :

$$ b = c \ \sin 60^\circ = \frac{r}{2} \ \sin 60^\circ $$

Comme le cosinus de $60^\circ$ vaut $\sqrt{3}/2$, cette équation devient :

$$ b = \frac{r}{2} \cdot \frac{\sqrt{3}}{2} = \frac{r \ \sqrt{3}}{4} $$

*** Triangle $OJI$

Dans le triangle $OJI$, le théorème de Pythagore s’écrit :

$$ r^2 = a^2 + d^2 $$

Comme $a = r/4$, cette relation devient :

$$ r^2 = \frac{r^2}{16} + d^2 $$

Isolons $d^2$ :

$$ d^2 = r^2 - \frac{r^2}{16} $$

Mettons les membres de drotie au même dénominateur :

$$ d^2 = \frac{16 \ r^2 - r^2}{16} = \frac{15 \ r^2}{16} $$

Il ne nous reste plus qu’à prendre la racine carrée :

$$ d = \frac{r \ \sqrt{15}}{4} $$

** Sommes

On a :

$$ f = b + d = \frac{r \ \sqrt{3}}{4} + \frac{r \ \sqrt{15}}{4} $$

Remarquons que :

$$ \sqrt{15} = \sqrt{3} \cdot \sqrt{5} $$

L’expression de $f$ devient :

$$ f = \frac{r \ \sqrt{3}}{4} + \frac{r \ \sqrt{3} \ \sqrt{5}}{4} $$

Mettons en évidence au membre de droite :

$$ f = \frac{r \ \sqrt{3}}{4} \ \left( 1 + \sqrt{5} \right) $$

Le terme entre parenthèses vaut deux fois le nombre d’or $\phi$ :

$$ f = \frac{r \ \sqrt{3}}{4} \cdot 2 \ \phi $$

On a donc finalement :

$$ f = \frac{r \ \sqrt{3}}{2} \ \phi $$

D’un autre côté, on a :

$$ e = 2 \ b = 2 \cdot \frac{r \ \sqrt{3}}{4} = \frac{r \ \sqrt{3}}{2} $$

Le rapport des longueurs :

$$ \frac{f}{e} = \frac{\phi \ r \ \sqrt{3}/2}{r \ \sqrt{3}/2} $$

nous donne donc le nombre d’or :

$$ \frac{f}{e} = \phi $$
