
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Hexagone régulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Classification des diagonales

Quels sont les types de $k$-diagonales dans un hexagone ? On a :

$$ 1 \le k \le 6 \diventiere 2 - 1 = 2 $$

Les seules diagonales possibles sont :

- les $1$-diagonales, ou diagonales courtes
- les $2$-diagonales, qui sont les seules diagonales longues

* Triangles formés par les rayons
:properties:
:custom_id: heading:triangles_formes_par_les_rayons
:end:

#+TOC: headlines 1 local

** Raisonnement

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les rayons de
$\mathscr{C}$ reliant le centre aux sommets de l’hexagone, découpant
ainsi la figure en six triangles intérieurs :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-triangles-rayons.svg]]

Nous avons tenu compte du caractère isocèle des triangles intérieurs
dans la notation des angles.

Dans les triangles $O P_1 P_2$ et $O P_2 P_3$ on a :

$$ \abs{P_1 P_2} = \abs{P_2 P_3} $$

car l’hexagone est régulier et :

$$ \abs{O P_1} = \abs{O P_2} = r $$

$$ \abs{O P_2} = \abs{O P_3} = r $$

par définition du cercle circonscrit. Ces triangles ont leurs trois
côtés de mêmes longueurs et sont donc isométriques. Un raisonnement
analogue nous montre que tous les triangles intérieurs de l’hexagone
sont isométriques :

$$ O P_1 P_2
\qquad
O P_2 P_3
\qquad
O P_3 P_4 $$

$$ O P_4 P_5
\qquad
O P_5 P_6
\qquad
O P_6 P_1 $$

On a en particulier :

$$ \alpha_1 = \alpha_2 = \ldots = \alpha_6 $$

$$ \beta_1 = \beta_2 = \ldots = \beta_6 $$

Posons :

$$ \alpha = \alpha_1 $$

$$ \beta = \beta_1 $$

Les angles $\alpha_1$, $\alpha_2$, $\ldots$, $\alpha_6$ forment ensemble
un tour complet :

$$ \sum_{i=1}^6 \alpha_i = 6 \ \alpha = 2 \ \pi $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{2 \ \pi}{6} = \frac{\pi}{3} = 60^\circ $$

La somme des angles dans le triangle $O P_1 P_2$ nous donne :

$$ \alpha + 2 \ \beta = 60^\circ + 2 \ \beta = 180^\circ $$

En isolant $\beta$, on obtient :

$$ \beta = \frac{180^\circ - 60^\circ}{2} = 60^\circ $$

Les triangles intérieurs ont donc leurs trois angles de même amplitude :

$$ \alpha = \beta = 60^\circ $$

Ce sont donc des triangles équilatéraux. On en déduit que le côté $c$
de l’hexagone régulier est de même longueur que le rayon du cercle
circonscrit :

$$ c = r $$

Ce résultat montre aussi que les angles internes d’un hexagone valent :

$$ 2 \ \beta = 120^\circ $$

Le schéma devient donc :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-triangles-rayons-resolu.svg]]

On a aussi les angles internes :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-angles-internes.svg]]

** Diamètres

On remarque que :

$$ \abs{\angleflex{P_1 O P_4}} = 3 \ \alpha = 180^\circ $$

Les points $O$, $P_1$ et $P_4$ sont alignés, ce qui signifie que $O$
se situe sur la $2$-diagonale $[P_1, P_4]$. Cette diagonale est donc un
diamètre du cercle $\mathscr{C}$.

Un raisonnement similaire nous montre que le centre du cercle circonscrit
est situé sur toutes les $2$-diagonales  :

$$ [P_1, P_4]
\qquad \qquad \qquad
[P_2, P_5]
\qquad \qquad \qquad
[P_3, P_6] $$

Ces $2$-diagonales sont donc aussi des diamètres du cercle.

** Conclusion

Dans un hexagone régulier :

- deux rayons qui aboutissent à deux sommets consécutifs forment un angle
  au centre de $60^\circ$
- l’angle formé par un côté et un rayon qui aboutit à une de ses extrémités
  a une amplitude de $60^\circ$
- le côté a la même longueur que le rayon du cercle circonscrit
- l’angle interne a une amplitude de $120^\circ$
- les $2$-diagonales sont des diamètres

* Diagonales courtes

#+TOC: headlines 1 local

** Angle entre côté et diagonale

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace la diagonale courte
$[P_2, P_6]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-angle-cote-diagonale-courte.svg]]

Nous avons tenu compte des résultats précédents et du caractère
isocèle des triangles dans la notation des angles.

Examinons le triangle isocèle $P_1 P_2 P_6$. La somme des angles nous
donne :

$$ 2 \ \alpha + 120^\circ = 180^\circ $$

On en déduit l’amplitude de $\alpha$ :

$$ \alpha = \frac{180^\circ - 120^\circ}{2} = 30^\circ $$

L’angle compris entre une diagonale courte de l’hexagone et un côté
qui relie une des extrémités de la diagonale au sommet intermédiaire
vaut $30^\circ$.

Notre schéma devient :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-angle-cote-diagonale-courte-resolu.svg]]

** Angle entre côté et rayon

** Triangle rectangle

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-triangle-rectangle.svg]]

Le côté $[P_1, P_4]$ du triangle $P_1 P_3 P_4$ est un
[[file:angles-et-cercles.org::#heading:diametre_comme_cote_d_un_triangle][diamètre
du cercle]]. Ce triangle est donc rectangle en $P_3$ :

$$ \angleflex{P_4 P_3 P_1} = 90^\circ $$

*** Angle

Le triangle $P_1 P_3 P_4$ étant rectangle en $P_3$, l’angle $\alpha$ est
le complémentaire de $60^\circ$ :

$$ \alpha = 90^\circ - 60^\circ = 30^\circ $$

*** Longueur

On note :

$$ L = \abs{P_1 P_3} $$

la longueur de la diagonale courte $[P_1,P_3]$.

La longueur d’un diamètre vaut deux fois le rayon :

$$ \abs{P_1 P_4} = 2 \ r $$

Le théorème de Pythagore appliqué au triangle $P_1 P_3 P_4$ nous donne :

$$ (2 \ r)^2 = r^2 + L^2 $$

ou encore :

$$ 4 \ r^2 = r^2 + L^2 $$

Isolons $L^2$ :

$$ L^2 = 4 \ r^2 - r^2 = 3 \ r^2 $$

En prenant la racine, on obtient :

$$ L = r \ \sqrt{3} $$

Un raisonnement similaire nous montre que toutes les diagonales courtes
sont de la même longueur :

$$ [P_1, P_3]
\qquad \qquad \qquad
[P_3, P_5]
\qquad \qquad \qquad
[P_5, P_1] $$

$$ [P_2, P_4]
\qquad \qquad \qquad
[P_4, P_6]
\qquad \qquad \qquad
[P_6, P_2] $$

*** Conclusion

Nous avons établi que :

- l’angle formé par une diagonale courte et un diamètre qui passe par
  une de ses extrémités a une amplitude de $30^\circ$
- les diagonales courtes ont une longueur $L = r \ \sqrt{3}$

Notre schéma devient :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-triangle-rectangle-resolu.svg]]

** Triangles équilatéraux
:properties:
:custom_id: heading:triangles_equilateraux
:end:

#+TOC: headlines 1 local

*** Premier triangle

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace le triangle $P_1
P_3 P_5$ dont les côtés sont les diagonales courtes $[P_1, P_3]$,
$[P_3, P_5]$ et $[P_5, P_1]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-grand-triangle-equilateral-1.svg]]

Nous avons tenu compte des résultats précédents et du caractère
isocèle des triangles dans la notation des angles.

- Comme :

$$ \abs{P_1 P_3} = \abs{P_3 P_5} = \abs{P_5 P_1} = r \ \sqrt{3} $$

le triangle $P_1 P_3 P_5$ est équilatéral. Ses angles valent $60^\circ$.

- La somme des angles du triangle isocèle $P_1 P_2 P_3$ nous donne :

$$ 2 \ \alpha + 120^\circ = 180^\circ $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{180^\circ - 120^\circ}{2} = 30^\circ $$

Un raisonnement similaire nous montre le même résultat pour les autres
triangles isocèles entourant le grand triangle équilatéral $P_1 P_3 P_5$ :

$$ P_3 P_4 P_5
\qquad \qquad
P_5 P_6 P_1 $$

Ces triangles ont donc un angle de $120^\circ$ et deux angles de
$30^\circ$.

- Notre schéma devient :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-grand-triangle-equilateral-resolu-1.svg]]

*** Second triangle

En utilisant un raisonnement similaire, on obtient le même résultat pour
le triangle $P_2 P_4 P_6$ formé par les autres diagonales courtes :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-grand-triangle-equilateral-resolu-2.svg]]

*** Conclusion

Nous avons établi que :

- les diagonales courtes forment deux triangles équilatéraux
- les triangles isocèles entourant un triangle équilatéral
  formé par les diagonale courtes ont un angle de $120^\circ$ et
  deux angles de $30^\circ$

* Losange
:properties:
:custom_id: heading:losange
:end:

#+TOC: headlines 1 local

** Introduction

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Traçons le losange $O P_6
P_1 P_2$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-losange.svg]]

Nous avons tenu compte dans la notation :

- des résultats précédents concernant l’hexagone régulier
- des propriétés du losange, et en particulier de ses diagonales
    + qui se croisent perpendiculairement en leur milieu
    + qui sont les bissectrices des angles situés à leurs extrémités

On définit :

$$ a = \abs{I O} = \abs{I P_1}
\qquad \qquad \qquad
b = \abs{I P_2} = \abs{I P_6} $$

** Longueurs

- Le rayon $[O, P_1]$ mesure $r$ mais aussi $2 \ a$ :

$$ 2 \ a = r $$

On en déduit que :

$$ a = \frac{r}{2} $$

- Comme $[P_2, P_6]$ est une diagonale courte, sa longueur vaut :

$$ \abs{P_2 P_6} = r \ \sqrt{3} $$

On a aussi :

$$ \abs{P_2 P_6} = 2 \ b $$

On en déduit que :

$$ 2 \ b = r \ \sqrt{3} $$

d’où :

$$ b = \frac{r \ \sqrt{3}}{2} $$

** Angles

- Puisque $[P_2, P_6]$ est la bissectrice de l’angle $\angleflex{O P_2 P_1}$, on a :

$$ 2 \ \alpha = 60^\circ $$

c’est-à-dire :

$$ \alpha = \frac{60^\circ}{2} = 30^\circ $$

- Puisque $[P_2, P_6]$ est la bissectrice de l’angle $\angleflex{P_1 P_6 O}$, on a :

$$ 2 \ \beta = 60^\circ $$

c’est-à-dire :

$$ \beta = \frac{60^\circ}{2} = 30^\circ $$

** Conclusion

Nous avons établi que :

- les rayons du cercle circonscrit passant par les sommets sont les médiatrices
  des diagonales courtes
- les diagonales courtes sont les médiatrices des rayons du cercle circonscrit
  qui passent par le sommet intermédiaire
- l’angle formé par une diagonale courte et un rayon qui passe par
  une de ses extrémités a une amplitude de $30^\circ$
- l’angle formé par un côté et la diagonale courte la plus proche qui
  passe par une de ses extrémités a une amplitude de $30^\circ$

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-losange-resolu.svg]]

*Remarque* : les propriétés des rayons sont aussi valables pour les
diamètres incluant ces rayons.

* Cerf-volant                                                 :noexport:

#+TOC: headlines 1 local

** Introduction

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Si on trace un grand triangle
équilatéral $P_1 P_3 P_5$, on voit se former le cerf-volant $P_1 P_3
P_4 P_5$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-cerf-volant.svg]]

Nous avons tenu compte dans la notation des angles :

- des résultats précédents concernant l’hexagone régulier
- des propriétés du cerf-volant, et en particulier de ses diagonales

La diagonale $[P_1, P_4]$ traverse les deux triangles isocèles qui
composent le cerf-volant. Ce segment est donc :

- la médiatrice de l’autre diagonale $[P_3, P_5]$ :
- la bissectrice des angles $\angleflex{P_3 P_1 P_5}$ et $\angleflex{P_5 P_4 P_3}$

Puisque $[P_1, P_4]$ est la bissectrice de l’angle $\angleflex{P_3
P_1 P_5}$ du grand triangle équilatéral, on a :

$$ 2 \ \alpha = 60^\circ $$

c’est-à-dire :

$$ \alpha = \frac{60^\circ}{2} = 30^\circ $$

** Conclusion

Les diamètres du cercle circonscrit passant par les sommets de l’hexagone sont
les médiatrices et les bissectrices des grands triangles équilatéraux.

Il en va de même pour les rayons inclus dans ces diamètres.

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-cerf-volant-resolu.svg]]

* Hexagramme

#+TOC: headlines 1 local

** Introduction

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Si on trace toutes les
diagonales courtes, on obtient deux triangles équilatéraux entrecroisés
qui forment ensemble une étoile à six branches. Cette figure est
appelée un hexagramme :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme.svg]]

Si nous ajoutons les angles de $30^\circ$ des six triangles isocèles
entourant les grands triangles équilatéraux de l’hexagramme :

$$ P_1 P_2 P_3
\qquad \qquad \qquad
P_3 P_4 P_5
\qquad \qquad \qquad
P_5 P_6 P_1 $$

$$ P_2 P_3 P_4
\qquad \qquad \qquad
P_4 P_5 P_6
\qquad \qquad \qquad
P_6 P_1 P_2 $$

le schéma devient :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-angles-triangles-isoceles.svg]]

Si nous ajoutons aussi les diamètres passant par les sommets, toutes
les diagonales de l’hexagone sont alors représentées :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-bissectrices.svg]]

** Pointes

#+TOC: headlines 1 local

*** Introduction

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Traçons l’hexagramme et
examinons la pointe supérieure :

#+attr_html: :width 55%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-pointes.svg]]

Nous avons tenu compte dans la notation :

- des résultats précédents concernant l’hexagone régulier
- des angles opposés par le sommet

On définit :

$$ a = \abs{P_1 S_1}
\qquad \qquad \qquad
b = \abs{P_1 S_6}
\qquad \qquad \qquad
c = \abs{S_1 S_6} $$

$$ d = \abs{P_2 S_1}
\qquad \qquad \qquad
f = \abs{S_6 P_6}
\qquad \qquad \qquad \qquad \qquad \quad $$

*** Angles

- La somme des angles dans le triangle $S_1 P_1 P_2$ nous donne :

$$ \lambda + 30^\circ + 30^\circ = 180^\circ $$

d’où :

$$ \lambda = 180^\circ - 2 \cdot 30^\circ = 120^\circ $$

- Comme $\alpha$ et $\lambda$ forment ensemble un angle plat, ils sont
  supplémentaires :

$$ \alpha + \lambda = 180^\circ $$

On en déduit la valeur de $\alpha$ :

$$ \alpha = 180^\circ - \lambda = 180^\circ - 120^\circ = 60^\circ $$

- La somme des angles dans le triangle $S_6 P_1 P_6$ nous donne :

$$ \mu + 30^\circ + 30^\circ = 180^\circ $$

d’où :

$$ \mu = 180^\circ - 2 \cdot 30^\circ = 120^\circ $$

- Comme $\beta$ et $\mu$ forment ensemble un angle plat, ils sont
  supplémentaires :

$$ \beta + \mu = 180^\circ $$

On en déduit la valeur de $\beta$ :

$$ \beta = 180^\circ - \mu = 180^\circ - 120^\circ = 60^\circ $$

- Un raisonnement similaire nous donne le même résultat pour les autres
  pointes de l’hexagramme.

*** Longueurs

- Le triangle $P_1 S_1 S_6$ possède trois angles de $60^\circ$ :

$$ \alpha = \beta = \abs{\angleflex{S_1 P_1 S_6}} = 60^\circ $$

C’est donc un triangle équilatéral :

$$ a = b = c $$

- Le triangle $S_1 P_1 P_2$ possède deux angles de même amplitude sur
  $P_1$ et $P_2$, il est donc isocèle en $S_1$ :

$$ a = d $$

- Le triangle $S_6 P_1 P_6$ possède deux angles de même amplitude sur
  $P_1$ et $P_6$, il est donc isocèle en $S_6$ :

$$ b = f $$

- Au vu de ce qui précède, on a :

$$ a = b = c = d = f $$

On a vu précédemment qu’une diagonale courte, telle que $[P_2, P_6]$,
est de longueur :

$$ L = r \ \sqrt{3} $$

Comme :

$$ L = d + c + f = 3 \ c $$

On en conclut que :

$$ c = \frac{L}{3} = \frac{r \ \sqrt{3}}{3} $$

- Un raisonnement similaire nous donne le même résultat pour les autres
  pointes de l’hexagramme.

*** Conclusion

Nous avons établi que :

- les pointes de l’hexagramme sont des triangles équilatéraux
- chaque triangle équilatéral de l’hexagramme coupe en trois parties
  égales les côtés de l’autre triangle équilatéral
- le côté d’une pointe d’hexagramme mesure $r \ \sqrt{3} / 3$

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-pointes-resolu.svg]]

On remarque que l’hexagone $S_1 S_2 ... S_6$ a :

- des côtés de même longueur
- des angles de même amplitude

C’est donc un hexagone régulier.

** Cerf-volants

#+TOC: headlines 1 local

*** Introduction

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Traçons l’hexagramme et
examinons-en la partie supérieure :

#+attr_html: :width 65%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-cerf-volants.svg]]

Nous avons tenu compte des résultats précédents dans la notation.

On définit :

$$ a
= \abs{P_1 S_1}
= \abs{P_1 S_6}
= \abs{P_2 S_1}
= \abs{P_6 S_6}
= \ldots
\qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \quad $$

$$ b_1 = \abs{S_1 I_1}
\qquad \qquad \qquad
c_1 = \abs{I_1 S_6}
\qquad \qquad \qquad
b_2 = \abs{S_2 I_2}
\qquad \qquad \qquad
c_2 = \abs{I_2 S_1} $$

$$ f_1 = \abs{O S_1}
\qquad \qquad \qquad
f_2 = \abs{O S_2}
\qquad \qquad \qquad \qquad \qquad
\qquad \qquad \qquad \qquad \qquad \qquad $$

*** Longueurs

- Le triangle $P_1 S_1 S_6$ étant équilatéral, il est isocèle en $P_1$.
  La hauteur qui part de $P_1$ est aussi la médiane du côté opposé :

$$ b_1 = c_1 $$

Idem dans le triangle $P_2 S_2 S_1$ :

$$ b_2 = c_2 $$

- Les triangles rectangles $P_1 S_1 I_1$ et $P_2 I_2 S_1$ ont un côté $a$
  de même longueur et un angle de $30^\circ$. Ces triangles sont donc
  isometriques et :

$$ b_1 = c_2 $$

En compilant les derniers résultats, on obtient :

$$ b_2 = c_2 = b_1 = c_1 $$

- Comme $b_1 = c_2$, les quadrilatères du type $O I_1 S_1 I_2$
  sont des cerf-volants.

- Les triangles rectangles $O I_2 S_1$ et $O I_2 S_2$ ont leurs
  deux cathètes de mêmes longueurs car $b_2 = c_2$. Ils sont donc
  isométriques et :

$$ f_1 = f_2 $$

Les triangles rectangles $P_2 I_2 S_2$ et $O I_2 S_2$ ont aussi leurs
deux cathètes de mêmes longueurs. Ils sont aussi isométriques et :

$$ f_2 = a $$

Les quadrilatères du type $P_2 S_2 O S_1$ sont des losanges.

*** Angles

Dans le cerf-volant $O I_1 S_1 I_2$, la diagonale $[O,S_1]$ traverse les
deux triangles isocèles $O I_1 I_2$ et $S_1 I_1 I_2$ qui le composent.
Cette diagonale est donc la bissectrice de l’angle $\angleflex{I_1 O
I_2}$ :

$$ \alpha = \beta $$

Or, $\alpha$ et $\beta$ forment ensemble un angle de $60^\circ$, car
situé entre deux rayons qui passent par des sommets consécutifs de
l’hexagone.  On en conclut que :

$$ 2 \ \alpha = 60^\circ $$

c’est-à-dire :

$$ \alpha = 30^\circ $$

La diagonale est $[O,S_1]$ est aussi la bissectrice de l’angle
$\angleflex{S_2 S_1 S_6}$ :

$$ \gamma = \delta $$

Or, $\gamma$ et $\delta$ forment ensemble un angle de $120^\circ$, car
interne à l’hexagone régulier $S_1 S_2 \ldots S_6$. On en conclut que :

$$ 2 \ \gamma = 120^\circ $$

c’est-à-dire :

$$ \gamma = 60^\circ $$

*** Conclusion

Un raisonnement similaire peut être appliqué aux autres pointes et
cerf-volants de l’hexagramme. Notre schéma devient :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-cerf-volants-resolu.svg]]

On remarque que :

- les distances entre $O$ et les sommets de l’hexagone $S_1 S_2 \ldots S_6$
  sont toutes identiques. Le point $O$ est donc aussi le centre du
  cercle circonscrit de $S_1 S_2 \ldots S_6$
- les segments reliant $O$ avec les $P_i$ et les $S_i$ forment des
  angles de $30^\circ$ autour de $O$
- les triangles de la catégorie $O S_1 S_2$ ont trois
  angles de $60^\circ$. Ce sont donc des triangles équilatéraux. Ce
  résultat est parfaitement cohérent, car les segments $[O,S_i]$ sont les
  [[#heading:triangles_formes_par_les_rayons][rayons du cercle circonscrit
  de l’hexagone régulier]] $S_1 S_2 \ldots S_6$.

** Fractale

Le tracé de l’hexagramme produit un deuxième hexagone régulier,
dans lequel on peut tracer un deuxième hexagramme :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-fractale-1.svg]]

Ce tracé produit un troisième hexagone, dans lequel on peut tracer un
troisième hexagramme :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-hexagramme-fractale-2.svg]]

On peut continuer ainsi indéfiniment.

* Nombre d’or

#+TOC: headlines 1 local

** Introduction

Soit un hexagone régulier $P_1 P_2 \ldots P_6$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace le grand triangle
équilatéral $P_1 P_3 P_5$, deux diamètres et quelques intersections :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hexagone-nombre-d-or.svg]]

Nous avons tenu compte dans la notation :

- des résultats précédents concernant l’hexagone régulier
  + en particulier sur les [[#heading:losange][losanges]] du type $O P_1 P_2 P_3$
- des propriétés du cerf-volant $G O H P_1$, et en particulier
  de ses diagonales

On définit les distances :

$$ a = \abs{OI}
\qquad \qquad
b = \abs{GI}
\qquad \qquad
d = \abs{IJ}
\qquad \qquad
e = \abs{GH}
\qquad \qquad
f = \abs{GJ} $$

La diagonale $[P_1,O]$ traverse les deux triangles isocèles qui composent
le cerf-volant $G O H P_1$, c’est donc la médiatrice de l’autre
diagonale $[G,H]$, comme indiqué sur le schéma. On a donc :

$$ b = \abs{GI} = \abs{IH} $$

On a :

$$ f = b + d
\qquad \qquad \qquad
e = 2 \ b $$

** Triangle $GOI$

- Dans le triangle rectangle $GOI$, on a par définition du cosinus :

$$ \cos 60^\circ = \frac{a}{r/2} $$

Isolons $a$ :

$$ a = \frac{r}{2} \ \cos 60^\circ $$

Comme le cosinus de $60^\circ$ vaut $1/2$, cette équation devient :

$$ a = \frac{r}{2} \cdot \unsur{2} = \frac{r}{4} $$

- Le sinus nous donne :

$$ \sin 60^\circ = \frac{b}{r/2} $$

Isolons $b$ :

$$ b = \frac{r}{2} \ \sin 60^\circ $$

Comme le sinus de $60^\circ$ vaut $\sqrt{3}/2$, cette équation devient :

$$ b = \frac{r}{2} \cdot \frac{\sqrt{3}}{2} = \frac{r \ \sqrt{3}}{4} $$

** Triangle $OJI$

Dans le triangle $OJI$, le théorème de Pythagore s’écrit :

$$ r^2 = a^2 + d^2 $$

Comme $a = r/4$, cette relation devient :

$$ r^2 = \frac{r^2}{16} + d^2 $$

Isolons $d^2$ :

$$ d^2 = r^2 - \frac{r^2}{16} $$

Mettons les membres de droite au même dénominateur :

$$ d^2 = \frac{16 \ r^2 - r^2}{16} = \frac{15 \ r^2}{16} $$

Il ne nous reste plus qu’à prendre la racine carrée pour obtenir la
valeur de $d$ :

$$ d = \frac{r \ \sqrt{15}}{4} $$

** Sommes

- On a :

$$ f = b + d = \frac{r \ \sqrt{3}}{4} + \frac{r \ \sqrt{15}}{4} $$

Remarquons que :

$$ \sqrt{15} = \sqrt{3} \cdot \sqrt{5} $$

L’expression de $f$ devient :

$$ f = \frac{r \ \sqrt{3}}{4} + \frac{r \ \sqrt{3} \ \sqrt{5}}{4} $$

Mettons en évidence au membre de droite :

$$ f = \frac{r \ \sqrt{3}}{4} \ \left( 1 + \sqrt{5} \right) $$

Soit le nombre d’or :

$$ \phi = \frac{ 1 + \sqrt{5} }{2} $$

Le terme entre parenthèses est le double de $\phi$ :

$$ f = \frac{r \ \sqrt{3}}{4} \cdot 2 \ \phi $$

On a donc finalement :

$$ f = \frac{r \ \sqrt{3}}{2} \ \phi $$

- D’un autre côté, on a :

$$ e = 2 \ b = 2 \cdot \frac{r \ \sqrt{3}}{4} = \frac{r \ \sqrt{3}}{2} $$

L’expression de $f$ peut se réécrire :

$$ f = e \ \phi $$

En divisant par $e$ :

$$ \frac{f}{e} = \phi $$

on obtient un rapport de longueur égal au nombre d’or.

** Conclusion

L’hexagone régulier inscrit dans un cercle nous donne la proportion
du nombre d’or :

$$ \phi = \frac{\abs{GJ}}{\abs{GH}} $$

