
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Intégrales
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:integral}

* Dépendances

  - Chapitre \ref{chap:fonction} : Les fonctions
  - Chapitre \ref{chap:mesure} : Les mesures

* Introduction

Soit une fonction $f : A \mapsto \setR$ mesurable et essentiellement positive ($f \esssuperieur 0$) :

$$\mu(\{x : f(x) \strictinferieur 0\}) = 0$$

Pour toute fonction étagée $w : A \mapsto \setR$, on sait que la fonction $w - f$ est mesurable. Le réel :

$$\mu(\{ x \in A : w(x) \strictsuperieur f(x) \}) = \mu(\{ x \in A : w(x) - f(x) \strictsuperieur 0 \})$$

est donc bien défini. On peut dès lors introduire l'ensemble des fonctions étagées $w$ essentiellement inférieures à $f$ :

$$\mathcal{E}_A(f) = \{ w \in \etagee(A) : w \essinferieur f \}$$

Evaluant les intégrales des fonctions étagées appartenant à $\mathcal{E}_A(f)$, on obtient l'ensemble de réels associé :

$$\mathcal{I}_A(f) = \left\{ \int_A w(x) \ d\mu(x) \ : w \in \mathcal{E}_A(f)  \right\}$$

Cet ensemble est non vide car $0 \in \mathcal{E}_A(f)$ produit une intégrale $0 \in \mathcal{I}_A(f)$. Deux cas peuvent se présenter :

  - L'ensemble de réels $\mathcal{I}_A(f)$ est majoré. Il admet donc un supremum. Nous pouvons alors définir l'intégrale de $f$ sur $A$ par :

$$\int_A f(x) \ d\mu(x) = \sup \left\{ \int_A w(x) \ d\mu(x) \ : w \in \mathcal{E}_A(f)  \right\}$$

On dit alors que $f$ est intégrable sur $A$. On le note parfois :

$$\int_A f(x) \ d\mu(x) \strictinferieur +\infty$$

  - Dans le cas contraire, on a $\sup \mathcal{I}_A(f) = +\infty$. On définit par analogie :

$$\int_A f(x) \ d\mu(x) = +\infty$$



** Consistance

Les propriétés extrémales des intégrales des fonctions étagées nous montrent que, dans le cas particulier où $f \in \etagee(A)$, l'intégrale obtenue par le supremum est identique à l'intégrale au sens des fonctions étagées.


* Signe quelconque

Soit une fonction mesurable $f : A \mapsto \setR$. On peut décomposer $f$ en fonctions positives $f^+,f^- : A \mapsto \setR$ définies par :

\begin{align}
f^+(x) &= \max \{ f(x) , 0 \} \ge 0 \)

\(
f^-(x) &= \max \{ -f(x) , 0 \} \ge 0
\end{align}

pour tout $x \in A$. On a alors :

$$f = f^+ - f^-$$

Les fonctions $f^+$ et $f^-$ étant également mesurables, leurs intégrales sont bien définies (finies ou infinies). Plusieurs cas peuvent se présenter :

  - Les fonctions $f^+$ et $f^-$ sont intégrables sur $A$. On étend alors la définition de l'intégrale par :

$$\int_A f(x) \ d\mu(x) = \int_A f^+(x) \ d\mu(x) - \int_A f^-(x) \ d\mu(x)$$

On dit alors que $f$ est intégrable.

  - La fonction $f^+$ produit une intégrale infinie, mais $f^-$ est intégrable sur $A$. On définit alors :

$$\int_A f(x) \ d\mu(x) = +\infty$$

  - La fonction $f^-$ produit une intégrale infinie, mais $f^+$ est intégrable sur $A$. On définit alors :

$$\int_A f(x) \ d\mu(x) = -\infty$$

  - Si  aucune des fonction $f^+,f^-$ n'est intégrable, l'intégrale de $f$ n'est pas définie.


* Intégrale de Riemann

Soit une fonction $f$ mesurable et essentiellement positive. Posons :

$$\mathcal{F}_A(f) = \{ w \in \etagee(A) : w \esssuperieur f \}$$

et :

$$\mathcal{J}_A(f) = \left\{ \int_A w(x) \ d\mu(x) \ : w \in \mathcal{F}_A(f)  \right\}$$

Si $f$ est intégrable et que son intégrale vérifie la dualité :

$$\int_A f(x) \ d\mu(x) = \sup \mathcal{I}_A(f) = \inf \mathcal{J}_A(f)$$

on dit que $f$ est intégrable au sens de Riemann.


* Fonctions essentiellement positives

Soit une fonction $f$ mesurable et essentiellement positive.


** Signe de l'intégrale

Comme la fonction étagée nulle $0 \in \mathcal{E}_A(f)$, on a :

$$\int_A f(x) \ d\mu(x) \ge \int_A 0 \ d\mu(x) = 0$$

par définition du supremum. L'intégrale d'une fonction essentiellement positive est positive.


** Intégrale nulle

Supposons que :

$$\int_A f(x) \ d\mu(x) = 0$$

Soit le réel $\epsilon \strictsuperieur 0$. Si il existait un ensemble $C \subseteq A$ de mesure non nulle tel que $f \strictsuperieur \epsilon$ sur $C$, la fonction étagée $w = \epsilon \cdot \indicatrice_C$ vérifierait $w \essinferieur f$ et appartiendrait donc à $\mathcal{E}_A(f)$. On aurait alors par définition du supremum :

$$\int_A f(x) \ d\mu(x) \ge \int_A \epsilon \cdot \indicatrice_C(x) \ d\mu(x) = \epsilon \cdot \mu(C) \strictsuperieur 0$$

ce qui contredit l'hypothèse. On doit donc avoir $f \essinferieur \epsilon$ quel que soit $\epsilon \strictsuperieur 0$. On en conclut que $f \essinferieur 0$. Mais comme on a également $f \esssuperieur 0$, on en déduit que $f \essegal 0$. Une fonction essentiellement positive présentant une intégrale nulle est essentiellement nulle.


* Ordre


** Fonctions positives

Soit les fonctions essentiellement positives et intégrables $f,g : A \to \setR$ telles que $f \essinferieur g$. Soit $w \in \mathcal{E}_A(f)$. Comme on a  $w \essinferieur f$ et $f \essinferieur g$, on en conclut que $w \essinferieur g$, c'est-à-dire que $w \in \mathcal{E}_A(g)$. On a donc $\mathcal{E}_A(f) \subseteq \mathcal{E}_A(g)$. On en déduit que $\mathcal{I}_A(f) \subseteq \mathcal{I}_A(g)$, d'où :

$$\sup \mathcal{I}_A(f) \le \sup \mathcal{I}_A(g)$$

Comme ces supremums sont par définition égaux aux intégrales correspondantes, on a :

$$\int_A f(x) \ d\mu(x) \le \int_A g(x) \ d\mu(x)$$


** Généralisation

On considère à présent le cas de fonctions $f,g$ de signe quelconque, toujours avec $f \essinferieur g$. On définit les fonctions positives :

\begin{align}
f^+(x) &= \max \{ f(x) , 0 \} \)

\(
f^-(x) &= \max \{ -f(x) , 0 \} \)

\(
g^+(x) &= \max \{ g(x) , 0 \} \)

\(
g^-(x) &= \max \{ -g(x) , 0 \}
\end{align}

On a donc $f^+ \essinferieur g^+$ et $g^- \essinferieur f^-$. On en conclut que :

$$\int_A f^+(x) \ d\mu(x) - \int_A f^-(x) \ d\mu(x) \le \int_A g^+(x) \ d\mu(x) - \int_A g^-(x) \ d\mu(x)$$

d'où, par définition :

$$\int_A f(x) \ d\mu(x) \le \int_A g(x) \ d\mu(x)$$

L'ordre des intégrales correspond à l'ordre essentiel sur les fonctions.


** Egalité

Soit deux fonctions intégrables $f,g$ vérifiant $f \essegal g$. On a $f \essinferieur g$ et l'intégrale de $f$ est inférieure à l'intégrale de $g$. Mais on a aussi $f \esssuperieur g$ et l'intégrale de $f$ est supérieure à l'intégrale de $g$. On en conclut que :

$$\int_A f(x) \ d\mu(x) = \int_A g(x) \ d\mu(x)$$


* Valeur moyenne

La valeur moyenne d'une fonction $f$ sur $A$ est définie par :

$$M = \unsur{\mu(A)} \int_A f(x) \ d\mu(x)$$


* Bornes

Soit une fonction intégrable $f : A \mapsto \setR$.

  - Si $f$ est essentiellement majorée, on a :

$$f \essinferieur \supessentiel \{ f(x) : x \in A \}$$

En intégrant sur $A$, il vient :

$$\int_A f(x) \ d\mu(x) \le \mu(A) \cdot \supessentiel_{x \in A} f(x)$$

  - Si $f$ est essentiellement minorée, on a :

$$f \esssuperieur \infessentiel \{ f(x) : x \in A \}$$

En intégrant sur $A$, il vient :

$$\int_A f(x) \ d\mu(x) \ge \mu(A) \cdot \infessentiel_{x \in A} f(x)$$

  - Si $f$ est majorée et minorée, et si $A$ est de mesure non nulle, on peut réexprimer ces bornes en terme de valeur moyenne de $f$ :

$$\infessentiel_{x \in A} f(x) \le \unsur{\mu(A)} \int_A f(x) \ d\mu(x) \le \supessentiel_{x \in A} f(x)$$



** Corollaires

Si $f$ est essentiellement nulle, les supremum et infimum essentiels s'annulent, et :

$$0 \le \int_A f(x) \ d\mu(x) \le 0$$

On en conclut que :

$$\int_A f(x) \ d\mu(x) = 0$$

Il en va de même si $\mu(A) = 0$.


* Opposé

Soit une fonction intégrable $f$ et $g = -f$. On a :

\begin{align}
g^+(x) &= \max \{ g(x) , 0 \} = \max \{ -f(x) , 0 \} = f^-(x) \)

\(
g^-(x) &= \max \{ -g(x) , 0 \} = \max \{ f(x) , 0 \} = f^+(x)
\end{align}

et :

$$\int_A g(x) \ d\mu(x) = \int_A f^-(x) \ d\mu(x) - \int_A f^+(x) \ d\mu(x) = - \int_A f(x) \ d\mu(x)$$

L'intégrale de la fonction opposée est donc l'opposé de l'intégrale :

$$\int_A (-f(x)) \ d\mu(x) = - \int_A f(x) \ d\mu(x)$$


* Multiplication par une fonction indicatrice


** Fonctions positives

Soit une fonction $f$ essentiellement positive et intégrable sur $A$ et l'ensemble $C \in \mathcal{T}$ vérifiant $C \subseteq A$. Soit le réel $\epsilon \strictsuperieur 0$.


  - Comme le supremum est dans l'adhérence, on peut trouver une fonction $u \in \mathcal{E}_A(f \cdot \indicatrice_C)$ telle que :

$$\abs{\int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x) - \int_A u(x) \ d\mu(x)} \le \epsilon$$

On a donc :

$$\int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x) - \epsilon \le \int_A u(x) \ d\mu(x)$$

Les ensembles $A \setminus C$ et $C$ étant disjoints et d'union égale à $A$, on a aussi :

$$\int_A u(x) \ d\mu(x) = \int_{A \setminus C} u(x) \ d\mu(x) + \int_C u(x) \ d\mu(x)$$

Sur $A \setminus C$, on a $u \essinferieur f \cdot \indicatrice_C = 0$. La fonction $u$ y est donc essentiellement négative. Son intégrale y est donc négative et :

$$\int_A u(x) \ d\mu(x) \le \int_C u(x) \ d\mu(x)$$

La fonction étagée $u$ étant essentiellement inférieure à $f$ sur $C$, on a aussi :

$$\int_C u(x) \ d\mu(x) \le \int_C f(x) \ d\mu(x)$$

Rassemblant ces résultats, on obtient :

$$\int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x) - \epsilon \le \int_C f(x) \ d\mu(x)$$

Cette inégalité étant satisfaite quel que soit $\epsilon \strictsuperieur 0$, on a :

$$\int_C f(x) \ d\mu(x) \ge \int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x)$$

  - Comme le supremum est dans l'adhérence, on peut trouver un $w \in \mathcal{E}_C(f)$ tel que :

$$\int_C f(x) \ d\mu(x) - \epsilon \le \int_C w(x) \ d\mu(x)$$

Considérons l'extension de $w$ sur $A$ définie par :

#+BEGIN_CENTER
\(
u =
\begin{cases}
w & \text{ sur } C \)

\(
0 & \text{ sur } A \setminus C
\end{cases}
\)
#+END_CENTER

On voit que $u$ est une fonction étagée. On a :

$$\int_A u(x) \ d\mu(x) = \int_{A \setminus C} u(x) \ d\mu(x) + \int_C u(x) \ d\mu(x)$$

Sur $A \setminus C$, $u$ est nulle et l'intégrale correspondante l'est aussi. Sur $C$, on a $u = w$. Donc :

$$\int_A u(x) \ d\mu(x) = 0 + \int_C u(x) \ d\mu(x) = \int_C w(x) \ d\mu(x)$$

Comme :

#+BEGIN_CENTER
\(
u \essinferieur
\begin{cases}
f & \text{ sur } C \)

\(
0 & \text{ sur } A \setminus C
\end{cases}
\)
#+END_CENTER

on voit que $u \in \mathcal{E}_A(f \cdot \indicatrice_C)$ et que :

$$\int_A u(x) \ d\mu(x) \le \int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x)$$

par définition du supremum. En rassemblant ces résultats, on obtient :

$$\int_C f(x) \ d\mu(x) - \epsilon \le \int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x)$$

Ce résultat étant vérifié pour tout $\epsilon \strictsuperieur 0$, on a finalement :

$$\int_C f(x) \ d\mu(x) \le \int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x)$$


L'intégrale de $f$ sur $C$ étant à la fois inférieure et supérieure à l'intégrale de $f \cdot \indicatrice_C$ sur $A$, elle doit lui être égale :

$$\int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x) = \int_C f(x) \ d\mu(x)$$


** Généralisation

Soit une fonction $f$ mesurable et sa décomposition en fonctions positives $f = f^+ - f^-$. On voit que :

$$(f^+ - f^-) \cdot \indicatrice_C = f^+ \cdot \indicatrice_C - f^- \cdot \indicatrice_C$$

Comme on a aussi :

#+BEGIN_CENTER
\(
(f \cdot \indicatrice_C)^+ = f^+ \cdot \indicatrice_C \)

\(
(f \cdot \indicatrice_C)^- = f^- \cdot \indicatrice_C
\)
#+END_CENTER

on en conclut que :

\begin{align}
\int_A f(x) \cdot \indicatrice_C(x) \ d\mu(x) &= \int_A f^+(x) \cdot \indicatrice_C(x) \ d\mu(x) - \int_A f^-(x) \cdot \indicatrice_C(x) \ d\mu(x) \)

\(
&= \int_C f^+(x) \ d\mu(x) - \int_C f^-(x) \ d\mu(x) \)

\(
&= \int_C f(x) \ d\mu(x)
\end{align}


* Additivité


** Fonctions positives

Soit deux ensembles $A$ et $B$ disjoints ($A \cap B = \emptyset$) et une fonction $f$ essentiellement positive et mesurable sur $A \cup B$. Comme $A$ et $B$ sont disjoints, on a $\indicatrice[A \cap B] = 0$ et :

$$1 = \indicatrice[A \cup B](x) = \indicatrice_A(x) + \indicatrice_B(x)$$

pour tout $x \in A \cup B$. Soit le réel $\epsilon \strictsuperieur 0$.

  - Comme le supremum est dans l'adhérence, on peut trouver des fonctions $u \in \mathcal{E}_{A \cup B}(f \cdot \indicatrice_A)$ et $v \in \mathcal{E}_{A \cup B}(f \cdot \indicatrice_B)$ telles que leurs intégrales soit situées à une distance inférieure à $\epsilon$ des intégrales de $f \cdot \indicatrice_A$ et $f \cdot \indicatrice_B$. Comme $A,B \subseteq A \cup B$, on a :

\begin{align}
\int_{A \cup B} u(x) \ d\mu(x) &\ge \int_{A \cup B} f(x) \cdot \indicatrice_A(x) \ d\mu(x) - \epsilon \)

\(
&\ge \int_A f(x) \ d\mu(x) - \epsilon \)

\(
\int_{A \cup B} v(x) \ d\mu(x) &\ge \int_{A \cup B} f(x) \cdot \indicatrice_B(x) \ d\mu(x) - \epsilon \)

\(
&\ge \int_B f(x) \ d\mu(x) - \epsilon
\end{align}

Par linéarité des intégrales des fonctions étagées, on a :

\begin{align}
\int_{A \cup B} [u(x) + v(x)] \ d\mu(x) &= \int_{A \cup B} u(x) \ d\mu(x) + \int_{A \cup B} v(x) \ d\mu(x) \)

\(
&\ge \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x) - 2 \epsilon
\end{align}

On voit que :

$$u + v \essinferieur f \cdot \indicatrice_A + f \cdot \indicatrice_B = f \cdot (\indicatrice_A + \indicatrice_B) = f$$

La fonction $u + v$ est donc essentiellement inférieure à $f$ et on a $u + v \in \mathcal{E}_{A \cup B}(f)$. La définition du supremum nous montre alors que :

$$\int_{A \cup B} f(x) \ d\mu(x) \ge \int_{A \cup B} [u(x) + v(x)] \ d\mu(x)$$

En rassemblant ces résultats, on arrive à :

$$\int_{A \cup B} f(x) \ d\mu(x) \ge \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x) - 2 \epsilon$$

Ce résultat étant valable pour tout $\epsilon \strictsuperieur 0$ et aucune grandeur ne dépendant de $\epsilon$, on a finalement :

$$\int_{A \cup B} f(x) \ d\mu(x) \ge \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x)$$

  - Le supremum étant dans l'adhérence, on peut trouver une fonction $w \in \mathcal{E}_{A \cup B}(f)$ telle que :

$$\int_{A \cup B} f(x) \ d\mu(x) - \epsilon \le \int_{A \cup B} w(x) \ d\mu(x)$$

Posons $u = w \cdot \indicatrice_A$ et $v = w \cdot \indicatrice_B$. On a :

$$w = w \cdot (\indicatrice_A + \indicatrice_B) = w \cdot \indicatrice_A + w \cdot \indicatrice_B = u + v$$

La multiplication par une fonction indicatrice conservant le caractère étagé d'une fonction, $u$ et $v$ sont étagées. On a :

#+BEGIN_CENTER
\(
u =
\begin{cases}
w & \text{ sur } A \)

\(
0 & \text{ sur } B
\end{cases}
\essinferieur
\begin{cases}
f & \text{ sur } A \)

\(
0 & \text{ sur } B
\end{cases}
\)
#+END_CENTER

et :

#+BEGIN_CENTER
\(
v =
\begin{cases}
0 & \text{ sur } A \)

\(
w & \text{ sur } B
\end{cases}
\essinferieur
\begin{cases}
0 & \text{ sur } A \)

\(
f & \text{ sur } B
\end{cases}
\)
#+END_CENTER

On en conclut que $u$ est essentiellement inférieure à $f \cdot \indicatrice_A$ et que $v$ est essentiellement inférieure à $f \cdot \indicatrice_B$. On a $u \in \mathcal{E}_{A \cup B}(f \cdot \indicatrice_A)$ et $v \in \mathcal{E}_{A \cup B}(f \cdot \indicatrice_B)$. On peut donc écrire :

#+BEGIN_CENTER
\(
\int_{A \cup B} u(x) \ d\mu(x) \le \int_{A \cup B} f(x) \cdot \indicatrice_A(x) \ d\mu(x) \)

\(
\int_{A \cup B} v(x) \ d\mu(x) \le \int_{A \cup B} f(x) \cdot \indicatrice_B(x) \ d\mu(x)
\)
#+END_CENTER

inégalités que l'on peut réécrire sous la forme :

#+BEGIN_CENTER
\(
\int_{A \cup B} u(x) \ d\mu(x) \le \int_A f(x) \ d\mu(x) \)

\(
\int_{A \cup B} v(x) \ d\mu(x) \le \int_B f(x) \ d\mu(x)
\)
#+END_CENTER

En utilisant la linéarité des intégrales des fonctions étagées, on a :

\begin{align}
\int_{A \cup B} f(x) \ d\mu(x) - \epsilon &\le \int_{A \cup B} w(x) \ d\mu(x) \)

\(
&\le \int_{A \cup B} [u(x) + v(x)] \ d\mu(x) \)

\(
&\le \int_{A \cup B} u(x) \ d\mu(x) + \int_{A \cup B} v(x) \ d\mu(x) \)

\(
&\le \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x)
\end{align}

Comme cette inégalité doit être valable pour tout $\epsilon \strictsuperieur 0$, on a finalement :

$$\int_{A \cup B} f(x) \ d\mu(x) \le \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x)$$


L'intégrale sur $A \cup B$ devant être à la fois supérieure et inférieure à la somme de l'intégrale sur $A$ et de l'intégrale sur $B$, on en conclut que :

$$\int_{A \cup B} f(x) \ d\mu(x) = \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x)$$


** Généralisation

Nous allons étendre le résultat précédent aux fonctions mesurables quelconques. Soit la fonction mesurable $f$. En utilisant la décomposition en fonctions positives $f = f^+ - f^-$, on obtient :

\begin{align}
\int_{A \cup B} f(x) \ d\mu(x) &= \int_{A \cup B} f^+(x) - \int_{A \cup B} f^-(x) \ d\mu(x) \)

\(
&= \int_A f^+ + \int_B f^+ - \int_A f^- - \int_B f^- \)

\(
&= \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x)
\end{align}


** Corollaire

Si $C \subseteq A$, les ensembles $A \setminus C$ et $C$ sont disjoints et d'union égale à $A$. On a donc :

$$\int_A f(x) \ d\mu(x) = \int_{A \setminus C} f(x) \ d\mu(x)  + \int_C f(x) \ d\mu(x) \ge \int_C f(x) \ d\mu(x)$$


** Invariance

Soit un sous-ensemble essentiel $C$ de $A$. On a alors $C = A \setminus Z$ avec $Z \subseteq A$ et $\mu(Z) = 0$. Les ensembles $C$ et $Z = A \setminus C$ sont disjoints et d'union égale à $A$. Comme l'intégrale de $f$ sur l'ensemble de mesure nulle $Z$ est nulle, on a :

\begin{align}
\int_A f(x) \ d\mu(x) &= \int_C f(x) \ d\mu(x)  + \int_Z f(x) \ d\mu(x) \)

\(
&= \int_C f(x) \ d\mu(x)  + 0 \)

\(
&= \int_C f(x) \ d\mu(x)
\end{align}

L'intégrale est invariante lorsqu'on ajoute ou s'abstrait d'un ensemble de mesure nulle.


* Union

Soit à présent $A,B \in \mathcal{T}$ quelconques et une fonction intégrable $f : A \cup B \mapsto \setR$. Comme $A \setminus B$ et $B$ sont disjoints et d'union égale à $A \cup B$, on a :

$$\int_{A \cup B} f(x) \ d\mu(x) = \int_{A \setminus B} f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x)$$

On peut également décomposer $A$ en les ensembles disjoints $A \setminus B$ et $A \cap B$. Donc :

$$\int_A f(x) \ d\mu(x) = \int_{A \setminus B} f(x) \ d\mu(x) + \int_{A \cap B} f(x) \ d\mu(x)$$

et :

$$\int_{A \setminus B} f(x) \ d\mu(x) = \int_A f(x) \ d\mu(x) - \int_{A \cap B} f(x) \ d\mu(x)$$

En injectant cette relation dans l'expression de l'intégrale sur $A \cup B$, on obtient :

$$\int_{A \cup B} f(x) \ d\mu(x) = \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x) - \int_{A \cap B} f(x) \ d\mu(x)$$


** Corollaire

Si l'ensemble $A \cap B$ vérifie $\mu(A \cap B) = 0$, l'intégrale correspondante est nulle et :

$$\int_{A \cup B} f(x) \ d\mu(x) = \int_A f(x) \ d\mu(x) + \int_B f(x) \ d\mu(x)$$

Il suffit donc d'avoir une intersection de mesure nulle (et pas forcément vide) pour vérifier l'additivité.


* Convergence des mesures

Soit une fonction $f : A \mapsto \setR$ essentiellement positive et intégrable. On a :

$$I = \int_A f(x) \ d\mu(x) \strictinferieur +\infty$$

Posons :

#+BEGIN_CENTER
\(
C(\alpha) = \{ x \in A : f(x) \le \alpha \} \)

\(
Z(\alpha) = \{ x \in A : f(x) \strictsuperieur \alpha \}
\)
#+END_CENTER

pour tout $\alpha \in \setR$. Il est clair que $A = C(\alpha) \cup Z(\alpha)$. On a :

$$\int_{Z(\alpha)} f(x) \ d\mu(x) \le \int_{C(\alpha)} f(x) \ d\mu(x) + \int_{Z(\alpha)} f(x) \ d\mu(x) = I$$

Mais comme $f \esssuperieur \alpha$ sur $Z(\alpha)$, on a :

$$\infessentiel_{x \in Z(\alpha)} f(x) \ge \alpha$$

et :

$$\mu(Z(\alpha)) \cdot \alpha \le \mu(Z(\alpha)) \cdot \infessentiel_{x \in Z(\alpha)} f(x) \le \int_{Z(\alpha)} f(x) \ d\mu(x)$$

Rassemblant ces résultats, il vient :

$$\mu(Z(\alpha)) \cdot \alpha \le I$$

Soit $\epsilon \strictsuperieur 0$. Si on choisit $\alpha \ge I / \epsilon$, on a :

$$\mu(Z(\alpha)) \le \frac{I}{\alpha} \le \epsilon$$

On en déduit que :

$$\lim_{\alpha \to +\infty} \mu(Z(\alpha)) = \lim_{\alpha \to +\infty} \mu(\{ x \in A : f(x) \strictsuperieur \alpha \}) = 0$$


* Convergence des intégrales

Soit une fonction $f : A \mapsto \setR$ essentiellement positive et intégrable. On a :

$$I = \int_A f(x) \ d\mu(x) \strictinferieur +\infty$$

Soit la collection $\{ C(\alpha) \in \sousens(A) : \alpha \in \setR \}$ et la collection associée $\{ Z(\alpha) \in \sousens(A) : \alpha \in \setR \}$ définie par :

$$Z(\alpha) = A \setminus C(\alpha)$$

Nous supposons que :

$$\lim_{\alpha \to \infty} \mu(Z(\alpha)) = 0$$

et que $Z(\alpha) \subseteq Z(\beta)$ pour tout $\alpha,\beta \in \setR$ vérifiant $\alpha \ge \beta$.

Soit le réel $\epsilon \strictsuperieur 0$. Comme le supremum est dans l'adhérence, on peut trouver un $w \in \mathcal{E}_A(f)$ tel que :

$$\int_A f(x) \ d\mu(x) \le \int_A w(x) \ d\mu(x) + \epsilon$$

Comme $A = C(\alpha) \cup Z(\alpha)$, on a :

#+BEGIN_CENTER
\(
\int_A f(x) \ d\mu(x) = \int_{C(\alpha)} f(x) \ d\mu(x) + \int_{Z(\alpha)} f(x) \ d\mu(x) \\ \)

\(
\int_A w(x) \ d\mu(x) = \int_{C(\alpha)} w(x) \ d\mu(x) + \int_{Z(\alpha)} w(x) \ d\mu(x)
\)
#+END_CENTER

pour tout $\alpha \in \setR$. On en déduit que :

$$\int_{Z(\alpha)} f(x) \ d\mu(x) \le \int_{C(\alpha)} w(x) \ d\mu(x) - \int_{C(\alpha)} f(x) \ d\mu(x) + \int_{Z(\alpha)} w(x) \ d\mu(x) + \epsilon$$

Soit la fonction $I : \setR \mapsto \setR$ définie par :

$$I(\alpha) = \int_{Z(\alpha)} f(x) \ d\mu(x) \ge 0$$

On sait que $w \essinferieur f$. Par conséquent, $\int w \le \int f$ sur $C(\alpha)$ et :

$$I(\alpha) \le \int_{Z(\alpha)} w(x) \ d\mu(x) + \epsilon$$

Comme $w$ est une fonction étagée, son supremum existe :

$$M = \supessentiel_{x \in A} w(x)$$

De plus, on a $C(\alpha) \subseteq A$ pour tout $\alpha \in \setR$, d'où :

$$S(\alpha) = \supessentiel_{x \in C(\alpha)} w(x) \le M$$

On a donc :

$$\int_{Z(\alpha)} w(x) \ d\mu(x) \le \mu(Z(\alpha)) \cdot S(\alpha) \le \mu(Z(\alpha)) \cdot M$$

et :

$$I(\alpha) \le \mu(Z(\alpha)) \cdot M + \epsilon$$

pour tout $\alpha \in \setR$. Si $\alpha \ge \beta$, on a $Z(\alpha) \subseteq Z(\beta)$, d'où $I(\alpha) \le I(\beta)$. La fonction $I$ est décroissante et minorée par zéro. Elle admet donc une limite à l'infini. Comme $M$ ne dépend pas de $\alpha$, on a :

$$\lim_{\alpha \to +\infty} [\mu(Z(\alpha)) \cdot M + \epsilon] = 0 \cdot M + \epsilon = \epsilon$$

La limite de cette expression existe donc, et $\limsup = \lim$. On en conclut que :

$$0 \le \lim_{\alpha \to +\infty} I(\alpha) \le \epsilon$$

Ce résultat devant être satisfait pour tout $\epsilon \strictsuperieur 0$, on a :

$$\lim_{\alpha \to +\infty} I(\alpha) = 0$$

c'est-à-dire :

$$\lim_{\alpha \to +\infty} \int_{Z(\alpha)} f(x) \ d\mu(x) = 0$$


** Corollaire

On en déduit que :

\begin{align}
\int_A f(x) \ d\mu(x) &= \lim_{\alpha \to +\infty} \int_{C(\alpha)} f(x) \ d\mu(x) + \lim_{\alpha \to +\infty} \int_{Z(\alpha)} f(x) \ d\mu(x) \)

\(
&= \lim_{\alpha \to +\infty} \int_{C(\alpha)} f(x) \ d\mu(x) + 0
\end{align}

d'où :

$$\lim_{\alpha \to +\infty} \int_{C(\alpha)} f(x) \ d\mu(x) = \int_A f(x) \ d\mu(x)$$


** Généralisation

Soit $f$ est une fonction intégrable de signe quelconque et sa décomposition en fonctions positives $f = f^+ - f^-$. On a :

#+BEGIN_CENTER
\(
\lim_{\alpha \to +\infty} \int_{C(\alpha)} f^+(x) \ d\mu(x) = \int_A f^+(x) \ d\mu(x) \\ \)

\(
\lim_{\alpha \to +\infty} \int_{C(\alpha)} f^-(x) \ d\mu(x) = \int_A f^-(x) \ d\mu(x)
\)
#+END_CENTER

On en déduit que :

\begin{align}
\lim_{\alpha \to +\infty} \int_{C(\alpha)} f(x) \ d\mu(x) &= \lim_{\alpha \to +\infty} \int_{C(\alpha)} f^+ - \lim_{\alpha \to +\infty} \int_{C(\alpha)} f^- \)

\(
&= \int_A f^+ - \int_A f^- \)

\(
&= \int_A f(x) \ d\mu(x)
\end{align}


* Adhérence

Soit un ensemble $A$ vérifiant $\mu(A) \strictsuperieur 0$ et une fonction $f : A \mapsto \setR$ mesurable, essentiellement positive et majorée :

$$M = \supessentiel_{x \in A} f(x) \strictinferieur +\infty$$

Comme $\mu(A) \strictsuperieur 0$ et $f \esssuperieur 0$, on a :

$$M \ge \infessentiel_{x \in A} f(x) \ge 0$$

Soit :

$$\Theta = \left\{ \supessentiel_{x \in A} [f(x) - w(x)] : w \in \mathcal{E}_A(f) \right\}$$

et :

$$\lambda = \inf_{w \in \mathcal{E}_A(f)} \supessentiel_{x \in A} [f(x) - w(x)]$$

Comme la fonction nulle $0 \in \mathcal{E}_A(f)$, on a :

$$\lambda \le \supessentiel_{x \in A} [f(x) - 0] = M$$

Choisissons $w \in \mathcal{E}_A(f)$. On a $w \essinferieur f$, d'où $f - w \esssuperieur 0$ et :

$$\supessentiel_{x \in A} [f(x) - w(x)] \ge \infessentiel_{x \in A} [f(x) - w(x)] \ge 0$$

Donc $\Theta \ge 0$ et $\lambda = \inf \Theta \ge 0$.

Si $M = 0$, on a également $\lambda \le 0$, d'où $\lambda = 0$. Supposons à présent que $M \strictsuperieur 0$. Nous allons construire une suite $\{ w_n : n \in \setN \} \subseteq \mathcal{E}_A(f)$ convergeant vers $f$ au sens du supremum essentiel. Posons $w_0 = 0 \in \mathcal{E}_A(f)$, le réel $\Delta_0 = M / 2$ et l'ensemble :

$$A_0 = \{ x \in A : f(x) - w_0(x) \strictsuperieur \Delta_0 \}$$

On construit ensuite la fonction $w_1$ par :

#+BEGIN_CENTER
\(
w_1 = w_0 + \Delta_0 \cdot \indicatrice[A_0] =
\begin{cases}
w_0 + \Delta_0 & \text{ sur } A_0 \)

\(
w_0 & \text{ sur } A \setminus A_0
\end{cases}
\)
#+END_CENTER

La fonction $\Delta_0 \cdot \indicatrice[A_0]$ étant étagée, $w_1$ l'est aussi. En utilisant $w_0 \essinferieur f$ sur $A$ et $w_0 + \Delta_0 \strictinferieur f$ sur $A_0$, on obtient :

#+BEGIN_CENTER
\(
w_1 =
\begin{cases}
w_0 + \Delta_0 & \text{ sur } A_0 \)

\(
w_0 & \text{ sur } A \setminus A_0
\end{cases}
\essinferieur
\begin{cases}
f & \text{ sur } A_0 \)

\(
f & \text{ sur } A \setminus A_0
\end{cases}
\)
#+END_CENTER

On en conclut que $w_1 \essinferieur f$ et que $w_1 \in \mathcal{E}_A(f)$. Sur $A \setminus A_0$, on a par définition $f - w_1 = f - w_0 \le \Delta_0$. Sur $A_0$, on a :

$$f - w_1 = f - w_0 - \Delta_0 \le M - \frac{M}{2} = \frac{M}{2}$$

On en conclut que :

$$\supessentiel_{x \in A} [f(x) - w_1(x)] \le \frac{M}{2} = \Delta_0$$

Supposons à présent être arrivé à l'étape $n - 1$ avec la fonction étagée $w_{n - 1}$ vérifiant $w_{n - 1} \essinferieur f$ et :

$$\supessentiel_{x \in A} [f(x) - w_{n - 1}(x)] \le \Delta_{n - 1}$$

On construit l'étape $n$ par :

\begin{align}
\Delta_n &= \Delta_{n - 1} / 2 \)

\(
A_n &= \{ x \in A : f(x) - w_{n - 1}(x) \strictsuperieur \Delta_n \} \)

\(
w_n &= w_{n - 1} + \Delta_n \cdot \indicatrice[A_n]
\end{align}

La fonction $\Delta_n \cdot \indicatrice[A_n]$ étant étagée, $w_n$ l'est aussi. En utilisant $w_{n - 1} \essinferieur f$ sur $A$ et $w_{n - 1} + \Delta_n \strictinferieur f$ sur $A_n$, on obtient :

#+BEGIN_CENTER
\(
w_n =
\begin{cases}
w_{n - 1} + \Delta_n & \text{ sur } A_n \)

\(
w_{n - 1} & \text{ sur } A \setminus A_n
\end{cases}
\essinferieur
\begin{cases}
f & \text{ sur } A_n \)

\(
f & \text{ sur } A \setminus A_n
\end{cases}
\)
#+END_CENTER

On en conclut que $w_n \essinferieur f$ et que $w_n \in \mathcal{E}_A(f)$. Sur $A \setminus A_n$, on a $f - w_n = f - w_{n - 1} \le \Delta_n$. Sur $A_n$, on a :

$$f - w_n = f - w_{n - 1} - \Delta_n \le \Delta_{n - 1} - \Delta_n = 2 \Delta_n - \Delta_n = \Delta_n$$

On a donc :

$$\supessentiel_{x \in A} [f(x) - w_n(x)] \le \Delta_n$$

Comme :

$$\Delta_n = \frac{\Delta_{n - 1}}{2} = ... = \frac{\Delta_0}{2^{n - 1}} = \frac{M}{2^n}$$

On voit que :

$$0 \le \supessentiel_{x \in A} [f(x) - w_n(x)] \le \frac{M}{2^n}$$

Comme :

$$\limsup_{n \to \infty} \frac{M}{2^n} = \liminf_{n \to \infty} 0 = 0$$

la limite de $\supessentiel_{x \in A} [f(x) - w_n(x)]$ existe et :

$$\lim_{n \to \infty} \supessentiel_{x \in A} [f(x) - w_n(x)] = 0$$

Pour tout réel $\epsilon \strictsuperieur 0$, on peut donc trouver un $n$ tel que :

$$\supessentiel_{x \in A} [f(x) - w_m(x)] \le \epsilon$$

pour tout $m \in \setN$ vérifiant $m \ge n$. Par conséquent, $\lambda$ ne peut pas être strictement positif et :

$$\inf_{w \in \mathcal{E}_A(f)} \supessentiel_{x \in A} [f(x) - w(x)] = 0$$


* Multiplication par un réel

Soit une fonction intégrable $f$ essentiellement positive et le réel $\lambda \strictsuperieur 0$. Si $w$ est une fonction étagée, on voit que $w \le f \Leftrightarrow \lambda \cdot w \le \lambda \cdot f$. On peut donc associer une fonction $\lambda \cdot w \in \mathcal{E}_A(\lambda \cdot f)$ à toute fonction $w \in \mathcal{E}_A(f)$, et réciproquement. Par linéarité de l'intégrale des fonctions étagées, on en conclut que :

$$\int_A \lambda \cdot w(x) \ d\mu(x) = \lambda \cdot \int_A w(x) \ d\mu(x)$$

En passant au supremum sur $w \in \mathcal{E}_A(f) \Leftrightarrow \lambda \cdot w \in \mathcal{E}_A(\lambda \cdot f)$, on obtient donc :

$$\int_A \lambda \cdot f(x) \ d\mu(x) = \lambda \cdot \int_A f(x) \ d\mu(x)$$

Le même résultat est bien évidemment vérifié lorsque $\lambda = 0$. Lorsque $\lambda \strictinferieur 0$, on pose $\alpha = - \lambda \strictsuperieur 0$. On a alors :

\begin{align}
\int_A \lambda \cdot f(x) \ d\mu(x) &= \int_A - \alpha \cdot f(x) \ d\mu(x) \)

\(
&= - \int_A \alpha \cdot f(x) \ d\mu(x) \)

\(
&= - \alpha \int_A f(x) \ d\mu(x) \)

\(
&= \lambda \int_A f(x) \ d\mu(x)
\end{align}

Nous avons donc prouvé la relation pour tout $\lambda \in \setR$.


* Addition


** Positives et majorées

Soit deux fonctions $f,g : A \mapsto \setR$ intégrables, essentiellement positives et majorées :

#+BEGIN_CENTER
\(
\supessentiel \{ f(x) : x \in A \} \strictinferieur +\infty \)

\(
\supessentiel \{ g(x) : x \in A \} \strictinferieur +\infty
\)
#+END_CENTER

Soit le réel $\epsilon \strictsuperieur 0$.

  - Le supremum étant dans l'adhérence, on peut trouver un $u \in \mathcal{E}_A(f)$ tel que :

$$\int_A u(x) \ d\mu(x) \ge \int_A f(x) \ d\mu(x) - \epsilon$$

et un $v \in \mathcal{E}_A(g)$ tel que :

$$\int_A v(x) \ d\mu(x) \ge \int_A g(x) \ d\mu(x) - \epsilon$$

On sait que $u + v$ est une fonction étagée. Les conditions $u \essinferieur f$ et $v \essinferieur g$ impliquent que $u + v \essinferieur f + g$. On a donc $u + v \in \mathcal{E}_A(f + g)$. En utilisant la linéarité des intégrales de fonctions étagées et la définition du supremum, il vient :

\begin{align}
\int_A u(x) \ d\mu(x) + \int_A v(x) \ d\mu(x) &=  \int_A [u(x) + v(x)] \ d\mu(x) \)

\(
&\le \int_A [f(x) + g(x)] \ d\mu(x)
\end{align}

En rassemblant ces résultats, on obtient :

$$\int_A f(x) \ d\mu(x) + \int_A g(x) \ d\mu(x) - 2 \epsilon \le \int_A [f(x) + g(x)] \ d\mu(x)$$

Cette relation étant valable quel que soit $\epsilon \strictsuperieur 0$, on a  :

$$\int_A f(x) \ d\mu(x) + \int_A g(x) \ d\mu(x) \le \int_A [f(x) + g(x)] \ d\mu(x)$$

  - Comme $f$ et $g$ sont essentiellement majorées, on peut trouver un $u \in \mathcal{E}_A(f)$ et un $v \in \mathcal{E}_A(g)$ vérifiant :

#+BEGIN_CENTER
\(
\supessentiel \{ f(x) - u(x) : x \in A \} \le \epsilon \)

\(
\supessentiel \{ g(x) - v(x) : x \in A) \} \le \epsilon
\)
#+END_CENTER

Donc $f \essinferieur u + \epsilon$ et $g \essinferieur v + \epsilon$. On en conclut que $f + g \essinferieur u + v + 2 \epsilon$, d'où :

\begin{align}
\int_A [f(x) + g(x)] \ d\mu(x) &\le \int_A [u(x) + v(x) + 2 \epsilon] \ d\mu(x) \)

\(
&\le \int_A u(x) \ d\mu(x) + \int_A v(x) \ d\mu(x) + 2 \epsilon \cdot \mu(A)
\end{align}

par linéarité des intégrales de fonctions étagées. On a aussi, par définition du supremum :

#+BEGIN_CENTER
\(
\int_A u(x) \ d\mu(x) \le \int_A f(x) \ d\mu(x) \\ \)

\(
\int_A v(x) \ d\mu(x) \le \int_A g(x) \ d\mu(x)
\)
#+END_CENTER

On a finalement la borne :

$$\int_A [f(x) + g(x)] \ d\mu(x) \le \int_A f(x) \ d\mu(x) + \int_A g(x) \ d\mu(x) + 2 \epsilon \cdot \mu(A)$$

Cette inégalité devant être satisfaite pour tout $\epsilon \strictsuperieur 0$, on en déduit que :

$$\int_A [f(x) + g(x)] \ d\mu(x) \le \int_A f(x) \ d\mu(x) + \int_A g(x) \ d\mu(x)$$


L'intégrale de $f + g$ devant être simultanément supérieure et inférieure à la somme de l'intégrale de $f$ et de l'intégrale de $g$, on en conclut que :

$$\int_A [f(x) + g(x)] \ d\mu(x) = \int_A f(x) \ d\mu(x) + \int_A g(x) \ d\mu(x)$$


** Positives

Soit deux fonctions $f,g$ intégrables et essentiellement positives. Posons :

#+BEGIN_CENTER
\(
F(\alpha) = \{ x \in A : f(x) \le \alpha \} \)

\(
G(\alpha) = \{ x \in A : g(x) \le \alpha \}
\)
#+END_CENTER

et :

#+BEGIN_CENTER
\(
N(\alpha) = \{ x \in A : f(x) \strictsuperieur \alpha \} = A \setminus F(\alpha) \)

\(
T(\alpha) = \{ x \in A : g(x) \strictsuperieur \alpha \} = A \setminus G(\alpha)
\)
#+END_CENTER

pour tout $\alpha \in \setR$. Pour tous réels $\alpha,\beta$ vérifiant $\alpha \ge \beta$, il est clair que $N(\alpha) \subseteq N(\beta)$ et $T(\alpha) \subseteq T(\beta)$. Soit :

$$C(\alpha) = F(\alpha) \cap G(\alpha) = A \setminus (N(\alpha) \cup T(\alpha))$$

et :

$$Z(\alpha) = A \setminus C(\alpha) = N(\alpha) \cup T(\alpha)$$

Choisissons des réels $\alpha,\beta$ tels que $\alpha \ge \beta$ et un $x \in Z(\alpha)$. On a soit $x \in N(\alpha)$, d'où $x \in N(\beta)$ et $x \in Z(\beta)$, soit $x \in T(\alpha)$, d'où $x \in T(\beta)$ et $x \in Z(\beta)$. On en conclut que $Z(\alpha) \subseteq Z(\beta)$.
On voit que :

$$0 \le \mu(Z(\alpha)) \le \mu(N(\alpha)) + \mu(T(\alpha))$$

Comme :

$$\limsup_{\alpha \to +\infty} [\mu(N(\alpha)) + \mu(T(\alpha))] = \liminf_{\alpha \to +\infty} 0 = 0$$

la fonction $\alpha \mapsto \mu(Z(\alpha))$ converge et :

$$\lim_{\alpha \to +\infty} \mu(Z(\alpha)) = 0$$

Si $\varphi$ est intégrable, par exemple $\varphi \in \{f, g, f + g\}$, on a donc :

$$\lim_{\alpha \to +\infty} \int_{C(\alpha)} \varphi(x) \ d\mu(x) = \int_A \varphi(x) \ d\mu(x)$$

Sur $C(\alpha) \subseteq F(\alpha)$, on a $0 \essinferieur f \essinferieur \alpha$. Le supremum essentiel existe par conséquent sur $C(\alpha)$ et :

$$0 \le \supessentiel \{ f(x) : x \in C(\alpha) \} \le \alpha$$

On conclut de même que :

$$0 \le \supessentiel \{ g(x) : x \in C(\alpha) \} \le \alpha$$

Les fonctions $f$ et $g$ sont donc essentiellement majorées sur $C(\alpha)$ et on a :

$$\int_{C(\alpha)} [f(x) + g(x)] \ d\mu(x) = \int_{C(\alpha)} f(x) \ d\mu(x) + \int_{C(\alpha)} g(x) \ d\mu(x)$$

Passant à la limite pour $\alpha \to +\infty$, on obtient alors :

$$\int_A [f(x) + g(x)] \ d\mu(x) = \int_A f(x) \ d\mu(x) + \int_A g(x) \ d\mu(x)$$


** Soustraction

Soit $f,g$ deux fonctions intégrables essentiellement positives vérifiant $h = f - g \esssuperieur 0$. Comme $f = g + h$, on a :

$$\int_A f(x) \ d\mu(x) = \int_A g(x) \ d\mu(x) + \int_A h(x) \ d\mu(x)$$

On en déduit que :

$$\int_A h(x) \ d\mu(x) = \int_A f(x) \ d\mu(x) - \int_A g(x) \ d\mu(x)$$

c'est-à-dire :

$$\int_A [f(x) - g(x)] \ d\mu(x) = \int_A f(x) \ d\mu(x) - \int_A g(x) \ d\mu(x)$$


** Généralisation

Soit deux fonctions intégrables $f,g$ et leurs décompositions en fonctions positives $f = f^+ - f^-$ et $g = g^+ - g^-$. Posons :

#+BEGIN_CENTER
\(
s^+ = f^+ + g^+ \)

\(
s^- = f^- + g^-
\)
#+END_CENTER

On a :

$$f + g = f^+ - f^- + g^+ - g^- = (f^+ + g^+) - (f^- + g^-) = s^+ - s^-$$

Décomposons $A$ en les ensembles :

#+BEGIN_CENTER
\(
P = \{ x \in A : s^+(x) - s^-(x) \ge 0 \} \)

\(
M = \{ x \in A : s^+(x) - s^-(x) \strictinferieur 0 \}
\)
#+END_CENTER

Comme $s^+ - s^- \esssuperieur 0$ sur $P$, on a :

$$\int_P [s^+(x) - s^-(x)] \ d\mu(x) = \int_P s^+(x) \ d\mu(x) - \int_P s^-(x) \ d\mu(x)$$

Comme $s^+ - s^- \essinferieur 0$ sur $M$, on y a $s^- - s^+ \esssuperieur 0$ et :

\begin{align}
\int_M [s^+(x) - s^-(x)] \ d\mu(x) &= - \int_M [s^-(x) - s^+(x)] \ d\mu(x) \)

\(
&= - \left[ \int_M s^-(x) \ d\mu(x) - \int_M s^+(x) \ d\mu(x) \right] \)

\(
&= \int_M s^+(x) \ d\mu(x) - \int_M s^-(x) \ d\mu(x)
\end{align}

Rassemblant ces résultats, il vient :

\begin{align}
\int_A [f(x) + g(x)] \ d\mu(x) &= \int_A [s^+(x) - s^-(x)] \ d\mu(x) \)

\(
&= \int_P [s^+(x) - s^-(x)] \ d\mu(x) + \int_M [s^+(x) - s^-(x)] \ d\mu(x) \)

\(
&= \int_P s^+ - \int_P s^- + \int_M s^+ - \int_M s^- \)

\(
&= \int_A s^+ - \int_A s^- \)

\(
&= \int_A [f^+(x) + g^+(x)] \ d\mu(x) - \int_A [f^-(x) + g^-(x)] \ d\mu(x) \)

\(
&= \int_A f^+ + \int_A g^+ - \int_A f^- - \int_A g^- \)

\(
&= \int_A f(x) \ d\mu(x) + \int_A g(x) \ d\mu(x)
\end{align}

L'intégrale d'une somme est la somme des intégrales.


* Linéarité

Soit les réels $\alpha,\beta$ et les fonctions intégrables $f,g : A \mapsto \setR$. On a :

\begin{align}
\int_A [\alpha \cdot f(x) + \beta \cdot g(x)] \ d\mu(x) &= \int_A \alpha \cdot f(x) \ d\mu(x) + \int_A \beta \cdot g(x) \ d\mu(x) \)

\(
&= \alpha \cdot \int_A f(x) \ d\mu(x) + \beta \cdot \int_A g(x) \ d\mu(x)
\end{align}

L'intégrale est linéaire.


