
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Introduction
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Idée générale

Tant d’ouvrages traitent abondemment et rigoureusement des domaines
les plus divers que couvrent les mathématiques ! L’objectif de ce
livre n’est pas d’en ajouter un de plus au bas d’une longue liste,
mais d’adopter une approche différente.

Je l’ai voulu comme une introduction rapide et intuitive aux notions
les plus diverses que l’on rencontre dans ce monde merveilleux et
fascinant. À ce titre, les démonstrations que vous rencontrerez au fil
de ces pages pourraient faire frémir plus d’un puriste : il s’agit
ici, non pas de « prouver » au sens strict du terme, mais de montrer
comment les différents concepts s’agencent entre-eux. Il s’agit avant
tout de faire acquérir au lecteur une intuition mathématique que
j’estime au moins aussi indispensable à l’apprentissage que la rigueur
logique. Car enfin, de quoi sert la rigueur à quelqu’un qui ne
« voit » pas où on veut en venir ?

Cet ouvrage est également conçu pour qu’un débutant puisse le lire
aussi agréablement qu’un mathématicien confirmé. Il existe donc deux
méthodes possibles pour parcourir cet ouvrage :

  - Les premiers chapitres définissent les notions fondamentales.
    L’édifice s’éleve ensuite patiemment vers des notions plus
    avancées. Le lecteur pourra donc entamer ce livre où il le
    souhaite, en fonction de ses connaissances. Qu’il n’hésite tout de
    même pas à jeter un oeil sur les notions qui lui semblent
    élémentaires : il sera parfois surpris par la complexité ou
    l’élégance de leur construction.

  - Afin de guider le lecteur qui voudrait accéder directement au
    domaine de son choix, une liste des « dépendances » est placée au
    début de chaque chapitre. Il s’agit en fait d’une liste d’autres
    chapitres, prérequis conseillés pour une compréhension optimale du
    chapitre choisi. Ces prérequis ne sont bien entendu pas à prendre
    au pied de la lettre. Il est même plutôt recommandé de commencer à
    lire, et de n’utiliser les dépendances que si la compréhension
    pose problème. N’oubliez pas non plus que ces dépendances sont
    récursives, à vous de reconstruire l’arbre jusqu’à la racine si
    besoin est.

* Portée des notations

Les notations sont valables jusqu’à leur redéfinition au sein d’un
autre concept. Le plus souvent, elles s’étendent sur une section,
parfois pendant un chapitre entier. Certaines notations, les plus
importantes, sont valables tout au long de l’ouvrage.

* Abstraction

La première étape de l’abstraction consiste à repérer les propriétés
fondamentales communes à plusieurs types différents d’objets
mathématiques. Ensuite, on crée une nouvelle structure en imposant
qu’elle vérifie ces propriétés. Tous les résultats qui s’en déduiront
auront alors un champ d’application plus large que dans les
applications de départ.

* Récurrence

Supposons que nous ayons à prouver que $A_n$ est vraie pour tout
entier $n \in \mathbb{N}$ tel que $n \ge p$. Si nous prouvons que
$A_p$ est vrai et que la véracité de $A_n$ implique celle de
$A_{n+1}$, la démonstration est finie. En effet, on a alors :

\begin{equation}
A_p \Rightarrow A_{p+1} \Rightarrow A_{p+2} \Rightarrow ... \Rightarrow A_n
\end{equation}

pour tout $n \ge p$ arbitraire.


* Notations

| $=$               | Égalité entre deux objets                       |
| $\ne$             | Non égalité entre deux objets                   |
| $\in$             | Appartenance à un ensemble                      |
| $\notin$          | Non-appartenance à un ensemble                  |
| $\equiv$          | Équivalence                                     |
| $\Rightarrow$     | La condition de gauche implique celle de droite |
| $\Leftarrow$      | La condition de droite implique celle de gauche |
| $\Leftrightarrow$ | Les deux conditions s’impliquent mutuellement   |
| $:$               | Tel que                                         |
| $\exists$         | Il existe                                       |
| $\forall$         | Pour tout                                       |
| $\subseteq$       | Inclusion                                       |
| $\subset$         | Inclusion stricte                               |
| $\cup$            | Union d’ensembles                               |
| $\cap$            | Intersection d’ensembles                        |
| $\sousens$        | Ensemble des sous-ensembles                     |
| $\partition$      | Ensemble des partitions                         |
| $\tribu$          | Ensemble des tribus                             |
| $\relation$       | Relation                                        |
| $\le$             | Ordre large                                     |
| $<$               | Ordre strict                                    |
| $\ensinferieur$   | Comparaison entre ensembles                     |
| major             | Ensemble des majorants                          |
| minor             | Ensemble des minorants                          |
| $\max$            | Maximum                                         |
| $\min$            | Minimum                                         |
| $\sup$            | Supremum                                        |
| $\inf$            | Infimum                                         |
| $\arg$            | Argument                                        |
| $\distance$       | Distance                                        |
| adh               | Adhérence                                       |
| int               | Intérieur                                       |
| $\frontiere$      | Frontière                                       |
| $\boule$          | Boule                                           |
| $\fonction$       | Fonction                                        |
| $\setB$           | Ensemble de Boole                               |
| $\setN$           | Ensemble des naturels                           |
| $\setZ$           | Ensemble des entiers                            |
| $\setQ$           | Ensemble des rationnels                         |
| $\setR$           | Ensemble des réels                              |
| $\setC$           | Ensemble des complexes                          |
| $\corps$          | Corps quelconque                                |
