
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Limites
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:limites}

* Dépendances

  - Chapitre \ref{chap:distances} : Les distances


* Définition

Soit les ensembles $E,F$ munis respectivement des distances $\distance_E$ et $\distance_F$, un sous-ensemble $D \subseteq E$ et la fonction $f : D \mapsto F$. Comme la distance utilisée est sans ambiguité d'après la nature des objets dont elle mesure l'éloignement :

#+BEGIN_CENTER
\(
\distance(x,y) = \distance_E(x,y) \Leftrightarrow x,y \in E \)

\(
\distance(x,y) = \distance_F(x,y) \Leftrightarrow x,y \in F
\)
#+END_CENTER

on note dans la suite de ce chapitre $\distance$ à la place de $\distance_E$ et de $\distance_F$.

Plaçons nous dans $A \subseteq D$. Nous nous intéressons au cas où $f(x)$ se rapproche de plus en plus d'un certain $L \in F$ lorsque $x \in A$ se rapproche suffisamment d'un certain $a \in E$. Pour toute précision $\epsilon \in \corps$, $\epsilon \strictsuperieur 0$ aussi petite que l'on veut, on doit alors pouvoir trouver un niveau de proximité $\delta(\epsilon) \in \corps$, $\delta(\epsilon) \strictsuperieur 0$ tel que :

$$\distance(f(x),L) \le \epsilon$$

pour tout les $x \in A$ vérifiant :

$$\distance(x,a) \le \delta(\epsilon)$$

Si cette condition est remplie, on dit que $L$ est la limite de $f$ en $a$, et on note :

$$\lim_{ \substack{ x \to a \\ x \in A } } f(x) = L$$


** Notations

Lorsque l'ensemble $A$ est évident d'après le contexte, on note simplement :

$$\lim_{ x \to a } f(x) = \lim_{ \substack{ x \to a \\ x \in A } } f(x)$$

Au lieu de noter l'ensemble, on peut citer les conditions qui le définissent. Ainsi par exemple :

$$\lim_{ \substack{ x \to a \\ x \ne a } } f(x) = \lim_{ \substack{ x \to a \\ x \in X(a) } } f(x)$$

où :

$$X(a) = D \setminus \{ a \}$$

Autre application :

$$\lim_{ \substack{ x \to a \\ x \le a } } f(x) = \lim_{ \substack{ x \to a \\ x \in I(a) } } f(x)$$

où :

$$I(a) = \{ x \in D : x \le a \}$$


** Remarque

Rien n'impose que $a$ appartienne à $A$. L'existence de la limite de $f$ en $a$ n'implique donc pas que la fonction $f$ soit définie en $a$.


** Unicité

Supposons que $b$ et $c$ soient deux limites de $f$ en $a$. Soit $\epsilon \strictsuperieur 0$. On peut alors trouver un $\alpha \strictsuperieur 0$ tel que :

$$\distance(f(x),b) \le \frac{\epsilon}{2}$$

pour tout $x$ vérifiant $\distance(x,a) \le \alpha$ et un $\beta \strictsuperieur 0$ tel que :

$$\distance(f(x),c) \le \frac{\epsilon}{2}$$

pour tout $x$ vérifiant $\distance(x,a) \le \beta$. Posons $\delta = \min\{\alpha,\beta\}$. Si $x$ vérifie $\distance(x,a) \le \delta$, on a :

$$\{ \ \distance(f(x),b) , \ \distance(f(x),c) \ \} \le \frac{\epsilon}{2}$$

et :

$$\distance(b,c) \le \distance(b,f(x)) + \distance(f(x),c) \le \frac{\epsilon}{2} + \frac{\epsilon}{2} = \epsilon$$

Comme ce doit être vrai pour tout $\epsilon$ strictement positif, on en conclut que $\distance(b,c) = 0$, c'est-à-dire $b = c$. La limite est donc unique.


** Inclusion des boules

Soit :

#+BEGIN_CENTER
\(
B_1(\delta) = \boule(a,\delta) \cap A \)

\(
B_2(\epsilon) = \boule(f(a),\epsilon)
\)
#+END_CENTER

La définition de la limite revient à exiger que, pour tout $\epsilon \strictsuperieur 0$, on puisse trouver un $\delta \strictsuperieur 0$ tel que tout élément de $B_1(\delta)$ auquel on applique la fonction $f$ se retrouve dans $B_2(\epsilon)$. Autrement dit, $f(B_1(\delta)) \subseteq B_2(\epsilon)$.


** Limite de la distance

Si $L$ est la limite de $f$ en $a$, la distance doit converger vers zéro par définition :

$$\lim_{ \substack{ x \to a \\ x \in A } } \distance(f(x),L) = 0$$


* Chemin

Supposons qu'il existe des sous-ensembles $A,B \subseteq D$ tels que :

$$\lim_{ \substack{ x \to a \\ x \in A } } f(x) \ne \lim_{ \substack{ x \to a \\ x \in B } } f(x)$$

On dit alors que la limite dépend du chemin parcouru.


* Limites à l'infini

Si $E$ est un ensemble ordonné, on peut définir la notion de limite à l'infini. Soit une fonction $f : E \mapsto F$ et $L \in F$. Si, pour toute précision $\epsilon > 0$, on peut trouver une borne inférieure $I(\epsilon) \in E$ telle que :

$$\distance(f(x),L) \le \epsilon$$

pour tout $x \in E$ vérifiant $x \ge I(\epsilon)$, on dit alors que $f$ tend vers $L$ à l'infini positif et on écrit :

$$\lim_{ x \to +\infty } f(x) = L$$

Symétriquement, si pour toute précision $\epsilon > 0$, on peut trouver une borne supérieure $S(\epsilon) \in E$ telle que :

$$\distance(f(x),L) \le \epsilon$$

pour tout $x \in E$ vérifiant $x \le S(\epsilon)$, on dit alors que $f$ tend vers $L$ à l'infini négatif et on écrit :

$$\lim_{ x \to -\infty } f(x) = L$$


** Notation

On a également la notation alternative :

$$\lim_{ x \to \infty } f(x) = \lim_{ x \to +\infty } f(x)$$

ainsi que :

\begin{align}
f(+\infty) &= \lim_{ x \to +\infty } f(x) \\
f(-\infty) &= \lim_{ x \to -\infty } f(x)
\end{align}

* Limite supremum et infimum

** Infini positif

Il arrive que la limite à l'infini positif d'une fonction $f : E \mapsto F$ n'existe pas mais que la limite de la fonction $g : E \mapsto F$, que l'on suppose correctement définie pour tout $x \in E$ par :

$$g(x) =  \inf \{ f(y) : y \in E, \ y \ge x \}$$

existe. On note alors :

$$\liminf_{ x \to +\infty } f(x) = \lim_{ x \to +\infty } \inf \{ f(y) : y \in E, \ y \ge x \}$$

On définit pareillement la limite du supremum :

$$\limsup_{ x \to +\infty } f(x) = \lim_{ x \to +\infty } \sup \{ f(y) : y \in E, \ y \ge x \}$$


** Infini négatif

On définit également :

$$ \limsup_{ x \to -\infty } f(x) = \lim_{ x \to -\infty } \sup \{ f(y) : y \in E, \ y \le x \} $$

$$ \liminf_{ x \to -\infty } f(x) = \lim_{ x \to -\infty } \inf \{ f(y) : y \in E, \ y \le x \} $$

* Limites infinies

Si $F$ est un ensemble ordonné, on peut définir la notion de limite infinie.


** Positive

Si, pour tout $G \in F$ aussi grand que l'on veut, on peut trouver une proximité $\delta(G) > 0$ vérifiant :

$$f(x) \ge G$$

pour tout les $x \in A$ assez proche de $a$ :

$$\distance(x,a) \le \delta(G)$$

on dit alors que $f$ tend vers l'infini positif en $a$ et on écrit :

$$\lim_{ x \to a } f(x) = +\infty$$


** Négative

Si, pour tout $P \in F$ aussi petit que l'on veut, on peut trouver une proximité $\delta(P) > 0$ vérifiant :

$$f(x) \le P$$

pour tout les $x \in A$ assez proche de $a$ :

$$\distance(x,a) \le \delta(P)$$

on dit alors que $f$ tend vers l'infini négatif en $a$ et on écrit :

$$\lim_{ x \to a } f(x) = -\infty$$


** Notation

On a les notations alternatives :

#+BEGIN_CENTER
\(
f(a) = +\infty \quad \Leftrightarrow \quad \lim_{ x \to a } f(x) = +\infty \)

\(
f(a) = -\infty \quad \Leftrightarrow \quad \lim_{ x \to a } f(x) = -\infty
\)
#+END_CENTER


* Limite infinie à l'infini

On suppose que $E$ et $F$ sont ordonnés. On dit que la limite de $f$ à l'infini positif est l'infini positif et on le note :

$$\lim_{x \to +\infty} f(x) = +\infty$$

si, pour tout $G \in F$ aussi grand que l'on veut, on peut trouver une borne inférieure $I(G) \in E$ telle que :

$$f(x) \ge G$$

pour tout $x \in E$ vérifiant $x \ge I(G)$. On dit que la limite de $f$ à l'infini positif est l'infini négatif et on le note :

$$\lim_{x \to +\infty} f(x) = -\infty$$

si, pour tout $P \in F$ aussi petit que l'on veut, on peut trouver une borne inférieure $I(G) \in E$ telle que :

$$f(x) \le P$$

pour tout $x \in E$ vérifiant $x \ge I(G)$. On dit que la limite de $f$ à l'infini négatif est l'infini positif et on le note :

$$\lim_{x \to -\infty} f(x) = +\infty$$

si, pour tout $G \in F$ aussi grand que l'on veut, on peut trouver une borne supérieure $S(G) \in E$ telle que :

$$f(x) \ge G$$

pour tout $x \in E$ vérifiant $x \le S(G)$. On dit que la limite de $f$ à l'infini négatif est l'infini négatif et on le note :

$$\lim_{x \to -\infty} f(x) = -\infty$$

si, pour tout $P \in F$ aussi petit que l'on veut, on peut trouver une borne supérieure $S(G) \in E$ telle que :

$$f(x) \le P$$

pour tout $x \in E$ vérifiant $x \le S(G)$.


