
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Matrices
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:matrices}

* Dépendances

  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes

* Définition

Les matrices sont des tableaux de réels, de complexes, ou de composantes
d'une autre nature appartenant à un corps quelconque. Voici un exemple
d'une matrice à $m$ lignes et $n$ colonnes :

#+BEGIN_CENTER
\(
A = \begin{Matrix}{cccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots &        & \ddots &  \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{Matrix}
\)
#+END_CENTER

où les $a_{ij}$ appartiennent à un corps $\corps$. On a également des versions simplifiées de cette notation :

$$A = ( a_{ij} )_{i,j} = [ a_{ij} ]_{i,j}$$

Par convention, le numéro de ligne passe avant le numéro de colonne à l'extérieur de la parenthèse (ou du crochet).

On note $\matrice(\corps,m,n)$ l'ensemble des matrices à $m$ lignes et $n$ colonnes. On dit d'une matrice $A \in \matrice(\corps,m,n)$ qu'elle est de taille $(m,n)$.


* Composantes

Soit $A = (a_{ij})_{i,j}$. La fonction $\composante_{ij}$ donne la
composante située à la $i^{ème}$ ligne et à la $j^{ème}$ colonne :

$$a_{ij} = \composante_{ij} A$$


* Blocs

Soit $A = (a_{ij})_{i,j}$. La fonction $\bloc_{ijkl}$ donne la sous-matrice située entre la $i^{ème}$ et la $j^{ème}$ ligne, ainsi qu'entre la $k^{ième}$ et la $l^{ième}$ colonne :

#+BEGIN_CENTER
\(
\bloc_{ijkl} A = \begin{Matrix}{cccc}
a_{ik} & a_{i,k+1} & \ldots & a_{il} \\
a_{i+1,k} & a_{i+1,k+1} & \ldots & a_{i+1,l} \\
\vdots &        & \ddots &  \vdots \\
a_{jk} & a_{j,k+1} & \ldots & a_{jl}
\end{Matrix}
\)
#+END_CENTER

On appelle bloc une telle sous-matrice.

* Partitionnement en blocs

Il est parfois très utile de partitionner une matrice en blocs, ou de former une matrice plus grande à partir de matrices de tailles plus petites. On note alors :

#+BEGIN_CENTER
\begin{eqnarray*}
A &=&
\begin{Matrix}{cc}
B & C \\
D & E
\end{Matrix} \\
&=&
\begin{Matrix}{cccccc}
b_{11} & \ldots & b_{1n} & c_{11} & \ldots & c_{1p} \\
\vdots &        & \vdots & \vdots &        & \vdots \\
b_{m1} & \ldots & b_{mn} & c_{m1} & \ldots & c_{mp} \\
d_{11} & \ldots & d_{1n} & e_{11} & \ldots & e_{1p} \\
\vdots &        & \vdots & \vdots &       & \vdots \\
d_{r1} & \ldots & d_{rn} & e_{r1} & \ldots & e_{rp}
\end{Matrix}
\end{eqnarray*}
#+END_CENTER

où les $b_{ij},c_{ij},d_{ij},e_{ij}$ sont respectivement les composantes des matrices $B,C,D,E$. Ces matrices doivent évidemment être de tailles compatibles (nombres de lignes identiques pour $B$ et $C$, ainsi que pour $D$ et $E$ ; nombres de colonnes identiques pour $B$ et $D$, ainsi que pour $C$ et $E$).


* Formes lignes et colonnes

On peut exprimer une matrice $A \in \matrice(\corps,m,n)$ sous la forme de lignes superposées. Soit :

#+BEGIN_CENTER
\(
A =
\begin{Matrix}{c}
l_1 \\
l_2 \\
\vdots \\
l_m
\end{Matrix}
\)
#+END_CENTER

où les $l_i \in \matrice(\corps,1,n)$ sont les lignes de $A$. On note :

$$\ligne_i A = l_i$$

On peut aussi l'exprimer sous la forme de colonnes juxtaposées. Soit :

$$A = [c_1 \ c_2 \ldots \ c_n]$$

où les $c_i \in \matrice(\corps,m,1)$ sont les colonnes de $A$. On note :

$$\colonne_i A = c_i$$


* Transposée

Transposer une matrice $A = (a_{ij})_{i,j} \in \matrice(\corps,m,n)$ consiste à agencer ses lignes en colonnes et vice-versa :

#+BEGIN_CENTER
\(
A^T = \begin{Matrix}{cccc}
a_{11} & a_{21} & \ldots & a_{m1} \\
a_{12} & a_{22} & \ldots & a_{m2} \\
\vdots &        & \ddots &  \vdots \\
a_{1n} & a_{2n} & \ldots & a_{mn}
\end{Matrix} = (a_{ji})_{i,j}
\)
#+END_CENTER

On voit que la transposée $A^T \in \matrice(\corps,n,m)$.

On a clairement :

$$\big( A^T \big)^T = A$$

* Vecteurs lignes et colonnes

On peut considérer un vecteur ligne comme une matrice ne possédant
qu'une seule ligne. Un vecteur ligne est donc de taille générique
$(1,n)$.

De même, on peut considérer un vecteur colonne omme une matrice ne
possédant qu'une seule colonne. Un vecteur colonne est donc de taille
générique $(m,1)$.

Les vecteurs /colonne/ sont notés :

$$x = (x_i)_i$$

On a aussi :

$$x_i = \composante_i x$$

** Transposée

Soit le $n$-tuple $x \in \corps^n$ représenté par le vecteur ligne :

$$l = [x_1 \ x_2 \ \ldots \ x_n]$$

et le vecteur colonne :

#+BEGIN_CENTER
$$ c = \begin{Matrix}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{Matrix} $$
#+END_CENTER

On a clairement :

#+BEGIN_CENTER
$$ \begin{Matrix}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{Matrix}^T
=
[x_1 \ x_2 \ \ldots \ x_n] $$
#+END_CENTER

et :

#+BEGIN_CENTER
$$ [x_1 \ x_2 \ \ldots \ x_n]^T =
\begin{Matrix}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{Matrix} $$
#+END_CENTER

autrement dit, le vecteur ligne est la transposée du vecteur colonne :

$$ l = c^T $$

et vice versa :

$$ c = l^T $$

** Équivalence avec $\corps^n$

A partir d'un $n$-tuple $(x_1,x_2,...,x_n) \in \corps^n$, on peut former
un vecteur ligne $l \in \matrice(\corps,1,n)$ et un vecteur colonne $c
\in \matrice(\corps,n,1)$. Les réciproques étant également vraies,
on a les équivalences :

#+begin_center
$\matrice(\corps,1,n) \equiv \matrice(\corps,n,1) \equiv \corps^n$
#+end_center

* Carrées et rectangulaires

Les matrices $A \in \matrice(\corps,n,n)$ ayant même nombre
de colonnes et de lignes sont dites « carrées ». Les
matrices $A \in \matrice(\corps,m,n)$ avec $m \ne n$ sont dites
« rectangulaires ». Lorsque $m \strictinferieur n$, on dit que la
matrice est « longue ». Si $m \strictsuperieur n$, on dit que la
matrice est « haute ».


* Matrices diagonales

Une matrice diagonale contient des composantes nulles partout, à
l'exception de la diagonale où aucune contrainte n'est fixée. On peut
représenter une matrice diagonale $D \in \matrice(\corps,m,n)$ par :

$$D = ( d_i \cdot \indicatrice_{ij} )_{i,j}$$

On peut aussi former une matrice diagonale de taille $(m,n)$ à partir
d'un vecteur $d = (d_i)_i$ de taille $(p,1)$, où $p \le \min \{ m ,
n \}$. On le note :

$$D = \diagonale_{m,n}(d) = \diagonale_{m,n}(d_1,...,d_p)$$

où :

#+BEGIN_CENTER
$$ \composante_{ij} \diagonale_{m,n}(d_1,...,d_p) =
\begin{cases}
d_i & \text{ si } i = j \in \{1,2,...,p\} \\
0 & \text{ sinon}
\end{cases} $$
#+END_CENTER


** Carrée

Dans le cas particulier où $m = n$, on note aussi :

$$\diagonale_n(d) = \diagonale_{n,n}(d)$$


* Matrices triangulaires

Les composantes des matrices triangulaires supérieures ne peuvent être non nulles qu'au-dessus de la diagonale, c'est-à-dire lorsque $i \le j$. Elles peuvent se représenter par :

$$T = (t_{ij} \cdot \tau^+_{ij})_{i,j}$$

où :

#+BEGIN_CENTER
$$ \tau^+_{ij} =
\begin{cases}
1 & \mbox{ si } i \le j \\
0 & \mbox{ si } i \strictsuperieur j
\end{cases} $$
#+END_CENTER

Les composantes des matrices triangulaires inférieures ne peuvent être non nulles qu'au-dessous de la diagonale, c'est-à-dire lorsque $i \ge j$. Elles peuvent se représenter par :

$$T = (t_{ij} \cdot \tau^-_{ij})_{i,j}$$

où :

#+BEGIN_CENTER
$$ \tau^-_{ij} =
\begin{cases}
1 & \mbox{ si } i \ge j \\
0 & \mbox{ si } i \strictinferieur j
\end{cases} $$
#+END_CENTER


* Egalité

Il est clair que deux matrices $A,B \in \matrice(\corps,m,n)$ :

#+BEGIN_CENTER
\(
A = ( a_{ij} )_{i,j} \)

\(
B = ( b_{ij} )_{i,j}
\)
#+END_CENTER

sont égales ($A = B$) si tous leurs éléments le sont :

$$a_{ij} = b_{ij}$$

pour tout $(i,j) \in \{ 1,2,...,m \} \times \{ 1,2,...,n \}$.


* Ordre partiel

Soit les matrices $A,B \in \matrice(\corps,m,n)$ :

#+BEGIN_CENTER
\(
A = ( a_{ij} )_{i,j} \)

\(
B = ( b_{ij} )_{i,j}
\)
#+END_CENTER

On dit que $A$ est inférieure à $B$, et on le note $A \le B$, si :

$$a_{ij} \le b_{ij}$$

pour tout $(i,j) \in \{ 1,2,...,m \} \times \{ 1,2,...,n \}$.


* Addition et soustraction

Soit les matrices de tailles identiques $A, B \in \matrice(\corps,m,n)$ :

#+BEGIN_CENTER
\(
A = (a_{ij})_{i,j} \)

\(
B = (b_{ij})_{i,j}
\)
#+END_CENTER

L'addition et la soustraction des matrices sont simplement définies par l'addition et la soustraction des composantes :

#+BEGIN_CENTER
\(
A + B = (a_{ij} + b_{ij})_{i,j} \)

\(
A - B = (a_{ij} - b_{ij})_{i,j}
\)
#+END_CENTER

On a donc clairement :

$$A + B = B + A$$


** Neutre

La matrice nulle $0$ est le neutre pour cette opération :

$$A + 0 = A$$

On en déduit que tous ses éléments doivent être nuls :

$$0 = ( 0 )_{i,j}$$

On note $0_{m,n}$ au lieu de $0$ lorsqu'on veut préciser que $0$ est
de taille $(m,n)$.


** Opposé

L'opposé de $A$, noté $-A$, est tel que :

$$A + (-A) = 0$$

On a donc clairement :

$$-A = (-a_{ij})_{i,j}$$


* Multiplication mixte

On définit la multiplication mixte $\cdot : \corps \times \matrice(\corps,m,n) \to \matrice(\corps,m,n)$ par :

$$\beta \cdot A = (\beta \cdot a_{ij})_{i,j}$$

où $\beta \in \corps$ et $A \in \matrice(\corps,m,n)$.

Choissons également $\gamma \in \corps$. On note comme d'habitude :

#+BEGIN_CENTER
\(
A \cdot \beta = \beta \cdot A \)

\(
\gamma \cdot \beta \cdot A = (\gamma \cdot \beta) \cdot A \)

\(
\beta A = \beta \cdot A
\)
#+END_CENTER


* Conjuguée

La conjuguée d'une matrice $A = (a_{ij})_{i,j} \in \matrice(\setC,m,n)$ est définie par la conjuguée des composantes :

$$\conjugue A = \bar{A} = ( \bar{a}_{ij} )_{i,j} = ( \conjugue a_{ij} )_{i,j}$$


