
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Matrices
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:matrices}

* Dépendances

  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes

* Définition

Soit un corps $\corps$, une fonction linéaire $\mathcal{A} : \corps^n
\mapsto \corps^m$ de composantes :

$$ \mathcal{A}_i = \composante_i \mathcal{A} $$

et la suite des vecteurs de la base canonique de $\corps^n$ :

$$ (\canonique_1,\canonique_2,...,\canonique_n) $$

Soit un vecteur $u \in \corps^n$ de composantes :

$$ u = (u_j)_j $$

Nous avons aussi :

$$ \mathcal{A}(u) = (\mathcal{A}_i(u))_i $$

En utilisant la linéarité de $\mathcal{A}$, on obtient :

$$ \mathcal{A}(u) = \sum_{j=1}^n \mathcal{A}(\canonique_j) \cdot u_j $$

Les composantes s’écrivent donc :

$$ \mathcal{A}_i(u) = \sum_{j=1}^n \mathcal{A}_i(\canonique_j) \cdot u_j $$

On voit que la fonction $\mathcal{A}$ est entièrement déterminée par les
coefficients scalaires :

$$ a_{ij} = \mathcal{A}_i(\canonique_j) $$

pour tout $i\in\{1,2,...,m\}$ et $j\in\{1,2,...,n\}$. On a donc :

$$ \mathcal{A}_i(u) = \sum_{j=1}^n a_{ij} \cdot u_j $$

La structure en double indice des coefficients $a_{ij}$ nous pousse à
représenter $\mathcal{A}$ par le tableau de $m$ lignes et $n$ colonnes :

$$ A = \begin{Matrix}{cccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots &        & \ddots &  \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{Matrix} $$

Un tableau $A$ de cette forme est appelé matrice de taille $(m,n)$. Les
coefficients $a_{ij}\in\corps$ sont appelés composantes de $A$.

On note $\matrice(\corps,m,n)$ l'ensemble des matrices à $m$ lignes et
$n$ colonnes.

* Composantes

Soit une matrice $A\in\matrice(\corps,m,n)$ :

$$ A = \begin{Matrix}{cccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots &        & \ddots &  \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{Matrix} $$

On note les composantes sous la forme plus compacte :

$$ A = ( a_{ij} )_{i \in \{1,2,...,m\},j \in \{1,2,...,n\}} $$

ou :

$$ A = [ a_{ij} ]_{i \in \{1,2,...,m\},j \in \{1,2,...,n\}} $$

Par convention, le numéro de ligne passe avant le numéro de colonne
à l'extérieur de la parenthèse (ou du crochet). Lorsque les nombres
de lignes et de colonnes sont évidentes d’après le contexte, on note
plus simplement :

$$ A = ( a_{ij} )_{i,j} $$

avec ou sans la virgule :

$$ A = (a_{ij})_{ij} $$

ou encore :

$$ A = [ a_{ij} ]_{i,j} = [ a_{ij} ]_{ij} $$

On dit aussi que $a_{ij}$ est la composante $i,j$ de $A$, et on le note :

$$a_{ij} = \composante_{i,j} A$$

avec ou sans virgule :

$$a_{ij} = \composante_{ij} A$$

* Egalité

Il est clair que deux matrices $A,B \in \matrice(\corps,m,n)$ :

$$ A = ( a_{ij} )_{i,j} $$

$$ B = ( b_{ij} )_{i,j} $$

sont égales ($A = B$) si et seulement si toutes leurs composantes
le sont :

$$a_{ij} = b_{ij}$$

pour tout $(i,j) \in \{ 1,2,...,m \} \times \{ 1,2,...,n \}$.

* Ordre partiel

Soit les matrices $A,B \in \matrice(\corps,m,n)$ :

$$ A = ( a_{ij} )_{i,j} $$

$$ B = ( b_{ij} )_{i,j} $$

On dit que $A$ est inférieure à $B$, et on le note $A \le B$, si :

$$a_{ij} \le b_{ij}$$

pour tout $(i,j) \in \{ 1,2,...,m \} \times \{ 1,2,...,n \}$.

* Scalaires

On peut associer à tout scalaire $a \in \corps$ une matrice $A$
de taille $(1,1)$ :

$$ A = [ a ] $$

et vice-versa. On a donc l’équivalence :

$$ \matrice(\corps,1,1) \equiv \corps $$

Dans la suite, on assimile toute matrice de taille $(1,1)$ à un scalaire.

* Vecteurs lignes et colonnes

#+TOC: headlines 1 local

** Taille des vecteurs

On peut considérer un vecteur colonne comme une matrice ne possédant
qu'une seule colonne. Un vecteur colonne est donc de taille générique
$(m,1)$.

De même, on peut considérer un vecteur ligne comme une matrice ne
possédant qu'une seule ligne. Un vecteur ligne est donc de taille
générique $(1,n)$.

** Équivalence avec $\corps^n$

A partir d'un n-tuple $(x_1,x_2,...,x_n) \in \corps^n$, on peut former
un vecteur ligne $l \in \matrice(\corps,1,n)$ et un vecteur colonne $c
\in \matrice(\corps,n,1)$. Les réciproques étant également vraies,
on a les équivalences :

#+begin_center
$\matrice(\corps,1,n) \equiv \matrice(\corps,n,1) \equiv \corps^n$
#+end_center

** Colonne d’une matrice

La colonne $j$ d’une matrice :

$$ A = (a_{ij})_{i,j} \in \matrice(\corps,m,n) $$

est aussi un vecteur colonne $c_j \in \corps^m$ défini par :

$$ c_j =  (a_{ij})_i = \begin{Matrix}{c}
a_{1j} \\
a_{2j} \\
\vdots \\
a_{mj}
\end{Matrix} $$

 On note :

$$ \colonne_j A = c_j $$

** Ligne d’une matrice

La ligne $i$ d’une matrice :

$$ A = (a_{ij})_{i,j} \in \matrice(\corps,m,n) $$

est aussi un vecteur ligne $l_i \in \corps^n$ défini par :

$$ l_i =  (a_{ij})_j = [a_{i1} \ \ a_{i2} \ \ldots \ \ a_{in}] $$

On note :

$$\ligne_i A = l_i$$

* Formes lignes et colonnes

On peut exprimer $A$ sous la forme de colonnes juxtaposées. Soit :

$$A = [c_1 \ \ c_2 \ \ \ldots \ \ c_n]$$

où les $c_i \in \matrice(\corps,m,1)$ sont les colonnes de $A$.

On peut aussi exprimer une matrice $A \in \matrice(\corps,m,n)$ sous la forme
de lignes superposées. Soit :

$$ A =
\begin{Matrix}{c}
l_1 \\
l_2 \\
\vdots \\
l_m
\end{Matrix} $$

où les $l_i \in \matrice(\corps,1,n)$ sont les lignes de $A$.

* Blocs

#+TOC: headlines 1 local

** Partitionnement en blocs

Il est parfois très utile de partitionner une matrice en blocs, ou de
former une matrice plus grande à partir de matrices de tailles plus
petites. On note alors :

$$ A =
\begin{Matrix}{cc}
B & C \\
D & E
\end{Matrix} = \begin{Matrix}{cccccc}
b_{11} & \ldots & b_{1n} & c_{11} & \ldots & c_{1p} \\
\vdots &        & \vdots & \vdots &        & \vdots \\
b_{m1} & \ldots & b_{mn} & c_{m1} & \ldots & c_{mp} \\
d_{11} & \ldots & d_{1n} & e_{11} & \ldots & e_{1p} \\
\vdots &        & \vdots & \vdots &       & \vdots \\
d_{r1} & \ldots & d_{rn} & e_{r1} & \ldots & e_{rp}
\end{Matrix} $$

où les $b_{ij},c_{ij},d_{ij},e_{ij}$ sont respectivement les composantes
des matrices $B,C,D,E$. Ces matrices doivent évidemment être de
tailles compatibles (nombres de lignes identiques pour $B$ et $C$,
ainsi que pour $D$ et $E$ ; nombres de colonnes identiques pour $B$
et $D$, ainsi que pour $C$ et $E$).

** Extraction d’un bloc

Soit $A = (a_{ij})_{i,j}$. La fonction $\bloc_{ijkl}$ donne la
sous-matrice située entre la $i^{ème}$ et la $j^{ème}$ ligne, ainsi
qu'entre la $k^{ième}$ et la $l^{ième}$ colonne :

$$ \bloc_{i,j,k,l} A = \bloc_{ijkl} A = \begin{Matrix}{cccc}
a_{ik} & a_{i,k+1} & \ldots & a_{il} \\
a_{i+1,k} & a_{i+1,k+1} & \ldots & a_{i+1,l} \\
\vdots &        & \ddots &  \vdots \\
a_{jk} & a_{j,k+1} & \ldots & a_{jl}
\end{Matrix} $$

On appelle bloc une telle sous-matrice.

* Transposée

Transposer une matrice $A = (a_{ij})_{i,j} \in \matrice(\corps,m,n)$ consiste à agencer ses lignes en colonnes et vice-versa :

$$ A^T = \begin{Matrix}{cccc}
a_{11} & a_{21} & \ldots & a_{m1} \\
a_{12} & a_{22} & \ldots & a_{m2} \\
\vdots &        & \ddots &  \vdots \\
a_{1n} & a_{2n} & \ldots & a_{mn}
\end{Matrix} = (a_{ji})_{i,j} $$

On voit que la transposée $A^T \in \matrice(\corps,n,m)$.

On a clairement :

$$\big( A^T \big)^T = A$$

* Conjuguée

La conjuguée d'une matrice $A = (a_{ij})_{i,j} \in \matrice(\setC,m,n)$
est définie par la conjuguée des composantes :

$$\conjugue A = \conjaccent{A} = ( \bar{a}_{ij} )_{i,j} = ( \conjugue a_{ij} )_{i,j}$$

* Catégories

#+TOC: headlines 1 local

** Matrices carrées et rectangulaires

Les matrices $A \in \matrice(\corps,n,n)$ ayant même nombre
de colonnes et de lignes sont dites « carrées ». Les
matrices $A \in \matrice(\corps,m,n)$ avec $m \ne n$ sont dites
« rectangulaires ». Lorsque $m \strictinferieur n$, on dit que la
matrice est « longue ». Si $m \strictsuperieur n$, on dit que la
matrice est « haute ».

** Matrices diagonales

Une matrice diagonale contient des composantes nulles partout, à
l'exception de la diagonale où aucune contrainte n'est fixée. On peut
représenter une matrice diagonale $D \in \matrice(\corps,m,n)$ par :

$$ D = ( d_i \cdot \indicatrice_{ij} )_{i,j} $$

On peut aussi former une matrice diagonale de taille $(m,n)$ à partir
d'un vecteur $d = (d_i)_i$ de taille $(p,1)$, où $p \le \min \{ m ,
n \}$. On le note :

$$D = \diagonale_{m,n}(d) = \diagonale_{m,n}(d_1,...,d_p)$$

où :

#+BEGIN_CENTER
$$ \composante_{ij} \diagonale_{m,n}(d_1,...,d_p) =
\begin{cases}
d_i & \text{ si } i = j \in \{1,2,...,p\} \\
0 & \text{ sinon}
\end{cases} $$
#+END_CENTER

*** Carrée

Dans le cas particulier où $m = n$, on note aussi :

$$\diagonale_n(d) = \diagonale_{n,n}(d)$$

** Matrices triangulaires

Les composantes des matrices triangulaires supérieures ne peuvent être non nulles qu'au-dessus de la diagonale, c'est-à-dire lorsque $i \le j$. Elles peuvent se représenter par :

$$T = (t_{ij} \cdot \tau^+_{ij})_{i,j}$$

où :

#+BEGIN_CENTER
$$ \tau^+_{ij} =
\begin{cases}
1 & \mbox{ si } i \le j \\
0 & \mbox{ si } i \strictsuperieur j
\end{cases} $$
#+END_CENTER

Les composantes des matrices triangulaires inférieures ne peuvent être non nulles qu'au-dessous de la diagonale, c'est-à-dire lorsque $i \ge j$. Elles peuvent se représenter par :

$$T = (t_{ij} \cdot \tau^-_{ij})_{i,j}$$

où :

#+BEGIN_CENTER
$$ \tau^-_{ij} =
\begin{cases}
1 & \mbox{ si } i \ge j \\
0 & \mbox{ si } i \strictinferieur j
\end{cases} $$
#+END_CENTER
