
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Naturels
#+AUTHOR: chimay
#+EMAIL: or du val chez gûˋ courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathûˋmatique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:naturels}

* Dûˋpendances

  - Chapitreô \ref{chap:ensembles} : Les ensembles
  - Chapitreô \ref{chap:operations} : Les opûˋrations
  - Chapitreô \ref{chap:algebre} : L'algû´bre
  - Chapitreô \ref{chap:ordres} : Les ordres
  - Chapitreô \ref{chap:extrema} : Les extrema

* Introduction

Nous allons ûˋtudier l'ensemble des naturelsô :

$$\setN = \{ 0,1,2,3,4,5,6,7,8,9,10,... \}$$

** Non nul

On note :

$$ \setN_0 = \{ 0,1,2,3,4,5,6,7,8,9,10,... \} $$

* Addition

L'addition usuelle sur $\setN$, notûˋe $+ : \setN \times \setN \mapsto
\setN$, est dûˋfinie parô :

$$ m + 0 = 0 $$

$$ m + n^+ = m^+ + n $$

pour tout $m,n \in \setN$.

En utilisant rûˋcursivement la dûˋfinition, on arrive û ô :

\begin{align}
m + 1 &= m + 0^+ = m^+ + 0 = m^+ \\
m + 2 &= m + 0^{++} = m^+ + 0^+ = m^{++} + 0 = m^{++} \\
\vdots & \\
m + n &= ... = m^{+...+}
\end{align}

oû¿ $+...+$ dûˋsigne l'opûˋration de succession appliquûˋe $n$
fois. L'addition de $n$ revient donc û  effectuer $n$ opûˋrations de
succession.

** Dualitûˋ

Posant $i = m$ et $j = n^+$, on voit clairement queô :

$$i + j = i^+ + j^-$$


** Neutre additif

Pour $m \in \setN$ quelconque, on aô :

$$0 + m = 0^{+...+}$$

oû¿ $+...+$ dûˋsigne l'opûˋration de succession appliquûˋe $m$ fois. Mais comme $0^{+...+} = m$, on aô :

$$0 + m = m$$

On a donc $0 + m = m + 0 = m$. On dit que $0$ est neutre pour l'addition. On voit clairement d'aprû´s la dûˋfinition que $0$ est le seul neutre pour l'addition.


** Commutativitûˋ

Soit $m,n \in \setN$. Par dûˋfinition de l'addition, on aô :

$$m + n = m^{+...+} = 0^{+.....+}$$

oû¿ $+.....+$ rûˋprûˋsente $m$ suivies de $n$ opûˋrations de successions. On a aussiô :

$$n + m = n^{+...+} = 0^{+.....+}$$

oû¿ $+.....+$ rûˋprûˋsente $n$ suivies de $m$ opûˋrations de successions. Les deux rûˋsultats ûˋtant identiques,on aô :

$$m + n = n + m$$

On dit que l'addition sur $\setN$ est commutative.


** Associativitûˋ

Soit $m,n,p \in \setN$.

Dûˋveloppons l'addition $m + (p + n)$. On aô :

$$m + (p + n) = m + p^{+...+}$$

oû¿ $+...+$ dûˋsigne l'opûˋration de succession appliquûˋe $n$ fois. Il vient ensuiteô :

#+BEGIN_CENTER
\(
m + (p + n) = m^+ + p^{+...+-} \)

\(
\vdots \)

\(
m + (p + n) = m^{+...+} + p^{+...+-...-}
\)
#+END_CENTER

oû¿ $+...+-...-$ dûˋsigne l'opûˋration de succession appliquûˋe $n$ fois, suivie de l'opûˋration de prûˋdûˋcession appliquûˋe $n$ fois ûˋgalement. Mais comme le prûˋdûˋcesseur du sucesseur est ûˋgal û  lui-mûˆme par dûˋfinition, on a $p^{+-} = p$. On constate en dûˋveloppant que la mûˆme propriûˋtûˋ doit ûˆtre vûˋrifiûˋe lorsque les opûˋrations de succession et de prûˋdûˋcession sont appliquûˋes un nombre quelconque mais identique de fois. On a doncô :

$$p^{+...+-...-} = p$$

En tenant compte de ces rûˋsultats dans le dûˋveloppement de la somme ci-dessus, on arrive û ô :

$$m + (p + n) = m^{+...+} + p$$

Mais $m^{+...+}$ n'est rien d'autre que la somme $m + n$, etô :

$$m + (p + n) = (m + n) + p$$

L'addition ûˋtant commutative, on peut inverser $p$ et $n$ pour obtenirô :

$$m + (n + p) = (m + n) + p$$

On peut donc associer les termes d'une somme comme on le dûˋsire, le rûˋsultat restera identique. On dit que l'addition sur $\setN$ est associative. On note aussiô :

$$m + n + p = m + (n + p) = (m + n) + p$$


* Ordre

Soit $m,n \in \setN$. On dit que $n$ est plus petit ou ûˋgal û  $m$, et on le noteô :

$$n \le m$$

si on peut trouver un $p \in \setN$ tel queô :

$$m = n + p$$

En ûˋvaluant les additions $n+1$ et $n^- + 1$, on obtientô :

$$ n^- + 1 = n $$

$$ n + 1 = n^+ $$

Le choix $p = 1$ nous montre alors queô :

$$n^- \le n \le n^+$$

** Plus grand ou ûˋgal

On note aussiô :

$$m \ge n$$

pour signifier que $n \le m$.


** Total

Soir $m,n \in \setN$. Comme $m$ est, directement ou indirectement,
un successeur ou un prûˋdûˋcesseur de $n$, on a soitô :

$$m \le n$$

soitô :

$$n \le m$$

L'ordre usuel sur $\setN$ est total.


** Ordre strict

On noteô :

$$n \strictinferieur m$$

ouô :

$$m \strictsuperieur n$$

lorsque $n \le m$ et $m \ne n$.


** Extrema

Comme tous les ûˋlûˋments de $\setN$ sont supûˋrieurs au ûˋgaux û  $0$, on a clairementô :

$$\minor \setN = \{ 0 \}$$

etô :

$$\inf \setN = \min \setN = 0$$

Par contre, si on suppose avoir trouvûˋ $s \in \major \setN$, on a $s
\le s^+ \in \setN$ ce qui contredit l'hypothû´se de majorant. L'ensemble
des majorants est donc vide, et le supremum n'existe pas dans $\setN$. On
dit alors que le suprûˋmum est infini et on noteô :

$$\sup \setN = +\infty$$

* Ordre et addition

Soit $a,b,c,d \in \setN$. Supposons queô :

$$a \le b$$
$$c \le d$$

On peut donc trouver $p,q \in \setN$ tels queô :

$$ b = a + p $$

$$ d = c + q $$

En additionnant ces deux ûˋquations, on obtientô :

$$b + d = a + p + c + q = (a + c) + (p + q)$$

Comme $p + q$ est ûˋgalement un naturel, on en conclut queô :

$$a + c \le b + d$$

L'ordre est donc conservûˋ lorsqu'on ajoute au moins autant au grand nombre qu'au petit. On parle d'invariance sous l'addition.


* Positivitûˋ

\label{sec:positivite_des_naturels}

Soit $n \in \setN$. La neutralitûˋ de $0$ pour l'addition nous permet d'ûˋcrireô :

$$n = 0 + n$$

On en dûˋduit queô :

$$n \ge 0$$

pour tout $n \in \setN$ etô :

$$n \strictsuperieur 0$$

lorsque $n \ne 0$.


* Soustraction

#+TOC: headlines 1 local

** $m \ge n$

Soit l'ensembleô :

$$\Delta = \{ (m,n) \in \setN^2 : n \le m \}$$

Choisissons $(m,n) \in \Delta$. On peut trouver $p \in \setN$ tel queô :

$$m = n + p$$

Commeô :

$$n + p = p + n = p^{+...+} = m$$

on voit queô :

$$p = m^{-...-}$$

oû¿ $-...-$ dûˋsigne $n$ opûˋrations de prûˋdûˋcessions. Le $p$ ainsi dûˋfini est donc unique. On dit que $p$ est la soustraction de $m$ et $n$, et on le noteô :

$$p = m - n$$

** $m \le n$

Si $m \strictinferieur n$, calculer la soustractionô :

$$p = m - n = m^{-...-} = 0^{+...+-...-}$$

reviendrait û  effectuer plus d'opûˋrations de prûˋdûˋcessions que de
sucessions. Nous serions donc amenûˋs û  devoir ûˋvaluer le prûˋdûˋcesseur
de l'ûˋlûˋment racine $0$, qui n'existe pas dans $\setN$. Cette opûˋration
n'est par consûˋquent pas dûˋfinie.

** Neutralisation

La dûˋfinition implique directement l'ûˋquivalenceô :

#+BEGIN_CENTER
\(
m = n = n + 0 \)

\(
\Longleftrightarrow \)

\(
m - n = 0
\)
#+END_CENTER


** Associativitûˋ

Soit $m,n,p \in \setN$ avec $n + p \le m$. On a trivialementô :

$$(m - n) - p = m - (n + p)$$

On note aussiô :

$$m - n - p = (m - n) - p = m - (n + p)$$


** Commutativitûˋ

Soit $m,n,p \in \setN$ avec $n + p \le m$. On voit queô :

$$m - n - p = m - (n + p) = m - (p + n) = m - p - n$$


** Associativitûˋ mixte

Soit $m,n,p \in \setN$ avec $p \le n$. On a trivialementô :

$$(m + n) - p = m + (n - p)$$

On note aussiô :

$$m + n - p = (m + n) - p = m + (n - p)$$


** Commutativitûˋ mixte

Soit $m,n,p \in \setN$ avec $m,p \le n$. On a trivialementô :

\begin{align}
m + n - p = (m + n) - p &= (n + m) - p \\
&= n + (m - p) \\
&= (m - p) + n \\
&= m - p + n
\end{align}

* Ordre et soustraction

Soit $a,b,c,d \in \setN$. Supposons queô :

$$a \le b$$
$$c \ge d$$

On peut donc trouver $p,q \in \setN$ tel queô :

$$b = a + p$$

$$d + q = c$$

En soustrayant ces deux ûˋquations, on obtientô :

$$b - d - q = a + p - c$$

$$b - d = a - c + p + q$$

Comme $p + q$ est aussi un naturel, on en conclut queô :

$$a - c \le b - d$$

L'ordre est donc conservûˋ lorsqu'on soustrait au moins autant au petit nombre qu'au grand. On parle d'invariance pour la soustraction.


* Multiplication

#+TOC: headlines 1 local

** Dûˋfinition

La multiplication usuelle entre deux nombres $m,n \in \setN$ est le
nombre de cases que contient un tableau qui comporte $m$ lignes et $n$
colonnes. On la note $\cdot : \setN \times \setN \mapsto \setN$.

*** Taille d'un tableau

Soit $m,n \in \setN$. Un tableau de taille $(m,n)$ est un tableau de $m$
lignes et $n$ colonnes.

*** Notation

Lorsque cela ne pose pas de problû´me d'ambiguitûˋ, on note aussiô :

$$m \ n = m \cdot n$$

pour tout $m,n \in \setN$.

*** Prioritûˋ

Afin d'allûˋger les notations, nous convenons que la multiplication est
toujours prioritaire sur l'addition. On pose doncô :

$$ m \cdot n + p = ( m \cdot n ) + p$$

pour tout $m,n,p \in \setN$.

** Rûˋcurrence

Soit $m,n \in \setN$. Augmenter le nombre de colonnes de $1$ augmente
le nombre de cases total du nombre de lignes $m$ :

$$ m \cdot n^+ = m \cdot n + m$$

Augmenter le nombre de lignes de $1$ augmente le nombre de cases total
du nombre de colonnes $n$ :

$$ m^+ \cdot n = m \cdot n + n $$

Posant $i = m$ et $j = n^+$, on en dûˋduit queô :

$$ i \cdot j = i \cdot j^- + i $$

Posant $k = m^+$ et $l = n$, on en dûˋduit queô :

$$ k \cdot l = k^- \cdot l + l $$

** Neutre multiplicatif

Soit $m,n \in \setN$. Il va de soi quãun tableau contenant une seule
ligne de $n$ colonnes contient au total $n$ cases :

$$ 1 \cdot n = n $$

et quãun tableau contenant une seule colonne de $m$ lignes contient
au total $m$ cases :

$$ m \cdot 1 = m $$

On a donc $1 \cdot i = i \cdot 1 = i$ pour tout $i \in \setN$. On dit
que $1$ est neutre pour la multiplication.

** Commutativitûˋ

Soit $m,n \in \setN$. Un tableau de taille $(m,n)$ contient autant de
cases quãun tableau de taille $(n,m)$. On a donc :

$$ m \cdot n = n \cdot m $$

La multiplication de naturels est commutative.

** Distributivitûˋ

Soit $m,n,p \in \setN$. En plaûÏant cûÇte û  cûÇte un tableau $T$ de
taille $(m,n)$ avec un tableau $U$ de taille $(m,p)$, on obtient un
nombre de cases total :

$$ m \cdot n + m \cdot p $$

Mais le tableau formûˋ en associant $T$ et $U$ est de taille $(m,n+p)$,
ce qui nous donne un nombre de cases :

$$ m \cdot (n + p) $$

Ces deux expressions comptant le nombre de cases du mûˆme tableau,
elles doivent ûˆtre ûˋgales et on a :

$$ m \cdot (n + p) = m \cdot n + m \cdot p $$

On dit que la multiplication se distribue sur l'addition.

Par commutativitûˋ, on a ûˋgalement :

$$ (n + p) \cdot m = n \cdot m + p \cdot m $$

*** Sur la soustraction

Soit $m,n,p \in \setN$ avec $p \le n$ etô :

$$q = n - p$$

On aô :

$$m \cdot (p + q) = m \cdot p + m \cdot q$$

Mais comme $p + q = n$, il vientô :

$$m \cdot n = m \cdot p + m \cdot (n - p)$$

On en dûˋduit queô :

$$m \cdot (n - p) = m \cdot n - m \cdot p$$

Par commutativitûˋ de la multiplication, on a ûˋgalementô :

$$(n - p) \cdot m = n \cdot m - p \cdot m$$

On dit que la multiplication se distribue sur la soustraction.

** Absorption

Soit $m,n \in \setN$. Il va de soi quãun tableau ne contenant aucune
ligne contient zûˋro case :

$$ m \cdot 0 = 0 $$

tout comme un tableau ne contenant aucune colonne :

$$ 0 \cdot n = 0 $$

On dit que lãûˋlûˋment $0$ est un absorbant pour la multiplication.

On peut obtenir le mûˆme rûˋsultat en utilisant la distributivitûˋ :

$$ m \cdot 0 = m \cdot (n - n) = m \cdot n - m \cdot n = 0 $$

$$ 0 \cdot m = (n - n) \cdot m = n \cdot m - n \cdot m = 0 $$

*** Unicitûˋ de l'absorbant

Nous allons voir que l'absorbant est unique. Soit $a_1, a_2 \in \setN$
tels queô :

$$a_1 \cdot n = a_2 \cdot n = 0$$

pour tout $n \in \setN$. On en dûˋduit queô :

$$a_1 \cdot n - a_2 \cdot n = 0$$

En utilisant la distributivitûˋ, on obtientô :

$$(a_1 - a_2) \cdot n = 0$$

Mais comme ce rûˋsultat doit ûˆtre valable pour tout $n \in \setN$, il est valable pour $n = 1$ et on aô :

$$(a_1 - a_2) \cdot 1 = a_1 - a_2 = 0$$

Autrement dit, $a_1 = a_2$. L'absorbant est donc unique.

** Associativitûˋ

Soit $m,n,p \in \setN$. On aô :

$$m \cdot (n \cdot p) = m + ... + m$$

oû¿ le membre de droite compte $n \cdot p$ termes ô¨ô $m$ô ô£. Par
associativitûˋ de l'addition, on peut les regrouper en $p$ parenthû´ses
contenant chacune $n$ termesô :

$$m \cdot (n \cdot p) = (m + ... + m) + ... + (m + ... + m)$$

ce qui revient û ô :

$$m \cdot (n \cdot p) = (m \cdot n) + ... + (m \cdot n)$$

Mais comme il y a $p$ parenthû´ses, on aô :

$$m \cdot (n \cdot p) = (m \cdot n) \cdot p$$

La multiplication est donc associative. On note aussiô :

$$m \cdot n \cdot p = m \cdot (n \cdot p) = (m \cdot n) \cdot p$$


** Produit nul

Soit $m,n \in \setN$ tels queô :

$$m \cdot n = 0$$

Nous allons prouver qu'au moins un des deux facteurs doit ûˆtre nul. Supposons que $m, n \ne 0$. On a alorsô :

$$m \cdot n = n + ... + n = 0$$

Mais comme $n \ne 0$, on aô :

$$n \strictsuperieur 0$$

etô :

$$0 = n + ... + n \ge n \strictsuperieur 0$$

ce qui est impossible. On a donc l'implicationô :

$$m \cdot n = 0 \quad \Rightarrow \quad m = 0 \quad \mathrm{ou} \quad n = 0$$


* Notation dûˋcimale

Soit le tupleô :

$$(i_0,i_1,i_2,...i_{n - 1},i_n) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^{n + 1}$$

La notation dûˋcimale associûˋe est dûˋfinie parô :

$$i_n i_{n - 1} ... i_2 i_1 i_0 = i_0 + i_1 \cdot 10 + i_2 \cdot 10^2 + ... + i_{n - 1} \cdot 10^{n - 1} + i_n \cdot 10^n$$

Exempleô :

$$7512 = 2 + 1 \cdot 10 + 5 \cdot 10^2 + 7 \cdot 10^3$$


* Division entiû´re ou euclidienne

#+TOC: headlines 1 local

** Introduction

Soit $m,n \in \setN$. On dûˋfinit la division entiû´re $\diventiere :
\setN \times \setN \to \setN$ parô :

$$ m \diventiere n = \sup \{ k \in \setN : k \cdot n \le m \} $$

On dit que $m$ est le dividende, $n$ le diviseur et $m \diventiere n$
le quotient de $m$ par $n$.

** Existence

Soit $m,n \in \setN$ avec $n \ne 0$ etô :

$$A_{mn} = \{ k \in \setN : k \cdot n \le m \}$$

Pour tout naturel $p$ vûˋrifiant $p \strictsuperieur m$, on aô :

$$p \cdot n = p + ... + p \strictsuperieur p \strictsuperieur m$$

On en conclut queô :

$$A_{mn} \subseteq \{ 0, 1, ..., m - 1, m \}$$

L'ensemble $A_{mn}$ contient donc un nombre fini d'ûˋlûˋments. Comme
l'ordre usuel sur $\setN$ est total, on en conclut que $A_{mn}$ admet
un maximum identique au suprûˋmum. La division entiû´re de $m$ par $n$
est donc bien dûˋfinieô :

$$m \diventiere n = \max A_{mn} = \sup A_{mn}$$

L'inclusion nous donne l'inûˋgalitûˋ des maximaô :

$$\max A_{mn} \le \max \{ 0, 1, ..., m - 1, m \} = m$$

On en dûˋduit queô :

$$m \diventiere n \le m$$

** Modulo, reste

Soit $m,n \in \setN$. Par dûˋfinition, on voit queô :

$$(m \diventiere n) \cdot n \le m$$

Il est donc licite de dûˋfinir le naturelô :

$$r = m - (m \diventiere n) \cdot n$$

On dit que $r$ est le modulo de $m$ par rapport û  $n$ et on le noteô :

$$m \modulo n = m - (m \diventiere n) \cdot n$$

On dit aussi que $r = m \modulo n$ est le reste de la division entiû´re
de $m$ par $n$.

*** Bornes

Soit $m,n \in \setN$ et $k = m \diventiere n$. On sait dûˋjû  queô :

$$m \modulo n \ge 0$$

par la positivitûˋ des naturels. Supposons de plus queô :

$$m \modulo n = m - k \cdot n \ge n$$

on a alorsô :

$$m \ge n + k \cdot n = (k + 1) \cdot n$$

ce qui est contraire au caractû´re de supremum de $k$. Par consûˋquentô :

$$0 \le m \modulo n \le n - 1$$

** Dûˋcomposition euclidienne

Soit $m,n \in \setN$. Par dûˋfinition du modulo, on a la relationô :

$$ m = (m \diventiere n) \cdot n + m \modulo n $$

Cette relation est appelûˋe dûˋcomposition euclidienne de $m$ par $n$.

On note souvent ce rûˋsultat sous la forme :

$$ m = k \cdot n + r $$

oû¿ $k = m \diventiere n$ est le quotient et $r = m \modulo n$ le reste
de la division euclidienne.

*** Unicitûˋ

Soit $m,n,k,r \in \setN$ avec $n \ne 0$. Supposons queô :

$$m = k \cdot n + r$$

Par positivitûˋ des naturels, on a $r \ge 0$ etô :

$$k \cdot n \le m$$

d'oû¿ l'on conclut par dûˋfinition du suprûˋmum que $k \le m \diventiere n$.
Si on a ûˋgalementô :

$$r \le n - 1$$

on a alorsô :

$$(k + 1) \cdot n = k \cdot n + n \strictsuperieur k \cdot n + r = m$$

On en conclut que $k + 1 \strictsuperieur m \diventiere n$. Doncô :

$$m \diventiere n = k$$

etô :

$$m \modulo n = r$$

*** Division exacte

Soit $m,n \in \setN$. Si $m \modulo n = 0$, on dit que la division
entiû´re est exacte, ou que $m$ est divisible par $n$. Dans ce cas,
la dûˋcomposition euclidienne s'ûˋcrit simplementô :

$$m = (m \diventiere n) \cdot n$$

**** Nombre pair

Un nombre $m \in \setN$ est dit pair sãil est divisible par $2$. On
a donc :

$$ m \modulo 2 = 0 $$

Posons :

$$ n = m \diventiere 2 $$

La dûˋcomposition euclidienne du nombre pair $m$ par $2$ sãûˋcrit :

$$ m = 2 \ n $$

**** Nombre impair

Un nombre $m \in \setN$ est dit impair sãil nãest pas divisible par
$2$. Soit :

$$ n = m \diventiere 2 $$

$$ r = m \modulo 2 $$

On a alors :

$$ 0 \le r \le 2 - 1 = 1 $$

Comme la division ne peut ûˆtre exacte, on a aussi $r \ne 0$. La seule
valeur possible est alors :

$$ r = 1 $$

La dûˋcomposition euclidienne du nombre impair $m$ par $2$ sãûˋcrit :

$$ m = 2 \ n + 1 $$

** Cas particuliers

*** Division par zûˋro

Soit $m \in \setN$. Essayons d'ûˋvaluer la division $m \diventiere 0$. Par absorption de $0$, on voit queô :

$$k \cdot 0 = 0 \le m$$

pour tout $k \in \setN$. Par consûˋquentô :

$$\{ k \in \setN : k \cdot 0 \le m \} = \setN$$

Le supremum n'existe pas dans $\setN$ et la division par zûˋro n'est par consûˋquent pas dûˋfinie. On le note symboliquementô :

$$m \diventiere 0 = \sup \setN = +\infty$$

*** Division par un

Soit $m \in \setN$. On aô :

$$m = m \cdot 1 \le m$$

etô :

$$(m + 1) \cdot 1 = m + 1 \strictsuperieur m$$

On en dûˋduit queô :

$$m \diventiere 1 = m$$

*** Zûˋro divisûˋ

Soit $n \in \setN$ avec $n \ne 0$. On aô :

$$\{ k \in \setN : k \cdot n \le 0 \} = \{ 0 \}$$

La division entiû´re de $0$ par $n$ est donc nulleô :

$$0 \diventiere n = \sup \{ 0 \} = 0$$

** Division de deux produits

Soit $m,n,q,i,j,k \in \setN$ avec $n,j \ne 0$ tels queô :

$$m = q \cdot n$$
$$i = k \cdot j$$

On a alors les divisions exactesô :

$$m \diventiere n = q$$
$$i \diventiere j = k$$

De plusô :

$$m \cdot i = q \cdot k \cdot n \cdot j$$

ce qui signifie queô :

$$(m \cdot i) \diventiere (n \cdot j) = q \cdot k$$

On a doncô :

$$(m \cdot i) \diventiere (n \cdot j) = (m \diventiere n) \cdot (i \diventiere j)$$


** Plus grand commun diviseur

Soit $m,n \in \setN$ avec $n \ne 0$. On dûˋfinit le plus grand commun diviseur de $m$ et $n$ parô :

$$\pgcd(m,n) = \sup \{ k \in \setN : m \modulo k = n \modulo k = 0 \}$$

Comme les divisions sont exactes, on aô :

$$m = \big[ m \diventiere \pgcd(m,n) \big] \cdot \pgcd(m,n)$$

etô :

$$n = \big[ n \diventiere \pgcd(m,n) \big] \cdot \pgcd(m,n)$$


** Plus petit commun multiple

Soit $m,n \in \setN$. On dûˋfinit le plus petit commun multiple de $m$ et $n$ parô :

$$\ppcm(m,n) = \inf \{ k \in \setN : k \modulo m = k \modulo n = 0 \}$$

Comme les divisions sont exactes, on aô :

$$\ppcm(m,n) = \big[ \ppcm(m,n) \diventiere m \big] \cdot m$$

etô :

$$\ppcm(m,n) = \big[ \ppcm(m,n) \diventiere n \big] \cdot n$$

* Puissance

Soit $m,n \in \setN$ avec $n \ne 0$. Les puissances naturelles sont dûˋfinies parô :

\begin{align*}
m^0 &= 1 \\
m^n &= m \cdot m^{n-1}
\end{align*}

En appliquant rûˋcursivement la dûˋfinition, on obtientô :

\begin{align*}
m^n &= m \cdot m^{n-1} \\
&\vdots& \\
m &= m \cdot \ldots \cdot m
\end{align*}

oû¿ le membre de droite compte $n$ facteurs ô¨ô $m$ô ô£.

** Prioritûˋ

Nous convenons des rû´gles de prioritûˋô :

$$m + n^p = m + (n^p)$$

$$m \cdot n^p = m \cdot (n^p)$$

valables pour tout $m,n,p \in \setN$.


** Somme en exposant

Soit $m,n,p \in \setN$. On aô :

$$m^{n+p} = m \cdot ... \cdot m$$

oû¿ le membre de droite compte $n+p$ facteur $m$. En regroupant les $n$ premiers facteurs dans une premiû´re parenthû´se et les $p$ facteurs restant dans la seconde, on aô :

$$m^{n+p} = (m \cdot ... \cdot m) \cdot (m \cdot ... \cdot m)$$

qui n'est rien d'autre queô :

$$m^{n+p} = m^n \cdot m^p$$


** Puissance d'un produit

$$\left(m \cdot n\right)^p = m \cdot n \cdot ... \cdot m \cdot n$$

oû¿ le membre de droite compte $p$ facteurs $m \cdot n$. La commutativitûˋ de la multiplication nous permet de les regrouper les $m$ d'un cotûˋ et les $n$ de l'autreô :

$$\left(m \cdot n\right)^p = m \cdot ... \cdot m \cdot n \cdot ... \cdot n$$

c'est-û -direô :

$$\left(m \cdot n\right)^p = m^p \cdot n^p$$


** Puissance d'une puissance

Soit $m,n,p \in \setN$. On aô :

\begin{align}
\left(m^n\right)^p &= \left(m \cdot ... \cdot m\right)^p \\
&= m \cdot ... \cdot m
\end{align}

oû¿ le membre de droite compte $n \cdot p$ facteurs. On en conclut queô :

$$\left(m^n\right)^p = m^{n \cdot p}$$

* Factorielle

Soit $n\in\setN$, $n \ne 0$. On dûˋfinit la factorielle de $n$ parô :

\begin{align*}
0 ! &= 1 \\
n ! &= n \cdot (n-1) !
\end{align*}

On a doncô :

$$n ! = n \cdot (n - 1) \cdot (n - 2) \cdot ... \cdot 1 = 1 \cdot 2 \cdot 3 \cdot ... \cdot n$$

** Prioritûˋ

On convient queô :

$$x \cdot y ! = x \cdot (y !)$$


* Monoû₤de

$(\setN,+)$ et $(\setN,\cdot)$ sont des monoû₤des.
