
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Naturels
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:naturels}

* Dépendances

  - Chapitre \ref{chap:ensembles} : Les ensembles
  - Chapitre \ref{chap:operations} : Les opérations
  - Chapitre \ref{chap:algebre} : L'algèbre
  - Chapitre \ref{chap:ordres} : Les ordres
  - Chapitre \ref{chap:extrema} : Les extrema

* Introduction

Nous allons étudier l'ensemble des naturels :

$$\setN = \{ 0,1,2,3,4,5,6,7,8,9,10,... \}$$


* Addition

L'addition usuelle sur $\setN$, notée $+ : \setN \times \setN \mapsto \setN$, est définie par :

\begin{align}
m + 0 &= 0 \)

\(
m + n^+ &= m^+ + n
\end{align}

pour tout $m,n \in \setN$.

En utilisant récursivement la définition, on arrive à :

\begin{align}
m + 1 &= m + 0^+ = m^+ + 0 = m^+ \)

\(
m + 2 &= m + 0^{++} = m^+ + 0^+ = m^{++} + 0 = m^{++} \)

\(
\vdots && \)

\(
m + n &= ... = m^{+...+}
\end{align}

où $+...+$ désigne l'opération de succession appliquée $n$ fois. L'addition de $n$ revient donc à effectuer $n$ opérations de succession.


** Dualité

Posant $i = m$ et $j = n^+$, on voit clairement que :

$$i + j = i^+ + j^-$$


** Neutre additif

Pour $m \in \setN$ quelconque, on a :

$$0 + m = 0^{+...+}$$

où $+...+$ désigne l'opération de succession appliquée $m$ fois. Mais comme $0^{+...+} = m$, on a :

$$0 + m = m$$

On a donc $0 + m = m + 0 = m$. On dit que $0$ est neutre pour l'addition. On voit clairement d'après la définition que $0$ est le seul neutre pour l'addition.


** Commutativité

Soit $m,n \in \setN$. Par définition de l'addition, on a :

$$m + n = m^{+...+} = 0^{+.....+}$$

où $+.....+$ réprésente $m$ suivies de $n$ opérations de successions. On a aussi :

$$n + m = n^{+...+} = 0^{+.....+}$$

où $+.....+$ réprésente $n$ suivies de $m$ opérations de successions. Les deux résultats étant identiques,on a :

$$m + n = n + m$$

On dit que l'addition sur $\setN$ est commutative.


** Associativité

Soit $m,n,p \in \setN$. Développons l'addition $m + (p + n)$. On a :

$$m + (p + n) = m + p^{+...+}$$

où $+...+$ désigne l'opération de succession appliquée $n$ fois. Il vient ensuite :

#+BEGIN_CENTER
\(
m + (p + n) = m^+ + p^{+...+-} \)

\(
\vdots \)

\(
m + (p + n) = m^{+...+} + p^{+...+-...-}
\)
#+END_CENTER

où $+...+-...-$ désigne l'opération de succession appliquée $n$ fois, suivie de l'opération de prédécession appliquée $n$ fois également. Mais comme le prédécesseur du sucesseur est égal à lui-même par définition, on a $p^{+-} = p$. On constate en développant que la même propriété doit être vérifiée lorsque les opérations de succession et de prédécession sont appliquées un nombre quelconque mais identique de fois. On a donc :

$$p^{+...+-...-} = p$$

En tenant compte de ces résultats dans le développement de la somme ci-dessus, on arrive à :

$$m + (p + n) = m^{+...+} + p$$

Mais $m^{+...+}$ n'est rien d'autre que la somme $m + n$, et :

$$m + (p + n) = (m + n) + p$$

L'addition étant commutative, on peut inverser $p$ et $n$ pour obtenir :

$$m + (n + p) = (m + n) + p$$

On peut donc associer les termes d'une somme comme on le désire, le résultat restera identique. On dit que l'addition sur $\setN$ est associative. On note aussi :

$$m + n + p = m + (n + p) = (m + n) + p$$


* Ordre

Soit $m,n \in \setN$. On dit que $n$ est plus petit ou égal à $m$, et on le note :

$$n \le m$$

si on peut trouver un $p \in \setN$ tel que :

$$m = n + p$$

En évaluant les additions $n+1$ et $n^- + 1$, on obtient :

\begin{align}
n^- + 1 &= n \)

\(
n + 1 &= n^+
\end{align}

Le choix $p = 1$ nous montre alors que :

$$n^- \le n \le n^+$$


** Plus grand ou égal

On note aussi :

$$m \ge n$$

pour signifier que $n \le m$.


** Total

Soir $m,n \in \setN$. Comme $m$ est, directement ou indirectement,
un successeur ou un prédécesseur de $n$, on a soit :

$$m \le n$$

soit :

$$n \le m$$

L'ordre usuel sur $\setN$ est total.


** Ordre strict

On note :

$$n \strictinferieur m$$

ou :

$$m \strictsuperieur n$$

lorsque $n \le m$ et $m \ne n$.


** Extrema

Comme tous les éléments de $\setN$ sont supérieurs au égaux à $0$, on a clairement :

$$\minor \setN = \{ 0 \}$$

et :

$$\inf \setN = \min \setN = 0$$

Par contre, si on suppose avoir trouvé $s \in \major \setN$, on a $s \le s^+ \in \setN$ ce qui contredit l'hypothèse de majorant. L'ensemble des majorants est donc vide, et le supremum n'existe pas dans $\setN$. On note donc :

$$\sup \setN = +\infty$$


* Ordre et addition

Soit $a,b,c,d \in \setN$. Supposons que :

$$a \le b$$
$$c \le d$$

On peut donc trouver $p,q \in \setN$ tels que :

\begin{align}
b &= a + p \)

\(
d &= c + q
\end{align}

En additionnant ces deux équations, on obtient :

$$b + d = a + p + c + q = (a + c) + (p + q)$$

Comme $p + q$ est également un naturel, on en conclut que :

$$a + c \le b + d$$

L'ordre est donc conservé lorsqu'on ajoute au moins autant au grand nombre qu'au petit. On parle d'invariance sous l'addition.


* Positivité

\label{sec:positivite_des_naturels}

Soit $n \in \setN$. La neutralité de $0$ pour l'addition nous permet d'écrire :

$$n = 0 + n$$

On en déduit que :

$$n \ge 0$$

pour tout $n \in \setN$ et :

$$n \strictsuperieur 0$$

lorsque $n \ne 0$.


* Soustraction

Soit l'ensemble :

$$\Delta = \{ (m,n) \in \setN^2 : n \le m \}$$

Choisissons $(m,n) \in \Delta$. On peut trouver $p \in \setN$ tel que :

$$m = n + p$$

Comme :

$$n + p = p + n = p^{+...+} = m$$

on voit que :

$$p = m^{-...-}$$

où $-...-$ désigne $n$ opérations de prédécessions. Le $p$ ainsi défini est donc unique. On dit que $p$ est la soustraction de $m$ et $n$, et on le note :

$$p = m - n$$


** $m \le n$

Si $m \strictinferieur n$, calculer la soustraction :

$$p = m - n = m^{-...-} = 0^{+...+-...-}$$

reviendrait à effectuer plus d'opérations de prédécessions que de sucessions. Nous serions donc amenés à devoir évaluer le prédécesseur de l'élément racine $0$, qui n'existe pas dans $\setN$. Cette opération n'est par conséquent pas définie.


** Neutralisation

La définition implique directement l'équivalence :

#+BEGIN_CENTER
\(
m = n = n + 0 \)

\(
\Longleftrightarrow \)

\(
m - n = 0
\)
#+END_CENTER


** Associativité

Soit $m,n,p \in \setN$ avec $n + p \le m$. On a trivialement :

$$(m - n) - p = m - (n + p)$$

On note aussi :

$$m - n - p = (m - n) - p = m - (n + p)$$


** Commutativité

Soit $m,n,p \in \setN$ avec $n + p \le m$. On voit que :

$$m - n - p = m - (n + p) = m - (p + n) = m - p - n$$


** Associativité mixte

Soit $m,n,p \in \setN$ avec $p \le n$. On a trivialement :

$$(m + n) - p = m + (n - p)$$

On note aussi :

$$m + n - p = (m + n) - p = m + (n - p)$$


** Commutativité mixte

Soit $m,n,p \in \setN$ avec $m,p \le n$. On a trivialement :

\begin{align}
m + n - p = (m + n) - p &= (n + m) - p \)

\(
&= n + (m - p) \)

\(
&= (m - p) + n \)

\(
&= m - p + n
\end{align}


* Ordre et soustraction

Soit $a,b,c,d \in \setN$. Supposons que :

$$a \le b$$
$$c \ge d$$

On peut donc trouver $p,q \in \setN$ tel que :

$$b = a + p$$

$$d + q = c$$

En soustrayant ces deux équations, on obtient :

$$b - d - q = a + p - c$$

$$b - d = a - c + p + q$$

Comme $p + q$ est aussi un naturel, on en conclut que :

$$a - c \le b - d$$

L'ordre est donc conservé lorsqu'on soustrait au moins autant au petit nombre qu'au grand. On parle d'invariance pour la soustraction.


* Multiplication

Soit $m,n \in \setN$. La multiplication usuelle, notée $\cdot : \setN \times \setN \mapsto \setN$, est définie par :

$$m \cdot 0 = 0$$

$$m \cdot n^+ = ( m \cdot n ) + m$$

Posant $i = m$ et $j = n^+$, on en déduit que :

$$i \cdot 0 = 0$$

$$i \cdot j = ( i \cdot j^- ) + i$$


** Priorité

Afin d'alléger les notations, nous convenons que la multiplication est toujours prioritaire sur l'addition. On pose donc :

$$i \cdot j + k = ( i \cdot j ) + k$$

pour tout $i,j,k \in \setN$.

La définition peut alors se réécrire :

$$m \cdot 0 = 0$$

$$m \cdot n^+ = m \cdot n + m$$


** Notation

Lorsque cela ne pose pas de problème d'ambiguité, on note aussi :

$$m \ n = m \cdot n$$


** Absorption

Soit $m \in \setN$. On déduit directement de la définition que :

\begin{align}
0 \cdot m &= 0 \cdot m^- + 0 \)

\(
\vdots && \)

\(
0 \cdot m &= 0 + ... + 0 = 0
\end{align}

On a donc $0 \cdot m = m \cdot 0 = 0$. On dit que $0$ est absorbant pour la multiplication.


** Définition alternative

Soit $m \ge 1$. En utilisant récursivement la définition, on obtient :

\begin{align}
m \cdot n &= m \cdot n^- + m \)

\(
&\vdots& \)

\(
&= m \cdot 0 + m + ... + m \)

\(
&= 0 + m + ... + m \)

\(
&= m + ... + m
\end{align}

où le membre de droite compte $n$ terme « $m$ ». Mais comme $m = m^- + 1$, on a :

$$m \cdot n = m^- + 1 + ... + m^- + 1$$

La commutativité nous permet de regrouper les $n$ nombres $1$ à la fin :

$$m \cdot n = m^- + ... + m^- + 1 + ... + 1$$

Il est clair que :

$$1 + ... + 1 = 0^{+...+} = n$$

On a dès lors :

$$m \cdot n = m^- + ... + m^- + n$$

Comme le membre de droite contient $n$ termes $m^-$, on en conclut que :

$$m \cdot n = m^- \cdot n + n$$

qui est une version alternative de la définition.


** Neutre multiplicatif

La définition implique que :

$$m \cdot 1 = m \cdot 0 + m = 0 + m = m$$

Mais en appliquant la définition alternative à $1 \cdot m$, il vient :

$$1 \cdot m = 0 \cdot m + m = m$$

On a donc $1 \cdot m = m \cdot 1 = m$. On dit que $1$ est neutre pour la multiplication.


** Commutativité

Soit $m \in \setN$. On a vu que $m \cdot 0 = 0 \cdot m$. L'équation :

$$m \cdot n = n \cdot m$$

Est donc vérifiée pour $n = 0$.

Supposons à présent que :

$$n^- \cdot m = m \cdot n^-$$

En appliquant les deux alternatives de la définition, on a :

$$m \cdot n = m \cdot n^- + m$$

$$n \cdot m = n^- \cdot m + m$$

et donc :

$$m \cdot n = n \cdot m$$

Puisque cette égalité est vraie pour $n = 0 = 1^-$, on en déduit qu'elle est également vraie pour $n = 1 = 2^-$, pour $n = 2 = 3^-$, etc. Elle est donc vérifiée pour tout $n \in \setN$ : la multiplication est commutative.


** Distributivité

Soit $m,n,p \in \setN$. On a :

$$m \cdot (n + p) = m + ... + m$$

où le membre de droite compte $n+p$ termes « $m$ ». Par associativité de l'addition, on peut regrouper les termes comme suit :

$$m \cdot (n + p) = (m + ... + m) + (m + ... + m)$$

où la première parenthèse compte $n$ termes et la seconde $p$ termes. On a donc :

$$m \cdot (n + p) = m \cdot n + m \cdot p$$

Par commutativité de la multiplication, on en déduit :

$$(n + p) \cdot m = n \cdot m + p \cdot m$$

On dit que la multiplication se distribue sur l'addition.


*** Sur la soustraction

Soit $m,n,p \in \setN$ avec $p \le n$ et :

$$q = n - p$$

On a :

$$m \cdot (p + q) = m \cdot p + m \cdot q$$

Mais comme $p + q = n$, il vient :

$$m \cdot n = m \cdot p + m \cdot (n - p)$$

On en déduit que :

$$m \cdot (n - p) = m \cdot n - m \cdot p$$

Par commutativité de la multiplication, on a également :

$$(n - p) \cdot m = n \cdot m - p \cdot m$$

On dit que la multiplication se distribue sur la soustraction.


** Unicité de l'absorbant

Nous allons voir que l'absorbant est unique. Soit $a_1, a_2 \in \setN$ tels que :

$$a_1 \cdot n = a_2 \cdot n = 0$$

pour tout $n \in \setN$. On en déduit que :

$$a_1 \cdot n - a_2 \cdot n = 0$$

En utilisant la distributivité, on obtient :

$$(a_1 - a_2) \cdot n = 0$$

Mais comme ce résultat doit être valable pour tout $n \in \setN$, il est valable pour $n = 1$ et on a :

$$(a_1 - a_2) \cdot 1 = a_1 - a_2 = 0$$

Autrement dit, $a_1 = a_2$. L'absorbant est donc unique.


** Associativité

Soit $m,n,p \in \setN$. On a :

$$m \cdot (n \cdot p) = m + ... + m$$

où le membre de droite compte $n \cdot p$ termes « $m$ ». Par associativité de l'addition, on peut les regrouper en $p$ parenthèses contenant chacune $n$ termes :

$$m \cdot (n \cdot p) = (m + ... + m) + ... + (m + ... + m)$$

ce qui revient à :

$$m \cdot (n \cdot p) = (m \cdot n) + ... + (m \cdot n)$$

Mais comme il y a $p$ parenthèses, on a :

$$m \cdot (n \cdot p) = (m \cdot n) \cdot p$$

La multiplication est donc associative. On note aussi :

$$m \cdot n \cdot p = m \cdot (n \cdot p) = (m \cdot n) \cdot p$$


** Produit nul

Soit $m,n \in \setN$ tels que :

$$m \cdot n = 0$$

Nous allons prouver qu'au moins un des deux facteurs doit être nul. Supposons que $m, n \ne 0$. On a alors :

$$m \cdot n = n + ... + n = 0$$

Mais comme $n \ne 0$, on a :

$$n \strictsuperieur 0$$

et :

$$0 = n + ... + n \ge n \strictsuperieur 0$$

ce qui est impossible. On a donc l'implication :

$$m \cdot n = 0 \quad \Rightarrow \quad m = 0 \quad \mathrm{ou} \quad n = 0$$


* Notation décimale

Soit le tuple :

$$(i_0,i_1,i_2,...i_{n - 1},i_n) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^{n + 1}$$

La notation décimale associée est définie par :

$$i_n i_{n - 1} ... i_2 i_1 i_0 = i_0 + i_1 \cdot 10 + i_2 \cdot 10^2 + ... + i_{n - 1} \cdot 10^{n - 1} + i_n \cdot 10^n$$

Exemple :

$$7512 = 2 + 1 \cdot 10 + 5 \cdot 10^2 + 7 \cdot 10^3$$


* Division entière

Soit $m,n \in \setN$. On définit la division entière $\diventiere : \setN \times \setN \to \setN$ par :

$$m \diventiere n = \sup \{ k \in \setN : k \cdot n \le m \}$$

On dit que $m$ est le numérateur, $n$ le dénominateur et $m \diventiere n$ le quotient de $m$ par $n$.


** Existence

Soit $m,n \in \setN$ avec $n \ne 0$ et :

$$A_{mn} = \{ k \in \setN : k \cdot n \le m \}$$

Pour tout naturel $p$ vérifiant $p \strictsuperieur m$, on a :

$$p \cdot n = p + ... + p \strictsuperieur p \strictsuperieur m$$

On en conclut que :

$$A_{mn} \subseteq \{ 0, 1, ..., m - 1, m \}$$

L'ensemble $A_{mn}$ contient donc un nombre fini d'éléments. Comme l'ordre
usuel sur $\setN$ est total, on en conclut que $A_{mn}$ admet un maximum
identique au suprémum. La division entière de $m$ par $n$ est donc bien définie :

$$m \diventiere n = \max A_{mn} = \sup A_{mn}$$

L'inclusion nous donne l'inégalité des maxima :

$$\max A_{mn} \le \max \{ 0, 1, ..., m - 1, m \} = m$$

On en déduit que :

$$m \diventiere n \le m$$


** Division par zéro

Soit $m \in \setN$. Essayons d'évaluer la division $m \diventiere 0$. Par absorption de $0$, on voit que :

$$k \cdot 0 = 0 \le m$$

pour tout $k \in \setN$. Par conséquent :

$$\{ k \in \setN : k \cdot 0 \le m \} = \setN$$

Le supremum n'existe pas dans $\setN$ et la division par zéro n'est par conséquent pas définie. On le note symboliquement :

$$m \diventiere 0 = \sup \setN = +\infty$$


** Division par un

Soit $m \in \setN$. On a :

$$m = m \cdot 1 \le m$$

et :

$$(m + 1) \cdot 1 = m + 1 \strictsuperieur m$$

On en déduit que :

$$m \diventiere 1 = m$$


** Zéro divisé

Soit $n \in \setN$ avec $n \ne 0$. On a :

$$\{ k \in \setN : k \cdot n \le 0 \} = \{ 0 \}$$

La division entière de $0$ par $n$ est donc nulle :

$$0 \diventiere n = \sup \{ 0 \} = 0$$


** Modulo

Soit $m,n \in \setN$. Par définition, on voit que :

$$(m \diventiere n) \cdot n \le m$$

Il est donc licite de définir le naturel :

$$r = m - (m \diventiere n) \cdot n$$

On dit que $r$ est le modulo de $m$ par rapport à $n$ et on le note :

$$m \modulo n = m - (m \diventiere n) \cdot n$$


** Décomposition

Soit $m,n \in \setN$. Par définition du modulo, a la décomposition :

$$m = (m \diventiere n) \cdot n + m \modulo n$$


** Reste

Soit $m,n \in \setN$. On dit aussi que $r = m \modulo n$ est le reste
de la division entière de $m$ par $n$.


** Exacte

Soit $m,n \in \setN$. Si $m \modulo n = 0$, on dit que la division entière est exacte. Dans
ce cas, la décomposition s'écrit simplement :

$$m = (m \diventiere n) \cdot n$$


** Bornes

Soit $m,n \in \setN$ et $k = m \diventiere n$. On sait déjà que :

$$m \modulo n \ge 0$$

par la positivité des naturels. Supposons de plus que :

$$m \modulo n = m - k \cdot n \ge n$$

on a alors :

$$m \ge n + k \cdot n = (k + 1) \cdot n$$

ce qui est contraire au caractère de supremum de $k$. Par conséquent :

$$0 \le m \modulo n \le n - 1$$


** Solution

Soit $m,n,k,r \in \setN$ avec $n \ne 0$. Supposons que :

$$m = k \cdot n + r$$

Par positivité des naturels, on a $r \ge 0$ et :

$$k \cdot n \le m$$

d'où l'on conclut par définition du suprémum que $k \le m \diventiere n$.
Si on a également :

$$r \le n - 1$$

on a alors :

$$(k + 1) \cdot n = k \cdot n + n \strictsuperieur k \cdot n + r = m$$

On en conclut que $k + 1 \strictsuperieur m \diventiere n$. Donc :

$$m \diventiere n = k$$

et :

$$m \modulo n = r$$


** Division de deux produits

Soit $m,n,q,i,j,k \in \setN$ avec $n,j \ne 0$ tels que :

$$m = q \cdot n$$
$$i = k \cdot j$$

On a alors les divisions exactes :

$$m \diventiere n = q$$
$$i \diventiere j = k$$

De plus :

$$m \cdot i = q \cdot k \cdot n \cdot j$$

ce qui signifie que :

$$(m \cdot i) \diventiere (n \cdot j) = q \cdot k$$

On a donc :

$$(m \cdot i) \diventiere (n \cdot j) = (m \diventiere n) \cdot (i \diventiere j)$$


** Plus grand commun diviseur

Soit $m,n \in \setN$ avec $n \ne 0$. On définit le plus grand commun diviseur de $m$ et $n$ par :

$$\pgcd(m,n) = \sup \{ k \in \setN : m \modulo k = n \modulo k = 0 \}$$

Comme les divisions sont exactes, on a :

$$m = \big[ m \diventiere \pgcd(m,n) \big] \cdot \pgcd(m,n)$$

et :

$$n = \big[ n \diventiere \pgcd(m,n) \big] \cdot \pgcd(m,n)$$


** Plus petit commun multiple

Soit $m,n \in \setN$. On définit le plus petit commun multiple de $m$ et $n$ par :

$$\ppcm(m,n) = \inf \{ k \in \setN : k \modulo m = k \modulo n = 0 \}$$

Comme les divisions sont exactes, on a :

$$\ppcm(m,n) = \big[ \ppcm(m,n) \diventiere m \big] \cdot m$$

et :

$$\ppcm(m,n) = \big[ \ppcm(m,n) \diventiere n \big] \cdot n$$


* Puissance

Soit $m,n \in \setN$ avec $n \ne 0$. Les puissances naturelles sont définies par :

\begin{align}
m^0 &= 1 \)

\(
m^n &= m \cdot m^{n-1}
\end{align}

En appliquant récursivement la définition, on obtient :

\begin{align}
m^n &= m \cdot m^{n-1} \)

\(
&\vdots& \)

\(
&= m \cdot ... \cdot m
\end{align}

où le membre de droite compte $n$ facteurs « $m$ ».


** Priorité

Nous convenons des règles de priorité :

$$m + n^p = m + (n^p)$$

$$m \cdot n^p = m \cdot (n^p)$$

valables pour tout $m,n,p \in \setN$.


** Somme en exposant

Soit $m,n,p \in \setN$. On a :

$$m^{n+p} = m \cdot ... \cdot m$$

où le membre de droite compte $n+p$ facteur $m$. En regroupant les $n$ premiers facteurs dans une première parenthèse et les $p$ facteurs restant dans la seconde, on a :

$$m^{n+p} = (m \cdot ... \cdot m) \cdot (m \cdot ... \cdot m)$$

qui n'est rien d'autre que :

$$m^{n+p} = m^n \cdot m^p$$


** Puissance d'un produit

$$\left(m \cdot n\right)^p = m \cdot n \cdot ... \cdot m \cdot n$$

où le membre de droite compte $p$ facteurs $m \cdot n$. La commutativité de la multiplication nous permet de les regrouper les $m$ d'un coté et les $n$ de l'autre :

$$\left(m \cdot n\right)^p = m \cdot ... \cdot m \cdot n \cdot ... \cdot n$$

c'est-à-dire :

$$\left(m \cdot n\right)^p = m^p \cdot n^p$$


** Puissance d'une puissance

Soit $m,n,p \in \setN$. On a :

\begin{align}
\left(m^n\right)^p &= \left(m \cdot ... \cdot m\right)^p \)

\(
&= m \cdot ... \cdot m
\end{align}

où le membre de droite compte $n \cdot p$ facteurs. On en conclut que :

$$\left(m^n\right)^p = m^{n \cdot p}$$


* Factorielle

Soit $n\in\setN$, $n \ne 0$. On définit la factorielle de $n$ par :

\begin{align*}
0 ! &= 1 \\
n ! &= n \cdot (n-1) !
\end{align*}

On a donc :

$$n ! = n \cdot (n - 1) \cdot (n - 2) \cdot ... \cdot 1 = 1 \cdot 2 \cdot 3 \cdot ... \cdot n$$

** Priorité

On convient que :

$$x \cdot y ! = x \cdot (y !)$$


* Monoïde

$(\setN,+)$ et $(\setN,\cdot)$ sont des monoïdes.


