
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Octogone régulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Classification des diagonales

Quels sont les types de $k$-diagonales dans un octogone ? On a :

$$ 1 \le k \le 8 \diventiere 2 - 1 = 3 $$

Les seules diagonales possibles sont :

- les $1$-diagonales, ou diagonales courtes
- les $2$-diagonales, ou diagonales de classe 1
- les $3$-diagonales, ou diagonales de classe 2

* Triangles formés par les rayons

#+TOC: headlines 1 local

** Raisonnement

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les rayons de
$\mathscr{C}$ reliant le centre aux sommets de l’octogone, découpant
ainsi la figure en huit triangles intérieurs :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-triangles-rayons.svg]]

Nous avons tenu compte du caractère isocèle des triangles intérieurs
dans la notation des angles.

Dans les triangles $O P_1 P_2$ et $O P_2 P_3$ on a :

$$ \abs{P_1 P_2} = \abs{P_2 P_3} $$

car l’octogone est régulier et :

$$ \abs{O P_1} = \abs{O P_2} = r $$

$$ \abs{O P_2} = \abs{O P_3} = r $$

par définition du cercle circonscrit. Ces triangles ont leurs trois
côtés de mêmes longueurs et sont donc isométriques. Un raisonnement
analogue nous montre que tous les triangles intérieurs de l’octogone
sont isométriques :

$$ O P_1 P_2
\qquad
O P_2 P_3
\qquad
O P_3 P_4
\qquad
O P_4 P_5 $$

$$ O P_5 P_6
\qquad
O P_6 P_7
\qquad
O P_7 P_8
\qquad
O P_8 P_1 $$

On a en particulier :

$$ \alpha_1 = \alpha_2 = \ldots = \alpha_8 $$

$$ \beta_1 = \beta_2 = \ldots = \beta_8 $$

Posons :

$$ \alpha = \alpha_1 $$

$$ \beta = \beta_1 $$

Les angles $\alpha_1$, $\alpha_2$, $\ldots$, $\alpha_8$ forment ensemble
un tour complet :

$$ \sum_{i=1}^6 \alpha_i = 8 \ \alpha = 2 \ \pi $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{2 \ \pi}{8} = 45^\circ $$

La somme des angles dans le triangle $O P_1 P_2$ nous donne :

$$ \alpha + 2 \ \beta = 45^\circ + 2 \ \beta = 180^\circ $$

En isolant $\beta$, on obtient :

$$ \beta = \frac{180^\circ - 45^\circ}{2} = 67.5^\circ $$

Les triangles intérieurs ont donc les angles suivants :

$$ \alpha = 45^\circ
\qquad \qquad \qquad
\beta = 67.5^\circ $$

Les angles internes d’un octogone valent :

$$ 2 \ \beta = 135^\circ $$

Le schéma devient donc :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-triangles-rayons-resolu.svg]]

On a aussi les angles internes :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angles-internes.svg]]

** Diamètres

On remarque que :

$$ \abs{\angleflex{P_1 O P_5}} = 4 \ \alpha = 180^\circ $$

Les points $O$, $P_1$ et $P_5$ sont alignés, ce qui signifie que $O$
se situe sur la $3$-diagonale $[P_1, P_5]$. Cette diagonale est donc un
diamètre du cercle $\mathscr{C}$.

Un raisonnement similaire nous montre que le centre du cercle circonscrit
est situé sur toutes les $3$-diagonales :

$$ [P_1, P_5]
\qquad \qquad \qquad
[P_2, P_6]
\qquad \qquad \qquad
[P_3, P_7]
\qquad \qquad \qquad
[P_4, P_8] $$

Ces $3$-diagonales sont donc aussi des diamètres du cercle.

** Conclusion

Dans un octogone régulier :

- deux rayons qui aboutissent à deux sommets consécutifs forment un angle
  au centre de $45^\circ$
- l’angle formé par un côté et un rayon qui aboutit à une de ses extrémités
  a une amplitude de $67.5^\circ$
- l’angle interne a une amplitude de $135^\circ$
- les $3$-diagonales sont des diamètres

* Longueur du côté

#+TOC: headlines 1 local

** Raisonnement

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-longueur-cote.svg]]

Appliquons la loi des cosinus à la longueur $c$ dans le triangle $O
P_1 P_2$ :

$$ c^2 = r^2 + r^2 - 2 \ r \ r \ \cos 45^\circ $$

Divisons par $r^2$ :

$$ \frac{c^2}{r^2} = 1 + 1 - 2 \ \cos 45^\circ $$

Remplaçons le cosinus par sa valeur :

$$ \frac{c^2}{r^2} = 2 - 2 \ \frac{\sqrt{2}}{2} $$

Prenons la racine carrée :

$$ \frac{c}{r} = \sqrt{2 - \sqrt{2}} $$

Ce rapport nous donne la longueur du côté en fonction du rayon :

$$ c = r \ \sqrt{2 - \sqrt{2}} $$

** En fonction du nombre d’argent

Ce résultat peut se réexprimer en fonction du
[[file:proportions-geometriques.org::#heading:nombre_d_argent][nombre
d’argent]] :

$$ \psi = 1 + \sqrt{2} $$

On peut remplacer la racine de deux par :

$$ \sqrt{2} = \psi - 1 $$

L’expression de la longueur du côté devient :

$$ c = r \ \sqrt{2 - (\psi - 1)} $$

En simplifiant, on obtient :

$$ c = r \ \sqrt{3 - \psi} $$

* Diagonales courtes

#+TOC: headlines 1 local

** Angle entre rayon et diagonale

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-rayon-diagonale-courte.svg]]

Nous avons tenu compte des résultats précédents et du caractère
isocèle des triangles dans la notation des angles.

On voit que :

$$ \theta = 2 \cdot 45^\circ = 90^\circ $$

Examinons le triangle $O P_2 P_8$, isocèle et rectangle en $O$. La
somme des angles nous donne :

$$ 2 \ \alpha + \theta = 2 \ \alpha + 90^\circ = 180^\circ $$

On en déduit l’amplitude de $\alpha$ :

$$ \alpha = \frac{180^\circ - 90^\circ}{2} = 45^\circ $$

Un raisonnement analogue nous donne le même résultat pour les autres
diagonales courtes.

*** Conclusion

Le triangle formé par une diagonale courte et le centre $O$ du cercle
circonscrit est rectangle en $O$. L’angle compris entre :

- une diagonale courte de l’octogone
- un rayon qui aboutit à une des extrémités de cette diagonale

a une amplitude de $45^\circ$.

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-rayon-diagonale-courte-resolu.svg]]

** Angle entre côté et diagonale

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-cote-diagonale-courte.svg]]

Nous avons tenu compte des résultats précédents et du caractère
isocèle des triangles dans la notation des angles.

Examinons le triangle isocèle $P_1 P_2 P_6$. La somme des angles nous
donne :

$$ 2 \ \alpha + 135^\circ = 180^\circ $$

On en déduit l’amplitude de $\alpha$ :

$$ \alpha = \frac{180^\circ - 135^\circ}{2} = 22.5^\circ $$

Un raisonnement analogue nous donne le même résultat pour les autres
diagonales courtes.

*** Conclusion

L’angle compris entre :

- une diagonale courte de l’octogone
- un côté qui relie une des extrémités de cette diagonale au sommet intermédiaire

a une amplitude de $22.5^\circ$.

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-cote-diagonale-courte-resolu.svg]]

** Angle entre deux diagonales

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-deux-diagonales-courtes.svg]]

La $3$-diagonale $[P_3,P_7]$ est un diamètre du cercle circonscrit. Par
conséquent, le triangle $P_1 P_3 P_7$ est rectangle en $P_1$ et :

$$ \alpha = 90^\circ $$

*** Conclusion

L’angle entre deux diagonales courtes partant d’un même sommet a
une amplitude de $90^\circ$. C’est donc un angle droit :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-deux-diagonales-courtes-resolu.svg]]

** Longueur

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-longueur-diagonale-courte.svg]]

On définit la longueur de la diagonale courte :

$$ L = \abs{P_2 P_8} $$

Le théorème de Pythagore appliqué au triangle rectangle $O P_2 P_8$
nous donne :

$$ L^2 = r^2 + r^2 = 2 \ r^2 $$

En prenant la racine carrée, on obtient une expression de la longueur
de la diagonale courte en fonction du rayon du cercle circonscrit :

$$ L = r \ \sqrt{2} $$

* Figures des diagonales courtes

#+TOC: headlines 1 local

** Carré

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Les angles internes du
quadrilatère $P_2 P_4 P_6 P_8$ sont des angles droits, car formés par
des diagonales courtes partant de mêmes sommets. De plus, toutes les
diagonales courtes on une même longueur $r \ \sqrt{2}$. Le quadrilatère
$P_2 P_4 P_6 P_8$ est donc un carré :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-carre-court-1.svg]]

Même constat pour le carré $P_1 P_3 P_5 P_7$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-carre-court-2.svg]]

* Diagonales de classe $2$

#+TOC: headlines 1 local

** Angle entre rayon et diagonale

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-rayon-diagonale-2.svg]]

Nous avons tenu compte des résultats précédents et du caractère
isocèle des triangles dans la notation des angles.

On voit que :

$$ \theta = 3 \cdot 45^\circ = 135^\circ $$

Examinons le triangle isocèle $O P_3 P_8$. La somme des angles nous
donne :

$$ 2 \ \alpha + \theta = 2 \ \alpha + 135^\circ = 180^\circ $$

On en déduit l’amplitude de $\alpha$ :

$$ \alpha = \frac{180^\circ - 135^\circ}{2} = 22.5^\circ $$

Un raisonnement analogue nous donne le même résultat pour les autres
diagonales courtes.

*** Conclusion

L’angle compris entre :

- une $2$-diagonale de l’octogone
- un rayon qui aboutit à une des extrémités de cette diagonale

a une amplitude de $22.5^\circ$.

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-rayon-diagonale-2-resolu.svg]]

** Angle entre côté et diagonale

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-cote-diagonale-2.svg]]

Nous avons tenu compte des résultats précédents et du caractère
isocèle des triangles dans la notation des angles.

L’angle $\alpha$ forme, avec un angle de $22.5^\circ$, un angle de
$67.5^\circ$ :

$$ \alpha + 22.5^\circ = 67.5^\circ $$

On en déduit la valeur de $\alpha$ :

$$ \alpha = 67.5^\circ - 22.5^\circ = 45^\circ $$

*** Conclusion

L’angle compris entre :

- une $2$-diagonale de l’octogone
- un côté qui relie une des extrémités de cette diagonale à un sommet intermédiaire

a une amplitude de $45^\circ$.

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-cote-diagonale-2-resolu.svg]]

** Angle entre deux diagonales

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-deux-diagonales-2.svg]]

Nous avons tenu compte des résultats précédents dans la notation
des angles.

L’angle $\alpha$ forme, avec deux angles de $45^\circ$, un angle interne
de $135^\circ$ :

$$ \alpha + 2 \cdot 45^\circ = 135^\circ $$

On en déduit que :

$$ \alpha = 135^\circ - 2 \cdot 45^\circ = 45^\circ $$

*** Conclusion

L’angle entre deux diagonales de classe $2$ partant d’un même sommet
a une amplitude de $45^\circ$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angle-deux-diagonales-2-resolu.svg]]

** Longueur

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-longueur-diagonale-2.svg]]

On définit la longueur de la diagonale de classe $2$ :

$$ \mathscr{L} = \abs{P_3 P_8} $$

L’angle au centre du triangle $O P_3 P_8$ a une amplitude de :

$$ \abs{\angleflex{P_3 O P_8}} = 3 \cdot 45^\circ = 135^\circ $$

Appliquons la loi des cosinus à la longueur $\mathscr{L}$ dans le
triangle $O P_3 P_8$ :

$$ \mathscr{L}^2 = r^2 + r^2 - 2 \ r \ r \ \cos 135^\circ $$

Divisons par $r^2$ :

$$ \frac{\mathscr{L}^2}{r^2} = 1 + 1 - 2 \ \cos 135^\circ $$

Le cosinus de l’angle supplémentaire nuos donne :

$$ \cos 135^\circ
= - \cos(180^\circ - 135^\circ)
= - \cos 45^\circ
= - \frac{\sqrt{2}}{2} $$

La loi des cosinus devient :

$$ \frac{\mathscr{L}^2}{r^2} = 2 + 2 \ \frac{\sqrt{2}}{2} = 2 + \sqrt{2} $$

Prenons la racine carrée :

$$ \frac{\mathscr{L}}{r} = \sqrt{2 + \sqrt{2}} $$

Ce rapport nous donne la longueur de la diagonale en fonction du rayon :

$$ \mathscr{L} = r \ \sqrt{2 + \sqrt{2}} $$

*** En fonction du nombre d’argent

Ce résultat peut se réexprimer en fonction du
[[file:proportions-geometriques.org::#heading:nombre_d_argent][nombre
d’argent]] :

$$ \psi = 1 + \sqrt{2} $$

On peut remplacer la racine de deux par :

$$ \sqrt{2} = \psi - 1 $$

L’expression de la longueur de la diagonale devient :

$$ \mathscr{L} = r \ \sqrt{2 + (\psi - 1)} $$

En simplifiant, on obtient :

$$ \mathscr{L} = r \ \sqrt{\psi + 1} $$

*** Rapport avec la longueur du côté
:properties:
:custom_id: heading:rapport_longueur_2_diagonale_cote
:end:

Examinons le rapport entre la longueur d’une $2$-diagonale :

$$ \mathscr{L} = r \ \sqrt{2 + \sqrt{2}} $$

et la longueur du côté de l’octogone :

$$ c = r \ \sqrt{2 - \sqrt{2}} $$

On obtient :

$$ \frac{\mathscr{L}}{c}
= \frac{r \ \sqrt{2 + \sqrt{2}}}{r \ \sqrt{2 - \sqrt{2}}}
= \frac{\sqrt{2 + \sqrt{2}}}{\sqrt{2 - \sqrt{2}}} $$

Multiplions numérateur et dénominateur du membre de droite par
$\sqrt{2 + \sqrt{2}}$ :

$$ \frac{\mathscr{L}}{c}
= \frac{\sqrt{(2 + \sqrt{2})^2}}{\sqrt{(2 - \sqrt{2}) (2 + \sqrt{2})}} $$

En utilisant les propriétés de la racine carrée et du binôme conjugué,
ce rapport devient :

$$ \frac{\mathscr{L}}{c}
= \frac{2 + \sqrt{2}}{\sqrt{4 - 2}}
= \frac{2 + \sqrt{2}}{\sqrt{2}} $$

Simplifions :

$$ \frac{\mathscr{L}}{c}
= \frac{2}{\sqrt{2}} + \frac{\sqrt{2}}{\sqrt{2}}
= \sqrt{2} + 1 $$

En isolant $\mathscr{L}$, on se rend compte que :

$$ \mathscr{L} = c \ \psi $$

où $\psi = 1 + \sqrt{2}$ est le
[[file:proportions-geometriques.org::#heading:nombre_d_argent][nombre
d’argent]].

* Figures des diagonales de classe $2$

#+TOC: headlines 1 local

** Trapèze isocèle

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-trapeze-isocele.svg]]

Nous avons tenu compte des résultats précédents dans la notation
des angles.

Le quadrilatère $P_1 P_2 P_3 P_8$ est un trapèze isocèle car il a
deux côtés $[P_1,P_8]$ et $[P_2,P_3]$ de même longueur formant un
angle de même amplitude avec le côté $[P_3,P_8]$.

*** Conclusion

Un quadrilatère formé par trois côtés contigus et une $2$-diagonale
de l’octogone régulier est un trapèze isocèle.

** Triangle rectangle

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-triangle-rectangle-diagonales-2.svg]]

La somme des angles dans le triangle $I P_2 P_3$ nous donne :

$$ \alpha = 180^\circ - 2 \cdot 45^\circ = 90^\circ $$

Ce triangle est donc rectangle en $I$.

L’angle $\beta$ est un angle droit car il forme, avec un angle de
$45^\circ$, un angle interne de l’octogone de $135^\circ$ :

$$ \beta = 135^\circ - 45^\circ = 90^\circ $$

L’angle $\gamma$ est un angle droit car il forme, avec un angle de
$45^\circ$, un angle interne de l’octogone de $135^\circ$ :

$$ \gamma = 135^\circ - 45^\circ = 90^\circ $$

*** Conclusion

Si deux diagonales forment chacune un angle de $45^\circ$ avec le même
côté de l’octogone, alors ces diagonales sont :

- perpendiculaires entre-elles
- perpendiculaires avec les côtés contigus de l’octogone

Notre schéma devient :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-triangle-rectangle-diagonales-2-resolu.svg]]

** Carré et rectangles

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-carre-et-rectangles-diagonales-2.svg]]

Nous avons tenu compte des résultats précédents et du caractère
isocèle des triangles dans la notation.

- On remarque que les quadrilatères $P_1 P_2 I_1 I_4$ et similaires sont
  des rectangles. Leurs côtés opposés sont identiques :

$$ \abs{I_1 I_4} = c
\qquad \qquad
\abs{I_2 I_3} = c
\qquad \qquad
\abs{I_1 I_2} = c
\qquad \qquad
\abs{I_3 I_4} = c $$

Par conséquent, le rectangle $I_1 I_2 I_3 I_4$ est un carré.

- Le théorème de Pythagore appliqué au triangle $I_1 P_2 P_3$ nous donne :

$$ c^2 = a^2 + a^2 = 2 \ a^2 $$

Prenons la racine carrée :

$$ c = a \ \sqrt{2} $$

Isolons $a$ :

$$ a = \frac{c}{\sqrt{2}} $$

Multiplions numérateur et dénominateur par la racine de $2$ :

$$ a = \frac{c \ \sqrt{2}}{(\sqrt{2})^2} $$

On obtient finalement :

$$ a = c \ \frac{\sqrt{2}}{2} $$

*** Conclusion

Notre schéma devient :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-carre-et-rectangles-diagonales-2-resolu.svg]]

*Remarque* : on obtient une structure similaire avec les quatre autres
$2$-diagonales.

*** Diagonale de classe $2$ en fonction du côté

Soit :

$$ \mathscr{L} = \abs{P_3 P_8} $$

la longueur de la $2$-diagonale. On voit sur le schéma que :

$$ \mathscr{L} = c + \frac{c \ \sqrt{2}}{2} + \frac{c \ \sqrt{2}}{2} $$

En simplifiant, il vient :

$$ \mathscr{L}
= c + \frac{2 \ c \ \sqrt{2}}{2}
= c + c \ \sqrt{2} $$

ou, en mettant $c$ en évidence :

$$ \mathscr{L} = c \ (1 + \sqrt{2}) $$

En utilisant la notation $\psi = 1 + \sqrt{2}$ pour le
[[file:proportions-geometriques.org::#heading:nombre_d_argent][nombre
d’argent]], on peut réécrire cette relation sous la forme :

$$ \mathscr{L} = c \ \psi $$

On retrouve le résultat de la section
[[#heading:rapport_longueur_2_diagonale_cote][concernant le rapport
entre ces deux grandeurs]].

* Tangente de $67.5^\circ$
:properties:
:custom_id: heading:tangente_de_67_5
:end:

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-trigonometrie.svg]]

On note le
[[file:proportions-geometriques.org::#heading:nombre_d_argent][nombre
d’argent]] par :

$$ \psi = 1 + \sqrt{2} $$

et la longueur de la $2$-diagonale par :

$$ \mathscr{L} = c \ (1 + \sqrt{2}) = c \ \psi $$

Le triangle $P_4 P_7 P_8$ est rectangle en $P_7$. On a donc par
définition :

$$ \tan 67.5^\circ = \frac{\mathscr{L}}{c} = \frac{c \ (1 + \sqrt{2})}{c} $$

et finalement :

$$ \tan 67.5^\circ = 1 + \sqrt{2} $$

Autrement dit, cette tangente est égale au nombre d’argent :

$$ \tan 67.5^\circ = \psi $$

On a aussi :

$$ \tan 22.5^\circ = \unsur{\tan 67.5^\circ} = \unsur{\psi} $$

Par définition du nombre d’argent, on a $1/\psi = \psi -2$ et :

$$ \tan 22.5^\circ = \psi - 2 $$

* Octogramme court

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. En traçant toutes les
diagonales courtes, on obtient l’octogramme court :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-octogramme-court.svg]]

* Octogramme de classe $2$

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. En traçant toutes les
$2$-diagonales, on obtient l’octogramme de classe $2$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-octogramme-2.svg]]
