
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Octogone rﾃｩgulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gﾃｩ courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathﾃｩmatique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Angles au centre

Le schﾃｩma ci-dessous reprﾃｩsente un octogone rﾃｩgulier inscrit dans un
cercle de centre $O$ et de rayon $r$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-tour.svg]]

On constate que les huit angles au centre d窶兮mplitude $\alpha$ forment
un tour complet :

$$ 8 \ \alpha = 2 \ \pi = 360^\circ $$

On a donc :

$$ \alpha = \frac{\pi}{4} = 45^\circ $$

Examinons le triangle $OAB$. Les longueurs des deux cﾃｴtﾃｩs reliﾃｩs au
centre $O$ sont de longueurs ﾃｩgales au rayon $r$. Il s窶兮git donc d窶冰n
triangle isocﾃｨle et les angles correspondants sont par symﾃｩtrie de mﾃｪme
amplitude :

$$ \beta = \gamma $$

La somme des angles du triangle $OAB$ vaut $180^\circ$ :

$$ \alpha + \beta + \gamma = 45^\circ + 2 \ \beta = 180^\circ $$

On en dﾃｩduit que :

$$ \beta = \frac{180^\circ - 45^\circ}{2} = 67,5^\circ $$

Ce rﾃｩsultat montre aussi que les angles internes d窶冰n octogone valent :

$$ \beta + \gamma = 67,5^\circ + 67,5^\circ = 135^\circ $$

Le schﾃｩma devient :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-tour-resolu.svg]]

* Diagonales

Le schﾃｩma ci-dessous reprﾃｩsente un octogone rﾃｩgulier muni de certaines
de ses diagonales, ainsi que les diamﾃｨtres du cercle  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-diagonales.svg]]

Nous avons tenu compte de la symﾃｩtrie dans la notation des angles.

Dans le quadrilatﾃｨre $IJKL$, la somme des angles vaut $360^\circ$ :

$$ 4 \ \delta = 360^\circ $$

ce qui nous donne la valeur de $\delta$ :

$$ \delta = 90^\circ $$

Comme $\delta$ et $\epsilon$ forment ensemble un angle plat, on a :

$$ \delta + \epsilon = 90^\circ + \epsilon = 180^\circ $$

et :

$$ \epsilon = 90^\circ $$

La somme des angles dans le quadrilatﾃｨre $EFJK$ nous donne :

$$ 2 \ \epsilon + 2 \ \tau = 2 \cdot 90^\circ + 2 \ \tau = 360^\circ $$

d窶冩ﾃｹ :

$$ \tau = \frac{360^\circ - 2 \cdot 90^\circ}{2} = 90^\circ $$

Comme $\epsilon$ et $\chi$ forment ensemble un angle plat, on a :

$$ \epsilon + \chi = 90^\circ + \chi = 180^\circ $$

et :

$$ \chi = 90^\circ $$

La somme des angles dans le triangle $CLB$ nous donne :

$$ 2 \ \alpha + \chi = 2 \ \alpha + 90^\circ = 180^\circ $$

c窶册st-ﾃ-dire :

$$ \alpha = \frac{180^\circ - 90^\circ}{2} = 45^\circ $$

Les angles $\alpha$ et $\gamma$ forment, avec un angle de $67.5^\circ$, un
des angles internes de l窶冩ctogone qui vaut $135^\circ$. On a donc :

$$ \alpha + \gamma + 67.5^\circ = 45^\circ + \gamma + 67.5^\circ = 135^\circ $$

c窶册st-ﾃ-dire :

$$ \gamma = 135^\circ - 45^\circ - 67.5^\circ = 22.5^\circ $$

** Conclusion

Les diagonales d窶冰n octogone rﾃｩgulier forment

- des quadrilatﾃｨres dont les angles sont droits
- des petits triangles rectangles dont les angles aigus valent $45^\circ$
- des angles de $22.5^\circ$ entre les rayons du cercle circonscrit et les diagonales
  construites en sautant deux sommets de l窶冩ctogone

Le schﾃｩma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-diagonales-resolu.svg]]

* Nombre d窶兮rgent

Le schﾃｩma ci-dessous reprﾃｩsente un octogone rﾃｩgulier muni de certaines
de ses diagonales, ainsi que les diamﾃｨtres du cercle  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-nombre-d-argent.svg]]

Nous avons tenu compte de la symﾃｩtrie, de l窶冓nvariance sous rotation et
des angles droits dans la notation des longueurs et des angles.

Le cercle est de rayon $r$. La longueur du cﾃｴtﾃｩ de l窶冩ctogone se note :

$$ l = \abs{AB} = \abs{BC} = \ldots $$

En tenant compte des multiples quadrilatﾃｨres qui sont des rectangles, on
obtient :

$$ l = \abs{LI} = \abs{KJ} = \ldots $$

On dﾃｩfinit aussi la distance :

$$ a = \abs{CL} = \abs{DK} = \ldots $$

** Pythagore

Appliquons le thﾃｩorﾃｨme de Pythagore au triangle rectangle $CLB$ :

$$ l^2 = a^2 + a^2 = 2 \ a^2 $$

Isolons $a^2$ :

$$ a^2 = \frac{l^2}{2} $$

et prenons la racine carrﾃｩe :

$$ a = \frac{l}{\sqrt{2}} $$

En multipliant le numﾃｩrateur de le dﾃｩnominateur de la fraction par
$\sqrt{2}$, il vient :

$$ a = \frac{l \ \sqrt{2}}{\sqrt{2} \cdot \sqrt{2}} $$

et finalement :

$$ a = \frac{l \ \sqrt{2}}{2} $$

** Longueur maximale de l窶冩ctogone

La longueur $\mathscr{L}$ du segment $[C,H]$, qui reprﾃｩsente aussi la
longueur maximale de l窶冩ctogone, vaut :

$$ \mathscr{L} = a + l + a = \frac{l \ \sqrt{2}}{2} + l + \frac{l \ \sqrt{2}}{2} $$

ou encore :

$$ \mathscr{L} = l + 2 \cdot \frac{l \ \sqrt{2}}{2} = l + l \ \sqrt{2} $$

et finalement :

$$ \mathscr{L} = l \ (1 + \sqrt{2}) $$

Si on compare avec le nombre d窶兮rgent :

$$ \psi = 1 + \sqrt{2} $$

on voit que :

$$ \frac{\mathscr{L}}{l} = \psi $$

Le rapport entre la longueur maximale d窶冰n octogone et la longueur de
son cﾃｴtﾃｩ est ﾃｩgal au nombre argent.

** Tangente de $67.5^\circ$
:properties:
:custom_id: heading:tangente_de_67_5
:end:

Le triangle $DGH$ est un triangle rectangle. On a donc par dﾃｩfinition :

$$ \tan 67.5^\circ = \frac{\mathscr{L}}{l} = \frac{l \ (1 + \sqrt{2})}{l} $$

et finalement :

$$ \tan 67.5^\circ = 1 + \sqrt{2} $$

Autrement dit, cette tangente est ﾃｩgale au nombre d窶兮rgent :

$$ \tan $67.5^\circ$ = \psi $$

*** Tangente de $22.5^\circ$

On a :

$$ \tan 22.5^\circ = \unsur{\tan 67.5^\circ} = \unsur{\psi} $$

Par dﾃｩfinition du nombre d窶兮rgent, on a $1/\psi = \psi -2$ et :

$$ \tan 22.5^\circ = \psi - 2 $$

