
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Octogone régulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Classification des diagonales

Quels sont les types de $k$-diagonales dans un octogone ? On a :

$$ 1 \le k \le 8 \diventiere 2 - 1 = 3 $$

Les seules diagonales possibles sont :

- les $1$-diagonales
- les $2$-diagonales
- les $3$-diagonales

* Triangles formés par les rayons

Soit un octogone régulier $P_1 P_2 \ldots P_8$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les rayons de
$\mathscr{C}$ reliant le centre aux sommets de l’octogone, découpant
ainsi la figure en huit triangles intérieurs :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-triangles-rayons.svg]]

Nous avons tenu compte du caractère isocèle des triangles intérieurs
dans la notation des angles.

Dans les triangles $P_1 P_2 O$ et $P_2 P_3 O$ on a :

$$ \abs{P_1 P_2} = \abs{P_2 P_3} $$

car l’octogone est régulier et :

$$ \abs{O P_1} = \abs{O P_2} = r $$

$$ \abs{O P_2} = \abs{O P_3} = r $$

par définition du cercle circonscrit. Ces triangles ont leurs trois
côtés de mêmes longueurs et sont donc isométriques. Un raisonnement
analogue nous montre que tous les triangles intérieurs de l’octogone
sont isométriques. On a en particulier :

$$ \alpha_1 = \alpha_2 = \ldots = \alpha_8 $$

$$ \beta_1 = \beta_2 = \ldots = \beta_8 $$

Posons :

$$ \alpha = \alpha_1 $$

$$ \beta = \beta_1 $$

Les angles $\alpha_1$, $\alpha_2$, $\ldots$, $\alpha_8$ forment ensemble
un tour complet :

$$ \sum_{i=1}^6 \alpha_i = 8 \ \alpha = 2 \ \pi $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{2 \ \pi}{8} = 45^\circ $$

La somme des angles dans le triangle $P_1 P_2 O$ nous donne :

$$ \alpha + 2 \ \beta = 45^\circ + 2 \ \beta = 180^\circ $$

En isolant $\beta$, on obtient :

$$ \beta = \frac{180^\circ - 45^\circ}{2} = 67.5^\circ $$

Les triangles intérieurs ont donc les angles suivants :

$$ \alpha = 45^\circ
\qquad \qquad \qquad
\beta = 67.5^\circ $$

Les angles internes d’un octogone valent :

$$ 2 \ \beta = 135^\circ $$

Le schéma devient donc :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-triangles-rayons-resolu.svg]]

On a aussi les angles internes :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-angles-internes.svg]]

** Diamètres

On remarque que :

$$ \abs{\angleflex{P_1 O P_5}} = 4 \ \alpha = 180^\circ $$

Les points $O$, $P_1$ et $P_5$ sont alignés, ce qui signifie que $O$
se situe sur la diagonale $[P_1, P_5]$. Cette diagonale est donc un
diamètre du cercle $\mathscr{C}$.

Un raisonnement similaire nous montre que le centre du cercle circonscrit
est situé sur toutes les diagonales qui sautent trois sommets de
l’octogone régulier :

$$ [P_1, P_5]
\qquad \qquad \qquad
[P_2, P_6]
\qquad \qquad \qquad
[P_3, P_7]
\qquad \qquad \qquad
[P_4, P_8] $$

Ces diagonales sont donc aussi des diamètres du cercle.

* Diagonales

Le schéma ci-dessous représente un octogone régulier muni de certaines
de ses diagonales, ainsi que les diamètres du cercle  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-diagonales.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

Dans le quadrilatère $IJKL$, la somme des angles vaut $360^\circ$ :

$$ 4 \ \delta = 360^\circ $$

ce qui nous donne la valeur de $\delta$ :

$$ \delta = 90^\circ $$

Comme $\delta$ et $\epsilon$ forment ensemble un angle plat, on a :

$$ \delta + \epsilon = 90^\circ + \epsilon = 180^\circ $$

et :

$$ \epsilon = 90^\circ $$

La somme des angles dans le quadrilatère $EFJK$ nous donne :

$$ 2 \ \epsilon + 2 \ \tau = 2 \cdot 90^\circ + 2 \ \tau = 360^\circ $$

d’où :

$$ \tau = \frac{360^\circ - 2 \cdot 90^\circ}{2} = 90^\circ $$

Comme $\epsilon$ et $\chi$ forment ensemble un angle plat, on a :

$$ \epsilon + \chi = 90^\circ + \chi = 180^\circ $$

et :

$$ \chi = 90^\circ $$

La somme des angles dans le triangle $CLB$ nous donne :

$$ 2 \ \alpha + \chi = 2 \ \alpha + 90^\circ = 180^\circ $$

c’est-à-dire :

$$ \alpha = \frac{180^\circ - 90^\circ}{2} = 45^\circ $$

Les angles $\alpha$ et $\gamma$ forment, avec un angle de $67.5^\circ$, un
des angles internes de l’octogone qui vaut $135^\circ$. On a donc :

$$ \alpha + \gamma + 67.5^\circ = 45^\circ + \gamma + 67.5^\circ = 135^\circ $$

c’est-à-dire :

$$ \gamma = 135^\circ - 45^\circ - 67.5^\circ = 22.5^\circ $$

** Conclusion

Les diagonales d’un octogone régulier forment

- des quadrilatères dont les angles sont droits
- des petits triangles rectangles dont les angles aigus valent $45^\circ$
- des angles de $22.5^\circ$ entre les rayons du cercle circonscrit et les diagonales
  construites en sautant deux sommets de l’octogone

Le schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-diagonales-resolu.svg]]

* Nombre d’argent

Le schéma ci-dessous représente un octogone régulier muni de certaines
de ses diagonales, ainsi que les diamètres du cercle  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-nombre-d-argent.svg]]

Nous avons tenu compte de la symétrie, de l’invariance sous rotation et
des angles droits dans la notation des longueurs et des angles.

Le cercle est de rayon $r$. La longueur du côté de l’octogone se note :

$$ l = \abs{AB} = \abs{BC} = \ldots $$

En tenant compte des multiples quadrilatères qui sont des rectangles, on
obtient :

$$ l = \abs{LI} = \abs{KJ} = \ldots $$

On définit aussi la distance :

$$ a = \abs{CL} = \abs{DK} = \ldots $$

** Pythagore

Appliquons le théorème de Pythagore au triangle rectangle $CLB$ :

$$ l^2 = a^2 + a^2 = 2 \ a^2 $$

Isolons $a^2$ :

$$ a^2 = \frac{l^2}{2} $$

et prenons la racine carrée :

$$ a = \frac{l}{\sqrt{2}} $$

En multipliant le numérateur de le dénominateur de la fraction par
$\sqrt{2}$, il vient :

$$ a = \frac{l \ \sqrt{2}}{\sqrt{2} \cdot \sqrt{2}} $$

et finalement :

$$ a = \frac{l \ \sqrt{2}}{2} $$

** Longueur maximale de l’octogone

La longueur $\mathscr{L}$ du segment $[C,H]$, qui représente aussi la
longueur maximale de l’octogone, vaut :

$$ \mathscr{L} = a + l + a = \frac{l \ \sqrt{2}}{2} + l + \frac{l \ \sqrt{2}}{2} $$

ou encore :

$$ \mathscr{L} = l + 2 \cdot \frac{l \ \sqrt{2}}{2} = l + l \ \sqrt{2} $$

et finalement :

$$ \mathscr{L} = l \ (1 + \sqrt{2}) $$

Si on compare avec le nombre d’argent :

$$ \psi = 1 + \sqrt{2} $$

on voit que :

$$ \frac{\mathscr{L}}{l} = \psi $$

Le rapport entre la longueur maximale d’un octogone et la longueur de
son côté est égal au nombre argent.

** Tangente de $67.5^\circ$
:properties:
:custom_id: heading:tangente_de_67_5
:end:

Le triangle $DGH$ est un triangle rectangle. On a donc par définition :

$$ \tan 67.5^\circ = \frac{\mathscr{L}}{l} = \frac{l \ (1 + \sqrt{2})}{l} $$

et finalement :

$$ \tan 67.5^\circ = 1 + \sqrt{2} $$

Autrement dit, cette tangente est égale au nombre d’argent :

$$ \tan 67.5^\circ = \psi $$

*** Tangente de $22.5^\circ$

On a :

$$ \tan 22.5^\circ = \unsur{\tan 67.5^\circ} = \unsur{\psi} $$

Par définition du nombre d’argent, on a $1/\psi = \psi -2$ et :

$$ \tan 22.5^\circ = \psi - 2 $$

* Invariance sous rotation

L’octogone régulier est invariant lorsqu’on le fait tourner
d’un huitième de tour, c’est-à-dire de $45^\circ$. Les longueurs,
les proportions et les angles entre ses côtés et les lignes qui en
découlent :

- diagonales
- octogramme

ne varient donc pas non plus.
