
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Octogone régulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Angles au centre

Le schéma ci-dessous représente un octogone régulier inscrit dans un
cercle de centre $O$ et de rayon $r$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-tour.svg]]

On constate que les huit angles au centre d’amplitude $\alpha$ forment
un tour complet :

$$ 8 \ \alpha = 2 \ \pi = 360^\circ $$

On a donc :

$$ \alpha = \frac{\pi}{4} = 45^\circ $$

Examinons le triangle $OAB$. Les longueurs des deux côtés reliés au
centre $O$ sont de longueurs égales au rayon $r$. Il s’agit donc d’un
triangle isocèle et les angles correspondants sont par symétrie de même
amplitude :

$$ \beta = \gamma $$

La somme des angles du triangle $OAB$ vaut $180^\circ$ :

$$ \alpha + \beta + \gamma = 45^\circ + 2 \ \beta = 180^\circ $$

On en déduit que :

$$ \beta = \frac{180^\circ - 45^\circ}{2} = 67,5^\circ $$

Ce résultat montre aussi que les angles internes d’un octogone valent :

$$ \beta + \gamma = 67,5^\circ + 67,5^\circ = 135^\circ $$

Le schéma devient :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-tour-resolu.svg]]

* Diagonales

Le schéma ci-dessous représente un octogone régulier muni de certaines
de ses diagonales, ainsi que les diamètres du cercle  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-diagonales.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

Dans le quadrilatère $IJKL$, la somme des angles vaut $360^\circ$ :

$$ 4 \ \delta = 360^\circ $$

ce qui nous donne la valeur de $\delta$ :

$$ \delta = 90^\circ $$

Comme $\delta$ et $\epsilon$ forment ensemble un angle plat, on a :

$$ \delta + \epsilon = 90^\circ + \epsilon = 180^\circ $$

et :

$$ \epsilon = 90^\circ $$

La somme des angles dans le quadrilatère $EFJK$ nous donne :

$$ 2 \ \epsilon + 2 \ \tau = 2 \cdot 90^\circ + 2 \ \tau = 360^\circ $$

d’où :

$$ \tau = \frac{360^\circ - 2 \cdot 90^\circ}{2} = 90^\circ $$

Comme $\epsilon$ et $\chi$ forment ensemble un angle plat, on a :

$$ \epsilon + \chi = 90^\circ + \chi = 180^\circ $$

et :

$$ \chi = 90^\circ $$

La somme des angles dans le triangle $CLB$ nous donne :

$$ 2 \ \alpha + \chi = 2 \ \alpha + 90^\circ = 180^\circ $$

c’est-à-dire :

$$ \alpha = \frac{180^\circ - 90^\circ}{2} = 45^\circ $$

Les angles $\alpha$ et $\gamma$ forment, avec un angle de $67.5^\circ$, un
des angles internes de l’octogone qui vaut $135^\circ$. On a donc :

$$ \alpha + \gamma + 67.5^\circ = 45^\circ + \gamma + 67.5^\circ = 135^\circ $$

c’est-à-dire :

$$ \gamma = 135^\circ - 45^\circ - 67.5^\circ = 22.5^\circ $$

** Conclusion

Les diagonales d’un octogone régulier forment

- des quadrilatères dont les angles sont droits
- des petits triangles rectangles dont les angles aigus valent $45^\circ$
- des angles de $22.5^\circ$ entre les rayons du cercle circonscrit et les diagonales
  construites en sautant deux sommets de l’octogone

Le schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-diagonales-resolu.svg]]

* Nombre d’argent

Le schéma ci-dessous représente un octogone régulier muni de certaines
de ses diagonales, ainsi que les diamètres du cercle  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/octogone-nombre-d-argent.svg]]

Nous avons tenu compte de la symétrie, de l’invariance sous rotation et
des angles droits dans la notation des longueurs et des angles.

Le cercle est de rayon $r$. La longueur du côté de l’octogone se note :

$$ l = \abs{AB} = \abs{BC} = \ldots $$

En tenant compte des multiples quadrilatères qui sont des rectangles, on
obtient :

$$ l = \abs{LI} = \abs{KJ} = \ldots $$

On définit aussi la distance :

$$ a = \abs{CL} = \abs{DK} = \ldots $$

** Pythagore

Appliquons le théorème de Pythagore au triangle rectangle $CLB$ :

$$ l^2 = a^2 + a^2 = 2 \ a^2 $$

Isolons $a^2$ :

$$ a^2 = \frac{l^2}{2} $$

et prenons la racine carrée :

$$ a = \frac{l}{\sqrt{2}} $$

En multipliant le numérateur de le dénominateur de la fraction par
$\sqrt{2}$, il vient :

$$ a = \frac{l \ \sqrt{2}}{\sqrt{2} \cdot \sqrt{2}} $$

et finalement :

$$ a = \frac{l \ \sqrt{2}}{2} $$

** Longueur maximale de l’octogone

La longueur $\mathscr{L}$ du segment $[C,H]$, qui représente aussi la
longueur maximale de l’octogone, vaut :

$$ \mathscr{L} = a + l + a = \frac{l \ \sqrt{2}}{2} + l + \frac{l \ \sqrt{2}}{2} $$

ou encore :

$$ \mathscr{L} = l + 2 \cdot \frac{l \ \sqrt{2}}{2} = l + l \ \sqrt{2} $$

et finalement :

$$ \mathscr{L} = l \ (1 + \sqrt{2}) $$

Si on compare avec le nombre d’argent :

$$ \psi = 1 + \sqrt{2} $$

on voit que :

$$ \frac{\mathscr{L}}{l} = \psi $$

Le rapport entre la longueur maximale d’un octogone et la longueur de
son côté est égal au nombre argent.

** Tangente de $67.5^\circ$
:properties:
:custom_id: heading:tangente_de_67_5
:end:

Le triangle $DGH$ est un triangle rectangle. On a donc par définition :

$$ \tan 67.5^\circ = \frac{\mathscr{L}}{l} = \frac{l \ (1 + \sqrt{2})}{l} $$

et finalement :

$$ \tan 67.5^\circ = 1 + \sqrt{2} $$

Autrement dit, cette tangente est égale au nombre d’argent :

$$ \tan 67.5^\circ = \psi $$

*** Tangente de $22.5^\circ$

On a :

$$ \tan 22.5^\circ = \unsur{\tan 67.5^\circ} = \unsur{\psi} $$

Par définition du nombre d’argent, on a $1/\psi = \psi -2$ et :

$$ \tan 22.5^\circ = \psi - 2 $$

