
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Opérations
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:operations}

* Dépendances

  - Chapitre \ref{chap:fonctions} : Les fonctions


* Introduction

Soit un ensemble $\Omega$. Une opération $\opera$ sur $\Omega$, ou loi de composition interne sur $\Omega$, est une fonction qui, à deux éléments de $\Omega$, associe un troisième élément de $\Omega$ appelé résultat. On a donc formellement :

$$\opera : \Omega \times \Omega \mapsto \Omega$$

Si $z \in \Omega$ est le résultat de l'opération $\opera$ sur $x,y \in \Omega$, on le note :

$$z = x \opera y$$


* Neutre


** À gauche

On dit qu'un élément $n \in \Omega$ est neutre à gauche pour la loi $\opera$ si :

$$n \opera x = x$$

pour tout $x \in \Omega$.


** À droite

On dit qu'un élément $n \in \Omega$ est neutre à droite pour la loi $\opera$ si :

$$x \opera n = x$$

pour tout $x \in \Omega$.


** Simultané

On dit qu'un élément $n \in \Omega$ est neutre pour la loi $\opera$ si :

$$x \opera n = n \opera x = x$$

pour tout $x \in \Omega$.


** Unicité

Si $m,n \in \Omega$ sont des éléments neutres pour $\opera$, on a :

$$m = m \opera n = n$$

Si un neutre existe, il est unique.


* Inverse

Supposons que $n \in \Omega$ soit l'unique neutre pour la loi $\opera$.


** À gauche

On dit qu'un élément $y \in \Omega$ est un inverse à gauche de $x \in \Omega$ pour la loi $\opera$ si :

$$y \opera x = n$$


** À droite

On dit qu'un élément $y \in \Omega$ est un inverse à droite de $x \in \Omega$ pour la loi $\opera$ si :

$$x \opera y = n$$


** Simultané

On dit qu'un élément $x^\inverse \in \Omega$ est l'inverse de $x \in \Omega$ pour la loi $\opera$ si :

$$x \opera x^\inverse = x^\inverse \opera x = n$$


* Associativité

On dit que $\opera$ est associative si :

$$(x \opera y) \opera z = x \opera (y \opera z)$$

pour tout $x,y,z \in \Omega$. On définit alors :

$$x \opera y \opera z = x \opera (y \opera z) = (x \opera y) \opera z$$

** Extension

Soit $x_1,x_2,...,x_n \in \Omega$. On définit


** Unicité de l'inverse

On suppose que $\opera$ admet $n$ comme neutre. Soit $x \in \Omega$ et $y,z \in \Omega$ deux inverses de $x$. On a :

$$y \opera x \opera z = y \opera (x \opera z) = y \opera n = y$$

et :

$$y \opera x \opera z = (y \opera x) \opera z = n \opera z = z$$

On a donc :

$$y = z$$

Dans le cadre d'une opération associative, l'inverse d'un élément donné est unique.


* Commutativité

On dit que $\opera$ est commutative si :

$$x \opera y = y \opera x$$

pour tout $x,y \in \Omega$.

* Distributivité

Soit $\autreaddition, \autremultiplication$ deux lois de composition
interne sur $\Omega$. On dit que $\autremultiplication$ se distribue
sur $\autreaddition$ si :

$$z \autremultiplication (x \autreaddition y) = (z \autremultiplication x) \autreaddition (z \autremultiplication y)$$

et :

$$(x \autreaddition y) \autremultiplication z = (x \autremultiplication z) \autreaddition (y \autremultiplication z)$$

pour tout $x,y,z \in \Omega$.

* Opération induite

Soit une opération $\opera$ définie sur l'ensemble $\Omega$. L'opération
induite par $\opera$ sur $\Omega^n$ est définie par :

$$(x_1,x_2,...,x_n) \opera (y_1,y_2,...,y_n) = (x_1 \opera y_1, x_2 \opera y_2, ..., x_n \opera y_n)$$

pour tout :

$$(x_1,x_2,...,x_n), (y_1,y_2,...,y_n) \in \Omega^n$$

On note aussi :

$$z = x \opera y$$

pour :

$$x = (x_1,x_2,...,x_n) \in \Omega^n$$

$$y = (y_1,y_2,...,y_n) \in \Omega^n$$

et :

$$z = (z_1,z_2,...,z_n) \in \Omega^n$$

avec :

$$z_i = x_i \opera y_i$$

pour tout $i \in \{1,2,...,n\}$.


