
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Ordres stricts
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:ordreStrict}

* Dépendances

  - Chapitre \ref{chap:ordres} : Les ordres

* Définition

Un ordre strict sur un ensemble $\Omega$ est une relation permettant de déterminer si un élément de $\Omega$ est « strictement plus petit » qu'un autre. La différence fondamentale avec l'ordre large étant que les deux éléments doivent être distincts.

Soit $\strictinferieur$ un ordre strict sur l'ensemble $\Omega$ et $x,y,z \in \Omega$. Comme $x$ ne peut pas être distinct de lui-même, {\em on ne peut pas avoir} $x \strictinferieur x$. La relation $x \strictinferieur y$ implique donc que $x \ne y$.

La seule solution pour avoir simultanément $x \strictinferieur y $ et $y \strictinferieur x$ serait que $x = y$ comme dans le cas de l'ordre large. Ce n'est pas possible par définition. Les relations $x \strictinferieur y$ et $z \strictinferieur x$ impliquent donc que $y \ne z$. Par contre la propriété :

#+BEGIN_CENTER
\(
x \strictinferieur y, \quad y \strictinferieur z \quad \Rightarrow \quad x \strictinferieur z
\)
#+END_CENTER

est analogue à celle de l'ordre large.


** Multiple

La notation $x \strictinferieur y \strictinferieur z$ signifie que $x \strictinferieur y$ et que $y \strictinferieur z$.


* Plus grand

Soit $x, y \in \Omega$. On dit que $x$ est strictement plus grand que $y$,
et on le note :

$$x \strictsuperieur y$$

si et seulement si :

$$y \strictinferieur x$$


* Dérivé du large

On peut définir un ordre strict à partir d'un ordre large en disant que $x \strictinferieur y$ si et seulement si $x \le y$ et $x \ne y$.


* Complémentarité

Supposons que l'ordre $\le$ soit total. Si $x,y$ ne vérifient pas $x \le y$, on doit forcément avoir $y \le x$. Si on avait $x = y$, on aurait aussi $x \le y$ ce qui contredit l'hypothèse. Par conséquent, on doit avoir $x \ne y$. On en déduit que $y \strictinferieur x$.

Réciproquement, si la condition $y \strictinferieur x$ n'est pas vérifiée, on a soit $x = y$, soit $x \le y$. Mais comme $x \le y$ inclut la possibilité que $x = y$, on a simplement $x \le y$.

On a donc soit $x \le y$, soit $x \strictsuperieur y$. Ou encore, soit $x \strictinferieur y$, soit $x = y$, soit $x \strictsuperieur y$.


