
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Ordre inclusif
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:ordreInclusif}

* Dépendances

  - Chapitre \ref{chap:collections} : Les collections
  - Chapitre \ref{chap:ordres} : Les ordres
  - Chapitre \ref{chap:extrema} : Les extrema

* Ordre sur les ensembles

Soit l'ensemble $\Omega$ et l'ensemble de ses sous-ensembles :

$$\sousens(\Omega) = \{ A : A \subseteq \Omega \}$$

On dit que $A \in \sousens(\Omega)$ est plus petit ou égal à $B \in \sousens(\Omega)$ au sens de l'ordre inclusif si et seulement si :

$$A \subseteq B$$

On voit qu'il s'agit d'un ordre partiel.


** Attention

Ne pas confondre l'ordre inclusif $\subseteq$ avec la comparaison d'ensembles $\ensinferieur$ qui est elle basée sur l'ordre entre les éléments des ensembles concernés.


* Extrema inclusifs d'une collection

Soit l'ensemble de paramètres $X$ et la collection paramétrée :

$$\mathcal{C} = \{ A(x) \in \sousens(\Omega) : x \in X \}$$


** Majorant

Si on veut qu'un ensemble quelconque $M \subseteq \Omega$ soit un majorant inclusif de $\mathcal{C}$, il faut que $A(x) \subseteq M$ pour tout $x \in X$. Pour cela, il faut et il suffit que $M$ contienne tous les $A(x)$. Autrement dit, il faut et il suffit que $M$ contienne l'union des ensembles-éléments de la collection. On a donc :

$$\major_\subseteq \mathcal{C} = \left\{ M \in \sousens(\Omega) : \bigcup_{x \in X} A(x) \subseteq M \right\}$$


** Supremum

Etudions l'ensemble :

$$S = \bigcup_{x \in X} A(x) \in \sousens(\Omega)$$

Comme :

$$\bigcup_{x \in X} A(x) \subseteq S$$

on a :

$$S \in \major_\subseteq \mathcal{C}$$

On voit aussi que $S \subseteq M$ pour tout $M \in \major_\subseteq \mathcal{C}$. On en déduit que :

$$S = \min_\subseteq \major_\subseteq \mathcal{C} = \sup_\subseteq \mathcal{C}$$


** Minorant

Si on veut qu'un ensemble quelconque $L \subseteq \Omega$ soit un minorant inclusif de $\mathcal{C}$, il faut que $L \subseteq A(x)$ pour tout $x \in X$. Pour cela, il faut et il suffit que $L$ soit contenu dans tous les $A(x)$. Autrement dit, il faut et il suffit que $L$ soit contenu dans l'intersection des ensembles-éléments de la collection. On a donc :

$$\minor_\subseteq \mathcal{C} = \left\{ L \in \sousens(\Omega) : L \subseteq \bigcap_{x \in X} A(x) \right\}$$


** Infimum

Etudions l'ensemble :

$$I = \bigcap_{x \in X} A(x) \in \sousens(\Omega)$$

Comme :

$$I \subseteq \bigcap_{x \in X} A(x)$$

on a :

$$I \in \minor_\subseteq \mathcal{C}$$

On voit aussi que $L \subseteq I$ pour tout $L \in \minor_\subseteq \mathcal{C}$. On en déduit que :

$$I = \max_\subseteq \minor_\subseteq \mathcal{C} = \inf_\subseteq \mathcal{C}$$


** Conclusion

Le supremum inclusif d'une collection de sous-ensembles de $\Omega$ existe toujours dans $\sousens(\Omega)$ et est égal à l'union de tous ces ensembles :

$$\sup_\subseteq \{ A(x) \in \sousens(\Omega) : x \in X \} = \bigcup_{x \in X} A(x)$$

L'infimum inclusif d'une collection de sous-ensembles de $\Omega$ existe toujours dans $\sousens(\Omega)$ et est égal à l'intersection de tous ces ensembles :

$$\inf_\subseteq \{ A(x) \in \sousens(\Omega) : x \in X \} = \bigcap_{x \in X} A(x)$$


