#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Parallélisme
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Euclide

#+TOC: headlines 1 local

** Cinquième axiome

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cinquieme-axiome-d-euclide.svg]]

On voit que les angles $\alpha$ et $\beta$ sont situés à l’intérieur
des droites $a$ et $b$. On dit que ce sont des *angles internes*. On
remarque que $\alpha$ et $\beta$ sont situés du même côté de $c$.

L’axiome d’Euclide stipule que si la somme des angles internes
$\alpha$ et $\beta$ situés du même côté de $c$ est strictement
inférieure à deux angles droits, c’est-à-dire à un angle plat :

$$ \alpha + \beta < 180^\circ $$

alors les droites $a$ et $b$ sont sécantes et leur point d’intersection
se situe du même côté de $c$ que les angles $\alpha$ et $\beta$.

Cette axiome est valide dans le cadre de la géométrie euclidienne,
dont la géométrie plane fait partie.

** Corollaire

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cinquieme-axiome-d-euclide-corollaire.svg]]

Comme $\alpha$ et $\gamma$ forment ensemble un angle plat, on a :

$$ \alpha + \gamma = 180^\circ $$

ou encore :

$$ \alpha = 180^\circ - \gamma $$

Pareil pour $\beta$ et $\delta$ :

$$ \beta = 180^\circ - \delta $$

En sommant ces deux dernières équations, on obtient :

$$ \alpha + \beta = 360^\circ - \gamma - \delta $$

ou encore :

$$ \alpha + \beta = 360^\circ - (\gamma + \delta) $$

Si les angles internes $\gamma$ et $\delta$ forment ensemble un angle
strictement plus grand que l’angle plat :

$$ \gamma + \delta > 180^\circ $$

on a :

$$ \alpha + \beta < 360^\circ - 180^\circ $$

et les angles $\alpha$ et $\beta$ vérifient alors la condition de
l’axiome d’Euclide :

$$ \alpha + \beta < 180^\circ $$

Les droites $a$ et $b$ sont donc forcément sécantes.

La relation entre les quatre angles peut se réécrire :

$$ \gamma + \delta = 360^\circ - (\alpha + \beta) $$

Par conséquent, si les angles internes $\alpha$ et $\beta$ vérifient
l’axiome d’Euclide :

$$ \alpha + \beta < 180^\circ $$

la somme des angles internes situés de l’åutre côté de $c$ est
strictement supérieure à 180° :

$$ \gamma + \delta > 180^\circ $$

Les deux relations ci-dessous sont donc équivalentes entre-elles, et
impliquent que $a$ et $b$ sont sécantes.

** Condition nécessaire de parallélisme

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$.

Si la somme des deux angles internes $\alpha$ et $\beta$ situés d’un
même côté de $c$ n'est pas égale à 180°, elle est alors :

- soit strictement inférieure à 180°, et l’axiome d’Euclide s’applique
  directement
- soit strictement supérieure à 180°, et les deux angles situés de
  l’autre côté de $c$ vérifient l’axiome d’Euclide

Dans les deux cas, les deux droites $a$ et $b$ sont forcément sécantes.

La seule possibilité pour avoir deux droites $a$ et $b$ parallèles est
donc que la somme des deux angles internes situés d’un même côté
de $c$ soit égale à 180° :

$$ \alpha + \beta = 180^\circ $$

* Deux droites parallèles et une sécante

#+TOC: headlines 1 local

** Somme des angles

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-paralleles-une-secante-somme.svg]]

Si la somme des angles $\alpha$ et $\beta$ était distincte de 180°,
l’axiome d’Euclide et son corollaire nous indique que $a$ et $b$
seraient sécantes. Comme $a$ et $b$ sont parallèles, ce cas de figure
n’est pas possible et on a :

$$ \alpha + \beta = 180^\circ $$

** Sécante perpendiculaire

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec une
troisième droite $c$, elle-même perpendiculaire à $a$, comme indiqué
sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-paralleles-une-perpendiculaire.svg]]

Comme $a$ et $b$ sont parallèles, la somme des deux angles internes
situés à droite de $c$ vaut un angle plat :

$$ \alpha + 90^\circ = 180^\circ $$

On en déduit que :

$$ \alpha = 90^\circ = \frac{\pi}{2} $$

La droite $c$ est donc aussi perpendiculaire à $b$.

Une perpendiculaire à une droite $a$ est aussi perpendiculaire avec
toutes les droites parallèles à $a$.

** Angles alternes-internes

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-alternes-internes.svg]]

Les angles $\alpha$ et $\delta$ sont dits alternes-internes. Il en va
de même pour $\beta$ et $\gamma$.

Comme $a$ et $b$ sont parallèles, on doit avoir :

$$ \alpha + \beta = 180^\circ $$

On remarque aussi que les angles $\beta$ et $\delta$ forment ensemble
un angle plat :

$$ \beta + \delta = 180^\circ $$

En soustrayant la seconde équation de la première, on obtient :

$$ \alpha - \delta = 0 $$

c’est-à-dire :

$$ \alpha = \delta $$

ON montre par un raisonnement similaire que :

$$ \beta = \gamma $$

Deux angles alternes-internes sont de même amplitude.

** Angles alternes-externes

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-alternes-externes.svg]]

Les angles $\lambda$ et $\omega$ sont dits alternes-externes. Il en va
de même pour $\mu$ et $\theta$.

On remarque que les angles $\lambda$ et $\gamma$ sont opposés par le
sommet. On a donc :

$$ \lambda = \gamma $$

Les angles $\gamma$ et $\beta$ sont alternes-internes :

$$ \gamma = \beta $$

Enfin, les angles $\beta$ et $\omega$ sont également opposés par le
sommet :

$$ \beta = \omega $$

Par transitivité de l’égalité, on a finalement :

$$ \lambda = \omega $$

ON démontre par un raisonnement similaire que :

$$ \mu = \theta $$

Deux angles alternes-externes sont de même amplitude.

** Angles correspondants

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec
une troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-correspondants.svg]]

Les angles $\alpha$ et $\mu$ sont dits correspondants. Il en va de même
pour :

- $\beta$ et $\lambda$
- $\gamma$ et $\omega$
- $\delta$ et $\theta$

Les angles $\alpha$ et $\delta$ sont alternes-internes :

$$ \alpha = \delta $$

D’un autre côté, les angles $\delta$ et $\mu$ sont opposés par le
sommet :

$$ \delta = \mu $$

On a donc :

$$ \alpha = \mu $$

On montre par un raisonnement similaire que :

$$ \beta = \lambda $$

$$ \gamma = \omega $$

$$ \delta = \theta $$

Deux angles correspondants sont de même amplitude.

** Synthèse

Soit deux droites parallèles $a$ et $b$, toutes deux sécantes avec une
troisième droite $c$. Le schéma ci-dessous intègre tous les résultats
obtenus jusqu’à présent :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-paralleles-une-secante-synthese.svg]]

On voit qu’il ne reste plus que deux angles, $\alpha$ et $\beta$,
qui vérifient la relation :

$$ \alpha + \beta = 180^\circ $$

* Réciproque du cinquième axiome d’Euclide

#+TOC: headlines 1 local

** Énoncé

Soit deux droites $a$ et $b$, qui sont toutes deux sécantes avec une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reciproque-cinquieme-axiome-d-euclide.svg]]

Une conséquence directe du cinquième axiome d’Euclide est que,
si $a$ et $b$ sont parallèles, la somme de $\alpha$ et de $\beta$
doit faire 180°.

La réciproque est-elle vraie ? La relation :

$$ \alpha + \beta = 180^\circ $$

est-elle suffisante pour garantir que $a$ et $b$ sont parallèles ?
Nous allons prouver par l’absurde que oui.

*** Démonstration

Faisons l’hypothèse que la somme de $\alpha$ et $\beta$ vaut 180°
et supposons que $a$ et $b$ s’intersectent en un point $P$. On peut
alors construire une droite $d$, parallèle à $c$ et passant par $P$,
comme sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reciproque-cinquieme-axiome-d-euclide-absurde.svg]]

Comme $c$ et $d$ sont parallèles, nous pouvons placer sur le schéma
les angles alternes-internes égaux à $\alpha$ et à $\beta$. Les angles
$\alpha$, $\beta$ et $\gamma$ formant ensemble un angle plat, on a :

$$ \alpha + \beta + \gamma = 180^\circ $$

Si $\gamma$ est un angle nul, les droites $a$ et $b$ doivent être
confondues et sont donc parallèles. Dans le cas contraire, on a $\gamma >
0$ et :

$$ \alpha + \beta = 180^\circ $$

par hypothèse. On en conclut que :

$$ 180° = \alpha + \beta + \gamma > \alpha + \beta = 180^\circ $$

c’est-à-dire :

$$ 180° > 180^\circ $$

ce qui est manifestement une absurdité. Le point d’intersection $P$ ne
peut donc pas exister, et on a :

$$ a \cap b = \emptyset $$

La relation :

$$ \alpha + \beta = 180^\circ $$

garantit que les droites $a$ et $b$ sont parallèles.

** Conclusion

Si la somme des deux angles :

- internes aux droites $a$ et $b$
- situés du même côté de $c$

vaut 180°, alors $a$ et $b$ sont parallèles.

* Conditions de parallélisme

#+TOC: headlines 1 local

** Somme des angles

Soit deux droites $a$ et $b$, toutes deux sécantes avec une troisième
droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-paralleles-une-secante-somme.svg]]

La réciproque du cinquième d’axiome d’Euclide nous dit que si :

$$ \alpha + \beta = 180^\circ $$

alors $a$ et $b$ sont parallèles.

** Deux droites perpendiculaires à une troisième

Soit deux droites $a$ et $b$, toutes deux perpendiculaires à une
troisième droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/deux-droites-perpendiculaires-a-une-troisieme.svg]]

Par perpendicularité, les deux angles internes situés à droite de $c$
sont deux angles droits. leur somme vaut donc :

$$ 90^\circ + 90^\circ = 180^\circ $$

La réciproque du cinquième axiome d’Euclide s’applique donc, ce qui nous
garantit que les droites $a$ et $b$ sont parallèles.

Si deux droites sont perpendiculaires à une même troisième droite,
alors elles sont parallèles entre-elles.

** Angles alternes-internes

Soit deux droites $a$ et $b$, toutes deux sécantes avec une troisième
droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-alternes-internes-condition.svg]]

Si les angles alternes-internes $\alpha$ et $\gamma$ sont égaux :

$$ \alpha = \gamma $$

on a :

$$ \beta = 180^\circ - \gamma = 180^\circ - \alpha $$

c’est-à-dire :

$$ \alpha + \beta = 180^\circ $$

On en déduit que les droites $a$ et $b$ sont parallèles.

Si deux angles alternes-internes sont égaux, les droites qui les
délimitent sont parallèles.

** Angles alternes-externes

Soit deux droites $a$ et $b$, toutes deux sécantes avec une troisième
droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-alternes-externes-condition.svg]]

Si les angles alternes-externes $\lambda$ et $\mu$ sont égaux :

$$ \lambda = \mu $$

les angles qui leurs sont opposés par le sommet le sont aussi :

$$ \alpha = \lambda = \mu = \beta $$

On a donc des angles alternes-internes $\alpha$ et $\beta$ égaux,
ce qui signifie que les droites $a$ et $b$ sont parallèles.

Si deux angles alternes-externes sont égaux, les droites qui les
délimitent sont parallèles.

** Angles correspondants

Soit deux droites $a$ et $b$, toutes deux sécantes avec une troisième
droite $c$, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-correspondants-condition.svg]]

Si les angles correspondants $\alpha$ et $\beta$ sont égaux :

$$ \alpha = \beta $$

les angles qui leurs sont opposés par le sommet le sont aussi et :

$$ \alpha = \beta = \gamma $$

On a donc des angles alternes-internes $\alpha$ et $\gamma$ égaux,
ce qui signifie que les droites $a$ et $b$ sont parallèles.

Si deux angles correspondants sont égaux, les droites qui les délimitent
sont parallèles.
