
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Pentagone régulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Classification des diagonales

Quels sont les types de $k$-diagonales dans un pentagone ? On a :

$$ 1 \le k \le 5 \diventiere 2 - 1 = 1 $$

Les seules diagonales possibles sont donc des $1$-diagonales.

Dans la suite, on parlera donc simplement de diagonales pour désigner
les $1$-diagonales.

* Triangles formés par les rayons

#+TOC: headlines 1 local

** Raisonnement

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les rayons de
$\mathscr{C}$ reliant le centre aux sommets du pentagone, découpant
ainsi la figure en cinq triangles intérieurs :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-triangles-rayons.svg]]

Nous avons tenu compte du caractère isocèle des triangles intérieurs
dans la notation des angles.

Dans les triangles $P_1 P_2 O$ et $P_2 P_3 O$ on a :

$$ \abs{P_1 P_2} = \abs{P_2 P_3} $$

car le pentagone est régulier et :

$$ \abs{O P_1} = \abs{O P_2} = r $$

$$ \abs{O P_2} = \abs{O P_3} = r $$

par définition du cercle circonscrit. Ces triangles ont leurs trois
côtés de mêmes longueurs et sont donc isométriques. Un raisonnement
analogue nous montre que tous les triangles intérieurs du pentagone
sont isométriques. On a en particulier :

$$ \alpha_1 = \alpha_2 = \ldots = \alpha_5 $$

$$ \beta_1 = \beta_2 = \ldots = \beta_5 $$

Posons :

$$ \alpha = \alpha_1 $$

$$ \beta = \beta_1 $$

Les angles $\alpha_1$, $\alpha_2$, $\ldots$, $\alpha_5$ forment ensemble
un tour complet :

$$ \sum_{i=1}^6 \alpha_i = 5 \ \alpha = 2 \ \pi $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{2 \ \pi}{5} = 72^\circ $$

La somme des angles dans le triangle $P_1 P_2 O$ nous donne :

$$ \alpha + 2 \ \beta = 72^\circ + 2 \ \beta = 180^\circ $$

En isolant $\beta$, on obtient :

$$ \beta = \frac{180^\circ - 72^\circ}{2} = 54^\circ $$

Les triangles intérieurs ont donc les angles suivants :

$$ \alpha = 72^\circ
\qquad \qquad \qquad
\beta = 54^\circ $$

Les angles internes d’un pentagone valent :

$$ 2 \ \beta = 108^\circ $$

Le schéma devient donc :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-triangles-rayons-resolu.svg]]

On a aussi les angles internes :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-angles-internes.svg]]

** Conclusion

Dans un pentagone régulier :

- deux rayons qui aboutissent à deux sommets consécutifs forment un angle
  au centre de $72^\circ$
- l’angle formé par un côté et un rayon qui aboutit à une de ses extrémités
  a une amplitude de $54^\circ$
- l’angle interne a une amplitude de $108^\circ$

* Diagonales
:properties:
:custom_id: heading:diagonales
:end:

#+TOC: headlines 1 local

** Angle entre côté et diagonale
:properties:
:custom_id: heading:angle_entre_cote_et_diagonale
:end:

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace la diagonale
$[P_2,P_5]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales.svg]]

Nous avons tenu compte du caractère isocèle des triangles dans la
notation des angles.

Examinons le triangle $P_1 P_2 P_5$. La somme des angles nous donne :

$$ 2 \ \alpha + 108^\circ = 180^\circ $$

On en déduit l’amplitude de $\alpha$ :

$$ \alpha = \frac{180^\circ - 108^\circ}{2} = 36^\circ $$

L’angle compris entre une diagonale du pentagone et un côté qui
relie une des extrémités de la diagonale au sommet intermédiaire
vaut $36^\circ$.

Notre schéma devient :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-resolu.svg]]

** Angle entre deux diagonales

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace deux diagonales
partant d’un même sommet, disons $[P_1,P_3]$ et $[P_1,P_4]$ :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-angles.svg]]

L’angle $\alpha$ forme, avec ceux angles de $36^\circ$, un angle interne
de $108^\circ$ :

$$ \alpha + 2 \cdot 36^\circ = 108^\circ $$

On en déduit que :

$$ \alpha = 108^\circ - 2 \cdot 36^\circ = 36^\circ $$

L’angle entre deux diagonales partant d’un même sommet vaut
$36^\circ$.

Notre schéma devient :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-angles-resolu.svg]]

** Isométrie

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace deux diagonales
quelconques, disons $[P_1,P_3]$ et $[P_1,P_4]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-isometrie.svg]]

Les triangles $P_1 P_2 P_3$ et $P_1 P_5 P_4$ ont :

- deux côtés de même longueur $c$
- trois angles de mêmes amplitudes

Ces triangles sont donc isométriques et :

$$ d_1 = d_2 $$

Toutes les diagonales d’un pentagone régulier ont la même longueur.

* Cerf-volant
:properties:
:custom_id: heading:cerf_volant
:end:

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Traçons le cerf-volant $O
P_5 P_1 P_2$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-cerf-volant.svg]]

Comme la diagonale $[O,P_1]$ traverse les deux triangles isocèles du
cerf-volant, elle est la médiatrice de l’autre diagonale $[P_2,P_5]$.

Dans le triangle rectangle $O I P_2$, l’angle $\alpha$ est le
complémentaire de $72^\circ$ :

$$ \alpha = 90^\circ - 72^\circ = 18^\circ $$

Dans le triangle rectangle $I O P_5$, l’angle $\beta$ est le
complémentaire de $72^\circ$ :

$$ \beta = 90^\circ - 72^\circ = 18^\circ $$

On a donc :

$$ \alpha = \beta = 18^\circ $$

En conclusion :

- les rayons du cercle circonscrit passant par les sommets du pentagone
  sont les médiatrices des diagonales
- l’angle compris entre une diagonale du pentagone et le rayon du cercle
  circonscrit qui passe par une de des extrémités vaut $18^\circ$

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-cerf-volant-resolu.svg]]

* Pentagramme

#+TOC: headlines 1 local

** Introduction

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Si on trace toutes les
diagonales, on obtient une étoile à cinq branches. Cette figure est
appelée un pentagramme :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme.svg]]

Nous avons tenu compte dans la notation :

- des angles opposés par le sommet
- de l’angle de $36^\circ$ entre une diagonale du pentagone et un côté
  qui relie une des extrémités de la diagonale au sommet intermédiaire
- de l’angle de $36^\circ$ entre deux diagonales qui partent du même sommet

Dans le triangle $P_1 S_1 P_2$, la somme des angles nous donne :

$$ \lambda + 36^\circ + 36^\circ = 180^\circ $$

d’où :

$$ \lambda = 180^\circ - 2 \cdot 36^\circ = 108^\circ $$

Dans le triangle $P_1 S_5 P_5$, la somme des angles nous donne :

$$ \mu = 180^\circ - 2 \cdot 36^\circ = 108^\circ $$

Comme $\lambda$ et $\alpha$ forment ensemble un angle plat, on a :

$$ \alpha = 180^\circ - \lambda = 180^\circ - 108^\circ = 72^\circ $$

Comme $\mu$ et $\beta$ forment ensemble un angle plat, on a :

$$ \beta = 180^\circ - \mu = 180^\circ - 108^\circ = 72^\circ $$

Le triangle $P_1 S_1 S_5$ est isocèle car il a deux angles de même
amplitude.

Remarquons que le triangle $P_1 S_1 P_2$ est aussi un triangle isocèle
car il a également deux angles de même amplitude.

Un raisonnement similaire nous montre le même résultat pour les autres
pointes du pentagramme. On en conclut que :

- les triangles isocèles du type $P_1 S_1 S_5$ qui forment les pointes du pentagramme
  ont un angle au sommet de $36^\circ$ et deux autres angles de $72^\circ$.
- les triangles isocèles du type $P_1 S_1 P_2$ qui complètent le pentagramme
  pour former le pentagone ont un angle obtus de $108^\circ$ et deux
  angles aigus de $36^\circ$

Les triangles qui constituent les pointes du pentagramme ont tous un
angle de même amplitude compris entre deux côtés de même longueur. Ces
triangles sont donc tous isométriques.

Notre schéma devient :

#+attr_html: :width 47%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme-resolu.svg]]

** Corollaire

Les triangles du type $P_1 S_1 P_2$ ont les mêmes angles
que l’on retrouve dans les triangles du type $P_1 P_2
P_5$, que nous avons analysé dans la section concernant
[[#heading:angle_entre_cote_et_diagonale][l’angle entre côté et
diagonale]]. Ces deux catégories de triangles sont donc semblables.

** Cerf-volants

#+TOC: headlines 1 local

*** Introduction

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Traçons le pentagramme et
examinons-en la partie supérieure :

#+attr_html: :width 65%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme-cerf-volants.svg]]

Nous avons tenu compte des résultats précédents dans la notation,
avec en particulier :

- les triangles isocèles formés par le pentagone et le pentagramme
- l’angle de $18^\circ$ entre une diagonale du pentagone et le rayon
  qui passe par une de ses extrémités
  + voir la section sur le [[#heading:cerf_volant][cerf-volant formé
    par le pentagone et les rayons]]

On définit :

$$ a
= \abs{P_1 S_1}
= \abs{P_1 S_5}
= \abs{P_2 S_1}
= \abs{P_5 S_5}
= \ldots
\qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \quad $$

$$ b_1 = \abs{S_1 I_1}
\qquad \qquad \qquad
c_1 = \abs{I_1 S_5}
\qquad \qquad \qquad
b_2 = \abs{S_2 I_2}
\qquad \qquad \qquad
c_2 = \abs{I_2 S_1} $$

$$ h_1 = \abs{P_1 I_1}
\qquad \qquad \qquad
h_2 = \abs{P_2 I_2}
\qquad \qquad \qquad
s_1 = \abs{O I_1}
\qquad \qquad \qquad
s_2 = \abs{O I_2} $$

$$ f_1 = \abs{O S_1}
\qquad \qquad \qquad
f_2 = \abs{O S_2}
\qquad \qquad \qquad \qquad \qquad
\qquad \qquad \qquad \qquad \qquad \qquad $$

*** Longueurs

- Le triangle $P_1 S_1 S_5$ étant isocèle en $P_1$, la hauteur $h_1$ qui
  part de $P_1$ est aussi la médiane du côté opposé :

$$ b_1 = c_1 $$

Idem dans le triangle $P_2 S_2 S_1$ :

$$ b_2 = c_2 $$

- Les triangles rectangles $P_1 S_1 I_1$ et $P_2 I_2 S_1$ ont un côté $a$
  de même longueur et un angle de $18^\circ$. Ces triangles sont donc
  isometriques et :

$$ b_1 = c_2
\qquad \qquad \qquad
h_1 = h_2 $$

En compilant les derniers résultats, on obtient :

$$ b_2 = c_2 = b_1 = c_1 $$

- Examinons les relations :

$$ r = h_1 + s_1 $$

$$ r = h_2 + s_2 $$

Isolons les $s_i$ :

$$ s_1 = r - h_1 $$

$$ s_2 = r - h_2 $$

Mais $h_1 = h_2$ et :

$$ s_1 = r - h_1 = r - h_2 = s_2 $$

Comme on a aussi $b_1 = c_2$, les quadrilatères du type $O I_1 S_1 I_2$
sont des cerf-volants.

- Les triangles rectangles $O I_2 S_1$ et $O I_2 S_2$ ont leurs
  deux cathères de mêmes longueurs car $b_2 = c_2$. Ils sont donc
  isométriques et :

$$ f_1 = f_2 $$

Les quadrilatères du type $P_2 S_2 O S_1$ sont des cerfs-volants.

*** Angles

Dans le cerf-volant $O I_1 S_1 I_2$, la diagonale $[O,S_1]$ traverse les
deux triangles isocèles $O I_1 I_2$ et $S_1 I_1 I_2$ qui le composent.
Cette diagonale est donc la bissectrice de l’angle $\angleflex{I_1 O
I_2}$ :

$$ \alpha = \beta $$

Or, $\alpha$ et $\beta$ forment ensemble un angle de $72^\circ$, car situé
entre deux rayons qui passent par des sommets consécutifs du pentagone.
On en conclut que :

$$ 2 \ \alpha = 72^\circ $$

c’est-à-dire :

$$ \alpha = 36^\circ $$

*** Conclusion

Un raisonnement similaire peut être appliqué aux autres pointes et
cerf-volants du pentagramme. Notre schéma devient :

#+attr_html: :width 52%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme-cerf-volants-resolu.svg]]

*** Corollaire

On a :

$$ \angleflex{P_1 O S_3} = 5 \cdot 36^\circ = 180^\circ $$

Les points $P_1$, $O$ et $S_3$ sont alignés. Le centre $O$ se trouve
donc sur le segment $[P_1,S_3]$.

Ce résultat est aussi valable pour les autres segments du même type :

$$ \angleflex{P_2 O S_4}
= \angleflex{P_3 O S_5}
= \angleflex{P_4 O S_1}
= \angleflex{P_5 O S_2}
= 180^\circ $$

Le point $O$ est donc l’intersection de tous ces segments :

$$ \{ O \}
= [P_1,S_3]
\cap [P_2,S_4]
\cap [P_3,S_5]
\cap [P_4,S_1]
\cap [P_5,S_2] $$

Ce constat nous permet de retrouver le centre du cercle circonscrit
d’un pentagone.

* Nombre d’or

#+TOC: headlines 1 local

** Introduction

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 47%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-nombre-d-or.svg]]

Nous avons tenu compte des résultats précédents dans la notation,

On définit :

$$ c = \abs{P_1 P_2} = \abs{P_1 P_5} = \ldots $$

$$ a = \abs{P_2 S_1} = \abs{P_5 S_5} = \ldots $$

$$ b = \abs{S_1 S_5} = \abs{S_4 S_5} = \ldots $$

ainsi que :

$$ d = \abs{P_2 P_5} $$

pour la longueur de la diagonale.

** Triangle isocèle

Dans le triangle $P_1 P_2 S_5$, on a :

$$ \abs{\angleflex{S_5}} = \abs{\angleflex{P_1 S_5 P_2}} = 72^\circ $$

et :

$$ \abs{\angleflex{P_1}}
= \abs{\angleflex{P_2 P_1 S_5}}
= 36^\circ + 36^\circ = 72^\circ $$

Le triangle $P_1 P_2 S_5$ est donc isocèle en $P_2$ et :

$$ \abs{P_1 P_2} = \abs{P_2 S_5} $$

c’est-à-dire :

$$ a + b = c $$

On a aussi :

$$ d = a + b + a = c + a $$

** Triangles semblables

Les triangles $P_1 P_2 P_5$ et $S_5 P_1 P_5$ ont deux angles de même
amplitude : ce sont donc des triangles semblables. On a en particulier :

$$  \frac{c}{a} = \frac{d}{c} $$

Remplaçons $d$ par son expression en fonction de $c$ et $a$ :

$$ \frac{c}{a} = \frac{c + a}{c} = 1 + \frac{a}{c} $$

Posons :

$$ \phi = \frac{c}{a} $$

La relation entre les longueurs devient :

$$ \phi = 1 + \unsur{\phi} $$

Multiplions par $\phi$ :

$$ \phi^2 = \phi + 1 $$

et faisons passer tous les termes dans le membre de gauche :

$$ \phi^2 - \phi - 1 = 0 $$

La quantité $\phi$ étant un rapport de longueurs, elle doit être
strictement positive. Or, nous avons vu dans le chapitre sur les
[[file:proportions-geometriques.org][proportions géométriques]],
que la solution positive de cette équation définit le
[[file:proportions-geometriques.org::#heading:nombre_d_or][nombre
d’or]] :

$$ \phi = \frac{1 + \sqrt{5}}{2} $$

On a donc la proportion :

$$ \frac{d}{c} = \frac{c}{a} = \phi =\frac{1 + \sqrt{5}}{2} $$

Le rapport entre la longueur de la diagonale d’un pentagone et la
longueur de son côté est égal au nombre d’or.

** Cosinus de $36^\circ$
:properties:
:custom_id: heading:cosinus_de_36
:end:

Appliquons la [[file:trigonometrie.org::#heading:loi_des_cosinus][loi
des cosinus]] à la longueur $a$ dans le triangle $S_5 P_1 P_5$ :

$$ a^2 = a^2 + c^2 - 2 \ a \ c \ \cos 36^\circ $$

Divisons par $a^2$ :

$$ 1 = 1 + \frac{c^2}{a^2} - 2 \ \frac{c}{a} \ \cos 36^\circ $$

Comme le rapport $c / a$ est égal au nombre d’or $\phi$, cette
équation devient :

$$ 1 = 1 + \phi^2 - 2 \ \phi \ \cos 36^\circ $$

Simplifions :

$$ 0 = \phi^2 - 2 \ \phi \ \cos 36^\circ $$

Isolons le cosinus :

$$ \cos 36^\circ = \frac{\phi^2}{2 \ \phi} $$

c’est-à-dire :

$$ \cos 36^\circ = \frac{\phi}{2} $$

Le cosinus de $36^\circ$ vaut la moitié du nombre d’or.

*** Sinus de $54^\circ$

Il en va de même pour le sinus de l’angle complémentaire, à savoir $54^\circ$ :

$$ \sin 54^\circ = \frac{\phi}{2} $$

** Cosinus de $72^\circ$

Appliquons la [[file:trigonometrie.org::#heading:loi_des_cosinus][loi
des cosinus]] à la longueur $c$ dans le triangle $S_5 P_1 P_5$ :

$$ c^2 = a^2 + a^2 - 2 \ a \ a \ \cos 108^\circ $$

Or :

$$ \cos 72^\circ = \cos(180^\circ - 108^\circ) = - \cos 108^\circ $$

La loi des cosinus peut se réécrire :

$$ c^2 = a^2 + a^2 + 2 \ a^2 \ \cos 72^\circ $$

Divisons par $a^2$ :

$$ \frac{c^2}{a^2} = 1 + 1 + 2 \ \cos 72^\circ $$

Comme le rapport $c / a$ est égal au nombre d’or $\phi$, cette
équation devient :

$$ \phi^2 = 2 + 2 \ \cos 72^\circ $$

Utilisons la relation $\phi^2 = \phi + 1$ :

$$ \phi + 1 = 2 + 2 \ \cos 72^\circ $$

Simplifions :

$$ \phi = 1 + 2 \ \cos 72^\circ $$

En isolant le cosinus de $72^\circ$, on obtient finalement :

$$ \cos 72^\circ = \frac{\phi - 1}{2} $$

*** Sinus de $18^\circ$

Il en va de même pour le sinus de l’angle complémentaire, à savoir $18^\circ$ :

$$ \sin 18^\circ = \frac{\phi - 1}{2} $$

* Rapport entre le côté et le rayon

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-rapport-cote-rayon.svg]]

La longueur du côté du pentagone se note :

$$ c = \abs{P_1 P_2} = \abs{P_2 P_3} = \ldots $$

Appliquons la [[file:trigonometrie.org::#heading:loi_des_cosinus][loi
des cosinus]] à la longueur $c$ dans le triangle $O P_1 P_2$ :

$$ c^2 = r^2 + r^2 - 2 \ r \ r \ \cos 72^\circ $$

Remplaçons le cosinus par son expression en fonction du nombre d’or :

$$ c^2 = r^2 + r^2 - 2 \ r^2 \ \frac{\phi - 1}{2} $$

Simplifions :

$$ c^2 = r^2 + r^2 - r^2 (\phi - 1) $$

Divisons par $r^2$ :

$$ \frac{c^2}{r^2} = 1 + 1 - (\phi - 1) = 3 - \phi $$

Il nous reste à prendre la racine carrée :

$$ \frac{c}{r} = \sqrt{3 - \phi} $$

pour obtenir le rapport entre le côté du pentagone régulier et le
rayon du cercle circonscrit.
