
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Pentagone régulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles formés par les rayons

Soit un pentagone régulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les rayons de
$\mathscr{C}$ reliant le centre aux sommets du pentagone, découpant
ainsi la figure en cinq triangles intérieurs :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-triangles-rayons.svg]]

Nous avons tenu compte du caractère isocèle des triangles intérieurs
dans la notation des angles.

Dans les triangles $P_1 P_2 O$ et $P_2 P_3 O$ on a :

$$ \abs{P_1 P_2} = \abs{P_2 P_3} $$

car le pentagone est régulier et :

$$ \abs{O P_1} = \abs{O P_2} = r $$

$$ \abs{O P_2} = \abs{O P_3} = r $$

par définition du cercle circonscrit. Ces triangles ont leurs trois
côtés de mêmes longueurs et sont donc isométriques. Un raisonnement
analogue nous montre que tous les triangles intérieurs du pentagone
sont isométriques. On a en particulier :

$$ \alpha_1 = \alpha_2 = \ldots = \alpha_5 $$

$$ \beta_1 = \beta_2 = \ldots = \beta_5 $$

Posons :

$$ \alpha = \alpha_1 $$

$$ \beta = \beta_1 $$

Les angles $\alpha_1$, $\alpha_2$, $\ldots$, $\alpha_5$ forment ensemble
un tour complet :

$$ \sum_{i=1}^6 \alpha_i = 5 \ \alpha = 2 \ \pi $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{2 \ \pi}{5} = 72^\circ $$

La somme des angles dans le triangle $P_1 P_2 O$ nous donne :

$$ \alpha + 2 \ \beta = 72^\circ + 2 \ \beta = 180^\circ $$

En isolant $\beta$, on obtient :

$$ \beta = \frac{180^\circ - 72^\circ}{2} = 54^\circ $$

Les triangles intérieurs ont donc les angles suivants :

$$ \alpha = 72^\circ
\qquad \qquad \qquad
\beta = 54^\circ $$

Les angles internes d’un pentagone valent :

$$ 2 \ \beta = 108^\circ $$

Le schéma devient donc :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-triangles-rayons-resolu.svg]]

On a aussi les angles internes :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-angles-internes.svg]]

* Diagonales

Le schéma ci-dessous représente un pentagone muni de toutes ses
diagonales formant un pentagramme, ainsi que les rayons du cercle
circonscrit  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

Examinons le triangle $ABE$. La somme des angles nous donne :

$$ 2 \ \alpha + 108^\circ = 180^\circ $$

On en déduit la valuer des deux autres angles :

$$ \alpha = \frac{180^\circ - 108^\circ}{2} = 36^\circ $$

L’angle compris entre un côté du pentagone et la plus proche de ses
diagonales vaut $36^\circ$.

* Pentagramme

Le schéma ci-dessous représente un pentagone muni de toutes ses
diagonales formant un pentagramme, ainsi que les rayons du cercle
circonscrit  :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

L’angle $\alpha$ forme, avec deux angles de $36^\circ$, un angle interne du
pentagone. On a donc :

$$ \alpha + 2 \cdot 36^\circ = 108^\circ $$

c’est-à-dire :

$$ \alpha = 108^\circ -  2 \cdot 36^\circ = 36^\circ $$

La somme des angles du triangle $AFG$ nous donne :

$$ \alpha + 2 \ \gamma = 36^\circ + 2 \ \gamma = 180^\circ $$

c’est-à-dire :

$$ \gamma = \frac{180^\circ - 36^\circ}{2} = 72^\circ $$

Examinons à présent le triangle $AFE$. On obtient directement la valeur
de l’angle $\theta$ par :

$$ \theta + 36^\circ + 36^\circ = 180^\circ $$

qui nous donne :

$$ \theta = 180^\circ - 36^\circ - 36^\circ = 108^\circ $$

** Conclusion

Les petits triangles formant les pointes du pentagramme ont un angle au
sommet de $36^\circ$ et deux autres angles de $72^\circ$.

Les triangles compris entre les côtés du pentagone et le pentagramme ont
un angle obtus de $108^\circ$ et deux angles aigus de $36^\circ$.

Le schéma devient :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme-resolu.svg]]

* Invariance sous rotation

Le schéma ci-dessous représente un pentagone muni de toutes ses
diagonales formant un pentagramme, ainsi que les rayons du cercle
circonscrit  :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-invariance-sous-rotation.svg]]

Nous avons déjà tenu compte de la symétrie dans la notation des
longueurs.

On définit les distances :

$$ a = \abs{BG} = \abs{FE} $$

$$ b = \abs{GH} = \abs{HF} $$

$$ c = \abs{AF} = \abs{ID} $$

$$ d = \abs{FJ} = \abs{JI} $$

Le pentagone régulier est invariant lorsqu’on le fait tourner
d’un cinquième de tour, c’est-à-dire de $72^\circ$. Les longueurs,
les proportions et les angles entre ses côtés et ses diagonales ne
varient donc pas non plus. En particulier, si on fait tourner le triangle
$BGA$ de $72^\circ$ dans le sens horlogique, on obtient le triangle $AFE$,
qui possède des propriétés identiques. Leurs côtés correspondants
sont donc égaux et :

$$ a = c $$

En utilisant le même raisonnement, si on fait tourner le triangle
$AFE$ de $72^\circ$ dans le sens horlogique, on obtient le triangle $EID$,
qui possède des propriétés identiques. Leurs côtés correspondants
sont donc égaux et :

$$ 2 \ b = 2 \ d $$

c’est-à-dire :

$$ b = d $$

On a aussi comme conséquences immédiates :

$$ \abs{AF} = c = a = \abs{FE} $$

et :

$$ \abs{BF} = a + 2 \ b = c + 2 \ d = \abs{FD} $$

* Nombre d’or

Le schéma ci-dessous représente un pentagone muni de toutes ses
diagonales formant un pentagramme, ainsi que les rayons du cercle
circonscrit  :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-nombre-d-or.svg]]

Nous avons tenu compte de la symétrie et de l’invariance sous rotation
d’un cinquième de tour dans la notation des longueurs.

Le cercle est de rayon $r$. La longueur du côté du pentagone se note :

$$ l = \abs{AB} = \abs{BC} = \abs{CD} = \abs{DE} = \abs{EA} $$

On définit aussi les distances :

$$ a = \abs{BF} = \abs{FD} $$

$$ c = \abs{AF} = \abs{FE} $$

** Triangle isocèle

Dans le triangle $AFB$, on a :

$$ \alpha + 72^\circ + 36^\circ = 180^\circ $$

d’où :

$$ \alpha = 72^\circ $$

Les deux angles aigus du triangle $AFB$ sont donc égaux. Par symétrie,
il s’agit donc d’un triangle isocèle et :

$$ a = l $$

** Triangles semblables

On remarque que les triangles $ADE$ et $AEF$ ont des angles correspondants
de même amplitude : ce sont donc des triangles semblables. Leurs rapports
de longueurs sont donc identiques. On a en particulier :

$$  \frac{l}{c} =\frac{a + c}{l} $$

Comme $a = l$, cette relation devient :

$$ \frac{l}{c} = \frac{l + c}{l} = \frac{l}{l} + \frac{c}{l} $$

ou :

$$ \frac{l}{c} = 1 + \frac{c}{l} $$

Posons :

$$ \phi = \frac{l}{c} $$

La relation entre les longueurs devient :

$$ \phi = 1 + \unsur{\phi} $$

Multiplions par $\phi$. On obtient :

$$ \phi^2 = \phi + 1 $$

ou encore :

$$ \phi^2 - \phi - 1 = 0 $$

Nous avons vu dans le chapitre sur les
[[file:proportions-geometriques.org][proportions géométriques]],
que la solution positive de cette équation définit le
[[file:proportions-geometriques.org::#heading:nombre_d_or][nombre d’or]] :

$$ \phi = \frac{1+\sqrt{5}}{2} $$

La longueur de la diagonale du pentagone vaut :

$$ d = a + c $$

On a donc :

$$ \frac{d}{l} = \frac{a + c}{l} = \frac{l}{c} = \phi $$

Le rapport entre la longueur de la diagonale d’un pentagone et la
longueur de son côté est égal au nombre d’or.

** Cosinus de $36^\circ$
:properties:
:custom_id: heading:cosinus_de_36
:end:

Dans le triangle $ABF$, la loi des cosinus nous donne une expression de
la longueur $c$  :

$$ c^2 = l^2 + c^2 - 2 \ l \ c \ \cos 36^\circ $$

Divisons par $c^2$ :

$$ 1 = \frac{l^2}{c^2} + 1 - 2 \ \frac{l}{c} \ \cos 36^\circ $$

Comme $l/c = \phi$, cette équation devient :

$$ 1 = \phi^2 + 1 - 2 \ \phi \ \cos 36^\circ $$

Isolons le cosinus :

$$ \cos 36^\circ = \frac{\phi^2 + 1 - 1}{2 \ \phi} = \frac{\phi^2}{2 \ \phi} $$

c’est-à-dire :

$$ \cos 36^\circ = \frac{\phi}{2} $$

Le cosinus de $36^\circ$ vaut la moitié du nombre d’or.

*** Sinus de $54^\circ$

Il en va de même pour le sinus de l’angle complémentaire, à savoir $54^\circ$ :

$$ \sin 54^\circ = \frac{\phi}{2} $$

* Rapport entre le côté et le rayon

Le schéma ci-dessous représente un pentagone régulier inscrit dans un
cercle de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-rapport-cote-rayon.svg]]

La longueur du côté du pentagone se note :

$$ l = \abs{AB} = \abs{BC} = \abs{CD} = \abs{DE} = \abs{EA} $$

On définit aussi les distances :

$$ a = \abs{AF} $$

$$ b = \abs{FB} $$

$$ c = \abs{OF} $$

** Symétrie

Le point $F$ est l’intersection entre le côté $[A,B]$ et le
prolongement du rayon $[O,D]$. Les points $F$, $O$ et $D$ sont donc
alignés. Par conséquent, l’angle $\alpha$ forme, avec deux angles
de $72^\circ$, un angle plat :

$$ \alpha + 2 \cdot 72^\circ = 180^\circ $$

Isolons $\alpha$ :

$$ \alpha = 180^\circ - 2 \cdot 72^\circ = 180^\circ - 144^\circ $$

Cet angle vaut donc :

$$ \alpha = 36^\circ $$

On peut tenir le même raisonnement pour l’angle $\gamma$ :

$$ \gamma = 36^\circ $$

On a donc :

$$ \alpha = \gamma $$

Par symétrie, on a aussi :

$$ a = b $$

$$ \delta = \epsilon $$

Comme :

$$ a + b = 2 \ a = l $$

on en déduit que :

$$ a = \frac{l}{2} $$

Les angles $\delta$ et $\epsilon$ mis ensemble forment également un
angle plat :

$$ 2 \ \delta = 180^\circ $$

c’est-à-dire :

$$ \delta = 90^\circ $$

Le triangle $AOF$ est donc un triangle rectangle.

** Pythagore

Appliquons le théorème de Pythagore au triangle rectangle $AOF$ :

$$ r^2 = a^2 + c^2 $$

Comme $a = l/2$, cette équation peut se réécrire :

$$ r^2 = \frac{l^2}{4} + c^2 $$

La longueur du côté $[O,F]$ peut s’exprimer en fonction du cosinus
de $36^\circ$ :

$$ c = r \ \cos 36^\circ $$

La relation de Pythagore devient alors :

$$ r^2 = \frac{l^2}{4} + r^2 \ (\cos 36^\circ)^2 $$

On peut remplacer le cosinus de $36^\circ$ par la moitié du nombre d’or :

$$ r^2 = \frac{l^2}{4} + r^2 \ \left(\frac{\phi}{2}\right)^2 = \frac{l^2}{4} + \frac{r^2 \ \phi^2}{4} $$

Isolons $l^2$ :

$$ l^2 = 4 \ r^2 - r^2 \ \phi^2 $$

et divisons par $r^2$ :

$$ \frac{l^2}{r^2} = 4 - \phi^2 $$

Comme $\phi^2 = \phi + 1$, cette équation devient :

$$ \frac{l^2}{r^2} = 4 - \phi - 1 = 3 - \phi $$

Il ne nous reste qu’à prendre la racine carrée :

$$ \frac{l}{r} = \sqrt{3 - \phi} $$

pour obtenir la valeur du rapport entre le côté d’un pentagone
régulier et le rayon de son cercle circonscrit.

