
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Pentagone rﾃｩgulier
#+AUTHOR: chimay
#+EMAIL: or du val chez gﾃｩ courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathﾃｩmatique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles formﾃｩs par les rayons

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace les rayons de
$\mathscr{C}$ reliant le centre aux sommets du pentagone, dﾃｩcoupant
ainsi la figure en cinq triangles intﾃｩrieurs :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-triangles-rayons.svg]]

Nous avons tenu compte du caractﾃｨre isocﾃｨle des triangles intﾃｩrieurs
dans la notation des angles.

Dans les triangles $P_1 P_2 O$ et $P_2 P_3 O$ on a :

$$ \abs{P_1 P_2} = \abs{P_2 P_3} $$

car le pentagone est rﾃｩgulier et :

$$ \abs{O P_1} = \abs{O P_2} = r $$

$$ \abs{O P_2} = \abs{O P_3} = r $$

par dﾃｩfinition du cercle circonscrit. Ces triangles ont leurs trois
cﾃｴtﾃｩs de mﾃｪmes longueurs et sont donc isomﾃｩtriques. Un raisonnement
analogue nous montre que tous les triangles intﾃｩrieurs du pentagone
sont isomﾃｩtriques. On a en particulier :

$$ \alpha_1 = \alpha_2 = \ldots = \alpha_5 $$

$$ \beta_1 = \beta_2 = \ldots = \beta_5 $$

Posons :

$$ \alpha = \alpha_1 $$

$$ \beta = \beta_1 $$

Les angles $\alpha_1$, $\alpha_2$, $\ldots$, $\alpha_5$ forment ensemble
un tour complet :

$$ \sum_{i=1}^6 \alpha_i = 5 \ \alpha = 2 \ \pi $$

En isolant $\alpha$, on obtient :

$$ \alpha = \frac{2 \ \pi}{5} = 72^\circ $$

La somme des angles dans le triangle $P_1 P_2 O$ nous donne :

$$ \alpha + 2 \ \beta = 72^\circ + 2 \ \beta = 180^\circ $$

En isolant $\beta$, on obtient :

$$ \beta = \frac{180^\circ - 72^\circ}{2} = 54^\circ $$

Les triangles intﾃｩrieurs ont donc les angles suivants :

$$ \alpha = 72^\circ
\qquad \qquad \qquad
\beta = 54^\circ $$

Les angles internes d窶冰n pentagone valent :

$$ 2 \ \beta = 108^\circ $$

Le schﾃｩma devient donc :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-triangles-rayons-resolu.svg]]

On a aussi les angles internes :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-angles-internes.svg]]

* Diagonales
:properties:
:custom_id: heading:diagonales
:end:

#+TOC: headlines 1 local

** Angle entre cﾃｴtﾃｩ et diagonale
:properties:
:custom_id: heading:angle_entre_cote_et_diagonale
:end:

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace la diagonale
$[P_2,P_5]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales.svg]]

Nous avons tenu compte du caractﾃｨre isocﾃｨle des triangles dans la
notation des angles.

On remarque que cette diagonale saute :

- le sommet $P_1$ au-dessus
- les sommet $P_3$ et $P_4$ en-dessous

En fait, toutes les diagonales d窶冰n pentagone sautent un ou deux sommets,
suivant le point de vue. Il n窶册xiste donc qu窶冰ne seule catﾃｩgorie
de diagonale pour le pentagone. Dans la suite, nous parlerons simplement
de diagonale.

Examinons le triangle $P_1 P_2 P_5$. La somme des angles nous donne :

$$ 2 \ \alpha + 108^\circ = 180^\circ $$

On en dﾃｩduit l窶兮mplitude de $\alpha$ :

$$ \alpha = \frac{180^\circ - 108^\circ}{2} = 36^\circ $$

L窶兮ngle compris entre une diagonale du pentagone et un cﾃｴtﾃｩ qui
relie une des extrﾃｩmitﾃｩs de la diagonale au sommet intermﾃｩdiaire
vaut $36^\circ$.

Notre schﾃｩma devient :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-resolu.svg]]

** Angle entre deux diagonales

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace deux diagonales
partant d窶冰n mﾃｪme sommet, disons $[P_1,P_3]$ et $[P_1,P_4]$ :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-angles.svg]]

L窶兮ngle $\alpha$ forme, avec ceux angles de $36^\circ$, un angle interne
de $108^\circ$ :

$$ \alpha + 2 \cdot 36^\circ = 108^\circ $$

On en dﾃｩduit que :

$$ \alpha = 108^\circ - 2 \cdot 36^\circ = 36^\circ $$

L窶兮ngle entre deux diagonales partant d窶冰n mﾃｪme sommet vaut
$36^\circ$.

Notre schﾃｩma devient :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-angles-resolu.svg]]

** Isomﾃｩtrie

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. On trace deux diagonales
quelconques, disons $[P_1,P_3]$ et $[P_1,P_4]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-diagonales-isometrie.svg]]

Les triangles $P_1 P_2 P_3$ et $P_1 P_5 P_4$ ont :

- deux cﾃｴtﾃｩs de mﾃｪme longueur $c$
- trois angles de mﾃｪmes amplitudes

Ces triangles sont donc isomﾃｩtriques et :

$$ d_1 = d_2 $$

Toutes les diagonales d窶冰n pentagone rﾃｩgulier ont la mﾃｪme longueur.

* Cerf-volant
:properties:
:custom_id: heading:cerf_volant
:end:

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Traﾃｧons le cerf-volant $O
P_5 P_1 P_2$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-cerf-volant.svg]]

Comme la diagonale $[O,P_1]$ traverse les deux triangles isocﾃｨles du
cerf-volant, elle est la mﾃｩdiatrice de l窶兮utre diagonale $[P_2,P_5]$.

Dans le triangle rectangle $O I P_2$, l窶兮ngle $\alpha$ est le
complﾃｩmentaire de $72^\circ$ :

$$ \alpha = 90^\circ - 72^\circ = 18^\circ $$

Dans le triangle rectangle $I O P_5$, l窶兮ngle $\beta$ est le
complﾃｩmentaire de $72^\circ$ :

$$ \beta = 90^\circ - 72^\circ = 18^\circ $$

On a donc :

$$ \alpha = \beta = 18^\circ $$

En conclusion :

- les rayons du cercle circonscrit passant par les sommets du pentagone
  sont les mﾃｩdiatrices des diagonales sautant un sommet.
- l窶兮ngle compris entre une diagonale du pentagone et le rayon du cercle
  circonscrit qui passe par une de des extrﾃｩmitﾃｩs vaut $18^\circ$.

Notre schﾃｩma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-cerf-volant-resolu.svg]]

* Pentagramme

#+TOC: headlines 1 local

** Introduction

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Si on trace toutes les
diagonales, on obtient une ﾃｩtoile ﾃ cinq branches. Cette figure est
appelﾃｩe un pentagramme :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme.svg]]

Nous avons tenu compte dans la notation :

- des angles opposﾃｩs par le sommet
- de l窶兮ngle de $36^\circ$ entre une diagonale du pentagone et un cﾃｴtﾃｩ
  qui relie une des extrﾃｩmitﾃｩs de la diagonale au sommet intermﾃｩdiaire
- de l窶兮ngle de $36^\circ$ entre deux diagonales qui partent du mﾃｪme sommet

Dans le triangle $P_1 S_1 P_2$, la somme des angles nous donne :

$$ \lambda + 36^\circ + 36^\circ = 180^\circ $$

d窶冩ﾃｹ :

$$ \lambda = 180^\circ - 2 \cdot 36^\circ = 108^\circ $$

Dans le triangle $P_1 S_5 P_5$, la somme des angles nous donne :

$$ \mu = 180^\circ - 2 \cdot 36^\circ = 108^\circ $$

Comme $\lambda$ et $\alpha$ forment ensemble un angle plat, on a :

$$ \alpha = 180^\circ - \lambda = 180^\circ - 108^\circ = 72^\circ $$

Comme $\mu$ et $\beta$ forment ensemble un angle plat, on a :

$$ \beta = 180^\circ - \mu = 180^\circ - 108^\circ = 72^\circ $$

Le triangle $P_1 S_1 S_5$ est isocﾃｨle car il a deux angles de mﾃｪme
amplitude.

Remarquons que le triangle $P_1 S_1 P_2$ est aussi un triangle isocﾃｨle
car il a ﾃｩgalement deux angles de mﾃｪme amplitude.

Un raisonnement similaire nous montre le mﾃｪme rﾃｩsultat pour les autres
pointes du pentagramme. On en conclut que :

- les triangles isocﾃｨles du type $P_1 S_1 S_5$ qui forment les pointes du pentagramme
  ont un angle au sommet de $36^\circ$ et deux autres angles de $72^\circ$.
- les triangles isocﾃｨles du type $P_1 S_1 P_2$ qui complﾃｨtent le pentagramme
  pour former le pentagone ont un angle obtus de $108^\circ$ et deux
  angles aigus de $36^\circ$

Les triangles qui constituent les pointes du pentagramme ont tous un
angle de mﾃｪme amplitude compris entre deux cﾃｴtﾃｩs de mﾃｪme longueur. Ces
triangles sont donc tous isomﾃｩtriques.

Notre schﾃｩma devient :

#+attr_html: :width 47%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme-resolu.svg]]

** Corollaire

Les triangles du type $P_1 S_1 P_2$ ont les mﾃｪmes angles
que l窶冩n retrouve dans les triangles du type $P_1 P_2
P_5$, que nous avons analysﾃｩ dans la section concernant
[[#heading:angle_entre_cote_et_diagonale][l窶兮ngle entre cﾃｴtﾃｩ et
diagonale]]. Ces deux catﾃｩgories de triangles sont donc semblables.

** Cerf-volants

#+TOC: headlines 1 local

*** Introduction

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$. Traﾃｧons le pentagramme et
examinons-en la partie supﾃｩrieure :

#+attr_html: :width 65%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme-cerf-volants.svg]]

Nous avons tenu compte des rﾃｩsultats prﾃｩcﾃｩdents dans la notation,
avec en particulier :

- les triangles isocﾃｨles formﾃｩs par le pentagone et le pentagramme
- l窶兮ngle de $18^\circ$ entre une diagonale du pentagone et le rayon
  qui passe par une de ses extrﾃｩmitﾃｩs
  + voir la section sur le [[#heading:cerf_volant][cerf-volant formﾃｩ
    par le pentagone et les rayons]]

On dﾃｩfinit :

$$ a
= \abs{P_1 S_1}
= \abs{P_1 S_5}
= \abs{P_2 S_1}
= \abs{P_5 S_5}
= \ldots
\qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \quad $$

$$ b_1 = \abs{S_1 I_1}
\qquad \qquad \qquad
c_1 = \abs{I_1 S_5}
\qquad \qquad \qquad
b_2 = \abs{S_2 I_2}
\qquad \qquad \qquad
c_2 = \abs{I_2 S_1} $$

$$ h_1 = \abs{P_1 I_1}
\qquad \qquad \qquad
h_2 = \abs{P_2 I_2}
\qquad \qquad \qquad
s_1 = \abs{O I_1}
\qquad \qquad \qquad
s_2 = \abs{O I_2} $$

$$ f_1 = \abs{O S_1}
\qquad \qquad \qquad
f_2 = \abs{O S_2}
\qquad \qquad \qquad \qquad \qquad
\qquad \qquad \qquad \qquad \qquad \qquad $$

*** Longueurs

- Le triangle $P_1 S_1 S_5$ ﾃｩtant isocﾃｨle en $P_1$, la hauteur $h_1$ qui
  part de $P_1$ est aussi la mﾃｩdiane du cﾃｴtﾃｩ opposﾃｩ :

$$ b_1 = c_1 $$

Idem dans le triangle $P_2 S_2 S_1$ :

$$ b_2 = c_2 $$

- Les triangles rectangles $P_1 S_1 I_1$ et $P_2 I_2 S_1$ ont un cﾃｴtﾃｩ $a$
  de mﾃｪme longueur et un angle de $18^\circ$. Ces triangles sont donc
  isometriques et :

$$ b_1 = c_2
\qquad \qquad \qquad
h_1 = h_2 $$

En compilant les derniers rﾃｩsultats, on obtient :

$$ b_2 = c_2 = b_1 = c_1 $$

- Les triangles rectangles $O I_2 S_1$ et $O I_2 S_2$ ont leurs
  deux cathﾃｨres de mﾃｪmes longueurs car $b_1 = c_2$. Ils sont donc
  isomﾃｩtriques et :

$$ f_1 = f_2 $$

Les quadrilatﾃｨres du type $P_2 S_2 O S_1$ sont des cerfs-volants.

- Comme :

$$ r = h_1 + s_1 $$

$$ r = h_2 + s_2 $$

On a :

$$ s_1 = r - h_1 $$

$$ s_2 = r - h_2 $$

On en dﾃｩduit que :

$$ s_1 = r - h_1 = r - h_2 = s_2 $$

Les quadrilatﾃｨres du type $O I_1 S_1 I_2$ sont des cerf-volants.

*** Angles

Dans le cerf-volant $O I_1 S_1 I_2$, la diagonale $[O,S_1]$ traverse les
deux triangles isocﾃｨles $O I_1 I_2$ et $S_1 I_1 I_2$ qui le composent.
Cette diagonale est donc la bissectrice de l窶兮ngle $\angleflex{I_1 O
I_2}$ :

$$ \alpha = \beta $$

Or, $\alpha$ et $\beta$ forment ensemble un angle de $72^\circ$, car situﾃｩ
entre deux rayons qui passent par des sommets consﾃｩcutifs du pentagone.
On en conclut que :

$$ 2 \ \alpha = 72^\circ $$

c窶册st-ﾃ-dire :

$$ \alpha = 36^\circ $$

*** Conclusion

Un raisonnement similaire peut ﾃｪtre appliquﾃｩ aux autres pointes et
cerf-volants du pentagramme. Notre schﾃｩma devient :

#+attr_html: :width 52%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-pentagramme-cerf-volants-resolu.svg]]

*** Corollaire

On a :

$$ \angleflex{P_1 O S_3} = 5 \cdot 36^\circ = 180^\circ $$

Les points $P_1$, $O$ et $S_3$ sont alignﾃｩs. Le centre $O$ se trouve
donc sur le segment $[P_1,S_3]$.

Ce rﾃｩsultat est aussi valable pour les autres segments du mﾃｪme type :

$$ \angleflex{P_2 O S_4}
= \angleflex{P_3 O S_5}
= \angleflex{P_4 O S_1}
= \angleflex{P_5 O S_2}
= 180^\circ $$

Le point $O$ est donc l窶冓ntersection de tous ces segments :

$$ \{ O \}
= [P_1,S_3]
\cap [P_2,S_4]
\cap [P_3,S_5]
\cap [P_4,S_1]
\cap [P_5,S_2] $$

Ce constat nous permet de retrouver le centre du cercle circonscrit
d窶冰n pentagone.

* Nombre d窶冩r

#+TOC: headlines 1 local

** Introduction

Soit un pentagone rﾃｩgulier $P_1 P_2 \ldots P_5$ inscrit dans un cercle
$\mathscr{C}$ de centre $O$ et de rayon $r$ :

#+attr_html: :width 47%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-nombre-d-or.svg]]

Nous avons tenu compte des rﾃｩsultats prﾃｩcﾃｩdents dans la notation,

On dﾃｩfinit :

$$ c = \abs{P_1 P_2} = \abs{P_1 P_5} = \ldots $$

$$ a = \abs{P_2 S_1} = \abs{P_5 S_5} = \ldots $$

$$ b = \abs{S_1 S_5} = \abs{S_4 S_5} = \ldots $$

ainsi que :

$$ d = \abs{P_2 P_5} $$

pour la longueur de la diagonale.

** Triangle isocﾃｨle

Dans le triangle $P_1 P_2 S_5$, on a :

$$ \abs{\angleflex{S_5}} = \abs{\angleflex{P_1 S_5 P_2}} = 72^\circ $$

et :

$$ \abs{\angleflex{P_1}}
= \abs{\angleflex{P_2 P_1 S_5}}
= 36^\circ + 36^\circ = 72^\circ $$

Le triangle $P_1 P_2 S_5$ est donc isocﾃｨle en $P_2$ et :

$$ \abs{P_1 P_2} = \abs{P_2 S_5} $$

c窶册st-ﾃ-dire :

$$ a + b = c $$

On a aussi :

$$ d = a + b + a = c + a $$

** Triangles semblables

On remarque que les triangles $ADE$ et $AEF$ ont des angles correspondants
de mﾃｪme amplitude : ce sont donc des triangles semblables. Leurs rapports
de longueurs sont donc identiques. On a en particulier :

$$  \frac{c}{a} = \frac{d}{c} $$

$$  \frac{c}{a} = \frac{c + a}{c} $$

$$ \frac{c}{a} = 1 + \frac{a}{c} $$

Posons :

$$ \phi = \frac{c}{a} $$

La relation entre les longueurs devient :

$$ \phi = 1 + \unsur{\phi} $$

Multiplions par $\phi$. On obtient :

$$ \phi^2 = \phi + 1 $$

ou encore :

$$ \phi^2 - \phi - 1 = 0 $$

Nous avons vu dans le chapitre sur les
[[file:proportions-geometriques.org][proportions gﾃｩomﾃｩtriques]],
que la solution positive de cette ﾃｩquation dﾃｩfinit le
[[file:proportions-geometriques.org::#heading:nombre_d_or][nombre d窶冩r]] :

$$ \phi = \frac{1+\sqrt{5}}{2} $$

On a finalement :

$$ \frac{d}{c} = \frac{c}{a} = \phi $$

Le rapport entre la longueur de la diagonale d窶冰n pentagone et la
longueur de son cﾃｴtﾃｩ est ﾃｩgal au nombre d窶冩r.

** Cosinus de $36^\circ$
:properties:
:custom_id: heading:cosinus_de_36
:end:

Dans le triangle $ABF$, la loi des cosinus nous donne une expression de
la longueur $c$  :

$$ c^2 = l^2 + c^2 - 2 \ l \ c \ \cos 36^\circ $$

Divisons par $c^2$ :

$$ 1 = \frac{l^2}{c^2} + 1 - 2 \ \frac{l}{c} \ \cos 36^\circ $$

Comme $l/c = \phi$, cette ﾃｩquation devient :

$$ 1 = \phi^2 + 1 - 2 \ \phi \ \cos 36^\circ $$

Isolons le cosinus :

$$ \cos 36^\circ = \frac{\phi^2 + 1 - 1}{2 \ \phi} = \frac{\phi^2}{2 \ \phi} $$

c窶册st-ﾃ-dire :

$$ \cos 36^\circ = \frac{\phi}{2} $$

Le cosinus de $36^\circ$ vaut la moitiﾃｩ du nombre d窶冩r.

*** Sinus de $54^\circ$

Il en va de mﾃｪme pour le sinus de l窶兮ngle complﾃｩmentaire, ﾃ savoir $54^\circ$ :

$$ \sin 54^\circ = \frac{\phi}{2} $$

* Rapport entre le cﾃｴtﾃｩ et le rayon

Le schﾃｩma ci-dessous reprﾃｩsente un pentagone rﾃｩgulier inscrit dans un
cercle de centre $O$ et de rayon $r$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pentagone-rapport-cote-rayon.svg]]

La longueur du cﾃｴtﾃｩ du pentagone se note :

$$ l = \abs{AB} = \abs{BC} = \abs{CD} = \abs{DE} = \abs{EA} $$

On dﾃｩfinit aussi les distances :

$$ a = \abs{AF} $$

$$ b = \abs{FB} $$

$$ c = \abs{OF} $$

** Symﾃｩtrie

Le point $F$ est l窶冓ntersection entre le cﾃｴtﾃｩ $[A,B]$ et le
prolongement du rayon $[O,D]$. Les points $F$, $O$ et $D$ sont donc
alignﾃｩs. Par consﾃｩquent, l窶兮ngle $\alpha$ forme, avec deux angles
de $72^\circ$, un angle plat :

$$ \alpha + 2 \cdot 72^\circ = 180^\circ $$

Isolons $\alpha$ :

$$ \alpha = 180^\circ - 2 \cdot 72^\circ = 180^\circ - 144^\circ $$

Cet angle vaut donc :

$$ \alpha = 36^\circ $$

On peut tenir le mﾃｪme raisonnement pour l窶兮ngle $\gamma$ :

$$ \gamma = 36^\circ $$

On a donc :

$$ \alpha = \gamma $$

Par symﾃｩtrie, on a aussi :

$$ a = b $$

$$ \delta = \epsilon $$

Comme :

$$ a + b = 2 \ a = l $$

on en dﾃｩduit que :

$$ a = \frac{l}{2} $$

Les angles $\delta$ et $\epsilon$ mis ensemble forment ﾃｩgalement un
angle plat :

$$ 2 \ \delta = 180^\circ $$

c窶册st-ﾃ-dire :

$$ \delta = 90^\circ $$

Le triangle $AOF$ est donc un triangle rectangle.

** Pythagore

Appliquons le thﾃｩorﾃｨme de Pythagore au triangle rectangle $AOF$ :

$$ r^2 = a^2 + c^2 $$

Comme $a = l/2$, cette ﾃｩquation peut se rﾃｩﾃｩcrire :

$$ r^2 = \frac{l^2}{4} + c^2 $$

La longueur du cﾃｴtﾃｩ $[O,F]$ peut s窶册xprimer en fonction du cosinus
de $36^\circ$ :

$$ c = r \ \cos 36^\circ $$

La relation de Pythagore devient alors :

$$ r^2 = \frac{l^2}{4} + r^2 \ (\cos 36^\circ)^2 $$

On peut remplacer le cosinus de $36^\circ$ par la moitiﾃｩ du nombre d窶冩r :

$$ r^2 = \frac{l^2}{4} + r^2 \ \left(\frac{\phi}{2}\right)^2 = \frac{l^2}{4} + \frac{r^2 \ \phi^2}{4} $$

Isolons $l^2$ :

$$ l^2 = 4 \ r^2 - r^2 \ \phi^2 $$

et divisons par $r^2$ :

$$ \frac{l^2}{r^2} = 4 - \phi^2 $$

Comme $\phi^2 = \phi + 1$, cette ﾃｩquation devient :

$$ \frac{l^2}{r^2} = 4 - \phi - 1 = 3 - \phi $$

Il ne nous reste qu窶凖 prendre la racine carrﾃｩe :

$$ \frac{l}{r} = \sqrt{3 - \phi} $$

pour obtenir la valeur du rapport entre le cﾃｴtﾃｩ d窶冰n pentagone
rﾃｩgulier et le rayon de son cercle circonscrit.

* Invariance sous rotation

Le pentagone rﾃｩgulier est invariant lorsqu窶冩n le fait tourner d窶冰n
cinquiﾃｨme de tour, c窶册st-ﾃ-dire de $72^\circ$. Les longueurs,
les proportions et les angles entre ses cﾃｴtﾃｩs et les lignes qui en
dﾃｩcoulent :

- diagonales
- pentagramme

ne varient donc pas non plus.
