
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Perpendicularité
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Perpendiculaire à une droite passant par un point

#+TOC: headlines 1 local

** Existence

Soit un point $A$ et une droite $d$. Traçons la construction géométrique
ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-existence.svg]]

Voici les étapes de cette construction :

1. ouvrir le compas d’un rayon $r$ suffisamment grand pour qu’un cercle
   de centre $A$ et de rayon $r$ possède deux intersection avec $d$
2. tracer l’arc de cercle $\mathscr{C}$ de centre $A$ et de rayon $r$
3. on note $E$ et $F$ les deux points d’intersections de
   la droite $d$ avec l’arc de cercle $\mathscr{C}$
4. on trace $P$ le point milieu du segment $[E,F]$
5. on trace la droite $p = (AP)$

On remarque ensuite que les triangles $APE$ et $APF$ possèdent trois
côtés de longueurs identiques :

- le côté commun $[A,P]$
- les côtés $[A,E]$ et $[A,F]$ sont tous deux de longueur $r$ par
  construction de l’arc de cercle $\mathscr{C}$
- les côtés $[E,P]$ et $[P,F]$ sont de même longueur par construction
  du point $P$

Par conséquent, les triangles $APE$ et $APF$ sont isométriques et
leurs angles correspondants sont de même amplitude :

$$ \alpha = \beta $$

Comme ces deux angles forment ensemble un angle plat :

$$ \alpha + \beta = 180^\circ $$

On a :

$$ 2 \ \alpha = 180^\circ $$

et finalement :

$$ \alpha = \beta = 90^\circ $$

La droite $p$ est donc perpendiculaire à $d$ et passe par $A$. Ce
résultat nous montre l’existence d’une telle droite.

** Unicité

Soit un point $A$ et une droite $d$. Nous avons établi qu’il existe au
moins une droite perpendiculaire à $d$ et passant par $A$. Cette droite
est-elle unique ? Supposons un instant qu’il y ait au moins deux de
ces perpendiculaires qui passent par le point $A$, disons $f$ et $g$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-unicite.svg]]

On a les intersections distinctes :

$$ f \cap d = \{ B \} $$

$$ g \cap d = \{ C \} $$

Les droites $f$ et $g$ ne sont donc pas confondues. Comme $f$ et $g$ sont
perpendiculaires à $d$, les angles $\angleflex{CBA}$ et $\angleflex{ACB}$
sont des angles droits. Leur somme vaut :

$$ \abs{\angleflex{CBA}} + \abs{\angleflex{ACB}} = 180^\circ $$

La somme des deux angles internes à $f$ et $g$ et situés du même côté de
$d$ vaut 180°. La réciproque du cinquième axiome d’Euclide nous garantit
alors que $f$ et $g$ sont parallèles. Comme ces droites ne sont pas
confondues, on doit avoir :

$$ f \cap g = \emptyset $$

Mais le point $A$ appartient aux deux droites, ce qui implique :

$$ A \in f \cap g $$

Cette intersection n’est donc pas vide :

$$ f \cap g \ne \emptyset $$

On a donc finalement :

$$ \emptyset = f \cap g \ne \emptyset $$

ce qui est manifestement une absurdité. On en conclut que notre hypothèse
est invalide. Il existe donc au maximum une seule droite perpendiculaire
à $d$ et passant par $A$.

** Conclusion

Étant donné un point $A$ et une droite $d$, il existe une et une seule
droite $p$ passant par $A$ et perpendiculaire à $d$.

* Projection orthogonale

#+TOC: headlines 1 local

** Définition

Soit un point $A$ et une droite $d$. Nous avons montré qu’il existe
une et une seule droite $p$, perpendiculaire à la droite $d$ et passant
par le point $A$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/projection-orthogonale.svg]]

Il existe donc un et un seul point d’intersection $P$ entre $d$ et $p$ :

$$ d \cap p = \{ P \} $$

Le point $P$ est appelé la projection orthogonale de $A$ sur $d$. On
la note :

$$ P = \projection(A,d) $$

** Demi-droite

Soit une demi-droite $f$ et :

- $d$ la droite qui prolonge la demi-droite $f$
- $P$ la projection orthogonale du point $A$ sur $d$

Si $P \in f$, on a le schéma suivant :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/projection-orthogonale-demi-droite.svg]]

On dit alors que $P$ est la projection orthogonale de $A$ sur la
demi-droite $f$ :

$$ P = \projection(A,f) $$

*** Angle

Soit $\alpha$ l’angle formé par les demi-droites $[OP)$ et $[OA)$

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/projection-orthogonale-demi-droite-angle-dedans.svg]]

Si $P \in f$, deux cas peuvent se présenter. Si $O \ne P$, $\alpha$
est un angle du triangle rectangle $OPA$ et doit être aigu :

$$ \abs{\alpha} < 90^\circ $$

ce qui nous donne l’intervalle :

$$ -90^\circ < \alpha < 90^\circ $$

Dans le cas où $O = P$, on a :

$$ (OA) = (PA) \perp d = (OP) $$

car $P$ est la projection orthogonale de $A$ sur $d$. On en conclut que :

$$ \abs{\alpha} = 90^\circ $$

par définition de $\alpha$. Dans les deux cas, on doit avoir :

$$ -90^\circ \le \alpha \le 90^\circ $$

Réciproquement, supposons que $\alpha \in [-90^\circ, 90^\circ]$. Si
$\abs{\alpha} = 90^\circ$, on a :

$$ (OA) \perp (OP) = d $$

Les points $P \in (AP)$ et $O \in (OA)$ sont tous deux à l’intersection
de $d$ et d’une droite passant par $A$ et perpendiculaire à $d$, ce
qui en fait des projections orthogonales de $A$ sur $d$. Par unicité
de cette projection, on a :

$$ P = O \in f $$

Si $\abs{\alpha} < 90^\circ$, TODO

La condition $P \in f$ est équivalente à la double condition suivante
sur l’angle $\alpha$ :

$$ -90^\circ \le \alpha \le 90^\circ $$

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/projection-orthogonale-demi-droite-angle-dehors.svg]]

* Minimum
:properties:
:custom_id: heading:minimum
:end:

Soit un point $A$, une droite $d$ et la droite $p$, perpendiculaire à
$d$ et passant par $A$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-preuve-minimum.svg]]

On note $P$ la projection orthogonale de $A$ sur $d$ :

$$ P = \projection(A,d) $$

On trace le point $B$, situé sur $p$ et à une distance :

$$ \abs{PB} = \abs{AP} $$

du point $P$. L’inégalité triangulaire des distances nous donne :

$$ \abs{AB} \le \abs{AC} + \abs{CB} $$

Or :

$$ \abs{AB} = \abs{AP} + \abs{PB} = 2 \ \abs{AP} $$

Les triangles rectangles $APC$ et $BPC$ ont  :

- une cathète commune $[P,C]$
- leurs autres cathètes $[A,P]$ et $[B,P]$ de même longueur,
  par construction du point $B$

Ce sont donc des triangles isométriques et :

$$ \abs{AC} = \abs{CB} $$

En tenant compte de tous ces résultats, l’inégalité triangulaire
devient :

$$ 2 \ \abs{AP} \le 2 \ \abs{AC} $$

c’est-à-dire :

$$ \abs{AP} \le \abs{AC} $$

Lorsque $C$ est distinct de $P$, les points $A$, $B$ et $C$ ne sont pas
alignés, et on a l’inégalité stricte :

$$ \abs{AP} < \abs{AC} $$

L’égalité n’est donc atteinte que dans le cas particulier où $C =
P$. Parmi tous les points $C$ de la droite $d$, la projection orthogonale
$P$ est l’unique point qui minimise la distance avec $A$ :

$$ \abs{AP} = \min_{C \in d} \abs{AC} $$

On a donc :

$$ P = \arg\min_{C \in d} \abs{AC} $$

ou encore :

$$ \projection(A,d) = \arg\min_{C \in d} \abs{AC} $$

*Remarque* : cette démonstration utilise les propriétés du triangle
isocèle $ABC$.

* Distance entre un point et une droite

La distance entre un point $A$ et une droite $d$ se définit comme étant
la longueur minimale entre $A$ et tous les points de $d$ :

$$ \distance(A,d) = \min_{X \in d} \abs{AX} $$

Soit le point $P$, projection orthogonale de $A$ sur $d$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-un-point-et-une-droite.svg]]

Comme la projection orthogonale minimise la distance entre $A$ et $d$,
on a :

$$ \abs{AP} = \min_{X \in d} \abs{AX} $$

On en conclut que :

$$ \distance(A,d) = \abs{AP} $$

La distance entre un point et une droite est égale à la distance entre
ce point et sa projection orthogonale sur la droite.

* Distance entre un point et une demi-droite

#+TOC: headlines 1 local

** Introduction

La distance entre un point $A$ et une demi-droite $f$ se définit comme
étant la distance minimale entre $A$ et tous les points de $f$ :

$$ \distance(A,f) = \min_{X \in f} \abs{AX} $$

** Projection orthogonale dans la demi-droite

Soit :

- $d$ la droite qui prolonge la demi-droite $f$
- $P$ la projection orthogonale du point $A$ sur $d$, avec $P \in f$

Le schéma ci-dessous représente tous ces éléments :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-un-point-et-une-demi-droite-dedans.svg]]

La demi-droite $f$ étant inclue dans $d$, les propriétés du minimum
nous donnent :

$$ \min_{X \in f} \abs{AX} \ge \min_{X \in d} \abs{AX} $$

Mais comme :

$$ \abs{AP} = \min_{X \in d} \abs{AX} $$

cette équation devient :

$$ \min_{X \in f} \abs{AX} \ge \abs{AP} $$

Comme le point $P$ est dans $f$, on a aussi :

$$ \min_{X \in f} \abs{AX} \le \abs{AP} $$

par définition du minimum. Ces deux dernières inégalités nous montrent
que :

$$ \min_{X \in f} \abs{AX} = \abs{AP} $$

c’est-à-dire :

$$ \distance(A,f) = \abs{AP} $$

On a donc la même propriété que pour la distance entre un point et
une droite.

** Projection orthogonale en dehors de la demi-droite

Soit :

- $d$ la droite qui prolonge la demi-droite $f$
- $P$ la projection orthogonale du point $A$ sur $d$, avec $P \notin f$

Le schéma ci-dessous représente tous ces éléments :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-un-point-et-une-demi-droite-dehors.svg]]

* Distance entre deux droites parallèles

#+TOC: headlines 1 local

** Définition

Soit deux droites $d$ et $f$, distinctes et parallèles. Choisissons
deux points $A$ et $B$ sur la droite $d$, et traçons :

- la droite $g$, perpendiculaire à $f$ et passant par $A$
- la droite $h$, perpendiculaire à $f$ et passant par $B$
- le point $C$, intersection de $g$ et $f$ et projection orthogonale de $A$ sur $f$
- le point $D$, intersection de $h$ et $f$ et projection orthogonale de $B$ sur $f$

Le schéma ci-dessous illustre cette construction géométrique :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-deux-droites-paralleles.svg]]

Comme $d$ et $f$ sont parallèles, $g$ et $h$ sont également
perpendiculaires à $d$, comme indiqué dans le schéma.

Nous avons aussi tenu compte, dans la notation des angles, du parallélisme
de $d$ et $f$, qui implique une égalité des angles alternes-internes.

Les triangles rectangles $ACD$ et $ADB$ ont un angle $\alpha$ de même
amplitude et une hypothénuse $[A,D]$ commune. Ce sont donc des triangles
isométriques et :

$$ \abs{AC} = \abs{BD} $$

La distance entre un point de $d$ et la projection orthogonale de ce
point sur $f$ ne dépend pas du point de $d$ choisi.

La distance entre deux droites parallèles peut donc être définie
comme la distance entre un point quelconque de la première droite et
sa projection orthogonale sur la seconde droite :

$$ \distance(d,f) = \abs{AC} $$

Pour tout point $A \in d$, cette distance est donc minimale parmi tous
les points de $f$ :

$$ \distance(d,f) =  \min_{X \in f} \abs{AX} $$

** Distance entre deux segments

La distance entre deux segments parallèles $[A,B]$ et $[C,D]$ est tout
simplement défini comme étant égal à la distance entre les droites
$(AB)$ et $(CD)$ qui les prolongent.

* Tangente à un cercle

#+TOC: headlines 1 local

** Droite perpendiculaire au rayon

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$, un point
$A \in \mathscr{C}$ et une droite $d$, perpendiculaire au rayon $[O,A]$
et passant par $A$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-perpendiculaire-tangente.svg]]

Le rayon $[O,A]$ est perpendiculaire à $d$ et passe par $O$. Le point
$A$ est donc la projection orthogonale de $O$ sur $d$. Par conséquent,
$A$ est l’unique point qui minimise la distance avec $O$ parmi tous
les points $B \in d$ :

$$ \abs{OA} = \min_{B \in d} \abs{OB} $$

On a donc :

$$ \abs{OB} \ge \abs{OA} = r $$

pour tout point $B$ appartenant à la droite $d$. Lorsque $B$ est distinct
de $A$, cette inégalité est stricte par unicité du minimum :

$$ \abs{OB} > \abs{OA} = r $$

Tous les points $B \in d$ distincts de $A$ sont donc situés en dehors du
cercle $\mathscr{C}$. Le point $A$ est donc l’unique point
d’intersection entre $d$ et $\mathscr{C}$ :

$$ d \cap \mathscr{C} = \{ A \} $$

Par définition, la droite $d$ est tangente au cercle $\mathscr{C}$
au point $A$.

Pour construire une tangente à un cercle, il suffit de tracer une
perpendiculaire à un rayon du cercle.

** Tangente

Soit un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$, un point
$A \in \mathscr{C}$ et une droite $t$ tangente au cercle $\mathscr{C}$
au point $A$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-tangente-perpendiculaire.svg]]

Par définition du cercle, le point $A$ est à une distance $r$ du centre
$O$ :

$$ \abs{OA} = r $$

Supposons qu’il existe un autre point $E \in t$ qui soit sur le cercle :

$$ \abs{OE} = r $$

Ces deux points appartiendraient alors simultanément à la droite $t$
et au cercle :

$$ \{ A, E \} \subseteq t \cap \mathscr{C} $$

Il y aurait donc au moins deux points d’intersection entre $t$ et le
cercle $\mathscr{C}$, et la droite $t$ ne pourrait pas être une tangente
au cercle, ce qui contredit l’hypothèse. Supposons à présent qu’il
existe un point $H \in t$ qui soit strictement à l’intérieur du
cercle :

$$ \abs{OH} < r $$

La seule solution pour que cette situation se produise est que la droite
$t$ rentre dans le cercle au point $A$ et en ressorte à une autre point
$I \in t$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-tangente-corde.svg]]

Il y aurait alors deux points d’intersection entre $t$ et le cercle
$\mathscr{C}$ :

$$ t \cap \mathscr{C} = \{ A, I \} $$

La droite $t$ ne pourrait donc pas être une tangente au cercle, ce qui
contredit l’hypothèse.

Par conséquent, le caractère de tangente de $t$ en $A$ implique que
tous les points $B \in t$ distincts de $A$ doivent se situer strictement
en dehors du cercle. On a donc l’inégalité stricte :

$$ \abs{OB} > r = \abs{OA} $$

Le point $A \in t$ minimise donc la distance avec le centre $O$ sur la
droite $t$ :

$$ \abs{OA} = \min_{B \in t} \abs{OB} $$

Par unicité du minimum, $A$ est la projection orthogonale de $O$
sur la droite $t$, ce qui implique que le rayon $[O,A]$ doit être
perpendiculaire à $t$ :

$$ [O,A] \perp t $$

Il existe une et une seule tangente au cercle $\mathscr{C}(O,r)$ au
point $A$ : la droite $t$, qui passe par $A$ et est perpendiculaire au
rayon $[O,A]$.

