
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Perpendicularité
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Perpendiculaire à une droite passant par un point

#+TOC: headlines 1 local

** Existence

Soit un point $P$ et une droite $d$. Traçons la construction géométrique
ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-existence.svg]]

Voici les étapes de cette construction :

1. ouvrir le compas d’un rayon $r$ suffisamment grand pour qu’un cercle
   de centre $P$ et de rayon $r$ possède deux intersection avec $d$
2. tracer l’arc de cercle $\mathscr{C}$ de centre $P$ et de rayon $r$
3. on note $A$ et $B$ les deux points d’intersections de
   la droite $d$ avec l’arc de cercle $\mathscr{C}$
4. on trace $F$ le point milieu du segment $[A,B]$
5. on trace la droite $p = (PF)$

On remarque ensuite que les triangles $AFP$ et $FBP$ possèdent trois
côtés de longueurs identiques :

- le côté commun $PF$
- les côtés $[P,A]$ et $[P,B]$ sont tous deux de longueur $r$ par
  construction de l’arc de cercle $\mathscr{C}$
- les côtés $[A,F]$ et $[F,B]$ sont de même longueur par construction
  du point $F$

Par conséquent, les triangles $AFP$ et $FBP$ sont isométriques et
leurs angles correspondants sont de même amplitude :

$$ \alpha = \beta $$

Comme ces deux angles forment ensemble un angle plat :

$$ \alpha + \beta = 180^\circ $$

On a :

$$ 2 \ \alpha = 180^\circ $$

et finalement :

$$ \alpha = \beta = 90^\circ $$

La droite $p$ est donc perpendiculaire à $d$ et passe par $P$. Ce
résultat nous montre l’existence d’une telle droite.

** Unicité

Soit un point $P$ et une droite $d$. Nous avons établi qu’il existe au
moins une droite perpendiculaire à $d$ et passant par $P$. Cette droite
est-elle unique ? Supposons un instant qu’il y ait au moins deux de
ces perpendiculaires qui passent par le point $P$, disons $f$ et $g$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-unicite.svg]]

On a les intersections distinctes :

$$ f \cap d = \{ A \} $$

$$ g \cap d = \{ B \} $$

Les droites $f$ et $g$ ne sont donc pas confondues. Comme $f$ et $g$ sont
perpendiculaires à $d$, les angles $\angleflex{CBP}$ et $\angleflex{PCB}$
sont des angles droits. Leur somme vaut :

$$ \abs{\angleflex{CBP}} + \abs{\angleflex{PCB}} = 180^\circ $$

La somme des deux angles internes à $f$ et $g$ et situés du même côté de
$d$ vaut 180°. La réciproque du cinquième axiome d’Euclide nous garantit
alors que $f$ et $g$ sont parallèles. Comme ces droites ne sont pas
confondues, on doit avoir :

$$ f \cap g = \emptyset $$

Mais le point $P$ appartient aux deux droites, ce qui implique :

$$ P \in f \cap g $$

Cette intersection n’est donc pas vide :

$$ f \cap g \ne \emptyset $$

On a donc finalement :

$$ \emptyset = f \cap g \ne \emptyset $$

ce qui est manifestement une absurdité. On en conclut que notre hypothèse
est invalide. Il existe donc au maximum une seule droite perpendiculaire
à $d$ et passant par $P$.

** Conclusion

Soit un point $P$ et une droite $d$. Nous avons montré qu’il existe
une et une seule droite $p$, perpendiculaire à la droite $d$ et passant
par le point $P$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-conclusion.svg]]

* Distance entre deux droites parallèles

#+TOC: headlines 1 local

** Définition

Soit deux droites distinctes parallèles $a$ et $b$. Traçons deux autres
droites distinctes $c$ et $d$, toutes deux perpendiculaires à $a$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-deux-droites-paralleles.svg]]

Comme $a$ et $b$ sont parallèles, $c$ et $d$ sont également
perpendiculaires à $b$, comme indiqué dans le schéma.

Nous avons aussi tenu compte dans la notation des angles du parallélisme
de $a$ et $b$, qui implique une égalité des angles alternes-internes.

Les triangles rectangles $ACD$ et $ADB$ ont un angle $\alpha$ de même
amplitude et une hypothénuse $[A,D]$ commune. Ce sont donc des triangles
isométriques et :

$$ \abs{AC} = \abs{BD} $$

La longueur d’un segment :

- perpendiculaire à deux droites parallèles
- délimité par les points d’intersections avec ces droites

ne dépend pas du point choisi sur une des droites pour construire ce
segment. On peut donc définir la distance entre deux droites comme étant
la longueur d’un segment qui les relie et leur est perpendiculaire :

$$ \distance(a,b) = \abs{AC} $$

** Corollaire

La distance entre deux droites parallèles est une constante.

** Distance entre deux segments

La distance entre deux segments parallèles $[A,B]$ et $[C,D]$ est tout
simplement défini comme étant égal à la distance entre les droites
$(AB)$ et $(CD)$ qui les prolongent.
* Distance entre un point et une droite

#+TOC: headlines 1 local

** Définition

La distance entre deux droites parallèles est la longueur d’un segment
qui les relie et leur est perpendiculaire.

Nous nous inspirons de ce résultat pour définir la distance entre un
point $A$ et une droite $d$ comme étant la longueur d’un segment :

- qui relie le point $A$ à la droite $d$
- qui est perpendiculaire à la droite $d$

Dans le schéma ci-dessous, la distance entre le point $A$ et la droite
$d$ est la longueur du segment $[A,B]$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-un-point-et-une-droite.svg]]

On a donc :

$$ \distance(A,d) = \abs{AB} $$

Il n’y a qu’un seul point $B$ qui vérifie :

$$ [A,B] \perp d $$

Contrairement à la distance entre deux droites, il n’y a qu’un seul
segment qui permet de mesurer la distance entre un point et une droite.

** Propriétés extrémales
:properties:
:custom_id: heading:proprietes_extremales_de_la_distance_entre_un_point_et_une_droite
:end:

* Triangle isocèle

#+TOC: headlines 1 local

** Hauteur

Le schéma ci-dessous représente un triangle isocèle et la hauteur
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

On voit que les triangles rectangles $ADC$ et $BCD$ ont une cathète $h$
et leur hypothénuse de mêmes longueurs. Ils sont donc isométriques et :

$$ \abs{AD} = \abs{DB} $$

La hauteur $h$ est donc aussi une médiane du triangle $ABC$. On a aussi :

$$ \alpha = \beta $$

Les angles adjacents au côté $[A,B]$ sont égaux. L’égalité du
dernier angle :

$$ \lambda = \mu $$

signifie que la hauteur $h$ est aussi la bissectrice de l’angle
$\angleflex{ACB}$.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur-resolu.svg]]

En résumé :

- les deux angles adjacents au côté $[A,B]$ sont égaux
  + $[A,B]$ est le côté qui reste lorsqu’on retire
    les côtés de longueur égale du triangle isocèle
- la hauteur $h$ est aussi une médiane du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

** Médiane

Le schéma ci-dessous représente un triangle isocèle et la médiane
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

Par définition de la médiane, on a :

$$ b = \abs{AD} = \abs{DB} $$

On voit que les triangles $ADC$ et $BCD$ ont leurs trois côtés de mêmes
longueurs. Ils sont donc isométriques, ce qui signifie que leurs angles
sont de mêmes amplitudes. On a en particulier :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

$$ \lambda = \mu $$

Cette dernière relation signifie que la médiane $m$ est aussi la
bissectrice de l’angle $\angleflex{ACB}$.

Comme les points $A$, $D$ et $C$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat, il vient :

$$ \gamma + \delta = 2 \ \gamma = 180^\circ $$

d’où :

$$ \gamma = 90^\circ $$

La médiane $m$ est donc aussi une hauteur du triangle $ABC$.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane-resolu.svg]]

** Bissectrice

Le schéma ci-dessous représente un triangle isocèle et la bissectrice
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

On voit que les triangles $ADC$ et $BCD$ ont un angle de même amplitude
$\lambda$ situé entre deux côtés de mêmes longueurs :

- la bissectrice $b$, côté commun
- les côtés $\abs{AC}$ et $\abs{BC}$

Ils sont donc isométriques et :

$$ \abs{AD} = \abs{DB} $$

La bissectrice $b$ est donc aussi une médiane du triangle $ABC$. On a
aussi :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Comme les points $A$, $D$ et $C$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat, il vient :

$$ \gamma + \delta = 2 \ \gamma = 180^\circ $$

d’où :

$$ \gamma = 90^\circ $$

La bissectrice $b$ est donc aussi une hauteur du triangle $ABC$. Notre
schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice-resolu.svg]]

*Conclusion* : les trois sections qui précèdent nous montre que la
hauteur, la médiatrice et la bissectrice qui partent du sommet situé
entre les côtés égaux d’un triangle isocèle se confondent.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède deux
angles de même amplitude sur deux de ses sommets, et la hauteur $h$
qui part du troisième sommet $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles.svg]]

Les triangles rectangles $ADC$ et $BCD$ ont une cathète $h$ commune,
et un angle non adjacent d’amplitude égale. Ces deux triangles sont
donc isométriques. On a en particulier :

$$ \abs{AC} = \abs{BC} $$

$$ \abs{AD} = \abs{DB} $$

$$ \lambda = \mu $$

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles-resolu.svg]]

On voit que :

- le triangle $ABC$ est isocèle
- la hauteur $h$ est aussi une médiane du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

Un triangle qui a deux angles de même amplitude est donc un triangle isocèle.

* Triangle équilatéral

#+TOC: headlines 1 local

** Angles

Le schéma ci-dessous représente un triangle équilatéral $ABC$ avec
ses trois angles :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-angles.svg]]

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[B,C]$ :

$$ \abs{AC} = \abs{BC} $$

les angles associés doivent être égaux :

$$ \alpha = \beta $$

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[A,B]$ :

$$ \abs{AC} = \abs{AB} $$

les angles associés doivent être égaux :

$$ \alpha = \gamma $$

Les trois angles sont donc identiques :

$$ \alpha = \beta = \gamma $$

La somme des angles de ce triangle nous donne :

$$ \alpha + \beta + \gamma = 3 \ \alpha = 180^\circ $$

On a donc :

$$ \alpha = \beta = \gamma = \frac{180^\circ}{3} = 60^\circ $$

Les angles d’un triangle équilatéral ont tous une amplitude de 60°.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède trois
angles égaux :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-condition-angles.svg]]

Comme les angles $\angleflex{A}$ et $\angleflex{B}$ sont égaux (ils
valent tous deux $\alpha$), ce triangle est isocèle en $[A,C]$ et
$[B,C]$ :

$$ \abs{AC} = \abs{BC} $$

Comme les angles $\angleflex{A}$ et $\angleflex{C}$ sont égaux, ce
triangle est isocèle en $[A,B]$ et $[C,B]$ :

$$ \abs{AB} = \abs{CB} $$

Les trois côtés sont donc de longueur égale.

Un triangle qui possède trois angles égaux est un triangle équilatéral.

