
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Perpendicularité
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Perpendiculaire à une droite passant par un point

#+TOC: headlines 1 local

** Existence

Soit un point $A$ et une droite $d$. Traçons la construction géométrique
ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-existence.svg]]

Voici les étapes de cette construction :

1. ouvrir le compas d’un rayon $r$ suffisamment grand pour qu’un cercle
   de centre $A$ et de rayon $r$ possède deux intersection avec $d$
2. tracer l’arc de cercle $\mathscr{C}$ de centre $A$ et de rayon $r$
3. on note $B$ et $D$ les deux points d’intersections de
   la droite $d$ avec l’arc de cercle $\mathscr{C}$
4. on trace $E$ le point milieu du segment $[B,D]$
5. on trace la droite $p = (AE)$

On remarque ensuite que les triangles $ABE$ et $AED$ possèdent trois
côtés de longueurs identiques :

- le côté commun $[A,E]$
- les côtés $[A,B]$ et $[A,D]$ sont tous deux de longueur $r$ par
  construction de l’arc de cercle $\mathscr{C}$
- les côtés $[B,E]$ et $[E,D]$ sont de même longueur par construction
  du point $E$

Par conséquent, les triangles $ABE$ et $AED$ sont isométriques et
leurs angles correspondants sont de même amplitude :

$$ \alpha = \beta $$

Comme ces deux angles forment ensemble un angle plat :

$$ \alpha + \beta = 180^\circ $$

On a :

$$ 2 \ \alpha = 180^\circ $$

et finalement :

$$ \alpha = \beta = 90^\circ $$

La droite $p$ est donc perpendiculaire à $d$ et passe par $A$. Ce
résultat nous montre l’existence d’une telle droite.

** Unicité

Soit un point $A$ et une droite $d$. Nous avons établi qu’il existe au
moins une droite perpendiculaire à $d$ et passant par $A$. Cette droite
est-elle unique ? Supposons un instant qu’il y ait au moins deux de
ces perpendiculaires qui passent par le point $A$, disons $f$ et $g$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-unicite.svg]]

On a les intersections distinctes :

$$ f \cap d = \{ B \} $$

$$ g \cap d = \{ C \} $$

Les droites $f$ et $g$ ne sont donc pas confondues. Comme $f$ et $g$ sont
perpendiculaires à $d$, les angles $\angleflex{CBA}$ et $\angleflex{ACB}$
sont des angles droits. Leur somme vaut :

$$ \abs{\angleflex{CBA}} + \abs{\angleflex{ACB}} = 180^\circ $$

La somme des deux angles internes à $f$ et $g$ et situés du même côté de
$d$ vaut 180°. La réciproque du cinquième axiome d’Euclide nous garantit
alors que $f$ et $g$ sont parallèles. Comme ces droites ne sont pas
confondues, on doit avoir :

$$ f \cap g = \emptyset $$

Mais le point $A$ appartient aux deux droites, ce qui implique :

$$ A \in f \cap g $$

Cette intersection n’est donc pas vide :

$$ f \cap g \ne \emptyset $$

On a donc finalement :

$$ \emptyset = f \cap g \ne \emptyset $$

ce qui est manifestement une absurdité. On en conclut que notre hypothèse
est invalide. Il existe donc au maximum une seule droite perpendiculaire
à $d$ et passant par $A$.

** Conclusion

Soit un point $A$ et une droite $d$. Nous avons montré qu’il existe
une et une seule droite $p$, perpendiculaire à la droite $d$ et passant
par le point $A$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-conclusion.svg]]

Il existe également un et un seul point d’intersection $I$ entre $d$
et $p$ :

$$ d \cap p = \{ I \} $$

Le point $I$ est appelé la projection orthogonale de $A$ sur $d$.

* Minimum
:properties:
:custom_id: heading:minimum
:end:

Soit un point $A$, une droite $d$ et la droite $p$, perpendiculaire à
$d$ et passant par $A$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/perpendiculaire-par-un-point-preuve-minimum.svg]]

On note $I$ la projection orthogonale de $A$ sur $d$. On trace le point
$B$, situé sur $p$ et à une distance :

$$ \abs{IB} = \abs{AI} $$

du point $I$. L’inégalité triangulaire des distances nous donne :

$$ \abs{AB} \le \abs{AC} + \abs{CB} $$

Or :

$$ \abs{AB} = \abs{AI} + \abs{IB} = 2 \ \abs{AI} $$

Les triangles rectangles $AIC$ et $BCI$ ont  :

- une cathète commune $[I,C]$
- leurs autres cathètes $[A,I]$ et $[I,B]$ de même longueur,
  par construction du point $B$

Ce sont donc des triangles isométriques et :

$$ \abs{AC} = \abs{CB} $$

En tenant compte de tous ces résultats, l’inégalité triangulaire
devient :

$$ 2 \ \abs{AI} \le 2 \ \abs{AC} $$

c’est-à-dire :

$$ \abs{AI} \le \abs{AC} $$

Lorsque $C$ est distinct de $I$, les points $A$, $B$ et $C$ ne sont pas
alignés, et on a l’iégalité stricte :

$$ \abs{AI} < \abs{AC} $$

L’égalité n’est donc atteinte que dans le cas particulier où $C =
I$. Parmi tous les points $C$ de la droite $d$, la projection orthogonale
$I$ est l’unique point qui minimise la distance avec $A$ :

$$ \abs{AI} = \min_{C \in d} \abs{AC} $$

On a donc :

$$ I = \arg\min_{C \in d} \abs{AC} $$

* Distance entre un point et une droite

La distance entre un point $A$ et une droite $d$ se définit comme la
comme étant la longueur minimale entre $A$ et tous les points de $d$ :

$$ \distance(A,d) = \min_{C \in d} \abs{AC} $$

Soit le point $B$, projection orthogonale de $A$ sur $d$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-un-point-et-une-droite.svg]]

Comme la projection orthogonale minimise la distance entre $A$ et $d$,
on a :

$$ \abs{AB} = \min_{C \in d} \abs{AC} $$

On en conclut que :

$$ \distance(A,d) = \abs{AB} $$

La distance entre un point et une droite est égale à la distance entre
ce point et sa projection orthogonale sur la droite.

* Distance entre deux droites parallèles

#+TOC: headlines 1 local

** Définition

Soit deux droites $d$ et $f$, distinctes et parallèles. Choisissons
deux points $A$ et $B$ sur la droite $d$, et traçons :

- la droite $g$, perpendiculaire à $f$ et passant par $A$
- la droite $h$, perpendiculaire à $f$ et passant par $B$
- le point $C$, intersection de $g$ et $f$ et projection orthogonale de $A$ sur $f$
- le point $D$, intersection de $h$ et $f$ et projection orthogonale de $B$ sur $f$

Le schéma ci-dessous illustre cette construction géométrique :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-deux-droites-paralleles.svg]]

Comme $d$ et $f$ sont parallèles, $g$ et $h$ sont également
perpendiculaires à $d$, comme indiqué dans le schéma.

Nous avons aussi tenu compte, dans la notation des angles, du parallélisme
de $d$ et $f$, qui implique une égalité des angles alternes-internes.

Les triangles rectangles $ACD$ et $ADB$ ont un angle $\alpha$ de même
amplitude et une hypothénuse $[A,D]$ commune. Ce sont donc des triangles
isométriques et :

$$ \abs{AC} = \abs{BD} $$

La longueur d’un segment :

- perpendiculaire à deux droites parallèles
- délimité par les points d’intersections avec ces droites

ne dépend pas du point choisi sur une des droites pour construire ce
segment. On peut donc définir la distance entre deux droites comme étant
la longueur d’un segment qui les relie et leur est perpendiculaire :

$$ \distance(d,f) = \abs{AC} $$

Comme $C$ est la projection orthogonale de $A$ sur $f$, la distance entre
deux droites est égale à la distance entre un point de la première
droite et sa projection orthogonale sur la seconde droite.

** Distance entre deux segments

La distance entre deux segments parallèles $[A,B]$ et $[C,D]$ est tout
simplement défini comme étant égal à la distance entre les droites
$(AB)$ et $(CD)$ qui les prolongent.

* Triangle isocèle

#+TOC: headlines 1 local

** Hauteur

Le schéma ci-dessous représente un triangle isocèle et la hauteur
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

On voit que les triangles rectangles $ADC$ et $BCD$ ont une cathète $h$
et leur hypothénuse de mêmes longueurs. Ils sont donc isométriques et :

$$ \abs{AD} = \abs{DB} $$

La hauteur $h$ est donc aussi une médiane du triangle $ABC$. On a aussi :

$$ \alpha = \beta $$

Les angles adjacents au côté $[A,B]$ sont égaux. L’égalité du
dernier angle :

$$ \lambda = \mu $$

signifie que la hauteur $h$ est aussi la bissectrice de l’angle
$\angleflex{ACB}$.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-hauteur-resolu.svg]]

En résumé :

- les deux angles adjacents au côté $[A,B]$ sont égaux
  + $[A,B]$ est le côté qui reste lorsqu’on retire
    les côtés de longueur égale du triangle isocèle
- la hauteur $h$ est aussi une médiane du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

** Médiane

Le schéma ci-dessous représente un triangle isocèle et la médiane
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

Par définition de la médiane, on a :

$$ b = \abs{AD} = \abs{DB} $$

On voit que les triangles $ADC$ et $BCD$ ont leurs trois côtés de mêmes
longueurs. Ils sont donc isométriques, ce qui signifie que leurs angles
sont de mêmes amplitudes. On a en particulier :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

$$ \lambda = \mu $$

Cette dernière relation signifie que la médiane $m$ est aussi la
bissectrice de l’angle $\angleflex{ACB}$.

Comme les points $A$, $D$ et $C$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat, il vient :

$$ \gamma + \delta = 2 \ \gamma = 180^\circ $$

d’où :

$$ \gamma = 90^\circ $$

La médiane $m$ est donc aussi une hauteur du triangle $ABC$.

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-mediane-resolu.svg]]

** Bissectrice

Le schéma ci-dessous représente un triangle isocèle et la bissectrice
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

On voit que les triangles $ADC$ et $BCD$ ont un angle de même amplitude
$\lambda$ situé entre deux côtés de mêmes longueurs :

- la bissectrice $b$, côté commun
- les côtés $\abs{AC}$ et $\abs{BC}$

Ils sont donc isométriques et :

$$ \abs{AD} = \abs{DB} $$

La bissectrice $b$ est donc aussi une médiane du triangle $ABC$. On a
aussi :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Comme les points $A$, $D$ et $C$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat, il vient :

$$ \gamma + \delta = 2 \ \gamma = 180^\circ $$

d’où :

$$ \gamma = 90^\circ $$

La bissectrice $b$ est donc aussi une hauteur du triangle $ABC$. Notre
schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-bissectrice-resolu.svg]]

*Conclusion* : les trois sections qui précèdent nous montre que la
hauteur, la médiatrice et la bissectrice qui partent du sommet situé
entre les côtés égaux d’un triangle isocèle se confondent.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède deux
angles de même amplitude sur deux de ses sommets, et la hauteur $h$
qui part du troisième sommet $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles.svg]]

Les triangles rectangles $ADC$ et $BCD$ ont une cathète $h$ commune,
et un angle non adjacent d’amplitude égale. Ces deux triangles sont
donc isométriques. On a en particulier :

$$ \abs{AC} = \abs{BC} $$

$$ \abs{AD} = \abs{DB} $$

$$ \lambda = \mu $$

Notre schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles-resolu.svg]]

On voit que :

- le triangle $ABC$ est isocèle
- la hauteur $h$ est aussi une médiane du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

Un triangle qui a deux angles de même amplitude est donc un triangle isocèle.

* Triangle équilatéral

#+TOC: headlines 1 local

** Angles

Le schéma ci-dessous représente un triangle équilatéral $ABC$ avec
ses trois angles :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-angles.svg]]

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[B,C]$ :

$$ \abs{AC} = \abs{BC} $$

les angles associés doivent être égaux :

$$ \alpha = \beta $$

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[A,B]$ :

$$ \abs{AC} = \abs{AB} $$

les angles associés doivent être égaux :

$$ \alpha = \gamma $$

Les trois angles sont donc identiques :

$$ \alpha = \beta = \gamma $$

La somme des angles de ce triangle nous donne :

$$ \alpha + \beta + \gamma = 3 \ \alpha = 180^\circ $$

On a donc :

$$ \alpha = \beta = \gamma = \frac{180^\circ}{3} = 60^\circ $$

Les angles d’un triangle équilatéral ont tous une amplitude de 60°.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède trois
angles égaux :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-condition-angles.svg]]

Comme les angles $\angleflex{A}$ et $\angleflex{B}$ sont égaux (ils
valent tous deux $\alpha$), ce triangle est isocèle en $[A,C]$ et
$[B,C]$ :

$$ \abs{AC} = \abs{BC} $$

Comme les angles $\angleflex{A}$ et $\angleflex{C}$ sont égaux, ce
triangle est isocèle en $[A,B]$ et $[C,B]$ :

$$ \abs{AB} = \abs{CB} $$

Les trois côtés sont donc de longueur égale.

Un triangle qui possède trois angles égaux est un triangle équilatéral.
