
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Polygones
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Soit un nombre naturel $n$.

Un polygone à $n$ côtés est une figure géométrique délimitée par
$n$ segments reliant $n$ points pour former un circuit fermé. Chaque
point du circuit est appelé *sommet* du polygone, tandis que chaque
segment est appelé *côté* du polygone.

Le schéma ci-dessous représente un exemple de polygone à sept côtés
de sommets $P_1$, $P_2$, $\ldots$, $P_7$ :

# #+attr_html: :width 27%
# #+attr_latex: :width 0.7\linewidth
# #+caption: polygone à 7 côtés
# #+name: fig:polygone_a_7_cotes
# [[file:tikz/polygone.svg]]

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/polygone.svg]]

Les côtés sont :

$$ [P_1,P_2]
\qquad \qquad \qquad
[P_2,P_3]
\qquad \qquad \qquad
[P_3,P_4]
\qquad \qquad \qquad
[P_4,P_5] $$

$$ [P_5,P_6]
\qquad \qquad \qquad
[P_6,P_7]
\qquad \qquad \qquad
[P_7,P_1]
\qquad \qquad \qquad \qquad \quad $$

On définit généralement un polygone par la liste de ces sommets. Le
polygone du schéma ci-dessus est appelé polygone $P_1 P_2 P_3 P_4 P_5
P_6 P_7$.

* Nomenclature

Les polygones les plus courants portent un nom. Nous avons déjà
rencontré le triangle, qui n’est rien d’autre qu’un polygone à
trois côtés, ainsi que le quadrilatère, polygone à quatre côtés. En
voici quelques autres :

| Nom          | Nombre de côtés |
|--------------+-----------------|
| triangle     |               3 |
| quadrilatère |               4 |
| pentagone    |               5 |
| hexagone     |               6 |
| heptagone    |               7 |
| octogone     |               8 |
| ennéagone    |               9 |
| décagone     |              10 |
| hendécagone  |              11 |
| dodécagone   |              12 |

* Diagonales

#+TOC: headlines 1 local

** Définition

Une diagonale d’un polygone $\mathcal{P}$ est un segment obtenu en
reliant deux sommets non adjacents de $\mathcal{P}$.

Par exemple, dans le schéma ci-dessous, les segments $[P_1,P_3]$ et
$[P_3,P_7]$ sont des diagonales du polygone $P_1 P_2 \ldots P_7$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diagonales-polygone.svg]]

** Classification

#+TOC: headlines 1 local

*** Introduction

Les diagonales d’un polygone peuvent se classer en fonction du nombre
de sommets qu’elles contournent. Ce nombre peut dépendre du sens de
rotation choisi pour parcourir les sommets. Aussi, afin d’éviter toute
ambiguité, on ne retient que le nombre minimal de sommets contournés.

Soit un polygone $\mathcal{P}_n$ à $n$ côtés et un nombre naturel
$k$. Une $k$-diagonale de $\mathcal{P}_n$ est une diagonale qui contourne
$k$ sommets du polygone, en choisissant le sens de rotation pour obtenir
un nombre $k$ minimal.

Examinons le polygone $P_1 P_2 \ldots P_7$ ci-dessous :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/classification-diagonales-polygone.svg]]

Lorsqu’on parcourt les sommets de $P_1 P_2 \ldots P_7$ dans le sens
anti-horlogique, on constate que :

- la diagonale $[P_1,P_3]$ contourne le sommet $P_2$
- la diagonale $[P_1,P_4]$ contourne deux sommets : $P_2$ et $P_3$
- la diagonale $[P_1,P_5]$ contourne trois sommets : $P_2$, $P_3$ et $P_4$
- la diagonale $[P_1,P_6]$ contourne quatre sommets : $P_2$, $P_3$, $P_4$ et $P_5$

Dans le sens horlogique, on observe la situation inverse :

- la diagonale $[P_1,P_3]$ contourne quatre sommets : $P_2$, $P_3$, $P_4$ et $P_5$
- la diagonale $[P_1,P_4]$ contourne trois sommets : $P_2$, $P_3$ et $P_4$
- la diagonale $[P_1,P_5]$ contourne deux sommets : $P_2$ et $P_3$
- la diagonale $[P_1,P_6]$ contourne le sommet $P_2$

En ne considérant à chaque fois que le sens de rotation qui produit le
nombre minimal de sommets contournés, on constate que :

- la diagonale $[P_1,P_3]$ est une $1$-diagonale
- la diagonale $[P_1,P_4]$ est une $2$-diagonale
- la diagonale $[P_1,P_5]$ est une $2$-diagonale
- la diagonale $[P_1,P_6]$ est une $1$-diagonale

*** Sommet intermédiaire

Un sommet contourné par une diagonale est aussi appelé sommet
intermédiaire de la diagonale.

Examinons le polygone $P_1 P_2 \ldots P_7$ ci-dessous :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/classification-diagonales-polygone.svg]]

On observe que :

- le point $P_2$ est le sommet intermédiaire de la $1$-diagonale $[P_1,P_3]$
- les points $P_2$ et $P_3$ sont les sommets intermédiaires de la $2$-diagonale $[P_1,P_4]$
- les points $P_6$ et $P_7$ sont les sommets intermédiaires de la $2$-diagonale $[P_1,P_5]$
- le point $P_7$ est le sommet intermédiaire de la $1$-diagonale $[P_1,P_6]$

*** Bornes

#+TOC: headlines 1 local

**** Minimulm

Soit une $k$-diagonale $d$ d’un polygone à $n$ côtés. Par définition
de la diagonale, il nous faut au minimum un sommet contourné :

$$ k \ge 1 $$

**** Nombre pair de côtés

Considérons le cas où $n$ est pair. Le nombre $k$ maximal est atteint
lorsque la diagonale $d$ sépare les points en deux groupes de tailles
égales. Si on décompte les deux points occupés par $d$, il reste $n - 2$
sommets contournés au total. Posons :

$$ p = n \diventiere 2 $$

La division euclidienne de $n$ par $2$ s’écrit :

$$ n = 2 \ p $$

On voit que :

$$ n - 2 = 2 \ p - 2 = 2 \ (p - 1) $$

Cette relation peut s’interpréter comme la décomposition euclidienne
de $n - 2$ par $2$. Le reste étant nul, le nombre $n - 2$ est aussi un
nombre pair, dont le quotient vaut :

$$ q = p - 1 = n \diventiere 2 - 1 $$

On peut donc diviser les $n - 2$ sommets contournés en deux groupes de
taille $q$. Cette valeur est donc le maximum pour $k$ :

$$ k \le n \diventiere 2 - 1 $$

Par exemple, avec $n = 6$ et le polygone $P_1 P_2 \ldots P_6$, la
diagonale qui maximise $k$ est la $2$-diagonale $[P_1,P_4]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/classification-diagonales-polygone-borne-pair.svg]]

On a bien :

$$ k \le 6 \diventiere 2 - 1 = 3 - 1 = 2 $$

**** Nombre impair de côtés

Si $n$ est impair, le nombre $k$ maximal est atteint lorsque la
diagonale $d$ sépare les points en deux groupes de tailles plus ou
moins égales. Le mieux que l’on puisse faire alors est d’avoir
un groupe qui compte un sommet de plus que l’autre. Posons :

$$ p = n \diventiere 2 $$

Comme le reste vaut $1$, la division euclidienne de $n$ par $2$
s’écrit :

$$ n = 2 \ p + 1 $$

Soit :

$$ q = p - 1 $$

On a $p = q + 1$ et :

$$ n = 2 \ (q + 1) + 1 = 2 \ q + 3 $$

On en déduit que :

$$ n - 2 = 2 \ q + 1 = q + (q + 1) $$

On peut donc séparer les $n - 2$ points contournés en :

- un groupe de taille $q$
- un groupe de taille $q + 1$

La taille minimale de ces deux groupes vaut :

$$ q = n \diventiere 2 - 1 $$

Cette valeur correspond au maximum pour $k$ :

$$ k \le n \diventiere 2 - 1 $$

Par exemple, avec $n = 7$ et le polygone $P_1 P_2 \ldots P_7$, les
diagonales qui maximisent $k$ sont les $2$-diagonales $[P_1,P_4]$ et
$[P_1,P_5]$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/classification-diagonales-polygone-borne-impair.svg]]

On a bien :

$$ k \le 7 \diventiere 2 - 1 = 3 - 1 = 2 $$

**** Conclusion

Dans tous les cas, on a :

$$ 1 \le k \le n \diventiere 2 - 1 $$

*** Nomenclature

Une $1$-diagonale est aussi appelée *diagonale courte*.

Une $L$-diagonale est aussi appelée *diagonale longue* si $L$ est un
nombre naturel strictement supérieur à $1$.

* Somme des angles

#+TOC: headlines 1 local

** Par une décomposition en triangles

On obtient la smme des angles d’un polygone générique à $n$ côtés
en le décomposant en triangles. Il y a toutefois quelques précautions
à prendre :

- les triangles doivent former une mosaïque qui recouvrent intégralement
  le polygone
  + les triangles ne peuvent donc pas se chevaucher
- on ne peut utiliser que les sommets du polygone
  + les côtés des triangles sont donc soit des côtés du polygones,
    soit des diagonales
  + les côtés des triangles ne peuvent pas se croiser
  + on ne peut pas faire apparaître de nouveaux sommets sans ajouter de
    nouveaux angles et obtenir un résultat incorrect

Le schéma ci-dessous donne un exemple de partition d’un polygone en
triangles :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-polygone-par-triangles.svg]]

On voit que le polygone compte six côtés (c’est un hexagone) et peut se
diviser en quatre triangles. On remarque aussi que la somme des angles de
tous les triangles est égal à la somme des angles internes du polygone.

En général, un polygone $\mathcal{P}_n$ à $n$ côtés peut se diviser
en $n - 2$ triangles. Comme la somme des angles de chaque triangle vaut
$\pi = 180^\circ$, la somme des angles de $\mathcal{P}_n$ vaut :

$$ (n - 2) \cdot \pi = (n - 2) \cdot 180^\circ $$

** Par un parcours autour du polygone

Ce raisonnement est inspiré de
[[https://www.youtube.com/watch?v=7wY-Byh8d6M][cette vidéo de Micmath]].

Imaginons un personnage fictif qui parcours un tour complet autour du
polygone suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-polygone-par-parcours.svg]]

Ce parcours se fait dans le sens anti-horlogique, en partant du
point $P_1$, avec une direction initiale donnée par le vecteur
$\vec{u}_1$. Notre personnage tourne à chaque sommet d’un angle
$\alpha_i$. l’angle total de sa rotation vaut donc  :

$$ S = \sum_{i=1}^n \alpha_i $$

où $n$ est le nombre de côtés. Mais comme il effectue un tour complet,
on a aussi :

$$ S = 2 \ \pi $$

On en déduit que :

$$ \sum_{i=1}^n \alpha_i = 2 \ \pi $$

À chaque sommet $i$, les angles $\alpha_i$ et $\beta_i$ forment ensemble
un angle plat :

$$ \alpha_i + \beta_i = \pi $$

On a donc :

$$ \alpha_i = \pi - \beta_i $$

La relation sur la somme des angles devient :

$$ \sum_{i=1}^n (\pi - \beta_i) = 2 \ \pi $$

ou encore :

$$ \sum_{i=1}^n \pi - \sum_{i=1}^n \beta_i = 2 \ \pi $$

La constante $\pi$ ne dépendant pas de $i$, on a simplement :

$$ n \ \pi - \sum_{i=1}^n \beta_i = 2 \ \pi $$

Isolons la somme des angles internes du polygone :

$$ \sum_{i=1}^n \beta_i = n \ \pi - 2 \ \pi $$

Mettons en évidence $\pi$ :

$$ \sum_{i=1}^n \beta_i = (n - 2) \ \pi $$

La somme dans le membre de gauche n’est rien d’autre que la somme
des angles internes du polygone. Nous avons donc montré que cette somme
vaut :

$$ \sum_{i=1}^n \beta_i = (n - 2) \cdot \pi = (n - 2) \cdot 180^\circ $$

** Polygones courants

On a en particulier le tableau suivant :

| Polygone     | Nombre de côtés | Somme des angles |
|--------------+-----------------+------------------|
| quadrilatère |               4 | $360^\circ$      |
| pentagone    |               5 | $540^\circ$      |
| hexagone     |               6 | $720^\circ$      |
| octogone     |               8 | $1080^\circ$     |
| décagone     |              10 | $1440^\circ$     |
| dodécagone   |              12 | $1800^\circ$     |

* Polygone et cercle

#+TOC: headlines 1 local

** Cercle circonscrit

On dit que le cercle $\mathscr{C}$ est circonscrit au polygone
$\mathcal{P}$, ou que $\mathcal{P}$ est inscrit dans $\mathscr{C}$,
si tous les sommets de $\mathcal{P}$ appartiennent à $\mathscr{C}$.

** Cercle inscrit

On dit que le cercle $\mathscr{C}$ est inscrit au polygone $\mathcal{P}$
si tous les côtés de $\mathcal{P}$ sont tangents à $\mathscr{C}$.
