
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Polygones
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un polygone régulier est un polygone dont :

- tous les côtés ont la même longueur
- tous les angles sont de même amplitude

Le schéma ci-dessous représente un heptagone régulier $P_1 P_2 \ldots
P_7$ :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/polygone-regulier.svg]]

* Angle

#+TOC: headlines 1 local

** Raisonnement

Notons $\alpha_n$ un angle quelconque d’un polygone à $n$ côtés. La
[[file:polygones.org::#heading:somme_des_angles][somme des angles]] vaut :

$$ n \ \alpha_n = (n - 2) \ \pi $$

On a donc :

$$ \alpha_n = \frac{(n - 2) \ \pi}{n} =  \frac{(n - 2) \cdot 180^\circ}{n} $$

** Polygones courants

On a en particulier le tableau suivant :

| Polygone régulier | Nombre de côtés | Somme des angles | Angle       |
|-------------------+-----------------+------------------+-------------|
| quadrilatère      |               4 | $360^\circ$      | $90^\circ$  |
| pentagone         |               5 | $540^\circ$      | $108^\circ$ |
| hexagone          |               6 | $720^\circ$      | $120^\circ$ |
| octogone          |               8 | $1080^\circ$     | $135^\circ$ |
| décagone          |              10 | $1440^\circ$     | $144^\circ$ |
| dodécagone        |              12 | $1800^\circ$     | $150^\circ$ |

** Limite à l’infini

On remarque que :

$$ \lim_{n \to \infty} \alpha_n = \lim_{n \to \infty} \frac{(n - 2) \ \pi}{n}  = \pi $$

Lorsque le nombre de côtés devient très grand, l’angle $\alpha_n$ converge
vers $\pi = 180^\circ$.

* Construction

On peut construire un polygone régulier $P_1 P_2 \ldots P_n$ en partant
seulement :

- d’un centre $O$
- d’un point $P_1$

Il suffit alors d’effectuer $n - 1$ rotations successives $\mathcal{R}$
de centre $O$ et d’angle :

$$ \theta = \frac{2 \ \pi}{n} = \frac{360^\circ}{n} $$

pour obtenir les autres sommets du polygone :

$$ P_2 = \mathcal{R}(P_1) $$

$$ P_3 = \mathcal{R}(P_2) $$

$$ P_4 = \mathcal{R}(P_3) $$

$$ \ldots $$

$$ P_n = \mathcal{R}(P_{n - 1}) $$

Comme :

$$ n \ \theta = 360^\circ $$

la $n^{ième}$ rotation revient au point de départ :

$$ P_1 = \mathcal{R}(P_n) $$

Les propriétés de la rotation garantissent alors que les triangles :

$$ O P_1 P_2
\qquad
O P_2 P_3
\qquad O
P_3 P_4
\qquad
\ldots
\qquad
O P_{n - 1} P_n
\qquad
O P_n P_1 $$

sont isométriques. Les côtés sont donc tous de même longueur, et
les angles internes de même amplitude. Le polygone $P_1 P_2 \ldots P_n$
est bien régulier. De plus, les distances entre $O$ et les sommets $P_i$
sont toutes identiques :

$$ \abs{O P_1} = \abs{O P_2} = \ldots = \abs{O P_n} $$

Le point $O$ est le centre du cercle circonscrit au polygone $P_1 P_2
\ldots P_n$.

Le schéma ci-dessous représente un heptagone régulier $P_1 P_2 \ldots
P_7$ construit avec cette méthode :

#+attr_html: :width 32%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/polygone-regulier-par-rotation.svg]]

* Invariance sous rotation

Soit un polygone régulier à $n$ côtés $P_1 P_2 \ldots P_n$, inscrit
dans un cercle $\mathscr{C}$ de centre $O$ et de rayon $r$.

Ses côtés et ses angles étant identiques, ce polygone est invariant
lorsqu’on lui applique une rotation $\mathcal{R}$ de centre $O$ et
d’angle :

$$ \theta = \frac{2 \ \pi}{n} = \frac{360^\circ}{n} $$

Il en va de même pour :

- l’ensemble des $1$-diagonales
- l’ensemble des $2$-diagonales
- etc
