
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Polynômes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:polynomes}

* Dépendances

  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes
  - Chapitre \ref{chap:somme} : Les sommes
  - Chapitre \ref{chap:produit} : Les produits

* Définition

Soit un corps $\corps$. On dit qu'une fonction $p : \corps \mapsto
\corps$ est un polynôme de degré $n$ si on peut trouver des éléments
$p_0,p_1,...p_n \in \corps$ tels que :

$$p(x) = \sum_{i = 0}^n p_i \cdot x^i$$

pour tout $x \in \corps$. On note $\polynome(\corps,n)$ l'espace des polynômes de degré $n$ définis sur $\corps$.

Un cas particulier important est celui des polynômes réels :

$$\mathcal{P}_n = \polynome(\setR,n)$$

* Équivalence avec $\corps^{n+1}$

Tout $n$-tuple $(p_0,p_1,p_2,...,p_n)\in\corps^{n+1}$ peut être associé
à un polynôme :

$$p(x) = \sum_{i = 0}^n p_i \cdot x^i \in \polynome(\corps,n)$$

et vice versa. On a donc l’équivalence :

$$\polynome(\corps,n) \equiv \corps^{n+1}$$

* Monôme

Un monôme $\mu_i : \corps \mapsto \corps$ est une fonction de la forme :

$$\mu_i(x) = x^i$$

pour tout $x \in \corps$.


* Division Euclidienne polynômiale

Soit deux polynomes $p \in \mathcal{P}_n$ et $d \in \mathcal{P}_m$
avec $m \le n$ et :

$$ p(x) = \sum_{i = 0}^n p_i \cdot x^i $$

$$ d(x) = \sum_{i = 0}^m d_i \cdot x^i $$

On dit que $q$ et $r$ sont respectivement le quotient et le reste de la
division euclidienne de $p$ par le polynôme diviseur $d$, et on note :

$$(q,r) = \division(p,d)$$

si :

$$ p(x) = d(x) \cdot q(x) + r(x) $$

avec :

$$ q(x) = \sum_{i=0}^{n-m} q_i \cdot x^i $$

et :

\[ r(x) = \sum_{i=0}^{p} r_i \cdot x^i \]

où $p \strictinferieur m \le n$.

** Méthode de Ruffini-Horner

*** Introduction

La méthode de Horner permet de diviser un polynôme $p$ de degré $n$ :

$$ p(x) = \sum_{i = 0}^n p_i \cdot x^i $$

par un polynôme $d$ du type :

$$ d(x) = x - a $$

Le polynôme diviseur $d$ est donc de degré 1.  Le polynôme quotient
doit donc être de degré $n - 1$, soit :

$$ q(x) = \sum_{i = 0}^{n - 1} q_i \cdot x^i $$

Le reste $r$ devant être de degré $p \strictinferieur 1$, il est
forcément de degré 0, soit :

$$ r(x) = R $$

La division euclidienne polynômiale s’écrit :

$$ p(x) = d(x) \cdot q(x) + r(x) $$

ou encore :

$$ p(x) = (x-a) \cdot q(x) + R $$

*** Valeur du polynôme au point $a$

En évaluant la division euclidienne polynômiale en $x = a$, on obtient :

$$ p(a) = (a-a) \cdot q(x) + R = 0 + R = R $$

Le reste est donc égal à la valeur du polynôme $p$ au point $a$.

*** Calcul du polynôme quotient et du reste

Examinons à présent plus en détail la division euclidienne polynômiale :

$$ \sum_{i=0}^n p_i \cdot x^i = (x - a) \sum_{i=1}^{n-1} \left(q_i \cdot x^i\right) + R $$

En comparant les termes de même puissance en $x$, on obtient :

\begin{align*}
q_{n-1} &= p_n \\
q_{n-2} - a \cdot q_{n-1} &= p_{n-1} \\
\ldots & \ldots \\
q_{i-1} - a \cdot q_i &= p_i \\
\ldots &= \ldots \\
q_0 - a \cdot q_1 &= p_1 \\
- a \cdot q_0 + R &= p_0
\end{align*}

Ces relations nous permettent d’évaluer les coefficients
du quotient de manière récursive :

\begin{align*}
q_{n-1} &= p_n \\
q_{n-2} &= p_{n-1} + a \cdot q_{n-1} \\
\ldots & \ldots \\
q_{i-1} &= p_i + a \cdot q_i \\
\ldots & \ldots \\
q_0 &= p_1 + a \cdot q_1 \\
R &= p_0 + a \cdot q_0
\end{align*}

*** Factorisation d’une différence de puissances

Nous avons déjà vu dans le chapitre sur les progressions
un résultat permettant de
[[file:progressions.org::#heading:factorisation_progression_geometrique][factoriser une différence de puissances]]
La méthode de Horner fournit une autre technique permettant d’arriver au
même résultat.

$$x^{n + 1} - a^{n + 1} = (x - a) \cdot \sum_{i = 0}^n x^{n - i} \cdot a^i$$

* Racines

On dit que $r$ est une racine ou un zéro du polynôme $p$ si :

$$p(r) = 0$$

Nous allons montrer que tout polynôme de degré $n$ non nul
admet au plus $n$ racines distinctes.

Ce qui revient à dire que si un polynôme de degré $n$ admet $m+1$
racines distinctes avec $m \ge n$, alors ce polynôme est forcément nul.

Soit $n = 0$. Considérons un polynôme $p_0$ de degré 0, défini par
$p_0(x) = a_0$ pour un certain $a_0 \in \corps$. On a $n + 1 = 1$. Si on
peut trouver au moins un $x_0 \in \corps$ qui est racine de $p_0$, on a :

$$ p_0(x_0) = a_0 = 0 $$

On en conclut que $a_0 = 0$ et que $p_0(x) = 0$ pour tout $x
\in \corps$, ce qui revient à dire que $p_0 = 0$. La thèse est donc
vérifiée pour $n = 0$.

A présent, supposons que l'affirmation soit vraie pour $n -
1$. Choisissons un polynôme $p_n$ de degré $n$ :

$$p_n(x) = \sum_{i=0}^n a_i \cdot x^i$$

Supposons que $p$ possède $m+1$ racines

$$p_n(x_0) = p_n(x_1) = ... = p_n(x_m) = 0$$

avec $m \ge n$ et  :

$$x_0 \strictinferieur x_1 \strictinferieur ... \strictinferieur x_m$$

On a alors :

$$p_n(x) = p_n(x) - p_n(x_0) = \sum_{i=1}^n a_i \cdot (x^i - x_0^i)$$

Nous pouvons factoriser chaque différence de puissances intervenant dans
la somme :

$$x^i - x_0^i = (x - x_0) \sum_{j = 0}^{i - 1} x^j \cdot x_0^{i - 1 -j}$$

on en déduit que :

$$p_n(x) = (x - x_0) \cdot q_{n-1}(x)$$

où le polynôme $q_{n - 1}$ est défini par :

$$q_{n - 1}(x) = \sum_{i = 1}^n a_i \sum_{j = 0}^{i - 1}  x^j \cdot x_0^{i - 1 - j}$$

Cette expression ne faisant intervenir que les puissances
$1,x,...,x^{n-1}$, on voit que $q_{n-1} \in \mathcal{P}_n$ est de degré
$n-1$. Considérons les cas des racines $x_k\in\{x_1, x_2, ...,x_m\}$
de $p_n$. On a :

$$0 = p_n(x_k) = (x_k - x_0) \cdot q_{n-1}(x_k)$$

Comme $x_k - x_0 \ne 0$, on peut multiplier par $(x_k - x_0)^{-1}$ pour obtenir :

$$q_{n-1}(x_k) = \frac{p_{n-1}(x_k)}{x_k - x_0} = 0$$

Le polynôme $q_{n-1}$ possède par conséquent au moins $m \ge n$ racines
distinctes. Il est dès lors nul par l'hypothèse de récurrence. La
factorisation de $p_n$ devient alors :

$$p_n(x) = (x - x_0) \cdot q_{n-1}(x) = 0$$

pour tout $x \in \corps$. Le polynôme $p_n$ est également nul et la
thèse est démontrée.

** Egalité

Si deux polynômes $p_1,p_2 \in \mathcal{P}_n$ sont égaux en $m + 1 \ge n + 1$ points distincts, alors le polynôme de degré $n$ :

$$h = p_1 - p_2$$

admet $m+1$ racines. Il est donc nul et $p_1 = p_2$.


* Factorisation

Choisissons un polynôme $p\in\mathcal{P}_n$ qui admet $n$ racines
distinctes $x_1,x_2,...,x_n$. Soit alors $x_0 \notin \{x_1,...,x_n\}$
et :

$$A = \frac{p(x_0)}{\prod_{i = 1}^n (x_0 - x_i)}$$

On voit que le polynôme :

$$q(x) = A \cdot \prod_{i=1}^n (x - x_i)$$

est égal à $p$ en chacune des racines :

$$p(x_i) = q(x_i) = 0 \qquad i = 1,2,...,n$$

Mais par la définition de $A$, on a aussi :

$$p(x_0) = q(x_0)$$

Les deux polynômes sont donc égaux en $n+1$ points distincts.
Comme ils sont tous deux de degré $n$, on en déduit que $p = q$.
Les coefficients doivent donc tous être égaux, et comme :

$$ p(x) = a_n \cdot x^n + \sum_{i = 0}^{n - 1} a_i \cdot x^i $$

$$ q(x) = A \cdot x^n + \sum_{i = 0}^{n - 1} b_i(x_1,...,x_n) \cdot x^i $$

on a $A = a_n$ et :

$$p(x) = a_n \cdot \prod_{i=1}^n (x - x_i)$$

* Binômes

#+TOC: headlines 1 local

** Binômes canoniques

Le binôme canonique de degré $n \in \setN$ est une fonction $b_n : \corps \to \corps$ définie par :

$$b_n(x) = (1 + x)^n$$

pour tout $x \in \corps$. On a par exemple :

\begin{align}
b_0(x) &= (1 + x)^0 = 1 \\
b_1(x) &= (1 + x)^1 = 1 + x \\
b_2(x) &= (1 + x)^2 = (1 + x) \cdot (1 + x) = 1 + 2 \ x + x^2
\end{align}

On voit donc que le binôme canonique de degré $n$ peut s'écrire comme :

$$b_n(x) = (1 + x)^n = \sum_{k = 0}^n a_{nk} \cdot x^k$$

pour certains coefficients $a_{nk} \in \corps$. On nomme ces coefficients les « nombres binômiaux », et on les note :

$$\binome{n}{k} = a_{nk}$$

L'expression de $b_0$ nous donne :

$$\binome{0}{0} = 1$$

On peut évaluer récursivement les nombres binômiaux d'ordres plus élevés en utilisant la définition de la puissance :

$$b_n(x) = (1 + x) \cdot b_{n-1}(x)$$

Il vient alors :

\begin{align*}
\sum_{k = 0}^n \binome{n}{k} \cdot x^k &= (1 + x) \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^k \\
&= \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^k + \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^{k + 1} \\
&= \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^k + \sum_{i = 1}^n \binome{n - 1}{i - 1} \cdot x^i
\end{align*}

et finalement :

\begin{Eqts}
\sum_{k = 0}^n \binome{n}{k} \cdot x^k
= \binome{n - 1}{0} + \sum_{k = 1}^{n - 1} \left[ \binome{n - 1}{k} + \binome{n - 1}{k - 1} \right] \cdot x^k +
\binome{n - 1}{n - 1} \cdot x^n
\end{Eqts}

En égalisant les coefficients des $x^0 = 1$, nous avons :

$$\binome{n}{0} = \binome{n - 1}{0}$$

On en déduit par récurrence que :

$$\binome{n}{0} = 1$$

En égalisant les coefficients des $x^n$, nous avons :

$$\binome{n}{n} = \binome{n - 1}{n - 1}$$

On en déduit par récurrence que :

$$\binome{n}{n} = 1$$

En égalisant les coefficients de $x^k$ pour $k \in \{1,...,n-1\}$, il vient :

$$\binome{n}{k} = \binome{n - 1}{k} + \binome{n - 1}{k - 1}$$

Il est donc facile d'évaluer les coefficients de $b_n$ à partir des coefficients de $b_{n - 1}$.

** Binômes génériques

Le binôme générique de degré $n \in \setN$ est une fonction $B_n : \corps \times \corps
\mapsto \corps$ définie par :

$$B_n(x,y) = (x + y)^n$$

pour tout $(x,y) \in \corps^2$. Nous avons la forme équivalente :

$$B_n(x,y) = y^n \cdot \left( 1 + \frac{x}{y} \right)^n = y^n \cdot b_n\left( \frac{x}{y} \right)$$

c'est-à-dire :

$$B_n(x,y) = \sum_{k = 0}^n \binome{n}{k} \cdot x^k \cdot y^{n - k}$$

** Second degré

Le binôme du second degré est couramment utilisé :

$$(x + y)^2 = x \ (x + y) + y \ (x + y) = x^2 + 2 \ x \ y + y^2$$

** Symétrie

Par commutativité de l'addition, on a $B_n(x,y) = B_n(y,x)$ et :

$$\sum_{k = 0}^n \binome{n}{k} \cdot x^k \cdot y^{n - k} = \sum_{i = 0}^n \binome{n}{i} \cdot y^i \cdot x^{n - i}$$

Procédant au changement d'indice $n - i = k$, il vient :

$$\sum_{k = 0}^n \binome{n}{k} \cdot x^k \cdot y^{n - k} = \sum_{k = 0}^n \binome{n}{n - k} \cdot x^k \cdot y^{n - k}$$

On en déduit en égalisant les coefficients de $x^k$ que :

$$\binome{n}{k} = \binome{n}{n - k}$$

** Cas particuliers

En considérant le cas particuliers $x = y = 1$, on constate que :

$$\sum_{k=0}^{n} \binome{n}{k} = (1 + 1)^n = 2^n$$

Pour $x = -1$, $y = 1$, on a :

$$\sum_{k=0}^{n} \binome{n}{k} \cdot (-1)^k = (-1 + 1)^n = 0^n = 0$$

Lorsque $y = 1 - x$ on arrive à :

$$\sum_{k=0}^{n} \binome{n}{k} \cdot x^k \cdot (1-x)^{n-k} = (x + 1 - x)^n = 1^n = 1$$

** Bernstein

Soit $i,n \in \setN$ avec $i \le n$. Les polynômes de Bernstein $B_i^n$ sont définis par :

$$B_i^n(t) = \binome{n}{i} \cdot t^i \cdot (1 - t)^{n-i}$$

pour tout $t \in [0,1]$.

Considérons l'espace fonctionnel $\mathcal{F} =
\fonction([0,1],\corps)$. L'opérateur de Bernstein $\mathcal{B}_n :
\mathcal{F} \mapsto \mathcal{F}$ est défini par :

$$\mathcal{B}_n(f)(t) = \sum_{i = 0}^n f(i / n) \cdot B_i^n(t)$$

pour tout $f \in \mathcal{F}$ et pour tout $t \in [0,1]$.

Soit la fonction constante $c \in \mathcal{F}$ associée à un certain $c \in \corps$ et définie par :

$$c(t) = c$$

pour tout $t \in [0,1]$.

L'opérateur de Bernstein possède l'importante propriété de conserver ces fonctions constantes :

$$\mathcal{B}_n(c)(t) = \sum_{i = 0}^n c \cdot B_i^n(t) = c \sum_{i = 0}^n \binome{n}{i} t^i \cdot (1 - t)^{n-i} = c$$

quelle que soit la valeur de $t \in [0,1]$.
