
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Polygones
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Hexagone

#+TOC: headlines 1 local

** Triangles équilatéraux

Le schéma ci-dessous représente un hexagone régulier inscrit dans un
cercle de centre $O$ et de rayon $r$ :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/hexagone-tour.svg]]

On constate que les six angles au centre d’amplitude $\alpha$ forment
un tour complet :

$$ 6 \ \alpha = 2 \ \pi = 360^\circ $$

On a donc :

$$ \alpha = \frac{\pi}{3} = 60^\circ $$

Examinons le triangle $OAB$. Les longueurs des deux côtés reliés au
centre $O$ sont de longueurs égales au rayon $r$. Il s’agit donc d’un
triangle isocèle et les angles correspondants sont par symétrie de même
amplitude :

$$ \beta = \gamma $$

La somme des angles du triangle $OAB$ vaut $180^\circ$ :

$$ \alpha + \beta + \gamma = 60^\circ + 2 \ \beta = 180^\circ $$

On en déduit que :

$$ \beta = \frac{180^\circ - 60^\circ}{2} = 60^\circ $$

Le triangle $OAB$ a donc ses trois angles de même amplitude :

$$ \alpha = \beta = \gamma = 60^\circ = \frac{\pi}{3} $$

Il s’agit donc d’un triangle équilatéral dont les longueurs des côtés
valent :

$$ c = r $$

Le schéma devient donc :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/hexagone-triangles-equilateraux.svg]]

Ce constat donne une méthode pour tracer aisément un hexagone régulier :

- tracer le cercle de centre $O$
- laisser le compas ouvert au même rayon $r$
- reporter le rayon du compas sur le cercle jusqu’à obtenir les six
  sommets de l’hexagone

Ce résultat montre aussi que les angles internes d’un hexagone valent :

$$ \beta + \gamma = 60^\circ + 60^\circ = 120^\circ $$

** Diagonales

Le schéma ci-dessous représente un hexagone régulier muni de toutes ses
diagonales, les diamètres du cercle et les deux grands triangles formant
un hexagramme :

#+attr_html: :width 700px
#+attr_latex: :width 700px
[[file:../include/tikz/hexagone-diagonales.svg]]

Le cercle est de rayon $r$. On définit les distances :

$$ a = \abs{EG} $$

$$ b = \abs{GC} $$

$$ c = \abs{OG} $$

$$ d = \abs{GD} $$

Par symétrie, on a :

$$ a = b $$

$$ \delta = \epsilon $$

$$ \alpha = \beta $$

$$ \lambda = \mu $$

Intéressons-nous à présent au triangle $OGE$.  On constate que $\delta$
et $\epsilon$ forment ensemble un angle plat de 180° :

$$ \delta + \epsilon = 180^\circ $$

Comme ces deux angles sont égaux, on a :

$$ 2 \ \delta = 180^\circ $$

c’est-à-dire :

$$ \delta = 90^\circ $$

Le triangle $OGE$ est donc un triangle rectangle dont l’hypthénuse
vaut :

$$ \abs{OE} = r $$

*** Angles

Les angles non droit du triangle rectangle $OGE$ étant complémentaires,
on a :

$$ \alpha = 90^\circ - 60^\circ = 30^\circ $$

Comme l’angle $\alpha + \lambda$ est l’un des angles du triangle
équilatéral $OED$, on a :

$$ \alpha + \lambda = 60^\circ $$

c’est-à-dire :

$$ \lambda = 60^\circ - \alpha = 60^\circ - 30^\circ = 30^\circ $$

et :

$$ \mu = \lambda = 30^\circ $$

On a donc finalement :

$$ \alpha = \beta = \lambda = \mu = \frac{\pi}{6} = 30^\circ $$

*** Longueurs

Le triangle $OGE$ étant un triangle rectangle, on a :

$$ a = r \ \sin 60^\circ = r \ \frac{\sqrt{3}}{2} $$

La longueur $L$ du côté $[EC]$ du triangle $ACE$ vaut donc :

$$ L = \abs{EC} = a + b = 2 \ a $$

c’est-à-dire :

$$ L = r \ \sqrt{3} $$

On a aussi :

$$ c = r \ \cos 60^\circ = \frac{r}{2} $$

Comme :

$$ c + d = \abs{OD} = r $$

on a :

$$ d = r - c = r - \frac{r}{2} = \frac{r}{2} $$

*** Conclusion

On peut appliquer le même raisonnement aux autres côtés du triangle
$ACE$, et ainsi montrer que le triangle $ACE$ est un triangle
équilatéral de côté $L = r \ \sqrt{3}$.

Il en va de même pour le triangle $DFB$.

Nous avons aussi montré que les côtés des triangles équilatéraux formés
par les diagonales divisent les rayons du cercle en deux parties égales de
longueur $r/2$.

Par symétrie, il est clair que le triangle équilatéral $ACE$ contient
six triangles isométriques à $OGE$ (en incluant $OGE$ lui-même). Ces
triangles possèdent donc les mêmes angles et les mêmes longueurs
de côtés.

Soit un triangle équilatéral $T$ formé par les diagonales de
l’hexagone, c’est-à-dire un des deux triangles $ACE$ ou $DFB$
formant l’hexagramme. Nous avons montré que :

- les rayons du cercle divisent les angles de $T$ en deux angles égaux de 30°
- les angles situés entre les pointes de $T$ et les côtés de l’hexagone
  sont également de 30°

** Hexagramme

Le schéma ci-dessous représente un hexagone régulier muni de toutes ses
diagonales, les diamètres du cercle et les deux grands triangles formant
un hexagramme :

#+attr_html: :width 700px
#+attr_latex: :width 700px
[[file:../include/tikz/hexagone-hexagramme.svg]]

Le cercle est de rayon $r$. On définit les distances :

$$ a = \abs{HD} $$

$$ b = \abs{ID} $$

$$ c = \abs{EH} $$

$$ d = \abs{HG} $$

$$ e = \abs{GI} $$

$$ f = \abs{IC} $$

Par symétrie, on a :

$$ a = b $$

$$ c = f $$

$$ a = c $$

$$ b = f $$

$$ d = e $$

$$ \alpha = \beta $$

*** Triangles compris entre l’hexagramme et les côtés de l’hexagone

Examinons à présent le triangle $FJE$. Nous avons vu précédemment
que les angles compris entre les triangles de l’hexagramme ($ACE$
et $DFB$) et les côtés de l’hexagone valent 30°. On a donc :

$$ \lambda = \mu = 30^\circ $$

Le troisième angle $\theta$ vaut donc :

$$ \theta = 180^\circ - 30^\circ - 30^\circ = 120^\circ $$

Les cinq autres triangles compris entre les côtés de l’hexagone et
l’hexagramme sont par symétrie isométriques à $FJE$.

*** Pointes de l’hexagramme

Examinons à présent les triangles formés aux pointes de l’hexagramme.

Le triangle $DFB$ étant équilatéral, ses angles valent 60° et en
particulier :

$$ \gamma = 60^\circ $$

Comme $\alpha$ et $\beta$ sont égaux, on a aussi :

$$ \alpha + \beta + \gamma = 2 \ \alpha + 60^\circ = 180^\circ $$

c’est-à-dire :

$$ \alpha = \frac{180^\circ - 60^\circ}{2} = 60^\circ $$

Le triangle $DHI$ est donc aussi un triangle équilatéral et :

$$ a = b = d + e = 2 \ d $$

Le côté $[EC]$ du triangle équilatéral $ACE$ est de longueur $r \
\sqrt{3}$. En décomposant cette longueur, on obtient :

$$ c + d + e + f = r \ \sqrt{3} $$

ou, en tenant compte de la symétrie :

$$ a + \frac{a}{2} + \frac{a}{2} + a = r \ \sqrt{3} $$

c’est-à-dire :

$$ 3 \ a = r \ \sqrt{3} $$

ce qui nous donne la valeur de $a$ et des mesures associées :

$$ a = b = c = f = r \ \frac{\sqrt{3}}{3} $$

$$ d = e = r \ \frac{\sqrt{3}}{6} $$

*** Conclusion

Les triangles compris entre les côtés de l’hexagone et l’hexagramme ont
des angles aigus de 30° et un angle obtus de 120°.

Les pointes de l’hexagramme sont des triangles équilatéraux de
côté $r \ \sqrt{3}/3$, c’est-à-dire le tiers du côté des triangles
formant l’hexagramme.

* Pentagone

#+TOC: headlines 1 local

** Angles au centre

Le schéma ci-dessous représente un pentagone régulier inscrit dans un
cercle de centre $O$ et de rayon $r$ :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/pentagone-tour.svg]]

On constate que les cinq angles au centre d’amplitude $\alpha$ forment
un tour complet :

$$ 5 \ \alpha = 2 \ \pi = 360^\circ $$

On a donc :

$$ \alpha = \frac{2 \ \pi}{5} = 72^\circ $$

Examinons le triangle $OAB$. Les longueurs des deux côtés reliés au
centre $O$ sont de longueurs égales au rayon $r$. Il s’agit donc d’un
triangle isocèle et les angles correspondants sont par symétrie de même
amplitude :

$$ \beta = \gamma $$

La somme des angles du triangle $OAB$ vaut $180^\circ$ :

$$ \alpha + \beta + \gamma = 72^\circ + 2 \ \beta = 180^\circ $$

On en déduit que :

$$ \beta = \frac{180^\circ - 72^\circ}{2} = 54^\circ $$

Ce résultat montre aussi que les angles internes d’un pentagone valent :

$$ \beta + \gamma = 54^\circ + 54^\circ = 108^\circ $$

** Diagonales

Le schéma ci-dessous représente un pentagone muni de toutes ses
diagonales formant un pentagramme, ainsi que les rayons du cercle  :

#+attr_html: :width 600px
#+attr_latex: :width 600px
[[file:../include/tikz/pentagone-diagonales.svg]]

Par symétrie, on a :

$$ \alpha = \beta $$

Examinons le triangle $ABE$. La somme des angles vaut 180° :

$$ \alpha + \beta + 108^\circ = 2 \ \alpha + 108^\circ = 180^\circ $$

On en déduit la valuer des autres angles :

$$ \alpha = \beta = \frac{180^\circ - 108^\circ}{2} = 36^\circ $$

Un angle compris entre un côté du pentagone et une diagonale vaut 36°.

** Pentagramme

Le schéma ci-dessous représente un pentagone muni de toutes ses
diagonales formant un pentagramme, ainsi que les rayons du cercle  :

#+attr_html: :width 700px
#+attr_latex: :width 700px
[[file:../include/tikz/pentagone-pentagramme.svg]]

Par symétrie, on a :

$$ \beta = \gamma $$

L’angle $\alpha$ forme, avec deux angles de 36°, un angle interne du
pentagone. On a donc :

$$ \alpha + 2 \cdot 36^\circ = 108^\circ $$

c’est-à-dire :

$$ \alpha = 108^\circ -  2 \cdot 36^\circ = 36^\circ $$

Dans le triangle $AFG$, les angles $\beta$ et $\gamma$ sont égaux et
$\alpha = 36^\circ$. On a donc :

$$ \alpha + \beta + \gamma = 36^\circ + 2 \ \beta = 180^\circ $$

c’est-à-dire :

$$ \beta = \gamma = \frac{180^\circ - 36^\circ}{2} = 72^\circ $$

Examinons à présent le triangle $ABF$. On obtient directement la valeur
de l’angle $\theta$ par :

$$ \theta + 36^\circ + 36^\circ = 180^\circ $$

qui nous donne :

$$ \theta = 180^\circ - 36^\circ - 36^\circ = 108^\circ $$

** Nombre d’or

Le schéma ci-dessous représente un pentagone muni de toutes ses
diagonales formant un pentagramme, ainsi que les rayons du cercle  :

#+attr_html: :width 700px
#+attr_latex: :width 700px
[[file:../include/tikz/pentagone-nombre-d-or.svg]]

Le cercle est de rayon $r$. La longueur du côté du pentagone se note :

$$ c = \abs{AB} = \abs{BC} = \abs{CD} = \abs{DE} = \abs{EA} $$

On définit aussi les distances :

$$ d = \abs{EF} $$

$$ e = \abs{FB} $$

$$ f = \abs{FA} $$

Par symétrie, on a :

$$ e = f $$

$$ d = g $$

*** Triangle isocèle

Dans le triangle $AFE$, on a :

$$ \alpha + 72^\circ + 36^\circ = 180^\circ $$

d’où :

$$ \alpha = 72^\circ $$

Les deux angles aigus du triangle $AFE$ sont donc égaux. Par symétrie,
il s’agit donc d’un triangle isocèle et :

$$ c = d $$

*** Triangles semblables

On remarque que les triangles $ABC$ et $ABF$ ont des angles correspondants
de même amplitude : ce sont donc des triangles semblables. Leurs rapports
de longueurs sont donc identiques. On a en particulier :

$$ \frac{f + g}{c} = \frac{c}{f} $$

Comme $c = d = g$ et $e = f$, cette relation devient :

$$ \frac{e + c}{c} = \frac{c}{e} $$

ou :

$$ \frac{e}{c} + 1 = \frac{c}{e} $$

Posons :

$$ \phi = \frac{c}{e} $$

La relation entre les longueurs devient :

$$ \unsur{\phi} + 1 = \phi $$

Multiplions par $\phi$. On obtient :

$$ 1 + \phi = \phi^2 $$

ou encore :

$$ \phi^2 - \phi - 1 = 0 $$

Nous avons vu dans le chapitre sur les
[[file:proportions-metalliques.org][proportions métalliques]],
que la solution positive de cette équation définit le
[[file:proportions-metalliques.org::#heading:nombre_d_or][nombre d’or]] :

$$ \phi = \frac{1+\sqrt{5}}{2} $$

La longueur de la diagonale du pentagone vaut :

$$ d + e = c + e $$

On a donc :

$$ \frac{d + e}{c} = \frac{c + e}{c} = \frac{c}{e} = \phi $$

Le rapport entre la longueur de la diagonale d’un pentagone et la
longueur de son côté est égal au nombre d’or.

*** Trigonométrie

**** Cosinus de 36°

Dans le triangle $ABF$, la loi des cosinus nous donne une expression de
la longueur $f$  :

$$ f = c^2 + d^2 - 2 \ c \ d \ \cos 36^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ e^2 = c^2 + c^2 - 2 \ c^2 \ \cos 36^\circ = 2 \ c^2 - 2 \ c^2 \ \cos 36^\circ $$

Divisons par $c^2$ :

$$ \frac{e^2}{c^2} = 2 - 2 \ \cos 36^\circ $$

Mais comme $\phi = c / e$, cette équation devient :

$$ \unsur{\phi^2} = 2 - 2 \ \cos 36^\circ $$

Multiplions par $\phi^2$ :

$$ 1 = 2 \ \phi^2 - 2 \ \phi^2 \ \cos 36^\circ $$

et isolons le cosinus :

$$ \cos 36^\circ = \frac{2 \phi^2 - 1}{2 \ \phi^2} $$

Comme $\phi^2 = \phi + 1$ par définition du nombre d’or, on a :

$$ \cos 36^\circ = \frac{2 (\phi + 1) - 1}{2 \ \phi^2} $$

c’est-à-dire :

$$ \cos 36^\circ
= \frac{2 \phi + 2 - 1}{2 \ \phi^2}
= \frac{2 \phi + 1}{2 \ \phi^2} $$

Nous avons vu dans la section sur le
[[file:proportions-metalliques.org::#heading:nombre_d_or][nombre d’or]]
que $\phi^3 = 2 \ \phi + 1$. La relation précédente devient donc :

$$ \cos 36^\circ = \frac{\phi^3}{2 \ \phi^2} $$

c’est-à-dire :

$$ \cos 36^\circ = \frac{\phi}{2} $$

Le cosinus de 36° vaut la moitié du nombre d’or.

**** Sinus de 54°

Il en va de même pour le sinus de l’angle complémentaire, à savoir 54° :

$$ \sin 54^\circ = \frac{\phi}{2} $$

**** Cosinus de 72°

Pour calculer le cosinus de 72°, angle double de 36°,
on utilise la formule du cosinus de l’angle double :

$$ \cos 72^\circ
= 2 \ (\cos 36^\circ)^2 - 1
= \frac{2 \ \phi^2}{4} - 1
= \frac{\phi^2}{2} - 1 $$

Comme $\phi^2 = \phi + 1$, on a :

$$ \cos 72^\circ = \frac{\phi + 1}{2} - 1 $$

puis :

$$ \cos 72^\circ = \frac{\phi + 1 - 2}{2} $$

et finalement :

$$ \cos 72^\circ = \frac{\phi - 1}{2} $$

**** Sinus de 18°

Il en va de même pour le sinus de l’angle complémentaire, à savoir 18° :

$$ \sin 18^\circ = \frac{\phi - 1}{2} $$

**** Cosinus de 18°

Pour calculer le cosinus de 18°, angle moitié de 36°,
on utilise la formule inverse du cosinus de l’angle double :

$$ (\cos 18^\circ)^2 = \frac{1 + \cos 36^\circ}{2} = \frac{1 + \phi / 2}{2} $$

Multiplions par deux le numérateur de le dénominateur de la fraction du
membre de droite :

$$ (\cos 18^\circ)^2 = \frac{2 + \phi}{4} $$

puis prenons la racine :

$$ \cos 18^\circ = \sqrt{\frac{2 + \phi}{4}} $$

et faisons sortir le dénominateur :

$$ \cos 18^\circ = \frac{\sqrt{\phi + 2}}{2} $$

**** Sinus de 72°

Il en va de même pour le sinus de l’angle complémentaire, à savoir 72° :

$$ \sin 72^\circ = \frac{\sqrt{\phi + 2}}{2} $$

**** Sinus de 36°

Le sinus de 36° vaut :

$$ \sin 36^\circ = \sqrt{1 - \cos 36^\circ} = \sqrt{1 - \frac{\phi^2}{4}} $$

Mettons l’intérieur de la racine au même dénominateur :

$$ \sin 36^\circ = \sqrt{\frac{4 - \phi^2}{4}} $$

Faisons sortir le dénominateur de la racine :

$$ \sin 36^\circ = \frac{\sqrt{4 - \phi^2}}{2} $$

Comme $\phi^2 = \phi + 1$, il vient :

$$ \sin 36^\circ = \frac{\sqrt{4 - \phi - 1}}{2} $$

et finalement :

$$ \sin 36^\circ = \frac{\sqrt{3 - \phi}}{2}$$

**** Cosinus de 54°

Il en va de même pour le cosinus de l’angle complémentaire, à savoir
54° :

$$ \cos 54^\circ = \frac{\sqrt{3 - \phi}}{2}$$

**** Tangente de 36°

La tangente de 36° vaut :

$$ \tan 36^\circ = \frac{\sin 36^\circ}{\cos 36^\circ} = \frac{\sqrt{3 - \phi}/2}{\phi / 2} $$

Multiplions numérateur et dénominateur de la fraction du membre de
droite par $2$ :

$$ \tan 36^\circ = \frac{\sqrt{3 - \phi}}{\phi} $$

Faisons renter le dénominateur dans la racine :

$$ \tan 36^\circ = \sqrt{\frac{3 - \phi}{\phi^2}} = \sqrt{\frac{3}{\phi^2} - \unsur{\phi}} $$

Nous avons vu dans la section sur le
[[file:proportions-metalliques.org::#heading:nombre_d_or][nombre d’or]]
que :

$$ \unsur{\phi} = \phi - 1 \qquad\qquad\qquad
\unsur{\phi^2} = 2 - \phi $$

La relation précédente devient donc :

$$ \tan 36^\circ = \sqrt{3 \ (2 - \phi) - (\phi - 1)} = \sqrt{6 - 3 \ \phi - \phi + 1} $$

et finalement :

$$ \tan 36^\circ = \sqrt{7 - 4 \ \phi} $$

**** Tangente de 54°

On en déduit la tangente de l’angle complémentaire de 54° :

$$ \tan 54^\circ = \unsur{\tan 36^\circ} = \unsur{\sqrt{7 - 4 \ \phi}} $$

* Octogone

#+TOC: headlines 1 local

** Angles au centre

Le schéma ci-dessous représente un octogone régulier inscrit dans un
cercle de centre $O$ et de rayon $r$ :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/octogone-tour.svg]]

On constate que les huit angles au centre d’amplitude $\alpha$ forment
un tour complet :

$$ 8 \ \alpha = 2 \ \pi = 360^\circ $$

On a donc :

$$ \alpha = \frac{\pi}{4} = 45^\circ $$

Examinons le triangle $OAB$. Les longueurs des deux côtés reliés au
centre $O$ sont de longueurs égales au rayon $r$. Il s’agit donc d’un
triangle isocèle et les angles correspondants sont par symétrie de même
amplitude :

$$ \beta = \gamma $$

La somme des angles du triangle $OAB$ vaut $180^\circ$ :

$$ \alpha + \beta + \gamma = 45^\circ + 2 \ \beta = 180^\circ $$

On en déduit que :

$$ \beta = \frac{180^\circ - 45^\circ}{2} = 67,5^\circ $$

Ce résultat montre aussi que les angles internes d’un octogone valent :

$$ \beta + \gamma = 67,5^\circ + 67,5^\circ = 135^\circ $$

* Tableau récapitulatif des résultat trigonométriques

Notre tableau récapitulatif des valeurs particulières des fonctions
trigonométriques s’agrandit :

| Radians      | Degrés       | sin                 | cos                 | tan                     |
|--------------+--------------+---------------------+---------------------+-------------------------|
| $0$          | $0$          | $0$                 | $1$                 | $0$                     |
| $\pi/10$     | $18^\circ$   | $(\phi - 1)/2$      | $\sqrt{\phi + 2}/2$ |                         |
| $\pi/8$      | $22,5^\circ$ |                     |                     |                         |
| $\pi/6$      | $30^\circ$   | $1/2$               | $\sqrt{3}/2$        | $\sqrt{3}/3$            |
| $\pi/5$      | $36^\circ$   | $\sqrt{3 - \phi}/2$ | $\phi/2$            | $\sqrt{7 - 4 \ \phi}$   |
| $\pi/4$      | $45^\circ$   | $\sqrt{2}/2$        | $\sqrt{2}/2$        | $1$                     |
| $3 \ \pi/10$ | $54^\circ$   | $\phi/2$            | $\sqrt{3 - \phi}/2$ | $1/\sqrt{7 - 4 \ \phi}$ |
| $\pi/3$      | $60^\circ$   | $\sqrt{3}/2$        | $1/2$               | $\sqrt{3}$              |
| $3 \ \pi/8$  | $67,5^\circ$ |                     |                     |                         |
| $2 \ \pi/5$  | $72^\circ$   | $\sqrt{\phi + 2}/2$ | $(\phi - 1)/2$      |                         |
| $\pi/2$      | $90^\circ$   | $1$                 | $0$                 | $\infty$                |
