
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Polygones
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Définition

Soit un nombre naturel $n$.

Un polygone à $n$ côtés est une figure géométrique délimitée par
$n$ segments reliant $n$ points pour former un circuit fermé. Chaque
point du circuit est appelé *sommet* du polygone, tandis que chaque
segment est appelé *côté* du polygone.

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
#+caption: polygone à 7 côtés
#+name: fig:polygone_a_7_cotes
[[file:tikz/polygone.svg]]

Le schéma ci-dessus représente un exemple de polygone à sept côtés
de sommets $P_1,P_2,...,P_7$. Les côtés sont :

$$ [P_1,P_2] $$

$$ [P_2,P_3] $$

$$ \ldots $$

$$ [P_6,P_7] $$

$$ [P_7,P_1] $$

On définit généralement un polygone par la liste de ces sommets. Le
polygone du schéma ci-dessus est appelé polygone $P_1 P_2 P_3 P_4 P_5
P_6 P_7$.

** Nomenclature

Les polygones les plus courants portent un nom. Nous avons déjà
rencontré le triangle, qui n’est rien d’autre qu’un polygone à
trois côtés. En voici quelques autres :

| Nom          | Nombre de côtés |
|--------------+-----------------|
| triangle     |               3 |
| quadrilatère |               4 |
| pentagone    |               5 |
| hexagone     |               6 |
| heptagone    |               7 |
| octogone     |               8 |
| ennéagone    |               9 |
| décagone     |              10 |
| hendécagone  |              11 |
| dodécagone   |              12 |

** Diagonales

Une diagonale d’un polygone $\mathcal{P}$ est un segment obtenu en
reliant deux sommets non adjacents de $\mathcal{P}$.

Par exemple, dans le schéma ci-dessous, les segments $[P_1,P_5]$ et
$[P_5,P_7]$ sont des diagonales du polygone $P_1 P_2 \ldots P_7$ :

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diagonales-polygone.svg]]

* Polygone régulier

Un polygone régulier est un polygone dont :

- tous les côtés ont la même longueur
- tous les angles sont de même amplitude

** Invariance sous rotation

Ses côtés et ses angles étant identiques, un polygone régulier à $n$
côtés est invariant lorsqu’on lui applique une rotation de :

$$ \frac{2 \ \pi}{n} = \frac{360^\circ}{n} $$

* Angles d’un polygone

#+TOC: headlines 1 local

** Somme des angles

#+TOC: headlines 1 local

*** Par une décomposition en triangles

On obtient la smme des angles d’un polygone générique à $n$ côtés
en le décomposant en triangles. Il y a toutefois quelques précautions
à prendre :

- les triangles doivent former une mosaïque qui recouvrent intégralement
  le polygone
  + les triangles ne peuvent donc pas se chevaucher
- on ne peut pas faire apparaître de nouveaux sommets sans ajouter de
  nouveaux angles et obtenir un résultat incorrect
  + on ne peut donc utiliser que les sommets du polygone
    * les côtés des triangles sont donc soit des côtés du polygones,
      soit des diagonales
    * les côtés des triangles ne peuvent pas se croiser

Le schéma ci-dessous donne un exemple de partition d’un polygone en
triangles :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-polygone-par-triangles.svg]]

On voit que le polygone compte six côtés (c’est un hexagone) et peut
se diviser en quatre triangles. On remarque aussi que la somme des angles
de tous les triangles est égal à la somme des angles du polygone.

En général, un polygone $\mathcal{P}_n$ à $n$ côtés peut se diviser
en $n - 2$ triangles. Comme la somme des angles de chaque triangle vaut
$\pi = 180^\circ$, la somme des angles de $\mathcal{P}_n$ vaut :

$$ (n - 2) \cdot \pi = (n - 2) \cdot 180^\circ $$

On a en particulier le tableau suivant :

| Polygone     | Nombre de côtés | Somme des angles                  |
|--------------+-----------------+-----------------------------------|
| quadrilatère |               4 | $2 \cdot 180^\circ = 360^\circ$   |
| pentagone    |               5 | $3 \cdot 180^\circ = 540^\circ$   |
| hexagone     |               6 | $4 \cdot 180^\circ = 720^\circ$   |
| octogone     |               8 | $6 \cdot 180^\circ = 1080^\circ$  |
| décagone     |              10 | $8 \cdot 180^\circ = 1440^\circ$  |
| dodécagone   |              12 | $10 \cdot 180^\circ = 1800^\circ$ |

*** Par un parcours autour du polygone

Ce raisonnement est inspiré de
[[https://www.youtube.com/watch?v=7wY-Byh8d6M][cette vidéo de Micmath]].

Imaginons un personnage fictif qui parcours un tour complet autour du
polygone suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-polygone-par-parcours.svg]]

Ce parcours se fait dans le sens anti-horlogique, en partant du point
$P$, avec une direction initiale donnée par le vecteur $\vec{u}$. Notre
personnage tourne à chaque sommet d’un angle $\alpha_i$. l’angle
total de sa rotation vaut donc  :

$$ S = \sum_{i=1}^n \alpha_i $$

où $n$ est le nombre de côtés. Mais comme il effectue un tour complet,
on a aussi :

$$ S = 2 \ \pi $$

On en déduit que :

$$ \sum_{i=1}^n \alpha_i = 2 \ \pi $$

À chaque sommet $i$, les angles $\alpha_i$ et $\gamma_i$ forment ensemble
un angle plat :

$$ \alpha_i + \gamma_i = \pi $$

On a donc :

$$ \alpha_i = \pi - \gamma_i $$

La relation sur la somme des angles devient :

$$ \sum_{i=1}^n (\pi - \gamma_i) = 2 \ \pi $$

ou encore :

$$ \sum_{i=1}^n \pi - \sum_{i=1}^n \gamma_i = 2 \ \pi $$

La constante $\pi$ ne dépendant pas de $i$, on a simplement :

$$ n \ \pi - \sum_{i=1}^n \gamma_i = 2 \ \pi $$

Isolons la somme des angles internes du polygone :

$$ \sum_{i=1}^n \gamma_i = n \ \pi - 2 \ \pi $$

Mettons en évidence $\pi$ :

$$ \sum_{i=1}^n \gamma_i = (n - 2) \ \pi $$

La somme dans le membre de gauche n’est rien d’autre que la somme
des angles internes du polygone. Nous avons donc montré que cette somme
vaut :

$$ \sum_{i=1}^n \gamma_i = (n - 2) \cdot \pi = (n - 2) \cdot 180^\circ $$

** Angle d’un polygone régulier

Dans le cas d’un polygone régulier, tous les angles sont égaux. Notons
$\alpha_n$ un angle quelconque d’un polygone à $n$ côtés. La somme des
angles vaut :

$$ n \ \alpha_n = (n - 2) \ \pi $$

On a donc :

$$ \alpha_n = \frac{(n - 2) \ \pi}{n} =  \frac{(n - 2) \cdot 180^\circ}{n} $$

On a en particulier le tableau suivant :

| Polygone régulier | Nombre de côtés | Somme des angles | Angle                       |
|-------------------+-----------------+------------------+-----------------------------|
| quadrilatère      |               4 | $360^\circ$      | $360^\circ/4 = 90^\circ$    |
| pentagone         |               5 | $540^\circ$      | $540^\circ/5 = 108^\circ$   |
| hexagone          |               6 | $720^\circ$      | $720^\circ/6 = 120^\circ$   |
| octogone          |               8 | $1080^\circ$     | $1080^\circ/8 = 135^\circ$  |
| décagone          |              10 | $1440^\circ$     | $1440^\circ/10 = 144^\circ$ |
| dodécagone        |              12 | $1800^\circ$     | $1800^\circ/12 = 150^\circ$ |

On remarque aussi que :

$$ \lim_{n \to \infty} \alpha_n = \lim_{n \to \infty} \frac{(n - 2) \ \pi}{n}  = \pi $$

Lorsque le nombre de côtés devient très grand, l’angle $\alpha_n$ converge
vers $\pi = 180^\circ$.

* Polygone et cercle

#+TOC: headlines 1 local

** Cercle circonscrit

On dit que le cercle $\mathscr{C}$ est circonscrit au polygone
$\mathcal{P}$, ou que $\mathcal{P}$ est inscrit dans $\mathscr{C}$,
si tous les sommets de $\mathcal{P}$ appartiennent à $\mathscr{C}$.
