
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Produit extérieur
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:prdext}

* Dépendances

  - Chapitre \ref{chap:vecteur} : Les vecteurs
  - Chapitre \ref{chap:tenseur} : Les tenseurs

* Dimension 2

Soit l'espace vectoriel $E = \combilin{e_1,e_2}$ sur $S$, où $(e_1,e_2)$ forme est une base orthonormée. Soit $u,v \in E$. On a :

#+BEGIN_CENTER
\(
u = \sum_{i = 1}^2 u_i e_i \)

\(
v = \sum_{i = 1}^2 v_i e_i
\)
#+END_CENTER

pour certains $u_i,v_i \in S$.

Les symboles $\permutation_{ij}\quad (i,j=1,2)$ sont définis de telle sorte que pour tout $u,v$ la double somme :

$$u \wedge v = \sum_{i,j=1}^2 \permutation_{ij} u_i v_j$$

représente (au signe près) la surface du parallélogramme dont les sommets
sont $(0,0)$, $(u_1,u_2)$, $(v_1,v_2)$ et $(u_1+v_1,u_2+v_2)$. On impose
de plus l'antisymétrie :

$$u \wedge v = - v \wedge u$$

afin de donner une orientation à ce parallélogramme. Ces contraintes nous donnent :

#+BEGIN_CENTER
\(
u = e_1, \quad v = e_1 \quad \Rightarrow \quad u \wedge v = 0 \)

\(
u = e_1, \quad v = e_2 \quad \Rightarrow \quad u \wedge v = 1 \)

\(
u = e_2, \quad v = e_2 \quad \Rightarrow \quad u \wedge v = 0 \)

\(
u = e_2, \quad v = e_1 \quad \Rightarrow \quad u \wedge v = -1
\)
#+END_CENTER

ce qui nous amène à :

#+BEGIN_CENTER
\(
\permutation_{11} = \permutation_{22} = 0 \)

\(
\permutation_{12} = 1 \qquad \permutation_{21} = -1
\)
#+END_CENTER

On voit qu'il y a un certain arbitraire dans notre choix, on aurait
pu également choisir :

#+BEGIN_CENTER
\(
\permutation_{11} = \permutation_{22} = 0 \)

\(
\permutation_{12} = -1 \qquad \permutation_{21} = 1
\)
#+END_CENTER

Le choix du signe détermine ce que l'on appelle l'orientation de l'espace $E$.


* Dimension 3

Soit l'espace vectoriel $E = \combilin{e_1,e_2,e_3}$ sur $S$, où $(e_1,e_2,e_3)$ forme est une base orthonormée. Soit $u,v,w \in E$. On a :

#+BEGIN_CENTER
\(
u = \sum_{i = 1}^3 u_i e_i \)

\(
v = \sum_{i = 1}^3 v_i e_i \)

\(
w = \sum_{i = 1}^3 w_i e_i
\)
#+END_CENTER

pour certains $u_i,v_i,w_i \in S$.

Les symboles $\permutation_{ijk} \quad (i,j=1,2,3)$ sont définis de telle sorte que pour tout $u,v,w$ le scalaire :

$$u \wedge v \wedge w = \sum_{i,j,k=1}^3 \permutation_{ijk} u_i v_j w_k$$

représente (au signe près) le volume du parallélipipède dont les côtés
sont définis par $u$, $v$ et $w$. On impose également l'antisymétrie

#+BEGIN_CENTER
\(
u \wedge v \wedge w = - u \wedge w \wedge v \)

\(
u \wedge v \wedge w = - v \wedge u \wedge w
\)
#+END_CENTER

Par un procédé analogue au cas bidimensionnel, on montre qu'un choix possible
est donné par :

#+BEGIN_CENTER
\(
\permutation_{123} = 1 \)

\(
\permutation_{ijj} = \permutation_{iij} = \permutation_{iji} = 0 \)

\(
\permutation_{ijk} = \permutation_{jki} = \permutation_{kij} \)

\(
\permutation_{ijk} = - \permutation_{jik} \qquad
\permutation_{ijk} = - \permutation_{ikj}
\)
#+END_CENTER


** Produit vectoriel

On peut également former un vecteur avec l'opérateur $\wedge$. On pose
simplement :

$$u \wedge v = \sum_{i,j,k = 1}^3 \left( \permutation_{ijk} u_j v_k \right) e_i$$

Les composantes sont donc données par :

#+BEGIN_CENTER
\(
(u \wedge v)_1 = u_2 v_3 - u_3 v_2  \)

\(
(u \wedge v)_2 = u_3 v_1 - u_1 v_3  \)

\(
(u \wedge v)_3 = u_1 v_2 - u_2 v_1
\)
#+END_CENTER

On peut relier le produit extérieur au produit scalaire en constatant que :

$$\scalaire{u}{v \wedge w} = \sum_{i,j,k} \permutation_{ijk} u_i v_j w_k = u \wedge v \wedge w$$


* Permutations en dimension $N$

Voyons quelles sont les propriétés communes aux $\permutation_*$ présentés
ci-dessus. On remarque que $\permutation_{12} = \permutation_{123} = 1$. On note aussi que $\permutation_*$ est antysimétrique puisque l'inversion de deux indices change le signe. Ces propriétés nous permettent de généraliser la définition du produit extérieur à un espace de dimension $N$. On impose que le $\permutation$ à $N$ indices vérifie les conditions suivantes :

\label{def:eps}

#+BEGIN_CENTER
\(
\permutation_{1,2,...,N} = 1 \)

\(
\permutation_{i ... j ... k ... l} = - \permutation_{i ... k ... j ... l}
\)
#+END_CENTER

Ces conditions nous permettent de retrouver la valeur de n'importe quel $\permutation_{ijk...l}$. Si deux indices sont égaux, l'antisymétrie nous permet d'affirmer que :

$$\permutation_{i ... j ... j ... k} = - \permutation_{i ... j ... j ... k}$$

et donc :

$$\permutation_{i ... j ... j ... k} = 0$$

Les seuls $\permutation$ non nuls sont donc ceux dont tous les indices $(i,j,k,...,s)$ sont distincts, c'est-à-dire les permutations de $(1,2,3,...,N)$. On se rend compte que si $p \in \setN$ est le nombre de permutations de couples d'indices nécessaires pour obtenir $(i,j,k,...,s)$ à partir de $(1,2,3,...,N)$, on a :

$$\permutation_{i j k ... l} = (-1)^p$$


* Tenseur de permutation

Soit $(e_1,e_2,...,e_N)$ une base orthonormée d'un espace vectoriel $E$ sur $S$. Nous définissons le tenseur de permutation $\mathcal{E} \in \tenseur_N(E)$ par :

$$\mathcal{E} = \sum_{i_1,i_2,...,i_N} \permutation_{i_1,i_2,...,i_N} \cdot e_{i_1} \otimes e_{i_2} \otimes ... \otimes e_{i_N}$$


* Produit extérieur généralisé

Soit $(e_1,e_2,...,e_N)$ une base orthonormée d'un espace vectoriel $E$ sur $\corps$,
$M \le N$ et les vecteurs $u_1,u_2,...u_M \in E$ de coordonnées $u_k^i$ :

$$u_k = \sum_{i = 1}^N u_k^i e_i$$

Nous définissons leur produit extérieur par une contraction d'ordre $M$ :

$$u_1 \wedge u_2 \wedge ... \wedge u_M = \contraction{ \mathcal{E} }{M}{ u_M \otimes ... \otimes u_1 }$$

Par orthonormalité de la base, on a :

$$\scalaire{e_j}{u_k} = u_k^j$$

Le produit extérieur s'écrit donc :

$$\mathcal{U} = u_1 \wedge u_2 \wedge ... \wedge u_M = \sum_{i_1,i_2,...i_N} \permutation_{i_1,i_2,...i_N} \cdot e_{i_1} \otimes ... \otimes e_{ i_{N - M} } \cdot u_M^{i_N} \cdot \ldots \cdot u_1^{ i_{N - M + 1} }$$

ce qui nous donne les coordonnées du tenseur $\mathcal{U} \in \tenseur_{N-M}(E)$ par rapport à la base $(e_1,...,e_N)$ :

$$U_{ i_1,...,i_{N - M} } = \sum_{i_{N - M + 1},...,i_N} \permutation_{i_1,i_2,...i_N} \cdot u_1^{ i_{N - M + 1} } \cdot \ldots \cdot u_M^{i_N}$$

On vérifie les propriétés suivantes :

#+BEGIN_CENTER
\(
u \wedge v = - v \wedge u \)

\(
u \wedge u = 0 \)

\(
(\alpha u + \beta v) \wedge w = \alpha u \wedge w + \beta v \wedge w \)

\(
w \wedge (\alpha u + \beta v) = \alpha w \wedge u + \beta w \wedge v
\)
#+END_CENTER

pour tout $u,v,w,... \in E$ et $\alpha,\beta \in S$.


** $N$ vecteurs

Dans le cas où $M = N$, le produit extérieur est le scalaire :

$$\Delta = u_1 \wedge u_2 \wedge ... \wedge u_N = \sum_{i,j,...,k = 1}^N \permutation_{ij...k} \cdot u_1^i \cdot u_2^j \cdot \ldots \cdot u_N^k$$

On appelle le $\Delta$ ainsi obtenu le déterminant des $N$ vecteurs $u_i$, et on le note :

$$\det(u_1,...,u_N) = u_1 \wedge u_2 \wedge ... \wedge u_N$$


* Déterminant d'une matrice

Soit une matrice $A \in \matrice(K,N,N)$ :

$$A = \left( a_{ij} \right)_{i,j}$$

et les vecteurs correspondants :

$$a_i = \sum_j a_{ij} e_j$$

On définit alors simplement :

#+BEGIN_CENTER
\(
\det(A) = a_1 \wedge ... \wedge a_N = \sum_{i_1,i_2,...i_N} \permutation_{i_1,i_2,...i_N} a_{1, i_1 } ...
a_{N, i_N}
\)
#+END_CENTER


