
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Proportions métalliques
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Nombre d’or

#+TOC: headlines 1 local

** Définition

On cherche un nombre $\phi$ réel positif tel que :

$$ \unsur{\phi} = \phi - 1 $$

$$ 1 = \phi^2 - \phi $$

$$ \phi^2 - \phi - 1 = 0 $$

En utilisant la technique de résolution d’une équation du second
degré, il vient :

$$ \delta^2 = \frac{(-1)^2 - 4 \cdot 1 \cdot (-1)}{4 \cdot 1^2} = \frac{5}{4} $$

Les valeurs possibles pour $\delta$ sont donc :

$$ \delta_+ = \frac{\sqrt{5}}{2} $$

$$ \delta_- = - \frac{\sqrt{5}}{2} $$

On en déduit celles pour $\phi$ :

$$ \phi_+ = \frac{-(-1)}{2 \cdot 1} + \frac{\sqrt{5}}{2} = \frac{1+\sqrt{5}}{2} $$

$$ \phi_- = \frac{-(-1)}{2 \cdot 1} - \frac{\sqrt{5}}{2} = \frac{1-\sqrt{5}}{2} $$

Comme nous cherchons une valeur de $\phi$ positive, on rejette la
seconde solution. On a donc :

$$ \phi = \frac{1+\sqrt{5}}{2} $$

** Carré

L’expression du carré de $\phi$ vient directement de la définition :

$$ \phi^2 = \phi + 1 $$

** Cube

On a :

\begin{align*}
\phi^3
&= \phi \cdot \phi^2 \\
&= \phi \cdot (\phi + 1) \\
&= \phi^2 + \phi \\
&= \phi + 1 + \phi
\end{align*}

et finalement :

$$ \phi^3 = 2 \ \phi + 1 $$

** Inverse du carré

On a :

\begin{align*}
\unsur{\phi^2}
&= (\phi - 1)^2 \\
&= \phi^2 - 2 \ \phi + 1 \\
&= \phi + 1 - 2 \ \phi + 1
\end{align*}

et finalement :

$$ \unsur{\phi^2} = 2 - \phi $$

** Inverse du cube

On a :

\begin{align*}
\unsur{\phi^3}
&= \unsur{\phi} \cdot \unsur{\phi^2} \\
&= (\phi - 1) \ (2 - \phi) \\
&= 2 \ \phi - \phi^2 - 2 + \phi \\
&= 2 \ \phi - \phi - 1 - 2 + \phi \\
\end{align*}

et finalement :

$$ \unsur{\phi^3} = 2 \ \phi - 3 $$

* Angle de 36°

On a :

$$ \cos(72^\circ + 18^\circ) = \cos 90^\circ = 0 $$

La formule de la somme nous donne :

$$ \cos(72^\circ + 18^\circ)
= \cos 72^\circ \ \cos 18^\circ - \sin 72^\circ \ \sin 18^\circ $$

On en déduit que :

$$ \cos 72^\circ \ \cos 18^\circ - \sin 72^\circ \ \sin 18^\circ = 0 $$

Posons :

$$ c = \cos 36^\circ $$

Nous allons rééxprimer les grandeurs ci-dessus en fonction de
$c$. Remarquons que :

$$ \sin 36^\circ = \sqrt{1 - (\cos 36^\circ)^2} = \sqrt{1 - c^2} $$

Le cosinus de 72° se réécrit :

$$ \cos 72^\circ = 2 \ (cos 36^\circ)^2 - 1 = 2 \ c^2 - 1 $$

Le cosinus de 18° se réécrit :

$$ (\cos 18^\circ)^2 = \frac{1 + \cos 36^\circ}{2} = \frac{1 + c}{2} $$

d’où :

$$ \cos 18^\circ = \sqrt{\frac{1 + c}{2}} $$

Le sinus de 72° se réécrit :

$$ \sin 72^\circ
= 2 \ \cos 36^\circ \ \sin 36^\circ
= 2 \ c \ \sqrt{1 - c^2} $$

Le sinus de 18° se réécrit :

$$ (\sin 18^\circ)^2 = \frac{1 - \cos 36^\circ}{2} = \frac{1 - c}{2} $$

d’où :

$$ \sin 18^\circ = \sqrt{\frac{1 - c}{2}} $$

La relation :

$$ \cos 72^\circ \ \cos 18^\circ - \sin 72^\circ \ \sin 18^\circ = 0 $$

devient alors :

$$ (2 \ c^2 - 1) \ \sqrt{\frac{1+c}{2}} - 2 \ c \ \sqrt{1-c^2} \ \sqrt{\frac{1-c}{2}} = 0 $$

Multiplions par $\sqrt{2}$ :

$$ (2 \ c^2 - 1) \ \sqrt{1+c} = 2 \ c \ \sqrt{1-c^2} \ \sqrt{1-c} $$

ou encore :

$$ (2 \ c^2 - 1) \ \sqrt{1+c} = 2 \ c \ \sqrt{1-c} \ \sqrt{1+c} \ \sqrt{1-c} $$

Divisons par $\sqrt{1+c}$ :

$$ 2 \ c^2 - 1
= 2 \ c \ \sqrt{1-c} \ \sqrt{1-c}
= 2 \ c \ (1-c)
= 2 \ c - 2 \ c^2 $$

On obtient finalement une équation du second degré :

$$ 4 \ c^2 - 2 \ c - 1 = 0 $$

Le chapitre sur les
[[file:polynomes-du-second-degre.org][polynômes du second degré]]
donne une méthode pour résoudre cette équation.

Appliquons cette méthode. En utilisans les mêmes notations, on a :

$$ \gamma = \frac{2}{8} = \unsur{4} $$

et :

$$ \delta^2 = \frac{4 - 4 \cdot 4 \cdot (-1)}{4 \cdot 16} = \frac{20}{64} $$

d’où :

$$ \delta = \pm \frac{2 \sqrt{5}}{8} = \frac{\sqrt{5}}{4} $$

Le cosinus de 36° étant un réel positif, on en déduit que :

$$ \cos 36^\circ = \frac{1 + \sqrt{5}}{4} $$

c’est-à-dire :

$$ \cos 36^\circ = \frac{\phi}{2} $$

* Nombre d’argent

On cherche un nombre $\psi$ réel positif tel que :

$$ \unsur{\psi} = \psi - 2 $$

$$ 1 = \psi^2 - 2 \ \psi $$

$$ \psi^2 - 2 \ \psi - 1 = 0 $$

En utilisant la technique de résolution d’une équation du second
degré, il vient :

$$ \delta^2 = \frac{4 - 4 \cdot 1 \cdot (-1)}{4 \cdot 1^2} = \frac{8}{4} $$

Les valeurs possibles pour $\delta$ sont donc :

$$ \delta_+ = \frac{2 \ \sqrt{2}}{2} = \sqrt{2} $$

$$ \delta_- = - \frac{2 \ \sqrt{2}}{2} = - \sqrt{2} $$

On en déduit celles pour $\psi$ :

$$ \psi_+ = 1 + \sqrt{2} $$

$$ \psi_- = 1 - \sqrt{2} $$

Comme nous cherchons une valeur de $\psi$ positive, on rejette la
seconde solution. On a donc :

$$ \psi = 1 + \sqrt{2} $$

* Nombre de bronze

On cherche un nombre $\varphi$ réel positif tel que :

$$ \unsur{\varphi} = \varphi - 3 $$

$$ 1 = \varphi^2 - 3 \ \varphi $$

$$ \varphi^2 - 3 \ \varphi - 1 = 0 $$

En utilisant la technique de résolution d’une équation du second
degré, il vient :

$$ \delta^2 = \frac{9 - 4 \cdot 1 \cdot (-1)}{4 \cdot 1^2} = \frac{13}{4} $$

Les valeurs possibles pour $\delta$ sont donc :

$$ \delta_+ = \frac{\sqrt{13}}{2} $$

$$ \delta_- = - \frac{\sqrt{13}}{2} $$

On en déduit celles pour $\varphi$ :

$$ \varphi_+ = \frac{3+\sqrt{13}}{2} $$

$$ \varphi_- = \frac{3-\sqrt{13}}{2} $$

Comme nous cherchons une valeur de $\varphi$ positive, on rejette la
seconde solution. On a donc :

$$ \varphi = \frac{1+\sqrt{13}}{2} $$
