
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Proportions géométriques
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles semblables

#+TOC: headlines 1 local

** Deux angles

#+TOC: headlines 1 local

*** Disposition acutangle

Considérons deux triangles $ABC$ et $XYZ$ qui
possèdent deux angles $\alpha$ et $\beta$ de mêmes
amplitudes. Nous avons vu dans la section qui traite de
[[file:triangles-isometriques.org::#heading:angle_de_meme_amplitude][triangles
possédant un angle de même amplitude]] que nous pouvons construire un
triangle $ADE$ isométrique à $XYZ$, tel que les deux angles $\alpha$
soient placés au même endroit :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables-deux-angles-acutangle.svg]]

On trace le segment $[A,G]$, perpendiculaire à $[D,E]$. Les angles
correspondants $\beta$ étant de même amplitude, les côtés $[B,C]$ et
$[D,E]$ sont parallèles. Le segment $[A,G]$ est donc aussi perpendiculaire
à $[B,C]$, comme indiqué sur le schéma. Remarquons que les troisièmes
angles des deux triangles sont aussi de même amplitude :

$$ \gamma = \delta = 180^\circ - \alpha - \beta $$

On définit les longueurs et la hauteur du triangle $ABC$ :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{BC}
\qquad \qquad \qquad
f = \abs{AF} $$

Idem pour le triangle $ADE$ :

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE}
\qquad \qquad \qquad
k = \abs{DE}
\qquad \qquad \qquad
g = \abs{AG} $$

et pour les côtés partiels :

$$ u = \abs{BF}
\qquad \qquad \qquad
v = \abs{FC}
\qquad \qquad \qquad
w = \abs{DG}
\qquad \qquad \qquad
z = \abs{GE} $$

Les triangles rectangles $BFA$ et $DGA$ ont un angle $\lambda$ et même
amplitude. Ce sont donc des triangles semblables. On a la
proportion commune :

$$ \varphi = \frac{d}{a} = \frac{w}{u} = \frac{g}{f} $$

Les triangles rectangles $FCA$ et $GEA$ ont un angle $\mu$ et même
amplitude. Ce sont donc des triangles semblables. On a la proportion
commune :

$$ \psi = \frac{e}{b} = \frac{z}{v} = \frac{g}{f} $$

Les deux proportions sont identiques :

$$ \varphi = \frac{g}{f} = \psi $$

avec comme conséquence immédiate :

$$ \varphi
= \frac{d}{a}
= \frac{w}{u}
= \frac{g}{f}
= \frac{z}{v}
= \frac{e}{b} $$

Isolons $w$ :

$$ w = \varphi \ u $$

et $z$ :

$$ z = \varphi \ v $$

Le côté $k$ peut s’écrire :

$$ k = w + z $$

En remplaçant $w$ et $z$ par leurs expressions, cette équation devient :

$$ k = \varphi \ u + \varphi \ v = \varphi \ (u + v) $$

Comme :

$$ c = u + v $$

on a finalement :

$$ k = \varphi \ c $$

Les côtés $k$ et $c$ respectent également la proportion $\varphi$. Les
triangles $ABC$ et $ADE$ ont donc leurs trois côtés proportionnels :

$$ \varphi = \frac{d}{a} = \frac{e}{b} = \frac{k}{c} $$

ou encore :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{AE}}{\abs{AC}} = \frac{\abs{DE}}{\abs{BC}} $$

Les trois angles $\alpha$, $\beta$ et $\gamma = \delta$ étant de mêmes
amplitudes, les triangles $ABC$ et $ADE$ sont semblables. Comme ce
dernier est isométrique au triangle $XYZ$, les triangles $ABC$ et $XYZ$
sont également semblables.

Deux triangles acutangles qui possèdent deux angles de mêmes amplitudes
sont des triangles semblables.

*** Disposition obtusangle

Considérons deux triangles obtusangles $ABC$ et $XYZ$ qui possèdent deux
angles $\alpha$ et $\beta$ de mêmes amplitudes. Nous pouvons construire
un triangle $ADE$ isométrique à $XYZ$, tel que les deux angles $\alpha$
soient placés au même endroit :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables-deux-angles-obtusangle.svg]]

On trace le segment $[A,G]$, perpendiculaire à $[D,G]$. Les angles
correspondants $\beta$ étant de même amplitude, les segment $[B,F]$ et
$[D,G]$ sont parallèles. Le segment $[A,G]$ est donc aussi perpendiculaire
à $[B,F]$, comme indiqué sur le schéma. Remarquons que les troisièmes
angles des deux triangles sont aussi de même amplitude :

$$ \gamma = \delta = 180^\circ - \alpha - \beta $$

On définit les longueurs et la hauteur du triangle $ABC$ :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{BC}
\qquad \qquad \qquad
f = \abs{AF} $$

Idem pour le triangle $ADE$ :

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE}
\qquad \qquad \qquad
k = \abs{DE}
\qquad \qquad \qquad
g = \abs{AG} $$

et pour les côtés partiels :

$$ u = \abs{CF}
\qquad \qquad \qquad
v = \abs{EG} $$

Les triangles rectangles $BFA$ et $DGA$ ont un angle $\lambda$ et même
amplitude. Ce sont donc des triangles semblables. On a la
proportion commune :

$$ \varphi = \frac{d}{a} = \frac{k + v}{c + u} = \frac{g}{f} $$

Les triangles rectangles $CFA$ et $EGA$ ont un angle $\mu$ et même
amplitude. Ce sont donc des triangles semblables. On a la proportion
commune :

$$ \psi = \frac{e}{b} = \frac{v}{u} = \frac{g}{f} $$

Les deux proportions sont identiques :

$$ \varphi = \frac{g}{f} = \psi $$

avec comme conséquence immédiate :

$$ \varphi
= \frac{d}{a}
= \frac{k + v}{c + u}
= \frac{g}{f}
= \frac{v}{u}
= \frac{e}{b} $$

Isolons $k$ :

$$ k = \varphi \ (c + u) - v = \varphi \ c + \varphi \ u - v $$

et $v$ :

$$ v = \varphi \ u $$

Le côté $k$ peut se réécrire :

$$ k = \varphi \ c + v - v = \varphi \ c $$

Les côtés $k$ et $c$ respectent également la proportion $\varphi$. Les
triangles $ABC$ et $ADE$ ont donc leurs trois côtés proportionnels :

$$ \varphi = \frac{d}{a} = \frac{e}{b} = \frac{k}{c} $$

ou encore :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{AE}}{\abs{AC}} = \frac{\abs{DE}}{\abs{BC}} $$

Les trois angles $\alpha$, $\beta$ et $\gamma$ étant de mêmes
amplitudes, les triangles $ABC$ et $ADE$ sont semblables. Comme ce
dernier est isométrique au triangle $XYZ$, les triangles $ABC$ et $XYZ$
sont également semblables.

Deux triangles obtusangles qui possèdent deux angles de mêmes amplitudes
sont des triangles semblables.

*** Conclusion

Deux triangles qui possèdent deux angles de mêmes amplitudes
sont des triangles semblables.

** Côté - angle - côté

#+TOC: headlines 1 local

*** Acutangle

Considérons deux triangles acutangles $ABC$ et $XYZ$ qui possèdent un
angle $\alpha$ de même amplitude, compris entre deux côtés de longueurs
proportionnelles. Nous pouvons construire un triangle $ADE$ isométrique à
$XYZ$, tel que les deux angles $\alpha$ soient placés au même endroit :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables-cote-angle-cote-acutangle.svg]]

On trace les segments $[A,G]$, $[B,H]$ et $[C,I]$, tous trois
perpendiculaires à $[D,E]$. Ces trois segments sont donc parallèles
entre-eux :

$$ [A,G] \parallel [B,H] \parallel [C,I] $$

On en déduit que les angles correspondants $\lambda$ et $\mu$ sont
égaux :

$$ \lambda = \mu $$

Il en va de même pour les angles correspondants $\eta$ et $\theta$ :

$$ \eta = \theta $$

On définit les longueurs et la hauteur du triangle $ABC$ :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC} $$

Idem pour le triangle $ADE$ :

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE} $$

pour les différences de longueurs :

$$ u = \abs{BD}
\qquad \qquad \qquad
v = \abs{CE} $$

et pour les perpendiculaires :

$$ g = \abs{AG}
\qquad \qquad \qquad
h = \abs{BH}
\qquad \qquad \qquad
p = \abs{CI} $$

Comme les côtés autour de l’angle sont proportionnels, on a la
proportion commune :

$$ \varphi = \frac{d}{a} = \frac{e}{b} $$

Les points $A$, $B$ et $D$ étant alignés, on a :

$$ d = a + u $$

Isolons $u$ :

$$ u = d - a $$

et appliquons la technique des
[[file:triangles.org::#heading:triangles_semblables_differences_de_longueurs][différences
de longueurs]] dans les
[[file:triangles.org::#heading:triangles_semblables][triangles semblables]] :

$$ \frac{u}{d}
= \frac{d - a}{d}
= 1 - \frac{a}{d}
= 1 - \unsur{\varphi}
= \frac{\varphi - 1}{\varphi} $$

Les points $A$, $C$ et $E$ étant alignés, on a :

$$ e = b + v $$

Isolons $v$ :

$$ v = e - b $$

et appliquons la technique des différences de longueurs dans les
triangles semblables :

$$ \frac{v}{e}
= \frac{e - b}{e}
= 1 - \frac{b}{e}
= 1 - \unsur{\varphi}
= \frac{\varphi - 1}{\varphi} $$

On en conclut que :

$$ \frac{u}{d} = \frac{\varphi - 1}{\varphi} = \frac{v}{e} $$

Les triangles rectangles $ADG$ et $DHB$ on un angle $\lambda = \mu$
de même amplitude. Ils sont donc semblables et :

$$ \frac{h}{u} = \frac{g}{d} $$

ou encore :

$$ h = \frac{u}{d} \ g = \frac{\varphi - 1}{\varphi} \ g $$

Les triangles rectangles $AGE$ et $IEC$ on un angle $\eta = \theta$
de même amplitude. Ils sont donc semblables et :

$$ \frac{p}{v} = \frac{g}{e} $$

ou encore :

$$ p = \frac{v}{e} \ g = \frac{\varphi - 1}{\varphi} \ g $$

On en conclut que :

$$ h = p $$

Le quadrilatère $HICB$ contient deux côtés de longueurs identiques
$[B,H]$ et $[C,I]$ formant deux angles droits avec le côté $[H,I]$. Il
s’agit donc d’un rectangle. Les droites $(HI) = (DE)$ et $(BC)$ sont
parallèles. Une conséquence directe est que les angles correspondants
$\beta$ et $\gamma$ sont égaux. Les triangles $ABC$ et $ADE$ ont donc
au total deux angles de même amplitude, ce qui signifie qu’ils sont
semblables. Comme le triangle $ADE$ est isométrique au triangle $XYZ$,
les triangles $ABC$ et $XYZ$ sont également semblables.

Deux triangles acutangles qui possèdent un angle de même amplitude
compris entre deux côtés proportionnels sont des triangles semblables.

*** Obtusangle

Considérons deux triangles obtusangles $ABC$ et $XYZ$ qui possèdent un
angle $\alpha$ de même amplitude, compris entre deux côtés de longueurs
proportionnelles. Nous pouvons construire un triangle $ADE$ isométrique à
$XYZ$, tel que les deux angles $\alpha$ soient placés au même endroit :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables-cote-angle-cote-obtusangle.svg]]

On trace les segments $[A,G]$, $[B,H]$ et $[C,I]$, tous trois
perpendiculaires à $[D,E]$. Ces trois segments sont donc parallèles
entre-eux :

$$ [A,G] \parallel [B,H] \parallel [C,I] $$

On en déduit que les angles correspondants $\lambda$ et $\mu$ sont
égaux :

$$ \lambda = \mu $$

Il en va de même pour les angles correspondants $\eta$ et $\theta$ :

$$ \eta = \theta $$

On définit les longueurs et la hauteur du triangle $ABC$ :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC} $$

Idem pour le triangle $ADE$ :

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE} $$

pour les différences de longueurs :

$$ u = \abs{BD}
\qquad \qquad \qquad
v = \abs{CE} $$

et pour les perpendiculaires :

$$ g = \abs{AG}
\qquad \qquad \qquad
h = \abs{BH}
\qquad \qquad \qquad
p = \abs{CI} $$

Comme les côtés autour de l’angle sont proportionnels, on a la
proportion commune :

$$ \varphi = \frac{d}{a} = \frac{e}{b} $$

Les points $A$, $B$ et $D$ étant alignés, on a :

$$ d = a + u $$

Isolons $u$ :

$$ u = d - a $$

et appliquons la technique des
[[file:triangles.org::#heading:triangles_semblables_differences_de_longueurs][différences
de longueurs]] dans les
[[file:triangles.org::#heading:triangles_semblables][triangles semblables]] :

$$ \frac{u}{d}
= \frac{d - a}{d}
= 1 - \frac{a}{d}
= 1 - \unsur{\varphi}
= \frac{\varphi - 1}{\varphi} $$

Les points $A$, $C$ et $E$ étant alignés, on a :

$$ e = b + v $$

Isolons $v$ :

$$ v = e - b $$

et appliquons la technique des différences de longueurs dans les
triangles semblables :

$$ \frac{v}{e}
= \frac{e - b}{e}
= 1 - \frac{b}{e}
= 1 - \unsur{\varphi}
= \frac{\varphi - 1}{\varphi} $$

On en conclut que :

$$ \frac{u}{d} = \frac{\varphi - 1}{\varphi} = \frac{v}{e} $$

Les triangles rectangles $ADG$ et $DHB$ on un angle $\lambda = \mu$
de même amplitude. Ils sont donc semblables et :

$$ \frac{h}{u} = \frac{g}{d} $$

ou encore :

$$ h = \frac{u}{d} \ g = \frac{\varphi - 1}{\varphi} \ g $$

Les triangles rectangles $AEG$ et $EIC$ on un angle $\eta = \theta$
de même amplitude. Ils sont donc semblables et :

$$ \frac{p}{v} = \frac{g}{e} $$

ou encore :

$$ p = \frac{v}{e} \ g = \frac{\varphi - 1}{\varphi} \ g $$

On en conclut que :

$$ h = p $$

Le quadrilatère $HICB$ contient deux côtés de longueurs identiques
$[B,H]$ et $[C,I]$ formant deux angles droits avec le côté $[H,I]$. Il
s’agit donc d’un rectangle. Les droites $(HI) = (DE)$ et $(BC)$ sont
parallèles. Une conséquence directe est que les angles correspondants
$\beta$ et $\gamma$ sont égaux. Les triangles $ABC$ et $ADE$ ont donc
au total deux angles de même amplitude, ce qui signifie qu’ils sont
semblables. Comme le triangle $ADE$ est isométrique au triangle $XYZ$,
les triangles $ABC$ et $XYZ$ sont également semblables.

Deux triangles obtusangles qui possèdent un angle de même amplitude
compris entre deux côtés proportionnels sont des triangles semblables.

*** Conclusion

Deux triangles qui possèdent un angle de même amplitude compris entre
deux côtés proportionnels sont des triangles semblables.

** Côtés proportionnels

Considérons deux triangles $ABC$ et $XYZ$ qui possèdent trois côtés
proportionnels. Traçons le triangle $ABC$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables-trois-cotes.svg]]

Prolongeons la demi-droite $[AB)$ et plaçons le point $D \in [AB)$
à la distance :

$$ \abs{AD} = \abs{XY} $$

de $A$. Ensuite, prolongeons la demi-droite $[AC)$ et plaçons le point
$E \in [AC)$ à la distance :

$$ \abs{AE} = \abs{XZ} $$

On définit les longueurs du triangle $ABC$ :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{BC} $$

Idem pour le triangle $ADE$ :

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE}
\qquad \qquad \qquad
f = \abs{DE} $$

et pour le triangle $XYZ$ :

$$ x = \abs{XY}
\qquad \qquad \qquad
y = \abs{XZ}
\qquad \qquad \qquad
z = \abs{YZ} $$

Comme les côtés de $ABC$ et $XYZ$ sont proportionnels, on a le rapport
commun :

$$ \varphi = \frac{x}{a} = \frac{y}{b} = \frac{z}{c} $$

Par construction, les triangles $XYZ$ et $ADE$ ont deux côtés de mêmes
longueurs :

$$ d = x
\qquad \qquad \qquad
e = y $$

On en conclut que :

$$ \frac{d}{a} = \frac{x}{a} = \frac{y}{b} = \frac{e}{b} $$

Les rapports $d/a$ et $e/b$ sont identiques, ce qui signifie que
les triangles $ABC$ et $DEF$ possèdent deux côtés de longueurs
proportionnelles autour d’un angle $\alpha$ de même amplitude. Ils
sont donc semblables :

$$ \psi = \frac{d}{a} = \frac{e}{b} = \frac{f}{c} $$

On a :

$$ \varphi = \frac{x}{a} = \frac{d}{a} = \psi $$

Les rapports $\varphi$ et $\psi$ sont donc égaux, ce qui implique que :

$$ \frac{f}{c} = \frac{z}{c} $$

En simplifiant, on obtient :

$$ f = z $$

c’est-à-dire :

$$ \abs{DE} = \abs{YZ} $$

Les troisièmes côtés des triangles $XYZ$ et $ADE$ sont aussi de même
longueur. Ces triangles sont donc isométriques. Comme les triangles $ABC$
et $ADE$ sont semblables, $ABC$ et $XYZ$ sont également semblables.

Deux triangles qui possèdent trois côtés proportionnels sont des
triangles semblables.

* Théorème de Thalès

#+TOC: headlines 1 local

** Énoncé

Soit deux droites parallèles $(BC)$ et $(DE)$, coupées par deux droites
sécantes $(AD)$ et $(AE)$, tel qu’illustré dans le schéma ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-thales.svg]]

Nous avons tenu compte du parallélisme dans la notation des angles
correspondants.

Les triangles $ABC$ et $ADE$ ont deux angles de mêmes amplitudes $\alpha$
et $\beta$. Ils sont donc semblables :

$$ \varphi
= \frac{\abs{AD}}{\abs{AB}}
= \frac{\abs{AE}}{\abs{AC}}
= \frac{\abs{DE}}{\abs{BC}} $$

Les propriétés des
[[file:triangles.org::#heading:triangles_semblables_differences_de_longueurs][différences
de longueurs]] dans les
[[file:triangles.org::#heading:triangles_semblables][triangles semblables]]
nous donnent :

$$ \rho
= \varphi - 1
= \frac{\abs{BD}}{\abs{AB}}
= \frac{\abs{CE}}{\abs{AC}} $$

et :

$$ \omega
= \frac{\varphi - 1}{\varphi}
= \frac{\abs{BD}}{\abs{AD}}
= \frac{\abs{CE}}{\abs{AE}} $$

** En croix

Soit deux droites parallèles $(BC)$ et $(DE)$, coupées par deux droites
sécantes $(AD)$ et $(AE)$, tel qu’illustré dans le schéma ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-thales-croix.svg]]

Les angles opposés par le sommet sont pris en compte dans la notation,
tout comme le parallélisme dans la notation des angles alternes-internes.

Les triangles $ABC$ et $ADE$ ont deux angles de mêmes amplitudes $\alpha$
et $\beta$. Ils sont donc semblables :

$$ \varphi
= \frac{\abs{AD}}{\abs{AB}}
= \frac{\abs{AE}}{\abs{AC}}
= \frac{\abs{DE}}{\abs{BC}} $$

** Trois parallèles

Soit trois droites parallèles $(BC)$, $(DE)$ et $(FG)$, coupées par
deux droites sécantes $(AF)$ et $(AG)$, tel qu’illustré dans le
schéma ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-thales-trois-paralleles.svg]]

Nous avons tenu compte du parallélisme dans la notation des angles
correspondants.

On définit :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC} $$

$$ c = \abs{BD}
\qquad \qquad \qquad
d = \abs{CE} $$

$$ f = \abs{DF}
\qquad \qquad \qquad
g = \abs{EG} $$

Les triangles $ABC$ et $ADE$ ont deux angles de mêmes amplitudes $\alpha$
et $\beta$. Ils sont donc semblables :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{AE}}{\abs{AC}} = \frac{\abs{DE}}{\abs{BC}} $$

Comme :

$$ \abs{AD} = \abs{AB} + \abs{BD} = a + c $$

on a en particulier :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{a + c}{a} = 1 + \frac{c}{a} $$

En isolant la fraction, on obtient :

$$ \frac{c}{a} = \varphi - 1 $$

Suivons le même raisonnement avec :

$$ \abs{AE} = \abs{AC} + \abs{CE} = b + d $$

et :

$$ \varphi = \frac{\abs{AE}}{\abs{AC}} = \frac{b + d}{b} = 1 + \frac{d}{b} $$

On obtient :

$$ \frac{d}{b} = \varphi - 1 $$

Les triangles $ABC$ et $AFG$ ont deux angles de mêmes amplitudes $\alpha$
et $\beta$. Ils sont donc semblables :

$$ \psi = \frac{\abs{AF}}{\abs{AB}} = \frac{\abs{AG}}{\abs{AC}} = \frac{\abs{FG}}{\abs{BC}} $$

Comme :

$$ \abs{AF} = \abs{AB} + \abs{BD} + \abs{DF} = a + c + f $$

on a en particulier :

$$ \psi
= \frac{\abs{AF}}{\abs{AB}}
= \frac{a + c + f}{a}
= 1 + \frac{c}{a} + \frac{f}{a}
= 1 + \varphi - 1 + \frac{f}{a}
= \varphi + \frac{f}{a} $$

En isolant la fraction, on obtient :

$$ \frac{f}{a} = \psi - \varphi $$

Suivons le même raisonnement avec :

$$ \abs{AG} = \abs{AC} + \abs{CE} + \abs{EG} = b + d + g $$

et :

$$ \psi
= \frac{\abs{AG}}{\abs{AC}}
= \frac{b + d + g}{b}
= 1 + \frac{d}{b} + \frac{g}{b}
= 1 + \varphi - 1 + \frac{g}{b}
= \varphi + \frac{g}{b} $$

On obtient :

$$ \frac{g}{b} = \psi - \varphi $$

On peut réécrire les précédents résultats sous la forme :

$$ c = (\varphi - 1) \ a $$

$$ d = (\varphi - 1) \ b $$

$$ f = (\psi - \varphi) \ a $$

$$ g = (\psi - \varphi) \ b $$

On a donc :

$$ \frac{f}{c}
= \frac{(\psi - \varphi) \ a}{(\varphi - 1) \ a}
= \frac{\psi - \varphi}{\varphi - 1} $$

et :

$$ \frac{g}{d}
= \frac{(\psi - \varphi) \ b}{(\varphi - 1) \ b}
= \frac{\psi - \varphi}{\varphi - 1} $$

Ces deux rapports sont égaux :

$$ \frac{f}{c} = \frac{g}{d} $$

c’est-à-dire :

$$ \frac{\abs{DF}}{\abs{BD}} = \frac{\abs{EG}}{\abs{CE}} $$

** Trois sécantes

Soit deux droites parallèles $(BC)$ et $(DE)$, coupées par trois
droites sécantes $(AE)$, $(AF)$ et $(AG)$, tel qu’illustré dans le
schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-thales-trois-secantes.svg]]

Nous avons tenu compte du parallélisme dans la notation des angles
correspondants.

Les triangles $ABC$ et $AEF$ ont deux angles de mêmes amplitudes $\alpha$
et $\gamma$. Ils sont donc semblables :

$$ \varphi
= \frac{\abs{AE}}{\abs{AB}}
= \frac{\abs{AF}}{\abs{AC}}
= \frac{\abs{EF}}{\abs{BC}} $$

Les triangles $ACD$ et $AFG$ ont deux angles de mêmes amplitudes $\beta$
et $\delta$. Ils sont donc semblables :

$$ \psi
= \frac{\abs{AF}}{\abs{AC}}
= \frac{\abs{AG}}{\abs{AD}}
= \frac{\abs{FG}}{\abs{CD}} $$

Les deux rapports $\varphi$ et $\psi$ sont égaux :

$$ \varphi = \frac{\abs{AF}}{\abs{AC}} = \psi $$

On en déduit que :

$$ \frac{\abs{EF}}{\abs{BC}} = \frac{\abs{FG}}{\abs{CD}} $$

ou :

$$ \frac{\abs{EF}}{\abs{FG}} = \frac{\abs{BC}}{\abs{CD}} $$

** Réciproque

Soit deux droites $(BC)$ et $(DE)$, coupées par deux droites
sécantes $(AD)$ et $(AE)$, tel qu’illustré dans le schéma ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reciproque-theoreme-de-thales.svg]]

Supposons que :

$$ \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{AE}}{\abs{AC}} $$

Les triangles $ABC$ et $ADE$ ont un angle de même amplitude $\alpha$
compris entre deux côtés proportionnels. Ils sont donc semblables et :

$$ \beta = \gamma $$

Comme ces angles correspondants sont égaux, les droites $(BC)$ et $(DE)$
sont parallèles :

$$ (BC) \parallel (DE) $$

* Construction d’un segment de proportionnel

Les triangles semblables donnent une méthode pour construire un segment
de longueur proportionnelle à un segment donné. Soit le segment $[A,B]$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-d-un-segment-proportionnel.svg]]

Supposons que l’on veuille tracer un segment $[A,C]$ de longueur :

$$ \abs{AC} = \frac{7}{4} \ \abs{AB} $$

Il suffit de :

- tracer la droite $d$ passant par $A$
- tracer des points équidistants sur $d$ en partant de $A$ et en allant de $P_1$ à $P_7$
- tracer la droite $f = (P_4 B)$
- tracer la droite $g$, parallèle à $f$ et passant par le point $P_7$

Le point d’intersection :

$$ C = g \cap (AB) $$

délimite le segment $[A,C]$ demandé. En effet, par similarité des
triangles, on a :

$$ \frac{\abs{AC}}{\abs{AB}} = \frac{\abs{AP_7}}{\abs{AP_4}} = \frac{7}{4} $$

* Nombre d’or
:properties:
:custom_id: heading:nombre_d_or
:end:

#+TOC: headlines 1 local

** Rectangle doré

Examinons le rectangle $ABCD$ ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-dore.svg]]

On dit que $ABCD$ est un rectangle doré si on peut le partitionner en :

- un carré $ABFE$
- un rectangle $EFCD$ qui possède la même forme que le rectangle $ABCD$ d’origine

Le rapport de la longueur à la largeur doit donc être le même dans
les rectangles $ABCD$ et $EFCD$ :

$$ \frac{a+b}{a} = \frac{a}{b} $$

c’est-à-dire :

$$ 1 + \frac{b}{a} = \frac{a}{b} $$

En posant :

$$ \phi = \frac{a}{b} $$

l’identité entre les rapports de longueurs devient :

$$ 1 + \unsur{\phi} = \phi $$

En multipliant le tout par $\phi$, on arrive à l’équation :

$$ \phi + 1 = \phi^2 $$

ou encore :

$$ \phi^2 - \phi - 1 = 0 $$

Le rapport de longueurs $\phi$ qui respecte cette équation est appelé
nombre d’or.

** Résolution

Un rapport de longueurs devant être strictement positif, on cherche un
nombre $\phi > 0$ tel que :

$$ \phi^2 - \phi - 1 = 0 $$

Le discriminant de cette équation s’écrit :

$$ \Delta = (-1)^2 - 4 \cdot 1 \cdot (-1) = 5 $$

On en déduit les solutions possibles pour $\phi$ :

$$ \phi_+ = \frac{1+\sqrt{5}}{2} $$

et :

$$ \phi_- = \frac{1-\sqrt{5}}{2} $$

Il faut rejeter la seconde solution, car elle est négative. Le nombre
d’or s’écrit donc :

$$ \phi = \frac{1+\sqrt{5}}{2} $$

** Inverse

Divisons l’équation :

$$ \phi^2 - \phi - 1 = 0 $$

par $\phi$ :

$$ \phi - 1 - \unsur{\phi} = 0 $$

puis isolons $1/\phi$ :

$$ \unsur{\phi} = \phi - 1 $$

Il suffit d’enlever $1$ au nombre d’or pour obtenir son inverse
multiplicatif.

** Carré

L’expression du carré de $\phi$ vient directement de la définition :

$$ \phi^2 = \phi + 1 $$

** Cube

On a :

\begin{align*}
\phi^3
&= \phi \cdot \phi^2 \\
&= \phi \cdot (\phi + 1) \\
&= \phi^2 + \phi \\
&= \phi + 1 + \phi
\end{align*}

et finalement :

$$ \phi^3 = 2 \ \phi + 1 $$

** Inverse du carré

On a :

\begin{align*}
\unsur{\phi^2}
&= (\phi - 1)^2 \\
&= \phi^2 - 2 \ \phi + 1 \\
&= \phi + 1 - 2 \ \phi + 1
\end{align*}

et finalement :

$$ \unsur{\phi^2} = 2 - \phi $$

** Inverse du cube

On a :

\begin{align*}
\unsur{\phi^3}
&= \unsur{\phi} \cdot \unsur{\phi^2} \\
&= (\phi - 1) \ (2 - \phi) \\
&= 2 \ \phi - \phi^2 - 2 + \phi \\
&= 2 \ \phi - \phi - 1 - 2 + \phi \\
\end{align*}

et finalement :

$$ \unsur{\phi^3} = 2 \ \phi - 3 $$

* Nombre d’argent

#+TOC: headlines 1 local

** Résolution

Le nombre d’or respecte l’équation :

$$ \unsur{\phi} = \phi - 1 $$

On définit le nombre d’argent $\psi$ par une équation similaire :

$$ \unsur{\psi} = \psi - 2 $$

En multipliant par $\psi$, on obtient :

$$ 1 = \psi^2 - 2 \ \psi $$

c’est-à-dire :

$$ \psi^2 - 2 \ \psi - 1 = 0 $$

Le discriminant de cette équation s’écrit :

$$ \Delta = 4 - 4 \cdot 1 \cdot (-1) = 8 $$

On en déduit les solutions possibles pour $\psi$ :

$$ \psi_+ = \frac{2 + \sqrt{8}}{2} $$

$$ \psi_- = \frac{2 - \sqrt{8}}{2} $$

Remarquons que :

$$ \sqrt{8} = \sqrt{4 \cdot 2} = \sqrt{4} \cdot \sqrt{2} = 2 \ \sqrt{2} $$

Les solutions deviennent :

$$ \psi_+ = \frac{2 + 2 \ \sqrt{2}}{2} $$

$$ \psi_- = \frac{2 - 2 \ \sqrt{2}}{2} $$

ou encore :

$$ \psi_+ = 1 + \sqrt{2} $$

$$ \psi_- = 1 - \sqrt{2} $$

Comme $\psi$ représente un rapport de longueur, il est forcément positif
et il faut rejeter la seconde solution. Le nombre d’argent s’écrit
donc :

$$ \psi = 1 + \sqrt{2} $$

** Inverse

L’inverse multiplicatif du nombre d’argent est directement issu de sa
définition :

$$ \unsur{\psi} = \psi - 2 $$

** Carré

Le nombre d’argent est la solution positive de l’équation :

$$ \psi^2 - 2 \ \psi - 1 = 0 $$

Il suffit d’isoler $\psi^2$ pour obtenir une expression de son carré :

$$ \psi^2 = 2 \ \psi + 1 $$

** Cube

On a :

\begin{align*}
\psi^3
&= \psi^2 \cdot \psi \\
&= (2 \ \psi + 1) \ \psi \\
&= 2 \ \psi^2 + \psi \\
&= 2 \ (2 \psi + 1) + \psi \\
&= 4 \ \psi + 2 + \psi
\end{align*}

et finalement :

$$ \psi^3 = 5 \ \psi + 2 $$

** Inverse du carré

On a :

\begin{align*}
\unsur{\psi^2}
&= (\psi - 2)^2 \\
&= \psi^2 - 4 \ \psi + 4 \\
&= 2 \ \psi + 1 - 4 \ \psi + 4 \\
\end{align*}

et finalement :

$$ \unsur{\psi^2} = 5 - 2 \ \psi $$

* Nombre de bronze

On définit le nombre de bronze $\varphi$ par l’équation :

$$ \unsur{\varphi} = \varphi - 3 $$

En multipliant par $\varphi$, on obtient :

$$ 1 = \varphi^2 - 3 \ \varphi $$

c’est-à-dire :

$$ \varphi^2 - 3 \ \varphi - 1 = 0 $$

Le discriminant de cette équation s’écrit :

$$ \Delta = 9 - 4 \cdot 1 \cdot (-1) = 13 $$

On en déduit les solutions possibles pour $\varphi$ :

$$ \varphi_+ = \frac{3 + \sqrt{13}}{2} $$

$$ \varphi_- = \frac{3 - \sqrt{13}}{2} $$

Comme $\varphi$ représente un rapport de longueur, il est forcément
positif et il faut rejeter la seconde solution. Le nombre de bronze
s’écrit donc :

$$ \varphi = \frac{1+\sqrt{13}}{2} $$
