
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Proportions géométriques
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles

#+TOC: headlines 1 local

** Triangle rectangle

** Triangle acutangle

** Triangle obtusangle

* Théorème de Thalès sur les proportions

* Triangles semblables

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits semblables si les rapports de leurs côtés
correspondants sont les mêmes, et si leurs angles correspondants de
même amplitude. Le schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables.svg]]

avec :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Corollaires

Soit la relation :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} $$

Multiplions par $a_2 \cdot b_2$ :

$$ a_1 \cdot b_2 = a_2 \cdot b_1 $$

puis divisons par $b_1 \cdot b_2$ :

$$ \frac{a_1}{b_1} = \frac{a_2}{b_2} $$

On obtient par un raisonnement similaire :

$$ \frac{a_1}{c_1} = \frac{a_2}{c_2} $$

$$ \frac{b_1}{c_1} = \frac{b_2}{c_2} $$

Les rapports entre les longueurs des côtés sont les mêmes dans les deux
triangles.

** Conditions pour avoir des triangles semblables

Pour que deux triangles soient semblables, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} $$

- deux angles correspondants sont de même amplitude, par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

Remarquons que, dans ce cas, les troisièmes angles sont forcément
de même amplitude :

$$ \gamma_2 = \pi - \alpha_2 - \beta_2 = \pi - \alpha_1 - \beta_1 = \gamma_1 $$

- deux côtés correspondants sont de longueurs proportionnelles et
  les angles qu’ils forment sont de même amplitude, par exemple :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} $$

et :

$$ \gamma_1 = \gamma_2 $$

*** Triangles rectangles

Dans le cas de deux triangles rectangles $T_1$ et $T_2$, les deux angles
droits correspondent et sont par définition égaux. Il suffit donc
d’avoir un deuxième angle $\alpha$ identique dans les deux triangles
pour que $T_1$ et $T_2$ soient semblables.

* Construction d’un segment de longueur proportionnelle

* Nombre d’or
:properties:
:custom_id: heading:nombre_d_or
:end:

#+TOC: headlines 1 local

** Rectangle doré

Examinons le rectangle $ABCD$ ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-dore.svg]]

On dit que $ABCD$ est un rectangle doré si on peut le partitionner en :

- un carré $ABFE$
- un rectangle $EFCD$ qui possède la même forme que le rectangle $ABCD$ d’origine

Le rapport de la longueur à la largeur doit donc être le même dans
les rectangles $ABCD$ et $EFCD$ :

$$ \frac{a+b}{a} = \frac{a}{b} $$

c’est-à-dire :

$$ 1 + \frac{b}{a} = \frac{a}{b} $$

En posant :

$$ \phi = \frac{a}{b} $$

l’identité entre les rapports de longueurs devient :

$$ 1 + \unsur{\phi} = \phi $$

En multipliant le tout par $\phi$, on arrive à l’équation :

$$ \phi + 1 = \phi^2 $$

ou encore :

$$ \phi^2 - \phi - 1 = 0 $$

Le rapport de longueurs $\phi$ qui respecte cette équation est appelé
nombre d’or.

** Résolution

On cherche un nombre $\phi$ réel positif tel que :

$$ \phi^2 - \phi - 1 = 0 $$

Le discriminant de cette équation s’écrit :

$$ \Delta = (-1)^2 - 4 \cdot 1 \cdot (-1) = 5 $$

On en déduit les solutions possibles pour $\phi$ :

$$ \phi_+ = \frac{1+\sqrt{5}}{2} $$

$$ \phi_- = \frac{1-\sqrt{5}}{2} $$

Comme $\phi$ est un rapport de longueur, il est forcément positif et
il faut rejeter la seconde solution. Le nombre d’or s’écrit donc :

$$ \phi = \frac{1+\sqrt{5}}{2} $$

** Inverse

Divisons l’équation :

$$ \phi^2 - \phi - 1 = 0 $$

par $\phi$ :

$$ \phi - 1 - \unsur{\phi} = 0 $$

puis isolons $1/\phi$ :

$$ \unsur{\phi} = \phi - 1 $$

Il suffit d’enlever $1$ au nombre d’or pour obtenir son inverse
multiplicatif.

** Carré

L’expression du carré de $\phi$ vient directement de la définition :

$$ \phi^2 = \phi + 1 $$

** Cube

On a :

\begin{align*}
\phi^3
&= \phi \cdot \phi^2 \\
&= \phi \cdot (\phi + 1) \\
&= \phi^2 + \phi \\
&= \phi + 1 + \phi
\end{align*}

et finalement :

$$ \phi^3 = 2 \ \phi + 1 $$

** Inverse du carré

On a :

\begin{align*}
\unsur{\phi^2}
&= (\phi - 1)^2 \\
&= \phi^2 - 2 \ \phi + 1 \\
&= \phi + 1 - 2 \ \phi + 1
\end{align*}

et finalement :

$$ \unsur{\phi^2} = 2 - \phi $$

** Inverse du cube

On a :

\begin{align*}
\unsur{\phi^3}
&= \unsur{\phi} \cdot \unsur{\phi^2} \\
&= (\phi - 1) \ (2 - \phi) \\
&= 2 \ \phi - \phi^2 - 2 + \phi \\
&= 2 \ \phi - \phi - 1 - 2 + \phi \\
\end{align*}

et finalement :

$$ \unsur{\phi^3} = 2 \ \phi - 3 $$

* Nombre d’argent

#+TOC: headlines 1 local

** Résolution

Le nombre d’or respecte l’équation :

$$ \unsur{\phi} = \phi - 1 $$

On définit le nombre d’argent $\psi$ par une équation similaire :

$$ \unsur{\psi} = \psi - 2 $$

En multipliant par $\psi$, on obtient :

$$ 1 = \psi^2 - 2 \ \psi $$

c’est-à-dire :

$$ \psi^2 - 2 \ \psi - 1 = 0 $$

Le discriminant de cette équation s’écrit :

$$ \Delta = 4 - 4 \cdot 1 \cdot (-1) = 8 $$

On en déduit les solutions possibles pour $\psi$ :

$$ \psi_+ = \frac{2 + \sqrt{8}}{2} $$

$$ \psi_- = \frac{2 - \sqrt{8}}{2} $$

Remarquons que :

$$ \sqrt{8} = \sqrt{4 \cdot 2} = \sqrt{4} \cdot \sqrt{2} = 2 \ \sqrt{2} $$

Les solutions deviennent :

$$ \psi_+ = \frac{2 + 2 \ \sqrt{2}}{2} $$

$$ \psi_- = \frac{2 - 2 \ \sqrt{2}}{2} $$

ou encore :

$$ \psi_+ = 1 + \sqrt{2} $$

$$ \psi_- = 1 - \sqrt{2} $$

Comme $\psi$ est un rapport de longueur, il est forcément positif et
il faut rejeter la seconde solution. Le nombre d’argent s’écrit donc :

$$ \psi = 1 + \sqrt{2} $$

** Inverse

L’inverse multiplicatif du nombre d’argent est directement issu de sa
définition :

$$ \unsur{\psi} = \psi - 2 $$

** Carré

Le nombre d’argent est la solution positive de l’équation :

$$ \psi^2 - 2 \ \psi - 1 = 0 $$

Il suffit d’isoler $\psi^2$ pour obtenir une expression de son carré :

$$ \psi^2 = 2 \ \psi + 1 $$

** Cube

On a :

\begin{align*}
\psi^3
&= \psi^2 \cdot \psi \\
&= (2 \ \psi + 1) \ \psi \\
&= 2 \ \psi^2 + \psi \\
&= 2 \ (2 \psi + 1) + \psi \\
&= 4 \ \psi + 2 + \psi
\end{align*}

et finalement :

$$ \psi^3 = 5 \ \psi + 2 $$

** Inverse du carré

On a :

\begin{align*}
\unsur{\psi^2}
&= (\psi - 2)^2 \\
&= \psi^2 - 4 \ \psi + 4 \\
&= 2 \ \psi + 1 - 4 \ \psi + 4 \\
\end{align*}

et finalement :

$$ \unsur{\psi^2} = 5 - 2 \ \psi $$

* Nombre de bronze

On définit le nombre de bronze $\varphi$ par l’équation :

$$ \unsur{\varphi} = \varphi - 3 $$

En multipliant par $\varphi$, on obtient :

$$ 1 = \varphi^2 - 3 \ \varphi $$

c’est-à-dire :

$$ \varphi^2 - 3 \ \varphi - 1 = 0 $$

Le discriminant de cette équation s’écrit :

$$ \Delta = 9 - 4 \cdot 1 \cdot (-1) = 13 $$

On en déduit les solutions possibles pour $\varphi$ :

$$ \varphi_+ = \frac{3 + \sqrt{13}}{2} $$

$$ \varphi_- = \frac{3 - \sqrt{13}}{2} $$

Comme $\varphi$ est un rapport de longueur, il est forcément positif et
il faut rejeter la seconde solution. Le nombre de bronze s’écrit donc :

$$ \varphi = \frac{1+\sqrt{13}}{2} $$
