
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Quadrilatères
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un quadrilatère est une figure géométrique délimitée par quatre
segments reliant quatre points pour former un circuit fermé. Chaque
point du circuit est appelé *sommet* du quadrilatère, tandis que chaque
segment est appelé *côté* du quadrilatère.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/quadrilatere.svg]]

Le schéma ci-dessus représente un exemple de quadrilatère de sommets
$A$, $B$ et $C$ délimité par les côtés :

$$ a = [A,B] $$

$$ b = [B,C] $$

$$ c = [C,D] $$

$$ d = [D,A] $$

On définit généralement un quadrilatère par la liste de ces
sommets. Le quadrilatère du schéma ci-dessus est appelé quadrilatère
$ABCD$.

* Rectangle

Un rectangle est un quadrilatère possédant quatre angles droits.

** Dimensions

Un rectangle possède deux grands et deux petits côtés. On nomme :

- longueur du rectangle la longueur de chacun des grands côtés
- largeur du rectangle la longueur de chacun des petits côtés

* Carré

Un rectangle est un quadrilatère possédant quatre angles droits et
quatre côtés de même longueur.

* Aire

** Carré unitaire

Un carré unitaire est un carré dont la longueur du coté vaut 1.

** Définition

L’aire d’une figure géométrique $F$ est le nombre de carrés
unitaires qu’elle peut contenir. On la note :

$$ \aire(F) $$

** Rectangle

*** Dimensions entières

Un rectangle de longueur $m \in \setN$ et de largeur $n \in \setN$ peut
contenir un tableau de carrés unitaire comprenant $m$ lignes et $n$
colonnes. Son aire vaut donc :

$$ m \cdot n $$

par définition de la multiplication dans les nombres naturels.

*** Dimensions rationnelles

Dans le cas où les dimensions du rectangle sont rationnelles, on peut
utiliser une unité secondaire, définie comme une fraction de l’unité
principale. On montre alors que l’aire vaut là aussi le produit des
dimensions du rectangle.

*** Dimensions réelles

Il suffit ensuite de choisir des suites de rationnels et de passer à
la limite vers une longueur $L \in \setR$ et une largeur $h \in \setR$
pour montrer que l’aire $A$ du rectangle vaut :

$$ A = L \ h $$
