
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Quadrilatères
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Définition

Un quadrilatère est une figure géométrique délimitée par quatre
segments reliant quatre points pour former un circuit fermé. Chaque
point du circuit est appelé *sommet* du quadrilatère, tandis que chaque
segment est appelé *côté* du quadrilatère.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/quadrilatere-cotes.svg]]

Le schéma ci-dessus représente un exemple de quadrilatère de sommets
$A$, $B$ et $C$ délimité par les côtés :

$$ a = [A,B] $$

$$ b = [B,C] $$

$$ c = [C,D] $$

$$ d = [D,A] $$

On définit généralement un quadrilatère par la liste de ces
sommets. Le quadrilatère du schéma ci-dessus est appelé quadrilatère
$ABCD$.

** Côtés opposés

Deux côtés non adjacents d’un quadrilatère sont dits opposés. Par
exemple, dans le schéma ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/quadrilatere.svg]]

les côtés $[A,B]$ et $[C,D]$ sont opposés. Il en va de même pour
les côtés $[A,D]$ et $[B,C]$.

** Diagonales

Une diagonale d’un quadrilatère $\mathcal{Q}$ est un segment obtenu en reliant
deux sommets non adjacents de $\mathcal{Q}$.

Par exemple, dans le schéma ci-dessous, les segments $[A,C]$ et $[B,D]$
sont les diagonales du quadrilatère $ABCD$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diagonales-quadrilatere.svg]]

** Médianes

Une médiane d’un quadrilatère $\mathcal{Q}$ est un segment obtenu en reliant
les points situés au milieu de deux côtés opposés de $\mathcal{Q}$.

Par exemple, dans le schéma ci-dessous, les segments $[E,G]$ et $[F,H]$
sont les médianes du quadrilatère $ABCD$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/medianes-quadrilatere.svg]]

* Somme des angles d’un quadrilatère

Un quadrilatère peut toujours se subdiviser en deux triangles : il suffit
de tracer une de ses deux diagonales, comme sur le schéma ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-quadrilatere.svg]]

On remarque que la somme des angles des deux triangles est égal à la
somme des angles du quadrilatère. Comme la somme des angles de chaque
triangle vaut $180^\circ$, la somme des angles du quadrilatère vaut :

$$ 2 \cdot 180^\circ = 360^\circ $$

La somme des angles d’un quadrilatère vaut donc 360°, c’est-à-dire
un angle plein.

* Trapèze

#+TOC: headlines 1 local

** Définition

Un trapèze est un quadrilatère qui possède au moins une paire de côtés
opposés parallèles.

Les côtés parallèles d’un trapèze sont appelées *bases*.

Le schéma ci-dessous représente un trapèze $ABCD$, où les bases sont
les côtés $[A,B]$ et $[C,D]$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze.svg]]

On appelle :

- petite base : la base la plus courte
- grande base : la base la plus longue

** Angles

Le schéma ci-dessous représente un trapèze $ABCD$, avec sa petite
base prolongée :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-angles.svg]]

Nous avons tenu compte dans la notation des angles du parallélisme des
bases, qui implique une égalité des angles alternes-internes.

Comme $\alpha$ et $\delta$ forment ensemble un angle plat, on a :

$$ \delta = 180^\circ - \alpha $$

Comme $\beta$ et $\gamma$ forment ensemble un angle plat, on a :

$$ \gamma = 180^\circ - \beta $$

Les angles adjacents à la petite base sont donc supplémentaires par
rapport aux angles situés du même côté mais adjacents à la grande
base. Notre schéma devient :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-angles-resolu.svg]]

** Hauteur

Une hauteur d’un trapèze est un segment délimité par les deux bases,
et perpendiculaire à celles-ci.

Le schéma ci-dessous représente un trapèze $ABCD$, avec une hauteur
$[E,F]$ perpendiculaire à la petite base, et qui se prolonge jusqu’à
la grande base :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-hauteur.svg]]

La hauteur $[E,F]$ est naturellement aussi perpendiculaire à la grande
base. Sa longueur :

$$ h = \abs{EF} $$

est égale à la distance entre les bases $[A,B]$ et $[C,D]$. Elle ne
dépend donc pas du point $E$ choisi sur la petite base, ni du point $F$.

** Trapèze rectangle

Un trapèze rectangle est un trapèze qui possède au moins un angle
droit. Le parallélisme des bases garantit que ce trapèze possède un
deuxième angle droit.

Le schéma suivant réprésente un trapèze rectangle $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-rectangle.svg]]

Une droite ou segment $x$ perpendiculaire à une autre droite ou segment
$y$ est aussi perpendiculaire à toutes les droites ou segments $z$
parallèles à $y$. Comme on a :

$$ [A,D] \perp [A,B] $$

$$ [A,B] \parallel [C,D] $$

le segment $[A,D]$ est aussi perpendiculaire à $[C,D]$.

** Trapèze isocèle

#+TOC: headlines 1 local

*** Définition

Un trapèze isocèle est un trapèze qui possède deux angles de même
amplitude adjacents à une même base.

Le schéma suivant réprésente un trapèze isocèle $ABCD$, avec deux
angles $\alpha$ identiques, adjacents à la base $[A,B]$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-isocele.svg]]

*** Angles

Le schéma ci-dessous représente un trapèze isocele $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-isocele-angles.svg]]

Nous avons tenu compte des propriétés des angles d’un trapèze dans
la notation.

On constate que si les deux angles adjacents à la grande base sont
égaux, il en va de même pour les deux angles adjacents à la petite
base, et vice versa. Les deux conditions sont donc équivalentes.

*** Longueurs

Le schéma ci-dessous représente un trapèze isocele $ABCD$, où les
deux côtés non bases ont été prolongés :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-isocele-longueurs.svg]]

Nous avons tenu compte, dans la notation des angles, du parallélisme
des bases, qui implique une égalité des angles correspondants.

Le triangle $ABE$ possède deux angles d’amplitudes égale. Il est
donc isocèle et :

$$ \abs{AE} = \abs{BE} $$

Il en va de même pour le triangle $DCE$ :

$$ \abs{DE} = \abs{CE} $$

On a aussi :

$$ \abs{AE} = \abs{AD} + \abs{DE} $$

$$ \abs{BE} = \abs{BC} + \abs{CE} $$

En soustrayant la seconde équation de la première, on obtient :

$$ \abs{AE} - \abs{BE} = \abs{AD} + \abs{DE} - \abs{BC} - \abs{CE} $$

Simplifions en tenant compte des longueurs égales :

$$ 0 = \abs{AD} - \abs{BC} $$

ou encore :

$$ \abs{AD} = \abs{BC} $$

Les côtés non bases d’un trapèze isocèle sont de longueur égale.

*** Condition suffisante

Le schéma ci-dessous représente un trapèze $ABCD$, où les deux
côtés non bases sont de même longueur :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze-isocele-condition-longueurs.svg]]

Les hauteurs passant par les sommets $C$ et $D$ y sont également
représentées.

Nous faisons l’hypothèse que les angles $\alpha$ et $\beta$ sont des
angles aigus.

Les triangles rectangles $AED$ et $FBC$ ont une hypothénuse et une
cathète de longeurs égales :

$$ \abs{AD} = \abs{BC} $$

$$ \abs{DE} = \abs{CF} $$

Ces triangles sont donc isométriques et :

$$ \alpha = \beta $$

Le trapèze $ABCD$ est donc isocèle.

* Parallélogramme

#+TOC: headlines 1 local

** Définition

Un parallélogramme est un quadrilatère qui possède deux paires
de côtés opposés parallèles.

Le schéma ci-dessous représente un parallélogramme $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme.svg]]

On a :

$$ [ A,B ] \parallel [ D,C ] $$

$$ [ A,D ] \parallel [ B,C ] $$

** Côtés

Le schéma ci-dessous représente un parallélogramme $ABCD$ et sa
diagonale $[A,C]$ qui le divise en deux triangles :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-cotes.svg]]

Comme $[A,B]$ est parallèle à $[C,D]$, les angles alternes-internes
$\alpha$ et $\beta$ sont égaux :

$$ \alpha = \beta $$

Comme $[A,D]$ est parallèle à $[B,C]$, les angles alternes-internes
$\gamma$ et $\delta$ sont égaux :

$$ \gamma = \delta $$

Les triangles $ABC$ et $ACD$ ont donc deux angles de mêmes amplitudes
autour d’un côté commun $[A,C]$ qui est forcément de même
longueur. Ces triangles sont donc isométriques. On en déduit que leurs
côtés correspondants sont de mêmes longueurs :

$$ \abs{AB} = \abs{CD} $$

$$ \abs{AD} = \abs{BC} $$

Les côtés opposés d’un parallélogramme sont donc de même longueur :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-cotes-resolu.svg]]

** Angles

Le schéma ci-dessous représente un parallélogramme $ABCD$ et ses
angles :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-angles.svg]]

Comme $[A,B]$ est parallèle à $[C,D]$, on doit avoir :

$$ \alpha + \delta = 180^\circ $$

$$ \beta + \gamma = 180^\circ $$

Comme $[A,D]$ est parallèle à $[B,C]$, on doit avoir :

$$ \alpha + \beta = 180^\circ $$

$$ \gamma + \delta = 180^\circ $$

On en déduit que :

$$ \delta = \beta = 180^\circ - \alpha $$

Le dernier angle vaut :

$$ \gamma = 180^\circ - \beta = 180^\circ - (180^\circ - \alpha) $$

c’est-à-dire :

$$ \gamma = \alpha $$

Un parallélogramme possède donc :

- des angles opposés égaux
- deux angles distincts supplémentaires

comme représenté dans le schéma ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-angles-resolu.svg]]

** Diagonales

Le schéma ci-dessous représente un parallélogramme $ABCD$ et ses
diagonales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-diagonales.svg]]

Nous avons tenu compte, dans la notation des angles, du parallélisme des
côtés opposés, qui implique une égalité des angles alternes-internes.

Les triangles $ABI$ et $DIC$ ont deux angles de mêmes amplitudes
($\alpha$ et $\beta$) autour des côtés $[A,B]$ et $[C,D]$ qui ont une
longueur identique. Ce sont donc des triangles isométriques. On a en
particulier :

$$ \abs{AI} = \abs{IC} $$

Le point d’intersection $I$ est donc situé au milieu de la diagonale
$[A,C]$. On a aussi :

$$ \abs{BI} = \abs{ID} $$

Le point $I$ est donc aussi situé au milieu de la diagonale $[B,D]$.

Notre schéma devient donc :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-diagonales-resolu.svg]]

Les diagonales d’un parallélogramme se coupent en leur milieu.

** Conditions suffisantes

#+TOC: headlines 1 local

*** Côtés opposés de mêmes longueurs

Le schéma ci-dessous représente un quadrilatère $ABCD$ qui possède deux
paires de côtés opposés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-condition-cotes-opposes-de-memes-longueurs.svg]]

On a donc :

$$ \abs{AB} = \abs{DC} $$

$$ \abs{AD} = \abs{BC} $$

Les triangles $ABD$ et $BCD$ ont leurs trois côtés de longueurs égales :

- le côté commun $[B,D]$
- les côtés
  + $[A,B]$ et $[D,C]$
  + $[A,D]$ et $[B,C]$

Ces triangles sont donc isométriques. Les angles alternes-internes
compris entre $[A,B]$ et $[D,C]$ sont donc identiques :

$$ \alpha = \beta $$

Ces côtés sont donc parallèles. Les angles alternes-internes compris
entre $[A,D]$ et $[B,C]$ sont aussi identiques :

$$ \gamma = \delta $$

Ces côtés sont aussi parallèles.

On en conclut que le quadrilatère $ABCD$ est un parallélogramme.

Un quadrilatère qui possède deux paires de côtés de mêmes longueurs
est un parallélogramme.

*** Deux côtés parallèles de même longueur
:properties:
:custom_id: heading:parallelogramme_conditions_suffisantes_deux_cotes_paralleles_de_meme_longueur
:end:

Le schéma ci-dessous représente un quadrilatère $ABCD$, où les
côtés $[A,D]$ et $[B,C]$ sont parallèles et de longueur égale :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-condition-paralleles-meme-longueur.svg]]

Nous avons tenu compte, dans la notation des angles, du parallélisme
de $[A,D]$ et $[B,C]$, qui implique une égalité des angles
alternes-internes.

Les triangles $ABD$ et $DBC$ possédent un angle $\alpha$ de même
amplitude entourés par deux côtés de longueurs égales :

- le côté commun $[B,D]$
- les côtés $[A,D]$ et $[B,C]$

Ces triangles sont donc isométriques. On a en particulier :

$$ \abs{AB} = \abs{DC} $$

Le quadrilatère $ABCD$ possède deux paires de côtés de longueurs
égales. C’est donc un parallélogramme.

Un quadrilatère qui possède une paire de côtés parallèles et de
même longueur est un parallélogramme.

*** Longueur et angle identiques
:properties:
:custom_id: heading:parallelogramme_conditions_suffisantes_longueur_et_angle_identique
:end:

Le schéma ci-dessous représente un quadrilatère $ABCD$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-condition-longueur-angle.svg]]

Ce quadrilatère remplit les conditions suivantes :

- les côtés $[A,D]$ et $[B,C]$ sont de longueur égale
- les côtés $[A,D]$ et $[B,C]$ forment un angle d’amplitude
  égale avec la droite $d$ qui contient le côté $[A,B]$

Comme $\alpha$ et $\beta$ forment un angle plat, on a :

$$ \alpha + \beta = 180^\circ $$

La somme des angles internes à $[A,D]$ et $[B,C]$ et
situés du même côté de $[A,B]$ vaut donc 180°. On peut
appliquer la réciproque du cinquième axiome d’Euclide,
ce qui nous montre que les côtés $[A,D]$ et $[B,C]$ sont
parallèles, en plus d’être de même longueur. Nous avons vu dans la
[[#heading:parallelogramme_conditions_suffisantes_deux_cotes_paralleles_de_meme_longueur][section
éponyme]] que cette condition est suffisante pour montrer que le
quadrilatère $ABCD$ est un parallélogramme.

** Médianes

Le schéma ci-dessous représente un parallélogramme $ABCD$ ainsi que ses
médianes :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-medianes.svg]]

Le quadrilatère $ABFH$ comporte deux côtés opposés parallèles et
de même longueur : $[A,H]$ et $[B,F]$. Ce quadrilatère est donc un
parallélogramme. On en conclut que $[H,F]$ est parallèle à $[A,B]$.

Un raisonnement similaire dans le quadrilatère $HFCD$ nous montre que
$[H,F]$ est parallèle à $[C,D]$.

Le quadrilatère $AEGD$ comporte deux côtés opposés parallèles et
de même longueur : $[A,E]$ et $[D,G]$. Ce quadrilatère est donc un
parallélogramme. On en conclut que $[E,G]$ est parallèle à $[A,D]$.

Un raisonnement similaire dans le quadrilatère $EBCG$ nous montre que
$[E,G]$ est parallèle à $[B,C]$.

Comme :

$$ [H,F] \parallel [A,B] $$

$$ [E,G] \parallel [A,D] $$

on a a fortiori :

$$ [H,I] \parallel [A,E] $$

$$ [E,I] \parallel [A,H] $$

Le quadrilatère $AEIH$ est donc un parallélogramme. Un raisonnement
similaire nous amène à la conclusion que les quatre quadrilatères
intérieurs formés avec les sommets du parallélogrammes et le point
d’intersection des médianes, à savoir :

- $AEIH$
- $EBFI$
- $IFCG$
- $HIGD$

sont aussi des parallélogrammes. Ils ont donc des côtés opposés de
longueurs égales. Le schéma devient :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-medianes-resolu.svg]]

On en déduit que les médianes d’un parallélogramme se coupent en
leur milieu.

** Médianes et diagonales

Le schéma ci-dessous représente un parallélogramme $ABCD$ ainsi
qu’une de ses médianes et une de ses diagonales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-medianes-et-diagonales.svg]]

Nous avons tenu compte, dans la notation des angles, du parallélisme des
côtés opposés, qui implique une égalité des angles alternes-internes.

Les triangles $AEI$ et $ICG$ ont un côté de longueur égale ($[A,E]$
et $[G,C]$) compris entre deux angles $\alpha$ et $\beta$ de mêmes amplitudes

Ce sont donc des triangles isométriques. On a en particulier :

$$ \abs{AI} = \abs{IC} $$

Le point $I$ se trouve au milieu de la diagonale $[A,C]$. Comme les
diagonales d’un parallélogramme se coupent en leur milieu, le point
$I$ se confond avec le point d’intersection des diagonales.

On a aussi :

$$ \abs{EI} = \abs{IG} $$

Le point $I$ se trouve au milieu de la médiane $[E,G]$. Comme les
médianes d’un parallélogramme se coupent en leur milieu, le point $I$
se confond aussi avec le point d’intersection des médianes.

Les médianes et les diagonales d’un parallélogramme se croisent toutes
au même point :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-medianes-et-diagonales-resolu.svg]]

* Rectangle

#+TOC: headlines 1 local

** Définition

Un rectangle est un quadrilatère qui possède quatre angles droits.

Le schéma ci-dessous représente un rectangle $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle.svg]]

** Parallélisme

Le schéma ci-dessous représente un rectangle $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-parallelisme.svg]]

Comme $[A,B]$ et $[D,C]$ sont tous deux perpendiculaire à $[A,C]$, ils
sont parallèles entre-eux :

$$ [A,B] \parallel [D,C] $$

Comme $[A,D]$ et $[B,C]$ sont tous deux perpendiculaire à $[A,B]$, ils
sont parallèles entre-eux :

$$ [A,D] \parallel [B,C] $$

Les côtés opposés d’un rectangle sont donc parallèles entre-eux. On
en déduit qu’un rectangle est un cas particulier de parallélogramme.

** Côtés

Le rectangle étant un cas particulier de parallélogramme, ses côtés
opposés sont de même longueur, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-cotes-resolu.svg]]

On nomme :

- longueur du rectangle la mesure du plus grand côté
  + dans notre schéma, la distance $L = \abs{AB}$
- largeur du rectangle la mesure du plus petit côté
  + dans notre schéma, la distance $l = \abs{AD}$

** Diagonales

Le schéma ci-dessous représente un rectangle $ABCD$  et ses diagonales :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-diagonales.svg]]

Comme un rectangle est un cas particulier de parallélogramme, les
diagonales se coupent en leur milieu.

Les triangles rectangles $ABC$ et $DAB$ ont leurs deux cathètes de
longueurs identiques. Ils sont donc isométriques et :

$$ \abs{AC} = \abs{BD} $$

Les diagonales d’un rectangle sont de même longueur.

Notre schéma devient :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-diagonales-resolu.svg]]

** Conditions suffisantes

#+TOC: headlines 1 local

*** Parallélogramme qui possède un angle droit

Soit un parallélogramme $ABCD$ qui possède au moins un angle droit. Les
angles opposés sont donc égaux, et $ABCD$ contient deux angles distincts
supplémentaires :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-condition-parallelogramme-angle-droit.svg]]

Comme :

$$ 180^\circ - 90^\circ = 90^\circ $$

les quatre angles du parallélogramme sont tous des angles droits.

Un parallélogramme qui possède au moins un angle droit est un rectangle.

*** Longueur et angle identiques

Il s’agit d’un cas particulier
de la configuration que nous avons vu dans la
[[#heading:parallelogramme_conditions_suffisantes_longueur_et_angle_identique][section
éponyme pour les parallélogrammes]], où on montre qu’un quadrilatère
qui possède deux côtés de longueurs égales formant un angle identique
avec un troisième côté est un parallélogramme.

Nous avons ici le cas particulier où les deux angles en question sont des
angles droits, comme le quadrilatère $ABCD$ sur le schéma ci-dessous :

#+attr_html: :width 33%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-condition-longueur-angle.svg]]

Le quadrilatère $ABCD$ est donc un parallélogramme qui contient deux
angles droits. On en conclut qu’il s’agit aussi un rectangle.

Ces conditions suffisent donc à garantir que le quadrilatère $ABCD$ est
un rectangle.

** Médianes

Le schéma ci-dessous représente un rectangle $ABCD$  et ses médianes :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-medianes.svg]]

Comme un rectangle est un cas particulier de parallélogramme,
les médianes se coupent en leur milieu et forment les quatre
parallélogrammes intérieurs suivants :

- $AEIH$
- $EBFI$
- $IFCG$
- $HIGD$

Chacun de ces parallélogrammes contient un angle droit. Ce sont donc
aussi des rectangles.

** Médianes et diagonales

Comme le rectangle est un cas particulier de parallélogramme, ses
médianes et diagonales se croisent au même point :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-medianes-et-diagonales.svg]]

* Cerf-volant

#+TOC: headlines 1 local

** Définition

Un cerf-volant est un quadrilatère formé par deux paires de côtés
adjacents de même longueur.

Le schéma ci-dessous représente un cerf-volant $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cerf-volant.svg]]

** Diagonales

Le schéma ci-dessous représente un cerf-volant $ABCD$ ainsi qu’une de
ses diagonales :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cerf-volant-diagonales-1.svg]]

Les triangles $ACD$ et $ABC$ ont leurs trois côtés de même
longueur. Ils sont donc isométriques. On a en particulier :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Traçons la deuxième diagonale :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cerf-volant-diagonales-2.svg]]

Les triangles $AID$ et $ABI$ ont un angle $\alpha$ d’amplitude égale
compris deux côtés de même longeurs :

- le côté commun $[A,I]$
- les côtés $[A,B]$ et $[A,D]$

Ils sont donc isométriques et :

$$ \abs{DI} = \abs{IB} $$

Le point d’intersection $I$ entre les diagonales est situé au milieu
de la diagonale $[B,D]$, autrement dit au milieu de la diagonale qui
divise le cerf-volant en deux triangles isocèles. On a aussi :

$$ \lambda = \mu $$

Comme ces deux angles forment ensemble un angle plat, il vient :

$$ \lambda + \mu = 2 \ \lambda = 180^\circ $$

d’où :

$$ \lambda = 90^\circ $$

Les diagonales d’un cerf-volant sont perpendiculaires. En tenant compte
de l’égalité des autres angles, notre schéma devient :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cerf-volant-diagonales-resolu.svg]]

Le cerf-volant $ABCD$ est subdivisé en deux triangles isocèles $ABD$
et $CDB$. La diagonale $[A,C]$, qui est perpendiculaire à la séparation
$[B,D]$ entre les triangles isocèles, est la bissectrice des angles
$\angleflex{BAD}$ et $\angleflex{DCB}$. Le segment $[A,I]$ est une hauteur
du triangle $ABD$. Le segment $[C,I]$ est une hauteur du triangle $CDB$.

* Losange

#+TOC: headlines 1 local

** Définition

Un losange est un quadrilatère qui possède quatre côtés de même
longueur.

Le schéma ci-dessous représente un losange $ABCD$ :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange.svg]]

** Parallélisme

Le schéma ci-dessous représente un losange $ABCD$ et une de ses
diagonales :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-parallelisme.svg]]

Nous avons tenu compte du caractère isocèle des triangles dans la
notation des angles.

Les triangles $ABD$ et $BCD$ ont leurs trois côtés de longueurs
identiques. Ils sont donc isométriques et :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Notre schéma devient :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-parallelisme-bis.svg]]

La somme des angles dans le triangle $ABD$ nous donne :

$$ \gamma + 2 \ \alpha = 180^\circ $$

ou encore :

$$ \gamma + \abs{\angleflex{ADC}} = 180^\circ $$

Il suffit d’appliquer la réciproque du cinquième axiome d’Euclide
pour obtenir le parallélisme :

$$ [A,B] \parallel [D,C] $$

La relation sur les angles peut se réécrire :

$$ \gamma + \abs{\angleflex{CBA}} = 180^\circ $$

Il suffit d’appliquer la réciproque du cinquième axiome d’Euclide
pour obtenir le parallélisme :

$$ [A,D] \parallel [B,C] $$

Un losange est donc un cas particulier de parallélogramme.

*Remarque* : on pourrait aussi simplement observer qu’un losange
$\mathscr{L}$ possède a fortiori des côtés opposés de longueurs
égales, ce qui est une condition suffisante pour conclure que
$\mathscr{L}$ est un cas particulier de parallélogramme.

** Diagonales

Le schéma ci-dessous représente un losange $ABCD$ et ses diagonales :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-diagonales.svg]]

Les triangles $ABD$ et $CDB$ possèdent trois côtés de mêmes
longueurs. Ils sont donc isométriques et la droite $(BD)$ est la
bissectrice des angles $\angleflex{ADC}$ et $\angleflex{CBA}$.

Les triangles $ACD$ et $ABC$ possèdent trois côtés de mêmes
longueurs. Ils sont donc isométriques et la droite $(AC)$ est la
bissectrice des angles $\angleflex{BAD}$ et $\angleflex{DCB}$.

Les diagonales d’un losange sont les bissectrices des angles aux
sommets de ce losange.

Comme le losange est un cas particulier de parallélogramme, ses
diagonales se coupent en leur milieu.

Comme le losange est un cas particulier de cerf-volant, ses
diagonales sont perpendiculaires.

** Médianes

Comme un losange est un cas particulier de parallélogramme, ses médianes
se coupent en leur milieu :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-medianes.svg]]

On sait aussi que les quatre quadrilatères intérieurs suivants :

- $AEIH$
- $EBFI$
- $IFCG$
- $HIGD$

sont des parallélogrammes. Comme on a en plus :

$$ \abs{AE} = \abs{AH} = \frac{\abs{AB}}{2} = \frac{\abs{AD}}{2} $$

les quatre côtés du parallélogramme $AEIH$ sont de longueur égale. Ce
parallélogramme est donc aussi un losange. Un raisonnement analogue
appliqué aux autres parallélogrammes intérieurs nous montre que ce
sont tous des losanges.

** Médianes et diagonales

Comme un losange est un cas particulier de parallélogramme, ses médianes
et diagonales se croisent au même point :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-medianes-et-diagonales.svg]]

* Carré

#+TOC: headlines 1 local

** Définition

Un carré est un quadrilatère possédant quatre angles droits et
quatre côtés de même longueur.

Le schéma ci-dessous représente un carré $ABCD$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre.svg]]

C’est donc aussi :

- un rectangle qui possède quatre côtés de même longueur
- un parallélogramme qui possèdes quatre angles droits et quatre côtés de même longueur
- un losange qui possède quatre angles droits
- un cerf-volant qui possède quatre côtés de même longueur et quatre angles droits

** Diagonales

Le schéma ci-dessous représente un carré $ABCD$ et ses diagonales :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre-diagonales.svg]]

Comme un carré est un cas particulier de :

- parallélogramme, ses diagonales se coupent en leur milieu
- rectangle, ses diagonales sont de même longueur
- cerf-volant, ses diagonales sont perpendiculaires

** Médianes

Le schéma ci-dessous représente un carré $ABCD$ et ses médianes :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre-medianes.svg]]

Comme un carré est un cas particulier de :

- parallélogramme, ses médianes se coupent en leur milieu,
  au même point que les diagonales
- rectangle, ses médianes forment quatre rectangles intérieurs
- losange, ses médianes forment quatre losanges intérieurs

Les quatre quadrilatères intérieurs :

- $AEIH$
- $EBFI$
- $IFCG$
- $HIGD$

sont donc à la fois des rectangles et des losanges. Ils ont donc
quatre côtés de longueur égale et quatre angles droits. Ce sont
donc des carrés. On en conclut que les médianes d’un carré sont
perpendiculaires.

** Médianes et diagonales

Comme le carré est un cas particulier de parallélogramme, ses
médianes et diagonales se croisent au même point :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre-medianes-et-diagonales.svg]]

* Constructions

#+TOC: headlines 1 local

** Introduction

Les propriétés des quadrilatères permettent de réaliser facilement
des constructions d’objets géométriques fondamentaux. Nous passons
en revue les principaux.

** Médiatrice

Le schéma ci-dessous illustre la construction de la médiatrice
$m$ du segment $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-mediatrice.svg]]

On définit :

$$ \mathscr{L} = \abs{AB} $$

Voici les étapes de cette méthode de construction :

1. ouvrir le compas d’un rayon $r$ à peu près compris entre
   $2 \ \mathscr{L} / 3$ et $\mathscr{L}$
  - si le rayon est trop près de $\mathscr{L}/2$, les points
    d’intersection vont être très proches, ce qui peut poser un problème
    de précision
2. tracer un arc de cercle $\mathscr{C}_1$ de centre $A$ et de rayon $r$
3. tracer un arc de cercle $\mathscr{C}_2$ de centre $B$ et de rayon $r$
4. on note $D$ et $E$ les deux points d’intersections de
   $\mathscr{C}_1$ et $\mathscr{C}_2$
5. tracer $m = (DE)$

Par construction, on a :

$$ \abs{AD} = \abs{AE} = \abs{BD} = \abs{BE} $$

Le quadrilatère $ODIE$ est donc un losange. Les segments $[A,B]$
et $[D,E]$ sont les diagonales du losange $ODIE$ : ils sont donc
perpendiculaires et se coupent en leur milieu. La droite $m = (DE)$
est bien la médiatrice du segment $[A,B]$

** Bissectrice

Le schéma ci-dessous illustre la construction de la bissectrice
$b$ de l’angle $\angleflex{AOB}$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-bissectrice.svg]]

Voici les étapes de cette méthode de construction :

1. ouvrir le compas d’un rayon $r_1$
2. tracer un arc de cercle $\mathscr{C}_1$ de centre $O$ et de rayon $r_1$
  - soit $D$ l’intersection de la droite $(OA)$ avec $\mathscr{C}_1$
  - soit $E$ l’intersection de la droite $(OB)$ avec $\mathscr{C}_1$
3. ouvrir le compas d’un rayon $r_2$
4. tracer un arc de cercle $\mathscr{C}_2$ de centre $D$ et de rayon $r_2$
5. tracer un arc de cercle $\mathscr{C}_3$ de centre $E$ et de rayon $r_2$
  * le rayon de $\mathscr{C}_3$ est donc le même que celui de $\mathscr{C}_2$
6. soit $I$ l’intersection de $\mathscr{C}_2$ avec $\mathscr{C}_3$
7. tracer $b = (OI)$

Par construction, on a :

$$ \abs{OD} = \abs{OE} $$

$$ \abs{DI} = \abs{EI} $$

Le quadrilatère $ODIE$ est donc un cerf-volant. La diagonale $[O,I]$
est perpendiculaire à la séparation $[D,E]$ entre les deux triangles
isocèles qui composent ce cerf-volant : la droite $b = (OI)$ est bien
la bissectrice de l’angle $\angleflex{DOE} = \angleflex{AOB}$.

** Perpendiculaire à une droite passant par un point donné

Le schéma ci-dessous illustre la construction d’une perpendiculaire
à une droite $d$ passant par le point $P$ :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-perpendiculaire-par-un-point.svg]]

On définit :

$$ \mathscr{L} = \abs{AB} $$

Voici les étapes de cette méthode de construction :

1. ouvrir le compas d’un rayon $R$ supérieur à la distance entre le point
   $P$ et la droite $d$
2. tracer un arc de cercle $\mathscr{C}_1$ de centre $P$ et de rayon $R$
3. on note $A$ et $B$ les deux points d’intersections de
   la droite $d$ avec l’arc de cercle $\mathscr{C}_1$
4. ouvrir le compas d’un rayon $r$ à peu près compris entre
   $2 \ \mathscr{L} / 3$ et $\mathscr{L}$
  - si le rayon est trop près de $\mathscr{L}/2$, les points
    d’intersection vont être très proches, ce qui peut poser un problème
    de précision
5. tracer un arc de cercle $\mathscr{C}_2$ de centre $A$ et de rayon $r$
6. tracer un arc de cercle $\mathscr{C}_3$ de centre $B$ et de rayon $r$
7. on note $D$ et $E$ les deux points d’intersections de
   $\mathscr{C}_2$ et $\mathscr{C}_3$
8. tracer la droite $p = (DE)$
9. on note $F$ le point d’intersection entre $d$ et $p$

Par construction, on a :

$$ \abs{AD} = \abs{AE} = \abs{BD} = \abs{BE} $$

Le quadrilatère $ODIE$ est donc un losange. Les segments $[A,B]$
et $[D,E]$ sont les diagonales du losange $ODIE$ : ils sont donc
perpendiculaires et se coupent en leur milieu. La droite $p = (DE)$
est bien perpendiculaire à la droite $d = (AB)$ et :

$$ \abs{AF} = \abs{FB} $$

De plus, le triangle $PAB$ est isocèle par construction :

$$ \abs{PA} = \abs{PB} $$

La médiane $[P,F]$ est donc aussi une hauteur de ce triangle, et :

$$ [P,F] \perp d $$

Le point $P$ appartient donc à la droite perpendiculaire à $d$ en $F$,
c’est-à-dire à la droite $p$ :

$$ P \in p $$

La droite $p$ est bien la perpendiculaire à $d$ passant par le point $P$.

** Parallèle à une droite passant par un point donné

#+TOC: headlines 1 local

*** Perpendiculaire d’une perpendiculaire

Le schéma ci-dessous illustre la construction d’une parallèle
à une droite $d$ passant par le point $P$ :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-parallele-par-un-point.svg]]

On procède comme suit :

1. tracer la droite $m$, perpendiculaire à $d$ et passant par $P$
2. tracer la droite $n$, perpendiculaire à $m$ et passant par $P$

On définit :

$$ \mathscr{L} = \abs{AB} $$

Voici les étapes détaillées de cette méthode de construction :

1. droite $m$, perpendiculaire à $d$ et passant par $P$
  1) ouvrir le compas d’un rayon $R$ supérieur à la distance entre le point
     $P$ et la droite $d$
  2) tracer un arc de cercle $\mathscr{C}_1$ de centre $P$ et de rayon $R$
  3) on note $A$ et $B$ les deux points d’intersections de
     la droite $d$ avec l’arc de cercle $\mathscr{C}_1$
  4) ouvrir le compas d’un rayon $r$ à peu près compris entre
     $2 \ \mathscr{L} / 3$ et $\mathscr{L}$
  5) tracer un arc de cercle $\mathscr{C}_2$ de centre $A$ et de rayon $r$
  6) tracer un arc de cercle $\mathscr{C}_3$ de centre $B$ et de rayon $r$
  7) on note $D$ et $E$ les deux points d’intersections de
     $\mathscr{C}_2$ et $\mathscr{C}_3$
  8) tracer la droite $m = (DE)$
  9) on note $F$ le point d’intersection entre $d$ et $m$
2. droite $n$, perpendiculaire à $m$ et passant par $P$
  1) ouvrir le compas d’un rayon $s$
  2) tracer un cercle $\mathscr{C}_4$ de centre $P$ et de rayon $s$
  3) on note $G$ et $H$ les deux points d’intersections de
     la droite $m$ avec le cercle $\mathscr{C}_4$
  4) ouvrir le compas d’un rayon $t$
  5) tracer un arc de cercle $\mathscr{C}_5$ de centre $G$ et de rayon $t$
  6) tracer un arc de cercle $\mathscr{C}_6$ de centre $H$ et de rayon $t$
  7) on note $I$ et $J$ les deux points d’intersections de
     $\mathscr{C}_5$ et $\mathscr{C}_6$
  8) tracer la droite $n = (IJ)$

La droite $m$ étant perpendiculaire à $d$ et $n$, on a :

$$ n \parallel d $$

Par construction, $n$ est aussi la médiatrice du segment $[G,H]$. La
droite $n$ passe donc par le milieu de $[G,H]$, c’est-à-dire le
point $P$.

*** Par un cercle
