
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Quadrilatères
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un quadrilatère est une figure géométrique délimitée par quatre
segments reliant quatre points pour former un circuit fermé. Chaque
point du circuit est appelé *sommet* du quadrilatère, tandis que chaque
segment est appelé *côté* du quadrilatère.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/quadrilatere.svg]]

Le schéma ci-dessus représente un exemple de quadrilatère de sommets
$A$, $B$ et $C$ délimité par les côtés :

$$ a = [A,B] $$

$$ b = [B,C] $$

$$ c = [C,D] $$

$$ d = [D,A] $$

On définit généralement un quadrilatère par la liste de ces
sommets. Le quadrilatère du schéma ci-dessus est appelé quadrilatère
$ABCD$.

* Trapèze

Un trapèze est un quadrilatère qui possède au moins une paire de côtés
opposés parallèles.

* Parallélogramme

Un parallélogramme est un quadrilatère qui possède deux paires
de côtés opposés parallèles.

* Losange

UN losange est un parallélogramme qui possède quatre côtés de même
longueur.

* Rectangle

Un rectangle est un parallélogramme qui possède quatre angles droits.

* Carré

Un carré est un quadrilatère possédant quatre angles droits et
quatre côtés de même longueur.

C’est donc aussi :

- un losange qui possède quatre côtés de même longueur
- un rectangle qui possède quatre angles droits
