
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Quadrilatères
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Définition

Un quadrilatère est une figure géométrique délimitée par quatre
segments reliant quatre points pour former un circuit fermé. Chaque
point du circuit est appelé *sommet* du quadrilatère, tandis que chaque
segment est appelé *côté* du quadrilatère.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/quadrilatere.svg]]

Le schéma ci-dessus représente un exemple de quadrilatère de sommets
$A$, $B$ et $C$ délimité par les côtés :

$$ a = [A,B] $$

$$ b = [B,C] $$

$$ c = [C,D] $$

$$ d = [D,A] $$

On définit généralement un quadrilatère par la liste de ces
sommets. Le quadrilatère du schéma ci-dessus est appelé quadrilatère
$ABCD$.

** Diagonales

Une diagonale d’un quadrilatère $\mathcal{Q}$ est un segment obtenu en reliant
deux sommets non adjacents de $\mathcal{Q}$.

Par exemple, dans le schéma ci-dessous, les segments $[A,C]$ et $[B,D]$
sont les diagonales du quadrilatère $ABCD$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diagonales-quadrilatere.svg]]

* Somme des angles d’un quadrilatère

Un quadrilatère peut toujours se subdiviser en deux triangles : il suffit
de tracer une de ses deux diagonales, comme sur le schéma ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-quadrilatere.svg]]

On remarque que la somme des angles des deux triangles est égal à la
somme des angles du quadrilatère. Comme la somme des angles de chaque
triangle vaut $180^\circ$, la somme des angles du quadrilatère vaut :

$$ 2 \cdot 180^\circ = 360^\circ $$

La somme des angles d’un quadrilatère vaut donc 360°, c’est-à-dire
un angle plein.

* Trapèze

#+TOC: headlines 1 local

** Définition

Un trapèze est un quadrilatère qui possède au moins une paire de côtés
opposés parallèles.

Le schéma ci-dessous représente un trapèze $ABCD$, où les côtés
$[A,B]$ et $[C,D]$ sont parallèles :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trapeze.svg]]

* Parallélogramme

#+TOC: headlines 1 local

** Définition

Un parallélogramme est un quadrilatère qui possède deux paires
de côtés opposés parallèles.

Le schéma ci-dessous représente un parallélogramme $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme.svg]]

On a :

$$ [ A,B ] \parallel [ D,C ] $$

$$ [ A,D ] \parallel [ B,C ] $$

** Côtés

Le schéma ci-dessous représente un parallélogramme $ABCD$ et sa
diagonale $[A,C]$ qui le divise en deux triangles :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-cotes.svg]]

Comme $[A,B]$ est parallèle à $[C,D]$, les angles alternes-internes
$\alpha$ et $\beta$ sont égaux :

$$ \alpha = \beta $$

Comme $[A,D]$ est parallèle à $[B,C]$, les angles alternes-internes
$\gamma$ et $\delta$ sont égaux :

$$ \gamma = \delta $$

Les triangles $ABC$ et $ACD$ ont donc deux angles de mêmes amplitudes
autour d’un côté commun $[A,C]$ qui est forcément de même
longueur. Ces triangles sont donc isométriques. On en déduit que leurs
côtés correspondants sont de mêmes longueurs :

$$ \abs{AB} = \abs{CD} $$

$$ \abs{AD} = \abs{BC} $$

Les côtés opposés d’un parallélogramme sont donc de même longueur :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-cotes-resolu.svg]]

** Angles

Le schéma ci-dessous représente un parallélogramme $ABCD$ et ses
angles :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-angles.svg]]

Comme $[A,B]$ est parallèle à $[C,D]$, on doit avoir :

$$ \alpha + \delta = 180^\circ $$

$$ \beta + \gamma = 180^\circ $$

Comme $[A,D]$ est parallèle à $[B,C]$, on doit avoir :

$$ \alpha + \beta = 180^\circ $$

$$ \gamma + \delta = 180^\circ $$

On en déduit que :

$$ \delta = \beta = 180^\circ - \alpha $$

Le dernier angle vaut :

$$ \gamma = 180^\circ - \beta = 180^\circ - (180^\circ - \alpha) $$

c’est-à-dire :

$$ \gamma = \alpha $$

Un parallélogramme possède donc deux angles distincts supplémentaires,
comme représenté dans le schéma ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-angles-resolu.svg]]

** Diagonales

Le schéma ci-dessous représente un parallélogramme $ABCD$ et ses
diagonales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-diagonales.svg]]

Nous avons tenu compte dans la notation des angles du parallélisme des
côtés opposés, qui implique une égalité des angles alternes-internes.

Les triangles $ABI$ et $DIC$ ont deux angles de mêmes amplitudes
($\alpha$ et $\beta$) autour des côtés $[A,B]$ et $[C,D]$ qui ont une
longueur identique. Ce sont donc des triangles isométriques. On a en
particulier :

$$ \abs{AI} = \abs{IC} $$

Le point d’intersection $I$ est donc situé au milieu de la diagonale
$[A,C]$. On a aussi :

$$ \abs{BI} = \abs{ID} $$

Le point $I$ est donc aussi situé au milieu de la diagonale $[B,D]$.

Notre schéma devient donc :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-diagonales-resolu.svg]]

Les diagonales d’un parallélogramme se coupent en leur milieu.

** Conditions suffisantes

#+TOC: headlines 1 local

*** Côtés opposés de mêmes longueurs

Le schéma ci-dessous représente un quadrilatère $ABCD$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-condition-cotes-opposes-de-memes-longueurs.svg]]

Ce quadrilatère possède deux paires de côtés opposés de longueurs
égales :

$$ \abs{AB} = \abs{DC} $$

$$ \abs{AD} = \abs{BC} $$

Les triangles $ABD$ et $BCD$ ont leurs trois côtés de longueurs égales :

- le côté commun $[B,D]$
- les côtés
  + $[A,B]$ et $[D,C]$
  + $[A,D]$ et $[B,C]$

Ces triangles sont donc isométriques. Les angles alternes-internes
compris entre $[A,B]$ et $[D,C]$ sont donc identiques :

$$ \alpha = \beta $$

Ces côtés sont donc parallèles. Les angles alternes-internes compris
entre $[A,D]$ et $[B,C]$ sont aussi identiques :

$$ \gamma = \delta $$

Ces côtés sont aussi parallèles.

On en conclut que le quadrilatère $ABCD$ est un parallélogramme.

Un quadrilatère qui possède deux paires de côtés de mêmes longueurs
est un parallélogramme.

*** Deux côtés parallèles de même longueur
:properties:
:custom_id: heading:parallelogramme_conditions_suffisantes_deux_cotes_paralleles_de_meme_longueur
:end:

Le schéma ci-dessous représente un quadrilatère $ABCD$, où les
côtés $[A,D]$ et $[B,C]$ sont parallèles et de longueur égale :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-condition-paralleles-meme-longueur.svg]]

Nous avons tenu compte dans la notation des angles du parallélisme
de $[A,D]$ et $[B,C]$, qui implique une égalité des angles
alternes-internes.

Les triangles $ABD$ et $DBC$ possédent un angle $\alpha$ de même
amplitude entourés par deux côtés de longueurs égales :

- le côté commun $[B,D]$
- les côtés $[A,D]$ et $[B,C]$

Ces triangles sont donc isométriques. On a en particulier :

$$ \abs{AB} = \abs{DC} $$

Le quadrilatère $ABCD$ possède deux paires de côtés de longueurs
égales. C’est donc un parallélogramme.

Un quadrilatère qui possède une paire de côtés parallèles et de
même longueur est un parallélogramme.

*** Longueur et angle identiques
:properties:
:custom_id: heading:parallelogramme_conditions_suffisantes_longueur_et_angle_identique
:end:

Le schéma ci-dessous représente un quadrilatère $ABCD$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/parallelogramme-condition-longueur-angle.svg]]

Ce quadrilatère remplit les conditions suivantes :

- les côtés $[A,D]$ et $[B,C]$ sont de longueur égale
- les côtés $[A,D]$ et $[B,C]$ forment un angle d’amplitude
  égale avec la droite $d$ qui contient le côté $[A,B]$

Comme $\alpha$ et $\beta$ forment un angle plat, on a :

$$ \alpha + \beta = 180^\circ $$

La somme des angles internes à $[A,D]$ et $[B,C]$ et
situés du même côté de $[A,B]$ vaut donc 180°. On peut
appliquer la réciproque du cinquième axiome d’Euclide,
ce qui nous montre que les côtés $[A,D]$ et $[B,C]$ sont
parallèles, en plus d’être de même longueur. Nous avons vu dans la
[[#heading:parallelogramme_conditions_suffisantes_deux_cotes_paralleles_de_meme_longueur][section
éponyme]] que cette condition est suffisante pour montrer que le
quadrilatère $ABCD$ est un parallélogramme.

** Médianes

* Rectangle

#+TOC: headlines 1 local

** Définition

Un rectangle est un quadrilatère qui possède quatre angles droits.

Le schéma ci-dessous représente un rectangle $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle.svg]]

** Parallélisme

Le schéma ci-dessous représente un rectangle $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-parallelisme.svg]]

Comme $[A,B]$ et $[D,C]$ sont tous deux perpendiculaire à $[A,C]$, ils
sont parallèles entre-eux :

$$ [A,B] \parallel [D,C] $$

Comme $[A,D]$ et $[B,C]$ sont tous deux perpendiculaire à $[A,B]$, ils
sont parallèles entre-eux :

$$ [A,D] \parallel [B,C] $$

Les côtés opposés d’un rectangle sont donc parallèles entre-eux. On
en déduit qu’un rectangle est un cas particulier de parallélogramme.

** Côtés

Le rectangle étant un cas particulier de parallélogramme, ses côtés
opposés sont de même longueur, comme indiqué sur le schéma ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-cotes-resolu.svg]]

On nomme :

- longueur du rectangle la mesure du plus grand côté
  + dans notre schéma, la distance $L = \abs{AB}$
- largeur du rectangle la mesure du plus petit côté
  + dans notre schéma, la distance $l = \abs{AD}$

** Diagonales

Le schéma ci-dessous représente un rectangle $ABCD$  et ses diagonales :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-diagonales.svg]]

Les triangles rectangles $ABC$ et $DAB$ ont leurs deux cathètes de
longueurs identiques. Ils sont donc isométriques et :

$$ \abs{AC} = \abs{BD} $$

Les diagonales d’un rectangle sont de même longueur.

** Médianes

** Conditions suffisantes

#+TOC: headlines 1 local

*** Parallélogramme qui possède un angle droit

Soit un parallélogramme $\mathcal{P}$ qui possède au moins un
angle droit. On sait que $\mathcal{P}$ possède deux angles distincts
supplémentaires, appelons-les $\alpha$ et $\beta$. On peut supposer
sans perte de généralité que l’angle droit est $\alpha$. On a :

$$ \beta = 180^\circ - \alpha = 180^\circ - 90^\circ = 90^\circ $$

Les quatre angles du parallélogramme, à savoir deux angles $\alpha$
et deux angles $\beta$, sont donc tous des angles droits.

On en déduit que $\mathcal{P}$ est aussi un rectangle.

*** Longueur et angle identiques

Il s’agit d’un cas particulier de la
configuration que nous avons vu dans la section où
[[#heading:parallelogramme_conditions_suffisantes_longueur_et_angle_identique][deux
côtés de longueurs égales formant un angle identique avec un
troisième côté]] suffisent à garantir qu’un quadrilatère est
un parallélogramme.

Nous avons ici le cas particulier où les deux angles en question sont des
angles droits, comme le quadrilatère $ABCD$ sur le schéma ci-dessous :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rectangle-condition-longueur-angle.svg]]

Ces conditions suffisent donc à garantir que le quadrilatère $ABCD$ est
un parallélogramme.

* Cerf-volant

#+TOC: headlines 1 local

** Définition

Un cerf-volant est un quadrilatère formé par deux paires de côtés
adjacents de même longueur.

Le schéma ci-dessous représente un cerf-volant $ABCD$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cerf-volant.svg]]

** Diagonales

Le schéma ci-dessous représente un cerf-volant $ABCD$ ainsi qu’une de
ses diagonales :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cerf-volant-diagonales-1.svg]]

Les triangles $ACD$ et $ABC$ ont leurs trois côtés de même
longueur. Ils sont donc isométriques. On a en particulier :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Traçons la deuxième diagonale :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cerf-volant-diagonales-2.svg]]

Les triangles $AID$ et $ABI$ ont un angle $\alpha$ d’amplitude égale
compris deux côtés de même longeurs :

- le côté commun $[A,I]$
- les côtés $[A,B]$ et $[A,D]$

Ils sont donc isométriques et :

$$ \lambda = \mu $$

Comme ces deux angles forment ensemble un angle plat, on a :

$$ \lambda + \mu = 2 \ \lambda = 180^\circ $$

d’où :

$$ \lambda = 90^\circ $$

Les diagonales d’un cerf-volant sont perpendiculaires.

* Losange

#+TOC: headlines 1 local

** Définition

Un losange est un quadrilatère qui possède quatre côtés de même
longueur.

Le schéma ci-dessous représente un losange $ABCD$ :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange.svg]]

** Parallélisme

Le schéma ci-dessous représente un losange $ABCD$ et une de ses
diagonales :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-parallelisme.svg]]

Nous avons tenu compte du caractère isocèle des triangles dans la
notation des angles.

Les triangles $ABD$ et $BCD$ ont leurs trois côtés de longueurs
identiques. Ils sont donc isométriques et :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

Notre schéma devient :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-parallelisme-bis.svg]]

La somme des angles dans le triangle $ABD$ nous donne :

$$ \gamma + 2 \ \alpha = 180^\circ $$

ou encore :

$$ \gamma + \abs{\angleflex{ADC}} = 180^\circ $$

Il suffit d’appliquer la réciproque du cinquième axiome d’Euclide
pour obtenir le parallélisme :

$$ [A,B] \parallel [D,C] $$

La relation sur les angles peut se réécrire :

$$ \gamma + \abs{\angleflex{CBA}} = 180^\circ $$

Il suffit d’appliquer la réciproque du cinquième axiome d’Euclide
pour obtenir le parallélisme :

$$ [A,D] \parallel [B,C] $$

Un losange est donc un cas particulier de parallélogramme.

** Diagonales

Le schéma ci-dessous représente un losange $ABCD$ et ses diagonales :

#+attr_html: :width 37%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/losange-diagonales.svg]]

Comme le losange est un cas particulier de parallélogramme, ses
diagonales se coupent en leur milieu.

Comme le losange est un cas particulier de cerf-volant, ses
diagonales sont perpendiculaires.

* Carré

#+TOC: headlines 1 local

** Définition

Un carré est un quadrilatère possédant quatre angles droits et
quatre côtés de même longueur.

Le schéma ci-dessous représente un carré $ABCD$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre.svg]]

C’est donc aussi :

- un rectangle qui possède quatre côtés de même longueur
- un parallélogramme qui possèdes quatre angles droits et quatre côtés de même longueur
- un losange qui possède quatre angles droits
- un cerf-volant qui possède quatre côtés de même longueur et quatre angles droits

** Diagonales

Le schéma ci-dessous représente un carré $ABCD$ et ses diagonales :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/carre-diagonales.svg]]

Comme un carré est un cas particulier de :

- parallélogramme, ses diagonales se coupent en leur milieu
- rectangle, ses diagonales sont de même longueur
- cerf-volant, ses diagonales sont perpendiculaires

* Distance entre deux droites
