
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Rationnels
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:rationnels}

* Dépendances

  - Chapitre \ref{chap:naturels} : Les nombres naturels
  - Chapitre \ref{chap:entiers} : Les nombres entiers

* Fractions

Soit $a,b \in \setZ$. On aimerait bien généraliser la division
entière de sorte qu'elle soit tout le temps exacte. Comme ce ne sera
en général pas le cas, on contourne le problème en introduisant dans
ce chapitre la notation fractionnaire :

$$\frac{a}{b} = (a,b)$$

où $(a,b) \in \setZ^2$ est appelé nombre rationnel. Le nombre $a$
est appelé le numérateur et $b$ le dénominateur. Ce nouveau concept
de fraction est destiné à généraliser la division entière :

$$a \diventiere b$$

Cette dernière n'étant pas définie lorsque $b = 0$, nous imposerons
comme seule restriction que $b$ soit non nul.

Il ne nous reste plus ensuite qu'à définir convenablement les autres
opérations pour conserver les propriétés intéressantes qu'elles
possèdent sur $\setN$ et $\setZ$.

** Notations

On note aussi les fractions par :

$$a/b = \frac{a}{b}$$

Lorsque $b = 1$, on note plus simplement :

$$a = \frac{a}{1} = (a,1)$$

et donc en particulier :

$$ 1 = 1 / 1 $$

$$ 0 = 0 / 1 $$

$$ -1 = -1 / 1 $$

** Attention

Ne pas confondre les couples $(.,.)$ fractionnaires de ce chapitre avec les couples différentiels du chapitre \ref{chap:entiers} traitant des entiers.


* Produit

La notation fractionnaire étant destinée à représenter une division exacte,
nous devons conserver les propriétés de la division entière dans le cas où
elle est également exacte. Comme on a :

$$(m \diventiere n) \cdot (i \diventiere j) = (m \cdot i) \diventiere (n \cdot j)$$

pour tout $m,n,i,j \in \setZ$ tels que :

$$m \modulo n = i \modulo j = 0$$

on définit le produit entre rationnels par :

$$\frac{a}{b} \cdot \frac{c}{d} = \frac{a \cdot c}{b \cdot d}$$

ou :

$$(a,b) \cdot (c,d) = (a \cdot c, b \cdot d)$$

pour tout $a,b,c,d \in \setZ$ vérifiant $b,d \ne 0$.


** Commutativité

Soit $a,b,c,d \in \setZ$ vérifiant $b,d \ne 0$. On a :

$$\frac{a}{b} \cdot \frac{c}{d} = \frac{a \cdot c}{b \cdot d} = \frac{c \cdot a}{d \cdot b} = \frac{c}{d} \cdot \frac{a}{b}$$

La multiplication entre rationnels est commutative.


** Associativité

Soit $a,b,c,d,e,f \in \setZ$ vérifiant $b,d,f \ne 0$. On a :

$$\frac{a}{b} \cdot \crochets{\frac{c}{d} \cdot \frac{e}{f}} = \frac{a}{b} \cdot \frac{c \cdot e}{d \cdot f} = \frac{a \cdot c \cdot e}{b \cdot d \cdot f}$$

$$\crochets{\frac{a}{b} \cdot \frac{c}{d}} \cdot \frac{e}{f} = \frac{a \cdot c}{b \cdot d} \cdot \frac{e}{f} = \frac{a \cdot c \cdot e}{b \cdot d \cdot f}$$

On en conclut que :

$$\frac{a}{b} \cdot \crochets{\frac{c}{d} \cdot \frac{e}{f}} = \crochets{\frac{a}{b} \cdot \frac{c}{d}} \cdot \frac{e}{f}$$

La multiplication entre rationnels est associative :

$$\frac{a}{b} \cdot \frac{c}{d} \cdot \frac{e}{f} = \frac{a}{b} \cdot \crochets{\frac{c}{d} \cdot \frac{e}{f}} = \crochets{\frac{a}{b} \cdot \frac{c}{d}} \cdot \frac{e}{f}$$


** Neutre multiplicatif

Soit $n \in \setZ$ avec $n \ne 0$. On a :

$$\frac{a}{b} \cdot 1 = \frac{a}{b} \cdot \frac{1}{1} = \frac{a \cdot 1}{b \cdot 1} = \frac{a}{b}$$

Le rationnel $1 = 1 / 1$ est le neutre pour la multiplication. Comme :

$$n \diventiere n = 1$$

on impose que :

$$\frac{n}{n} = \frac{1}{1} = 1$$

Cette contrainte nous donne :

$$\frac{a \cdot n}{b \cdot n} = \frac{a}{b} \cdot \frac{n}{n} = \frac{a}{b} \cdot 1 = \frac{a}{b}$$

pour tout $a,b \in \setZ$ avec $b \ne 0$.


** Équivalence

On voit apparaître les familles :

$$F(a,b) = \left\{ \frac{a \cdot n}{b \cdot n} : n \in \setZ, \ n \ne 0 \right\}$$

où chaque élément de $F(a,b)$ est équivalent à un autre.
Nous noterons donc également :

$$\frac{a}{b} = F(a,b)$$


* Définition

On définit l'ensemble des nombres rationnels par :

$$\setQ = \left\{ \frac{a}{b} : a,b \in \setZ, \ b \ne 0 \right\}$$


** Naturels

Se rappelant que tout $a \in \setZ$ peut s'exprimer comme la soustraction
de deux naturels $i,j$ :

$$a = i - j$$

on arrive à la formulation équivalente :

$$\setQ = \left\{ \frac{i - j}{k - l} : i,j,k,l \in \setN, \ k \ne l \right\}$$


** Inclusion

Nous pouvons associer à tout entier $a$ un rationnel équivalent $(a,1) = a/1$. Pour cette raison, nous dirons que tout entier est également un rationnel, et nous noterons : $\setZ \subseteq \setQ$.


* Inverse

Soit $a,b \in \setZ$ avec $a,b \ne 0$. On a :

$$\frac{a}{b} \cdot \frac{b}{a} = \frac{a \cdot b}{b \cdot a} = 1$$

On dit que $b / a$ est l'inverse de $a / b$ et réciproquement. On le note :

$$\left( \frac{a}{b} \right)^{-1} = \frac{b}{a}$$

** Inverse de l'inverse

On a clairement :

$$\crochets{\left( \frac{a}{b} \right)^{-1}}^{-1} = \crochets{\frac{b}{a}}^{-1} = \frac{a}{b}$$

L'inverse de l'inverse d'une fraction est égal à elle-même.

** Inverse d'un produit

Soit $a,b,c,d \in \setZ \setminus \{ 0 \}$. On a :

$$\frac{a}{b} \cdot \frac{c}{d} \cdot \frac{d}{c} \cdot \frac{b}{a} = \frac{a}{b} \cdot \frac{c \cdot d}{d \cdot c} \cdot \frac{b}{a} = \frac{a}{b} \cdot 1 \cdot \frac{b}{a} = \frac{a}{b} \cdot \frac{b}{a} = \frac{a \cdot b}{b \cdot a} = 1$$

On en conclut que :

$$\frac{d}{c} \cdot \frac{b}{a} = \left( \frac{a}{b} \cdot \frac{c}{d}
\right)^{-1}$$


* Addition


** Dénominateur commun

Soit $a,b,n \in \setZ$ avec $n \ne 0$. On voit que :

$$ \frac{a}{n} + \frac{b}{n}
= \frac{a}{1} \cdot \frac{1}{n} + \frac{b}{1} \cdot \frac{1}{n}
= a \cdot \frac{1}{n} + b \cdot \frac{1}{n} $$

Si on veut conserver la distributivité de la multiplication sur l'addition, on doit donc avoir :

$$\frac{a}{n} + \frac{b}{n} = (a + b) \cdot \frac{1}{n} = \frac{a + b}{n}$$

Pour additionner deux fractions possédant un même dénominateur, il suffit d'additionner les numérateurs.


** Générique

Soit $a,b,c,d \in \setZ$ avec $b,d \ne 0$. Tentons à présent d'obtenir une expression de la somme $(a,b) + (c,d)$. Multipliant la première par $d / d = 1$ et la seconde par $b / b = 1$, il vient :

$$\frac{a}{b} + \frac{c}{d} = \frac{a \cdot d}{b \cdot d} + \frac{c \cdot b}{d \cdot b}$$

Comme les deux fractions du membre de droite ont un même dénominateur, on a finalement :

$$\frac{a}{b} + \frac{c}{d} = \frac{a \cdot d + c \cdot b}{b \cdot d}$$


** Neutre additif

Soit $a,b \in \setZ$ avec $b \ne 0$. On a :

$$\frac{a}{b} + 0 = \frac{a}{b} + \frac{0}{1} = \frac{a \cdot 1 + 0 \cdot b}{b \cdot 1} = \frac{a}{b}$$

Le rationnel :

$$0 = \frac{0}{1}$$

est le neutre pour l'addition. On a aussi :

$$\frac{0}{n} = \frac{0 \cdot n}{1 \cdot n} = \frac{0}{1} = 0$$


* Opposé

Soit $m, n \in \setZ$. On sait que :

$$(-m) \diventiere n = -(m \diventiere n)$$
$$m \diventiere (-n) = - (m \diventiere n)$$
$$(-m) \diventiere (-n) = m \diventiere n$$

A-t-on les même propriétés pour les rationnels ? Soit $a,b \in \setZ$
avec $b \ne 0$. On a :

$$\frac{a}{b} + \frac{-a}{b} = \frac{a - a}{b} = \frac{0}{b} = 0$$

L'opposé de $a/b$ est donc $-a/b$ :

$$-\frac{a}{b} = \frac{-a}{b}$$

On a également :

$$\frac{a}{-b} = \frac{(-1) \cdot a}{(-1) \cdot (-b)} = \frac{-a}{b} = -\frac{a}{b}$$

et :

$$\frac{-a}{-b} = \frac{(-1) \cdot (-a)}{(-1) \cdot (-b)} = \frac{a}{b}$$


* Représentation canonique

Soit un rationnel $x \in \setQ$ et des entiers $a,b \in \setZ$ vérifiant
$b \ne 0$ et :

$$x = \frac{a}{b}$$

Si $b \strictsuperieur 0$, on pose :

$$m = a$$
$$n = b$$

et on a :

$$x = \frac{m}{n}$$

avec $n \strictsuperieur 0$. Si $b \strictinferieur 0$, on pose :

$$m = -a$$
$$n = -b$$

et on a :

$$x = \frac{a}{b} = \frac{-a}{-b} = \frac{m}{n}$$

avec $n \strictsuperieur 0$. On peut donc toujours se ramener à la représentation
canonique :

$$x = \frac{m}{n}$$

où $m,n \in \setZ$ et $n \strictsuperieur 0$.


* Soustraction

Soit $a,b,c,d \in \setZ$ avec $b,d \ne 0$. On définit :

$$\frac{a}{b} - \frac{c}{d} = \frac{a}{b} + \frac{-c}{d} = \frac{a \cdot d - c \cdot b}{b \cdot d}$$


* Ordre

Soit $a,b,c,d \in \setZ$ avec $b,d \ne 0$. Nous allons étendre l'ordre sur l'ensemble
des rationnels en imposant que la multiplication par un nombre strictement
positif conserve l'ordre et que la multiplication par un nombre strictement
négatif l'inverse. Soit l'inégalité :

$$\frac{a}{b} \le \frac{c}{d}$$


  - Supposons que $b,d \ge 0$. En multipliant par $b \cdot d \strictsuperieur 0$,
on voit que l'inégalité est équivalente à :

$$a \cdot d \le c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \le c \cdot b$$

  - Supposons que $b \le 0$ et $d \ge 0$. On a $b \cdot d \strictinferieur 0$
et l'inégalité est équivalente à :

$$a \cdot d \ge c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \ge c \cdot b$$

  - Supposons que $b \ge 0$ et $d \le 0$. On a $b \cdot d \strictinferieur 0$
et l'inégalité est équivalente à :

$$a \cdot d \ge c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \ge c \cdot b$$

  - Supposons que $b,d \le 0$, on a
$b \cdot d = (-b) \cdot (-d) \strictsuperieur 0$ et l'inégalité
est équivalente à :

$$a \cdot d \le c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \le c \cdot b$$



** Positifs et négatifs

On définit les ensembles des rationnels positifs et négatifs par :

$$\setQ^+ = \{ x \in \setQ : x \ge 0 \}$$

$$\setQ^- = \{ x \in \setQ : x \le 0 \}$$

Soit un rationnel $x$ sous la forme canonique :

$$x = \frac{a}{b}$$

Si $x$ est négatif :

$$x = \frac{a}{b} \le 0 = \frac{0}{1}$$

on a par définition :

$$a \cdot 1 \le 0 \cdot b = 0$$

autrement dit :

$$a \le 0$$

Invérsément, si $x$ est positif :

$$x = \frac{a}{b} \ge 0 = \frac{0}{1}$$

on a par définition :

$$a \cdot 1 \ge 0 \cdot b = 0$$

autrement dit :

$$a \ge 0$$


** Invariance sous multiplication

Soit les rationnels $x,y,z$ sous forme canonique :

$$x = \frac{a}{b}$$

$$y = \frac{c}{d}$$

$$z = \frac{e}{f}$$

avec $a,b,c,d,e,f \in \setZ$ et $b,d,f \strictsuperieur 0$. On suppose que
$z \ge 0$, c'est-à-dire :

$$e \ge 0$$

et que :

$$x \le y$$

c'est-à-dire :

$$a \cdot d \le c \cdot b$$

L'ordre entre entiers est conservé par la multiplication
de l'entier positif $e \cdot f$ :

$$a \cdot e \cdot d \cdot f \le  c \cdot e \cdot b \cdot f$$

Par définition de l'ordre entre rationnels, on en déduit que :

$$\frac{a \cdot e}{b \cdot f} \le \frac{c \cdot e}{d \cdot f}$$

c'est-à-dire :

$$x \cdot z \le y \cdot z$$

L'ordre entre rationnels est conservé sous la multiplication d'un
rationnel positif.


** Invariance sous addition

Soit les rationnels $x,z,u,v$ sous forme canonique :

$$x = \frac{a}{b}$$

$$y = \frac{c}{d}$$

$$u = \frac{e}{f}$$

$$v = \frac{g}{h}$$

On suppose que :

$$x \le y$$
$$u \le v$$

c'est-à-dire :

$$\frac{a}{b} \le \frac{c}{d}$$

$$\frac{e}{f} \le \frac{g}{h}$$

ou :

$$a \cdot d \le c \cdot b$$

$$e \cdot h \le g \cdot f$$

L'ordre entre entiers étant conservé sous la multiplication
de $f \cdot h \strictsuperieur 0$, on a :

$$a \cdot d \cdot f \cdot h \le c \cdot b \cdot f \cdot h$$

L'ordre entre entiers étant conservé sous la multiplication
de $b \cdot d \strictsuperieur 0$, on a :

$$e \cdot h \cdot b \cdot d \le g \cdot f \cdot b \cdot d$$

L'ordre entre entiers étant conservé sous l'addition, on a :

$$a \cdot d \cdot f \cdot h + e \cdot h \cdot b \cdot d \le c \cdot b \cdot f \cdot h + g \cdot f \cdot b \cdot d$$

En utilisant la distributivité, on en déduit que :

$$(a \cdot f + e \cdot b) \cdot d \cdot h \le (c \cdot h + g \cdot d) \cdot b \cdot f$$

ou, par définition de l'ordre entre rationnels :

$$\frac{a \cdot f + e \cdot b}{b \cdot f} \le \frac{c \cdot h + g \cdot d}{d \cdot h}$$

qui n'est rien d'autre que :

$$\frac{a}{b} + \frac{e}{f} \le \frac{c}{d} + \frac{g}{h}$$

c'est-à-dire :

$$x + u \le y + v$$

L'ordre entre rationnels est conservé sous l'addition.


** Invariance sous soustraction

Soit les rationnels $x,z,u,v$ tels que :

$$x \le y$$
$$u \ge v$$

En ajoutant :

$$(-u)+(-v) \ge (-u)+(-v)$$

à la seconde inégalité, on obtient :

$$u + (-u) + (-v) \ge v + (-u) + (-v)$$

qui se simplifie en :

$$-v \ge -u$$

ou :

$$-u \le -v$$

On a donc :

$$x + (-u) \le y + (-v)$$

c'est-à-dire :

$$x - u \le y - v$$


* Signe

La fonction signe est définie par :

$$ \signe(x) = \begin{cases}
1 & \text{ si } x \ge 0 \\
-1 & \text{ si } x \strictinferieur 0
\end{cases} $$

pour tout $x \in \setQ$

* Valeur absolue

Soit $x \in \setQ$. On définit la valeur absolue de $x$ par :

$$\left| x \right| = \max \{ x , -x \}$$

* Notation décimale

Soit les tuples :

$$(i_0,...,i_m) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^{m + 1}$$

et :

$$(j_1,...,j_n) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^n$$

La notation décimale associée est définie par :

$$i_m ... i_0, j_1 ... j_n = i_0 + ... + i_m \cdot 10^m + j_1 \cdot \frac{1}{10} + ... + j_n \cdot \frac{1}{10^n}$$

pour les rationnels positifs et :

$$i_m ... i_0, j_1 ... j_n = -\left(i_0 + ... + i_m \cdot 10^m + j_1
\cdot \frac{1}{10} + ... + j_n \cdot \frac{1}{10^n} \right)$$

pour les rationnels négatifs. Exemple :

$$-7512,34 = -\left( 2 + 1 \cdot 10 + 5 \cdot 10^2 + 7 \cdot 10^3 + 3
\cdot \frac{1}{10} + 4 \cdot \frac{1}{10^2} \right)$$


* Division

Soit $x,y \in \setQ$ et $a,b,c,d \in \setZ$ avec $b,c,d \ne 0$ et :

$$x = \frac{a}{b}$$

$$y = \frac{c}{d}$$

On dit que $q \in \setQ$ est la division de $x$ par $y$ et on le note :

$$\frac{x}{y} = q$$

si :

$$x = q \cdot y$$

Multipliant par $y^{-1}$, on a bien sur :

$$q = x \cdot y^{-1} = \frac{a}{b} \cdot \frac{d}{c}$$

La division de deux fractions s'écrit donc simplement :

$$\frac{x}{y} = \frac{a/b}{c/d} = \frac{a}{b} \cdot \frac{d}{c}$$


* Puissance

Soit $m,n \in \setN$ et $a,b \in \setZ$. Les puissances positives s'étendent facilement aux fractions :

$$\left( \frac{a}{b} \right)^n = \frac{a}{b} \cdot ... \cdot \frac{a}{b} = \frac{a^n}{b^n}$$

On définit de plus les puissances négatives par :

$$\left( \frac{a}{b} \right)^{-n} = \left( \frac{b}{a} \right)^n$$

Mais comme un produit d'inverses est égal à l'inverse des produits, on a également :

$$\left( \frac{a}{b} \right)^{-n} = \left( \frac{a^n}{b^n} \right)^{-1}$$


** Somme en exposant

Soit $x \in \setQ$. On vérifie que :

$$x^{m + n} = x^m \cdot x^n$$

$$x^{m - n} = x^m \cdot x^{-n} = \frac{x^m}{x^n}$$

$$x^{-m + n} = x^{-m} \cdot x^n = \frac{x^n}{x^m}$$

$$x^{-m - n} = x^{-m} \cdot x^{-n} = \frac{1}{x^m \cdot x^n}$$

On a donc bien :

$$x^{i + j} = x^i \cdot x^j$$

pour tout $i,j \in \setZ$.


* Carré

Le carré est la deuxième puissance d'un nombre :

$$x^2 = x \cdot x$$


** Positivité

Soit $x \in \setQ$. Si $x \ge 0$, on pose $p = x$. On a donc $p \ge 0$.
La multiplication par un rationnel positif ne modifiant pas l'ordre, on a :

$$p^2 = p \cdot p \ge 0 \cdot p = 0$$

Le carré est donc également positif :

$$x^2 = p^2 \ge 0$$

Si $x \le 0$, on pose $p = -x$. On a donc $p \ge 0$.
On voit que $x = -p$ et que :

$$x^2 = (-p)^2 = (-p) \cdot (-p) = p \cdot p = p^2 \ge 0$$

On a donc :

$$x^2 \ge 0$$

pour tout $x \in \setQ$.


** Ordre

Soit $x,y \in \setQ$ vérifiant :

$$x,y \ge 0$$

et :

$$x \le y$$

Comme $x \ge 0$, l'inégalité $x \le y$ est conservée sous
la multiplication par $x$ :

$$x^2 = x \cdot x \le y \cdot x$$

Comme $y \ge 0$, l'inégalité $x \le y$ est conservée sous
la multiplication par $y$ :

$$x \cdot y \le y \cdot y = y^2$$

En rassemblant ces résultats, il vient :

$$x^2 \le y \cdot x = x \cdot y \le y^2$$

on a donc :

$$x^2 \le y^2$$

La fonction $f : x \mapsto x^2$ est croissante sur l'ensemble des
rationnels positifs.


** Binôme

Soit $x,y \in \setZ$. En utilisant la distributivité, on obtient :

$$(x + y)^2 = (x + y) \cdot (x + y) = x \cdot (x + y) + y \cdot (x + y)$$

En l'utilisant une seconde fois, on arrive à :

$$(x + y)^2 = x \cdot x + x \cdot y + y \cdot x + y \cdot y$$

En utilisant la commutativité, on arrive au développement :

$$(x + y)^2 = x^2 + x \cdot y + x \cdot y + y^2$$

que l'on peut réexprimer comme :

$$(x + y)^2 = x^2 + 2 \cdot x \cdot y + y^2$$


*** Différence

On a :

$$(x - y)^2 = (x + (-y))^2 = x^2 + 2 \cdot x \cdot (-y) + y^2$$

et donc :

$$(x - y)^2 = x^2 - 2 \cdot x \cdot y + y^2$$


* Corps

$(\setQ,+,\cdot)$ est un corps commutatif.

* Densité

Soit le rationnel $\epsilon \in \setQ$ vérifiant $\epsilon \strictsuperieur 0$
exprimé sous la forme canonique :

$$\epsilon = \frac{m}{n}$$

avec $m,n \in \setZ$ et $n \strictsuperieur 0$. Comme $\epsilon$ est
strictement positif, on a :

$$m \strictsuperieur 0$$

Existe-t-il un rationnel intermédiaire $\delta$ vérifiant :

$$0 \strictinferieur \delta \strictinferieur \epsilon$$

Posons :

$$\delta = \frac{m}{2 \ n}$$

Il est clair que $\delta \strictsuperieur 0$. On a :

$$n \strictinferieur 2 \ n$$

En multipliant par $m \strictsuperieur 0$, on obtient :

$$m \cdot n \strictinferieur m \cdot 2 \cdot n$$

Par définition de l'ordre sur les rationnels, cette inégalité
est équivalente à :

$$\delta = \frac{m}{2 \ n} \strictinferieur \frac{m}{n} = \epsilon$$

On en conclut que :

$$0 \strictinferieur \delta \strictinferieur \epsilon$$


** Rationnels distincts

Soit les rationnels $x,y$ vérifiant :

$$x \strictinferieur y$$

On pose :

$$\epsilon = y - x \strictsuperieur 0$$

On peut trouver un rationnel $\delta$ tel que :

$$0 \strictinferieur \delta \strictinferieur \epsilon$$

En additionnant cette inégalité avec :

$$x \le x \le x$$

on arrive à :

$$x \strictinferieur x + \delta \strictinferieur x + \epsilon$$

Soit :

$$z = x + \delta$$

Comme :

$$x + \epsilon = x + y - x = y$$

on a :

$$x \strictinferieur z \strictinferieur y$$

On peut toujours trouver un rationnel strictement compris
entre deux rationnels distincts.


