
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Structures algèbriques
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:algebre}

* Dépendances

  - Chapitre \ref{chap:operations} : Les opérations

* Monoïde

Soit un ensemble $M$ sur lequel est défini une opération $\opera$.
On dit que le couple $(M,\opera)$ est un monoïde si $\opera$ est associative.


** Nomenclature

Lorsque l'opération $\opera$ est évidente d'après le contexte, on dit
simplement que $M$ est un monoïde.


* Groupes

Soit un ensemble $G$ sur lequel est défini une opération $\opera$.
On dit que le couple $(G,\opera)$ est un groupe si :

  - $\opera$ est associative
  - Il existe un neutre pour $\opera$
  - Chaque élément de $G$ possède un inverse pour $\opera$


** Nomenclature

Lorsque l'opération $\opera$ est évidente d'après le contexte, on dit
simplement que $G$ est un groupe.


** Commutatif

Si $\opera$ est également commutative, on dit que $(G,\opera)$ est un
groupe abélien ou commutatif.


* Monoïde et groupe

Soit un monoïde $(G,\opera)$ tel qu'il existe un neutre à droite $n \in G$
pour $\opera$ et que chaque élément $x \in G$ admet un inverse à droite
$x^\inverse$ pour $\opera$ :

$$x \opera x^\inverse = n$$

Soit :

$$y = x^\inverse \opera x$$

En utilisant l'associativité de $\opera$, on se rend compte que :

$$y = x^\inverse \opera n \opera x = x^\inverse \opera x \opera x^\inverse \opera x = y \opera y$$

En utilisant ce résultat, on obtient :

$$y = y \opera n = y \opera y \opera y^\inverse = y \opera y^\inverse = n$$

Donc :

$$x^\inverse \opera x = n$$

et $x^\inverse$ est un inverse de $x$. On a aussi :

$$n \opera x = x \opera x^\inverse \opera x = x \opera n = x$$

L'élément $n$ est donc l'unique neutre de $G$ et tout élément $x \in G$
admet un inverse. On en conclut que le couple $(G,\opera)$ est un groupe.


* Anneaux

Soit un ensemble $A$ sur lequel sont définies les opérations
$\autreaddition$, appelée addition, et l'opération
$\autremultiplication$, appelée multiplication. On dit que le tuple
$(A,\autreaddition,\autremultiplication)$ est un anneau si :

  - L'addition est commutative et associative
  - Il existe un neutre pour l'addition
  - Chaque élément de $A$ possède un inverse pour l'addition appelé opposé
  - La multiplication est associative
  - La multiplication se distribue sur l'addition

** Nomenclature

Lorsque les opérations sont évidentes d'après le contexte, on dit simplement
que $A$ est un anneau.

** Anneau unitaire

Si la multiplication admet également un neutre, on dit que $A$ est un
anneau unitaire.

** Anneau commutatif

Un anneau $A$ est dit commutatif si la multiplication y est commutative.

** Notations

Soit un anneau $A$. L'addition de $x,y \in A$ est généralement notée :

$$x + y$$

La multiplication est généralement notée :

$$x \cdot y$$

On désigne généralement par $0$ le neutre pour l'addition :

$$x + 0 = 0 + x = x$$

Si l'anneau $A$ est unitaire, on désigne généralement par $1$ le neutre
pour la multiplication :

$$x \cdot 1 = 1 \cdot x = x$$

L'inverse de $x$ pour l'addition, aussi nommé opposé, est noté $-x$ :

$$x + (-x) = (-x) + x = 0$$


** Intègre

Soit un anneau $(A,+,\cdot)$. Si la relation :

$$a \cdot b = 0$$

implique :

$$a = 0 \ \text{ ou } \ b = 0$$

on dit que $(A,+,\cdot)$ est un anneau intègre.


* Corps

Soit un ensemble $K$ sur lequel sont définies les
opérations $\autreaddition$, appelée addition, et l'opération
$\autremultiplication$, appelée multiplication. On dit que le tuple
$(K,\autreaddition,\autremultiplication)$ est un corps si :

- L'addition est commutative et associative
- Il existe un neutre pour l'addition
- Chaque élément de $K$ possède un inverse pour l'addition appelé opposé
- La multiplication est associative
- Il existe un neutre pour la multiplication
- Chaque élément de $K$, à l'exception du neutre pour l'addition,
  possède un inverse pour la multiplication appelé inverse
- La multiplication se distribue sur l'addition

** Nomenclature

Lorsque les opérations sont évidentes d'après le contexte,
on dit simplement que $K$ est un corps.

** Corps commutatif

Un corps commutatif, on champ algébrique, est un corps dans lequel
la multiplication est commutative.

** Symbole

On utilise souvent le symbole $\corps$ pour désigner un corps
générique.


** Commutatif

Si la multiplication est également commutative, on parle de corps commutatif.


** Notations

Soit un corps $K$. L'addition de $x,y \in K$ est notée :

$$x + y$$

La multiplication est notée :

$$x \cdot y$$

On désigne généralement par $0$ le neutre pour l'addition :

$$x + 0 = 0 + x = x$$

et par $1$ le neutre pour la multiplication :

$$x \cdot 1 = 1 \cdot x = x$$

L'inverse de $x$ pour l'addition, aussi nommé opposé, est noté $-x$ :

$$x + (-x) = (-x) + x = 0$$

et l'inverse de $x$ pour la multiplication est noté $x^{-1}$ ou $1/x$ :

$$x \cdot x^{-1} = x^{-1} \cdot x = 1$$

* Soustraction et division

Lorsque l'addition est définie et que $b$ possède un opposé $-b$, on définit
généralement l'opération de soustraction par :

$$a - b = a + (-b)$$

Lorsque la multiplication est définie et que $b$ dispose d'un inverse $b^{-1}$,
on définit généralement l'opération de division par :

$$\frac{a}{b} = a \cdot b^{-1}$$

On note aussi :

$$a / b = \frac{a}{b}$$


* Les puissances

On définit généralement les puissances positives par :

\begin{align}
x^0 &= 1 \)

\(
x^k &= x \cdot x^{k - 1}
\end{align}

pour tout $k \in \setN$. Si l'inverse de $x$ existe, on définit généralement
les puissances négatives par :

$$x^{-k} = (x^{-1})^k$$

pour tout $k \in \setN$.


* Somme d'ensembles

Soit l'ensemble $\Omega$ sur lequel est définie une opération d'addition.
On définit la somme de deux sous-ensembles $A,B \subseteq \Omega$ par :

$$A + B = \{ x + y : (x,y) \in A \times B \}$$

** Somme directe

Si, pour tout $s \in S$, il existe un et un seul couple $(x,y) \in A \times B$
tel que $s = x + y$, on dit que $S$ est la somme directe de $A$ et $B$ et
on le note :

$$S = A \bigoplus B$$


* Multiplication mixte

Soit l'ensemble $\Omega$ sur lequel est définie une opération de
multiplication. On définit la multiplication de $\lambda \in \Omega$
et de $A \subseteq \Omega$ par :

$$\lambda \cdot A = \{ \lambda \cdot x : x \in A \}$$


