
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Suites
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

\label{chap:suites}

* Dépendances

  - Chapitre \ref{chap:limites} : Les limites

* Définition

Une suite est une fonction $\mathcal{S} : \setN \mapsto \Omega$ définie par :

$$ \mathcal{S} : n \mapsto s_n = \mathcal{S}(n) $$

pour tout $n \in \setN$. On note $\suitek(\Omega)$ l'ensemble
des suites $\mathcal{S} : \setN \mapsto \Omega$.

La notation conventionnelle d’une suite est :

$$ (s_n)_{n \in \setN} = (\mathcal{S} : n \mapsto s_n) $$

ou même :

$$ (s_n)_n = (s_n)_{n \in \setN} $$

* Limite

On dit qu'une suite $\mathcal{S} : n \mapsto s_n \in \Omega$ converge
vers $L \in \Omega$ au sens de la distance $\distance$, ou que $L$
est sa limite à l'infini :

$$L = \lim_{n \to \infty} s_n$$

si, pour toute précision $\epsilon > 0$ aussi petite que l'on veut,
on peut trouver un naturel $K(\epsilon)$ à partir duquel l'erreur
sera au moins aussi faible que demandée. On a donc :

$$\distance(L,s_n) \le \epsilon$$

pour tout $n \ge K(\epsilon)$.

** Notation

Comme la limite d'une suite est toujours sous-entendue vers l'infini,
on note :

$$\lim_n s_n = \lim_{n \to \infty} s_n$$

* Limites extrémales

On définit :

$$\limsup_{n \to \infty} s_n = \lim_{n \to \infty} \sup \{ s_m : m \in \setN, \ m \ge n \}$$

$$\liminf_{n \to \infty} s_n = \lim_{n \to \infty} \inf \{ s_m : m \in \setN, \ m \ge n \}$$


** Notation

On note aussi :

$$\limsup_n s_n = \limsup_{n \to \infty} s_n$$

$$\liminf_n s_n = \liminf_{n \to \infty} s_n$$


* Équivalence

Soit les suites :

$$\mathcal{S} : n \mapsto s_n \in \Omega$$

et :

$$\mathcal{T} : n \mapsto t_n \in \Omega$$

On dit que $s$ est équivalente à $t$, et on le note :

$$s \equiv t$$

si et seulement si la limite de la distance entre les deux suites converge
vers zéro :

$$\lim_{n \to \infty} \distance(s_n,t_n) = 0$$

Quelque soit $\epsilon \strictsuperieur 0$, on peut donc trouver un
naturel $K(\epsilon)$ tel que :

$$\distance(s_n,t_n) \le \epsilon$$

pour tout $n \ge K(\epsilon)$.

*Remarque* : l'équivalence entre $\mathcal{S}$ et $\mathcal{T}$
n'implique nullement que la limite de $\mathcal{S}$ ou de $\mathcal{T}$
existe.

** Existence des limites

Suppons que :

$$ (s_n)_{n \in \setN} \equiv (t_n)_{n \in \setN} $$

et que la limite :

$$\sigma = \lim_{n \to \infty} s_n$$

existe. On a :

$$\distance(\sigma,t_n) \le \distance(\sigma,s_n) + \distance(s_n,t_n)$$

Soit $\epsilon \strictsuperieur 0$. En choisissant $K_1$ tel que :

$$\distance(\sigma,s_n) \le \frac{\epsilon}{2}$$

pour tout $n \ge K_1$ et $K_2$ tel que :

$$\distance(s_n,t_n) \le \frac{\epsilon}{2}$$

pour tout $n \ge K_2$, on voit que :

$$\distance(\sigma,t_n) \le \frac{\epsilon}{2} + \frac{\epsilon}{2} = \epsilon$$

Cette relation étant valable quel que soit $\epsilon \strictsuperieur 0$,
on en déduit que la limite des $t_n$ existe et que :

$$\lim_{n \to \infty} t_n = \sigma = \lim_{n \to \infty} s_n$$

Les limites de suites équivalentes sont identiques.

* Ordre

Soit les suites :

$$\mathcal{S} : n \mapsto s_n \in \Omega$$

et :

$$\mathcal{T} : n \mapsto t_n \in \Omega$$

Si un ordre est défini sur $\Omega$, on dit que $\mathcal{S}$ est
inférieure à $\mathcal{T}$ :

$$ \mathcal{S} \le  \mathcal{T} $$

si et seulement si les éléments de $\mathcal{S}$ sont inférieurs aux
éléments de $\mathcal{T}$ :

$$s_n \le t_n$$

pour tout $n \in \setN$.

* Monotonie

#+TOC: headlines 1 local

** Croissance

On dit qu'une suite :

$$\mathcal{S} : n \mapsto s_n \in \Omega$$

est croissante si :

$$s_m \le s_n$$

pour tout $m,n \in \setN$ tels que $m \le n$.

** Décroissance

On dit qu'une suite :

$$\mathcal{S} : n \mapsto s_n \in \Omega$$

est décroissante si :

$$s_m \le s_n$$

pour tout $m,n \in \setN$ tels que $m \ge n$.

* Opérations

#+TOC: headlines 1 local

** Définition

Soit les suites :

$$\mathcal{S} : n \mapsto s_n \in \Omega$$

et :

$$\mathcal{T} : n \mapsto t_n \in \Omega$$

Pour toute opération $\opera$ définie sur $\Omega$, on définit
l'opération induite $\opera : \suitek(\Omega) \times \suitek(\Omega)
\mapsto \suitek(\Omega)$ par :

$$(\mathcal{S} \opera \mathcal{T})(n) = s_n \opera t_n$$

pour tout $n \in \setN$. On note aussi :

$$(s \opera t)_n = (\mathcal{S} \opera \mathcal{T})(n)$$

** Usuelles

Sur les ensembles où sont définies les opérations usuelles,
on aura l'addition :

$$(s + t)_n = s_n + t_n$$

la multiplication :

$$(s - t)_n = s_n - t_n$$

la soustraction :

$$(s \cdot t)_n = s_n \cdot t_n$$

la division :

$$\left[ \frac{s}{t} \right]_n = \frac{s_n}{t_n}$$

pour tout $n \in \setN$.

* Cauchy

#+TOC: headlines 1 local

** Définition

On dit qu'une suite :

$$ \mathcal{S} : n \mapsto s_n \in \Omega $$

est de Cauchy si, pour toute précision $\epsilon > 0$ aussi petite que
l'on veut, on peut trouver un naturel $K(\epsilon)$ à partir duquel
la distance entre deux éléments de la suite sera aussi petite que
demandée. On a donc :

$$\distance(s_m,s_n) \le \epsilon$$

pour tout $m,n \ge K(\epsilon)$.

** Suite convergente

Toute suite convergente vers une limite :

$$L = \lim_{n \to \infty} s_n \in \Omega$$

est de Cauchy. En effet, soit $\epsilon \strictsuperieur 0$. Si on choisit
$K$ tel que :

$$\distance(L,s_n) \le \epsilon / 2$$

pour tout $n \ge K$, on a :

$$\distance(s_m,s_n) \le \distance(s_m,L) + \distance(L,s_n) = \frac{\epsilon}{2} + \frac{\epsilon}{2} = \epsilon$$

pour tout $m,n \ge K$.

* Ensemble complet

#+TOC: headlines 1 local

** Définition

On dit qu'un ensemble $X$ est complet si toute suite de Cauchy inclue
dans $X$ converge vers une limite $L \in X$.

** Complétion

On peut compléter tout ensemble $A$ incomplet en créant un ensemble
$X$ tel que tout $x \in X$ soit associé à une suite de Cauchy :

$$ \mathcal{S} : n \mapsto s_n \in A $$

On note alors symboliquement :

$$x = \lim_{n \to \infty} s_n$$
