
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Transformations géométriques planes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Une transformation plane $\mathscr{T}$ dans un plan $\Theta$ est une
fonction $\mathscr{T} : \Theta \mapsto \Theta$ qui, à chaque point $P
\in \Theta$, associe un point image $\mathscr{T}(P)$.

* Translation

Une translation utilise un même vecteur pour faire glisser chaque point
du plan d’un point origine vers une destination.

Le schéma ci-dessous donne un exemple de translation d’un point $A$
en utilisant un vecteur $\vecteur{v} = \vecteur{XY}$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/translation.svg]]

Pour procéder à la translation d’un point $A$ par un vecteur $\vecteur{v}$ :

1. on trace une droite $d$ parallèle au segment $[X,Y]$ associé à $\vecteur{v}$
2. en partant du point $A$, on trace une copie du vecteur $\vecteur{v} = \vecteur{AB}$
   sur la droite $d$ en veillant à ce que
  - la longueur $\abs{AB}$ soit égale à $\abs{XY}$
  - le sens de progression $[A \to B]$ soit le même que celui de $[X \to Y]$
3. le point $B$ obtenu est l’image de $A$ par la translation de vecteur $\vecteur{v}$

* Rotation

Une rotation fait tourner chaque point du plan d’un même angle autour
d’un même centre.

Le schéma ci-dessous donne un exemple de rotation d’un point $A$
par un angle $\alpha$ autour d’un centre $O$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rotation.svg]]

La convention usuelle du signe des angles s’applique :

- un angle positif fait tourner le point dans le sens anti-horlogique
- un angle négatif fait tourner le point dans le sens horlogique

Pour procéder à la rotation d’un point $A$ autour du centre $O$
par un angle $\alpha$ :

1. on trace la droite $OA$
2. on trace un arc de cercle $\Gamma$ de centre $O$
3. on repère sur $\Gamma$ le point $B$ tel que $\abs{\anglecirc{AOB}} = \alpha$

* Symétrie centrale

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-centrale.svg]]

* Réflexion

alias : symétrie orthogonale

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reflexion.svg]]

* Homothétie

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/homothetie.svg]]

* Image d’une figure

#+TOC: headlines 1 local

** Segment

Pour tracer l’image d’un segment, il suffit de relier entre-elles les
images de chaque extrémité du segment original.

** Polygone

Pour tracer l’image d’un polygone, il suffit de relier entre-elles les
images de chaque côté du polygone original.
