
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Transformations géométriques planes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Définition

Une transformation plane $\mathscr{T}$ dans un plan $\Theta$ est une
fonction $\mathscr{T} : \Theta \mapsto \Theta$ qui, à chaque point $P
\in \Theta$, associe un point image $\mathscr{T}(P)$.

** Segment

Pour tracer l’image d’un segment, il suffit de relier entre-elles les
images de chaque extrémité du segment original.

** Polygone

Pour tracer l’image d’un polygone, il suffit de tracer les images
des segments (côtés) du polygone original.

* Translation

#+TOC: headlines 1 local

** Point

Une translation utilise un même vecteur pour faire glisser chaque point
du plan d’un point origine vers une destination.

Le schéma ci-dessous donne un exemple de translation $\mathcal{T}$
d’un point $A$ en utilisant un vecteur $\vecteur{v} = \vecteur{XY}$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/translation.svg]]

Pour procéder à la translation d’un point $A$ par un vecteur $\vecteur{v}$ :

1. on trace une droite $d$ parallèle au segment $[X,Y]$ associé à $\vecteur{v}$
2. en partant du point $A$, on trace une copie du vecteur $\vecteur{v} = \vecteur{AB}$
   sur la droite $d$ en veillant à ce que
  - la longueur $\abs{AB}$ soit égale à $\abs{XY}$
  - le sens de progression $[A \to B]$ soit le même que celui de $[X \to Y]$
3. le point $B = \mathcal{T}(A)$ obtenu est l’image de $A$ par la translation
   de vecteur $\vecteur{v}$

** Segment

Soit une translation $\mathcal{T}$ de vecteur $\vecteur{v}$. Le schéma
ci-dessous représente un segment $[A,B]$ et son image $[\mathcal{T}(A),
\mathcal{T}(B)]$ par la translation $\mathcal{T}$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/translation-segment.svg]]

* Rotation

#+TOC: headlines 1 local

** Point

Une rotation fait tourner chaque point du plan d’un même angle autour
d’un même centre.

Le schéma ci-dessous donne un exemple de rotation $\mathcal{R}$ d’un
point $A$, qui tourne d’un angle $\alpha$ autour d’un centre $O$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rotation.svg]]

La convention usuelle du signe des angles s’applique :

- un angle positif fait tourner le point dans le sens anti-horlogique
- un angle négatif fait tourner le point dans le sens horlogique

Pour procéder à la rotation d’un point $A$ autour d’un centre $O$
par un angle $\alpha$ :

1. on trace la droite $OA$
2. on trace un arc de cercle $\Gamma$ de centre $O$
3. on repère sur $\Gamma$ le point $B$ tel que $\abs{\anglecirc{AOB}} = \alpha$
4. le point $B = \mathcal{R}(A)$ obtenu est l’image de $A$ par la rotation
   de centre $O$ et d’angle $\alpha$

** Segment

* Symétrie centrale

Une symétrie centrale projette un point quelconque du plan de l’autre
côté et à la même distance d’un centre donné.

Le schéma ci-dessous donne un exemple de symétrie centrale d’un
point $A$ autour d’un centre $O$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-centrale.svg]]

Pour procéder à la symétrie centrale d’un point $A$ autour d’un
centre $O$ :

1. on trace la droite $OA$
2. on reporte la distance $r = \abs{OA}$ de l’autre côté de $O$ pour
   obtenir le point $B$
  - on a donc $\abs{OA} = \abs{OB}$
3. le point $B$ obtenu est l’image de $A$ par la symétrie centrale de
   centre $O$

Cette transformation est équivalente à une rotation de centre $O$ et
d’angle égal à 180°, comme nous le montre le schéma ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-centrale-et-rotation.svg]]

* Réflexion

Une réflexion, ou symétrie orthogonale, projette un point quelconque
du plan de l’autre côté d’une droite donnée, appelée axe de
la réflexion. La projection se fait perpendiculairement à l’axe,
et à la même distance.

Le schéma ci-dessous donne un exemple de réflexion d’un point $A$
autour de l’axe $d$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/reflexion.svg]]

Pour procéder à la réflexion d’un point $A$ autour d’un axe $d$ :

1. on trace la droite $p$, perpendiculaire à $d$ et qui passe par $A$
  - soit $I$, le point d’intersection entre $d$ et $p$
2. on repère le point $B$, tel que $\abs{AI} = \abs{IB}$
3. le point $B$ obtenu est l’image de $A$ par la réflexion d’axe $d$

* Homothétie

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/homothetie.svg]]
