
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Transformations géométriques planes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Une transformation plane $\mathscr{T}$ dans un plan $\Theta$ est une
fonction $\mathscr{T} : \Theta \mapsto \Theta$ qui, à chaque point $P
\in \Theta$, associe un point image $\mathscr{T}(P)$.

* Segment orienté
:properties:
:custom_id: heading:segment_oriente
:end:

#+TOC: headlines 1 local

** Définition

Un segment orienté est un segment auquel on donne un sens de progression,
d’une extrémité du segment vers l’autre. Dans cet ouvrage, je note :

$$ [A \to B] $$

un segment orienté $[A,B]$ progressant de $A$ vers $B$.

Le schéma ci-dessous représente un exemple de segment orienté $[A
\to B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/segment-oriente.svg]]

** Caractéristiques

Un segment orienté $[A \to B]$ est caractérisé par :

- les points $A$ et $B$, extrémités du segment
- une longueur $\abs{AB}$
- une droite $(AB)$ dans laquelle il est inclus, qui donne sa direction
- un sens de progression de $A$ vers $B$

** Équivalence

On considère que deux segments orientés $[A \to B]$ et $[C \to D]$ sont
équivalents si :

- ils ont la même longueur : $\abs{AB} = \abs{CD}$
- ils ont la même direction : la droite $(AB)$ est parallèle à la droite $(CD)$
- ils ont un même sens de progression : les segments $[A,C]$ et $[B,D]$ ne se croisent pas

Le schéma ci-dessous représente deux segments orientés équivalents
$[A \to B]$ et $[C \to D]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/segments-orientes-sans-croisement.svg]]

On voit que les segments $[A,C]$ et $[B,D]$ ne se croisent pas : les
sens de progression sont donc identiques.

Par contre, dans le schéma ci-dessous, les segments orientés
$[E \to F]$ et $[G \to H]$ ne sont pas équivalents :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/segments-orientes-avec-croisement.svg]]

En effet, les segments $[E,G]$ et $[F,H]$ se croisent, ce qui signifie
que les sens de progressions sont opposés.

* Vecteur géométrique
:properties:
:custom_id: heading:vecteur_geometrique
:end:

Un vecteur géométrique est une classe d’équivalence de segments
orientés : on considère que des segments orientés équivalents
entre-eux représentent le même vecteur.

Le vecteur associé au segment $[A \to B]$ est noté :

$$ \vecteur{AB} $$

Le segment orienté $[A \to B]$, ainsi que toutes ses copies par
translation, sont donc considèrés comme des représentants du vecteur
$\vecteur{AB}$.

Comme tous les segments orientés équivalents à $[A \to B]$ sont
caractérisés par :

- une même longueur
- une même direction
- un même sens de progression

un vecteur $\vecteur{AB}$ est entièrement déterminé par les mêmes
caractéristiques.

* Translation

#+TOC: headlines 1 local

** Point

** Segment

* Rotation

#+TOC: headlines 1 local

** Introduction

** Point

** Segment

** Symétrie centrale

* Réflexion

#+TOC: headlines 1 local

alias : symétrie orthogonale

** Point

** Segment

* Homothétie

#+TOC: headlines 1 local

** Point

** Segment

