
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Transformations géométriques planes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

#+TOC: headlines 1 local

** Définition

Une transformation plane $\mathscr{T}$ dans un plan $\Theta$ est une
fonction $\mathscr{T} : \Theta \mapsto \Theta$ qui, à chaque point $P
\in \Theta$, associe un point image $\mathscr{T}(P)$.

** Segment

Pour tracer l’image d’un segment, il suffit de relier entre-elles les
images de chaque extrémité du segment original.

** Polygone

Pour tracer l’image d’un polygone, il suffit de tracer les images
des segments (côtés) du polygone original.

* Translation

#+TOC: headlines 1 local

** Point

Une translation utilise un même vecteur pour faire glisser chaque point
du plan d’un point origine vers une destination.

Le schéma ci-dessous donne un exemple de translation $\mathcal{T}$
de vecteur $\vecteur{v} = \vecteur{XY}$ appliquée à un point $A$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/translation.svg]]

Pour appliquer une translation $\mathcal{T}$ de vecteur $\vecteur{v}$
à un point $A$ :

1. on trace une droite $d$ parallèle au segment $[X,Y]$ associé à $\vecteur{v}$
2. en partant du point $A$, on trace une copie du vecteur $\vecteur{v} = \vecteur{AB}$
   sur la droite $d$ en veillant à ce que
  - la longueur $\abs{AB}$ soit égale à $\abs{XY}$
  - le sens de progression $[A \to B]$ soit le même que celui de $[X \to Y]$
3. le point $B = \mathcal{T}(A)$ obtenu est l’image de $A$ par la translation
   de vecteur $\vecteur{v}$

** Segment

Soit une translation $\mathcal{T}$ de vecteur $\vecteur{v}$. Le schéma
ci-dessous représente un segment $[A,B]$ et son image $[C,D]$ par
$\mathcal{T}$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/translation-segment.svg]]

* Rotation

#+TOC: headlines 1 local

** Point

Une rotation fait tourner chaque point du plan d’un même angle autour
d’un même centre.

Le schéma ci-dessous donne un exemple de rotation $\mathcal{R}$ de
centre $O$ et d’angle $\alpha$, appliquée à un point $A$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rotation.svg]]

La convention usuelle du signe des angles s’applique :

- un angle positif fait tourner le point dans le sens anti-horlogique
- un angle négatif fait tourner le point dans le sens horlogique

Pour appliquer une rotation $\mathcal{R}$ de centre $O$ et d’angle
$\alpha$ à un point $A$ :

1. on trace la droite $OA$
2. on trace un arc de cercle $\Gamma$ de centre $O$
3. on repère sur $\Gamma$ le point $B$ tel que $\abs{\angleflex{AOB}} = \alpha$
4. le point $B = \mathcal{R}(A)$ obtenu est l’image de $A$ par la rotation
   de centre $O$ et d’angle $\alpha$

** Segment

Soit une rotation $\mathcal{R}$ de centre $O$ et d’angle $\alpha$.
Le schéma ci-dessous représente un segment $[A,B]$ et son image $[C,D]$
par $\mathcal{R}$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/rotation-segment.svg]]

* Symétrie centrale

#+TOC: headlines 1 local

** Point

Une symétrie centrale projette un point quelconque du plan de l’autre
côté et à la même distance d’un centre donné.

Le schéma ci-dessous donne un exemple de symétrie centrale $\mathcal{S}$
de centre $O$ appliquée à un point $A$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-centrale.svg]]

Pour appliquer une symétrie centrale $\mathcal{S}$ de centre $O$ à un
point $A$ :

1. on trace la droite $OA$
2. on reporte la distance $r = \abs{OA}$ de l’autre côté de $O$ pour
   obtenir le point $B$
  - on a donc $\abs{OA} = \abs{OB}$
3. le point $B = \mathcal{S}(A)$ obtenu est l’image de $A$
   par la symétrie centrale de centre $O$

*** Équivalence

Cette transformation est équivalente à une rotation de centre $O$ et
d’angle égal à 180°, comme nous le montre le schéma ci-dessous :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-centrale-et-rotation.svg]]

** Segment

Soit une symétrie centrale $\mathcal{S}$ de centre $O$. Le schéma
ci-dessous représente un segment $[A,B]$ et son image $[C,D]$ par
$\mathcal{S}$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-centrale-segment.svg]]

* Symétrie orthogonale

#+TOC: headlines 1 local

** Point

Une symétrie orthogonale, ou réflexion, projette un point quelconque
du plan de l’autre côté d’une droite donnée, appelée axe de
la symétrie orthogonale. La projection se fait perpendiculairement à
l’axe, et à la même distance.

Le schéma ci-dessous donne un exemple de symétrie orthogonale
$\mathcal{S}$ d’axe $d$ appliquée à un point $A$ :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-orthogonale.svg]]

Pour appliquer une symétrie orthogonale d’axe $d$ à un point $A$ :

1. on trace la droite $p$, perpendiculaire à $d$ et qui passe par $A$
  - soit $I$, le point d’intersection entre $d$ et $p$
2. on reporte la distance $\abs{AI}$ de l’autre côté de $d$, obtenant ainsi le point $B$
  - on a alors $\abs{AI} = \abs{IB}$
3. le point $B = \mathcal{S}(A)$ obtenu est l’image de $A$ par la symétrie orthogonale d’axe $d$

** Segment

Soit une symétrie orthogonale $\mathcal{S}$ d’axe $d$. Le schéma
ci-dessous représente un segment $[A,B]$ et son image $[C,D]$ par
$\mathcal{S}$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/symetrie-orthogonale-segment.svg]]

* Homothétie

#+TOC: headlines 1 local

** Point

Une homothétie multiplie la distance du point d’origine par rapport
à un centre donné. On appelle rapport de l’homothétie le ratio de
distance utilisé.

Le schéma ci-dessous donne un exemple d’homothétie $\mathcal{H}$
de centre $O$ et de rapport $R = 4$ appliquée à un point $A$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/homothetie.svg]]

Pour appliquer une homothétie de centre $O$ et de rapport $R$ à un
point $A$ :

1. on trace la droite $d = OA$
2. on multiplie la distance $\abs{OA}$ par $R$ pour obtenir la distance $D$
3. on reporte la distance $D$ sur la droite $OA$, obtenant ainsi le point $B$
  - on a donc : $\abs{OB} = D = R \ \abs{OA}$
4. le point $B = \mathcal{H}(A)$ obtenu est l’image de $A$ par l’homothétie $\mathcal{H}$

** Rapport négatif

Par convention, un rapport de distance négatif envoie le point image
de l’autre côté du centre. Le schéma ci-dessous donne un exemple
d’homothétie $\mathcal{H}$ de centre $O$ et de rapport $R = -4$
appliquée à un point $A$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/homothetie-rapport-negatif.svg]]

Le rapport de longueurs s’écrit alors :

$$ \abs{OB} = \abs{R} \cdot \abs{OA} $$

*** Symétrie centrale

On peut voir une symétrie centrale comme une homothétie de rapport $-1$.

** Segment

Soit une homothétie $\mathcal{H}$ de centre $O$ et de rapport $R =
3$. Le schéma ci-dessous représente un segment $[A,B]$ et son image
$[C,D]$ par $\mathcal{H}$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/homothetie-segment.svg]]

* Isométrie

#+TOC: headlines 1 local

** Définition

Une isométrie est une transformation du plan qui conserve les longueurs
et les angles.

*** Longueurs suffisantes

Si une transformation $\mathscr{I}$ conserve les longueurs,
l’image d’un triangle $T_1$ est un triangle $T_2$ qui a des
côtés correspondants de même longueur. Les deux triangles sont donc
isométriques, ce qui implique que leurs angles correspondants sont de
même amplitude. Comme nous n’avons fait aucune hypothèse sur les
angles de départ, on en conclut que la transformation $\mathscr{I}$
conserve aussi bien les angles que les longueurs : c’est donc une
isométrie.

La condition de conservation des longueurs est donc suffisante pour
avoir une isométrie.

** Translation

Le schéma ci-dessous représente un segment $[A,B]$ et son image $[C,D]$
par une translation $\mathcal{T}$ de vecteur $\vecteur{v}$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/isometrie-translation.svg]]

Comme les segments orientés $[A \to C]$ et $[B \to D]$ sont des
représentants du même vecteur $\vecteur{v}$, ils sont de même
longueur :

$$ \abs{AC} = \abs{BD} $$

Ces segments sont aussi parallèles, ce qui implique que les angles
alternes-internes $\alpha$ et $\beta$ sont de même amplitude :

$$ \alpha = \beta $$

Les triangles $ABC$ et $BDC$ ont donc :

- un angle correspondant de même amplitude : $\alpha$ et $\beta$
- un côté commun $[B,C]$ qui est forcément de même longueur
- un autre côté correspondant de même longueur : $[A,C]$ et $[B,D]$

Comme l’angle de même amplitude est compris entre les côtés de
mêmes longueurs, les triangles $ABC$ et $BDC$ sont isométriques.

Ce résultat implique que la longueur du segment d’origine est égale
à la longueur du segment image :

$$ \abs{AB} = \abs{CD} $$

Toute translation est donc une isométrie.

** Rotation

Le schéma ci-dessous représente un segment $[A,B]$ et son image $[C,D]$
par une rotation $\mathcal{R}$ de centre $O$ et d’angle $\theta$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/isometrie-rotation.svg]]

Par construction de la rotation, on a :

$$ \abs{OA} = \abs{OC} $$

$$ \abs{OB} = \abs{OD} $$

Au niveau des angles, on a :

$$ \alpha + \theta = \theta + \beta $$

En simplifiant les $\theta$, cette relation devient :

$$ \alpha = \beta $$

Les triangles $OAB$ et $OCD$ ont donc un angle correspondant de même
amplitude ($\alpha = \beta$) compris entre deux côtés correspondants
de mêmes longueurs :

$$ \abs{OA} = \abs{OC} $$

$$ \abs{OB} = \abs{OD} $$

Les triangles $OAB$ et $OCD$ sont donc isométriques. Ce résultat
implique que la longueur du segment d’origine est égale à la longueur
du segment image :

$$ \abs{AB} = \abs{CD} $$

Toute rotation est donc une isométrie.

** Symétrie centrale

Le schéma ci-dessous représente un segment $[A,B]$ et son image $[C,D]$
par une symétrie centrale $\mathcal{S}$ de centre $O$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/isometrie-symetrie-centrale.svg]]

Par construction de la symétrie centrale, on a :

$$ \abs{OA} = \abs{OC} $$

$$ \abs{OB} = \abs{OD} $$

Les angles $\alpha$ et $\beta$ sont opposés par le sommet :

$$ \alpha = \beta $$

Les triangles $OAB$ et $OCD$ ont donc un angle correspondant de même
amplitude ($\alpha = \beta$) compris entre deux côtés correspondants
de mêmes longueurs :

$$ \abs{OA} = \abs{OC} $$

$$ \abs{OB} = \abs{OD} $$

Les triangles $OAB$ et $OCD$ sont donc isométriques. Ce résultat
implique que la longueur du segment d’origine est égale à la longueur
du segment image :

$$ \abs{AB} = \abs{CD} $$

Toute symétrie centrale est donc une isométrie.

** Symétrie orthogonale

Nous avons déjà utilisé la symétrie orthogonale
pour justifier le fait que les constructions de triangles
produisent des triangles isométriques, ce qui nous amène aux
[[file:constructions-de-triangles.org::#heading:condition_d_isometrie_de_deux_triangles][conditions
suffisantes d’isométrie entre triangles]]. Le caractère d’isométrie
de la symétrie orthogonale est donc implicitement admis comme axiome,
et nous n’avons pas vraiment besoin de le démontrer ici. Toutefois,
on peut imaginer un système alternatif où nous admettons comme axiomes
les conditions suffisantes d’isométrie entre triangles. Nous pouvons
alors prouver que toute symétrie orthogonale est une isométrie, ce
que nous faisons ici à titrre d’exercice.

Le schéma ci-dessous représente un segment $[A,B]$ et son image $[C,D]$
par une symétrie orthogonale $\mathcal{S}$ de centre $O$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/isometrie-symetrie-orthogonale.svg]]

Par construction de la symétrie orthogonale, on a :

$$ \abs{AI} = \abs{IC} $$

$$ \abs{BJ} = \abs{JD} $$

Les triangles rectangles $BIJ$ et $JID$ ont leurs deux cathètes de même longueur :

- le côté commun $[I,J]$
- $[B,J]$ et $[J,D]$

Ces triangles sont donc isométriques et :

$$ \abs{BI} = \abs{ID} $$

$$ \alpha = \beta $$

Les droites $(BD)$ et $(AC)$ sont parallèles, car elles sont toutes
deux perpendiculaires à l’axe $d$. L’égalité des angles
alternes-internes nous donne :

$$ \alpha = \gamma $$

$$ \beta = \delta $$

Comme $\alpha = \beta$, on en conclut que :

$$ \gamma = \alpha = \beta = \delta $$

Les triangles $AIB$ et $ICD$ ont donc un angle de même amplitude
($\gamma = \delta$) compris entre deux  côtés correspondants de mêmes
longueurs :

$$ \abs{AI} = \abs{IC} $$

$$ \abs{BI} = \abs{ID} $$

Ils sont donc isométriques, ce qui implique que la longueur du segment
d’origine est égale à la longueur du segment image :

$$ \abs{AB} = \abs{CD} $$

Toute symétrie orthogonale est donc une isométrie.

