
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un triangle est une figure géométrique délimitée par trois segments
reliant trois points pour former un circuit fermé. Chaque point du
circuit est appelé *sommet* du triangle, tandis que chaque segment est
appelé *côté* du triangle.

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle.svg]]

Le schéma ci-dessus représente un exemple de triangle de sommets $A$,
$B$ et $C$ délimité par les côtés :

$$ a = [A,B] $$

$$ b = [B,C] $$

$$ c = [C,D] $$

On définit généralement un triangle par la liste de ces sommets. Le
triangle du schéma ci-dessus est appelé triangle $ABC$.

* Somme des angles d’un triangle

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-triangle.svg]]

La figure ci-dessus, où la droite $d$ est parallèle au côté $b$,
nous montre que la somme des angles d’un triangle vaut un angle plat,
c’est-à-dire $\pi$ ou 180° :

$$ \alpha + \beta + \gamma = \pi = 180^\circ $$

* Triangles isométriques

Deux triangles sont dits isométriques si leur côtés correspondants sont
de même longueur et leurs angles correspondants de même amplitude. Le
schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques.svg]]

avec :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

* Triangles semblables

Deux triangles sont dits semblables si les rapports de leurs côtés
correspondants sont les mêmes, et si leurs angles correspondants de
même amplitude. Le schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables.svg]]

avec :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Corollaires

Soit la relation :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} $$

Multiplions par $a_2 \cdot b_2$ :

$$ a_1 \cdot b_2 = a_2 \cdot b_1 $$

puis divisons par $b_1 \cdot b_2$ :

$$ \frac{a_1}{b_1} = \frac{a_2}{b_2} $$

On obtient par un raisonnement similaire :

$$ \frac{a_1}{c_1} = \frac{a_2}{c_2} $$

$$ \frac{b_1}{c_1} = \frac{b_2}{c_2} $$

Les rapports entre les longueurs des côtés sont les mêmes dans les deux
triangles.

* Aire

#+TOC: headlines 1 local

** Triangle rectangle

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle-rectangle.svg]]

Que vaut l’aire $T$ du triangle rectangle $ABC$ ? On sait que l’aire
$R$ du rectangle $ABCD$ vaut :

$$ R = a \cdot b $$

Or, ce rectangle contient deux triangles rectangle isométriques : $ABC$
et $ACD$. On a donc :

$$ d = a $$

$$ e = b $$

Ces deux triangles ayant la même aire, on a :

$$ R = 2 \cdot T $$

ou encore :

$$ T = \frac{R}{2} $$

et donc :

$$ T = \frac{a \cdot b}{2} $$

** Triangle quelconque

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/aire-triangle.svg]]

* Théorème de Thalès sur les proportions

#+TOC: headlines 1 local

** Démonstration

** Conditions pour avoir des triangles isométriques

Pour que deux triangles soient isométriques, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

- un côté de même longueur entre deux angles de même amplitude. Par
  exemple :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

- un angle de même amplitude compris entre deux côtés de même longueur.
  Par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

** Conditions pour avoir des triangles semblables

Pour que deux triangles soient semblables, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} $$

- deux angles correspondants sont de même amplitude, par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

Remarquons que, dans ce cas, les troisièmes angles sont forcément
de même amplitude :

$$ \gamma_2 = \pi - \alpha_2 - \beta_2 = \pi - \alpha_1 - \beta_1 = \gamma_1 $$

- deux côtés correspondants sont de longueurs proportionnelles et
  les angles qu’ils forment sont de même amplitude, par exemple :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} $$

et :

$$ \gamma_1 = \gamma_2 $$

*** Triangles rectangles

Dans le cas de deux triangles rectangles $T_1$ et $T_2$, les deux angles
droits correspondent et sont par définition égaux. Il suffit donc
d’avoir un deuxième angle $\alpha$ identique dans les deux triangles
pour que $T_1$ et $T_2$ soient semblables.

* Triangle rectangle

#+TOC: headlines 1 local

** Définition

Un triangle rectangle est un triangle dont un des angles est un angle
droit.

** Hypothénuse et cathètes

Dans un triangle rectangle :

- le plus long côté est appelé hypothénuse
- les deux autres côtés, appelés cathètes, sont adjacents à l’angle droit

** Somme des angles

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-triangle-rectangle.svg]]

Dans le cas d’un triangle rectangle, un des angles vaut $\pi/2$ et
leur somme s’écrit :

$$ \alpha + \beta + \frac{\pi}{2} = \pi $$

ou encore :

$$ \alpha + \beta = \pi - \frac{\pi}{2} $$

et finalement :

$$ \alpha + \beta = \frac{\pi}{2} $$

Les angles non droits d’un triangle rectangle sont complémentaires.

** Théorème de Pythagore

Soit le triangle :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/longueurs-triangle-rectangle.svg]]

Nous allons montrer une importante relation entre les longueurs $a,b,c$
en utilisant le schéma suivant :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pythagore.svg]]

Aire de chaque triangle rectangle :

$$ A_T = \frac{a b}{2} $$

Aire du grand carré d’après son côté $a+b$ :

$$ A = (a+b)^2 = a^2 + 2 \ a \ b + b^2 $$

Aire du grand carré exprimé comme la somme des aires du carré et
des triangles qu’il contient :

$$ A = c^2 + 4 \cdot A_T = c^2 + 4 \cdot \frac{a \ b}{2} = c^2 + 2 \ a \ b $$

Comme les deux expressions de $A$ sont égales, on a :

$$ a^2 + 2 \ a \ b + b^2 = c^2 + 2 \ a \ b $$

ce qui donne en simplifiant :

$$ a^2 + b^2 = c^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

La longueur $c$ étant un réel positif, on en déduit immédiatement que :

$$ c = \sqrt{a^2 + b^2} $$

** Triangles de Pythagore

Un triangle de Pythagore est un triangle rectangle où les longueurs
des trois côtés sont des nombres entiers.

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-pythagore.svg]]

La figure ci-dessus utilise une astuce algébrique pour obtenir certains
triangles de Pythagore. En effet :

\begin{align*}
A^2 + B^2
&= \left(a^2 - b^2\right)^2 + \left(2 \ a \ b\right)^2 \\
&= a^4 - 2 \ a^2 \ b^2 + b^4 + 4 \ a^2 \ b^2 \\
&= a^4 + 2 \ a^2 \ b^2 + b^4 \\
&= \left(a^2 + b^2\right)^2
\end{align*}

et finalement :

$$ A^2 + B^2 = C^2 $$

Choisir de telles expressions pour $A$, $B$, $C$ nous assure d’avoir
des longueurs qui respectent le théorème de Pythagore. De plus, si
les longueurs $a$, $b$, $c$ sont entières, les longueurs $A$, $B$,
$C$ le seront également. Le tableau suivant nous donne les premiers
triangles de Pythagore obtenus avec cette méthode.

| $a$ | $b$ | $A$ | $B$ | $C$ |
|-----+-----+-----+-----+-----|
|   2 |   1 |   3 |   4 |   5 |
|   3 |   2 |   5 |  12 |  13 |
|   4 |   1 |   8 |  15 |  17 |
|   4 |   3 |   7 |  24 |  25 |
|   5 |   2 |  20 |  21 |  29 |
|   5 |   4 |   9 |  40 |  41 |
|   6 |   1 |  12 |  35 |  37 |
|   6 |   5 |  11 |  60 |  61 |
|   7 |   2 |  28 |  45 |  53 |
|   7 |   4 |  33 |  56 |  65 |
|   7 |   6 |  13 |  84 |  85 |

** Propriétés des cathètes

Examinons le triangle rectangle ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cathetes.svg]]

L’hypothénuse $c$ y est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle rectangle principal en deux
triangles rectangles : $a,h,u$ et $b,h,c$.

*** Carré de la hauteur

Le théorème de Pythagore appliqué au triangle rectangle principal nous
donne :

$$ a^2 + b^2 = c^2 $$

On sait déjà que $c = u + v$. Par ailleurs, le théorème de Pythagore
appliqué au triangle rectangle de gauche nous donne :

$$ h^2 + u^2 = a^2 $$

Le théorème de Pythagore appliqué au triangle rectangle de droite nous
donne :

$$ h^2 + v^2 = b^2 $$

On peut se servir de ces expressions pour substituer les valeurs de $a$
et $b$ dans le triangle principal :

$$ (h^2 + u^2) + (h^2 + v^2) = (u+v)^2 $$

ou encore :

$$ 2 \ h^2 + u^2 + v^2 = u^2 + 2 \ u \ v + v^2 $$

En simplifiant, il vient :

$$ 2 \ h^2 = 2 \ u \ v $$

On obtient finalement :

$$ h^2 = u \ v $$

*** Carré des cathètes

On reprend le théorème de Pythagore dans le triangle de gauche :

$$ a^2 = u^2 + h^2 $$

et on remplace le carré de la hauteur par le produit $u\ v$ :

$$ a^2 = u^2 + u \ v $$

On met ensuite $u$ en évidence :

$$ a^2 = u \ (u + v) $$

ce qui nous donne :

$$ a^2 = u \ c $$

On utilise le même procédé dans le triangle de droite :

\begin{align*}
b^2
&= v^2 + h^2 \\
&= v^2 + u \ v \\
&= v \ (u + v) \\
\end{align*}

ce qui nous donne :

$$ b^2 = v \ c $$

*** Produit des cathètes

En multipliant les équations :

$$ a^2 = u \ c $$

$$ b^2 = v \ c $$

ensemble, on obtient :

$$ a^2 \ b^2 = u \ c \ v \ c $$

ou encore :

$$ a^2 \ b^2 = u \ v \ c^2 $$

Le produit $u \ v$ étant identique à la hauteur, on a :

$$ a^2 \ b^2 = h^2 \ c^2 $$

et finalement :

$$ a \ b = h \ c $$

* Triangle isocèle

#+TOC: headlines 1 local

** Définition

Un triangle isocèle est un triangle dont au moins deux côtés sont de
longueur égale.

* Triangle équilatéral

#+TOC: headlines 1 local

** Définition

Un triangle équilatéral est un triangle dont les trois côtés sont de
longueur égale. Par symétrie, les trois angles sont alors d’amplitude
égale. Soit $\alpha$ cette amplitude. On a :

$$ 3 \ \alpha = \pi = 180^\circ $$

et donc :

$$ \alpha = \frac{\pi}{3} = 60^\circ $$

