
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un triangle est une figure géométrique délimitée par trois segments
reliant trois points pour former un circuit fermé. Chaque point du
circuit est appelé *sommet* du triangle, tandis que chaque segment est
appelé *côté* du triangle.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-et-longueurs.svg]]

Le schéma ci-dessous représente un exemple de triangle de sommets $A$,
$B$ et $C$ délimité par les côtés de longueurs :

$$ a = \abs{BC} $$

$$ b = \abs{CA} $$

$$ c = \abs{AB} $$

On définit généralement un triangle par la liste de ces sommets. Le
triangle du schéma ci-dessus est appelé triangle $ABC$.

* Sommets et côtés

Soit le triangle $ABC$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle.svg]]

Un sommet du triangle est dit opposé à un côté si le sommet n’est
pas une extrémité du côté. Dans notre schéma :

- $A$ est le sommet opposé à $[B,C]$
- $B$ est le sommet opposé à $[C,A]$
- $C$ est le sommet opposé à $[A,B]$

Un côté du triangle est dit opposé à un sommet si le sommet n’est pas
une extrémité du côté. Dans notre schéma :

- $[B,C]$ est le côté opposé à $A$
- $[C,A]$ est le côté opposé à $B$
- $[A,B]$ est le côté opposé à $C$

* Classification

#+TOC: headlines 1 local

** Triangle rectangle

Un triangle rectangle est un triangle qui possède un angle droit.

Le schéma ci-dessous donne un exemple de triangle rectangle $ABC$ :

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-rectangle.svg]]

On voit que l’angle droit est situé sur le sommet $B$ :

$$ \angleflex{B} = 90^\circ $$

On dit aussi que le triangle $ABC$ est rectangle en $B$.

*** Nomenclature des côtés

Dans un triangle rectangle :

- les deux côtés adjacents à l’angle droit sont appelés cathètes
- le troisième côté est appelé hypothénuse

Par exemple, dans le triangle $ABC$ rectangle en $B$ :

- les côtés $[A,B]$ et $[B,C]$ sont les cathètes
- le côté $[A,C]$ est l’hypothénuse

** Triangle isocèle

Un triangle isocèle est un triangle qui possède deux côtés de
longueurs égales.

Le schéma ci-dessous donne un exemple de triangle isocèle $ABC$ :

#+attr_html: :width 36%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele.svg]]

On voit que :

$$ a = \abs{AB} = \abs{AC} $$

On dit aussi que le triangle $ABC$ est isocèle en $A$.

*** Nomenclature des côtés

Dans un triangle isocèle :

- le sommet adjacent aux deux côtés de même longueur est
  appelé sommet principal
- le côté opposé au sommet principal est appelé base principale

Par exemple, dans le triangle $ABC$ isocèle en $A$ :

- $A$ est le sommet principal
- $[B,C]$ est la base principale

** Triangle équilatéral

Un triangle équilatéral est un triangle dont les trois côtés sont de longueurs égales

Le schéma ci-dessous donne un exemple de triangle équilatéral $ABC$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral.svg]]

On voit que :

$$ a = \abs{AB} = \abs{BC} = \abs{CA} $$

** Triangle acutangle

Un triangle acutangle est un triangle dont tous les angles sont aigus

Le schéma ci-dessous donne un exemple de triangle acutangle $ABC$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-acutangle.svg]]

On voit que :

$$ \alpha, \beta, \gamma < 90^\circ $$

** Triangle obtusangle

Un triangle obtusangle est un triangle dont un des angles est obtus

Le schéma ci-dessous donne un exemple de triangle obtusangle :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-obtusangle.svg]]

On voit que :

$$ \gamma > 90^\circ $$

tandis que :

$$ \alpha, \beta < 90^\circ $$

* Angles

#+TOC: headlines 1 local

** Somme des angles d’un triangle

La figure ci-dessous représente un triangle $ABC$, une droite $d$
qui prolonge le côté $[A,B]$ et une droite $f$ parallèle à $d$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-triangle.svg]]

La notation des angles tient compte de l’égalité des angles
alternes-internes.

Ce schéma nous montre que les angles $\alpha$, $\beta$ et $\gamma$
forment ensemble un angle plat au point $C$ :

$$ \alpha + \beta + \gamma = 180^\circ $$

Ces trois angles ayant les mêmes amplitudes que les angles internes du
triangle $ABC$, on en déduit que la somme des angles d’un triangle
vaut $180^\circ$.

** Triangle rectangle

#+TOC: headlines 1 local

*** Raisonnement

Soit un triangle $ABC$ rectangle en $B$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-triangle-rectangle.svg]]

On suppose dans la suite que les angles sont orientés pour être
positifs :

$$ \alpha, \beta \ge 0 $$

et que le triangle n’est pas dégénéré. Les angles ne sont donc
pas nuls et :

$$ \alpha, \beta > 0 $$

Puisque l’angle $\angleflex{B}$ est un angle droit, la somme des angles
du triangle $ABC$ s’écrit :

$$ \alpha + \beta + 90^\circ = 180^\circ $$

ou encore :

$$ \alpha + \beta = 180^\circ - 90^\circ $$

et finalement :

$$ \alpha + \beta = 90^\circ $$

Les angles $\alpha$ et $\beta$ sont complémentaires.

On en conclut que :

$$ \alpha  = 90^\circ - \beta < 90^\circ $$

$$ \beta  = 90^\circ - \alpha < 90^\circ $$

Les angles $\alpha$ et $\beta$ sont des angles aigus.

*** Conclusion

Les angles aigus d’un triangle rectangle sont complémentaires.

* Inégalités triangulaires

Soit le triangle $ABC$ suivant :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/inegalites-triangulaires.svg]]

[[file:geometrie-plane.org::#heading:distance_inegalite_triangulaire][L’inégalité
triangulaire]] des
[[file:geometrie-plane.org::#heading:distance][distances]] nous garantit
qu’il est toujours plus court d'aller directement du point $A$ au
point $B$ plutôt que de passer par un point intermédiaire $C$. On a
donc l'inégalité triangulaire :

$$ \abs{AB} \le \abs{AC} + \abs{CB} $$

Il en va de mēme pour aller du point $A$ au point $C$ en passant ou
non par $B$ :

$$ \abs{AC} \le \abs{AB} + \abs{BC} $$

ou pour aller du point $B$ au point $C$ en passant ou non par $A$ :

$$ \abs{BC} \le \abs{BA} + \abs{AC} $$

En isolant $\abs{BC} = \abs{CB}$ dans les deux premières équations,
on obtient :

$$ \abs{BC} \ge \abs{AB} - \abs{AC} $$

$$ \abs{BC} \ge \abs{AC} - \abs{AB} $$

ou, sous forme plus condensée :

$$ \abs{BC} \ge \max \big\{ \abs{AB} - \abs{AC}, \abs{AC} - \abs{AB} \big\} $$

En suivant le même raisonnement pour $\abs{AB} = \abs{BA}$ dans les
deuxième et troisième inégalités triangulaires, on obtient :

$$ \abs{AB} \ge \max \big\{ \abs{AC} - \abs{BC}, \abs{BC} - \abs{AC} \big\} $$

En suivant le même raisonnement pour $\abs{AC}$ dans les première et
troisième inégalités triangulaires, on obtient :

$$ \abs{AC} \ge \max \big\{ \abs{AB} - \abs{BC}, \abs{BC} - \abs{AB} \big\} $$

Dans notre exemple, on a clairement :

$$ \abs{AB} \ge \abs{BC} \ge \abs{CA} $$

et :

$$ \abs{AB} - \abs{AC} \ge 0
\qquad \qquad \qquad
\abs{AC} - \abs{AB} \le 0 $$

$$ \abs{BC} - \abs{AC} \ge 0
\qquad \qquad \qquad
\abs{AC} - \abs{BC} \le 0 $$

$$ \abs{AB} - \abs{BC} \ge 0
\qquad \qquad \qquad
\abs{BC} - \abs{AB} \le 0 $$

ce qui nous donne les bornes inférieures :

$$ \abs{BC} \ge \abs{AB} - \abs{AC} $$

$$ \abs{AB} \ge \abs{BC} - \abs{AC} $$

$$ \abs{AC} \ge \abs{AB} - \abs{BC} $$

Nous avons donc montré que :

- la longueur de chacun des côtés d’un triangle est inférieure ou
  égale à la somme des longueurs des deux autres côtés.
- la longueur de chacun des côtés d’un triangle est supérieure ou
  égale à la différence entre le plus long et le plus court des
  deux autres côtés

* Triangle et cercle

#+TOC: headlines 1 local

** Cercle circonscrit

On dit que le cercle $\mathscr{C}$ est circonscrit au triangle
$\mathcal{T}$, ou que $\mathcal{T}$ est inscrit dans $\mathscr{C}$,
si tous les sommets de $\mathcal{T}$ appartiennent à $\mathscr{C}$.

Le schéma ci-dessous représente un triangle $\mathcal{T} = ABC$ et
son cercle circonscrit $\mathscr{C}$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-circonscrit-a-un-triangle.svg]]

** Cercle inscrit

On dit que le cercle $\mathscr{C}$ est inscrit au triangle $\mathcal{T}$
si tous les côtés de $\mathcal{T}$ sont tangents à $\mathscr{C}$.

Le schéma ci-dessous représente un triangle $\mathcal{T} = ABC$ et
son cercle inscrit $\mathscr{C}$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-inscrit-a-un-triangle.svg]]

On voit que $\mathscr{C}$ est tangent aux côtés du triangles $ABC$
aux points $P$, $S$ et $T$.

* Triangles isométriques

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits isométriques si leur côtés correspondants sont
de même longueur et leurs angles correspondants de même amplitude. Le
schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques.svg]]

avec :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

*Remarque* : deux côtés ou angles correspondants sont aussi qualifiés
d’homologues.

** Notation

Si deux triangles $T_1$ et T_2$ sont isométriques, on le note :

$$ T_1 \cong T_2 $$

*Remarque* : attention à ne pas confondre le symbole d’isométrie $\cong$
avec l’égalité approximative $\approx$ ou $\simeq$.

** Équivalence

On vérifie aisément que la relation d’isométrie est une équivalence.

* Triangles semblables
:properties:
:custom_id: heading:triangles_semblables
:end:

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits semblables si leurs côtés sont proportionnels,
c’est-à-dire si les rapports de leurs côtés correspondants sont les
mêmes, et si leurs angles correspondants sont de même amplitude. Le
schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 65%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables.svg]]

On a alors la proportion commune :

$$ \varphi = \frac{a_2}{a_1} = \frac{b_2}{b_1} = \frac{c_2}{c_1} $$

et les angles :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Isolation des longueurs

En isolant les longueurs du grand triangle $DEF$ dans les relations de
la proportion commune, on obtient :

$$ a_2 = \varphi \ a_1 $$

$$ b_2 = \varphi \ b_1 $$

$$ c_2 = \varphi \ c_1 $$

** Différences de longueurs
:properties:
:custom_id: heading:triangles_semblables_differences_de_longueurs
:end:

Le triangle $DEF$ est clairement plus grand que le triangle $ABC$. On
a donc :

$$ \varphi = \frac{a_2}{a_1} = \frac{b_2}{b_1} = \frac{c_2}{c_1} \ge 1 $$

Ces différences de longueurs sont donc positives :

$$ \difference a = a_2 - a_1 $$

$$ \difference b = b_2 - b_1 $$

$$ \difference c = c_2 - c_1 $$

*** Petit triangle comme référence

Comparons la différence de longueurs $\difference a$ avec la longueur
correspondante du petit triangle $ABC$ :

$$ \frac{\difference a}{a_1} = \frac{a_2 - a_1}{a_1} $$

Il vient :

$$ \frac{\difference a}{a_1}
= \frac{a_2}{a_1} - \frac{a_1}{a_1}
= \frac{a_2}{a_1} - 1 $$

Comme le rapport dans le membre de droite vaut $\varphi$, on a finalement :

$$ \frac{\difference a}{a_1} = \varphi - 1 $$

Posons :

$$ \rho = \varphi - 1 $$

Le rapport précédent peut se réécrire :

$$ \frac{\difference a}{a_1} = \rho $$

On a aussi :

$$ \frac{\difference b}{b_1}
= \frac{b_2}{b_1} - 1
= \varphi - 1
= \rho $$

et :

$$ \frac{\difference c}{c_1}
= \frac{c_2}{c_1} - 1
= \varphi - 1
= \rho $$

Les différences de longueurs entre le plus grand triangle et le plus
petit respectent la proportion commune :

$$ \rho
= \frac{\difference a}{a_1}
= \frac{\difference b}{b_1}
= \frac{\difference c}{c_1} $$

de valeur :

$$ \rho = \varphi - 1 $$

Comme $\varphi \ge 1$, on a la borne :

$$ \rho \ge 0 $$

*** Grand triangle comme référence

Comparons la différence de longueurs $\difference a$ avec la longueur
correspondante du grand triangle $DEF$ :

$$ \frac{\difference a}{a_2} = \frac{a_2 - a_1}{a_2} $$

Il vient :

$$ \frac{\difference a}{a_2}
= \frac{a_2}{a_2} - \frac{a_1}{a_2}
= 1 - \frac{a_1}{a_2} $$

Comme le rapport dans le membre de droite vaut $1/\varphi$, on a finalement :

$$ \frac{\difference a}{a_2} = 1 - \unsur{\varphi} = \frac{\varphi - 1}{\varphi} $$

Posons :

$$ \omega = 1 - \unsur{\varphi} = \frac{\varphi - 1}{\varphi} $$

Le rapport précédent peut se réécrire :

$$ \frac{\difference a}{a_2} = \omega $$

On a aussi :

$$ \frac{\difference b}{b_2}
= 1 - \frac{b_1}{b_2}
= 1 - \unsur{\varphi}
= \omega $$

et :

$$ \frac{\difference c}{c_2}
= 1 - \frac{c_1}{c_2}
= 1 - \unsur{\varphi}
= \omega $$

Les différences de longueurs entre le plus grand triangle et le plus
petit respectent la proportion commune :

$$ \omega
= \frac{\difference a}{a_2}
= \frac{\difference b}{b_2}
= \frac{\difference c}{c_2} $$

de valeur :

$$ \omega = \frac{\varphi - 1}{\varphi} $$

Comme $\varphi \ge 1$, on a les bornes :

$$ 0 \le 1 - \unsur{\varphi} < 1 $$

ou :

$$ 0 \le \omega < 1 $$

*Remarque* : on aurait aussi pu partir de :

$$ \frac{\difference a}{a_1} = \rho = \varphi - 1 $$

isoler $\difference a$ :

$$ \difference a = (\varphi - 1) \ a_1 $$

et diviser par $a_2$ :

$$ \frac{\difference a}{a_2} = (\varphi - 1) \ \frac{a_1}{a_2} $$

comme $a_1 / a_2 = 1/\varphi$, on obtient le même résultat que
précédemment :

$$ \frac{\difference a}{a_2} = \frac{\varphi - 1}{\varphi} $$

Le raisonnement est similaire pour $\difference b / b_2$ et $\difference
c / c_2$.

** Proportions internes
:properties:
:custom_id: heading:triangles_semblables_proportions_internes
:end:

Divisons $a_2$ par $b_2$ et remplaçons ces longueurs par leurs expressions
en fonctions de $\varphi$ et des longueurs du petit triangle $ABC$ :

$$ \frac{a_2}{b_2} = \frac{\varphi \ a_1}{\varphi \ b_1} $$

En simplifiant, il vient :

$$ \frac{a_2}{b_2} = \frac{a_1}{b_1} $$

Le rapport des longueurs des deux premiers côtés est le même dans
les deux triangles. En utilisant la même méthode avec $a_2$ et $c_2$,
on obtient :

$$ \frac{a_2}{c_2} = \frac{a_1}{c_1} $$

Enfin, en utilisant la même méthode avec $b_2$ et $c_2$, on obtient :

$$ \frac{b_2}{c_2} = \frac{b_1}{c_1} $$

Les proportions internes entre les longueurs des côtés sont les mêmes
dans les deux triangles.
