
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définitions

#+TOC: headlines 1 local

** Triangle

Un triangle est une figure géométrique délimitée par trois segments
reliant trois points pour former un circuit fermé. Chaque point du
circuit est appelé *sommet* du triangle, tandis que chaque segment est
appelé *côté* du triangle.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle.svg]]

Le schéma ci-dessus représente un exemple de triangle de sommets $A$,
$B$ et $C$ délimité par les côtés :

$$ a = [B,C] $$

$$ b = [C,A] $$

$$ c = [A,B] $$

On définit généralement un triangle par la liste de ces sommets. Le
triangle du schéma ci-dessus est appelé triangle $ABC$.

** Catégories

- un triangle isocèle est un triangle qui possède deux côtés de longueurs égales
- un triangle équilatéral est un triangle dont les trois côtés sont de longueurs égales
- un triangle rectangle est un triangle dont un des angles est un angle droit
- un triangle acutangle est un triangle dont tous les angles sont aigus
- un triangle obtusangle est un triangle dont un des angles est aigu

** Objets liés au triangle

- une médiane est un segment qui part d’un sommet du triangle jusqu’au
  milieu du côté opposé
- une hauteur est un segment qui part d’un sommet du triangle et qui est
  perpendiculaire au côté opposé
- une bissectrice est un segment qui part d’un sommet du triangle et qui coupe
  l’angle lié à ce sommet en deux parties égales

* Somme des angles d’un triangle

La figure ci-dessous représente un triangle $ABC$, une droite $a$
qui prolonge le côté $[A,B]$ et une droite $b$ parallèle à $a$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-triangle.svg]]

La notation des angles tient compte de l’égalité des angles
alternes-internes formés par les droites $a$, $b$, $c$ et $d$.

Ce schéma nous montre que les angles $\alpha$, $\beta$ et $\gamma$
forment ensemble un angle plat :

$$ \alpha + \beta + \gamma = 180^\circ $$

Ces trois angles ayant les mêmes amplitudes que les angles internes du
triangle $ABC$, on en déduit que la somme des angles d’un triangle
vaut 180°.

* Construction

#+TOC: headlines 1 local

** Longueur des trois cotés

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-ccc.svg]]

** Côté - angle - côté

** Angle - côté - angle

* Triangle rectangle

#+TOC: headlines 1 local

** Hypothénuse et cathètes

Dans un triangle rectangle :

- le plus long côté est appelé hypothénuse
- les deux autres côtés, appelés cathètes, sont adjacents à l’angle droit

** Somme des angles

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-triangle-rectangle.svg]]

Dans le cas d’un triangle rectangle, un des angles vaut $\pi/2$ et
leur somme s’écrit :

$$ \alpha + \beta + \frac{\pi}{2} = \pi $$

ou encore :

$$ \alpha + \beta = \pi - \frac{\pi}{2} $$

et finalement :

$$ \alpha + \beta = \frac{\pi}{2} $$

Les angles non droits d’un triangle rectangle sont complémentaires.

* Triangle isocèle

#+TOC: headlines 1 local

** Définition

Un triangle isocèle est un triangle dont au moins deux côtés sont de
longueur égale.

* Triangle équilatéral

#+TOC: headlines 1 local

** Définition

Un triangle équilatéral est un triangle dont les trois côtés sont de
longueur égale. Par symétrie, les trois angles sont alors d’amplitude
égale. Soit $\alpha$ cette amplitude. On a :

$$ 3 \ \alpha = \pi = 180^\circ $$

et donc :

$$ \alpha = \frac{\pi}{3} = 60^\circ $$

* Angle et cercle

#+TOC: headlines 1 local

** Angle au centre

** Angle inscrit

** Relation
