
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un triangle est une figure géométrique délimitée par trois segments
reliant trois points pour former un circuit fermé. Chaque point du
circuit est appelé *sommet* du triangle, tandis que chaque segment est
appelé *côté* du triangle.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle.svg]]

Le schéma ci-dessous représente un exemple de triangle de sommets $A$,
$B$ et $C$ délimité par les côtés de longueurs :

$$ a = \abs{BC} $$

$$ b = \abs{CA} $$

$$ c = \abs{AB} $$

On définit généralement un triangle par la liste de ces sommets. Le
triangle du schéma ci-dessus est appelé triangle $ABC$.

* Classification

#+TOC: headlines 1 local

** Triangle rectangle

Un triangle rectangle est un triangle dont un des angles est un angle droit.

Le schéma ci-dessous donne un exemple de triangle rectangle :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-rectangle.svg]]

Dans un triangle rectangle :

- le plus long côté est appelé hypothénuse
- les deux autres côtés, appelés cathètes, sont adjacents à l’angle droit

Dans notre schéma, le côté $c$ est l’hypothénuse, tandis que $a$
et $b$ sont les cathètes.

** Triangle isocèle

Un triangle isocèle est un triangle qui possède deux côtés de
longueurs égales.

Le schéma ci-dessous donne un exemple de triangle isocèle :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele.svg]]

** Triangle équilatéral

Un triangle équilatéral est un triangle dont les trois côtés sont de longueurs égales

Le schéma ci-dessous donne un exemple de triangle équilatéral :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral.svg]]

** Triangle acutangle

Un triangle acutangle est un triangle dont tous les angles sont aigus

Le schéma ci-dessous donne un exemple de triangle acutangle :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-acutangle.svg]]

** Triangle obtusangle

Un triangle obtusangle est un triangle dont un des angles est obtus

Le schéma ci-dessous donne un exemple de triangle obtusangle :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-obtusangle.svg]]

* Objets géométriques liés au triangle

#+TOC: headlines 1 local

** Hauteur

Une hauteur est un segment qui part d’un sommet du triangle et qui
est perpendiculaire au côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une hauteur $h$ qui
part du sommet $C$ pour rejoindre perpendiculairement le côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-triangle.svg]]

*** Hauteur extérieure

Dans le cas où la hauteur progresse vers un côté du triangle adjacent
à un angle obtus, on est amené à tracer la droite qui prolonge
ce côté pour pouvoir construire la hauteur. Le schéma ci-dessous
nous en donne un exemple, avec la hauteur $h$ qui part du sommet $C$
et progresse vers la droite $d$ prolongeant le côté $[A,B]$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-exterieure-triangle.svg]]

Les points $A$, $B$ et $D$ sont alignés sur la droite $d$.

** Médiane

Une médiane est un segment qui part d’un sommet du triangle jusqu’au
milieu du côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une médiane $m$ qui
part du sommet $C$ pour rejoindre le milieu $D$ du côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediane-triangle.svg]]

On a donc :

$$ \abs{AD} = \abs{DB} $$

** Médiatrice

Une médiatrice d’un triangle est tout simplement la médiatrice d’un
des côtés.

Le schéma ci-dessous représente un triangle $ABC$ et une médiatrice $m$ qui
croise perpendiculairement le côté $[A,B]$ en son milieu :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediatrice-triangle.svg]]

** Bissectrice

Une bissectrice d’un triangle est une droite qui passe par un de ses
sommets et qui coupe l’angle lié à ce sommet en deux parties égales.

Le schéma ci-dessous représente un triangle $ABC$ et une bissectrice
$b$ qui passe par le sommet $A$ et coupe l’angle $\angleflex{BAC}$
en deux angles $\alpha$ d’amplitudes égales :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/bissectrice-triangle.svg]]

* Angles

#+TOC: headlines 1 local

** Somme des angles d’un triangle

La figure ci-dessous représente un triangle $ABC$, une droite $a$
qui prolonge le côté $[A,B]$ et une droite $b$ parallèle à $a$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-triangle.svg]]

La notation des angles tient compte de l’égalité des angles
alternes-internes formés par les droites $a$, $b$, $c$ et $d$.

Ce schéma nous montre que les angles $\alpha$, $\beta$ et $\gamma$
forment ensemble un angle plat :

$$ \alpha + \beta + \gamma = 180^\circ $$

Ces trois angles ayant les mêmes amplitudes que les angles internes du
triangle $ABC$, on en déduit que la somme des angles d’un triangle
vaut 180°.

** Triangle rectangle

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-triangle-rectangle.svg]]

Dans le cas d’un triangle rectangle, un des angles vaut $\pi/2$ et
leur somme s’écrit :

$$ \alpha + \beta + \frac{\pi}{2} = \pi $$

ou encore :

$$ \alpha + \beta = \pi - \frac{\pi}{2} $$

et finalement :

$$ \alpha + \beta = \frac{\pi}{2} $$

Les angles non droits d’un triangle rectangle sont complémentaires.

* Inégalités triangulaires

Soit le triangle $ABC$ suivant :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/inegalites-triangulaires.svg]]

[[file:geometrie-plane.org::#heading:distance_inegalite_triangulaire][L’inégalité
triangulaire]] des
[[file:geometrie-plane.org::#heading:distance][distances]] nous garantit
qu’il est toujours plus court d'aller directement du point $A$ au
point $B$ plutôt que de passer par un point intermédiaire $C$. On a
donc l'inégalité triangulaire :

$$ \abs{AB} \le \abs{AC} + \abs{CB} $$

Il en va de mēme pour aller du point $A$ au point $C$ en passant ou
non par $B$ :

$$ \abs{AC} \le \abs{AB} + \abs{BC} $$

ou pour aller du point $B$ au point $C$ en passant ou non par $A$ :

$$ \abs{BC} \le \abs{BA} + \abs{AC} $$

En isolant $\abs{BC} = \abs{CB}$ dans les deux premières équations,
on obtient :

$$ \abs{BC} \ge \abs{AB} - \abs{AC} $$

$$ \abs{BC} \ge \abs{AC} - \abs{AB} $$

ou, sous forme plus condensée :

$$ \abs{BC} \ge \max \big\{ \abs{AB} - \abs{AC}, \abs{AC} - \abs{AB} \big\} $$

En suivant le même raisonnement pour $\abs{AB} = \abs{BA}$ dans les
deuxième et troisième inégalités triangulaires, on obtient :

$$ \abs{AB} \ge \max \big\{ \abs{AC} - \abs{BC}, \abs{BC} - \abs{AC} \big\} $$

En suivant le même raisonnement pour $\abs{AC}$ dans les première et
troisième inégalités triangulaires, on obtient :

$$ \abs{AC} \ge \max \big\{ \abs{AB} - \abs{BC}, \abs{BC} - \abs{AB} \big\} $$

Dans notre exemple, on a clairement :

$$ \abs{AB} \ge \abs{BC} \ge \abs{CA} $$

et :

$$ \abs{AB} - \abs{AC} \ge 0
\qquad \qquad \qquad
\abs{AC} - \abs{AB} \le 0 $$

$$ \abs{BC} - \abs{AC} \ge 0
\qquad \qquad \qquad
\abs{AC} - \abs{BC} \le 0 $$

$$ \abs{AB} - \abs{BC} \ge 0
\qquad \qquad \qquad
\abs{BC} - \abs{AB} \le 0 $$

ce qui nous donne les bornes inférieures :

$$ \abs{BC} \ge \abs{AB} - \abs{AC} $$

$$ \abs{AB} \ge \abs{BC} - \abs{AC} $$

$$ \abs{AC} \ge \abs{AB} - \abs{BC} $$

Nous avons donc montré que :

- la longueur de chacun des côtés d’un triangle est inférieure ou
  égale à la somme des longueurs des deux autres côtés.
- la longueur de chacun des côtés d’un triangle est supérieure ou
  égale à la différence entre le plus long et le plus court des
  deux autres côtés

* Triangles isométriques

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits isométriques si leur côtés correspondants sont
de même longueur et leurs angles correspondants de même amplitude. Le
schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques.svg]]

avec :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

*Remarque* : deux côtés ou angles correspondants sont aussi qualifiés
d’homologues.

** Notation

Si deux triangles $T_1$ et T_2$ sont isométriques, on le note :

$$ T_1 \cong T_2 $$

*Remarque* : attention à ne pas confondre le symbole d’isométrie $\cong$
avec l’égalité approximative $\approx$ ou $\simeq$.

** Équivalence

On vérifie aisément que la relation d’isométrie est une équivalence.

* Triangles semblables
:properties:
:custom_id: heading:triangles_semblables
:end:

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits semblables si les rapports de leurs côtés
correspondants sont les mêmes, et si leurs angles correspondants sont
de même amplitude. Le schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 65%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables.svg]]

On a alors la proportion commune :

$$ \varphi = \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} $$

et les angles :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Isolation des longueurs

En isolant les longueurs du premier triangle dans les relations de la
proportion commune, on obtient :

$$ a_1 = \varphi \ a_2 $$

$$ b_1 = \varphi \ b_2 $$

$$ c_1 = \varphi \ c_2 $$

** Différences de longueurs
:properties:
:custom_id: heading:triangles_semblables_differences_de_longueurs
:end:

Le triangle $ABC$ est clairement plus grand que le triangle $DEF$. On
a donc :

$$ \varphi = \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} > 1 $$

Ces différences de longueurs sont donc strictement positives :

$$ \difference a = a_1 - a_2 $$

$$ \difference b = b_1 - b_2 $$

$$ \difference c = c_1 - c_2 $$

Examinons le rapport :

$$ \frac{\difference a}{a_2} = \frac{a_1 - a_2}{a_2} $$

Il vient :

$$ \frac{\difference a}{a_2}
= \frac{a_1}{a_2} - \frac{a_2}{a_2}
= \frac{a_1}{a_2} - 1 $$

Comme le rapport dans le membre de droite vaut $\varphi$, on a finalement :

$$ \frac{\difference a}{a_2} = \varphi - 1 $$

Posons :

$$ \rho = \varphi - 1 $$

Le rapport précédent peut se réécrire :

$$ \frac{\difference a}{a_2} = \rho $$

On a aussi :

$$ \frac{\difference b}{b_2}
= \frac{b_1}{b_2} - 1
= \varphi - 1
= \rho $$

et :

$$ \frac{\difference c}{c_2}
= \frac{c_1}{c_2} - 1
= \varphi - 1
= \rho $$

Les différences de longueurs entre le plus grand triangle et le plus
petit respectent aussi une proportion commune :

$$ \rho
= \frac{\difference a}{a_2}
= \frac{\difference b}{b_2}
= \frac{\difference c}{c_2} $$

de valeur :

$$ \rho = \varphi - 1 $$

** Proportions internes
:properties:
:custom_id: heading:triangles_semblables_proportions_internes
:end:

Divisons $a_1$ par $b_1$ et remplaçons ces longueurs par leurs expressions
en fonctions de $\varphi$ et des longueurs du second triangle :

$$ \frac{a_1}{b_1} = \frac{\varphi \ a_2}{\varphi \ b_2} $$

En simplifiant, il vient :

$$ \frac{a_1}{b_1} = \frac{a_2}{b_2} $$

Le rapport des longueurs des deux premiers côtés est le même dans
les deux triangles. En utilisant la même méthode avec $a_1$ et $c_1$,
on obtient :

$$ \frac{a_1}{c_1} = \frac{a_2}{c_2} $$

Enfin, en utilisant la même méthode avec $b_1$ et $c_1$, on obtient :

$$ \frac{b_1}{c_1} = \frac{b_2}{c_2} $$

Les proportions internes entre les longueurs des côtés sont les mêmes
dans les deux triangles.
