
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définition

Un triangle est une figure géométrique délimitée par trois segments
reliant trois points pour former un circuit fermé. Chaque point du
circuit est appelé *sommet* du triangle, tandis que chaque segment est
appelé *côté* du triangle.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle.svg]]

Le schéma ci-dessous représente un exemple de triangle de sommets $A$,
$B$ et $C$ délimité par les côtés :

$$ a = [B,C] $$

$$ b = [C,A] $$

$$ c = [A,B] $$

On définit généralement un triangle par la liste de ces sommets. Le
triangle du schéma ci-dessus est appelé triangle $ABC$.

* Classification

#+TOC: headlines 1 local

** Triangle rectangle

Un triangle rectangle est un triangle dont un des angles est un angle droit.

Le schéma ci-dessous donne un exemple de triangle rectangle :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-rectangle.svg]]

Dans un triangle rectangle :

- le plus long côté est appelé hypothénuse
- les deux autres côtés, appelés cathètes, sont adjacents à l’angle droit

Dans notre schéma, le côté $c$ est l’hypothénuse, tandis que $a$
et $b$ sont les cathètes.

** Triangle isocèle

Un triangle isocèle est un triangle qui possède deux côtés de longueurs égales

Le schéma ci-dessous donne un exemple de triangle isocèle :

#+attr_html: :width 20%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele.svg]]

** Triangle équilatéral

Un triangle équilatéral est un triangle dont les trois côtés sont de longueurs égales

Le schéma ci-dessous donne un exemple de triangle équilatéral :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral.svg]]

** Triangle acutangle

Un triangle acutangle est un triangle dont tous les angles sont aigus

Le schéma ci-dessous donne un exemple de triangle acutangle :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-acutangle.svg]]

** Triangle obtusangle

Un triangle obtusangle est un triangle dont un des angles est obtus

Le schéma ci-dessous donne un exemple de triangle obtusangle :

#+attr_html: :width 50%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-obtusangle.svg]]

* Objets géométriques liés au triangle

#+TOC: headlines 1 local

** Hauteur

Une hauteur est un segment qui part d’un sommet du triangle et qui
est perpendiculaire au côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une hauteur $h$ qui
part du sommet $C$ pour rejoindre perpendiculairement le côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-triangle.svg]]

*** Hauteur extérieure

Dans le cas où la hauteur progresse vers un côté du triangle adjacent
à un angle obtus, on est amené à tracer la droite qui prolonge
ce côté pour pouvoir construire la hauteur. Le schéma ci-dessous
nous en donne un exemple, avec la hauteur $h$ qui part du sommet $C$
et progresse vers la droite $d$ prolongeant le côté $[A,B]$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/hauteur-exterieure-triangle.svg]]

Les points $A$, $B$ et $D$ sont alignés sur la droite $d$.

** Médiane

Une médiane est un segment qui part d’un sommet du triangle jusqu’au
milieu du côté opposé.

Le schéma ci-dessous représente un triangle $ABC$ et une médiane $m$ qui
part du sommet $C$ pour rejoindre le milieu $D$ du côté $[A,B]$ :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediane-triangle.svg]]

On a donc :

$$ \abs{AD} = \abs{DB} $$

** Médiatrice

Une médiatrice d’un triangle est tout simplement la médiatrice d’un
des côtés.

Le schéma ci-dessous représente un triangle $ABC$ et une médiatrice $m$ qui
croise perpendiculairement le côté $[A,B]$ en son milieu :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/mediatrice-triangle.svg]]

** Bissectrice

Une bissectrice d’un triangle est une droite qui passe par un de ses
sommets et qui coupe l’angle lié à ce sommet en deux parties égales.

Le schéma ci-dessous représente un triangle $ABC$ et une bissectrice
$b$ qui passe par le sommet $A$ et coupe l’angle $\anglecirc{BAC}$
en deux angles $\alpha$ d’amplitudes égales :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/bissectrice-triangle.svg]]

* Angles

#+TOC: headlines 1 local

** Somme des angles d’un triangle

La figure ci-dessous représente un triangle $ABC$, une droite $a$
qui prolonge le côté $[A,B]$ et une droite $b$ parallèle à $a$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-triangle.svg]]

La notation des angles tient compte de l’égalité des angles
alternes-internes formés par les droites $a$, $b$, $c$ et $d$.

Ce schéma nous montre que les angles $\alpha$, $\beta$ et $\gamma$
forment ensemble un angle plat :

$$ \alpha + \beta + \gamma = 180^\circ $$

Ces trois angles ayant les mêmes amplitudes que les angles internes du
triangle $ABC$, on en déduit que la somme des angles d’un triangle
vaut 180°.

** Triangle rectangle

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-triangle-rectangle.svg]]

Dans le cas d’un triangle rectangle, un des angles vaut $\pi/2$ et
leur somme s’écrit :

$$ \alpha + \beta + \frac{\pi}{2} = \pi $$

ou encore :

$$ \alpha + \beta = \pi - \frac{\pi}{2} $$

et finalement :

$$ \alpha + \beta = \frac{\pi}{2} $$

Les angles non droits d’un triangle rectangle sont complémentaires.

* Angle au centre et angle inscrit

#+TOC: headlines 1 local

** Première disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-1.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

Nous allons examiner la relation entre l’angle au centre :

$$ \alpha = \abs{\anglecirc{AOB}} $$

et l’angle inscrit :

$$ \beta = \abs{\anglecirc{APB}} $$

Les segments $[O,A]$, $[O,B]$ et $[O,P]$ étant des rayons du cercle, on
a :

$$ r = \abs{OA} = \abs{OB} = \abs{OP} $$

La somme des angles dans le triangle $POB$ nous donne :

$$ 2 \ \gamma + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - 2 \ \gamma $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ 2 \ \lambda + \theta = 180^\circ $$

ou encore :

$$ \theta = 180^\circ - 2 \ \lambda $$

Comme les angles $\alpha$, $\delta$ et $\theta$ forment ensemble un tour
complet (un angle plein), on a :

$$ \alpha + \delta + \theta = 360^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ \alpha + (180^\circ - 2 \ \gamma) + (180^\circ - 2 \ \lambda) = 360^\circ $$

Simplifions les 360°  :

$$ \alpha - 2 \ \gamma - 2 \ \lambda = 0 $$

isolons $\alpha$ :

$$ \alpha = 2 \ \gamma + 2 \ \lambda $$

et mettons les $2$ en évidence :

$$ \alpha = 2 \ (\gamma + \lambda) $$

Comme :

$$ \beta = \gamma + \lambda $$

cette équation devient :

$$ \alpha = 2 \ \beta $$

L’amplitude de l’angle au centre vaut le double de l’amplitude de
l’angle inscrit.

** Deuxième disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-2.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

Nous allons examiner la relation entre l’angle au centre $\alpha$
et l’angle inscrit $\beta$.

Les segments $[O,A]$, $[O,B]$ et $[O,P]$ étant des rayons du cercle, on
a :

$$ r = \abs{OA} = \abs{OB} = \abs{OP} $$

Par symétrie dans le triangle $PAO$, on a aussi :

$$ \theta = \beta + \gamma $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ \beta + \gamma + \theta + \delta = 180^\circ $$

En tenant compte de la symétrie, cette équation devient :

$$ \beta + \gamma + \beta + \gamma + \delta = 180^\circ $$

ou encore :

$$ 2 \ \beta + 2 \ \gamma + \delta = 180^\circ $$

La somme des angles dans le triangle $PBO$ nous donne :

$$ 2 \ \gamma + \alpha + \delta = 180^\circ $$

En soustrayant cette dernière équation de la précédente, on obtient :

$$ 2 \ \beta + 2 \ \gamma + \delta - 2 \ \gamma - \alpha - \delta = 0 $$

c’est-à-dire :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Troisième disposition

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$
et de rayon $r$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit-3.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

Nous allons examiner la relation entre l’angle au centre $\alpha$
et l’angle inscrit $\beta$.

Les angles $\alpha$ et $\delta$ forment ensemble un angle plat :

$$ \alpha + \delta = 180^\circ $$

Isolons $\delta$ :

$$ \delta = 180^\circ - \alpha  $$

La somme des angles du triangle $POB$ nous donne :

$$ 2 \ \beta + \delta = 180^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ 2 \ \beta + 180^\circ - \alpha = 180^\circ $$

Simplifions les 180°  :

$$ 2 \ \beta - \alpha = 0 $$

Isolons $\alpha$ :

$$ \alpha  = 2 \ \beta $$

Ici aussi, l’amplitude de l’angle au centre vaut le double de
l’amplitude de l’angle inscrit.

** Synthèse

Lorsque les côtés d’un angle au centre ont les mêmes points
d’intersection avec le cercle que les côtés d’un angle inscrit,
l’angle au centre vaut toujours le double de l’angle inscrit.

* Triangle et cercle

#+TOC: headlines 1 local

** Cercle circonscrit

On dit que le cercle $\mathscr{C}$ est circonscrit au triangle
$\mathcal{T}$, ou que $\mathcal{T}$ est inscrit dans $\mathscr{C}$,
si tous les sommets de $\mathcal{T}$ appartiennent à $\mathscr{C}$.

** Diamètre comme côté d’un triangle
:properties:
:custom_id: heading:diametre_comme_cote_d_un_triangle
:end:

Le schéma ci-dessous représente un triangle $ABC$ dont le côté $[A,B]$
est un diamètre du cercle circonscrit $\mathscr{C}$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/diametre-comme-cote-d-un-triangle.svg]]

Nous avons tenu compte de la symétrie dans la notation des angles.

Le côté $[A,B]$ passe donc par le centre $O$ du cercle $\mathscr{C}$.
Les points $A$, $O$ et $B$ sont donc alignés; ce qui signifie que les
angles $\alpha$ et $\delta$ forment ensemble un angle plat :

$$ \alpha + \delta = 180^\circ $$

*** Triangle rectangle

La somme des angles du triangle $AOC$ nous donne :

$$ \alpha + 2 \ \beta = 180^\circ $$

La somme des angles du triangle $OBC$ nous donne :

$$ \delta + 2 \ \gamma = 180^\circ $$

En sommant ces deux dernières équations, on obtient :

$$ \alpha + 2 \ \beta + \delta + 2 \ \gamma = 360^\circ $$

Faisons passer $\alpha$ et $\delta$ dans le membre de droite :

$$ 2 \ \beta + 2 \ \gamma = 360^\circ - \alpha - \delta $$

ou encore :

$$ 2 \ \beta + 2 \ \gamma = 360^\circ - (\alpha + \delta) $$

En tenant compte de l’alignement de $A$, $O$ et $B$, on obtient :

$$ 2 \ \beta + 2 \ \gamma = 360^\circ - 180^\circ = 180^\circ $$

Mettons les $2$ en évidence :

$$ 2 \ (\beta + \gamma) = 180^\circ $$

Comme :

$$ \theta = \beta + \gamma $$

notre équation devient :

$$ 2 \ \theta = 180^\circ $$

c’est-à-dire :

$$ \theta = 90^\circ $$

Le triangle $ABC$ est donc un triangle rectangle.

Nous venons de montrer que tout triangle inscrit dans un cercle et dont
un des côtés est un diamètre est un triangle rectangle. Pour construire
un triangle rectangle, il suffit donc :

- de tracer un diamètre du cercle
- de choisir un troisième sommet du triangle sur le cercle
- de relier les extrémités du diamètre au troisième somme choisi

*** Angle inscrit

Les côtés de l’angle inscrit $\theta$ intersectent le
cercle aux mêmes points que les côtés de l’angle au centre
$\anglecirc{AOB}$. Comme l’amplitude de ce dernier vaut 180°, on
obtient le même résultat que précédemment :

$$ \theta = \frac{180^\circ}{2} = 90^\circ $$

* Triangles isométriques

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits isométriques si leur côtés correspondants sont
de même longueur et leurs angles correspondants de même amplitude. Le
schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques.svg]]

avec :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Notation

Si deux triangles $T_1$ et T_2$ sont isométriques, on le note :

$$ T_1 \cong T_2 $$

*Remarque* : attention à ne pas confondre le symbole d’isométrie $\cong$
avec l’égalité approximative $\approx$ ou $\simeq$.

** Équivalence

On vérifie aisément que la relation d’isométrie est une équivalence.
