
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définitions

#+TOC: headlines 1 local

** Triangle

Un triangle est une figure géométrique délimitée par trois segments
reliant trois points pour former un circuit fermé. Chaque point du
circuit est appelé *sommet* du triangle, tandis que chaque segment est
appelé *côté* du triangle.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle.svg]]

Le schéma ci-dessus représente un exemple de triangle de sommets $A$,
$B$ et $C$ délimité par les côtés :

$$ a = [B,C] $$

$$ b = [C,A] $$

$$ c = [A,B] $$

On définit généralement un triangle par la liste de ces sommets. Le
triangle du schéma ci-dessus est appelé triangle $ABC$.

** Catégories

- un triangle rectangle est un triangle dont un des angles est un angle droit
- un triangle isocèle est un triangle qui possède deux côtés de longueurs égales
- un triangle équilatéral est un triangle dont les trois côtés sont de longueurs égales
- un triangle acutangle est un triangle dont tous les angles sont aigus
- un triangle obtusangle est un triangle dont un des angles est obtus

* Objets liés au triangle

#+TOC: headlines 1 local

** Hauteur

Une hauteur est un segment qui part d’un sommet du triangle et qui
est perpendiculaire au côté opposé.

** Médiane

Une médiane est un segment qui part d’un sommet du triangle jusqu’au
milieu du côté opposé.

** Bissectrice

Une bissectrice est un segment qui part d’un sommet du triangle et
qui coupe l’angle lié à ce sommet en deux parties égales.

** Médiatrice

Une médiatrice d’un triangle est tout simplement la médiatrice d’un
des côtés.

* Angles

#+TOC: headlines 1 local

** Somme des angles d’un triangle

La figure ci-dessous représente un triangle $ABC$, une droite $a$
qui prolonge le côté $[A,B]$ et une droite $b$ parallèle à $a$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-triangle.svg]]

La notation des angles tient compte de l’égalité des angles
alternes-internes formés par les droites $a$, $b$, $c$ et $d$.

Ce schéma nous montre que les angles $\alpha$, $\beta$ et $\gamma$
forment ensemble un angle plat :

$$ \alpha + \beta + \gamma = 180^\circ $$

Ces trois angles ayant les mêmes amplitudes que les angles internes du
triangle $ABC$, on en déduit que la somme des angles d’un triangle
vaut 180°.

** Triangle rectangle

#+TOC: headlines 1 local

*** Hypothénuse et cathètes

Dans un triangle rectangle :

- le plus long côté est appelé hypothénuse
- les deux autres côtés, appelés cathètes, sont adjacents à l’angle droit

*** Somme des angles

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-triangle-rectangle.svg]]

Dans le cas d’un triangle rectangle, un des angles vaut $\pi/2$ et
leur somme s’écrit :

$$ \alpha + \beta + \frac{\pi}{2} = \pi $$

ou encore :

$$ \alpha + \beta = \pi - \frac{\pi}{2} $$

et finalement :

$$ \alpha + \beta = \frac{\pi}{2} $$

Les angles non droits d’un triangle rectangle sont complémentaires.

** Triangle équilatéral

Un triangle équilatéral est un triangle dont les trois côtés sont de
longueur égale. Par symétrie, les trois angles sont alors d’amplitude
égale. Soit $\alpha$ cette amplitude. On a :

$$ 3 \ \alpha = \pi = 180^\circ $$

et donc :

$$ \alpha = \frac{\pi}{3} = 60^\circ $$

* Angle au centre et angle inscrit

Le schéma ci-dessous représente un cercle $\mathscr{C}$ de centre $O$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angle-au-centre-et-angle-inscrit.svg]]

Nous allons examiner la relation entre l’angle au centre :

$$ \alpha = \abs{\anglecirc{AOB}} $$

et l’angle inscrit :

$$ \beta = \abs{\anglecirc{APB}} $$

Les segments $[O,A]$, $[O,B]$ et $[O,P]$ étant des rayons du cercle, on
a :

$$ r = \abs{OA} = \abs{OB} = \abs{OP} $$

Par symétrie, on a aussi :

$$ \gamma = \delta $$

$$ \lambda = \mu $$

La somme des angles dans le triangle $PAO$ nous donne :

$$ 2 \ \gamma + \theta = 180^\circ $$

ou encore :

$$ \theta = 180^\circ - 2 \ \gamma $$

La somme des angles dans le triangle $POB$ nous donne :

$$ 2 \ \lambda + \sigma = 180^\circ $$

ou encore :

$$ \sigma = 180^\circ - 2 \ \lambda $$

Comme les angles $\alpha$, $\theta$ et $\sigma$ forment ensemble un tour
complet (un angle plein), on a :

$$ \alpha + \theta + \sigma = 360^\circ $$

En tenant compte des résultats précédents, cette équation devient :

$$ \alpha + (180^\circ - 2 \ \gamma) + (180^\circ - 2 \ \lambda) = 360^\circ $$

Simplifions les 360°  :

$$ \alpha - 2 \ \gamma - 2 \ \lambda = 0 $$

isolons $\alpha$ :

$$ \alpha = 2 \ \gamma + 2 \ \lambda $$

et mettons les $2$ en évidence :

$$ \alpha = 2 \ (\gamma + \lambda) $$

Comme :

$$ \beta = \gamma + \lambda $$

cette équation devient :

$$ \alpha = 2 \ \beta $$

L’amplitude de l’angle au centre vaut le double de l’amplitude de
l’angle inscrit.

* Construction

#+TOC: headlines 1 local

** Triangles quelconques

#+TOC: headlines 1 local

*** Longueur des trois cotés

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/construction-triangle-ccc.svg]]

*** Côté - angle - côté

*** Angle - côté - angle

** Triangle rectangle

#+TOC: headlines 1 local

*** Deux cathètes

*** Cathète et hypothénuse

*** Cathète et angle

*** Hypothénuse et angle

* Triangles isométriques

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits isométriques si leur côtés correspondants sont
de même longueur et leurs angles correspondants de même amplitude. Le
schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques.svg]]

avec :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Conditions pour avoir des triangles isométriques

Pour que deux triangles soient isométriques, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

- un côté de même longueur entre deux angles de même amplitude. Par
  exemple :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

- un angle de même amplitude compris entre deux côtés de même longueur.
  Par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$
