
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles rectangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Proportions

#+TOC: headlines 1 local

** Cathètes

Soit les triangles rectangles $ABC$ et $ADE$, qui partagent un même
angle $\alpha$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proportions-triangle-rectangle-cathetes.svg]]

On définit :

$$ a = \abs{AB} $$

$$ b = \abs{BC} $$

$$ c = \abs{CA} $$

$$ d = \abs{BD} $$

$$ e = \abs{DF} $$

$$ f = \abs{FE} $$

$$ g = \abs{EC} $$

$$ h = \abs{CF} $$

Les segments $[B,C]$ et $[D,E]$ sont tous deux perpendiculaires à $[A,D]$
et sont donc parallèles :

$$ [B,C] \parallel [D,E] $$

La distance entre deux droites parallèles étant constante, on a :

$$ h = d $$

Le quadrilatère $BDFC$ est de toute évidence un rectangle et :

$$ b = e $$

L’aire $\mathcal{A}$ du triangle rectangle $ADE$ vaut :

$$ \mathcal{A} = \frac{(a + d) \ (e + f)}{2} $$

ou encore :

$$ \mathcal{A} = \frac{(a + h) \ (b + f)}{2} $$

Distribuons :

$$ \mathcal{A} = \frac{a \ b + a \ f + b \ h + f \ h}{2} $$

L’aire $A_1$ du triangle rectangle $ABC$ vaut :

$$ A_1 = \frac{a \ b}{2} $$

L’aire $A_2$ du triangle rectangle $BDC$ vaut :

$$ A_2 = \frac{b \ d}{2} = \frac{b \ h}{2} $$

L’aire $A_3$ du triangle rectangle $CDF$ vaut :

$$ A_3 = \frac{e \ h}{2} = \frac{b \ h}{2} $$

L’aire $A_4$ du triangle rectangle $CFE$ vaut :

$$ A_4 = \frac{f \ h}{2} $$

Ces quatre triangles subdivisent le triangle rectangle $ADE$. L’aire
totale du triangle $ADE$ est donc égale à la somme des $A_i$ :

$$ \mathcal{A} = \sum_{i=1}^4 A_i $$

Remplaçons ces aires par leurs expressions :

$$ \frac{a \ b + a \ f + b \ h + f \ h}{2} = \frac{a \ b + b \ h + b \ h + f \ h}{2} $$

Multiplions par deux :

$$ a \ b + a \ f + b \ h + f \ h = a \ b + b \ h + b \ h + f \ h $$

Simplifions :

$$ a \ f = b \ h $$

Divisons par $a \ b$ :

$$ \frac{f}{b} = \frac{h}{a} $$

Notons :

$$ \rho = \frac{f}{b} = \frac{h}{a} = \frac{d}{a} $$

Comparons les cathètes horizontales des triangles $ADE$ et $ABC$ :

$$ \frac{\abs{AD}}{\abs{AB}}
= \frac{a + d}{a}
= 1 + \frac{d}{a}
= 1 + \rho $$

et leurs cathètes verticales :

$$ \frac{\abs{DE}}{\abs{BC}}
= \frac{e + f}{b}
= \frac{b + f}{b}
= 1 + \frac{f}{b}
= 1 + \rho $$

Posons :

$$ \varphi = 1 + \rho $$

On a :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{DE}}{\abs{BC}} $$

Les cathètes de deux triangles rectangles qui partagent un même angle
$\alpha$ respectent les mêmes proportions.

** Hypothénuse

* Théorème de Pythagore

#+TOC: headlines 1 local

** Preuve par les triangles semblables

** Preuve par le carré environnant

Soit le triangle :

#+attr_html: :width 23%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/longueurs-triangle-rectangle.svg]]

Nous allons montrer une importante relation entre les longueurs $a,b,c$
en utilisant le schéma suivant :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/pythagore.svg]]

Aire de chaque triangle rectangle :

$$ A_T = \frac{a b}{2} $$

Aire du grand carré d’après son côté $a+b$ :

$$ A = (a+b)^2 = a^2 + 2 \ a \ b + b^2 $$

Aire du grand carré exprimé comme la somme des aires du carré et
des triangles qu’il contient :

$$ A = c^2 + 4 \cdot A_T = c^2 + 4 \cdot \frac{a \ b}{2} = c^2 + 2 \ a \ b $$

Comme les deux expressions de $A$ sont égales, on a :

$$ a^2 + 2 \ a \ b + b^2 = c^2 + 2 \ a \ b $$

ce qui donne en simplifiant :

$$ a^2 + b^2 = c^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

La longueur $c$ étant un réel positif, on en déduit immédiatement que :

$$ c = \sqrt{a^2 + b^2} $$

** Triangles de Pythagore

Un triangle de Pythagore est un triangle rectangle où les longueurs
des trois côtés sont des nombres entiers.

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-pythagore.svg]]

La figure ci-dessus utilise une astuce algébrique pour obtenir certains
triangles de Pythagore. En effet :

\begin{align*}
A^2 + B^2
&= \left(a^2 - b^2\right)^2 + \left(2 \ a \ b\right)^2 \\
&= a^4 - 2 \ a^2 \ b^2 + b^4 + 4 \ a^2 \ b^2 \\
&= a^4 + 2 \ a^2 \ b^2 + b^4 \\
&= \left(a^2 + b^2\right)^2
\end{align*}

et finalement :

$$ A^2 + B^2 = C^2 $$

Choisir de telles expressions pour $A$, $B$, $C$ nous assure d’avoir
des longueurs qui respectent le théorème de Pythagore. De plus, si
les longueurs $a$, $b$, $c$ sont entières, les longueurs $A$, $B$,
$C$ le seront également. Le tableau suivant nous donne les premiers
triangles de Pythagore obtenus avec cette méthode.

| $a$ | $b$ | $A$ | $B$ | $C$ |
|-----+-----+-----+-----+-----|
|   2 |   1 |   3 |   4 |   5 |
|   3 |   2 |   5 |  12 |  13 |
|   4 |   1 |   8 |  15 |  17 |
|   4 |   3 |   7 |  24 |  25 |
|   5 |   2 |  20 |  21 |  29 |
|   5 |   4 |   9 |  40 |  41 |
|   6 |   1 |  12 |  35 |  37 |
|   6 |   5 |  11 |  60 |  61 |
|   7 |   2 |  28 |  45 |  53 |
|   7 |   4 |  33 |  56 |  65 |
|   7 |   6 |  13 |  84 |  85 |

** Propriétés des cathètes

Examinons le triangle rectangle ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cathetes.svg]]

L’hypothénuse $c$ y est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle rectangle principal en deux
triangles rectangles : $a,h,u$ et $b,h,c$.

*** Carré de la hauteur

Le théorème de Pythagore appliqué au triangle rectangle principal nous
donne :

$$ a^2 + b^2 = c^2 $$

On sait déjà que $c = u + v$. Par ailleurs, le théorème de Pythagore
appliqué au triangle rectangle de gauche nous donne :

$$ h^2 + u^2 = a^2 $$

Le théorème de Pythagore appliqué au triangle rectangle de droite nous
donne :

$$ h^2 + v^2 = b^2 $$

On peut se servir de ces expressions pour substituer les valeurs de $a$
et $b$ dans le triangle principal :

$$ (h^2 + u^2) + (h^2 + v^2) = (u+v)^2 $$

ou encore :

$$ 2 \ h^2 + u^2 + v^2 = u^2 + 2 \ u \ v + v^2 $$

En simplifiant, il vient :

$$ 2 \ h^2 = 2 \ u \ v $$

On obtient finalement :

$$ h^2 = u \ v $$

*** Carré des cathètes

On reprend le théorème de Pythagore dans le triangle de gauche :

$$ a^2 = u^2 + h^2 $$

et on remplace le carré de la hauteur par le produit $u\ v$ :

$$ a^2 = u^2 + u \ v $$

On met ensuite $u$ en évidence :

$$ a^2 = u \ (u + v) $$

ce qui nous donne :

$$ a^2 = u \ c $$

On utilise le même procédé dans le triangle de droite :

\begin{align*}
b^2
&= v^2 + h^2 \\
&= v^2 + u \ v \\
&= v \ (u + v) \\
\end{align*}

ce qui nous donne :

$$ b^2 = v \ c $$

*** Produit des cathètes

En multipliant les équations :

$$ a^2 = u \ c $$

$$ b^2 = v \ c $$

ensemble, on obtient :

$$ a^2 \ b^2 = u \ c \ v \ c $$

ou encore :

$$ a^2 \ b^2 = u \ v \ c^2 $$

Le produit $u \ v$ étant identique à la hauteur, on a :

$$ a^2 \ b^2 = h^2 \ c^2 $$

et finalement :

$$ a \ b = h \ c $$

* Distance entre un point et une droite

* Racines carrées

