
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles rectangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles rectangles semblables

#+TOC: headlines 1 local

** Un angle commun

#+TOC: headlines 1 local

*** Isométries

#+TOC: headlines 1 local

**** Première disposition

Considérons deux triangles rectangles $ABC$ et $XYZ$ qui ont un angle
$\alpha$ de même amplitude, en plus de leur angle droit :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle.svg]]

Appliquons une translation de vecteur $\vecteur{XA}$ au triangle $XYZ$,
pour amèner le sommet $X$ au point $A$. On obtient alors un nouveau
triangle $X_2 Y_2 Z_2$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-translation.svg]]

Effectuons ensuite une rotation de centre $A$ et d’angle $\beta$ pour
amener $[X_2,Y_2]$ dans la demi-droite $[A,B)$ et $[X_2,Z_2]$ dans la
demi-droite $[A,C)$. On obtient alors un nouveau triangle $X_3 Y_3 Z_3$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-rotation.svg]]

Nous avons donc amené le sommet $X$ au point $A = X_3$, et les côtés
adjacents à ce sommet sont inclus dans les demi-droites $[A,B)$
et $[A,C)$. Les sommets de l’angle de même amplitude sont donc
confondus, tandis que les côtés de cet angle sont placés dans les
mêmes demi-droites. Pour obtenir ce résultat, nous n’avons utilisé
que des isométries. Comme les isométries conservent les angles et les
distances, les résultats obtenus pour le triangle transformé $X_3 Y_3
Z_3$ sont aussi valables pour le triangle $XYZ$ original.

**** Seconde disposition

Considérons deux triangles rectangles $ABC$ et $XYZ$ qui ont un angle
$\alpha$ de même amplitude, en plus de leur angle droit, mais cette
fois dans une disposition où le triangle $XYZ$ est un miroir du cas
précédent :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir.svg]]

Appliquons une translation de vecteur $\vecteur{XA}$ au triangle $XYZ$,
pour amèner le sommet $X$ au point $A$. On obtient alors un nouveau
triangle $X_2 Y_2 Z_2$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir-translation.svg]]

Effectuons ensuite une rotation de centre $A$ et d’angle $\beta$
pour amener $[X_2,Y_2]$ dans la demi-droite $[A,B)$. On obtient alors
un nouveau triangle $X_3 Y_3 Z_3$ :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir-rotation.svg]]

Le côté $[X_3,Z_3]$ n’est pas inclus dans la demi-droite $[AC)$. Pour
y remédier, on applique une symétrie orthogonale d’axe $(AB)$ au
triangle $X_3 Y_3 Z_3$. On obtient alors un nouveau triangle $X_4 Y_4
Z_4$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir-symetrie-orthogonale.svg]]

Nous avons donc amené le sommet $X$ au point $A = X_4$, et les côtés
adjacents à ce sommet sont inclus dans les demi-droites $[A,B)$
et $[A,C)$. Les sommets de l’angle de même amplitude sont donc
confondus, tandis que les côtés de cet angle sont placés dans les
mêmes demi-droites. Pour obtenir ce résultat, nous n’avons utilisé
que des isométries. Comme les isométries conservent les angles et les
distances, les résultats obtenus pour le triangle transformé $X_4 Y_4
Z_4$ sont aussi valables pour le triangle $XYZ$ original.

*** Cathètes

Considérons deux triangles rectangles qui ont un angle $\alpha$ de même
amplitude, en plus de leur angle droit. Nous avons vu précédemment
qus nous pouvons utiliser une série d’isométries pour que ces angles
partagent un même sommet et des mêmes demi-droites, ce qui les amène
dans la position des triangles rectangles $ABC$ et $ADE$, représentés
ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-cathetes.svg]]

On définit :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{BC} $$

$$ d = \abs{BD}
\qquad \qquad \qquad
f = \abs{DF} $$

$$ g = \abs{FE}
\qquad \qquad \qquad
h = \abs{CF} $$

Le quadrilatère $BDFC$ possède quatre angles droits :

- la hauteur $h$ est perpendiculaire à $[D,F]$
- les angles $\angleflex{FDB}$ et $\angleflex{DBC}$ sont
  les angles droits de triangles rectangles

L’amplitude du dernier angle vaut :

$$ \abs{\angleflex{BCF}} = 360^\circ - 3 \cdot 90^\circ = 90^\circ $$

Le quatrième angle est donc aussi un angle droit. Le quadrilatère $BDFC$
est donc un rectangle et :

$$ h = d $$

$$ b = f $$

L’aire $\mathcal{A}$ du triangle rectangle $ADE$ vaut :

$$ \mathcal{A} = \frac{(a + d) \ (f + g)}{2} $$

ou encore :

$$ \mathcal{A} = \frac{(a + d) \ (b + g)}{2} $$

Distribuons :

$$ \mathcal{A} = \frac{a \ b + a \ g + b \ d + d \ g}{2} $$

L’aire $A_1$ du triangle rectangle $ABC$ vaut :

$$ A_1 = \frac{a \ b}{2} $$

L’aire $A_2$ du triangle rectangle $BDC$ vaut :

$$ A_2 = \frac{b \ d}{2} $$

L’aire $A_3$ du triangle rectangle $CDF$ vaut :

$$ A_3 = \frac{f \ d}{2} = \frac{b \ d}{2} $$

L’aire $A_4$ du triangle rectangle $CFE$ vaut :

$$ A_4 = \frac{g \ h}{2} = \frac{d \ g}{2} $$

Ces quatre triangles forment une partition du triangle rectangle
$ADE$. L’aire de ce triangle est donc égale à la somme des $A_i$ :

$$ \mathcal{A} = \sum_{i=1}^4 A_i $$

Remplaçons ces aires par leurs expressions :

$$ \frac{a \ b + a \ g + b \ d + d \ g}{2} = \frac{a \ b + b \ d + b \ d + d \ g}{2} $$

Multiplions par deux :

$$ a \ b + a \ g + b \ d + d \ g = a \ b + b \ d + b \ d + d \ g $$

Simplifions :

$$ a \ g = b \ d $$

Divisons par $a \ b$ :

$$ \frac{g}{b} = \frac{d}{a} $$

Notons :

$$ \rho = \frac{g}{b} = \frac{d}{a} $$

Comparons les cathètes horizontales des triangles $ADE$ et $ABC$ :

$$ \frac{\abs{AD}}{\abs{AB}}
= \frac{a + d}{a}
= 1 + \frac{d}{a}
= 1 + \rho $$

et leurs cathètes verticales :

$$ \frac{\abs{DE}}{\abs{BC}}
= \frac{f + g}{b}
= \frac{b + g}{b}
= 1 + \frac{g}{b}
= 1 + \rho $$

Posons :

$$ \varphi = 1 + \rho $$

On a :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{DE}}{\abs{BC}} $$

Étant donnés deux triangles rectangles qui possèdent un angle de même
amplitude, la proportion entre les premières cathètes est identique
à la proportion entre les secondes cathètes. En multipliant par
$\abs{BC}/\abs{AD}$, on obtient la forme équivalente :

$$ \frac{\abs{BC}}{\abs{AB}} = \frac{\abs{DE}}{\abs{AD}} $$

Le rapport entre les cathètes est le même dans chacun des deux
triangles.

*** Hypothénuse

Considérons deux triangles rectangles qui ont un angle $\alpha$ de
même amplitude, en plus de leur angle droit. Comme l’angle droit est
par définition de même amplitude dans ces deux triangles, nous pouvons
utiliser une série d’isométries pour que ces angles partagent un même
sommet et des mêmes demi-droites, ce qui les amène dans la position
des triangles rectangles $ABC$ et $ADE$, représentés ci-dessous :

#+attr_html: :width 42%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-hypothenuse.svg]]

Les angles correspondants $\alpha$ étant de même amplitude, les
segments $[B,C]$ et $[D,E]$ sont parallèles. La hauteur $[A,G]$
étant perpendiculaire au segment $[D,E]$, elle doit donc être aussi
perpendiculaire au segment $[B,C]$, comme indiqué sur le schéma. Comme
$ABC$ et $ADE$ sont des triangles rectangles, on a aussi :

$$ \beta = \gamma = 90^\circ - \alpha $$

On définit :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{BC}
\qquad \qquad \qquad
f = \abs{AF} $$

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE}
\qquad \qquad \qquad
k = \abs{DE}
\qquad \qquad \qquad
g = \abs{AG} $$

$$ u = \abs{AF}
\qquad \qquad \qquad
v = \abs{FC}
\qquad \qquad \qquad
w = \abs{DG}
\qquad \qquad \qquad
z = \abs{GE} $$

Comme les triangles rectangles $ABC$ et $ADE$ possèdent un angle $\alpha$ de même
amplitude, on a le rapport entre les cathètes :

$$ \varphi = \frac{d}{a} = \frac{e}{b} $$

ou encore :

$$ d = \varphi \ a $$

$$ e = \varphi \ b $$

Examinons à présent les triangles intérieurs. Comme les triangles
rectangles $ABF$ et $ADG$ possèdent un angle $\alpha$ de même amplitude,
on a le rapport entre les cathètes :

$$ \phi = \frac{w}{u} = \frac{g}{f} $$

Les triangles rectangles $AFC$ et $AGE$ possèdent aussi un angle $\beta =
\gamma$ de même amplitude et :

$$ \psi = \frac{z}{v} = \frac{g}{f} $$

Ces deux derniers ratios sont donc identiques :

$$ \psi = \frac{g}{f} = \phi $$

avec comme conséquence immédiate :

$$ \frac{z}{v} = \psi = \phi = \frac{w}{u} = \frac{g}{f} $$

relations que l’on peut réécrire :

$$ w = \phi \ u $$

$$ z = \phi \ v $$

$$ g = \phi \ f $$

La grande hypothénuse $k$ vérifie :

$$ k = w + z = \phi \ u + \phi \ v = \phi \ (u + v) $$

Comme la petite hypothénuse $c$ vérifie :

$$ c = u + v $$

on a finalement :

$$ k = \phi \ c $$

Nous avons vu dans le
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle_corollaire][corollaire]]
de la
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle][section
concernant l’aire du triangle rectangle]] que le produit des cathètes
est égal au produit de l’hypothénuse par la hauteur qui lui est
perpendiculaire. Dans le triangle rectangle $ABC$, cela nous donne :

$$ a \ b = c \ f $$

Dans le triangle rectangle $ADE$, on a :

$$ d \ e = k \ g $$

En tenant compte des ratios précédent, cette équation devient :

$$ \varphi^2 \ a \ b = \phi^2 c \ f $$

On peut simplifier cette relation en utilisant l’égalité $a \ b = c \ f$ :

$$ \varphi^2 = \phi^2 $$

Comme $\varphi$ et $\phi$ sont des rapports de longueurs, ce sont des
réels positifs. Il suffit de prendre la racine de la dernière équation
pou obtenir :

$$ \varphi = \phi $$

Tous les ratios de ces triangles sont identiques et :

$$ \varphi = \frac{d}{a} = \frac{e}{b} = \frac{k}{c} = \frac{g}{f} $$

Étant donnés deux triangles rectangles qui possèdent un angle $\alpha$
de même amplitude, la proportion entre :

- les premières cathètes
- les secondes cathètes
- les hypothénuses
- les hauteurs perpendiculaires aux hypothénuses

est le même dans chacun des deux triangles. Les trois côtés des deux
triangles respectent donc la même proportion. Les deux autres angles
sont aussi de même amplitude :

- l’autre angle aigu qui vaut $\beta = 90^\circ - \alpha$
- l’angle droit

On en conclut que deux triangles rectangles qui possèdent un angle de
même amplitude sont des triangles semblables.

* Théorème de Pythagore

#+TOC: headlines 1 local

** Par les triangles semblables

Examinons le triangle rectangle $ABC$ ci-dessous :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-pythagore-par-triangles-semblables.svg]]

On définit :

$$ a = \abs{BC}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{AB} $$

$$ h = \abs{CD}
\qquad \qquad \qquad
u = \abs{AD}
\qquad \qquad \qquad
v = \abs{DB} $$

L’hypothénuse $c$ est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle principal en deux triangles
rectangles : $ADC$ et $DBC$.

Les triangles rectangles $ABC$ et $ADC$ ont un angle $\alpha$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{u}{b} = \frac{b}{c} $$

En isolant $u$, on obtient :

$$ u = \frac{b^2}{c} $$

Les triangles rectangles $ABC$ et $DBC$ ont un angle $\beta$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{v}{a} = \frac{a}{c} $$

En isolant $v$, on obtient :

$$ v = \frac{a^2}{c} $$

L’hypothénuse $c$ vérifie :

$$ c = u + v = \frac{b^2}{c} + \frac{a^2}{c} $$

En multipliant par $c$, on obtient la relation :

$$ c^2 = b^2 + a^2 $$

ou encore :

$$ c^2 = a^2 + b^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

La longueur $c$ étant un réel positif, on en déduit immédiatement que :

$$ c = \sqrt{a^2 + b^2} $$

** Par le carré environnant

Soit le triangle :

#+attr_html: :width 23%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/longueurs-triangle-rectangle.svg]]

Nous allons montrer une importante relation entre les longueurs $a,b,c$
en utilisant le schéma suivant :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-pythagore-par-carre.svg]]

L’aire $\mathcal{T}$ de chaque triangle rectangle vaut :

$$ \mathcal{T} = \frac{a b}{2} $$

L’aire $\mathcal{C}$ du grand carré vaut le carré de son côté $a+b$ :

$$ \mathcal{C} = (a+b)^2 = a^2 + 2 \ a \ b + b^2 $$

Cette aire $\mathcal{C}$ est aussi égale à la somme des aires du carré
et des triangles qu’il contient :

$$ \mathcal{C} = c^2 + 4 \ \mathcal{T} = c^2 + 4 \cdot \frac{a \ b}{2} = c^2 + 2 \ a \ b $$

Comme les deux expressions de $\mathcal{C}$ sont égales, on a :

$$ a^2 + 2 \ a \ b + b^2 = c^2 + 2 \ a \ b $$

ce qui donne en simplifiant :

$$ a^2 + b^2 = c^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

* Triangles de Pythagore

Un triangle de Pythagore est un triangle rectangle où les longueurs
des trois côtés sont des nombres entiers.

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-pythagore.svg]]

La figure ci-dessus utilise une astuce algébrique pour obtenir certains
triangles de Pythagore. En effet :

\begin{align*}
A^2 + B^2
&= \left(a^2 - b^2\right)^2 + \left(2 \ a \ b\right)^2 \\
&= a^4 - 2 \ a^2 \ b^2 + b^4 + 4 \ a^2 \ b^2 \\
&= a^4 + 2 \ a^2 \ b^2 + b^4 \\
&= \left(a^2 + b^2\right)^2
\end{align*}

et finalement :

$$ A^2 + B^2 = C^2 $$

Choisir de telles expressions pour $A$, $B$, $C$ nous assure d’avoir
des longueurs qui respectent le théorème de Pythagore. De plus, si
les longueurs $a$, $b$, $c$ sont entières, les longueurs $A$, $B$,
$C$ le seront également. Le tableau suivant nous donne les premiers
triangles de Pythagore obtenus avec cette méthode.

| $a$ | $b$ | $A$ | $B$ | $C$ |
|-----+-----+-----+-----+-----|
|   2 |   1 |   3 |   4 |   5 |
|   3 |   2 |   5 |  12 |  13 |
|   4 |   1 |   8 |  15 |  17 |
|   4 |   3 |   7 |  24 |  25 |
|   5 |   2 |  20 |  21 |  29 |
|   5 |   4 |   9 |  40 |  41 |
|   6 |   1 |  12 |  35 |  37 |
|   6 |   5 |  11 |  60 |  61 |
|   7 |   2 |  28 |  45 |  53 |
|   7 |   4 |  33 |  56 |  65 |
|   7 |   6 |  13 |  84 |  85 |

* Propriétés des cathètes

#+TOC: headlines 1 local

** Introduction

Examinons le triangle rectangle $ABC$ ci-dessous :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-des-cathetes.svg]]

On définit :

$$ a = \abs{BC}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{AB} $$

$$ h = \abs{CD}
\qquad \qquad \qquad
u = \abs{AD}
\qquad \qquad \qquad
v = \abs{DB} $$

L’hypothénuse $c$ est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle principal en deux triangles
rectangles : $ADC$ et $DBC$.

** Carré des cathètes

Les triangles rectangles $ABC$ et $DBC$ ont un angle $\beta$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{a}{c} = \frac{v}{a} $$

En multipliant par $a \ c$, on obtient :

$$ a^2 = v \ c $$

Les triangles rectangles $ABC$ et $ADC$ ont un angle $\alpha$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{b}{c} = \frac{u}{b} $$

En multipliant par $b \ c$, on obtient :

$$ b^2 = u \ c $$

** Carré de la hauteur

Nous avons vu dans le
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle_corollaire][corollaire]]
de la
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle][section
concernant l’aire du triangle rectangle]] que le produit des cathètes
est égal au produit de l’hypothénuse par la hauteur qui lui est
perpendiculaire. Dans le triangle rectangle $ABC$, cela nous donne :

$$ c \ h = a \ b $$

Prenons le carré de chaque membre :

$$ c^2 \ h^2 = a^2 \ b^2 $$

et ramplaçons par les expressions des carrés des cathètes en fonctions
de $u$, $v$ et $c$ :

$$ c^2 \ h^2 = v \ c \ u \ c = u \ v \ c^2 $$

En simplifiant, il vient :

$$ h^2 = u \ v $$

* Propriétés extrémales de la distance entre un point et une droite

Soit un point $A$, une droite $d$ et un segment $[A,B]$ perpendiculaire
à $d$ avec $B \in d$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-un-point-et-une-droite-minimum.svg]]

On choisit un point quelconque $C \in d$. On a :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{BC}
\qquad \qquad \qquad
c = \abs{CA} $$

Par définition :

$$ \abs{AB} = \distance(A,d) $$

Le théorème de Pythagore appliqué au triangle rectangle $ABC$ nous
donne :

$$ a^2 + b^2 = c^2 $$

Comme $b$ est un nombre réel, on a $b^2 \ge 0$ et :

$$ a^2 \le c^2 $$

c’est-à-dire :

$$ \abs{AB}^2 \le \abs{AC}^2 $$

En prenant la racine des deux membres, on obtient :

$$ \abs{AB} \le \abs{AC} $$

L’égalité est atteinte pour le choix particulier $C = B$.  Parmi tous
les points appartenant à la droite $d$, le point $B$ minimise donc la
distance avec $A$ :

$$ \abs{AB} = \min_{C \in d} \abs{AC} $$

La distance entre un point et une droite est donc minimale parmi tous
les points de la droite :

$$ \distance(A,d) = \min_{C \in d} \abs{AC} $$

On a aussi :

$$ B = \arg\min_{C \in d} \abs{AC} $$

* Racines carrées
