
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles isométriques
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Conditions d’isométrie de deux triangles
:properties:
:custom_id: heading:condition_d_isometrie_de_deux_triangles
:end:

#+TOC: headlines 1 local

** Principe d’équivalence des constructions

Chacune des [[file:constructions-de-triangles.org][techniques de
construction de triangles]] que nous avons présenté jusqu’ici produit,
soit un unique triangle, soit deux triangles isométriques.

Étant donné une technique de construction $\mathscr{T}$ et ses
données de départ $\mathscr{D}$, les longueurs et les angles des
triangles obtenus sont donc identiques, et ce quel que soit l’endroit
et l’orientation des éléments de départ de la construction.

Si deux triangles $T_1$ et $T_2$ partagent les mêmes caractéristiques
$\mathscr{D}$, on peut les reconstruire à l’identique au moyen de
$\mathscr{T}$. On en déduit que ces deux triangles sont isométriques :

$$ T_1 \cong T_2 $$

Les longueurs et leurs angles de ces triangles sont donc complètement
déterminés par les caractéristiques de $\mathscr{D}$.

** Triangles quelconques

#+TOC: headlines 1 local

*** Trois côtés de même longueur

Soit les deux triangles $ABC$ et $DEF$ présentés dans le schéma
ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques-trois-cotes.svg]]

Si les trois côtés sont de mêmes longueurs :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

*** Côté - angle - côté

Soit les deux triangles $ABC$ et $DEF$ présentés dans le schéma
ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques-cote-angle-cote.svg]]

Si les deux triangles ont un angle correspondant de même amplitude
compris entre deux côtés correspondants de mêmes longueurs :

$$ \alpha_1 = \alpha_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

*** Angle - côté - angle

Soit les deux triangles $ABC$ et $DEF$ présentés dans le schéma
ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques-angle-cote-angle.svg]]

Si les deux triangles ont un côté correspondant de même longueur
compris entre deux angles correspondants de mêmes amplitudes :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

** Triangles rectangles

#+TOC: headlines 1 local

# #+attr_html: :width 60%
# #+attr_latex: :width 0.7\linewidth
# [[file:tikz/triangles-rectangles-isometriques.svg]]

*** Deux cathètes

Soit les deux triangles rectangles $ABC$ et $DEF$ présentés dans le
schéma ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-isometriques-deux-cathetes.svg]]

Si les deux triangles rectangles ont leurs deux cathètes de même
longueur :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

*** Cathète et hypothénuse

Soit les deux triangles rectangles $ABC$ et $DEF$ présentés dans le
schéma ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-isometriques-cathete-et-hypothenuse.svg]]

Si les deux triangles rectangles ont une cathète et l’hypothénuse de mêmes
longueurs :

$$ a_1 = a_2 $$

$$ c_1 = c_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

*** Cathéte et angle adjacent

Soit les deux triangles rectangles $ABC$ et $DEF$ présentés dans le
schéma ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-isometriques-cathete-et-angle-adjacent.svg]]

Si les deux triangles rectangles ont une cathète de même
longueur adjacente à un angle de même amplitude :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

*** Cathéte et angle non adjacent

Soit les deux triangles rectangles $ABC$ et $DEF$ présentés dans le
schéma ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-isometriques-cathete-et-angle-non-adjacent.svg]]

Si les deux triangles rectangles ont une cathète de même
longueur qui n’est pas adjacente à un angle de même amplitude :

$$ a_1 = a_2 $$

$$ \alpha_1 = \alpha_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

*** Hypothénuse et angle

Soit les deux triangles rectangles $ABC$ et $DEF$ présentés dans le
schéma ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-isometriques-hypothenuse-et-angle.svg]]

Si les deux triangles rectangles ont leur hypothénuse
de même longueur et un angle d’amplitude identique :

$$ c_1 = c_2 $$

$$ \alpha_1 = \alpha_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

* Triangle isocèle

#+TOC: headlines 1 local

** Angles et médiane

Le schéma ci-dessous représente un triangle isocèle et la médiane
qui part du sommet adjacent aux côtés de longueurs égales :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-angles-et-mediane.svg]]

Par définition du triangle isocèle, on a :

$$ a = \abs{AC} = \abs{BC} $$

Par définition de la médiane, on a :

$$ b = \abs{AD} = \abs{DB} $$

On voit que les triangles $ADC$ et $DBC$ ont leurs trois côtés de mêmes
longueurs. Ils sont donc isométriques, ce qui signifie que leurs angles
sont de mêmes amplitudes. On a en particulier :

$$ \alpha = \beta $$

$$ \gamma = \delta $$

$$ \lambda = \mu $$

Comme les points $A$, $D$ et $C$ sont alignés, $\gamma$ et $\delta$
forment ensemble un angle plat :

$$ \gamma + \delta = 180^\circ $$

On en conclut que :

$$ 2 \ \gamma = 180^\circ $$

c’est-à-dire :

$$ \gamma = 90^\circ $$

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-angles-et-mediane-resolu.svg]]

On voit que :

- les deux angles adjacents à $[A,B]$ sont égaux
  + $[A,B]$ est le côté qui reste lorsqu’on retire
    les côtés de longueur égale du triangle isocèle
- la médiane $m$ est aussi une hauteur du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ et la hauteur $h$
qui part du sommet $C$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles.svg]]

Les triangles $ADC$ et $BCD$ ont leur hypothénuse de longeur égale,
et un angle adjacent d’amplitude égale. Ces deux triangles sont donc
isométriques. On a en particulier :

$$ \abs{AC} = \abs{BC} $$

$$ \abs{AD} = \abs{DB} $$

$$ \lambda = \mu $$

On a donc finalement le schéma suivant :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-condition-angles-resolu.svg]]

On voit que :

- le triangle $ABC$ est isocèle
- la hauteur $h$ est aussi une médiane du triangle $ABC$, et la
  bissectrice de l’angle $\angleflex{ACB}$

Un triangle qui a deux angles de même amplitude est donc un triangle isocèle.

* Triangle équilatéral

#+TOC: headlines 1 local

** Angles

Le schéma ci-dessous représente un triangle équilatéral $ABC$ avec
ses trois angles :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-angles.svg]]

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[B,C]$, les angles associés doivent être égaux :

$$ \alpha = \beta $$

Comme $ABC$ est un cas particulier de triangle isocèle en $[A,C]$
et $[A,B]$, les angles associés doivent être égaux :

$$ \alpha = \gamma $$

Les trois angles sont donc identiques :

$$ \alpha = \beta = \gamma $$

La somme des angles de ce triangle nous donne :

$$ \alpha + \beta + \gamma = 3 \ \alpha = 180^\circ $$

On a donc :

$$ \alpha = \frac{180^\circ}{3} = 60^\circ $$

Les angles d’un triangle équilatéral ont tous une amplitude de 60°.

** Condition suffisante

Le schéma ci-dessous représente un triangle $ABC$ qui possède trois
angles égaux :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-condition-angles.svg]]

Comme les angles $\angleflex{A}$ et $\angleflex{B}$ sont égaux, ce
triangle est isocèle en $[A,C]$ et $[B,C]$ :

$$ \abs{AC} = \abs{BC} $$

Comme les angles $\angleflex{A}$ et $\angleflex{C}$ sont égaux, ce
triangle est isocèle en $[A,B]$ et $[C,B]$ :

$$ \abs{AB} = \abs{CB} $$

Les trois côtés sont donc de longueur égale.

Un triangle qui possède trois angles égaux est un triangle équilatéral.
