
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles rectangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles rectangles semblables

#+TOC: headlines 1 local

** Un angle commun

#+TOC: headlines 1 local

*** Isométries

#+TOC: headlines 1 local

**** Première disposition

Considérons deux triangles rectangles $ABC$ et $XYZ$ qui ont un angle
$\alpha$ de même amplitude, en plus de leur angle droit :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle.svg]]

Appliquons une translation de vecteur $\vecteur{XA}$ au triangle $XYZ$,
pour amèner le sommet $X$ au point $A$. On obtient alors un nouveau
triangle $X_2 Y_2 Z_2$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-translation.svg]]

Effectuons ensuite une rotation de centre $A$ et d’angle $\beta$ pour
amener $[X_2,Y_2]$ dans la demi-droite $[A,B)$ et $[X_2,Z_2]$ dans la
demi-droite $[A,C)$. On obtient alors un nouveau triangle $X_3 Y_3 Z_3$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-rotation.svg]]

Nous avons donc amené le sommet $X$ au point $A = X_3$, et les côtés
adjacents à ce sommet sont inclus dans les demi-droites $[A,B)$
et $[A,C)$. Les sommets de l’angle de même amplitude sont donc
confondus, tandis que les côtés de cet angle sont placés dans les
mêmes demi-droites. Pour obtenir ce résultat, nous n’avons utilisé
que des isométries. Comme les isométries conservent les angles et les
distances, les résultats obtenus pour le triangle transformé $X_3 Y_3
Z_3$ sont aussi valables pour le triangle $XYZ$ original.

**** Seconde disposition

Considérons deux triangles rectangles $ABC$ et $XYZ$ qui ont un angle
$\alpha$ de même amplitude, en plus de leur angle droit, mais cette
fois dans une disposition où le triangle $XYZ$ est un miroir du cas
précédent :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir.svg]]

Appliquons une translation de vecteur $\vecteur{XA}$ au triangle $XYZ$,
pour amèner le sommet $X$ au point $A$. On obtient alors un nouveau
triangle $X_2 Y_2 Z_2$ :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir-translation.svg]]

Effectuons ensuite une rotation de centre $A$ et d’angle $\beta$
pour amener $[X_2,Y_2]$ dans la demi-droite $[A,B)$. On obtient alors
un nouveau triangle $X_3 Y_3 Z_3$ :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir-rotation.svg]]

Le côté $[X_3,Z_3]$ n’est pas inclus dans la demi-droite $[AC)$. Pour
y remédier, on applique une symétrie orthogonale d’axe $(AB)$ au
triangle $X_3 Y_3 Z_3$. On obtient alors un nouveau triangle $X_4 Y_4
Z_4$ :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-miroir-symetrie-orthogonale.svg]]

Nous avons donc amené le sommet $X$ au point $A = X_4$, et les côtés
adjacents à ce sommet sont inclus dans les demi-droites $[A,B)$
et $[A,C)$. Les sommets de l’angle de même amplitude sont donc
confondus, tandis que les côtés de cet angle sont placés dans les
mêmes demi-droites. Pour obtenir ce résultat, nous n’avons utilisé
que des isométries. Comme les isométries conservent les angles et les
distances, les résultats obtenus pour le triangle transformé $X_4 Y_4
Z_4$ sont aussi valables pour le triangle $XYZ$ original.

*** Cathètes

Considérons deux triangles rectangles qui ont un angle $\alpha$ de même
amplitude, en plus de leur angle droit. Nous avons vu précédemment
qus nous pouvons utiliser une série d’isométries pour que ces angles
partagent un même sommet et des mêmes demi-droites, ce qui les amène
dans la position des triangles rectangles $ABC$ et $ADE$, représentés
ci-dessous :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-cathetes.svg]]

On définit :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{BC} $$

$$ d = \abs{BD}
\qquad \qquad \qquad
f = \abs{DF} $$

$$ g = \abs{FE}
\qquad \qquad \qquad
h = \abs{CF} $$

Le quadrilatère $BDFC$ possède quatre angles droits :

- la hauteur $h$ est perpendiculaire à $[D,F]$
- les angles $\angleflex{FDB}$ et $\angleflex{DBC}$ sont
  les angles droits de triangles rectangles

L’amplitude du dernier angle vaut :

$$ \abs{\angleflex{BCF}} = 360^\circ - 3 \cdot 90^\circ = 90^\circ $$

Le quatrième angle est donc aussi un angle droit. Le quadrilatère $BDFC$
est donc un rectangle et :

$$ h = d $$

$$ b = f $$

L’aire $\mathcal{A}$ du triangle rectangle $ADE$ vaut :

$$ \mathcal{A} = \frac{(a + d) \ (f + g)}{2} $$

ou encore :

$$ \mathcal{A} = \frac{(a + d) \ (b + g)}{2} $$

Distribuons :

$$ \mathcal{A} = \frac{a \ b + a \ g + b \ d + d \ g}{2} $$

L’aire $A_1$ du triangle rectangle $ABC$ vaut :

$$ A_1 = \frac{a \ b}{2} $$

L’aire $A_2$ du triangle rectangle $BDC$ vaut :

$$ A_2 = \frac{b \ d}{2} $$

L’aire $A_3$ du triangle rectangle $CDF$ vaut :

$$ A_3 = \frac{f \ d}{2} = \frac{b \ d}{2} $$

L’aire $A_4$ du triangle rectangle $CFE$ vaut :

$$ A_4 = \frac{g \ h}{2} = \frac{d \ g}{2} $$

Ces quatre triangles forment une partition du triangle rectangle
$ADE$. L’aire de ce triangle est donc égale à la somme des $A_i$ :

$$ \mathcal{A} = \sum_{i=1}^4 A_i $$

Remplaçons ces aires par leurs expressions :

$$ \frac{a \ b + a \ g + b \ d + d \ g}{2} = \frac{a \ b + b \ d + b \ d + d \ g}{2} $$

Multiplions par deux :

$$ a \ b + a \ g + b \ d + d \ g = a \ b + b \ d + b \ d + d \ g $$

Simplifions :

$$ a \ g = b \ d $$

Divisons par $a \ b$ :

$$ \frac{g}{b} = \frac{d}{a} $$

Notons :

$$ \rho = \frac{g}{b} = \frac{d}{a} $$

Comparons les cathètes horizontales des triangles $ADE$ et $ABC$ :

$$ \frac{\abs{AD}}{\abs{AB}}
= \frac{a + d}{a}
= 1 + \frac{d}{a}
= 1 + \rho $$

et leurs cathètes verticales :

$$ \frac{\abs{DE}}{\abs{BC}}
= \frac{f + g}{b}
= \frac{b + g}{b}
= 1 + \frac{g}{b}
= 1 + \rho $$

Posons :

$$ \varphi = 1 + \rho $$

On a :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{DE}}{\abs{BC}} $$

Étant donnés deux triangles rectangles qui possèdent un angle de même
amplitude, la proportion entre les premières cathètes est identique
à la proportion entre les secondes cathètes. En multipliant par
$\abs{BC}/\abs{AD}$, on obtient la forme équivalente :

$$ \frac{\abs{BC}}{\abs{AB}} = \frac{\abs{DE}}{\abs{AD}} $$

Le rapport entre les cathètes est le même dans chacun des deux
triangles.

*** Hypothénuse

Considérons deux triangles rectangles qui ont un angle $\alpha$ de
même amplitude, en plus de leur angle droit. Comme l’angle droit est
par définition de même amplitude dans ces deux triangles, nous pouvons
utiliser une série d’isométries pour que ces angles partagent un même
sommet et des mêmes demi-droites, ce qui les amène dans la position
des triangles rectangles $ABC$ et $ADE$, représentés ci-dessous :

#+attr_html: :width 42%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-angle-hypothenuse.svg]]

Les angles correspondants $\alpha$ étant de même amplitude, les
segments $[B,C]$ et $[D,E]$ sont parallèles. La hauteur $[A,G]$
étant perpendiculaire au segment $[D,E]$, elle doit donc être aussi
perpendiculaire au segment $[B,C]$, comme indiqué sur le schéma. Comme
$ABC$ et $ADE$ sont des triangles rectangles, on a aussi :

$$ \beta = \gamma = 90^\circ - \alpha $$

On définit :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{BC}
\qquad \qquad \qquad
f = \abs{AF} $$

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE}
\qquad \qquad \qquad
k = \abs{DE}
\qquad \qquad \qquad
g = \abs{AG} $$

$$ u = \abs{AF}
\qquad \qquad \qquad
v = \abs{FC}
\qquad \qquad \qquad
w = \abs{DG}
\qquad \qquad \qquad
z = \abs{GE} $$

Les triangles $ABC$ et $ADE$ possèdent un angle $\alpha$ de même
amplitude. On a donc le rapport :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{AE}}{\abs{AC}} $$

Les triangles $ABG$ et $ADF$ possèdent un angle $\alpha$ de même
amplitude. On a donc le rapport :

$$ \psi = \frac{\abs{DF}}{\abs{BG}} = \frac{\abs{AF}}{\abs{AG}} $$

Les triangles $AGC$ et $AFE$ possèdent un angle $\beta = \gamma$ de
même amplitude. On a donc le rapport :

$$ \omega = \frac{\abs{FE}}{\abs{GC}} = \frac{\abs{AF}}{\abs{AG}} $$

On voit que :

$$ \omega = \frac{\abs{AF}}{\abs{AG}} = \psi $$

On en conclut que :

$$ \frac{\abs{FE}}{\abs{GC}} = \omega = \psi = \frac{\abs{DF}}{\abs{BG}} $$

* Théorème de Pythagore

#+TOC: headlines 1 local

** Preuve par les triangles semblables

** Preuve par le carré environnant

Soit le triangle :

#+attr_html: :width 23%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/longueurs-triangle-rectangle.svg]]

Nous allons montrer une importante relation entre les longueurs $a,b,c$
en utilisant le schéma suivant :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-pythagore-carre.svg]]

Aire de chaque triangle rectangle :

$$ A_T = \frac{a b}{2} $$

Aire du grand carré d’après son côté $a+b$ :

$$ A = (a+b)^2 = a^2 + 2 \ a \ b + b^2 $$

Aire du grand carré exprimé comme la somme des aires du carré et
des triangles qu’il contient :

$$ A = c^2 + 4 \cdot A_T = c^2 + 4 \cdot \frac{a \ b}{2} = c^2 + 2 \ a \ b $$

Comme les deux expressions de $A$ sont égales, on a :

$$ a^2 + 2 \ a \ b + b^2 = c^2 + 2 \ a \ b $$

ce qui donne en simplifiant :

$$ a^2 + b^2 = c^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

La longueur $c$ étant un réel positif, on en déduit immédiatement que :

$$ c = \sqrt{a^2 + b^2} $$

** Triangles de Pythagore

Un triangle de Pythagore est un triangle rectangle où les longueurs
des trois côtés sont des nombres entiers.

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-pythagore.svg]]

La figure ci-dessus utilise une astuce algébrique pour obtenir certains
triangles de Pythagore. En effet :

\begin{align*}
A^2 + B^2
&= \left(a^2 - b^2\right)^2 + \left(2 \ a \ b\right)^2 \\
&= a^4 - 2 \ a^2 \ b^2 + b^4 + 4 \ a^2 \ b^2 \\
&= a^4 + 2 \ a^2 \ b^2 + b^4 \\
&= \left(a^2 + b^2\right)^2
\end{align*}

et finalement :

$$ A^2 + B^2 = C^2 $$

Choisir de telles expressions pour $A$, $B$, $C$ nous assure d’avoir
des longueurs qui respectent le théorème de Pythagore. De plus, si
les longueurs $a$, $b$, $c$ sont entières, les longueurs $A$, $B$,
$C$ le seront également. Le tableau suivant nous donne les premiers
triangles de Pythagore obtenus avec cette méthode.

| $a$ | $b$ | $A$ | $B$ | $C$ |
|-----+-----+-----+-----+-----|
|   2 |   1 |   3 |   4 |   5 |
|   3 |   2 |   5 |  12 |  13 |
|   4 |   1 |   8 |  15 |  17 |
|   4 |   3 |   7 |  24 |  25 |
|   5 |   2 |  20 |  21 |  29 |
|   5 |   4 |   9 |  40 |  41 |
|   6 |   1 |  12 |  35 |  37 |
|   6 |   5 |  11 |  60 |  61 |
|   7 |   2 |  28 |  45 |  53 |
|   7 |   4 |  33 |  56 |  65 |
|   7 |   6 |  13 |  84 |  85 |

** Propriétés des cathètes

Examinons le triangle rectangle ci-dessous :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/cathetes.svg]]

L’hypothénuse $c$ y est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle rectangle principal en deux
triangles rectangles : $a,h,u$ et $b,h,c$.

*** Carré de la hauteur

Le théorème de Pythagore appliqué au triangle rectangle principal nous
donne :

$$ a^2 + b^2 = c^2 $$

On sait déjà que $c = u + v$. Par ailleurs, le théorème de Pythagore
appliqué au triangle rectangle de gauche nous donne :

$$ h^2 + u^2 = a^2 $$

Le théorème de Pythagore appliqué au triangle rectangle de droite nous
donne :

$$ h^2 + v^2 = b^2 $$

On peut se servir de ces expressions pour substituer les valeurs de $a$
et $b$ dans le triangle principal :

$$ (h^2 + u^2) + (h^2 + v^2) = (u+v)^2 $$

ou encore :

$$ 2 \ h^2 + u^2 + v^2 = u^2 + 2 \ u \ v + v^2 $$

En simplifiant, il vient :

$$ 2 \ h^2 = 2 \ u \ v $$

On obtient finalement :

$$ h^2 = u \ v $$

*** Carré des cathètes

On reprend le théorème de Pythagore dans le triangle de gauche :

$$ a^2 = u^2 + h^2 $$

et on remplace le carré de la hauteur par le produit $u\ v$ :

$$ a^2 = u^2 + u \ v $$

On met ensuite $u$ en évidence :

$$ a^2 = u \ (u + v) $$

ce qui nous donne :

$$ a^2 = u \ c $$

On utilise le même procédé dans le triangle de droite :

\begin{align*}
b^2
&= v^2 + h^2 \\
&= v^2 + u \ v \\
&= v \ (u + v) \\
\end{align*}

ce qui nous donne :

$$ b^2 = v \ c $$

*** Produit des cathètes

En multipliant les équations :

$$ a^2 = u \ c $$

$$ b^2 = v \ c $$

ensemble, on obtient :

$$ a^2 \ b^2 = u \ c \ v \ c $$

ou encore :

$$ a^2 \ b^2 = u \ v \ c^2 $$

Le produit $u \ v$ étant identique à la hauteur, on a :

$$ a^2 \ b^2 = h^2 \ c^2 $$

et finalement :

$$ a \ b = h \ c $$

* Distance entre un point et une droite

* Racines carrées

