
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définitions

#+TOC: headlines 1 local

** Triangle

Un triangle est une figure géométrique délimitée par trois segments
reliant trois points pour former un circuit fermé. Chaque point du
circuit est appelé *sommet* du triangle, tandis que chaque segment est
appelé *côté* du triangle.

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle.svg]]

Le schéma ci-dessus représente un exemple de triangle de sommets $A$,
$B$ et $C$ délimité par les côtés :

$$ a = [B,C] $$

$$ b = [C,A] $$

$$ c = [A,B] $$

On définit généralement un triangle par la liste de ces sommets. Le
triangle du schéma ci-dessus est appelé triangle $ABC$.

** Catégories

- un triangle isocèle est un triangle qui possède deux côtés de longueurs égales
- un triangle équilatéral est un triangle dont les trois côtés sont de longueurs égales
- un triangle rectangle est un triangle dont un des angles est un angle droit
- un triangle acutangle est un triangle dont tous les angles sont aigus
- un triangle obtusangle est un triangle dont un des angles est aigu

** Objets liés au triangle

- une médiane est un segment qui part d’un sommet du triangle jusqu’au
  milieu du côté opposé
- une hauteur est un segment qui part d’un sommet du triangle et qui est
  perpendiculaire au côté opposé
- une bissectrice est un segment qui part d’un sommet du triangle et qui coupe
  l’angle lié à ce sommet en deux parties égales

* Somme des angles d’un triangle

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/somme-angles-triangle.svg]]

La figure ci-dessus, où la droite $d$ est parallèle au côté $b$,
nous montre que la somme des angles d’un triangle vaut un angle plat,
c’est-à-dire $\pi$ ou 180° :

$$ \alpha + \beta + \gamma = \pi = 180^\circ $$

* Triangle rectangle

#+TOC: headlines 1 local

** Hypothénuse et cathètes

Dans un triangle rectangle :

- le plus long côté est appelé hypothénuse
- les deux autres côtés, appelés cathètes, sont adjacents à l’angle droit

** Somme des angles

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/angles-triangle-rectangle.svg]]

Dans le cas d’un triangle rectangle, un des angles vaut $\pi/2$ et
leur somme s’écrit :

$$ \alpha + \beta + \frac{\pi}{2} = \pi $$

ou encore :

$$ \alpha + \beta = \pi - \frac{\pi}{2} $$

et finalement :

$$ \alpha + \beta = \frac{\pi}{2} $$

Les angles non droits d’un triangle rectangle sont complémentaires.

* Triangles isométriques

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits isométriques si leur côtés correspondants sont
de même longueur et leurs angles correspondants de même amplitude. Le
schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques.svg]]

avec :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Conditions pour avoir des triangles isométriques

Pour que deux triangles soient isométriques, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

- un côté de même longueur entre deux angles de même amplitude. Par
  exemple :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

- un angle de même amplitude compris entre deux côtés de même longueur.
  Par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

* Triangles semblables

#+TOC: headlines 1 local

** Définition

Deux triangles sont dits semblables si les rapports de leurs côtés
correspondants sont les mêmes, et si leurs angles correspondants de
même amplitude. Le schéma ci-dessous nous en montre un exemple :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-semblables.svg]]

avec :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} $$

et :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

** Corollaires

Soit la relation :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} $$

Multiplions par $a_2 \cdot b_2$ :

$$ a_1 \cdot b_2 = a_2 \cdot b_1 $$

puis divisons par $b_1 \cdot b_2$ :

$$ \frac{a_1}{b_1} = \frac{a_2}{b_2} $$

On obtient par un raisonnement similaire :

$$ \frac{a_1}{c_1} = \frac{a_2}{c_2} $$

$$ \frac{b_1}{c_1} = \frac{b_2}{c_2} $$

Les rapports entre les longueurs des côtés sont les mêmes dans les deux
triangles.

** Conditions pour avoir des triangles semblables

Pour que deux triangles soient semblables, chaque condition ci-dessous
est suffisante :

- les trois côtés correspondants sont de longueurs proportionnelles :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} = \frac{c_1}{c_2} $$

- deux angles correspondants sont de même amplitude, par exemple :

$$ \alpha_1 = \alpha_2 $$

$$ \beta_1 = \beta_2 $$

Remarquons que, dans ce cas, les troisièmes angles sont forcément
de même amplitude :

$$ \gamma_2 = \pi - \alpha_2 - \beta_2 = \pi - \alpha_1 - \beta_1 = \gamma_1 $$

- deux côtés correspondants sont de longueurs proportionnelles et
  les angles qu’ils forment sont de même amplitude, par exemple :

$$ \frac{a_1}{a_2} = \frac{b_1}{b_2} $$

et :

$$ \gamma_1 = \gamma_2 $$

*** Triangles rectangles

Dans le cas de deux triangles rectangles $T_1$ et $T_2$, les deux angles
droits correspondent et sont par définition égaux. Il suffit donc
d’avoir un deuxième angle $\alpha$ identique dans les deux triangles
pour que $T_1$ et $T_2$ soient semblables.

* Triangle isocèle

#+TOC: headlines 1 local

** Définition

Un triangle isocèle est un triangle dont au moins deux côtés sont de
longueur égale.

* Triangle équilatéral

#+TOC: headlines 1 local

** Définition

Un triangle équilatéral est un triangle dont les trois côtés sont de
longueur égale. Par symétrie, les trois angles sont alors d’amplitude
égale. Soit $\alpha$ cette amplitude. On a :

$$ 3 \ \alpha = \pi = 180^\circ $$

et donc :

$$ \alpha = \frac{\pi}{3} = 60^\circ $$

* Angle et cercle

#+TOC: headlines 1 local

** Angle au centre

** Angle inscrit

** Relation
