
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles rectangles
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangles rectangles semblables

#+TOC: headlines 1 local

** Cathètes

Considérons deux triangles rectangles $ABC$ et $XYZ$ qui
possèdent un angle $\alpha$ de même amplitude, en plus de
leur angle droit. Nous avons vu dans la section qui traite de
[[file:triangles-isometriques.org::#heading:angle_de_meme_amplitude][triangles
possédant un angle de même amplitude]] que nous pouvons construire un
triangle $ADE$ isométrique à $XYZ$, tel que les deux angles $\alpha$
soient placés au même endroit :

#+attr_html: :width 35%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-cathetes.svg]]

On définit :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{BC} $$

$$ d = \abs{BD}
\qquad \qquad \qquad
f = \abs{DF} $$

$$ g = \abs{FE}
\qquad \qquad \qquad
h = \abs{CF} $$

Le quadrilatère $BDFC$ possède quatre angles droits :

- la hauteur $h$ est perpendiculaire à $[D,F]$
- les angles $\angleflex{FDB}$ et $\angleflex{DBC}$ sont
  les angles droits de triangles rectangles

L’amplitude du dernier angle vaut :

$$ \abs{\angleflex{BCF}} = 360^\circ - 3 \cdot 90^\circ = 90^\circ $$

Le quatrième angle est donc aussi un angle droit. Le quadrilatère $BDFC$
est donc un rectangle et :

$$ h = d $$

$$ b = f $$

L’aire $\mathcal{A}$ du triangle rectangle $ADE$ vaut :

$$ \mathcal{A} = \frac{(a + d) \ (f + g)}{2} $$

ou encore :

$$ \mathcal{A} = \frac{(a + d) \ (b + g)}{2} $$

Distribuons :

$$ \mathcal{A} = \frac{a \ b + a \ g + b \ d + d \ g}{2} $$

L’aire $A_1$ du triangle rectangle $ABC$ vaut :

$$ A_1 = \frac{a \ b}{2} $$

L’aire $A_2$ du triangle rectangle $BDC$ vaut :

$$ A_2 = \frac{b \ d}{2} $$

L’aire $A_3$ du triangle rectangle $CDF$ vaut :

$$ A_3 = \frac{f \ d}{2} = \frac{b \ d}{2} $$

L’aire $A_4$ du triangle rectangle $CFE$ vaut :

$$ A_4 = \frac{g \ h}{2} = \frac{d \ g}{2} $$

Ces quatre triangles forment une partition du triangle rectangle
$ADE$. L’aire de ce triangle est donc égale à la somme des $A_i$ :

$$ \mathcal{A} = \sum_{i=1}^4 A_i $$

Remplaçons ces aires par leurs expressions :

$$ \frac{a \ b + a \ g + b \ d + d \ g}{2} = \frac{a \ b + b \ d + b \ d + d \ g}{2} $$

Multiplions par deux :

$$ a \ b + a \ g + b \ d + d \ g = a \ b + b \ d + b \ d + d \ g $$

simplifions :

$$ a \ g = b \ d $$

et divisons par $a \ b$ :

$$ \frac{g}{b} = \frac{d}{a} $$

Notons :

$$ \rho = \frac{g}{b} = \frac{d}{a} $$

Comparons les cathètes horizontales des triangles $ADE$ et $ABC$ :

$$ \frac{\abs{AD}}{\abs{AB}}
= \frac{a + d}{a}
= 1 + \frac{d}{a}
= 1 + \rho $$

et leurs cathètes verticales :

$$ \frac{\abs{DE}}{\abs{BC}}
= \frac{f + g}{b}
= \frac{b + g}{b}
= 1 + \frac{g}{b}
= 1 + \rho $$

Posons :

$$ \varphi = 1 + \rho $$

On a :

$$ \varphi = \frac{\abs{AD}}{\abs{AB}} = \frac{\abs{DE}}{\abs{BC}} $$

Le rapport entre les cathètes est le même dans chacun des deux
triangles. En multipliant par $\abs{BC}/\abs{AD}$, on obtient la forme
équivalente :

$$ \frac{\abs{BC}}{\abs{AB}} = \frac{\abs{DE}}{\abs{AD}} $$

Étant donnés deux triangles rectangles qui possèdent un angle de même
amplitude, la proportion entre les premières cathètes est identique
à la proportion entre les secondes cathètes.

Comme les triangles $ADE$ et $XYZ$ sont isométriques, les triangles $ABC$
et $XYZ$ vérifient également ces propriétés.

** Hypothénuses

Considérons deux triangles rectangles $ABC$ et $XYZ$ qui possèdent un
angle $\alpha$ de même amplitude, en plus de leur angle droit. Comme
l’angle droit est par définition de même amplitude dans ces deux
triangles, nous pouvons construire un triangle $ADE$ isométrique à
$XYZ$, tel que les deux angles droits soient placés au même endroit :

#+attr_html: :width 42%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-rectangles-semblables-hypothenuses.svg]]

Les angles correspondants $\alpha$ étant de même amplitude, les
segments $[B,C]$ et $[D,E]$ sont parallèles. La hauteur $[A,G]$
étant perpendiculaire au segment $[D,E]$, elle doit donc être aussi
perpendiculaire au segment $[B,C]$, comme indiqué sur le schéma. Comme
$ABC$ et $ADE$ sont des triangles rectangles, on a aussi :

$$ \beta = \gamma = 90^\circ - \alpha $$

On définit les longueurs et la hauteur du triangle $ABC$ :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{AC}
\qquad \qquad \qquad
c = \abs{BC}
\qquad \qquad \qquad
f = \abs{AF} $$

Idem pour le triangle $ADE$ :

$$ d = \abs{AD}
\qquad \qquad \qquad
e = \abs{AE}
\qquad \qquad \qquad
k = \abs{DE}
\qquad \qquad \qquad
g = \abs{AG} $$

et pour les hypothénuses partielles :

$$ u = \abs{BF}
\qquad \qquad \qquad
v = \abs{FC}
\qquad \qquad \qquad
w = \abs{DG}
\qquad \qquad \qquad
z = \abs{GE} $$

Comme les triangles rectangles $ABC$ et $ADE$ possèdent un angle $\alpha$ de même
amplitude, on a le rapport entre les cathètes :

$$ \varphi = \frac{d}{a} = \frac{e}{b} $$

ou encore :

$$ d = \varphi \ a $$

$$ e = \varphi \ b $$

Examinons à présent les triangles intérieurs. Comme les triangles
rectangles $ABF$ et $ADG$ possèdent un angle $\alpha$ de même amplitude,
on a le rapport entre les cathètes :

$$ \phi = \frac{w}{u} = \frac{g}{f} $$

Les triangles rectangles $AFC$ et $AGE$ possèdent aussi un angle $\beta =
\gamma$ de même amplitude et :

$$ \psi = \frac{z}{v} = \frac{g}{f} $$

Ces deux derniers ratios sont donc identiques :

$$ \psi = \frac{g}{f} = \phi $$

avec comme conséquence immédiate :

$$ \frac{z}{v} = \psi = \phi = \frac{w}{u} = \frac{g}{f} $$

relations que l’on peut réécrire :

$$ w = \phi \ u $$

$$ z = \phi \ v $$

$$ g = \phi \ f $$

La grande hypothénuse $k$ vérifie :

$$ k = w + z = \phi \ u + \phi \ v = \phi \ (u + v) $$

Comme la petite hypothénuse $c$ vérifie :

$$ c = u + v $$

on a finalement :

$$ k = \phi \ c $$

Nous avons vu dans le
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle_corollaire][corollaire]]
de la
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle][section
concernant l’aire du triangle rectangle]] que le produit des cathètes
est égal au produit de l’hypothénuse par la hauteur qui lui est
perpendiculaire. Dans le triangle rectangle $ABC$, cela nous donne :

$$ a \ b = c \ f $$

Dans le triangle rectangle $ADE$, on a :

$$ d \ e = k \ g $$

En tenant compte des ratios précédent, cette équation devient :

$$ \varphi^2 \ a \ b = \phi^2 \ c \ f $$

On peut simplifier cette relation en utilisant l’égalité $a \ b = c \ f$ :

$$ \varphi^2 = \phi^2 $$

Comme $\varphi$ et $\phi$ sont des rapports de longueurs, ce sont des
réels positifs. Il suffit de prendre la racine de la dernière équation
pou obtenir :

$$ \varphi = \phi $$

Tous les ratios de ces triangles sont identiques et :

$$ \varphi = \frac{d}{a} = \frac{e}{b} = \frac{k}{c} = \frac{g}{f} $$

ou encore :

$$ \varphi
= \frac{\abs{AD}}{\abs{AB}}
= \frac{\abs{AE}}{\abs{AC}}
= \frac{\abs{DE}}{\abs{BC}}
= \frac{\abs{AG}}{\abs{AF}} $$

Étant donnés deux triangles rectangles qui possèdent un angle $\alpha$
de même amplitude, la proportion entre :

- les premières cathètes
- les secondes cathètes
- les hypothénuses
- les hauteurs perpendiculaires aux hypothénuses

est le même dans chacun des deux triangles. Les trois côtés des deux
triangles respectent donc la même proportion. Les deux autres angles
sont aussi de même amplitude :

- l’angle droit est forcément le même
- l’autre angle aigu vaut $\beta = 90^\circ - \alpha$

Comme les triangles $ADE$ et $XYZ$ sont isométriques, les triangles $ABC$
et $XYZ$ vérifient également ces propriétés. On en conclut que deux
triangles rectangles qui possèdent un angle de même amplitude sont
des triangles semblables.

* Théorème de Pythagore

#+TOC: headlines 1 local

** Par les triangles semblables

Examinons le triangle rectangle $ABC$ ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-pythagore-par-triangles-semblables.svg]]

On définit :

$$ a = \abs{AC}
\qquad \qquad \qquad
b = \abs{BC}
\qquad \qquad \qquad
c = \abs{AB} $$

$$ h = \abs{CD}
\qquad \qquad \qquad
u = \abs{AD}
\qquad \qquad \qquad
v = \abs{DB} $$

L’hypothénuse $c$ est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle principal en deux triangles
rectangles : $ADC$ et $DBC$.

Les triangles rectangles $ABC$ et $ADC$ ont un angle $\alpha$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{u}{a} = \frac{a}{c} $$

En isolant $u$, on obtient :

$$ u = \frac{a^2}{c} $$

Les triangles rectangles $ABC$ et $DBC$ ont un angle $\beta$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{v}{b} = \frac{b}{c} $$

En isolant $v$, on obtient :

$$ v = \frac{b^2}{c} $$

L’hypothénuse $c$ vérifie :

$$ c = u + v = \frac{a^2}{c} + \frac{b^2}{c} $$

En multipliant par $c$, on obtient la relation :

$$ c^2 = a^2 + b^2 $$

Le carré de l’hypothénuse d’un triangle rectangle est égal à la
somme des carrés des deux autres côtés.

La longueur $c$ étant un réel positif, on en déduit immédiatement que :

$$ c = \sqrt{a^2 + b^2} $$

** Par le carré environnant

Soit le triangle :

#+attr_html: :width 23%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/longueurs-triangle-rectangle.svg]]

Nous allons montrer une importante relation entre les longueurs $a,b,c$
en utilisant le schéma suivant :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/theoreme-de-pythagore-par-carre.svg]]

L’aire $\mathcal{T}$ de chaque triangle rectangle vaut :

$$ \mathcal{T} = \frac{a b}{2} $$

L’aire $\mathcal{C}$ du grand carré vaut le carré de son côté $a+b$ :

$$ \mathcal{C} = (a+b)^2 = a^2 + 2 \ a \ b + b^2 $$

Cette aire $\mathcal{C}$ est aussi égale à la somme des aires du carré
et des triangles qu’il contient :

$$ \mathcal{C} = c^2 + 4 \ \mathcal{T} = c^2 + 4 \cdot \frac{a \ b}{2} = c^2 + 2 \ a \ b $$

Comme les deux expressions de $\mathcal{C}$ sont égales, on a :

$$ a^2 + 2 \ a \ b + b^2 = c^2 + 2 \ a \ b $$

ce qui donne en simplifiant :

$$ a^2 + b^2 = c^2 $$

* Triangles de Pythagore

Un triangle de Pythagore est un triangle rectangle où les longueurs
des trois côtés sont des nombres entiers.

#+attr_html: :width 27%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-pythagore.svg]]

La figure ci-dessus utilise une astuce algébrique pour obtenir certains
triangles de Pythagore. En effet :

\begin{align*}
A^2 + B^2
&= \left(a^2 - b^2\right)^2 + \left(2 \ a \ b\right)^2 \\
&= a^4 - 2 \ a^2 \ b^2 + b^4 + 4 \ a^2 \ b^2 \\
&= a^4 + 2 \ a^2 \ b^2 + b^4 \\
&= \left(a^2 + b^2\right)^2
\end{align*}

et finalement :

$$ A^2 + B^2 = C^2 $$

Choisir de telles expressions pour $A$, $B$, $C$ nous assure d’avoir
des longueurs qui respectent le théorème de Pythagore. De plus, si
les longueurs $a$, $b$, $c$ sont entières, les longueurs $A$, $B$,
$C$ le seront également. Le tableau suivant nous donne les premiers
triangles de Pythagore obtenus avec cette méthode.

| $a$ | $b$ | $A$ | $B$ | $C$ |
|-----+-----+-----+-----+-----|
|   2 |   1 |   3 |   4 |   5 |
|   3 |   2 |   5 |  12 |  13 |
|   4 |   1 |   8 |  15 |  17 |
|   4 |   3 |   7 |  24 |  25 |
|   5 |   2 |  20 |  21 |  29 |
|   5 |   4 |   9 |  40 |  41 |
|   6 |   1 |  12 |  35 |  37 |
|   6 |   5 |  11 |  60 |  61 |
|   7 |   2 |  28 |  45 |  53 |
|   7 |   4 |  33 |  56 |  65 |
|   7 |   6 |  13 |  84 |  85 |

* Propriétés

#+TOC: headlines 1 local

** Introduction

Examinons le triangle rectangle $ABC$ ci-dessous :

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/proprietes-des-longueurs-du-triangle-rectangle.svg]]

On définit :

$$ a = \abs{AC}
\qquad \qquad \qquad
b = \abs{BC}
\qquad \qquad \qquad
c = \abs{AB} $$

$$ h = \abs{CD}
\qquad \qquad \qquad
u = \abs{AD}
\qquad \qquad \qquad
v = \abs{DB} $$

L’hypothénuse $c$ est scindée en deux parties $u$ et $v$ par la
hauteur $h$ qui lui est perpendiculaire. On a donc :

$$ c = u + v $$

De plus, la hauteur $h$ divise le triangle principal en deux triangles
rectangles : $ADC$ et $DBC$.

** Carré des cathètes

Les triangles rectangles $ABC$ et $ADC$ ont un angle $\alpha$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{a}{c} = \frac{u}{a} $$

En multipliant par $a \ c$, on obtient :

$$ a^2 = u \ c $$

Le carré de la première cathéte $a$ est égale au produit de
l’hypothénuse partielle correspondante $u$ par l’hypothénuse $c$.

Les triangles rectangles $ABC$ et $DBC$ ont un angle $\beta$ de même
amplitude. Ce sont donc des triangles semblables. On a en particulier :

$$ \frac{b}{c} = \frac{v}{b} $$

En multipliant par $b \ c$, on obtient :

$$ b^2 = v \ c $$

Le carré de la seconde cathéte $b$ est égale au produit de
l’hypothénuse partielle correspondante $v$ par l’hypothénuse $c$.

** Carré de la hauteur

Nous avons vu dans le
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle_corollaire][corollaire]]
de la
[[file:aire-dans-le-plan.org::#heading:aire_triangle_rectangle][section
concernant l’aire du triangle rectangle]] que le produit des cathètes
est égal au produit de l’hypothénuse par la hauteur qui lui est
perpendiculaire. Dans le triangle rectangle $ABC$, cela nous donne :

$$ c \ h = a \ b $$

Prenons le carré de chaque membre :

$$ c^2 \ h^2 = a^2 \ b^2 $$

et ramplaçons par les expressions des carrés des cathètes en fonctions
de $u$, $v$ et $c$ :

$$ c^2 \ h^2 = u \ c \ v \ c = u \ v \ c^2 $$

En simplifiant, il vient :

$$ h^2 = u \ v $$

Le carré de la hauteur est égale au produit des hypothénuses partielles
$u$ et $v$.

* Centre du cercle circonscrit

Dans la section traitant
[[file:angles-et-cercles.org::#heading:diametre_comme_cote_d_un_triangle][du
diamètre comme coté d’un triangle inscrit]], nous avons montré
comment construire un triangle rectangle en partant du diamètre d’un
cercle. Le milieu de l’hypothénuse est alors le centre du cercle
circonscrit au triangle. Nous allons à présent partir d’un triangle
rectangle générique $ABC$ et tenter de montrer le même résultat :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-rectangle-centre-du-cercle-circonscrit.svg]]

On trace :

- la hauteur $[C,D]$, perpendiculaire à l’hypothénuse $[A,B]$
- le point $E$, situé au milieu de l’hypothénuse $[A,B]$

On définit :

$$ a = \abs{AC}
\qquad \qquad \qquad
b = \abs{BC} $$

$$ c = \abs{AB}
\qquad \qquad \qquad
d = \abs{DE} $$

$$ h = \abs{CD}
\qquad \qquad \qquad
m = \abs{EC} $$

$$ u = \abs{AD}
\qquad \qquad \qquad
v = \abs{DB} $$

Par construction du point $E$, on a :

$$ \abs{EA} = \abs{EB} = \frac{c}{2} $$

et :

$$ u = \frac{c}{2} - d $$

$$ v = \frac{c}{2} + d $$

Le carré de la hauteur $h$ est égale au produit des hypothénuses
partielles :

$$ h^2 = u \ v $$

En remplaçant $u$ et $v$ par leurs expressions, on obtient :

$$ h^2 = \left( \frac{c}{2} - d \right) \ \left( \frac{c}{2} + d \right) $$

Ou, en utilisant la formule du binôme conjugué :

$$ h^2 = \frac{c^2}{4} - d^2 $$

Par ailleurs, le théorème de Pythagore appliqué au triangle $CDE$
nous donne :

$$ m^2 = h^2 + d^2 $$

En remplaçant le carré de la hauteur par son expression en fonction de
$c$ et $d$, cette relation devient :

$$ m^2 = \frac{c^2}{4} - d^2 + d^2 $$

Simplifions :

$$ m^2 = \frac{c^2}{4} $$

Comme $m$ est une longueur et donc un réel positif, il suffit de prendre
la racine carrée pour obtenir l’expression :

$$ m = \frac{c}{2} $$

On a finalement :

$$ \abs{EA} = \abs{EB} = \abs{EC} = \frac{c}{2} $$

Les trois sommets du triangle $ABC$ sont donc équidistants du point
$E$. Le milieu de l’hypothénuse est donc le centre du cercle circonscrit
d’un triangle rectangle, et le rayon $r$ de ce cercle est égale à
la moitié de la longueur de l’hypothénuse :

$$ r = \frac{c}{2} $$

* Propriétés extrémales de la projection orthogonale

Nous avons déjà étudié les
[[file:perpendicularite.org::#heading:minimum][propriétés extrémales de
la projection orthogonale]] en utilisant des triangles isométriques. Nous
allons à présent tenter d’obtenir le même résultat avec le théorème
de Pythagore.

Soit un point $A$, une droite $d$ et le point $B$, projection orthogonale
de $A$ sur $d$ :

#+attr_html: :width 45%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/distance-entre-un-point-et-une-droite-minimum.svg]]

On choisit un point quelconque $C \in d$. On a :

$$ a = \abs{AB}
\qquad \qquad \qquad
b = \abs{BC}
\qquad \qquad \qquad
c = \abs{CA} $$

Le théorème de Pythagore appliqué au triangle rectangle $ABC$ nous
donne :

$$ a^2 + b^2 = c^2 $$

Comme $b$ est un nombre réel, on a $b^2 \ge 0$ et :

$$ a^2 \le c^2 $$

c’est-à-dire :

$$ \abs{AB}^2 \le \abs{AC}^2 $$

En prenant la racine des deux membres, on obtient :

$$ \abs{AB} \le \abs{AC} $$

L’égalité est atteinte uniquement pour le choix particulier $C =
B$, lorsque $b = 0$. Parmi tous les points appartenant à la droite $d$,
$B$ est l’unique point qui minimise la distance avec $A$ :

$$ B = \arg\min_{C \in d} \abs{AC} $$

On a donc :

$$ \abs{AB} = \min_{C \in d} \abs{AC} $$

Par définition de la distance entre un point et une droite, on a :

$$ \distance(A,d) = \min_{C \in d} \abs{AC} $$

On en conclut que :

$$ \abs{AB} = \distance(A,d) $$
