
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Triangles isométriques
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Conditions d’isométrie de deux triangles
:properties:
:custom_id: heading:condition_d_isometrie_de_deux_triangles
:end:

#+TOC: headlines 1 local

** Principe d’équivalence des constructions

Chacune des [[file:constructions-de-triangles.org][techniques de
construction de triangles]] que nous avons présenté jusqu’ici produit,
soit un unique triangle, soit deux triangles isométriques.

Étant donné une technique de construction $\mathscr{T}$ et ses
données de départ $\mathscr{D}$, les longueurs et les angles des
triangles obtenus sont donc identiques, et ce quel que soit l’endroit
et l’orientation des éléments de départ de la construction.

Si deux triangles $T_1$ et $T_2$ partagent les mêmes caractéristiques
$\mathscr{D}$, on peut les reconstruire à l’identique au moyen de
$\mathscr{T}$. On en déduit que ces deux triangles sont isométriques :

$$ T_1 \cong T_2 $$

Les longueurs et leurs angles de ces triangles sont donc complètement
déterminés par les caractéristiques de $\mathscr{D}$.

** Trois côtés de même longueur

Soit les deux triangles $ABC$ et $DEF$ présentés dans le schéma
ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques-trois-cotes.svg]]

Si les trois côtés sont de mêmes longueurs :

$$ a_1 = a_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

** Côté - angle - côté

Soit les deux triangles $ABC$ et $DEF$ présentés dans le schéma
ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques-cote-angle-cote.svg]]

Si les deux triangles ont un angle correspondant de même amplitude
compris entre deux côtés correspondants de mêmes longueurs :

$$ \alpha_1 = \alpha_2 $$

$$ b_1 = b_2 $$

$$ c_1 = c_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

** Angle - côté - angle

Soit les deux triangles $ABC$ et $DEF$ présentés dans le schéma
ci-dessous :

#+attr_html: :width 60%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangles-isometriques-angle-cote-angle.svg]]

Si les deux triangles ont un côté correspondant de même longueur
compris entre deux angles correspondants de mêmes amplitudes :

$$ a_1 = a_2 $$

$$ \beta_1 = \beta_2 $$

$$ \gamma_1 = \gamma_2 $$

on peut utiliser la même technique pour reconstruire les deux triangles
à l’identique. On en déduit que les deux triangles sont isométriques.

* Triangle isocèle

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-isocele-angles.svg]]

* Triangle équilatéral

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-equilateral-angles.svg]]

