
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Trigonometrie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Triangle rectangle

#+TOC: headlines 1 local

** Définitions

Soit le triangle rectangle :

#+attr_html: :width 400px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigonometrie-triangle-rectangle.svg]]

On définit la fonction trigonométrique du sinus, notée $\sin$, comme
le rapport entre le côté opposé à l’angle avec l’hypothénuse :

$$ \sin(\alpha) = \frac{b}{c} $$

On définit la fonction trigonométrique du cosinus, notée $\cos$, comme
le rapport entre le côté adjacent à l’angle avec l’hypothénuse :

$$ \cos(\alpha) = \frac{a}{c} $$

On définit la fonction trigonométrique de tangente, notée $\tan$, comme
le rapport entre le côté opposé et le côté adjacent :

$$ \tan(\alpha) = \frac{b}{a} $$

On a aussi les rapports inversés :

- cosécante :

$$ \csc(\alpha) = \frac{c}{b} $$

- sécante :

$$ \sec(\alpha) = \frac{c}{a} $$

- cotangente :

$$ \cot(\alpha) = \frac{a}{b} $$

** Notations

On note :

$$ \sin \alpha = \sin(\alpha) $$

$$ \cos \alpha = \cos(\alpha) $$

$$ \tan \alpha = \tan(\alpha) $$

$$ \csc \alpha = \csc(\alpha) $$

$$ \sec \alpha = \sec(\alpha) $$

$$ \cot \alpha = \cot(\alpha) $$

*** Carrés

L’usage veut également que :

$$ \sin^2 \alpha = (\sin \alpha)^2 $$

$$ \cos^2 \alpha = (\cos \alpha)^2 $$

$$ \tan^2 \alpha = (\tan \alpha)^2 $$

et ainsi de suite. J’évite autant que possible cette notation
dans cet ouvrage, car elle n’est pas cohérente avec la notation
générale des fonctions qui veut que :

$$ f^2(x) = (f \circ f)(x) \ne [f(x)]^2 = f(x) \cdot f(x) $$

** Corollaires

En multipliant la définition du sinus par $c$, on obtient :

$$ b = c \ \sin \alpha $$

En multipliant la définition du cosinus par $c$, on obtient :

$$ a = c \ \cos \alpha $$

** Inverses multiplicatifs

On remarque que la cosécante est l’inverse du sinus :

$$ \csc\alpha = \frac{c}{b} = \frac{1}{b/c} = \unsur{\sin\alpha} $$

On remarque que la sécante est l’inverse du cosinus :

$$ \sec\alpha = \frac{c}{a} = \frac{1}{a/c} = \unsur{\cos\alpha} $$

On remarque que la cotangente est l’inverse de la tangente :

$$ \cot\alpha = \frac{a}{b} = \frac{1}{b/a} = \unsur{\tan\alpha} $$

** Angle complémentaire

Comme le triangle est rectangle, on a :

$$ \alpha + \beta = \frac{\pi}{2} $$

ou :

$$ \beta = \frac{\pi}{2} - \alpha $$

Le rapport entre le côté adjacent à $\beta$ et l’hypothénuse nous
donne :

$$ \cos \beta = \frac{b}{c} = \sin \alpha $$

c’est-à-dire :

$$ \cos\left(\frac{\pi}{2} - \alpha\right) = \sin \alpha $$

Le rapport entre le côté opposé à $\beta$ et l’hypothénuse nous
donne :

$$ \sin \beta = \frac{a}{c} = \cos \alpha $$

c’est-à-dire :

$$ \sin\left(\frac{\pi}{2} - \alpha\right) = \cos \alpha $$

Le rapport entre le côté opposé et le côté adjacent à $\beta$
nous donne :

$$ \tan \beta = \frac{a}{b} = \unsur{b/a} = \unsur{\tan \alpha} $$

c’est-à-dire :

$$ \tan\left(\frac{\pi}{2} - \alpha\right) = \unsur{\tan \alpha} $$

* Cercle trigonométrique

#+TOC: headlines 1 local

** Premier quadrant

Le cercle trigonométrique permet de généraliser la définition des
fonctions trigonometriques au-delà de l’intervalle $[0,\pi/2]$.

#+attr_html: :width 800px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/cercle-trigonometrique.svg]]

Ce cercle est un cercle unitaire, c’est-à-dire de rayon $1$, et permet
de générer un triangle rectangle dont l’hypothénuse vaut $1$ pour
chaque angle $\alpha$. La figure ci-dessus en illustre un exemple. Les
deux autres côtés sont alors de longueurs :

$$ a = 1 \cdot \cos \alpha = \cos \alpha $$

$$ b = 1 \cdot \sin \alpha = \sin \alpha $$

Ces longueurs correspondent aussi aux coordonnées du point $P$ qui
valent :

$$ (\cos \alpha, \sin \alpha) $$

dans le système d’axes $(O,x,y)$. Ces coordonnées peuvent varier
entre $-1$ et $1$, tout comme les valeurs des fonctions $\cos$ et $\sin$.

On en déduit les valeurs des fonctions trigonométriques $\cos$ et
$\sin$ pour n’importe quel angle entre $0$ et $2\pi$.

** Deuxième quadrant

Le schéma ci-dessous illustre le cas du deuxième quadrant,
c’est-à-dire de l’ntervalle $[\pi/2,\pi]$.

#+attr_html: :width 600px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigo-quadrant-2.svg]]

On en déduit que :

$$ \cos(\alpha+\pi/2) = - \sin(\alpha) $$

$$ \sin(\alpha+\pi/2) = \cos(\alpha) $$

Pour la tangente, on a :

$$ \tan(\alpha + \pi/2)
= \frac{\sin(\alpha + \pi/2)}{\cos(\alpha + \pi/2)}
= \frac{\cos\alpha}{-\sin\alpha}
= \frac{-1}{\sin\alpha / \cos\alpha}
=  \frac{-1}{\tan\alpha} $$

** Troisième quadrant

Le schéma ci-dessous illustre le cas du troisième quadrant,
c’est-à-dire de l’ntervalle $[\pi,3\pi/2]$.

#+attr_html: :width 600px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigo-quadrant-3.svg]]

On en déduit que :

$$ \cos(\alpha+\pi) = - \cos(\alpha) $$

$$ \sin(\alpha+\pi) = - \sin(\alpha) $$

Pour la tangente, on a :

$$ \tan(\alpha + \pi)
= \frac{\sin(\alpha + \pi)}{\cos(\alpha + \pi)}
= \frac{-\sin\alpha}{-\cos\alpha}
= \frac{\sin\alpha}{\cos\alpha}
=  \tan\alpha $$

** Quatrième quadrant

Le schéma ci-dessous illustre le cas du quatrième quadrant,
c’est-à-dire de l’ntervalle $[3\pi/2,2\pi]$.

#+attr_html: :width 600px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigo-quadrant-4.svg]]

On en déduit que :

$$ \cos(\alpha+3\pi/2) = \sin(\alpha) $$

$$ \sin(\alpha+3\pi/2) = - \cos(\alpha) $$

Pour la tangente, on a :

$$ \tan(\alpha + 3\pi/2)
= \frac{\sin(\alpha + 3\pi/2)}{\cos(\alpha + 3\pi/2)}
= \frac{-\cos\alpha}{\sin\alpha}
= \frac{-1}{\sin\alpha / \cos\alpha}
= \frac{-1}{\tan\alpha} $$

** Angle supplémentaire

#+attr_html: :width 700px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigo-quadrant-supplementaire.svg]]

Le schéma ci-dessus nous montre que :

$$ \cos(\pi - \alpha) = - \cos \alpha $$

$$ \sin(\pi - \alpha) = \sin \alpha $$

Pour la tangente, on a :

$$ \tan(\pi - \alpha)
= \frac{\sin(\pi - \alpha)}{\cos(\pi - \alpha)}
= \frac{\sin\alpha}{-\cos\alpha}
= - \tan\alpha $$

** Angles négatifs

Le schéma ci-dessous illustre le cas d’angles négatifs.

#+attr_html: :width 600px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigo-quadrant-miroir.svg]]

On a clairement :

$$ \cos(-\alpha) = \cos(\alpha) $$

$$ \sin(-\alpha) = - \sin(\alpha) $$

Pour la tangente, on a :

$$ \tan(-\alpha)
= \frac{\sin(-\alpha)}{\cos(-\alpha)}
= \frac{-\sin\alpha}{\cos\alpha}
= - \tan\alpha $$

** Généralisation à n’importe quel angle réel

On considère qu’ajouter un nombre entier de tours complets (multiple
entier de $2\pi$) ne change rien aux fonctions trigonométriques. On a
donc :

$$ \cos(\alpha+2 \ \pi \ k) = \cos \alpha $$

$$ \sin(\alpha+2 \ \pi \ k) = \sin \alpha $$

pour tout $k \in \setZ$. Ce constat permet de couvrir l’ensemble des
angles à amplitude réelle.

* Relations fondamentales

#+TOC: headlines 1 local

** Préambule

Soit le triangle rectangle :

#+attr_html: :width 400px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigonometrie-triangle-rectangle.svg]]

** Sinus et cosinus

Le théorème de Pythagore dans notre triangle rectangle nous donne :

$$ a^2 + b^2 = c^2 $$

Mais comme :

$$ a = c \ \cos \alpha $$

$$ b = c \ \sin \alpha $$

la première relation devient :

$$ c^2 \ (\cos \alpha)^2 + c^2 \ (\sin \alpha)^2 = c^2 $$

On peut mettre $c^2$ en évidence :

$$ c^2 \ \left[(\cos \alpha)^2 + (\sin \alpha)^2\right] = c^2 $$

puis diviser par $c^2$ les deux membres, ce qui nous donne la relation
fondamentale entre sinus et cosinus :

$$ (\cos \alpha)^2 + (\sin \alpha)^2 = 1 $$

** Tangente

On a :

$$ \tan \alpha
= \frac{b}{a}
= \frac{b}{c} \cdot \frac{c}{a}
= \frac{b/c}{a/c} $$

Par définition des sinus et cosinus, on a donc :

$$ \tan \alpha = \frac{\sin \alpha}{\cos \alpha} $$

** Combinaison

Soit un angle $\alpha$ et :

$$ s = \sin\alpha $$

$$ c = \cos\alpha $$

$$ t = \tan\alpha $$

Les relations fondamentales s’écrivent :

$$ s^2 + c^2 = 1 $$

et :

$$ t = \frac{s}{c} $$

ou encore :

$$ t^2 = \frac{s^2}{c^2} $$

Divisons :

$$ s^2 + c^2 = 1 $$

par $c^2$. Il vient :

$$ \frac{s^2}{c^2} + 1 = \unsur{c^2} $$

c’est-à-dire :

$$ t^2 + 1 = \unsur{c^2} $$

Autrement dit :

$$ (\tan\alpha)^2 + 1 = \unsur{(\cos\alpha)^2} $$


* Sinus et cosinus en fonction de la tangente

#+TOC: headlines 1 local

** Préambule

Soit un angle $\alpha$. Posons :

$$ s = \sin \alpha $$

$$ c = \cos \alpha $$

$$ t = \tan \alpha $$

Nous allons utiliser les relations fondamentales :

$$ t = s / c $$

$$ s^2 + c^2 = 1 $$

pour obtenir une expression du sinus et du cosinus comme fonction de
la tangente uniquement. En prenant le carré de la première équation
ci-cessus, on a :

$$ t^2 = s^2 / c^2 $$

Remarquons aussi que la seconde équation peur se réécrire, au choix,
comme :

$$ s^2 = 1 - c^2 $$

$$ c^2 = 1 - s^2 $$

** Sinus en fonction de la tangente

On a :

$$ t^2 = \frac{s^2}{c^2} = \frac{s^2}{1 - s^2} $$

Multiplions par $1 - s^2$ :

$$ (1 - s^2) \ t^2 = s^2 $$

Distribuons :

$$ t^2 - s^2 \ t^2 = s^2 $$

et passons tous les termes en $s^2$ du même côté :

$$ t^2 = s^2 + s^2 \ t^2 $$

Mettons $s^2$ en évidence :

$$ t^2 = (1 + t^2) \ s^2 $$

En isolant $s^2$, on obtient :

$$ s^2 = \frac{t^2}{1 + t^2} $$

c’est-à-dire :

$$ (\sin \alpha)^2 = \frac{(\tan \alpha)^2}{1 + (\tan \alpha)^2} $$

On a donc soit :

$$ \sin \alpha = \sqrt{\frac{(\tan \alpha)^2}{1 + (\tan \alpha)^2}} $$

ou :

$$ \sin \alpha = - \sqrt{\frac{(\tan \alpha)^2}{1 + (\tan \alpha)^2}} $$

ce que l’on note sous la forme :

$$ \sin \alpha = \pm \sqrt{\frac{(\tan \alpha)^2}{1 + (\tan \alpha)^2}} $$

** Cosinus en fonction de la tangente

On a :

$$ t^2 = \frac{s^2}{c^2} = \frac{1 - c^2}{c^2} $$

Multiplions par $c^2$ :

$$ c^2 \ t^2 = 1 - c^2 $$

et passons tous les termes en $c^2$ du même côté :

$$ c^2 + c^2 \ t^2 = 1 $$

Mettons $c^2$ en évidence :

$$ (1 + t^2) \ c^2 = 1 $$

En isolant $c^2$, on obtient :

$$ c^2 = \frac{1}{1 + t^2} $$

c’est-à-dire :

$$ (\cos \alpha)^2 = \frac{1}{1 + (\tan \alpha)^2} $$

On a donc soit :

$$ \cos \alpha = \unsur{\sqrt{1 + (\tan \alpha)^2}} $$

ou :

$$ \cos \alpha = \frac{-1}{\sqrt{1 + (\tan \alpha)^2}} $$

ce que l’on note sous la forme :

$$ \cos \alpha = \frac{\pm 1}{\sqrt{1 + (\tan \alpha)^2}} $$

* Triangles quelconques

#+TOC: headlines 1 local

** Loi des sinus

Soit un triangle quelconque. On peut toujours le décomposer en deux
triangles rectangles comme suit :

#+attr_html: :width 500px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/loi-des-sinus.svg]]

Dans le triangle rectangle de gauche, nous avons :

$$ h = a \ \sin \gamma $$

Dans le triangle rectangle de droite, nous avons :

$$ h = c \ \sin \alpha $$

On en déduit que :

$$ a \ \sin \gamma = c \ \sin \alpha $$

c’est-à-dire :

$$ \frac{a}{\sin \alpha} = \frac{c}{\sin \gamma} $$

On peut aussi tracer la hauteur perpendiculaire au côté $c$ et suivre un
raisonnement similaire, qui nous donne :

$$ a \ \sin \beta = b \ \sin \alpha $$

c’est-à-dire :

$$ \frac{a}{\sin \alpha} = \frac{b}{\sin \beta} $$

On a donc finalement la loi des sinus qui englobe les trois côtés :

$$ \frac{a}{\sin \alpha} = \frac{b}{\sin \beta} = \frac{c}{\sin \gamma} $$

** Loi des cosinus

Soit un triangle quelconque. On peut toujours le décomposer en deux
triangles rectangles comme suit :

#+attr_html: :width 500px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/loi-des-cosinus.svg]]

Dans le triangle rectangle de gauche, nous avons :

\begin{Eqts}
e = a \cos \gamma \\
h = a \sin \gamma
\end{Eqts}

Appliquons à présent le théorème de Pythagore au triangle rectangle
de droite :

$$ c^2 = h^2 + (b - e)^2 $$

En tenant compte des relations trigonométriques, cette équation
devient :

\begin{align*}
c^2
&= a^2 \ (\sin \gamma)^2 + (b - a \ \cos \gamma)^2 \\
&= a^2 \ (\sin \gamma)^2 + b^2 - 2 \ a \ b \ \cos \gamma + a^2 \ (\cos \gamma)^2 \\
&= a^2 \left[(\sin \gamma)^2 + (\cos \gamma)^2 \right] + b^2 - 2 \ \ a \ b \cos \gamma \\
\end{align*}

Mais comme la somme entre crochets vaut toujours 1, on a finalement :

$$ c^2 = a^2 + b^2 - 2 \ a \ b \ \cos \gamma $$

Un raisonnement similaire nous donne le même résultat lorsque l’angle
$\gamma$ est obtus.

On peut voir ce résultat comme une généralisation du théorème de
Pythagore à un triangle quelconque.

#+attr_html: :width 500px
#+#+attr_latex: :width 0.7\linewidth
[[file:tikz/triangle-et-angles.svg]]

Un raisonnement similaire nous donne un résultat analogue pour les
autres côtés :

$$ a^2 = b^2 + c^2 - 2 \ b \ c \ \cos \alpha $$

$$ b^2 = a^2 + c^2 - 2 \ a \ c \ \cos \beta $$

* Fonctions trigonométriques inverses

#+TOC: headlines 1 local

** Arc sinus

Les fonctions trigonométriques ne sont pas directement inversibles. Soit
un certain $y \in [-1,1]$ et la valeur $x \in \setR$ solution du
problème :

$$\sin(x) = y$$

Comme la fonction $\sin$ est périodique de période $2 \ \pi$, on a :

$$\sin(x + 2 \ k \ \pi) = \sin(x) = y$$

pour tout $k \in \setN$. L'ensemble des solutions inclut donc
l’ensemble :

$$ S = \{ x + 2 \ \pi \ k : k \in \setN \} $$

qui admet une infinité d’éléments. On ne peut donc pas déduire
une seule valeur de $x$ à partir d’une valeur de $y$. Par contre,
l’ensemble des solutions ne contient qu’une seule valeur de $x$
dans l’invervalle $[-\pi/2,\pi/2]$, et on peut définir la fonction
arc sinus, notée $\arcsin$, par :

$$ \arcsin(y) = x
\qquad \Leftrightarrow \qquad
\left\lbrace \begin{array}{l}
y = \sin(x) \\
x \in [-\pi/2,\pi/2]
\end{array}
\right. $$

On note abusivement :

$$ \sin^{-1} = \arcsin $$

On utilise aussi la notation sans parenthèse, comme pour les autres
fonctions trigonometriques :

$$ \arcsin y = \arcsin(y) $$

On a :

$$ \sin\arcsin y = \sin x = y $$

pour tout $y \in [-1,1]$.

** Arc cosinus

Soit un certain $y \in [-1,1]$ et la valeur $x \in \setR$ solution
du problème :

$$\cos(x) = y$$

Comme la fonction $\cos$ est périodique, on ne peut pas déduire
une seule valeur de $x$ à partir d’une valeur de $y$. Par contre,
l’ensemble des solutions ne contient qu’une seule valeur de $x$ dans
l’invervalle $[0,\pi]$, et on peut définir la fonction arc cosinus,
notée $\arccos$, par :

$$ \arccos(y) = x
\qquad \Leftrightarrow \qquad
\left\lbrace \begin{array}{l}
y = \cos(x) \\
x \in [0,\pi]
\end{array}
\right. $$

On note abusivement :

$$ \cos^{-1} = \arccos $$

On utilise aussi la notation sans parenthèse, comme pour les autres
fonctions trigonometriques :

$$ \arccos y = \arccos(y) $$

On a :

$$ \cos\arccos y = \cos x = y $$

pour tout $y \in [-1,1]$.

** Arc tangente

Soit un certain $y \in \setR$ et la valeur $x \in \setR$ solution du
problème :

$$\tan(x) = y$$

Comme la fonction $\tan$ est périodique, on ne peut pas déduire
une seule valeur de $x$ à partir d’une valeur de $y$. Par contre,
l’ensemble $S$ ne contient qu’une seule valeur de $x$ dans
l’invervalle $\intervalleouvert{-\pi/2}{\pi/2}$, et on peut définir
la fonction arc tangente, notée $\arctan$, par :

$$ \arctan(y) = x
\qquad \Leftrightarrow \qquad
\left\lbrace \begin{array}{l}
y = \tan(x) \\
x \in \intervalleouvert{-\pi/2}{\pi/2}
\end{array}
\right. $$

On note abusivement :

$$ \tan^{-1} = \arctan $$

On utilise aussi la notation sans parenthèse, comme pour les autres
fonctions trigonometriques :

$$ \arctan y = \arctan(y) $$

On a :

$$ \tan\arctan y = \tan x = y $$

pour tout $y \in \setR$.
