
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Trigonometrie : sommes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Somme de deux angles

#+TOC: headlines 1 local

** Par une superposition de triangles

Soit les triangles rectangles $ABC$ et $ACD$ empilés l’un sur
l’autre :

#+attr_html: :width 42%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigonometrie-somme-angles.svg]]

Les droites $(AB)$ et $(EF)$ sont clairement parallèles.

Nous avons tenu compte des angles alternes-internes dans la notation.

Comme $\alpha$ et $\gamma$ sont les deux angles aigus d’un triangle
rectangle, ils sont complémentaires :

$$ \gamma = 90^\circ - \alpha $$

Comme $\gamma$, $\delta$ et $90^\circ$ forment ensemble un angle plat,
on a :

$$ \gamma + \delta + 90^\circ = 180^\circ $$

En soustrayant la première équation de la seconde, on obtient :

$$ \gamma + \delta + 90^\circ - \gamma = 180^\circ - 90^\circ + \alpha $$

En simplifiant, on obtient :

$$ \delta = \alpha $$

*** Sinus de la somme

Le diagramme nous montre que :

$$ \sin(\alpha+\beta) = \cos\beta \ \sin\alpha + \cos\delta \ \sin\beta $$

mais comme $\delta = \alpha$, cette relation devient :

$$ \sin(\alpha+\beta) = \cos\beta \ \sin\alpha + \cos\alpha \ \sin\beta $$

ou encore :

$$ \sin(\alpha+\beta) = \sin\alpha \ \cos\beta + \sin\beta \ \cos\alpha $$

ce qui nous donne la formule pour le sinus d’une somme d’angles.

*** Cosinus de la somme

Le diagramme nous montre que :

$$ \cos(\alpha+\beta) + \sin\beta \ \sin\delta = \cos\beta \ \cos\alpha $$

mais comme $\delta = \alpha$, cette relation devient :

$$ \cos(\alpha+\beta) + \sin\beta \ \sin\alpha = \cos\beta \ \cos\alpha $$

En isolant $\cos(\alpha+\beta)$ :

$$ \cos(\alpha+\beta) = \cos\beta \ \cos\alpha - \sin\beta \ \sin\alpha $$

ou encore :

$$ \cos(\alpha+\beta) = \cos\alpha \ \cos\beta - \sin\alpha \ \sin\beta $$

ce qui nous donne la formule pour le cosinus d’une somme d’angles.

** Par la loi des sinus

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigonometrie-somme-angles-par-loi-sinus.svg]]

On définit :

$$ a = \abs{BC}
\qquad \qquad \qquad
b = \abs{CA}
\qquad \qquad \qquad
c = \abs{AB} $$

$$ u = \abs{AD}
\qquad \qquad \qquad
v = \abs{DB}
\qquad \qquad \qquad \qquad \qquad $$

- La loi des sinus appliquée aux côtés $a$ et $c$ nous donne :

$$ \frac{a}{\sin\gamma} = \frac{c}{\sin(\alpha + \beta)} $$

- Les angles $\alpha$ et $\gamma$ sont des angles aigus de triangle
  rectangle, et sont donc complémentaires :

$$ \gamma = 90^\circ - \alpha $$

On en déduit que :

$$ \sin\gamma = \cos\alpha $$

La loi des sinus devient :

$$ \frac{a}{\cos\alpha} = \frac{c}{\sin(\alpha + \beta)} $$

- La définition du cosinus nous donne :

$$ \cos\beta = \frac{h}{a} $$

Isolons $a$ :

$$ a = \frac{h}{\cos\beta} $$

La loi des sinus devient :

$$ \frac{h}{\cos\alpha \ \cos\beta} = \frac{c}{\sin(\alpha + \beta)} $$

- La définition de la tangente nous donne les relations :

$$ \tan\alpha = \frac{u}{h}
\qquad \qquad \qquad
\tan\beta = \frac{v}{h} $$

Isolons $u$ et $v$ :

$$ u = h \ \tan\alpha
\qquad \qquad \qquad
v = h \ \tan\beta $$

Comme les points $A$, $D$ et $B$ sont alignés, on a :

$$ c = u + v $$

Remplaçons $u$ et $v$ par leurs expressions :

$$ c = h \ \tan\alpha + h \ \tan\beta $$

Mettons $h$ en évidence :

$$ c = h \ (\tan\alpha + \tan\beta) $$

La loi des sinus devient :

$$ \frac{h}{\cos\alpha \ \cos\beta} = \frac{h \ (\tan\alpha + \tan\beta)}{\sin(\alpha + \beta)} $$

- Divisons les deux membres par $h$ :

$$ \frac{1}{\cos\alpha \ \cos\beta} = \frac{\tan\alpha + \tan\beta}{\sin(\alpha + \beta)} $$

Isolons le sinus de la somme :

$$ \sin(\alpha + \beta) = (\tan\alpha + \tan\beta) \ \cos\alpha \ \cos\beta $$

Distribuons :

$$ \sin(\alpha + \beta) = \tan\alpha \ \cos\alpha \ \cos\beta + \tan\beta \ \cos\alpha \ \cos\beta $$

Utilisons la relation fondamentale de la tangente :

$$ \sin(\alpha + \beta) = \frac{\sin\alpha}{\cos\alpha} \ \cos\alpha \ \cos\beta + \frac{\sin\beta}{\cos\beta} \ \cos\alpha \ \cos\beta $$

Il ne nous reste qu’à simplifier pour obtenir la formule :

$$ \sin(\alpha + \beta) = \sin\alpha \ \cos\beta + \sin\beta \ \cos\alpha $$

** Par la loi des cosinus

#+attr_html: :width 40%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/trigonometrie-somme-angles-par-loi-cosinus.svg]]

On définit :

$$ a = \abs{BC}
\qquad \qquad \qquad
b = \abs{CA}
\qquad \qquad \qquad
c = \abs{AB} $$

$$ u = \abs{AD}
\qquad \qquad \qquad
v = \abs{DB}
\qquad \qquad \qquad \qquad \qquad $$

- La définition de la tangente nous donne les relations :

$$ \tan\alpha = \frac{u}{h}
\qquad \qquad \qquad
\tan\beta = \frac{v}{h} $$

Isolons $u$ et $v$ :

$$ u = h \ \tan\alpha
\qquad \qquad \qquad
v = h \ \tan\beta $$

Comme les points $A$, $D$ et $B$ sont alignés, on a :

$$ c = u + v $$

Remplaçons $u$ et $v$ par leurs expressions :

$$ c = h \ \tan\alpha + h \ \tan\beta $$

Élévons au carré :

$$ c^2 = (h \ \tan\alpha + h \ \tan\beta)^2 $$

Appliquons la formule du carré parfait :

$$ c^2 = h^2 \ (\tan\alpha)^2 + 2 \ h^2 \ \tan\alpha \ \tan\beta + h^2 \ (\tan\beta)^2 $$

- D’un autre côté, la loi des cosinus appliquée au côté $c$ nous donne :

$$ c^2 = a^2 + b^2 - 2 \ a \ b \ \cos(\alpha + \beta) $$

- La définition du cosinus nous donne :

$$ \cos\beta = \frac{h}{a}
\qquad \qquad \qquad
\cos\alpha = \frac{h}{b} $$

Isolons $a$ et $b$ :

$$ a = \frac{h}{\cos\beta}
\qquad \qquad \qquad
b = \frac{h}{\cos\alpha} $$

La loi des cosinus devient :

$$ c^2 =
\frac{h^2}{(\cos\beta)^2} +
\frac{h^2}{(\cos\alpha)^2} -
\frac{2 \ h^2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} $$

- Égalisons les deux expressions de $c^2$ :

$$ h^2 \ (\tan\alpha)^2 + 2 \ h^2 \ \tan\alpha \ \tan\beta + h^2 \ (\tan\beta)^2 =
\frac{h^2}{(\cos\beta)^2} +
\frac{h^2}{(\cos\alpha)^2} -
\frac{2 \ h^2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} $$

Divisons le tout par $h^2$ :

$$ (\tan\alpha)^2 + 2 \ \tan\alpha \ \tan\beta + (\tan\beta)^2 =
\frac{1}{(\cos\beta)^2} +
\frac{1}{(\cos\alpha)^2} -
\frac{2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} $$

- Utilisons la relation fondamentale de la tangente :

$$ \frac{(\sin\alpha)^2}{(\cos\alpha)^2} +
\frac{2 \ \sin\alpha \ \sin\beta}{\cos\alpha \ \cos\beta} +
\frac{(\sin\beta)^2}{(\cos\beta)^2} =
\frac{1}{(\cos\beta)^2} +
\frac{1}{(\cos\alpha)^2} -
\frac{2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} $$

Isolons le terme du cosinus de la comme :

$$ \frac{2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} =
\frac{1}{(\cos\beta)^2} +
\frac{1}{(\cos\alpha)^2} -
\frac{(\sin\alpha)^2}{(\cos\alpha)^2} -
\frac{(\sin\beta)^2}{(\cos\beta)^2} -
\frac{2 \ \sin\alpha \ \sin\beta}{\cos\alpha \ \cos\beta} $$

Regroupons les quatre premiers termes du membre de droite :

$$ \frac{2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} =
\frac{1 - (\sin\beta)^2}{(\cos\beta)^2} +
\frac{1 - (\sin\alpha)^2}{(\cos\alpha)^2} -
\frac{2 \ \sin\alpha \ \sin\beta}{\cos\alpha \ \cos\beta} $$

- Utilisons la relation fondamentale entre sinus et cosinus :

$$ (\sin\alpha)^2 + (\cos\alpha)^2 = 1
\qquad \Longleftrightarrow \qquad
(\cos\alpha)^2 = 1 - (\sin\alpha)^2 $$

$$ (\sin\beta)^2 + (\cos\beta)^2 = 1
\qquad \Longleftrightarrow \qquad
(\cos\beta)^2 = 1 - (\sin\beta)^2 $$

La relation entre les expressions de $c^2$ devient :

$$ \frac{2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} =
\frac{(\cos\beta)^2}{(\cos\beta)^2} +
\frac{(\cos\alpha)^2}{(\cos\alpha)^2} -
\frac{2 \ \sin\alpha \ \sin\beta}{\cos\alpha \ \cos\beta} $$

qui se simplifie en :

$$ \frac{2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} =
1 + 1 - \frac{2 \ \sin\alpha \ \sin\beta}{\cos\alpha \ \cos\beta} $$

ou :

$$ \frac{2 \ \cos(\alpha + \beta)}{\cos\alpha \ \cos\beta} =
2 - \frac{2 \ \sin\alpha \ \sin\beta}{\cos\alpha \ \cos\beta} $$

Multiplions le tout par le produit des cosinus des dénominateurs :

$$ 2 \ \cos(\alpha + \beta) = 2 \ \cos\alpha \ \cos\beta - 2 \ \sin\alpha \ \sin\beta $$

En divisant le tout par deux, on obtient la formule :

$$ \cos(\alpha + \beta) = \cos\alpha \ \cos\beta - \sin\alpha \ \sin\beta $$

** Tangente de la somme

On a :

$$ \tan(\alpha + \beta) = \frac{\sin(\alpha + \beta)}{\cos(\alpha + \beta)} $$

En utilisant les formules de sommes pour le sinus et le cosinus, cette
relation devient :

$$ \tan(\alpha + \beta)
= \frac{\sin\alpha \ \cos\beta + \sin\beta \ \cos\alpha}{\cos\alpha \ \cos\beta - \sin\alpha \ \sin\beta} $$

En divisant numérateur et dénominateur de la fraction par $\cos\alpha \
\cos\beta$, il vient :

$$ \tan(\alpha + \beta)
= \frac{\sin\alpha / \cos\alpha + \sin\beta / \cos\beta}{1 - (\sin\alpha / \cos\alpha) (\sin\beta / \cos\beta)} $$

En se rappelant la relation fondamentale liant tangente, sinus et
cosinus on obtient finalement :

$$ \tan(\alpha + \beta)
= \frac{\tan\alpha + \tan\beta}{1 - \tan\alpha \ \tan\beta} $$

* Différence de deux angles

#+TOC: headlines 1 local

** Par angle négatif

#+TOC: headlines 1 local

*** Cosinus de la différence

On part de la constatation que :

$$ \cos(\alpha - \beta) = \cos\big( \alpha + (-\beta) \big) $$

La formule de la somme nous donne :

$$ \cos\big( \alpha + (-\beta) \big) = \cos\alpha \ \cos(-\beta) - \sin\alpha \ \sin(-\beta) $$

Mais comme :

$$ \cos(-\beta) = \cos(\beta) $$

$$ \sin(-\beta) = - \sin(\beta) $$

le cosinus de la différence peut se réécrire :

$$ \cos(\alpha - \beta) = \cos\alpha \ \cos\beta + \sin\alpha \ \sin\beta $$

*** Sinus de la différence

On part de la constatation que :

$$ \sin(\alpha - \beta) = \sin\big( \alpha + (-\beta) \big) $$

La formule de la somme nous donne :

$$ \sin\big( \alpha + (-\beta) \big) = \sin\alpha \ \cos(-\beta) + \sin(-\beta) \ \cos\alpha $$

Mais comme :

$$ \cos(-\beta) = \cos(\beta) $$

$$ \sin(-\beta) = - \sin(\beta) $$

le sinus de la différence peut se réécrire :

$$ \sin(\alpha - \beta) = \sin\alpha \ \cos\beta - \sin\beta \ \cos\alpha $$

*** Tangente de la différence

On part de la constatation que :

$$ \tan(\alpha - \beta) = \tan\big(\alpha + (-\beta)\big) $$

La formule de la somme nous donne :

$$ \tan\big(\alpha + (-\beta)\big) = \frac{\tan\alpha + \tan(-\beta)}{1 - \tan\alpha \ \tan(-\beta)} $$

Mais comme :

$$ \tan(-\beta) = - \tan\beta $$

la tangente de la différence peut se réécrire :

$$ \tan(\alpha - \beta) = \frac{\tan\alpha - \tan\beta}{1 + \tan\alpha \ \tan\beta} $$

** Par point de vue dual

#+TOC: headlines 1 local

*** Introduction

Choisissons deux angles $\alpha$ et $\beta$ et posons :

$$ \gamma = \alpha - \beta $$

On a alors :

$$ \alpha = \gamma + \beta $$

*** Sinus de la différence

Le formules de sommes nous donnent :

$$ \left\{ \begin{array}{l}
\sin\alpha = \sin(\gamma+\beta) = \sin\gamma \ \cos\beta + \sin\beta \ \cos\gamma \\
\cos\alpha = \cos(\gamma+\beta) = \cos\gamma \ \cos\beta - \sin\gamma \ \sin\beta
\end{array} \right. $$

En multipliant la première équation par $\cos\beta$ et la seconde
par $\sin\beta$, on obtient :

$$ \left\{ \begin{array}{l}
\sin\alpha \ \cos\beta = \sin\gamma \ (\cos\beta)^2 + \sin\beta \ \cos\beta \ \cos\gamma \\
\cos\alpha \ \sin\beta = \cos\gamma \ \sin\beta \ \cos\beta - \sin\gamma \ (\sin\beta)^2
\end{array} \right. $$

En soustrayant la seconde équation de la première, des termes dans le
membre de droite se simplifient et il reste :

$$ \sin\alpha \ \cos\beta - \cos\alpha \ \sin\beta
= \sin\gamma \left[ (\cos\beta)^2 + (\sin\gamma)^2 \right] $$

Le terme entre crochet vaut $1$ et :

$$ \sin\alpha \ \cos\beta - \cos\alpha \ \sin\beta = \sin\gamma $$

Mais comme $\sin\gamma = \sin(\alpha - \beta)$, cela nous donne la
formule du sinus de la différence :

$$ \sin(\alpha - \beta) = \sin\alpha \ \cos\beta - \cos\alpha \ \sin\beta $$

*** Cosinus de la différence

Les formules de sommes nous donnent :

$$ \left\{ \begin{array}{l}
\sin\alpha = \sin(\gamma+\beta) = \sin\gamma \ \cos\beta + \sin\beta \ \cos\gamma \\
\cos\alpha = \cos(\gamma+\beta) = \cos\gamma \ \cos\beta - \sin\gamma \ \sin\beta
\end{array} \right. $$

En multipliant la première équation par $\sin\beta$ et la seconde
par $\cos\beta$, on obtient :

$$ \left\{ \begin{array}{l}
\sin\alpha \ \sin\beta = \sin\gamma \ \sin\beta \ \cos\beta + (\sin\beta)^2 \ \cos\gamma \\
\cos\alpha \ \cos\beta = \cos\gamma \ (\cos\beta)^2 - \sin\gamma \ \sin\beta \ \cos\beta
\end{array} \right. $$

En additionant ces deux équations, des termes dans le membre de droite
se simplifient et il reste :

$$ \sin\alpha \ \sin\beta + \cos\alpha \ \cos\beta
= \cos\gamma \left[ (\cos\beta)^2 + (\sin\gamma)^2 \right] $$

Le terme entre crochet vaut $1$ et :

$$ \sin\alpha \ \sin\beta + \cos\alpha \ \cos\beta = \cos\gamma $$

Mais comme $\cos\gamma = \cos(\alpha - \beta)$, cela nous donne la
formule du sinus de la différence :

$$ \cos(\alpha - \beta) = \cos\alpha \ \cos\beta + \sin\alpha \ \sin\beta $$

* Angle double

#+TOC: headlines 1 local

** Cosinus de l’angle double

On a :

$$ \cos(2 \ \alpha)
= \cos(\alpha+\alpha)
= \cos\alpha \ \cos\alpha - \sin\alpha \ \sin\alpha $$

et donc :

$$ \cos(2 \ \alpha) = (\cos\alpha)^2 - (\sin\alpha)^2 $$

** Sinus de l’angle double

On a :

$$ \sin(2 \ \alpha)
= \sin(\alpha + \alpha)
= \sin\alpha \ \cos\alpha + \sin\alpha \ \cos\alpha $$

et donc :

$$ \sin(2 \ \alpha) = 2 \ \sin\alpha \ \cos\alpha $$

** Tangente de l’angle double

On a :

$$ \tan(\alpha + \alpha)
= \frac{\tan\alpha + \tan\alpha}{1 - \tan\alpha \ \tan\alpha} $$

et donc :

$$ \tan(2 \ \alpha)
= \frac{2 \ \tan\alpha}{1 - (\tan\alpha)^2} $$

* Angle moitié

#+TOC: headlines 1 local

** Carré du cosinus

Soit un angle $\alpha$. La formule du cosinus de l’angle double nous
donne :

$$ \cos(2 \ \alpha) = (\cos\alpha)^2 - (\sin\alpha)^2 $$

En se rappelant la relation fondamentale :

$$ (\cos \alpha)^2 + (\sin \alpha)^2 = 1 $$

on peut remplacer le carré du sinus :

$$ (\sin \alpha)^2 = 1 - (\cos \alpha)^2 $$

dans l’expression du cosinus de l’angle double, ce qui nous donne :

$$ \cos(2 \ \alpha) =(\cos\alpha)^2 - [1 - (\cos\alpha)^2] $$

ou encore :

$$ \cos(2 \ \alpha) = 2 \ (\cos\alpha)^2 - 1 $$

En isolant le carré du cosinus de l’angle $\alpha$, on obtient :

$$ (\cos\alpha)^2 = \frac{1 + \cos(2 \ \alpha)}{2} $$

Pour mettre en évidence l’angle moitié, il suffit de poser :

$$ \theta = 2 \ \alpha $$

On a alors :

$$ \alpha = \theta/2 $$

et :

$$ \big[ \cos(\theta/2) \big]^2 = \frac{1 + \cos\theta}{2} $$

** Carré du sinus

Soit un angle $\alpha$. La formule du cosinus de l’angle double nous
donne :

$$ \cos(2 \ \alpha) = (\cos\alpha)^2 - (\sin\alpha)^2 $$

Si on  remplace le carré du cosinus :

$$ (\cos \alpha)^2 = 1 - (\sin \alpha)^2 $$

dans l’expression du cosinus de l’angle double, on obtient :

$$ \cos(2 \ \alpha) = 1 - 2 \ (\sin\alpha)^2 $$

ou, en isolant le carré du sinus :

$$ (\sin\alpha)^2 = \frac{1 - \cos(2 \ \alpha)}{2} $$

Pour mettre en évidence l’angle moitié, il suffit de poser :

$$ \theta = 2 \ \alpha $$

On a alors :

$$ \alpha = \theta/2 $$

et :

$$ \big[ \sin(\theta/2) \big]^2 = \frac{1 - \cos\theta}{2} $$

** Carré de la tangente

On a aussi :

$$ (\tan\alpha)^2 = \frac{(\sin\alpha)^2}{(\cos\alpha)^2} = \frac{(1 - \cos(2 \ \alpha))/2}{(1 + \cos(2 \ \alpha))/2} $$

et finalement :

$$ (\tan\alpha)^2 = \frac{1 - \cos(2 \ \alpha)}{1 + \cos(2 \ \alpha)} $$

Pour mettre en évidence l’angle moitié, il suffit de poser :

$$ \theta = 2 \ \alpha $$

On a alors :

$$ \alpha = \theta/2 $$

et :

$$ \big[ \tan(\theta/2) \big]^2 = \frac{1 - \cos\theta}{1 + \cos\theta} $$

** Tangente

#+TOC: headlines 1 local

*** Première forme

On a :

$$ \tan(\alpha/2) = \frac{\sin(\alpha/2)}{\cos(\alpha/2)} $$

Multiplions le numérateur et le dénominateur de la fraction par
$2 \ \cos(\alpha/2)$ :

$$ \tan(\alpha/2) = \frac{2 \ \sin(\alpha/2) \ \cos(\alpha/2)}{2 \ [\cos(\alpha/2)]^2} $$

Comme $\alpha$ est l’angle double de $\alpha/2$, on a :

$$ \sin\alpha = 2 \ \sin(\alpha/2) \ \cos(\alpha/2) $$

et :

$$ \cos\alpha = 2 \ [\cos(\alpha/2)]^2 - 1 $$

Cette dernière relation peut se réécrire :

$$ \cos\alpha + 1 = 2 \ [\cos(\alpha/2)]^2 $$

Notre expression de la tangente devient donc :

$$ \tan(\alpha/2) = \frac{\sin\alpha}{1 + \cos\alpha} $$

*** Deuxième forme

Reprenons l’expression de la tangente de l’angle moitié sous sa première
forme :

$$ \tan(\alpha/2) = \frac{\sin\alpha}{1 + \cos\alpha} $$

Multiplions le numérateur et le dénominateur de la fraction par $1 -
\cos\alpha$ :

$$ \tan(\alpha/2) = \frac{\sin\alpha \ (1 - \cos\alpha)}{(1 + \cos\alpha) (1 - \cos\alpha)} $$

Appliquons la formule du binôme conjugue :

$$ \tan(\alpha/2) = \frac{\sin\alpha \ (1 - \cos\alpha)}{1 - (\cos\alpha)^2} $$

Comme :

$$ (\sin\alpha)^2 = 1 - (\cos\alpha)^2 $$

cette relation devient :

$$ \tan(\alpha/2) = \frac{\sin\alpha \ (1 - \cos\alpha)}{(\sin\alpha)^2} $$

ce qui nous donne la deuxième forme :

$$ \tan(\alpha/2) = \frac{1 - \cos\alpha}{\sin\alpha} $$

* Formules de Simpson

#+TOC: headlines 1 local

** Linéarisation

Les formules de linéarisation de Simpson permettent de transformer les
produits en sommes.

*** En partant des cosinus de sommes et différences

- En additionant les deux équations suivantes :

$$ \left\{ \begin{array}{l}
\cos(\alpha + \beta) = \cos\alpha \ \cos\beta - \sin\alpha \ \sin\beta \\
\cos(\alpha - \beta) = \cos\alpha \ \cos\beta + \sin\alpha \ \sin\beta
\end{array} \right. $$

on obtient :

$$ \cos(\alpha + \beta) + \cos(\alpha - \beta) = 2 \ \cos\alpha \ \cos\beta $$

c’est-à-dire :

$$ \cos\alpha \ \cos\beta = \frac{\cos(\alpha + \beta) + \cos(\alpha - \beta)}{2} $$

- En soustrayant la première équation de la seconde, on obtient :

$$ \cos(\alpha - \beta) - \cos(\alpha + \beta) = 2 \ \sin\alpha \ \sin\beta $$

c’est-à-dire :

$$ \sin\alpha \ \sin\beta = \frac{\cos(\alpha - \beta) - \cos(\alpha + \beta)}{2} $$

*** En partant des sinus de sommes et différences

- En additionant les deux équations suivantes :

$$ \left\{ \begin{array}{l}
\sin(\alpha + \beta) = \sin\alpha \ \cos\beta + \sin\beta \ \cos\alpha \\
\sin(\alpha - \beta) = \sin\alpha \ \cos\beta - \sin\beta \ \cos\alpha
\end{array} \right. $$

on obtient :

$$ \sin(\alpha + \beta) + \sin(\alpha - \beta) = 2 \ \sin\alpha \ \cos\beta $$

c’est-à-dire :

$$ \sin\alpha \ \cos\beta = \frac{\sin(\alpha + \beta) + \sin(\alpha - \beta)}{2} $$

- En soustrayant la seconde équation de la première, on obtient :

$$ \sin(\alpha + \beta) - \sin(\alpha - \beta) = 2 \ \sin\beta \ \cos\alpha $$

c’est-à-dire :

$$ \cos\alpha \ \sin\beta = \frac{\sin(\alpha + \beta) - \sin(\alpha - \beta)}{2} $$

** Antilinéarisation

Les formules d’antilinéarisation de Simpson permettent de transformer les
sommes en produits.

*** Moyenne et écart

Le formules de linéarisation utilisent une somme et une différence
d’angle. Nous allons inverser ce raisonnement en exprimant deux angles
$\alpha$ et $\beta$ respectivement comme une somme et une différence de
deux variables, que nous appelons $\mu$ et $\delta$ :

$$ \alpha = \mu + \delta $$

$$ \beta = \mu - \delta $$

En additionnant ces deux équations, il vient :

$$ \alpha + \beta = \mu + \delta + \mu - \delta = 2 \ \mu $$

c’est-à-dire :

$$ \mu = \frac{\alpha + \beta}{2} $$

La variable $\mu$ représente la moyenne des deux angles. Si par contre,
nous soustrayons la seconde équation de la première, il vient :

$$ \alpha - \beta = \mu + \delta - \mu + \delta = 2 \ \delta $$

c’est-à-dire :

$$ \delta = \frac{\alpha - \beta}{2} $$

La variable $\delta$ représente la demi-différence des deux angles.

Nous disposons donc des relations inverses entre $\alpha$, $\beta$
et $\mu$, $\delta$.

Remarquons que :

$$ \delta = \alpha - \mu = \mu - \beta $$

La variable $\delta$ représente aussi l’écart entre $\alpha$ ou
$\beta$ et la moyenne $\mu$.

*** En partant des cosinus de sommes et différences

- Si on applique la formule de linéarisation des cosinus à $\mu$
  et $\delta$, on obtient :

$$ \cos(\mu + \delta) + \cos(\mu - \delta) = 2 \ \cos\mu \ \cos\delta $$

c’est-à-dire :

$$ \cos\alpha + \cos\beta
= 2 \ \cos\left(\frac{\alpha + \beta}{2}\right) \ \cos\left(\frac{\alpha - \beta}{2}\right) $$

- Similairement, on a :

$$ \cos(\mu - \delta) - \cos(\mu + \delta) = 2 \ \sin\mu \ \sin\delta $$

c’est-à-dire :

$$ \cos\beta - \cos\alpha
= 2 \ \sin\left(\frac{\alpha + \beta}{2}\right) \ \sin\left(\frac{\alpha - \beta}{2}\right) $$

*** En partant des sinus de sommes et différences

- Si on applique la formule de linéarisation des sinus à $\mu$ et
  $\delta$, on obtient :

$$ \sin(\mu + \delta) + \sin(\mu - \delta) = 2 \ \sin\mu \ \cos\delta $$

c’est-à-dire :

$$ \sin\alpha + \sin\beta
= 2 \ \sin\left(\frac{\alpha + \beta}{2}\right) \ \cos\left(\frac{\alpha - \beta}{2}\right) $$

- Similairement, on a :

$$ \sin(\mu + \delta) - \sin(\mu - \delta) = 2 \ \cos\mu \ \sin\delta $$

c’est-à-dire :

$$ \sin\alpha - \sin\beta
= 2 \ \cos\left(\frac{\alpha + \beta}{2}\right) \ \sin\left(\frac{\alpha - \beta}{2}\right) $$

* Formule de Mollweide

#+TOC: headlines 1 local

** Introduction

Soit un triangle quelconque :

#+attr_html: :width 30%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/formule-de-mollweide.svg]]

Le
[[file:trigonometrie.org::#heading:loi_des_sinus_corollaire][corollaire]]
de [[file:trigonometrie.org::#heading:loi_des_sinus][la loi des sinus]]
nous donne :

$$ \frac{a}{c} = \frac{\sin \alpha}{\sin \gamma} $$

et :

$$ \frac{b}{c} = \frac{\sin \beta}{\sin \gamma} $$

** Moyenne et écart

Pour plus de concision, on pose :

$$ \mu = \frac{\alpha + \beta}{2} $$

$$ \delta = \frac{\alpha - \beta}{2} $$

** Complémentarité

Comme la somme des angles d’un triangle vaut $180^\circ$, on a :

$$ \alpha + \beta = 180^\circ - \gamma $$

En divisant cette somme par deux, il vient :

$$ \mu = \frac{\alpha + \beta}{2} = 90^\circ - \frac{\gamma}{2} $$

Comme le sinus d’un angle est égal au cosinus de l’angle
complémentaire, on a :

$$ \sin \mu = \cos(\gamma/2) $$

et vice versa :

$$ \cos \mu = \sin(\gamma/2) $$

** Addition

On a :

$$ \frac{a + b}{c}
= \frac{a}{c} + \frac{b}{c}
= \frac{\sin \alpha}{\sin \gamma} + \frac{\sin \beta}{\sin \gamma}
= \frac{\sin \alpha + \sin \beta}{\sin \gamma} $$

L’antilinéarisation de Simpson nous permet de transformer la somme
en produit :

$$ \sin\alpha + \sin\beta
= 2 \ \sin\left(\frac{\alpha + \beta}{2}\right) \ \cos\left(\frac{\alpha - \beta}{2}\right) $$

ou, en utilisant la moyenne et l’écart :

$$ \sin\alpha + \sin\beta = 2 \ \sin\mu \ \cos\delta $$

Comme $\gamma$ est l’angle double de $\gamma / 2$, on a aussi :

$$ \sin\gamma = 2 \ \sin(\gamma/2) \ \cos(\gamma/2) $$

Le rapport de longueurs devient :

$$ \frac{a + b}{c}
= \frac{2 \ \sin\mu \ \cos\delta}{2 \ \sin(\gamma/2) \ \cos(\gamma/2)} $$

Comme $\sin(\gamma/2) = \cos\mu$ et $\cos(\gamma/2) = \sin\mu$, il vient :

$$ \frac{a + b}{c}
= \frac{2 \ \sin\mu \ \cos\delta}{2 \ \cos\mu \ \sin\mu}
= \frac{\cos\delta}{\cos\mu} $$

c’est-à-dire :

$$ \frac{a + b}{c}
= \frac{\cos\Big[(\alpha - \beta)/2\Big]}{\cos\Big[(\alpha + \beta)/2\Big]} $$

La complémentarite de $\mu$ et $\gamma/2$ nous donne la variante :

$$ \frac{a + b}{c}
= \frac{\cos\Big[(\alpha - \beta)/2\Big]}{\sin(\gamma/2)} $$

** Soustraction

On a :

$$ \frac{a - b}{c}
= \frac{a}{c} - \frac{b}{c}
= \frac{\sin \alpha}{\sin \gamma} - \frac{\sin \beta}{\sin \gamma}
= \frac{\sin \alpha - \sin \beta}{\sin \gamma} $$

L’antilinéarisation de Simpson nous permet de transformer la différence
en produit :

$$ \sin\alpha - \sin\beta
= 2 \ \sin\left(\frac{\alpha - \beta}{2}\right) \ \cos\left(\frac{\alpha + \beta}{2}\right) $$

ou, en utilisant la moyenne et l’écart :

$$ \sin\alpha - \sin\beta = 2 \ \sin\delta \ \cos\mu $$

Comme $\gamma$ est l’angle double de $\gamma / 2$, on a :

$$ \sin\gamma = 2 \ \sin(\gamma/2) \ \cos(\gamma/2) $$

Le rapport de longueurs devient :

$$ \frac{a - b}{c}
= \frac{2 \ \sin\delta \ \cos\mu}{2 \ \sin(\gamma/2) \ \cos(\gamma/2)} $$

Comme $\sin(\gamma/2) = \cos\mu$ et $\cos(\gamma/2) = \sin\mu$, il vient :

$$ \frac{a - b}{c}
= \frac{2 \ \sin\delta \ \cos\mu}{2 \ \cos\mu \ \sin\mu}
= \frac{\sin\delta}{\sin\mu} $$

c’est-à-dire :

$$ \frac{a - b}{c}
= \frac{\sin\Big[(\alpha - \beta)/2\Big]}{\sin\Big[(\alpha + \beta)/2\Big]} $$

La complémentarite de $\mu$ et $\gamma/2$ nous donne la variante :

$$ \frac{a - b}{c}
= \frac{\sin\Big[(\alpha - \beta)/2\Big]}{\cos(\gamma/2)} $$

** Loi des tangentes

La loi des tangente peut se dériver directement de la formule de
Mollweide. En effet :

$$ \frac{a - b}{a + b}
= \frac{a - b}{c} \cdot \frac{c}{a + b}
= \frac{\sin\delta}{\sin\mu} \cdot
\frac{\cos\mu}{\cos\delta} $$

que l’on peut réécrire :

$$ \frac{a - b}{a + b}
= \frac{\sin\delta / \cos\delta}{\sin\mu / \cos\mu}
= \frac{\tan\delta}{\tan\mu} $$

c’est-à-dire :

$$ \frac{a - b}{a + b}
= \frac{\tan\Big[(\alpha - \beta)/2\Big]}{\tan\Big[(\alpha + \beta)/2\Big]} $$

* Réduction d’une combinaison linéaire de sinus et cosinus

#+TOC: headlines 1 local

** Réduction

Soit un angle $\theta$. On peut utiliser les formules de sommes d’angles
pour réduire une expression trigonométrique de la forme :

$$ T = a \ \sin \theta + b \ \cos \theta $$

Soit le triangle $ABC$ rectangle en $B$, de cathètes $a$ et $b$ :

#+attr_html: :width 25%
#+attr_latex: :width 0.7\linewidth
[[file:tikz/longueurs-angles-triangle-rectangle.svg]]

- Le théorème de Pythagore nous donne :

$$ c = \sqrt{a^2 + b^2} $$

- On a :

$$ \frac{a}{c} = \cos\alpha = \sin\beta
\qquad \qquad \qquad
\frac{b}{c} = \cos\beta = \sin\alpha  $$

d’où :

$$ \alpha
= \arccos\left( \frac{a}{c} \right)
= \arcsin\left( \frac{b}{c} \right) $$

$$ \beta
= \arccos\left( \frac{b}{c} \right)
= \arcsin\left( \frac{a}{c} \right) $$

- Notre expression peut se réécrire :

$$ T = \frac{c}{c} \ (a \ \sin \theta + b \ \cos \theta) $$

ou encore :

$$ T = c \ \left( \frac{a}{c} \ \sin \theta + \frac{b}{c} \ \cos \theta \right) $$

- Les fractions $a/c$ et $b/c$ sont respectivement le cosinus et le sinus
  de l’angle $\alpha$ :

$$ T = c \ \left( \cos \alpha \ \sin \theta + \sin \alpha \ \cos \theta \right) $$

L’expression entre parenthèses n’est rien d’autre que le sinus de la
somme de $\theta$ et $\alpha$, et on a finalement :

$$ a \ \sin \theta + b \ \cos \theta = c \ \sin(\theta + \alpha) $$

- Si on utilise l’angle $\beta$, on a plutôt :

$$ T = c \ \left( \sin \beta \ \sin \theta + \cos \beta \ \cos \theta \right) $$

L’expression entre parenthèses n’est rien d’autre que le cosinus de la
différence de $\theta$ et $\beta$, et on a finalement :

$$ a \ \sin \theta + b \ \cos \theta = c \ \cos(\theta - \beta) $$

** Résolution d’équation

On peut utiliser cette technique pour résoudre en $\theta$ une équation
de la forme :

$$ a \ \sin \theta + b \ \cos \theta = d $$

- La technique de réduction nous donne :

$$ c \ \sin(\theta + \alpha) = d $$

En divisant par $c$, il vient simplement :

$$ \sin(\theta + \alpha) = \frac{d}{c} $$

Une des solutions se trouve en prenant l’arc sinus des deux membres :

$$ \theta + \alpha = \arcsin\left( \frac{d}{c}\right) $$

ce qui nous donne :

$$ \theta = \arcsin\left( \frac{d}{c}\right) - \alpha $$

- On a aussi :

$$ \cos(\theta - \beta) = \frac{d}{c} $$

Une des solutions se trouve en prenant l’arc cosinus des deux membres :

$$ \theta - \beta = \arccos\left( \frac{d}{c}\right) $$

ce qui nous donne :

$$ \theta = \arccos\left( \frac{d}{c}\right) + \beta $$
