
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Trigonometrie : sommes
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Somme de deux angles

#+TOC: headlines 1 local

** Introduction

Considérons le diagramme suivant :

#+attr_html: :width 800px
#+attr_latex: :width 800px
[[file:../include/tikz/trigo-somme-angles.svg]]

** Préambule

Comme $\alpha$ et $\gamma$ sont les deux angles non droits d’un triangle
rectangle, on a :

$$ \gamma = \frac{\pi}{2} - \alpha $$

Comme $\gamma$, $\delta$ et $\pi/2$ forment ensemble un angle plat, on a :

$$ \gamma + \delta + \frac{\pi}{2} = \pi $$

En substituant la valeur de $\gamma$ par rapport à $\alpha$, cette
relation devient :

$$ \frac{\pi}{2} - \alpha + \delta + \frac{\pi}{2} = \pi $$

ou encore :

$$ - \alpha + \delta = 0 $$

et finalement :

$$ \delta = \alpha $$

** Cosinus de la somme

Le diagramme nous montre que :

$$ \cos(\alpha+\beta) + \sin\beta \ \sin\delta = \cos\beta \ \cos\alpha $$

mais comme $\delta = \alpha$, cette relation devient :

$$ \cos(\alpha+\beta) + \sin\beta \ \sin\alpha = \cos\beta \ \cos\alpha $$

En isolant $\cos(\alpha+\beta)$ :

$$ \cos(\alpha+\beta) = \cos\beta \ \cos\alpha - \sin\beta \ \sin\alpha $$

ou encore :

$$ \cos(\alpha+\beta) = \cos\alpha \ \cos\beta - \sin\alpha \ \sin\beta $$

ce qui nous donne la formule pour le cosinus d’une somme d’angles.

** Sinus de la somme

Le diagramme nous montre que :

$$ \sin(\alpha+\beta) = \cos\beta \ \sin\alpha + \cos\delta \ \sin\beta $$

mais comme $\delta = \alpha$, cette relation devient :

$$ \sin(\alpha+\beta) = \cos\beta \ \sin\alpha + \cos\alpha \ \sin\beta $$

ou encore :

$$ \sin(\alpha+\beta) = \sin\alpha \ \cos\beta + \sin\beta \ \cos\alpha $$

ce qui nous donne la formule pour le sinus d’une somme d’angles.

** Tangente de la somme

On a :

$$ \tan(\alpha + \beta) = \frac{\sin(\alpha+\beta)}{\cos(\alpha+beta)} $$

En utilisant les forumes de sommes pour le sinus et le cosinus, cette
relation devient :

$$ \tan(\alpha + \beta)
= \frac{\sin\alpha \ \cos\beta + \sin\beta \ \cos\alpha}{\cos\alpha \ \cos\beta - \sin\alpha \ \sin\beta} $$

En divisant numérateur et dénominateur de la fraction par $\cos\alpha \
\cos\beta$, il vient :

$$ \tan(\alpha + \beta)
= \frac{\sin\alpha / \cos\alpha + \sin\beta / \cos\beta}{1 - (\sin\alpha / \cos\alpha) (\sin\beta / \cos\beta)} $$

En se rappelant la relation fondamentale liant tangente, sinus et
cosinus on obtient finalement :

$$ \tan(\alpha + \beta)
= \frac{\tan\alpha + \tan\beta}{1 - \tan\alpha \ \tan\beta} $$

* Différence de deux angles

#+TOC: headlines 1 local

** Par angle négatif

#+TOC: headlines 1 local

*** Cosinus de la différence

On part de la constatation que :

$$ \cos(\alpha - \beta) = \cos\big( \alpha + (-\beta) \big) $$

La formule de la somme nous donne :

$$ \cos\big( \alpha + (-\beta) \big) = \cos\alpha \ \cos(-\beta) - \sin\alpha \ \sin(-\beta) $$

Mais comme :

$$ \cos(-\beta) = \cos(\beta) $$

$$ \sin(-\beta) = - \sin(\beta) $$

le cosinus de la différence peut se réécrire :

$$ \cos(\alpha - \beta) = \cos\alpha \ \cos\beta + \sin\alpha \ \sin\beta $$

*** Sinus de la différence

On part de la constatation que :

$$ \sin(\alpha - \beta) = \sin\big( \alpha + (-\beta) \big) $$

La formule de la somme nous donne :

$$ \sin\big( \alpha + (-\beta) \big) = \sin\alpha \ \cos(-\beta) + \sin(-\beta) \ \cos\alpha $$

Mais comme :

$$ \cos(-\beta) = \cos(\beta) $$

$$ \sin(-\beta) = - \sin(\beta) $$

le sinus de la différence peut se réécrire :

$$ \sin(\alpha - \beta) = \sin\alpha \ \cos\beta - \sin\beta \ \cos\alpha $$

*** Tangente de la différence

On part de la constatation que :

$$ \tan(\alpha - \beta) = \tan\big(\alpha + (-\beta)\big) $$

La formule de la somme nous donne :

$$ \tan\big(\alpha + (-\beta)\big) = \frac{\tan\alpha + \tan(-\beta)}{1 - \tan\alpha \ \tan(-\beta)} $$

Mais comme :

$$ \tan(-\beta) = - \tan\beta $$

la tangente de la différence peut se réécrire :

$$ \tan(\alpha - \beta) = \frac{\tan\alpha - \tan\beta}{1 + \tan\alpha \ \tan\beta} $$

** Par point de vue dual

#+TOC: headlines 1 local

*** Introduction

Choisissons deux angles $\alpha$ et $\beta$ et posons :

$$ \gamma = \alpha - \beta $$

On a alors :

$$ \alpha = \gamma + \beta $$

*** Cosinus de la différence

Le formules de sommes nous donnent :

$$ \left\{ \begin{array}{l}
\sin\alpha = \sin(\gamma+\beta) = \sin\gamma \ \cos\beta + \sin\beta \ \cos\gamma \\
\cos\alpha = \cos(\gamma+\beta) = \cos\gamma \ \cos\beta - \sin\gamma \ \sin\beta
\end{array} \right. $$

En multipliant la première équation par $\sin\beta$ et la seconde
par $\cos\beta$, on obtient :

$$ \left\{ \begin{array}{l}
\sin\alpha \ \sin\beta = \sin\gamma \ \sin\beta \ \cos\beta + (\sin\beta)^2 \ \cos\gamma \\
\cos\alpha \ \cos\beta = \cos\gamma \ (\cos\beta)^2 - \sin\gamma \ \sin\beta \ \cos\beta
\end{array} \right. $$

En additionant ces deux équations, des termes dans le membre de droite
se simplifient et il reste :

$$ \sin\alpha \ \sin\beta + \cos\alpha \ \cos\beta
= \cos\gamma \left[ (\cos\beta)^2 + (\sin\gamma)^2 \right] $$

Le terme entre crochet vaut $1$ et :

$$ \sin\alpha \ \sin\beta + \cos\alpha \ \cos\beta = \cos\gamma $$

Mais comme $\cos\gamma = \cos(\alpha - \beta)$, cela nous donne la
formule du sinus de la différence :

$$ \cos(\alpha - \beta) = \cos\alpha \ \cos\beta + \sin\alpha \ \sin\beta $$

*** Sinus de la différence

Le formules de sommes nous donnent :

$$ \left\{ \begin{array}{l}
\sin\alpha = \sin(\gamma+\beta) = \sin\gamma \ \cos\beta + \sin\beta \ \cos\gamma \\
\cos\alpha = \cos(\gamma+\beta) = \cos\gamma \ \cos\beta - \sin\gamma \ \sin\beta
\end{array} \right. $$

En multipliant la première équation par $\cos\beta$ et la seconde
par $\sin\beta$, on obtient :

$$ \left\{ \begin{array}{l}
\sin\alpha \ \cos\beta = \sin\gamma \ (\cos\beta)^2 + \sin\beta \ \cos\beta \ \cos\gamma \\
\cos\alpha \ \sin\beta = \cos\gamma \ \sin\beta \ \cos\beta - \sin\gamma \ (\sin\beta)^2
\end{array} \right. $$

En soustrayant la seconde équation de la première, des termes dans le
membre de droite se simplifient et il reste :

$$ \sin\alpha \ \cos\beta - \cos\alpha \ \sin\beta
= \sin\gamma \left[ (\cos\beta)^2 + (\sin\gamma)^2 \right] $$

Le terme entre crochet vaut $1$ et :

$$ \sin\alpha \ \cos\beta - \cos\alpha \ \sin\beta = \sin\gamma $$

Mais comme $\sin\gamma = \sin(\alpha - \beta)$, cela nous donne la
formule du sinus de la différence :

$$ \sin(\alpha - \beta) = \sin\alpha \ \cos\beta - \cos\alpha \ \sin\beta $$

* Angle double

#+TOC: headlines 1 local

** Introduction

On étudie le cas particulier de la somme de deux angles identiques :

** Cosinus de l’angle double

On a :

$$ \cos(2 \ \alpha)
= \cos(\alpha+\alpha)
= \cos\alpha \ \cos\alpha - \sin\alpha \ \sin\alpha $$

et donc :

$$ \cos(2 \ \alpha) = (\cos\alpha)^2 - (\sin\alpha)^2 $$

*** Corollaires

En se rappelant la relation fondamentale :

$$ (\cos \alpha)^2 + (\sin \alpha)^2 = 1 $$

on peut remplacer le carré du sinus :

$$ (\sin \alpha)^2 = 1 - (\cos \alpha)^2 $$

dans la relation du cosinus de l’angle double, ce qui nous donne :

$$ \cos(2 \ \alpha) = 2 \ (\cos\alpha)^2 - 1 $$

Si on  remplace le carré du cosinus :

$$ (\cos \alpha)^2 = 1 - (\sin \alpha)^2 $$

on obtient :

$$ \cos(2 \ \alpha) = 1 - 2 \ (\sin\alpha)^2 $$

** Sinus de l’angle double

On a :

$$ \sin(2 \ \alpha)
= \sin(\alpha + \alpha)
= \sin\alpha \ \cos\alpha + \sin\alpha \ \cos\alpha $$

et donc :

$$ \sin(2 \ \alpha) = 2 \ \sin\alpha \ \cos\alpha $$

* Formules de Simpson

#+TOC: headlines 1 local

** Linéarisation

Les formules de linéarisation de Simpson permettent de transformer les
produits en sommes.

*** En partant des cosinus de sommes et différences

En additionant les deux équations suivantes :

$$ \left\{ \begin{array}{l}
\cos(\alpha + \beta) = \cos\alpha \ \cos\beta - \sin\alpha \ \sin\beta \\
\cos(\alpha - \beta) = \cos\alpha \ \cos\beta + \sin\alpha \ \sin\beta
\end{array} \right. $$

on obtient :

$$ \cos(\alpha + \beta) + \cos(\alpha - \beta) = 2 \ \cos\alpha \ \cos\beta $$

c’est-à-dire :

$$ \cos\alpha \ \cos\beta = \frac{\cos(\alpha + \beta) + \cos(\alpha - \beta)}{2} $$

En soustrayant la première équation de la seconde, on obtient :

$$ \cos(\alpha - \beta) - \cos(\alpha + \beta) = 2 \ \sin\alpha \ \sin\beta $$

c’est-à-dire :

$$ \sin\alpha \ \sin\beta = \frac{\cos(\alpha - \beta) - \cos(\alpha + \beta)}{2} $$

*** En partant des sinus de sommes et différences

En additionant les deux équations suivantes :

$$ \left\{ \begin{array}{l}
\sin(\alpha + \beta) = \sin\alpha \ \cos\beta + \sin\beta \ \cos\alpha \\
\sin(\alpha - \beta) = \sin\alpha \ \cos\beta - \sin\beta \ \cos\alpha
\end{array} \right. $$

on obtient :

$$ \sin(\alpha + \beta) + \sin(\alpha - \beta) = 2 \ \sin\alpha \ \cos\beta $$

c’est-à-dire :

$$ \sin\alpha \ \cos\beta = \frac{\sin(\alpha + \beta) + \sin(\alpha - \beta)}{2} $$

En soustrayant la seconde équation de la première, on obtient :

$$ \sin(\alpha + \beta) - \sin(\alpha - \beta) = 2 \ \sin\beta \ \cos\alpha $$

c’est-à-dire :

$$ \cos\alpha \ \sin\beta = \frac{\sin(\alpha + \beta) - \sin(\alpha - \beta)}{2} $$

** Antilinéarisation

Les formules d’antilinéarisation de Simpson permettent de transformer les
sommes en produits.

Choisissons des angles $\alpha$ et $\beta$ et posons :

$$ \mu = \frac{\alpha + \beta}{2} $$

$$ \delta = \frac{\alpha - \beta}{2} $$

En additionnant ces deux équations, on obtient :

$$ \mu + \delta = \alpha $$

En soustrayant la seconde équation de la première, on obtient :

$$ \mu - \delta = \beta $$

Nous disposons donc des relations inverses entre $\mu,\delta$ et
$\alpha,\beta$.

*** En partant des cosinus de sommes et différences

Si on applique la formule de linéarisation des cosinus à $\mu$ et
$\delta$, on obtient :

$$ \cos(\mu + \delta) + \cos(\mu - \delta) = 2 \ \cos\mu \ \cos\delta $$

c’est-à-dire :

$$ \cos\alpha + \cos\beta = 2 \ \cos\left(\frac{\alpha + \beta}{2}\right) \ \cos\left(\frac{\alpha - \beta}{2}\right) $$

Similairement, on a :

$$ \cos(\mu - \delta) - \cos(\mu + \delta) = 2 \ \sin\mu \ \sin\delta $$

c’est-à-dire :

$$ \cos\beta - \cos\alpha = 2 \ \sin\left(\frac{\alpha + \beta}{2}\right) \ \sin\left(\frac{\alpha - \beta}{2}\right) $$

*** En partant des sinus de sommes et différences

Si on applique la formule de linéarisation des sinus à $\mu$ et
$\delta$, on obtient :

$$ \sin(\mu + \delta) + \sin(\mu - \delta) = 2 \ \sin\mu \ \cos\delta $$

c’est-à-dire :

$$ \sin\alpha + \sin\beta = 2 \ \sin\left(\frac{\alpha + \beta}{2}\right) \ \cos\left(\frac{\alpha - \beta}{2}\right) $$

Similairement, on a :

$$ \sin(\mu + \delta) - \sin(\mu - \delta) = 2 \ \cos\mu \ \sin\delta $$

c’est-à-dire :

$$ \sin\alpha - \sin\beta = 2 \ \cos\left(\frac{\alpha + \beta}{2}\right) \ \sin\left(\frac{\alpha - \beta}{2}\right) $$

* Réduction d’une combinaison linéaire de sinus et cosinus

#+TOC: headlines 1 local

** Réduction

Soit un angle $\theta$. On peut utiliser les formules de sommes d’angles
pour réduire une expression trigonométrique de la forme :

$$ T = a \ \sin \theta + b \ \cos \theta $$

Soit le triangle rectangle de cathétes $a$ et $b$ et d’angles $\alpha$
et $\beta$ :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/angles-triangle-rectangle.svg]]

On a :

$$ c = \sqrt{a^2 + b^2} $$

Notre expression peut se réécrire :

$$ T = \frac{c}{c} \ (a \ \sin \theta + b \ \cos \theta) $$

ou encore :

$$ T = c \ \left( \frac{a}{c} \ \sin \theta + \frac{b}{c} \ \cos \theta \right) $$

Les fractions $a/c$ et $b/c$ sont respectivement le cosinus et le sinus
de l’angle $\alpha$ :

$$ T = c \ \left( \cos \alpha \ \sin \theta + \sin \alpha \ \cos \theta \right) $$

L’expression entre parenthèses n’est rien d’autre que le sinus de la
somme de $\theta$ et $\alpha$, et on a finalement :

$$ a \ \sin \theta + b \ \cos \theta = c \ \sin(\theta + \alpha) $$

Si on utilise l’angle $\beta$, on a plutôt :

$$ T = c \ \left( \sin \beta \ \sin \theta + \cos \beta \ \cos \theta \right) $$

L’expression entre parenthèses n’est rien d’autre que le cosinus de la
différence de $\theta$ et $\beta$, et on a finalement :

$$ a \ \sin \theta + b \ \cos \theta = c \ \cos(\theta - \beta) $$

** Résolution d’équation

On peut utiliser cette technique pour résoudre en $\theta$ une équation
de la forme :

$$ a \ \sin \theta + b \ \cos \theta = d $$

En divisant par $c$, il vient simplement :

$$ \sin(\theta + \alpha) = \frac{d}{c} $$

qui admet notamment comme solution :

$$ \theta = \arcsin\left( \frac{d}{c}\right) - \alpha $$

On a aussi :

$$ \cos(\theta - \beta) = \frac{d}{c} $$

qui admet entre-autres comme solution :

$$ \theta = \beta + \arccos\left( \frac{d}{c}\right) $$
