
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Trigonométrie des polygones
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Introduction

Lors de l’étude des polygones, nous avons vu quelques résultats
concernant des valeurs particulières de fonctions trigonométriques. Nous
utilisons dans ce chapitre la trigonométrie pour étendre ces résultats
à d’autres angles.

Dans ce chapitre, on pose $\phi$ pour le nombre d’or :

$$ \phi = \frac{1 + \sqrt{5}}{2} $$

et $\psi$ pour le nombre d’argent :

$$ \psi = 1 + \sqrt{2} $$

* Angle de 36° et associés

#+TOC: headlines 1 local

** Cosinus de 36° par la trigonométrie

Pendant l’étude des propriétés du pentagone, nous avons vu une
méthode permettant d’obtenir la valeur du
[[file:polygones.org::#heading:cosinus_de_36][cosinus de 36°]].
Nous présentons ici une autre méthode, qui utilise des relations
trigonométriques et algébriques.

On commence par constater que la somme des angles 72° et 18° donne 90°.
Le cosinus de cet angle est donc nul :

$$ \cos(72^\circ + 18^\circ) = \cos 90^\circ = 0 $$

La formule de la somme nous donne :

$$ \cos(72^\circ + 18^\circ)
= \cos 72^\circ \ \cos 18^\circ - \sin 72^\circ \ \sin 18^\circ $$

On en déduit que :

$$ \cos 72^\circ \ \cos 18^\circ - \sin 72^\circ \ \sin 18^\circ = 0 $$

ou encore :

$$ \cos 72^\circ \ \cos 18^\circ = \sin 72^\circ \ \sin 18^\circ $$

Posons :

$$ c = \cos 36^\circ $$

Nous allons rééxprimer les grandeurs ci-dessus en fonction de
$c$. Remarquons que :

$$ \sin 36^\circ = \sqrt{1 - (\cos 36^\circ)^2} = \sqrt{1 - c^2} $$

Le cosinus de 72° se réécrit :

$$ \cos 72^\circ = 2 \ (\cos 36^\circ)^2 - 1 = 2 \ c^2 - 1 $$

Le cosinus de 18° se réécrit :

$$ (\cos 18^\circ)^2 = \frac{1 + \cos 36^\circ}{2} = \frac{1 + c}{2} $$

d’où :

$$ \cos 18^\circ = \sqrt{\frac{1 + c}{2}} $$

Le sinus de 72° se réécrit :

$$ \sin 72^\circ
= 2 \ \cos 36^\circ \ \sin 36^\circ
= 2 \ c \ \sqrt{1 - c^2} $$

Le sinus de 18° se réécrit :

$$ (\sin 18^\circ)^2 = \frac{1 - \cos 36^\circ}{2} = \frac{1 - c}{2} $$

d’où :

$$ \sin 18^\circ = \sqrt{\frac{1 - c}{2}} $$

La relation :

$$ \cos 72^\circ \ \cos 18^\circ = \sin 72^\circ \ \sin 18^\circ $$

devient alors :

$$ (2 \ c^2 - 1) \ \sqrt{\frac{1+c}{2}} = 2 \ c \ \sqrt{1-c^2} \ \sqrt{\frac{1-c}{2}} $$

Exprimons les racines de fractions comme fractions de racines :

$$ (2 \ c^2 - 1) \ \frac{\sqrt{1+c}}{\sqrt{2}} = 2 \ c \ \sqrt{1-c^2} \ \frac{\sqrt{1-c}}{\sqrt{2}} $$

Multiplions par $\sqrt{2}$ :

$$ (2 \ c^2 - 1) \ \sqrt{1+c} = 2 \ c \ \sqrt{1-c^2} \ \sqrt{1-c} $$

Utilisons la formule du binôme conjugué :

$$ (2 \ c^2 - 1) \ \sqrt{1+c} = 2 \ c \ \sqrt{(1-c)(1+c)} \ \sqrt{1-c} $$

Exprimons la racine carrée du produit comme produit de racines carrées :

$$ (2 \ c^2 - 1) \ \sqrt{1+c} = 2 \ c \ \sqrt{1-c} \ \sqrt{1+c} \ \sqrt{1-c} $$

Divisons par $\sqrt{1+c}$ :

$$ 2 \ c^2 - 1 = 2 \ c \ \sqrt{1-c} \ \sqrt{1-c} $$

Exprimons le produit de racines carrées comme la racine carrée d’un
produit :

$$ 2 \ c^2 - 1 = 2 \ c \ \sqrt{(1-c)^2} $$

Ce produit étant un carré, on a la racine carrée d’un carré,
c’est-à-dire, autrement dit une fonction identité :

$$ 2 \ c^2 - 1 = 2 \ c \ (1-c) $$

Distribuons :

$$ 2 \ c^2 - 1 = 2 \ c - 2 \ c^2 $$

On obtient finalement une équation du second degré :

$$ 4 \ c^2 - 2 \ c - 1 = 0 $$

Le discriminant de cette équation s’écrit :

$$ \Delta = 4 - 4 \cdot 4 \cdot (-1) = 20 $$

Remarquons que :

$$ \sqrt{\Delta} = \sqrt{20} = \sqrt{4 \cdot 5} = \sqrt{4} \cdot \sqrt{5} = 2 \ \sqrt{5} $$

On en déduit les solutions possibles pour $c$ :

$$ c_+ = \frac{2 + 2 \ \sqrt{5}}{8} $$

$$ c_- = \frac{2 - 2 \ \sqrt{5}}{8} $$

ou encore :

$$ c_+ = \frac{1 + \sqrt{5}}{4} $$

$$ c_- = \frac{1 - \sqrt{5}}{4} $$

Le cosinus de 36° étant un réel positif, on en déduit que :

$$ \cos 36^\circ = \frac{1 + \sqrt{5}}{4} $$

c’est-à-dire la moitié du nombre d’or :

$$ \cos 36^\circ = \frac{\phi}{2} $$

** Sinus de 36°

Le sinus de 36° vaut :

$$ \sin 36^\circ = \sqrt{1 - \cos 36^\circ} = \sqrt{1 - \frac{\phi^2}{4}} $$

Mettons l’intérieur de la racine au même dénominateur :

$$ \sin 36^\circ = \sqrt{\frac{4 - \phi^2}{4}} $$

Faisons sortir le dénominateur de la racine :

$$ \sin 36^\circ = \frac{\sqrt{4 - \phi^2}}{2} $$

Comme $\phi^2 = \phi + 1$, il vient :

$$ \sin 36^\circ = \frac{\sqrt{4 - \phi - 1}}{2} $$

et finalement :

$$ \sin 36^\circ = \frac{\sqrt{3 - \phi}}{2}$$

*** Cosinus de 54°

Le cosinus de 54° est égal au sinus de l’angle complémentaire,
à savoir 36° :

$$ \cos 54^\circ = \frac{\sqrt{3 - \phi}}{2}$$

** Cosinus de 72°

Pour calculer le cosinus de 72°, angle double de 36°,
on utilise la formule du cosinus de l’angle double :

$$ \cos 72^\circ
= 2 \ (\cos 36^\circ)^2 - 1
= \frac{2 \ \phi^2}{4} - 1
= \frac{\phi^2}{2} - 1 $$

Par définition du nombre d’or, $\phi^2 = \phi + 1$ et on a :

$$ \cos 72^\circ = \frac{\phi + 1}{2} - 1 $$

puis :

$$ \cos 72^\circ = \frac{\phi + 1 - 2}{2} $$

et finalement :

$$ \cos 72^\circ = \frac{\phi - 1}{2} $$

*** Sinus de 18°

Le sinus de 18° est égal au cosinus de l’angle complémentaire,
à savoir 72° :

$$ \sin 18^\circ = \frac{\phi - 1}{2} $$

** Cosinus de 18°

Pour calculer le cosinus de 18°, angle moitié de 36°,
on utilise la formule inverse du cosinus de l’angle double :

$$ (\cos 18^\circ)^2 = \frac{1 + \cos 36^\circ}{2} = \frac{1 + \phi / 2}{2} $$

Multiplions par deux le numérateur de le dénominateur de la fraction du
membre de droite :

$$ (\cos 18^\circ)^2 = \frac{2 + \phi}{4} $$

puis prenons la racine :

$$ \cos 18^\circ = \sqrt{\frac{2 + \phi}{4}} $$

et faisons sortir le dénominateur :

$$ \cos 18^\circ = \frac{\sqrt{\phi + 2}}{2} $$

*** Sinus de 72°

Le sinus de 72° est égal au cosinus de l’angle complémentaire,
à savoir 18° :

$$ \sin 72^\circ = \frac{\sqrt{\phi + 2}}{2} $$

** Tangente de 36°

La tangente de 36° vaut :

$$ \tan 36^\circ = \frac{\sin 36^\circ}{\cos 36^\circ} = \frac{\sqrt{3 - \phi}/2}{\phi / 2} $$

Multiplions numérateur et dénominateur de la fraction du membre de
droite par $2$ :

$$ \tan 36^\circ = \frac{\sqrt{3 - \phi}}{\phi} $$

Faisons renter le dénominateur dans la racine :

$$ \tan 36^\circ = \sqrt{\frac{3 - \phi}{\phi^2}} = \sqrt{\frac{3}{\phi^2} - \unsur{\phi}} $$

Nous avons vu dans la section sur le
[[file:proportions-metalliques.org::#heading:nombre_d_or][nombre d’or]]
que :

$$ \unsur{\phi} = \phi - 1 \qquad\qquad\qquad
\unsur{\phi^2} = 2 - \phi $$

La relation précédente devient donc :

$$ \tan 36^\circ = \sqrt{3 \ (2 - \phi) - (\phi - 1)} = \sqrt{6 - 3 \ \phi - \phi + 1} $$

et finalement :

$$ \tan 36^\circ = \sqrt{7 - 4 \ \phi} $$

*** Tangente de 54°

On en déduit la tangente de l’angle complémentaire de 54° :

$$ \tan 54^\circ = \unsur{\tan 36^\circ} = \unsur{\sqrt{7 - 4 \ \phi}} $$

** Tangente de 72°

La relation fondamentale de la tangente nous donne :

$$ \tan 72° = \frac{\sin 72°}{\cos 72°} $$

Nous pouvons remplacer les sinus et cosinus de 72° par les valeurs
déjkà obtenues :

$$ \tan 72° = \frac{\sqrt{\phi + 2}/2}{(\phi - 1)/2} $$

Multiplions numérateur et dénominateur de la fraction du membre de
droite par $2$ :

$$ \tan 72° = \frac{\sqrt{\phi + 2}}{\phi - 1} $$

Multiplions la relation :

$$ \unsur{\phi} = \phi - 1 $$

par $\phi/(\phi - 1)$. on obtient :

$$ \unsur{\phi - 1} = \phi $$

L’expression de la tangente devient donc :

$$ \tan 72° = \phi \ \sqrt{\phi + 2} $$

Faisons rentrer $\phi$ dans la racine carrée :

$$ \tan 72° = \sqrt{\phi^2 \ (\phi + 2)} $$

Remplaçons $\phi^2$ par $\phi + 1$ :

$$ \tan 72° = \sqrt{(\phi + 1) \ (\phi + 2)} $$

Distribuons :

$$ \tan 72° = \sqrt{\phi^2 + 2 \ \phi + \phi + 1} $$

ou encore :

$$ \tan 72° = \sqrt{\phi + 1 + 2 \ \phi + \phi + 1} $$

On a finalement :

$$ \tan 72° = \sqrt{4 \ \phi + 3} $$

*** Tangente de 18°

On en déduit la tangente de l’angle complémentaire de 18° :

$$ \tan 18^\circ = \unsur{\tan 72^\circ} = \unsur{\sqrt{4 \ \phi + 3}} $$

* Angle de 22.5° et associés

#+TOC: headlines 1 local

** Cosinus de 22.5°

La formule du carré du cosinus de l’angle moitié nous donne :

$$ \big[ \cos 22.5^\circ \big]^2 = \frac{1 + \cos 45^\circ}{2} $$

Comme le cosinus de 45° vaut $\sqrt{2}/2$, cette relation devient :

$$ \big[ \cos 22.5^\circ \big]^2 = \frac{1 + \sqrt{2}/2}{2} $$

ou encore :

$$ \big[ \cos 22.5^\circ \big]^2
= \frac{(2 + \sqrt{2})/2}{2}
= \frac{2 + \sqrt{2}}{4} $$

Prenons la racine carrée. Comme le cosinus de 22.5° est manifestement un
réel positif, on a :

$$ \cos 22.5° = \frac{\sqrt{2 + \sqrt{2}}}{2} $$

Le nombre dans la racine du numérateur peut s’exprimer en fonction
du nombre d’argent :

$$ 2 + \sqrt{2} = 1 + (1 + \sqrt{2}) = 1 + \psi $$

On a donc finalement :

$$ \cos 22.5° = \frac{\sqrt{\psi + 1}}{2} $$

*** Sinus de 67.5°

Le sinus de 67.5° est égal au cosinus de l’angle complémentaire,
à savoir 22.5° :

$$ \sin 67.5° = \frac{\sqrt{\psi + 1}}{2} $$

** Sinus de 22.5°

La relation fondamentale entre sinus et cosinus nous donne :

$$ \big[ \sin 22.5° \big]^2 = 1 - \big[ \cos 22.5° \big]^2 = 1 - \frac{\psi + 1}{4} $$

Mettons les termes du membre de droite au même dénominateur :

$$ \big[ \sin 22.5° \big]^2 = \frac{4 - (\psi + 1)}{4} $$

On a donc :

$$ \big[ \sin 22.5° \big]^2 = \frac{4 - \psi - 1}{4} $$

ou encore :

$$ \big[ \sin 22.5° \big]^2 = \frac{3 - \psi}{4} $$

Ce qui nous donne la valeur du sinus de 22.5° en prenant la racine
carrée :

$$ \sin 22.5° = \frac{\sqrt{3 - \psi}}{2} $$

*** Cosinus de 67.5°

Le cosinus de 67.5° est égal au sinus de l’angle complémentaire,
à savoir 22.5° :

$$ \cos 67.5° = \frac{\sqrt{3 - \psi}}{2} $$

** Tangente de 67.5° par la trigonométrie

Pendant l’étude des propriétés de l’octogone, nous
avons vu une méthode permettant d’obtenir la valeur de
[[file:polygones.org::#heading:tangente_de_67_5][la tangente de 67.5°]].

Nous pouvons retrouver ce résultat par la relation fondamentale de la
tangente :

$$ \tan 67.5^\circ = \frac{\sin 67.5^\circ}{\cos 67.5^\circ} $$

Remplaçons le sinus et le cosinus par les valeurs obtenues plut tôt :

$$ \tan 67.5^\circ = \frac{\sqrt{\psi + 1}/2}{\sqrt{3 - \psi}/2} $$

Multiplions numérateur et dénominateur de la fraction du membre de
droite par $2$ :

$$ \tan 67.5^\circ = \frac{\sqrt{\psi + 1}}{\sqrt{3 - \psi}} $$

Exprimons la fraction de racines carrées comme la racine carrée d’une
fraction :

$$ \tan 67.5^\circ = \sqrt{\frac{\psi + 1}{3 - \psi}} $$

Remplaçons le nombre d’argent par sa valeur :

$$ \tan 67.5^\circ = \sqrt{\frac{1 + 1 + \sqrt{2}}{3 - (1 - \sqrt{2})}} $$

Il vient :

$$ \tan 67.5^\circ = \sqrt{\frac{1 + 1 + \sqrt{2}}{3 - 1 + \sqrt{2}}} $$

puis :

$$ \tan 67.5^\circ = \sqrt{\frac{2 + \sqrt{2}}{2 - \sqrt{2}}} $$

Multiplions numérateur et dénominateur de la fraction du membre de
droite par $2 + \sqrt{2}$ :

$$ \tan 67.5^\circ = \sqrt{\frac{(2 + \sqrt{2})^2}{(2 - \sqrt{2})(2 + \sqrt{2})}} $$

Utilisons la formule du binôme conjugué :

$$ \tan 67.5^\circ = \sqrt{\frac{(2 + \sqrt{2})^2}{4 - 2}} $$

ou encore :

$$ \tan 67.5^\circ = \sqrt{\frac{(2 + \sqrt{2})^2}{2}} $$

Exprimons la racine carrée de la fraction comme une fraction de racines
carrées :

$$ \tan 67.5^\circ = \frac{\sqrt{(2 + \sqrt{2})^2}}{\sqrt{2}} $$

La racine carrée d’un carrée étant la fonction identité, on a :

$$ \tan 67.5^\circ = \frac{2 + \sqrt{2}}{\sqrt{2}} $$

c’est-à-dire :

$$ \tan 67.5^\circ = \sqrt{2} + 1 $$

qui n’est rien d’autre que le nombre d’argent :

$$ \tan 67.5^\circ = \psi $$

*** Tangente de 22.5°

On a :

$$ \tan 22.5^\circ = \unsur{\tan 67.5^\circ} = \unsur{\psi} $$

Par définition du nombre d’argent, on a $1/\psi = \psi -2$ et :

$$ \tan 22.5^\circ = \psi - 2 $$

* Tableau récapitulatif des résultat trigonométriques

Notre tableau récapitulatif des valeurs particulières des fonctions
trigonométriques s’agrandit :

| Radians      | Degrés       | sin                 | cos                 | tan                     |
|--------------+--------------+---------------------+---------------------+-------------------------|
| $0$          | $0$          | $0$                 | $1$                 | $0$                     |
| $\pi/10$     | $18^\circ$   | $(\phi - 1)/2$      | $\sqrt{\phi + 2}/2$ | $1/\sqrt{4 \ \phi + 3}$ |
| $\pi/8$      | $22,5^\circ$ | $\sqrt{3 - \psi}/2$ | $\sqrt{\psi + 1}/2$ | $\psi - 2$              |
| $\pi/6$      | $30^\circ$   | $1/2$               | $\sqrt{3}/2$        | $\sqrt{3}/3$            |
| $\pi/5$      | $36^\circ$   | $\sqrt{3 - \phi}/2$ | $\phi/2$            | $\sqrt{7 - 4 \ \phi}$   |
| $\pi/4$      | $45^\circ$   | $\sqrt{2}/2$        | $\sqrt{2}/2$        | $1$                     |
| $3 \ \pi/10$ | $54^\circ$   | $\phi/2$            | $\sqrt{3 - \phi}/2$ | $1/\sqrt{7 - 4 \ \phi}$ |
| $\pi/3$      | $60^\circ$   | $\sqrt{3}/2$        | $1/2$               | $\sqrt{3}$              |
| $3 \ \pi/8$  | $67,5^\circ$ | $\sqrt{\psi + 1}/2$ | $\sqrt{3 - \psi}/2$ | $\psi$                  |
| $2 \ \pi/5$  | $72^\circ$   | $\sqrt{\phi + 2}/2$ | $(\phi - 1)/2$      | $\sqrt{4 \ \phi + 3}$   |
| $\pi/2$      | $90^\circ$   | $1$                 | $0$                 | $\infty$                |
