
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Trigonometrie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Définitions

#+TOC: headlines 1 local

** Introduction

Soit le triangle rectangle :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/triangle-rectangle.svg]]

On définit la fonction trigonométrique du sinus, notée $\sin$, par :

$$ \sin(\alpha) = b/c $$

On définit la fonction trigonométrique du cosinus, notée $\cos$, par :

$$ \cos(\alpha) = a/c $$

On définit la fonction trigonométrique de la tangente, notée $\tan$, par :

$$ \tan(\alpha) = b/a $$

On a aussi les rapports inversés, cosécante, sécante et cotangente :

$$ \csc(\alpha) = c/b $$

$$ \sec(\alpha) = c/a $$

$$ \cot(\alpha) = a/b $$

** Notations

On note :

$$ \sin \alpha = \sin(\alpha) $$

$$ \cos \alpha = \cos(\alpha) $$

$$ \tan \alpha = \tan(\alpha) $$

$$ \csc \alpha = \csc(\alpha) $$

$$ \sec \alpha = \sec(\alpha) $$

$$ \cot \alpha = \cot(\alpha) $$

*** Carrés

L’usage veut également que :

$$ \sin^2 \alpha = (\sin \alpha)^2 $$

$$ \cos^2 \alpha = (\cos \alpha)^2 $$

$$ \tan^2 \alpha = (\tan \alpha)^2 $$

et ainsi de suite, mais j’évite autant que possible cette notation
dans cet ouvrage, car elle n’est pas cohérente avec la notation
générale des fonctions qui veut que :

$$ f^2(x) = (f \circ f)(x) \ne [f(x)]^2 = f(x) \cdot f(x) $$

** Corollaires

En multipliant la définition du sinus par $c$, on obtient :

$$ b = c \ \sin \alpha $$

En multipliant la définition du cosinus par $c$, on obtient :

$$ a = c \ \cos \alpha $$

* Relations fondamentales

#+TOC: headlines 1 local

** Sinus et cosinus

Le théorème de Pythagore dans notre triangle rectangle nous donne :

$$ a^2 + b^2 = c^2 $$

Mais comme :

$$ a = c \ \cos \alpha $$

$$ b = c \ \sin \alpha $$

la première relation devient :

$$ c^2 \ (\cos \alpha)^2 + c^2 \ (\sin \alpha)^2 = c^2 $$

On peut mettre $c^2$ en évidence :

$$ c^2 \ \left[(\cos \alpha)^2 + (\sin \alpha)^2\right] = c^2 $$

puis diviser par $c^2$ les deux membres, ce qui nous donne la relation
fondamentale entre sinus et cosinus :

$$ (\cos \alpha)^2 + (\sin \alpha)^2 = 1 $$

** Tangente

On a :

$$ \tan \alpha
= \frac{b}{a}
= \frac{b}{c} \cdot \frac{c}{a}
= \frac{b/c}{a/c} $$

Par définition des sinus et cosinus, on a donc :

$$ \tan \alpha = \frac{\sin \alpha}{\cos \alpha} $$

* Cercle trigonométrique

#+attr_html: :width 800px
#+attr_latex: :width 800px
[[file:../include/tikz/cercle-trigonometrique.svg]]

* Loi des sinus

Soit un triangle quelconque. On peut toujours le décomposer en deux
triangles rectangles comme suit :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/loi-des-sinus.svg]]

Dans le triangle rectangle de gauche, nous avons :

$$ h = a \ \sin \gamma $$

Dans le triangle rectangle de droite, nous avons :

$$ h = c \ \sin \alpha $$

On en déduit que :

$$ a \ \sin \gamma = c \ \sin \alpha $$

c’est-à-dire :

$$ \frac{a}{\sin \alpha} = \frac{c}{\sin \gamma} $$

On peut aussi tracer la hauteur perpendiculaire au côté $c$ et suivre un
raisonnement similaire, qui nous donne :

$$ a \ \sin \beta = b \ \sin \alpha $$

c’est-à-dire :

$$ \frac{a}{\sin \alpha} = \frac{b}{\sin \beta} $$

On a donc finalement la loi des sinus qui englobe les trois côtés :

$$ \frac{a}{\sin \alpha} = \frac{b}{\sin \beta} = \frac{c}{\sin \gamma} $$

* Loi des cosinus

Soit un triangle quelconque. On peut toujours le décomposer en deux
triangles rectangles comme suit :

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/loi-des-cosinus.svg]]

Dans le triangle rectangle de gauche, nous avons :

\begin{Eqts}
e = a \cos \gamma \\
h = a \sin \gamma
\end{Eqts}

Appliquons à présent le théorème de Pythagore au triangle rectangle
de droite :

$$ c^2 = h^2 + (b - e)^2 $$

En tenant compte des relations trigonométriques, cette équation
devient :

\begin{align*}
c^2
&= a^2 \ (\sin \gamma)^2 + (b - a \ \cos \gamma)^2 \\
&= a^2 \ (\sin \gamma)^2 + b^2 - 2 \ a \ b \ \cos \gamma + a^2 \ (\cos \gamma)^2 \\
&= a^2 \left[(\sin \gamma)^2 + (\cos \gamma)^2 \right] + b^2 - 2 \ \ a \ b \cos \gamma \\
\end{align*}

Mais comme la somme entre crochets vaut toujours 1, on a finalement :

$$ c^2 = a^2 + b^2 - 2 \ a \ b \ \cos \gamma $$

Un raisonnement similaire nous donne le même résultat lorsque l’angle
$\gamma$ est obtus.

On peut voir ce résultat comme une généralisation du théorème de
Pythagore à un triangle quelconque.

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/triangle-et-angles.svg]]

Un raisonnement similaire nous donne un résultat analogue pour les
autres côtés :

$$ a^2 = b^2 + c^2 - 2 \ b \ c \ \cos \alpha $$

$$ b^2 = a^2 + c^2 - 2 \ a \ c \ \cos \beta $$

* Somme de deux angles

#+attr_html: :width 500px
#+attr_latex: :width 500px
[[file:../include/tikz/sin-cos-somme-de-deux-angles.svg]]
