
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Vecteurs de dimension finie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Produit cartésien d’un corps $\corps$

Soit un corps $\corps$. Nous considérons dans ce chapitre les n-tuples
appartenant à $\corps^n$. On nomme vecteur un élément de $\corps^n$.

En pratique, le corps $\corps$ sera le plus souvent $\setR$ ou $\setC$.

** Scalaire

Par opposition aux vecteurs de $\corps^n$, un élément du corps $\corps$
est appelé un scalaire.

* Vecteur colonne

On peut représenter un n-tuple $(u_1,u_2,...,u_n) \in \corps^n$
sous la forme d’une colonne de $u_i$ :

$$ u = \begin{bmatrix}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{bmatrix} $$

On appelle vecteur colonne une telle représentation.

Dans la suite de cet ouvrage, les vecteurs de $\corps^n$ seront des
vecteurs colonnes par défaut.

** Composantes

On peut aussi définir un vecteur colonne $u\in\corps^n$ en termes de
composantes :

$$ u = (u_i)_{i \in \{1,2,...,n\}} $$

Lorsque le nombre de lignes est évident d’après le contexte, on note
plus simplement :

$$u = (u_i)_i$$

ou encore :

$$u = [u_i]_i$$

On dit aussi que $u_i$ est la $i^{ème}$ composante de $u$, et on
le note :

$$u_i = \composante_i u$$

* Vecteur ligne

On peut représenter un n-tuple $(u_1,u_2,...,u_n) \in \corps^n$
sous la forme d’une ligne de $u_i$ :

$$u = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

On appelle vecteur ligne une telle représentation.

* Transposition

#+TOC: headlines 1 local

** Colonne vers ligne

Soit le vecteur colonne :

$$ u = \begin{bmatrix}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{bmatrix} $$

On appelle transposé de $u$, et on le note :

$$ u^T $$

le vecteur ligne défini par les mêmes composantes :

$$u^T = \begin{bmatrix}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{bmatrix}^T = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

** Ligne vers colonne

Soit le vecteur ligne :

$$u = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

On appelle transposé de $u$, et on le note :

$$ u^T $$

le vecteur colonne défini par les mêmes composantes :

$$ u^T = [u_1 \ \ u_2 \ \ldots \ \ u_n]^T = \begin{bmatrix}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{bmatrix} $$

** Équivalence

On voit qu’il existe un équivalence entre le vecteur colonne :

$$ u = \begin{bmatrix}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{bmatrix} $$

et le vecteur ligne correspondant :

$$u^T = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

* Vecteur nul

Le vecteur nul $0_n \in \corps^n$ est défini par :

$$ 0_n = (0)_i = \begin{bmatrix}
0 \\
0 \\
\vdots \\
0
\end{bmatrix} $$

Lorsqu’on ne risque pas de confondre le vecteur nul de $\corps^n$
avec l’élément nul de $\corps$, on peut le noter plus simplement :

$$ 0 = (0)_i = \begin{bmatrix}
0 \\
0 \\
\vdots \\
0
\end{bmatrix} $$

* Opérations

#+TOC: headlines 1 local

** Addition induite

Soit deux vecteurs colonne $u$ et $v$ :

$$ u = (u_i)_i $$

$$ v = (v_i)_i $$

on a :

$$ u + v = \begin{bmatrix}
u_1 + v_1 \\
u_2 + v_2 \\
\vdots \\
u_n + v_n
\end{bmatrix} $$

c’est-à-dire :

$$ u + v = (u_i + v_i)_i $$

L’addition entre deux vecteurs est donc induite par l’addition du
corps $\corps$.

** Multiplication par un scalaire

Soit le vecteur :

$$ u = (u_i)_i $$

Pour rester cohérent avec le produit sur les scalaires, on note :

$$ 2 \ u = u + u $$

On a donc :

$$ 2 \ u = \begin{bmatrix}
u_1 + u_1 \\
u_2 + u_2 \\
\vdots \\
u_n + u_n
\end{bmatrix}
= \begin{bmatrix}
2 \ u_1 \\
2 \ u_2 \\
\vdots \\
2 \ u_n
\end{bmatrix} $$

On généralise cette notation pour tout $\alpha \in \corps$ :

$$ \alpha \cdot u = \begin{bmatrix}
\alpha \cdot u_1 \\
\alpha \cdot u_2 \\
\vdots \\
\alpha \cdot u_n
\end{bmatrix} $$

c’est-à-dire :

$$ \alpha \cdot u = (\alpha \cdot u_i)_i $$

L’élément $\alpha$ effectue donc une mise à échelle du vecteur,
d’où le nom de scalaire.

** Propriétés
:PROPERTIES:
:CUSTOM_ID: heading:proprietes_operations_sur_vecteurs_de_dimension_finie
:END:

Soit les vecteurs colonnes $u,v,w \in \corps^n$, les scalaires $\alpha,
\beta \in \corps$, le vecteur nul $0 \in \corps^n$ et le scalaire neutre
pour la multiplication $1 \in \corps$. On a :

\begin{align*}
0 + u &= u \\
u + (-u) &= 0 \\
1 \cdot u &= 1 \\
u + v &= v + u \\
u + (v + w) &= (u + v) + w \\
(\alpha \cdot \beta) \cdot u &= \alpha \cdot (\beta \cdot u) \\
(\alpha + \beta) \cdot u &= \alpha \cdot u + \beta \cdot u \\
\alpha \cdot (u + v) &= \alpha \cdot u + \alpha \cdot v
\end{align*}

On voit que l'addition induite sur $\corps^n$ par l'addition de $\corps$
transforme $\corps^n$ en groupe commutatif.

* Vecteurs canoniques

Soit $i \in \{1,2,...,n\}$. On note $\canonique_i$ le vecteur colonne
de $\corps^n$ ayant un $1$ en $i^{ème}$ position et des $0$ partout
ailleurs :

$$ \canonique_i
= ( \indicatrice_{ij} )_j
= \begin{bmatrix}
\vdots \\
0 \\
1 \\
0 \\
\vdots
\end{bmatrix} $$

On a donc la suite de vecteurs :

\begin{align*}
\canonique_1 &= [1 \ 0 \ \ldots \ 0]^T \\
\canonique_2 &= [0 \ 1 \ \ldots \ 0]^T \\
\vdots \\
\canonique_n &= [0 \ \ldots \ 0 \ 1]^T
\end{align*}

On nomme base canonique de $\corps^n$ la suite
$(\canonique_1,\canonique_2,...,\canonique_n)$.

** Composantes et base canonique

On a, pour tout vecteur $u\in\corps^n$ défini par :

$$ u = (u_i)_i $$

l’identité le reliant aux vecteurs de la base canonique :

$$u = \sum_{i = 1}^n u_i \cdot \canonique_i$$
