
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Vecteurs de dimension finie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Vecteur ligne

On peut représenter un n-tuple $(x_1,x_2,...,x_n) \in \corps^n$
sous la forme d’une ligne de $x_i$ :

$$x = [x_1 \ x_2 \ \ldots \ x_n]$$

On appelle vecteur ligne une telle représentation.

* Vecteur colonne

On peut représenter un n-tuple $(x_1,x_2,...,x_n) \in \corps^n$
sous la forme d’une colonne de $x_i$ :

#+BEGIN_CENTER
$$ x = \begin{Matrix}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{Matrix} $$
#+END_CENTER

On appelle vecteur colonne une telle représentation.

** Composantes

On peut aussi définir un vecteur colonne en termes de composantes :

$$x = (x_i)_i$$

On dit aussi que $x_i$ est la $i^{ème}$ composante de $x$, et on
le note :

$$x_i = \composante_i x$$

* Scalaire

Par opposition aux vecteurs de $\corps^n$, un élément de $\corps$
est appelé scalaire.

* Vecteurs canoniques de $\corps^n$

Soit $\corps \in \{ \setR, \setC \}$. On note $\canonique_i$ l'élément
de $\corps^n$ ayant un $1$ en $i^{ème}$ position et des $0$ partout
ailleurs. On a donc :

\begin{align*}
\canonique_1 &= (1,0,...,0) \\
\canonique_2 &= (0,1,0,...,0) \\
&\vdots& \\
\canonique_n &= (0,...,0,1)
\end{align*}

On a alors, pour tout $x = (x_1,...,x_n) \in \corps^n$ :

$$x = \sum_{i = 1}^n x_i \cdot \canonique_i$$
