
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat : Vecteurs de dimension finie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index mathématique]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/latex/latex.org"

* Produit cartésien d’un corps $\corps$

Soit un corps $\corps$. Nous considérons dans ce chapitre les n-tuples
appartenant à $\corps^n$. On nomme vecteur un élément de $\corps^n$.

En pratique, le corps $\corps$ sera le plus souvent $\setR$ ou $\setC$.

** Scalaire

Par opposition aux vecteurs de $\corps^n$, un élément du corps $\corps$
est appelé un scalaire.

* Vecteur ligne

On peut représenter un n-tuple $(u_1,u_2,...,u_n) \in \corps^n$
sous la forme d’une ligne de $u_i$ :

$$u = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

On appelle vecteur ligne une telle représentation.

* Vecteur colonne

On peut représenter un n-tuple $(u_1,u_2,...,u_n) \in \corps^n$
sous la forme d’une colonne de $u_i$ :

$$ u = \begin{Matrix}{c}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{Matrix} $$

On appelle vecteur colonne une telle représentation.

** Composantes

On peut aussi définir un vecteur colonne en termes de composantes :

$$u = (u_i)_i$$

ou encore :

$$u = [u_i]_i$$

On dit aussi que $u_i$ est la $i^{ème}$ composante de $u$, et on
le note :

$$u_i = \composante_i u$$

* Équivalence

On voit qu’il existe un équivalence entre le vecteur ligne

$$u = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

et le vecteur colonne :

$$ u = \begin{Matrix}{c}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{Matrix} $$

* Transposition

** Ligne vers colonne

Soit le vecteur ligne :

$$u = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

On appelle transposé de $u$, et on le note :

$$ u^T $$

le vecteur colonne défini par les mêmes composantes :

$$ u^T = \begin{Matrix}{c}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{Matrix} $$

** Colonne vers ligne

Soit le vecteur colonne :

$$ u = \begin{Matrix}{c}
u_1 \\
u_2 \\
\vdots \\
u_n
\end{Matrix} $$

On appelle transposé de $u$, et on le note :

$$ u^T $$

le vecteur ligne défini par les mêmes composantes :

$$u^T = [u_1 \ \ u_2 \ \ldots \ \ u_n]$$

* Opérations

** Addition induite

Soit deux vecteurs colonne $u$ et $v$ :

$$ u = (u_i)_i $$

$$ v = (v_i)_i $$

on a :

$$ u + v = \begin{Matrix}{c}
u_1 + v_1 \\
u_2 + v_2 \\
\vdots \\
u_n + v_n
\end{Matrix} $$

c’est-à-dire :

$$ u + v = (u_i + v_i)_i $$

L’addition entre deux vecteurs est donc induite par l’addition du
corps $\corps$.

** Multiplication par un scalaire

Soit le vecteur :

$$ u = (u_i)_i $$

Pour rester cohérent avec le produit sur les scalaires, on note :

$$ 2 \ u = u + u $$

On a donc :

$$ 2 \ u = \begin{Matrix}{c}
u_1 + u_1 \\
u_2 + u_2 \\
\vdots \\
u_n + u_n
\end{Matrix}
= \begin{Matrix}{c}
2 \ u_1 \\
2 \ u_2 \\
\vdots \\
2 \ u_n
\end{Matrix} $$

On généralise cette notation pour tout $\alpha \in \corps$ :

$$ \alpha \cdot u = \begin{Matrix}{c}
\alpha \cdot u_1 \\
\alpha \cdot u_2 \\
\vdots \\
\alpha \cdot u_n
\end{Matrix} $$

c’est-à-dire :

$$ \alpha \cdot u = (\alpha \cdot u_i)_i $$

L’élément $\alpha$ effectue donc une mise à échelle du vecteur,
d’où le nom de scalaire.

* Vecteurs canoniques

On note $\canonique_i$ l'élément de $\corps^n$ ayant un $1$ en
$i^{ème}$ position et des $0$ partout ailleurs. On a donc :

\begin{align*}
\canonique_1 &= (1,0,...,0) \\
\canonique_2 &= (0,1,0,...,0) \\
&\vdots& \\
\canonique_n &= (0,...,0,1)
\end{align*}

ou, exprimés comme des vecteurs colonnes :

$$ \canonique_i = (\indicatrice_{ij})_j $$

On nomme base canonique de $\corps^n$ la suite
$(\canonique_1,\canonique_2,...,\canonique_n)$.

** Composantes et base canonique

On a, pour tout vecteur $u\in\corps^n$ défini par :

$$ u = (u_i)_i $$

l’identité le reliant aux vecteurs de la base canonique :

$$u = \sum_{i = 1}^n u_i \cdot \canonique_i$$
