
#+STARTUP: showall

#+TITLE: Eclats de vers : Litera : Anthologie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+../include: "../../include/navigan-1.org"

#+TOC: headlines 2

* Théodore de Banville

** L'air

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans l'Air s’en vont les ailes,
    Par le vent caressées ;
    Mes errantes pensées
    S’envolent avec elles.

    Aux cieux pleins d'étincelles,
    Vers la nue élancées,
    Dans l'Air s’en vont les ailes
    Par le vent caressées.

    Vers des terres nouvelles,
    Sur les rayons bercées,
    Vous fuyez, dispersées,
    Ô blanches colombelles ;
    Dans l'Air s’en vont les ailes !
#+END_VERSE
#+END_CENTER

** La lune

#+BEGIN_CENTER
#+BEGIN_VERSE
    Avec ses caprices, la Lune
    Est comme une frivole amante ;
    Elle sourit et se lamente,
    Et vous fuit et vous importune.

    La nuit, suivez-la sur la dune,
    Elle vous raille et vous tourmente ;
    Avec ses caprices, la Lune
    Est comme une frivole amante.

    Et souvent elle se met une
    Nuée en manière de mante ;
    Elle est absurde, elle est charmante ;
    Il faut adorer sans rancune,
    Avec ses caprices, la Lune.
#+END_VERSE
#+END_CENTER

** Les métaux

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les Métaux, les divins Métaux
    Que toujours l’homme voit en rêve,
    Ornent la couronne ou le glaive
    De tous les Péchés capitaux.

    L'Orgueil jette sur ses manteaux
    Pour cette vie, ô Dieu ! si brève,
    Les Métaux, les divins Métaux
    Que toujours l’homme voit en rêve.

    L’or gémit sous les vils râteaux
    Que toujours le banquier soulève,
    Et pour parer les filles d'Ève
    Nous tourmentons de nos marteaux
    Les Métaux, les divins Métaux.
#+END_VERSE
#+END_CENTER

** Les pierreries

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les flamboyantes Pierreries
    Qui parent les glaives des rois
    Et les mors de leurs palefrois,
    Brillent dans les rouges tueries.

    La foule, amante des féeries,
    Admire, en ses humbles effrois,
    Les flamboyantes Pierreries
    Qui parent les glaives des rois.

    Et, dans les louanges nourries,
    Les Princesses aux regards froids
    Sèment sur leurs corsages droits
    Et sur leurs jupes d’or fleuries
    Les flamboyantes Pierreries.
#+END_VERSE
#+END_CENTER

* Charles Baudelaire

** Le balcon

#+BEGIN_CENTER
#+BEGIN_VERSE
    Mère des souvenirs, maîtresse des maîtresses,
    Ô toi, tous mes plaisirs ! ô toi, tous mes devoirs !
    Tu te rappelleras la beauté des caresses,
    La douceur du foyer et le charme des soirs,
    Mère des souvenirs, maîtresse des maîtresses !

    Les soirs illuminés par l’ardeur du charbon,
    Et les soirs au balcon, voilés de vapeurs roses.
    Que ton sein m'était doux ! que ton coeur m'était bon !
    Nous avons dit souvent d’impérissables choses
    Les soirs illuminés par l’ardeur du charbon.

    Que les soleils sont beaux dans les chaudes soirées !
    Que l’espace est profond ! que le coeur est puissant !
    En me penchant vers toi, reine des adorées,
    Je croyais respirer le parfum de ton sang.
    Que les soleils sont beaux dans les chaudes soirées !

    La nuit s'épaississait ainsi qu’une cloison,
    Et mes yeux dans le noir devinaient tes prunelles,
    Et je buvais ton souffle, ô douceur ! ô poison !
    Et tes pieds s’endormaient dans mes mains fraternelles.
    La nuit s'épaississait ainsi qu’une cloison.

    Je sais l’art d'évoquer les minutes heureuses,
    Et revis mon passé blotti dans tes genoux.
    Car à quoi bon chercher tes beautés langoureuses
    Ailleurs qu’en ton cher corps et qu’en ton coeur si doux ?
    Je sais l’art d'évoquer les minutes heureuses !

    Ces serments, ces parfums, ces baisers infinis,
    Renaîtront-il d’un gouffre interdit à nos sondes,
    Comme montent au ciel les soleils rajeunis
    Après s'être lavés au fond des mers profondes ?
    - Ô serments ! ô parfums ! ô baisers infinis !
#+END_VERSE
#+END_CENTER

** Les chats

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les amoureux fervents et les savants austères
    Aiment également, dans leur mûre saison,
    Les chats puissants et doux, orgueil de la maison,
    Qui comme eux sont frileux et comme eux sédentaires.

    Amis de la science et de la volupté
    Ils cherchent le silence et l’horreur des ténèbres ;
    L'Erèbe les eût pris pour ses coursiers funèbres,
    S’ils pouvaient au servage incliner leur fierté.

    Ils prennent en songeant les nobles attitudes
    Des grands sphinx allongés au fond des solitudes,
    Qui semblent s’endormir dans un rêve sans fin ;

    Leurs reins féconds sont pleins d'étincelles magiques,
    Et des parcelles d’or, ainsi qu’un sable fin,
    Etoilent vaguement leurs prunelles mystiques.
#+END_VERSE
#+END_CENTER

** Harmonie du soir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Voici venir les temps où vibrant sur sa tige
    Chaque fleur s'évapore ainsi qu’un encensoir ;
    Les sons et les parfums tournent dans l’air du soir ;
    Valse mélancolique et langoureux vertige !

    Chaque fleur s'évapore ainsi qu’un encensoir ;
    Le violon frémit comme un coeur qu’on afflige ;
    Valse mélancolique et langoureux vertige !
    Le ciel est triste et beau comme un grand reposoir.

    Le violon frémit comme un coeur qu’on afflige,
    Un coeur tendre, qui hait le néant vaste et noir !
    Le ciel est triste et beau comme un grand reposoir ;
    Le soleil s’est noyé dans son sang qui se fige.

    Un coeur tendre, qui hait le néant vaste et noir,
    Du passé lumineux recueille tout vestige !
    Le soleil s’est noyé dans son sang qui se fige...
    Ton souvenir en moi luit comme un ostensoir !
#+END_VERSE
#+END_CENTER

** Lesbos

#+BEGIN_CENTER
#+BEGIN_VERSE
    Mère des jeux latins et des voluptés grecques,
    Lesbos, où les baisers, languissants ou joyeux,
    Chauds comme les soleils, frais comme les pastèques,
    Font l’ornement des nuits et des jours glorieux,
    Mère des jeux latins et des voluptés grecques,

    Lesbos, où les baisers sont comme les cascades
    Qui se jettent sans peur dans les gouffres sans fonds
    Et courent , sanglotant et gloussant par saccades,
    Orageux et secrets, fourmillants et profonds ;
    Lesbos, où les baisers sont comme les cascades !

    Lesbos, où les Phrynés l’une l’autre s’attirent,
    Où jamais un soupir ne resta sans écho,
    A l'égal de Paphos les étoiles t’admirent,
    Et Vénus à bon droit peut jalouser Sapho !
    Lesbos, où les Phrynés l’une l’autre s’attirent,

    Lesbos, terre des nuits chaudes et langoureuses,
    Qui font qu'à leurs miroirs, stérile volupté !
    Les filles aux yeux creux, de leur corps amoureuses,
    Caressent les fruits mûrs de leur nubilité ;
    Lesbos, terre des nuits chaudes et langoureuses,

    Laisse du vieux Platon se froncer l’oeil austère ;
    Tu tires ton pardon de l’excès des baisers,
    Reine du doux empire, aimable et noble terre,
    Et des raffinements toujours inépuisés.
    Laisse du vieux Platon se froncer l’oeil austère.

    Tu tires ton pardon de l'éternel martyre,
    Infligé sans relâche aux coeurs ambitieux,
    Qu’attire loin de nous le radieux sourire
    Entrevu vaguement au bord des autres cieux !
    Tu tires ton pardon de l'éternel martyre !

    Qui des Dieux osera, Lesbos, être ton juge
    Et condamner ton front pâli dans les travaux,
    Si ses balances d’or n’ont pesé le déluge
    De larmes qu'à la mer ont versé tes ruisseaux ?
    Qui des Dieux osera, Lesbos, être ton juge ?

    Que nous veulent les lois du juste et de l’injuste ?
    Vierges au coeur sublime, honneur de l'Archipel,
    Votre religion comme une autre est auguste,
    Et l’amour se rira de l'Enfer et du Ciel !
    Que nous veulent les lois du juste et de l’injuste ?

    Car Lesbos entre tous m’a choisi sur la terre
    Pour chanter le secret de ses vierges en fleurs,
    Et je fus dès l’enfance admis au noir mystère
    Des rires effrénés mêlés aux sombres pleurs ;
    Car Lesbos entre tous m’a choisi sur la terre.

    Et depuis lors je veille au sommet de Leucate,
    Comme une sentinelle à l’oeil perçant et sûr,
    Qui guette nuit et jour brick, tartane ou frégate,
    Dont les formes au loin frissonnent dans l’azur ;
    Et depuis lors je veille au sommet de Leucate,

    Pour savoir si la mer est indulgente et bonne,
    Et parmi les sanglots dont le roc retentit
    Un soir ramènera vers Lesbos, qui pardonne,
    Le cadavre adoré de Sapho qui partit
    Pour savoir si la mer est indulgente et bonne !

    De la mâle Sapho, l’amante et le poète,
    Plus belle que Vénus par ses mornes pâleurs !
    - L’oeil d’azur est vaincu par l’oeil noir que tachète
    Le cercle ténébreux tracé par les douleurs
    De la mâle Sapho, l’amante et le poète !

    - Plus belle que Vénus se dressant sur le monde
    Et versant les trésors de sa sérénité
    Et le rayonnement de sa jeunesse blonde
    Sur le vieil Océan de sa fille enchanté ;
    Plus belle que Vénus se dressant sur le monde !

    - De Sapho qui mourut le jour de son blasphème,
    Quand, insultant le rite et le culte inventé,
    Elle fit son beau corps la pâture suprême
    D’un brutal dont l’orgueil punit l’impiété
    De celle qui mourut le jour de son blasphème.

    Et c’est depuis ce temps que Lesbos se lamente,
    Et, malgré les honneurs que lui rend l’univers,
    S’enivre chaque nuit du cri de la tourmente
    Que poussent vers les cieux ses rivages déserts.
    Et c’est depuis ce temps que Lesbos se lamente !
#+END_VERSE
#+END_CENTER

** Tristesses de la lune

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ce soir, la lune rêve avec plus de paresse ;
    Ainsi qu’une beauté, sur de nombreux coussins,
    Qui d’une main distraite et légère caresse
    Avant de s’endormir le contour de ses seins,

    Sur le dos satiné des molles avalanches,
    Mourante, elle se livre aux longues pâmoisons,
    Et promène ses yeux sur les visions blanches
    Qui montent dans l’azur comme des floraisons.

    Quand parfois sur ce globe, en sa langueur oisive,
    Elle laisse filer une larme furtive,
    Un poète pieux, ennemi du sommeil,

    Dans le creux de sa main prend cette larme pâle,
    Aux reflets irisés comme un fragment d’opale,
    Et la met dans son coeur loin des yeux du soleil.
#+END_VERSE
#+END_CENTER

* Pierre Corneille

** A la Marquise

#+BEGIN_CENTER
#+BEGIN_VERSE
    Marquise, si mon visage
    A quelques traits un peu vieux,
    Souvenez-vous qu'à mon âge
    Vous ne vaudrez guère mieux.

    Le temps aux plus belles choses
    Se plaît à faire un affront,
    Et saura faner vos roses
    Comme il a ridé mon front.

    Le même cours des planètes
    Règle nos jours et nos nuits
    On m’a vu ce que vous êtes;
    Vous serez ce que je suis.

    Cependant j’ai quelques charmes
    Qui sont assez éclatants
    Pour n’avoir pas trop d’alarmes
    De ces ravages du temps.

    Vous en avez qu’on adore;
    Mais ceux que vous méprisez
    Pourraient bien durer encore
    Quand ceux-là seront usés.

    Ils pourront sauver la gloire
    Des yeux qui me semblent doux,
    Et dans mille ans faire croire
    Ce qu’il me plaira de vous.

    Chez cette race nouvelle,
    Où j’aurai quelque crédit,
    Vous ne passerez pour belle
    Qu’autant que je l’aurai dit.

    Pensez-y, belle marquise.
    Quoiqu’un grison fasse effroi,
    Il vaut bien qu’on le courtise
    Quand il est fait comme moi.
#+END_VERSE
#+END_CENTER

** Chanson

#+BEGIN_CENTER
#+BEGIN_VERSE
    Si je perds bien des maîtresses,
    J’en fais encor plus souvent,
    Et mes voeux et mes promesses
    Ne sont que feintes caresses,
    Et mes voeux et mes promesses
    Ne sont jamais que du vent.

    Quand je vois un beau visage,
    Soudain je me fais de feu,
    Mais longtemps lui faire hommage,
    Ce n’est pas bien mon usage,
    Mais longtemps lui faire hommage,
    Ce n’est pas bien là mon jeu.

    J’entre bien en complaisance
    Tant que dure une heure ou deux,
    Mais en perdant sa présence
    Adieu toute souvenance,
    Mais en perdant sa présence
    Adieu soudain tous mes feux (...)
#+END_VERSE
#+END_CENTER

* Marceline Desbordes-Valmore

** Fleur d'enfance

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’haleine d’une fleur sauvage,
    En passant tout près de mon coeur,
    Vient de m’emporter au rivage,
    Où naguère aussi j'étais fleur :
    Comme au fond d’un prisme où tout change,
    Où tout se relève à mes yeux,
    Je vois un enfant aux yeux d’ange :
    C'était mon petit amoureux !

    Parfum de sa neuvième année,
    Je respire encor ton pouvoir ;
    Fleur à mon enfance donnée,
    Je t’aime ! comme son miroir.
    Nos jours ont séparé leur trame,
    Mais tu me rappelles ses yeux ;
    J’y regardais flotter mon âme :
    C'était mon petit amoureux !

    De blonds cheveux en auréole,
    Un regard tout voilé d’azur,
    Une brève et tendre parole,
    Voilà son portrait jeune et pur :
    Au seuil de ma pauvre chaumière
    Quand il se sauvait de ses jeux,
    Que ma petite âme était fière ;
    C'était mon petit amoureux !

    Cette ombre qui joue à ma rive
    Et se rapproche au moindre bruit,
    Me suit, comme un filet d’eau vive,
    A travers mon sentier détruit :
    Chaste, elle me laisse autour d’elle
    Enlacer un chant douloureux ;
    Hélas ! ma seule ombre fidèle,
    C’est vous ! mon petit amoureux !

    Femme ! à qui ses lèvres timides
    Ont dit ce qu’il semblait penser,
    Au temps où nos lèvres humides
    Se rencontraient sans se presser ;
    Vous ! qui fûtes son doux Messie,
    L’avez-vous rendu bien heureux ?
    Du coeur je vous en remercie :
    C'était mon petit amoureux !
#+END_VERSE
#+END_CENTER

** Hiver

#+BEGIN_CENTER
#+BEGIN_VERSE
    Non, ce n’est pas l'été, dans le jardin qui brille,
    Où tu t’aimes de vivre, où tu ris, coeur d’enfant !
    Où tu vas demander à quelque jeune fille,
    Son bouquet frais comme elle et que rien ne défend.

    Ce n’est pas aux feux blancs de l’aube qui t'éveille,
    Qui rouvre à ta pensée un lumineux chemin,
    Quand tu crois, aux parfums retrouvés de la veille,
    Saisir déjà l’objet qui t’a dit : " A demain ! "

    Non ! ce n’est pas le jour, sous le soleil d’où tombent
    Les roses, les senteurs, les splendides clartés,
    Les terrestres amours qui naissent et succombent,
    Que tu dois me rêver pleurante à tes côtés :

    C’est l’hiver, c’est le soir, près d’un feu dont la flamme
    Eclaire le passé dans le fond de ton âme.
    Au milieu du sommeil qui plane autour de toi,
    Une forme s'élève ; elle est pâle ; c’est moi ;

    C’est moi qui viens poser mon nom sur ta pensée,
    Sur ton coeur étonné de me revoir encor ;
    Triste, comme on est triste, a-t-on dit, dans la mort,
    A se voir poursuivi par quelque âme blessée,

    Vous chuchotant tout bas ce qu’elle a dû souffrir,
    Qui passe et dit : " C’est vous qui m’avez fait mourir ! "
#+END_VERSE
#+END_CENTER

** La jeune châtelaine

#+BEGIN_CENTER
#+BEGIN_VERSE
    « Je vous défends, châtelaine,
    De courir seule au grand bois. »
    M’y voici, tout hors d’haleine,
    Et pour la seconde fois.
    J’aurais manqué de courage
    Dans ce long sentier perdu ;
    Mais que j’en aime l’ombrage !
    Mon seigneur l’a défendu.

    « Je vous défends, belle mie.
    Ce rondeau vif et moqueur. »
    Je n'étais pas endormie
    Que je le savais par coeur.
    Depuis ce jour je le chante ;
    Pas un refrain n’est perdu :
    Dieu ! que ce rondeau m’enchante !
    Mon seigneur l’a défendu.

    « Je vous défends sur mon page
    De jamais lever les yeux. »
    Et voilà que son image
    Me suit, m’obsède en tous lieux.
    Je l’entends qui, par mégarde,
    Au bois s’est aussi perdu :
    D’où vient que je le regarde ?
    Mon seigneur l’a défendu.

    Mon seigneur défend encore
    Au pauvre enfant de parler ;
    Et sa voix douce et sonore
    Ne dit plus rien sans trembler.
    Qu’il doit souffrir de se taire !
    Pour causer quel temps perdu !
    Mais, mon page, comment faire ?
    Mon seigneur l’a défendu.
#+END_VERSE
#+END_CENTER

** La lune des fleurs

#+BEGIN_CENTER
#+BEGIN_VERSE
    Douce lune des fleurs, j’ai perdu ma couronne !
    Je ne sais quel orage a passé sur ces bords.
    Des chants de l’espérance il éteint les accords,
    Et dans la nuit qui m’environne,
    Douce lune des fleurs, j’ai perdu ma couronne.

    Jette-moi tes présents, lune mystérieuse,
    De mon front qui pâlit ranime les couleurs ;
    J’ai perdu ma couronne et j’ai trouvé des pleurs ;
    Loin de la foule curieuse,
    Jette-moi tes présents, lune mystérieuse.

    Entrouvre d’un rayon les noires violettes,
    Douces comme les yeux du séduisant amour.
    Tes humides baisers hâteront leur retour.
    Pour cacher mes larmes muettes,
    Entrouvre d’un rayon les noires violettes !
#+END_VERSE
#+END_CENTER

** La sincère

#+BEGIN_CENTER
#+BEGIN_VERSE
    Veux-tu l’acheter ?
    Mon coeur est à vendre.
    Veux-tu l’acheter,
    Sans nous disputer ?

    Dieu l’a fait d’aimant ;
    Tu le feras tendre ;
    Dieu l’a fait d’aimant
    Pour un seul amant !

    Moi, j’en fais le prix ;
    Veux-tu le connaître ?
    Moi, j’en fais le prix ;
    N’en sois pas surpris.

    As-tu tout le tien ?
    Donne ! et sois mon maître.
    As-tu tout le tien,
    Pour payer le mien ?

    S’il n’est plus à toi,
    Je n’ai qu’une envie ;
    S’il n’est plus à toi,
    Tout est dit pour moi.

    Le mien glissera,
    Fermé dans la vie ;
    Le mien glissera,
    Et Dieu seul l’aura !

    Car, pour nos amours,
    La vie est rapide ;
    Car, pour nos amours,
    Elle a peu de jours.

    L'âme doit courir
    Comme une eau limpide ;
    L'âme doit courir,
    Aimer ! et mourir.
#+END_VERSE
#+END_CENTER

** L'entrevue au ruisseau

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’eau nous sépare, écoute bien :
    Si tu fais un pas, tu n’as rien.

    Voici ma plus belle ceinture,
    Elle embaume encor de mes fleurs.
    Prends les parfums et les couleurs,
    Prends tout... je m’en vais sans parure.

    L’eau nous sépare, écoute bien :
    Si tu fais un pas, tu n’as rien.

    Sais-tu pourquoi je viens moi-même
    Jeter mon ruban sur ton sein ?
    C’est que tu parlais d’un larcin,
    Et l’on veut donner quand on aime.

    L’eau nous sépare, écoute bien ;
    Si tu fais un pas, tu n’as rien.

    Adieu ! ta réponse est à craindre,
    Je n’ai pas le temps d'écouter ;
    Mais quand je n’ose m’arrêter,
    N’est-ce donc que toi qu’il faut plaindre ?

    Ce que j’ai dit, retiens-le bien :
    Pour aujourd’hui, je n’ai plus rien !
#+END_VERSE
#+END_CENTER

** Les séparés

#+BEGIN_CENTER
#+BEGIN_VERSE
    N'écris pas. Je suis triste, et je voudrais m'éteindre.
    Les beaux étés sans toi, c’est la nuit sans flambeau.
    J’ai refermé mes bras qui ne peuvent t’atteindre,
    Et frapper à mon coeur, c’est frapper au tombeau.
    N'écris pas !

    N'écris pas. N’apprenons qu'à mourir à nous-mêmes.
    Ne demande qu'à Dieu... qu'à toi, si je t’aimais !
    Au fond de ton absence écouter que tu m’aimes,
    C’est entendre le ciel sans y monter jamais.
    N'écris pas !

    N'écris pas. Je te crains ; j’ai peur de ma mémoire ;
    Elle a gardé ta voix qui m’appelle souvent.
    Ne montre pas l’eau vive à qui ne peut la boire.
    Une chère écriture est un portrait vivant.
    N'écris pas !

    N'écris pas ces doux mots que je n’ose plus lire :
    Il semble que ta voix les répand sur mon coeur ;
    Que je les vois brûler à travers ton sourire ;
    Il semble qu’un baiser les empreint sur mon coeur.
    N'écris pas !
#+END_VERSE
#+END_CENTER

** Ma chambre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ma demeure est haute,
    Donnant sur les cieux ;
    La lune en est l’hôte,
    Pâle et sérieux :
    En bas que l’on sonne,
    Qu’importe aujourd’hui
    Ce n’est plus personne,
    Quand ce n’est plus lui !

    Aux autres cachée,
    Je brode mes fleurs ;
    Sans être fâchée,
    Mon âme est en pleurs ;
    Le ciel bleu sans voiles ,
    Je le vois d’ici ;
    Je vois les étoiles
    Mais l’orage aussi !

    Vis-à-vis la mienne
    Une chaise attend :
    Elle fut la sienne,
    La nôtre un instant ;
    D’un ruban signée,
    Cette chaise est là,
    Toute résignée,
    Comme me voilà !
#+END_VERSE
#+END_CENTER

** Qu'en avez-vous fait ?

#+BEGIN_CENTER
#+BEGIN_VERSE
    Vous aviez mon coeur,
    Moi, j’avais le vôtre :
    Un coeur pour un coeur ;
    Bonheur pour bonheur !

    Le vôtre est rendu,
    Je n’en ai plus d’autre,
    Le vôtre est rendu,
    Le mien est perdu !

    La feuille et la fleur
    Et le fruit lui-même,
    La feuille et la fleur,
    L’encens, la couleur :

    Qu’en avez-vous fait,
    Mon maître suprême ?
    Qu’en avez-vous fait,
    De ce doux bienfait ?

    Comme un pauvre enfant
    Quitté par sa mère,
    Comme un pauvre enfant
    Que rien ne défend,

    Vous me laissez là,
    Dans ma vie amère ;
    Vous me laissez là,
    Et Dieu voit cela !

    Savez-vous qu’un jour
    L’homme est seul au monde ?
    Savez-vous qu’un jour
    Il revoit l’amour ?

    Vous appellerez,
    Sans qu’on vous réponde ;
    Vous appellerez,
    Et vous songerez !...

    Vous viendrez rêvant
    Sonner à ma porte;
    Ami comme avant,
    Vous viendrez rêvant.

    Et l’on vous dira :
    « Personne !... elle est morte. »
    On vous le dira ;
    Mais qui vous plaindra ?
#+END_VERSE
#+END_CENTER

** Simple histoire

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tu m’as connue au temps des roses,
    Quand les colombes sont écloses ;
    Tes yeux alors pleins de soleil
    Ont brillé sur mon teint vermeil.
    Souriant à ma destinée,
    Par ta douce force entraînée,
    Je ne t’aimai pas à demi,
    Mon jeune ami, mon seul ami !

    À l'étonnement de nos âmes
    Tout jetait des fleurs et des flammes ;
    Une feuille, un bruit de roseaux
    Nous semblaient des hymnes d’oiseaux.
    Quand ce beau temps sur notre tête
    Sonnait à chaque heure une fête,
    Nous n'étions mortels qu'à demi,
    Mon jeune ami, mon seul ami !

    Puis, tu t’en allas vers ta mère,
    Et la vie eut une ombre amère ;
    Autour de mon sort languissant
    L'été même allait pâlissant.
    Les roses me paraient encore ;
    Mais déjà, pleurant l’autre aurore,
    Je n’aimai plus rien qu'à demi,
    Sans mon ami, mon seul ami !

    Un jour, l’invincible espérance
    Poussa ton vaisseau vers la France :
    Tu me ranimas sur ton coeur...
    Jeune, on ne meurt pas de bonheur !
    Mais la guerre appelait tes armes...
    Sous tant de baisers et de larmes
    Je ne t’ai revu qu'à demi,
    Mon jeune ami, mon seul ami !

    Plus tard, un enfant du village
    Accourut, tout pâle au visage,
    Disant : « Voulez-vous le revoir ?
    Demain, ce sera sans espoir.
    Déjà les prières sont faites,
    Venez vite, comme vous êtes... »
    Et je revins morte à demi,
    Mon pauvre ami, mon seul ami !
#+END_VERSE
#+END_CENTER

* Théophile Gautier

** Affinités secrètes

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dans le fronton d’un temple antique,
    Deux blocs de marbre ont, trois mille ans,
    Sur le fond bleu du ciel attique
    Juxtaposé leurs rêves blancs ;

    Dans la même nacre figées,
    Larmes des flots pleurant Vénus,
    Deux perles au gouffre plongées
    Se sont dit des mots inconnus ;

    Au frais Généralife écloses,
    Sous le jet d’eau toujours en pleurs,
    Du temps de Boabdil, deux roses
    Ensemble ont fait jaser leurs fleurs ;

    Sur les coupoles de Venise
    Deux ramiers blancs aux pieds rosés,
    Au nid où l’amour s'éternise
    Un soir de mai se sont posés.

    Marbre, perle, rose, colombe,
    Tout se dissout, tout se détruit ;
    La perle fond, le marbre tombe,
    La fleur se fane et l’oiseau fuit.

    En se quittant, chaque parcelle
    S’en va dans le creuset profond
    Grossir la pâte universelle
    Faite des formes que Dieu fond.

    Par de lentes métamorphoses,
    Les marbres blancs en blanches chairs,
    Les fleurs roses en lèvres roses
    Se refont dans des corps divers.

    Les ramiers de nouveau roucoulent
    Au coeur de deux jeunes amants,
    Et les perles en dents se moulent
    Pour l'écrin des rires charmants.

    De là naissent ces sympathies
    Aux impérieuses douceurs,
    Par qui les âmes averties
    Partout se reconnaissent soeurs.

    Docile à l’appel d’un arome,
    D’un rayon ou d’une couleur,
    L’atome vole vers l’atome
    Comme l’abeille vers la fleur.

    L’on se souvient des rêveries
    Sur le fronton ou dans la mer,
    Des conversations fleuries
    Prés de la fontaine au flot clair,

    Des baisers et des frissons d’ailes
    Sur les dômes aux boules d’or,
    Et les molécules fidèles
    Se cherchent et s’aiment encor.

    L’amour oublié se réveille,
    Le passé vaguement renaît,
    La fleur sur la bouche vermeille
    Se respire et se reconnaît.

    Dans la nacre où le rire brille,
    La perle revoit sa blancheur ;
    Sur une peau de jeune fille,
    Le marbre ému sent sa fraîcheur.

    Le ramier trouve une voix douce,
    Echo de son gémissement,
    Toute résistance s'émousse,
    Et l’inconnu devient l’amant.

    Vous devant qui je brûle et tremble,
    Quel flot, quel fronton, quel rosier,
    Quel dôme nous connut ensemble,
    Perle ou marbre, fleur ou ramier ?
#+END_VERSE
#+END_CENTER

** À une robe rose

#+BEGIN_CENTER
#+BEGIN_VERSE
    Que tu me plais dans cette robe
    Qui te déshabille si bien,
    Faisant jaillir ta gorge en globe,
    Montrant tout nu ton bras païen !

    Frêle comme une aile d’abeille,
    Frais comme un coeur de rose-thé,
    Son tissu, caresse vermeille,
    Voltige autour de ta beauté.

    De l'épiderme sur la soie
    Glissent des frissons argentés,
    Et l'étoffe à la chair renvoie
    Ses éclairs roses reflétés.

    D’où te vient cette robe étrange
    Qui semble faite de ta chair,
    Trame vivante qui mélange
    Avec ta peau son rose clair ?

    Est-ce à la rougeur de l’aurore,
    A la coquille de Vénus,
    Au bouton de sein près d'éclore,
    Que sont pris ces tons inconnus ?

    Ou bien l'étoffe est-elle teinte
    Dans les roses de ta pudeur ?
    Non ; vingt fois modelée et peinte,
    Ta forme connaît sa splendeur.

    Jetant le voile qui te pèse,
    Réalité que l’art rêva,
    Comme la princesse Borghèse
    Tu poserais pour Canova.

    Et ces plis roses sont les lèvres
    De mes désirs inapaisés,
    Mettant au corps dont tu les sèvres
    Une tunique de baisers.
#+END_VERSE
#+END_CENTER

** La montre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Deux fois je regarde ma montre,
    Et deux fois à mes yeux distraits
    L’aiguille au même endroit se montre ;
    Il est une heure... une heure après.

    La figure de la pendule
    En rit dans le salon voisin,
    Et le timbre d’argent module
    Deux coups vibrant comme un tocsin.

    Le cadran solaire me raille
    En m’indiquant, de son long doigt,
    Le chemin que sur la muraille
    A fait son ombre qui s’accroît.

    Le clocher avec ironie
    Dit le vrai chiffre et le beffroi,
    Reprenant la note finie,
    A l’air de se moquer de moi.

    Tiens ! la petite bête est morte.
    Je n’ai pas mis hier encor,
    Tant ma rêverie était forte,
    Au trou de rubis la clef d’or !

    Et je ne vois plus, dans sa boîte,
    Le fin ressort du balancier
    Aller, venir, à gauche, à droite,
    Ainsi qu’un papillon d’acier.

    C’est bien de moi ! Quand je chevauche
    L'Hippogriffe, au pays du Bleu,
    Mon corps sans âme se débauche,
    Et s’en va comme il plaît à Dieu !

    L'éternité poursuit son cercle
    Autour de ce cadran muet,
    Et le temps, l’oreille au couvercle,
    Cherche ce coeur qui remuait ;

    Ce coeur que l’enfant croit en vie,
    Et dont chaque pulsation
    Dans notre poitrine est suivie
    D’une égale vibration,

    Il ne bat plus, mais son grand frère
    Toujours palpite à mon côté.
    - Celui que rien ne peut distraire,
    Quand je dormais, l’a remonté !
#+END_VERSE
#+END_CENTER

** La source

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tout près du lac filtre une source,
    Entre deux pierres, dans un coin ;
    Allègrement l’eau prend sa course
    Comme pour s’en aller bien loin.

    Elle murmure : Oh ! quelle joie !
    Sous la terre il faisait si noir !
    Maintenant ma rive verdoie,
    Le ciel se mire à mon miroir.

    Les myosotis aux fleurs bleues
    Me disent : Ne m’oubliez pas !
    Les libellules de leurs queues
    M'égratignent dans leurs ébats ;

    A ma coupe l’oiseau s’abreuve ;
    Qui sait ? - Après quelques détours
    Peut-être deviendrai-je un fleuve
    Baignant vallons, rochers et tours.

    Je broderai de mon écume
    Ponts de pierre, quais de granit,
    Emportant le steamer qui fume
    A l'Océan où tout finit.

    Ainsi la jeune source jase,
    Formant cent projets d’avenir ;
    Comme l’eau qui bout dans un vase,
    Son flot ne peut se contenir ;

    Mais le berceau touche à la tombe ;
    Le géant futur meurt petit ;
    Née à peine, la source tombe
    Dans le grand lac qui l’engloutit !
#+END_VERSE
#+END_CENTER

** Les yeux bleus de la montagne

#+BEGIN_CENTER
#+BEGIN_VERSE
    On trouve dans les monts des lacs de quelques toises,
    Purs comme des cristaux, bleus comme des turquoises,
    Joyaux tombés du doigt de l’ange Ithuriel,
    Où le chamois craintif, lorsqu’il vient pour y boire,
    S’imagine, trompé par l’optique illusoire,
    Laper l’azur du ciel.

    Ces limpides bassins, quand le jour s’y reflète,
    Ont comme la prunelle une humide paillette ;
    Et ce sont les yeux bleus, au regard calme et doux,
    Par lesquels la montagne en extase contemple,
    Forgeant quelque soleil dans le fond de son temple,
    Dieu, l’ouvrier jaloux !
#+END_VERSE
#+END_CENTER

** Premier sourire du printemps

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tandis qu'à leurs oeuvres perverses
    Les hommes courent haletants,
    Mars qui rit, malgré les averses,
    Prépare en secret le printemps.

    Pour les petites pâquerettes,
    Sournoisement lorsque tout dort,
    Il repasse des collerettes
    Et cisèle des boutons d’or.

    Dans le verger et dans la vigne,
    Il s’en va, furtif perruquier,
    Avec une houppe de cygne,
    Poudrer à frimas l’amandier.

    La nature au lit se repose ;
    Lui descend au jardin désert,
    Et lace les boutons de rose
    Dans leur corset de velours vert.

    Tout en composant des solfèges,
    Qu’aux merles il siffle à mi-voix,
    Il sème aux prés les perce-neiges
    Et les violettes aux bois.

    Sur le cresson de la fontaine
    Où le cerf boit, l’oreille au guet,
    De sa main cachée il égrène
    Les grelots d’argent du muguet.

    Sous l’herbe, pour que tu la cueilles,
    Il met la fraise au teint vermeil,
    Et te tresse un chapeau de feuilles
    Pour te garantir du soleil.

    Puis, lorsque sa besogne est faite,
    Et que son règne va finir,
    Au seuil d’avril tournant la tête,
    Il dit : « Printemps, tu peux venir ! »
#+END_VERSE
#+END_CENTER

* José-Maria de Heredia

** Bretagne

#+BEGIN_CENTER
#+BEGIN_VERSE
    Pour que le sang joyeux dompte l'esprit morose,
    Il faut, tout parfumé du sel des goëmons,
    Que le souffle atlantique emplisse tes poumons ;
    Arvor t'offre ses caps que la mer blanche arrose.

    L'ajonc fleurit et la bruyère est déjà rose.
    La terre des vieux clans, des nains et des démons,
    Ami, te garde encor, sur le granit des monts,
    L'homme immobile auprès de l'immuable chose.

    Viens. Partout tu verras, par les landes d'Arèz,
    Monter vers le ciel morne, infrangible cyprès,
    Le menhir sous lequel gît la cendre du Brave ;

    Et l'Océan, qui roule en un lit d'algues d'or
    Is la voluptueuse et la grande Occismor,
    Bercera ton cour triste à son murmure grave.
#+END_VERSE
#+END_CENTER

** La naissance d'Aphrodité

#+BEGIN_CENTER
#+BEGIN_VERSE
    Avant tout, le Chaos enveloppait les mondes
    Où roulaient sans mesure et l'Espace et le Temps ;
    Puis Gaia, favorable à ses fils les Titans,
    Leur prêta son grand sein aux mamelles fécondes.

    Ils tombèrent. Le Styx les couvrit de ses ondes.
    Et jamais, sous l'éther foudroyé, le Printemps
    N'avait fait resplendir les soleils éclatants,
    Ni l'Eté généreux mûri les moissons blondes.

    Farouches, ignorants des rires et des jeux,
    Les Immortels siégeaient sur l'Olympe neigeux.
    Mais le ciel fit pleuvoir la virile rosée ;

    L'Océan s'entr'ouvrit, et dans sa nudité
    Radieuse, émergeant de l'écume embrasée,
    Dans le sang d'Ouranos fleurit Aphrodité.
#+END_VERSE
#+END_CENTER

** La sieste

#+BEGIN_CENTER
#+BEGIN_VERSE
    Pas un seul bruit d'insecte ou d'abeille en maraude,
    Tout dort sous les grands bois accablés de soleil
    Où le feuillage épais tamise un jour pareil
    Au velours sombre et doux des mousses d'émeraude.

    Criblant le dôme obscur, Midi splendide y rôde
    Et, sur mes cils mi-clos alanguis de sommeil,
    De mille éclairs furtifs forme un réseau vermeil
    Qui s'allonge et se croise à travers l'ombre chaude.

    Vers la gaze de feu que trament les rayons,
    Vole le frêle essaim des riches papillons
    Qu'enivrent la lumière et le parfum des sèves ;

    Alors mes doigts tremblants saisissent chaque fil,
    Et dans les mailles d'or de ce filet subtil,
    Chasseur harmonieux, j'emprisonne mes rêves.
#+END_VERSE
#+END_CENTER

** Le récif de corail

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le soleil sous la mer, mystérieuse aurore,
    Éclaire la forêt des coraux abyssins
    Qui mêle, aux profondeurs de ses tièdes bassins,
    La bête épanouie et la vivante flore.

    Et tout ce que le sel ou l'iode colore,
    Mousse, algue chevelue, anémones, oursins,
    Couvre de pourpre sombre, en somptueux dessins,
    Le fond vermiculé du pâle madrépore.

    De sa splendide écaille éteignant les émaux,
    Un grand poisson navigue à travers les rameaux ;
    Dans l'ombre transparente indolemment il rôde ;

    Et, brusquement, d'un coup de sa nageoire en feu
    Il fait, par le cristal morne, immobile et bleu,
    Courir un frisson d'or, de nacre et d'émeraude.
#+END_VERSE
#+END_CENTER

** Un peintre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il a compris la race antique aux yeux pensifs
    Qui foule le sol dur de la terre bretonne,
    La lande rase, rose et grise et monotone
    Où croulent les manoirs sous le lierre et les ifs.

    Des hauts talus plantés de hêtres convulsifs,
    Il a vu, par les soirs tempétueux d'automne,
    Sombrer le soleil rouge en la mer qui moutonne ;
    Sa lèvre s'est salée à l'embrun des récifs.

    Il a peint l'Océan splendide, immense et triste,
    Où le nuage laisse un reflet d'améthyste,
    L'émeraude écumante et le calme saphir ;

    Et fixant l'eau, l'air, l'ombre et l'heure insaisissables,
    Sur une toile étroite il a fait réfléchir
    Le ciel occidental dans le miroir des sables.
#+END_VERSE
#+END_CENTER

* Victor Hugo

** À celle qui est voilée

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tu me parles du fond d’un rêve
    Comme une âme parle aux vivants.
    Comme l'écume de la grève,
    Ta robe flotte dans les vents.

    Je suis l’algue des flots sans nombre,
    Le captif du destin vainqueur ;
    Je suis celui que toute l’ombre
    Couvre sans éteindre son coeur.

    Mon esprit ressemble à cette île,
    Et mon sort à cet océan ;
    Et je suis l’habitant tranquille
    De la foudre et de l’ouragan.

    Je suis le proscrit qui se voile,
    Qui songe, et chante, loin du bruit,
    Avec la chouette et l'étoile,
    La sombre chanson de la nuit.

    Toi, n’es-tu pas, comme moi-même,
    Flambeau dans ce monde âpre et vil,
    Ame, c’est-à-dire problème,
    Et femme, c’est-à-dire exil ?

    Sors du nuage, ombre charmante.
    O fantôme, laisse-toi voir !
    Sois un phare dans ma tourmente,
    Sois un regard dans mon ciel noir !

    Cherche-moi parmi les mouettes !
    Dresse un rayon sur mon récif,
    Et, dans mes profondeurs muettes,
    La blancheur de l’ange pensif !

    Sois l’aile qui passe et se mêle
    Aux grandes vagues en courroux.
    Oh, viens ! tu dois être bien belle,
    Car ton chant lointain est bien doux ;

    Car la nuit engendre l’aurore ;
    C’est peut-être une loi des cieux
    Que mon noir destin fasse éclore
    Ton sourire mystérieux !

    Dans ce ténébreux monde où j’erre,
    Nous devons nous apercevoir,
    Toi, toute faite de lumière,
    Moi, tout composé de devoir !

    Tu me dis de loin que tu m’aimes,
    Et que, la nuit, à l’horizon,
    Tu viens voir sur les grèves blêmes
    Le spectre blanc de ma maison.

    Là, méditant sous le grand dôme,
    Près du flot sans trêve agité,
    Surprise de trouver l’atome
    Ressemblant à l’immensité,

    Tu compares, sans me connaître,
    L’onde à l’homme, l’ombre au banni,
    Ma lampe étoilant ma fenêtre
    A l’astre étoilant l’infini !

    Parfois, comme au fond d’une tombe,
    Je te sens sur mon front fatal,
    Bouche de l'Inconnu d’où tombe
    Le pur baiser de l'Idéal.

    A ton souffle, vers Dieu poussées,
    Je sens en moi, douce frayeur,
    Frissonner toutes mes pensées,
    Feuilles de l’arbre intérieur.

    Mais tu ne veux pas qu’on te voie ;
    Tu viens et tu fuis tour à tour ;
    Tu ne veux pas te nommer joie,
    Ayant dit : Je m’appelle amour.

    Oh ! fais un pas de plus ! Viens, entre,
    Si nul devoir ne le défend ;
    Viens voir mon âme dans son antre,
    L’esprit lion, le coeur enfant ;

    Viens voir le désert où j’habite
    Seul sous mon plafond effrayant ;
    Sois l’ange chez le cénobite,
    Sois la clarté chez le voyant.

    Change en perles dans mes décombres
    Toutes mes gouttes de sueur !
    Viens poser sur mes oeuvres sombres
    Ton doigt d’où sort une lueur !

    Du bord des sinistres ravines
    Du rêve et de la vision,
    J’entrevois les choses divines... -
    Complète l’apparition !

    Viens voir le songeur qui s’enflamme
    A mesure qu’il se détruit,
    Et, de jour en jour, dans son âme
    A plus de mort et moins de nuit !

    Viens ! viens dans ma brume hagarde,
    Où naît la foi, d’où l’esprit sort,
    Où confusément je regarde
    Les formes obscures du sort.

    Tout s'éclaire aux lueurs funèbres ;
    Dieu, pour le penseur attristé,
    Ouvre toujours dans les ténèbres
    De brusques gouffres de clarté.

    Avant d'être sur cette terre,
    Je sens que jadis j’ai plané ;
    J'étais l’archange solitaire,
    Et mon malheur, c’est d'être né.

    Sur mon âme, qui fut colombe,
    Viens, toi qui des cieux as le sceau.
    Quelquefois une plume tombe
    Sur le cadavre d’un oiseau.

    Oui, mon malheur irréparable,
    C’est de pendre aux deux éléments,
    C’est d’avoir en moi, misérable,
    De la fange et des firmaments !

    Hélas ! hélas ! c’est d'être un homme ;
    C’est de songer que j'étais beau,
    D’ignorer comment je me nomme,
    D'être un ciel et d'être un tombeau !

    C’est d'être un forçat qui promène
    Son vil labeur sous le ciel bleu ;
    C’est de porter la hotte humaine
    Où j’avais vos ailes, mon Dieu !

    C’est de traîner de la matière ;
    C’est d'être plein, moi, fils du jour,
    De la terre du cimetière,
    Même quand je m'écrie : Amour !
#+END_VERSE
#+END_CENTER

** Demain, dès l'aube...

#+BEGIN_CENTER
#+BEGIN_VERSE
    Demain, dès l’aube, à l’heure où blanchit la campagne,
    Je partirai. Vois-tu, je sais que tu m’attends.
    J’irai par la forêt, j’irai par la montagne.
    Je ne puis demeurer loin de toi plus longtemps.

    Je marcherai les yeux fixés sur mes pensées,
    Sans rien voir au dehors, sans entendre aucun bruit,
    Seul, inconnu, le dos courbé, les mains croisées,
    Triste, et le jour pour moi sera comme la nuit.

    Je ne regarderai ni l’or du soir qui tombe,
    Ni les voiles au loin descendant vers Harfleur,
    Et quand j’arriverai, je mettrai sur ta tombe
    Un bouquet de houx vert et de bruyère en fleur.
#+END_VERSE
#+END_CENTER

** Hier au soir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Hier, le vent du soir, dont le souffle caresse,
    Nous apportait l’odeur des fleurs qui s’ouvrent tard ;
    La nuit tombait ; l’oiseau dormait dans l’ombre épaisse.
    Le printemps embaumait, moins que votre jeunesse ;
    Les astres rayonnaient, moins que votre regard.

    Moi, je parlais tout bas. C’est l’heure solennelle
    Où l'âme aime à chanter son hymne le plus doux.
    Voyant la nuit si pure et vous voyant si belle,
    J’ai dit aux astres d’or : Versez le ciel sur elle !
    Et j’ai dit à vos yeux : Versez l’amour sur nous !
#+END_VERSE
#+END_CENTER

** J'ai cueilli cette fleur pour toi sur la colline.

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai cueilli cette fleur pour toi sur la colline.
    Dans l'âpre escarpement qui sur le flot s’incline,
    Que l’aigle connaît seul et seul peut approcher,
    Paisible, elle croissait aux fentes du rocher.
    L’ombre baignait les flancs du morne promontoire ;
    Je voyais, comme on dresse au lieu d’une victoire
    Un grand arc de triomphe éclatant et vermeil,
    À l’endroit où s'était englouti le soleil,
    La sombre nuit bâtir un porche de nuées.
    Des voiles s’enfuyaient, au loin diminuées ;
    Quelques toits, s'éclairant au fond d’un entonnoir,
    Semblaient craindre de luire et de se laisser voir.
    J’ai cueilli cette fleur pour toi, ma bien-aimée.
    Elle est pâle, et n’a pas de corolle embaumée,
    Sa racine n’a pris sur la crête des monts
    Que l’amère senteur des glauques goémons ;
    Moi, j’ai dit: Pauvre fleur, du haut de cette cime,
    Tu devais t’en aller dans cet immense abîme
    Où l’algue et le nuage et les voiles s’en vont.
    Va mourir sur un coeur, abîme plus profond.
    Fane-toi sur ce sein en qui palpite un monde.
    Le ciel, qui te créa pour t’effeuiller dans l’onde,
    Te fit pour l’océan, je te donne à l’amour. -
    Le vent mêlait les flots; il ne restait du jour
    Qu’une vague lueur, lentement effacée.
    Oh! comme j'étais triste au fond de ma pensée
    Tandis que je songeais, et que le gouffre noir
    M’entrait dans l'âme avec tous les frissons du soir !
#+END_VERSE
#+END_CENTER

** Jeune fille, l'amour, c'est d'abord un miroir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Jeune fille, l’amour, c’est d’abord un miroir
    Où la femme coquette et belle aime à se voir,
    Et, gaie ou rêveuse, se penche ;
    Puis, comme la vertu, quand il a votre coeur,
    Il en chasse le mal et le vice moqueur,
    Et vous fait l'âme pure et blanche ;

    Puis on descend un peu, le pied vous glisse... - Alors
    C’est un abîme ! en vain la main s’attache aux bords,
    On s’en va dans l’eau qui tournoie ! -
    L’amour est charmant, pur, et mortel. N’y crois pas !
    Tel l’enfant, par un fleuve attiré pas à pas,
    S’y mire, s’y lave et s’y noie.
#+END_VERSE
#+END_CENTER

** La source

#+BEGIN_CENTER
#+BEGIN_VERSE
    La source tombait du rocher
    Goutte à goutte à la mer affreuse.
    L’océan, fatal au nocher,
    Lui dit : - Que me veux-tu, pleureuse ?

    Je suis la tempête et l’effroi ;
    Je finis où le ciel commence.
    Est-ce que j’ai besoin de toi,
    Petite, moi qui suis l’immense ? -

    La source dit au gouffre amer :
    - je te donne, sans bruit ni gloire,
    Ce qui te manque, ô vaste mer !
    Une goutte d’eau qu’on peut boire.
#+END_VERSE
#+END_CENTER

** Ô mes lettres d'amour, de vertu, de jeunesse

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ô mes lettres d’amour, de vertu, de jeunesse,
    C’est donc vous ! Je m’enivre encore à votre ivresse ;
    Je vous lis à genoux.
    Souffrez que pour un jour je reprenne votre âge !
    Laissez-moi me cacher, moi, l’heureux et le sage,
    Pour pleurer avec vous !

    J’avais donc dix-huit ans ! j'étais donc plein de songes !
    L’espérance en chantant me berçait de mensonges.
    Un astre m’avait lui !
    J'étais un dieu pour toi qu’en mon coeur seul je nomme !
    J'étais donc cet enfant, hélas! devant qui l’homme
    Rougit presque aujourd’hui !

    Ô temps de rêverie, et de force, et de grâce !
    Attendre tous les soirs une robe qui passe !
    Baiser un gant jeté !
    Vouloir tout de la vie, amour, puissance et gloire !
    Etre pur, être fier, être sublime et croire
    A toute pureté !

    A présent j’ai senti, j’ai vu, je sais. - Qu’importe ?
    Si moins d’illusions viennent ouvrir ma porte
    Qui gémit en tournant !
    Oh ! que cet âge ardent, qui me semblait si sombre,
    A côté du bonheur qui m’abrite à son ombre,
    Rayonne maintenant !

    Que vous ai-je donc fait, ô mes jeunes années !
    Pour m’avoir fui si vite et vous être éloignées
    Me croyant satisfait ?
    Hélas ! pour revenir m’apparaître si belles,
    Quand vous ne pouvez plus me prendre sur vos ailes,
    Que vous ai-je donc fait ?

    Oh ! quand ce doux passé, quand cet âge sans tache,
    Avec sa robe blanche où notre amour s’attache,
    Revient dans nos chemins,
    On s’y suspend, et puis que de larmes amères
    Sur les lambeaux flétris de vos jeunes chimères
    Qui vous restent aux mains !

    Oublions ! oublions ! Quand la jeunesse est morte,
    Laissons-nous emporter par le vent qui l’emporte
    A l’horizon obscur,
    Rien ne reste de nous ; notre oeuvre est un problème.
    L’homme, fantôme errant, passe sans laisser même
    Son ombre sur le mur !
#+END_VERSE
#+END_CENTER

** Puisque j'ai mis ma lèvre à ta coupe encor pleine

#+BEGIN_CENTER
#+BEGIN_VERSE
    Puisque j’ai mis ma lèvre à ta coupe encor pleine ;
    Puisque j’ai dans tes mains posé mon front pâli ;
    Puisque j’ai respiré parfois la douce haleine
    De ton âme, parfum dans l’ombre enseveli ;

    Puisqu’il me fut donné de t’entendre me dire
    Les mots où se répand le coeur mystérieux ;
    Puisque j’ai vu pleurer, puisque j’ai vu sourire
    Ta bouche sur ma bouche et tes yeux sur mes yeux ;

    Puisque j’ai vu briller sur ma tête ravie
    Un rayon de ton astre, hélas ! voilé toujours ;
    Puisque j’ai vu tomber dans l’onde de ma vie
    Une feuille de rose arrachée à tes jours ;

    Je puis maintenant dire aux rapides années :
    - Passez ! passez toujours ! je n’ai plus à vieillir !
    Allez-vous-en avec vos fleurs toutes fanées ;
    J’ai dans l'âme une fleur que nul ne peut cueillir !

    Votre aile en le heurtant ne fera rien répandre
    Du vase où je m’abreuve et que j’ai bien rempli.
    Mon âme a plus de feu que vous n’avez de cendre !
    Mon coeur a plus d’amour que vous n’avez d’oubli !
#+END_VERSE
#+END_CENTER

** Soleils couchants

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’aime les soirs sereins et beaux, j’aime les soirs,
    Soit qu’ils dorent le front des antiques manoirs
    Ensevelis dans les feuillages ;
    Soit que la brume au loin s’allonge en bancs de feu ;
    Soit que mille rayons brisent dans un ciel bleu
    A des archipels de nuages.

    Oh ! regardez le ciel ! cent nuages mouvants,
    Amoncelés là-haut sous le souffle des vents,
    Groupent leurs formes inconnues ;
    Sous leurs flots par moments flamboie un pâle éclair.
    Comme si tout à coup quelque géant de l’air
    Tirait son glaive dans les nues.

    Le soleil, à travers leurs ombres, brille encor ;
    Tantôt fait, à l'égal des larges dômes d’or,
    Luire le toit d’une chaumière ;
    Ou dispute aux brouillards les vagues horizons ;
    Ou découpe, en tombant sur les sombres gazons,
    Comme de grands lacs de lumière.

    Puis voilà qu’on croit voir, dans le ciel balayé,
    Pendre un grand crocodile au dos large et rayé,
    Aux trois rangs de dents acérées ;
    Sous son ventre plombé glisse un rayon du soir ;
    Cent nuages ardents luisent sous son flanc noir
    Comme des écailles dorées.

    Puis se dresse un palais. Puis l’air tremble, et tout fuit.
    L'édifice effrayant des nuages détruit
    S'écroule en ruines pressées ;
    Il jonche au loin le ciel, et ses cônes vermeils
    Pendent, la pointe en bas, sur nos têtes, pareils
    A des montagnes renversées.

    Ces nuages de plomb, d’or, de cuivre, de fer,
    Où l’ouragan, la trombe, et la foudre, et l’enfer
    Dorment avec de sourds murmures,
    C’est Dieu qui les suspend en foule aux cieux profonds,
    Comme un guerrier qui pend aux poutres des plafonds
    Ses retentissantes armures.

    Tout s’en va ! Le soleil, d’en haut précipité,
    Comme un globe d’airain qui, rouge, est rejeté
    Dans les fournaises remuées,
    En tombant sur leurs flots que son choc désunit
    Fait en flocons de feu jaillir jusqu’au zénith
    L’ardente écume des nuées.

    Oh ! contemplez le ciel ! et dès qu’a fui le jour,
    En tout temps, en tout lieu, d’un ineffable amour,
    Regardez à travers ses voiles ;
    Un mystère est au fond de leur grave beauté,
    L’hiver, quand ils sont noirs comme un linceul, l'été,
    Quand la nuit les brode d'étoiles.
#+END_VERSE
#+END_CENTER

** Une nuit qu'on entendait la mer sans la voir

#+BEGIN_CENTER
#+BEGIN_VERSE
    Quels sont ces bruits sourds ?
    Ecoutez vers l’onde
    Cette voix profonde
    Qui pleure toujours
    Et qui toujours gronde,
    Quoiqu’un son plus clair
    Parfois l’interrompe... -
    Le vent de la mer
    Souffle dans sa trompe.

    Comme il pleut ce soir !
    N’est-ce pas, mon hôte ?
    Là-bas, à la côte,
    Le ciel est bien noir,
    La mer est bien haute !
    On dirait l’hiver ;
    Parfois on s’y trompe... -
    Le vent de la mer
    Souffle dans sa trompe.

    Oh ! marins perdus !
    Au loin, dans cette ombre
    Sur la nef qui sombre,
    Que de bras tendus
    Vers la terre sombre !
    Pas d’ancre de fer
    Que le flot ne rompe. -
    Le vent de la mer
    Souffle dans sa trompe.

    Nochers imprudents !
    Le vent dans la voile
    Déchire la toile
    Comme avec les dents !
    Là-haut pas d'étoile !
    L’un lutte avec l’air,
    L’autre est à la pompe. -
    Le vent de la mer
    Souffle dans sa trompe.

    C’est toi, c’est ton feu
    Que le nocher rêve,
    Quand le flot s'élève,
    Chandelier que Dieu
    Pose sur la grève,
    Phare au rouge éclair
    Que la brume estompe ! -
    Le vent de la mer
    Souffle dans sa trompe.
#+END_VERSE
#+END_CENTER

* Charles-Marie Leconte de Lisle

** Aux modernes

#+BEGIN_CENTER
#+BEGIN_VERSE
    Vous vivez lâchement, sans rêve, sans dessein,
    Plus vieux, plus décrépits que la terre inféconde,
    Châtrés dès le berceau par le siècle assassin
    De toute passion vigoureuse et profonde.

    Votre cervelle est vide autant que votre sein,
    Et vous avez souillé ce misérable monde
    D’un sang si corrompu, d’un souffle si malsain,
    Que la mort germe seule en cette boue immonde.

    Hommes, tueurs de Dieux, les temps ne sont pas loin
    Où, sur un grand tas d’or vautrés dans quelque coin,
    Ayant rongé le sol nourricier jusqu’aux roches,

    Ne sachant faire rien ni des jours ni des nuits,
    Noyés dans le néant des suprêmes ennuis,
    Vous mourrez bêtement en emplissant vos poches.
#+END_VERSE
#+END_CENTER

** La dernière vision

#+BEGIN_CENTER
#+BEGIN_VERSE
    Un long silence pend de l’immobile nue.
    La neige, bossuant ses plis amoncelés,
    Linceul rigide, étreint les océans gelés.
    La face de la terre est absolument nue.

    Point de villes, dont l'âge a rompu les étais,
    Qui s’effondrent par blocs confus que mord le lierre.
    Des lieux où tournoyait l’active fourmilière
    Pas un débris qui parle et qui dise : J'étais !

    Ni sonnantes forêts, ni mers des vents battues.
    Vraiment, la race humaine et tous les animaux
    Du sinistre anathème ont épuisé les maux.
    Les temps sont accomplis : les choses se sont tues.

    Comme, du faîte plat d’un grand sépulcre ancien,
    La lampe dont blêmit la lueur vagabonde,
    Plein d’ennui, palpitant sur le désert du monde,
    Le soleil qui se meurt regarde et ne voit rien.

    Un monstre insatiable a dévoré la vie.
    Astres resplendissants des cieux, soyez témoins !
    C’est à vous de frémir, car ici-bas, du moins,
    L’affreux spectre, la goule horrible est assouvie.

    Vertu, douleur, pensée, espérance, remords,
    Amour qui traversais l’univers d’un coup d’aile,
    Qu'êtes-vous devenus ? L'âme, qu’a-t-on fait d’elle ?
    Qu’a-t-on fait de l’esprit silencieux des morts ?

    Tout ! tout a disparu, sans échos et sans traces,
    Avec le souvenir du monde jeune et beau.
    Les siècles ont scellé dans le même tombeau
    L’illusion divine et la rumeur des races.

    Ô soleil ! vieil ami des antiques chanteurs,
    Père des bois, des blés, des fleurs et des rosées,
    Éteins donc brusquement tes flammes épuisées,
    Comme un feu de berger perdu sur les hauteurs.

    Que tardes-tu ? La terre est desséchée et morte :
    Fais comme elle, va, meurs ! Pourquoi survivre encor ?
    Les globes détachés de ta ceinture d’or
    Volent, poussière éparse, au vent qui les emporte.

    Et, d’heure en heure aussi, vous vous engloutirez,
    Ô tourbillonnements d'étoiles éperdues,
    Dans l’incommensurable effroi des étendues,
    Dans les gouffres muets et noirs des cieux sacrés !

    Et ce sera la Nuit aveugle, la grande Ombre
    Informe, dans son vide et sa stérilité,
    L’abîme pacifique où gît la vanité
    De ce qui fut le temps et l’espace et le nombre.
#+END_VERSE
#+END_CENTER

** Le dernier souvenir

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai vécu, je suis mort. - Les yeux ouverts, je coule
    Dans l’incommensurable abîme, sans rien voir,
    Lent comme une agonie et lourd comme une foule.

    Inerte, blême, au fond d’un lugubre entonnoir
    Je descends d’heure en heure et d’année en année,
    À travers le Muet, l'Immobile, le Noir.

    Je songe, et ne sens plus. L'épreuve est terminée.
    Qu’est-ce donc que la vie ? Étais-je jeune ou vieux ?
    Soleil ! Amour ! - Rien, rien. Va, chair abandonnée !

    Tournoie, enfonce, va ! Le vide est dans tes yeux,
    Et l’oubli s'épaissit et t’absorbe à mesure.
    Si je rêvais ! Non, non, je suis bien mort. Tant mieux.

    Mais ce spectre, ce cri, cette horrible blessure ?
    Cela dut m’arriver en des temps très anciens.
    Ô nuit ! Nuit du néant, prends-moi ! - La chose est sûre :

    Quelqu’un m’a dévoré le coeur. Je me souviens.
#+END_VERSE
#+END_CENTER

** Les clairs de lune - I

#+BEGIN_CENTER
#+BEGIN_VERSE
    C’est un monde difforme, abrupt, lourd et livide,
    Le spectre monstrueux d’un univers détruit
    Jeté comme une épave à l'Océan du vide,
    Enfer pétrifié, sans flammes et sans bruit,
    Flottant et tournoyant dans l’impassible nuit.
    Autrefois, revêtu de sa grâce première,
    Globe heureux d’où montait la rumeur des vivants,
    Jeune, il a fait ailleurs sa route de lumière,
    Avec ses eaux, ses bleus sommets, ses bois mouvants,
    Sa robe de vapeurs mollement dénouées,
    Ses millions d’oiseaux chantant par les nuées,
    Dans la pourpre du ciel et sur l’aile des vents.
    Loin des tièdes soleils, loin des nocturnes gloires,
    À travers l'étendue il roule maintenant ;
    Et voici qu’une mer d’ombre, par gerbes noires,
    Contre les bords rongés du hideux continent
    S'écrase, furieuse, et troue en bouillonnant
    Le blême escarpement des rugueux promontoires.
    Jusqu’au faîte des pics elle jaillit d’un bond,
    Et, sur leurs escaliers versant ses cataractes,
    Écume et rejaillit, hors des gouffres sans fond,
    Dans l’espace aspergé de ténèbres compactes.
    Et de ces blocs disjoints, de ces lugubres flots,
    De cet écroulement horrible, morne, immense,
    On n’entend rien sortir, ni clameurs ni sanglots
    Le sinistre univers se dissout en silence.
    Mais la Terre, plus bas, qui rêve et veille encor
    Sous le pétillement des solitudes bleues,
    Regarde en souriant, à des milliers de lieues,
    La lune, dans l’air pur, tendre son grand arc d’or.
#+END_VERSE
#+END_CENTER

** Midi

#+BEGIN_CENTER
#+BEGIN_VERSE
    Midi, Roi des étés, épandu sur la plaine,
    Tombe en nappes d’argent des hauteurs du ciel bleu.
    Tout se tait. L’air flamboie et brûle sans haleine ;
    La Terre est assoupie en sa robe de feu.

    L'étendue est immense, et les champs n’ont point d’ombre,
    Et la source est tarie où buvaient les troupeaux ;
    La lointaine forêt, dont la lisière est sombre,
    Dort là-bas, immobile, en un pesant repos.

    Seuls, les grands blés mûris, tels qu’une mer dorée,
    Se déroulent au loin, dédaigneux du sommeil ;
    Pacifiques enfants de la Terre sacrée,
    Ils épuisent sans peur la coupe du Soleil.

    Parfois, comme un soupir de leur âme brûlante,
    Du sein des épis lourds qui murmurent entre eux,
    Une ondulation majestueuse et lente
    S'éveille, et va mourir à l’horizon poudreux.

    Non loin, quelques boeufs blancs, couchés parmi les herbes,
    Bavent avec lenteur sur leurs fanons épais,
    Et suivent de leurs yeux languissants et superbes
    Le songe intérieur qu’ils n’achèvent jamais.

    Homme, si, le coeur plein de joie ou d’amertume,
    Tu passais vers midi dans les champs radieux,
    Fuis ! la Nature est vide et le Soleil consume :
    Rien n’est vivant ici, rien n’est triste ou joyeux.

    Mais si, désabusé des larmes et du rire,
    Altéré de l’oubli de ce monde agité,
    Tu veux, ne sachant plus pardonner ou maudire,
    Goûter une suprême et morne volupté,

    Viens ! Le Soleil te parle en paroles sublimes ;
    Dans sa flamme implacable absorbe-toi sans fin ;
    Et retourne à pas lents vers les cités infimes,
    Le coeur trempé sept fois dans le Néant divin.
#+END_VERSE
#+END_CENTER

** Solvet seclum

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tu te tairas, ô voix sinistre des vivants !

    Blasphèmes furieux qui roulez par les vents,
    Cris d'épouvante, cris de haine, cris de rage,
    Effroyables clameurs de l'éternel naufrage,
    Tourments, crimes, remords, sanglots désespérés,
    Esprit et chair de l’homme, un jour vous vous tairez !
    Tout se taira, dieux, rois, forçats et foules viles,
    Le rauque grondement des bagnes et des villes,
    Les bêtes des forêts, des monts et de la mer,
    Ce qui vole et bondit et rampe en cet enfer.

    Tout ce qui tremble et fuit, tout ce qui tue et mange
    Depuis le ver de terre écrasé dans la fange
    Jusqu'à la foudre errant dans l'épaisseur des nuits !
    D’un seul coup la nature interrompra ses bruits,
    Et ce ne sera point, sous les cieux magnifiques,
    Le bonheur reconquis des paradis antiques,
    Ni l’entretien d'Adam et d'Ève sur les fleurs,
    Ni le divin sommeil après tant de douleurs ;
    Ce sera quand le Globe et tout ce qui l’habite,
    Bloc stérile arraché de son immense orbite,
    Stupide, aveugle, plein d’un dernier hurlement,
    Plus lourd, plus éperdu de moment en moment,
    Contre quelque univers immobile en sa force
    Défoncera sa vieille et misérable écorce,
    Et, laissant ruisseler, par mille trous béants,
    Sa flamme intérieure avec ses océans,
    Ira fertiliser de ses restes immondes
    Les sillons de l’espace où fermentent les mondes.
#+END_VERSE
#+END_CENTER

** Un coucher de soleil

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sur la côte d’un beau pays,
    Par delà les flots Pacifiques,
    Deux hauts palmiers épanouis
    Bercent leurs palmes magnifiques.

    À leur ombre, tel qu’un Nabab
    Qui, vers midi, rêve et repose,
    Dort un grand tigre du Pendj-Ab,
    Allongé sur le sable rose ;

    Et, le long des fûts lumineux,
    Comme au paradis des genèses,
    Deux serpents enroulent leurs noeuds
    Dans une spirale de braises.

    Auprès, un golfe de satin,
    Où le feuillage se reflète,
    Baigne un vieux palais byzantin
    De brique rouge et violette.

    Puis, des cygnes noirs, par milliers,
    L’aile ouverte au vent qui s’y joue,
    Ourlent, au bas des escaliers,
    L’eau diaphane avec leur proue.

    L’horizon est immense et pur ;
    À peine voit-on, aux cieux calmes,
    Descendre et monter dans l’azur
    La palpitation des palmes.

    Mais voici qu’au couchant vermeil
    L’oiseau Rok s’enlève, écarlate :
    Dans son bec il tient le soleil,
    Et des foudres dans chaque patte.

    Sur le poitrail du vieil oiseau,
    Qui fume, pétille et s’embrase,
    L’astre coule et fait un ruisseau
    Couleur d’or, d’ambre et de topaze.

    Niagara resplendissant,
    Ce fleuve s'écroule aux nuées,
    Et rejaillit en y laissant
    Des écumes d'éclairs trouées.

    Soudain le géant Orion,
    Ou quelque sagittaire antique,
    Du côté du septentrion
    Dresse sa stature athlétique.

    Le Chasseur tend son arc de fer
    Tout rouge au sortir de la forge,
    Et, faisant un pas sur la mer,
    Transperce le Rok à la gorge.

    D’un coup d’aile l’oiseau sanglant
    S’enfonce à travers l'étendue ;
    Et le soleil tombe en brûlant,
    Et brise sa masse éperdue.

    Alors des volutes de feu
    Dévorent d’immenses prairies,
    S'élancent, et, du zénith bleu,
    Pleuvent en flots de pierreries.

    Sur la face du ciel mouvant
    Gisent de flamboyants décombres ;
    Un dernier jet exhale au vent
    Des tourbillons de pourpre et d’ombres ;

    Et, se dilantant par bonds lourds,
    Muette, sinistre, profonde,
    La nuit traîne son noirs velours
    Sur la solitude du monde
#+END_VERSE
#+END_CENTER

* François de Malherbe

** Dessein de quitter une dame qui ne le contentait que de promesse

#+BEGIN_CENTER
#+BEGIN_VERSE
    Beauté, mon beau souci, de qui l'âme incertaine
    A, comme l'océan, son flux et son reflux,
    Pensez de vous résoudre à soulager ma peine,
    Ou je me vais résoudre à ne la souffrir plus.

    Vos yeux ont des appas que j'aime et que je prise.
    Et qui peuvent beaucoup dessus ma liberté :
    Mais pour me retenir, s'ils font cas de ma prise,
    Il leur faut de l'amour autant que de beauté.

    Quand je pense être au point que cela s'accomplisse
    Quelque excuse toujours en empêche l'effet;
    C'est la toile sans fin de la femme d'Ulysse,
    Dont l'ouvrage du soir au matin se défait.

    Madame, avisez-y, vous perdez votre gloire
    De me l'avoir promis et vous rire de moi.
    S'il ne vous en souvient, vous manquez de mémoire
    Et s'îl vous en souvient, vous n'avez point de foi.

    J'avais toujours fait compte, aimant chose si haute,
    De ne m'en séparer qu'avecque le trépas
    S'il arrive autrement ce sera votre faute,
    De faire des serments et ne les tenir pas.
#+END_VERSE
#+END_CENTER

* Stéphane Mallarmé

** Eventail de Mademoiselle Mallarmé

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ô rêveuse, pour que je plonge
    Au pur délice sans chemin,
    Sache, par un subtil mensonge,
    Garder mon aile dans ta main.

    Une fraîcheur de crépuscule
    Te vient à chaque battement
    Dont le coup prisonnier recule
    L’horizon délicatement.

    Vertige ! voici que frissonne
    L’espace comme un grand baiser
    Qui, fou de naître pour personne,
    Ne peut jaillir ni s’apaiser.

    Sens-tu le paradis farouche
    Ainsi qu’un rire enseveli
    Se couler du coin de ta bouche
    Au fond de l’unanime pli !

    Le sceptre des rivages roses
    Stagnants sur les soirs d’or, ce l’est,
    Ce blanc vol fermé que tu poses
    Contre le feu d’un bracelet.
#+END_VERSE
#+END_CENTER

** La chevelure vol...

#+BEGIN_CENTER
#+BEGIN_VERSE
    La chevelure vol d’une flamme à l’extrême
    Occident de désirs pour la tout éployer
    Se pose (je dirais mourir un diadème)
    Vers le front couronné son ancien foyer

    Mais sans or soupirer que cette vive nue
    L’ignition du feu toujours intérieur
    Originellement la seule continue
    Dans le joyau de l’oeil véridique ou rieur

    Une nudité de héros tendre diffame
    Celle qui ne mouvant astre ni feux au doigt
    Rien qu'à simplifier avec gloire la femme
    Accomplit par son chef fulgurante l’exploit

    De semer de rubis le doute qu’elle écorche
    Ainsi qu’une joyeuse et tutélaire torche
#+END_VERSE
#+END_CENTER

** Le vierge, le vivace ...

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le vierge, le vivace et le bel aujourd’hui
    Va-t-il nous déchirer avec un coup d’aile ivre
    Ce lac dur oublié que hante sous le givre
    Le transparent glacier des vols qui n’ont pas fui !

    Un cygne d’autrefois se souvient que c’est lui
    Magnifique mais qui sans espoir se délivre
    Pour n’avoir pas chanté la région où vivre
    Quand du stérile hiver a resplendi l’ennui.

    Tout son col secouera cette blanche agonie
    Par l’espace infligée à l’oiseau qui le nie,
    Mais non l’horreur du sol où le plumage est pris.

    Fantôme qu'à ce lieu son pur éclat assigne,
    Il s’immobilise au songe froid de mépris
    Que vêt parmi l’exil inutile le Cygne.
#+END_VERSE
#+END_CENTER

** O, si chère de loin ...

#+BEGIN_CENTER
#+BEGIN_VERSE
    O si chère de loin et proche et blanche, si
    Délicieusement toi, Mary, que je songe
    À quelque baume rare émané par mensonge
    Sur aucun bouquetier de cristal obscurci

    Le sais-tu, oui ! pour moi voici des ans, voici
    Toujours que ton sourire éblouissant prolonge
    La même rose avec son bel été qui plonge
    Dans autrefois et puis dans le futur aussi.

    Mon coeur qui dans les nuits parfois cherche à s’entendre
    Ou de quel dernier mot t’appeler le plus tendre
    S’exalte en celui rien que chuchoté de soeur

    N'étant, très grand trésor et tête si petite,
    Que tu m’enseignes bien toute une autre douceur
    Tout bas par le baiser seul dans tes cheveux dite.
#+END_VERSE
#+END_CENTER

** Placet futile

#+BEGIN_CENTER
#+BEGIN_VERSE
    Princesse ! à jalouser le destin d’une Hébé
    Qui poind sur cette tasse au baiser de vos lèvres,
    J’use mes feux mais n’ai rang discret que d’abbé
    Et ne figurerai même nu sur le Sèvres.

    Comme je ne suis pas ton bichon embarbé,
    Ni la pastille ni du rouge, ni Jeux mièvres
    Et que sur moi je sais ton regard clos tombé,
    Blonde dont les coiffeurs divins sont des orfèvres !

    Nommez-nous... toi de qui tant de ris framboisés
    Se joignent en troupeau d’agneaux apprivoisés
    Chez tous broutant les voeux et bêlant aux délires,

    Nommez-nous... pour qu'Amour ailé d’un éventail
    M’y peigne flûte aux doigts endormant ce bercail,
    Princesse, nommez-nous berger de vos sourires.
#+END_VERSE
#+END_CENTER

** Rêve antique

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle est dans l’atrium la blonde Lycoris
    Sous un flot parfumé mollement renversée.
    Comme un saule jauni s'épand sous la rosée,
    Ses cheveux sur son sein pleuvent longs et fleuris.

    Dans les roseaux, vis-tu, sur un fleuve bleuâtre,
    Le soir, glisser le front de la pâle Phoebé ?
    – Elle dort dans son bain et sa gorge d’albâtre,
    Comme la lune, argente un flot du ciel tombé.

    Son doigt qui sur l’eau calme effeuillait une rose
    Comme une urne odorante offre un calice vert :
    Descends, ô brune Hébé ! verse de ta main rose
    Ce vin qui fait qu’un coeur brûle, à tout coeur ouvert.

    Elle est dans l’atrium la blonde Lycoris
    Sous un flot parfumé mollement renversée :
    Comme ton arc d’argent, Diane aux forêts lancée,
    Se détend son beau corps sous ses amants choisis.
#+END_VERSE
#+END_CENTER

** Sainte

#+BEGIN_CENTER
#+BEGIN_VERSE
    A la fenêtre recélant
    Le santal vieux qui se dédore
    De sa viole étincelant
    Jadis avec flûte ou mandore,

    Est la Sainte pâle, étalant
    Le livre vieux qui se déplie
    Du Magnificat ruisselant
    Jadis selon vêpre et complie :

    A ce vitrage d’ostensoir
    Que frôle une harpe par l'Ange
    Formée avec son vol du soir
    Pour la délicate phalange

    Du doigt, que, sans le vieux santal
    Ni le vieux livre, elle balance
    Sur le plumage instrumental,
    Musicienne du silence.
#+END_VERSE
#+END_CENTER

** Ses purs ongles très-haut ...

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ses purs ongles très-haut dédiant leur onyx,
    L'Angoisse, ce minuit, soutient, lampadophore,
    Maint rêve vespéral brûlé par le Phénix
    Que ne recueille pas de cinéraire amphore

    Sur les crédences, au salon vide : nul ptyx,
    Aboli bibelot d’inanité sonore,
    (Car le Maître est allé puiser des pleurs au Styx
    Avec ce seul objet dont le Néant s’honore.)

    Mais proche la croisée au nord vacante, un or
    Agonise selon peut-être le décor
    Des licornes ruant du feu contre une nixe,

    Elle, défunte nue en le miroir, encor
    Que, dans l’oubli fermé par le cadre, se fixe
    De scintillations sitôt le septuor.
#+END_VERSE
#+END_CENTER

** Salut

#+BEGIN_CENTER
#+BEGIN_VERSE
    Rien, cette écume, vierge vers
    A ne désigner que la coupe ;
    Telle loin se noie une troupe
    De sirènes mainte à l’envers.

    Nous naviguons, ô mes divers
    Amis, moi déjà sur la poupe
    Vous l’avant fastueux qui coupe
    Le flot de foudres et d’hivers ;

    Une ivresse belle m’engage
    Sans craindre même son tangage
    De porter debout ce salut

    Solitude, récif, étoile
    A n’importe ce qui valut
    Le blanc souci de notre toile.
#+END_VERSE
#+END_CENTER

** Tristesse d'été

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le soleil, sur le sable, ô lutteuse endormie,
    En l’or de tes cheveux chauffe un bain langoureux
    Et, consumant l’encens sur ta joue ennemie,
    Il mêle avec les pleurs un breuvage amoureux.

    De ce blanc flamboiement l’immuable accalmie
    T’a fait dire, attristée, ô mes baisers peureux
    " Nous ne serons jamais une seule momie
    Sous l’antique désert et les palmiers heureux ! "

    Mais la chevelure est une rivière tiède,
    Où noyer sans frissons l'âme qui nous obsède
    Et trouver ce Néant que tu ne connais pas.

    Je goûterai le fard pleuré par tes paupières,
    Pour voir s’il sait donner au coeur que tu frappas
    L’insensibilité de l’azur et des pierres.
#+END_VERSE
#+END_CENTER

* Alfred de Musset

** A Laure

#+BEGIN_CENTER
#+BEGIN_VERSE
    Si tu ne m'aimais pas, dis-moi, fille insensée,
    Que balbutiais-tu dans ces fatales nuits ?
    Exerçais-tu ta langue à railler ta pensée ?
    Que voulaient donc ces pleurs, cette gorge oppressée,
    Ces sanglots et ces cris ?

    Ah ! si le plaisir seul t'arrachait ces tendresses,
    Si ce n'était que lui qu'en ce triste moment
    Sur mes lèvres en feu tu couvrais de caresses
    Comme un unique amant ;

    Si l'esprit et les sens, les baisers et les larmes,
    Se tiennent par la main de ta bouche à ton coeur,
    Et s'il te faut ainsi, pour y trouver des charmes,
    Sur l'autel du plaisir profaner le bonheur :

    Ah ! Laurette ! ah ! Laurette, idole de ma vie,
    Si le sombre démon de tes nuits d'insomnie
    Sans ce masque de feu ne saurait faire un pas,
    Pourquoi l'évoquais-tu, si tu ne m'aimais pas ?
#+END_VERSE
#+END_CENTER

** A Madame M...

#+BEGIN_CENTER
#+BEGIN_VERSE
    Vous m'envoyez, belle Emilie,
    Un poulet bien emmailloté ;
    Votre main discrète et polie
    L'a soigneusement cacheté.
    Mais l'aumône est un peu légère,
    Et malgré sa dextérité,
    Cette main est bien ménagère
    Dans ses actes de charité.
    C'est regarder à la dépense
    Si votre offrande est un paiement,
    Et si c'est une récompense,
    Vous n'aviez pas besoin d'argent.
    A l'avenir, belle Emilie,
    Si votre coeur est généreux,
    Aux pauvres gens, je vous en prie
    Faites l'aumône avec vos yeux.
    Quand vous trouverez le mérite,
    Et quand vous voudrez le payer,
    Souvenez-vous de Marguerite
    Et du poète Alain Chartier
    Il était bien laid, dit l'histoire,
    La dame était fille de roi ;
    Je suis bien obligé de croire
    Qu'il faisait mieux les vers que moi.
    Mais si ma plume est peu de chose,
    Mon coeur, hélas ! ne vaut pas mieux ;
    Fût-ce même pour de la prose
    Vos cadeaux sont trop dangereux.
    Que votre charité timide
    Garde son argent et son or,
    Car en ouvrant votre main vide
    Vous pouvez donner un trésor.
#+END_VERSE
#+END_CENTER

** Ballade à la lune

#+BEGIN_CENTER
#+BEGIN_VERSE
    C'était, dans la nuit brune,
    Sur le clocher jauni,
    La lune
    Comme un point sur un i.

    Lune, quel esprit sombre
    Promène au bout d'un fil,
    Dans l'ombre,
    Ta face et ton profil ?

    Es-tu l'oeil du ciel borgne ?
    Quel chérubin cafard
    Nous lorgne
    Sous ton masque blafard ?

    N'es-tu rien qu'une boule,
    Qu'un grand faucheux bien gras
    Qui roule
    Sans pattes et sans bras ?

    Es-tu, je t'en soupçonne,
    Le vieux cadran de fer
    Qui sonne
    L'heure aux damnés d'enfer ?

    Sur ton front qui voyage.
    Ce soir ont-ils compté
    Quel âge
    A leur éternité ?

    Est-ce un ver qui te ronge
    Quand ton disque noirci
    S'allonge
    En croissant rétréci ?

    Qui t'avait éborgnée,
    L'autre nuit ? T'étais-tu
    Cognée
    A quelque arbre pointu ?

    Car tu vins, pâle et morne
    Coller sur mes carreaux
    Ta corne
    À travers les barreaux.

    Va, lune moribonde,
    Le beau corps de Phébé
    La blonde
    Dans la mer est tombé.

    Tu n'en es que la face
    Et déjà, tout ridé,
    S'efface
    Ton front dépossédé.

    Rends-nous la chasseresse,
    Blanche, au sein virginal,
    Qui presse
    Quelque cerf matinal !

    Oh ! sous le vert platane
    Sous les frais coudriers,
    Diane,
    Et ses grands lévriers !

    Le chevreau noir qui doute,
    Pendu sur un rocher,
    L'écoute,
    L'écoute s'approcher.

    Et, suivant leurs curées,
    Par les vaux, par les blés,
    Les prées,
    Ses chiens s'en sont allés.

    Oh ! le soir, dans la brise,
    Phoebé, soeur d'Apollo,
    Surprise
    A l'ombre, un pied dans l'eau !

    Phoebé qui, la nuit close,
    Aux lèvres d'un berger
    Se pose,
    Comme un oiseau léger.

    Lune, en notre mémoire,
    De tes belles amours
    L'histoire
    T'embellira toujours.

    Et toujours rajeunie,
    Tu seras du passant
    Bénie,
    Pleine lune ou croissant.

    T'aimera le vieux pâtre,
    Seul, tandis qu'à ton front
    D'albâtre
    Ses dogues aboieront.

    T'aimera le pilote
    Dans son grand bâtiment,
    Qui flotte,
    Sous le clair firmament !

    Et la fillette preste
    Qui passe le buisson,
    Pied leste,
    En chantant sa chanson.

    Comme un ours à la chaîne,
    Toujours sous tes yeux bleus
    Se traîne
    L'océan montueux.

    Et qu'il vente ou qu'il neige
    Moi-même, chaque soir,
    Que fais-je,
    Venant ici m'asseoir ?

    Je viens voir à la brune,
    Sur le clocher jauni,
    La lune
    Comme un point sur un i.

    Peut-être quand déchante
    Quelque pauvre mari,
    Méchante,
    De loin tu lui souris.

    Dans sa douleur amère,
    Quand au gendre béni
    La mère
    Livre la clef du nid,

    Le pied dans sa pantoufle,
    Voilà l'époux tout prêt
    Qui souffle
    Le bougeoir indiscret.

    Au pudique hyménée
    La vierge qui se croit
    Menée,
    Grelotte en son lit froid,

    Mais monsieur tout en flamme
    Commence à rudoyer
    Madame,
    Qui commence à crier.

    " Ouf ! dit-il, je travaille,
    Ma bonne, et ne fais rien
    Qui vaille;
    Tu ne te tiens pas bien. "

    Et vite il se dépêche.
    Mais quel démon caché
    L'empêche
    De commettre un péché ?

    " Ah ! dit-il, prenons garde.
    Quel témoin curieux
    Regarde
    Avec ces deux grands yeux ? "

    Et c'est, dans la nuit brune,
    Sur son clocher jauni,
    La lune
    Comme un point sur un i.
#+END_VERSE
#+END_CENTER

** Chanson

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai dit à mon coeur, à mon faible coeur :
    N’est-ce point assez d’aimer sa maîtresse ?
    Et ne vois-tu pas que changer sans cesse,
    C’est perdre en désirs le temps du bonheur ?

    Il m’a répondu : Ce n’est point assez,
    Ce n’est point assez d’aimer sa maîtresse ;
    Et ne vois-tu pas que changer sans cesse
    Nous rend doux et chers les plaisirs passés ?

    J’ai dit à mon coeur, à mon faible coeur :
    N’est-ce point assez de tant de tristesse ?
    Et ne vois-tu pas que changer sans cesse,
    C’est à chaque pas trouver la douleur ?

    Il m’a répondu : Ce n’est point assez
    Ce n’est point assez de tant de tristesse ;
    Et ne vois-tu pas que changer sans cesse
    Nous rend doux et chers les chagrins passés ?
#+END_VERSE
#+END_CENTER

** Chanson de Barberine

#+BEGIN_CENTER
#+BEGIN_VERSE
    Beau chevalier qui partez pour la guerre,
    Qu'allez-vous faire
    Si loin d'ici ?
    Voyez-vous pas que la nuit est profonde,
    Et que le monde
    N'est que souci ?

    Vous qui croyez qu'une amour délaissée
    De la pensée
    S'enfuit ainsi,
    Hélas ! hélas ! chercheurs de renommée,
    Votre fumée
    S'envole aussi.

    Beau chevalier qui partez pour la guerre,
    Qu'allez-vous faire
    Si loin de nous ?
    J'en vais pleurer, moi qui me laissais dire
    Que mon sourire
    Etait si doux.
#+END_VERSE
#+END_CENTER

** La nuit

#+BEGIN_CENTER
#+BEGIN_VERSE
    Quand la lune blanche
    S'accroche à la branche
    Pour voir
    Si quelque feu rouge
    Dans l'horizon bouge
    Le soir,

    Fol alors qui livre
    A la nuit son livre
    Savant,
    Son pied aux collines,
    Et ses mandolines
    Au vent ;

    Fol qui dit un conte,
    Car minuit qui compte
    Le temps,
    Passe avec le prince
    Des sabbats qui grince
    Des dents.

    L'amant qui compare
    Quelque beauté rare
    Au jour,
    Tire une ballade
    De son coeur malade
    D'amour.

    Mais voici dans l'ombre
    Qu'une ronde sombre
    Se fait,
    L'enfer autour danse,
    Tous dans un silence
    Parfait.

    Tout pendu de Grève,
    Tout Juif mort soulève
    Son front,
    Tous noyés des havres
    Pressent leurs cadavres
    En rond.

    Et les âmes feues
    Joignent leurs mains bleues
    Sans os ;
    Lui tranquille chante
    D'une voix touchante
    Ses maux.

    Mais lorsque sa harpe,
    Où flotte une écharpe,
    Se tait,
    Il veut fuir... La danse
    L'entoure en silence
    Parfait.

    Le cercle l'embrasse,
    Son pied s'entrelace
    Aux morts,
    Sa tête se brise
    Sur la terre grise !
    Alors

    La ronde contente,
    En ris éclatante,
    Le prend ;
    Tout mort sans rancune
    Trouve au clair de lune
    Son rang.

    Car la lune blanche
    S'accroche à la branche
    Pour voir
    Si quelque feu rouge
    Dans l'horizon bouge
    Le soir.
#+END_VERSE
#+END_CENTER

** La nuit de décembre

#+BEGIN_CENTER
#+BEGIN_VERSE
    LE POÈTE

    Du temps que j'étais écolier,
    Je restais un soir à veiller
    Dans notre salle solitaire.
    Devant ma table vint s’asseoir
    Un pauvre enfant vêtu de noir,
    Qui me ressemblait comme un frère.

    Son visage était triste et beau :
    A la lueur de mon flambeau,
    Dans mon livre ouvert il vint lire.
    Il pencha son front sur sa main,
    Et resta jusqu’au lendemain,
    Pensif, avec un doux sourire.

    Comme j’allais avoir quinze ans
    Je marchais un jour, à pas lents,
    Dans un bois, sur une bruyère.
    Au pied d’un arbre vint s’asseoir
    Un jeune homme vêtu de noir,
    Qui me ressemblait comme un frère.

    Je lui demandai mon chemin ;
    Il tenait un luth d’une main,
    De l’autre un bouquet d'églantine.
    Il me fit un salut d’ami,
    Et, se détournant à demi,
    Me montra du doigt la colline.

    A l'âge où l’on croit à l’amour,
    J'étais seul dans ma chambre un jour,
    Pleurant ma première misère.
    Au coin de mon feu vint s’asseoir
    Un étranger vêtu de noir,
    Qui me ressemblait comme un frère.

    Il était morne et soucieux ;
    D’une main il montrait les cieux,
    Et de l’autre il tenait un glaive.
    De ma peine il semblait souffrir,
    Mais il ne poussa qu’un soupir,
    Et s'évanouit comme un rêve.

    A l'âge où l’on est libertin,
    Pour boire un toast en un festin,
    Un jour je soulevais mon verre.
    En face de moi vint s’asseoir
    Un convive vêtu de noir,
    Qui me ressemblait comme un frère.

    Il secouait sous son manteau
    Un haillon de pourpre en lambeau,
    Sur sa tête un myrte stérile.
    Son bras maigre cherchait le mien,
    Et mon verre, en touchant le sien,
    Se brisa dans ma main débile.

    Un an après, il était nuit ;
    J'étais à genoux près du lit
    Où venait de mourir mon père.
    Au chevet du lit vint s’asseoir
    Un orphelin vêtu de noir,
    Qui me ressemblait comme un frère.

    Ses yeux étaient noyés de pleurs ;
    Comme les anges de douleurs,
    Il était couronné d'épine ;
    Son luth à terre était gisant,
    Sa pourpre de couleur de sang,
    Et son glaive dans sa poitrine.

    Je m’en suis si bien souvenu,
    Que je l’ai toujours reconnu
    A tous les instants de ma vie.
    C’est une étrange vision,
    Et cependant, ange ou démon,
    J’ai vu partout cette ombre amie.

    Lorsque plus tard, las de souffrir,
    Pour renaître ou pour en finir,
    J’ai voulu m’exiler de France ;
    Lorsqu’impatient de marcher,
    J’ai voulu partir, et chercher
    Les vestiges d’une espérance ;

    A Pise, au pied de l'Apennin ;
    A Cologne, en face du Rhin ;
    A Nice, au penchant des vallées ;
    A Florence, au fond des palais ;
    A Brigues, dans les vieux chalets ;
    Au sein des Alpes désolées ;

    A Gênes, sous les citronniers ;
    A Vevey, sous les verts pommiers ;
    Au Havre, devant l'Atlantique ;
    A Venise, à l’affreux Lido,
    Où vient sur l’herbe d’un tombeau
    Mourir la pâle Adriatique ;

    Partout où, sous ces vastes cieux,
    J’ai lassé mon coeur et mes yeux,
    Saignant d’une éternelle plaie ;
    Partout où le boiteux Ennui,
    Traînant ma fatigue après lui,
    M’a promené sur une claie ;

    Partout où, sans cesse altéré
    De la soif d’un monde ignoré,
    J’ai suivi l’ombre de mes songes ;
    Partout où, sans avoir vécu,
    J’ai revu ce que j’avais vu,
    La face humaine et ses mensonges ;

    Partout où, le long des chemins,
    J’ai posé mon front dans mes mains,
    Et sangloté comme une femme ;
    Partout où j’ai, comme un mouton,
    Qui laisse sa laine au buisson,
    Senti se dénuder mon âme ;

    Partout où j’ai voulu dormir,
    Partout où j’ai voulu mourir,
    Partout où j’ai touché la terre,
    Sur ma route est venu s’asseoir
    Un malheureux vêtu de noir,
    Qui me ressemblait comme un frère.

    Qui donc es-tu, toi que dans cette vie
    Je vois toujours sur mon chemin ?
    Je ne puis croire, à ta mélancolie,
    Que tu sois mon mauvais Destin.
    Ton doux sourire a trop de patience,
    Tes larmes ont trop de pitié.
    En te voyant, j’aime la Providence.
    Ta douleur même est soeur de ma souffrance ;
    Elle ressemble à l'Amitié.

    Qui donc es-tu ? - Tu n’es pas mon bon ange,
    Jamais tu ne viens m’avertir.
    Tu vois mes maux (c’est une chose étrange !)
    Et tu me regardes souffrir.
    Depuis vingt ans tu marches dans ma voie,
    Et je ne saurais t’appeler.
    Qui donc es-tu, si c’est Dieu qui t’envoie ?
    Tu me souris sans partager ma joie,
    Tu me plains sans me consoler !

    Ce soir encor je t’ai vu m’apparaître.
    C'était par une triste nuit.
    L’aile des vents battait à ma fenêtre ;
    J'étais seul, courbé sur mon lit.
    J’y regardais une place chérie,
    Tiède encor d’un baiser brûlant ;
    Et je songeais comme la femme oublie,
    Et je sentais un lambeau de ma vie
    Qui se déchirait lentement.

    Je rassemblais des lettres de la veille,
    Des cheveux, des débris d’amour.
    Tout ce passé me criait à l’oreille
    Ses éternels serments d’un jour.
    Je contemplais ces reliques sacrées,
    Qui me faisaient trembler la main :
    Larmes du coeur par le coeur dévorées,
    Et que les yeux qui les avaient pleurées
    Ne reconnaîtront plus demain !

    J’enveloppais dans un morceau de bure
    Ces ruines des jours heureux.
    Je me disais qu’ici-bas ce qui dure,
    C’est une mèche de cheveux.
    Comme un plongeur dans une mer profonde,
    Je me perdais dans tant d’oubli.
    De tous côtés j’y retournais la sonde,
    Et je pleurais, seul, loin des yeux du monde,
    Mon pauvre amour enseveli.

    J’allais poser le sceau de cire noire
    Sur ce fragile et cher trésor.
    J’allais le rendre, et, n’y pouvant pas croire,
    En pleurant j’en doutais encor.
    Ah ! faible femme, orgueilleuse insensée,
    Malgré toi, tu t’en souviendras !
    Pourquoi, grand Dieu ! mentir à sa pensée ?
    Pourquoi ces pleurs, cette gorge oppressée,
    Ces sanglots, si tu n’aimais pas ?

    Oui, tu languis, tu souffres, et tu pleures ;
    Mais ta chimère est entre nous.
    Eh bien ! adieu ! Vous compterez les heures
    Qui me sépareront de vous.
    Partez, partez, et dans ce coeur de glace
    Emportez l’orgueil satisfait.
    Je sens encor le mien jeune et vivace,
    Et bien des maux pourront y trouver place
    Sur le mal que vous m’avez fait.

    Partez, partez ! la Nature immortelle
    N’a pas tout voulu vous donner.
    Ah ! pauvre enfant, qui voulez être belle,
    Et ne savez pas pardonner !
    Allez, allez, suivez la destinée ;
    Qui vous perd n’a pas tout perdu.
    Jetez au vent notre amour consumée ; -
    Eternel Dieu ! toi que j’ai tant aimée,
    Si tu pars, pourquoi m’aimes-tu ?

    Mais tout à coup j’ai vu dans la nuit sombre
    Une forme glisser sans bruit.
    Sur mon rideau j’ai vu passer une ombre ;
    Elle vient s’asseoir sur mon lit.
    Qui donc es-tu, morne et pâle visage,
    Sombre portrait vêtu de noir ?
    Que me veux-tu, triste oiseau de passage ?
    Est-ce un vain rêve ? est-ce ma propre image
    Que j’aperçois dans ce miroir ?

    Qui donc es-tu, spectre de ma jeunesse,
    Pèlerin que rien n’a lassé ?
    Dis-moi pourquoi je te trouve sans cesse
    Assis dans l’ombre où j’ai passé.
    Qui donc es-tu, visiteur solitaire,
    Hôte assidu de mes douleurs ?
    Qu’as-tu donc fait pour me suivre sur terre ?
    Qui donc es-tu, qui donc es-tu, mon frère,
    Qui n’apparais qu’au jour des pleurs ?

    LA VISION

    - Ami, notre père est le tien.
    Je ne suis ni l’ange gardien,
    Ni le mauvais destin des hommes.
    Ceux que j’aime, je ne sais pas
    De quel côté s’en vont leurs pas
    Sur ce peu de fange où nous sommes.

    Je ne suis ni dieu ni démon,
    Et tu m’as nommé par mon nom
    Quand tu m’as appelé ton frère ;
    Où tu vas, j’y serai toujours,
    Jusques au dernier de tes jours,
    Où j’irai m’asseoir sur ta pierre.

    Le ciel m’a confié ton coeur.
    Quand tu seras dans la douleur,
    Viens à moi sans inquiétude.
    Je te suivrai sur le chemin ;
    Mais je ne puis toucher ta main,
    Ami, je suis la Solitude.
#+END_VERSE
#+END_CENTER

** Namouna (extraits)

*** Chant premier

#+BEGIN_CENTER
#+BEGIN_VERSE
    I
    Le sofa sur lequel Hassan était couché
    Était dans son espèce une admirable chose.
    Il était de peau d’ours, — mais d’un ours bien léché ;
    Moelleux comme une chatte, et frais comme une rose
    Hassan avait d’ailleurs une très noble pose,
    Il était nu comme Ève à son premier péché.

    II
    Quoi ! tout nu ! dira-t-on, n’avait-il pas de honte ?
    Nu, dès le second mot !-Que sera-ce à la fin ?
    Monsieur, excusez-moi, — je commence ce conte
    Juste quand mon héros vient de sortir du bain
    Je demande pour lui l’indulgence, et j’y compte.
    Hassan était donc nu, — mais nu comme la main,

    III
    Nu comme un plat d’argent, — nu comme un mur d'église
    Nu comme le discours d’un académicien.
    Ma lectrice rougit, et je la scandalise.
    Mais comment se fait-il, madame, que l’on dise
    Que vous avez la jambe et la poitrine bien ?
    Comment le dirait-on, si l’on n’en savait rien

    IV
    Madame alléguera qu’elle monte en berline ;
    Qu’elle a passé les ponts quand il faisait du vent ;
    Que, lorsqu’on voit le pied, la jambe se devine ;
    Et tout le monde sait qu’elle a le pied charmant
    Mais moi qui ne suis pas du monde, j’imagine
    Qu’elle aura trop aimé quelque indiscret amant.

    V
    Et quel crime est-ce donc de se mettre à son aise,
    Quand on est tendrement aimée, — et qu’il fait chaud ?
    On est si bien tout nu, dans une large chaise !
    Croyez-m’en, belle dame, et, ne vous en déplaise,
    Si vous m’apparteniez, vous y seriez bientôt.
    Vous en crieriez sans doute un peu, — mais pas bien haut,

    VI
    Dans un objet aimé qu’est-ce donc que l’on aime ?
    Est-ce du taffetas ou du papier gommé ?
    Est-ce un bracelet d’or, un peigne parfumé ?
    Non, — ce qu’on aime en vous, madame, c’est vous même.
    La parure est une arme, et le bonheur suprême,
    Après qu’on a vaincu, c’est d’avoir désarmé.

    VII
    Tout est nu sur la terre, hormis l’hypocrisie ;
    Tout est nu dans les cieux, tout est nu dans la vie,
    Les tombeaux, les enfants et les divinités.
    Tous les cœurs vraiment beaux laissent voir leurs beautés
    Ainsi donc le héros de cette comédie
    Restera nu, madame, — et vous y consentez.
#+END_VERSE
#+END_CENTER

*** Chant deuxième

#+BEGIN_CENTER
#+BEGIN_VERSE
    I
    Eh bien ! en vérité, les sots auront beau dire,
    Quand on n’a pas d’argent, c’est amusant d'écrire.
    Si c’est un passe-temps pour se désennuyer,
    Il vaut bien la bouillotte ; et, si c’est un métier,
    Peut-être qu’après tout ce n’en est pas un pire
    Que fille entretenue, avocat ou portier

    II
    J’aime surtout les vers, cette langue immortelle.
    C’est peut-être un blasphème, et je le dis tout bas
    Mais je l’aime à la rage. Elle a cela pour elle
    Que les sots d’aucun temps n’en ont pu faire cas,
    Qu’elle nous vient de Dieu, — qu’elle est limpide et belle,
    Que le monde l’entend, et ne la parle pas.

    .......

    VIII
    Aujourd’hui par exemple, il plait à ma cervelle
    De rimer en sixains le conte que voici,
    Va-t-on le maltraiter et lui chercher querelle ?
    Est-ce sa faute, à lui, si je l'écris ainsi ?
    « Byron, me direz-vous, m’a servi de modèle. »
    Vous ne savez donc pas qu’il imitait Pulci ?

    IX
    Lisez les Italiens, vous verrez s’il les vole.
    Rien n’appartient à rien, tout appartient à tous.
    Il faut être ignorant comme un maître d'école
    Pour se flatter de dire une seule parole
    Que personne ici-bas n’ait pu dire avant vous.
    C’est imiter quelqu’un que de planter des choux.

    .......

    XII
    Pourquoi donc les amants veillent-ils nuit et jour ?
    Pourquoi donc le poète aime-t-il sa souffrance ?
    Que demandent-ils donc tous les deux en retour ?
    Une larme, ô mon Dieu, voilà leur récompense ;
    Voilà pour eux le ciel ; la gloire et l'éloquence,
    Et par là le génie est semblable à l’amour.

    XIII
    Mon premier chant est fait. — Je viens de le relire.
    J’ai bien mal expliqué ce que je voulais dire ;
    Je n’ai pas dit un mot de ce que j’aurais dit
    Si j’avais fait un plan une heure avant d'écrire ;
    Je crève de dégoût, de rage et de dépit
    Je crois en vérité que j’ai fait de l’esprit
#+END_VERSE
#+END_CENTER

*** Chant troisième

#+BEGIN_CENTER
#+BEGIN_VERSE
    I
    Je jure devant Dieu que mon unique envie
    Etait de raconter une histoire suivie.
    Le sujet de ce conte avait quelque douceur,
    Et mon héros peut-être eût su plaire au lecteur.
    J’ai laissé s’envoler ma plume avec sa vie,
    En voulant prendre au vol les rêves de son cœur.

    II
    Je reconnais bien là ma tactique admirable.
    Dans tout ce que je fais j’ai la triple vertu
    D'être à la fois trop court, trop long, et décousu.
    Le poème et le plan, les héros et la fable,
    Tout s’en va de travers, comme sur une table
    Un plat cuit d’un côté, pendant que l’autre est cru.

    .......

    IV
    Mes amis à présent me conseillent d’en rire,
    De couper sous l’archet les cordes de ma lyre,
    Et de remettre au vert Hassan et Namouna.
    Mais j’ai dit que l’histoire existait, — la voilà.
    Puisqu’en son temps et lieu je n’ai pas pu l'écrire,
    Je vais la raconter ; l'écrira qui voudra.
#+END_VERSE
#+END_CENTER

* Gérard de Nerval

** Artémis

#+BEGIN_CENTER
#+BEGIN_VERSE
    La Treizième revient... C’est encor la première ;
    Et c’est toujours la Seule, - ou c’est le seul moment :
    Car es-tu Reine, ô Toi! la première ou dernière ?
    Es-tu Roi, toi le seul ou le dernier amant ? ...

    Aimez qui vous aima du berceau dans la bière ;
    Celle que j’aimai seul m’aime encor tendrement :
    C’est la Mort - ou la Morte... Ô délice ! ô tourment !
    La rose qu’elle tient, c’est la Rose trémière.

    Sainte napolitaine aux mains pleines de feux,
    Rose au coeur violet, fleur de sainte Gudule,
    As-tu trouvé ta Croix dans le désert des cieux ?

    Roses blanches, tombez ! vous insultez nos Dieux,
    Tombez, fantômes blancs, de votre ciel qui brûle :
    - La sainte de l’abîme est plus sainte à mes yeux !
#+END_VERSE
#+END_CENTER

** Caligula - Ier chant

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’hiver s’enfuit ; le printemps embaumé
    Revient suivi des Amours et de Flore ;
    Aime demain qui n’a jamais aimé,
    Qui fut amant, demain le soit encore !

    Hiver était le seul maître des temps,
    Lorsque Vénus sortit du sein de l’onde ;
    Son premier souffle enfanta le printemps,
    Et le printemps fit éclore le monde.

    L'été brûlant a ses grasses moissons,
    Le riche automne a ses treilles encloses,
    L’hiver frileux son manteau de glaçons,
    Mais le printemps a l’amour et les roses.

    L’hiver s’enfuit, le printemps embaumé
    Revient suivi des Amours et de Flore ;
    Aime demain qui n’a jamais aimé,
    Qui fut amant, demain le soit encore !
#+END_VERSE
#+END_CENTER

** Delfica

#+BEGIN_CENTER
#+BEGIN_VERSE
    La connais-tu, Dafné, cette ancienne romance
    Au pied du sycomore, ou sous les lauriers blancs,
    Sous l’olivier, le myrte, ou les saules tremblants
    Cette chanson d’amour qui toujours recommence ? ...

    Reconnais-tu le TEMPLE au péristyle immense,
    Et les citrons amers où s’imprimaient tes dents,
    Et la grotte, fatale aux hôtes imprudents,
    Où du dragon vaincu dort l’antique semence ? ..

    Ils reviendront, ces Dieux que tu pleures toujours !
    Le temps va ramener l’ordre des anciens jours ;
    La terre a tressailli d’un souffle prophétique ...

    Cependant la sibylle au visage latin
    Est endormie encor sous l’arc de Constantin
    - Et rien n’a dérangé le sévère portique.
#+END_VERSE
#+END_CENTER

** El Desdichado

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je suis le Ténébreux, - le Veuf, - l'Inconsolé,
    Le Prince d'Aquitaine à la Tour abolie :
    Ma seule Étoile est morte, - et mon luth constellé
    Porte le Soleil noir de la Mélancolie.

    Dans la nuit du Tombeau, Toi qui m’as consolé,
    Rends-moi le Pausilippe et la mer d'Italie,
    La fleur qui plaisait tant à mon coeur désolé,
    Et la treille où le Pampre à la Rose s’allie.

    Suis-je Amour ou Phoebus ?... Lusignan ou Biron ?
    Mon front est rouge encor du baiser de la Reine ;
    J’ai rêvé dans la Grotte où nage la Sirène...

    Et j’ai deux fois vainqueur traversé l'Achéron :
    Modulant tour à tour sur la lyre d'Orphée
    Les soupirs de la Sainte et les cris de la Fée.
#+END_VERSE
#+END_CENTER

** Myrtho

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je pense à toi, Myrtho, divine enchanteresse,
    Au Pausilippe altier, de mille feux brillant,
    À ton front inondé des clartés de l'Orient,
    Aux raisins noirs mêlés avec l’or de ta tresse.

    C’est dans ta coupe aussi que j’avais bu l’ivresse,
    Et dans l'éclair furtif de ton oeil souriant,
    Quand aux pieds d’lacchus on me voyait priant,
    Car la Muse m’a fait l’un des fils de la Grèce.

    Je sais pourquoi là-bas le volcan s’est rouvert...
    C’est qu’hier tu l’avais touché d’un pied agile,
    Et de cendres soudain l’horizon s’est couvert.

    Depuis qu’un duc normand brisa tes dieux d’argile,
    Toujours, sous les rameaux du laurier de Virgile,
    Le pâle hortensia s’unit au myrte vert !
#+END_VERSE
#+END_CENTER

* Charles d'Orléans

** Le temps a laissé son manteau

*** En français moderne

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le temps a laissé son manteau.
    De vent, de froidure et de pluie,
    Et s’est vêtu de broderie,
    De soleil luisant, clair et beau.

    Il n’y a bête, ni oiseau
    Qu’en son jargon ne chante ou crie :
    Le temps a laissé son manteau
    De vent, de froidure et de pluie.

    Rivière, fontaine et ruisseau
    Portent en livrée jolie,
    Gouttes d’argent d’orfèvrerie,
    Chacun s’habille de nouveau :
    Le temps a laissé son manteau.
    De vent, de froidure et de pluie.
#+END_VERSE
#+END_CENTER

*** En ancien français

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le temps a laissié son manteau
    De vent, de froidure et de pluye,
    Et s’est vestu de brouderie,
    De soleil luyant, cler et beau.

    Il n’y a beste ne oyseau,
    Qu’en son jargon ne chante ou crie ;
    Le temps a laissié son manteau
    De vent, de froidure et de pluye.

    Rivière, fontaine et ruisseau
    Portent, en livree jolie,
    Gouttes d’argent d’orfaverie,
    Chascun s’abille de nouveau :
    Le temps a laissié son manteau.
    De vent, de froidure et de pluye.
#+END_VERSE
#+END_CENTER

* Maurice Rollinat

** À l'inaccessible

#+BEGIN_CENTER
#+BEGIN_VERSE
    Argile toujours vierge, inburinable airain,
    Magicien masqué plus tyran que la femme,
    Art ! Terrible envoûteur qui martyrise l’âme,
    Railleur mystérieux de l’esprit pèlerin !

    Il n’est pas de poète insoumis à ton frein
    Et tous ceux dont la gloire ici-bas te proclame
    Savent que ton autel épuisera leur flamme
    Et qu’ils récolteront ton mépris souverain.

    Rageuse inquiétude et patience blême
    Usent leurs ongles d’or à fouiller ton problème ;
    L’homme évoque pourtant ton mirage moqueur ;

    Longuement il te cherche et te poursuit sans trêve,
    Abîme où s’engloutit la tendresse du coeur,
    Zénith où cogne en vain l’avidité du rêve !
#+END_VERSE
#+END_CENTER

** À quoi pense la nuit

#+BEGIN_CENTER
#+BEGIN_VERSE
    À quoi pense la Nuit, quand l'âme des marais
    Monte dans les airs blancs sur tant de voix étranges,
    Et qu’avec des sanglots qui font pleurer les anges
    Le rossignol module au milieu des forêts !...

    À quoi pense la Nuit, lorsque le ver luisant
    Allume dans les creux des frissons d'émeraude,
    Quand murmure et parfum, comme un zéphyr qui rôde,
    Traversent l’ombre vague où la tiédeur descend ?...

    Elle songe en mouillant la terre de ses larmes
    Qu’elle est plus belle, ayant le mystère des charmes,
    Que le jour regorgeant de lumière et de bruit.

    Et - ses grands yeux ouverts aux étoiles - la Nuit
    Enivre de secret ses extases moroses,
    Aspire avec longueur le magique des choses.
#+END_VERSE
#+END_CENTER

** La blanchisseuse du paradis

#+BEGIN_CENTER
#+BEGIN_VERSE
    Au son de musiques étranges
    De harpes et de clavecins,
    Tandis que flottent par essaims
    Les cantiques et les louanges,

    Elle blanchit robes et langes
    Dans l’eau bénite des bassins,
    Au son de musiques étranges
    De harpes et de clavecins.

    Et les bienheureuses phalanges
    Peuvent la voir sur des coussins
    Repassant les surplis des saints
    Et les collerettes des anges,
    Au son de musiques étranges.
#+END_VERSE
#+END_CENTER

** Le fou

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je rêve un pays rouge et suant le carnage,
    Hérissé d’arbres verts en forme d'éteignoir,
    Des calvaires autour, et dans le voisinage
    Un étang où pivote un horrible entonnoir.

    Farouche et raffolant des donjons moyen âge,
    J’irais m’ensevelir au fond d’un vieux manoir :
    Comme je humerais le mystère qui nage
    Entre de vastes murs tendus de velours noir !

    Pour jardins, je voudrais deux ou trois cimetières
    Où je pourrais tout seul rôder des nuits entières ;
    Je m’y promènerais lugubre et triomphant,

    Escorté de lézards gros comme ceux du Tigre.
    - Oh ! fumer l’opium dans un crâne d’enfant,
    Les pieds nonchalamment appuyés sur un tigre !
#+END_VERSE
#+END_CENTER

** Les arbres

#+BEGIN_CENTER
#+BEGIN_VERSE
    Arbres, grands végétaux, martyrs des saisons fauves,
    Sombres lyres des vents, ces noirs musiciens,
    Que vous soyez feuillus ou que vous soyez chauves,
    Le poète vous aime et vos spleens sont les siens.

    Quand le regard du peintre a soif de pittoresque,
    C’est à vous qu’il s’abreuve avec avidité,
    Car vous êtes l’immense et formidable fresque
    Dont la terre sans fin pare sa nudité.

    De vous un magnétisme étrange se dégage,
    Plein de poésie âpre et d’amères saveurs ;
    Et quand vous bruissez, vous êtes le langage
    Que la nature ébauche avec les grands rêveurs.

    Quand l'éclair et la foudre enflent rafale et grêle,
    Les forêts sont des mers dont chaque arbre est un flot,
    Et tous, le chêne énorme et le coudrier grêle,
    Dans l’opaque fouillis poussent un long sanglot.

    Alors, vous qui parfois, muets comme des marbres,
    Vous endormez, pareils à des cœurs sans remords,
    Vous tordez vos grands bras, vous hurlez, pauvres arbres,
    Sous l’horrible galop des éléments sans mors.

    L'été, plein de langueur, l’oiseau clôt ses paupières
    Et dort paisiblement sur vos mouvants hamacs,
    Vous êtes les écrans des herbes et des pierres
    Et vous mêlez votre ombre à la fraîcheur des lacs.

    Et quand la canicule, aux vivants si funeste,
    Pompe les étangs bruns, miroirs des joncs fluets,
    Dans l’atmosphère lourde où fermente la peste,
    Vous immobilisez vos branchages muets.

    Votre mélancolie, à la fin de l’automne,
    Est pénétrante, alors que sans fleurs et sans nids,
    Sous un ciel nébuleux où d’heure en heure il tonne,
    Vous semblez écrasés par vos rameaux jaunis.

    Les seules nuits de mai, sous les rayons stellaires,
    Aux parfums dont la terre emplit ses encensoirs,
    Vous oubliez parfois vos douleurs séculaires
    Dans un sommeil bercé par le zéphyr des soirs.

    Une brume odorante autour de vous circule
    Quand l’aube a dissipé la nocturne stupeur,
    Et, quand vous devenez plus grands au crépuscule,
    Le poète frémit comme s’il avait peur.

    Sachant qu’un drame étrange est joué sous vos dômes,
    Par les bêtes le jour, par les spectres la nuit,
    Pour voir rôder les loups et glisser les fantômes,
    Vos invisibles yeux s’ouvrent au moindre bruit.

    Et le soleil vous mord, l’aquilon vous cravache,
    L’hiver vous coud tout vifs dans un froid linceul blanc,
    Et vous souffrez toujours jusqu'à ce que la hache
    Taillade votre chair et vous tranche en sifflant.

    Partout où vous vivez, chênes, peupliers, ormes,
    Dans les cités, aux champs, et sur les rocs déserts,
    Je fraternise avec les tristesses énormes
    Que vos sombres rameaux épandent par les airs.
#+END_VERSE
#+END_CENTER

** Les infinis

#+BEGIN_CENTER
#+BEGIN_VERSE
    Vertigineux géant du désert qu’il écrase,
    La tête dans l’azur et le pied dans la mer,
    Le mont découpe, ardent, sous le dôme de l’air,
    Son farouche horizon de chaos en extase.

    Le vide où, par instants, des vents de feu circulent,
    Tend son gouffre comblé par son rutilement ;
    L’onde et la nue, ayant même bleuissement,
    Face à face vibrants, s'éblouissent et brûlent.

    Là, ce que la Nature a de plus éternel :
    L'Espace, l'Océan, la Montagne, le Ciel,
    Souffre pompeusement la lumière embrasée :

    Puis, la Nuit vient, gazant sous ses voiles bénis
    La Lune, spectre errant de ces quatre infinis
    Qui boivent les soupirs de son âme glacée.
#+END_VERSE
#+END_CENTER

** Les meules de foin

#+BEGIN_CENTER
#+BEGIN_VERSE
    Tout le sol tondu ras des solitudes plates
    Dans un indéfini recul, toujours plus loin,
    S'étale montueux de ses meules de foin
    Où saigne le soleil croulé qui se dilate.

    Solennelle, pompeuse, avec la nuit qui poind,
    D’un morne extasié, leur masse rouge éclate,
    Puis, blêmissant, devient l’horizon spectre, et joint
    La ligne des cieux blancs de sa cime écarlate.

    Stagnant dans l’air croupi, ces meules en sommeil,
    Lentement, goutte à goutte, ont tari le soleil
    De ses pourpres de sang dont la dernière est bue.

    Maintenant, la hideuse et moite obscurité
    Comble, débosse, fond, brouille l’immensité
    Qui bâille l’ombre informe où s’engloutit la vue.
#+END_VERSE
#+END_CENTER

** Les seins

#+BEGIN_CENTER
#+BEGIN_VERSE
    J’ai fait ces vers subtils, polis comme des bagues,
    Pour immortaliser la gloire de tes seins
    Que mon houleux désir bat toujours de ses vagues.

    Qu’ils y fleurissent donc éternellement sains,
    Et que dans la roideur fière des pics de glace
    Ils narguent à jamais les siècles assassins !

    Sur ta chemise, enfant, mon œil baise la place
    Qu’use le frottement de leurs boutons rosés,
    Et voilà que déjà le vertige m’enlace.

    Si j’osais ! Tu souris, semblant me dire : « Osez !
    Mes seins voluptueux sont friands de vos lèvres
    Et de larmes d’amour veulent être arrosés. »

    Et pour m’indemniser des nuits où tu m’en sèvres,
    Tu ne les caches plus que sous tes noirs cheveux
    Drus comme les buissons que mordillent les chèvres.

    Ivresse ! Ils sont alors à moi tant que je veux :
    Car mes doigts chatouilleurs ont des caresses lentes
    S’entrecoupant d’arrêts et de frissons nerveux.

    Et quand vibrent sur vous mes lèvres harcelantes,
    Libellules d’amour dont vous êtes les fleurs,
    Votre incarnat rougit, pointes ensorcelantes !

    Rubis des seins, vous en rehaussez les pâleurs
    Et vous vous aiguisez, jusqu'à piquer ma joue
    Comme le bec lutin des oiselets siffleurs.

    Et tu frémis avec une adorable moue
    Tandis qu’au cliquetis de tes bracelets d’or
    Ta main dans ma crinière indomptable se joue !

    En vain la bise hurle au fond du corridor,
    Tu souris de langueur sur le sopha d'ébène
    Devant l'âtre paisible où la flamme s’endort.

    Moi, je brûle affolé, je me contiens à peine ;
    Et pourtant mon désir qui rampe à tes genoux
    Sait que sa patience a toujours bonne aubaine.

    Mais tu laisses tomber ton provocant burnous,
    Et, moderne houri des paradis arabes,
    Tu bondis toute nue en criant : « Aimons-nous ! »

    Oh ! comme nous râlons ces magiques syllabes,
    Dans la chère seconde où, pour mieux s’enlacer,
    Nos jambes et nos bras sont des pinces de crabes !

    Ma convoitise enfin peut donc se harasser !
    Pas un coin de ton corps où mes lèvres ne paissent
    Tu me bois, je t’aspire ! et, pour me délasser,

    J’admire tes beaux seins qui s’enflent et s’abaissent.
#+END_VERSE
#+END_CENTER

** Magie de la nature

#+BEGIN_CENTER
#+BEGIN_VERSE
    Béant, je regardais du seuil d’une chaumière
    De grands sites muets, mobiles et changeants,
    Qui, sous de frais glacis d’ambre, d’or et d’argent,
    Vivaient un infini d’espace et de lumière.

    C'étaient des fleuves blancs, des montagnes mystiques.
    Des rocs pâmés de gloire et de solennité,
    Des chaos engendrant de leur obscurité
    Des éblouissements de forêts élastiques.

    Je contemplais, noyé d’extase, oubliant tout,
    Lorsqu’ainsi qu’une rose énorme, tout à coup,
    La Lune, y surgissant, fleurit ces paysages.

    Un tel charme à ce point m’avait donc captivé
    Que j’avais bu des yeux, comme un aspect rêvé,
    La simple vision du ciel et des nuages !
#+END_VERSE
#+END_CENTER

* Edmond Rostand

** Cyrano de Bergerac (extraits)

*** Acte I

#+BEGIN_CENTER
#+BEGIN_VERSE
    – Ay – Je cherchais un gant ! – Vous trouvez une main.

    .......

    – Messieurs ! – Mais jouez donc ! – Gros homme si tu joues
    Je vais être obligé de te fesser les joues !

    .......

    Je vous en prie, ayez pitié de mon fourreau :
    Si vous continuez, il va rendre sa lame !

    .......

    La pudeur vous défend de voir ma lame nue ?
    Pas un nom ? — Pas un doigt ? — C’est bien. Je continue.

    .......

    Amical : « Mais il doit tremper dans votre tasse
    Pour boire, faites-vous fabriquer un hanap ! »
    Descriptif : « C’est un roc !... c’est un pic !... c’est un cap !
    Que dis-je, c’est un cap ?... C’est une péninsule ! »
    Curieux : « De quoi sert cette oblongue capsule ?
    D'écritoire, monsieur, ou de boîtes à ciseaux ? »
    Gracieux : « Aimez-vous à ce point les oiseaux
    Que paternellement vous vous préoccupâtes
    De tendre ce perchoir à leurs petites pattes ? »
    Truculent : « Cà, monsieur, lorsque vous pétunez,
    La vapeur du tabac vous sort-elle du nez
    Sans qu’un voisin ne crie au feu de cheminée ? »
    Prévenant : « Gardez-vous, votre tête entraînée
    Par ce poids, de tomber en avant sur le sol ! »
    Tendre : « Faites-lui faire un petit parasol
    De peur que sa couleur au soleil ne se fane ! »
    Pédant : « L’animal seul, monsieur, qu'Aristophane
    Appelle Hippocampelephantocamélos
    Dut avoir sous le front tant de chair sur tant d’os ! »
    Cavalier : « Quoi, l’ami, ce croc est à la mode ?
    Pour pendre son chapeau, c’est vraiment très commode ! »
    Emphatique : « Aucun vent ne peut, nez magistral,
    T’enrhumer tout entier, excepté le mistral ! »
    Dramatique : « C’est la Mer Rouge quand il saigne ! »
    Admiratif : « Pour un parfumeur, quelle enseigne ! »
    Lyrique : « Est-ce une conque, êtes-vous un triton ? »
    Naïf : « Ce monument, quand le visite-t-on ? »
    Respectueux : « Souffrez, monsieur, qu’on vous salue,
    C’est là ce qui s’appelle avoir pignon sur rue ! »
    Campagnard : « Hé, ardé ! C’est-y un nez ? Nanain !
    C’est queuqu’navet géant ou ben queuqu’melon nain ! »
    Militaire : « Pointez contre cavalerie !" »
    Pratique : « Voulez-vous le mettre en loterie ?
    Assurément, monsieur, ce sera le gros lot ! »
    Enfin parodiant Pyrame en un sanglot
    « Le voilà donc ce nez qui des traits de son maître
    A détruit l’harmonie ! Il en rougit, le traître ! »
    – Voilà ce qu'à peu près, mon cher, vous m’auriez dit
    Si vous aviez un peu de lettres et d’esprit

    .......

    Je me les sers moi-même, avec assez de verve,
    Mais je ne permets pas qu’un autre me les serve.

    .......

    Mais je suis plus soigné si je suis moins coquet ;

    .......

    « Ballade du duel qu’en l’hôtel bourguignon
    Monsieur de Bergerac eut avec un bélître ! »

    .......

    Je jette avec grâce mon feutre,
    Je fais lentement l’abandon
    Du grand manteau qui me calfeutre,
    Et je tire mon espadon ;
    Elégant comme Céladon,
    Agile comme Scaramouche,
    Je vous préviens, cher Mirmydon,
    Qu'à la fin de l’envoi je touche !

    Vous auriez bien dû rester neutre ;
    Où vais-je vous larder, dindon ?...
    Dans le flanc, sous votre maheutre ?...
    Au coeur, sous votre bleu cordon ?...
    – Les coquilles tintent, ding-don !
    Ma pointe voltige : une mouche !
    Décidément... c’est au bedon,
    Qu'à la fin de l’envoi je touche.

    Il me manque une rime en eutre...
    Vous rompez, plus blanc qu’amidon ?
    C’est pour me fournir le mot pleutre !
    — Tac ! je pare la pointe dont
    Vous espériez me faire don : —
    J’ouvre la ligne, — je la bouche...
    Tiens bien ta broche, Laridon !
    A la fin de l’envoi, je touche.

    Prince, demande à Dieu pardon !
    Je quarte du pied, j’escarmouche,
    je coupe, je feinte... Hé ! là donc
    A la fin de l’envoi, je touche.

    .......

    C’est un héros !... – Monsieur, voulez-vous me permettre ?...
    C’est tout à fait très bien, et je crois m’y connaître ;
    J’ai du reste exprimé ma joie en trépignant !...
    – Comment s’appelle donc ce monsieur ? – D'Artagnan.

    .......

    Et je le hais depuis qu’il se permit, un soir,
    De poser son regard, sur celle... Oh ! j’ai cru voir
    Glisser sur une fleur une longue limace !
    – Hein ? Comment ? Serait-il possible ?... – Que j’aimasse ?...
    J’aime. – Et peut-on savoir ? Tu ne m’a jamais dit ?...
    – Qui j’aime ?... Réfléchis, voyons. Il m’interdit
    Le rêve d'être aimé même par une laide,
    Ce nez qui d’un quart d’heure en tous lieux me précède ;
    Alors moi, j’aime qui ?... Mais cela va de soit !
    J’aime — mais c’est forcé ! — la plus belle qui soit !

    .......

    Eh, mon Dieu, quelle est donc cette femme ?... – Un danger
    Mortel sans le vouloir, exquis sans y songer,
    Un piège de nature, une rose muscade
    Dans laquelle l’amour se tient en embuscade !

    .......

    Venez tous, le Docteur, Isabelle, Léandre,
    Tous ! Car vos allez joindre, essaim charmant et fol,
    La farce italienne à ce drame espagnol,
    Et sur son ronflement tintant un bruit fantasque,
    L’entourer de grelots comme un tambour de basque !...

    .......

    Ah !... Paris fuit, nocturne et quasi nébuleux ;
    Le clair de lune coule aux pentes des toits bleus ;
    Un cadre se prépare, exquis, pour cette scène ;
    Là-bas, sous des vapeurs en écharpe, la Seine,
    Comme un mystérieux et magique miroir,
    Tremble... Et vous allez voir ce que vous allez voir !

    .......

    Ne demandiez-vous pas pourquoi, mademoiselle,
    Contre ce seul rimeur cent hommes furent mis ?
    C’est parce qu’on savait qu’il est de mes amis !
#+END_VERSE
#+END_CENTER

*** Acte II

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sur les cuivres, déjà, glisse l’argent de l’aube !
    Etouffe en toi le dieu qui chante, Ragueneau !
    L’heure du luth viendra, — c’est l’heure du fourneau !

    .......

    Tandis qu’en écrivant... Eh bien ! écrivons-là,
    Cette lettre d’amour qu’en moi-même j’ai faite
    Et refaite cent fois, de sorte qu’elle est prête,
    Et que mettant mon âme à côté du papier,
    Je n’ai tout simplement qu'à la recopier.

    .......

    Ce pain d'épice suit le rimeur famélique,
    De ses yeux en amande aux sourcils d’angélique !

    .......

    Euh ! pour des yeux vainqueurs, je les trouve battus.
    – Mais... – Ragueneau me plaît. C’est pourquoi, dame Lise,
    Je défends que quelqu’un le ridicoculise.

    .......

    Que l’instant entre tous les instants soit béni,
    Où, cessant d’oublier qu’humblement je respire
    Vous venez jusqu’ici pour me dire... me dire ?...

    .......

    Roxane, en jupons courts, s’appelait Madeleine...
    – J'étais jolie, alors ? – Vous n'étiez pas vilaine.

    .......

    Et, dites-moi, — pendant que j'ôte un peu le sang, —
    Ils étaient contre vous ? – Oh ! pas tout à fait cent.

    .......

    Ce sont les cadets de Gascogne
    De Carbon de Castel-Jaloux ;
    Bretteurs et menteurs sans vergogne,
    Ce sont les cadets de Gascogne !
    Parlant blason, lambel, bastogne,
    Tous plus nobles que des filous,
    Ce sont les cadets de Gascogne
    De Carbon de Castel-Jaloux

    Oeil d’aigle, jambe de cigogne,
    Moustache de chat, dents de loups,
    Fendant la canaille qui grogne,
    Oeil d’aigle, jambe de cigogne,
    Ils vont, — coiffés d’un vieux vigogne
    Dont la plume cache les trous ! —
    Oeil d’aigle, jambe de cigogne,
    Moustache de chat, dents de loups !

    Perce-Bedaine et Casse-Trogne
    Sont leurs sobriquets les plus doux ;
    De gloire, leur âme est ivrogne !
    Perce-Bedaine et Casse-Trogne,
    Dans tous les endroits où l’on cogne
    Ils se donnent des rendez-vous...
    Perce-Bedaine et Casse-Trogne
    Sont leurs sobriquets les plus doux !

    Voici les cadets de Gascogne
    Qui font cocus tous les jaloux !
    O femme, adorable carogne,
    Voici les cadets de Gascogne !
    Que le vieil époux se renfrogne
    Sonnez, clairons ! chantez, coucous !
    Voici les cadets de Gascogne
    Qui font cocus tous les jaloux !

    .......

    Un poète est un luxe, aujourd’hui, qu’on se donne.
    – Voulez-vous être à moi ? – Non, Monsieur, à personne.

    .......

    – Car lorsqu’on les attaque, il arrive souvent...
    – J’attaque donc des gens qui tournent à tout vent ?
    – Qu’un moulinet de leurs grands bras chargés de toiles
    Vous lance dans la boue !... – Ou bien dans les étoiles !

    .......

    Dans l’espoir vil de voir, aux lèvres d’un ministre,
    Naître un sourire, enfin, qui ne soit pas sinistre ?

    .......

    S’aller faire nommer pape par les conciles
    Que dans les cabarets tiennent des imbéciles ?
    Non, merci ! Travailler à se construire un nom
    Sur un sonnet, au lieu d’en faire d’autres ? Non,
    Merci ! Ne découvrir du talent qu’aux mazettes ?

    .......

    Lors même qu’on n’est pas le chêne ou le tilleul,
    Ne pas monter bien haut, peut-être, mais tout seul !

    .......

    Quelle aberration ! – Eh bien ! oui, c’est mon vice.
    Déplaire est mon plaisir. J’aime qu’on me haïsse.

    .......

    – On ne peut faire, sans défuncter avant l'âge,
    La moindre allusion au fatal cartilage !
    – Un mot suffit ! Que dis-je, un mot ? Un geste, un seul !
    Et tirer son mouchoir, c’est tirer son linceul !

    .......

    La lune, dans le ciel, luisait comme une montre,
    Quand soudain, je ne sais quel soigneux horloger
    S'étant mis à passer un coton nuager
    Sur le boîtier d’argent de cette montre ronde,
    Il se fit une nuit la plus noire du monde,
    Et les quais n'étant pas du tout illuminés,
    Mordious ! on n’y voyait pas plus loin... – Que son nez.

    .......

    J’en estomaque deux ! J’en empale un tout vif !
    Quelqu’un m’ajuste : Paf ! et je riposte... – Pif !

    .......

    Comment ? – Las ! je suis sot à m’en tuer de honte !
    – Mais non, tu ne l’es pas, puisque tu t’en rends compte.

    .......

    – Oh ! leurs yeux, quand je passe, ont pour moi des bontés...
    – Leurs coeurs n’en ont-ils plus quand vous vous arrêtez ?

    .......

    C’est une expérience à tenter un poète.
    Veux-tu me compléter et que je te complète ?
    Tu marcheras, j’irai dans l’ombre à ton côté
    Je serai ton esprit, tu seras ma beauté.

    .......

    Car nous sommes ceux-là qui pour amantes n’ont
    Que du rêve soufflé dans la bulle d’un nom !...
    Prends, et tu changeras en vérités ces feintes ;
    Je lançais au hasard ces aveux et ces plaintes
    Tu verras se poser tous ces oiseaux errants.
    Tu verras que je fus dans cette lettre — prends ! —
    D’autant plus éloquent que j'étais moins sincère !
#+END_VERSE
#+END_CENTER

*** Acte III

#+BEGIN_CENTER
#+BEGIN_VERSE
    Jusqu'à ce que Phoebus recommence son orbe,
    J’ai donc sur mes talons ces joueurs de théorbe,
    De tout ce que je fais harmonieux témoins !...
    Ce fut d’abord charmant, et ce l’est déjà moins.

    .......

    Plus fin diseur de ces jolis rien qui sont tout.

    .......

    Des ordres. On assiège Arras. - Ah !... on assiège ?...
    – Oui... Mon départ a l’air de vous laisser de neige.

    .......

    Oh ! voyez ! le heurtoir est entouré de linges !...
    On vous a bâillonné pour que votre métal
    Ne troublât pas les beaux discours, — petit brutal !

    .......

    Vous ne méritez pas... Mets-toi là, misérable !
    Là, devant le balcon ! Je me mettrai dessous...

    .......

    Joyeux pour une femme, et pour un homme, triste !

    .......

    Vos mots sont hésitants. Pourquoi ? – C’est qu’il fait nuit,
    Dans cette ombre, à tatons, ils cherchent votre oreille.
    – Les miens n'éprouvent pas difficulté pareille.
    – Ils trouvent tout de suite ? oh ! cela va de soi,
    Puisque c’est dans mon coeur, eux, que je les reçois ;
    Or, moi, j’ai le coeur grand, vous, l’oreille petite.
    D’ailleurs vos mots à vous descendent : ils vont plus vite,
    Les miens montent, Madame : il leur faut plus de temps !
    – Mais ils montent bien mieux depuis quelques instants.
    – De cette gymnastique, ils ont pris l’habitude !
    – Je vous parle en effet d’une vraie altitude !
    – Certes, et vous me tueriez si de cette hauteur
    Vous me laissiez tomber un mot dur sur le coeur !

    .......

    Mais oui, c’est adorable. On se devine à peine.
    Vous voyez la noirceur d’un long manteau qui traîne,
    J’aperçois la blancheur d’une robe d'été
    Moi je ne suis qu’une ombre, et vous qu’une clarté !

    .......

    Je pars pour décrocher l'étoile, et je m’arrête
    Par peur du ridicule, à cueillir la fleurette !

    .......

    Je crains tant que parmi notre alchimie exquise
    Le vrai du sentiment ne se volatilise,
    Que l'âme ne se vide à ces passe-temps vains,
    Et que le fin du fin ne soit la fin des fins !

    .......

    – Mais l’esprit ?... – Je le hais, dans l’amour ! C’est un crime
    Lorsqu’on aime de trop prolonger cette escrime !

    .......

    – Nous parlions de... de... d’un... – Baiser. Le mot est doux !
    Je ne vois pas pourquoi votre lèvre ne l’ose ;
    S’il la brûle déjà, que sera-ce la chose ?
    Ne vous en faites pas un épouvantement
    N’avez-vous pas tantôt, presque insensiblement,
    Quitté le badinage et glissé sans alarmes
    De sourire au soupir, et du soupir aux larmes !
    Glisser encore un peu d’insensible façon
    Des larmes au baiser il n’y a qu’un frisson !
    – Taisez-vous ! – Un baiser, mais à tout prendre, qu’est-ce ?
    Un serment fait d’un peu plus près, une promesse
    Plus précise, un aveu qui veut se confirmer,
    Un point rose qu’on met sur l’i du verbe aimer ;
    C’est un secret qui prend la bouche pour oreille,
    Un instant d’infini qui fait un bruit d’abeille,
    Une communication ayant un goût de fleur,
    Une façon d’un peu se respirer le coeur,
    Et d’un peu se goûter, au bord des lèvres, l'âme !

    .......

    – Ce masque !... – Je suis donc à Venise, ou dans Gêne ?
    – Une dame m’attend !... – Je suis donc à Paris.
    – Le drôle est assez drôle ! – Ah ! vous riez ? – Je ris,

    .......

    Me faire, par des feux sucessifs de salpêtre,
    Lancer dans les prés bleus où les astres vont paître !
#+END_VERSE
#+END_CENTER

*** Acte IV

#+BEGIN_CENTER
#+BEGIN_VERSE
    Rien de plus compliqué que ce siège d'Arras
    Nous assiégeons Arras, — nous-mêmes, pris au piège,
    Le cardinal infant d'Espagne nous assiège...
    – Quelqu’un devrait venir l’assiéger à son tour.

    .......

    Chapeau bas, tous ! – Du Roi ! — Rangez-vous, vile tourbe,
    Pour qu’il puisse décrire avec pompe sa courbe !

    .......

    Il est un peu petit. – Mais il est en dentelle !
#+END_VERSE
#+END_CENTER

*** Acte V

#+BEGIN_CENTER
#+BEGIN_VERSE
    Ne le plaignez pas trop : il a vécu sans pactes,
    Libre dans sa pensée autant que dans ses actes.
    Monsieur le duc !... – Je sais, oui : j’ai tout ; il n’a rien...
    Mais je lui serrerais bien volontiers la main.

    .......

    — Voyez-vous, lorsqu’on a trop réussi sa vie,
    On sent, — n’ayant rien fait, mon Dieu, de vraiment mal !
    Mille petits dégoûts de soi, dont le total
    Ne fait pas un remords, mais une gêne obscure ;
    Et les manteaux de duc traînent dans leur fourrure,
    Pendant que des grandeurs on monte les degrés,
    Un bruit d’illusions sèches et de regrets,
    Comme, quand vous montez lentement vers ces portes,
    Votre robe de deuil traîne des feuilles mortes.

    .......

    – Les feuilles ! – Elles sont d’un blond vénitien.
    Regardez-les tomber. – Comme elles tombent bien !
    Dans ce trajet si court de la branche à la terre,
    Comme elles savent mettre une beauté dernière,
    Et malgré leur terreur de pourrir sur le sol,
    Veulent que cette chute ait la grâce d’un vol !

    .......

    – Mélancolique, vous ? – Mais pas du tout, Roxane !
    Allons, laissez tomber les feuilles de platane...
    Et racontez un peu ce qu’il y a de neuf.

    .......

    Non, non, mon cher amour, je ne vous aimais pas !
    – Ah ! que de choses qui sont mortes... qui sont nées !
    — Pourquoi vous être tu pendant quatorze années,
    Puisque sur cette lettre où, lui, n'était pour rien,
    Ces pleurs étaient de vous ? – Ce sang était le sien.

    .......

    Vous souvient-il du soir où Christian vous parla
    Sous le balcon ? Eh bien toute ma vie est là
    Pendant que je restais en bas, dans l’ombre noire,
    D’autres montaient cueillir le baiser de la gloire !
    C’est justice, et j’approuve au seuil de mon tombeau
    Molière a du génie et Christian était beau !

    .......

    Mais que diable allait-il faire,
    Mais que diable allait-il faire en cette galère ?...

    Philosophe, physicien,
    Rimeur, bretteur, musicien,
    Et voyageur aérien,
    Grand risposteur du tac au tac,
    Amant aussi — pas pour son bien ! —
    Ci-gît Hercule-Savinien
    De Cyrano de Bergerac
    Qui fut tout, et qui ne fut rien.

    ... Mais je m’en vais, pardon, je ne peux faire attendre
    Vous voyez, le rayon de lune vient me prendre !
#+END_VERSE
#+END_CENTER

* Paul Verlaine

** Femme et chatte

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle jouait avec sa chatte,
    Et c'était merveille de voir
    La main blanche et la blanche patte
    S'ébattre dans l’ombre du soir.

    Elle cachait - la scélérate ! -
    Sous ces mitaines de fil noir
    Ses meurtriers ongles d’agate,
    Coupants et clairs comme un rasoir.

    L’autre aussi faisait la sucrée
    Et rentrait sa griffe acérée,
    Mais le diable n’y perdait rien...

    Et dans le boudoir où, sonore,
    Tintait son rire aérien,
    Brillaient quatre points de phosphore.
#+END_VERSE
#+END_CENTER

** Mon rêve familier

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je fais souvent ce rêve étrange et pénétrant
    D’une femme inconnue, et que j’aime, et qui m’aime
    Et qui n’est, chaque fois, ni tout à fait la même
    Ni tout à fait une autre, et m’aime et me comprend.

    Car elle me comprend, et mon coeur, transparent
    Pour elle seule, hélas ! cesse d'être un problème
    Pour elle seule, et les moiteurs de mon front blême,
    Elle seule les sait rafraîchir, en pleurant.

    Est-elle brune, blonde ou rousse ? - Je l’ignore.
    Son nom ? Je me souviens qu’il est doux et sonore
    Comme ceux des aimés que la Vie exila.

    Son regard est pareil au regard des statues,
    Et, pour sa voix, lointaine, et calme, et grave, elle a
    L’inflexion des voix chères qui se sont tues.
#+END_VERSE
#+END_CENTER

** Promenade sentimentale

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le couchant dardait ses rayons suprêmes
    Et le vent berçait les nénuphars blêmes ;
    Les grands nénuphars entre les roseaux
    Tristement luisaient sur les calmes eaux.
    Moi j’errais tout seul, promenant ma plaie
    Au long de l'étang, parmi la saulaie
    Où la brume vague évoquait un grand
    Fantôme laiteux se désespérant
    Et pleurant avec la voix des sarcelles
    Qui se rappelaient en battant des ailes
    Parmi la saulaie où j’errais tout seul
    Promenant ma plaie ; et l'épais linceul
    Des ténèbres vint noyer les suprêmes
    Rayons du couchant dans ses ondes blêmes
    Et les nénuphars, parmi les roseaux,
    Les grands nénuphars sur les calmes eaux.
#+END_VERSE
#+END_CENTER

** Soleils couchants

#+BEGIN_CENTER
#+BEGIN_VERSE
    Une aube affaiblie
    Verse par les champs
    La mélancolie
    Des soleils couchants.

    La mélancolie
    Berce de doux chants
    Mon coeur qui s’oublie
    Aux soleils couchants.

    Et d'étranges rêves,
    Comme des soleils
    Couchants, sur les grèves,
    Fantômes vermeils,

    Défilent sans trêves,
    Défilent, pareils
    A de grands soleils
    Couchants sur les grèves.
#+END_VERSE
#+END_CENTER

** Pensionnaires

#+BEGIN_CENTER
#+BEGIN_VERSE
    L’une avait quinze ans, l’autre en avait seize ;
    Toutes deux dormaient dans la même chambre.
    C'était par un soir très lourd de septembre
    Frêles, des yeux bleus, des rougeurs de fraise.

    Chacune a quitté, pour se mettre à l’aise,
    La fine chemise au frais parfum d’ambre.
    La plus jeune étend les bras, et se cambre,
    Et sa soeur, les mains sur ses seins, la baise,

    Puis tombe à genoux, puis devient farouche
    Et tumultueuse et folle, et sa bouche
    Plonge sous l’or blond, dans les ombres grises ;

    Et l’enfant, pendant ce temps-là, recense
    Sur ses doigts mignons des valses promises,
    Et, rose, sourit avec innocence.
#+END_VERSE
#+END_CENTER

** Sur le balcon

#+BEGIN_CENTER
#+BEGIN_VERSE
    Toutes deux regardaient s’enfuir les hirondelles :
    L’une pâle aux cheveux de jais, et l’autre blonde
    Et rose, et leurs peignoirs légers de vieille blonde
    Vaguement serpentaient, nuages, autour d’elles.

    Et toutes deux, avec des langueurs d’asphodèles,
    Tandis qu’au ciel montait la lune molle et ronde,
    Savouraient à longs traits l'émotion profonde
    Du soir et le bonheur triste des coeurs fidèles,

    Telles, leurs bras pressant, moites, leurs tailles souples,
    Couple étrange qui prend pitié des autres couples,
    Telles, sur le balcon, rêvaient les jeunes femmes.

    Derrière elles, au fond du retrait riche et sombre,
    Emphatique comme un trône de mélodrames
    Et plein d’odeurs, le Lit, défait, s’ouvrait dans l’ombre.
#+END_VERSE
#+END_CENTER

 

[[../index.php][Accueil]]
