
#+STARTUP: showall

#+TITLE: Eclats de vers : Article : Finance
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+../include: "../../include/navigan-1.org"

#+TOC: headlines 1

* Les raisons de l'abandon de l'étalon-or

Contrairement à une idée répandue, l'or et les autres métaux précieux
n'ont pas toujours été reconnu comme une monnaie d'échange universelle :

-  l'Égypte antique lui conférait un coté sacré, divin, et le réservait
   exclusivement aux cérémonies religieuses, et leur système économique,
   bien que très différent du nôtre, a permis à cette civilisation de
   prospérer pendant des millénaires
-  certains peuples se servaient de coquilles d'huîtres ou d'autres
   mollusques pour régler leurs transactions
-  d'autres encore utilisaient des céréales, peaux, dents, plumes, ...
-  plus près de nous, le paquet de cigarettes était fort utilisé dans le
   marché noir des pays de l'est, avant la chute du communisme

Toutes ces monnaies exotiques possédaient en communs ces critères
essentiels :

-  il fallait produire un effort de production (pêche, chasse, ...) ou
   un échange pour en obtenir
-  elle était suffisamment abondante pour permettre à l'économie de se
   développer

Quand on y réfléchit, on voit que ce sont ces conditions qui assurent la
stabilité d'un système monétaire : une monnaie gratuite ou trop
facilement accessible finit par introduire une hyper-inflation ; à
l'inverse, une liquidité insuffisante empêche l'économie de se
développer correctement.

Du fait de l'adoption pendant l'antiquité et le moyen-âge des monnaies
métalliques (or, argent, cuivre, bronze, ...), ce second point posa
régulièrement problème au fil de l'histoire : la production des mines ne
suffisait plus à alimenter la liquidité de l'économie. Les rois se
mirent alors à rogner de plus en plus la part de métaux précieux dans
les pièces afin d'en augmenter la quantité et surtout de remplir les
caisses de l'état, souvent vidées par les guerres incessantes. Le
développement des banques et de leurs produits financiers, ancêtres du
billet de banque actuel (lettre de change inventées par les templiers,
billets à ordre) apporta également une bulle d'oxygène au système, car
une banque prête généralement plus que ce qu'elle n'a en dépôt, ce qui
produit un effet multiplicateur sur la masse monétaire.

A partir du 19e siècle, le développement industriel explosif mis de plus
en plus en évidence la rareté de l'or par rapport aux besoins en
liquidités de l'économie.

Après la guerre 14, l'Allemagne, confrontée à une hyperinflation se vit
face à la nécessité de créer une nouvelle monnaie. Certes, il fallait
garantir cette monnaie par quelque chose de tangible. Oui, mais sur quoi
? Les réserves en or avaient été vidée suite au paiement exigé par le
traité de Versailles. Faute de métaux précieux, ils décidèrent donc que
la garantie serait une fraction (6 % des parts) de l'économie elle-même
: immobilier, entreprises, mines, production, ... La boucle était
bouclée et la nouvelle monnaie, le rentenmark, fut adoptée aisément par
la population.

L'ironie de l'histoire est que cette solution, adoptée comme une
rustine, se révèle en fait supérieure à la garantie or, car la valeur
des biens économiques, de loin supérieure à la quantité d'or disponible
sur la planète, permet une liquidité plus abondante et un développement
économique beaucoup plus souple.

Dernier acte, dans les années 70, où il apparaît clairement que la
quantité d'or disponible ne répond plus aux besoins économiques :
l'étalon or est abandonné par les USA, les changes deviennent flottants.

Aujourd'hui, on peut voir que, contrairement à une idée répandue, c'est
la rareté de l'or qui a provoqué sa chute en tant que monnaie. Demain,
si le système actuel apparaissait de plus en plus instable, peut-être
seront-nous amené à créer un « rentenmark » mondial.

* La vente à découvert

En ces temps de crise, les boucs émissaires fleurissent à tous les coins
de rue, et ces horribles sorciers de vendeurs à découverts figurent en
bonne position sur la liste : vilains, pas beaux, ils ont tous les
défauts que l'ignorance voudra bien lui /prêter/.

Car c'est bien de prêt qu'il s'agit : vendre à découvert revient,
directement ou indirectement, à emprunter un titre pour le vendre sur le
marché, dans le but avoué de le racheter plus tard, et surtout plus bas.
Il en résulte donc bel et bien une offre de titres surnuméraire, et il
n'en faut pas plus aux démagoges de tous les horizons pour nous sortir
des raccourcis et des conclusions simplistes, conclusions relayées par
les inévitables perroquets de service et autres volatiles toujours en
quête de perches pour se mettre en valeur.

Ainsi, la vente à découvert, ou « vade » comme on dit dans le jargon
financier, est responsable de tous les maux : cracks boursiers, crises,
récessions, épuisement des matières premières, problèmes écologiques.
Qu'on se le dise : la vade est la cheville ouvrière du grand complot
international-mondial de l'univers intergalactique ! C'est elle qui
alimente les bulles spéculatives, c'est elle qui oblige les banques à
prendre des risques inconsidérés sur des marchés illiquides et
dérégulés, c'est elle qui est la cause de la dégradation des comptes des
sociétés, c'est elle qui, point barre et sans discussion possible !

Trêve de plaisanteries et revenons à la réalité. Ce que les démagogues
ne vous disent pas, c'est que cette offre accrue implique également une
hausse de la demande. En fait, toute action vendue à découvert est
rachetée tôt ou tard, et ce d'autant plus vite que, comme tout emprunt,
l'emprunt de titre a un coût. Les intervenants ne peuvent donc pas
s'éterniser dans une vade sans voir s'amenuiser leur bénéfice ou se
creuser leurs pertes.

Les démagogues ne vous disent pas que plus la demande d'emprunt de
titres sera élevée, plus le taux d'intérêt correspondant grimpera,
rendant de moins en moins avantageuse une telle opération. La caricature
d'un marché constitué presque exclusivement de vadeurs affamés salivant
des crocs ne tient pas la route, car les taux pratiqués seraient alors
si élevés que la probabilité de gain frôlerait le zéro absolu. Avec des
taux élevés, non seulement les détenteurs d'actions ont plus intérêt à
prêter leurs titres qu'à les vendre, ce qui a pour effet d'assécher un
peu plus l'offre sur le marché au comptant, mais les intervenants ont
également tendance à acheter des titres afin de pouvoir les prêter et
d'en tirer une rémunération conséquente. Toutes choses inchangées par
ailleurs, on assisterait alors à une hausse spectaculaire des cours.

Interdire la vade n'aboutirait donc qu'à diminuer la liquidité des
marchés financiers, et par là même à diminuer l'attrait des titres
eux-mêmes. On l'a vu récemment, l'interdiction de la vente à découvert
des bancaires n'a pas le moins du monde ralenti leur chute, bien au
contraire.

Ce qui serait intéressant par contre, ce serait de permettre aux
particuliers de prêter aisément les titres qu'ils possèdent, histoire
d'arrondir les dividendes.

Si vous voulez vraiment assainir économie et finance, c'est ailleurs
qu'il vous faudra chercher. Et si nous parlions des monopoles, des
effets de leviers sans limite légale, des mandats cumulés, ce serait
plus intéressant que tous ces écrans de fumée.

* Réponse à l'argument « tu ne vends pas une maison que tu ne possèdes
pas

Une maison n'est pas liquide, ni fongible, tu n'as pas deux baraques
pareilles, ce qui n'est pas le cas des titres ou contrats standardisés.

* La face cachée de l'analyse fondamentale

On en revient toujours au même problème, une action ne peut se valoriser
que par des données futures donc inconnues, que ce soit dividendes ou
cours, autrement dit elle ne peut pas se valoriser, d'où l'extrême
volatilité dont elle souffre.

Le problème du cours présent dépendant du cours futur pose aussi le
problème d'auto-référence qui peut provoquer des exagérations à la
hausse comme à la baisse.

Sans compter que les actions n'ont pas la même valeur unitaire quand on
détient 0,01 % ou 70 % d'une société. Dans le premier cas, le dividende
prime, dans le second, c'est le bénéfice puisqu'on sait qu'on pourra le
faire sortir de la société quand on le désire.

Le titre qui permet de passer de 49,99 % à 50,01 % est en fait celui qui
a le plus de valeur intrinsèque pour le détenteur tout en n'ayant pas
d'attrait particulier pour un quelconque petit porteur.

La valorisation générique d'une action n'est donc pas seulement
inconnue, elle est inexistante.

