
#+STARTUP: showall

#+TITLE: Eclats de vers : Noeuds 13 : Divers
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des noeuds]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+TAGS: noexport(n)
#+TAGS: derived(d)
#+TAGS: middle_rope(m)
#+TAGS: sliding(s) adjustable_grip(g)
#+TAGS: double_loop(2) triple_loop(3)
#+TAGS: quick_release(q)
#+TAGS: vibration_proof(v)

* Serrage de lacets de chaussures

#+TOC: headlines 1 local

** Conseils pratiques

*** Désserrage de lacets

Bien faire attention à ce que les extrémités des lacets ne soient pas
à l’intérieur des boucles avant de tirer dessus.

** Simple

  1. on considère les terminus *E* et *F*
  2. premier overhand
     1) orienter *E* vers l’arrière droite
     2) orienter *F* vers l’arrière gauche
     3) croiser *E* et *F*, *E* au-dessus
     4) faire un tour avec *E* autour de *F*
        + en progressant vers la droite
  3. second overhand, avec des doublures
     1) faire une doublure *A* avec *E*
     2) faire une doublure *B* avec *F*
     3) orienter *A* vers l’arrière gauche
     4) orienter *B* vers l’arrière droite
     5) croiser *A* et *B*, *A* au-dessus
     6) faire un tour avec *A* autour de *B*
        + en progressant vers la gauche
  4. serrer

* Arrangement des lacets dans les oeillets des chaussures

** Introduction

*** Modélisation

On regroupe les oeillets par étages :

  0. [@0] étage du bas
  1. étage numéro 1, juste au-dessus du 0
  2. étage numéro 2, juste au-dessus du 1
  3. ...

Chaque étage contient un oeillet de gauche et un oeillet de droite.

*** Conseils pratiques

Partir du milieu de la corde, pour disposer de la même longueur pour
chaque partie libre.

** Double helix

Réalisé avec les deux parties libres du lacet.

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  5. étage 1
     1) passer *G* dans l’oeillet de droite, en entrant par au-dessus
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  6. étage 2
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  7. étage 3
     1) passer *G* dans l’oeillet de droite, en entrant par au-dessus
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  8. continuer ainsi jusqu’en haut de la chaussure

** Criss cross

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
  5. étage 1
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  6. étage 2
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
  7. étage 3
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  8. continuer ainsi jusqu’en haut de la chaussure

** Over under

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  5. étage 1
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  6. étage 2
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  7. étage 3
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  8. continuer ainsi jusqu’en haut de la chaussure

** Bow tie

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  5. étage 1
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
  6. étage 2
     1) passer *G* dans l’oeillet de droite, en entrant par au-dessus
     2) passer *D* dans l’oeillet de gauche, en entrant par au-dessus
  7. étage 3
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  8. étage 4
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  9. étage 5
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
  10. continuer ainsi jusqu’en haut de la chaussure

** Straight european

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  5. étage 1
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     2) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
  6. étage 2
     1) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  7. étage 3
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     2) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
  8. étage 4
     1) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
  9. continuer ainsi jusqu’en haut de la chaussure

** Train track

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
  5. étage 1
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     3) passer *D* dans l’oeillet de droite, en entrant par au-dessus
     4) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  6. étage 2
     1) passer *G* dans l’oeillet de droite, en entrant par au-dessus
     2) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     3) passer *D* dans l’oeillet de gauche, en entrant par au-dessus
     4) passer *D* dans l’oeillet de droite, en entrant par en-dessous
  7. étage 1
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *G* dans l’oeillet de droite, en entrant par en-dessous
     3) passer *D* dans l’oeillet de droite, en entrant par au-dessus
     4) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
  8. continuer ainsi jusqu’en haut de la chaussure

** Ladder

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
  5. étage 1
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
     3) passer *G* sous le passage formé à droite par le lacet entre
        les étages 0 et 1
        - vers la droite
     4) passer *D* sous le passage formé à gauche par le lacet entre
        les étages 0 et 1
        - vers la gauche
  6. étage 2
     1) passer *G* dans l’oeillet de droite, en entrant par au-dessus
     2) passer *D* dans l’oeillet de gauche, en entrant par au-dessus
     3) passer *G* sous le passage formé à gauche par le lacet entre
        les étages 1 et 2
        - vers la droite
     4) passer *D* sous le passage formé à droite par le lacet entre
        les étages 1 et 2
        - vers la gauche
  7. étage 3
     1) passer *G* dans l’oeillet de gauche, en entrant par au-dessus
     2) passer *D* dans l’oeillet de droite, en entrant par au-dessus
     3) passer *G* sous le passage formé à droite par le lacet entre
        les étages 2 et 3
        - vers la droite
     4) passer *D* sous le passage formé à gauche par le lacet entre
        les étages 2 et 3
        - vers la gauche
  8. continuer ainsi jusqu’en haut de la chaussure

** Zipper

  1. commencer par le bas de la chaussure
  2. soit *G* la partie libre de gauche du lacet
  3. soit *D* la partie libre de droite du lacet
  4. étage 0
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
     3) passer *G* sous le passage formé entre les deux oeillets, vers
        le haut
     4) passer *D* sous le passage formé entre les deux oeillets, vers
        le haut
  5. étage 1
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
        - soit *P1* le passage en diagonale de *G* entre les deux
          étages
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
        - soit *R1* le passage en diagonale de *D* entre les deux
          étages
     3) passer *G* sous *P1*, vers le haut
     4) passer *D* sous *R1*, vers le haut
  6. étage 2
     1) passer *G* dans l’oeillet de gauche, en entrant par en-dessous
        - soit *P2* le passage en diagonale de *G* entre les deux
          étages
     2) passer *D* dans l’oeillet de droite, en entrant par en-dessous
        - soit *R2* le passage en diagonale de *D* entre les deux
          étages
     3) passer *G* sous *P2*, vers le haut
     4) passer *D* sous *R2*, vers le haut
  7. étage 3
     1) passer *G* dans l’oeillet de droite, en entrant par en-dessous
        - soit *P3* le passage en diagonale de *G* entre les deux
          étages
     2) passer *D* dans l’oeillet de gauche, en entrant par en-dessous
        - soit *R3* le passage en diagonale de *D* entre les deux
          étages
     3) passer *G* sous *P3*, vers le haut
     4) passer *D* sous *R3*, vers le haut
  8. continuer ainsi jusqu’en haut de la chaussure

* Cravate

** Orientation

Pour nouer une cravate, il y a deux solutions :

  1. on penche la tête vers le torse pour regarder ce qu’on fait
  2. on regarde le noeud dans le miroir

Dans un cas comme dans l’autre, la partie arrière du noeud va se
retrouver entre la cravate et le torse, tandis que la partie avant va
se retrouver de l’autre côté. Pour cette raison, la convention
habituelle avant / arrière est inversée pour le nouage d’une cravate

** Simple

  1. passer la cravate autour du cou
     - partie fine *F* à gauche
     - partie large *L* à droite
  2. utiliser *L* comme partie de travail
  3. faire une boucle *B* en passant devant *F*, vers la gauche
     - soit *X* le croisement de *B*
  4. faire un tour anti-horlogique *T* autour de *X*
     - commencer vers la droite, derrière *X*
     - terminer vers la gauche, devant *X*
  5. passer dans *B*
     - vers le haut
     - en entrant sous le bord gauche
  6. passer entre *X* et *T*, vers le bas
  7. régler et serrer

** Half windsor

  1. passer la cravate autour du cou
     - partie fine *F* à gauche
     - partie large *L* à droite
  2. utiliser *L* comme partie de travail
  3. faire une boucle *B* en passant devant *F*, vers la gauche
     - soit *X* le croisement de *B*
  4. passer derrière *X*, vers la droite
  5. passer dans *B*
     - vers le bas et la gauche
     - en entrant au-dessus du bord droit
  6. effectuer le passage *P* devant *X*, vers la droite
  7. passer dans *B*
     - vers le haut
     - en entrant sous le bord droit
  8. passer entre *X* et *P*, vers le bas
  9. régler et serrer

** Full windsor

/alias/ : double windsor

  1. passer la cravate autour du cou
     - partie fine *F* à gauche
     - partie large *L* à droite
  2. utiliser *L* comme partie de travail
  3. faire une boucle *B* en passant devant *F*, vers la gauche
     - soit *X* le croisement de *B*
  4. passer dans *B*
     - vers le haut
     - en entrant sous le bord gauche
  5. orienter *L* vers le bas et la gauche
  6. passer derrière *X*, vers la droite
  7. passer dans *B*
     - vers le bas et la droite
     - en entrant au-dessus du bord droit
  8. effectuer le passage *P* devant *X*, vers la gauche
  9. passer dans *B*
     - vers le haut
     - en entrant sous le bord gauche
  10. passer entre *X* et *P*, vers le bas
  11. régler et serrer

* Filets

** Modified snake knot

  1. disposer la première corde principale *I*
     - sur un axe gauche - droite
     - à l’arrière de ce qui deviendra le filet
  2. attacher les cordes auxiliaires à *I* en nouant des bull hitch à
     intervalles réguliers
  3. réaliser des noeuds en quinconce avec des parties libres
     consécutives
     - exemples de noeuds
       + [[file:noeuds-05-ajut.org::#heading:two_strands_crown_knot][two strands crown knots]]
       + procédé utilisé dans le [[file:noeuds-13-ornement.org::#heading:snake_knot][snake knot]]
  4. disposer la seconde corde principale *II* sur un axe
     gauche - droite, à l’avant du filet
  5. faire passer les parties libres des cordes auxiliaires en
     alternant au-dessus et en-dessous de *II*
  6. fixer *II* au filet en faisant une série d’overhand avec des
     parties doubles
     - autrement dit, utiliser deux parties libre à chaque overhand

* Tissage (weaving)

#+TOC: headlines 1 local

  - Basket weave knot
  - Cargo net
  - Door knocker knot

* Références

  - livres
    + Ashley Book of Knots : une référence dans le domainse
  - chaînes youtube
    + Robert Mion : beaucoup de noeuds provenant de l’Ashley book of
      knots
    + First Class Amateur : inventivité, noeuds originaux
    + TX Tool Crib : connaissance approfondie des noeuds présentés
      * liste de lecture Knots
    + WhyKnot
    + Knotting Knots
    + Fire or Knot
    + Jason’s Knot Channel
    + knotsandcues
    + ProfessorShoelace
    + Repairs101
    + selfmadesailor
    + Paracord Planet
    + AnimatedKnots
