
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Carnaval
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+../include: "../../include/navigan-1.org"

#+TOC: headlines 1

* Je ne dormirai pas

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je ne dormirai pas
    Cette nuit
    Mais je ne viendrai pas

    Il fera froid et gris
    Et pourtant
    Je resterai ici

    A écouter le vent
    Balayer
    Les tristes paravents

    Auxquels je suis lié
    Tout comme eux
    Qui pourrait le nier

    Plus rien ne nous émeut
    Qu’en surface
    L’air devient venimeux

    Dans les palais des glaces
    Des paons teints
    S'échangent des grimaces

    Deux ragots le potin
    Ce cheval
    Vingt sous à trois contre un

    Je fuis le carnaval
    Sans attendre
    Que le masque m’avale

    La vanité n’engendre
    Que le vide
    Et des germes de cendre

    Je cherche l’atlantide
    Le compas
    Vers le zénith splendide

    Aussi je ne dors pas
    Je me baigne
    Dans le torrent des voix

    De la nuit souveraine
    Mystérieuse
    Fugitive fontaine

    Quand la nue capricieuse
    Déshabille
    Les étoiles rieuses

    Le vertige frétille
    Je m’y plonge
    Le sable bleu pétille

    Et les oisillons-songes
    Qui pépient
    Auprès de moi s’allongent
#+END_VERSE
#+END_CENTER

* Les éléments

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il surgira des flots ténébreux de la honte,
    Auréolé d'éclairs plus bleutés que le ciel.
    Par vagues, sa fureur, inondera l’immonde
    Et brisera la roue de la haine cruelle.
    Fuyez ! Voici l’orage,
    Déjà l’onde s’ombrage
    Et l’horizon est noir d’averses torrentielles.

    Il surgira des eaux profondes et glacées,
    Déchirure de lave engloutissant la mer.
    Ses bras étincelants, plus tranchants que l'épée,
    Tournoieront, meurtriers, en un disque de fer.
    Fuyez loin du séisme !
    Déjà le cataclysme
    Fait trembler l’océan sous ses tambours de guerre.

    De l’aube il surgira pour vaincre le couchant,
    Rose aurore affrontant la pourpre des empires,
    Deux soleils face à face en un duel sanglant,
    L’un armé de rubis et l’autre de saphir.
    Fuyez loin du combat !
    N’entendez-vous donc pas
    Leurs chevaux galoper et leurs sabres frémir ?

    Et ce sera le choc des éléments sauvages,
    Métal contre métal dans un bruit de tonnerre.
    Leurs hurlements furieux, repris par les nuages,
    Répandront la panique aux confins de la terre.
    Fuyons, point de bravade
    Devant cette tornade !
    Chaque coup creusera un immense cratère.

    Lorsqu’ils auront brûlé les océans grondeurs,
    Incendié jusqu'à l’eau frigide des glaciers ;
    Lorsqu’ils auront noyé la fournaise intérieure
    Et figé le magma des volcans surchauffés,
    Ils rompront, titubants,
    Leur rage de Titans,
    Et tourneront la bride vers l'éternité.
#+END_VERSE
#+END_CENTER

* Champs vénéneux

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les plus dangereux des reptiles
    Ne sont pas toujours ceux qu’on pense
    Souvent les manteaux d’innocence
    Servent à masquer les plus vils

    Ils sont si frêles si fragiles
    Sous leurs beaux habits de dentelle
    Mais méfiez-vous de leurs crécelles
    De leurs couvertures d’argile

    Car sous ces dehors ravissants
    Une seule idée les démange
    C’est vous vider de votre sang
    Pendant que leurs douces voix d’ange

    Endorment votre vigilance
    Et que dans cette anesthésie
    Vous vous transformez en zombie
    Pris entre torpeur et démence

    Sans même sentir l'énergie
    S'écouler par vos plaies béantes
    Cette sournoise léthargie
    Ne vous laissant qu’un coeur exsangue

    Le seul salut est la surprise
    Montrez-lui vos crocs de cobra
    La bête relâche sa prise
    Et vous fuyez loin de ses bras

    Attendez-vous à des crachats
    A quelques cris dans votre dos
    L'âcre fumée s'élèvera
    De l’herbe roussie des ragots

    On dira qu’en vous dégageant
    Vous fîtes souffrir ses mâchoires
    Qu’elle avala son poison blanc
    Et depuis pleure de l’eau noire

    Les légions des spectres drogués
    Diront d’une voix monocorde
    Le cauchemar halluciné
    Qu’est le mot d’ordre de la horde

    Mais les échos ont l’importance
    Que vous voulez bien leur prêter
    Marchez sans plus rien écouter
    Hormis le baume du silence

    Prenez garde soyez prudent
    Le lis est souvent sa cachette
    Quand son clin d’oeil étincelant
    Abrite un serpent à sornette
#+END_VERSE
#+END_CENTER

* Aux vertueux

#+BEGIN_CENTER
#+BEGIN_VERSE
    Aux vertueux enracinés
    Dans une auréole de neige
    Hautains comme des peupliers
    Parce qu’ils flottent comme un liège

    Sur la mer huileuse du vice
    Loin des nymphes des sortilèges
    Préférant sans doute à leurs pièges
    Leur âme vierge froide et lisse

    A ces pourfendeurs de caprice
    Fiers de ne s'être pas mouillé
    Pour n’avoir pas osé plonger
    Dans les arcanes du délice

    Aux professeurs de natation
    Qui n’ont jamais l’orteil dans l’eau
    Que dans des bains forts peu profonds
    Et qui se moquent des crapauds

    A ces champions de la rigueur
    Qui voudraient bien nous l’imposer
    Sous prétexte que leur pâleur
    Leur serait moins lourde au collier

    Aux hypocrites vaniteux
    Détenteurs de double morale
    Une pour l’autre une pour eux
    Sur une balance bancale

    A ces habiles habilleurs
    De vils intérêts par l’ascèse
    Qui alimentent leur orgueil
    Sur la dîme du diocèse

    Aux habitués de l’ennui
    Depuis de trop longues années
    Aux logiques cadenassées
    Je dirai simplement ceci

    C’est dans la boue qui s'évapore
    Que croît et germe le blé d’or
    Et le plus pur des diamants
    Sort du cratère d’un volcan
#+END_VERSE
#+END_CENTER

* Recto-verso

#+BEGIN_CENTER
#+BEGIN_VERSE
    Recto, l’arbre est en fleur,
    Il neige au bord de l’eau :
    Des nuées de couleurs
    Arrosent le ruisseau.
    Le concert des oiseaux
    Concurrence l’abeille ;
    Les ailes du soleil
    Réchauffent les roseaux.

    Verso, l’arbre est mort. Tronçonné par l’argent.
    La laideur immonde en bave de plaisir
    Dans l’eau qui n’est plus qu’un égoût dégoûtant.
    Rien n’empêchera l’immeuble de grandir,
    Rien n’ombrage plus les buildings arrogants.

    Recto, longs cheveux bruns,
    Un joli brin de fille ;
    L’amour lui va au teint,
    Tout son corps en frétille.
    Pourvu qu’elle sourie,
    Les nuées se découvrent ;
    L’aurore qui s’entrouvre
    Pâlit de jalousie.

    Verso, son coeur froid qui ne bat que pour elle.
    L’amour l’a souillée, louée, vendue, trahie :
    Elle n’en veut plus. Seule, restée fidèle,
    L’acide rancoeur ronge sa jeune vie :
    Elle a quatorze ans et le néant l’appelle.

    Recto, l’eau d'émeraude
    Parsemée de corail ;
    La plage d’ocre chaude
    Y dessine un vitrail ;
    Des poissons-éventails
    Flamboient dans tout l’atoll,
    Offrant une auréole
    A ce joyau de taille.

    Verso, c’est un rêve, une perle boueuse,
    Tombée du plafond d’une cave halogène
    Sur les murs transis de sueur laborieuse ;
    C’est le champignon qui verse l’eau laiteuse
    Sur les mains droguées aux hallucinogènes.

    Recto, la liberté
    A brisé ses entraves ;
    Son essor éthéré
    Libère les esclaves.
    Plus de rameurs d'étraves,
    La galère est finie ;
    La chiourme affranchie
    Sort enfin de l’enclave.

    Verso, c’est la voix de la faim, de l’envie
    D’un luxe inutile asséné constamment
    Sur tous les écrans ; les paillettes pourries
    Versées par l’espoir dans la cruche du vent,
    L’espoir d'évasion qui étrangle la vie.

    Recto, la paix profonde
    De la nuit impérieuse
    Où chaque étoile abonde
    En phrases silencieuses ;
    Les soirées délicieuses
    Où la brise caresse,
    Où la lune se dresse,
    Reine majestueuse.

    Verso, le vain bruit de la vaine querelle
    Et le rire en toc de la haine cordiale,
    Echo émergé de l’horrible crécelle
    Qui peine à cacher les rivières léthales,
    Le sang mal lavé par le chagrin du ciel.
#+END_VERSE
#+END_CENTER

* Les masques

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les masques grotesques se massent,
    Chacun dans son propre brouillard,
    Contemplant, au fond de l’impasse,
    Les mirages qui les égarent :
    Les illusions sont importantes
    Au bal des coquilles volantes.
    Assez de feutre, assez de fard
    Et du crachin des boulevards.

    La vanité, drogue tenace,
    Les enfume dans ses hangars.
    Ils engraissent quelque rapace
    Des cernes de leurs yeux hagards :
    La gloriole est toute puissante
    Sur leurs espérances fuyantes.
    Assez de feutre, assez de fard
    Et de froideur dans les regards.

    Leurs jours, au travers de la nasse,
    S'écoulent comme des cafards,
    L’heure n’est plus qu’une crevasse
    Où ils cachent leurs désespoirs :
    Il n’est plus un cil qui ne mente
    De ces marionnettes démentes.
    Assez de feutre, assez de fard
    Et des seringues du pouvoir.
#+END_VERSE
#+END_CENTER

* La plaine

#+BEGIN_CENTER
#+BEGIN_VERSE
    Alors qu’un soir que dans la plaine
    J'étais descendu vivement
    Pour fuir orage et mauvais temps
    Dans hautes broussailles s’amène
    Ombre furtive lentement
    Alors qu’un soir que dans la plaine
    J'étais descendu vivement

    La nuit un vent glacé de haine
    Me gela jusqu’au coeur le sang
    Je vis une mine d’argent
    Où règnait une odeur malsaine
    Et la tanière d’un géant
    La nuit un vent glacé de haine
    Me gela jusqu’au coeur le sang

    Comme pour complèter la scène
    Apparut Temple médisant
    Au feu aussi sombre qu’ardent
    Au milieu, la Justice obscène
    Otait jusqu’au dernier ruban
    Comme pour complèter la scène
    Apparut Temple médisant

    Le souffle court de leur rengaine
    Me fit fuir loin de ces déments
    Je remontai lors vivement
    Dans les collines, hors de la plaine
    Et le ciel me parut clément
    Le souffle court de leur rengaine
    Me fit fuir loin de ces déments

    Je me reposais sous un chêne
    Lorsque j’entendis doucement
    D’entre les feuilles sifflement
    D’un merle de ramée hautaine
    Récital doux et apaisant
    Je me reposais sous un chêne
    Lorsque j’entendis doucement
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]
