
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Comptoir
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+../include: "../../include/navigan-1.org"

#+TOC: headlines 1

* Dix vagues à six on

#+BEGIN_CENTER
#+BEGIN_VERSE
    Si l’on dit l’onde je dis vague
    Se méfier du quand dix ratons
    Qu’en dira-t-on si je divague
    Dix sous pour dissoudre un aiglon

    Et quand les escargots ergotent
    Ça ne vaut pas un vers ni sage
    Verni pour qui la crue des mottes
    Ne s’escamote après l’or âge

    Hors d'âge comme un vieux cognac
    L’ardoise apaisée par l'étang
    L’art doit zapper tous les tic-tac
    S’il veut s’extraire enfin du temps

    Mais méditer c’est suranné
    Sirop thé la plage aux soupirs
    Rendez la méditerranée
    Le vol au-dessus des sous pire

    Du pinard dans les épinards
    Car l'épine arrive assez tôt
    L'épi n’a reflété qu’un soir
    Les ondulations du ruisseau

    Il n’a prêté sa jolie plume
    Qu’au clair d’un notaire éphémère
    Que la brume automnale inhume
    Dans les chaudes vapeurs de bière

    L’hiver lis devant un bon verre
    Ecris des vers teintés d’azur
    Verse du vin sur la lumière
    Et tout le reste est confiture
#+END_VERSE
#+END_CENTER

* Clepsydre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Source de sable fin. L’eau frémit doucement.
    C’est le faux bourg : des ciels légers, du flottement,
    L'échappement, l’heure affolée, le cyclone,
    L’argent au long cours d’or à court de chrome.
    Et bientôt, le trou noir fait le vide.
    Tout est plus lent, passe plus vite.
    Et l’océan qui se noie,
    Et la plage qui plonge.
    Au travers des doigts,
    L'érosion ronge
    Quelques grains
    A n'être
    Qu'Un,
    Renaître
    Incertain
    Dans le silence,
    Perdu au mi lieu
    D’un monde qui s'épanche.
    De l’air blanc à mille lieues
    A la ronde. Hiver. Hé ! qui vive ?
    De la vie, mais fragile, intuitive.
    La solitude est dissoute à jamais.
    La conscience est, se développe. Eclair. Mais
    Déjà la pesanteur s’inverse. Flottement.
    Source de sable fin. L’eau frémit doucement.
#+END_VERSE
#+END_CENTER

* Le verre

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les hautes cimes enneigées des collines de chantilly
    Narguent de toute la splendeur des mousselines onctueuses
    De printaniers rayons, chatoyants et blonds comme l'épi.
    Plus bas, de crémeuses vallées se fondent, langoureuses,
    Sur un tapis moëlleux de sources effervescentes,
    Jacuzzi qu’alimente une fraîche rivière
    Au teint de miel, à la robe aurifère,
    Chaleureuse et pétillante,
    Tarie, déjà ?
    Ah ça !
    Crions !
    Garçon !
    Holà !
    L’addition ?
    Une autre tournée, c’est pour moi :
    Il faut bien hydrater nos valeureux cartons !
#+END_VERSE
#+END_CENTER

* Douzain

#+BEGIN_CENTER
#+BEGIN_VERSE
    Quand la rime opprimée déprime dans son coin,
    Trimant pour supprimer ses lamentables liens,
    Le sonore sonnet aux tercets balladeurs
    Entre dans la polka des rondeaux séducteurs
    Dont l’arrondi refrain attire les noceurs.
    L’haïssable hiatus y ébrèche sa hache,
    Des charmes convoités aux chansons qui se cachent,
    Alors qu’au panthéon le roi pantoum s’entiche
    Du pastiche qui lui dédie ses acrostiches.
    Loin de ces triolets et de ces hémistiches,
    Languides comme après l’extase les amants,
    L’alexandrin se traîne interminablement.
#+END_VERSE
#+END_CENTER

* Sonnet

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sonnet sonnant et trébuchant
    Qui vaut son pesant de pécune
    Muse d’encens chercher fortune
    Sonnet sonnant tinte d’argent

    Sonnet pipé lourdé comptant
    Un faux-plafond point de rancune
    En trompe-l’oeil une lagune
    Ravit les gourmets du clinquant

    Le tout flamboie de fioritures
    Clocher gothique ding dang dong
    C’est creux On s’en fout ca résonne

    Tant que balancent les postures
    Allez un dernier coup de gong
    Et que l’emphase me pardonne
#+END_VERSE
#+END_CENTER

* Monte-charge

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je suis le monte-charge avenue des plaisirs
    Numéros 6 à 9 building de 7 étages
    Qui gémit sous un ciel à l'éternel sourire
    Le parking est discret les clients sont en nage

    C’est un ancien moulin converti en hôtel
    Mais on n’y entre pas on pénètre les lieux
    Tous les coquins du coin y mènent leurs donzelles
    On m’a nommé ici car je suis silencieux

    C’est que j’en ai monté de la lingerie fine
    Vingt-huit heures par jour je reviens à la charge
    Des lanières de cuir des guêpières coquines
    Ah je suis soulagé quand sonne la décharge

    On pourrait croire à tort qu'à la fin on s’en lasse
    Repu de trop d'épice et l’aqueux en virgule
    Ne se redressant plus que surpris dans la nasse
    Mais l'être est ainsi fait qu’il avance et recule

    Je suis le monte-charge et j’en ai vu des couples
    Mignons le rouge au front s’agrippant les menottes
    Pour mieux se renverser d’autres qui ne s’accouplent
    Jamais sans un gadget qui plane en rase-motte

    Tout le village y passe ou par deux ou par douze
    Ils viennent se soigner se tâtent s’expertisent
    Votre pouls s’accélère enlevez votre blouse
    Ah si vous entendiez ce choeur de vocalises

    La femme du docteur est très anatomique
    Le genre lessiveuse à trente-sept degrés
    L’amante du facteur c’est la bombe tonique
    Regardez le pauvret il a l’air épuisé

    Fidèle au rendez-vous voici le tirailleur
    C’est un corsaire lui pistolet à deux coups
    Sa femme lui a dit va-t-en tirer ailleurs
    Et il l’a prise au mot sans hésiter beaucoup

    Le notaire et le clerc sont de proches amis
    La bonne et son curé n’en faisons pas un drame
    Le brave vigneron se dope au jus de fruit
    Je n’en dirai pas plus mais revenons aux dames

    La baronne ronronne et est des plus gourmandes
    La marquise est exquise et aime la tendresse
    La comtesse caresse active et redemande
    La duchesse en souplesse est excellente hôtesse

    La princesse paresse et s’impose en offrande
    Et comment dire non à autant de finesse
    L’adresse de l’altesse entre dans la légende
    La déesse opère en grande délicatesse

    Lorsque j’en ai assez de jouer au concierge
    Je grimpe sur le toit juste au-dessous du ciel
    Si vous vous attendiez à une rime en cierge
    Sachez que je la chante à ma belle gazelle

    Je suis le monte-charge avenue des plaisirs
    Numéros 6 à 9 building de 7 étages
    Qui jouit d’un beau ciel à l'éternel sourire
    Le parking est discret les clients sont en nage
#+END_VERSE
#+END_CENTER

* Secret taire

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le plumard est à la plume
    Ce que l’encre est à l’encrier
    Si la rythmique s’enrhume
    C’est que tu as perdu ton pied

    Et que l’accord désaccordé
    Titube sur le buvard
    Auprès d’un vélin bavard
    Qui s’amuse à lui rire au nez

    Car le vilain est sans fard
    Depuis qu’il a quitté la mine
    Et la gomme des cafards
    Pour la vulgaire encre de chine

    Cette dévoreuse de lignes
    Qui n’accepte aucune faute
    Si vous êtes de ses hôtes
    Méfiez-vous de ses épines

    La coquine un jour ou l’autre
    Vous asséchera le plumier
    On prétend qu’elle se vautre
    Et fait flèche de tout papier

    Il se dit que les papetiers
    Y trouvent chacun leur compte
    L’un serait devenu comte
    Sur l’or en barre des cahiers
#+END_VERSE
#+END_CENTER

* Ronsardises

#+BEGIN_CENTER
#+BEGIN_VERSE
    Mais que vois-je ? De l’ancolie
    Ou du nectar ? Non de la lie !
    C’est que j’aurais déjà tout bu ?
    Oui cette bouteille est devers
    Las ! Puisqu’il a plu dans mon verre
    Pourquoi n’y en a-t-il donc plus ?

    Cette carafe de sanglots
    Rebouchonnons-en le goulot
    Double tour le hublot bondé
    Elle est si lente à se remplir
    Au goutte-à-goutte du désir
    Dans le cristal sitôt vidé

    Ne céde point à la névrose
    Garde pure cette eau de rose
    Ne coupe point d’eau de javel
    Je sais c’est le nombril du nombre
    Mais quand trop brille la vaisselle
    A tous les coups la vie est sombre

    Cocktail à marquer d’une pierre :
    Dans la bière verse ce vin
    Verse de ce vin dans la bière
    Et mélangeons l’un l’autre afin
    Que le pampre mousse sans fin
    Sur les pamplemouses ibères

    Découpe deux citrons pressés
    Découpe deux citrons vert pomme
    Et puis si tu n’es pas pressé
    Arrosons d’un flacon de rhum
    Ne reste plus que les glaçons
    A servir frais et sans façon
#+END_VERSE
#+END_CENTER

* Pacha

#+BEGIN_CENTER
#+BEGIN_VERSE
    C'était un petit chat luthier
    Qui pêchait sur un chalutier

    Les mousses le traitaient chat lent
    Marin d’eau douce et de chaland

    Un pâle cueilleur de chataîgnes
    Souvent de mauvais poil chat teigne

    Je dirais plutôt non chat lent
    Mais admettons-le nonchalant

    Un matou de haute chatière
    Qui ne souffre pas un chat tiers

    Fier de son beau poil de chaton
    Enfin qui sait ce qu’un chat tond

    En somme juste un peu galant
    Mais certainement pas gars lent

    Même s’il arrose au pastis
    Sa fine moustache postiche

    Après quoi il dort et navrant
    Scie tout un bois dorénavant

    Un bois bruyant d'épicéas
    Aux fragrances épicées à

    Cet air roide des vers guindés
    Qui titubent dévergondés

    Et pour ne sombrer aux abysses
    S’entraident d’une canne à biche

    Le temps d’arriver au bord d’elle
    - Non je n’ai pas dit au bordel -

    Car enfin il faut bien qu’on vive
    Et plus il y a de convives

    Plus on rit c’est automatique
    Non nul besoin d’automne attique

    Mais à quoi bon cet écrit vain
    Je ne suis pas un écrivain

    Et ce puits de littérature
    Qui me dit relis tes ratures

    Car l’or a son taux gramme au graphe
    Surveille bien ton orthographe

    Après tout, tout relicat niche
    Après toutou relis caniche

    Commence donc par achever
    Ce qu’il te faut parachever

    Oui mais malgré ce commentaire
    Je ne trouve pas comment taire

    Cette question folle : L’est-on
    Ce clair alliage de laiton

    Et de la poupe à la proue est-ce
    L'étrave effilée de prouesses ?

    Peine perdue car il n’a guère
    De ces réponses de naguère

    Mais il ne faudrait pas qu’on fonde
    Ni que l’on s’endorme ou confonde

    Juste aller vérifier si terre
    Est bien la côte de Cythère

    Pour tout dire mets l’ancre au lit
    Ca guérit des mélancolies
#+END_VERSE
#+END_CENTER

* Mes nages rient

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le chat est fieffé maraudeur
    Un chapardeur au mat rôdeur

    La souris ondule et chaloupe
    Que bien trop souvent le chat loupe

    - Le perroquet ou le vrai ment
    - Le pèr’hoquèt’houle vraiment

    Le chien fidèle au baromètre
    Il fait fi d’aile au bar au mètre

    Le joyeux vautour y retourne
    Avant que le veau tourne autour

    Du veau de ville au veau des champs
    Ce vaudeville est indécent

    Je vous parle ici d’un veau doux
    Pratiquant la magie vaudou

    Tandis que la vache au pré, lasse,
    Tout en ruminant se prélasse

    En se disant que c’est assez
    La baleine aussi s’est tassée

    Et que dans les bois le gourd daim
    Somnole à coté  d’un gourdin

    L'écureuil vide ses ordures
    Seulement l'écu et l’or durent

    Le canard boude dans son coin
    On n’entend plus un seul coin coin

    Et près de l'étang le lin, seul,
    Semble se couvrir d’un linceul

    Le pivert picore les vers
    Sur un pauvre arbre de trouvère

    Se baladant toujours a poil
    La belette se chauffe au poële

    Ca fait siffler le canari
    Qui se rince l’oeil dans son nid

    L’oie qui répand quelques potins
    Prétend qu’elle fait le tapin

    Allons déplumer l’alouette
    Pour faire vibrer la luette
#+END_VERSE
#+END_CENTER

* En bourg Gueur

#+BEGIN_CENTER
#+BEGIN_VERSE
    Nous, Oignons de Bur-Gueur, Ducs et pairs de nos queux,
    Ors dorés par le Beurre au coeur de la saucière,
    En ce poëlon béni par l’essaim moustiquaire,
    En l’an deux mil sept vingt, Nous, Sommes silencieux,

    Aux songes d’icelui, élevons dame Bière,
    Soeur en soleil du vin, au rang de boisson d’or !
    Elle, Aura du pain cuit, Elle, Fût de Cythère,
    Outre, de notre miel, sceau plein de notre accord,

    Et de notre hydromel, qu’elle soit de l'Amphore !
    Par tous les fructidors ! Couronnée de houx blond,
    Et de tendre cresson ! Et de tendre cresson,
    Couronnée de houx blond par tous les fructidors.

    Qu’elle soit de l'Amphore et de notre hydromel,
    Sceau plein de notre accord, Outre de notre miel !
    Elle fût de Cythère, elle aura du pain cuit !

    Au rang de boisson d’or, soeur en soleil du vin,
    Elevons dame Bière aux songes ! D’icelui,
    Nous sommes silencieux en l’an deux mil sept vingt.

    Par l’essaim moustiquaire ! En ce poëlon béni,
    Au coeur de la saucière, Ors, dorés par le Beurre,
    Ducs et pairs de nos queux, nous oignons de Bur-Gueur !
#+END_VERSE
#+END_CENTER

* Cauchemar

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le thé qui bout sans la théine
    Le café sans la caféine
    Plus de beurre, mais margarine
    Le pain allégé sans tartines

    Le bazar sans babioles
    La bière sans alcool
    La pièce sans paroles
    Et l’ennui sans école

    Le pile sans le face
    Le sucre sans sa glace
    Le coca sans cocasse
    Le géant sans échasse

    De la glace pilée sans tain
    Grappe de pépins sans raisin
    Le pichet de vin sans tanin
    Et la nuit d’amour sans calin

    Le foie gras dégraissé
    Puis le roti raté
    Le pousse sans café
    Le dessert déserté

    Le cigare sans tabac
    Sans cacao le chocolat
    La tringle sans matelas
    Et les calins sans ébats

    L’argent sans la fortune
    Le sable sans la dune
    Le couchant sans la brune
    Le croissant sans la lune

    Les soleils sans chaleur
    Les sauces sans saveur
    Nuits d’hiver sans sueur
    Les parfums sans odeur
#+END_VERSE
#+END_CENTER

* Mal armé

#+BEGIN_CENTER
#+BEGIN_VERSE
    Orgueil et vanité, des titres des médailles,
    Des applaudissements croisés dans l’ascenceur :
    Le printemps déjà vieux n’a plus la même odeur,
    Trinquons ma belle avant que les cieux ne défaillent !
    Aux dieux des divins fûts, aux rois de la guindaille,
    Laissons la convenance aux mirlitons sans coeur !

    La chair est faible, et l’as, et je voudrais être ivre
    D’un peu d’humanité dans le clinquant des livres
    Sterling et des dollars et des parieurs stressés ;
    Ressentir ta chaleur sous ton décolleté,
    Puis, fusionnant nos peaux dans la fusion du givre,
    Au ressac de mon coeur ton coeur éclabousser.

    Lesbos, où les baisers manquent un peu de verge,
    Et puis ? Les doux cressons, qu’ils soient pipés de cierges,
    Demeurent vertueux sur les joues de leurs dames.
    Soeurs des sous à venirs, maîtresses des caresses
    Ô eux tous leurs écus, leurs florins, leurs sesterces,
    Te convertiront-ils à l’art des épigrammes ?

    Dis-le moi, nonne humour, c’est vrai qu’un tutu même
    Couvre le pissenlit d’un pompom diadème ?
    Que serait le balai sans quelques rats à poële ?
    L’eau paiera cet affront ! Mais que fait-elle ? Un rêve
    Etrange et, pénétrée de quelque gloire, glaive,
    D’un nain connu tout nu qui lui soigne le poil.
#+END_VERSE
#+END_CENTER

* Les dessous des Cartons

#+BEGIN_CENTER
#+BEGIN_VERSE
    Honneur aux Dames !

    Vient la Dame de Coeur, de toutes la première
    Un sourire discret festonne en tapinois
    Les teintes rose-thé de son joli minois.

    Suit la Dame de Pique, aigrelette et austère ;
    Une robe assassine encercle sans émoi
    Le couteau acéré d’un nez cireux et froid.

    La Dame de Carreau vaque à son ministère ;
    Elevant ses talents, et comptant ses ducats,
    Elle use au denier cinq, intérêts sans appas.

    Puis la Dame de Trèfle entourée de mystère ;
    Songe-t-elle à la grange où elle voit parfois
    En secret dans la paille un autre que le Roi ?

    A présent, aux Rois l’entame !

    Le pauvre Roi de Pique est maigre et courbatu
    Sous les coups redoublés des sermons infinis
    Que sa Dame lui sert aux vêpres comme au lit.

    Sire Roi de Carreau est las voire fourbu ;
    Il passe ses journées en des jeux étourdis
    Puis s’en va tout content, combler son appétit.

    S’en vient le Roi de Trèfle au bouc fier et cornu ;
    Il arbore un menton plissé par le souci
    Et un regard lointain qui compte l’ennemi.

    Le raide Roi de Coeur, flegmatique et barbu ;
    Pas un poil qui ne bouge, aucun cheveu ne bruit,
    Immobile statue encombrée de sourcils.

    A leurs talons, les Valets par qui tout se trame !

    Un Valet de Carreau au plumage hautain,
    En coquet coquelet poudré de vol-au-vent,
    A la belote couve un 9 élégamment.

    Vient le Valet de Trèfle, air tranquille et serein ;
    il pense à cette grange, où ses ébats ardents
    Font jaser le palais du coucher au levant.

    Puis le Valet de Coeur, de tous le plus coquin :
    Sans crainte qu’on le coupe, il emballe atout vent ;
    Insouciant il s’en vante, hé ! Naturellement.

    Enfin Valet de Pique effacé, clandestin ;
    Il aime les complots, les intrigues du temps
    Qui font tourner le grain de son moulin à vent.
#+END_VERSE
#+END_CENTER

* Contact

#+BEGIN_CENTER
#+BEGIN_VERSE
    Chaleur éparpillée dans des liens incertains
    On ne peut les palper mais ils flottent dans l’air
    Nervures composées de joie et de chagrin
    Tapies à l’intérieur de phrases tubulaires
    A chaque fois que vibre une émotion intense
    C'est qu’une autre corde entre aussi en résonance
    Tissant sans s’arrêter des rayons de lumière
#+END_VERSE
#+END_CENTER

* Liquides divins

#+BEGIN_CENTER
#+BEGIN_VERSE
    La bière est dans le verre. Pétillante et légère
    Sa mousse déborde de vie, ses reflets de mystères
    Qu’elle soit blonde, qu’elle soit brune,
    Qu’elle soit fauve ou bien féline
    Sa robe éclaire nos jours et rend nos nuits calines

    Le vin coule en cascades, en torrents de rubis
    Il déverse sa magie du bouchon à la lie
    En lui j’ai souvent vu des palais enchantés
    Où se mèlent en caresses de fines voluptés

    La bière est gourmande en rires et gaillardises
    Le soir est le moment où ses bulles frémissent
    Alors dans une gorge des lampées se glissent
    Puis un verre vide te regarde d’un air complice

    Le vin est sombre et fin, plein de fruits, plein d'épices
    Ses arômes rougeoient, que c’en est un délice
    Et lorsque l’on soulève sa jupe tentatrice
    Mille désirs s'éveillent devant ses friandises
#+END_VERSE
#+END_CENTER

* 24 heures, double tour

#+BEGIN_CENTER
#+BEGIN_VERSE
    Neuf heur' du mat', j’ai des frissons
    Le réveil sonn', coup de canon !
    Y vol' par la f’nêtre, mon crâne explose,
    J’ai du trop forcer sur la dose.

    Midi tapant' je me réveille
    Je tiens debout, pure merveille.
    Cachets d’aspro, que ça pétille
    Dans la douche l’eau qui frétille

    Trois heur' d’l'aprèm', dans l’auditoire
    C’est comm' de relir' l’assomoir
    Mes yeux clignot', j’ai l’vent dans l’dos
    Mais y a pas d’nymphe au cours d’info

    Six heur' du soir, l’air frais dégrise
    Les jupons vol', jambes exquises
    La soirée chaud' m’ouvr' l’appétit
    M’en vais manger un spaghetti

    Neuf heur' du soir un copain passe
    J’enfil' rapidos mes godasses
    Y connaît un gars qui connaît quelques copines,
    Du genre à têter la bibine.

    Onze heur', rallye de bar en bar
    Dans la tempêt' mon verr' s'égare
    A pleines pint' les pomp' offertes
    Versent la mousse aux moulinettes

    Une heur' du mat', on danse, on chante
    La sono vibre dans les ventres.
    Dans la fumée un vieux laser
    Semble nous dir' ``le feu est vert''

    Trois heur' du mat', ses lèvres nues
    Ell' dit ``j’ai un mec'', j’dis ``moi non plus''
    Rire sauvag' de la donzelle
    Et on s’aide à rentrer chez elle

    Six heur' retour à l’abreuvoir
    Y rest' encor' quelques soiffards
    L’un dit ``j’crois bien que j’ai trop bu
    Mais faut vider les derniers fûts''

    Neuf' heur' du mat' j’ai pas sommeil
    J’rentr' dans ma cour, tiens ? un réveil !
    Je fouill' mes poch', y a p’u d’oseille,
    Je trouv' les clefs, pure merveille !
#+END_VERSE
#+END_CENTER

* Le boursicoteur

#+BEGIN_CENTER
#+BEGIN_VERSE
    Plus d’amarres.
    Un seul homme a la barre.
    Son esquif s’esquive de la rive.
    Courants d’achats, vagues de ventes. Grincements.
    Les ordres affluent, la cote dérive.
    Le roulis en roue libre.
    Tout vibre.

    Nuit sans étoiles.
    Ciel bouché, réduire la toile.
    Le carnet vire, vole sous les coups de vent.
    Dans leurs cadrans, quelques aiguilles
    Partent en vrille.

    Récifs. Quelques sirènes à découvert
    Oscillent du rouge au vert.
    Laquelle ment ?
    Quel futur et quelle option
    Choisir ? Faut-il être court ou bien long ?

    Mouvement.
    Tendance pour seul guide.
    Rapides sur un canal liquide.
    Des chaloupes en régate
    Distancent les frégates.
    Voiles gonflées sous le vent arrière,
    Echange de masses d’air.
    Craquement.

    Cassure.
    Mats usés en rupture.
    Houle.
    La coque tangue et roule.

    Un Parquet ciré nous accueille.
    Glissades de titres.
    La tempête emporte nos feuilles
    Rejoindre les huitres.

    Des analyses farfelues
    Remplissent la corbeille
    Devant les regards médusés
    De porteurs abusés.
    L’espérance est ténue
    De retrouver l’oseille.
#+END_VERSE
#+END_CENTER

* Double sens

#+BEGIN_CENTER
#+BEGIN_VERSE
    Double sens, danse étrange
    Une porte me suit, dans la brume plongée
    Double tour, verrou d’ange
    La clef après l’huis sombre, à la fin s’est posée

    Nous étions au printemps. La brise soulevait
    Ses longs cheveux soyeux. Toujours elle portait
    Sa robe légère, me laissant entrevoir
    Ses chevilles. Tout près, ainsi qu’un nid de fées,
    Un buisson accueillant d’où perlait la rosée
    Poussait, paisible. J’admirais son regard noir
    Sous lequel des lèvres empressées et gourmandes
    Achevaient le dîner. Quelques ailes friandes
    Aspiraient le nectar, ce fertile ruisseau
    Des champs fleuris. La pelouse respirait l’eau
    Dont je l’avais arrosée le matin. Entre
    Deux festins nous nous reposions sur l’herbe tendre,
    Ses délicieuses jambes s'étirant, se pâmant
    Se laissant deviner. Etendue sur le flanc,
    Sous sa main caressante sa chatte s’extasiait.
    A contempler ce grand jardin empli de paix
    A contempler ses collines rondes et nues
    J’eu envie de cheminer. Ma panse repue,
    Je repris en main mon bâton de bois noueux
    Et commençai de gravir le sentier en pente
    Déjà raide qui mène presque jusqu’au cieux.
    Elle m’accompagnait, aimant les vertes sentes.
    Lorsque j’arrivai à l’entrée caverneuse
    Du bois de conifères, elle était essouflée,
    Sa poitrine haletait. L’onde tumultueuse
    D’un petit ru chantait. La fatigue empressée
    Envahissait nos corps et le désir grandit
    De nous en retourner. Mais nous fûmes d’avis
    D’aller toujours plus haut, augmentant la cadence
    N'épargnant ni nos muscles, ni nos pieds en flamme
    Jusqu'à ce que nos membres, gonflés d’impatience
    Nous amènenent au sommet, ou enfin nos âmes
    Eclatent de joie en gerbes de délivrance.

    Si tu trouves, Lecteur, ma strophe trop austère
    Reprend-la, n’en lisant que les lignes impaires
#+END_VERSE
#+END_CENTER

* Chaste ivresse

#+BEGIN_CENTER
#+BEGIN_VERSE
    Toujours être fin soûl, et sans rien avoir bu
    Dans une chaste ivresse accrocher au plumage
    Sombre de ses soucis les froufrous d’un tutu.
    Pour couvrir de colombes leur grèle ramage,
    Toujours être fin soûl, et sans rien avoir bu.

    Pouvoir être naif le temps d’un arc-en-ciel,
    Le temps de s’extasier de la moindre couleur.
    Redécouvrir le goût d’une gorge de miel
    Et revivre les nuits des premières douceurs.
    Pouvoir être naif le temps d’un arc-en-ciel.

    Voler, s’arracher de l’obscurité sans lune
    Que tissent sous les toits les angoisses frileuses,
    Fendre la toile épaisse des vieilles rancunes
    Puis atteindre les doigts des étoiles heureuses.
    Voler, s’arracher de l’obscurité sans lune.

    Prendre la peau d’un fou et son rire incisif,
    Rire à faire éclater les planches des théâtres
    Qui nous séparent tous de leurs bouffants motifs.
    A en brûler les écrans de fumée dans l'âtre,
    Prendre la peau d’un fou et son rire incisif.

    Se translater d’un pas vers l’orange horizon
    Voir le rouge infini ouvrir son pont-levis
    Flotter à contre-sens sur le fil des saisons
    A travers les murailles et les miroirs polis
    Se translater d’un pas vers l’orange horizon
#+END_VERSE
#+END_CENTER

* ABCDaire

#+BEGIN_CENTER
#+BEGIN_VERSE
    Acrostiche, viens avec nous : on rime au troquet de l'écluse !
    Banquet jusqu’au matin sous les yeux pétillants des muses !
    Décide-toi, la lettre C n’attends plus que tes vers,
    Et quand tu le dessines, il en devient si fier !
    Frère, le clocher sonne, il est dix heures
    Gagnons vite la lice guidé par la lueur
    Hâlée et sereine de damoiselle Lune,
    Intense reine du ciel nocturne.
    Joutons pour un lys, une fleur,
    Kimono rose-thé sur un coeur
    Laissé ouvert sur le passé.
    Mandoline, un air enchanté,
    Naviguons au petit bonheur
    Où des berceuses affolées
    Pourront panser nos plaies,
    Que nos chants de guérisseurs
    Répètent les octaves du bonheur
    Sur la soie sensible de nos lèvres
    Tandis qu’une nouvelle étoile se lève,
    Une autre Vénus en robe de soirée qui s’en
    Vient écouter nos strophes assise sur un divan,
    Wagonnet de l'Orient-Express à la lueur des bougies.
    Xérès pour tout le monde, et buvons aux Walkiries en furie,
    Régate sur Pégase, distorsion poétique dans moins d’une seconde,
    Zéro et c’est parti pour un voyage au pays d’un délire qui nous inonde.
#+END_VERSE
#+END_CENTER

* Sa Majesté Sérénissime

#+BEGIN_CENTER
#+BEGIN_VERSE
    Poème en Essaimessien traduit texto d’un texte troyen

    O §des C - $R 6 tu 10 8 ma rN
    J V 2main mat1 nous HT 1 ObN

    1 Knapé 10:20 tesT par l'XR6
    le temps 2 D6D 6 l’on est bien A6

    le temps 2 Vrifier 6 l'11& s'AJT
    2sus 100 rien KC & sans 2voir CD

    toute notre K7 pour 1 10van DT
    il nous faut DpenC dans l'FIK6T

    soyons 12 + prudents avec les 2/2 prix
    /4 les /3 commerçants sont souvent faux a/2

    traduction :

    Aux soldes c’est moins cher si tu dis oui ma reine
    J’y vais demain matin nous acheter une aubaine

    Un canapé divin testé par l’exercice
    Le temps de décider si l’on est bien assis

    Le temps de vérifier si l’on sait s’agiter
    Dessus sans rien casser et sans devoir céder

    Toute notre cassette pour un divan d'été
    Il nous faut dépenser dans l’efficacité

    Soyons tous plus prudents avec les demi-prix
    Car les tiers commerçants sont souvent faux amis
#+END_VERSE
#+END_CENTER

* Evanescence

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les meilleurs vers
    Sont ceux qui restent en l’air
    D’ailleurs ceux-ci se sont déjà évaporés
    Vers l'éther
    D’où ils sont nés
#+END_VERSE
#+END_CENTER

* Octave

#+BEGIN_CENTER
#+BEGIN_VERSE
    Allez déposer un cas do
    Cas ré
    Sous la cas mi sol
    D’un papier bleu et rose où le ruban forme un cas si
    Véritable cas la mité
    Pour celui cas fa me
    La vue d’un cas do
#+END_VERSE
#+END_CENTER

* Esprit gaulois

#+BEGIN_CENTER
#+BEGIN_VERSE
    A l’approche d’un spasme écartelé, Cécile
    A raté son orgasme à cause d’une pile

    Fuyant la pestilence avant de Ludivine,
    Je regrettai l’oubli d’un pot de vaseline

    Une odeur de marée poursuit dame Clarisse,
    Clitoris attitré de la marine suisse

    Du maillot détrempé de notre amie Joèlle
    Dépassait, impudique, une intime ficelle

    C’est en voyant son string dénuder Véronique
    Que l’appétit me dit : « va pour latex tonique ! »

    Tu peux dire à la soeur de la froide Chantale
    Qu’on prend bien mieux son pied en ôtant ses sandales

    Après l’avoir sucé, la coquine Eloïse
    A planté le noyau de l’ardente cerise
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

