
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Galanteries
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+../include: "../../include/navigan-1.org"

#+TOC: headlines 1

* Cocktail

#+BEGIN_CENTER
#+BEGIN_VERSE
    Il y faudrait de la glace
    Fondante comme un sourire
    En langues d’eau qui s’effacent
    Vaporisées de désir

    Il y faudrait un chalet
    Au frigidaire garni
    Les chats raffolent du lait
    Qu’on leur verse dans le nid

    Il y faudrait une chambre
    Discrète à double vitrage
    Qu’on soit les seuls à entendre
    Nos culbutes de sauvages

    Il y faudrait de la fièvre
    Et se noyer de sueur
    A la fraîcheur de nos lèvres
    Pour condenser la vapeur

    Il y faudrait des calmants
    A pleins tubes d’endorphine
    Pour apaiser nos tourments
    Quand l’aurore s’endort fine

    Il y faudrait quelques nuits
    Au moins pour tout consommer
    Et l’or logé en circuit
    Pour pouvoir recommencer

    Il y faudrait de ces fruits
    Juteux pour désaltérer
    Et recharger sur le lit
    Nos batteries épuisées

    Il y faudrait la pulpeuse
    La tendre pêche sanguine
    De la houle langoureuse
    Et beaucoup de vitamines

    Il y faudrait ces soupirs
    Ces pulsions dans ta poitrine
    Aiguillons à assouvir
    Pointant sous la mousseline

    Il y faudrait de l’encens
    Pour corrompre le brouillard
    Qui nous coule dans le sang
    Comme un poison doux et noir

    Il y faudrait des salés
    Pour attiser notre soif
    Et flamber dans le foyer
    Les réserves de cognac

    Il y faudrait des frissons
    Pour que vibre le sommier
    Pour secouer au tison
    Le mélangeur échancré

    Il y faudrait quelque lien
    Pour tordre l’espace-temps
    Et que mousse le chemin
    Jusqu’au point d'égarement
#+END_VERSE
#+END_CENTER

* Alternative

#+BEGIN_CENTER
#+BEGIN_VERSE
    Te prouver mon amour autrement qu’en je-t-aimes
    Te prouver, mon amour, que l’amour qui nous lie
    Est plus fort est plus beau que trois mots qui frétillent
    Dans le doute et la peur de nos mains qui s'étreignent

    Qu’il ne reste qu’un souffle aux bougies qui s'éteignent
    Et un parfum d’encens pour allonger la nuit
    Qu’il ne reste qu’un souffle un peu rauque un peu gris
    A l’aurore attendrie dont le rire nous baigne

    Te prouver qu’un serment vaut bien moins qu’un instant
    Quand je le passe en toi à célébrer la vie
    Jusqu’aux petites morts dont on renaît plus grand

    La seule vérité est l’alcôve où l’on crie
    La seule éternité est celle que l’on prend
    Ne la réduisons pas à ces mots inconstants
#+END_VERSE
#+END_CENTER

* Contact

#+BEGIN_CENTER
#+BEGIN_VERSE
    Quand les mots n’ont plus cours reste la poésie
    Elle est seule à pouvoir retranscrire à distance
    Tout ce que l’on ressent à rêver d’une fille
    Et à transmettre intacte une ardeur lancinante

    Aussi quand deux beaux yeux vous regardent : silence !
    Ne lui dites plus rien mais écrivez-lui tout
    Vos fantasmes cachés vos désirs les plus fous
    Et la brûlure au sang que vous crée l’abstinence

    De ne pouvoir enfin la serrer dans vos bras
    De ne pouvoir enfin la couvrir de vos mains
    Et la border d’amour à l’abri de vos draps

    Quand vient le souffle court reste un vers de satin
    Un sonnet tout en soie qui frôlera ses seins
    Et la caressera du haut jusques en bas
#+END_VERSE
#+END_CENTER

* Vent d'anges

#+BEGIN_CENTER
#+BEGIN_VERSE
    Sers à boire l’amour je vide la bouteille
    Le tonneau de ta peau surtout s’il est sans fond
    Sers à boire l’humour et n’oublie pas la treille
    Les grappes alourdies geignent sous la pression

    Allons tâter les fûts que cache ton jupon
    Pour voir si l’un d’entre-eux peut être mis en perce
    Ne feins pas l’ingénue et retrousse ta herse
    Veux-tu un peu de feu ? J’allume la passion

    Je veux la voir fumer dans ces yeux qui me bercent
    Comme une averse chaude aux braises d’un soupir
    C’est un cru bien trempé le vin que tu nous verses
    Lever ton cotillon relève mon désir

    Ta chair de satin rose enflamme le saphir
    Il n’y a plus qu’un pas de la coupe à nos lèvres
    Sens-tu le narguilé tourbillonner de fièvre ?
    La cuvée est tirée buvons sans tant languir
#+END_VERSE
#+END_CENTER

* Décalage

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je te l'écrirai le seize
    Loin des flopées de cuicuis
    Nous attendrons que s’apaisent
    Les trafiquants de grigris

    Envolez-vous confettis
    Et petits coeurs de papier !
    Les cocottes dépliées
    Ne vous ont donc rien appris ?

    La poule aux oeufs d’or est lasse
    De nidifier le quatorze
    La fleur s'étiole et s’efface
    Quand l’escroc griffe l'écorce

    Bouton de robe et de rose
    Attends un peu pour t’ouvrir
    Je ne veux pas que l’eau rose
    Se mêle à l’eau du désir

    Inonde-toi de patience
    Lune de ciel océane
    Ta lingerie alléchante
    En deviendra diaphane

    C’est tout l’art et la science
    Que nous enseigne l'éclair :
    Electriser l’atmosphère
    Avant d’entrer dans la danse

    C’est dans des bois plus discrets
    Plus langoureux moins précoces
    Que l’on murmure en secret
    Les biens en chair et en noces

    Et ce sera quitte ou trouble
    La toile évadée du cadre
    Nos lèvres verseront double
    Le feu échappé de l'âtre

    On prend mieux son contre-pied
    En décalant les audaces
    Le savoir-faire l’impasse
    S’applique au calendrier

    Foin des piscines moroses
    Des jacuzzis grand écran
    Où l’onde vague s’est close
    Depuis plusieurs nuits du temps

    Je te l'écrirai le seize
    Loin de la meute du quinze
    Qui pour éviter le treize
    Nous assourdit de syrinx
#+END_VERSE
#+END_CENTER

* Vers galants

#+BEGIN_CENTER
#+BEGIN_VERSE
    Couvrez-vous, chère amie, je ne réponds de rien
    Si pendant cette oeillade enflammée qui va suivre
    Vous laissez l’air de rien le galbe de vos seins
    Naître et s'épanouir sous mes yeux qui s’enivrent

    Si vous ne rentrez pas, bergère, vos tétons
    La nuit nous sera courte à nos ébats bien longs

    Couvrez-vous, alouette, où je vais déplumer,
    Une à une effeuiller les grappes de vos vignes
    Pour m’en aller nicher dans la rose dorée
    Qui depuis ce matin semble me faire signe

    Si vous ne rentrez pas, bergère, vos tétons
    La nuit nous sera courte à nos ébats bien longs

    Couvrez-vous, demoiselle, et fermez vos pupilles
    Ou je plonge dedans ! Et ton sourire en coeur
    Où flotte cet aveu de notre amour qui brille
    Garde-toi qu’il se fonde en rire tentateur

    Si vous ne rentrez pas, bergère, vos tétons
    La nuit nous sera courte à nos ébats bien longs

    Votre robe, voyez, ne tient plus qu'à un fil !
    Un bien pâle verrou pour garder vos trésors :
    Il suffit d’un soupir et d’une main habile ...
    Dois-je entendre que vous me cédez votre corps ?

    Si vous ne rentrez pas, bergère, vos tétons
    La nuit nous sera courte à nos ébats bien longs

    Couvrez-vous, gente dame, il est temps, choisissez !
    Le désir me lancine et mon clin d’oeil s’achève ...
    Bien, vous l’aurez voulu, vos draps seront froissés,
    Je m’en vais vous couvrir de votre tenue d'Eve.
#+END_VERSE
#+END_CENTER

* Ablutions

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle était bain-douche
    Je suis plutôt mousse
    Nous prîmes pour couche
    L’abri d’un bain-mousse

    Je me nommai mousse
    De sa jolie bouche
    Baisai à la louche
    Sa jolie frimousse

    Elle prit la mouche
    Mais bouderie douce
    Je vis dans sa mouche
    Un rire qui mousse

    Un sourire en couche
    Déjà jeune pousse
    Arrosant la brousse
    D’une fraîche souche

    La savane rousse
    S’incline et se couche
    Un frisson de frousse
    Nous frôle et nous touche

    Docile et farouche
    Son souffle éclabousse
    Ses lèvres qui gloussent
    D’un air des plus louches

    Caressant mon pouce
    D’autres diraient gousse
    Ah mais vos yeux louchent ?
    Rideau sur la douche !
#+END_VERSE
#+END_CENTER

* Trottinette

#+BEGIN_CENTER
#+BEGIN_VERSE
    - Ton sourire est sursis
    Sous tes sombres sourcils
    Aurais-tu un souci
    Ma souris qui trottine ?
    Tu ne peux me l'écrire
    Ni même le décrire
    Mais je ne peux souscrire
    A ce qui te chagrine

    - Mes excédents me lassent
    Je suis dans la mélasse
    Mes rondeurs fuient la glace
    Vise ma silhouette
    Je ne peux plus si vite
    En jolie marguerite
    M’approcher des guérites
    Me la jouer coquette

    - Ah ça si tu déprimes
    Il faut que tu l’imprimes
    Sur quelque rythme en prime
    Qui te ferait danser
    Pour guérir du syndrome
    Et retrouver ses chromes
    Rien de tel que le baume
    Qu’on appelle chanter

    - Mais j’ai l’aphone éthique
    Je perds la phonétique
    Dans ce champ de colchiques
    De charmeuses à larmes
    Tu sais l’arbre au riz colle
    Plaisirs arboricoles
    Qui faussement décollent
    En de fausses alarmes

    - Aies confiance en un chat
    Paresseux et pacha
    Ne fait pas tout un plat
    De tes fruits généreux
    J’hésite à déguster
    Ou bien me délecter
    Savourer dévorer
    Tes appas onctueux

    - Rentre ces mots grivois
    Propre des chats gris vois
    Je ne suis pas de bois
    Je sais que tu me daubes
    Sais-tu que je me cambre
    Je plie sous le gingembre
    Quand vient geindre en ma chambre
    La fontaine de l’aube

    - J’admire votre coffre
    Qui gonfle sous l'étoffe
    L’inspiration étoffe
    Votre joli cou lisse
    Crois-tu que les dés pensent
    Quand les corps se dépensent
    En folles récompenses
    A l’abri des coulisses ?

    - Cher ami je présume
    Que votre soif écume
    Tous les ports où l'écume
    Est douce et virevolte ?
    Gardez donc vos secousses
    Je ne suis de ces housses
    Si légères qu’on trousse
    D’une aile désinvolte

    - Je sens comme un vent pire
    Que celui des vampires
    Souffler en ton empire
    Range tes incisives
    Aux sangsues alitées
    Prendre autant que donner
    De sensualité
    Oui telle est ma devise

    - Ne sois pas si ballant
    Le jeu de go est lent
    Passons au goéland
    Mon sommeil se délabre
    Ta réplique est cinglante
    Et je reste sanglante
    Le feu ardent au ventre
    Sans même un candélabre

    - Ni homme ni présence
    Tu veux l’omniprésence
    Nous rouler dans la danse
    Mais sans en avoir l’air
    Tu me parles maquette
    De flamber la moquette
    Ou d’attiser la couette
    Sans sauter de barrière

    - Tout cela reste à voir
    Si l’on ne peut savoir
    Alors autant s’avoir
    Autant que je fléchisse
    - Veux-tu que je m’enflamme ?
    - Que mon corps te réclame ?
    - Que ma chanson t’acclame ?
    - Que je te réfléchisse ?
#+END_VERSE
#+END_CENTER

* Adamantine

#+BEGIN_CENTER
#+BEGIN_VERSE
    Elle est fauve et féline et son corps de panthère
    Se fond dedans les flots agités de la nuit.
    Seuls, un reflet de lune et d’enivrants yeux verts
    Dénudent ma vénus allongée sur le lit.

    Le piège est bien tendu mais qui me pensait pris
    Se retrouve captive emmêlée dans ses tresses.
    Un baiser velouté, de contre-danse épris,
    Coule au creux de mes mains les clefs de leur maîtresse.

    Dans un rire soumis tout autant que vainqueur,
    Elle se fait brebis tour à tour et tigresse ;
    Nos sauvages douceurs libèrent la liqueur
    Des chaudes voluptés, des tendres allégresses.

    Elle est au jeu d’amour une insatiable ogresse
    Mais je la prise ainsi, feulant dans la litière,
    Jusqu'à l’aube écrémée où les rais de lumière
    Se posent sur les cils de ma charmante hôtesse.

    M’agripperai-je à vous chatoyante crinière,
    Aux guirlandes de fleurs du saule guilleret ?
    A travers le rideau, irai-je au nid douillet
    Qui dans l’obscurité couve quelque mystère ?

    Ondoyante toison, frontière de l’azur,
    Sur sa peau satinée ruisseaux aux cours distraits
    Qui sillonnez sa gorge et ses pulpeux attraits,
    Laissez ce chant sur vous étendre son murmure !
#+END_VERSE
#+END_CENTER

* La muse inquiète

#+BEGIN_CENTER
#+BEGIN_VERSE
    - Dis-moi mon jeune ami avec qui je partage
    L’essence et la douceur de tant de douces heures
    Où nous volons tous deux d’éclaircies en orages

    Espérant dieu sait quel improbable rivage
    Mon frère mon amant - mais suis-je bien ta soeur ? -
    Avec qui quand l’envie nous y convie je couche

    Sur un lit de vélin nos fiévreuses langueurs
    Notre souffle commun transmis de bouche à bouche
    Tout ce qui en un mot nous donne le vertige

    Dis le moi s’il-te-plaît dis le moi je t'écoute
    Pourquoi ? Je veux savoir ! que dis-je je l’exige !
    Pourquoi la dédaigner ? Une aussi jolie fille ?

    Je l’ai vue comme toi cette poupée érige
    Sûrement bien des feux qui l’appellent chérie
    Elle a le teint si frais et ses joues sont si roses

    Qu’on dirait un dessert orné de sucreries
    Ne serait-ce cet air hautain de porte close
    Si je n'étais inquiète oui je serais jalouse

    Car enfin je le sais quand tu vis cette chose
    Tu as montré autant d'émotion qu’une arbouse
    Certes connaissant bien ton goût des petits fours

    Je ne m’attendais pas à ce que tu l'épouses
    Je te sais préférer au marbre le velours
    Mais de là à bâiller devant si belle proie

    Aurais-tu attrapé quelque chagrin d’humour ?
    Devrais-je te soigner de mon nectar de roi
    Ou t’enseigner l’ardeur qui bouillonne en mes veines ?

    M’instruiras-tu comment ? Me diras-tu pourquoi ?
    - Je me le suis aussi demandé sois sereine
    La raison la voici fais taire ces alarmes

    C’est que de ses yeux secs ne coule aucune larme
    Beaux oui comme il convient c’est là tout le problème
    C’est qu’elle a de l'éclat ... sans avoir aucun charme
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

