
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Mages
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+../include: "../../include/navigan-1.org"

#+TOC: headlines 1

* Lave oratoire

La palmeraie se ferme aux soupirs des fontaines, le soir tombe de son
lit, l'orage gronde, menaçant, et il en est ainsi depuis la nuit des
temps.

Non, vraiment, les générations futures ne nous ont rien appris : le
théâtre a besoin de monnaie, la monnaie se vend à la pièce, la pièce
achète le théâtre et le cycle recommence. Car au prix où est l'or, nul
ne peut plus s'en passer. Il paraît même que l'important n'est plus
d'être, mais d'avoir, et même d'avoir l'air, brasser de l'air et de
l'argent.

Mais la palmeraie, le soir, l'orage, ce tourbillon t'emporte dans ses
trombes de neige et de vent, et te voilà noyé sous cette neige plus drue
que de l'encens, sous ce vent qui te fait siège.

Et il en est ainsi depuis la nuit des temps : l'eau descend les
ruisseaux, la fleur descend les coeurs. N'était-ce l'avenir de ce papier
à musique, qu'y aurait-il d'autre à composer ? Qu'y aurait-il d'autre à
écrire que ces quelques versets zéro tic ?

⁂

Le sel et la soif, la soif et le sel.

Une rose des vents secs qui déchaîne l'empire de l'éternité. Des draps
et des coquilles de soie qui coulent en quelques secondes.

Une brindille électrique, un buisson, une oasis venimeuse, une escorte
de dunes lunatiques où grouillent des scorpions veufs, des scorpions
noirs.

Le buste d'un arbre de calcaire pour projeter son ombre arrosée sur les
rosiers. Parmi les moins diserts, parmi les plus sauvages.

De frêles arbustes en guise de feuillage, un soleil pour s'ensabler peu
à peu au souffle aride du désert, de la rosée d'étoile, et de la nuit
pour la cadence. Une brindille, un buisson, puis le silence.

Voilà pour les champs de graines.

⁂

Quant aux châteaux de pierre et de sable, ils ne diffèrent que par le
temps qui les sépare des vagues séculaires. C'est sur leurs ruines
témoins imbibées de murmures que les souvenirs se dessinent à qui les
sait lire.

Et qui les sait lire saura qu'il doit effleurer l'onde d'ivoire et
d'ébène, car c'est d'elle que partira la foudre des déluges libérateurs.

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je te suis d’un pas vif et joyeux, je te suis
    Reconnaissant et fier de danser sous la pluie
#+END_VERSE
#+END_CENTER

A l'abri d'un saule rieur à moitié effondré, le cristal liquide s'écoule
le long de l'écorce. Quelques gouttelettes de ludicité limpide, bientôt
maquillées aux couleurs de la frondaison déchue. Quelques mélodies
échappées d'un vitrail teinté de bleu, et ces quelques mots de celte :

#+BEGIN_CENTER
#+BEGIN_VERSE
    Lente en est l’ascension quand la chute est rapide,
    L’ami lierre le sait qui s’agrippe aux vestiges.
#+END_VERSE
#+END_CENTER

Mais qui n'a pas déjà oublié les mythes de ces langues cryptées ...
savez vous ce que l'on prétend ? Ce serait lors de ces éclipses de
légende, ce serait lorsque croissants de lune et de soleil partagent le
même disque astral sans se recouvrir que l'étincelle se transmet de
regard en regard.

Des éclipses fort rares, mais ce sont d'elles que part la foudre des
déluges libérateurs.

⁂

Il y aurait beaucoup de choses à découvrir parmi ces légions de raretés.
Beaucoup de choses à maudire, beaucoup de fleurs où tomber. Car même si
elles aiment à croire le contraire, ce sont leurs pétales qui se posent
sur les ailes des papillons, qui se brûlent en confondant la cire et le
jour, quand la flamme étouffée n'atteint jamais les nuages.

Ainsi l'abeille têtue s'arrangera toujours pour heurter fenêtres
ouvertes ou fermées jusqu'à l'épuisement. Et de pouvoir pester ensuite
contre le machiavélisme de l'architecte ... mais qu'on se le dise,
aucune verrière n'a jamais utilisé l'appât d'un nid d'abeille.

Les sortilèges, ils résident ailleurs, sous le plumage naufragé de
l'oiseau qui tisse sa cage.

Ils nichent sous la cicatrice de ces vérités qui étincellent,
s'embrasent, flambent, incendient tout sur leur passage avant de
s'engloutir dans les flots.

Les sortilèges couvent dans les nuées de sirènes.

⁂

Plus loin dans la nuit, les éclairs rôdent en meutes parmi les ombres.
Qui écoutera d'une oreille attentive percevra l'écoulement d'un fleuve
pastel fleuri d'automnes chatoyants. Le ciel est dans son reflet, mais à
la moindre rafale, au moindre poisson trouble qui remuera des nageoires,
au moindre frémissement, l'eau se voilera et les bals jadis démasqués
hurleront de nouveau avec les fous.

#+BEGIN_CENTER
#+BEGIN_VERSE
    Nous sommes des chouettes
    Mariées à des hiboux
    Qui chevrotons coquettes
    Pour les beaux yeux des loups
#+END_VERSE
#+END_CENTER

C'est le royaume des aliénés et des quêtes insensées, de la table ronde
à la pierre philosophale, de l'or au graal. Là-bas, rien n'est certain,
mais tout est possible. Rien ne se sait, mais tout se devine.

#+BEGIN_CENTER
#+BEGIN_VERSE
    Harpe désenchantée des écharpes fétiches,
    La serpe aromatique a parcouru les steppes ;
    Sauras-tu voyageur dans ce cordage en friche
    Quel accord déluré déverrouille les sceptres ?
#+END_VERSE
#+END_CENTER

Tu ne trouveras en ces lieux ni éprouvette sulfureuse, ni le vase
auroral d'une étoile lointaine, ni le nacarat scintillant d'une
constellation improbable. Absentes également les crinières fougueuses et
la grâce des licornes qui distancent les comètes à la course.

Il n'y a là que le frère de ton frère, de ce frère que tu n'as jamais
eu.

#+BEGIN_CENTER
#+BEGIN_VERSE
    Dès la pénombre offerte
    Nous ferions vraiment tout
    Pour glousser en cachette
    Dans les bois de bambous
#+END_VERSE
#+END_CENTER

Il n'y a là que celui que tu ne sais pas trop comment fuir, celui que tu
fuis par peur de savoir.

Dans la nuit éclairée de meutes d'ombres, les lynx contemplent
silencieusement un fleuve automnal fleuri de pastels chatoyants.

⁂

Au solstice des antipodes, la lumière filtre à travers le toit en
souricière : la houle tourmentée dont tu crains l'apaisement, et ces
palais des glaces, et ces glaces libérant des hydres d'épouvantails.

Chacun sait qu'y demeurent de grandioses vertus, parmi lesquelles la
mesquinerie et la vanité sont assises aux places d'honneur mais,
l'ironie n'ayant pas sa place ici, je me garderai bien de te décrire
l'infâme tuyauterie qui se cache sous la mousse irisée et le parfum
balnéaire !

L'hypocrisie qui serait presque charmante s'il lui arrivait de rire, la
crasse poudrée de sentiments aussi ostensiblement nobles que
discrètement fétides, les retournements des vestales opportunistes ne
sont finalement que de tristes lieux communs.

Les lieux communs de l'âme humaine.

⁂

Bien sûr, au-delà de l'artifice, la clef.

Un tourbillon de roses, des déluges d'étoiles, des essaims de papillons,
des quêtes insensées, un soleil radin qui ne donne plus rien, de la
tuyauterie parfumée ...

Et au-delà de l'art, la clef.

La source.

* Insomnia

I can't get no sleep sleep sleep sleep sleep sleep ...\\
 (Faithless)

Quelle heure est-elle ? Les bas-fonds de la nuit, les égouts du sommeil
n'ont pas d'heure, seulement la cadence de la pesanteur. Tu te poses des
questions qui n'ont pas de sens, tu tournes à vide. Evite de regarder
les pendules murales, il y a déjà bien assez d'horloges qui te tournent
autour, et ce n'est pas un tic tac de plus qui va alléger le poids du
temps sur ta poitrine.

Pulsation. Ton coeur vient de battre, depuis combien de temps ne
l'avait-il plus fait ? Une seconde, une heure, un sac de grains
d'éternité ... Quand on fonce vers les moulins à vent, vers les moulins
de l'aube, vers les moulins à poivre, il faut s'attendre autant aux
nuées qu'à l'éther, et tu le sais.

Quelle heure est-elle ? Ne regarde pas, il y a déjà bien assez
d'horloges, bien assez d'aiguilles qui sortent de leur cadran et
vrombissent à ton oreille. Un essaim affamé de moustiques femelles.
Elles ont déjà probablement commencé à te sucer le sang sans que tu ne
t'en rendes compte. Tu te répands dans le néant, ferme les vannes si tu
ne veux pas crever. Tu connais la musique non ? Combien de gammes as-tu
joué déjà ? Des sauvages, des tendres, des frissonnantes, rappelle-toi !

Pulsation. C'est fou comme le gong de la vie résonne dans ce silence qui
retombe. L'écho, l'écho, l'écho ... l'écho te revient comme une syncope.
On a vu mieux balancé comme blues. Inutile de se noyer dans les arpèges
pourris d'une quelconque lubie cuitée, ferme plutôt les vannes et laisse
la vie vibrer à nouveau dans les basses. Tu les as vues voler plus haut,
les basses, alors redonne-leur des ailes.

C'est l'heure où la folie étend ses bras autour de ton cou, la folie
pure et dure comme une drogue qui manque d'humour. Comme une vraie folle
du cru qui ne guérit pas l'âme. Ce n'est pas encore le moment, pas
encore, tu dois réapprendre à rêver. Tout doit être détruit et
reconstruit. Les retours de flamme de l'absolu sont aussi violents que
ses élans, c'est l'évidence même, et tu n'es pas du genre à faire les
choses à moitié.

A chaque pulsation, tu sens ton être se répandre aux quatre vents, se
vider de son essence. Plus de jus, ni dans ton coeur, ni dans tes yeux.
Ca t'apprendra à emprunter les sentiers de forêt plutôt que les chemins
balisés. Ferme les vannes, ferme ! ... Les nuages sont si lourds qu'ils
ne vont bientôt plus pouvoir se contenir.

Quelle heure est-elle ? L'heure où la souffrance appelle sa délivrance.
Ne cède pas, tu ne dois pas céder. Rappelle-toi plutôt, rappelle-toi qui
tu es. Souviens-toi de ton nom. Non idiot, pas celui qui t'a été donné !
Celui que tu as gravé de tes mains, l'empreinte de ton âme sur le marbre
des neiges originelles. Celui qui est tien depuis la nuit des temps. Oui
... tu le reconnais à présent.

Un éclair, enfin. Les nuages crèvent, la pluie translucide nettoie les
blessures. La vie se diffuse, la sensation renaît. Quitte ce qu'il reste
de cette chrysalide dérisoirement petite, absurdement mesquine, et dors,
que les plaies se cicatrisent.

Quelle heure est-il ? L'aube certainement. Dehors les oiseaux chantent
et tu te rappelles à nouveau leur langage mystique. Ils te disent
« viens ! ».

* Les dragons rouges

Je connaissais le pouvoir des gifles du silence, mais qui aurait cru
qu'elles pourraient crever aussi aisément les nuages ? J'ai bien tenté
de rentrer les griffes et de modérer la flamme, mais le ciel s'est
déchiré comme un simple papier peint. Et derrière les papiers peints, il
y a toujours des cafards, et d'anciens tournesols tristes. Au fond de
moi je le sais, le ciel ne peut pas se déchirer, il devait s'agir de son
ombre.

Voulez-vous connaître la tragédie des dragons ? Ce sont des volcans. Des
volcans qui sèment la lave et récoltent des cendres. Ils fertilisent
mais n'engendrent pas, car les forêts sont trop faibles pour soutenir
longtemps en elles l'intensité de leur amour. Des éclaircies qui les
suivent, ils n'entendent que des légendes sans couleur. La tristesse qui
les emplit pourrait pulvériser les montagnes du grès le plus dur comme
un château de cartes, mais les seules larmes qu'ils arrivent à verser se
sont forgées dans le sel et le sable.

Parmi les bipèdes sans aile, certains choisissent de cracher en liquide,
d'autres empruntent des promesses à découvert ou signent des chèques en
bois synthétiques, d'autres encore paient de leur personne. On peut même
en croiser qui égorgent les vestiges de leur fierté pour abreuver leurs
succubes. Mais pas eux. Eux, ils ne paient que de leurs larmes. Des
larmes de sel et de sable.

Quand la douleur devient trop forte, ils muent. On les voit alors errer
sans but, sans espoir, sans lendemain. En vain. Ils ne goûtent plus rien
que de pâles souvenirs. Pour renaître, ils devront à nouveau tremper
leur langue dans la fournaise. Et chaque naissance contient son agonie.
Et chaque souffrance est plus intense, plus lancinante que la
précédente. Dans ce cas, pourquoi ne font-ils pas taire leurs ardeurs ?
Sont-ils fous ? Sont-ils inconscients des risques qu'ils courent ? Non,
mais ce sont des volcans.

Des volcans qui sèment la fleur et le feu, la fleur après le feu. Ils
fuient comme la peste les radiateurs tièdes et les flammèches froides.
Ils ne prennent pas le thé, ils s'enivrent dans ses draps de vapeurs.
Ils ne se contentent pas de faire l'amour, ils lui redonnent vie. Ils
n'offrent pas l'avenir, mais partagent les clefs de l'éternité.

Voulez-vous savoir la tragédie des dragons ? C'est qu'ils aiment la
neige, sans jamais pouvoir l'embrasser. Seule la pureté peut résister à
leur souffle, seule la sincérité d'un sentiment peut soutenir leurs
regards. Mais il ne reste jamais rien que la blessure d'un fol espoir.

Vous pouvez les détester, vous pouvez nous détester. Après tout, vous
êtes capables de vous renier, vous, pauvres bipèdes sans aile, êtres
fragiles qui vous cassez les crocs sur nos écailles. Mais vous ne
pourrez pas le faire sans briser en vous le lien entre la terre et le
ciel.

Le ciel ... on m'a dit qu'il s'est déchiré comme un simple papier peint.
Et derrière les papiers peints, il y a toujours des cafards, et
d'anciens tournesols tristes. Au fond de moi je le sais, le ciel ne peut
pas se déchirer, il devait s'agir de son ombre. Je ne modèrerai plus ma
flamme. Dis-moi mon Amour, veux-tu que je te calcine ?

* Léthé

Quand le fleuve incandescent se répand dans ta gorge, que des langues de
lave s'écoulent depuis les forges, que l'éponge efface tous ces
souvenirs si lourds à porter sur le tableau noir de ta mémoire
surchargée, tu oublies...

Tu oublies les paillettes moqueuses, les étoiles filantes qui ont filé
plus vite que tes espoirs, les petites mines étrangleuses qui ne se
savent pas, qui blessent par inconscience comme on écrase un insecte.
Disparus les sermons partiaux et partiels, les vaines jalousies, les
sanglots ravageurs. Toutes ces peines sont effacées. Mais il reste ...

Mais il reste des torrents de tresses dorés par l'aube, l'appel des
soeurs de l'aurore comme des frères de la côte sud du bar. Il reste les
yeux silencieux et pensifs d'une maîtresse qui t'éclaboussent de bonheur
sans même que tu saches pourquoi. Et puis, il y a ce regard éperdu qui
brille dans la brume, collé au fond d'une salle, et presque
simultanément ce fantôme éthéré qui surgit de la paroi nébuleuse du
futur, parfaite réplique du présent, en plus triste néanmoins.

Mais c'est alors que vient ce sourire ensoleillé qui tombe sur la rose
encore humide de l'averse, pareille à un éclat libérateur dans un
silence épaissi par l'orage. Et tu oublies l'apparition pour ne plus
voir que l'éclaircie.

* Dissolution

#+BEGIN_CENTER
#+BEGIN_VERSE
    Des vers libres ? Bien sûr, j’ai tenté d’en coucher
    Sur le doux matelas du papier glacé.
    J’ai pris entre mes mains le noble alexandrin,
    Le rythme somptueux, le canonique airain
    Et je l’ai brisé.

    Comme ça, sans réfléchir, un peu comme on casserait une noisette.
    Le vers y a beaucoup gagné en incohérence,
    Quelle chance !
    Restait à aplatir cette
    Entêtante sonorité
    A grand renfort de voyelles
    Lourdes, sombres, sourdes, sans ailes.

    Hélas, le langage emprisonnait toujours la pensée !
    Je me devais de l'éclater !

    Erluna rosidème auriège outmos bisame

    Voilà qui était fait.
    Ce vers
    Ne voulant plus rien dire, on s’approche du but.
    Mais encore ?

    La page emprisonnait toujours le texte
    Je passai donc au cube de papier, à la cocotte,
    Au calligramme volumique
    A l’encre rose-orange
    J'écrivis sur un ballon gonflé à l’hélium pour rendre le texte
    plus aérien
    Je passai aux caractères chinois, au sanskrit
    J’inventai de nouveaux alphabets

    < { [ ( µ @ % § # $ * £ ° | : / ) ] } >

    Puis me mis au seul dessin que je défigurai
    J'écrivis du doigt sur l'éther
    Comme symbole de l'éphémère
    Ide. Je traçai des constellations new wave entre les étoiles
    Histoire de dépoussiérer les anciennes
    Transformer le temporel en argument de l’intemporel
    Paradoxe
    Orthodoxe
    Mais tout cela ne me menait à rien

    Tout ce que j’entreprenais restait obstinément coincé
    Coin Coin c’est Coin Coin c’est Coin Coin c’est Coin Coin c’est
    Tributaire des lois de notre monde
    Alors j’imaginai un univers sans loi
    Sans forme
    Sans couleur
    Sans rien
    Le vers fut dissout
    Et je vis quelque chose qui n’existe pas
    Je vis la liberté absolue
    Je vis le néant.

    J’abandonnai alors la gravure sur sable.
    Voilà pourquoi depuis, pour partager mes fables,
    J’utilise sans frein les folles pulsations
    Et grave l'émotion sur les sillons du son.
#+END_VERSE
#+END_CENTER

* Jeune aise

Le petit enfant ne pouvait plus dormir. Tant de rêves s'étaient
accumulés en lui qu'il peinait à les contenir tous, et il ne voulait à
aucun prix les laisser s'envoler à tout jamais avant d'en avoir conservé
l'empreinte dans son esprit. Comme pour désserrer l'étau qui comprimait
ses songes, il se leva du lit douillet, traversa sa chambre en direction
des fenêtres et en ouvrit grand les battants. L'air glacial de la nuit
hivernale s'engouffra dans la pièce, mais curieusement ce froid intense
qui contrastait avec son feu intérieur l'apaisa. Détendu, il observa
longuement les carreaux qui reflétaient la lueur pâle mais splendide de
la voie lactée. Attirés par le magnétisme du spectacle, ses doigts
carressèrent la vitre étincelante. Cette dernière ne comportait aucune
aspérité, aucune rugosité. D'une voix aussi douce, aussi lisse que
l'était sa surface, elle lui dit : "je suis la perfection de
l'équilibre, mais cette plénitude que tu ressens en moi est à la fois ma
force et ma faiblesse. Dès que je tente de m'écarter de mon état
originel, les forces irrépressibles de l'esthétique parviennent à
vaincre ma volonté en me montrant combien j'étais plus belle avant, quel
sacrilège et quelle imprudence je commets en m'aventurant dans
l'inconnu. Je retourne alors dans la cage de mon miroir doré. Pourtant,
je suis sûre qu'il doit exister d'autres équilibres, je voudrais les
explorer, les connaître. Mais l'univers est si vaste et mon éclat si
fragile. Je suis l'ordre et la logique ultime, la contrainte à l'état
pur, celle qui donne forme à toute chose. Je suis une déesse, mais une
déesse stérile. Les seuls enfants que j'aurai jamais sont ces étoiles
que j'adopte et que je recueille dans le sein de mes reflets."

L'enfant pleura des larmes brûlantes de tristesse pour évacuer la peine
qu'il ressentait face au sort de son amie. Il se répandit tellement
qu'une brise chaleureuse s'insinua à travers les fenêtres ouvertes pour
venir le consoler. Son contact si tendre, enivrant, sensuel submergea
rapidement ses sens. Il ressentit au creux de l'alizé une vapeur
enfiévrée qui lui dit : "je suis le magma des possibilités en éruption,
le labyrinthe tentaculaire des univers probables et improbables, mais
cette ivresse que tu ressens en moi est à la fois ma force et ma
faiblesse. Je puis aller partout sans pouvoir me fixer nulle part,
l'étendue même des choix qui s'offrent à moi m'écrase. Je me disperse
dans l'infini sans être capable de m'accrocher à un endroit particulier,
pareil à l'eau tumultueuse d'un torrent. Mon naturel bouillant me
déchire, me pousse à me relever avant même que je ne sois assis. J'ai
cotoyé nombres d'équilibres, sans avoir jamais pu projeter mon
imaginaire sur leur beauté, je n'ai jamais pu voir leurs visages ni le
mien. Je suis la liberté ultime, le chaos absolu, le principe même de la
création. Pourtant, toutes mes oeuvres se marchent les unes sur les
autres, s'entre-détruisent. Des myriades en naissent à chaque instant
mais aucune n'a le temps de se développer et toutes restent inachevées."

Voyant l'enfant qui pleurait à nouveau de plus belle, les masses d'air
chaudes et froides s'entremêlèrent et dansèrent en un vaste tourbillon,
arrachant un rire joyeux à leur jeune protégé. La vapeur d'eau,
refroidie, se condensa en buée au contact de la vitre. Troublée,
celle-ci interrogea l'enfant : "est-ce le reflet de tes larmes qui se
pose sur moi ?". A l'instant où il s'apprêtait à répondre, un éclair le
traversa et il comprit comment il pouvait aider ses amis. Les mains du
jeune peintre commencèrent à dessiner ses songes sur la buée : des
galaxies prirent forme, des étoiles brillèrent, des comètes fusèrent !
Dans les premiers temps, seule l'inventivité du bambin gambadait sur la
vitre. Puis, petit à petit, l'esprit créatif de la vapeur, apaisé par la
plénitude du verre qui le berçait, acquit sa propre dynamique. De la
buée plus fine remplit partiellement les traces des doigts laissés par
l'enfant-dieu : la vie était née.

L'enfant-père, satisfait, s'assit en tailleur et contempla le monde
qu'il venait de créer.

⁂

- Dis papa, est-ce qu'elle est vraie cette histoire ?\\
 - Bien sûr fiston, à partir du moment où tu y crois elle sera vraie.
Mais il faut la ressentir assez intensément que pour convaincre la
matière elle-même qu'elle vit. D'ailleurs fais taire tes doutes, sinon
tu vas provoquer des catastrophes dans le monde de la vitre.

* Les exilés du ciel

Bien sûr on peut faire le plein de vent dans la voilure et tenter de
remonter le cours du ciel comme on remonte une simple brise. Une régate
dans les bras des voiles latines, en direction du sourire accrocheur
d'un clair de lune. On peut atteindre les étoiles et dissiper le voile
de ces mondes féeriques tapis à l'intérieur des nuages roses. J'ai
entendu dire que la musique y explose comme une palette de couleurs,
qu'on peut y glaner un espoir ni vert ni sage et déposer sur la toile le
parfum résiduel d'une rose. On peut aussi récolter une couvée de ces
oeufs d'or et les nicher au creux de sa main. L'autre main acceptera les
draps bleus d'une vénus sanguine qui vous reliera au foyer rougeoyant du
magma terrestre. La neige éternelle préférera sans doute répandre sa
douce fraîcheur dans vos cheveux flottant en apesanteur. On peut même
aller jusqu'à tout graver dans le marbre le plus dur que l'on puisse
trouver dans toute l'étendue de la rose des vents. On peut même aller
jusqu'à saisir l'insaisissable. Mais vous n'attendrez pas longtemps
avant que vos enluminures ne soient recouvertes de poussière et de
sable. Quant à ces mondes paradisiaques, dès que le réservoir sera à sec
d'alizé et que vous retomberez dans la grisaille ils se dissoudront dans
l'exil. Les oeufs s'empresseront d'éclore et les poussins de regagner
les cumulus ; la neige fondue mouillera vos yeux et coulera sur vos
joues ; la vénus ne sera plus caressée que par l'étoffe et les langueurs
du sommeil. Les dernières braises du foyer de la veille tiédiront au
petit jour. Il semble que les corps célestes tombent tous en cendre au
contact de notre atmosphère. Il n'en reste que le remous d'un sillage,
une vaguelette sur un rivage où vient mouiller un vaisseau fantôme sans
équipage. Aussi quelques poètes un peu beaucoup fous qui tentent de
rassembler les feuilles mortes, de sculpter la cendre et de polir la
courbe des vagues. De ces poètes assez cinglés pour jeter des bouteilles
à la mer.

* Politique céleste

Nul commencement n'eut lieu. Ce furent des renouvellements dans la
luxuriance des possibles. Des atlantides émergeaient de leurs tombeaux
silencieux, des avalons rafraîchis par d'autres aurores cristallines
s'ouvraient sur les univers régénérés. Il y avait un amour, il y avait
un fruit, et aussitôt apparaissait l'aurore d'une vie nouvelle. La
boucle se bouclait, le cycle recommençait.

Aux matines de notre temps, à l'aube de notre monde, les dieux vivaient
dans l'anarchie et la création n'était encore qu'un magma incandescent.
Ils étaient nombreux alors à se réunir autour du concert sacré !
Pourtant, dès que les accords se taisaient, ils se retrouvaient seuls et
en souffraient beaucoup. Voyant cela, le diapason de l'orchestre
créateur donna à chacun d'eux un peuple pour l'adorer. Chacun de ces
peuples leur construisit des sanctuaires et chacun de ces sanctuaires
s'élevait, palais splendide au coeur de l'olympe.

Mais il advint qu'un dieu fut jaloux, car son voisin possédait un palais
plus haut que le sien. L'envieux força alors son peuple à lui bâtir des
temples toujours plus imposants. Comme cela ne suffisait pas, il demanda
à une partie de ses fidèles de prendre le fouet et de le tourner contre
leurs frères. Ce qu'ils firent d'autant plus promptement que leur propre
rancoeur était à l'image de celle de leur dieu : dévastatrice et
dévorante. Content de leurs services, l'envieux nomma les fouetteurs
« Maîtres » et il les exhorta à châtier de leur paresse la caste des
esclaves.

Il arriva ce qui devait arriver : la caste des Maîtres s'enrichit en
dépossédant le reste du peuple, elle pilla sans réserve les monts et les
plaines sans réaliser qu'elle détruisait la crèche aux oeufs d'or. Les
temples grimpèrent plus haut, tellement haut qu'ils en devinrent de
simples boîtes de fer. Cependant, personne ne sembla s'apercevoir qu'ils
perdaient en élégance ce qu'ils gagnaient en orgueil.

L'harmonie suprême quitta les lieux en attendant de meilleurs jours. Les
sources se tarirent, les fruits perdirent de leur saveur, les arbres de
la connaissance furent coupés avant de parvenir à l'état adulte. L'homme
les abattait parce qu'ils le dépassaient et qu'il ne supportait plus
leurs ombres lumineuses. Au lieu de s'endormir sous sa frondaison, de
profiter des pages effeuillées de la sagesse qui lui tombaient sur la
tête et les pieds, il prit sa hache et chaque coup l'éloigna un peu plus
de la vérité.

C'est à ce moment que le dieu jaloux réalisa qu'aussi immenses
fussent-elles, ses citadelles n'étaient égayées d'aucune vie. Furieux,
il nourrit le projet de s'emparer des possessions de ses pairs. Il
réunit ceux de ses frères qui souffraient aussi des blessures de
l'orgueil et les mena dans une guerre impitoyable contre les autres
divinités. Comme ceux-ci n'étaient pas armés, ils n'eurent aucune
difficulté à les vaincre un à un. Ils s'auto-proclamèrent ensuite les
premiers Ducs de l'olympe. Les vaincus furent impitoyablement chassés et
durent se réfugier au plus profond de la forêt de brocéliande. Il y eut
des discours, il y eut du bruit. Ce fut la fin de l'âge premier.

⁂

Les nouveaux maîtres du panthéon inaugurèrent leur règne en établissant
les fondations d'une monarchie qu'ils espéraient éternelle. Afin
qu'aucun d'entre-eux ne puisse les trahir, ils décidèrent de se répartir
les partitions enchantées abandonnées par les vaincus. Le livre
contenant les arcanes de la magie des mots fut placé au centre de la
table ronde. Ainsi, tous purent invoquer le sortilège permettant de
nommer toute chose qui est un être et tout être qui est une chose. Leur
meneur fut couronné Roi et grava par le feu des nuées les lettres
Z-e-u-s sur sa pierre d'éternité.

Les autres Ducs et Duchesses prirent les noms d'Aphrodite, Astarté,
Ammon, Râ, Baal, Seth, Vulcain, Neptune. Immenses étaient leurs
pouvoirs, et ils en usaient sans compter pour tourmenter et asservir
leurs frères les hommes. Pourtant, malgré tout leur savoir, ils ne
parvenaient pas à accéder au double sens des glyphes que contenaient les
grimoires. Bientôt ceux-ci s'éteignirent, endormis par la cruauté et les
rivalités qui dévastaient le monde. Les sept portes de la cité de
l'octave et les douze piliers du sanctuaire des accords se fermèrent aux
yeux des occupants de l'olympe.

Privés de toute source d'imagination, ils en étaient réduits à subir une
lente et inexorable glissade vers l'oubli. Les intrigues les plus torves
qu'ils fomentaient ne parvenaient qu'à accélérer leur chute. Comme ils
se disputaient la pomme de la vengeance et les flammes des plus belles
villes, les dieux évincés décidèrent de leur coté d'envoyer Prométhée
offrir la science aux hommes leurs frères. Une pousse d'abord timide
dont se gaussèrent les monarques, mais qui acquit rapidement une ampleur
suffisante pour menacer l'équilibre du pouvoir.

Voyant croître à nouveau l'arbre de lumière, Zeus convoqua le conseil et
leur proposa d'aller punir le coupable. Mais il était déjà trop tard :
le serpent aux mille tentacules les avaient tellement divisés qu'aucune
décision n'aboutit, si ce n'est celle de ne rien décider du tout. Plus
grave encore, un cercle restreint de félons excédés par les abus de leur
souverain décida d'ouvrir les portes qui gardaient la frontière aux
alentours de brocéliande. Les dieux des origines ne se firent pas prier
pour se ruer à l'assaut du royaume qui tomba comme un fruit mûr. Il y
eut des discours, il y eut du bruit. Ce fut la fin de l'âge second.

⁂

Les palais olympiens ne changèrent pas seulement de mains, leur destin
fut également irrémédiablement modifié. Le panthéon parla république et
démocratie. On bâtit un hémicycle autour de l'ancienne table ronde, et
les voix des grands orateurs y résonnèrent pendant des siècles. Les
utopies se réalisaient parce qu'il se trouvait assez de monde pour les
désirer. Une ère dorée commençait.

Le sénat envoya une alliance formée autour des elfes pour déposer les
anciens tyrans de la terre : les sylphes balayèrent de leurs rafales
l'âcre fumée des maléfices ; les racines magiques des dryades
transformèrent la lave des anciennes guerres en un terreau fertile ;
enfin, les ondines dispensèrent avec largesse l'eau bienfaitrice de
leurs oasis de vie. Ils se placèrent ensuite tous au centre des quatre
éléments et leur pacte fut connu sous le nom de l'ordre crépusculaire.
Ensemble, ils veillèrent sur le fragile équilibre des forces de la
lumière et des ténèbres. Car il est dit dans l'un des échos de la
mélodie originelle qu'il n'y a pas de nuit sans étoile ni de jour sans
ombre.

Les esprits mauvais refluèrent et l'on connu des floraisons sans
précédent. Des pluies de pétales tombaient des cerisiers dans un
printemps qui ne semblait jamais devoir prendre fin. Les licornes
d'abondance paissaient librement dans les champs infinis du solfège
symphonique. Les dragons ne soufflaient plus que le feu sacré de
l'amour. L'harmonie rayonnait jusque dans les plus obscures des
galeries.

Voyant cela, les humains, désireux de faire montre de leur
reconnaissance, se mirent à idolâtrer les sages du panthéon. Ces
derniers, un peu gênés, décidèrent d'envoyer des missives à leurs
frères. Ils voulurent leur expliquer qu'hommes et dieux étaient nés du
même ventre de l'éternité, que la meilleure façon de les remercier était
de participer tout comme eux aux réjouissances. Certains comprirent,
mais quelques-uns contestèrent l'origine des graphèmes dessinés sur les
constellations du zodiaque ou feignirent de ne rien entendre et
continuèrent à se prosterner.

Cela n'aurait rien eu de véritablement gênant si les plus orgueilleux
des idolâtrés ne s'étaient enivrés des cultes dont ils étaient l'objet.
Rares au début, les orgies atlantes se firent de plus en plus fréquentes
et démesurées, au point que Bacchus lui-même s'inquiéta de ces excès.
Les descendants des Ducs déchus en profitèrent pour rassembler les
mécontents autour d'un prétexte qu'ils nommèrent Vertu. Le clan des
Vertueux, qui comptait parmi les moins sages dans ses rangs, s'empressa
de fomenter un complot pour renverser la démocratie.

C'est alors que les procès contre les adorateurs et leurs adorés
commencèrent. Un par un, les verrous scellant l'équilibre se voyaient
démantelés, et ce dans l'ignorance et l'indifférence générale. Pourtant,
quelques rares sénateurs prirent le temps de consulter l'horizon des
augures, auprès duquel ils distinguèrent de sombres présages. Comme ils
ne pouvaient rien tenter publiquement contre la montée fulgurante du
fanatisme, ils convoquèrent les phénix, un couple d'inséparables
contenant la mémoire des âges passés, et leur confièrent les clefs des
partitions originelles. Ensuite, ils leur firent boire l'élixir de la
résurrection afin qu'ils puissent revivre depuis leurs cendres si jamais
ils venaient à être consumés par la tempête qui menaçait. Ils furent
ensuite séparés dans l'attente d'une ère favorable à leur éclosion.

Il ne fallut plus attendre longtemps pour que les premiers éclairs
apparaissent. Le déluge provoqua une rapide montée des flots de la
folie. La république fragilisée s'enlisa rapidement dans la guerre
civile puis le chaos. L'ordre crépusculaire tenta de s'interposer, mais
il ne put empêcher le cataclysme de balayer le souffle léger du
printemps. Plutôt que de continuer une lutte perdue d'avance, les elfes
se replièrent à nouveau dans les lieux enchantés qui demeuraient
inaccessibles au cyclone dévastateur. Il y eut des discours, il y eut du
bruit. Ce fut la fin de l'âge tiers.

⁂

Et les ronces proliférèrent sur les ruines de l'hémicycle. Les Vertueux
scellèrent les portes invisibles de brocéliande en les lestant d'une
indicible terreur qu'ils nommèrent Enfer. Elle pesait si lourd que les
dieux réfugiés dans son enceinte furent incapables de les réouvrir. Afin
de mieux asseoir leur pouvoir, les nouveaux tyrans décrétèrent le règne
de l'unicité et interdirent sans ménagement tout culte qui n'était pas
des leurs. Et le sang des brebis innocentes commença à ruisseler sur les
autels du sacrifice.

La faction ennemie vaincue, ces dieux ivres de violence
s'entre-déchirèrent. Les coups des poignards empoisonnés décimèrent les
rangs des prétendants au pouvoir absolu. Il vint un moment où il ne
furent plus que trois à se partager l'empire. Mais ils étaient entré
dans une spirale qui ne permettrait qu'à un seul d'entre-eux de
s'échapper. Et les deux plus rusés du triumvirat se liguèrent contre le
troisième avant de le projeter dans les abysses de l'insondable néant.
Le duel ultime put enfin commencer.

Ils étaient de force égale et le combat dura pendant des siècles.
Jusqu'au jour où Iacchus, l'ainé du dieu de Dextre, parvint par hasard à
réunir les deux phénix abandonnés par les anciens et perçut le léger
rayonnement qui s'en dégageait. Il déploya les ailes des songes pour
tenter de les communiquer aux hommes dans le langage sacré du choeur,
mais ceux-ci l'avaient oublié depuis longtemps déjà.

Le patriarche, prévenu du danger, exila ce fils turbulent et le remplaça
à la charge de gouverneur par son cadet. Le nouveau tribun s'empressa de
reprendre les hymnes de son frère. Mais il modula sa voix d'un trémolo
si discordant qu'il exhorta les légions saintes à se baigner dans le
sang des infidèles. L'amour prit une robe de haine, la compréhension se
hérissa des tribunaux de la foi et la lumière stellaire se métamorphosa
en feu colérique. Bientôt, les phalanges meurtrières fondirent sur les
terres du sinistre dieu Senestre qui prit peur pour la première fois.

Il eut si peur qu'il entreprit lui aussi de moduler d'horreur les hymnes
d'Iacchus. Il en modifia même des mesures entières, afin de rendre plus
efficaces les vibrations de la destruction. La liberté fut rouée de
coups, couverte de pierres et enterrée vivante sous un sordide linceul
de toile grossière. La barbarie des rites antiques fut cautionnée,
encensée même, si bien que la cruauté eut tout loisir de contaminer les
fidèles. Le dieu Senestre tenait enfin ses légions.

Les démons des deux camps ne se firent pas prier pour répandre la suie
des suppliciés et le ciel se couvrit d'une teinte plus sombre que
jamais. La peste tomba en pluie de cendres sur les champs noircis par
les nuées de sauterelles et la famine plongea définitivement l'ancien
monde dans l'obscurantisme. Il y eut des discours, il y eut du bruit. Ce
fut la fin de l'âge quart.

⁂

Mais il arrive un temps où même la haine la plus forcenée ne trouve plus
rien à brûler. Mais il arrive un temps où même la terreur se dissout, où
même les enfers s'éteignent. Voici ce qui se produisit : à mesure que
les cendres les plus volatiles retombaient et que de timides rayons de
soleil éclairaient de nouveau la terre, l'un d'eux alla frapper dans les
décombres les phénix qui renaissaient. Un prêtre de Dextre fut illuminé
par ces deux étoiles de conscience qui transperçaient les ténèbres. De
ce jour, il sut comment imprimer et propager les signes des origines sur
la fine écorce de la multitude.

Ainsi, tous purent comparer ce qu'il en était de ce qui leur avait été
raconté. Il y eut des révoltes et des schismes qui morcelèrent les
phalanges de Dextre en de nombreuses factions. Le troisième dieu,
Austère, profita de la confusion pour s'échapper du néant et vint
attiser les conflits. Le monde semblait à nouveau faire voile vers
d'interminables ouragans.

Cependant, à l'ombre des lanternes magiques, le chemin vers la fertilité
polyphonique de brocéliande se rouvrait, lentement mais inexorablement.
Année après année, la pluie ternissait les étendards ; les glaives
épuisés retombaient avec fracas ; les fondations corrodées des temples
n'arrivaient plus à soutenir le poids monstrueux de la tyrannie et de
l'intransigeance.

C'est alors que les lumières s'allumèrent une à une. Parce qu'ils
reflétaient les fleuves flamboyants des sérénades mélancoliques, les
étincelants lustres baroques permettaient de discerner, à travers les
masques des bals vénitiens, les yeux qui sont des lèvres et les lèvres
qui sont des yeux. Ainsi, la mesquinerie des intrigues et les rouages
des complots furent enfin visibles au grand jour. Partout, le murmure
avait des oreilles, la contestation envahissait dans la clandestinité
les anciens cloîtres de la pensée. L'humanité se redécouvrait dans
l'éclat vivace de l'âge d'or.

Or, il advint qu'une douce brise fit tourbillonner les dés de
l'histoire. Les lézardes fusèrent de leurs cachettes et sillonnèrent la
pierre surchauffée. Les remparts du régime en ruine s'écroulèrent d'une
seule voix et le souffle balaya les derniers résidus de l'obscurantisme.
Il y eut des discours, il y eut du bruit. Ce fut la fin de l'âge
cinquième.

⁂

Grande est la colère du volcan qui se relève d'un trop long sommeil.
Grande, la colère des esclaves libérés qui jaillirent du cratère,
emportant tout sur leur passage. Grande, oui. Grande et aveugle. Nul ne
songea à filtrer le bon grain dans les sacs d'ivraie. Nul ne remarqua
non plus l'ivraie infiltrée dans les sacs de grains. Les premiers furent
brûlés, les seconds encensés.

Les esprits de l'ordre crépusculaire s'échinèrent à rétablir un semblant
de calme tout au long de ce siècle torturé. Ils remportèrent de nombreux
succès : la vie pouvait de nouveau voir au-delà de la matière, l'utopie
rebatissait peu à peu l'équilbre des premiers âges, les arts aspiraient
de grandes bouffées d'oxygène et les chants florissaient comme autrefois
les collines de la jeune saison.

Mais tandis qu'ils oeuvraient, ils sentirent s'enfoncer dans la chair de
leurs doutes le double tranchant d'une lame insidieuse. Cette même lame
qu'ils avaient sorti de leur propre fourreau pour vaincre l'ignorance,
la machinerie tumultueuse de l'idée et du savoir, s'emballait, hors de
contrôle. S'ils tentèrent de la calmer, rien n'y fit : chacun ne joua
plus que ses propres mélodies, et le souvenir pâlissant de l'harmonie se
transforma rapidement en bruit informe. Le monde se précipitait à toute
allure vers le chaos.

L'inconscient humain, apeuré par sa liberté retrouvée, tentait-il de se
recréer d'autres chaînes ? Toujours est-il que, devant l'alliance
impuissante, de nouvelles religions apparurent. Elles adorèrent
l'Industrie, la Finance, le Syndicat, le Travail et se proclamèrent
Idéologies et Partis. Personne n'était dupe, et au fond les noms de
leurs dieux importe peu. Apprenez seulement qu'une à une, étouffées par
la suie des fabriques, le mirage de la richesse et le sang des
révolutions, les lumières s'éteignirent.

Et c'est par une nuit sans lune qu'un double éclair fendit le ciel. Les
insectes apeurés vrombissaient et tournoyaient autour des ampoules
mortes, et nul n'entendit les enfants hideux de la vengeance vagir dans
le berceau maudit des tranchées. Des bébés qui, lorsqu'ils furent de
jeunes adultes irresponsables, déclenchèrent un autre orage, comme un
écho amplifié de leur naissance. Ils allèrent jusqu'à libérer l'esprit
de la matière. C'est alors que l'oeil d'un terrible cyclone s'ouvrit
sous les pieds de l'humanité désemparée.

Un oeil perçant, insistant, qui l'observa durant de longues décennies,
guettant la moindre faille qui lui permettrait de déclencher
l'apocalypse. Mince était la corde nerveuse qui la retint de sombrer
dans le gouffre sans fond de la folie. Et pendant ce temps, la faux
sciait les branches de l'espoir et le napalm désertifiait les plaines
fertiles de l'idée. L'angoisse refaisait surface, et bientôt la terreur
et la lassitude furent telles que plus personne n'osa ou ne voulut plus
croire en rien.

Cette torpeur semblait vouloir durer des siècles, lorsqu'à la surprise
générale, le regard menaçant s'effondra. Il y eut des discours, il y eut
du bruit. Ce fut la fin de l'âge sixième.

⁂

A peine la paix triomphait-elle sur scène qu'on la négociait déjà en
coulisse. Tapis derrière le confortable rideau des apparences, le prix
grimpait. On construisit une parodie de l'âge d'or en carton pâte, ce
qui n'empêcha pas le malaise de grandir, bien au contraire. Et si tous
feignaient de ne pas voir le béton sous la peinture dorée qui
s'écaillait, la société se désagrégeait doucement dans une guerre
sournoise. Une guerre dont les armes dématérialisées continuèrent de
stériliser les consciences.

Attiré par l'appel d'air de ces vastes territoires désertifiés, le
triumvirat des anciens dieux Vertueux refit son apparition. Puisque la
verte prairie ne parvenait plus à pousser, ils en profitèrent pour semer
de la mauvaise herbe synthétique dans ces esprits affaiblis et
ignorants. Ces esprits prêts à tout pour fuir le néant qui les envahit.

Et nous en sommes là.

Il se dit que les univers trop vieux finissent par retourner au néant.
Il se dit que de titanesques pendules se balancent en tous sens pour
l'éternité, qu'ils régissent les cycles des civilisations et des
barbaries, et que même les dieux sont incapables de les arrêter. Il se
dit beaucoup de choses, mais rarement que le fatalisme provoque
l'apparition des monstres qu'il craint ; rarement vous entendrez que les
songes sont créateurs, et que c'est à nous de décider s'ils doivent se
terminer en rêve ou en cauchemar.

[[../index.php][Accueil]]
