
#+STARTUP: showall

#+TITLE: Eclats de vers : Poésie : Muses
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index littéraire]]

#+../include: "../../include/navigan-1.org"

#+TOC: headlines 1

* Quatorze vers et plus

Art pathétique, 1ère partie : de l'art de ne pas faire un sonnet.

#+BEGIN_CENTER
#+BEGIN_VERSE
    « Entonnons une églogue où s’abreuve un essaim
    De pieds nus et lactés sous un ciel sans nuage.
    Muse, ajuste ton col, que ton raide lignage
    Soit sculpté noblement sur ton buste abyssin.

    Que la Règle pédante agrippe le buccin
    Pour clamer à tous vents comment faire un vers sage !
    Que ton luth soit carré, qu’il incline au servage
    La Rime sourde aux yeux, le Mètre capucin.

    Intitule Poëme un péplum sans mérite
    Où se pâme, où se tord la Vierge sodomite
    Enjambée – en secret – par un jeune Berger.

    Car le Cadre interdit la voltige à Pégase,
    Le frisson de la Nymphe et l’écho trop léger
    Dont il verse le flot dans la pompe d’un vase. »

        *

    Ainsi parle celui qui n’ose s’envoler.
#+END_VERSE
#+END_CENTER

* Réseau

#+BEGIN_CENTER
#+BEGIN_VERSE
    Le h en est muet quand je voudrais l’hurler
    Jusqu'à ce que l'écho se rappelle ma voix
    Le h en est muet j’ai dû trop l’aspirer
    A force d’essouffler des comètes de soie

    Pourtant j’ai libéré les lettres de leur cage
    Et la montagne au moins se rappelle ma voix
    Pourtant j’ai libéré le feu sur chaque page
    Mais il ne reste rien des comètes de soie

    Le vide est le vélin sur lequel j’ai écrit
    J’ai su l’ensemencer dans un lacet de phrases
    Et chaque goutte d’encre et chaque idée depuis
    Batifole au hasard dans un lacet de phrases

    Et chaque goutte d’encre imbibe le treillis
    Volant de maille en maille ailes gonflées d’extase
    Le vide est le vélin mais je le sais qui vit
    Sa texture palpite ailes gonflées d’extase

    C’est un calque en relief sculpté recto-verso
    La vallée devient col pour qui tourne la page
    C’est un calque en relief chaque sens chaque mot
    Contient son négatif et l’eau est un rivage

    Parfois la brise émue fait tinter les cigales
    Le panier en osier louvoie comme un serpent
    Le mistral est rageur le drapeau claque au vent
    Girouette emportée de rafale en rafale

    Le tout part en fumée quand tombe sur l’enclume
    Surchauffée la vapeur des trombes d’eau transies
    Si c’est pour être sobre autant ranger la plume
    Que l'épée soit trempée par l'écume en furie

    La muse aime la mer le ressac le tumulte
    Et sait ressusciter les cendres des chevaux
    L’ivresse de l’air frais sur sa peau qui exulte
    Fera bientôt revivre un nouvel écheveau

    Parfois sur le filet les cheveux des étoiles
    Déposent doucement de ces tresses bouclées
    Si fines que le fil paraît soudain grossier
    Et qu’il faut invoquer les fées du carnaval

    Pour arriver à rendre un zeste de beauté
    A l'éclat qu’on retient dans une lampe à huile
    Gloire à la perspective au trompe-l’oeil fertile
    Car ils sont la racine où l’astre peut germer

    Si la lettre est éteinte elle n’attend qu’une âme
    Pour redorer ses feux tout vibrant de mystère
    Le son est un joyau un vivant hologramme
    Tapis dans la pénombre et guettant la lumière

    L'étincelle c’est toi dont le coeur est ouvert
    Toi dont la voix sensible allume des soleils
    Toi qui voit rougeoyer à travers la poussière
    Le pétale assoupi d’une rose vermeille
#+END_VERSE
#+END_CENTER

* Brise nocturne

#+BEGIN_CENTER
#+BEGIN_VERSE
    Je n’ai plus aucun rève, ils se sont tous enfuis
    Là haut, dans les bourgeons d’un arbre vaporeux
    De leurs ailes d’albâtre ont quitté mon ennui
    Emmenant les clefs d’or des accords harmonieux

    Je ne sais plus ouvrir les coffres verrouillés
    Le santal vainqueur tient à l'écart les curieux
    Il est juste permis de sentir transpirer
    Le vertige assoupis sur l’oreiller des cieux

    Il ne me reste plus qu’un voile déchiré
    Habillant une brise à la vibrante voix
    Qui me dit : « Rejoins-nous ! Quitte ce dur sommier !
    Viens flotter avec nous au souffle des hautbois ! »

    Mais sans plume, impossible de quitter ce sol
    Qui me retient de ses invisibles courroies
    Ni parfum, ni encens, rien n’y fait. De ces fioles
    Seul un brouillard blafard s’en échappe et me noie

    Je laisse ma fenêtre cueillir les paroles
    Du vent farceur qui vient la voiler de rosée
    C’est ainsi que parfois quelque strophe frivole
    Se dépose sur le vitrail de mes pensées
#+END_VERSE
#+END_CENTER

* Le chat

#+BEGIN_CENTER
#+BEGIN_VERSE
    Une de mes muses est un chat
    Qui travaille sur mon sofa

    Quand il dort mes rimes ronronnent
    Ses pattes feutrées les façonnent

    Lorsqu’il a faim et qu’il miaule
    Elles pleurent comme des saules

    Si l’on ne voit que ses moustaches
    Les vers murmurent et puis se cachent

    Sa queue remue et se rebiffe ?
    Est-il fâché la strophe griffe !
#+END_VERSE
#+END_CENTER

* Frayeur de l'écrivain

#+BEGIN_CENTER
#+BEGIN_VERSE
    La recherche incessante et effrénée des lignes
    Me conduit quelques fois devant les yeux étranges
    D’une longue et maline et large feuille blanche
    Dans ces moments elle semble me faire un signe

    Elle veut que je la trempe de beaucoup d’encre
    Elle me donne alors une grande inspiration
    C’est comme si ses lignes produisaient des sons
    Alors pour un moment, je jette amarres et ancre

    Alors je manipule tous ses recoins secrets
    Je la froisse et puis je l’adoucit sans remords
    Elle se livre à moi dans un curieux ballet
    Et la frénésie dure au moins jusqu'à l’aurore
#+END_VERSE
#+END_CENTER

* La Muse aérée

#+BEGIN_CENTER
#+BEGIN_VERSE
    - Viens donc ici ma Muse, ici sur ce sofa
    Etale-toi, m’amuse, qu’as-tu vu là-bas ?
    Ne cèle rien ma Muse, aux rêves guide-moi,
    Toi qui connais, j’abuse, l'âme des émois.

    Balaie en moi, j’en use, ce froid engrenage
    Raide et implacable, lui qui fauche et qui rase
    Instant aprèse instant.
    Son nom ? Nul ne le sait. Il vit loin de l’extase
    Et porte convenances en guise d’ornements

    Où es-tu ma coquine, ma bise volage ?
    Uses-tu de tes charmes auprès d’une autre plume ?
    Rognes-tu sur ta peine, as-tu peur qu’on s’enrhume ?
    - Assez de cette plainte, n’entends-tu pas mon rire ?
    Gagnée par ta complainte, il me faut découvrir
    As-tu pas vu mon jeu, je suis là dans tes lignes
    Ne vois-tu pas ton front, où je souffle en sourdine ?
#+END_VERSE
#+END_CENTER

* Les violons

#+BEGIN_CENTER
#+BEGIN_VERSE
    Vibrent quatre cordes chantant chaque saison
    Il est le ré, l’automne, l’archet tourmenté
    Ou bien le sourd hiver de son sol en haillon,
    Libère de son la un printemps agité ;
    Oiseau du si, du gazouilli sifflant l'été.
    Neige-t-il en son âme, le bois est tout en pleurs ;
    S'il se noie dans la joie, ses accords sont rieurs.
#+END_VERSE
#+END_CENTER

* Une flûte

#+BEGIN_CENTER
#+BEGIN_VERSE
    J'étais bien jeune encor. J’arpentais les ruelles
    Des livres verrouillés et des claviers rongeurs.
    Déjà une souris riait sur mes doigts tendres
    Mais je l’oubliais sous un écran de poussière.

    Des forets à la main, les insidieux sapeurs
    Du regret ne cessaient de partout se répandre.
    Mais je ne voyais rien des journées qu’ils enterrent
    Lorsqu’ils minent les nuits blanchies qui nous attellent.

    Mon rire se taisait, vaincu par les calandres
    Qui écrasent dans leur monochrome lumière
    Le fuyant horizon de nos oeuvres trop frèles
    Et déroulent l’oubli géant et dévoreur.

    Au fil de l’inutile où la fatigue éclaire
    Je dételai bientôt le labeur et sa selle
    De sueur. Laissant là mon carcan de rigueur,
    Je construisis une armure pour me défendre.

    J’avais fermé ma porte aux cris et aux appels
    Lorsqu'à travers le chêne massif de l’horreur
    J’entendis une voix surmontant les cassandres
    Chantant : « Réveille-toi ! ». Et mon oeil s’est ouvert
#+END_VERSE
#+END_CENTER

* Plénitude

#+BEGIN_CENTER
#+BEGIN_VERSE
    Au plus profond des bois, où des troncs d’autrefois
    Dénouent de leurs senteurs le murmure du bois
    Il m’a semblé entendre, un murmure, une voix

    Il se cache souvent dans les plus hauts branchages
    Murmurant aux passants qui fuient les orages
    "Viens, assieds-toi ici, écoute mon feuillage
    Ecoute mon ramage, il vient du fond des âges

    Quand les arbustes bruissent, c’est la voix d’une brise
    Qui emmène en soupirs nos soucis, nos querelles.
    Par d’impalpables bises, la belle fraternise
    Invisible coquine peignant une aquarelle.
    Ces jours l’esprit s'élève, et guidé par le vent
    Il parcourre royaumes, cités et châteaux,
    Montagnes et forêts, océans et ruisseaux
    Voluptueux et calmes autant qu'éblouissants.
    Lors, presque sans un bruit, il s’assied sur le buis
    Et réveille son corps tout encore endormi.
#+END_VERSE
#+END_CENTER

* Etrange blessure

#+BEGIN_CENTER
#+BEGIN_VERSE
    Les vers s'échappent de ces étranges blessures
    D’où ruisselle un sang clair, épais et translucide,
    Un sang clair sans couleur, sans défaut sans souillure
    S'écoulant lentement des lèvres insipides.

    Les vers chantent dans les ruisseaux ensorcelés
    Leur filet timide jaillit de nulle part
    Mais leur timbre grave trahit la cavité
    Imbibé de larmes de tristesse et d’espoir.

    Le long de la voûte du temple pétrifié
    Des perles chrysalides prennent leur envol
    Hors du cocon des souvenirs fossilisés,
    Arc-en-ciel d'émotions intenses et frivoles.

    En essaims satinés les échos se propagent,
    Tableaux tournoyant des papillons colorés.
    L’intérieur reste exsangue, las mais soulagé
    D’avoir plus libérer le trop-plein de l’orage.
#+END_VERSE
#+END_CENTER



[[../index.php][Accueil]]

