
#+STARTUP: showall

#+TITLE: Eclats de vers : Agora 01 : Constitution
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Principes

#+TOC: headlines 1 local


** Souveraineté

Toute constitution, qu’elle soit locale, nationale, fédérale ou
confédérale, transfère à la collectivité une partie de la souveraineté
des constituants afin d’en garantir le fonctionnement harmonieux.

Une constitution saine garantit un maximum de liberté à l’individu et
aux constituants. Le transfert de souveraineté doit donc être minimal
et justifié.


** Équilibre

Il est important de veiller à l’équilibre entre :

  - la liberté individuelle (république)
  - la volonté du peuple (démocratie directe)
    + exercée par référendum sur initiative de la population
  - la démocratie représentative
    + exercée via des représentants élus par les citoyens qu’ils représentent
  - la conscience individuelle
    + la liberté ne peut réellement exister qu’en conscience
  - la conscience collective
  - les niveaux de pouvoir
    + la commune : communauté locale
    + la cité : regroupement de communes
    + l’autonomie de l’état membre
    + les compétences fédérales
    + les compétences confédérales


** Compétence

Pour savoir qui est compétent :

  - individu
  - commune
  - cité
  - état
  - fédération
  - confédération

répondre à la question : qui est (principalement) concerné ?


** Synthèse


*** Liberté individuelle

  - respect de la liberté individuelle, pour éviter que la démocratie
    ne devienne la dictature de la majorité
    + le transfert de souveraineté à l’état doit être minimal
    + la liberté individuelle doit être garantie par la constitution
    + le citoyen doit disposer de ressources qui garantissent son indépendance
  - l’État doit intervenir
    + au minimum
    + là où c’est nécessaire
    + de façon cohérente


*** Local

  - importance du local (commune à taille humaine)
    + entraide
    + partage
    + échange
    + économie
    + services
    + contre-pouvoir à l’état central


*** Démocratie directe

  - démocratie directe, via les référendums
    + prend le pas sur
      * les décisions des représentants
      * les traités internationaux
    + doit être en équilibre avec la liberté individuelle
    + à tous les nivaux
      * individu
      * commune
      * cité
      * état
      * fédération
      * confédération
  - représentativité
    + par élection au suffrage universel
    + concerne tous les pouvoirs
      * législatif
      * exécutif
      * juridique
	- création d’un conseil chargé de vérifier la neutralité des juges
      * financier
	- fiscal
	- bancaire
	- marché
      * territoire
      * sociétal
      * scientifique
      * média
      * services publics


*** Information

  - importance de la libre circulation de l’information
    + débats
    + décisions


*** Concentration de pouvoir

  - éviter toute concentration excessive de pouvoir
    + mène à une instabilité et à un déséquilibre
    + indépendance des pouvoirs
    + éviter les cumuls de mandats
    + mandats partiellement impératifs dans certains cas afin de
      fixer un cadre d’action aux représentants ?
  - concerne (liste non exhaustive)
    + politique
    + juridique
    + financier
    + économique
    + presse


*** Transparence

  - un impôt = un pot commun = un objectif clairement défini
    + pas question de rediriger l’argent ailleurs
    + prévoir une structure juridique, un fond par impôt
    + impôt générique : pour huiler le mécanisme, mais il doit être
      bien cadré et contrôlé


*** Services publics

Réseau dense de services publics pour que chaque citoyen puisse en profiter


** Économie

  - Remplacer l’idée de croissance par celle du bien-être et de la prospérité
  - Profiter des avantages des marchés sans en subir les défauts
  - Réguler où il le faut pour éviter les instabilités
  - Éviter le gaspillage
    * Généraliser le recyclage & la récupération d’énergie
    * Ne pas pousser à consommer excessivement
    * Télé-travail
    * Transports en commun
  - Une société qui domine un marché doit, suivant les cas
    * Étre divisée en plusieurs sociétés de taille réduite afin de
      relancer la concurrence
    * Dans certains cas, un contrôle de l’état avec régulation se
      justifie
      - Régulation des prix, salaires, de la qualité, quantité, etc
      - Secteurs : Eau, Énergie, Transports, Etc
  - International
    * Protectionisme vis à vis des pays qui n’ont pas les mêmes
      avantages sociaux
    * Protectionisme vis à vis des pays nn démocratiques
    * Développer des conventions internationales pour que ces
      avantages soient adoptés le plus largement possible


* Fédération

#+TOC: headlines 1 local

Un *état* est un ensemble de citoyens.

Une *fédération* est un ensemble d'états *et* l’ensemble des citoyens
formé par l’union des citoyens des états membres. Cette propriété est
appelée *principe de superposition*. Tout citoyen d’un état membre est
donc également citoyen de la fédération. Inversément, tout citoyen de
la fédération est membre d’un et d’un seul de ses états.

Tout citoyen est libre de choisir son état et d’en changer à sa guise.


** Souveraineté

Dans une fédération, les niveaux de pouvoir sont typiquement :

  - l’individu = citoyen
  - la commune = collectivité locale
  - la cité = regroupement de communes
  - l’état = entité fédérée
  - la fédération

Par conséquent, les transferts de souveraineté suivants doivent être
minimaux :

  - individu --> commune
  - individu --> cité
  - individu --> état
  - individu --> fédération
  - commune --> cité
  - commune --> état
  - commune --> fédération
  - cité --> état
  - cité --> fédération
  - état --> fédération

Chaque transfert de souveraineté doit être cité explicitement dans la
constitution.


* Confédération

Une *confédération* est une union d’états souverains qui décident de
s’occuper ensemble de sujets définis par un traité fondateur.

Afin de maintenir l’équilibre entre les niveaux de pouvoir, l’ensemble
des citoyens, l’ensemble des états et l’ensemble des fédérations de la
confédération doivent être représentés dans le processus de décision.


** Souveraineté

Dans une confédération, les niveaux de pouvoir sont typiquement :

  - l’individu = citoyen
  - la commune = collectivité locale
  - la cité = regroupement de communes
  - l’état = entité fédérée
  - la fédération

Par conséquent, les transferts de souveraineté suivants doivent être
minimaux

  - individu --> commune
  - individu --> cité
  - individu --> état
  - individu --> fédération
  - individu --> confédération
  - commune --> cité
  - commune --> état
  - commune --> fédération
  - commune --> confédération
  - cité --> état
  - cité --> fédération
  - cité --> confédération
  - état --> fédération
  - état --> confédération
  - fédération --> confédération

Chaque transfert de souveraineté doit être cité explicitement dans la
constitution.


** Modification de la constitution

Toute modification de la constitution de la confédération doit être
approuvée par une large majorité :

  - de l’ensemble de la population confédérale, par référendum
  - des communes
  - des cités
  - des états membres
  - des fédérationx membres

Toute modification de la constitution d’une fédérationx doit être
approuvée par une majorité aux deux-tiers :

  - de l’ensemble de la population de la fédérationx, par référendum
  - des communes
  - des cités
  - des états membres

Toute modification de la constitution d’un état doit être approuvée
par une majorité aux deux-tiers :

  - de l’ensemble de la population de l’état, par référendum
  - des communes
  - des cités

Toute modification de la constitution d’une cité doit être approuvée
par une majorité aux deux-tiers :

  - de l’ensemble de la population de la cité, par référendum
  - des communes membres

Toute modification de la constitution d’une commune doit être
approuvée par une majorité aux deux-tiers

  - de l’ensemble de la population communale, par référendum


* Confédération versus fédération


** Confédération

  - l’état membre garde une autonomie plus grande
  - alliance, entraide, coopération
  - institutions confédérales minimales
    + le rôle des assemblées confédérales est de
      * coordonner les actions des états membres
      * organiser des services communs
      * servir d’intermédiaire ou de garantie dans les relations entre
        les états
  - cadre minimal pour la constitution des états membres
    + droits humains fondamentaux
    + bien-être de la population
    + valeurs républicaines & démocratiques


** Fédération

  - transitivité
    + un membre d’une fédération qui est elle même membre de la
      confédération est automatiquement membre de la confédération
  - équilibre entre
    + l’autonomie des états membres
    + les responsabilités fédérales
    + l’harmonisation des règles fédérales parmi les états membres
  - cadre pour la constitution des états membres
    + droits humains fondamentaux
    + bien-être de la population
    + liberté individuelle républicaine
    + démocratie directe, via les référendums
    + système de vote


* Confédération de fédérations

On peut imaginer une confédération composée :

  - de fédérations
  - d’états isolés
  - de cités isolées
  - de communes isolées

où chaque état inclu dans une fédération membre est automatiquement
inclue dans la confédération.

On a alors les niveaux de pouvoir :

  - individu
  - commune
  - cité
  - état
  - fédération
  - confédération

et les transferts minimaux de souveraineté :

  - individu --> commune
  - individu --> état
  - individu --> fédération
  - individu --> confédération
  - commune --> état
  - commune --> fédération
  - commune --> confédération
  - état --> fédération
  - état --> confédération
  - fédération --> confédération


* Assemblées

#+TOC: headlines 1 local


** Représentativité

Une assemblée peut être

  - populaire : chaque citoyen y dispose d’un droit de vote
  - représentative : composée de représentants élus


** Décisions

Le mode de décision des assemblées est constitué d’une phase
de discussion et de deux tours.


*** Discussions

Les votes sont précédés d’une période de discussion
permettant de proposer une loi, de débattre des amendements,
des variantes, etc.


*** Premier tour

Au premier tour, les différentes options proposées (par exemple les
variantes d’une même loi) sont placées sur les bulletins de vote.
Ensuite, chaque membre de l’assemblée attribue un nombre de points
entier compris entre +5 et -5 à chacune des options envisagées, et
l’option victorieuse est celle ayant recolté le plus de points sur
l’ensemble des bulletins.

En cas d’ex-aequo, l’option victorieuse est, par ordre d’importance
décroissant :

  - celle ayant reçu le plus de votes +5
  - celle ayant reçu le moins de votes -5
  - celle ayant reçu le plus de votes +4
  - celle ayant reçu le moins de votes -4
  - celle ayant reçu le plus de votes +3
  - celle ayant reçu le moins de votes -3
  - celle ayant reçu le plus de votes +2
  - celle ayant reçu le moins de votes -2
  - celle ayant reçu le plus de votes +1
  - celle ayant reçu le moins de votes -1


*** Second tour

Au second tour, chaque membre de l’assemblée peut s’abstenir
ou voter pour ou contre l’option victorieuse du premier tour.
Il lui suffit de remplir le bulletin suivant son choix :

  - +1 : vote favorable
  - 0 : abstention
  - -1 : vote défavorable

On évalue ensuite le score moyen.

A la majorité simple, l’option n’est appliquée que si le score
moyen est strictement positif.

A la majorité /R/, l’option n’est appliquée que si l'écart
entre le score moyen /S/ et la valeur la plus basse possible (-1)
est au moins /R/ fois plus importante que l'écart entre /S/
et la valeur la plus haute posssible (+1). On doit donc avoir :

#+BEGIN_EXAMPLE
S - (-1) ≥ R × (+1 - S)
#+END_EXAMPLE

c’est-à-dire :

#+BEGIN_EXAMPLE
S ≥ (R - 1) / (R + 1)
#+END_EXAMPLE

À la majorité double, le score moyen doit donc être strictement
supérieur à 1/3

À la majorité triple, le score moyen doit donc être strictement
supérieur à 2/4 = 1/2


*** Absence de premier tour

Lorsqu’il n’y a qu’une seule option envisagée, le premier tour est
bien entendu inutile, l’assemblée passe alors directement au second
tour.


* Méta-assemblées

#+TOC: headlines 1 local

Une méta-assemblée est une assemblée

  - constituée de plusieurs sous-assemblées
  - où chaque sous-assemlée dispose d’un droit de vote avec un poids
    bien défini

On note /p_i/ le poids du droit de vote de la sous-assemlée /i/ et :

#+begin_center
P = Σ_j p_j
#+end_center

le poids total de toutes les sous-assemblées. Le poids relatif de la
 sous-assemblée /i/ s’écrit :

#+begin_center
π = p_i / P
#+end_center

Les méta-assemblées disposent de deux modes de fonctionnement.


** Fonctionnement


*** Fluide

Chaque membre de la méta-assemblée vote normalement, indépendamment
des autres membres de la sous-assemblée à laquelle il appartient.

Pour une option ou un candidat donné, on évalue ensuite le score moyen
/S_i/ obtenu dans chaque assemblée /i/. Le score final au niveau de la
méta-assemblée est :

#+BEGIN_EXAMPLE
S = ∑_i p_i × S_i / P
#+END_EXAMPLE

ou plus simplement :

#+BEGIN_EXAMPLE
S = ∑_i π_i × S_i
#+END_EXAMPLE


*** Granulaire

Chaque sous-assemblée effectue un vote interne et attribue les scores
suivant en fonction du résultat :

  - les options ou candidats ayant récolté les *meilleurs scores
    positifs* au vote interne reçoivent, en commençant par le premier,
    les points : +5, +4, +3, +2, +1
  - les options ou candidats ayant récolté les *plus faibles scores
    strictement négatifs* au vote interne reçoivent, en commençant par
    le dernier, les points : -5, -4, -3, -2, -1</li>
  - les autres options ou candidats reçoivent 0 point

Ces scores lui permettent de remplir un unique bulletin de vote
qu’elle remet à la méta-assemblée. L’ensemble des votes de chaque
sous-assemblée permet d'évaluer le résultat final.

Pour une option ou un candidat donné, notons /S_i/ le score obtenu
auprès de la sous-assemblée /i/. Le score au niveau de la
méta-assemblée sera alors :

#+BEGIN_EXAMPLE
S = ∑_i π_i × S_i
#+END_EXAMPLE


** Égalitaire

Dans une /méta-assemblée égalitaire/, chaque sous-assemblée
dispose d’un poids identique /p/. Notons /N/ le nombre
de sous-assemblées. Le poids total est alors de :

#+begin_center
P = N × p
#+end_center

et les poids relatifs :

#+begin_center
π_i = p / (N × p) = 1 / N
#+end_center

sont tous identiques :

#+begin_center
π = 1 / N
#+end_center


** Récursivité

Rien ne s’oppose à ce qu’une sous-assemblée soit elle-même une
méta-assemblée. Le jeu des assemblées peut donc former une
arborescence sur plusieurs niveaux.


** Ne pas confondre

Le concept de méta-assemblée est totalement indépendant de celui
de groupe électoral utilisé dans les élections progressives.


* Assemblées composite

Une assemblée composite est une assemblée

  - constituée de plusieurs sous-assemblées
  - où une décision n’est prise que si toutes les sous-assemblées l’approuvent

Il s’agit donc d’un mécanisme d’approbation multiple.


* Niveaux & assemblées d’une confédération


** Commune

  - assemblée populaire composée des citoyens d’une commune
  - assemblée représentative élue par les citoyens d’une commune


** Cité

  - assemblée populaire composée des citoyens d’une cité
  - assemblée représentative élue par les citoyens d’une commune
  - assemblée représentative de la communauté des communes, où chaque
    commune dispose du même nombre de représentants élus
    + méta-assemblée égalitaire où chaque commune de la cité dispose
      d’une assemblée


** État membre

  - assemblée des citoyens d’un état membre
  - assemblée représentative élue par les citoyens d’un état membre


** Fédération membre

Le principe de superposition implique au minimum une double
représentation : celle de l’ensemble des citoyens, et celle de
l’ensemble des états membres.


*** Populaire

  - assemblée des citoyens d’une fédération membre
  - assemblée populaire composée des états membres de la fédération
    + méta-assemblée égalitaire où chaque état membre de la fédération
      dispose d’une assemblée


*** Représentative

Principales :

  - assemblée représentative des citoyens, où chaque état dispose d’un
    nombre de représentants proportionnel à sa population
  - assemblée représentative de la communauté des états, où chaque
    état dispose du même nombre de représentants élus
    + méta-assemblée égalitaire où chaque état de la fédération
      dispose d’une assemblée

Autres :

  - méta-assemblée égalitaire où chaque commune de la fédération
    dispose d’une assemblée

  - assemblée des représentants des citoyens d’une commune
  - assemblée des représentants des citoyens d’un état
  - assemblée des représentants des citoyens de la fédération
  - méta-assemblée égalitaire des représentants des citoyens des communes de la fédération
  - méta-assemblée égalitaire des représentants des citoyens des états de la fédération


** Confédération

Le principe d’équilibre implique au minimum une triple
représentation : celle de l’ensemble des citoyens, celle de l’ensemble
des états membres, et celle de l’ensemble des fédérations membres.


*** Populaire

  - assemblée populaire composée des citoyens de la confédération
  - assemblée populaire composée des états membres de la confédération
    + méta-assemblée égalitaire où chaque état de la confédération
      dispose d’une assemblée
  - assemblée populaire composée des fédérations membres de la confédération
    + méta-assemblée égalitaire où chaque fédération de la
      confédération dispose d’une assemblée


*** Représentatives

  - assemblée représentative des citoyens de la confédération
  - assemblée représentative de la communauté des états membres, où
    chaque état dispose du même nombre de représentants élus
  - assemblée représentative de la communauté des fédérations membres,
    où chaque fédération dispose du même nombre de représentants élus

Méta assemblées :

  - méta-assemblée égalitaire où chaque commune de la confédération
    dispose d’une assemblée


* Référendum

#+TOC: headlines 1 local


** Introduction

Les citoyens sont directement impliqués dans les décisions au moyen de
*référendums*, aussi appelés *consultations populaires* ou
*votations*.

Lors d’un référendum, tous les citoyens d’une assemblée populaire
votent afin de prendre une décision ou d'élire une assemblée de
représentants.


** Universalité verticale

Les règles pour les consultations populaires sont valables au
niveau

  - d’une commune
  - d’un état
  - d’une fédération
  - de la confédération


** Sujets

Un référendum peut concerner :

  - Un article de la constitution
    + Création
    + Modification
    + Abrogation
  - Un article de loi
    + Création
    + Modification
    + Abrogation
  - La sanction ou la révocation d’un représentant
  - Initiative, questionnement ou véto concernant un des pouvoirs de l’état
    + Législatif
    + Exécutif
    + Juridique
    + Financier
    + Etc


** Initiative


*** Populaire

Les propositions donnant potentiellement lieu à une consultation
populaire peuvent résulter :

  - de l’initiative d’un nombre significatif de citoyens
  - de l’initiative d’un nombre significatif de citoyens d’une commune, pour
    + voter à l’échelle municipale
    + faire remonter à l’échelle de l’état
  - de l’initiative d’un nombre significatif de communes, qui ont
    marqué leur accord par référendum pour faire remonter à l’échelle
    de l’état
  - de l’initiative d’un nombre significatif d’états, qui ont marqué
    leur accord par référendum pour faire remonter à l’échelle
    fédérale
  - d’un vote d’une assemblée de représentants
  - d’une proposition automatique prévue par la constitution.


**** Forum

Tout citoyen peut faire une proposition sur le Forum des Initiatives
Populaires. Ce format permet un débat préalable et une maturation des
propositions.

Chaque mois, les /N/ propositions ayant reçu le plus de votes
favorables sur le Forum des Initiatives Populaires font l’objet d’un
référendum.

Afin d’offrir un maximum de lisibilité à chaque sujet du forum, les
vues suivantes sont disponibles :

  - aléatoire
  - chronologique (date de création)
  - sujets actifs (le plus de réponses)
  - ...


*** Assemblées

Un référendum est organisé à chaque fois qu’une assemblée de
représentants le demande.


*** Propositions automatiques

Les propositions automatiques sont :

  - modification / suppression de chaque loi votée par les assemblées
    de représentants
  - proposition d'élections anticipées pour chaque assemblée de
    représentants
  - décision d’appliquer ou non une modification de la constitution


** Quorum

Une proportion minimale de votant est requise. Par exemple :

  - au moins les deux tiers pour la constitution
  - au moins la moitié pour une loi


* Scrutins

#+TOC: headlines 1 local

On vote régulièrement pour élire les membres des assemblées représentatives


** Droit de vote

Tout citoyen âgé d’au minimum /N/ ans est en droit de voter.


** Éligibilité

Tout citoyen âgé d’au minimum /M/ ans est éligible.

Les représentants sont réélligibles et peuvent donc se
représenter à leur propre succession.

Un citoyen ne peut présenter sa candidature que pour une
seule assemblée : le cumul des mandats est interdit.

Les candidats aux élections doivent être des personnes physiques.
Aucune personne morale (société, association, parti politique, ...) ne
doit figurer dans la liste des candidats.


** Bulletins

On donne un bulletin de vote à remplir à chaque citoyen en âge
de voter.

Les candidats sont classés dans un ordre aléatoire différent pour
chaque bulletin.

L'élection s’effectue par points. Chaque électeur accorde
un nombre entier entre +5 et -5 points à chacun des candidats. Les
candidats non notés reçoivent 0 point. Un nombre positif est associé
à un vote favorable, un nombre négatif à un vote défavorable.

A la fin du scrutin, on additionne pour chaque candidat le nombre
de points qu’il a obtenu sur chaque bulletin. Le score moyen du
candidat est alors obtenu en divisant cette somme par le nombre
de bulletins.

 Si il y a N sièges à pourvoir, les élus seront les N candidats
ayant les scores moyens les plus élevés.


** Ex-aequos

En cas d’ex-aequo pour la ou les dernières places, on départage
les candidats en utilisant les critéres suivants, classés par ordre
d’importance décroissant :

  - Celui ou ceux qui on reçu le plus de votes +5
  - Celui ou ceux qui on reçu le moins de votes -5
  - Celui ou ceux qui on reçu le plus de votes +4
  - Celui ou ceux qui on reçu le moins de votes -4
  - Celui ou ceux qui on reçu le plus de votes +3
  - Celui ou ceux qui on reçu le moins de votes -3
  - Celui ou ceux qui on reçu le plus de votes +2
  - Celui ou ceux qui on reçu le moins de votes -2
  - Celui ou ceux qui on reçu le plus de votes +1
  - Celui ou ceux qui on reçu le moins de votes -1

Si cela ne suffit pas, un nouveaux vote est organisé pour les
départager.


** Élections progressives

Les élections progressives divisent les assemblées en groupes électoraux.
Considérons une assemblée comptant /N/ groupes électoraux, chaque groupe
comptant /G/ membres. L’assemblée compte donc au total :

#+BEGIN_EXAMPLE
M = G × N
#+END_EXAMPLE

membres.

On procède à une élection initiale permettant d'élire la totalite de
l’assemblée. Celle-ci est alors répartie en groupes électoraux en
fonction des scores moyens individuels. Le premier groupe comprend
donc les /G/ membres disposant des plus hauts scores, le deuxième
groupe comprend les /G/ membres suivants, et ainsi de suite jusqu’au
/N/^ième groupe qui comprend les membres disposant des scores les plus
faibles.

À la fin de chaque période électorale /T/, un des groupes électoraux
de l’assemblée est choisi et soumis à une élection.


*** Choix du groupe soumis à l'élection

Pendant les /N/ périodes suivant l'élection initiale,
le groupe soumis au vote est le groupe aux scores les plus faibles
parmi les groupes résiduels nommés lors de l'élection initiale.

Par la suite, c’est le groupe le plus anciennement élu
qui est choisi. On assiste donc à une rotation des groupes soumis
à l'élection.


*** Valeurs pratiques

En choisissant /N = 12 groupes/ et /T = 1 mois/,
des élections ont lieu tous les mois afin de remplacer un
douzième de chaque assemblée. Au bout d’un an, l’entièreté
des assemblées a été soumis à une élection.


** Élections continues

Dans un système d'élection continue, chaque électeur peut à tout moment
modifier son bulletin. Ces modifications peuvent provoquer le remplacement
d’un ou de plusieurs élus.

L'élection continue est uneforme extrême d’élection progressive.


