
#+STARTUP: showall

#+TITLE: Eclats de vers : Agora 02 : Économie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Impôts

Pour des raisons de transparence, tout objectif collectif doit se
financer sur un fond propre alimenté par l’impôt correspondant. Les
flux financiers sont alors clairement visibles.

Vient s’ajouter à ces impôts particuliers un impôt générique
alimentant un fond servant de tampon.


** Taux d’imposition

Lorsque l’impôt consiste à soustraire une fraction d’une certaine
somme S et que l’on souhaite que la contribution des fortes sommes
soit plus importante que celle des petites, on évalue le taux
d’imposition Λ par :

#+BEGIN_EXAMPLE
Λ = min { Λ_min + γ × S ; Λ_max }
#+END_EXAMPLE

où Λ_min est le taux d’imposition minimal, Λ_max le taux d’imposition
maximal et γ sa vitesse de croissance. Le calcul de l’impôt est alors
immédiat :

#+begin_example
Impôt = Λ × S = min { Λ_min + γ × S ; Λ_max }
#+end_example


** Répartition des impôts

  - Vôté par le pouvoir financier

* Sociétés

Une société est un regroupement de citoyens.


** Sociétaire

Tout citoyen membre d’une société /A/ est appelé sociétaire de /A/.


** Société personnelle

Chaque citoyen possède automatiquement sa société propre, appelée
société personnelle, qui n’admet que lui comme sociétaire.


** Création

Une société est créée par un certain nombre de citoyens appelés *fondateurs*.

Les fondateurs sont les premiers *sociétaires* de la société.


** Coopérateur

Un *coopérateur* est un salarié de la société.


** Investisseur

Une société financière peut se financer en émettant des titres donnant
différents droits aux acquéreurs. Tout acquéreur d’un ou de plusieurs
de ces titres est appelé investisseur.


*** Rente

Une rente, ou obligation perpétuelle, est un titre émis par une
société. Elle donne droit à un revenu fixe appelé *coupon*, versé à la
fin de chaque période.

Le montant du coupon est indiqué sur le titre.


*** Action

Une action est un titre émis par une société. Il donne droit à un
revenu variable appelé *dividende* versé à la fin de chaque période.


*** Obligation

Une obligation est similaire à une rente, si ce n’est qu’elle est
rendue à la société émettrice à une échéance fixée en échange de la
restitution de la somme initiale consentie par l’acheteur. Ce dernier
reçoit en plus, chaque année, un coupon fixe dont le montant est
indiqué sur l’obligation.


** Assemblées


*** Assemblée sociale

L’assemblée sociale est constituée de l’ensemble des sociétaires.
Chaque sociétaire y dispose d’une voix.

L’assemblée sociale décide à la majorité simple de l’admission des
candidats au titre de sociétaire.


*** Assemblée coopérative

L’assemblée coopérative est constituée de l’ensemble des
coopérateurs, autrement dit de l’ensemble des salariés de la
société. Chaque coopérateur y dispose d’une voix.


*** Assemblée financière

L’assemblée financière est constituée de l’ensemble des investisseurs,
autrement dit de l’ensemble des détenteurs de titres de la société.

Le poids du vote de chaque investisseur est égal au montant qu’il a
investi dans la société.

L’assemblée financière décide du niveau des dividendes. Ce niveau doit
être compris entre 10 % et 90 % du bénéfice annuel de la société si
celui-ci est positif. Dans le cas contraire, aucun dividende n’est
versé.


*** Assemblée générale

L’assemblée générale est une méta-assemblée égalitaire constituée des
assemblées sociale, coopérative et financière.


** Conseils

Un citoyen ne peut se présenter que pour un seul conseil. Le cumul des
mandats dans les conseils est donc interdit.


*** Conseil social

Le conseil social est élu chaque année par l’assemblée sociale.


*** Conseil coopérateur

Le conseil coopérateur est élu chaque année par l’assemblée
coopérative.


*** Conseil financier

Le conseil social est élu chaque année par l’assemblée
financière.


*** Conseil général

Le conseil général est élu chaque année par l’assemblée
générale.


** Statuts

Au sein de ce cadre constitutionnel (éventuellement à compléter
par un cadre légal), la société est libre de rédiger et de modifier
ses statuts particuliers comme elle l’entend.


* Régulation

La philosophie générale est d’encadrer et de réguler les instabilités
potentielles de l'économie et des marchés financiers, tout en laissant à
ceux-ci une large marge de manoeuvre.


** La concurrence

Afin d'éviter les positions dominantes, la règle par défaut est la
suivante : le poids consolidé d’une société et de ses filiales sur
l’offre ou la demande d’un marché ne peut pas excéder 5 %. Par
exemple, si une société a une part de marché de 3 %, et qu’elle compte
prendre une participation P dans une société qui possède 4 % de part
de marché, on a la contrainte :

#+BEGIN_EXAMPLE
3 % + P × 4 % ≤ 5 %
#+END_EXAMPLE

Ce qui nous mène à un maximum pour la participation :

#+BEGIN_EXAMPLE
P ≤ (5 % - 3 %) / 4 %
P ≤ 2 % / 4 %
P ≤ 1 / 2 = 50 %
#+END_EXAMPLE


** Les concentrations naturelles

Dans les secteurs où il est établi qu’une concentration permet de
créer des outils de production plus performants, et donc de produire à
moindre coût, toute société peut, pourvu qu’elle le signale
officiellement, s’allier avec un concurrent ou le racheter. Si cette
opération lui fait dépasser le seuil de 5 % de part de marché, elle
sera alors tenue d’ajuster ses tarifs afin que son profit net
s’annulle. En d’autres termes, les recettes devront s’adapter afin de
compenser le plus exactement possible :

  - les salaires

  - la rémunération des actionnaires (au taux du marché)

  - les investissements

  - l’usure du matériel (amortissements)

  - ...

Elle devra également offrir les tarifs les plus bas et les
salaires les plus hauts possibles, ainsi qu’une qualité élevée.


** Les monopoles officiels

Au compte au minimum comme monopoles officiels :

  - les ressources naturelles et matières premières

  - les transports

  - l'énergie (électricité, ...)

  - les réseaux de communication

  - ...

Leur but est de créér un cadre efficace ou l'économie peut s'épanouir
dans l’intérêt général.

La régulation des tarifs s’applique également aux monopoles officiels.
De plus, l’actionnariat d’un monopole officiel se répartit comme suit :

  - 15 % des titres appartiennent à l'état fédéral

  - 15 % des titres sont répartis équitablement entre les états membres

  - 30 % des titres sont répartis équitablement entre les citoyens

  - 40 % des titres s'échangent librement sur le marché



** Richesse

Soit V_min la valeur des biens du citoyen le plus démuni et V_max la
valeur des biens du citoyen le plus aisé. On exige que :

  - V_min reste supérieur au minimum Δ d’une vie digne

  - V_max / V_min reste inférieur à un rapport Γ

Si V_min passe en-dessous de Δ, ou si le rapport V_max / V_min dépasse
Γ, les citoyens les plus aisés sont mis à contribution pour renflouer
les plus démunis, jusqu'à ce que les deux critères ci-dessus soient de
nouveau remplis.

On procède comme suit : le citoyen le plus aisé est seul mis à
contribution jusqu'à ce que la valeur de ses biens devienne égale à
celle du deuxième citoyen le plus riche. Ils contribuent alors
équitablement à deux jusqu'à ce qu’ils atteignent le troisième, et
ainsi de suite.

Le rapport Γ est à fixer dans une fourchette de 10 à 100.


*** Société enveloppe

Dans le cas où, faute de liquidités, le paiement exigerait la vente
d’un bien que le contributeur ne souhaite pas vendre, on procède à la
titrisation de ce bien : une société enveloppe est créée, et le
contributeur est donc autorisé à verser la somme en titres plutôt
qu’en liquide :

  - le contributeur place le bien concerné dans la société enveloppe
    dont il détient alors 100 % des parts

  - le contributeur verse à l'état la contrevaleur en titres à revenus
    fixes ou variables de la société

  - l'état reverse en liquide le montant correspondant aux plus
    démunis


* Monnaie

Le *Livre des comptes* :

  - émet la monnaie

  - tient les comptes

  - garantit la valeur de la monnaie


** Émission

Le Livre des comptes est chargée d'émettre la monnaie fiduciaire
et scripturale.


** Comptes

Le Livre des Comptes tient les comptes de chaque société. Il tient
également les comptes de chaque citoyen via les sociétés personnelles.
Il est le seul autorisé à recevoir des dépôts des citoyens et des
sociétés. Ces derniers peuvent retirer leur argent quand ils le
souhaitent et le service est gratuit.

Les transactions entre citoyens et entre sociétés se réalisent :

  - soit par monnaie physique

  - soit par virement entre leurs comptes


** Garantie

Le Livre des comptes garantit la valeur de la monnaie en permettant de
l'échanger à un prix Π constant contre un panier de produits
tangibles, appelé panier de référence et comprenant :

  - des matières premières

  - de l’alimentation

  - de l’immobilier

  - des terrains cultivables

  - des outils de production

  - ...

On a donc l'équivalence :

#+begin_example
1 panier = Π unités monétaires
#+end_example

Chacun peut donc acheter de tels paniers en échange d’un paiement en
liquide ou d’une diminution du montant sur son compte. Naturellement,
de tels paniers peuvent également être vendus au même prix Π contre
du liquide ou une augmentation du montant sur son compte.

Afin de satisfaire la demande en paniers de référence, le Livre des
comptes dispose d’un droit de réquisition sur les biens et la
production de chaque société. En échange, les comptes des sociétés
sont crédités d’un montant équivalent à la contrevaleur de leur
contribution. Afin de répartir la charge, les réquisitions doivent
impérativement être réparties entre les sociétés, et ce
proportionnellement à la valeur des biens et de la production de
chacune d’entre elles.

Le Livre de compte sert dans ce cas d’intermédiaire entre
acheteurs et producteurs, tout en régulant les prix.


* Marchés


** Centralisation

Les marchés portant sur les produits importants :

  - titres émis par des sociétés

  - matières premières

  - alimentation

  - ...

sont centralisés au niveau fédéral afin de garantir une transparence
optimale (prix unique à un instant donné, ...) aux citoyens.


** Cotation

Les marchés sont des lieux de rencontre entre tous les acheteurs et
vendeurs potentiels d’un même produit. Les meilleures offres d’achats
et de vente sont rendues disponible à tous dans le carnet d’ordre,
afin de favoriser les échanges aux meilleurs prix (appelés cours)
possibles. On appelle ce procédé une *cotation en continu*

En plus de cette cotation en continu, on organise deux *fixing* par
jour. Les ordres sont alors cachés et accumulés dans une boîte noire.
Au bout de 30 minutes, on les découvre et on calcule l’intersection
des courbes d’offre et de demande agrégées, ce qui donne le cours
optimal et la quantité échangée.


** Marchés au comptant

Sur les marchés au comptant, le vendeur remet immédiatement le produit
à l’acheteur, et reçoit son prix en échange.


** Marchés à terme

Sur les marchés à terme, des contrats sont conclus entre acheteurs et
vendeurs, qui s’engagent respectivement à payer et à livrer le produit
dans le futur, à une date appelée échéance.

Pour un produit donné, les contrats à terme de même échéance sont
standardisés, donc échangeables. Chaque échéance fait donc l’objet
d’une cotation séparée. Ces marchés sont symétriques car il permettent
d’acheter à terme avant ou après avoir vendu à terme.


*** Chambre de compensation

La chambre de compensation sert d’intermédiaire entre les acheteurs et
les vendeurs.

Si A achète à terme à un vendeur V, la chambre de compensation va en
fait acheter au vendeur V pour revendre la même quantité au même prix
à l’acheteur A.


*** Appels de marge

Afin d'éviter les défauts de paiement, chaque intervenant d’un marché
à terme doit mettre à disposition, sur un compte prévu à cet effet,
une somme appelée marge représentant au minimum 20 % de la valeur des
contrats qu’il a conclu.

A chaque cotation, si le cours monte, la chambre de compensation
s’occupe de créditer les comptes des acheteurs et de débiter les
comptes des vendeurs de la différence de cours multiplié par le nombre
de contrats qu’ils ont conclus.

Par contre, si le cours chute, les comptes des acheteurs sont débités
et les comptes des vendeurs crédités de la différence de cours
multiplié par le nombre de contrats qu’ils ont conclus.

A tout moment, un acheteur peut sortir du jeu en revendant un nombre
de contrat identique au nombre de contrat acheté.

A tout moment, un vendeur peut sortir du jeu en rachetant un nombre de
contrat identique au nombre de contrat vendu.

Un intervenant qui n’a plus assez de marge sur son compte est obligé,
soit de renflouer celui-ci, soit de sortir du marché en revendant ou
en rachetant ses contrats.


** Les prêts - emprunts

Un contrat de prêt - emprunt est un contrat par lequel le prêteur cède
provisoirement un produit à l’emprunteur. En contrepartie, ce dernier
s’engage à restituer à l'échéance fixée le dit produit plus une
compensation financière.

Le montant de cette compensation financière est déterminée par la
valeur du produit prêté et une variable appelée taux d’intérêt :

#+BEGIN_EXAMPLE
Compensation = Taux d’intérêt × Cours du produit au moment de la conclusion du contrat
#+END_EXAMPLE

Pour un produit donné, les contrats de prêt - emprunt de même échéance
sont standardisés, donc échangeables. Chaque échéance fait l’objet
d’une cotation séparée où le taux d’intérêt est la variable cotée du
contrat, les meilleurs ordres prêteurs étant ceux demandant le taux
d’intérêt le plus faible, et les meilleurs ordres emprunteurs étant
ceux offrant le taux d’intérêt le plus élevé.

Le produit prêté - emprunté peut-être :

  - de l’argent

  - un produit financier

  - une matière première

  - ...


* Travail

Le temps de travail doit être partagé équitablement afin de laisser le
plus de loisir possible à la population, qui a a lors le temps
d’accomplir des tâches plus enrichissantes.


* Citoyen actionnaire

Les sociétés de citoyens suivantes sont créées

  - 1 société par municipalité

  - 1 société par état

  - 1 société pour la fédération


Chaque citoyen dispose d’une action dans les sociétés de citoyens
suivantes

  - Société de sa municipalité

  - Société de son état

  - Société de la fédération

Ces actions sont personnelles et ne peuvent être vendues ou achetées.
Chaque action lui donne droit

  - au droit de vote

  - au dividende


* Principes


** Monopoles

La prise en compte de monopoles officiels peut paraître en
contradiction avec la philosophie de concurrence. Je dis qu’ils sont
complémentaires, car la concurrence n’est pas synonyme de chaos. Pour
ne citer qu’un exemple, comment organiser proprement et
rationnellement le fonctionnement de l'économie sans centralisation
des ordres d’achat et de vente ? Or, toute centralisation implique la
création d’un monopole. Il vaut mieux un tel monopole, régulé et
encadré rigoureusement par des lois, que la création de plusieurs
marchés concurrents impliquant entre autres :

  - Des informations éparpillées, d’où une diminution nette de la
    clarté, nuisible aux intervenants

  - Une diminution de la liquidité au sein de chaque marché


** Titres

Attention de ne pas confondre :

  - les dépôts, que l’on peut voir comme des prêts à échéance
    indéterminée laissée au gré du prêteur

  - les rentes, ou obligations perpétuelles qui ne comportent pas
    d'échéance.

  - les prêts classiques qui sont à échéance fixe


* Brevets

Licence d’utilisation rémunérée par une partie des recettes que les
produits qui en découlent génèrent, et cela pendant une durée bien
déterminée
