
#+STARTUP: showall

#+TITLE: Eclats de vers : Agora 01 : Constitution
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Introduction

Cet ouvrage est inspiré par des idées personnelles, ainsi que par les
sources suivantes :

  - [[https://jortay.net/][François Jortay]] : page principale qui renvoie vers ses autres sites
    + [[https://konfedera.org/][konfedera]] : confédération d’états souverains
    + [[https://democratiedirecte.net/][democratie directe]] : référendum, économie mixte
    + [[https://allocation-universelle.net/][allocation universelle]]

* Principes

#+TOC: headlines 1 local

** Souveraineté

Toute constitution, qu’elle soit locale, nationale, fédérale ou
confédérale, transfère à la collectivité une partie de la souveraineté
des constituants afin d’en garantir le fonctionnement harmonieux.

Une constitution saine garantit un maximum de liberté à l’individu et
aux constituants. Le transfert de souveraineté des constituants vers
l’entité constituée doit donc être minimal et pleinement justifié.

** Équilibre

Il est important de veiller à l’équilibre entre :

  - la liberté individuelle (république)
  - la volonté du peuple (démocratie directe)
    + exercée par référendum sur initiative de la population
  - la démocratie représentative
    + exercée via des représentants élus par les citoyens qu’ils représentent
  - la conscience individuelle
    + la liberté ne peut réellement exister qu’en conscience
  - la conscience collective
  - les étages de la collectivité
    + l’individu
    + la commune
      * la fédération intercommunale
    + la cité
      * fédération de communes
    + l’état
      * fédération de cités
    + l’autonomie de l’entité fédérée
    + les compétences fédérales
    + l’autonomie de l’entité confédérée
    + les compétences confédérales

** Compétence

Pour savoir qui est compétent :

  - individu
  - commune
  - cité
      * fédération de communes
  - état
      * fédération de cités
  - fédération
  - confédération

répondre à la question : qui est (principalement) concerné ?

** Liberté individuelle

  - respect de la liberté individuelle, pour éviter que la démocratie
    ne devienne la dictature de la majorité
    + la liberté individuelle doit être garantie par la constitution
    + le citoyen doit disposer de ressources qui garantissent son indépendance
    + le transfert de souveraineté à l’état (ou autre) doit être
      minimal
  - les autres étages de collectivité doivent intervenir
    + au minimum
    + seulement là où c’est nécessaire
    + de façon cohérente

** Importance de la communauté locale

  - commune à taille humaine
  - entraide
  - partage
  - échange
  - économie
  - services
  - contre-pouvoir aux plus grands étages de la collectivité

** Information libre

Importance de la libre circulation de l’information pour les :

  - débats
  - décisions

Pour cela, il faut des réseaux sociaux et des média :

  - en partie publics
  - en partie sous forme de concurrence privée, sans position
    dominante

** Démocratie directe

Démocratie directe, via les référendums sur initiative de la
population :

  - doit être en équilibre avec la liberté individuelle
  - prend le pas sur
    * les décisions des représentants
    * les traités internationaux
  - à tous les nivaux
    * individu
    * commune
    * cité
    * état
    * fédération
    * confédération
  - concerne toutes les catégories de pouvoirs (liste non exhaustive)
    * législatif
    * exécutif
    * judiciaire
      - vérification de la neutralité des juges
    * économique
      - financier
    * information
      * réseaux sociaux
      * média, presse
    * social
    * connaissance
    * territorial

** Représentation

  - par élection au suffrage universel
    + chaque citoyen dispose d’un unique bulletin de vote
    + méthode : par points (positifs, nuls ou négatifs)
  - concerne toutes les catégories de pouvoirs

** Éviter les concentrations excessives de pouvoir

  - la concentration excessive de pouvoir mène à un déséquilibre et
    une instabilité
  - garantir l’indépendance des étages de la collectivité et des
    catégories de pouvoirs
  - éviter les cumuls de mandats
  - instaurer des mandats partiellement impératifs dans certains cas
    afin de fixer un cadre d’action aux représentants ?

Concerne toustes les catégories de pouvoir (liste non exhaustive) :

  - législatif
  - exécutif
  - judiciaire
  - économique
    + financier
  - information
    + réseaux sociaux
    + média, presse
  - social
  - connaissance
  - territorial

** Modularité

  - gouvernance modulaire, à la fois
    + par démocratie directe, qui prime
    + par assemblée de représentants
  - exemples de modules
    + coopérative publique
    + caisse reliée à un objectif et un impôt
      * caisse de retraite
      * caisse de santé
      * etc
    + thème
      * législatif
      * exécutif
      * financier
      * etc

** Transparence des impôts

  - un impôt = un pot commun = un objectif clairement défini
    + pas question de rediriger l’argent ailleurs
    + prévoir une structure juridique, un fond par impôt
  - impôt générique : pour huiler le mécanisme, mais il doit être
    bien cadré et contrôlé

** Services publics

  - réseau dense de services publics pour que chaque citoyen puisse en
    profiter
  - chaque service public peut être assuré par une ou plusieurs
    coopératives publiques, éventuellement complétées par des sociétés
    privées agréées

** Économie

  - remplacer l’idée de croissance par celle du bien-être et de la prospérité
  - profiter des avantages des marchés sans en subir les défauts
    + parmi ces défauts, notons le développement de compagnies
      gigantesques, et les concentrations excessive de moyens
      financiers qui en résultent
  - réguler où il le faut pour éviter les concentrations excessives et les instabilités
  - quand une compagnie est trop grande, ou domine un marché,
    plusieurs solutions sont possibles
    * diviser la compagnie en plusieurs compagnies de taille réduite
      afin de relancer la concurrence
      - solution à privilégier
    * nationaliser en coopérative publique régulée si cela se justifie
      - régulation des prix, salaires, de la qualité, quantité, etc
      - secteurs : eau, énergie, transports, etc
  - sociétés commerciales à tendance coopérative
    + assemblée sociale des coopérateurs
    + éventuellement assemblée actionnariale
  - éviter le gaspillage
    * généraliser
      - la récupération des biens
      - le recyclage de biens
      - la récupération d’énergie
      - le télé-travail
      - les transports en commun
    * favoriser
      - la production, le commerce et la consommation locale
    * ne pas pousser à consommer excessivement
  - international
    * protectionisme vis à vis des pays qui n’ont pas les mêmes
      avantages sociaux
    * protectionisme vis à vis des pays qui ne respectent pas les
      principes démocratiques et républicains
    * développer des conventions internationales pour que ces
      avantages soient adoptés le plus largement possible

* Assemblées

#+TOC: headlines 1 local

** Introduction

Une assemblée peut être :

  - populaire : chaque citoyen y dispose d’un droit de vote
    + ce sont donc les assemblées populaiers qui votent les
      référendums
  - représentative : composée de représentants élus
    + on dit aussi assemblée de représentants

** Préparation

L’écriture d’un projet susceptible de remporter une large adhésion
nécessite un processus de maturation où tous les points de vue sont
écoutés, analysés et compris en profondeur. On aboutit alors
normalement sur un texte qui a de bonnes chances de rassembler un
maximum de gens, idéalement au moins 70% des votants. Un projet qui ne
passe que grâce à une majorité courte est souvent le signe qu’il n’a
pas été suffisamment préparé, et qu’il pourrait se voir améliorer.

Ce processus est valable autant pour les assemblées populaires des
référendums, que pour les assemblées de représentants.

* Référendum

#+TOC: headlines 1 local

** Introduction

Les citoyens sont directement impliqués dans les décisions au moyen de
*référendums*, aussi appelés *votations*.

Lors d’un référendum, tous les citoyens d’une assemblée populaire
votent afin de prendre une décision.

** Prépondérance

Les décisions prises par référendum sont prépondérantes par rapport
aux décisions prises par les assemblées de réprésentants.

** Contrepoids

Le pouvoir des référendums est énorme, il est important de le
contrebalancer par des garanties inscrites dans la constitution, afin
d’éviter qu’une décision prise par référendum ne vienne empiéter sur
les libertés individuelles.

** Initiative

Les citoyens ont l’initiative des référendums dès qu’un nombre
significatif d’entre-eux le demande.

Les propositions donnant lieu à une consultation populaire peuvent
résulter :

  - de l’initiative d’un nombre significatif de citoyens
    + par exemple, 0.1% de la population
  - d’un vote d’une assemblée de représentants
  - de l’initiative d’un étage de collectivité
    + via
      * un référendum favorable à cet étage
      * une décision de l’assemblée de représentants de cet étage
    + pour faire remonter à l’étage supérieur
    + exemples
      * référendum à l’échelle d’une cité, pour faire remonter à
        l’échelle de l’état
    + effet de cascade possible : chaque étage fait remonter à l’étage
      immédiatement supérieur
      * exemple
	+ commune -> cité -> état -> fédération -> confédération
  - d’une proposition automatique prévue par la constitution

*** Espace de proposition

Tout citoyen peut faire une proposition sur la *Coordination des
Initiatives Populaires*..

Après une période de débats destiné à faire murir la proposition,
celle-ci est soumise à des votes favorables et défavorables. Chaque
mois, les /N/ propositions ayant le meilleur score font l’objet d’un
référendum.

Afin d’offrir un maximum de lisibilité à chaque sujet traité, les vues
suivantes sont disponibles :

  - aléatoire
  - chronologique (date de création)
  - sujets actifs (le plus de réponses)
  - ...

*** Propositions automatiques

Les propositions automatiques sont :

  - modification / suppression de chaque loi votée par les assemblées
    de représentants
  - proposition d'élections anticipées pour chaque assemblée de
    représentants
  - décision d’appliquer ou non une modification de la constitution

** Exclusivité

Les décisions collectives dont il est difficile, voire impossible,
d’annuler les effets ne peuvent être prises que par référendum, et non
pas une chambre de représentants.

La seule exception pourrait se justifier lorsqu’une urgence vitale
nécessite de prendre une décision rapide et provisoire, à confirmer
par la suite par référendum.

** Sujets

Toute décision qui concerne la collectivité peut être sujet à un
référendum :

  - modification de la constitution
    + seulement par référendum
    + les assemblées de représentants n’y ont pas accès
  - article de loi
    + création
    + modification
    + abrogation
  - traités internationaux
  - représentants & fonctionnaires
    + sanction
    + révocation
    + jugement
    + salaire
    + imposition
  - assemblée
    + annulation d’une décision d’une assemblée
    + dissolution d’une assemblée, et convocation d’élections
      anticipées
  - initiative, questionnement ou véto concernant un des pouvoirs de
    l’état
    + législatif
    + exécutif
    + judiciaire
    + économique
      * société commerciale
      * coopérative publique
	- création
	- supervision du cénacle interne de représentants
	- gestion
	- dissolution
      * monétaire
      * bancaire
      * financier
      * marché
      * fiscal
    + information
      - média, presse
      - informatique
    + social
      * réseaux sociaux
    + connaisance
      * science
    + territorial
    + etc

*** Critères

  - le sujet d’un référendum doit être le plus simple possible
  - s’il s’agit d’un sujet complexe
    + il vaut mieux le morceler en sections simples
    + chaque section simple est soumise à un vote séparé

** Universalité verticale

Les règles pour les consultations populaires sont valables au niveau :

  - d’une commune
  - d’une cité
  - d’un état
  - d’une fédération
  - de la confédération

** Majorité

En fonction du sujet, une majorité plus ou moins grande est requise :

  - majorité des deux-tiers pour la constitution
  - majorité simple (la moitié plus une voix) pour une loi

** Quorum

Si il y a trop d’absentions, le résultat du référendum est invalidé.

On demande donc un quorum minimum, c’est-à-dire une proportion
minimale de votants parmi la population, pour valider le résultat.

Exemples de quorums :

  - au moins les deux-tiers pour la constitution
  - au moins la moitié pour une loi

* Scrutin

#+TOC: headlines 1 local

On vote régulièrement pour élire les membres des assemblées
représentatives

** Droit de vote

Tout citoyen âgé d’au minimum /N/ ans est en droit de voter.

** Éligibilité

Tout citoyen âgé d’au minimum /M/ ans est éligible.

Les représentants sont réélligibles et peuvent donc se
représenter à leur propre succession.

Un citoyen ne peut présenter sa candidature que pour une
seule assemblée : le cumul des mandats est interdit.

Les candidats aux élections doivent être des personnes physiques.
Aucune personne morale (société, association, parti politique, ...) ne
doit figurer dans la liste des candidats.

** Bulletins

On donne un bulletin de vote à remplir à chaque citoyen en âge
de voter.

Les candidats sont classés dans un ordre aléatoire différent pour
chaque bulletin.

L'élection s’effectue par points. Chaque électeur accorde
un nombre entier entre +5 et -5 points à chacun des candidats. Les
candidats non notés reçoivent 0 point. Un nombre positif est associé
à un vote favorable, un nombre négatif à un vote défavorable.

A la fin du scrutin, on additionne pour chaque candidat le nombre
de points qu’il a obtenu sur chaque bulletin. Le score moyen du
candidat est alors obtenu en divisant cette somme par le nombre
de bulletins.

Si il y a /N/ sièges à pourvoir, les élus seront les N candidats ayant
les scores moyens les plus élevés.

** Ex-aequos

En cas d’ex-aequo pour la ou les dernières places, on départage
les candidats en utilisant les critéres suivants, classés par ordre
d’importance décroissant :

  - celui ou ceux qui on reçu le plus de votes +5
  - celui ou ceux qui on reçu le moins de votes -5
  - celui ou ceux qui on reçu le plus de votes +4
  - celui ou ceux qui on reçu le moins de votes -4
  - celui ou ceux qui on reçu le plus de votes +3
  - celui ou ceux qui on reçu le moins de votes -3
  - celui ou ceux qui on reçu le plus de votes +2
  - celui ou ceux qui on reçu le moins de votes -2
  - celui ou ceux qui on reçu le plus de votes +1
  - celui ou ceux qui on reçu le moins de votes -1

Si cela ne suffit pas, un nouveaux vote est organisé pour les
départager.

* Étages de la collectivité

#+TOC: headlines 1 local

** Citoyen

Un *citoyen* est un individu membre d’une communauté.

Cette communauté correspond généralement à un des autres étgaes de
collectivité.

** Commune

Une *commune* est une communauté locale.

On parle aussi de municipalité.

Typiquement, un village ou une petite ville.

** Cité

Une *cité* est un regroupement de communes.

Typiquement, une grande ville composée de plusieurs communautés.

** État

Un *état* est un ensemble de citoyens associés à un territoire,
lui-même délimité par une frontière.

Un état est généralement composé de :

  - cités
  - communes
  - régions
    + urbaines
    + campagnes
    + forêts
    + montagnes
    + rivières
    + etc

*** Modification de la constitution

Toute modification de la constitution d’un état doit être approuvée
par une majorité aux deux-tiers :

  - deux-tiers de l’ensemble de la population de l’état, par
    référendum
  - deux-tiers des cités et des communes simples, non regroupées en
    cités
    + le résultat du référendum doit être favorable à la majorité
      simple dans au moins deux-tiers des cités et communes

** Commune-état

Une *commune-état* est une commune formant un état à part entière.

** Cité-état

Une *cité-état* est une cité formant un état à part entière.

** Fédération

#+TOC: headlines 1 local

*** Définition

Une *fédération* est une union d’entités fédérées (états ou
autres) *et* un ensemble de citoyens formé par l’union des citoyens des
entités fédérées. Les entités fédérées décident de s’occuper
ensemble de compétences définies par un traité fondateur.

Afin de maintenir l’équilibre entre les étages de la collectivité,
l’ensemble des citoyens et l’ensemble des entités fédérées
doivent être représentés dans le processus de décision.

*** Composition

Une entité membre d’une fédération est appelée *entité fédérée*.

Chaque entité fédérée peut être :

  - un état
  - une cité-état
  - une commune-état
  - une sous-fédération
  - une sous-confédération

*** Équilibre & souveraineté

Dans une fédération, une étage de la collectivité peut être :

  - un individu
  - une commune
  - une cité
  - un état
  - une commune-état
  - une cité-état
  - une sous-fédération
  - une sous-confédération

Comme d’habitude, les transferts de souveraineté suivants sont
minimaux :

  - individu --> commune
  - individu --> cité
  - individu --> entité fédérée (état ou autre)
  - individu --> fédération

Un des principes fondamentaux d’une fédération est de veiller à
l’équilibre entre les différents niveaux de pouvoir. Par conséquent,
on veille à ce que les transferts de souveraineté suivants soient
équilibrés :

  - commune --> cité
  - commune --> entité fédérée
  - commune --> fédération
  - cité --> entité fédérée (état ou autre)
  - cité --> fédération
  - entité fédérée --> fédération

On veille malgré tout à ce que ces transferts restent proches du
minimum.

Chaque transfert de souveraineté doit être cité explicitement dans la
constitution.

*** Cadre

Cadre minimal pour la constitution des entités fédérées :

  - droits humains fondamentaux
  - liberté individuelle républicaine
  - démocratie directe, via les référendums
  - bien-être de la population

*** Double référendum

Pour être approuvée, une décision par référendum nécessite la double
approbation :

  - d’une majorité de la population fédérale
  - d’une majorité d’entités fédérées où le référendum interne est
    favorable
    + si l’entité fédérée est un état, il faut alors l’accord de la
      majorité de sa population
    + si l’entité fédérée est une sous-fédération, il faut alors le
      double accord
      * d’une majorité de la population sous-fédérale
      * d’une majorité d’entités de la sous-fédération où le référendum
        interne est favorable
    + si l’entité fédérée est une sous-confédération, il faut alors le
      double accord
      * d’une majorité de la population sous-confédérale
      * d’une majorité d’entités de la sous-confédération où le référendum
        interne est favorable

*** Forum fédéral

Le processus de décision est double, car il reflète la double
structure de la fédération.

Il existe deux assemblées principales de représentants :

  - *sénat* fédéral
    + assemblée où chaque entité fédérée dispose d’un même nombre
      de représentants
  - *parlement* fédéral
    + assemblée où chaque entité fédérée dispose d’un nombre de
      représentants approximativement proportionnel à sa population
      * il est difficile d’avoir une représentation exactement
        proportionnelle sans augmenter considérablement le nombre de
        représentants

L’ensemble de ces deux assemblées forme le *forum* fédéral.

Toute décision qui relève de la compétence du forum fédéral doit être
approuvée par le sénat et le parlement pour être validée.

En cas de désaccord persistent entre ces deux assemblées, le sujet du
vote est soumis à un double référendum.

Pour affiner, on peut imaginer de :

  - multiplier les forums fédéraux, chacun ayant son domaine de
    compétence
    + législatif, exécutif, juridique, économie, information, etc
  - constituer un forum central, chargé de coordonner les autres
    + de part sa position privilégiée, ce forum central devra être
      sous une surveillance particulièrement attentive des assemblées
      populaires

*** Majorité des deux-tiers

Certaines décisions nécessitent une majorité d’au moins deux-tiers,
par double référendum :

  - au moins deux-tiers de l’ensemble de la population fédérale
  - au moins deux-tiers des entités fédérées où le référendum interne est
    favorable

Les décisions suivantes nécessitent une majorité des deux-tiers :

  - modification de la constitution fédérale
  - adhésion d’une nouvelle entité
    + nécessite aussi l’accord de la nouvelle entité

*** Citoyenneté

Tout citoyen d’une entité fédérée est également citoyen de la fédération.
Inversément, tout citoyen de la fédération est membre d’une et d’une
seul de ses entités.

Tout citoyen de la fédération est libre de voyager dans tous les entités
membres.

Tout citoyen est libre de choisir son état et d’en changer à sa
guise : il est automatiquement citoyen de l’état fédéré dans lequel se
situe sa résidence principale.

*** Relations extérieures

  - traités internationaux, sur double approbation du forum
    + entre la fédération et l’extérieur l’extérieur
  - commerce extérieur unifié

** Confédération

#+TOC: headlines 1 local

*** Définition

Une *confédération* est une union d’entités confédérées (états
ou autres) *et* un ensemble de citoyens formé par l’union des citoyens
des entités confédérées. Les entités confédérées décident de
s’occuper ensemble de compétences définies par un traité fondateur.

Afin de maintenir l’équilibre entre les étages de la collectivité,
l’ensemble des citoyens et l’ensemble des entités confédérées
doivent être représentés dans le processus de décision.

*** Composition

Une entité membre d’une confédération est appelée *entité confédérée*.

Chaque entité fédérée peut être :

  - un état
  - une cité-état
  - une commune-état
  - une sous-fédération
  - une sous-confédération

*** Souveraineté

Dans une confédération, une étage de la collectivité peut être :

  - un individu
  - une commune
  - une cité
  - un état
  - une commune-état
  - une cité-état
  - une sous-fédération
  - une sous-confédération

Un des principes fondamentaux d’une confédération est le minimalisme
harmonieux. Par conséquent, on veille à ce que les transferts de
souveraineté suivants soient minimaux :

  - individu --> commune
  - individu --> cité
  - individu --> entité fédérée (état ou autre)
  - individu --> fédération
  - commune --> cité
  - commune --> entité fédérée
  - commune --> fédération
  - cité --> entité fédérée (état ou autre)
  - cité --> fédération
  - entité fédérée --> fédération

Chaque transfert de souveraineté doit être cité explicitement dans la
constitution.

*** Cadre

Cadre minimal pour la constitution des entités confédérées :

  - droits humains fondamentaux
  - liberté individuelle républicaine
  - démocratie directe, via les référendums
  - bien-être de la population

*** Double référendum

Pour être approuvée, une décision par référendum nécessite
l’approbation :

  - d’une majorité de la population confédérale
  - d’une majorité d’entités confédérées où le référendum interne est
    favorable
    + si l’entité confédérée est un état, il faut alors l’accord de la
      majorité de sa population
    + si l’entité confédérée est une sous-fédération, il faut alors le
      double accord
      * d’une majorité de la population sous-fédérale
      * d’une majorité d’entités de la sous-fédération où le référendum
        interne est favorable
    + si l’entité confédérée est une sous-confédération, il faut alors le
      double accord
      * d’une majorité de la population sous-confédérale
      * d’une majorité d’entités de la sous-confédération où le référendum
        interne est favorable

*** Congrès confédéral

Le processus de décision est double, car il reflète la double
structure de la confédération.

Il existe deux assemblées principales de représentants :

  - *collège* confédéral
    + assemblée où chaque entité confédérée dispose d’un même nombre
      de représentants
  - *convention* confédérale
    + assemblée où chaque entité confédérée dispose d’un nombre de
      représentants approximativement proportionnel à sa population
      * il est difficile d’avoir une représentation exactement
        proportionnelle sans augmenter considérablement le nombre de
        représentants

L’ensemble de ces deux assemblées forme le *congrès* confédéral.

Toute décision qui relève de la compétence du congrès confédéral
doit être approuvée par le collège et la convention pour être
validée.

En cas de désaccord persistent entre ces deux assemblées, le sujet du
vote est soumis à un double référendum confédéral.

Pour affiner, on peut imaginer de :

  - multiplier les congrès confédéraux, chacun ayant son domaine de
    compétence
    + législatif, exécutif, juridique, économie, information, etc
  - constituer un congrès central, chargé de coordonner les autres
    + de part sa position privilégiée, ce congrès central devra être
      sous une surveillance particulièrement attentive des assemblées
      populaires

*** Majorité des deux-tiers

Certaines décisions nécessitent une majorité des deux-tiers, par
double référendum :

  - au moins deux-tiers de l’ensemble de la population confédérale
  - au moins deux-tiers des entités confédérées où le référendum interne est
    favorable

Les décisions suivantes nécessitent une majorité des deux-tiers :

  - modification de la constitution confédérale
  - adhésion d’une nouvelle entité
    + nécessite aussi l’accord de la nouvelle entité

*** Citoyenneté

Tout citoyen d’une entité confédérée est également citoyen de la
confédération. Inversément, tout citoyen de la confédération est
membre d’une et d’une seule des entités confédérées.

Tout citoyen de la confédération est libre de voyager dans les
entités confédérées.

Un citoyen qui désire changer l’entité confédérée à laquelle il est
affilié doit demander l’autorisation :

  - à l’entité confédérée à laquelle il est actuellement affilié
  - à l’entité confédérée à laquelle il souhaite s’affilier

*** Relations extérieures

  - traités internationaux, sur double approbation du congrès
    + entre la confédération et l’extérieur
    + entre une entité confédérée et l’extérieur
  - commerce extérieur
    + tarifs douaniers harmonisés

** Confédération et fédération

#+TOC: headlines 1 local

*** Dualité

Un ensemble d’entités peut très bien décider de constituer à la
fois une fédération et une confédération.

On pourrait nommer ce type de structure une confédération duale, à défaut
de trouver un meilleur terme.

Dans ce cas :

- la fédération s’occupe des projets et relations
  de l’ensemble des entités avec l’extérieur
- la confédération s’occupe des projets et relations
  interieures entre les entités

Les citoyens cumulent les fonctions à travers les référendums
fédéraux, confédéraux et de leurs entités respectives.

Les chambres doubles du forum et du congrès coexistent, chacune
s’occupant des fonctions qui leurs sont confiées par la constitution.

*** Comparaison

|               | fédération                           | confédération                                 |
|---------------+--------------------------------------+-----------------------------------------------|
| concept       | La fédération forme une enveloppe    | La confédération est comme une table ronde    |
|               | autour des entités fédérées          | placée au centre, entourée par les entités    |
|               |                                      | confédérées, en tant que plate-forme :        |
|               | Elle est :                           | - de coopération                              |
|               | - uniforme vue de l’extérieur        | - d’entraide                                  |
|               | - diversifiée à l’intérieur          | - d’alliance                                  |
|               |                                      | Elle sert aussi d’intermédiaire entre         |
|               |                                      | les entités confédérées :                     |
|               |                                      | - échanges                                    |
|               |                                      | - arbitrage                                   |
|               |                                      | - garantie                                    |
|---------------+--------------------------------------+-----------------------------------------------|
| autonomie     | - intégration plus poussée des       | Large autonomie des entités confédérées       |
|               | entités fédérées                     |                                               |
|               | - équilibre entre l’autonomie        |                                               |
|               | des entités fédérées et              |                                               |
|               | les responsabilités fédérales        |                                               |
|---------------+--------------------------------------+-----------------------------------------------|
| institution   | Institutions fédérales en équilibre  | Institutions confédérales minimales           |
|               | avec celles des entités fédérées     |                                               |
|               |                                      | Le rôle des assemblées confédérales est :     |
|               |                                      | - de coordonner les actions                   |
|               |                                      | - d’organiser des services communs            |
|               |                                      | - d’offrir un cadre aux échanges              |
|---------------+--------------------------------------+-----------------------------------------------|
| citoyenneté   | Le citoyen est libre de voyager      | Le citoyen est libre de voyager               |
|               | où il le souhaite dans la fédération | où il le souhaite dans la confédération,      |
|               | et de choisir l’état auquel il est   | mais il lui est plus difficile de changer     |
|               | affilié                              | l’entité confédérée à laquelle il est affilié |
|---------------+--------------------------------------+-----------------------------------------------|
| monnaie       | monnaie fédérale                     | - monnaie confédérale pour les échanges       |
|               |                                      | entre entités confédérées et le commerce      |
|               |                                      | inter-entités confédérées                     |
|               |                                      | - à laquelle s’ajoutent éventuellement        |
|               |                                      | les monnaies des entités confédérées pour     |
|               |                                      | le commerce local                             |
|---------------+--------------------------------------+-----------------------------------------------|
| international | sur approbation du forum :           | sur approbation du congrès :                  |
|               | traités fédéraux avec l’extérieur    | - traités confédéraux avec l’extérieur        |
|               |                                      | - traités entre une entité confédérée et      |
|               |                                      | l’extérieur                                   |
|---------------+--------------------------------------+-----------------------------------------------|
| commerce      | commerce extérieur unifié            | commerce extérieur :                          |
|               |                                      | - tarifs douaniers harmonisés                 |

* Élections progressives

Les élections progressives divisent les assemblées en groupes électoraux.
Considérons une assemblée comptant /N/ groupes électoraux, chaque groupe
comptant /G/ membres. L’assemblée compte donc au total :

#+BEGIN_EXAMPLE
M = G × N
#+END_EXAMPLE

membres.

On procède à une élection initiale permettant d'élire la totalite de
l’assemblée. Celle-ci est alors répartie en groupes électoraux en
fonction des scores moyens individuels. Le premier groupe comprend
donc les /G/ membres disposant des plus hauts scores, le deuxième
groupe comprend les /G/ membres suivants, et ainsi de suite jusqu’au
/N/^ième groupe qui comprend les membres disposant des scores les plus
faibles.

À la fin de chaque période électorale /T/, un des groupes électoraux
de l’assemblée est choisi et soumis à une élection.

** Rotation des groupes soumis à l'élection

Pendant les /N/ périodes suivant l'élection initiale,
le groupe soumis au vote est le groupe aux scores les plus faibles
parmi les groupes résiduels nommés lors de l'élection initiale.

Par la suite, c’est le groupe le plus anciennement élu
qui est choisi. On assiste donc à une rotation des groupes soumis
à l'élection.

** Valeurs pratiques

En choisissant /N = 12 groupes/ et /T = 1 mois/,
des élections ont lieu tous les mois afin de remplacer un
douzième de chaque assemblée. Au bout d’un an, l’entièreté
des assemblées a été soumis à une élection.

** Élections continues

Dans un système d'élection continue, chaque électeur peut à tout moment
modifier son bulletin. Ces modifications peuvent provoquer le remplacement
d’un ou de plusieurs élus.

L'élection continue est uneforme extrême d’élection progressive.

* Décisions des assemblées

Le mode de décision des assemblées est constitué d’une phase
de discussion et de deux tours.

** Discussions

Les votes sont précédés d’une période de discussion
permettant de proposer une loi, de débattre des amendements,
des variantes, etc.

** Premier tour

Au premier tour, les différentes options proposées (par exemple les
variantes d’une même loi) sont placées sur les bulletins de vote.
Ensuite, chaque membre de l’assemblée attribue un nombre de points
entier compris entre +5 et -5 à chacune des options envisagées, et
l’option victorieuse est celle ayant recolté le plus de points sur
l’ensemble des bulletins.

En cas d’ex-aequo, l’option victorieuse est, par ordre d’importance
décroissant :

  - celle ayant reçu le plus de votes +5
  - celle ayant reçu le moins de votes -5
  - celle ayant reçu le plus de votes +4
  - celle ayant reçu le moins de votes -4
  - celle ayant reçu le plus de votes +3
  - celle ayant reçu le moins de votes -3
  - celle ayant reçu le plus de votes +2
  - celle ayant reçu le moins de votes -2
  - celle ayant reçu le plus de votes +1
  - celle ayant reçu le moins de votes -1

** Second tour

Au second tour, chaque membre de l’assemblée peut s’abstenir
ou voter pour ou contre l’option victorieuse du premier tour.
Il lui suffit de remplir le bulletin suivant son choix :

  - +1 : vote favorable
  - 0 : abstention
  - -1 : vote défavorable

On évalue ensuite le score moyen.

A la majorité simple, l’option n’est appliquée que si le score
moyen est strictement positif.

A la majorité /R/, l’option n’est appliquée que si l'écart
entre le score moyen /S/ et la valeur la plus basse possible (-1)
est au moins /R/ fois plus importante que l'écart entre /S/
et la valeur la plus haute posssible (+1). On doit donc avoir :

#+BEGIN_EXAMPLE
S - (-1) ≥ R × (+1 - S)
#+END_EXAMPLE

c’est-à-dire :

#+BEGIN_EXAMPLE
S ≥ (R - 1) / (R + 1)
#+END_EXAMPLE

À la majorité double, le score moyen doit donc être strictement
supérieur à 1/3

À la majorité triple, le score moyen doit donc être strictement
supérieur à 2/4 = 1/2

** Absence de premier tour

Lorsqu’il n’y a qu’une seule option envisagée, le premier tour est
bien entendu inutile, l’assemblée passe alors directement au second
tour.

* Méta-assemblées

#+TOC: headlines 1 local

** Introduction

Une méta-assemblée est une assemblée

  - constituée de plusieurs sous-assemblées
  - où chaque sous-assemlée dispose d’un droit de vote avec un poids
    bien défini

On note /p_i/ le poids du droit de vote de la sous-assemlée /i/ et :

#+begin_center
P = Σ_j p_j
#+end_center

le poids total de toutes les sous-assemblées. Le poids relatif de la
 sous-assemblée /i/ s’écrit :

#+begin_center
π = p_i / P
#+end_center

Les méta-assemblées disposent de deux modes de fonctionnement.

** Fonctionnement

*** Fluide

Chaque membre de la méta-assemblée vote normalement, indépendamment
des autres membres de la sous-assemblée à laquelle il appartient.

Pour une option ou un candidat donné, on évalue ensuite le score moyen
/S_i/ obtenu dans chaque assemblée /i/. Le score final au niveau de la
méta-assemblée est :

#+BEGIN_EXAMPLE
S = ∑_i p_i × S_i / P
#+END_EXAMPLE

ou plus simplement :

#+BEGIN_EXAMPLE
S = ∑_i π_i × S_i
#+END_EXAMPLE

*** Granulaire

Chaque sous-assemblée effectue un vote interne et attribue les scores
suivant en fonction du résultat :

  - les options ou candidats ayant récolté les *meilleurs scores
    positifs* au vote interne reçoivent, en commençant par le premier,
    les points : +5, +4, +3, +2, +1
  - les options ou candidats ayant récolté les *plus faibles scores
    strictement négatifs* au vote interne reçoivent, en commençant par
    le dernier, les points : -5, -4, -3, -2, -1</li>
  - les autres options ou candidats reçoivent 0 point

Ces scores lui permettent de remplir un unique bulletin de vote
qu’elle remet à la méta-assemblée. L’ensemble des votes de chaque
sous-assemblée permet d'évaluer le résultat final.

Pour une option ou un candidat donné, notons /S_i/ le score obtenu
auprès de la sous-assemblée /i/. Le score au niveau de la
méta-assemblée sera alors :

#+BEGIN_EXAMPLE
S = ∑_i π_i × S_i
#+END_EXAMPLE

** Égalitaire

Dans une /méta-assemblée égalitaire/, chaque sous-assemblée
dispose d’un poids identique /p/. Notons /N/ le nombre
de sous-assemblées. Le poids total est alors de :

#+begin_center
P = N × p
#+end_center

et les poids relatifs :

#+begin_center
π_i = p / (N × p) = 1 / N
#+end_center

sont tous identiques :

#+begin_center
π = 1 / N
#+end_center

#+begin_center
⁂
#+end_center

Par exemple, un sénat fédéral ou une convention confédérale sont des
méta-assemblées égalitaire à fonctionnement fluide.

** Récursivité

Rien ne s’oppose à ce qu’une sous-assemblée soit elle-même une
méta-assemblée. Le jeu des assemblées peut donc former une
arborescence sur plusieurs niveaux.

** Ne pas confondre

Le concept de méta-assemblée est totalement indépendant de celui
de groupe électoral utilisé dans les élections progressives.

* Assemblées composite

Une assemblée composite est une assemblée :

  - constituée de plusieurs sous-assemblées
  - où une décision n’est prise que si toutes les sous-assemblées
    l’approuvent

Il s’agit donc d’un mécanisme d’approbation multiple.

Par exemple, le forum fédéral ou le congrès confédéral sont des
assemblées composites.

** Assemblée double

Une *assemblée double* est une assemblée composite constitutée de deux
assemblées.

** Assemblée triple

Une *assemblée triple* est une assemblée composite constitutée de trois
assemblées.

Etc.

* Exemple d’assemblées d’une confédération

** Commune

  - assemblée populaire composée des citoyens d’une commune
  - assemblée représentative élue par les citoyens d’une commune

** Cité

  - assemblée populaire composée des citoyens d’une cité
  - assemblée représentative élue par les citoyens d’une cité
  - assemblée représentative de la communauté des communes, où chaque
    commune dispose du même nombre de représentants élus
    + méta-assemblée égalitaire où chaque commune de la cité dispose
      d’une assemblée

** État

  - assemblée des citoyens d’un état fédéré
  - assemblée représentative élue par les citoyens d’un état fédéré

** Fédération

Le principe de superposition implique au minimum une double
représentation : celle de l’ensemble des citoyens, et celle de
l’ensemble des entités fédérées.

*** Populaire

  - assemblée des citoyens d’une fédération membre
  - assemblée populaire composée des entités fédérées de la fédération
    + méta-assemblée égalitaire où chaque ensemble de citoyens d’un
      état fédéré de la fédération dispose d’une assemblée

*** Représentative

Principales :

  - assemblée représentative des citoyens, où chaque état dispose d’un
    nombre de représentants proportionnel à sa population
  - assemblée représentative de la communauté des entités, où chaque
    entité dispose du même nombre de représentants élus
    + méta-assemblée égalitaire où chaque état de la fédération
      dispose d’une assemblée

** Confédération

Le principe de superposition implique au minimum une double
représentation : celle de l’ensemble des citoyens, et celle de
l’ensemble des entités confédérées.

*** Populaire

  - assemblée populaire composée des citoyens de la confédération
  - assemblée populaire composée des entités confédérées
    + méta-assemblée égalitaire où chaque ensemble de citoyens d’une
      entité confédérée dispose d’une assemblée

*** Représentatives

Principales :

  - assemblée représentative des citoyens de la confédération
  - assemblée représentative de la communauté des entités confédérées,
    où chaque entité dispose du même nombre de représentants élus

Autres :

  - méta-assemblée égalitaire où chaque commune de la confédération
    dispose d’une assemblée
  - méta-assemblée égalitaire où chaque cité de la confédération
    dispose d’une assemblée

