
#+STARTUP: showall

#+TITLE: Eclats de vers : Agora 03 : Association
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Introduction

Une association est un regroupement formel de citoyens (et/ou
éventuellement d’autres associations).

Une association présente des caractéristiques similaires aux étages de
la collectivité et aux sociétés commerciales de tous types. Elle a :

- un but
- un processus de décision
- des moyens de financement
- un budget
- etc

En fait, on peut considérér qu’un état, une commune, une
société commerciale, une coopérative publique ou autre, sont
des cas particuliers d’association.

* Financement

Une association peut se financer :

- par une contribution des membres
- par des dons du public
- en utilisant les mêmes méthodes qu’une
  [[file:/home/david/racine/site/eclats2vers/generic/grimoire/agora-02-economie.org::#section:societe_commerciale][société commerciale]]

* Fédération d’association

Une fédération d’associations peut utiliser les mêmes outils qu’une
fédération d’états.

Exemple : fédération d’associations d’artistes, une association
pour chaque domaine :

- musique, composition
- littérature, poésie
- peinture
- sculpture
- décoration
- etc

** Double approbation

Le processus de décision peut s’inspirer des approbations doubles
des forums fédéraux et congrès confédéraux. On envisage alors de
créer une double assemblée :

- une première assemblée où chaque association fédérée dispose
  d’un même nombre de représentants
- une seconde assemblée où chaque association fédérée dispose
  d’un nombre de représentants plus ou moins proportionnel au
  nombre de ses membres

Le même principe de double approbation peut être utilisé pour les
référendums internes.

* Commerce

Une association peut avoir un but commercial ou non commercial.
