
#+STARTUP: showall

#+TITLE: Eclats de vers : Agora 02 : Économie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Société commerciale
:properties:
:custom_id: section:societe_commerciale
:end:

#+TOC: headlines 1 local

** Introduction

Une *société commerciale* est une entité juridique fondée et gérée par
un ou plusieurs citoyens.

** Statuts

Les *statuts* d’une société commerciale sont les textes qui en
décrivent les règles particulières.

Au sein du cadre constitutionnel et législatif, la société commerciale
est libre de rédiger et de modifier ses statuts particuliers comme
elle l’entend.

** Fondateur

Une société commerciale est créée par un certain nombre de citoyens
appelés *fondateurs*.

** Sociétaire

Tout citoyen membre d’une société commerciale /A/ est appelé
*sociétaire*, *associé*, ou *coopérateur* de /A/.

L’idée générale est que les sociétaires coopèrent pour développer et
entretenir un projet commun.

Règles générales :

- un fondateur est automaquement sociétaire
- un salarié peut devenir sociétaire s’il le souhaite

D’autres catégories de citoyens peuvent être admises comme
sociétaires, suivant les statuts de la société commerciale. Exemples :

  - investisseurs divers
    + actionnaires
    + détenteurs de rentes
    + détenteurs d’obligations
  - entrepreneurs qui se regroupent pour développer des outils
    communs au sein d’une société
  - fournisseurs
    + les sociétaires procèdent à des ventes groupées via leur
      société, qu’on appelle alors centrale de vente
  - clients
    + les sociétaires procèdent à des achats groupés via leur société,
      qu’on appelle alors centrale d’achat
    + banque mutuelle
  - utilisateurs des biens ou services de la société commerciale

** Titres

Une société commerciale peut se financer en émettant des *titres*
donnant différents droits aux acquéreurs.

*** Part sociale

Une *part sociale* est un titre émis par la société commerciale. Elle
donne un statut de membre de la société commerciale à son détenteur,
ainsi qu’un droit de participation aux décisions. Plus précisément,
chaque part sociale détenue donne droit à un vote à l’assemblée
sociale (voir la section sur les [[#section:assemblees][assemblées]]).

*** Action

Une action est un titre émis par une société commerciale. Il donne
droit à un revenu variable appelé *dividende* versé à la fin de chaque
période.

La période entre deux versements varie généralement entre 3 mois et
un an.

*** Rente

Une rente, ou obligation perpétuelle, est un titre émis par une
société commerciale. Elle donne droit à un revenu fixe appelé
*coupon*, versé à la fin de chaque période.

La période entre deux versements varie généralement entre 3 mois et
un an.

Le montant du coupon est indiqué sur la rente.

*** Obligation

Une obligation est similaire à une rente, si ce n’est qu’elle
est rendue à la société commerciale émettrice à une échéance
fixée en échange de la restitution de la somme initiale consentie par
l’acheteur de l’obligation (le prêteur). Ce dernier reçoit en plus,
à la fin de chaque période, un coupon fixe dont le montant est indiqué
sur l’obligation.

La période entre deux versements varie généralement entre 3 mois et
un an.

** Investisseur

Tout citoyen qui possède au moins une action, une rente ou une
obligation émise par une société commerciale est appelé
*investisseur*.

Récursivité : une société commerciale /S/ peut aussi faire fonction
d’investisseur dans une autre société commerciale /A/.

*** Actionnaire

Un investisseur qui possède une ou plusieurs actions émises par une
société commerciale est appelé *actionnaire*.

*** Rentier

Un investisseur qui possède une ou plusieurs rentes émises par une
société commerciale est appelé *rentier*.

*** Prêteur

Un investisseur qui possède une ou plusieurs obligation émises par une
société commerciale est appelé *prêteur*.

** Modes de distribution des parts sociales

Chaque sociétaire reçoit un nombre déterminé de parts sociales en
fonction de sa catégorie :

- fondateur
  + ce sont les fondateurs qui ont en général le plus de poids,
    et donc le plus de parts sociales
- salarié
  + poids éventuellement proportionnel à l’expérience du salarié
- investisseur
  + poids éventuellement proportionnel au nombre de titres détenus
    (actions, rentes, obligations)
- client
- fournisseur
- utilisateur
- etc

*** Pondération proportionnelle à l’expérience

Chaque sociétaire reçoit une part sociale de la société commerciale
à la fin de chaque période où il y est actif (par exemple un mois,
un trimestre, un an).

Ce système permet de donner plus de poids aux sociétaires
expérimentés.

** Attirer les investisseurs

Afin d’attirer les investisseurs, les statuts de la société peuvent :

- distribuer des parts sociales aux actionnaires, proportionnellement
  au nombre d’actions détenues
  + ce procédé peut aussi s’appliquer aux rentiers et prêteurs,
    avec des pondérations éventuellement distinctes
- partager le pouvoir entre l’assemblée des sociétaires et celle des
  actionnaires pour certaines catégories de décisions
  (voir la section sur les [[#section:assemblees][assemblées]])
- garantir un minimum de redistribution des bénéfices sous forme de dividendes
  + par exemple, au moins 20% des bénéfices annuels de la société commerciale

Bien entendu, ces solutions peuvent être combinées.

** Assemblées
:properties:
:custom_id: section:assemblees
:end:

*** Assemblée sociale

L’ *assemblée sociale* est constituée de l’ensemble des sociétaires.

Le poids du vote de chaque sociétaire est proportionnel au nombre
de part sociales qu’il détient.

*** Assemblée actionnariale

L’ *assemblée actionnariale* est constituée de l’ensemble des actionnaires
de la société commerciale.

Si les statuts le prévoient, l’assemblée actionnariale peut participer
à certaines décisions.

Le poids du vote de chaque actionnaire est proportionnel au nombre
d’actions qu’il détient.

*** Cénacle

Le *cénacle* est l’assemblée qui prend les décisions au sein de
la société commerciale.

**** Simple

Dans le cas le plus simple, le cénacle est identique à l’assemblée
sociale.

**** Double

Si on souhaite faire intervenir les actionnaires dans le processus
de décision, le *cénacle* est alors une double assemblée :

  - assemblée sociale
  - assemblée actionnariale

Les statuts peuvent mentionner certaines décisions ou catégories de
décisions qui nécessitent, suivant les cas :

- la double approbation de ces deux assemblées (sociale et actionnariale)
- l’approbation simple de l’assemblée sociale
- l’approbation simple de l’assemblée actionnariale

En général, l’assemblée actionnariale appréciera de participer
aux décisions qui ont un impact sur les bénéfices à long terme de
la société commerciale, et donc sur les dividendes.

**** Multiple

Dans le cas où il existe plusieurs catégories de sociétaires et
d’investisseurs, les statuts peuvent prévoir un cénacle qui contient
toutes ces catégories :

  - assemblée des sociétaires fondateurs
  - assemblée des sociétaires salariés
  - assemblée des actionnaires
  - assemblée des rentiers
  - assemblée des prêteurs
  - assemblée des sociétaires entrepreneurs
  - assemblée des sociétaires fournisseurs
  - assemblée des sociétaires clients
  - assemblée des sociétaires utilisateurs

Les statuts doivent alors détailler quelles assemblées du cénacle sont
compétentes pour une catégorie de décision donnée. Une approbation
multiple des assemblées concernées est alors nécessaire pour valider
la décision.

Les fondateurs voudront généralement être consultés pour les décisions
ayant une influence sur la direction générale de la société commerciale,
pour rester fidèle à l’idée de départ.

Les actionnaires salariés participeront bien entendu aux décisions
concernant le personnel.

L’assemblée des rentiers appréciera de participer aux décisions
qui ont un impact sur la solvabilité et la survie à long terme de la
société commerciale, et donc sur les coupons. Il en va de même pour
l’assemblée des prêteurs.

Pour les décisions les plus importantes, l’approbation multiple de
toutes les assemblées du cénacle est requise.

*** Modification des statuts

Il faut une majorité des deux tiers du cénacle pour modifier les
statuts.

Si les statuts prévoient d’impliquer le cénacle dans leurs
modifications, il faut une majorité des deux tiers dans chacune de ses
assemblées constitutives pour les modifier.

*** Pas de cumul

Pour éviter les cumuls de mandat et les diverses dérives qui en
découlent :

  - un acteur économique ne peut posséder plus de 5% de pouvoir décisionnel
    d’un secteur économique
    + un sociétaire ne peut posséder en part sociales plus de 5% d’un secteur
      économique
    + un actionnaire ne peut posséder en actions plus de 5% d’un secteur
      économique
    + idem pour les autres catégories d’investisseurs, fournisseurs,
      clients, etc
    + une société ne peut représenter plus de 5% d’un secteur économique
      * par elle-même et à travers ses participations dans d’autres sociétés

Ce ratio de 5% peut naturellement être ajusté via un référendum.

*** Gestion quotidienne

Ke cénacle :

- nomme et révoque les membres d’un conseil restreint chargé
  de la gestion quotidienne de la société
- peut modifier ou annuler les décisions du conseil restreint

** Répartition des bénéfices

Les statuts peuvent définir la répartition du bénéfice avant coût
financier. Exemple :

- entre 20% et 50% pour les sociétaires
- si les statuts le prévoient, un minimum est distribué aux actionnaires
  + par exemple, 20% des bénéfices annuels de la société commerciale
- le reste est réinvesti dans la société

** Récurvisité

Si les statuts de la société commerciale le permettent, une société
commerciale /S/ peut être sociétaire ou actionnaire d’une autre
société commerciale /A/.

Exemples de sociétaires ou actionnaires dans ce cas :

  - des sociétés commerciales qui se regroupent pour développer des
    outils communs
  - les sociétaires ou actionnaires de sociétés commerciales qui
    sont elles-mêmes sociétaires ou actionnaires de /A/

* Sociétés particulières

#+TOC: headlines 1 local

** Société personnelle

Chaque citoyen possède automatiquement sa société commerciale propre,
appelée *société personnelle*, qui n’admet que lui comme sociétaire et
comme actionnaire.

** Sociétés de citoyens

Les *sociétés de citoyens* suivantes sont créées :

  - 1 société par commune
  - 1 société par cité
  - 1 société par état
  - 1 société par fédération
  - 1 société pour la confédération

Chaque citoyen dispose d’une part sociale et d’une action dans les
sociétés de citoyens suivantes :

  - société de sa commune
  - société de sa cité
  - société de son état
  - société de sa fédération
  - société de la confédération

Ces parts sociales et actions sont personnelles et ne peuvent être
échangées. Chaque action donne droit à un dividende.

** Société enveloppe

Dans le cas où, faute de liquidités, le paiement exigerait la vente
d’un bien que le contributeur ne souhaite pas vendre, on procède à la
titrisation de ce bien : une société commerciale servant d’enveloppe
est créée, et le contributeur est donc autorisé à verser la somme en
titres plutôt qu’en liquide :

  - le contributeur place le bien concerné dans la société enveloppe
    dont il détient alors 100% des parts
  - le contributeur verse à l'état la contrevaleur en titres à revenus
    fixes ou variables de la société enveloppe
  - l'état reverse en liquide le montant correspondant aux plus
    démunis

* Société d’actionnaires

#+TOC: headlines 1 local

** Introduction

Il s’agit d’une société commerciale où les actionnaires sont sociétaires.
Les parts sociales sont alors formellement identiques aux actions, et
les assemblées sociale et actionnariale se confondent.

Chaque employé est alors aussi sociétaire et actionnaire. Il reçoit
un certain nombre d’actions à la fin de chaque période (mois, année,
etc). Cette distribution s’effectue en émettant de nouvelles actions,
ce qui augmente mécaniquement le capital. L’ensemble des actions
distribuées au personnel chaque année doit représenter au minimum 5%
du bénéfice annuel de la société. Ce ratio de 5% peut naturellement
être ajusté via un référendum.

* Coopérative publique

#+TOC: headlines 1 local

** Introduction

Une *coopérative publique* est une société qui remplit une mission de
service public. Elle ressemble à une société commerciale classique,
mais avec quelques différences :

  - les sociétaires sont tous des représentants élus par l’ensemble des citoyens
    + les salariés ne sont donc sociétaires que s’ils sont élus
  - des référendums sur initiative de la population permettent de
    prendre ou annuler une décision de la coopérative publique
    + ces décisions sont prépondérantes par rapport à celles de
      du cénacle de la coopérative
  - le bénéfice est régulé pour compenser le coût total
    + salaires
    + investissements
    + usure du matériel (amortissement)
    + coût financier versé aux investisseurs
    + ...

Elle doit également offrir :

  - une bonne qualité
  - des tarifs modérés
  - des salaires corrects
  - une activité respectueuse de l’environnement

Leur but est de créér un cadre souple mais efficace et éthique ou
l'économie peut s'épanouir dans l’intérêt général.

** Étages de la collectivité

Une coopérative publique peut être créée par n’importe quel étage de
collectivité :

  - commune
  - cité
  - région
  - état
  - fédération
  - confédération

Son assemblée de sociétaires est naturellement élue par les citoyens
de l’étage de collectivité qui la crée.

Une coopérative publique créée par la confédération aura une assemblée
double de type congrès confédéral.

Une coopérative publique créée par une fédération aura une assemblée
double de type forum fédéral.

** Actionnariat

L’actionnariat d’une coopérative publique doit respecter les règles
suivantes :

  - la part publique totale est d’au moins 75%
    + part attribuée équitablement aux citoyens : 50%
    + part attribuée à l'étage de la collectivité : 25%
    + composée d’actions non échangeables
  - les actionnaires privés doivent être des citoyens de la
    confédération
    + une société commerciale n’est pas pas autorisée à être
      actionnaire d’une coopérative publique

Exemple d’actionnariat d’une coopérative publique confédérale :

  - 50% pour les citoyens
  - 25% pour les institutions confédérales et entités
    * 5% des titres sont attribués à la confédération
    * 20% des titres sont répartis équitablement entre les entités
      confédérées
      - si l’entité fédérée est elle-même une fédération, sa part est
        répartie comme suit
        + 25% de la part va à la fédération
        + 75% de la part est réparti entre les états membres
  - actions échangeables
    + 25% des titres s'échangent librement sur le marché

** Secteurs économiques

Les coopérative publiques sont créées par décision d’un référendum.

On les retrouve en général dans les secteurs économiques stratégiques,
d’infrastructure, et les secteurs où une concurrence ordinaire seule
n’a pas beaucoup de sens :

- ressources naturelles
  + source d’eau potable
  + gisement
- alimentation
- immobilier
- environnement
  + assainissement
- enseignement
- soin
- énergie
  + barrage hydro-électrique
- transport
  + chemin de fer
- communication
  + réseaux sociaux
  + média, presse
- ...

Précisions :

  - le statut de coopérative publique ne donne pas un avantage
    d’exclusivité sur un secteur économiques, celui-ci reste ouvert
    aux compétiteurs
    + le but est d’ailleurs de générer une concurrence entre sociétés
      privées et coopératives publiques
    + par contre, les sociétés privées positionnées dans des secteurs
      stratégiques doivent respecter des règles supplémentaires
      permettant d’assurer la protection et la bonne gestion des
      ressources naturelles
  - il peut très bien y avoir plusieurs coopératives publiques opérant
    dans le même secteur économique
  - une coopérative publique ne bénéficie pas forcément d’une position
    dominante

* Brevet

Un *brevet* certifie que son détenteur est l’auteur d’une découverte
scientifique ou technique bien précise.

Le détenteur d’un brevet est rémunéré par une fraction du bénéfice
généré par cette découverte. Cette fraction est prélevée dans toutes
les sociétés commerciales qui utilisent la découverte associée.

La licence est universelle au sein de la fédération : toutes les
sociétés commerciales peuvent utiliser la découverte à condition de
s’acquitter de la fraction légale des recettes engendrées.

La validité d’un brevet est limitée à une durée de /N/ années. Par la
suite, la découverte pourrat être utilisée gratuitement.

La fraction et La durée de validité sont déterminées par référendum et
valables pour toutes les sociétés commerciales de la fédération.

* Concurrence et régulation

#+TOC: headlines 1 local

** Introduction

La philosophie générale est d’encadrer et de réguler les instabilités
potentielles de l'économie et des marchés financiers, tout en laissant à
ceux-ci une large marge de manoeuvre.

L’instabilité la plus fréquente étant la concentration excessive de
pouvoir, le rôle premier de la régulation sera d’éviter la formation
de ces concentrations.

** Concurrence

Afin d'éviter toute concentration excessive, la règle par défaut est la
suivante : le poids consolidé d’une société commerciale et de ses
filiales sur l’offre ou la demande d’un marché ne peut pas excéder
5%. Ce ratio de 5% peut naturellement être ajusté via un référendum.
Ceci s’applique donc :

- aux vendeurs
  + fournisseurs
  + etc
- aux acheteurs
  + clients
  + consommateurs finaux
  + etc

Dans le cas où une société commerciale dépasse ce seuil, un référendum
décide si elle est :

- contrainte de vendre certaines de ses participations, ce qui peut
  suffire dans certains cas à la faire redescendre sous le seuil des 5%
- scindée en plusieurs sociétés de taille réduite
- transformée en coopérative publique

Au niveau local (commune par exemple), ces solutions ne sont pas toujours
possibles ou souhaitables. On peut alors :

- stimuler la formation de sociétés commerciales concurrentes
- réguler divers paramètres de la société
  + fixer des prix maximum pour ses produits
  + fixer un niveau de salaire maximal (confortable mais sans excès)

** Poids consolidé

Le facteur déterminant étant le poids consolidé, c’est-à-dire en
incluant les participations et les filiales de la société commerciale,
celle-ci devra être attentive à ne pas dépasser un certain seuil dans
ses participations.

Par exemple, si une société commerciale a une part de marché de 3%, et
qu’elle compte prendre une participation P dans une société
commerciale qui possède 4% de part de marché, on a la contrainte :

#+BEGIN_EXAMPLE
3% + P × 4% ≤ 5%
#+END_EXAMPLE

Ce qui nous mène à un maximum pour la participation :

#+BEGIN_EXAMPLE
P ≤ (5% - 3%) / 4%
P ≤ 2% / 4%
P ≤ 1 / 2 = 50%
#+END_EXAMPLE

** Quelle solution privilégier

- coopérative publique
  + dans les secteurs qui forment le socle de l’économie :
    * ressources naturelles
    * transport
    * énergie
    * secteurs stratégiques
  + dans les secteurs où la concurrence est structurellement difficile
    à réaliser
    * exemple : chemins de fer
  + division en plusieurs sociétés
    * dès que raisonnablement possible

** Coopérative publique

Une coopérative publique étant sous contrôle de représentants élus et
de référendums, elle est autorisée à dépasser le seuil des 5%. On sera
particulièrement attentif à ce qu’elle n’abuse pas de ce privilège.

En contrepartie de ce privilège, la coopérative publique doit mettre en
place une régulation :

- des prix
- des salaires
- de la qualité
- de la quantité
- etc

** Actionnaire

On peut appliquer les mêmes principes au niveau des actionnaires, pour
éviter qu l’un d’entre-eux ne possède trop d’influence.

** Nouveau secteur économiques

Une société commerciale qui crée un nouveau secteur économiques est
par définition en position dominante puisqu’elle représente par
définition 100% du secteur.

Diviser cette société commerciale serait en général prématuré et
n’aurait économiquement pas de sens.

Dans ce cas, une dérogation est accordée à cette société commerciale,
lui permettant de rester en position dominante durant les /N/
premières années de l’existence du secteur économique. Pour compenser
cette position dominante :

  - d’autres sociétés commerciales sont bien entendu autorisées, et
    même encouragées, à s’inviter sur ce nouveau secteur
    + les brevets détenus par la société dominante sont mis à
      leur disposition
  - une coopérative publique est créée dans le même secteur afin de
    créer un minimum de concurrence

Après ce délai de /N/ années, les règles habituelles s’appliquent, et
la société commerciale se verra scindée, transformée en coopérative
publique, régulée ou mise en concurrence avec de nouveaux acteurs.

Exemple raisonnable de /N/ : entre 5 et 10.

** Économie locale

On évitera autant que possible la formation de concentration excessive
au niveau local.

Exemple : pas de concentration excessive dans l’immobilier d’une commune.

Dans certains cas, aucune des solutions applicables à grande échelle
n’est souhaitable. Par exemple, il ne serait pas raisonnable de scinder
l’unique boulangerie d’un village. Étant donné son caractère de
modeste propriété familiale, il serait aussi contraire à l’éthique
et aux libertés fondamentales de la transformer en coopérative publique
à l’échelle communale. Dans ce cas, il est préférable de :

- réguler les prix de ses produits, en fixant par exemple des tarifs maximum
- stimuler la création de boulangeries concurrentes

* Protectionnisme

#+TOC: headlines 1 local

** Filiale à l’étranger

Si une société commerciale de la confédération souhaite opérer à
l’étranger, elle doit le faire via une filiale dans le pays souhaité.

Afin de décourager les délocalisations à l’étranger, le bénéfice
réalisé via cette filiale est taxé de façon plus importante que le
bénéfice réalisé à l’intérieur de la confédération.

** Société commerciale étrangère

Si une société commerciale étrangère à la confédération souhaite y
opérer, elle doit créer une filiale à l’intérieur de celle-ci. La
participation de la maison mère étrangère dans cette filiale est de
maximum 40%.

* Monnaie

#+TOC: headlines 1 local

** Livre des comptes

Le *livre des comptes* :

  - émet la monnaie
  - tient les comptes
  - garantit la valeur de la monnaie

** Contrôle démocratique

  - des référendums sur initiative de la population sont disponibles
    + prendre ou annuler une décision
  - le livre des comptes est dirigé par une assemblée de représentants
    élus
    + assemblée double de type congrès confédéral

** Émission

Le livre des comptes est chargée d'émettre la monnaie fiduciaire
et scripturale.

** Comptes bancaires

Le livre des comptes tient un compte pour chaque société commerciale.
Il tient également un compte pour chaque citoyen via les sociétés
personnelles. Ces derniers peuvent déposer ou retirer leur argent
quand ils le souhaitent et le service est gratuit.

Les transactions entre citoyens et entre sociétés se réalisent :

  - soit par monnaie physique
  - soit par virement entre leurs comptes

Les données concernant les opérations sur les comptes sont
confidentielles, et ne peuvent être accédées que lors de conditions
juridiques précisément définies :

  - litige entre deux parties
  - etc

** Banques mutuelles

Une *banque mutuelle* est une banque où les citoyens qui y possède un
compte sont des sociétaires.

Une banque mutuelle peut :

  - offrir un service de compte bancaire

Une banque mutuelle ne peut pas :

  - investir plus que 90% du montant total qu’elle garde en dépôt

Le type d’investissement pratiqué par une banque mutuelle doit être
clairement communiqué aux clients-déposants-sociétaires :

  - diversification
  - qualité
  - catégories
    + prêts
    + achat d’actions
    + transactions sur les marchés à terme
    + ...

** Panier en contrepartie

Le Livre des comptes garantit la valeur de la monnaie en permettant de
l'échanger à un prix Π constant contre un panier de produits
tangibles, appelé panier de référence et comprenant :

  - des matières premières
  - de l’alimentation
  - de l’immobilier
  - des terrains cultivables
  - des outils de production
  - etc

On a donc l'équivalence :

#+begin_example
1 panier = Π unités monétaires
#+end_example

Chacun peut donc acheter de tels paniers en échange d’un paiement en
liquide ou d’une diminution du montant sur son compte. Naturellement,
de tels paniers peuvent également être vendus au même prix Π contre
du liquide ou une augmentation du montant sur son compte.

Afin de satisfaire la demande en paniers de référence, le Livre des
comptes dispose d’un droit de réquisition sur les biens et la
production de chaque société commerciale. En échange, les comptes des
sociétés commerciales sont crédités d’un montant équivalent à la
contrevaleur de leur contribution. Afin de répartir la charge, les
réquisitions doivent impérativement être réparties entre les sociétés
commerciales, et ce proportionnellement à la valeur des biens et de la
production de chacune d’entre elles.

Le livre de compte sert dans ce cas d’intermédiaire entre acheteurs et
producteurs, tout en régulant les prix.

* Marché financier

#+TOC: headlines 1 local

** Centralisation

Les marchés financiers portant sur les produits importants :

  - titres émis par des sociétés commerciales
    + actions
    + rentes
    + obligations
  - matières premières
  - alimentation
  - etc

sont centralisés au niveau confédéral afin de garantir une
transparence optimale (prix unique à un instant donné, ...) aux
citoyens.

** Pas de transactions ultra-rapides

Afin d’éviter les abus dus aux transactions ultra-rapides, un minimum
d’une seconde est requis entre deux transactions par le même
intervenant.

** Contrôle démocratique

  - des référendums sur initiative de la population sont disponibles
    + prendre ou annuler une décision
  - le marché centralisé est dirigé par une assemblée de représentants
    élus
    + assemblée double de type congrès confédéral

** Cotation

Les marchés sont des lieux de rencontre entre tous les acheteurs et
vendeurs potentiels d’un même produit. Les meilleures offres d’achats
et de vente sont rendues disponible à tous dans le carnet d’ordre,
afin de favoriser les échanges aux meilleurs prix (appelés cours)
possibles. On appelle ce procédé une *cotation en continu*.

En plus de cette cotation en continu, on organise deux *fixing* par
jour. Les ordres sont alors cachés et accumulés dans une boîte noire.
Au bout de 30 minutes, on les découvre et on calcule l’intersection
des courbes d’offre et de demande agrégées, ce qui donne le prix
optimal et la quantité échangée.

** Marchés au comptant

Sur les marchés au comptant, le vendeur remet immédiatement le produit
à l’acheteur, et reçoit immédiatement son prix en échange.

** Marchés à terme

Sur les marchés à terme, des contrats sont conclus entre acheteurs et
vendeurs, qui s’engagent respectivement à payer et à livrer le produit
dans le futur, à une date appelée échéance.

Pour un produit donné, les contrats à terme de même échéance sont
standardisés, donc échangeables. Chaque échéance fait donc l’objet
d’une cotation séparée.

Ces marchés sont symétriques car il permettent d’acheter à terme avant
ou après avoir vendu à terme.

Une position d’achat à terme peut être cloturée à tout moment en
vendant la même quantité de contrats à la même échéance.

Une position de vente à terme peut être cloturée achetant la même
quantité de contrats à la même échéance.

*** Chambre de compensation

La chambre de compensation sert d’intermédiaire entre les acheteurs et
les vendeurs.

**** Appels de marge

Afin d'éviter les défauts de paiement, chaque intervenant d’un marché
à terme doit mettre à disposition une somme appelée marge représentant
au minimum 20% de la valeur des contrats qu’il a conclu. En pratique,
cette somme est versée sur un compte prévu à cet effet dans le système
de la chambre de compensation.

A chaque cotation, si le cours monte, la chambre de compensation
s’occupe de créditer les marges des acheteurs et de débiter les
comptes des vendeurs de la différence de cours multiplié par le nombre
de contrats qu’ils ont conclus.

Par contre, si le cours chute, les comptes des acheteurs sont débités
et les comptes des vendeurs crédités de la différence de cours
multiplié par le nombre de contrats qu’ils ont conclus.

Un intervenant qui n’a plus assez de marge sur son compte est obligé,
soit de renflouer celui-ci, soit de cloturer sa position.

**** Nettoyage des positions cloturées

La chambre de compensation détecte les positions cloturées et annule
les contrats correspondants, après avoir ajusté les marges des
intervenants, en fonction de leurs gains ou pertes respectifs.

** Les prêts - emprunts

Un contrat de prêt - emprunt est un contrat par lequel le prêteur cède
provisoirement un produit à l’emprunteur. En contrepartie, ce dernier
s’engage à restituer à l'échéance fixée le dit produit plus une
compensation financière.

Le montant de cette compensation financière est déterminée par la
valeur du produit prêté et une variable appelée taux d’intérêt :

#+BEGIN_EXAMPLE
Compensation = Taux d’intérêt × Cours du produit au début du prêt x Nombre de produits prêtés
#+END_EXAMPLE

Pour un produit donné, les contrats de prêt - emprunt de même échéance
sont standardisés, donc échangeables. Chaque échéance fait l’objet
d’une cotation séparée où le taux d’intérêt est la variable cotée du
contrat, les meilleurs ordres prêteurs étant ceux demandant le taux
d’intérêt le plus faible, et les meilleurs ordres emprunteurs étant
ceux offrant le taux d’intérêt le plus élevé.

Le produit prêté - emprunté peut-être :

  - de l’argent
  - un produit financier
  - une matière première
  - etc

** Produits stratégiques

En cas de forte hausse sur un produit stratégiques, les coopératives
publiques présentes sur le secteur économique sont amenées à en
augmenter la production pour faire redescendre le prix.

* Impôts

#+TOC: headlines 1 local

** Transparence

Pour des raisons de transparence, tout objectif collectif doit se
financer sur un fond propre alimenté par l’impôt correspondant. Les
flux financiers sont alors clairement visibles.

Vient s’ajouter à ces impôts particuliers un impôt générique
alimentant un fond servant de tampon.

** Taux d’imposition

Lorsque l’impôt consiste à soustraire une fraction d’une certaine
somme S et que l’on souhaite que la contribution des fortes sommes
soit plus importante que celle des petites, on évalue le taux
d’imposition Λ par :

#+BEGIN_EXAMPLE
Λ = min { Λ_min + γ × S ; Λ_max }
#+END_EXAMPLE

où Λ_min est le taux d’imposition minimal, Λ_max le taux d’imposition
maximal et γ sa vitesse de croissance. Le calcul de l’impôt est alors
immédiat :

#+begin_example
Impôt = Λ × S = min { Λ_min + γ × S ; Λ_max } × S
#+end_example

** Répartition des impôts

  - Vôté par l’assemblée chargée de répartir les budgets

* Distribution des richesses
:PROPERTIES:
:CUSTOM_ID: heading:distribution_richesses
:END:

Soit V_min la valeur des biens du citoyen le plus démuni et V_max la
valeur des biens du citoyen le plus aisé. On exige que :

  - V_min reste supérieur au minimum Δ d’une vie digne
  - V_max / V_min reste inférieur à un rapport Γ

Si V_min passe en-dessous de Δ, ou si le rapport V_max / V_min dépasse
Γ, les citoyens les plus aisés sont mis à contribution pour renflouer
les plus démunis, jusqu'à ce que les deux critères ci-dessus soient de
nouveau remplis.

On procède comme suit : le citoyen le plus aisé est seul mis à
contribution jusqu'à ce que la valeur de ses biens devienne égale à
celle du deuxième citoyen le plus riche. Ils contribuent alors
équitablement à deux jusqu'à ce qu’ils atteignent le troisième, et
ainsi de suite.

Le rapport Γ est à fixer dans une fourchette de 10 à 100.

* Allocation universelle

#+TOC: headlines 1 local

** Introduction

/alias/ : revenu universel

  - allocation de base versée à tous les citoyens sans condition
  - doit permettre de vivre dignement et de réaliser des projets
    personnels, mais sans luxe

** Avantages

- simplification
  + remplace
    * allocations familiales, qui deviennent les allocations universelles
      des enfants, destinées à augmenter avec l’âge
    * allocations de chômage
    * pension
  + rend inutile
    * le salaire minimum

** Financement

  - principalement par
    + la [[#heading:distribution_richesses][distribution des richesses]]
    + les revenus des coopératives publiques
  - marginalement par
    + la création monétaire correspondant à la croissance économique

* Travail

Le temps de travail doit être partagé équitablement afin de laisser le
plus de loisir possible à la population, qui a a lors le temps
d’accomplir des tâches plus enrichissantes.

* Divers

** Titres

Attention de ne pas confondre :

  - les dépôts, que l’on peut voir comme des prêts à échéance
    indéterminée laissée au gré du prêteur
  - les rentes, ou obligations perpétuelles qui ne comportent pas
    d'échéance.
  - les prêts classiques qui sont à échéance fixe
