
#+STARTUP: showall

#+TITLE: Eclats de vers : Agora 02 : Économie
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Société commerciale

#+TOC: headlines 1 local


** Introduction

Une *société commerciale* est une entité juridique fondée et gérée par
un ou plusieurs citoyens.


** Statuts

Les *statuts* d’une société commerciale sont les textes qui en
décrivent les règles particulières.

Au sein du cadre constitutionnel et législatif, la société commerciale
est libre de rédiger et de modifier ses statuts particuliers comme
elle l’entend.


** Fondateur

Une société commerciale est créée par un certain nombre de citoyens
appelés *fondateurs*.


** Sociétaire

Tout citoyen membre d’une société commerciale /A/ est appelé
*sociétaire*, *associé*, ou *coopérateur* de /A/.

Chaque sociétaire reçoit une *part* de la société commerciale en
échange d’un apport initial.

Les citoyens suivant sont toujours sociétaires, indépendamment des
statuts de la société commerciale :

  - les fondateurs de la société commerciale, qui sont en fait ses
    premiers sociétaires
  - les salariés de la société commerciale

Autre cas, qui dépendent des statuts de la société commerciales :

  - entrepreneurs indépendants regroupés dans cette société
    commerciales pour développer des outils en commun
  - clients réguliers enregistrés
  - utilisateurs des biens ou services de la société commerciale

L’idée générale est que les sociétaires coopèrent pour développer et
entretenir un projet commun.


** Titres

Une société commerciale peut se financer en émettant des *titres*
donnant différents droits aux acquéreurs.


*** Action

Une action est un titre émis par une société commerciale. Il donne
droit à un revenu variable appelé *dividende* versé à la fin de chaque
période.

La période varie généralement entre 3 mois et un an.


*** Rente

Une rente, ou obligation perpétuelle, est un titre émis par une
société commerciale. Elle donne droit à un revenu fixe appelé
*coupon*, versé à la fin de chaque période.

La période varie généralement entre 3 mois et un an.

Le montant du coupon est indiqué sur le titre.


*** Obligation

Une obligation est similaire à une rente, si ce n’est qu’elle est
rendue à la société commerciale émettrice à une échéance fixée en
échange de la restitution de la somme initiale consentie par
l’acheteur. Ce dernier reçoit en plus, chaque année, un coupon fixe
dont le montant est indiqué sur l’obligation.


** Investisseur

Tout citoyen qui possède un ou plusieurs titres émis par une société
commerciale est appelé *investisseur*.


*** Actionnaire

Un investisseur qui possède une ou plusieurs actions émises par une
société commerciale est appelé *actionnaire*.


*** Rentier

Un investisseur qui possède une ou plusieurs rentes émises par une
société commerciale est appelé *rentier*.


*** Actions et sociétaires

Une quantite d’actions correspondant à 5% du capital est émise à la
fin de chaque période et distribuée équitablement aux sociétaires.

La période est d’un an maximum.

Les bénéficiaires ont alors un double statut de sociétaire et
d’actionnaire. Ils peuvent donc participer aux assemblées
correspondantes.


** Assemblées


*** Assemblée sociale

L’assemblée sociale est constituée de l’ensemble des sociétaires.
Chaque sociétaire y dispose d’une voix.


*** Assemblée financière

L’assemblée financière est constituée de l’ensemble des investisseurs,
autrement dit de l’ensemble des détenteurs de titres de la société
commerciale.

Le poids du vote de chaque investisseur est proportionnel à la
moyenne :

  - du nombre d’actions qu’il détient divisé par le nombre total d’actions
  - du nombre de rentes qu’il détient divisé par le nombre total de rentes


*** Assemblée des actionnaires

L’assemblée des actionnaires est constituée de l’ensemble des
actionnaires de la société commerciale.

Chaque action donne droit à un vote. Le poids du vote d’un actionnaire
est donc proportionnel au nombre d’actions qu’il possède.


*** Assemblée des rentiers

L’assemblée des rentiers est constituée de l’ensemble des rentiers de
la société commerciale.

Chaque rente donne droit à un vote. Le poids du vote d’un rentier
est donc proportionnel au nombre de rentes qu’il possède.


** Cénacle

Les décisions importantes de la société commerciale nécessitent la
double approbation de ces deux assemblées :

  - assemblée sociale
  - assemblée financière

L’ensemble de ces deux assemblées forme le *cénacle* de la société.


** Gestion quotidienne

La cénacle nomme les membres d’un conseil restreint chargé de la
gestion quotidienne de la société.


* Sociétés particulières

#+TOC: headlines 1 local


** Société personnelle

Chaque citoyen possède automatiquement sa société commerciale propre,
appelée *société personnelle*, qui n’admet que lui comme sociétaire et
comme actionnaire.


** Sociétés de citoyens

Les *sociétés de citoyens* suivantes sont créées :

  - 1 société par commune
  - 1 société par cité
  - 1 société par état
  - 1 société par fédération
  - 1 société pour la confédération

Chaque citoyen dispose d’une action dans les sociétés de citoyens
suivantes :

  - société de sa commune
  - société de son état
  - société de sa fédération
  - société de la confédération

Ces actions sont personnelles et ne peuvent être échangées. Chaque
action donne droit à un dividende.


** Coopérative publique

#+TOC: headlines 1 local


*** Introduction

Une *coopérative publique* est une société commerciale où :

  - les sociétaires sont des représentants élus par les citoyens
  - des référendums sur initiative de la population permettent de
    prendre ou annuler une décision
    + ces décisions sont prépondérantes par rapport à celles du
      cénacle de la coopérative publique
  - le bénéfice est régulé pour compenser le coût total
    + salaires
    + investissements
    + usure du matériel (amortissements)
    + coût financier versé aux investisseurs
    + ...

Elle doit également offrir les tarifs les plus bas et les salaires les
plus hauts possibles, ainsi qu’une qualité élevée.

Leur but est de créér un cadre souple mais efficace ou l'économie peut
s'épanouir dans l’intérêt général.


*** Actionnariat

L’actionnariat d’une coopérative publique doit respecter les règles
suivantes :

  - la part publique soit d’au moins 70%
    + la moitié des dividendes versés aux différents étages de la
      collectivité (confédération, entités confédérée, fédération,
      états membres, etc) doit être redistribué à la population via
      les sociétés de citoyens correspondantes
  - les actionnaires privés sont tous des citoyens de la confédération
    + une société commerciale n’est pas pas autorisée à être
      actionnaire d’une coopérative publique

Exemple d’actionnariat d’une coopérative publique :

  - actions non échangeables
    + 15% des titres sont attribués à la confédération
    + 60% des titres sont répartis équitablement entre les entités
      confédérées
      * si l’entité fédérée est elle-même une fédération, sa part est
	répartie comme suit
	+ 25% de la part va à la fédération
	+ 75% de la part est réparti entre les états membres
  - actions échangeables
    + 25% des titres s'échangent librement sur le marché
    + les acquéreurs doivent être des citoyens
    + les sociétés commerciales ne sont pas autorisées à en détenir


*** Secteurs

Les coopérative publiques sont créées par décision d’un référendum.

On les retrouve en général dans des secteurs stratégiques où une
concurrence ordinaire seule n’a pas beaucoup de sens :

  - ressources naturelles
    + source d’eau potable
    + gisement
  - énergie
    + barrage hydro-électrique
  - transport
    + chemin de fer
  - communication
    + réseaux sociaux
    + presse
  - ...

Précisions :

  - le statut de coopérative publique ne donne pas un avantage
    d’exclusivité sur un secteur, celui-ci reste ouvert aux
    compétiteurs
    + le but est d’ailleurs de générer une concurrence entre sociétés
      privées et coopératives publiques
  - il peut très bien y avoir plusieurs coopératives publiques opérant
    dans le même secteur
  - une coopérative publique ne bénéficie pas forcément d’une position
    dominante


** Société enveloppe

Dans le cas où, faute de liquidités, le paiement exigerait la vente
d’un bien que le contributeur ne souhaite pas vendre, on procède à la
titrisation de ce bien : une société commerciale servant d’enveloppe
est créée, et le contributeur est donc autorisé à verser la somme en
titres plutôt qu’en liquide :

  - le contributeur place le bien concerné dans la société enveloppe
    dont il détient alors 100% des parts
  - le contributeur verse à l'état la contrevaleur en titres à revenus
    fixes ou variables de la société enveloppe
  - l'état reverse en liquide le montant correspondant aux plus
    démunis


* Concurrence et régulation

#+TOC: headlines 1 local


** Introduction

La philosophie générale est d’encadrer et de réguler les instabilités
potentielles de l'économie et des marchés financiers, tout en laissant à
ceux-ci une large marge de manoeuvre.

L’instabilité la plus fréquente étant la concentration excessive de
pouvoir, le rôle premier de la régulation sera d’éviter la formation
de ces concentrations.


** Concurrence

Afin d'éviter toute position dominante, la règle par défaut est la
suivante : le poids consolidé d’une société commerciale et de ses
filiales sur l’offre ou la demande d’un marché ne peut pas excéder 5%.

Dans le cas où une société commerciale dépasse ce seuil, un référendum
décide si elle est :

  - divisée en plusieurs sociétés de taille plus petite
  - transformée en coopérative publique

La coopérative publique est sous contrôle de représentants élus et de
référendums, et est autorisée à ce titre à dépasser le seuil des 5%.

#+begin_center
⁂
#+end_center

Par exemple, si une société commerciale a une part de marché de 3%, et
qu’elle compte prendre une participation P dans une société
commerciale qui possède 4% de part de marché, on a la contrainte :

#+BEGIN_EXAMPLE
3% + P × 4% ≤ 5%
#+END_EXAMPLE

Ce qui nous mène à un maximum pour la participation :

#+BEGIN_EXAMPLE
P ≤ (5% - 3%) / 4%
P ≤ 2% / 4%
P ≤ 1 / 2 = 50%
#+END_EXAMPLE


* Protectionnisme

#+TOC: headlines 1 local


** Filiale à l’étranger

Si une société commerciale de la confédération souhaite opérer à
l’étranger, elle doit le faire via une filiale dans le pays souhaité.

Afin de décourager les délocalisations à l’étranger, le bénéfice
réalisé via cette filiale est taxé de façon plus importante que le
bénéfice réalisé à l’intérieur de la confédération.


** Société commerciale étrangère

Si une société commerciale étrangère à la confédération souhaite y
opérer, elle doit créer une filiale à l’intérieur de celle-ci. La
participation de la maison mère étrangère dans cette filiale est de
maximum 40%.


* Monnaie

#+TOC: headlines 1 local


** Introduction

Le *livre des comptes* :

  - émet la monnaie
  - tient les comptes
  - garantit la valeur de la monnaie

Pour éviter tout abus de pouvoir :

  - le livre des comptes est dirigé par une assemblée distincte de
    représentants élus
  - des référendums sur initiative de la population sont disponibles
    + prendre ou annuler une décision


** Émission

Le livre des comptes est chargée d'émettre la monnaie fiduciaire
et scripturale.


** Comptes bancaires

Le livre des Comptes tient les comptes de chaque société commerciale.
Il tient également les comptes de chaque citoyen via les sociétés
personnelles. Il est le seul autorisé à recevoir des dépôts des
citoyens et des sociétés. Ces derniers peuvent retirer leur argent
quand ils le souhaitent et le service est gratuit.

Les transactions entre citoyens et entre sociétés se réalisent :

  - soit par monnaie physique
  - soit par virement entre leurs comptes

Les données concernant les opérations sur les comptes sont
confidentielles, et ne peuvent être accédées que lors de conditions
juridiques précisément définies :

  - litige entre deux parties
  - etc


** Panier en contrepartie

Le Livre des comptes garantit la valeur de la monnaie en permettant de
l'échanger à un prix Π constant contre un panier de produits
tangibles, appelé panier de référence et comprenant :

  - des matières premières
  - de l’alimentation
  - de l’immobilier
  - des terrains cultivables
  - des outils de production
  - etc

On a donc l'équivalence :

#+begin_example
1 panier = Π unités monétaires
#+end_example

Chacun peut donc acheter de tels paniers en échange d’un paiement en
liquide ou d’une diminution du montant sur son compte. Naturellement,
de tels paniers peuvent également être vendus au même prix Π contre
du liquide ou une augmentation du montant sur son compte.

Afin de satisfaire la demande en paniers de référence, le Livre des
comptes dispose d’un droit de réquisition sur les biens et la
production de chaque société commerciale. En échange, les comptes des
sociétés commerciales sont crédités d’un montant équivalent à la
contrevaleur de leur contribution. Afin de répartir la charge, les
réquisitions doivent impérativement être réparties entre les sociétés
commerciales, et ce proportionnellement à la valeur des biens et de la
production de chacune d’entre elles.

Le livre de compte sert dans ce cas d’intermédiaire entre acheteurs et
producteurs, tout en régulant les prix.


* Marchés

#+TOC: headlines 1 local


** Centralisation

Les marchés portant sur les produits importants :

  - titres émis par des sociétés commerciales
  - matières premières
  - alimentation
  - etc

sont centralisés au niveau confédéral afin de garantir une
transparence optimale (prix unique à un instant donné, ...) aux
citoyens.

Afin d’éviter les abus de transactions ultra-rapide, un minimum d’une
seconde est requis entre deux transaction par le même intervenant.

Pour éviter toute concentration de pouvoir :

  - des référendums sur initiative de la population sont disponibles
    + prendre ou annuler une décision
  - le marché centralisé est dirigé par une assemblée distincte de
    représentants élus


** Cotation

Les marchés sont des lieux de rencontre entre tous les acheteurs et
vendeurs potentiels d’un même produit. Les meilleures offres d’achats
et de vente sont rendues disponible à tous dans le carnet d’ordre,
afin de favoriser les échanges aux meilleurs prix (appelés cours)
possibles. On appelle ce procédé une *cotation en continu*

En plus de cette cotation en continu, on organise deux *fixing* par
jour. Les ordres sont alors cachés et accumulés dans une boîte noire.
Au bout de 30 minutes, on les découvre et on calcule l’intersection
des courbes d’offre et de demande agrégées, ce qui donne le cours
optimal et la quantité échangée.


** Marchés au comptant

Sur les marchés au comptant, le vendeur remet immédiatement le produit
à l’acheteur, et reçoit son prix en échange.


** Marchés à terme

Sur les marchés à terme, des contrats sont conclus entre acheteurs et
vendeurs, qui s’engagent respectivement à payer et à livrer le produit
dans le futur, à une date appelée échéance.

Pour un produit donné, les contrats à terme de même échéance sont
standardisés, donc échangeables. Chaque échéance fait donc l’objet
d’une cotation séparée.

Ces marchés sont symétriques car il permettent d’acheter à terme avant
ou après avoir vendu à terme.

Une position d’achat à terme peut être cloturée à tout moment en
vendant la même quantité de contrats à la même échéance.

Une position de vente à terme peut être cloturée achetant la même
quantité de contrats à la même échéance.


*** Chambre de compensation

La chambre de compensation sert d’intermédiaire entre les acheteurs et
les vendeurs.


**** Appels de marge

Afin d'éviter les défauts de paiement, chaque intervenant d’un marché
à terme doit mettre à disposition une somme appelée marge représentant
au minimum 20% de la valeur des contrats qu’il a conclu. En pratique,
cette somme est versée sur un compte prévu à cet effet dans le système
de la chambre de compensation.

A chaque cotation, si le cours monte, la chambre de compensation
s’occupe de créditer les marges des acheteurs et de débiter les
comptes des vendeurs de la différence de cours multiplié par le nombre
de contrats qu’ils ont conclus.

Par contre, si le cours chute, les comptes des acheteurs sont débités
et les comptes des vendeurs crédités de la différence de cours
multiplié par le nombre de contrats qu’ils ont conclus.

Un intervenant qui n’a plus assez de marge sur son compte est obligé,
soit de renflouer celui-ci, soit de cloturer sa position.


**** Nettoyage des positions cloturées

La chambre de compensation détecte les positions cloturées et annule
les contrats correspondants, après avoir ajusté les marges des
intervenants, en fonction de leurs gains ou pertes respectifs.


** Les prêts - emprunts

Un contrat de prêt - emprunt est un contrat par lequel le prêteur cède
provisoirement un produit à l’emprunteur. En contrepartie, ce dernier
s’engage à restituer à l'échéance fixée le dit produit plus une
compensation financière.

Le montant de cette compensation financière est déterminée par la
valeur du produit prêté et une variable appelée taux d’intérêt :

#+BEGIN_EXAMPLE
Compensation = Taux d’intérêt × Cours du produit au début du prêt x Nombre de produits prêtés
#+END_EXAMPLE

Pour un produit donné, les contrats de prêt - emprunt de même échéance
sont standardisés, donc échangeables. Chaque échéance fait l’objet
d’une cotation séparée où le taux d’intérêt est la variable cotée du
contrat, les meilleurs ordres prêteurs étant ceux demandant le taux
d’intérêt le plus faible, et les meilleurs ordres emprunteurs étant
ceux offrant le taux d’intérêt le plus élevé.

Le produit prêté - emprunté peut-être :

  - de l’argent
  - un produit financier
  - une matière première
  - etc


* Impôts

Pour des raisons de transparence, tout objectif collectif doit se
financer sur un fond propre alimenté par l’impôt correspondant. Les
flux financiers sont alors clairement visibles.

Vient s’ajouter à ces impôts particuliers un impôt générique
alimentant un fond servant de tampon.


** Taux d’imposition

Lorsque l’impôt consiste à soustraire une fraction d’une certaine
somme S et que l’on souhaite que la contribution des fortes sommes
soit plus importante que celle des petites, on évalue le taux
d’imposition Λ par :

#+BEGIN_EXAMPLE
Λ = min { Λ_min + γ × S ; Λ_max }
#+END_EXAMPLE

où Λ_min est le taux d’imposition minimal, Λ_max le taux d’imposition
maximal et γ sa vitesse de croissance. Le calcul de l’impôt est alors
immédiat :

#+begin_example
Impôt = Λ × S = min { Λ_min + γ × S ; Λ_max } × S
#+end_example


** Répartition des impôts

  - Vôté par l’assemblée chargée de répartir les budgets


* Distribution des richesses

Soit V_min la valeur des biens du citoyen le plus démuni et V_max la
valeur des biens du citoyen le plus aisé. On exige que :

  - V_min reste supérieur au minimum Δ d’une vie digne
  - V_max / V_min reste inférieur à un rapport Γ

Si V_min passe en-dessous de Δ, ou si le rapport V_max / V_min dépasse
Γ, les citoyens les plus aisés sont mis à contribution pour renflouer
les plus démunis, jusqu'à ce que les deux critères ci-dessus soient de
nouveau remplis.

On procède comme suit : le citoyen le plus aisé est seul mis à
contribution jusqu'à ce que la valeur de ses biens devienne égale à
celle du deuxième citoyen le plus riche. Ils contribuent alors
équitablement à deux jusqu'à ce qu’ils atteignent le troisième, et
ainsi de suite.

Le rapport Γ est à fixer dans une fourchette de 10 à 100.


* Travail

Le temps de travail doit être partagé équitablement afin de laisser le
plus de loisir possible à la population, qui a a lors le temps
d’accomplir des tâches plus enrichissantes.


* Divers


** Titres

Attention de ne pas confondre :

  - les dépôts, que l’on peut voir comme des prêts à échéance
    indéterminée laissée au gré du prêteur
  - les rentes, ou obligations perpétuelles qui ne comportent pas
    d'échéance.
  - les prêts classiques qui sont à échéance fixe


** Brevets

Licence d’utilisation rémunérée par une partie des recettes que les
produits qui en découlent génèrent au sein de toutes les sociétés
commerciales qui l’utilisent, et cela pendant une durée bien
déterminée.

L’auteur du brevet n’a pas le droit de privilégier une société
commerciale par rapport à une autre.
