
#+STARTUP: showall

#+TITLE: Eclats de vers : Grimoires
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+TAGS: noexport(n)

* Synthèse

  1. [[file:synthese-01-art-chipel.org][L’art chipel]] : le caractére multiple et omniprésent de l’art


* Bien-être

Avertissement : les informations contenues dans cette section ne
constituent *en rien* des avis ou conseils médicaux : elles sont
seulement le fruit de ce que j’ai pu glaner sur internet. Aussi, je
vous recommande vivement de faire preuve de prudence, de vérifier et
d’approfondir vos connaissances avant toute application. Veillez
également à ne pas dépasser vos limites, en fonction de votre état de
forme.

  1. [[file:bienetre-01-enpratique.org][En pratique]]

  2. [[file:bienetre-02-physiologie.org][Physiologie]]

  3. [[file:bienetre-03-sport.org][Sport]]

  4. [[file:bienetre-04-yoga.org][Yoga]]

  5. [[file:bienetre-05-qigong.org][Qi Gong]]

  6. [[file:bienetre-06-vision.org][Vision]]


* Nature

  1. [[file:nature-01-permaculture.org][Permaculture]]

  2. [[file:nature-02-ecoconstruction.org][Écoconstruction]]

  3. [[file:nature-03-camper.org][Camper]]


* Métaphysique

  1. [[file:meta-01-metaphysics.org][Métaphysique]]

  2. [[file:meta-02-tradition.org][Tradition]]

  3. [[file:meta-03-esoterisme.org][Ésotérisme]]

  4. [[file:meta-04-spiritus.org][Spiritualité]]

  5. [[file:meta-05-bibliotheque.org][Bibliothèque]]


* Musique

La suite de documentation musicale de ce site se compose comme suit :

  1. Le [[file:musica-01-monocorde.org][monocorde]] définit les notes et les intervalles, les gammes,
     les modes et les durées.

  2. Le [[file:musica-02-metronome.org][métronome]] discute du rythme.

  3. Le [[file:musica-03-luth.org][luth]] entame l’exploration du monde merveilleux de la polyphonie.

  4. Le [[file:musica-04-clavier.org][clavier]] parcourt les éléments polyphoniques avancés.

  5. La [[file:musica-05-tablature.org][tablature]] développe la tonalité.

  6. La [[file:musica-06-partition.org][partition]] passe en revue les accord classés et étudie la
     dynamique musicale.

  7. Le [[file:musica-07-concert.org][concert]] enchaîne avec les cadences tonales et la modulation.

  8. La [[file:musica-08-clechant.org][clé des chants]] élabore des architectures de motifs mélodiques.
     Il examine ensuite la pratique du chant et de la poésie chantée.

  9. La [[file:musica-09-chamuse.org][chambre des muses]] rassemble quelques réflexions sur la
     composition, le contrepoint, le jazz et l’instrumentation.

  10. La [[file:musica-10-coda.org][coda]] contient un bref aperçu de l’histoire musicale. Les
      annexes concluent l’ouvrage.

# Idées de titres
#
# Feuilles notes
# Mélharmodie
# Polyson


* Littérature

La suite de documentation littéraire de ce site se compose comme suit :

  1. Les [[file:litera-01-rimailleur.org][rimes d’ailleurs]] rassemblent tout ce qui concerne la poésie et
    l’art de la versification.

  2. Le [[file:litera-02-styleau.org][style-eau]] regroupe les figures de styles, outils indispensables
    à la construction de toute poésie, qu’elle soit en vers ou en
    prose.

  3. Le [[file:litera-03-theatre.org][thé-âtre]] discute des astuces permettant de construire une histoire.

  4. Le [[file:litera-04-plumier.org][plumier]] propose un classement de mots par thèmes.

  5. Le bibliothèque de [[file:litera-05-babel.org][babel]] propose quelques traductions depuis des
     langues anciennes et modernes

# Idées de titres
#
# Encre-lierre


* Danse

  1. [[file:danse-01-quadrille.org][Danse]]


* Graphisme

  1. [[file:pictura-01-geometrie.org][Géométrie]]

  2. Dessin à la [[file:pictura-02-regle-compas.org][règle et au compas]] : technique de base, mandalas,
     polygones réguliers et les étoiles associées, plus quelques
     classiques comme le Sri Yantra.

  3. [[file:pictura-03-croquis.org][Croquis]] : comment dessiner à main levée


* Noeuds

Avertissement :

  - aucune garantie n’est fournie concernant la solidité, la sécurité
    ou l’exactitude des noeuds présentés dans cet ouvrage
  - les noeuds ne sont pas anodins, certains peuvent présenter des
    risques en cas de mauvaise utilisation

Cette série de tomes sur les noeuds a été rédigé dans le double but :

  - de comprendre les principes géométriques qui sous-tendent la
    formation et la structure des noeuds
  - d’avoir sous la main une synthèse de noeuds disponibles pour de
    petites applications domestiques

Les applications que j’ai pu en faire n’ont donc été testée qu’à
faible charge, et jamais dans des conditions professionnelles.

  1. [[file:noeuds-01-definitions.org][Définitions]]
  2. [[file:noeuds-02-operations.org][Opérations]]
  3. [[file:noeuds-03-base.org][Noeuds de base]]
  4. [[file:noeuds-04-boucle.org][Noeuds de boucle]]
  5. [[file:noeuds-05-ajut.org][Noeuds d’ajut]] : attaches de deux extrémités de corde
  6. [[file:noeuds-06-arret.org][Noeuds d’arrêt]] : empêcher que la corde ne passe à travers une ouverture
  7. [[file:noeuds-07-raccourcir.org][Noeuds pour raccourcir]] une corde
  8. [[file:noeuds-08-rangement.org][Noeuds de rangement]]
  9. [[file:noeuds-09-accroche.org][Noeuds d’accroche]] : attacher la corde à un objet
  10. [[file:noeuds-10-maintien.org][Noeuds de maintien]] : tenir des éléments ensembles, serrer un colis
  11. [[file:noeuds-11-transport.org][Transport d’objet]]
  12. [[file:noeuds-12-levier.org][Systèmes de levier]]
  13. [[file:noeuds-13-ornement.org][Noeuds ornementaux]]
  14. [[file:noeuds-14-divers.org][Divers]]


* Artisanat

  1. [[file:artisanat-02-origamis.org][Origamis]]


* Agora

  1. [[file:agora-01-constitution.org][Constitution]]

  2. [[file:agora-02-economie.org][Économie]]

  3. [[file:agora-03-education.org][Éducation]]


* Mathématiques

Les tomes sont disponibles en format monolithique, ou scindés en
plusieurs parties, plus légères pour le chargement de MathJax.

  1. [[file:matemat-01-introduction.org][Introduction]]

  2. [[file:matemat-02-ensemble.org][Ensembles]]

     1) [[file:matemat-02-ensemble-1.org][Ensembles - 1]]

     2) [[file:matemat-02-ensemble-2.org][Ensembles - 2]]

     3) [[file:matemat-02-ensemble-3.org][Ensembles - 3]]

     4) [[file:matemat-02-ensemble-4.org][Ensembles - 4]]

     5) [[file:matemat-02-ensemble-5.org][Ensembles - 5]]

  3. [[file:matemat-03-nombre.org][Nombres]]

     1) [[file:matemat-03-nombre-1.org][Nombres - 1]]

     2) [[file:matemat-03-nombre-2.org][Nombres - 2]]

     3) [[file:matemat-03-nombre-3.org][Nombres - 3]]

     4) [[file:matemat-03-nombre-4.org][Nombres - 4]]

  4. [[file:matemat-04-suite.org][Suites]]

     1) [[file:matemat-04-suite-1.org][Suites - 1]]

     2) [[file:matemat-04-suite-2.org][Suites - 2]]

     3) [[file:matemat-04-suite-3.org][Suites - 3]]

     4) [[file:matemat-04-suite-4.org][Suites - 4]]

     5) [[file:matemat-04-suite-5.org][Suites - 5]]

     6) [[file:matemat-04-suite-6.org][Suites - 6]]

  5. [[file:matemat-05-nombre-compose.org][Nombres composés]]

     1) [[file:matemat-05-nombre-compose-1.org][Nombres composés - 1]]

     2) [[file:matemat-05-nombre-compose-2.org][Nombres composés - 2]]

  6. [[file:matemat-06-vecteur.org][Vecteurs]]

     1) [[file:matemat-06-vecteur-1.org][Vecteurs - 1]]

     2) [[file:matemat-06-vecteur-2.org][Vecteurs - 2]]

     3) [[file:matemat-06-vecteur-3.org][Vecteurs - 3]]

     4) [[file:matemat-06-vecteur-4.org][Vecteurs - 4]]

     5) [[file:matemat-06-vecteur-5.org][Vecteurs - 5]]

     6) [[file:matemat-06-vecteur-6.org][Vecteurs - 6]]

     7) [[file:matemat-06-vecteur-7.org][Vecteurs - 7]]

     8) [[file:matemat-06-vecteur-8.org][Vecteurs - 8]]

  7. [[file:matemat-07-integrale.org][Intégrales]]

     1) [[file:matemat-07-integrales-1.org][Intégrales - 1]]

     2) [[file:matemat-07-integrales-2.org][Intégrales - 2]]

     3) [[file:matemat-07-integrales-3.org][Intégrales - 3]]

     4) [[file:matemat-07-integrales-4.org][Intégrales - 4]]

     5) [[file:matemat-07-integrales-5.org][Intégrales - 5]]

  8. [[file:matemat-08-differentielles.org][Différentielles]]

     1) [[file:matemat-08-differentielles-1.org][Différentielles - 1]]

     2) [[file:matemat-08-differentielles-2.org][Différentielles - 2]]

  9. [[file:matemat-09-analyse.org][Analyse]]

     1) [[file:matemat-09-analyse-1.org][Analyse - 1]]

     2) [[file:matemat-09-analyse-2.org][Analyse - 2]]

     3) [[file:matemat-09-analyse-3.org][Analyse - 3]]

     4) [[file:matemat-09-analyse-4.org][Analyse - 4]]

  10. [[file:matemat-10-optimisation.org][Optimisation]]

      1) [[file:matemat-10-optimisation-1.org][Optimisation - 1]]

      2) [[file:matemat-10-optimisation-2.org][Optimisation - 2]]

      3) [[file:matemat-10-optimisation-3.org][Optimisation - 3]]

      4) [[file:matemat-10-optimisation-4.org][Optimisation - 4]]

      5) [[file:matemat-10-optimisation-5.org][Optimisation - 5]]

      6) [[file:matemat-10-optimisation-6.org][Optimisation - 6]]

      7) [[file:matemat-10-optimisation-7.org][Optimisation - 7]]

      8) [[file:matemat-10-optimisation-8.org][Optimisation - 8]]

      9) [[file:matemat-10-optimisation-9.org][Optimisation - 9]]

  11. [[file:matemat-11-equadiff.org][Équations différentielles]]

      1) [[file:matemat-11-equadiff-1.org][Équations différentielles - 1]]

      2) [[file:matemat-11-equadiff-2.org][Équations différentielles - 2]]

      3) [[file:matemat-11-equadiff-3.org][Équations différentielles - 3]]

      4) [[file:matemat-11-equadiff-4.org][Équations différentielles - 4]]

  12. [[file:matemat-12-analyse-complexe.org][Analyse complexe]]

      1) [[file:matemat-12-analyse-complexe-1.org][Analyse complexe - 1]]

      2) [[file:matemat-12-analyse-complexe-2.org][Analyse complexe - 2]]

  13. [[file:matemat-13-probabilite.org][Probabilité]]

      1) [[file:matemat-13-probabilite-1.org][Probabilité - 1]]

      2) [[file:matemat-13-probabilite-2.org][Probabilité - 2]]


* Physique

  1. [[file:physics-01-mecanic.org][Mécanique]]


* Cosmos

  1. [[file:cosmos-01-terre.org][Terre]]


* Informatique

  1. [[file:ordina-01-multics.org][Multics]]

  2. [[file:ordina-02-bsd.org][BSD]]

  3. [[file:ordina-03-linux.org][Linux]]

  4. [[file:ordina-04-shell.org][Shell]]

  5. [[file:ordina-05-edition.org][Édition]]

  6. [[file:ordina-06-utils.org][Utilitaires]]

  7. [[file:ordina-07-script.org][Langages de script]]

  8. [[file:ordina-08-version.org][Contrôle de version]]


* Divers

  1. [[file:divers-01-unite.org][Unités]] de poids et mesures


* Références

  1. [[file:referen-01-signets.org][Signets]]

  2. [[file:referen-02-livres.org][Livres]]
