
#+STARTUP: showall

#+TITLE: Eclats de vers : Grimoires
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:../index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+TAGS: noexport(n)

* Synthèse

  1. [[file:synthese-01-art-chipel.org][L’art chipel]] : le caractére multiple et omniprésent de l’art
  2. [[file:synthese-02-annexes.org][Synthèse des annexes]]

* Bien-être

Avertissement : les informations contenues dans cette section ne
constituent *en rien* des avis ou conseils médicaux : elles sont
seulement le fruit de ce que j’ai pu glaner sur internet. Aussi, je
vous recommande vivement de faire preuve de prudence, de vérifier et
d’approfondir vos connaissances avant toute application. Veillez
également à ne pas dépasser vos limites, en fonction de votre état de
forme.

  1. [[file:bienetre-01-enpratique.org][En pratique]]
  2. [[file:bienetre-02-physiologie.org][Physiologie]]
  3. [[file:bienetre-03-sport.org][Sport]]
  4. [[file:bienetre-04-yoga.org][Yoga]]
  5. [[file:bienetre-05-qigong.org][Qi Gong]]
  6. [[file:bienetre-06-vision.org][Vision]]


* Nature

  1. [[file:nature-01-permaculture.org][Permaculture]]
  2. [[file:nature-02-ecoconstruction.org][Écoconstruction]]
  3. [[file:nature-03-camper.org][Camper]]


* Métaphysique

  1. [[file:meta-01-metaphysics.org][Métaphysique]]
  2. [[file:meta-02-tradition.org][Tradition]]
  3. [[file:meta-03-esoterisme.org][Ésotérisme]]
  4. [[file:meta-04-spiritus.org][Spiritualité]]
  5. [[file:meta-05-bibliotheque.org][Bibliothèque]]


* Musique

La suite de documentation musicale de ce site se compose comme suit :

  1. Le [[file:musica-01-monocorde.org][monocorde]] définit les notes et les intervalles, les gammes,
     les modes, les portées et les clefs.
  2. Le [[file:musica-02-metronome.org][métronome]] discute des durées et des différentes échelles de la
     structure rythmique : temps, mesure, carrure, pulsation,
     oscillation. On y voit aussi les syncopes et l’hémiole.
  3. Le [[file:musica-03-luth.org][luth]] entame l’exploration du monde merveilleux de la
     polyphonie : mélodie, harmonie et accords.
  4. Le [[file:musica-04-clavier.org][clavier]] parcourt les éléments polyphoniques avancés : dualité
     mélodie/harmonie, grille polyphonique, mouvements, cadences
     d’intervalles et modales, ornements, etc.
  5. La [[file:musica-05-tablature.org][tablature]] introduit la notion de tonalité, puis passe ensuite
     en revue les modes et les accords classés.
  6. La [[file:musica-06-partition.org][partition]] développe les notions tonales avancées : dualité
     tonale, accords synonymes, cycle tonal et cycle plagal. On passe
     ensuite à l’étude de la dynamique musicale et aux dispositions
     des accords.
  7. le [[file:musica-07-concert.org][concert]] enchaîne avec les cadences tonales et la modulation.
  8. la [[file:musica-08-clechant.org][clé des chants]] élabore des architectures de motifs mélodiques.
     il examine ensuite la pratique du chant et de la poésie chantée.
  9. l’[[file:musica-09-academie.org][académie]] passe en revue les conseils d’écriture pour l’harmonie
     et le contrepoint, ainsi que quelques caractéristiques propres au
     jazz.
  10. la [[file:musica-10-chamuse.org][chambre des muses]] rassemble quelques réflexions sur la
      pratique de la composition et l’orchestration.
  11. la [[file:musica-11-coda.org][coda]] contient un bref aperçu de l’histoire musicale.
  12. les [[file:musica-12-annexe.org][annexes]] concluent l’ouvrage.

# idées de titres
#
# feuilles notes
# mélharmodie
# polyson


* Littérature

la suite de documentation littéraire de ce site se compose comme suit :

  1. les [[file:litera-01-rimailleur.org][rimes d’ailleurs]] rassemblent tout ce qui concerne la poésie et
    l’art de la versification.
  2. le [[file:litera-02-styleau.org][style-eau]] regroupe les figures de styles, outils indispensables
    à la construction de toute poésie, qu’elle soit en vers ou en
    prose.
  3. le [[file:litera-03-theatre.org][thé-âtre]] discute des astuces permettant de construire une histoire.
  4. les [[file:litera-04-annexe.org][annexes]] récapitulent les points essentiels.
  5. le [[file:litera-05-plumier.org][plumier]] propose un classement de mots par thèmes.
  6. le bibliothèque de [[file:litera-06-babel.org][babel]] propose quelques traductions depuis des
     langues anciennes et modernes

# idées de titres
#
# encre-lierre


* Danse

  1. [[file:danse-01-quadrille.org][danse]]


* Graphisme

  1. [[file:pictura-01-geometrie.org][géométrie]]
  2. dessin à la [[file:pictura-02-regle-compas.org][règle et au compas]] : technique de base, mandalas,
     polygones réguliers et les étoiles associées, plus quelques
     classiques comme le sri yantra.
  3. [[file:pictura-03-croquis.org][croquis]] : comment dessiner à main levée


* Noeuds

avertissement :

  - aucune garantie n’est fournie concernant la solidité, la sécurité
    ou l’exactitude des noeuds présentés dans cet ouvrage
  - les noeuds ne sont pas anodins, certains peuvent présenter des
    risques en cas de mauvaise utilisation

cette série de tomes sur les noeuds a été rédigé dans le double but :

  - de comprendre les principes géométriques qui sous-tendent la
    formation et la structure des noeuds
  - d’avoir sous la main une synthèse de noeuds disponibles pour de
    petites applications domestiques

les applications que j’ai pu en faire n’ont donc été testée qu’à
faible charge, et jamais dans des conditions professionnelles.

  1. [[file:noeuds-01-definitions.org][définitions]]
  2. [[file:noeuds-02-operations.org][opérations]]
  3. [[file:noeuds-03-base.org][noeuds de base]]
  4. [[file:noeuds-04-boucle.org][noeuds de boucle]]
  5. [[file:noeuds-05-ajut.org][noeuds d’ajut]] : attaches de deux extrémités de corde
  6. [[file:noeuds-06-arret.org][noeuds d’arrêt]] : empêcher que la corde ne passe à travers une ouverture
  7. [[file:noeuds-07-raccourcir.org][noeuds pour raccourcir]] une corde
  8. [[file:noeuds-08-rangement.org][noeuds de rangement]]
  9. [[file:noeuds-09-accroche.org][noeuds d’accroche]] : attacher la corde à un objet
  10. [[file:noeuds-10-maintien.org][noeuds de maintien]] : tenir des éléments ensembles, serrer un colis
  11. [[file:noeuds-11-transport.org][transport d’objet]]
  12. [[file:noeuds-12-montage.org][montages]] : système de levier, ajusteurs de tension, etc.
  13. [[file:noeuds-13-ornement.org][noeuds ornementaux]]
  14. [[file:noeuds-14-divers.org][divers]]


* Artisanat

  1. [[file:artisanat-01-origamis.org][origamis]]


* Mathématiques

Pour le fichier pdf complet, [[../document/matemat.pdf][c’est ici]].

le livre de mathématiques est si volumineux que je lui ai consacré un
autre site, voir un de ces liens :

  - [[https://orduval.gitlab.io/equa6on/][equa6on]]

les tomes sont disponibles en format monolithique, ou scindés en
plusieurs parties, plus légères pour le chargement de mathjax.

  1. [[file:matemat-01-introduction.org][introduction]]
  2. [[file:matemat-02-ensemble.org][ensembles]]
     1) [[file:matemat-02-ensemble-1.org][ensembles - 1]]
     2) [[file:matemat-02-ensemble-2.org][ensembles - 2]]
     3) [[file:matemat-02-ensemble-3.org][ensembles - 3]]
     4) [[file:matemat-02-ensemble-4.org][ensembles - 4]]
     5) [[file:matemat-02-ensemble-5.org][ensembles - 5]]
  3. [[file:matemat-03-nombre.org][nombres]]
     1) [[file:matemat-03-nombre-1.org][nombres - 1]]
     2) [[file:matemat-03-nombre-2.org][nombres - 2]]
     3) [[file:matemat-03-nombre-3.org][nombres - 3]]
     4) [[file:matemat-03-nombre-4.org][nombres - 4]]
  4. [[file:matemat-04-suite.org][suites]]
     1) [[file:matemat-04-suite-1.org][suites - 1]]
     2) [[file:matemat-04-suite-2.org][suites - 2]]
     3) [[file:matemat-04-suite-3.org][suites - 3]]
     4) [[file:matemat-04-suite-4.org][suites - 4]]
     5) [[file:matemat-04-suite-5.org][suites - 5]]
     6) [[file:matemat-04-suite-6.org][suites - 6]]
  5. [[file:matemat-05-nombre-compose.org][nombres composés]]
     1) [[file:matemat-05-nombre-compose-1.org][nombres composés - 1]]
     2) [[file:matemat-05-nombre-compose-2.org][nombres composés - 2]]
  6. [[file:matemat-06-vecteur.org][vecteurs]]
     1) [[file:matemat-06-vecteur-1.org][vecteurs - 1]]
     2) [[file:matemat-06-vecteur-2.org][vecteurs - 2]]
     3) [[file:matemat-06-vecteur-3.org][vecteurs - 3]]
     4) [[file:matemat-06-vecteur-4.org][vecteurs - 4]]
     5) [[file:matemat-06-vecteur-5.org][vecteurs - 5]]
     6) [[file:matemat-06-vecteur-6.org][vecteurs - 6]]
     7) [[file:matemat-06-vecteur-7.org][vecteurs - 7]]
     8) [[file:matemat-06-vecteur-8.org][vecteurs - 8]]
  7. [[file:matemat-07-integrale.org][intégrales]]
     1) [[file:matemat-07-integrales-1.org][intégrales - 1]]
     2) [[file:matemat-07-integrales-2.org][intégrales - 2]]
     3) [[file:matemat-07-integrales-3.org][intégrales - 3]]
     4) [[file:matemat-07-integrales-4.org][intégrales - 4]]
     5) [[file:matemat-07-integrales-5.org][intégrales - 5]]
  8. [[file:matemat-08-differentielles.org][différentielles]]
     1) [[file:matemat-08-differentielles-1.org][différentielles - 1]]
     2) [[file:matemat-08-differentielles-2.org][différentielles - 2]]
  9. [[file:matemat-09-analyse.org][analyse]]
     1) [[file:matemat-09-analyse-1.org][analyse - 1]]
     2) [[file:matemat-09-analyse-2.org][analyse - 2]]
     3) [[file:matemat-09-analyse-3.org][analyse - 3]]
     4) [[file:matemat-09-analyse-4.org][analyse - 4]]
  10. [[file:matemat-10-optimisation.org][optimisation]]
      1) [[file:matemat-10-optimisation-1.org][optimisation - 1]]
      2) [[file:matemat-10-optimisation-2.org][optimisation - 2]]
      3) [[file:matemat-10-optimisation-3.org][optimisation - 3]]
      4) [[file:matemat-10-optimisation-4.org][optimisation - 4]]
      5) [[file:matemat-10-optimisation-5.org][optimisation - 5]]
      6) [[file:matemat-10-optimisation-6.org][optimisation - 6]]
      7) [[file:matemat-10-optimisation-7.org][optimisation - 7]]
      8) [[file:matemat-10-optimisation-8.org][optimisation - 8]]
      9) [[file:matemat-10-optimisation-9.org][optimisation - 9]]
  11. [[file:matemat-11-equadiff.org][équations différentielles]]
      1) [[file:matemat-11-equadiff-1.org][équations différentielles - 1]]
      2) [[file:matemat-11-equadiff-2.org][équations différentielles - 2]]
      3) [[file:matemat-11-equadiff-3.org][équations différentielles - 3]]
      4) [[file:matemat-11-equadiff-4.org][équations différentielles - 4]]
  12. [[file:matemat-12-analyse-complexe.org][analyse complexe]]
      1) [[file:matemat-12-analyse-complexe-1.org][analyse complexe - 1]]
      2) [[file:matemat-12-analyse-complexe-2.org][analyse complexe - 2]]
  13. [[file:matemat-13-probabilite.org][probabilité]]
      1) [[file:matemat-13-probabilite-1.org][probabilité - 1]]
      2) [[file:matemat-13-probabilite-2.org][probabilité - 2]]


* Physique

  1. [[file:physics-01-mecanic.org][mécanique]]


* Cosmos

  1. [[file:cosmos-01-terre.org][terre]]


* Informatique

  1. [[file:ordina-01-multics.org][multics]]
  2. [[file:ordina-02-bsd.org][bsd]]
  3. [[file:ordina-03-linux.org][linux]]
  4. [[file:ordina-04-shell.org][shell]]
  5. [[file:ordina-05-edition.org][édition]]
  6. [[file:ordina-06-utils.org][utilitaires]]
  7. [[file:ordina-07-script.org][langages de script]]
  8. [[file:ordina-08-version.org][contrôle de version]]


* Agora

  1. [[file:agora-01-constitution.org][constitution]]
  2. [[file:agora-02-economie.org][économie]]
  3. [[file:agora-03-education.org][éducation]]


* Divers

  1. [[file:divers-01-unite.org][unités]] de poids et mesures

* Références

  1. [[file:referen-01-signets.org][Signets]]
  2. [[file:referen-02-livres.org][Livres]]
