#+STARTUP: showall

#+TITLE: Eclats de vers : Litéra 02 : Style-eau
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Pré en bulles

#+TOC: headlines 1 local

** Introduction

#+ATTR_HTML: :class lettrine
Rhétorique, figures, ronds de jambes et petits pas de danse, fort
bien ! Mais où se situe le naturel dans ces détours de la langue, me
direz-vous ? Je vous répondrai ceci : nombreux sont les auteurs qui,
tout en étant persuadé de nager dans la spontanéité la plus pure,
utilisent inconsciemment les techniques de ce que l’on appelle
communément le /style/. Que ce soit dû à un don naturel ou à l’analyse
inconsciente de leurs lectures, il n’en reste pas moins qu’ils se
servent généreusement dans cette fort pratique boîte à outils.
Ajoutons à celà qu’il est peu probable qu’aucun puisse maîtriser sans
les apprendre toutes les astuces connues, et vous comprendrez
l’intérêt de ce recensement.

Cet ouvrage traite donc des procédés, placés ici sous le terme
générique de /figure de style/, permettant de donner du caractère à un
texte. Leur classification ne fut pas chose aisée, les propriétés en
étant fort dispersées. J’ai finalement décidé de procéder par
analogie, l’ensemble devenant un de ces édifices de grande ampleur,
une de ces merveilles à la symbolique forte qui n’a pu être réalisée
que grâce à l’accumulation du savoir-faire au cours des siècles. Nous
commencerons par tracer le [[*Plan][plan]] des figures de pensée et du langage
imagé. Viendra ensuite une classification des [[*Transformations][transformations]]
permettant de créer des variations d’un texte original, aussitôt
suivie des [[*Constructions][constructions]], figures où intervient une forme quelconque
de répétition, simple ou dérivée. Le [[*Carillon][carillon]] dévoilera des techniques
associées au phrasé musical, puis l’[[*Architecture][architecture]] présentera des
figures plus vastes ou plus complexes. Enfin, le [[*Temple][temple]] concluera cet
ouvrage en recensant quelques méthodes encore plus larges, liées à
l’argumentation.

Mon espoir est qu’avec tout cet arsenal, vous pourrez inventer vous
même les formes poétiques qui s’accorderont le mieux à votre âme au
moment où l’inspiration, qu’elle soit petite ténue ou grande tétue,
viendra frapper à votre porte. Dans une chanson réussie, la musique à
un sens propre en plus de celui des paroles, et un poème est avant
tout une mélodie de toute beauté, qui suggère plutôt que d’imposer.

** Avertissement

La nomenclature utilisée dans ce document est fort éloignée du
vocabulaire habituel propre aux figures de style ou de rhétorique, et
la raison en est triple. Tout d’abord pédagogique, car si on peut
admettre une certaine force poétique dans la bizarrerie d’une famille
où se cotoient anaphore, épanalepse, oxymore et autre adynaton, il me
semble naturellement plus adapté à un bestiaire chimérique qu’à la
limpidité d’un exposé. Ensuite, j’ai pu constater en lisant deux
ouvrages sur le sujet, l’un orienté vers le style et l’autre vers la
rhétorique, qu’il n’existe pas de convention universelle en ce
domaine : si certains termes possèdent un sens bien établi, de
nombreux autres admettent plusieurs définitions. Enfin, j’ai pu
observer au fil de mes lectures poétiques ou découvrir par moi-même
des figures qui ne semblent pas recensées. J’ai donc choisi d’adopter
une nomenclature innovante, même si certains mots comme la métaphore
sont repris du vocabulaire traditionnel, tout en ayant parfois un sens
nuancé. Toutefois, lorsqu’un lien clair avec la nomenclature
traditionnelle existe, celle-ci est précisée à titre indicatif au
début de la section correspondante.

** Notations

On symbolise les blocs de texte par des lettres majuscules :

#+BEGIN_CENTER
A, B, C, ..., Z
#+END_CENTER

Les tirets « — » entre les groupes de lettres désignent des
séparations logiques, conceptuelles, de ponctuation, de strophes, du
texte ou autre. Considérons par exemple ce quatrain :

#+BEGIN_CENTER
#+BEGIN_VERSE
Sur quoi repose une vie
Qu’un peu de cendre et de pluie
Qu’un peu de cendre emportée
Dans la tempête en furie
#+END_VERSE
#+END_CENTER

Afin de mettre en évidence l’architecture du texte, nous symbolisons
par des lettres majuscules les blocs concernés :

#+ATTR_HTML: :class plat
| A | = | Qu’un peu de cendre |
| B | = | et de pluie         |
| C | = | emportée            |

ce qui nous permet d’annoter la strophe :

#+BEGIN_CENTER
Sur quoi repose une vie
[ Qu’un peu de cendre ] (A) [ et de pluie ] (B)
[ Qu’un peu de cendre ] (A) [ emportée ] (C)
Dans la tempête en furie
#+END_CENTER

Nous pouvons alors en schématiser la structure par :

#+ATTR_HTML: :class plat
| =..........= |
| AB           |
| AC           |
| =..........= |

La structure interne peut donc s’écrire :

#+BEGIN_CENTER
AB — AC
#+END_CENTER

* Plan

#+TOC: headlines 1 local

** Échelle

Les figures de style peuvent se construire à n’importe quelle échelle
textuelle ou poétique : on peut par exemple utiliser des mots pour
modifier l’intérieur des syntagmes ou des hémistiches pour ajuster les
strophes. Le tableau ci-dessous recense les cas les plus courants :

- discours
  + lettre
  + syllabe
  + mot
  + syntagme
  + locution
  + proposition
  + phrasé
  + paragraphe
- poésie
  + voyelle
  + consonne
  + syllabe
  + rime
  + coupe
  + césure
  + hémistiche
  + vers
  + strophe

Notons que la poésie versifiée n’exclut pas les échelles discursives,
bien au contraire : la combinaison des échelles discursives et
poétiques ainsi que les décalages qui peuvent en résulter constituent
l’un de ses atouts majeurs.

** Implicite

/Nomenclature traditionnelle : ellipse, brachylogie/

Dans toute figure de style, chaque idée ou bloc de texte peut être
effectivement présent, et on dit alors qu’il est explicite, ou bien
seulement sous-entendu, et on dit qu’il est implicite. Dans ce dernier
cas, c’est le plus souvent le coté insolite ou la variation par
rapport à la structure usuelle qui indique la présence de la figure.

*** Indices

Lorsqu’une idée est sous-entendue, il est possible de glisser un
indice permettant d’orienter le lecteur vers le sens implicite.

*** Contexte

Lorsqu’aucun indice n’est glissé, c’est au contexte de nous
renseigner. Par exemple, dans un contexte élogieux, l’exclamation :

#+BEGIN_CENTER
Merveilleux !
#+END_CENTER

ne signifie rien d’autre que son sens propre. Il en va tout autrement
dans un contexte de défaitisme, où la même exclamation est perçue
comme ironique, ce qui a pour effet d’accentuer le pessimisme ambiant.

** Images

Il s’agit de rapprocher deux idées *A* et *B* (choses, êtres, actions,
abstractions, ...), voire d’identifier l’une à l’autre, afin de faire
correspondre leurs caractéristiques (constituant, partie, action,
comportement, ...).

Par exemple, si on rapproche l’idée /d’arbre/ à celle de /navire/, les
/racines/ pourront être représentées par /l’ancre/, ou inversément. De
même, l’action de /libérer les voiles/ pour gagner de la vitesse
pourra être interchangeable avec la /pousse des feuilles/ au
printemps.

*** Cristal

Il s’agit d’une idée centrale *A* rapprochée de plusieurs idées *B*,
*C*, =...=, de sorte que chaque caractéristique, chaque facette de *A*
est associée à une idée différente.

On peut par exemple décrire un personnage en disant qu’il a la souplesse d’un félin
et les yeux d’un serpent, ou dépeindre une plage comme étant la demeure du vent et
l’orée de l’océan.

** Combinaisons

/Nomenclature traditionnelle : alliance/

La combinaison rassemble deux ou plusieurs idées quelconques en
utilisant une construction grammaticale pour assurer la cohérence de
l’ensemble. Le tableau ci-dessous donne des exemples des formes les
plus courantes de ces structures.

| Type  | +           | Type              | Exemple                      |
|-------+-------------+-------------------+------------------------------|
| nom   | +           | apposition        | Renard, oiseau de ruse, ...  |
|       |             | adjectif          | Un ciel empoisonné           |
|       |             | génitif           | Les soupirs du printemps     |
|       |             | consistance       | Son sourire est en or        |
|       |             |                   | Une larme de sel             |
|       |             | verbe             | La brume transpire           |
| verbe | +           | adverbe           | Il ruse paresseusement       |
|       |             | infinitif         | Il joue à perdre haleine     |
|       |             | complément direct | Suer des oasis               |
|       |             | complément        | Il pleure jusqu’au sel       |
|       | coordonnée  |                   | Ni renard ni calife          |
|       |             |                   | Frénétiques et glacés        |
|       | subordonnée |                   | Cette brise qui nous parfume |
|       | relative    |                   | Le printemps qui soupire     |

** Croisements

Le croisement est une combinaison qui joue sur deux plans :

  - la phonétique
  - les idées

Chacun de ces deux sens peut être explicité ou rester implicite. Par
exemple, les mots :

#+BEGIN_CENTER
arbre + buste
#+END_CENTER

font penser phonétiquement à un arbuste. Le sens imagé pourrait être
le buste de l’arbre, ce qui donne un style fantastique à la
description tout en suggérant la partie supérieure du tronc ou le
feuillage.

** Connexions

/Nomenclature traditionnelle : métonymie, synecdote/

Il s’agit de voyager d’un concept à l’autre en utilisant des
associations d’idées, une phonétique similaire ou des déclinaisons
grammaticales. Par exemple, on peut partir du concept de /nuage/ et
arriver à l’idée de /pluie/. Le tableau ci-dessous reprend les schémas
de pensée les plus courants.

| Connexion            |                 | Exemple  |              |
|----------------------+-----------------+----------+--------------|
| phonétique semblable |                 | oseille  | oreille      |
| déclinaisons         |                 | amour    | aime         |
|                      |                 | rouge    | rougeur      |
| thème commun         |                 | comète   | astronef     |
| famille commune      |                 | chouette | goéland      |
| juxtaposés           |                 | papillon | fleur        |
| opposés              |                 | feu      | glace        |
| générique            | spécifique      | oiseau   | cygne        |
| cause                | effet           | soleil   | jour         |
| engendrant           | engendré        | poule    | oeuf         |
| tout                 | partie          | chat     | patte        |
| contenant            | contenu         | carafe   | vin          |
| idée                 | caractéristique | verre    | transparence |
|                      | action          | chat     | miauler      |
|                      | constituant     | perle    | nacre        |
| les sens             |                 | voir     |              |
|                      |                 | écouter  |              |
|                      |                 | sentir   |              |
|                      |                 | gôuter   |              |
|                      |                 | toucher  |              |

Par souci de concision, tous les exemples ci-dessus sont de simples
mots, mais il en va de même avec tout autre échelle littéraire. Par
exemple, on peut utiliser un lien de causalité pour associer la
conséquence :

#+BEGIN_CENTER
Le verre s’est brisé.
#+END_CENTER

à un des éléments de la cause :

#+BEGIN_CENTER
Le verre est si fragile.
#+END_CENTER

*** Déclinaisons

Les principaux paramètres que l’on peut faire varier pour une
déclinaison sont, pour les noms et adjectifs :

  - le genre
  - le nombre

et pour les verbes :

  - le temps
  - la personne
  - actif / passif
  - affirmatif / négatif

Il existe bien entendu d’autres cas de déclinaisons, comme la
transformation d’un adjectif en nom ou en adverbe par exemple.

*** Indirecte

Lorsqu’on combine plusieurs associations simples, on obtient une
association complexe comportant plusieurs étapes. Une association
indirecte est le lien existant entre le point de départ et l’arrivée
de tout le raisonnement. Prenons par exemple la suite de connexions :

#+BEGIN_CENTER
soleil —— chaleur —— désert —— sable —— ensabler
#+END_CENTER

La phrase :

#+BEGIN_CENTER
Le soleil s’ensable.
#+END_CENTER

contient les idées initiale et finale de la construction.

** Treillis

Il s’agit d’énumérer une idée ainsi qu’une ou plusieurs de ses
connexions. Par exemple, Baudelaire cite dans cet extrait pas mal
d’idées liées aux animaux, à leurs actions et en particulier leurs
cris :

#+BEGIN_CENTER
#+BEGIN_VERSE
Mais parmi les chacals, les panthères, les lices,
Les singes, les scorpions, les vautours les serpents,
Les monstres glapissants, hurlants, grognants, rampants,
Dans la ménagerie infâme de nos vices
#+END_VERSE
#+END_CENTER

*** Grammatical

Voici un exemple de treillis grammatical, c’est-à-dire utilisant les
déclinaisons :

#+BEGIN_CENTER
#+BEGIN_VERSE
Ses /rougeurs/ en /rougirent/ de plaisir
#+END_VERSE
#+END_CENTER

** Contrastes

/Nomenclature traditionnelle : antilogie, antithèse/

Il s’agit d’un cas particulier de treillis où l’on juxtapose deux
idées contrastées ou opposées. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
La /glace/ est sur le /feu/
#+END_VERSE
#+END_CENTER

On peut également travailler à l’échelle du vers, en opposant deux
hémistiches :

#+BEGIN_CENTER
#+BEGIN_VERSE
Qui veut se croire /grand/ s’entoure de /petits/
#+END_VERSE
#+END_CENTER

*** Combinaison

/Nomenclature traditionnelle : oxymore/

L’effet est saisissant lorsque le contraste est composé de deux mots
liés par un ciment grammatical. Un exemple de Corneille :

#+BEGIN_CENTER
#+BEGIN_VERSE
Cette /obscure clarté/ qui tombe des étoiles.
#+END_VERSE
#+END_CENTER

Voici un autre exemple de construction faisant intervenir un verbe et
un complément :

#+BEGIN_CENTER
#+BEGIN_VERSE
Oui, /sondez l’insondable/ océan du sabbat
#+END_VERSE
#+END_CENTER

*** Négation — affirmation

On peut aussi construire un couple négation — affirmation.
Exemple :

#+BEGIN_CENTER
Il /ne sera jamais/ d’homme si médiocre que l’art /est/ un titan.
#+END_CENTER

Voici un autre exemple, de Valéry :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Toute/ humide des pleurs que je /n’ai point/ versés
#+END_VERSE
#+END_CENTER

On rencontre aussi des constructions basées sur des contrastes
similaires, comme :

#+ATTR_HTML: :class plat
| plus     | — | moins   |
| toujours | — | jamais  |
| début    | — | fin     |
| premier  | — | dernier |

Exemple de Rostand :

#+BEGIN_CENTER
#+BEGIN_VERSE
/D’autant plus/ éloquent que j’étais /moins/ sincère
#+END_VERSE
#+END_CENTER

*** Description

/Nomenclature traditionnelle : antéisagoge/

On décrit quelque chose en commençant par ce qu’il n’est pas et en
terminant par ce qu’il est :

#+BEGIN_CENTER
#+BEGIN_VERSE
Il n’était pas très grand, mais plus haut qu’un titan !
#+END_VERSE
#+END_CENTER

** Comparaisons

Une comparaison est un cas particulier d’image, où les deux idées,
appelées le comparé et le comparant, sont rapprochées par une
caractéristique appelée le point de comparaison. Dans cet exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Ce dessert est doux comme une brise vespérale
#+END_VERSE
#+END_CENTER

Le /dessert/ est le comparé, la /brise vespérale/ le comparant, le
caractère /doux/ le point de comparaison et le mot-lien est /comme/.
Les mots-liens les plus courants sont : /comme, tel, tel que,
aussi ... que, ainsi que/. Voici quelques exemples d’utilisation :

#+BEGIN_CENTER
#+BEGIN_VERSE
L’air est aussi frais que l’eau d’un étang
La lune se parait ainsi qu’une princesse

Tel un fol horizon, leur espoir refluait
#+END_VERSE
#+END_CENTER

*** Similitude

Lorsqu’on veut montrer une similitude entre toutes les
caractéristiques du comparé et du comparant, on utilise plutôt les
mots-liens /pareil/ ou /semblable/ :

#+BEGIN_CENTER
#+BEGIN_VERSE
Pareil aux illusions, le spectre disparut
La douceur est semblable aux brises vespérales
#+END_VERSE
#+END_CENTER

mais on peut aussi en utiliser d’autres :

#+BEGIN_CENTER
#+BEGIN_VERSE
Nous ne sommes pas tout à fait arrivés, mais c’est tout comme
Ton frère est comme sa soeur
#+END_VERSE
#+END_CENTER

** Métaphores

/Nomenclature traditionnelle : métaphore/

Une métaphore est une image, image qui peut être vue comme une
comparaison où, hormis le comparant, la plupart des éléments sont
implicites. On se sert d’indices pour guider le lecteur vers les
éléments masqués. Exemple :

#+BEGIN_CENTER
Deux brasiers le foudroyèrent du regard
#+END_CENTER

L’indice du /regard/ nous mène vers les yeux. Quel pourrait
être le point de comparaison entre ces deux idées ? Par exemple
l’aspect brillant, la /foudre/ nous suggérant la colère.
On peut donc supposer qu’il s’agit de la comparaison implicite :

#+BEGIN_CENTER
Son regard se posa sur lui, et ses deux yeux étaient aussi
brillants que deux brasiers, ce qui le foudroya
#+END_CENTER

*** Identification

Une variante particulière de métaphore est celle où le comparé est
explicitement cité, et identifié au comparant. Dans notre exemple, on
aurait :

#+BEGIN_CENTER
Ses yeux étaient deux brasiers foudroyants
#+END_CENTER

ou :

#+BEGIN_CENTER
Ses yeux, brasiers foudroyants, =...=
#+END_CENTER

*** Filée

Les métaphores filées sont des suites de métaphores où comparés et
comparants sont développés à partir de thèmes centraux. Par exemple,
si nous voulons filer la métaphore autour des yeux, nous pourrons
dire :

#+BEGIN_CENTER
Deux brasiers foudroyants étincelèrent dans la nuit endormie,
et il sentit que des flammes tourmentées par le vent l’examinaient.
#+END_CENTER

Il y a un développement de l’idée des yeux, à travers le qualificatif
/endormie/ qui suggère des yeux fermés, mais aussi à travers
l’adjectif /tourmentées/, et le verbe /examiner/, caractérisant un
regard inquiet et attentif. L’idée du /brasier/ est également
développée, à travers le verbe /étinceler/ et les /flammes/.

*** Cryptée

Il s’agit d’une métaphore où les indices sont très ténus, pour ne pas
dire inexistants. Il y a alors ambiguité, et donc multiplication des
sens possibles. Le contexte ou la suite du texte peut éventuellement
donner un ou plusieurs éclairages différents à une métaphore cryptée.

*** Analogie

Une analogie consiste à comparer deux relations, par exemple :

#+BEGIN_CENTER
La vertu en société est aussi rare que le trèfle à quatre feuilles
dans une prairie
#+END_CENTER

On peut rendre implicite le point de comparaison, ici la rareté :

#+BEGIN_CENTER
La vertu est à la société ce que le trèfle à quatre feuilles
est à la prairie
#+END_CENTER

** Sémantique

Il s’agit de jouer avec les différents sens possibles des mots, ainsi
qu’avec le nombre d’occurences d’un même texte ou d’une même idée. Une
même idée peut être exprimée identiquement ou différemment au fil des
occurences. Voyons un exemple :

#+BEGIN_CENTER
/Il paraît que/ l’important n’est plus d’être, mais /d’avoir/, et même
/d’avoir l’air/ ; /brasser de l’air/ et /de l’argent/.
#+END_CENTER

Cette phrase contient deux occurences du verbe /avoir/. Mais dans le
premier cas, il est isolé et signifie /posséder/, alors que dans le
second, il est inclus dans l’expression /avoir l’air/ qui signifie
/paraître/. Le verbe /paraître/ est d’ailleurs cité explicitement au
début du texte, mais il est inclus dans l’expression /Il paraît que/
qui signifie /On raconte que/. Dans la deuxième partie de la phrase,
une seule occurence du verbe /brasser/ prend deux significations :
/brasser de l’air/ qui signifie /s’agiter beaucoup pour masquer
l’inconsistance de ses travaux/, et /brasser de l’argent/ qui signifie
/être riche/.

Voyons à présent les figures simples que l’on peut déduire de cet
exemple.

*** Syllepse

/Nomenclature traditionnelle : syllepse (oratoire)/

Une seule occurence d’un seul bloc de texte prend plusieurs sens.
Exemple :

#+BEGIN_CENTER
Le /sel de mer/ et /du texte/
#+END_CENTER

Le /sel/ prend d’abord le sens de /sel marin/, puis ensuite celui
d’aspect /spirituel/ d’un texte.

Dans cet autre exemple :

#+BEGIN_CENTER
Il posa son bic et une question
#+END_CENTER

Le verbe /poser/ a d’abord le sens de /poser un objet/ puis de
/demander/.

*** Périphrase

/Nomenclature traditionnelle : périphrase, circonlocution/

Une périphrase consiste à exprimer une même idée différemment. Par
exemple, on peut exprimer l’idée de /pluie/ par :

#+BEGIN_CENTER
Les larmes du ciel
#+END_CENTER

La tournure initiale (ici /pluie/) reste implicite.

*** Redondance

/Nomenclature traditionnelle : pléonasme, trajection/

Il s’agit de la répétition d’une même idée exprimée différemment.
Exemple :

#+BEGIN_CENTER
La /pluie/, les /larmes du ciel/ nous rafraîchissent l’âme
#+END_CENTER

*** Résonance

/Nomenclature traditionnelle : antanaclase, diaphore, tautologie/

Chaque occurence d’un bloc de texte prend un nouveau sens. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Les jeunes /fleurs/ aiment les /fleurs/
#+END_VERSE
#+END_CENTER

La première occurence de /fleurs/ a le sens poétique de /jeune fille/,
tandis que la seconde occurence a le sens propre de /fleurs/.

/Remarque :/ notons qu’un indice a été glissé dans notre exemple :
/jeune fleur/ ressemble phonétiquement à /jeune fille/.

*** Pronom

Plutôt que de répéter le bloc tel quel, on utilise un pronom. Par
exemple, la phrase :

#+BEGIN_CENTER
/Tout le monde/, /tout le monde/ arrive !
#+END_CENTER

devient :

#+BEGIN_CENTER
/Tout le monde il/ arrive !
#+END_CENTER

De même :

#+BEGIN_CENTER
C’est /son bonbon/, /son bonbon/ !
#+END_CENTER

peut être reformulé en :

#+BEGIN_CENTER
C’est /son bonbon à lui/ !
#+END_CENTER

** Feintes

Une feinte est la combinaison d’une affirmation et d’un indice ou d’un
contexte qui nous guide vers un sens implicite différent du sens
apparent de l’affirmation.

*** Dépréciation feinte

/Nomenclature traditionnelle : autocatégorème, chleuasme/

C’est une manoeuvre qui consiste à se déprécier dans le but de
provoquer une réaction opposée de l’interlocuteur. Elle est souvent
teintée d’ironie ou d’indignation, comme dans cet exemple du Tartuffe
de Molière :

#+BEGIN_CENTER
Mais la vérité pure est que je ne vaux rien.
#+END_CENTER

*** Éloge implicite

/Nomenclature traditionnelle : astéisme, antiphrase/

Exemple :

#+BEGIN_CENTER
Je vous dois gronder, cruel, votre absence
me fut une torture, oh mais constante !
#+END_CENTER

On comprend qu’en fait la narratrice est très attachée à son
interlocuteur.

*** Grief implicite

/Nomenclature traditionnelle : ironie, antiphrase/

Exemple :

#+BEGIN_CENTER
Si tu continues à viser aussi bien, tu peux être sûr de ne jamais
atteindre la cible.
#+END_CENTER

On comprend qu’en fait la personne en question vise très mal.

*** Double négation

/Nomenclature traditionnelle : litote/

Il s’agit d’une feinte utilisant une double négation : grammaticale
(/ne/ ... /pas/) et implicite. Exemple :

#+BEGIN_CENTER
Il /ne/ fait /pas/ très chaud.
#+END_CENTER

phrase qui nous laisse entendre qu’il fait très froid.

** Condensation

Il s’agit de rendre concret, de donner une consistance à une notion
abstraite, par exemple :

#+BEGIN_CENTER
Lance tes /sentiments/ par-dessus les grillages
#+END_CENTER

** Animation

/Nomenclature traditionnelle : allégorie/

*** Hypotypose

Description très vivante, comme si on y était.

*** Personnification

On fait vivre une idée, un objet, ou un être inanimé. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Avec son front squelettique
Sa frondaison dégarnie
Privé de toute tunique
Notre /arbre/ songe aux Antilles
#+END_VERSE
#+END_CENTER

ou encore :

#+BEGIN_CENTER
Le /printemps/ nous sourit, soulevant ses jupons
#+END_CENTER

*** Prosopopée

On adresse la parole à une idée, un objet ou un être. Exemple de
Lamartine :

#+BEGIN_CENTER
Ô /temps/ suspends ton vol !
#+END_CENTER

*** Sermonication

On donne la parole à une idée, un objet ou un être. Exemple :

#+BEGIN_CENTER
Je suis la /forêt/, entends-tu ma plainte ?
#+END_CENTER

** Intensité

#+TOC: headlines 1 local

*** Emphase

Accentue l’aspect solennel.

*** Hyperbole

Exagération forte.

*** Adynaton

Hyperbole tellement exagérée qu’elle en est impossible.

*** Euphémisme

Expression atténuée pour ne pas choquer.

*** Exténuation

Propos d’aspect anodin.

** Dialogue

#+TOC: headlines 1 local

*** Apostrophe

Interpellation directe d’une personne réelle ou abstraite.

*** Interrogation oratoire

Fausse question qui n’attend pas de réponse de l’interlocuteur, mais
destinée uniquement à renforcer la suite du discours. La réponse est
donc fournie comme suite logique par la personne qui pose la question.

** Décalage temporel

#+TOC: headlines 1 local

*** Analepse

Récit d’une action antérieure au temps principal du discours.

*** Prolepse

Anticipation d’une situation, dans le futur du temps principal du récit.

Souvent utilisée pour anticiper les objections de l’interlocuteur.

* Transformations

#+TOC: headlines 1 local

** Variations

Nous regroupons sous le terme générique de variations les figures qui
consistent à modifier un bloc de texte original pour produire un bloc
dérivé qui lui ressemble. Nous notons :

#+BEGIN_CENTER
A’
#+END_CENTER

tout bloc dérivé d’un bloc original *A*. L’original et la variation
peuvent se ressembler sur différents niveaux : idée, structure,
phonétique, rythme ou sous-bloc(s) similaire(s), etc. Par exemple :

#+BEGIN_CENTER
Le silence écrasa le désert
#+END_CENTER

peut être dérivé en :

#+BEGIN_CENTER
La cadence envoûta la litière
#+END_CENTER

qui est de structure, phonétique et rythme semblables.

*** Multiples

Il arrive fréquemment qu’un bloc de texte soit sujet à plusieurs
variations. Dans ce cas, nous notons :

#+BEGIN_CENTER
A’   A’’   A’’’   =...=
#+END_CENTER

les variations successives

*** Utilisation

Les variations sont bien sûr utilisées isolément, mais elles le sont
aussi par nécessité, lors de la construction d’autres figures, qui
nécéssitent des ajustements afin de conserver la fluidité du texte.

** Déplacements

/Nomenclature traditionnelle : dislocation, hypallage/

Il s’agit de déplacer un bloc de texte pour produire un effet
d’étrangeté ou bouleverser la structure usuelle. Le tableau ci-dessous
donne des exemples des formes de déplacements les plus courants.

| Type        | Exemple                                              |                                                      |
|             | Forme implicite d’origine                            | Forme déplacée                                       |
|-------------+------------------------------------------------------+------------------------------------------------------|
| Syntagme    | L’orage /et le chien/ grondent.                      | L’orage gronde, /et le chien/                        |
| Adjectif    | La chaleur de sa robe /pourpre/ le fascinait.        | La chaleur /pourpre/ de sa robe le fascinait.        |
| Subordonnée | L’éclair /que l’orage couvait/ nous a surpris        | L’éclair nous a surpris /que l’orage couvait/        |
| Relative    | L’éclair /qui s’enfuit sans attendre/ nous a surpris | L’éclair nous a surpris /qui s’enfuit sans attendre/ |

** Ajouts

L’ajout consiste à ajouter un ou plusieurs éléments à un bloc de
texte.

** Suppressions

La suppression consiste à supprimer un ou plusieurs éléments d’un bloc
de texte.

** Développements

/Nomenclature traditionnelle : paraphrase/

Il s’agit de développer une idée afin d’en construire une forme plus ample.

*** Gradation

/Nomenclature traditionnelle : climax/

Une idée est développée progressivement, avec de plus en plus de
force. Exemple :

#+BEGIN_CENTER
Là-bas le ciel est sombre, grisâtre, sinistre, à glacer le sang.
#+END_CENTER

*** Évanescence

/Nomenclature traditionnelle : anticlimax/

Une idée est développée avec de moins en moins de force. Exemple :

#+BEGIN_CENTER
Allons, du bonheur, de la joie, de l’enthousiasme,
ne serait-ce qu’un sourire.
#+END_CENTER

*** Grammaticale

Il s’agit d’utiliser un maximum de particules grammaticales : le, les,
et, mais, etc. On allonge donc le texte en ajoutant des articulations.
Par exemple, cette phrase :

#+BEGIN_CENTER
Je sais que tu es là
#+END_CENTER

peut être développée en :

#+BEGIN_CENTER
Je le sais que tu es vraiment tout à fait là
#+END_CENTER

** Synthèses

Il s’agit de synthétiser une idée afin d’en construire une forme plus concise.

*** Raccourci

Une part du sens est omis, c’est au lecteur de le reconstituer. Un
exemple de toute beauté de Corneille :

#+BEGIN_CENTER
Je t’aimais inconstant, qu’eussé-je fait fidèle ?
#+END_CENTER

qui signifie :

#+BEGIN_CENTER
Je t’aimais alors que tu étais inconstant,
qu’eussé-je fait si tu avais été fidèle ?
#+END_CENTER

*** Grammaticale

/Nomenclature traditionnelle : asyndète, parataxe/

Il s’agit d’utiliser un minimum de particules grammaticales. On
condense donc le texte en supprimant des pronoms, articulations, etc.
Par exemple, cette phrase :

#+BEGIN_CENTER
Je sais que tu es là
#+END_CENTER

peut être synthétisée en :

#+BEGIN_CENTER
Tu es là, je le sais
#+END_CENTER

Cet extrait d’Edmond Rostand :

#+BEGIN_CENTER
Cyrano, fais ce que dois !
#+END_CENTER

omet un pronom normalement utilisé :

#+BEGIN_CENTER
Cyrano, fais ce que *tu* dois !
#+END_CENTER

** Substitutions

Il s’agit de substituer une idée ou un bloc de texte à un autre.

*** Connexions

Les connexions permettent de construire d’élégantes substitutions.

Utilisons par exemple :

#+BEGIN_CENTER
nuage —— pluie
#+END_CENTER

La phrase :

#+BEGIN_CENTER
Les /nuages/ arrivent sur nous
#+END_CENTER

peut être remplacée par :

#+BEGIN_CENTER
La /pluie/ arrive sur nous
#+END_CENTER

** Inversions

Il s’agit de permuter deux blocs de texte. L’ordre d’origine est
implicite.

*** Étrangeté

L’inversion est indiquée par un effet d’étrangeté. Ainsi, la phrase :

#+BEGIN_CENTER
Sa robe était /brodée/ et de couleur /vive/.
#+END_CENTER

devient après inversion :

#+BEGIN_CENTER
Sa robe était /vive/, et de couleur /brodée/.
#+END_CENTER

*** Ordre usuel

/Nomenclature traditionnelle : anastrophe/

L’inversion est indiquée par une modification de l’ordre usuel. Par
exemple :

#+BEGIN_CENTER
Sans /aucun désir/
#+END_CENTER

devient après inversion :

#+BEGIN_CENTER
Sans /désir aucun/
#+END_CENTER

Le tableau ci-dessus reprend quelques exemples d 'inversion :

| Forme implicite d’origine      | Forme inversée                 |
|--------------------------------+--------------------------------|
| /Encore plus/                  | /Plus encore/                  |
| /Durant sa vie/                | /Sa vie durant/                |
| Je /veux la/ voir sourire      | Je /la veux/ voir sourire      |
| Ne /pas le sentir/             | Ne /le sentir pas/             |
| Je /vais y/ songer             | J’ /y vais/ songer             |
| /La lune se fond/ dans la nuit | /Se fond la lune/ dans la nuit |
| /Voici/ qui ? /moi/            | /Me voici/                     |

*** Causalité

/Nomenclature traditionnelle : prolepse/

Il s’agit de l’inversion d’une cause et d’une conséquence. On se sert
souvent d’un adjectif indiquant la conséquence pour placer celle-ci
avant la cause. Par exemple, cette phrase :

#+BEGIN_CENTER
L’eau subit la /tempête/ qui la /trouble/
#+END_CENTER

devient après inversion :

#+BEGIN_CENTER
L’eau /troublée/ subit la /tempête/
#+END_CENTER

*** Types grammaticaux

/Nomenclature traditionnelle : implication/

Il s’agit de permuter les types grammaticaux dans un syntagme. Un
exemple courant consiste à permuter les types d’un nom et d’un
qualificatif. Par exemple, le syntagme :

#+BEGIN_CENTER
Le ciel clair
#+END_CENTER

devient après permutation :

#+BEGIN_CENTER
La clarté céleste
#+END_CENTER

ou encore :

#+BEGIN_CENTER
La clarté du ciel
#+END_CENTER

*** Rupture

L’inversion peut provoquer une rupture au niveau des articulations de
la phrase. Par exemple, /un tapis vert et bleu/ peut devenir :

#+BEGIN_CENTER
un vert tapis, et bleu
#+END_CENTER

** Fusions

Il s’agit de fusionner deux blocs de texte en les juxtaposant. On peut
être amené à les modifier afin de rendre l’ensemble plus cohérent. Par
exemple, cette phrase :

#+BEGIN_CENTER
Des /rafales/ et des /fleurs/ nous embrument.
#+END_CENTER

devient après fusion :

#+BEGIN_CENTER
Des /rafales fleuries/
nous embrument.
#+END_CENTER

** Scissions

/Nomenclature traditionnelle : hendiadyn, handiadys/

Il s’agit de scinder un bloc de texte en deux blocs non consécutifs.
On peut être amené à effectuer des modifications afin de rendre
l’ensemble plus cohérent. Par exemple, cette phrase :

#+BEGIN_CENTER
De /lourdes nuées/ s’amoncellent.
#+END_CENTER

devient après scission :

#+BEGIN_CENTER
De la /lourdeur/ et des /nuées/ s’amoncellent.
#+END_CENTER

*** Locution

/Nomenclature traditionnelle : tmèse/

Cette figure est également d’une grande force lorsqu’on scinde une
locution. Ici, Valéry scinde la locution /Quelle que soit/ :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Quelle/, et si fine et si mortelle,
/Que soit/ ta pointe, blonde abeille
#+END_VERSE
#+END_CENTER

* Constructions

#+TOC: headlines 1 local

** Répétitions

Un même bloc de texte est répété à plusieurs endroits du texte, avec
ou sans variations.

*** Refrain

/Nomenclature traditionnelle : refrain/

Un refrain est un bloc de texte répété régulièrement. En poésie, on le
retrouve souvent sous la forme de petites strophes alternant avec les
strophes ordinaires, ou d’un ou plusieurs vers situés en même position
dans chaque strophe. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Les nuées pourpres du désir
Viennent rosir le parchemin
Son coeur se gonfle d’un soupir
Le stylo languit dans sa main
Quelle strophe vive et sanguine
Ecrit-elle à l’encre carmin ?
J’entends glisser sur le vélin
/Son joli rire de coquine/

Les nuées pourpres du désir
Se sont lovées dans ses cheveux
Sa muse d’un baiser fougueux
Baillonne son charmant sourire
C’est un frôlement langoureux
Qui l’envoûte et qui la taquine
C’est le murmure des aveux
/Son joli rire de coquine/
#+END_VERSE
#+END_CENTER

*** Rafale

/Nomenclature traditionnelle : battologie, épizeuxe, palillogie, réduplication/

Il s’agit de répéter plusieurs fois de suite un même bloc de texte. La
dernière occurence peut servir d’introduction à un développement de
l’idée. On a donc la structure générique :

#+BEGIN_CENTER
=AA...A=
#+END_CENTER

Exemple :

#+BEGIN_CENTER
/Tourner, tourner/ encore et de plus en plus vite
#+END_CENTER

Autre exemple, à l’échelle de la syllabe :

#+BEGIN_CENTER
Le DÉ, ce DÉ-mon
#+END_CENTER

ou encore :

#+BEGIN_CENTER
NOUS NOUS NOU-rissions de venin
#+END_CENTER

*** Récursivité

On utilise une répétition et un ciment grammatical pour obtenir un
effet de récursivité, avec suggestion de mise en abyme. Le tableau
ci-dessous donne des exemples des formes les plus courantes de ces
structures.

| Type              | Exemple                      |
|-------------------+------------------------------|
| adjectif          | Un ciel céleste              |
|                   | Nos rêves endormis           |
| génitif           | Le soupir des soupirs        |
| consistance       | Une guirlande de guirlandes  |
| verbe             | La brume s’embrume           |
| adverbe           | Il ralentit lentement        |
| verbe + Infinitif | Il sait ce qu’il faut savoir |
| complément direct | Il regarde un regard         |
| complément        | La poésie pour la poésie     |
| coordonnée        | De l’art, mais artistique    |
| subordonnée       | Je rêve que je rêve          |

Voici un exemple où Valéry utilise une double récursivité : celle,
assez naturelle, du pronom personnel /me/ par rapport au sujet /Je/,
et celle de l’infinitif /voir/ par rapport au verbe conjugué /voyais/ :

#+BEGIN_CENTER
/Je me voyais me voir/, sinueuse, et dorais
#+END_CENTER

** Nuances

Il s’agit d’une répétition ou le bloc répété est dérivé à chaque
nouvelle occurence.

*** Refrains

On utilise entre-autres les nuances pour varier les refrains.
Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Le vigneron carillonne/
/L’heure des vendanges sonne/

Les beaux raisins sont bien mûrs
Les lourdes grappes vermeilles
Pèsent leur poids sur la treille
On croirait un champ de mûres

/Les vendangeurs emprisonnent/
/Les coloris de l’automne/

Dans les arbres, les buissons
La campagne se barbouille
C’est une autre floraison
De menthe, d’or et de rouille

/Le tonnelier assaisonne/
/La brûlure de l’automne/
#+END_VERSE
#+END_CENTER

** Mouvements

Un mouvement est un déplacement avec forme originale explicite :

#+BEGIN_CENTER
A   —   ⟻ A ⟼
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Le temps s’était figé sur l’aurore des siècles
=.............=
S’était figé le temps sur l’aurore des siècles
#+END_VERSE
#+END_CENTER

** Extensions

On développe une idée préalablement citée sous une forme plus concise.
Exemple :

#+BEGIN_CENTER
La pire, ce fut la pire journée.
#+END_CENTER

Le procédé peut être appliqué plusieurs fois de suite :

#+BEGIN_CENTER
La pire, ce fut la pire journée, ce fut la pire journée dont ils se
souviennent.
#+END_CENTER

*** Droite et gauche

Comme cas particuliers, le développement peut se faire à droite de la
forme concise :

#+BEGIN_CENTER
Je cours. Je cours derrière un être qui s’enfuit.
#+END_CENTER

ou à gauche :

#+BEGIN_CENTER
Je doute. Je n’y peux rien, je doute.
#+END_CENTER

** Compressions

On synthètise une idée préalablement citée sous une forme plus ample.
Exemple :

#+BEGIN_CENTER
C’était le seul moment, le seul.
#+END_CENTER

Le procédé peut être appliqué plusieurs fois de suite :

#+BEGIN_CENTER
Nous étions jeunes et fiers, nous étions jeunes, nous étions.
#+END_CENTER

*** Droite et gauche

Comme cas particuliers, la synthèse peut se faire en supprimant la
droite de la forme étendue :

#+BEGIN_CENTER
Sais-tu pourquoi ils rient, sais-tu pourquoi ?
#+END_CENTER

ou la gauche :

#+BEGIN_CENTER
La montagne est si belle, si belle.
#+END_CENTER

** Dilatations

Il s’agit de développer l’intérieur d’un bloc de texte. Les bords
restent plus ou moins inchangés, au moins phonétiquement. On a donc la
structure :

#+BEGIN_CENTER
AB — AXB
#+END_CENTER

Ce procédé peut servir à mettre en relief une rime, comme par exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Je ne sais plus /pourquoi/ ces cr-IS
/Pourquoi/ les fées dansent la nu-IT
#+END_VERSE
#+END_CENTER

** Contractions

Il s’agit de synthétiser l’intérieur d’un bloc de texte. Les bords
restent plus ou moins inchangés, au moins phonétiquement. On a donc la
structure :

#+BEGIN_CENTER
AXB — AB
#+END_CENTER

** Cadres

Un cadre consiste à conserver au sein d’un groupe une partie constante
dont la position est fixe.

*** Gauche

/Nomenclature traditionnelle : anaphore, épanaphore/

Le début du groupe reste fixe, c’est la fin qui varie. On a la
structure générique :

#+BEGIN_CENTER
AB — AC — AD — =...=
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Choisir un miel,
Choisir une douceur,
Choisir une idée de bonheur
#+END_VERSE
#+END_CENTER

*** Droit

/Nomenclature traditionnelle : épiphore/

La fin du groupe reste fixe, c’est le début qui varie. On a la
structure générique :

#+BEGIN_CENTER
BA — CA — DA — =...=
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Un frisson, il est effrayé,
Une oraison, il est effrayé,
L’ombre d’une ombre même, il est effrayé !
#+END_VERSE
#+END_CENTER

*** Central

Le début et la fin du groupe varient. On a la structure générique :

#+BEGIN_CENTER
BAC — DAE — FAG — =...=
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Le marin /fuit/ l’eau douce,
L’oie sauvage la bise
La fleur /fuit/ la cerise,
Lui ne /fuit/ que l’amour.
#+END_VERSE
#+END_CENTER

*** Hybride

/Nomenclature traditionnelle : symploque, antépériphore/

La partie médiane du groupe varie. On a la structure générique :

#+BEGIN_CENTER
ACB — ADB — AEB — =...=
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Nous avions/ poursuivi /l’impossible/,
/Nous avions/ entrevu /l’impossible/,
/Nous avions/ sommeillé sur /l’impossible/ =...=
#+END_VERSE
#+END_CENTER

*** Alterné

Un cadre alterné consiste à faire varier alternativement
le début et la fin d’un groupe. En voici la structure générique :

#+BEGIN_CENTER
AB — CB — CD — ED — EF — =...=
#+END_CENTER

Un exemple avec un jeu de rimes :

#+BEGIN_CENTER
#+BEGIN_VERSE
Bien que l’eau y soit douce et que dansent les f-ILLES
Leurs jolis bracelets ne rendent qu’un son cr-EUX

L’odeur de l’inutile et de l’absurdit-É
Remplit l’air surchargé d’un luxe somptu-EUX

Qui n’a rêvé l’accès à l’immortalit-É
L’ambroisie, le nectar, les palais olympi-ENS =...=
#+END_VERSE
#+END_CENTER

** Miroirs

Le miroir est semblable à l’inversion, si ce n’est que l’ordre
d’origine est explicite :

#+BEGIN_CENTER
AB — BA
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
C’est qu’il y a tant
De fleurs pour l’écrire
De fleurs /qui pourtant/ (A)
/Ont peur/ (B) de le dire

/Ont peur/ (B) /et pourtant/ (A)
Qui oserait rire
Quel fol épi blanc
Neigerait son ire ?
#+END_VERSE
#+END_CENTER

** Réversions

/Nomenclature traditionnelle : réversion, antimétabole/

La réversion est un cas particulier de miroir où les rôles des deux
blocs sont inversés. Exemple :

#+BEGIN_CENTER
Nous vivons une époque étrange où les /vieux/
se sentent /jeunes/, où les
/jeunes/ se sentent /vieux/.
#+END_CENTER

Le point de vue glisse d’un bloc à l’autre.

*** Négative

On peut utiliser la négation dans l’un des deux groupes :

#+BEGIN_CENTER
#+BEGIN_VERSE
Je ne /sais/ si je /fuis/, mais je /fuis/ si je /sais/.
#+END_VERSE
#+END_CENTER

** Fédération

Il s’agit de fusions ou de scissions ou les blocs d’origine sont
explicitement cités dans le texte.

/Remarque :/ l’appellation provient du système homonyme ou les états
membres sont considérés à la fois séparément et ensemble.

*** Fusion

Les blocs sont d’abord développés séparément avant d’être fusionnés.

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
La /rose/ se refermait,
Le /soir/ tombait,
La /pluie/ menaçait.
La /rose, le soir, la pluie/, ce tourbillon m’emportait !
#+END_VERSE
#+END_CENTER

*** Scission

/Nomenclature traditionnelle : épanode/

Les blocs sont cités côte à côté avant d’être développés séparément.

Exemple :

#+ATTR_HTML: :class plat
| *Dans l’étrange pays des songes* | ⟼ | A |
| _Régi par les charmes des fées_  | ⟼ | B |
| La vérité est un mensonge        |   |   |
| Le mensonge une vérité           |   |   |
|                                  |   |   |
| *Dans l’étrange pays des songes* | ⟼ | A |
| Les castels sont ensorcelés      |   |   |
| Le sol se transforme en éponge   |   |   |
| Sans prévenir l’intéressé        |   |   |
|                                  |   |   |
| _Régi par les charmes des fées_  | ⟼ | B |
| Et la magie des anciens druides  |   |   |
| Chaque passage est cloisonné     |   |   |
| Chaque miroir y est liquide      |   |   |

** Tête-bêche

La fusion du début d’un groupe et de la fin d’un autre en forme un
troisième. On a donc la structure :

#+BEGIN_CENTER
AX — YB — AB
#+END_CENTER

La scission est également possible :

#+BEGIN_CENTER
AB — AX — YB
#+END_CENTER

** Entrelac

IL s’agit d’entrelacer deux groupes de blocs :

#+BEGIN_CENTER
AB — XY — AXBY
#+END_CENTER

** Parallélisme

/Nomenclature traditionnelle : parallélisme, hypozeuxe/

Le parallélisme est la juxtaposition de deux groupes de structure
identiques. On le symbolise par :

#+BEGIN_CENTER
AB — A’B’
#+END_CENTER

Exemple :

#+BEGIN_CENTER
L’eau descend les ruisseaux, la fleur coule les coeurs
#+END_CENTER

*** Inversé

/Nomenclature traditionnelle : chiasme/

Dans le parallélisme inversé, le second groupe a une structure
inversée par rapport au premier :

#+BEGIN_CENTER
AB — B’A’
#+END_CENTER

La forme la plus frappante est une inversion de la structure
grammaticale, comme dans cet exemple de Corneille avec le couple
verbe-adverbe :

#+BEGIN_CENTER
Il /attaque toujours/ et /jamais/ ne se /lasse/
#+END_CENTER

mais elle peut prendre aussi d’autres formes, comme dans le tableau
ci-dessous.

| Type       | Exemple                                                           |
|------------+-------------------------------------------------------------------|
| Phonétique | Secou-AN-t dans mes y-EUX-x leurs f-EU-x diam-AN-tés (Baudelaire) |
|            | an — eu ; eu — an                                                 |
| Rythmique  | Le fleuve / étend ses bras // voluptueux / et clairs              |
|            | 2 — 4 ; 4 — 2                                                     |
| Logique    | Il /grimpe doucement/ et /redescend bien vite/                    |
|            | positif — négatif ; négatif — positif                             |
| Lettres    | L’O-R en R-O_tation                                               |
|            | inversion de lettres                                              |

Un autre exemple de chiasme de lettres, par Didier Meral :

#+BEGIN_CENTER
Mais le t-O-R-rent charrie une R-O-che arrachée
#+END_CENTER

*** Double

Dans le parallélisme double, une structure est inversée mais
pas l’autre. On le note :

#+BEGIN_CENTER
(AB, CD) — (A’B’, D’C’)
#+END_CENTER

Par exemple, on peut inverser les rimes sans inverser la structure de
la phrase :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Au feu luisant/ où cuit l’artich-AUT
/Et au flocon/ venu du beffr-OI
/Au feu luisant/ brûlant sous la s-OIE
/Et au flocon/ qui fond sur ta p-EAU
#+END_VERSE
#+END_CENTER

** Paires

Une paire est une phrase constituée de deux propositions alternatives.
Les propositions sont par exemple introduites par :

#+BEGIN_CENTER
Les uns ..., les autres =...=
D’une part ..., d’autre part =...=
Pour commencer ..., ensuite =...=
Tantôt ..., tantôt =...=
Soit ..., soit =...=
Que l'on soit ..., ou =...=
Ou bien ..., ou bien =...=
Ni ..., ni =...=
... mais, ou, et, donc, or, car ...
#+END_CENTER

*** Semi-implicite

/Nomenclature traditionnelle : anantapodoton, anapodoton/

On peut obtenir un effet de rupture en escamotant une des deux propositions :

#+BEGIN_CENTER
Les uns parient des fortunes aux dés =...=
mais asseyez-vous, je vous en prie !
#+END_CENTER

On peut éventuellement ajouter un indice sur la teneur de la
proposition implicite :

#+BEGIN_CENTER
Les uns parient des fortunes aux dés ... jouez-vous à la roulette ?
#+END_CENTER

Dans ce cas, on devine que /les autres/ parient des fortunes à la
roulette.

**** Contraste

Les structures basées sur une négation, comme le « ni ..., ni ... »,
offrent une variante intéressante. Partant de :

#+BEGIN_CENTER
Ni la lune ni le soleil
#+END_CENTER

le semi-implicite classique nous donne :

#+BEGIN_CENTER
La lune ni le soleil
#+END_CENTER

La variante consiste à intégrer la négation dans la proposition où le
coordonnant est rendu implicite. Par exemple, en partant de :

#+BEGIN_CENTER
Ni le feu ni la lumière ne le réchauffent
#+END_CENTER

on peut utiliser le contraste feu / glace et obtenir :

#+BEGIN_CENTER
La glace ni la lumière ne le réchauffent
#+END_CENTER

** Reprises

/Nomenclature traditionnelle : anadiplose/

Il s’agit de suite de groupes où la fin de chaque groupe est reprise
au début du groupe suivant. On a la structure :

#+BEGIN_CENTER
AB — BC — CD — DE — EF — =...=
#+END_CENTER

Un exemple avec deux groupes :

Je retiendrai /l’espoir/, /l’espoir/ de ce miracle

Un exemple avec plusieurs groupes :

#+BEGIN_CENTER
#+BEGIN_VERSE
Le ciel est /beau/,
/Beau/ comme /l’air/,
/L’air/ est si doux
Loin de l’hiver.
#+END_VERSE
#+END_CENTER

*** Inversées

Il s’agit de suite de groupes où le début de chaque groupe est repris
à la fin du groupe suivant. On a la structure :

#+BEGIN_CENTER
BA — CB — DC — ED — FE — =...=
#+END_CENTER

On voit que la structure de chaque groupe est inversée par rapport
à la reprise ordinaire.

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
*Pourquoi* souffrir,
/Dis-moi/ *pourquoi*
Mon coeur /dis-moi/
S’il faut en rire.
#+END_VERSE
#+END_CENTER

*** Généralisée

La reprise peut se généraliser facilement à plus de deux blocs par
groupe. Exemple avec trois :

#+BEGIN_CENTER
ABC — BCD — CDE — DEF — EFG — =...=
#+END_CENTER

Dans l’autre sens :

#+BEGIN_CENTER
ABC — DAB — EDA — FED — GFE — =...=
#+END_CENTER

** Boucles

#+TOC: headlines 1 local

*** Ronde

Les groupes se donnent la main en utilisant des reprises, jusqu’au
groupe concluant qui se termine par le début du groupe initial. On a
donc la structure générique :

#+BEGIN_CENTER
AB — BC — CD — =...= — XY — YZ — ZA
#+END_CENTER

Un exemple où on utilise les double sens :

#+BEGIN_CENTER
#+BEGIN_VERSE
Le /théâtre/ a besoin de /monnaie/,
La /monnaie/ a besoin de /pièces/,
La /pièce/ à besoin du /théâtre/.
#+END_VERSE
#+END_CENTER

*** Rondine

/Nomenclature traditionnelle : épanadiplose/

Un même bloc de texte est cité au début d’un groupe et à la fin d’un
autre, ce qui donne un effet de retour. La structure type est donc :

#+BEGIN_CENTER
AB — CA
#+END_CENTER

On peut voir une rondine comme un cas particulier de reprise inversée,
écourtée et bouclée.

Cet exemple utilise deux strophes :

#+ATTR_HTML: :class plat
| *Des chats j’ai appris la paresse* |   |   |
| *Et des minettes les câlins*       | ⟼ | A |
| _Je dois dire que leurs caresses_  |   |   |
| _M’ont rendu dingue du satin_      | ⟼ | B |
|                                    |   |   |
| /Si je suis chaud comme un lapin/  |   |   |
| /La faute en est à ces déesses/    | ⟼ | C |
| *Des chats j’ai appris la paresse* |   |   |
| *Et des minettes les câlins*       | ⟼ | A |

et celui-ci deux propositions :

*En vain* _il court_, /toujours/ *en vain*.

*** Serpentine

/Nomenclature traditionnelle : antepiphore, épanalepse/

Le bloc répété apparaît au début et à la fin d’une même structure.
Cette structure peut être une phrase :

#+BEGIN_CENTER
/L’horizon/ rougeoyant avale /l’horizon/.
#+END_CENTER

une strophe :

#+BEGIN_CENTER
#+BEGIN_VERSE
/- Etres fols qui nagez, vous roulez dans vos vices,/
Vous contenterez-vous des bas-fonds du débats,
D’humecter de vos doigts l’aile ronde ou la cuisse ?
C’est assez de surface, explorez les abysses !
Oui, sondez l’insondable océan du sabbat,
Ne vous contentez pas des bas-fonds du débat,
/Etres fols qui nagez, vous roulez dans vos vices./
#+END_VERSE
#+END_CENTER

un vers :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Je te suis/ d’un pas vif et joyeux, /je te suis/
Reconnaissant et fier de danser sous la pluie
#+END_VERSE
#+END_CENTER

ou un hémistiche, comme dans cet exemple de Baudelaire :

#+BEGIN_CENTER
/Entends/ ma chère, /entends/ — la douce nuit qui marche.
#+END_CENTER

ou cet autre de Valéry :

#+BEGIN_CENTER
/Voir/, ô merveille, /voir/ !  — ma bouche nuancée
#+END_CENTER

*** Ostinato

Il s’agit de la répétition incessante et successive d’un bloc de texte
dont la fin est une introduction au début, ce qui donne un effet de
mouvement perpétuel.

Les ostinatos sont souvent conclus par un bloc de texte plus petit,
appelé clausule. La clausule peut être indépendante ou dérivée du bloc
répété. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Pourquoi la lune est si douce, je sais
Pourquoi la lune est si douce, je sais
=.......................................=
Pourquoi la lune est si douce, je sais
Pourquoi.
#+END_VERSE
#+END_CENTER

Lorsqu’on place l’ostinato en refrain, la clausule donne un effet
saisissant marquant la fin du texte. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
=....................................=
=....................................=
Jamais de cierge n’a fondu

=....................................=
=....................................=
Jamais de cierge n’a fondu

=....................................=

=....................................=
=....................................=
Jamais de cierge n’a fondu

=....................................=
=....................................=
Jamais de cierge n’a fondu
Sans que l’amour soit de mêche.
#+END_VERSE
#+END_CENTER

*** Moulin

Il s’agit de mettre tour à tour en évidence les constituants les
plus importants d’un bloc de texte. Une application courante est de
placer tour à tour les mots importants d’un vers à la rime. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Je vous /entends/ fleurs de /minuit/
Qui dansez sous la lune argent
Car du ciel d’encre monte un cri
Fleurs de /minuit/ je vous /entends/
#+END_VERSE
#+END_CENTER

** Glissade

La position d’un bloc de texte glisse vers la gauche de groupe en
groupe. Exemple :

#+BEGIN_CENTER
ABC — DCE — CFG
#+END_CENTER

On peut prolonger la série en choisissant un nouveau bloc à faire
glisser :

#+BEGIN_CENTER
ABC — DCE — CFG — HGI — GJK — =...=
#+END_CENTER

*** Inversée

La position d’un bloc de texte glisse vers la droite de groupe en
groupe. Exemples :

#+BEGIN_CENTER
ABC — DAE — FGA
#+END_CENTER

On peut prolonger la série en choisissant un nouveau bloc à faire
glisser :

#+BEGIN_CENTER
ABC — DAE — FGA — HFI — JKF — =...=
#+END_CENTER

** Hélice

Il s’agit d’une glissade dans un sens, puis dans l’autre, formant
comme une rotation dans les groupes. Exemple :

#+BEGIN_CENTER
ABC — DCE — CFG — HCI — JKC — =...=
#+END_CENTER

*** Inversée

L’hélice inversée commence à glisser dans l’autre sens. Exemple :

#+BEGIN_CENTER
ABC — DAE — FGA — HAI — AJK — =...=
#+END_CENTER

** Arborescence

Une arborescence est constituée d’une racine reliée à plusieurs
branches. On met en évidence les liens entre la racine et les branches
en utilisant la répétition.

*** Fourche

La fin de la racine est reprise à tous les débuts des blocs suivants :

#+BEGIN_CENTER
AB — BC — BD — =...=
#+END_CENTER

Exemple :

#+begin_center
#+begin_verse
Elle est revenue,
La belle /saison/,
/Saison/ des amours,
/Saison/ des moissons.
#+end_verse
#+end_center

*** Fourche inversée

Dans la fourche inversée, le bloc contenant la racine est présent à la
fin de la structure :

#+BEGIN_CENTER
AX — BX — =...= — UX — XZ
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Il file comme un /oiseau/,
Il chante comme un /oiseau/,
Il vole comme un /oiseau/,
Un /oiseau/ qui joue avec les vagues.
#+END_VERSE
#+END_CENTER

*** Grammaticale

/Nomenclature traditionnelle : polysyndète/

On ajoute un même coordonnant à toutes les branches se référant à une
même racine. Un exemple de Voltaire :

#+BEGIN_CENTER
#+BEGIN_VERSE
Oui je le lui rendrai, /mais/ mourant, /mais/ puni
/Mais/ versant à ses yeux le sang qui m’a trahi
#+END_VERSE
#+END_CENTER

équivalent à la forme plus concise :

#+BEGIN_CENTER
#+BEGIN_VERSE
Oui je le lui rendrai, /mais/ mourant, puni,
Versant à ses yeux le sang qui m’a trahi
#+END_VERSE
#+END_CENTER

** Factorisations

/Nomenclature traditionnelle : zeugme, zeugma, disjonction/

On n’utilise qu’une seule occurence d’un même texte commun à plusieurs
blocs de texte. Par exemple, cette phrase :

#+BEGIN_CENTER
/Quelques années/ plus tard,
/quelques années/ qui semblèrent des siècles
#+END_CENTER

donne après factorisation :

#+BEGIN_CENTER
/Quelques années/ plus tard, qui semblèrent des siècles
#+END_CENTER

Autre exemple, Hugo a exprimé cette idée :

#+BEGIN_CENTER
#+BEGIN_VERSE
L’air /était plein/ d’encens et les prés /étaient plein/ de verdure
#+END_VERSE
#+END_CENTER

par la forme factorisée :

#+BEGIN_CENTER
L’air /était/ plein d’encens et les prés de verdure
#+END_CENTER

Autre exempl avec des phrases relatives :

#+BEGIN_CENTER
#+BEGIN_VERSE
Je sais /que/ tu le vois, /que/ tu le comprends.
#+END_VERSE
#+END_CENTER

qu’on peut remplacer par :

#+BEGIN_CENTER
#+BEGIN_VERSE
Je sais /que/ tu le vois, tu le comprends.
#+END_VERSE
#+END_CENTER

** Tableaux

Il s’agit d’appliquer le principe de la dualité à un tableau, en le
lisant tantôt ligne par ligne, tantôt colonne après colonne.
Considérons le tableau :

| A | B |
| R | S |

Lu ligne après ligne, il nous donne :

#+BEGIN_CENTER
A — B — R — S
#+END_CENTER

Colonne après colonne, cela devient :

#+BEGIN_CENTER
A — R — B — S
#+END_CENTER

Si nous partons par exemple des éléments :

| Agile  | Singe |
| Furtif | Chat  |

on peut construire la phrase « ligne » :

#+BEGIN_CENTER
Aussi /agile/ qu’un /singe/, aussi /furtif/ qu’un /chat/
#+END_CENTER

qui devient, en version « colonne » :

#+BEGIN_CENTER
#+BEGIN_VERSE
Il était /agile/ et /furtif/,
Un /singe/ aux moustaches de /chat/
#+END_VERSE
#+END_CENTER

*** Rectangulaire

Voici un autre tableau, de deux lignes et trois colonnes cette fois :

| A | B | S |
| R | S | T |

Lu ligne par ligne, il nous donne :

#+BEGIN_CENTER
A — B — C — R — S — T
#+END_CENTER

Colonne par colonne, cela devient :

#+BEGIN_CENTER
A — R — B — S — C — T
#+END_CENTER

Si nous partons par exemple de cette phrase :

#+BEGIN_CENTER
#+BEGIN_VERSE
Les rayons s’étirent,
les arbres s’éveillent,
les quatre vents se lèvent
#+END_VERSE
#+END_CENTER

elle deviendra :

#+BEGIN_CENTER
#+BEGIN_VERSE
Les rayons, les arbres et les quatre vents
s’étirent, s’éveillent, se lèvent
#+END_VERSE
#+END_CENTER

*** Rimes

Cette technique peut être employée pour entrelacer des rimes. Ainsi,
la structure /a b b a/ peut être associée à /c d c d/ :

| a | b | b | a |
| c | d | c | d |

La lecture colonne par colonne nous donne alors /a c b d b c a d/, structure utilisée dans cette strophe :

#+BEGIN_CENTER
#+BEGIN_VERSE
Où l’air s’appesantit
Le temps cesse de battre
Plus de vent plus de sens
La plaine attend l’orage
Attend sa délivrance
Que l’atmosphère éclate
Du verbe qui jaillit
Rempli d’idées sauvages
#+END_VERSE
#+END_CENTER

** Produit tensoriel

On commence par examiner toutes les combinaisons possible entre deux
séries de blocs. Par exemple, avec deux couples /(A, B)/ et /(C, D)/,
on a le tableau :

| ⨯ | R  | S  |
| A | AR | AS |
| B | BR | BS |

Un produit tensoriel est une structure qui énumère toutes ces
possibilités, comme par exemple :

#+BEGIN_CENTER
AR — AS — BR — BS
#+END_CENTER

En voici une application :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Rose des blés/ tu montes pég-ASE
/Rose des blés/ nymphe des lég-ENDES
/Les bois dorés/ sous tes pas s’embr-ASENT
/Les bois dorés/ les champs de lav-ANDE
#+END_VERSE
#+END_CENTER

** Dualité

La dualité est une notion très puissante qui peut désigner différents
concepts semblables.

*** Optimisation

En optimisation, la dualité est un concept qui relie le maximum d’un
ensemble au minimum de l’ensemble complémentaire. Ainsi, une plage en
bordure de mer peut être vue comme le point le plus bas du continent,
ou le point le plus haut de l’océan. Il s’agit donc d’une inversion de
point de vue.

On peut utiliser ce concept pour « dualiser » une image. Partons par
exemple de :

#+BEGIN_CENTER
Les voiles sont les ailes du navire.
#+END_CENTER

Les ailes font clairement référence à un oiseau. On se place donc du
point de vue de l’oiseau, et on écrit :

#+BEGIN_CENTER
Les ailes sont les voiles de l’oiseau.
#+END_CENTER

*** Formes linéaires

En théorie des formes linéaires, la dualité est un concept qui
consiste à regarder le résultat d’une opération binaire tantôt comme
une fonction de la première variable, tantôt comme une fonction de la
seconde. Nous adoptons donc une structure où chacun des blocs d’un
groupe de deux blocs varie tour à tour :

#+BEGIN_CENTER
AR — AS — BS
#+END_CENTER

En voici une application :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Le lac s’étalait/ sous la l-UNE
/Le lac s’étalait/ sans or-AGE
/Que restait-il/ sur le riv-AGΕ ?
#+END_VERSE
#+END_CENTER

On peut également faire varier le début du groupe avant la fin :

#+BEGIN_CENTER
AR — BR — BS
#+END_CENTER

Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Le potager/ sentait la /menthe/
/Son fruit femelle/ une autre a/mante/
/Son fruit femelle/ entre ses /mains/
#+END_VERSE
#+END_CENTER

*** Réversion

On peut considérer la réversion comme un cas particulier de dualité.

* Carillon

#+TOC: headlines 1 local

** Préparation - Tension - Résolution

Il s’agit de s’inspirer du principe musical alternant préparation,
tension et détente d’une mélodie, harmonie ou rythme. Considérons cet
exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Oui je le sais /princesse/, et je sais la /tristesse/
Et l’étrange /beauté/ des divines /faiblesses/ =...=
#+END_VERSE
#+END_CENTER

Les hémistiches du premiers vers (/princesse — tristesse/) riment
entre-eux, l’oreille s’habitue à cette sonorité, c’est la préparation.
Le premier hémistiche du second vers fait entendre une sonorité
orpheline (/beauté/), c’est la tension. Le second hémistiche du second
vers détend l’oreille en revenant à la rime des hémistiches du premier
vers (/faiblesse/), c’est la résolution.

On remarque que la figure est due, non pas au caractère
particulièrement tendu ou détendu du texte, mais au /contraste/ entre
les deux parties. Ainsi, dans cet autre exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Au hurlement du vent dans les plaines de br-UME =...=
Que de coups de tabac, de tempêtes, de gr-AINS
De beauté a-t-il dû traverser, et d’éc-UME,
Combien de naufragées les soirs de pleine l-UNE ?
#+END_VERSE
#+END_CENTER

Ce n’est pas vraiment la tension des rimes différentes des deux
premiers vers, schéma très courant en poésie, qui provoque l’effet
mais plutôt le contraste avec la résolution matérialisée par la rime
approximative commune des deux derniers vers.

** Ouverture — Conclusion

Un des modèles de phrase musicale se décompose en une première partie
ouverte et une seconde partie conclusive. En littérature, on se sert
de la ponctuation et de la structure du texte pour produire un effet
similaire. Dans cet exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Il a vogué, pareil aux ailettes d’argent,
    Il a vogué sur l’océan.
#+END_VERSE
#+END_CENTER

Le premier vers est ouvert, on s’attend clairement à une suite, alors
que le second est conclusif.

** Cadences

/Nomenclature traditionnelle : bathos/

En musique, une cadence est un enchaînement d’accords indiquant une
légère pause ou une conclusion. Lorsque la cadence est conclusive, on
a l’impression que la musique retombe au sol après avoir voltigé dans
les airs. On peut s’inspirer de cette structure pour créer un effet de
surprise. Le procédé le plus courant consiste à augmenter
graduellement le ton dans un sens avant de l’inverser brutalement.
Exemple :

#+BEGIN_CENTER
Il est honnête, poli, courtois, délicat,
charmant, en un mot /insipide/.
#+END_CENTER

** Rupture

/Nomenclature traditionnelle : aposiopèse/

Analogue à la rupture d’une continuité mélodique, elle consiste à changer
de sujet de façon abrupte. Exemple :

#+BEGIN_CENTER
Et si j’y parvenais ... La pluie a-t-elle cessé ?
#+END_CENTER

** Rythmes

On peut faire varier le rythme des phrases en allongeant ou
raccourcissant les syntagmes, les propositions.

En poésie, on peut jouer à la fois sur le rythme des phrases et sur
les mètres des vers, par exemple en faisant varier l’un tout en
laissant l’autre constant.

** Enjambements

L’enjambement est analogue à une mélodie syncopée, c’est-à-dire
décalée par rapport au rythme. En poésie, on remplace la mélodie par
la structure de la phrase, tandis que le rythme est cadencé par les
vers, les hémistiches et les strophes. Un enjambement est donc obtenu
en décalant la fin d’un vers, d’un hémistiche ou d’une strophe par
rapport aux pauses naturelles correspondant à la structure de la
phrase.

*** Sémantique

Les plus beaux enjambements sont ceux qui donnent un double sens aux
vers, comme dans cet exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
Princesse, /je te suis/
/Reconnaissant/. Celui
=............=
#+END_VERSE
#+END_CENTER

A la fin de la lecture du premier vers, on a l’impression que le
narrateur veut /suivre/ la princesse. Au second vers, on apprend qu’il
lui /est/ reconnaissant. On peut même développer la strophe afin de
laisser les deux sens s’épanouir :

#+BEGIN_CENTER
#+BEGIN_VERSE
Lune d’or, je te /suis/
Tel une ombre légère.
Lune d’or, je te /suis/
Reconnaissant de ta lumière.
#+END_VERSE
#+END_CENTER

Dans les deux premier vers, il s’agit bien entendu du verbe /suivre/,
et dans les deux derniers du verbe /être/.

*** Serpentin

La combinaison d’un enjambement et d’une serpentine provoque un
contraste encore plus saisissant entre la structure rythmique et le
phrasé. Exemple :

#+BEGIN_CENTER
#+BEGIN_VERSE
/Nous irons/ écouter leur rire, /nous irons/
Admirer la fraîcheur timide des cascades
#+END_VERSE
#+END_CENTER

*** Rejet

Le rejet est une forme d’enjambement où un élément court est isolé au
début du second vers :

#+BEGIN_CENTER
#+BEGIN_VERSE
Le moindre coup de vent, la plus petite goutte
/De pluie/ leur suffisait pour se découvrir libres.
#+END_VERSE
#+END_CENTER

*** Contre-rejet

Le contre-rejet est une forme d’enjambement où un élément court est
isolé à la fin du premier vers :

#+BEGIN_CENTER
#+BEGIN_VERSE
La lune et le soleil s’embrassaient. /Un nuage/
Translucide voilait la flamme de leur rage.
#+END_VERSE
#+END_CENTER

* Architecture

#+TOC: headlines 1 local

** Imbriquer

Il s’agit d’imbriquer les figures sur deux niveaux ou plus.

On peut par exemple former une combinaison à partir d’un développement
et d’une déclinaison. Exemple à partir de /l’aurore humide de rosée/ :

#+begin_center
#+begin_verse
L’aurore humide encor de la rosée nocturne
Arrose la prairie de sa sérénité
#+end_verse
#+end_center

** Méta

C’est un procédé qui consiste à construire une figure de style au
moyen de briques étant elles-mêmes des figures de style.

** Composition

Il s’agit d’appliquer une figure de style après l’autre. Voici par
exemple une réversion :

#+BEGIN_CENTER
Nous vivons une époque étrange où les vieux se sentent jeunes,
où les jeunes se sentent vieux.
#+END_CENTER

à laquelle on applique le principe de factorisation :

#+BEGIN_CENTER
Nous vivons une époque étrange où les vieux se sentent
jeunes, les jeunes vieux.
#+END_CENTER

*** Connexion et contraste

On part d’un contraste, comme :

#+BEGIN_CENTER
Les eaux en feu
#+END_CENTER

puis, on substitue en utilisant une connexion :

#+BEGIN_CENTER
feu —— fumée —— fumant(e)
#+END_CENTER

ce qui nous donne :

#+BEGIN_CENTER
Les eaux fumantes
#+END_CENTER

*** Yourcenar

Marguerite Yourcenar nous en livre un autre exemple, en partant de la
phrase :

#+BEGIN_CENTER
Quelques braves gens dont c’était le métier de mourir mouraient.
#+END_CENTER

elle déplace la relative :

#+BEGIN_CENTER
Quelques braves gens mouraient dont c’était le métier de mourir.
#+END_CENTER

puis factorise :

#+BEGIN_CENTER
Quelques braves gens mouraient dont c’était le métier.
#+END_CENTER

*** Corneille

Voyons à présent cette idée exprimée par Corneille :

#+BEGIN_CENTER
Je t’aimais /alors que tu étais/ inconstant,
qu’eussé-je fait /si tu avais été/ fidèle ?
#+END_CENTER

On peut factoriser les blocs semblables :

#+BEGIN_CENTER
Je t’aimais /alors que tu étais/ inconstant,
qu’eussé-je fait fidèle ?
#+END_CENTER

avant de rendre l’articulation implicite, ce qui nous amène au vers
célèbre:

#+BEGIN_CENTER
Je t’aimais inconstant, qu’eussé-je fait fidèle ?
#+END_CENTER

*** Rostand

Ce vers de Rostand mêle un chiasme avec un double contraste
homme / femme et joyeux / triste :

#+BEGIN_CENTER
Joyeux pour une femme, et pour un homme, triste
#+END_CENTER

** Introduction

#+TOC: headlines 1 local

*** Implicite

On peut rentrer directement dans le vif d’une idée en rendant son
introduction implicite. Cette technique donne de la vigueur au texte.

*** Déplacée

En reportant l’introduction à la fin du discours, on lui donne un air
de conclusion, renforçant ainsi son importance

*** Répétée

L’introduction peut être répétée au début et à la fin du discours,
formant ainsi une boucle.

** Conclusion

#+TOC: headlines 1 local

*** Implicite

On peut rendre implicite la conclusion d’une idée, ce qui diffuse une
atmosphère de sous-entendu.

*** Déplacée

En déplaçant la conclusion au début du discours, on lui donne un air
d’introduction, renforçant ainsi son importance.

*** Répétée

On renforce l’importance de la conclusion en la répétant au début et à
la fin du discours.

* Temple

#+TOC: headlines 1 local

** Juxtapositions

#+TOC: headlines 1 local

*** Évidence

Pour appuyer une affirmation, il suffit de la juxtaposer avec une
évidence. Par exemple, si on veut proclamer avec force que la bouderie
succède souvent à la colère, on pourra écrire :

#+BEGIN_CENTER
L’hiver succède à l’automne, la bouderie à la colère.
#+END_CENTER

*** Absurdité

Pour illustrer la fausseté d’une affirmation, on peut la juxtaposer
avec une absurdité. Exemple :

#+BEGIN_CENTER
Je l’ai déjà vu user de franchise, c’était un 30 février je crois.
#+END_CENTER

Le caractère absurde provient ici du 30 février, date non valide comme
chacun sait.

*** Grand angle

/Nomenclature traditionnelle : antéoccupation/

Il s’agit de présenter un point de vue différent avant l’affirmation.
Exemple :

#+BEGIN_CENTER
Cette prairie est magnifique, mais alors que dire du ciel nocturne !
#+END_CENTER

** Simulations

#+TOC: headlines 1 local

*** Interrogation

Poser une question dont la réponse est évidente et renforce
l’apparente solidité d’un argument.

*** Doute

/Nomenclature traditionnelle : dubitation/

Feindre le doute entre deux opinions ou deux décisions pour ensuite
trancher dans le sens souhaité.

*** Mauvaises augures

/Nomenclature traditionnelle : commination/

Décrire les malheurs qui surgiraient en cas de décision contraire à
celle que l’on attend.

*** Conciliation

/Nomenclature traditionnelle : communication/

Feindre la concilation pour amener l’adversaire à baisser sa garde.

** Négociations

#+TOC: headlines 1 local

*** Concession

Céder sur un point de détail dont on fait des montagnes pour mieux
imposer un point crucial dont on cache ou minimise l’importance.

*** Objection anticipée

/Nomenclature traditionnelle : apodioxe/

Anticiper une objection en l’exposant pour ensuite la réfuter.

*** Dire sans dire

/Nomenclature traditionnelle : prétérition/

Décrire ou sous-entendre quelque chose tout en se défendant de le
faire.
