
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 07 : Intégrales - 4
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Intégrales et mesures

#+TOC: headlines 1 local


** Addition de mesure

Soit les mesures $\gamma, \lambda$ et la mesure $\mu$ définie par :

$$\mu = \gamma + \lambda$$

Soit un ensemble $A$ et une fonction $w \in \etagee(A)$. On peut trouver des $w_i \in \setR$ et des $A_i \in \mathcal{T}$ formant une partition de $A$ et tels que :

$$w(x) = \sum_{i = 1}^n w_i \cdot \indicatrice_{A_i}(x)$$

On a alors :

\begin{align}
\int_A w(x) \ d\mu(x) &= \sum_{i = 1}^n w_i \cdot \mu(A_i) \\
&= \sum_{i = 1}^n w_i \cdot (\gamma(A_i) + \lambda(A_i)) \\
&= \sum_{i = 1}^n w_i \cdot \gamma(A_i) + \sum_{i = 1}^n w_i \cdot \lambda(A_i) \\
&= \int_A w(x) \ d\gamma(x) + \int_A w(x) \ d\lambda(x)
\end{align}

En passant au suprémum sur toutes les fonctions étagées $w$ essentiellement inférieures à une fonction positive intégrable, puis en utilisant la définition d'une fonction intégrable $f$ on en déduit que :

$$\int_A f(x) \ d(\gamma + \lambda)(x) = \int_A f(x) \ d\gamma(x) + \int_A f(x) \ d\lambda(x)$$


** Mesure de Lebesgue

Soit $A \subseteq \setR^n$ et $\mu_L$ la mesure de Lebesgue. On note alors $d\mu_L(x) = dx$ ou :

$$d\mu_L(x) = dx = dx_1 \ ... \ dx_n$$

et :

$$\int_A f(x) \ dx = \int_A f(x) \ d\mu_L(x)$$


** Intégrale de Stieltjes

Soit la fonction croissante $\gamma : A \mapsto \setR$. L'intégrale de Stieltjes associée à $\gamma$ se note :

$$\int_A f(x) \ d\gamma(x)$$

Elle se définit d'après la mesure de Stieltjes $\mu_\gamma$ associée à $\gamma$ :

$$\int_A f(x) \ d\gamma(x) = \int_A f(x) \ d\mu_\gamma(x)$$


*** Fonction à variation bornée

Nous allons étendre la définition à des fonctions non nécessairement croissantes. Soit une fonction $g : [\alpha,\beta] \mapsto \setR$ et $S[a,b]$ l'ensemble des suites réelles croissantes inclues dans $[a,b]$ :

$$S[a,b] = \Big\{ \{x_0, x_1, x_2, ..., x_n \} : a \le x_0 \le x_1 \le x_2 \le ... \le b, \ n \in \setN \Big\}$$

Nous supposons que la fonction $g$ nous permet de définir les fonctions $\sigma,\lambda$ associées par :

$$\sigma(x) = \sup \accolades{ \sum_{i = 0}^n \max\{g(x_{i + 1}) - g(x_i), 0\} : \{x_0, x_1, ..., x_n \} \in S[\alpha,x] }$$

et :

$$\lambda(x) = - \inf \accolades{ \sum_{i = 0}^n \min\{g(x_{i + 1}) - g(x_i), 0\} : \{x_0, x_1, ..., x_n \} \in S[\alpha,x] }$$

pour tout $x \in [\alpha,\beta]$. Il est clair que les fonctions $\sigma, \lambda$ sont croissantes. On peut donc définir l'intégrale de Stieltjes associée à $g$ par :

$$\int_A f(x) \ dg(x) = \int_A f(x) \ d\sigma(x) - \int_A f(x) \ d\lambda(x)$$


*** Positivité

L'intégrale de Stieltjes d'une fonction essentiellement positive n'est généralement pas positive.


** Mesure pondérée

Soit une fonction essentiellement positive $\varphi$ telle que la fonction $\mu$ associée définie par :

$$\mu(A) = \int_A \varphi(x) \ dx$$

soit une mesure. Considérons une fonction $w \in \mathcal{E}_A(f)$, avec :

$$w = \sum_i w_i \cdot \indicatrice_{A_i}$$

où les $A_i$ forment une partition de $A$ et où les $w_i \in \setR$. On a alors :

$$\int_A w(x) \ d\mu(x) = \sum_i w_i \cdot \int_{A_i} \varphi(x) \ dx$$

Par linéarité de l'intégrale, on voit aussi que :

\begin{align}
\int_A w(x) \cdot \varphi(x) \ dx &= \sum_i w_i \cdot \int_A \varphi(x) \cdot \indicatrice_{A_i}(x) \ dx \\
&= \sum_i w_i \cdot \int_{A_i} \varphi(x) \ dx
\end{align}

On en conclut que :

$$\int_A w(x) \ d\mu(x) = \int_A w(x) \cdot \varphi(x) \ dx$$

Comme $\varphi$ est positive, on a l'équivalence entre $w \essinferieur f$ et $w \cdot \varphi \essinferieur f \cdot \varphi$. En passant au supremum, on obtient donc :

$$\int_A f(x) \ d\mu(x) = \int_A f(x) \cdot \varphi(x) \ dx$$

pour toute fonction intégrable $f : A \to \setR$. On note symboliquement :

$$d\mu(x) = \varphi(x) \ dx$$


*** Problème inverse

Remarquons qu'on ne sait généralement pas faire correspondre une fonction $\varphi$ à une mesure $\mu$ donnée.


** Mesure de Dirac

L'intégrale d'une fonction $f : \setR \to \setR$ par rapport à une mesure de Dirac $\mu_D^a$ est fort simple à calculer. En effet :

$$\int_A d\mu_D^a(x) = \mu_D^a(A) = \indicatrice_A(a)$$

par définition. Si $a \notin A$, l'ensemble $A$ est de mesure nulle et :

$$\int_A f(x) \ d\mu_D^a(x) = 0$$

Considérons à présent le cas où $a \in A$. L'ensemble $A \setminus \{a\}$ étant disjoint de $\{a\}$ et de mesure nulle :

$$\int_{A \setminus \{a\}} d\mu_D^a(x) = \indicatrice_{A \setminus \{a\}}(a) = 0$$

on a :

$$\int_A f(x) \ d\mu_D^a(x) = \int_{\{a\}} f(x) \ d\mu_D^a(x)$$

La fonction $f$ étant constante sur $\{a\}$ et valant $f(a)$, on a finalement :

$$\int_A f(x) \ d\mu_D^a(x) = f(a) \cdot \indicatrice_{\{a\}}(a) = f(a)$$

Dans le cas général, on a donc :

$$\int_A f(x) \ d\mu_D^a(x) = f(a) \cdot \indicatrice_A(a)$$

On note également :

$$\int_A f(x) \ \indicatrice(x - a) \ dx = f(a) \cdot \indicatrice_A(a)$$


** Pondérée - Dirac

Soit une mesure $\mu$ définie par :

$$d\mu(x) = \left[ \varphi(x) + \sum_i \alpha_i \cdot \indicatrice(x - x_i) \right] \ dx$$

où les $\alpha_i \in \setR$. Si les $x_i$ appartiennent tous à $A$, l'intégrale d'une fonction $f$ par rapport à cette mesure s'écrit :

$$\int_A f(x) \ d\mu(x) = \int_A f(x) \cdot \varphi(x) \ dx + \sum_i \alpha_i \cdot f(x_i)$$


* Intégrales unidimensionnelles

#+TOC: headlines 1 local


** Intreduction

Soit une fonction $f : \setR \mapsto \setR$ et $a,b \in \setR$ tels que $a \le b$.


*** Intervalle

On définit la notation particulière :

$$\int_a^b f(x) \ d\mu(x) = \int_{[a,b]} f(x) \ d\mu(x)$$


*** Intervalle inversé

On étend la notation à des « intervalles » inversés par :

$$\int_b^a f(x) \ d\mu(x) = - \int_a^b f(x) \ d\mu(x)$$


*** Intervalle ouvert

Pour les intervalles ouverts, on considère la limite :

$$\int_{]a,b[} f(x) \ d\mu(x) = \lim_{(s,t) \to (a,b)} \int_s^t f(x) \ d\mu(x)$$


*** Infini

Quand une des bornes de l'intervalle tend vers l'infini, on définit l'intégrale par :

#+BEGIN_CENTER
\(
\int_a^{+\infty} f(x) \ d\mu(x) = \lim_{b \to +\infty} \int_a^b f(x) \ d\mu(x) \\
\int_{-\infty}^b f(x) \ d\mu(x) = \lim_{a \to -\infty} \int_a^b f(x) \ d\mu(x)
\)
#+END_CENTER


*** Sur l'ensemble des réels

Enfin, l'intégrale sur $\setR$ entier est définie par :

$$\int_{-\infty}^{+\infty} f(x) \ d\mu(x) = \int_\setR f(x) \ d\mu(x) = \lim_{a \to -\infty} \int_{-a}^a f(x) \ d\mu(x)$$


** Additivité d'intervalles

Soit $a,b,c,\alpha,\beta \in \setR$ avec $\alpha \le a,b,c \le \beta$. Soit une fonction intégrable $f : [\alpha,\beta] \mapsto \setR$. Posons :

$$I(x,y) = \int_x^y f(\xi) \ d\xi$$

où $d\xi = d\mu_L(\xi)$ est la mesure de Lebesgue. Par définition, on a :

$$I(y,x) = - I(x,y)$$

Si $a \le b \le c$, on a :

$$\mu_L( [a,b] \cap [b,c] ) = \mu_L( \{ b \} ) = 0$$

L'additivité nous donne alors :

$$I(a,c) = I(a,b) + I(b,c)$$

Si $a \le c \le b$, on a :

$$\mu_L( [a,c] \cap [c, b] ) = \mu_L( \{ c \} ) = 0$$

et :

$$I(a,b) = I(a,c) + I(c,b)$$

On en déduit que :

$$I(a,c) = I(a,b) - I(c,b) = I(a,b) + I(b,c)$$

On vérifie pareillement, en considérant tous les cas, que $I(a,b) = I(a,c) + I(c,b)$ quel que soit l'ordre des réels $a,b,c$. On a donc :

$$\int_a^c f(x) \ dx = \int_a^b f(x) \ dx + \int_b^c f(x) \ dx$$


** Valeur moyenne d'une intégrale

Soit la fonction intégrable et continue $f : [a,b] \mapsto \setR$. Pour la mesure de Lebesgue, on a :

#+BEGIN_CENTER
\(
\supessentiel \{ f(x) : x \in [a,b] \} = \max f([a,b]) \\
\infessentiel \{ f(x) : x \in [a,b] \} = \min f([a,b])
\)
#+END_CENTER

Les bornes d'une fonction continue sur un intervalle fermé étant atteintes, on peut trouver des réels $\sigma,\lambda \in [a,b]$ tels que :

#+BEGIN_CENTER
\(
f(\sigma) = \max f([a,b]) \\
f(\lambda) = \min f([a,b])
\)
#+END_CENTER

Les bornes de l'intégrales nous disent que :

$$f(\lambda) \le \unsur{b - a} \int_a^b f(s) ds \le f(\sigma)$$

Le théorème des valeurs intermédiaires nous permet alors de trouver un $c$ compris entre $\lambda$ et $\sigma$ (et donc dans $[a,b]$) tel que :

$$f(c) = \unsur{b - a} \int_a^b f(s) ds$$


* Les espaces fonctionnels

#+TOC: headlines 1 local


** Dépendances

  - Chapitre \ref{chap:mesure} : Les normes
  - Chapitre \ref{chap:ps} : Les produits scalaires
  - Chapitre \ref{chap:integral} : Les intégrales


** Fonctions intégrables

Soit une fonction $f : A \mapsto \setR$ et sa décomposition en fonctions positives $f = f^+ - f^-$. Soit $\abs{f} : A \mapsto \setR$ définie par :

$$\abs{f}(x) = \abs{f(x)}$$

pour tout $x \in A$. Si $f(x) \ge 0$, on a $f^-(x) = 0$ et :

$$\abs{f(x)} = f(x) = f^+(x) = f^+(x) + f^-(x)$$

Si $f(x) \strictinferieur 0$, on a $f^+(x) = 0$ et :

$$\abs{f(x)} = -f(x) = f^-(x) = f^+(x) + f^-(x)$$

On en conclut que $\abs{f} = f^+ + f^-$. Si $f$ est intégrable, $f^+$ et $f^-$ le sont aussi et :

$$\int_A \abs{f(x)} \ d\mu(x) = \int_A f^+(x) \ d\mu(x) + \int_A f^-(x) \ d\mu(x) \strictinferieur +\infty$$

La fonction $\abs{f}$ est donc également intégrable. Inversément, si $\abs{f}$ est intégrable, on a $f^+ = \abs{f} - f^- \le \abs{f}$ et $f^- = \abs{f} - f^+ \le \abs{f}$, d'où :

#+BEGIN_CENTER
\(
\int_A f^+(x) \ d\mu(x) \le \int_A \abs{f(x)} \ d\mu(x) \strictinferieur +\infty \\ \\
\int_A f^-(x) \ d\mu(x) \le \int_A \abs{f(x)} \ d\mu(x) \strictinferieur +\infty
\)
#+END_CENTER

La fonction $f$ est donc également intégrable. On en conclut que l'on peut représenter l'ensemble des fonctions intégrables par :

$$\lebesgue(A) = \left\{ f \in \setR^A : \int_A \abs{f(x)} \ d\mu(x) \strictinferieur +\infty \right\}$$


** Intégrale complexe

Soit une fonction à valeurs complexes $u : A \mapsto \setC$. On définit les fonctions à valeurs réelles associées $v,w : A \mapsto \setR$ par :

#+BEGIN_CENTER
\(
\phi(x) = \Re(u(x)) \\
\psi(x) = \Im(u(x)) \\
\)
#+END_CENTER

L'intégrale de la fonction $u$ est alors définie par :

$$\int_A u(x) \ d\mu(x) = \int_A \phi(x) \ d\mu(x) + \img \int_A \psi(x) \ d\mu(x)$$


** Produit scalaire

Par analogie avec le produit scalaire sur $\corps^n$ :

$$\scalaire{x}{y} = \sum_i \conjaccent{x}_i \cdot y_i \equiv \sum_i \conjaccent{x}(i) \cdot y(i)$$

on définit le produit scalaire entre deux fonctions $u,v : A \mapsto \setC$ par :

$$\scalaire{u}{v} = \int_A \conjaccent{u(x)} \cdot v(x) \ d\mu(x)$$

Cette application est clairement hermitienne et linéaire à droite. Comme l'intégrale d'une fonction positive est positive, on a aussi :

$$\scalaire{u}{u} = \int_A \abs{u(x)}^2 \ d\mu(x) \ge 0$$

Il ne s'agit cependant pas tout à fait d'un produit scalaire, car la condition :

$$\scalaire{u}{u} = \int_A \abs{u(x)}^2 \ d\mu(x) = 0$$

n'implique pas que $u = 0$ partout sur $A$. Par contre, l'annulation de cette intégrale implique que la fonction positive $x \mapsto \abs{u(x)}^2$ soit essentiellement nulle. On aura donc également $u \essegal 0$. L'application $\scalaire{}{}$ est donc essentiellement un produit scalaire. On parlera aussi de produit scalaire au sens faible. La norme essentielle (ou norme faible) associée est :

$$\norme{u} = \sqrt{ \scalaire{u}{u} } = \sqrt{ \int_A \abs{u(x)}^2 \ d\mu(x) }$$

Sur quel espace ce « produit scalaire » est-il correctement défini ? Il faut que la norme associée soit finie :

$$\norme{u}^2 = \scalaire{u}{u} = \int_A \abs{u(x)}^2 \ d\mu(x) \strictinferieur +\infty$$

Si les normes de $u$ et $v$ sont finies, Cauchy-Schwartz nous garantit que :

$$\abs{\int_A \conjaccent{u(x)} \cdot v(x) \ d\mu(x)} \le \left[ \int_A \abs{u(x)}^2 \ d\mu(x) \right] \cdot \left[ \int_A \abs{v(x)}^2 \ d\mu(x) \right] \strictinferieur +\infty$$

Nous définissons donc notre produit scalaire fonctionnel sur l'espace :

$$\lebesgue^2(A) = \left\{ u \in \setC^A : \int_A \abs{u(x)}^2 \ d\mu(x) \strictinferieur +\infty \right\}$$

nommé espace de Lebesgue de degré $2$.


** Espaces de Lebesgue

L'espace de Lebesgue de degré $k$ est l'ensemble des fonctions telles que l'intégrale
de la puissance $k$ existe (et ne soit donc pas infinie) :

$$\lebesgue^k(A,B) = \left\{ u \in \setC^A : \int_A \abs{u(x)}^k \ d\mu(x) \strictinferieur +\infty \right\}$$


*** Norme

La norme usuelle sur cet espace est définie par :

$$\norme{u}_k = \left[ \int_A \abs{u(x)}^k \ dx \right]^{1/k}$$

Il s'agit d'une norme faible.


** Espace de fonctions essentiellement bornées

Par analogie avec la norme « max », on définit l'espace des fonctions essentiellement bornées par :

$$\lebesgue^\infty(A,B) = \left\{ u \in \setR^A : \supessentiel \{ \abs{u(x)} : x \in A \} \strictinferieur +\infty \right\}$$


** Noyau

On peut généraliser le produit scalaire usuel de $\lebesgue^2(A,B)$ en généralisant la notion de « matrice de produit scalaire ». On choisit une fonction $K : A^2 \to B$ appelée « noyau » et on définit le produit scalaire associé :

$$\braket{u}{K}{v} = \scalaire{u}{v}_K = \int_{A^2} u(x) \cdot K(x,y) \cdot v(y) \ d\mu(x) \ d\mu(y)$$

Ce noyau doit bien entendu respecter certaines propriétés afin de s'assurer que $\scalaire{}{}_K$ soit bien un produit scalaire.


* Convergence et intégration

#+TOC: headlines 1 local

\label{chap:convint}


** Convergence monotone

Soit une suite de fonctions intégrables :

$$\{ u_n \in \setR^A : n \in \setR \}$$

Nous supposons que $u_n \esssuperieur 0$ pour tout $n \in \setN$ et que la suite soit essentiellement croissante :

$$u_0 \essinferieur u_1 \essinferieur u_2 \essinferieur u_3 \essinferieur ...$$

Nous supposons également que la fonction :

$$s = \sup \{ u_n : n \in \setN\}$$

est bien définie et intégrable :

$$S = \int_A s(x) \ d\mu(x) \strictinferieur +\infty$$


*** Convergence des fonctions

Pour tout $n \in \setN$, on a $u_n \essinferieur u_{n + 1}$ et l'ensemble :

$$Z_n = \{ x \in A : u_n(x) \strictsuperieur u_{n + 1}(x) \}$$

est de mesure nulle. Il en va donc de même pour leur union :

$$Z = \bigcup_n Z_n$$

L'ensemble $\Phi = A \setminus Z$ est donc un sous-ensemble essentiel de $A$. Soit $x \in \Phi$. On a alors :

$$u_0(x) \le u_1(x) \le u_2(x) \le ...$$

La suite $\{ u_n(x) : n \in \setN \}$ est donc croissante et majorée par $s(x) = \sup_n u_n(x)$. Elle converge dès lors vers son supremum :

$$\lim_{n \to \infty} u_n(x) = s(x)$$


*** Suite d'intégrales

On définit la suite $\{ I_n : n \in \setN \}$ par :

$$I_n = \int_A u_n(x) \ d\mu(x)$$

pour tout $n \in \setN$. Comme $u_n$ croît essentiellement avec $n$, on a $I_m \le I_n$ pour tout $m,n \in \setN$ vérifiant $m \le n$. Comme $u_n \le s$, on a aussi $I_n \le S$. On en conclut que la suite des $I_n$ converge vers son supremum et que :

$$L = \lim_{n \to \infty} I_n \le S = \int_A s(x) \ d\mu(x)$$


*** Fonction étagée

Soit le réel $\epsilon \strictsuperieur 0$. Choisissons $w \in \mathcal{E}_A(s)$ telle que :

$$\int_A s(x) \ d\mu(x) \le \int_A w(x) \ d\mu(x) + \epsilon$$

Comme $w \essinferieur s$ l'ensemble :

$$N = \{ x \in A : w(x) \strictsuperieur s(x) \}$$

est de mesure nulle. Posons $\Psi = \Phi \setminus N$. La fonction $w$ étant étagée, on dispose d'une partition $\{A_1,...,A_N\}$ de $A$ et de réels $w_i$ tels que :

$$w = \sum_i w_i \cdot \indicatrice[A_i]$$

Posons $\Psi_i = A_i \cap \Psi$. Comme $\Psi \subseteq A$, les $\Psi_i$ forment une partition de $\Psi$ et on a :

$$w \cdot \indicatrice[\Psi] = \sum_i w_i \cdot \indicatrice[A_i] \cdot \indicatrice[\Psi] = \sum_i w_i \cdot \indicatrice[\Psi_i]$$

On en déduit que :

$$\int_\Psi w(x) \ d\mu(x) = \int_A w(x) \cdot \indicatrice_\Psi(x) \ d\mu(x) = \sum_i w_i \cdot \mu(\Psi_i)$$

L'intégrale étant invariante par abstraction d'un ensemble de mesure nulle, on a :

$$\int_\Psi w(x) \ d\mu(x) = \int_\Phi w(x) \ d\mu(x) = \int_A w(x) \ d\mu(x)$$

et finalement :

$$\int_A w(x) \ d\mu(x) = \sum_i w_i \cdot \mu(\Psi_i)$$


*** Mesures convergentes

Choisissons un réel $\alpha$ vérifiant $0 \strictinferieur \alpha \strictinferieur 1$ et posons :

$$C_n = \{ x \in \Psi : \alpha \cdot w(x) \le u_n(x) \}$$

Soit :

\begin{align}
W_n^i &= C_n \cap \Psi_i = \{ x \in \Psi_i : \alpha \cdot w(x) \le u_n(x) \} \\
X_n^i &= Z_n \cap \Psi_i = \{ x \in \Psi_i : u_n(x) \strictsuperieur u_{n + 1}(x) \}
\end{align}

Comme $X_n^i \subseteq Z_n$, on a $\mu(X_n^i) = 0$. Si $x \in W_n^i \setminus X_n^i$, on a :

$$\alpha \cdot w(x) \le u_n(x) \le u_{n + 1}(x)$$

On en déduit que $x \in W_{n + 1}^i$. Donc $W_n^i \setminus X_n^i \subseteq W_{n + 1}^i$ et :

$$\lim_{n \to \infty} \mu(W_n^i) = \mu\left( \bigcup_n W_n^i \right)$$

Comme les $W_n^i \subseteq \Psi_i$, il est clair que leur union sur $n$ est inclue dans $\Psi_i$. Soit $x \in \Psi_i$.

  - Si $s(x) = 0$, on a $0 \le u_n(x) \le s(x) = 0$ pour tout $n \in \setN$ et $u_n(x) = 0$. On a aussi $w(x) \le s(x) = 0$, d'où $\alpha \cdot w(x) \le 0 = u_n(x)$ et $x \in W_n^i$.

  - Considérons à présent le cas où $s(x) \strictsuperieur 0$. On se rappelle que $\Psi_i \subseteq \Psi = \Phi \setminus N$. Donc $x \notin N$ et on a $w(x) \le s(x)$. Multipliant cette relation par $\alpha \strictsuperieur 0$, on obtient $\alpha \cdot w(x) \le \alpha \cdot s(x)$. Soit le réel :

$$\delta = (1 - \alpha) \cdot s(x) \strictsuperieur 0$$

Sur $\Psi_i \subseteq \Psi \subseteq \Phi$, la suite des $\{ u_n(x) : n \in \setN \}$ converge vers $s(x)$. On peut donc trouver un $K \in \setN$ tel que $\abs{u_n(x) - s(x)} \le \delta$ pour tout naturel $n$ vérifiant $n \ge K$. On a alors :

$$u_n(x) \ge s(x) - \delta = s(x) - (1 - \alpha) \cdot s(x) = \alpha \cdot s(x) \ge \alpha \cdot w(x)$$

Il existe donc un naturel $n$ tel que $x \in C_n$, d'où $x \in C_n \cap \Psi_i = W_n^i$.

Notre $x$ appartient donc à l'union sur $n$ des $W_n^i$. On en conclut que $\Psi_i$ est inclu dans l'union sur $n$ des $W_n^i$. La réciproque étant également vraie, on a :

$$\bigcup_n W_n^i = \Psi_i$$

et :

$$\lim_{n \to \infty} \mu(W_n^i) = \mu(\Psi_i)$$


*** Convergence des intégrales

Fixons $n \in \setN$. Comme $C_n \subseteq A$, les $W_n^i = C_n \cap \Psi_i$ forment une partition de $C_n$ et on a :

$$w \cdot \indicatrice[C_n] = \sum_i w_i \cdot \indicatrice[C_n] \cdot \indicatrice[\Psi_i] = \sum_i w_i \cdot \indicatrice[W_n^i]$$

On en déduit que :

$$\int_{C_n} w(x) \ d\mu(x) = \int_A w(x) \cdot \indicatrice_{C_n}(x) \ d\mu(x) = \sum_i w_i \cdot \mu(W_n^i)$$

En passant à la limite sur $n$, on obtient donc :

\begin{align}
\lim_{n \to \infty} \int_{C_n} w(x) \ d\mu(x) &= \sum_i w_i \cdot \lim_{n \to \infty} \mu(W_n^i) \\
&= \sum_i w_i \cdot \mu(\Psi_i) \\
&= \int_A w(x) \ d\mu(x)
\end{align}

Comme $\alpha \cdot w \le u_n$ sur $C_n$, on a a fortiori l'infériorité essentielle et :

$$\int_{C_n} \alpha \cdot w(x) \ d\mu(x) = \alpha \int_{C_n} w(x) \ d\mu(x) \le \int_A u_n(x) \ d\mu(x) = I_n$$

En passant à la limite sur $n$ et en multipliant par $1/\alpha$, on en déduit que :

$$\int_A w(x) \ d\mu(x) \le \unsur{\alpha} \lim_{n \to \infty} I_n = \frac{L}{\alpha}$$

Se rappelant la propriété de $w$ par rapport à $s$, on a :

$$\int_A s(x) \ d\mu(x) - \epsilon \le \int_A w(x) \ d\mu(x) \le \frac{L}{\alpha}$$

Donc :

$$S - \epsilon = \int_A s(x) \ d\mu(x) - \epsilon \le \frac{L}{\alpha}$$

Ce résultat devant être satisfait pour tout $\epsilon \strictsuperieur 0$ et pour tout $0 \strictsuperieur \alpha \strictsuperieur 1$, on a finalement $S \le L$. Mais nous avons vu précédemment que $L \le S$. On en conclut que $S = L$, c'est-à-dire :

$$\int_A \lim_{n \to \infty} u_n(x) \ d\mu(x) = \lim_{n \to \infty} \int_A u_n(x) \ d\mu(x)$$


** Convergence des sommes

Soit une suite $\{ f_n \in \setR^A : n \in \setN \}$ de fonctions intégrables essentiellement positives. Posons :

$$u_n = \sum_{i = 0}^n f_i$$

On voit que la suite des $u_n$ est croissante et essentiellement positive. Si la somme converge, on a :

$$\lim_{n \to \infty} u_n(x) = \sum_{i = 0}^{+\infty} f_i(x) = s(x)$$

pour tout $x \in A$. Si la fonction $s$ ainsi définie est intégrable, on a donc :

$$\int_A \sum_{i = 0}^{+\infty} f_i(x) \ d\mu(x) = \lim_{n \to \infty} \int_A \sum_{i = 0}^n f_i(x) \ d\mu(x)$$


** Lemme de Fatou

Soit une suite $\{ f_n \in \setR^A : n \in \setN \}$ de fonctions intégrables essentiellement positives. Posons :

$$u_n = \inf \{ f_m : m \in \setN, \  m \ge n \}$$

et supposons que la fonction $s = \sup_n u_n$ soit bien définie et intégrable. Par construction, la suite des $u_n$ est croissante et essentiellement positive. On a donc $\int_A \lim_n u_n = \lim_n \int_A u_n$, c'est-à-dire :

$$\int_A \liminf_{n \to \infty} f_n(x) \ d\mu(x) = \lim_{n \to \infty} \int_A u_n(x) \ d\mu(x)$$

Comme la limite des $U_n = \int_A u_n$ existe, on a $\liminf_n U_n = \lim_n U_n$ et :

$$\int_A \liminf_{n \to \infty} f_n(x) \ d\mu(x) = \liminf_{n \to \infty} \int_A u_n(x) \ d\mu(x)$$

Comme $u_n \le f_n$, on a $U_n \le F_n = \int_A f_n$. On en conclut que $\liminf_n U_n \le \liminf_n F_n$ :

$$\liminf_{n \to \infty} \int_A u_n(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

Rassemblant ces résultats, il vient :

$$\int_A \liminf_{n \to \infty} f_n(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$


** Convergence dominée

Soit une suite de fonctions $\{ f_n : n \in \setN \}$ intégrables sur $\Omega$. Nous supposons qu'il existe un sous-ensemble essentiel $A$ de $\Omega$ et une fonction $f : A \mapsto \setR$ telle que :

$$\lim_{n \to \infty} f_n(x) = f(x)$$

pour tout $x \in A$. Nous supposons également qu'il existe une fonction intégrable $\varphi : A \mapsto \setR$ telle que $\abs{f_n} \le \varphi$ pour tout $n \in \setN$.

Soit $x \in A$. Puisque la suite $\{ \abs{f_n(x)} : n \in \setN \}$ est inférieure à $\varphi(x)$, sa limite $\abs{f(x)}$ vérifie $\abs{f(x)} \le \varphi(x)$. On a donc $\abs{f} \le \varphi$ et $\int_A \abs{f} \le \int_A \varphi \strictinferieur +\infty$, ce qui montre que $f$ est intégrable. La majoration par $\varphi$ nous montre également que $\varphi - \max \{ f_n , -f_n \} \ge 0$, d'où :

#+BEGIN_CENTER
\(
\varphi - f_n \ge 0 \\
\varphi + f_n \ge 0
\)
#+END_CENTER

On peut donc appliquer le lemme de Fatou à la suite de fonctions $\psi_n = \varphi - f_n$. On obtient :

$$\int_A \liminf_{n \to \infty} [\varphi(x) - f_n(x)] \ d\mu(x) \le \liminf_{n \to \infty} \int_A [\varphi(x) - f_n(x)] \ d\mu(x)$$

On sait que la fonction $\varphi$ ne dépend pas de $n$ et que la limite de $f_n$ existe. On a donc $\liminf_n f_n = \limsup_n f_n = \lim f_n$. Comme $\inf(-X) = -\sup(X)$, on a aussi :

$$\liminf_n (-f_n) = - \limsup_n f_n = - \lim_n f_n = -f$$

On en déduit que :

$$\int_A \liminf_n [\varphi - f_n] = \int_A \varphi - \int_A f$$

Pour le second membre, on a :

$$\liminf_n \int_A [\varphi - f_n] = \int_A \varphi + \liminf_n \left[ - \int_A f_n \right] = \int_A \varphi - \limsup_n \int_A f_n$$

On se retrouve donc avec l'inégalité :

$$\int_A \varphi - \int_A f \le \int_A \varphi - \limsup_n \int_A f_n$$

Eliminant l'intégrale de $\varphi$, il vient :

$$\int_A f(x) \ d\mu(x) \ge \limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

Appliquons à présent le lemme de Fatou à la suite de fonctions $\omega_n = \varphi + f_n$. On obtient :

$$\int_A \liminf_{n \to \infty} [\varphi(x) + f_n(x)] \ d\mu(x) \le \liminf_{n \to \infty} \int_A [\varphi(x) + f_n(x)] \ d\mu(x)$$

Utilisant les mêmes remarques que précédemment et éliminant l'intégrale de $\varphi$, il vient :

$$\int_A f(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

Rassemblant ces résultats, on en déduit que :

$$\limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x) \le \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

Mais on sait que $\liminf(X) \le \limsup(X)$. On conclut de ces deux inégalités que :

$$\limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x) = \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

La limite de la suite d'intégrales existe donc et :

$$\lim_{n \to \infty} \int_A f_n(x) \ d\mu(x) = \limsup_{n \to \infty} \int_A f_n(x) \ d\mu(x) = \liminf_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

Les bornes faisant intervenir l'intégrale de $f$ deviennent :

$$\lim_{n \to \infty} \int_A f_n(x) \ d\mu(x) \le \int_A f(x) \ d\mu(x) \le \lim_{n \to \infty} \int_A  f_n(x) \ d\mu(x)$$

d'où :

$$\int_A f(x) \ d\mu(x) = \lim_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

Nous venons de prouver que :

$$\int_A \lim_{n \to \infty} f_n(x) \ d\mu(x) = \lim_{n \to \infty} \int_A f_n(x) \ d\mu(x)$$

L'intégrale étant invariante sous abstraction d'un ensemble de mesure nulle, on a même :

$$\int_\Omega f(x) \ d\mu(x) = \lim_{n \to \infty} \int_\Omega f_n(x) \ d\mu(x)$$

pour autant que $f$ soit définie sur $\Omega$.
