
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 11 : Équations différentielles - 3
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Fonctions trigonométriques

#+TOC: headlines 1 local


** Dépendances


  - Chapitre \ref{chap:complexe} : Les complexes



** Introduction

Les fonctions trigonométriques cosinus ($\cos$), sinus ($\sin$) et associées peuvent se définir
à partir des rotations dans le plan $\setR^2$. Pour cela, commençons par définir ce qu'est
une rotation. Soit la fonction :

$$Q : \setR\mapsto \matrice(\setR, 2, 2), \qquad \theta \mapsto Q(\theta)$$

qui associe à chaque valeur de l'angle de rotation $\theta \in \setR$ une matrice carrée réelle représentant une rotation dans le plan $\setR^2$.


** Angle nul

Il semble logique de demander qu'une rotation d'angle $0$ d'un vecteur ne modifie pas ce vecteur, c'est-à-dire :

$$Q(0) = I$$


** Produit scalaire

Une rotation doit conserver les angles entre les vecteurs, ainsi que leur norme. Autrement dit, le produit scalaire sur $\setR^2$ :

$$\scalaire{x}{y} = x^\dual \cdot y$$

doit être conservé :

$$\scalaire{Q(\theta) \cdot x}{Q(\theta) \cdot y} = \scalaire{x}{y}$$

pour tout $x,y\in\setR^2$, c'est-à-dire :

$$(Q(\theta) \cdot x)^\dual \cdot (Q(\theta) \cdot y) = x^\dual \cdot Q(\theta)^\dual \cdot Q(\theta) \cdot y = x^\dual \cdot y$$

On en déduit que :

$$Q(\theta)^\dual \cdot Q(\theta) = I$$

Comme $Q(\theta)$ est carrée, on a :

$$Q(\theta)^\dual  = Q(\theta)^{-1}$$

où le $^{-1}$ désigne l'inverse matriciel. Quelques calculs suffisent à nous montrer que pour satisfaire cette condition, la forme de la matrice doit être l'une des deux solutions suivantes :

#+BEGIN_CENTER
\(
\begin{Matrix}{cc}
\cos(\theta) & -\sin(\theta) \\
\sin(\theta) & \cos(\theta)
\end{Matrix}
\qquad\mathrm{ou}\qquad
\begin{Matrix}{cc}
\cos(\theta) & \sin(\theta) \\
\sin(\theta) & -\cos(\theta)
\end{Matrix}
\)
#+END_CENTER

où $\cos, \sin : \setR \mapsto \setR$ sont des fonctions à déterminer vérifiant la relation fondamentale :

$$\cos(\theta)^2 + \sin(\theta)^2 = 1$$

Mais comme $Q(0)=I$, l'élément $(1,1)$ de la matrice doit être identique à l'élément
$(2,2)$ et on a :

#+BEGIN_CENTER
\(
Q(\theta) =
\begin{Matrix}{cc}
\cos(\theta) & -\sin(\theta) \\
\sin(\theta) & \cos(\theta)
\end{Matrix}
\)
#+END_CENTER

avec :

#+BEGIN_CENTER
\(
\cos(0) = 1 \\
\sin(0) = 0
\)
#+END_CENTER


*** Relation fondamentale et bornes

Soit $x \in \setR$. Comme les fonctions $\cos$ et $\sin$ sont à valeurs dans $\setR$, on a :

#+BEGIN_CENTER
\(
\cos(x)^2 \ge 0 \\
\sin(x)^2 \ge 0
\)
#+END_CENTER

On déduit de la relation fondamentale :

$$\cos(x)^2 + \sin(x)^2 = 1$$

les inégalités :

\begin{align}
\cos(x)^2 = 1 - \sin(x)^2 \le 1 \\
\sin(x)^2 = 1 - \cos(x)^2 \le 1
\end{align}

On en déduit les bornes :

#+BEGIN_CENTER
\(
-1 \le \cos \le 1 \\
-1 \le \sin \le 1
\)
#+END_CENTER


** Différentielle

Posons $x = \cos(\theta)$ et $y = \sin(\theta)$. En différentiant la condition :

$$x^2 + y^2 = 1$$

on obtient :

$$2 \ x \ dx + 2 \ y \ dy = 0$$

En particulier, si $(x,y) = (1,0)$, le vecteur $(dx,dy)$ doit être
de la forme :

#+BEGIN_CENTER
\(
dx = 0 \\
dy = \delta
\)
#+END_CENTER

Une rotation infinitésimale doit donc modifier le vecteur $(1,0)$ en :

$$(1,0)+(dx,dy)=(1,\delta)$$

On en conclut que :

#+BEGIN_CENTER
\(
Q(\delta) \cdot
\begin{Matrix}{c}
1 \\
0
\end{Matrix} \approx
\begin{Matrix}{c}
1 \\
\delta
\end{Matrix}
\)
#+END_CENTER

Compte tenu des propriétés de symétrie de $Q(\delta)$, on a donc :

#+BEGIN_CENTER
\(
Q(\delta) \approx
\begin{Matrix}{cc}
1 & -\delta \\
\delta & 1
\end{Matrix}
\)
#+END_CENTER

lorsque $\delta$ suffisamment proche de $0$. Plus précisément, on a :

#+BEGIN_CENTER
\(
Q(\delta) =
\begin{Matrix}{cc}
1 & -\delta \\
\delta & 1
\end{Matrix}
+
\begin{Matrix}{cc}
E_{11} & E_{12} \\
E_{21} & E_{22}
\end{Matrix}
\)
#+END_CENTER

On impose que les valeurs absolues des composantes de l'erreur convergent plus vite vers zéro que $\delta$ :

$$\lim_{\delta\to 0} \frac{\abs{E_{ij}(\delta)}}{\delta} = 0$$

D'après la forme des matrices, il est clair que :

#+BEGIN_CENTER
\(
E_{11} = E_{22} \\
E_{12} = -E_{21}
\)
#+END_CENTER

On en déduit qu'il suffit de vérifier la convergence des composantes $(1,1)$ et $(2,1)$. La première nous dit que :

$$\lim_{\delta\to 0} \frac{\cos(\delta) - 1}{\delta} = 0$$

et la seconde :

$$\lim_{\delta\to 0} \frac{\sin(\delta)-\delta}{\delta} = 0$$

ou :

$$\lim_{\delta\to 0} \frac{\sin(\delta)}{\delta} = 1$$


** Additivité

Une rotation d'angle $\theta_1$ suivie d'une rotation d'angle $\theta_2$ doit
donner le même résultat qu'une rotation directe d'angle $\theta_1+\theta_2$, ce qui s'écrit :

$$Q(\theta_1+\theta_2) = Q(\theta_2) \cdot Q(\theta_1)$$

On en déduit directement que :

$$Q(\theta) \cdot Q(-\theta) = Q(\theta - \theta) = Q(0) = I$$

Comme $Q(\theta)$ est carrée, on a :

$$Q(-\theta) = Q(\theta)^{-1} = Q(\theta)^\dual$$

Au niveau des composantes, la propriété d'additivité implique que :

#+BEGIN_CENTER
\(

\begin{Matrix}{cc}
\cos(\theta_2) & -\sin(\theta_2) \\
\sin(\theta_2) & \cos(\theta_2)
\end{Matrix}

\cdot

\begin{Matrix}{cc}
\cos(\theta_1) & -\sin(\theta_1) \\
\sin(\theta_1) & \cos(\theta_1)
\end{Matrix}

=

\begin{Matrix}{cc}
\cos(\theta_1+\theta_2) & -\sin(\theta_1+\theta_2) \\
\sin(\theta_1+\theta_2) & \cos(\theta_1+\theta_2)
\end{Matrix}

\)
#+END_CENTER

En effectuant le produit matriciel et en comparant composante par composante, on obtient
les formules suivantes :

#+BEGIN_CENTER
\(
\cos(\theta_1+\theta_2) = \cos(\theta_1) \ \cos(\theta_2)-\sin(\theta_1) \ \sin(\theta_2) \\
\sin(\theta_1+\theta_2) = \sin(\theta_1) \ \cos(\theta_2)+\cos(\theta_1) \ \sin(\theta_2)
\)
#+END_CENTER


** Dérivées

La dérivée de la fonction $\cos$ s'écrit :

$$\OD{\cos}{\theta}(\theta) = \lim_{\delta\to 0} \frac{ \cos(\theta+\delta)-\cos(\theta)  }{  \delta } \\$$

En appliquant les formules d'additivité ci-dessus avec $\theta_1 = \theta$ et $\theta_2  = \delta$,
et en se rappelant les propriétés des fonctions $\cos$ et $\sin$ pour des angles $\delta\to 0$,
on obtient :

\begin{align}
\OD{\cos}{\theta}(\theta)
&= \lim_{\delta\to 0} \frac{ \cos(\theta) \ \cos(\delta) - \sin(\theta) \ \sin(\delta) - \cos(\theta) }{ \delta } \\
&= \lim_{\delta\to 0} \frac{ \cos(\theta) \ (\cos(\delta) - 1) - \sin(\theta) \ \sin(\delta) }{ \delta } \\
&= -\sin(\theta)
\end{align}

La dérivée de la fonction $\sin$ s'écrit :

$$\OD{\sin}{\theta}(\theta) = \lim_{\delta\to 0} \frac{\sin(\theta+\delta)-\sin(\theta)}{\delta} \\$$

En procédant comme précédemment, on arrive à :

\begin{align}
\OD{\sin}{\theta}(\theta)
&= \lim_{\delta\to 0} \frac{\sin(\theta) \ \cos(\delta) + \cos(\theta) \ \sin(\delta) - \sin(\theta)}{\delta} \\
&= \lim_{\delta\to 0} \frac{\sin(\theta) \ (\cos(\delta) - 1) + \cos(\theta) \ \sin(\delta)}{\delta} \\
&= \cos(\theta)
\end{align}

On a donc :

#+BEGIN_CENTER
\(
\OD{\cos}{\theta}(\theta) = -\sin(\theta) \\ \\
\OD{\sin}{\theta}(\theta) = \cos(\theta)
\)
#+END_CENTER


** Équations différentielles

La dérivée seconde de la fonction $\cos$ s'écrit :

$$\OOD{\cos}{\theta}(\theta) = \OD{(-\sin)}{\theta}(\theta) = -\cos(\theta)$$

On a aussi $\cos(0) = 1$ et :

$$\OD{\cos}{\theta}(0) = -\sin(0) = 0$$

La fonction $\cos$ est donc l'unique solution $u : \setR \mapsto \setR$ du problème différentiel :

\begin{align}
\partial^2 u(t) &= -u(t) \\
u(0) &= 1 \\
\partial u(0) &= 0
\end{align}

vérifié pour tout $t \in \setR$. La dérivée seconde de la fonction $\sin$ s'écrit :

$$\OOD{\sin}{\theta}(\theta) = \OD{\cos}{\theta}(\theta) = -\sin(\theta)$$

On a aussi $\sin(0) = 0$ et :

$$\OD{\sin}{\theta}(0) = \cos(0) = 1$$

La fonction $\sin$ est donc l'unique solution $v : \setR \mapsto \setR$ du problème différentiel :

\begin{align}
\partial^2 v(t) &= -v(t) \\
v(0) &= 0 \\
\partial v(0) &= 1
\end{align}

vérifié pour tout $t \in \setR$.


** Racines

Nous allons maintenant nous occuper du problème des éventuelles racines
des fonctions trigonométriques. Soit :

#+BEGIN_CENTER
\(
u(t) = \cos(t) \\
v(t) = \sin(t)
\)
#+END_CENTER

La fonction $u$ vérifie :

#+BEGIN_CENTER
\(
u(0) = 1 \\
\partial u = -v
\)
#+END_CENTER

La fonction $v$ vérifie :

#+BEGIN_CENTER
\(
v(0) = 0 \\
\partial v = u
\)
#+END_CENTER

Soit $\varphi$ l'infimum des réels positifs donnant une valeur négative à la fonction $u$ :

$$\varphi = \inf\{ x \in \setR : x \ge 0, \ u(x) < 0  \}$$

Nous allons montrer que $\varphi$ est un réel, c'est-à-dire que $\varphi < +\infty$. Le théorème
fondamental du calcul différentiel et intégral nous dit que :

#+BEGIN_CENTER
\(
u(t) - u(0) = \int_0^t \OD{u}{t}(s) \ ds \\
v(t) - v(0) = \int_0^t \OD{v}{t}(s) \ ds
\)
#+END_CENTER

En tenant compte des propriétés de $u, v$, ces relations se réécrivent :

#+BEGIN_CENTER
\(
u(t) - 1 = - \int_0^t v(s) ds \\
v(t) - 0 = \int_0^t u(s) ds
\)
#+END_CENTER

On a donc :

#+BEGIN_CENTER
\(
u(t) = 1 - \int_0^t v(s) ds \\
v(t) = \int_0^t u(s) ds
\)
#+END_CENTER

Comme $u$ est dérivable, elle est continue et on peut trouver un $\epsilon\in \intervalleouvert{0}{\varphi}$ tel que, pour tout $t\in \intervalleouvert{0}{\epsilon}$ :

$$\abs{u(t)-u(0)} = \abs{u(t) - 1} \strictinferieur 1$$

On en déduit que :

$$1 - u(t) \strictinferieur 1$$

c'est-à-dire :

$$u(t) \strictsuperieur 0$$

La positivité de $u$ entraîne celle de $v$ :

$$v(t) = \int_0^t u(s) ds > 0$$

pour tout $t \in \intervalleouvert{0}{\epsilon}$.

Pour $t\in \intervalleouvert{\epsilon}{\varphi}$, la définition de $\varphi$ nous dit que $u \ge 0$ sur $\intervalleouvert{0}{\varphi}$ et donc :

\begin{align}
v(t) &= \int_0^t u(s) ds = \int_0^\epsilon u(s) ds  + \int_\epsilon^t u(s) ds \\
&\ge \int_0^\epsilon u(s) ds > 0
\end{align}

On pose :

$$\delta = \int_0^\epsilon u(s) ds$$

pour alléger les notations. Toujours avec $t \in \intervalleouvert{\epsilon}{\varphi}$, il vient :

\begin{align}
u(t) &= 1 - \int_0^t v(s) ds \le 1 - \int_\epsilon^t v(s) ds \\
&\le 1 - (t-\epsilon) \ \delta
\end{align}

On peut donc trouver $t$ tel que $u(t) \le 0$. En effet, l'égalité :

$$1 - (t-\epsilon) \ \delta = 0$$

est équivalente à :

$$t = \unsur{\delta} + \epsilon < +\infty$$

donc :

$$u\left(\unsur{\delta} + \epsilon\right) \le 0$$

Comme $u$ est continue, elle ne peut pas devenir négative sans
passer par $0$ et il existe au moins un :

$$\psi \le \unsur{\delta} + \epsilon$$

tel que $u(\psi) = 0$. Donc :

$$\varphi \le \unsur{\delta} + \epsilon < +\infty$$


** Périodicité

Nous allons à présent montrer d'importantes propriétés de périodicité des fonctions trigonométriques. Considérons la plus petite racine positive de $u$ :

$$\psi = \min\{ x \ge 0 : u(x) = 0 \}$$

Vu que $u^2+v^2 = 1$, on doit avoir $v(\psi)^2 = 1 - u(\psi)^2 = 1$.
Donc $v(\psi)=\pm 1$. Mais $v \ge \delta > 0$ sur l'intervalle $(\epsilon,\psi)$
et par continuité :

$$v(\psi) = \lim_{x\to\psi} v(x) \ge 0$$

La seule solution acceptable est donc $v(\psi) = 1$. Donc $v$
est solution du problème :

#+BEGIN_CENTER
\(
\OOD{v}{t} = -v \\
v(\psi) = 1 \\
\OD{v}{t}(\psi) = 0
\)
#+END_CENTER

Mais la fonction définie par $f(t) = u(t-\psi)$ vérifie également ce problème.
Par unicité, on en déduit :

$$u(t-\psi) = v(t)$$

En particulier, en $t = 2 \psi$, on a :

$$v(2\psi) = u(\psi) = 0$$

Donc $u(2\psi)^2 = 1 - v(2\psi)^2 = 1$. Quel est le signe de $u(2\psi)$ ?
Choisissons $s\in [\psi,2\psi]$ et $t = s-\psi \in [0,\psi]$. On a :

$$v(s) = u(t) \ge 0$$

par définition de $\psi$ et continuité de $u$ (la fonction de peut pas devenir
négative avant de passer par $0$). Donc :

$$u(t) = -\int_\psi^t v(s) ds \le 0$$

et par continuité  $u(2\psi) = -1$. Par unicité de la solution de :

#+BEGIN_CENTER
\(
\OOD{}{t}(-u) = -(-u) \\
-u(0) = -1 \\
\OD{}{t}(-u)(0) = 0
\)
#+END_CENTER

on a :

$$u(t-2\psi) = -u(t)$$

Répétant le même procédé, on obtient successivement :

#+BEGIN_CENTER
\(
u(0) = 1 \qquad v(0) = 0 \\
u(\psi) = 0 \qquad v(\psi) = 1 \\
u(2\psi) = -1 \qquad v(2\psi) = 0 \\
u(3\psi) = 0 \qquad v(3\psi) = -1 \\
u(4\psi) = 1 \qquad v(4\psi) = 0
\)
#+END_CENTER


*** Extension

Donc $u(4\psi) = u(0)$ et $v(4\psi) = v(0)$. On en déduit
que $Q(4\psi)=Q(0)=I$. Mais, par additivité des rotations,

$$Q(t + 4\psi) = Q(t) \ Q(4\psi) = Q(t)$$

Et donc :

#+BEGIN_CENTER
\(
u(t+4\psi) = u(t) \\
v(t+4\psi) = v(t)
\)
#+END_CENTER

pour tout $t\in\setR$. Définissant le nombre $\pi$ par :

$$\pi = 2\psi$$

on peut écrire la périodicité des fonctions trigonométriques :

#+BEGIN_CENTER
\(
\cos(\theta+2\pi) = \cos(\theta) \\
\sin(\theta+2\pi) = \sin(\theta)
\)
#+END_CENTER

On en déduit directement que :

#+BEGIN_CENTER
\(
\cos(\theta+2 k\pi) = ... = \cos(\theta) \\
\sin(\theta+2 k\pi) = ... = \sin(\theta)
\)
#+END_CENTER

pour tout $k\in\setZ$.


** Angle double

L'additivité nous donne :

$$\cos(2 \ x) = \cos(x + x) = \cos(x) \cdot \cos(x) - \sin(x) \cdot \sin(x)$$

On a donc :

$$\cos(2 \ x) = \cos(x)^2 - \sin(x)^2$$


*** Alternative

En utilisant :

$$\cos(x)^2 + \sin(x)^2 = 1$$

on dispose des formulations alternatives :

$$\cos(2 \ x) = 2 \cos(x)^2 - 1$$

et :

$$\cos(2 \ x) = 1 - 2 \sin(x)^2$$


*** Relations inverses

Il est aisé d'inverser ces deux relations, on a :

$$\cos(x)^2 = \frac{\cos(2 \ x) + 1}{2}$$

et :

$$\sin(x)^2 = \frac{1 - \cos(2 \ x)}{2}$$


** Intégrale

Comme $\sin$ est une primitive de $\cos$, on a :

$$\int_a^b \cos(t) \ dt = \sin(b) - \sin(a)$$

Comme $\cos$ est une primitive de $-\sin$, on a :

$$-\int_a^b \sin(t) \ dt = \cos(b) - \cos(a)$$

ou :

$$\int_a^b \sin(t) \ dt = \cos(a) - \cos(b)$$


** Tangente

La tangente $\tan$ est définie par :

$$\tan(x) = \frac{\sin(x)}{\cos(x)}$$

pour tout $x \in \setR$.


*** Dérivée

On a :

$$\OD{\tan}{x}(x) = \frac{\cos(x)}{\cos(x)} - \frac{\sin(x) \cdot \big(-\sin(x)\big)}{\cos(x)^2} = 1 + \tan(x)^2$$


*** Problème différentiel

Comme :

$$\tan(0) = \frac{\sin(0)}{\cos(0)} = \frac{0}{1} = 0$$

la tangente est solution $u : \setR \mapsto \setR$ du problème différentiel :

\begin{align}
\partial u(t) &= 1 + u(t)^2 \\
u(0) &= 0
\end{align}

vérifié pour tout $t \in \setR$.


** Angle entre vecteurs

Dans le cas où le produit scalaire est réel, on peut trouver un réel
$\theta\in [0,\pi]$ tel que :

$$-1 \le \cos(\theta) = \frac{ \scalaire{x}{y} }{ \norme{x}\ \norme{y} } \le 1$$

On dit alors que $\theta$ est l'angle formé par les deux vecteurs $x$ et $y$.


** Angles entre espaces

Autre application des valeurs singulières, les angles entres espaces vectoriels
générés par les vecteurs colonnes orthonormés des matrices :

#+BEGIN_CENTER
\(
X \in \matrice(\setR, k, n) \\
Y \in \matrice(\setR, l, n)
\)
#+END_CENTER

On a donc :

#+BEGIN_CENTER
\(
X^\dual \cdot X = I_k \\
Y^\dual \cdot Y = I_l
\)
#+END_CENTER

Les valeurs singulières de la matrice des produits scalaires :

$$Y^\dual \cdot X$$

nous donne les cosinus de ces angles.


** Coordonnées polaires

AFAIRE : CLARIFIER LA FIN DU CHAPITRE

Soit les vecteurs $(c_1,c_2)$ formant une base orthonormée de $\setR^2$ :

$$\scalaire{c_i}{c_j} = \delta_{ij}$$

et ne dépendant pas de la position :

$$\deriveepartielle{c_i}{x_j} = 0$$

Soit le changement de variable vers $y = (R,\theta)$, exprimé par :

#+BEGIN_CENTER
\(
x_1 = R \cdot \cos(\theta) \\
x_2 = R \cdot \sin(\theta)
\)
#+END_CENTER

#+BEGIN_CENTER
\(
r = x_1 \cdot c_1 + x_2 \cdot c_2 \\
dr = e_R \ dR + e_\theta \ d\theta
\)
#+END_CENTER

#+BEGIN_CENTER
\(
e_R = \deriveepartielle{r}{R} = \cos(\theta) \cdot c_1 + \sin(\theta) \cdot c_2 \\
e_\theta = \deriveepartielle{r}{\theta} = -R \cdot \sin(\theta) c_1 + R \cdot \cos(\theta) \cdot c_2
\)
#+END_CENTER

#+BEGIN_CENTER
\(
\deriveepartielle{e_R}{R} = 0 \\
\deriveepartielle{e_R}{\theta} = -\sin(\theta) \cdot c_1 + \cos(\theta) \cdot c_2 = \unsur{R} \cdot e_\theta \\
\deriveepartielle{e_\theta}{R} = -\sin(\theta) \cdot c_1 + \cos(\theta) \cdot c_2 = \unsur{R} \cdot e_\theta \\
\deriveepartielle{e_\theta}{\theta} = -R \cdot \cos(\theta) \cdot c_1 - R \cdot \sin(\theta) \cdot c_2 = -R \cdot e_R
\)
#+END_CENTER

#+BEGIN_CENTER
\(
de_R = \deriveepartielle{e_R}{R} \ dR + \deriveepartielle{e_R}{\theta} \ d\theta =
\unsur{R} \ d\theta \ e_\theta \\
de_\theta = \deriveepartielle{e_\theta}{R} \ dR + \deriveepartielle{e_\theta}{\theta} \ d\theta =
\unsur{R} \ dR \ e\theta - R \ d\theta
\)
#+END_CENTER

#+BEGIN_CENTER
\(
a = a^R \cdot e_R + a^\theta \cdot e_\theta \\
da = \deriveepartielle{a^R}{R} \cdot e_R \ dR + \left( \deriveepartielle{a^R}{\theta} - R \cdot a^\theta \right)  \cdot e_R \ d\theta + \\
\left( \deriveepartielle{a^\theta}{R} + \frac{a^\theta}{R} \right) \cdot e_\theta \ dR + \left( \deriveepartielle{a^\theta}{\theta} + \frac{a^R}{R} \right) \cdot e_\theta \ d\theta
\)
#+END_CENTER
