
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 04 : Suites - 3
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Produits

#+TOC: headlines 1 local

\label{chap:produits}


** Dépendances

  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes
  - Chapitre \ref{chap:somme} : Les sommes


** Introduction

Soit le corps $\corps$ sur lequel est défini une relation d'ordre total ainsi des opérations d'addition, de multiplication, de soustraction, de division et de puissance similaires à celles de $\setR$.

Soit un ensemble $\Omega$ et la fonction $f : \Omega \mapsto \corps$. On note le produit de $f$ sur $X$ par :

$$\prod_{x \in X} f(x)$$

pour tout sous-ensemble $X \subseteq \Omega$. Il s'agit intuitivement du produit des $f(x) \in \corps$ lorsque $x$ parcourt $X$. Nous allons voir comment le formaliser.


** Multiplicativité finie

Si deux ensembles $X,Y \subseteq \Omega$ ne se chevauchent pas :

$$X \cap Y = \emptyset$$

le produit sur l'union des deux est intuitivement le produit des produits sur chacun d'entre-eux :

$$\prod_{z \in X \cup Y} f(z) = \left[ \prod_{z \in X} f(z) \right] \cdot \left[ \prod_{z \in Y} f(z) \right]$$


** Ensemble vide

Comme $X = X \cup \emptyset$ et $X \cap \emptyset = \emptyset$, on en déduit que :

$$\prod_{x \in X} f(x) = \prod_{x \in X \cup \emptyset} f(x) = \prod_{x \in X} f(x) \cdot \prod_{x \in \emptyset} f(x)$$

Le produit sur l'ensemble vide doit donc être le neutre pour la multiplication :

$$\prod_{x \in \emptyset} f(x) = 1$$


** Singleton

Il semble également logique d'imposer que le produit sur un ensemble contenant un seul élément $a \in X$ soit égal à $f(a)$ :

$$\prod_{ x \in \{ a \} } f(x) = f(a)$$

Voilà qui complète les caractéristiques génériques des produits.


** Algorithme

Soit l'ensemble $X$ non vide, ensemble dont nous voulons évaluer le produit. Choisissons un élément $a \in A$ et considérons la décomposition :

$$X = \{ a \} \cup ( X \setminus \{ a \} )$$

Comme l'intersection des deux ensembles du membre de droite est vide :

$$\{ a \} \cap ( X \setminus \{ a \} ) = \emptyset$$

on peut écrire :

$$\prod_{x \in X} f(x) = \prod_{ x \in \{ a \} } f(x) \cdot \prod_{x \in X \setminus \{ a \} } f(x)$$

c'est-à-dire :

$$\prod_{x \in X} f(x) = f(a) \cdot \prod_{x \in X \setminus \{ a \} } f(x)$$

On en déduit un algorithme itératif permettant d'estimer le produit :

$$S \approx \prod_{x \in X} f(x)$$

Nous partons de :

#+BEGIN_CENTER
\(
S_0 = 0 \\
X_0 = X
\)
#+END_CENTER

A chaque étape $k$, nous choisissons $a_k \in X_k$ et nous adaptons notre estimation par :

$$S_{k + 1} = f(a_k) \cdot S_k$$

On retire ensuite $a_k$ de $X_k$ pour éviter de le compter plus d'une fois, ce qui nous donne l'ensemble suivant :

$$X_{k + 1} = X_k \setminus \{ a_k \}$$


** Ensemble fini

Soit l'ensemble $X$ contenant un nombre fini $N \in \setN$ d'éléments :

$$X = \{ a_1, a_2, ..., a_N \}$$

En appliquant l'algorithme d'évaluation d'une somme, on finit par arriver à l'itération $N$ avec :

$$X_N = \emptyset$$

On a simplement :

$$\prod_{x \in X} f(x) = S_N \cdot \prod_{x \in \emptyset} f(x) = S_N \cdot 1 = S_N$$

et :

$$\prod_{x \in X} f(x) = S_N = f(a_1) \cdot f(a_2) \cdot ... \cdot f(a_N)$$

On note :

$$\prod_{k = 1}^N f(a_k) = f(a_1) \cdot f(a_2) \cdot ... \cdot f(a_N)$$


*** Numérotation

Les éléments de $X$ peuvent être numérotés différemment. Soit $m, n \in \setZ$ et :

$$X = \{ a_m, a_{m + 1}, ..., a_{n - 1}, a_n \}$$

On a alors :

$$\prod_{x \in X} f(x) = f(a_m) \cdot f(a_{m+1}) \cdot ... \cdot f(a_{n-1}) \cdot f(a_n)$$

On note :

$$\prod_{k = m}^n f(a_k) = f(a_m) \cdot f(a_{m+1}) \cdot ... \cdot f(a_{n-1}) \cdot f(a_n)$$


*** Extension

Soit un ensemble $X$ dont on peut extraire un sous-ensemble fini de la forme :

$$F = \{ a_m, a_{m + 1}, ..., a_{n - 1}, a_n \} \subseteq X$$

tel que :

$$f(x) = 1$$

pour tout $x \in X \setminus F$. La somme s'écrit alors :

$$\prod_{x \in X} f(x) = \prod_{x \in F} f(x) = \prod_{k = m}^n f(a_k)$$


** Ensemble dénombrable


*** Naturels

Soit :

$$X = \{ a_0, a_1, a_2,... \} = \{ a_k : k \in \setN \}$$

Si la suite des $\{ S_n : n \in \setN \}$ définie par :

$$S_n = \prod_{k = 0}^n f(a_k) = f(a_0) \cdot f(a_1) \cdot ... \cdot f(a_n)$$

pour tout $n \in \setN$ converge vers un certain $S \in \corps$, on définit :

$$\prod_{x \in X} f(x) = \lim_{n \to \infty} S_n = S$$

c'est-à-dire :

$$\prod_{x \in X} f(x) = \lim_{n \to \infty} \prod_{k = 0}^n f(a_k)$$

On introduit la notation :

$$\prod_{k = 0}^{+\infty} f(a_k) = \lim_{n \to \infty} \prod_{k = 0}^n f(a_k)$$


*** Entiers

Soit :

$$X = \{ ...,a_{-2},a_{-1},a_0, a_1, a_2,... \} = \{ a_k : k \in \setZ \}$$

Si la suite des $\{ S_n : n \in \setN \}$ définie par :

$$S_n = \prod_{k = -n}^n f(a_k) = f(a_{-n}) \cdot f(a_{-n+1}) \cdot ... \cdot f(a_{n-1}) \cdot f(a_n)$$

pour tout $n \in \setN$ converge vers un certain $S \in \corps$, on définit :

$$\prod_{x \in X} f(x) = \lim_{n \to \infty} S_n = S$$

On introduit la notation :

$$\prod_{k = -\infty}^{+\infty} f(a_k) = \lim_{n \to \infty} \prod_{k = -n}^{n} f(a_k)$$


*** Extension

Soit un ensemble $X$ dont on peut extraire un sous-ensemble $D$ de la forme :

$$D = \{a_k : k \in \setN\} \subseteq X$$

ou :

$$D = \{a_k : k \in \setZ\} \subseteq X$$

tel que :

$$f(x) = 1$$

pour tout $x \in X \setminus D$. La somme s'écrit alors :

$$\prod_{x \in X} f(x) = \prod_{x \in D} f(x)$$


* Progressions

#+TOC: headlines 1 local

\label{chap:progressions}


** Arithmétique

Soit $n \in \setN$. Nous allons tenter d'évaluer la somme :

$$S_n = \sum_{i = 0}^n i = 0 + 1 + 2 + ... + n$$

L'idée est d'exprimer que cette somme est équivalente à :

$$(n - 0) + (n - 1) + ... + (n - n)$$

Si nous posons $j$ tel que $i = n - j$, on voit que l'on a $j = n -i$ et $0 \le j \le n$. Donc :

$$S_n = \sum_{j = 0}^n (n-j)$$

Développons :

$$\sum_{j = 0}^n (n-j) = \sum_{j = 0}^{n} n - \sum_{j = 0}^{n} j$$

Le premier terme du membre de droite peut se réécrire :

$$\sum_{j = 0}^n n = n \cdot \sum_{j = 0}^{n} 1 = n \cdot (n + 1)$$

Pour le second, on a clairement :

$$\sum_{j = 0}^n j = S_n$$

On en conclut que :

$$S_n = n \cdot (n + 1) - S_n$$

c'est-à-dire :

$$2 S_n = n \cdot (n + 1)$$

Divisant par $2$, on obtient le résultat final :

$$\sum_{i = 0}^{n} i = \frac{ n \cdot (n + 1) }{ 2 }$$


** Géométrique

Soit $n \in \setN$ et $a \in \corps$. Nous allons rechercher une expression de la somme :

$$G_n = \sum_{i=0}^n a^i = 1 + a + a^2 + ... + a^n$$

Si $a = 1$, on a simplement :

$$G_n = \sum_{i=0}^n a^i = 1 + ... + 1 = n$$

Intéressons-nous à présent au cas où $a \ne 1$. On part du constat que la somme $G_n$ est équivalente à :

$$1 + a \cdot (1 + a + a^2 + ... + a^n) - a^{n+1}$$

On développe en ce sens :

\begin{eqnarray*}
G_n &=& 1 + \sum_{i = 1}^n a^i \\
&=& 1 + a \cdot \sum_{i = 0}^{n - 1} a^i \\
&=& 1 + a \cdot \sum_{i = 0}^n a^i - a^{n + 1}
\end{eqnarray*}

et finalement, on arrive à l'équation implicite :

$$G_n = 1 + a \cdot G_n - a^{n + 1}$$

En soustrayant $a \cdot G_n$ des deux membres, on obtient :

$$(1 - a) \cdot G_n = 1 - a^{n + 1}$$

Comme $a \ne 1$, on en déduit que :

$$\sum_{i = 0}^n a^i = \frac{ 1 - a^{n + 1} }{ 1 - a }$$


*** Autre forme

En multipliant numérateur et dénominateur par $-1$, on obtient la forme équivalente :

$$\sum_{i = 0}^n a^i = \frac{a^{n + 1} - 1}{a - 1}$$


** Factorisation

\label{sec:factorisation_progression_geometrique}

Les progressions géométriques permettent d'obtenir une importante formule de
factorisation. Soit $a,b \in \corps$ avec $a \ne 0$. Posons :

$$r = \frac{b}{a}$$

On a alors :

$$(1 - r) \cdot \sum_{i = 0}^n r^i = 1 - r^{n + 1}$$

Multipliant par $a^{n + 1}$, on obtient :

$$(a - b) \cdot a^n \cdot \sum_{i = 0}^n \frac{b^i}{a^i} = a^{n + 1} - b^{n + 1}$$

En faisant rentrer le facteur $a^n$ dans la somme, on a en définitive :

$$a^{n + 1} - b^{n + 1} = (a - b) \cdot \sum_{i = 0}^n a^{n - i} \cdot b^i$$


*** Extension

Si $a = 0$, on a :

$$a^{n + 1} - b^{n + 1} = - b^{n + 1}$$

et :

\begin{eqnarray*}
(a - b) \cdot \sum_{i = 0}^n a^{n - i} \cdot b^i &=& -b \cdot (0^n + 0^{n -1} \cdot b + ... + 0 \cdot b^{n - 1} + b^n) \\
&=& -b \cdot b^n = - b^{n + 1}
\end{eqnarray*}

La formule de factorisation est donc valable pour tout $a,b \in \corps$.


*** Exemples

Voici quelques exemples d'applications :

\begin{eqnarray*}
a^{2} - b^{2} &=& (a - b) \cdot (a + b) \\
a^{3} - b^{3} &=& (a - b) \cdot (a^2 + a \cdot b + b^2)
\end{eqnarray*}


*** Symétrie

On a clairement :

$$\sum_{i = 0}^n a^{n - i} \cdot b^i = a^n + a^{n - 1} \cdot b + ... + a \cdot b^{n - 1} + b^n = \sum_{i = 0}^n a^i \cdot b^{n - i}$$

et donc :

$$a^{n + 1} - b^{n + 1} = (a - b) \cdot \sum_{i = 0}^n a^i \cdot b^{n - i}$$


** Somme des carrés

Considérons la somme :

$$C_n = \sum_{i = 0}^n i^2 = 1 + 4 + 16 + ... + n^2$$

La progression arythmétique nous dit que :

$$\frac{1}{2} \cdot i \cdot (i+1) = \sum_{j=0}^i j$$

On a par conséquent :

$$\sum_{i = 0}^n \frac{1}{2} \cdot i \cdot (i+1) = \sum_{i = 0}^n \sum_{j = 0}^i j$$

On peut utiliser le lemme du triangle pour inverser les deux sommes du membre de droite :

$$\sum_{i = 0}^n \sum_{j = 0}^i j = \sum_{j = 0}^n \sum_{i = j}^n j$$

Comme $j$ ne dépend pas de $i$, on peut le faire sortir de la somme sur $i$ et le membre de droite devient :

$$\sum_{j = 0}^n \sum_{i = j}^n j = \sum_{j = 0}^n j \sum_{i = j}^n 1 = \sum_{j = 0}^n j \cdot (n - j + 1)$$

En tenant compte de la linéarité des sommes, on a alors :

\begin{eqnarray*}
\sum_{j = 0}^n j \cdot (n - j + 1) &=& (n + 1) \cdot \sum_{j = 0}^n j - \sum_{j = 0}^n j^2 \\
&=& \frac{1}{2} \cdot n \cdot (n + 1)^2 - C_n
\end{eqnarray*}

D'un autre côté, on a :

$$\sum_{i = 0}^n \frac{1}{2} \cdot i \cdot (i+1) = \frac{1}{2} \sum_{i = 0}^n (i^2 + i) = \frac{1}{2} \cdot C_n + \frac{1}{4} \cdot n \cdot (n + 1)$$

En égalisant ces deux expressions, on obtient :

$$\frac{3}{2} \cdot C_n &=& \frac{1}{4} \cdot \Big[ 2 \cdot n \cdot (n + 1)^2 - n \cdot (n + 1) \Big]$$

Ou encore :

\begin{eqnarray*}
6 \cdot C_n &=& ( 2 \cdot n \cdot (n + 1) - n ) \cdot (n + 1) \\
&=& ( 2 \cdot n^2 + n ) \cdot (n + 1)
\end{eqnarray*}

On a donc la formule permettant d'évaluer la somme des carrés :

$$\sum_{i = 0}^n i^2 = \frac{ (2 \cdot n^2 + n) \cdot (n + 1) }{ 6 }$$


* Différences

#+TOC: headlines 1 local

\label{chap:differences}


** Définition

Etant donné une suite :

$$A = \{ a_k : k \in \setN \} \subseteq \corps$$

on définit l'opérateur des différences $\difference$ par :

$$\difference a_k = a_{k + 1} - a_k$$


** Addition

Soit les suites :

$$A = \{ a_k : k \in \setN \} \subseteq \corps$$

et :

$$B = \{ b_k : k \in \setN \} \subseteq \corps$$

La différence de l'addition vérifie :

$$\difference (a_k + b_k) = a_{k + 1} + b_{k + 1} - a_k - b_k = \difference a_k + \difference b_k$$


** Multiplication

Soit les suites :

$$A = \{ a_k : k \in \setN \} \subseteq \corps$$

et :

$$B = \{ b_k : k \in \setN \} \subseteq \corps$$

La différence de la multiplication vérifie :

$$\difference (a_k \cdot b_k) = a_{k + 1} \cdot b_{k + 1} - a_k \cdot b_k$$

Ajoutons et soustrayons le terme hybride $a_{k + 1} \cdot b_k$. On a :

$$\difference (a_k \cdot b_k) = a_{k + 1} \cdot b_{k + 1} - a_{k + 1} \cdot b_k + a_{k + 1} \cdot b_k - a_k \cdot b_k$$

et :

$$\difference (a_k \cdot b_k) = a_{k + 1} \cdot \difference b_k + \difference a_k \cdot b_k$$

Ajoutons et soustrayons le terme hybride $a_k \cdot b_{k + 1}$. On a :

$$\difference (a_k \cdot b_k) = a_{k + 1} \cdot b_{k + 1} - a_k \cdot b_{k + 1} + a_k \cdot b_{k + 1} - a_k \cdot b_k$$

et :

$$\difference (a_k \cdot b_k) = \difference a_k \cdot b_{k + 1} + a_k \cdot \difference b_k$$


** Somme et différence

On définit également :

$$\difference \sum_{k = 0}^n a_k = \sum_{k = 1}^{n + 1} a_k - \sum_{k = 0}^n a_k$$

La définition nous donne directement :

$$\difference \sum_{k = 0}^n a_k = (a_1 + ... + a_{n + 1}) - (a_0 + ... + a_n)$$

Tous les termes se neutralisant sauf $a_0$ et $a_{n + 1}$, on a :

$$\difference \sum_{k = 0}^n a_k = a_{n + 1} - a_0$$

On voit aussi que :

$$\sum_{k = 0}^n \difference a_k = (a_{n + 1} - a_n) + ... + (a_2 - a_1) + (a_1 - a_0)$$

Tous les termes se neutralisant mutuellement sauf le permier et le dernier, on a :

$$\sum_{k = 0}^n \difference a_k = a_{n + 1} - a_0$$

Ce résultat étant identique au précédent, on a :

$$\difference \sum_{k = 0}^n a_k = \sum_{k = 0}^n \difference a_k = a_{n + 1} - a_0$$


** Sommation par parties

Soit les suites :

$$A = \{ a_k : k \in \setN \} \subseteq \corps$$

et :

$$B = \{ b_k : k \in \setN \} \subseteq \corps$$

On a :

$$\sum_{k = 0}^n \difference (a_k \cdot b_k) = a_{n + 1} \cdot b_{n + 1} - a_0 \cdot b_0$$

En utilisant la loi de différence d'une multiplication, on obtient parallèlement :

$$\sum_{k = 0}^n \difference (a_k \cdot b_k) = \sum_{k = 0}^n \difference a_k \cdot b_{k + 1} + \sum_{k = 0}^n a_k \cdot \difference b_k$$

On a donc :

$$\sum_{k = 0}^n a_k \cdot \difference b_k = \sum_{k = 0}^n \difference (a_k \cdot b_k) - \sum_{k = 0}^n \difference a_k \cdot b_{k + 1}$$

c'est-à-dire :

$$\sum_{k = 0}^n a_k \cdot \difference b_k = a_{n + 1} \cdot b_{n + 1} - a_0 \cdot b_0 - \sum_{k = 0}^n \difference a_k \cdot b_{k + 1}


* Suites de rationnels

#+TOC: headlines 1 local

\label{chap:suitesDeRationnels}


** Dépendances

  - Chapitre \ref{chap:rationnels} : Les rationnels
  - Chapitre \ref{chap:distances} : Les distances
  - Chapitre \ref{chap:limites} : Les limites


** Définition

Une suite de rationnels, ou suite rationnelle est une suite $s : \setN \mapsto \setQ$ :

$$s : n \mapsto s_n$$


** Distance

On définit une distance sur l'ensemble des rationnels $\setQ$ par :

$$\distance(x,y) = \abs{x - y}$$

pour tout $x,y \in \setQ$. On a bien $\distance(x,y) \ge 0$.
La condition $\distance(x,y) = 0$ implique que $\abs{x - y}$,
donc $x - y = 0$ et $x = y$. Enfin :

\begin{eqnarray*}
\distance(x,z) &=& \abs{x - z} \\
&\le& \abs{x - y} + \abs{y - z} \\
&\le& \distance(x,y) + \distance(y,z)
\end{eqnarray*}


** Équivalence

Soit les suites rationnelles $s,t : \setN \mapsto \setQ$ vérifiant $s \equiv t$. On a :

$$\lim_{n \to \infty} \distance(s_n,t_n) = \lim_{n \to \infty} \abs{s_n - t_n} = 0$$

On en déduit que :

$$\lim_{n \to \infty} (s_n - t_n) = 0$$


*** Réciproque

Supposons que :

$$\lim_{n \to \infty} (s_n - t_n) = 0$$

Choisissons $\epsilon \strictsuperieur 0$ et le naturel $K(\epsilon)$ tel que :

$$\distance(s_n - t_n, 0) \le \epsilon$$

pour tout $k \ge K(\epsilon)$. Par définition de la distance entre rationnels, on a :

$$\distance(s_n - t_n, 0) = \abs{(s_n - t_n) - 0} = \abs{s_n - t_n}$$

on en conclut que :

$$\lim_{n \to \infty} \distance(s_n,t_n) = \lim_{n \to \infty} \abs{s_n - t_n} = 0$$

c'est-à-dire $s \equiv t$ par définition.


** Cauchy


*** Croissante

Soit une suite de Cauchy $u : \setN \mapsto \setQ$ :

$$u : n \mapsto u_n$$

croissante :

$$u_0 \le u_1 \le ... \le u_k \le ...$$

Comme :

$$u_n \ge u_0$$

pour tout $n \in \setN$, on voit que la suite est minorée
par $u_0$. On peut trouver un naturel $K$ tel que :

$$\distance(u_m,u_n) = \abs{u_m - u_n} \le 1$$

pour tout naturels $m,n \ge K$. Soit $n \in \setN$
vérifiant $n \ge K$. On a :

$$\abs{u_n - u_K} = u_n - u_K \le 1$$

d'où :

$$u_n \le u_K + 1$$

Pour tout naturel $k \le K$, on a :

$$u_k \le u_n \le u_K + 1$$

En posant :

$$S = u_K + 1$$

on voit que :

$$u_n \le S$$

pour tout $n \in \setN$. Une suite de Cauchy croissante est également majorée.


*** Décroissante

Soit une suite de Cauchy $u : \setN \mapsto \setQ$ :

$$u : n \mapsto u_n$$

décroissante :

$$u_0 \ge u_1 \ge ... \ge u_k \ge ...$$

Comme :

$$u_n \le u_0$$

pour tout $n \in \setN$, on voit que la suite est majorée
par $u_0$. On peut trouver un naturel $K$ tel que :

$$\distance(u_m,u_n) = \abs{u_m - u_n} \le 1$$

pour tout naturels $m,n \ge K$. Soit $n \in \setN$
vérifiant $n \ge K$. On a :

$$\abs{u_n - u_K} = u_K - u_n \le 1$$

d'où :

$$u_n \ge u_K - 1$$

Pour tout naturel $k \le K$, on a :

$$u_k \ge u_n \ge u_K - 1$$

En posant :

$$I = u_K - 1$$

on voit que :

$$u_n \ge I$$

pour tout $n \in \setN$. Une suite de Cauchy décroissante est également minorée.


** Suite inverse

Soit un rationnel $I_0$ vérifiant $I_0 \strictsuperieur 0$ et la suite
$I : \setN \setminus \{ 0 \} \mapsto \setQ$ définie par :

$$I : n \mapsto I_n = \frac{I_0}{n}$$

pour tout naturel $n$ vérifiant $n \ne 0$. Soit $\epsilon \strictsuperieur 0$.
Comme $I_0$ est strictement positif, on a :

$$\epsilon \cdot \frac{1}{I_0} = \frac{\epsilon}{I_0} \strictsuperieur 0$$

Soit $\epsilon \strictsuperieur 0$. On peut trouver un naturel $n$ tel que :

$$\frac{1}{n} \strictinferieur \frac{\epsilon}{I_0}$$

On a alors :

$$\frac{I_0}{n} \strictinferieur \epsilon$$

et :

$$\distance\parentheses{0,\frac{I_0}{n}} = \abs{\frac{I_0}{n} - 0} = \abs{\frac{I_0}{n}} \strictinferieur \epsilon$$

On en déduit que :

$$\lim_{n \to \infty} \frac{I_0}{n} = 0$$
