
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 04 : Suites - 1
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Distances

#+TOC: headlines 1 local

\label{chap:distances}


** Dépendances

  - Chapitre \ref{chap:algebre} : Les structures algébriques
  - Chapitre \ref{chap:ordres} : Les ordres
  - Chapitre \ref{chap:topologies} : Les topologies


** Définition

Afin de généraliser le plus possible la notion de distance au sens usuel, nous allons nous poser la question : quelles sont les caractéristiques fondamentales d'une distance ? Nous en déduirons les propriétés que doit respecter une distance générique.

Soit l'ensemble $\Omega$, un corps $\corps$ et une fonction $\distance : \Omega \times \Omega \to \corps$ représentant une distance entre deux éléments de l'ensemble $\Omega$. Choisissons des éléments quelconques $x,y,z \in \Omega$. Au sens usuel, une distance entre deux objets est clairement positive :

$$\distance(x,y) \ge 0$$

Elle est également symétrique puisqu'on obtient la même distance lorsqu'on intervertit les objets :

$$\distance(x,y) = \distance(y,x)$$

Par ailleurs , la distance entre deux objets identiques doit évidemment
être nulle :

$$\distance(x,x) = 0$$

On impose également que le seul élément $y$ qui puisse être à distance nulle de $x$ soit l'élément $x$ lui-même :

$$\distance(x,y) = 0 \ \Rightarrow \ x = y$$

Enfin, il est toujours plus court d'aller directement de $x$ à $z$ plutôt que de passer par une étape $y$. On a donc l'inégalité triangulaire :

$$\distance(x,z) \le \distance(x,y) + \distance(y,z)$$


*** Remarque

Parfois, au lieu d'imposer l'égalité de deux éléments situés à distance nulle l'un de l'autre, on impose juste l'équivalence suivant un critère prédéfini :

$$\distance(x,y) = 0 \ \Rightarrow \ x \equiv y$$


** Distance à un ensemble

Quelle est la distance à parcourir d'une ville donnée lorsqu'on désire se rendre dans un certain pays ? On a envie de dire que la distance est parcourue dès que l'on a atteint la frontière du pays en question. Comme on choisit généralement le chemin le plus court pour arriver à destination, on se rend compte que la distance ville - pays est le minimum des distances entre la ville et tous les points appartenant au pays.

Maintenant, remplaçons la ville par un élément $x \in \Omega$ et le pays par un ensemble $A \subseteq \Omega$. On définit simplement la distance de $x$ à $A$ comme étant l'infimum des distances de $x$ à un point quelconque de $A$ :

$$\distance(x,A) = \inf_{a \in A} \distance(x,a) = \inf \{ \distance(x,a) : a \in A \}$$


*** Inclusion

Si $B \subseteq A$, on en déduit directement que :

$$\distance(a,A) \le \distance(a,B)$$


*** Notation

On note aussi :

$$\distance(A,a) = \distance(a,A)$$


*** Self-distance

Soit $a \in A$. Comme $\distance(a,a) = 0$ et que la distance $\distance(a,b) \ge 0$ pour tout $b \in A$, on voit que le choix $b = a$ minimise $\distance(a,b)$ sur $A$. Donc :

$$\distance(a,A) = 0$$

pour tout élément $a \in A$.


** Distance inter-ensembles

La distance entre deux ensembles $A$ et $B$ est l'infimum des distances possibles entre les couples $(a,b) \in A \times B$ :

$$\distance(A,B) = \inf \{ \distance(a,b) : (a,b) \in A \times B \}$$

On a bien évidemment :

$$\distance(A,B) = \inf \{ \distance(a,B) : a \in A \} = \inf \{ \distance(A,b) : b \in B \}$$


** Boules

Les boules sont la généralisation des disques et des sphères. Or, ce qui caractèrise ces entités, c'est qu'elle incluent des points $x$ vérifiant $\distance(x,c) \le r$, où $c$ est le centre et $r$ le rayon. On définit par conséquent la boule fermée $\boule[c,r]$ par :

$$\boule[c,r] = \{ x \in \Omega : \distance(x,c) \le r \}$$

où $r$ est un réel positif.

Si l'on veut que la distance soit strictement inférieure à $r$, on considérera plutôt la définition de la boule ouverte :

$$\boule(c,r) = \{ x \in \Omega : \distance(x,c) \strictinferieur r \}$$


** Topologie métrique

La topologie usuelle définie sur les ensembles munis d'une distance est celle générée par les boules ouvertes, soit les éléments de la collection :

$$\mathcal{B} = \{ \boule(c,r) : c \in \Omega, \ r \in \corps, \  r \strictsuperieur 0 \}$$

La topologie métrique $\topologie$ s'écrit donc :

$$\topologie = \topologies(\mathcal{B},\Omega)$$

Toute union de boules ouvertes est donc un ouvert.


** Intérieur

Soit $A \subseteq \Omega$.

  - Soit $x \in \interieur A$. L'élément $x$ appartient donc à un ouvert $U$ contenu dans $A$. Comme $x \in U$, on a $U \ne \emptyset$. On en conclut que $U$ doit être une union de boules ouvertes. On peut donc trouver un $a \in U$ et un $\delta \strictsuperieur 0$ tel que $x \in \boule(a,\delta) \subseteq U$. Comme $d = \distance(a,x) \strictinferieur \delta$, on a $\delta - d \strictsuperieur 0$. Soit $\epsilon = \delta - d$ et $y \in \boule(x,\epsilon)$. On a :

$$\distance(a,y) \le \distance(a,x) + \distance(x,y) \strictinferieur d + \epsilon = \delta$$

Donc $\boule(x,\epsilon) \subseteq \boule(a,\delta) \subseteq U \subseteq A$ et $\distance( x , \Omega \setminus A ) \strictsuperieur 0$.

  - Réciproquement, si $z \in \Omega$ vérifie $d = \distance( x , \Omega \setminus A ) \strictsuperieur 0$, on a $z \in \boule(z,d/2) \subseteq A$. L'élément $z$ appartient donc à un ouvert contenu dans $A$. Il appartient donc à l'union des ouverts inclus dans $A$, c'est-à-dire $z \in \interieur A$.

On conclut de ce qui précède que :

$$\interieur A = \{ x \in \Omega : \distance( x , \Omega \setminus A ) \strictsuperieur 0 \}$$


** Adhérence

On voit que :

$$\interieur (\Omega \setminus A) = \{ x \in \Omega : \distance(x,A) \strictsuperieur 0 \}$$

Le complémentaire de cet ensemble est bien sur constitué des $x \in \Omega$ vérifiant $\distance(x,A) = 0$. Or, nous avons vu que ce complémentaire n'est rien d'autre que l'adhérence de $A$ :

$$\adh A = \{ x \in \Omega : \distance(x,A) = 0 \}$$


** Adhérence carrée

Soit $x \in \Omega$, $A \subseteq \Omega$ et :

#+BEGIN_CENTER
\(
B = \adh A \\
C = \adh B = \adh \adh A
\)
#+END_CENTER

Soit $c \in C$. Pour tout $\epsilon \in \corps$ avec $\epsilon \strictsuperieur 0$, on peut trouver $b \in B$ tel que :

$$\distance(c,b) \le \epsilon$$

et ensuite $a \in A$ tel que :

$$\distance(b,a) \le \epsilon$$

On a donc :

$$\distance(c,a) \le \distance(c,b) + \distance(b,a) \le \epsilon + \epsilon$$

L'infimum est par conséquent nul :

$$\distance(c,A) = \inf_{a \in A} \distance(c,a) = 0$$

On en déduit que $c \in \adh A$. Nous venons de montrer que :

$$\adh \adh A \subseteq \adh A$$

Mais comme l'inverse est également vrai, on a :

$$\adh \adh A = \adh A$$


* Limites

#+TOC: headlines 1 local

\label{chap:limites}


** Dépendances

  - Chapitre \ref{chap:distances} : Les distances


** Définition

Soit les ensembles $E,F$ munis respectivement des distances $\distance_E$ et $\distance_F$, un sous-ensemble $D \subseteq E$ et la fonction $f : D \mapsto F$. Comme la distance utilisée est sans ambiguité d'après la nature des objets dont elle mesure l'éloignement :

#+BEGIN_CENTER
\(
\distance(x,y) = \distance_E(x,y) \Leftrightarrow x,y \in E \\
\distance(x,y) = \distance_F(x,y) \Leftrightarrow x,y \in F
\)
#+END_CENTER

on note dans la suite de ce chapitre $\distance$ à la place de $\distance_E$ et de $\distance_F$.

Plaçons nous dans $A \subseteq D$. Nous nous intéressons au cas où $f(x)$ se rapproche de plus en plus d'un certain $L \in F$ lorsque $x \in A$ se rapproche suffisamment d'un certain $a \in E$. Pour toute précision $\epsilon \in \corps$, $\epsilon \strictsuperieur 0$ aussi petite que l'on veut, on doit alors pouvoir trouver un niveau de proximité $\delta(\epsilon) \in \corps$, $\delta(\epsilon) \strictsuperieur 0$ tel que :

$$\distance(f(x),L) \le \epsilon$$

pour tout les $x \in A$ vérifiant :

$$\distance(x,a) \le \delta(\epsilon)$$

Si cette condition est remplie, on dit que $L$ est la limite de $f$ en $a$, et on note :

$$\lim_{ \substack{ x \to a \\ x \in A } } f(x) = L$$


*** Notations

Lorsque l'ensemble $A$ est évident d'après le contexte, on note simplement :

$$\lim_{ x \to a } f(x) = \lim_{ \substack{ x \to a \\ x \in A } } f(x)$$

Au lieu de noter l'ensemble, on peut citer les conditions qui le définissent. Ainsi par exemple :

$$\lim_{ \substack{ x \to a \\ x \ne a } } f(x) = \lim_{ \substack{ x \to a \\ x \in X(a) } } f(x)$$

où :

$$X(a) = D \setminus \{ a \}$$

Autre application :

$$\lim_{ \substack{ x \to a \\ x \le a } } f(x) = \lim_{ \substack{ x \to a \\ x \in I(a) } } f(x)$$

où :

$$I(a) = \{ x \in D : x \le a \}$$


*** Remarque

Rien n'impose que $a$ appartienne à $A$. L'existence de la limite de $f$ en $a$ n'implique donc pas que la fonction $f$ soit définie en $a$.


*** Unicité

Supposons que $b$ et $c$ soient deux limites de $f$ en $a$. Soit $\epsilon \strictsuperieur 0$. On peut alors trouver un $\alpha \strictsuperieur 0$ tel que :

$$\distance(f(x),b) \le \frac{\epsilon}{2}$$

pour tout $x$ vérifiant $\distance(x,a) \le \alpha$ et un $\beta \strictsuperieur 0$ tel que :

$$\distance(f(x),c) \le \frac{\epsilon}{2}$$

pour tout $x$ vérifiant $\distance(x,a) \le \beta$. Posons $\delta = \min\{\alpha,\beta\}$. Si $x$ vérifie $\distance(x,a) \le \delta$, on a :

$$\{ \ \distance(f(x),b) , \ \distance(f(x),c) \ \} \le \frac{\epsilon}{2}$$

et :

$$\distance(b,c) \le \distance(b,f(x)) + \distance(f(x),c) \le \frac{\epsilon}{2} + \frac{\epsilon}{2} = \epsilon$$

Comme ce doit être vrai pour tout $\epsilon$ strictement positif, on en conclut que $\distance(b,c) = 0$, c'est-à-dire $b = c$. La limite est donc unique.


*** Inclusion des boules

Soit :

#+BEGIN_CENTER
\(
B_1(\delta) = \boule(a,\delta) \cap A \\
B_2(\epsilon) = \boule(f(a),\epsilon)
\)
#+END_CENTER

La définition de la limite revient à exiger que, pour tout $\epsilon \strictsuperieur 0$, on puisse trouver un $\delta \strictsuperieur 0$ tel que tout élément de $B_1(\delta)$ auquel on applique la fonction $f$ se retrouve dans $B_2(\epsilon)$. Autrement dit, $f(B_1(\delta)) \subseteq B_2(\epsilon)$.


*** Limite de la distance

Si $L$ est la limite de $f$ en $a$, la distance doit converger vers zéro par définition :

$$\lim_{ \substack{ x \to a \\ x \in A } } \distance(f(x),L) = 0$$


** Chemin

Supposons qu'il existe des sous-ensembles $A,B \subseteq D$ tels que :

$$\lim_{ \substack{ x \to a \\ x \in A } } f(x) \ne \lim_{ \substack{ x \to a \\ x \in B } } f(x)$$

On dit alors que la limite dépend du chemin parcouru.


** Limites à l'infini

Si $E$ est un ensemble ordonné, on peut définir la notion de limite à l'infini. Soit une fonction $f : E \mapsto F$ et $L \in F$. Si, pour toute précision $\epsilon > 0$, on peut trouver une borne inférieure $I(\epsilon) \in E$ telle que :

$$\distance(f(x),L) \le \epsilon$$

pour tout $x \in E$ vérifiant $x \ge I(\epsilon)$, on dit alors que $f$ tend vers $L$ à l'infini positif et on écrit :

$$\lim_{ x \to +\infty } f(x) = L$$

Symétriquement, si pour toute précision $\epsilon > 0$, on peut trouver une borne supérieure $S(\epsilon) \in E$ telle que :

$$\distance(f(x),L) \le \epsilon$$

pour tout $x \in E$ vérifiant $x \le S(\epsilon)$, on dit alors que $f$ tend vers $L$ à l'infini négatif et on écrit :

$$\lim_{ x \to -\infty } f(x) = L$$


*** Notation

On a également la notation alternative :

$$\lim_{ x \to \infty } f(x) = \lim_{ x \to +\infty } f(x)$$

ainsi que :

\begin{align}
f(+\infty) &=& \lim_{ x \to +\infty } f(x) \\ \\
f(-\infty) &=& \lim_{ x \to -\infty } f(x)
\end{align}


** Limite supremum et infimum


*** Infini positif

Il arrive que la limite à l'infini positif d'une fonction $f : E \mapsto F$ n'existe pas mais que la limite de la fonction $g : E \mapsto F$, que l'on suppose correctement définie pour tout $x \in E$ par :

$$g(x) =  \inf \{ f(y) : y \in E, \ y \ge x \}$$

existe. On note alors :

$$\liminf_{ x \to +\infty } f(x) = \lim_{ x \to +\infty } \inf \{ f(y) : y \in E, \ y \ge x \}$$

On définit pareillement la limite du supremum :

$$\limsup_{ x \to +\infty } f(x) = \lim_{ x \to +\infty } \sup \{ f(y) : y \in E, \ y \ge x \}$$


*** Infini négatif

On définit également :

#+BEGIN_CENTER
\(
\limsup_{ x \to -\infty } f(x) = \lim_{ x \to -\infty } \sup \{ f(y) : y \in E, \ y \le x \} \\ \\
\liminf_{ x \to -\infty } f(x) = \lim_{ x \to -\infty } \inf \{ f(y) : y \in E, \ y \le x \}
\)
#+END_CENTER


** Limites infinies

Si $F$ est un ensemble ordonné, on peut définir la notion de limite infinie.


*** Positive

Si, pour tout $G \in F$ aussi grand que l'on veut, on peut trouver une proximité $\delta(G) > 0$ vérifiant :

$$f(x) \ge G$$

pour tout les $x \in A$ assez proche de $a$ :

$$\distance(x,a) \le \delta(G)$$

on dit alors que $f$ tend vers l'infini positif en $a$ et on écrit :

$$\lim_{ x \to a } f(x) = +\infty$$


*** Négative

Si, pour tout $P \in F$ aussi petit que l'on veut, on peut trouver une proximité $\delta(P) > 0$ vérifiant :

$$f(x) \le P$$

pour tout les $x \in A$ assez proche de $a$ :

$$\distance(x,a) \le \delta(P)$$

on dit alors que $f$ tend vers l'infini négatif en $a$ et on écrit :

$$\lim_{ x \to a } f(x) = -\infty$$


*** Notation

On a les notations alternatives :

#+BEGIN_CENTER
\(
f(a) = +\infty \quad \Leftrightarrow \quad \lim_{ x \to a } f(x) = +\infty \\
f(a) = -\infty \quad \Leftrightarrow \quad \lim_{ x \to a } f(x) = -\infty
\)
#+END_CENTER


** Limite infinie à l'infini

On suppose que $E$ et $F$ sont ordonnés. On dit que la limite de $f$ à l'infini positif est l'infini positif et on le note :

$$\lim_{x \to +\infty} f(x) = +\infty$$

si, pour tout $G \in F$ aussi grand que l'on veut, on peut trouver une borne inférieure $I(G) \in E$ telle que :

$$f(x) \ge G$$

pour tout $x \in E$ vérifiant $x \ge I(G)$. On dit que la limite de $f$ à l'infini positif est l'infini négatif et on le note :

$$\lim_{x \to +\infty} f(x) = -\infty$$

si, pour tout $P \in F$ aussi petit que l'on veut, on peut trouver une borne inférieure $I(G) \in E$ telle que :

$$f(x) \le P$$

pour tout $x \in E$ vérifiant $x \ge I(G)$. On dit que la limite de $f$ à l'infini négatif est l'infini positif et on le note :

$$\lim_{x \to -\infty} f(x) = +\infty$$

si, pour tout $G \in F$ aussi grand que l'on veut, on peut trouver une borne supérieure $S(G) \in E$ telle que :

$$f(x) \ge G$$

pour tout $x \in E$ vérifiant $x \le S(G)$. On dit que la limite de $f$ à l'infini négatif est l'infini négatif et on le note :

$$\lim_{x \to -\infty} f(x) = -\infty$$

si, pour tout $P \in F$ aussi petit que l'on veut, on peut trouver une borne supérieure $S(G) \in E$ telle que :

$$f(x) \le P$$

pour tout $x \in E$ vérifiant $x \le S(G)$.


* Limites doubles

#+TOC: headlines 1 local

\label{chap:limitesDoubles}


** Dépendances

  - Chapitre \ref{chap:limites} : Les limites


** Introduction

Si les ensemble $A, B$ sont munis d'une distance, on définit la distance :

$$\distance^2 : (A \times B) \times (A \times B) \mapsto \corps$$

associée par :

$$\distance^2\big[(x,y), (a,b)\big] = \max \big\{ \distance(x,a), \distance(y,b) \big\}$$

pour tout $(x,y),(a,b) \in A \times B$. La fonction définie est-elle une distance ? On a clairement $\distance^2 \ge 0$ et :

$$\distance^2\big[(x,y), (a,b)\big] = \distance^2\big[(a,b), (x,y)\big]$$

On a aussi :

$$\distance^2\big[(x,y), (x,y)\big] = \max \big\{ \distance(x,x), \distance(y,y) \big\} = \max \{ 0, 0 \} = 0$$

Si :

$$\distance^2\big[(x,y), (a,b)\big] = 0$$

on a forcément :

$$\distance(x,a) = \distance(y,b) = 0$$

Donc $x = a$, $y = b$ et :

$$(x,y) = (a,b)$$

Pour l'inégalité triangulaire, soit $(x,y),(a,b),(c,d) \in A \times B$ et :

$$d = \distance^2\big[(a,b), (c,d)\big] = \max \big\{ \distance(a,c), \distance(b,d) \big\}$$

La distance sur $A$ vérifie :

$$\distance(a,c) \le \distance(a,x) + \distance(x,c)$$

La distance sur $B$ vérifie :

$$\distance(b,d) \le \distance(b,y) + \distance(y,d)$$

On en déduit que :

\begin{align}
d &\le& \max \{ \distance(a,x) + \distance(x,c), \distance(b,y) + \distance(y,d) \} \\
&\le& \max \{ \distance(a,x), \distance(b,y) \} + \max \{ \distance(x,c), \distance(y,d) \} \\
&\le& \distance^2\big[(a,b), (x,y)\big] + \distance^2\big[(x,y), (c,d)\big]
\end{align}


** Limite en un point

Soit un ensemble $F$ et une fonction $f : A \times B \mapsto F$. On choisit un ensemble $U \subseteq A \times B$. On dit que $L$ est la limite de $f$ en $(a,b) \in A \times B$ et on le note :

$$\lim_{ \substack{ (x,y) \to (a,b) \\ (x,y) \in U } } f(x,y) = L$$

si, pour toute précision $\epsilon \strictsuperieur 0$, on peut trouver un $\delta \strictsuperieur 0$ tel que :

$$\distance(f(x,y), L) \le \epsilon$$

pour tout $(x,y) \in U$ vérifiant :

$$\distance^2\big[ (x,y), (a,b) \big] = \max \{ \distance(x,a), \distance(y,b) \} \le \delta$$


*** Formulation équivalente

La condition :

$$\max \{ \distance(x,a), \distance(y,b) \} \le \delta$$

est équivalente à :

#+BEGIN_CENTER
\(
\distance(x,a) \le \delta \\
\distance(y,b) \le \delta
\)
#+END_CENTER

On en conclut que :

$$\lim_{ \substack{ (x,y) \to (a,b) \\ (x,y) \in U } } f(x,y) = L$$

si et seulement si, pour toute précision $\epsilon \strictsuperieur 0$, on peut trouver un $\delta \strictsuperieur 0$ tel que :

$$\distance(f(x,y), L) \le \epsilon$$

pour tout $(x,y) \in U$ vérifiant :

#+BEGIN_CENTER
\(
\distance(x,a) \le \delta \\
\distance(y,b) \le \delta
\)
#+END_CENTER


*** Extension

Supposons que pour toute précision $\epsilon \strictsuperieur 0$ on puisse trouver des $\delta_1, \delta_2 \strictsuperieur 0$ tels que :

$$\distance(f(x,y), L) \le \epsilon$$

pour tout $(x,y) \in U$ vérifiant :

#+BEGIN_CENTER
\(
\distance(x,a) \le \delta_1 \\
\distance(y,b) \le \delta_2
\)
#+END_CENTER

En posant :

$$\delta = \min \{ \delta_1, \delta_2 \} \strictsuperieur 0$$

on voit que :

$$\distance(f(x,y), L) \le \epsilon$$

pour tout $(x,y) \in U$ vérifiant :

#+BEGIN_CENTER
\(
\distance(x,a) \le \delta \le \delta_1 \\
\distance(y,b) \le \delta \le \delta_2
\)
#+END_CENTER

On en conclut que :

$$\lim_{ \substack{ (x,y) \to (a,b) \\ (x,y) \in U } } f(x,y) = L$$


** Limite à l'infini

On suppose que les ensembles $A, B$ sont ordonnés. On dit que $L \in F$ est la limite de $f : A \times B \mapsto F$ à l'infini positif et on le note :

$$\lim_{(x,y) \to +\infty} f(x,y) = L$$

si, pour toute précision $\epsilon \strictsuperieur 0$, on peut trouver des bornes inférieures $(I, J) \in A \times B$ telles que :

$$\distance\big[f(x,y), L\big] \le \epsilon$$

pour tout $(x,y) \in A \times B$ vérifiant :

#+BEGIN_CENTER
\(
x \ge I \\
y \ge J
\)
#+END_CENTER

On dit que $L \in F$ est la limite de $f : A \times B \mapsto F$ à l'infini négatif et on le note :

$$\lim_{(x,y) \to -\infty} f(x,y) = L$$

si, pour toute précision $\epsilon \strictsuperieur 0$, on peut trouver des bornes supérieures $(I, J) \in A \times B$ telles que :

$$\distance\big[f(x,y), L\big] \le \epsilon$$

pour tout $(x,y) \in A \times B$ vérifiant :

#+BEGIN_CENTER
\(
x \le I \\
y \le J
\)
#+END_CENTER


** Dualité


*** $x$ puis $y$

Supposons que la limite $\lambda(y)$ définie par :

$$\lambda(y) = \lim_{x \to a} f(x,y)$$

existe pour tout $y \in B$ et que :

$$L = \lim_{y \to b} \lambda(y) = \lim_{y \to b} \lim_{x \to a} f(x,y)$$

est bien définie. Nous supposons également que, quelque soit $\epsilon \strictsuperieur 0$, on peut trouver un $\delta \strictsuperieur 0$ tel que :

$$\distance(f(x,y),\lambda(y)) \le \epsilon$$

pour tout $(x,y) \in A \times B$ vérifiant :

$$\distance(x,a) \le \delta$$

Choissons $\epsilon \strictsuperieur 0$. On peut trouver $\delta_1 \strictsuperieur 0$ tel que :

$$\distance(\lambda(y), L) \le \frac{\epsilon}{2}$$

pour tout $(x,y) \in A \times B$ vérifiant :

$$\distance(y,b) \le \delta_1$$

On peut aussi trouver $\delta_2$ tel que :

$$\distance(f(x,y),\lambda(y)) \le \frac{\epsilon}{2}$$

pour tout $(x,y) \in A \times B$ vérifiant :

$$\distance(x,a) \le \delta_2$$

Soit $\delta = \min \{ \delta_1, \delta_2 \}$ et $(x,y) \in A \times B$ vérifiant :

$$\max \{ \distance(x,a), \distance(y,b) \} \le \delta$$

On a alors :

\begin{align}
\distance(f(x,y),L) &\le& \distance(f(x,y),\lambda(y)) + \distance(\lambda(y),L) \\
&\le& \frac{\epsilon}{2} + \frac{\epsilon}{2} = \epsilon
\end{align}

On en conclut que :

$$\lim_{(x,y) \to (a,b)} f(x,y) = L$$

autrement dit :

$$\lim_{(x,y) \to (a,b)} f(x,y) = \lim_{y \to b} \lim_{x \to a} f(x,y)$$


*** $y$ puis $x$

Supposons que la limite $\mu(x)$ définie par :

$$\mu(x) = \lim_{y \to b} f(x,y)$$

existe pour tout $x \in A$ et que :

$$M = \lim_{x \to a} \mu(y) = \lim_{x \to a} \lim_{y \to b} f(x,y)$$

est bien définie. Nous supposons également que, quelque soit $\epsilon \strictsuperieur 0$, on peut trouver un $\delta \strictsuperieur 0$ tel que :

$$\distance(f(x,y),\mu(x)) \le \epsilon$$

pour tout $(x,y) \in A \times B$ vérifiant :

$$\distance(y,b) \le \delta$$

Choissons $\epsilon \strictsuperieur 0$. On peut trouver $\delta_1 \strictsuperieur 0$ tel que :

$$\distance(\mu(x), M) \le \frac{\epsilon}{2}$$

pour tout $(x,y) \in A \times B$ vérifiant :

$$\distance(x,a) \le \delta_1$$

On peut aussi trouver $\delta_2$ tel que :

$$\distance(f(x,y),\mu(x)) \le \frac{\epsilon}{2}$$

pour tout $(x,y) \in A \times B$ vérifiant :

$$\distance(y,b) \le \delta_2$$

Soit $\delta = \min \{ \delta_1, \delta_2 \}$ et $(x,y) \in A \times B$ vérifiant :

$$\max \{ \distance(x,a), \distance(y,b) \} \le \delta$$

On a alors :

\begin{align}
\distance(f(x,y),M) &\le& \distance(f(x,y),\mu(x)) + \distance(\mu(x),M) \\
&\le& \frac{\epsilon}{2} + \frac{\epsilon}{2} = \epsilon
\end{align}

On en conclut que :

$$\lim_{(x,y) \to (a,b)} f(x,y) = M$$

autrement dit :

$$\lim_{(x,y) \to (a,b)} f(x,y) = \lim_{x \to a} \lim_{y \to b} f(x,y)$$
