
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 05 : Nombres composés - 2
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Matrices

#+TOC: headlines 1 local

\label{chap:matrices}


** Dépendances

  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes


** Définition

Les matrices sont des tableaux de réels, de complexes, ou de composantes d'une autre nature appartenant à un corps quelconque. Voici un exemple d'une matrice à $m$ lignes et $n$ colonnes :

#+BEGIN_CENTER
\(
A =
\begin{Matrix}{cccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots &        & \ddots &  \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{Matrix}
\)
#+END_CENTER

où les $a_{ij}$ appartiennent à un corps $\corps$. On a également des versions simplifiées de cette notation :

$$A = ( a_{ij} )_{i,j} = [ a_{ij} ]_{i,j}$$

Par convention, le numéro de ligne passe avant le numéro de colonne à l'extérieur de la parenthèse (ou du crochet).

On note $\matrice(\corps,m,n)$ l'ensemble des matrices à $m$ lignes et $n$ colonnes. On dit d'une matrice $A \in \matrice(\corps,m,n)$ qu'elle est de taille $(m,n)$.


** Composantes

Soit $A = (a_{ij})_{i,j}$. La fonction $\composante_{ij}$ donne la composante située à la $i^{ème}$ ligne et à la $j^{ème}$ colonne :

$$a_{ij} = \composante_{ij} A$$


** Blocs

Soit $A = (a_{ij})_{i,j}$. La fonction $\bloc_{ijkl}$ donne la sous-matrice située entre la $i^{ème}$ et la $j^{ème}$ ligne, ainsi qu'entre la $k^{ième}$ et la $l^{ième}$ colonne :

#+BEGIN_CENTER
\(
\bloc_{ijkl} A =
\begin{Matrix}{cccc}
a_{ik} & a_{i,k+1} & \ldots & a_{il} \\
a_{i+1,k} & a_{i+1,k+1} & \ldots & a_{i+1,l} \\
\vdots &        & \ddots &  \vdots \\
a_{jk} & a_{j,k+1} & \ldots & a_{jl}
\end{Matrix}
\)
#+END_CENTER

On appelle bloc une telle sous-matrice.


** Partitionnement en blocs

Il est parfois très utile de partitionner une matrice en blocs, ou de former une matrice plus grande à partir de matrices de tailles plus petites. On note alors :

#+BEGIN_CENTER
\(
A =
\begin{Matrix}{cc}
B & C \\
D & E
\end{Matrix}
=
\begin{Matrix}{cccccc}
b_{11} & \ldots & b_{1n} & c_{11} & \ldots & c_{1p} \\
\vdots &        & \vdots & \vdots &        & \vdots \\
b_{m1} & \ldots & b_{mn} & c_{m1} & \ldots & c_{mp} \\
d_{11} & \ldots & d_{1n} & e_{11} & \ldots & e_{1p} \\
\vdots &        & \vdots & \vdots &       & \vdots \\
d_{r1} & \ldots & d_{rn} & e_{r1} & \ldots & e_{rp}
\end{Matrix}
\)
#+END_CENTER

où les $b_{ij},c_{ij},d_{ij},e_{ij}$ sont respectivement les composantes des matrices $B,C,D,E$. Ces matrices doivent évidemment être de tailles compatibles (nombres de lignes identiques pour $B$ et $C$, ainsi que pour $D$ et $E$ ; nombres de colonnes identiques pour $B$ et $D$, ainsi que pour $C$ et $E$).


** Formes lignes et colonnes

On peut exprimer une matrice $A \in \matrice(\corps,m,n)$ sous la forme de lignes superposées. Soit :

#+BEGIN_CENTER
\(
A =
\begin{Matrix}{c}
l_1 \\
l_2 \\
\vdots \\
l_m
\end{Matrix}
\)
#+END_CENTER

où les $l_i \in \matrice(\corps,1,n)$ sont les lignes de $A$. On note :

$$\ligne_i A = l_i$$

On peut aussi l'exprimer sous la forme de colonnes juxtaposées. Soit :

$$A = [c_1 \ c_2 \hdots \ c_n]$$

où les $c_i \in \matrice(\corps,m,1)$ sont les colonnes de $A$. On note :

$$\colonne_i A = c_i$$


** Transposée

Transposer une matrice $A = (a_{ij})_{i,j} \in \matrice(\corps,m,n)$ consiste à agencer ses lignes en colonnes et vice-versa :

#+BEGIN_CENTER
\(
A^T =
\begin{Matrix}{cccc}
a_{11} & a_{21} & \ldots & a_{m1} \\
a_{12} & a_{22} & \ldots & a_{m2} \\
\vdots &        & \ddots &  \vdots \\
a_{1n} & a_{2n} & \ldots & a_{mn}
\end{Matrix} = (a_{ji})_{i,j}
\)
#+END_CENTER

On voit que la transposée $A^T \in \matrice(\corps,n,m)$.

On a clairement :

$$\big( A^T \big)^T = A$$


** Vecteurs lignes et colonnes

Les vecteurs ligne sont des matrices ne possédant qu'une seule ligne. Ils sont donc de taille générique $(1,n)$. Les vecteurs colonne sont des matrices ne possédant qu'une seule colonne. Ils sont donc de taille générique $(m,1)$.

Les vecteurs {\em colonne} sont notés :

$$x = (x_i)_i$$

On a aussi :

$$x_i = \composante_i x$$

*** Equivalence avec $\corps^n$

A partir d'un $n$-tuple $(x_1,x_2,...,x_n) \in \corps^n$, on peut former un vecteur ligne $x \in \matrice(\corps,1,n)$ par :

$$x = [x_1 \ x_2 \ \hdots \ x_n]$$

et un vecteur colonne $x' \in \matrice(\corps,n,1)$ par :

#+BEGIN_CENTER
\(
x' =
\begin{Matrix}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{Matrix}
=
[x_1 \ x_2 \ \hdots \ x_n]^T
\)
#+END_CENTER

On a donc $\matrice(\corps,1,n),\matrice(\corps,n,1) \equiv \corps^n$.


*** Notation

Sauf mention contraire, nous convenons dans la suite que tout vecteur $u \in  \corps^n$ sera associé à un vecteur {\em colonne} de même nom $u \in \matrice(\corps,n,1)$. Si nous voulons utiliser un vecteur {\em ligne}, nous le noterons alors $u^T$ (ou $u^\dual$ pour des raisons qui apparaîtront plus loin).


** Carrées et rectangulaires

Les matrices $A \in \matrice(\corps,n,n)$ ayant même nombre de colonnes et de lignes sont dites « carrées ». Les matrices $A \in \matrice(\corps,m,n)$ avec $m \ne n$ sont dites « rectangulaires ». Lorsque $m \strictinferieur n$, on dit que la matrice est « longue ». Si $m \strictsuperieur n$, on dit que la matrice est « haute ».


** Matrices diagonales

Une matrice diagonale contient des composantes nulles partout, à l'exception de la diagonale où aucune contrainte n'est fixée. On peut représenter une matrice diagonale $D \in \matrice(\corps,m,n)$ par :

$$D = ( d_i \cdot \indicatrice_{ij} )_{i,j}$$

On peut aussi former une matrice diagonale de taille $(m,n)$ à partir d'un vecteur $d = (d_i)_i$ de taille $(p,1)$, où $p \le \min \{ m , n \}$. On le note :

$$D = \diagonale_{m,n}(d) = \diagonale_{m,n}(d_1,...,d_p)$$

où :

#+BEGIN_CENTER
\(
\composante_{ij} \diagonale_{m,n}(d_1,...,d_p) =
\begin{cases}
d_i & \text{ si } i = j \in \{1,2,...,p\} \\
0 & \text{ sinon}
\end{cases}
\)
#+END_CENTER


*** Carrée

Dans le cas particulier où $m = n$, on note aussi :

$$\diagonale_n(d) = \diagonale_{n,n}(d)$$


** Matrices triangulaires

Les composantes des matrices triangulaires supérieures ne peuvent être non nulles qu'au-dessus de la diagonale, c'est-à-dire lorsque $i \le j$. Elles peuvent se représenter par :

$$T = (t_{ij} \cdot \tau^+_{ij})_{i,j}$$

où :

#+BEGIN_CENTER
\(
\tau^+_{ij} =
\begin{cases}
1 & \mbox{ si } i \le j \\
0 & \mbox{ si } i \strictsuperieur j
\end{cases}
\)
#+END_CENTER

Les composantes des matrices triangulaires inférieures ne peuvent être non nulles qu'au-dessous de la diagonale, c'est-à-dire lorsque $i \ge j$. Elles peuvent se représenter par :

$$T = (t_{ij} \cdot \tau^-_{ij})_{i,j}$$

où :

#+BEGIN_CENTER
\(
\tau^-_{ij} =
\begin{cases}
1 & \mbox{ si } i \ge j \\
0 & \mbox{ si } i \strictinferieur j
\end{cases}
\)
#+END_CENTER


** Egalité

Il est clair que deux matrices $A,B \in \matrice(\corps,m,n)$ :

#+BEGIN_CENTER
\(
A = ( a_{ij} )_{i,j} \\
B = ( b_{ij} )_{i,j}
\)
#+END_CENTER

sont égales ($A = B$) si tous leurs éléments le sont :

$$a_{ij} = b_{ij}$$

pour tout $(i,j) \in \{ 1,2,...,m \} \times \{ 1,2,...,n \}$.


** Ordre partiel

Soit les matrices $A,B \in \matrice(\corps,m,n)$ :

#+BEGIN_CENTER
\(
A = ( a_{ij} )_{i,j} \\
B = ( b_{ij} )_{i,j}
\)
#+END_CENTER

On dit que $A$ est inférieure à $B$, et on le note $A \le B$, si :

$$a_{ij} \le b_{ij}$$

pour tout $(i,j) \in \{ 1,2,...,m \} \times \{ 1,2,...,n \}$.


** Addition et soustraction

Soit les matrices de tailles identiques $A, B \in \matrice(\corps,m,n)$ :

#+BEGIN_CENTER
\(
A = (a_{ij})_{i,j} \\
B = (b_{ij})_{i,j}
\)
#+END_CENTER

L'addition et la soustraction des matrices sont simplement définies par l'addition et la soustraction des composantes :

#+BEGIN_CENTER
\(
A + B = (a_{ij} + b_{ij})_{i,j} \\
A - B = (a_{ij} - b_{ij})_{i,j}
\)
#+END_CENTER

On a donc clairement :

$$A + B = B + A$$


*** Neutre

La matrice nulle $0$ est le neutre pour cette opération :

$$A + 0 = A$$

On en déduit que tous ses éléments doivent être nuls :

$$0 = ( 0 )_{i,j}$$

On note $0_{m,n}$ au lieu de $0$ lorsqu'on veut préciser que $0$ est
de taille $(m,n)$.


*** Opposé

L'opposé de $A$, noté $-A$, est tel que :

$$A + (-A) = 0$$

On a donc clairement :

$$-A = (-a_{ij})_{i,j}$$


** Multiplication mixte

On définit la multiplication mixte $\cdot : \corps \times \matrice(\corps,m,n) \to \matrice(\corps,m,n)$ par :

$$\beta \cdot A = (\beta \cdot a_{ij})_{i,j}$$

où $\beta \in \corps$ et $A \in \matrice(\corps,m,n)$.

Choissons également $\gamma \in \corps$. On note comme d'habitude :

#+BEGIN_CENTER
\(
A \cdot \beta = \beta \cdot A \\
\gamma \cdot \beta \cdot A = (\gamma \cdot \beta) \cdot A \\
\beta A = \beta \cdot A
\)
#+END_CENTER


** Conjuguée

La conjuguée d'une matrice $A = (a_{ij})_{i,j} \in \matrice(\setC,m,n)$ est définie par la conjuguée des composantes :

$$\conjugue A = \bar{A} = ( \bar{a}_{ij} )_{i,j} = ( \conjugue a_{ij} )_{i,j}$$


* Progressions matricielles

#+TOC: headlines 1 local

\label{chap:progressionsMatricielles}


** Géométrique

Soit une matrice carréé $A \in \matrice(\corps, n, n)$.

$$G_N = \sum_{k = 0}^N A^k = I + A + A^2 + ... + A^N$$


*** Forme gauche

$$G_N = I + A \cdot (I + A + ... + A^N) - A^{N + 1}$$

$$G_N = I + A \cdot G_N - A^{N + 1}$$

$$(I - A) \cdot G_N = I - A^{N + 1}$$

$$(I - A) \cdot \sum_{k = 0}^N A^k = I - A^{N + 1}$$


*** Forme droite

$$G_N = I + (I + A + ... + A^N) \cdot A - A^{N + 1}$$

$$G_N = I + G_N \cdot A - A^{N + 1}$$

$$G_N \cdot (I - A) = I - A^{N + 1}$$

$$\sum_{k = 0}^N A^k \cdot (I - A) = I - A^{N + 1}$$


*** Inversible

$$\sum_{k = 0}^N A^k = (I - A)^{-1} \cdot (I - A^{N + 1})$$

$$\sum_{k = 0}^N A^k = (I - A^{N + 1}) \cdot (I - A)^{-1}$$


* Polynômes

#+TOC: headlines 1 local

\label{chap:polynomes}


** Dépendances

  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes
  - Chapitre \ref{chap:somme} : Les sommes
  - Chapitre \ref{chap:produit} : Les produits


** Définition

Soit un corps $\corps$. On dit qu'une fonction $p : \corps \mapsto \corps$ est un polynôme de degré $n$ si on peut trouver des éléments $a_0,a_1,...a_n \in \corps$ tels que :

$$p(x) = \sum_{i = 0}^n a_i \cdot x^i$$

pour tout $x \in \corps$. On note $\polynome(\corps,n)$ l'espace des polynômes de degré $n$ définis sur $\corps$.

Un cas particulier important est celui des polynômes réels :

$$\mathcal{P}_n = \polynome(\setR,n)$$


** Monôme

Un monôme $\mu_i : \corps \mapsto \corps$ est une fonction de la forme :

$$\mu_i(x) = x^i$$

pour tout $x \in \corps$.


** Racines

On dit que $r$ est une racine du polynôme $p$ si :

$$p(r) = 0$$

Nous allons montrer que tout polynôme de degré $n$ non nul
admet au plus $n$ racines distinctes.

Ce qui revient à dire que si un polynôme de degré $n$ admet $m+1$ racines distinctes avec $m \ge n$, alors ce polynôme est forcément nul.

Soit $n = 0$. Considérons un polynôme $p_0$ défini par $p_0(x) = a_0$ pour un certain $a_0 \in \corps$. Comme $n + 1 = 1$, on peut trouver au moins un $x \in \corps$ tel que $p_0(x_0) = a_0 = 0$. On en conclut que $a_0 = 0$ et que $p_0(x) = 0$ pour tout $x \in \corps$, ce qui revient à dire que $p_0 = 0$. La thèse est donc vérifiée pour $n = 0$.

A présent, supposons que l'affirmation soit vraie pour $n - 1$. Choisissons un polynôme $p_n$ de degré $n$ :

$$p_n(x) = \sum_{i=0}^n a_i \cdot x^i$$

Supposons que $p$ possède $m+1$ racines

$$p_n(x_0) = p_n(x_1) = ... = p_n(x_m) = 0$$

avec $m \ge n$ et  :

$$x_0 \strictinferieur x_1 \strictinferieur ... \strictinferieur x_m$$

On a alors :

$$p_n(x) = p_n(x) - p_n(x_0) = \sum_{i=1}^n a_i \cdot (x^i - x_0^i)$$

Mais les propriétés de factorisation des progressions géométriques (voir la section \ref{sec:factorisation_progression_geometrique}) nous permettent d'affirmer que :

$$x^i - x_0^i = (x - x_0) \sum_{j = 0}^{i - 1} x^j \cdot x_0^{i - 1 -j}$$

on en déduit que :

$$p_n(x) = (x - x_0) \cdot q_{n-1}(x)$$

où le polynôme $q_{n - 1}$ est défini par :

$$q_{n - 1}(x) = \sum_{i = 1}^n a_i \sum_{j = 0}^{i - 1}  x^j \cdot x_0^{i - 1 - j}$$

Cette expression ne faisant intervenir que les puissances $1,x,...,x^{n-1}$, on voit que $q_{n-1} \in \mathcal{P}_n$ est de degré $n-1$. Considérons les cas des racines $x = x_1, x_2, ...,x_m$ de $p_n$. On a :

$$0 = p_n(x_k) = (x_k - x_0) \cdot q_{n-1}(x_k)$$

Comme $x_k - x_0 \ne 0$, on peut multiplier par $(x_k - x_0)^{-1}$ pour obtenir :

$$q_{n-1}(x_k) = \frac{p_{n-1}(x_k)}{x_k - x_0} = 0$$

Le polynôme $q_{n-1}$ possède par conséquent au moins $m-1 \ge n-1$ racines distinctes. Il est dès lors nul par l'hypothèse de récurrence. La factorisation de $p_n$ devient alors :

$$p_n(x) = (x - x_0) \cdot q_{n-1}(x) = 0$$

pour tout $x \in \corps$. Le polynôme $p_n$ est également nul et la thèse est démontrée.


*** Egalité

Si deux polynômes $p_1,p_2 \in \mathcal{P}_n$ sont égaux en $m + 1 \ge n + 1$ points distincts, alors le polynôme de degré $n$ :

$$h = p_1 - p_2$$

admet $m+1$ racines. Il est donc nul et $p_1 = p_2$.


** Factorisation

Choisissons un polynôme $p\in\mathcal{P}_n$ qui admet $n$ racines
distinctes $x_1,x_2,...,x_n$. Soit alors $x_0 \notin \{x_1,...,x_n\}$
et :

$$A = \frac{p(x_0)}{\prod_{i = 1}^n (x_0 - x_i)}$$

On voit que le polynôme :

$$q(x) = A \cdot \prod_{i=1}^n (x - x_i)$$

est égal à $p$ en chacune des racines :

$$p(x_i) = q(x_i) = 0 \qquad i = 1,2,...,n$$

Mais par la définition de $A$, on a aussi :

$$p(x_0) = q(x_0)$$

Les deux polynômes sont donc égaux en $n+1$ points distincts.
Comme ils sont tous deux de degré $n$, on en déduit que $p = q$.
Les coefficients doivent donc tous être égaux, et comme :

#+BEGIN_CENTER
\(
p(x) = a_n \cdot x^n + \sum_{i = 0}^{n - 1} a_i \cdot x^i \\
q(x) = A \cdot x^n + \sum_{i = 0}^{n - 1} b_i(x_1,...,x_n) \cdot x^i
\)
#+END_CENTER

on a $A = a_n$ et :

$$p(x) = a_n \cdot \prod_{i=1}^n (x - x_i)$$


** Binômes canoniques

Le binôme canonique de degré $n \in \setN$ est une fonction $b_n : \corps \to \corps$ définie par :

$$b_n(x) = (1 + x)^n$$

pour tout $x \in \corps$. On a par exemple :

\begin{eqnarray*}
b_0(x) &=& (1 + x)^0 = 1 \\
b_1(x) &=& (1 + x)^1 = 1 + x \\
b_2(x) &=& (1 + x)^2 = (1 + x) \cdot (1 + x) = 1 + 2 \ x + x^2
\end{eqnarray*}

On voit donc que le binôme canonique de degré $n$ peut s'écrire comme :

$$b_n(x) = (1 + x)^n = \sum_{k = 0}^n a_{nk} \cdot x^k$$

pour certains coefficients $a_{nk} \in \corps$. On nomme ces coefficients les « nombres binômiaux », et on les note :

$$\binome{n}{k} = a_{nk}$$

L'expression de $b_0$ nous donne :

$$\binome{0}{0} = 1$$

On peut évaluer récursivement les nombres binômiaux d'ordres plus élevés en utilisant la définition de la puissance :

$$b_n(x) = (1 + x) \cdot b_{n-1}(x)$$

Il vient alors :

\begin{eqnarray*}
\sum_{k = 0}^n \binome{n}{k} \cdot x^k &=& (1 + x) \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^k \\
&=& \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^k + \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^{k + 1} \\
&=& \sum_{k = 0}^{n - 1} \binome{n - 1}{k} \cdot x^k + \sum_{i = 1}^n \binome{n - 1}{i - 1} \cdot x^i \\
\end{eqnarray*}

et finalement :

#+BEGIN_CENTER
\(
\sum_{k = 0}^n \binome{n}{k} \cdot x^k = \binome{n - 1}{0} + \sum_{k = 1}^{n - 1} \left[ \binome{n - 1}{k} + \binome{n - 1}{k - 1} \right] \cdot x^k \\
\qquad \qquad \qquad + \binome{n - 1}{n - 1} \cdot x^n
\end{Eqts*}

En égalisant les coefficients des $x^0 = 1$, nous avons :

$$\binome{n}{0} = \binome{n - 1}{0}$$

On en déduit par récurrence que :

$$\binome{n}{0} = 1$$

En égalisant les coefficients des $x^n$, nous avons :

$$\binome{n}{n} = \binome{n - 1}{n - 1}$$

On en déduit par récurrence que :

$$\binome{n}{n} = 1$$

En égalisant les coefficients de $x^k$ pour $k \in \{1,...,n-1\}$, il vient :

$$\binome{n}{k} = \binome{n - 1}{k} + \binome{n - 1}{k - 1}$$

Il est donc facile d'évaluer les coefficients de $b_n$ à partir des coefficients de $b_{n - 1}$.


** Binômes génériques

Le binôme générique de degré $n \in \setN$ est une fonction $B_n : \corps \times \corps
\mapsto \corps$ définie par :

$$B_n(x,y) = (x + y)^n$$

pour tout $(x,y) \in \corps^2$. Nous avons la forme équivalente :

$$B_n(x,y) = y^n \cdot \left( 1 + \frac{x}{y} \right)^n = y^n \cdot b_n\left( \frac{x}{y} \right)$$

c'est-à-dire :

$$B_n(x,y) = \sum_{k = 0}^n \binome{n}{k} \cdot x^k \cdot y^{n - k}$$


** Second degré

Le binôme du second degré est couramment utilisé :

$$(x + y)^2 = x \ (x + y) + y \ (x + y) = x^2 + 2 \ x \ y + y^2$$


** Symétrie

Par commutativité de l'addition, on a $B_n(x,y) = B_n(y,x)$ et :

$$\sum_{k = 0}^n \binome{n}{k} \cdot x^k \cdot y^{n - k} = \sum_{i = 0}^n \binome{n}{i} \cdot y^i \cdot x^{n - i}$$

Procédant au changement d'indice $n - i = k$, il vient :

$$\sum_{k = 0}^n \binome{n}{k} \cdot x^k \cdot y^{n - k} = \sum_{k = 0}^n \binome{n}{n - k} \cdot x^k \cdot y^{n - k}$$

On en déduit en égalisant les coefficients de $x^k$ que :

$$\binome{n}{k} = \binome{n}{n - k}$$


** Cas particuliers

En considérant le cas particuliers $x = y = 1$, on constate que :

$$\sum_{k=0}^{n} \binome{n}{k} = (1 + 1)^n = 2^n$$

Pour $x = -1$, $y = 1$, on a :

$$\sum_{k=0}^{n} \binome{n}{k} \cdot (-1)^k = (-1 + 1)^n = 0^n = 0$$

Lorsque $y = 1 - x$ on arrive à :

$$\sum_{k=0}^{n} \binome{n}{k} \cdot x^k \cdot (1-x)^{n-k} = (x + 1 - x)^n = 1^n = 1$$


** Bernstein

Soit $i,n \in \setN$ avec $i \le n$. Les polynômes de Bernstein $B_i^n$ sont définis par :

$$B_i^n(t) = \binome{n}{i} \cdot t^i \cdot (1 - t)^{n-i}$$

pour tout $t \in [0,1]$.

Considérons l'espace fonctionnel $\mathcal{F} = \fonction([0,1],\corps)$. L'opérateur de Bernstein $\mathcal{B}_n : \mathcal{F} \mapsto \mathcal{F}$ est défini par :

$$\mathcal{B}_n(f)(t) = \sum_{i = 0}^n f(i / n) \cdot B_i^n(t)$$

pour tout $f \in \mathcal{F}$ et pour tout $t \in [0,1]$.

Soit la fonction constante $c \in \mathcal{F}$ associée à un certain $c \in \corps$ et définie par :

$$c(t) = c$$

pour tout $t \in [0,1]$.

L'opérateur de Bernstein possède l'importante propriété de conserver ces fonctions constantes :

$$\mathcal{B}_n(c)(t) = \sum_{i = 0}^n c \cdot B_i^n(t) = c \sum_{i = 0}^n \binome{n}{i} t^i \cdot (1 - t)^{n-i} = c$$

quelle que soit la valeur de $t \in [0,1]$.


** Division Euclidienne

Soit deux polynomes $a \in \mathcal{P}_n$ et $b \in \mathcal{P}_m$
avec $m \le n$ et :

#+BEGIN_CENTER
\(
a(x) = \sum_{i = 0}^n a_i \cdot x^i \\
b(x) = \sum_{i = 0}^m b_i \cdot x^i
\)
#+END_CENTER

On dit que $q$ et $r$ sont respectivement le quotient et le reste
de la division euclidienne de $a$ et $b$, et on note :

$$(q,r) = \division(a,b)$$

si :

#+BEGIN_CENTER
\(
a(x) = b(x) \cdot q(x) + r(x) \\
q(x) = \sum_{i=0}^{n-m} q_i x^i \\
r(x) = \sum_{i=0}^{p} r_i x^i
\)
#+END_CENTER

avec $p \strictinferieur m \le n$.
