
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 12 : Analyse complexe - 2
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Analyse de Fourier

#+TOC: headlines 1 local

\label{chap:fourier}


** Séries de Fourier

ARRANGER LE CHAPITRE

Constatons tout d'abord que :

#+BEGIN_CENTER
\(
\int_0^{2\pi} \exp(\img k x) dx =
\begin{cases}
2 \pi & \mbox{si  } k = 0 \\
0 & \mbox{si  } k \ne 0
\end{cases}
\)
#+END_CENTER

pour tout $k\in\setZ$. En effet, si $k=0$, l'intégrale devient :

$$\int_0^{2\pi} \exp(0) dx = \int_0^{2\pi} 1 dx = 2 \pi$$

Par contre, si $k\ne 0$, le changement de variable :

#+BEGIN_CENTER
\(
s = \img k x \\
ds =  \img k dx
\)
#+END_CENTER

nous mène à :

$$\int_0^{2\pi} \exp(\img k x) dx = \unsur{\img k} \int_0^{2\pi\img k} \exp(s) ds$$

le théorème fondamental nous donne alors :

$$\int_0^{2\pi} \exp(\img k x) dx = \unsur{\img k} [\exp(2\pi\img k)-\exp(0)] = 0$$

pour tout $k\in\setZ$, par périodicité des exponentielles imaginaires.
On généralise ce résultat en utilisant le changement de variable :

$$t = a + \frac{T}{2\pi} x$$

ce qui nous donne :

#+BEGIN_CENTER
\(
\int_a^{a+T} \exp\left(\frac{2\pi\img k x}{T}\right) dx =
\begin{cases}
T & \mbox{si  } k = 0 \\
0 & \mbox{si  } k \ne 0
\end{cases}
\)
#+END_CENTER

Définissons à présent le produit scalaire :

$$\scalaire{u}{v} = \int\limits_{-T/2}^{T/2} \bar{u}(x) v(x) dx$$

Soient les fonctions $e_k$ :

$$e_k : x \mapsto \exp\left(\frac{2\pi\img k x}{T}\right)$$

où $k\in\setZ$. Notons que :

#+BEGIN_CENTER
\(
\bar{e}_m e_n =
\exp\left(-\frac{2\pi\img m x}{T}\right)\exp\left(\frac{2\pi\img n x}{T}\right) \\
\bar{e}_m e_n = \exp\left(\frac{2\pi\img (n-m) x}{T}\right)
\)
#+END_CENTER

La suite des $e_k$ est donc orthonormée :

$$\scalaire{e_m}{e_n} = \int\limits_{-T/2}^{T/2} \exp\left(\frac{2\pi\img (n-m) x}{T}\right)dx = 2 \pi \delta_{mn}$$

Soit à présent $u\in\ev{e_k : k\in\setZ}$ :

$$u(x) = \sum_{k=-\infty}^{+\infty} \hat{u}_k e_k$$

Nous avons vu au chapitre \ref{chap:vector} que les composantes d'un vecteur
(ici la fonction $u$) par rapport à une base orthonormée s'écrivent :

$$\hat{u}_k = \scalaire{e_k}{u} = \int\limits_{-T/2}^{T/2} u(x) \exp\left(-\frac{2\pi\img k x}{T}\right)dx$$

Soit à présent $v$ :

$$v(x) = \sum_{k=-\infty}^{+\infty} \hat{v}_k e_k$$

Utilisant à nouveau les propriétés des bases orthonormées, on a :

$$\scalaire{u}{v} = \sum_{k=-\infty}^{+\infty} \conj(\hat{u}_k) \hat{v}_k$$


** Transformeée de Fourier discrète

Dans le cas où :

#+BEGIN_CENTER
\(
a = \exp(\img x) \\
a^k = \exp(\img k x)
\)
#+END_CENTER

l'équation de la progression géométrique
du chapitre \ref{chap:real} :

$$\sum_{i=0}^{n} a^i = \frac{1-a^{n+1}}{1-a}$$

devient :

$$\sum_{k=0}^{n} \exp(\img k x) = \frac{1-\exp(\img (n+1) x)}{1-\exp(\img x)}$$

On voit alors que si $(n+1) x$ est un multiple entier de $2\pi$, la somme s'annule
par périodicité sauf dans le cas où $x$ est un multiple entier de $2\pi$, où elle
vaut $n+1$. Posant $N = n - 1$ et $x = 2\pi l/N$, on obtient :

#+BEGIN_CENTER
\(
\sum_{k=0}^{N-1} \exp \left( \frac{2 \pi \img k l}{N} \right) =
\begin{cases}
N & \mbox{si  } m = l/N \in\setZ \\
0 & \mbox{si  } m = l/N \notin\setZ
\end{cases}
\)
#+END_CENTER

pour tout $k,l,m,N \in \setZ$. Dans la suite nous utilisons la notation :

$$e(k,l) = \exp \left( \frac{2 \pi \img k l}{N} \right)$$

Nous allons en déduire la forme de la transformeée de Fourier discrète. Soit la
série $u_k : k = 0,...,N-1$ :

$$u_k = \sum_{n=-N/2}^{N/2-1} U_n e(k,n)$$

où nous supposons que $N/2 \in\setN$. Multipliant par $e(k,-m)$ où
$m \in \{-N/2,...,N/2-1\}$, et utilisant l'additivité des exponentielles, il vient :

#+BEGIN_CENTER
\(
u_k e(k,-m) = \sum_{n=-N/2}^{N/2-1} U_n e(k,n) e(k,-m) \\
u_k e(k,-m) = \sum_{n=-N/2}^{N/2-1} U_n e(k,n-m)
\)
#+END_CENTER

Sommons à présent sur $k$ :

$$\sum_{k=0}^{N-1} u_k e(k,-m) = \sum_{n=-N/2}^{N/2-1} U_n \sum_{k=0}^{N-1} e(k,n-m)$$

Mais la somme sur $k$ du membre de droite s'annule sauf lorsque $n-m$
est multiple entier de $N$. Comme $m,n$ sont dans $\{-N/2,...,N/2-1\}$, le seul
cas possible est ici $m = n$. On a donc :

$$U_m = \unsur{N} \sum_{k=0}^{N-1} u_k e(k,-m)$$

Nous avons donc obtenu une bijection entre les $u_k$ et les $U_n$ :

#+BEGIN_CENTER
\(
u_k = \sum_{n=-N/2}^{N/2-1} U_n \exp\left(\frac{2 \pi \img k n}{N}\right) \\
U_n = \unsur{N} \sum_{k=0}^{N-1} u_k \exp\left(-\frac{2 \pi \img k n}{N}\right)
\)
#+END_CENTER


** Transformeée de Fourier

On peut présenter le résultat précédent sous une autre forme. On peut poser :

#+BEGIN_CENTER
\(
x_k = k\Delta x \\
y_n = n\Delta y
\)
#+END_CENTER

ainsi que :

#+BEGIN_CENTER
\(
u_k = u(x_k) \\
U_n = U(y_n)
\)
#+END_CENTER

pour des fonctions $u,v \in X \subset \fonction(\setR,\setR)$. Soit :

$$u(x_k) = \sum_{n=-N/2}^{N/2-1} U(y_n) \exp(2 \pi \img x_k y_n) \Delta y$$

où $k = -N/2 , ... ,N/2 - 1$. Suivant le même procédé que ci-dessus, on aboutit à
la relation inverse :

$$U(y_n) = \sum_{k = -N/2}^{N/2-1} u(x_k) \exp(-2 \pi \img x_k y_n) \Delta x$$

pour autant que :

$$\Delta x \Delta y = \frac{1}{N}$$

Choisissons :

$$\Delta x  = \Delta y = \frac{1}{\sqrt{N}}$$

On voit que $\Delta x$ et $\Delta y$ tendent alors vers $0$ lorsque $N$ tend vers l'infini.
Les sommes ci-dessus se rapprochent donc de plus en plus d'intégrales sur
l'intervalle $[-\sqrt{N}/2,\sqrt{N}/2]$, qui tend lui-même vers
$(-\infty,+\infty) = \setR$. On arrive donc aux relations :

#+BEGIN_CENTER
\(
u(x) = \int\limits_{-\infty}^{+\infty} U(y) \exp(2\pi\img x y) dy \\
U(y) = \int\limits_{-\infty}^{+\infty} u(x) \exp(-2\pi\img x y) dx
\)
#+END_CENTER

On définit alors la transformeée de Fourier $\mathcal{F} : X \mapsto X$ et
son inverse par :

#+BEGIN_CENTER
\(
U(y) = \mathcal{F}(u)(y) = \int\limits_{-\infty}^{+\infty} u(x) \exp(-2\pi\img x y) dx \\
u(x) = \mathcal{F}^{-1}(U)(x) = \int\limits_{-\infty}^{+\infty} U(y) \exp(2\pi\img x y) dy
\)
#+END_CENTER


*** Delta de Dirac

On déduit des relations ci dessus que :

#+BEGIN_CENTER
\(
u(x) = \int\limits_{-\infty}^{+\infty} \exp(2\pi\img x y) dy
\int\limits_{-\infty}^{+\infty} u(z) \exp(-2\pi\img z y) dz \\
u(x) = \int\limits_{-\infty}^{+\infty} u(z) dz
\int\limits_{-\infty}^{+\infty} \exp(2\pi\img (x-z) y) dy
\)
#+END_CENTER

On en déduit la relation fondamentale :

$$\int\limits_{-\infty}^{+\infty} \exp(2\pi\img (x-z) y) dy = \delta(x-z)$$

qui est l'extension de l'orthonormalité des bases discrètes.
Ce n'est donc pas une intégrale au sens classique du terme, mais une distribution.

Cette relation nous montre aussi, lorsque $z=0$, que :

$$\mathcal{F}(1)(x) = \delta(x)$$

Inversément, on a :

$$\mathcal{F}(\delta)(x) = \int\limits_{-\infty}^{+\infty} \delta(x) \exp(-2\pi\img x y) dx = \exp(0) = 1$$


*** Produit scalaire

Considérons à présent le produit scalaire :

$$\scalaire{u}{v} = \int\limits_{-\infty}^{+\infty} \bar{u}(x) v(x) dx$$

et examinons $\scalaire{\mathcal{F}(u)}{\mathcal{F}(v)}$. En utilisant la propriété
d'orthonormalité, on arrive à :

#+BEGIN_CENTER
\(
\int\limits_{-\infty}^{+\infty} \conj\left[\mathcal{F}(u)(y)\right] \mathcal{F}(v)(y) dy =
\int_{\setR^2} \bar{u}(x) v(z) \exp\left(2\pi\img (x-z) y\right) dx dz \\
\int\limits_{-\infty}^{+\infty} \conj\left[\mathcal{F}(u)(y)\right] \mathcal{F}(v)(y) dy =
\int_{\setR^2} \bar{u}(x) v(z) \delta(x-z) dx dz
\)
#+END_CENTER

et donc :

#+BEGIN_CENTER
\(
\int\limits_{-\infty}^{+\infty} \conj\left[\mathcal{F}(u)(y)\right] \mathcal{F}(v)(y) dy =
\int\limits_{-\infty}^{+\infty} \bar{u}(x) v(x) dx
\)
#+END_CENTER

La transformeée de Fourier possède donc la propriété de conserver
le produit scalaire :

$$\scalaire{\mathcal{F}(u)}{\mathcal{F}(v)} = \scalaire{u}{v}$$


*** Convolution

La transformeèe d'un produit de convolution s'écrit :

#+BEGIN_CENTER
\(
\mathcal{F}(u \star v)(y) =
\int\limits_{-\infty}^{+\infty} \exp(-2\pi\img x y) dx
\int\limits_{-\infty}^{+\infty} u(x-z) v(z) dz
\)
#+END_CENTER

Considérons le changement de variable :

#+BEGIN_CENTER
\(
\xi = x - z  \\
\eta = z
\)
#+END_CENTER

On a alors $x = \xi + \eta$ et :

#+BEGIN_CENTER
\(
\mathcal{F}(u \star v)(y) =
\int\limits_{-\infty}^{+\infty} u(\xi) \exp(-2\pi\img \xi y) d\xi
\int\limits_{-\infty}^{+\infty} v(\eta) \exp(-2\pi\img \eta y) d\eta
\)
#+END_CENTER

c'est-à-dire :

$$\mathcal{F}(u \star v) = \mathcal{F}(u)\mathcal{F}(v)$$


*** Dérivées

Soit $u$ une fonction qui s'annule à l'infini. La transformeée de Fourier
de sa dérivée s'écrit :

#+BEGIN_CENTER
\(
\mathcal{F}\left(\OD{u}{x}\right)(y) =
\int\limits_{-\infty}^{+\infty} \OD{u}{x}(x)\exp(-2\pi\img x y) dx
\)
#+END_CENTER

En intégrant par partie, et en tenant compte du fait que
les limites à l'infini sont nulles, il vient :

#+BEGIN_CENTER
\(
\mathcal{F}\left(\OD{u}{x}\right)(y) =
- (-2\pi\img y) \int\limits_{-\infty}^{+\infty} u(x)\exp(-2\pi\img x y) dx
\)
#+END_CENTER

et finalement :

$$\mathcal{F}\left(\OD{u}{x}\right)(y) =  2 \pi \img y \mathcal{F}(y)$$


*** Déphasage

Considérons l'opérateur de translation :

$$t_a(u)(x) = u(x-a)$$

La transformeée de Fourier d'une translatée de la fonction $u$ s'écrit :

#+BEGIN_CENTER
\(
\mathcal{F}\left[t_a(u)\right](y) =
\int\limits_{-\infty}^{+\infty} u(x-a) \exp(-2\pi\img x y) dx \\
\mathcal{F}\left[t_a(u)\right](y) = \exp(-2\pi\img a y)
\int\limits_{-\infty}^{+\infty} u(x-a) \exp(-2\pi\img (x-a) y) dx
\)
#+END_CENTER

Mais comme $dx = d(x-a)$, on en déduit que :

$$\mathcal{F}\left[t_a(u)\right](y) = \exp(-2\pi\img a y)\mathcal{F}(u)(y)$$


*** Dilatation

Soit $d_a$ l'opérateur de dilatation :

$$d_a(u)(x) = u(a x)$$

où $a > 0$ est un réel strictement positif.

La transformeée de Fourier de la fonction dilaté $d_a(u)$ s'écrit :

#+BEGIN_CENTER
\(
\mathcal{F}\left[d_a(u)\right](y) =
\int\limits_{-\infty}^{+\infty} u(a x) \exp(-2\pi\img x y) dx
\)
#+END_CENTER

Considérons le changement de variable $z = a x$. On a alors :

#+BEGIN_CENTER
\(
\mathcal{F}\left[d_a(u)\right](y) =
\unsur{a}\int\limits_{-\infty}^{+\infty} u(z)
\exp\left(-2\pi\img z \frac{y}{a}\right) dz \\
\mathcal{F}\left[d_a(u)\right](y) = \unsur{a}\mathcal{F}(u)(y/a)
\)
#+END_CENTER

c'est-à-dire :

$$\mathcal{F}\left[d_a(u)\right] = \unsur{a}\mathcal{F}\left[d_{1/a}(u)\right]$$


*** Gaussienne

Définissons la gaussienne $G$ :

$$G(x) = \exp(-\pi x^2)$$

Sa transformeée s'écrit :

$$\mathcal{F}(G)(y) = \int\limits_{-\infty}^{+\infty} \exp(-\pi x^2 - 2\pi\img x y) dx$$

Il est clair que :

#+BEGIN_CENTER
\(
\exp\left[ -\pi (x+\img y)^2 \right] =
\exp(-\pi x^2 - 2 \pi\img x y)\exp(\pi y^2)
\)
#+END_CENTER

Il vient donc, en effectuant le changement de variable
$\xi = x + \img y$ :

$$\mathcal{F}(G)(y) = \exp(-\pi y^2) \int\limits_{-\infty}^{+\infty} \exp(-\pi \xi^2) d\xi$$

Mais nous avons vu au chapitre \ref{chap:integ} que cette dernière
intégrale vaut $1$. Donc :

$$\mathcal{F}(G) = G$$

La transformeée de Fourier laisse $G$ inchangée.


** Transformeée de Fourier

La transformeée de Fourier (voir chapitre \ref{chap:fourier}) est définie par :

$$\mathcal{F}(u)(y) = \int_{\setR} u(x) \exp(2\pi \img x y) dx$$

où $\img = \sqrt{-1}$. On a :

#+BEGIN_CENTER
\(
\int_{\setR} \mathcal{F}(u)(y) v(y) dy = \int_{\setR} u(x) v(y) \exp(2\pi \img x y) dx dy \\
\int_{\setR} \mathcal{F}(u)(y) v(y) dy = \int_{\setR} u(x) \mathcal{F}(v)(x) dx
\)
#+END_CENTER

et donc :

$$\forme{\mathcal{F}(u)}{v} = \forme{u}{\mathcal{F}(v)}$$


* Ondelettes

#+TOC: headlines 1 local

\label{chap:ondelet}

Les ondelettes constitue un outil d'analyse de signal puissant. L'idée est de décomposer une
fonction en différentes échelles, des échelles grossières jusqu'à des résolution très fines.
Contrairement aux séries de Fourier, elles ont une influence locale et des relations simples
entres les différentes échelles représentées, ce qui permet  de passer rapidement
(en $\mathcal{O}(N)$) d'une représentation à une autre.

Elles sont fort utilisées en compression de donnée (son, image, ...)
où les coefficients les plus négligeables sont ignorés.


** Introduction

AFAIRE : ARRANGER LE CHAPITRE

Le plus simple est de commencer avec un exemple célèbre : les ondelettes de Haar :

#+BEGIN_CENTER
\(
\varphi(x) = \indicatrice_{[0,1[}(x) \\
\psi(x) = \indicatrice_{[0,1/2[}(x) - \indicatrice_{[1/2,1[}(x)
\)
#+END_CENTER

La fonction $\varphi$ est appelée fonction d'échelle, tandis que
$\psi$ est l'ondelette proprement dite. La propriété principale
d'un système d'ondelette est qu'il permet facilement de changer
d'échelle. Ainsi, on a :

#+BEGIN_CENTER
\(
\varphi(x) = \varphi(2x) + \varphi(2x-1) = a_0^0 \varphi(2x) + a_1^0 \varphi(2x-1) \\
\psi(x) = \varphi(2x) - \varphi(2x-1) = a_0^1 \varphi(2x) + a_1^1 \varphi(2x-1)
\)
#+END_CENTER

où l'on a posé $a_0^0 = 1$,  $a_1^0 = 1$,  $a_0^1 = 1$,  $a_1^1 = -1$.
En inversant les deux relations ci-dessus, on arrive à :

#+BEGIN_CENTER
\(
\varphi(2x) = \frac{1}{2} ( \varphi(x) + \psi(x) ) \\
\varphi(2x-1) = \frac{1}{2} ( \varphi(x) - \psi(x) )
\)
#+END_CENTER

Les deux représentations ci-dessous sont donc équivalentes :

#+BEGIN_CENTER
\(
f(x) = f_1 \varphi(2x) + f_2 \varphi(2x-1) \\
f(x) = \frac{f_1+f_2}{2} \varphi(x) + \frac{f_1 - f_2}{2} \psi(x)
\)
#+END_CENTER

La différence est que l'on représente $f$ tantôt comme une somme de fonctions
de base de même échelle, tantôt comme une superposition d'échelles différentes.
En effet, $\varphi(2x), \varphi(2x-1),\psi(x) $ représentent l'échelle fine $1/2$, tandis
que $\varphi(x)$ représente l'échelle grossière $1$ (un petit dessin peut aider).

Une autre propriété importante est que le support des fonctions $\varphi$ et $\psi$ est borné,
et donc la fonction  $\varphi_{jk} : x \mapsto \varphi( 2^j x - k )$ à un support $S_j$ de plus
en plus fin lorsque $j$ augmente. On dit que les ondelettes ont une influence locale.


** Définition

Nous allons construire un système d'ondelettes générique à partir des coefficients :

$$a_k^i \quad : \quad i = 0,1,...,m-1 \qquad k, m \in \setZ, m > 1$$

Adoptant la convention $\sum_k = \sum_{k \in \setZ}$,
nous demandons que ces coefficients vérifient les propriétés de normalisation :

#+BEGIN_CENTER
\(
\sum_k a^0_{p+m k} = 1 \\
\sum_k a_k^i = m \indicatrice_{i,0}
\)
#+END_CENTER

et d'orthogonalisation suivantes :

#+BEGIN_CENTER
\(
\sum_k a_{k + m r}^i a_{k + m s}^j = m \indicatrice_{ij} \indicatrice_{rs} \\
\sum_k\sum_{i=0}^{m-1} a^i_{r+m k} a^i_{s+m k} = m \indicatrice_{rs}
\)
#+END_CENTER

Par ailleurs, afin d'assurer le caractère compact des fonctions associées, on impose
la nullité des coefficients en dehors d'un certain domaine :

#+BEGIN_CENTER
\(
a^i_k = 0 \qquad \forall k \notin \{0,1,2,.... m g - 1 \}
\)
#+END_CENTER

où $g > 0$ est un entier fixé.

Nous allons voir dans la suite que ces propriétés permettent de montrer d'importants
résultats sur le comportement des ondelettes associées. Remarquons déjà les conséquences
directes suivantes :

#+BEGIN_CENTER
\(
\sum_k a^0_{p-m k} = 1 \\
\sum_k\sum_{i=0}^{m-1} a^i_{r-m.k} a^i_{s-m.k} = m \indicatrice_{rs} \\
\)
#+END_CENTER

Dans la suite, nous utilisons le produit scalaire :

$$\scalaire{u}{v} = \int_{\setR} u(x) v(x) dx$$



** Construction

La fonction d'échelle s'obtient en partant de :

$$\varphi^{(0)}(x) = \indicatrice_{[0,1[}(x)$$

et en itérant :

$$\varphi^{(n)}(x) = \sum_k a_k^0 \varphi^{(n-1)}(m x - k)$$

Supposant que l'algorithme converge vers un point fixe (voir chapitre \ref{chap:ode}),
on définit la fonction d'échelle :

$$\varphi = \lim_{n\rightarrow\infty} \varphi^{(n)}$$

Qui possède la propriété :

$$\varphi(x) = \sum_k a_k^0 \varphi(m x - k)$$

Le système d'ondelettes est définit finalement par :

#+BEGIN_CENTER
\(
\varphi(x) = \sum_k a_k^0 \varphi(m x - k) \\
\psi^i(x) = \sum_k a_k^i \varphi(m x - k)
\)
#+END_CENTER



** Propriétés

Les propriétés des $a^i_k$ permettent de montrer, par récurrence sur $n$, que :

#+BEGIN_CENTER
\(
\int_{\setR} \varphi(x) dx = 1 \\
\int_{\setR} \psi^i(x) dx = 0
\)
#+END_CENTER

En effet, on a $\int_{\setR} \varphi^{(0)} = 1$ et si on suppose que
 $\int_{\setR} \varphi^{(n-1)} = 1$ alors :

#+BEGIN_CENTER
\(
\int_{\setR} \varphi^{(n)}(x) dx = \sum_k a_k^0 \int_{\setR} \varphi^{(n-1)}(m x - k) dx \\
\int_{\setR} \varphi^{(n)}(x) dx = \left( \sum_k a_k^0 \right) \frac{1}{m} \int_{\setR} \varphi^{(n-1)}(\xi) d\xi = 1
\)
#+END_CENTER

Par ailleurs on a :

#+BEGIN_CENTER
\(
\int_{\setR} \psi^i(x) dx =   \sum_k a_k^i \int_{\setR} \varphi(m x - k) dx \\
\int_{\setR} \psi^i(x) dx = \left( \sum_k a_k^i \right) \frac{1}{m} \int_{\setR} \varphi(\xi) d\xi = 0
\)
#+END_CENTER

On peut aussi montrer par récurrence :

$$\support(\varphi) \subseteq \left[0, 1 + (g-1) \sum_{k=0}^{+\infty} \left( \frac{1}{m} \right)^k \right] = \left[0, 1 + (g-1) \frac{m}{m-1} \right]$$

Le support de $\varphi$ est donc bien borné.

Une autre propriété importante qui va nous permettre de prouver la convergence
des développements en ondelettes est la partition de l'unité :

$$\sum_k \varphi(x-k) = 1 \qquad \forall x \in \setR$$

En effet, il est clair que $\sum_k \varphi^{(0)}(x-k) = 1$. Partant de l'hypothèse de récurrence $\sum_k \varphi^{(n-1)}(x-k) = 1$, on obtient :

#+BEGIN_CENTER
\(
\sum_k \varphi^{(n)}(x-k) = \sum_k\sum_l a^0_l \varphi^{(n-1)}\left( m (x - k) - l \right) \\
\sum_k \varphi^{(n)}(x-k) = \sum_l\sum_k a^0_l \varphi^{(n-1)}(m x - m k - l)
\)
#+END_CENTER

Posant $p = m k + l$, cette dernière équation devient :

$$\sum_k \varphi^{(n)}(x-k) = \sum_p \varphi^{(n-1)}(m x - p) \sum_k  a^0_{p - m k}$$

Mais comme $ \sum_k  a^0_{p - m k} = 1$ quel que soit la valeur de $p$, on en déduit que :

$$\sum_k \varphi^{(n)}(x-k) = \sum_p \varphi^{(n-1)}(m x - p) = 1$$

et la propriété de partition de l'unité est démontréé en passant à la limite :

$$\sum_k \varphi(x-k) = \lim_{n \rightarrow +\infty} \sum_k \varphi^{(n)}(x-k) = 1$$


** Niveaux

On définit la fonction d'échelle et les ondelettes du niveau $j \in \setN$ comme étant les
dilatations translatées des fonctions $\varphi,\psi^i$ :

#+BEGIN_CENTER
\(
\varphi_{jk}(x) = m^{j/2} \varphi(m^j x - k) \\
\psi^i_{jk}(x) = m^{j/2} \psi^i(m^j x - k)
\)
#+END_CENTER

Le coefficient $m^{j/2}$ permet d'obtenir les normalisations : $\scalaire{\varphi_{jk} }{\varphi_{jk} } = 1$ et $\scalaire{\psi^i_{jk} }{\psi^i_{jk} } = 1$

La définition du système d'ondelettes permet d'obtenir les relations suivantes
entres échelles voisines :

#+BEGIN_CENTER
\(
\varphi_{jk} = \frac{1}{\sqrt{m}} \sum_l a^0_l \varphi_{j+1,m k + l} = \frac{1}{\sqrt{m}} \sum_p a^0_{p - m k} \varphi_{j+1,p}\\
\psi^i_{jk} = \frac{1}{\sqrt{m}} \sum_l a^i_l \varphi_{j+1,m k + l} =  \frac{1}{\sqrt{m}} \sum_p a^i_{p - m k} \varphi_{j+1,p}\\
\)
#+END_CENTER



** Développement en série et algorithme de Mallat


*** Convergence

Commençons par remarquer que :

$$\sup_{\xi\in\setR} \varphi_{jk}(\xi) = m^{j/2} \sup_{\xi\in\setR} \varphi(\xi) = m^{j/2} M$$

où $M$ ne dépend pas de $j$.

Soit la mesure de Lebesgue $\mu$ définie par :

$$\mu([a,b]) = \abs{b-a}$$

On a alors :

$$\mu(\support(\varphi_{jk})) = m^{-j} \mu(\support(\varphi)) = m^{-j} \indicatrice_0$$

où $\indicatrice_0$ de dépend pas de $j$. Le support des fonctions $\varphi_{jk}$ est donc de
plus en plus fin lorsque $j$ augmente.

Nous définissons la famille d'ensembles :

$$K_j(x) = \{ k \in \setZ : \varphi_{jk}(x) \ne 0 \}$$

où $x \in \setR$. On obtient, à partir des propriétés du support de $\varphi$, que :

$$m^j x - k \in \suppport(\varphi) \Rightarrow m^j x - 2 g \le k \le m^j x$$

pour tout $k\in K_j(x)$. On a donc :

$$\# K_j(x) \le 2 g$$

Pour un réel $x$ fixé, le nombre de $\varphi_{jk}(x)$ non nuls est donc borné, et ce quelle que soit la valeur de $j \in \setN$.

Choisissons $x,y \in \suppport(\varphi_{jk})$. On a alors :

$$\abs{x-y} \le \indicatrice_0 m^{-j}$$

et par continuité de $f$ :

$$\abs{f(x)-f(y)} \le \epsilon_j$$

avec :

$$\lim_{j \rightarrow +\infty} \epsilon_j = 0$$

Utilisant un simple changement de variable $\xi = m^j y - k$, on obtient :

#+BEGIN_CENTER
\(
\int_{\setR} \varphi_{jk}(y) dy  = \int_{\setR} m^{j/2} \varphi\left( m^j y - k \right) dy \\
\int_{\setR} \varphi_{jk}(y) dy  = \int_{\setR} m^{j/2} \varphi(\xi) m^{-j} d\xi \\
\int_{\setR} \varphi_{jk}(y) dy  = m^{-j/2} \int_{\setR} \varphi(\xi) d\xi = m^{-j/2}
\)
#+END_CENTER

Comme $m^j x \in \setR$, on a aussi :

$$\sum_k \varphi_{jk}(x) = m^{j/2} \sum_k \varphi( m^j x - k ) = m^{j/2}$$

Donc :

#+BEGIN_CENTER
\(
\sum_k \varphi_{jk}(x) \int_{\setR} \varphi_{jk}(y) dy = m^{-j/2} \sum_k \varphi_{jk}(x) \\
\sum_k \varphi_{jk}(x) \int_{\setR} \varphi_{jk}(y) dy = m^{-j/2} m^{j/2} = 1
\)
#+END_CENTER

On en déduit en particulier que :

$$f(x) = \sum_k \varphi_{jk}(x) \int_{\setR} f(x) \varphi_{jk}(y) dy$$

On aimerait bien montrer que les fonctions échelles de niveau $j$ quelconque forment un cadre (voir chapitre \ref{chap:tensor}), c'est-à-dire que :

$$f = \sum_k\scalaire{f}{\varphi_{jk}}\varphi_{jk}$$

Pour $x$ fixé, seuls les $k$ appartenant à $K_j(x)$ vont donner une contribution non nulle
à la somme :

$$\sum_k\scalaire{f}{\varphi_{jk}}\varphi_{jk}(x)} = \sum_{k \in K_j(x) } \scalaire{f}{\varphi_{jk}}\varphi_{jk}(x)}$$

Rassemblant tous les résultats ci-dessus, on en déduit que :

#+BEGIN_CENTER
\(
\abs{f(x) - \sum_k\scalaire{f}{\varphi_{jk}}\varphi_{jk}(x)} =
\abs{\sum_{k \in K_j}\varphi_{jk}(x) \int_{\setR} \left( f(x) - f(y) \right) \varphi_{jk}(y) dy   } \\
\abs{f(x) - \sum_k\scalaire{f}{\varphi_{jk}}\varphi_{jk}(x)} \le
2 g M m^{j/2} \epsilon_j \indicatrice_0 m^{-j} M m^{j/2} = 2 g M^2 \indicatrice_0 \epsilon_j
\)
#+END_CENTER

qui tend bien vers 0 lorsque $j$ tend vers l'infini.


*** Algorithme de Mallat

Considérons à présent l'approximation suivante :

$$f(x) \approx \tilde{f}(x) = \sum_k c_{Rk} \varphi_{Rk}(x)$$

où $c_{Rk} = \scalaire{f}{\varphi_{Rk}}$. Nous allons maintenant montrer par récurrence que pour tout $J \le R$ :

$$\tilde{f}(x) = \sum_k c_{Jk} \varphi_{Jk}(x) + \sum_k \sum_{i=1}^{m-1} \sum_{j=J}^{R} d^i_{jk} \psi^i_{jk}(x)$$

où :

#+BEGIN_CENTER
\(
c_{jk} = \scalaire{ f  }{ \varphi_{jk}  } \\
d^i_{jk} = \scalaire{ f  }{ \psi^i_{jk}  }
\)
#+END_CENTER

Il suffit pour cela de constater que :

#+BEGIN_CENTER
\(
\sum_k c_{jk} \varphi_{jk} + \sum_k\sum_{i=1}^{m-1} d^i_{jk} \psi^i_{jk} =
\sum_k \scalaire{ f  }{ \varphi_{jk} } \varphi_{jk} + \sum_k\sum_{i=1}^{m-1} \scalaire{ f  }{ \psi^i_{jk}  } \psi^i_{jk} \\
= \frac{1}{m}\sum_{p,q}\sum_k \sum_{i=0}^{m-1} \scalaire{ f  }{ \varphi_{j+1,p} } \varphi_{j+1,q} a^i_{p - m k} a^i_{q - m k} \\
= \sum_{p,q} \scalaire{ f  }{ \varphi_{j+1,p} } \varphi_{j+1,q} \frac{1}{m} \sum_k \sum_{i=0}^{m-1}  a^i_{p - m k} a^i_{q - m k} \\
= \sum_{p,q} \scalaire{ f  }{ \varphi_{j+1,p} } \varphi_{j+1,q} \indicatrice_{pq} \\
= \sum_p \scalaire{ f  }{ \varphi_{j+1,p} } \varphi_{j+1,p}
\)
#+END_CENTER

en utilisant les propriétés des $a^i_k$. On peut donc construire le développement du niveau $j+1$ à partir des fonctions
d'échelles et des ondelettes du niveau $j$.
La définition des $c_{jk}$, $d^i_{jk}$  combinée aux équations reliant les échelles voisines nous donne :

#+BEGIN_CENTER
\(
c_{jk} = \scalaire{ f  }{ \varphi_{jk}  }  =  \frac{1}{\sqrt{m}}\sum_p\scalaire{ f  }{ \varphi_{j+1,p}  } a^0_{p - m k} \\
c_{jk} = \frac{1}{\sqrt{m}}\sum_p c_{j+1,p} a^0_{p-m.k} = \frac{1}{\sqrt{m}}\sum_l c_{j+1,l + m k} a^0_{l}
\)
#+END_CENTER

ainsi que :

#+BEGIN_CENTER
\(
d^i_{jk} = \scalaire{ f  }{ \psi^i_{jk}  }  =  \frac{1}{\sqrt{m}}\sum_p\scalaire{ f  }{ \varphi_{j+1,p}  } a^i_{p - m k} \\
d^i_{jk} = \frac{1}{\sqrt{m}}\sum_p c_{j+1,p} a^i_{p - m k} = \frac{1}{\sqrt{m}}\sum_l c_{j+1,l + m k} a^i_{l}
\)
#+END_CENTER

La relation inverse s'obtient à partir de :

#+BEGIN_CENTER
\(
\sum_p \scalaire{ f }{ \varphi_{j+1,p} } \varphi_{j+1,p} = \sum_k c_{jk} \varphi_{jk} + \sum_k\sum_{i=1}^{m-1} d^i_{jk} \psi^i_{jk} \\
\sum_p c_{j+1,p} \varphi_{j+1,p} = \frac{1}{\sqrt{m}}\sum_p \varphi_{j+1,p} \left[ \sum_k c_{jk} a^0_{p - m k}
+ \sum_k\sum_{i=1}^{m-1} d^i_{jk} a^i_{p - m k} \right] \\
\)
#+END_CENTER

En comparant les coefficients des $\varphi_{j+1,p}$, et comme cette équation doit être valable pour tout $x$, on a :

#+BEGIN_CENTER
\(
c_{j+1,p} = \frac{1}{\sqrt{m}}\sum_k c_{jk} a^0_{p-m.k} + \sum_k\sum_{i=1}^{m-1} d^i_{jk} a^i_{p - m k}  \\
c_{j+1,p} = \frac{1}{\sqrt{m}}\sum_k c_{jk} a^0_{p-m.k} + \sum_k\sum_{i=1}^{m-1} d^i_{jk} a^i_{p - m k}  \\
\)
#+END_CENTER

On voit donc que pour passer d'une représentation mono-échelle

$$f(x) = \sum_k c_{Rk} \varphi_{Rk}(x)$$

à une représentation multi-échelle

$$f(x) = \sum_k c_{Jk} \varphi_{Jk}(x) + \sum_k \sum_{i=1}^{m-1} \sum_{j=J}^{R} d^i_{jk} \psi^i_{jk}(x)$$

(ou l'inverse) il suffit d'appliquer successivement les équations ci-dessus reliant entre-eux les coefficients
$c_{j+1,p}$, $c_{jk}$, $d^i_{jk}$, pour $j = R-1,R-2,...,J$.
En pratique, on approxime les coefficients du niveau de résolution maximal $R$ par :

$$c_{Rk} \approx m^{R/2} f \left(\frac{k}{m^R}\right)$$

Lorsque $f$ est assez régulière pour avoir la convergence :

$$f(x) = \lim_{R \to +\infty} \sum_k c_{Rk} \varphi_{Rk}(x)$$

on écrit :

$$f(x) = \sum_k c_{Jk} \varphi_{Jk}(x) + \sum_k \sum_{i=1}^{m-1} \sum_{j=J}^{+\infty} d^i_{jk} \psi^i_{jk}(x)$$
