
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 03 : Nombres
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Naturels

#+TOC: headlines 1 local

\label{chap:naturels}


** Dépendances

  - Chapitre \ref{chap:ensembles} : Les ensembles
  - Chapitre \ref{chap:operations} : Les opérations
  - Chapitre \ref{chap:algebre} : L'algèbre
  - Chapitre \ref{chap:ordres} : Les ordres
  - Chapitre \ref{chap:extrema} : Les extrema


** Introduction

Nous allons étudier l'ensemble des naturels :

$$\setN = \{ 0,1,2,3,4,5,6,7,8,9,10,... \}$$


** Addition

L'addition usuelle sur $\setN$, notée $+ : \setN \times \setN \mapsto \setN$, est définie par :

\begin{align}
m + 0 &= 0 \\
m + n^+ &= m^+ + n
\end{align}

pour tout $m,n \in \setN$.

En utilisant récursivement la définition, on arrive à :

\begin{align}
m + 1 &= m + 0^+ = m^+ + 0 = m^+ \\
m + 2 &= m + 0^{++} = m^+ + 0^+ = m^{++} + 0 = m^{++} \\
\vdots && \\
m + n &= ... = m^{+...+}
\end{align}

où $+...+$ désigne l'opération de succession appliquée $n$ fois. L'addition de $n$ revient donc à effectuer $n$ opérations de succession.


*** Dualité

Posant $i = m$ et $j = n^+$, on voit clairement que :

$$i + j = i^+ + j^-$$


*** Neutre additif

Pour $m \in \setN$ quelconque, on a :

$$0 + m = 0^{+...+}$$

où $+...+$ désigne l'opération de succession appliquée $m$ fois. Mais comme $0^{+...+} = m$, on a :

$$0 + m = m$$

On a donc $0 + m = m + 0 = m$. On dit que $0$ est neutre pour l'addition. On voit clairement d'après la définition que $0$ est le seul neutre pour l'addition.


*** Commutativité

Soit $m,n \in \setN$. Par définition de l'addition, on a :

$$m + n = m^{+...+} = 0^{+.....+}$$

où $+.....+$ réprésente $m$ suivies de $n$ opérations de successions. On a aussi :

$$n + m = n^{+...+} = 0^{+.....+}$$

où $+.....+$ réprésente $n$ suivies de $m$ opérations de successions. Les deux résultats étant identiques,on a :

$$m + n = n + m$$

On dit que l'addition sur $\setN$ est commutative.


*** Associativité

Soit $m,n,p \in \setN$. Développons l'addition $m + (p + n)$. On a :

$$m + (p + n) = m + p^{+...+}$$

où $+...+$ désigne l'opération de succession appliquée $n$ fois. Il vient ensuite :

#+BEGIN_CENTER
\(
m + (p + n) = m^+ + p^{+...+-} \\
\vdots \\
m + (p + n) = m^{+...+} + p^{+...+-...-}
\)
#+END_CENTER

où $+...+-...-$ désigne l'opération de succession appliquée $n$ fois, suivie de l'opération de prédécession appliquée $n$ fois également. Mais comme le prédécesseur du sucesseur est égal à lui-même par définition, on a $p^{+-} = p$. On constate en développant que la même propriété doit être vérifiée lorsque les opérations de succession et de prédécession sont appliquées un nombre quelconque mais identique de fois. On a donc :

$$p^{+...+-...-} = p$$

En tenant compte de ces résultats dans le développement de la somme ci-dessus, on arrive à :

$$m + (p + n) = m^{+...+} + p$$

Mais $m^{+...+}$ n'est rien d'autre que la somme $m + n$, et :

$$m + (p + n) = (m + n) + p$$

L'addition étant commutative, on peut inverser $p$ et $n$ pour obtenir :

$$m + (n + p) = (m + n) + p$$

On peut donc associer les termes d'une somme comme on le désire, le résultat restera identique. On dit que l'addition sur $\setN$ est associative. On note aussi :

$$m + n + p = m + (n + p) = (m + n) + p$$


** Ordre

Soit $m,n \in \setN$. On dit que $n$ est plus petit ou égal à $m$, et on le note :

$$n \le m$$

si on peut trouver un $p \in \setN$ tel que :

$$m = n + p$$

En évaluant les additions $n+1$ et $n^- + 1$, on obtient :

\begin{align}
n^- + 1 &= n \\
n + 1 &= n^+
\end{align}

Le choix $p = 1$ nous montre alors que :

$$n^- \le n \le n^+$$


*** Plus grand ou égal

On note aussi :

$$m \ge n$$

pour signifier que $n \le m$.


*** Total

Soir $m,n \in \setN$. Comme $m$ est, directement ou indirectement,
un successeur ou un prédécesseur de $n$, on a soit :

$$m \le n$$

soit :

$$n \le m$$

L'ordre usuel sur $\setN$ est total.


*** Ordre strict

On note :

$$n \strictinferieur m$$

ou :

$$m \strictsuperieur n$$

lorsque $n \le m$ et $m \ne n$.


*** Extrema

Comme tous les éléments de $\setN$ sont supérieurs au égaux à $0$, on a clairement :

$$\minor \setN = \{ 0 \}$$

et :

$$\inf \setN = \min \setN = 0$$

Par contre, si on suppose avoir trouvé $s \in \major \setN$, on a $s \le s^+ \in \setN$ ce qui contredit l'hypothèse de majorant. L'ensemble des majorants est donc vide, et le supremum n'existe pas dans $\setN$. On note donc :

$$\sup \setN = +\infty$$


** Ordre et addition

Soit $a,b,c,d \in \setN$. Supposons que :

$$a \le b$$
$$c \le d$$

On peut donc trouver $p,q \in \setN$ tels que :

\begin{align}
b &= a + p \\
d &= c + q
\end{align}

En additionnant ces deux équations, on obtient :

$$b + d = a + p + c + q = (a + c) + (p + q)$$

Comme $p + q$ est également un naturel, on en conclut que :

$$a + c \le b + d$$

L'ordre est donc conservé lorsqu'on ajoute au moins autant au grand nombre qu'au petit. On parle d'invariance sous l'addition.


** Positivité

\label{sec:positivite_des_naturels}

Soit $n \in \setN$. La neutralité de $0$ pour l'addition nous permet d'écrire :

$$n = 0 + n$$

On en déduit que :

$$n \ge 0$$

pour tout $n \in \setN$ et :

$$n \strictsuperieur 0$$

lorsque $n \ne 0$.


** Soustraction

Soit l'ensemble :

$$\Delta = \{ (m,n) \in \setN^2 : n \le m \}$$

Choisissons $(m,n) \in \Delta$. On peut trouver $p \in \setN$ tel que :

$$m = n + p$$

Comme :

$$n + p = p + n = p^{+...+} = m$$

on voit que :

$$p = m^{-...-}$$

où $-...-$ désigne $n$ opérations de prédécessions. Le $p$ ainsi défini est donc unique. On dit que $p$ est la soustraction de $m$ et $n$, et on le note :

$$p = m - n$$


*** $m \le n$

Si $m \strictinferieur n$, calculer la soustraction :

$$p = m - n = m^{-...-} = 0^{+...+-...-}$$

reviendrait à effectuer plus d'opérations de prédécessions que de sucessions. Nous serions donc amenés à devoir évaluer le prédécesseur de l'élément racine $0$, qui n'existe pas dans $\setN$. Cette opération n'est par conséquent pas définie.


*** Neutralisation

La définition implique directement l'équivalence :

#+BEGIN_CENTER
\(
m = n = n + 0 \\
\Longleftrightarrow \\
m - n = 0
\)
#+END_CENTER


*** Associativité

Soit $m,n,p \in \setN$ avec $n + p \le m$. On a trivialement :

$$(m - n) - p = m - (n + p)$$

On note aussi :

$$m - n - p = (m - n) - p = m - (n + p)$$


*** Commutativité

Soit $m,n,p \in \setN$ avec $n + p \le m$. On voit que :

$$m - n - p = m - (n + p) = m - (p + n) = m - p - n$$


*** Associativité mixte

Soit $m,n,p \in \setN$ avec $p \le n$. On a trivialement :

$$(m + n) - p = m + (n - p)$$

On note aussi :

$$m + n - p = (m + n) - p = m + (n - p)$$


*** Commutativité mixte

Soit $m,n,p \in \setN$ avec $m,p \le n$. On a trivialement :

\begin{align}
m + n - p = (m + n) - p &= (n + m) - p \\
&= n + (m - p) \\
&= (m - p) + n \\
&= m - p + n
\end{align}


** Ordre et soustraction

Soit $a,b,c,d \in \setN$. Supposons que :

$$a \le b$$
$$c \ge d$$

On peut donc trouver $p,q \in \setN$ tel que :

$$b = a + p$$

$$d + q = c$$

En soustrayant ces deux équations, on obtient :

$$b - d - q = a + p - c$$

$$b - d = a - c + p + q$$

Comme $p + q$ est aussi un naturel, on en conclut que :

$$a - c \le b - d$$

L'ordre est donc conservé lorsqu'on soustrait au moins autant au petit nombre qu'au grand. On parle d'invariance pour la soustraction.


** Multiplication

Soit $m,n \in \setN$. La multiplication usuelle, notée $\cdot : \setN \times \setN \mapsto \setN$, est définie par :

$$m \cdot 0 = 0$$

$$m \cdot n^+ = ( m \cdot n ) + m$$

Posant $i = m$ et $j = n^+$, on en déduit que :

$$i \cdot 0 = 0$$

$$i \cdot j = ( i \cdot j^- ) + i$$


*** Priorité

Afin d'alléger les notations, nous convenons que la multiplication est toujours prioritaire sur l'addition. On pose donc :

$$i \cdot j + k = ( i \cdot j ) + k$$

pour tout $i,j,k \in \setN$.

La définition peut alors se réécrire :

$$m \cdot 0 = 0$$

$$m \cdot n^+ = m \cdot n + m$$


*** Notation

Lorsque cela ne pose pas de problème d'ambiguité, on note aussi :

$$m \ n = m \cdot n$$


*** Absorption

Soit $m \in \setN$. On déduit directement de la définition que :

\begin{align}
0 \cdot m &= 0 \cdot m^- + 0 \\
\vdots && \\
0 \cdot m &= 0 + ... + 0 = 0
\end{align}

On a donc $0 \cdot m = m \cdot 0 = 0$. On dit que $0$ est absorbant pour la multiplication.


*** Définition alternative

Soit $m \ge 1$. En utilisant récursivement la définition, on obtient :

\begin{align}
m \cdot n &= m \cdot n^- + m \\
&\vdots& \\
&= m \cdot 0 + m + ... + m \\
&= 0 + m + ... + m \\
&= m + ... + m
\end{align}

où le membre de droite compte $n$ terme « $m$ ». Mais comme $m = m^- + 1$, on a :

$$m \cdot n = m^- + 1 + ... + m^- + 1$$

La commutativité nous permet de regrouper les $n$ nombres $1$ à la fin :

$$m \cdot n = m^- + ... + m^- + 1 + ... + 1$$

Il est clair que :

$$1 + ... + 1 = 0^{+...+} = n$$

On a dès lors :

$$m \cdot n = m^- + ... + m^- + n$$

Comme le membre de droite contient $n$ termes $m^-$, on en conclut que :

$$m \cdot n = m^- \cdot n + n$$

qui est une version alternative de la définition.


*** Neutre multiplicatif

La définition implique que :

$$m \cdot 1 = m \cdot 0 + m = 0 + m = m$$

Mais en appliquant la définition alternative à $1 \cdot m$, il vient :

$$1 \cdot m = 0 \cdot m + m = m$$

On a donc $1 \cdot m = m \cdot 1 = m$. On dit que $1$ est neutre pour la multiplication.


*** Commutativité

Soit $m \in \setN$. On a vu que $m \cdot 0 = 0 \cdot m$. L'équation :

$$m \cdot n = n \cdot m$$

Est donc vérifiée pour $n = 0$.

Supposons à présent que :

$$n^- \cdot m = m \cdot n^-$$

En appliquant les deux alternatives de la définition, on a :

$$m \cdot n = m \cdot n^- + m$$

$$n \cdot m = n^- \cdot m + m$$

et donc :

$$m \cdot n = n \cdot m$$

Puisque cette égalité est vraie pour $n = 0 = 1^-$, on en déduit qu'elle est également vraie pour $n = 1 = 2^-$, pour $n = 2 = 3^-$, etc. Elle est donc vérifiée pour tout $n \in \setN$ : la multiplication est commutative.


*** Distributivité

Soit $m,n,p \in \setN$. On a :

$$m \cdot (n + p) = m + ... + m$$

où le membre de droite compte $n+p$ termes « $m$ ». Par associativité de l'addition, on peut regrouper les termes comme suit :

$$m \cdot (n + p) = (m + ... + m) + (m + ... + m)$$

où la première parenthèse compte $n$ termes et la seconde $p$ termes. On a donc :

$$m \cdot (n + p) = m \cdot n + m \cdot p$$

Par commutativité de la multiplication, on en déduit :

$$(n + p) \cdot m = n \cdot m + p \cdot m$$

On dit que la multiplication se distribue sur l'addition.


**** Sur la soustraction

Soit $m,n,p \in \setN$ avec $p \le n$ et :

$$q = n - p$$

On a :

$$m \cdot (p + q) = m \cdot p + m \cdot q$$

Mais comme $p + q = n$, il vient :

$$m \cdot n = m \cdot p + m \cdot (n - p)$$

On en déduit que :

$$m \cdot (n - p) = m \cdot n - m \cdot p$$

Par commutativité de la multiplication, on a également :

$$(n - p) \cdot m = n \cdot m - p \cdot m$$

On dit que la multiplication se distribue sur la soustraction.


*** Unicité de l'absorbant

Nous allons voir que l'absorbant est unique. Soit $a_1, a_2 \in \setN$ tels que :

$$a_1 \cdot n = a_2 \cdot n = 0$$

pour tout $n \in \setN$. On en déduit que :

$$a_1 \cdot n - a_2 \cdot n = 0$$

En utilisant la distributivité, on obtient :

$$(a_1 - a_2) \cdot n = 0$$

Mais comme ce résultat doit être valable pour tout $n \in \setN$, il est valable pour $n = 1$ et on a :

$$(a_1 - a_2) \cdot 1 = a_1 - a_2 = 0$$

Autrement dit, $a_1 = a_2$. L'absorbant est donc unique.


*** Associativité

Soit $m,n,p \in \setN$. On a :

$$m \cdot (n \cdot p) = m + ... + m$$

où le membre de droite compte $n \cdot p$ termes « $m$ ». Par associativité de l'addition, on peut les regrouper en $p$ parenthèses contenant chacune $n$ termes :

$$m \cdot (n \cdot p) = (m + ... + m) + ... + (m + ... + m)$$

ce qui revient à :

$$m \cdot (n \cdot p) = (m \cdot n) + ... + (m \cdot n)$$

Mais comme il y a $p$ parenthèses, on a :

$$m \cdot (n \cdot p) = (m \cdot n) \cdot p$$

La multiplication est donc associative. On note aussi :

$$m \cdot n \cdot p = m \cdot (n \cdot p) = (m \cdot n) \cdot p$$


*** Produit nul

Soit $m,n \in \setN$ tels que :

$$m \cdot n = 0$$

Nous allons prouver qu'au moins un des deux facteurs doit être nul. Supposons que $m, n \ne 0$. On a alors :

$$m \cdot n = n + ... + n = 0$$

Mais comme $n \ne 0$, on a :

$$n \strictsuperieur 0$$

et :

$$0 = n + ... + n \ge n \strictsuperieur 0$$

ce qui est impossible. On a donc l'implication :

$$m \cdot n = 0 \quad \Rightarrow \quad m = 0 \quad \mathrm{ou} \quad n = 0$$


** Notation décimale

Soit le tuple :

$$(i_0,i_1,i_2,...i_{n - 1},i_n) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^{n + 1}$$

La notation décimale associée est définie par :

$$i_n i_{n - 1} ... i_2 i_1 i_0 = i_0 + i_1 \cdot 10 + i_2 \cdot 10^2 + ... + i_{n - 1} \cdot 10^{n - 1} + i_n \cdot 10^n$$

Exemple :

$$7512 = 2 + 1 \cdot 10 + 5 \cdot 10^2 + 7 \cdot 10^3$$


** Division entière

Soit $m,n \in \setN$. On définit la division entière $\diventiere : \setN \times \setN \to \setN$ par :

$$m \diventiere n = \sup \{ k \in \setN : k \cdot n \le m \}$$

On dit que $m$ est le numérateur, $n$ le dénominateur et $m \diventiere n$ le quotient de $m$ par $n$.


*** Existence

Soit $m,n \in \setN$ avec $n \ne 0$ et :

$$A_{mn} = \{ k \in \setN : k \cdot n \le m \}$$

Pour tout naturel $p$ vérifiant $p \strictsuperieur m$, on a :

$$p \cdot n = p + ... + p \strictsuperieur p \strictsuperieur m$$

On en conclut que :

$$A_{mn} \subseteq \{ 0, 1, ..., m - 1, m \}$$

L'ensemble $A_{mn}$ contient donc un nombre fini d'éléments. Comme l'ordre
usuel sur $\setN$ est total, on en conclut que $A_{mn}$ admet un maximum
identique au suprémum. La division entière de $m$ par $n$ est donc bien définie :

$$m \diventiere n = \max A_{mn} = \sup A_{mn}$$

L'inclusion nous donne l'inégalité des maxima :

$$\max A_{mn} \le \max \{ 0, 1, ..., m - 1, m \} = m$$

On en déduit que :

$$m \diventiere n \le m$$


*** Division par zéro

Soit $m \in \setN$. Essayons d'évaluer la division $m \diventiere 0$. Par absorption de $0$, on voit que :

$$k \cdot 0 = 0 \le m$$

pour tout $k \in \setN$. Par conséquent :

$$\{ k \in \setN : k \cdot 0 \le m \} = \setN$$

Le supremum n'existe pas dans $\setN$ et la division par zéro n'est par conséquent pas définie. On le note symboliquement :

$$m \diventiere 0 = \sup \setN = +\infty$$


*** Division par un

Soit $m \in \setN$. On a :

$$m = m \cdot 1 \le m$$

et :

$$(m + 1) \cdot 1 = m + 1 \strictsuperieur m$$

On en déduit que :

$$m \diventiere 1 = m$$


*** Zéro divisé

Soit $n \in \setN$ avec $n \ne 0$. On a :

$$\{ k \in \setN : k \cdot n \le 0 \} = \{ 0 \}$$

La division entière de $0$ par $n$ est donc nulle :

$$0 \diventiere n = \sup \{ 0 \} = 0$$


*** Modulo

Soit $m,n \in \setN$. Par définition, on voit que :

$$(m \diventiere n) \cdot n \le m$$

Il est donc licite de définir le naturel :

$$r = m - (m \diventiere n) \cdot n$$

On dit que $r$ est le modulo de $m$ par rapport à $n$ et on le note :

$$m \modulo n = m - (m \diventiere n) \cdot n$$


*** Décomposition

Soit $m,n \in \setN$. Par définition du modulo, a la décomposition :

$$m = (m \diventiere n) \cdot n + m \modulo n$$


*** Reste

Soit $m,n \in \setN$. On dit aussi que $r = m \modulo n$ est le reste
de la division entière de $m$ par $n$.


*** Exacte

Soit $m,n \in \setN$. Si $m \modulo n = 0$, on dit que la division entière est exacte. Dans
ce cas, la décomposition s'écrit simplement :

$$m = (m \diventiere n) \cdot n$$


*** Bornes

Soit $m,n \in \setN$ et $k = m \diventiere n$. On sait déjà que :

$$m \modulo n \ge 0$$

par la positivité des naturels. Supposons de plus que :

$$m \modulo n = m - k \cdot n \ge n$$

on a alors :

$$m \ge n + k \cdot n = (k + 1) \cdot n$$

ce qui est contraire au caractère de supremum de $k$. Par conséquent :

$$0 \le m \modulo n \le n - 1$$


*** Solution

Soit $m,n,k,r \in \setN$ avec $n \ne 0$. Supposons que :

$$m = k \cdot n + r$$

Par positivité des naturels, on a $r \ge 0$ et :

$$k \cdot n \le m$$

d'où l'on conclut par définition du suprémum que $k \le m \diventiere n$.
Si on a également :

$$r \le n - 1$$

on a alors :

$$(k + 1) \cdot n = k \cdot n + n \strictsuperieur k \cdot n + r = m$$

On en conclut que $k + 1 \strictsuperieur m \diventiere n$. Donc :

$$m \diventiere n = k$$

et :

$$m \modulo n = r$$


*** Division de deux produits

Soit $m,n,q,i,j,k \in \setN$ avec $n,j \ne 0$ tels que :

$$m = q \cdot n$$
$$i = k \cdot j$$

On a alors les divisions exactes :

$$m \diventiere n = q$$
$$i \diventiere j = k$$

De plus :

$$m \cdot i = q \cdot k \cdot n \cdot j$$

ce qui signifie que :

$$(m \cdot i) \diventiere (n \cdot j) = q \cdot k$$

On a donc :

$$(m \cdot i) \diventiere (n \cdot j) = (m \diventiere n) \cdot (i \diventiere j)$$


*** Plus grand commun diviseur

Soit $m,n \in \setN$ avec $n \ne 0$. On définit le plus grand commun diviseur de $m$ et $n$ par :

$$\pgcd(m,n) = \sup \{ k \in \setN : m \modulo k = n \modulo k = 0 \}$$

Comme les divisions sont exactes, on a :

$$m = \big[ m \diventiere \pgcd(m,n) \big] \cdot \pgcd(m,n)$$

et :

$$n = \big[ n \diventiere \pgcd(m,n) \big] \cdot \pgcd(m,n)$$


*** Plus petit commun multiple

Soit $m,n \in \setN$. On définit le plus petit commun multiple de $m$ et $n$ par :

$$\ppcm(m,n) = \inf \{ k \in \setN : k \modulo m = k \modulo n = 0 \}$$

Comme les divisions sont exactes, on a :

$$\ppcm(m,n) = \big[ \ppcm(m,n) \diventiere m \big] \cdot m$$

et :

$$\ppcm(m,n) = \big[ \ppcm(m,n) \diventiere n \big] \cdot n$$


** Puissance

Soit $m,n \in \setN$ avec $n \ne 0$. Les puissances naturelles sont définies par :

\begin{align}
m^0 &= 1 \\
m^n &= m \cdot m^{n-1}
\end{align}

En appliquant récursivement la définition, on obtient :

\begin{align}
m^n &= m \cdot m^{n-1} \\
&\vdots& \\
&= m \cdot ... \cdot m
\end{align}

où le membre de droite compte $n$ facteurs « $m$ ».


*** Priorité

Nous convenons des règles de priorité :

$$m + n^p = m + (n^p)$$

$$m \cdot n^p = m \cdot (n^p)$$

valables pour tout $m,n,p \in \setN$.


*** Somme en exposant

Soit $m,n,p \in \setN$. On a :

$$m^{n+p} = m \cdot ... \cdot m$$

où le membre de droite compte $n+p$ facteur $m$. En regroupant les $n$ premiers facteurs dans une première parenthèse et les $p$ facteurs restant dans la seconde, on a :

$$m^{n+p} = (m \cdot ... \cdot m) \cdot (m \cdot ... \cdot m)$$

qui n'est rien d'autre que :

$$m^{n+p} = m^n \cdot m^p$$


*** Puissance d'un produit

$$\left(m \cdot n\right)^p = m \cdot n \cdot ... \cdot m \cdot n$$

où le membre de droite compte $p$ facteurs $m \cdot n$. La commutativité de la multiplication nous permet de les regrouper les $m$ d'un coté et les $n$ de l'autre :

$$\left(m \cdot n\right)^p = m \cdot ... \cdot m \cdot n \cdot ... \cdot n$$

c'est-à-dire :

$$\left(m \cdot n\right)^p = m^p \cdot n^p$$


*** Puissance d'une puissance

Soit $m,n,p \in \setN$. On a :

\begin{align}
\left(m^n\right)^p &= \left(m \cdot ... \cdot m\right)^p \\
&= m \cdot ... \cdot m
\end{align}

où le membre de droite compte $n \cdot p$ facteurs. On en conclut que :

$$\left(m^n\right)^p = m^{n \cdot p}$$


** Factorielle

Soit $n\in\setN$, $n \ne 0$. On définit la factorielle de $n$ par :

\begin{align}
0 ! &= 1 \\
n ! &= n \cdot (n-1) !
\end{align}

On a donc :

$$n ! = n \cdot (n - 1) \cdot (n - 2) \cdot ... \cdot 1 = 1 \cdot 2 \cdot 3 \cdot ... \cdot n$$


*** Priorité

On convient que :

$$x \cdot y ! = x \cdot (y !)$$


** Monoïde

$(\setN,+)$ et $(\setN,\cdot)$ sont des monoïdes.


* Entiers

#+TOC: headlines 1 local

\label{chap:entiers}


** Dépendances

  - Chapitre \ref{chap:naturels} : Les nombres naturels


** Principe général de l'extension

Nous allons à présent étendre progressivement les opérations vues sur les naturels. Le principe est de partir d'un ensemble $X$ et de construire un ensemble dérivé $Y$ (souvent $Y$ sera $X^2$). Ensuite, nous définissons l'opération étendue sur $Y$ de telle sorte qu'elle vérifie les nouvelles propriétés demandées en plus de celles déjà acquises sur $X$.


** Soustraction de naturels

On aimerait bien étendre la soustraction à deux naturels $i,j \in \setN$ quelconques. Malheureusement, nous avons vu que si $i \le j$, cette opération n'est pas définie. Pour contourner ce problème nous introduisons la notation différentielle :

$$i - j = (i,j)$$

où $(i,j) \in \setN^2$ est appelé nombre entier. Il ne nous reste plus ensuite qu'à définir convenablement les autres opérations pour conserver les propriétés intéressantes qu'elles possèdent sur $\setN$.


*** Notations

Soit $i \in \setN$. On note aussi :

#+BEGIN_CENTER
\(
i = i - 0 = (i,0) \\
-i = 0 - i = (0,i)
\)
#+END_CENTER

En particulier :

#+BEGIN_CENTER
\(
1 = (1,0) \\
0 = (0,0) \\
-1 = (0,1)
\)
#+END_CENTER


** Addition

Soit $i,j,k,l \in \setN$. Pour conserver l'associativité et la commutativité, on doit avoir :

$$(i - j) + (k - l) = (i + j) - k - l = (i + j) - (k + l)$$

Ceci nous incite à définir l'addition des entiers par :

$$(i,j) + (k,l) = (i + j, k + l)$$


*** Neutre additif

Soit $i,j \in \setN$. On a :

$$(i - j) + (0 - 0) = (i + 0) - (j + 0) = i - j$$

Pour tout $n \in \setN$, la soustraction native des naturels nous dit que :

$$n - n = 0$$

Afin de rester consistant, on impose que :

$$i - j = (i - j) + 0 = (i - j) + (n - n) = (i + n) - (j + n)$$

ou, en terme de couples :

$$(i,j) = (i + n, j + n)$$

Le neutre pour l'addition s'écrit donc :

$$0 = 0 - 0 = n - n = (0,0) = (n,n)$$


*** Équivalence

On voit apparaître les familles :

$$D(i,j) = \{ (i + n, j + n) : n \in \setN \}$$

où chaque élément de $D(i,j)$ est équivalent à un autre.
Nous noterons donc également :

$$i - j = D(i,j)$$


** Définition

On définit l'ensemble des nombres entiers par :

$$\setZ = \{ i - j : i,j \in \setN \}$$

où $i - j$ représente l'ensemble d'équivalence $D(i,j)$.
En introduisant les symboles usuels, on a donc :

$$\setZ = \{ ...,-5,-4,-3,-2,-1,0,1,2,3,4,5,... \}$$


*** Forme canonique

Soit $i,j \in \setN$.


  - Si $i \ge j$, le naturel $i - j$ existe et nous pouvons toujours
ramener $(i,j)$ par équivalence à :

$$(i - j, 0) = (i - j, 0) + (j,j) = (i - j + j, j) = (i,j)$$

On dit alors que $(i,j) = i - j$ est un entier positif.

  - Si $i \le j$, le naturel $j - i$ existe et nous pouvons toujours
ramener $(i,j)$ par équivalence à :

$$(0, j - i) = (0, j - i) + (i,i) = (i, j - i + i) = (i,j)$$

On dit alors que $(i,j) = i - j$ est un entier négatif.



*** Signe

On définit l'ensemble des entiers positifs par :

$$\setZ^+ = \{ i = D(i,0) : i \in \setN \}$$

ainsi que l'ensemble des entiers négatifs :

$$\setZ^- = \{ -i = D(0,i) : i \in \setN \}$$

L'ensemble des entiers est bien entendu l'union des deux : $\setZ = \setZ^+ \cup \setZ^-$.


*** Inclusion

Nous pouvons associer à tout naturel $i$ un entier équivalent $i - 0 = (i,0)$. Pour cette raison, nous dirons que tout naturel est également un entier, et nous noterons : $\setN \subseteq \setZ$.


*** Entiers positifs et naturels

Il existe une bijection $f : \setN \mapsto \setZ^+$ définie par :

$$f(n) = (n,0) = n - 0 = n$$

pour tout $n \in \setN$. On assimile donc les deux ensembles en écrivant
$\setN = \setZ^+$.


** Opposé

Soit $i,j \in \setN$. On déduit de la définition de l'addition que :

$$(i - j) + (j - i) = (i + j) - (j + i) = (i + j) - (i + j) = 0 - 0 = 0$$

ou, en terme de couples :

$$(i,j) + (j,i) = (i + j, i + j) = (0,0) = 0$$

On dit que $j - i = (j,i)$ est l'opposé de $i - j = (i,j)$,
et inversément. On le note :

$$- (i - j) = j - i$$

ou :

$$- (i,j) = (j,i)$$


*** De l'opposé

On a clairement :

$$- ( - (i - j)) = - (j - i) = i - j$$

ou :

$$- ( - (i,j)) = - (j,i) = (i,j)$$

L'opposé de l'opposé est l'entier lui-même.


*** D'une somme

Soit $u,v \in \setZ$ et $i,j,k,l \in \setN$ tels que :

$$u = i - j$$
$$v = k - l$$

On a :

$$(u + v) + ((-u) + (-v)) = ((i - j) + (k - l)) + ((j - i) + (l - k))$$

ce qui nous donne :

$$(u + v) + ((-u) + (-v)) = (i + k + j + l) - (j + l + i + k) = 0$$

On en conclut que la somme des opposés est égale à l'opposé de la somme :

$$(-u) + (-v) = - ( u + v)$$


*** Notation

On note aussi :

$$- u + v = (-u) + v$$

pour tout $u,v \in \setZ$.


*** Moins un

Un cas particulier important :

$$-(1 - 0) = 0 - 1 = -1$$

et :

$$-(-1) = 1$$


** Soustraction d'entiers

Soit $i,j,k,l \in \setN$. Comme :

\begin{align}
i + (-j) = (i,0) + (0,j) = (i,j) = i - j
\end{align}

On étend la soustraction à l'ensemble des entiers par :

\begin{align}
(i,j) - (k,l) = (i,j) + (-(k,l)) = (i,j) + (l,k)
\end{align}

ce qu'on peut réécrire par :

$$u - v = u + (-v)$$

pour tout $u,v \in \setZ$.


*** Propriétés

On a clairement :

$$(-i) - j = (-i) + (-j) = - ( i + j )$$

$$(-i) - (-j) = (-i) + j = j + (-i) = j - i$$


*** Notation

On note aussi :

$$- u - v = (-u) - v$$

pour tout $u,v \in \setZ$.


** Ordre

Soit $u,v \in \setZ$ et $i,j,k,l \in \setN$ tels que :

$$u = i - j$$
$$v = k - l$$

Si nous voulons conserver la propriété de conservation
de l'ordre sous l'addition, l'inégalité :

$$u = i - j \le k - l = v$$

doit être équivalente à :

$$(i - j) + j + l \le (k - l) + j + l$$

qui nous donne :

$$i + l \le k + j$$

Nous définissons l'ordre sur les entiers en affirmant que :

$$i - j \le k - l$$

si et seulement si :

$$i + l \le j + k$$


*** Plus grand ou égal

Soit $x,y \in \setZ$. On note aussi :

$$y \ge x$$

pour signifier que $x \le y$.


*** Ordre strict

Soit $x,y \in \setZ$. On note :

$$x \strictinferieur y$$

$$y \strictsuperieur x$$

lorsque $x \le y$ et $x \ne y$.


*** Conservation

Soit $u,v,w,z \in \setZ$ et $i,j,k,l,m,n,r,s \in \setN$ tels que :

$$u = i - j$$
$$v = k - l$$
$$w = m - n$$
$$z = r - s$$

On a :

$$u + w = (i + m) - (j + n)$$
$$v + z = (k + r) - (l + s)$$

Supposons que :

$$u \le v$$
$$w \le z$$

On a :

$$i - j \le k - l$$
$$m - n \le r - s$$

ou :

$$i + l \le j + k$$
$$m + s \le n + r$$

L'ordre des naturels étant conservé sous l'addition, on a :

$$i + l + m + s \le j + k + n + r$$

et :

$$(i + m) - (j + n) \le (k + r) - (l + s)$$

c'est-à-dire :

$$u + w \le v + z$$

L'ordre des entiers est conservé par l'addition.


*** Opposé

Soit $u,v \in \setZ$ tels que :

$$u \le v$$

Comme :

$$-(u + v) = -(u + v)$$

on a :

$$-(u + v) \le -(u + v)$$

et :

$$u + (-(u + v)) \le v + (-(u + v))$$

En développant, on a :

$$-v = u - u - v \le v - u - v = -u$$

c'est-à-dire :

$$-u \ge -v$$

L'ordre sur les opposés est l'inverse de l'ordre original.


**** Signe

Soit $z \in \setZ$. Si $z \ge 0$, on a :

$$-z \le 0$$

Inversément, si $z \le 0$, on a :

$$-z \ge 0$$


*** Positifs et négatifs

Soit $u \in \setZ^+$ et $i \in \setN$ tel que :

$$u = i - 0$$

On a :

$$i + 0 \ge 0 + 0$$

et :

$$i - 0 \ge 0 - 0 = 0$$

On en déduit que $u \ge 0$. Réciproquement, soit $u \in \setZ$ et
$i,j \in \setN$ tels que :

$$u = i - j$$

Si $u \ge 0$, on a :

$$i - j \ge 0$$

et :

$$i \ge j$$

On peut donc mettre $u$ sous la forme canonique :

$$u = (i - j,0) \in \setZ^+$$

On a donc :

$$\setZ^+ = \{ u \in \setZ : u \ge 0 \}$$

On montre aussi que :

$$\setZ^- = \{ u \in \setZ : u \le 0 \}$$

Par analogie avec les naturels, on dit que les entiers positifs
sont les successeurs de $0$ et les entiers négatifs les
prédécesseurs de $0$.


** Signe

La fonction signe est définie par :

$$\signe(z) =
\begin{cases}
1 & \text{si } \ z \ge 0 \\
-1 & \text{si } \ z \strictinferieur 0
\end{cases}$$

pour tout $z \in \setZ$.


** Valeur absolue

Soit $z \in \setZ$. On définit la valeur absolue de $z$ par :

$$\left| z \right | = \max \{ z , -z \}$$

On a donc :

$$\left| z \right| =
\begin{cases}
z & \text{si } \ z \ge 0 \\
-z & \text{si } \ z \strictinferieur 0
\end{cases}$$

Comme le nombre positif l'emporte toujours sur le négatif dans le maximum, on a :

$$\left| z \right| \ge 0$$

On vérifie que :

$$\left| x + y \right| \le \left| x \right| + \left| y \right|$$

pour tout $x,y \in \setZ$.


** Multiplication

Soit $u \in \setZ$. Le naturel $0$ est absorbant pour la multiplication.
On souhaite conserver cette propriété pour l'entier $0 = 0 - 0$ :

$$u \cdot 0 = 0 \cdot u = 0$$

$$u \cdot 1 = 1 \cdot u = u$$

Soit $u,v \in \setZ$. Si nous voulons conserver la distributivité, il
faut que :

$$u \cdot v + (-u) \cdot v = (u + (-u)) \cdot v = 0 \cdot v = 0$$

On en conclut que :

$$(-u) \cdot v = - (u \cdot v)$$

On a aussi :

$$u \cdot v + u \cdot (-v) = u \cdot (v + (-v)) = u \cdot 0 = 0$$

et :

$$u \cdot (-v) = -(u \cdot v)$$

Enfin :

$$(-u) \cdot (-v) = - (u \cdot (-v)) = - ( - (u \cdot v)) = u \cdot v$$


*** Définition

Soit $u,v \in \setZ$ et $i,j,k,l \in \setN$ tels que :

$$u = i - j$$
$$v = k - l$$

On a :

$$u \cdot v = (i - j) \cdot (k - l) = (i + (-j)) \cdot (k + (-l))$$

La distributivité nous donne :

$$u \cdot v = i \cdot (k + (-l)) + (-j) \cdot (k + (-l))$$

En l'utilisant une nouvelle fois, on arrive à :

$$u \cdot v = i \cdot k + i \cdot (-l) + (-j) \cdot k + (-j) \cdot (-l)$$

ou :

$$u \cdot v = i \cdot k - i \cdot l - j \cdot k + j \cdot l = (i \cdot k + j \cdot l) - (i \cdot l + j \cdot k)$$

On définit donc la multiplication d'entiers par :

$$(i,j) \cdot (k,l) = (i \cdot k + j \cdot l, i \cdot l + j \cdot k)$$


*** Entiers positifs

Soit $u,v \in \setZ$ tels que $u,v \ge 0$. On peut trouver des naturels
$i,j$ tels que :

$$u = i - 0$$
$$v = j - 0$$

On a :

$$u \cdot v = (i - 0) \cdot (j - 0) = (i \cdot j + 0 \cdot 0) - (i \cdot 0 + 0 \cdot j) = i \cdot j - 0 = i \cdot j$$

La multiplication d'entiers positifs correspond à celle des naturels.


*** Lien avec l'addition

Soit $u,v \in \setZ$ avec $v \ge 0$ et $i,j,k \in \setN$ tels que :

$$u = i - j$$
$$v = k - 0$$

On a :

$$u \cdot v = (i - j) \cdot (k - 0) = (i \cdot k + j \cdot 0) - (j \cdot k + i \cdot 0) = i \cdot k - j \cdot k$$


En additionnant $k$ fois le même terme $u$, on obtient :

$$u + ... + u = i \cdot k - j \cdot k = u \cdot v$$


*** Commutativité

La commutativité de la multiplication sur les entiers découle de celle sur les naturels :

\begin{align}
(k - l) \cdot (i - j) &= (k \cdot i + l \cdot j) - (k \cdot j + l \cdot i) \\
&= (i \cdot k + j \cdot l) - (i \cdot l + j \cdot k) \\
&= (i - j) \cdot (k - l)
\end{align}


*** Associativité

Soit $u,v,w \in \setZ$. Si $u, v, w \ge 0$, on peut les associer aux naturels
$i,j,k \in \setN$ par :

$$u = i - 0$$
$$v = j - 0$$
$$w = k - 0$$

On a alors :

$$u \cdot v = i \cdot j$$

et :

$$v \cdot w = j \cdot k$$

On a donc :

$$(u \cdot v) \cdot w = (i \cdot j) \cdot (k - 0) = i \cdot j \cdot k - 0 = i \cdot j \cdot k$$

et :

$$u \cdot (v \cdot w) = (i - 0) \cdot (j \cdot k) = i \cdot j \cdot k - 0 = i \cdot j \cdot k$$

On en conclut que :

$$(u \cdot v) \cdot w = u \cdot (v \cdot w)$$

Si un ou plusieurs entiers sont négatifs, soit $-u,-v,-w$, on a :

$$((-u) \cdot v) \cdot w = (- (u \cdot v)) \cdot w = - ((u \cdot v) \cdot w)$$

et :

$$((-u) \cdot v) \cdot w = - (u  \cdot (v \cdot w)) = (-u) \cdot (v \cdot w)$$

ou :

$$(u \cdot v) \cdot (-w) = - ((u \cdot v) \cdot w)$$

et :

$$(u \cdot v) \cdot w = - (u  \cdot (v \cdot w)) = u \cdot (-(v \cdot w)) = u \cdot (v \cdot (-w))$$

Les autres cas sont semblables, on a donc :

$$u \cdot v \cdot w = (u \cdot v) \cdot w = u \cdot (v \cdot w)$$

pour tout $u,v,w \in \setZ$.


*** Neutre

On a :

$$(i - j) \cdot 1 = (i - j) \cdot (1 - 0) = (i \cdot 1 + j \cdot 0) - (i \cdot 0 + j \cdot 1) = i - j$$

et :

$$1 \cdot (i - j) = (i - j) \cdot 1 = i - j$$

L'entier $1 = 1 - 0$ est le neutre pour la multiplication.


*** Notation

On note aussi :

$$- u \cdot v = - (u \cdot v)$$

pour tout $u,v \in \setZ$.


*** Moins un

On a :

$$(-1) \cdot (i,j) = - (1 \cdot (i,j)) = - (i,j)$$

Un cas particulier important :

$$(-1) \cdot (-1) = -(-1) = 1$$


** Ordre et multiplication


*** Conservation simple

Soit $x,y,z \in \setZ$ avec $z \ge 0$. Supposons que :

$$x \le y$$

On a alors :

$$x \cdot z = x + ... + x \le y + ... + y = y \cdot z$$

L'ordre est conservé lorsqu'on multiplie les deux membres de l'inégalité par un entier positif. Par contre :

$$x \cdot (-z) = - x \cdot z \ge - y \cdot z = y \cdot (-z)$$

L'ordre est inversé lorsqu'on multiplie les deux membres de l'inégalité par un entier négatif.


*** Conservation double

Soit $x,y,u,v \in \setZ$ vérifiant :

$$x \le y$$
$$u \le v$$

Si :

$$x,y,u,v \ge 0$$

on a :

$$x \cdot u \le x \cdot v \le y \cdot v$$


** Notation décimale

Soit le tuple :

$$(i_0,i_1,i_2,...i_{n - 1},i_n) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^{n + 1}$$

La notation décimale associée est définie par :

$$i_n i_{n - 1} ... i_2 i_1 i_0 = i_0 + i_1 \cdot 10 + i_2 \cdot 10^2 + ... + i_{n - 1} \cdot 10^{n - 1} + i_n \cdot 10^n$$

pour les entiers positifs et :

$$-i_n i_{n - 1} ... i_2 i_1 i_0 = -\left( i_0 + i_1 \cdot 10 + i_2
\cdot 10^2 + ... + i_{n - 1} \cdot 10^{n - 1} + i_n \cdot 10^n
\right)$$

pour les entiers négatifs. Exemple :

$$-7512 = -\left( 2 + 1 \cdot 10 + 5 \cdot 10^2 + 7 \cdot 10^3 \right)$$


** Division entière et modulo

Soit $m,n \in \setN$, avec $n \ne 0$. Soit :

\begin{align}
k &= m \diventiere n \\
r &= m \modulo n
\end{align}

On veut étendre la division entière à $\setZ$ en conservant la décomposition :

$$m = k \cdot n + r$$

On note que :

$$m = (-k) \cdot (-n) + r$$

On en déduit l'extension :

$$m \diventiere (-n) = -k = - (m \diventiere n)$$

et :

$$m \modulo (-n) = r = m \modulo n$$

On note que :

$$-m = k \cdot (-n) - r$$

On en déduit l'extension :

$$(-m) \diventiere (-n) = k = m \diventiere n$$

et :

$$(-m) \modulo (-n) = -r = - (m \modulo n)$$

On note que :

$$-m = (-k) \cdot n - r$$

On en déduit l'extension :

$$(-m) \diventiere n = -k = -(m \diventiere n)$$

et :

$$(-m) \modulo n = -r = - (m \modulo n)$$


** Puissance

Soit $z \in \setZ$ et $n \in \setN$. On définit les puissances par :

\begin{align}
z^0 &= 1 \\
z^n &= z \cdot z^{n - 1}
\end{align}

On a donc :

$$z^n = z \cdot ... \cdot z$$

$z^n$ est égal au produit de $n$ facteurs $z$.


** Anneau

$(\setZ,+,\cdot)$ est un anneau.


** Propriétés

La majeure partie des résultats démontrés sur $\setN$ reste valable sur $\setZ$. On le vérifie aisément en utilisant les définitions étendues. Exceptions :

  - La positivité des naturels (voir section \ref{sec:positivite_des_naturels}), qui est remplacée par la positivité de la valeur absolue


* Rationnels

#+TOC: headlines 1 local

\label{chap:rationnels}


** Dépendances

  - Chapitre \ref{chap:naturels} : Les nombres naturels
  - Chapitre \ref{chap:entiers} : Les nombres entiers


** Fractions

Soit $a,b \in \setZ$. On aimerait bien généraliser la division entière de sorte qu'elle soit tout le temps exacte. Comme ce ne sera en général pas le cas, on contourne le problème en introduisant la notation fractionnaire :

$$\frac{a}{b} = (a,b)$$

où $(a,b) \in \setZ^2$ est appelé nombre rationnel. Le nombre $a$ est appelé le numérateur
et $b$ le dénominateur. La division entière :

$$a \diventiere b$$

n'étant pas définie lorsque $b = 0$, nous imposerons comme seule restriction que $b$ soit non nul.


*** Notations

On note aussi les fractions par :

$$a/b = \frac{a}{b}$$

Lorsque $b = 1$, on note plus simplement :

$$a = \frac{a}{1} = (a,1)$$

et donc en particulier :

\begin{align}
1 &= 1 / 1 \\
0 &= 0 / 1 \\
-1 &= -1 / 1
\end{align}


*** Attention

Ne pas confondre les couples $(.,.)$ fractionnaires de ce chapitre avec les couples différentiels du chapitre \ref{chap:entiers} traitant des entiers.


** Produit

La notation fractionnaire étant destinée à représenter une division exacte,
nous devons conserver les propriétés de la division entière dans le cas où
elle est également exacte. Comme on a :

$$(m \diventiere n) \cdot (i \diventiere j) = (m \cdot i) \diventiere (n \cdot j)$$

pour tout $m,n,i,j \in \setZ$ tels que :

$$m \modulo n = i \modulo j = 0$$

on définit le produit entre rationnels par :

$$\frac{a}{b} \cdot \frac{c}{d} = \frac{a \cdot c}{b \cdot d}$$

ou :

$$(a,b) \cdot (c,d) = (a \cdot c, b \cdot d)$$

pour tout $a,b,c,d \in \setZ$ vérifiant $b,d \ne 0$.


*** Commutativité

Soit $a,b,c,d \in \setZ$ vérifiant $b,d \ne 0$. On a :

$$\frac{a}{b} \cdot \frac{c}{d} = \frac{a \cdot c}{b \cdot d} = \frac{c \cdot a}{d \cdot b} = \frac{c}{d} \cdot \frac{a}{b}$$

La multiplication entre rationnels est commutative.


*** Associativité

Soit $a,b,c,d,e,f \in \setZ$ vérifiant $b,d,f \ne 0$. On a :

$$\frac{a}{b} \cdot \crochets{\frac{c}{d} \cdot \frac{e}{f}} = \frac{a}{b} \cdot \frac{c \cdot e}{d \cdot f} = \frac{a \cdot c \cdot e}{b \cdot d \cdot f}$$

$$\crochets{\frac{a}{b} \cdot \frac{c}{d}} \cdot \frac{e}{f} = \frac{a \cdot c}{b \cdot d} \cdot \frac{e}{f} = \frac{a \cdot c \cdot e}{b \cdot d \cdot f}$$

On en conclut que :

$$\frac{a}{b} \cdot \crochets{\frac{c}{d} \cdot \frac{e}{f}} = \crochets{\frac{a}{b} \cdot \frac{c}{d}} \cdot \frac{e}{f}$$

La multiplication entre rationnels est associative :

$$\frac{a}{b} \cdot \frac{c}{d} \cdot \frac{e}{f} = \frac{a}{b} \cdot \crochets{\frac{c}{d} \cdot \frac{e}{f}} = \crochets{\frac{a}{b} \cdot \frac{c}{d}} \cdot \frac{e}{f}$$


*** Neutre multiplicatif

Soit $n \in \setZ$ avec $n \ne 0$. On a :

$$\frac{a}{b} \cdot 1 = \frac{a}{b} \cdot \frac{1}{1} = \frac{a \cdot 1}{b \cdot 1} = \frac{a}{b}$$

Le rationnel $1 = 1 / 1$ est le neutre pour la multiplication. Comme :

$$n \diventiere n = 1$$

on impose que :

$$\frac{n}{n} = \frac{1}{1} = 1$$

Cette contrainte nous donne :

$$\frac{a \cdot n}{b \cdot n} = \frac{a}{b} \cdot \frac{n}{n} = \frac{a}{b} \cdot 1 = \frac{a}{b}$$

pour tout $a,b \in \setZ$ avec $b \ne 0$.


*** Équivalence

On voit apparaître les familles :

$$F(a,b) = \left\{ \frac{a \cdot n}{b \cdot n} : n \in \setZ, \ n \ne 0 \right\}$$

où chaque élément de $F(a,b)$ est équivalent à un autre.
Nous noterons donc également :

$$\frac{a}{b} = F(a,b)$$


** Définition

On définit l'ensemble des nombres rationnels par :

$$\setQ = \left\{ \frac{a}{b} : a,b \in \setZ, \ b \ne 0 \right\}$$


*** Naturels

Se rappelant que tout $a \in \setZ$ peut s'exprimer comme la soustraction
de deux naturels $i,j$ :

$$a = i - j$$

on arrive à la formulation équivalente :

$$\setQ = \left\{ \frac{i - j}{k - l} : i,j,k,l \in \setN, \ k \ne l \right\}$$


*** Inclusion

Nous pouvons associer à tout entier $a$ un rationnel équivalent $(a,1) = a/1$. Pour cette raison, nous dirons que tout entier est également un rationnel, et nous noterons : $\setZ \subseteq \setQ$.


** Inverse

Soit $a,b \in \setZ$ avec $a,b \ne 0$. On a :

$$\frac{a}{b} \cdot \frac{b}{a} = \frac{a \cdot b}{b \cdot a} = 1$$

On dit que $b / a$ est l'inverse de $a / b$ et réciproquement. On le note :

$$\left( \frac{a}{b} \right)^{-1} = \frac{b}{a}$$


*** De l'inverse

On a clairement :

$$\crochets{\left( \frac{a}{b} \right)^{-1}}^{-1} = \crochets{\frac{b}{a}}^{-1} = \frac{a}{b}$$

L'inverse de l'inverse d'une fraction est égal à elle-même.


*** D'un produit

Soit $a,b,c,d \in \setZ \setminus \{ 0 \}$. On a :

$$\frac{a}{b} \cdot \frac{c}{d} \cdot \frac{d}{c} \cdot \frac{b}{a} = \frac{a}{b} \cdot \frac{c \cdot d}{d \cdot c} \cdot \frac{b}{a} = \frac{a}{b} \cdot 1 \cdot \frac{b}{a} = \frac{a}{b} \cdot \frac{b}{a} = \frac{a \cdot b}{b \cdot a} = 1$$

On en conclut que :

$$\frac{d}{c} \cdot \frac{b}{a} = \left( \frac{a}{b} \cdot \frac{c}{d}
\right)^{-1}$$


** Addition


*** Dénominateur commun

Soit $a,b,n \in \setZ$ avec $n \ne 0$. On voit que :

$$\frac{a}{n} + \frac{b}{n} = \frac{a}{1} \cdot \frac{1}{n} +
\frac{b}{1} \cdot \frac{1}{n} = a \cdot \frc{1}{n} + b \cdot
\frac{1}{n}$$

Si on veut conserver la distributivité de la multiplication sur l'addition, on doit donc avoir :

$$\frac{a}{n} + \frac{b}{n} = (a + b) \cdot \frac{1}{n} = \frac{a + b}{n}$$

Pour additionner deux fractions possédant un même dénominateur, il suffit d'additionner les numérateurs.


*** Générique

Soit $a,b,c,d \in \setZ$ avec $b,d \ne 0$. Tentons à présent d'obtenir une expression de la somme $(a,b) + (c,d)$. Multipliant la première par $d / d = 1$ et la seconde par $b / b = 1$, il vient :

$$\frac{a}{b} + \frac{c}{d} = \frac{a \cdot d}{b \cdot d} + \frac{c \cdot b}{d \cdot b}$$

Comme les deux fractions du membre de droite ont un même dénominateur, on a finalement :

$$\frac{a}{b} + \frac{c}{d} = \frac{a \cdot d + c \cdot b}{b \cdot d}$$


*** Neutre additif

Soit $a,b \in \setZ$ avec $b \ne 0$. On a :

$$\frac{a}{b} + 0 = \frac{a}{b} + \frac{0}{1} = \frac{a \cdot 1 + 0 \cdot b}{b \cdot 1} = \frac{a}{b}$$

Le rationnel :

$$0 = \frac{0}{1}$$

est le neutre pour l'addition. On a aussi :

$$\frac{0}{n} = \frac{0 \cdot n}{1 \cdot n} = \frac{0}{1} = 0$$


** Opposé

Soit $m, n \in \setZ$. On sait que :

$$(-m) \diventiere n = -(m \diventiere n)$$
$$m \diventiere (-n) = - (m \diventiere n)$$
$$(-m) \diventiere (-n) = m \diventiere n$$

A-t-on les même propriétés pour les rationnels ? Soit $a,b \in \setZ$
avec $b \ne 0$. On a :

$$\frac{a}{b} + \frac{-a}{b} = \frac{a - a}{b} = \frac{0}{b} = 0$$

L'opposé de $a/b$ est donc $-a/b$ :

$$-\frac{a}{b} = \frac{-a}{b}$$

On a également :

$$\frac{a}{-b} = \frac{(-1) \cdot a}{(-1) \cdot (-b)} = \frac{-a}{b} = -\frac{a}{b}$$

et :

$$\frac{-a}{-b} = \frac{(-1) \cdot (-a)}{(-1) \cdot (-b)} = \frac{a}{b}$$


** Représentation canonique

Soit un rationnel $x \in \setQ$ et des entiers $a,b \in \setZ$ vérifiant
$b \ne 0$ et :

$$x = \frac{a}{b}$$

Si $b \strictsuperieur 0$, on pose :

$$m = a$$
$$n = b$$

et on a :

$$x = \frac{m}{n}$$

avec $n \strictsuperieur 0$. Si $b \strictinferieur 0$, on pose :

$$m = -a$$
$$n = -b$$

et on a :

$$x = \frac{a}{b} = \frac{-a}{-b} = \frac{m}{n}$$

avec $n \strictsuperieur 0$. On peut donc toujours se ramener à la représentation
canonique :

$$x = \frac{m}{n}$$

où $m,n \in \setZ$ et $n \strictsuperieur 0$.


** Soustraction

Soit $a,b,c,d \in \setZ$ avec $b,d \ne 0$. On définit :

$$\frac{a}{b} - \frac{c}{d} = \frac{a}{b} + \frac{-c}{d} = \frac{a \cdot d - c \cdot b}{b \cdot d}$$


** Ordre

Soit $a,b,c,d \in \setZ$ avec $b,d \ne 0$. Nous allons étendre l'ordre sur l'ensemble
des rationnels en imposant que la multiplication par un nombre strictement
positif conserve l'ordre et que la multiplication par un nombre strictement
négatif l'inverse. Soit l'inégalité :

$$\frac{a}{b} \le \frac{c}{d}$$


  - Supposons que $b,d \ge 0$. En multipliant par $b \cdot d \strictsuperieur 0$,
on voit que l'inégalité est équivalente à :

$$a \cdot d \le c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \le c \cdot b$$

  - Supposons que $b \le 0$ et $d \ge 0$. On a $b \cdot d \strictinferieur 0$
et l'inégalité est équivalente à :

$$a \cdot d \ge c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \ge c \cdot b$$

  - Supposons que $b \ge 0$ et $d \le 0$. On a $b \cdot d \strictinferieur 0$
et l'inégalité est équivalente à :

$$a \cdot d \ge c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \ge c \cdot b$$

  - Supposons que $b,d \le 0$, on a
$b \cdot d = (-b) \cdot (-d) \strictsuperieur 0$ et l'inégalité
est équivalente à :

$$a \cdot d \le c \cdot b$$

Nous dirons donc que :

$$\frac{a}{b} \le \frac{c}{d}$$

si et seulement si :

$$a \cdot d \le c \cdot b$$



*** Positifs et négatifs

On définit les ensembles des rationnels positifs et négatifs par :

$$\setQ^+ = \{ x \in \setQ : x \ge 0 \}$$

$$\setQ^- = \{ x \in \setQ : x \le 0 \}$$

Soit un rationnel $x$ sous la forme canonique :

$$x = \frac{a}{b}$$

Si $x$ est négatif :

$$x = \frac{a}{b} \le 0 = \frac{0}{1}$$

on a par définition :

$$a \cdot 1 \le 0 \cdot b = 0$$

autrement dit :

$$a \le 0$$

Invérsément, si $x$ est positif :

$$x = \frac{a}{b} \ge 0 = \frac{0}{1}$$

on a par définition :

$$a \cdot 1 \ge 0 \cdot b = 0$$

autrement dit :

$$a \ge 0$$


*** Invariance sous multiplication

Soit les rationnels $x,y,z$ sous forme canonique :

$$x = \frac{a}{b}$$

$$y = \frac{c}{d}$$

$$z = \frac{e}{f}$$

avec $a,b,c,d,e,f \in \setZ$ et $b,d,f \strictsuperieur 0$. On suppose que
$z \ge 0$, c'est-à-dire :

$$e \ge 0$$

et que :

$$x \le y$$

c'est-à-dire :

$$a \cdot d \le c \cdot b$$

L'ordre entre entiers est conservé par la multiplication
de l'entier positif $e \cdot f$ :

$$a \cdot e \cdot d \cdot f \le  c \cdot e \cdot b \cdot f$$

Par définition de l'ordre entre rationnels, on en déduit que :

$$\frac{a \cdot e}{b \cdot f} \le \frac{c \cdot e}{d \cdot f}$$

c'est-à-dire :

$$x \cdot z \le y \cdot z$$

L'ordre entre rationnels est conservé sous la multiplication d'un
rationnel positif.


*** Invariance sous addition

Soit les rationnels $x,z,u,v$ sous forme canonique :

$$x = \frac{a}{b}$$

$$y = \frac{c}{d}$$

$$u = \frac{e}{f}$$

$$v = \frac{g}{h}$$

On suppose que :

$$x \le y$$
$$u \le v$$

c'est-à-dire :

$$\frac{a}{b} \le \frac{c}{d}$$

$$\frac{e}{f} \le \frac{g}{h}$$

ou :

$$a \cdot d \le c \cdot b$$

$$e \cdot h \le g \cdot f$$

L'ordre entre entiers étant conservé sous la multiplication
de $f \cdot h \strictsuperieur 0$, on a :

$$a \cdot d \cdot f \cdot h \le c \cdot b \cdot f \cdot h$$

L'ordre entre entiers étant conservé sous la multiplication
de $b \cdot d \strictsuperieur 0$, on a :

$$e \cdot h \cdot b \cdot d \le g \cdot f \cdot b \cdot d$$

L'ordre entre entiers étant conservé sous l'addition, on a :

$$a \cdot d \cdot f \cdot h + e \cdot h \cdot b \cdot d \le c \cdot b \cdot f \cdot h + g \cdot f \cdot b \cdot d$$

En utilisant la distributivité, on en déduit que :

$$(a \cdot f + e \cdot b) \cdot d \cdot h \le (c \cdot h + g \cdot d) \cdot b \cdot f$$

ou, par définition de l'ordre entre rationnels :

$$\frac{a \cdot f + e \cdot b}{b \cdot f} \le \frac{c \cdot h + g \cdot d}{d \cdot h}$$

qui n'est rien d'autre que :

$$\frac{a}{b} + \frac{e}{f} \le \frac{c}{d} + \frac{g}{h}$$

c'est-à-dire :

$$x + u \le y + v$$

L'ordre entre rationnels est conservé sous l'addition.


*** Invariance sous soustraction

Soit les rationnels $x,z,u,v$ tels que :

$$x \le y$$
$$u \ge v$$

En ajoutant :

$$(-u)+(-v) \ge (-u)+(-v)$$

à la seconde inégalité, on obtient :

$$u + (-u) + (-v) \ge v + (-u) + (-v)$$

qui se simplifie en :

$$-v \ge -u$$

ou :

$$-u \le -v$$

On a donc :

$$x + (-u) \le y + (-v)$$

c'est-à-dire :

$$x - u \le y - v$$


** Signe

La fonction signe est définie par :

$$\signe(x) =
\begin{cases}
1 & \text{ si } x \ge 0 \\
-1 & \text{ si } x \strictinferieur 0
\end{cases}$$

pour tout $x \in \setQ$


** Valeur absolue

Soit $x \in \setQ$. On définit la valeur absolue de $x$ par :

$$\left| x \right| = \max \{ x , -x \}$$


** Notation décimale

Soit les tuples :

$$(i_0,...,i_m) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^{m + 1}$$

et :

$$(j_1,...,j_n) \in \{ 0,1,2,3,4,5,6,7,8,9 \}^n$$

La notation décimale associée est définie par :

$$i_m ... i_0, j_1 ... j_n = i_0 + ... + i_m \cdot 10^m + j_1 \cdot \frac{1}{10} + ... + j_n \cdot \frac{1}{10^n}$$

pour les rationnels positifs et :

$$i_m ... i_0, j_1 ... j_n = -\left(i_0 + ... + i_m \cdot 10^m + j_1
\cdot \frac{1}{10} + ... + j_n \cdot \frac{1}{10^n} \right)$$

pour les rationnels négatifs. Exemple :

$$-7512,34 = -\left( 2 + 1 \cdot 10 + 5 \cdot 10^2 + 7 \cdot 10^3 + 3
\cdot \frac{1}{10} + 4 \cdot \frac{1}{10^2} \right)$$


** Division

Soit $x,y \in \setQ$ et $a,b,c,d \in \setZ$ avec $b,c,d \ne 0$ et :

$$x = \frac{a}{b}$$

$$y = \frac{c}{d}$$

On dit que $q \in \setQ$ est la division de $x$ par $y$ et on le note :

$$\frac{x}{y} = q$$

si :

$$x = q \cdot y$$

Multipliant par $y^{-1}$, on a bien sur :

$$q = x \cdot y^{-1} = \frac{a}{b} \cdot \frac{d}{c}$$

La division de deux fractions s'écrit donc simplement :

$$\frac{x}{y} = \frac{a/b}{c/d} = \frac{a}{b} \cdot \frac{d}{c}$$


** Puissance

Soit $m,n \in \setN$ et $a,b \in \setZ$. Les puissances positives s'étendent facilement aux fractions :

$$\left( \frac{a}{b} \right)^n = \frac{a}{b} \cdot ... \cdot \frac{a}{b} = \frac{a^n}{b^n}$$

On définit de plus les puissances négatives par :

$$\left( \frac{a}{b} \right)^{-n} = \left( \frac{b}{a} \right)^n$$

Mais comme un produit d'inverses est égal à l'inverse des produits, on a également :

$$\left( \frac{a}{b} \right)^{-n} = \left( \frac{a^n}{b^n} \right)^{-1}$$


*** Somme en exposant

Soit $x \in \setQ$. On vérifie que :

$$x^{m + n} = x^m \cdot x^n$$

$$x^{m - n} = x^m \cdot x^{-n} = \frac{x^m}{x^n}$$

$$x^{-m + n} = x^{-m} \cdot x^n = \frac{x^n}{x^m}$$

$$x^{-m - n} = x^{-m} \cdot x^{-n} = \frac{1}{x^m \cdot x^n}$$

On a donc bien :

$$x^{i + j} = x^i \cdot x^j$$

pour tout $i,j \in \setZ$.


** Carré

Le carré est la deuxième puissance d'un nombre :

$$x^2 = x \cdot x$$


*** Positivité

Soit $x \in \setQ$. Si $x \ge 0$, on pose $p = x$. On a donc $p \ge 0$.
La multiplication par un rationnel positif ne modifiant pas l'ordre, on a :

$$p^2 = p \cdot p \ge 0 \cdot p = 0$$

Le carré est donc également positif :

$$x^2 = p^2 \ge 0$$

Si $x \le 0$, on pose $p = -x$. On a donc $p \ge 0$.
On voit que $x = -p$ et que :

$$x^2 = (-p)^2 = (-p) \cdot (-p) = p \cdot p = p^2 \ge 0$$

On a donc :

$$x^2 \ge 0$$

pour tout $x \in \setQ$.


*** Ordre

Soit $x,y \in \setQ$ vérifiant :

$$x,y \ge 0$$

et :

$$x \le y$$

Comme $x \ge 0$, l'inégalité $x \le y$ est conservée sous
la multiplication par $x$ :

$$x^2 = x \cdot x \le y \cdot x$$

Comme $y \ge 0$, l'inégalité $x \le y$ est conservée sous
la multiplication par $y$ :

$$x \cdot y \le y \cdot y = y^2$$

En rassemblant ces résultats, il vient :

$$x^2 \le y \cdot x = x \cdot y \le y^2$$

on a donc :

$$x^2 \le y^2$$

La fonction $f : x \mapsto x^2$ est croissante sur l'ensemble des
rationnels positifs.


*** Binôme

Soit $x,y \in \setZ$. En utilisant la distributivité, on obtient :

$$(x + y)^2 = (x + y) \cdot (x + y) = x \cdot (x + y) + y \cdot (x + y)$$

En l'utilisant une seconde fois, on arrive à :

$$(x + y)^2 = x \cdot x + x \cdot y + y \cdot x + y \cdot y$$

En utilisant la commutativité, on arrive au développement :

$$(x + y)^2 = x^2 + x \cdot y + x \cdot y + y^2$$

que l'on peut réexprimer comme :

$$(x + y)^2 = x^2 + 2 \cdot x \cdot y + y^2$$


**** Différence

On a :

$$(x - y)^2 = (x + (-y))^2 = x^2 + 2 \cdot x \cdot (-y) + y^2$$

et donc :

$$(x - y)^2 = x^2 - 2 \cdot x \cdot y + y^2


** Corps

$(\setQ,+,\cdot)$ est un corps commutatif.


** Densité

Soit le rationnel $\epsilon \in \setQ$ vérifiant $\epsilon \strictsuperieur 0$
exprimé sous la forme canonique :

$$\epsilon = \frac{m}{n}$$

avec $m,n \in \setZ$ et $n \strictsuperieur 0$. Comme $\epsilon$ est
strictement positif, on a :

$$m \strictsuperieur 0$$

Existe-t-il un rationnel intermédiaire $\delta$ vérifiant :

$$0 \strictinferieur \delta \strictinferieur \epsilon$$

Posons :

$$\delta = \frac{m}{2 \ n}$$

Il est clair que $\delta \strictsuperieur 0$. On a :

$$n \strictinferieur 2 \ n$$

En multipliant par $m \strictsuperieur 0$, on obtient :

$$m \cdot n \strictinferieur m \cdot 2 \cdot n$$

Par définition de l'ordre sur les rationnels, cette inégalité
est équivalente à :

$$\delta = \frac{m}{2 \ n} \strictinferieur \frac{m}{n} = \epsilon$$

On en conclut que :

$$0 \strictinferieur \delta \strictinferieur \epsilon$$


*** Rationnels distincts

Soit les rationnels $x,y$ vérifiant :

$$x \strictinferieur y$$

On pose :

$$\epsilon = y - x \strictsuperieur 0$$

On peut trouver un rationnel $\delta$ tel que :

$$0 \strictinferieur \delta \strictinferieur \epsilon$$

En additionnant cette inégalité avec :

$$x \le x \le x$$

on arrive à :

$$x \strictinferieur x + \delta \strictinferieur x + \epsilon$$

Soit :

$$z = x + \delta$$

Comme :

$$x + \epsilon = x + y - x = y$$

on a :

$$x \strictinferieur z \strictinferieur y$$

On peut toujours trouver un rationnel strictement compris
entre deux rationnels distincts.


* Booléens

#+TOC: headlines 1 local

\label{chap:booleens}


** Dépendances

  - Chapitre \ref{chap:operations} : Les opérations
  - Chapitre \ref{chap:algebre} : L'algèbre


** Définition

L'ensemble de Boole se définit par :

$$\setB = \{ 0 , 1 \}$$

On associe souvent à $0$ le sens de « faux » et à $1$ le sens de « vrai ».


** La loi « et »

Soit $C_1, C_2 \in \setB$. La condition « $C_1$ et $C_2$ » n'est vraie ($=1$) que si $C_1 = 1$ et $C_2 = 1$. On définit donc l'opération « ET », notée $\cdot : \setB \times \setB \mapsto \setB$, par :

#+BEGIN_CENTER
\(
1 \cdot 1 = 1 \\
1 \cdot 0 = 0 \\
0 \cdot 1 = 0 \\
0 \cdot 0 = 0
\)
#+END_CENTER


** La loi « ou »

Soit $C_1, C_2 \in \setB$. La condition « $C_1$ ou $C_2$ » est vraie ($=1$) dès qu'au moins un des deux $C_i = 1$. On définit donc l'opération « OU », notée $\oplus : \setB \times \setB \mapsto \setB$, par :

#+BEGIN_CENTER
\(
1 \oplus 1 = 1 \\
1 \oplus 0 = 1 \\
0 \oplus 1 = 1 \\
0 \oplus 0 = 0
\)
#+END_CENTER


** Le contraire

Le contraire de vrai est simplement faux et inversément. On définit donc le contraire de $C \in \setB$ noté $\neg C$, par :

#+BEGIN_CENTER
\(
\neg 1 = 0 \\
\neg 0 = 1
\)
#+END_CENTER


* Fonctions et opérations

\label{chap:fonctionsEtOperations}


** Dépendances

  - Chapitre \ref{chap:algebre} : L'algèbre
  - Chapitre \ref{chap:naturels} : Les naturels
  - Chapitre \ref{chap:entiers} : Les entiers
  - Chapitre \ref{chap:rationnels} : Les rationnels


** Opérations induites

Soit les fonctions $f,g \in B^A$ et $\divideontimes$ une opération sur $A$.
On définit alors la fonction $f \divideontimes g$ par :

$$(f \divideontimes g)(x) = f(x) \divideontimes g(x)$$

pour tout $x \in A$. Nous avons ainsi défini une opération sur $B^A$ :

$$\divideontimes : B^A \times B^A \mapsto B^A$$

induite par la loi équivalente sur $B$.


*** Usuelles

Sur les anneaux et les corps, ou sur tout ensemble où sont définies
les opérations usuelles $+,-,\cdot,/$, on aura ainsi :

  - les sommes : $(f + g)(x) = f(x) + g(x)$
  - les produits : $(f \cdot g)(x) = f(x) \cdot g(x)$
  - les soustractions : $(f - g)(x) = f(x) - g(x)$
  - les divisions : $(f / g)(x) = f(x) / g(x)$

pour tout $x \in A$.


** Opposé et inverse

Soit la fonction $f \in B^A$. Si l'inverse pour l'addition $-f(x)$ existe
pour tout $x \in A$, on définit la fonction opposée $-f$ par :

$$(-f)(x) = -f(x)$$

pour tout $x \in A$. On a alors :

$$f - f = 0$$

Si l'inverse pour la multiplication $1/f(x)$ existe pour tout $x \in A$,
on définit la fonction $1/f$ par :

$$(1/f)(x) = 1/f(x)$$

pour tout $x \in A$. On a alors :

$$f \cdot 1/f = 1$$


** Opérations mixte

Soit la fonction $f \in B^A$ et $c \in B$. Étant donnée une opération
$\divideontimes$ définie sur $B$, on définit les opérations mixtes
$f \divideontimes c$ et $c \divideontimes f$ par :

#+BEGIN_CENTER
\(
(f \divideontimes c)(x) = f(x) \divideontimes c \\
(c \divideontimes f)(x) = c \divideontimes f
\)
#+END_CENTER

pour tout $x \in A$. Dans le cas où l'opération $\divideontimes$ définie
sur $B$ est commutative, on a bien entendu $f \divideontimes c = c \divideontimes f$.

Sur les ensembles où sont définies les lois usuelles $+,-,\cdot,/$,
on aura ainsi :


  - les sommes :

#+BEGIN_CENTER
\(
(f + c)(x) = f(x) + c \\
(c + f)(x) = c + f(x)
\)
#+END_CENTER

  - les produits :

#+BEGIN_CENTER
\(
(f \cdot c)(x) = f(x) \cdot c \\
(c \cdot f)(x) = c \cdot f(x)
\)
#+END_CENTER

  - les soustractions :

#+BEGIN_CENTER
\(
(f - c)(x) = f(x) - c \\
(c - f)(x) = c - f(x)
\)
#+END_CENTER

  - les divisions :

#+BEGIN_CENTER
\(
(f / c)(x) = f(x) / c \\
(c / f)(x) = c / f(x)
\)
#+END_CENTER


pour tout $x \in A$.


** Commutateur

Notons qu'en général la composée n'est pas commutative. On peut en
effet trouver des fonctions $f,g : A \mapsto A$
telles que $f \circ g \ne g \circ f$.

Cette constatation nous amène à la notion de commutateur. Il s'agit
d'une fonction $[f,g] : A \mapsto A$ définie par :

$$[f,g] = f \circ g - g \circ f$$

Cet opérateur est clairement antisymétrique :

$$[f,g] = - [g,f]$$

Dans le cas particulier où $[f,g] = 0$, on dit que les fonctions
$f$ et $g$ commutent.


** Puissance fonctionnelle et puissance

Attention à ne pas confondre exposant de la fonction et exposant de
la valeur de la fonction en un point :

$$f(x)^n = f(x) \cdot f(x)^{n - 1} \ne f^n(x) = (f \circ f^{n - 1})(x)$$


** Noyau

Le noyau d'une fonction $f : A \mapsto B$ est l'ensemble des $x \in A$
où les valeurs de $f$ sont égales au neutre pour l'addition :

$$\noyau f = \{ x \in A : f(x) = 0 \}$$


** Support d'une fonction

Le support d'une fonction $f : A \mapsto \Omega$ est l'adhérence
de l'ensemble des points où $f$ prend une valeur non nulle :

$$\support f = \adh \{ x \in A : f(x) \ne 0 \}$$


*** Remarque

Attention à ne pas confondre le suprémum d'un ensemble,
noté « $\sup$ » avec un seul « p », avec le support,
noté « $\support$ », qui prend deux « p ».


* Fonctions indicatrices

\label{chap:fonctionsIndicatrices}


** Dépendances

  - Chapitre \ref{chap:algebre} : Les structures algébriques
  - Chapitre \ref{chap:ordres} : Les ordres
  - Chapitre \ref{chap:naturels} : Les naturels
  - Chapitre \ref{chap:entiers} : Les entiers
  - Chapitre \ref{chap:rationnels} : Les rationnels


** Définition

Soit un ensemble de référence $\Omega$ et $A \subseteq \Omega$. La fonction indicatrice

$$\indicatrice_A : \Omega \mapsto \{ 0 , 1 \}$$

associée à l'ensemble $A$ permet de déterminer si un élément quelconque de $\Omega$ appartient où non à $A$. Elle est définie par :

$$\indicatrice_A(x) =
\begin{cases}
1 & \text{si } \ x \in A \\
0 & \text{si } \ x \in \Omega \setminus A
\end{cases}$$


*** Crochets

On note aussi :

$$\indicatrice[A] = \indicatrice_A$$

et :

$$\indicatrice[A](x) = \indicatrice_A(x)$$


** Ensemble vide

Notons en particulier que :

$$\indicatrice[\emptyset] = 0$$


** Ordre

Soit $A,B \subseteq \Omega$ avec $A \subseteq B$. On voit que :


  - pour tout $x \in A$, on a aussi $x \in B$ et $\indicatrice_A(x) = \indicatrice_B(x) = 1$

  - pour tout $x \in \Omega \setminus A$, on a $\indicatrice_A(x) = 0 \le \indicatrice_B(x)$


On en conclut que :

$$\indicatrice_A(x) \le \indicatrice_B(x)$$

pour tout $x \in \Omega$, c'est-à-dire :

$$\indicatrice_A \le \indicatrice_B$$

L'ordre des fonctions indicatrices correspond à l'ordre inclusif des ensembles.


** Intersection

Soit $A, B \subseteq \Omega$. On voit que :

  - si $x \in A \cap B$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 1 \cdot 1 = 1 = \indicatrice[A \cap B](x)$
  - si $x \in A \cap (\Omega \setminus B)$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 1 \cdot 0 = 0 = \indicatrice[A \cap B](x)$
  - si $x \in (\Omega \setminus A) \cap B$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 0 \cdot 1 = 0 = \indicatrice[A \cap B](x)$
  - si $x \in \Omega \setminus (A \cup B)$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 0 \cdot 0 = 0 = \indicatrice[A \cap B](x)$

Donc :

$$\indicatrice[A \cap B] = \indicatrice_A \cdot \indicatrice_B$$


** Union d'ensembles disjoints

Si $A \cap B = \emptyset$, on a clairement :

$$\indicatrice[A \cup B] = \indicatrice_A + \indicatrice_B$$


** Différence

Soit les ensembles $A$ et $B$. On a la décomposition :

$$A = (A \setminus B) \cup (A \cap B)$$

On sait que les deux sous-ensembles sont disjoints :

$$(A \setminus B) \cap (A \cap B) = \emptyset$$

On a donc :

$$\indicatrice_A = \indicatrice[A \setminus B] + \indicatrice[A \cap B]$$

On en conclut que :

\begin{align}
\indicatrice[A \setminus B] &= \indicatrice_A - \indicatrice[A \cap B] \\
&= \indicatrice_A - \indicatrice_A \cdot \indicatrice_B
\end{align}


** Union d'ensembles quelconques

Soit les ensembles $A$ et $B$. On a la décomposition :

$$A \cup B = (A \setminus B) \cup B$$

On voit que les deux sous-ensembles sont disjoints :

$$(A \setminus B) \cap B = \emptyset$$

On en conclut que :

$$\indicatrice[A \cup B] = \indicatrice[A \setminus B] + \indicatrice_B$$

Reprenant l'expression de la différence, on a finalement :

\begin{align}
\indicatrice[A \cup B] &= \indicatrice_A + \indicatrice_B - \indicatrice[A \cap B] \\
&= \indicatrice_A + \indicatrice_B - \indicatrice_A \cdot \indicatrice_B
\end{align}


** Produit cartésien

Pour tout $(x,y) \in A \times B$, on a :

$$\indicatrice[A \times B](x,y) = \indicatrice_A(x) \cdot \indicatrice_B(y)$$


** Delta de Kronecker

Considérons l'ensemble $I \subset \Omega^2$ défini par :

$$I = \{ (i,j) \in \Omega^2 : i = j \}$$

Le delta de Kronecker est simplement :

$$\indicatrice_{ij} = \indicatrice_I(i,j)$$

On a donc :

#+BEGIN_CENTER
\(
\indicatrice_{ij} =
\begin{cases}
1 & \text{si } i = j \\
0 & \text{si } i \neq j
\end{cases}
\)
#+END_CENTER


*** Notation

On note aussi :

$$\indicatrice^{ij} = \indicatrice_i^j = \indicatrice_{ij}$$


* Parité

\label{chap:parite}


** Définition

On dit qu'une fonction $\sigma : \corps \mapsto \corps$ est paire si :

$$\sigma(-x) = \sigma(x)$$

pour tout réel $x$. Inversément, on dit qu'une fonction $\alpha : \corps \mapsto \corps est impaire si :

$$\alpha(-x) = - \alpha(x)$$

pour tout réel $x$.


** Décomposition

Soit une fonction $\varphi : \corps \mapsto \corps$. La fonction $\sigma$ définie par :

$$\sigma(x) = \frac{1}{2} \  \Big[\varphi(x) + \varphi(-x)\Big]$$

pour tout réel $x$ vérifie :

$$\sigma(-x) = \frac{1}{2} \ \Big[\varphi(-x) + \varphi(x)\Big] =
\frac{1}{2} \ \Big[\varphi(x) + \varphi(-x)\Big] = \sigma(x)$$

Cette fonction est donc paire. La fonction $\alpha$ définie par :

$$\alpha(x) = \frac{1}{2} \ \Big[\varphi(x) - \varphi(-x)\Big]$$

pour tout réel $x$ vérifie :

$$\alpha(-x) = \frac{1}{2} \  \Big[\varphi(-x) - \varphi(x)\Big] = - \frac{1}{2} \  \Big[\varphi(x) - \varphi(-x)\Big] = - \alpha(x)$$

Cette fonction est donc impaire. On voit que :

$$\sigma(x) + \alpha(x) = \frac{1}{2} \  \Big[\varphi(x) + \varphi(-x) + \varphi(x) - \varphi(-x)\Big] = \frac{2}{2} \ \varphi(x) = \varphi(x)$$

On a donc la décomposition :

$$\varphi = \sigma + \alpha$$

où $\sigma$ est paire et $\alpha$ impaire. On dit que $\sigma$ est la composante paire de $\varphi$ et que $\alpha$ est la composante impaire de $\varphi$·
