
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 03 : Nombres - 4
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Booléens

#+TOC: headlines 1 local

\label{chap:booleens}


** Dépendances

  - Chapitre \ref{chap:operations} : Les opérations
  - Chapitre \ref{chap:algebre} : L'algèbre


** Définition

L'ensemble de Boole se définit par :

$$\setB = \{ 0 , 1 \}$$

On associe souvent à $0$ le sens de « faux » et à $1$ le sens de « vrai ».


** La loi « et »

Soit $C_1, C_2 \in \setB$. La condition « $C_1$ et $C_2$ » n'est vraie ($=1$) que si $C_1 = 1$ et $C_2 = 1$. On définit donc l'opération « ET », notée $\cdot : \setB \times \setB \mapsto \setB$, par :

#+BEGIN_CENTER
\(
1 \cdot 1 = 1 \\
1 \cdot 0 = 0 \\
0 \cdot 1 = 0 \\
0 \cdot 0 = 0
\)
#+END_CENTER


** La loi « ou »

Soit $C_1, C_2 \in \setB$. La condition « $C_1$ ou $C_2$ » est vraie ($=1$) dès qu'au moins un des deux $C_i = 1$. On définit donc l'opération « OU », notée $\oplus : \setB \times \setB \mapsto \setB$, par :

#+BEGIN_CENTER
\(
1 \oplus 1 = 1 \\
1 \oplus 0 = 1 \\
0 \oplus 1 = 1 \\
0 \oplus 0 = 0
\)
#+END_CENTER


** Le contraire

Le contraire de vrai est simplement faux et inversément. On définit donc le contraire de $C \in \setB$ noté $\neg C$, par :

#+BEGIN_CENTER
\(
\neg 1 = 0 \\
\neg 0 = 1
\)
#+END_CENTER


* Fonctions et opérations

\label{chap:fonctionsEtOperations}


** Dépendances

  - Chapitre \ref{chap:algebre} : L'algèbre
  - Chapitre \ref{chap:naturels} : Les naturels
  - Chapitre \ref{chap:entiers} : Les entiers
  - Chapitre \ref{chap:rationnels} : Les rationnels


** Opérations induites

Soit les fonctions $f,g \in B^A$ et $\divideontimes$ une opération sur $A$.
On définit alors la fonction $f \divideontimes g$ par :

$$(f \divideontimes g)(x) = f(x) \divideontimes g(x)$$

pour tout $x \in A$. Nous avons ainsi défini une opération sur $B^A$ :

$$\divideontimes : B^A \times B^A \mapsto B^A$$

induite par la loi équivalente sur $B$.


*** Usuelles

Sur les anneaux et les corps, ou sur tout ensemble où sont définies
les opérations usuelles $+,-,\cdot,/$, on aura ainsi :

  - les sommes : $(f + g)(x) = f(x) + g(x)$
  - les produits : $(f \cdot g)(x) = f(x) \cdot g(x)$
  - les soustractions : $(f - g)(x) = f(x) - g(x)$
  - les divisions : $(f / g)(x) = f(x) / g(x)$

pour tout $x \in A$.


** Opposé et inverse

Soit la fonction $f \in B^A$. Si l'inverse pour l'addition $-f(x)$ existe
pour tout $x \in A$, on définit la fonction opposée $-f$ par :

$$(-f)(x) = -f(x)$$

pour tout $x \in A$. On a alors :

$$f - f = 0$$

Si l'inverse pour la multiplication $1/f(x)$ existe pour tout $x \in A$,
on définit la fonction $1/f$ par :

$$(1/f)(x) = 1/f(x)$$

pour tout $x \in A$. On a alors :

$$f \cdot 1/f = 1$$


** Opérations mixte

Soit la fonction $f \in B^A$ et $c \in B$. Étant donnée une opération
$\divideontimes$ définie sur $B$, on définit les opérations mixtes
$f \divideontimes c$ et $c \divideontimes f$ par :

#+BEGIN_CENTER
\(
(f \divideontimes c)(x) = f(x) \divideontimes c \\
(c \divideontimes f)(x) = c \divideontimes f
\)
#+END_CENTER

pour tout $x \in A$. Dans le cas où l'opération $\divideontimes$ définie
sur $B$ est commutative, on a bien entendu $f \divideontimes c = c \divideontimes f$.

Sur les ensembles où sont définies les lois usuelles $+,-,\cdot,/$,
on aura ainsi :


  - les sommes :

#+BEGIN_CENTER
\(
(f + c)(x) = f(x) + c \\
(c + f)(x) = c + f(x)
\)
#+END_CENTER

  - les produits :

#+BEGIN_CENTER
\(
(f \cdot c)(x) = f(x) \cdot c \\
(c \cdot f)(x) = c \cdot f(x)
\)
#+END_CENTER

  - les soustractions :

#+BEGIN_CENTER
\(
(f - c)(x) = f(x) - c \\
(c - f)(x) = c - f(x)
\)
#+END_CENTER

  - les divisions :

#+BEGIN_CENTER
\(
(f / c)(x) = f(x) / c \\
(c / f)(x) = c / f(x)
\)
#+END_CENTER


pour tout $x \in A$.


** Commutateur

Notons qu'en général la composée n'est pas commutative. On peut en
effet trouver des fonctions $f,g : A \mapsto A$
telles que $f \circ g \ne g \circ f$.

Cette constatation nous amène à la notion de commutateur. Il s'agit
d'une fonction $[f,g] : A \mapsto A$ définie par :

$$[f,g] = f \circ g - g \circ f$$

Cet opérateur est clairement antisymétrique :

$$[f,g] = - [g,f]$$

Dans le cas particulier où $[f,g] = 0$, on dit que les fonctions
$f$ et $g$ commutent.


** Puissance fonctionnelle et puissance

Attention à ne pas confondre exposant de la fonction et exposant de
la valeur de la fonction en un point :

$$f(x)^n = f(x) \cdot f(x)^{n - 1} \ne f^n(x) = (f \circ f^{n - 1})(x)$$


** Noyau

Le noyau d'une fonction $f : A \mapsto B$ est l'ensemble des $x \in A$
où les valeurs de $f$ sont égales au neutre pour l'addition :

$$\noyau f = \{ x \in A : f(x) = 0 \}$$


** Support d'une fonction

Le support d'une fonction $f : A \mapsto \Omega$ est l'adhérence
de l'ensemble des points où $f$ prend une valeur non nulle :

$$\support f = \adh \{ x \in A : f(x) \ne 0 \}$$


*** Remarque

Attention à ne pas confondre le suprémum d'un ensemble,
noté « $\sup$ » avec un seul « p », avec le support,
noté « $\support$ », qui prend deux « p ».


* Fonctions indicatrices

\label{chap:fonctionsIndicatrices}


** Dépendances

  - Chapitre \ref{chap:algebre} : Les structures algébriques
  - Chapitre \ref{chap:ordres} : Les ordres
  - Chapitre \ref{chap:naturels} : Les naturels
  - Chapitre \ref{chap:entiers} : Les entiers
  - Chapitre \ref{chap:rationnels} : Les rationnels


** Définition

Soit un ensemble de référence $\Omega$ et $A \subseteq \Omega$. La fonction indicatrice

$$\indicatrice_A : \Omega \mapsto \{ 0 , 1 \}$$

associée à l'ensemble $A$ permet de déterminer si un élément quelconque de $\Omega$ appartient où non à $A$. Elle est définie par :

$$\indicatrice_A(x) =
\begin{cases}
1 & \text{si } \ x \in A \\
0 & \text{si } \ x \in \Omega \setminus A
\end{cases}$$


*** Crochets

On note aussi :

$$\indicatrice[A] = \indicatrice_A$$

et :

$$\indicatrice[A](x) = \indicatrice_A(x)$$


** Ensemble vide

Notons en particulier que :

$$\indicatrice[\emptyset] = 0$$


** Ordre

Soit $A,B \subseteq \Omega$ avec $A \subseteq B$. On voit que :


  - pour tout $x \in A$, on a aussi $x \in B$ et $\indicatrice_A(x) = \indicatrice_B(x) = 1$

  - pour tout $x \in \Omega \setminus A$, on a $\indicatrice_A(x) = 0 \le \indicatrice_B(x)$


On en conclut que :

$$\indicatrice_A(x) \le \indicatrice_B(x)$$

pour tout $x \in \Omega$, c'est-à-dire :

$$\indicatrice_A \le \indicatrice_B$$

L'ordre des fonctions indicatrices correspond à l'ordre inclusif des ensembles.


** Intersection

Soit $A, B \subseteq \Omega$. On voit que :

  - si $x \in A \cap B$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 1 \cdot 1 = 1 = \indicatrice[A \cap B](x)$
  - si $x \in A \cap (\Omega \setminus B)$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 1 \cdot 0 = 0 = \indicatrice[A \cap B](x)$
  - si $x \in (\Omega \setminus A) \cap B$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 0 \cdot 1 = 0 = \indicatrice[A \cap B](x)$
  - si $x \in \Omega \setminus (A \cup B)$, on a $\indicatrice_A(x) \cdot \indicatrice_B(x) = 0 \cdot 0 = 0 = \indicatrice[A \cap B](x)$

Donc :

$$\indicatrice[A \cap B] = \indicatrice_A \cdot \indicatrice_B$$


** Union d'ensembles disjoints

Si $A \cap B = \emptyset$, on a clairement :

$$\indicatrice[A \cup B] = \indicatrice_A + \indicatrice_B$$


** Différence

Soit les ensembles $A$ et $B$. On a la décomposition :

$$A = (A \setminus B) \cup (A \cap B)$$

On sait que les deux sous-ensembles sont disjoints :

$$(A \setminus B) \cap (A \cap B) = \emptyset$$

On a donc :

$$\indicatrice_A = \indicatrice[A \setminus B] + \indicatrice[A \cap B]$$

On en conclut que :

\begin{align}
\indicatrice[A \setminus B] &= \indicatrice_A - \indicatrice[A \cap B] \\
&= \indicatrice_A - \indicatrice_A \cdot \indicatrice_B
\end{align}


** Union d'ensembles quelconques

Soit les ensembles $A$ et $B$. On a la décomposition :

$$A \cup B = (A \setminus B) \cup B$$

On voit que les deux sous-ensembles sont disjoints :

$$(A \setminus B) \cap B = \emptyset$$

On en conclut que :

$$\indicatrice[A \cup B] = \indicatrice[A \setminus B] + \indicatrice_B$$

Reprenant l'expression de la différence, on a finalement :

\begin{align}
\indicatrice[A \cup B] &= \indicatrice_A + \indicatrice_B - \indicatrice[A \cap B] \\
&= \indicatrice_A + \indicatrice_B - \indicatrice_A \cdot \indicatrice_B
\end{align}


** Produit cartésien

Pour tout $(x,y) \in A \times B$, on a :

$$\indicatrice[A \times B](x,y) = \indicatrice_A(x) \cdot \indicatrice_B(y)$$


** Delta de Kronecker

Considérons l'ensemble $I \subset \Omega^2$ défini par :

$$I = \{ (i,j) \in \Omega^2 : i = j \}$$

Le delta de Kronecker est simplement :

$$\indicatrice_{ij} = \indicatrice_I(i,j)$$

On a donc :

#+BEGIN_CENTER
\(
\indicatrice_{ij} =
\begin{cases}
1 & \text{si } i = j \\
0 & \text{si } i \neq j
\end{cases}
\)
#+END_CENTER


*** Notation

On note aussi :

$$\indicatrice^{ij} = \indicatrice_i^j = \indicatrice_{ij}$$


* Parité

\label{chap:parite}


** Définition

On dit qu'une fonction $\sigma : \corps \mapsto \corps$ est paire si :

$$\sigma(-x) = \sigma(x)$$

pour tout réel $x$. Inversément, on dit qu'une fonction $\alpha : \corps \mapsto \corps$ est impaire si :

$$\alpha(-x) = - \alpha(x)$$

pour tout réel $x$.


** Décomposition

Soit une fonction $\varphi : \corps \mapsto \corps$. La fonction $\sigma$ définie par :

$$\sigma(x) = \frac{1}{2} \  \Big[\varphi(x) + \varphi(-x)\Big]$$

pour tout réel $x$ vérifie :

$$\sigma(-x) = \frac{1}{2} \ \Big[\varphi(-x) + \varphi(x)\Big] =
\frac{1}{2} \ \Big[\varphi(x) + \varphi(-x)\Big] = \sigma(x)$$

Cette fonction est donc paire. La fonction $\alpha$ définie par :

$$\alpha(x) = \frac{1}{2} \ \Big[\varphi(x) - \varphi(-x)\Big]$$

pour tout réel $x$ vérifie :

$$\alpha(-x) = \frac{1}{2} \  \Big[\varphi(-x) - \varphi(x)\Big] = - \frac{1}{2} \  \Big[\varphi(x) - \varphi(-x)\Big] = - \alpha(x)$$

Cette fonction est donc impaire. On voit que :

$$\sigma(x) + \alpha(x) = \frac{1}{2} \  \Big[\varphi(x) + \varphi(-x) + \varphi(x) - \varphi(-x)\Big] = \frac{2}{2} \ \varphi(x) = \varphi(x)$$

On a donc la décomposition :

$$\varphi = \sigma + \alpha$$

où $\sigma$ est paire et $\alpha$ impaire. On dit que $\sigma$ est la composante paire de $\varphi$ et que $\alpha$ est la composante impaire de $\varphi$·
