
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 05 : Nombres composés - 1
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Complexes

#+TOC: headlines 1 local

\label{chap:complexes}


** Dépendances

  - Chapitre \ref{chap:naturels} : Les nombres naturels
  - Chapitre \ref{chap:entiers} : Les nombres entiers
  - Chapitre \ref{chap:rationnels} : Les nombres rationnels
  - Chapitre \ref{chap:reels} : Les nombres réels


** Nombre imaginaire

Nous avons vu que le carré d'un nombre positif est forcément positif. Par conséquent, on ne peut pas trouver de $x \in \setR$ tel que :

$$x^2 = -1$$

Il nous faut donc inventer un nouvel objet, que l'on nomme nombre imaginaire, et que l'on note $\img$, tel que :

$$\img^2 = -1$$

On peut dès lors étendre la définition de la racine carrée par :

$$\sqrt{-1} = \img$$

Soit $x \in \setR$. Comme l'on veut conserver les propriétés des produits et puissances, on note que :

$$(x \cdot \img)^2 = x^2 \cdot \img^2 = x^2 \cdot (-1) = - x^2$$

On a par conséquent :

$$\sqrt{-x^2} = x \cdot \img$$


*** Notation

On note aussi :

$$x \img = \img x = x \cdot \img$$


*** Remarque

Attention à ne pas confondre les variables « $i$ » avec le nombre imaginaire « $\img$ ».


** Définition

Nous allons à présent nous intéresser aux propriétés algébriques des couples nombre réel - nombre imaginaire. Pour tout $(a, b) \in \setR^2$, nous introduisons la notation complexe :

$$a + \img b$$

L'ensemble des nombres complexes est simplement l'ensemble des couples réel - imaginaire :

$$\setC = \{ a + \img b : \ a,b \in \setR \}$$


** Parties réelles et imaginaires

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

On nomme $a$ la partie réelle de $z$, et on la note :

$$\Re(z) = a$$

On nomme $b$ la partie imaginaire de $z$, et on la note :

$$\Im(z) = b$$

On a donc :

$$z = \Re(z) + \img \Im(z)$$


** Complexe conjugué

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

Le complexe conjugué de $z$ est le nombre donné par :

$$\conjaccent{z} = \conjugue(z) = a + \img (-b) = a - \img b$$

On a donc :

#+BEGIN_CENTER
\(
\Re(\conjaccent{z}) = \Re(z) \\
\Im(\conjaccent{z}) = - \Im(z)
\)
#+END_CENTER


*** Conjugué carré

Il est clair d'après la définition que :

$$\conjugue \conjugue z = z$$


** Addition

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \\
y = c + \img d
\)
#+END_CENTER

Comme nous désirons conserver les propriétés de commutativité et d'associativité de l'addition, on a :

$$x + y = a + \img b + c + \img d = (a + c) + \img (b + d)$$


** Soustraction

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \\
y = c + \img d
\)
#+END_CENTER

Comme nous souhaitons conserver les propriétés de la soustraction, on a simplement :

$$x + y = a + \img b - (c + \img d) = a + \img b - c - \img d = (a - c) + \img (b - d)$$


** Multiplication

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \\
y = c + \img d
\)
#+END_CENTER

Comme nous voulons conserver les propriétés de la multiplication, nous écrivons :

$$x \cdot y = (a + \img b) \cdot (c + \img d) = a \cdot c + \img a \cdot d + \img b \cdot c + \img^2 b  \cdot d$$

En tenant compte de la définition du nombre imaginaire, on a :

$$x \cdot y = a \cdot c + \img a \cdot d + \img b \cdot c - b  \cdot d$$

et finalement :

$$x \cdot y = (a \cdot c - b  \cdot d) + \img (a \cdot d + b \cdot c)$$

On a donc :

#+BEGIN_CENTER
\(
\Re(x \cdot y) = \Re(x) \cdot \Re(y) - \Im(x) \cdot \Im(y) \\
\Im(x \cdot y) = \Re(x) \cdot \Im(y) + \Im(x) \cdot \Re(y)
\)
#+END_CENTER


*** Mixte

On en déduit le cas particulier suivant :

$$(a + \img b) \cdot c = a \cdot c + \img b \cdot c$$

*** Multiplication par $\img$

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

Comme :

$$\img z = \img a + \img^2 b = \img a - b$$

on a :

#+BEGIN_CENTER
\(
\Re(\img z) = -b = - \Im(z) \\
\Im(\img z) = a = \Re(z)
\)
#+END_CENTER


*** Conjugué

On a :

$$\conjugue(x) \cdot \conjugue(y) = (a \cdot c - b  \cdot d) - \img (a \cdot d + b \cdot c) = \conjugue(x \cdot y)$$


** Module

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

On définit le module de $z$ par :

$$\abs{z} = \sqrt{a^2 + b^2} \ge 0$$

On voit que le module est un réel positif. Dans le cas d'un réel, le module s'identifie à la valeur absolue, ce qui justifie la notation identique.


*** Conjugué

On voit que :

$$z \cdot \conjaccent{z} = (a + \img b) \cdot (a - \img b) = a^2 + b^2 + \img (a \cdot b - a \cdot b) = a^2 + b^2$$

c'est-à-dire :

$$z \cdot \conjaccent{z} = \abs{z}^2$$


** Inverse

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

Multiplions la relation $z \cdot \conjaccent{z} = \abs{z}^2$ par :

$$\left( z \cdot \abs{z}^2 \right)^{-1}$$

Il vient :

$$\unsur{z} = \frac{ \conjaccent{z} }{ \abs{z}^2 }$$

Nous pouvons donc évaluer l'inverse d'un nombre complexe :

$$\unsur{z} = \frac{ a - \img b }{ a^2 + b^2 } = \frac{ a }{ a^2 + b^2 } - \img \frac{ b }{ a^2 + b^2 }$$

*** Inverse de $\img$

On a en particulier :

$$\unsur{\img} = -\img$$


** Division

Soient $x,y \in \setC$ et $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \\
y = c + \img d
\)
#+END_CENTER

On définit la division de deux nombres complexes par :

$$\frac{x}{y} = x \cdot \unsur{y} = \frac{ x \cdot \conjaccent{y} }{ \abs{y}^2 }$$

On a donc :

$$\frac{x}{y} = \frac{(a + \img b) \cdot (c - \img d)}{c^2 + d^2}$$

ou encore :

$$\frac{x}{y} = \frac{(a \cdot c + b \cdot d) + \img (b \cdot c - a \cdot d)}{c^2 + d^2}$$


** Obtention des parties réelles et imaginaires

Soit $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

En additionnant $z$ et son conjugué, on obtient :

$$z + \conjaccent{z} = (a + \img b) + (a - \img b) = 2 a = 2 \Re(z)$$

ce qui permet d'obtenir une expression de la partie réelle :

$$\Re(z) = \unsur{2}(z + \conjaccent{z})$$

En soustrayant $z$ et $\conjaccent{z}$, on obtient :

$$z - \conjaccent{z} = (a + \img b) - (a - \img b) = 2 \img b = 2 \img \Im(z)$$

ce qui permet d'obtenir une expression de la partie imaginaire :

$$\Im(z) = \unsur{2\img}(z - \conjaccent{z})$$


*** Cas particuliers

On en déduit directement que si $z = \conjaccent{z}$, on a $\Im(z) = 0$ et $z\in\setR$. Par contre, si $z = -\conjaccent{z}$, on a $\Re(z) = 0$ et $z$ est purement imaginaire.


** Puissance

Soit $n \in \setN$ avec $n \ne 0$, $z \in \setC$ et $a,b \in \setR$ tels que :

$$z = a + \img b$$

On définit la $n^{ième}$ puissance d'un nombre complexe par :

#+BEGIN_CENTER
\(
z^0 = 1 \\
z^n = z \cdot z^{n-1}
\)
#+END_CENTER


*** Négatives

Les puissances négatives sont données par :

$$z^{-n} = \unsur{z^n}$$


*** Racines

La $n^{ième}$ racine $x \in \setC$ de $z$ est définie par :

$$x^n = z$$

On a alors :

$$z = x^{1/n}$$


*** Fractionnaires

Soit $m \in \setN$. on a simplement :

$$z^{m/n} = \left( z^{1/n} \right)^m$$


*** Réelles

Soit $s \in \setR$ et une suite $\{ r_i \in \setQ : i \in \setN \}$ qui converge vers $s$. On définit :

$$z^s = \lim_{i \to \infty} z^{r_i}$$


** Ordre partiel

Soit les complexes $x,y \in \setC$ et les réels $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \\
y = c + \img d
\)
#+END_CENTER

On dit que $x$ est plus petit que $y$ au sens des composantes, et on le note $x \le y$ si les deux conditions suivantes sont vérifiées :

#+BEGIN_CENTER
\(
a \le c \\
b \le d
\)
#+END_CENTER


** Ordre total

Soit les complexes $x,y \in \setC$ et les réels $a,b,c,d \in \setR$ tels que :

#+BEGIN_CENTER
\(
x = a + \img b \\
y = c + \img d
\)
#+END_CENTER

On dit que $x$ est plus petit que $y$ et on le note $x \preceq y$ si :

$$a \strictinferieur c$$

ou si les conditions suivantes sont vérifiées :

#+BEGIN_CENTER
\(
a = c \\
b \le d
\)
#+END_CENTER


** Inclusion

Pour tout $a \in \setR$, on a $a = a + \img 0 \in \setC$. On considère donc que $\setR \subseteq \setC$.


* Intervalles de réels

#+TOC: headlines 1 local

\label{chap:intervallesDeReels}


** Dépendances

  - Chapitre \ref{chap:reel} : Les nombres réels


** Intervalles bornés

Soit $a,b \in \setR$ avec $a \le b$. L'intervalle fermé $[a,b]$ est défini par :

$$[a,b] = \{ x \in \setR : a \le x \le b \}$$

L'intervalle ouvert $\intervalleouvert{a}{b}$ est défini par :

$$\intervalleouvert{a}{b} \ = \{ x \in \setR : a \strictinferieur x \strictinferieur b \}$$

On recontre aussi les intervalles semi-ouverts à gauche :

$$\intervallesemiouvertgauche{a}{b} = \{ x \in \setR : a \strictinferieur x \le b \}$$

ou à droite :

$$\intervallesemiouvertdroite{a}{b} \ = \{ x \in \setR : a \le x \strictinferieur b \}$$


** Intervalles non bornés

Soit $a \in \setR$. Les intervalles non bornés sont des intervalles partant de l'infini négatif ou/et allant jusqu'à l'infini positif :

\begin{eqnarray*}\relax
\intervallesemiouvertdroite{a}{+\infty} &=& \{ x \in \setR : x \ge a \} \\
\intervalleouvert{a}{+\infty} &=& \{ x \in \setR : x \strictsuperieur a \} \\
\intervallesemiouvertgauche{-\infty}{a} &=& \{ x \in \setR : x \le a \} \\
\intervalleouvert{-\infty}{a} &=& \{ x \in \setR : x \strictinferieur a \} \\
\intervalleouvert{-\infty}{+\infty} &=& \setR
\end{eqnarray*}


** Boules

Soit $c,r,x \in \setR$ avec $r \ge 0$. La condition $\abs{x - c} \le r$ est équivalente à $x - c \le r$ et $-(x - c) = c - x \le r$. On en déduit que :

#+BEGIN_CENTER
\(
x \le c + r \\
x \ge c - r
\)
#+END_CENTER

ce qui revient à dire que $x \in [c - r, c + r]$. Nous obtenons un résultat analogue avec les inégalités strictes. On peut donc exprimer les boules en terme d'intervalles :

\begin{eqnarray*}
\boule[c,r] &=& [c - r, c + r] \\
\boule(c,r) &=& \ \intervalleouvert{c - r}{c + r}
\end{eqnarray*}

On peut inverser ces relations et exprimer certains intervalles en termes de boules. Soit $a = c - r$ et $b = c + r$. On a alors $a \le b$ et :

#+BEGIN_CENTER
\(
a + b = c - r + c + r = 2 c \\
b - a = c + r - c + r = 2 r
\)
#+END_CENTER

On en déduit que :

\begin{eqnarray*}\relax
[a,b] &=& \boule\left[\frac{a + b}{2},\frac{b - a}{2}\right] \\ \\
\intervalleouvert{a}{b} &=& \boule\left(\frac{a + b}{2},\frac{b - a}{2}\right)
\end{eqnarray*}


** Majorants et minorants

Soit $a,b \in \setR$ avec $a \le b$ et $x \in \setR$.

Pour que $x \ge [a,b]$, il faut que $x \ge b$. Si $y \in [a,b]$, on aura alors $x \ge b \ge y$ d'où $x \ge y$ par transitivité de l'ordre. On en déduit que :

$$\major [a,b] = \intervallesemiouvertgauche{b}{+\infty}$$

On obtient le même résultat pour l'intervalle ouvert :

$$\major \intervalleouvert{a}{b} = \intervallesemiouvertgauche{b}{+\infty}$$

ainsi que pour les intervalles semi-ouverts.

Pour que $x \le [a,b]$, il faut que $x \le a$. Si $y \in [a,b]$, on aura alors $x \le a \le y$ d'où $x \le y$ par transitivité de l'ordre. On en déduit que :

$$\minor [a,b] = \intervallesemiouvertdroite{-\infty}{a}$$

On obtient le même résultat pour l'intervalle ouvert :

$$\minor \intervalleouvert{a}{b} = \intervallesemiouvertdroite{-\infty}{a}$$

ainsi que pour les intervalles semi-ouverts.


** Maximum et minimum

Soit $a,b \in \setR$ avec $a \le b$. On a clairement :

\begin{eqnarray*}
\max [a,b] &=& \max \intervallesemiouvertgauche{a}{b} = \max \intervallesemiouvertgauche{-\infty}{b} = b \\
\min [a,b] &=& \min \intervallesemiouvertdroite{a}{b} = \min \intervallesemiouvertdroite{a}{+\infty} \ = a
\end{eqnarray*}

Les autre types d'intervalles n'admettent ni maximum ni minimum.


** Supremum et infimum

Dans le cas où le maximum de l'intervalle $I$ existe, on a $\sup I = \max I$. Dans les autres cas, on a par exemple :

$$\sup \intervalleouvert{a}{b} = \min \major \intervalleouvert{a}{b} = \min [b, +\infty[ \ = b$$

et le même résultat pour les intervalles semi-ouverts.

Dans le cas où le minimum de l'intervalle $I$ existe, on a $\inf I = \min I$. Dans les autres cas, on a par exemple :

$$\inf \intervalleouvert{a}{b} = \max \minor \intervalleouvert{a}{b} = \max \ ]-\infty, a] = a$$

et le même résultat pour les intervalles semi-ouverts.


** Adhérence, intérieur et frontière

On peut vérifier que :

\begin{eqnarray*}
\adh [a,b] &=& \adh \intervalleouvert{a}{b} = [a,b] \\
\interieur [a,b] &=& \interieur \intervalleouvert{a}{b} = \ ]a,b[
\end{eqnarray*}

et ainsi de suite. La frontière est donc simplement :

$$\partial [a,b] = \partial \intervalleouvert{a}{b} = \{a,b\}$$


* Dimension $n$

#+TOC: headlines 1 local

\label{chap:dimensionN}


** Dépendances

  - Chapitre \ref{chap:naturel} : Les naturels
  - Chapitre \ref{chap:entier} : Les entiers
  - Chapitre \ref{chap:rationel} : Les rationnels
  - Chapitre \ref{chap:reel} : Les réels
  - Chapitre \ref{chap:complexe} : Les complexes


** Définition

Conformément à la définition de la « puissance » d'un ensemble, $\setN^n$ est l'ensemble des $n$-tuples :

$$\setN^n = \{ (m_1,m_2,...,m_n) : m_1,m_2,...,m_n \in \setN \}$$

où chaque composante $m_i$ est un naturel. On a pareillement :

#+BEGIN_CENTER
\(
\setZ^n = \{ (z_1,z_2,...,z_n) : z_1,z_2,...,z_n \in \setN \} \\
\setQ^n = \{ (q_1,q_2,...,q_n) : q_1,q_2,...,q_n \in \setQ \} \\
\setR^n = \{ (r_1,r_2,...,r_n) : r_1,r_2,...,r_n \in \setR \} \\
\setC^n = \{ (c_1,c_2,...,c_n) : c_1,c_2,...,c_n \in \setC \}
\)
#+END_CENTER

Dans la suite, nous notons :

$$\mathcal{D} = \{ \setN^n , \setZ^n , \setQ^n , \setR^n , \setC^n \}$$

On dit que les éléments de $\mathcal{D}$ sont des ensembles de dimension $n$.


** Egalité

Soit l'ensemble $A^n \in \mathcal{D}$ et $x,y \in A^n$. On a :

#+BEGIN_CENTER
\(
x = (x_1,x_2,...,x_n) \\
y = (y_1,y_2,...,y_n)
\)
#+END_CENTER

On dit que $x = y$ si et seulement si $x_i = y_i$ pour tout $i \in \{1,2,...,n\}$.

De même, on dit que $x = 0$ si et seulement si $x_i = 0$ pour tout $i \in \{1,2,...,n\}$.


** Ordre partiel

Soit l'ensemble $A^n \in \mathcal{D}$ et $x,y \in A^n$. On a :

#+BEGIN_CENTER
\(
x = (x_1,x_2,...,x_n) \\
y = (y_1,y_2,...,y_n)
\)
#+END_CENTER

On dit que $x \le y$ si et seulement si $x_i \le y_i$ pour tout $i \in \{1,2,...,n\}$. On le note aussi $y \ge x$.

On dit que $x \strictinferieur y$ si et seulement si $x_i \strictinferieur y_i$ pour tout $i \in \{1,2,...,n\}$. On le note aussi $y \strictsuperieur x$.


** Opérations internes

Soit l'ensemble $A^n \in \mathcal{D}$ et $x,y \in A^n$. On a :

#+BEGIN_CENTER
\(
x = (x_1,x_2,...,x_n) \\
y = (y_1,y_2,...,y_n)
\)
#+END_CENTER

pour certains $x_i,y_i \in A$.

Les opérations sur $A^n$ sont définies par la même opération appliquée aux composantes. L'addition s'écrit donc :

$$x + y = (x_1 + y_1 , x_2 + y_2 , ... , x_n + y_n)$$

tandis que la soustraction est donnée par :

$$x - y = (x_1 - y_1 , x_2 - y_2 , ... , x_n - y_n)$$


** Multiplication mixte

La multiplication mixte $\cdot : A \times A^n \to A^n$ est définie par :

$$\alpha \cdot x = (\alpha \cdot x_1 , \alpha \cdot x_2 , ... , \alpha \cdot x_n)$$

pour tout $\alpha \in A$.


*** Notations

On note bien entendu :

$$x \cdot \alpha = \alpha \cdot x$$

Choisissant un $\beta \in A$, on pose également :

$$\alpha \cdot \beta \cdot x = (\alpha \cdot \beta) \cdot x$$

Enfin, le signe de multiplication est souvent omis :

$$\alpha \ x = \alpha \cdot x$$


** Neutre

Soit l'ensemble $A^n \in \mathcal{D}$. On note :

$$0 = (0,0,...,0)$$

l'élément $0 \in A^n$


** Lien avec les fonctions

On voit clairement que ces relations et opérations sont équivalentes aux mêmes relations et opérations définies sur les fonctions :

$$\{1,2,...,n\} \mapsto \{f(1),f(2),...,f(n)\} \equiv (f_1,f_2,...,f_n)$$

associées.


** Puissance

Soit $x = (x_1,...x_n) , y = (y_1,...,y_n) \in A^n$. La puissance s'écrit :

$$y^x = y_1^{x_1} \cdot y_2^{x_2} \cdot ... \cdot y_n^{x_n}$$


** Factorielle

Soit $m = (m_1,m_2,...,m_n) \in \setN^n$. On définit :

$$m ! = m_1 ! \cdot m_2 ! \cdot ... \cdot m_n !$$
