
#+STARTUP: showall

#+TITLE: Eclats de vers : Matemat 07 : Intégrales - 1
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+INCLUDE: "../include/commandes-tex.org"

* Mesures

#+TOC: headlines 1 local

\label{chap:mesure}


** Dépendances

  - Chapitre \ref{chap:ensemble} : Les ensembles
  - Chapitre \ref{chap:ordre} : Les ordres et extréma
  - Chapitre \ref{chap:fonction} : Les fonctions


** Introduction

L'objectif des mesures est de « mesurer » des ensembles, ou plutôt des sous-ensembles d'un ensemble donné. Soit l'ensemble $\Omega$ et une tribu de sous-ensembles $\mathcal{T} \subseteq \sousens(\Omega)$. Une mesure sur $\mathcal{T}$ est une fonction $\mu : \mathcal{T} \mapsto \setR$ associant une valeur réelle à chaque ensemble de la tribu. On demande que cette mesure soit positive :

$$\mu(A) \ge 0$$

pour tout $A \in \mathcal{T}$. Il semble également logique que la mesure d'un ensemble vide soit nulle :

$$\mu(\emptyset) = 0$$

Pour toute suite discrète (finie ou infinie) $\{ A_1,A_2,... \} \subseteq \mathcal{T}$ d'ensembles disjoints deux à deux, on a :

$$A_i \cap A_j = \emptyset$$

pour tout $(i,j)$ tels que $i \ne j$. On exige dans ce cas que la mesure vérifie la propriété d'additivité :

$$\mu\left( \bigcup_i A_i \right) = \sum_i \mu(A_i)$$


*** Inclusion

Soit $A,B \in \mathcal{T}$ avec $A \subseteq B$. Comme $C = B \setminus A$ et $A$ vérifient $C \cup A = B$ et $C \cap A = \emptyset$, on a :

$$\mu(B) = \mu(C) + \mu(A) \ge \mu(A)$$

La mesure d'un ensemble « plus petit » au sens de l'inclusion est donc plus petite :

$$\mu(A) \le \mu(B)$$


*** Union

Soit $A,B \in \mathcal{T}$. Comme $A \cup B = (A \setminus B) \cup B$ et $(A \setminus B) \cap B = \emptyset$, on a :

$$\mu(A \cup B) = \mu(A \setminus B) + \mu(B)$$

Comme $A \setminus B \subseteq A$, on a aussi $\mu(A \setminus B) \le \mu(A)$. On en déduit que :

$$\mu(A \cup B) \le \mu(A) + \mu(B)$$

On peut en conclure par récurrence que :

$$\mu\left( \bigcup_{i = 0}^n A_i \right) \le \sum_{i = 0}^n \mu(A_i)$$

Puis, par passage à la limite :

$$\mu\left( \bigcup_{i = 0}^{+\infty} A_i \right) \le \sum_{i = 0}^{+\infty} \mu(A_i)$$


*** Appellation

On dit qu'un ensemble $A$ est mesurable (pour $\mu$) si $A \in \mathcal{T}$. Dans la suite, nous considérons une mesure $\mu : \mathcal{T} \mapsto \setR$ et un ensemble mesurable $A \in \mathcal{T}$.


** Lebesgue

La mesure de Lebesgue $\mu_L$ est définie sur la tribu $\mathcal{T}$ engendrée par les ensembles ouverts de $\setR$. Elle exprime simplement la longueur d'un intervalle. Pour tout :

$$I \in \big\{ \ [a,b], \intervalleouvert{a}{b}, \intervallesemiouvertgauche{a}{b}, \intervallesemiouvertdroite{a}{b} \big\}$$

on a simplement :

$$\mu_L(I) = b - a$$

Soit $\mathfrak{J}$ l'ensemble des collections au plus dénombrables d'intervalles ouverts disjoints. Pour tout $A \in \mathcal{T}$, on définit :

$$\mu_I(A) = \inf \accolades{ \sum_{n \in N} \mu_L(I_n) : \{ I_n : n \in N \subseteq \setN \} \in \mathfrak{J} , \ A \subseteq \bigcup_{n \in N} I_n}$$

et :

$$\mu^S(A) = \sup \accolades{ \sum_{n \in N} \mu_L(I_n) : \{ I_n : n \in N \subseteq \setN \} \in \mathfrak{J} , \ \bigcup_{n \in N} I_n \subseteq A }$$

Si :

$$\mu_I(A) = \mu^S(A)$$

on dit que l'ensemble $A$ est mesurable au sens de Lebesgue et on définit :

$$\mu_L(A) = \mu_I(A) = \mu^S(A)$$


*** Mesure nulle

Pour tout ensemble $N$ inclus dans un ensemble $A \in \mathcal{T}$ de mesure nulle :

$$\mu_L(A) = 0$$

on définit :

$$\mu_L(N) = 0$$


*** Singleton

On voit que les ensembles de la forme $\{a\} = [a,a]$ sont de mesure nulle :

$$\mu_L(\{a\}) = a - a = 0$$

On en conclut que pour toute suite discrète de réels $a_1,a_2,...$, on a :

$$\mu_L(\{a_1,a_2,...\}) = \sum_i \mu_L(\{a_i\}) = 0$$

On a aussi :

\begin{align}
b - a = \mu_L([a,b]) &= \mu_L([a,b] \setminus \{a_1,a_2,...\}) + \mu_L(\{a_1,a_2,...\}) \\
&= \mu_L([a,b] \setminus \{a_1,a_2,...\}) + 0
\end{align}

et donc :

$$\mu_L([a,b] \setminus \{a_1,a_2,...\}) = b - a$$


** Mesure de Stieltjes

On associe à toute fonction croissante $g : \setR \mapsto \setR$ une mesure de Stieltjes $\mu_g$. Pour tout :

$$I \in \big\{ \ [a,b], \intervalleouvert{a}{b}, \intervallesemiouvertgauche{a}{b}, \intervallesemiouvertdroite{a}{b} \big\}$$

on définit :

$$\mu_g(I) = g(b) - g(a)$$

Soit $\mathfrak{J}$ l'ensemble des collections au plus dénombrables d'intervalles ouverts disjoints. Pour tout $A \in \mathcal{T}$, on définit :

$$\mu_g(A) = \inf \accolades{ \sum_{n \in N} \mu_L(I_n) : \{ I_n : n \in N \subseteq \setN \} \in \mathfrak{J} , \ A \subseteq \bigcup_{n \in N} I_n}$$


*** Mesure nulle

Pour tout ensemble $N$ inclus dans un ensemble $A \in \mathcal{T}$ de mesure nulle :

$$\mu_g(A) = 0$$

on définit :

$$\mu_g(N) = 0$$


** Dirac

La mesure de Dirac $\mu_D^a$ en $a$ est définie sur $\sousens(\Omega)$. Il s'agit d'une mesure permettant de détecter si un $A \subseteq \Omega$ donné contient $a$. Elle est donc basée sur les fonctions indicatrices :

#+BEGIN_CENTER
\(
\mu_D^a(A) = \indicatrice_A(a) =
\begin{cases}
1 & \mbox{  si  } a \in A \\
0 & \mbox{  si  } a \notin A
\end{cases}
\)
#+END_CENTER


** Mesure produit

Soit les tribus $\mathcal{T}_1$ et $\mathcal{T}_2$ et la tribu produit :

$$\mathcal{P} = \{ A \times B : A \in \mathcal{T}_1, \ B \in \mathcal{T}_2 \}$$

A partir de mesures $\mu : \mathcal{T}_1 \mapsto \setR$ et $\nu : \mathcal{T}_2 \mapsto \setR$, on peut construire une mesure produit $\mu \otimes \nu : \mathcal{P} \mapsto \setR$ par :

$$(\mu \otimes \nu)(A \times B) = \mu(A) \cdot \nu(B)$$


*** Dimension $n$

On généralise la mesure de Lebesgue sur $\setR^n$ par :

$$\mu_L( \intervalleouvert{a_1}{b_1} \times \intervalleouvert{a_2}{b_2} ... \times \intervalleouvert{a_n}{b_n}) = \prod_{i = 1}^n (b_i - a_i)$$

et l'extension à la tribu engendrée par les ouverts de $\setR^n$ au moyen des
supremum et infimum.


** Fonction mesurable

On dit qu'une fonction $f : A \mapsto \setR$ est mesurable (au sens de la tribu $\mathcal{T}$) si la relation $f^{-1}$ vérifie $f^{-1}(]a,+\infty[) \in \mathcal{T}$ et $f^{-1}(]-\infty,a[) \in \mathcal{T}$ pour tout $a \in \setR$. On a donc :

#+BEGIN_CENTER
\(
\{ x \in A : f(x) \strictsuperieur a \} \in \mathcal{T} \\
\{ x \in A : f(x) \strictinferieur a \} \in \mathcal{T}
\)
#+END_CENTER


*** Corollaires

On a :

#+BEGIN_CENTER
\(
\{ x \in A : f(x) \ge a \} = A \setminus \{ x \in A : f(x) \strictinferieur a \} \in \mathcal{T} \\
\{ x \in A : f(x) \le a \} = A \setminus \{ x \in A : f(x) \strictsuperieur a \} \in \mathcal{T}
\)
#+END_CENTER

et :

$$\{ x \in A : f(x) = a \} = \{ x \in A : f(x) \ge a \} \cap \{ x \in A : f(x) \le a \} \in \mathcal{T}$$

Les mesures de tous ces ensembles sont donc bien définies pour tout $a \in \setR$.


** Opposé d'une fonction mesurable

Soit une fonction mesurable $f : A \mapsto \setR$. On a :

#+BEGIN_CENTER
\(
\{ x \in A : -f(x) \strictsuperieur a \} = \{ x \in A : f(x) \strictinferieur -a \} \in \mathcal{T} \\
\{ x \in A : -f(x) \strictinferieur a \} = \{ x \in A : f(x) \strictsuperieur -a \} \in \mathcal{T}
\)
#+END_CENTER

On en déduit que la fonction opposée $-f$ est mesurable.


** Fonctions extrema

Soit la suite $\{ f_n : n \in \setN \}$ de fonctions mesurables. Posons :

#+BEGIN_CENTER
\(
S = \sup \{ f_n : n \in \setN \} \\
I = \inf \{ f_n : n \in \setN \}
\)
#+END_CENTER

On a :

#+BEGIN_CENTER
\(
\{ x \in A : S(x) \strictsuperieur a \} = \bigcup_n \{ x \in A : f_n(x) \strictsuperieur a \} \in \mathcal{T} \\
\{ x \in A : S(x) \strictinferieur a \} = \bigcap_n \{ x \in A : f_n(x) \strictinferieur a \} \in \mathcal{T}
\)
#+END_CENTER

On en conclut que $\sup_n f_n$ est mesurable. Symétriquement, on a :

#+BEGIN_CENTER
\(
\{ x \in A : I(x) \strictsuperieur a \} = \bigcap_n \{ x \in A : f_n(x) \strictsuperieur a \} \in \mathcal{T} \\
\{ x \in A : I(x) \strictinferieur a \} = \bigcup_n \{ x \in A : f_n(x) \strictinferieur a \} \in \mathcal{T}
\)
#+END_CENTER

On en conclut que $\inf_n f_n$ est mesurable.


* Essentialité

#+TOC: headlines 1 local

\label{chap:essentialite}


** Dépendances

  - Chapitre \ref{chap:mesure} : Les mesures


** Introduction

Soit la mesure $\mu : \mathcal{T} \mapsto \setR$ et l'ensemble $A \in \mathcal{T}$. On a envie de dire que tout sous-ensemble de mesure nulle de $A$ est « négligeable ». L'essentiel de l'information demeurera donc si on s'abstrait d'un quelconque ensemble $N \subseteq A$ vérifiant $N \in \mathcal{T}$ et $\mu(N) = 0$. Le résultat de cette abstraction, soit $A \setminus N$, est appelé sous-ensemble essentiel de $A$. On note :

$$\essentiel(A) = \{ A \setminus N : N \subseteq A, \ N \in \mathcal{T}, \ \mu(N) = 0 \}$$

l'ensemble des sous-ensembles essentiels de $A$.


** Ensembles de mesure nulle


*** Inclusion

Soit $A,B \in \mathcal{T}$ avec $A \subseteq B$ et $\mu(B) = 0$. On a alors :

$$0 \le \mu(A) \le \mu(B) = 0$$

On en déduit que :

$$\mu(A) = 0$$

Un ensemble inclus dans un ensemble de mesure nulle est également de mesure nulle.


*** Union

Soit $A,B \in \mathcal{T}$ avec $\mu(A) = \mu(B) = 0$. On a alors :

$$0 \le \mu(A \cup B) \le \mu(A) + \mu(B) = 0 + 0 = 0$$

On en déduit que :

$$\mu(A \cup B) = 0$$

De même, la mesure d'une union d'une suite finie d'ensembles de mesure nulle est de mesure nulle :

$$\mu\left( \bigcup_{i = 1}^n A_i \right) = 0$$

On a le même résultat pour les suites infinies :

$$\mu\left( \bigcup_{i = 1}^{+\infty} A_i \right) = 0$$


** Mesure d'un sous-ensemble essentiel

Soit $E \in \essentiel(A)$. On peut alors trouver $Z \in \mathcal{T}$ tel que $Z \subseteq A$, $E = A \setminus Z$ et vérifiant $\mu(Z) = 0$. Comme les ensembles $E$ et $Z$ sont disjoints et d'union égale à $A$, on a :

$$\mu(A) = \mu(E) + \mu(Z) = \mu(E) + 0 = \mu(E)$$

On a donc :

$$\mu(E) = \mu(A)$$

pour tout sous-ensemble essentiel $E \in \essentiel(A)$.


** Convergence de la mesure

Soit une suite d'ensembles $\{ A_n \in \mathcal{T} : n \in \setN \}$ telle que $A_m \subseteq A_n$ pour tout naturels $m,n$ vérifiant $m \le n$. Posons :

$$A = \bigcup_{n \in \setN} A_n \in \mathcal{T}$$

Considérons la suite d'ensemble $\{D_n \subseteq A : n \in \setN \}$ définie par :

\begin{align}
D_0 &= A_0 \\
D_n &= A_n \setminus A_{n - 1}
\end{align}

pour tout $n \ge 1$. Comme $A_{n - 1}, D_n \subseteq A_n$, on a $A_n = A_{n - 1} \cup D_n$. Nous allons montrer par récurrence que :

$$A_n = \bigcup_{k = 0}^n D_k$$

On sait que c'est vrai pour $n = 0$. Supposons que ce soit vrai pour $n - 1$. On a :

$$A_n = D_n \cup A_{n - 1} = D_n \cup \bigcup_{k = 0}^{n - 1} D_k = \bigcup_{k = 0}^n D_k$$

Si $x$ appartient à au moins un des $A_n$, il appartient à au moins un des $D_k$ pour $0 \le k \le n$, et inversément. On en déduit que :

$$A = \bigcup_{n \in \setN} A_n = \bigcup_{k \in \setN} D_k$$

Soit les naturels $i,j$ avec $i \ne j$. Soit $m = \max \{ i, j \}$ et $n = \min \{ i,j \}$. Si $D_i = \emptyset$ ou si $D_j = \emptyset$, on a forcément $D_i \cap D_j = \emptyset$. Sinon, soit $x \in D_m$. On a alors $x \in A_m$ et $x \notin A_{m - 1}$. Comme $i \ne j$, on a $m - 1 \ge n$ et $A_n \subseteq A_{m - 1}$. On en déduit que :

$$x \notin A_n = \bigcup_{k = 0}^n D_k \subseteq A_{m - 1}$$

En particulier, $x$ ne peut pas appartenir à $D_n$. On en conclut que $D_i \cap D_j = D_m \cap D_n = \emptyset$. Les propriétés de la mesure nous disent alors que :

$$\mu(A_n) = \sum_{k = 0}^n \mu(D_k)$$

et que :

$$\mu(A) = \sum_{n \in \setN} \mu(D_n)$$

Par définition de la somme infinie sur $\setN$, on a :

$$\sum_{n \in \setN} \mu(D_n) = \lim_{n \to \infty} \sum_{k = 0}^n \mu(D_k)$$

et donc :

$$\lim_{n \to \infty} \mu(A_n) = \mu(A)$$


** Convergence étendue

Soit une suite d'ensembles $\{ A_n \in \mathcal{T} : n \in \setN \}$ telle que, pour tout $n \in \setN$, on puisse trouver un sous-ensemble essentiel $E_n \subseteq A_n$ vérifiant $E_n \subseteq A_{n + 1}$. Posons :

$$A = \bigcup_{n \in \setN} A_n \in \mathcal{T}$$

Pour tout $n \in \setN$, on peut donc trouver un $Z_n \subseteq A_n$ vérifiant $\mu(Z_n) = 0$ et $E_n = A_n \setminus Z_n \subseteq A_{n + 1}$. Notons $Z$ l'union de ces ensembles :

$$Z = \bigcup_{n \in \setN} Z_n$$

et analysons le comportement des $C_n = A_n \setminus Z$. Notons $C$ l'union de ces ensembles. On a :

$$C = \bigcup_{n \in \setN} C_n = \bigcup_{n \in \setN} A_n \setminus Z = A \setminus Z$$

Supposons que $x \in C_n$. On a alors $x \in A_n$ et $x \notin Z_n$, d'où $x \in A_{n + 1}$. Comme $x \notin Z$, on a aussi $x \in A_{n + 1} \setminus Z = C_{n + 1}$. On en conclut que $C_n \subseteq C_{n + 1}$. La récurrence :

$$C_0 \subseteq C_1 \subseteq C_2 \subseteq C_3 \subseteq ...$$

nous montre alors que $C_m \subseteq C_n$ pour tout $m,n \in \setN$ vérifiant $m \le n$. La mesure converge par conséquent vers la mesure de l'union :

$$\lim_{n \to \infty} \mu(C_n) = \mu(C) = \mu(A \setminus Z)$$

Mais comme $C$ est un sous-ensemble essentiel de $A$, on a $\mu(C) = \mu(A)$. Pour la même raison, on a $\mu(C_n) = \mu(A_n)$. On a donc finalement :

$$\lim_{n \to \infty} \mu(A_n) = \mu(A)$$


** Ordre faible


*** Infériorité essentielle

Soit deux fonctions $f,g : A \mapsto \setR$ telles que $f - g$ soit mesurable.
On dit que $f$ est {\em essentiellement} inférieure à $g$, et on le note :

$$f \essinferieur g$$

si on peut trouver un sous-ensemble essentiel $S$ de $A$ tel que $f(x) \le g(x)$ en tout point $x \in S$. On a donc :

$$\mu(\{ x \in A : f(x) \strictsuperieur g(x) \}) = 0$$


*** Supériorité essentielle

Soit deux fonctions $f,g : A \mapsto \setR$ telles que $f - g$ soit mesurable.
On dit que $f$ est {\em essentiellement} supérieure à $g$, et on le note :

$$f \esssuperieur g$$

si on peut trouver un sous-ensemble essentiel $S$ de $A$ tel que $f(x) \ge g(x)$ en tout point $x \in S$. On a donc :

$$\mu(\{ x \in A : f(x) \strictinferieur g(x) \}) = 0$$


*** Validité

La définition de $f \essinferieur g$ revient à imposer que :

$$\mu(\{ x \in A : f(x) - g(x) \strictsuperieur 0 \}) = 0$$

La définition de $f \esssuperieur g$ revient à imposer que :

$$\mu(\{ x \in A : f(x) - g(x) \strictinferieur 0 \}) = 0$$

Comme $f - g$ est mesurable, ces notions sont correctement définies.


** Transitivité

Soit les fonctions $f,g,h : A \mapsto \setR$ telles que :

#+BEGIN_CENTER
\(
f \essinferieur g \\ \\
g \essinferieur h
\)
#+END_CENTER

Si on pose :

#+BEGIN_CENTER
\(
Z = \{ x \in A : f(x) \strictsuperieur g(x)\} \\
N = \{ x \in A : g(x) \strictsuperieur h(x)\}
\)
#+END_CENTER

on a $\mu(Z) = \mu(N) = 0$. Comme une union finie d'ensembles de mesure nulle est de mesure nulle, on a $\mu(N \cup Z) = 0$. Pour tout $A \setminus (N \cup Z)$, on a $f(x) \le g(x)$ et $g(x) \le h(x)$. On en déduit que $f(x) \le h(x)$. Notre $f$ est donc inférieure à $h$ sur $A$ sauf sur l'ensemble de mesure nulle $N \cup Z$. On en conclut que la fonction étagée $f$ est essentiellement inférieure à $h$ :

$$f \essinferieur h$$


** Conservation sous l'addition

Supposons que $f \essinferieur g$ et que $u \essinferieur v$. Les ensembles :

#+BEGIN_CENTER
\(
Z = \{ x \in A : f(x) \strictsuperieur g(x)\} \\
N = \{ x \in A : u(x) \strictsuperieur v(x)\}
\)
#+END_CENTER

sont de mesure nulle. Leur union est donc également de mesure nulle et on a bien entendu $f(x) + u(x) \le g(x) + v(x)$ sur $A \setminus (Z \cup N)$ c'est-à-dire sur une sous-ensemble essentiel de $A$. On en conclut que :

$$f + u \essinferieur g + v$$


** Conservation sous la soustraction

Supposons que $f \essinferieur g$ et que $u \esssuperieur v$. Les ensembles :

#+BEGIN_CENTER
\(
Z = \{ x \in A : f(x) \strictsuperieur g(x)\} \\
N = \{ x \in A : u(x) \strictinferieur v(x)\}
\)
#+END_CENTER

sont de mesure nulle. Leur union est donc également de mesure nulle et on a bien entendu $f(x) - u(x) \le g(x) - v(x)$ sur $A \setminus (Z \cup N)$ c'est-à-dire sur une sous-ensemble essentiel de $A$. On en conclut que :

$$f - u \essinferieur g - v$$


** Fonctions max et min


*** Max

Supposons que $f,g \essinferieur h$. Les ensembles :

#+BEGIN_CENTER
\(
Z = \{ x \in A : f(x) \strictsuperieur h(x)\} \\
N = \{ x \in A : g(x) \strictsuperieur h(x)\}
\)
#+END_CENTER

sont de mesure nulle. Leur union est donc également de mesure nulle et on a bien entendu $\max\{f(x) , g(x)\} \le h(x)$ sur $A \setminus (Z \cup N)$ c'est-à-dire sur une sous-ensemble essentiel de $A$. On en conclut que :

$$\max\{f,g\} \essinferieur h$$


*** Min

Supposons que $f,g \esssuperieur h$. Les ensembles :

#+BEGIN_CENTER
\(
Z = \{ x \in A : f(x) \strictinferieur h(x)\} \\
N = \{ x \in A : g(x) \strictinferieur h(x)\}
\)
#+END_CENTER

sont de mesure nulle. Leur union est donc également de mesure nulle et on a bien entendu $\min\{f(x) , g(x)\} \ge h(x)$ sur $A \setminus (Z \cup N)$ c'est-à-dire sur une sous-ensemble essentiel de $A$. On en conclut que :

$$\min\{f,g\} \esssuperieur h$$


** Egalité

On dit que $f$ est essentiellement égale à $g$, et on le note :

$$f \essegal g$$

si et seulement si $f \essinferieur g$ et $f \esssuperieur g$. Les ensembles :

#+BEGIN_CENTER
\(
Z = \{ x \in A : f(x) \strictinferieur g(x)\} \\
N = \{ x \in A : f(x) \strictsuperieur g(x)\}
\)
#+END_CENTER

sont alors de mesure nulle. Donc, l'ensemble :

$$D = \{ x \in A : f(x) \ne g(x)\} = Z \cup N$$

est également de mesure nulle.


* Extrema essentiels

#+TOC: headlines 1 local

\label{chap:essextr}


** Dépendances

  - Chapitre \ref{chap:mesure} : Les mesures


** Bornes

Soit la fonction mesurable $f : A \mapsto \setR$.


*** Supérieure

On dit que $f$ est {\em essentiellement} inférieure au réel $\sigma \in \setR$, et on le note :

$$f \essinferieur \sigma$$

si on peut trouver un sous-ensemble essentiel $S$ de $A$ tel que $f(x) \le \sigma$ en tout point $x \in S$. On a donc :

$$\mu(\{ x \in A : f(x) \strictsuperieur \sigma \}) = 0$$

On dit aussi que $f$ est essentiellement majorée par $\sigma$.


*** Inférieure

On dit que $f$ est {\em essentiellement} supérieure au réel $\lambda \in \setR$, et on le note :

$$f \esssuperieur \lambda$$

si on peut trouver un sous-ensemble essentiel $S$ de $A$ tel que $f(x) \ge \lambda$ en tout point $x \in S$. On a donc :

$$\mu(\{ x \in A : f(x) \strictinferieur \lambda \}) = 0$$

On dit aussi que $f$ est essentiellement minorée par $\lambda$.


** Extrema essentiels

Soit une fonction mesurable $f : A \mapsto \setR$. Pour tout $\sigma \in \setR$, notons :

$$\Psi(\sigma) = \{ x \in A : f(x) \strictsuperieur \sigma \}$$

Comme on ne se soucie pas des ensembles de mesure nulle, on peut choisir (si elle existe) une borne supérieure $\sigma \in \setR$ telle que $f \essinferieur \sigma$, ce qui revient à imposer que $\mu(\Psi(\sigma)) = 0$. Notons :

$$\Theta = \{ \sigma \in \setR : f \essinferieur \sigma \} = \{ \sigma \in \setR : \mu(\Psi(\sigma)) = 0 \}$$

La finalité des bornes étant d'encadrer au plus près un ensemble, nous considérons l'infimum (s'il existe) des réels $\sigma$ possédant cette propriété, et nous l'appelons supremum essentiel :

$$\supessentiel_{x \in A} f(x) = \inf \Theta$$

Symétriquement, on note :

$$\Gamma(\lambda) = \{ x \in A : f(x) \strictinferieur \lambda \}$$

pour tout $\lambda \in \setR$ et :

$$\Lambda = \{ \lambda \in \setR : f \esssuperieur \lambda \} = \{ \lambda \in \setR : \mu(\Gamma(\lambda)) = 0 \}$$

Si le supremum de $\Lambda$ existe, on définit alors l'infimum essentiel par :

$$\infessentiel_{x \in A} f(x) = \sup \Lambda$$

Nous disposons donc des bornes :

#+BEGIN_CENTER
\(
\supessentiel_{x \in A} f(x) = \inf \{ \sigma \in \setR : f \essinferieur \sigma \} \\ \\
\infessentiel_{x \in A} f(x) = \sup \{ \lambda \in \setR : f \esssuperieur \lambda \}
\)
#+END_CENTER


*** Notation

On note aussi :

#+BEGIN_CENTER
\(
\supessentiel \{f(x) : x \in A\} = \supessentiel_{x \in A} f(x) \\
\infessentiel \{f(x) : x \in A\} = \infessentiel_{x \in A} f(x)
\)
#+END_CENTER

Au besoin, la mesure $\mu$ utilisée est indiquée par :

#+BEGIN_CENTER
\(
\supessentiel_{x \in A}^\mu f(x) \\ \\
\infessentiel_{x \in A}^\mu f(x)
\)
#+END_CENTER


** Existence et estimation


*** Supremum essentiel

Supposons que $f$ soit essentiellement inférieure (sur $A$) à un certain $\sigma \in \setR$ et que $f$ soit essentiellement supérieure à un certain $\lambda \in \setR$ sur un ensemble $L \subseteq A$ de mesure strictement positive. On a $\sigma \in \Theta \ne \emptyset$. Pour tout $\alpha \in \setR$ tel que $\alpha \ge \sigma$, on a $\Psi(\alpha) \subseteq \Psi(\sigma)$. Comme $\mu(\Psi(\sigma)) = 0$, l'ensemble $\Psi(\alpha)$ est inclus dans un ensemble de mesure nulle. Il est donc lui-même de mesure nulle et $\alpha \in \Theta$. On en conclut que :

$$[\sigma, +\infty[ \ \subseteq \Theta$$

pour tout $\sigma \in \Theta$. Comme $f$ est essentiellement supérieure à $\lambda$ sur $L$, on peut trouver un ensemble de mesure nulle $Z \subseteq L$ tel que :

$$L \setminus Z = \{ x \in L : f(x) \ge \lambda \}$$

Comme $L \setminus Z$ est un sous-ensemble essentiel de $L$, on a $\mu(L \setminus Z) = \mu(L) \strictsuperieur 0$. Posons :

$$C = \{ x \in A : f(x) \ge \lambda \}$$

Comme $L \subseteq A$, on a $L \setminus Z \subseteq C$ et $\mu(C) \ge \mu(L \setminus Z) \strictsuperieur 0$. Soit $\beta \in \setR$ vérifiant $\beta \strictinferieur \lambda$. La condition $f(x) \ge \lambda$ implique que $f(x) \strictsuperieur \beta$. On en déduit que :

$$C \subseteq \{ x \in A : f(x) \strictsuperieur \beta \} = \Psi(\beta)$$

On a alors $\mu(\Psi(\beta)) \ge \mu(C) \strictsuperieur 0$, ce qui implique que $\beta$ ne peut pas appartenir à $\Theta$. Tous les éléments $\theta \in \Theta$ vérifient donc $\theta \ge \lambda$ et :

$$\Theta \subseteq [\lambda, +\infty[$$

Comme $\lambda \le \Theta$, l'ensemble de réels $\Theta$ est non vide et minoré. Il admet donc un infimum :

$$\supessentiel_{x \in A} f(x) = \inf \Theta$$

On se rappelle que l'inclusion $X \subseteq Y$ implique que $\inf X \ge \inf Y$. Comme $\lambda = \inf [\lambda, +\infty[$ et $\sigma = \inf [\sigma, +\infty[$, les inclusions :

$$[\sigma, +\infty[ \ \subseteq \Theta \subseteq [\lambda, +\infty[$$

nous montrent que :

$$\lambda \le \supessentiel_{x \in A} f(x) \le \sigma$$


*** Infimum essentiel

Supposons que $f$ soit essentiellement supérieure (sur $A$) à un certain $\lambda \in \setR$ et que $f$ soit essentiellement inférieure à un certain $\sigma \in \setR$ sur un ensemble $S \subseteq A$ de mesure strictement positive. On a $\lambda \in \Lambda \ne \emptyset$. Pour tout $\alpha \in \setR$ tel que $\alpha \le \lambda$, on a $\Gamma(\alpha) \subseteq \Gamma(\lambda)$. Comme $\mu(\Gamma(\lambda)) = 0$, l'ensemble $\Gamma(\alpha)$ est inclus dans un ensemble de mesure nulle. Il est donc lui-même de mesure nulle et $\alpha \in \Lambda$. On en conclut que :

$$]-\infty, \lambda] \subseteq \Lambda$$

pour tout $\lambda \in \Lambda$. Comme $f$ est essentiellement inférieure à $\sigma$ sur $S$, on peut trouver un ensemble de mesure nulle $Z \subseteq S$ tel que :

$$S \setminus Z = \{ x \in S : f(x) \le \sigma \}$$

Comme $S \setminus Z$ est un sous-ensemble essentiel de $S$, on a $\mu(S \setminus Z) = \mu(S) \strictsuperieur 0$. Posons :

$$C = \{ x \in A : f(x) \le \sigma \}$$

Comme $S \subseteq A$, on a $S \setminus Z \subseteq C$ et $\mu(C) \ge \mu(S \setminus Z) \strictsuperieur 0$. Soit $\beta \in \setR$ vérifiant $\beta \strictsuperieur \sigma$. La condition $f(x) \le \sigma$ implique que $f(x) \strictinferieur \beta$. On en déduit que :

$$C \subseteq \{ x \in A : f(x) \strictinferieur \beta \} = \Gamma(\beta)$$

On a alors $\mu(\Gamma(\beta)) \ge \mu(C) \strictsuperieur 0$, ce qui implique que $\beta$ ne peut pas appartenir à $\Lambda$. Tous les éléments $\gamma \in \Lambda$ vérifient donc $\gamma \le \sigma$ et :

$$\Theta \subseteq \ ]-\infty, \sigma]$$

Comme $\sigma \ge \Lambda$, l'ensemble de réels non vide $\Lambda$ est majoré. Il admet donc un supremum :

$$\infessentiel_{x \in A} f(x) = \sup \Lambda$$

On se rappelle que l'inclusion $X \subseteq Y$ implique que $\sup X \le \sup Y$. Comme $\lambda = \sup \ ]-\infty, \lambda]$ et $\sigma = \sup \ ]-\infty, \sigma]$, les inclusions :

$$]-\infty, \lambda] \ \subseteq \Theta \subseteq \ ]-\infty, \sigma]$$

nous montrent que :

$$\lambda \le \infessentiel_{x \in A} f(x) \le \sigma$$


** Intersection

Supposons que $A$ soit de mesure strictement positive et que $\Theta \cap \Lambda \ne \emptyset$. Pour tout $\alpha \in \setR$, posons :

$$\Xi(\alpha) = \{ x \in A : f(x) = \alpha \}$$

et :

$$\Upsilon(\alpha) = \{ x \in A : f(x) \ne \alpha \}$$

Il est clair que :

$$A = \Xi(\alpha) \cup \Upsilon(\alpha)$$

Comme imposer la différence revient à imposer soit la supériorité soit l'infériorité stricte, on a :

$$\Upsilon(\alpha) = \Psi(\alpha) \cup \Gamma(\alpha)$$

Soit à présent $\alpha \in \Theta \cap \Lambda$. Comme $\mu(\Psi(\alpha)) = \mu(\Gamma(\alpha)) = 0$, leur union est également de mesure nulle :

$$\mu(\Upsilon(\alpha)) = 0$$

Si l'intersection $\Theta \cap \Lambda$ n'est pas vide, la fonction $f$ est donc essentiellement constante sur $A$ et $\Xi(\alpha) = A \setminus \Upsilon(\alpha)$ est un sous-ensemble essentiel de $A$. On a donc $\mu(\Xi(\alpha)) = \mu(A) \strictsuperieur 0$. Soit à présent $\beta \in \setR$ et supposons que $\beta \ne \alpha$. Si $f(x) = \beta$, on a forcément $f(x) \ne \alpha$, donc :

$$\Xi(\beta) = \{ x \in A : f(x) = \beta \} \subseteq \{ x \in A : f(x) \ne \alpha \}$$

L'ensemble $\Xi(\beta)$ étant inclus dans un ensemble de mesure nulle, on doit avoir $\mu(\Xi(\beta)) = 0$. Comme $\mu(\Xi(\alpha)) \strictsuperieur 0$ pour tout $\alpha \in \Theta \cap \Lambda$, $\beta$ ne peut pas appartenir à $\Theta \cap \Lambda$. On en conclut que l'intersection vérifie soit :

$$\Theta \cap \Lambda = \emptyset$$

soit :

$$\Theta \cap \Lambda = \{ \alpha \}$$

pour un certain $\alpha \in \setR$.


*** Extrema

Supposons que $f$ soit essentiellement inférieure à $\sigma$ et essentiellement supérieure à $\lambda$ sur $A$ qui est de mesure strictement positive. On en déduit que les supremum et infimum essentiels existent :

#+BEGIN_CENTER
\(
S = \supessentiel \{ f(x) : x \in A \} \\
I = \infessentiel \{ f(x) : x \in A \}
\)
#+END_CENTER

et que $\lambda \le \{ S,I \} \le \sigma$. Supposons que $S \strictinferieur I$ et posons $\delta = I - S \strictsuperieur 0$. Soit le réel strictement positif $\epsilon = \delta / 4$. Comme l'infimum est dans l'adhérence, on peut trouver un $\alpha \in \Theta$ tel que $\abs{\alpha - S} \le \epsilon$, d'où $\alpha \le S + \epsilon$. On a alors :

$$[\alpha, +\infty[ \ \subseteq \Theta$$

Comme le supremum est dans l'adhérence, on peut trouver un $\beta \in \Lambda$ tel que $\abs{I - \beta} \le \epsilon$, d'où $\beta \ge I - \epsilon$. On a alors :

$$]-\infty, \beta] \subseteq \Lambda$$

On voit que :

\begin{align}
S + \epsilon &= S + \frac{\delta}{4} \\
I - \epsilon &= S + \delta - \frac{\delta}{4} = S  + \frac{3 \delta}{4}
\end{align}

On a donc :

$$\alpha \le S + \epsilon \strictinferieur I - \epsilon \le \beta$$

et $\alpha \strictinferieur \beta$. On a aussi :

$$[\alpha,\beta] = \ ]-\infty, \beta] \cap [\alpha, +\infty[ \ \subseteq \Theta \cap \Lambda$$

Donc $\alpha,\beta \in \Theta \cap \Lambda$ avec $\alpha \ne \beta$ ce qui impossible. Notre hypothèse est donc fausse et $I \le S$, c'est-à-dire :

$$\infessentiel_{x \in A} f(x) \le \supessentiel_{x \in A} f(x)$$


** Ordre

Soit les fonctions $f,g : A \mapsto \setR$ telles que $f \essinferieur g$.


*** Supremum essentiel

On a bien entendu :

$$f \essinferieur g \essinferieur \supessentiel_{x \in A} g(x)$$

On en déduit que :

$$\supessentiel_{x \in A} f(x) \le \supessentiel_{x \in A} g(x)$$


*** Infimum essentiel

On a bien entendu :

$$\infessentiel_{x \in A} f(x) \essinferieur f \essinferieur g$$

On en déduit que :

$$\infessentiel_{x \in A} f(x) \le \infessentiel_{x \in A} g(x)$$


** Addition

Soit les fonctions $f,g : A \mapsto \setR$.


*** Supremum essentiel

On sait que :

#+BEGIN_CENTER
\(
f \essinferieur \sigma = \supessentiel \{ f(x) : x \in A \} \\
g \essinferieur \tau = \supessentiel \{ g(x) : x \in A \}
\)
#+END_CENTER

On a donc :

$$f + g \essinferieur \sigma + \tau$$

On en conclut que :

$$\supessentiel_{x \in A} [f(x) + g(x)] \le \supessentiel_{x \in A} f(x) + \supessentiel_{x \in A} g(x)$$


*** Infimum essentiel

On sait que :

#+BEGIN_CENTER
\(
f \esssuperieur \lambda = \infessentiel \{ f(x) : x \in A \} \\
g \esssuperieur \gamma = \infessentiel \{ g(x) : x \in A \}
\)
#+END_CENTER

On a donc :

$$f + g \esssuperieur \lambda + \gamma$$

On en conclut que :

$$\infessentiel_{x \in A} [f(x) + g(x)] \ge \infessentiel_{x \in A} f(x) + \infessentiel_{x \in A} g(x)$$
