(setq torus-wheel (quote
((("racine"
   (("infoman"
     (("/home/david/racine/README.org" . 1387))
     0 . 1)
    ("organ"
     (("/home/david/racine/organ/orgmode/education.org" . 141))
     0 . 1))
   1 . 2)
  ("site"
   (("root"
     (("/home/david/racine/site/orgmode/README.org" . 94))
     0 . 1)
    ("include"
     (("/home/david/racine/site/orgmode/include/commandes-tex.org" . 2913))
     0 . 1)
    ("grimoire"
     (("/home/david/racine/site/orgmode/grimoire/index.org" . 1399)
      ("/home/david/racine/site/orgmode/grimoire/divers-01-unite.org" . 13104)
      ("/home/david/racine/site/orgmode/grimoire/test-titres.org" . 319))
     0 . 3)
    ("nature"
     (("/home/david/racine/site/orgmode/grimoire/nature-01-permaculture.org" . 327)
      ("/home/david/racine/site/orgmode/grimoire/nature-02-ecoconstruction.org" . 1037))
     1 . 2)
    ("meta"
     (("/home/david/racine/site/orgmode/grimoire/meta-01-metaphysics.org" . 31503)
      ("/home/david/racine/site/orgmode/grimoire/meta-02-esoterisme.org" . 6384)
      ("/home/david/racine/site/orgmode/grimoire/meta-03-spiritus.org" . 1836))
     0 . 3)
    ("bien etre"
     (("/home/david/racine/site/orgmode/grimoire/bienetre-01-enpratique.org" . 7435)
      ("/home/david/racine/site/orgmode/grimoire/bienetre-03-sport.org" . 1)
      ("/home/david/racine/site/orgmode/grimoire/bienetre-04-yoga.org" . 8007)
      ("/home/david/racine/site/orgmode/grimoire/bienetre-05-qigong.org" . 34656)
      ("/home/david/racine/site/orgmode/grimoire/bienetre-06-vision.org" . 10173))
     2 . 5)
    ("artisan"
     (("/home/david/racine/site/orgmode/grimoire/artisanat-01-noeuds.org" . 1))
     0 . 1)
    ("litera"
     (("/home/david/racine/site/orgmode/grimoire/litera-01-rimailleur.org" . 56560)
      ("/home/david/racine/site/orgmode/grimoire/litera-02-styleau.org" . 91438)
      ("/home/david/racine/site/orgmode/grimoire/litera-03-theatre.org" . 1)
      ("/home/david/racine/site/orgmode/grimoire/litera-04-plumier.org" . 8870))
     3 . 4)
    ("pictura"
     (("/home/david/racine/site/orgmode/grimoire/pictura-01-geometrie.org" . 2743)
      ("/home/david/racine/site/orgmode/grimoire/pictura-02-regle-compas.org" . 1)
      ("/home/david/racine/site/orgmode/grimoire/pictura-03-croquis.org" . 1050))
     1 . 3)
    ("musica"
     (("/home/david/racine/site/orgmode/grimoire/musica-01-monocorde.org" . 29447)
      ("/home/david/racine/site/orgmode/grimoire/musica-02-metronome.org" . 16271)
      ("/home/david/racine/site/orgmode/grimoire/musica-03-luth.org" . 26872)
      ("/home/david/racine/site/orgmode/grimoire/musica-04-clavier.org" . 58025)
      ("/home/david/racine/site/orgmode/grimoire/musica-05-tablature.org" . 18911)
      ("/home/david/racine/site/orgmode/grimoire/musica-06-partition.org" . 37688)
      ("/home/david/racine/site/orgmode/grimoire/musica-07-concert.org" . 5032)
      ("/home/david/racine/site/orgmode/grimoire/musica-08-clechant.org" . 16655)
      ("/home/david/racine/site/orgmode/grimoire/musica-09-chamuse.org" . 21529)
      ("/home/david/racine/site/orgmode/grimoire/musica-10-coda.org" . 14212))
     2 . 10)
    ("matemat"
     (("/home/david/racine/site/orgmode/grimoire/matemat-06-vecteur.org" . 2121)
      ("/home/david/racine/site/orgmode/grimoire/matemat-09-analyse.org" . 1))
     0 . 2)
    ("physics"
     (("/home/david/racine/site/orgmode/grimoire/physics-01-mecanic.org" . 12897))
     0 . 1)
    ("multics"
     (("/home/david/racine/site/orgmode/grimoire/ordina-07-script.org" . 250)
      ("/home/david/racine/site/orgmode/grimoire/ordina-01-multics.org" . 42660)
      ("/home/david/racine/site/orgmode/grimoire/ordina-02-bsd.org" . 2177)
      ("/home/david/racine/site/orgmode/grimoire/ordina-03-linux.org" . 2143))
     1 . 4)
    ("referen"
     (("/home/david/racine/site/orgmode/grimoire/referen-01-signets.org" . 1124)
      ("/home/david/racine/site/orgmode/grimoire/referen-02-livre.org" . 1))
     0 . 2)
    ("html doc"
     (("/home/david/racine/site/entites-html.org" . 1401))
     0 . 1)
    ("poesie"
     (("/home/david/racine/site/orgmode/litera/aubes.org" . 445)
      ("/home/david/racine/site/orgmode/litera/carnaval.org" . 452)
      ("/home/david/racine/site/orgmode/litera/eclairci.org" . 812)
      ("/home/david/racine/site/orgmode/litera/songes.org" . 448)
      ("/home/david/racine/site/orgmode/litera/cendres.org" . 839))
     4 . 5)
    ("agora"
     (("/home/david/racine/site/orgmode/grimoire/agora-01-constitution.org" . 1811)
      ("/home/david/racine/site/orgmode/grimoire/agora-02-economie.org" . 12109))
     1 . 2))
   4 . 17)
  ("plain"
   (("maison"
     (("/home/david/racine/plain/maison/valise.org" . 966))
     0 . 1))
   0 . 1)
  ("emacs-lisp"
   (("duo"
     (("/home/david/racine/public/duo/README.org" . 4125)
      ("/home/david/racine/public/duo/duo.el" . 3496)
      ("/home/david/racine/public/duo/duo-common.el" . 37347)
      ("/home/david/racine/public/duo/duo-symbol.el" . 15753)
      ("/home/david/racine/public/duo/duo-referen.el" . 13998)
      ("/home/david/racine/public/duo/duo-return.el" . 12006)
      ("/home/david/racine/public/duo/recipes/melpa/duo.melpa" . 29))
     2 . 7)
    ("snippets"
     (("/home/david/racine/snippet/elisp.snip" . 33425)
      ("/home/david/racine/snippet/emacs.snip" . 1)
      ("/home/david/racine/snippet/makefile.snip" . 22)
      ("/home/david/racine/snippet/git.snip" . 759)
      ("/home/david/racine/snippet/shell.snip" . 274))
     1 . 5)
    ("torus"
     (("/home/david/racine/public/torus/README.org" . 7524)
      ("/home/david/racine/public/torus/torus.el" . 84437)
      ("/home/david/racine/public/torus/torus.el" . 151755)
      ("/home/david/racine/public/torus/torus.el" . 57999)
      ("/home/david/racine/public/torus/recipes/melpa/torus.melpa" . 1))
     3 . 5)
    ("emacs"
     (("/home/david/racine/config/edit/emacs/emacs.el" . 113)
      ("/home/david/racine/config/edit/emacs/paquets.el" . 2587)
      ("/home/david/racine/config/edit/emacs/orgconfig.el" . 89)
      ("/home/david/racine/config/edit/emacs/configuration.org" . 34292)
      ("/home/david/racine/config/edit/emacs/fonction.el" . 23))
     3 . 5)
    ("emacs-test"
     (("/home/david/racine/test/emacs/init.el" . 1310))
     0 . 1))
   3 . 5)
  ("public"
   (("configuration"
     (("/home/david/racine/public/configuration/README.org" . 2477))
     0 . 1))
   0 . 1))
 1 . 5)
))

(setq torus-helix (quote
(((("emacs-lisp" . "duo")
   "/home/david/racine/public/duo/README.org" . 4125)
  (("emacs-lisp" . "duo")
   "/home/david/racine/public/duo/duo-common.el" . 37347)
  (("emacs-lisp" . "duo")
   "/home/david/racine/public/duo/duo-referen.el" . 13998)
  (("emacs-lisp" . "duo")
   "/home/david/racine/public/duo/duo-return.el" . 12006)
  (("emacs-lisp" . "duo")
   "/home/david/racine/public/duo/duo-symbol.el" . 15753)
  (("emacs-lisp" . "duo")
   "/home/david/racine/public/duo/duo.el" . 3496)
  (("emacs-lisp" . "duo")
   "/home/david/racine/public/duo/recipes/melpa/duo.melpa" . 29)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/configuration.org" . 34292)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/emacs.el" . 113)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/fonction.el" . 23)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/orgconfig.el" . 89)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/paquets.el" . 2587)
  (("emacs-lisp" . "emacs-test")
   "/home/david/racine/test/emacs/init.el" . 1310)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/elisp.snip" . 33425)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/emacs.snip" . 1)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/git.snip" . 759)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/makefile.snip" . 22)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/shell.snip" . 274)
  (("emacs-lisp" . "torus")
   "/home/david/racine/public/torus/README.org" . 7524)
  (("emacs-lisp" . "torus")
   "/home/david/racine/public/torus/recipes/melpa/torus.melpa" . 1)
  (("emacs-lisp" . "torus")
   "/home/david/racine/public/torus/torus.el" . 84437)
  (("emacs-lisp" . "torus")
   "/home/david/racine/public/torus/torus.el" . 151755)
  (("emacs-lisp" . "torus")
   "/home/david/racine/public/torus/torus.el" . 57999)
  (("plain" . "maison")
   "/home/david/racine/plain/maison/valise.org" . 966)
  (("public" . "configuration")
   "/home/david/racine/public/configuration/README.org" . 2477)
  (("racine" . "infoman")
   "/home/david/racine/README.org" . 1387)
  (("racine" . "organ")
   "/home/david/racine/organ/orgmode/education.org" . 141)
  (("site" . "agora")
   "/home/david/racine/site/orgmode/grimoire/agora-01-constitution.org" . 1811)
  (("site" . "agora")
   "/home/david/racine/site/orgmode/grimoire/agora-02-economie.org" . 12109)
  (("site" . "artisan")
   "/home/david/racine/site/orgmode/grimoire/artisanat-01-noeuds.org" . 1)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-01-enpratique.org" . 7435)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-03-sport.org" . 1)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-04-yoga.org" . 8007)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-05-qigong.org" . 34656)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-06-vision.org" . 10173)
  (("site" . "grimoire")
   "/home/david/racine/site/orgmode/grimoire/divers-01-unite.org" . 13104)
  (("site" . "grimoire")
   "/home/david/racine/site/orgmode/grimoire/index.org" . 1399)
  (("site" . "grimoire")
   "/home/david/racine/site/orgmode/grimoire/test-titres.org" . 319)
  (("site" . "html doc")
   "/home/david/racine/site/entites-html.org" . 1401)
  (("site" . "include")
   "/home/david/racine/site/orgmode/include/commandes-tex.org" . 2913)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-01-rimailleur.org" . 56560)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-02-styleau.org" . 91438)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-03-theatre.org" . 1)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-04-plumier.org" . 8870)
  (("site" . "matemat")
   "/home/david/racine/site/orgmode/grimoire/matemat-06-vecteur.org" . 2121)
  (("site" . "matemat")
   "/home/david/racine/site/orgmode/grimoire/matemat-09-analyse.org" . 1)
  (("site" . "meta")
   "/home/david/racine/site/orgmode/grimoire/meta-01-metaphysics.org" . 31503)
  (("site" . "meta")
   "/home/david/racine/site/orgmode/grimoire/meta-02-esoterisme.org" . 6384)
  (("site" . "meta")
   "/home/david/racine/site/orgmode/grimoire/meta-03-spiritus.org" . 1836)
  (("site" . "multics")
   "/home/david/racine/site/orgmode/grimoire/ordina-01-multics.org" . 42660)
  (("site" . "multics")
   "/home/david/racine/site/orgmode/grimoire/ordina-02-bsd.org" . 2177)
  (("site" . "multics")
   "/home/david/racine/site/orgmode/grimoire/ordina-03-linux.org" . 2143)
  (("site" . "multics")
   "/home/david/racine/site/orgmode/grimoire/ordina-07-script.org" . 250)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-01-monocorde.org" . 29447)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-02-metronome.org" . 16271)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-03-luth.org" . 26872)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-04-clavier.org" . 58025)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-05-tablature.org" . 18911)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-06-partition.org" . 37688)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-07-concert.org" . 5032)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-08-clechant.org" . 16655)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-09-chamuse.org" . 21529)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-10-coda.org" . 14212)
  (("site" . "nature")
   "/home/david/racine/site/orgmode/grimoire/nature-01-permaculture.org" . 327)
  (("site" . "nature")
   "/home/david/racine/site/orgmode/grimoire/nature-02-ecoconstruction.org" . 1037)
  (("site" . "physics")
   "/home/david/racine/site/orgmode/grimoire/physics-01-mecanic.org" . 12897)
  (("site" . "pictura")
   "/home/david/racine/site/orgmode/grimoire/pictura-01-geometrie.org" . 2743)
  (("site" . "pictura")
   "/home/david/racine/site/orgmode/grimoire/pictura-02-regle-compas.org" . 1)
  (("site" . "pictura")
   "/home/david/racine/site/orgmode/grimoire/pictura-03-croquis.org" . 1050)
  (("site" . "poesie")
   "/home/david/racine/site/orgmode/litera/aubes.org" . 445)
  (("site" . "poesie")
   "/home/david/racine/site/orgmode/litera/carnaval.org" . 452)
  (("site" . "poesie")
   "/home/david/racine/site/orgmode/litera/cendres.org" . 839)
  (("site" . "poesie")
   "/home/david/racine/site/orgmode/litera/eclairci.org" . 812)
  (("site" . "poesie")
   "/home/david/racine/site/orgmode/litera/songes.org" . 448)
  (("site" . "referen")
   "/home/david/racine/site/orgmode/grimoire/referen-01-signets.org" . 1124)
  (("site" . "referen")
   "/home/david/racine/site/orgmode/grimoire/referen-02-livre.org" . 1)
  (("site" . "root")
   "/home/david/racine/site/orgmode/README.org" . 94)))
))

(setq torus-grid (quote
((("emacs-lisp" . "duo")
  ("emacs-lisp" . "emacs")
  ("emacs-lisp" . "emacs-test")
  ("emacs-lisp" . "snippets")
  ("emacs-lisp" . "torus")
  ("plain" . "maison")
  ("public" . "configuration")
  ("racine" . "infoman")
  ("racine" . "organ")
  ("site" . "agora")
  ("site" . "artisan")
  ("site" . "bien etre")
  ("site" . "grimoire")
  ("site" . "html doc")
  ("site" . "include")
  ("site" . "litera")
  ("site" . "matemat")
  ("site" . "meta")
  ("site" . "multics")
  ("site" . "musica")
  ("site" . "nature")
  ("site" . "physics")
  ("site" . "pictura")
  ("site" . "poesie")
  ("site" . "referen")
  ("site" . "root")))
))

(setq torus-history (quote
(((("site" . "meta")
   "/home/david/racine/site/orgmode/grimoire/meta-01-metaphysics.org" . 31503)
  (("site" . "grimoire")
   "/home/david/racine/site/orgmode/grimoire/index.org" . 1399)
  (("site" . "meta")
   "/home/david/racine/site/orgmode/grimoire/meta-02-esoterisme.org" . 6384)
  (("site" . "meta")
   "/home/david/racine/site/orgmode/grimoire/meta-03-spiritus.org" . 1836)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-03-luth.org" . 26872)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-04-clavier.org" . 58025)
  (("site" . "multics")
   "/home/david/racine/site/orgmode/grimoire/ordina-01-multics.org" . 42660)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/configuration.org" . 34292)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-04-yoga.org" . 8007)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-09-chamuse.org" . 21529)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-04-plumier.org" . 8870)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-06-partition.org" . 37688)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-08-clechant.org" . 16655)
  (("site" . "multics")
   "/home/david/racine/site/orgmode/grimoire/ordina-02-bsd.org" . 2177)
  (("site" . "referen")
   "/home/david/racine/site/orgmode/grimoire/referen-01-signets.org" . 1124)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/fonction.el" . 23)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-01-rimailleur.org" . 56560)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-01-enpratique.org" . 7435)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-01-monocorde.org" . 29447)
  (("racine" . "organ")
   "/home/david/racine/organ/orgmode/education.org" . 141)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/emacs.snip" . 1)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-05-tablature.org" . 18911)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-05-qigong.org" . 34656)
  (("site" . "nature")
   "/home/david/racine/site/orgmode/grimoire/nature-02-ecoconstruction.org" . 1037)
  (("site" . "nature")
   "/home/david/racine/site/orgmode/grimoire/nature-01-permaculture.org" . 327)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/git.snip" . 759)
  (("site" . "pictura")
   "/home/david/racine/site/orgmode/grimoire/pictura-02-regle-compas.org" . 1)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-02-metronome.org" . 16271)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-07-concert.org" . 5032)
  (("racine" . "infoman")
   "/home/david/racine/README.org" . 1387)
  (("public" . "configuration")
   "/home/david/racine/public/configuration/README.org" . 2477)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-02-styleau.org" . 91438)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-03-sport.org" . 1)
  (("site" . "bien etre")
   "/home/david/racine/site/orgmode/grimoire/bienetre-06-vision.org" . 10173)
  (("site" . "pictura")
   "/home/david/racine/site/orgmode/grimoire/pictura-01-geometrie.org" . 2743)
  (("site" . "agora")
   "/home/david/racine/site/orgmode/grimoire/agora-02-economie.org" . 12109)
  (("site" . "agora")
   "/home/david/racine/site/orgmode/grimoire/agora-01-constitution.org" . 1811)
  (("site" . "musica")
   "/home/david/racine/site/orgmode/grimoire/musica-10-coda.org" . 14212)
  (("site" . "html doc")
   "/home/david/racine/site/entites-html.org" . 1401)
  (("site" . "root")
   "/home/david/racine/site/orgmode/README.org" . 94)
  (("site" . "grimoire")
   "/home/david/racine/site/orgmode/grimoire/divers-01-unite.org" . 13104)
  (("site" . "litera")
   "/home/david/racine/site/orgmode/grimoire/litera-03-theatre.org" . 1)
  (("site" . "matemat")
   "/home/david/racine/site/orgmode/grimoire/matemat-06-vecteur.org" . 2121)
  (("site" . "matemat")
   "/home/david/racine/site/orgmode/grimoire/matemat-09-analyse.org" . 1)
  (("site" . "grimoire")
   "/home/david/racine/site/orgmode/grimoire/test-titres.org" . 319)
  (("site" . "artisan")
   "/home/david/racine/site/orgmode/grimoire/artisanat-01-noeuds.org" . 1)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/makefile.snip" . 22)
  (("emacs-lisp" . "emacs")
   "/home/david/racine/config/edit/emacs/paquets.el" . 2587)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/elisp.snip" . 33425)
  (("emacs-lisp" . "snippets")
   "/home/david/racine/snippet/shell.snip" . 274)))
))

(setq torus-aliases (quote
((((("emacs-lisp" . "torus")
    "/home/david/racine/public/torus/README.org" . 7524)
   . "README.org")
  ((("emacs-lisp" . "torus")
    "/home/david/racine/public/torus/torus.el" . 84437)
   . "torus-1")
  ((("emacs-lisp" . "torus")
    "/home/david/racine/public/torus/torus.el" . 151755)
   . "torus-2")
  ((("emacs-lisp" . "torus")
    "/home/david/racine/public/torus/torus.el" . 57999)
   . "torus-3")
  ((("emacs-lisp" . "torus")
    "/home/david/racine/public/torus/torus.el" . 116937)
   . "torus-3")))
))

(setq torus-user-input-history (quote
("torus-2" "/home/david/racine/site/orgmode/grimoire/meta-01-metaphysics.org" "(\"/home/david/racine/site/orgmode/grimoire/meta-03-spiritus.org\" . 68)" "(\"/home/david/racine/site/orgmode/grimoire/meta-02-esoterisme.org\" . 52)" "(\"/home/david/racine/site/orgmode/grimoire/meta-01-metaphysics.org\" . 70)" "(\"/home/david/racine/site/orgmode/grimoire/meta-03-spiritus.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/meta-01-metaphysics.org\" . 1)" "auto" "(\"/home/david/racine/site/orgmode/grimoire/nature-02-ecoconstruction.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/nature-01-permaculture.org\" . 327)" "nature" "(\"/home/david/racine/organ/orgmode/education.org\" . 1)" "organ" "(\"/home/david/racine/site/orgmode/grimoire/musica-10-coda.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-09-chamuse.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-08-clechant.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-07-concert.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-06-partition.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-05-tablature.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-04-clavier.org\" . 445)" "/home/david/racine/plugin/data/torus/dernier.el" "(\"/home/david/racine/site/orgmode/grimoire/musica-09-coda.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-08-chamuse.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-07-clechant.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-06-concert.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-05-partition.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-04-clavier.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-03-luth.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-08-coda.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-05-concert.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-04-partition.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/litera-04-plumier.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-08-coda.org\" . 458)" "(\"/home/david/racine/site/orgmode/grimoire/musica-07-chamuse.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-02-metronome.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-01-monocorde.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/test-titres.org\" . 1)" "(\"/home/david/racine/snippet/emacs.snip\" . 1)" "/home/david/racine/plugin/data/torus/auto.el" "(\"/home/david/racine/site/orgmode/grimoire/musica-07-coda.org\" . 617)" "(\"/home/david/racine/site/orgmode/grimoire/musica-06-clechant.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-05-tablature.org\" . 72888)" "(\"/home/david/racine/site/orgmode/grimoire/musica-04-concert.org\" . 27687)" "(\"/home/david/racine/site/orgmode/grimoire/musica-03-clavier.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-02-partition.org\" . 1)" "(\"/home/david/racine/site/orgmode/grimoire/musica-01-monocorde.org\" . 447)" "musica" "(\"/home/david/racine/site/orgmode/grimoire/litera-03-theatre.org\" . 1)" "/home/david/racine/site/orgmode/grimoire/litera-01-rimailleur.org" "(\"/home/david/racine/site/orgmode/grimoire/agora-02-economie.org\" . 1)" "(\"/home/david/racine/plain/maison/valise.org\" . 1)")
))

(setq torus-split-layout (quote
(((("emacs-lisp" . "duo")
   . 109)
  (("emacs-lisp" . "emacs")
   . 109)
  (("emacs-lisp" . "snippets")
   . 111)
  (("emacs-lisp" . "torus")
   . 109)
  (("site" . "multics")
   . 109)))
))

(setq torus-line-col (quote
(((("/home/david/racine/README.org" . 1387)
   95 . 7)
  (("/home/david/racine/config/edit/emacs/color/ornuit-gui-theme.el" . 1538)
   54 . 36)
  (("/home/david/racine/config/edit/emacs/configuration.org" . 34292)
   1620 . 69)
  (("/home/david/racine/config/edit/emacs/emacs.el" . 113)
   8 . 0)
  (("/home/david/racine/config/edit/emacs/fonction.el" . 23)
   2 . 0)
  (("/home/david/racine/config/edit/emacs/orgconfig.el" . 89)
   6 . 0)
  (("/home/david/racine/config/edit/emacs/paquets.el" . 2587)
   71 . 26)
  (("/home/david/racine/organ/orgmode/education.org" . 141)
   13 . 2)
  (("/home/david/racine/plain/alimen/courses.org" . 528)
   69 . 11)
  (("/home/david/racine/plain/alimen/recettes.org" . 1680)
   142 . 41)
  (("/home/david/racine/plain/alimen/the.org" . 120)
   8 . 0)
  (("/home/david/racine/plain/artisan/litera.org" . 12824)
   668 . 0)
  (("/home/david/racine/plain/echange/change.org" . 1)
   1 . 0)
  (("/home/david/racine/plain/maison/consommation.org" . 763)
   18 . 24)
  (("/home/david/racine/plain/maison/rangement.org" . 860)
   19 . 48)
  (("/home/david/racine/plain/maison/valise.org" . 966)
   47 . 17)
  (("/home/david/racine/plain/orgdir/education.org" . 1460)
   109 . 36)
  (("/home/david/racine/plain/science/histoire.org" . 1)
   1 . 0)
  (("/home/david/racine/plain/spiritus/spiritus.org" . 1)
   1 . 0)
  (("/home/david/racine/plain/text/contact.org" . 1840)
   93 . 22)
  (("/home/david/racine/plain/text/cronos.org" . 273)
   17 . 2)
  (("/home/david/racine/plain/text/jeux.org" . 28167)
   751 . 34)
  (("/home/david/racine/plain/text/personne.org" . 30592)
   583 . 24)
  (("/home/david/racine/public/configuration/README.org" . 2477)
   107 . 24)
  (("/home/david/racine/public/duo/README.org" . 4125)
   184 . 0)
  (("/home/david/racine/public/duo/duo-common.el" . 37347)
   1141 . 17)
  (("/home/david/racine/public/duo/duo-referen.el" . 13998)
   441 . 22)
  (("/home/david/racine/public/duo/duo-return.el" . 12006)
   345 . 11)
  (("/home/david/racine/public/duo/duo-symbol.el" . 15753)
   475 . 33)
  (("/home/david/racine/public/duo/duo.el" . 3496)
   92 . 19)
  (("/home/david/racine/public/duo/recipes/melpa/duo.melpa" . 29)
   2 . 4)
  (("/home/david/racine/public/torus/README.org" . 7524)
   276 . 20)
  (("/home/david/racine/public/torus/recipes/melpa/torus.melpa" . 1)
   1 . 0)
  (("/home/david/racine/public/torus/torus.el" . 84437)
   2209 . 64)
  (("/home/david/racine/public/torus/torus.el" . 151755)
   3897 . 7)
  (("/home/david/racine/public/torus/torus.el" . 112213)
   2846 . 14)
  (("/home/david/racine/public/torus/torus.el" . 112408)
   2850 . 14)
  (("/home/david/racine/public/torus/torus.el" . 57999)
   1590 . 0)
  (("/home/david/racine/public/torus/torus.el" . 116937)
   2952 . 14)
  (("/home/david/racine/site/entites-html.org" . 1401)
   72 . 0)
  (("/home/david/racine/site/orgmode/README.org" . 94)
   14 . 0)
  (("/home/david/racine/site/orgmode/grimoire/agora-01-constitution.org" . 1811)
   79 . 22)
  (("/home/david/racine/site/orgmode/grimoire/agora-02-economie.org" . 12109)
   455 . 23)
  (("/home/david/racine/site/orgmode/grimoire/artisanat-01-noeuds.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/bienetre-01-enpratique.org" . 7435)
   311 . 0)
  (("/home/david/racine/site/orgmode/grimoire/bienetre-01-enpratique.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/bienetre-03-sport.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/bienetre-03-sport.org" . 10046)
   554 . 0)
  (("/home/david/racine/site/orgmode/grimoire/bienetre-04-yoga.org" . 8007)
   466 . 7)
  (("/home/david/racine/site/orgmode/grimoire/bienetre-05-qigong.org" . 34656)
   1293 . 0)
  (("/home/david/racine/site/orgmode/grimoire/bienetre-06-vision.org" . 10173)
   384 . 0)
  (("/home/david/racine/site/orgmode/grimoire/divers-01-unite.org" . 13104)
   934 . 0)
  (("/home/david/racine/site/orgmode/grimoire/index.org" . 1399)
   58 . 0)
  (("/home/david/racine/site/orgmode/grimoire/litera-01-rimailleur.org" . 56560)
   1883 . 0)
  (("/home/david/racine/site/orgmode/grimoire/litera-02-styleau.org" . 91438)
   3350 . 32)
  (("/home/david/racine/site/orgmode/grimoire/litera-03-plumier.org" . 57)
   4 . 35)
  (("/home/david/racine/site/orgmode/grimoire/litera-03-theatre.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/litera-04-babel.org" . 6031)
   130 . 2)
  (("/home/david/racine/site/orgmode/grimoire/litera-04-plumier.org" . 8870)
   711 . 7)
  (("/home/david/racine/site/orgmode/grimoire/matemat-06-vecteur.org" . 2121)
   55 . 0)
  (("/home/david/racine/site/orgmode/grimoire/matemat-09-analyse.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/meta-01-metaphysics.org" . 31503)
   1486 . 13)
  (("/home/david/racine/site/orgmode/grimoire/meta-01-spiritus.org" . 31348)
   1482 . 0)
  (("/home/david/racine/site/orgmode/grimoire/meta-01-spiritus.org" . 37803)
   2086 . 0)
  (("/home/david/racine/site/orgmode/grimoire/meta-02-esoterisme.org" . 6384)
   239 . 0)
  (("/home/david/racine/site/orgmode/grimoire/meta-03-spiritus.org" . 1836)
   58 . 10)
  (("/home/david/racine/site/orgmode/grimoire/musica-01-monocorde.org" . 29447)
   971 . 6)
  (("/home/david/racine/site/orgmode/grimoire/musica-02-metronome.org" . 16271)
   547 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-02-partition.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-03-clavier.org" . 41514)
   1518 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-03-luth.org" . 26872)
   950 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-04-clavier.org" . 58025)
   2220 . 12)
  (("/home/david/racine/site/orgmode/grimoire/musica-04-concert.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-04-partition.org" . 80408)
   2814 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-05-concert.org" . 61071)
   2411 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-05-partition.org" . 30720)
   1063 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-05-tablature.org" . 18911)
   700 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-05-tablature.org" . 447)
   23 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-06-clechant.org" . 25144)
   1020 . 58)
  (("/home/david/racine/site/orgmode/grimoire/musica-06-concert.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-06-partition.org" . 37688)
   1243 . 12)
  (("/home/david/racine/site/orgmode/grimoire/musica-07-chamuse.org" . 14975)
   584 . 6)
  (("/home/david/racine/site/orgmode/grimoire/musica-07-clechant.org" . 57)
   4 . 35)
  (("/home/david/racine/site/orgmode/grimoire/musica-07-coda.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-07-concert.org" . 5032)
   188 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-08-chamuse.org" . 57)
   4 . 35)
  (("/home/david/racine/site/orgmode/grimoire/musica-08-clechant.org" . 16655)
   593 . 52)
  (("/home/david/racine/site/orgmode/grimoire/musica-08-coda.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-09-chamuse.org" . 21529)
   834 . 0)
  (("/home/david/racine/site/orgmode/grimoire/musica-09-coda.org" . 57)
   4 . 35)
  (("/home/david/racine/site/orgmode/grimoire/musica-10-coda.org" . 14212)
   456 . 48)
  (("/home/david/racine/site/orgmode/grimoire/nature-01-permaculture.org" . 327)
   13 . 18)
  (("/home/david/racine/site/orgmode/grimoire/nature-02-ecoconstruction.org" . 1037)
   48 . 28)
  (("/home/david/racine/site/orgmode/grimoire/ordina-01-multics.org" . 42660)
   841 . 0)
  (("/home/david/racine/site/orgmode/grimoire/ordina-02-bsd.org" . 2177)
   87 . 30)
  (("/home/david/racine/site/orgmode/grimoire/pictura-01-geometrie.org" . 2743)
   120 . 0)
  (("/home/david/racine/site/orgmode/grimoire/pictura-02-regle-compas.org" . 1)
   1 . 0)
  (("/home/david/racine/site/orgmode/grimoire/pictura-03-croquis.org" . 1050)
   70 . 0)
  (("/home/david/racine/site/orgmode/grimoire/referen-01-signets.org" . 1124)
   42 . 4)
  (("/home/david/racine/site/orgmode/grimoire/test-titres.org" . 319)
   16 . 0)
  (("/home/david/racine/snippet/elisp.snip" . 1)
   1 . 0)
  (("/home/david/racine/snippet/elisp.snip" . 33425)
   1693 . 0)
  (("/home/david/racine/snippet/elisp.snip" . 135440)
   4429 . 26)
  (("/home/david/racine/snippet/emacs.snip" . 1)
   1 . 0)
  (("/home/david/racine/snippet/git.snip" . 759)
   38 . 0)
  (("/home/david/racine/snippet/makefile.snip" . 22)
   2 . 0)
  (("/home/david/racine/snippet/shell.snip" . 274)
   19 . 24)
  (("/home/david/racine/test/emacs/init.el" . 1310)
   44 . 0)))
))

