
#+STARTUP: showall

#+TITLE: Eclats de vers : Meta 02 : Ésoterisme
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Géométrie sacrée


** Symboles

  - Point

  - Ligne

  - Cercle

    + Symbole d’union d’une communauté (table ronde)

    + Symbole de l’infini, car on peut y marcher indéfiniment

    + Symbole du cycle, un point fixé sur une roue se retrouvant
      alternativement en haut et en bas

    + Les ondes, sons, vibrations peuvent êtres vues comme un cercle «
      déroulé » en sinus et cosinus

  - Croix

    + Points cardinaux

    + Équinoxes & Solstices

    + Horizontal & Vertical

  - Triangle

    + Trinité

  - Ankh, clé de vie

    + Ressemble à une ancre sans l’arc de cercle inférieur

  - Caducée

    + Baguette de laurier ou d’olivier

    + Surmonté de deux ailas

    + Entouré de deux serpents entrelacés

  - Pentagramme

    - Nombre d’or

    - Éléments ?

  - Hexagramme, Sceau de Salomon

    + Polarité ?

  - Balance

    + Équilibre ?

    + Harmonie ?

  - Ouroboros (uroborus)

    + Serpent qui se mord la queue, formant un rond

    + Serpent qui se mord la queue, formant un huit

    + Deux serpents qui se mordent la queue, formant un rond

    + La chaîne de serpents qui se mordent la queue

    + Dynamique générée par une poursuite sans fin qui fait tourner la
      roue. Le système n’existe que parce que les contraires se
      courrent après dans une ronde sans fin, si ils se rejoignaient,
      si le serpent rattrapait la queue, ils s’autodétruirait.

  - Échiquier, Damier

    + Dualité

    + Templiers, maçons

  - Labyrinthe

    + Chemin initiatique

  - Voir aussi [[file:pictura-01-geometrie.org][le fichier concernant la géométrie]]


** Cultures

  - Un peu partout

    + Croix Solaire, Wheel Cross, Sun Cross, Solar Cross

  - Hindouïsme : Mandala

  - Bouddhisme : Mandala

  - Bouddhisme Tibétain : Mandala éphémère

    + Thangka (tangka, thanka, tanka) : peinture tibétaine sur du
      coton ou de la soie

  - Lauburu

  - Celtes

    + Art géométrique

    + Triskel

    + Triquetra : triple vesica piscis

    + Rouelle

    + Croix Celtique

  - Germains

    + Valknet

    + Runes

  - Navajo : Peinture sur sable

    + Peinture éphémère, comme au Tibet

  - Chrétienté

    + Chrisme, Chi Rho, ressemble aux segments d’une graine de vie

    + Croix Templier

    + Croix de Malte

    + Cathédrales

      * Rosaces ~ fleur de vie

      * Triskel

  - Native Americans

    + Medecine Wheel

  - Inca

    + Chakana, croix Inca


** Styles

  - Mandala : dessin symbolique décrivant l’univers

    + Exemples

      * 2 triangles croisés en étoile

      * Sri Yantra

      * Lotus

      * Temple à niveaux


* Numérologie

  1. Un = Unité

     - Point initial

     - Cercle initial

     - Ligne

  2. Deux = Dualité

     - Géométrie, Structure

     - Polarité +/- constitutive de l’univers

       + 0 = Neutre

       + Yang = Positif

       + Yin = Négatif

     - Polarité Intérieur / Extérieur

       + Yang = Extérieur

       + Yin = Intérieur

     - Nombre de cercles d’un Vesica Piscis

     - Croix

  3. Trois = Trinité

     - Enveloppe & Dualité

       + 1

	 * Unité centrale, point d’appui du balancier en équilibre

	 * Enveloppe englobant Positif & Négatif

	 * Centre de rotation autour duquel tournent Positif & Négatif

       + 2 = Positif

       + 3 = Négatif

     - Cycle

       + 1 = Montée

       + 2 = Maintien

       + 3 = Descente

     - Temps

       + 1 = Passé

       + 2 = Présent

       + 3 = Futur

     - Triangle

     - Nombre de branches d’un triskel

  4. Quatre

     - Points Cardinaux

     - Éléments feu, air, terre, eau

     - Carré

  5. Cinq

     - Centre & Sommets d’un carré

     - Solides de Platon

     - Pentagone

     - Deux triangles avec un côté commun

  6. Six

     - Nombre de branches partant du centre d’une graine de vie vers
       les centres des autres cercles

     - Sommets d’un hexagone

     - Triangles équilatéraux constituant un hexagone

     - Carré avec diagonales

  7. Sept

     - Centres des 7 cercles de la graine de vie

     - Centre et Sommets d’un hexagone

     - Centre et Sommets de 6 triangles équilatéraux assemblés en hexagone

  8. Huit

     - Sommets d’un cube

     - Possibilités des trigrammes yin/yang

  9. Neuf

     - Centre & Sommets d’un octahèdre

     - Centre & Sommets d’un cube

  10. Dix

      - Tetractys (tetraktys)

	+ De haut en bas

	  * 1 point : monade, unité

	  * 2 points : dyade, dualité

	  * 3 points, triade, harmonie, accord parfait en musique

	  * 4 points : tétrade, cosmos

	+ Le tout arrangé en triangle

	+ Le total fait 10 points

  11. Onze

  12. Douze

      - Nombre de branches partant du centre d’une graine de vie vers
	les centres des autres cercles et les intersections entre cercles

      - Sommets d’un cuboctahèdre

  13. Treize

      - Cercles principaux du fruit de vie

      - Centre & Sommets d’un cuboctahèdre

      - Important dans le calendrier Maya

  14. Quatorze

  15. Quinze

  16. Seize

  17. Dix-sept

  18. Dix-huit

  19. Nombre de cercle de la fleur de vie

  20. Vingt

      - Important dans le calendrier Maya


* Éléments

  - Grèce, Inde : Feu, Air, Eau, Terre, Éther

  - Chine : Eau, Bois, Feu, Terre, Métal


** Sept éléments

  - La fusion des écoles donne 7 éléments

    + Air

    + Eau

    + Métal

    + Éther

    + Feu

    + Bois

    + Terre

  - Directions

    + Centre cube + 6 faces --> 7 directions

      * Éther = Centre

      * Terre = Bas

      * Air = Haut

      * Bois = Est

      * Feu = Sud

      * Métal = Ouest

      * Eau = Nord

    + Centre hexagone + 6 sommets --> 7 directions


** Classiques

  - Noms

    + Eau

    + Terre

    + Aether, Éther, Espace, Vide, Plasma

    + Air

    + Feu

  - Polarité +/-

    + Yang : Feu (Créativité), Air (Intellect)

    + Yin : Terre (Matière), Eau (Émotions)

  - Saisons

    + Air : Printemps

    + Feu : Été

    + Terre : Automne

    + Eau : Hiver


** Qualités

  - Chaud = énergie

  - Froid = résistance

  - Sec = analyse

  - Humide = synthèse

Qualités des éléments

| Feu   | Chaud | Sec    |
| Air   | Chaud | Humide |
| Terre | Froid | Sec    |
| Eau   | Froid | Humide |

Présenté autrement

| Sec   | Feu    | Chaud  |
|-------+--------+--------|
| Terre | Aether | Air    |
|-------+--------+--------|
| Froid | Eau    | Humide |


** Celtique

  - Noms

    + Eau

    + Terre

    + Brouillard

    + Air

    + Feu


** Inde

  - Sanskrit

    + Agni    : Feu

    + Vayu    : Air

    + Akasha  : Éther, Espace

    + Prithvi : Terre

    + Jala    : Eau

  - Mudras

    + Auriculaire : Eau

    + Annulaire   : Terre

    + Majeur      : Aether

    + Index       : Air

    + Pouce       : Feu

  - Énergies (Dosha)

    + Vata  : Éther, Air

    + Pitta : Feu, Eau

    + Kapha : Eau, Terre


** Chine

  - Éléments du Wu Xing

    + Shul : Eau

    + Mu : Bois

    + Huo : Feu

    + Tu : Terre

    + Jin : Métal

  - Cycles

    + Cycle nourissier

      * L’Eau nourrit le Bois

      * Le Bois nourrit le Feu

      * Le Feu nourrit la Terre

      * La Terre nourrit le Métal

      * Le Métal nourrit l’Eau

    + Cycle de contrôle

      * L’Eau contrôle le Feu

      * Le Feu contrôle le Métal

      * Le Métal contrôle le Bois

      * La Bois contrôle la Terre

      * La Terre contrôle l’Eau

  - Symbolique

    + Feu : Montée, Polarité +

    + Eau : Descente, Polarité -

    + Bois : Expansion vers l’Extérieur

    + Métal : Contraction vers l’Intérieur

    + Terre : Rotation, Cycle

  - Saisons

    + Eau : Hiver

    + Bois : Printemps

    + Feu : Été

    + Métal : Automne

    + Terre

      * Cycle des saisons

      * Périodes de transition entre les saisons

	- Exemple : Été indien

  - Directions

    + Eau : Nord

    + Bois : Est

    + Feu : Sud

    + Métal : Ouest

    + Terre : Centre

  - Mouvements du corps

    + Eau : Être debout

    + Bois : Marcher

    + Feu : Courir

    + Terre : Être assis

    + Métal : Être couché

  - Saveurs

    + Eau : Salé

    + Bois : Acide

    + Feu : Amer

    + Terre : Doux, Sucré

    + Métal : Piquant

  - Couleurs

    + Eau : bleu, noir

    + Bois : vert

    + Feu : rouge

    + Terre : jaune, ocre

    + Métal : blanc


** Japon

  - Terre

  - Eau

  - Feu

  - Vent

  - Vide, Aether


* Astronomie


** Lune & Soleil

  - Lunaison : 29.53 jours

    + À peu près 30 jours soit un mois

      * 30 divisible par 2, 3, 5, 6, 10, 15

  - Temps entre la nouvelle lune et le premier quartier : 7.375 jours

    + Dont 7 jours complets soit une semaine

  - Nombre de lunaisons par an : 12.3684

    + 12 lunaisons complètes & une 13e entamée

      * 12 divisible par 2, 3, 4, 6


* Astrologie


** Zodiaque

| Nom         | Latin        | Début        | Fin          | Symbole |
|-------------+--------------+--------------+--------------+---------|
| Bélier      | Aries        | 21 mars      | 20 avril     | ♈      |
| Taureau     | Taurus       | 21 avril     | 21 mai       | ♉      |
| Gémeaux     | Gemini       | 22 mai       | 21 juin      | ♊      |
| Cancer      | Cancer       | 22 juin      | 22 juillet   | ♋      |
| Lion        | Leo          | 23 juillet   | 22 août      | ♌      |
| Vierge      | Virgo        | 23 août      | 22 septembre | ♍      |
| Balance     | Libra        | 23 septembre | 22 octobre   | ♎      |
| Scorpion    | Scorpio      | 23 octobre   | 22 novembre  | ♏      |
| Serpentaire | Serpentarius | 29 novembre  | 28 décembre  | ♐      |
|             | Ophiuchus    |              |              |         |
| Sagittaire  | Sagittarius  | 23 novembre  | 21 décembre  | ♑      |
| Capricorne  | Capricorn    | 22 décembre  | 20 janvier   | ♒      |
| Verseau     | Aquarius     | 21 janvier   | 19 février   | ♓      |
| Poissons    | Pisces       | 20 février   | 20 mars      | ♔       |


*** Éléments & Caractères

Modalités

  - Cardinal

    + Début d’une saison

  - Fixe

    + Milieu d’une saison

  - Mutable

    + Fin d’une saison


|          | Feu         | Terre     | Air      | Eau     |
|----------+-------------+-----------+----------+---------|
| Cardinal | Aries       | Capricorn | Libra    | Cancer  |
| Fixe     | Leo         | Taurus    | Aquarius | Scorpio |
| Mutable  | Sagittarius | Virgo     | Gemini   | Pisces  |


*** Planètes

| Aries       | Mars                        |
| Taurus      | Venus                       |
| Gemini      | Mercury                     |
| Cancer      | Moon                        |
| Leo         | Sun                         |
| Virgo       | Mercury                     |
| Libra       | Venus                       |
| Scorpio     | Mars (moderne : Pluto)      |
| Sagittarius | Jupiter                     |
| Capricorn   | Saturn                      |
| Aquarius    | Saturn (moderne : Uranus)   |
| Pisces      | Jupiter (moderne : Neptune) |


** Astrologie chinoise

| Signe   | Yin/Yang | Direction | Saison           | Fixed | Element |
|---------+----------+-----------+------------------+-------+---------|
| Rat     | Yang     | North     | Milieu hiver     | Eau   |       1 |
| Boeuf   | Yin      | North     | Fin hiver        | Eau   |       2 |
| Tigre   | Yang     | East      | Début printemps  | Bois  |       3 |
| Lapin   | Yin      | East      | Milieu printemps | Bois  |       4 |
| Dragon  | Yang     | East      | Fin printemps    | Bois  |       1 |
| Serpent | Yin      | South     | Début été        | Feu   |       2 |
| Cheval  | Yang     | South     | Milieu été       | Feu   |       3 |
| Chèvre  | Yin      | South     | Fin été          | Feu   |       4 |
| Singe   | Yang     | West      | Début automne    | Métal |       1 |
| Coq     | Yin      | West      | Milieu automne   | Métal |       2 |
| Chien   | Yang     | West      | Fin automne      | Métal |       3 |
| Cochon  | Yin      | North     | Début hiver      | Eau   |       4 |


** Calendrier Maya

  - Cycle

    + 3114 BC - 2012 AD

    + 1 kin = 1 jour

    + 1 uinal = 20 jours = mois maya

    + 1 tun = 18 uinal = 360 jours = année maya

    + 1 katun = 20 tun = 7 200 jours = génération

    + 1 baktun = 20 katun = 400 tuns = 144 000 jours

    + 1 age = 13 baktun = 5 200 tun = 1 872 000 jours ~ 5 125 ans

    + Tzolkin : 260 jours

      * 13 signes de 20 jours

      * 1 tzolkin = 13 uinal = 260 jours


* Tarot

  - Arcanes mineures : 56

  - Arcanes majeures : 22

  - Mineures - Majeures = 56 - 22 = 34

  - Mineures - Majeures - Majeures = 12

  - Mineures + Majeures = 78

  - Mineures + Majeures + Majeures = 100


* Symbolique


** Taoisme


*** Trigrammes

Un trigramme est l’association de trois symboles, chacun d’entre-eux
pouvant représenter le yin ou le yang.

Le yang est généralement représenté par un trait plein et le yin
par un trait redoublé. Nous les notons :

| ¦ | Yang |
| — | Yin  |

Voici les 8 possibilités des trigrammes :

| ¦¦¦ | Ciel               |
| ¦¦— | Lac, Brume, Marais |
| ¦—¦ | Feu                |
| ¦—— | Foudre, Tonnerre   |
| —¦¦ | Vent, Bois         |
| —¦— | Eau                |
| ——¦ | Montagne           |
| ——— | Terre              |

Sous la forme des dualités, il donne :


| Trigrammes | Symboles           | Qualités                                          |
|------------+--------------------+---------------------------------------------------|
| ¦¦¦        | Ciel               | Créativité, Force, Initiative                     |
| ———        | Terre              | Réceptivité, Adaptabilité, Accueil                |
| ¦¦—        | Lac, Brume, Marais | Joie, Légèreté                                    |
| ——¦        | Montagne           | Immobilité, Rigueur, Cohésion, Calme, Solidité    |
| ¦—¦        | Feu                | Clarté, Lucidité, Vivacité, Éclat                 |
| —¦—        | Eau                | Profondeur, Endurance, Peur                       |
| ¦——        | Foudre, Tonnerre   | Dureté, Impulsion, Secousse                       |
| —¦¦        | Vent, Bois         | Douceur, Pénétration, Soumission, Intériorisation |


*** Hexagramme

Un hexagramme un constitué de deux trigrammes.


*** Bāguà

Les trigrammes sont représentés habituellement sous forme d’octogone
entourant le tai-ji, l’ensemble étant alors nommé *bāguà*, ou plus
simplement *bagua*.


** Mayas


*** Hunab ku

  - Spirales emmêlées rappelant le taijitu

  - Les spirales sont entourées d’une variante de chakana formant
    quatre pyramides à degrés

  - Quatre paires d’antennes sortent des sommets des pyramides


** Couleurs                                                        :noexport:

Retrouver source

  - Rouge : C’est le symbole de la passion, du courage, de l’ambition,
    de l’amour ardent et passionné mais également le symbole de la
    colère et du tempérament volontaire.

  - Orange : C’est le symbole de la joie, de la gaieté, de la beauté,
    de la grandeur, de l’équilibre de l’esprit et des sens.

  - Jaune : C’est le symbole du luxe, de la gloire, du succès. Il est
    également associé à l’infidélité et à la trahison.

  - Vert : C’est l’emblème du printemps, le symbole de l’espoir, de la
    joie, de l’optimisme.

  - Bleu : C’est le symbole de l’air, de la sagesse, de l’amour pur et
    platonique, de la communion des âmes, de l’élévation de l’âme.

  - Violet : C’est le symbole de la paix, de la douceur, de la
    générosité, de l’humilité.

  - Rose : C’est le symbole de la jeunesse.

  - Blanc : C’est le symbole de la pureté, de la consolation, de
    l’innocence, de la naïveté et de la joie.



** Fleurs                                                          :noexport:

Retrouver source

| Acacia                      | Amour chaste                    |
| Marguerite bariolée         | Beauté                          |
| Amarante                    | Immortalité                     |
| Marguerite des champs       | Patience                        |
| Amaryllis                   | Fierté                          |
| Marguerite jaune            | Incertitude                     |
| Ancolie                     | Folie                           |
| Menthe                      | Chaleureux                      |
| Armoise                     | Absence                         |
| Menthe poivrée              | Cordialité                      |
| Aubépine                    | Espérance                       |
| Mimosa                      | Sensibilité                     |
| Basilic                     | Haine                           |
| Muguet                      | Retour du bonheur               |
| Belladone                   | Silence                         |
| Muscade                     | Rencontre attendue et espérée   |
| Blé                         | Richesses                       |
| Myosotis                    | Amitié sincère                  |
| Bourrache                   | Brusquerie                      |
| Myosotis                    | Amour véritable                 |
| Bouton de citronnier        | Fidélité en amour               |
| Narcisses poétiques         | Estime de soi                   |
| Bouton de pêcher            | Je suis ton prisonnier          |
| Oeillet                     | Audace                          |
| Bouton de rose blanc        | Un coeur sans amour             |
| Oeillet de poète            | Finesse                         |
| Bouton de rose rouge        | Tu es jeune et beau             |
| Oeillet d’Inde              | Jalousie                        |
| Boutons de fleurs d’oranger | Ta pureté égale ta beauté       |
| Oeillet double              | Toujours ravissante             |
| Branche d’olivier           | Paix                            |
| Onagre                      | Inconstance                     |
| Camélia                     | Excellence sans prétention      |
| Oranger                     | Générosité                      |
| Camélia blanc               | Perfection constante            |
| Palmier                     | Victoire                        |
| Camomille                   | Énergie dans l’adversité        |
| Pavot                       | Plaisir éphémère                |
| Campanule                   | Reconnaissance                  |
| Perce-neige                 | Espérance                       |
| Cèdre                       | Force                           |
| Pervenche blanche           | Souvenirs agréables             |
| Chardon                     | Austérité                       |
| Pervenche bleue             | Début de l’amitié               |
| Châtaignier                 | Justice rend moi                |
| Pivoine                     | Honte                           |
| Chêne                       | Hospitalité                     |
| Primevère                   | Beauté divine                   |
| Chèvrefeuille               | Amour fraternel                 |
| Primevère des jardins       | Les mystères du coeur           |
| Chrysanthème blanc          | Vérité                          |
| Rhododendron                | Danger                          |
| Chrysanthème jaune          | Amour en réserve                |
| Rose                        | Amour                           |
| Chrysanthème rouge          | J’aime                          |
| Rose à feuilles rouges      | Beauté et prospérité            |
| Clématite                   | Beauté mentale                  |
| Rose acacia                 | Amitié                          |
| Coquelicot rouge            | Consolation                     |
| Rose blanche                | Je suis digne de toi            |
| Crocus                      | Joie et jeunesse                |
| Rose jaune                  | Jalousie                        |
| Fleur de lis                | Flamme                          |
| Rose multiflore             | Grâce                           |
| Fleur de lotus              | Amour brouillé                  |
| Rose rouge foncé            | Confusion timide                |
| Fougère                     | Sincérité                       |
| Rose trémière blanche       | Ambition féminine               |
| Genêt                       | Humilité                        |
| Rose unique                 | Ne m’appelle pas belle          |
| Géranium                    | Gentillesse                     |
| Souci                       | Mélancolie                      |
| Gerbe d’or                  | Précaution                      |
| Sureau                      | Enthousiasme                    |
| Giroflée                    | Beauté éternelle                |
| Thym                        | Activité                        |
| Hibiscus                    | Beauté délicate                 |
| Tournesol géant             | Arrogance                       |
| Iris                        | Flamme                          |
| Trèfle                      | Légèreté de l’âme               |
| Jasmin                      | Amabilité                       |
| Tubéreuse                   | Plaisirs dangereux              |
| Jasmin jaune                | Élégance et grâce               |
| Tulipe                      | Célébrité                       |
| Jonquille                   | Qualités chevaleresques         |
| Tulipe jaune                | Amour désespéré                 |
| Laurier rose                | Méfiance                        |
| Tulipe panachée             | Yeux superbes                   |
| Laurier sauce               | Gloire                          |
| Tulipe rouge                | Déclaration d’amour             |
| Lavande                     | Méfiance                        |
| Véronique                   | Fidélité féminine               |
| Lierre                      | Mariage                         |
| Violette blanche            | Modestie                        |
| Lilas blanc                 | Pureté                          |
| Violette bleue              | Fidélité                        |
| Lilas pourpre               | Premiers émois en amour         |
| Violette jaune              | Bonheur rural                   |
| Lis blanc                   | Pureté, modestie et gentillesse |
| Violette pourpre            | Tu occupes mes pensées          |
| Lis jaune                   | Gaieté                          |
| Volubilis                   | Espoir éteint                   |
| Lupin                       | Imagination                     |
| Zinnia                      | Pensées pour les amis absents   |


** Arbres                                                          :noexport:

Retrouver source


*** L’Acacia

On dit que l’arche d’alliance était en bois d’Acacia plaqué d’or, et
que la couronne d’épines du Christ provenait de ce même arbre. Dans la
pensée judéo-chrétienne, cet arbuste au bois dur et presque
imputrescible, aux épines redoutables et aux fleurs arborant les
couleurs du lait et du sang, est un symbole de renaissance et
d’immortalité.


*** L’Amandier

Signe de la renaissance de la nature, cet arbre à la feuillaison
printanière est aussi un symbole de fragilité car ses fleurs, ouvertes
dès l’arrivée du printemps, sont sensibles au gel tardif. Chez les
Grecs, l’amande pressée était comparée à la semence de Zeus, en tant
que puissance créatrice. On affirme même que l’Amandier remonte
directement à ce Dieu et que son fruit peut féconder une vierge
indépendamment de l’union sexuelle. Selon une croyance qui tient
encore en Europe, la jeune fille qui s’endort sous un Amandier en
rêvant à son fiancé, peut soudainement se réveiller enceinte.


*** L’Aubépine

On accordait à cet arbre des pouvoirs permettant de détourner la
foudre, de conserver la viande, d’empêcher de faire tourner le lait et
d’éloigner les serpents ; d’où des plantations fréquentes d’Aubépines
à proximité des granges et des étables.


*** Le Bouleau

Les chamans de la Sibérie vantaient les vertus thérapeutiques de cet
arbre des régions froides et tempérées. Ils n’hésitaient pas à monter
dans ses branches pour mieux entrer en contact avec les Dieux de
l’autre monde. On peut également s’interroger sur les raisons
inconscientes qui font autant apprécier le Bouleau comme arbre
d’ornement, une essence qui, pourtant, ne possède pas une grande
espérance de vie et qui, mis à part sa beauté esthétique, offre plus
d’inconvénients que d’avantages en ornementation. S’agit-il de sa
blancheur, un symbole de pureté, ou de l’extrême finesse de sa ramure
qui rend cet arbre si attirant ?


*** Le Chêne

Arbre sacré dans de nombreuses traditions, le Chêne est investi de
privilèges accordés à la divinité suprême parce qu’il attire la foudre
et symbolise la majesté. En tout temps et en tout lieu, le Chêne est
synonyme de force et de solidité. C’est du moins l’impression qu’il
laisse quand il atteint sa maturité. Notons que le bois du chêne a la
propriété d’être incorruptible, alors ne soyons donc pas étonnés
d’apprendre que les termes "chêne" et "force" se traduisent en latin
par le même mot : robur, symbolisant autant la force morale que
physique. Il est le symbole de l’arbre de vie, le salut ainsi que les
figures allégoriques de la Force et de la Prospérité. Le chêne est
aussi l’arbre consacré à Jupiter dans la mythologie classique où de
grands chênes croissent dans la forêt de Dodone, en Épire, qui est
consacré à l’oracle de ce dieu, et est l’un des plus anciens
sanctuaires grecs.


*** Le Cyprès

Cet arbre sacré chez de nombreux peuples, grâce à sa longévité et à sa
verdure persistante, est également nommé "Arbre de vie", à l’instar du
Thuya. Chez les Grecs et les Romains, le Cyprès est en rapport avec
les divinités de l’enfer. Il est l’arbre des régions souterraines,
d’où sa présence remarquée dans plusieurs cimetières du bassin de la
Méditerranée. Le cyprès est l’un des attributs de la figure
allégorique du Désespoir[4] : elle en tient une branche dans la main
droite car, de même que le cyprès ne repousse pas s’il est coupé,
l’homme en proie au désespoir finit par annihiler en lui toute
possibilité de cultiver le courage et la Vertu.


*** Le Frêne

À l’instar du Chêne, le Frêne est un symbole de solidité puissante. On
en faisait des hampes de lances. Dans les traditions scandinaves, cet
arbre symbolise l’immortalité et sert de lien entre les trois niveaux
du cosmos. Dans les anciens pays baltes, l’homme étourdi et un peu
niais est qualifié de frêne car il est considéré comme aveugle. En
effet, ne sachant pas quand vient le printemps, il reste longtemps
dénudé. Tandis qu’à l’automne, craignant de paraître ridicule à
nouveau, il est le premier à se dépouiller rapidement de toutes ses
feuilles.


*** L’Olivier

La richesse symbolique de cet arbre est abondante: récompense,
purification, force, paix, victoire, fécondité. Consacré à la Déesse
grecque Athéna, l’Olivier l’était également au Dieu romain Jupiter. Un
mythe raconte que Neptune et Minerve, se disputant la possession de
l’Attique se présentent devant l’assemblée des Dieux. Ces derniers
décident de confier la région à celui qui offrira le don le plus
précieux. Le dieu de la mer frappa un rocher avec son trident et fit
jaillir une source pendant que la déesse fit naître un Olivier. Ainsi
Minerve remporta la victoire et cet arbre lui fut consacré. Il est
devenu symbole de paix sans doute parce que la déesse est la figure
guerrière opposée à Mars. Il faut aussi se rappeler que vers la fin du
déluge, une colombe rapporta une branche d’Olivier vers l’arche de
Noé. Selon une vieille légende, la croix du Christ était fabriquée de
Cèdre et d’Olivier. Dans le langage du Moyen Âge, cet arbre
symbolisait l’or et l’amour.


*** L’Orme

Cet arbre a toujours détenu des pouvoirs surnaturels. Dans la France
du Moyen Âge, il était appelé "l’arbre de la justice" parce que
c’était sous sa canopée que les seigneurs et les juges rendaient leurs
jugements. On savait l’Orme capable de guérir diverses maladies
cutanées, dont la lèpre. Les guérisseurs enlevaient des morceaux
d’écorce d’Orme pour concocter des remèdes contre le rhumatisme.


*** Le Peuplier

Cet arbre propre à l’hémisphère boréal tire son nom du mot latin
populus et de l’ancien français poplier, deux termes qui signifient
"Peuple". La légende dit que c’est l’Arbre du peuple puisque ce serait
sous des Peupliers que celui-ci prenait autrefois des décisions
importantes. Depuis l’Antiquité le peuplier a une connotation funèbre.
Pline l’Ancien rappelle que les défunts étaient recouverts de
peupliers noirs. Le graveur Vincenzo Cartari, au XVIIe siècle, note
que le peuplier est considéré comme un arbre infernal parce qu’il
croît sur les rives de l’Achéron. Lorsque Hercule descend aux enfers
afin de s’emparer du chien Cerbère, il s’enveloppe le crâne de rameaux
de peuplier, qui blanchissent au contact de la sueur dans sa partie
inférieure et noircissent par les fumées infernales en sa partie
supérieure.


*** Le Pommier

Il se trouve au centre de plusieurs croyances, dont celles de procurer
la sagesse, d’améliorer les connaissances et d’acquérir l’immortalité.
Son fruit est identifié depuis très longtemps comme un fortifiant et
comme un remède préventif contre la maladie. À cet effet,
souvenons-nous du vieux proverbe anglo-saxon: An apple a day keeps the
doctor away.


*** Le Sapin

On dit que le Sapin empêchait la foudre de tomber et conjurait les
mauvais sorts. En Allemagne, on flagellait autrefois les femmes durant
le mardi gras, avec des branches de cet arbre, dans le but de leur
permettre d’avoir des enfants.


*** Le Saule

Une croix faite avec deux rameaux de Saule, que l’on jetait dans l’eau
d’une source sacrée, permettait de connaître l’imminence ou non de sa
mort. Une croix flottante annonçait une mort certaine dans les mois
suivants. Celle-ci était cependant éloignée si la croix coulait ; plus
éloignée encore si elle atteignait rapidement le fond de l’eau. Le
phénomène apparaît toutefois contradictoire quant à la mort associée à
la flottaison plutôt qu’à la disparition de la croix. L’image du saule
a une connotation négative depuis l’Antiquité, probablement parce que
les fruits de cet arbre tombent avant qu’ils ne soient mûrs. Dans
l’Odyssée, Homère signale cette particularité. Lorsque Ulysse prend
congé de Circé, la magicienne lui indique comment atteindre l’Hadès :
"Quand ton vaisseau arrivera au bout de l’Océan, tu trouveras un
rivage plat et les bois sacrés de Perséphone : hauts peupliers noirs
et saules qui perdent leurs fruits. Echoue là ta nef, près de l’Océan
aux profonds remous ;toi, entre dans l’humide demeure d’Hadès.[5]" La
croyance selon laquelle le saule est infécond est répandue dans
l’Antiquité, Pline l’Ancien la mentionne aussi[6]. À la renaissance,
la stérélité présumée du saule inspire la représentation de la figure
allégorique de la Disette. Cesare Ripa [7]la décrit comme une femme
émaciée, mal vêtue, debout à côté d’une vache maigre et tenant, de la
main droite une branche de saule et dans la main gauche, une pierre
ponce, toute deux considérées comme stériles. Car Ripa explique que :
"la stérilité est la raison principale de la disette".


*** Le Laurier

Ovide raconte comment la nymphe Daphné, est métamorphosée en laurier
pour avoir échappé à l’amour d’Apollon qu’elle ne payait pas en
retour. Depuis cet arbre est consacré au Dieu du soleil. Dans la Rome
antique, le laurier est consacré à Jupiter. Selon la doctrine
chrétienne, le laurier est à la fois symbole d’éternité, car il est
toujours vert et de chasteté car ses feuilles ne se flétrissent
jamais. C’est surout à la renaissance que se diffuse l’image
allégorique de la Victoire, figure féminine ailée qui remet une
couronne de laurier au vainqueur ou lui pose sur la tête.


*** Le Genévrier

Apollonios de Rhodes[8] décrit comment Médée aide Jason à s’emparer de
la Toison d’or en endormant le dragon en lui administrant une potion
issue du genévrier. Le genévrier est aussi associé à la chasteté, car
comme la châtaigne est protégée par sa bogue, la baie de genièvre est
protégée par ses feuilles. Pline l’Ancien[9] signale aussi que le bois
de genévrier n’est pas attaqué par les vers et qu’il a la propriété de
ne pas dépérir. Celui-ci donne l’exemple d’un temple consacré à Diane,
en Espagne, bâtit avec des poutres de genèvrier, deux cents ans avant
la guerre de Troie et est encore en parfait état à son époque. C’est
pour cela, sans doute, qu’il est aussi associé à l’éternité.


*** Le Palmier

Il signifie la victoire, la renommée, le triomphe sur la mort. Il
symbolise le martyre, la Vierge Marie et l’Asie. Depuis l’Antiquité le
palmier est attribué au mythe du soleil pour évoquer la gloire et
l’immortalité, en raison de la disposition harmonieuse de ses branches
et de ses feuilles semblables à des rayons. La branche de palmier est
offerte a vainqueur comme emblème de victoire. Dans certaines légendes
Romaines la branche de palmier est signe de bon présage. Horace
raconte que Rhéa Silvia voit en songe Romulus et Rémus peu avant
d’accoucher, sous l’aspect de palmiers aux branches majestueuses se
dressant vers le ciel.


*** Le Myrte

Arbrisseau consacré à Vénus car selon Ovide[10], c’est de son
feuillage que la déesse de la beauté, née de la mer, couvre sa nudité,
le jour où elle aborde l’île de Cythère. Une autre légende rapporte qu
Bacchus, devant se rendre aux enfers pour libérer sa mère Sémélé tuée
par le foudre de Jupiter, promet d’y laisser un myrthe en échange.
D’où la signification funèbre de l’arbrisseau. Malgré tout, le myrthe
a toujours été chargé d’une valeur positive et consacré à Vénus, est
devenu un symbole de fécondité : durant le banquet des noces, les
jeunes époux portent habituellement une couronne de myrthe sur la
tête. Pline l’Ancien appelle cet arbrisseau myrthus conjugalis[11]. Un
rameau de myrte est parfois représenté dans la main du prophète Isaïe
en vertu de ce passage de son livre : "Au lieu d’épines croîtra le
cyprès, au lieu d’ortie croîtra le myrte[12]".


*** Le Lierre

Le lierre est avec la vigne, l’un des attributs de Bacchus, dieu du
vin et de ses suivantes, les Ménades : il entoure leur thyse ou,
tressé en couronne, il ceint leur tête. Ovide raconte que Bacchus,
aussitôt après sa naissance, est confié aux nymphes de Nysa, qui
dissimulent son berceau en le recouvrant de lierre pour le soustraire
de la colère de Junon. En effet, l’enfant est né de l’union
clandestine de Jupiter et Sémélé. Notons que le lierre en décoction a
les propriétés d’atténuer les effets de l’ivresse. C’est probablement
une des raisons pour laquelle le lierre est associé au dieu du vin. Le
fait que le lierre soit une plante grimpante qui pousse en embrassant
le tronc des arbres le rapproche de l’idée symbolique de l’amour
éternel et de fidélité.


*** La Vigne

La vigne est assez fréquente comme motif ornemental dans
l’architecture sacrée et l’art. Elle est l’attribut des figures
allégoriques de l’Automne, du mois de septembre, de la Joie, de
l’Entraide, de la Solidarité conjugale et de l’Amitié. La vigne est
aussi l’un des attributs de Bacchus, dieu du vin et ses suivantes le
Ménades. Dans les représentations des bacchanales et du cortège du
dieu, les participants ont la tête ceinte de couronnes tressées de
sarments et de feuilles de vignes. Le cep de vigne et son fruit sont
fréquemment cités dans les Ecritures et sont généralement considérés
comme des symboles du Christ, du sang versé lors de son sacrifice et
de l’eucharistie. Dans un célèbre passage de l’Evangile de Jean le
Christ affirme : "Je suis la vrai vigne"[13].

*** Le Blé. Le blé est le fruit de la terre par excellence. La mythologie
antique raconte comment Cérès en fait don à l’homme après avoir
retrouvé sa fille Proserpine. Les allégories de l’Eté et des mois de
juin et de juillet ont souvent pour attributs des épis ou des germes de
blé[14]. Celle de l’Abondance est représentée sous les traits d’une
femme aux bras chargés de gerbes de blé ou tenant une corne d’abondance
d’où débordent des épis.

En Inde, le figuier cosmique, Asvattha (ou arbre Pippal, ficus
religiosa) est le représentant sur terre de Brihaspati, qui n’est
autre que Jupiter. C’est un arbre hautement sacré, car il est dédié à
la trimurti (trois dieux) : Brahmâ, Shiva, Vishnu. On l’honore plus
particulièrement pendant le mois de Shravana (juillet-août). C’est à
l’ombre de son feuillage que Siddhartha, le bouddha historique,
atteignit l’Éveil. Il abrite l’âme des défunts, et on lui rend un
culte de fécondité et de fertilité. On se sert de son bois pour
allumer le feu sacré.

Mircea Eliade évoque [15] un culte des arbres, liés aux dieux Attis et
Cybèle, en Grèce antique. Une confrérie dite des « dendrophores »
(étymologiquement « porteurs d’arbres ») « amenait de la forêt un pin
coupé (arbor intrat). Le tronc était enveloppé de bandelettes, comme
un cadavre, et au milieu était attaché une image d’Attis. L’arbre
représentait le dieu mort. » Ces processions avaient lieu lors de
fêtes à l’équinoxe de printemps, du 15 au 23 mars.

Les Celtes auraient élaboré un zodiaque en corrélation avec les
arbres. Mais ce sujet prête à polémiques. [1] L’arbre biblique de la
connaissance portant le « fruit défendu », tel qu’imaginé et peint par
Lucas Cranach l’Ancien (1472-1553)

Dans le judaisme et le christianisme, deux arbres imaginaires et
sacrés sont importants, et reliés au Paradis : l’arbre de la
connaissance du bien et du mal, l’arbre de vie.[16]

    "L’Éternel Dieu fit pousser du sol des arbres de toute espèce,
    agréables à voir et bons à manger, et l’arbre de vie au milieu du
    jardin, et l’arbre de la connaissance du bien et du mal...
    L’Éternel Dieu prit l’homme et le plaça dans le jardin d’Éden... :
    'Tu pourras manger de tous les arbres du jardin ; mais tu ne
    mangeras pas de l’arbre de la connaissance du bien et du mal, car,
    le jour où tu en mangeras, tu mourras.'" (Genèse, II).
