
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 05 : Tablature
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Tonalité

#+TOC: headlines 1 local

** Introduction

L’association d’une tonique et d’un mode est appelée *tonalité*.

On parlera par exemple de la tonalité de :

  - do ionien
  - la éolien
  - etc

** Intérieur & extérieur

La tonalité détermine les notes et les altérations de la gamme
utilisée.

On dit qu’une note, diatonique ou altérée, est *dans la tonalité* si
elle fait partie de la gamme determinée par la tonalité.

On dit qu’une note, diatonique ou altérée, est *en dehors de la
tonalité* si elle ne fait pas partie de la gamme detérminée par la
tonalité.

** Notes tonales

Quelle est la différence entre une gamme et une tonalité ? Toutes deux
sont définies par une tonique et un mode, mais la tonalité possède en
plus une hiérarchie entre les degrés qui la constituent.

Les *notes tonales* sont les notes les plus importantes de la gamme, à
savoir la tonique et les degrés qui l’entourent dans le cycle des
quintes :

#+ATTR_HTML: :class plat
| noms   | : | sous-dominante | <— | 5te | —> | tonique | <— | 5te | —> | dominante |
| degrés | : |              4 | <— | 5te | —> |       1 | <— | 5te | —> |         5 |

Un *degré fort*, ou *degré tonal*, est un degré qui correspond à une
note tonale. Les degrés 4, 1, 5 sont donc les degrés forts de la
tonalité.

Les autres degrés sont appelés *degrés faibles*.

On a donc la hiérarchie :

#+ATTR_HTML: :class plat
| degrés forts   | : |   | 4 |   | 1 |   | 5 |   |
| degrés faibles | : | 2 |   | 6 |   | 3 |   | 7 |

** Intervalles justes

Les notes tonales sont généralement séparées de la tonique par les
intervalles justes de la gamme :

| Note 1  | Note 2         | Intervalle      |
|         |                | à l’octave près |
|---------+----------------+-----------------|
| tonique | tonique        | unisson         |
| tonique | dominante      | quinte          |
| tonique | sous-dominante | quarte          |

Il existe toutefois quelques exceptions. Ainsi, la dominante de la
gamme de /si locrien/ forme un intervalle de quinte diminuée avec la
tonique, raison pour laquelle le mode locrien est peu utilisé.

** Accords

Considérons les accords de trois notes construits en prenant les notes
tonales comme fondamentales :

| Note tonale    | Degrés        | Exemple      |
|                | dans l’accord | tonique = do |
|----------------+---------------+--------------|
| tonique        | 1 3 5         | do mi sol    |
| dominante      | 5 7 2         | sol si ré    |
| sous-dominante | 4 6 1         | fa la do     |

On constate que l’on retrouve toutes les notes de la gamme.

* Fonctions tonales

#+TOC: headlines 1 local

** Introduction

Une *fonction tonale* est une fonction musicale réalisée à la fois par :

  - une note tonale
  - un accord mettant en évidence cette note tonale

La musique utilisant les fonctions tonales est appelée *musique tonale*.

** Tonique

En tant que note la plus importante de la gamme, la tonique assure
aussi la première fonction tonale.

La tonique est la fonction sur laquelle la musique effectue ses pauses
les plus importantes.

** Dominante

La musique tonale s’articule autour de la dualité qui existe entre la
tonique, fonction de repos, et la dominante, fonction dynamique autour
de laquelle la musique peut se développer. Il arrive également que la
musique effectue des pauses à la dominante, mais ce sont là des arrêts
nettement moins appuyés que ceux effectués sur la tonique.

La dominante est naturellement attirée par la tonique, et peut :

  - répondre à son appel, ce qui détent la musique
  - ne pas y répondre et repartir vers une autre idée

La dominante constitue donc la fonction tonale la plus importante avec
la tonique.

** Sous-dominante

La sous-dominante constitue la fonction tonale la plus importante
après la tonique et la dominante.

** Tableau récapitulatif

| Degrés | Fonctions            | Abréviations |
|--------+----------------------+--------------|
|      4 | sous-dominante       | SD           |
|      1 | tonique              | T            |
|      5 | dominante            | D            |

* Modes majeur et mineur

#+TOC: headlines 1 local

** Introduction

Le tableau suivant regroupe les accords de trois notes générés par les
degrés des modes naturels. La lettre *M* signifie accord parfait
majeur et la lettre *m* accord parfait mineur. Le symbole *dim*
signifie ici accord de quinte diminuée :

| Modes      |     | Degrés |     |     |     |     |     |     |
|            |     | 4      | 1   | 5   | 2   | 6   | 3   | 7   |
|------------+-----+--------+-----+-----+-----+-----+-----+-----|
| lydien     | fa  | dim    | M   | M   | M   | m   | m   | m   |
| ionien     | do  | M      | M   | M   | m   | m   | m   | dim |
| mixolydien | sol | M      | M   | m   | m   | m   | dim | M   |
| dorien     | ré  | M      | m   | m   | m   | dim | M   | M   |
| éolien     | la  | m      | m   | m   | dim | M   | M   | M   |
| phrygien   | mi  | m      | m   | dim | M   | M   | M   | m   |
| locrien    | si  | m      | dim | M   | M   | M   | m   | m   |

Parmi les modes naturels, les modes ionien et éolien sont les seuls à
présenter le même type d’accords sur les degrés forts 4, 1, 5. Le mode
ionien produit des accords parfaits majeurs, tandis que le mode éolien
produit des accords parfaits mineurs :

| Modes  | Degrés |   |   |
|        | 4      | 1 | 5 |
|--------+--------+---+---|
| ionien | M      | M | M |
| éolien | m      | m | m |

Pour cette raison :

  - le mode ionien est aussi appelé *mode majeur*
  - le mode éolien est aussi appelé *mode mineur*

Exemple de mode majeur avec la gamme de /do majeur/ :

#+begin_center
do ré mi fa sol la si do
#+end_center

Exemple de mode mineur avec la gamme de /la mineur/ :

#+begin_center
la si do ré mi fa sol la
#+end_center

** Tonalités modèles

La tonalité modèle du mode :

  - majeur correspond à la gamme modèle du mode ionien
  - mineur correspond à la gamme modèle du mode éolien

| Mode   | Nom médiéval | Tonalité modèle          |
|--------+--------------+--------------------------|
| majeur | ionien       | do ré mi fa sol la si do |
| mineur | éolien       | la si do ré mi fa sol la |

** Adaptations du mineur

#+TOC: headlines 1 local

*** Mineur harmonique

Le mode majeur dispose d’une sensible inférieure. Par exemple, en /do
majeur/, la sensible inférieure est le /si/, à un demi-ton de la
tonique /do/.

En mode mineur par contre, les degrés 2 et 7 sont situés à un ton
entier de la tonique : ce mode ne possède donc pas de sensible. On
peut toutefois y remédier en haussant la sous-tonique d’un demi-ton,
obtenant ainsi un mode dérivé, appelé *mode mineur harmonique*. Par
exemple, en /la mineur/, le /sol/ sera haussé d’un demi-ton, donnant
ainsi la gamme :

#+begin_center
la si do ré mi fa sol^{#} la
#+end_center

Dans la suite, le mode mineur par défaut sera généralement le mode
mineur harmonique.

*** Mineur ascendant et descendant

Le mode mineur harmonique sonne très bien, disposant à la fois de la
sonorité du mode mineur et de l’attirance de la sensible inférieure.
Cependant, l’écart de seconde augmentée entre les degrés 6 et 7 n’est
pas toujours souhaitable. Dans ce cas, on hausse le degré 6, obtenant
un mode appelé *mode mineur ascendant*. Exemple, le /la mineur
ascendant/ :

#+begin_center
la si do ré mi fa^{#} sol^{#} la
#+end_center

Par opposition, on appelle alors *mode mineur descendant* le mode
mineur naturel (le mode éolien). En pratique, les modes mineurs
(harmonique, ascendant et descendant) sont souvent mêlés, donnant
ainsi beaucoup de couleur et de souplesse à la musique. Enfin, le
degré 3 peut lui aussi être haussé d’un demi-ton, complétant ainsi le
caractère polymorphe du mode mineur, qui peut se rapprocher ou même se
confondre avec le mode majeur.

*** Conclusion

Le mode mineur est très versatile, et ses altérations flottantes
donnent une couleur particulière à la musique.

** Degrés & intervalles caractéristiques

Les modes majeur et mineur sont les modes les plus utilisés. On s’en
sert donc comme référence pour souligner les *degrés caractéristiques*
des autres modes. Ces degrés forment des *intervalles
caractéristiques* avec la tonique.

*** Autour du mode majeur

En partant de /do majeur/, les quintes voisines nous donnent les
gammes de /sol mixolydien/ et /fa lydien/.

Si nous transposons la gamme de /sol mixolydien/ vers la tonique /do/,
nous obtenons la gamme de /do mixolydien/ :

#+begin_center
do ré mi fa sol la /si^b/ do
#+end_center

La note caractéristique du mode mixolydien est donc le /si^b/,
septième degré formant un intervalle de septième mineure avec la
tonique.

Si nous transposons la gamme de /fa lydien/ vers la tonique /do/,
nous obtenons la gamme de /do lydien/ :

#+begin_center
do ré mi /fa^{#}/ sol la si do
#+end_center

La note caractéristique du mode lydien est donc le /fa^{#}/, quatrième
degré formant un intervalle de quarte augmentée avec la tonique.

*** Autour du mode mineur

En partant de /la mineur/, les quintes voisines nous donnent les
gammes de /mi phrygien/ et /ré dorien/.

Si nous transposons la gamme de /mi phrygien/ vers la tonique /la/,
nous obtenons la gamme de /la phrygien/ :

#+begin_center
la /si^b/ do ré mi fa sol la
#+end_center

La note caractéristique du mode phrygien est donc le /si^b/, deuxième
degré formant un intervalle de seconde mineure avec la tonique.

Si nous transposons la gamme de /ré dorien/ vers la tonique /la/, nous
obtenons la gamme de /la dorien/ :

#+begin_center
la si do ré mi /fa^{#}/ sol la
#+end_center

La note caractéristique du mode dorien est donc le /fa^{#}/, sixième
degré formant un intervalle de sixte majeure avec la tonique.

Nous n’avons pas encore exploré le mode locrien. Partons de la gamme
de /si locrien/ et transposons vers la tonique /la/, deux quintes plus
bas. Nous obtenons la gamme de /la locrien/ :

#+begin_center
la si^b do ré mi^b fa sol la
#+end_center

Les notes caractéristiques du mode locrien sont donc le /si^b/ et le
/la^b/, deuxième et cinquième degré formant des intervalles de seconde
mineure et quinte diminuée avec la tonique.

*** Récapitulation

| Modes           |           Degré | Intervalle      |
|                 | caractéristique | caractéristique |
|-----------------+-----------------+-----------------|
| lydien          |               4 | 4te augmentée   |
| ionien (Majeur) |                 | —               |
| mixolydien      |               7 | 7e mineure      |
|-----------------+-----------------+-----------------|
| dorien          |               6 | 6te majeure     |
| éolien (Mineur) |                 | —               |
| phrygien        |               2 | 2de mineure     |
|-----------------+-----------------+-----------------|
| locrien         |               2 | 2de mineure     |
|                 |               5 | 5te diminuée    |

* Autres modes

#+TOC: headlines 1 local

** Introduction

Nous avons déjà vu les modes naturels, le majeur et le mineur. Ce
chapitre recense les autres modes disponibles.

** Construire de nouveaux modes

La technique la plus simple consiste à construire les gammes relatives
d’un mode existant. Chaque nouvelle gamme ainsi obtenue peut alors
être considérée comme la gamme modèle d’un nouveau mode.

Chaque mode heptaphonique nous donnera ainsi six nouveaux modes,
construits à partir des degrés 2 à 7.

Chaque mode pentaphonique nous donnera ainsi quatre nouveaux modes,
construits à partir des degrés 2 à 5.

Chaque mode tetraphonique nous donnera ainsi trois nouveaux modes,
construits à partir des degrés 2 à 4.

** Heptaphoniques

#+TOC: headlines 1 local

*** Acoustique

Le mode acoustique est construit à partir des premiers éléments de la
série des harmoniques naturelles. Exemple en partant de /do/ :

#+ATTR_HTML: :class plat
| /Notes/ | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |

En ramenant toutes les notes dans la même octave, on obtient :

#+begin_center
do ré mi fa^{#} sol si^b do
#+end_center

Ce mode contient donc une quinte, une tierce majeure, une septième
mineure, une seconde majeure et une quarte augmentée.

On peut bien entendu ajouter la note naturelle manquante, à savoir
le /la/ :

#+begin_center
do ré mi fa^{#} sol la si^b do
#+end_center

La gamme ainsi obtenue possède les mêmes écarts qu’un relatif du mode
mineur ascendant à partir du quatrième degré :

#+begin_center
ré mi fa^{#} sol^{#} la si do ré
#+end_center

*** Superlocrien

Le mode superlocrien est construit comme un relatif du mode mineur
ascendant à partir du septième degré :

#+begin_center
sol^{#} la si do ré mi fa^{#} sol^{#}
#+end_center

Ce mode est appelé superlocrien, car il ressemble fort au mode
locrien. On le voit clairement en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la si
#+end_center

**** Mineur harmonique

Il existe aussi une variante dérivée du mode mineur harmonique :

#+begin_center
sol^{#} la si do ré mi fa sol^{#}
#+end_center

ce qui donne, en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la^b si
#+end_center

*** Tzigane

Le mode tzigane, ou mode hongrois, est un mode dérivé du mineur
harmonique, le 4e degré étant haussé afin de se rapprocher de la
dominante :

#+begin_center
la si do ré^{#} mi fa sol^{#} la
#+end_center

Ce mode est caractérisé par la présence de deux sensibles auxiliaires :

#+begin_center
sensible auxiliaire inférieure —> dominante <— sensible auxiliaire supérieure
#+end_center

Notons les deux écarts de trois demi-tons entre les degrés 3 - 4 et
6 - 7.

*** Andalou

Le mode andalou ressemble au mode phrygien, mais il est caractérisé
par une médiante flottante, formant une tierce majeure ou mineure avec
la tonique :

#+begin_center
mi fa sol^{(#)} la si do ré mi
#+end_center

*** Napolitain

Il s’agit d’un mode ressemblant au mode phrygien, mais où le septième
degré est haussé d’un demi-ton, ce qui le transforme en sensible
inférieure :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

On voit que la sus-tonique est une sensible supérieure. Ce mode est
donc caractérisé par la double attraction :

#+begin_center
sensible inférieure —> tonique <— sensible supérieure
#+end_center

Il en existe une variante où le sixième degré est haussé :

#+begin_center
mi fa sol la si do^{#} ré^{#} mi
#+end_center

*** Oriental

**** Variante phrygienne

Le mode oriental phrygien est un relatif du mode tzigane construit à
partir du cinquième degré :

#+begin_center
mi fa sol^{#} la si do ré^{#} mi
#+end_center

Ce mode est caractérisé par les deux secondes augmentées qui séparent
les degrés 2 — 3 et 6 — 7, ainsi que par la double attraction :

#+begin_center
sensible inférieure —> tonique <— sensible supérieure
#+end_center

Si on souhaite également créer une double attraction vers la
dominante :

#+begin_center
sous-dominante altérée —> dominante <— sous-médiante
#+end_center

il suffit de hausser le degré 4 :

#+begin_center
mi fa sol^{#} la^{#} si do ré^{#} mi
#+end_center

**** Variante locrienne

Le mode oriental locrien est un relatif du mode tzigane construit à
partir du deuxième degré :

#+begin_center
si do ré^{#} mi fa sol^{#} la si
#+end_center

Afin d’obtenir la même propriété de double attraction que la variante
basée sur le mode de /mi/, on peut sensibiliser le degré 7 en le
haussant d’un demi-ton :

#+begin_center
si do ré^{#} mi fa sol^{#} la^{#} si
#+end_center

** Pentaphoniques

Les modes pentaphoniques sont des gammes de cinq notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
cinq quintes :

#+begin_center
do sol ré la mi
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode pentaphonique :

#+begin_center
do ré mi sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do  | ré | mi  | sol |
| sur ré  | : | ré  | mi  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré  | mi | sol | la  |
| sur mi  | : | mi  | sol | la  | do | ré  | mi  |

*** Avec caractéristique

Ce sont des modes pentaphoniques que l’on altère afin d’intégrer une
ou plusieurs notes caractéristiques des modes naturels. Par exemple,
ce mode pentaphonique altéré :

#+begin_center
ré mi sol^{#} la do ré
#+end_center

possède une quarte haussée, caractéristique du mode lydien.

*** Blues

Le mode blues est un mode pentaphonique développant les quintes à
partir de la médiante. La médiante, la dominante et la sous-tonique
sont flottantes. Par exemple, avec /la/ comme tonique, nous avons :

#+begin_center
la do^{(#)} ré mi^{(b)} sol^{(#)} la
#+end_center

*** Chinois

Le mode chinois est un mode pentaphonique développant les quintes à
partir de la tonique. Par exemple, avec /do/ comme tonique, nous
obtenons :

#+begin_center
do ré mi sol la do
#+end_center

*** Japonais

Le mode japonais est un mode pentaphonique développant les quintes à
partir de la sous-dominante. La gamme modèle de ce mode possède un
/mi/ pour tonique. On part alors de la sous-dominante /la/ et on
gravit les quintes entre notes naturelles :

#+begin_center
la mi si fa do
#+end_center

En disposant ces notes sur une octave /mi — mi^{+1}/ et en les
ordonnant de la plus grave à la plus aiguë, nous obtenons :

#+begin_center
mi fa la si do mi
#+end_center

La dominante auxiliaire /fa/ est une sensible supérieure. Ce mode
possède un autre demi-ton entre la dominante /si/ et la sous-médiante
/do/.

Notons également l’intervalle de quarte augmentée /si — fa/ qui sépare
la sus-tonique de la dominante.

** Tétraphoniques

Les modes tetraphoniques sont des gammes de quatre notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
quatre quintes :

#+begin_center
do sol ré la
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode tetraphonique :

#+begin_center
do ré sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do | ré  | sol |
| sur ré  | : | ré  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré | sol | la  |

* Accords classés

#+TOC: headlines 1 local

** Introduction

Les accords classés sont des accords naturellement engendrés par les
gammes lorsqu’on y superpose des tierces.

*** Nomenclature

Une *septième de dominante* est un accord de quatre notes dont la
fondamentale est placée sur la dominante.

Une *septième d’espèce* est un accord de quatre notes dont la
fondamentale n’est pas placée sur la dominante.

On utilise les abréviations suivantes :

| Accord                | Abréviation |
|-----------------------+-------------|
| septième de dominante | 7e D        |
| septième d’espèce     | 7e E        |

** Tonique

Les accords de tonique les plus utilisés sont des accords parfaits
majeur ou mineur. On rencontre aussi des septièmes d’espèce, comme
dans ces exemples :

| Accords             | Abréviations | Exemples             |                  |
|                     |              | Gammes               | Accords          |
|---------------------+--------------+----------------------+------------------|
| septième majeure    | 7e M         | do majeur            | do mi sol si     |
| septième mineure    | 7e m         | la mineur            | la do mi sol     |
| septième harmonique | 7e h         | la mineur harmonique | la do mi sol^{#} |

et plus rarement des accords de 5, 6 ou 7 notes.

*** Quinte augmentée

Si nous supprimons la fondamentale de l’accord de septième harmonique,
nous obtenons un accord dit de *quinte augmentée* :

| Accords          | Abréviations | Exemples      |
|------------------+--------------+---------------|
| quinte augmentée | 5te aug      | do mi sol^{#} |

** Dominante

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante sont très importants, de par leur fonction
tonale dynamique et parce qu’ils sont naturellement attirés par un
accord de tonique.

*** Triades

En empilant deux tierces, on obtient un accord parfait majeur, que ce
soit en mode majeur ou mineur harmonique :

| Accords        | Abréviations | Exemples             |               |
|                |              | Gammes               | Accords       |
|----------------+--------------+----------------------+---------------|
| parfait majeur | M            | do majeur            | sol si ré     |
| parfait majeur | M            | la mineur harmonique | mi sol^{#} si |

*** Septième

En empilant trois tierces, on obtient l’accord de septième de
dominante, dont la structure est identique en majeur et en mineur
harmonique :

| Accords               | Abréviations | Exemples             |                  |
|                       |              | Gammes               | Accords          |
|-----------------------+--------------+----------------------+------------------|
| septième de dominante | 7e D         | do majeur            | sol si ré fa     |
| septième de dominante | 7e D         | la mineur harmonique | mi sol^{#} si ré |

Dans les deux cas :

  - la première tierce est majeure
  - les deux tierces suivantes sont mineures

Avec les accords parfaits majeur et mineur, la septième de dominante
figure parmi les accords les plus importants de l’harmonie tonale.

**** Quinte diminuée

Lorsqu’on prive un accord de dominante de sa fondamentale, on obtient
un accord de *quinte diminuée* :

| Accords         | Abréviations | Exemples             |               |
|                 |              | Gammes               | Accords       |
|-----------------+--------------+----------------------+---------------|
| quinte diminuée | 5te dim      | do majeur            | si ré fa      |
| quinte diminuée | 5te dim      | la mineur harmonique | sol^{#} si ré |

*** Neuvième

En empilant quatre tierces, on obtient la *neuvième de dominante*,
majeure ou mineure suivant le mode :

| Accords                       | Abréviations | Exemples             |                     |
|                               |              | Gammes               | Accords             |
|-------------------------------+--------------+----------------------+---------------------|
| neuvième de dominante majeure | 9e D M       | do majeur            | sol si ré fa la     |
| neuvième de dominante mineure | 9e D m       | la mineur harmonique | mi sol^{#} si ré fa |

**** Septième et quinte diminuée

Lorsqu’on prive une neuvième de dominante majeure de sa fondamentale,
on obtient un accord de *septième et quinte diminuée* :

| Accords                     | Abréviations | Exemples  |             |
|                             |              | Gammes    | Accords     |
|-----------------------------+--------------+-----------+-------------|
| septième et quinte diminuée | 7e & 5te dim | do majeur | si ré fa la |

**** Septième diminuée

Lorsqu’on prive une neuvième de dominante mineure de sa fondamentale,
on obtient un accord de *septième diminuée* :

| Accords           | Abréviations | Exemples             |                  |
|                   |              | Gammes               | Accords          |
|-------------------+--------------+----------------------+------------------|
| septième diminuée | 7e dim       | la mineur harmonique | sol^{#} si ré fa |

** Sous-dominante

Les accords de sous-dominante sont similaires aux accords de tonique :
accords parfaits et septièmes majeures ou mineures. Exemples :

| Accords | Exemples  |             |
|         | Gammes    | Accords     |
|---------+-----------+-------------|
| 7e M    | do majeur | fa la do mi |
| 7e m    | la mineur | ré fa la do |

** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: heading:dominanteAuxiliaire
:END:

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante auxiliaire sont similaires aux accords de
dominante, si ce n’est qu’ils sont construits sur le degré 2 de la
gamme. Afin de renforcer le rôle de ces accords, il est possible de
les altérer en faisant /comme si/ la dominante de la gamme courante
devenait la tonique. On utilise les abréviations :

| Accords                          | Abréviations |
|----------------------------------+--------------|
| triade de dominante auxiliaire   | 3ade Daux    |
| septième de dominante auxiliaire | 7e Daux      |
| neuvième de dominante auxiliaire | 9e Daux      |

*** Majeur

Nous prenons comme illustration la gamme de /do majeur/. Nous obtenons
par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| do ré mi fa sol la si do | —> | sol la si do ré mi fa^{#} sol |

L’altération haussière du /fa^{#}/ (degré 4 par rapport à la tonique
/do/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /sol/.

On peut également altérer le /la/ (degré 6 par rapport à la tonique
/do/) vers le bas afin de le transformer en sensible auxiliaire
supérieure. Nous avons alors la gamme :

#+begin_center
sol la^b si do ré mi fa^{#} sol
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en do majeur |
|-------------------------+-----------+-----------------------|
| aucune                  | 3ade Daux | ré fa la              |
|                         | 7e Daux   | ré fa la do           |
|                         | 9e Daux   | ré fa la do mi        |
| inférieure              | 3ade Daux | ré fa^{#} la          |
|                         | 7e Daux   | ré fa^{#} la do       |
|                         | 9e Daux   | ré fa^{#} la do mi    |
| inférieure & supérieure | 3ade Daux | ré fa^{#} la^b        |
|                         | 7e Daux   | ré fa^{#} la^b do     |
|                         | 9e Daux   | ré fa^{#} la^b do mi  |

*** Mineur harmonique

Nous prenons comme illustration la gamme de /la mineur harmonique/.
Nous obtenons par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| la si do ré mi fa sol^{#} la | —> | mi fa^{#} sol la si do ré^{#} mi |

L’altération haussière du /ré^{#}/ (degré 4 par rapport à la tonique
/la/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /mi/.

Si on supprime l’altération haussière du /fa^{#}/ (degré 6 par rapport
à la tonique /la/), on transforme ce degré en sensible auxiliaire
supérieure de la dominante /mi/. Nous obtenons alors la gamme :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en la mineur harmonique |
|-------------------------+-----------+----------------------------------|
| supérieure              | 2ade Daux | si ré fa                         |
|                         | 7e Daux   | si ré fa la                      |
|                         | 9e Daux   | si ré fa la do                   |
| inférieure              | 3ade Daux | si ré^{#} fa^{#}                 |
|                         | 7e Daux   | si ré^{#} fa^{#} la              |
|                         | 9e Daux   | si ré^{#} fa^{#} la do           |
| inférieure & supérieure | 3ade Daux | si ré^{#} fa                     |
|                         | 7e Daux   | si ré^{#} fa la                  |
|                         | 9e Daux   | si ré^{#} fa la do               |

Remarquons en passant que la triade de dominante auxiliaire non
altérée est un accord de quinte diminuée.

*** Sans fondamentale

Tout comme les accords de dominante, les accords de dominante
auxiliaire sont parfois présentés sans leur fondamentale. On obtient
alors des accords qui semblent être du degré 4, les fonctions de
dominante auxiliaire et de sous-dominante se voyant ainsi intimement
liées.

Exemple en /do majeur/ :

| Sensibles auxiliaires   | Accords | Exemples en do majeur |
|-------------------------+---------+-----------------------|
| aucune                  | 7e Daux | fa la do              |
|                         | 9e Daux | fa la do mi           |
| inférieure              | 7e Daux | fa^{#} la do          |
|                         | 9e Daux | fa^{#} la do mi       |
| inférieure & supérieure | 7e Daux | fa^{#} la^b do        |
|                         | 9e Daux | fa^{#} la^b do mi     |

Exemple en /la mineur harmonique/ :

| Sensibles auxiliaires   | Accords | Exemples en la mineur harmonique |
|-------------------------+---------+----------------------------------|
| supérieure              | 7e Daux | ré fa la                         |
|                         | 9e Daux | ré fa la do                      |
| inférieure              | 7e Daux | ré^{#} fa^{#} la                 |
|                         | 9e Daux | ré^{#} fa^{#} la do              |
| inférieure & supérieure | 7e Daux | ré^{#} fa la                     |
|                         | 9e Daux | ré^{#} fa la do                  |

*** Sixtes augmentées

#+TOC: headlines 1 local

**** Introduction

Les accords de *sixte augmentée* sont des accords de dominante
auxiliaire renversés. Ils sont altérés de sorte qu’ils présentent un
intervalle caractéristique de sixte augmentée, d’où leur nom.

**** Sixte française

La *sixte française* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est présentée sous la forme d’un
second renversement.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| ré fa^{#} la^b do | —> | la^b do ré fa^{#} |

En /la mineur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| si ré^{#} fa la | —> | fa la si ré^{#} |

**** Sixte italienne

La *sixte italienne* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (ré) fa^{#} la^b do | —> | la^b do (ré) fa^{#} |

ce qui nous donne finalement :

#+begin_center
la^b do fa^{#}
#+end_center

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la | —> | fa la (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la ré^{#}
#+end_center

**** Sixte allemande

La *sixte allemande* est une neuvième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la do | —> | fa la do (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la do ré^{#}
#+end_center

L’accord altéré de /do majeur/ respectant les mêmes écarts s’écrit :

#+begin_center
la^b do mi^b fa^{#}
#+end_center

** Emprunts

#+TOC: headlines 1 local

*** Introduction

Un emprunt est un accord provenant d’une autre gamme (tonique et/ou
mode) que l’on insère dans la gamme courante.

*** Majeur <——> Mineur

On peut placer des accords caractéristiques du mineur (quintes
augmentées, septièmes diminuées, ...) dans des gammes majeures, ou
l’inverse.

*** Tierces picardes

Une *tierce picarde* est un accord parfait majeur intégré à un autre
mode. On la rencontre souvent sur les degrés 1, 5, ou 4 du mode
mineur : la tierce de l’accord y est rendue majeure par une altération
haussière. Voici des exemples en /la mineur/ :

| Degrés | Exemples      |
|--------+---------------|
|      1 | la do^{#} mi  |
|      4 | ré fa^{#} la  |
|      5 | mi sol^{#} si |

*** Napolitain

En gamme de /mi napolitain/, l’accord de dominante auxiliaire non
altéré :

#+begin_center
fa la do
#+end_center

est un accord parfait majeur situé un demi-ton au-dessus de la tonique
/mi/. Par extension, on appelle accord *napolitain* tout accord défini
par les mêmes propriétés, et ce quels que soient le mode et la
tonique. Voici ce que cela donne en majeur et en mineur :

| do majeur    | la mineur  |
|--------------+------------|
| ré^b fa la^b | si^b ré fa |

Lorsque cet accord est présenté sous la forme de premier renversement,
il est appelé *sixte napolitaine* :

| do majeur    | la mineur  |
|--------------+------------|
| fa la^b ré^b | ré fa si^b |

Afin de former un accord similaire à une 7e de dominante, on peut
ajouter une note de 7e mineure à l’accord napolitain :

| do majeur         | la mineur       |
|-------------------+-----------------|
| ré^b fa la^b do^b | si^b ré fa la^b |

Ces derniers accords sont aussi appelés *substitution au triton*, ou
*substitution tritonique* à cause de l’intervalle de triton qui lie la
dominante auxiliaire altérée vers le bas avec la dominante.

** Modes composites

Un *mode composite* associe à chaque degré une liste d’accords qui lui
sont caractéristiques. Voici un exemple de mode composite proche du
/la mineur/ :

| Degrés | Accords                     | Exemples             |
|--------+-----------------------------+----------------------|
|      1 | parfait mineur              | la do mi             |
|        | parfait majeur              | la do^{#} mi         |
|      2 | 7e Daux                     | si ré fa la          |
|        |                             | si ré^{#} fa la      |
|        | napolitains                 | si^b ré fa           |
|        |                             | si^b ré fa la^b      |
|      3 | quinte augmentée            | do mi sol^{#}        |
|      4 | parfait mineur              | ré fa la             |
|        | parfait majeur              | ré fa^{#} la         |
|      5 | septième de dominante       | mi sol^{#} si ré     |
|        | neuvième de dominante       | mi sol^{#} si ré fa  |
|      6 | parfait majeur              | fa la do             |
|        | quinte diminuée             | fa^{#} la do         |
|      7 | quinte diminuée             | sol^{#} si ré        |
|        | septième diminuée           | sol^{#} si ré fa     |
|        | septième et quinte diminuée | sol^{#} si ré fa^{#} |

Cette variété d’accords implique qu’une partie ou la totalité des
notes de la gamme peut être altérée vers le haut ou vers le bas en
fonction du contexte.

** Tableau récapitulatif

#+TOC: headlines 1 local

*** Issus du majeur

| Accord                        | Exemple             | 3ces     |
|                               |                     | empilées |
|-------------------------------+---------------------+----------|
| parfait majeur                | do mi sol           | M m      |
| sixte                         | mi sol do           |          |
| quarte & sixte                | sol do mi           |          |
|-------------------------------+---------------------+----------|
| septième de dominante         | sol si ré fa        | M m m    |
| quinte diminuée               | si ré fa            | m m      |
| neuvième de dominante majeure | sol si ré fa la     | M m m M  |
| septième et quinte diminuée   | si ré fa la         | m m M    |
|-------------------------------+---------------------+----------|
| septième majeure              | do mi sol si        | M m M    |
|-------------------------------+---------------------+----------|
| dominante auxiliaire          | ré fa^{#} la        |          |
| sixte française               | la^b do ré fa^{#}   |          |
| sixte italienne               | la^b do fa^{#}      |          |
| sixte allemande               | la^b do mi^b fa^{#} |          |
| napolitain                    | ré^b fa la^b        |          |
| sixte napolitaine             | fa la^b ré^b        |          |

*** Issus du mineur

| Accord                        | Exemple              | 3ces     |
|                               |                      | empilées |
|-------------------------------+----------------------+----------|
| parfait mineur                | la do mi             | m M      |
| sixte                         | do mi la             |          |
| quarte & sixte                | mi la do             |          |
|-------------------------------+----------------------+----------|
| septième de dominante         | mi sol^{#} si ré     | M m m    |
| quinte diminuée               | sol^{#} si ré        | m m      |
| neuvième de dominante mineure | mi sol^{#} si ré fa  | M m m m  |
| septième diminuée             | sol^{#} si ré fa     | m m m    |
|-------------------------------+----------------------+----------|
| septième harmonique           | la do mi sol^{#}     | m M M    |
| quinte augmentée              | do mi sol^{#}        | M M      |
| septième mineure              | la do mi sol         | m M m    |
|-------------------------------+----------------------+----------|
| dominante auxiliaire          | si ré^{(#)} fa^{(#)} |          |
| sixte française               | fa la si ré^{#}      |          |
| sixte italienne               | fa la ré^{#}         |          |
| sixte allemande               | fa la do ré^{#}      |          |
| napolitain                    | si^b ré fa           |          |
| sixte napolitaine             | ré fa si^b           |          |

* Accords à base de quintes

#+TOC: headlines 1 local

** Triades

Si on superpose deux quintes, on obtient une triade que nous décidons
de nommer accord de *double quinte* :

| Accords       | Exemples  |
|---------------+-----------|
| double quinte | do sol ré |

En permutant les notes afin de les rapprocher, nous obtenons d’autres
dispositions de cet accord :

| Accords           | Exemples  |
|-------------------+-----------|
| double quarte     | ré sol do |
|-------------------+-----------|
| quarte et quinte  | sol do ré |
| seconde et quinte | do ré sol |

Ces accords sont nommés, suivant les cas :

  - d’après les intervalles entre les notes consécutives
  - d’après les intervalles qui séparent les notes de la basse

Synonymes courants :

  - l’accord de quarte et quinte se nomme aussi accord de *quarte suspendue*.
  - l’accord de seconde et quinte se nomme aussi accord de *seconde suspendue*.

** Tétrades

Les accords de quatre notes sont construits en superposant trois
quintes. Voici quelques dispositions possibles de ces accords :

| Accords        | Exemples     |
|----------------+--------------|
| triple quinte  | do sol ré la |
| triple quarte  | la ré sol do |
|----------------+--------------|
| 2de, 4te & 5te | sol la do ré |
| 4te, 5te & 9e  | sol do ré la |

Ces dispositions d’accords ressemblent aux modes tétraphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
tétraphonique.

** Pentades

Les accords de cinq notes sont construits en superposant quatre
quintes. Voici quelques dispositions possibles :

| Accords             | Exemples        |
|---------------------+-----------------|
| quadruple quinte    | do sol ré la mi |
| quadruple quarte    | mi la ré sol do |
|---------------------+-----------------|
| 3ce, 4te, 5te & 7e  | la do ré mi sol |
| 2de, 4te, 5te & 6te | sol la do ré mi |
| 4te, 5te, 6te & 9e  | sol do ré mi la |

Ces dispositions d’accords ressemblent aux modes pentaphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
pentaphonique.

** Tableau récapitulatif

| Accord              | Exemple         |
|---------------------+-----------------|
| double quinte       | do sol ré       |
| double quarte       | ré sol do       |
|---------------------+-----------------|
| quarte & quinte     | sol do ré       |
| seconde & quinte    | do ré sol       |
|---------------------+-----------------|
| triple quinte       | do sol ré la    |
| triple quarte       | la ré sol do    |
|---------------------+-----------------|
| 2de, 4te & 5te      | sol la do ré    |
| 4te, 5te & 9e       | sol do ré la    |
|---------------------+-----------------|
| quadruple quinte    | do sol ré la mi |
| quadruple quarte    | mi la ré sol do |
|---------------------+-----------------|
| 3ce, 4te, 5te & 7e  | la do ré mi sol |
| 2de, 4te, 5te & 6te | sol la do ré mi |
| 4te, 5te, 6te & 9e  | sol do ré mi la |

* Dualité tonale

#+TOC: headlines 1 local

** Couple tonal

La musique tonale se base essentiellement sur la dualité
dominante — tonique. Le *couple tonal* est un enchaînement qui met en
évidence cette dualité en faisant entendre les deux fonctions.
L’accord faisant fonction de tonique, de par son caractère conclusif,
se place après l’accord faisant fonction de dominante :

#+ATTR_HTML: :class plat
| dominante | — | tonique |

Le couple tonal est également caractérisé par la descente de quinte
qui mène du premier accord au second.

** Couple plagal

Le *couple plagal* est un peu le miroir du couple tonal : au lieu de
descendre d’une quinte pour aboutir à la tonique, l’enchaînement monte
d’une quinte. On doit donc partir de la quinte inférieure,
c’est-à-dire de la sous-dominante :

#+ATTR_HTML: :class plat
| sous-dominante | — | tonique |

** Dualité tonale mélodique

Le couple tonal peut servir à construire des mélodies qui se
répondent.

Ainsi, on peut écrire une mélodie originale dont l’ambitus s’étend
approximativement de la tonique à la dominante. La mélodie duale
s’étendra alors une quinte plus haut, de la dominante jusqu’à la
sus-tonique. Un retour de la mélodie duale à la mélodie originale sera
alors percue comme une descente de quinte.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| do - sol          | sol - ré      |

Si l’ambitus de la mélodie originale s’étend de la tonique à la
sous-dominante, la mélodie duale s’étendra de la dominante jusqu’à la
tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| do - fa           | sol - do      |

Enfin, on peut construire un cas intermédiaire où la mélodie originale
s’étend de la tonique à la dominante, tandis que la mélodie duale
s’étend de la dominante à la tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| do - sol          | sol - do      |

Nous verrons une application importante de ce cas particulier lorsque
nour parlerons des [[file:musica-08-clechant.org::#heading:mutation][mutations]].

** Dualité plagale mélodique

Le couple plagal peut servir à construire des mélodies qui se
répondent.

Ainsi, on peut écrire une mélodie originale dont l’ambitus s’étend
approximativement de la tonique à la dominante. La mélodie duale
s’étendra alors une quinte plus bas, de la sous-dominante jusqu’à la
tonique. Un retour de la mélodie duale à la mélodie originale sera
alors percue comme une montée de quinte.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| la - mi           | ré - la       |

Si l’ambitus de la mélodie originale s’étend de la tonique à la
sous-dominante, la mélodie duale s’étendra de la sous-dominante
jusqu’à la sous-tonique.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| la - ré           | ré - sol      |

Enfin, on peut construire un cas intermédiaire où la mélodie originale
s’étend de la tonique à la sous-dominante, tandis que la mélodie duale
s’étend de la sous-dominante à la tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| la - ré           | ré - la       |

Nous verrons une application importante de ce cas particulier lorsque
nour parlerons des [[file:musica-08-clechant.org::#heading:mutation][mutations]].

** Couple tonal pentatonique

Il s’agit d’un couple tonal où les accords utilisés comportent cinq
notes et sont construits en empilant des quintes. On élabore alors
deux petites mélodies :

  - la première utilise les notes d’un mode pentatonique établi sur la
    dominante
  - la seconde utilise les notes d’un mode pentatonique établi sur la
    tonique

Exemple de modes pentatoniques en /la mineur/ :

#+ATTR_HTML: :class plat
| dominante          | tonique            |
| mi sol la si ré mi | la do ré mi sol la |

Cette technique est notamment utilisée dans le blues et le jazz.

** Couple plagal pentatonique

Il s’agit d’un couple plagal où les accords utilisés comportent cinq
notes et sont construits en empilant des quintes. On élabore alors
deux petites mélodies :

  - la première utilise les notes d’un mode pentatonique établi sur la
    sous-dominante
  - la seconde utilise les notes d’un mode pentatonique établi sur la
    tonique

Exemple de modes pentatoniques en /la mineur/ :

#+ATTR_HTML: :class plat
| sous-dominante     | tonique            |
| ré fa sol la do ré | la do ré mi sol la |

* Tonalité secondaire

#+TOC: headlines 1 local

** Introduction

On peut renforcer le rôle du degré /X/ de la tonalité principale en le
considérant comme une *tonique secondaire*. La tonalité construite sur
ce degré /X/ s’appelle alors *tonalité secondaire*.

Une fonction tonale d’une tonalité secondaire est appelée *fonction
secondaire* et notée :

#+begin_center
Fonction de /X/
#+end_center

*** Degrés

Un accord construit sur le degré /Y/ de la tonique secondaire
correspondant au degré /X/ est noté :

#+begin_center
/Y/ de /X/
#+end_center

** Fonctions secondaires

#+TOC: headlines 1 local

*** Dominante secondaire

La *dominante secondaire* basée sur le degré /X/ de la tonalité
principale s’obtient en considérant /X/ comme une tonique secondaire
et en exprimant sa dominante :

#+begin_center
Dominante de /X/
#+end_center

Prenons par exemple /do majeur/ comme tonalité principale et
sélectionnons le degré 2, le /ré/, comme tonique secondaire. Si nous
décidons de lui appliquer le mode majeur, nous obtenons la tonalité
secondaire de /ré majeur/, qui est située une seconde majeure plus
haut que la principale. Le [[file:musica-01-monocorde.org::#heading:recapitulationTranspositionQuintes][tableau des transpositions]] nous donne alors
les altérations /fa^{#}/ et /do^{#}/. Une quinte plus haut que le
/ré/, nous avons le /la/ au degré 6, qui correspond à la dominante
secondaire :

#+ATTR_HTML: :class plat
| noms   | : | tonique principale | tonique secondaire | dominante secondaire |
| degrés | : |                  1 |                  2 |                    6 |

Nous choisissons un accord 5 de 2 pour la représenter :

#+begin_center
la do^{#} mi
#+end_center

*** Sous-dominante secondaire

La *sous-dominante secondaire* basée sur le degré /X/ de la gamme
courante s’obtient en considérant /X/ comme une tonique secondaire et
en exprimant sa sous-dominante :

#+begin_center
Sous-dominante de /X/
#+end_center

** Tonicisation

La tonicisation consiste à mettre en évidence le caractère de tonique
secondaire d’un degré /X/ en jouant le couple tonal secondaire :

#+ATTR_HTML: :class plat
| ( dominante | — | tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| dominante de /X/ | — | tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| dominante de /X/ | — | /X/ |

L’accord parfait sera :

  - majeur si on souhaite mettre en évidence une tonalité secondaire majeure
  - mineur si on souhaite mettre en évidence une tonalité secondaire mineure

*** Sous-dominante secondaire

Une alternative consiste à jouer le couple plagal secondaire :

#+ATTR_HTML: :class plat
| ( sous-dominante | — | tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| sous-dominante de /X/ | — | tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| sous-dominante de /X/ | — | /X/ |

** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: heading:dominanteAuxiliaire
:END:

La *dominante auxiliaire* est la dominante secondaire obtenue en
choisissant la dominante principale comme tonique secondaire. En
d’autres termes, la dominante auxiliaire correspond à la dominante de
la dominante, située deux quintes plus haut que la tonique principale
dans le cycle des quintes :

#+ATTR_HTML: :class plat
| noms         | : | tonique principale | dominante principale | dominante auxiliaire |
| abréviations | : | T                  | D                    | Daux                 |
| degrés       | : | 1                  | 5                    | 2                    |

La dominante auxiliaire est la fonction secondaire la plus utilisée
car elle permet de réaliser le couple tonal secondaire :

#+begin_center
Daux — D
#+end_center

qui renforce la dominante principale. Enfin, un accord du degré 2 peut
être disposé pour assurer une fonction tonale de sous-dominante ou de
dominante auxiliaire, reliant ainsi les deux fonctions.

** Dominante de la sous-dominante

#+TOC: headlines 1 local

*** Majeur

Nous allons à présent étudier la dominante de la sous-dominante.
Supposons par exemple que nous voulions renforcer le rôle de la
sous-dominante de /do majeur/, c’est-à-dire du /fa/. Notre accord doit
donc s’intégrer à la tonalité de /fa majeur/, qui possède un /si^b/
comme altération  :

#+begin_center
fa sol la si^b do ré mi fa
#+end_center

La dominante de cette gamme étant le /do/, la première idée est
d’utiliser la triade :

#+begin_center
do mi sol
#+end_center

mais cet accord ne met pas en évidence l’altération /si^b/ et ne se
différencie donc pas d’un accord parfait de tonique de /do majeur/. On
utilisera donc plutôt un accord d’au minimum quatre notes :

#+begin_center
do mi sol si^b
#+end_center

*** Mineur

En mineur, les modifications sont un peu plus compliquées. Plaçons
nous dans la gamme de /la mineur harmonique/, et construisons la
dominante de la sous-dominante. La sous-dominante étant le /ré/, on
doit intégrer cet accord dans la gamme de /ré mineur harmonique/.
Comme nous sommes une quinte plus bas que le /la/, un /si^b/ apparaît,
auquel on doit ajouter la sensible inférieure /do^{#}/ du mineur
harmonique :

#+begin_center
ré mi fa sol la si^b do^{#} ré
#+end_center

La dominante de cette gamme étant le /la/, on utilisera donc :

#+begin_center
la do^{#} mi
#+end_center

ou :

#+begin_center
la do^{#} mi sol
#+end_center

Si on souhaite mettre l’altération /si^b/ en évidence, on utilisera
plutôt l’accord de cinq notes :

#+begin_center
la do^{#} mi sol si^b
#+end_center

** Sensibles

#+TOC: headlines 1 local

*** Sensibles secondaires

Une note située à une distance d’un demi-ton d’une tonique secondaire
crée une attraction mélodique vers cette dernière.

Une *sensible secondaire supérieure* est un degré situé juste
au-dessus d’une tonique secondaire, à un demi-ton de celle-ci.

Une *sensible secondaire inférieure* est un degré situé juste
en-dessous d’une tonique secondaire, à un demi-ton de celle-ci.

*** Sensibles auxiliaires

Une note située à une distance d’un demi-ton de la dominante crée une
attraction mélodique vers cette dernière.

La dominante correspondant au degré 5, les notes qui l’entourent sont
situées aux degrés 4 et 6.

Lorsque le degré 4 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire inférieure*.

Lorsque le degré 6 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire supérieure*.

*** Tableau récapitulatif

| Degrés | Noms                           | Abréviations |
|--------+--------------------------------+--------------|
|      2 | sensible supérieure            | Ssup         |
|      7 | sensible inférieure            | Sinf         |
|      6 | sensible auxiliaire supérieure | SauxSup      |
|      4 | sensible auxiliaire inférieure | SauxInf      |

** Polarisation secondaire

On parle de *polarisation secondaire* lorsqu’un ensemble d’accords
consécutifs remplissent des fonctions secondaires et mettent ainsi en
évidence l’existence d’une tonalité secondaire.

On choisit souvent une note tonale de la gamme principale comme
tonique de la tonalité secondaire. Placer la tonique secondaire sur la
tonique principale revient à identifier les deux gammes et n’apporte
aucun éclairage neuf. La dominante et la sous-dominante sont donc les
choix les plus courants de tonique secondaire.

* Sémantique

#+TOC: headlines 1 local

** Introduction

La fonction tonale d’un accord peut correspondre au degré :

  - de la fondamentale
  - de la basse
  - du soprano
  - d’une éventuelle note redoublée

Un même accord peut donc assurer différentes fonctions tonales,
suivant qu’une ou l’autre de ses notes est mise en évidence.

Inversément, de nombreux accords peuvent jouer le rôle d’une même
fonction tonale : il suffit de placer la note souhaitée en évidence.
Ce procédé permet de choisir au mieux accords et dispositions afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.

*** Suppression

Parfois, la fondamentale est supprimée mais correspond malgré tout à
la fonction tonale de l’accord. On parle alors de *fonction
implicite*.

/Remarque/ : ce raisonnement scabreux vise à considérer l’enchaînement
des degrés 7 - 1 comme une suite de fonctions dominante - tonique. Je
vous le livre ici car il figure dans la théorie harmonique
conventionnelle, mais je n’y souscris pas. Il me semble bien plus
naturel de considérer que l’enchaînement 7 - 1 prend sa source dans la
[[file:musica-04-clavier.org::#heading:cadenceIonienneTroisVoix][cadence ionienne à trois voix]]. Les mouvements contraires qu’elle
contient amènent élégamment la tonique, ce qui justifie sa place parmi
les piliers de l’harmonie tonale.

*** Pédale

Si une pédale est présente, c’est elle qui assure la fonction tonale
pendant toute la durée de son règne. Suivant les cas, on parle de
pédale de tonique, de dominante, ou de sous-dominante.

Idem pour les accords pédale.

*** Accords ornementaux mélodiques

Les accords ornementaux mélodiques n’ont pas de fonction tonale
propre. On considère qu’ils remplissent la même fonction tonale que le
premier accord stratégique qui précède ou qui suit, suivant le
contexte.

** Synonymes

#+TOC: headlines 1 local

*** Introduction

Deux accords distincts remplissant une même fonction tonale sont dit
*synonymes*.

*** Recherche d’accords synonymes

Nous allons considérer un exemple simple afin de bien comprendre le
procédé permettant de découvrir des accords synonymes. Nous
choisissons la note /do/ comme tonique et nous voulons découvrir les
accords pouvant remplir la fonction de dominante. La dominante étant
le /sol/, cette note devra donc pouvoir être mise en évidence. Le
choix le plus évident est un accord du degré 5 avec le /sol/ comme
fondamentale, mais il en existe d’autres.

On peut parcourir le cycle des tierces pour découvrir les autres
accords à base de tierces incluant un /sol/. Pour les triades, cela
nous donne :

  - /sol/ si ré
  - mi /sol/ si
  - do mi /sol/

On voit que les fondamentales de ces accords, /sol/, /mi/ et /do/,
descendent le cycle des tierces.

Il ne nous reste plus qu’à mettre en évidence le /sol/ en le plaçant à
la basse, au soprano ou en le doublant. Nous choissons ici la dernière
option, ce qui nous donne :

  - /sol/ si ré /sol/
  - /sol/ mi /sol/ si
  - /sol/ do mi /sol/

*** Sans fondamentale

Nous pouvons aussi considérer qu’un accord de degré 7 :

#+begin_center
si ré fa =...=
#+end_center

est un accord de degré 5 privé de sa fondamentale :

#+begin_center
(sol) si ré fa =...=
#+end_center

et remplit implicitement une fonction de dominante.

*** Synonymes usuels

Étant donné une note tonale située sur le degré /X/, les synonymes
les plus utilisés sont :

  - les accords du degré /X/
  - les accords dont la fondamentale est située une tierce plus bas que le degré /X/
  - les accords dont la fondamentale est située une quinte plus bas que le degré /X/

En effet, tous ces accords contiennent la note du degré /X/, ce qui
permet de mettre la note tonale en évidence. On ajoute à cela les
accords situés à la tierce supérieure, considérés comme des degrés /X/
sans fondamentale.

Le tableau suivant nous donne les degrés des accords synonymes :

|     quinte |     tierce | degré |     tierce |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
|          4 |          6 |     1 |          3 |
|          7 |          2 |     4 |          6 |
|          1 |          3 |     5 |          7 |

Exemple en /do majeur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| fa         | la         | do    | mi         |
| si         | ré         | fa    | la         |
| do         | mi         | sol   | si         |

Exemple en /la mineur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| ré         | fa         | la    | do         |
| sol        | si         | ré    | fa         |
| la         | do         | mi    | sol        |

*** Les plus courants

Les possibilités les plus couramment employées sont rassemblées dans
ce tableau :

| Fonctions      | Degrés | Exemple      | Exemple      |
|                |        | en do majeur | en la mineur |
|----------------+--------+--------------+--------------|
| tonique        |      1 | do           | la           |
|                |      6 | la           | fa           |
|                |      3 | mi           | do           |
| sous-dominante |      4 | fa           | ré           |
|                |      2 | ré           | si           |
|                |      6 | la           | fa           |
| dominante      |      5 | sol          | mi           |
|                |      3 | mi           | do           |
|                |      7 | si           | sol          |

** Lien sémantique

Lorsqu’une modification de la disposition d’un accord /A/ permet de
rendre sa fonction tonale identique à celle d’un accord /B/, on dit
qu’il existe un *lien sémantique* entre les accords /A/ et /B/.

Par exemple, en /do majeur/, l’accord :

#+begin_center
do mi sol
#+end_center

exerce une fonction de tonique. Si nous plaçons le /sol/ à la basse et
que nous le doublons :

#+begin_center
sol do mi sol
#+end_center

il exerce alors une fonction de dominante. On met ainsi en évidence un
lien sémantique avec l’accord du degré 5 :

#+begin_center
sol si ré sol
#+end_center

qui exerce la même fonction.

*** Synonymes

Si les accords /A/ et /B/ sont unis par un lien sémantique, on peut
réarranger /A/, ou du moins réinterpréter sa fonction tonale, pour
qu’il soit synonyme de /B/.

* Cycle tonal

#+TOC: headlines 1 local

** Introduction

Le *cycle tonal* est une suite d’accords dont les fondamentales
descendent le cycle des quintes, mais en annulant ou ajoutant des
altérations pour que les notes obtenues restent dans la tonalité. Il
part du degré 1 et parcourt tous les autres degrés jusqu’à revenir à
la tonique.

Considérons par exemple la tonalité de /la mineur/. Le cycle des
quintes descendantes s’écrit :

#+begin_center
la ré sol do fa si^b mi^b la^b
#+end_center

Les bémols /si^b/, /mi^b/ et /la^b/ ne font pas partie de la tonalité
et sont donc annulés pour revenir aux notes naturelles /si/, /mi/ et
/la/. On obtient ainsi le cycle :

#+begin_center
la ré sol do fa si mi la
#+end_center

ce qui correspond aux degrés :

#+ATTR_HTML: :class plat
| notes  | : | la | ré | sol | do | fa | si | mi | la |
| degrés | : |  1 |  4 |   7 |  3 |  6 |  2 |  5 | 1  |

Écrit en terme de degrés, le cycle tonal est applicable à n’importe
quelle tonalité. C’est donc cette forme que nous retiendrons :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 3 | 6 | 2 | 5 | 1 |

C’est ce cycle, répété en boucle, qui sert de fondation à la musique
tonale. Naturellement, de nombreuses variations de ce modèle se
succèdent afin d’en rompre la monotonie. Si les techniques permettant
de produire ces variations peuvent nous mener à des enchaînements
parfois très éloignés du cycle d’origine, elles respectent néanmoins
certains principes :

  - il existe un lien entre
    + les accords originaux et les modifications
    + le nouvel accord et son environnement
  - ce lien peut être
    + accord synonyme
    + lien sémantique
    + fonction secondaire
    + lien polyphonique
    + enharmonie
  - l’accord final de chaque cycle fait en général fonction de tonique
    ou de dominante

Le cycle tonal permet d’expliquer des enchaînements courants ou d’en
découvrir de nouveaux, mais n’oublions pas qu’il ne s’agit que d’un
d’outil optionnel, à utiliser lorsqu’on le juge pertinent.

*** Quinte diminuée

Reprenons notre exemple en /la mineur/. Si toutes les quintes étaient
justes, nous traverserions le cycle complet des douze notes
diatoniques et altérées :

#+begin_center
la ré sol do fa si^b mi^b la^b ré^b sol^b [do^b = si] mi la
#+end_center

Au moins une de ces quintes doit être altérée afin de rester dans la
gamme heptatonique de /la mineur/. Dans notre exemple, l’annulation
des bémols produit l’apparition de la quinte diminuée descendante
/fa — si/.

** Suppression des doublons

Afin de simplifier la structure musicale, les accords intervenant en
double peuvent naturellement être réduits à un seul exemplaire.
Exemple :

#+ATTR_HTML: :class plat
| =...= | 5 | *1* | *1* | 4 | =...= | —> | =...= | 5 | *1* | 4 | =...= |

** Substitution

Cette opération consiste à remplacer un accord du cycle par un autre.
On veille toutefois à ce que l’accord original et son remplaçant
présentent certaines caractéristiques communes. Voici les principaux
mécanismes de substitution :

  - substitution par un accord synonyme à l’accord remplacé
  - substitution par un accord qui possède un lien sémantique avec
    l’accord remplacé
  - substitution par une fonction secondaire transformant le degré
    suivant en tonique secondaire
  - substitution polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants
  - substitution enharmonique : le nouvel accord est enharmonique à
    l’accord remplacé

** Insertion

Cette opération consiste à insérer un nouvel accord entre deux accords
du cycle. On veille toutefois à ce que l’accord inséré présente
certaines caractéristiques communes avec au moins un des accords
environnants. Les techniques d’insertion sont similaires à celles
utilisées pour la substitution :

  - insertion d’un accord synonyme renforçant une fonction tonale
    environnante
  - insertion d’un accord possédant un lien sémantique avec un des
    accords environnants
  - insertion d’une fonction secondaire transformant le degré
    suivant en tonique secondaire
  - insertion polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants
  - insertion par enharmonie : le nouvel accord est enharmonique au
    précédent ou au suivent

** Déviation

Cette opération consiste à dévier de trajectoire en créant un
raccourci dans le cycle tonal. On veille toutefois à ce que l’accord
de départ ait un lien avec l’accord d’arrivée :

  - déviation vers un accord d’arrivée synonyme à celui de départ
  - déviation vers un accord d’arrivée qui possède un lien sémantique
    avec l’accord de départ
  - déviation polyphonique : l’accord de départ possède un lien polyphonique
    avec l’accord d’arrivée
  - déviation enharmonique : les accords de départ et d’arrivée sont
    enharmoniques

*** Raccourci

Le *raccourci* est une déviation partant de n’importe quel accord du
cycle vers une fonction de dominante, éventuellement suivie par une
fonction de tonique.

*** Déviation enharmonique

À titre d’exemple de déviation enharmonique, plaçons-nous en /la
mineur/. L’accord de dominante sans fondamentale :

#+begin_center
sol^{#} si ré fa
#+end_center

est enharmonique à :

#+begin_center
la^b si ré fa
#+end_center

lui-même renversement de :

#+begin_center
si ré fa la^b
#+end_center

Ce dernier accord étant du degré 2, on peut créer un court-circuit
entre les degrés 7 et 2. Le cycle devient :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 2 | 5 | 1 |

** Figures de style

On peut imaginer d’autres types de modifications à apporter au cycle
tonal, en s’inspirant des [[file:litera-02-styleau.org][figures de style]] littéraires par exemple.

** Interprétation & réalisation

#+TOC: headlines 1 local

*** Introduction

Il existe de nombreuses interprétations du cycle tonal en terme de
fonctions, et chacune de ces interprétations peut être réalisées par
différentes suites d’accords. Nous disposons donc d’un système très
prolifique.

*** Degré 7 comme dominante

Voici un exemple d’interprétation du cycle tonal :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | T | T | Daux | D | T |

Le degré 7 y est considéré comme une dominante sans fondamentale et
les degrés 3 et 6 comme des accords de tonique. L’astuce est que nous
allons à présent oublier les degrés du cycle pour se concentrer sur
les fonctions :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |

Nous pouvons décider de réaliser ces fonctions par la suite
d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |
| 1 |  4 | 5 | 1 | 6 |    2 | 5 | 1 |

pour autant que chacun d’entre-eux mette en évidence la note tonale
correspondante, cela va de soi. Mais il existe d’autres possibilités
pour représenter cette suite de fonctions. Par exemple :

#+ATTR_HTML: :class plat
| 1 | 4 | 5 | 6 | 3 | 2 | 5 | 1 |

ou :

#+ATTR_HTML: :class plat
| 1 | 2 | 5 | 6 | 1 | 4 | 5 | 1 |

*** Degré 3 comme dominante

Si nous considérons que le degré 3 représente une dominante, nous
pouvons interpréter le cycle tonal de la façon suivante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | D | T | Daux | D | T |

qui peut par exemple se représenter par la suite d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | D | T | Daux | D | T |
| 1 |  4 | 7 | 5 | 6 |    2 | 5 | 1 |

*** Degrés 6 et 2 comme sous-dominante

Si nous considérons que les degrés 6 et 2 représentent une
sous-dominante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 |  6 |  2 | 5 | 1 |
| T | SD | D | T | SD | SD | D | T |

nous obtenons par exemple :

#+ATTR_HTML: :class plat
| T | SD | D | T | SD | SD | D | T |
| 1 |  2 | 5 | 1 |  6 |  4 | 5 | 1 |

*** Suites fréquentes

Nous constatons que les suites de fonctions :

#+ATTR_HTML: :class plat
| T | SD   | D | T |

et :

#+ATTR_HTML: :class plat
| T | Daux | D | T |

sont très fréquentes.

**** Anatole

Parmi les suites d’accords courantes provenant des innombrables
variations du cycle tonal, citons l’ *anatole* :

#+ATTR_HTML: :class plat
| 6 | 2 | 5 | 1 |

* Cycle plagal

Le *cycle plagal* est une suite d’accords dont les fondamentales
montent le cycle des quintes :

#+ATTR_HTML: :class plat
| 1 | 5 | 2 | 6 | 3 | 7 | 4 | 1 |

Les modifications qu’on peut lui apporter sont analogues à celles du
cycle tonal.

Si le cycle plagel est rarement utilisé seul, il peut être utile d’en
insérer occasionnellement un fragment dans le cycle tonal.

* Distance tonale

#+TOC: headlines 1 local

** Introduction

La *distance tonale* entre deux accords est le nombre d’étapes
nécessaires pour aller du premier accord au deuxième en suivant le
cycle tonal. Cette distance dépend de l’intervalle formé par les
fondamentales :

| Nombre d’étapes | Intervalle |
|-----------------+------------|
|               1 | 5te        |
|               2 | 2de M      |
|               3 | 3ce m      |
|               4 | 3ce M      |
|               5 | 2de m      |
|               6 | 4te aug    |

On retrouve ainsi un tableau similaire à ceux des
[[file:musica-01-monocorde.org::#heading:recapitulationTranspositionQuintes][transpositions par combinaisons de quintes]].

Comme l’enchaînement reste équivalent si la fondamentale monte ou
descend d’une octave, les renversements de ces intervalles
correspondent à la même distance tonale et on a en définitive :

| Étapes | Intervalles |         |
|--------+-------------+---------|
|      1 | 5te         | 4te     |
|      2 | 2de M       | 7e m    |
|      3 | 3ce m       | 6te M   |
|      4 | 3ce M       | 6te m   |
|      5 | 2de m       | 7e M    |
|      6 | 4te aug     | 5te dim |

** Proximité tonale

Deux accords sont dit *tonalement proches* lorsque la distance tonale
qui les sépare est faible.

On retient généralement comme proches les accords séparés par une ou
deux étapes dans le cycle des quintes. Leurs fondamentales forment
alors :

  1. une quinte
  2. une seconde majeure

Deux accords sont dits *tonalement éloignés* s’ils ne sont pas proches.

** Enchaînements forts & faibles

Les enchaînements d’accords tonalement proches sont appelés
*enchaînements forts*.

Les enchaînements d’accords tonalement éloignés sont appelés
*enchaînements faibles*.

Un enchaînement est donc :

  - fort si les fondamentales procèdent par
    + quinte
    + seconde majeure
  - faible si les fondamentales procèdent par
    + tierce

* Dispositions des accords

#+TOC: headlines 1 local

** Harmoniques naturelles

Nous avons déjà vu que les harmoniques naturelles pouvaient
inspirer des dispositions intéressantes pour les
[[file:/home/david/racine/site/eclats2vers/generic/grimoire/musica-03-luth.org::#heading:accordsParfaitsDispositions][accords parfaits]]

Il va de soi que ce principe peut être généralisé aux septièmes
de domoinante ou à n’importe quel autre accord : s’inspirer des
harmoniques naturelles est toujours une bonne idée.

** Accords parfaits

#+TOC: headlines 1 local

*** État fondamental

L'état fondamental est le plus affirmé, il agit comme un pilier de la
tonalité.

On double :

  - le plus souvent la fondamentale ou une note tonale
  - parfois la 3ce, en guise de variation

Si on souhaite supprimer une note :

  - on évite de supprimer la fondamentale
  - si on souhaite éviter l’ambiguité entre accord parfait majeur ou mineur
    + on ne supprime pas la note de 3ce majeure ou mineure
    + on supprime plutôt la 5te
  - l’accord produira un effet de simplicité si on supprime la 3ce
    + à réserver aux instants de convergence, comme en fin de phrase

#+begin_center
⁂
#+end_center

L’accord parfait du degré 7 remplit généralement la même fonction
tonale qu’une 7e de dominante sans fondamentale.

*** Premier renversement

Le premier renversement est moins appuyé que l’état fondamental.

On double en général une note tonale.

Si un degré fort est situé une tierce au-dessus de la fondamentale, la
basse est généralement doublée et l’accord peut assurer la fonction
tonale correspondante.

De part leur forte similitude, les accords de sixte peuvent aussi
ornementer l’accord parfait à l’état fondamental situé une tierce plus
haut. On compte en effet deux notes communes, et même trois avec la
doublure. Exemples en /do majeur/ :

| degrés | fonction | premier       | état fondamental d’un accord |
|        |          | renversement  | situé une tierce au-dessus   |
|--------+----------+---------------+------------------------------|
| 2 & 4  | SD       | fa la ré fa   | fa la do fa                  |
| 6 & 1  | T        | do mi la do   | do mi sol do                 |
| 3 & 5  | D        | sol si mi sol | sol si ré sol                |

#+begin_center
⁂
#+end_center

En mineur, l’accord de sus-tonique est soit :

  - au premier renversement pour éviter la quinte diminuée avec la basse
  - présenté avec un degré 2 abaissé pour produire un accord napolitain
  - sous la forme d’un accord napolitain au premier renversement

*** Second renversement

Le second renversement sert souvent d’accord ornemental. On s’arrange
alors pour que la basse fasse note commune avec les accords
environnants, contrastant alors avec les mouvements mélodiques
ornementaux des autres voix.

On double en général la basse, pour équilibrer les mouvements
constants et variables. Dans un quatuor, on se retrouve alors avec
deux voix constantes et deux voix variables.

Exemple de second renversement avec broderies au soprano et au ténor :

#+ATTR_HTML: :class plat
| S | : | si  | do  | si  |
| A | : | sol | sol | sol |
| T | : | ré  | mi  | ré  |
| B | : | sol | sol | sol |

Exemple de second renversement avec note de passage au ténor :

#+ATTR_HTML: :class plat
| S | : | sol | la | mi  |
| A | : | do  | do | do  |
| T | : | mi  | fa | sol |
| B | : | do  | do | do  |

Exemple avec une broderie au ténor et une note de passage au soprano :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | do  |
| A | : | sol | sol | sol |
| T | : | do  | si  | do  |
| B | : | do  | ré  | mi  |

** Septième de dominante

La note de 7e peut servir d’ornement harmonique ou mélodique.

Suppression :

  - on évite de supprimer la 3ce, car c’est la sensible inférieure
  - si on supprime la 7e, on se retrouve avec un accord parfait
  - on supprime le plus souvent la fondamentale ou la 5te

*** Sans fondamentale
:PROPERTIES:
:CUSTOM_ID: heading:dispositionSeptièmeDominanteSansFondamentale
:END:

La septième de dominante sans fondamentale est au minimum au premier
renversement, avec la 3ce à la basse.

Cette disposition est moins dissonante que l’accord complet, car
l’intervalle de septième mineure n’est plus présent.

Le second renversement est préféré au premier, car il évite aussi les
intervalles dissonants avec la basse, ce qui rend sa sonorité plus
douce.

Par exemple, en /do majeur/, la septième de dominante sans
fondamentale s’écrit :

#+begin_center
(sol) si ré fa —> si ré fa
#+end_center

ce qui produit un intervalle de quinte diminuée entre la note de 7e
/fa/ et la basse. Par contre, au second renversement :

#+begin_center
(sol) si ré fa —> ré fa si
#+end_center

on obtient des intervalles consonants avec la basse :

  - basse — fa : tierce mineure
  - basse — si : sixte majeure

L’intervalle dissonant du triton /fa — si/ ne fait alors pas
intervenir la basse.

Sous cette forme, l’accord de septième de dominante sans fondamentale
est présent dans la
[[file:musica-04-clavier.org::#heading:cadenceIonienneTroisVoix][cadence ionienne à trois voix]].

** Accords à base de quintes

Suppressions :

  - on évite de supprimer les notes qui contiennent la tension
    + 2de
    + 4te
    + etc

** Renversements

Les accords renversés ont généralement un caractère tonal moins
affirmé que leurs homologues à l’état fondamental. Cette remarque est
d’autant plus vraie pour les accords de trois notes. Afin de ne pas
rendre leur fonction tonale encore plus floue, on évite autant que
possible de supprimer une note d’une triade renversée.

Par contre, les accords renversés de quatre notes ou plus, et en
particulier la 7e et la 9e de dominante, peuvent s’employer sans
fondamentale ou sans quinte.
