
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 02 : Métronome
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Rythme

Chaque note de musique est définie par :

  - une hauteur
  - une durée

L’ensemble des durées produites par les notes de musique est appelée
*rythme*.


* Durées

#+TOC: headlines 1 local


** Valeurs rythmiques

L’unité rythmique standard est la ronde.

Les unités plus petites que la ronde sont des divisions binaires de
celle-ci :

| Noms             | Abréviations | Duréés en rondes |
|------------------+--------------+------------------|
| ronde            | R            | 1                |
| blanche          | B            | 1 / 2            |
| noire            | N            | 1 / 4            |
|------------------+--------------+------------------|
| croche           | C            | 1 / 8            |
| double-croche    | dC           | 1 / 16           |
| triple-croche    | tC           | 1 / 32           |
| quadruple-croche | qC           | 1 / 64           |

Les unités plus grandes que la ronde sont des multiples binaires de
celle-ci :

| Noms             | Abréviations | Duréés en rondes |
|------------------+--------------+------------------|
| brève, ou carrée | U            |                2 |
| longue           | L            |                4 |
| maxime           | M            |                8 |

Historiquement, la brève a été une unité rythmique de durée
intermédiaire, mais au fil du temps, la notation du rythme a beaucoup
évolué, ce qui la classe à présent parmi les plus longues. Voir à ce
sujet la section concernant la [[file:musica-11-coda.org::#heading:notation_durees][notation des durées]] dans la coda de cet
ouvrage.


*** Sur une portée

Le remplissage et la hampe de chaque note déterminent son rythme.

La ronde et ses subdivisions se représentent comme suit :

  - ronde : note blanche (non remplie) sans hampe
  - blanche :  note blanche avec hampe
  - noire : note noire (remplie) avec hampe
  - croche : note noire avec hampe et crochet
  - double croche : note noire avec hampe et crochet double
  - triple croche : note noire avec hampe et crochet triple

Les notes plus longues que la ronde se représentent comme suit :

  - brève : ronde entourée à gauche et à droite de barres verticales
  - longue : brève avec hampe


** Notes pointées

Afin de pouvoir passer d’une décomposition binaire à une décomposition
ternaire, on dispose également des notes pointées, dont la durée est
de 3/2 de celle d’une note ordinaire :

| Abréviations | Signification                        | Durée en rondes |
|--------------+--------------------------------------+-----------------|
| /Dp/         | indique que la durée /D/ est pointée | /D/ × 3 / 2     |
| Mp           | maxime pointée                       | 12              |
| Lp           | longue pointée                       | 6               |
| Up           | brève pointée                        | 3               |
| Rp           | ronde pointée                        | 3 / 2           |
| Bp           | blanche pointée                      | 3 / 4           |
| Np           | noire pointée                        | 3 / 8           |
| Cp           | croche pointée                       | 3 / 16          |
| dCp          | double-croche pointée                | 3 / 32          |
| tCp          | triple-croche pointée                | 3 / 64          |
| qCp          | quadruple-croche pointée             | 3 / 128         |


*** Notes doublement pointées

Pointer une note ajoute la moitié de sa durée :

#+begin_center
1 ⟶ 1 + 1/2 = 3/2
#+end_center

Double-pointer une note ajoute la moitié de la durée, puis le quart :

#+begin_center
1 ⟶ 1 + 1/2 + 1/4 = 7/4
#+end_center

Voici la liste des notes double-pointées :

| Abréviations | Signification                                   | Durée en rondes |
|--------------+-------------------------------------------------+-----------------|
| /Dpp/        | indique que la durée /D/ est doublement pointée | /D/ × 7 / 4     |
| Mpp          | maxime double-pointée                           | 14              |
| Lpp          | longue double-pointée                           | 7               |
| Upp          | brève double-pointée                            | 7 / 2           |
| Rpp          | ronde double-pointée                            | 7 / 4           |
| Bpp          | blanche double-pointée                          | 7 / 8           |
| Npp          | noire double-pointée                            | 7 / 16          |
| Cpp          | croche double-pointée                           | 7 / 32          |
| dCpp         | double-croche double-pointée                    | 7 / 64          |
| tCpp         | triple-croche double-pointée                    | 7 / 128         |
| qCpp         | quadruple-croche double-pointée                 | 7 / 256         |


*** Sur une portée

Les notes pointées se représentent comme suit :

  - note pointée : un point est ajouté à droite du cercle de la note
  - note doublement pointée : deux points sont ajoutés


** Durées fractionnaires

Il est possible de raccourcir ou d’allonger la durée d’un groupe de
notes en le précisant avec une fraction :

#+begin_center
M / N (groupe de notes)
#+end_center
*
La durée totale du groupe de notes ainsi modifié vaudra alors M / N de
sa durée naturelle :

#+begin_center
durée de { M / N (groupe de notes) } = M / N × durée de { groupe de notes }
#+end_center


*** Triolet

La fraction la plus fréquente est le *triolet* :

#+begin_center
2/3 (N N N)
#+end_center

La durée totale du groupe vaut alors :

#+begin_center
2/3 × 3 noires = 2 noires = 1 blanche
#+end_center

Le triolet permet d’insérer trois noires dans une blanche au lieu de
deux. On rencontre aussi des triolets de trois croches qui durent une
noire, ainsi que d’autres durées.


*** Duolet

Le *duolet* est l’inverse du triolet :

#+begin_center
3/2 (N N)
#+end_center

La durée totale du groupe vaut :

#+begin_center
3/2 × 2 noires = 3 noires = 1 blanche pointée
#+end_center

Le duolet permet d’insérer deux noires dans une blanche pointée au
lieu de trois. On rencontre aussi des duolets de deux croches valant
une noire pointée, ainsi que d’autres durées.


*** Sur une portée

Un triolet est représenté par un trait arrondi qui relie trois notes
et près duquel on écrit un 3.

Un duolet est représenté par un trait arrondi qui relie deux notes
et près duquel on écrit un 2.


** Liaison de prolongation

Une liaison de prolongation consiste à prolonger une note par une ou
plusieurs notes situées à la même hauteur. La durée de la note
résultante est égale à la somme des durées des notes impliquées.

On note la liaison de prolongation par :

#+begin_center
X‿Y
#+end_center

ou, pour un nombre arbitraire de notes :

#+begin_center
X‿Y‿...‿Z
#+end_center

Exemples :

#+ATTR_HTML: :class plat
| N‿N     | est identique à | B     |
| N‿N‿N   | est identique à | Np    |
| N‿C     | est identique à | Np    |
| B‿N‿C   | est identique à | Bpp   |


*** Sur une portée

Les cercles des notes qui composent la liaison de prolongation sont
reliés par un trait arrondi.


** Silences

Le tableau suivant nous donne la liste des silences et de leurs
durées :

| Abréviation | Silence            | Durée            |
|-------------+--------------------+------------------|
| ms          |                    | maxime           |
| ls          |                    | longue           |
| us          | bâton de pause     | brève            |
| rs          | pause              | ronde            |
| bs          | demi-pause         | blanche          |
| ns          | soupir             | noire            |
| cs          | demi-soupir        | croche           |
| dcs         | quart de soupir    | double-croche    |
| tcs         | huitième de soupir | triple-croche    |
| qcs         | seizième de soupir | quadruple-croche |

Les silences peuvent aussi être pointés. Si /D/ est une durée
quelconque, on a :

| Abréviation | Durée                    |
|-------------+--------------------------|
| /dps/       | 3 / 2 × la durée de /D/s |
| /dpps/      | 7 / 4 × la durée de /D/s |


*** Sur une portée

  - bâton de pause : une barre épaisse reliant deux lignes de la portée
  - pause : une barre épaisse horizontale suspendue à une ligne de la portée
    + chapeau inversé
  - demi-pause : une barre épaisse horizontale posée sur une ligne de la portée
    + chapeau
  - soupir : ressemble vaguement à un 3 inversé, ou à un E arrondi
  - demi-soupir : hampe inclinée vers la droite avec un crochet en
    haut à gauche
  - quart de soupir : hampe inclinée vers la droite avec deux crochets
  - huitième de soupir : hampe inclinée vers la droite avec trois crochets
  - etc

* Pyramide rythmique

#+TOC: headlines 1 local

** Introduction

Une oeuvre musicale se base sur différentes *unités rythmiques*
fondamentales. La structure pyramidale qui en résulte provient des
principes complémentaires suivants :

  - plusieurs unités peuvent s’assembler pour constituer une unité
    plus longue
  - chaque unité rythmique est décomposable en unités plus courtes

Voici les unités les plus courantes, en commençant par les plus
courtes :

  - le *temps*
  - la *mesure*, qui regroupe plusieurs temps
  - la *carrure*, qui regroupe plusieurs mesures


** Structure interne

On dispose de qualificatifs permettant de préciser en combien de
sous-unités se décompose une unité rythmique donnée. Ainsi :

  - une unité rythmique *binaire* se décompose en *deux* sous-unités
  - une unité rythmique *ternaire* se décompose en *trois* sous-unités
  - une unité rythmique *quaternaire* se décompose en *quatre* sous-unités

Exemples :

  - une carrure quaternaire se compose de quatre mesures
  - une mesure ternaire se compose de trois temps
  - un temps binaire se subdivise en 2 parties de temps

Remarquone qu’une unité rythmique quaternaire peut aussi de décomposer
en deux sous-unités, et est donc également binaire. Il est également
très facile de diviser en deux les durées d’une unité rythmique
binaire pour la transformer en unité rythmique quaternaire.


** Régularité

Une unité rythmique est dite *régulière* lorsqu’elle se décompose en
sous-unités de durées et structures identiques.

Une unité rythmique est dite *irrégulière* lorsqu’elle se décompose en
sous-unités de durées et structures différentes.


* Temps

#+TOC: headlines 1 local

** Introduction

Tous les temps ne sont pas d’égale importance, certains sont plus
accentués que d’autres. Les temps les plus accentués sont appelés
*temps forts*, et les autres *temps faibles*. On rencontre aussi des
*temps médians*, dont l’accentuation est intermédiaire entre celles
des temps forts et faibles. Nous avons donc finalement trois niveaux
d’accentuation :

  - temps fort
  - temps médian
  - temps faible

Nous utilisons les abréviations suivantes :

| F | temps fort   |
| µ | temps médian |
| f | temps faible |


** Parties fortes et faibles

À cette hiérarchie des temps forts et faibles, vient s’ajouter celle
des parties fortes et faibles d’un temps.

Lorsqu’un temps est subdivisé en plusieurs parties, la *partie forte*
du temps correspond à la première partie, et la *partie faible* du
temps à tout le reste.


** Tempo

Le *tempo* donne le nombre de temps contenus dans une minute. Plus le
tempo est élevé, plus la durée d’un temps sera faible. Le tempo
représente donc la vitesse à laquelle la musique est jouée.

En pratique, le tempo est défini en passant par une unité rythmique de
référence, qui correspond généralement à la durée d’un temps.

Par exemple, un tempo de :

#+begin_center
/N/ blanches par minutes
#+end_center

nous donnera :

#+begin_center
durée d’une blanche = 1 / /N/ minute
#+end_center

Toutes les autres durées se déduisent du tempo. On aura ainsi :

#+ATTR_HTML: :class plat
| /N/ / 16 | maximes par minute           |
| /N/ / 8  | longues par minute           |
| /N/ / 4  | brèves par minute            |
| /N/ / 2  | rondes par minute            |
| 2 /N/    | noires par minute            |
| 4 /N/    | croches par minute           |
| 8 /N/    | double-croches par minute    |
| 16 /N/   | triple-croches par minute    |
| 32 /N/   | quadruple-croches par minute |


* Mesures

#+TOC: headlines 1 local

** Simples & composées

Les mesures se classent en deux catégories :

  - les *mesures simples*
    + une mesure simple est constituée d’un seul groupe de /N/ temps
    + les plus courantes
      * mesure simple à 2 temps
      * mesure simple à 3 temps
      * mesure simple à 4 temps
  - les *mesures composées*
    + une mesure composée est constituée de /M/ groupes de /N/ temps
    + les plus courantes
      * 4 temps structurés en 2 groupes de 2 temps
      * 6 temps structurés en 2 groupes de 3 temps
      * 9 temps structurés en 3 groupes de 3 temps
      * 12 temps structurés en 4 groupes de 3 temps

Par exemple :

  - le galop, la habanera et la polka sont basés sur une mesure simple
    à 2 temps
  - la valse, la chaconne et la sarabande sont basés sur une mesure
    simple à 3 temps
  - le fameux "Take Five" de Dave Brubeck est basé sur une mesure
    simple à 5 temps
  - la sicilienne et la tarentelle sont basées sur une mesure composée
    à 6 temps

** Temps forts et faibles

Le cas le plus fréquent est celui où les temps forts et faibles sont
alternés. Les temps médians sont également alternés avec les temps
faibles et forts quand c’est possible.

Nous avons les structures de base suivantes pour les mesures
régulières :

| Mesure  | Temps   |
|---------+---------|
| 2 temps | F f     |
|---------+---------|
| 3 temps | F f f   |
|         | F µ f   |
|         | F f µ   |
|---------+---------|
| 4 temps | F f µ f |
|         | F f f f |


** Sur la portée

#+TOC: headlines 1 local

*** Structure

Le symbole indiquant la structure de la mesure est placé au début de la portée, juste à
droite de la clef. Il est généralement constitué de deux chiffres
superposés, comme une fraction sans barre :

  - le chiffre du haut indique le nombre de temps
    + 2, 3 ou 4 pour une mesure simple
    + 4, 6, 9, 12 pour une mesure composée
  - le chiffre du bas indique la durée du temps, en fractions de ronde
    + 2 pour la demi-ronde, c’est-à-dire la blanche
    + 4 pour le quart de ronde, c’est-à-dire la noire
    + 8 pour le huitième de ronde, c’est-à-dire la croche
    + etc

On trouve aussi :

  - le demi-cercle à la place du 4 / 4
    + mesure à 4 temps
    + 1 temps = 1 noire
  - le demi-cercle barré à la place du 2 / 2
    + mesure à 2 temps
    + 1 temps = 1 blanche

*** Séparation

Les mesures sont séparées par des traits verticaux appelés *barres de
mesure* qui traversent la portée de la première à la dernière ligne.

Chaque mesure commence et se termine donc par une barre verticale.

*** Changement de mesure

Un changement de mesure peut s’opérer en cours de portée. On place
alors le nouveau symbole à l’endroit choisi.


** Mesure régulière

Une mesure *régulière* est une mesure composée de groupes
de temps de durées et structures identiques.

Les mesures régulières sont les mesures composées les plus utilisées.

Considérons par exemple une mesure comptant en tout 6 temps. Elle peut
s’organiser en 2 groupes de 3 temps ou en 3 groupes de 2 temps :

#+ATTR_HTML: :class plat
| /Deux groupes ternaires/ | : | 3 + 3     |
| /Trois groupes binaires/ | : | 2 + 2 + 2 |

De même, une mesure de 12 temps peut se structurer en 4
temps ternaires ou en 3 temps quaternaires :

#+ATTR_HTML: :class plat
| /Quatre groupes ternaires/   | : | 3 + 3 + 3 + 3 |
| /Trois groupes quaternaires/ | : | 4 + 4 + 4     |

Si l’on souhaite une mesure composée de /M/ groupes de /N/ temps il
suffit de choisir une mesure de /M × N/ temps.


** Mesure irrégulière

Une mesure *irrégulière* est une mesure composée constituée de groupes
de temps de natures différentes. Voici quelques exemples de
décompositions irrégulières :

| Nombre de temps | Décomposition     |
|-----------------+-------------------|
|               5 | 2 + 3             |
|               7 | 3 + 4             |
|               7 | 2 + 3 + 2         |
|               7 | 3 + 2 + 2         |
|               8 | 3 + 2 + 3         |
|               9 | 3 + 2 + 4         |
|              10 | 4 + 3 + 3         |
|              11 | 4 + 4 + 3         |
|              12 | 3 + 4 + 2 + 3     |
|                 | 2 + 3 + 3 + 2 + 2 |

On retrouve des décompositions analogues dans [[file:litera-01-rimailleur.org::#heading:coupesEtCesures][les coupes et césures poétiques]].


* Carrures

#+TOC: headlines 1 local

** Introduction

Une *carrure* est un groupe de mesures.

Chaque carrure peut regrouper 2, 3, 4, 8 mesures ou plus.

L’échelle rythmique de la carrure est liée au phrasé musical.


** Royale

La *carrure royale* compte huit mesures. Chaque carrure sert de
support au développement d’un mini-thème musical.


** Multi-niveaux

Il n’est pas rare qu’une carrure puisse être analysée sur plusieurs
niveaux rythmiques.

C’est généralement le cas de la carrure royale :

  - le groupe de 8 mesures peut se décomposer en 2 demi-carrures
    comptant chacune 4 mesures
  - chaque groupe de 4 mesures peut se subdiviser en 2 groupes de 2 mesures
  - le groupe de 8 mesures peut donc se décomposer en 4 quart de
    carrures comptant chacune 2 mesures

On trouve aussi d’autres configurations :

  - 6 mesures subdivisées en 3 groupes de 2 mesures
  - 6 mesures subdivisées en 2 groupes de 3 mesures


* Pulsations & Oscillations

#+TOC: headlines 1 local

** Introduction

En plus de la structure écrite sur la partition, on dispose de la
notion de *pulsation*, battement fondamental que l’on ressent en
écoutant la musique. Les accents les plus importants sont d’ailleurs
placés au début de chaque pulsation.

Suivant les cas, la pulsation correspond à la durée :

  - d’un temps
  - d’un groupe de temps
  - d’une mesure

En termes absolus, une pulsation dure approximativement une seconde,
mais cette durée dépend de la rapidité de la musique. En général, une
pulsation dure :

  - un peu plus d’une seconde dans les tempos lents
  - un peu moins d’une seconde dans les tempos rapides

La durée des pulsations reste normalement constante, à moins d’un
changement de tempo.

On utilisait autrefois un concept proche de la pulsation : le
*tactus*, unité de temps proche de la seconde à laquelle toutes les
durées se rapportaient. Tout comme pour la pulsation, des variantes de
tactus plus ou moins rapides existaient.

#+begin_center
⁂
#+end_center

L’effet de balancement produit par le regroupement de deux pulsations
ou plus est appelé *oscillation*. On a donc :

  - la pulsation, dont la durée est approximativement égale à la
    seconde
  - l’oscillation, qui regroupe plusieurs pulsations

/Remarque/ : l’oscillation binaire, c’est-à-dire formée de deux
pulsations, est la plus fréquente.


** Pulsation

#+TOC: headlines 1 local

*** Introduction

Une pulsation englobe généralement plusieurs temps.


*** Mesure simple

Quand la pulsation correspond à la durée d’une mesure simple, elle se
décompose suivant le nombre de temps de la mesure : 2, 3, 4 ou /N/
temps.


*** Mesure composée

Dans une mesure composée, la pulsation peut correspondre à la durée
d’un groupe de temps. Dans ce cas, on a :

  - 2 pulsations de 2 temps dans une mesure composée à 4 temps
  - 2 pulsations de 3 temps dans une mesure composée à 6 temps
  - 3 pulsations de 3 temps dans une mesure composée à 9 temps
  - 4 pulsations de 3 temps dans une mesure composée à 12 temps

Les débuts de temps forts et médians coïncident généralement avec les
débuts des pulsations.


** Oscillation

Une oscillation binaire peut être formée de :

  - 2 mesures simples
  - 1 mesure composée de 6 temps, soit 2 groupes de 3 temps

Une oscillation ternaire peut être formée de :

  - 3 mesures simples
  - 1 mesure composée de 6 temps, soit 3 groupes de 2 temps
  - 1 mesure composée de 9 temps, soit 3 groupes de 3 temps

Une oscillation quaternaire peut être formée de :

  - 4 mesures simples
  - 1 mesure composée de 12 temps, soit 4 groupes de 3 temps

En général, une oscillation de /M/ pulsations peut être formée de :

  - /M/ mesures simples à /N/ temps
  - 1 mesure composée de /M × N/ temps, soit /M/ groupes de /N/ temps


*** Carrure

Les carrures sont normalement organisées de telle sorte qu’elles
respectent la structure des oscillations.


** Notation

Nous utilisons les notations suivantes :

| Notation | Temps                                            |
|----------+--------------------------------------------------|
| §        | début de la première pulsation d’une oscillation |
| ¶        | début d’une autre pulsation                      |
| χ        | début d’un autre temps                           |

Voici quelques exemples de cette notation :

| Oscillation            | structure               |
|------------------------+-------------------------|
| 2 pulsations binaires  | § χ ¶ χ                 |
| 3 pulsations binaires  | § χ ¶ χ ¶ χ             |
| 4 pulsations binaires  | § χ ¶ χ ¶ χ ¶ χ         |
|------------------------+-------------------------|
| 2 pulsations ternaires | § χ χ ¶ χ χ             |
| 3 pulsations ternaires | § χ χ ¶ χ χ ¶ χ χ       |
| 4 pulsations ternaires | § χ χ ¶ χ χ ¶ χ χ ¶ χ χ |


** Ambiguité

Comment faire la différence entre une mesure simple de 4 temps et une
mesure composée de 2 groupes de 2 temps ? La pulsation permet de lever
cette ambiguité :

  - si seul le premier temps de la mesure marque le début d’une
    pulsation, il s’agit d’une mesure simple à 4 temps
  - si le premier et le troisième temps de la mesure marquent le début
    d’une pulsation, il s’agit d’une mesure composée de 2 x 2 temps

En supposant une oscillation binaire, on a le schéma :

| Oscillation                      | structure       |
|----------------------------------+-----------------|
| 2 mesures simples à 4 temps      | § χ χ χ ¶ χ χ χ |
| 1 mesure composée de 2 x 2 temps | § χ ¶ χ         |


** Tableau récapitulatif

Le tableau ci-dessous recense les structures de pulsations et
d’oscillations les plus courantes.

| Oscillation | Pulsation   | Durée       | Durée     | Mesure         | Structure                       |
|             |             | oscillation | pulsation |                |                                 |
|-------------+-------------+-------------+-----------+----------------+---------------------------------|
| binaire     | binaire     | 1 mesure    | 2 temps   | composée 2 x 2 | § χ ¶ χ                         |
|             |             | 2 mesures   | 1 mesure  | simple 2 temps | § χ ¶ χ                         |
|             | ternaire    | 1 mesure    | 3 temps   | composée 2 x 3 | § χ χ ¶ χ χ                     |
|             |             | 2 mesures   | 1 mesure  | simple 3 temps | § χ χ ¶ χ χ                     |
|             | quaternaire | 2 mesures   | 1 mesure  | simple 4 temps | § χ χ χ ¶ χ χ χ                 |
|-------------+-------------+-------------+-----------+----------------+---------------------------------|
| ternaire    | binaire     | 3 mesures   | 1 mesure  | simple 2 temps | § χ ¶ χ ¶ χ                     |
|             | ternaire    | 1 mesure    | 3 temps   | composée 3 x 3 | § χ χ ¶ χ χ ¶ χ χ               |
|             |             | 3 mesures   | 1 mesure  | simple 3 temps | § χ χ ¶ χ χ ¶ χ χ               |
|             | quaternaire | 1 mesure    | 4 temps   | composée 3 x 4 | § χ χ χ ¶ χ χ χ ¶ χ χ χ         |
|             |             | 3 mesures   | 1 mesure  | simple 4 temps | § χ χ χ ¶ χ χ χ ¶ χ χ χ         |
|-------------+-------------+-------------+-----------+----------------+---------------------------------|
| quaternaire | binaire     | 4 mesures   | 1 mesure  | simple 2 temps | § χ ¶ χ ¶ χ ¶ χ                 |
|             | ternaire    | 4 mesures   | 1 mesure  | simple 3 temps | § χ χ ¶ χ χ ¶ χ χ ¶ χ χ         |
|             |             | 1 mesure    | 3 temps   | composée 4 x 3 | § χ χ ¶ χ χ ¶ χ χ ¶ χ χ         |
|             | quaternaire | 4 mesures   | 1 mesure  | simple 4 temps | § χ χ χ ¶ χ χ χ ¶ χ χ χ ¶ χ χ χ |


** Mesures irrégulières

On choisit une pulsation qui dure au moins une mesure entière, afin de
maintenir une durée constante.

Considérons par exemple une mesure irrégulière de structure 2 + 3.

Une oscillation constitutée de deux pulsations constantes sera alors
construite sur deux mesures, comme suit :

#+ATTR_HTML: :class plat
| § | χ | χ | χ | χ | ¶ | χ | χ | χ | χ |


* Hémiole

#+TOC: headlines 1 local

** Introduction

L’hémiole est un procédé qui consiste à réorganiser une structure
rythmique du type :

#+ATTR_HTML: :class plat
| 2 x 3 | = | 2 entités décomposables en 3 |

en une structure alternative du type :

#+ATTR_HTML: :class plat
| 3 x 2 | = | 3 entités décomposables en 2 |

Les deux structures auront exactement la même durée.

Le procédé inverse, à savoir réorganiser une structure du type /3 × 2/
en une structure alternative du type /2 × 3/, est également une
hémiole. Précisons que les structures /2 × 3/ et /3 × 2/ peuvent être
présentées consécutivement ou simultanément.


** Étymologie

Le terme hémiole provient du grec ancien et signifie littéralement
« un et demi », mathématiquement identique à 3 / 2.


** Mesures

Dans le cas de mesures simples, l’hémiole peut se construire au
choix :

  - sur une mesure de trois temps binaires qui se transforme en mesure
    de deux temps ternaires, et vice versa
  - sur plusieurs mesures : 2 mesures de 3 temps peuvent être pensées
    comme 3 mesures de 2 temps, et vice versa

Dans le cas de mesures composées, l’hémiole se positionne sur les
groupes de temps de la mesure : 2 groupes de 3 temps peuvent être
pensés comme 3 groupes de 2 temps, et vice versa.


** Generalisation

On peut appliquer le même procédé à 4 entités rythmiques décomposables
en 3, structure qui peut être réorganisée en 3 unités rythmiques
décomposables en 4, et vice versa.

Plus généralement, soit /M/ et /N/ deux nombres entiers strictement
positifs. On considère une structure rythmique formée par /M/ entités,
chacune de ces entités étant décomposable en /N/ sous-entités. La
structure compte donc en tout /M × N/ sous-entités. Comme :

#+ATTR_HTML: :class plat
| M × N | = | N × M |

on peut réorganiser l’ensemble en /N/ entités rythmiques décomposables
en /M/ sous-entités. On parle alors d’une hémiole de type (/M/, /N/).


** Transition

Il est possible de réaliser des transitions naturelles entre mesures
composées de groupes binaires, ternaires et quaternaires :

  - une mesure composée de 2 groupes de 3 temps peut être réorganisée
    en 3 groupes de 2 temps. Chaque groupe correspondant à une
    pulsation, on passe alors de 2 pulsations ternaires à 3 pulsations
    binaires
  - une mesure composée de 4 groupes de 3 temps peut être réorganisée
    en 3 groupes de 4 temps. Chaque groupe correspondant à une
    pulsation, on passe alors de 4 pulsations ternaires à 3 pulsations
    quaternaires

En utilisant le même procédé, on peut réorganiser les pulsations dans
un groupe de mesures :

  - 2 mesures de 3 temps avec une pulsation par mesure, c’est-à-dire
    une pulsation tout les 3 temps, peuvent être réorganisées en
    plaçant une pulsation tous les 2 temps. On passe alors de 2
    pulsations ternaires à 3 pulsations binaires.
  - 4 mesures de 3 temps avec une pulsation par mesure peuvent être
    réorganisées en plaçant une pulsation tous les 4 temps. On passe
    alors de 4 pulsations ternaires à 3 pulsations quaternaires.


* Modification des paramètres rythmiques

#+TOC: headlines 1 local

** Introduction

N’importe quel paramètre musical peut être modifié en cours de
morceau : gamme, mode, rythme, etc.

Dans le cas du rythme, on peut modifier :

  - le tempo
  - la mesure
    + nombre de temps
    + groupes de temps
  - la carrure
  - la pulsation
  - l’oscillation

Pour réaliser une transition fluide, on fait généralement correspondre
une durée caractéristique du rythme précédant le changement avec une
durée caractéristique du rythme qui suit le changement.

Par exemple, le temps peut rester de même durée, mais le nombre de
temps dans un groupe peut augmenter, ralentissant ainsi la musique.

Dans la phase qui précède un changement de tempo, on fait entendre la
durée du futur tempo dans certaines notes. Par exemple, le rythme :

#+begin_center
Np C Np C =...=
#+end_center

mets la noire pointée en évidence. Il nous permet donc de passer d’un
tempo de 70 noires par minutes à 70 noires pointées par minutes. Ce
dernier tempo est équivalent à 105 noires par minutes, car :

#+begin_center
70 x (durée d’une noire pointée) / (durée d’une noire) = 70 x 3 / 2 = 105
#+end_center


* Cellules rythmiques

#+TOC: headlines 1 local


** Introduction

Une *cellule rythmique* est un rythme basique occupant l’entièreté
d’une pulsation, soit un des cas suivants :

  - une mesure simple
  - un groupe de temps dans une mesure composée


** Décomposition et liaison

Une cellule rythmique quelconque peut être obtenue en décomposant la
durée de la pulsation en plusieurs unités, puis en liant entre-elles
certaines de ces unités.

Par exemple, dans le cas où la pulsation est ternaire, on peut la
décomposer en trois temps, puis décomposer chacun de ces temps en deux
unités, ce qui nous donne au total 6 unités. Si la pulsation dure une
blanche pointée, chaque temps dure une noire et chaque unité dure une
croche. Nous avons alors une série de 6 croches, que nous pouvons
réarranger comme nous le souhaitons. Exemple :

#+begin_center
C‿C‿C C C‿C
#+end_center

On obtient alors le rythme :

#+begin_center
Np C N
#+end_center

Dans certains cas, il est nécessaire d’affiner encore plus et on
subdiviser alors les 6 croches en 12 double-croches.

Les rythmes les plus courants sont :

  - les rythmes binaires, obtenus en décomposant une pulsation binaire
    en 2, en 4, en 8 ou en 16
  - les rythmes ternaires, obtenus en décomposant une pulsation
    ternaire en 3, en 6, ou en 12


** Adaptation des durées

Il est possible d’adapter une cellule rythmique prévue pour une durée
/D/ afin qu’elle occupe une durée /M × D/. Il suffit pour cela
de multiplier la durée de chaque note par /M/.

Il est possible d’adapter une cellule rythmique prévue pour une durée
/D/ afin qu’elle occupe une durée /D / M/.  Il suffit
pour cela de diviser la durée de chaque note par /M/.


**** Triolet et duolet

Le triolet multiplie la durée par 2 / 3 et permet donc de placer un
rythme ternaire dans une pulsation binaire.

Le duolet multiplie la durée par 3 / 2 et permet donc de placer un
rythme binaire dans une pulsation ternaire.


**** Note pointée

Le rapport :

#+begin_center
durée d’une blanche pointée / durée d’une blanche
#+end_center

est de 3 / 2. Lors des variations de structure rythmique au sein d’un
même morceau, il est parfois souhaitable de disposer d’un rapport plus
proche de 1, comme le rapport :

#+begin_center
durée d’une noire pointée / durée d’une blanche
#+end_center

qui nous donne 3 / 4. On divise alors par deux la durée de chaque
cellule rythmique occupant une blanche pointée afin qu’elle n’occupe
plus qu’une noire pointée. Ce procédé nous donne par exemple :

#+ATTR_HTML: :class plat
| Bp    | —> | Np    |
| Ν N N | —> | C C C |
| B N   | —> | N C   |


** Silences


*** Remplacement par un silence

On peut très bien remplacer une ou plusieurs notes d’une cellule
rythmique par des silences de mêmes durées. Par exemple, si on
escamote la première note de :

#+begin_center
N C N C
#+end_center

on obtient :

#+begin_center
ns C N C
#+end_center


*** Staccato

Les cellules rythmiques construites par décomposition et liaison
donnent des rythmes fluides, c’est-à-dire ne comprenant pas de
silences. On peut toutefois raccourcir les notes et intercaler des
silences afin de produire ce qu’on appelle un staccato. Par exemple,
on peut écourter les notes de :

#+begin_center
Np C N
#+end_center

obtenant le rythme sec :

#+begin_center
C ns dC dcs C cs
#+end_center


** Oscillation

Le rythme d’une oscillation peut être construit en combinant plusieurs
cellules rythmiques, à raison d’une cellule par pulsation.

Les cellules rythmiques binaires s’appliquent aux pulsations
binaires, tandis que les cellules rythmiques ternaires s’appliquent
aux pulsations ternaires.


** Usuelles

Cette section recense les cellules rythmiques les plus courantes.


*** Notes longues et brèves

Les cellules rythmiques sont caractérisées par le nombre de notes
présentes après décomposition et liaison. Parmi celles-ci, on
distingue les notes « longues » des notes « brèves ». Il s’agit d’une
distinction approximative, deux notes classées dans la même catégorie
(longue ou brève) n’ayant pas forcément une durée exactement
identique. Il arrive aussi que cette distinction n’ait pas lieu
d’être, quand :

  - toutes les notes ont des durées à peu près identiques
    + on parle alors de notes « égales »
  - la cellule rythmique comporte plus de deux catégories de durées

Nous utilisons les notations :

# symboles :
#
# &mdash; = —
# &union; = ∪
# &perp;= ⊥

| — | note longue |
| ∪ | note brève  |
| ⊥ | note égale  |

/Remarque/ : cette notion de contraste entre longues et brèves n’est
pas sans rappeler les syllabes lourdes et légères de la [[file:litera-01-rimailleur.org::#heading:metriqueQuantitative][métrique quantitative]]
en poésie. Toutefois, la palette des durées musicales est
nettement plus nuancée que cette simple dualité, et permet donc des
possibilités beaucoup plus nombreuses, ainsi que nous allons le voir.

Dans la suite, nous considérons une pulsation ternaire de durée égale
à une blanche pointée et une pulsation binaire (ou quaternaire) de
durée égale à une ronde. Les annexes comportent également une [[file:musica-12-annexe.org::#heading:cellules_rythmiques][section]]
avec des tableaux récapitulatifs.


*** Ternaires

Considérons une pulsation ternaire durant une blanche pointée. Elle
peut se décomposer au choix en :

  - trois noires
  - six croches
  - douze double-croches

ce qui nous donne directement les cellules rythmiques à notes égales :

#+ATTR_HTML: :class plat
| Bp          |
| N N N       |
| C C C C C C |
| 12 x dC     |

Les structures les plus courantes sur deux notes sont :

| — ∪        | B N      |
|            | B‿C C    |
| ∪ —        | N B      |
| ⊥ ⊥        | Np Np    |

Les autres structures les plus courantes sur trois notes sont :

| — ∪ ∪      | B C C    |
|            | Np C N   |
|            | Np N C   |
| ∪ — ∪      | C B C    |
|            | N Np C   |
|            | C Np N   |
| ∪ ∪ —      | C C B    |
|            | N C Np   |
|            | C N Np   |


*** Binaires

Considérons une pulsation binaire durant une ronde. Elle peut se
décomposer au choix en :

  - deux blanches
  - quatre noires
  - huit croches
  - seize double-croches

ce qui nous donne directement les cellules rythmiques à notes égales :

#+ATTR_HTML: :class plat
| R               |
| B B             |
| N N N N         |
| C C C C C C C C |
| 16 x dC         |

Les autres structures les plus courantes sur deux notes sont :

| — ∪        | Bp N     |
|            | Bpp C    |
| ∪ —        | N Bp     |

Les structures les plus courantes sur trois notes sont :

| — ∪ ∪      | B N N    |
| ∪ — ∪      | N B N    |
| ∪ ∪ —      | N N B    |


* Cellules composites

#+TOC: headlines 1 local


** Introduction

Considérons une suite de cellules rythmiques consécutives. Si nous
adaptons leurs durées pour que l’ensemble occupe exactement une
pulsation, le résultat est une nouvelle cellule rythmique composée de
sous-cellules rythmiques simples. Une telle construction est appelée
*cellule composite*.

Remarquons que les cellules rythmiques combinées n’ont pas
nécessairement la même durée, avant ou après adaptation, et peuvent
même être de nature différente (binaire, ternaire, quaternaire, etc).

Un petit exemple avec une pulsation binaire :

#+ATTR_HTML: :class plat
| (R)/2 + (B B)/2 | ⟼ | B N N |

Dans l’exemple suivant, on combine une cellule rythmique binaire avec
une cellule rythmique ternaire pour produire une cellule composite
ternaire :

#+ATTR_HTML: :class plat
| (R)/2 + (N N)/2 | ⟼ | B C C |

Autre exemple, cette fois pour produire une cellule composite
quaternaire :

#+ATTR_HTML: :class plat
| (B B)/4 + (B N)/1 | ⟼ | C C B N |


*** Nomenclature

En juxtaposant deux rythmes, on obtient une cellule composite dite
*double*.

En juxtaposant trois rythmes, on obtient une cellule composite dite
*triple*.


** Extension

Prenons une cellule rythmique durant une pulsation et multiplions par
deux la durée de chaque note : on peut remplir deux pulsations avec le
rythme ainsi obtenu. En voici un exemple avec deux pulsations binaires
durant chacune une blanche :

#+ATTR_HTML: :class plat
| N B N | ⟼ | B R B |

Si nous multiplions par trois la durée de la cellule rythmique
initiale, nous pouvons remplir trois pulsations, si nous la
multiplions par /M/, nous pouvons remplir /M/ pulsations.


** Usuelles

Cette section recense les cellules composites les plus courantes.


*** Ternaires

Sur quatre notes :

#+ATTR_HTML: :class plat
| (Bp)/3 + (Bp)/3 + (B B)/4 | ⟼ | N N C C  |
| (Bp)/3 + (B B)/4 + (Bp)/3 | ⟼ | N C C N  |
| (B B)/4 + (Bp)/3 + (Bp)/3 | ⟼ | C C N N  |
| (Bp)/2 + (N N N)/2        | ⟼ | Np C C C |

Certaines combinaisons produisent une hémiole qui transforme la
structure interne de la pulsation, passant de trois temps binaires à
deux temps ternaires :

#+ATTR_HTML: :class plat
| (B N)/2 + (B N)/2 | ⟼ | N C N C |

Sur cinq notes :

#+ATTR_HTML: :class plat
| (Bp)/3 + (B B)/4 + (B B)/4 | ⟼ | N C C C C |
| (B B)/4 + (Bp)/3 + (B B)/4 | ⟼ | C C N C C |
| (B B)/4 + (B B)/4 + (Bp)/3 | ⟼ | C C C C N |


*** Binaires

sur quatre notes :

#+ATTR_HTML: :class plat
| (Bp N)/2 + (B B)/2  | ⟼ | Np C N N  |
| (B B)/2 + (Bp N)/2  | ⟼ | N N Np C  |
| (Bp N)/2 + (Bp N)/2 | ⟼ | Np C Np C |

Sur cinq notes :

#+ATTR_HTML: :class plat
| (R)/2 + (B B)/4 + (B B)/4 | ⟼ | B C C C C |
| (B B)/4 + (R)/2 + (B B)/4 | ⟼ | C C B C C |
| (B B)/4 + (B B)/4 + (R)/2 | ⟼ | C C C C B |

Sur six notes :

#+ATTR_HTML: :class plat
| (B B)/2 + (B B)/4 + (B B)/4 | ⟼ | N N C C C C |
| (B N N)/2 + (B N N)/2       | ⟼ | N C C N C C |
| (B N N)/2 + (N N B)/3       | ⟼ | N C C C C N |

Sur sept notes :

#+ATTR_HTML: :class plat
| (B N N)/2 + (N N N N)/2 | ⟼ | N C C C C C C |


* Syncopes

#+TOC: headlines 1 local

** Introduction

Une *syncope* est une note entamée à l’intérieur d’une pulsation et
qui se prolonge au début de la pulsation suivante. On peut construire
une syncope en disposant deux cellules rythmiques sur deux pulsations
consécutives et en liant la dernière note de la première pulsation à
la première note de la seconde. Voici quelques exemples :

#+ATTR_HTML: :class plat
| pulsation binaire (B B)    | : | B B‿B B     | ⟼ | B R B     |
| pulsation ternaire (Ν N N) | : | N N N‿N N N | ⟼ | Ν N B Ν N |

Dans la suite, nous considérons une pulsation ternaire de structure
/N N N/ et une pulsation binaire (ou quaternaire) de structure /B B/.


*** Prolongation

Il est possible de prolonger une syncope d’une ou de plusieurs
pulsations. Exemple sur une pulsation binaire :

#+ATTR_HTML: :class plat
| N N‿N‿N‿N N | ⟼ | N R N |


*** Rythme syncopé

Dans le cas où plusieurs syncopes consécutives sont réalisées, on
parle de rythme syncopé. Exemple sur une pulsation binaire de
structure N N :

#+ATTR_HTML: :class plat
| B B‿B B‿B B | ⟼ | B R R B |


** Contretemps

Les contretemps sont similaires aux syncopes, mais au lieu de
prolonger la note, on place un silence sur le début de la pulsations
suivante.

Exemple sur une pulsation binaire :

#+ATTR_HTML: :class plat
| B B‿B B | ⟼ | B B bs B |

Exemple sur une pulsation ternaire :

#+ATTR_HTML: :class plat
| N N N‿N N N | ⟼ | N N N ns N N |


** Implicite ou déplacement

Il existe deux méthodes permettant de relier syncope et mélodie :

  - lorsque la syncope ou le contretemps est réalisé en supprimant une ou
    plusieurs notes par rapport à un thème de référence préalablement
    entendu ou simplement sous-entendu, on parle de *motif implicite*.
  - par contre, si la syncope ou le contretemps est réalisé en
    déplaçant la suite du thème, on parle de *déplacement*.

Pour illustrer ces deux philosophies, partons du thème :

#+begin_center
do ré mi si la sol
#+end_center

Un exemple de motif implicite sera alors :

#+begin_center
do ré mi—— la sol
#+end_center

où le /mi——/ est soit prolongé, soit suivi par un silence, ce qui rend
le /si/ implicite.

Le même exemple avec déplacement nous donne :

#+begin_center
do ré mi—— si la sol
#+end_center

où la prolongation du /mi——/ retarde le dernier groupe de notes
/si la sol/. Notons qu'il est aussi possible de produire une syncope
en raccourcissant le /mi/. Un déplacement peut donc se produire par
*report* ou *anticipation*.


* Cellules syncopées

#+TOC: headlines 1 local


** Introduction

Une *cellule syncopée* est une cellule rythmique :

  - composée de plusieurs temps
  - dont une note à l’intérieur d’un temps se prolonge au début du
    temps suivant

On peut construire une cellule syncopée en adaptant la durée de
plusieurs cellules rythmiques consécutives pour qu’elles occupent
chacune un temps, puis en liant la dernière note d’un de ces temps à
la première note du temps suivant.

Voici quelques exemples :

#+ATTR_HTML: :class plat
| pulsation binaire (2 temps, B B)    | : | N N‿N N     | ⟼ | N B N     |
| pulsation ternaire (3 temps, Ν N N) | : | N N N‿N N N | ⟼ | Ν N B Ν N |

Pour produire un rythme syncopé, il faut effectuer plusieurs liaisons
à la frontière de temps consécutifs. La structure de la pulsation doit
cependant le supporter : ternaire, quaternaire, etc.


** Usuelles

Cette section recense les cellules syncopées les plus courantes.


*** Ternaires

Le tableau suivant reprend quelques cellules syncopées courantes
basées sur des pulsations ternaires de 3 noires :

| Liaison(s)  | Résultat  |
|-------------+-----------|
| N C‿N C     | N Np C    |
| N‿C C N     | Np C N    |
| N C C‿N     | N C Np    |
| C C‿C C‿C C | C N N C   |
| C C‿C C C C | C N C C C |


*** Binaires

Le tableau suivant reprend quelques cellules syncopées courantes
basées sur des pulsations binaires de 2 blanches, équivalentes à des
pulsations quaternaires de 4 noires :

| Liaison(s)      | Résultat      |
|-----------------+---------------|
| N N‿N N         | N B N         |
| Np C‿Np C       | Np B C        |
| Np C‿N N        | Np Np N       |
| N N‿C C N       | N Np C N      |
| C C‿C C‿C C‿C C | C N N N C     |
| C C C C‿C C C C | C C C N C C C |
