
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 08 : La clé des chants
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Raconter une histoire

#+ATTR_HTML: :class lettrine
Une oeuvre musicale est une histoire à part entière, une histoire
composée de thèmes. Certains de ces thèmes plantent le décor, tandis
que d’autres incarnent les personnages. Des personnages qui
interagissent, dialoguent, questionnent, répondent, changent d’humeur
suivant le contexte ou l’interlocuteur. Mais le décor est en lui-même
un personnage, et il peut se réveiller à tout moment pour jouer un
rôle plus actif, un peu comme ces créatures des contes fantastiques,
en apparence inanimées mais que l’on découvre subitement douées de
mouvement et de parole.

L’idée est donc d’explorer les possibilités offertes par différentes
combinaisons de thèmes afin de développer les scènes de la pièce
musicale. Le nombre de thèmes impliqués dans une scène détermine en
partie son style : un contraste entre deux thèmes sera moins
mouvementé que l’agitation d’une foule.


* Variations

#+TOC: headlines 1 local


** Introduction

Il est fréquent en musique de présenter un thème puis des variations
de ce thème. Les procédés aboutissant à ces variations sont nombreux,
voici les plus courants.


** Inverser la mélodie

On peut inverser le sens des intervalles mélodiques et/ou le sens de
lecture.


** Transposer

On peut transposer la mélodie.


** Changer le mode

Changer le mode modifie le caractère des accords du thème.


** Changer l’ornementation

On peut changer le type ou la quantité des ornements présents.


*** Agrémenter

Agrémenter une note longue consiste à la remplacer par une suite de
notes rapides dont la moyenne correspond à la hauteur de la note
longue. Par extension, agrémenter un groupe de notes longues consiste
à agrémenter chacune d’entre-elles. L’agrémentation permet d’ajouter
de l’ornementation à la musique.


*** Épurer

Épurer une suite de note rapides consiste à les remplacer par une note
longue correspondant à leur moyenne. On peut également diviser un
thème en plusieurs groupes de notes, chaque groupe étant ensuite épuré
et donc remplacé par une note plus longue.

/Remarque/ : au lieu de faire correspondre les notes longues aux
moyennes des notes rapides, on peut également choisir la note rapide
qui semble la plus pertinente en fonction du contexte musical : la
première note de chaque temps, mesure, ...


** Changer le rythme

On peut changer le rythme du thème tout en conservant la mélodie.


*** Augmenter / Diminuer

On peut augmenter ou diminuer la longueur d’un thème en multipliant
par un même facteur la durée de chaque note.

Exemple d’augmentation avec un facteur 2 :

#+begin_center
N C C —> B N N
#+end_center

Exemple de diminution avec un facteur 1/2 :

#+begin_center
N C C —> C dC dC
#+end_center


*** Conversions

Il est possible de convertir une succession de cellules rythmiques
binaires en cellules rythmes ternaires, et vice versa. Ces conversions
se font en conservant l’allure générale (nombre de notes, notes
longues, brèves ou égales, etc) de chaque cellule. Plusieurs choix
sont parfois possibles.


* Inversion

#+TOC: headlines 1 local


** Introduction

Un *miroir* inverse le sens des intervalles mélodiques : les
intervalles haussiers deviennent baissiers et vice versa.

Une *rétrogradation* inverse l’ordre chronologique des notes, comme si
la mélodie était lue à l’envers.


** Miroir libre

L’opération en miroir libre ne se soucie pas de l’aspect mineur,
majeur ou juste des intervalles traversés.

Exemple avant inversion :

#+ATTR_HTML: :class plat
| notes       | : | do | ré    | mi    | fa    |
| intervalles | : |    | 2de M | 2de M | 2de m |

et après :

#+ATTR_HTML: :class plat
| notes       | : | do | si    | la    | sol   |
| intervalles | : |    | 2de m | 2de M | 2de M |


** Miroir strict

Le miroir strict respecte le caractère majeur, mineur ou juste des
intervalles traversés.


*** Sans altération

En l’absence d’altération, on utilise la symétrie naturelle des notes
diatoniques par rapport à la note /ré/ :

#+ATTR_HTML: :class plat
| notes       | : | la    | si    | do    | ré | mi    | fa    | sol   |
| intervalles | : | 2de M | 2de m | 2de M |    | 2de M | 2de m | 2de M |

Considérons comme exemple le motif :

#+begin_center
mi la sol la ré si do
#+end_center

L’intervalle entre la note /ré/ et la première note du motif, /mi/,
est d’une seconde majeure ascendante. On reporte cet intervalle dans
l’autre sens en partant de /ré/, et on obtient la note /do/. Il nous
suffit alors de partir du /do/ et de reproduire les intervalles du
motif de départ en les inversant :

#+begin_center
do sol la sol ré fa mi
#+end_center

On vérifie que les amplitudes des intervalles sont bien respectés :

#+ATTR_HTML: :class plat
| avant inversion | : | mi | la  | sol   | la    | ré  | si    | do    |
|                 |   |    | +   | -     | +     | -   | -     | +     |
| intervalles     | : |    | 4te | 2de M | 2de M | 5te | 3ce m | 2de m |
|                 |   |    | -   | +     | -     | +   | +     | -     |
| après inversion | : | do | sol | la    | sol   | ré  | fa    | mi    |


*** Avec altérations

Lorsque des altérations sont présentes dans la tonalité, il faut
reproduire la transposition qui a causé ces altérations pour trouver
la note qui va remplacer /ré/ comme centre de symétrie.

Par exemple, en /la majeur/, on a /fa^{#}/, /do^{#}/ et /sol^{#}/
comme altérations. La transposition depuis la gamme modèle de /do
majeur/ est d’une tierce mineure descendante. Une tierce mineure plus
bas que /ré/, nous avons la note /si/. On vérifie que /si/ est bien
le centre de symétrie de la tonalité de /la majeur/ :

#+ATTR_HTML: :class plat
| notes       | : | fa^{#} | sol^{#} | la    | si | do^{#} | ré    | mi    |
| intervalles | : | 2de M  | 2de m   | 2de M |    | 2de M  | 2de m | 2de M |


* Mutation
:PROPERTIES:
:CUSTOM_ID: section:mutation
:END:

#+TOC: headlines 1 local

** Introduction

La *mutation* consiste à adapter certaines notes d’un motif transposé
afin de l’intégrer à la tonalité de départ.

Les adaptations ont lieu pour conserver :

  - les notes de la gamme
  - les mêmes altérations, ni plus ni moins
  - les degrés forts
  - les fonctions tonales

Ce procédé s’applique aussi lorsque plusieurs mélodies superposées
sont transposées.

Précisons que la mutation ne s’applique pas à toutes les notes du
thème transposé, mais seulement lorsque le compositeur le juge
nécessaire pour rester dans la tonalité de départ.


** Transposition

Une transposition peut ajouter ou supprimer des altérations, générant
ainsi des notes qui ne font pas partie de la tonalité de départ.

La mutation va alors annuler ces ajouts ou suppressions d’altérations,
ceci afin que toutes les notes du motif transposé soient incluses dans
la tonalité.

#+begin_center
⁂
#+end_center

Choisissons /sol majeur/ comme tonalité de départ. La gamme est une
quinte plus haut que la tonalité modèle de /do majeur/, et contient
donc l’altération /fa^{#}/ :

#+begin_center
sol la si do ré mi /fa^{#}/ sol
#+end_center

Si nous transposons vers /fa majeur/, située une quinte plus bas que
/do majeur/, nous obtenons l’altération /si^b/ :

#+begin_center
fa sol la /si^b/ do ré mi fa
#+end_center

Si nous souhaitons rester dans la tonalité de départ, il nous faut :

  - annuler l’altération /si^b/ produite par la transposition
  - restaurer l’altération /fa^{#}/ de la tonalité de départ

Nous obtenons :

#+begin_center
/fa^{#}/ sol la si do ré mi /fa^{#}/
#+end_center


** Dualité tonale

Dans le cas d’une transposition à la quinte ascendante, le procédé de
mutation va même plus loin car il veille à conserver l’équilibre entre
tonique et dominante.

Si nous effectuons une transposition exacte, nous obtenons :

#+ATTR_HTML: :class plat
| Initial   |    | Intervalle     |    | Transposé   |
|-----------+----+----------------+----+-------------|
| tonique   | —> | 5te ascendante | —> | dominante   |
| dominante | —> | 5te ascendante | —> | sus-tonique |

La mutation va alors transformer la sus-tonique en tonique pour
conserver une dualité intégrée à la tonalité de départ. Ce procédé
nous donne implicitement un intervalle de transposition de quarte pour
la dominante. :

#+ATTR_HTML: :class plat
| tonique   | —> | 5te ascendante | —> | dominante |
| dominante | —> | 4te ascendante | —> | tonique   |

La dualité tonique — dominante du thème de départ s’est donc muée en
dualité dominante — tonique dans le thème transposé.

Il va de soi que les note environnantes peuvent également être
modifiées afin d’ajuster la mélodie.


*** Symétrie

La transposition suivie de mutations transforme la sous-dominante et
la dominante en tonique. Si on souhaite établir une symétrie dans
l’opération, il faut s’arranger pour que la tonique puisse être
transformée au choix en sous-dominante ou en dominante.

On a donc le schéma :

#+ATTR_HTML: :class plat
| Initial        |    | Intervalle     |    | Transposé      |
|----------------+----+----------------+----+----------------|
| tonique        | —> | 5te ascendante | —> | dominante      |
| tonique        | —> | 4te ascendante | —> | sous-dominante |
| dominante      | —> | 4te ascendante | —> | tonique        |
| sous-dominante | —> | 5te ascendante | —> | tonique        |


** Extension de la dualité tonale

#+TOC: headlines 1 local

*** Introduction

Il existe plusieurs techniques pour étendre la dualité des notes
tonales au reste de la gamme.

Ces techniques ne donnent pas forcément un résultat équivalent, au
compositeur de choisir laquelle lui semble la plus pertinente. La
technique utilisée peut aussi varier d’une note à l’autre, en fonction
du contexte musical.


*** Compartiments

On divise la gamme en deux compartiments délimités par la tonique et
la dominante :

  - du degré 1 au degré 5, on transpose à la quinte ascendante
  - du degré 5 au degré 1, on transpose à la quarte ascendante

En tant que notes frontières, la tonique et la dominante sont
transposées au choix par une quinte ou une quarte ascendante.

Le tableau suivant nous donne la liste des degrés, avant et après
l’opération :

#+ATTR_HTML: :class plat
| avant | : | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 1 |
| après | : | 5 | 6 | 7 | 1 | 1 | 2 | 3 | 4 |

Exemple en partant de /do majeur/ :

#+ATTR_HTML: :class plat
| avant | : | do  | ré | mi | fa | sol | la | si | do |
| après | : | sol | la | si | do | do  | ré | mi | fa |

On remarque une symétrie complète dans cette table :

  - le /do/ correspond au /sol/, et vice versa
  - le /ré/ correspond au /la/, et vice versa
  - etc


*** Fonctions

Une note d’un accord faisant fonction de dominante ou de
sous-dominante est transposée vers la note correspondante dans un
accord faisant fonction de tonique.

Par symétrie, une note d’un accord faisant fonction de tonique est
transposée vers la note correspondante dans un accord faisant fonction
de dominante ou de sous-dominante.


**** Accords parfaits

Le choix le plus évident pour assurer les fonctions tonales est celui
d’accords parfaits situés sur les degrés forts.

Prenons comme exemple la tonalité de /do majeur/.

L’accord parfait du degré 1 peut être transformé en accord parfait du
degré 5. Comme chaque note doit garder sa place dans l’accord on en
déduit les relations :

#+ATTR_HTML: :class plat
| do  | —> | sol |
| mi  | —> | si  |
| sol | —> | ré  |

Symétriquement, l’accord parfait du degré 5 devient accord parfait du
degré 1 :

#+ATTR_HTML: :class plat
| sol | —> | do  |
| si  | —> | mi  |
| ré  | —> | sol |

Si l’accord parfait du degré 1 est transformé en accord parfait du
degré 4, on a plutôt :

#+ATTR_HTML: :class plat
| do  | —> | fa |
| mi  | —> | la |
| sol | —> | do |

Symétriquement, l’accord parfait du degré 4 devient accord parfait du
degré 1 :

#+ATTR_HTML: :class plat
| fa | —> | do  |
| la | —> | mi  |
| do | —> | sol |

En compilant tous ces résultats, on a la table :

#+ATTR_HTML: :class plat
| avant | : | fa | la | do  | mi | sol | si | ré  |
| après | : | do | mi | sol |    |     |    |     |
|       |   |    |    | sol | si | ré  |    |     |
|       |   |    |    | fa  | la | do  |    |     |
|       |   |    |    |     |    | do  | mi | sol |

ou, en simplifiant et en triant les notes du grave à l’aigu :

#+ATTR_HTML: :class plat
| avant | : | do  | ré  | mi | fa | sol | la | si |
| après | : | sol | sol | la | do | do  | mi | mi |
|       |   | fa  |     | si |    | ré  |    |    |

En terme de degrés, on a :

#+ATTR_HTML: :class plat
| avant | : | 4 | 6 | 1 | 3 | 5 | 7 | 2 |
| après | : | 1 | 3 | 5 |   |   |   |   |
|       |   |   |   | 5 | 7 | 2 |   |   |
|       |   |   |   | 4 | 6 | 1 |   |   |
|       |   |   |   |   |   | 1 | 3 | 5 |

ou, sous forme concise :

#+ATTR_HTML: :class plat
| avant | : | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| après | : | 5 | 5 | 6 | 1 | 1 | 3 | 3 |
|       |   | 4 |   | 7 |   | 2 |   |   |


* Marches

#+TOC: headlines 1 local


** Introduction

Une *marche* se forme lorsqu’on répète plusieurs fois de suite une
même structure génératrice /S_0/, structure qui se voit transposée
d’un intervalle /I/ constant à chaque nouvelle apparition. On génère
donc une suite :

#+begin_center
S_0 — S_1 — S_2 — S_3 — =...=
#+end_center

où :

#+ATTR_HTML: :class plat
| S_1   | =     | S_0 transposé d’un intervalle I     |
| S_2   | =     | S_1 transposé d’un intervalle I     |
| S_3   | =     | S_2 transposé d’un intervalle I     |
| =...= | =...= | =...=                               |
| S_n   | =     | S_{n-1} transposé d’un intervalle I |

Afin d’éviter la monotonie, le thème générateur de la marche peut être
soumis à des variations, l’essentiel étant de conserver une certaine
continuité dans la structure. On a alors :

#+ATTR_HTML: :class plat
| S_1   | =     | variation de S_0 transposé d’un intervalle I     |
| S_2   | =     | variation de S_1 transposé d’un intervalle I     |
| S_3   | =     | variation de S_2 transposé d’un intervalle I     |
| =...= | =...= | =...=                                            |
| S_n   | =     | variation de S_{n-1} transposé d’un intervalle I |


** Structure génératrice

Si la structure génératrice est de type :

  - harmonique, on parle de *marche harmonique*

  - mélodique, on parle de *marche mélodique*

  - =...=


** Transposition

On dit qu’une marche est :

  - *ascendante* lorsque l’intervalle de transposition est ascendant

  - *descendante* lorsque l’intervalle de transposition est descendant


** Modulante ou pas

Lorsque les transpositions successives de la marche n’utilisent pas de
mutations, elles produisent ou suppriment des altérations par rapport
à la tonalité de départ. On dit alors que la marche est *modulante*.

Lorsque les transpositions successives de la marche utilisent des
mutations pour conserver les altérations de départ, on dit que la
marche est *non modulante*.

Enfin, une marche peut être *hybride*, certaines étapes étant
modulantes et d’autres non.

Ainsi, il existe des marches essentiellement non modulantes dans
lesquelles certains passages sont altérés afin de constituer des
transpositions exactes des passages entendus précédemment dans la même
marche. On parle alors d’ *altération par analogie*.


* Marches harmoniques

#+TOC: headlines 1 local

** Introduction

Une *marche harmonique* se forme lorsqu’on répète plusieurs fois de
suite une même structure génératrice harmonique /H_0/, structure qui
se voit transposée d’un intervalle /I/ constant à chaque nouvelle
apparition. On a donc :

#+begin_center
H_0 — H_1 — H_2 — H_3 — =...=
#+end_center

avec :

#+ATTR_HTML: :class plat
| H_1   | =     | variation de H_0 transposé d’un intervalle I     |
| H_2   | =     | variation de H_1 transposé d’un intervalle I     |
| H_3   | =     | variation de H_2 transposé d’un intervalle I     |
| =...= | =...= | =...=                                            |
| H_n   | =     | variation de H_{n-1} transposé d’un intervalle I |

On peut exposer la structure interne du thème en notant la suite
d’accords de chaque variation entre accolades. Voici un exemple de
marche descendant par tierces :

#+ATTR_HTML: :class plat
| { 5 - 6 } | — | { 3 - 4 } | — | { 1 - 2 } | — | =...= |
| H_0       | — | H_1       | — | H_2       | — | =...= |

Une autre montant par secondes :

#+ATTR_HTML: :class plat
| { 5 - 1 } | — | { 6 - 2 } | — | { 7 - 3 } | — | =...= |
| H_0       | — | H_1       | — | H_2       | — | =...= |


** Transposition

On classe les marches harmoniques suivant leur intervalle de
transposition :

  - quinte ascendante ou descendante
  - tierce ascendante ou descendante
  - seconde ascendante ou descendante

Les structures harmoniques étant considérées comme équivalentes
lorsque l’octave change, les autres marches peuvent être assimilées
aux cas fondamentaux présentés ci-dessus. Ainsi :

  - une marche par quarte est assimilée à une marche par quinte de sens inverse
  - une marche par sixte est assimilée à une marche par tierce de sens inverse
  - une marche par septième est assimilée à une marche par seconde de sens inverse


** Marches glissantes

#+TOC: headlines 1 local

*** Introduction

Une *marche glissante* est une marche harmonique où la fin de chaque
variation de la structure génératrice se révèle être également une
introduction à la variation suivante. La musique est alors toujours en
mouvement, et donne l’impression de « glisser » d’une variation à la
suivante.

Le dernier accord de /H_n/ est *réinterprété* pour devenir le premier
accord de /H_{n + 1}/. En utilisant le symbole « ≡ » pour désigner la
réinterprétation, on a le schéma :

#+begin_center
D_1 — D_2 — =...= — D_m ≡ D_1
#+end_center

où les /D_1/, /D_2/, =...=, /D_m/ sont les degrés des accords de la
structure génératrice. Ce type de marche produit une suite d’accords
du type :

#+begin_center
D_1 — D_2 — =...= — D_m ≡ D_1 — =...= — D_m ≡ D_1 — =...= — D_m ≡ D_1 — =...=
#+end_center

#+begin_center
⁂
#+end_center

Considérons un exemple où la structure génératrice de la marche est
constituée de la suite d’accords :

#+begin_center
4 — 5 — 1
#+end_center

Le dernier accord, du degré 1, doit pouvoir être réinterprété comme un
accord du degré 4 pour entamer la variation suivante.

#+begin_center
4 — 5 — 1 ≡ 4
#+end_center

Nous sommes donc forcés de changer de tonalité en déplaçant la tonique
une quarte plus bas pour que le degré 1 devienne un degré 4.

Plaçons nous en /do majeur/ à titre d’illustration. Le degré 1, un
/do/, doit pouvoir être réinterprété comme le degré 4 d’une nouvelle
gamme. Dans cette nouvelle gamme :

  - le degré 4 est un /do/
  - le degré 3 est un /si/
  - le degré 2 est un /la/
  - le degré 1 est un /sol/

La nouvelle tonalité est donc celle de /sol majeur/. Comme le /sol/
correspond au degré 5 de la gamme de départ /do majeur/, on peut
réécrire le schéma de la marche sous la forme :

#+begin_center
4 — 5 — 1 ≡ 4 de 5
#+end_center

Ce schéma génère la marche :

#+begin_center
4 — 5 — 1 ≡ 4 de 5 — 5 de 5 — 1 de 5 ≡ 4 de 2 — 5 de 2 — 1 de 2 ≡ =...=
#+end_center

Ce type de marche peut être modulante ou non modulante, suivant que
l’on tient compte ou non des altérations des gammes traversées.

Voici quelques exemples de réinterprétation  :

  - 2 — 5 — 1 ≡ 2
  - 6 — 2 — 5 — 1 ≡ 6


*** Descente de quinte

Le schéma :

#+begin_center
5 — 1 ≡ 5
#+end_center

produit la suite :

#+begin_center
5 — 1 ≡ 5 de 4 — 1 de 4 ≡ 5 de 7 — 1 de 7 ≡ 5 de 3 — 1 de 3 ≡ 5 de 6 — =...=
#+end_center

Par rapport à la gamme de départ, on retrouve donc le cycle des quintes :

#+begin_center
5 — 1 — 4 — 7 — 3 — 6 — 2 — 5 — 1 — =...=
#+end_center

On peut réaliser ce schéma en utilisant des accords de septième ou de
neuvième, une note ou plus étant résolue à chaque accord tandis qu’une
autre devient dissonante.

En voici un exemple avec des accords de septième, aux altérations
près :

#+ATTR_HTML: :class plat
| S | : | fa   | /fa/ | /mi/ | mi   |
| A | : | /do/ | /si/ | /si/ | /la/ |
| T | : | la   | ré   | sol  | do   |
| B | : | ré   | sol  | do   | fa   |

Au premier enchaînement, le /do/ se résout en /si/ à l’alto, au second
le /fa/ se résout en /mi/ au soprano, et au dernier le /si/ se résout
en /la/ à l’alto.


** Marches divertissantes

#+TOC: headlines 1 local

*** Divertissement modulant

On peut créer une *surprise* élégante en développant une marche
harmonique *non modulante*, suivie d’une *modulation* au ton auquel on
serait arrivé si la marche avait été modulante.

Un petit exemple :

  1. On part de /ré majeur/ qui comporte les altérations : /fa^{#}/,
    /do^{#}/

  2. On fait entendre une structure génératrice contenant les notes /ré
     mi fa^{#} sol la si do^{#}/

  3. On descend les quintes jusqu’au do sans moduler :

     1) /sol la si do^{#} ré mi fa^{#}/

     2) /do^{#} ré mi fa^{#} sol la si/

  4. Surprise : on module en /do majeur/ en faisant entendre un thème
     contenant les notes /do ré mi fa sol la si/


*** Divertissement non modulant

On peut également suivre le procédé inverse lorsqu’on module à un ton
relatif. Utiliser une marche *modulante* qui accumule les altérations
en cours de route, puis *supprimer* toutes les altérations causées par
la marche une fois arrivé au ton désiré.

Un exemple :

  1. On part de /la mineur/ qui ne comporte pas d’altération

  2. On fait entendre un thème contenant les notes /la si do ré mi fa sol/

  3. On descend les quintes jusqu’au /do/ en modulant :

     1) /ré mi fa sol la si^b do/

     2) /sol la si^b do ré mi^b fa/

     3) /do ré mi^b fa sol la^b si^b/

  4. Surprise : on module en /do majeur/ en faisant entendre un thème
     où les altérations causées par la marche sont supprimées : /do ré
     mi fa sol la si/


* Imitation

#+TOC: headlines 1 local


** Introduction

L’imitation consiste à reprendre des thèmes d’une ou plusieurs voix
données afin de les intégrer à une autre voix. Ce principe peut être
mutuel : les voix peuvent s’imiter les unes les autres.


** Parallèle

La forme la plus simple d’imitation consiste à créer par transposition
un thème *parallèle* à un thème donné. Le thème parallèle est appelé
*doublure*. On dit aussi que le thème d’origine est *doublé*.

L’intervalle entre le thème d’origine et la réplique parallèle peut
être :

  - un unisson
  - une octave
  - une quinte
  - une quarte
  - une tierce
  - une sixte
  - une dixième
  - une douzième
  - etc.


*** Unisson

La doublure la plus simple se fait à l’unisson ; le thème d’origine
est alors simplement recopié pour produire la doublure.

La doublure à l’unisson peut être utilisée pour augmenter le volume de
l’original : on utilise alors plusieurs instruments identiques jouant
la même voix. Si l’on souhaite obtenir un timbre synthétique, on peut
aussi faire jouer la même voix par des instruments différents.


** Variante

L’imitation par variante utilise des variations et de l’ornementation
afin de produire un thème qui soit créatif tout en demeurant similaire
au thème d’origine.


** Partielle

L’imitation partielle consiste à imiter certains éléments d’un thème
d’origine, les autres éléments étant ignorés.


** Multiple

L’imitation multiple rassemble des éléments provenant de plusieurs
voix différentes afin de produire un nouveau thème.


** Strette

Une *strette*, ou *resserrement* est une imitation qui commence avant
la fin de l’exposé du thème original imité.


* Constructions

#+TOC: headlines 1 local

** Ostinato

Un *ostinato* est un petit motif mélodique qui se répète en boucle sur
une voix, pendant que les autres voix varient leurs thèmes.

Afin de rendre cette répétition naturelle, la fin d’un ostinato est
généralement construite comme une introduction à son début.

Tout comme en littérature, on utilise souvent une clausule afin de
marquer la fin de la musique. Exemple :

#+begin_center
(do ré =...= mi si) (do ré =...= mi si) (do ré =...= mi si) =...= (do ré =...= mi si) do
#+end_center


** Hoquet

Le *hoquet* est une technique qui consiste à distribuer les éléments d’une
mélodie sur deux ou plusieurs voix.

Par exemple, si nous partons de la mélodie :

#+ATTR_HTML: :class plat
| Z | : | A1 | B1 | A2 | B2 | A3 | B3 | A4 | B4 |

nous pouvons réaliser un hoquet sur deux voix :

#+ATTR_HTML: :class plat
| V | : | A1 |    | A2 |    | A3 |    | A4 |    | =...= |
| W | : |    | B1 |    | B2 |    | B3 |    | B4 | =...= |


** Collage

Le *collage* consiste à découper une mélodie et à la répartir sur
plusieurs voix distinctes.


** Convergence

La *convergence* se compose de deux voix aux thèmes différents qui
convergent vers un même thème.


** Divergence

La *divergence* se compose de deux voix qui introduisent un même thème
en parallèle, pour ensuite diverger en introduisant un ou plusieurs
autres thèmes. La divergence peut être :

  - simple : une des voix diverge tandis que l’autre poursuit sur le même thème
  - double : les deux voix divergent vers des variantes ou des thèmes différents


** Méta

Les notes de référence d’une suite de notes forment une suite de notes
de niveau supérieur.

Par exemple, on peut transposer la suite /do ré mi/ de telle sorte que
les notes de référence (ici les notes initiales) tombent sur la suite
/ré fa mi ré/ :

#+ATTR_HTML: :class plat
| (/ré/ mi fa) | (/fa/ sol la) | (/mi/ fa sol) | (/ré/ mi fa) |


* Écho

#+TOC: headlines 1 local

** Introduction

L’écho consiste à jouer un motif sur une voix /V/, puis à jouer le
même motif, éventuellement transposé, sur une autre voix /W/.


** Une seule note

Il est possible d’appliquer le principe de l’écho à une seule note, en
faisant entendre la même note transposée d’une ou plusieurs octaves
successivement sur deux voix différentes.

Ce procédé est utilisé dans « Les barricades mystérieuses », de
François Couperin.


** Intervalle mélodique

On peut aussi utiliser un mouvement mélodique caractéristique.

Dans cet exemple, une seconde mineure mélodique descendante est
répètée de voix en voix :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /mi/ | mi       | =...= |
| B | : | ré   | /ré/ | /do^{#}/ | =...= |

Beethoven utilise cet intervalle avec des accords arpégés dans sa
sonate au clair de lune.


* Relais
:PROPERTIES:
:CUSTOM_ID: section:relais
:END:

#+TOC: headlines 1 local

** Introduction

Un relais consiste à continuer le développement d’un motif tout en le
déplaçant sur une autre voix. C’est généralement le caractère
particulier du motif qui permet de détecter le relais, mais on peut
également se servir d’un mouvement conjoint, d’une octave ou d’une
septième afin de renforcer la continuité de l’ensemble :

#+ATTR_HTML: :class plat
| S | : | la si la sol /fa/ |                  | =...= |
| B | : |                   | /mi/ ré do ré si | =...= |


** Tuilage polyphonique

Le *tuilage polyphonique* déplace une mélodie d’une voix à une autre
en utilisant un motif mélodique commun aux deux voix pour réaliser une
transition naturelle.

Exemple :

#+ATTR_HTML: :class plat
| V | : | A1 | A2 | A3 |    |    | =...= |
| W | : |    |    | A3 | A4 | A5 | =...= |


** Fausse relation chromatique

Une fausse relation chromatique peut servir à produire un relais.
Exemple :

#+ATTR_HTML: :class plat
| S | : | la la^b |       | =...= |
| B | : |         | sol   | =...= |


* Entrelac

#+TOC: headlines 1 local

** Introduction

Un *entrelac* est une mélodie résultant de l’entrelacement de deux ou
de plusieurs voix. Cette technique permet de donner l’impression que
plusieurs voix sont jouées alors qu’une seule est à l’oeuvre.

Considérons par exemple la configuration suivante :

#+ATTR_HTML: :class plat
| V | : | A1 | A2 | A3 | A4 | =...= |
| W | : | B1 | B2 | B3 | B4 | =...= |

Nous pouvons construire un entrelac sur une nouvelle voix /C/ à partir
des thèmes de /V/ et /W/, en les alternant par exemple :

#+ATTR_HTML: :class plat
| C | : | A1 | B1 | A2 | B2 | A3 | B3 | A4 | B4 |


*** Hoquet & Entrelac

Le hoquet est le procédé inverse de l’entrelac


** Ordre

Soit :

#+ATTR_HTML: :class plat
| V | : | A1 | A2 | A3 | A4 | =...= |
| W | : | B1 | B2 | B3 | B4 | =...= |

et l’entrelac associé :

#+ATTR_HTML: :class plat
| C | : | (A1 | B1) | (A2 | B2) | (A3 | B3) | (A4 | B4) | =...= |

On peut produire d’autres entrelacs en variant l’ordre à l’intérieur
de chaque groupe. On obtient alors par exemple :

#+ATTR_HTML: :class plat
| (A1 | B1) | (B2 | A2) | (A3 | B3) | (B4 | A4) | =...= |

Afin de souligner la liberté de l’ordre à l’intérieur des groupes,
nous les entourons d’accolades :

#+ATTR_HTML: :class plat
| { A1 | B1 } | { A2 | B2 } | { A3 | B3 } | { A4 | B4 } | =...= |


** Généralisation

Le procédé peut être généralisé à un nombre quelconque /N/ de voix.

Voici un exemple à trois voix :

#+ATTR_HTML: :class plat
| Va | : | A1 | A2 | A3 | A4 | =...= |
| Vb | : | B1 | B2 | B3 | B4 | =...= |
| Vc | : | F1 | F2 | F3 | F4 | =...= |

et le schéma de l’entrelac résultant :

#+ATTR_HTML: :class plat
| { A1 | B1 | F1 } | { A2 | B2 | F2 } | { A3 | B3 | F3 } | { A4 | B4 | F4 } | =...= |


** Environnement

Lorsqu’on construit un entrelac au sein d’une polyphonie, il faut
penser à la synchronisation avec les autres voix. Si nous construisons
aveuglément un entrelac à partir des mélodies /Va/ et /Vb/ dans :

#+ATTR_HTML: :class plat
| Va | : | A1 | A2 | A3 | A4 | =...= |
| Vb | : | B1 | B2 | B3 | B4 | =...= |
| Vc | : | F1 | F2 | F3 | F4 | =...= |

nous obtenons :

#+ATTR_HTML: :class plat
| C | : | A1 | B1 | A2 | B2 | A3    | B3    | A4    | B4    | =...= |
| Z | : | F1 | F2 | F3 | F4 | =...= | =...= | =...= | =...= | =...= |

L’entrelac sur la voix /C/ est donc totalement désynchronisé par
rapport à son environnement, représenté ici par la voix /Z/. Ce
problème peut être aisément corrigé en doublant la rapidité de chaque
thème de /C/ :

#+ATTR_HTML: :class plat
| C | : | A1 | B1 | A2 | B2 | A3 | B3 | A4 | B4 | =...= |
| Z | : | F1 |    | F2 |    | F3 |    | F4 |    | =...= |


*** Généralisation

Dans le cas d’un entrelac constitutée de /N/ mélodies, on sera amené à
augmenter la rapidité d’un facteur /N/.


** Basse d'Alberti

La basse d'Alberti est une ligne entrelacée arpégée : on place les
notes basses des accords au début de chaque temps et les autres notes
à l’intérieur. Le cadre harmonique est donc entièrement contenu dans
une seule voix.

Ce procédé permet de libérer d’autres voix pour faire entendre des
mélodies supplémentaires. On le rencontre aussi dans les partitions
pour clavier.


* Adaptation des figures de style

#+TOC: headlines 1 local


** Introduction

Les figures musicales sont directement inspirées des
[[file:litera-02-styleau.org][figures de style littéraires]].


** Discursives

L’analogie la plus simple entre les figures de style littéraires et
les figures musicales consiste à faire correspondre le discours à la
mélodie, et les blocs de texte aux thèmes musicaux. On construit ainsi
des figures mélodiques faisant intervenir des refrains, des variations
des inversions de thèmes, etc.

Ce type de construction est en tout point semblable aux figures de
style classiques.


** Polyphoniques

Un autre procédé consiste à faire correspondre, à chaque bloc de texte
d’un groupe, un thème présent sur une des voix d’une polyphonie.
Lorsqu’un même thème doit se retrouver simultanément ou successivement
sur plusieurs voix différentes, on le transpose afin de l’adapter à la
voix qui le reçoit.

Notons que certaines de ces figures sont déjà présentes dans les
constructions traditionnelles. Ainsi, la superposition d’une pédale
constante et d’une mélodie variée constitue un cas particulier de
cadre (AB - AC - ...) où le thème constant correspond à la pédale.

Le tableau ci-dessous donne des exemples de ces constructions. Tout
comme en littérature, nous introduisons la notation :

#+begin_center
A’ = variation de A
#+end_center


*** Rafale

#+ATTR_HTML: :class plat
| S | : | A |
| B | : | A |


*** Extension

#+ATTR_HTML: :class plat
| S | : | A | A |
| B | : | — | B |


*** Compression

#+ATTR_HTML: :class plat
| S | : | A | A |
| B | : | B | — |


*** Dilatation

#+ATTR_HTML: :class plat
| S | : | A | A |
| A | : | B | X |
| B | : | — | B |


*** Contraction

#+ATTR_HTML: :class plat
| S | : | A | A |
| A | : | X | B |
| B | : | B | — |


*** Cadre

#+ATTR_HTML: :class plat
| S | : | X1 | X2 |
| A | : | A  | A  |
| B | : | Y1 | Y2 |


*** Reprises

#+ATTR_HTML: :class plat
| S | : | A | B |
| B | : | B | C |


*** Arborescence

#+ATTR_HTML: :class plat
| S | : | B | C | D |
| B | : | A | B | B |


*** Factorisation

#+ATTR_HTML: :class plat
| S | : | X1 | X2 |
| A | : | A  | —  |
| B | : | Y1 | Y2 |


*** Réversion

#+ATTR_HTML: :class plat
| S | : | A | B |
| B | : | B | A |


*** Serpentine

#+ATTR_HTML: :class plat
| S | : | A |
| A | : | X |
| B | : | A |


*** Rondine

#+ATTR_HTML: :class plat
| S | : | A | C |
| B | : | B | A |


*** Ronde

#+ATTR_HTML: :class plat
| S | : | A | B | =...= | Y | Z |
| B | : | B | C | =...= | Z | A |


*** Moulin

#+ATTR_HTML: :class plat
| S | : | A | B | C |
| A | : | B | A | A |
| T | : | C | C | B |
| B | : | A | B | C |


*** Parallélisme

#+ATTR_HTML: :class plat
| S | : | A | A’ |
| B | : | B | B’ |


*** Parallélisme inversé

#+ATTR_HTML: :class plat
| S | : | A | B’ |
| B | : | B | A’ |


*** Double parallélisme

#+ATTR_HTML: :class plat
| S | : | A | A’ |
| A | : | B | B’ |
| T | : | C | D’ |
| B | : | D | C’ |


*** Fédération

#+ATTR_HTML: :class plat
| S | : | A | B | A |
| B | : | — | — | B |


*** Tête-bêche

#+ATTR_HTML: :class plat
| S | : | A | Y | A |
| B | : | X | B | B |


*** Produit tensoriel

#+ATTR_HTML: :class plat
| S | : | R | S | R | S |
| B | : | A | A | B | B |


*** Dualité

#+ATTR_HTML: :class plat
| S | : | R | S | S |
| B | : | A | A | B |


*** Tableau

#+ATTR_HTML: :class plat
| S | : | S1 | S2 | S3 | S1 | A1 |
| A | : | A1 | A2 | A3 | S2 | A2 |
| B | : | —  | —  | —  | S3 | A3 |


** Ajouter des voix

Certaines figures polyphoniques peuvent être étendues à un nombre de
voix plus élevé. Passons en revue quelques exemples.


*** Reprise étendue

#+ATTR_HTML: :class plat
| S | : | A | B |
| A | : | B | C |
| T | : | C | D |
| B | : | D | E |


* Figures musicales

#+TOC: headlines 1 local

** Introduction

Certaines figures sont principalement musicales et polyphoniques par
nature.


*** Adaptation à la littérature

Il est possible de les adapter à la littérature, mais on perd une
partie de la structure.


** Hélice

Un objet parcourt une hélice lorsqu’il tourne autour d’un centre qui
avence en ligne droite.

On peut représenter ce mouvement sur une polyphonie au moyen d’un
thème /A/ qui va tourner de voix en voix pendant que la polyponie
avance dans le temps. Exemple :

#+ATTR_HTML: :class plat
| S | : | A |   |   |   | A |   |   |   | A | =...= |
| A | : |   | A |   | A |   | A |   | A |   | =...= |
| B | : |   |   | A |   |   |   | A |   |   | =...= |


** Double hélice

La double hélice fait touner deux thèmes /A/ et /B/ :

#+ATTR_HTML: :class plat
| S | : | A |   |   | B |   |   | A |   |   | B |   |   | A |
| A | : |   | A | B |   | B | A |   | A | B |   | B | A |   |
| T | : |   | B | A |   | A | B |   | B | A |   | A | B |   |
| B | : | B |   |   | A |   |   | B |   |   | A |   |   | B |

Lorsque le nombre de voix est impair, il se produit une collision, car
les deux thèmes veulent se placer au même endroit au même moment.
Comme ce n’est évidemment pas possible, on peut contourner le problème
en jouant alternativement /A/ et /B/ à chaque croisement :

#+ATTR_HTML: :class plat
| S | : | A |   |   |   | B |   |   |   | A |   |   |   | B |   |   |   | A |
| M | : |   | A |   | B |   | B |   | A |   | A |   | B |   | B |   | A |   |
| A | : |   |   | A |   |   |   | B |   |   |   | A |   |   |   | B |   |   |
| T | : |   | B |   | A |   | A |   | B |   | B |   | A |   | A |   | B |   |
| B | : | B |   |   |   | A |   |   |   | B |   |   |   | A |   |   |   | B |

On retrouve ce genre d’alternance dans les noeuds et le tissage.


* Phrasé

#+TOC: headlines 1 local


** Ouverture et conclusion

Schématiquement, une phrase musicale est constituée d’un ou de
plusieurs mouvements d’ *ouverture*, suivis d’un mouvement de
*conclusion* :

#+begin_center
ouverture — =...= — ouverture — conclusion
#+end_center


** Anacrouses


*** Généralisation

Le terme « anacrouse » réfère en principe à la première mesure d’un
morceau, lorsque celle-ci est incomplète. Nous généralisons cette
notion à toute suite de notes occupant la fin d’une structure
rythmique et rattachées mélodiquement à la structure rythmique
suivante. Tous les niveaux rythmiques sont possibles :

  - oscillation
  - pulsation
  - mesure
  - carrure
  - ...


*** Carrure

Une mélodie est le plus souvent composée de petits fragments, chacun
d’entre-eux reposant sur une carrure. Ces thèmes sont structurés
généralement comme suit :

  - mélodie principale

  - note plus longue ou silence se prolongeant assez longtemps pour
    mordre dans la dernière oscillation de la carrure.

  - anacrouse : petite mélodie intercalée entre cette longue note et
    la fin de la carrure. Elle constitue une introduction à la mélodie
    de la carrure suivante.

L’intérêt de l’anacrouse est de décaler la logique mélodique, qui
commence au début de l’anacrouse, de la logique rythmique commençant
au début de la mesure suivante. On crée ainsi un ressort musical.
L’introduction non accentuée suivie par la note accentuée sur la
pulsation suivante donne également un effet d’augmentation progressive
de l’amplitude.


**** Exemple

Comme exemple, voici le rythme du thème situé au début du Beau Danube
bleu, où chaque pulsation correspond à une blanche pointée. Les
doubles barres verticales marquent le début et la fin de chaque
carrure, tandis que les accolades suivent la logique mélodique :

#+ATTR_HTML: :class plat
| { N ¦¦ Ν N N   B N   B N   B } { N ¦¦ N N N   B N   B N   B } |
| { N ¦¦ Ν N N   B N   B N   B } { N ¦¦ N N N   B N   B N   B } |
| =...=                                                         |

L’anacrouse correspond à la partie située entre le début du thème
mélodique et le début de la carrure :

#+begin_center
{ N ¦¦
#+end_center


* Chant

#+TOC: headlines 1 local


** Introduction

Nous considérons dans cette partie que la musique intègre une ou
plusieurs voix correspondant à un ou plusieurs textes chantés,
éventuellement versifiés.


** Syllabes et notes

Il existe trois types de relations possibles entre les syllabes et les notes :

  - *syllabique* : une syllabe par note, le plus fréquent

  - *mélismatique* : plusieurs notes par syllabe

  - *psalmodique* : plusieurs syllabes par note


*** Mélisme

Un *mélisme* est une syllabe chantée sur plusieurs notes.

Plus précisément, la partie vocalique de la syllabe est prolongée
durant les notes du mélisme.


*** Psalmodie

Une *psalmodie* est une suite de plusieurs syllabes chantées sur une unique note.


** Accentuation

Les accents du chant sont généralement disposés au début des
pulsations et oscillations.


** Chant virtuel

Lorsqu’on ne dispose pas de chant, on peut malgré tout utiliser les
techniques littéraires et poétiques présentées ci-dessous afin de
dynamiser la musique, la seule différence étant que les syllabes
chantées sont alors remplacées par de simples notes. On parle alors de
*chant virtuel*, ou de *vers virtuels* si le texte est versifié.


* Poésie

#+TOC: headlines 1 local


** Vers


*** Accentuation

Dans un poème, les accents sont généralement disposés aux syllabes qui
précédent les pauses naturelles, et se prolongent éventuellement sur
celles-ci. On a donc, par ordre décroissant d’importance, des
accents :

  - aux rimes, ou plus généralement à la dernière syllabe sonore de chaque vers
  - aux syllabes précédant les césures
  - aux syllabes précédant les coupes

On peut également inverser ce dispositif en disposant
occasionnellement un accent sur la première syllabe d’un vers, d’une
coupe ou d’une césure.

/Remarque/ : bien que ceux-ci puissent se confondre en pratique, il
est important de faire la distinction conceptuelle entre les accents
mélodiques (discontinuités, extrêmes, ...), les accents rythmiques
(pulsations) et les accents du chant (rimes, coupes, ...).


*** Rimes

Les notes correspondant aux *rimes* sont parmis les plus longues du
vers. Ces notes sont souvent de durée plus élevée que les autres notes
de la carrures, formant des paliers musicaux.


**** Virtuelles

En l’absence de chant, des rimes virtuelles peuvent être représentées
par de longues notes identiques ou complémentaires. Ces notes sont
placées à la fin de deux ou plusieurs carrures afin d’en accentuer les
finales. On parle alors de *rimes virtuelles*.

Les structures de rimes virtuelles les plus courantes sont analogues à
celles des [[file:litera-01-rimailleur.org::#section:strophes][strophes poétiques]].


*** Phrasé

Chaque vers peut être *ouvert* ou *conclusif*, la strophe disposant
ainsi d’une double structure de rimes et d’ouvertures. Exemple :

#+begin_center
a — a — a — b — c — c — c — b
#+end_center

avec :

#+begin_center
ouverture — ouverture — ouverture — conclusion — ouverture — ouverture — ouverture — conclusion
#+end_center


*** Anacrouse

Lorsqu’une anacrouse est désirée, on la place à la fin du vers, entre
la rime et le début de la mesure suivante.


** Strophes


*** Virtuelles

Les strophes composées de vers virtuels sont appelées *strophes
virtuelles*.


*** Zone tampon

La taille de la carrure est généralement prévue large, afin de
disposer d’une zone tampon où la dernière rime de chaque carrure peut
être allongée. Cette zone tampon permet également de gérer des vers
plus longs.


*** Fins de strophes

Afin de rendre solennelle la fin d’une strophe, il suffit de supprimer
l’anacrouse suivant la dernière rime. Par exemple, un quatrain pourra
se construire comme suit :

#+ATTR_HTML: :class plat
| vers | rime | anacrouse |
| vers | rime | anacrouse |
| vers | rime | anacrouse |
| vers | rime |           |


** Niveaux rythmiques

  - les accents du poème (coupes, césures, rimes) sont généralement
    disposés au début des pulsations musicales

  - la durée d’une pulsation correspond donc à un pied (syllabique)

  - L’oscillation peut correspondre

    + À un vers entier s’il s’agit d’un vers court

    + À une partie de vers intermédiaire

    + À une césure s’il s’agit d’un vers long

  - la carrure peut correspondre

    + À une strophe

    + À une partie de strophe

La structure des coupes et césures d’un poème chanté est souvent moins
régulière que celle d’un poème récité. En effet, le rythme musical se
charge d’imposer la régularité, ce qui laisse la place à plus de
flexibilité dans la structure interne des vers.

Les niveaux rythmiques d’une poésie chantée sont donc organisées en
s’inspirant du modèle :

| Musique     | Chant   |
|-------------+---------|
|             | strophe |
| carrure     |         |
|             | vers    |
| oscillation | césure  |
| pulsation   | coupe   |
| mesure      |         |

Gardons à l’esprit qu’il s’agit d’une hiérarchie souple, à adapter au cas par cas.


*** Exemples


**** Quatrain

Imaginons pour l’exemple le cas d’un quatrain d’alexandrins de
structure :

#+begin_center
3 / 3 // 3 / 3
#+end_center

On a alors les correspondances :

| pied (syllabique) | 1 pulsation                   | 1 mesure de 3 temps         |
| hémistiche        | 1 oscillation de 2 pulsations | 2 mesures de 3 temps        |
| vers              | 2 oscillations                | 4 mesures                   |
| demi-strophe      | 4 oscillations                | 1 demi-carrure de 8 mesures |
| strophe           | 8 oscillations                | 1 carrure de 16 mesures     |

Dans le cas de rimes croisées, chaque demi-strophe (occupant une
demi-carrure) contient donc les deux rimes, et la deuxième
demi-strophe répond à la première :

#+begin_center
a b  —  a b
#+end_center


**** Sixain

Nous prenons comme exemple la structure :

#+begin_center
a a b c c b
#+end_center

Disposition sur 8 oscillations :

| 1er vers | 1 oscillation  | a |
| 2e vers  | 1 oscillation  | a |
| 3e vers  | 2 oscillations | b |
| 4e vers  | 1 oscillation  | c |
| 5e vers  | 1 oscillation  | c |
| 6e vers  | 2 oscillations | b |

Disposition sur 16 oscillations :

| 1er vers | 2 oscillations | a |
| 2e vers  | 2 oscillations | a |
| 3e vers  | 4 oscillations | b |
| 4e vers  | 2 oscillations | c |
| 5e vers  | 2 oscillations | c |
| 6e vers  | 4 oscillations | b |

Les deux dispositions sont similaires, il s’agit d’un simple
changement de niveau rythmique. Dans les deux cas, les vers 3 et 6
(derniers vers de chaque demi-strophe, rimes b) sont mis en
évidences : ils occupent une place double par rapport à celle des
autres vers.


** Polystrophes

Lorsque deux ou plusieurs strophes (réelles ou virtuelles) sont
chantées simultanément sur les voix d’une polyphonie, on parle de
*polystrophe*.


*** Polyrimes

La structure de rimes d’une polystrophe est baptisée *polyrime*.

Lorsque les strophes commencent au même instant et que les mètres des
carrures sont identiques, leurs rimes sont jouées simultanément sur
les différentes voix, on dit qu’elles sont *synchrones*.

Dans le cas où les rimes sont décalées, on dit qu’elles sont
*asynchrones*.


**** Structures

Qu’elles soient synchrones ou non, les structures de rimes des
différentes strophes peuvent être identiques ou différentes.

Un exemple de structure identique :

#+ATTR_HTML: :class plat
| S | : | a | — | b | — | a | — | b |
| B | : | c | — | d | — | c | — | d |

Un exemple utilisant des structures différentes :

#+ATTR_HTML: :class plat
| S | : | a | — | b | — | a | — | b |
| B | : | c | — | d | — | d | — | c |


*** Fins de strophe

Dans le cas de polystrophes, on s’arrangera pour que les dernières
rimes soient synchronisées.
