
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 05 : Tablature
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Tonalité

#+TOC: headlines 1 local

** Introduction

L’association d’une tonique et d’un mode est appelée *tonalité*.

On parlera par exemple de la tonalité de :

  - do ionien
  - la éolien
  - etc


** Intérieur & extérieur

La tonalité détermine les notes et les altérations de la gamme
utilisée.

On dit qu’une note, diatonique ou altérée, est *dans la tonalité* si
elle fait partie de la gamme detérminée par la tonalité.

On dit qu’une note, diatonique ou altérée, est *en dehors de la
tonalité* si elle ne fait pas partie de la gamme detérminée par la
tonalité.


** Notes tonales

Quelle est la différence entre une gamme et une tonalité ? Toutes deux
sont définies par une tonique et un mode, mais la tonalité possède en
plus une hiérarchie entre les degrés qui la constituent.

Les *notes tonales* sont les notes les plus importantes de la gamme, à
savoir la tonique et les degrés qui l’entourent dans le cycle des
quintes :

#+ATTR_HTML: :class plat
| noms   | : | sous-dominante | <— | 5te | —> | tonique | <— | 5te | —> | dominante |
| degrés | : |              4 | <— | 5te | —> |       1 | <— | 5te | —> |         5 |


Un *degré fort*, ou *degré tonal*, est un degré qui correspond à une
note tonale. Les degrés 4, 1, 5 sont donc les degrés forts de la
tonalité.

Les autres degrés sont appelés *degrés faibles*.

On a donc la hiérarchie :

#+ATTR_HTML: :class plat
| degrés forts   | : |   | 4 |   | 1 |   | 5 |   |
| degrés faibles | : | 2 |   | 6 |   | 3 |   | 7 |


** Intervalles justes

Les notes tonales sont généralement séparées de la tonique par les
intervalles justes de la gamme :

| Note 1  | Note 2         | Intervalle      |
|         |                | à l’octave près |
|---------+----------------+-----------------|
| tonique | tonique        | unisson         |
| tonique | dominante      | quinte          |
| tonique | sous-dominante | quarte          |

Il existe toutefois quelques exceptions. Ainsi, la dominante de la
gamme de /si locrien/ forme un intervalle de quinte diminuée avec la
tonique, raison pour laquelle le mode locrien est peu utilisé.


** Accords

Considérons les accords de trois notes construits en prenant les notes
tonales comme fondamentales :

| Note tonale    | Degrés        | Exemple      |
|                | dans l’accord | tonique = do |
|----------------+---------------+--------------|
| tonique        | 1 3 5         | do mi sol    |
| dominante      | 5 7 2         | sol si ré    |
| sous-dominante | 4 6 1         | fa la do     |

On constate que l’on retrouve toutes les notes de la gamme.


* Fonctions tonales

#+TOC: headlines 1 local

** Introduction

Une *fonction tonale* est une fonction musicale réalisée à la fois par :

  - une note tonale
  - un accord mettant en évidence cette note tonale

La musique utilisant les fonctions tonales est appelée *musique tonale*.


** Tonique

En tant que note la plus importante de la gamme, la tonique assure
aussi la première fonction tonale.

La tonique est la fonction sur laquelle la musique effectue ses pauses
les plus importantes.


** Dominante

La musique tonale s’articule autour de la dualité qui existe entre la
tonique, fonction de repos, et la dominante, fonction dynamique autour
de laquelle la musique peut se développer. Il arrive également que la
musique effectue des pauses à la dominante, mais ce sont là des arrêts
nettement moins appuyés que ceux effectués sur la tonique.

La dominante est naturellement attirée par la tonique, et peut :

  - répondre à son appel, ce qui détent la musique
  - ne pas y répondre et repartir vers une autre idée

La dominante constitue donc la fonction tonale la plus importante avec
la tonique.


** Sous-dominante

La sous-dominante constitue la fonction tonale la plus importante
après la tonique et la dominante.


** Tableau récapitulatif

| Degrés | Fonctions            | Abréviations |
|--------+----------------------+--------------|
|      4 | sous-dominante       | SD           |
|      1 | tonique              | T            |
|      5 | dominante            | D            |


* Modes majeur et mineur

#+TOC: headlines 1 local

** Introduction

Le tableau suivant regroupe les accords de trois notes générés par les
degrés des modes naturels. La lettre *M* signifie accord parfait
majeur et la lettre *m* accord parfait mineur. Le symbole *dim*
signifie ici accord de quinte diminuée :

| Modes      |     | Degrés |     |     |     |     |     |     |
|            |     | 4      | 1   | 5   | 2   | 6   | 3   | 7   |
|------------+-----+--------+-----+-----+-----+-----+-----+-----|
| lydien     | fa  | dim    | M   | M   | M   | m   | m   | m   |
| ionien     | do  | M      | M   | M   | m   | m   | m   | dim |
| mixolydien | sol | M      | M   | m   | m   | m   | dim | M   |
| dorien     | ré  | M      | m   | m   | m   | dim | M   | M   |
| éolien     | la  | m      | m   | m   | dim | M   | M   | M   |
| phrygien   | mi  | m      | m   | dim | M   | M   | M   | m   |
| locrien    | si  | m      | dim | M   | M   | M   | m   | m   |

Parmi les modes naturels, les modes ionien et éolien sont les seuls à
présenter le même type d’accords sur les degrés forts 4, 1, 5. Le mode
ionien produit des accords parfaits majeurs, tandis que le mode éolien
produit des accords parfaits mineurs :

| Modes  | Degrés |   |   |
|        | 4      | 1 | 5 |
|--------+--------+---+---|
| ionien | M      | M | M |
| éolien | m      | m | m |

Pour cette raison :

  - le mode ionien est aussi appelé *mode majeur*
  - le mode éolien est aussi appelé *mode mineur*

Exemple de mode majeur avec la gamme de /do majeur/ :

#+begin_center
do ré mi fa sol la si do
#+end_center

Exemple de mode mineur avec la gamme de /la mineur/ :

#+begin_center
la si do ré mi fa sol la
#+end_center


** Tonalités modèles

La tonalité modèle du mode :

  - majeur correspond à la gamme modèle du mode ionien
  - mineur correspond à la gamme modèle du mode éolien

| Mode   | Nom médiéval | Tonalité modèle          |
|--------+--------------+--------------------------|
| majeur | ionien       | do ré mi fa sol la si do |
| mineur | éolien       | la si do ré mi fa sol la |


** Adaptations du mineur

#+TOC: headlines 1 local

*** Mineur harmonique

Le mode majeur dispose d’une sensible inférieure. Par exemple, en /do
majeur/, la sensible inférieure est le /si/, à un demi-ton de la
tonique /do/.

En mode mineur par contre, les degrés 2 et 7 sont situés à un ton
entier de la tonique : ce mode ne possède donc pas de sensible. On
peut toutefois y remédier en haussant la sous-tonique d’un demi-ton,
obtenant ainsi un mode dérivé, appelé *mode mineur harmonique*. Par
exemple, en /la mineur/, le /sol/ sera haussé d’un demi-ton, donnant
ainsi la gamme :

#+begin_center
la si do ré mi fa sol^{#} la
#+end_center

Dans la suite, le mode mineur par défaut sera généralement le mode
mineur harmonique.


*** Mineur ascendant et descendant

Le mode mineur harmonique sonne très bien, disposant à la fois de la
sonorité du mode mineur et de l’attirance de la sensible inférieure.
Cependant, l’écart de seconde augmentée entre les degrés 6 et 7 n’est
pas toujours souhaitable. Dans ce cas, on hausse le degré 6, obtenant
un mode appelé *mode mineur ascendant*. Exemple, le /la mineur
ascendant/ :

#+begin_center
la si do ré mi fa^{#} sol^{#} la
#+end_center

Par opposition, on appelle alors *mode mineur descendant* le mode
mineur naturel (le mode éolien). En pratique, les modes mineurs
(harmonique, ascendant et descendant) sont souvent mêlés, donnant
ainsi beaucoup de couleur et de souplesse à la musique. Enfin, le
degré 3 peut lui aussi être haussé d’un demi-ton, complétant ainsi le
caractère polymorphe du mode mineur, qui peut se rapprocher ou même se
confondre avec le mode majeur.


*** Conclusion

Le mode mineur est très versatile, et ses altérations flottantes
donnent une couleur particulière à la musique.


** Degrés & intervalles caractéristiques

Les modes majeur et mineur sont les modes les plus utilisés. On s’en
sert donc comme référence pour souligner les *degrés caractéristiques*
des autres modes. Ces degrés forment des *intervalles
caractéristiques* avec la tonique.


*** Autour du mode majeur

En partant de /do majeur/, les quintes voisines nous donnent les
gammes de /sol mixolydien/ et /fa lydien/.

Si nous transposons la gamme de /sol mixolydien/ vers la tonique /do/,
nous obtenons la gamme de /do mixolydien/ :

#+begin_center
do ré mi fa sol la /si^b/ do
#+end_center

La note caractéristique du mode mixolydien est donc le /si^b/,
septième degré formant un intervalle de septième mineure avec la
tonique.

Si nous transposons la gamme de /fa lydien/ vers la tonique /do/,
nous obtenons la gamme de /do lydien/ :

#+begin_center
do ré mi /fa^{#}/ sol la si do
#+end_center

La note caractéristique du mode lydien est donc le /fa^{#}/, quatrième
degré formant un intervalle de quarte augmentée avec la tonique.


*** Autour du mode mineur

En partant de /la mineur/, les quintes voisines nous donnent les
gammes de /mi phrygien/ et /ré dorien/.

Si nous transposons la gamme de /mi phrygien/ vers la tonique /la/,
nous obtenons la gamme de /la phrygien/ :

#+begin_center
la /si^b/ do ré mi fa sol la
#+end_center

La note caractéristique du mode phrygien est donc le /si^b/, deuxième
degré formant un intervalle de seconde mineure avec la tonique.

Si nous transposons la gamme de /ré dorien/ vers la tonique /la/, nous
obtenons la gamme de /la dorien/ :

#+begin_center
la si do ré mi /fa^{#}/ sol la
#+end_center

La note caractéristique du mode dorien est donc le /fa^{#}/, sixième
degré formant un intervalle de sixte majeure avec la tonique.

Nous n’avons pas encore exploré le mode locrien. Partons de la gamme
de /si locrien/ et transposons vers la tonique /la/, deux quintes plus
bas. Nous obtenons la gamme de /la locrien/ :

#+begin_center
la si^b do ré mi^b fa sol la
#+end_center

Les notes caractéristiques du mode locrien sont donc le /si^b/ et le
/la^b/, deuxième et cinquième degré formant des intervalles de seconde
mineure et quinte diminuée avec la tonique.


*** Récapitulation

| Modes           |           Degré | Intervalle      |
|                 | caractéristique | caractéristique |
|-----------------+-----------------+-----------------|
| lydien          |               4 | 4te augmentée   |
| ionien (Majeur) |                 | —               |
| mixolydien      |               7 | 7e mineure      |
|-----------------+-----------------+-----------------|
| dorien          |               6 | 6te majeure     |
| éolien (Mineur) |                 | —               |
| phrygien        |               2 | 2de mineure     |
|-----------------+-----------------+-----------------|
| locrien         |               2 | 2de mineure     |
|                 |               5 | 5te diminuée    |


* Autres modes

#+TOC: headlines 1 local

** Introduction

Nous avons déjà vu les modes naturels, le majeur et le mineur. Ce
chapitre recense les autres modes disponibles.


** Construire de nouveaux modes

La technique la plus simple consiste à construire les gammes relatives
d’un mode existant. Chaque nouvelle gamme ainsi obtenue peut alors
être considérée comme la gamme modèle d’un nouveau mode.

Chaque mode heptaphonique nous donnera ainsi six nouveaux modes,
construits à partir des degrés 2 à 7.

Chaque mode pentaphonique nous donnera ainsi quatre nouveaux modes,
construits à partir des degrés 2 à 5.

Chaque mode tetraphonique nous donnera ainsi trois nouveaux modes,
construits à partir des degrés 2 à 4.


** Heptaphoniques


*** Acoustique

Le mode acoustique est construit à partir des premiers éléments de la
série des harmoniques naturelles. Exemple en partant de /do/ :

#+ATTR_HTML: :class plat
| /Notes/ | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |


En ramenant toutes les notes dans la même octave, on obtient :

#+begin_center
do ré mi fa^{#} sol si^b do
#+end_center

Ce mode contient donc une quinte, une tierce majeure, une septième
mineure, une seconde majeure et une quarte augmentée.

On peut bien entendu ajouter la note naturelle manquante, à savoir
le /la/ :

#+begin_center
do ré mi fa^{#} sol la si^b do
#+end_center

La gamme ainsi obtenue possède les mêmes écarts qu’un relatif du mode
mineur ascendant à partir du quatrième degré :

#+begin_center
ré mi fa^{#} sol^{#} la si do ré
#+end_center


*** Superlocrien

Le mode superlocrien est construit comme un relatif du mode mineur
ascendant à partir du septième degré :

#+begin_center
sol^{#} la si do ré mi fa^{#} sol^{#}
#+end_center

Ce mode est appelé superlocrien, car il ressemble fort au mode
locrien. On le voit clairement en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la si
#+end_center


**** Mineur harmonique

Il existe aussi une variante dérivée du mode mineur harmonique :

#+begin_center
sol^{#} la si do ré mi fa sol^{#}
#+end_center

ce qui donne, en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la^b si
#+end_center


*** Tzigane

Le mode tzigane, ou mode hongrois, est un mode dérivé du mineur
harmonique, le 4e degré étant haussé afin de se rapprocher de la
dominante :

#+begin_center
la si do ré^{#} mi fa sol^{#} la
#+end_center

Ce mode est caractérisé par la présence de deux sensibles auxiliaires :

#+begin_center
sensible auxiliaire inférieure —> dominante <— sensible auxiliaire supérieure
#+end_center

Notons les deux écarts de trois demi-tons entre les degrés 3 - 4 et
6 - 7.


*** Andalou

Le mode andalou ressemble au mode phrygien, mais il est caractérisé
par une médiante flottante, formant une tierce majeure ou mineure avec
la tonique :

#+begin_center
mi fa sol^{(#)} la si do ré mi
#+end_center


*** Napolitain

Il s’agit d’un mode ressemblant au mode phrygien, mais où le septième
degré est haussé d’un demi-ton, ce qui le transforme en sensible
inférieure :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

On voit que la sus-tonique est une sensible supérieure. Ce mode est
donc caractérisé par la double attraction :

#+begin_center
sensible inférieure —> tonique <— sensible supérieure
#+end_center

Il en existe une variante où le sixième degré est haussé :

#+begin_center
mi fa sol la si do^{#} ré^{#} mi
#+end_center


*** Oriental


**** Variante phrygienne

Le mode oriental phrygien est un relatif du mode tzigane construit à
partir du cinquième degré :

#+begin_center
mi fa sol^{#} la si do ré^{#} mi
#+end_center

Ce mode est caractérisé par les deux secondes augmentées qui séparent
les degrés 2 — 3 et 6 — 7, ainsi que par la double attraction :

#+begin_center
sensible inférieure —> tonique <— sensible supérieure
#+end_center

Si on souhaite également créer une double attraction vers la
dominante :

#+begin_center
sous-dominante altérée —> dominante <— sous-médiante
#+end_center

il suffit de hausser le degré 4 :

#+begin_center
mi fa sol^{#} la^{#} si do ré^{#} mi
#+end_center


**** Variante locrienne

Le mode oriental locrien est un relatif du mode tzigane construit à
partir du deuxième degré :

#+begin_center
si do ré^{#} mi fa sol^{#} la si
#+end_center

Afin d’obtenir la même propriété de double attraction que la variante
basée sur le mode de /mi/, on peut sensibiliser le degré 7 en le
haussant d’un demi-ton :

#+begin_center
si do ré^{#} mi fa sol^{#} la^{#} si
#+end_center


** Pentaphoniques

Les modes pentaphoniques sont des gammes de cinq notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
cinq quintes :

#+begin_center
do sol ré la mi
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode pentaphonique :

#+begin_center
do ré mi sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do  | ré | mi  | sol |
| sur ré  | : | ré  | mi  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré  | mi | sol | la  |
| sur mi  | : | mi  | sol | la  | do | ré  | mi  |


*** Avec caractéristique

Ce sont des modes pentaphoniques que l’on altère afin d’intégrer une
ou plusieurs notes caractéristiques des modes naturels. Par exemple,
ce mode pentaphonique altéré :

#+begin_center
ré mi sol^{#} la do ré
#+end_center

possède une quarte haussée, caractéristique du mode lydien.


*** Blues

Le mode blues est un mode pentaphonique développant les quintes à
partir de la médiante. La médiante, la dominante et la sous-tonique
sont flottantes. Par exemple, avec /la/ comme tonique, nous avons :

#+begin_center
la do^{(#)} ré mi^{(b)} sol^{(#)} la
#+end_center


*** Chinois

Le mode chinois est un mode pentaphonique développant les quintes à
partir de la tonique. Par exemple, avec /do/ comme tonique, nous
obtenons :

#+begin_center
do ré mi sol la do
#+end_center


*** Japonais

Le mode japonais est un mode pentaphonique développant les quintes à
partir de la sous-dominante. La gamme modèle de ce mode possède un
/mi/ pour tonique. On part alors de la sous-dominante /la/ et on
gravit les quintes entre notes naturelles :

#+begin_center
la mi si fa do
#+end_center

En disposant ces notes sur une octave /mi — mi^{+1}/ et en les
ordonnant de la plus grave à la plus aiguë, nous obtenons :

#+begin_center
mi fa la si do mi
#+end_center

La dominante auxiliaire /fa/ est une sensible supérieure. Ce mode
possède un autre demi-ton entre la dominante /si/ et la sous-médiante
/do/.

Notons également l’intervalle de quarte augmentée /si — fa/ qui sépare
la sus-tonique de la dominante.


** Tétraphoniques

Les modes tetraphoniques sont des gammes de quatre notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
quatre quintes :

#+begin_center
do sol ré la
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode tetraphonique :

#+begin_center
do ré sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do | ré  | sol |
| sur ré  | : | ré  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré | sol | la  |


* Sémantique

#+TOC: headlines 1 local

** Introduction

La fonction tonale d’un accord peut correspondre au degré :

  - de la fondamentale
  - de la basse
  - du soprano
  - d’une éventuelle note redoublée

Un même accord peut donc assurer différentes fonctions tonales,
suivant qu’une ou l’autre de ses notes est mise en évidence.

Inversément, de nombreux accords peuvent jouer le rôle d’une même
fonction tonale : il suffit de placer la note souhaitée en évidence.
Ce procédé permet de choisir au mieux accords et dispositions afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.


*** Suppression

Parfois, la fondamentale est supprimée mais correspond malgré tout à
la fonction tonale de l’accord. On parle alors de *fonction
implicite*.

/Remarque/ : ce raisonnement scabreux vise à considérer l’enchaînement
des degrés 7 - 1 comme une suite de fonctions dominante - tonique. Je
vous le livre ici car il figure dans la théorie harmonique
conventionnelle, mais je n’y souscris pas. Il me semble bien plus
naturel de considérer que l’enchaînement 7 - 1 prend sa source dans la
[[file:musica-04-clavier.org::#section:cadenceIonienneTroisVoix][cadence ionienne à trois voix]]. Les mouvements contraires qu’elle
contient amènent élégamment la tonique, ce qui justifie sa place parmi
les piliers de l’harmonie tonale.


*** Pédale

Si une pédale est présente, c’est elle qui assure la fonction tonale
pendant toute la durée de son règne. Suivant les cas, on parle de
pédale de tonique, de dominante, ou de sous-dominante.

Idem pour les accords pédale.


*** Accords ornementaux mélodiques

Les accords ornementaux mélodiques n’ont pas de fonction tonale
propre. On considère qu’ils remplissent la même fonction tonale que le
premier accord stratégique qui précède ou qui suit, suivant le
contexte.


** Synonymes

#+TOC: headlines 1 local

*** Introduction

Deux accords distincts remplissant une même fonction tonale sont dit
*synonymes*.


*** Recherche d’accords synonymes

Nous allons considérer un exemple simple afin de bien comprendre le
procédé permettant de découvrir des accords synonymes. Nous
choisissons la note /do/ comme tonique et nous voulons découvrir les
accords pouvant remplir la fonction de dominante. La dominante étant
le /sol/, cette note devra donc pouvoir être mise en évidence. Le
choix le plus évident est un accord du degré 5 avec le /sol/ comme
fondamentale, mais il en existe d’autres.

On peut parcourir le cycle des tierces pour découvrir les autres
accords à base de tierces incluant un /sol/. Pour les triades, cela
nous donne :

  - /sol/ si ré
  - mi /sol/ si
  - do mi /sol/

On voit que les fondamentales de ces accords, /sol/, /mi/ et /do/,
descendent le cycle des tierces.

Il ne nous reste plus qu’à mettre en évidence le /sol/ en le plaçant à
la basse, au soprano ou en le doublant. Nous choissons ici la dernière
option, ce qui nous donne :

  - /sol/ si ré /sol/
  - /sol/ mi /sol/ si
  - /sol/ do mi /sol/


*** Sans fondamentale

Nous pouvons aussi considérer qu’un accord de degré 7 :

#+begin_center
si ré fa =...=
#+end_center

est un accord de degré 5 privé de sa fondamentale :

#+begin_center
(sol) si ré fa =...=
#+end_center

et remplit implicitement une fonction de dominante.


*** Synonymes usuels

Étant donné une note tonale située sur le degré /X/, les synonymes
les plus utilisés sont :

  - les accords du degré /X/
  - les accords dont la fondamentale est située une tierce plus bas que le degré /X/
  - les accords dont la fondamentale est située une quinte plus bas que le degré /X/

En effet, tous ces accords contiennent la note du degré /X/, ce qui
permet de mettre la note tonale en évidence. On ajoute à cela les
accords situés à la tierce supérieure, considérés comme des degrés /X/
sans fondamentale.

Le tableau suivant nous donne les degrés des accords synonymes :

|     quinte |     tierce | degré |     tierce |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
|          4 |          6 |     1 |          3 |
|          7 |          2 |     4 |          6 |
|          1 |          3 |     5 |          7 |


Exemple en /do majeur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| fa         | la         | do    | mi         |
| si         | ré         | fa    | la         |
| do         | mi         | sol   | si         |

Exemple en /la mineur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| ré         | fa         | la    | do         |
| sol        | si         | ré    | fa         |
| la         | do         | mi    | sol        |


*** Les plus courants

Les possibilités les plus couramment employées sont rassemblées dans
ce tableau :

| Fonctions      | Degrés | Exemple      | Exemple      |
|                |        | en do majeur | en la mineur |
|----------------+--------+--------------+--------------|
| tonique        |      1 | do           | la           |
|                |      6 | la           | fa           |
|                |      3 | mi           | do           |
| sous-dominante |      4 | fa           | ré           |
|                |      2 | ré           | si           |
|                |      6 | la           | fa           |
| dominante      |      5 | sol          | mi           |
|                |      3 | mi           | do           |
|                |      7 | si           | sol          |


** Lien sémantique

Lorsqu’une modification de la disposition d’un accord /A/ permet de
rendre sa fonction tonale identique à celle d’un accord /B/, on dit
qu’il existe un *lien sémantique* entre les accords /A/ et /B/.

Par exemple, en /do majeur/, l’accord :

#+begin_center
do mi sol
#+end_center

exerce une fonction de tonique. Si nous plaçons le /sol/ à la basse et
que nous le doublons :

#+begin_center
sol do mi sol
#+end_center

il exerce alors une fonction de dominante. On met ainsi en évidence un
lien sémantique avec l’accord du degré 5 :

#+begin_center
sol si ré sol
#+end_center

qui exerce la même fonction.


*** Synonymes

Si les accords /A/ et /B/ sont unis par un lien sémantique, on peut
réarranger /A/, ou du moins réinterpréter sa fonction tonale, pour
qu’il soit synonyme de /B/.


* Couples

#+TOC: headlines 1 local

** Couple tonal

La musique tonale se base essentiellement sur la dualité
dominante — tonique. Le *couple tonal* est un enchaînement qui met en
évidence cette dualité en faisant entendre les deux fonctions.
L’accord faisant fonction de tonique, de par son caractère conclusif,
se place après l’accord faisant fonction de dominante :

#+ATTR_HTML: :class plat
| dominante | — | tonique |

Le couple tonal est également caractérisé par la descente de quinte
qui mène du premier accord au second.


** Couple plagal

Le *couple plagal* est un peu le miroir du couple tonal : au lieu de
descendre d’une quinte pour aboutir à la tonique, on monte d’une
quinte. On doit donc partir de la quinte inférieure, c’est-à-dire de
la sous-dominante :

#+ATTR_HTML: :class plat
| sous-dominante | — | tonique |


* Tonalité secondaire

#+TOC: headlines 1 local

** Introduction

On peut renforcer le rôle du degré /X/ de la tonalité principale en le
considérant comme une *tonique secondaire*. La tonalité construite sur
ce degré /X/ s’appelle alors *tonalité secondaire*.

Une fonction tonale d’une tonalité secondaire est appelée *fonction
secondaire* et notée :

#+begin_center
Fonction de /X/
#+end_center


*** Degrés

Un accord construit sur le degré /Y/ de la tonique secondaire
correspondant au degré /X/ est noté :

#+begin_center
/Y/ de /X/
#+end_center


** Fonctions secondaires

#+TOC: headlines 1 local


*** Dominante secondaire

La *dominante secondaire* basée sur le degré /X/ de la tonalité
principale s’obtient en considérant /X/ comme une tonique secondaire
et en exprimant sa dominante :

#+begin_center
Dominante de /X/
#+end_center

Prenons par exemple /do majeur/ comme tonalité principale et
sélectionnons le degré 2, le /ré/, comme tonique secondaire. Si nous
décidons de lui appliquer le mode majeur, nous obtenons la tonalité
secondaire de /ré majeur/, qui est située une seconde majeure plus
haut que la principale. Le [[file:musica-01-monocorde.org::#section:recapitulationTranspositionQuintes][tableau des transpositions]] nous donne alors
les altérations /fa^{#}/ et /do^{#}/. Une quinte plus haut que le
/ré/, nous avons le /la/ au degré 6, qui correspond à la dominante
secondaire :

#+ATTR_HTML: :class plat
| noms   | : | tonique principale | tonique secondaire | dominante secondaire |
| degrés | : |                  1 |                  2 |                    6 |

Nous choisissons un accord 5 de 2 pour la représenter :

#+begin_center
la do^{#} mi
#+end_center


*** Sous-dominante secondaire

La *sous-dominante secondaire* basée sur le degré /X/ de la gamme
courante s’obtient en considérant /X/ comme une tonique secondaire et
en exprimant sa sous-dominante :

#+begin_center
Sous-dominante de /X/
#+end_center


** Tonicisation

La tonicisation consiste à mettre en évidence le caractère de tonique
secondaire d’un degré /X/ en jouant le couple tonal secondaire :

#+ATTR_HTML: :class plat
| ( dominante | — | tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| dominante de /X/ | — | tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| dominante de /X/ | — | /X/ |

L’accord parfait sera :

  - majeur si on souhaite mettre en évidence une tonalité secondaire majeure
  - mineur si on souhaite mettre en évidence une tonalité secondaire mineure


*** Sous-dominante secondaire

Une alternative consiste à jouer le couple plagal secondaire :

#+ATTR_HTML: :class plat
| ( sous-dominante | — | tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| sous-dominante de /X/ | — | tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| sous-dominante de /X/ | — | /X/ |


** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: section:dominanteAuxiliaire
:END:

La *dominante auxiliaire* est la dominante secondaire obtenue en
choisissant la dominante principale comme tonique secondaire. En
d’autres termes, la dominante auxiliaire correspond à la dominante de
la dominante, située deux quintes plus haut que la tonique principale
dans le cycle des quinte :

#+ATTR_HTML: :class plat
| noms         | : | tonique principale | dominante principale | dominante auxiliaire |
| abréviations | : | T                  | D                    | Daux                 |
| degrés       | : | 1                  | 5                    | 2                    |

La dominante auxiliaire est la fonction secondaire la plus utilisée
car elle permet de réaliser le couple tonal secondaire :

#+begin_center
Daux — D
#+end_center

qui renforce la dominante principale. Enfin, un accord du degré 2 peut
être disposé pour assurer une fonction tonale de sous-dominante ou de
dominante auxiliaire, reliant ainsi les deux fonctions.


** Sensibles


*** Sensibles secondaires

Une note située à une distance d’un demi-ton d’une tonique secondaire
crée une attraction mélodique vers cette dernière.

Une *sensible secondaire supérieure* est un degré situé juste
au-dessus d’une tonique secondaire, à un demi-ton de celle-ci.

Une *sensible secondaire inférieure* est un degré situé juste
en-dessous d’une tonique secondaire, à un demi-ton de celle-ci.


*** Sensibles auxiliaires

Une note située à une distance d’un demi-ton de la dominante crée une
attraction mélodique vers cette dernière.

La dominante correspondant au degré 5, les notes qui l’entourent sont
situées aux degrés 4 et 6.

Lorsque le degré 4 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire inférieure*.

Lorsque le degré 6 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire supérieure*.


*** Tableau récapitulatif

| Degrés | Noms                           | Abréviations |
|--------+--------------------------------+--------------|
|      2 | sensible supérieure            | Ssup         |
|      7 | sensible inférieure            | Sinf         |
|      6 | sensible auxiliaire supérieure | SauxSup      |
|      4 | sensible auxiliaire inférieure | SauxInf      |


* Cycle tonal

#+TOC: headlines 1 local

** Introduction

Le *cycle tonal* est une suite d’accords dont les fondamentales
descendent le cycle des quintes, mais en annulant ou ajoutant des
altérations pour que les notes obtenues restent dans la tonalité. Il
part du degré 1 et parcourt tous les autres degrés jusqu’à revenir à
la tonique.

Considérons par exemple la tonalité de /la mineur/. Le cycle des
quintes descendantes s’écrit :

#+begin_center
la ré sol do fa si^b mi^b la^b
#+end_center

Les bémols /si^b/, /mi^b/ et /la^b/ ne font pas partie de la tonalité
et sont donc annulés pour revenir aux notes naturelles /si/, /mi/ et
/la/. On obtient ainsi le cycle :

#+begin_center
la ré sol do fa si mi la
#+end_center

ce qui correspond aux degrés :

#+ATTR_HTML: :class plat
| notes  | : | la | ré | sol | do | fa | si | mi | la |
| degrés | : |  1 |  4 |   7 |  3 |  6 |  2 |  5 | 1  |

Écrit en terme de degrés, le cycle tonal est applicable à n’importe
quelle tonalité. C’est donc cette forme que nous retiendrons :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 3 | 6 | 2 | 5 | 1 |

C’est ce cycle, répété en boucle, qui sert de fondation à la musique
tonale. Naturellement, de nombreuses variations de ce modèle se
succèdent afin d’en rompre la monotonie. Si les techniques permettant
de produire ces variations peuvent nous mener à des enchaînements
parfois très éloignés du cycle d’origine, elles respectent néanmoins
certains principes :

  - il existe un lien entre
    + les accords originaux et les modifications
    + le nouvel accord et son environnement
  - ce lien peut être
    + accord synonyme
    + lien sémantique
    + fonction secondaire
    + lien polyphonique
    + enharmonie
  - l’accord final de chaque cycle fait en général fonction de tonique
    ou de dominante

Le cycle tonal permet d’expliquer des enchaînements courants ou d’en
découvrir de nouveaux, mais n’oublions pas qu’il ne s’agit que d’un
d’outil optionnel, à utiliser lorsqu’on le juge pertinent.


*** Quinte diminuée

Reprenons notre exemple en /la mineur/. Si toutes les quintes étaient
justes, nous traverserions le cycle complet des douze notes
diatoniques et altérées :

#+begin_center
la ré sol do fa si^b mi^b la^b ré^b sol^b [do^b = si] mi la
#+end_center

Au moins une de ces quintes doit être altérée afin de rester dans la
gamme heptatonique de /la mineur/. Dans notr exemple, l’annulation des
bémols produit l’apparition de la quinte diminuée descendante
/fa — si/.


** Suppression des doublons

Afin de simplifier la structure musicale, les accords intervenant en
double peuvent naturellement être réduits à un seul exemplaire.
Exemple :

#+ATTR_HTML: :class plat
| =...= | 5 | *1* | *1* | 4 | =...= | —> | =...= | 5 | *1* | 4 | =...= |


** Substitution

Cette opération consiste à remplacer un accord du cycle par un autre.
On veille toutefois à ce que l’accord original et son remplaçant
présentent certaines caractéristiques communes. Voici les principaux
mécanismes de substitution :

  - substitution par un accord synonyme à l’accord remplacé
  - substitution par un accord qui possède un lien sémantique avec
    l’accord remplacé
  - substitution par une fonction secondaire transformant le degré
    suivant en tonique secondaire
  - substitution polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants
  - substitution enharmonique : le nouvel accord est enharmonique à
    l’accord remplacé


** Insertion

Cette opération consiste à insérer un nouvel accord entre deux accords
du cycle. On veille toutefois à ce que l’accord inséré présente
certaines caractéristiques communes avec au moins un des accords
environnants. Les techniques d’insertion sont similaires à celles
utilisées pour la substitution :

  - insertion d’un accord synonyme renforçant une fonction tonale
    environnante
  - insertion d’un accord possédant un lien sémantique avec un des
    accords environnants
  - insertion d’une fonction secondaire transformant le degré
    suivant en tonique secondaire
  - insertion polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants
  - insertion par enharmonie : le nouvel accord est enharmonique au
    précédent ou au suivent


** Déviation

Cette opération consiste à dévier de trajectoire en créant un
raccourci dans le cycle tonal. On veille toutefois à ce que l’accord
de départ ait un lien avec l’accord d’arrivée :

  - déviation vers un accord d’arrivée synonyme à celui de départ
  - déviation vers un accord d’arrivée qui possède un lien sémantique
    avec l’accord de départ
  - déviation polyphonique : l’accord de départ possède un lien polyphonique
    avec l’accord d’arrivée
  - déviation enharmonique : les accords de départ et d’arrivée sont
    enharmoniques


*** Raccourci

Le *raccourci* est une déviation partant de n’importe quel accord du
cycle vers une fonction de dominante, éventuellement suivie par une
fonction de tonique.


*** Déviation enharmonique

À titre d’exemple de déviation enharmonique, plaçons-nous en /la
mineur/. L’accord de dominante sans fondamentale :

#+begin_center
sol^{#} si ré fa
#+end_center

est enharmonique à :

#+begin_center
la^b si ré fa
#+end_center

lui-même renversement de :

#+begin_center
si ré fa la^b
#+end_center

Ce dernier accord étant du degré 2, on peut créer un court-circuit
entre les degrés 7 et 2. Le cycle devient :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 2 | 5 | 1 |


** Figures de style

On peut imaginer d’autres types de modifications à apporter au cycle
tonal, en s’inspirant des [[file:litera-02-styleau.org][figures de style]] littéraires par exemple.


** Interprétation & réalisation

#+TOC: headlines 1 local

*** Introduction

Il existe de nombreuses interprétations du cycle tonal en terme de
fonctions, et chacune de ces interprétations peut être réalisées par
différentes suites d’accords. Nous disposons donc d’un système très
prolifique.


*** Degré 7 comme dominante

Voici un exemple d’interprétation du cycle tonal :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | T | T | Daux | D | T |

Le degré 7 y est considéré comme une dominante sans fondamentale et
les degrés 3 et 6 comme des accords de tonique. L’astuce est que nous
allons à présent oublier les degrés du cycle pour se concentrer sur
les fonctions :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |

Nous pouvons décider de réaliser ces fonctions par la suite
d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |
| 1 |  4 | 5 | 1 | 6 |    2 | 5 | 1 |

pour autant que chacun d’entre-eux mette en évidence la note tonale
correspondante, cela va de soi. Mais il existe d’autres possibilités
pour représenter cette suite de fonctions. Par exemple :

#+ATTR_HTML: :class plat
| 1 | 4 | 5 | 6 | 3 | 2 | 5 | 1 |

ou :

#+ATTR_HTML: :class plat
| 1 | 2 | 5 | 6 | 1 | 4 | 5 | 1 |


*** Degré 3 comme dominante

Si nous considérons que le degré 3 représente une dominante, nous
pouvons interpréter le cycle tonal de la façon suivante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | D | T | Daux | D | T |

qui peut par exemple se représenter par la suite d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | D | T | Daux | D | T |
| 1 |  4 | 7 | 5 | 6 |    2 | 5 | 1 |


*** Degrés 6 et 2 comme sous-dominante

Si nous considérons que les degrés 6 et 2 représentent une
sous-dominante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 |  6 |  2 | 5 | 1 |
| T | SD | D | T | SD | SD | D | T |

nous obtenons par exemple :

#+ATTR_HTML: :class plat
| T | SD | D | T | SD | SD | D | T |
| 1 |  2 | 5 | 1 |  6 |  4 | 5 | 1 |


*** Suites fréquentes

Nous constatons que les suites de fonctions :

#+ATTR_HTML: :class plat
| T | SD   | D | T |

et :

#+ATTR_HTML: :class plat
| T | Daux | D | T |

sont très fréquentes.


**** Anatole

Parmi les suites d’accords courantes provenant des innombrables
variations du cycle tonal, citons l’ *anatole* :

#+ATTR_HTML: :class plat
| 6 | 2 | 5 | 1 |


* Cycle plagal

Le *cycle plagal* est une suite d’accords dont les fondamentales
montent le cycle des quintes :

#+ATTR_HTML: :class plat
| 1 | 5 | 2 | 6 | 3 | 7 | 4 | 1 |

Les modifications qu’on peut lui apporter sont analogues à celles du
cycle tonal.

Si le cycle plagel est rarement utilisé seul, il peut être utile d’en
insérer occasionnellement un fragment dans le cycle tonal.


* Polarisation secondaire

#+TOC: headlines 1 local

** Introduction

On parle de *polarisation secondaire* lorsqu’un ensemble d’accords
consécutifs remplissent des fonctions secondaires et mettent ainsi en
évidence l’existence d’une tonalité secondaire.

On choisit souvent une note tonale de la gamme principale comme
tonique de la tonalité secondaire. Placer la tonique secondaire sur la
tonique principale revient à identifier les deux gammes et n’apporte
aucun éclairage neuf. La dominante et la sous-dominante sont donc les
choix les plus courants de tonique secondaire.


** Dominante de la dominante

Nous avons déjà étudié en détail la dominante de la dominante, qui
n’est autre que la [[#section:dominanteAuxiliaire][dominante auxiliaire]].


** Dominante de la sous-dominante


*** Majeur

Nous allons à présent étudier la dominante de la sous-dominante.
Supposons par exemple que nous voulions renforcer le rôle de la
sous-dominante de /do majeur/, c’est-à-dire du /fa/. Notre accord doit
donc s’intégrer à la tonalité de /fa majeur/, qui possède un /si^b/
comme altération  :

#+begin_center
fa sol la si^b do ré mi fa
#+end_center

La dominante de cette gamme étant le /do/, la première idée est
d’utiliser la triade :

#+begin_center
do mi sol
#+end_center

mais cet accord ne met pas en évidence l’altération /si^b/ et ne se
différencie donc pas d’un accord parfait de tonique de /do majeur/. On
utilisera donc plutôt un accord d’au minimum quatre notes :

#+begin_center
do mi sol si^b
#+end_center


*** Mineur

En mineur, les modifications sont un peu plus compliquées. Plaçons
nous dans la gamme de /la mineur harmonique/, et construisons la
dominante de la sous-dominante. La sous-dominante étant le /ré/, on
doit intégrer cet accord dans la gamme de /ré mineur harmonique/.
Comme nous sommes une quinte plus bas que le /la/, un /si^b/ apparaît,
auquel on doit ajouter la sensible inférieure /do^{#}/ du mineur
harmonique :

#+begin_center
ré mi fa sol la si^b do^{#} ré
#+end_center

La dominante de cette gamme étant le /la/, on utilisera donc :

#+begin_center
la do^{#} mi
#+end_center

ou :

#+begin_center
la do^{#} mi sol
#+end_center

Si on souhaite mettre l’altération /si^b/ en évidence, on utilisera
plutôt l’accord de cinq notes :

#+begin_center
la do^{#} mi sol si^b
#+end_center


* Distance tonale

#+TOC: headlines 1 local

** Introduction

La *distance tonale* entre deux accords est le nombre d’étapes
nécessaires pour aller du premier accord au deuxième en suivant le
cycle tonal. Cette distance dépend de l’intervalle formé par les
fondamentales :

| Nombre d’étapes | Intervalle |
|-----------------+------------|
|               1 | 5te        |
|               2 | 2de M      |
|               3 | 3ce m      |
|               4 | 3ce M      |
|               5 | 2de m      |
|               6 | 4te aug    |

On retrouve ainsi un tableau similaire à ceux des
[[file:musica-01-monocorde.org::#section:recapitulationTranspositionQuintes][transpositions par combinaisons de quintes]].

Comme l’enchaînement reste équivalent si la fondamentale monte ou
descend d’une octave, les renversements de ces intervalles
correspondent à la même distance tonale et on a en définitive :

| Étapes | Intervalles |         |
|--------+-------------+---------|
|      1 | 5te         | 4te     |
|      2 | 2de M       | 7e m    |
|      3 | 3ce m       | 6te M   |
|      4 | 3ce M       | 6te m   |
|      5 | 2de m       | 7e M    |
|      6 | 4te aug     | 5te dim |


** Proximité tonale

Deux accords sont dit *tonalement proches* lorsque la distance tonale
qui les sépare est faible.

On retient généralement comme proches les accords séparés par une ou
deux étapes dans le cycle des quintes. Leurs fondamentales forment
alors :

  1. une quinte
  2. une seconde majeure

Deux accords sont dits *tonalement éloignés* s’ils ne sont pas proches.


** Enchaînements forts & faibles

Les enchaînements d’accords tonalement proches sont appelés
*enchaînements forts*.

Les enchaînements d’accords tonalement éloignés sont appelés
*enchaînements faibles*.

Un enchaînement est donc :

  - fort si les fondamentales procèdent par
    + quinte
    + seconde majeure
  - faible si les fondamentales procèdent par
    + tierce


* Boucles d’accords

#+TOC: headlines 1 local

** Introduction

Les boucles d’accords sont des cycles d’accords qui ne respectent pas
toujours la progression d’un cycle tonal ou plagal.

Ils sont beaucoup utilisés en musique pop.


** Boucle de quatre accords

Inspiré de la théorie de Philip Tagg.

  1. pôle principal
     - généralisation de la tonique
  2. sortant
     - prépare l’installation du pôle secondaire
  3. pôle secondaire
     - généralisation de la dominante
  4. rentrant
     - prépare l’installation du pôle principal
  5. retour au pôle principal


** Environnement

Inspiré de [[https://www.youtube.com/watch?v=JvyChMVvqnQ&t=401s][My Brand New Take On Four Chords Loop, by 12tone]].

Les enchaînements forts ou faibles entre un accord et ses voisins nous
donnent quatre configurations possibles :

| Catégorie    | Enchaînement avec |                |
| d’accord     | accord précédent  | accord suivant |
|--------------+-------------------+----------------|
| isolé        | faible            | faible         |
| continuation | fort              | fort           |
| départ       | faible            | fort           |
| destination  | fort              | faible         |

Un accord :

  - isolé sert de pause temporaire
  - de départ entame une série d’accord qui mène à une destination
  - de continuation prolonge une série entamée
  - de destination termine une série d’accord par une pause


* Stratification

#+TOC: headlines 1 local

** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique
tonalité, on parle de *musique tonale*. Il existe donc à tout moment
un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.


** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre tonalité, distincte
de celles des autres groupes, on parle de musique polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.


** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.


** Polyrythmie

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de *polymétrie* ou de *rythmes polymétriques*.


**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| V | : | § | χ | ¶ | χ | ¶ | χ |
| W | : | § | χ | χ | ¶ | χ | χ |
