
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 03 : Clavier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Tonalité

#+TOC: headlines 1 local


** Introduction

L’association d’une tonique et d’un mode est appelée *tonalité*.

En effet, une fois la tonique et le mode connu, on dispose d’assez
d’informations pour construire toute la gamme.

On parlera par exemple de la tonalité de :

  - fa lydien
  - do ionien
  - sol mixolydien
  - ré dorien
  - la éolien
  - mi phrygien
  - si locrien
  - etc


** Hiérarchie

La hiérarchie des notes au sein d’une gamme s’établit à partir du
cycle des quintes : le degré 1 et ses voisins dans le cycle des
quintes, les degrés 4 et 5, correspondent aux notes les plus
importantes. Les autres notes passent au second plan, et sont souvent
utilisées comme alternatives aux premières.

Les degrés 4, 1, 5 sont donc appelés *degrés forts*.

Les autres degrés, 2, 6, 3, 7 sont appelés *degrés faibles*.

La musique utilisant la hiérarchie des fonctions tonales est appelée
*musique tonale*.


** Fonctions tonales

Les *fonctions tonales* sont :

  - la tonique
  - la sous-dominante
  - la dominante


**** Notation

Afin de bien distinguer les concepts de degré et de fonction, les
degrés sont symbolisés par des chiffres (1, 2, ..., 7), tandis que les
fonctions sont décrites par leurs noms ou leurs abréviations.


*** Tonique

La *tonique*, degré 1 et fondation de la gamme, est la note la plus
importante, celle qui donne le ton. Elle constitue donc la première
fonction tonale.

La tonique est la fonction sur laquelle la musique effectue ses pauses
les plus importantes.

On l’appelle aussi *finale*, car c’est généralement elle qui marque la
fin d’une structure musicale.


*** Dominante

La *dominante* est le degré 5 de la gamme. Elle est donc située une
quinte au-dessus de la tonique. Ce rapport de quinte n’est évidemment
pas choisi au hasard, puisqu’il s’agit d’un des intervalles les plus
fondamentaux en musique.

Par exemple, si la tonique est un /do/, la dominante sera un /sol/.

La musique tonale s’appuie sur la dualité qui existe entre la tonique,
fonction de repos, et la dominante, fonction dynamique autour de
laquelle la musique peut se développer. Il arrive également que la
musique effectue des pauses à la dominante, mais ce sont là des arrêts
nettement moins appuyés que ceux de la tonique.

La dominante est naturellement attirée par la tonique, et peut :

  - répondre à son appel, ce qui détent la musique
  - ne pas y répondre et repartir vers une autre idée

La dominante constitue donc la fonction tonale la plus importante avec
la tonique.


*** Sous-dominante

La *sous-dominante* est située une quinte sous la tonique, et
correspond donc au degré 4. En fait, dominante et sous-dominante
entourent la tonique dans le cycle des quintes :


#+ATTR_HTML: :class plat
| Fonctions | : | Sous-dominante | ⟻ | 5te | ⟼ | Tonique | ⟻ | 5te | ⟼ | Dominante |
| Degrés    | : |              4 | ⟻ | 5te | ⟼ |       1 | ⟻ | 5te | ⟼ | 5         |

À ce titre, la sous-dominante constitue la fonction tonale la plus
importante après la tonique et la dominante.

Par exemple, si la tonique est un /do/, la sous-dominante sera un
/fa/.


*** Sus-tonique, dominante auxiliaire

Le degré 2 est appelé *sus-tonique*, parce qu’il est situé juste
au-dessus de la tonique dans la gamme.

Par exemple, si la tonique est un /do/, la sus-tonique sera un /ré/.

Ce degré est situé deux quintes plus haut que la tonique dans le cycle
des quintes. En d’autres termes, il correspond à la dominante de la
dominante. La sus-tonique permet donc de renforcer le rôle de la
dominante en la considérant comme une *tonique secondaire* dont on
exprime la dominante.

On utilise le terme de *dominante auxiliaire* comme synonyme de
sus-tonique.

Considérons l’exemple où la tonique est un /do/ et la dominante un
/sol/, et posons nous la question : que se passerait-il si le /sol/
était la tonique ? La dominante serait alors située une quinte
au-dessus, ce qui correspond au /ré/, degré 2 de notre gamme de
départ :

#+ATTR_HTML: :class plat
| Fonctions | : | Tonique | ⟻ | 5te | ⟼ | Dominante | ⟻ | 5te | ⟼ | Dominante auxiliaire |
| Degrés    | : |       1 | ⟻ | 5te | ⟼ |         5 | ⟻ | 5te | ⟼ |                    2 |


*** Sus-dominante, sous-médiante

Continuons à grimper dans le cycle des quintes, et reprenons notre
exemple où /do/ est la tonique : une quinte plus haut que la
sus-tonique, le /ré/, nous avons le /la/ qui correspond au degré 6. Ce
degré 6 est appelé *sus-dominante*, parce qu’il est situé juste
au-dessus de la dominante dans la gamme, ou encore *sous-médiante*
parce qu’il divise en deux tierces la quinte séparant la
sous-dominante de la tonique :

#+ATTR_HTML: :class plat
| Fonctions | : | Sous-dominante | ⟻ | 3ce | ⟼ | Sous-médiante | ⟻ | 3ce | ⟼ | Tonique |
| Degrés    | : |              4 | ⟻ | 3ce | ⟼ |             6 | ⟻ | 3ce | ⟼ |       1 |


*** Médiante

Reprenons notre exemple où /do/ est la tonique : une quinte plus haut
que la sous-médiante, le /la/, nous avons le /mi/ qui correspond au
degré 3. Ce degré 3 est appelé *médiante* parce qu’il divise en deux
tierces la quinte séparant la tonique de la dominante :

#+ATTR_HTML: :class plat
| Fonctions | : | Tonique | ⟻ | 3ce | ⟼ | Médiante | ⟻ | 3ce | ⟼ | Dominante |
| Degrés    | : |       1 | ⟻ | 3ce | ⟼ |        3 | ⟻ | 3ce | ⟼ |         5 |


*** Sous-tonique

Reprenons notre exemple où /do/ est la tonique : une quinte plus haut
que la médiante, le /mi/, nous avons le /si/ qui correspond au
degré 7. Ce degré 7 est appelé *sous-tonique* parce qu’il est situé
juste sous la tonique dans la gamme.


** Récapitulation

Le classement des degrés de la gamme par quintes croissantes nous
suggère la nomenclature et les abréviations suivantes :

| Degrés | Fonctions            | Abréviations |
|--------+----------------------+--------------|
|      2 | Dominante auxiliaire | Daux         |
|--------+----------------------+--------------|
|      5 | Dominante            | D            |
|--------+----------------------+--------------|
|      1 | Tonique              | T            |
|--------+----------------------+--------------|
|      4 | Sous-dominante       | SD           |


* Sémantique

#+TOC: headlines 1 local


** Introduction

La fonction tonale d’un accord peut correspondre au degré :

  - de la fondamentale
  - de la basse
  - du soprano
  - d’une éventuelle note redoublée
  - d’une note manquante d’un accord incomplet
  - d’une éventuelle pédale

Un même accord peut donc assurer différentes fonctions tonales,
suivant qu’une ou l’autre de ses notes est /mise en évidence/.
Inversément, différents accords peuvent jouer le rôle d’une même
fonction tonale.


** Lien sémantique

Lorsqu’une modification de la disposition d’un accord permet de
réinterpréter sa fonction tonale en la fonction tonale d’un autre
accord, on dit qu’il existe un *lien sémantique* entre ces deux
accords.


** Synonymes

Deux accords distincts remplissant une même fonction tonale sont dit
*synonymes*.


*** Recherche d’accords synonymes

Nous allons considérer un exemple simple afin de bien comprendre le
procédé permettant de découvrir des accords synonymes. Nous
choisissons donc la note /do/ comme tonique et nous voulons découvrir
les accords pouvant remplir la fonction de dominante. La dominante
étant le /sol/, cette note devra donc pouvoir être mise en évidence.
Le choix le plus évident est un accord du degré 5 avec le /sol/ comme
fondamentale, mais il en existe d’autres.

On peut parcourir le cycle des tierces pour découvrir les autres
accords à base de tierces incluant un /sol/. Pour les triades, cela
nous donne :

  - /sol/ si ré
  - mi /sol/ si
  - do mi /sol/

Il ne nous reste alors plus qu’à mettre en évidence le /sol/.
L’utilisation d’une doublure nous donne :

  - /sol/ si ré /sol/
  - /sol/ mi /sol/ si
  - /sol/ do mi /sol/


*** Sans fondamentale

Nous pouvons aussi considérer qu’un accord de degré 7 :

#+BEGIN_CENTER
si ré fa =...=
#+END_CENTER

est un accord de degré 5 privé de sa fondamentale :

#+BEGIN_CENTER
(sol) si ré fa =...=
#+END_CENTER

et remplit donc une fonction de dominante.


** Synonymes usuels

Étant donné une fonction tonale située sur le degré /X/, les synonymes
les plus utilisés sont :

  - les accords du degré /X/
  - les accords dont la fondamentale est située une tierce plus bas que le degré /X/
  - les accords dont la fondamentale est située une quinte plus bas que le degré /X/

En effet, tous ces accords contiennent la note du degré /X/, ce qui
permet de mettre la fonction tonale en évidence. On ajoute à cela les
accords situés à la tierce supérieure, considérés comme des degrés /X/
sans fondamentale.

Le tableau suivant donne un aperçu des synonymes :

| Quinte inférieure | Tierce inférieure | Degré tonal | Tierce supérieure |
|-------------------+-------------------+-------------+-------------------|
|                 4 |                 6 |           1 |                 3 |
|                 7 |                 2 |           4 |                 6 |
|                 1 |                 3 |           5 |                 7 |


Exemple en /do majeur/ :

| Quinte inférieure | Tierce inférieure | Degré tonal | Tierce supérieure |
|-------------------+-------------------+-------------+-------------------|
| fa                | la                | do          | mi                |
| si                | ré                | fa          | la                |
| do                | mi                | sol         | si                |

Exemple en /la mineur/ :

| Quinte inférieure | Tierce inférieure | Degré tonal | Tierce supérieure |
|-------------------+-------------------+-------------+-------------------|
| ré                | fa                | la          | do                |
| sol               | si                | ré          | fa                |
| la                | do                | mi          | sol               |


*** Les plus courants

Les possibilités les plus couramment employées sont rassemblées dans
ce tableau :

| Fonctions      | Degrés | Exemple      | Exemple      |
|                |        | en do majeur | en la mineur |
|----------------+--------+--------------+--------------|
| Tonique        |      1 | do           | la           |
|                |      3 | mi           | do           |
|                |      6 | la           | fa           |
| Sous-dominante |      4 | fa           | ré           |
|                |      2 | ré           | si           |
| Dominante      |      5 | sol          | mi           |
|                |      7 | si           | sol          |


** Récapitulation

| Lien            | Accords            | Fonctions tonales             |
|-----------------+--------------------+-------------------------------|
| lien sémantique | même accord        | fonctions tonales différentes |
| synonymes       | accords différents | même fonction tonale          |


* Dynamique

#+TOC: headlines 1 local


** Introduction

La dynamique musicale est basée sur l’alternance de *tension* et de
*détente*, la détente servant de *résolution* à la tension initiale :

#+ATTR_HTML: :class plat
| Tension | — | Résolution |

La tension d’un objet musical est souvent due à l’ *attraction* vers
un objet proche condidéré comme plus stable.

Un objet musical est qualifié de :

  - *stable* ou *consonant* s’il ne cause aucune tension

  - *instable* ou *dissonant* s’il provoque une tension

Un objet musical consonant est aussi appelé *consonance*.

Un objet musical dissonant est aussi appelé *dissonance*.


** Préparation

Une tension peut être précédée d’une phase de *préparation*, phase qui
permet d’introduire la future dissonance dans un contexte où elle est
consonante. On a donc la structure générique :

#+ATTR_HTML: :class plat
| Préparation | — | Tension | — | Résolution |

où la phase de préparation est optionnelle.


** Résolution

Lorsqu’une dissonance se résout indifféremment suivant plusieurs
processus différents, on dit alors que sa résolution est *libre*.

Lorsqu’une dissonance se résout préférentiellement via un processus
bien défini, correspondant à un effet de détente maximal, on dit alors
que cette résolution est *régulière* ou *ordinaire*. On parle
également de *mouvement obligé*.

Dans le cas où une dissonance censée adopter un mouvement obligé se
résout autrement, on parle de résolution *irrégulière* ou
*exceptionnelle*.

Enfin, lorsqu’une dissonance ne se résout pas, on conduit généralement
la musique vers une tension encore plus forte.


*** Absolue ou relative

La *résolution absolue* fait suivre un objet dissonant par un objet
consonant.

La *résolution relative* fait suivre un objet consonant par un objet
qui est encore plus consonant que le premier.


*** Nouveauté

La dissonance peut être utilisée comme *introduction* à un nouvel
objet musical, la résolution amenant alors la *nouveauté* que l’on
souhaite présenter :

#+ATTR_HTML: :class plat
| Introduction | = | Tension    |
| Nouveauté    | = | Résolution |


* Sensibles

#+TOC: headlines 1 local

** Introduction

Une note située à une distance d’un demi-ton de la tonique crée une
attraction mélodique vers cette dernière.

La tonique correspondant au degré 1, les notes qui l’entourent sont
situées aux degrés 2 et 7.

Lorsque le degré 7 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible inférieure*.

Lorsque le degré 2 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible supérieure*.

Exemples :

  - si la tonique est un /do/, le /si/ sera une sensible inférieure

  - si la tonique est un /mi/, le /fa/ sera une sensible supérieure

  - une gamme ayant /do/ pour tonique ne possède qu’une sensible
    inférieure, le /si/, qui est alors appelé sensible


** Sensibles auxiliaires

Une note située à une distance d’un demi-ton de la dominante crée une
attraction mélodique vers cette dernière.

La dominante correspondant au degré 5, les notes qui l’entourent sont
situées aux degrés 4 et 6.

Lorsque le degré 4 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire inférieure*.

Lorsque le degré 6 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire supérieure*.


** Tableau récapitulatif

| Degrés | Noms                           | Abréviations |
|--------+--------------------------------+--------------|
|      2 | Sensible supérieure            | Ssup         |
|--------+--------------------------------+--------------|
|      7 | Sensible inférieure            | Sinf         |
|        | Sensible                       | S            |
|--------+--------------------------------+--------------|
|      6 | Sensible auxiliaire supérieure | SauxSup      |
|--------+--------------------------------+--------------|
|      4 | Sensible auxiliaire inférieure | SauxInf      |


* Dynamique de la mélodie

#+TOC: headlines 1 local


** Sensibles

Une sensible induit une tension mélodique vers la fonction tonale la
plus proche : tonique ou dominante. Les sensibles sont donc
considérées comme des notes dissonantes.

Voici les résolutions attendues :

  - la sensible inférieure se résout sur la tonique en montant d’un demi-ton
  - la sensible supérieure se résout sur la tonique en descendant d’un demi-ton
  - la sensible auxiliaire inférieure se résout sur la dominante en montant d’un demi-ton
  - la sensible auxiliaire supérieure se résout sur la dominante en descendant d’un demi-ton


** Hauteur

Une note plus aiguë est plus tendue qu’une note plus grave.

Une note plus grave est plus détendue qu’une note plus aiguë.


** Intervalles

Un intervalle conjoint ne suscite pas de tension.

Un intervalle disjoint entre deux notes /x/ et /y/ suscite une tension
qui se résout en jouant les notes intermédiaires entre /x/ et /y/.


** Direction

Une mélodie qui monte vers l’aigu génère une tension.

Une mélodie qui descend vers le grave produit une détente.


** Extrêmes

Une mélodie dont les pics (maxima locaux) montent vers l’aigu génère
une tension.

Une mélodie dont les creux (minima locaux) descendent vers le grave
produit une détente.


* Dynamique des intervalles harmoniques

#+TOC: headlines 1 local


** Introduction

Les intervalles harmoniques peuvent être classés suivant leur
caractère consonant ou dissonant. Un *intervalle consonant* donne une
impression de douceur, d’équilibre, de plénitude. Par contre, un
*intervalle dissonant* est dans un état de tension qui est appelé à se
résoudre sur un intervalle consonant proche, appelé *intervalle de
résolution*.

La classification des intervalles harmoniques est basée sur la série
des harmoniques naturelles, série commençant par les intervalles
considérés comme consonants en théorie classique. Analysons par
exemple le début d’une série d’harmoniques naturelles de fondamentale
/do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Les premiers intervalles qui apparaissent sont :

| Intervalle harmonique | Note I | Note II |
|-----------------------+--------+---------|
| Unisson               |      1 |       1 |
| Octave                |      1 |       2 |
| Quinte                |      2 |       3 |
| Quarte                |      3 |       4 |
| Tierce majeure        |      4 |       5 |
| Tierce mineure        |      5 |       6 |
| Sixte majeure         |      3 |       5 |
| Sixte mineure         |      5 |       8 |
| Septième mineure      |      4 |       7 |
| Seconde majeure       |      8 |       9 |
| Quarte augmentée      |      8 |      11 |

La classification usuelle des intervalles considère les intervalles
comme consonants jusqu’aux sixtes, et dissonants ensuite. Les
intervalles augmentés et diminués sont également considérés comme
dissonants.


** Consonances

Le tableau suivant donne la liste des intervalles consonants :

| Consonances                | Intervalles harmoniques |
|----------------------------+-------------------------|
| Consonances parfaites      | Unisson                 |
|                            | Octave                  |
|                            | Quinte                  |
| Consonances intermédiaires | Quarte                  |
| Consonances imparfaites    | Tierce majeure          |
|                            | Tierce mineure          |
|                            | Sixte majeure           |
|                            | Sixte mineure           |

/Remarque/ : le terme « consonance imparfaite » ne signifie pas qu’une
tierce ou une sixte sonne moins bien qu’une quinte ou qu’une octave,
mais simplement que les notes des consonances parfaites se ressemblent
plus que celles des consonances imparfaites.


** Dissonances

Le tableau suivant donne la liste des intervalles dissonants :

| Dissonances                | Intervalles harmoniques |
|----------------------------+-------------------------|
| Dissonances imparfaites    | Septième mineure        |
|                            | Seconde majeure         |
| Dissonances intermédiaires | Quarte augmentée        |
| Dissonances parfaites      | Septième majeure        |
|                            | Seconde mineure         |
| Autres                     | Intervalles diminués    |
|                            | Intervalles augmentés   |


* Accords parfaits

#+TOC: headlines 1 local

** Introduction

Les accords de trois notes sont construits en empilant deux tierces.
Utilisons ce procédé sur chaque note diatonique et analysons les
intervalles obtenus :

| Note | Accord    | Intervalles |             |             |
|      |           | Notes 1 & 2 | Notes 2 & 3 | Notes 1 & 3 |
|------+-----------+-------------+-------------+-------------|
| do   | do mi sol | 3ce M       | 3ce m       | 5te         |
| ré   | ré fa la  | 3ce m       | 3ce M       | 5te         |
| mi   | mi sol si | 3ce m       | 3ce M       | 5te         |
| fa   | fa la do  | 3ce M       | 3ce m       | 5te         |
| sol  | sol si ré | 3ce M       | 3ce m       | 5te         |
| la   | la do mi  | 3ce m       | 3ce M       | 5te         |
| si   | si ré fa  | 3ce m       | 3ce m       | 5te dim     |

Les accords obtenus génèrent des intervalles de tierce et
de quinte par rapport à la fondamentale. On constate en fait trois
possibilités :

  - tierce majeure puis tierce mineure, le total formant une quinte juste
  - tierce mineure puis tierce majeure, le total formant une quinte juste
  - deux tierces mineures, formant au total une quinte diminuée

L’ *accord parfait majeur* est construit en empilant une tierce
majeure, puis une tierce mineure, les deux intervalles totalisant une
quinte juste.

L’ *accord parfait mineur* est construit en empilant une tierce
mineure, puis une tierce majeure, les deux intervalles totalisant une
quinte juste.

Ces accords sonnent particulièrement bien.

Notons que l’on retrouve les notes d’un accord parfait majeur dans les
six premiers éléments de la suite des harmoniques naturelles. Rien
d’étonnant à ce qu’il soit considéré comme l’une des clefs de voûte de
l’harmonie.

Exemples d’accords parfaits :

| Accords        | Abréviations | Exemples  |
|----------------+--------------+-----------|
| Parfait majeur | P M          | do mi sol |
| Parfait mineur | P m          | la do mi  |


** Renversements

Au premier renversement, la fondamentale est séparée de la basse par
un intervalle de sixte. Cet intervalle donne son nom à l’accord,
simplement appelé *accord de sixte* :

| Accords | Abréviations | Exemples  |
|---------+--------------+-----------|
| Sixte   | 6te          | mi sol do |
| Sixte   | 6te          | do mi la  |

Au second renversement, les notes de l’accord sont séparées de la
basse par des intervalles de quarte et de sixte. Ces intervalles
donnent leur nom à l’accord, qui est appelé *accord de quarte et
sixte* :

| Accords         | Abréviations | Exemples  |
|-----------------+--------------+-----------|
| Quarte et sixte | 4te & 6te    | sol do mi |
| Quarte et sixte | 4te & 6te    | mi la do  |


** Accord de quinte diminuée

L’ *accord de quinte diminuée* est construit en empilant deux tierces
mineures, les deux intervalles totalisant une quinte diminuée.

Il est important de noter que cet accord ne fait pas partie des
accords parfaits.


* Majeur et mineur

#+TOC: headlines 1 local


** Introduction

Le tableau suivant regroupe les accords de trois notes générés par les
degrés des modes naturels. La lettre *M* signifie accord parfait
majeur et la lettre *m* accord parfait mineur. Le symbole *dim*
signifie ici accord de quinte diminuée :

| Modes      |     | Degrés |     |     |     |     |     |     |
|            |     | 4      | 1   | 5   | 2   | 6   | 3   | 7   |
|------------+-----+--------+-----+-----+-----+-----+-----+-----|
| Lydien     | fa  | dim    | M   | M   | M   | m   | m   | m   |
| Ionien     | do  | M      | M   | M   | m   | m   | m   | dim |
| Mixolydien | sol | M      | M   | m   | m   | m   | dim | M   |
| Dorien     | ré  | M      | m   | m   | m   | dim | M   | M   |
| Éolien     | la  | m      | m   | m   | dim | M   | M   | M   |
| Phrygien   | mi  | m      | m   | dim | M   | M   | M   | m   |
| Locrien    | si  | m      | dim | M   | M   | M   | m   | m   |

Parmi les modes naturels, les modes ionien et éolien sont les seuls à
présenter le même type d’accords sur les fonctions tonales principales
4, 1, 5 :

| Modes  | Degrés |   |   |     |   |   |     |
|        | 4      | 1 | 5 | 2   | 6 | 3 | 7   |
|--------+--------+---+---+-----+---+---+-----|
| Ionien | M      | M | M | m   | m | m | dim |
| Éolien | m      | m | m | dim | M | M | M   |

Pour cette raison :

  - le mode ionien est aussi appelé *mode majeur*
  - le mode éolien est aussi appelé *mode mineur*

Exemple de mode majeur avec la tonalité de /do majeur/ :

#+BEGIN_CENTER
do ré mi fa sol la si do
#+END_CENTER

Exemple de mode mineur avec la tonalité de /la mineur/ :

#+BEGIN_CENTER
la si do ré mi fa sol la
#+END_CENTER


** Degrés & intervalles caractéristiques

Les modes majeur et mineur sont les modes les plus utilisés. On s’en
sert donc comme référence pour souligner les *degrés caractéristiques*
des autres modes. Ces degrés forment des *intervalles
caractéristiques* avec la tonique.


*** Autour du mode majeur

En partant de /do majeur/, les quintes voisines nous donnent les
gammes de /sol mixolydien/ et /fa lydien/.

Si nous transposons la gamme de /sol mixolydien/ vers la tonique /do/,
nous obtenons :

#+begin_center
do ré mi fa sol la /si^b/ do
#+end_center

La note caractéristique du mode mixolydien est donc le /si^b/,
septième degré formant un intervalle de septième mineure avec la
tonique.

Si nous transposons la gamme de /fa lydien/ vers la tonique /do/,
nous obtenons :

#+begin_center
do ré mi /fa^{#}/ sol la si do
#+end_center

La note caractéristique du mode lydien est donc le /fa^{#}/, quatrième
degré formant un intervalle de quarte augmentée avec la tonique.


*** Autour du mode mineur

En partant de /la mineur/, les quintes voisines nous donnent les
gammes de /mi phrygien/ et /ré dorien/.

Si nous transposons la gamme de /mi phrygien/ vers la tonique /la/,
nous obtenons :

#+begin_center
la /si^b/ do ré mi fa sol la
#+end_center

La note caractéristique du mode phrygien est donc le /si^b/, deuxième
degré formant un intervalle de seconde mineure avec la tonique.

Si nous transposons la gamme de /ré dorien/ vers la tonique /la/, nous
obtenons :

#+begin_center
la si do ré mi /fa^{#}/ sol la
#+end_center

La note caractéristique du mode dorien est donc le /fa^{#}/, sixième
degré formant un intervalle de sixte majeure avec la tonique.

Nous n’avons pas encore exploré le mode locrien. Partons de la gamme
de /si locrien/ et transposons vers la tonique /la/, deux quintes plus
bas. Nous obtenons :

#+begin_center
la si^b do ré mi^b fa sol la
#+end_center

Les notes caractéristiques du mode locrien sont donc le /si^b/ et le
/la^b/, deuxième et cinquième degré formant des intervalles de seconde
mineure et quinte diminuée avec la tonique.


*** Récapitulation

| Modes           |           Degré | Intervalle      |
|                 | caractéristique | caractéristique |
|-----------------+-----------------+-----------------|
| Locrien         |               2 | 2de mineure     |
|                 |               5 | 5te diminuée    |
| Phrygien        |               2 | 2de mineure     |
| Éolien (Mineur) |                 | —               |
| Dorien          |               6 | 6te majeure     |
| Mixolydien      |               7 | 7e mineure      |
| Ionien (Majeur) |                 | —               |
| Lydien          |               4 | 4te augmentée   |


* Autres modes

#+TOC: headlines 1 local

** Introduction

Nous étudions dans ce chapitre les modes dérivés des modes naturels.


** Mineur


*** Mineur harmonique

Le mode majeur dispose d’une sensible inférieure. Par exemple,
en /do majeur/, la sensible inférieure est le /si/, à un demi-ton de
la tonique /do/. Cette propriété est intéressante car la sensible est
naturellement attirée par la tonique, ce qui permet de donner de la
dynamique à un déroulement musical.

En mode mineur par contre, le degré 7 est situé un ton entier sous la
tonique. La propriété d’attirance de la sensible vers la tonique n’est
donc pas présente. On peut toutefois y remédier en haussant la
sous-tonique d’un demi-ton, obtenant ainsi un mode dérivé, appelé
*mode mineur harmonique*. Par exemple, en /la mineur/, le /sol/ sera
haussé d’un demi-ton, donnant ainsi la gamme :

#+BEGIN_CENTER
la si do ré mi fa sol^{#} la
#+END_CENTER

Dans la suite, le mode mineur par défaut sera généralement le mode
mineur harmonique.


*** Mineur ascendant et descendant

Le mode mineur harmonique sonne très bien, disposant à la fois de la
sonorité du mode mineur et de l’attirance de la sensible inférieure.
Cependant, l’écart de trois demi-tons entre les degrés 6 et 7 n’est
pas toujours souhaitable. Dans ce cas, on hausse le degré 6, obtenant
un mode appelé *mode mineur ascendant*. Exemple, le /la mineur
ascendant/ :

#+BEGIN_CENTER
la si do ré mi fa^{#} sol^{#} la
#+END_CENTER

Par opposition, on appelle alors *mode mineur descendant* le mode
mineur naturel (le mode éolien). En pratique, les modes mineurs
(harmonique, ascendant et descendant) sont souvent mêlés, donnant
ainsi beaucoup de couleur et de souplesse à la musique. Enfin, le
degré 3 peut lui aussi être haussé d’un demi-ton, complétant ainsi le
caractère polymorphe du mode mineur, qui peut se rapprocher ou même se
confondre avec le mode majeur.


*** Conclusion

Le mode mineur est très versatile, et ses altérations flottantes
donnent une couleur particulière à la musique.


** Variantes des modes naturels


*** Acoustique

Le mode acoustique est construit à partir des premiers éléments de la
série des harmoniques naturelles. Elle contient donc une quinte, une
tierce majeure, une septième mineure, une seconde majeure et une
quarte augmentée. En partant d’un /do/, on obtient :

#+BEGIN_CENTER
do ré mi fa^{#} sol si^b do
#+END_CENTER

On peut bien entendu ajouter la note naturelle manquante, à savoir
le /la/ :

#+BEGIN_CENTER
do ré mi fa^{#} sol la si^b do
#+END_CENTER

La gamme ainsi obtenue possède les mêmes écarts qu’un relatif du mode
mineur ascendant à partir du quatrième degré :

#+BEGIN_CENTER
ré mi fa^{#} sol^{#} la si do ré
#+END_CENTER


*** Superlocrien

Le mode superlocrien est construit comme un relatif du mode mineur
ascendant à partir du septième degré :

#+BEGIN_CENTER
sol^{#} la si do ré mi fa^{#} sol^{#}
#+END_CENTER

Ce mode est appelé superlocrien, car il ressemble fort au mode
locrien. On le voit clairement en prenant /si/ comme tonique :

#+BEGIN_CENTER
si do ré mi^b fa sol la si
#+END_CENTER


**** Mineur harmonique

Il existe aussi une variante dérivée du mode mineur harmonique :

#+BEGIN_CENTER
sol^{#} la si do ré mi fa sol^{#}
#+END_CENTER

ce qui donne, en prenant /si/ comme tonique :

#+BEGIN_CENTER
si do ré mi^b fa sol la^b si
#+END_CENTER


*** Tzigane

Le mode Tzigane, ou mode Hongrois, est un mode dérivé du mineur
harmonique, le 4e degré étant haussé afin de se rapprocher de la
dominante :

#+BEGIN_CENTER
la si do ré^{#} mi fa sol^{#} la
#+END_CENTER

Ce mode est caractérisé par la présence de deux sensibles auxiliaires :

#+BEGIN_CENTER
sensible auxiliaire inférieure ⟼ dominante ⟻ sensible auxiliaire supérieure
#+END_CENTER

Notons les deux écarts de trois demi-tons entre les degrés 3 - 4 et
6 - 7.


*** Andalou

Il s’agit d’un mode ressemblant au /mode de mi/, mais disposant d’une
médiante flottante, formant une tierce majeure ou mineure avec la
tonique :

#+BEGIN_CENTER
mi fa sol^{(#)} la si do ré mi
#+END_CENTER


*** Napolitain

Il s’agit d’un mode ressemblant au /mode de mi/ où le septième degré
est haussé d’un demi-ton, ce qui le transforme en sensible inférieure :

#+BEGIN_CENTER
mi fa sol la si do ré^{#} mi
#+END_CENTER

On voit que la sus-tonique est une sensible supérieure. Ce mode est
donc caractérisé par la double attraction :

#+BEGIN_CENTER
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+END_CENTER

Il en existe une variante où le sixième degré est haussé :

#+BEGIN_CENTER
mi fa sol la si do^{#} ré^{#} mi
#+END_CENTER


*** Oriental


**** Variante phrygienne

Il s’agit d’un mode ressemblant au /mode de mi/, mais caractérisé par
les mêmes altérations que la gamme tzigane située une quinte plus
bas :

#+BEGIN_CENTER
mi fa sol^{#} la si do ré^{#} mi
#+END_CENTER

Ce mode est caractérisé par les deux écarts de trois demi-tons entre
les degrés 2 - 3 et 6 - 7, ainsi que par la double attraction :

#+BEGIN_CENTER
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+END_CENTER

Si on souhaite également créer une double attraction vers la
dominante :

#+BEGIN_CENTER
sous-dominante altérée ⟼ dominante ⟻ sous-médiante
#+END_CENTER

il suffit de hausser le degré 4 :

#+BEGIN_CENTER
mi fa sol^{#} la^{#} si do ré^{#} mi
#+END_CENTER


**** Variante locrienne

Il s’agit d’un mode ressemblant au /mode de si/, mais caractérisé par
les mêmes altérations que la gamme tzigane située deux quintes plus
bas :

#+BEGIN_CENTER
si do ré^{#} mi fa sol^{#} la si
#+END_CENTER

Afin d’obtenir la même propriété de double attraction que la variante
basée sur le mode de /mi/, on peut sensibiliser le degré 7 en le
haussant d’un demi-ton :

#+BEGIN_CENTER
si do ré^{#} mi fa sol^{#} la^{#} si
#+END_CENTER


** Tétraphoniques

Les modes tetraphoniques sont des gammes de quatre notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
quatre quintes :

#+BEGIN_CENTER
do sol ré la
#+END_CENTER

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode tetraphonique :

#+BEGIN_CENTER
do ré sol la do
#+END_CENTER

et ses relatifs :

#+ATTR_HTML: :class plat
| sol | la  | do | ré  | sol |
| ré  | sol | la | do  | ré  |
| la  | do  | ré | sol | la  |


** Pentaphoniques

Les modes pentaphoniques sont des gammes de cinq notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
cinq quintes :

#+BEGIN_CENTER
do sol ré la mi
#+END_CENTER

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode pentaphonique :

#+BEGIN_CENTER
do ré mi sol la do
#+END_CENTER

et ses relatifs :

#+ATTR_HTML: :class plat
| sol | la  | do  | ré | mi  | sol |
| ré  | mi  | sol | la | do  | ré  |
| la  | do  | ré  | mi | sol | la  |
| mi  | sol | la  | do | ré  | mi  |


*** Avec caractéristique

Ce sont des modes pentaphoniques que l’on altère afin d’intégrer une
ou plusieurs notes caractéristiques des modes naturels. Par exemple,
ces modes pentaphoniques altérés :

#+ATTR_HTML: :class plat
| ré | mi | sol^{#} | la | do  | ré |
| la | do | ré^{#}  | mi | sol | la |

possèdent une quarte haussée, caractéristique du mode lydien.


*** Blues

Le mode blues est un mode pentaphonique développant les quintes à
partir de la médiante. La médiante, la dominante et la sous-tonique
sont flottantes :

#+BEGIN_CENTER
la do^{(#)} ré mi^{(b)} sol^{(#)} la
#+END_CENTER


*** Chinois

Le mode chinois est un mode pentaphonique développant les quintes à
partir de la tonique. Par exemple, avec /do/ comme tonique, nous
obtenons :

#+BEGIN_CENTER
do ré mi sol la do
#+END_CENTER


*** Japonais

Le mode japonais est un mode pentaphonique développant les quintes à
partir de la sous-dominante. Il est caractérisé par un intervalle de
quarte augmentée, intervalle qui sépare sa dominante auxiliaire de sa
dominante. La gamme modèle de ce mode possède un /mi/ pour tonique. On
part alors de la sous-dominante /la/ et on gravit les quintes entre
notes naturelles :

#+BEGIN_CENTER
la mi si fa do
#+END_CENTER

On voit que ce procédé produit la quinte diminuée /si — fa/. En
disposant ces notes sur une octave /mi — mi^{+1}/ et en les ordonnant
de la plus grave à la plus aiguë, nous obtenons :

#+BEGIN_CENTER
mi fa la si do mi
#+END_CENTER

La dominante auxiliaire /fa/ est donc une sensible supérieure. Le mode
possède un autre demi-ton entre la dominante /si/ et la sous-médiante
/do/.


* Accords classés

#+TOC: headlines 1 local


** Introduction

Les accords classés sont des accords naturellement engendrés par les
gammes lorsqu’on y superpose des tierces.


** Tonique

Les accords de tonique les plus utilisés sont des *accords parfaits
majeur ou mineur*. On rencontre aussi parfois des accords de quatre
notes, comme dans ces exemples :

| Accords             | Abréviations | Exemples             |                  |
|                     |              | Gammes               | Accords          |
|---------------------+--------------+----------------------+------------------|
| Septième majeure    | 7e M         | do majeur            | do mi sol si     |
| Septième mineure    | 7e m         | la mineur            | la do mi sol     |
| Septième harmonique | 7e h         | la mineur harmonique | la do mi sol^{#} |

et plus rarement des accords de 5, 6 ou 7 notes.


*** Quinte augmentée

Si nous supprimons la fondamentale de l’accord de septième harmonique,
nous obtenons un accord dit de *quinte augmentée* :

| Accords          | Abréviations | Exemples      |
|------------------+--------------+---------------|
| Quinte augmentée | 5te aug      | do mi sol^{#} |


** Dominante

Les accords de dominante sont très importants, de par leur fonction
tonale dynamique et parce qu’ils sont naturellement attirés par un
accord de tonique.


*** Triades

En empilant deux tierces, on obtient un accord parfait majeur, que ce
soit en mode majeur ou mineur harmonique :

| Accords        | Abréviations | Exemples             |               |
|                |              | Gammes               | Accords       |
|----------------+--------------+----------------------+---------------|
| Parfait majeur | M            | do majeur            | sol si ré     |
| Parfait majeur | M            | la mineur harmonique | mi sol^{#} si |


*** Septième

En empilant trois tierces, on obtient l’accord de *septième de
dominante*, dont la structure est identique en majeur et en mineur
harmonique :

| Accords               | Abréviations | Exemples             |                  |
|                       |              | Gammes               | Accords          |
|-----------------------+--------------+----------------------+------------------|
| Septième de dominante | 7e D         | do majeur            | sol si ré fa     |
| Septième de dominante | 7e D         | la mineur harmonique | mi sol^{#} si ré |

Avec les parfaits majeur et mineur, la septième de dominante figure
parmi les accords les plus importants de l’harmonie tonale.


*** Neuvième

En empilant quatre tierces, on obtient la neuvième de dominante,
majeure ou mineure suivant le mode :

| Accords                       | Abréviations | Exemples             |                     |
|                               |              | Gammes               | Accords             |
|-------------------------------+--------------+----------------------+---------------------|
| Neuvième de dominante majeure | 9e D M       | do majeur            | sol si ré fa la     |
| Neuvième de dominante mineure | 9e D m       | la mineur harmonique | mi sol^{#} si ré fa |


*** Onzième, treizième

Viennent ensuite les onzième et treizième de dominante comprenant
respectivement 6 et 7 notes.


*** Sans fondamentale

La fondamentale des accords de dominante est parfois omise. Il en
résulte les accords suivants :

| Accords      | Accords                     | Abréviations | Exemples         |
| de dominante | sans fondamentale           |              |                  |
|--------------+-----------------------------+--------------+------------------|
| 7e D         | Quinte diminuée             | 5te dim      | si ré fa         |
| 9e D M       | Septième et Quinte diminuée | 7e & 5te dim | si ré fa la      |
| 9e D m       | Septième diminuée           | 7e dim       | sol^{#} si ré fa |


** Sous-dominante

Les accords de sous-dominante sont similaires aux accords de tonique :
accords parfaits et septièmes majeures ou mineures. Exemples :

| Accords | Exemples  |             |
|         | Gammes    | Accords     |
|---------+-----------+-------------|
| 7e M    | do majeur | fa la do mi |
| 7e m    | la mineur | ré fa la do |


** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: section:dominanteAuxiliaire
:END:

Les accords de dominante auxiliaire sont similaires aux accords de
dominante, si ce n’est qu’ils sont construits sur le degré 2 de la
gamme. Afin de renforcer le rôle de ces accords, il est possible de
les altérer en faisant /comme si/ la dominante de la gamme courante
devenait la tonique. On utilise les abréviations :

| Accords                          | Abréviations |
|----------------------------------+--------------|
| Triade de dominante auxiliaire   | 3ade Daux    |
| Septième de dominante auxiliaire | 7e Daux      |
| Neuvième de dominante auxiliaire | 9e Daux      |


*** Majeur

Nous prenons comme illustration la gamme de /do majeur/. Nous obtenons
par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| do ré mi fa sol la si do | ⟼ | sol la si do ré mi fa^{#} sol |

L’altération haussière du /fa^{#}/ (degré 4 par rapport à la tonique
/do/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /sol/.

On peut également altérer le /la/ (degré 6 par rapport à la tonique
/do/) vers le bas afin de le transformer en sensible auxiliaire
supérieure de la dominante /sol/. Nous avons alors la gamme :

#+BEGIN_CENTER
sol la^b si do ré mi fa^{#} sol
#+END_CENTER

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en do majeur |
|-------------------------+-----------+-----------------------|
| Aucune                  | 3ade Daux | ré fa la              |
|                         | 7e Daux   | ré fa la do           |
|                         | 9e Daux   | ré fa la do mi        |
| Inférieure              | 3ade Daux | ré fa^{#} la          |
|                         | 7e Daux   | ré fa^{#} la do       |
|                         | 9e Daux   | ré fa^{#} la do mi    |
| Inférieure & Supérieure | 3ade Daux | ré fa^{#} la^b        |
|                         | 7e Daux   | ré fa^{#} la^b do     |
|                         | 9e Daux   | ré fa^{#} la^b do mi  |


*** Mineur harmonique

Nous prenons comme illustration la gamme de /la mineur harmonique/.
Nous obtenons par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| la si do ré mi fa sol^{#} la | ⟼ | mi fa^{#} sol la si do ré^{#} mi |

L’altération haussière du /ré^{#}/ (degré 4 par rapport à la tonique
/la/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /mi/.

Si on supprime l’altération haussière du /fa^{#}/ (degré 6 par rapport
à la tonique /la/), on transforme ce degré en sensible auxiliaire
supérieure de la dominante /mi/. Nous obtenons alors la gamme :

#+BEGIN_CENTER
mi fa sol la si do ré^{#} mi
#+END_CENTER

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en la mineur harmonique |
|-------------------------+-----------+----------------------------------|
| Supérieure              | 2ade Daux | si ré fa                         |
|                         | 7e Daux   | si ré fa la                      |
|                         | 9e Daux   | si ré fa la do                   |
| Inférieure              | 3ade Daux | si ré^{#} fa^{#}                 |
|                         | 7e Daux   | si ré^{#} fa^{#} la              |
|                         | 9e Daux   | si ré^{#} fa^{#} la do           |
| Inférieure & Supérieure | 3ade Daux | si ré^{#} fa                     |
|                         | 7e Daux   | si ré^{#} fa la                  |
|                         | 9e Daux   | si ré^{#} fa la do               |

Remarquons en passant que la triade de dominante auxiliaire non
altérée est un accord de quinte diminuée.


*** Sans fondamentale

Tout comme les accords de dominante, les accords de dominante
auxiliaire sont parfois présentés sans leur fondamentale. On obtient
alors des accords qui semblent être du degré 4, les fonctions de
dominante auxiliaire et de sous-dominante se voyant ainsi intimement
liées.

Exemple en /do majeur/ :

| Sensibles auxiliaires   | Accords | Exemples en do majeur |
|-------------------------+---------+-----------------------|
| Aucune                  | 7e Daux | fa la do              |
|                         | 9e Daux | fa la do mi           |
| Inférieure              | 7e Daux | fa^{#} la do          |
|                         | 9e Daux | fa^{#} la do mi       |
| Inférieure & Supérieure | 7e Daux | fa^{#} la^b do        |
|                         | 9e Daux | fa^{#} la^b do mi     |

Exemple en /la mineur harmonique/ :

| Sensibles auxiliaires   | Accords | Exemples en la mineur harmonique |
|-------------------------+---------+----------------------------------|
| Supérieure              | 7e Daux | ré fa la                         |
|                         | 9e Daux | ré fa la do                      |
| Inférieure              | 7e Daux | ré^{#} fa^{#} la                 |
|                         | 9e Daux | ré^{#} fa^{#} la do              |
| Inférieure & Supérieure | 7e Daux | ré^{#} fa la                     |
|                         | 9e Daux | ré^{#} fa la do                  |


*** Sixtes augmentées

Certains accords de dominante auxiliaire présentent de par leurs
altérations et leurs renversements un intervalle caractéristique de
sixte augmentée.


**** Sixte française

La *sixte française* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est présentée sous la forme d’un
second renversement.

En /do majeur/, nous obtenons :

#+BEGIN_CENTER
la^b do ré fa^{#}
#+END_CENTER

En /la mineur/, nous obtenons :

#+BEGIN_CENTER
fa la si ré^{#}
#+END_CENTER


**** Sixte italienne

La *sixte italienne* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (ré) fa^{#} la^b do | ⟼ | la^b do (ré) fa^{#} |

ce qui nous donne finalement :

#+BEGIN_CENTER
la^b do fa^{#}
#+END_CENTER

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la | ⟼ | fa la (si) ré^{#} |

ce qui nous donne finalement :

#+BEGIN_CENTER
fa la ré^{#}
#+END_CENTER


**** Sixte allemande

La *sixte allemande* est une neuvième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la do | ⟼ | fa la do (si) ré^{#} |

ce qui nous donne finalement :

#+BEGIN_CENTER
fa la do ré^{#}
#+END_CENTER

L’accord altéré de /do majeur/ respectant les mêmes écarts s’écrit :

#+BEGIN_CENTER
la^b do mi^b fa^{#}
#+END_CENTER


** Emprunts

Un emprunt est un accord provenant d’une autre gamme (tonique et/ou
mode) que l’on insère dans la gamme courante.


*** Majeur ⟻⟼ Mineur

On peut placer des accords caractéristiques du mineur (quintes
augmentées, septièmes diminuées, ...) dans des gammes majeures, ou
l’inverse.


*** Tierces picardes

Une *tierce picarde* est un accord parfait majeur intégré à un autre
mode. On la rencontre souvent sur les degrés 1, 5, ou 4 du mode
mineur : la tierce de l’accord y est rendue majeure par une altération
haussière. Voici des exemples en /la mineur/ :

| Degrés | Exemples      |
|--------+---------------|
|      1 | la do^{#} mi  |
|      4 | ré fa^{# la}  |
|      5 | mi sol^{#} si |


*** Napolitain

En gamme de /mi napolitain/, l’accord de dominante auxiliaire non
altéré :

#+BEGIN_CENTER
fa la do
#+END_CENTER

est un accord parfait majeur situé un demi-ton au-dessus de la tonique
/mi/. Par extension, on appelle accord *napolitain* tout accord défini
par les mêmes propriétés, et ce quels que soient le mode et la
tonique. Voici ce que cela donne en majeur et en mineur :

| do majeur    | la mineur  |
|--------------+------------|
| ré^b fa la^b | si^b ré fa |

Lorsque cet accord est présenté sous la forme de premier renversement,
il est appelé *sixte napolitaine* :

| do majeur    | la mineur  |
|--------------+------------|
| fa la^b ré^b | ré fa si^b |

Afin de former un accord similaire à une 7e de dominante, on peut
ajouter une note de 7e mineure à l’accord napolitain :

| do majeur         | la mineur       |
|-------------------+-----------------|
| ré^b fa la^b do^b | si^b ré fa la^b |

Ces derniers accords sont très prisé en jazz, où ils sont parfois
appelés *substitution au triton*, ou *substitution tritonique* à cause
de l’intervalle de triton qui lie la dominante auxiliaire altérée vers
le bas avec la dominante.


** Modes composites

Un *mode composite* associe à chaque degré une liste d’accords qui lui
sont caractéristiques. Voici un exemple de mode composite proche du
/la mineur/ :

| Degrés | Accords                     | Exemples             |
|--------+-----------------------------+----------------------|
|      1 | Parfait mineur              | la do mi             |
|        | Parfait majeur              | la do^{#} mi         |
|      2 | 7e Daux                     | si ré fa la          |
|        |                             | si ré^{#} fa la      |
|        | Napolitains                 | si^b ré fa           |
|        |                             | si^b ré fa la^b      |
|      3 | Quinte augmentée            | do mi sol^{#}        |
|      4 | Parfait mineur              | ré fa la             |
|        | Parfait majeur              | ré fa^{#} la         |
|      5 | Septième de dominante       | mi sol^{#} si ré     |
|        | Neuvième de dominante       | mi sol^{#} si ré fa  |
|      6 | Parfait majeur              | fa la do             |
|        | Quinte diminuée             | fa^{#} la do         |
|      7 | Quinte diminuée             | sol^{#} si ré        |
|        | Septième diminuée           | sol^{#} si ré fa     |
|        | Septième et quinte diminuée | sol^{#} si ré fa^{#} |

Cette variété d’accords implique qu’une partie ou la totalité des
notes de la gamme peut être altérée vers le haut ou vers le bas en
fonction du contexte.


* Accords à base de quintes

Les accords à base de tierces, présents dans les premières harmoniques
naturelles, sont de loin les plus utilisés. Mais on rencontre
également une autre famille d’accords, où la quinte est la brique de
construction. Le cas le plus simple consiste à superposer deux
quintes, obtenant ainsi une triade que nous décidons de nommer accord
de *double quinte* :

| Accords       | Exemples  |
|---------------+-----------|
| Double quinte | fa do sol |

En permutant les notes afin de les rapprocher, nous obtenons les
accords de *double quarte*, de *quarte et quinte* et de *seconde et
quinte* :

| Accords           | Exemples  |
|-------------------+-----------|
| Double quarte     | sol do fa |
| Quarte et quinte  | do fa sol |
| Seconde et quinte | fa sol do |

Les accords de quatre et cinq notes sont construits en superposant
trois ou quatre quintes :

| Accords          | Exemples         |
|------------------+------------------|
| Triple quinte    | fa do sol ré     |
| Quadruple quinte | fa do sol ré la  |

En intervertissant l’ordre des notes, ces accords deviennent des
accords de triple et quadruple quarte :

| Accords          | Exemples        |
|------------------+-----------------|
| Triple quarte    | ré sol do fa    |
| Quadruple quarte | la ré sol do fa |

Voici quelques autres permutations de ces accords :

| Triple quinte | Quadruple quinte |
|---------------+------------------|
| do ré fa sol  | do ré fa sol la  |
| do fa sol ré  | do fa sol la ré  |

/Remarque/ : jouer un accord de triple quinte revient à construire
localement un mode tétraphonique. Dans le même ordre d’idée, jouer un
accord de quadruple quinte revient à construire localement un mode
pentaphonique.


* Dynamique des accords

#+TOC: headlines 1 local


** Introduction

Dans le cadre d’un accord :

  - une *note consonante* est une note constitutive qui forme un
    intervalle harmonique consonant avec la fondamentale

  - une *note dissonante* est une note constitutive qui forme un
    intervalle harmonique dissonant avec la fondamentale

Une note dissonante est également appelée *dissonance constitutive*.

Les accords sont également classés suivant leur caractère stable ou
instable :

  - un *accord consonant* est un accord

    + qui ne contient que des notes consonantes

    + ET dont tous les intervalles internes sont consonants

  - un *accord dissonant* est un accord

    + qui contient au moins une note dissonante

    + OU dont au moins un intervalle interne est dissonant


** Classification


*** Accords parfaits

Les notes d’un accord parfait majeur forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte

avec la fondamentale de l’accord. Les intervalles internes sont
également des tierces et des quintes.

L’ *accord parfait majeur* est donc un accord *consonant*.

#+BEGIN_CENTER
⁂
#+END_CENTER

Les notes d’un accord parfait mineur forment des intervalles :

  - d’unisson
  - de tierce mineure
  - de quinte

avec la fondamentale de l’accord. Les intervalles internes sont
également des tierces et des quintes.

L’ *accord parfait mineur* est donc un accord *consonant*.

#+BEGIN_CENTER
⁂
#+END_CENTER


**** Premier renversement

Les notes d’un accord parfait majeur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce mineure
  - de sixte mineure

avec la fondamentale de l’accord. Les intervalles internes sont
des tierces, des quartes et des sixtes.

L’accord parfait majeur au premier renversement est donc un accord
consonant.

Les notes d’un accord parfait mineur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce majeure
  - de sixte majeure

avec la fondamentale de l’accord. Les intervalles internes sont
des tierces, des quartes et des sixtes.

L’accord parfait mineur au premier renversement est donc un accord
consonant.


**** Second renversement

Les notes d’un accord parfait majeur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte majeure

avec la fondamentale de l’accord. Les intervalles internes sont des
tierces, des quartes et des sixtes.

L’accord parfait majeur au second renversement est donc un accord
consonant.

Les notes d’un accord parfait mineur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte mineure

avec la fondamentale de l’accord. Les intervalles internes sont des
tierces, des quartes et des sixtes.

L’accord parfait mineur au second renversement est donc un accord
consonant.


*** Autres triades

Les notes d’un accord de quinte augmentée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte augmentée

avec la fondamentale de l’accord. La quinte augmentée étant un
intervalle harmonique dissonant, l’accord de *quinte augmentée* est
également *dissonant*.

#+BEGIN_CENTER
⁂
#+END_CENTER

Les notes d’un accord de quinte diminuée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte diminuée

avec la fondamentale de l’accord. La quinte diminuée étant un
intervalle harmonique dissonant, l’accord de *quinte diminuée* est
également *dissonant*.


*** Septième de dominante

Les notes d’un accord de septième de dominante forment des
intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte
  - de septième mineure

avec la fondamentale de l’accord. La septième mineure étant un
intervalle harmonique dissonant, l’accord de *septième de dominante*
est également *dissonant*.


*** Accords à base de quintes

Les accords à base de quintes contiennent au moins un intervalle
dissonant : seconde, septième, neuvième, etc. Ce sont donc des accords
dissonants.


*** Autres accords de quatre notes ou plus

Un accord de quatre notes ou plus contient au moins une note qui va
former un intervalle harmonique de septième (mineure, majeure ou
diminuée) avec la fondamentale. Tous ces accords sont donc
*dissonants*.


** Harmoniques naturelles

Nous allons à présent établir une classification alternative des
accords en nous basant cette fois sur la série des harmoniques
naturelles.


*** Accord parfait majeur

Considérons par exemple le début d’une série d’harmoniques naturelles
de fondamentale /do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Si nous nous arrêtons à la note 6, nous avons :

#+BEGIN_CENTER
do   do   sol   do   mi   sol
#+END_CENTER

Hors doublures, nous obtenons un ensemble de trois notes :

#+BEGIN_CENTER
do   mi   sol
#+END_CENTER

qui n’est rien d’autre qu’un accord parfait majeur.

L’ *accord parfait majeur* est donc un accord consonant, autant du
point de ses intervalles harmoniques internes que de la série des
harmoniques naturelles.


*** Septième de dominante

Considérons par exemple le début d’une série d’harmoniques naturelles
de fondamentale /sol/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | sol | sol | ré | sol | si | ré | fa | sol | la | si | do^{#} | ré | =...= |
| /Numéros/ | : |   1 |   2 |  3 |   4 |  5 |  6 |  7 |   8 |  9 | 10 |     11 | 12 | =...= |

Si nous nous arrêtons à la note 7, nous avons :

#+BEGIN_CENTER
sol   sol   ré   sol   si   ré   fa
#+END_CENTER

Hors doublures, nous obtenons un ensemble de quatre notes :

#+BEGIN_CENTER
sol   si   ré   fa
#+END_CENTER

L’accord de septième de dominante se trouve donc dans une situation
paradoxale. Comme tous les accords de quatres notes à base de tierces,
sa note de septième forme une dissonance avec sa fondamentale. D’un
autre coté, nous voyons apparaître un accord de *septième de
dominante* parmi les premières harmoniques naturelles. Cet accord
figure donc parmi les plus *équilibrés* des accords dissonants. Il y a
donc là une forme d’ *équilibre dynamique*, ce qui explique son rôle
important.


** Sensible

La présence d’une sensible dans un accord provoque une tension qui
pousse cet accord à se résoudre sur un autre accord.

Une sensible, ou une sensible auxiliaire :

  - rend instable un accord qui ne comporte pourtant aucune dissonance constitutive
  - augmente l’instabilité d’un accord dissonant

#+BEGIN_CENTER
⁂
#+END_CENTER

Les accords suivants contiennent une ou plusieurs tensions
mélodiques :

  - accords de dominante
  - accords de dominante auxiliaire avec sensible(s) auxiliaire(s)
  - accords napolitains
  - =...=


** Tableau récapitulatif

| Stabilité                         | Accords               |
|-----------------------------------+-----------------------|
| Stables, Consonants               | Parfait majeur        |
|                                   | Parfait mineur        |
| Équilibre dynamique               | Septième de dominante |
| Instables, Dissonants, Équilibrés | Tous les autres       |


* Dynamique du rythme

#+TOC: headlines 1 local


** Introduction

Le rythmes les plus stables sont les *rythmes réguliers* :

  - *rapides*, avec au moins une note par temps
  - *lents*, avec de longues notes continues

Tous les autres rythmes correspondent à des tensions qui peuvent se
résoudre sur l’une ou l’autre de ces configurations. Il va de soi que
les rythmes lents sont plutôt réservés à la fin d’une phrase et les
rythmes rapides au coeur d’un mouvement.


** Mesures

Une mesure irrégulière constitue une tension par rapport à une mesure
régulière proche.


** Fluidité

Un rythme sec produit une tension par rapport à un rythme fluide qui
lui est proche. Par exemple, la suite :

#+ATTR_HTML: :class plat
| C cs C | cs N N |

produira une tension puis une détente, et la suite :

#+ATTR_HTML: :class plat
| C cs N | C cs N | =...= |

un cycle de tension et de détente.


** Syncopes

Le schéma générique d’une syncope applique la structure générique de
tension et résolution. En voici un exemple :

  - *Préparation* : rythme régulier, à raison d’une note par temps

  - *Tension* : on gomme la première note de la mesure suivante en la
    remplaçant par la prolongation de la note précédente

  - *Résolution* : la mélodie reprend le rythme régulier précédent, à
    raison d’une note par temps

Toutes les variations partant de ce cas d’école sont bien entendu
possibles. La phase de préparation est bien entendu optionnelle.

Voici des exemples de réalisation où la mesure compte deux temps d’une
noire chacun :

|         | Préparation | Tension     | Résolution |
|---------+-------------+-------------+------------|
| Syncope | N N         | N N‿N N     | N N        |
| Syncopé | N N         | N N‿N N‿N N | N N        |


** Contretemps

On peut considérer qu’une syncope est un rythme fluide et que le
contretemps est le rythme sec associé. Par conséquent, le contretemps
offre une tension rythmique encore plus importante que celle de la
syncope. On peut imaginer un prototype de tension — relaxation :

  - Rythme régulier de préparation, une note par temps

  - Tension : syncope

  - Tension accrue : contretemps associé

  - Légère détente : retour à la syncope

  - Détente finale : retour au rythme régulier

chaque étape étant optionnelle.
