
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 03 : Luth
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Introduction

#+ATTR_HTML: :class lettrine
Il est possible de développer une analogie très poussée entre le monde
du théâtre et celui de la musique. Ainsi, une belle mélodie jouée en
solo, procurant un sentiment d’intimité et de simplicité, est
comparable à un personnage qui s’adonne au monologue, au soliloque ou
à l’aparté. Lorsque plusieurs protagonistes entament un dialogue,
plusieurs mélodies sont jouées simultanément, faisant ainsi naître une
polyphonie. Ici, le décor harmonique est dynamique, et chaque ligne
mélodique contribue à le faire évoluer. Certaines voix musicales
prennent tour à tour un rôle plus actif dans la causerie. Tantôt en
concorde, tantôt en discorde, toute la troupe bouillonne de thèmes et
d’idées qui se baladent de main en main, tissant ainsi la trame de
l’histoire. Lorsque les Muses apparaîssent au centre de cette table
ronde, une magie collective émerge des voix, dans toute la splendeur
de sa virtuosité collective. Fidèles à cette riche tradition, nous
introduisons les concepts qui permettent d’explorer la dualité, ce
fragile mais féerique équilibre entre les dimensions mélodiques et
harmoniques d’une polyphonie.


* Mélodie & Harmonie

#+TOC: headlines 1 local

** Introduction

Une *mélodie* est un ensemble de notes jouées *successivement*.

Une *harmonie* est un ensemble de notes jouées *simultanément*.


** Intervalle mélodique

Un *intervalle mélodique* est un intervalle dont les deux notes sont
jouées successivement.

Le cas échéant, on qualifiera un intervalle particulier de mélodique.

Par exemple, une quarte mélodique est un intervalle mélodique de
quarte.


*** Unisson

Un *unisson mélodique* consiste à répéter la même note.

Si les deux notes de l’unisson sont connectées par une liaison
rythmique, on entend une seule note, de durée plus longue. Dans le cas
contraire, la note est jouée deux fois.


** Intervalle harmonique

Un *intervalle harmonique* est un intervalle dont les deux notes sont
jouées simultanément.

Le cas échéant, on qualifiera un intervalle particulier d’harmonique.

Par exemple, une quinte harmonique est un intervalle harmonique de
quinte.


*** Plaqué

On dit qu’un intervalle harmonique est *plaqué* ou *frappé* si les
deux notes sont entamées simultanément.


*** Unisson

Un *unisson harmonique* consiste à faire jouer la même note
simultanément par deux instruments différents.


** Sensible

Une *sensible* est une note située à une distance d’un demi-ton de la
tonique, ce qui crée une attraction mélodique vers cette dernière.

La tonique correspondant au degré 1, les notes qui l’entourent sont
situées aux degrés 2 et 7.

Lorsque le degré 7 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible inférieure*.

Lorsque le degré 2 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible supérieure*.

Exemples :

  - si la tonique est un /do/, le /si/ sera une sensible inférieure

  - si la tonique est un /mi/, le /fa/ sera une sensible supérieure


** Étendue

Un *ambitus* est une plage de notes limitée par la note la plus aiguë
et la note la plus grave d’une mélodie.

En musique vocale, une *tessiture* est l’étendue des notes qu’un
interprète est capable de chanter sans forcer sa voix. Les voici,
classées du plus aigu au plus grave :

  - soprano
  - mezzo-soprano
  - alto
  - contralto, haute-contre ou contre-ténor (avec nuances)
  - ténor
  - baryton
  - basse

Un *registre* est une plage de notes limitée dans l’aigu et le grave.
Ce mot regroupe plusieurs notions connexes. Ainsi :

  - un registre peut être grave, moyen, haut ou aigu suivant la
    position relative des notes qu’il contient

  - un registre peut correspondre à l’aspect plus ou moins aigu ou
    grave d’une mélodie

    + on peut comparer plusieurs mélodies d’après leurs registres
      relatifs

  - le registre d’un instrument est l’étendue des notes qu’il est
    possible de jouer sur cet instrument

  - un orgue possède plusieurs jeux de tuyaux aux timbres distincts,
    un peu comme un orchestre où chaque jeu correspond à un
    instrument. Un registre désigne alors une commande permettant
    d’activer un de ces jeux.


** Motif

Un *motif* est un fragment de mélodie jouée à un rythme
donné. Un motif résulte donc de l’association d’une structure
mélodique avec une structure rythmique.

Exemple de motif :

#+ATTR_HTML: :class plat
| mélodie | : | do | ré | sol | fa |
| rythme  | : | B  | B  | N   | N  |


*** Thème

Un *thème* est un motif élaboré et reconnaissable, ce qui permet de le
repérer aisément à chaque fois qu’il est joué.


** Anacrouse

Lorsque la première mesure d’un morceau est incomplète, on la nomme
*anacrouse*. Cette première mesure est alors constituée de notes
précédent le premier temps fort de la musique, ce qui provoque un
décalage entre la mélodie et le rythme.

Notons que l’anacrouse n’est pas obligatoire : la mélodie peut
démarrer au début d’une mesure.


* Mouvements mélodiques

#+TOC: headlines 1 local


** Introduction

Les *mouvements mélodiques* analysent les intervalles
d’une mélodie.


** Direction

Un intervalle mélodique est dit :

  - *ascendant* si la deuxième note est plus aiguë que la première

  - *descendant* si la deuxième note est plus grave que la première


** Mouvement constant & variable

Un *mouvement constant* est un unisson mélodique : la même note est
répétée.

Tous les autres intervalles mélodiques sont des *mouvements
variables*.


** Mouvement conjoint

Un mouvement *conjoint* est un intervalle mélodique d’unisson ou de
seconde. Rentrent donc dans cette catégorie :

  1. l’unisson mélodique, ou répétition d’une même note
  2. la seconde mineure mélodique
  3. la seconde majeure mélodique

En tenant compte du caractère ascendant ou descendant, on obtient les
intervalles conjoints suivant :

  - la seconde majeure ascendante
  - la seconde mineure ascendante
  - l’unisson
  - la seconde mineure descendante
  - la seconde majeure descendante


*** Constant ou variable

On distingue :

  - le *mouvement conjoint constant*, ou mouvement constant, identique
    à l’unisson mélodique

  - le *mouvement conjoint variable* qui procède par seconde majeure
    ou mineure


*** Notes conjointes

Deux notes sont dites conjointes si elles forment un intervalle
d’unisson ou de seconde.


*** Continuité

Une mélodie qui ne présente que des mouvements conjoints est dite
*continue*. Une mélodie constituée d’une majorité de mouvements
conjoints est dite majoritairement continue.


** Mouvement disjoint

Un mouvement *disjoint* est un intervalle mélodique non conjoint.
Rentrent donc dans cette catégorie :

  - les tierces
  - les quartes
  - les quintes
  - les sixtes
  - les septièmes
  - les octaves
  - les neuvièmes
  - =...=

et ce quel que soit leur qualificatif : juste, majeur, mineur,
augmenté, diminué, sur-augmenté ou sur-diminué.


*** Notes disjointes

Deux notes sont dites disjointes si elles ne sont pas conjointes.
Autrement dit, elles forment un intervalle d’au moins une tierce.


*** Discontinuité

Un mouvement disjoint provoque un *saut*, une *discontinuité* dans une
mélodie.


** Mouvement chromatique

Un mouvement *chromatique* est constitué de trois notes. La première
fait partie de la gamme en cours (tonique et mode), la seconde est altérée
d’un demi-ton et la troisième poursuit le mouvement d’un demi-ton dans
la même direction afin d’atteindre la note voisine de la gamme. Les
notes initiale et finale doivent donc être séparées d’un ton entier.

Exemple de mouvement chromatique ascendant dans la gamme de /do ionien/ :

#+begin_center
ré ré^{#} mi
#+end_center

Exemple de mouvement chromatique descendant :

#+begin_center
la la^b sol
#+end_center


* Intervalles harmoniques

#+TOC: headlines 1 local

** Introduction

La classification des intervalles harmoniques s’appuie sur la série
des harmoniques naturelles.

Les premiers intervalles rencontrés dans la série procurent une
sensation de douceur, d’équilibre, de plénitude. Ils sont qualifiés de
*consonants*.

Les intervalles suivants sont qualifiés de *dissonants*.

Analysons par exemple le début d’une série d’harmoniques naturelles
de note fondamentale /do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Nous réduisons la série aux six premières notes, auxquelles on
ajoute les redoublements d’octave :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | do |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |  8 |

et nous considérons comme consonants tous les intervalles harmoniques
qui y sont présents :

| Intervalle       | Note I | Note II |
| harmonique       |        |         |
|------------------+--------+---------|
| unisson          |      1 |       1 |
| octave           |      1 |       2 |
| quinte           |      2 |       3 |
| quarte           |      3 |       4 |
| tierce majeure   |      4 |       5 |
| tierce mineure   |      5 |       6 |
| sixte majeure    |      3 |       5 |
| sixte mineure    |      5 |       8 |

Les autres intervalles de la série complète sont dissonants :

| Intervalle       | Note I | Note II |
| harmonique       |        |         |
|------------------+--------+---------|
| septième mineure |      4 |       7 |
| seconde majeure  |      8 |       9 |
| quarte augmentée |      8 |      11 |

Les autres intervalles sont également considérés comme dissonants :

  - septième majeure
  - seconde mineure
  - intervalles augmentés
  - intervalles diminués
  - intervalles sur-augmentés
  - intervalles sur-diminués


** Consonances

Les intervalles consonants se subdivisent en consonances parfaites,
intermédiaires et imparfaites en fonction de leur ordre d’apparition
dans la série des harmoniques naturelles.

Il est important de souligner que les termes « consonance
intermédiaire » et « consonance imparfaite » ne signifient pas que ces
intervalles sonnent moins bien que les consonances parfaites. Ces
dernières produisent des sons plus épurés, car leurs notes se
ressemblent plus, tandis que les autres consonances produisent un son
plus riche.

Le tableau suivant donne la liste des intervalles consonants :

| Consonances                | Intervalles harmoniques |
|----------------------------+-------------------------|
| consonances parfaites      | unisson                 |
|                            | octave                  |
|                            | quinte                  |
|----------------------------+-------------------------|
| consonances intermédiaires | quarte                  |
|----------------------------+-------------------------|
| consonances imparfaites    | tierce majeure          |
|                            | tierce mineure          |
|                            | sixte majeure           |
|                            | sixte mineure           |


** Dissonances

Les intervalles dissonants sont ceux qui ne sont pas consonants. Ils
se subdivisent en dissonances imparfaites, intermédiaires et
parfaites.

Hormis la quarte augmentée, qui est dissonante par nature, les
intervalles augmentés ou diminués se forment en ajoutant ou supprimant
des altérations, ce qui fait sortir une ou plusieurs notes de la gamme
en cours. Cette situation produit une instabilité qui se résout par un
retour vers une note de la gamme. Pour cette raison, on classe
également les intervalles augmentés et diminués parmi les intervalles
dissonants.

Le tableau suivant donne la liste des intervalles dissonants :

| Dissonances                | Intervalles harmoniques   |
|----------------------------+---------------------------|
| dissonances imparfaites    | septième mineure          |
|                            | seconde majeure           |
|----------------------------+---------------------------|
| dissonances intermédiaires | quarte augmentée          |
|----------------------------+---------------------------|
| dissonances parfaites      | septième majeure          |
|                            | seconde mineure           |
|----------------------------+---------------------------|
| autres                     | intervalles diminués      |
|                            | intervalles augmentés     |
|                            | intervalles sur-augmentés |
|                            | intervalles sur-diminués  |


** Redoublements

Considérons les notes consonantes d’une série d’harmoniques naturelles
de fondamentale /do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | do |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |  8 |

Cette série est consonante, ainsi que tous les intervalles qui y sont
présents.

Si nous examinons les intervalles supérieurs à l’octave qui
apparaissent, nous obtenons :

| Intervalle harmonique | Note I | Note II |
|-----------------------+--------+---------|
| douzième              |      1 |       3 |
| quinzième             |      1 |       4 |
| dixième majeure       |      2 |       5 |

Les intervalles simplifiés s’écrivent :

| Intervalle      | Simplifié      |
|-----------------+----------------|
| dixième majeure | tierce majeure |
| douzième        | quinte         |
| quinzième       | octave         |

Les redoublements de la tierce majeure, de la quinte et de l’octave
sont donc également consonants. Il ne nous manque que la quarte et la
tierce mineure pour compléter la liste des consonances.

Nous généralisons ce résultat en considérant que :

  - le redoublement d’un intervalle consonant est également consonant
  - le redoublement d’un intervalle dissonant est également dissonant

Ce qui nous mène au principe d’équivalence suivant : ajouter ou
retirer une ou plusieurs octaves à un intervalle harmonique ne modifie
pas son caractère consonant ou dissonant.


** Renversements

Le renversement ne modifie pas le caractère consonant ou dissonant
d’un intervalle harmonique :

|             | Intervalle | Renversement |
|             | harmonique |              |
|-------------+------------+--------------|
| consonances | unisson    | octave       |
|             | octave     | unisson      |
|             | quinte     | quarte       |
|             | tierce     | sixte        |
|             | sixte      | tierce       |
|-------------+------------+--------------|
| dissonances | seconde    | septième     |
|             | septième   | seconde      |
|             | augmenté   | diminué      |
|             | diminué    | augmenté     |


* Polyphonie

#+TOC: headlines 1 local


** Introduction

Une *polyphonie* est une superposition de plusieurs mélodies jouées
simultanément par différents instruments ou groupes d’instruments.
Chacune de ces mélodies est aussi appelée *voix*, *partie*, *ligne* ou
encore *ligne mélodique*.

Attention à ne pas confondre la notion de voix, synonyme de ligne
mélodique, avec la voix humaine, qui peut être considérée comme un
instrument de musique. En tant que ligne mélodique, une voix peut donc
être interprétée par un instrument quelconque : violon, voix humaine,
flûte, etc.


*** Instrument polyphonique

Un instrument polyphonique est un instrument capable de jouer
simultanément plusieurs lignes mélodiques. Les plus célèbres
d’entre-eux sont les instruments à clavier comme le clavecin ou le
piano. L’orgue dispose en plus d’un pédalier, permettant ainsi de
jouer avec les pieds et les mains.

Le luth, la guitare et autres instruments similaires permettent
également de jouer plusieurs notes à la fois.


*** Plusieurs instruments par voix

Il peut arriver que plusieurs chanteurs ou instruments interprètent la
même mélodie, du début à la fin de la partition. Dans ce cas, on
considère qu’il s’agit d’une seule et même voix de la polyphonie.


** Horizontal & Vertical

Une *mélodie* correspond à la dimension *horizontale* d’une
polyphonie, à savoir les notes qui sont jouées consécutivement sur une
voix.

Une *harmonie* correspond à la dimension *verticale* d’une polyphonie,
à savoir les notes qui sont jouées à un instant donné sur les voix.

Dans une polyphonie, deux notes quelconques peuvent être jouées :

  - consécutivement (sur la même voix ou sur deux voix différentes)
  - simultanément (sur deux voix différentes)
  - avec simultanéité partielle
    + les deux débutent au même moment, l’une s’arrête avant l’autre
    + les deux finissent au même moment, l’une débute avant l’autre
    + l’une commence et finit avant l’autre
    + l’une débute avant et finit après l’autre
    + l’une commence avant et finit après l’autre


** Portées


*** Voix

Une portée contient en général une ou deux voix.

Lorsque deux voix sont présentes, les hampes des notes :

  - de la voix supérieure sont orientées vers le haut
  - de la voix inférieure sont orientées vers le bas


*** Système

Un système est un groupe de portées jouées simultanément par un ou
plusieurs instruments.


*** Partition

Une partition est un ensemble de portées, ou de systèmes de portées,
contenant les notes et les indications grâce auxquelles les musiciens
vont pouvoir jouer une oeuvre musicale.


** Notation

Dans ce traité, nous représentons une polyphonie par une
*superposition* de voix. Il s’agit en quelque sorte d’un *tableau* où
chaque voix occupe une ligne. Les voix sont disposées de la plus aiguë
à la plus grave, de haut en bas du tableau. Une voix située au-dessus
d’une autre est donc normalement plus aiguë. Précisons que chaque
colonne du tableau contient des notes jouées simultanément.

Voici un exemple :

#+ATTR_HTML: :class plat
| Va    | :     | a1    | a2    | a3    | a4    | =...= |
| Vb    | :     | b1    | b2    | b3    | b4    | =...= |
| Vc    | :     | c1    | c2    | c3    | c4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |

où :

  - Va, Vb, Vc, =...= sont les noms donnés à chacune des voix

  - a1, a2, a3, a4 ; b1, b2, b3, b4 ; c1, c2, c3, c4, =...= sont les notes jouées

Les notes a1, a2, a3, a4 sont donc jouées consécutivement tandis que
les notes a1, b1, c1 sont jouées simultanément.


*** Thèmes

On peut aussi représenter la musique comme une suite de thèmes
mélodiques, chacun étant constitué de plusieurs notes. Dans ce cas, on
symbolise chaque thème par une lettre majuscule et on représente la
polyphonie par :

#+ATTR_HTML: :class plat
| Va    | :     | A1    | A2    | A3    | A4    | =...= |
| Vb    | :     | B1    | B2    | B3    | B4    | =...= |
| Vc    | :     | C1    | C2    | C3    | C4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |

où :

  - Va, Vb, Vc, =...= sont les noms donnés à chacune des voix

  - A1, A2, A3, A4 ; B1, B2, B3, B4 ; C1, C2, C3, C4, =...= sont les
    noms donnés aux thèmes

Les thèmes A1, A2, A3, A4 sont donc joués consécutivement tandis que
les thèmes A1, B1, C1 sont joués simultanément.


*** Silences

Une voix momentanément silencieuse est représentée par un tiret, comme
la voix /V/ dans :

#+ATTR_HTML: :class plat
| V     | :     | A1    | —     | —     | A4    | =...= |
| W     | :     | B1    | B2    | B3    | B4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |


*** Case vide

Une case vide dans le tableau polyphonique signifie que le contenu est
indéterminé : note, motif mélodique ou silence, suivant les cas.

Le contenu des cases vides n’a en fait pas d’importance dans la
compréhension ce que l’on souhaite illustrer par le tableau
polyphonique.


** Voix


*** Basse & Soprano

La voix la plus grave d’une polyphonie est nommée *basse*.

La voix la plus aiguë d’une polyphonie est nommée *soprano*.


*** Extrêmes & Internes

Le soprano et la basse sont les *voix extrêmes* d’une polyphonie.

Toutes les autres voix sont dites *internes*.


*** Importance

Au niveau harmonique :

  - la basse est la voix la plus importante
  - le soprano est la deuxième voix la plus importante

Au niveau mélodique, la situation est inversée :

  - le soprano est la voix la plus importante
  - la basse est la deuxième voix la plus importante

Les autres voix ont une importance relative moins élevée. On a donc,
par ordre décroissant d’importance :

  - les voix extrêmes : basse & soprano
  - les voix internes


*** Distinction

À un instant donné, les voix d’une polyphonie se distinguent en
général par :

  - le registre : une voix est plus aiguë ou plus grave qu’une l’autre
  - le rythme : une voix est plus rapide ou plus lente qu’une autre
  - le timbre : les voix sont jouées par des instruments de familles
    différentes, aux sons différenciables


*** Ajout et suppression

Le nombre de voix ne reste pas toujours constant tout le long d’une
pièce musicale. Une ou plusieurs voix peuvent être ajoutées ou
retirées. Dans le cas d’un ajout, on peut toujours considérer qu’une
voix préalablement silencieuse devient active. Dans le cas d’un
retrait, on peut considérer qu’une voix préalablement active devient
silencieuse.


**** Scission

La *scission* est un cas particulier d’ajout où la nouvelle voix
semble issue d’une ancienne comme une branche d’un arbre. Cet effet
est souvent obtenu en utilisant un mouvement pseudo-conjoint (à
l’octave près) entre les voix concernées. Exemple :

#+ATTR_HTML: :class plat
| V | : | do | ré |
| W | : | —  | si |

ou encore :

#+ATTR_HTML: :class plat
| V | : | —  | sol |
| W | : | fa | mi  |


**** Fusion

La *fusion* est un cas particulier de retrait, où l’ancienne voix
semble se fondre dans une autre avant de se taire. Cet effet est
souvent obtenu en utilisant un mouvement pseudo-conjoint entre les
voix concernées. Exemple :

#+ATTR_HTML: :class plat
| V | : | ré | do |
| W | : | si | —  |

ou encore :

#+ATTR_HTML: :class plat
| V | : | sol | —  |
| W | : | mi  | fa |


*** Groupes

Les voix d’une polyphonie peuvent être subdivisées en plusieurs
groupes. Les voix d’un même groupe possèdent généralement des
caractéristiques musicales communes, afin de les différencier des
autres voix. On parle alors de *groupe de voix*, de *plan sonore* ou
encore de *strate*.

Les groupes de voix ne sont pas figés :

  - chaque voix peut changer de groupe à tout moment
  - de nouveaux groupes peuvent être créés, d’anciens supprimés


**** Structure

Dans une *structure stratifiée*, chaque groupe de voix dispose de ses
propres motifs musicaux.

Dans une *structure imitative*, chaque groupe de voix reprend et varie
les thèmes des autres groupes.


** Ensembles

#+TOC: headlines 1 local

*** Introduction

En musique vocale, les voix de la polyphonie sont désignées d’après
les tessitures des chanteuses ou chanteurs qui les interprètent.

Dans ce traité, nous nous inspirons des tessitures pour nommer les
lignes mélodiques de n’importe quel ensemble, qu’il soit vocal,
instrumental ou mixte. Il ne s’agit que d’une convention : une ligne
mélodique particulière ne respecte pas forcément les caractéristiques
de la tessiture qui lui a donné son nom.


**** Aigu & grave

Le classement des voix de la plus aiguë à la plus grave n’est pas
absolu. Le fait de placer une voix /X/ au-dessus d’une voix /Y/
signifie simplement que la voix /X/ sera plus aiguê que /Y/ la plupart
du temps. Il n’est pas impossible que /X/ et /Y/ se croisent à un
instant donné du déroulement musical, /X/ devenant alors
temporairement plus grave que /Y/.


*** Duo

Un *duo* est une polyphonie à deux voix. Ces voix se nomment par
convention :

  - soprano
  - basse

de la plus aiguë à la plus grave. J’utilise comme abréviations : *S*
pour soprano et *B* pour basse, ce qui nous donne des tableaux de
cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| B | : | =...= |


*** Trio

Un *trio* est une polyphonie à trois voix. Ces voix se nomment par
convention :

  - soprano
  - alto
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le duo, avec en prime *A* pour l’alto, ce qui nous donne des
tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| B | : | =...= |


*** Quatuor

Un *quatuor* (aussi appelé *quartet*) est une polyphonie à quatre
voix. Ces voix se nomment par convention :

  - soprano
  - alto
  - ténor
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le trio, avec en prime *T* pour le ténor, ce qui nous donne des
tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| T | : | =...= |
| B | : | =...= |


*** Quintette

Un *quintette* (parfois orthographié *quintet*) est une polyphonie à
cinq voix. Ces voix se nomment par convention :

  - soprano
  - mezzo-soprano
  - alto
  - ténor
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le quatuor, avec en prime *M* pour le mezzo-soprano, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| M | : | =...= |
| A | : | =...= |
| T | : | =...= |
| B | : | =...= |


*** Sextuor

Un *sextuor* (aussi appélé *sextet*, *sextette*) est une polyphonie à
six voix. Ces voix se nomment par convention :

  - soprano
  - mezzo-soprano
  - alto
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le quintettte, avec en prime *Y* pour le baryton, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| M | : | =...= |
| A | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |


*** Septuor

Un *septuor* (aussi appéles *septet*, *septette*) est une polyphonie à
sept voix. Ces voix se nomment par convention :

  - soprano
  - mezzo-soprano
  - alto
  - haute-contre
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le sextuor, avec en prime *C* pour le haute-contre, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| M | : | =...= |
| A | : | =...= |
| C | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |

/Remarque/ : la voix de haute-contre est aussi appelée, avec des
nuances, *contralto* ou *contreténor*.


*** Formation générique

Au-dessus de sept voix, on à la nomenclature :

  - octuor, octet : 8 voix
  - nonet, nonette : 9 voix
  - dixtuor : 10 voix

On représente un ensemble contenant un nombre quelconque de voix par :

#+ATTR_HTML: :class plat
|     0 | : | =...= |
|     1 | : | =...= |
|     2 | : | =...= |
|     3 | : | =...= |
|     4 | : | =...= |
| =...= | : | =...= |
|   /M/ | : | =...= |

ou, si l’on souhaite faire ressortir les voix extrêmes *S* et *B* :

#+ATTR_HTML: :class plat
|     S | : | =...= |
|     1 | : | =...= |
|     2 | : | =...= |
|     3 | : | =...= |
|     4 | : | =...= |
| =...= | : | =...= |
|   /N/ | : | =...= |
|     B | : | =...= |


* Accords

#+TOC: headlines 1 local


** Introduction

Un *accord* est un ensemble de notes qui sert pendant un certain
laps de temps de fondation au déroulement musical.

Cela ne signifie pas que toutes les notes jouées appartiennent à
l’accord, mais que la musique est élaborée à partir des notes qui le
constituent.

L’ajout de notes étrangères à l’accord se fait en général pour des
raisons de liaisons mélodiques entre les notes.


** Polyvalence

Les notes d’un accord peuvent être disposées suivant des
configurations très diverses. Il existe bien entendu des cas
extrêmes :

  - l’accord purement harmonique, où les notes sont jouées
    simultanément

  - l’accord purement mélodique, où les notes sont jouées les unes
    après les autres

mais la réalité est souvent plus complexe. La plupart du temps, la
musique explore les deux aspects, superposant et alignant les notes
d’un accord tout au long de son règne. Un accord est donc une *entité
abstraite* dont les *réalisations* constituent le plus souvent un
*hybride* d’harmonie et de mélodie.


*** Jargon

Lorsque les notes d’un accord sont jouées simultanément, on parle d’
*accord frappé* ou encore d’ *accord plaqué*.

Lorsque les notes d’un accord mélodique sont jouées consécutivement,
on parle d’ *arpège*.

Enfin, on parle d’ *accumulation* lorsque les notes de l’accord sont
entamées consécutivement mais que chacune d’elle est maintenue jusqu’à
la fin de l’accord. Par exemple, avec l’accord /do mi sol/, on
commence par jouer le /do/, ensuite le /mi/ vient s’ajouter et on
entend simultanément les notes /do mi/, et finalement le /sol/ vient
s’ajouter et on entend simultanément les notes /do mi sol/.


** Octave

C’est avant tout l’ordre des notes, de la plus grave à la plus aiguë,
qui importe en théorie des accords. Leur octave précise n’est pas
prise en compte. Les notes et intervalles doivent donc s’entendre à
l’octave près.

Ce constat nous permet d’employer une notation allégée. Par
convention, nous représentons un accord par une suite de notes
croissantes en hauteur, ce qui nous permet d’omettre leurs octaves.
Ainsi, dans l’accord :

#+begin_center
sol si sol
#+end_center

le second /sol/ doit être plus aigu que le /si/, lui-même strictement
plus aigu que le premier /sol/. En supposant que nous partons de
l’octave 1, cette notation est donc équivalente à :

#+begin_center
sol^1 si^1 sol^2
#+end_center

On peut aussi monter plus haut dans les octaves :

#+ATTR_HTML: :class plat
| sol^1 si^1 sol^3 |
| sol^1 si^2 sol^3 |
| sol^1 si^2 sol^4 |
| =...=            |

mais cela ne change rien en théorie des accords.


** État canonique

Un accord est défini par une suite de notes disposées dans un ordre de
référence appelé *état canonique*. La note la plus grave de l’état
canonique est appelée *fondamentale*.

Toutes les notes doivent être distinctes les unes des autres.

L’état canonique permet également de nommer les notes de l’accord
d’après l’intervalle qui les sépare de la fondamentale.

Par exemple, dans l’accord défini par l’état canonique :

#+begin_center
do   mi   sol   si   ré   fa   la
#+end_center

les notes reçoivent des noms repris dans le tableau ci-dessous :

| Notes | Noms         | Abréviations |
|-------+--------------+--------------|
| do    | fondamentale |         1ale |
| mi    | tierce       |          3ce |
| sol   | quinte       |          5te |
| si    | septième     |           7e |
| ré    | neuvième     |           9e |
| fa    | onzième      |          11e |
| la    | treizième    |          13e |

/Remarque/ : ne pas confondre le concept de /note/ fondamentale d’un
accord avec celui de /fréquence/ fondamentale d’un son.


** Degré

Le *degré* d’un accord est simplement le degré de sa fondamentale.

Par exemple :

  - un accord de degré 1, ou accord de tonique, est un accord dont la
    fondamentale est le degré 1 de la gamme

  - un accord de degré 5, ou accord de dominante, est un accord dont
    la fondamentale est le degré 5 de la gamme


** Empilement

L’état canonique de la plupart des accords est construit en empilant
des notes séparées par un intervalle constant donné.


*** Harmoniques naturelles

Considérons une suite d’harmiques naturelles de fondamentale /do/ :

#+ATTR_HTML: :class plat
| do | do | sol | do | mi | sol | si^b  | do | ré | =...= |

Abstraction faite :

  - des octaves
  - des notes apparaissant en double dans des octaves différentes

il nous reste :

#+begin_center
do mi sol si^b ré
#+end_center

La suite des harmoniques naturelles semble donc nous diriger vers des
accords construits par empilement de tierces majeures ou mineures.
Ceci explique la prédominance des accords à base de tierces.


*** Tierces

Les accords construits par empilement de tierces sont de loin les plus
fréquents, parce qu’ils sont intimement liés aux harmoniques
naturelles et sonnent particulièrement bien. Notons qu’un accord à
base de tierces peut aussi bien contenir des tierces majeures que
mineures. Exemples d’accords à base de tierces :

#+ATTR_HTML: :class plat
| ré | fa | la |    |    |     |    |
| ré | fa | la | do |    |     |    |
| ré | fa | la | do | mi |     |    |
| ré | fa | la | do | mi | sol |    |
| ré | fa | la | do | mi | sol | si |


*** Quintes

Les accords construits par empilement de quintes sont considérés comme
des altérations d’accords à base de tierces. On les utilise pour
donner une coloration alternative à la musique, ou encore pour
soutenir une mélodie issue d’une gamme pentaphonique (comme on en
rencontre en blues et en jazz). Exemples d’accords à base de quintes :

#+ATTR_HTML: :class plat
| do | sol |    |    |    |    |    |
| do | sol | ré |    |    |    |    |
| do | sol | ré | la |    |    |    |
| do | sol | ré | la | mi |    |    |
| do | sol | ré | la | mi | si |    |
| do | sol | ré | la | mi | si | fa |

Si la théorie classique ne reconnaît que les accords construits par
empilement de tierces, Jean-Sébastien Bach n’a pas attendu l’avènement
du jazz pour utiliser des accords formés à base de quintes : on en
rencontre dans le prélude le plus célèbre du Clavier bien tempéré.


** Disposition

#+TOC: headlines 1 local

*** Introduction

On nomme *disposition* d’un accord un agencement particulier de ses
notes intrinsèques. De nombreux événements peuvent modifier la
disposition : permutation, renversement, doublure, suppression, etc.


*** Permutations

Une *permutation* consiste à modifier l’ordre des notes d’un accord.

On dit alors que l’accord est *permuté*.

Exemples de permutations de l’accord dont l’état canonique est
/do mi sol/ :

  - do sol mi
  - mi do sol
  - mi sol do
  - sol do mi
  - sol mi do


*** Basse

La note la plus grave d’une permutation quelconque d’un accord est
appelée la *basse* de l’accord ainsi disposé. On dit aussi de cette
note qu’elle est mise *à la basse*.

Dans cet exemple, le /sol/ est à la basse :

#+begin_center
sol do mi
#+end_center

Dans cet exemple, le /do/ est à la basse :

#+begin_center
do sol mi
#+end_center


*** Octave

Une note de l’accord peut changer d’octave. L’intervalle de cette note
dans la disposition d’un accord peut donc étre égal :

  - à l’intervalle /I/ de la disposition canonique
  - à l’intervalle /I/ + un nombre entier d’octaves/
  - à l’intervalle /I/ - un nombre entier d’octaves/

Les cas particuliers les plus importants sont :

  - /I/
  - le renversement de /I/
  - le redoublement de /I/

Prenons comme exemple l’accord dont l’état canonique est /sol si ré
fa/. La 7e, le /fa/, peut être disposée comme septième ou quatorzième
mineure au-dessus de la basse :

#+ATTR_HTML: :class plat
| S | : | fa  |
| B | : | sol |

ou comme seconde majeure sous la basse :

#+ATTR_HTML: :class plat
| S | : | sol |
| B | : | fa  |

On peut bien sûr continuer à monter ou descendre dans les octaves.


*** État fondamental

On dit qu’un accord est dans son *état fondamental* lorsque la
fondamentale est à la basse.

/Remarque/ : si une permutation place la fondamentale à la basse,
l’accord est toujours considéré comme étant dans son état fondamental.

Considérons par exemple l’accord dont l’état canonique est
/do mi sol/. Il existe plusieurs variantes de son état fondamental :

  - état canonique : do mi sol
  - permutation avec fondamentale à la basse : do sol mi


*** Renversements

Lorsque les notes d’un accord sont permutées, il arrive que la note
mise à la basse ne soit pas la fondamentale. On dit alors que l’accord
est *renversé*.

Si c’est la deuxième note la plus grave de l’état canonique qui est à
la basse, on dit que l’accord est dans un premier *renversement*, ou
qu’il est *renversé* une fois.

Si c’est la troisième note la plus grave de l’état canonique qui est à
la basse, on dit que l’accord est dans un second renversement, ou
qu’il est renversé deux fois.

Si c’est la quatrième note la plus grave de l’état canonique qui est à
la basse, on dit que l’accord est dans un troisième renversement, ou
qu’il est renversé trois fois ; etc.

Considérons par exemple l’accord dont l’état canonique est
/do mi sol/. Ses permutations peuvent se classer comme suit :

  - état fondamental
    + do mi sol
    + do sol mi
  - premier renversement
    * mi sol do
    * mi do sol
  - second renversement
    * sol do mi
    * sol mi do


*** Doublure

Une *doublure* est une note ajoutée à l’accord, identique à l’octave
près à une des notes de l’état canonique. La note originale est alors
dite *doublée* ou *redoublée*. Une doublure peut donc se faire :

  - une ou plusieurs octaves au-dessus de la note originale
  - à l’unisson de la note originale
  - une ou plusieurs octaves en-dessous de la note originale

Par exemple, si on redouble le /mi/ de l’accord /la do mi/, on
obtient :

#+begin_center
la mi do mi
#+end_center

ou une quelconque permutation de cet accord. La note redoublée
correspond souvent :

  - à une note importante que l’on souhaite souligner
  - à la fondamentale
  - à la basse

Quelques précisions :

  - L’ajout d’une doublure ne modifie pas l’état canonique de
    l’accord. Le nombre de notes intrinsèques reste donc inchangé.

  - une même note peut être doublée plusieurs fois, à des octaves
    différentes ou identiques.


*** Suppression

On peut modifier un accord en supprimant une de ses notes.


**** Fondamentale

Pour éviter toute ambiguité, le nombre de renversements est toujours
évalué par rapport à l’ordre des notes dans l’état canonique de
l’accord /au complet/. Donc, si la fondamentale de :

#+begin_center
do mi sol si
#+end_center

est supprimée, la disposition suivante :

#+begin_center
mi sol si
#+end_center

est assimilée à un premier renversement, puisque c’est le /mi/,
deuxième note de l’état canonique, qui est à la basse. La disposition
suivante :

#+begin_center
sol si mi
#+end_center

sera dans un second renversement et celle-ci  :

#+begin_center
si mi sol
#+end_center

dans un troisième.

Une conséquence importante de cette convention est qu’un accord privé
de sa fondamentale est toujours renversé.


*** Harmoniques naturelles

Considérons la suite des harmoniques naturelles de fondamentale /do/ :

#+ATTR_HTML: :class plat
| do | do | sol | do | mi | sol | si^b  | do | ré | =...= |

On peut voir cette suite comme un accord placé dans une disposition
particulière : multiples doublures de la fondamentale /do/, doublure
de la quinte /sol/, intervalles larges dans les graves et plus
resserrés dans l’aigu, etc.

On peut s’en inspirer comme disposition pour un accord de fondamentale
/do/.


** Intervalle interne

Un *intervalle interne* d’un accord est un intervalle qui sépare deux
de ses notes.

Les intervalles internes les plus importants sont ceux qui séparent :

  - une note de l’accord avec la fondamentale
  - une note de l’accord avec la basse


** Nombre de notes

On nomme :

  - *dyade* un accord constitué de deux notes
  - *triade* un accord constitué de trois notes
  - *tétrade* un accord constitué de quatre notes
  - *pentade* un accord constitué de cinq notes

/Remarque/ : on parle ici du nombre de notes intrinsèques de l’accord,
sans tenir compte des éventuelles doublures, suppressions ou ajouts.

Le tableau suivant nous donne les abréviations de ces termes :

| Nom     | Abréviation |
|---------+-------------|
| dyade   | 2ade        |
| triade  | 3ade        |
| tétrade | 4ade        |
| pentade | 5ade        |


*** Accord et intervalle

On peut voir un accord comme un empilement d’intervalles.
Réciproquement, on peut voir un intervalle comme un accord constitué
de deux notes.


** Enharmonie

Deux accords son dits *enharmoniques* si ils sont identiques par
enharmonie.

Partons par exemple de l’accord :

#+begin_center
do mi sol^{#}
#+end_center

En utilisant l’enharmonie /sol^{#} = la^b/, on peut le réécrire :

#+begin_center
do mi la^b
#+end_center


* Accords consonants & dissonants

#+TOC: headlines 1 local

** Introduction

Dans le cadre d’un accord :

  - une *note consonante* est une note constitutive qui forme un
    intervalle consonant avec la fondamentale

  - une *note dissonante* est une note constitutive qui forme un
    intervalle dissonant avec la fondamentale

Une note dissonante est également appelée *dissonance constitutive*.

Les accords sont également classés suivant leur caractère consonant ou
dissonant :

  - un *accord consonant* est un accord

    + qui ne contient que des notes consonantes

    + ET dont tous les intervalles internes sont consonants

  - un *accord dissonant* est un accord

    + qui contient au moins une note dissonante

    + OU dont au moins un intervalle interne est dissonant


** Recherche d’accords consonants

#+TOC: headlines 1 local

*** Introduction

Nous allons chercher à former des accords consonants de trois notes ou
plus.

/Remarque/ : les accords de deux notes se résument à des intervalles
harmoniques, dont nous avons déjà étudié le caractère consonant ou
dissonant.


*** Trois notes

Pour que l’accord soit consonant, nous devons éviter les intervalles
internes dissonants : la seconde et son renversement, la septième,
ainsi que leurs redoublements. Nous ne choisirons pas non plus
d’intervalles augmentés ou diminués.

Qui plus est, les notes doivent être distinctes, car la présence d’une
doublure ne nous donnerait pas les trois notes nécessaires pour
établir l’état canonique de l’accord.

Il ne nous reste alors plus que les possibilités suivantes :

  - fondamentale, 3ce, 5te
  - fondamentale, 3ce, 6te
  - fondamentale, 4te, 6te

Toutes les autres accords de trois notes sont dissonants.

En partant de /do/ comme note de basse, nous obtenons la liste des
accords consonants :

  - do mi sol
  - do mi la
  - do fa la

La disposition /do mi la/ peut être considérée comme le premier
renversement de :

#+begin_center
la do mi
#+end_center

La disposition /do fa la/ peut être considérée comme le second
renversement de :

#+begin_center
fa la do
#+end_center

Nous nous retrouvons dans tous les cas avec des accords consonants
formés par empilement de tierces.


*** Quatre notes et plus

Il n’est pas possible de former d’accord consonant de quatre notes ou
plus, car on se retrouve avec au moins un intervalle de septième ou de
seconde.


*** Conclusion

La recherche d’accords consonants nous suggère de construire des
accords de trois notes par empilement de tierces, ce qui est le sujet
du chapitre suivant.


* Accords parfaits

#+TOC: headlines 1 local

** Introduction

Analysons plus en détail les accords de trois notes construits en
empilant deux tierces. Utilisons ce procédé sur chaque note diatonique
et analysons les intervalles obtenus :

| Note | Accord    | Intervalles |           |            |
|      |           | 1ale & 3ce  | 3ce & 5te | 1ale & 5te |
|------+-----------+-------------+-----------+------------|
| do   | do mi sol | 3ce M       | 3ce m     | 5te        |
| ré   | ré fa la  | 3ce m       | 3ce M     | 5te        |
| mi   | mi sol si | 3ce m       | 3ce M     | 5te        |
| fa   | fa la do  | 3ce M       | 3ce m     | 5te        |
| sol  | sol si ré | 3ce M       | 3ce m     | 5te        |
| la   | la do mi  | 3ce m       | 3ce M     | 5te        |
| si   | si ré fa  | 3ce m       | 3ce m     | 5te dim    |

Les accords obtenus génèrent des intervalles de tierce et
de quinte par rapport à la fondamentale. On constate en fait trois
possibilités :

  - tierce majeure puis tierce mineure, le total formant une quinte juste
  - tierce mineure puis tierce majeure, le total formant une quinte juste
  - deux tierces mineures, formant au total une quinte diminuée

Nous avons donc trois catégories d’accords.

L’ *accord parfait majeur* est construit en empilant une tierce
majeure puis une tierce mineure, les deux intervalles totalisant une
quinte juste.

L’ *accord parfait mineur* est construit en empilant une tierce
mineure puis une tierce majeure, les deux intervalles totalisant une
quinte juste.

Ces accords sonnent particulièrement bien.

Exemples d’accords parfaits :

| Accords        | Abréviations | Exemples  |
|----------------+--------------+-----------|
| parfait majeur | P M          | do mi sol |
| parfait mineur | P m          | la do mi  |


L’ *accord de quinte diminuée* est construit en empilant deux tierces
mineures, les deux intervalles totalisant une quinte diminuée.

Exemple :

| Accords         | Abréviations | Exemples |
|-----------------+--------------+----------|
| quinte diminuée | 5te dim      | si ré fa |


** Premier renversement

Au premier renversement, la fondamentale est séparée de la basse par
un intervalle de sixte. Sous cette forme, l’accord parfait est
simplement appelé *accord de sixte*.

On remarque que le renversement d’un accord parfait majeur donne un
intervalle de sixte mineure, et vice versa :

| Accords       | Abréviations | Exemples  |
|---------------+--------------+-----------|
| sixte mineure | 6te m        | mi sol do |
| sixte majeure | 6te M        | do mi la  |


** Second renversement

Au second renversement, les notes de l’accord sont séparées de la
basse par des intervalles de quarte et de sixte. Sous cette forme,
l’accord parfait est simplement appelé *accord de quarte et sixte*.

On remarque que le second renversement d’un accord parfait :

  - majeur donne un intervalle de sixte majeure
  - mineur donne un intervalle de sixte mineure

Le tableau suivant illustre cette propriété :

| Accords                 | Abréviations | Exemples  |
|-------------------------+--------------+-----------|
| quarte et sixte majeure | 4te & 6te M  | sol do mi |
| quarte et sixte mineure | 4te & 6te m  | mi la do  |


** Consonance
:PROPERTIES:
:CUSTOM_ID: section:consonanceAccordsParfaits
:END:

#+TOC: headlines 1 local

*** État fondamental

Les notes d’un accord parfait majeur à l’état fondamental forment des
intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte juste

avec la fondamentale de l’accord. Les intervalles internes sont
également des tierces et des quintes.

L’ *accord parfait majeur* est donc un accord *consonant*.

#+begin_center
⁂
#+end_center

Les notes d’un accord parfait mineur à l’état fondamental forment des
intervalles :

  - d’unisson
  - de tierce mineure
  - de quinte juste

avec la fondamentale de l’accord. Les intervalles internes sont
également des tierces et des quintes.

L’ *accord parfait mineur* est donc un accord *consonant*.

#+begin_center
⁂
#+end_center

Les notes d’un accord de quinte diminuée à l’état fondamental forment
des intervalles :

  - d’unisson
  - de tierce mineure
  - de quinte diminuée

avec la fondamentale de l’accord. L’intervalle de quinte diminuée rend
cet accord dissonant..

L’ *accord de quinte diminuée* est donc un accord *dissonant*.


*** Premier renversement

Les notes d’un accord parfait majeur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce mineure
  - de sixte mineure

avec la fondamentale de l’accord. Les intervalles internes sont
des tierces, des quartes et des sixtes.

L’accord parfait majeur au premier renversement est donc consonant.

#+begin_center
⁂
#+end_center

Les notes d’un accord parfait mineur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce majeure
  - de sixte majeure

avec la fondamentale de l’accord. Les intervalles internes sont
des tierces, des quartes et des sixtes.

L’accord parfait mineur au premier renversement est donc consonant.


*** Second renversement

Les notes d’un accord parfait majeur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte majeure

avec la fondamentale de l’accord. Les intervalles internes sont des
tierces, des quartes et des sixtes.

L’accord parfait majeur au second renversement est donc consonant.

#+begin_center
⁂
#+end_center

Les notes d’un accord parfait mineur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte mineure

avec la fondamentale de l’accord. Les intervalles internes sont des
tierces, des quartes et des sixtes.

L’accord parfait mineur au second renversement est donc consonant.


** Harmoniques naturelles

Considérons le début d’une série d’harmoniques naturelles de
fondamentale /do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Si nous nous arrêtons à la note 6, nous avons :

#+begin_center
do   do   sol   do   mi   sol
#+end_center

Hors doublures, nous obtenons un ensemble de trois notes :

#+begin_center
do   mi   sol
#+end_center

qui n’est rien d’autre qu’un accord parfait majeur. Rien d’étonnant à
ce que cet accord soit considéré comme l’une des clefs de voûte de
l’harmonie.


** Dispositions
:PROPERTIES:
:CUSTOM_ID: section:accordsParfaitsDispositions
:END:

Les dispositions d’accords parfaits inspirées des harmoniques
naturelles sonnent particulièrement bien.

Les exemples qui suivent sont des dispositions de l’accord parfait :

#+begin_center
do mi sol
#+end_center


*** Accord complet

Exemple à sept voix :

#+ATTR_HTML: :class plat
| S | : | do  |
| M | : | sol |
| A | : | mi  |
| C | : | do  |
| T | : | sol |
| Y | : | do  |
| B | : | do  |

Exemple à six voix :

#+ATTR_HTML: :class plat
| S | : | do  |
| M | : | sol |
| A | : | mi  |
| T | : | do  |
| Y | : | sol |
| B | : | do  |

Exemple à cinq voix :

#+ATTR_HTML: :class plat
| S | : | sol |
| M | : | mi  |
| A | : | do  |
| T | : | sol |
| B | : | do  |

Exemple à quatre voix :

#+ATTR_HTML: :class plat
| S | : | mi  |
| A | : | do  |
| T | : | sol |
| B | : | do  |

Exemple à trois voix :

#+ATTR_HTML: :class plat
| S | : | mi  |
| A | : | sol |
| B | : | do  |


*** Sans la tierce

Exemple à quatre voix :

#+ATTR_HTML: :class plat
| S | : | do  |
| A | : | sol |
| T | : | do  |
| B | : | do  |

Exemple à trois voix :

#+ATTR_HTML: :class plat
| S | : | do  |
| A | : | sol |
| B | : | do  |


* Septième de dominante

Une *septième de dominante* est un accord de quatre notes dont la
fondamentale est placée sur la dominante.

Exemple en /do majeur/ :

#+begin_example
sol si ré fa
#+end_example


** Dissonance
:PROPERTIES:
:CUSTOM_ID: section:dissonanceSeptiemeDomminante
:END:

Les notes d’un accord de septième de dominante forment des
intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte
  - de septième mineure

avec la fondamentale de l’accord. La septième mineure étant un
intervalle harmonique dissonant, l’accord de *septième de dominante*
est également *dissonant*.


*** Harmoniques naturelles

Considérons le début d’une série d’harmoniques naturelles de
fondamentale /sol/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | sol | sol | ré | sol | si | ré | fa | sol | la | si | do^{#} | ré | =...= |
| /Numéros/ | : |   1 |   2 |  3 |   4 |  5 |  6 |  7 |   8 |  9 | 10 |     11 | 12 | =...= |

Si nous nous arrêtons à la note 7, nous avons :

#+begin_center
sol   sol   ré   sol   si   ré   fa
#+end_center

Hors doublures, nous obtenons un ensemble de quatre notes :

#+begin_center
sol   si   ré   fa
#+end_center

L’accord de septième de dominante se trouve donc dans une situation
paradoxale. Comme tous les accords de quatres notes à base de tierces,
sa note de septième forme une dissonance avec sa fondamentale. D’un
autre coté, nous voyons apparaître un accord de *septième de
dominante* parmi les premières harmoniques naturelles. Cet accord
figure donc parmi les plus *équilibrés* des accords dissonants. Il y a
donc là une forme d’ *équilibre dynamique*, ce qui explique son rôle
crucial en harmonie.
