
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 04 : Concert
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Tonalité

#+TOC: headlines 1 local

** Introduction

L’association d’une tonique et d’un mode est appelée *tonalité*.

En effet, une fois la tonique et le mode connu, on dispose d’assez
d’informations pour construire toute la gamme.

On parlera par exemple de la tonalité de :

  - do ionien
  - la éolien
  - etc


** Notes tonales

Les *notes tonales* sont les notes les plus importantes de la gamme, à
savoir la tonique et les degrés qui l’entourent dans le cycle des
quintes :

#+ATTR_HTML: :class plat
| Noms   | : | Sous-dominante | ⟻ | 5te | ⟼ | Tonique | ⟻ | 5te | ⟼ | Dominante |
| Degrés | : |              4 | ⟻ | 5te | ⟼ |       1 | ⟻ | 5te | ⟼ |         5 |


*** Intervalles justes

Les notes tonales sont généralement séparées de la tonique par les
intervalles justes de la gamme :

| Note 1  | Note 2         | Intervalle      |
|         |                | à l’octave près |
|---------+----------------+-----------------|
| tonique | tonique        | unisson         |
| tonique | dominante      | quinte          |
| tonique | sous-dominante | quarte          |

Il existe toutefois quelques exceptions. Ainsi, la dominante de la
gamme de /si locrien/ forme un intervalle de quinte diminuée avec la
tonique, raison pour laquelle le mode locrien est peu utilisé.


** Accords

Considérons les accords de trois notes construits en prenant les notes
tonales comme fondamentales :

| Note tonale    | Degrés dans l’accord | Exemple      |
|                |                      | tonique = do |
|----------------+----------------------+--------------|
| tonique        | 1 3 5                | do mi sol    |
| dominante      | 5 7 2                | sol si ré    |
| sous-dominante | 4 6 1                | fa la do     |

On constate que l’on retrouve toutes les notes de la gamme.


** Hiérarchie des degrés

Les degrés 4, 1, 5 correspondant aux notes tonales sont appelés
*degrés forts*, ou encore *degrés tonaux*.

Les autres degrés sont appelés *degrés faibles*.


* Fonctions tonales

#+TOC: headlines 1 local

** Introduction

Une *fonction tonale* est une fonction musicale réalisée à la fois par :

  - une note tonale
  - un accord mettant en évidence cette note tonale

La musique utilisant les fonctions tonales est appelée *musique tonale*.


** Tonique

En tant que note la plus importante de la gamme, la tonique assure
aussi la première fonction tonale.

La tonique est la fonction sur laquelle la musique effectue ses pauses
les plus importantes.

On l’appelle aussi *finale*, car c’est généralement elle qui marque la
fin d’une section musicale.


** Dominante

La musique tonale s’articule autour de la dualité qui existe entre la
tonique, fonction de repos, et la dominante, fonction dynamique autour
de laquelle la musique peut se développer. Il arrive également que la
musique effectue des pauses à la dominante, mais ce sont là des arrêts
nettement moins appuyés que ceux effectués sur la tonique.

La dominante est naturellement attirée par la tonique, et peut :

  - répondre à son appel, ce qui détent la musique
  - ne pas y répondre et repartir vers une autre idée

La dominante constitue donc la fonction tonale la plus importante avec
la tonique.


** Sous-dominante

La sous-dominante constitue la fonction tonale la plus importante
après la tonique et la dominante.


** Dominante auxiliaire

Le degré 2 est situé deux quintes plus haut que la tonique dans le
cycle des quintes. En d’autres termes, il correspond à la dominante de
la dominante :

#+ATTR_HTML: :class plat
| Noms   | : | Tonique | ⟻ | 5te | ⟼ | Dominante | ⟻ | 5te | ⟼ | Sus-tonique |
| Degrés | : |       1 | ⟻ | 5te | ⟼ |         5 | ⟻ | 5te | ⟼ |           2 |

La sus-tonique permet donc de renforcer le rôle de la dominante en la
considérant comme une *tonique secondaire* dont on exprime la
dominante.

On utilise le terme de *dominante auxiliaire* pour désigner la
fonction tonale correspondant à la sus-tonique.

Par exemple, si la tonique est un /do/, la dominante est un /sol/. Que
se passerait-il si le /sol/ était la tonique ? La dominante serait
alors située une quinte au-dessus, ce qui correspond au /ré/, degré 2
de notre gamme de départ.


** Tableau récapitulatif

| Degrés | Fonctions            | Abréviations |
|--------+----------------------+--------------|
|      4 | Sous-dominante       | SD           |
|      1 | Tonique              | T            |
|      5 | Dominante            | D            |
|      2 | Dominante auxiliaire | Daux         |


* Couples

#+TOC: headlines 1 local

** Couple tonal

La musique tonale se base essentiellement sur la dualité
dominante — tonique. Le *couple tonal* est un enchaînement qui met en
évidence cette dualité en faisant entendre les deux fonctions.
L’accord faisant fonction de tonique, de par son caractère conclusif,
se place après l’accord faisant fonction de dominante :

#+ATTR_HTML: :class plat
| Dominante | — | Tonique |

Le couple tonal est également caractérisé par la descente de quinte
qui mène du premier accord au second.


** Couple plagal

Le *couple plagal* est un peu le miroir du couple tonal : au lieu de
descendre d’une quinte pour aboutir à la tonique, on monte d’une
quinte. On doit donc partir de la quinte inférieure, c’est-à-dire de
la sous-dominante :

#+ATTR_HTML: :class plat
| Sous-dominante | — | Tonique |


* Tonalité secondaire

#+TOC: headlines 1 local

** Introduction

On peut considérer le degré /X/ de la tonalité principale comme la
tonique d’une *tonalité secondaire* qui viendrait épauler la première.

Pour mettre en évidence cette tonalité secondaire, on peut exprimer
une *fonction secondaire* basée sur le degré /X/ de la tonalité
principale. Cette fonction s’obtient en considérant /X/ comme une
*tonique secondaire* et en exprimant la fonction tonale choisie :

#+begin_center
Fonction de /X/
#+end_center


*** Dominante secondaire

La *dominante secondaire* basée sur le degré /X/ de la tonalité
principale s’obtient en considérant /X/ comme une tonique secondaire
et en exprimant sa dominante :

#+begin_center
Dominante de /X/
#+end_center


*** Sous-dominante secondaire

La *sous-dominante secondaire* basée sur le degré /X/ de la gamme
courante s’obtient en considérant /X/ comme une tonique secondaire et
en exprimant sa sous-dominante :

#+begin_center
Sous-dominante de /X/
#+end_center


** Tonicisation

La tonicisation consiste à mettre en évidence le caractère de tonique
secondaire d’un degré /X/ en jouant le couple tonal secondaire :

#+ATTR_HTML: :class plat
| ( Dominante | — | Tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| Dominante de /X/ | — | Tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| Dominante de /X/ | — | /X/ |

L’accord parfait sera :

  - majeur si on souhaite mettre en évidence une tonalité secondaire majeure
  - mineur si on souhaite mettre en évidence une tonalité secondaire mineure


*** Sous-dominante secondaire

Une alternative consiste à jouer le couple plagal secondaire :

#+ATTR_HTML: :class plat
| ( Sous-dominante | — | Tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| Sous-dominante de /X/ | — | Tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| Sous-dominante de /X/ | — | /X/ |


* Sémantique

#+TOC: headlines 1 local

** Introduction

La fonction tonale d’un accord peut correspondre au degré :

  - de la fondamentale
  - de la basse
  - du soprano
  - d’une éventuelle note redoublée

Un même accord peut donc assurer différentes fonctions tonales,
suivant qu’une ou l’autre de ses notes est mise en évidence.

Inversément, de nombreux accords peuvent jouer le rôle d’une même
fonction tonale : il suffit de placer la note souhaitée en évidence.
Ce procédé permet de choisir au mieux accords et dispositions afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.


** Suppression

Parfois, la fondamentale est supprimée mais correspond malgré tout à
la fonction tonale de l’accord. On parle alors de *fonction
implicite*.


** Ornements


*** Pédale

Si une pédale est présente, c’est elle qui assure la fonction tonale
pendant toute la durée de son règne. Suivant les cas, on parle de
pédale de tonique, de dominante, ou de sous-dominante.


** Accords ornementaux


*** Accord pédale

La fonction tonale est assurée par l’accord pédale pendant toute la
durée de celui-ci.


*** Mélodiques

Les accords ornementaux mélodiques n’ont pas de fonction tonale
propre. On considère qu’ils remplissent la même fonction tonale que le
premier accord stratégique qui suit.


** Synonymes

#+TOC: headlines 1 local

*** Introduction

Deux accords distincts remplissant une même fonction tonale sont dit
*synonymes*.


*** Recherche d’accords synonymes

Nous allons considérer un exemple simple afin de bien comprendre le
procédé permettant de découvrir des accords synonymes. Nous
choisissons la note /do/ comme tonique et nous voulons découvrir les
accords pouvant remplir la fonction de dominante. La dominante étant
le /sol/, cette note devra donc pouvoir être mise en évidence. Le
choix le plus évident est un accord du degré 5 avec le /sol/ comme
fondamentale, mais il en existe d’autres.

On peut parcourir le cycle des tierces pour découvrir les autres
accords à base de tierces incluant un /sol/. Pour les triades, cela
nous donne :

  - /sol/ si ré
  - mi /sol/ si
  - do mi /sol/

On voit que les fondamentales de ces accords, /sol/, /mi/ et /do/,
descendent le cycle des tierces.

Il ne nous reste plus qu’à mettre en évidence le /sol/ en le plaçant à
la basse, au soprano ou en le doublant. Nous choissons ici la dernière
option, ce qui nous donne :

  - /sol/ si ré /sol/
  - /sol/ mi /sol/ si
  - /sol/ do mi /sol/


*** Sans fondamentale

Nous pouvons aussi considérer qu’un accord de degré 7 :

#+begin_center
si ré fa =...=
#+end_center

est un accord de degré 5 privé de sa fondamentale :

#+begin_center
(sol) si ré fa =...=
#+end_center

et remplit une fonction de dominante.


*** Synonymes usuels

Étant donné une note tonale située sur le degré /X/, les synonymes
les plus utilisés sont :

  - les accords du degré /X/
  - les accords dont la fondamentale est située une tierce plus bas que le degré /X/
  - les accords dont la fondamentale est située une quinte plus bas que le degré /X/

En effet, tous ces accords contiennent la note du degré /X/, ce qui
permet de mettre la note tonale en évidence. On ajoute à cela les
accords situés à la tierce supérieure, considérés comme des degrés /X/
sans fondamentale.

Le tableau suivant nous donne les degrés des accords synonymes :

| 5te inférieure | 3ce inférieure | Degré tonal | Tierce supérieure |
|----------------+----------------+-------------+-------------------|
|              4 |              6 |           1 |                 3 |
|              7 |              2 |           4 |                 6 |
|              1 |              3 |           5 |                 7 |


Exemple en /do majeur/ :

| Quinte inférieure | Tierce inférieure | Degré tonal | Tierce supérieure |
|-------------------+-------------------+-------------+-------------------|
| fa                | la                | do          | mi                |
| si                | ré                | fa          | la                |
| do                | mi                | sol         | si                |

Exemple en /la mineur/ :

| Quinte inférieure | Tierce inférieure | Degré tonal | Tierce supérieure |
|-------------------+-------------------+-------------+-------------------|
| ré                | fa                | la          | do                |
| sol               | si                | ré          | fa                |
| la                | do                | mi          | sol               |


*** Les plus courants

Les possibilités les plus couramment employées sont rassemblées dans
ce tableau :

| Fonctions      | Degrés | Exemple      | Exemple      |
|                |        | en do majeur | en la mineur |
|----------------+--------+--------------+--------------|
| Tonique        |      1 | do           | la           |
|                |      3 | mi           | do           |
|                |      6 | la           | fa           |
| Sous-dominante |      4 | fa           | ré           |
|                |      2 | ré           | si           |
| Dominante      |      5 | sol          | mi           |
|                |      7 | si           | sol          |


** Lien sémantique

Lorsqu’une modification de la disposition d’un accord /A/ permet de
rendre sa fonction tonale identique à celle d’un accord /B/, on dit
qu’il existe un *lien sémantique* entre les accords /A/ et /B/.

Par exemple, en /do majeur/, l’accord :

#+begin_center
do mi sol
#+end_center

exerce une fonction de tonique. Si nous plaçons le /sol/ à la basse et
que nous le doublons :

#+begin_center
sol do mi sol
#+end_center

il exerce alors une fonction de dominante. On met ainsi en évidence un
lien sémantique avec l’accord du degré 5 :

#+begin_center
sol si ré sol
#+end_center

qui exerce la même fonction.


*** Synonymes

Si les accords /A/ et /B/ sont unis par un lien sémantique, on peut
réarranger /A/, ou du moins réinterpréter sa fonction tonale, pour
qu’il soit synonyme de /B/.


* Dynamique

#+TOC: headlines 1 local


** Introduction

La dynamique musicale est basée sur l’alternance de *tension* et de
*détente*, la détente servant de *résolution* à la tension initiale :

#+ATTR_HTML: :class plat
| Tension | — | Résolution |

La tension d’un objet musical est souvent due à l’ *attraction* vers
un objet proche condidéré comme plus stable.

Un objet musical est qualifié de :

  - *stable* ou *consonant* s’il ne cause aucune tension

  - *instable* ou *dissonant* s’il provoque une tension

Un objet musical consonant est aussi appelé *consonance*.

Un objet musical dissonant est aussi appelé *dissonance*.


** Préparation

Une tension peut être précédée d’une phase de *préparation*, phase qui
permet d’introduire la future dissonance dans un contexte où elle est
consonante. On a donc la structure générique :

#+ATTR_HTML: :class plat
| Préparation | — | Tension | — | Résolution |

où la phase de préparation est optionnelle.

La dissonance qui passe par une phase de préparation est dite
*préparée*.


** Résolution

Lorsqu’une dissonance se résout indifféremment suivant plusieurs
processus différents, on dit alors que sa résolution est *libre*.

Lorsqu’une dissonance se résout préférentiellement via un processus
bien défini, correspondant à un effet de détente maximal, on dit alors
que cette résolution est *régulière* ou *ordinaire*. On parle
également de *mouvement obligé*.

Dans le cas où une dissonance censée adopter un mouvement obligé se
résout autrement, on parle de résolution *irrégulière* ou
*exceptionnelle*.

Enfin, lorsqu’une dissonance ne se résout pas, on peut conduire la
musique vers une autre idée, ou vers une tension encore plus forte.


*** Absolue ou relative

La *résolution absolue* fait suivre un objet dissonant par un objet
consonant.

La *résolution relative* fait suivre un objet consonant par un objet
qui est encore plus consonant que le premier.


*** Nouveauté

La dissonance peut être utilisée comme *introduction* à un nouvel
objet musical, la résolution amenant alors la *nouveauté* que l’on
souhaite présenter :

#+ATTR_HTML: :class plat
| Introduction | = | Tension    |
| Nouveauté    | = | Résolution |


* Sensibles

#+TOC: headlines 1 local

** Introduction

Une note située à une distance d’un demi-ton de la tonique crée une
attraction mélodique vers cette dernière.

La tonique correspondant au degré 1, les notes qui l’entourent sont
situées aux degrés 2 et 7.

Lorsque le degré 7 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible inférieure*.

Lorsque le degré 2 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible supérieure*.

Exemples :

  - si la tonique est un /do/, le /si/ sera une sensible inférieure

  - si la tonique est un /mi/, le /fa/ sera une sensible supérieure


** Sensibles auxiliaires

Une note située à une distance d’un demi-ton de la dominante crée une
attraction mélodique vers cette dernière.

La dominante correspondant au degré 5, les notes qui l’entourent sont
situées aux degrés 4 et 6.

Lorsque le degré 4 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire inférieure*.

Lorsque le degré 6 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire supérieure*.


** Tableau récapitulatif

| Degrés | Noms                           | Abréviations |
|--------+--------------------------------+--------------|
|      2 | Sensible supérieure            | Ssup         |
|      7 | Sensible inférieure            | Sinf         |
|      6 | Sensible auxiliaire supérieure | SauxSup      |
|      4 | Sensible auxiliaire inférieure | SauxInf      |


* Dynamique mélodique

#+TOC: headlines 1 local


** Sensibles

Une sensible induit une tension mélodique vers la note tonale la plus
proche : tonique ou dominante. Les sensibles sont donc considérées
comme des notes dissonantes.

Voici les résolutions attendues :

  - la sensible inférieure se résout sur la tonique en montant d’un demi-ton
  - la sensible supérieure se résout sur la tonique en descendant d’un demi-ton
  - la sensible auxiliaire inférieure se résout sur la dominante en montant d’un demi-ton
  - la sensible auxiliaire supérieure se résout sur la dominante en descendant d’un demi-ton


** Hauteur

Une note plus aiguë est plus tendue qu’une note plus grave.

Une note plus grave est plus détendue qu’une note plus aiguë.


** Intervalles

Un intervalle conjoint ne suscite pas de tension.

Un intervalle disjoint entre deux notes /x/ et /y/ suscite une tension
qui se résout en jouant les notes intermédiaires entre /x/ et /y/.


** Direction

Une mélodie qui monte vers l’aigu génère une tension.

Une mélodie qui descend vers le grave produit une détente.


** Extrêmes

Une mélodie dont les pics (maxima locaux) montent vers l’aigu génère
une tension.

Une mélodie dont les creux (minima locaux) descendent vers le grave
produit une détente.


* Modes

#+TOC: headlines 1 local

** Introduction

Nous avons déjà vu les modes naturels, le majeur et le mineur. Ce
chapitre recense les autres modes disponibles.


** Mineur harmonique

Le mode majeur dispose d’une sensible inférieure. Par exemple,
en /do majeur/, la sensible inférieure est le /si/, à un demi-ton de
la tonique /do/. Cette propriété est intéressante car la sensible est
naturellement attirée par la tonique, ce qui permet de donner de la
dynamique à un déroulement musical.

En mode mineur par contre, le degré 7 est situé un ton entier sous la
tonique. La propriété d’attirance de la sensible vers la tonique n’est
donc pas présente. On peut toutefois y remédier en haussant la
sous-tonique d’un demi-ton, obtenant ainsi un mode dérivé, appelé
*mode mineur harmonique*. Par exemple, en /la mineur/, le /sol/ sera
haussé d’un demi-ton, donnant ainsi la gamme :

#+begin_center
la si do ré mi fa sol^{#} la
#+end_center

Dans la suite, le mode mineur par défaut sera généralement le mode
mineur harmonique.


** Mineur ascendant et descendant

Le mode mineur harmonique sonne très bien, disposant à la fois de la
sonorité du mode mineur et de l’attirance de la sensible inférieure.
Cependant, l’écart de trois demi-tons entre les degrés 6 et 7 n’est
pas toujours souhaitable. Dans ce cas, on hausse le degré 6, obtenant
un mode appelé *mode mineur ascendant*. Exemple, le /la mineur
ascendant/ :

#+begin_center
la si do ré mi fa^{#} sol^{#} la
#+end_center

Par opposition, on appelle alors *mode mineur descendant* le mode
mineur naturel (le mode éolien). En pratique, les modes mineurs
(harmonique, ascendant et descendant) sont souvent mêlés, donnant
ainsi beaucoup de couleur et de souplesse à la musique. Enfin, le
degré 3 peut lui aussi être haussé d’un demi-ton, complétant ainsi le
caractère polymorphe du mode mineur, qui peut se rapprocher ou même se
confondre avec le mode majeur.


** Variantes des modes naturels


*** Acoustique

Le mode acoustique est construit à partir des premiers éléments de la
série des harmoniques naturelles. Elle contient donc une quinte, une
tierce majeure, une septième mineure, une seconde majeure et une
quarte augmentée. En partant d’un /do/, on obtient :

#+begin_center
do ré mi fa^{#} sol si^b do
#+end_center

On peut bien entendu ajouter la note naturelle manquante, à savoir
le /la/ :

#+begin_center
do ré mi fa^{#} sol la si^b do
#+end_center

La gamme ainsi obtenue possède les mêmes écarts qu’un relatif du mode
mineur ascendant à partir du quatrième degré :

#+begin_center
ré mi fa^{#} sol^{#} la si do ré
#+end_center


*** Superlocrien

Le mode superlocrien est construit comme un relatif du mode mineur
ascendant à partir du septième degré :

#+begin_center
sol^{#} la si do ré mi fa^{#} sol^{#}
#+end_center

Ce mode est appelé superlocrien, car il ressemble fort au mode
locrien. On le voit clairement en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la si
#+end_center


**** Mineur harmonique

Il existe aussi une variante dérivée du mode mineur harmonique :

#+begin_center
sol^{#} la si do ré mi fa sol^{#}
#+end_center

ce qui donne, en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la^b si
#+end_center


*** Tzigane

Le mode Tzigane, ou mode Hongrois, est un mode dérivé du mineur
harmonique, le 4e degré étant haussé afin de se rapprocher de la
dominante :

#+begin_center
la si do ré^{#} mi fa sol^{#} la
#+end_center

Ce mode est caractérisé par la présence de deux sensibles auxiliaires :

#+begin_center
sensible auxiliaire inférieure ⟼ dominante ⟻ sensible auxiliaire supérieure
#+end_center

Notons les deux écarts de trois demi-tons entre les degrés 3 - 4 et
6 - 7.


*** Andalou

Il s’agit d’un mode ressemblant au /mode de mi/, mais disposant d’une
médiante flottante, formant une tierce majeure ou mineure avec la
tonique :

#+begin_center
mi fa sol^{(#)} la si do ré mi
#+end_center


*** Napolitain

Il s’agit d’un mode ressemblant au /mode de mi/ où le septième degré
est haussé d’un demi-ton, ce qui le transforme en sensible inférieure :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

On voit que la sus-tonique est une sensible supérieure. Ce mode est
donc caractérisé par la double attraction :

#+begin_center
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+end_center

Il en existe une variante où le sixième degré est haussé :

#+begin_center
mi fa sol la si do^{#} ré^{#} mi
#+end_center


*** Oriental


**** Variante phrygienne

Le mode oriental phrygien est un relatif du mode tzigane construit à
partir du cinquième degré :

#+begin_center
mi fa sol^{#} la si do ré^{#} mi
#+end_center

Ce mode est caractérisé par les deux écarts de trois demi-tons entre
les degrés 2 - 3 et 6 - 7, ainsi que par la double attraction :

#+begin_center
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+end_center

Si on souhaite également créer une double attraction vers la
dominante :

#+begin_center
sous-dominante altérée ⟼ dominante ⟻ sous-médiante
#+end_center

il suffit de hausser le degré 4 :

#+begin_center
mi fa sol^{#} la^{#} si do ré^{#} mi
#+end_center


**** Variante locrienne

Le mode oriental phrygien est un relatif du mode tzigane construit à
partir du deuxième degré :

#+begin_center
si do ré^{#} mi fa sol^{#} la si
#+end_center

Afin d’obtenir la même propriété de double attraction que la variante
basée sur le mode de /mi/, on peut sensibiliser le degré 7 en le
haussant d’un demi-ton :

#+begin_center
si do ré^{#} mi fa sol^{#} la^{#} si
#+end_center


** Tétraphoniques

Les modes tetraphoniques sont des gammes de quatre notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
quatre quintes :

#+begin_center
do sol ré la
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode tetraphonique :

#+begin_center
do ré sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do | ré  | sol |
| sur ré  | : | ré  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré | sol | la  |


** Pentaphoniques

Les modes pentaphoniques sont des gammes de cinq notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
cinq quintes :

#+begin_center
do sol ré la mi
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode pentaphonique :

#+begin_center
do ré mi sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do  | ré | mi  | sol |
| sur ré  | : | ré  | mi  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré  | mi | sol | la  |
| sur mi  | : | mi  | sol | la  | do | ré  | mi  |


*** Avec caractéristique

Ce sont des modes pentaphoniques que l’on altère afin d’intégrer une
ou plusieurs notes caractéristiques des modes naturels. Par exemple,
ce mode pentaphoniques altéré :

#+begin_center
ré mi sol^{#} la do ré
#+end_center

possède une quarte haussée, caractéristique du mode lydien.


*** Blues

Le mode blues est un mode pentaphonique développant les quintes à
partir de la médiante. La médiante, la dominante et la sous-tonique
sont flottantes :

#+begin_center
la do^{(#)} ré mi^{(b)} sol^{(#)} la
#+end_center


*** Chinois

Le mode chinois est un mode pentaphonique développant les quintes à
partir de la tonique. Par exemple, avec /do/ comme tonique, nous
obtenons :

#+begin_center
do ré mi sol la do
#+end_center


*** Japonais

Le mode japonais est un mode pentaphonique développant les quintes à
partir de la sous-dominante. La gamme modèle de ce mode possède un
/mi/ pour tonique. On part alors de la sous-dominante /la/ et on
gravit les quintes entre notes naturelles :

#+begin_center
la mi si fa do
#+end_center

 En disposant ces notes sur une octave /mi — mi^{+1}/ et en les
ordonnant de la plus grave à la plus aiguë, nous obtenons :

#+begin_center
mi fa la si do mi
#+end_center

La dominante auxiliaire /fa/ est une sensible supérieure. Ce mode
possède un autre demi-ton entre la dominante /si/ et la sous-médiante
/do/.

Notons également l’intervalle de quarte augmentée /si — fa/ qui sépare
la sus-tonique de la dominante.


* Accords classés

#+TOC: headlines 1 local


** Introduction

Les accords classés sont des accords naturellement engendrés par les
gammes lorsqu’on y superpose des tierces.


*** Nomenclature

Une *septième de dominante* est un accord de quatre notes dont la
fondamentale est placée sur la dominante.

Une *septième d’espèce* est un accord de quatre notes dont la
fondamentale n’est pas placée sur la dominante.

On utilise les abréviations suivantes :

| Accord                | Abréviation |
|-----------------------+-------------|
| Septième de dominante | 7e D        |
| Septième d’espèce     | 7e E        |


** Tonique

Les accords de tonique les plus utilisés sont des accords parfaits
majeur ou mineur. On rencontre aussi des septièmes d’espèce, comme
dans ces exemples :

| Accords             | Abréviations | Exemples             |                  |
|                     |              | Gammes               | Accords          |
|---------------------+--------------+----------------------+------------------|
| Septième majeure    | 7e M         | do majeur            | do mi sol si     |
| Septième mineure    | 7e m         | la mineur            | la do mi sol     |
| Septième harmonique | 7e h         | la mineur harmonique | la do mi sol^{#} |

et plus rarement des accords de 5, 6 ou 7 notes.


*** Quinte augmentée

Si nous supprimons la fondamentale de l’accord de septième harmonique,
nous obtenons un accord dit de *quinte augmentée* :

| Accords          | Abréviations | Exemples      |
|------------------+--------------+---------------|
| Quinte augmentée | 5te aug      | do mi sol^{#} |


** Dominante

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante sont très importants, de par leur fonction
tonale dynamique et parce qu’ils sont naturellement attirés par un
accord de tonique.


*** Triades

En empilant deux tierces, on obtient un accord parfait majeur, que ce
soit en mode majeur ou mineur harmonique :

| Accords        | Abréviations | Exemples             |               |
|                |              | Gammes               | Accords       |
|----------------+--------------+----------------------+---------------|
| Parfait majeur | M            | do majeur            | sol si ré     |
| Parfait majeur | M            | la mineur harmonique | mi sol^{#} si |


*** Septième

En empilant trois tierces, on obtient l’accord de *septième de
dominante*, dont la structure est identique en majeur et en mineur
harmonique :

| Accords               | Abréviations | Exemples             |                  |
|                       |              | Gammes               | Accords          |
|-----------------------+--------------+----------------------+------------------|
| Septième de dominante | 7e D         | do majeur            | sol si ré fa     |
| Septième de dominante | 7e D         | la mineur harmonique | mi sol^{#} si ré |

Dans les deux cas :

  - la première tierce est majeure
  - les deux tierces suivantes sont mineures

Avec les accords parfaits majeur et mineur, la septième de dominante
figure parmi les accords les plus importants de l’harmonie tonale.


**** Quinte diminuée

Lorsqu’on prive un accord de dominante de sa fondamentale, on obtient
un accord de *quinte diminuée* :

| Accords         | Abréviations | Exemples             |               |
|                 |              | Gammes               | Accords       |
|-----------------+--------------+----------------------+---------------|
| Quinte diminuée | 5te dim      | do majeur            | si ré fa      |
| Quinte diminuée | 5te dim      | la mineur harmonique | sol^{#} si ré |


*** Neuvième

En empilant quatre tierces, on obtient la *neuvième de dominante*,
majeure ou mineure suivant le mode :

| Accords                       | Abréviations | Exemples             |                     |
|                               |              | Gammes               | Accords             |
|-------------------------------+--------------+----------------------+---------------------|
| Neuvième de dominante majeure | 9e D M       | do majeur            | sol si ré fa la     |
| Neuvième de dominante mineure | 9e D m       | la mineur harmonique | mi sol^{#} si ré fa |


**** Septième et quinte diminuée

Lorsqu’on prive une neuvième de dominante majeure de sa fondamentale,
on obtient un accord de *septième et quinte diminuée* :

| Accords                     | Abréviations | Exemples  |             |
|                             |              | Gammes    | Accords     |
|-----------------------------+--------------+-----------+-------------|
| Septième et quinte diminuée | 7e & 5te dim | do majeur | si ré fa la |


**** Septième diminuée

Lorsqu’on prive une neuvième de dominante mineure de sa fondamentale,
on obtient un accord de *septième diminuée* :

| Accords           | Abréviations | Exemples             |                  |
|                   |              | Gammes               | Accords          |
|-------------------+--------------+----------------------+------------------|
| Septième diminuée | 7e dim       | la mineur harmonique | sol^{#} si ré fa |


** Sous-dominante

Les accords de sous-dominante sont similaires aux accords de tonique :
accords parfaits et septièmes majeures ou mineures. Exemples :

| Accords | Exemples  |             |
|         | Gammes    | Accords     |
|---------+-----------+-------------|
| 7e M    | do majeur | fa la do mi |
| 7e m    | la mineur | ré fa la do |


** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: section:dominanteAuxiliaire
:END:

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante auxiliaire sont similaires aux accords de
dominante, si ce n’est qu’ils sont construits sur le degré 2 de la
gamme. Afin de renforcer le rôle de ces accords, il est possible de
les altérer en faisant /comme si/ la dominante de la gamme courante
devenait la tonique. On utilise les abréviations :

| Accords                          | Abréviations |
|----------------------------------+--------------|
| Triade de dominante auxiliaire   | 3ade Daux    |
| Septième de dominante auxiliaire | 7e Daux      |
| Neuvième de dominante auxiliaire | 9e Daux      |


*** Majeur

Nous prenons comme illustration la gamme de /do majeur/. Nous obtenons
par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| do ré mi fa sol la si do | ⟼ | sol la si do ré mi fa^{#} sol |

L’altération haussière du /fa^{#}/ (degré 4 par rapport à la tonique
/do/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /sol/.

On peut également altérer le /la/ (degré 6 par rapport à la tonique
/do/) vers le bas afin de le transformer en sensible auxiliaire
supérieure. Nous avons alors la gamme :

#+begin_center
sol la^b si do ré mi fa^{#} sol
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en do majeur |
|-------------------------+-----------+-----------------------|
| Aucune                  | 3ade Daux | ré fa la              |
|                         | 7e Daux   | ré fa la do           |
|                         | 9e Daux   | ré fa la do mi        |
| Inférieure              | 3ade Daux | ré fa^{#} la          |
|                         | 7e Daux   | ré fa^{#} la do       |
|                         | 9e Daux   | ré fa^{#} la do mi    |
| Inférieure & Supérieure | 3ade Daux | ré fa^{#} la^b        |
|                         | 7e Daux   | ré fa^{#} la^b do     |
|                         | 9e Daux   | ré fa^{#} la^b do mi  |


*** Mineur harmonique

Nous prenons comme illustration la gamme de /la mineur harmonique/.
Nous obtenons par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| la si do ré mi fa sol^{#} la | ⟼ | mi fa^{#} sol la si do ré^{#} mi |

L’altération haussière du /ré^{#}/ (degré 4 par rapport à la tonique
/la/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /mi/.

Si on supprime l’altération haussière du /fa^{#}/ (degré 6 par rapport
à la tonique /la/), on transforme ce degré en sensible auxiliaire
supérieure de la dominante /mi/. Nous obtenons alors la gamme :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en la mineur harmonique |
|-------------------------+-----------+----------------------------------|
| Supérieure              | 2ade Daux | si ré fa                         |
|                         | 7e Daux   | si ré fa la                      |
|                         | 9e Daux   | si ré fa la do                   |
| Inférieure              | 3ade Daux | si ré^{#} fa^{#}                 |
|                         | 7e Daux   | si ré^{#} fa^{#} la              |
|                         | 9e Daux   | si ré^{#} fa^{#} la do           |
| Inférieure & Supérieure | 3ade Daux | si ré^{#} fa                     |
|                         | 7e Daux   | si ré^{#} fa la                  |
|                         | 9e Daux   | si ré^{#} fa la do               |

Remarquons en passant que la triade de dominante auxiliaire non
altérée est un accord de quinte diminuée.


*** Sans fondamentale

Tout comme les accords de dominante, les accords de dominante
auxiliaire sont parfois présentés sans leur fondamentale. On obtient
alors des accords qui semblent être du degré 4, les fonctions de
dominante auxiliaire et de sous-dominante se voyant ainsi intimement
liées.

Exemple en /do majeur/ :

| Sensibles auxiliaires   | Accords | Exemples en do majeur |
|-------------------------+---------+-----------------------|
| Aucune                  | 7e Daux | fa la do              |
|                         | 9e Daux | fa la do mi           |
| Inférieure              | 7e Daux | fa^{#} la do          |
|                         | 9e Daux | fa^{#} la do mi       |
| Inférieure & Supérieure | 7e Daux | fa^{#} la^b do        |
|                         | 9e Daux | fa^{#} la^b do mi     |

Exemple en /la mineur harmonique/ :

| Sensibles auxiliaires   | Accords | Exemples en la mineur harmonique |
|-------------------------+---------+----------------------------------|
| Supérieure              | 7e Daux | ré fa la                         |
|                         | 9e Daux | ré fa la do                      |
| Inférieure              | 7e Daux | ré^{#} fa^{#} la                 |
|                         | 9e Daux | ré^{#} fa^{#} la do              |
| Inférieure & Supérieure | 7e Daux | ré^{#} fa la                     |
|                         | 9e Daux | ré^{#} fa la do                  |


*** Sixtes augmentées

#+TOC: headlines 1 local

**** Introduction

Les accords de *sixte augmentée* sont des accords de dominante
auxiliaire renversés. Ils sont altérés de sorte qu’ils présentent un
intervalle caractéristique de sixte augmentée, d’où leur nom.


**** Sixte française

La *sixte française* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est présentée sous la forme d’un
second renversement.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| ré fa^{#} la^b do | ⟼ | la^b do ré fa^{#} |

En /la mineur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| si ré^{#} fa la | ⟼ | fa la si ré^{#} |


**** Sixte italienne

La *sixte italienne* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (ré) fa^{#} la^b do | ⟼ | la^b do (ré) fa^{#} |

ce qui nous donne finalement :

#+begin_center
la^b do fa^{#}
#+end_center

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la | ⟼ | fa la (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la ré^{#}
#+end_center


**** Sixte allemande

La *sixte allemande* est une neuvième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la do | ⟼ | fa la do (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la do ré^{#}
#+end_center

L’accord altéré de /do majeur/ respectant les mêmes écarts s’écrit :

#+begin_center
la^b do mi^b fa^{#}
#+end_center


** Emprunts

Un emprunt est un accord provenant d’une autre gamme (tonique et/ou
mode) que l’on insère dans la gamme courante.


*** Majeur ⟻⟼ Mineur

On peut placer des accords caractéristiques du mineur (quintes
augmentées, septièmes diminuées, ...) dans des gammes majeures, ou
l’inverse.


*** Tierces picardes

Une *tierce picarde* est un accord parfait majeur intégré à un autre
mode. On la rencontre souvent sur les degrés 1, 5, ou 4 du mode
mineur : la tierce de l’accord y est rendue majeure par une altération
haussière. Voici des exemples en /la mineur/ :

| Degrés | Exemples      |
|--------+---------------|
|      1 | la do^{#} mi  |
|      4 | ré fa^{#} la  |
|      5 | mi sol^{#} si |


*** Napolitain

En gamme de /mi napolitain/, l’accord de dominante auxiliaire non
altéré :

#+begin_center
fa la do
#+end_center

est un accord parfait majeur situé un demi-ton au-dessus de la tonique
/mi/. Par extension, on appelle accord *napolitain* tout accord défini
par les mêmes propriétés, et ce quels que soient le mode et la
tonique. Voici ce que cela donne en majeur et en mineur :

| do majeur    | la mineur  |
|--------------+------------|
| ré^b fa la^b | si^b ré fa |

Lorsque cet accord est présenté sous la forme de premier renversement,
il est appelé *sixte napolitaine* :

| do majeur    | la mineur  |
|--------------+------------|
| fa la^b ré^b | ré fa si^b |

Afin de former un accord similaire à une 7e de dominante, on peut
ajouter une note de 7e mineure à l’accord napolitain :

| do majeur         | la mineur       |
|-------------------+-----------------|
| ré^b fa la^b do^b | si^b ré fa la^b |

Ces derniers accords sont très prisé en jazz, où ils sont parfois
appelés *substitution au triton*, ou *substitution tritonique* à cause
de l’intervalle de triton qui lie la dominante auxiliaire altérée vers
le bas avec la dominante.


** Modes composites

Un *mode composite* associe à chaque degré une liste d’accords qui lui
sont caractéristiques. Voici un exemple de mode composite proche du
/la mineur/ :

| Degrés | Accords                     | Exemples             |
|--------+-----------------------------+----------------------|
|      1 | Parfait mineur              | la do mi             |
|        | Parfait majeur              | la do^{#} mi         |
|      2 | 7e Daux                     | si ré fa la          |
|        |                             | si ré^{#} fa la      |
|        | Napolitains                 | si^b ré fa           |
|        |                             | si^b ré fa la^b      |
|      3 | Quinte augmentée            | do mi sol^{#}        |
|      4 | Parfait mineur              | ré fa la             |
|        | Parfait majeur              | ré fa^{#} la         |
|      5 | Septième de dominante       | mi sol^{#} si ré     |
|        | Neuvième de dominante       | mi sol^{#} si ré fa  |
|      6 | Parfait majeur              | fa la do             |
|        | Quinte diminuée             | fa^{#} la do         |
|      7 | Quinte diminuée             | sol^{#} si ré        |
|        | Septième diminuée           | sol^{#} si ré fa     |
|        | Septième et quinte diminuée | sol^{#} si ré fa^{#} |

Cette variété d’accords implique qu’une partie ou la totalité des
notes de la gamme peut être altérée vers le haut ou vers le bas en
fonction du contexte.


* Accords à base de quintes

Les accords à base de tierces, présents dans les premières harmoniques
naturelles, sont de loin les plus utilisés. Mais on rencontre
également une autre famille d’accords, où la quinte est la brique de
construction. Le cas le plus simple consiste à superposer deux
quintes, obtenant ainsi une triade que nous décidons de nommer accord
de *double quinte* :

| Accords       | Exemples  |
|---------------+-----------|
| Double quinte | fa do sol |

En permutant les notes afin de les rapprocher, nous obtenons les
accords de *double quarte*, de *quarte et quinte* et de *seconde et
quinte* :

| Accords           | Exemples  |
|-------------------+-----------|
| Double quarte     | sol do fa |
| Quarte et quinte  | do fa sol |
| Seconde et quinte | fa sol do |

Les accords de quatre et cinq notes sont construits en superposant
trois ou quatre quintes :

| Accords          | Exemples         |
|------------------+------------------|
| Triple quinte    | fa do sol ré     |
| Quadruple quinte | fa do sol ré la  |

En intervertissant l’ordre des notes, ces accords deviennent des
accords de triple et quadruple quarte :

| Accords          | Exemples        |
|------------------+-----------------|
| Triple quarte    | ré sol do fa    |
| Quadruple quarte | la ré sol do fa |

Voici quelques autres permutations de ces accords :

| Triple quinte | Quadruple quinte |
|---------------+------------------|
| do ré fa sol  | do ré fa sol la  |
| do fa sol ré  | do fa sol la ré  |

/Remarque/ : jouer un accord de triple quinte revient à construire
localement un mode tétraphonique. Dans le même ordre d’idée, jouer un
accord de quadruple quinte revient à construire localement un mode
pentaphonique.


* Consonance & Dissonance

#+TOC: headlines 1 local

** Intervalles harmoniques

#+TOC: headlines 1 local

*** Introduction

Les intervalles harmoniques peuvent être classés suivant leur
caractère consonant ou dissonant. Un *intervalle consonant* donne une
impression de douceur, d’équilibre, de plénitude. Par contre, un
*intervalle dissonant* est dans un état de tension qui est appelé à se
résoudre sur un intervalle consonant proche, appelé *intervalle de
résolution*.

La classification des intervalles harmoniques est basée sur la série
des harmoniques naturelles, série commençant par les intervalles
considérés comme consonants en théorie classique. Analysons par
exemple le début d’une série d’harmoniques naturelles de fondamentale
/do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Les premiers intervalles qui apparaissent sont :

| Intervalle harmonique | Note I | Note II |
|-----------------------+--------+---------|
| Unisson               |      1 |       1 |
| Octave                |      1 |       2 |
| Quinte                |      2 |       3 |
| Quarte                |      3 |       4 |
| Tierce majeure        |      4 |       5 |
| Tierce mineure        |      5 |       6 |
| Sixte majeure         |      3 |       5 |
| Sixte mineure         |      5 |       8 |
| Septième mineure      |      4 |       7 |
| Seconde majeure       |      8 |       9 |
| Quarte augmentée      |      8 |      11 |

La classification usuelle des intervalles considère les intervalles
comme consonants jusqu’aux sixtes, et dissonants ensuite. Les
intervalles augmentés et diminués sont également considérés comme
dissonants.


*** Consonances

Le tableau suivant donne la liste des intervalles consonants :

| Consonances                | Intervalles harmoniques |
|----------------------------+-------------------------|
| Consonances parfaites      | Unisson                 |
|                            | Octave                  |
|                            | Quinte                  |
| Consonances intermédiaires | Quarte                  |
| Consonances imparfaites    | Tierce majeure          |
|                            | Tierce mineure          |
|                            | Sixte majeure           |
|                            | Sixte mineure           |

/Remarque/ : le terme « consonance imparfaite » ne signifie pas qu’une
tierce ou une sixte sonne moins bien qu’une quinte ou qu’une octave,
mais simplement que les notes des consonances parfaites se ressemblent
plus que celles des consonances imparfaites.


*** Dissonances

Le tableau suivant donne la liste des intervalles dissonants :

| Dissonances                | Intervalles harmoniques |
|----------------------------+-------------------------|
| Dissonances imparfaites    | Septième mineure        |
|                            | Seconde majeure         |
| Dissonances intermédiaires | Quarte augmentée        |
| Dissonances parfaites      | Septième majeure        |
|                            | Seconde mineure         |
| Autres                     | Intervalles diminués    |
|                            | Intervalles augmentés   |


** Accords

#+TOC: headlines 1 local

*** Introduction

Dans le cadre d’un accord :

  - une *note consonante* est une note constitutive qui forme un
    intervalle harmonique consonant avec la fondamentale

  - une *note dissonante* est une note constitutive qui forme un
    intervalle harmonique dissonant avec la fondamentale

Une note dissonante est également appelée *dissonance constitutive*.

Les accords sont également classés suivant leur caractère stable ou
instable :

  - un *accord consonant* est un accord

    + qui ne contient que des notes consonantes

    + ET dont tous les intervalles internes sont consonants

  - un *accord dissonant* est un accord

    + qui contient au moins une note dissonante

    + OU dont au moins un intervalle interne est dissonant


*** Intervalles

#+TOC: headlines 1 local

**** Accords parfaits

Les notes d’un accord parfait majeur forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte juste

avec la fondamentale de l’accord. Les intervalles internes sont
également des tierces et des quintes.

L’ *accord parfait majeur* est donc un accord *consonant*.

#+begin_center
⁂
#+end_center

Les notes d’un accord parfait mineur forment des intervalles :

  - d’unisson
  - de tierce mineure
  - de quinte juste

avec la fondamentale de l’accord. Les intervalles internes sont
également des tierces et des quintes.

L’ *accord parfait mineur* est donc un accord *consonant*.

#+begin_center
⁂
#+end_center


***** Premier renversement

Les notes d’un accord parfait majeur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce mineure
  - de sixte mineure

avec la fondamentale de l’accord. Les intervalles internes sont
des tierces, des quartes et des sixtes.

L’accord parfait majeur au premier renversement est donc un accord
consonant.

#+begin_center
⁂
#+end_center

Les notes d’un accord parfait mineur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce majeure
  - de sixte majeure

avec la fondamentale de l’accord. Les intervalles internes sont
des tierces, des quartes et des sixtes.

L’accord parfait mineur au premier renversement est donc un accord
consonant.


***** Second renversement

Les notes d’un accord parfait majeur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte majeure

avec la fondamentale de l’accord. Les intervalles internes sont des
tierces, des quartes et des sixtes.

L’accord parfait majeur au second renversement est donc un accord
consonant.

#+begin_center
⁂
#+end_center

Les notes d’un accord parfait mineur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte mineure

avec la fondamentale de l’accord. Les intervalles internes sont des
tierces, des quartes et des sixtes.

L’accord parfait mineur au second renversement est donc un accord
consonant.


**** Autres triades

Les notes d’un accord de quinte augmentée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte augmentée

avec la fondamentale de l’accord. La quinte augmentée étant un
intervalle harmonique dissonant, l’accord de *quinte augmentée* est
*dissonant*.

#+begin_center
⁂
#+end_center

Les notes d’un accord de quinte diminuée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte diminuée

avec la fondamentale de l’accord. La quinte diminuée étant un
intervalle harmonique dissonant, l’accord de *quinte diminuée* est
*dissonant*.


**** Septième de dominante

Les notes d’un accord de septième de dominante forment des
intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte
  - de septième mineure

avec la fondamentale de l’accord. La septième mineure étant un
intervalle harmonique dissonant, l’accord de *septième de dominante*
est également *dissonant*.


**** Autres accords de quatre notes ou plus

Un accord de quatre notes ou plus contient au moins une note qui va
former un intervalle harmonique de septième (mineure, majeure ou
diminuée) avec la fondamentale. Tous ces accords sont donc
*dissonants*.


**** Accords à base de quintes

Les accords à base de quintes contiennent au moins un intervalle
dissonant : seconde, septième, neuvième, etc. Ce sont donc des accords
dissonants.


*** Harmoniques naturelles

#+TOC: headlines 1 local

**** Introduction

Nous allons à présent opter pour un point de vue légèrement différent
en nous basant cette fois sur la série des harmoniques naturelles.


**** Accord parfait majeur

Considérons par exemple le début d’une série d’harmoniques naturelles
de fondamentale /do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Si nous nous arrêtons à la note 6, nous avons :

#+begin_center
do   do   sol   do   mi   sol
#+end_center

Hors doublures, nous obtenons un ensemble de trois notes :

#+begin_center
do   mi   sol
#+end_center

qui n’est rien d’autre qu’un accord parfait majeur.

L’ *accord parfait majeur* est donc un accord consonant, autant du
point de ses intervalles harmoniques internes que de la série des
harmoniques naturelles.


**** Septième de dominante

Considérons par exemple le début d’une série d’harmoniques naturelles
de fondamentale /sol/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | sol | sol | ré | sol | si | ré | fa | sol | la | si | do^{#} | ré | =...= |
| /Numéros/ | : |   1 |   2 |  3 |   4 |  5 |  6 |  7 |   8 |  9 | 10 |     11 | 12 | =...= |

Si nous nous arrêtons à la note 7, nous avons :

#+begin_center
sol   sol   ré   sol   si   ré   fa
#+end_center

Hors doublures, nous obtenons un ensemble de quatre notes :

#+begin_center
sol   si   ré   fa
#+end_center

L’accord de septième de dominante se trouve donc dans une situation
paradoxale. Comme tous les accords de quatres notes à base de tierces,
sa note de septième forme une dissonance avec sa fondamentale. D’un
autre coté, nous voyons apparaître un accord de *septième de
dominante* parmi les premières harmoniques naturelles. Cet accord
figure donc parmi les plus *équilibrés* des accords dissonants. Il y a
donc là une forme d’ *équilibre dynamique*, ce qui explique son rôle
important.


*** Tableau récapitulatif

| Stabilité           | Accords               |
|---------------------+-----------------------|
| Consonants          | Parfait majeur        |
|                     | Parfait mineur        |
| Équilibre dynamique | Septième de dominante |
| Dissonants          | Tous les autres       |


* Dynamique des accords

#+TOC: headlines 1 local

** Introduction

Le principe d’alternance d’accords stables et instables est
omniprésent en musique. Ce ressort musical est centré autour d’une
phase de *tension*, accord instable contenant une ou plusieurs notes
dissonantes. Chaque tension est suivie d’une phase de *résolution* où
chaque note dissonante se résout vers une note d’un accord stable.

La résolution d’une note instable dans un accord stable peut se
réaliser suivant différents schémas :

  - *résolution conjointe* : la note instable réalise un mouvement
    conjoint vers une note inclue dans l’accord stable

  - *résolution polyphonique* : les notes instables réalisent un
    mouvement polyphonique élégant vers des notes inclues dans
    l’accord stable

  - *résolution par intégration* : la note instable est inclue dans
    l’accord stable suivant et devient donc naturellement stable lors
    du changement d’accord

La tension peut être précédée d’un accord stable de *préparation* :

  - qui permet d’amener les notes dissonantes par mouvement conjoint,
    on a alors *préparation conjointe*

  - qui permet d’amener les notes dissonantes par un mouvement
    polyphonique élégant, on a alors *préparation polyphonique*

  - qui contient les futures notes dissonantes, on a alors
    *préparation par intégration*

On a donc le cycle générique :

#+begin_center
préparation  —  tension  —  résolution  — préparation  —  tension  — résolution  —  =...=
#+end_center

où les préparations sont facultatives. Lorsque l’accord de préparation
est omis, on dit que la dissonance est *attaquée*.

Remarquons que l’accord de résolution peut servir d’accord de
préparation à la tension suivante, formant ainsi un cycle :

#+begin_center
préparation —  tension  —  (résolution & préparation)  —  tension  — (résolution & préparation)  —  =...=
#+end_center


** Sensibles

La présence d’une sensible dans un accord provoque une tension qui
pousse cet accord à se résoudre sur un autre accord.

Une sensible, ou une sensible auxiliaire :

  - rend instable un accord qui ne comporte pourtant aucune dissonance constitutive
  - augmente l’instabilité d’un accord dissonant

#+begin_center
⁂
#+end_center

Les accords suivants contiennent une ou plusieurs tensions
mélodiques :

  - accords de dominante
  - accords de dominante auxiliaire avec sensible(s) auxiliaire(s)
  - accords napolitains
  - =...=


** Suppressions

Il est parfois souhaitable ou nécessaire de supprimer une des notes
d’un accord donné. L’effet obtenu dépendra du choix de cette note.


*** Accords parfaits

Plaçons-nous par exemple en tonique /do/ afin d’illustrer le propos,
et examinons les accords parfaits. Si nous supprimons la fondamentale
d’un accord du degré 1, on obtient un accord qui peut être analysé
comme étant du degré 3 :

#+ATTR_HTML: :class plat
| do mi sol | ⟼ | mi sol |

Nous obtenons alors l’effet particulier d’une fonction implicite de
tonique réalisée par un accord du degré 3. Plus généralement, le degré
est disposé à la tierce supérieure par rapport à la fonction tonale
implicite. Voyons à présent ce qui se passe si on supprime la tierce :

#+ATTR_HTML: :class plat
| do mi sol | ⟼ | do sol |

On supprime alors la médiante, qui détermine si le mode est majeur ou
mineur (/mi/ ou /mi^b/ dans notre exemple). Il en va de même pour la
dominante et la sous-dominante :

#+ATTR_HTML: :class plat
| sol si ré | ⟼ | sol ré |
| fa la do  | ⟼ | fa do  |

Il est donc tout à fait possible de supprimer la tierce afin de
produire volontairement un accord plus dépouillé, mais il faut savoir
que cette suppression va rendre le mode ambigu sur les degrés
principaux de la gamme. Voyons à présent ce qui se passe lorsqu’on
supprime la quinte :

#+ATTR_HTML: :class plat
| do mi sol | ⟼ | do mi |

La tonique et la médiante sont alors conservées.


*** Accords de dominante

Plaçons-nous par exemple en tonique /do/ afin d’illustrer le propos,
et examinons les accords suivant :

  - accord parfait du degré 5
  - septième de dominante
  - neuvième de dominante

Si nous supprimons la fondamentale d’un accord du degré 5, on obtient
des accords qui peuvent être analysés comme étant du degré 7 :

#+ATTR_HTML: :class plat
| sol si ré       | ⟼ | si ré       |
| sol si ré fa    | ⟼ | si ré fa    |
| sol si ré fa la | ⟼ | si ré fa la |

Nous obtenons alors l’effet particulier d’une fonction implicite de
dominante assurée par un degré 7. Voyons à présent ce qui se passe si
on supprime la tierce :

#+ATTR_HTML: :class plat
| sol si ré       | ⟼ | sol ré       |
| sol si ré fa    | ⟼ | sol ré fa    |
| sol si ré fa la | ⟼ | sol ré fa la |

On supprime alors la sensible inférieure, qui possède une importante
fonction de résolution sur la tonique (le /si/ est attiré par le /do/
dans notre exemple). Même en mineur, le degré 7 est fréquemment haussé
d’un demi-ton afin de le transformer en sensible.

Il est donc tout à fait possible de supprimer la tierce afin de
produire volontairement un accord plus dépouillé, mais il faut savoir
que cette suppression va diminuer la tension des accords de dominante.
Voyons à présent ce qui se passe lorsqu’on supprime la quinte :

#+ATTR_HTML: :class plat
| sol si ré       | ⟼ | sol si       |
| sol si ré fa    | ⟼ | sol si fa    |
| sol si ré fa la | ⟼ | sol si fa la |

La médiante et la sensible inférieure sont alors conservées. Supprimer
la septième de l’accord de neuvième :

#+ATTR_HTML: :class plat
| sol si ré fa la | ⟼ | sol si ré la |

diminue quelque peu la tension de l’accord de dominante, car la
sous-dominante est naturellement attirée par la médiante de résolution
(le /fa/ est attiré par le /mi/ dans notre exemple).


*** Accords à base de quintes

Pour les accords de double quinte et similaires, l’intervalle de
seconde entre la quarte et la quinte, ou entre la fondamentale et la
seconde contient la tension de l’accord. On peut la supprimer :

#+ATTR_HTML: :class plat
| do fa sol | ⟼ | do sol |
| do fa sol | ⟼ | do sol |
| do ré sol | ⟼ | do sol |
| do ré sol | ⟼ | ré sol |

mais on se retrouve alors avec un simple intervalle de quinte, ou
accord parfait sans tierce. On supprime du même coup la possibilité de
résolution vers un accord parfait. Dans le cas où cette résolution est
souhaitée, on supprimera plutôt la quinte :

#+ATTR_HTML: :class plat
| do fa sol | ⟼ | do fa |
| do ré sol | ⟼ | do ré |

ou la fondamentale :

#+ATTR_HTML: :class plat
| do fa sol | ⟼ | fa sol |
| do ré sol | ⟼ | ré sol |


*** Renversements

Les accords renversés ont généralement un caractère moins affirmé que
leurs homologues à l’état fondamental. Cette remarque est d’autant
plus vraie pour les triades. Afin de ne pas rendre leur fonction
tonale encore plus floue, on évite autant que possible de supprimer
une note d’une triade renversée.

Par contre, les accords renversés de quatre notes ou plus, et en
particulier la 7e et la 9e de dominante, peuvent s’employer sans
fondamentale ou sans quinte.


*** Conclusion

De façon générale, la richesse harmonique, le mode ou la tension d’un
accord sont tributaires au moins partiellement de la tierce.

Lorsqu’on souhaite conserver cette richesse, on préfère choisir la
quinte ou la fondamentale comme candidat à la suppression.

Si on souhaite par contre obtenir un effet de simplicité harmonique,
on supprime la tierce, mettant ainsi en évidence l’intervalle de
quinte. L’intervalle d’octave est également exposé si une doublure est
présente.


* Cycle tonal

#+TOC: headlines 1 local

** Introduction

Le *cycle tonal* est une suite d’accords dont les fondamentales
descendent le cycle des quintes :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 3 | 6 | 2 | 5 | 1 |

C’est ce cycle, répété en boucle, qui sert de fondation à la musique
tonale. Naturellement, de nombreuses variations de ce modèle se
succèdent afin d’en rompre la monotonie. Si les techniques permettant
de produire ces variations peuvent nous mener à des enchaînements
parfois très éloignés du cycle d’origine, elles respectent certains
principes :

  - il existe un lien entre les accords originaux et les modifications

  - l’accord final de chaque cycle fait en général fonction de tonique
    ou de dominante


** Suppression des doublons

Afin d’accentuer la continuité musicale, les accords intervenant en
double peuvent naturellement être simplifiés en un seul exemplaire.
Exemple :

#+ATTR_HTML: :class plat
| =...= | 5 | *1* | *1* | 4 | =...= | ⟼ | =...= | 5 | *1* | 4 | =...= |


** Substitution

Cette opération consiste à remplacer un accord du cycle par un autre.
On veille toutefois à ce que l’accord original et son remplaçant
présentent certaines caractéristiques communes. Voici les principaux
mécanismes de substitution :

  - substitution par un accord *synonyme* à l’accord original

  - substitution par un accord qui possède un *lien sémantique* avec
    l’accord original

  - substitution par une *fonction secondaire* transformant le degré
    suivant en tonique secondaire

  - substitution *polyphonique* : le nouvel accord établit des
    mouvements polyphoniques élégants avec les accords environnants


** Insertion

Cette opération consiste à insérer un nouvel accord entre deux accords
du cycle. On veille toutefois à ce que l’accord inséré présente
certaines caractéristiques communes avec au moins un des accords
environnants. Les techniques d’insertion sont similaires à celles
utilisées pour la substitution :

  - insertion d’un accord *synonyme* renforçant une fonction tonale
    environnante

  - insertion d’un accord possédant un *lien sémantique* avec un des
    accords environnants

  - insertion d’une *fonction secondaire* transformant le degré
    suivant en tonique secondaire

  - insertion *polyphonique* : le nouvel accord s’insère entre les
    accords environnants via des mouvements polyphoniques élégants

** Déviation

Cette opération consiste à dévier de trajectoire en créant un
raccourci dans le cycle tonal. On veille toutefois à ce que l’accord
de départ ait un lien avec l’accord d’arrivée :

  - *synonymes* : les accords de départ et d’arrivée sont synonymes

  - *sémantique* : la fonction tonale de l’accord de départ peut être
    réinterprétée en celle de l’accord d’arrivée

  - *enharmonique* : les accords de départ et d’arrivée sont
    enharmoniques

  - *polyphonique* : l’accord de départ peut évoluer vers l’accord
    d’arrivée via un mouvement polyphonique élégant

On ajoute à ces possibilités le *raccourci* menant de n’importe quel
accord du cycle *vers* une fonction de *dominante*.


*** Déviation enharmonique

À titre d’exemple de déviation enharmonique, plaçons-nous en /la
mineur/. L’accord de dominante sans fondamentale :

#+begin_center
sol^{#} si ré fa
#+end_center

est enharmonique à :

#+begin_center
la^b si ré fa
#+end_center

lui-même renversement de :

#+begin_center
si ré fa la^b
#+end_center

Ce dernier accord étant du degré 2, on peut créer un court-circuit
entre les degrés 7 et 2. Le cycle devient :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 2 | 5 | 1 |


** Figures de style

On peut imaginer d’autres types de modifications à apporter au cycle
tonal, en s’inspirant des [[file:litera-02-styleau.org][figures de style]] littéraires par exemple.


** Interprétation & réalisation

#+TOC: headlines 1 local

*** Introduction

Il existe de nombreuses interprétations du cycle tonal en terme de
fonctions, et chacune de ces interprétations peut être réalisées par
différentes suites d’accords. Nous disposons donc d’un système très
prolifique.


*** Degré 7 comme dominante

Voici un exemple d’interprétation du cycle tonal :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | T | T | Daux | D | T |

Le degré 7 y est considéré comme une dominante sans fondamentale et
les degrés 3 et 6 comme des accords de tonique. L’astuce est que nous
allons à présent oublier les degrés du cycle pour se concentrer sur
les fonctions :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |

Nous pouvons décider de réaliser ces fonctions par la suite
d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |
| 1 |  4 | 5 | 1 | 6 |    2 | 5 | 1 |

pour autant que chacun d’entre-eux mette en évidence la note tonale
correspondante, cela va de soi. Mais il existe d’autres possibilités
pour représenter cette suite de fonctions. Par exemple :

#+ATTR_HTML: :class plat
| 1 | 4 | 5 | 6 | 3 | 2 | 5 | 1 |

ou :

#+ATTR_HTML: :class plat
| 1 | 2 | 5 | 6 | 1 | 4 | 5 | 1 |


*** Degré 3 comme dominante

Si nous considérons que le degré 3 représente une dominante, nous
pouvons interpréter le cycle tonal de la façon suivante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | D | T | Daux | D | T |

qui peut par exemple se représenter par la suite d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | D | T | Daux | D | T |
| 1 |  4 | 7 | 5 | 6 |    2 | 5 | 1 |


*** Degrés 6 et 2 comme sous-dominante

Si nous considérons que les degrés 6 et 2 représentent une
sous-dominante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 |  6 |  2 | 5 | 1 |
| T | SD | D | T | SD | SD | D | T |

nous obtenons par exemple :

#+ATTR_HTML: :class plat
| T | SD | D | T | SD | SD | D | T |
| 1 |  2 | 5 | 1 |  6 |  4 | 5 | 1 |


*** Enchaînements fréquents

Nous constatons dans tous ces enchaînements que les suites de
fonctions :

#+ATTR_HTML: :class plat
| T | SD   | D | T |

et :

#+ATTR_HTML: :class plat
| T | Daux | D | T |

sont très fréquentes.


** Cycle plagal

Le *cycle plagal* est une suite d’accords dont les fondamentales
montent le cycle des quintes :

#+ATTR_HTML: :class plat
| 1 | 5 | 2 | 6 | 3 | 7 | 4 | 1 |

Il est moins utilisé que le cycle tonal. Les modifications qu’on peut
lui apporter sont analogues à celles du cycle tonal.


** Anatole

Parmi les suites d’accords courantes provenant des innombrables
variations du cycle tonal, citons l’ *anatole* :

#+ATTR_HTML: :class plat
| 6 | 2 | 5 | 1 |


* Polarisation secondaire

#+TOC: headlines 1 local

** Introduction

On parle de *polarisation secondaire* lorsqu’un ensemble d’accords
consécutifs remplissent des fonctions secondaires et mettent ainsi en
évidence l’existence d’une tonalité secondaire.

On choisit souvent une note tonale de la gamme principale comme
tonique de la tonalité secondaire. Placer la tonique secondaire sur la
tonique principale revient à identifier les deux gammes et n’apporte
aucun éclairage neuf. La dominante et la sous-dominante sont donc les
choix les plus courants de tonique secondaire.


** Dominante de la dominante

Nous avons déjà étudié en détail la dominante de la dominante, qui
n’est autre que la [[#section:dominanteAuxiliaire][dominante auxiliaire]], dans le chapitre consacré aux
accords classés.


** Dominante de la sous-dominante


*** Majeur

Nous allons à présent étudier la dominante de la sous-dominante.
Supposons par exemple que nous voulions renforcer le rôle de la
sous-dominante de /do majeur/, c’est-à-dire du /fa/. Notre accord doit
donc s’intégrer à la gamme de /fa majeur/, qui possède un
/si^b/ comme altération  :

#+begin_center
fa sol la si^b do ré mi fa
#+end_center

La dominante de cetta gamme étant le /do/, la première idée est
d’utiliser la triade :

#+begin_center
do mi sol
#+end_center

Malheureusement, cet accord ne met pas en évidence l’altération
/si^b/ et ne se différencie donc pas d’un accord parfait de
tonique de /do majeur/. On utilisera donc plutôt un accord d’au
minimum quatre notes :

#+begin_center
do mi sol si^b
#+end_center


*** Mineur

En mineur, les modifications sont un peu plus compliquées. Plaçons
nous dans la gamme de /la mineur harmonique/, et construisons la
dominante de la sous-dominante. La sous-dominante étant le /ré/, on
doit intégrer cet accord dans la gamme de /ré mineur harmonique/.
Comme nous sommes une quinte plus bas que le /la/, un /si^b/ apparaît,
auquel on doit ajouter la sensible inférieure /do^{#}/ du mineur
harmonique :

#+begin_center
ré mi fa sol la si^b do^{#} ré
#+end_center

La dominante de cette gamme étant le /la/, on utilisera donc :

#+begin_center
la do^{#} mi
#+end_center

ou :

#+begin_center
la do^{#} mi sol
#+end_center

Si on souhaite mettre l’altération /si^b/ en évidence, on utilisera
plutôt l’accord de cinq notes :

#+begin_center
la do^{#} mi sol si^b
#+end_center


* Dynamique des enchaînements

#+TOC: headlines 1 local

** Quarte et sixte

L’accord de quarte et sixte ne comporte que des notes consonantes, et
peut donc être considéré comme un accord consonant.

Il permet toutefois une résolution relative vers un accord encore plus
stable, à savoir l’accord parfait à l’état fondamental :

  - note de sixte ↦ note de quinte
  - note de quarte ↦  note de tierce

Exemple de résolution d’une 4te & 6te de fondamentale /fa/ :

#+ATTR_HTML: :class plat
| S | : | la | sol |
| A | : | fa | mi  |
| B | : | do | do  |

L’accord de 4te & 6te peut également être utilisé comme [[file:musica-03-clavier.org::#section:accordBroderie][accord broderie]].


** Septième de dominante

Les accords de dominante sont souvent enchaînés avec un accord de
tonique pour réaliser un couple tonal.

Dans cet exemple en /do majeur/, on voit que la 7e, le /fa/, se résout
en descendant sur la 3ce de l’accord de tonique, à savoir le /mi/ :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | /fa/ | /mi/ |
| T | : | ré   | do   |
| B | : | sol  | do   |

On note aussi que la 3ce de l’accord de dominante (le /si/ au soprano,
sensible inférieure de la gamme) se résout sur la fondamentale de
l’accord de tonique (le /do/, tonique de la gamme). Le triton /fa/ —
/si/ se résout donc vers la sixte /mi/ — /do/.


*** Préparation

Si l’on souhaite ajouter un accord de préparation contenant la 7e, on peut par
exemple choisir un accord de sous-dominante :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | do   | si   | do   |
| T | : | la   | ré   | do   |
| B | : | fa   | sol  | do   |

On peut aussi faire progresser l’alto du /la/ au /do/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | do   | ré   | do   |
| B | : | fa   | sol  | do   |

Ici, l’accord de préparation est une dominante auxiliaire :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | ré   | ré   | do   |
| B | : | fa   | sol  | do   |

Une variante où la quinte de l’accord de dominante est supprimée :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | ré   | sol  | sol  |
| B | : | fa   | sol  | do   |


*** Résolution irrégulière

Si on souhaite conserver les deux accords complets, on peut enchaîner
la 3ce de l’accord de dominante avec la 5te de l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | /fa/ | /mi/ |
| T | : | ré   | sol  |
| B | : | sol  | do   |

Notons toutefois que cela produit des quintes consécutives.

Une autre solution consiste à dévier la sensible inférieure de son
mouvement attendu vers la tonique, et la rediriger vers la 5te de
l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /si/ | /sol/ |
| A | : | /fa/ | /mi/  |
| T | : | ré   | do    |
| B | : | sol  | do    |

Enfin, on peut dévier la 7e et la 5te de l’accord de dominante :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/  |
| A | : | /fa/ | /sol/ |
| T | : | ré   | mi    |
| B | : | sol  | do    |


** Neuvième de dominante

Dans cet exemple en /do majeur/, la 9e de dominante est suivie par un
accord de tonique. On voit que la 9e, le /la/, se résout en descendant
sur la 5te de l’accord de tonique, à savoir le /sol/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | mi    |
| T | : | si   | do    |
| B | : | sol  | do    |

La 9e de dominante peut également se résoudre à l’intérieur d’un autre
accord de dominante. Voici par exemple une résolution d’une 9e de
dominante sans fondamentale vers une 7e de dominante complète,
toujours en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | fa    |
| T | : | ré   | ré    |
| B | : | si   | si    |

Le même cas en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/    | /mi/    |
| A | : | ré      | ré      |
| T | : | si      | si      |
| B | : | sol^{#} | sol^{#} |


** Dominante auxiliaire

Les accords de dominante auxiliaire peuvent subir des altérations qui
les rapprochent des notes tonales. Ces notes altérées se résolvent
alors naturellement sur les degrés correspondant :

| Résolution     | do majeur    | la mineur    |
|----------------+--------------+--------------|
| Vers dominante | fa^{#} ⟼ sol | ré^{#} ⟼ mi  |
|                | la^b ⟼ sol   | fa ⟼ mi      |
| Vers tonique   | si ⟼ do      | sol^{#} ⟼ la |
|                | ré^b ⟼ do    | si^b ⟼ la    |


** Septièmes d’espèces

Le choix le plus évident pour une septième d’espèce consiste à imiter
le couple tonal en enchaînant avec un accord situé une quinte plus
bas.

Dans cet exemple, qui enchaine un accord de /la/ avec un accord de
/ré/, on voit que la 7e, le /sol/, se résout en descendant vers le
/fa/ de l’accord suivant :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /fa/ |
| A | : | mi    | ré   |
| T | : | /do/  | /ré/ |
| B | : | la    | ré   |

On note aussi que la 3ce du premier accord (le /do/ au ténor) évolue
vers la fondamentale du deuxième accord (le /ré/).

Exemple avec un accord de préparation contenant la 7e :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /sol/ | /fa/ |
| A | : | mi    | mi    | ré   |
| T | : | si    | /do/  | /ré/ |
| B | : | sol   | la    | ré   |


** Accords à base de quintes

Un accord à base de quintes peut se résoudre sur l’octave de la
fondamentale, devenant ainsi une doublure :

#+ATTR_HTML: :class plat
| S | : | /si/ | /la/ |
| A | : | mi   | mi   |
| B | : | la   | la   |

ou sur la tierce de la fondamentale, devenant ainsi un accord parfait :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | mi   | mi   |
| B | : | la   | la   |

La fondamentale peut aussi glisser pour aboutir sur une doublure :

#+ATTR_HTML: :class plat
| S | : | si   | si   |
| A | : | mi   | mi   |
| B | : | /la/ | /si/ |

ou sur un accord parfait renversé :

#+ATTR_HTML: :class plat
| S | : | si   | si    |
| A | : | mi   | mi    |
| B | : | /la/ | /sol/ |

Enfin, la quinte de l’accord peut glisser pour obtenir un accord de
7e incomplet :

#+ATTR_HTML: :class plat
| S | : | fa   | fa   |
| A | : | /do/ | /ré/ |
| B | : | sol  | sol  |


*** Disposition en quartes

Le raisonnement est analogue pour les dispositions en quartes :

#+ATTR_HTML: :class plat
| S | : | fa    | fa   |
| A | : | do    | do   |
| B | : | /sol/ | /fa/ |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | fa    | fa   |
| A | : | do    | do   |
| B | : | /sol/ | /la/ |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /sol/ |
| A | : | do   | do    |
| B | : | sol  | sol   |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /mi/ |
| A | : | do   | do   |
| B | : | sol  | sol  |


* Dynamique des ornements

#+TOC: headlines 1 local


** Introduction

Une note ornementale peut être :

  - consonante, si elle peut s’interpréter comme note consonante de l’accord en cours
  - dissonante, sinon
    + note essentielle dissonante
    + note étrangère dissonante

Dans tous les cas, une note ornementale joue un rôle dynamique dans la
polyphonie. On utilise donc les termes de préparation et de résolution
pour toutes les notes ornementales :

  - la préparation est un accord qui prépare l’arrivée de la note ornementale
  - la résolution fait évoluer la note ornementale au sein d’un nouvel accord

Ces deux phases peuvent s’effectuer :

  - par mouvement conjoint
  - par intégration dans l’accord concerné
  - par mouvement polyphonique élégant

Ce processus est donc en tout point similaire à celui de la
préparation et de la résolution de dissonance.


** Accentuation

Les ornements harmoniques sont généralement placés sur temps fort ou
partie forte de temps.

Les ornements mélodiques sont généralement placés sur temps faible ou
partie faible de temps.


** Pédale

Lorsqu’une *pédale* est présente, elle est en général alternativement
dissonante et consonante par rapport aux accords qui se succèdent sur
les autres voix.

Une pédale est souvent préparée en s’intégrant à un premier accord et
en perdurant après sa disparition. Le dernier accord qui se superpose
à une pédale lui est en général également consonant.

Autrement dit, une pédale est généralement préparée et résolue par
intégration.


** Retard

Le retard se résout généralement en évoluant par mouvement conjoint
vers une note du nouvel accord. Par définition, un retard est préparé
par intégration.

Suivant le sens du mouvement, on distingue :

  - le *retard supérieur* qui se résout en descendant
  - le *retard inférieur* qui se résout en montant

Par exemple, dans l’enchaînement suivant, le /ré/ au soprano est un
retard supérieur qui se résout en descendant vers le /do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /do/ |
| A | : | la   | sol  | sol  |
| T | : | fa   | mi   | mi   |
| B | : | ré   | do   | do   |

Autre exemple où le /ré/ est un retard inférieur qui se résout en
montant vers le /mi/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /mi/ |
| A | : | la   | la   | la   |
| B | : | fa   | do   | do   |


** Anticipation

L’anticipation se résout par intégration dans l’accord suivant. Par
exemple, dans l’enchaînement suivant, le /mi/ au soprano est une
ancicipation :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


** Appogiature

Contrairement au retard qui est préparé par intégration, l’appogiature
est purement et simplement attaquée.

L’appogiature se résout généralement en évoluant par mouvement
conjoint vers une note de l’accord.


* Dynamique du rythme

#+TOC: headlines 1 local

** Introduction

Le rythmes les plus stables sont les *rythmes réguliers* :

  - *rapides*, avec au moins une note par temps
  - *lents*, avec de longues notes continues

Tous les autres rythmes correspondent à des tensions qui peuvent se
résoudre sur l’une ou l’autre de ces configurations. Il va de soi que
les rythmes lents sont plutôt réservés à la fin d’une phrase et les
rythmes rapides au coeur d’un mouvement.


** Mesures

Une mesure irrégulière constitue une tension par rapport à une mesure
régulière proche.


** Fluidité

Un rythme sec produit une tension par rapport à un rythme fluide qui
lui est proche. Par exemple, la suite :

#+ATTR_HTML: :class plat
| C cs C | cs N N |

produira une tension puis une détente, et la suite :

#+ATTR_HTML: :class plat
| C cs N | C cs N | =...= |

un cycle de tension et de détente.


** Syncopes

Le schéma générique d’une syncope applique la structure générique de
tension et résolution. En voici un exemple :

  - *Préparation* : rythme régulier, à raison d’une note par temps

  - *Tension* : on gomme la première note de la mesure suivante en la
    remplaçant par la prolongation de la note précédente

  - *Résolution* : la mélodie reprend le rythme régulier précédent, à
    raison d’une note par temps

Toutes les variations partant de ce cas d’école sont bien entendu
possibles. La phase de préparation est bien entendu optionnelle.

Voici des exemples de réalisation où la mesure compte deux temps d’une
noire chacun :

|         | Préparation | Tension     | Résolution |
|---------+-------------+-------------+------------|
| Syncope | N N         | N N‿N N     | N N        |
| Syncopé | N N         | N N‿N N‿N N | N N        |


*** Contraste

Il arrive souvent qu’on mette en relief une syncope en introduisant un
contraste entre la voix syncopée et une voix sans syncope qui assure
la régularité rythmique. Dans ce cas, la tension découle naturellement
du contraste.


** Contretemps

On peut considérer qu’une syncope est un rythme fluide et que le
contretemps est le rythme sec associé. Par conséquent, le contretemps
offre une tension rythmique encore plus importante que celle de la
syncope. On peut imaginer un prototype de tension — relaxation :

  - Rythme régulier de préparation, une note par temps

  - Tension : syncope

  - Tension accrue : contretemps associé

  - Légère détente : retour à la syncope

  - Détente finale : retour au rythme régulier

chaque étape étant optionnelle.


* Stratification

#+TOC: headlines 1 local


** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique
tonalité, on parle de *musique tonale*. Il existe donc à tout moment
un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.


** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre tonalité, distincte
de celles des autres groupes, on parle de musique polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.


** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.


** Polyrythmie

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de *polymétrie* ou de *rythmes polymétriques*.


**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| X | : | § | χ | ¶ | χ | ¶ | χ |
| Y | : | § | χ | χ | ¶ | χ | χ |
