
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 05 : Tablature
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Tonalité

#+TOC: headlines 1 local

** Introduction

L’association d’une tonique et d’un mode est appelée *tonalité*.

On parlera par exemple de la tonalité de :

  - do ionien
  - la éolien
  - etc


** Intérieur & extérieur

La tonalité détermine les notes et les altérations de la gamme
utilisée.

On dit qu’une note, diatonique ou altérée, est *dans la tonalité* si
elle fait partie de la gamme determinée par la tonalité.

On dit qu’une note, diatonique ou altérée, est *en dehors de la
tonalité* si elle ne fait pas partie de la gamme detérminée par la
tonalité.


** Notes tonales

Quelle est la différence entre une gamme et une tonalité ? Toutes deux
sont définies par une tonique et un mode, mais la tonalité possède en
plus une hiérarchie entre les degrés qui la constituent.

Les *notes tonales* sont les notes les plus importantes de la gamme, à
savoir la tonique et les degrés qui l’entourent dans le cycle des
quintes :

#+ATTR_HTML: :class plat
| noms   | : | sous-dominante | <— | 5te | —> | tonique | <— | 5te | —> | dominante |
| degrés | : |              4 | <— | 5te | —> |       1 | <— | 5te | —> |         5 |


Un *degré fort*, ou *degré tonal*, est un degré qui correspond à une
note tonale. Les degrés 4, 1, 5 sont donc les degrés forts de la
tonalité.

Les autres degrés sont appelés *degrés faibles*.

On a donc la hiérarchie :

#+ATTR_HTML: :class plat
| degrés forts   | : |   | 4 |   | 1 |   | 5 |   |
| degrés faibles | : | 2 |   | 6 |   | 3 |   | 7 |


** Intervalles justes

Les notes tonales sont généralement séparées de la tonique par les
intervalles justes de la gamme :

| Note 1  | Note 2         | Intervalle      |
|         |                | à l’octave près |
|---------+----------------+-----------------|
| tonique | tonique        | unisson         |
| tonique | dominante      | quinte          |
| tonique | sous-dominante | quarte          |

Il existe toutefois quelques exceptions. Ainsi, la dominante de la
gamme de /si locrien/ forme un intervalle de quinte diminuée avec la
tonique, raison pour laquelle le mode locrien est peu utilisé.


** Accords

Considérons les accords de trois notes construits en prenant les notes
tonales comme fondamentales :

| Note tonale    | Degrés        | Exemple      |
|                | dans l’accord | tonique = do |
|----------------+---------------+--------------|
| tonique        | 1 3 5         | do mi sol    |
| dominante      | 5 7 2         | sol si ré    |
| sous-dominante | 4 6 1         | fa la do     |

On constate que l’on retrouve toutes les notes de la gamme.


* Fonctions tonales

#+TOC: headlines 1 local

** Introduction

Une *fonction tonale* est une fonction musicale réalisée à la fois par :

  - une note tonale
  - un accord mettant en évidence cette note tonale

La musique utilisant les fonctions tonales est appelée *musique tonale*.


** Tonique

En tant que note la plus importante de la gamme, la tonique assure
aussi la première fonction tonale.

La tonique est la fonction sur laquelle la musique effectue ses pauses
les plus importantes.


** Dominante

La musique tonale s’articule autour de la dualité qui existe entre la
tonique, fonction de repos, et la dominante, fonction dynamique autour
de laquelle la musique peut se développer. Il arrive également que la
musique effectue des pauses à la dominante, mais ce sont là des arrêts
nettement moins appuyés que ceux effectués sur la tonique.

La dominante est naturellement attirée par la tonique, et peut :

  - répondre à son appel, ce qui détent la musique
  - ne pas y répondre et repartir vers une autre idée

La dominante constitue donc la fonction tonale la plus importante avec
la tonique.


** Sous-dominante

La sous-dominante constitue la fonction tonale la plus importante
après la tonique et la dominante.


** Tableau récapitulatif

| Degrés | Fonctions            | Abréviations |
|--------+----------------------+--------------|
|      4 | sous-dominante       | SD           |
|      1 | tonique              | T            |
|      5 | dominante            | D            |


* Modes majeur et mineur

#+TOC: headlines 1 local

** Introduction

Le tableau suivant regroupe les accords de trois notes générés par les
degrés des modes naturels. La lettre *M* signifie accord parfait
majeur et la lettre *m* accord parfait mineur. Le symbole *dim*
signifie ici accord de quinte diminuée :

| Modes      |     | Degrés |     |     |     |     |     |     |
|            |     | 4      | 1   | 5   | 2   | 6   | 3   | 7   |
|------------+-----+--------+-----+-----+-----+-----+-----+-----|
| lydien     | fa  | dim    | M   | M   | M   | m   | m   | m   |
| ionien     | do  | M      | M   | M   | m   | m   | m   | dim |
| mixolydien | sol | M      | M   | m   | m   | m   | dim | M   |
| dorien     | ré  | M      | m   | m   | m   | dim | M   | M   |
| éolien     | la  | m      | m   | m   | dim | M   | M   | M   |
| phrygien   | mi  | m      | m   | dim | M   | M   | M   | m   |
| locrien    | si  | m      | dim | M   | M   | M   | m   | m   |

Parmi les modes naturels, les modes ionien et éolien sont les seuls à
présenter le même type d’accords sur les degrés forts 4, 1, 5. Le mode
ionien produit des accords parfaits majeurs, tandis que le mode éolien
produit des accords parfaits mineurs :

| Modes  | Degrés |   |   |
|        | 4      | 1 | 5 |
|--------+--------+---+---|
| ionien | M      | M | M |
| éolien | m      | m | m |

Pour cette raison :

  - le mode ionien est aussi appelé *mode majeur*
  - le mode éolien est aussi appelé *mode mineur*

Exemple de mode majeur avec la gamme de /do majeur/ :

#+begin_center
do ré mi fa sol la si do
#+end_center

Exemple de mode mineur avec la gamme de /la mineur/ :

#+begin_center
la si do ré mi fa sol la
#+end_center


** Tonalités modèles

La tonalité modèle du mode :

  - majeur correspond à la gamme modèle du mode ionien
  - mineur correspond à la gamme modèle du mode éolien

| Mode   | Nom médiéval | Tonalité modèle          |
|--------+--------------+--------------------------|
| majeur | ionien       | do ré mi fa sol la si do |
| mineur | éolien       | la si do ré mi fa sol la |


** Adaptations du mineur

#+TOC: headlines 1 local

*** Mineur harmonique

Le mode majeur dispose d’une sensible inférieure. Par exemple, en /do
majeur/, la sensible inférieure est le /si/, à un demi-ton de la
tonique /do/.

En mode mineur par contre, les degrés 2 et 7 sont situés à un ton
entier de la tonique : ce mode ne possède donc pas de sensible. On
peut toutefois y remédier en haussant la sous-tonique d’un demi-ton,
obtenant ainsi un mode dérivé, appelé *mode mineur harmonique*. Par
exemple, en /la mineur/, le /sol/ sera haussé d’un demi-ton, donnant
ainsi la gamme :

#+begin_center
la si do ré mi fa sol^{#} la
#+end_center

Dans la suite, le mode mineur par défaut sera généralement le mode
mineur harmonique.


*** Mineur ascendant et descendant

Le mode mineur harmonique sonne très bien, disposant à la fois de la
sonorité du mode mineur et de l’attirance de la sensible inférieure.
Cependant, l’écart de seconde augmentée entre les degrés 6 et 7 n’est
pas toujours souhaitable. Dans ce cas, on hausse le degré 6, obtenant
un mode appelé *mode mineur ascendant*. Exemple, le /la mineur
ascendant/ :

#+begin_center
la si do ré mi fa^{#} sol^{#} la
#+end_center

Par opposition, on appelle alors *mode mineur descendant* le mode
mineur naturel (le mode éolien). En pratique, les modes mineurs
(harmonique, ascendant et descendant) sont souvent mêlés, donnant
ainsi beaucoup de couleur et de souplesse à la musique. Enfin, le
degré 3 peut lui aussi être haussé d’un demi-ton, complétant ainsi le
caractère polymorphe du mode mineur, qui peut se rapprocher ou même se
confondre avec le mode majeur.


*** Conclusion

Le mode mineur est très versatile, et ses altérations flottantes
donnent une couleur particulière à la musique.


** Degrés & intervalles caractéristiques

Les modes majeur et mineur sont les modes les plus utilisés. On s’en
sert donc comme référence pour souligner les *degrés caractéristiques*
des autres modes. Ces degrés forment des *intervalles
caractéristiques* avec la tonique.


*** Autour du mode majeur

En partant de /do majeur/, les quintes voisines nous donnent les
gammes de /sol mixolydien/ et /fa lydien/.

Si nous transposons la gamme de /sol mixolydien/ vers la tonique /do/,
nous obtenons la gamme de /do mixolydien/ :

#+begin_center
do ré mi fa sol la /si^b/ do
#+end_center

La note caractéristique du mode mixolydien est donc le /si^b/,
septième degré formant un intervalle de septième mineure avec la
tonique.

Si nous transposons la gamme de /fa lydien/ vers la tonique /do/,
nous obtenons la gamme de /do lydien/ :

#+begin_center
do ré mi /fa^{#}/ sol la si do
#+end_center

La note caractéristique du mode lydien est donc le /fa^{#}/, quatrième
degré formant un intervalle de quarte augmentée avec la tonique.


*** Autour du mode mineur

En partant de /la mineur/, les quintes voisines nous donnent les
gammes de /mi phrygien/ et /ré dorien/.

Si nous transposons la gamme de /mi phrygien/ vers la tonique /la/,
nous obtenons la gamme de /la phrygien/ :

#+begin_center
la /si^b/ do ré mi fa sol la
#+end_center

La note caractéristique du mode phrygien est donc le /si^b/, deuxième
degré formant un intervalle de seconde mineure avec la tonique.

Si nous transposons la gamme de /ré dorien/ vers la tonique /la/, nous
obtenons la gamme de /la dorien/ :

#+begin_center
la si do ré mi /fa^{#}/ sol la
#+end_center

La note caractéristique du mode dorien est donc le /fa^{#}/, sixième
degré formant un intervalle de sixte majeure avec la tonique.

Nous n’avons pas encore exploré le mode locrien. Partons de la gamme
de /si locrien/ et transposons vers la tonique /la/, deux quintes plus
bas. Nous obtenons la gamme de /la locrien/ :

#+begin_center
la si^b do ré mi^b fa sol la
#+end_center

Les notes caractéristiques du mode locrien sont donc le /si^b/ et le
/la^b/, deuxième et cinquième degré formant des intervalles de seconde
mineure et quinte diminuée avec la tonique.


*** Récapitulation

| Modes           |           Degré | Intervalle      |
|                 | caractéristique | caractéristique |
|-----------------+-----------------+-----------------|
| lydien          |               4 | 4te augmentée   |
| ionien (Majeur) |                 | —               |
| mixolydien      |               7 | 7e mineure      |
|-----------------+-----------------+-----------------|
| dorien          |               6 | 6te majeure     |
| éolien (Mineur) |                 | —               |
| phrygien        |               2 | 2de mineure     |
|-----------------+-----------------+-----------------|
| locrien         |               2 | 2de mineure     |
|                 |               5 | 5te diminuée    |


* Autres modes

#+TOC: headlines 1 local

** Introduction

Nous avons déjà vu les modes naturels, le majeur et le mineur. Ce
chapitre recense les autres modes disponibles.


** Construire de nouveaux modes

La technique la plus simple consiste à construire les gammes relatives
d’un mode existant. Chaque nouvelle gamme ainsi obtenue peut alors
être considérée comme la gamme modèle d’un nouveau mode.

Chaque mode heptaphonique nous donnera ainsi six nouveaux modes,
construits à partir des degrés 2 à 7.

Chaque mode pentaphonique nous donnera ainsi quatre nouveaux modes,
construits à partir des degrés 2 à 5.

Chaque mode tetraphonique nous donnera ainsi trois nouveaux modes,
construits à partir des degrés 2 à 4.


** Heptaphoniques

#+TOC: headlines 1 local

*** Acoustique

Le mode acoustique est construit à partir des premiers éléments de la
série des harmoniques naturelles. Exemple en partant de /do/ :

#+ATTR_HTML: :class plat
| /Notes/ | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |


En ramenant toutes les notes dans la même octave, on obtient :

#+begin_center
do ré mi fa^{#} sol si^b do
#+end_center

Ce mode contient donc une quinte, une tierce majeure, une septième
mineure, une seconde majeure et une quarte augmentée.

On peut bien entendu ajouter la note naturelle manquante, à savoir
le /la/ :

#+begin_center
do ré mi fa^{#} sol la si^b do
#+end_center

La gamme ainsi obtenue possède les mêmes écarts qu’un relatif du mode
mineur ascendant à partir du quatrième degré :

#+begin_center
ré mi fa^{#} sol^{#} la si do ré
#+end_center


*** Superlocrien

Le mode superlocrien est construit comme un relatif du mode mineur
ascendant à partir du septième degré :

#+begin_center
sol^{#} la si do ré mi fa^{#} sol^{#}
#+end_center

Ce mode est appelé superlocrien, car il ressemble fort au mode
locrien. On le voit clairement en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la si
#+end_center


**** Mineur harmonique

Il existe aussi une variante dérivée du mode mineur harmonique :

#+begin_center
sol^{#} la si do ré mi fa sol^{#}
#+end_center

ce qui donne, en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la^b si
#+end_center


*** Tzigane

Le mode tzigane, ou mode hongrois, est un mode dérivé du mineur
harmonique, le 4e degré étant haussé afin de se rapprocher de la
dominante :

#+begin_center
la si do ré^{#} mi fa sol^{#} la
#+end_center

Ce mode est caractérisé par la présence de deux sensibles auxiliaires :

#+begin_center
sensible auxiliaire inférieure —> dominante <— sensible auxiliaire supérieure
#+end_center

Notons les deux écarts de trois demi-tons entre les degrés 3 - 4 et
6 - 7.


*** Andalou

Le mode andalou ressemble au mode phrygien, mais il est caractérisé
par une médiante flottante, formant une tierce majeure ou mineure avec
la tonique :

#+begin_center
mi fa sol^{(#)} la si do ré mi
#+end_center


*** Napolitain

Il s’agit d’un mode ressemblant au mode phrygien, mais où le septième
degré est haussé d’un demi-ton, ce qui le transforme en sensible
inférieure :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

On voit que la sus-tonique est une sensible supérieure. Ce mode est
donc caractérisé par la double attraction :

#+begin_center
sensible inférieure —> tonique <— sensible supérieure
#+end_center

Il en existe une variante où le sixième degré est haussé :

#+begin_center
mi fa sol la si do^{#} ré^{#} mi
#+end_center


*** Oriental


**** Variante phrygienne

Le mode oriental phrygien est un relatif du mode tzigane construit à
partir du cinquième degré :

#+begin_center
mi fa sol^{#} la si do ré^{#} mi
#+end_center

Ce mode est caractérisé par les deux secondes augmentées qui séparent
les degrés 2 — 3 et 6 — 7, ainsi que par la double attraction :

#+begin_center
sensible inférieure —> tonique <— sensible supérieure
#+end_center

Si on souhaite également créer une double attraction vers la
dominante :

#+begin_center
sous-dominante altérée —> dominante <— sous-médiante
#+end_center

il suffit de hausser le degré 4 :

#+begin_center
mi fa sol^{#} la^{#} si do ré^{#} mi
#+end_center


**** Variante locrienne

Le mode oriental locrien est un relatif du mode tzigane construit à
partir du deuxième degré :

#+begin_center
si do ré^{#} mi fa sol^{#} la si
#+end_center

Afin d’obtenir la même propriété de double attraction que la variante
basée sur le mode de /mi/, on peut sensibiliser le degré 7 en le
haussant d’un demi-ton :

#+begin_center
si do ré^{#} mi fa sol^{#} la^{#} si
#+end_center


** Pentaphoniques

Les modes pentaphoniques sont des gammes de cinq notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
cinq quintes :

#+begin_center
do sol ré la mi
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode pentaphonique :

#+begin_center
do ré mi sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do  | ré | mi  | sol |
| sur ré  | : | ré  | mi  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré  | mi | sol | la  |
| sur mi  | : | mi  | sol | la  | do | ré  | mi  |


*** Avec caractéristique

Ce sont des modes pentaphoniques que l’on altère afin d’intégrer une
ou plusieurs notes caractéristiques des modes naturels. Par exemple,
ce mode pentaphonique altéré :

#+begin_center
ré mi sol^{#} la do ré
#+end_center

possède une quarte haussée, caractéristique du mode lydien.


*** Blues

Le mode blues est un mode pentaphonique développant les quintes à
partir de la médiante. La médiante, la dominante et la sous-tonique
sont flottantes. Par exemple, avec /la/ comme tonique, nous avons :

#+begin_center
la do^{(#)} ré mi^{(b)} sol^{(#)} la
#+end_center


*** Chinois

Le mode chinois est un mode pentaphonique développant les quintes à
partir de la tonique. Par exemple, avec /do/ comme tonique, nous
obtenons :

#+begin_center
do ré mi sol la do
#+end_center


*** Japonais

Le mode japonais est un mode pentaphonique développant les quintes à
partir de la sous-dominante. La gamme modèle de ce mode possède un
/mi/ pour tonique. On part alors de la sous-dominante /la/ et on
gravit les quintes entre notes naturelles :

#+begin_center
la mi si fa do
#+end_center

En disposant ces notes sur une octave /mi — mi^{+1}/ et en les
ordonnant de la plus grave à la plus aiguë, nous obtenons :

#+begin_center
mi fa la si do mi
#+end_center

La dominante auxiliaire /fa/ est une sensible supérieure. Ce mode
possède un autre demi-ton entre la dominante /si/ et la sous-médiante
/do/.

Notons également l’intervalle de quarte augmentée /si — fa/ qui sépare
la sus-tonique de la dominante.


** Tétraphoniques

Les modes tetraphoniques sont des gammes de quatre notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
quatre quintes :

#+begin_center
do sol ré la
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode tetraphonique :

#+begin_center
do ré sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do | ré  | sol |
| sur ré  | : | ré  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré | sol | la  |


* Accords classés

#+TOC: headlines 1 local


** Introduction

Les accords classés sont des accords naturellement engendrés par les
gammes lorsqu’on y superpose des tierces.


*** Nomenclature

Une *septième de dominante* est un accord de quatre notes dont la
fondamentale est placée sur la dominante.

Une *septième d’espèce* est un accord de quatre notes dont la
fondamentale n’est pas placée sur la dominante.

On utilise les abréviations suivantes :

| Accord                | Abréviation |
|-----------------------+-------------|
| septième de dominante | 7e D        |
| septième d’espèce     | 7e E        |


** Tonique

Les accords de tonique les plus utilisés sont des accords parfaits
majeur ou mineur. On rencontre aussi des septièmes d’espèce, comme
dans ces exemples :

| Accords             | Abréviations | Exemples             |                  |
|                     |              | Gammes               | Accords          |
|---------------------+--------------+----------------------+------------------|
| septième majeure    | 7e M         | do majeur            | do mi sol si     |
| septième mineure    | 7e m         | la mineur            | la do mi sol     |
| septième harmonique | 7e h         | la mineur harmonique | la do mi sol^{#} |

et plus rarement des accords de 5, 6 ou 7 notes.


*** Quinte augmentée

Si nous supprimons la fondamentale de l’accord de septième harmonique,
nous obtenons un accord dit de *quinte augmentée* :

| Accords          | Abréviations | Exemples      |
|------------------+--------------+---------------|
| quinte augmentée | 5te aug      | do mi sol^{#} |


** Dominante

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante sont très importants, de par leur fonction
tonale dynamique et parce qu’ils sont naturellement attirés par un
accord de tonique.


*** Triades

En empilant deux tierces, on obtient un accord parfait majeur, que ce
soit en mode majeur ou mineur harmonique :

| Accords        | Abréviations | Exemples             |               |
|                |              | Gammes               | Accords       |
|----------------+--------------+----------------------+---------------|
| parfait majeur | M            | do majeur            | sol si ré     |
| parfait majeur | M            | la mineur harmonique | mi sol^{#} si |


*** Septième

En empilant trois tierces, on obtient l’accord de septième de
dominante, dont la structure est identique en majeur et en mineur
harmonique :

| Accords               | Abréviations | Exemples             |                  |
|                       |              | Gammes               | Accords          |
|-----------------------+--------------+----------------------+------------------|
| septième de dominante | 7e D         | do majeur            | sol si ré fa     |
| septième de dominante | 7e D         | la mineur harmonique | mi sol^{#} si ré |

Dans les deux cas :

  - la première tierce est majeure
  - les deux tierces suivantes sont mineures

Avec les accords parfaits majeur et mineur, la septième de dominante
figure parmi les accords les plus importants de l’harmonie tonale.


**** Quinte diminuée

Lorsqu’on prive un accord de dominante de sa fondamentale, on obtient
un accord de *quinte diminuée* :

| Accords         | Abréviations | Exemples             |               |
|                 |              | Gammes               | Accords       |
|-----------------+--------------+----------------------+---------------|
| quinte diminuée | 5te dim      | do majeur            | si ré fa      |
| quinte diminuée | 5te dim      | la mineur harmonique | sol^{#} si ré |


*** Neuvième

En empilant quatre tierces, on obtient la *neuvième de dominante*,
majeure ou mineure suivant le mode :

| Accords                       | Abréviations | Exemples             |                     |
|                               |              | Gammes               | Accords             |
|-------------------------------+--------------+----------------------+---------------------|
| neuvième de dominante majeure | 9e D M       | do majeur            | sol si ré fa la     |
| neuvième de dominante mineure | 9e D m       | la mineur harmonique | mi sol^{#} si ré fa |


**** Septième et quinte diminuée

Lorsqu’on prive une neuvième de dominante majeure de sa fondamentale,
on obtient un accord de *septième et quinte diminuée* :

| Accords                     | Abréviations | Exemples  |             |
|                             |              | Gammes    | Accords     |
|-----------------------------+--------------+-----------+-------------|
| septième et quinte diminuée | 7e & 5te dim | do majeur | si ré fa la |


**** Septième diminuée

Lorsqu’on prive une neuvième de dominante mineure de sa fondamentale,
on obtient un accord de *septième diminuée* :

| Accords           | Abréviations | Exemples             |                  |
|                   |              | Gammes               | Accords          |
|-------------------+--------------+----------------------+------------------|
| septième diminuée | 7e dim       | la mineur harmonique | sol^{#} si ré fa |


** Sous-dominante

Les accords de sous-dominante sont similaires aux accords de tonique :
accords parfaits et septièmes majeures ou mineures. Exemples :

| Accords | Exemples  |             |
|         | Gammes    | Accords     |
|---------+-----------+-------------|
| 7e M    | do majeur | fa la do mi |
| 7e m    | la mineur | ré fa la do |


** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: heading:dominanteAuxiliaire
:END:

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante auxiliaire sont similaires aux accords de
dominante, si ce n’est qu’ils sont construits sur le degré 2 de la
gamme. Afin de renforcer le rôle de ces accords, il est possible de
les altérer en faisant /comme si/ la dominante de la gamme courante
devenait la tonique. On utilise les abréviations :

| Accords                          | Abréviations |
|----------------------------------+--------------|
| triade de dominante auxiliaire   | 3ade Daux    |
| septième de dominante auxiliaire | 7e Daux      |
| neuvième de dominante auxiliaire | 9e Daux      |


*** Majeur

Nous prenons comme illustration la gamme de /do majeur/. Nous obtenons
par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| do ré mi fa sol la si do | —> | sol la si do ré mi fa^{#} sol |

L’altération haussière du /fa^{#}/ (degré 4 par rapport à la tonique
/do/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /sol/.

On peut également altérer le /la/ (degré 6 par rapport à la tonique
/do/) vers le bas afin de le transformer en sensible auxiliaire
supérieure. Nous avons alors la gamme :

#+begin_center
sol la^b si do ré mi fa^{#} sol
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en do majeur |
|-------------------------+-----------+-----------------------|
| aucune                  | 3ade Daux | ré fa la              |
|                         | 7e Daux   | ré fa la do           |
|                         | 9e Daux   | ré fa la do mi        |
| inférieure              | 3ade Daux | ré fa^{#} la          |
|                         | 7e Daux   | ré fa^{#} la do       |
|                         | 9e Daux   | ré fa^{#} la do mi    |
| inférieure & supérieure | 3ade Daux | ré fa^{#} la^b        |
|                         | 7e Daux   | ré fa^{#} la^b do     |
|                         | 9e Daux   | ré fa^{#} la^b do mi  |


*** Mineur harmonique

Nous prenons comme illustration la gamme de /la mineur harmonique/.
Nous obtenons par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| la si do ré mi fa sol^{#} la | —> | mi fa^{#} sol la si do ré^{#} mi |

L’altération haussière du /ré^{#}/ (degré 4 par rapport à la tonique
/la/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /mi/.

Si on supprime l’altération haussière du /fa^{#}/ (degré 6 par rapport
à la tonique /la/), on transforme ce degré en sensible auxiliaire
supérieure de la dominante /mi/. Nous obtenons alors la gamme :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en la mineur harmonique |
|-------------------------+-----------+----------------------------------|
| supérieure              | 2ade Daux | si ré fa                         |
|                         | 7e Daux   | si ré fa la                      |
|                         | 9e Daux   | si ré fa la do                   |
| inférieure              | 3ade Daux | si ré^{#} fa^{#}                 |
|                         | 7e Daux   | si ré^{#} fa^{#} la              |
|                         | 9e Daux   | si ré^{#} fa^{#} la do           |
| inférieure & supérieure | 3ade Daux | si ré^{#} fa                     |
|                         | 7e Daux   | si ré^{#} fa la                  |
|                         | 9e Daux   | si ré^{#} fa la do               |

Remarquons en passant que la triade de dominante auxiliaire non
altérée est un accord de quinte diminuée.


*** Sans fondamentale

Tout comme les accords de dominante, les accords de dominante
auxiliaire sont parfois présentés sans leur fondamentale. On obtient
alors des accords qui semblent être du degré 4, les fonctions de
dominante auxiliaire et de sous-dominante se voyant ainsi intimement
liées.

Exemple en /do majeur/ :

| Sensibles auxiliaires   | Accords | Exemples en do majeur |
|-------------------------+---------+-----------------------|
| aucune                  | 7e Daux | fa la do              |
|                         | 9e Daux | fa la do mi           |
| inférieure              | 7e Daux | fa^{#} la do          |
|                         | 9e Daux | fa^{#} la do mi       |
| inférieure & supérieure | 7e Daux | fa^{#} la^b do        |
|                         | 9e Daux | fa^{#} la^b do mi     |

Exemple en /la mineur harmonique/ :

| Sensibles auxiliaires   | Accords | Exemples en la mineur harmonique |
|-------------------------+---------+----------------------------------|
| supérieure              | 7e Daux | ré fa la                         |
|                         | 9e Daux | ré fa la do                      |
| inférieure              | 7e Daux | ré^{#} fa^{#} la                 |
|                         | 9e Daux | ré^{#} fa^{#} la do              |
| inférieure & supérieure | 7e Daux | ré^{#} fa la                     |
|                         | 9e Daux | ré^{#} fa la do                  |


*** Sixtes augmentées

#+TOC: headlines 1 local

**** Introduction

Les accords de *sixte augmentée* sont des accords de dominante
auxiliaire renversés. Ils sont altérés de sorte qu’ils présentent un
intervalle caractéristique de sixte augmentée, d’où leur nom.


**** Sixte française

La *sixte française* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est présentée sous la forme d’un
second renversement.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| ré fa^{#} la^b do | —> | la^b do ré fa^{#} |

En /la mineur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| si ré^{#} fa la | —> | fa la si ré^{#} |


**** Sixte italienne

La *sixte italienne* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (ré) fa^{#} la^b do | —> | la^b do (ré) fa^{#} |

ce qui nous donne finalement :

#+begin_center
la^b do fa^{#}
#+end_center

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la | —> | fa la (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la ré^{#}
#+end_center


**** Sixte allemande

La *sixte allemande* est une neuvième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la do | —> | fa la do (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la do ré^{#}
#+end_center

L’accord altéré de /do majeur/ respectant les mêmes écarts s’écrit :

#+begin_center
la^b do mi^b fa^{#}
#+end_center


** Emprunts

#+TOC: headlines 1 local

*** Introduction

Un emprunt est un accord provenant d’une autre gamme (tonique et/ou
mode) que l’on insère dans la gamme courante.


*** Majeur <——> Mineur

On peut placer des accords caractéristiques du mineur (quintes
augmentées, septièmes diminuées, ...) dans des gammes majeures, ou
l’inverse.


*** Tierces picardes

Une *tierce picarde* est un accord parfait majeur intégré à un autre
mode. On la rencontre souvent sur les degrés 1, 5, ou 4 du mode
mineur : la tierce de l’accord y est rendue majeure par une altération
haussière. Voici des exemples en /la mineur/ :

| Degrés | Exemples      |
|--------+---------------|
|      1 | la do^{#} mi  |
|      4 | ré fa^{#} la  |
|      5 | mi sol^{#} si |


*** Napolitain

En gamme de /mi napolitain/, l’accord de dominante auxiliaire non
altéré :

#+begin_center
fa la do
#+end_center

est un accord parfait majeur situé un demi-ton au-dessus de la tonique
/mi/. Par extension, on appelle accord *napolitain* tout accord défini
par les mêmes propriétés, et ce quels que soient le mode et la
tonique. Voici ce que cela donne en majeur et en mineur :

| do majeur    | la mineur  |
|--------------+------------|
| ré^b fa la^b | si^b ré fa |

Lorsque cet accord est présenté sous la forme de premier renversement,
il est appelé *sixte napolitaine* :

| do majeur    | la mineur  |
|--------------+------------|
| fa la^b ré^b | ré fa si^b |

Afin de former un accord similaire à une 7e de dominante, on peut
ajouter une note de 7e mineure à l’accord napolitain :

| do majeur         | la mineur       |
|-------------------+-----------------|
| ré^b fa la^b do^b | si^b ré fa la^b |

Ces derniers accords sont aussi appelés *substitution au triton*, ou
*substitution tritonique* à cause de l’intervalle de triton qui lie la
dominante auxiliaire altérée vers le bas avec la dominante.


** Modes composites

Un *mode composite* associe à chaque degré une liste d’accords qui lui
sont caractéristiques. Voici un exemple de mode composite proche du
/la mineur/ :

| Degrés | Accords                     | Exemples             |
|--------+-----------------------------+----------------------|
|      1 | parfait mineur              | la do mi             |
|        | parfait majeur              | la do^{#} mi         |
|      2 | 7e Daux                     | si ré fa la          |
|        |                             | si ré^{#} fa la      |
|        | napolitains                 | si^b ré fa           |
|        |                             | si^b ré fa la^b      |
|      3 | quinte augmentée            | do mi sol^{#}        |
|      4 | parfait mineur              | ré fa la             |
|        | parfait majeur              | ré fa^{#} la         |
|      5 | septième de dominante       | mi sol^{#} si ré     |
|        | neuvième de dominante       | mi sol^{#} si ré fa  |
|      6 | parfait majeur              | fa la do             |
|        | quinte diminuée             | fa^{#} la do         |
|      7 | quinte diminuée             | sol^{#} si ré        |
|        | septième diminuée           | sol^{#} si ré fa     |
|        | septième et quinte diminuée | sol^{#} si ré fa^{#} |

Cette variété d’accords implique qu’une partie ou la totalité des
notes de la gamme peut être altérée vers le haut ou vers le bas en
fonction du contexte.


** Tableau récapitulatif

#+TOC: headlines 1 local

*** Issus du majeur

| Accord                        | Exemple             | 3ces     |
|                               |                     | empilées |
|-------------------------------+---------------------+----------|
| parfait majeur                | do mi sol           | M m      |
| sixte                         | mi sol do           |          |
| quarte & sixte                | sol do mi           |          |
|-------------------------------+---------------------+----------|
| septième de dominante         | sol si ré fa        | M m m    |
| quinte diminuée               | si ré fa            | m m      |
| neuvième de dominante majeure | sol si ré fa la     | M m m M  |
| septième et quinte diminuée   | si ré fa la         | m m M    |
|-------------------------------+---------------------+----------|
| septième majeure              | do mi sol si        | M m M    |
|-------------------------------+---------------------+----------|
| dominante auxiliaire          | ré fa^{#} la        |          |
| sixte française               | la^b do ré fa^{#}   |          |
| sixte italienne               | la^b do fa^{#}      |          |
| sixte allemande               | la^b do mi^b fa^{#} |          |
| napolitain                    | ré^b fa la^b        |          |
| sixte napolitaine             | fa la^b ré^b        |          |


*** Issus du mineur

| Accord                        | Exemple              | 3ces     |
|                               |                      | empilées |
|-------------------------------+----------------------+----------|
| parfait mineur                | la do mi             | m M      |
| sixte                         | do mi la             |          |
| quarte & sixte                | mi la do             |          |
|-------------------------------+----------------------+----------|
| septième de dominante         | mi sol^{#} si ré     | M m m    |
| quinte diminuée               | sol^{#} si ré        | m m      |
| neuvième de dominante mineure | mi sol^{#} si ré fa  | M m m m  |
| septième diminuée             | sol^{#} si ré fa     | m m m    |
|-------------------------------+----------------------+----------|
| septième harmonique           | la do mi sol^{#}     | m M M    |
| quinte augmentée              | do mi sol^{#}        | M M      |
| septième mineure              | la do mi sol         | m M m    |
|-------------------------------+----------------------+----------|
| dominante auxiliaire          | si ré^{(#)} fa^{(#)} |          |
| sixte française               | fa la si ré^{#}      |          |
| sixte italienne               | fa la ré^{#}         |          |
| sixte allemande               | fa la do ré^{#}      |          |
| napolitain                    | si^b ré fa           |          |
| sixte napolitaine             | ré fa si^b           |          |


* Accords à base de quintes

#+TOC: headlines 1 local

** Triades

Si on superpose deux quintes, on obtient une triade que nous décidons
de nommer accord de *double quinte* :

| Accords       | Exemples  |
|---------------+-----------|
| double quinte | do sol ré |

En permutant les notes afin de les rapprocher, nous obtenons d’autres
dispositions de cet accord :

| Accords           | Exemples  |
|-------------------+-----------|
| double quarte     | ré sol do |
|-------------------+-----------|
| quarte et quinte  | sol do ré |
| seconde et quinte | do ré sol |

Ces accords sont nommés, suivant les cas :

  - d’après les intervalles entre les notes consécutives
  - d’après les intervalles qui séparent les notes de la basse

Synonymes courants :

  - l’accord de quarte et quinte se nomme aussi accord de *quarte suspendue*.
  - l’accord de seconde et quinte se nomme aussi accord de *seconde suspendue*.


** Tétrades

Les accords de quatre notes sont construits en superposant trois
quintes. Voici quelques dispositions possibles de ces accords :

| Accords        | Exemples     |
|----------------+--------------|
| triple quinte  | do sol ré la |
| triple quarte  | la ré sol do |
|----------------+--------------|
| 2de, 4te & 5te | sol la do ré |
| 4te, 5te & 9e  | sol do ré la |

Ces dispositions d’accords ressemblent aux modes tétraphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
tétraphonique.


** Pentades

Les accords de cinq notes sont construits en superposant quatre
quintes. Voici quelques dispositions possibles :

| Accords             | Exemples        |
|---------------------+-----------------|
| quadruple quinte    | do sol ré la mi |
| quadruple quarte    | mi la ré sol do |
|---------------------+-----------------|
| 3ce, 4te, 5te & 7e  | la do ré mi sol |
| 2de, 4te, 5te & 6te | sol la do ré mi |
| 4te, 5te, 6te & 9e  | sol do ré mi la |

Ces dispositions d’accords ressemblent aux modes pentaphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
pentaphonique.


** Tableau récapitulatif

| Accord              | Exemple         |
|---------------------+-----------------|
| double quinte       | do sol ré       |
| double quarte       | ré sol do       |
|---------------------+-----------------|
| quarte & quinte     | sol do ré       |
| seconde & quinte    | do ré sol       |
|---------------------+-----------------|
| triple quinte       | do sol ré la    |
| triple quarte       | la ré sol do    |
|---------------------+-----------------|
| 2de, 4te & 5te      | sol la do ré    |
| 4te, 5te & 9e       | sol do ré la    |
|---------------------+-----------------|
| quadruple quinte    | do sol ré la mi |
| quadruple quarte    | mi la ré sol do |
|---------------------+-----------------|
| 3ce, 4te, 5te & 7e  | la do ré mi sol |
| 2de, 4te, 5te & 6te | sol la do ré mi |
| 4te, 5te, 6te & 9e  | sol do ré mi la |
