
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 06 : La clé des chants
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Raconter une histoire

#+ATTR_HTML: :class lettrine
Une oeuvre musicale est une histoire à part entière, une histoire
composée de thèmes. Certains de ces thèmes plantent le décor, tandis
que d’autres incarnent les personnages. Des personnages qui
interagissent, dialoguent, questionnent, répondent, changent d’humeur
suivant le contexte ou l’interlocuteur. Mais le décor est en lui-même
un personnage, et il peut se réveiller à tout moment pour jouer un
rôle plus actif, un peu comme ces créatures des contes fantastiques,
en apparence inanimées mais que l’on découvre subitement douées de
mouvement et de parole.

L’idée est donc d’explorer les possibilités offertes par différentes
combinaisons de thèmes afin de développer les scènes de la pièce
musicale. Le nombre de thèmes impliqués dans une scène détermine en
partie son style : un contraste entre deux thèmes sera moins
mouvementé que l’agitation d’une foule.


* Variations

#+TOC: headlines 1 local


** Introduction

Il est fréquent en musique de présenter un thème puis des variations
de ce thème. Les procédés aboutissant à ces variations sont nombreux,
voici les plus courants.


** Inverser la mélodie


*** Miroir

Un miroir inverse le sens des intervalles mélodiques : les intervalles
haussiers devient baissiers et vice versa.


*** Rétrograder

Il s’agit d’inverser l’ordre chronologique des notes comme si le thème
était lu à l’envers.


** Transposer

On peut transposer la mélodie.


*** Mutation

La *mutation* consiste à adapter certaines notes d’un motif transposé
afin de l’intégrer à la tonalité en cours.

Une transposition peut ajouter ou supprimer des altérations, générant
ainsi des notes qui ne font pas partie de la gamme de référence.

La *mutation* consiste à annuler ces ajouts ou suppressions
d’altérations, ceci afin que toutes les notes du motif transposé
soient incluses dans la gamme de référence.


**** Dualité tonale

Dans le cas d’une transposition à la quinte, le procédé de mutation va
même plus loin car il veille à conserver l’équilibre entre tonique et
dominante.

Si nous transposons sans modification, nous obtenons :

#+ATTR_HTML: :class plat
| Initial   |   | Intervalle |   | Transposé   |
|-----------+---+------------+---+-------------|
| Tonique   | ⟼ | Quinte     | ⟼ | Dominante   |
| Dominante | ⟼ | Quinte     | ⟼ | Sus-tonique |

Dans ce cas, la mutation consiste à transformer les sus-toniques en
toniques :

#+ATTR_HTML: :class plat
| Initial   |   | Intervalle |   | Transposé |
|-----------+---+------------+---+-----------|
| Tonique   | ⟼ | Quinte     | ⟼ | Dominante |
| Dominante | ⟼ | Quarte     | ⟼ | Tonique   |

ce qui nous donne implicitement un intervalle de transposition de
quarte pour les notes concernées.

La dualité tonique — dominante du thème de départ s’est donc muée en
dualité dominante — tonique dans le thème transposé.

Il va de soi que les note environnantes peuvent également être
modifiées afin d’ajuster la mélodie.


** Changer le mode

Changer le mode modifie le caractère des accords du thème.


** Changer l’ornementation

On peut changer le type ou la quantité des ornements présents.


*** Agrémenter / Épurer

Agrémenter une note longue consiste à la remplacer par une suite de
notes rapides dont la moyenne correspond à la hauteur de la note
longue. Par extension, agrémenter un groupe de notes longues consiste
à agrémenter chacune d’entre-elles. L’agrémentation permet d’ajouter
de l’ornementation à la musique.

Épurer une suite de note rapides consiste à les remplacer par une note
longue correspondant à leur moyenne. On peut également diviser un
thème en plusieurs groupes de notes, chaque groupe étant ensuite épuré
et donc remplacé par une note plus longue.

/Remarque/ : au lieu de faire correspondre les notes longues aux
moyennes des notes rapides, on peut également choisir la note rapide
qui semble la plus pertinente en fonction du contexte musical : la
première note de chaque temps, mesure, ...


** Changer le rythme

On peut changer le rythme du thème tout en conservant la mélodie.


*** Augmenter / Diminuer

On peut augmenter ou diminuer la longueur d’un thème en multipliant
par un même facteur la durée de chaque note.

Exemple d’augmentation avec un facteur 2 :

#+BEGIN_CENTER
N C C ⟼ B N N
#+END_CENTER

Exemple de diminution avec un facteur 1/2 :

#+BEGIN_CENTER
N C C ⟼ C dC dC
#+END_CENTER


*** Conversions

Il est possible de convertir une succession de cellules rythmiques
binaires en cellules rythmes ternaires, et vice versa. Ces conversions
se font en conservant l’allure générale (nombre de notes, notes
longues, brèves ou égales, etc) de chaque cellule. Plusieurs choix
sont parfois possibles.


* Imitation

#+TOC: headlines 1 local


** Introduction

L’imitation consiste à reprendre des thèmes d’une ou plusieurs voix
données afin de les intégrer à une autre voix. Ce principe peut être
mutuel : les voix peuvent s’imiter les unes les autres.


** Parallèle

La forme la plus simple d’imitation consiste à créer par transposition
un thème *parallèle* à un thème donné. Le thème parallèle est appelé
*doublure*. On dit aussi que le thème d’origine est *doublé*.

L’intervalle entre le thème d’origine et la réplique parallèle peut
être :

  - un unisson
  - une octave
  - une quinte
  - une quarte
  - une tierce
  - une sixte
  - une dixième
  - une douzième
  - etc.


*** Unisson

La doublure la plus simple se fait à l’unisson ; le thème d’origine
est alors simplement recopié pour produire la doublure.

La doublure à l’unisson peut être utilisée pour augmenter le volume de
l’original : on utilise alors plusieurs instruments identiques jouant
la même voix. Si l’on souhaite obtenir un timbre synthétique, on peut
aussi faire jouer la même voix par des instruments différents.


** Variante

L’imitation par variante utilise des variations et de l’ornementation
afin de produire un thème qui soit créatif tout en demeurant similaire
au thème d’origine.


** Partielle

L’imitation partielle consiste à imiter certains éléments d’un thème
d’origine, les autres éléments étant ignorés.


** Multiple

L’imitation multiple rassemble des éléments provenant de plusieurs
voix différentes afin de produire un nouveau thème.


** Strette

Une *strette*, ou *resserrement* est une imitation qui commence avant
la fin de l’exposé du thème original imité.


* Constructions

#+TOC: headlines 1 local


** Écho

L’écho consiste à jouer un motif sur une voix /V/, puis à jouer le
même motif, éventuellement transposé, sur une autre voix /W/.

/Remarque/ : il est possible d’appliquer le principe de l’écho à une
seule note, en faisant entendre la même note transposée d’une ou
plusieurs octaves successivement sur deux voix différentes.


** Relais
:PROPERTIES:
:CUSTOM_ID: section:relais
:END:

Un relais consiste à continuer le développement d’un motif tout en le
déplaçant sur une autre voix. C’est généralement le caractère
particulier du motif qui permet de détecter le relais, mais on peut
également se servir d’un mouvement conjoint, d’une octave ou d’une
septième afin de renforcer la continuité de l’ensemble :

#+ATTR_HTML: :class plat
| S | : | la si la sol /fa/ |                  | =...= |
| B | : |                   | /mi/ ré do ré si | =...= |


*** Tuilage polyphonique

Le *tuilage polyphonique* déplace une mélodie d’une voix à une autre
en utilisant un motif mélodique commun aux deux voix pour réaliser une
transition naturelle.

Exemple :

#+ATTR_HTML: :class plat
| X | : | A1 | A2 | A3 |    |    | =...= |
| Y | : |    |    | A3 | A4 | A5 | =...= |


*** Fausse relation

Une fausse relation chromatique peut servir à produire un relais.
Exemple :

#+ATTR_HTML: :class plat
| S | : | la la^b |       | =...= |
| B | : |         | sol   | =...= |


** Collage

Le *collage* consiste à découper une mélodie et à la répartir sur
plusieurs voix distinctes.


** Entrelac

Un *entrelac* est une mélodie résultant de l’entrelacement de deux ou
de plusieurs voix. Cette technique permet de donner l’impression que
plusieurs voix sont jouées alors qu’une seule est à l’oeuvre.

Considérons par exemple la configuration suivante :

#+ATTR_HTML: :class plat
| X | : | A1 | A2 | A3 | A4 | =...= |
| Y | : | B1 | B2 | B3 | B4 | =...= |

Nous pouvons construire un entrelac sur une nouvelle voix /C/ à partir
des thèmes de /X/ et /Y/, en les alternant par exemple :

#+ATTR_HTML: :class plat
| C | : | A1 | B1 | A2 | B2 | A3 | B3 | A4 | B4 |


*** Ordre

Soit :

#+ATTR_HTML: :class plat
| X | : | A1 | A2 | A3 | A4 | =...= |
| Y | : | B1 | B2 | B3 | B4 | =...= |

et l’entrelac associé :

#+ATTR_HTML: :class plat
| C | : | (A1 | B1) | (A2 | B2) | (A3 | B3) | (A4 | B4) | =...= |

On peut produire d’autres entrelacs en variant l’ordre à l’intérieur
de chaque groupe. On obtient alors par exemple :

#+ATTR_HTML: :class plat
| (A1 | B1) | (B2 | A2) | (A3 | B3) | (B4 | A4) | =...= |

Afin de souligner la liberté de l’ordre à l’intérieur des groupes,
nous les entourons d’accolades :

#+ATTR_HTML: :class plat
| { A1 | B1 } | { A2 | B2 } | { A3 | B3 } | { A4 | B4 } | =...= |


*** Généralisation

Le procédé peut être généralisé à un nombre quelconque /N/ de voix.

Voici un exemple à trois voix :

#+ATTR_HTML: :class plat
| X | : | A1 | A2 | A3 | A4 | =...= |
| Y | : | B1 | B2 | B3 | B4 | =...= |
| Z | : | F1 | F2 | F3 | F4 | =...= |

et le schéma de l’entrelac résultant :

#+ATTR_HTML: :class plat
| { A1 | B1 | F1 } | { A2 | B2 | F2 } | { A3 | B3 | F3 } | { A4 | B4 | F4 } | =...= |


*** Environnement

Lorsqu’on construit un entrelac au sein d’une polyphonie, il faut
penser à la synchronisation avec les autres voix. Si nous construisons
aveuglément un entrelac à partir des mélodies /X/ et /Y/ dans :

#+ATTR_HTML: :class plat
| X | : | A1 | A2 | A3 | A4 | =...= |
| Y | : | B1 | B2 | B3 | B4 | =...= |
| Z | : | F1 | F2 | F3 | F4 | =...= |

nous obtenons :

#+ATTR_HTML: :class plat
| C | : | A1 | B1 | A2 | B2 | A3    | B3    | A4    | B4    | =...= |
| Z | : | F1 | F2 | F3 | F4 | =...= | =...= | =...= | =...= | =...= |

L’entrelac sur la voix /C/ est donc totalement désynchronisé par
rapport à son environnement, représenté ici par la voix /Z/. Ce
problème peut être aisément corrigé en doublant la rapidité de chaque
thème de /C/ :

#+ATTR_HTML: :class plat
| C | : | A1 | B1 | A2 | B2 | A3 | B3 | A4 | B4 | =...= |
| Z | : | F1 |    | F2 |    | F3 |    | F4 |    | =...= |


**** Généralisation

Dans le cas d’un entrelac constitutée de /N/ mélodies, on sera amené à
augmenter la rapidité d’un facteur /N/.


*** Basse d'Alberti

La basse d'Alberti est une ligne entrelacée arpégée : on place les
notes basses des accords au début de chaque temps et les autres notes
à l’intérieur. Le cadre harmonique est donc entièrement contenu dans
une seule voix.

Ce procédé permet de libérer d’autres voix pour faire entendre des
mélodies supplémentaires. On le rencontre aussi dans les partitions
pour clavier.


** Hoquet

Le *hoquet* est une technique qui consiste à distribuer les éléments d’une
mélodie sur deux ou plusieurs voix.

Par exemple, si nous partons de la mélodie :

#+ATTR_HTML: :class plat
| Z | : | A1 | B1 | A2 | B2 | A3 | B3 | A4 | B4 |

nous pouvons réaliser un hoquet sur deux voix :

#+ATTR_HTML: :class plat
| X | : | A1 |    | A2 |    | A3 |    | A4 |    | =...= |
| Y | : |    | B1 |    | B2 |    | B3 |    | B4 | =...= |


*** Hoquet & Entrelac

Le hoquet est le procédé inverse de l’entrelac


** Convergence / Divergence

La *convergence* se compose de deux voix aux thèmes différents qui
convergent vers un même thème.

La *divergence* se compose de deux voix qui introduisent un même thème
en parallèle, pour ensuite diverger en introduisant un ou plusieurs
autres thèmes. La divergence peut être :

  - simple : une des voix diverge tandis que l’autre poursuit sur le même thème
  - double : les deux voix divergent vers des variantes ou des thèmes différents


** Ostinato

Un *ostinato* est un petit motif mélodique qui se répète en boucle sur
une voix, pendant que les autres voix varient leurs thèmes.

Afin de rendre cette répétition naturelle, la fin d’un ostinato est
généralement construite comme une introduction à son début.

Tout comme en littérature, on utilise souvent une clausule afin de
marquer la fin de la musique. Exemple :

#+BEGIN_CENTER
(do ré =...= mi si) (do ré =...= mi si) (do ré =...= mi si) =...= (do ré =...= mi si) do
#+END_CENTER


** Méta

Les notes de référence d’une suite de notes forment une suite de notes
de niveau supérieur.

Par exemple, on peut transposer la suite /do ré mi/ de telle sorte que
les notes de référence (ici les notes initiales) tombent sur la suite
/ré fa mi ré/ :

#+ATTR_HTML: :class plat
| (/ré/ mi fa) | (/fa/ sol la) | (/mi/ fa sol) | (/ré/ mi fa) |


* Figures

#+TOC: headlines 1 local


** Introduction

Les figures musicales sont directement inspirées des
[[file:litera-02-styleau.org][figures de style littéraires]].


** Discursives

L’analogie la plus simple entre les [[file:litera-02-styleau.org][figures de style littéraires]] et
les figures musicales consiste à faire correspondre le discours à la
mélodie, et les blocs de texte aux thèmes musicaux. On construit ainsi
des figures mélodiques faisant intervenir des refrains, des variations
des inversions de thèmes, etc.

Ce type de construction est en tout point semblable aux figures de
style classiques.


** Polyphoniques

Un autre procédé consiste à faire correspondre, à chaque bloc de texte
d’un groupe, un thème présent sur une des voix d’une polyphonie.
Lorsqu’un même thème doit se retrouver simultanément ou successivement
sur plusieurs voix différentes, on le transpose afin de l’adapter à la
voix qui le reçoit.

Notons que certaines de ces figures sont déjà présentes dans les
constructions traditionnelles. Ainsi, la superposition d’une pédale
constante et d’une mélodie variée constitue un cas particulier de
cadre (AB - AC - ...) où le thème constant correspond à la pédale.

Le tableau ci-dessous donne des exemples de ces constructions. Tout
comme en littérature, nous introduisons la notation :

#+BEGIN_CENTER
A’ = variation de A
#+END_CENTER


*** Rafale

#+ATTR_HTML: :class plat
| S | : | A |
| B | : | A |


*** Extension

#+ATTR_HTML: :class plat
| S | : | A | A |
| B | : | — | B |


*** Compression

#+ATTR_HTML: :class plat
| S | : | A | A |
| B | : | B | — |


*** Dilatation

#+ATTR_HTML: :class plat
| S | : | A | A |
| A | : | B | X |
| B | : | — | B |


*** Contraction

#+ATTR_HTML: :class plat
| S | : | A | A |
| A | : | X | B |
| B | : | B | — |


*** Cadre

#+ATTR_HTML: :class plat
| S | : | X1 | X2 |
| A | : | A  | A  |
| B | : | Y1 | Y2 |


*** Reprises

#+ATTR_HTML: :class plat
| S | : | A | B |
| B | : | B | C |


*** Arborescence

#+ATTR_HTML: :class plat
| S | : | B | C | D |
| B | : | A | B | B |


*** Factorisation

#+ATTR_HTML: :class plat
| S | : | X1 | X2 |
| A | : | A  | —  |
| B | : | Y1 | Y2 |


*** Réversion

#+ATTR_HTML: :class plat
| S | : | A | B |
| B | : | B | A |


*** Serpentine

#+ATTR_HTML: :class plat
| S | : | A |
| A | : | X |
| B | : | A |


*** Rondine

#+ATTR_HTML: :class plat
| S | : | A | C |
| B | : | B | A |


*** Ronde

#+ATTR_HTML: :class plat
| S | : | A | B | =...= | Y | Z |
| B | : | B | C | =...= | Z | A |


*** Moulin

#+ATTR_HTML: :class plat
| S | : | A | B | C |
| A | : | B | A | A |
| T | : | C | C | B |
| B | : | A | B | C |


*** Parallélisme

#+ATTR_HTML: :class plat
| S | : | A | A’ |
| B | : | B | B’ |


*** Parallélisme inversé

#+ATTR_HTML: :class plat
| S | : | A | B’ |
| B | : | B | A’ |


*** Double parallélisme

#+ATTR_HTML: :class plat
| S | : | A | A’ |
| A | : | B | B’ |
| T | : | C | D’ |
| B | : | D | C’ |


*** Fédération

#+ATTR_HTML: :class plat
| S | : | A | B | A |
| B | : | — | — | B |


*** Tête-bêche

#+ATTR_HTML: :class plat
| S | : | A | Y | A |
| B | : | X | B | B |


*** Produit tensoriel

#+ATTR_HTML: :class plat
| S | : | R | S | R | S |
| B | : | A | A | B | B |


*** Dualité

#+ATTR_HTML: :class plat
| S | : | R | S | S |
| B | : | A | A | B |


*** Tableau

#+ATTR_HTML: :class plat
| S | : | S1 | S2 | S3 | S1 | A1 |
| A | : | A1 | A2 | A3 | S2 | A2 |
| B | : | —  | —  | —  | S3 | A3 |


** Ajouter des voix

Certaines figures polyphoniques peuvent être étendues à un nombre de
voix plus élevé. Passons en revue quelques exemples.


*** Reprise étendue

#+ATTR_HTML: :class plat
| S | : | A | B |
| A | : | B | C |
| T | : | C | D |
| B | : | D | E |


* Phrasé

#+TOC: headlines 1 local


** Ouverture et conclusion

Schématiquement, une phrase musicale est constituée d’un ou de
plusieurs mouvements d’ *ouverture*, suivis d’un mouvement de
*conclusion* :

#+BEGIN_CENTER
ouverture — =...= — ouverture — conclusion
#+END_CENTER


** Anacrouses


*** Généralisation

Le terme « anacrouse » réfère en principe à la première mesure d’un
morceau, lorsque celle-ci est incomplète. Nous généralisons cette
notion à toute suite de notes occupant la fin d’une structure
rythmique et rattachées mélodiquement à la structure rythmique
suivante. Toutes les échelles rythmiques sont possibles :

  - oscillation
  - pulsation
  - mesure
  - carrure
  - ...


*** Carrure

Une mélodie est le plus souvent composée de petits fragments, chacun
d’entre-eux reposant sur une carrure. Ces thèmes sont structurés
généralement comme suit :

  - Mélodie principale

  - Note plus longue ou silence se prolongeant assez longtemps pour
    mordre dans la dernière oscillation de la carrure.

  - Anacrouse : petite mélodie intercalée entre cette longue note et
    la fin de la carrure. Elle constitue une introduction à la mélodie
    de la carrure suivante.

L’intérêt de l’anacrouse est de décaler la logique mélodique, qui
commence au début de l’anacrouse, de la logique rythmique commençant
au début de la mesure suivante. On crée ainsi un ressort musical.
L’introduction non accentuée suivie par la note accentuée sur la
pulsation suivante donne également un effet d’augmentation progressive
de l’amplitude.


**** Exemple

Comme exemple, voici le rythme du thème situé au début du Beau Danube
bleu, où chaque pulsation correspond à une blanche pointée. Les
doubles barres verticales marquent le début et la fin de chaque
carrure, tandis que les accolades suivent la logique mélodique :

#+ATTR_HTML: :class plat
| { N ¦¦ Ν N N   B N   B N   B } { N ¦¦ N N N   B N   B N   B } |
| { N ¦¦ Ν N N   B N   B N   B } { N ¦¦ N N N   B N   B N   B } |
| =...=                                                         |

L’anacrouse correspond à la partie située entre le début du thème
mélodique et le début de la carrure :

#+BEGIN_CENTER
{ N ¦¦
#+END_CENTER


* Chant

#+TOC: headlines 1 local


** Introduction

Nous considérons dans cette partie que la musique intègre une ou
plusieurs voix correspondant à un ou plusieurs textes chantés,
éventuellement versifiés.


** Syllabes et notes

Il existe trois types de relations possibles entre les syllabes et les notes :

  - Syllabique : une syllabe par note, le plus fréquent

  - Mélismatique : plusieurs notes par syllabe

  - Psalmodique : plusieurs syllabes par note


*** Mélisme

Un *mélisme* est une syllabe chantée sur plusieurs notes.


*** Psalmodie

Une *psalmodie* est une suite de plusieurs syllabes chantées sur une unique note.


** Accentuation

Les accents du chant sont généralement disposés au début des
pulsations et oscillations.


** Chant virtuel

Lorsqu’on ne dispose pas de chant, on peut malgré tout utiliser les
techniques littéraires et poétiques présentées ci-dessous afin de
dynamiser la musique, la seule différence étant que les syllabes
chantées sont alors remplacées par de simples notes. On parle alors de
*chant virtuel*, ou de *vers virtuels* si le texte est versifié.


* Poésie

#+TOC: headlines 1 local


** Vers


*** Accentuation

Dans un poème, les accents sont généralement disposés aux syllabes qui
précédent les pauses naturelles, et se prolongent éventuellement sur
celles-ci. On a donc, par ordre décroissant d’importance, des
accents :

  - aux rimes, ou plus généralement à la dernière syllabe sonore de chaque vers
  - aux syllabes précédant les césures
  - aux syllabes précédant les coupes

On peut également inverser ce dispositif en disposant
occasionnellement un accent sur la première syllabe d’un vers, d’une
coupe ou d’une césure.

/Remarque/ : bien que ceux-ci puissent se confondre en pratique, il
est important de faire la distinction conceptuelle entre les accents
mélodiques (discontinuités, extrêmes, ...), les accents rythmiques
(pulsations) et les accents du chant (rimes, coupes, ...).


*** Rimes

Les notes correspondant aux *rimes* sont parmis les plus longues du
vers. Ces notes sont souvent de durée plus élevée que les autres notes
de la carrures, formant des paliers musicaux.


**** Virtuelles

En l’absence de chant, des rimes virtuelles peuvent être représentées
par de longues notes identiques ou complémentaires. Ces notes sont
placées à la fin de deux ou plusieurs carrures afin d’en accentuer les
finales. On parle alors de *rimes virtuelles*.

Les structures de rimes virtuelles les plus courantes sont analogues à
celles des [[file:litera-01-rimailleur.org::#section:strophes][strophes poétiques]].


*** Phrasé

Chaque vers peut être *ouvert* ou *conclusif*, la strophe disposant
ainsi d’une double structure de rimes et d’ouvertures. Exemple :

#+BEGIN_CENTER
a — a — a — b — c — c — c — b
#+END_CENTER

avec :

#+BEGIN_CENTER
ouverture — ouverture — ouverture — conclusion — ouverture — ouverture — ouverture — conclusion
#+END_CENTER


*** Anacrouse

Lorsqu’une anacrouse est désirée, on la place à la fin du vers, entre
la rime et le début de la mesure suivante.


** Strophes


*** Virtuelles

Les strophes composées de vers virtuels sont appelées *strophes
virtuelles*.


*** Zone tampon

La taille de la carrure est généralement prévue large, afin de
disposer d’une zone tampon où la dernière rime de chaque carrure peut
être allongée. Cette zone tampon permet également de gérer des vers
plus longs.


*** Fins de strophes

Afin de rendre solennelle la fin d’une strophe, il suffit de supprimer
l’anacrouse suivant la dernière rime. Par exemple, un quatrain pourra
se construire comme suit :

#+ATTR_HTML: :class plat
| Vers | Rime | Anacrouse |
| Vers | Rime | Anacrouse |
| Vers | Rime | Anacrouse |
| Vers | Rime |           |


** Échelles rythmiques

  - Les accents du poème (coupes, césures, rimes) sont généralement
    disposés au début des pulsations musicales

  - La durée d’une pulsation correspond donc à un pied (syllabique)

  - L’oscillation peut correspondre

    + À un vers entier s’il s’agit d’un vers court

    + À une partie de vers intermédiaire

    + À une césure s’il s’agit d’un vers long

  - La carrure peut correspondre

    + À une strophe

    + À une partie de strophe

La structure des coupes et césures d’un poème chanté est souvent moins
régulière que celle d’un poème récité. En effet, le rythme musical se
charge d’imposer la régularité, ce qui laisse la place à plus de
flexibilité dans la structure interne des vers.

Les échelles rythmiques d’une poésie chantée sont donc organisées en
s’inspirant du modèle :

| Musique     | Chant   |
|-------------+---------|
|             | Strophe |
| Carrure     |         |
|             | Vers    |
| Oscillation | Césure  |
| Pulsation   | Coupe   |
| Mesure      |         |

Gardons à l’esprit qu’il s’agit d’une hiérarchie souple, à adapter au cas par cas.


*** Exemples


**** Quatrain

Imaginons pour l’exemple le cas d’un quatrain d’alexandrins de
structure :

#+BEGIN_CENTER
3 / 3 // 3 / 3
#+END_CENTER

On a alors les correspondances :

| Pied (syllabique) | 1 pulsation                   | 1 mesure de 3 temps         |
| Hémistiche        | 1 oscillation de 2 pulsations | 2 mesures de 3 temps        |
| Vers              | 2 oscillations                | 4 mesures                   |
| Demi-strophe      | 4 oscillations                | 1 demi-carrure de 8 mesures |
| Strophe           | 8 oscillations                | 1 carrure de 16 mesures     |

Dans le cas de rimes croisées, chaque demi-strophe (occupant une
demi-carrure) contient donc les deux rimes, et la seconde demi-strophe
répond à la première :

#+BEGIN_CENTER
a b  —  a b
#+END_CENTER


**** Sixain

Nous prenons comme exemple la structure :

#+BEGIN_CENTER
a a b c c b
#+END_CENTER


Disposition sur 8 oscillations :

| 1er vers | 1 oscillation  | a |
| 2e vers  | 1 oscillation  | a |
| 3e vers  | 2 oscillations | b |
| 4e vers  | 1 oscillation  | c |
| 5e vers  | 1 oscillation  | c |
| 6e vers  | 2 oscillations | b |

Disposition sur 16 oscillations :

| 1er vers | 2 oscillations | a |
| 2e vers  | 2 oscillations | a |
| 3e vers  | 4 oscillations | b |
| 4e vers  | 2 oscillations | c |
| 5e vers  | 2 oscillations | c |
| 6e vers  | 4 oscillations | b |

Les deux dispositions sont similaires, il s’agit d’un simple
changement d’échelle. Dans les deux cas, les vers 3 et 6 (derniers
vers de chaque demi-strophe, rimes b) sont mis en évidences : ils
occupent une place double par rapport à celle des autres vers.


** Polystrophes

Lorsque deux ou plusieurs strophes (réelles ou virtuelles) sont
chantées simultanément sur les voix d’une polyphonie, on parle de
*polystrophe*.


*** Polyrimes

La structure de rimes d’une polystrophe est baptisée *polyrime*.

Lorsque les strophes commencent au même instant et que les mètres des
carrures sont identiques, leurs rimes sont jouées simultanément sur
les différentes voix, on dit qu’elles sont *synchrones*.

Dans le cas où les rimes sont décalées, on dit qu’elles sont
*asynchrones*.


**** Structures

Qu’elles soient synchrones ou non, les structures de rimes des
différentes strophes peuvent être identiques ou différentes.

Un exemple de structure identique :

#+ATTR_HTML: :class plat
| S | : | a | — | b | — | a | — | b |
| B | : | c | — | d | — | c | — | d |

Un exemple utilisant des structures différentes :

#+ATTR_HTML: :class plat
| S | : | a | — | b | — | a | — | b |
| B | : | c | — | d | — | d | — | c |


*** Fins de strophe

Dans le cas de polystrophes, on s’arrangera pour que les dernières
rimes soient synchronisées.
