
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 01 : Monocorde
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Pré en bulles

#+TOC: headlines 1 local

** Introduction

#+ATTR_HTML: :class lettrine
Si tout est lié dans le cosmos, et en particulier dans le monde des
arts, la musique en est un exemple frappant : le chant nous amène à la
poésie et à la littérature ; le rythme suggère la danse ; les mélodies
qui dialoguent ou qui décorent se rapprochent du théâtre ; quant aux
intervalles, leurs fréquences sont calibrées sur des proportions
mathématiques, véritables clefs de voûte qui soutiennent le dessin et
l’architecture musicale. Tracer un mandala, c’est un peu comme
caresser un clavier invisible et subtil. Sculpter, c’est faire
résonner un point d’orgue dans la crypte des siècles. Des troubadours
à Hildegarde von Bingen, de Johannes Ockeghem à Claude Debussy, les
compositeurs réchauffent l’âtre des châteaux et enchantent les
cathédrales. Les salons intimes frissonnent sous leurs doigts, les
fresques prennent vie, les jardins s’animent et les accords font
vibrer le tréfonds de l’âme humaine. Car si le silence peut parfois
nous paraître vertigineux, c’est parce qu’il contient en puissance les
plus belles musiques imaginables.

Porte d’entrée vers cet univers merveilleux, la théorie musicale
repose sur un arbre dont les racines sont aussi simples que les
ramifications sont denses et complexes. Rien d’étonnant à ce qu’une
variété aussi prodigieuse de styles puisse nidifier dans une
arborescence aussi riche. Une des clés de voûte de toute polyphonie
consiste en la dualité Mélodie — Harmonie, la première semant ses
notes consécutivement et la seconde simultanément. Mais tout n’est pas
aussi simple car les deux concepts se rejoignent : la mélodie forme
une harmonie implicite en laissant s’accumuler dans la mémoire de
l’auditeur des notes qui s’agrègent ; de son coté, l’harmonie suggère
dans sa superposition une mélodie implicite qui peut se voir
développée par la suite. Au croisement se situe l'Accord, groupe
polyvalent de notes pouvant donner lieu de par ses nombreuses
dispositions possibles à une foule de thèmes musicaux différents.

La richesse de cette tapisserie provient également des intéractions
entre les cycles d’intervalles, où se mêlent à nouveau mélodie et
harmonie. C’est aussi dans ces cycles, souvent partiellement
implicites, que les accords s’enchaînent, formant une ronde
perpétuelle. La tonalité ajoute son grain de sel via le concept de
fonction tonale, concept qui permet de voyager via une autre dimension
d’accord en accord, aussi facilement que l’on se transporte sur une
autre planète dans la littérature fantastique. Partout en musique,
nous sommes en présence d’un système que l’on pourrait qualifier de
métamorphe, dans la mesure où chaque élément musical peut se présenter
sous différentes formes, où chaque forme peut être interprétée comme
provenant d’éléments distincts.

Avec le rythme s’ajoute à cet incroyable treillis la notion de
fractale, un même motif rythmique pouvant être appliqué à des échelles
temporelles différentes. La structure rythmique elle-même s’articule
sur différents niveaux, chacun d’entre-eux étant décomposé en un
nombre variable de subdivisions. Cette nouvelle dimension possède une
identité propre, indépendante de la mélodie de laquelle elle se décale
régulièrement, formant ainsi syncopes et anacrouses. Comme vous pouvez
le constater, les trois facettes du triptyque formé par la Mélodie,
l’Harmonie et le Rythme s’entremêlent, formant sous nos yeux ébahis ce
miracle que l’on nomme Musique.

Vous ayant averti de l’univers vertigineux qui vous attend, il me
reste à conclure cette introduction en vous souhaitant une bonne
lecture.


** Remerciements

Je tiens à remercier :

  - Michel Baron, qui nous offre [[http://michelbaron.com][un cours d’harmonie, de contrepoint et de fugue]].

  - Sylvain Caron, pour son [[http://www.mapageweb.umontreal.ca/caronsy/harmonie_1/html/plan_harm1.html][cours d’harmonie tonale]].

  - Luce Beaudet, qui nous fait partager [[http://bw.musique.umontreal.ca/][une méthode simple et puissante]]
    permettant d’analyser le discours harmonique générique, ainsi que les marches.

  - Alan Belkin, pour [[http://alanbelkinmusic.com/site/en/][sa vision éclairante de la composition musicale]].
    Vous trouverez sur son site de riches réflexions sur la forme
    musicale, l’orchestration, la composition, l’harmonie et le
    contrepoint.

  - Johann Joseph Fux, pour son précieux traité de contrepoint, le
    [[https://imslp.org/wiki/Gradus_ad_Parnassum_(Fux%2C_Johann_Joseph)][Gradus ad Parnassum]], qui inspire les compositeurs depuis plus de
    deux siècles.


* Acoustique

#+TOC: headlines 1 local


** Introduction

Le son étant la brique fondamentale sur laquelle repose tout l’édifice
musical, il semble raisonnable d’entamer ce traité par son étude.

Un son est une *onde acoustique*, c’est-à-dire une onde de pression,
simple ou complexe, perceptible par nos oreilles.


** Onde élémentaire

Une *onde acoustique élémentaire*, ou plus simplement *onde
élémentaire*, est une onde acoustique au tracé sinusoïdal.

Ce type d’onde permet de rendre compte d’un grand nombre de phénomènes
physiques, que ce soit sous sa forme simple (pendule, cercle en
rotation, ...) ou par superposition (corde vibrante, tuyau
sonore, ...).

#+begin_center
⁂
#+end_center

Un *son élémentaire* est un son associé à une onde acoustique
élémentaire.


** Fréquence

La *fréquence* d’une onde élémentaire (et donc du son élémentaire
associé) est égale au nombre de cycles qu’elle parcourt en une
seconde. L’unité de fréquence est le *Herz*, symbolisé par *Hz* :

#+begin_center
/N/ Herz = /N/ Hz = /N/ cycles par secondes
#+end_center


*** Aigu et grave

La hauteur d’un son élémentaire est déterminée par la fréquence de
l’onde élémentaire associée :

  - plus la fréquence est grande, plus le son est dit *haut* ou *aigu*
  - plus la fréquence est petite, plus le son est dit *bas* ou *grave*


** Son composé

Si la plupart des sons utilisables musicalement sont trop complexes
pour être étudiés en tant que tels, il est généralement possible de
les considérer comme des superpositions de sons élémentaires, ce qui
facilite grandement leur analyse.

On nomme *son composé* un tel son décomposable en sons élémentaires.


* Sons composés

#+TOC: headlines 1 local


** Introduction

Nous étudions dans ce chapitre l’organisation interne (fréquences &
amplitudes) des sons composés.


** Fréquences

La *fréquence fondamentale* est la fréquence la plus grave présente
dans un son composé.

Toutes les autres fréquences sont appelées *fréquences harmoniques*.


** Fréquences harmoniques naturelles

Dans de nombreux cas, les fréquences des sons élémentaires
constitutifs d’un son composé sont des multiples entiers de la
fréquence fondamentale /F_0/ :

#+ATTR_HTML: :class plat
| 1 F_0 | — | 2 F_0 | — | 3 F_0 | — | 4 F_0 | — | 5 F_0 | — | 6 F_0 | — | 7 F_0 | — | 8 F_0 | — | 9 F_0 | — | =...= |

Ces fréquences sont appelées *fréquences harmoniques naturelles*.


*** Ratios

En exprimant le tout comme des multiples de /F_0/, on obtient :

#+ATTR_HTML: :class plat
| 1 | — | 2 | — | 3 | — | 4 | — | 5 | — | 6 | — | 7 | — | 8 | — | 9 | — | =...= |

Les ratios des fréquences consécutives sont donc, dans l’ordre :

#+ATTR_HTML: :class plat
| 2 / 1 | — | 3 / 2 | — | 4 / 3 | — | 5 / 4 | — | 6 / 5 | — | 7 / 6 | — | 8 / 7 | — | 9 / 8 | — | =...= |


** Timbre

Si les fréquences des harmoniques naturelles sont des multiples
entiers de la fréquence fondamentale, les amplitudes relatives de ces
harmoniques varient considérablement d’un instrument de musique à un
autre. Une combinaison particulière de ces amplitudes produit ce qu’on
appelle le *timbre* d’un son. C’est donc le timbre qui donne un
caractère reconnaissable à chaque instrument.


* Notes

#+TOC: headlines 1 local

** Introduction

Une *note* est un son dont la fréquence fondamentale est donnée. Cette
fréquence détermine la hauteur du son obtenu :

  - plus la fréquence fondamentale est élevée, plus la note est dite *aiguë*.
  - plus la fréquence fondamentale est faible, plus la note est dite *grave*.

On utilise aussi une analogie basée sur la *hauteur* :

  - une note est dite plus haute ou supérieure à une autre lorsqu’elle est plus aiguë
  - une note est dite plus basse ou inférieure à une autre lorsqu’elle est plus grave

Suivant le même raisonnement, une suite de note sera dite :

  - montante si elle évolue vers l’aigu
  - descendante si elle évolue vers le grave

Une note correspond donc à une certaine fréquence fondamentale. Le
timbre du son reste par contre libre et dépend de l’instrument utilisé
pour jouer la note.


** Diapason

Le diapason est une note qui permet à tous les musiciens de
synchroniser leurs instruments. Cette note est définie par sa
fréquence fondamentale, fixée par convention à :

#+begin_center
440 Hz
#+end_center


** Intervalles

Un *intervalle* représente la distance qui sépare deux notes.

L’expérience nous montre que l’oreille mesure la distance entre deux
notes par le ratio de leurs fréquences fondamentales.

L’intervalle qui sépare deux notes est donc formellement défini par le
ratio de leurs fréquences fondamentales.


*** Purs

Un *intervalle pur* est un intervalle dont le ratio de fréquence est
*identique* à l’un des premiers ratios intervenant dans les fréquences
harmoniques naturelles.

Le tableau ci-dessous reprend les noms et ratios de fréquences des
intervalles purs les plus importants :

| Intervalle     | Ratio |
|----------------+-------|
| octave         | 2 / 1 |
| quinte         | 3 / 2 |
| quarte         | 4 / 3 |
| tierce majeure | 5 / 4 |
| tierce mineure | 6 / 5 |

Les noms donnés à ces intervalles peuvent paraître étranges à ce
stade ; nous en verrons plus loin l’origine.


** Harmoniques naturelles

Une *suite d’harmoniques naturelles* est une suite de *notes* qui
respecte les proportions des fréquences harmoniques naturelles.

Les ratios des fréquences fondamentales des notes sont donc les
mêmes :

#+ATTR_HTML: :class plat
| 2 / 1 | — | 3 / 2 | — | 4 / 3 | — | 5 / 4 | — | 6 / 5 | — | 7 / 6 | — | 8 / 7 | — | 9 / 8 | — | =...= |

et les notes de la suite produisent les mêmes intervalles :

#+begin_center
octave — quinte — quarte — tierce majeure — tierce mineure — =...=
#+end_center

La note la plus grave est appelée *fondamentale* de la suite. C’est
elle qui détermine la hauteur des notes suivantes.

/Remarque/ : ne pas confondre la /note/ fondamentale d’une suite
d’harmoniques naturelle avec la /fréquence/ fondamentale d’un son
composé.

Les suites d’harmoniques naturelles sont très utilisées comme
référence, car :

  - elles sont construites en se basant sur un principe acoustique essentiel
  - elles sonnent particulièrement bien


* Octave

#+TOC: headlines 1 local


** Introduction

L’octave est le premier des intervalles apparaissant dans les
harmoniques naturelles, ce qui lui confère un statut particulièrement
important en musique.

À ce titre, l’octave est utilisée pour simplifier considérablement le
problème de la répartition des notes de musique sur la plage des
fréquences audibles.

On commence par définir un ensemble de notes incluses dans une octave
de référence, c’est-à-dire dans une plage allant d’une fréquence
donnée /F_0/ à son double /2 F_0/. Les notes des octaves environnantes
s’obtiennent ensuite facilement en multipliant ou en divisant par 2 la
fréquence d’une des notes de l’octave de référence. En répétant ce
processus de multiplication ou de division, on peut alors construire
autant d’octaves qu’on le souhaite, du très grave au très aigu.

Le tableau suivant schématise cette construction, en partant d’une
note de fréquence /F/ dans l’octave de référence :

#+ATTR_HTML: :class plat
| octave +N :           |               |       | 2^N F   |       |       |
| =...=                 | =...=         | =...= | =...=   | =...= | =..=  |
| octave +3 :           | 2 × 2 × 2 F   | =     | 2^3 F   | =     | 8 F   |
| octave +2 :           | 2 × 2 F       | =     | 2^2 F   | =     | 4 F   |
| octave +1 :           | 2 F           |       |         |       |       |
| octave de référence : | F             |       |         |       |       |
| octave − 1 :          | F / 2         |       |         |       |       |
| octave − 2 :          | F / 2 / 2     | =     | F / 2^2 | =     | F  4  |
| octave − 3 :          | F / 2 / 2 / 2 | =     | F / 2^3 | =     | F  8  |
| =...=                 | =...=         | =...= | =...=   | =...= | =...= |
| octave − N :          |               |       | F / 2^N |       |       |


** Notes naturelles

Le système musical le plus répandu comporte sept notes par octave. Ces
notes sont appelées *notes naturelles*, ou encore *notes diatoniques*.
Elles sont nommées par convention comme suit, de la plus grave à la
plus aiguë :

#+begin_center
do   ré   mi   fa   sol   la   si
#+end_center

Le /do/ est parfois appelé /ut/, ce qui nous donne les notes :

#+begin_center
ut   ré   mi   fa   sol   la   si
#+end_center


*** Alphabet

Il existe une notation alternative, basée sur les premières lettres de
l’alphabet, le « A » correspondant à la note « la ». On a
l’équivalence :

#+ATTR_HTML: :class plat
| la  | = | A |
| si  | = | B |
| do  | = | C |
| ré  | = | D |
| mi  | = | E |
| fa  | = | F |
| sol | = | G |


** Notation

Il existe plusieurs façons de préciser l’octave d’une note.


*** Jusqu’à quatre octaves

Il est possible d’employer une notation basée sur :

  - des lettres minuscules et majuscules
  - des barres inférieures

On peut alors différencier jusqu’à 4 octaves :

|       | Octaves | Notes                               |
|-------+---------+-------------------------------------|
| aigu  |       4 | do ré mi fa sol la si               |
|       |       3 | DO RÉ MI FA SOL LA SI               |
|       |       2 | _do_ _ré_ _mi_ _fa_ _sol_ _la_ _si_ |
| grave |       1 | _DO_ _RÉ_ _MI_ _FA_ _SOL_ _LA_ _SI_ |

Il est possible d’utiliser des versions restreintes de cette notation
pour différencier un nombre d’octaves moins grand, l’essentiel étant
de respecter l’ordre du tableau ci-dessus.


**** Deux octaves

Pour rendre compte de 2 octaves, on a par exemple :

|       | Octaves | Notes                 |
|-------+---------+-----------------------|
| aigu  |       2 | do ré mi fa sol la si |
| grave |       1 | DO RÉ MI FA SOL LA SI |


**** Trois octaves

Lorsqu’on souhaite différencier 3 octaves, on a par exemple :

|       | Octaves | Notes                               |
|-------+---------+-------------------------------------|
| aigu  |       3 | do ré mi fa sol la si               |
|       |       2 | DO RÉ MI FA SOL LA SI               |
| grave |       1 | _do_ _ré_ _mi_ _fa_ _sol_ _la_ _si_ |


*** Générique

Étant donnée une note /X/ de fréquence /F/, on définit :

  - /X^+1/ : la note de fréquence /2 F/ située à l’octave supérieure
  - /X^-1/ : la note de fréquence /F / 2/ située à l’octave inférieure

On généralise cette notation à un nombre naturel /N = 1, 2, 3, .../
quelconque par :

#+ATTR_HTML: :class plat
| /X^+N/ : | la note de fréquence /2^N F/ située       /N/ octaves au-dessus de l’octave de référence |
| /X^-N/ : | la note de fréquence /F / 2^N/ située        /N/ octaves sous l’octave de référence      |


** Implicite

En théorie musicale, la mention de l’octave d’une note est souvent
omise. Dans ce cas, c’est soit que cette octave :

  - n’a aucune incidence sur le raisonnement en cours
  - peut se déduire aisément du contexte


** Suites croissantes

Une *suite croissante* est une série de notes triées de la plus grave
à la plus aiguë.

Dans une suite croissante, la mention de l’octave peut être omise, car
il est évident que chaque /do/ franchi nous oblige à monter au moins
d’une octave.

#+begin_center
⁂
#+end_center

Nous allons illustrer le principe de déduction de l’octave au moyen de
la suite croissante suivante :

#+begin_center
fa sol la si do ré mi fa
#+end_center

Nous savons que le /do/ doit être plus aigu que le /si/ qui le
précède. Ces deux notes ne peuvent donc pas faire partie d’une même
octave, sans quoi le /si/ serait plus aigu que le /do/ par convention.
On en déduit que le /do/ est situé dans une octave supérieure à celle
du /si/. En conséquence, la fin de la suite :

#+begin_center
do ré mi fa
#+end_center

est située dans une octave supérieure à celle du début :

#+begin_center
fa sol la si
#+end_center

Notons que le /do/ n’a pas besoin d’être explicitement présent dans la
suite pour provoquer la hausse d’une octave. Ainsi, dans :

#+begin_center
fa sol la ré mi fa
#+end_center

le /do/ est implicitement franchi :

#+begin_center
fa sol la (si *do*) ré mi fa
#+end_center

En conséquence, la fin de la suite :

#+begin_center
ré mi fa
#+end_center

est située dans une octave supérieure à celle du début :

#+begin_center
fa sol la
#+end_center


**** Exemples

Pour être bien sûr d’y voir clair, voici quelques exemples de suites
croissantes avec octave implicite, puis leur version équivalente avec
l’octave explicitée :

| Octave implicite         | Octave explicite          |
|--------------------------+---------------------------|
| fa sol la si do ré mi fa | FΑ SOL LA SI do ré mi fa  |
| fa la do mi sol si ré    | _fa_ _la_ DO MI SOL SI ré |
| fa do sol ré la mi       | _FA_ _do_ _sol_ RÉ LA mi  |


* Tempérament

#+TOC: headlines 1 local

** Introduction

Comme aucune répartition de notes diatoniques n’est à même de former
uniquement des intervalles purs, on est forcé de faire des
approximations. Une répartition particulière de ces approximations,
qui conditionne l’agencement précis des notes diatoniques, est appelé
*tempérament*.

La suite des notes ainsi obtenues sera dite *tempérée*.

Ce chapitre présente quelques tempéraments fondamentaux.


** Pythagore

Le *tempérament de Pythagore*, ou *tempérament pythagoricien*, est
construit à partir de quintes pures.

On part d’une note de référence /do/ de fréquence /F_0/ et on
construit les autres notes via des intervalles de quintes pures. La
fréquence est donc à chaque fois multipliée ou divisée par /3 / 2/ :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| Q 7         | 243 / 32        |
| Q 6         | 81 / 16         |
| Q 5         | 27 / 8          |
| Q 4         | 9 /4            |
| Q 3         | 3 / 2           |
| Q 2         | 1               |
| Q 1         | 2 / 3           |

On ramène ensuite toutes les fréquences à l’intérieur de l’octave de
référence [F_0, 2 F_0], en les multipliant ou en les divisant par
la puissance de deux adéquate. On les trie ensuite de la plus grave à
la plus aiguë, ce qui nous donne, avec les plus graves en bas du
tableau :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| Q 7         | 243 / 128       |
| Q 5         | 27 /16          |
| Q 3         | 3 / 2           |
| Q 1         | 4 / 3           |
| Q 6         | 81 / 64         |
| Q 4         | 9 / 8           |
| Q 2         | 1               |

Nous pouvons à présent nommer les notes définies par ces fréquences,
suivant la convention usuelle /do, ré, mi, fa, sol, la, si/ :

| Notes | Identifiant | Fréquence / F_0 |
|-------+-------------+-----------------|
| si    | Q 7         | 243 / 128       |
| la    | Q 5         | 27 / 16         |
| sol   | Q 3         | 3 / 2           |
| fa    | Q 1         | 4 / 3           |
| mi    | Q 6         | 81 / 64         |
| ré    | Q 4         | 9 / 8           |
| do    | Q 2         | 1               |

Il ne reste alors plus qu’à ajouter un /do/ de fréquence /2 F_0/ pour
compléter l’octave, ce qui nous donne :

| Notes | Fréquence / F_0 |
|-------+-----------------|
| do    | 2               |
| si    | 243 / 128       |
| la    | 27 / 16         |
| sol   | 3 / 2           |
| fa    | 4 / 3           |
| mi    | 81 / 64         |
| ré    | 9 / 8           |
| do    | 1               |


*** Tons et demi-tons

Les ratios de fréquences entre les notes naturelles consécutives du
tempérament de Pythagore s’écrivent :

| Notes    | Ratios    |
|----------+-----------|
| si — do  | 256 / 243 |
| la — si  | 9 / 8     |
| sol — la | 9 / 8     |
| fa — sol | 9 / 8     |
| mi — fa  | 256 / 243 |
| ré — mi  | 9 / 8     |
| do — ré  | 9 / 8     |

On constate que ces écarts peuvent être classés en deux catégories
suivant leur taille. Les plus grands sont appelés *tons* et les plus
petits *demi-tons*. En effet, on peut vérifier que parcourir deux
demi-tons revient plus ou moins à parcourir un ton.

Le tableau suivant nous donne la liste de tous les tons et demi-tons
du tempérament de Pythagore :

| Type      | Ratio    | Notes    |
|-----------+----------+----------|
| tons      | 9 / 8    | do — ré  |
|           |          | ré — mi  |
|           |          | fa — sol |
|           |          | sol — la |
|           |          | la — si  |
| demi-tons | 256 /243 | mi — fa  |
|           |          | si — do  |

En faisant les comptes, on en déduit que le tempérament de Pythagore
contient *5 tons* et *2 demi-tons* par *octave*.


*** Quintes

En réarrangeant les notes du tempérament de Pythagore suivant les
intervalles de quintes qui ont mené à sa formation :

#+ATTR_HTML: :class plat
| Q 1 | — | Q 2 |
| Q 2 | — | Q 3 |
| Q 3 | — | Q 4 |
| Q 4 | — | Q 5 |
| Q 5 | — | Q 6 |
| Q 6 | — | Q 7 |

on obtient les intervalles :

#+ATTR_HTML: :class plat
| fa  | — | do  |
| do  | — | sol |
| sol | — | ré  |
| ré  | — | la  |
| la  | — | mi  |
| mi  | — | si  |

En considérant chacun de ces intervalles de *quinte*, on constate
qu’ils englobent tous *cinq* notes :

#+ATTR_HTML: :class plat
| /fa — do/  | : | fa  | sol | la  | si  | do  |
| /do — sol/ | : | do  | ré  | mi  | fa  | sol |
| /sol — ré/ | : | sol | la  | si  | do  | ré  |
| /ré — la/  | : | ré  | mi  | fa  | sol | la  |
| /la — mi/  | : | la  | si  | do  | ré  | mi  |
| /mi — si/  | : | mi  | fa  | sol | la  | si  |

C’est de là que vient le nom de quinte, *quintus* signifiant cinquième
en latin.


**** Pureté

Par construction, presque toutes les quintes formées par les notes
naturelles du tempérament de Pythagore sont pures. La seule exception
est la quinte /si — fa/, qui est une quinte diminuée.


*** Tierces


**** Majeures

Aucune tierce majeure pure n’est présente dans le tempérament de
Pythagore, on ne dispose que d’approximations.

Pour ne citer qu’un exemple, le ratio de fréquence entre les notes
/do/ et /mi/ est de :

#+begin_center
81 / 64 = 1.265625
#+end_center

à comparer avec le ratio de la tierce majeure pure :

#+begin_center
5 / 4 = 80 / 64 = 1.25
#+end_center


**** Mineures

Il en va de même pour les tierces mineures. Ainsi, le ratio de
fréquence entre les notes /mi/ et /sol/ est de :

#+begin_center
3 / 2 × 64 / 81 = 32 / 27 = 1.1851 =...=
#+end_center

à comparer avec le ratio de la tierce mineure pure :

#+begin_center
6 / 5 = 1.2
#+end_center


** Zarlino

Le *tempérament de Zarlino*, ou *tempérament zarlinien*, est construit
à partir de quintes et de tierces majeures pures.

On part d’une note de référence /do/ de fréquence /F_0/ et on
construit les autres notes via des intervalles de quintes et de
tierces majeures pures. On commence par construire les quintes pures
autour de la note de référence :

| Fréquence / F_0 |
|-----------------|
| *3 / 2*         |
| *1*             |
| *2 / 3*         |

On multiplie ensuite chacune des fréquences déjà obtenues par le
facteur /5 / 4/, ce qui nous donne trois nouvelles notes situées une
tierce majeure pure au-dessus des trois premières :

| Fréquence / F_0 |
|-----------------|
| 15 / 8          |
| *3 / 2*         |
| 5 / 4           |
| *1*             |
| 10 / 12         |
| *2 / 3*         |

On complète le tempérament en ajoutant une dernière note, située une
quinte pure au-dessus de la fréquence /3 / 2 F_0/, c’est-à-dire à
/9 / 4 F_0/ :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| T 7         | 9 / 4           |
| T 6         | 15 / 8          |
| T 5         | *3 / 2*         |
| T 4         | 5 / 4           |
| T 3         | *1*             |
| T 2         | 5 / 6           |
| T 1         | *2 / 3*         |

On ramène ensuite toutes les fréquences à l’intérieur de l’octave de
référence [F_0, 2 F_0], en les multipliant ou en les divisant par la
puissance de deux adéquate. On les trie ensuite de la plus grave à la
plus aiguë, ce qui nous donne, avec les plus graves en bas du
tableau :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| T 6         | 15 / 8          |
| T 2         | 5 / 3           |
| T 5         | *3 / 2*         |
| T 1         | *4 / 3*         |
| T 4         | 5 / 4           |
| T 7         | 9 / 8           |
| T 3         | *1*             |

Nous pouvons à présent nommer les notes définies par ces fréquences,
suivant la convention usuelle /do, ré, mi, fa, sol, la, si/ :

| Notes | Identifiant | Fréquence / F_0 |
|-------+-------------+-----------------|
| si    | T 6         | 15 / 8          |
| la    | T 2         | 5 / 3           |
| sol   | T 5         | *3 / 2*         |
| fa    | T 1         | *4 / 3*         |
| mi    | T 4         | 5 / 4           |
| ré    | T 7         | 9 / 8           |
| do    | T 3         | *1*             |

Il ne reste alors plus qu’à ajouter un /do/ de fréquence /2 F_0// pour
compléter l’octave, ce qui nous donne :

| Notes | Fréquence / F_0 |
|-------+-----------------|
| do    | 2               |
| si    | 15 / 8          |
| la    | 5 / 3           |
| sol   | *3 / 2*         |
| fa    | *4 / 3*         |
| mi    | 5 / 4           |
| ré    | 9 / 8           |
| do    | *1*             |


*** Tons et demi-tons

Les ratios de fréquences entre les notes naturelles consécutives du
tempérament de Zarlino s’écrivent :

| Notes    | Ratios  |
|----------+---------|
| si — do  | 16 / 15 |
| la — si  | 9 / 8   |
| sol — la | 10 / 9  |
| fa — sol | 9 / 8   |
| mi — fa  | 16 / 15 |
| ré — mi  | 10 / 9  |
| do — ré  | 9 / 8   |

On constate que ces écarts peuvent être classés en deux catégories
suivant leur taille. Les plus grands sont appelés *tons* et les plus
petits *demi-tons*. En effet, on peut vérifier que parcourir deux
demi-tons revient plus ou moins à parcourir un ton.

Le tableau suivant nous donne la liste de tous les tons et demi-tons
du tempérament de Zarlino :

| Type      | Ratio   | Notes    |
|-----------+---------+----------|
| tons      | 9 / 8   | do — ré  |
|           | 10 / 9  | ré — mi  |
|           | 9 / 8   | fa — sol |
|           | 10 / 9  | sol — la |
|           | 9 / 8   | la — si  |
| demi-tons | 16 / 15 | mi — fa  |
|           |         | si — do  |

En faisant les comptes, on en déduit que le tempérament de Zarlino
contient *5 tons* et *2 demi-tons* par *octave*.

On remarque que tous les tons ne sont pas identiques, certains valant
/9 / 8/ et les autres /10 / 9/. Cette légère différence peut poser
problème lorsqu’on souhaite déplacer la structure musicale d’une
hauteur de son à l’autre.


*** Quintes

Par construction, la plupart des quintes du tempérament de Zarlino
sont pures. Il y a toutefois des exceptions. Ainsi, l’intervalle
séparant le /ré/ du /la/ vaut :

#+begin_center
5 / 3 × 8 / 9 = 40 / 27 = 1.4814 =...=
#+end_center

à comparer avec le ratio de la quinte pure :

#+begin_center
3 / 2 = 1.5
#+end_center


*** Tierces


**** Majeures

En réarrangeant les notes du tempérament de Zarlino suivant les
intervalles de tierces majeures qui ont mené à sa formation :

#+ATTR_HTML: :class plat
| T 1 | — | T 2 |
| T 3 | — | T 4 |
| T 5 | — | T 6 |

on obtient les intervalles :

#+ATTR_HTML: :class plat
| fa  | — | la |
| do  | — | mi |
| sol | — | si |

En considérant chacun de ces intervalles de *tierce majeure*, on
constate qu’ils englobent tous *trois* notes :

#+ATTR_HTML: :class plat
| /fa — la/  | : | fa  | sol | la |
| /do — mi/  | : | do  | ré  | mi |
| /sol — si/ | : | sol | la  | si |

C’est de là que vient le nom de tierce, *tertius* signifiant troisième
en latin.


**** Mineures

En considérant les autres intervalles contenant trois notes, on
obtient la liste :

#+ATTR_HTML: :class plat
| /ré — fa/  | : | ré | mi | fa  |
| /mi — sol/ | : | mi | fa | sol |
| /la — do/  | : | la | si | do  |
| /si — ré/  | : | si | do | ré  |

En calculant les ratios de fréquences de ces intervalles, on vérifie
qu’ils sont tous identiques à /6 / 5/, à l’exception de l’intervalle
/ré — fa/ qui vaut :

#+begin_center
4 / 3 × 8 / 9 = 32 / 27 = 1.1851 =...=
#+end_center

à comparer avec le ratio de la tierce mineure pure :

#+begin_center
6 / 5 = 1.2
#+end_center

Ces *tierces mineures* (pures ou approximatives) englobent donc aussi
*trois* notes.


** Tempérament égal

Le *tempérament égal* est construite à partir de l’approximation qui
consiste à considérer que :

  - tous les demi-tons sont identiques
  - chaque ton vaut exactement deux demi-tons

Une octave contient donc :

#+ATTR_HTML: :class plat
| 5 tons + 2 demi-tons | = | 5 × 2 demi-tons | + | 2 demi-tons |
|                      | = | 10 demi-tons    | + | 2 demi-tons |
|                      | = | 12 demi-tons    |   |             |

Le tempérament égal est donc construit en divisant l’octave en douze
demi-tons identiques. Ce demi-ton est appelé demi-ton tempéré et noté
*DT*.

On a les relations :

#+ATTR_HTML: :class plat
| 1 demi-ton = 1 DT |
| 1 ton = 2 DT      |

Sauf indication contraire, nous utiliserons dans la suite le
tempérament égal.


*** Ratios

Puisqu’il y a 12 demi-tons tempérés par octave, le rapport de
fréquence d’un demi-ton tempéré $RFDT$ vérifie :

#+ATTR_HTML: :class plat
RFDT^{12} = 2

Le rapport $RFDT$ correspond donc à un douxième de l’octave :

#+ATTR_HTML: :class plat
RFDT = 2^{1/12}

On en déduit que l’écart /E/ en demi-tons tempérés qui sépare deux
notes est lié au ratio de leurs fréquences /F_1/ et /F_2/ par les
relations :

#+ATTR_HTML: :class plat
F_2 / F_1 = 2^{E/12}

La relation inverse nous donne l’écart en demi-tons à partir d’un
rapport de fréquence quelconque :

#+ATTR_HTML: :class plat
E = 12 × log_2 ( F_2 / F_1 )


** Comparatif

Le tableau suivant compare les différentes tempéraments. Les
fréquences sont exprimées en multiples de /F_0/, fréquence du /do/ :

| Notes | Pythagore | Zarlino | Tempérament égal |
|-------+-----------+---------+------------------|
| si    | 1.8984    | 1.875   | 1.8877           |
| la    | 1.6875    | 1.6667  | 1.6818           |
| sol   | 1.5       | 1.5     | 1.4983           |
| fa    | 1.3333    | 1.3333  | 1.3348           |
| mi    | 1.2656    | 1.25    | 1.26             |
| ré    | 1.125     | 1.125   | 1.1225           |
| do    | 1         | 1       | 1                |


* Chromatisme

#+TOC: headlines 1 local

** Altérations

Dans la suite croissante suivante :

#+begin_center
do   ré   mi   fa   sol   la   si   do
#+end_center

toutes les notes consécutives sont séparées par un ton, à l’exception
des écarts :

#+ATTR_HTML: :class plat
| mi | — | fa |
| si | — | do |

qui valent chacun un demi-ton.

Que se passerait-il si nous voulions obtenir temporairement un écart
d’un demi-ton entre deux notes habituellement séparées par un ton
entier ? Il faudrait alors hausser ou abaisser d’un demi-ton un des
notes impliquées.

Une *altération haussière* consiste à hausser une note d’un demi-ton.

Une *altération baissière* consiste à baisser une note d’un demi-ton.

#+begin_center
⁂
#+end_center

Considérons pour illustrer les notes /fa/ et /sol/, qui sont séparées
par un ton. Si nous haussons le /fa/ d’un demi-ton, ou si nous
abaissons le /sol/ d’un demi-ton, l’écart /fa — sol/ se réduit à un
demi-ton comme souhaité.


** Dièses et bémols

Une note naturelle peut être altérée :

  - d’un demi-ton vers le haut par un *dièse* (symbolisé par un *#*)
  - d’un demi-ton vers le bas par un *bémol* (symbolisé par un *b*)

Une note ainsi altérée est dite *chromatique*.

Les altérations d’une note /X/ s’écrivent donc :

| Altération               | Nom   | Notation |
|--------------------------+-------+----------|
| haussière : + 1 demi-ton | dièse | X^{#}    |
| baissière : − 1 demi-ton | bémol | X^b      |


*** Doubles

Il arrive que le contexte musical emploie déjà abondamment une note
altérée par un dièse ou un bémol. Dans ce cas, comment distinguer une
altération temporaire supplémentaire ? C’est là qu’interviennent les
altérations doubles. Une note naturelle peut être altérée :

  - de deux demi-tons vers le haut par un double dièse (symbolisé par
    un *##*)
  - de deux demi-tons vers le bas par un double bémol (symbolisé par
    un *bb*)

Les altérations doubles d’une note /X/ s’écrivent donc :

| Altération                | Nom          | Notation |
|---------------------------+--------------+----------|
| haussière : + 2 demi-tons | double dièse | X^{##}   |
| baissière : − 2 demi-tons | double bémol | X^bb     |


** Enharmonie

Dans un tempérament égal, une *enharmonie* est constitutée de deux
notes de même fréquence obtenues par des altérations différentes.

Deux notes liées par une enharmonie sont qualifiées d’*enharmoniques*.


*** Notes séparées par un ton

Choisissons deux notes séparées par un ton, par exemple /do/ et /ré/.
Les demi-tons tempérés étant tous égaux et valant exactement la moitié
d’un ton, on réalise qu’on obtient la même hauteur de son en haussant
le /do/ d’un demi-ton qu’en abaissant le /ré/ d’un demi-ton. On a
donc :

#+begin_center
do^{#}  =  ré^b
#+end_center

On dit alors que le /do #/ est *l’enharmonie* du /ré^b/.


*** Notes séparées par un demi-ton

Choisissons deux notes séparées par un demi-ton, par exemple /mi/ et
/fa/.

Les demi-tons tempérés étant tous égaux, on réalise qu’on obtient la
même hauteur de son en haussant le /mi/ d’un demi-ton qu’en jouant le
/fa/. On a donc l’enharmonie :

#+begin_center
mi^{#}  =  fa
#+end_center

En suivant un raisonnement analogue, on réalise qu’on obtient la même
hauteur de son en abaissant le /fa/ d’un demi-ton qu’en jouant le
/mi/. On a donc l’enharmonie :

#+begin_center
fa^b  =  mi
#+end_center


*** Relations enharmoniques

En appliquant le raisonnement précédent à toutes les notes, on obtient
les relations enharmoniques :

| do^{#}  | = | ré^b  |
| ré^{#}  | = | mi^b  |
| mi      | = | fa^b  |
| mi^{#}  | = | fa    |
| fa^{#}  | = | sol^b |
| sol^{#} | = | la^b  |
| la^{#}  | = | si^b  |
| si      | = | do^b  |
| si^{#}  | = | do    |


*** Autres tempéraments

On peut étendre les relations enharmoniques à un tempérament
quelconque. Il faut toutefois garder à l’esprit que, lorsque le
tempérament n’est pas égal, les fréquences de deux notes enharmoniques
ne sont pas rigoureusement identiques, un léger décalage de fréquence
est observé.


** Listes

Voici la liste des notes naturelles et chromatiques réunies et
triées avec les plus graves en bas du tableau :

| Notes   |        |       Écarts en demi-tons |
|         |        | par rapport au *do* grave |
|---------+--------+---------------------------|
| do      | si^{#} |                        12 |
| si      | do^b   |                        11 |
| la^{#}  | si^b   |                        10 |
| la      |        |                         9 |
| sol^{#} | la^b   |                         8 |
| sol     |        |                         7 |
| fa^{#}  | sol^b  |                         6 |
| fa      | mi^{#} |                         5 |
| mi      | fa^b   |                         4 |
| ré^{#}  | mi^b   |                         3 |
| ré      |        |                         2 |
| do^{#}  | ré^b   |                         1 |
| do      | si^{#} |                         0 |


*** Doubles

Voici quelques exemples d’altérations doubles :

| Notes    |        |       Écarts en demi-tons |
|          |        | par rapport au *do* grave |
|----------+--------+---------------------------|
| la       | si^bb  |                         9 |
| la^{##}  | si     |                        11 |
| sol      | la^bb  |                         7 |
| sol^{##} | la     |                         9 |
| fa       | sol^bb |                         5 |
| fa^{##}  | sol    |                         7 |
| mi^b     | fa^bb  |                         3 |
| mi^{##}  | fa^{#} |                         6 |
| ré^{##}  | mi     |                         4 |
| ré       | mi^bb  |                         2 |
| do^{##}  | ré     |                         2 |
| do       | ré^bb  |                         0 |


* Intervalles

#+TOC: headlines 1 local


** Introduction

Un intervalle est nommé d’après le nombre de notes distinctes qu’il
faut parcourir pour aller de la première note (la plus grave) à la
deuxième (la plus aiguë). Les notes de départ et d’arrivée sont
inclues dans le décompte.

L’intervalle entre deux notes identiques porte le nom particulier
*d’unisson*, qui signifie « un seul son ».

/Remarque/ : les intervalles étant présentés sous formes de suites
croissantes, l’octave est implicite.

Voici la liste des principaux intervalles :

| Nombre de notes | Intervalle  |                |                                                |
|      parcourues | Nom         | Notes extrêmes | Notes parcourues                               |
|-----------------+-------------+----------------+------------------------------------------------|
|               1 | unisson     | do — do        | do                                             |
|               2 | seconde     | do — ré        | do ré                                          |
|               3 | tierce      | do — mi        | do ré mi                                       |
|               4 | quarte      | do — fa        | do ré mi fa                                    |
|               5 | quinte      | do — sol       | do ré mi fa sol                                |
|               6 | sixte       | do — la        | do ré mi fa sol la                             |
|               7 | septième    | do — si        | do ré mi fa sol la si                          |
|               8 | octave      | do — do        | do ré mi fa sol la si do                       |
|               9 | neuvième    | do — ré        | do ré mi fa sol la si do ré                    |
|              10 | dixième     | do — mi        | do ré mi fa sol la si do ré mi                 |
|              11 | onzième     | do — fa        | do ré mi fa sol la si do ré mi fa              |
|              12 | douzième    | do — sol       | do ré mi fa sol la si do ré mi fa sol          |
|              13 | treizième   | do — la        | do ré mi fa sol la si do ré mi fa sol la       |
|              14 | quatorzième | do — si        | do ré mi fa sol la si do ré mi fa sol la si    |
|              15 | quinzième   | do — do        | do ré mi fa sol la si do ré mi fa sol la si do |


** Justes

Certains intervalles recouvrent un nombre de demi-tons qui reste fixe,
et ce quelle que soit la note de départ choisie. Ces intervalles sont
parfois qualifiés de *justes*, bien que ce qualificatif reste
généralement implicite.

L’ *unisson* contient invariablement zéro demi-tons. C’est donc un
intervalle juste.

L’ *octave* contient invariablement douze demi-tons. C’est donc un
intervalle juste.


*** Quinte

La *quinte* contient sept demi-tons, à une seule exception près, qui
en contient six :

| Quintes  | Écarts en |
|          | demi-tons |
|----------+-----------|
| do — sol |         7 |
| ré — la  |         7 |
| mi — si  |         7 |
| fa — do  |         7 |
| sol — ré |         7 |
| la — mi  |         7 |
| si — fa  |         6 |

Toutes les quintes sont donc justes, à l’exception de /si — fa/, qui
sera appelée *quinte diminuée*.


*** Quarte

La *quarte*  contient cinq demi-tons, à une seule exception près,
qui en contient six :

| Quartes  | Écarts en demi-tons |
|----------+---------------------|
| sol — do |                   5 |
| la — ré  |                   5 |
| si — mi  |                   5 |
| do — fa  |                   5 |
| ré — sol |                   5 |
| mi — la  |                   5 |
| fa — si  |                   6 |

Toutes les quartes sont donc justes, à l’exception de /fa — si/, qui
sera appelée *quarte augmentée*, ou encore *triton*, parce qu’elle
parcourt trois tons.


*** Récapitulation

| Intervalles | Abréviations | Exemple        | Écarts en |
| justes      |              | Notes extrêmes | demi-tons |
|-------------+--------------+----------------+-----------|
| unisson     | 1son         | do — do        |         0 |
| quarte      | 4te          | do — fa        |         5 |
| quinte      | 5te          | do — sol       |         7 |
| octave      | 8ve          | do — do        |        12 |


** Majeurs, mineurs

Les intervalles dont l’amplitude varie avec la note de départ choisie
sont qualifiés de *majeurs* ou de *mineurs* suivant le nombre de
demi-tons qui sépare les notes extrêmes. Les intervalles majeurs sont
alors un demi-ton plus grand que les intervalles mineurs.

Dans le cadre des intervalles, on utilise les abréviations :

| majeur | M |
| mineur | m |

Le tableau suivant reprend les intervalles majeurs et mineurs contenus
dans l’octave :

| Intervalles      | Abréviations | Écarts en | Exemple        |
|                  |              | demi-tons | Notes extrêmes |
|------------------+--------------+-----------+----------------|
| seconde mineure  | 2de m        |         1 | mi — fa        |
| seconde majeure  | 2de M        |         2 | do — ré        |
| tierce mineure   | 3ce m        |         3 | la — do        |
| tierce majeure   | 3ce M        |         4 | do — mi        |
| sixte mineure    | 6te m        |         8 | la — fa        |
| sixte majeure    | 6te M        |         9 | do — la        |
| septième mineure | 7e m         |        10 | la — sol       |
| septième majeure | 7e M         |        11 | do — si        |


** Augmentés, diminués

Un intervalle *augmenté* est un intervalle juste ou majeur auquel on a
ajouté un demi-ton, ou un intervalle mineur auquel on a ajouté deux
demi-tons.

Un intervalle *diminué* est un intervalle juste ou mineur auquel on a
retiré un demi-ton, ou un intervalle majeur auquel on a retiré deux
demi-tons.

Dans le cadre des intervalles, on utilise les abréviations :

| augmenté | aug |
| diminué  | dim |


*** Altérations

L’ajout ou le retrait d’un demi-ton s’effectue généralement en
altérant une des notes qui constituent l’intervalle.

Notons toutefois que l’intervalle /fa — si/ est une quarte augmentée,
sans qu’aucune altération soit présente. Il en va de même pour
l’intervalle renversé /si — fa/, qui est une quinte diminuée.


*** Augmentés

Voici quelques exemples d’intervalles augmentés :

| Intervalles        | Abréviations | Exemple        | Écarts en |
|                    |              | Notes extrêmes | demi-tons |
|--------------------+--------------+----------------+-----------|
| unisson augmenté   | 1son aug     | do — do^{#}    |         1 |
|                    |              | do^b — do      |           |
| seconde augmentée  | 2de aug      | do — ré^{#}    |         3 |
|                    |              | mi^b — fa^{#}  |           |
| tierce augmentée   | 3ce aug      | do — mi^{#}    |         5 |
|                    |              | la^b — do^{#}  |           |
| quarte augmentée   | 4te aug      | do — fa^{#}    |         6 |
|                    |              | fa — si        |           |
| quinte augmentée   | 5te aug      | do — sol^{#}   |         8 |
|                    |              | la^b — mi      |           |
| sixte augmentée    | 6te aug      | do — la^{#}    |        10 |
|                    |              | la^b — fa^{#}  |           |
| septième augmentée | 7e aug       | do — si^{#}    |        12 |
|                    |              | la^b — sol^{#} |           |
| octave augmentée   | 8ve aug      | do — do^{#}    |        13 |
|                    |              | la^b — la      |           |


**** Triton

La quarte augmentée est aussi appelée *triton* (abréviation *3ton*),
parce qu’elle parcourt trois tons.


*** Diminués

Voici quelques exemples d’intervalles diminués :

| Intervalles       | Abréviations | Exemple        | Écarts en |
|                   |              | Notes extrêmes | demi-tons |
|-------------------+--------------+----------------+-----------|
| seconde diminuée  | 2de dim      | mi — fa^b      |         0 |
|                   |              | do^{#} — ré^b  |           |
| tierce diminuée   | 3ce dim      | la — do^b      |         2 |
|                   |              | do^{#} — mi^b  |           |
| quarte diminuée   | 4te dim      | la — ré^b      |         4 |
| quinte diminuée   | 5te dim      | do — sol^b     |         6 |
|                   |              | si — fa        |           |
| sixte diminuée    | 6te dim      | la^{#} — fa    |         7 |
|                   |              | do^{#} — la^b  |           |
| septième diminuée | 7e dim       | la^{#} — sol   |         9 |
|                   |              | do^{#} — si^b  |           |
| octave diminuée   | 8ve dim      | do — do^b      |        11 |
|                   |              | do^{#} — do    |           |


*** Relations enharmoniques

Les intervalles augmentés et diminués sont souvent liés
enharmoniquement à des intervalles majeurs, mineurs ou justes. Par
exemple, la septième augmentée :

#+begin_center
do — si^{#}
#+end_center

est enharmoniquement équivalente à l’octave :

#+begin_center
do — do
#+end_center

La sixte augmentée :

#+begin_center
do — la^{#}
#+end_center

est enharmoniquement équivalente à la septième mineure :

#+begin_center
do — si^b
#+end_center

La seconde diminuée :

#+begin_center
do^{#} — ré^b
#+end_center

est enharmoniquement équivalente à l’unisson :

#+begin_center
do^{#} — do^{#}
#+end_center


** Sur-augmentés, sur-diminués

Un intervalle *sur-augmenté* est un intervalle juste ou majeur auquel
on a ajouté deux demi-tons.

Un intervalle *sur-diminué* est un intervalle juste ou mineur auquel
on a retiré deux demi-tons.

Dans le cadre des intervalles, on utilise les abréviations :

| sur-augmenté | suraug |
| sur-diminué  | surdim |


*** Sur-augmentés

Voici quelques exemples d’intervalles sur-augmentés :

| Intervalles           | Abréviations | Exemple        | Écarts en |
|                       |              | Notes extrêmes | demi-tons |
|-----------------------+--------------+----------------+-----------|
| unisson sur-augmenté  | 1son suraug  | do^b — do^{#}  |         2 |
| seconde sur-augmentée | 2de suraug   | sol^b — la^{#} |         4 |
| tierce sur-augmentée  | 3ce suraug   | do^b — mi^{#}  |         6 |


*** Sur-diminués

Voici quelques exemples d’intervalles sur-diminués :

| Intervalles         | Abréviations | Exemple        | Écarts en |
|                     |              | Notes extrêmes | demi-tons |
|---------------------+--------------+----------------+-----------|
| tierce sur-diminuée | 3ce surdim   | mi^{#} — sol^b |         1 |
| quarte sur-diminuée | 4te surdim   | ré^{#} — sol^b |         3 |
| quinte sur-diminuée | 5te surdim   | do^{#} — sol^b |         5 |


*** Relations enharmoniques

Par exemple, l’unisson sur-augmenté :

#+begin_center
ré^b — ré^{#}
#+end_center

est enharmoniquement équivalent à la seconde majeure :

#+begin_center
do^{#} — ré^{#}
#+end_center


** Redoublements

Lorsqu’on ajoute une octave à un intervalle, on obtient le
*redoublement* de cet intervalle. On dit alors que l’intervalle
original est *redoublé*.

Voici les redoublements des intervalles compris entre l’unisson et
l’octave :

| Intervalle       | Redoublement        | Écarts en demi-tons |
|------------------+---------------------+---------------------|
| unisson          | octave              |                  12 |
| seconde mineure  | neuvième mineure    |                  13 |
| seconde majeure  | neuvième majeure    |                  14 |
| tierce mineure   | dixième mineure     |                  15 |
| tierce majeure   | dixième majeure     |                  16 |
| quarte           | onzième             |                  17 |
| quarte augmentée | onzième augmentée   |                  18 |
| quinte diminuée  | douzième diminuée   |                  18 |
| quinte           | douzième            |                  19 |
| sixte mineure    | treizième mineure   |                  20 |
| sixte majeure    | treizième majeure   |                  21 |
| septième mineure | quatorzième mineure |                  22 |
| septième majeure | quatorzième majeure |                  23 |
| octave           | quinzième           |                  24 |


*** Généralisation

Par généralisation, un intervalle redoublé peut désigner l’intervalle
original auquel on ajoute une ou plusieurs octaves.


** Simplification

La *simplification* consiste à retirer autant d’octaves que nécessaire
à un intervalle pour obtenir un intervalle *simplifié* compris entre
l’unisson et l’octave.

Prenons par exemple la douzième /do — sol/ :

#+begin_center
do ré mi fa sol la si do ré mi fa sol
#+end_center

Si nous lui retirons une octave, nous obtenons une quinte comme
intervalle simplifié :

#+begin_center
do ré mi fa sol
#+end_center


** Renversements

Le *renversement* d’un intervalle est l’intervalle que l’on obtient
lorsqu’on inverse les notes de départ et d’arrivée.

Prenons par exemple la tierce /do — mi/ :

#+begin_center
do ré mi
#+end_center

Si on inverse le /do/ et le /mi/, on obtient l’intervalle /mi — do/,
qui est une sixte :

#+begin_center
mi fa sol la si do
#+end_center

On remarque que si on fusionne l’intervalle d’origine avec son
renversement, on obtient :

#+begin_center
do ré mi mi fa sol la si do
#+end_center

Le deuxième /mi/ de la série est redondant et peut donc être supprimé.
On se retrouve alors avec l’octave /do — do/ :

#+begin_center
do ré mi fa sol la si do
#+end_center

Il en va de même pour chaque intervalle compris entre la seconde
mineure et la septième majeure : son renversement le complète pour
former une octave.

Afin de rester cohérent avec ce résultat, on convient que :

  - l’octave est le renversement de l’unisson
  - l’unisson est le renversement de l’octave


*** Tableau

Le tableau suivant nous donne les renversement de tous les intervalles
compris entre l’unisson et l’octave :

| Intervalle       | Renversement     | Exemple    |              |
|                  |                  | Intervalle | Renversement |
|------------------+------------------+------------+--------------|
| unisson          | octave           | do — do    | do — do      |
| seconde mineure  | septième majeure | mi — fa    | fa — mi      |
| seconde majeure  | septième mineure | do — ré    | ré — do      |
| tierce mineure   | sixte majeure    | la — do    | do — la      |
| tierce majeure   | sixte mineure    | do — mi    | mi — do      |
| quarte           | quinte           | do — fa    | fa — fa      |
| quarte augmentée | quinte diminuée  | fa — si    | si — fa      |
| quinte diminuée  | quarte augmentée | si — fa    | fa — si      |
| quinte           | quarte           | do — sol   | sol — do     |
| sixte mineure    | tierce majeure   | la — fa    | fa — la      |
| sixte majeure    | tierce mineure   | do — la    | la — do      |
| septième mineure | seconde majeure  | la — sol   | sol — la     |
| septième majeure | seconde mineure  | do — si    | si — do      |
| octave           | unisson          | do — do    | do — do      |


*** Au-delà de l’octave

Lorsqu’un intervalle dépasse l’octave, on convient que son
renversement est égal au renversement de l’intervalle simplifié.

Prenons par exemple la douzième /do — sol/ :

#+begin_center
do ré mi fa sol la si do ré mi fa sol
#+end_center

L’intervalle simplifié correspondant est la quinte :

#+begin_center
do ré mi fa sol
#+end_center

Le renversement de cette quinte est la quarte /sol — do/ :

#+begin_center
sol la si do
#+end_center

Le renversement d’une douzième est donc une quarte.


** Purs

#+TOC: headlines 1 local

*** Introduction

Les *intervalles purs* sont des intervalles dont les ratios de
fréquences sont issus de la série des harmoniques naturelles.

Bien sûr, la suite des notes diatoniques tempérées ne pourra nous
fournir qu’une approximation de ces intervalles. Si nous choisissons
un /do/ comme note fondamentale, nous obtenons ;

#+ATTR_HTML: :class plat
| /octaves/   | : |  0 |  1 |   1 |  2 |  2 |   2 |    2 |  3 |  3 |  3 |      3 |   3 | =...= |
| /notes/     | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |

Nous allons à présent adapter légèrement ces notes afin qu’elles
s’ajustent avec précision sur les multiples entiers de la fréquence de
base :

#+ATTR_HTML: :class plat
| /octaves/   | : |  0 |  1 |   1 |  2 |  2 |   2 |    2 |  3 |  3 |  3 |      3 |   3 | =...= |
| /notes/     | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /multiples/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Cet ajustement n’est pas destiné à assembler un tempérament digne de
ce nom, car la formation de certains intervalles purs ne peut se faire
qu’au détriment d’autres. Par exemple, la tierce mineure /mi — sol/
est pure (ratio 6/5), mais la tierce mineure /sol —si^b/, de ratio
7/6, est complètement faussée.

L’objectif est ici d’obtenir les ratios des intervalles purs que nous
ne connaissons pas encore, puis de les comparer avec ceux des
différents tempéraments. En examinant les notes de la série, on
obtient :

| Intervalle       | Octaves |   | Notes |        | Multiples |    | Ratio de  |
| harmonique       |         |   |       |        |           |    | fréquence |
|------------------+---------+---+-------+--------+-----------+----+-----------|
| unisson          |       0 | 0 | do    | do     |         1 |  1 | 1         |
| octave           |       0 | 1 | do    | do     |         1 |  2 | 2         |
| quinte           |       1 | 1 | do    | sol    |         2 |  3 | 3 / 2     |
| quarte           |       1 | 2 | sol   | do     |         3 |  4 | 4 / 3     |
| tierce majeure   |       2 | 2 | do    | mi     |         4 |  5 | 5 / 4     |
| tierce mineure   |       2 | 2 | mi    | sol    |         5 |  6 | 6 / 5     |
| sixte majeure    |       1 | 2 | sol   | mi     |         3 |  5 | 5 / 3     |
| sixte mineure    |       2 | 3 | mi    | do     |         5 |  8 | 8 / 5     |
| septième mineure |       2 | 2 | do    | si^b   |         4 |  7 | 7 / 4     |
| seconde majeure  |       3 | 3 | do    | ré     |         8 |  9 | 9 / 8     |
| quarte augmentée |       3 | 3 | do    | fa^{#} |         8 | 11 | 11 / 8    |

Ces premiers résultats vont nous permettre d’en déduire d’autres.


*** Seconde mineure

La seconde mineure empilée sur une tierce majeure forme une quarte :

#+begin_center
5 / 4 × 2de m = 4 / 3
#+end_center

On en déduit une première valeur :

#+begin_center
2de m = 4 / 3 × 4 / 5 = 16 / 15
#+end_center

La seconde mineure empilée sur une tierce mineure forme une tierce
majeure :

#+begin_center
6 / 5 × 2de m = 5 / 4
#+end_center

On en déduit une autre valeur, proche de la première :

#+begin_center
2de m = 5 / 6 × 5 / 4 = 25 / 24
#+end_center


*** Septième majeure

La septième majeure empilée sur une seconde mineure forme une octave :

#+begin_center
16 / 15 × 7e M = 2
#+end_center

En partant de la première valeur de la seconde mineure, on en déduit :

#+begin_center
7e M = 2 × 15 / 16 = 15 / 8
#+end_center

En partant de la seconde valeur de la seconde mineure, on en déduit :

#+begin_center
7e M = 2 × 24 / 25 = 48 / 25
#+end_center


*** Quinte diminuée

En empilant deux tierces mineures, on obtient une quinte diminuée :

#+begin_center
5te dim = (6 / 5)^2
#+end_center

On en déduit que :

#+begin_center
5te dim = 36 / 25
#+end_center


*** Quinte augmentée

En empilant deux tierces majeures, on obtient une quinte augmentée :

#+begin_center
5te aug = (5 / 4)^2
#+end_center

On en déduit que :

#+begin_center
5te aug = 25 / 16
#+end_center


*** Septième diminuée

En empilant trois tierces mineures, on obtient une septième diminuée :

#+begin_center
7te dim = (6 / 5)^3
#+end_center

On en déduit que :

#+begin_center
7te dim = 216 / 125
#+end_center


*** Synthèse

Le tableau ci-dessous nous donne la liste des intervalles purs et la
comparaison avec les intervalles issus des tempéraments pythagoricien,
zarlinien ou égal. Notons que dans le cas du tempérament zarlinien,
l’intervalle peut varier légèrement suivant les notes choisies ; nous
ne reprenons dans ce cas que les choix les plus proches de
l’intervalle pur correspondant :

| Intervalle        | Ratio de fréquence |               |           |              |
|                   | Pur                | Pythagoricien | Zarlinien | Tempéré égal |
|-------------------+--------------------+---------------+-----------+--------------|
| unisson           | 1                  | 1             | 1         |            1 |
| seconde mineure   | 16 / 15            | 256 / 243     | 16 / 15   |       1.0595 |
|                   | 25 / 24            |               |           |              |
| seconde majeure   | 9 / 8              | 9 / 8         | 9 / 8     |       1.1225 |
|                   |                    |               | 10 / 9    |              |
| tierce mineure    | 6 / 5              | 32 / 27       | 6 / 5     |       1.1892 |
| tierce majeure    | 5 / 4              | 81 / 64       | 5 / 4     |       1.2599 |
| quarte            | 4 / 3              | 4 / 3         | 4 / 3     |       1.3348 |
| quarte augmentée  | 11 / 8             |               |           |       1.4142 |
| quinte diminuée   | 36 / 25            | 1024 / 729    | 36 / 25   |       1.4142 |
| quinte            | 3 / 2              | 3 / 2         | 3 / 2     |       1.4983 |
| quinte augmentée  | 25 / 16            | 6561 / 4096   | 25 / 16   |       1.5874 |
| sixte mineure     | 8 / 5              | 128 / 81      | 8 / 5     |       1.5874 |
| sixte majeure     | 5 / 3              | 27 / 16       | 5 / 3     |       1.6817 |
| septième diminuée | 216 / 125          |               |           |       1.6817 |
| septième mineure  | 7 / 4              | 16 / 9        | 16 / 9    |       1.7818 |
| septième majeure  | 15 / 8             | 243 / 128     | 15 / 8    |       1.8877 |
|                   | 48 / 25            |               |           |              |
| octave            | 2                  | 2             | 2         |            2 |


* Cycles

#+TOC: headlines 1 local

** Introduction

Lorsqu’on parcourt le tempérament égal en maintenant, à l’octave près,
un intervalle constant entre les notes successives (naturelles ou
chromatiques), on finit par revenir au point de départ, formant ainsi
un *cycle*.


** Cycle des quintes


*** Quintes ascendantes

Si on choisit de monter les quintes dans un tempérament égal, on
obtient :

#+begin_center
fa do sol ré la mi si fa^{#} do^{#} sol^{#} ré^{#} la^{#} mi^{#}
#+end_center

Comme /mi^{#} = fa/, on a :

#+begin_center
fa do sol ré la mi si fa^{#} do^{#} sol^{#} ré^{#} la^{#} fa
#+end_center

Cette suite retourne à la note de départ /fa/ et forme donc un cycle
complet.


*** Quintes descendantes

Si on choisit de descendre les quintes, on obtient :

#+begin_center
si mi la ré sol do fa si^b mi^b la^b ré^b sol^b do^b
#+end_center

Comme /do^b = si/, on a :

#+begin_center
si mi la ré sol do fa si^b mi^b la^b ré^b sol^b si
#+end_center

Cette suite retourne à la note de départ /si/ et forme donc un cycle
complet.


*** Lien

Considérons le cycle des quintes ascendantes et remplaçons les dièses
en utilisant l’enharmonie :

#+begin_center
fa do sol ré la mi si sol^b ré^b la^b mi^b si^b fa
#+end_center

On peut faire tourner le cycle pour partir du /si/ :

#+begin_center
si sol^b ré^b la^b mi^b si^b fa fa do sol ré la mi
#+end_center

Le /fa/ en double est redondant et peut être simplifié. Une quinte
plus haut que le /mi/, on trouve /si/, et le cycle d’écrit :

#+begin_center
si sol^b ré^b la^b mi^b si^b fa do sol ré la mi si
#+end_center

Si on lit ce cycle de droite à gauche, on retombe sur le cycle des
quintes descendantes :

#+begin_center
si mi la ré sol do fa si^b mi^b la^b ré^b sol^b si
#+end_center

La réciproque est vraie : si on lit le cycle des quintes descendantes
à rebours, on retombe sur le cycle des quintes ascendantes.

Le cycle ascendant s’écrit généralement en utilisant les dièses, et le
cycle descendant les bémols.


*** Représentation

On représente souvent le cycle des quintes disposé sur un cercle (ici
très approximatif) :

#+ATTR_HTML: :class plat
|        |         |        | do     |     |    |    |
|        |         | fa     |        | sol |    |    |
|        | la^{#}  |        |        |     | ré |    |
| ré^{#} |         |        |        |     |    | la |
|        | sol^{#} |        |        |     | mi |    |
|        |         | do^{#} |        | si  |    |    |
|        |         |        | fa^{#} |     |    |    |

Le cycle ascendant se lit dans le sens horlogique en partant du /fa/.

Si on remplace par enharmonie les dièses par des bémols, on obtient :

#+ATTR_HTML: :class plat
|      |      |      | do    |     |    |    |
|      |      | fa   |       | sol |    |    |
|      | si^b |      |       |     | ré |    |
| mi^b |      |      |       |     |    | la |
|      | la^b |      |       |     | mi |    |
|      |      | ré^b |       | si  |    |    |
|      |      |      | sol^b |     |    |    |

Le cycle descendant se lit dans le sens anti-horlogique en partant du /si/.


** Cycle des quartes

Si on fait abstraction des octaves :

  - monter d’une quarte équivaut à descendre d’une quinte
  - descendre d’une quarte équivaut à monter d’une quinte

Ce constat nous mène aux résultats suivants :

  - le cycle des quartes ascendantes est identique au cycle des
    quintes descendantes
  - le cycle des quartes descendantes est identique au cycle des
    quintes ascendantes


** Spirale

Si on décide d’utiliser des intervalles purs à la place d’intervalles
intégrés dans un tempérament égal, on ne revient jamais tout à fait au
point de départ. On parle alors de *spirale*.


* Transposition

#+TOC: headlines 1 local

** Introduction

*Transposer* un groupe de notes consiste à le déplacer d’un intervalle
donné vers l’aigu ou vers le grave.

Au cours d’une *transposition*, chaque note est donc décalée d’un même
intervalle vers le haut ou vers le bas.


** Conservation des intervalles internes

Nous allons montrer que les intervalles internes d’un groupe de notes
sont conservés lors d’une transposition.

Illustrons cette idée en prenant comme exemple la suite de notes suivante :

#+begin_center
do   mi   ré
#+end_center

Si nous transposons cette suite d’une quinte vers le haut, nous obtenons :

#+begin_center
sol   si   la
#+end_center

On constate que les intervalles internes sont identiques avant et
après transposition :

| Notes originales | Notes transposées |
|------------------+-------------------|
| do — mi          | sol — si          |
| mi — ré          | si — la           |


*** Raisonnement générique

Fixons une note de référence /R/ à une fréquence choisie /F_R/. Nous
pouvons à présent définir un groupe quelconque de notes par :

#+ATTR_HTML: :class plat
| /Notes/  | : | N_1 | N_2 | N_3 | =...= | N_m |
| /Écarts/ | : | E_1 | E_2 | E_3 | =...= | E_m |

où les /E_1/, /E_2/, ..., /E_m/ sont les nombres de demi-tons séparant
les notes du groupe de la note de référence /R/. Plus précisément :

#+begin_center
/E_k/ = nombre de demi-tons entre la note /N_k/ et la note de référence /R/
#+end_center

Si nous transposons ce groupe d’un intervalle contenant /D/ demi-tons,
nous obtenons la suite :

#+ATTR_HTML: :class plat
| /Notes/  | : | T_1     | T_2     | T_3     | =...= | T_m     |
| /Écarts/ | : | E_1 + D | E_2 + D | E_3 + D | =...= | E_m + D |

Choisissons deux notes /N_A/ et /N_B/ dans la suite originale. Ces
notes correspondent aux notes transposées /T_A/ et /T_B/, qui forment
un intervalle après transposition :

#+ATTR_HTML: :class plat
| ( E_B + D )  −  ( E_A + D ) | = | E_B + D  −  E_A − D |

Les /D/ se simplifient, et on a finalement :

#+begin_center
E_B  −  E_A
#+end_center

qui n’est rien d’autre que l’intervalle avant transposition.

Les intervalles internes au groupe sont donc bien conservés par la
transposition.


** Transposition à l’octave

L’octave est l’intervalle le plus important en musique. Il semble donc
logique d’examiner en premier les transpositions par octave ascendante
ou descendante.


*** Ascendante

Nous allons transposer les notes naturelles :

#+begin_center
do   ré   mi   fa   sol   la   si
#+end_center

d’une octave vers l’aigu. Pour ce faire, on commence par parcourir
huit notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| départ | —>  | —>  | —>  | —>  | —>  | —>  | arrivée |
| 1      | 2   | 3   | 4   | 5   | 6   | 7   | 8       |
| do     | ré  | mi  | fa  | sol | la  | si  | do      |
| ré     | mi  | fa  | sol | la  | si  | do  | ré      |
| mi     | fa  | sol | la  | si  | do  | ré  | mi      |
| fa     | sol | la  | si  | do  | ré  | mi  | fa      |
| sol    | la  | si  | do  | ré  | mi  | fa  | sol     |
| la     | si  | do  | ré  | mi  | fa  | sol | la      |
| si     | do  | ré  | mi  | fa  | sol | la  | si      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | do      |                  12 |
| ré     | ré      |                  12 |
| mi     | mi      |                  12 |
| fa     | fa      |                  12 |
| sol    | sol     |                  12 |
| la     | la      |                  12 |
| si     | si      |                  12 |

Toutes les octaves contiennent 12 demi-tons et sont donc justes.

La transposition par octave ascendante ne nécessite donc aucune
altération parmi les notes naturelles.


*** Descendante

Nous allons transposer les notes naturelles :

#+begin_center
do   ré   mi   fa   sol   la   si
#+end_center

d’une octave vers le grave. Pour ce faire, on commence par parcourir
huit notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| départ | —>  | —>  | —>  | —>  | —>  | —>  | arrivée |
| 1      | 2   | 3   | 4   | 5   | 6   | 7   | 8       |
| do     | si  | la  | sol | fa  | mi  | ré  | do      |
| ré     | do  | si  | la  | sol | fa  | mi  | ré      |
| mi     | ré  | do  | si  | la  | sol | fa  | mi      |
| fa     | mi  | ré  | do  | si  | la  | sol | fa      |
| sol    | fa  | mi  | ré  | do  | si  | la  | sol     |
| la     | sol | fa  | mi  | ré  | do  | si  | la      |
| si     | la  | sol | fa  | mi  | ré  | do  | si      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | do      |                  12 |
| ré     | ré      |                  12 |
| mi     | mi      |                  12 |
| fa     | fa      |                  12 |
| sol    | sol     |                  12 |
| la     | la      |                  12 |
| si     | si      |                  12 |

Toutes les octaves contiennent 12 demi-tons et sont donc justes.

La transposition par octave descendante ne nécessite donc aucune
altération parmi les notes naturelles.


*** Conclusion

Une transposition à l’octave ne nécessite aucune altération parmi les
notes naturelles.


** Transposition à la quinte

Après l’octave, la quinte est l’intervalle le plus important en
musique. Nous allons donc examiner les transpositions par quinte
ascendante ou descendante.


*** Ascendante

Nous allons transposer les notes naturelles :

#+begin_center
do   ré   mi   fa   sol   la   si
#+end_center

d’une quinte vers l’aigu. Pour ce faire, on commence par parcourir
cinq notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| départ | —>  | —>  | —>  | arrivée |
| 1      | 2   | 3   | 4   | 5       |
| do     | ré  | mi  | fa  | sol     |
| ré     | mi  | fa  | sol | la      |
| mi     | fa  | sol | la  | si      |
| fa     | sol | la  | si  | do      |
| sol    | la  | si  | do  | ré      |
| la     | si  | do  | ré  | mi      |
| si     | do  | ré  | mi  | fa      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | sol     |                   7 |
| ré     | la      |                   7 |
| mi     | si      |                   7 |
| fa     | do      |                   7 |
| sol    | ré      |                   7 |
| la     | mi      |                   7 |
| si     | fa      |                   6 |

Toutes les quintes contiennent 7 demi-tons et sont donc justes, à
l’exception de la quinte ascendante /si — fa/ qui n’en contient que
6 ; il s’agit donc d’une quinte diminuée.

Comme l’intervalle de transposition doit être strictement le même pour
toutes les notes, on doit remédier à cette situation en augmentant de
1 le nombre de demi-tons de la quinte diminuée. On est donc amenés à
altérer vers le haut le /fa/ final, qui devient un /fa^{#}/. La
transposition devient alors :

#+ATTR_HTML: :class plat
| départ | —> | arrivée |
| do     |    | sol     |
| ré     |    | la      |
| mi     |    | si      |
| fa     |    | do      |
| sol    |    | ré      |
| la     |    | mi      |
| si     |    | fa^{#}  |

La transposition par quinte ascendante ne nécessite donc qu’une seule
altération parmi les notes naturelles.


*** Descendante

Nous allons transposer les notes naturelles :

#+begin_center
do   ré   mi   fa   sol   la   si
#+end_center

d’une quinte vers le grave. Pour ce faire, on commence par parcourir
cinq notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| départ | —>  | —>  | —>  | arrivée |
| 1      | 2   | 3   | 4   | 5       |
| do     | si  | la  | sol | fa      |
| ré     | do  | si  | la  | sol     |
| mi     | ré  | do  | si  | la      |
| fa     | mi  | ré  | do  | si      |
| sol    | fa  | mi  | ré  | do      |
| la     | sol | fa  | mi  | ré      |
| si     | la  | sol | fa  | mi      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | fa      |                   7 |
| ré     | sol     |                   7 |
| mi     | la      |                   7 |
| fa     | si      |                   6 |
| sol    | do      |                   7 |
| la     | ré      |                   7 |
| si     | mi      |                   7 |

Toutes les quintes contiennent 7 demi-tons et sont donc justes, à
l’exception de la quinte descendante /fa — si/ qui n’en contient que
6 ; il s’agit donc d’une quinte diminuée.

Comme l’intervalle de transposition doit être strictement le même pour
toutes les notes, on doit remédier à cette situation en augmentant de
1 le nombre de demi-tons de la quinte diminuée. On est donc amenés à
altérer vers le bas le /si/ final, qui devient un /si^b/. La
transposition devient alors :

#+ATTR_HTML: :class plat
| départ | —> | arrivée |
| do     |    | fa      |
| ré     |    | sol     |
| mi     |    | la      |
| fa     |    | si^b    |
| sol    |    | do      |
| la     |    | ré      |
| si     |    | mi      |

La transposition par quinte descendante ne nécessite donc qu’une seule
altération parmi les notes naturelles.


*** Conclusion

Une transposition à la quinte ne nécessite qu’une seule altération
parmi les notes naturelles.


** Combinaison

#+TOC: headlines 1 local

*** Introduction

Il est possible de *combiner* deux ou plusieurs transpositions afin de
former une transposition complexe.

Inversément, il est possible de *décomposer* une transposition simple
en passant par une ou plusieurs étapes intermédiaires, ce qui nous
donne alors une transposition complexe reproduisant le même résultat.


*** Deux quintes ascendantes

Nous allons effectuer une double transposition de quinte ascendante
sur la série des notes naturelles :

#+begin_center
do   ré   mi   fa   sol   la   si
#+end_center

Chaque étape transpose donc ces notes d’une quinte vers l’aigu. La
première transposition nous mène à une étape intermédiaire, et la
seconde transposition aux notes finales :

#+ATTR_HTML: :class plat
| départ | —>    | intermédiaire | —>    | arrivée |
|        | 5te ↑ |               | 5te ↑ |         |
| do     |       | sol           |       | ré      |
| ré     |       | la            |       | mi      |
| mi     |       | si            |       | fa^{#}  |
| fa     |       | do            |       | sol     |
| sol    |       | ré            |       | la      |
| la     |       | mi            |       | si      |
| si     |       | fa^{#}        |       | do^{#}  |

À ce stade, quelques remarques s’imposent :

  - chaque étape nécessite une nouvelle altération, ce qui produit
    deux altérations au total : /fa^{#}/ et /do^{#}/

  - chaque nouvelle altération produite se situe au même degré dans la
    gamme, mais une quinte plus haut

    + les altérations suivent donc le cycle des quintes ascendantes

  - la transposition combinée équivaut à une transposition simple
    d’une /neuvième majeure ascendante/

La neuvième majeure correspondant au redoublement de la seconde
majeure, il est possible de décomposer la transposition associée en
une /octave ascendante/ suivie d’une /seconde majeure ascendante/.

Comme la transposition à l’octave n’engendre aucune altération, on en
déduit que la transposition *d’une seconde majeure ascendante* est
équivalente, du point de vue des altérations produites, à une
transposition combinée de *deux quintes ascendantes*.

Nous disposons donc d’un procédé permettant de déduire facilement les
altérations produites par une transposition d’une seconde majeure vers
l’aigu.


*** Trois quintes ascendantes

On effectue une triple transposition de quinte ascendante sur la série
des notes naturelles :

#+ATTR_HTML: :class plat
| départ | —>    | inter 1 | —>    | inter 2 | —>    | arrivée |
|        | 5te ↑ |         | 5te ↑ |         | 5te ↑ |         |
| do     |       | sol     |       | ré      |       | la      |
| ré     |       | la      |       | mi      |       | si      |
| mi     |       | si      |       | fa^{#}  |       | do^{#}  |
| fa     |       | do      |       | sol     |       | ré      |
| sol    |       | ré      |       | la      |       | mi      |
| la     |       | mi      |       | si      |       | fa^{#}  |
| si     |       | fa^{#}  |       | do^{#}  |       | sol^{#} |

ce qui donne trois altérations au total : /fa^{#}/, /do^{#}/,
/sol^{#}/. Chaque nouvelle altération se produit toujours au même
degré mais une quinte plus haut. En conséquence, l’ensemble des
altérations suit le cycle des quintes ascendantes.

On remarque que la première note est passée du /do/ au /la/,
c’est-à-dire, à l’octave près, une transposition d’une /tierce
mineure descendante/.

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition *d’une tierce mineure
descendante* est équivalente, du point de vue des altérations
produites, à une transposition combinée de *trois quintes
ascendantes*.


*** Quatre quintes ascendantes

Une quadruple transposition de quinte ascendante sur la série des
notes naturelles :

#+ATTR_HTML: :class plat
| départ | —>    | inter 1 | —>    | inter 2 | —>    | inter 3 | —>    | arrivée |
|        | 5te ↑ |         | 5te ↑ |         | 5te ↑ |         | 5te ↑ |         |
| do     |       | sol     |       | ré      |       | la      |       | mi      |
| ré     |       | la      |       | mi      |       | si      |       | fa^{#}  |
| mi     |       | si      |       | fa^{#}  |       | do^{#}  |       | sol^{#} |
| fa     |       | do      |       | sol     |       | ré      |       | la      |
| sol    |       | ré      |       | la      |       | mi      |       | si      |
| la     |       | mi      |       | si      |       | fa^{#}  |       | do^{#}  |
| si     |       | fa^{#}  |       | do^{#}  |       | sol^{#} |       | ré^{#}  |

produit quatre altérations au total : /fa^{#}/, /do^{#}/, /sol^{#}/,
/ré^{#}/. Ces altérations suivent le cycle des quintes.

On remarque que la première note est passée du /do/ au /mi/,
c’est-à-dire, à l’octave près, une transposition d’une /tierce majeure
ascendante/.

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition *d’une tierce majeure
ascendante* est équivalente, du point de vue des altérations
produites, à une transposition combinée de *quatre quintes
ascendantes*.


*** Cinq quintes ascendantes

Une quintuple transposition de quinte ascendante sur la série des
notes naturelles :

#+ATTR_HTML: :class plat
| départ | —> | arrivée |
| do     |    | si      |
| ré     |    | do^{#}  |
| mi     |    | ré^{#}  |
| fa     |    | mi      |
| sol    |    | fa^{#}  |
| la     |    | sol^{#} |
| si     |    | la^{#}  |

produit cinq altérations au total : /fa^{#}/, /do^{#}/, /sol^{#}/,
/ré^{#}/, /la^{#}/. Ces altérations suivent le cycle des quintes.

On remarque que la première note est passée du /do/ au /si/,
c’est-à-dire, à l’octave près, une transposition d’une /seconde
mineure descendante/

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition *d’une seconde mineure
descendante* est équivalente, du point de vue des altérations
produites, à une transposition combinée de *cinq quintes ascendantes*.


*** Six quintes ascendantes

Une sextuple transposition de quinte ascendante sur la série des notes
naturelles :

#+ATTR_HTML: :class plat
| départ | —> | arrivée |
| do     |    | fa^{#}  |
| ré     |    | sol^{#} |
| mi     |    | la^{#}  |
| fa     |    | si^{#}  |
| sol    |    | do^{#}  |
| la     |    | ré^{#}  |
| si     |    | mi^{#}  |

produit six altérations au total : /fa^{#}/, /do^{#}/, /sol^{#}/,
/ré^{#}/, /la^{#}/, /mi^{#}. Ces altérations suivent le cycle des
quintes.

On remarque que la première note est passée du /do/ au /fa^{#}/,
c’est-à-dire, à l’octave près, une transposition d’une /quarte
augmentée ascendante/

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition d’une *quarte augmentée
ascendante* est équivalente, du point de vue des altérations
produites, à une transposition combinée de *six quintes ascendantes*.


** Récapitulation
:PROPERTIES:
:CUSTOM_ID: section:recapitulationTranspositionQuintes
:END:


*** Quintes ascendantes

Nous disposons des équivalences suivantes :

| Transposition simple | Équivalent combiné |        Nombre |
|                      |                    | d’altérations |
|----------------------+--------------------+---------------|
| 5te ascendante       | 1 x 5te ascendante |             1 |
| 2de M ascendante     | 2 x 5te ascendante |             2 |
| 3ce m descendante    | 3 x 5te ascendante |             3 |
| 3ce M ascendante     | 4 x 5te ascendante |             4 |
| 2de m descendante    | 5 x 5te ascendante |             5 |
| 4te aug ascendante   | 6 x 5te ascendante |             6 |

Les altérations produites suivent le cycle des quintes ascendantes :

#+begin_center
fa^{#} do^{#} sol^{#} ré^{#} la^{#} mi^{#} si^{#} ...
#+end_center

Pour une transposition de /N/ quintes ascendantes, il suffit
d’utiliser les /N/ premières altérations de ce cycle, en commençant
par le /fa^{#}/.


*** Quintes descendantes

En combinant des transpositions de quintes descendantes, on arrive aux
équivalences suivantes :

| Transposition simple | Équivalent combiné  |        Nombre |
|                      |                     | d’altérations |
|----------------------+---------------------+---------------|
| 5te descendante      | 1 x 5te descendante |             1 |
| 2de M descendante    | 2 x 5te descendante |             2 |
| 3ce m ascendante     | 3 x 5te descendante |             3 |
| 3ce M descendante    | 4 x 5te descendante |             4 |
| 2de m ascendante     | 5 x 5te descendante |             5 |
| 4te aug descendante  | 6 x 5te descendante |             6 |

Les altérations produites suivent le cycle des quintes descendantes :

#+begin_center
si^b mi^b la^b ré^b sol^b do^b fa^b ...
#+end_center

Pour une transposition de /N/ quintes descendantes, il suffit
d’utiliser les /N/ premières altérations de ce cycle, en commençant
par le /si^b/.


* Gamme

#+TOC: headlines 1 local


** Définition

Une *gamme* est une suite de notes parcourant une octave et ordonnées
de la plus grave à la plus aiguë. La gamme sert de fondation au
développement de la musique.

Synonyme : *échelle*.

/Remarque/ : une gamme étant un cas particulier de suite croissante,
leurs notes sont présentées avec octave implicite.


** Nombre de notes


*** Heptaphonique

Une gamme *heptaphonique* contient sept notes.

Synonyme : gamme *heptatonique*.

Exemple :

#+begin_center
do ré mi fa sol la si
#+end_center

Ces échelles sont les plus utilisées, car elles sont relativement
complètes tout en permettant un contraste entre :

  - les notes de la gamme
  - les autres notes, utilisées occasionnellement, et obtenues en
    ajoutant ou en supprimant des altérations

Dans la suite de ce traité, les gammes sont heptaphoniques par défaut.


*** Pentaphonique

Une gamme *pentaphonique* contient cinq notes.

Synonyme : gamme *pentatonique*.

On construit une gamme pentaphonique en partant d’une note choisie et
en parcourant le cycle des quintes jusqu’à inclure cinq notes.

Exemple en partant dé /do/ :

#+begin_center
do ré mi sol la
#+end_center


**** Inclusion

Pour obtenir une gamme heptaphonique qui contient une gamme
pentaphonique donnée, il suffit de continuer à parcourir le cycle des
quintes pour ajouter deux notes supplémentaires.

Inversément, une oeuvre musicale construite sur une gamme
heptaphonique peut contenir des passages utilisant préférentiellement
les notes d’une gamme pentaphonique incluse.


*** Tétraphonique

Une gamme *tétraphonique* contient quatre notes.

Synonyme : gamme *tetratonique*.

On construit une gamme tétraphonique en partant d’une note choisie et
en parcourant le cycle des quintes jusqu’à inclure quatre notes.

Exemple en partant dé /do/ :

#+begin_center
do ré sol la
#+end_center


*** Hexaphonique

Une *gamme hexaphonique* contient six notes.

Synonyme : gamme *hexatonique*.

Exemple, la gamme par tons qui part dé /do/ :

#+begin_center
do ré mi fa^{#} sol^{#} la^{#}
#+end_center


*** Dodécaphonique

Une *gamme dodécaphonique* contient les 12 demi-tons de l’octave.

Synonymes : gamme *dodécatonique*, gamme *chromatique*.

Exemple en partant de /do/ :

#+begin_center
do do^{#} ré ré^{#} mi fa fa^{#} sol sol^{#} la la^{#} si
#+end_center

ou encore, son équivalent enharmonique :

#+begin_center
do ré^b ré mi^b mi fa sol^b sol la^b la si^b si
#+end_center

Ce genre d’échelle ne permet pas de contraster les notes de la gamme
avec celles n’en faisant pas partie, car toutes les possibilités
d’altérations y sont déjà présentes.


** Degrés

Les notes d’une gamme sont comptées à partir d’une note de référence
qui devient le *degré 1*. Les notes suivantes correspondent aux degrés
2 à 7, de la note la plus grave à la plus aiguë.

Le tableau suivant nous montre un exemple de gamme construite en
choisissant /do/ comme premier degré :

| degrés |  1 |  2 |  3 |  4 |   5 |  6 |  7 |
| notes  | do | ré | mi | fa | sol | la | si |


** Octaves

Pour ne pas se limiter à une seule octave, une gamme peut être répétée
autant que nécessaire dans l’aigu et dans le grave.

L’exemple suivant nous montre une gamme étendue sur plusieurs
octaves, avec un /do/ comme premier degré et les notes les plus graves
en bas du tableau :

| Octave | Degré | Notes |
|--------+-------+-------|
|  =...= | =...= | =...= |
|      2 |     7 | si    |
|      2 |     6 | la    |
|      2 |     5 | sol   |
|      2 |     4 | fa    |
|      2 |     3 | mi    |
|      2 |     2 | ré    |
|      2 |     1 | do    |
|      1 |     7 | si    |
|      1 |     6 | la    |
|      1 |     5 | sol   |
|      1 |     4 | fa    |
|      1 |     3 | mi    |
|      1 |     2 | ré    |
|      1 |     1 | do    |
|  =...= | =...= | =...= |


** Nomenclature des degrés

On attribue un nom à chaque note de la gamme.

Les exemples de cette section utilisent une gamme construite en
utilisant un /la/ comme note de référence :

| degrés |  1 |  2 |  3 |  4 |  5 |  6 |   7 |
| notes  | la | si | do | ré | mi | fa | sol |


*** Tonique

La *tonique*, degré 1 et fondation de la gamme, est la note la plus
importante, celle qui donne le ton.

Dans notre exemple, la tonique est un /la/.


*** Dominante

Une quinte au-dessus de la tonique se trouve la *dominante*, degré 5 de
la gamme.

Par exemple, si la tonique est un /la/, la dominante sera un /mi/.


*** Sous-dominante

Une quinte en-dessous de la tonique se trouve la *sous-dominante*,
degré 4 de la gamme.

Par exemple, si la tonique est un /la/, la sous-dominante sera un /ré/.


*** Médiante

Le degré 3 est appelé *médiante* car il coupe en deux la quinte
séparant la tonique de la dominante.

#+ATTR_HTML: :class plat
| noms   | : | tonique | <— | 3ce | —> | médiante | <— | 3ce | —> | dominante |
| degrés | : |       1 | <— | 3ce | —> |        3 | <— | 3ce | —> |         5 |

Par exemple, si la tonique est un /la/, la médiante sera un /do/.


*** Sus-tonique

Le degré 2 est appelé *sus-tonique*, parce qu’il est situé un degré
au-dessus de la tonique.

Par exemple, si la tonique est un /la/, la sus-tonique sera un /mi/.


*** Sous-tonique

Le degré 7 est appelé *sous-tonique*, parce qu’il est situé un degré
en-dessous de la tonique.

Par exemple, si la tonique est un /la/, la sous-tonique sera un /sol/.


*** Sus-dominante, sous-médiante

Le degré 6 est appelé *sus-dominante* car il est situé un degré
au-dessus de la dominante.

Le degré 6 est aussi appelé *sous-médiante* car il coupe en deux la
quinte séparant la tonique de la sous-dominante :

#+ATTR_HTML: :class plat
| noms   | : | sous-dominante | <— | 3ce | —> | sous-médiante | <— | 3ce | —> | tonique |
| degrés | : |              4 | <— | 3ce | —> |             6 | <— | 3ce | —> |       1 |

Par exemple, si la tonique est un /la/, la sus-dominante sera un /fa/.


*** Tableau récapitulatif

| Degré | Nom            | Nom alternatif | Abréviation |
|-------+----------------+----------------+-------------|
|     1 | tonique        |                | T           |
|     2 | sus-tonique    |                | Tsup        |
|     3 | médiante       |                | Méd         |
|     4 | sous-dominante |                | SD          |
|     5 | dominante      |                | D           |
|     6 | sus-dominante  | sous-médiante  | Dsup        |
|     7 | sous-tonique   |                | Tinf        |


** Quintes et tierces

Le tableau suivant met en évidence les intervalles de quintes (ligne
par ligne) et de tierces (zig-zag) qui séparent les degrés de la
gamme :

#+ATTR_HTML: :class plat
|   | 4 |   | 1 |   | 5 |   |
| 2 |   | 6 |   | 3 |   | 7 |

Exemple avec /la/ pour tonique :

#+ATTR_HTML: :class plat
|    | ré |    | la |    | mi |     |
| si |    | fa |    | do |    | sol |


* Modes

#+TOC: headlines 1 local

** Introduction

L’ensemble des intervalles qui séparent les notes d’une gamme de la
tonique va produire une couleur musicale particulière : c’est ce qu’on
appelle le *mode*.

Fixer les intervalles des notes par rapport à la tonique ou entre
notes consécutives de la gamme est équivalent. C’est donc aussi le
mode qui définit les écarts entre les notes consécutives.

Puisque le mode fixe les intervalles, une gamme est pleinement définie
par la tonique et le mode qui la caractérisent.


** Modes naturels

Les modes naturels sont obtenus en choisissant comme tonique une note
naturelle quelconque et en n’altérant aucune note. Les gammes ainsi
obtenues sont appelées les *gammes modèles* des modes naturels :

| Mode        | Nom médiéval | Gamme modèle              |
|-------------+--------------+---------------------------|
| mode de si  | locrien      | si do ré mi fa sol la si  |
| mode de mi  | phrygien     | mi fa sol la si do ré mi  |
| mode de la  | éolien       | la si do ré mi fa sol la  |
| mode de ré  | dorien       | ré mi fa sol la si do ré  |
| mode de sol | mixolydien   | sol la si do ré mi fa sol |
| mode de do  | ionien       | do ré mi fa sol la si do  |
| mode de fa  | lydien       | fa sol la si do ré mi fa  |

La nomenclature médiévale provient d’une interprétation erronée des
modes grecs. Elle est toutefois fort pratique pour distinguer les
modes naturels, et est encore largement utilisés aujourd’hui.


** Nomenclature des gammes

On nomme une gamme en écrivant la tonique puis le mode.

Par exemple, une gamme de tonique /sol/ et de mode /ionien/ se nommera
/sol ionien/ ou encore /sol, mode de do/. Pour respecter les
intervalles internes de la gamme modèle du mode ionien, cette gamme
devra comporter une altération :

#+begin_center
sol la si do ré mi fa^{#} sol
#+end_center


** Transpositions

Il est possible de transposer une gamme naturelle sur une autre
tonique. Comme la transposition respecte les intervalles internes, le
mode ne sera pas altéré.


*** Par quintes ascendantes

Lorsqu’on transpose la gamme modèle du mode de /do/ :

#+begin_center
do ré mi fa sol la si do
#+end_center

d’une quinte vers le haut, on obtient :

#+begin_center
sol la si do ré mi fa^{#} sol
#+end_center

soit une altération haussière du degré 4 de l’ancienne gamme, qui
correspond au degré 7 de la nouvelle.

En continuant à parcourir les toniques séparées par des quintes
ascendantes, on est amené à hausser chaque fois le degré 4 de
l’ancienne gamme, ce qui nous donne un ordre des altérations
haussières progressant également par quintes ascendantes :

#+begin_center
fa, do, sol, ré, la, mi, si
#+end_center

On peut suivre le même procédé avec la gamme modèle de n’importe quel
mode naturel, on constate que l’ordre des altérations haussières est
toujours le même.


*** Par quintes descendantes

Lorsqu’on transpose la gamme modèle du mode de /do/ :

#+begin_center
do ré mi fa sol la si do
#+end_center

d’une quinte vers le bas, on obtient :

#+begin_center
fa sol la si^b do ré mi fa
#+end_center

soit une altération baissière du degré 7 de l’ancienne gamme, qui
correspond au degré 4 de la nouvelle.

En continuant à parcourir les toniques séparées par des quintes
descendantes, on est amené à baisser chaque fois le degré 7 de
l’ancienne gamme, ce qui nous donne un ordre des altérations
baissières progressant également par quintes descendantes :

#+begin_center
si, mi, la, ré, sol, do, fa
#+end_center

On peut suivre le même procédé avec la gamme modèle de n’importe quel
mode naturel, on constate que l’ordre des altérations haussières est
toujours le même.


*** Généralisation

On peut utiliser le cycle des quintes pour déduire les altérations de
n’importe quelle gamme d’un mode naturel.

Par exemple, si on souhaite connaître les altérations de la gamme de
/la ionien/, on part de la gamme modèle /do ionien/ et on parcourt le
cycle des quintes ascendantes pour passer de la tonique /do/ à la
tonique /la/ :

#+begin_center
do — sol — ré — la
#+end_center

On doit effectuer trois transpositions d’une quinte ascendante. La
gamme de /la ionien/ aura donc trois altérations haussières :

#+begin_center
fa^{#} do^{#} sol^{#}
#+end_center

Autre exemple, si on souhaite connaître les altérations de la gamme de
/sol éolien/, on part de la gamme modèle /la éolien/ et on parcourt le
cycle des quintes descendantes pour passer de la tonique /la/ à la
tonique /sol/ :

#+begin_center
la — ré — sol
#+end_center

On doit effectuer deux transpositions d’une quinte descendante. La
gamme de /sol éolien/ aura donc deux altérations baissières :

#+begin_center
si^b mi^b
#+end_center

#+begin_center
⁂
#+end_center

Le tableau de la section de [[#section:recapitulationTranspositionQuintes][récapitulation]] concernant les
transpositions par combinaison de quintes peut également nous aider.

Si on souhaite connaître les altérations de la gamme de /ré ionien/,
on doit partir de la gamme modèle /do ionien/. La tonique passe de
/do/ à /ré/, soit une 2de M ascendante. Le tableau nous indique que
cet intervalle correspond à deux quintes ascendantes, et donc à deux
altérations haussières : /fa^{#}/ et /do^{#}/.

Si on souhaite connaître les altérations de la gamme de /fa éolien/,
on doit partir de la gamme modèle /la éolien/. La tonique passe de
/la/ à /fa/, soit une 3ce M descendante. Le tableau nous indique que
cet intervalle correspond à quatre quintes descendantes, et donc à
quatre altérations baissières : /si^b/, /mi^b/, /la^b/, /ré^b/.


** Relatif

Deux gammes construites à partir des mêmes notes et des mêmes
altérations mais dont les toniques diffèrent sont dites *gammes
relatives* ou *relatifs*. Trouver un relatif consiste donc à faire
/tourner/ une gamme pour changer de tonique. Par exemple, la gamme de
/fa lydien/ :

#+begin_center
fa sol la si do ré mi fa
#+end_center

est le relatif /lydien/ de la gamme de /si locrien/ :

#+begin_center
si do ré mi fa fa sol la
#+end_center

Autre exemple, la gamme de /sol ionien/ :

#+begin_center
sol la si do ré mi fa^{#} sol
#+end_center

est le relatif /ionien/ de la gamme de /mi éolien/ :

#+begin_center
mi fa^{#} sol la si do ré mi
#+end_center

Dans le cas particulier d’un mode naturel, les gammes relatives se
situent par conséquent sur une même ligne dans les tableaux des
transpositions.


* Portées

#+TOC: headlines 1 local

** Introduction

Une note de musique peut être représentée par un petit cercle dessiné
sur un ensemble de lignes horizontales parallèles appelé *portée*. Le
bas de la portée correspond aux notes les plus graves, et le haut aux
notes les plus aiguës. Les notes s’écrivent chronologiquement de
gauche à droite, en commençant par la portée en haut de la page, puis
la deuxième en partant du haut, etc. Il s’agit donc d’une convention
analogue à celle de l’écriture.


** Lignes

On numérote les lignes de bas en haut.

Sur une portée classique de 5 lignes :

  - la première ligne est la plus basse
  - la cinquième ligne est la plus haute

Les notes triées de la plus grave à la plus aiguë s’écriront :

  1. sous la première ligne
  2. sur la première ligne
  3. entre la première et la deuxième ligne
  4. sur la deuxième ligne
  5. entre la deuxième et la troisième ligne
  6. sur la troisième ligne
  7. entre la troisième et la quatrième ligne
  8. sur la quatrième ligne
  9. entre la quatrième et la cinquième ligne
  10. sur la cinquième ligne
  11. au-dessus de la cinquième ligne

Il est possible d’ajouter des lignes temporaires en-desous ou
au-dessus de la portée pour étendre le registre vers l’aigu ou vers le
grave.


** Clefs

Une *clef* est un symbole figurant au début de la portée et permettant
de repérer une note de référence. Les autres notes de la portée s’en
déduisent alors aisément. Voici les différents types de clés
utilisées :

  - une clé *d’ut* donne la position sur la portée du premier /do/ que
    l’on rencontre lorsqu’on descend du /la/ de référence, de
    fréquence 440 Hz

  - une clé de *sol* donne la position sur la portée du /sol/ situé
    une quinte plus haut que le /do/ de la clef d’ut

  - une clé de *fa* donne la position sur la portée du /fa/ situé une
    quinte plus bas que le /do/ de la clef d’ut

soit :

#+begin_center
fa < do < sol < la /de fréquence 440 Hz/
#+end_center

En considérant des intervalles purs, on a :

  - le /do/ une sixte majeure plus bas que le /la/, de fréquence 440 x 3 / 5 = 264 Hz
  - le /sol/ une quinte plus haut que le /do/, de fréquence 264 x 3 / 2 = 396 Hz
  - le /fa/ une quinte plus bas que le /do/, de fréquence 264 x 2 / 3 = 176 Hz


*** Position de la clé

Suivant la position de la clé sur la portée, la hauteur des notes va
naturellement varier. Voici les principales clefs utilisées, ainsi que
leur position en partant du bas de la portée :

| Nom de la clef | Note de référence | Position   |
|----------------+-------------------+------------|
| française      | sol               | 1ère ligne |
| aiguë          | sol               | 2e ligne   |
|----------------+-------------------+------------|
| soprano        | ut (do)           | 1ère ligne |
| mezzosoprano   | ut                | 2e ligne   |
| alto           | ut                | 3e ligne   |
| ténor          | ut                | 4e ligne   |
|----------------+-------------------+------------|
| baryton        | fa                | 3e ligne   |
| basse          | fa                | 4e ligne   |
| infra-basse    | fa                | 5e ligne   |

La clef de /sol/ première ligne est celle qui permet de représenter
les notes les plus aiguës, tandis que la clef de /fa/ cinquième ligne
est celle qui permet de représenter les notes les plus graves.

Les clefs les plus utilisées sont :

  - la clef de sol 2e ligne
  - la clef d’ut 3e ligne
  - la clef de fa 4e ligne


*** Changement de clef

Un changement de clef peut s’opérer en cours de portée. On place alors
le nouveau symbole à l’endroit choisi.
