
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 03 : Clavier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Introduction

#+ATTR_HTML: :class lettrine
Il est possible de développer une analogie très poussée entre le monde
du théâtre et celui de la musique. Ainsi, une belle mélodie jouée en
solo, procurant un sentiment d’intimité et de simplicité, est
comparable à un personnage qui s’adonne au monologue, au soliloque ou
à l’aparté. Lorsque plusieurs protagonistes entament un dialogue,
plusieurs mélodies sont jouées simultanément, faisant ainsi naître une
polyphonie. Ici, le décor harmonique est dynamique, et chaque ligne
mélodique contribue à le faire évoluer. Certaines voix musicales
prennent tour à tour un rôle plus actif dans la causerie. Tantôt en
concorde, tantôt en discorde, toute la troupe bouillonne de thèmes et
d’idées qui se baladent de main en main, tissant ainsi la trame de
l’histoire. Lorsque les Muses apparaîssent au centre de cette table
ronde, une magie collective émerge des voix, dans toute la splendeur
de sa virtuosité collective. Fidèle à cette riche tradition, cette
partie du traité introduit les concepts qui vont nous permettre
d’explorer la dualité, ce fragile mais féerique équilibre entre les
dimensions mélodiques et harmoniques d’une polyphonie.


* Mélodie & Harmonie

#+TOC: headlines 1 local

** Introduction

Une *mélodie* est un ensemble de notes jouées *successivement*.

Une *harmonie* est un ensemble de notes jouées *simultanément*.


** Intervalles

Un *intervalle mélodique* est un intervalle dont les deux notes sont
jouées successivement.

Un *intervalle harmonique* est un intervalle dont les deux notes sont
jouées simultanément.


*** Unisson

Un *unisson mélodique* consiste à répéter la même note.

Un *unisson harmonique* consiste à faire jouer la même note au même
moment par deux instruments différents.


** Étendue

Un *registre* est une plage de notes.

Un *ambitus* est une étendue de notes limitée par la note la plus
aiguë et la note la plus grave d’une mélodie.

Une *tessiture* est l’étendue de notes qu’un chanteur ou un instrument
est capable de jouer.


** Motif

Un *motif* est un fragment de mélodie jouée à un rythme
donné. Un motif résulte donc de l’association d’une structure
mélodique avec une structure rythmique.

Exemple de motif :

#+ATTR_HTML: :class plat
| Mélodie | : | do | ré | sol | fa |
| Rythme  | : | B  | B  | N   | N  |


*** Thème

Un *thème* est un motif élaboré et reconnaissable, qui revient à
plusieurs reprises pendant l’oeuvre musicale.


* Mouvements mélodiques

#+TOC: headlines 1 local


** Introduction

Les *mouvements mélodiques* analysent les intervalles
d’une mélodie.


** Direction

Un intervalle mélodique est dit :

  - *ascendant* si la deuxième note est plus aiguë que la première

  - *descendant* si la deuxième note est plus grave que la première


** Mouvement conjoint

Un mouvement *conjoint* est un intervalle mélodique d’unisson ou de
seconde. Rentrent donc dans cette catégorie :

  1. l’unisson mélodique, ou répétition d’une même note
  2. la seconde mineure mélodique
  3. la seconde majeure mélodique

Voici quelques exemples de mouvements conjoints :

  - Seconde majeure ascendante : do ré
  - Seconde mineure ascendante : mi fa
  - Unisson : sol sol
  - Seconde mineure descendante : fa mi
  - Seconde majeure descendante : ré do


*** Notes conjointes

Deux notes sont dites conjointes si elles forment un intervalle
d’unisson ou de seconde.


*** Continuité

Une mélodie qui ne présente que des mouvements conjoints est dite
*continue*. Une mélodie constituée d’une majorité de mouvements
conjoints est dite majoritairement continue.


** Mouvement disjoint

Un mouvement *disjoint* est un intervalle mélodique non conjoint.
Rentrent donc dans cette catégorie :

  - les tierces
  - les quartes
  - les quintes
  - les sixtes
  - les septièmes
  - les octaves
  - les neuvièmes
  - =...=

et ce quel que soit leur qualificatif : juste, majeur, mineur,
augmenté, diminué, sur-augmenté ou sur-diminué.


*** Notes disjointes

Deux notes sont dites disjointes si elles ne sont pas conjointes.
Autrement dit, elles forment un intervalle d’au moins une tierce.

*** Discontinuité

Un mouvement disjoint provoque un *saut*, une *discontinuité* dans une
mélodie.


** Mouvement chromatique

Un mouvement *chromatique* est constitué de trois notes. La première
fait partie de la gamme en cours (ton et mode), la seconde est altérée
d’un demi-ton et la troisième poursuit le mouvement d’un demi-ton dans
la même direction afin d’atteindre la note voisine de la gamme. Les
notes initiale et finale doivent donc être séparées d’un ton entier.

Exemple de mouvement chromatique ascendant en /do majeur/ :

#+BEGIN_CENTER
ré ré^{#} mi
#+END_CENTER

Exemple de mouvement chromatique descendant en /do majeur/ :

#+BEGIN_CENTER
la la^b sol
#+END_CENTER


* Portées

#+TOC: headlines 1 local

** Introduction

Une note de musique peut être représentée par un petit cercle dessiné
sur un ensemble de lignes horizontales parallèles appelé *portée*. Le
haut de la portée correspond aux notes les plus aiguës, et le bas aux
notes les plus graves. Les notes s’écrivent chronologiquement de
gauche à droite, en commençant par la portée en haut de la page, puis
la deuxième en partant du haut, etc. Il s’agit donc d’une convention
analogue à celle de l’écriture.


** Lignes

On numérote les lignes de bas en haut.

Sur une portée classique de 5 lignes :

  - la première ligne est la plus basse
  - la cinquième ligne est la plus haute


** Clefs

Une portée est généralement munie d’une *clef* permettant de repérer
une note de référence. Les autres notes de la portée s’en déduisent
alors aisément. Voici les différents types de clés utilisées :

  - une clé *d’ut* donne la position sur la portée du premier /do/ que
    l’on rencontre lorsqu’on descend du /la/ de référence, de
    fréquence 440 Hz

  - une clé de *sol* donne la position sur la portée du /sol/ situé
    une quinte plus haut que le /do/ de la clef d’ut

  - une clé de *fa* donne la position sur la portée du /fa/ situé une
    quinte plus bas que le /do/ de la clef d’ut

soit :

#+begin_center
fa < do < sol < la /de fréquence 440 Hz/
#+end_center

En considérant des intervalles purs, on a :

  - le /do/ une sixte majeure plus bas que le /la/, de fréquence 440 x 3 / 5 = 264 Hz
  - le /sol/ une quinte plus haut que le /do/, de fréquence 264 x 3 / 2 = 396 Hz
  - le /fa/ une quinte plus bas que le /do/, de fréquence 264 x 2 / 3 = 176 Hz


*** Position de la clé

Suivant la position de la clé sur la portée, la hauteur des notes va
naturellement varier. Voici les principales clefs utilisées, ainsi que
leur position en partant du bas de la portée :

| Nom de la clef | Note de référence | Position   |
|----------------+-------------------+------------|
| Française      | Sol               | 1ère ligne |
| Aiguë          | Sol               | 2e ligne   |
|----------------+-------------------+------------|
| Soprano        | Do (Ut)           | 1ère ligne |
| Mezzosoprano   | Do                | 2e ligne   |
| Alto           | Do                | 3e ligne   |
| Ténor          | Do                | 4e ligne   |
|----------------+-------------------+------------|
| Baryton        | Fa                | 3e ligne   |
| Basse          | Fa                | 4e ligne   |
| Sous-basse     | Fa                | 5e ligne   |

La clef de /sol/ première ligne est celle qui permet de représenter
les notes les plus aiguës, tandis que la clef de /fa/ cinquième ligne
est celle qui permet de représenter les notes les plus graves.

Les clefs les plus utilisées sont :

  - la clef de sol 2e ligne
  - la clef d’ut 3e ligne
  - la clef de fa 4e ligne


** Système

Un système est un groupe de portées jouées simultanément par un ou
plusieurs instruments.


** Partition

Une partition est un ensemble de portées, ou de systèmes de portées,
contenant les notes et les indications grâce auxquelles les musiciens
vont pouvoir jouer une oeuvre musicale.


* Polyphonie

#+TOC: headlines 1 local


** Introduction

Une *polyphonie* est une superposition de plusieurs mélodies jouées
simultanément par différents instruments ou groupes d’instruments.
Chacune de ces mélodies est aussi appelée *voix*, *partie*, *ligne* ou
encore *ligne mélodique*.

Attention à ne pas confondre la notion de voix, synonyme de ligne
mélodique, avec la voix humaine, qui peut être considérée comme un
instrument de musique. En tant que ligne mélodique, une voix peut donc
être interprétée par un instrument quelconque : violon, voix humaine,
flûte, etc.


*** Instrument polyphonique

Un instrument polyphonique est un instrument capable de jouer
simultanément plusieurs lignes mélodiques. Les plus célèbres
d’entre-eux sont les instruments à clavier comme le clavecin ou le
piano. L’orgue dispose en plus d’un pédalier, permettant ainsi de
jouer avec les pieds et les mains.

Le luth, la guitare et autres instruments similaires permettent
également de jouer plusieurs notes à la fois.


** Horizontal & Vertical

La *mélodie* constitue la dimension *horizontale* d’une polyphonie, à
savoir les notes qui sont jouées consécutivement sur les voix.

L’ *harmonie* constitue la dimension *verticale* d’une polyphonie, à
savoir les groupes de notes qui sont jouées simultanément sur les
voix.

Dans une polyphonie, deux notes quelconques peuvent être jouées :

  - consécutivement (sur la même voix ou sur deux voix différentes)
  - simultanément (sur deux voix différentes)
  - avec simultanéité partielle :
    + les deux débutent au même moment, l’une s’arrête avant l’autre
    + les deux finissent au même moment, l’une débute avant l’autre
    + l’une débute avant et finit après l’autre


** Caractéristiques

Voici quelques caractéristiques propres à une polyphonie réussie :

  - *Cohérence* :

    + chaque voix fait entendre une mélodie cohérente

    + l’ensemble de la polyphonie doit être cohérent

  - *Clarté* : les voix superposées ne doivent pas surcharger
    l’oreille, on doit pouvoir entendre chacune d’entre-elles, ou du
    moins les plus importantes.

  - *Indépendance* : les voix sont indépendantes, elles alternent les
    phases de divergence et de convergence.

  - *Avant-plan* et *arrière-plan* : à tout instant, certaines voix
    sont mises en avant-plan et d’autres en arrière-plan. Le nombre de
    voix en avant-plan ne doit pas être trop élevé afin de ne pas
    surcharger l’oreille.

  - *Dialogue* : la succession des thèmes d’avant-plan mis bout à bout
    forme un ensemble cohérent qui se balade de voix en voix, donnant
    une impression de causerie où les voix se répondent.


** Notation

Dans ce traité, nous représentons une polyphonie par une
*superposition* de voix. Il s’agit en quelque sorte d’un *tableau* où
chaque voix occupe une ligne. Les voix sont disposées de la plus aiguë
à la plus grave, de haut en bas du tableau. Une voix située au-dessus
d’une autre est donc normalement plus aiguë. Précisons que chaque
colonne du tableau contient des notes jouées simultanément.

Voici un exemple :

#+ATTR_HTML: :class plat
| Va    | :     | a1    | a2    | a3    | a4    | =...= |
| Vb    | :     | b1    | b2    | b3    | b4    | =...= |
| Vc    | :     | c1    | c2    | c3    | c4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |

où :

  - Va, Vb, Vc, =...= sont les noms donnés à chacune des voix

  - a1, a2, a3, a4 ; b1, b2, b3, b4 ; c1, c2, c3, c4, =...= sont les notes jouées

Les notes a1, a2, a3, a4 sont donc jouées consécutivement tandis que
les notes a1, b1, c1 sont jouées simultanément.


*** Thèmes

On peut aussi représenter la musique comme une suite de thèmes
mélodiques, chacun étant constitué de plusieurs notes. Dans ce cas, on
symbolise chaque thème par une lettre majuscule et on représente la
polyphonie par :

#+ATTR_HTML: :class plat
| Va    | :     | A1    | A2    | A3    | A4    | =...= |
| Vb    | :     | B1    | B2    | B3    | B4    | =...= |
| Vc    | :     | C1    | C2    | C3    | C4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |

où :

  - Va, Vb, Vc, =...= sont les noms donnés à chacune des voix

  - A1, A2, A3, A4 ; B1, B2, B3, B4 ; C1, C2, C3, C4, =...= sont les
    noms donnés aux thèmes

Les thèmes A1, A2, A3, A4 sont donc joués consécutivement tandis que
les thèmes A1, B1, C1 sont joués simultanément.


*** Silences

Une voix momentanément silencieuse est représentée par un tiret, comme
la voix /V/ dans :

#+ATTR_HTML: :class plat
| V     | :     | A1    | —     | —     | A4    | =...= |
| W     | :     | B1    | B2    | B3    | B4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |


** Voix


*** Basse & Soprano

La voix la plus grave d’une polyphonie est nommée *basse*.

La voix la plus aiguë d’une polyphonie est nommée *soprano*.


*** Extrêmes & Internes

Le soprano et la basse sont les *voix extrêmes* d’une polyphonie.

Toutes les autres voix sont dites *internes*.


*** Importance

D’un point de vue harmonique, la *basse*, voix la plus grave, est la
plus importante d’une polyphonie. À l’extrême opposé, le *soprano*,
voix la plus aiguë, arrive en seconde. Les autres voix ont une
importance relative moins élevée. On a donc, par ordre décroissant
d’importance :

  - la basse (voix extrême inférieure)
  - le soprano (voix extrême supérieure)
  - les autres voix (voix internes)


*** Distinction

À un instant donné, les voix d’une polyphonie se distinguent en
général par :

  - le registre : une voix est plus aiguë ou plus grave qu’une l’autre
  - le rythme : une voix est plus rapide ou plus lente qu’une autre
  - le timbre : les voix sont jouées par des instruments de familles
    différentes, aux sons différenciables


*** Ajout et suppression

Le nombre de voix ne reste pas toujours constant tout le long d’une
pièce musicale. Une ou plusieurs voix peuvent être ajoutées ou
retirées. Dans le cas d’un ajout, on peut toujours considérer qu’une
voix préalablement silencieuse devient active. Dans le cas d’un
retrait, on peut considérer qu’une voix préalablement active devient
silencieuse.


**** Scission

La *scission* est un cas particulier d’ajout où la nouvelle voix
semble issue d’une ancienne comme une branche d’un arbre. Cet effet
est souvent obtenu en utilisant un mouvement pseudo-conjoint (à
l’octave près) entre les voix concernées. Exemple :

#+ATTR_HTML: :class plat
| S | : | do | ré |
| B | : | —  | si |

ou encore :

#+ATTR_HTML: :class plat
| S | : | —  | sol |
| B | : | fa | mi  |


**** Fusion

La *fusion* est un cas particulier de retrait, où l’ancienne voix
semble se fondre dans une autre avant de se taire. Cet effet est
souvent obtenu en utilisant un mouvement pseudo-conjoint entre les
voix concernées. Exemple :

#+ATTR_HTML: :class plat
| S | : | ré | do |
| B | : | si | —  |

ou encore :

#+ATTR_HTML: :class plat
| S | : | sol | —  |
| B | : | mi  | fa |


*** Groupes

Les voix d’une polyphonie peuvent être subdivisées en plusieurs
groupes. Les voix d’un même groupe possèdent généralement des
caractéristiques musicales communes, afin de les différencier des
autres voix. On parle alors de *groupe de voix*, de *plan sonore* ou
encore de *strate*.

Les groupes de voix ne sont pas figés :

  - chaque voix peut changer de groupe à tout moment
  - de nouveaux groupes peuvent être créés, d’anciens supprimés


**** Structure

Dans une *structure stratifiée*, chaque groupe de voix dispose de ses
propres motifs musicaux.

Dans une *structure imitative*, chaque groupe de voix reprend et varie
les thèmes des autres groupes.


** Ensembles


*** Duo

Un *duo* est une polyphonie à deux voix. Ces voix se nomment par
convention :

  - soprano
  - basse

de la plus aiguë à la plus grave. J’utilise comme abréviations : *S*
pour soprano et *B* pour basse, ce qui nous donne des tableaux de
cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| B | : | =...= |


*** Trio

Un *trio* est une polyphonie à trois voix. Ces voix se nomment par
convention :

  - soprano
  - alto
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le duo, avec en prime *A* pour l’alto, ce qui nous donne des
tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| B | : | =...= |


*** Quatuor

Un *quatuor* (aussi appelé *quartet*) est une polyphonie à quatre
voix. Ces voix se nomment par convention :

  - soprano
  - alto
  - ténor
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le trio, avec en prime *T* pour le ténor, ce qui nous donne des
tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| T | : | =...= |
| B | : | =...= |


*** Quintette

Un *quintette* (parfois orthographié *quintet*) est une polyphonie à
cinq voix. Ces voix se nomment par convention :

  - soprano
  - alto
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le quatuor, avec en prime *Y* pour le baryton, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |


*** Sextuor

Un *sextuor* (aussi appélé *sextet*, *sextette*) est une polyphonie à
six voix. Ces voix se nomment par convention :

  - soprano
  - mezzo-soprano
  - alto
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le quintettte, avec en prime *M* pour le mezzo-soprano, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| M | : | =...= |
| A | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |


*** Septuor

Un *septuor* (aussi appéles *septet*, *septette*) est une polyphonie à
sept voix. Ces voix se nomment par convention :

  - soprano
  - mezzo-soprano
  - alto
  - haute-contre
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le sextuor, avec en prime *C* pour le haute-contre, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| M | : | =...= |
| A | : | =...= |
| C | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |


/Remarque/ : la voix de haute-contre est aussi appelée, avec des
nuances, *contralto* ou *contreténor*.


*** Formation générique

Au-dessus de sept voix, on à la nomenclature :

  - Octuor, octet : 8 voix
  - Nonet, nonette : 9 voix
  - Dixtuor : 10 voix

On représente un ensemble contenant un nombre quelconque de voix par :

#+ATTR_HTML: :class plat
|     0 | : | =...= |
|     1 | : | =...= |
|     2 | : | =...= |
|     3 | : | =...= |
|     4 | : | =...= |
| =...= | : | =...= |
|   /M/ | : | =...= |

ou, si l’on souhaite faire ressortir les voix extrêmes :

#+ATTR_HTML: :class plat
|     S | : | =...= |
|     1 | : | =...= |
|     2 | : | =...= |
|     3 | : | =...= |
|     4 | : | =...= |
| =...= | : | =...= |
|   /N/ | : | =...= |
|     B | : | =...= |


* Accords

#+TOC: headlines 1 local


** Introduction

Un *accord* est un ensemble de notes qui sert pendant un certain
laps de temps de fondation au déroulement musical.

Cela ne signifie pas que toutes les notes jouées appartiennent à
l’accord, mais que la musique est élaborée à partir des notes qui le
constituent.

L’ajout de notes étrangères à l’accord se fait en général pour des
raisons de liaisons mélodiques entre les notes.


** Polyvalence

Les notes d’un accord peuvent être disposées suivant des
configurations très diverses. Il existe bien entendu des cas
extrêmes :

  - l’accord purement harmonique, où les notes sont jouées
    simultanément

  - l’accord purement mélodique, où les notes sont jouées les unes
    après les autres

mais la réalité est souvent plus complexe. La plupart du temps, la
musique explore les deux aspects, superposant et alignant les notes
d’un accord tout au long de son règne. Un accord est donc
une *entité abstraite* dont les *réalisations* constituent
le plus souvent un *hybride* d’harmonie et de mélodie.


*** Jargon

Les notes d’un accord mélodique ne sont en général pas jouées
consécutivement, d’autres notes pouvant être intercalées afin
d’affiner les lignes mélodiques. Lorsque les notes d’un accord
mélodique sont jouées consécutivement, on parle alors d’ *arpège*.

Lorsque les notes d’un accord sont jouées simultanément et sans ajout
de notes étrangères, on parle d’ *accord frappé* ou encore d’ *accord
plaqué*.

Enfin, on parle d’ *accumulation* lorsque les notes de l’accord sont
entamées consécutivement mais que chacune d’elle est maintenue jusqu’à
la fin de l’accord. Par exemple, avec l’accord /do mi sol/, on
commence par jouer le /do/, ensuite le /mi/ vient s’ajouter et on
entend simultanément les notes /do mi/, et finalement le /sol/ vient
s’ajouter et on entend simultanément les notes /do mi sol/.


** Octave

C’est avant tout l’ordre des notes, de la plus grave à la plus aiguë,
qui importe en théorie des accords. Leur octave précise n’est pas
prise en compte. Les notes et intervalles doivent donc s’entendre à
l’octave près.

Ce constat nous permet d’employer une notation allégée. Par
convention, nous représentons un accord par une suite de notes
croissantes en hauteur, ce qui nous permet d’omettre leurs octaves.
Ainsi, dans l’accord :

#+BEGIN_CENTER
sol si sol
#+END_CENTER

le second /sol/ doit être plus aigu que le /si/, lui-même strictement
plus aigu que le premier /sol/. Cette notation est donc équivalente
à :

#+BEGIN_CENTER
SOL SI sol
#+END_CENTER

ou plus généralement à :

#+BEGIN_CENTER
sol^M si^N sol^P
#+END_CENTER

où les octaves /M/, /N/, /P/ sont des entiers respectant la
contrainte :

#+BEGIN_CENTER
M ≤ N < P
#+END_CENTER


** État canonique

Un accord est défini par une suite de notes disposées dans un ordre de
référence appelé *état canonique*. La note la plus grave de l’état
canonique est appelée *fondamentale*. L’état canonique permet
également de nommer les notes de l’accord d’après l’intervalle qui les
sépare de la fondamentale.

Par exemple, dans l’accord défini par l’état canonique :

#+BEGIN_CENTER
do   mi   sol   si   ré   fa   la
#+END_CENTER

les notes reçoivent des noms repris dans le tableau ci-dessous :

| Notes | Noms         | Abréviations |
|-------+--------------+--------------|
| do    | fondamentale |         1ale |
| mi    | tierce       |          3ce |
| sol   | quinte       |          5te |
| si    | septième     |           7e |
| ré    | neuvième     |           9e |
| fa    | onzième      |          11e |
| la    | treizième    |          13e |

/Remarque/ : ne pas confondre le concept de /note/ fondamentale d’un
accord avec celui de /fréquence/ fondamentale d’un son.


** Degré

Le *degré* d’un accord est simplement le degré de sa fondamentale.

Par exemple :

  - un accord de degré 1, ou accord de tonique, est un accord dont la
    fondamentale est le degré 1 de la gamme

  - un accord de degré 5, ou accord de dominante, est un accord dont
    la fondamentale est le degré 5 de la gamme


** Empilement

L’état canonique de la plupart des accords est construit en empilant
des notes séparées par un intervalle constant donné. Cet intervalle
est généralement un des premiers que l’on rencontre dans la suite des
harmoniques naturelles, à savoir les tierces et les quintes.


*** Tierces

Les accords construits par empilement de tierces sont de loin les plus
fréquents, parce qu’ils sont intimement liés aux harmoniques
naturelles et sonnent donc particulièrement bien. Notons qu’un
accord à base de tierces peut aussi bien contenir des tierces
majeures que mineures. Exemples d’accords à base de tierces :

#+ATTR_HTML: :class plat
| ré | fa | la |    |    |     |    |
| ré | fa | la | do |    |     |    |
| ré | fa | la | do | mi |     |    |
| ré | fa | la | do | mi | sol |    |
| ré | fa | la | do | mi | sol | si |


*** Quintes

Les accords construits par empilement de quintes sont considérés comme
des altérations d’accords à base de tierces. On les utilise pour
donner une coloration alternative à la musique, ou encore pour
soutenir une mélodie issue d’un mode tétraphonique ou pentaphonique
(comme on en rencontre en blues et en jazz). Exemples d’accords à base
de quintes :

#+ATTR_HTML: :class plat
| fa | do | sol |    |    |    |    |
| fa | do | sol | ré |    |    |    |
| fa | do | sol | ré | la |    |    |
| fa | do | sol | ré | la | mi |    |
| fa | do | sol | ré | la | mi | si |

Si la théorie classique ne reconnaît que les accords construits par
empilement de tierces, Jean-Sébastien Bach n’a pas attendu l’avènement
du jazz pour l’utiliser : on en rencontre dans le prélude le plus
célèbre du Clavier bien tempéré.


** Disposition

#+TOC: headlines 1 local

*** Introduction

On nomme *disposition* d’un accord un agencement particulier de ses
notes intrinsèques. De nombreux événements peuvent modifier la
disposition : permutation, renversement, doublure, suppression, etc.


*** Permutations

On peut permuter l’ordre des notes d’un accord. Exemples :

#+ATTR_HTML: :class plat
| do mi sol | ⟼ | do sol mi |
| sol do fa | ⟼ | do fa sol |


*** Basse

La note la plus grave d’une permutation quelconque d’un accord est
appelée la *basse* de l’accord ainsi disposé. On dit aussi de cette
note qu’elle est mise *à la basse*.

Dans cet exemple, le /sol/ est à la basse :

#+BEGIN_CENTER
sol do mi
#+END_CENTER

Dans cet exemple, le /do/ est à la basse :

#+BEGIN_CENTER
do sol mi
#+END_CENTER


*** Octave

Une note de l’accord peut changer d’octave. L’intervalle de cette note
dans la disposition d’un accord peut donc étre égal :

  - à l’intervalle /I/ de la disposition canonique
  - à l’intervalle /I/ + un nombre entier d’octaves/
  - à l’intervalle /I/ - un nombre entier d’octaves/

Les cas particuliers les plus importants sont :

  - /I/
  - le renversement de /I/
  - le redoublement de /I/

Prenons comme exemple l’accord dont l’état canonique est /sol si ré
fa/. La 7e, le /fa/, peut être disposée comme septième ou quatorzième
mineure au-dessus de la basse :

#+ATTR_HTML: :class plat
| S | : | fa  |
| B | : | sol |

ou comme seconde majeure sous la basse :

#+ATTR_HTML: :class plat
| S | : | sol |
| B | : | fa  |

On peut bien sûr continuer à monter ou descendre dans les octaves.


*** État fondamental et renversements

Lorsque les notes d’un accord sont permutées, il arrive que la note
mise à la basse ne soit pas la fondamentale. On dit alors que l’accord
est *renversé*.

Si c’est la deuxième note la plus grave de l’état canonique qui est à
la basse, on dit que l’accord est dans un premier *renversement*, ou
qu’il est *renversé* une fois.

Si c’est la troisième note la plus grave de l’état canonique qui est à
la basse, on dit que l’accord est dans un second renversement, ou
qu’il est renversé deux fois ; etc.

Qu’il soit permuté ou non, on dit qu’un accord est dans son *état
fondamental* lorsque la fondamentale est à la basse.

Exemple :

  - État fondamental :
    + État canonique : do mi sol
    + Permutation sans renversement : do sol mi
  - Renversements :
    + Premier renversement :
      * mi sol do
      * mi do sol
    + Second renversement :
      * sol do mi
      * sol mi do


*** Doublure

Une *doublure* est une note ajoutée à l’accord, identique à l’octave
près à une des notes de l’état canonique. La note originale est alors
dite *doublée* ou *redoublée*. Une doublure peut donc se faire :

  - une ou plusieurs octaves au-dessus de la note originale
  - à l’unisson de la note originale
  - une ou plusieurs octaves en-dessous de la note originale

Par exemple, si on redouble le /mi/ de l’accord /la do mi/, on
obtient :

#+BEGIN_CENTER
la mi do mi
#+END_CENTER

ou une quelconque permutation de cet accord. La note redoublée
correspond souvent, mais pas nécessairement, à une note importante que
l’on souhaite souligner, à la fondamentale ou à la basse de l’accord.

Quelques précisions :

  - L’ajout d’une doublure ne modifie pas l’état canonique de
    l’accord. Le nombre de notes intrinsèques reste donc inchangé.

  - Une même note peut être doublée plusieurs fois, à des octaves
    différentes ou identiques.


*** Suppression

On peut modifier un accord en supprimant une de ses notes.


**** Fondamentale

Pour éviter toute ambiguité, le nombre de renversements est toujours
évalué par rapport à l’ordre des notes dans l’état canonique de
l’accord /au complet/. Donc, si la fondamentale de :

#+BEGIN_CENTER
do mi sol si
#+END_CENTER

est supprimée, la disposition suivante :

#+BEGIN_CENTER
mi sol si
#+END_CENTER

est assimilée à un premier renversement, puisque c’est le /mi/,
deuxième note de l’état canonique, qui est à la basse. La disposition
suivante :

#+BEGIN_CENTER
sol si mi
#+END_CENTER

sera dans un deuxième renversement et celle-ci  :

#+BEGIN_CENTER
si mi sol
#+END_CENTER

dans un troisième.

Une conséquence importante de cette convention est qu’un accord privé
de sa fondamentale est toujours renversé.


** Intervalle interne

Un *intervalle interne* d’un accord est un intervalle qui sépare deux
de ses notes.

Les intervalles internes les plus importants sont ceux qui séparent :

  - une note de l’accord avec la fondamentale
  - une note de l’accord avec la basse


** Harmoniques naturelles

On peut générer une suite de notes dont les fréquences respectent au
moins approximativement les ratios des harmoniques naturelles :

#+ATTR_HTML: :class plat
| 2 / 1 | — | 3 / 2 | — | 4 / 3 | — | 5 / 4 | — | 6 / 5 | — | 7 / 6 | — | 8 / 7 | — | 9 / 8 | — | =...= |

En partant d’un /do/, nous obtenons :

#+ATTR_HTML: :class plat
| do | do | sol | do | mi | sol | si^b  | do | ré | =...= |

On peut voir cette suite comme un accord placé dans une disposition
particulière : multiples doublures de la fondamentale /do/, doublure
de la quinte /sol/, intervalles larges dans les graves et plus
resserrés dans l’aigu, etc. Une disposition analogue aura donc de
bonnes chances d’asseoir confortablement un accord. On remarque aussi,
qu’abstraction faite des doublures, on obtient la suite de notes :

#+BEGIN_CENTER
do mi sol si^b ré
#+END_CENTER

La suite des harmoniques naturelles semble donc nous diriger vers des
accords construits par empilement de tierces majeures ou mineures.
Ceci explique la prédominance des accords à base de tierces.


** Nombre de notes

On nomme :

  - *dyade* un accord constitué de deux notes
  - *triade* un accord constitué de trois notes
  - *tétrade* un accord constitué de quatre notes
  - *pentade* un accord constitué de cinq notes

/Remarque/ : on parle ici du nombre de notes intrinsèques de l’accord,
sans tenir compte des éventuelles doublures, suppressions ou ajouts.

Le tableau suivant nous donne les abréviations de ces termes :

| Nom     | Abréviation |
|---------+-------------|
| Dyade   | 2ade        |
| Triade  | 3ade        |
| Tétrade | 4ade        |
| Pentade | 5ade        |


*** Accord et intervalle

On peut voir un accord comme un empilement d’intervalles.
Réciproquement, on peut voir un intervalle comme un accord constitué
de deux notes, c’est-à-dire une dyade.


* Dualité

#+TOC: headlines 1 local


** Grille

On peut représenter une polyphonie comme une superposition de
mélodies, mais également comme une succession d’accords, chacun
d’entre-eux régnant un certain temps sur le déroulement musical avant
de laisser la place à son successeur. Le tableau suivant illustre
cette dualité dans le cas d’un septuor :

#+ATTR_HTML: :class plat
| S | : | (accord-1, note-1) | (accord-2, note-1) | (accord-3, note-1) | =...= |
| M | : | (accord-1, note-2) | (accord-2, note-2) | (accord-3, note-2) | =...= |
| A | : | (accord-1, note-3) | (accord-2, note-3) | (accord-3, note-3) | =...= |
| C | : | (accord-1, note-4) | (accord-2, note-4) | (accord-3, note-4) | =...= |
| T | : | (accord-1, note-5) | (accord-2, note-5) | (accord-3, note-5) | =...= |
| Y | : | (accord-1, note-6) | (accord-2, note-6) | (accord-3, note-6) | =...= |
| B | : | (accord-1, note-7) | (accord-2, note-7) | (accord-3, note-7) | =...= |

Cette représentation schématique a le mérite de n’intégrer que les
notes essentielles de la polyphonie, ce qui permet de visualiser du
premier coup d’oeil les évolutions des voix lors des changements
d’accords. Nous appelons *grille polyphonique*, ou plus simplement
*grille* une telle représentation schématique de la polyphonie.


** Notes

Les notes d’une polyphonie peuvent se scinder en deux catégories :

  - les *notes essentielles* sont les notes qui appartiennent à la
    grille polyphonique, et donc à l’un des accords qui la constituent

  - les *notes étrangères* sont les notes qui n’appartiennent pas à la
    grille polyphonique, et donc à aucun des accords qui la
    constituent

Les notes essentielles consitutent la fondation de la polyphonie,
tandis que les notes étrangères servent à compléter le discours
musical.

/Remarque/ : on utilise également les expressions *note réelle* ou
*note constitutive* comme synonymes de note essentielle.


** Accords

On peut classer grossièrement les accords en deux catégories, suivant
leur importance :

  - Les *accords stratégiques* constituent la clef de voûte du
    discours musical

  - Les *accords ornementaux* ont pour but de fluidifier et
    d’ornementer les mélodies


** Enchaînement

On appelle *enchaînement* une suite formée de deux accords
consécutifs.

Deux accords consécutifs sont dit *enchaînés*.


*** Changement d’harmonie

Une *harmonie* peut aussi désigner le règne d’un accord. On parle donc
de *changement d’harmonie* pour signaler un changement d’accord.


** Mélodie

On distingue :

  - l’ *intervalle mélodique* en général, intervalle entre deux notes
    consécutives quelconques

  - l’ *intervalle mélodique essentiel*, intervalle entre deux notes
    essentielles consécutives

On utilise également l’expression *mouvement mélodique essentiel*
comme synonyme d’intervalle mélodique essentiel.

Il existe donc 4 possibilités de mouvement mélodique :

  1. note essentielle — note essentielle : intervalle mélodique essentiel
  2. note essentielle — note étrangère
  3. note étrangère — note essentielle
  4. note étrangère — note étrangère


** Rythme harmonique

Le rythme auquel les accords se succèdent est appelé *rythme
harmonique*. Le rythme harmonique peut être régulier ou variable.

Chaque accord règne un certain temps sur la musique avant de laisser
la place à son successeur. Ce règne peut durer pendant :

  - une carrure (entière, 1/2, 1/4, =...=)

  - une oscillation

  - une pulsation

  - une mesure

  - un temps

  - =...=


** Rencontres

La perception du cadre harmonique est renforcée par des rencontres
entre les notes essentielles les plus importantes de chaque accord.
Ces notes sont alors jouées simultanément sur les différentes voix de
la polyphonie. Les rencontres peuvent se produire à un rythme régulier
ou variable. En fait, elles sont liées au rythme harmonique, l’idéal
étant de disposer au moins une rencontre par accord. Les cas les plus
courants sont :


  - une rencontre au début de chaque temps
  - une rencontre au début de chaque mesure
  - une rencontre au début de chaque pulsation
  - une rencontre au début de chaque oscillation
  - =...=


* Mouvements harmoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements harmoniques* analysent les modifications de
disposition des notes essentielles au cours du règne d’un même accord.


** Échange

L’ *échange* consiste à intervertir les voix de deux notes
essentielles.

Exemple d’échange :

#+ATTR_HTML: :class plat
| S | : | mi | do |
| B | : | do | mi |


** Changement

Le *changement* consiste à modifier une des voix pour jouer une autre
note de l’accord.

Exemple de changement, ici sur le soprano :

#+ATTR_HTML: :class plat
| S | : | mi | sol |
| B | : | do | do  |


* Mouvements polyphoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements polyphoniques* comparent les évolutions de deux voix
quelconques de la grille polyphonique lors d’un changement d’accord,
ce qui les place au croisement de l’harmonie et de la mélodie.

Les notes impliquées sont donc des notes essentielles, et les
intervalles mélodiques sont des intervalles mélodiques essentiels.


** Mouvement parallèle

Il se produit un mouvement *parallèle* lorsque les deux voix évoluent
dans la même direction en utilisant le même intervalle mélodique.

/Remarque/ : dans le cadre des mouvements polyphoniques, on ne fait
pas de distinction entre les intervalles majeurs et mineurs. Par
exemple, si une voix monte d’une seconde majeure pendant que l’autre
monte d’une seconde mineure, le mouvement sera considéré comme
parallèle.


*** Ascendant

Un mouvement *parallèle ascendant* est un mouvement parallèle où les
deux voix évoluent vers l’aigu.

Exemple de mouvement parallèle ascendant :

#+ATTR_HTML: :class plat
| S | : | ré | mi | (monte) |
| B | : | la | si | (monte) |


*** Descendant

Un mouvement *parallèle descendant* est un mouvement parallèle où les
deux voix évoluent vers le grave.

Exemple de mouvement parallèle descendant :

#+ATTR_HTML: :class plat
| S | : | ré | do  | (descend) |
| B | : | la | sol | (descend) |


*** Continuité

Un mouvement *parallèle conjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement conjoint.

Un mouvement *parallèle disjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement disjoint.


*** Mélodies parallèles

Le mouvement parallèle se rencontre entre-autres lorsque deux mélodies
évoluent parallèlement. Par analogie avec les premières formes de la
polyphonie, on parle alors :


  - d’ *organum* lorsque l’intervalle qui les sépare est une octave,
    une quinte ou une quarte

  - de *gymel*, ou de *faux-bourdon*, lorsque l’intervalle qui les
    sépare est une tierce ou une sixte


** Mouvement oblique

Il se produit un mouvement *oblique* lorsqu’une des deux voix reste
constante pendant que l’autre varie.

Le mouvement oblique se produit généralement lorsqu’une note commune à
deux accords consécutifs est disposée sur la même voix.


*** Ascendant

Un mouvement *oblique ascendant* est un mouvement oblique où la voix
mobile évolue vers l’aigu.

Exemple de mouvement oblique ascendant :


#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte)    |
| B | : | do | do  | (constant) |


*** Descendant

Un mouvement *oblique descendant* est un mouvement oblique où la voix
mobile évolue vers le grave.

Exemple de mouvement oblique descendant :

#+ATTR_HTML: :class plat
| S | : | fa | ré | (descend)  |
| B | : | do | do | (constant) |


*** Continuité

Un mouvement *oblique conjoint* est un mouvement oblique où la voix
mobile évolue par mouvement conjoint.

Un mouvement *oblique disjoint* est un mouvement oblique où la voix
mobile évolue par mouvement disjoint.


** Mouvement contraire

Il se produit un mouvement *contraire* lorsque les deux voix évoluent
dans des directions opposées : l’une monte, l’autre descend. C’est un
mouvement naturellement très équilibré.


*** Extérieur

Un mouvement *extérieur* est un mouvement *contraire* où la voix
supérieure monte, tandis que la voix inférieure descend.

Pour s’en souvenir, se rappeler que les voix d’un mouvement extérieur
se dirigent vers l’extérieur.

Exemple de mouvement extérieur :

#+ATTR_HTML: :class plat
| S | : | si  | do | (monte)   |
| B | : | sol | fa | (descend) |


*** Intérieur

Un mouvement *intérieur* est un mouvement *contraire* où la voix
supérieure descend, tandis que la voix inférieure monte.

Pour s’en souvenir, se rappeler que les voix d’un mouvement intérieur
se dirigent vers l’intérieur.

Exemple de mouvement intérieur :

#+ATTR_HTML: :class plat
| S | : | si | la | (descend) |
| B | : | mi | fa | (monte)   |


*** Continuité

Un mouvement *contraire conjoint* est un mouvement contraire où les
deux voix évoluent par mouvement conjoint.

Un mouvement *contraire disjoint* est un mouvement contraire où au
moins une des voix évolue par mouvement disjoint.


** Mouvement direct

Il se produit un mouvement *direct* lorsque les deux voix évoluent
dans la même direction, mais au moyen d’intervalles différents.


*** Ascendant

Un mouvement *direct ascendant* est un mouvement direct où les deux
voix évoluent vers l’aigu.

Exemple de mouvement direct ascendant :

#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte) |
| B | : | mi | si  | (monte) |


*** Descendant

Un mouvement *direct descendant* est un mouvement direct où les deux
voix évoluent vers le grave.

Exemple de mouvement direct descendant :

#+ATTR_HTML: :class plat
| S | : | fa  | mi | (descend) |
| B | : | sol | do | (descend) |


*** Continuité

Un *mouvement direct conjoint* est un mouvement direct où l’une des
voix évolue par mouvement conjoint tandis que l’autre évolue par
mouvement disjoint.

Un *mouvement direct disjoint* est un mouvement direct où les deux
voix évoluent par mouvement disjoint.

De façon générale, le mouvement direct est considéré comme plus
élégant lorsqu’une des deux voix évolue par mouvement conjoint.


** Mouvement consécutif
:PROPERTIES:
:CUSTOM_ID: section:mouvementConsecutif
:END:


Il se produit un mouvement *consécutif* lorsque les deux voix
reproduisent un même intervalle harmonique à l’octave près, que ce
soit par mouvement parallèle, oblique, contraire ou direct.

Exemple de mouvement consécutif reproduisant une tierce :

#+ATTR_HTML: :class plat
| S | : | mi | la  | (monte d’une 4te ou descend d’une 5te) |
| B | : | do | fa  | (monte d’une 4te ou descend d’une 5te) |


** Disposition des voix

Cette section analyse certaines configurations liées à la disposition
relative des voix.


*** Croisement

Un *croisement* se produit lorsqu’une note essentielle d’une voix
normalement plus grave croise à la hausse une note essentielle d’une
voix plus aiguë.


*** Chevauchement

Un *chevauchement* se produit lorsqu’une note essentielle d’une voix
plus grave croise à la hausse une note essentielle d’une voix plus
aiguë /de l’accord précédent/.


*** Fausse relation

Une fausse relation est une association de deux notes disposées sur
des voix différentes.


**** Chromatique

Une *fausse relation chromatique* se produit lorsque les trois notes
d’un mouvement chromatique ne sont pas toutes disposées sur la même
voix.


**** Triton

Une *fausse relation de triton* se produit lorsque les deux notes d’un
intervalle de triton :

  - appartiennent à deux accords consécutifs
  - sont situées sur deux voix différentes


** Principes


*** Économie de mouvement


**** Changement d’accord

Le principe d’ *économie de mouvement* dit que les notes essentielles
doivent évoluer majoritairement par mouvement conjoint au cours d’un
changement d’accord, ce qui permet :

  - de distinguer plus aisément les différentes voix de la polyphonie

  - de distinguer les intervalles internes des accords (tierces,
    sixtes, etc) des intervalles permettant l’enchaînement

On priviligiera donc à chaque enchaînement :

  - le mouvement conjoint sur une majorité des voix
  - les sauts de quinte ou de quarte sur les voix restantes

Ceci étant dit, on peut bien entendu se permettre une tierce ou une
sixte occasionnelle si cela correspond à un effet souhaité, ou s’il
est difficile de s’en passer sans dénaturer le paysage musical.

/Remarque/ : ce principe s’applique aux changements de notes
essentielles lors du passage d’un accord à un autre. Il n’y a par
contre aucune réserve à avoir concernant l’utilisation des tierces et
des sixtes mélodiques à l’intérieur du règne d’un même accord.


**** Mélodie

Le principe d’économie de mouvement est également valable à l’échelle
des mélodies de la grille polyphonique, mélodies générées par la
succession des accords : chacune d’entre-elle doit évoluer
majoritairement par mouvement conjoint, ceci afin de permettre à
l’oreille de discerner les différentes voix qui composent la
polyphonie. Cette continuité majoritaire permet également d’accentuer
aisément les fins de phrases en utilisant le contraste qu’offrent
alors les sauts discontinus des mouvements disjoints.


*** Mouvements, accords et dispositions

De nombreux accords et dispositions différentes peuvent assurer une
même fonction tonale, ce qui permet de les choisir au mieux afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.


*** Lignes mélodiques extrêmes

Les mouvements formés par les lignes mélodiques extrêmes (basse et
soprano) doivent être particulièrement soignés, car ce sont les voix
les plus évidentes pour l’oreille.


* Ornements

#+TOC: headlines 1 local

** Introduction

La modélisation d’une polyphonie sous la forme d’une suite d’accords
est d’une grande clarté et permet de cerner l’essentiel. Mais
l’essentiel n’est pas tout, et si la sobriété est très utile dans les
premières phases de la composition, on est amenés par la suite à
insérer des *ornements* afin de donner de la souplesse aux lignes
mélodiques ou d’enrichir la dynamique harmonique.

On appelle *note ornementale* une note constitutive d’un ornement.


** Notes essentielles & étrangères

Parmi les notes ornementales, on distingue :

  - les *notes ornementales essentielles* : notes ornementales qui
    font partie de l’accord en cours

  - les *notes ornementales étrangères* : notes ornementales qui ne
    font pas partie de l’accord en cours


** Ornements harmoniques

#+TOC: headlines 1 local

*** Introduction

Cette section analyse les ornements dont la fonction est
essentiellement harmonique.


*** Arpège

Un *arpège* consiste à jouer consécutivement une partie ou la totalité
des notes de l’accord en cours. Chaque note peut être répétée, à
l’unisson où à l’octave près.

Les arpèges d’accords à base de tierces sont très utilisés dans la
construction de voix accompagnatrices d’une mélodie principale.

Les arpèges d’accords à base de quintes s’apparentent aux modes
pentaphoniques ou tétraphoniques. Ils sont donc très utilisés dans la
construction de mélodies blues par exemple.


**** Accord brisé

Un *accord brisé* est une généralisation de l’arpège, où plusieurs
notes de l’accord peuvent être jouées simultanément. Les deux termes
sont parfois considérés comme synonymes.


*** Pédale

Une *pédale* est une note qui reste obstinément constante,
indépendamment des accords qui se succèdent sur les autres voix.

Une pédale est placée le plus souvent à la basse ou au soprano, plus
rarement aux voix intermédiaires.

Exemple de pédale, ici à la basse :

#+ATTR_HTML: :class plat
| S | : | la   | si   | mi   |
| A | : | fa   | sol  | do   |
| B | : | /do/ | /do/ | /do/ |


*** Retard

Un *retard* est une note intégrée à un accord et qui se poursuit
au-delà du changement d’accord, empiétant sur le début du règne de
l’accord suivant.

Exemple de retard, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | do  |
| A | : | la   | sol  | sol |
| B | : | fa   | mi   | mi  |


*** Anticipation

Une *anticipation* est une note appartenant à un accord qui est
entamée avant la fin du règne de l’accord précédent.

Exemple d’anticipation, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


*** Appogiature

Une *appogiature* est une note arbitraire jouée au début du règne d’un
accord.


** Ornements mélodiques

#+TOC: headlines 1 local

*** Introduction

Cette section analyse les ornements dont la fonction est
essentiellement mélodique.


*** Note de passage

Une *note de passage* est une note ornementale intermédiaire
permettant de relier par mouvement conjoint deux notes disjointes
appartenant à un même accord où à deux accords successifs.

Exemple, le /si/ dans :

#+BEGIN_CENTER
do /si/ la
#+END_CENTER

Autre exemple, avec deux notes de passage consécutives :

#+BEGIN_CENTER
ré /do si/ la
#+END_CENTER


*** Broderie

La *broderie* quitte une note de l’accord par mouvement conjoint et la
retrouve juste après.

On distingue :

  - la *broderie supérieure*, qui monte d’un degré avant de redescendre
  - la *broderie inférieure*, qui descend d’un degré avant de remonter

Exemple de broderie supérieure :

#+BEGIN_CENTER
do /ré/ do
#+END_CENTER

Exemple de broderie inférieure :

#+BEGIN_CENTER
fa /mi/ fa
#+END_CENTER


**** Double

La *double broderie* combine les broderies supérieure et inférieure.

Exemple :

#+BEGIN_CENTER
do /ré si/ do
#+END_CENTER


*** Échappée

L’ *échappée* quitte une note de l’accord par mouvement conjoint puis
évolue par mouvement disjoint vers une note du même accord ou de
l’accord suivant.

Exemple, le /la/ dans :

#+BEGIN_CENTER
sol /la/ ré
#+END_CENTER


** Ornements répétitifs


*** Trémolo

Un *trémolo* consiste à alterner deux notes. Exemple :

#+BEGIN_CENTER
do sol do sol do sol do sol
#+END_CENTER


**** Basse de Murky

Il s’agit dun trémolo en octave.


*** Trille

Un *trille* consiste à alterner deux notes séparées par une seconde
majeure ou mineure. Exemple :

#+BEGIN_CENTER
do ré do ré do ré do ré
#+END_CENTER


*** Roulement

Un *roulement* consiste à répéter une même note. Exemple :

#+BEGIN_CENTER
do do do do do do do do
#+END_CENTER


** Combinaisons

Les ornements peuvent être combinés : broderie d’une note de passage,
retard d’une broderie, anticipation d’une note de passage, etc.


* Accords ornementaux

#+TOC: headlines 1 local

** Harmoniques


*** Accord pédale

Un *accord pédale* est un accord maintenu constant sur une partie des
voix pendant que d’autres accords se succèdent sur les autres voix.

Un exemple d’accord-pédale est celui où un même accord est arpégé
inlassablement sur une des voix.


** Mélodiques

#+TOC: headlines 1 local

*** Accord broderie

Un *accord broderie* est un accord dont au moins une des notes effectue
une broderie par rapport aux notes des accords environnant disposées
sur la même voix.

Le second renversement de l’accord parfait peut servir d’accord de
broderie. En effet, il est proche d’un accord parfait dont la
fondamentale est située une quinte plus haut. On le fait donc souvent
suivre ou précéder par cet accord parfait. On observe alors les
intervalles suivant, par rapport à la basse :

  - tierce ↦ quarte ↦ tierce
  - quinte ↦ sixte ↦ quinte

Exemple de broderie d’un accord parfait de fondamentale /do/ :

#+ATTR_HTML: :class plat
| S | : | sol | la | sol |
| A | : | mi  | fa | mi  |
| B | : | do  | do | do  |

Voir aussi la section concernant la [[file:musica-05-tablature.org::#section:quarteEtSixteCadentielle][quarte et sixte cadentielle]].


*** Accord de passage

Les *accords de passage* ont pour fonction de réaliser une transition
fluide, principalement par mouvements conjoints, entre deux autres
accords.

Exemple :

#+ATTR_HTML: :class plat
| S | : | /si/ | /la/ | /sol/ |
| A | : | /fa/ | /fa/ | /sol/ |
| T | : | /ré/ | /do/ | /si/  |
| B | : | ré   | ré   | sol   |


**** Échange

Lorsqu’on souhaite échanger deux notes d’un accord tout en opérant par
mouvements conjoints, il est parfois nécessaire d’intercaler un accord
de passage entre la disposition initiale et la disposition finale. À
deux voix, on a par exemple :

#+ATTR_HTML: :class plat
| S | : | mi | ré | do |
| B | : | do | ré | mi |

Dans cet exemple, on échange le soprano et la basse :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | do   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Autre exemple, avec un accord de 7e comme point de départ :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | si   | si   | si   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Enfin, l’accord final peut révéler une version 7e de l’accord de
départ :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | la   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |


**** Suites d’accords de passage

Il est possible d’enchaîner plusieurs accords de passage. On assiste
alors généralement à la formation de portions de gammes diatoniques ou
chromatiques sur une des voix.


* Accentuation

#+TOC: headlines 1 local


** Mélodie

Une mélodie est généralement accentuée par :

  - la durée : notes de durée plus longue
  - des extrêmes : pics ou creux locaux
  - des virages : changements de direction, de pente
  - des sauts : mouvements disjoints dans une mélodie majoritairement conjointe


*** Indépendance

Les accents mélodiques des différentes voix de la polyphonie sont
indépendants. La plupart du temps, on s’arrange pour que ces accents
apparaissent à des instants différents sur chacune des voix, ceci afin
de les mettre tour à tour en évidence.

Il arrive toutefois que les accents mélodiques soient synchronisés
afin de donner à l’ensemble un effet de convergence et d’apothéose
très convaincant.


** Notes essentielles

Les accents mélodiques sont généralement disposés sur des notes
essentielles.


*** Discontinuités

Ceci est particulièrement vrai pour les discontinuités. Il est donc
rare d’observer un mouvement disjoint ne faisant intervenir aucune
note de l’accord.


** Rythme

Un temps fort peut être accentué par :

  - une intensité plus forte de la note qui l’entame
  - un accent mélodique


* Superposition rythmique

#+TOC: headlines 1 local

** Introduction

Ce chapitre analyse les configurations rythmiques que l’on rencontre
dans une polyphonie.


** Classification


*** Rythmes identiques

Les deux rythmes sont identiques. Exemple :

#+ATTR_HTML: :class plat
| S | : | B N | N N N | Bp |
| B | : | B N | N N N | Bp |


*** Rythmes contrastés

Un rythme est lent, l’autre est rapide. Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | Bp |   |   |
| B | : | N  | N | N | N  | N | N |


*** Rythmes dialogués

Les voix alternent rythmes rapides et lents, afin de laisser à chacune
un « temps de parole ». Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | N  | N | N |
| B | : | N  | N | N | Bp |   |   |


*** Rythmes décalés

Les deux rythmes sont décalés. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | — | — | N | — | — | N |


*** Rythmes hybrides

Il s’agit de rythmes alternativement synchronisés et décalés.
Exemples :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | N | — | N | N | — | N |

Le même en version fluide :

#+ATTR_HTML: :class plat
| S | : | N | B |   | N | B |   |
| B | : | B |   | N | B |   | N |


*** Rythmes convergents

Ce sont des rythmes contrastés, décalés ou hybrides qui convergent
l’un vers l’autre. Cette situation est très fréquente à l’approche des
fins de phrase, où toutes les voix finissent par ralentir. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | — | N | B |   | N | Bp |
| B | : | N | N | — | N | B |   | Bp |


*** Rythmes fleuris

Il est bien évident que chaque mélodie peut changer de rythme à tout
instant, modifiant du même coup l’agencement rythmique de la
polyphonie. Lorsqu’une superposition de rythmes fait entendre
successivement différentes configurations, on parle de style fleuri.


** Rythmes agrégés

Un rythme agrégé résulte de la condensation en une seule voix des
différents rythmes d’une polyphonie : chaque nouvelle note entamée sur
une des voix est également entamée sur le rythme agrégé. Considérons
par exemple la superposition :

#+ATTR_HTML: :class plat
| S | : | Np | C  |
| B | : | C  | Np |

Pour obtenir le rythme agrégé, on décompose le temps en suivant la
plus petite valeur commune, ici la croche, et on note le début de
chaque note sur le tableau correspondant :

#+ATTR_HTML: :class plat
|        |   | C | C | C | C |
| S      | : | X |   |   | X |
| B      | : | X | X |   |   |
| Agrégé | : | X | X |   | X |

On voit qu’aucune note n’est entamée à la troisième croche.
Le rythme agrégé associé est donc :

#+BEGIN_CENTER
C C cs C
#+END_CENTER

ou, en version fluide :

#+BEGIN_CENTER
C N C
#+END_CENTER


*** Binaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| Ν N + Np C         | N C C           |
| Np C + C Np        | C N C           |
| N C C + C N C      | C C C C         |
| N N + C N C        | C C C C         |
|                    |                 |

*** Ternaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| B N + N B          | Ν N N           |
| N B + B C C        | N N C C         |
| N C N C + N N N    | N C C C C       |


*** Hybrides

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| N N N + Np Np      | N C C N         |
| B N + Np Np        | Np C N          |
| B C C + Np Np      | Np C C C        |
| N B + Np Cp Cp     | N C Cp Cp       |


** Structure rythmique

Le moyen le plus simple permettant d’établir la structure rythmique
d’une polyphonie consiste à assigner une échelle rythmique différente
à chacune des voix. Par exemple, une voix peut jouer une note à chaque
oscillation, une autre à chaque mesure ou pulsation et une troisième à
chaque temps. Dans l’hypothèse d’un quatuor, cela laisse une voix au
rythme totalement libre.

Toutes les variantes de ce schéma sont possibles. Dans les cas
extrêmes, la structure rythmique est répartie sur toutes les voix, sur
une seule, voire sur aucune. Les rythmes eux-mêmes peuvent n’être
qu’approximativement réguliers : l’essentiel est qu’ils établissent
clairement les fondations rythmiques de la polyphonie.

De plus, les rôles des voix peuvent être permutés ou modifiés à tout
moment, ce qui permet de générer une musique vive et variée.


*** Ostinato

L’ostinato permet de concentrer le support rythmique en une seule
voix, ce qui libère les rythmes du reste de l’ensemble.

Considérons par exemple une carrure composée de quatre oscillations.
Chaque oscillation est subdivisée en deux pulsations ternaires durant
chacune une blanche pointée. Cette structure correspond au schéma :

#+ATTR_HTML: :class plat
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |

On peut lui associer l’ostinato suivant :

#+ATTR_HTML: :class plat
| Bp    | B N   |
| N N N | B N   |
| Bp    | B N   |
| N N N | N N N |

/Remarque/ : par son coté inlassable, constant dans un environnement
variable, on peut voir un ostinato comme une sorte de pédale rythmique.


*** Percussions

Un autre moyen de mettre en évidence la structure rythmique d’une
oeuvre est d’ajouter des percussions. Les rythmes des voix préalables sont
alors totalement libérés.


** Syncopes


*** Retard harmonique

Un procédé élégant consiste à utiliser une syncope pour produire
un retard harmonique.


*** Syncope d’harmonie

La syncope d’harmonie est un accord entamé sur temps faible, ou partie
faible de temps, et poursuivi sur temps fort, ou partie forte de
temps.


* Camouflage
:PROPERTIES:
:CUSTOM_ID: section:camouflage
:END:

#+TOC: headlines 1 local

** Introduction

Il arrive qu’une disposition musicale génère un effet inhabituel,
voire étrange.

Lorsqu’on est confronté à une telle disposition, il existe alors trois
possibilités :

  1. l’éviter complètement
  2. l’appliquer malgré tout, car elle correspond à l’effet désiré
  3. s’arranger pour qu’elle reste discrète

Nous étudions dans ce chapitre les techniques d’insertion discrète
dans une polyphonie.


** Position

Lorsqu’on souhaite rendre un agencement discret, on peut :

  - le placer dans les voix internes, plus discrètes
  - le placer sur un temps faible de la mesure


** Divertissement

On fait intervenir un autre paramètre (mélodique, harmonique,
rythmique, etc) pour divertir l’oreille, qui prête alors moins
attention à l’agencement que l’on veut placer à l’arrière-plan.


** Intervalles harmoniques

Pour rendre un intervalle harmonique plus discret, on peut faire
commencer une des deux notes avant l’autre.

On peut même aller plus loin et éviter de produire cet intervalle
harmonique. On utilise alors une des techniques suivantes :

  - modifier la disposition de l’accord concerné
  - intercaler une modification de la disposition de l’accord
    + échange
    + changement
  - décaler une des deux notes à un autre moment du règne de l’accord


** Mouvements polyphoniques


*** Direct disjoint

Pour masquer un mouvement direct disjoint, on peut ajouter une ou
plusieurs notes de passage afin de produire un mouvement mélodique
conjoint. Le mouvement mélodique essentiel associé restera disjoint,
mais sera plus discret.

Exemple, on part de :

#+ATTR_HTML: :class plat
| S | : | si  | mi |
| B | : | sol | mi |

et on ajoute la note de passage /fa/, pour obtenir :

#+ATTR_HTML: :class plat
| S | : | si  |      | mi |
| B | : | sol | /fa/ | mi |
