
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 04 : Concert
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Introduction

#+ATTR_HTML: :class lettrine
La polyphonie médiévale a fait ses premiers pas en utilisant un
processus d’accompagnement simple, l’ *organum strict* : une voix
parallèle, appelée *voix organale*, était alors ajoutée à une mélodie
préexistante de référence, la *voix principale*. Au fil du temps, la
voix organale est devenue de plus en plus ornée et indépendante. On
tournait alors autour du parallélisme strict, ne revenant à
l’intervalle harmonique original (unisson, octave ou quinte) que lors
des convergences de fin de phrase. C’était l’époque du *déchant* et de
l’ *organum fleuri*. Plus tard, d’autres voix ont été ajoutées,
donnant ainsi naissance au *motet*. Les lignes mélodiques ont pris de
plus en plus d’indépendance, la cohérence de l’ensemble étant assurée
par les lois du contrepoint, ancêtre de l’harmonie, ainsi que par
l’échange de motifs mélodiques via des procédés d’imitation et de
variation. Le *ricercar* et la *fugue* ont abondamment utilisé ce type
de constructions. L’art de la polyphonie aboutit alors à des
merveilles : imaginez une pièce de théâtre où chaque voix musicale
représente un personnage ; tantôt en concorde, tantôt en discorde,
toute la troupe bouillonne de thèmes, d’idées qui se baladent de main
en main, tissant ainsi la trame de l’histoire. Lorsque les Muses
apparaîssent au centre de cette table ronde, une magie collective
émerge des voix, dans toute la splendeur de sa virtuosité collective.

Fidèle à cette riche tradition, cette partie du traité introduit les
concepts qui vont nous permettre d’explorer la dualité, ce fragile
mais féerique équilibre entre les dimensions mélodiques et harmoniques
d’une polyphonie.

/Remarques/ :

  - la voix principale était aussi appelée *vox principalis*,
    *cantus*, *cantus firmus*, ou encore *plain-chant*

  - la voix organale était aussi appelée *vox organalis*

  - le terme de motet viendrait de *motetus*, le petit mot, en
    référence au texte ajouté sur la ou les voix supplémentaires


* Dualité

#+TOC: headlines 1 local


** Grille

On peut représenter une polyphonie comme une superposition de
mélodies, mais également comme une succession d’accords, chacun
d’entre-eux régnant un certain temps sur le déroulement musical avant
de laisser la place à son successeur. Le tableau suivant illustre
cette dualité dans le cas d’un septuor :

#+ATTR_HTML: :class plat
| S | : | (accord-1, note-1) | (accord-2, note-1) | (accord-3, note-1) | =...= |
| M | : | (accord-1, note-2) | (accord-2, note-2) | (accord-3, note-2) | =...= |
| A | : | (accord-1, note-3) | (accord-2, note-3) | (accord-3, note-3) | =...= |
| C | : | (accord-1, note-4) | (accord-2, note-4) | (accord-3, note-4) | =...= |
| T | : | (accord-1, note-5) | (accord-2, note-5) | (accord-3, note-5) | =...= |
| Y | : | (accord-1, note-6) | (accord-2, note-6) | (accord-3, note-6) | =...= |
| B | : | (accord-1, note-7) | (accord-2, note-7) | (accord-3, note-7) | =...= |

Cette représentation schématique a le mérite de n’intégrer que les
notes essentielles de la polyphonie, ce qui permet de visualiser du
premier coup d’oeil les évolutions des voix lors des changements
d’accords. Nous appelons *grille polyphonique*, ou plus simplement
*grille* une telle représentation schématique de la polyphonie.


** Notes

Les notes d’une polyphonie peuvent se scinder en deux catégories :

  - les *notes essentielles* sont les notes qui appartiennent à la
    grille polyphonique, et donc à l’un des accords qui la constituent

  - les *notes étrangères* sont les notes qui n’appartiennent pas à la
    grille polyphonique, et donc à aucun des accords qui la
    constituent

Les notes essentielles consitutent la fondation de la polyphonie,
tandis que les notes étrangères servent à compléter le discours
musical.

/Remarque/ : on utilise également les expressions *note réelle* ou
*note constitutive* comme synonymes de note essentielle.


** Accords

On peut classer grossièrement les accords en deux catégories, suivant
leur importance :

  - Les *accords stratégiques* constituent la clef de voûte du
    discours musical

  - Les *accords ornementaux* ont pour but de fluidifier et
    d’ornementer les mélodies


** Enchaînement

On appelle *enchaînement* une suite formée de deux accords
consécutifs.

Deux accords consécutifs sont dit *enchaînés*.


*** Changement d’harmonie

Une *harmonie* peut aussi désigner le règne d’un accord. On parle donc
de *changement d’harmonie* pour signaler un changement d’accord.


** Mélodie

On distingue :

  - l’ *intervalle mélodique* en général, intervalle entre deux notes
    consécutives quelconques

  - l’ *intervalle mélodique essentiel*, intervalle entre deux notes
    essentielles consécutives

On utilise également l’expression *mouvement mélodique essentiel*
comme synonyme d’intervalle mélodique essentiel.

Il existe donc 4 possibilités de mouvement mélodique :

  1. note essentielle — note essentielle : intervalle mélodique essentiel
  2. note essentielle — note étrangère
  3. note étrangère — note essentielle
  4. note étrangère — note étrangère


** Rythme harmonique

Le rythme auquel les accords se succèdent est appelé *rythme
harmonique*. Le rythme harmonique peut être régulier ou variable.

Chaque accord règne un certain temps sur la musique avant de laisser
la place à son successeur. Ce règne peut durer pendant :

  - une carrure (entière, 1/2, 1/4, =...=)

  - une oscillation

  - une pulsation

  - une mesure

  - un temps

  - =...=


** Rencontres

La perception du cadre harmonique est renforcée par des rencontres
entre les notes essentielles les plus importantes de chaque accord.
Ces notes sont alors jouées simultanément sur les différentes voix de
la polyphonie. Les rencontres peuvent se produire à un rythme régulier
ou variable. En fait, elles sont liées au rythme harmonique, l’idéal
étant de disposer au moins une rencontre par accord. Les cas les plus
courants sont :


  - une rencontre au début de chaque temps
  - une rencontre au début de chaque mesure
  - une rencontre au début de chaque pulsation
  - une rencontre au début de chaque oscillation
  - =...=


* Mouvements harmoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements harmoniques* analysent les modifications de
disposition des notes essentielles au cours du règne d’un même accord.


** Échange

L’ *échange* consiste à intervertir les voix de deux notes
essentielles.

Exemple d’échange :

#+ATTR_HTML: :class plat
| S | : | mi | do |
| B | : | do | mi |


** Changement

Le *changement* consiste à modifier une des voix pour jouer une autre
note de l’accord.

Exemple de changement, ici sur le soprano :

#+ATTR_HTML: :class plat
| S | : | mi | sol |
| B | : | do | do  |


* Mouvements polyphoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements polyphoniques* comparent les évolutions de deux voix
quelconques de la grille polyphonique lors d’un changement d’accord,
ce qui les place au croisement de l’harmonie et de la mélodie.

Les intervalles mélodiques analysés sont donc des intervalles
mélodique essentiels.


** Mouvement parallèle

Il se produit un mouvement *parallèle* lorsque les deux voix évoluent
dans la même direction en utilisant le même intervalle mélodique.

/Remarque/ : dans le cadre des mouvements polyphoniques, on ne fait
pas de distinction entre les intervalles majeurs et mineurs. Par
exemple, si une voix monte d’une seconde majeure pendant que l’autre
monte d’une seconde mineure, le mouvement sera considéré comme
parallèle.


*** Ascendant

Un mouvement *parallèle ascendant* est un mouvement parallèle où les
deux voix évoluent vers l’aigu.

Exemple de mouvement parallèle ascendant :

#+ATTR_HTML: :class plat
| S | : | ré | mi | (monte) |
| B | : | la | si | (monte) |


*** Descendant

Un mouvement *parallèle descendant* est un mouvement parallèle où les
deux voix évoluent vers le grave.

Exemple de mouvement parallèle descendant :

#+ATTR_HTML: :class plat
| S | : | ré | do  | (descend) |
| B | : | la | sol | (descend) |


*** Continuité

Un mouvement *parallèle conjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement conjoint.

Un mouvement *parallèle disjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement disjoint.


*** Mélodies parallèles

Le mouvement parallèle se rencontre entre-autres lorsque deux mélodies
évoluent parallèlement. Par analogie avec les premières formes de la
polyphonie, on parle alors :


  - d’ *organum* lorsque l’intervalle qui les sépare est une octave,
    une quinte ou une quarte

  - de *gymel*, ou de *faux-bourdon*, lorsque l’intervalle qui les
    sépare est une tierce ou une sixte


** Mouvement oblique

Il se produit un mouvement *oblique* lorsqu’une des deux voix reste
constante pendant que l’autre varie.

Le mouvement oblique se produit généralement lorsqu’une note commune à
deux accords consécutifs est disposée sur la même voix.


*** Ascendant

Un mouvement *oblique ascendant* est un mouvement oblique où la voix
mobile évolue vers l’aigu.

Exemple de mouvement oblique ascendant :


#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte)    |
| B | : | do | do  | (constant) |


*** Descendant

Un mouvement *oblique descendant* est un mouvement oblique où la voix
mobile évolue vers le grave.

Exemple de mouvement oblique descendant :

#+ATTR_HTML: :class plat
| S | : | fa | ré | (descend)  |
| B | : | do | do | (constant) |


*** Continuité

Un mouvement *oblique conjoint* est un mouvement oblique où la voix
mobile évolue par mouvement conjoint.

Un mouvement *oblique disjoint* est un mouvement oblique où la voix
mobile évolue par mouvement disjoint.


** Mouvement contraire

Il se produit un mouvement *contraire* lorsque les deux voix évoluent
dans des directions opposées : l’une monte, l’autre descend. C’est un
mouvement naturellement très équilibré.


*** Extérieur

Un mouvement *extérieur* est un mouvement *contraire* où la voix
supérieure monte, tandis que la voix inférieure descend.

Pour s’en souvenir, se rappeler que les voix d’un mouvement extérieur
se dirigent vers l’extérieur.

Exemple de mouvement extérieur :

#+ATTR_HTML: :class plat
| S | : | si  | do | (monte)   |
| B | : | sol | fa | (descend) |


*** Intérieur

Un mouvement *intérieur* est un mouvement *contraire* où la voix
supérieure descend, tandis que la voix inférieure monte.

Pour s’en souvenir, se rappeler que les voix d’un mouvement intérieur
se dirigent vers l’intérieur.

Exemple de mouvement intérieur :

#+ATTR_HTML: :class plat
| S | : | si | la | (descend) |
| B | : | mi | fa | (monte)   |


*** Continuité

Un mouvement *contraire conjoint* est un mouvement contraire où les
deux voix évoluent par mouvement conjoint.

Un mouvement *contraire disjoint* est un mouvement contraire où au
moins une des voix évolue par mouvement disjoint.


** Mouvement direct

Il se produit un mouvement *direct* lorsque les deux voix évoluent
dans la même direction, mais au moyen d’intervalles différents.


*** Ascendant

Un mouvement *direct ascendant* est un mouvement direct où les deux
voix évoluent vers l’aigu.

Exemple de mouvement direct ascendant :

#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte) |
| B | : | mi | si  | (monte) |


*** Descendant

Un mouvement *direct descendant* est un mouvement direct où les deux
voix évoluent vers le grave.

Exemple de mouvement direct descendant :

#+ATTR_HTML: :class plat
| S | : | fa  | mi | (descend) |
| B | : | sol | do | (descend) |


*** Continuité

Un *mouvement direct conjoint* est un mouvement direct où l’une des
voix évolue par mouvement conjoint tandis que l’autre évolue par
mouvement disjoint.

Un *mouvement direct disjoint* est un mouvement direct où les deux
voix évoluent par mouvement disjoint.

De façon générale, le mouvement direct est considéré comme plus
élégant lorsqu’une des deux voix évolue par mouvement conjoint.


*** Bonne pratique

Le mouvement direct est le plus élégant lorsqu’une des voix évolue par
mouvement conjoint tandis que l’autre effectue un mouvement disjoint
(idéalement quarte ou quinte), l’idée étant que le contraste entre les
variations des deux voix le fasse ressembler à un mouvement oblique.


** Mouvement consécutif
:PROPERTIES:
:CUSTOM_ID: section:mouvementConsecutif
:END:


Il se produit un mouvement *consécutif* lorsque les deux voix
reproduisent un même intervalle harmonique à l’octave près, que ce
soit par mouvement parallèle, oblique, contraire ou direct.

Exemple de mouvement consécutif reproduisant une tierce :

#+ATTR_HTML: :class plat
| S | : | mi | la  | (monte d’une 4te ou descend d’une 5te) |
| B | : | do | fa  | (monte d’une 4te ou descend d’une 5te) |


** Disposition des voix

Cette section analyse certaines configurations liées à la disposition
relative des voix.


*** Croisement

Un *croisement* se produit lorsqu’une note essentielle d’une voix
normalement plus grave croise à la hausse une note essentielle d’une
voix plus aiguë.


*** Chevauchement

Un *chevauchement* se produit lorsqu’une note essentielle d’une voix
plus grave croise à la hausse une note essentielle d’une voix plus
aiguë /de l’accord précédent/.


*** Fausse relation

Une fausse relation est une association de deux notes disposées sur
des voix différentes.


**** Chromatique

Une *fausse relation chromatique* se produit lorsque les trois notes
d’un mouvement chromatique ne sont pas toutes disposées sur la même
voix.


**** Triton

Une *fausse relation de triton* se produit lorsque les deux notes d’un
intervalle de triton :

  - appartiennent à deux accords consécutifs
  - sont situées sur deux voix différentes


** Principes


*** Économie de mouvement


**** Changement d’accord

Le principe d’ *économie de mouvement* dit que les notes essentielles
doivent évoluer majoritairement par mouvement conjoint au cours d’un
changement d’accord, ce qui permet :

  - de distinguer plus aisément les différentes voix de la polyphonie

  - de distinguer les intervalles internes des accords (tierces,
    sixtes, etc) des intervalles permettant l’enchaînement

On priviligiera donc à chaque enchaînement :

  - le mouvement conjoint sur une majorité des voix
  - les sauts de quinte ou de quarte sur les voix restantes

Ceci étant dit, on peut bien entendu se permettre une tierce ou une
sixte occasionnelle si cela correspond à un effet souhaité, ou s’il
est difficile de s’en passer sans dénaturer le paysage musical.

/Remarque/ : ce principe s’applique aux changements de notes
essentielles lors du passage d’un accord à un autre. Il n’y a par
contre aucune réserve à avoir concernant l’utilisation des tierces et
des sixtes mélodiques à l’intérieur du règne d’un même accord.


**** Mélodie

Le principe d’économie de mouvement est également valable à l’échelle
des mélodies de la grille polyphonique, mélodies générées par la
succession des accords : chacune d’entre-elle doit évoluer
majoritairement par mouvement conjoint, ceci afin de permettre à
l’oreille de discerner les différentes voix qui composent la
polyphonie. Cette continuité majoritaire permet également d’accentuer
aisément les fins de phrases en utilisant le contraste qu’offrent
alors les sauts discontinus des mouvements disjoints.


*** Mouvements, accords et dispositions

De nombreux accords et dispositions différentes peuvent assurer une
même fonction tonale, ce qui permet de les choisir au mieux afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.


*** Lignes mélodiques extrêmes

Les mouvements formés par les lignes mélodiques extrêmes (basse et
soprano) doivent être particulièrement soignés, car ce sont les voix
les plus évidentes pour l’oreille.


* Ornements

#+TOC: headlines 1 local

** Introduction

La modélisation d’une polyphonie sous la forme d’une suite d’accords
est d’une grande clarté et permet de cerner l’essentiel. Mais
l’essentiel n’est pas tout, et si la sobriété est très utile dans les
premières phases de la composition, on est amenés par la suite à
insérer des *ornements* afin de donner de la souplesse aux lignes
mélodiques ou d’enrichir la dynamique harmonique.

On appelle *note ornementale* une note constitutive d’un ornement.


** Notes essentielles & étrangères

Parmi les notes ornementales, on distingue :

  - les *notes ornementales essentielles* : notes ornementales qui
    font partie de l’accord en cours

  - les *notes ornementales étrangères* : notes ornementales qui ne
    font pas partie de l’accord en cours


** Ornements harmoniques

Cette section analyse les ornements dont la fonction est
essentiellement harmonique.


*** Arpège

Un *arpège* consiste à jouer consécutivement une partie ou la totalité
des notes de l’accord en cours. Chaque note peut être répétée, à
l’unisson où à l’octave près.

Les arpèges d’accords à base de tierces sont très utilisés dans la
construction de voix accompagnatrices d’une mélodie principale.

Les arpèges d’accords à base de quintes s’apparentent aux modes
pentaphoniques ou tétraphoniques. Ils sont donc très utilisés dans la
construction de mélodies blues par exemple.


**** Accord brisé

Un *accord brisé* est une généralisation de l’arpège, où plusieurs
notes de l’accord peuvent être jouées simultanément. Les deux termes
sont parfois considérés comme synonymes.


*** Pédale

Une *pédale* est une note qui reste obstinément constante,
indépendamment des accords qui se succèdent sur les autres voix.

Exemple de pédale, ici à la basse :

#+ATTR_HTML: :class plat
| S | : | la   | si   | mi   |
| A | : | fa   | sol  | do   |
| B | : | /do/ | /do/ | /do/ |


*** Retard

Un *retard* est une note intégrée à un accord et qui se poursuit
au-delà du changement d’accord, empiétant sur le début du règne de
l’accord suivant.

Exemple de retard, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | do  |
| A | : | la   | sol  | sol |
| B | : | fa   | mi   | mi  |


*** Anticipation

Une *anticipation* est une note appartenant à un accord qui est
entamée avant la fin du règne de l’accord précédent.

Exemple d’anticipation, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


*** Appogiature

Une *appogiature* est une note arbitraire jouée au début du règne d’un
accord.


** Ornements mélodiques


Cette section analyse les ornements dont la fonction est
essentiellement mélodique.


*** Note de passage

Une *note de passage* est une note ornementale permettant de relier
par mouvement conjoint deux notes appartenant à un même accord où à
deux accords différents. Exemple :

#+BEGIN_CENTER
do /si/ la
#+END_CENTER

Autre exemple, avec deux notes de passage consécutives :

#+BEGIN_CENTER
ré /do si/ la
#+END_CENTER


*** Broderie

Une *broderie* est une note conjointe qui quitte une note de l’accord
avant de la retrouver. Exemple :

#+BEGIN_CENTER
do /ré/ do
#+END_CENTER


**** Double

La *double broderie* combine une broderie vers le haut et une broderie
vers le bas. Exemple :

#+BEGIN_CENTER
do /ré si/ do
#+END_CENTER


*** Échappée

L’ *échappée* quitte une note conjointe de l’accord et est suivie par
une note disjointe du même accord ou de l’accord suivant. Exemple :

#+BEGIN_CENTER
sol /la/ ré
#+END_CENTER


** Ornements répétitifs


*** Trémolo

Un *trémolo* consiste à alterner deux notes. Exemple :

#+BEGIN_CENTER
do sol do sol do sol do sol
#+END_CENTER


**** Basse de Murky

Il s’agit dun trémolo en octave.


*** Trille

Un *trille* consiste à alterner deux notes séparées par une seconde
majeure ou mineure. Exemple :

#+BEGIN_CENTER
do ré do ré do ré do ré
#+END_CENTER


*** Roulement

Un *roulement* consiste à répéter une même note. Exemple :

#+BEGIN_CENTER
do do do do do do do do
#+END_CENTER


** Combinaisons

Les ornements peuvent être combinés : broderie d’une note de passage,
retard d’une broderie, anticipation d’une note de passage, etc.


* Accords ornementaux


** Accord de passage

Les *accords de passage* ont pour fonction de permettre une transition
fluide, principalement par mouvements conjoints, entre deux autres
accords.


*** Échange fluide

Lorsqu’on souhaite échanger deux notes d’un accord tout en opérant par
mouvements conjoints, il est parfois nécessaire d’intercaler un accord
de passage entre la disposition initiale et la disposition finale. À
deux voix, on a par exemple :

#+ATTR_HTML: :class plat
| S | : | mi | ré | do |
| B | : | do | ré | mi |

Dans cet exemple, on échange le soprano et la basse :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | do   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Autre exemple, avec un accord de 7e comme point de départ :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | si   | si   | si   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Enfin, l’accord final peut révéler une version 7e de l’accord de
départ :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | la   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |


*** Suites d’accords de passage

Il est possible d’enchaîner plusieurs accords ornementaux. On assiste
alors généralement à la formation de portions de gammes diatoniques ou
chromatiques sur une des voix.


** Accord broderie

Un *accord broderie* est un accord dont au moins une des notes effectue
une broderie par rapport aux notes des accords environnant disposées
sur la même voix.

Le second renversement de l’accord parfait peut servir d’accord de
broderie. En effet, il est proche d’un accord parfait dont la
fondamentale est située une quinte plus haut. On le fait donc souvent
suivre ou précéder par cet accord parfait. On observe alors les
intervalles suivant, par rapport à la basse :

  - tierce ↦ quarte ↦ tierce
  - quinte ↦ sixte ↦ quinte

Exemple de broderie d’un accord parfait de fondamentale /do/ :

#+ATTR_HTML: :class plat
| S | : | sol | la | sol |
| A | : | mi  | fa | mi  |
| B | : | do  | do | do  |

Voir aussi la section concernant la [[file:musica-05-tablature.org::#section:quarteEtSixteCadentielle][quarte et sixte cadentielle]].


** Accord pédale

Un *accord pédale* est un accord maintenu constant sur une partie des
voix pendant que d’autres accords se succèdent sur les autres voix.

Un exemple d’accord-pédale est celui où un même accord est arpégé
inlassablement sur une des voix.


* Superposition rythmique

#+TOC: headlines 1 local

** Introduction

Ce chapitre analyse les configurations rythmiques que l’on rencontre
dans une polyphonie.


** Classification


*** Rythmes identiques

Les deux rythmes sont identiques. Exemple :

#+ATTR_HTML: :class plat
| S | : | B N | N N N | Bp |
| B | : | B N | N N N | Bp |


*** Rythmes contrastés

Un rythme est lent, l’autre est rapide. Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | Bp |   |   |
| B | : | N  | N | N | N  | N | N |


*** Rythmes dialogués

Les voix alternent rythmes rapides et lents, afin de laisser à chacune
un « temps de parole ». Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | N  | N | N |
| B | : | N  | N | N | Bp |   |   |


*** Rythmes décalés

Les deux rythmes sont décalés. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | — | — | N | — | — | N |


*** Rythmes hybrides

Il s’agit de rythmes alternativement synchronisés et décalés.
Exemples :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | N | — | N | N | — | N |

Le même en version fluide :

#+ATTR_HTML: :class plat
| S | : | N | B |   | N | B |   |
| B | : | B |   | N | B |   | N |


*** Rythmes convergents

Ce sont des rythmes contrastés, décalés ou hybrides qui convergent
l’un vers l’autre. Cette situation est très fréquente à l’approche des
fins de phrase, où toutes les voix finissent par ralentir. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | — | N | B |   | N | Bp |
| B | : | N | N | — | N | B |   | Bp |


*** Rythmes fleuris

Il est bien évident que chaque mélodie peut changer de rythme à tout
instant, modifiant du même coup l’agencement rythmique de la
polyphonie. Lorsqu’une superposition de rythmes fait entendre
successivement différentes configurations, on parle de style fleuri.


** Rythmes agrégés

Un rythme agrégé résulte de la condensation en une seule voix des
différents rythmes d’une polyphonie : chaque nouvelle note entamée sur
une des voix est également entamée sur le rythme agrégé. Considérons
par exemple la superposition :

#+ATTR_HTML: :class plat
| S | : | Np | C  |
| B | : | C  | Np |

Pour obtenir le rythme agrégé, on décompose le temps en suivant la
plus petite valeur commune, ici la croche, et on note le début de
chaque note sur le tableau correspondant :

#+ATTR_HTML: :class plat
|        |   | C | C | C | C |
| S      | : | X |   |   | X |
| B      | : | X | X |   |   |
| Agrégé | : | X | X |   | X |

On voit qu’aucune note n’est entamée à la troisième croche.
Le rythme agrégé associé est donc :

#+BEGIN_CENTER
C C cs C
#+END_CENTER

ou, en version fluide :

#+BEGIN_CENTER
C N C
#+END_CENTER


*** Binaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| Ν N + Np C         | N C C           |
| Np C + C Np        | C N C           |
| N C C + C N C      | C C C C         |
| N N + C N C        | C C C C         |
|                    |                 |

*** Ternaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| B N + N B          | Ν N N           |
| N B + B C C        | N N C C         |
| N C N C + N N N    | N C C C C       |


*** Hybrides

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| N N N + Np Np      | N C C N         |
| B N + Np Np        | Np C N          |
| B C C + Np Np      | Np C C C        |
| N B + Np Cp Cp     | N C Cp Cp       |


** Structure rythmique

Le moyen le plus simple permettant d’établir la structure rythmique
d’une polyphonie consiste à assigner une échelle rythmique différente
à chacune des voix. Par exemple, une voix peut jouer une note à chaque
oscillation, une autre à chaque mesure ou pulsation et une troisième à
chaque temps. Dans l’hypothèse d’un quatuor, cela laisse une voix au
rythme totalement libre.

Toutes les variantes de ce schéma sont possibles. Dans les cas
extrêmes, la structure rythmique est répartie sur toutes les voix, sur
une seule, voire sur aucune. Les rythmes eux-mêmes peuvent n’être
qu’approximativement réguliers : l’essentiel est qu’ils établissent
clairement les fondations rythmiques de la polyphonie.

De plus, les rôles des voix peuvent être permutés ou modifiés à tout
moment, ce qui permet de générer une musique vive et variée.


*** Ostinato

L’ostinato permet de concentrer le support rythmique en une seule
voix, ce qui libère les rythmes du reste de l’ensemble.

Considérons par exemple une carrure composée de quatre oscillations.
Chaque oscillation est subdivisée en deux pulsations ternaires durant
chacune une blanche pointée. Cette structure correspond au schéma :

#+ATTR_HTML: :class plat
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |

On peut lui associer l’ostinato suivant :

#+ATTR_HTML: :class plat
| Bp    | B N   |
| N N N | B N   |
| Bp    | B N   |
| N N N | N N N |

/Remarque/ : par son coté inlassable, constant dans un environnement
variable, on peut voir un ostinato comme une sorte de pédale rythmique.


*** Percussions

Un autre moyen de mettre en évidence la structure rythmique d’une
oeuvre est d’ajouter des percussions. Les rythmes des voix préalables sont
alors totalement libérés.


** Syncopes


*** Retard harmonique

Un procédé élégant consiste à utiliser une syncope pour produire
un retard harmonique.


*** Syncope d’harmonie

La syncope d’harmonie est un accord entamé sur temps faible, ou partie
faible de temps, et poursuivi sur temps fort, ou partie forte de
temps.


*** Contraste

Il arrive souvent qu’on mette en relief une syncope en introduisant un
contraste voix syncopée — voix sans syncope. Dans ce cas, la tension
découle naturellement du contraste.


* Accentuation

#+TOC: headlines 1 local


** Mélodie

Une mélodie est généralement accentuée par :

  - des paliers : notes de longue durée
  - des extrêmes : pics ou creux locaux
  - des virages : changements de direction, de pente
  - des sauts : mouvements disjoints dans une mélodie majoritairement conjointe


** Notes essentielles

Les accents mélodiques sont généralement disposés sur des notes
essentielles.


*** Discontinuités

Ceci est particulièrement vrai pour les discontinuités. Il est donc
rare d’observer un mouvement disjoint ne faisant intervenir aucune
note de l’accord.


** Indépendance

Les accents mélodiques des différentes voix de la polyphonie sont
indépendants. La plupart du temps, on s’arrange pour que ces accents
apparaissent à des instants différents sur chacune des voix, ceci afin
de les mettre tour à tour en évidence.

Il arrive toutefois que les accents mélodiques soient synchronisés
afin de donner à l’ensemble un effet de convergence et d’apothéose
très convaincant.


* Enchaînements

#+TOC: headlines 1 local

** Dynamique

Le principe d’alternance d’accords stables et instables est
omniprésent en musique. Ce ressort musical est centré autour d’une
phase de *tension*, accord instable contenant une ou plusieurs notes
dissonantes. Chaque tension est suivie d’une phase de *résolution* où
chaque note dissonante se résout vers une note d’un accord stable.

La résolution d’une note instable dans un accord stable peut se
réaliser suivant différents schémas :

  - *résolution conjointe* : la note instable réalise un mouvement
    conjoint vers une note inclue dans l’accord stable

  - *résolution polyphonique* : les notes instables réalisent un
    mouvement polyphonique élégant vers des notes inclues dans
    l’accord stable

  - *résolution par intégration* : la note instable est inclue dans
    l’accord stable suivant et devient donc naturellement stable lors
    du changement d’accord

La tension peut être précédée d’un accord stable de *préparation* :

  - qui permet d’amener les notes dissonantes par mouvement conjoint,
    on a alors *préparation conjointe*

  - qui permet d’amener les notes dissonantes par un mouvement
    polyphonique élégant, on a alors *préparation polyphonique*

  - qui contient les futures notes dissonantes, on a alors
    *préparation par intégration*

On a donc le cycle générique :

#+BEGIN_CENTER
préparation  —  tension  —  résolution  — préparation  —  tension  — résolution  —  =...=
#+END_CENTER

où les préparations sont facultatives. Lorsque l’accord de préparation
est omis, on dit que la dissonance est *attaquée*.

Remarquons que l’accord de résolution peut servir d’accord de
préparation à la tension suivante, formant ainsi un cycle :

#+BEGIN_CENTER
préparation —  tension  —  (résolution & préparation)  —  tension  — (résolution & préparation)  —  =...=
#+END_CENTER


** Notes communes

#+TOC: headlines 1 local

*** Aucune note commune

Si la basse évolue par mouvement conjoint et que les accords enchaînés
ne possèdent aucune note commune, on fait généralement évoluer les
autres voix par mouvement contraire. On conserve ainsi un certain
équilibre entre les voix.

Exemple sans note commune :

#+ATTR_HTML: :class plat
| S | : | do | si  | (descend) |
| A | : | la | sol | (descend) |
| T | : | fa | ré  | (descend) |
| B | : | fa | sol | (monte)   |

Lorsque ce n’est pas possible, on essaie malgré tout de privilégier un
mouvement contraire entre les voix extrêmes.


*** Une note commune

Lorsque deux accords consécutifs possèdent une note commune, on la
place généralement sur une même voix afin de respecter la philosophie
de l’économie de mouvement. On génère alors des mouvements obliques
avec les autres voix.

Lorsque c’est possible, on privilégie les mouvements obliques
conjoints, avec éventuellement un mouvement disjoint.

Lors d’un enchaînement d’accords parfaits respectant les conditions
suivantes :

  - à l’état fondamental
  - à la quinte descendante
  - avec une basse disjointe

la basse du deuxième accord fera entendre une nouvelle note, ce qui
donnera plus de solennité à l’enchaînement.

Exemple de note commune disposée sur une même voix :

#+ATTR_HTML: :class plat
| S | : | si    | do    |
| A | : | /sol/ | /sol/ |
| T | : | ré    | mi    |
| B | : | sol   | do    |


*** Deux notes communes

Lorsque deux accords consécutifs possèdent deux notes communes, on les
place généralement sur une même voix.

Lors d’un enchaînement d’accords parfaits respectant les conditions
suivantes :

  - à l’état fondamental
  - à la tierce descendante
  - avec une basse disjointe

la basse du deuxième accord fera entendre une nouvelle note, ce qui
donnera plus de solennité à l’enchaînement.

Exemple avec deux notes communes :

#+ATTR_HTML: :class plat
| S | : | /la/ | /la/ |
| A | : | mi   | fa   |
| T | : | /do/ | /do/ |
| B | : | la   | fa   |


* Dynamique des ornements

#+TOC: headlines 1 local


** Introduction

Une note ornementale peut être :

  - consonante, si elle peut s’interpréter comme note consonante de
    l’accord en cours

  - dissonante, sinon

    + note essentielle dissonante

    + note étrangère dissonante

Dans tous les cas, une note ornementale joue un rôle dynamique dans la
polyphonie. On utilise donc les termes de préparation et de résolution
pour toutes les notes ornementales :

  - la préparation est un accord qui prépare l’arrivée de la note ornementale
  - la résolution fait évoluer la note ornementale au sein d’un nouvel accord

Ces deux phases peuvent s’effectuer :

  - par mouvement conjoint
  - par intégration dans l’accord concerné
  - par mouvement polyphonique élégant

Ce processus est donc en tout point similaire à celui de la
préparation et de la résolution de dissonance.


** Pédale

Lorsqu’une *pédale* est présente, elle est en général alternativement
dissonante et consonante par rapport aux accords qui se succèdent sur
les autres voix.

Une pédale est souvent préparée en s’intégrant à un premier accord et
en perdurant après sa disparition. Le dernier accord qui se superpose
à une pédale lui est en général également consonant.

Autrement dit, une pédale est généralement préparée et résolue par
intégration.


** Retard

Le retard se résout généralement en évoluant par mouvement conjoint
vers une note du nouvel accord. Par définition, un retard est préparé
par intégration.

Suivant le sens du mouvement, on distingue :

  - le *retard supérieur* qui se résout en descendant
  - le *retard inférieur* qui se résout en montant

Par exemple, dans l’enchaînement suivant, le /ré/ au soprano est un
retard supérieur qui se résout en descendant vers le /do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /do/ |
| A | : | la   | sol  | sol  |
| T | : | fa   | mi   | mi   |
| B | : | ré   | do   | do   |

Autre exemple où le /ré/ est un retard inférieur qui se résout en
montant vers le /mi/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /mi/ |
| A | : | la   | la   | la   |
| B | : | fa   | do   | do   |


** Anticipation

L’anticipation se résout par intégration dans l’accord suivant. Par
exemple, dans l’enchaînement suivant, le /mi/ au soprano est une
ancicipation :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


** Appogiature

L’appogiature se résout généralement en évoluant par mouvement
conjoint vers une note de l’accord.

Contrairement au retard qui est préparé par intégration, l’appogiature
est généralement préparée par mouvement conjoint, mouvement polyphonique,
ou purement et simplement attaquée.


* Camouflage
:PROPERTIES:
:CUSTOM_ID: section:camouflage
:END:

#+TOC: headlines 1 local

** Introduction

Il arrive qu’une disposition musicale génère un effet inhabituel,
voire étrange.

Lorsqu’on est confronté à une telle disposition, il existe alors trois
possibilités :

  1. l’éviter complètement
  2. l’appliquer malgré tout, car elle correspond à l’effet désiré
  3. s’arranger pour qu’elle reste discrète

Nous étudions dans ce chapitre les techniques d’insertion discrète
dans une polyphonie.


** Position

Lorsqu’on souhaite rendre un agencement discret, on peut :

  - le placer dans les voix internes, plus discrètes
  - le placer sur un temps faible de la mesure


** Divertissement

On fait intervenir un autre paramètre (mélodique, harmonique,
rythmique, etc) pour divertir l’oreille, qui prête alors moins
attention à l’agencement que l’on veut placer à l’arrière-plan.


** Intervalles harmoniques

Pour rendre un intervalle harmonique plus discret, on peut faire
commencer une des deux notes avant l’autre.

On peut même aller plus loin et éviter de produire cet intervalle
harmonique. On utilise alors une des techniques suivantes :

  - modifier la disposition de l’accord concerné
  - intercaler une modification de la disposition de l’accord
    + échange
    + changement
  - décaler une des deux notes à un autre moment du règne de l’accord


** Mouvements polyphoniques


*** Direct disjoint

Pour masquer un mouvement direct disjoint, on peut ajouter une ou
plusieurs notes de passage afin de produire un mouvement mélodique
conjoint. Le mouvement mélodique essentiel associé restera disjoint,
mais sera plus discret.

Exemple, on part de :

#+ATTR_HTML: :class plat
| S | : | si  | mi |
| B | : | sol | mi |

et on ajoute la note de passage /fa/, pour obtenir :

#+ATTR_HTML: :class plat
| S | : | si  |      | mi |
| B | : | sol | /fa/ | mi |


* Conseils d’écriture
:PROPERTIES:
:CUSTOM_ID: section:conseilsDEcriture
:END:

#+TOC: headlines 1 local


** Introduction

Ce chapitre a pour but de nous aider à acquérir de bonnes habitudes
dans la pratique de l’écriture polyphonique. À cette fin, certaines
constructions musicales y sont privilégiées, d’autres sont
déconseillées.

Prenons garde toutefois à ne pas en faire des règles rigides : ces
principes sont supposés être mis en oeuvre par défaut, dans un
contexte dépourvu de toute particularité qui nous permettrait
d’orienter la musique vers une autre configuration. Il n’est pas rare
non plus qu’un aspect musical élégant justifie largement l’emploi
d’une disposition alternative.

L’important est de bien connaître l’effet que produira l’application
ou la transgression d’un de ces conseils, afin de pouvoir orienter la
musique dans la direction souhaitée. Une autre possibilité consiste à
faire passer un agencement déconseillé à l’arrière-plan en utilisant
les techniques de [[#section:camouflage][camouflage]].


** Mélodie

#+TOC: headlines 1 local

*** Plage

On privilégie les intervalles mélodiques suivants :

  - l’unisson
  - les secondes majeure et mineure
  - les tierces majeure et mineure
  - la quarte juste
  - la quinte juste
  - la sixte mineure
  - l’octave

Ceux-ci sont déconseillés :

  - les intervalles augmentés et diminués
    + dont le triton
  - la sixte majeure
  - les septièmes majeure et mineure
  - les intervalles dépassant l’octave


*** Mouvement disjoint

Les mouvements disjoints sont de préférence précédés ou suivis par un
intervalle mélodique allant dans le sens opposé du saut.


*** En trois notes


Les septièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  - sixte mélodique puis seconde mélodique dans le même sens
  - octave mélodique puis seconde mélodique dans le sens opposé

#+begin_center
⁂
#+end_center

Les neuvièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  1. octave mélodique puis seconde mélodique dans le même sens
  2. dixième mélodique puis seconde mélodique dans le sens opposé

Les intervalles mélodiques dépassant l’octave étant déconseillés, on
préférera la première solution.

#+begin_center
⁂
#+end_center

La quarte augmentée (triton) parcourue en trois notes est suivie de
préférence d’une seconde mineure de même direction, afin de former une
quinte juste en quatre notes.


** Écarts des voix

#+TOC: headlines 1 local

*** Harmoniques naturelles

Une disposition élégante consiste à suivre approximativement les
harmoniques naturelles, où les notes sont plus éloignées dans les
graves et plus proches dans les aiguës.

En appliquant ce principe à un quatuor, on obtient, par ordre
décroissant des écarts :

#+BEGIN_CENTER
basse — ténor   >   ténor — alto   >   alto — soprano
#+END_CENTER


*** Écart maximal

On convient généralement d’éviter un écart de plus d’une octave entre
voix adjacentes. Une exception à ce principe, qui découle des
harmoniques naturelles : l’intervalle entre la basse et la voix qui
lui est immédiatement supérieure (le ténor dans un quatuor) peut
dépasser une octave.

Dans le cas d’un quatuor, si l’alto et le ténor sont séparés d’une
octave, on resserre le ténor et la basse à distance de tierce ou moins.


*** Régulière

Les intervalles sont à peu près égaux entre chaque paire de voix
adjacentes.


*** Basse éloignée

La basse est éloignée, les autres voix sont resserrées.


** Mouvements

#+TOC: headlines 1 local

*** Oblique


**** Consonances parfaites

L’arrivée sur unisson par mouvement oblique conjoint est déconseillée.

Quitter l’unisson par mouvement direct (conjoint ou disjoint) ne pose
aucun problème.


*** Direct


**** Consonances parfaites

L’arrivée sur unisson par mouvement direct est déconseillé.

Lorsqu’un mouvement direct débouche sur une octave ou une quinte :

  - on veille généralement à ce que l’une des voix évolue par
    mouvement conjoint

  - si le mouvement direct à lieu entre les voix extrêmes, la voix
    conjointe sera de préférence le soprano.


*** Consécutif
:PROPERTIES:
:CUSTOM_ID: section:conseilsMouvementConsecutif
:END:


**** Consonances parfaites

Les unissons, octaves et quintes consécutifs sont généralement
déconseillés dans les traités d’harmonie, car la répétition de ces
intervalles diminue l’indépendance des voix.

Toutefois, ce conseil est à relativiser : lorsque deux mélodies sont
parallèles, l’une étant transposée suivant l’un de ces intervalles, on
assiste naturellement à la formation d’unissons, d’octaves ou de
quintes parallèles, et donc consécutifs. L’organum strict, une des
premières formes de polyphonie, a utilisé abondamment ce principe
pendant plusieurs siècles

En pratique, si vous souhaiter utiliser des consonances parfaites
consécutives sans trop les exposer, vous pouvez utiliser les
techniques de [[#section:camouflage][camouflage]].


**** Consonances imparfaites

Pour éviter la monotonie, on déconseille :

  - plus de trois tierces consécutives
  - plus de trois sixtes consécutives


*** Croisement

Afin de bien distinguer les lignes mélodiques constitutives d’une
polyphonie, le croisement est généralement déconseillé. Certaines
circonstances, comme l’utilisation de timbres différents, permettent
toutefois d’éviter la confusion. Il peut arriver aussi qu’une
confusion fugitive soit souhaitée.


*** Chevauchement

Tout comme le croisement, le chevauchement est généralement déconseillé,
sauf effet ponctuel désiré.


*** Fausse relation chromatique

La fausse relation chromatique a tendance à mêler les voix concernées
et est donc en général déconseillée. Il existe toutefois des
exceptions.


**** Relais

Lorsqu’on souhaite déplacer un développement mélodique d’une voix à
une autre, la fausse relation chromatique sert de [[file:musica-06-clechant.org::#section:relais][relais]].


**** Sixte napolitaine

La succession du degré 2 baissé de la sixte napolitaine avec le degré
2 de l’accord de dominante ne pose pas de problème.


**** Septième de dominante

Si l’un des deux accords est une septième de dominante, la fausse
relation chromatique ne pose pas de problème.


*** Fausse relation de triton

La fausse relation de triton est déconseillée dans l’enchaînement des
degrés 5 et 4.


** Harmonie

#+TOC: headlines 1 local

*** Accord de sixte

Les accords de sixte, premiers renversements des accords parfaits,
sont fréquemment disposés avec la fondamentale au soprano.

Les suppressions sont déconseillées.


*** Septième de dominante

La 3ce est la sensible inférieure de la gamme, qui se résout en
montant vers la tonique.

La 7e est une dissonance qui se résout par mouvement conjoint. Deux
cas sont possibles :

  - si on la fait descendre, on arrive sur la médiante, c’est la
    résolution la plus fréquente

  - si on la fait monter, on retombe sur la tonique, qui est déjà
    entendue dans le mouvement sensible inférieure — tonique

La 7e peut être agrémentée d’une broderie qui passe par la
fondamentale.

Par contre, il est déconseillé de procéder à un échange entre la 7e et
la fondamentale.


*** Neuvième de dominante majeure

La 9e est de préférence placée au-dessus :

  - de la fondamentale
  - de la sensible

Idéalement, elle forme au moins un intervalle de neuvième avec la
fondamentale.

Si la 9e est sous la sensible, on conseille de préparer une des deux
notes.

Si la 9e est à la basse, il est préférable de la préparer.

La 9e est une dissonance qui se résout généralement par mouvement
conjoint, en descendant vers la dominante.

L’arrivée sur la 9e par mouvement direct disjoint est déconseillée.

L’arrivée sur la 9e par mouvement direct conjoint est déconseillée si
l’accord est renversé.

La sensible et la 7e se résolvent comme dans l’accord de septième.


*** Neuvième de dominante mineure

Les conseils sont similaires à ceux de la neuvième majeure, avec
quelques nuances.

La 9e se placer sans problème sous la sensible.

Lorsque la fondamentale est supprimée, on peut oublier les règles de
disposition concernant la 7e, la 9e et la sensible.

Échange fréquent : la 7e et la 9e, avec la fondamentale en note de
passage.


** Dissonances

#+TOC: headlines 1 local

*** Voix

Une dissonance se trouve habituellement sur la même voix que sa
résolution. On peut toutefois procéder à un échange de voix simultanée
à une résolution ordinaire, produisant ainsi un effet inattendu.


*** Résolution irrégulière

Lorsqu’il n’est pas possible de procéder à un mouvement obligé, il est
préférable de quitter la dissonance par mouvement conjoint.


*** Doublure

Supposons qu’une dissonance soit doublée. La double résolution
attendue provoque en ce cas des octaves consécutives, phénomène que
l’on souhaite généralement éviter. Exemple :

#+ATTR_HTML: :class plat
| S | : | si | do |
| B | : | si | do |

Il est donc déconseillé de doubler une note dissonante.

Pour la même raison, on évite de doubler :

  - une note altérée
  - une note intervenant dans un mouvement chromatique
  - la sensible
  - la 7e d’un accord de 4 notes ou plus
  - la 9e d’un accord de 5 notes ou plus
  - la 5te de l’accord de quinte diminuée

Si l’on souhaite malgré tout doubler une dissonance, ou qu’il est
difficile de faire autrement, il est préférable que la doublure
n’évolue pas vers la même note que l’originale.

La dissonance et sa doublure sont de préférence :

  - amenées par mouvement contraire ou oblique
  - quittées par mouvement contraire


**** Préparation

Si une note de préparation est doublée, on quitte de préférence cette
note et sa doublure par mouvement contraire ou oblique.


**** Résolution

Si la note de résolution est doublée, on amène de préférence cette
note et sa doublure par mouvement contraire.

L’arrivée sur résolution par mouvement oblique est déconseillée.


*** Altérations

Il est déconseillé de faire entendre simultanément une note de la gamme et son
altération.

Il est déconseillé de produire une tierce diminuée par altération.

Dans les accords de sixte précédant une fonction de dominante, la
basse et la 6te sont propices aux altérations, produisant ainsi les
sixtes augmentées des accords de dominante auxiliaire.


** Ornements

#+TOC: headlines 1 local

*** Retard

Pendant l’accord de préparation, afin de ne pas gâcher l’effet de
surprise, on évite habituellement de faire entendre le retard en même
temps que sa note de résolution.

On peut cependant l’envisager si les conditions suivantes sont
réunies :

  - la note de résolution est sous le retard
  - la note de résolution est placée sur une voix interne
  - l’intervalle harmonique entre retard et résolution est au moins égal à la septième


*** Seconde mineure

L’intervalle harmonique de seconde mineure (à l’octave près) entre :

  - une note de passage et une autre voix
  - une broderie et une autre voix

est déconseillé.


** Rythme


*** Syncope d’harmonie

La syncope d’harmonie est déconseillée car elle déstabilise la
structure rythmique d’une polyphonie.


*** Syncope des parties extrêmes

La syncope simultanée au soprano et à la basse est déconseillée, car
ce procédé perturbe la structure rythmique d’une polyphonie.


* Stratification

#+TOC: headlines 1 local


** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique
tonalité, on parle de *musique tonale*. Il existe donc à tout moment
un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.


** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre tonalité, distincte
de celles des autres groupes, on parle de musique polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.


** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.


** Polyrythmie

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de *polymétrie* ou de *rythmes polymétriques*.


**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| X | : | § | χ | ¶ | χ | ¶ | χ |
| Y | : | § | χ | χ | ¶ | χ | χ |
