
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 06 : Partition
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Dualité tonale

#+TOC: headlines 1 local

** Couple tonal

La musique tonale se base essentiellement sur la dualité
dominante — tonique. Le *couple tonal* est un enchaînement qui met en
évidence cette dualité en faisant entendre les deux fonctions.
L’accord faisant fonction de tonique, de par son caractère conclusif,
se place après l’accord faisant fonction de dominante :

#+ATTR_HTML: :class plat
| dominante | — | tonique |

Le couple tonal est également caractérisé par la descente de quinte
qui mène du premier accord au second.


** Couple plagal

Le *couple plagal* est un peu le miroir du couple tonal : au lieu de
descendre d’une quinte pour aboutir à la tonique, l’enchaînement monte
d’une quinte. On doit donc partir de la quinte inférieure,
c’est-à-dire de la sous-dominante :

#+ATTR_HTML: :class plat
| sous-dominante | — | tonique |


** Dualité tonale mélodique

Le couple tonal peut servir à construire des mélodies qui se
répondent.

Ainsi, on peut écrire une mélodie originale dont l’ambitus s’étend
approximativement de la tonique à la dominante. La mélodie duale
s’étendra alors une quinte plus haut, de la dominante jusqu’à la
sus-tonique. Un retour de la mélodie duale à la mélodie originale sera
alors percue comme une descente de quinte.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| do - sol          | sol - ré      |

Si l’ambitus de la mélodie originale s’étend de la tonique à la
sous-dominante, la mélodie duale s’étendra de la dominante jusqu’à la
tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| do - fa           | sol - do      |

Enfin, on peut construire un cas intermédiaire où la mélodie originale
s’étend de la tonique à la dominante, tandis que la mélodie duale
s’étend de la dominante à la tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| do - sol          | sol - do      |

Nous verrons une application importante de ce cas particulier lorsque
nour parlerons des [[file:musica-08-clechant.org::#heading:mutation][mutations]].


** Dualité plagale mélodique

Le couple plagal peut servir à construire des mélodies qui se
répondent.

Ainsi, on peut écrire une mélodie originale dont l’ambitus s’étend
approximativement de la tonique à la dominante. La mélodie duale
s’étendra alors une quinte plus bas, de la sous-dominante jusqu’à la
tonique. Un retour de la mélodie duale à la mélodie originale sera
alors percue comme une montée de quinte.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| la - mi           | ré - la       |

Si l’ambitus de la mélodie originale s’étend de la tonique à la
sous-dominante, la mélodie duale s’étendra de la sous-dominante
jusqu’à la sous-tonique.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| la - ré           | ré - sol      |

Enfin, on peut construire un cas intermédiaire où la mélodie originale
s’étend de la tonique à la sous-dominante, tandis que la mélodie duale
s’étend de la sous-dominante à la tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| mélodie originale | mélodie duale |
| la - ré           | ré - la       |

Nous verrons une application importante de ce cas particulier lorsque
nour parlerons des [[file:musica-08-clechant.org::#heading:mutation][mutations]].


** Couple tonal pentatonique

Il s’agit d’un couple tonal où les accords utilisés comportent cinq
notes et sont construits en empilant des quintes. On élabore alors
deux petites mélodies :

  - la première utilise les notes d’un mode pentatonique établi sur la
    dominante
  - la seconde utilise les notes d’un mode pentatonique établi sur la
    tonique

Exemple de modes pentatoniques en /la mineur/ :

#+ATTR_HTML: :class plat
| dominante          | tonique            |
| mi sol la si ré mi | la do ré mi sol la |

Cette technique est notamment utilisée dans le blues et le jazz.


** Couple plagal pentatonique

Il s’agit d’un couple plagal où les accords utilisés comportent cinq
notes et sont construits en empilant des quintes. On élabore alors
deux petites mélodies :

  - la première utilise les notes d’un mode pentatonique établi sur la
    sous-dominante
  - la seconde utilise les notes d’un mode pentatonique établi sur la
    tonique

Exemple de modes pentatoniques en /la mineur/ :

#+ATTR_HTML: :class plat
| sous-dominante     | tonique            |
| ré fa sol la do ré | la do ré mi sol la |


* Tonalité secondaire

#+TOC: headlines 1 local

** Introduction

On peut renforcer le rôle du degré /X/ de la tonalité principale en le
considérant comme une *tonique secondaire*. La tonalité construite sur
ce degré /X/ s’appelle alors *tonalité secondaire*.

Une fonction tonale d’une tonalité secondaire est appelée *fonction
secondaire* et notée :

#+begin_center
Fonction de /X/
#+end_center


*** Degrés

Un accord construit sur le degré /Y/ de la tonique secondaire
correspondant au degré /X/ est noté :

#+begin_center
/Y/ de /X/
#+end_center


** Fonctions secondaires

#+TOC: headlines 1 local


*** Dominante secondaire

La *dominante secondaire* basée sur le degré /X/ de la tonalité
principale s’obtient en considérant /X/ comme une tonique secondaire
et en exprimant sa dominante :

#+begin_center
Dominante de /X/
#+end_center

Prenons par exemple /do majeur/ comme tonalité principale et
sélectionnons le degré 2, le /ré/, comme tonique secondaire. Si nous
décidons de lui appliquer le mode majeur, nous obtenons la tonalité
secondaire de /ré majeur/, qui est située une seconde majeure plus
haut que la principale. Le [[file:musica-01-monocorde.org::#heading:recapitulationTranspositionQuintes][tableau des transpositions]] nous donne alors
les altérations /fa^{#}/ et /do^{#}/. Une quinte plus haut que le
/ré/, nous avons le /la/ au degré 6, qui correspond à la dominante
secondaire :

#+ATTR_HTML: :class plat
| noms   | : | tonique principale | tonique secondaire | dominante secondaire |
| degrés | : |                  1 |                  2 |                    6 |

Nous choisissons un accord 5 de 2 pour la représenter :

#+begin_center
la do^{#} mi
#+end_center


*** Sous-dominante secondaire

La *sous-dominante secondaire* basée sur le degré /X/ de la gamme
courante s’obtient en considérant /X/ comme une tonique secondaire et
en exprimant sa sous-dominante :

#+begin_center
Sous-dominante de /X/
#+end_center


** Tonicisation

La tonicisation consiste à mettre en évidence le caractère de tonique
secondaire d’un degré /X/ en jouant le couple tonal secondaire :

#+ATTR_HTML: :class plat
| ( dominante | — | tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| dominante de /X/ | — | tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| dominante de /X/ | — | /X/ |

L’accord parfait sera :

  - majeur si on souhaite mettre en évidence une tonalité secondaire majeure
  - mineur si on souhaite mettre en évidence une tonalité secondaire mineure


*** Sous-dominante secondaire

Une alternative consiste à jouer le couple plagal secondaire :

#+ATTR_HTML: :class plat
| ( sous-dominante | — | tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| sous-dominante de /X/ | — | tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| sous-dominante de /X/ | — | /X/ |


** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: heading:dominanteAuxiliaire
:END:

La *dominante auxiliaire* est la dominante secondaire obtenue en
choisissant la dominante principale comme tonique secondaire. En
d’autres termes, la dominante auxiliaire correspond à la dominante de
la dominante, située deux quintes plus haut que la tonique principale
dans le cycle des quintes :

#+ATTR_HTML: :class plat
| noms         | : | tonique principale | dominante principale | dominante auxiliaire |
| abréviations | : | T                  | D                    | Daux                 |
| degrés       | : | 1                  | 5                    | 2                    |

La dominante auxiliaire est la fonction secondaire la plus utilisée
car elle permet de réaliser le couple tonal secondaire :

#+begin_center
Daux — D
#+end_center

qui renforce la dominante principale. Enfin, un accord du degré 2 peut
être disposé pour assurer une fonction tonale de sous-dominante ou de
dominante auxiliaire, reliant ainsi les deux fonctions.


** Dominante de la sous-dominante


*** Majeur

Nous allons à présent étudier la dominante de la sous-dominante.
Supposons par exemple que nous voulions renforcer le rôle de la
sous-dominante de /do majeur/, c’est-à-dire du /fa/. Notre accord doit
donc s’intégrer à la tonalité de /fa majeur/, qui possède un /si^b/
comme altération  :

#+begin_center
fa sol la si^b do ré mi fa
#+end_center

La dominante de cette gamme étant le /do/, la première idée est
d’utiliser la triade :

#+begin_center
do mi sol
#+end_center

mais cet accord ne met pas en évidence l’altération /si^b/ et ne se
différencie donc pas d’un accord parfait de tonique de /do majeur/. On
utilisera donc plutôt un accord d’au minimum quatre notes :

#+begin_center
do mi sol si^b
#+end_center


*** Mineur

En mineur, les modifications sont un peu plus compliquées. Plaçons
nous dans la gamme de /la mineur harmonique/, et construisons la
dominante de la sous-dominante. La sous-dominante étant le /ré/, on
doit intégrer cet accord dans la gamme de /ré mineur harmonique/.
Comme nous sommes une quinte plus bas que le /la/, un /si^b/ apparaît,
auquel on doit ajouter la sensible inférieure /do^{#}/ du mineur
harmonique :

#+begin_center
ré mi fa sol la si^b do^{#} ré
#+end_center

La dominante de cette gamme étant le /la/, on utilisera donc :

#+begin_center
la do^{#} mi
#+end_center

ou :

#+begin_center
la do^{#} mi sol
#+end_center

Si on souhaite mettre l’altération /si^b/ en évidence, on utilisera
plutôt l’accord de cinq notes :

#+begin_center
la do^{#} mi sol si^b
#+end_center


** Sensibles


*** Sensibles secondaires

Une note située à une distance d’un demi-ton d’une tonique secondaire
crée une attraction mélodique vers cette dernière.

Une *sensible secondaire supérieure* est un degré situé juste
au-dessus d’une tonique secondaire, à un demi-ton de celle-ci.

Une *sensible secondaire inférieure* est un degré situé juste
en-dessous d’une tonique secondaire, à un demi-ton de celle-ci.


*** Sensibles auxiliaires

Une note située à une distance d’un demi-ton de la dominante crée une
attraction mélodique vers cette dernière.

La dominante correspondant au degré 5, les notes qui l’entourent sont
situées aux degrés 4 et 6.

Lorsque le degré 4 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire inférieure*.

Lorsque le degré 6 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire supérieure*.


*** Tableau récapitulatif

| Degrés | Noms                           | Abréviations |
|--------+--------------------------------+--------------|
|      2 | sensible supérieure            | Ssup         |
|      7 | sensible inférieure            | Sinf         |
|      6 | sensible auxiliaire supérieure | SauxSup      |
|      4 | sensible auxiliaire inférieure | SauxInf      |


** Polarisation secondaire

On parle de *polarisation secondaire* lorsqu’un ensemble d’accords
consécutifs remplissent des fonctions secondaires et mettent ainsi en
évidence l’existence d’une tonalité secondaire.

On choisit souvent une note tonale de la gamme principale comme
tonique de la tonalité secondaire. Placer la tonique secondaire sur la
tonique principale revient à identifier les deux gammes et n’apporte
aucun éclairage neuf. La dominante et la sous-dominante sont donc les
choix les plus courants de tonique secondaire.


* Sémantique

#+TOC: headlines 1 local

** Introduction

La fonction tonale d’un accord peut correspondre au degré :

  - de la fondamentale
  - de la basse
  - du soprano
  - d’une éventuelle note redoublée

Un même accord peut donc assurer différentes fonctions tonales,
suivant qu’une ou l’autre de ses notes est mise en évidence.

Inversément, de nombreux accords peuvent jouer le rôle d’une même
fonction tonale : il suffit de placer la note souhaitée en évidence.
Ce procédé permet de choisir au mieux accords et dispositions afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.


*** Suppression

Parfois, la fondamentale est supprimée mais correspond malgré tout à
la fonction tonale de l’accord. On parle alors de *fonction
implicite*.

/Remarque/ : ce raisonnement scabreux vise à considérer l’enchaînement
des degrés 7 - 1 comme une suite de fonctions dominante - tonique. Je
vous le livre ici car il figure dans la théorie harmonique
conventionnelle, mais je n’y souscris pas. Il me semble bien plus
naturel de considérer que l’enchaînement 7 - 1 prend sa source dans la
[[file:musica-04-clavier.org::#heading:cadenceIonienneTroisVoix][cadence ionienne à trois voix]]. Les mouvements contraires qu’elle
contient amènent élégamment la tonique, ce qui justifie sa place parmi
les piliers de l’harmonie tonale.


*** Pédale

Si une pédale est présente, c’est elle qui assure la fonction tonale
pendant toute la durée de son règne. Suivant les cas, on parle de
pédale de tonique, de dominante, ou de sous-dominante.

Idem pour les accords pédale.


*** Accords ornementaux mélodiques

Les accords ornementaux mélodiques n’ont pas de fonction tonale
propre. On considère qu’ils remplissent la même fonction tonale que le
premier accord stratégique qui précède ou qui suit, suivant le
contexte.


** Synonymes

#+TOC: headlines 1 local

*** Introduction

Deux accords distincts remplissant une même fonction tonale sont dit
*synonymes*.


*** Recherche d’accords synonymes

Nous allons considérer un exemple simple afin de bien comprendre le
procédé permettant de découvrir des accords synonymes. Nous
choisissons la note /do/ comme tonique et nous voulons découvrir les
accords pouvant remplir la fonction de dominante. La dominante étant
le /sol/, cette note devra donc pouvoir être mise en évidence. Le
choix le plus évident est un accord du degré 5 avec le /sol/ comme
fondamentale, mais il en existe d’autres.

On peut parcourir le cycle des tierces pour découvrir les autres
accords à base de tierces incluant un /sol/. Pour les triades, cela
nous donne :

  - /sol/ si ré
  - mi /sol/ si
  - do mi /sol/

On voit que les fondamentales de ces accords, /sol/, /mi/ et /do/,
descendent le cycle des tierces.

Il ne nous reste plus qu’à mettre en évidence le /sol/ en le plaçant à
la basse, au soprano ou en le doublant. Nous choissons ici la dernière
option, ce qui nous donne :

  - /sol/ si ré /sol/
  - /sol/ mi /sol/ si
  - /sol/ do mi /sol/


*** Sans fondamentale

Nous pouvons aussi considérer qu’un accord de degré 7 :

#+begin_center
si ré fa =...=
#+end_center

est un accord de degré 5 privé de sa fondamentale :

#+begin_center
(sol) si ré fa =...=
#+end_center

et remplit implicitement une fonction de dominante.


*** Synonymes usuels

Étant donné une note tonale située sur le degré /X/, les synonymes
les plus utilisés sont :

  - les accords du degré /X/
  - les accords dont la fondamentale est située une tierce plus bas que le degré /X/
  - les accords dont la fondamentale est située une quinte plus bas que le degré /X/

En effet, tous ces accords contiennent la note du degré /X/, ce qui
permet de mettre la note tonale en évidence. On ajoute à cela les
accords situés à la tierce supérieure, considérés comme des degrés /X/
sans fondamentale.

Le tableau suivant nous donne les degrés des accords synonymes :

|     quinte |     tierce | degré |     tierce |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
|          4 |          6 |     1 |          3 |
|          7 |          2 |     4 |          6 |
|          1 |          3 |     5 |          7 |


Exemple en /do majeur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| fa         | la         | do    | mi         |
| si         | ré         | fa    | la         |
| do         | mi         | sol   | si         |

Exemple en /la mineur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| ré         | fa         | la    | do         |
| sol        | si         | ré    | fa         |
| la         | do         | mi    | sol        |


*** Les plus courants

Les possibilités les plus couramment employées sont rassemblées dans
ce tableau :

| Fonctions      | Degrés | Exemple      | Exemple      |
|                |        | en do majeur | en la mineur |
|----------------+--------+--------------+--------------|
| tonique        |      1 | do           | la           |
|                |      6 | la           | fa           |
|                |      3 | mi           | do           |
| sous-dominante |      4 | fa           | ré           |
|                |      2 | ré           | si           |
|                |      6 | la           | fa           |
| dominante      |      5 | sol          | mi           |
|                |      3 | mi           | do           |
|                |      7 | si           | sol          |


** Lien sémantique

Lorsqu’une modification de la disposition d’un accord /A/ permet de
rendre sa fonction tonale identique à celle d’un accord /B/, on dit
qu’il existe un *lien sémantique* entre les accords /A/ et /B/.

Par exemple, en /do majeur/, l’accord :

#+begin_center
do mi sol
#+end_center

exerce une fonction de tonique. Si nous plaçons le /sol/ à la basse et
que nous le doublons :

#+begin_center
sol do mi sol
#+end_center

il exerce alors une fonction de dominante. On met ainsi en évidence un
lien sémantique avec l’accord du degré 5 :

#+begin_center
sol si ré sol
#+end_center

qui exerce la même fonction.


*** Synonymes

Si les accords /A/ et /B/ sont unis par un lien sémantique, on peut
réarranger /A/, ou du moins réinterpréter sa fonction tonale, pour
qu’il soit synonyme de /B/.


* Cycle tonal

#+TOC: headlines 1 local

** Introduction

Le *cycle tonal* est une suite d’accords dont les fondamentales
descendent le cycle des quintes, mais en annulant ou ajoutant des
altérations pour que les notes obtenues restent dans la tonalité. Il
part du degré 1 et parcourt tous les autres degrés jusqu’à revenir à
la tonique.

Considérons par exemple la tonalité de /la mineur/. Le cycle des
quintes descendantes s’écrit :

#+begin_center
la ré sol do fa si^b mi^b la^b
#+end_center

Les bémols /si^b/, /mi^b/ et /la^b/ ne font pas partie de la tonalité
et sont donc annulés pour revenir aux notes naturelles /si/, /mi/ et
/la/. On obtient ainsi le cycle :

#+begin_center
la ré sol do fa si mi la
#+end_center

ce qui correspond aux degrés :

#+ATTR_HTML: :class plat
| notes  | : | la | ré | sol | do | fa | si | mi | la |
| degrés | : |  1 |  4 |   7 |  3 |  6 |  2 |  5 | 1  |

Écrit en terme de degrés, le cycle tonal est applicable à n’importe
quelle tonalité. C’est donc cette forme que nous retiendrons :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 3 | 6 | 2 | 5 | 1 |

C’est ce cycle, répété en boucle, qui sert de fondation à la musique
tonale. Naturellement, de nombreuses variations de ce modèle se
succèdent afin d’en rompre la monotonie. Si les techniques permettant
de produire ces variations peuvent nous mener à des enchaînements
parfois très éloignés du cycle d’origine, elles respectent néanmoins
certains principes :

  - il existe un lien entre
    + les accords originaux et les modifications
    + le nouvel accord et son environnement
  - ce lien peut être
    + accord synonyme
    + lien sémantique
    + fonction secondaire
    + lien polyphonique
    + enharmonie
  - l’accord final de chaque cycle fait en général fonction de tonique
    ou de dominante

Le cycle tonal permet d’expliquer des enchaînements courants ou d’en
découvrir de nouveaux, mais n’oublions pas qu’il ne s’agit que d’un
d’outil optionnel, à utiliser lorsqu’on le juge pertinent.


*** Quinte diminuée

Reprenons notre exemple en /la mineur/. Si toutes les quintes étaient
justes, nous traverserions le cycle complet des douze notes
diatoniques et altérées :

#+begin_center
la ré sol do fa si^b mi^b la^b ré^b sol^b [do^b = si] mi la
#+end_center

Au moins une de ces quintes doit être altérée afin de rester dans la
gamme heptatonique de /la mineur/. Dans notre exemple, l’annulation
des bémols produit l’apparition de la quinte diminuée descendante
/fa — si/.


** Suppression des doublons

Afin de simplifier la structure musicale, les accords intervenant en
double peuvent naturellement être réduits à un seul exemplaire.
Exemple :

#+ATTR_HTML: :class plat
| =...= | 5 | *1* | *1* | 4 | =...= | —> | =...= | 5 | *1* | 4 | =...= |


** Substitution

Cette opération consiste à remplacer un accord du cycle par un autre.
On veille toutefois à ce que l’accord original et son remplaçant
présentent certaines caractéristiques communes. Voici les principaux
mécanismes de substitution :

  - substitution par un accord synonyme à l’accord remplacé
  - substitution par un accord qui possède un lien sémantique avec
    l’accord remplacé
  - substitution par une fonction secondaire transformant le degré
    suivant en tonique secondaire
  - substitution polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants
  - substitution enharmonique : le nouvel accord est enharmonique à
    l’accord remplacé


** Insertion

Cette opération consiste à insérer un nouvel accord entre deux accords
du cycle. On veille toutefois à ce que l’accord inséré présente
certaines caractéristiques communes avec au moins un des accords
environnants. Les techniques d’insertion sont similaires à celles
utilisées pour la substitution :

  - insertion d’un accord synonyme renforçant une fonction tonale
    environnante
  - insertion d’un accord possédant un lien sémantique avec un des
    accords environnants
  - insertion d’une fonction secondaire transformant le degré
    suivant en tonique secondaire
  - insertion polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants
  - insertion par enharmonie : le nouvel accord est enharmonique au
    précédent ou au suivent


** Déviation

Cette opération consiste à dévier de trajectoire en créant un
raccourci dans le cycle tonal. On veille toutefois à ce que l’accord
de départ ait un lien avec l’accord d’arrivée :

  - déviation vers un accord d’arrivée synonyme à celui de départ
  - déviation vers un accord d’arrivée qui possède un lien sémantique
    avec l’accord de départ
  - déviation polyphonique : l’accord de départ possède un lien polyphonique
    avec l’accord d’arrivée
  - déviation enharmonique : les accords de départ et d’arrivée sont
    enharmoniques


*** Raccourci

Le *raccourci* est une déviation partant de n’importe quel accord du
cycle vers une fonction de dominante, éventuellement suivie par une
fonction de tonique.


*** Déviation enharmonique

À titre d’exemple de déviation enharmonique, plaçons-nous en /la
mineur/. L’accord de dominante sans fondamentale :

#+begin_center
sol^{#} si ré fa
#+end_center

est enharmonique à :

#+begin_center
la^b si ré fa
#+end_center

lui-même renversement de :

#+begin_center
si ré fa la^b
#+end_center

Ce dernier accord étant du degré 2, on peut créer un court-circuit
entre les degrés 7 et 2. Le cycle devient :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 2 | 5 | 1 |


** Figures de style

On peut imaginer d’autres types de modifications à apporter au cycle
tonal, en s’inspirant des [[file:litera-02-styleau.org][figures de style]] littéraires par exemple.


** Interprétation & réalisation

#+TOC: headlines 1 local

*** Introduction

Il existe de nombreuses interprétations du cycle tonal en terme de
fonctions, et chacune de ces interprétations peut être réalisées par
différentes suites d’accords. Nous disposons donc d’un système très
prolifique.


*** Degré 7 comme dominante

Voici un exemple d’interprétation du cycle tonal :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | T | T | Daux | D | T |

Le degré 7 y est considéré comme une dominante sans fondamentale et
les degrés 3 et 6 comme des accords de tonique. L’astuce est que nous
allons à présent oublier les degrés du cycle pour se concentrer sur
les fonctions :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |

Nous pouvons décider de réaliser ces fonctions par la suite
d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |
| 1 |  4 | 5 | 1 | 6 |    2 | 5 | 1 |

pour autant que chacun d’entre-eux mette en évidence la note tonale
correspondante, cela va de soi. Mais il existe d’autres possibilités
pour représenter cette suite de fonctions. Par exemple :

#+ATTR_HTML: :class plat
| 1 | 4 | 5 | 6 | 3 | 2 | 5 | 1 |

ou :

#+ATTR_HTML: :class plat
| 1 | 2 | 5 | 6 | 1 | 4 | 5 | 1 |


*** Degré 3 comme dominante

Si nous considérons que le degré 3 représente une dominante, nous
pouvons interpréter le cycle tonal de la façon suivante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | D | T | Daux | D | T |

qui peut par exemple se représenter par la suite d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | D | T | Daux | D | T |
| 1 |  4 | 7 | 5 | 6 |    2 | 5 | 1 |


*** Degrés 6 et 2 comme sous-dominante

Si nous considérons que les degrés 6 et 2 représentent une
sous-dominante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 |  6 |  2 | 5 | 1 |
| T | SD | D | T | SD | SD | D | T |

nous obtenons par exemple :

#+ATTR_HTML: :class plat
| T | SD | D | T | SD | SD | D | T |
| 1 |  2 | 5 | 1 |  6 |  4 | 5 | 1 |


*** Suites fréquentes

Nous constatons que les suites de fonctions :

#+ATTR_HTML: :class plat
| T | SD   | D | T |

et :

#+ATTR_HTML: :class plat
| T | Daux | D | T |

sont très fréquentes.


**** Anatole

Parmi les suites d’accords courantes provenant des innombrables
variations du cycle tonal, citons l’ *anatole* :

#+ATTR_HTML: :class plat
| 6 | 2 | 5 | 1 |


* Cycle plagal

Le *cycle plagal* est une suite d’accords dont les fondamentales
montent le cycle des quintes :

#+ATTR_HTML: :class plat
| 1 | 5 | 2 | 6 | 3 | 7 | 4 | 1 |

Les modifications qu’on peut lui apporter sont analogues à celles du
cycle tonal.

Si le cycle plagel est rarement utilisé seul, il peut être utile d’en
insérer occasionnellement un fragment dans le cycle tonal.


* Dynamique

#+TOC: headlines 1 local

** Introduction

La dynamique musicale est basée sur l’alternance de *tension* et de
*détente*, la détente servant de *résolution* à la tension initiale :

#+ATTR_HTML: :class plat
| tension | — | résolution |

Un objet musical est qualifié de :

  - *stable* s’il ne cause aucune tension

  - *instable* s’il provoque une tension


** Attraction

La tension d’un objet musical instable est souvent due à une
*attraction* vers un objet proche considéré comme plus stable. La
résolution s’effectue alors lorsque l’objet instable répond à cette
attraction en évoluant vers l’objet stable.


** Consonance & dissonance


*** Intervalles harmoniques

Un intervalle harmonique :

  - consonant est stable.
  - dissonant est instable.


*** Accords

Un accord :

  - consonant est stable.
  - dissonant est instable.


*** Généralisation

Par analogie avec les intervalles harmoniques :

  - un objet musical stable est qualifié de *consonant*
  - un objet musical instable est qualifié de *dissonant*

Synonymes :

  - un objet musical consonant est aussi appelé *consonance*
  - un objet musical dissonant est aussi appelé *dissonance*


** Préparation

Une tension peut être précédée d’une phase de *préparation*, phase qui
permet d’introduire la future dissonance dans un contexte où elle est
consonante. On a donc la structure générique :

#+ATTR_HTML: :class plat
| préparation | — | tension | — | résolution |

où la phase de préparation est optionnelle.

La dissonance qui passe par une phase de préparation est dite
*préparée*.

Lorsque la phase de préparation est omise, on dit que la dissonance
est *attaquée*.


** Résolution

Lorsqu’une dissonance se résout indifféremment suivant plusieurs
processus différents, on dit alors que sa résolution est *libre*.

Lorsqu’une dissonance se résout préférentiellement via un processus
bien défini, correspondant à un effet de détente maximal, on dit alors
que cette résolution est *régulière* ou *ordinaire*. On parle
également de *mouvement obligé*.

Dans le cas où une dissonance censée adopter un mouvement obligé se
résout autrement, on parle de résolution *irrégulière* ou
*exceptionnelle*.

Enfin, lorsqu’une dissonance ne se résout pas, on peut conduire la
musique vers une autre idée, ou vers une tension encore plus forte.


*** Absolue ou relative

La *résolution absolue* fait suivre un objet dissonant par un objet
consonant.

La *résolution relative* fait suivre un objet consonant par un objet
qui est encore plus consonant que le premier.


** Cycle

On a le cycle générique :

#+begin_center
(préparation)  —  tension  —  résolution  — (préparation)  —  tension  — résolution  —  =...=
#+end_center

Remarquons que la phase de résolution peut servir de préparation à la
tension suivante, formant ainsi le cycle :

#+begin_center
(préparation) —  tension  —  (résolution & préparation)  —  tension  — (résolution & préparation)  —  =...=
#+end_center


** Nouveauté

Les phases dynamiques peuvent servir à introduire de la nouveauté dans
le discours musical :

  - nouveau thème
  - modification du rythme
  - entrée d’une voix
  - changement de tonalité
  - etc

La nouveauté est présentée comme :

  - cause de la résolution
    + elle apparaît alors pendant la phase de tension
  - conséquence de la résolution


* Dynamique mélodique

#+TOC: headlines 1 local

** Sensibles

Une sensible induit une tension mélodique vers la note tonale la plus
proche : tonique ou dominante. Les sensibles sont donc considérées
comme des notes dissonantes.

Voici les résolutions attendues :

  - la sensible inférieure se résout sur la tonique en montant d’un demi-ton
  - la sensible supérieure se résout sur la tonique en descendant d’un demi-ton
  - la sensible auxiliaire inférieure se résout sur la dominante en montant d’un demi-ton
  - la sensible auxiliaire supérieure se résout sur la dominante en descendant d’un demi-ton


** Continuité

Un intervalle conjoint ne suscite pas de tension.

Un intervalle disjoint entre deux notes /x/ et /y/ suscite une tension
relative qui se résout en jouant les notes intermédiaires entre /x/ et /y/.


** Hauteur

Une note plus aiguë est relativement plus tendue qu’une note plus
grave.

Une note plus grave est relativement plus détendue qu’une note plus
aiguë.


*** Direction

Une mélodie qui monte vers l’aigu génère une tension relative.

Une mélodie qui descend vers le grave produit une détente relative.


*** Extrêmes

Une mélodie dont les pics (maxima locaux) montent vers l’aigu génère
une tension relative.

Une mélodie dont les creux (minima locaux) descendent vers le grave
produit une détente relative.


** Accentuation

Une mélodie est généralement accentuée par :

  - la durée : notes de durée plus longue
  - tout ce qui tranche d’une pente rectigligne et continue
    + saut : mouvement disjoint dans une mélodie majoritairement conjointe
    + virage : changement de direction, de pente
    + extrême : pic ou creux local


*** Notes essentielles

Les accents mélodiques sont généralement disposés sur des notes
essentielles ou sur des ornements harmoniques.


*** Discontinuités

Il est rare d’observer un mouvement disjoint ne faisant intervenir
aucune note de l’accord.


*** Indépendance

Les accents mélodiques des différentes voix de la polyphonie sont
indépendants. On peut disposer ces accents à des instants différents
sur chacune des voix, ceci afin de les mettre tour à tour en évidence.
On peut aussi s’arranger pour que les accents mélodiques soient
synchronisés afin de donner à l’ensemble un effet de convergence et
d’apothéose très convaincant.


* Dynamique des accords

#+TOC: headlines 1 local

** Accords parfaits

Les accords parfaits sont consonants. Pour plus de détails, voir la
section sur la [[file:musica-03-luth.org::#heading:consonanceAccordsParfaits][consonance des accords parfaits]].


** Quinte diminuée

L’accord de quinte diminuée est dissonant, voir la section sur la
[[file:musica-03-luth.org::#heading:consonanceAccordsParfaits][consonance des accords parfaits]].


** Quinte augmentée

Les notes d’un accord de quinte augmentée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte augmentée

avec la fondamentale de l’accord. La quinte augmentée étant un
intervalle harmonique dissonant, l’accord de *quinte augmentée* est
*dissonant*.


** Septième de dominante

Les accords de septième de dominante sont dissonants.
Pour plus de détails, voir la section sur
la [[file:musica-03-luth.org::#heading:dissonanceSeptiemeDomminante][dissonance de la septième de dominante]].


** Autres accords de quatre notes ou plus

Un accord de quatre notes ou plus contient au moins une note qui va
former un intervalle harmonique de septième (mineure, majeure ou
diminuée) avec la fondamentale. Tous ces accords sont donc
*dissonants*.


** Accords à base de quintes

Les accords à base de quintes contiennent au moins un intervalle
dissonant : seconde, septième, neuvième, etc. Ce sont donc des accords
dissonants.


** Sensibles

La présence d’une sensible dans un accord provoque une tension qui
pousse cet accord à se résoudre sur un autre accord.

Une sensible, ou une sensible auxiliaire :

  - rend instable un accord qui ne comporte pourtant aucune dissonance constitutive
  - augmente l’instabilité d’un accord dissonant

#+begin_center
⁂
#+end_center

Les accords suivants contiennent une ou plusieurs tensions
mélodiques :

  - accords de dominante
  - accords de dominante auxiliaire avec sensible(s) auxiliaire(s)
  - accords napolitains
  - =...=


** Tableau récapitulatif

| Stabilité              | Accords               |
|------------------------+-----------------------|
| consonants             | parfait majeur        |
|                        | parfait mineur        |
| équilibre dynamique    | septième de dominante |
| dissonants             | tous les autres       |

La présence de sensible(s) rend l’accord dissonant ou augmente son
instabilité.


* Dynamique des dissonances

#+TOC: headlines 1 local

** Note dissonante

Une note dissonante est une note qui provoque l’apparition d’une
dissonance. Il peut s’agir :

  - d’une note ornementale dissonante
  - d’une note constitutive d’un accord dissonant

Chaque dissonance :

  - peut être précédée d’une phase de préparation
  - est suivie d’une phase de résolution


*** Ornement

Une note ornementale peut être :

  - consonante
    + l’accord en cours est consonant
    + la note ornementale en fait parfie
  - dissonante, sinon
    + note essentielle dissonante
    + note étrangère dissonante


*** Constitutive

Sans note de 7e, un accord de septième de dominante se réduit à un
accord parfait et ne présente plus de dissonance. On considère donc
que c’est la note de 7e qui est la note dissonante de l’accord.

Ce raisonnement nous permet de trouver la ou les notes responsables de
la dissonance dans la plupart des accords dissonants. Le tableau
suivant rassemble les principales notes dissonantes et leurs accords
respectifs :

| Accord                          | Notes                 |
|                                 | dissonantes           |
|---------------------------------+-----------------------|
| septième de dominante           | 7e                    |
| neuvième de dominante majeure   | 7e, 9e                |
| neuvième de dominante mineure   | 7e, 9e                |
|---------------------------------+-----------------------|
| septième majeure                | 7e                    |
| septième mineure                | 7e                    |
| septième harmonique             | 7e                    |
|---------------------------------+-----------------------|
| quinte augmentée                | 5te                   |
|---------------------------------+-----------------------|
| quinte diminuée                 | 5te                   |
| septième et quinte diminuée     | 5te, 7e               |
| septième diminuée               | 5te, 7e               |
|---------------------------------+-----------------------|

Parfois, la présence d’une sensible gènère une tension, que l’accord
soit dissonant ou non :

| Accord                          | Sensible(s) |
|---------------------------------+-------------|
| accords de dominante auxiliaire | auxiliaires |
| napolitain                      | supérieure  |


** Préparation

La tension due à la dissonance peut être précédée d’un accord stable
de *préparation* :

  - qui contient les futures notes dissonantes, on a alors
    *préparation par intégration*

  - qui permet d’amener les notes dissonantes par mouvement conjoint
    variable, on a alors *préparation conjointe*

  - qui permet d’amener les notes dissonantes par un ou plusieurs
    mouvements polyphoniques élégants, on a alors *préparation
    polyphonique*

/Remarque/ : la préparation par intégration peut être considérée comme
une préparation par mouvement conjoint constant.


** Résolution

#+TOC: headlines 1 local

*** Introduction

La résolution d’une note dissonante dans un accord stable peut se
réaliser suivant différents schémas :

  - *résolution par intégration* : la note instable est inclue dans
    l’accord stable suivant et devient donc naturellement stable lors
    du changement d’accord

  - *résolution conjointe* : la note instable réalise un mouvement
    conjoint variable vers une note inclue dans l’accord stable

  - *résolution polyphonique* : les notes instables réalisent un ou
    plusieurs mouvements polyphoniques élégants vers des notes inclues
    dans l’accord stable


*** Voix

Une dissonance se trouve habituellement sur la même voix que sa
résolution.

On peut toutefois procéder à un échange de voix simultanée à une
résolution ordinaire, produisant ainsi un effet inattendu.


*** Résolution irrégulière

En cas de résolution irrégulière, il est préférable de quitter la
dissonance par mouvement conjoint.


** Doublure

#+TOC: headlines 1 local

*** Introduction

Une dissonance est aisément détectable par l’oreille, et l’est encore
plus si une note intervenant dans la préparation ou la résolution est
doublée.

On privilégie donc les mouvements contraire et oblique dans les phases
de préparation et de résolution d’une dissonance.


*** Préparation

Si une note de préparation est doublée, on quitte de préférence cette
note et sa doublure par mouvement contraire ou oblique.


*** Dissonance

La dissonance et sa doublure sont de préférence :

  - amenées par mouvement contraire ou oblique
  - quittées par mouvement contraire

On évite généralement de doubler une dissonance, sauf effet
particulier souhaité.


*** Résolution

Si la note de résolution est doublée, on amène de préférence cette
note et sa doublure par mouvement contraire.

L’arrivée sur résolution par mouvement oblique est déconseillée.


** Généralisation

Il arrive que l’on souhaite imiter le processus appliqué aux notes
dissonantes, mais dans le cas d’une note consonante. Cette note peut
alors être :

  - précédée d’une phase de préparation (optionnel)
  - suivie d’une phase de résolution

Ces deux phases peuvent se dérouler :

  - par intégration dans l’accord concerné (mouvement constant)
  - par mouvement conjoint variable
  - par mouvement(s) polyphonique(s) élégant(s)

et sont donc en tout point similaires à la préparation et à la
résolution de dissonance.


*** Ornements

Généralement, la définition d’un ornement demande que la note soit
préparée et/ou résolue, qu’elle soit consonante ou dissonante.


* Dispositions des accords

#+TOC: headlines 1 local

** Accords parfaits


*** État fondamental

L'état fondamental est le plus affirmé, il agit comme un pilier de la
tonalité.

On double :

  - le plus souvent la fondamentale ou une note tonale
  - parfois la 3ce, en guise de variation

Si on souhaite supprimer une note :

  - on évite de supprimer la fondamentale
  - si on souhaite éviter l’ambiguité entre accord parfait majeur ou mineur
    + on ne supprime pas la note de 3ce majeure ou mineure
    + on supprime plutôt la 5te
  - l’accord produira un effet de simplicité si on supprime la 3ce
    + à réserver aux instants de convergence, comme en fin de phrase

#+begin_center
⁂
#+end_center

L’accord parfait du degré 7 remplit généralement la même fonction
tonale qu’une 7e de dominante sans fondamentale.


*** Premier renversement

Le premier renversement est moins appuyé que l’état fondamental.

On double en général une note tonale.

Si un degré fort est situé une tierce au-dessus de la fondamentale, la
basse est généralement doublée et l’accord peut assurer la fonction
tonale correspondante.

De part leur forte similitude, les accords de sixte peuvent aussi
ornementer l’accord parfait à l’état fondamental situé une tierce plus
haut. On compte en effet deux notes communes, et même trois avec la
doublure. Exemples en /do majeur/ :

| degrés | fonction | premier       | état fondamental d’un accord |
|        |          | renversement  | situé une tierce au-dessus   |
|--------+----------+---------------+------------------------------|
| 2 & 4  | SD       | fa la ré fa   | fa la do fa                  |
| 6 & 1  | T        | do mi la do   | do mi sol do                 |
| 3 & 5  | D        | sol si mi sol | sol si ré sol                |


#+begin_center
⁂
#+end_center

En mineur, l’accord de sus-tonique est soit :

  - au premier renversement pour éviter la quinte diminuée avec la basse
  - présenté avec un degré 2 abaissé pour produire un accord napolitain
  - sous la forme d’un accord napolitain au premier renversement


*** Second renversement

Le second renversement sert souvent d’accord ornemental. On s’arrange
alors pour que la basse fasse note commune avec les accords
environnants, contrastant alors avec les mouvements mélodiques
ornementaux des autres voix.

On double en général la basse, pour équilibrer les mouvements
constants et variables. Dans un quatuor, on se retrouve alors avec
deux voix constantes et deux voix variables.

Exemple de second renversement avec broderies au soprano et au ténor :

#+ATTR_HTML: :class plat
| S | : | si  | do  | si  |
| A | : | sol | sol | sol |
| T | : | ré  | mi  | ré  |
| B | : | sol | sol | sol |

Exemple de second renversement avec note de passage au ténor :

#+ATTR_HTML: :class plat
| S | : | sol | la | mi  |
| A | : | do  | do | do  |
| T | : | mi  | fa | sol |
| B | : | do  | do | do  |

Exemple avec une broderie au ténor et une note de passage au soprano :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | do  |
| A | : | sol | sol | sol |
| T | : | do  | si  | do  |
| B | : | do  | ré  | mi  |


** Septième de dominante

La note de 7e peut servir d’ornement harmonique ou mélodique.

Suppression :

  - on évite de supprimer la 3ce, car c’est la sensible inférieure
  - si on supprime la 7e, on se retrouve avec un accord parfait
  - on supprime le plus souvent la fondamentale ou la 5te


*** Sans fondamentale
:PROPERTIES:
:CUSTOM_ID: heading:dispositionSeptièmeDominanteSansFondamentale
:END:

La septième de dominante sans fondamentale est au minimum au premier
renversement, avec la 3ce à la basse.

Cette disposition est moins dissonante que l’accord complet, car
l’intervalle de septième mineure n’est plus présent.

Le second renversement est préféré au premier, car il évite aussi les
intervalles dissonants avec la basse, ce qui rend sa sonorité plus
douce.

Par exemple, en /do majeur/, la septième de dominante sans
fondamentale s’écrit :

#+begin_center
(sol) si ré fa —> si ré fa
#+end_center

ce qui produit un intervalle de quinte diminuée entre la note de 7e
/fa/ et la basse. Par contre, au second renversement :

#+begin_center
(sol) si ré fa —> ré fa si
#+end_center

on obtient des intervalles consonants avec la basse :

  - basse — fa : tierce mineure
  - basse — si : sixte majeure

L’intervalle dissonant du triton /fa — si/ ne fait alors pas
intervenir la basse.

Sous cette forme, l’accord de septième de dominante sans fondamentale
est présent dans la
[[file:musica-04-clavier.org::#heading:cadenceIonienneTroisVoix][cadence ionienne à trois voix]].


** Septième d’espèce

Il est préférable de préparer la note de 7e.

Idéalement, la durée de la préparation est au moins égale à la durée
de la note de 7e.


** Accords à base de quintes

Suppressions :

  - on évite de supprimer les notes qui contiennent la tension
    + 2de
    + 4te
    + etc


** Remarques générales


*** Continuité

Les accords proches au niveau tonal supportent mieux les mouvements
disjoints lors de leurs enchaînements. Exemples :

  - couple tonal
  - couple plagal
  - voisins dans le cycle tonal

Les accords dont le lien tonal est plus lointain demanderont plus de
mouvements conjoints pour assurer la liaison.


*** Renversements

Les accords renversés ont généralement un caractère tonal moins
affirmé que leurs homologues à l’état fondamental. Cette remarque est
d’autant plus vraie pour les accords de trois notes. Afin de ne pas
rendre leur fonction tonale encore plus floue, on évite autant que
possible de supprimer une note d’une triade renversée.

Par contre, les accords renversés de quatre notes ou plus, et en
particulier la 7e et la 9e de dominante, peuvent s’employer sans
fondamentale ou sans quinte.


* Dynamique des enchaînements

#+TOC: headlines 1 local

** Quarte et sixte

L’accord de quarte et sixte est un accord consonant, mais il permet
une résolution relative vers un accord encore plus stable, à savoir
l’accord parfait à l’état fondamental :

  - note de sixte —> note de quinte
  - note de quarte —>  note de tierce

Exemple de résolution d’une 4te & 6te de fondamentale /fa/ :

#+ATTR_HTML: :class plat
| S | : | fa | mi  |
| A | : | la | sol |
| B | : | do | do  |

L’accord de 4te & 6te peut également être utilisé comme
[[file:musica-04-clavier.org::#heading:accordBroderie][accord broderie]].


** Couple tonal

#+TOC: headlines 1 local

*** Introduction

La sensible inférieure évolue généralement vers la tonique. On
généralise cette propriété en utilisant l’attraction produite par les
intervalles de seconde mineure de la tonalité.

En /do majeur/ et /la mineur/, avec les accords :

|           | Dominante           | Tonique   |
|-----------+---------------------+-----------|
| do majeur | sol si ré (fa) (la) | do mi sol |
| la mineur | mi sol si (ré) (fa) | la do mi  |

nous avons :

|             | do majeur   | la mineur     | commentaire         |
|-------------+-------------+---------------+---------------------|
| 3ce —> 1ale | si —> do    | sol —> la     |                     |
|             |             | sol^{#} —> la | sensible inférieure |
|-------------+-------------+---------------+---------------------|
| 5te —> 3ce  | ré —> mi    | si —> do      |                     |
|             | ré —> mi^b  |               | 3ce altérée         |
|-------------+-------------+---------------+---------------------|
| 7e —> 3ce   | fa —> mi    | ré —> do      |                     |
|             |             | ré —> do^{#}  | 3ce picarde         |
|-------------+-------------+---------------+---------------------|
| 9e —> 5te   | la —> sol   | fa —> mi      |                     |
|             | la^b —> sol |               | 9e altérée          |

L’emploi simultané des évolutions /5te —> 3ce/ et /7e —> 3ce/ produit
une doublure de la 3ce de l’accord de tonique, ce qui n’est pas
toujours souhaitable. Si on souhaite l’éviter, on peut :

  - ne pas utiliser de note de 7e
    + accord parfait de dominante
  - dévier un des deux mouvements vers une autre note
    + 5te —> 1ale
    + 7e —> 5te

En termes de degrés de la gamme, on a :

#+ATTR_HTML: :class plat
| sensible inférieure | —> | tonique   |
| sus-tonique         | —> | médiante  |
| sous-dominante      | —> | médiante  |
| sus-dominante       | —> | dominante |

Exemple typique en /do majeur/, avec l’évolution /5te —> 3ce/ :

#+ATTR_HTML: :class plat
| S | : | la  | sol |
| M | : | si  | do  |
| A | : | fa  | sol |
| T | : | ré  | mi  |
| B | : | sol | do  |

et avec l’évolution /7e —> 3ce/ :

#+ATTR_HTML: :class plat
| S | : | la  | sol |
| M | : | si  | do  |
| A | : | fa  | mi  |
| T | : | ré  | do  |
| B | : | sol | do  |


*** Préparation

Exemple de préparation d’une note de 7e en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | do   | ré   | do   |
| B | : | fa   | sol  | do   |


*** Résolution irrégulière

On peut dévier la sensible inférieure de son mouvement attendu vers la
tonique, et la rediriger vers la 5te de l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /si/ | /sol/ |
| A | : | fa   | mi    |
| T | : | ré   | do    |
| B | : | sol  | do    |

La 9e de dominante peut se résoudre à l’intérieur d’un autre accord de
dominante. Voici par exemple une résolution d’une 9e de dominante sans
fondamentale vers une 7e de dominante complète, toujours en /do
majeur/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | fa    |
| T | : | ré   | ré    |
| B | : | si   | si    |


** Dominante auxiliaire

Les accords de dominante auxiliaire peuvent subir des altérations qui
les rapprochent des notes tonales. Ces notes altérées se résolvent
alors naturellement sur les degrés correspondant :

| Résolution     | do majeur     | la mineur     |
|----------------+---------------+---------------|
| vers dominante | fa^{#} —> sol | ré^{#} —> mi  |
|                | la^b —> sol   | fa —> mi      |
| vers tonique   | si —> do      | sol^{#} —> la |
|                | ré^b —> do    | si^b —> la    |


** Septièmes d’espèces

Les septièmes d’espèces sont utilisées pour renforcer la résolution
vers l’accord suivant.

Le choix le plus évident consiste à imiter le couple tonal en
enchaînant avec un accord situé une quinte plus bas.

Dans cet exemple, qui enchaine un accord de /la/ avec un accord de
/ré/, on voit que la 7e, le /sol/, se résout en descendant vers le
/fa/ de l’accord suivant :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /fa/ |
| A | : | mi    | ré   |
| T | : | /do/  | /ré/ |
| B | : | la    | ré   |

On note aussi que la 3ce du premier accord (le /do/ au ténor) évolue
vers la fondamentale du deuxième accord (le /ré/).

Exemple avec un accord de préparation contenant la 7e :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /sol/ | /fa/ |
| A | : | mi    | mi    | ré   |
| T | : | si    | /do/  | /ré/ |
| B | : | sol   | la    | ré   |


** Accords à base de quintes

Un accord à base de quintes peut se transformer en accord parfait sans
3ce, avec doublure de la fondamentale :

#+ATTR_HTML: :class plat
| S | : | la   | la   |
| A | : | mi   | mi   |
| B | : | /si/ | /la/ |

Il peut aussi devenir un accord parfait au premier renversement :

#+ATTR_HTML: :class plat
| S | : | la   | la   |
| A | : | mi   | mi   |
| B | : | /si/ | /do/ |

Il peut aussi se transformer en accord parfait au second
renversement :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | mi   | mi    |
| B | : | si   | si    |

Il peut aussi devenir un accord parfait sans 3ce au second
renversement :

#+ATTR_HTML: :class plat
| S | : | /la/ | /si/ |
| A | : | mi   | mi   |
| B | : | si   | si   |

Enfin, il peut évoluer vers un accord de 7e incomplet :

#+ATTR_HTML: :class plat
| S | : | fa   | fa   |
| A | : | /do/ | /si/ |
| B | : | sol  | sol  |


* Dynamique des ornements

#+TOC: headlines 1 local

** Accentuation

Les ornements harmoniques sont généralement placés sur temps fort ou
partie forte de temps.

Les ornements mélodiques sont généralement placés sur temps faible ou
partie faible de temps.


** Pédale

Lorsqu’une *pédale* est présente, elle est en général alternativement
dissonante et consonante par rapport aux accords qui se succèdent sur
les autres voix.

Une pédale est souvent préparée en s’intégrant à un premier accord et
en perdurant après sa disparition. Le dernier accord qui se superpose
à une pédale lui est en général également consonant.

Autrement dit, une pédale est généralement préparée et résolue par
intégration.


** Retard

#+TOC: headlines 1 local

*** Préparation

Par définition, un retard est préparé par intégration. Idéalement, la
durée de la préparation est au moins égale à la durée du retard.


*** Phase active

Pour ne pas gâcher l’effet de surprise, on préfère ne pas faire
entendre simultanément le retard et sa résolution, sauf si une des
conditions suivantes est satisfaite :

  - la résolution est placée sous le retard
    + par exemple, si la résolution est placée à la basse
  - la résolution est discrète, voir les techniques de
    [[file:musica-04-clavier.org::#heading:camouflage][camouflage]]
  - on peut placer retard & résolution dans une disposition élégante

Le retard est généralement sur un temps plus accentué que sa
résolution :

| Retard       | Résolution   |
|--------------+--------------|
| temps fort   | temps médian |
| temps fort   | temps faible |
| temps médian | temps faible |


*** Résolution

Un retard dissonant se résout généralement en évoluant par mouvement
conjoint variable vers une note du nouvel accord. Suivant le sens du
mouvement, on distingue :

  - le *retard supérieur* qui se résout en descendant
    + c’est le plus courant, car l’effet de descente mélodique
      accentue la détente harmonique
  - le *retard inférieur* qui se résout en montant

Par exemple, dans l’enchaînement suivant, le /ré/ au soprano est un
retard supérieur qui se résout en descendant vers le /do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /do/ |
| A | : | sol  | mi   | mi   |
| T | : | sol  | sol  | sol  |
| B | : | si   | do   | do   |

Autre exemple où le /fa/ est un retard inférieur qui se résout en
montant vers le /sol/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /sol/ |
| A | : | do   | si   | si    |
| T | : | la   | ré   | ré    |
| B | : | fa   | sol  | sol   |


** Anticipation

Une anticipation dissonante se résout par intégration dans l’accord
suivant.

Par exemple, dans l’enchaînement suivant, le /mi/ au soprano est une
ancicipation :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


** Appogiature

Par définition, l’appogiature est attaquée.

Une appogiature dissonante se résout le plus souvent par mouvement
conjoint variable.


* Dynamique du rythme

#+TOC: headlines 1 local

** Introduction

Le rythmes les plus stables sont les *rythmes réguliers* :

  - *rapides*, avec au moins une note par temps
  - *lents*, avec de longues notes continues

Tous les autres rythmes correspondent à des tensions qui peuvent se
résoudre sur l’une ou l’autre de ces configurations. Il va de soi que
les rythmes lents sont plutôt réservés à la fin d’une phrase et les
rythmes rapides au coeur d’un mouvement.


** Accentuation

Un temps fort peut être accentué par :

  - une intensité plus forte de la note qui l’entame
  - un accent mélodique


** Mesures

Une mesure irrégulière constitue une tension par rapport à une mesure
régulière proche.


** Fluidité

Un rythme sec produit une tension par rapport à un rythme fluide qui
lui est proche. Par exemple, la suite :

#+ATTR_HTML: :class plat
| C cs C | cs N N |

produira une tension puis une détente, et la suite :

#+ATTR_HTML: :class plat
| C cs N | C cs N | =...= |

un cycle de tension et de détente.

** Syncopes

Le schéma générique d’une syncope applique la structure générique de
tension et résolution. En voici un exemple :

  - *préparation* : rythme régulier, à raison d’une note par temps

  - *tension* : on gomme la première note de la mesure suivante en la
    remplaçant par la prolongation de la note précédente

  - *résolution* : la mélodie reprend le rythme régulier précédent, à
    raison d’une note par temps

Toutes les variations partant de ce cas d’école sont bien entendu
possibles. La phase de préparation est bien entendu optionnelle.

Voici des exemples de réalisation où la mesure compte deux temps d’une
noire chacun :

|         | Préparation | Tension     | Résolution |
|---------+-------------+-------------+------------|
| syncope | N N         | N N‿N N     | N N        |
| syncopé | N N         | N N‿N N‿N N | N N        |


*** Contraste

Il arrive souvent qu’on mette en relief une syncope en introduisant un
contraste entre la voix syncopée et une voix sans syncope qui assure
la régularité rythmique. Dans ce cas, la tension découle naturellement
du contraste.


** Contretemps

On peut considérer qu’une syncope est un rythme fluide et que le
contretemps est le rythme sec associé. Par conséquent, le contretemps
offre une tension rythmique encore plus importante que celle de la
syncope. On peut imaginer un prototype de tension — relaxation :

  - rythme régulier de préparation, une note par temps
  - tension : syncope
  - tension accrue : contretemps associé
  - légère détente : retour à la syncope
  - détente finale : retour au rythme régulier

chaque étape étant optionnelle.


* Distance tonale

#+TOC: headlines 1 local

** Introduction

La *distance tonale* entre deux accords est le nombre d’étapes
nécessaires pour aller du premier accord au deuxième en suivant le
cycle tonal. Cette distance dépend de l’intervalle formé par les
fondamentales :

| Nombre d’étapes | Intervalle |
|-----------------+------------|
|               1 | 5te        |
|               2 | 2de M      |
|               3 | 3ce m      |
|               4 | 3ce M      |
|               5 | 2de m      |
|               6 | 4te aug    |

On retrouve ainsi un tableau similaire à ceux des
[[file:musica-01-monocorde.org::#heading:recapitulationTranspositionQuintes][transpositions par combinaisons de quintes]].

Comme l’enchaînement reste équivalent si la fondamentale monte ou
descend d’une octave, les renversements de ces intervalles
correspondent à la même distance tonale et on a en définitive :

| Étapes | Intervalles |         |
|--------+-------------+---------|
|      1 | 5te         | 4te     |
|      2 | 2de M       | 7e m    |
|      3 | 3ce m       | 6te M   |
|      4 | 3ce M       | 6te m   |
|      5 | 2de m       | 7e M    |
|      6 | 4te aug     | 5te dim |


** Proximité tonale

Deux accords sont dit *tonalement proches* lorsque la distance tonale
qui les sépare est faible.

On retient généralement comme proches les accords séparés par une ou
deux étapes dans le cycle des quintes. Leurs fondamentales forment
alors :

  1. une quinte
  2. une seconde majeure

Deux accords sont dits *tonalement éloignés* s’ils ne sont pas proches.


** Enchaînements forts & faibles

Les enchaînements d’accords tonalement proches sont appelés
*enchaînements forts*.

Les enchaînements d’accords tonalement éloignés sont appelés
*enchaînements faibles*.

Un enchaînement est donc :

  - fort si les fondamentales procèdent par
    + quinte
    + seconde majeure
  - faible si les fondamentales procèdent par
    + tierce


* Boucles d’accords

#+TOC: headlines 1 local

** Introduction

Les boucles d’accords sont des cycles d’accords qui ne respectent pas
toujours la progression d’un cycle tonal ou plagal.

Ils sont beaucoup utilisés en musique pop.


** Boucle de quatre accords

Inspiré de la théorie de Philip Tagg.

  1. pôle principal
     - généralisation de la tonique
  2. sortant
     - prépare l’installation du pôle secondaire
  3. pôle secondaire
     - généralisation de la dominante
  4. rentrant
     - prépare l’installation du pôle principal
  5. retour au pôle principal


** Environnement

Inspiré de [[https://www.youtube.com/watch?v=JvyChMVvqnQ&t=401s][My Brand New Take On Four Chords Loop, by 12tone]].

Les enchaînements forts ou faibles entre un accord et ses voisins nous
donnent quatre configurations possibles :

| Catégorie    | Enchaînement avec |                |
| d’accord     | accord précédent  | accord suivant |
|--------------+-------------------+----------------|
| isolé        | faible            | faible         |
| continuation | fort              | fort           |
| départ       | faible            | fort           |
| destination  | fort              | faible         |

Un accord :

  - isolé sert de pause temporaire
  - de départ entame une série d’accord qui mène à une destination
  - de continuation prolonge une série entamée
  - de destination termine une série d’accord par une pause


* Stratification

#+TOC: headlines 1 local

** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique
tonalité, on parle de *musique tonale*. Il existe donc à tout moment
un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.


** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre tonalité, distincte
de celles des autres groupes, on parle de musique polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.


** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.


** Polyrythmie

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de *polymétrie* ou de *rythmes polymétriques*.


**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| V | : | § | χ | ¶ | χ | ¶ | χ |
| W | : | § | χ | χ | ¶ | χ | χ |
