
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 03 : Clavier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Dynamique

#+TOC: headlines 1 local


** Introduction

La dynamique musicale est basée sur l’alternance de *tension* et de
*détente*, la détente servant de *résolution* à la tension initiale :

#+ATTR_HTML: :class plat
| Tension | — | Résolution |

Un objet musical est qualifié de :

  - *stable* ou *consonant* s’il ne cause aucune tension

  - *instable* ou *dissonant* s’il provoque une tension

Un objet musical consonant est aussi appelé *consonance*.

Un objet musical dissonant est aussi appelé *dissonance*.


** Préparation

Une tension peut être précédée d’une phase de *préparation*, phase qui
permet d’introduire la future dissonance dans un contexte où elle est
consonante. On a donc la structure générique :

#+ATTR_HTML: :class plat
| Préparation | — | Tension | — | Résolution |

où la phase de préparation est optionnelle.


** Résolution

Lorsqu’une dissonance se résout indifféremment suivant plusieurs
processus différents, on dit alors que sa résolution est *libre*.

Lorsqu’une dissonance se résout préférentiellement via un processus
bien défini, correspondant à un effet de détente maximal, on dit alors
que cette résolution est *régulière* ou *ordinaire*. On parle
également de *mouvement obligé*.

Dans le cas où une dissonance censée adopter un mouvement obligé se
résout autrement, on parle de résolution *irrégulière* ou
*exceptionnelle*.

Enfin, lorsqu’une dissonance ne se résout pas, on conduit généralement
la musique vers une tension encore plus forte.


*** Absolue ou relative

La *résolution absolue* fait suivre un objet dissonant par un objet
consonant.

La *résolution relative* fait suivre un objet consonant par un objet
qui est encore plus consonant que le premier.


*** Nouveauté

La dissonance peut être utilisée comme *introduction* à un nouvel
objet musical, la résolution amenant alors la *nouveauté* que l’on
souhaite présenter :

#+ATTR_HTML: :class plat
| Introduction | = | Tension    |
| Nouveauté    | = | Résolution |


* Dynamique de la mélodie

#+TOC: headlines 1 local


** Hauteur

Une note plus aiguë est plus tendue qu’une note plus grave.

Une note plus grave est plus détendue qu’une note plus aiguë.


** Intervalles

Un intervalle conjoint ne suscite pas de tension.

Un intervalle disjoint entre deux notes /x/ et /y/
suscite une tension qui se résout en jouant les notes intermédiaires
entre /x/ et /y/.

** Direction

Une mélodie qui monte vers l’aigu génère une tension.

Une mélodie qui descend vers le grave produit une détente.


** Extrêmes

Une mélodie dont les pics (maxima locaux) montent vers l’aigu génère
une tension.

Une mélodie dont les creux (minima locaux) descendent vers le grave
produit une détente.


* Dynamique des sensibles

#+TOC: headlines 1 local


** Introduction

Une sensible est située à distance d’un demi-ton de la tonique de la
gamme. On a donc envie d’entendre la tonique juste après avoir entendu
la sensible, ce qui génère une tension. Les sensibles sont donc des
notes dissonantes.

Voici les résolutions attendues :

  - la sensible inférieure se résout sur la tonique en montant d’un demi-ton

  - la sensible supérieure se résout sur la tonique en descendant d’un demi-ton


** Sensibles secondaires

Une sensible secondaire est située à distance d’un demi-ton de la
dominante de la gamme. On a donc envie d’entendre la dominante juste
après avoir entendu la sensible secondaire, ce qui génère une *tension
mélodique*. Les sensibles secondaires sont donc des notes dissonantes.

Voici les résolutions attendues :

  - la sensible secondaire inférieure se résout sur la dominante en montant d’un demi-ton

  - la sensible secondaire supérieure se résout sur la dominante en descendant d’un demi-ton


* Dynamique des intervalles harmoniques

#+TOC: headlines 1 local


** Introduction

Les intervalles harmoniques peuvent être classés suivant leur
caractère consonant ou dissonant. Un intervalle *consonant* donne une
impression de douceur, d’équilibre, de plénitude. Par contre, un
intervalle *dissonant* est dans un état de tension qui est appellé à
se résoudre sur un intervalle consonant proche, appelé intervalle de
*résolution*.

La classification des intervalles harmoniques est basée sur la série
des harmoniques naturelles, série commençant par les intervalles
considérés comme consonants en théorie classique. Analysons par
exemple le début d’une série d’harmoniques naturelles de fondamentale
/do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Les premiers intervalles qui apparaissent sont :

| Intervalle harmonique | Note I | Note II |
|-----------------------+--------+---------|
| Unisson               |      1 |       1 |
| Octave                |      1 |       2 |
| Quinte                |      2 |       3 |
| Quarte                |      3 |       4 |
| Tierce majeure        |      4 |       5 |
| Tierce mineure        |      5 |       6 |
| Sixte majeure         |      3 |       5 |
| Sixte mineure         |      5 |       8 |
| Septième mineure      |      4 |       7 |
| Seconde majeure       |      8 |       9 |
| Quarte augmentée      |      8 |      11 |

La classification usuelle des intervalles considère les intervalles
comme consonants jusqu’aux sixtes, et dissonants ensuite. Les
intervalles augmentés et diminués sont également considérés comme
dissonants.


** Consonances

Le tableau suivant donne la liste des intervalles consonants :

| Consonances                | Intervalles harmoniques |
|----------------------------+-------------------------|
| Consonances parfaites      | Unisson                 |
|                            | Octave                  |
|                            | Quinte                  |
| Consonances intermédiaires | Quarte                  |
| Consonances imparfaites    | Tierce majeure          |
|                            | Tierce mineure          |
|                            | Sixte majeure           |
|                            | Sixte mineure           |

/Remarque/ : le terme « consonance imparfaite » ne signifie pas qu’une
tierce ou une sixte sonne moins bien qu’une quinte ou qu’une octave,
mais simplement que les notes des consonances parfaites se ressemblent
plus que celles des consonances imparfaites.


** Dissonances

Le tableau suivant donne la liste des intervalles dissonants :

| Dissonances                | Intervalles harmoniques |
|----------------------------+-------------------------|
| Dissonances imparfaites    | Septième mineure        |
|                            | Seconde majeure         |
| Dissonances intermédiaires | Quarte augmentée        |
| Dissonances parfaites      | Septième majeure        |
|                            | Seconde mineure         |
| Autres                     | Intervalles diminués    |
|                            | Intervalles augmentés   |


* Dynamique des accords

#+TOC: headlines 1 local


** Introduction

Dans le cadre d’un accord :

  - une *note consonante* est une note constitutive qui forme un
    intervalle harmonique consonant avec la fondamentale

  - une *note dissonante* est une note constitutive qui forme un
    intervalle harmonique dissonant avec la fondamentale

Une note dissonante est également appelée *dissonance constitutive*.

Les accords sont également classés suivant leur caractère stable ou
instable :

  - un *accord consonant* est un accord qui ne contient que des notes
    consonantes

  - un *accord dissonant* est un accord qui contient au moins une note
    dissonante


** Classification


*** Accords parfaits

Les notes d’un accord parfait majeur forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte

avec la fondamentale de l’accord. L’ *accord parfait majeur* est donc
un accord *consonant*.

#+BEGIN_CENTER
⁂
#+END_CENTER

Les notes d’un accord parfait mineur forment des intervalles :

  - d’unisson
  - de tierce mineure
  - de quinte

avec la fondamentale de l’accord. L’ *accord parfait mineur* est donc
un accord *consonant*.

#+BEGIN_CENTER
⁂
#+END_CENTER


**** Premier renversement

Les notes d’un accord parfait majeur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce mineure
  - de sixte mineure

avec la fondamentale de l’accord. L’accord parfait majeur au premier
renversement est donc un accord consonant.

Les notes d’un accord parfait mineur au premier renversement forment
des intervalles :

  - d’unisson
  - de tierce majeure
  - de sixte majeure

avec la fondamentale de l’accord. L’accord parfait mineur au premier
renversement est donc un accord consonant.


**** Second renversement

Les notes d’un accord parfait majeur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte majeure

avec la fondamentale de l’accord. L’accord parfait majeur au second
renversement est donc un accord consonant.

Les notes d’un accord parfait mineur au second renversement forment
des intervalles :

  - d’unisson
  - de quarte
  - de sixte mineure

avec la fondamentale de l’accord. L’accord parfait mineur au second
renversement est donc un accord consonant.


*** Autres triades

Les notes d’un accord de quinte augmentée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte augmentée

avec la fondamentale de l’accord. La quinte augmentée étant un
intervalle harmonique dissonant, l’accord de *quinte augmentée* est
également *dissonant*.

#+BEGIN_CENTER
⁂
#+END_CENTER

Les notes d’un accord de quinte diminuée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte diminuée

avec la fondamentale de l’accord. La quinte diminuée étant un
intervalle harmonique dissonant, l’accord de *quinte diminuée* est
également *dissonant*.


*** Septième de dominante

Les notes d’un accord de septième de dominante forment des
intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte
  - de septième mineure

avec la fondamentale de l’accord. La septième mineure étant un
intervalle harmonique dissonant, l’accord de *septième de dominante*
est également *dissonant*.


*** Autres accords de quatre notes ou plus

Un accord de quatre notes ou plus contient au moins une note qui va
former un intervalle harmonique de septième (mineure, majeure ou
diminuée) avec la fondamentale. Tous ces accords sont donc
*dissonants*.


** Harmoniques naturelles

Nous allons à présent établir une classification alternative des
accords en nous basant cette fois sur la série des harmoniques
naturelles.


*** Accord parfait majeur

Considérons par exemple le début d’une série d’harmoniques naturelles
de fondamentale /do/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

Si nous nous arrêtons à la note 6, nous avons :

#+BEGIN_CENTER
do   do   sol   do   mi   sol
#+END_CENTER

Hors doublures, nous obtenons un ensemble de trois notes :

#+BEGIN_CENTER
do   mi   sol
#+END_CENTER

qui n’est rien d’autre qu’un accord parfait majeur.

L’ *accord parfait majeur* est donc un accord consonant, autant du
point de ses intervalles harmoniques internes que de la série des
harmoniques naturelles.


*** Septième de dominante

Considérons par exemple le début d’une série d’harmoniques naturelles
de fondamentale /sol/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | sol | sol | ré | sol | si | ré | fa | sol | la | si | do^{#} | ré | =...= |
| /Numéros/ | : |   1 |   2 |  3 |   4 |  5 |  6 |  7 |   8 |  9 | 10 |     11 | 12 | =...= |

Si nous nous arrêtons à la note 7, nous avons :

#+BEGIN_CENTER
sol   sol   ré   sol   si   ré   fa
#+END_CENTER

Hors doublures, nous obtenons un ensemble de quatre notes :

#+BEGIN_CENTER
sol   si   ré   fa
#+END_CENTER

L’accord de septième de dominante se trouve donc dans une situation
paradoxale. Comme tous les accords de quatres notes à base de tierces,
sa note de septième forme une dissonance avec sa fondamentale. D’un
autre coté, nous voyons apparaître un accord de *septième de
dominante* parmi les premières harmoniques naturelles. Cet accord
figure donc parmi les plus *équilibrés* des accords dissonants. Il y a
donc là une forme d’ *équilibre dynamique*, ce qui explique son rôle
important.


** Sensible

La présence d’une sensible ou d’une sensible secondaire dans un accord
provoque une tension qui pousse cet accord à se résoudre sur un autre
accord.

Une sensible, ou une sensible secondaire :

  - rend instable un accord qui ne comporte pourtant aucune dissonance
    constitutive

  - augmente l’instabilité d’un accord dissonant

#+BEGIN_CENTER
⁂
#+END_CENTER

Les accords suivants contiennent une ou plusieurs tensions
mélodiques :

  - accords de dominante seconde avec sensible(s) secondaire(s)
  - accords napolitains
  - =...=


** Tableau récapitulatif

| Stabilité                         | Accords               |
|-----------------------------------+-----------------------|
| Stables, Consonants               | Parfait majeur        |
|                                   | Parfait mineur        |
| Équilibre dynamique               | Septième de dominante |
| Instables, Dissonants, Équilibrés | Tous les autres       |


* Dynamique du rythme

#+TOC: headlines 1 local


** Introduction

Le rythmes les plus stables sont les *rythmes réguliers* :

  - *rapides*, avec au moins une note par temps

  - *lents*, avec de longues notes continues

Tous les autres rythmes correspondent à des tensions qui peuvent se
résoudre sur l’une ou l’autre de ces configurations. Il va de soi que
les rythmes lents sont plutôt réservés à la fin d’une phrase et les
rythmes rapides au coeur d’un mouvement.


** Mesures

Une mesure irrégulière constitue une tension par rapport à une mesure
régulière proche.


** Fluidité

Un rythme sec produit une tension par rapport à un rythme fluide qui
lui est proche. Par exemple, la suite :

#+ATTR_HTML: :class plat
| C cs C | cs N N |

produira une tension puis une détente, et la suite :

#+ATTR_HTML: :class plat
| C cs N | C cs N | =...= |

un cycle de tension et de détente.


** Syncopes

Le schéma générique d’une syncope applique la structure générique de
tension et résolution. En voici un exemple :

  - *Préparation* : rythme régulier, à raison d’une note par temps

  - *Tension* : on gomme la première note de la mesure suivante en la
    remplaçant par la prolongation de la note précédente

  - *Résolution* : la mélodie reprend le rythme régulier précédent, à
    raison d’une note par temps

Toutes les variations partant de ce cas d’école sont bien entendu
possibles. La phase de préparation est bien entendu optionnelle.

Voici des exemples de réalisation où la mesure compte deux temps d’une
noire chacun :

|         | Préparation | Tension     | Résolution |
|---------+-------------+-------------+------------|
| Syncope | N N         | N N‿N N     | N N        |
| Syncopé | N N         | N N‿N N‿N N | N N        |


** Contretemps

On peut considérer qu’une syncope est un rythme fluide et que le
contretemps est le rythme sec associé. Par conséquent, le contretemps
offre une tension rythmique encore plus importante que celle de la
syncope. On peut imaginer un prototype de tension — relaxation :

  - Rythme régulier de préparation, une note par temps secondaire

  - Tension : syncope

  - Tension accrue : contretemps associé

  - Légère détente : retour à la syncope

  - Détente finale : retour au rythme régulier

chaque étape étant optionnelle.
