
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 04 : Partition
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Tonalité

#+TOC: headlines 1 local

** Introduction

L’association d’une tonique et d’un mode est appelée *tonalité*.

En effet, une fois la tonique et le mode connu, on dispose d’assez
d’informations pour construire toute la gamme.

On parlera par exemple de la tonalité de :

  - do ionien
  - la éolien
  - etc


** Notes tonales

Les *notes tonales* sont les notes les plus importantes de la gamme, à
savoir la tonique et les degrés qui l’entourent dans le cycle des
quintes :

#+ATTR_HTML: :class plat
| Noms   | : | Sous-dominante | ⟻ | 5te | ⟼ | Tonique | ⟻ | 5te | ⟼ | Dominante |
| Degrés | : |              4 | ⟻ | 5te | ⟼ |       1 | ⟻ | 5te | ⟼ |         5 |


*** Intervalles justes

Les notes tonales sont généralement séparées de la tonique par les
intervalles justes de la gamme :

| Note 1  | Note 2         | Intervalle      |
|         |                | à l’octave près |
|---------+----------------+-----------------|
| tonique | tonique        | unisson         |
| tonique | dominante      | quinte          |
| tonique | sous-dominante | quarte          |

Il existe toutefois quelques exceptions. Ainsi, la dominante de la
gamme de /si locrien/ forme un intervalle de quinte diminuée avec la
tonique, raison pour laquelle le mode locrien est peu utilisé.


** Accords

Considérons les accords de trois notes construits en prenant les notes
tonales comme fondamentales :

| Note tonale    | Degrés        | Exemple      |
|                | dans l’accord | tonique = do |
|----------------+---------------+--------------|
| tonique        | 1 3 5         | do mi sol    |
| dominante      | 5 7 2         | sol si ré    |
| sous-dominante | 4 6 1         | fa la do     |

On constate que l’on retrouve toutes les notes de la gamme.


** Hiérarchie des degrés

Les degrés 4, 1, 5 correspondant aux notes tonales sont appelés
*degrés forts*, ou encore *degrés tonaux*.

Les autres degrés sont appelés *degrés faibles*.


** Sensible

Une *sensible* est une note située à une distance d’un demi-ton de la
tonique, ce qui crée une attraction mélodique vers cette dernière.

La tonique correspondant au degré 1, les notes qui l’entourent sont
situées aux degrés 2 et 7.

Lorsque le degré 7 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible inférieure*.

Lorsque le degré 2 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible supérieure*.

Exemples :

  - si la tonique est un /do/, le /si/ sera une sensible inférieure

  - si la tonique est un /mi/, le /fa/ sera une sensible supérieure


* Fonctions tonales

#+TOC: headlines 1 local

** Introduction

Une *fonction tonale* est une fonction musicale réalisée à la fois par :

  - une note tonale
  - un accord mettant en évidence cette note tonale

La musique utilisant les fonctions tonales est appelée *musique tonale*.


** Tonique

En tant que note la plus importante de la gamme, la tonique assure
aussi la première fonction tonale.

La tonique est la fonction sur laquelle la musique effectue ses pauses
les plus importantes.

On l’appelle aussi *finale*, car c’est généralement elle qui marque la
fin d’une section musicale.


** Dominante

La musique tonale s’articule autour de la dualité qui existe entre la
tonique, fonction de repos, et la dominante, fonction dynamique autour
de laquelle la musique peut se développer. Il arrive également que la
musique effectue des pauses à la dominante, mais ce sont là des arrêts
nettement moins appuyés que ceux effectués sur la tonique.

La dominante est naturellement attirée par la tonique, et peut :

  - répondre à son appel, ce qui détent la musique
  - ne pas y répondre et repartir vers une autre idée

La dominante constitue donc la fonction tonale la plus importante avec
la tonique.


** Sous-dominante

La sous-dominante constitue la fonction tonale la plus importante
après la tonique et la dominante.


** Tableau récapitulatif

| Degrés | Fonctions            | Abréviations |
|--------+----------------------+--------------|
|      4 | Sous-dominante       | SD           |
|      1 | Tonique              | T            |
|      5 | Dominante            | D            |


* Modes majeur et mineur

#+TOC: headlines 1 local


** Introduction

Le tableau suivant regroupe les accords de trois notes générés par les
degrés des modes naturels. La lettre *M* signifie accord parfait
majeur et la lettre *m* accord parfait mineur. Le symbole *dim*
signifie ici accord de quinte diminuée :

| Modes      |     | Degrés |     |     |     |     |     |     |
|            |     | 4      | 1   | 5   | 2   | 6   | 3   | 7   |
|------------+-----+--------+-----+-----+-----+-----+-----+-----|
| Lydien     | fa  | dim    | M   | M   | M   | m   | m   | m   |
| Ionien     | do  | M      | M   | M   | m   | m   | m   | dim |
| Mixolydien | sol | M      | M   | m   | m   | m   | dim | M   |
| Dorien     | ré  | M      | m   | m   | m   | dim | M   | M   |
| Éolien     | la  | m      | m   | m   | dim | M   | M   | M   |
| Phrygien   | mi  | m      | m   | dim | M   | M   | M   | m   |
| Locrien    | si  | m      | dim | M   | M   | M   | m   | m   |

Parmi les modes naturels, les modes ionien et éolien sont les seuls à
présenter le même type d’accords sur les degrés forts 4, 1, 5. Le mode
ionien produit des accords parfaits majeurs, tandis que le mode éolien
produit des accords parfaits mineurs :

| Modes  | Degrés |   |   |
|        | 4      | 1 | 5 |
|--------+--------+---+---|
| Ionien | M      | M | M |
| Éolien | m      | m | m |

Pour cette raison :

  - le mode ionien est aussi appelé *mode majeur*
  - le mode éolien est aussi appelé *mode mineur*

Exemple de mode majeur avec la gamme de /do majeur/ :

#+begin_center
do ré mi fa sol la si do
#+end_center

Exemple de mode mineur avec la gamme de /la mineur/ :

#+begin_center
la si do ré mi fa sol la
#+end_center


** Adaptations du mineur

#+TOC: headlines 1 local

*** Mineur harmonique

Le mode majeur dispose d’une sensible inférieure. Par exemple,
en /do majeur/, la sensible inférieure est le /si/, à un demi-ton de
la tonique /do/. Cette propriété est intéressante car la sensible est
naturellement attirée par la tonique, ce qui permet de donner de la
dynamique à un déroulement musical.

En mode mineur par contre, le degré 7 est situé un ton entier sous la
tonique. La propriété d’attirance de la sensible vers la tonique n’est
donc pas présente. On peut toutefois y remédier en haussant la
sous-tonique d’un demi-ton, obtenant ainsi un mode dérivé, appelé
*mode mineur harmonique*. Par exemple, en /la mineur/, le /sol/ sera
haussé d’un demi-ton, donnant ainsi la gamme :

#+begin_center
la si do ré mi fa sol^{#} la
#+end_center

Dans la suite, le mode mineur par défaut sera généralement le mode
mineur harmonique.


*** Mineur ascendant et descendant

Le mode mineur harmonique sonne très bien, disposant à la fois de la
sonorité du mode mineur et de l’attirance de la sensible inférieure.
Cependant, l’écart de trois demi-tons entre les degrés 6 et 7 n’est
pas toujours souhaitable. Dans ce cas, on hausse le degré 6, obtenant
un mode appelé *mode mineur ascendant*. Exemple, le /la mineur
ascendant/ :

#+begin_center
la si do ré mi fa^{#} sol^{#} la
#+end_center

Par opposition, on appelle alors *mode mineur descendant* le mode
mineur naturel (le mode éolien). En pratique, les modes mineurs
(harmonique, ascendant et descendant) sont souvent mêlés, donnant
ainsi beaucoup de couleur et de souplesse à la musique. Enfin, le
degré 3 peut lui aussi être haussé d’un demi-ton, complétant ainsi le
caractère polymorphe du mode mineur, qui peut se rapprocher ou même se
confondre avec le mode majeur.


** Degrés & intervalles caractéristiques

Les modes majeur et mineur sont les modes les plus utilisés. On s’en
sert donc comme référence pour souligner les *degrés caractéristiques*
des autres modes. Ces degrés forment des *intervalles
caractéristiques* avec la tonique.


*** Autour du mode majeur

En partant de /do majeur/, les quintes voisines nous donnent les
gammes de /sol mixolydien/ et /fa lydien/.

Si nous transposons la gamme de /sol mixolydien/ vers la tonique /do/,
nous obtenons la gamme de /do mixolydien/ :

#+begin_center
do ré mi fa sol la /si^b/ do
#+end_center

La note caractéristique du mode mixolydien est donc le /si^b/,
septième degré formant un intervalle de septième mineure avec la
tonique.

Si nous transposons la gamme de /fa lydien/ vers la tonique /do/,
nous obtenons la gamme de /do lydien/ :

#+begin_center
do ré mi /fa^{#}/ sol la si do
#+end_center

La note caractéristique du mode lydien est donc le /fa^{#}/, quatrième
degré formant un intervalle de quarte augmentée avec la tonique.


*** Autour du mode mineur

En partant de /la mineur/, les quintes voisines nous donnent les
gammes de /mi phrygien/ et /ré dorien/.

Si nous transposons la gamme de /mi phrygien/ vers la tonique /la/,
nous obtenons la gamme de /la phrygien/ :

#+begin_center
la /si^b/ do ré mi fa sol la
#+end_center

La note caractéristique du mode phrygien est donc le /si^b/, deuxième
degré formant un intervalle de seconde mineure avec la tonique.

Si nous transposons la gamme de /ré dorien/ vers la tonique /la/, nous
obtenons la gamme de /la dorien/ :

#+begin_center
la si do ré mi /fa^{#}/ sol la
#+end_center

La note caractéristique du mode dorien est donc le /fa^{#}/, sixième
degré formant un intervalle de sixte majeure avec la tonique.

Nous n’avons pas encore exploré le mode locrien. Partons de la gamme
de /si locrien/ et transposons vers la tonique /la/, deux quintes plus
bas. Nous obtenons la gamme de /la locrien/ :

#+begin_center
la si^b do ré mi^b fa sol la
#+end_center

Les notes caractéristiques du mode locrien sont donc le /si^b/ et le
/la^b/, deuxième et cinquième degré formant des intervalles de seconde
mineure et quinte diminuée avec la tonique.


*** Récapitulation

| Modes           |           Degré | Intervalle      |
|                 | caractéristique | caractéristique |
|-----------------+-----------------+-----------------|
| Lydien          |               4 | 4te augmentée   |
| Ionien (Majeur) |                 | —               |
| Mixolydien      |               7 | 7e mineure      |
|-----------------+-----------------+-----------------|
| Dorien          |               6 | 6te majeure     |
| Éolien (Mineur) |                 | —               |
| Phrygien        |               2 | 2de mineure     |
|-----------------+-----------------+-----------------|
| Locrien         |               2 | 2de mineure     |
|                 |               5 | 5te diminuée    |


* Sémantique

#+TOC: headlines 1 local

** Introduction

La fonction tonale d’un accord peut correspondre au degré :

  - de la fondamentale
  - de la basse
  - du soprano
  - d’une éventuelle note redoublée

Un même accord peut donc assurer différentes fonctions tonales,
suivant qu’une ou l’autre de ses notes est mise en évidence.

Inversément, de nombreux accords peuvent jouer le rôle d’une même
fonction tonale : il suffit de placer la note souhaitée en évidence.
Ce procédé permet de choisir au mieux accords et dispositions afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.


*** Suppression

Parfois, la fondamentale est supprimée mais correspond malgré tout à
la fonction tonale de l’accord. On parle alors de *fonction
implicite*.


*** Pédale

Si une pédale est présente, c’est elle qui assure la fonction tonale
pendant toute la durée de son règne. Suivant les cas, on parle de
pédale de tonique, de dominante, ou de sous-dominante.

Idem pour les accords pédale.


*** Accords ornementaux mélodiques

Les accords ornementaux mélodiques n’ont pas de fonction tonale
propre. On considère qu’ils remplissent la même fonction tonale que le
premier accord stratégique qui précède ou qui suit, suivant le
contexte.


** Synonymes

#+TOC: headlines 1 local

*** Introduction

Deux accords distincts remplissant une même fonction tonale sont dit
*synonymes*.


*** Recherche d’accords synonymes

Nous allons considérer un exemple simple afin de bien comprendre le
procédé permettant de découvrir des accords synonymes. Nous
choisissons la note /do/ comme tonique et nous voulons découvrir les
accords pouvant remplir la fonction de dominante. La dominante étant
le /sol/, cette note devra donc pouvoir être mise en évidence. Le
choix le plus évident est un accord du degré 5 avec le /sol/ comme
fondamentale, mais il en existe d’autres.

On peut parcourir le cycle des tierces pour découvrir les autres
accords à base de tierces incluant un /sol/. Pour les triades, cela
nous donne :

  - /sol/ si ré
  - mi /sol/ si
  - do mi /sol/

On voit que les fondamentales de ces accords, /sol/, /mi/ et /do/,
descendent le cycle des tierces.

Il ne nous reste plus qu’à mettre en évidence le /sol/ en le plaçant à
la basse, au soprano ou en le doublant. Nous choissons ici la dernière
option, ce qui nous donne :

  - /sol/ si ré /sol/
  - /sol/ mi /sol/ si
  - /sol/ do mi /sol/


*** Sans fondamentale

Nous pouvons aussi considérer qu’un accord de degré 7 :

#+begin_center
si ré fa =...=
#+end_center

est un accord de degré 5 privé de sa fondamentale :

#+begin_center
(sol) si ré fa =...=
#+end_center

et remplit implicitement une fonction de dominante.


*** Synonymes usuels

Étant donné une note tonale située sur le degré /X/, les synonymes
les plus utilisés sont :

  - les accords du degré /X/
  - les accords dont la fondamentale est située une tierce plus bas que le degré /X/
  - les accords dont la fondamentale est située une quinte plus bas que le degré /X/

En effet, tous ces accords contiennent la note du degré /X/, ce qui
permet de mettre la note tonale en évidence. On ajoute à cela les
accords situés à la tierce supérieure, considérés comme des degrés /X/
sans fondamentale.

Le tableau suivant nous donne les degrés des accords synonymes :

|     quinte |     tierce | degré |     tierce |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
|          4 |          6 |     1 |          3 |
|          7 |          2 |     4 |          6 |
|          1 |          3 |     5 |          7 |


Exemple en /do majeur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| fa         | la         | do    | mi         |
| si         | ré         | fa    | la         |
| do         | mi         | sol   | si         |

Exemple en /la mineur/ :

| quinte     | tierce     | degré | tierce     |
| inférieure | inférieure | tonal | supérieure |
|------------+------------+-------+------------|
| ré         | fa         | la    | do         |
| sol        | si         | ré    | fa         |
| la         | do         | mi    | sol        |


*** Les plus courants

Les possibilités les plus couramment employées sont rassemblées dans
ce tableau :

| Fonctions      | Degrés | Exemple      | Exemple      |
|                |        | en do majeur | en la mineur |
|----------------+--------+--------------+--------------|
| Tonique        |      1 | do           | la           |
|                |      6 | la           | fa           |
|                |      3 | mi           | do           |
| Sous-dominante |      4 | fa           | ré           |
|                |      2 | ré           | si           |
|                |      6 | la           | fa           |
| Dominante      |      5 | sol          | mi           |
|                |      3 | mi           | do           |
|                |      7 | si           | sol          |


** Lien sémantique

Lorsqu’une modification de la disposition d’un accord /A/ permet de
rendre sa fonction tonale identique à celle d’un accord /B/, on dit
qu’il existe un *lien sémantique* entre les accords /A/ et /B/.

Par exemple, en /do majeur/, l’accord :

#+begin_center
do mi sol
#+end_center

exerce une fonction de tonique. Si nous plaçons le /sol/ à la basse et
que nous le doublons :

#+begin_center
sol do mi sol
#+end_center

il exerce alors une fonction de dominante. On met ainsi en évidence un
lien sémantique avec l’accord du degré 5 :

#+begin_center
sol si ré sol
#+end_center

qui exerce la même fonction.


*** Synonymes

Si les accords /A/ et /B/ sont unis par un lien sémantique, on peut
réarranger /A/, ou du moins réinterpréter sa fonction tonale, pour
qu’il soit synonyme de /B/.


* Couples

#+TOC: headlines 1 local

** Couple tonal

La musique tonale se base essentiellement sur la dualité
dominante — tonique. Le *couple tonal* est un enchaînement qui met en
évidence cette dualité en faisant entendre les deux fonctions.
L’accord faisant fonction de tonique, de par son caractère conclusif,
se place après l’accord faisant fonction de dominante :

#+ATTR_HTML: :class plat
| Dominante | — | Tonique |

Le couple tonal est également caractérisé par la descente de quinte
qui mène du premier accord au second.


** Couple plagal

Le *couple plagal* est un peu le miroir du couple tonal : au lieu de
descendre d’une quinte pour aboutir à la tonique, on monte d’une
quinte. On doit donc partir de la quinte inférieure, c’est-à-dire de
la sous-dominante :

#+ATTR_HTML: :class plat
| Sous-dominante | — | Tonique |


* Tonalité secondaire

#+TOC: headlines 1 local

** Introduction

On peut renforcer le rôle du degré /X/ de la tonalité principale en le
considérant comme une *tonique secondaire*. La tonalité construite sur
ce degré /X/ s’appelle alors *tonalité secondaire*.

Une fonction tonale d’une tonalité secondaire est appelée *fonction
secondaire* et notée :

#+begin_center
Fonction de /X/
#+end_center


*** Degrés

Un accord construit sur le degré /Y/ de la tonique secondaire
correspondant au degré /X/ est noté :

#+begin_center
/Y/ de /X/
#+end_center


** Fonctions secondaires

#+TOC: headlines 1 local


*** Dominante secondaire

La *dominante secondaire* basée sur le degré /X/ de la tonalité
principale s’obtient en considérant /X/ comme une tonique secondaire
et en exprimant sa dominante :

#+begin_center
Dominante de /X/
#+end_center

Prenons par exemple /do majeur/ comme tonalité principale et
sélectionnons le degré 2, le /ré/, comme tonique secondaire. Si nous
décidons de lui appliquer le mode majeur, nous obtenons la tonalité
secondaire de /ré majeur/, qui est située une seconde majeure plus
haut que la principale. Le [[file:musica-01-monocorde.org::#section:recapitulationTranspositionQuintes][tableau des transpositions]] nous donne alors
les altérations /fa^{#}/ et /do^{#}/. Une quinte plus haut que le
/ré/, nous avons le /la/ au degré 6, qui correspond à la dominante
secondaire :

#+ATTR_HTML: :class plat
| Noms   | : | tonique principale | tonique secondaire | dominante secondaire |
| Degrés | : |                  1 |                  2 |                    6 |

Nous choisissons un accord 5 de 2 pour la représenter :

#+begin_center
la do^{#} mi
#+end_center


*** Sous-dominante secondaire

La *sous-dominante secondaire* basée sur le degré /X/ de la gamme
courante s’obtient en considérant /X/ comme une tonique secondaire et
en exprimant sa sous-dominante :

#+begin_center
Sous-dominante de /X/
#+end_center


** Tonicisation

La tonicisation consiste à mettre en évidence le caractère de tonique
secondaire d’un degré /X/ en jouant le couple tonal secondaire :

#+ATTR_HTML: :class plat
| ( Dominante | — | Tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| Dominante de /X/ | — | Tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| Dominante de /X/ | — | /X/ |

L’accord parfait sera :

  - majeur si on souhaite mettre en évidence une tonalité secondaire majeure
  - mineur si on souhaite mettre en évidence une tonalité secondaire mineure


*** Sous-dominante secondaire

Une alternative consiste à jouer le couple plagal secondaire :

#+ATTR_HTML: :class plat
| ( Sous-dominante | — | Tonique ) | de /X/ |

c’est-à-dire :

#+ATTR_HTML: :class plat
| Sous-dominante de /X/ | — | Tonique de /X/ |

Si la fonction de tonique secondaire sur le degré /X/ est assurée par
un accord parfait situé sur le même degré, nous obtenons
l’enchaînement :

#+ATTR_HTML: :class plat
| Sous-dominante de /X/ | — | /X/ |


** Dominante auxiliaire

La *dominante auxiliaire* est la dominante secondaire obtenue en
choisissant la dominante principale comme tonique secondaire. En
d’autres termes, la dominante auxiliaire correspond à la dominante de
la dominante, située deux quintes plus haut que la tonique principale
dans le cycle des quinte :

#+ATTR_HTML: :class plat
| Noms         | : | tonique principale | dominante principale | dominante auxiliaire |
| Abréviations | : | T                  | D                    | Daux                 |
| Degrés       | : | 1                  | 5                    | 2                    |

La dominante auxiliaire est la fonction secondaire la plus utilisée
car elle permet de réaliser le couple tonal secondaire :

#+begin_center
Daux — D
#+end_center

qui renforce la dominante principale. Enfin, un accord du degré 2 peut
être disposé pour assurer une fonction tonale de sous-dominante ou de
dominante auxiliaire, reliant ainsi les deux fonctions.


** Sensibles


*** Sensibles secondaires

Une note située à une distance d’un demi-ton d’une tonique secondaire
crée une attraction mélodique vers cette dernière.

Une *sensible secondaire supérieure* est un degré situé juste
au-dessus d’une tonique secondaire, à un demi-ton de celle-ci.

Une *sensible secondaire inférieure* est un degré situé juste
en-dessous d’une tonique secondaire, à un demi-ton de celle-ci.


*** Sensibles auxiliaires

Une note située à une distance d’un demi-ton de la dominante crée une
attraction mélodique vers cette dernière.

La dominante correspondant au degré 5, les notes qui l’entourent sont
situées aux degrés 4 et 6.

Lorsque le degré 4 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire inférieure*.

Lorsque le degré 6 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire supérieure*.


*** Tableau récapitulatif

| Degrés | Noms                           | Abréviations |
|--------+--------------------------------+--------------|
|      2 | Sensible supérieure            | Ssup         |
|      7 | Sensible inférieure            | Sinf         |
|      6 | Sensible auxiliaire supérieure | SauxSup      |
|      4 | Sensible auxiliaire inférieure | SauxInf      |



* Cycle tonal

#+TOC: headlines 1 local

** Introduction

Le *cycle tonal* est une suite d’accords dont les fondamentales
descendent le cycle des quintes, mais en annulant ou ajoutant des
altérations pour que les notes obtenues restent dans la tonalité. Il
part du degré 1 et parcourt tous les autres degrés jusqu’à revenir à
la tonique.

Considérons par exemple la tonalité de /la mineur/. Le cycle des
quintes descendantes s’écrit :

#+begin_center
la ré sol do fa si^b mi^b la^b
#+end_center

Les bémols /si^b/, /mi^b/ et /la^b/ ne font pas partie de la tonalité
et sont donc annulés. On obtient ainsi le cycle :

#+begin_center
la ré sol do fa si mi la
#+end_center

Si on le traduit en termes de degrés, on obtient :

#+ATTR_HTML: :class plat
| Notes  | : | la | ré | sol | do | fa | si | mi | la |
| Degrés | : |  1 |  4 |   7 |  3 |  6 |  2 |  5 | 1  |

Écrit en terme de degrés, le cycle tonal est applicable à n’importe
quelle tonalité. C’est donc cette forme que nous retiendrons :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 3 | 6 | 2 | 5 | 1 |

C’est ce cycle, répété en boucle, qui sert de fondation à la musique
tonale. Naturellement, de nombreuses variations de ce modèle se
succèdent afin d’en rompre la monotonie. Si les techniques permettant
de produire ces variations peuvent nous mener à des enchaînements
parfois très éloignés du cycle d’origine, elles respectent certains
principes :

  - il existe un lien entre
    + les accords originaux et les modifications
    + le nouvel accord et son environnement
  - ce lien peut être
    + accord synonyme
    + lien sémantique
    + fonction secondaire
    + lien polyphonique
    + enharmonie
  - l’accord final de chaque cycle fait en général fonction de tonique
    ou de dominante


*** Quinte diminuée

Reprenons notre exemple en /la mineur/. Si toutes les quintes étaient
justes, nous traverserions le cycle complet des douze notes
diatoniques et altérées :

#+begin_center
la ré sol do fa si^b mi^b la^b ré^b sol^b [do^b = si] mi la
#+end_center

Au moins une de ces quintes doit être altérée afin de rester dans la
gamme heptatonique de /la mineur/. Effectivement, l’annulation des
bémols produit l’apparition de la quinte diminuée descendante
/fa — si/.


** Suppression des doublons

Afin de simplifier la structure musicale, les accords intervenant en
double peuvent naturellement être réduits à un seul exemplaire.
Exemple :

#+ATTR_HTML: :class plat
| =...= | 5 | *1* | *1* | 4 | =...= | ⟼ | =...= | 5 | *1* | 4 | =...= |


** Substitution

Cette opération consiste à remplacer un accord du cycle par un autre.
On veille toutefois à ce que l’accord original et son remplaçant
présentent certaines caractéristiques communes. Voici les principaux
mécanismes de substitution :

  - substitution par un accord synonyme à l’accord remplacé

  - substitution par un accord qui possède un lien sémantique avec
    l’accord remplacé

  - substitution par une fonction secondaire transformant le degré
    suivant en tonique secondaire

  - substitution polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants

  - substitution enharmonique : le nouvel accord est enharmonique à
    l’accord remplacé


** Insertion

Cette opération consiste à insérer un nouvel accord entre deux accords
du cycle. On veille toutefois à ce que l’accord inséré présente
certaines caractéristiques communes avec au moins un des accords
environnants. Les techniques d’insertion sont similaires à celles
utilisées pour la substitution :

  - insertion d’un accord synonyme renforçant une fonction tonale
    environnante

  - insertion d’un accord possédant un lien sémantique avec un des
    accords environnants

  - insertion d’une fonction secondaire transformant le degré
    suivant en tonique secondaire

  - insertion polyphonique : le nouvel accord possède des liens
    polyphoniques avec les accords environnants

  - insertion par enharmonie : le nouvel accord est enharmonique au
    précédent ou au suivent


** Déviation

Cette opération consiste à dévier de trajectoire en créant un
raccourci dans le cycle tonal. On veille toutefois à ce que l’accord
de départ ait un lien avec l’accord d’arrivée :

  - déviation vers un accord d’arrivée synonyme à celui de départ

  - déviation vers un accord d’arrivée qui possède un lien sémantique
    avec l’accord de départ

  - déviation polyphonique : l’accord de départ possède un lien polyphonique
    avec l’accord d’arrivée

  - déviation enharmonique : les accords de départ et d’arrivée sont
    enharmoniques

On ajoute à ces possibilités le *raccourci* menant de n’importe quel
accord du cycle vers une fonction de dominante, éventuellement suivie
par une fonction de tonique.


*** Déviation enharmonique

À titre d’exemple de déviation enharmonique, plaçons-nous en /la
mineur/. L’accord de dominante sans fondamentale :

#+begin_center
sol^{#} si ré fa
#+end_center

est enharmonique à :

#+begin_center
la^b si ré fa
#+end_center

lui-même renversement de :

#+begin_center
si ré fa la^b
#+end_center

Ce dernier accord étant du degré 2, on peut créer un court-circuit
entre les degrés 7 et 2. Le cycle devient :

#+ATTR_HTML: :class plat
| 1 | 4 | 7 | 2 | 5 | 1 |


** Figures de style

On peut imaginer d’autres types de modifications à apporter au cycle
tonal, en s’inspirant des [[file:litera-02-styleau.org][figures de style]] littéraires par exemple.


** Interprétation & réalisation

#+TOC: headlines 1 local

*** Introduction

Il existe de nombreuses interprétations du cycle tonal en terme de
fonctions, et chacune de ces interprétations peut être réalisées par
différentes suites d’accords. Nous disposons donc d’un système très
prolifique.


*** Degré 7 comme dominante

Voici un exemple d’interprétation du cycle tonal :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | T | T | Daux | D | T |

Le degré 7 y est considéré comme une dominante sans fondamentale et
les degrés 3 et 6 comme des accords de tonique. L’astuce est que nous
allons à présent oublier les degrés du cycle pour se concentrer sur
les fonctions :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |

Nous pouvons décider de réaliser ces fonctions par la suite
d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | T | T | Daux | D | T |
| 1 |  4 | 5 | 1 | 6 |    2 | 5 | 1 |

pour autant que chacun d’entre-eux mette en évidence la note tonale
correspondante, cela va de soi. Mais il existe d’autres possibilités
pour représenter cette suite de fonctions. Par exemple :

#+ATTR_HTML: :class plat
| 1 | 4 | 5 | 6 | 3 | 2 | 5 | 1 |

ou :

#+ATTR_HTML: :class plat
| 1 | 2 | 5 | 6 | 1 | 4 | 5 | 1 |


*** Degré 3 comme dominante

Si nous considérons que le degré 3 représente une dominante, nous
pouvons interpréter le cycle tonal de la façon suivante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 | 6 |    2 | 5 | 1 |
| T | SD | D | D | T | Daux | D | T |

qui peut par exemple se représenter par la suite d’accords :

#+ATTR_HTML: :class plat
| T | SD | D | D | T | Daux | D | T |
| 1 |  4 | 7 | 5 | 6 |    2 | 5 | 1 |


*** Degrés 6 et 2 comme sous-dominante

Si nous considérons que les degrés 6 et 2 représentent une
sous-dominante :

#+ATTR_HTML: :class plat
| 1 |  4 | 7 | 3 |  6 |  2 | 5 | 1 |
| T | SD | D | T | SD | SD | D | T |

nous obtenons par exemple :

#+ATTR_HTML: :class plat
| T | SD | D | T | SD | SD | D | T |
| 1 |  2 | 5 | 1 |  6 |  4 | 5 | 1 |


*** Suites fréquentes

Nous constatons que les suites de fonctions :

#+ATTR_HTML: :class plat
| T | SD   | D | T |

et :

#+ATTR_HTML: :class plat
| T | Daux | D | T |

sont très fréquentes.


**** Anatole

Parmi les suites d’accords courantes provenant des innombrables
variations du cycle tonal, citons l’ *anatole* :

#+ATTR_HTML: :class plat
| 6 | 2 | 5 | 1 |


** Cycle plagal

Le *cycle plagal* est une suite d’accords dont les fondamentales
montent le cycle des quintes :

#+ATTR_HTML: :class plat
| 1 | 5 | 2 | 6 | 3 | 7 | 4 | 1 |

Les modifications qu’on peut lui apporter sont analogues à celles du
cycle tonal.

Si le cycle plagel est rarement utilisé seul, il peut être utile d’en
insérer occasionnellement un fragment dans le cycle tonal.


* Dynamique

#+TOC: headlines 1 local


** Introduction

La dynamique musicale est basée sur l’alternance de *tension* et de
*détente*, la détente servant de *résolution* à la tension initiale :

#+ATTR_HTML: :class plat
| Tension | — | Résolution |

La tension d’un objet musical est souvent due à l’ *attraction* vers
un objet proche condidéré comme plus stable.

Un objet musical est qualifié de :

  - *stable* s’il ne cause aucune tension

  - *instable* s’il provoque une tension


** Consonance & dissonance


*** Intervalles harmoniques

Un intervalle harmonique :

  - consonant est stable.
  - dissonant est instable.


*** Accords

Un accord :

  - consonant est stable.
  - dissonant est instable.


*** Généralisation

Par analogie avec les intervalles harmoniques :

  - un objet musical stable est qualifié de *consonant*
  - un objet musical instable est qualifié de *dissonant*

Synonymes :

  - un objet musical consonant est aussi appelé *consonance*
  - un objet musical dissonant est aussi appelé *dissonance*


** Préparation

Une tension peut être précédée d’une phase de *préparation*, phase qui
permet d’introduire la future dissonance dans un contexte où elle est
consonante. On a donc la structure générique :

#+ATTR_HTML: :class plat
| Préparation | — | Tension | — | Résolution |

où la phase de préparation est optionnelle.

La dissonance qui passe par une phase de préparation est dite
*préparée*.


** Résolution

Lorsqu’une dissonance se résout indifféremment suivant plusieurs
processus différents, on dit alors que sa résolution est *libre*.

Lorsqu’une dissonance se résout préférentiellement via un processus
bien défini, correspondant à un effet de détente maximal, on dit alors
que cette résolution est *régulière* ou *ordinaire*. On parle
également de *mouvement obligé*.

Dans le cas où une dissonance censée adopter un mouvement obligé se
résout autrement, on parle de résolution *irrégulière* ou
*exceptionnelle*.

Enfin, lorsqu’une dissonance ne se résout pas, on peut conduire la
musique vers une autre idée, ou vers une tension encore plus forte.


*** Absolue ou relative

La *résolution absolue* fait suivre un objet dissonant par un objet
consonant.

La *résolution relative* fait suivre un objet consonant par un objet
qui est encore plus consonant que le premier.


*** Nouveauté

La dissonance peut être utilisée comme *introduction* à un nouvel
objet musical, la résolution amenant alors la *nouveauté* que l’on
souhaite présenter :

#+ATTR_HTML: :class plat
| Introduction | = | Tension    |
| Nouveauté    | = | Résolution |


* Dynamique mélodique

#+TOC: headlines 1 local

** Sensibles

Une sensible induit une tension mélodique vers la note tonale la plus
proche : tonique ou dominante. Les sensibles sont donc considérées
comme des notes dissonantes.

Voici les résolutions attendues :

  - la sensible inférieure se résout sur la tonique en montant d’un demi-ton
  - la sensible supérieure se résout sur la tonique en descendant d’un demi-ton
  - la sensible auxiliaire inférieure se résout sur la dominante en montant d’un demi-ton
  - la sensible auxiliaire supérieure se résout sur la dominante en descendant d’un demi-ton


** Hauteur

Une note plus aiguë est plus tendue qu’une note plus grave.

Une note plus grave est plus détendue qu’une note plus aiguë.


** Continuité

Un intervalle conjoint ne suscite pas de tension.

Un intervalle disjoint entre deux notes /x/ et /y/ suscite une tension
qui se résout en jouant les notes intermédiaires entre /x/ et /y/.


** Direction

Une mélodie qui monte vers l’aigu génère une tension.

Une mélodie qui descend vers le grave produit une détente.


** Extrêmes

Une mélodie dont les pics (maxima locaux) montent vers l’aigu génère
une tension.

Une mélodie dont les creux (minima locaux) descendent vers le grave
produit une détente.


** Accentuation

Une mélodie est généralement accentuée par :

  - la durée : notes de durée plus longue
  - des sauts : mouvements disjoints dans une mélodie majoritairement conjointe
  - des virages : changements de direction, de pente
  - des extrêmes : pics ou creux locaux


*** Notes essentielles

Les accents mélodiques sont généralement disposés sur des notes
essentielles ou sur des ornements harmoniques.


*** Discontinuités

Il est rare d’observer un mouvement disjoint ne faisant intervenir
aucune note de l’accord.


*** Indépendance

Les accents mélodiques des différentes voix de la polyphonie sont
indépendants. La plupart du temps, on s’arrange pour que ces accents
apparaissent à des instants différents sur chacune des voix, ceci afin
de les mettre tour à tour en évidence.

Il arrive toutefois que les accents mélodiques soient synchronisés
afin de donner à l’ensemble un effet de convergence et d’apothéose
très convaincant.


* Modes

#+TOC: headlines 1 local

** Introduction

Nous avons déjà vu les modes naturels, le majeur et le mineur. Ce
chapitre recense les autres modes disponibles.


** Heptaphoniques


*** Acoustique

Le mode acoustique est construit à partir des premiers éléments de la
série des harmoniques naturelles. Elle contient donc une quinte, une
tierce majeure, une septième mineure, une seconde majeure et une
quarte augmentée. En partant d’un /do/, on obtient :

#+begin_center
do ré mi fa^{#} sol si^b do
#+end_center

On peut bien entendu ajouter la note naturelle manquante, à savoir
le /la/ :

#+begin_center
do ré mi fa^{#} sol la si^b do
#+end_center

La gamme ainsi obtenue possède les mêmes écarts qu’un relatif du mode
mineur ascendant à partir du quatrième degré :

#+begin_center
ré mi fa^{#} sol^{#} la si do ré
#+end_center


*** Superlocrien

Le mode superlocrien est construit comme un relatif du mode mineur
ascendant à partir du septième degré :

#+begin_center
sol^{#} la si do ré mi fa^{#} sol^{#}
#+end_center

Ce mode est appelé superlocrien, car il ressemble fort au mode
locrien. On le voit clairement en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la si
#+end_center


**** Mineur harmonique

Il existe aussi une variante dérivée du mode mineur harmonique :

#+begin_center
sol^{#} la si do ré mi fa sol^{#}
#+end_center

ce qui donne, en prenant /si/ comme tonique :

#+begin_center
si do ré mi^b fa sol la^b si
#+end_center


*** Tzigane

Le mode Tzigane, ou mode Hongrois, est un mode dérivé du mineur
harmonique, le 4e degré étant haussé afin de se rapprocher de la
dominante :

#+begin_center
la si do ré^{#} mi fa sol^{#} la
#+end_center

Ce mode est caractérisé par la présence de deux sensibles auxiliaires :

#+begin_center
sensible auxiliaire inférieure ⟼ dominante ⟻ sensible auxiliaire supérieure
#+end_center

Notons les deux écarts de trois demi-tons entre les degrés 3 - 4 et
6 - 7.


*** Andalou

Il s’agit d’un mode ressemblant au /mode de mi/, mais disposant d’une
médiante flottante, formant une tierce majeure ou mineure avec la
tonique :

#+begin_center
mi fa sol^{(#)} la si do ré mi
#+end_center


*** Napolitain

Il s’agit d’un mode ressemblant au /mode de mi/ où le septième degré
est haussé d’un demi-ton, ce qui le transforme en sensible inférieure :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

On voit que la sus-tonique est une sensible supérieure. Ce mode est
donc caractérisé par la double attraction :

#+begin_center
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+end_center

Il en existe une variante où le sixième degré est haussé :

#+begin_center
mi fa sol la si do^{#} ré^{#} mi
#+end_center


*** Oriental


**** Variante phrygienne

Le mode oriental phrygien est un relatif du mode tzigane construit à
partir du cinquième degré :

#+begin_center
mi fa sol^{#} la si do ré^{#} mi
#+end_center

Ce mode est caractérisé par les deux écarts de trois demi-tons entre
les degrés 2 - 3 et 6 - 7, ainsi que par la double attraction :

#+begin_center
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+end_center

Si on souhaite également créer une double attraction vers la
dominante :

#+begin_center
sous-dominante altérée ⟼ dominante ⟻ sous-médiante
#+end_center

il suffit de hausser le degré 4 :

#+begin_center
mi fa sol^{#} la^{#} si do ré^{#} mi
#+end_center


**** Variante locrienne

Le mode oriental phrygien est un relatif du mode tzigane construit à
partir du deuxième degré :

#+begin_center
si do ré^{#} mi fa sol^{#} la si
#+end_center

Afin d’obtenir la même propriété de double attraction que la variante
basée sur le mode de /mi/, on peut sensibiliser le degré 7 en le
haussant d’un demi-ton :

#+begin_center
si do ré^{#} mi fa sol^{#} la^{#} si
#+end_center


** Tétraphoniques

Les modes tetraphoniques sont des gammes de quatre notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
quatre quintes :

#+begin_center
do sol ré la
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode tetraphonique :

#+begin_center
do ré sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do | ré  | sol |
| sur ré  | : | ré  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré | sol | la  |


** Pentaphoniques

Les modes pentaphoniques sont des gammes de cinq notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
cinq quintes :

#+begin_center
do sol ré la mi
#+end_center

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode pentaphonique :

#+begin_center
do ré mi sol la do
#+end_center

et ses relatifs :

#+ATTR_HTML: :class plat
| sur sol | : | sol | la  | do  | ré | mi  | sol |
| sur ré  | : | ré  | mi  | sol | la | do  | ré  |
| sur la  | : | la  | do  | ré  | mi | sol | la  |
| sur mi  | : | mi  | sol | la  | do | ré  | mi  |


*** Avec caractéristique

Ce sont des modes pentaphoniques que l’on altère afin d’intégrer une
ou plusieurs notes caractéristiques des modes naturels. Par exemple,
ce mode pentaphoniques altéré :

#+begin_center
ré mi sol^{#} la do ré
#+end_center

possède une quarte haussée, caractéristique du mode lydien.


*** Blues

Le mode blues est un mode pentaphonique développant les quintes à
partir de la médiante. La médiante, la dominante et la sous-tonique
sont flottantes :

#+begin_center
la do^{(#)} ré mi^{(b)} sol^{(#)} la
#+end_center


*** Chinois

Le mode chinois est un mode pentaphonique développant les quintes à
partir de la tonique. Par exemple, avec /do/ comme tonique, nous
obtenons :

#+begin_center
do ré mi sol la do
#+end_center


*** Japonais

Le mode japonais est un mode pentaphonique développant les quintes à
partir de la sous-dominante. La gamme modèle de ce mode possède un
/mi/ pour tonique. On part alors de la sous-dominante /la/ et on
gravit les quintes entre notes naturelles :

#+begin_center
la mi si fa do
#+end_center

 En disposant ces notes sur une octave /mi — mi^{+1}/ et en les
ordonnant de la plus grave à la plus aiguë, nous obtenons :

#+begin_center
mi fa la si do mi
#+end_center

La dominante auxiliaire /fa/ est une sensible supérieure. Ce mode
possède un autre demi-ton entre la dominante /si/ et la sous-médiante
/do/.

Notons également l’intervalle de quarte augmentée /si — fa/ qui sépare
la sus-tonique de la dominante.


* Accords classés

#+TOC: headlines 1 local


** Introduction

Les accords classés sont des accords naturellement engendrés par les
gammes lorsqu’on y superpose des tierces.


*** Nomenclature

Une *septième de dominante* est un accord de quatre notes dont la
fondamentale est placée sur la dominante.

Une *septième d’espèce* est un accord de quatre notes dont la
fondamentale n’est pas placée sur la dominante.

On utilise les abréviations suivantes :

| Accord                | Abréviation |
|-----------------------+-------------|
| Septième de dominante | 7e D        |
| Septième d’espèce     | 7e E        |


** Tonique

Les accords de tonique les plus utilisés sont des accords parfaits
majeur ou mineur. On rencontre aussi des septièmes d’espèce, comme
dans ces exemples :

| Accords             | Abréviations | Exemples             |                  |
|                     |              | Gammes               | Accords          |
|---------------------+--------------+----------------------+------------------|
| Septième majeure    | 7e M         | do majeur            | do mi sol si     |
| Septième mineure    | 7e m         | la mineur            | la do mi sol     |
| Septième harmonique | 7e h         | la mineur harmonique | la do mi sol^{#} |

et plus rarement des accords de 5, 6 ou 7 notes.


*** Quinte augmentée

Si nous supprimons la fondamentale de l’accord de septième harmonique,
nous obtenons un accord dit de *quinte augmentée* :

| Accords          | Abréviations | Exemples      |
|------------------+--------------+---------------|
| Quinte augmentée | 5te aug      | do mi sol^{#} |


** Dominante

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante sont très importants, de par leur fonction
tonale dynamique et parce qu’ils sont naturellement attirés par un
accord de tonique.


*** Triades

En empilant deux tierces, on obtient un accord parfait majeur, que ce
soit en mode majeur ou mineur harmonique :

| Accords        | Abréviations | Exemples             |               |
|                |              | Gammes               | Accords       |
|----------------+--------------+----------------------+---------------|
| Parfait majeur | M            | do majeur            | sol si ré     |
| Parfait majeur | M            | la mineur harmonique | mi sol^{#} si |


*** Septième

En empilant trois tierces, on obtient l’accord de *septième de
dominante*, dont la structure est identique en majeur et en mineur
harmonique :

| Accords               | Abréviations | Exemples             |                  |
|                       |              | Gammes               | Accords          |
|-----------------------+--------------+----------------------+------------------|
| Septième de dominante | 7e D         | do majeur            | sol si ré fa     |
| Septième de dominante | 7e D         | la mineur harmonique | mi sol^{#} si ré |

Dans les deux cas :

  - la première tierce est majeure
  - les deux tierces suivantes sont mineures

Avec les accords parfaits majeur et mineur, la septième de dominante
figure parmi les accords les plus importants de l’harmonie tonale.


**** Quinte diminuée

Lorsqu’on prive un accord de dominante de sa fondamentale, on obtient
un accord de *quinte diminuée* :

| Accords         | Abréviations | Exemples             |               |
|                 |              | Gammes               | Accords       |
|-----------------+--------------+----------------------+---------------|
| Quinte diminuée | 5te dim      | do majeur            | si ré fa      |
| Quinte diminuée | 5te dim      | la mineur harmonique | sol^{#} si ré |


*** Neuvième

En empilant quatre tierces, on obtient la *neuvième de dominante*,
majeure ou mineure suivant le mode :

| Accords                       | Abréviations | Exemples             |                     |
|                               |              | Gammes               | Accords             |
|-------------------------------+--------------+----------------------+---------------------|
| Neuvième de dominante majeure | 9e D M       | do majeur            | sol si ré fa la     |
| Neuvième de dominante mineure | 9e D m       | la mineur harmonique | mi sol^{#} si ré fa |


**** Septième et quinte diminuée

Lorsqu’on prive une neuvième de dominante majeure de sa fondamentale,
on obtient un accord de *septième et quinte diminuée* :

| Accords                     | Abréviations | Exemples  |             |
|                             |              | Gammes    | Accords     |
|-----------------------------+--------------+-----------+-------------|
| Septième et quinte diminuée | 7e & 5te dim | do majeur | si ré fa la |


**** Septième diminuée

Lorsqu’on prive une neuvième de dominante mineure de sa fondamentale,
on obtient un accord de *septième diminuée* :

| Accords           | Abréviations | Exemples             |                  |
|                   |              | Gammes               | Accords          |
|-------------------+--------------+----------------------+------------------|
| Septième diminuée | 7e dim       | la mineur harmonique | sol^{#} si ré fa |


** Sous-dominante

Les accords de sous-dominante sont similaires aux accords de tonique :
accords parfaits et septièmes majeures ou mineures. Exemples :

| Accords | Exemples  |             |
|         | Gammes    | Accords     |
|---------+-----------+-------------|
| 7e M    | do majeur | fa la do mi |
| 7e m    | la mineur | ré fa la do |


** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: section:dominanteAuxiliaire
:END:

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante auxiliaire sont similaires aux accords de
dominante, si ce n’est qu’ils sont construits sur le degré 2 de la
gamme. Afin de renforcer le rôle de ces accords, il est possible de
les altérer en faisant /comme si/ la dominante de la gamme courante
devenait la tonique. On utilise les abréviations :

| Accords                          | Abréviations |
|----------------------------------+--------------|
| Triade de dominante auxiliaire   | 3ade Daux    |
| Septième de dominante auxiliaire | 7e Daux      |
| Neuvième de dominante auxiliaire | 9e Daux      |


*** Majeur

Nous prenons comme illustration la gamme de /do majeur/. Nous obtenons
par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| do ré mi fa sol la si do | ⟼ | sol la si do ré mi fa^{#} sol |

L’altération haussière du /fa^{#}/ (degré 4 par rapport à la tonique
/do/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /sol/.

On peut également altérer le /la/ (degré 6 par rapport à la tonique
/do/) vers le bas afin de le transformer en sensible auxiliaire
supérieure. Nous avons alors la gamme :

#+begin_center
sol la^b si do ré mi fa^{#} sol
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en do majeur |
|-------------------------+-----------+-----------------------|
| Aucune                  | 3ade Daux | ré fa la              |
|                         | 7e Daux   | ré fa la do           |
|                         | 9e Daux   | ré fa la do mi        |
| Inférieure              | 3ade Daux | ré fa^{#} la          |
|                         | 7e Daux   | ré fa^{#} la do       |
|                         | 9e Daux   | ré fa^{#} la do mi    |
| Inférieure & Supérieure | 3ade Daux | ré fa^{#} la^b        |
|                         | 7e Daux   | ré fa^{#} la^b do     |
|                         | 9e Daux   | ré fa^{#} la^b do mi  |


*** Mineur harmonique

Nous prenons comme illustration la gamme de /la mineur harmonique/.
Nous obtenons par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| la si do ré mi fa sol^{#} la | ⟼ | mi fa^{#} sol la si do ré^{#} mi |

L’altération haussière du /ré^{#}/ (degré 4 par rapport à la tonique
/la/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /mi/.

Si on supprime l’altération haussière du /fa^{#}/ (degré 6 par rapport
à la tonique /la/), on transforme ce degré en sensible auxiliaire
supérieure de la dominante /mi/. Nous obtenons alors la gamme :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en la mineur harmonique |
|-------------------------+-----------+----------------------------------|
| Supérieure              | 2ade Daux | si ré fa                         |
|                         | 7e Daux   | si ré fa la                      |
|                         | 9e Daux   | si ré fa la do                   |
| Inférieure              | 3ade Daux | si ré^{#} fa^{#}                 |
|                         | 7e Daux   | si ré^{#} fa^{#} la              |
|                         | 9e Daux   | si ré^{#} fa^{#} la do           |
| Inférieure & Supérieure | 3ade Daux | si ré^{#} fa                     |
|                         | 7e Daux   | si ré^{#} fa la                  |
|                         | 9e Daux   | si ré^{#} fa la do               |

Remarquons en passant que la triade de dominante auxiliaire non
altérée est un accord de quinte diminuée.


*** Sans fondamentale

Tout comme les accords de dominante, les accords de dominante
auxiliaire sont parfois présentés sans leur fondamentale. On obtient
alors des accords qui semblent être du degré 4, les fonctions de
dominante auxiliaire et de sous-dominante se voyant ainsi intimement
liées.

Exemple en /do majeur/ :

| Sensibles auxiliaires   | Accords | Exemples en do majeur |
|-------------------------+---------+-----------------------|
| Aucune                  | 7e Daux | fa la do              |
|                         | 9e Daux | fa la do mi           |
| Inférieure              | 7e Daux | fa^{#} la do          |
|                         | 9e Daux | fa^{#} la do mi       |
| Inférieure & Supérieure | 7e Daux | fa^{#} la^b do        |
|                         | 9e Daux | fa^{#} la^b do mi     |

Exemple en /la mineur harmonique/ :

| Sensibles auxiliaires   | Accords | Exemples en la mineur harmonique |
|-------------------------+---------+----------------------------------|
| Supérieure              | 7e Daux | ré fa la                         |
|                         | 9e Daux | ré fa la do                      |
| Inférieure              | 7e Daux | ré^{#} fa^{#} la                 |
|                         | 9e Daux | ré^{#} fa^{#} la do              |
| Inférieure & Supérieure | 7e Daux | ré^{#} fa la                     |
|                         | 9e Daux | ré^{#} fa la do                  |


*** Sixtes augmentées

#+TOC: headlines 1 local

**** Introduction

Les accords de *sixte augmentée* sont des accords de dominante
auxiliaire renversés. Ils sont altérés de sorte qu’ils présentent un
intervalle caractéristique de sixte augmentée, d’où leur nom.


**** Sixte française

La *sixte française* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est présentée sous la forme d’un
second renversement.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| ré fa^{#} la^b do | ⟼ | la^b do ré fa^{#} |

En /la mineur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| si ré^{#} fa la | ⟼ | fa la si ré^{#} |


**** Sixte italienne

La *sixte italienne* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (ré) fa^{#} la^b do | ⟼ | la^b do (ré) fa^{#} |

ce qui nous donne finalement :

#+begin_center
la^b do fa^{#}
#+end_center

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la | ⟼ | fa la (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la ré^{#}
#+end_center


**** Sixte allemande

La *sixte allemande* est une neuvième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la do | ⟼ | fa la do (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la do ré^{#}
#+end_center

L’accord altéré de /do majeur/ respectant les mêmes écarts s’écrit :

#+begin_center
la^b do mi^b fa^{#}
#+end_center


** Emprunts

Un emprunt est un accord provenant d’une autre gamme (tonique et/ou
mode) que l’on insère dans la gamme courante.


*** Majeur ⟻⟼ Mineur

On peut placer des accords caractéristiques du mineur (quintes
augmentées, septièmes diminuées, ...) dans des gammes majeures, ou
l’inverse.


*** Tierces picardes

Une *tierce picarde* est un accord parfait majeur intégré à un autre
mode. On la rencontre souvent sur les degrés 1, 5, ou 4 du mode
mineur : la tierce de l’accord y est rendue majeure par une altération
haussière. Voici des exemples en /la mineur/ :

| Degrés | Exemples      |
|--------+---------------|
|      1 | la do^{#} mi  |
|      4 | ré fa^{#} la  |
|      5 | mi sol^{#} si |


*** Napolitain

En gamme de /mi napolitain/, l’accord de dominante auxiliaire non
altéré :

#+begin_center
fa la do
#+end_center

est un accord parfait majeur situé un demi-ton au-dessus de la tonique
/mi/. Par extension, on appelle accord *napolitain* tout accord défini
par les mêmes propriétés, et ce quels que soient le mode et la
tonique. Voici ce que cela donne en majeur et en mineur :

| do majeur    | la mineur  |
|--------------+------------|
| ré^b fa la^b | si^b ré fa |

Lorsque cet accord est présenté sous la forme de premier renversement,
il est appelé *sixte napolitaine* :

| do majeur    | la mineur  |
|--------------+------------|
| fa la^b ré^b | ré fa si^b |

Afin de former un accord similaire à une 7e de dominante, on peut
ajouter une note de 7e mineure à l’accord napolitain :

| do majeur         | la mineur       |
|-------------------+-----------------|
| ré^b fa la^b do^b | si^b ré fa la^b |

Ces derniers accords sont très prisés en jazz, où ils sont parfois
appelés *substitution au triton*, ou *substitution tritonique* à cause
de l’intervalle de triton qui lie la dominante auxiliaire altérée vers
le bas avec la dominante.


** Modes composites

Un *mode composite* associe à chaque degré une liste d’accords qui lui
sont caractéristiques. Voici un exemple de mode composite proche du
/la mineur/ :

| Degrés | Accords                     | Exemples             |
|--------+-----------------------------+----------------------|
|      1 | Parfait mineur              | la do mi             |
|        | Parfait majeur              | la do^{#} mi         |
|      2 | 7e Daux                     | si ré fa la          |
|        |                             | si ré^{#} fa la      |
|        | Napolitains                 | si^b ré fa           |
|        |                             | si^b ré fa la^b      |
|      3 | Quinte augmentée            | do mi sol^{#}        |
|      4 | Parfait mineur              | ré fa la             |
|        | Parfait majeur              | ré fa^{#} la         |
|      5 | Septième de dominante       | mi sol^{#} si ré     |
|        | Neuvième de dominante       | mi sol^{#} si ré fa  |
|      6 | Parfait majeur              | fa la do             |
|        | Quinte diminuée             | fa^{#} la do         |
|      7 | Quinte diminuée             | sol^{#} si ré        |
|        | Septième diminuée           | sol^{#} si ré fa     |
|        | Septième et quinte diminuée | sol^{#} si ré fa^{#} |

Cette variété d’accords implique qu’une partie ou la totalité des
notes de la gamme peut être altérée vers le haut ou vers le bas en
fonction du contexte.


* Accords à base de quintes

#+TOC: headlines 1 local

** Triades

Si on superpose deux quintes, on obtient une triade que nous décidons
de nommer accord de *double quinte* :

| Accords       | Exemples  |
|---------------+-----------|
| Double quinte | do sol ré |

En permutant les notes afin de les rapprocher, nous obtenons d’autres
dispositions de cet accord :

| Accords           | Exemples  |
|-------------------+-----------|
| Double quarte     | ré sol do |
|-------------------+-----------|
| Quarte et quinte  | sol do ré |
| Seconde et quinte | do ré sol |

Ces accords sont nommés, suivant les cas :

  - d’après les intervalles entre les notes consécutives
  - d’après les intervalles qui séparent les notes de la basse


** Tétrades

Les accords de quatre notes sont construits en superposant trois
quintes. Voici quelques dispositions possibles de ces accords :

| Accords        | Exemples     |
|----------------+--------------|
| Triple quinte  | do sol ré la |
| Triple quarte  | la ré sol do |
|----------------+--------------|
| 2de, 4te & 5te | sol la do ré |
| 4te, 5te & 9e  | sol do ré la |

Ces dispositions d’accords ressemblent aux modes tétraphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
tétraphonique.


** Pentades

Les accords de cinq notes sont construits en superposant quatre
quintes. Voici quelques dispositions possibles :

| Accords             | Exemples        |
|---------------------+-----------------|
| Quadruple quinte    | do sol ré la mi |
| Quadruple quarte    | mi la ré sol do |
|---------------------+-----------------|
| 3ce, 4te, 5te & 7e  | la do ré mi sol |
| 2de, 4te, 5te & 6te | sol la do ré mi |
| 4te, 5te, 6te & 9e  | sol do ré mi la |

Ces dispositions d’accords ressemblent aux modes pentaphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
pentaphonique.


* Polarisation secondaire

#+TOC: headlines 1 local

** Introduction

On parle de *polarisation secondaire* lorsqu’un ensemble d’accords
consécutifs remplissent des fonctions secondaires et mettent ainsi en
évidence l’existence d’une tonalité secondaire.

On choisit souvent une note tonale de la gamme principale comme
tonique de la tonalité secondaire. Placer la tonique secondaire sur la
tonique principale revient à identifier les deux gammes et n’apporte
aucun éclairage neuf. La dominante et la sous-dominante sont donc les
choix les plus courants de tonique secondaire.


** Dominante de la dominante

Nous avons déjà étudié en détail la dominante de la dominante, qui
n’est autre que la [[#section:dominanteAuxiliaire][dominante auxiliaire]], dans le chapitre consacré aux
accords classés.


** Dominante de la sous-dominante


*** Majeur

Nous allons à présent étudier la dominante de la sous-dominante.
Supposons par exemple que nous voulions renforcer le rôle de la
sous-dominante de /do majeur/, c’est-à-dire du /fa/. Notre accord doit
donc s’intégrer à la gamme de /fa majeur/, qui possède un
/si^b/ comme altération  :

#+begin_center
fa sol la si^b do ré mi fa
#+end_center

La dominante de cetta gamme étant le /do/, la première idée est
d’utiliser la triade :

#+begin_center
do mi sol
#+end_center

Malheureusement, cet accord ne met pas en évidence l’altération
/si^b/ et ne se différencie donc pas d’un accord parfait de
tonique de /do majeur/. On utilisera donc plutôt un accord d’au
minimum quatre notes :

#+begin_center
do mi sol si^b
#+end_center


*** Mineur

En mineur, les modifications sont un peu plus compliquées. Plaçons
nous dans la gamme de /la mineur harmonique/, et construisons la
dominante de la sous-dominante. La sous-dominante étant le /ré/, on
doit intégrer cet accord dans la gamme de /ré mineur harmonique/.
Comme nous sommes une quinte plus bas que le /la/, un /si^b/ apparaît,
auquel on doit ajouter la sensible inférieure /do^{#}/ du mineur
harmonique :

#+begin_center
ré mi fa sol la si^b do^{#} ré
#+end_center

La dominante de cette gamme étant le /la/, on utilisera donc :

#+begin_center
la do^{#} mi
#+end_center

ou :

#+begin_center
la do^{#} mi sol
#+end_center

Si on souhaite mettre l’altération /si^b/ en évidence, on utilisera
plutôt l’accord de cinq notes :

#+begin_center
la do^{#} mi sol si^b
#+end_center


* Dynamique des accords

#+TOC: headlines 1 local

** Accords parfaits

Les accords parfaits sont consonants. Pour plus de détails, voir la
section sur la [[file:musica-03-clavier.org::#section:consonanceAccordsParfaits][consonance des accords parfaits]].


** Autres triades

Les notes d’un accord de quinte augmentée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte augmentée

avec la fondamentale de l’accord. La quinte augmentée étant un
intervalle harmonique dissonant, l’accord de *quinte augmentée* est
*dissonant*.

#+begin_center
⁂
#+end_center

Les notes d’un accord de quinte diminuée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte diminuée

avec la fondamentale de l’accord. La quinte diminuée étant un
intervalle harmonique dissonant, l’accord de *quinte diminuée* est
*dissonant*.


** Septième de dominante

Les notes d’un accord de septième de dominante forment des
intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte
  - de septième mineure

avec la fondamentale de l’accord. La septième mineure étant un
intervalle harmonique dissonant, l’accord de *septième de dominante*
est également *dissonant*.


*** Harmoniques naturelles

Considérons le début d’une série d’harmoniques naturelles de
fondamentale /sol/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | sol | sol | ré | sol | si | ré | fa | sol | la | si | do^{#} | ré | =...= |
| /Numéros/ | : |   1 |   2 |  3 |   4 |  5 |  6 |  7 |   8 |  9 | 10 |     11 | 12 | =...= |

Si nous nous arrêtons à la note 7, nous avons :

#+begin_center
sol   sol   ré   sol   si   ré   fa
#+end_center

Hors doublures, nous obtenons un ensemble de quatre notes :

#+begin_center
sol   si   ré   fa
#+end_center

L’accord de septième de dominante se trouve donc dans une situation
paradoxale. Comme tous les accords de quatres notes à base de tierces,
sa note de septième forme une dissonance avec sa fondamentale. D’un
autre coté, nous voyons apparaître un accord de *septième de
dominante* parmi les premières harmoniques naturelles. Cet accord
figure donc parmi les plus *équilibrés* des accords dissonants. Il y a
donc là une forme d’ *équilibre dynamique*, ce qui explique son rôle
important.


** Autres accords de quatre notes ou plus

Un accord de quatre notes ou plus contient au moins une note qui va
former un intervalle harmonique de septième (mineure, majeure ou
diminuée) avec la fondamentale. Tous ces accords sont donc
*dissonants*.


** Accords à base de quintes

Les accords à base de quintes contiennent au moins un intervalle
dissonant : seconde, septième, neuvième, etc. Ce sont donc des accords
dissonants.


** Sensibles

La présence d’une sensible dans un accord provoque une tension qui
pousse cet accord à se résoudre sur un autre accord.

Une sensible, ou une sensible auxiliaire :

  - rend instable un accord qui ne comporte pourtant aucune dissonance constitutive
  - augmente l’instabilité d’un accord dissonant

#+begin_center
⁂
#+end_center

Les accords suivants contiennent une ou plusieurs tensions
mélodiques :

  - accords de dominante
  - accords de dominante auxiliaire avec sensible(s) auxiliaire(s)
  - accords napolitains
  - =...=


** Tableau récapitulatif

| Stabilité              | Accords               |
|------------------------+-----------------------|
| Consonants             | Parfait majeur        |
|                        | Parfait mineur        |
| Équilibre dynamique    | Septième de dominante |
| Dissonants             | Tous les autres       |

La présence de sensible(s) rend l’accord dissonant ou augmente son
instabilité.


* Dispositions des accords

#+TOC: headlines 1 local

** Accords parfaits


*** État fondamental

L'état fondamental est le plus affirmé, il agit comme un pilier de la
tonalité.

On double :

  - le plus souvent la fondamentale ou une note tonale
  - parfois la 3ce, en guise de variation

Si on souhaite supprimer une note :

  - on évite de supprimer la fondamentale
  - si on souhaite éviter l’ambiguité entre accord parfait majeur ou mineur
    + on ne supprime pas la note de 3ce majeure ou mineure
    + on supprime alors plutôt la 5te
  - l’accord produira un effet de simplicité si on supprime la 3ce
    + à réserver aux instants de convergence, comme en fin de phrase

#+begin_center
⁂
#+end_center

L’accord parfait du degré 7 remplit généralement la même fonction
qu’une 7e de dominante sans fondamentale.


*** Premier renversement

Le premier renversement est moins appuyé que l’état fondamental.

On double en général une note tonale.

Si un degré fort est situé une tierce au-dessus de la fondamentale, la
basse est généralement doublée et l’accord peut assurer la fonction
tonale correspondante. Exemples en /do majeur/ :

| degrés | fonction | premier       | état fondamental d’un accord |
|        |          | renversement  | situé une tierce au-dessus   |
|--------+----------+---------------+------------------------------|
| 2 & 4  | SD       | fa la ré fa   | fa la do fa                  |
| 6 & 1  | T        | do mi la do   | do mi sol do                 |
| 3 & 5  | D        | sol si mi sol | sol si ré sol                |

De part leur forte similitude, les accords de sixte peuvent aussi
ornementer l’accord parfait à l’état fondamental situé une tierce plus
haut. On compte en effet deux notes communes, trois avec la doublure.

#+begin_center
⁂
#+end_center

En mineur, l’accord de sus-tonique est soit :

  - au premier renversement pour éviter la quinte diminuée avec la basse
  - présenté avec un degré 2 abaissé pour produire un accord napolitain


*** Second renversement

Le second renversement sert souvent d’accord ornemental. On s’arrange
alors pour que la basse fasse note commune avec les accords
environnants, contrastant alors avec les mouvements mélodiques
ornementaux des autres voix.

On double en général la basse, pour produire un équilibre de deux voix
constantes et deux voix variables.

Exemple de second renversement avec broderies à l’alto et au ténor :

#+ATTR_HTML: :class plat
| S | : | sol |  sol | sol |
| A | : | ré  |  mi  | ré  |
| T | : | si  |  do  | si  |
| B | : | sol |  sol | sol |

Exemple de second renversement avec note de passage au ténor :

#+ATTR_HTML: :class plat
| S | : | do  | do | do  |
| A | : | sol | la | mi  |
| T | : | mi  | fa | sol |
| B | : | do  | do | do  |

Exemple avec une broderie au ténor et une note de passage au soprano :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | do  |
| A | : | sol | sol | sol |
| T | : | do  | si  | do  |
| B | : | do  | ré  | mi  |


** Septième de dominante

La note de 7e peut servir d’ornement harmonique ou mélodique.

Suppression :

  - on évite de supprimer la 3ce, car c’est la sensible inférieure
  - si on supprime la 7e, on se retrouve avec un accord parfait
  - on supprimer le plus souvent la fondamentale ou la 5te


*** Sans fondamentale

La septième de dominante sans fondamentale est au minimum au premier
renversement, avec la 3ce à la basse.

Cette disposition est moins dissonante que l’accord complet, car
l’intervalle de septième mineure n’est plus présent.

Le second renversement est préféré au premier, car il évite des
intervalles dissonants avec la basse, ce qui rend sa sonorité plus
douce.

Par exemple, en /do majeur/, la septième de dominante sans
fondamentale s’écrit :

#+begin_center
(sol) si ré fa ↦ si ré fa
#+end_center

ce qui produit un intervalle de quinte diminuée entre la 7e et la
basse. Par contre, au second renversement :

#+begin_center
(sol) si ré fa ↦ ré fa si
#+end_center

on obtient les intervalles consonants :

  - basse — 5te : tierce mineure
  - basse — 3ce : sixte majeure

L’intervalle dissonant du triton /fa — si/ ne fait alors pas
intervenir la basse.


** Accords à base de quintes

Suppressions :

  - on évite de supprimer les notes qui contiennent la tension
    + 2de
    + 4te
    + etc


** Remarques générales


*** Renversements

Les accords renversés ont généralement un caractère moins affirmé que
leurs homologues à l’état fondamental. Cette remarque est d’autant
plus vraie pour les accords de trois notes. Afin de ne pas rendre leur
fonction tonale encore plus floue, on évite autant que possible de
supprimer une note d’une triade renversée.

Par contre, les accords renversés de quatre notes ou plus, et en
particulier la 7e et la 9e de dominante, peuvent s’employer sans
fondamentale ou sans quinte.


* Dynamique des enchaînements

#+TOC: headlines 1 local

** Tension & résolution

Le principe d’alternance d’accords stables et instables est
omniprésent en musique. Ce ressort musical est centré autour d’une
phase de *tension*, accord instable contenant une ou plusieurs notes
dissonantes. Chaque tension est suivie d’une phase de *résolution* où
chaque note dissonante se résout vers une note d’un accord stable.

La résolution d’une note instable dans un accord stable peut se
réaliser suivant différents schémas :

  - *résolution conjointe* : la note instable réalise un mouvement
    conjoint variable vers une note inclue dans l’accord stable

  - *résolution par intégration* : la note instable est inclue dans
    l’accord stable suivant et devient donc naturellement stable lors
    du changement d’accord

  - *résolution polyphonique* : les notes instables réalisent un ou
    plusieurs mouvements polyphoniques élégants vers des notes inclues
    dans l’accord stable

La tension peut être précédée d’un accord stable de *préparation* :

  - qui permet d’amener les notes dissonantes par mouvement conjoint
    variable, on a alors *préparation conjointe*

  - qui contient les futures notes dissonantes, on a alors
    *préparation par intégration*

  - qui permet d’amener les notes dissonantes par un ou plusieurs
    mouvements polyphoniques élégants, on a alors *préparation
    polyphonique*

On a donc le cycle générique :

#+begin_center
préparation  —  tension  —  résolution  — préparation  —  tension  — résolution  —  =...=
#+end_center

où les préparations sont facultatives. Lorsque l’accord de préparation
est omis, on dit que la dissonance est *attaquée*.

Remarquons que l’accord de résolution peut servir d’accord de
préparation à la tension suivante, formant ainsi un cycle :

#+begin_center
préparation —  tension  —  (résolution & préparation)  —  tension  — (résolution & préparation)  —  =...=
#+end_center


** Quarte et sixte

L’accord de quarte et sixte ne comporte que des notes consonantes, et
peut donc être considéré comme un accord consonant.

Il permet toutefois une résolution relative vers un accord encore plus
stable, à savoir l’accord parfait à l’état fondamental :

  - note de sixte ↦ note de quinte
  - note de quarte ↦  note de tierce

Exemple de résolution d’une 4te & 6te de fondamentale /fa/ :

#+ATTR_HTML: :class plat
| S | : | la | sol |
| A | : | fa | mi  |
| B | : | do | do  |

L’accord de 4te & 6te peut également être utilisé comme [[file:musica-03-clavier.org::#section:accordBroderie][accord broderie]].


** Couple tonal

#+TOC: headlines 1 local

*** Accords parfaits

Dans cet exemple en /do majeur/, on note que la sensible inférieure
/si/ (3ce de l’accord de dominante) se résout sur la tonique /do/
(fondamentale de l’accord de tonique) :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | sol  | sol  |
| T | : | ré   | mi   |
| B | : | sol  | do   |


*** Septième de dominante

La sensible se résout généralement sur la tonique.

En mode majeur, une autre progression par demi-ton est possible : la
sous-dominante qui évolue vers la médiante.

Dans cet exemple en /do majeur/, on constate que la 7e, le /fa/, se
résout en descendant d’un demi-ton sur la 3ce de l’accord de tonique,
à savoir le /mi/ :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | /fa/ | /mi/ |
| T | : | ré   | do   |
| B | : | sol  | do   |

L’intervalle harmonique de triton /fa/ — /si/ se résout donc vers la
sixte /mi/ — /do/. En termes de cadences d’intervalles, il s’agit
d’une cadence extérieure conjointe.

En mode mineur, un enchaînement analogue est possible si on utilise
une sensible inférieure et une tierce picarde.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | si      | mi     |
| B | : | mi      | la     |


**** Préparation

Si l’on souhaite ajouter un accord de préparation contenant la 7e, on peut par
exemple choisir un accord de sous-dominante.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | do   | si   | do   |
| T | : | la   | ré   | do   |
| B | : | fa   | sol  | do   |

On peut aussi faire progresser l’alto du /la/ au /do/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | do   | ré   | do   |
| B | : | fa   | sol  | do   |

Ici, l’accord de préparation est une dominante auxiliaire :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | ré   | ré   | do   |
| B | : | fa   | sol  | do   |

Une variante où la quinte de l’accord de dominante est supprimée :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | ré   | sol  | sol  |
| B | : | fa   | sol  | do   |


**** Résolution irrégulière

Si on souhaite conserver les deux accords complets, on peut enchaîner
la 5te de l’accord de dominante avec la 5te de l’accord de tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | /fa/ | /mi/ |
| T | : | ré   | sol  |
| B | : | sol  | do   |

Notons toutefois que cela produit des quintes consécutives.

Une autre solution consiste à dévier la sensible inférieure de son
mouvement attendu vers la tonique, et la rediriger vers la 5te de
l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /si/ | /sol/ |
| A | : | /fa/ | /mi/  |
| T | : | ré   | do    |
| B | : | sol  | do    |

Enfin, on peut dévier la 7e et la 5te de l’accord de dominante :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/  |
| A | : | /fa/ | /sol/ |
| T | : | ré   | mi    |
| B | : | sol  | do    |


*** Neuvième de dominante

Dans cet exemple en /do majeur/, la 9e de dominante est suivie par un
accord de tonique. On voit que la 9e, le /la/, se résout en descendant
sur la 5te de l’accord de tonique, à savoir le /sol/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | mi    |
| T | : | si   | do    |
| B | : | sol  | do    |

La 9e de dominante peut également se résoudre à l’intérieur d’un autre
accord de dominante. Voici par exemple une résolution d’une 9e de
dominante sans fondamentale vers une 7e de dominante complète,
toujours en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | fa    |
| T | : | ré   | ré    |
| B | : | si   | si    |

Le même cas en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/    | /mi/    |
| A | : | ré      | ré      |
| T | : | si      | si      |
| B | : | sol^{#} | sol^{#} |


** Dominante auxiliaire

Les accords de dominante auxiliaire peuvent subir des altérations qui
les rapprochent des notes tonales. Ces notes altérées se résolvent
alors naturellement sur les degrés correspondant :

| Résolution     | do majeur    | la mineur    |
|----------------+--------------+--------------|
| Vers dominante | fa^{#} ⟼ sol | ré^{#} ⟼ mi  |
|                | la^b ⟼ sol   | fa ⟼ mi      |
| Vers tonique   | si ⟼ do      | sol^{#} ⟼ la |
|                | ré^b ⟼ do    | si^b ⟼ la    |


** Septièmes d’espèces

Les septièmes d’espèces sont utilisées pour renforcer la résolution
vers l’accord suivant.

Le choix le plus évident consiste à imiter le couple tonal en
enchaînant avec un accord situé une quinte plus bas.

Dans cet exemple, qui enchaine un accord de /la/ avec un accord de
/ré/, on voit que la 7e, le /sol/, se résout en descendant vers le
/fa/ de l’accord suivant :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /fa/ |
| A | : | mi    | ré   |
| T | : | /do/  | /ré/ |
| B | : | la    | ré   |

On note aussi que la 3ce du premier accord (le /do/ au ténor) évolue
vers la fondamentale du deuxième accord (le /ré/).

Exemple avec un accord de préparation contenant la 7e :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /sol/ | /fa/ |
| A | : | mi    | mi    | ré   |
| T | : | si    | /do/  | /ré/ |
| B | : | sol   | la    | ré   |


** Accords à base de quintes

Un accord à base de quintes peut se résoudre sur l’octave de la
fondamentale, devenant ainsi une doublure :

#+ATTR_HTML: :class plat
| S | : | /si/ | /la/ |
| A | : | mi   | mi   |
| B | : | la   | la   |

ou sur la tierce de la fondamentale, devenant ainsi un accord parfait :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | mi   | mi   |
| B | : | la   | la   |

La fondamentale peut aussi glisser pour aboutir sur une doublure :

#+ATTR_HTML: :class plat
| S | : | si   | si   |
| A | : | mi   | mi   |
| B | : | /la/ | /si/ |

ou sur un accord parfait renversé :

#+ATTR_HTML: :class plat
| S | : | si   | si    |
| A | : | mi   | mi    |
| B | : | /la/ | /sol/ |

Enfin, la quinte de l’accord peut glisser pour obtenir un accord de
7e incomplet :

#+ATTR_HTML: :class plat
| S | : | fa   | fa   |
| A | : | /do/ | /ré/ |
| B | : | sol  | sol  |


*** Disposition en quartes

Le raisonnement est analogue pour les dispositions en quartes :

#+ATTR_HTML: :class plat
| S | : | fa    | fa   |
| A | : | do    | do   |
| B | : | /sol/ | /fa/ |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | fa    | fa   |
| A | : | do    | do   |
| B | : | /sol/ | /la/ |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /sol/ |
| A | : | do   | do    |
| B | : | sol  | sol   |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /mi/ |
| A | : | do   | do   |
| B | : | sol  | sol  |


* Dynamique des ornements

#+TOC: headlines 1 local


** Introduction

Une note ornementale peut être :

  - consonante, si elle peut s’interpréter comme note consonante de l’accord en cours
  - dissonante, sinon
    + note essentielle dissonante
    + note étrangère dissonante

Dans tous les cas, une note ornementale joue un rôle dynamique dans la
polyphonie. On utilise donc les termes de préparation et de résolution
pour toutes les notes ornementales :

  - la préparation est un accord qui prépare l’arrivée de la note ornementale
  - la résolution fait évoluer la note ornementale au sein d’un nouvel accord

Ces deux phases peuvent s’effectuer :

  - par mouvement conjoint variable
  - par intégration dans l’accord concerné
  - par mouvement(s) polyphonique(s) élégant(s)

Ce processus est donc en tout point similaire à celui de la
préparation et de la résolution de dissonance.


** Accentuation

Les ornements harmoniques sont généralement placés sur temps fort ou
partie forte de temps.

Les ornements mélodiques sont généralement placés sur temps faible ou
partie faible de temps.


** Pédale

Lorsqu’une *pédale* est présente, elle est en général alternativement
dissonante et consonante par rapport aux accords qui se succèdent sur
les autres voix.

Une pédale est souvent préparée en s’intégrant à un premier accord et
en perdurant après sa disparition. Le dernier accord qui se superpose
à une pédale lui est en général également consonant.

Autrement dit, une pédale est généralement préparée et résolue par
intégration.


** Retard

#+TOC: headlines 1 local

*** Préparation

Par définition, un retard est préparé par intégration. Idéalement, la
durée de la préparation est au moins égale à la durée du retard.


*** Phase active

Pour ne pas gâcher l’effet de surprise, on évite de faire entendre
simultanément le retard et sa résolution, sauf si une des conditions
suivantes est satisfaite :

  - la résolution est placée à la basse
  - la résolution est discrète, voir les techniques de [[file:musica-03-clavier.org::#section:camouflage][camouflage]]

Le retard est sur un temps plus accentué que sa résolution :

| Retard       | Résolution   |
|--------------+--------------|
| temps fort   | temps médian |
| temps fort   | temps faible |
| temps médian | temps faible |


*** Résolution

Un retard se résout généralement en évoluant par mouvement conjoint
variable vers une note du nouvel accord. Suivant le sens du mouvement,
on distingue :

  - le *retard supérieur* qui se résout en descendant
  - le *retard inférieur* qui se résout en montant

Par exemple, dans l’enchaînement suivant, le /ré/ au soprano est un
retard supérieur qui se résout en descendant vers le /do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /do/ |
| A | : | sol  | sol  | sol  |
| T | : | sol  | mi   | mi   |
| B | : | si   | do   | do   |

Autre exemple où le /fa/ est un retard inférieur qui se résout en
montant vers le /sol/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /sol/ |
| A | : | la   | ré   | ré    |
| T | : | do   | si   | si    |
| B | : | fa   | sol  | sol   |


** Anticipation

Une anticipation se résout par intégration dans l’accord suivant.

Par exemple, dans l’enchaînement suivant, le /mi/ au soprano est une
ancicipation :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


** Appogiature

L’appogiature n’est généralement pas préparée.

Elle se résout le plus souvent par mouvement conjoint.


* Dynamique du rythme

#+TOC: headlines 1 local

** Introduction

Le rythmes les plus stables sont les *rythmes réguliers* :

  - *rapides*, avec au moins une note par temps
  - *lents*, avec de longues notes continues

Tous les autres rythmes correspondent à des tensions qui peuvent se
résoudre sur l’une ou l’autre de ces configurations. Il va de soi que
les rythmes lents sont plutôt réservés à la fin d’une phrase et les
rythmes rapides au coeur d’un mouvement.


** Accentuation

Un temps fort peut être accentué par :

  - une intensité plus forte de la note qui l’entame
  - un accent mélodique


** Mesures

Une mesure irrégulière constitue une tension par rapport à une mesure
régulière proche.


** Fluidité

Un rythme sec produit une tension par rapport à un rythme fluide qui
lui est proche. Par exemple, la suite :

#+ATTR_HTML: :class plat
| C cs C | cs N N |

produira une tension puis une détente, et la suite :

#+ATTR_HTML: :class plat
| C cs N | C cs N | =...= |

un cycle de tension et de détente.


** Syncopes

Le schéma générique d’une syncope applique la structure générique de
tension et résolution. En voici un exemple :

  - *Préparation* : rythme régulier, à raison d’une note par temps

  - *Tension* : on gomme la première note de la mesure suivante en la
    remplaçant par la prolongation de la note précédente

  - *Résolution* : la mélodie reprend le rythme régulier précédent, à
    raison d’une note par temps

Toutes les variations partant de ce cas d’école sont bien entendu
possibles. La phase de préparation est bien entendu optionnelle.

Voici des exemples de réalisation où la mesure compte deux temps d’une
noire chacun :

|         | Préparation | Tension     | Résolution |
|---------+-------------+-------------+------------|
| Syncope | N N         | N N‿N N     | N N        |
| Syncopé | N N         | N N‿N N‿N N | N N        |


*** Contraste

Il arrive souvent qu’on mette en relief une syncope en introduisant un
contraste entre la voix syncopée et une voix sans syncope qui assure
la régularité rythmique. Dans ce cas, la tension découle naturellement
du contraste.


** Contretemps

On peut considérer qu’une syncope est un rythme fluide et que le
contretemps est le rythme sec associé. Par conséquent, le contretemps
offre une tension rythmique encore plus importante que celle de la
syncope. On peut imaginer un prototype de tension — relaxation :

  - Rythme régulier de préparation, une note par temps

  - Tension : syncope

  - Tension accrue : contretemps associé

  - Légère détente : retour à la syncope

  - Détente finale : retour au rythme régulier

chaque étape étant optionnelle.


* Stratification

#+TOC: headlines 1 local


** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique
tonalité, on parle de *musique tonale*. Il existe donc à tout moment
un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.


** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre tonalité, distincte
de celles des autres groupes, on parle de musique polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.


** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.


** Polyrythmie

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de *polymétrie* ou de *rythmes polymétriques*.


**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| X | : | § | χ | ¶ | χ | ¶ | χ |
| Y | : | § | χ | χ | ¶ | χ | χ |
