
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 01 : Monocorde
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Pré en bulles

#+TOC: headlines 1 local


** Introduction

#+ATTR_HTML: :class lettrine
La texture musicale repose sur un arbre théorique dont les racines
sont aussi simples que les ramifications sont denses et complexes.
Rien d’étonnant à ce qu’une variété aussi prodigieuse de styles puisse
nidifier dans une arborescence aussi tortueuse. Une des clés de voûte
de toute polyphonie consiste en la dualité Mélodie — Harmonie, la
première semant ses notes consécutivement et la seconde simultanément.
Mais tout n’est pas aussi simple car les deux concepts se rejoignent :
la mélodie forme une harmonie implicite en laissant s’accumuler dans
la mémoire de l’auditeur des notes qui s’agrègent ; de son coté,
l’harmonie suggère dans sa superposition une mélodie implicite qui
peut se voir développée par la suite. Au croisement se situe l'Accord,
groupe abstrait de notes pouvant donner lieu de par ses nombreuses
dispositions possibles à une foule de thèmes musicaux différents.

La richesse de cette tapisserie provient également des intéractions
entre les cycles d’intervalles, où se mêlent à nouveau mélodie et
harmonie. C’est aussi dans ces cycles, souvent partiellement
implicites, que les accords s’enchaînent, formant une ronde
perpétuelle. La tonalité ajoute son grain de sel via le concept de
fonction tonale, concept qui permet de voyager via une autre dimension
d’accord en accord, aussi facilement que l’on se transporte sur une
autre planète dans la littérature fantastique. Partout en musique,
nous sommes en présence d’un système que l’on pourrait qualifier de
logique floue, dans la mesure où chaque élément musical peut se
présenter sous différentes formes, où chaque forme peut être
interprétée comme provenant d’éléments distincts.

Avec le rythme s’ajoute à cet improbable treillis la notion de
fractale, un même motif rythmique pouvant être appliqué à des échelles
temporelles différentes. La structure rythmique elle-même s’articule
sur différents niveaux, chacun d’entre-eux étant décomposé en un
nombre variable de subdivisions. Cette nouvelle dimension possède une
identité propre, indépendante de la mélodie de laquelle elle se décale
régulièrement, formant ainsi syncopes et anacrouses. Comme vous pouvez
le constater, les trois facettes du triptyque formé par la Mélodie,
l’Harmonie et le Rythme s’entremêlent, formant sous nos yeux ébahis ce
miracle que l’on nomme Musique.

Vous ayant averti de l’univers vertigineux qui vous attend, il me
reste à conclure cette introduction en vous souhaitant une bonne
lecture.


** Remerciements

Je tiens à remercier :

  - Michel Baron, qui nous offre [[http://michelbaron.com][un cours d’harmonie, de contrepoint et de fugue]].

  - Sylvain Caron, pour son [[http://www.mapageweb.umontreal.ca/caronsy/harmonie_1/html/plan_harm1.html][cours d’harmonie tonale]].

  - Luce Beaudet, qui nous fait partager [[http://bw.musique.umontreal.ca/][une méthode simple et puissante]]
    permettant d’analyser le discours harmonique générique, ainsi que les marches.

  - Alan Belkin, pour [[http://alanbelkinmusic.com/site/en/][sa vision éclairante de la composition musicale]].
    Vous trouverez sur son site de riches réflexions sur la forme
    musicale, l’orchestration, la composition, l’harmonie et le
    contrepoint.

  - Le [[http://www.chmtl.indiana.edu][CHTML (Centre d’histoire de la théorie musicale et de la littérature)]],
    bibliothèque numérique qui contient de précieux traités.



* Acoustique

#+TOC: headlines 1 local


** Introduction

Le son étant la brique fondamentale sur laquelle repose tout l’édifice
musical, il semble raisonnable d’entamer ce traité par son étude.


** Onde

Un son est une *onde acoustique*, c’est-à-dire une onde de pression,
simple ou complexe, perceptible par nos oreilles.


*** Élémentaire

Une *onde acoustique élémentaire*, ou plus simplement *onde
élémentaire*, est une onde acoustique au tracé sinusoïdal.

Ce type d’onde permet de rendre compte d’un grand nombre de phénomènes
physiques, que ce soit sous sa forme simple (pendule, cercle en
rotation, ...) ou par superposition (corde vibrante, tuyau
sonore, ...).

#+BEGIN_CENTER
⁂
#+END_CENTER

Un *son élémentaire* est un son associé à une onde acoustique
élémentaire.


*** Fréquence

La *fréquence* d’une onde élémentaire (et donc du son élémentaire
associé) est égale au nombre de cycles qu’elle parcourt en une
seconde. L’unité de fréquence est le *Herz*, symbolisé par *Hz* :

#+BEGIN_CENTER
/N/ Herz = /N/ Hz = /N/ cycles par secondes
#+END_CENTER


**** Aigu et grave

La hauteur d’un son élémentaire est déterminée par la fréquence de
l’onde élémentaire associée :

  - plus la fréquence est grande, plus le son est *haut* ou *aigu*
  - plus la fréquence est petite, plus le son est *bas* ou *grave*


*** Son composé

Si la plupart des sons utilisables musicalement sont trop complexes
pour être étudiés en tant que tels, il est généralement possible de
les considérer comme des superpositions de sons élémentaires, ce qui
facilite grandement leur analyse.

On nomme *son composé* un tel son décomposable en sons élémentaires.


* Harmoniques naturelles

#+TOC: headlines 1 local


** Introduction

Nous étudions dans ce chapitre l’organisation interne (fréquences &
amplitudes) des sons composés.


** Fréquences

Dans de nombreux cas, les fréquences des sons élémentaires
constitutifs d’un son composé sont des multiples entiers de la
fréquence la plus grave /F_0/ :

#+ATTR_HTML: :class plat
| 1 F_0 | — | 2 F_0 | — | 3 F_0 | — | 4 F_0 | — | 5 F_0 | — | 6 F_0 | — | 7 F_0 | — | 8 F_0 | — | 9 F_0 | — | =...= |

La fréquence /F_0/ est alors appelée *fréquence fondamentale*, tandis
que les autres fréquences du son composé sont appelées *harmoniques
naturelles*.

#+BEGIN_CENTER
⁂
#+END_CENTER

En exprimant le tout comme des multiples de /F_0/, on obtient :

#+ATTR_HTML: :class plat
| 1 | — | 2 | — | 3 | — | 4 | — | 5 | — | 6 | — | 7 | — | 8 | — | 9 | — | =...= |

Les ratios des fréquences consécutives sont donc, dans l’ordre :

#+ATTR_HTML: :class plat
| 2 / 1 | — | 3 / 2 | — | 4 / 3 | — | 5 / 4 | — | 6 / 5 | — | 7 / 6 | — | 8 / 7 | — | 9 / 8 | — | =...= |


** Timbre

Si les fréquences des harmoniques naturelles sont des multiples
entiers de la fréquence fondamentale, les amplitudes relatives de ces
harmoniques varient considérablement d’un instrument de musique à un
autre. Une combinaison particulière de ces amplitudes produit ce qu’on
appelle le *timbre* d’un son. C’est donc le timbre qui donne un
caractère reconnaissable à chaque instrument.


** Notes

Une *note* est un son dont la fréquence fondamentale est donnée. Plus
cette fréquence est élevée, plus la note est dite *aiguë* ; plus cette
fréquence est faible et plus la note est dite *grave*.

On utilise aussi une analogie basée sur la *hauteur* :

  - une note est dite plus haute ou supérieure à une autre lorsqu’elle est plus aiguë
  - une note est dite moins haute ou inférieure à une autre lorsqu’elle est plus grave

Suivant le même raisonnement, une suite de note sera dite :

  - montante si elle évolue vers l’aigu
  - descendante si elle évolue vers le grave

Une note correspond donc à une certaine fréquence fondamentale. Le
timbre du son reste par contre libre et dépend de l’instrument utilisé
pour jouer la note.


*** Diapason

Le diapason est une note qui permet à tous les musiciens de
synchroniser leurs instruments. Cette note est définie par sa
fréquence fondamentale, fixée par convention à :

#+BEGIN_CENTER
440 Hz
#+END_CENTER


** Intervalles

Un *intervalle* représente la distance qui sépare deux notes. Or,
l’expérience nous montre que l’oreille mesure la distance entre deux
notes par le ratio de leurs fréquences fondamentales.

L’intervalle qui sépare deux notes est donc formellement défini par le
ratio de leurs fréquences fondamentales.


*** Purs

Un *intervalle pur* est un intervalle dont le ratio de fréquence est
*identique* à l’un des ratios intervenant dans les harmoniques
naturelles.

Le tableau ci-dessous reprend les noms et ratios de fréquences des
intervalles purs les plus importants :

| Intervalle     | Ratio |   |   |
|----------------+-------+---+---|
| Octave         | 2 / 1 | = | 2 |
| Quinte         | 3 / 2 |   |   |
| Quarte         | 4 / 3 |   |   |
| Tierce majeure | 5 / 4 |   |   |
| Tierce mineure | 6 / 5 |   |   |

Les noms donnés à ces intervalles peuvent paraître étranges à ce
stade ; nous en verrons plus loin l’origine.


* Octave

#+TOC: headlines 1 local


** Introduction

L’octave est le premier des intervalles apparaissant dans les
harmoniques naturelles, ce qui lui confère un statut particulièrement
important en musique.

À ce titre, l’octave est utilisée pour simplifier considérablement le
problème de la répartition des notes de musique sur la plage des
fréquences audibles.

On commence par définir un ensemble de notes incluses dans une octave
de référence, c’est-à-dire dans une plage allant d’une fréquence
donnée /F_0/ à son double /2 F_0/. Les notes des octaves environnantes
s’obtiennent ensuite facilement en multipliant ou en divisant par 2 la
fréquence d’une des notes de l’octave de référence. En répétant ce
processus de multiplication ou de division, on peut alors construire
autant d’octaves qu’on le souhaite, du très grave au très aigu.

Le tableau suivant schématise cette construction, en partant d’une
note de fréquence /F/ dans l’octave de référence :

#+ATTR_HTML: :class plat
| Octave +N :           |               |       | 2^N F   |       |       |
| =...=                 | =...=         | =...= | =...=   | =...= | =..=  |
| Octave +3 :           | 2 × 2 × 2 F   | =     | 2^3 F   | =     | 8 F   |
| Octave +2 :           | 2 × 2 F       | =     | 2^2 F   | =     | 4 F   |
| Octave +1 :           | 2 F           |       |         |       |       |
| Octave de référence : | F             |       |         |       |       |
| Octave − 1 :          | F / 2         |       |         |       |       |
| Octave − 2 :          | F / 2 / 2     | =     | F / 2^2 | =     | F  4  |
| Octave − 3 :          | F / 2 / 2 / 2 | =     | F / 2^3 | =     | F  8  |
| =...=                 | =...=         | =...= | =...=   | =...= | =...= |
| Octave − N :          |               |       | F / 2^N |       |       |


** Notes naturelles

Le système musical le plus répandu comporte sept notes par octave. Ces
notes sont appelées *notes naturelles*, ou encore *notes diatoniques*.
Elles sont nommées par convention comme suit, de la plus grave à la
plus aiguë :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

Le /do/ est parfois appelé /ut/, ce qui nous donne les notes :

#+BEGIN_CENTER
ut   ré   mi   fa   sol   la   si
#+END_CENTER


*** Alphabet

Il existe une notation alternative, basée sur les premières lettres de
l’alphabet, le « A » correspondant à la note « la ». On a
l’équivalence :

#+ATTR_HTML: :class plat
| la  | = | A |
| si  | = | B |
| do  | = | C |
| ré  | = | D |
| mi  | = | E |
| fa  | = | F |
| sol | = | G |


** Notation

Il existe plusieurs façons de préciser l’octave d’une note.


*** Jusqu’à quatre octaves

Il est possible d’employer une notation basée sur :

  - des lettres minuscules et majuscules
  - des barres inférieures

On peut alors différencier jusqu’à 4 octaves :

|       | Octaves | Notes                               |
|-------+---------+-------------------------------------|
| Aigu  |       4 | do ré mi fa sol la si               |
|       |       3 | DO RÉ MI FA SOL LA SI               |
|       |       2 | _do_ _ré_ _mi_ _fa_ _sol_ _la_ _si_ |
| Grave |       1 | _DO_ _RÉ_ _MI_ _FA_ _SOL_ _LA_ _SI_ |

Il est possible d’utiliser des versions restreintes de cette notation
pour différencier un nombre d’octaves moins grand, l’essentiel étant
de respecter l’ordre du tableau ci-dessus.


**** Deux octaves

Pour rendre compte de 2 octaves, on a par exemple :

|       | Octaves | Notes                 |
|-------+---------+-----------------------|
| Aigu  |       2 | do ré mi fa sol la si |
| Grave |       1 | DO RÉ MI FA SOL LA SI |


**** Trois octaves

Lorsqu’on souhaite différencier 3 octaves, on a par exemple :

|       | Octaves | Notes                               |
|-------+---------+-------------------------------------|
| Aigu  |       3 | do ré mi fa sol la si               |
|       |       2 | DO RÉ MI FA SOL LA SI               |
| Grave |       1 | _do_ _ré_ _mi_ _fa_ _sol_ _la_ _si_ |


*** Générique

Étant donnée une note /X/ de fréquence /F/, on définit :

  - /X^+1/ : la note de fréquence /2 F/ située à l’octave supérieure
  - /X^-1/ : la note de fréquence /F / 2/ située à l’octave inférieure

On généralise cette notation à un nombre naturel /N = 1, 2, 3, .../
quelconque par :

#+ATTR_HTML: :class plat
| /X^+N/ : | la note de fréquence /2^N F/ située       /N/ octaves au-dessus de l’octave de référence |
| /X^-N/ : | la note de fréquence /F / 2^N/ située        /N/ octaves sous l’octave de référence      |


** Implicite

En théorie musicale, la mention de l’octave d’une note est souvent
omise. Dans ce cas, c’est soit que cette octave :

  - n’a aucune incidence sur le raisonnement en cours
  - peut se déduire aisément du contexte


*** Suites croissantes

Une *suite croissante* est une série de notes triées de la plus grave
à la plus aiguë.

Dans une suite croissante, la mention de l’octave peut être omise, car
il est évident que chaque /do/ franchi nous oblige à monter au moins
d’une octave.

#+BEGIN_CENTER
⁂
#+END_CENTER

Nous allons illustrer le principe de déduction de l’octave au moyen de
la suite croissante suivante :

#+BEGIN_CENTER
fa sol la si do ré mi fa
#+END_CENTER

Nous savons que le /do/ doit être plus aigu que le /si/ qui le
précède. Ces deux notes ne peuvent donc pas faire partie d’une même
octave, sans quoi le /si/ serait plus aigu que le /do/ par convention.
On en déduit que le /do/ est situé dans une octave supérieure à celle
du /si/. En conséquence, la fin de la suite :

#+BEGIN_CENTER
do ré mi fa
#+END_CENTER

est située dans une octave supérieure à celle du début :

#+BEGIN_CENTER
fa sol la si
#+END_CENTER

Notons que le /do/ n’a pas besoin d’être explicitement présent dans la
suite pour provoquer la hausse d’une octave. Ainsi, dans :

#+BEGIN_CENTER
fa sol la ré mi fa
#+END_CENTER

le /do/ est implicitement franchi :

#+BEGIN_CENTER
fa sol la (si *do*) ré mi fa
#+END_CENTER

En conséquence, la fin de la suite :

#+BEGIN_CENTER
ré mi fa
#+END_CENTER

est située dans une octave supérieure à celle du début :

#+BEGIN_CENTER
fa sol la
#+END_CENTER


**** Exemples

Pour être bien sûr d’y voir clair, voici quelques exemples de suites
croissantes avec octave implicite, puis leur version équivalente avec
l’octave explicitée :

| Octave implicite         | Octave explicite          |
|--------------------------+---------------------------|
| fa sol la si do ré mi fa | FΑ SOL LA SI do ré mi fa  |
| fa la do mi sol si ré    | _fa_ _la_ DO MI SOL SI ré |
| fa do sol ré la mi       | _FA_ _do_ _sol_ RÉ LA mi  |


* Tempérament

#+TOC: headlines 1 local


** Introduction

Comme aucune répartition de notes diatoniques n’est à même de former
uniquement des intervalles purs, on est forcé de faire des
approximations. Une répartition particulière de ces approximations,
qui conditionne l’agencement précis des notes diatoniques, est appelé
*tempérament*.

Ce chapitre présente quelques tempéraments fondamentaux.


** Pythagore

Le *tempérament de Pythagore*, ou *tempérament pythagoricien*, est
construit à partir de quintes pures.

On part d’une note de référence /do/ de fréquence /F_0/ et on
construit les autres notes via des intervalles de quintes pures. La
fréquence est donc à chaque fois multipliée ou divisée par /3 / 2/ :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| Q 7         | 243 / 32        |
| Q 6         | 81 / 16         |
| Q 5         | 27 / 8          |
| Q 4         | 9 /4            |
| Q 3         | 3 / 2           |
| Q 2         | 1               |
| Q 1         | 2 / 3           |

On ramène ensuite toutes les fréquences à l’intérieur de l’octave de
référence [F_0, 2 F_0], en les multipliant ou en les divisant par
la puissance de deux adéquate. On les trie ensuite de la plus grave à
la plus aiguë, ce qui nous donne, avec les plus graves en bas du
tableau :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| Q 7         | 243 / 128       |
| Q 5         | 27 /16          |
| Q 3         | 3 / 2           |
| Q 1         | 4 / 3           |
| Q 6         | 81 / 64         |
| Q 4         | 9 / 8           |
| Q 2         | 1               |

Nous pouvons à présent nommer les notes définies par ces fréquences,
suivant la convention usuelle /do, ré, mi, fa, sol, la, si/ :

| Notes | Identifiant | Fréquence / F_0 |
|-------+-------------+-----------------|
| si    | Q 7         | 243 / 128       |
| la    | Q 5         | 27 / 16         |
| sol   | Q 3         | 3 / 2           |
| fa    | Q 1         | 4 / 3           |
| mi    | Q 6         | 81 / 64         |
| ré    | Q 4         | 9 / 8           |
| do    | Q 2         | 1               |

Il ne reste alors plus qu’à ajouter un /do/ de fréquence /2 F_0/ pour
compléter l’octave, ce qui nous donne :

| Notes | Fréquence / F_0 |
|-------+-----------------|
| do    | 2               |
| si    | 243 / 128       |
| la    | 27 / 16         |
| sol   | 3 / 2           |
| fa    | 4 / 3           |
| mi    | 81 / 64         |
| ré    | 9 / 8           |
| do    | 1               |


*** Tons et demi-tons

Les ratios de fréquences entre les notes naturelles consécutives du
tempérament de Pythagore s’écrivent :

| Notes    | Ratios    |
|----------+-----------|
| si — do  | 256 / 243 |
| la — si  | 9 / 8     |
| sol — la | 9 / 8     |
| fa — sol | 9 / 8     |
| mi — fa  | 256 / 243 |
| ré — mi  | 9 / 8     |
| do — ré  | 9 / 8     |

On constate que ces écarts peuvent être classés en deux catégories
suivant leur taille. Les plus grands sont appelés *tons* et les plus
petits *demi-tons*. En effet, on peut vérifier que parcourir deux
demi-tons revient plus ou moins à parcourir un ton.

Le tableau suivant nous donne la liste de tous les tons et demi-tons
du tempérament de Pythagore :

| Type      | Ratio    | Notes    |
|-----------+----------+----------|
| Tons      | 9 / 8    | do — ré  |
|           |          | ré — mi  |
|           |          | fa — sol |
|           |          | sol — la |
|           |          | la — si  |
| Demi-tons | 256 /243 | mi — fa  |
|           |          | si — do  |

En faisant les comptes, on en déduit que le tempérament de Pythagore
contient *5 tons* et *2 demi-tons* par *octave*.


*** Quintes

En réarrangeant les notes du tempérament de Pythagore suivant les
intervalles de quintes qui ont mené à sa formation :

#+ATTR_HTML: :class plat
| Q 1 | — | Q 2 |
| Q 2 | — | Q 3 |
| Q 3 | — | Q 4 |
| Q 4 | — | Q 5 |
| Q 5 | — | Q 6 |
| Q 6 | — | Q 7 |

on obtient les intervalles :

#+ATTR_HTML: :class plat
| fa  | — | do  |
| do  | — | sol |
| sol | — | ré  |
| ré  | — | la  |
| la  | — | mi  |
| mi  | — | si  |

En considérant chacun de ces intervalles de *quinte*, on constate
qu’ils englobent tous *cinq* notes :

#+ATTR_HTML: :class plat
| /fa — do/  | : | fa  | sol | la  | si  | do  |
| /do — sol/ | : | do  | ré  | mi  | fa  | sol |
| /sol — ré/ | : | sol | la  | si  | do  | ré  |
| /ré — la/  | : | ré  | mi  | fa  | sol | la  |
| /la — mi/  | : | la  | si  | do  | ré  | mi  |
| /mi — si/  | : | mi  | fa  | sol | la  | si  |

C’est de là que vient le nom de quinte, *quintus* signifiant cinquième
en latin.


**** Pureté

Par construction, presque toutes les quintes formées par les notes
naturelles du tempérament de Pythagore sont pures. La seule exception
est la quinte /si — fa/, qui est une quinte diminuée.


*** Tierces


**** Majeures

Aucune tierce majeure pure n’est présente dans le tempérament de
Pythagore, on ne dispose que d’approximations.

Pour ne citer qu’un exemple, le ratio de fréquence entre les notes
/do/ et /mi/ est de :

#+BEGIN_CENTER
81 / 64 = 1.265625
#+END_CENTER

à comparer avec le ratio de la tierce majeure pure :

#+BEGIN_CENTER
5 / 4 = 80 / 64 = 1.25
#+END_CENTER


**** Mineures

Il en va de même pour les tierces mineures. Ainsi, le ratio de
fréquence entre les notes /mi/ et /sol/ est de :

#+BEGIN_CENTER
3 / 2 × 64 / 81 = 32 / 27 = 1.1851 =...=
#+END_CENTER

à comparer avec le ratio de la tierce mineure pure :

#+BEGIN_CENTER
6 / 5 = 1.2
#+END_CENTER


** Zarlino

Le *tempérament de Zarlino*, ou *tempérament zarlinien*, est construit
à partir de quintes et de tierces majeures pures.

On part d’une note de référence /do/ de fréquence /F_0/ et on
construit les autres notes via des intervalles de quintes et de
tierces majeures pures. On commence par construire les quintes pures
autour de la note de référence :

| Fréquence / F_0 |
|-----------------|
| *3 / 2*         |
| *1*             |
| *2 / 3*         |

On multiplie ensuite chacune des fréquences déjà obtenues par le
facteur /5 / 4/, ce qui nous donne trois nouvelles notes situées une
tierce majeure pure au-dessus des trois premières :

| Fréquence / F_0 |
|-----------------|
| 15 / 8          |
| *3 / 2*         |
| 5 / 4           |
| *1*             |
| 10 / 12         |
| *2 / 3*         |

On complète le tempérament en ajoutant une dernière note, située une
quinte pure au-dessus de la fréquence /3 / 2 F_0/, c’est-à-dire à
/9 / 4 F_0/ :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| T 7         | 9 / 4           |
| T 6         | 15 / 8          |
| T 5         | *3 / 2*         |
| T 4         | 5 / 4           |
| T 3         | *1*             |
| T 2         | 5 / 6           |
| T 1         | *2 / 3*         |

On ramène ensuite toutes les fréquences à l’intérieur de l’octave de
référence [F_0, 2 F_0], en les multipliant ou en les divisant par la
puissance de deux adéquate. On les trie ensuite de la plus grave à la
plus aiguë, ce qui nous donne, avec les plus graves en bas du
tableau :

| Identifiant | Fréquence / F_0 |
|-------------+-----------------|
| T 6         | 15 / 8          |
| T 2         | 5 / 3           |
| T 5         | *3 / 2*         |
| T 1         | *4 / 3*         |
| T 4         | 5 / 4           |
| T 7         | 9 / 8           |
| T 3         | *1*             |

Nous pouvons à présent nommer les notes définies par ces fréquences,
suivant la convention usuelle /do, ré, mi, fa, sol, la, si/ :

| Notes | Identifiant | Fréquence / F_0 |
|-------+-------------+-----------------|
| si    | T 6         | 15 / 8          |
| la    | T 2         | 5 / 3           |
| sol   | T 5         | *3 / 2*         |
| fa    | T 1         | *4 / 3*         |
| mi    | T 4         | 5 / 4           |
| ré    | T 7         | 9 / 8           |
| do    | T 3         | *1*             |

Il ne reste alors plus qu’à ajouter un /do/ de fréquence /2 F_0// pour
compléter l’octave, ce qui nous donne :

| Notes | Fréquence / F_0 |
|-------+-----------------|
| do    | 2               |
| si    | 15 / 8          |
| la    | 5 / 3           |
| sol   | *3 / 2*         |
| fa    | *4 / 3*         |
| mi    | 5 / 4           |
| ré    | 9 / 8           |
| do    | *1*             |


*** Tons et demi-tons

Les ratios de fréquences entre les notes naturelles consécutives du
tempérament de Zarlino s’écrivent :

| Notes    | Ratios  |
|----------+---------|
| si — do  | 16 / 15 |
| la — si  | 9 / 8   |
| sol — la | 10 / 9  |
| fa — sol | 9 / 8   |
| mi — fa  | 16 / 15 |
| ré — mi  | 10 / 9  |
| do — ré  | 9 / 8   |

On constate que ces écarts peuvent être classés en deux catégories
suivant leur taille. Les plus grands sont appelés *tons* et les plus
petits *demi-tons*. En effet, on peut vérifier que parcourir deux
demi-tons revient plus ou moins à parcourir un ton.

Le tableau suivant nous donne la liste de tous les tons et demi-tons
du tempérament de Zarlino :

| Type      | Ratio   | Notes    |
|-----------+---------+----------|
| Tons      | 9 / 8   | do — ré  |
|           | 10 / 9  | ré — mi  |
|           | 9 / 8   | fa — sol |
|           | 10 / 9  | sol — la |
|           | 9 / 8   | la — si  |
| Demi-tons | 16 / 15 | mi — fa  |
|           |         | si — do  |

En faisant les comptes, on en déduit que le tempérament de Zarlino
contient *5 tons* et *2 demi-tons* par *octave*.

On remarque que tous les tons ne sont pas identiques, certains valant
/9 / 8/ et les autres /10 / 9/. Cette légère différence peut poser
problème lorsqu’on souhaite déplacer la structure musicale d’une
hauteur de son à l’autre.


*** Quintes

Par construction, la plupart des quintes du tempérament de Zarlino
sont pures. Il y a toutefois des exceptions. Ainsi, l’intervalle
séparant le /ré/ du /la/ vaut :

#+BEGIN_CENTER
5 / 3 × 8 / 9 = 40 / 27 = 1.4814 =...=
#+END_CENTER

à comparer avec le ratio de la quinte pure :

#+BEGIN_CENTER
3 / 2 = 1.5
#+END_CENTER


*** Tierces


**** Majeures

En réarrangeant les notes du tempérament de Zarlino suivant les
intervalles de tierces majeures qui ont mené à sa formation :

#+ATTR_HTML: :class plat
| T 1 | — | T 2 |
| T 3 | — | T 4 |
| T 5 | — | T 6 |

on obtient les intervalles :

#+ATTR_HTML: :class plat
| fa  | — | la |
| do  | — | mi |
| sol | — | si |

En considérant chacun de ces intervalles de *tierce majeure*, on
constate qu’ils englobent tous *trois* notes :

#+ATTR_HTML: :class plat
| /fa — la/  | : | fa  | sol | la |
| /do — mi/  | : | do  | ré  | mi |
| /sol — si/ | : | sol | la  | si |

C’est de là que vient le nom de tierce, *tertius* signifiant troisième
en latin.


**** Mineures

En considérant les autres intervalles contenant trois notes, on
obtient la liste :

#+ATTR_HTML: :class plat
| /ré — fa/  | : | ré | mi | fa  |
| /mi — sol/ | : | mi | fa | sol |
| /la — do/  | : | la | si | do  |
| /si — ré/  | : | si | do | ré  |

En calculant les ratios de fréquences de ces intervalles, on vérifie
qu’ils sont tous identiques à /6 / 5/, à l’exception de l’intervalle
/ré — fa/ qui vaut :

#+BEGIN_CENTER
4 / 3 × 8 / 9 = 32 / 27 = 1.1851 =...=
#+END_CENTER

à comparer avec le ratio de la tierce mineure pure :

#+BEGIN_CENTER
6 / 5 = 1.2
#+END_CENTER

Ces *tierces mineures* (pures ou approximatives) englobent donc aussi
*trois* notes.


** Tempérament égal

Le *tempérament égal* est construite à partir de l’approximation qui
consiste à considérer que :

  - tous les demi-tons sont identiques
  - chaque ton vaut exactement deux demi-tons

Une octave contient donc :

#+ATTR_HTML: :class plat
| 5 tons + 2 demi-tons | = | 5 × 2 demi-tons | + | 2 demi-tons |
|                      | = | 10 demi-tons    | + | 2 demi-tons |
|                      | = | 12 demi-tons    |   |             |

Le tempérament égal est donc construit en divisant l’octave en douze
demi-tons identiques. Ce demi-ton est appelé demi-ton tempéré et noté
*DT*.

On a les relations :

#+ATTR_HTML: :class plat
| 1 demi-ton = 1 DT |
| 1 ton = 2 DT      |

Sauf indication contraire, nous utiliserons dans la suite le
tempérament égal.


*** Ratios

Puisqu’il y a 12 demi-tons tempérés par octave, le rapport de
fréquence d’un demi-ton tempéré $RFDT$ vérifie :

#+ATTR_HTML: :class plat
RFDT^{12} = 2

Le rapport $RFDT$ correspond donc à un douxième de l’octave :

#+ATTR_HTML: :class plat
RFDT = 2^{1/12}

On en déduit que l’écart /E/ en demi-tons tempérés qui sépare deux
notes est lié au ratio de leurs fréquences /F_1/ et /F_2/ par les
relations :

#+ATTR_HTML: :class plat
F_2 / F_1 = 2^{E/12}

La relation inverse nous donne l’écart en demi-tons à partir d’un
rapport de fréquence quelconque :

#+ATTR_HTML: :class plat
E = 12 × log_2 ( F_2 / F_1 )


** Comparatif

Le tableau suivant compare les différentes tempéraments. Les
fréquences sont exprimées en multiples de /F_0/, fréquence du /do/ :

| Notes | Pythagore | Zarlino | Tempérament égal |
|-------+-----------+---------+------------------|
| si    | 1.8984    | 1.875   | 1.8877           |
| la    | 1.6875    | 1.6667  | 1.6818           |
| sol   | 1.5       | 1.5     | 1.4983           |
| fa    | 1.3333    | 1.3333  | 1.3348           |
| mi    | 1.2656    | 1.25    | 1.26             |
| ré    | 1.125     | 1.125   | 1.1225           |
| do    | 1         | 1       | 1                |


* Chromatisme

#+TOC: headlines 1 local


** Introduction

Dans la suite croissante suivante :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si   do
#+END_CENTER

toutes les notes consécutives sont séparées par un ton, à l’exception
des écarts :

#+ATTR_HTML: :class plat
| mi | — | fa |
| si | — | do |

qui valent chacun un demi-ton.

Que se passerait-il si nous voulions obtenir temporairement un écart
d’un demi-ton entre deux notes habituellement séparées par un ton
entier ? Il faudrait alors hausser ou abaisser d’un demi-ton un des
notes impliquées. C’est à celà que servent les altérations haussières
et baissières.

Considérons pour illustrer les notes /fa/ et /sol/, qui sont séparées
par un ton. Si nous haussons le /fa/ d’un demi-ton, ou si nous
abaissons le /sol/ d’un demi-ton, l’écart /fa — sol/ se réduit à un
demi-ton comme souhaité.


** Dièses et bémols

Une note naturelle peut être altérée :

  - d’un demi-ton vers le haut par un *dièse* (symbolisé par un *#*)
  - d’un demi-ton vers le bas par un *bémol* (symbolisé par un *b*)

Une note ainsi altérée est dite *chromatique*.

Les altérations d’une note /X/ s’écrivent donc :

| Altération               | Nom   | Notation |
|--------------------------+-------+----------|
| Haussière : + 1 demi-ton | Dièse | X^{#}    |
| Baissière : − 1 demi-ton | Bémol | X^b      |


*** Doubles

Il arrive que le contexte musical emploie déjà abondamment une note
altérée par un dièse ou un bémol. Dans ce cas, comment distinguer une
altération temporaire supplémentaire ? C’est là qu’interviennent les
altérations doubles. Une note naturelle peut être altérée :

  - de deux demi-tons vers le haut par un double dièse (symbolisé par
    un *##*)
  - de deux demi-tons vers le bas par un double bémol (symbolisé par
    un *bb*)

Les altérations doubles d’une note /X/ s’écrivent donc :

| Altération                | Nom          | Notation |
|---------------------------+--------------+----------|
| Haussière : + 2 demi-tons | Double dièse | X^{##}   |
| Baissière : − 2 demi-tons | Double bémol | X^bb     |


** Enharmonie

Dans un tempérament égal, une *enharmonie* est constitutée de deux
notes de même fréquence obtenues par des altérations différentes.

Deux notes liées par une enharmonie sont qualifiées d’*enharmoniques*.


*** Notes séparées par un ton

Choisissons deux notes séparées par un ton, par exemple /do/ et /ré/.
Les demi-tons tempérés étant tous égaux et valant exactement la moitié
d’un ton, on réalise qu’on obtient la même hauteur de son en haussant
le /do/ d’un demi-ton qu’en abaissant le /ré/ d’un demi-ton. On a
donc :

#+BEGIN_CENTER
do^{#}  =  ré^b
#+END_CENTER

On dit alors que le /do #/ est *l’enharmonie* du /ré^b/.


*** Notes séparées par un demi-ton

Choisissons deux notes séparées par un demi-ton, par exemple /mi/ et
/fa/.

Les demi-tons tempérés étant tous égaux, on réalise qu’on obtient la
même hauteur de son en haussant le /mi/ d’un demi-ton qu’en jouant le
/fa/. On a donc l’enharmonie :

#+BEGIN_CENTER
mi^{#}  =  fa
#+END_CENTER

En suivant un raisonnement analogue, on réalise qu’on obtient la même
hauteur de son en abaissant le /fa/ d’un demi-ton qu’en jouant le
/mi/. On a donc l’enharmonie :

#+BEGIN_CENTER
fa^b  =  mi
#+END_CENTER


*** Relations enharmoniques

En appliquant le raisonnement précédent à toutes les notes, on obtient
les relations enharmoniques :

| do^{#}  | = | ré^b  |
| ré^{#}  | = | mi^b  |
| mi      | = | fa^b  |
| mi^{#}  | = | fa    |
| fa^{#}  | = | sol^b |
| sol^{#} | = | la^b  |
| la^{#}  | = | si^b  |
| si      | = | do^b  |
| si^{#}  | = | do    |


*** Autres tempéraments

On peut étendre les relations enharmoniques à un tempérament
quelconque. Il faut toutefois garder à l’esprit que, lorsque le
tempérament n’est pas égal, les fréquences de deux notes enharmoniques
ne sont pas rigoureusement identiques, un léger décalage de fréquence
est observé.


** Listes

Voici la liste des notes naturelles et chromatiques réunies et
triées :

| Notes   |        | Écarts en demi-tons par rapport au *do* grave |
|---------+--------+-----------------------------------------------|
| do      | si^{#} |                                            12 |
| si      | do^b   |                                            11 |
| la^{#}  | si^b   |                                            10 |
| la      |        |                                             9 |
| sol^{#} | la^b   |                                             8 |
| sol     |        |                                             7 |
| fa^{#}  | sol^b  |                                             6 |
| fa      | mi^{#} |                                             5 |
| mi      | fa^b   |                                             4 |
| ré^{#}  | mi^b   |                                             3 |
| ré      |        |                                             2 |
| do^{#}  | ré^b   |                                             1 |
| do      | si^{#} |                                             0 |


*** Doubles

Voici quelques exemples d’altérations doubles :

| Notes    |        | Écarts en demi-tons par rapport au *do* grave |
|----------+--------+-----------------------------------------------|
| la       | si^bb  |                                             9 |
| la^{##}  | si     |                                            11 |
| sol      | la^bb  |                                             7 |
| sol^{##} | la     |                                             9 |
| fa       | sol^bb |                                             5 |
| fa^{##}  | sol    |                                             7 |
| mi^b     | fa^bb  |                                             3 |
| mi^{##}  | fa^{#} |                                             6 |
| ré^{##}  | mi     |                                             4 |
| ré       | mi^bb  |                                             2 |
| do^{##}  | ré     |                                             2 |
| do       | ré^bb  |                                             0 |


* Intervalles

#+TOC: headlines 1 local


** Introduction

Le nom d’un intervalle est lié au nombre de notes qu’il parcourt,
notes extrêmes inclues. L’intervalle entre deux notes identiques porte
le nom particulier *d’unisson*.

/Remarque/ : les intervalles étant présentés sous formes de suites
croissantes, l’octave est généralement implicite.

Voici la liste des principaux intervalles :

|        Nombre de | Intervalle  |                |                                                |
| notes parcourues | Nom         | Notes extrêmes | Notes parcourues                               |
|------------------+-------------+----------------+------------------------------------------------|
|                1 | Unisson     | do — do        | do                                             |
|                2 | Seconde     | do — ré        | do ré                                          |
|                3 | Tierce      | do — mi        | do ré mi                                       |
|                4 | Quarte      | do — fa        | do ré mi fa                                    |
|                5 | Quinte      | do — sol       | do ré mi fa sol                                |
|                6 | Sixte       | do — la        | do ré mi fa sol la                             |
|                7 | Septième    | do — si        | do ré mi fa sol la si                          |
|                8 | Octave      | do — do        | do ré mi fa sol la si do                       |
|                9 | Neuvième    | do — ré        | do ré mi fa sol la si do ré                    |
|               10 | Dixième     | do — mi        | do ré mi fa sol la si do ré mi                 |
|               11 | Onzième     | do — fa        | do ré mi fa sol la si do ré mi fa              |
|               12 | Douzième    | do — sol       | do ré mi fa sol la si do ré mi fa sol          |
|               13 | Treizième   | do — la        | do ré mi fa sol la si do ré mi fa sol la       |
|               14 | Quatorzième | do — si        | do ré mi fa sol la si do ré mi fa sol la si    |
|               15 | Quinzième   | do — do        | do ré mi fa sol la si do ré mi fa sol la si do |


** Justes

Certains intervalles recouvrent un nombre de demi-tons qui reste fixe,
et ce quelle que soit la note de départ choisie. Ces intervalles sont
parfois qualifiés de *justes*, bien que ce qualificatif reste
généralement implicite.


*** Unisson

Parmi ces intervalles, citons l’ *unisson*, qui contient invariablement
zéro demi-tons :

| Unissons  | Écarts en demi-tons |
|-----------+---------------------|
| do — do   |                   0 |
| ré — ré   |                   0 |
| mi — mi   |                   0 |
| fa — fa   |                   0 |
| sol — sol |                   0 |
| la — la   |                   0 |
| si — si   |                   0 |


*** Octave

Vient ensuite *l’octave*, qui contient invariablement douze
demi-tons :

| Octaves   | Écarts en demi-tons |
|-----------+---------------------|
| do — do   |                  12 |
| ré — ré   |                  12 |
| mi — mi   |                  12 |
| fa — fa   |                  12 |
| sol — sol |                  12 |
| la — la   |                  12 |
| si — si   |                  12 |


*** Quinte

Nous avons ensuite la *quinte*, qui contient invariablement sept
demi-tons, à une seule exception près, qui en contient six :

| Quintes  | Écarts en demi-tons |
|----------+---------------------|
| do — sol |                   7 |
| ré — la  |                   7 |
| mi — si  |                   7 |
| fa — do  |                   7 |
| sol — ré |                   7 |
| la — mi  |                   7 |
| si — fa  |                   6 |

Toutes les quintes sont donc justes, à l’exception de /si — fa/, qui
sera appelée *quinte diminuée*.


*** Quarte

Nous avons ensuite la *quarte*, qui contient invariablement cinq
demi-tons, à une seule exception près, qui en contient six :

| Quartes  | Écarts en demi-tons |
|----------+---------------------|
| sol — do |                   5 |
| la — ré  |                   5 |
| si — mi  |                   5 |
| do — fa  |                   5 |
| ré — sol |                   5 |
| mi — la  |                   5 |
| fa — si  |                   6 |

Toutes les quartes sont donc justes, à l’exception de /fa — si/, qui
sera appelée *quarte augmentée*, ou encore *triton*, parce qu’elle
parcourt trois tons.


*** Récapitulation

| Intervalles justes | Abréviations | Exemple        | Écarts en |
|                    |              | Notes extrêmes | demi-tons |
|--------------------+--------------+----------------+-----------|
| Unisson            | 1son         | do — do        |         0 |
| Quarte             | 4te          | do — fa        |         5 |
| Quinte             | 5te          | do — sol       |         7 |
| Octave             | 8ve          | do — do        |        12 |


** Majeurs, mineurs

Les intervalles dont l’amplitude varie avec la note de départ choisie
sont qualifiés de *majeurs* ou de *mineurs* suivant le nombre de
demi-tons qui sépare les notes extrêmes. Les intervalles majeurs sont
alors un demi-ton plus grand que les intervalles mineurs.

Dans le cadre des intervalles, on utilise les abréviations :

| Majeur | M |
| Mineur | m |

Le tableau suivant reprend les intervalles majeurs et mineurs contenus
dans l’octave :

| Intervalles      | Abréviations | Exemple        | Écarts en |
|                  |              | Notes extrêmes | demi-tons |
|------------------+--------------+----------------+-----------|
| Seconde mineure  | 2de m        | mi — fa        |         1 |
| Seconde majeure  | 2de M        | do — ré        |         2 |
| Tierce mineure   | 3ce m        | la — do        |         3 |
| Tierce majeure   | 3ce M        | do — mi        |         4 |
| Sixte mineure    | 6te m        | la — fa        |         8 |
| Sixte majeure    | 6te M        | do — la        |         9 |
| Septième mineure | 7e m         | la — sol       |        10 |
| Septième majeure | 7e M         | do — si        |        11 |


** Augmentés, diminués

Un intervalle *augmenté* est un intervalle juste ou majeur auquel on a
ajouté un demi-ton, ou un intervalle mineur auquel on a ajouté deux
demi-tons.

Un intervalle *diminué* est un intervalle juste ou mineur auquel on a
retiré un demi-ton, ou un intervalle majeur auquel on a retiré deux
demi-tons.


*** Altérations

L’ajout ou le retrait d’un demi-ton s’effectue généralement en
altérant une des notes qui constituent l’intervalle.

Notons toutefois que l’intervalle /fa — si/ est une quarte augmentée,
sans qu’aucune altération soit présente. Il en va de même pour
l’intervalle renversé /si — fa/, qui est une quinte diminuée.

Dans le cadre des intervalles, on utilise les abréviations :

| Augmenté | aug |
| Diminué  | dim |


*** Augmentés

Voici quelques exemples d’intervalles augmentés :

| Intervalles        | Abréviations | Exemple        | Écarts en |
|                    |              | Notes extrêmes | demi-tons |
|--------------------+--------------+----------------+-----------|
| Unisson augmenté   | 1son aug     | do — do^{#}    |         1 |
|                    |              | do^b — do      |           |
| Seconde augmentée  | 2de aug      | do — ré^{#}    |         3 |
|                    |              | mi^b — fa^{#}  |           |
| Tierce augmentée   | 3ce aug      | do — mi^{#}    |         5 |
|                    |              | la^b — do^{#}  |           |
| Quarte augmentée   | 4te aug      | do — fa^{#}    |         6 |
|                    |              | fa — si        |           |
| Quinte augmentée   | 5te aug      | do — sol^{#}   |         8 |
|                    |              | la^b — mi      |           |
| Sixe augmentée     | 6te aug      | do — la^{#}    |        10 |
|                    |              | la^b — fa^{#}  |           |
| Septième augmentée | 7e aug       | do — si^{#}    |        12 |
|                    |              | la^b — sol^{#} |           |
| Octave augmentée   | 8ve aug      | do — do^{#}    |        13 |
|                    |              | la^b — la      |           |


**** Triton

La quarte augmentée est aussi appelée *triton* (abréviation *3ton*),
parce qu’elle parcourt trois tons.


*** Diminués

Voici quelques exemples d’intervalles diminués :

| Intervalles       | Abréviations | Exemple        | Écarts en |
|                   |              | Notes extrêmes | demi-tons |
|-------------------+--------------+----------------+-----------|
| Seconde diminuée  | 2de dim      | mi — fa^b      |         0 |
|                   |              | do^{#} — ré^b  |           |
| Tierce diminuée   | 3ce dim      | la — do^b      |         2 |
|                   |              | do^{#} — mi^b  |           |
| Quarte diminuée   | 4te dim      | la — ré^b      |         4 |
| Quinte diminuée   | 5te dim      | do — sol^b     |         6 |
|                   |              | si — fa        |           |
| Sixte diminuée    | 6te dim      | la^{#} — fa    |         7 |
|                   |              | do^{#} — la^b  |           |
| Septième diminuée | 7e dim       | la^{#} — sol   |         9 |
|                   |              | do^{#} — si^b  |           |
| Octave diminuée   | 8ve dim      | do — do^b      |        11 |
|                   |              | do^{#} — do    |           |


*** Relations enharmoniques

Les intervalles augmentés et diminués sont souvent liés
enharmoniquement à des intervalles majeurs, mineurs ou justes. Par
exemple, la septième augmentée :

#+BEGIN_CENTER
do — si^{#}
#+END_CENTER

est enharmoniquement équivalente à l’octave :

#+BEGIN_CENTER
do — do
#+END_CENTER

La sixte augmentée :

#+BEGIN_CENTER
do — la^{#}
#+END_CENTER

est enharmoniquement équivalente à la septième mineure :

#+BEGIN_CENTER
do — si^b
#+END_CENTER

La seconde diminuée :

#+BEGIN_CENTER
do^{#} — ré^b
#+END_CENTER

est enharmoniquement équivalente à l’unisson :

#+BEGIN_CENTER
do^{#} — do^{#}
#+END_CENTER


** Sur-augmentés, sur-diminués

Un intervalle *sur-augmenté* est un intervalle juste ou majeur auquel
on a ajouté deux demi-tons.

Un intervalle *sur-diminué* est un intervalle juste ou mineur auquel
on a retiré deux demi-tons.

Dans le cadre des intervalles, on utilise les abréviations :

| Sur-augmenté | suraug |
| Sur-diminué  | surdim |


*** Sur-augmentés

Voici quelques exemples d’intervalles sur-augmentés :

| Intervalles           | Abréviations | Exemple        | Écarts en |
|                       |              | Notes extrêmes | demi-tons |
|-----------------------+--------------+----------------+-----------|
| Unisson sur-augmenté  | 1son suraug  | do^b — do^{#}  |         2 |
| Seconde sur-augmentée | 2de suraug   | sol^b — la^{#} |         4 |
| Tierce sur-augmentée  | 3ce suraug   | do^b — mi^{#}  |         6 |


*** Sur-diminués

Voici quelques exemples d’intervalles sur-diminués :

| Intervalles         | Abréviations | Exemple        | Écarts en |
|                     |              | Notes extrêmes | demi-tons |
|---------------------+--------------+----------------+-----------|
| Tierce sur-diminuée | 3ce surdim   | mi^{#} — sol^b |         1 |
| Quarte sur-diminuée | 4te surdim   | ré^{#} — sol^b |         3 |
| Quinte sur-diminuée | 5te surdim   | do^{#} — sol^b |         5 |


*** Relations enharmoniques

Par exemple, l’unisson sur-augmenté :

#+BEGIN_CENTER
ré^b — ré^{#}
#+END_CENTER

est enharmoniquement équivalent à la seconde majeure :

#+BEGIN_CENTER
do^{#} — ré^{#}
#+END_CENTER


** Renversements

Les intervalles les plus importants sont ceux compris entre l’unisson
et l’octave inclus. Chacun d’entre-eux est relié à un intervalle
associé appelé *renversement*, qui le complète pour former une
octave :

| Intervalle       | Renversement     | Exemple    |              |
|                  |                  | Intervalle | Renversement |
|------------------+------------------+------------+--------------|
| Unisson          | Octave           | do — do    | do — do      |
| Seconde mineure  | Septième majeure | mi — fa    | fa — mi      |
| Seconde majeure  | Septième mineure | do — ré    | ré — do      |
| Tierce mineure   | Sixte majeure    | la — do    | do — la      |
| Tierce majeure   | Sixte mineure    | do — mi    | mi — do      |
| Quarte           | Quinte           | do — fa    | fa — fa      |
| Quarte augmentée | Quinte diminuée  | fa — si    | si — fa      |
| Quinte diminuée  | Quarte augmentée | si — fa    | fa — si      |
| Quinte           | Quarte           | do — sol   | sol — do     |
| Sixte mineure    | Tierce majeure   | la — fa    | fa — la      |
| Sixte majeure    | Tierce mineure   | do — la    | la — do      |
| Septième mineure | Seconde majeure  | la — sol   | sol — la     |
| Septième majeure | Seconde mineure  | do — si    | si — do      |
| Octave           | Unisson          | do — do    | do — do      |


** Redoublements

Lorsqu’on ajoute une octave à un intervalle, on obtient le
*redoublement* de cet intervalle. On dit alors que l’intervalle
original est *redoublé*.

Voici les redoublements des intervalles compris entre l’unisson et
l’octave :

| Intervalle       | Redoublement        | Écarts en demi-tons |
|------------------+---------------------+---------------------|
| Unisson          | Octave              |                  12 |
| Seconde mineure  | Neuvième mineure    |                  13 |
| Seconde majeure  | Neuvième majeure    |                  14 |
| Tierce mineure   | Dixième mineure     |                  15 |
| Tierce majeure   | Dixième majeure     |                  16 |
| Quarte           | Onzième             |                  17 |
| Quarte augmentée | Onzième augmentée   |                  18 |
| Quinte diminuée  | Douzième diminuée   |                  18 |
| Quinte           | Douzième            |                  19 |
| Sixte mineure    | Treizième mineure   |                  20 |
| Sixte majeure    | Treizième majeure   |                  21 |
| Septième mineure | Quatorzième mineure |                  22 |
| Septième majeure | Quatorzième majeure |                  23 |
| Octave           | Quinzième           |                  24 |


*** Généralisation

Par généralisation, un intervalle redoublé peut désigner l’intervalle
original auquel on ajoute une ou plusieurs octaves.


** Purs

Les *intervalles purs* sont des intervalles dont les ratios de
fréquences sont issus de la série des harmoniques naturelles. On
considère donc des multiples entiers de la fréquence de base, par
exemple en partant de /do/ :

#+ATTR_HTML: :class plat
| /Octaves/   | : |  0 |  1 |   1 |  2 |  2 |   2 |    2 |  3 |  3 |  3 |      3 |   3 | =...= |
| /Notes/     | : | do | do | sol | do | mi | sol | si^b | do | ré | mi | fa^{#} | sol | =...= |
| /Multiples/ | : |  1 |  2 |   3 |  4 |  5 |   6 |    7 |  8 |  9 | 10 |     11 |  12 | =...= |

On en déduit les ratios de fréquences des intervalles purs :

| Intervalle harmonique | Octaves |   | Notes |        | Multiples |    | Ratio de fréquence |
|-----------------------+---------+---+-------+--------+-----------+----+--------------------|
| Unisson               |       0 | 0 | do    | do     |         1 |  1 | 1                  |
| Octave                |       0 | 1 | do    | do     |         1 |  2 | 2                  |
| Quinte                |       1 | 1 | do    | sol    |         2 |  3 | 3 / 2              |
| Quarte                |       1 | 2 | sol   | do     |         3 |  4 | 4 / 3              |
| Tierce majeure        |       2 | 2 | do    | mi     |         4 |  5 | 5 / 4              |
| Tierce mineure        |       2 | 2 | mi    | sol    |         5 |  6 | 6 / 5              |
| Sixte majeure         |       1 | 2 | sol   | mi     |         3 |  5 | 5 / 3              |
| Sixte mineure         |       2 | 3 | mi    | do     |         5 |  8 | 8 / 5              |
| Septième mineure      |       2 | 2 | do    | si^b   |         4 |  7 | 7 / 4              |
| Seconde majeure       |       3 | 3 | do    | ré     |         8 |  9 | 9 / 8              |
| Quarte augmentée      |       3 | 3 | do    | fa^{#} |         8 | 11 | 11 / 8             |


*** Intervalles dérivés

D’autres intervalles dérivent des intervalles purs.


**** Seconde mineure

La seconde mineure empilée sur une tierce majeure forme une quarte :

#+BEGIN_CENTER
5 / 4 × 2de m = 4 / 3
#+END_CENTER

On en déduit une première valeur :

#+BEGIN_CENTER
2de m = 4 / 3 × 4 / 5 = 16 / 15
#+END_CENTER

La seconde mineure empilée sur une tierce mineure forme une tierce
majeure :

#+BEGIN_CENTER
6 / 5 × 2de m = 5 / 4
#+END_CENTER

On en déduit une autre valeur, proche de la première :

#+BEGIN_CENTER
2de m = 5 / 6 × 5 / 4 = 25 / 24
#+END_CENTER


**** Septième majeure

La septième majeure empilée sur une seconde mineure forme une octave :

#+BEGIN_CENTER
16 / 15 × 7e M = 2
#+END_CENTER

En partant de la première valeur de la seconde mineure, on en déduit :

#+BEGIN_CENTER
7e M = 2 × 15 / 16 = 15 / 8
#+END_CENTER

En partant de la seconde valeur de la seconde mineure, on en déduit :

#+BEGIN_CENTER
7e M = 2 × 24 / 25 = 48 / 25
#+END_CENTER


**** Quinte diminuée

En empilant deux tierces mineures, on obtient une quinte diminuée :

#+BEGIN_CENTER
5te dim = (6 / 5)^2
#+END_CENTER

On en déduit que :

#+BEGIN_CENTER
5te dim = 36 / 25
#+END_CENTER


**** Quinte augmentée

En empilant deux tierces majeures, on obtient une quinte augmentée :

#+BEGIN_CENTER
5te aug = (5 / 4)^2
#+END_CENTER

On en déduit que :

#+BEGIN_CENTER
5te aug = 25 / 16
#+END_CENTER


**** Septième diminuée

En empilant trois tierces mineures, on obtient une septième diminuée :

#+BEGIN_CENTER
7te dim = (6 / 5)^3
#+END_CENTER

On en déduit que :

#+BEGIN_CENTER
7te dim = 216 / 125
#+END_CENTER


*** Synthèse

Le tableau ci-dessous nous donne la liste des intervalles purs,
simples et dérivés, et la comparaison avec les intervalles issus des
tempéraments pythagoriciens, zarliniens ou égal. Notons que dans le
cas du tempérament zarlinien, l’intervalle peut varier légèrement
suivant les notes choisies ; nous ne reprenons dans ce cas que les
choix les plus proches de l’intervalle pur correspondant :

| Intervalle        | Ratio de fréquence |               |           |              |
|                   | Pur                | Pythagoricien | Zarlinien | Tempéré égal |
|-------------------+--------------------+---------------+-----------+--------------|
| Unisson           | 1                  | 1             | 1         |            1 |
| Seconde mineure   | 16 / 15            | 256 / 243     | 16 / 15   |       1.0595 |
|                   | 25 / 24            |               |           |              |
| Seconde majeure   | 9 / 8              | 9 / 8         | 9 / 8     |       1.1225 |
|                   |                    |               | 10 / 9    |              |
| Tierce mineure    | 6 / 5              | 32 / 27       | 6 / 5     |       1.1892 |
| Tierce majeure    | 5 / 4              | 81 / 64       | 5 / 4     |       1.2599 |
| Quarte            | 4 / 3              | 4 / 3         | 4 / 3     |       1.3348 |
| Quarte augmentée  | 11 / 8             |               |           |       1.4142 |
| Quinte diminuée   | 36 / 25            | 1024 / 729    | 36 / 25   |       1.4142 |
| Quinte            | 3 / 2              | 3 / 2         | 3 / 2     |       1.4983 |
| Quinte augmentée  | 25 / 16            | 6561 / 4096   | 25 / 16   |       1.5874 |
| Sixte mineure     | 8 / 5              | 128 / 81      | 8 / 5     |       1.5874 |
| Sixte majeure     | 5 / 3              | 27 / 16       | 5 / 3     |       1.6817 |
| Septième diminuée | 216 / 125          |               |           |       1.6817 |
| Septième mineure  | 7 / 4              | 16 / 9        | 16 / 9    |       1.7818 |
| Septième majeure  | 15 / 8             | 243 / 128     | 15 / 8    |       1.8877 |
|                   | 48 / 25            |               |           |              |
| Octave            | 2                  | 2             | 2         |            2 |

** Cycles

Lorsqu’on parcourt le tempérament égal en maintenant, à l’octave près,
un intervalle constant entre les notes successives (naturelles ou
chromatiques), on finit par revenir au point de départ, formant ainsi
un *cycle*.


*** Quintes

Le cycle le plus important est le cycle des quintes. Il s’écrit :

#+BEGIN_CENTER
=...= mi = fa^b do^b sol^b ré^b la^b mi^b si^b
fa do sol ré la mi si
fa^{#} do^{#} sol^{#} ré^{#} la^{#} mi^{#} si^{#} = do =...=
#+END_CENTER

Mais comme /sol # = la^b/, la suite :

#+BEGIN_CENTER
sol^{#} = la^b mi^b si^b fa do sol ré la mi si fa^{#} do^{#} sol^{#} = la^b
#+END_CENTER

forme déjà un cycle complet de 12 notes.


**** Représentation

On représente souvent le cycle des quintes disposé sur un cercle (ici
très approximatif) :

#+ATTR_HTML: :class plat
|        |         |        | do     |     |    |    |
|        |         | fa     |        | sol |    |    |
|        | la^{#}  |        |        |     | ré |    |
| ré^{#} |         |        |        |     |    | la |
|        | sol^{#} |        |        |     | mi |    |
|        |         | do^{#} |        | si  |    |    |
|        |         |        | fa^{#} |     |    |    |

La forme enharmonique remplace les dièses par les bémols :

#+ATTR_HTML: :class plat
|      |      |      | do    |     |    |    |
|      |      | fa   |       | sol |    |    |
|      | si^b |      |       |     | ré |    |
| mi^b |      |      |       |     |    | la |
|      | la^b |      |       |     | mi |    |
|      |      | ré^b |       | si  |    |    |
|      |      |      | sol^b |     |    |    |


**** Pures

Si on décide d’utiliser des quintes pures à la place de quintes
intégrées dans un tempérament égal, on ne revient jamais tout à fait
au point de départ. On parle alors de *spirale* des quintes.


* Transposition

#+TOC: headlines 1 local


** Introduction

*Transposer* un groupe de notes consiste à le déplacer d’un intervalle
donné vers l’aigu ou vers le grave.

Au cours d’une *transposition*, chaque note est donc décalée d’un même
intervalle vers le haut ou vers le bas.


** Conservation des intervalles internes

Nous allons montrer que les intervalles internes d’un groupe de notes
sont conservés lors d’une transposition.

Illustrons cette idée en prenant comme exemple la suite de notes suivante :

#+BEGIN_CENTER
do   mi   ré
#+END_CENTER

Si nous transposons cette suite d’une quinte vers le haut, nous obtenons :

#+BEGIN_CENTER
sol   si   la
#+END_CENTER

On constate que les intervalles internes sont identiques avant et
après transposition :

| Notes originales | Notes transposées |
|------------------+-------------------|
| do — mi          | sol — si          |
| mi — ré          | si — la           |


*** Raisonnement générique

Fixons une note de référence /R/ à une fréquence choisie /F_R/. Nous
pouvons à présent définir un groupe quelconque de notes par :

#+ATTR_HTML: :class plat
| /Notes/  | : | N_1 | N_2 | N_3 | =...= | N_m |
| /Écarts/ | : | E_1 | E_2 | E_3 | =...= | E_m |

où les /E_1/, /E_2/, ..., /E_m/ sont les nombres de demi-tons séparant
les notes du groupe de la note de référence /R/. Plus précisément :

#+BEGIN_CENTER
/E_k/ = nombre de demi-tons entre la note /N_k/ et la note de référence /R/
#+END_CENTER

Si nous transposons ce groupe d’un intervalle contenant /D/ demi-tons,
nous obtenons la suite :

#+ATTR_HTML: :class plat
| /Notes/  | : | T_1     | T_2     | T_3     | =...= | T_m     |
| /Écarts/ | : | E_1 + D | E_2 + D | E_3 + D | =...= | E_m + D |

Choisissons deux notes /N_A/ et /N_B/ dans la suite originale. Ces
notes correspondent aux notes transposées /T_A/ et /T_B/, qui forment
un intervalle après transposition :

#+ATTR_HTML: :class plat
| ( E_B + D )  −  ( E_A + D ) | = | E_B + D  −  E_A − D |

Les /D/ se simplifient, et on a finalement :

#+BEGIN_CENTER
E_B  −  E_A
#+END_CENTER

qui n’est rien d’autre que l’intervalle avant transposition.

Les intervalles internes au groupe sont donc bien conservés par la
transposition.


** Transposition à l’octave

L’octave est l’intervalle le plus important en musique. Il semble donc
logique d’examiner en premier les transpositions par octave ascendante
ou descendante.


*** Ascendante

Nous allons transposer les notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

d’une octave vers l’aigu. Pour ce faire, on commence par parcourir
huit notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| Départ | ⟼   | ⟼   | ⟼   | ⟼   | ⟼   | ⟼   | Arrivée |
| 1      | 2   | 3   | 4   | 5   | 6   | 7   | 8       |
| do     | ré  | mi  | fa  | sol | la  | si  | do      |
| ré     | mi  | fa  | sol | la  | si  | do  | ré      |
| mi     | fa  | sol | la  | si  | do  | ré  | mi      |
| fa     | sol | la  | si  | do  | ré  | mi  | fa      |
| sol    | la  | si  | do  | ré  | mi  | fa  | sol     |
| la     | si  | do  | ré  | mi  | fa  | sol | la      |
| si     | do  | ré  | mi  | fa  | sol | la  | si      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | do      |                  12 |
| ré     | ré      |                  12 |
| mi     | mi      |                  12 |
| fa     | fa      |                  12 |
| sol    | sol     |                  12 |
| la     | la      |                  12 |
| si     | si      |                  12 |

Toutes les octaves contiennent 12 demi-tons et sont donc justes.

La transposition par octave ascendante ne nécessite donc aucune
altération parmi les notes naturelles.


*** Descendante

Nous allons transposer les notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

d’une octave vers le grave. Pour ce faire, on commence par parcourir
huit notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| Départ | ⟼   | ⟼   | ⟼   | ⟼   | ⟼   | ⟼   | Arrivée |
| 1      | 2   | 3   | 4   | 5   | 6   | 7   | 8       |
| do     | si  | la  | sol | fa  | mi  | ré  | do      |
| ré     | do  | si  | la  | sol | fa  | mi  | ré      |
| mi     | ré  | do  | si  | la  | sol | fa  | mi      |
| fa     | mi  | ré  | do  | si  | la  | sol | fa      |
| sol    | fa  | mi  | ré  | do  | si  | la  | sol     |
| la     | sol | fa  | mi  | ré  | do  | si  | la      |
| si     | la  | sol | fa  | mi  | ré  | do  | si      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | do      |                  12 |
| ré     | ré      |                  12 |
| mi     | mi      |                  12 |
| fa     | fa      |                  12 |
| sol    | sol     |                  12 |
| la     | la      |                  12 |
| si     | si      |                  12 |

Toutes les octaves contiennent 12 demi-tons et sont donc justes.

La transposition par octave descendante ne nécessite donc aucune
altération parmi les notes naturelles.


*** Conclusion

Une transposition à l’octave ne nécessite aucune altération parmi les
notes naturelles.


** Transposition à la quinte

Après l’octave, la quinte est l’intervalle le plus important en
musique. Nous allons donc examiner les transpositions par quinte
ascendante ou descendante.


*** Ascendante

Nous allons transposer les notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

d’une quinte vers l’aigu. Pour ce faire, on commence par parcourir
cinq notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| Départ | ⟼   | ⟼   | ⟼   | Arrivée |
| 1      | 2   | 3   | 4   | 5       |
| do     | ré  | mi  | fa  | sol     |
| ré     | mi  | fa  | sol | la      |
| mi     | fa  | sol | la  | si      |
| fa     | sol | la  | si  | do      |
| sol    | la  | si  | do  | ré      |
| la     | si  | do  | ré  | mi      |
| si     | do  | ré  | mi  | fa      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | sol     |                   7 |
| ré     | la      |                   7 |
| mi     | si      |                   7 |
| fa     | do      |                   7 |
| sol    | ré      |                   7 |
| la     | mi      |                   7 |
| si     | fa      |                   6 |

Toutes les quintes contiennent 7 demi-tons et sont donc justes, à
l’exception de la quinte ascendante /si — fa/ qui n’en contient que
6 ; il s’agit donc d’une quinte diminuée.

Comme l’intervalle de transposition doit être strictement le même pour
toutes les notes, on doit remédier à cette situation en augmentant de
1 le nombre de demi-tons de la quinte diminuée. On est donc amenés à
altérer vers le haut le /fa/ final, qui devient un /fa^{#}/. La
transposition devient alors :

#+ATTR_HTML: :class plat
| Départ      | ⟼ | Arrivée |
| do	  |   | sol     |
| ré	  |   | la      |
| mi	  |   | si      |
| fa	  |   | do      |
| sol	 |   | ré      |
| la	  |   | mi      |
| si	  |   | fa^{#}  |

La transposition par quinte ascendante ne nécessite donc qu’une seule
altération parmi les notes naturelles.


*** Descendante

Nous allons transposer les notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

d’une quinte vers le grave. Pour ce faire, on commence par parcourir
cinq notes en partant de chacune des notes naturelles :

#+ATTR_HTML: :class plat
| Départ | ⟼   | ⟼   | ⟼   | Arrivée |
| 1      | 2   | 3   | 4   | 5       |
| do     | si  | la  | sol | fa      |
| ré     | do  | si  | la  | sol     |
| mi     | ré  | do  | si  | la      |
| fa     | mi  | ré  | do  | si      |
| sol    | fa  | mi  | ré  | do      |
| la     | sol | fa  | mi  | ré      |
| si     | la  | sol | fa  | mi      |

On examine ensuite le nombre de demi-tons séparant les notes de départ
et d’arrivée :

| Départ | Arrivée | Nombre de demi-tons |
|--------+---------+---------------------|
| do     | fa      |                   7 |
| ré     | sol     |                   7 |
| mi     | la      |                   7 |
| fa     | si      |                   6 |
| sol    | do      |                   7 |
| la     | ré      |                   7 |
| si     | mi      |                   7 |

Toutes les quintes contiennent 7 demi-tons et sont donc justes, à
l’exception de la quinte descendante /fa — si/ qui n’en contient que
6 ; il s’agit donc d’une quinte diminuée.

Comme l’intervalle de transposition doit être strictement le même pour
toutes les notes, on doit remédier à cette situation en augmentant de
1 le nombre de demi-tons de la quinte diminuée. On est donc amenés à
altérer vers le bas le /si/ final, qui devient un /si^b/. La
transposition devient alors :

#+ATTR_HTML: :class plat
| Départ      | ⟼ | Arrivée |
| do	  |   | fa      |
| ré	  |   | sol     |
| mi	  |   | la      |
| fa	  |   | si^b    |
| sol	 |   | do      |
| la	  |   | ré      |
| si	  |   | mi      |

La transposition par quinte descendante ne nécessite donc qu’une seule
altération parmi les notes naturelles.


*** Conclusion

Une transposition à la quinte ne nécessite qu’une seule altération
parmi les notes naturelles.


** Combinaison

Il est possible de *combiner* deux ou plusieurs transpositions afin de
former une transposition complexe.

Inversément, il est possible de *décomposer* une transposition simple
en passant par une ou plusieurs étapes intermédiaires, ce qui nous
donne alors une transposition complexe reproduisant le même résultat.


*** Deux quintes

Nous allons opérer une double transposition de quinte ascendante sur
la série des notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

Chaque étape transpose donc ces notes d’une quinte vers l’aigu. La
première transposition nous mène à une étape intermédiaire, et la
seconde transposition aux notes finales :

#+ATTR_HTML: :class plat
| Départ | ⟼     | Intermédiaire | ⟼     | Arrivée |
|        | 5te ↑ |               | 5te ↑ |         |
| do     |       | sol           |       | ré      |
| ré     |       | la            |       | mi      |
| mi     |       | si            |       | fa^{#}  |
| fa     |       | do            |       | sol     |
| sol    |       | ré            |       | la      |
| la     |       | mi            |       | si      |
| si     |       | fa^{#}        |       | do^{#}  |

À ce stade, quelques remarques s’imposent :

  - chaque étape nécessite une nouvelle altération, ce qui produit
    deux altérations au total (le /fa^{#}/ et le /do^{#}/)

  - la transposition combinée équivaut à une transposition simple
    d’une /neuvième majeure ascendante/

La neuvième majeure correspondant au redoublement de la seconde
majeure, il est possible de décomposer la transposition associée en
une /octave ascendante/ suivie d’une /seconde majeure ascendante/.

Comme la transposition à l’octave n’engendre aucune altération, on en
déduit que la transposition *d’une seconde majeure ascendante* est
équivalente, du point de vue des altérations produites, à une
transposition combinée de *deux quintes ascendantes*.

Nous disposons donc d’un procédé permettant de déduire facilement les
altérations produites par une transposition d’une seconde majeure vers
l’aigu.


*** Trois quintes

Nous allons opérer une triple transposition de quinte ascendante sur
la série des notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

Chaque étape transpose donc ces notes d’une quinte vers l’aigu :

#+ATTR_HTML: :class plat
| Départ | ⟼     | Inter 1 | ⟼     | Inter 2 | ⟼     | Arrivée |
|        | 5te ↑ |         | 5te ↑ |         | 5te ↑ |         |
| do     |       | sol     |       | ré      |       | la      |
| ré     |       | la      |       | mi      |       | si      |
| mi     |       | si      |       | fa^{#}  |       | do^{#}  |
| fa     |       | do      |       | sol     |       | ré      |
| sol    |       | ré      |       | la      |       | mi      |
| la     |       | mi      |       | si      |       | fa^{#}  |
| si     |       | fa^{#}  |       | do^{#}  |       | sol^{#} |

À ce stade, quelques remarques s’imposent :

  - la transposition combinée produit trois altérations au total
    (/fa^{#}/, /do^{#}/, /sol^{#}/)

  - la transposition combinée équivaut à une transposition simple
    d’une /treizième majeure ascendante/

Il est possible de décomposer la transposition associée à la treizième
majeure en deux /octaves ascendantes/ suivies d’une /tierce mineure
descendante/.

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition
*d’une tierce mineure descendante* est équivalente,
du point de vue des altérations produites,
à une transposition combinée de *trois quintes ascendantes*.


*** Quatre quintes

Nous allons opérer une quadruple transposition de quinte ascendante
sur la série des notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

Chaque étape transpose donc ces notes d’une quinte vers l’aigu :

#+ATTR_HTML: :class plat
| Départ | ⟼     | Inter 1 | ⟼     | Inter 2 | ⟼     | Inter 3 | ⟼     | Arrivée |
|        | 5te ↑ |         | 5te ↑ |         | 5te ↑ |         | 5te ↑ |         |
| do     |       | sol     |       | ré      |       | la      |       | mi      |
| ré     |       | la      |       | mi      |       | si      |       | fa^{#}  |
| mi     |       | si      |       | fa^{#}  |       | do^{#}  |       | sol^{#} |
| fa     |       | do      |       | sol     |       | ré      |       | la      |
| sol    |       | ré      |       | la      |       | mi      |       | si      |
| la     |       | mi      |       | si      |       | fa^{#}  |       | do^{#}  |
| si     |       | fa^{#}  |       | do^{#}  |       | sol^{#} |       | ré^{#}  |

À ce stade, quelques remarques s’imposent :

  - la transposition combinée produit quatre altérations au total (/fa
    #/, /do^{#}/, /sol^{#}/, /ré^{#}/)

  - à l’octave près, la transposition combinée équivaut à une
    transposition simple d’une /tierce majeure ascendante/

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition
*d’une tierce majeure ascendante* est équivalente,
du point de vue des altérations produites,
à une transposition combinée de *quatre quintes ascendantes*.


*** Cinq quintes

Nous allons opérer cinq transpositions de quinte ascendante sur la
série des notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

Nous obtenons :

#+ATTR_HTML: :class plat
| Départ | ⟼ | Arrivée |
| do     |   | si      |
| ré     |   | do^{#}  |
| mi     |   | ré^{#}  |
| fa     |   | mi      |
| sol    |   | fa^{#}  |
| la     |   | sol^{#} |
| si     |   | la^{#}  |

À ce stade, quelques remarques s’imposent :

  - la transposition combinée produit cinq altérations au total (/fa^{#}/,
    /do^{#}/, /sol^{#}/, /ré^{#}/, /la^{#}/)

  - à l’octave près, la transposition combinée équivaut à une
    transposition simple d’une /seconde mineure descendante/

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition
*d’une seconde mineure descendante* est équivalente, du point de vue
des altérations produites, à une transposition combinée
de *cinq quintes ascendantes*.


*** Six quintes

Nous allons opérer six transpositions de quinte ascendante sur la
série des notes naturelles :

#+BEGIN_CENTER
do   ré   mi   fa   sol   la   si
#+END_CENTER

Nous obtenons :

#+ATTR_HTML: :class plat
| Départ | ⟼ | Arrivée |
| do     |   | fa^{#}  |
| ré     |   | sol^{#} |
| mi     |   | la^{#}  |
| fa     |   | si^{#}  |
| sol    |   | do^{#}  |
| la     |   | ré^{#}  |
| si     |   | mi^{#}  |

À ce stade, quelques remarques s’imposent :

  - la transposition combinée produit six altérations au total (/fa^{#}/,
    /do^{#}/, /sol^{#}/, /ré^{#}/, /la^{#}/, /mi^{#}/)

  - à l’octave près, la transposition combinée équivaut à une
    transposition simple d’une /quarte augmentée ascendante/

Comme les transpositions à l’octave n’interviennent pas dans les
altérations, on en déduit que la transposition
/d’une quarte augmentée ascendante/ est équivalente,
du point de vue des altérations produites,
à une transposition combinée de /six quintes ascendantes/.


** Récapitulation
:PROPERTIES:
:CUSTOM_ID: section:recapitulationTranspositionQuintes
:END:


*** Quintes ascendantes

Nous disposons des équivalences suivantes :

| Transposition simple    | Équivalent combiné | Nombre d’altérations |
|-------------------------+--------------------+----------------------|
| 5te ascendante          | 1 x 5te ascendante |                    1 |
| 2de M ascendante        | 2 x 5te ascendante |                    2 |
| 3ce mineure descendante | 3 x 5te ascendante |                    3 |
| 3ce majeure ascendante  | 4 x 5te ascendante |                    4 |
| 2de mineure descendante | 5 x 5te ascendante |                    5 |
| 4te aug ascendante      | 6 x 5te ascendante |                    6 |


**** Altérations

Les altérations produites suivent également le cycle des quintes
ascendantes :

#+begin_center
fa^{#} do^{#} sol^{#} ré^{#} la^{#} mi^{#} si^{#} ...
#+end_center


*** Quintes descendantes

Un raisonnement analogue aux précédents nous permet de conclure aux
équivalences suivantes :

| Transposition simple    | Équivalent combiné  | Nombre d’altérations |
|-------------------------+---------------------+----------------------|
| 5te descendante         | 1 x 5te descendante |                    1 |
| 2de M descendante       | 2 x 5te descendante |                    2 |
| 3ce mineure ascendante  | 3 x 5te descendante |                    3 |
| 3ce majeure descendante | 4 x 5te descendante |                    4 |
| 2de mineure ascendante  | 5 x 5te descendante |                    5 |
| 4te aug descendante     | 6 x 5te descendante |                    6 |


**** Altérations

Les altérations produites suivent également le cycle des quintes
descendantes :

#+begin_center
si^b mi^b la^b ré^b sol^b do^b fa^b ...
#+end_center


* Gamme

#+TOC: headlines 1 local


** Définition

Une *gamme* est une suite de notes, ordonnées de la plus grave à la
plus aiguë, qui sert de fondation au développement de la musique.

/Remarque/ : une gamme étant un cas particulier de suite croissante,
leurs notes sont présentées avec octave implicite.


** Degrés

Les notes d’une gamme sont comptées à partir d’une note de référence
qui devient le *degré 1*. Les notes suivantes correspondent aux degrés
2 à 7, de la plus grave à la plus aiguë.

Le tableau suivant nous montre un exemple de gamme construite en
choisissant /do/ comme premier degré :

| Degré | Notes |
|-------+-------|
|     1 | do    |
|     2 | ré    |
|     3 | mi    |
|     4 | fa    |
|     5 | sol   |
|     6 | la    |
|     7 | si    |


*** Octaves

Pour ne pas se limiter à une seule octave, une gamme peut être répétée
autant que nécessaire dans l’aigu et dans le grave.

Le tableau suivant nous montre une gamme étendue sur plusieurs
octaves, avec un /do/ comme premier degré :

| Octave | Degré | Notes |
|--------+-------+-------|
|  =...= | =...= | =...= |
|      3 |     7 | si    |
|        |     6 | la    |
|        |     5 | sol   |
|        |     4 | fa    |
|        |     3 | mi    |
|        |     2 | ré    |
|        |     1 | do    |
|      2 |     7 | si    |
|        |     6 | la    |
|        |     5 | sol   |
|        |     4 | fa    |
|        |     3 | mi    |
|        |     2 | ré    |
|        |     1 | do    |
|      1 |     7 | si    |
|        |     6 | la    |
|        |     5 | sol   |
|        |     4 | fa    |
|        |     3 | mi    |
|        |     2 | ré    |
|        |     1 | do    |
|  =...= | =...= | =...= |


** Fonctions tonales

Une *fonction tonale* est un degré qui permet de mettre en évidence la
structure de la gamme à laquelle il appartient..

La musique utilisant des fonctions tonales est appelée *musique
tonale*.

Afin de bien distinguer les concepts de degré et de fonction, les
degrés sont symbolisés par des chiffres arabes (1, 2, ...), tandis que
les fonctions sont décrites par leurs noms, leurs abréviations ou des
chiffres romains majuscules (I, II, ...).


*** Tonique

La *tonique*, degré 1 et fondation de la gamme, est la note la plus
importante, celle qui donne le ton. Elle constitue donc la première
fonction tonale.

La tonique est la fonction sur laquelle la musique effectue ses pauses
les plus importantes.

On l’appelle aussi *finale*, car c’est généralement elle qui marque la
fin d’une structure musicale.


*** Dominante

La *dominante* est le degré 5 de la gamme. Elle est donc située une
quinte au-dessus de la tonique. Ce rapport de quinte n’est évidemment
pas choisi au hasard, puisqu’il s’agit d’un des intervalles les plus
fondamentaux en musique.

Par exemple, si la tonique est un /do/, la dominante sera un /sol/.

La musique tonale s’appuie sur la dualité qui existe entre la tonique,
fonction de repos, et la dominante, fonction dynamique autour de
laquelle la musique peut se développer. Il arrive également que la
musique effectue des pauses à la dominante, mais ce sont là des arrêts
nettement moins appuyés que ceux de la tonique.

La dominante est naturellement attirée par la tonique, et peut :

  - répondre à son appel, ce qui détent la musique
  - ne pas y répondre et repartir vers une autre idée

La dominante constitue donc la fonction tonale la plus importante avec
la tonique.


*** Sous-dominante

La *sous-dominante* est située une quinte sous la tonique, et
correspond donc au degré 4. En fait, dominante et sous-dominante
entourent la tonique dans le cycle des quintes :


#+ATTR_HTML: :class plat
| Fonctions | : | Sous-dominante | ⟻ | 5te | ⟼ | Tonique | ⟻ | 5te | ⟼ | Dominante |
| Degrés    | : |              4 | ⟻ | 5te | ⟼ |       1 | ⟻ | 5te | ⟼ | 5         |

À ce titre, la sous-dominante constitue la fonction tonale la plus
importante après la tonique et la dominante.

Par exemple, si la tonique est un /do/, la sous-dominante sera un
/fa/.


*** Sus-tonique, dominante auxiliaire

Le degré 2 est appelé *sus-tonique*, parce qu’il est situé juste
au-dessus de la tonique dans la gamme.

Par exemple, si la tonique est un /do/, la sus-tonique sera un /ré/.

Ce degré est situé deux quintes plus haut que la tonique dans le cycle
des quintes. En d’autres termes, il correspond à la dominante de la
dominante. La sus-tonique permet donc de renforcer le rôle de la
dominante en la considérant comme une *tonique secondaire* dont on
exprime la dominante.

On utilisera donc le terme de *dominante auxiliaire* comme synonyme de
sus-tonique.

Considérons l’exemple où la tonique est un /do/ et la dominante un
/sol/, et posons nous la question : que se passerait-il si le /sol/
était la tonique ? La dominante serait alors située une quinte
au-dessus, ce qui correspond au /ré/, degré 2 de notre gamme de
départ :

#+ATTR_HTML: :class plat
| Fonctions | : | Tonique | ⟻ | 5te | ⟼ | Dominante | ⟻ | 5te | ⟼ | Dominante auxiliaire |
| Degrés    | : |       1 | ⟻ | 5te | ⟼ |         5 | ⟻ | 5te | ⟼ |                    2 |


*** Sus-dominante, sous-médiante

Continuons à grimper dans le cycle des quintes, et reprenons notre
exemple où /do/ est la tonique : une quinte plus haut que la
sus-tonique, le /ré/, nous avons le /la/ qui correspond au degré 6. Ce
degré 6 est appelé *sus-dominante*, parce qu’il est situé juste
au-dessus de la dominante dans la gamme, ou encore *sous-médiante*
parce qu’il divise en deux tierces la quinte séparant la
sous-dominante de la tonique :

#+ATTR_HTML: :class plat
| Fonctions | : | Sous-dominante | ⟻ | 3ce | ⟼ | Sous-médiante | ⟻ | 3ce | ⟼ | Tonique |
| Degrés    | : |              4 | ⟻ | 3ce | ⟼ |             6 | ⟻ | 3ce | ⟼ |       1 |


*** Médiante

Reprenons notre exemple où /do/ est la tonique : une quinte plus haut
que la sous-médiante, le /la/, nous avons le /mi/ qui correspond au
degré 3. Ce degré 3 est appelé *médiante* parce qu’il divise en deux
tierces la quinte séparant la tonique de la dominante :

#+ATTR_HTML: :class plat
| Fonctions | : | Tonique | ⟻ | 3ce | ⟼ | Médiante | ⟻ | 3ce | ⟼ | Dominante |
| Degrés    | : |       1 | ⟻ | 3ce | ⟼ |        3 | ⟻ | 3ce | ⟼ |         5 |


*** Sous-tonique

Reprenons notre exemple où /do/ est la tonique : une quinte plus haut
que la médiante, le /mi/, nous avons le /si/ qui correspond au
degré 7. Ce degré 7 est appelé *sous-tonique* parce qu’il est situé
juste sous la tonique dans la gamme.


*** Sensibles

La tonique joue un rôle clé dans la gamme, aussi les degrés 7 et 2 qui
l’entourent suscitent un intérêt particulier. Un intervalle de seconde
mineure (un demi-ton) avec la tonique provoque en effet une attraction
naturelle vers cette dernière.

Lorsque le degré 7 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible inférieure*.

Lorsque le degré 2 n’est séparé de la tonique que par un demi-ton, il
est appelé *sensible supérieure*.

Lorsque la gamme ne dispose que d’une sensible inférieure, celle-ci
est simplement appelée *sensible*.

Exemples :

  - si la tonique est un /do/, la sensible inférieure sera un /si/

  - si la tonique est un /mi/, la sensible supérieure sera un /fa/

  - une gamme ayant /do/ pour tonique ne possède qu’une sensible
    inférieure, le /si/, qui est alors appelé sensible


**** Sensibles auxiliaires

La dominante joue un rôle clé dans la gamme, aussi les degrés 4 et 6
qui l’entourent suscitent un intérêt particulier. Un intervalle de
seconde mineure (un demi-ton) avec la dominante provoque en effet une
attraction naturelle vers cette dernière.

Lorsque le degré 4 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire inférieure*.

Lorsque le degré 6 n’est situé qu’à un demi-ton de la dominante, il
est appelé *sensible auxiliaire supérieure*.


*** Récapitulation

Le classement des degrés de la gamme par quintes croissantes nous
suggère la nomenclature et les abréviations suivantes :

| Degrés | Fonctions        |                                |              |
|        | Chiffres romains | Noms                           | Abréviations |
|--------+------------------+--------------------------------+--------------|
|      7 | VII              | Sous-tonique                   | Tinf         |
|        |                  | Sensible inférieure            | Sinf         |
|        |                  | Sensible                       | S            |
|      3 | III              | Médiante                       | M            |
|      6 | VI               | Sus-dominante                  | Dsup         |
|        |                  | Sous-médiante                  | SM           |
|        |                  | Sensible auxiliaire supérieure | SauxSup      |
|      2 | II               | Sus-tonique                    | Tsup         |
|        |                  | Dominante auxiliaire           | Daux         |
|        |                  | Sensible supérieure            | Ssup         |
|      5 | V                | Dominante                      | D            |
|      1 | I                | Tonique                        | T            |
|      4 | IV               | Sous-dominante                 | SD           |
|        |                  | Sensible auxiliaire inférieure | SauxInf      |

Parmi ces degrés, les fonctions tonales les plus importantes sont la
*tonique*, la *dominante* et la *sous-dominante*.


** Quintes et tierces

Le tableau suivant met en évidence les intervalles de quintes (ligne
par ligne) et de tierces (zig-zag) qui séparent les degrés de la
gamme :

#+ATTR_HTML: :class plat
|   | 4 |   | 1 |   | 5 |   |
| 2 |   | 6 |   | 3 |   | 7 |

Exemple avec /do/ pour tonique :

#+ATTR_HTML: :class plat
|    | fa |    | do |    | sol |    |
| ré |    | la |    | mi |     | si |


* Modes

#+TOC: headlines 1 local


** Introduction

Un mode est caractérisé par les intervalles qui séparent les notes
d’une gamme de sa tonique.


** Modes naturels

Les modes naturels sont obtenus simplement en prenant pour tonique une
note naturelle quelconque et en n’altérant aucune note de la gamme.
Voici les noms et définitions de ces modes :

| Mode        | Nom médiéval | Gamme modèle              |
|-------------+--------------+---------------------------|
| Mode de si  | Locrien      | si do ré mi fa sol la si  |
| Mode de mi  | Phrygien     | mi fa sol la si do ré mi  |
| Mode de la  | Éolien       | la si do ré mi fa sol la  |
| Mode de ré  | Dorien       | ré mi fa sol la si do ré  |
| Mode de sol | Mixolydien   | sol la si do ré mi fa sol |
| Mode de do  | Ionien       | do ré i fa sol la si do   |
| Mode de fa  | Lydien       | fa sol la si do ré mi     |

Le nom médiéval provient d’une interprétation erronée des modes grecs.
Ils sont toutefois encore largement utilisés aujourd’hui pour des
raisons purement pratiques.


*** Transpositions

Il est possible de transposer chacune des gammes naturelles sur une
autre tonique en respectant les écarts entre les notes afin de ne pas
altérer le mode. Nous définirons une gamme par le nom de la tonique
suivi du nom du mode. Par exemple, la gamme modèle de /do/ transposée
sur /sol/ se nommera /sol, mode de do/, ou /sol ionien/ suivant la
terminologie médiévale.


*** Par quintes ascendantes

Lorsqu’on transpose la gamme modèle du mode de /do/ :

#+BEGIN_CENTER
do ré mi fa sol la si do
#+END_CENTER

d’une quinte vers le haut, on obtient :

#+BEGIN_CENTER
sol la si do ré mi fa^{#} sol
#+END_CENTER

soit une altération haussière du degré 4 de l’ancienne gamme, qui
correspond au degré 7 de la nouvelle.

En continuant à parcourir les toniques séparées par des quintes
ascendantes, on est amené à hausser chaque fois le degré 4 de
l’ancienne gamme, ce qui nous donne un ordre des altérations
haussières progressant également par quintes ascendantes :

#+BEGIN_CENTER
fa, do, sol, ré, la, mi, si
#+END_CENTER

On peut suivre le même procédé avec la gamme modèle de n’importe quel
mode naturel, on constate que l’ordre des altérations haussières est
toujours le même.


*** Par quintes descendantes

Lorsqu’on transpose la gamme modèle du mode de /do/ :

#+BEGIN_CENTER
do ré mi fa sol la si do
#+END_CENTER

d’une quinte vers le bas, on obtient :

#+BEGIN_CENTER
fa sol la si^b do ré mi fa
#+END_CENTER

soit une altération baissière du degré 7 de l’ancienne gamme, qui
correspond au degré 4 de la nouvelle.

En continuant à parcourir les toniques séparées par des quintes
descendantes, on est amené à baisser chaque fois le degré 7 de
l’ancienne gamme, ce qui nous donne un ordre des altérations
baissières progressant également par quintes descendantes :

#+BEGIN_CENTER
si, mi, la, ré, sol, do, fa
#+END_CENTER

On peut suivre le même procédé avec la gamme modèle de n’importe quel
mode naturel, on constate que l’ordre des altérations haussières est
toujours le même.


*** Généralisation

On peut utiliser le cycle des quintes pour déduire les altérations de
n’importe quelle gamme d’un mode naturel.

Par exemple, si on souhaite connaître les altérations de la gamme de
/la, mode de do/, on part de la gamme modèle /do, mode de do/ et on
parcourt le cycle des quintes ascendantes pour passer de la tonique
/do/ à la tonique /la/ :

#+BEGIN_CENTER
do — sol — ré — la
#+END_CENTER

On doit effectuer trois transpositions d’une quinte ascendante : la
gamme de /la, mode de do/ aura donc trois altérations haussières :

#+BEGIN_CENTER
fa^{#} do^{#} sol^{#}
#+END_CENTER

Autre exemple, si on souhaite connaître les altérations de la gamme de
/sol, mode de la/, on part de la gamme modèle /la, mode de la/ et on
parcourt le cycle des quintes descendantes pour passer de la tonique
/la/ à la tonique /sol/ :

#+BEGIN_CENTER
la — ré — sol
#+END_CENTER

On doit effectuer deux transpositions d’une quinte descendante : la
gamme de /sol, mode de la/ aura donc deux altérations baissières :

#+BEGIN_CENTER
si^b mi^b
#+END_CENTER

Le tableau de la section de [[#section:recapitulationTranspositionQuintes][récapitulation]] concernant les
transpositions par combinaison de quintes peut également nous aider.

Si on souhaite connaître les altérations de la gamme de /ré, mode de
do/, on doit partir de la gamme modèle /do, mode de do/. La tonique
passe donc de /do/ à /ré/, soit une 2de majeure ascendante. Le tableau
nous indique que cet intervalle correspond à deux quintes ascendantes,
et donc à deux altérations haussières : /fa^{#}/ et /do^{#}/.

Si on souhaite connaître les altérations de la gamme de /fa, mode de
la/, on doit partir de la gamme modèle /la, mode de la/. La tonique
passe donc de /la/ à /fa/, soit une 3ce majeure descendante. Le tableau
nous indique que cet intervalle correspond à quatre quintes descendantes,
et donc à quatre altérations baissières : /si^b/, /mi^b/, /la^b/, /ré^b/.


*** Relatif

Deux gammes construites à partir des mêmes notes et des mêmes
altérations mais dont les toniques diffèrent sont dites *gammes
relatives* ou *relatifs*. Trouver un relatif consiste donc à faire
/tourner/ une gamme pour changer de tonique. Par exemple, la gamme de
/fa lydien/ :

#+BEGIN_CENTER
fa sol la si do ré mi fa
#+END_CENTER

est le relatif /lydien/ de la gamme de /si locrien/ :

#+BEGIN_CENTER
si do ré mi fa fa sol la
#+END_CENTER

Autre exemple, la gamme de /sol ionien/ :

#+BEGIN_CENTER
sol la si do ré mi fa^{#} sol
#+END_CENTER

est le relatif /ionien/ de la gamme de /mi éolien/ :

#+BEGIN_CENTER
mi fa^{#} sol la si do ré mi
#+END_CENTER

Dans le cas particulier d’un mode naturel, les gammes relatives se
situent par conséquent sur une même ligne dans les tableaux des
transpositions.


** Majeur et mineur

Le mode /majeur/ est simplement le mode /ionien/ :

#+BEGIN_CENTER
do ré mi fa sol la si do
#+END_CENTER

et le mode /mineur/ le mode /éolien/ :

#+BEGIN_CENTER
la si do ré mi fa sol la
#+END_CENTER

On remplace souvent les expressions /mode ionien/ par /mode majeur/ et
/mode éolien/ par /mode mineur/. Ainsi, on dira par exemple /ré majeur/
au lieu de /ré ionien/. De même, on utilisera indifféremment
/sol mineur/ ou /sol éolien/.

On emploiera également les termes de relatifs majeurs et mineurs au
lieu de relatifs ionien et éolien. On dira donc par exemple que /do majeur/
est le relatif majeur de /la mineur/, ou que /mi mineur/ est
le relatif mineur de /sol majeur/.


*** Degrés & intervalles caractéristiques

Les modes majeur et mineur sont les modes les plus utilisés. On s’en
sert donc comme référence pour souligner les *degrés caractéristiques*
des autres modes. Ces degrés forment des *intervalles
caractéristiques* avec la tonique.


**** Autour du mode majeur

En partant de /do majeur/, les quintes voisines nous donnent les
gammes de /sol mixolydien/ et /fa lydien/. Si nous transposons la
gamme de /sol mixolydien/ vers la tonique /do/, nous obtenons :

#+begin_center
do ré mi fa sol la /si^b/ do
#+end_center

La note caractéristique du mode mixolydien est donc le /si^b/,
septième degré formant un intervalle de septième mineure avec la
tonique.

Si nous transposons la gamme de /fa lydien/ vers la tonique /do/,
nous obtenons :

#+begin_center
do ré mi /fa^{#}/ sol la si do
#+end_center

La note caractéristique du mode lydien est donc le /fa^{#}/, quatrième
degré formant un intervalle de quarte augmentée avec la tonique.


**** Autour du mode mineur

En partant de /la mineur/, les quintes voisines nous donnent les
gammes de /mi phrygien/ et /ré dorien/. Si nous transposons la
gamme de /mi phrygien/ vers la tonique /la/, nous obtenons :

#+begin_center
la /si^b/ do ré mi fa sol la
#+end_center

La note caractéristique du mode phrygien est donc le /si^b/, deuxième
degré formant un intervalle de seconde mineure avec la tonique.

Si nous transposons la gamme de /ré dorien/ vers la tonique /la/, nous
obtenons :

#+begin_center
la si do ré mi /fa^{#}/ sol la
#+end_center

La note caractéristique du mode dorien est donc le /fa^{#}/, sixième
degré formant un intervalle de sixte majeure avec la tonique.

Nous n’avons pas encore exploré le mode locrien. Partons de la gamme
de /si locrien/ et transposons vers la tonique /la/, deux quintes plus
bas. Nous obtenons :

#+begin_center
la si^b do ré mi^b fa sol la
#+end_center

Les notes caractéristiques du mode lydien sont donc le /si^b/ et le
/la^b/, deuxième et cinquième degré formant des intervalles de seconde
mineure et quinte diminuée avec la tonique.


**** Récapitulation

| Modes           |           Degré | Intervalle      |
|                 | caractéristique | caractéristique |
|-----------------+-----------------+-----------------|
| Locrien         |               2 | 2de mineure     |
|                 |               5 | 5te diminuée    |
| Phrygien        |               2 | 2de mineure     |
| Éolien (Mineur) |                 | —               |
| Dorien          |               6 | 6te majeure     |
| Mixolydien      |               7 | 7e mineure      |
| Ionien (Majeur) |                 | —               |
| Lydien          |               4 | 4te augmentée   |


** Mineur


*** Mineur harmonique

En mode majeur, le degré 7 est une sensible qui n’est séparée de la
tonique que par un demi-ton. Par exemple, en /do majeur/, la sensible
est le /si/, à un demi-ton de la tonique /do/. Cette propriété est
intéressante car la sensible est naturellement attirée par la tonique,
ce qui permet de donner de la dynamique à un déroulement musical.

En mode mineur par contre, le degré 7 est une sous-tonique située un
ton sous la tonique. Par exemple, en /la mineur/, la sous-tonique est
le /sol/, à un ton de la tonique /la/. La propriété d’attirance de la
sensible vers la tonique n’est donc pas présente. On peut toutefois y
remédier en haussant la sous-tonique d’un demi-ton, obtenant ainsi un
mode dérivé, appelé *mode mineur harmonique*. Par exemple, en /la
mineur/, le /sol/ sera haussé d’un demi-ton, donnant ainsi la gamme :

#+BEGIN_CENTER
la si do ré mi fa sol^{#} la
#+END_CENTER

Dans la suite, le mode mineur par défaut sera généralement le mode
mineur harmonique.


*** Mineur ascendant et descendant

Le mode mineur harmonique sonne très bien, disposant à la fois des
propriétés mélancoliques du mode mineur et de l’attirance de la
sensible. Cependant, l’écart de trois demi-tons entre les degrés 6 et
7 n’est pas toujours souhaitable. Dans ce cas, on hausse le degré 6,
obtenant un mode appelé *mode mineur ascendant*. Par exemple, le /la
mineur harmonique/ devient :

#+BEGIN_CENTER
la si do ré mi fa^{#} sol^{#} la
#+END_CENTER

Par opposition, on appelle alors *mode mineur descendant* le mode
mineur naturel (le mode éolien). En pratique, les modes mineurs
(harmonique, ascendant et descendant) sont souvent mêlés, donnant
ainsi beaucoup de couleur et de souplesse à la musique. Enfin, le
degré 3 peut lui aussi être haussé d’un demi-ton, complétant ainsi le
caractère polymorphe du mode mineur, qui peut se rapprocher ou même se
confondre avec le mode majeur.


*** Conclusion

Le mode mineur est très versatile, et ses altérations flottantes
donnent une couleur particulière à la musique.


** Variantes des modes naturels


*** Acoustique

Le mode acoustique est construit à partir des premiers éléments de la
série des harmoniques naturelles. Elle contient donc une quinte, une
tierce majeure, une septième mineure, une seconde majeure et une
quarte augmentée. En partant d’un /do/, on obtient :

#+BEGIN_CENTER
do ré mi fa^{#} sol si^b do
#+END_CENTER

On peut bien entendu ajouter la note naturelle manquante, à savoir
le /la/ :

#+BEGIN_CENTER
do ré mi fa^{#} sol la si^b do
#+END_CENTER

La gamme ainsi obtenue possède les mêmes écarts qu’un relatif du mode
mineur ascendant à partir du quatrième degré :

#+BEGIN_CENTER
ré mi fa^{#} sol^{#} la si do ré
#+END_CENTER


*** Superlocrien

Le mode superlocrien est construit comme un relatif du mode mineur
ascendant à partir du septième degré :

#+BEGIN_CENTER
sol^{#} la si do ré mi fa^{#} sol^{#}
#+END_CENTER

Ce mode est appelé superlocrien, car il ressemble fort au mode
locrien. On le voit clairement en prenant /si/ comme tonique :

#+BEGIN_CENTER
si do ré mi^b fa sol la si
#+END_CENTER

**** Mineur harmonique

Il existe aussi une variante dérivée du mode mineur harmonique :

#+BEGIN_CENTER
sol^{#} la si do ré mi fa sol^{#}
#+END_CENTER

ce qui donne, en prenant /si/ comme tonique :

#+BEGIN_CENTER
si do ré mi^b fa sol la^b si
#+END_CENTER


*** Tzigane

Le mode Tzigane, ou mode Hongrois, est un mode dérivé du mineur
harmonique, le 4e degré étant haussé afin de se rapprocher de la
dominante :

#+BEGIN_CENTER
la si do ré^{#} mi fa sol^{#} la
#+END_CENTER

Ce mode est caractérisé par les deux écarts de trois demi-tons entre
les degrés 3 - 4 et 6 - 7.

*** Andalou

Il s’agit d’un mode ressemblant au /mode de mi/, mais disposant d’une
médiante flottante, formant une tierce majeure ou mineure avec la
tonique :

#+BEGIN_CENTER
mi fa sol^{(#)} la si do ré mi
#+END_CENTER

*** Napolitain

Il s’agit d’un mode ressemblant au /mode de mi/ où le septième degré
est haussé d’un demi-ton, ce qui le transforme en sensible :

#+BEGIN_CENTER
mi fa sol la si do ré^{#} mi
#+END_CENTER

On voit que la dominante auxiliaire est une sensible supérieure. Ce
mode est donc caractérisé par la double attraction :

#+BEGIN_CENTER
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+END_CENTER


*** Oriental


**** Variante phrygienne

Il s’agit d’un mode ressemblant au /mode de mi/, mais caractérisé par
les mêmes altérations que la gamme tzigane située une quinte plus
bas :

#+BEGIN_CENTER
mi fa sol^{#} la si do ré^{#} mi
#+END_CENTER

Ce mode est caractérisé par les deux écarts de trois demi-tons entre
les degrés 2 - 3 et 6 - 7, ainsi que par la double attraction :

#+BEGIN_CENTER
sensible inférieure ⟼ tonique ⟻ sensible supérieure
#+END_CENTER

Si on souhaite également créer une double attraction vers la
dominante :

#+BEGIN_CENTER
sous-dominante altérée ⟼ dominante ⟻ sous-médiante
#+END_CENTER

il suffit de hausser le degré 4 :

#+BEGIN_CENTER
mi fa sol^{#} la^{#} si do ré^{#} mi
#+END_CENTER


**** Variante locrienne

Il s’agit d’un mode ressemblant au /mode de si/, mais caractérisé par
les mêmes altérations que la gamme tzigane située deux quintes plus
bas :

#+BEGIN_CENTER
si do ré^{#} mi fa sol^{#} la si
#+END_CENTER

Afin d’obtenir la même propriété de double attraction que la variante
basée sur le mode de /mi/, on peut sensibiliser le degré 7 en le
haussant d’un demi-ton :

#+BEGIN_CENTER
si do ré^{#} mi fa sol^{#} la^{#} si
#+END_CENTER


** Tétraphoniques

Les modes tetraphoniques sont des gammes de quatre notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
quatre quintes :

#+BEGIN_CENTER
do sol ré la
#+END_CENTER

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode tetraphonique :

#+BEGIN_CENTER
do ré sol la do
#+END_CENTER

et ses relatifs :

#+ATTR_HTML: :class plat
| sol | la  | do | ré  | sol |
| ré  | sol | la | do  | ré  |
| la  | do  | ré | sol | la  |


** Pentaphoniques

Les modes pentaphoniques sont des gammes de cinq notes séparées par
des quintes. Par exemple, si nous partons de /do/, nous obtenons les
cinq quintes :

#+BEGIN_CENTER
do sol ré la mi
#+END_CENTER

En disposant ces notes sur une octave et en les ordonnant de la plus
grave à la plus aiguë, nous obtenons le mode pentaphonique :

#+BEGIN_CENTER
do ré mi sol la do
#+END_CENTER

et ses relatifs :

#+ATTR_HTML: :class plat
| sol | la  | do  | ré | mi  | sol |
| ré  | mi  | sol | la | do  | ré  |
| la  | do  | ré  | mi | sol | la  |
| mi  | sol | la  | do | ré  | mi  |


*** Avec caractéristique

Ce sont des modes pentaphoniques que l’on altère afin d’intégrer une
ou plusieurs notes caractéristiques des modes naturels. Par exemple,
ces modes pentaphoniques altérés :

#+ATTR_HTML: :class plat
| ré | mi | sol^{#} | la | do  | ré |
| la | do | ré^{#}  | mi | sol | la |

possèdent une quarte haussée, caractéristique du mode lydien.


*** Blues

Le mode blues est un mode pentaphonique développant les quintes à
partir de la médiante. La médiante, la dominante et la sous-tonique
sont flottantes :

#+BEGIN_CENTER
la do^{(#)} ré mi^{(b)} sol^{(#)} la
#+END_CENTER


*** Chinois

Le mode chinois est un mode pentaphonique développant les quintes à
partir de la tonique. Par exemple, avec /do/ comme tonique, nous
obtenons :

#+BEGIN_CENTER
do ré mi sol la do
#+END_CENTER


*** Japonais

Le mode japonais est un mode pentaphonique développant les quintes à
partir de la sous-dominante. Il est caractérisé par un intervalle de
quarte augmentée, intervalle qui sépare sa dominante auxiliaire de sa
dominante. La gamme modèle de ce mode possède un /mi/ pour tonique. On
part alors de la sous-dominante /la/ et on gravit les quintes entre
notes naturelles :

#+BEGIN_CENTER
la mi si fa do
#+END_CENTER

On voit que ce procédé produit la quinte diminuée /si — fa/. En
disposant ces notes sur une octave /mi — mi^{+1}/ et en les ordonnant
de la plus grave à la plus aiguë, nous obtenons :

#+BEGIN_CENTER
mi fa la si do mi
#+END_CENTER

La dominante auxiliaire /fa/ est donc une sensible supérieure. Le mode
possède un autre demi-ton entre la dominante /si/ et la sous-médiante
/do/.


* Tonalité

L’association d’une gamme et d’un mode est appelée *tonalité*.

On parlera par exemple de la tonalité de :

  - do majeur
  - la mineur
  - sol majeur
  - ré mineur
  - mi dorien
  - etc


* Durées

#+TOC: headlines 1 local


** Valeurs rythmiques

L’unité rythmique standard est la ronde. Les autres unités rythmiques
sont des multiples ou des divisions binaires de la ronde, obtenues en
multipliant ou divisant par deux la durée d’une unité voisine. Voici
les noms et les symboles de ces unités rythmiques :

| Notations | Noms             | Duréés en rondes |
|-----------+------------------+------------------|
| M         | Maxime           | 8                |
| L         | Longue           | 4                |
| U         | Brève            | 2                |
| R         | Ronde            | 1                |
| B         | Blanche          | 1 / 2            |
| N         | Noire            | 1 / 4            |
| C         | Croche           | 1 / 8            |
| dC        | Double-croche    | 1 / 16           |
| tC        | Triple-croche    | 1 / 32           |
| qC        | Quadruple-croche | 1 / 64           |

Malgré son nom, la brève compte donc parmi les unités rythmiques
les plus longues.


** Tempo

Le *tempo* définit la durée de l’unité rythmique choisie en indiquant
le nombre d’unités que peut contenir une minute. Par exemple, un tempo
de :

#+BEGIN_CENTER
/N/ blanches par minutes
#+END_CENTER

nous donnera :

#+BEGIN_CENTER
durée d’une blanche = 1 minute
#+END_CENTER

Toutes les autres durées se déduisent du tempo. On aura ainsi :

#+ATTR_HTML: :class plat
| /N/ / 16        | maximes par minute           |
| /N/ / 8	 | longues par minute           |
| /N/ / 4	 | brèves par minute            |
| /N/ / 2	 | rondes par minute            |
| 2 /N/           | noires par minute            |
| 4 /N/           | croches par minute           |
| 8 /N/           | double-croches par minute    |
| 16 /N/          | triple-croches par minute    |
| 32 /N/          | quadruple-croches par minute |

Un tempo peut être défini en utilisant indifféremment n’importe quelle
unité rythmique de référence.

Le tempo représente donc la vitesse à laquelle la musique est jouée.


** Notes pointées

Afin de pouvoir passer d’une décomposition binaire à une décomposition
ternaire, on dispose également des notes pointées, dont la durée est
de 3/2 de celle d’une note ordinaire :

| Notation | Signification                        | Durée en rondes |
|----------+--------------------------------------+-----------------|
| /Dp/     | Indique que la durée /D/ est pointée | /D/ × 3 / 2     |
| Mp       | Maxime pointée                       | 12              |
| Lp       | Longue pointée                       | 6               |
| Up       | Brève pointée                        | 3               |
| Rp       | Ronde pointée                        | 3 / 2           |
| Bp       | Blanche pointée                      | 3 / 4           |
| Np       | Noire pointée                        | 3 / 8           |
| Cp       | Croche pointée                       | 3 / 16          |
| dCp      | Double-croche pointée                | 3 / 32          |
| tCp      | Triple-croche pointée                | 3 / 64          |
| qCp      | Quadruple-croche pointée             | 3 / 128         |


*** Notes doublement pointées

Pointer une note ajoute la moitié de sa durée :

#+BEGIN_CENTER
1 ⟶ 1 + 1/2 = 3/2
#+END_CENTER

Double-pointer une note ajoute la moitié de la durée, puis le quart :

#+BEGIN_CENTER
1 ⟶ 1 + 1/2 + 1/4 = 7/4
#+END_CENTER

Voici la liste des notes double-pointées :

| Notation | Signification                                   | Durée en rondes |
|----------+-------------------------------------------------+-----------------|
| /Dpp/    | indique que la durée /D/ est doublement pointée | /D/ × 7 / 4     |
| Mpp      | Maxime double-pointée                           | 14              |
| Lpp      | Longue double-pointée                           | 7               |
| Upp      | Brève double-pointée                            | 7 / 2           |
| Rpp      | Ronde double-pointée                            | 7 / 4           |
| Bpp      | Blanche double-pointée                          | 7 / 8           |
| Npp      | Noire double-pointée                            | 7 / 16          |
| Cpp      | Croche double-pointée                           | 7 / 32          |
| dCpp     | Double-croche double-pointée                    | 7 / 64          |
| tCpp     | Triple-croche double-pointée                    | 7 / 128         |
| qCpp     | Quadruple-croche double-pointée                 | 7 / 256         |


** Durées fractionnaires

Il est possible de raccourcir ou d’allonger la durée d’un groupe de
notes en le précisant avec une fraction :

#+BEGIN_CENTER
M / N (groupe de notes)
#+END_CENTER

La durée totale du groupe de notes ainsi modifié vaudra alors M / N de
sa durée naturelle :

#+BEGIN_CENTER
durée de { M / N (groupe de notes) } = M / N × durée de { groupe de notes }
#+END_CENTER


*** Triolet

La fraction la plus fréquente est le *triolet* :

#+BEGIN_CENTER
2/3 (N N N)
#+END_CENTER

La durée totale du groupe vaut alors :

#+BEGIN_CENTER
2/3 × 3 noires = 2 noires = 1 blanche
#+END_CENTER

Le triolet permet d’insérer trois noires dans une blanche au lieu de
deux. On rencontre aussi des triolets de trois croches qui durent une
noire, ainsi que d’autres durées.


*** Duolet

Le *duolet* est l’inverse du triolet :

#+BEGIN_CENTER
3/2 (N N)
#+END_CENTER

La durée totale du groupe vaut :

#+BEGIN_CENTER
3/2 × 2 noires = 3 noires = 1 blanche pointée
#+END_CENTER

Le duolet permet d’insérer deux noires dans une blanche pointée au
lieu de trois. On rencontre aussi des duolets de deux croches valant
une noire pointée, ainsi que d’autres durées.


** Liaisons

Une liaison consiste à produire une note dont la durée est la somme
des durées des composantes. On la note :

# symboles :
#
# &8255; = ‿

#+BEGIN_CENTER
X‿Y
#+END_CENTER

ou, pour un nombre arbitraire de composantes :

#+BEGIN_CENTER
X‿Y‿...‿Z
#+END_CENTER

Exemples :

#+ATTR_HTML: :class plat
| /N‿N/   | est identique à | /B/  |
| /N‿N‿N/ | est identique à | /Np/ |
| /N‿C/   | est identique à | /Np/ |
| /B‿N‿C/ | est identique à | /Bpp/ |

** Silences

Le tableau suivant nous donne la liste des silences et de leurs
durées :

| Silence | Durée                    |
|---------+--------------------------|
| ms      | maxime                   |
| ls      | longue                   |
| us      | brève                    |
| rs      | ronde                    |
| bs      | blanche                  |
| ns      | noire                    |
| cs      | croche                   |
| dcs     | double-croche            |
| tcs     | triple-croche            |
| qcs     | quadruple-croche         |
| /dps/   | 3 / 2 × la durée de /D/s |
| /dpps/  | 7 / 4 × la durée de /D/s |
