
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 06 : Partition
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Les consonances adoucissent les dissonances

#+TOC: headlines 1 local

** Introduction

Pour atténuer l’effet d’une note dissonance, on peut s’arranger pour
que cette note forme un intervalle consonant avec au moins une des
autres notes de l’accord.

L’effet adoucissant est renforcé lorsqu’il fait intervenir une voix
voisine ou la basse.

Par exemple, pour atténuer l’effet du /fa/, qui forme une dissonance
de 7e mineure avec la fondamentale /sol/ dans :

#+ATTR_HTML: :class plat
| S | : | fa  |
| B | : | sol |

on peut ajouter un /ré/, qui est à la fois consonant avec le /fa/
(formant une tierce) et avec le /sol/ (formant une quinte) :

#+ATTR_HTML: :class plat
| S | : | fa  |
| A | : | ré  |
| B | : | sol |

** Accord pédale

Considérons :

  - un accord pédale /P/ consonant sur une partie des voix
  - un accord consonant /A/ sur les autres voix

Si les notes de /P/ ne forment que des consonances avec les notes de
/A/, l’ensemble est consonant.

Si les notes de /P/ forment au moins une dissonance avec les notes de
/A/, l’ensemble produit un effet de dissonance modérée, grâce aux
consonances internes de /P/ et de /A/.

Le résultat dépendra bien entendu du rapport entre le nombre de
consonances et le nombre de dissonances.

* Dispositions des accords

#+TOC: headlines 1 local

** Harmoniques naturelles

Nous avons déjà vu que les harmoniques naturelles pouvaient
inspirer des dispositions intéressantes pour les
[[file:/home/david/racine/site/eclats2vers/generic/grimoire/musica-03-luth.org::#heading:accordsParfaitsDispositions][accords parfaits]]

Il va de soi que ce principe peut être généralisé aux septièmes
de domoinante ou à n’importe quel autre accord : s’inspirer des
harmoniques naturelles est toujours une bonne idée.

** Accords parfaits

#+TOC: headlines 1 local

*** État fondamental

L'état fondamental est le plus affirmé, il agit comme un pilier de la
tonalité.

On double :

  - le plus souvent la fondamentale ou une note tonale
  - parfois la 3ce, en guise de variation

Si on souhaite supprimer une note :

  - on évite de supprimer la fondamentale
  - si on souhaite éviter l’ambiguité entre accord parfait majeur ou mineur
    + on ne supprime pas la note de 3ce majeure ou mineure
    + on supprime plutôt la 5te
  - l’accord produira un effet de simplicité si on supprime la 3ce
    + à réserver aux instants de convergence, comme en fin de phrase

#+begin_center
⁂
#+end_center

L’accord parfait du degré 7 remplit généralement la même fonction
tonale qu’une 7e de dominante sans fondamentale.

*** Premier renversement

Le premier renversement est moins appuyé que l’état fondamental.

On double en général une note tonale.

Si un degré fort est situé une tierce au-dessus de la fondamentale, la
basse est généralement doublée et l’accord peut assurer la fonction
tonale correspondante.

De part leur forte similitude, les accords de sixte peuvent aussi
ornementer l’accord parfait à l’état fondamental situé une tierce plus
haut. On compte en effet deux notes communes, et même trois avec la
doublure. Exemples en /do majeur/ :

| degrés | fonction | premier       | état fondamental d’un accord |
|        |          | renversement  | situé une tierce au-dessus   |
|--------+----------+---------------+------------------------------|
| 2 & 4  | SD       | fa la ré fa   | fa la do fa                  |
| 6 & 1  | T        | do mi la do   | do mi sol do                 |
| 3 & 5  | D        | sol si mi sol | sol si ré sol                |

#+begin_center
⁂
#+end_center

En mineur, l’accord de sus-tonique est soit :

  - au premier renversement pour éviter la quinte diminuée avec la basse
  - présenté avec un degré 2 abaissé pour produire un accord napolitain
  - sous la forme d’un accord napolitain au premier renversement

*** Second renversement

Le second renversement sert souvent d’accord ornemental. On s’arrange
alors pour que la basse fasse note commune avec les accords
environnants, contrastant alors avec les mouvements mélodiques
ornementaux des autres voix.

On double en général la basse, pour équilibrer les mouvements
constants et variables. Dans un quatuor, on se retrouve alors avec
deux voix constantes et deux voix variables.

Exemple de second renversement avec broderies au soprano et au ténor :

#+ATTR_HTML: :class plat
| S | : | si  | do  | si  |
| A | : | sol | sol | sol |
| T | : | ré  | mi  | ré  |
| B | : | sol | sol | sol |

Exemple de second renversement avec note de passage au ténor :

#+ATTR_HTML: :class plat
| S | : | sol | la | mi  |
| A | : | do  | do | do  |
| T | : | mi  | fa | sol |
| B | : | do  | do | do  |

Exemple avec une broderie au ténor et une note de passage au soprano :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | do  |
| A | : | sol | sol | sol |
| T | : | do  | si  | do  |
| B | : | do  | ré  | mi  |

** Septième de dominante

La note de 7e peut servir d’ornement harmonique ou mélodique.

Suppression :

  - on évite de supprimer la 3ce, car c’est la sensible inférieure
  - si on supprime la 7e, on se retrouve avec un accord parfait
  - on supprime le plus souvent la fondamentale ou la 5te

*** Sans fondamentale
:PROPERTIES:
:CUSTOM_ID: heading:dispositionSeptièmeDominanteSansFondamentale
:END:

La septième de dominante sans fondamentale est au minimum au premier
renversement, avec la 3ce à la basse.

Cette disposition est moins dissonante que l’accord complet, car
l’intervalle de septième mineure n’est plus présent.

Le second renversement est préféré au premier, car il évite aussi les
intervalles dissonants avec la basse, ce qui rend sa sonorité plus
douce.

Par exemple, en /do majeur/, la septième de dominante sans
fondamentale s’écrit :

#+begin_center
(sol) si ré fa —> si ré fa
#+end_center

ce qui produit un intervalle de quinte diminuée entre la note de 7e
/fa/ et la basse. Par contre, au second renversement :

#+begin_center
(sol) si ré fa —> ré fa si
#+end_center

on obtient des intervalles consonants avec la basse :

  - basse — fa : tierce mineure
  - basse — si : sixte majeure

L’intervalle dissonant du triton /fa — si/ ne fait alors pas
intervenir la basse.

Sous cette forme, l’accord de septième de dominante sans fondamentale
est présent dans la
[[file:musica-04-clavier.org::#heading:cadenceIonienneTroisVoix][cadence ionienne à trois voix]].

** Accords à base de quintes

Suppressions :

  - on évite de supprimer les notes qui contiennent la tension
    + 2de
    + 4te
    + etc

** Renversements

Les accords renversés ont généralement un caractère tonal moins
affirmé que leurs homologues à l’état fondamental. Cette remarque est
d’autant plus vraie pour les accords de trois notes. Afin de ne pas
rendre leur fonction tonale encore plus floue, on évite autant que
possible de supprimer une note d’une triade renversée.

Par contre, les accords renversés de quatre notes ou plus, et en
particulier la 7e et la 9e de dominante, peuvent s’employer sans
fondamentale ou sans quinte.
* Dynamique

#+TOC: headlines 1 local

** Introduction

La dynamique musicale est basée sur l’alternance de *tension* et de
*détente*, la détente servant de *résolution* à la tension initiale :

#+ATTR_HTML: :class plat
| tension | — | résolution |

Un objet musical est qualifié de :

  - *stable* s’il ne cause aucune tension
  - *instable* s’il provoque une tension

** Attraction

La tension d’un objet musical instable est souvent due à une
*attraction* vers un objet proche considéré comme plus stable. La
résolution s’effectue alors lorsque l’objet instable répond à cette
attraction en évoluant vers l’objet stable.

** Consonance & dissonance

#+TOC: headlines 1 local

*** Intervalles harmoniques

Un intervalle harmonique :

  - consonant est stable.
  - dissonant est instable.

*** Accords

Un accord :

  - consonant est stable.
  - dissonant est instable.

*** Généralisation

Par analogie avec les intervalles harmoniques :

  - un objet musical stable est qualifié de *consonant*
  - un objet musical instable est qualifié de *dissonant*

Synonymes :

  - un objet musical consonant est aussi appelé *consonance*
  - un objet musical dissonant est aussi appelé *dissonance*

** Préparation

Une tension peut être précédée d’une phase de *préparation*, phase qui
permet d’introduire la future dissonance dans un contexte où elle est
consonante. On a donc la structure générique :

#+ATTR_HTML: :class plat
| préparation | — | tension | — | résolution |

où la phase de préparation est optionnelle.

La dissonance qui passe par une phase de préparation est dite
*préparée*.

Lorsque la phase de préparation est omise, on dit que la dissonance
est *attaquée*.

** Résolution

Lorsqu’une dissonance se résout indifféremment suivant plusieurs
processus différents, on dit alors que sa résolution est *libre*.

Lorsqu’une dissonance se résout préférentiellement via un processus
bien défini, correspondant à un effet de détente maximal, on dit alors
que cette résolution est *régulière* ou *ordinaire*. On parle
également de *mouvement obligé*.

Dans le cas où une dissonance censée adopter un mouvement obligé se
résout autrement, on parle de résolution *irrégulière* ou
*exceptionnelle*.

Enfin, lorsqu’une dissonance ne se résout pas, on peut conduire la
musique vers une autre idée, ou vers une tension encore plus forte.

*** Absolue ou relative

La *résolution absolue* fait suivre un objet dissonant par un objet
consonant.

La *résolution relative* fait suivre un objet consonant par un objet
qui est encore plus consonant que le premier.

** Cycle

On a le cycle générique :

#+begin_center
(préparation)  —  tension  —  résolution  — (préparation)  —  tension  — résolution  —  =...=
#+end_center

Remarquons que la phase de résolution peut servir de préparation à la
tension suivante, formant ainsi le cycle :

#+begin_center
(préparation) —  tension  —  (résolution & préparation)  —  tension  — (résolution & préparation)  —  =...=
#+end_center

** Nouveauté

Les phases dynamiques peuvent servir à introduire de la nouveauté dans
le discours musical :

  - nouveau thème
  - modification du rythme
  - entrée d’une voix
  - changement de tonalité
  - etc

La nouveauté est présentée comme :

  - cause de la résolution
    + elle apparaît alors pendant la phase de tension
  - conséquence de la résolution

* Dynamique mélodique

#+TOC: headlines 1 local

** Sensibles

Une sensible induit une tension mélodique vers la note tonale la plus
proche : tonique ou dominante. Les sensibles sont donc considérées
comme des notes dissonantes.

Voici les résolutions attendues :

  - la sensible inférieure se résout sur la tonique en montant d’un demi-ton
  - la sensible supérieure se résout sur la tonique en descendant d’un demi-ton
  - la sensible auxiliaire inférieure se résout sur la dominante en montant d’un demi-ton
  - la sensible auxiliaire supérieure se résout sur la dominante en descendant d’un demi-ton

** Continuité

Un intervalle conjoint ne suscite pas de tension.

Un intervalle disjoint entre deux notes /x/ et /y/ suscite une tension
relative qui se résout en jouant les notes intermédiaires entre /x/ et /y/.

** Hauteur

Une note plus aiguë est relativement plus tendue qu’une note plus
grave.

Une note plus grave est relativement plus détendue qu’une note plus
aiguë.

*** Direction

Une mélodie qui monte vers l’aigu génère une tension relative.

Une mélodie qui descend vers le grave produit une détente relative.

*** Extrêmes

Une mélodie dont les pics (maxima locaux) montent vers l’aigu génère
une tension relative.

Une mélodie dont les creux (minima locaux) descendent vers le grave
produit une détente relative.

** Accentuation

Une mélodie est généralement accentuée par :

  - la durée : notes de durée plus longue
  - tout ce qui tranche d’une pente rectigligne et continue
    + saut : mouvement disjoint dans une mélodie majoritairement conjointe
    + virage : changement de direction, de pente
    + extrême : pic ou creux local

*** Notes essentielles

Les accents mélodiques sont généralement disposés sur des notes
essentielles ou sur des ornements harmoniques.

*** Discontinuités

Il est rare d’observer un mouvement disjoint ne faisant intervenir
aucune note de l’accord.

*** Indépendance

Les accents mélodiques des différentes voix de la polyphonie sont
indépendants. On peut disposer ces accents à des instants différents
sur chacune des voix, ceci afin de les mettre tour à tour en évidence.
On peut aussi s’arranger pour que les accents mélodiques soient
synchronisés afin de donner à l’ensemble un effet de convergence et
d’apothéose très convaincant.

* Dynamique des accords

#+TOC: headlines 1 local

** Accords parfaits

Les accords parfaits sont consonants. Pour plus de détails, voir la
section sur la
[[file:musica-03-luth.org::#heading:consonanceAccordsParfaits][consonance des accords parfaits]].

** Quinte diminuée

L’accord de quinte diminuée est dissonant, voir la section sur la
[[file:musica-03-luth.org::#heading:consonanceAccordsParfaits][consonance des accords parfaits]].

** Quinte augmentée

Les notes d’un accord de quinte augmentée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte augmentée

avec la fondamentale de l’accord. La quinte augmentée étant un
intervalle harmonique dissonant, l’accord de *quinte augmentée* est
*dissonant*.

** Septième de dominante

Les accords de septième de dominante sont dissonants.
Pour plus de détails, voir la section sur
la [[file:musica-03-luth.org::#heading:dissonanceSeptiemeDomminante][dissonance de la septième de dominante]].

** Autres accords de quatre notes ou plus

Un accord de quatre notes ou plus contient au moins une note qui va
former un intervalle harmonique de septième (mineure, majeure ou
diminuée) avec la fondamentale. Tous ces accords sont donc
*dissonants*.

** Accords à base de quintes

Les accords à base de quintes contiennent au moins un intervalle
dissonant : seconde, septième, neuvième, etc. Ce sont donc des accords
dissonants.

** Sensibles

La présence d’une sensible dans un accord provoque une tension qui
pousse cet accord à se résoudre sur un autre accord.

Une sensible, ou une sensible auxiliaire :

  - rend instable un accord qui ne comporte pourtant aucune dissonance constitutive
  - augmente l’instabilité d’un accord dissonant

#+begin_center
⁂
#+end_center

Les accords suivants contiennent une ou plusieurs tensions
mélodiques :

  - accords de dominante
  - accords de dominante auxiliaire avec sensible(s) auxiliaire(s)
  - accords napolitains
  - =...=

** Tableau récapitulatif

| Stabilité              | Accords               |
|------------------------+-----------------------|
| consonants             | parfait majeur        |
|                        | parfait mineur        |
| équilibre dynamique    | septième de dominante |
| dissonants             | tous les autres       |

La présence de sensible(s) rend l’accord dissonant ou augmente son
instabilité.

* Dynamique des dissonances

#+TOC: headlines 1 local

** Note dissonante

Une note dissonante est une note qui provoque l’apparition d’une
dissonance. Il peut s’agir :

  - d’une note ornementale dissonante
  - d’une note dissonante constitutive d’un accord dissonant

Chaque dissonance :

  - peut être précédée d’une phase de préparation
  - est suivie d’une phase de résolution

*** Ornement

Une note ornementale peut être :

  - consonante
    + l’accord en cours est consonant
    + la note ornementale en fait parfie
  - dissonante, sinon
    + note essentielle dissonante
    + note étrangère dissonante

*** Constitutive

Sans note de 7e, un accord de septième de dominante se réduit à un
accord parfait et ne présente plus de dissonance. On considère donc
que c’est la note de 7e qui est la note dissonante de l’accord.

Ce raisonnement nous permet de trouver la ou les notes responsables de
la dissonance dans la plupart des accords dissonants. Le tableau
suivant rassemble les principales notes dissonantes et leurs accords
respectifs :

| Accord                        | Notes           |
|                               | dissonantes     |
|-------------------------------+-----------------|
| septième de dominante         | 7e              |
| neuvième de dominante majeure | 7e, 9e          |
| neuvième de dominante mineure | 7e, 9e          |
|-------------------------------+-----------------|
| septième majeure              | 7e              |
| septième mineure              | 7e              |
| septième harmonique           | 7e              |
|-------------------------------+-----------------|
| quinte augmentée              | 5te aug         |
|-------------------------------+-----------------|
| quinte diminuée               | 5te dim         |
| septième et quinte diminuée   | 5te dim, 7e     |
| septième diminuée             | 5te dim, 7e dim |
|-------------------------------+-----------------|

Parfois, la présence d’une sensible gènère une tension, que l’accord
soit dissonant ou non :

| Accord                          | Sensible(s) |
|---------------------------------+-------------|
| accords de dominante auxiliaire | auxiliaires |
| napolitain                      | supérieure  |

** Préparation

La tension due à la dissonance peut être précédée d’un accord de
*préparation* :

  - qui contient les futures notes dissonantes, mais en tant que
    notes consonantes : on a alors *préparation par intégration*

  - qui permet d’amener les notes dissonantes par mouvement conjoint
    variable, on a alors *préparation conjointe*

  - qui permet d’amener les notes dissonantes par un ou plusieurs
    mouvements polyphoniques élégants, on a alors *préparation
    polyphonique*

/Remarque/ : la préparation par intégration peut être considérée comme
une préparation par mouvement conjoint constant.

** Résolution

#+TOC: headlines 1 local

*** Introduction

La résolution d’une note dissonante dans l’accord suivant peut se
réaliser suivant différents schémas :

  - *résolution par intégration* : la note instable est inclue dans
    l’accord suivant comme note consonante

  - *résolution conjointe* : la note instable réalise un mouvement
    conjoint variable vers une note consonante de l’accord suivant

  - *résolution polyphonique* : les notes instables réalisent un ou
    plusieurs mouvements polyphoniques élégants vers des notes consonantes
    de l’accord suivant

*** Voix

Une dissonance se trouve habituellement sur la même voix que sa
résolution.

On peut toutefois procéder à un échange de voix simultanée à une
résolution ordinaire, produisant ainsi un effet inattendu.

*** Résolution irrégulière

En cas de résolution irrégulière, il est préférable de quitter la
dissonance par mouvement conjoint.

** Doublure

#+TOC: headlines 1 local

*** Introduction

Une dissonance est aisément détectable par l’oreille, et l’est encore
plus si une note intervenant dans la préparation ou la résolution est
doublée.

On privilégie donc les mouvements contraire et oblique dans les phases
de préparation et de résolution d’une dissonance.

*** Préparation

Si une note de préparation est doublée, on quitte de préférence cette
note et sa doublure par mouvement contraire ou oblique.

*** Dissonance

La dissonance et sa doublure sont de préférence :

  - amenées par mouvement contraire ou oblique
  - quittées par mouvement contraire

On évite généralement de doubler une dissonance, sauf effet
particulier souhaité.

*** Résolution

Si la note de résolution est doublée, on amène de préférence cette
note et sa doublure par mouvement contraire.

L’arrivée sur résolution par mouvement oblique est déconseillée.

** Généralisation

Il arrive que l’on souhaite imiter le processus appliqué aux notes
dissonantes, mais dans le cas d’une note consonante. Cette note peut
alors être :

  - précédée d’une phase de préparation (optionnel)
  - suivie d’une phase de résolution

Ces deux phases peuvent se dérouler :

  - par intégration dans l’accord concerné (mouvement constant)
  - par mouvement conjoint variable
  - par mouvement(s) polyphonique(s) élégant(s)

et sont donc en tout point similaires à la préparation et à la
résolution de dissonance.

*** Ornements

Généralement, la définition d’un ornement demande que la note soit
préparée et/ou résolue, qu’elle soit consonante ou dissonante.

* Dynamique des enchaînements

#+TOC: headlines 1 local

** Enchaînements forts & faibles

Les enchaînements d’accords tonalement proches sont appelés
*enchaînements forts*.

Les enchaînements d’accords tonalement éloignés sont appelés
*enchaînements faibles*.

Un enchaînement est donc :

  - fort si les fondamentales procèdent par
    + quinte
    + seconde majeure
  - faible si les fondamentales procèdent par
    + tierce

** Continuité

Les accords proches au niveau tonal supportent mieux les mouvements
disjoints lors de leurs enchaînements. Exemples :

  - couple tonal
  - couple plagal
  - voisins dans le cycle tonal

Les accords dont le lien tonal est plus lointain demanderont plus de
mouvements conjoints pour assurer la liaison.

** Quarte et sixte

L’accord de quarte et sixte est un accord consonant, mais il permet
une résolution relative vers un accord encore plus stable, à savoir
l’accord parfait à l’état fondamental :

  - note de sixte —> note de quinte
  - note de quarte —>  note de tierce

Exemple de résolution d’une 4te & 6te de fondamentale /fa/ :

#+ATTR_HTML: :class plat
| S | : | fa | mi  |
| A | : | la | sol |
| B | : | do | do  |

L’accord de 4te & 6te peut également être utilisé comme
[[file:musica-04-clavier.org::#heading:accordBroderie][accord broderie]].

** Couple tonal

#+TOC: headlines 1 local

*** Introduction

La sensible inférieure évolue généralement vers la tonique. On
généralise cette propriété en utilisant l’attraction produite par les
intervalles de seconde mineure de la tonalité.

En /do majeur/ et /la mineur/, avec les accords :

|           | Dominante           | Tonique   |
|-----------+---------------------+-----------|
| do majeur | sol si ré (fa) (la) | do mi sol |
| la mineur | mi sol si (ré) (fa) | la do mi  |

nous avons :

|             | do majeur   | la mineur     | commentaire         |
|-------------+-------------+---------------+---------------------|
| 3ce —> 1ale | si —> do    | sol —> la     |                     |
|             |             | sol^{#} —> la | sensible inférieure |
|-------------+-------------+---------------+---------------------|
| 5te —> 3ce  | ré —> mi    | si —> do      |                     |
|             | ré —> mi^b  |               | 3ce altérée         |
|-------------+-------------+---------------+---------------------|
| 7e —> 3ce   | fa —> mi    | ré —> do      |                     |
|             |             | ré —> do^{#}  | 3ce picarde         |
|-------------+-------------+---------------+---------------------|
| 9e —> 5te   | la —> sol   | fa —> mi      |                     |
|             | la^b —> sol |               | 9e altérée          |

L’emploi simultané des évolutions /5te —> 3ce/ et /7e —> 3ce/ produit
une doublure de la 3ce de l’accord de tonique, ce qui n’est pas
toujours souhaitable. Si on souhaite l’éviter, on peut :

  - ne pas utiliser de note de 7e
    + accord parfait de dominante
  - dévier un des deux mouvements vers une autre note
    + 5te —> 1ale
    + 7e —> 5te

En termes de degrés de la gamme, on a :

#+ATTR_HTML: :class plat
| sensible inférieure | —> | tonique   |
| sus-tonique         | —> | médiante  |
| sous-dominante      | —> | médiante  |
| sus-dominante       | —> | dominante |

Exemple typique en /do majeur/, avec l’évolution /5te —> 3ce/ :

#+ATTR_HTML: :class plat
| S | : | la  | sol |
| M | : | si  | do  |
| A | : | fa  | sol |
| T | : | ré  | mi  |
| B | : | sol | do  |

et avec l’évolution /7e —> 3ce/ :

#+ATTR_HTML: :class plat
| S | : | la  | sol |
| M | : | si  | do  |
| A | : | fa  | mi  |
| T | : | ré  | do  |
| B | : | sol | do  |

L’harmonie classique privilégie cette seconde solution.

*** Préparation

Exemple de préparation d’une note de 7e en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | do   | ré   | do   |
| B | : | fa   | sol  | do   |

*** Résolution irrégulière

On peut dévier la sensible inférieure de son mouvement attendu vers la
tonique, et la rediriger vers la 5te de l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /si/ | /sol/ |
| A | : | fa   | mi    |
| T | : | ré   | do    |
| B | : | sol  | do    |

La 9e de dominante peut se résoudre à l’intérieur d’un autre accord de
dominante. Voici par exemple une résolution d’une 9e de dominante sans
fondamentale vers une 7e de dominante complète, toujours en /do
majeur/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | fa    |
| T | : | ré   | ré    |
| B | : | si   | si    |

** Dominante auxiliaire

Les accords de dominante auxiliaire peuvent subir des altérations qui
les rapprochent des notes tonales. Ces notes altérées se résolvent
alors naturellement sur les degrés correspondant :

| Résolution     | do majeur     | la mineur     |
|----------------+---------------+---------------|
| vers dominante | fa^{#} —> sol | ré^{#} —> mi  |
|                | la^b —> sol   | fa —> mi      |
| vers tonique   | si —> do      | sol^{#} —> la |
|                | ré^b —> do    | si^b —> la    |

** Septièmes d’espèces

Les septièmes d’espèces sont utilisées pour renforcer la résolution
vers l’accord suivant.

Le choix le plus évident consiste à imiter le couple tonal en
enchaînant avec un accord situé une quinte plus bas.

Dans cet exemple, qui enchaine un accord de /la/ avec un accord de
/ré/, on voit que la 7e, le /sol/, se résout en descendant vers le
/fa/ de l’accord suivant :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /fa/ |
| A | : | mi    | ré   |
| T | : | /do/  | /ré/ |
| B | : | la    | ré   |

On note aussi que la 3ce du premier accord (le /do/ au ténor) évolue
vers la fondamentale du deuxième accord (le /ré/).

Exemple avec un accord de préparation contenant la 7e :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /sol/ | /fa/ |
| A | : | mi    | mi    | ré   |
| T | : | si    | /do/  | /ré/ |
| B | : | sol   | la    | ré   |

** Accords à base de quintes

Un accord à base de quintes peut se transformer en accord parfait sans
3ce, avec doublure de la fondamentale :

#+ATTR_HTML: :class plat
| S | : | la   | la   |
| A | : | mi   | mi   |
| B | : | /si/ | /la/ |

Il peut aussi devenir un accord parfait au premier renversement :

#+ATTR_HTML: :class plat
| S | : | la   | la   |
| A | : | mi   | mi   |
| B | : | /si/ | /do/ |

Il peut aussi se transformer en accord parfait au second
renversement :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | mi   | mi    |
| B | : | si   | si    |

Il peut aussi devenir un accord parfait sans 3ce au second
renversement :

#+ATTR_HTML: :class plat
| S | : | /la/ | /si/ |
| A | : | mi   | mi   |
| B | : | si   | si   |

Enfin, il peut évoluer vers un accord de 7e incomplet :

#+ATTR_HTML: :class plat
| S | : | fa   | fa   |
| A | : | /do/ | /si/ |
| B | : | sol  | sol  |

* Dynamique des ornements

#+TOC: headlines 1 local

** Accentuation

Les ornements harmoniques sont généralement placés sur temps fort ou
partie forte de temps.

Les ornements mélodiques sont généralement placés sur temps faible ou
partie faible de temps.

** Pédale

Lorsqu’une *pédale* est présente, elle est en général alternativement
dissonante et consonante par rapport aux accords qui se succèdent sur
les autres voix.

Une pédale est souvent préparée en s’intégrant à un premier accord et
en perdurant après sa disparition. Le dernier accord qui se superpose
à une pédale lui est en général également consonant.

Autrement dit, une pédale est généralement préparée et résolue par
intégration.

** Retard

#+TOC: headlines 1 local

*** Préparation

Par définition, un retard est préparé par intégration. Idéalement, la
durée de la préparation est au moins égale à la durée du retard.

*** Phase active

Pour ne pas gâcher l’effet de surprise, on préfère ne pas faire
entendre simultanément le retard et sa résolution, sauf si une des
conditions suivantes est satisfaite :

  - la résolution est placée sous le retard
    + par exemple, si la résolution est placée à la basse
  - la résolution est discrète, voir les techniques de
    [[file:musica-04-clavier.org::#heading:camouflage][camouflage]]
  - on peut placer retard & résolution dans une disposition élégante

Le retard est généralement sur un temps plus accentué que sa
résolution :

| Retard       | Résolution   |
|--------------+--------------|
| temps fort   | temps médian |
| temps fort   | temps faible |
| temps médian | temps faible |

*** Résolution

Un retard dissonant se résout généralement en évoluant par mouvement
conjoint variable vers une note du nouvel accord. Suivant le sens du
mouvement, on distingue :

  - le *retard supérieur* qui se résout en descendant
    + c’est le plus courant, car l’effet de descente mélodique
      accentue la détente harmonique
  - le *retard inférieur* qui se résout en montant

Par exemple, dans l’enchaînement suivant, le /ré/ au soprano est un
retard supérieur qui se résout en descendant vers le /do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /do/ |
| A | : | sol  | mi   | mi   |
| T | : | sol  | sol  | sol  |
| B | : | si   | do   | do   |

Autre exemple où le /fa/ est un retard inférieur qui se résout en
montant vers le /sol/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /sol/ |
| A | : | do   | si   | si    |
| T | : | la   | ré   | ré    |
| B | : | fa   | sol  | sol   |

** Anticipation

Une anticipation dissonante se résout par intégration dans l’accord
suivant.

Par exemple, dans l’enchaînement suivant, le /mi/ au soprano est une
ancicipation :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |

** Appogiature

Par définition, l’appogiature est attaquée.

Une appogiature dissonante se résout le plus souvent par mouvement
conjoint variable.

* Dynamique du rythme

#+TOC: headlines 1 local

** Introduction

Le rythmes les plus stables sont les *rythmes réguliers* :

  - *rapides*, avec au moins une note par temps
  - *lents*, avec de longues notes continues

Tous les autres rythmes correspondent à des tensions qui peuvent se
résoudre sur l’une ou l’autre de ces configurations. Il va de soi que
les rythmes lents sont plutôt réservés à la fin d’une phrase et les
rythmes rapides au coeur d’un mouvement.

** Accentuation

Un temps fort peut être accentué par :

  - une intensité plus forte de la note qui l’entame
  - un accent mélodique

** Mesures

Une mesure irrégulière constitue une tension par rapport à une mesure
régulière proche.

** Fluidité

Un rythme sec produit une tension par rapport à un rythme fluide qui
lui est proche. Par exemple, la suite :

#+ATTR_HTML: :class plat
| C cs C | cs N N |

produira une tension puis une détente, et la suite :

#+ATTR_HTML: :class plat
| C cs N | C cs N | =...= |

un cycle de tension et de détente.

** Syncopes

Le schéma générique d’une syncope applique la structure générique de
tension et résolution. En voici un exemple :

  - *préparation* : rythme régulier, à raison d’une note par temps

  - *tension* : on gomme la première note de la mesure suivante en la
    remplaçant par la prolongation de la note précédente

  - *résolution* : la mélodie reprend le rythme régulier précédent, à
    raison d’une note par temps

Toutes les variations partant de ce cas d’école sont bien entendu
possibles. La phase de préparation est bien entendu optionnelle.

Voici des exemples de réalisation où la mesure compte deux temps d’une
noire chacun :

|         | Préparation | Tension     | Résolution |
|---------+-------------+-------------+------------|
| syncope | N N         | N N‿N N     | N N        |
| syncopé | N N         | N N‿N N‿N N | N N        |

*** Contraste

Il arrive souvent qu’on mette en relief une syncope en introduisant un
contraste entre la voix syncopée et une voix sans syncope qui assure
la régularité rythmique. Dans ce cas, la tension découle naturellement
du contraste.

** Contretemps

On peut considérer qu’une syncope est un rythme fluide et que le
contretemps est le rythme sec associé. Par conséquent, le contretemps
offre une tension rythmique encore plus importante que celle de la
syncope. On peut imaginer un prototype de tension — relaxation :

  - rythme régulier de préparation, une note par temps
  - tension : syncope
  - tension accrue : contretemps associé
  - légère détente : retour à la syncope
  - détente finale : retour au rythme régulier

chaque étape étant optionnelle.

* Boucles d’accords

#+TOC: headlines 1 local

** Introduction

Les boucles d’accords sont des cycles d’accords qui ne respectent pas
toujours la progression d’un cycle tonal ou plagal.

Ils sont beaucoup utilisés en musique pop.

** Boucle de quatre accords

Inspiré de la théorie de Philip Tagg.

  1. pôle principal
     - généralisation de la tonique
  2. sortant
     - prépare l’installation du pôle secondaire
  3. pôle secondaire
     - généralisation de la dominante
  4. rentrant
     - prépare l’installation du pôle principal
  5. retour au pôle principal

** Environnement

Inspiré de [[https://www.youtube.com/watch?v=JvyChMVvqnQ&t=401s][My Brand New Take On Four Chords Loop, by 12tone]].

Les enchaînements forts ou faibles entre un accord et ses voisins nous
donnent quatre configurations possibles :

| Catégorie    | Enchaînement avec |                |
| d’accord     | accord précédent  | accord suivant |
|--------------+-------------------+----------------|
| isolé        | faible            | faible         |
| continuation | fort              | fort           |
| départ       | faible            | fort           |
| destination  | fort              | faible         |

Un accord :

  - isolé sert de pause temporaire
  - de départ entame une série d’accord qui mène à une destination
  - de continuation prolonge une série entamée
  - de destination termine une série d’accord par une pause

* Stratification

#+TOC: headlines 1 local

** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique
tonalité, on parle de *musique tonale*. Il existe donc à tout moment
un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.

** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre tonalité, distincte
de celles des autres groupes, on parle de musique polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.

** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.

** Polyrythmie

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de *polymétrie* ou de *rythmes polymétriques*.

**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| V | : | § | χ | ¶ | χ | ¶ | χ |
| W | : | § | χ | χ | ¶ | χ | χ |
