
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 06 : Partition
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Accords classés

#+TOC: headlines 1 local


** Introduction

Les accords classés sont des accords naturellement engendrés par les
gammes lorsqu’on y superpose des tierces.


*** Nomenclature

Une *septième de dominante* est un accord de quatre notes dont la
fondamentale est placée sur la dominante.

Une *septième d’espèce* est un accord de quatre notes dont la
fondamentale n’est pas placée sur la dominante.

On utilise les abréviations suivantes :

| Accord                | Abréviation |
|-----------------------+-------------|
| septième de dominante | 7e D        |
| septième d’espèce     | 7e E        |


** Tonique

Les accords de tonique les plus utilisés sont des accords parfaits
majeur ou mineur. On rencontre aussi des septièmes d’espèce, comme
dans ces exemples :

| Accords             | Abréviations | Exemples             |                  |
|                     |              | Gammes               | Accords          |
|---------------------+--------------+----------------------+------------------|
| septième majeure    | 7e M         | do majeur            | do mi sol si     |
| septième mineure    | 7e m         | la mineur            | la do mi sol     |
| septième harmonique | 7e h         | la mineur harmonique | la do mi sol^{#} |

et plus rarement des accords de 5, 6 ou 7 notes.


*** Quinte augmentée

Si nous supprimons la fondamentale de l’accord de septième harmonique,
nous obtenons un accord dit de *quinte augmentée* :

| Accords          | Abréviations | Exemples      |
|------------------+--------------+---------------|
| quinte augmentée | 5te aug      | do mi sol^{#} |


** Dominante

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante sont très importants, de par leur fonction
tonale dynamique et parce qu’ils sont naturellement attirés par un
accord de tonique.


*** Triades

En empilant deux tierces, on obtient un accord parfait majeur, que ce
soit en mode majeur ou mineur harmonique :

| Accords        | Abréviations | Exemples             |               |
|                |              | Gammes               | Accords       |
|----------------+--------------+----------------------+---------------|
| parfait majeur | M            | do majeur            | sol si ré     |
| parfait majeur | M            | la mineur harmonique | mi sol^{#} si |


*** Septième

En empilant trois tierces, on obtient l’accord de *septième de
dominante*, dont la structure est identique en majeur et en mineur
harmonique :

| Accords               | Abréviations | Exemples             |                  |
|                       |              | Gammes               | Accords          |
|-----------------------+--------------+----------------------+------------------|
| septième de dominante | 7e D         | do majeur            | sol si ré fa     |
| septième de dominante | 7e D         | la mineur harmonique | mi sol^{#} si ré |

Dans les deux cas :

  - la première tierce est majeure
  - les deux tierces suivantes sont mineures

Avec les accords parfaits majeur et mineur, la septième de dominante
figure parmi les accords les plus importants de l’harmonie tonale.


**** Quinte diminuée

Lorsqu’on prive un accord de dominante de sa fondamentale, on obtient
un accord de *quinte diminuée* :

| Accords         | Abréviations | Exemples             |               |
|                 |              | Gammes               | Accords       |
|-----------------+--------------+----------------------+---------------|
| quinte diminuée | 5te dim      | do majeur            | si ré fa      |
| quinte diminuée | 5te dim      | la mineur harmonique | sol^{#} si ré |


*** Neuvième

En empilant quatre tierces, on obtient la *neuvième de dominante*,
majeure ou mineure suivant le mode :

| Accords                       | Abréviations | Exemples             |                     |
|                               |              | Gammes               | Accords             |
|-------------------------------+--------------+----------------------+---------------------|
| neuvième de dominante majeure | 9e D M       | do majeur            | sol si ré fa la     |
| neuvième de dominante mineure | 9e D m       | la mineur harmonique | mi sol^{#} si ré fa |


**** Septième et quinte diminuée

Lorsqu’on prive une neuvième de dominante majeure de sa fondamentale,
on obtient un accord de *septième et quinte diminuée* :

| Accords                     | Abréviations | Exemples  |             |
|                             |              | Gammes    | Accords     |
|-----------------------------+--------------+-----------+-------------|
| septième et quinte diminuée | 7e & 5te dim | do majeur | si ré fa la |


**** Septième diminuée

Lorsqu’on prive une neuvième de dominante mineure de sa fondamentale,
on obtient un accord de *septième diminuée* :

| Accords           | Abréviations | Exemples             |                  |
|                   |              | Gammes               | Accords          |
|-------------------+--------------+----------------------+------------------|
| septième diminuée | 7e dim       | la mineur harmonique | sol^{#} si ré fa |


** Sous-dominante

Les accords de sous-dominante sont similaires aux accords de tonique :
accords parfaits et septièmes majeures ou mineures. Exemples :

| Accords | Exemples  |             |
|         | Gammes    | Accords     |
|---------+-----------+-------------|
| 7e M    | do majeur | fa la do mi |
| 7e m    | la mineur | ré fa la do |


** Dominante auxiliaire
:PROPERTIES:
:CUSTOM_ID: section:dominanteAuxiliaire
:END:

#+TOC: headlines 1 local

*** Introduction

Les accords de dominante auxiliaire sont similaires aux accords de
dominante, si ce n’est qu’ils sont construits sur le degré 2 de la
gamme. Afin de renforcer le rôle de ces accords, il est possible de
les altérer en faisant /comme si/ la dominante de la gamme courante
devenait la tonique. On utilise les abréviations :

| Accords                          | Abréviations |
|----------------------------------+--------------|
| triade de dominante auxiliaire   | 3ade Daux    |
| septième de dominante auxiliaire | 7e Daux      |
| neuvième de dominante auxiliaire | 9e Daux      |


*** Majeur

Nous prenons comme illustration la gamme de /do majeur/. Nous obtenons
par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| do ré mi fa sol la si do | —> | sol la si do ré mi fa^{#} sol |

L’altération haussière du /fa^{#}/ (degré 4 par rapport à la tonique
/do/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /sol/.

On peut également altérer le /la/ (degré 6 par rapport à la tonique
/do/) vers le bas afin de le transformer en sensible auxiliaire
supérieure. Nous avons alors la gamme :

#+begin_center
sol la^b si do ré mi fa^{#} sol
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en do majeur |
|-------------------------+-----------+-----------------------|
| aucune                  | 3ade Daux | ré fa la              |
|                         | 7e Daux   | ré fa la do           |
|                         | 9e Daux   | ré fa la do mi        |
| inférieure              | 3ade Daux | ré fa^{#} la          |
|                         | 7e Daux   | ré fa^{#} la do       |
|                         | 9e Daux   | ré fa^{#} la do mi    |
| inférieure & supérieure | 3ade Daux | ré fa^{#} la^b        |
|                         | 7e Daux   | ré fa^{#} la^b do     |
|                         | 9e Daux   | ré fa^{#} la^b do mi  |


*** Mineur harmonique

Nous prenons comme illustration la gamme de /la mineur harmonique/.
Nous obtenons par transposition implicite vers la dominante :

#+ATTR_HTML: :class plat
| la si do ré mi fa sol^{#} la | —> | mi fa^{#} sol la si do ré^{#} mi |

L’altération haussière du /ré^{#}/ (degré 4 par rapport à la tonique
/la/) le transforme en sensible auxiliaire inférieure naturellement
attirée vers la dominante /mi/.

Si on supprime l’altération haussière du /fa^{#}/ (degré 6 par rapport
à la tonique /la/), on transforme ce degré en sensible auxiliaire
supérieure de la dominante /mi/. Nous obtenons alors la gamme :

#+begin_center
mi fa sol la si do ré^{#} mi
#+end_center

Les différentes variantes des accords de dominante auxiliaire
s’écrivent donc :

| Sensibles auxiliaires   | Accords   | Exemples en la mineur harmonique |
|-------------------------+-----------+----------------------------------|
| supérieure              | 2ade Daux | si ré fa                         |
|                         | 7e Daux   | si ré fa la                      |
|                         | 9e Daux   | si ré fa la do                   |
| inférieure              | 3ade Daux | si ré^{#} fa^{#}                 |
|                         | 7e Daux   | si ré^{#} fa^{#} la              |
|                         | 9e Daux   | si ré^{#} fa^{#} la do           |
| inférieure & supérieure | 3ade Daux | si ré^{#} fa                     |
|                         | 7e Daux   | si ré^{#} fa la                  |
|                         | 9e Daux   | si ré^{#} fa la do               |

Remarquons en passant que la triade de dominante auxiliaire non
altérée est un accord de quinte diminuée.


*** Sans fondamentale

Tout comme les accords de dominante, les accords de dominante
auxiliaire sont parfois présentés sans leur fondamentale. On obtient
alors des accords qui semblent être du degré 4, les fonctions de
dominante auxiliaire et de sous-dominante se voyant ainsi intimement
liées.

Exemple en /do majeur/ :

| Sensibles auxiliaires   | Accords | Exemples en do majeur |
|-------------------------+---------+-----------------------|
| aucune                  | 7e Daux | fa la do              |
|                         | 9e Daux | fa la do mi           |
| inférieure              | 7e Daux | fa^{#} la do          |
|                         | 9e Daux | fa^{#} la do mi       |
| inférieure & supérieure | 7e Daux | fa^{#} la^b do        |
|                         | 9e Daux | fa^{#} la^b do mi     |

Exemple en /la mineur harmonique/ :

| Sensibles auxiliaires   | Accords | Exemples en la mineur harmonique |
|-------------------------+---------+----------------------------------|
| supérieure              | 7e Daux | ré fa la                         |
|                         | 9e Daux | ré fa la do                      |
| inférieure              | 7e Daux | ré^{#} fa^{#} la                 |
|                         | 9e Daux | ré^{#} fa^{#} la do              |
| inférieure & supérieure | 7e Daux | ré^{#} fa la                     |
|                         | 9e Daux | ré^{#} fa la do                  |


*** Sixtes augmentées

#+TOC: headlines 1 local

**** Introduction

Les accords de *sixte augmentée* sont des accords de dominante
auxiliaire renversés. Ils sont altérés de sorte qu’ils présentent un
intervalle caractéristique de sixte augmentée, d’où leur nom.


**** Sixte française

La *sixte française* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est présentée sous la forme d’un
second renversement.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| ré fa^{#} la^b do | —> | la^b do ré fa^{#} |

En /la mineur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| si ré^{#} fa la | —> | fa la si ré^{#} |


**** Sixte italienne

La *sixte italienne* est une septième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /do majeur/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (ré) fa^{#} la^b do | —> | la^b do (ré) fa^{#} |

ce qui nous donne finalement :

#+begin_center
la^b do fa^{#}
#+end_center

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la | —> | fa la (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la ré^{#}
#+end_center


**** Sixte allemande

La *sixte allemande* est une neuvième de dominante auxiliaire avec
double sensible auxiliaire. Elle est privée de sa fondamentale et
présentée sous la forme d’un second renversement. Attention,
rappelez-vous que le nombre de renversements est calculé par rapport à
la fondamentale, même si celle-ci est supprimée.

En /la mineur harmonique/, nous avons le second renversement :

#+ATTR_HTML: :class plat
| (si) ré^{#} fa la do | —> | fa la do (si) ré^{#} |

ce qui nous donne finalement :

#+begin_center
fa la do ré^{#}
#+end_center

L’accord altéré de /do majeur/ respectant les mêmes écarts s’écrit :

#+begin_center
la^b do mi^b fa^{#}
#+end_center


** Emprunts

#+TOC: headlines 1 local

*** Introduction

Un emprunt est un accord provenant d’une autre gamme (tonique et/ou
mode) que l’on insère dans la gamme courante.


*** Majeur <——> Mineur

On peut placer des accords caractéristiques du mineur (quintes
augmentées, septièmes diminuées, ...) dans des gammes majeures, ou
l’inverse.


*** Tierces picardes

Une *tierce picarde* est un accord parfait majeur intégré à un autre
mode. On la rencontre souvent sur les degrés 1, 5, ou 4 du mode
mineur : la tierce de l’accord y est rendue majeure par une altération
haussière. Voici des exemples en /la mineur/ :

| Degrés | Exemples      |
|--------+---------------|
|      1 | la do^{#} mi  |
|      4 | ré fa^{#} la  |
|      5 | mi sol^{#} si |


*** Napolitain

En gamme de /mi napolitain/, l’accord de dominante auxiliaire non
altéré :

#+begin_center
fa la do
#+end_center

est un accord parfait majeur situé un demi-ton au-dessus de la tonique
/mi/. Par extension, on appelle accord *napolitain* tout accord défini
par les mêmes propriétés, et ce quels que soient le mode et la
tonique. Voici ce que cela donne en majeur et en mineur :

| do majeur    | la mineur  |
|--------------+------------|
| ré^b fa la^b | si^b ré fa |

Lorsque cet accord est présenté sous la forme de premier renversement,
il est appelé *sixte napolitaine* :

| do majeur    | la mineur  |
|--------------+------------|
| fa la^b ré^b | ré fa si^b |

Afin de former un accord similaire à une 7e de dominante, on peut
ajouter une note de 7e mineure à l’accord napolitain :

| do majeur         | la mineur       |
|-------------------+-----------------|
| ré^b fa la^b do^b | si^b ré fa la^b |

Ces derniers accords sont très prisés en jazz, où ils sont parfois
appelés *substitution au triton*, ou *substitution tritonique* à cause
de l’intervalle de triton qui lie la dominante auxiliaire altérée vers
le bas avec la dominante.


** Modes composites

Un *mode composite* associe à chaque degré une liste d’accords qui lui
sont caractéristiques. Voici un exemple de mode composite proche du
/la mineur/ :

| Degrés | Accords                     | Exemples             |
|--------+-----------------------------+----------------------|
|      1 | parfait mineur              | la do mi             |
|        | parfait majeur              | la do^{#} mi         |
|      2 | 7e Daux                     | si ré fa la          |
|        |                             | si ré^{#} fa la      |
|        | napolitains                 | si^b ré fa           |
|        |                             | si^b ré fa la^b      |
|      3 | quinte augmentée            | do mi sol^{#}        |
|      4 | parfait mineur              | ré fa la             |
|        | parfait majeur              | ré fa^{#} la         |
|      5 | septième de dominante       | mi sol^{#} si ré     |
|        | neuvième de dominante       | mi sol^{#} si ré fa  |
|      6 | parfait majeur              | fa la do             |
|        | quinte diminuée             | fa^{#} la do         |
|      7 | quinte diminuée             | sol^{#} si ré        |
|        | septième diminuée           | sol^{#} si ré fa     |
|        | septième et quinte diminuée | sol^{#} si ré fa^{#} |

Cette variété d’accords implique qu’une partie ou la totalité des
notes de la gamme peut être altérée vers le haut ou vers le bas en
fonction du contexte.


* Accords à base de quintes

#+TOC: headlines 1 local

** Triades

Si on superpose deux quintes, on obtient une triade que nous décidons
de nommer accord de *double quinte* :

| Accords       | Exemples  |
|---------------+-----------|
| double quinte | do sol ré |

En permutant les notes afin de les rapprocher, nous obtenons d’autres
dispositions de cet accord :

| Accords           | Exemples  |
|-------------------+-----------|
| double quarte     | ré sol do |
|-------------------+-----------|
| quarte et quinte  | sol do ré |
| seconde et quinte | do ré sol |

Ces accords sont nommés, suivant les cas :

  - d’après les intervalles entre les notes consécutives
  - d’après les intervalles qui séparent les notes de la basse

Synonymes courants :

  - l’accord de quarte et quinte se nomme aussi accord de *quarte suspendue*.
  - l’accord de seconde et quinte se nomme aussi accord de *seconde suspendue*.


** Tétrades

Les accords de quatre notes sont construits en superposant trois
quintes. Voici quelques dispositions possibles de ces accords :

| Accords        | Exemples     |
|----------------+--------------|
| triple quinte  | do sol ré la |
| triple quarte  | la ré sol do |
|----------------+--------------|
| 2de, 4te & 5te | sol la do ré |
| 4te, 5te & 9e  | sol do ré la |

Ces dispositions d’accords ressemblent aux modes tétraphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
tétraphonique.


** Pentades

Les accords de cinq notes sont construits en superposant quatre
quintes. Voici quelques dispositions possibles :

| Accords             | Exemples        |
|---------------------+-----------------|
| quadruple quinte    | do sol ré la mi |
| quadruple quarte    | mi la ré sol do |
|---------------------+-----------------|
| 3ce, 4te, 5te & 7e  | la do ré mi sol |
| 2de, 4te, 5te & 6te | sol la do ré mi |
| 4te, 5te, 6te & 9e  | sol do ré mi la |

Ces dispositions d’accords ressemblent aux modes pentaphoniques,
construits eux aussi en utilisant le cycle des quintes. En fait, jouer
une de ces dispositions revient à construire localement un mode
pentaphonique.


* Dynamique

#+TOC: headlines 1 local

** Introduction

La dynamique musicale est basée sur l’alternance de *tension* et de
*détente*, la détente servant de *résolution* à la tension initiale :

#+ATTR_HTML: :class plat
| tension | — | résolution |

La tension d’un objet musical est souvent due à l’ *attraction* vers
un objet proche condidéré comme plus stable.

Un objet musical est qualifié de :

  - *stable* s’il ne cause aucune tension

  - *instable* s’il provoque une tension


** Consonance & dissonance


*** Intervalles harmoniques

Un intervalle harmonique :

  - consonant est stable.
  - dissonant est instable.


*** Accords

Un accord :

  - consonant est stable.
  - dissonant est instable.


*** Généralisation

Par analogie avec les intervalles harmoniques :

  - un objet musical stable est qualifié de *consonant*
  - un objet musical instable est qualifié de *dissonant*

Synonymes :

  - un objet musical consonant est aussi appelé *consonance*
  - un objet musical dissonant est aussi appelé *dissonance*


** Préparation

Une tension peut être précédée d’une phase de *préparation*, phase qui
permet d’introduire la future dissonance dans un contexte où elle est
consonante. On a donc la structure générique :

#+ATTR_HTML: :class plat
| préparation | — | tension | — | résolution |

où la phase de préparation est optionnelle.

La dissonance qui passe par une phase de préparation est dite
*préparée*.

Lorsque la phase de préparation est omise, on dit que la dissonance
est *attaquée*.


** Résolution

Lorsqu’une dissonance se résout indifféremment suivant plusieurs
processus différents, on dit alors que sa résolution est *libre*.

Lorsqu’une dissonance se résout préférentiellement via un processus
bien défini, correspondant à un effet de détente maximal, on dit alors
que cette résolution est *régulière* ou *ordinaire*. On parle
également de *mouvement obligé*.

Dans le cas où une dissonance censée adopter un mouvement obligé se
résout autrement, on parle de résolution *irrégulière* ou
*exceptionnelle*.

Enfin, lorsqu’une dissonance ne se résout pas, on peut conduire la
musique vers une autre idée, ou vers une tension encore plus forte.


*** Absolue ou relative

La *résolution absolue* fait suivre un objet dissonant par un objet
consonant.

La *résolution relative* fait suivre un objet consonant par un objet
qui est encore plus consonant que le premier.


** Cycle

On a le cycle générique :

#+begin_center
(préparation)  —  tension  —  résolution  — (préparation)  —  tension  — résolution  —  =...=
#+end_center

Remarquons que la phase de résolution peut servir de préparation à la
tension suivante, formant ainsi le cycle :

#+begin_center
(préparation) —  tension  —  (résolution & préparation)  —  tension  — (résolution & préparation)  —  =...=
#+end_center


** Nouveauté

Les phases dynamiques peuvent servir à introduire de la nouveauté dans
le discours musical :

  - nouveau thème
  - modification du rythme
  - entrée d’une voix
  - changement de tonalité
  - etc

La nouveauté est présentée comme :

  - cause de la résolution
    + elle apparaît alors pendant la phase de tension
  - conséquence de la résolution


* Dynamique mélodique

#+TOC: headlines 1 local

** Sensibles

Une sensible induit une tension mélodique vers la note tonale la plus
proche : tonique ou dominante. Les sensibles sont donc considérées
comme des notes dissonantes.

Voici les résolutions attendues :

  - la sensible inférieure se résout sur la tonique en montant d’un demi-ton
  - la sensible supérieure se résout sur la tonique en descendant d’un demi-ton
  - la sensible auxiliaire inférieure se résout sur la dominante en montant d’un demi-ton
  - la sensible auxiliaire supérieure se résout sur la dominante en descendant d’un demi-ton


** Hauteur

Une note plus aiguë est plus tendue qu’une note plus grave.

Une note plus grave est plus détendue qu’une note plus aiguë.


** Continuité

Un intervalle conjoint ne suscite pas de tension.

Un intervalle disjoint entre deux notes /x/ et /y/ suscite une tension
qui se résout en jouant les notes intermédiaires entre /x/ et /y/.


** Direction

Une mélodie qui monte vers l’aigu génère une tension.

Une mélodie qui descend vers le grave produit une détente.


** Extrêmes

Une mélodie dont les pics (maxima locaux) montent vers l’aigu génère
une tension.

Une mélodie dont les creux (minima locaux) descendent vers le grave
produit une détente.


** Accentuation

Une mélodie est généralement accentuée par :

  - la durée : notes de durée plus longue
  - des sauts : mouvements disjoints dans une mélodie majoritairement conjointe
  - des virages : changements de direction, de pente
  - des extrêmes : pics ou creux locaux


*** Notes essentielles

Les accents mélodiques sont généralement disposés sur des notes
essentielles ou sur des ornements harmoniques.


*** Discontinuités

Il est rare d’observer un mouvement disjoint ne faisant intervenir
aucune note de l’accord.


*** Indépendance

Les accents mélodiques des différentes voix de la polyphonie sont
indépendants. La plupart du temps, on s’arrange pour que ces accents
apparaissent à des instants différents sur chacune des voix, ceci afin
de les mettre tour à tour en évidence.

Il arrive toutefois que les accents mélodiques soient synchronisés
afin de donner à l’ensemble un effet de convergence et d’apothéose
très convaincant.


* Dynamique des accords

#+TOC: headlines 1 local

** Accords parfaits

Les accords parfaits sont consonants. Pour plus de détails, voir la
section sur la [[file:musica-03-clavier.org::#section:consonanceAccordsParfaits][consonance des accords parfaits]].


** Autres triades

Les notes d’un accord de quinte augmentée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte augmentée

avec la fondamentale de l’accord. La quinte augmentée étant un
intervalle harmonique dissonant, l’accord de *quinte augmentée* est
*dissonant*.

#+begin_center
⁂
#+end_center

Les notes d’un accord de quinte diminuée forment des intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte diminuée

avec la fondamentale de l’accord. La quinte diminuée étant un
intervalle harmonique dissonant, l’accord de *quinte diminuée* est
*dissonant*.


** Septième de dominante

Les notes d’un accord de septième de dominante forment des
intervalles :

  - d’unisson
  - de tierce majeure
  - de quinte
  - de septième mineure

avec la fondamentale de l’accord. La septième mineure étant un
intervalle harmonique dissonant, l’accord de *septième de dominante*
est également *dissonant*.


*** Harmoniques naturelles

Considérons le début d’une série d’harmoniques naturelles de
fondamentale /sol/ :

#+ATTR_HTML: :class plat
| /Notes/   | : | sol | sol | ré | sol | si | ré | fa | sol | la | si | do^{#} | ré | =...= |
| /Numéros/ | : |   1 |   2 |  3 |   4 |  5 |  6 |  7 |   8 |  9 | 10 |     11 | 12 | =...= |

Si nous nous arrêtons à la note 7, nous avons :

#+begin_center
sol   sol   ré   sol   si   ré   fa
#+end_center

Hors doublures, nous obtenons un ensemble de quatre notes :

#+begin_center
sol   si   ré   fa
#+end_center

L’accord de septième de dominante se trouve donc dans une situation
paradoxale. Comme tous les accords de quatres notes à base de tierces,
sa note de septième forme une dissonance avec sa fondamentale. D’un
autre coté, nous voyons apparaître un accord de *septième de
dominante* parmi les premières harmoniques naturelles. Cet accord
figure donc parmi les plus *équilibrés* des accords dissonants. Il y a
donc là une forme d’ *équilibre dynamique*, ce qui explique son rôle
important.


** Autres accords de quatre notes ou plus

Un accord de quatre notes ou plus contient au moins une note qui va
former un intervalle harmonique de septième (mineure, majeure ou
diminuée) avec la fondamentale. Tous ces accords sont donc
*dissonants*.


** Accords à base de quintes

Les accords à base de quintes contiennent au moins un intervalle
dissonant : seconde, septième, neuvième, etc. Ce sont donc des accords
dissonants.


** Sensibles

La présence d’une sensible dans un accord provoque une tension qui
pousse cet accord à se résoudre sur un autre accord.

Une sensible, ou une sensible auxiliaire :

  - rend instable un accord qui ne comporte pourtant aucune dissonance constitutive
  - augmente l’instabilité d’un accord dissonant

#+begin_center
⁂
#+end_center

Les accords suivants contiennent une ou plusieurs tensions
mélodiques :

  - accords de dominante
  - accords de dominante auxiliaire avec sensible(s) auxiliaire(s)
  - accords napolitains
  - =...=


** Tableau récapitulatif

| Stabilité              | Accords               |
|------------------------+-----------------------|
| consonants             | parfait majeur        |
|                        | parfait mineur        |
| équilibre dynamique    | septième de dominante |
| dissonants             | tous les autres       |

La présence de sensible(s) rend l’accord dissonant ou augmente son
instabilité.


* Dynamique des dissonances

#+TOC: headlines 1 local

** Note dissonante

Une note dissonante est une note qui provoque l’apparition d’une
dissonance. Il peut s’agir :

 - d’une note ornementale dissonante
 - d’une note constitutive d’un accord dissonant

Chaque dissonance :

  - peut être précédée d’une phase de préparation
  - est suivie d’une phase de résolution


*** Ornement

Une note ornementale peut être :

  - consonante
    + l’accord en cours est consonant
    + la note ornementale en fait parfie
  - dissonante, sinon
    + note essentielle dissonante
    + note étrangère dissonante


*** Constitutive

Sans note de 7e, un accord de septième de dominante se réduit à un
accord parfait et ne présente plus de dissonance. On considère donc
que c’est la note de 7e qui est la note dissonante de l’accord.

Ce raisonnement nous permet de trouver la ou les notes responsables de
la dissonance dans la plupart des accords dissonants. Le tableau
suivant rassemble les principales notes dissonantes et leurs accords
respectifs :

| Accord                          | Notes                 |
|                                 | dissonantes           |
|---------------------------------+-----------------------|
| septième de dominante           | 7e                    |
| neuvième de dominante majeure   | 7e, 9e                |
| neuvième de dominante mineure   | 7e, 9e                |
|---------------------------------+-----------------------|
| septième majeure                | 7e                    |
| septième mineure                | 7e                    |
| septième harmonique             | 7e                    |
|---------------------------------+-----------------------|
| quinte augmentée                | 5te                   |
|---------------------------------+-----------------------|
| quinte diminuée                 | 5te                   |
| septième et quinte diminuée     | 5te, 7e               |
| septième diminuée               | 5te, 7e               |
|---------------------------------+-----------------------|

Parfois, la présence d’une sensible gènère une tension, que l’accord
soit dissonant ou non :

| Accord                          | Sensible(s) |
|---------------------------------+-------------|
| accords de dominante auxiliaire | auxiliaires |
| napolitain                      | supérieure  |


** Préparation

La tension due à la dissonance peut être précédée d’un accord stable
de *préparation* :

  - qui permet d’amener les notes dissonantes par mouvement conjoint
    variable, on a alors *préparation conjointe*

  - qui contient les futures notes dissonantes, on a alors
    *préparation par intégration*

  - qui permet d’amener les notes dissonantes par un ou plusieurs
    mouvements polyphoniques élégants, on a alors *préparation
    polyphonique*

/Remarque/ : la préparation par intégration peut être considérée comme
une préparation par mouvement conjoint constant.


** Résolution

#+TOC: headlines 1 local

*** Introduction

La résolution d’une note dissonante dans un accord stable peut se
réaliser suivant différents schémas :

  - *résolution conjointe* : la note instable réalise un mouvement
    conjoint variable vers une note inclue dans l’accord stable

  - *résolution par intégration* : la note instable est inclue dans
    l’accord stable suivant et devient donc naturellement stable lors
    du changement d’accord

  - *résolution polyphonique* : les notes instables réalisent un ou
    plusieurs mouvements polyphoniques élégants vers des notes inclues
    dans l’accord stable


*** Voix

Une dissonance se trouve habituellement sur la même voix que sa
résolution.

On peut toutefois procéder à un échange de voix simultanée à une
résolution ordinaire, produisant ainsi un effet inattendu.


*** Résolution irrégulière

En cas de résolution irrégulière, il est préférable de quitter la
dissonance par mouvement conjoint.


** Dissonance doublée

#+TOC: headlines 1 local

*** Introduction

Une dissonance est aisément détectable par l’oreille, et l’est encore
plus si une note intervenant dans la préparation ou la résolution est
doublée.

On privilégie donc les mouvements contraire et oblique dans les phases
de préparation et de résolution d’une dissonance doublée.


*** Préparation

Si une note de préparation est doublée, on quitte de préférence cette
note et sa doublure par mouvement contraire ou oblique.


*** Dissonance

La dissonance et sa doublure sont de préférence :

  - amenées par mouvement contraire ou oblique
  - quittées par mouvement contraire


*** Résolution

Si la note de résolution est doublée, on amène de préférence cette
note et sa doublure par mouvement contraire.

L’arrivée sur résolution par mouvement oblique est déconseillée.


** Généralisation

Il arrive que l’on souhaite imiter le processus appliqué aux notes
dissonantes, mais dans le cas d’une note consonante. Cette note peut
alors être :

  - précédée d’une phase de préparation (optionnel)
  - suivie d’une phase de résolution

Ces deux phases peuvent se dérouler :

  - par mouvement conjoint variable
  - par intégration dans l’accord concerné (mouvement constant)
  - par mouvement(s) polyphonique(s) élégant(s)

et sont donc en tout point similaires à la préparation et à la
résolution de dissonance.


*** Ornements

Généralement, la définition d’un ornement demande que la note soit
préparée et/ou résolue, qu’elle soit consonante ou dissonante.


* Dispositions des accords

#+TOC: headlines 1 local

** Accords parfaits


*** État fondamental

L'état fondamental est le plus affirmé, il agit comme un pilier de la
tonalité.

On double :

  - le plus souvent la fondamentale ou une note tonale
  - parfois la 3ce, en guise de variation

Si on souhaite supprimer une note :

  - on évite de supprimer la fondamentale
  - si on souhaite éviter l’ambiguité entre accord parfait majeur ou mineur
    + on ne supprime pas la note de 3ce majeure ou mineure
    + on supprime plutôt la 5te
  - l’accord produira un effet de simplicité si on supprime la 3ce
    + à réserver aux instants de convergence, comme en fin de phrase

#+begin_center
⁂
#+end_center

L’accord parfait du degré 7 remplit généralement la même fonction
tonale qu’une 7e de dominante sans fondamentale.


*** Premier renversement

Le premier renversement est moins appuyé que l’état fondamental.

On double en général une note tonale.

Si un degré fort est situé une tierce au-dessus de la fondamentale, la
basse est généralement doublée et l’accord peut assurer la fonction
tonale correspondante.

De part leur forte similitude, les accords de sixte peuvent aussi
ornementer l’accord parfait à l’état fondamental situé une tierce plus
haut. On compte en effet deux notes communes, et même trois avec la
doublure. Exemples en /do majeur/ :

| degrés | fonction | premier       | état fondamental d’un accord |
|        |          | renversement  | situé une tierce au-dessus   |
|--------+----------+---------------+------------------------------|
| 2 & 4  | SD       | fa la ré fa   | fa la do fa                  |
| 6 & 1  | T        | do mi la do   | do mi sol do                 |
| 3 & 5  | D        | sol si mi sol | sol si ré sol                |


#+begin_center
⁂
#+end_center

En mineur, l’accord de sus-tonique est soit :

  - au premier renversement pour éviter la quinte diminuée avec la basse
  - présenté avec un degré 2 abaissé pour produire un accord napolitain
  - sous la forme d’un accord napolitain au premier renversement


*** Second renversement

Le second renversement sert souvent d’accord ornemental. On s’arrange
alors pour que la basse fasse note commune avec les accords
environnants, contrastant alors avec les mouvements mélodiques
ornementaux des autres voix.

On double en général la basse, pour produire un équilibre de deux voix
constantes et deux voix variables.

Exemple de second renversement avec broderies au soprano et au ténor :

#+ATTR_HTML: :class plat
| S | : | si  | do  | si  |
| A | : | sol | sol | sol |
| T | : | ré  | mi  | ré  |
| B | : | sol | sol | sol |

Exemple de second renversement avec note de passage au ténor :

#+ATTR_HTML: :class plat
| S | : | sol | la | mi  |
| A | : | do  | do | do  |
| T | : | mi  | fa | sol |
| B | : | do  | do | do  |

Exemple avec une broderie au ténor et une note de passage au soprano :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | do  |
| A | : | sol | sol | sol |
| T | : | do  | si  | do  |
| B | : | do  | ré  | mi  |


** Septième de dominante

La note de 7e peut servir d’ornement harmonique ou mélodique.

Suppression :

  - on évite de supprimer la 3ce, car c’est la sensible inférieure
  - si on supprime la 7e, on se retrouve avec un accord parfait
  - on supprime le plus souvent la fondamentale ou la 5te


*** Sans fondamentale

La septième de dominante sans fondamentale est au minimum au premier
renversement, avec la 3ce à la basse.

Cette disposition est moins dissonante que l’accord complet, car
l’intervalle de septième mineure n’est plus présent.

Le second renversement est préféré au premier, car il évite des
intervalles dissonants avec la basse, ce qui rend sa sonorité plus
douce.

Par exemple, en /do majeur/, la septième de dominante sans
fondamentale s’écrit :

#+begin_center
(sol) si ré fa —> si ré fa
#+end_center

ce qui produit un intervalle de quinte diminuée entre la 7e et la
basse. Par contre, au second renversement :

#+begin_center
(sol) si ré fa —> ré fa si
#+end_center

on obtient les intervalles consonants :

  - basse — 5te : tierce mineure
  - basse — 3ce : sixte majeure

L’intervalle dissonant du triton /fa — si/ ne fait alors pas
intervenir la basse.

Sous cette forme, la dominante sans fondamentale est présente dans la
[[file:musica-04-clavier.org::#section:cadenceIonienneTroisVoix][cadence ionienne à trois voix]].


** Septième d’espèce

Il est préférable de préparer la note de 7e.

Idéalement, la durée de la préparation est au moins égale à la durée
de la note de 7e.


** Accords à base de quintes

Suppressions :

  - on évite de supprimer les notes qui contiennent la tension
    + 2de
    + 4te
    + etc


** Remarques générales


*** Continuité

Les accords proches au niveau tonal supportent mieux les mouvements
disjoints lors de leurs enchaînements. Exemples :

  - couple tonal
  - couple plagal
  - voisins dans le cycle tonal

Les accords dont le lien tonal est plus lointain demanderont plus de
mouvements conjoints pour assurer la liaison.


*** Renversements

Les accords renversés ont généralement un caractère tonal moins
affirmé que leurs homologues à l’état fondamental. Cette remarque est
d’autant plus vraie pour les accords de trois notes. Afin de ne pas
rendre leur fonction tonale encore plus floue, on évite autant que
possible de supprimer une note d’une triade renversée.

Par contre, les accords renversés de quatre notes ou plus, et en
particulier la 7e et la 9e de dominante, peuvent s’employer sans
fondamentale ou sans quinte.


* Dynamique des enchaînements

#+TOC: headlines 1 local

** Quarte et sixte

L’accord de quarte et sixte est un accord consonant, mais il permet
une résolution relative vers un accord encore plus stable, à savoir
l’accord parfait à l’état fondamental :

  - note de sixte —> note de quinte
  - note de quarte —>  note de tierce

Exemple de résolution d’une 4te & 6te de fondamentale /fa/ :

#+ATTR_HTML: :class plat
| S | : | fa | mi  |
| A | : | la | sol |
| B | : | do | do  |

L’accord de 4te & 6te peut également être utilisé comme [[file:musica-03-clavier.org::#section:accordBroderie][accord broderie]].


** Couple tonal

#+TOC: headlines 1 local

*** Accords parfaits

Dans cet exemple en /do majeur/, on note que la sensible inférieure
/si/ (3ce de l’accord de dominante) se résout sur la tonique /do/
(fondamentale de l’accord de tonique) :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | sol  | sol  |
| T | : | ré   | mi   |
| B | : | sol  | do   |


*** Septième de dominante

La sensible se résout généralement sur la tonique.

En mode majeur, une autre progression par demi-ton est possible : la
sous-dominante qui évolue vers la médiante.

Dans cet exemple en /do majeur/, on constate que la 7e, le /fa/, se
résout en descendant d’un demi-ton sur la 3ce de l’accord de tonique,
à savoir le /mi/ :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | /fa/ | /mi/ |
| T | : | ré   | do   |
| B | : | sol  | do   |

L’intervalle harmonique de triton /fa/ — /si/ se résout donc vers la
sixte /mi/ — /do/. En termes de cadences d’intervalles, il s’agit
d’une cadence extérieure conjointe.

En mode mineur, un enchaînement analogue est possible si on utilise
une sensible inférieure et une tierce picarde.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | si      | mi     |
| B | : | mi      | la     |


**** Préparation

Si l’on souhaite ajouter un accord de préparation contenant la 7e, on peut par
exemple choisir un accord de sous-dominante.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | do   | si   | do   |
| T | : | la   | ré   | do   |
| B | : | fa   | sol  | do   |

On peut aussi faire progresser l’alto du /la/ au /do/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | do   | ré   | do   |
| B | : | fa   | sol  | do   |

Ici, l’accord de préparation est une dominante auxiliaire :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | ré   | ré   | do   |
| B | : | fa   | sol  | do   |

Une variante où la quinte de l’accord de dominante est supprimée :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /mi/ |
| A | : | la   | si   | do   |
| T | : | ré   | sol  | sol  |
| B | : | fa   | sol  | do   |


**** Résolution irrégulière

Si on souhaite conserver les deux accords complets, on peut enchaîner
la 5te de l’accord de dominante avec la 5te de l’accord de tonique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | /fa/ | /mi/ |
| T | : | ré   | sol  |
| B | : | sol  | do   |

Notons toutefois que cela produit des quintes consécutives.

Une autre solution consiste à dévier la sensible inférieure de son
mouvement attendu vers la tonique, et la rediriger vers la 5te de
l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /si/ | /sol/ |
| A | : | /fa/ | /mi/  |
| T | : | ré   | do    |
| B | : | sol  | do    |

Enfin, on peut dévier la 7e et la 5te de l’accord de dominante :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/  |
| A | : | /fa/ | /sol/ |
| T | : | ré   | mi    |
| B | : | sol  | do    |


*** Neuvième de dominante

Dans cet exemple en /do majeur/, la 9e de dominante est suivie par un
accord de tonique. On voit que la 9e, le /la/, se résout en descendant
sur la 5te de l’accord de tonique, à savoir le /sol/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | mi    |
| T | : | si   | do    |
| B | : | sol  | do    |

La 9e de dominante peut également se résoudre à l’intérieur d’un autre
accord de dominante. Voici par exemple une résolution d’une 9e de
dominante sans fondamentale vers une 7e de dominante complète,
toujours en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /la/ | /sol/ |
| A | : | fa   | fa    |
| T | : | ré   | ré    |
| B | : | si   | si    |

Le même cas en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/    | /mi/    |
| A | : | ré      | ré      |
| T | : | si      | si      |
| B | : | sol^{#} | sol^{#} |


** Dominante auxiliaire

Les accords de dominante auxiliaire peuvent subir des altérations qui
les rapprochent des notes tonales. Ces notes altérées se résolvent
alors naturellement sur les degrés correspondant :

| Résolution     | do majeur    | la mineur    |
|----------------+--------------+--------------|
| vers dominante | fa^{#} —> sol | ré^{#} —> mi  |
|                | la^b —> sol   | fa —> mi      |
| vers tonique   | si —> do      | sol^{#} —> la |
|                | ré^b —> do    | si^b —> la    |


** Septièmes d’espèces

Les septièmes d’espèces sont utilisées pour renforcer la résolution
vers l’accord suivant.

Le choix le plus évident consiste à imiter le couple tonal en
enchaînant avec un accord situé une quinte plus bas.

Dans cet exemple, qui enchaine un accord de /la/ avec un accord de
/ré/, on voit que la 7e, le /sol/, se résout en descendant vers le
/fa/ de l’accord suivant :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /fa/ |
| A | : | mi    | ré   |
| T | : | /do/  | /ré/ |
| B | : | la    | ré   |

On note aussi que la 3ce du premier accord (le /do/ au ténor) évolue
vers la fondamentale du deuxième accord (le /ré/).

Exemple avec un accord de préparation contenant la 7e :

#+ATTR_HTML: :class plat
| S | : | /sol/ | /sol/ | /fa/ |
| A | : | mi    | mi    | ré   |
| T | : | si    | /do/  | /ré/ |
| B | : | sol   | la    | ré   |


** Accords à base de quintes

Un accord à base de quintes peut se résoudre sur l’octave de la
fondamentale, devenant ainsi une doublure :

#+ATTR_HTML: :class plat
| S | : | /si/ | /la/ |
| A | : | mi   | mi   |
| B | : | la   | la   |

ou sur la tierce de la fondamentale, devenant ainsi un accord parfait :

#+ATTR_HTML: :class plat
| S | : | /si/ | /do/ |
| A | : | mi   | mi   |
| B | : | la   | la   |

La fondamentale peut aussi glisser pour aboutir sur une doublure :

#+ATTR_HTML: :class plat
| S | : | si   | si   |
| A | : | mi   | mi   |
| B | : | /la/ | /si/ |

ou sur un accord parfait renversé :

#+ATTR_HTML: :class plat
| S | : | si   | si    |
| A | : | mi   | mi    |
| B | : | /la/ | /sol/ |

Enfin, la quinte de l’accord peut glisser pour obtenir un accord de
7e incomplet :

#+ATTR_HTML: :class plat
| S | : | fa   | fa   |
| A | : | /do/ | /ré/ |
| B | : | sol  | sol  |


*** Disposition en quartes

Le raisonnement est analogue pour les dispositions en quartes :

#+ATTR_HTML: :class plat
| S | : | fa    | fa   |
| A | : | do    | do   |
| B | : | /sol/ | /fa/ |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | fa    | fa   |
| A | : | do    | do   |
| B | : | /sol/ | /la/ |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /sol/ |
| A | : | do   | do    |
| B | : | sol  | sol   |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /mi/ |
| A | : | do   | do   |
| B | : | sol  | sol  |


* Dynamique des ornements

#+TOC: headlines 1 local

** Accentuation

Les ornements harmoniques sont généralement placés sur temps fort ou
partie forte de temps.

Les ornements mélodiques sont généralement placés sur temps faible ou
partie faible de temps.


** Pédale

Lorsqu’une *pédale* est présente, elle est en général alternativement
dissonante et consonante par rapport aux accords qui se succèdent sur
les autres voix.

Une pédale est souvent préparée en s’intégrant à un premier accord et
en perdurant après sa disparition. Le dernier accord qui se superpose
à une pédale lui est en général également consonant.

Autrement dit, une pédale est généralement préparée et résolue par
intégration.


** Retard

#+TOC: headlines 1 local

*** Préparation

Par définition, un retard est préparé par intégration. Idéalement, la
durée de la préparation est au moins égale à la durée du retard.


*** Phase active

Pour ne pas gâcher l’effet de surprise, on évite de faire entendre
simultanément le retard et sa résolution, sauf si une des conditions
suivantes est satisfaite :

  - la résolution est placée à la basse
  - la résolution est discrète, voir les techniques de [[file:musica-03-clavier.org::#section:camouflage][camouflage]]

Le retard est sur un temps plus accentué que sa résolution :

| Retard       | Résolution   |
|--------------+--------------|
| temps fort   | temps médian |
| temps fort   | temps faible |
| temps médian | temps faible |


*** Résolution

Un retard dissonant se résout généralement en évoluant par mouvement
conjoint variable vers une note du nouvel accord. Suivant le sens du
mouvement, on distingue :

  - le *retard supérieur* qui se résout en descendant
  - le *retard inférieur* qui se résout en montant

Par exemple, dans l’enchaînement suivant, le /ré/ au soprano est un
retard supérieur qui se résout en descendant vers le /do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /do/ |
| A | : | sol  | mi   | mi   |
| T | : | sol  | sol  | sol  |
| B | : | si   | do   | do   |

Autre exemple où le /fa/ est un retard inférieur qui se résout en
montant vers le /sol/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /fa/ | /sol/ |
| A | : | do   | si   | si    |
| T | : | la   | ré   | ré    |
| B | : | fa   | sol  | sol   |


** Anticipation

Une anticipation dissonante se résout par intégration dans l’accord
suivant.

Par exemple, dans l’enchaînement suivant, le /mi/ au soprano est une
ancicipation :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


** Appogiature

L’appogiature est généralement attaquée.

Une appogiature dissonante se résout le plus souvent par mouvement
conjoint variable.


* Dynamique du rythme

#+TOC: headlines 1 local

** Introduction

Le rythmes les plus stables sont les *rythmes réguliers* :

  - *rapides*, avec au moins une note par temps
  - *lents*, avec de longues notes continues

Tous les autres rythmes correspondent à des tensions qui peuvent se
résoudre sur l’une ou l’autre de ces configurations. Il va de soi que
les rythmes lents sont plutôt réservés à la fin d’une phrase et les
rythmes rapides au coeur d’un mouvement.


** Accentuation

Un temps fort peut être accentué par :

  - une intensité plus forte de la note qui l’entame
  - un accent mélodique


** Mesures

Une mesure irrégulière constitue une tension par rapport à une mesure
régulière proche.


** Fluidité

Un rythme sec produit une tension par rapport à un rythme fluide qui
lui est proche. Par exemple, la suite :

#+ATTR_HTML: :class plat
| C cs C | cs N N |

produira une tension puis une détente, et la suite :

#+ATTR_HTML: :class plat
| C cs N | C cs N | =...= |

un cycle de tension et de détente.


** Syncopes

Le schéma générique d’une syncope applique la structure générique de
tension et résolution. En voici un exemple :

  - *Préparation* : rythme régulier, à raison d’une note par temps

  - *Tension* : on gomme la première note de la mesure suivante en la
    remplaçant par la prolongation de la note précédente

  - *Résolution* : la mélodie reprend le rythme régulier précédent, à
    raison d’une note par temps

Toutes les variations partant de ce cas d’école sont bien entendu
possibles. La phase de préparation est bien entendu optionnelle.

Voici des exemples de réalisation où la mesure compte deux temps d’une
noire chacun :

|         | Préparation | Tension     | Résolution |
|---------+-------------+-------------+------------|
| syncope | N N         | N N‿N N     | N N        |
| syncopé | N N         | N N‿N N‿N N | N N        |


*** Contraste

Il arrive souvent qu’on mette en relief une syncope en introduisant un
contraste entre la voix syncopée et une voix sans syncope qui assure
la régularité rythmique. Dans ce cas, la tension découle naturellement
du contraste.


** Contretemps

On peut considérer qu’une syncope est un rythme fluide et que le
contretemps est le rythme sec associé. Par conséquent, le contretemps
offre une tension rythmique encore plus importante que celle de la
syncope. On peut imaginer un prototype de tension — relaxation :

  - rythme régulier de préparation, une note par temps
  - tension : syncope
  - tension accrue : contretemps associé
  - légère détente : retour à la syncope
  - détente finale : retour au rythme régulier

chaque étape étant optionnelle.


* Stratification

#+TOC: headlines 1 local


** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique
tonalité, on parle de *musique tonale*. Il existe donc à tout moment
un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.


** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre tonalité, distincte
de celles des autres groupes, on parle de musique polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.


** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.


** Polyrythmie

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de *polymétrie* ou de *rythmes polymétriques*.


**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| V | : | § | χ | ¶ | χ | ¶ | χ |
| W | : | § | χ | χ | ¶ | χ | χ |
