
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 05 : Tablature
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Modulation

#+TOC: headlines 1 local


** Introduction

Une *modulation* est un changement de gamme de référence : on passe
d’une tonique /T1/ et d’un mode /M1/ à une tonique /T2/ et un mode
/M2/.

La modulation nécessite de transposer la gamme de départ de
l’intervalle qui sépare /T1/ de /T2/, puis à modifier les altérations
pour satisfaire le mode /M2/.

Pour qu’il y ait modulation, il ne suffit pas de modifier les notes
(altérations haussières ou baissières ajoutées ou annulées) afin de
s’insérer dans la nouvelle gamme, il faut également que la tonalité
/T2/ et le mode /M2/ soient clairement affirmés par des enchaînements
d’accords faisant intervenir :

  - les fonctions tonales de /T2/
  - le cycle tonal de /T2/ ou une de ses variantes
  - les notes, intervalles, accords différenciant le mode /M2/ de /M1/


*** Diatonique et chromatique

Il existe deux types de modulation :

  - Si l’on enchaîne directement un accord appartenant clairement à la
    tonalité T1 avec un accord dont les altérations indiquent
    clairement la tonalité T2, le passage est net, il y a *modulation
    chromatique*.

  - Si on intercale des accords pouvant appartenir à T1 ou à T2, la
    transition se fait en douceur, on parle de *modulation
    diatonique*.

Les accords provoquant une modulation chromatique sont dit *accords
chromatiques*. De même, les accords provoquant une modulation
diatonique sont dit *accords diatoniques*.


*** Pédale

Si il existe une pédale correspondant à la tonique ou à la dominante
de T1 avant la modulation, deux cas peuvent se présenter :

  - La pédale reste constante : la modulation est alors considérée
    comme passagère

  - La pédale s’arrête ou passe à la tonique ou à la dominante de T2 :
    la modulation est considérée comme importante


** Tons voisins

Lorsqu’il n’existe qu’une altération d’écart entre l’ancienne gamme et
la nouvelle, on parle de *modulation voisine*. Les gammes concernées
sont nommées *tons voisins*.


*** Quinte voisine

La modulation vers une quinte voisine s’effectue en transposant la
gamme de départ d’une quinte, ce qui ne produit qu’une seule
altération. Du point de vue des fonctions tonales, il s’agit de la
dominante et de la sous-dominante de la gamme de départ.

Exemples :

| Gamme     | Gamme      | Altération | Altérations |
| de départ | d’arrivée  | de départ  | d’arrivée   |
|-----------+------------+------------+-------------|
| do majeur | sol majeur |            | fa^{#}      |
| do majeur | fa majeur  |            | si^b        |
|-----------+------------+------------+-------------|
| la mineur | mi mineur  |            | fa^{#}      |
| la mineur | ré mineur  |            | si^b        |


**** Accords diatoniques & chromatiques

Considérons une modulation au ton voisin, par exemple /do majeur/ pour
T1 et /sol majeur/ pour T2. La seule altération intervenant est le
/fa^{#}/ du /sol majeur/. Les accords diatoniques sont donc les
accords qui ne font pas intervenir le /fa/ du /do majeur/ ou le
/fa^{#}/ du /sol majeur/. Les accords parfaits correspondant à cette
description sont :

  - la do mi
  - do mi sol
  - mi sol si
  - sol si ré

Par opposition, les accords chromatiques sont ceux où intervient un
/fa/ ou un /fa^{#}/, c’est-à-dire, aux altérations près :

  - si ré fa
  - ré fa la
  - fa la do

On peut appliquer le même raisonnement aux accords à base de quintes
ainsi qu’aux accords de quatre notes et plus.


*** Ton relatif

On peut moduler d’une gamme majeure au relatif mineur ou l’inverse. On
peut également imaginer de moduler à d’autres gammes relatives
correspondant aux autres modes naturels.

Ces modulations relatives ne modifient aucune note, à l’exception de
la sensible inférieure du mineur harmonique.

Exemples :

| Gamme     | Gamme     | Sensible  | Sensible  |
| de départ | d’arrivée | de départ | d’arrivée |
|-----------+-----------+-----------+-----------|
| do majeur | la mineur |           | sol^{#}   |
| la mineur | do majeur | sol^{#}   |           |


*** Quinte voisine & relatif

On peut aussi moduler vers le relatif d’une quinte voisine, ou vice versa.

Exemples :

| Gamme     | Gamme      | Altérations | Altérations | Sensible  | Sensible  |
| de départ | d’arrivée  | de départ   | d’arrivée   | de depart | d’arrivée |
|-----------+------------+-------------+-------------+-----------+-----------|
| do majeur | mi mineur  |             | fa^{#}      | si        | ré^{#}    |
| do majeur | ré mineur  |             | si^b        | si        | do^{#}    |
|-----------+------------+-------------+-------------+-----------+-----------|
| la mineur | sol majeur |             | fa^{#}      | sol^{#}   | fa^{#}    |
| la mineur | fa majeur  |             | si^b        | sol^{#}   | mi        |


** Modulations éloignées

Une modulation vers une gamme autre qu’un ton voisin est dite
éloignée. Le procédé le plus naturel permettant de réaliser une
modulation éloignée est d’effectuer plusieurs modulations voisines
jusqu’à l’obtention du ton et du mode désiré. Mais il existe d’autres
procédés, tels que l’utilisation de pivots ou d’accords vagues, qui
font l’objet des sections suivantes.


** Pivots fonctionnels

Un *pivot fonctionnel* est un accord ou un groupe d’accords qui peut
s’intégrer dans deux logiques tonales différentes :

  - celle de la gamme que l’on quitte
  - celle de la gamme vers laquelle on module

Grâce à cette propriété, un pivot fonctionnel peut servir de
transition entre les deux gammes.


*** Couple tonal

Le couple tonal permet d’affirmer une nouvelle tonalité. Un des
accords joué peut être utilisé comme pivot.


**** Accord de dominante

L’accord de septième de dominante de /do majeur/ peut être considéré
comme un accord du degré 3 sans fondamentale :

#+ATTR_HTML: :class plat
| sol si ré fa | ⟻⟼ | (mi) sol si ré fa |

Or, ce degré est la dominante d’une gamme dont la tonique serait une
quinte plus bas, à savoir le /la/, degré 6 de la gamme courante. Notre
accord de dominante permet donc de moduler vers le relatif /la mineur/
en jouant l’enchaînement :

#+ATTR_HTML: :class plat
| sol si ré fa | — | la do mi la |

Il est même possible d’altérer le premier accord pour faire entendre
la sensible inférieure /sol^{#}/ du mineur harmonique :

#+ATTR_HTML: :class plat
| sol^{#} si ré fa | — | la do mi la |


**** Accord de dominante sans fondamentale

L’accord de dominante sans fondamentale de /do majeur/ :

#+ATTR_HTML: :class plat
| (sol) si ré fa | ⟼ | si ré fa |

peut être également considéré comme un accord du degré 7, le /si/ dans
notre cas. Or, ce degré est la dominante d’une gamme dont la tonique
serait une quinte plus bas, à savoir le /mi/, degré 3 de la gamme
courante. Notre accord de dominante sans fondamentale permet donc de
moduler d’une tierce ascendante, il suffit de jouer l’enchaînement :

#+ATTR_HTML: :class plat
| si ré fa | — | mi sol si |


**** Sous-dominante

L’accord de sous-dominante :

#+begin_center
fa la do
#+end_center

peut être considéré comme la dominante d’une gamme dont la tonique
serait un /si^b/. On peut donc moduler vers /si^b majeur/ en jouant
l’enchaînement :

#+ATTR_HTML: :class plat
| fa la do | — | si^b ré fa |


**** Médiante

L’accord de degré 3 au second renversement de la gamme de /do
majeur/ :

#+begin_center
sol si mi (sol)
#+end_center

fait fonction de dominante de /do majeur/ de par la mise à la basse et
l’éventuelle doublure du /sol/, mais la fondamentale /mi/ est
également la dominante de la gamme de /la mineur/. On peut donc
moduler vers le relatif mineur en faisant entendre :

#+ATTR_HTML: :class plat
| sol si mi | — | la do mi |


**** Sous-médiante

L’accord de degré 6 renversé de la gamme de /do majeur/ :

#+begin_center
do mi la (do)
#+end_center

fait fonction de tonique de la tonalité en cours, mais comme sa
fondamentale est un /la/, il peut être vu comme la dominante d’une
gamme ayant /ré/ pour tonique. On peut donc moduler à la seconde
ascendante en jouant l’enchaînement :

#+ATTR_HTML: :class plat
| do mi la | — | ré fa la |


*** Couple plagal

Le couple plagal permet d’affirmer une nouvelle tonalité. Un des
accords joué peut être utilisé comme pivot.


**** Accord de dominante

L’accord de dominante de /do majeur/ :

#+begin_center
sol si ré fa
#+end_center

peut être vu comme l’accord de sous-dominante d’une gamme ayant /ré/
pour tonique. Pour moduler vers /ré dorien/, il suffit donc de faire
entendre :

#+ATTR_HTML: :class plat
| sol si ré fa | — | ré fa la ré |

Pour moduler vers /ré majeur/, il suffit d’ajouter les altérations
nécessaires :

#+ATTR_HTML: :class plat
| sol si ré fa | — | ré fa^{#} la ré |


*** Tonique

Un accord de tonique permet d’affirmer une nouvelle tonalité. L’accord
joué peut être utilisé comme pivot.


**** Sous-médiante

L’accord de degré 6 de /do majeur/ :

#+begin_center
do mi la (do)
#+end_center

fait fonction de tonique de part la mise à la basse et l’éventuelle
doublure du /do/, mais comme le /la/ est la fondamentale de l’accord,
il peut être également vu comme un accord de tonique de /la mineur/.


** Pivots polyphoniques

Un *pivot polyphonique* est un accord ou un groupe d’accords qui
s’intercale entre deux tonalités, de telle sorte que les enchaînements
soient constitués de mouvements polyphoniques élégants. Cet accord ou
groupe d’accords peut donc servir de transition entre les deux gammes.

#+begin_center
⁂
#+end_center

Considérons par exemple l’accord de tonique de la gamme de /mi
majeur/ :

#+begin_center
mi sol^{#} si
#+end_center

Cet accord est très semblable à l’accord de tonique de /do majeur/ au
premier renversement :

#+begin_center
mi sol do
#+end_center

L’enchaînement :

#+ATTR_HTML: :class plat
| S | : | si      | do  | (monte)   |
| A | : | sol^{#} | sol | (descend) |
| B | : | mi      | mi  | (constant) |

permet donc de moduler par un simple mouvement contraire de /mi
majeur/ vers /do majeur/.


** Accords vagues

Les *accords vagues* sont des accords qui peuvent appartenir à
plusieurs tonalités différentes suivant l’enharmonie utilisée.


*** Septième diminuée

L’accord de septième diminuée peut être utilisé comme accord vague.

Par exemple, la septième diminuée suivante :

#+begin_center
sol^{#} si ré fa
#+end_center

peut être vue comme un accord de neuvième de dominante sans
fondamentale de la gamme de /la mineur harmonique/ :

#+ATTR_HTML: :class plat
| (mi) sol^{#} si ré fa | ⟼ | sol^{#} si ré fa |

En utilisant l’enharmonie /sol^{#} = la^b/, cet accord peut se
réécrire :

#+begin_center
la^b si ré fa
#+end_center

dont l’état canonique est :

#+begin_center
si ré fa la^b
#+end_center

Ce dernier accord peut être analysé comme une neuvième de dominante
sans fondamentale de la gamme de /do mineur harmonique/ :

#+ATTR_HTML: :class plat
| (sol) si ré fa la^b | ⟼ | si ré fa la^b |

Cet accord permet donc de moduler aisément à la tierce mineure. Il
permet même de moduler au triton si on l’écrit :

#+begin_center
do^b ré fa la^b
#+end_center

dont l’état fondamental est :

#+begin_center
ré fa la^b do^b
#+end_center

accord de neuvième de dominante sans fondamentale de la gamme de /mi^b
mineur harmonique/.

Cet accord permet donc de moduler aisément à la *tierce mineure* ou au
*triton*.


*** Quinte augmentée

L’accord de quinte augmentée peut être utilisé comme accord vague.

Par exemple, la quinte augmentée suivante :

#+begin_center
do mi sol^{#}
#+end_center

peut être vue comme un accord de septième sans fondamentale disposé
sur la tonique de /la mineur harmonique/ :

#+ATTR_HTML: :class plat
| (la) do mi sol^{#} | ⟼ | do mi sol^{#} |

En utilisant l’enharmonie /sol^{#} = la^b/, cet accord peut se
réécrire :

#+begin_center
do mi la^b
#+end_center

dont l’état canonique est :

#+begin_center
la^b do mi
#+end_center

Ce dernier accord peut être analysé comme une septième sans
fondamentale disposée sur la tonique de /fa mineur harmonique/ :

#+ATTR_HTML: :class plat
| (fa) la^b dont mi | ⟼ | la^b do mi |

Cet accord permet donc de moduler aisément à la *tierce majeure*.


*** Sixte allemande

L’accord de sixte allemande peut être utilisé comme accord vague.

Considérons par exemple la sixte allemande de /do majeur/ :

#+begin_center
la^b do mi^b fa^{#}
#+end_center

En utilisant l’enharmonie /fa^{#} = sol^b/, cet accord peut se
réécrire :

#+begin_center
la^b do mi^b sol^b
#+end_center

Ce dernier accord peut être analysé comme une septième de dominante de
la gamme de /ré^b majeur/.

Cet accord permet donc de moduler aisément à la *seconde mineure*.


*** Synthèse

Le tableau suivant nous livre un exemple des différentes écritures
possibles des accords vagues :

| Accords       | Orthographes         |
|---------------+----------------------|
| 7e dim        | sol^{#} si ré fa     |
|               | si ré fa la^b        |
|               | ré fa la^b do^b      |
|               | mi^{#} sol^{#} si ré |
| 5te aug       | la^b do mi           |
|               | do mi sol^{#}        |
|               | mi sol^{#} si^{#}    |
| 6te allemande | la^b do mi^b fa^{#}  |
|               | la^b do mi^b sol^b   |


* Marches

#+TOC: headlines 1 local


** Introduction

Une *marche* se forme lorsqu’on répète plusieurs fois de suite une
même structure génératrice /S_0/, structure qui se voit transposée
d’un intervalle /I/ constant à chaque nouvelle apparition. On génère
donc une suite :

#+begin_center
S_0 — S_1 — S_2 — S_3 — =...=
#+end_center

où :

#+ATTR_HTML: :class plat
| S_1   | =     | S_0 transposé d’un intervalle I     |
| S_2   | =     | S_1 transposé d’un intervalle I     |
| S_3   | =     | S_2 transposé d’un intervalle I     |
| =...= | =...= | =...=                               |
| S_n   | =     | S_{n-1} transposé d’un intervalle I |

Afin d’éviter la monotonie, le thème générateur de la marche peut être
soumis à des variations, l’essentiel étant de conserver une certaine
continuité dans la structure. On a alors :

#+ATTR_HTML: :class plat
| S_1   | =     | variation de S_0 transposé d’un intervalle I     |
| S_2   | =     | variation de S_1 transposé d’un intervalle I     |
| S_3   | =     | variation de S_2 transposé d’un intervalle I     |
| =...= | =...= | =...=                                            |
| S_n   | =     | variation de S_{n-1} transposé d’un intervalle I |


*** Structure génératrice

Si la structure génératrice est de type :

  - harmonique, on parle de *marche harmonique*

  - mélodique, on parle de *marche mélodique*

  - =...=


*** Transposition

On dit qu’une marche est :

  - *ascendante* lorsque l’intervalle de transposition est ascendant

  - *descendante* lorsque l’intervalle de transposition est descendant


*** Modulante ?

Une marche est dite *modulante* lorsque les transpositions successives
produisent des altérations par rapport à la gamme de départ.

Une marche est dite *non modulante* lorsque les notes s’intègrent dans
la même gamme tout au long de la marche. Afin de ne produire aucune
altération, certaines transpositions sont approximatives. Par exemple,
un intervalle mélodique de quinte peut devenir une quarte, une tierce
majeure peut devenir mineure, etc. Les approximations réalisées dans
une transposition pour rendre une marche non modulante sont appelées
*mutations*.

En pratique, une marche peut être *hybride*, certaines étapes étant
modulantes et d’autres non.

#+begin_center
⁂
#+end_center

Considérons un petit exemple pour bien voir la différence. On part de
la gamme de /do majeur/ et on considère une marche descendant par
quintes. On suppose que la structure génératrice fait entendre toutes
les notes de la gamme :

#+begin_center
do ré mi fa sol la si
#+end_center

Si la transposition est exacte, la variation suivante fera entendre un
/si^b/ en altération, la marche est donc modulante :

#+begin_center
fa sol la /si^b/ do ré mi
#+end_center

Si la marche est non modulante, la variation suivante ne fera entendre
aucune altération :

#+begin_center
fa sol la /si/ do ré mi
#+end_center

Toutes les notes sont alors transposées d’une quinte juste, excepté le
/fa/ de la gamme de départ qui descent d’une quinte diminuée pour se
transformer en /si/ naturel.


** Marches harmoniques

Une *marche harmonique* se forme lorsqu’on répète plusieurs fois de
suite une même structure génératrice harmonique /H_0/, structure qui
se voit transposée d’un intervalle /I/ constant à chaque nouvelle
apparition. On a donc :

#+begin_center
H_0 — H_1 — H_2 — H_3 — =...=
#+end_center

avec :

#+ATTR_HTML: :class plat
| H_1   | =     | variation de H_0 transposé d’un intervalle I     |
| H_2   | =     | variation de H_1 transposé d’un intervalle I     |
| H_3   | =     | variation de H_2 transposé d’un intervalle I     |
| =...= | =...= | =...=                                            |
| H_n   | =     | variation de H_{n-1} transposé d’un intervalle I |

On peut exposer la structure interne du thème en notant la suite
d’accords de chaque variation entre accolades. Voici un exemple de
marche descendant par tierces :

#+ATTR_HTML: :class plat
| { 5 - 6 } | — | { 3 - 4 } | — | { 1 - 2 } | — | =...= |
| H_0       | — | H_1       | — | H_2       | — | =...= |

Une autre montant par secondes :

#+ATTR_HTML: :class plat
| { 5 - 1 } | — | { 6 - 2 } | — | { 7 - 3 } | — | =...= |
| H_0       | — | H_1       | — | H_2       | — | =...= |


*** Transposition

On classe les marches harmoniques suivant leur intervalle de
transposition :

  - quinte ascendante ou descendante
  - tierce ascendante ou descendante
  - seconde ascendante ou descendante

Les structures harmoniques étant considérées comme équivalentes
lorsque l’octave change, les autres marches peuvent être assimilées
aux cas fondamentaux présentés ci-dessus. Ainsi :

  - une marche par quarte est assimilée à une marche par quinte de sens inverse
  - une marche par sixte est assimilée à une marche par tierce de sens inverse
  - une marche par septième est assimilée à une marche par seconde de sens inverse


*** Altération par analogie

La frontière entre marches modulantes et non modulantes n’est pas
toujours bien tracée. Ainsi, il existe des marches essentiellement non
modulantes dans lesquelles certains accords sont altérés afin de
constituer des transpositions exactes d’accords entendus précédemment
dans la même marche. On parle alors d’ *altération par analogie*.


** Marches glissantes

Une *marche glissante* est une marche harmonique où la fin de chaque
variation de la structure génératrice se révèle être également une
introduction à la variation suivante. La musique est alors toujours en
mouvement, et donne l’impression de &laquo; glisser &raquo; d’une
variation à la suivante.

Le dernier accord de /H_n/ est donc *réinterprété* pour devenir le
premier accord de /H_{n + 1}/. En utilisant le symbole « ≡ » pour
désigner la réinterprétation, on a le schéma :

#+begin_center
D_1 — D_2 — =...= — D_m ≡ D_1
#+end_center

où les /D_1/, /D_2/, =...=, /D_m/ sont les degrés des accords de la
structure génératrice. Ce type de marche produit une suite d’accords
du type :

#+begin_center
D_1 — D_2 — =...= — D_m ≡ D_1 — =...= — D_m ≡ D_1 — =...= — D_m ≡ D_1 — =...=
#+end_center

#+begin_center
⁂
#+end_center

Considérons un exemple où la structure génératrice de la marche est
constituée de la suite d’accords :

#+begin_center
4 — 5 — 1
#+end_center

Le dernier accord, du degré 1, doit pouvoir être réinterprété comme un
accord du degré 4 pour entamer la variation suivante.

#+begin_center
4 — 5 — 1 ≡ 4
#+end_center

Nous sommes donc forcés de changer de gamme en déplaçant la tonique
une quarte plus bas pour que le degré 1 devienne un degré 4.

Plaçons nous en /do majeur/ à titre d’illustration. Le degré 1, un
/do/, doit pouvoir être réinterprété comme le degré 4 d’une nouvelle
gamme. Dans cette nouvelle gamme :

  - le degré 4 est un /do/
  - le degré 3 est un /si/
  - le degré 2 est un /la/
  - le degré 1 est un /sol/

La nouvelle gamme est donc celle de /sol majeur/. Comme le /sol/
correspond au degré 5 de la gamme de départ /do majeur/, on peut
réécrire le schéma de la marche sous la forme :

#+begin_center
4 — 5 — 1 ≡ 4 de 5
#+end_center

Ce schéma génère la marche :

#+begin_center
4 — 5 — 1 ≡ 4 de 5 — 5 de 5 — 1 de 5 ≡ 4 de 2 — 5 de 2 — 1 de 2 ≡ =...=
#+end_center

Ce type de marche peut être modulante ou non modulante, suivant que
l’on tient compte ou non des altérations des gammes traversées.

Voici quelques exemples de réinterprétation  :

  - 2 — 5 — 1 ≡ 2
  - 6 — 2 — 5 — 1 ≡ 6


*** Descente de quinte

Le schéma :

#+begin_center
5 — 1 ≡ 5
#+end_center

produit la suite :

#+begin_center
5 — 1 ≡ 5 de 4 — 1 de 4 ≡ 5 de 7 — 1 de 7 ≡ 5 de 3 — 1 de 3 ≡ 5 de 6 — =...=
#+end_center

Par rapport à la gamme de départ, on retrouve donc le cycle des quintes :

#+begin_center
5 — 1 — 4 — 7 — 3 — 6 — 2 — 5 — 1 — =...=
#+end_center

On peut réaliser ce schéma en utilisant des accords de septième ou de
neuvième, une note ou plus étant résolue à chaque accord tandis qu’une
autre devient dissonante.

En voici un exemple avec des accords de septième, aux altérations
près :

#+ATTR_HTML: :class plat
| S | : | fa   | /fa/ | /mi/ | mi   |
| A | : | /do/ | /si/ | /si/ | /la/ |
| T | : | la   | ré   | sol  | do   |
| B | : | ré   | sol  | do   | fa   |

Au premier enchaînement, le /do/ se résout en /si/ à l’alto, au second
le /fa/ se résout en /mi/ au soprano, et au dernier le /si/ se résout
en /la/ à l’alto.


** Marches divertissantes


*** Divertissement modulant

On peut créer une *surprise* élégante en développant une marche
harmonique *non modulante*, suivie d’une *modulation* au ton auquel on
serait arrivé si la marche avait été modulante.

Un petit exemple :

  1. On part de /ré majeur/ qui comporte les altérations : /fa^{#}/,
    /do^{#}/

  2. On fait entendre une structure génératrice contenant les notes /ré
     mi fa^{#} sol la si do^{#}/

  3. On descend les quintes jusqu’au do sans moduler :

     1) /sol la si do^{#} ré mi fa^{#}/

     2) /do^{#} ré mi fa^{#} sol la si/

  4. Surprise : on module en /do majeur/ en faisant entendre un thème
     contenant les notes /do ré mi fa sol la si/


*** Divertissement non modulant

On peut également suivre le procédé inverse lorsqu’on module à un ton
relatif. Utiliser une marche *modulante* qui accumule les altérations
en cours de route, puis *supprimer* toutes les altérations causées par
la marche une fois arrivé au ton désiré.

Un exemple :

  1. On part de /la mineur/ qui ne comporte pas d’altération

  2. On fait entendre un thème contenant les notes /la si do ré mi fa sol/

  3. On descend les quintes jusqu’au /do/ en modulant :

     1) /ré mi fa sol la si^b do/

     2) /sol la si^b do ré mi^b fa/

     3) /do ré mi^b fa sol la^b si^b/

  4. Surprise : on module en /do majeur/ en faisant entendre un thème
     où les altérations causées par la marche sont supprimées : /do ré
     mi fa sol la si/


* Cadences

#+TOC: headlines 1 local


** Introduction

Une *cadence* est une suite d’intervalles ou d’accords qui ponctue le
discours musical par le jeu des tensions et des détentes.

Les chapitres qui suivent abordent les cadences dans l’ordre
historique de leur apparition :

  - les *cadences d’intervalles* faisant intervenir 2 voix

  - les *cadences modales* (Moyen-Âge, Renaissance)

  - les *combinaisons* de cadences d’intervalles, de plus en plus complexes

  - les *cadences tonales*, ou cadences d’accords (Baroque, Classique, Romantisme)

Cet ordre permet de bien comprendre les mécanismes de formation des
cadences. Il met également en évidence leur caractére, depuis la
simplicité et la clarté des cadences d’intervalles et modales, jusqu’à
la richesse harmonique des cadences tonales.

Cette évolution historique vers les cadences tonales, qui sont les
plus utilisées aujourd’hui, ne nous interdit bien sûr pas d’utiliser
les autres types de cadences.


** Tuilage harmonique

Le *tuilage harmonique* est une technique qui consiste à décaler
l’enchaînement des thèmes mélodiques par rapport à l’enchaînement des
accords, en particulier lors des cadences. Il a pour effet de
distraire l’oreille par la mélodie, et donc de faire passer les
enchaînements d’accords en sourdine.

On peut également utiliser le principe du tuilage pour masquer une
modulation.


* Cadences d’intervalles

#+TOC: headlines 1 local


** Introduction

Comme son nom le suggère, une *cadence d’intervalles* est un
enchaînement d’intervalles harmoniques. Cet enchaînement débouche
généralement sur une consonance parfaite (unisson, octave ou quinte).

L’arrivée se fait via un mouvement polyphonique contraire, oblique,
direct ou parallèle.

Le mouvement conjoint a d’abord été omniprésent dans ces cadences
mais, à mesure que le nombre de voix a augmenté dans les oeuvres
polyphoniques, le mouvement disjoint est devenu plus fréquent.


** Cadence contraire

Une *cadence contraire* est une cadence d’intervalles où les deux voix
progressent par mouvement contraire. On distingue :

  - la *cadence extérieure* : la voix supérieure monte et la voix inférieure descend

  - la *cadence intérieure* : la voix supérieure descend et la voix inférieure monte

Pour s’en souvenir, se rappeler que les voix d’une cadence extérieure
(respectivement intérieure) se dirigent vers l’extérieur
(respectivement vers l’intérieur).


*** Conjointe

Une *cadence contraire conjointe* est une cadence contraire où les
deux voix progressent par mouvement conjoint. On distingue :

  - la *cadence extérieure conjointe* : une cadence extérieure où les
    deux voix progressent par mouvement conjoint

  - la *cadence intérieure conjointe* : une cadence intérieure où les
    deux voix progressent par mouvement conjoint

Les cadences les plus appréciées sont celles où l’une des voix
évolue par ton, tandis que l’autre progresse par demi-ton.


**** Arrivée sur unisson

La cadence extérieure conjointe arrivant sur unisson nécessite un
croisement des voix et est donc à utiliser avec précaution. Exemple :

#+ATTR_HTML: :class plat
| S | : | sol | la | (monte)   |
| B | : | si  | la | (descend) |

Par contre, la cadence intérieure conjointe arrivant sur unisson part
d’une tierce, ce qui ne pose aucun problème. Exemple :

#+ATTR_HTML: :class plat
| S | : | si  | la | (descend) |
| B | : | sol | la | (monte)   |


**** Arrivée sur octave

La cadence extérieure arrivant sur octave part d’une sixte. En
voici un exemple :

#+ATTR_HTML: :class plat
| S | : | mi  | fa | (monte)   |
| B | : | sol | fa | (descend) |

La cadence intérieure arrivant sur octave part d’une dixième. En
voici un exemple :

#+ATTR_HTML: :class plat
| S | : | sol | fa | (descend) |
| B | : | mi  | fa | (monte)   |


**** Arrivée sur quinte

La cadence extérieure arrivant sur quinte part d’une tierce. En voici
un exemple :

#+ATTR_HTML: :class plat
| S | : | la | si | (monte)   |
| B | : | fa | mi | (descend) |

La cadence intérieure arrivant sur quinte part d’une septième. En
voici un exemple :

#+ATTR_HTML: :class plat
| S | : | do | si | (descend) |
| B | : | ré | mi | (monte)   |


*** Disjointe

Une *cadence contraire disjointe* est une cadence contraire où au
moins une des voix progresse par mouvement disjoint. Dans ce cas, il
existe deux possibilités :

  - une des voix évolue par mouvement conjoint et l’autre par mouvement disjoint
  - les deux voix évoluent par mouvement disjoint


** Cadence oblique

Une *cadence oblique* est une cadence d’intervalles où les deux voix
progressent par mouvement oblique.


*** Conjointe

Une *cadence oblique conjointe* est une cadence oblique où la voix
mobile progresse par mouvement conjoint.

Exemple :

#+ATTR_HTML: :class plat
| S | : | sol | la | (monte)    |
| B | : | ré  | ré | (constant) |


*** Disjointe

Une *cadence oblique disjointe* est une cadence oblique où la voix
mobile progresse par mouvement disjoint.

Exemple :

#+ATTR_HTML: :class plat
| S | : | la | la |
| B | : | fa | do |


** Cadence directe

Une *cadence directe* est une cadence d’intervalles où les deux voix
progressent par mouvement direct.


*** Conjointe

Une *cadence directe conjointe* est une cadence directe où les deux
voix progressent par mouvement direct conjoint.

Exemple :

#+ATTR_HTML: :class plat
| S | : | la | ré | (monte) |
| B | : | do | ré | (monte) |


*** Disjointe

Une *cadence directe disjointe* est une cadence directe où les deux
voix progressent par mouvement direct disjoint.

Exemple :

#+ATTR_HTML: :class plat
| S | : | la | ré | (monte) |
| B | : | fa | ré | (monte) |


** Cadence parallèle

Une *cadence parallèle* est une cadence d’intervalles où les deux voix
progressent par mouvement parallèle. On distingue :

  - la *cadence ascendante* : les deux voix montent
  - la *cadence descendante* : les deux voix descendent


**** Conjointe

Une *cadence parallèle conjointe* est une cadence parallèle où les
deux voix progressent par mouvement conjoint.

Exemple :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| B | : | do  | ré |


**** Disjointe

Une *cadence parallèle disjointe* est une cadence parallèle où les
deux voix progressent par mouvement disjoint.

Exemple :

#+ATTR_HTML: :class plat
| S | : | sol | si |
| B | : | do  | mi |


**** Contraste

On pourrait arguer que la cadence parallèle n’est pas tout à fait une
cadence, car une véritable cadence nécessite un effet de contraste, ce
qui n’est pas le cas lorsque le premier intervalle harmonique de
l’enchaînement est identique au second. Une solution pour produire un
tel contraste est de faire évoluer une des voix par seconde mineure
tandis que l’autre progresse d’une seconde majeure. Cela reste un
mouvement parallèle, car les deux voix progressent d’une seconde, mais
le premier intervalle est alors dissonant, produisant une détente lors
de l’arrivée sur la consonance parfaite.

Dans le cas d’une arrivée sur quinte, le premier intervalle est alors
nécessairement une quinte diminuée. Exemple de cadence ascendante :

#+ATTR_HTML: :class plat
| S | : | fa | sol |
| B | : | si | do  |

Exemple de cadence descendante :

#+ATTR_HTML: :class plat
| S | : | fa | mi |
| B | : | si | la |

Dans le cas d’une arrivée sur octave, le contraste impose de partir
d’une octave diminuée. Exemple de cadence ascendante :

#+ATTR_HTML: :class plat
| S | : | si^b | do |
| B | : | si   | do |

Exemple de cadence descendante :

#+ATTR_HTML: :class plat
| S | : | ré   | do |
| B | : | ré^b | do |


* Cadences modales

#+TOC: headlines 1 local


** Introduction

Une cadence construite à partir d’intervalles harmoniques possède une
couleur musicale caractéristique. Cette couleur musicale dépend des
intervalles mélodiques parcourus par les voix lors de l’enchaînement.
Or, ces intervalles mélodiques sont eux-mêmes tributaires de la basse
amenée par la cadence, note qui correspond généralement au mode
utilisé. Pour cette raison, les cadences construites à partir
d’intervalles harmoniques nous amènent naturellement aux *cadences
modales*.

Toute cadence modale peut donc être associée au mode d’une gamme
naturelle, cette gamme ayant pour tonique la basse amenée par la
cadence :

  - fa, pour une cadence lydienne
  - do, pour une cadence ionienne
  - sol, pour une cadence mixolydienne
  - ré, pour une cadence dorienne
  - la, pour une cadence éolienne
  - mi, pour une cadence phrygienne
  - si, pour une cadence locrienne

Suivant la consonance parfaite utilisée, trois cas peuvent se
présenter. Lors d’une arrivée sur :

  - unisson, le mode est celui de la note amenée par la cadence,
    identique sur les deux voix

  - octave, le mode est celui de la note amenée par la cadence,
    identique à l’octave près sur les deux voix

  - quinte, le mode est celui de la basse amenée par la cadence


** Cadence lydienne

La *cadence lydienne* est liée au mode lydien, le mode de /fa/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| B | : | sol | fa |

on remarque que la voix supérieure monte d’un demi-ton, tandis que la
voix inférieure descend d’un ton.

On observe les mêmes intervalles mélodiques lors d’une arrivée sur
quinte, dont voici un exemple :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| B | : | sol | fa |


*** Cadence Landini

La *cadence Landini* porte le nom d’un célèbre compositeur italien du
14e siècle. Une étape intermédiaire est ajoutée à la cadence lydienne,
sous la forme d’une cadence oblique conjointe arrivant sur quinte. La
basse reste constante durant cette étape, ce qui nous donne :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  |
| B | : | sol | sol |

Cet enchaînement est suivi de l’arrivée sur une octave identique
à celle de la cadence lydienne :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | fa |
| B | : | sol | sol | fa |

On remarque que la voix supérieure descend d’une seconde avant de
remonter d’une tierce.


** Cadence ionienne

La *cadence ionienne* est liée au mode ionien, le mode de /do/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | si | do |
| B | : | ré | do |

on remarque que la voix supérieure monte d’un demi-ton, tandis que la voix
inférieure descend d’un ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | fa | sol |
| B | : | ré | do  |

on remarque que les deux voix évoluent par ton.


** Cadence mixolydienne

La *cadence mixolydienne* est liée au mode mixolydien, le mode de /sol/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | fa | sol |
| B | : | la | sol |

on remarque que les deux voix évoluent par ton.

Même constatation lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | do | ré  |
| B | : | la | sol |


** Cadence dorienne

La *cadence dorienne* est liée au mode dorien, le mode de /ré/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | do | ré |
| B | : | mi | ré |

on remarque que les deux voix évoluent par ton.

Même constatation lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| B | : | mi  | ré |


** Cadence éolienne

La *cadence éolienne* est liée au mode éolien, le mode de /la/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| B | : | si  | la |

on remarque que les deux voix évoluent par ton.

Même constatation lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| B | : | si | la |


** Cadence phrygienne

La *cadence phrygienne* est liée au mode phrygien, le mode de /mi/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| B | : | fa | mi |

on remarque que la voix supérieure monte d’un ton, tandis que la voix
inférieure descend d’un demi-ton.

On observe les mêmes intervalles mélodiques lors d’une arrivée sur
quinte, dont voici un exemple :

#+ATTR_HTML: :class plat
| S | : | la | si |
| B | : | fa | mi |


** Cadence locrienne

La *cadence locrienne* est liée au mode locrien, le mode de /si/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | la | si |
| B | : | do | si |

on remarque que la voix supérieure monte d’un ton, tandis que la voix
inférieure descend d’un demi-ton.

L’arrivée sur quinte n’est pas vraiment utilisée, car elle déboucherait
sur une quinte diminuée, intervalle instable qui ne convient pas à la
fin d’une cadence :

#+ATTR_HTML: :class plat
| S | : | mi | fa |
| B | : | do | si |


** Autres modes


*** Acoustique

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | si^b | do |
| B | : | ré   | do |

on remarque que les deux voix évoluent par ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | fa^{#} | sol |
| B | : | ré     | do  |

on remarque que la voix supérieure monte d’un demi-ton, tandis que la
voix inférieure descend d’un ton.


*** Napolitain

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | ré^{#} | mi |
| B | : | fa     | mi |

on remarque que les deux voix évoluent par demi-ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | la | si |
| B | : | fa | mi |

on remarque que la voix supérieure monte d’un ton, tandis que la voix
inférieure descend d’un demi-ton.


*** Tzigane avec seconde mineure

Il s’agit d’une variante du mode tzigane avec le degré 2 abaissé :

#+begin_center
la si^b do ré^{#} mi fa sol^{#} la
#+end_center

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| B | : | si^b    | la |

on remarque que les deux voix évoluent par demi-ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | ré^{#} | mi |
| B | : | si^b   | la |

on remarque que les deux voix évoluent par demi-ton. Notons aussi que
le premier intervalle harmonique est une tierce augmentée.


** Tableau récapitulatif

| Mode               | Intervalle  | Intervalle     | Intervalle    |
|                    | de la basse | vers la quinte | vers l’octave |
|--------------------+-------------+----------------+---------------|
| lydien             | ton         | demi-ton       | demi-ton      |
| ionien             | ton         | ton            | demi-ton      |
| mixolydien         | ton         | ton            | ton           |
| dorien             | ton         | ton            | ton           |
| éolien             | ton         | ton            | ton           |
| phrygien           | demi-ton    | ton            | ton           |
| locrien            | demi-ton    | demi-ton       | ton           |
|--------------------+-------------+----------------+---------------|
| acoustique         | ton         | demi-ton       | ton           |
| napolitain         | demi-ton    | ton            | demi-ton      |
| tzigane avec 2de m | demi-ton    | demi-ton       | demi-ton      |


** Transposition

Toute transposition exacte d’une cadence modale sera caractérisée par
les mêmes intervalles mélodiques que la cadence d’origine. La cadence
modale transposée pourra donc être associée au même mode que la
cadence originale.


* Combinaisons de cadences d’intervalles

#+TOC: headlines 1 local


** Cadences à trois voix

Les cadences à trois voix s’obtiennent en combinant deux cadences
d’intervalles à deux voix.


*** Cadence lydienne à trois voix

La *cadence lydienne à trois voix*, liée au mode du même nom, résulte
de la combinaison de deux cadences extérieures conjointes, cadences
qui partagent une même basse et procédent par demi-ton ascendant sur
la voix supérieure. La première de ces cadences débouche sur une
octave et la seconde sur une quinte. La cadence lydienne à trois voix
est aussi appelée *cadence Machaut*, du nom d’un célèbre compositeur
du 14e siècle.

Voici un exemple de construction, avec tout d’abord l’arrivée sur
octave :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| B | : | sol | fa |

ensuite l’arrivée sur quinte :

#+ATTR_HTML: :class plat
| A | : | si  | do |
| B | : | sol | fa |

et la cadence combinée qui en résulte :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | si  | do |
| B | : | sol | fa |


**** Cadence Landini à trois voix

La *cadence Landini à trois voix* est une variante de la cadence
Machaut. Une étape intermédiaire est ajoutée, sous la forme d’une
cadence oblique conjointe arrivant sur quinte et faisant intervenir
les voix extrêmes. La basse et la voix médiane restent constantes
durant cette étape, ce qui nous donne :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  |
| A | : | si  | si  |
| B | : | sol | sol |

On retrouve ensuite les arrivées sur octave et sur quinte de la
cadence Machaut :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | fa |
| A | : | si  | si  | do |
| B | : | sol | sol | fa |


*** Cadence phrygienne à trois voix

La *cadence phrygienne à trois voix*, liée au mode du même nom,
résulte de la combinaison de deux cadences extérieures conjointes,
cadences qui partagent une même basse et procédent par demi-ton
descendant sur la voix inférieure. La première de ces cadences
débouche sur une octave et la seconde sur une quinte.

Voici un exemple de construction, avec tout d’abord l’arrivée sur
octave :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| B | : | fa | mi |

ensuite l’arrivée sur quinte :

#+ATTR_HTML: :class plat
| A | : | la | si |
| B | : | fa | mi |

et la cadence combinée qui en résulte :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| A | : | la | si |
| B | : | fa | mi |


*** Ajout d’une voix

Une autre variété de cadence à trois voix se construit en ajoutant une
voix à une cadence contraire conjointe. Dans ce cas, la voix ajoutée
est généralement constante ou disjointe, afin de produire un contraste
avec les autres mouvements mélodiques.

Voici un exemple d’ajout d’une voix constante (ici à l’alto) à une
cadence extérieure conjointe arrivant sur octave. La voix
supplémentaire est choisie pour arriver une quinte au-dessus de la
basse finale :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | do  | do |
| B | : | sol | fa |

Voici un exemple d’ajout d’une voix disjointe (ici à la basse) à une
cadence extérieure conjointe arrivant sur octave. La voix
supplémentaire descend d’une quinte pour arriver à l’octave sous les
autres notes finales :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | sol | fa |
| B | : | do  | fa |


** Cadences à quatre voix

Lorsqu’on ajoute une voix constante /et/ une voix disjointe à une
cadence contraire conjointe, on obtient une cadence à quatre voix.

Pour illustrer ce procédé, partons d’une cadence extérieure conjointe
arrivant sur octave. Dans le cas d’une cadence lydienne, nous
obtenons :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | do  | do |
| T | : | sol | fa |
| B | : | do  | fa |

Dans le cas d’une cadence ionienne, on obtient :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | sol | do  |


** Cadence parfaite

Dans une cadence à quatre voix, le mouvement conjoint descendant peut
être remplacé par un mouvement conjoint ascendant. On arrive alors une
tierce au-dessus de la basse finale.

Dans le cas d’une cadence ionienne, on obtient :

#+ATTR_HTML: :class plat
| S | : | si   | do   |
| A | : | sol  | sol  |
| T | : | /ré/ | /mi/ |
| B | : | sol  | do   |

Nous avons ainsi construit une *cadence parfaite*.


* Cadences tonales

#+TOC: headlines 1 local


** Introduction

Les cadences tonales sont divisées en deux catégories :

  - les cadences *conclusives* concluent une partie du discours musical
  - les cadences *ouvertes* relancent la musique

En régle générale, les cadences conclusives sont celles qui se
terminent par un accord de tonique à l’état fondamental. Les autres
cadences sont ouvertes.


* Cadence parfaite

#+TOC: headlines 1 local

** Introduction

La *cadence parfaite*, aussi appelée *cadence authente*, est la
cadence conclusive la plus répandue. Elle enchaîne un accord de
dominante du degré 5 avec un accord de tonique du degré 1. L’accord de
dominante peut être un accord parfait, une septième ou une neuvième.
L’accord de tonique est un accord parfait à l’état fondamental.
L’accord de dominante peut être renversé sans remettre en cause le
caractère conclusif.

/Remarque/ : la cadence parfaite peut être vue comme une évolution de
la cadence Machaut (cadence modale).


** Mode majeur

#+TOC: headlines 1 local

*** Introduction

Nous classons les différentes variantes de la cadence parfaite suivant
le type de l’accord de dominante.


*** Accord parfait

Nous prenons comme exemple la gamme de /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | sol | sol |
| T | : | ré  | mi  |
| B | : | sol | do  |


**** Renversements

Voici un exemple en /do majeur/ avec un premier renversement :

#+ATTR_HTML: :class plat
| S | : | ré  | do  |
| A | : | sol | sol |
| T | : | ré  | mi  |
| B | : | si  | do  |


*** Quinte augmentée

La quinte de l’accord de dominante peut être augmentée afin de se
rapprocher de la tierce de l’accord de tonique. Nous prenons comme
exemple la gamme de /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si     | do  |
| A | : | sol    | sol |
| T | : | ré^{#} | mi  |
| B | : | sol    | do  |


*** Septième de dominante

#+TOC: headlines 1 local

**** Quatuor

Considérons le cas de l’accord de 7e de dominante et disposons-le sur
un quatuor. En /do majeur/, si on veut conserver les deux accords
complets, il faut écrire :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | mi  |
| T | : | ré  | sol |
| B | : | sol | do  |

On note la résolution du triton /fa — si/ vers la sixte /mi — do/,
caractéristique des cadences parfaites utilisant une 7e de dominante.

Cette disposition génère des quintes consécutives, ici entre le ténor
et la basse : /sol — ré/ est en effet suivie de /do — sol/. Si l’on
souhaite éviter cette disposition, il est toujours possible de
supprimer la quinte d’un des deux accords, ou de renverser l’accord de
dominante.


**** Suppression de la quinte

Voici une variante d’une cadence parfaite en /do majeur/ où l’on a
supprimé la quinte de l’accord de septième de dominante, en la
remplaçant par une doublure de la fondamentale :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | mi  |
| T | : | sol | sol |
| B | : | sol | do  |

Voici une autre variante où c’est la quinte de l’accord de tonique qui
est supprimée :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | fa  | mi |
| T | : | ré  | do |
| B | : | sol | do |


**** Renversements

Certains renversements de l’accord de dominante permettent de
conserver les deux accords complets sur quatre voix sans générer de
quintes consécutives. Voici un exemple en /do majeur/ avec un premier
renversement :

#+ATTR_HTML: :class plat
| S | : | fa  | mi  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | si  | do  |

un autre avec un second renversement :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | mi  |
| T | : | sol | sol |
| B | : | ré  | do  |

et enfin un troisième renversement :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | fa  | mi  |


**** Quintette

Reprenons notre accord de 7e de dominante et disposons-le sur une
polyphonie de cinq voix ou plus. En /do majeur/, on peut écrire un
enchaînement du type :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| M | : | fa  | mi  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | sol | do  |

Cette fois, aucune quinte consécutive n’est observée.


*** Septième sans fondamentale

L’accord de dominante peut être une septième sans fondamentale. Voici
un exemple du premier renversement en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | ré | do  |
| A | : | fa | mi  |
| T | : | ré | sol |
| B | : | si | do  |

Voici un exemple dans un second renversement avec la quinte doublée :

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | mi  |
| T | : | ré | sol |
| B | : | ré | do  |

Voici un exemple dans un second renversement avec la septième
doublée :

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | mi  |
| T | : | fa | sol |
| B | : | ré | do  |


*** Neuvième de dominante

L’accord de dominante peut être une neuvième. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la  | sol |
| M | : | si  | do  |
| A | : | fa  | mi  |
| T | : | ré  | do  |
| B | : | sol | do  |


*** Neuvième sans fondamentale

L’accord de dominante peut être une neuvième sans fondamentale.
Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la | sol |
| A | : | fa | mi  |
| T | : | ré | do  |
| B | : | si | do  |


** Mode mineur

#+TOC: headlines 1 local

*** Introduction

En mineur, l’accord de dominante intègre généralement un degré 7
haussé d’un demi-ton afin de le transformer en sensible inférieure
(mode mineur harmonique). On peut aussi utiliser une tierce picarde
sur l’accord de tonique lorsque ce procédé permet de renforcer la
résolution.


*** Accord parfait

Nous prenons comme exemple la gamme de /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | mi      | mi |
| T | : | si      | do |
| B | : | mi      | la |


**** Renversements

Voici un exemple en /la mineur/ avec un premier renversement :

#+ATTR_HTML: :class plat
| S | : | si      | la |
| A | : | mi      | mi |
| T | : | si      | do |
| B | : | sol^{#} | la |


*** Septième de dominante

#+TOC: headlines 1 local

**** Quatuor

Considérons le cas de l’accord de 7e de dominante et disposons-le sur
un quatuor. En /la mineur/, si on veut conserver les deux accords
complets, il faut écrire :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | si      | mi     |
| B | : | mi      | la     |

On note l’utilisation de la tierce picarde /la — do^{#}/ afin de
renforcer la résolution.

On observe également la résolution de la quarte augmentée
/ré — sol^{#}/ vers la sixte /do^{#} — la/.

Cette disposition génère des quintes consécutives. Si l’on souhaite
les éviter, on peut supprimer la quinte d’un des deux accords, ou
renverser l’accord de dominante.


**** Suppression de la quinte

Voici une variante d’une cadence parfaite en /la mineur/ où l’on a
supprimé la quinte de l’accord de septième de dominante, en la
remplaçant par une doublure de la fondamentale :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | mi      | mi     |
| B | : | mi      | la     |

Voici une autre variante où c’est la quinte de l’accord de tonique qui
est supprimée :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | si      | la     |
| B | : | mi      | la     |


**** Renversements

Certains renversements de l’accord de dominante permettent de
conserver les deux accords complets sur quatre voix sans générer de
quintes consécutives. Voici un exemple en /la mineur/ avec un premier
renversement :

#+ATTR_HTML: :class plat
| S | : | ré      | do^{#} |
| A | : | mi      | mi     |
| T | : | si      | la     |
| B | : | sol^{#} | la     |

un autre avec un second renversement :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | mi      | mi     |
| B | : | si      | la     |

et enfin un troisième renversement :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | mi      | mi     |
| T | : | si      | la     |
| B | : | ré      | do^{#} |


**** Quintette

Reprenons notre accord de 7e de dominante et disposons-le sur une
polyphonie de cinq voix ou plus. En /la mineur/, on peut écrire un
enchaînement du type :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| M | : | ré      | do^{#} |
| A | : | mi      | mi     |
| T | : | si      | la     |
| B | : | mi      | la     |

Cette fois, aucune quinte consécutive n’est observée.


*** Septième sans fondamentale

L’accord de dominante peut être une septième sans fondamentale. Voici
un exemple du premier renversement en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | si      | la     |
| A | : | ré      | do^{#} |
| T | : | si      | mi     |
| B | : | sol^{#} | la     |

Voici un exemple dans un second renversement avec la quinte doublée :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | si      | mi     |
| B | : | si      | la     |

Voici un exemple dans un second renversement avec la septième doublée :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | ré      | mi     |
| B | : | si      | la     |


*** Neuvième de dominante

L’accord de dominante peut être une neuvième. Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | fa      | mi     |
| M | : | sol^{#} | la     |
| A | : | ré      | do^{#} |
| T | : | si      | la     |
| B | : | mi      | la     |


*** Neuvième sans fondamentale

L’accord de dominante peut être une neuvième sans fondamentale.
Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | fa      | mi     |
| A | : | ré      | do^{#} |
| T | : | si      | la     |
| B | : | sol^{#} | la     |


* Autres cadences conclusives

#+TOC: headlines 1 local


** Introduction

La cadence parfaite est la cadence conclusive la plus répandue, mais
il en existe d’autres. En voici quelques unes.


** Cadence plagale

La *cadence plagale* est une cadence conclusive qui enchaîne un accord
de sous-dominante du degré 4 avec un accord de tonique du degré
1. L’accord de tonique est un accord parfait à l’état fondamental.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | ré | do^{#} |
| A | : | la | la     |
| T | : | fa | mi     |
| B | : | ré | la     |

Remarquons que l’accord de sous-dominante peut être renversé sans
remettre en cause le caractère conclusif :

#+ATTR_HTML: :class plat
| S | : | la | la     |
| A | : | fa | mi     |
| T | : | ré | do^{#} |
| B | : | la | la     |

Une des utilisations possibles de la cadence plagale est de la placer
à la suite d’une cadence parfaite afin d’en renforcer le caractère
conclusif. Ce procédé est naturellement à réserver aux fins de
sections importantes d’une oeuvre musicale :

  - fin d’un mouvement
  - conclusion finale


** Cadence Bach

La *cadence Bach* utilise un accord de neuvième de dominante sans
fondamentale dans un troisième renversement. Elle enchaîne ensuite sur
un accord de tonique à l’état fondamental. Attention, le nombre de
renversements se calcule par rapport à la fondamentale, même si
celle-ci est supprimée. En /la mineur/, nous aurons donc :

#+ATTR_HTML: :class plat
| (mi) sol^{#} si ré fa | ⟼ | ré fa (mi) sol^{#} si |

On obtient finalement l’accord de dominante :

#+begin_center
ré fa sol^{#} si
#+end_center

Une disposition possible pour la cadence Bach s’écrit :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | si      | do |
| T | : | fa      | mi |
| B | : | ré      | la |

Cette cadence combine l’évolution sensible inférieure — tonique
(/sol^{#} — la/), typique de la cadence parfaite, avec le saut
sous-dominante — tonique (/ré — la/) à la basse, typique de la cadence
plagale. On note aussi la résolution du triton /fa — si/ vers la sixte
/mi — do/, caractéristique du relatif /do majeur/. La cadence Bach est
en quelque sorte une cadence polymorphe.

Si on souhaite placer une tierce picarde dans l’accord de résolution,
on aura :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | si      | do^{#} |
| T | : | fa      | mi     |
| B | : | ré      | la     |


** Cadence fauréenne modale

La *cadence fauréenne modale* est semblable à la cadence Bach, mais
elle n’utilise pas de sensible.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | si  | do |
| T | : | fa  | mi |
| B | : | ré  | la |

Si on souhaite placer une tierce picarde dans l’accord de résolution,
on aura :

#+ATTR_HTML: :class plat
| S | : | sol | la     |
| A | : | si  | do^{#} |
| T | : | fa  | mi     |
| B | : | ré  | la     |


** Substitution tritonique

La *substitution tritonique* remplace le premier accord de la cadence
parfaite (dans sa version septième de dominante sur le degré 5) par un
accord respectant les mêmes écarts mais construit un triton plus bas,
sur le degré 2 abaissé d’un demi-ton (variante de l’accord
napolitain). Voici un exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | la^b | la     |
| A | : | fa   | mi     |
| T | : | ré   | do^{#} |
| B | : | si^b | la     |

On note que le /la^b/ est l’enharmonie de la sensible inférieure
/sol^{#}/. Cette cadence est très prisée dans la musique de jazz.


** Cadence italienne

La *cadence italienne* enchaîne les degrés forts de l’harmonie tonale,
en terminant par une cadence parfaite :

#+begin_center
4 — 5 — 1
#+end_center

Exemple de réalisation sur cinq voix, en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la | si  | do  |
| M | : | fa | fa  | mi  |
| A | : | do | ré  | do  |
| T | : | fa | sol | sol |
| B | : | do | sol | do  |


*** Accord de tonique intercalé

Le degré 1 au second renversement est fréquemment intercalé entre
les degrés 4 et 5, donnant ainsi lieu à la suite d’accords :

#+begin_center
4  —  1  —  5  —  1
#+end_center

Exemple de réalisation sur cinq voix, en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do | do  | si  | do  |
| M | : | la | sol | fa  | mi  |
| A | : | fa | mi  | ré  | do  |
| T | : | fa | sol | sol | sol |
| B | : | fa | sol | sol | do  |


*** Dominante auxiliaire

Lorsque l’accord de sous-dominante est remplacé par un accord de
dominante auxiliaire, nous avons :

#+begin_center
2  —  5  —  1
#+end_center

Exemple de réalisation sur cinq voix, en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la | si  | do  |
| M | : | fa | fa  | mi  |
| A | : | ré | ré  | do  |
| T | : | fa | sol | sol |
| B | : | ré | sol | do  |


**** Accord de tonique intercalé

Avec un accord de tonique intercalé :

#+begin_center
2  —  1  —  5  —  1
#+end_center

#+ATTR_HTML: :class plat
| S | : | ré | do  | si  | do  |
| M | : | la | sol | fa  | mi  |
| A | : | fa | mi  | ré  | do  |
| T | : | ré | sol | sol | sol |
| B | : | ré | sol | sol | do  |


* Cadence imparfaite

#+TOC: headlines 1 local


** Introduction

La *cadence imparfaite* est une cadence *ouverte* qui enchaîne une
dominante avec un *accord de tonique renversé*, ce qui permet de
relancer la musique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | fa  | mi  |
| A | : | ré  | do  |
| T | : | si  | do  |
| B | : | sol | sol |

Lors d’une cadence imparfaite, il n’est pas toujours possible de
réaliser les résolutions habituelles, à savoir la sensible inférieure
vers la tonique et, dans le cas d’une septième de dominante, la 7e
vers la médiante. On parle alors de résolution irrégulière. Voici un
exemple de résolution irrégulière d’une 7e en /do majeur/, avec
l’accord de dominante au second renversement :

#+ATTR_HTML: :class plat
| S | : | si   | do    |
| A | : | /fa/ | /sol/ |
| T | : | sol  | sol   |
| B | : | ré   | mi    |

Si on avait fait évoluer le /fa/ vers le /mi/, ce dernier aurait été
doublé. Or le /mi/ est le degré 3 de la tonalité, degré faible que
l’on évite en général d’accentuer.

Par contre, la résolution suivante est régulière, avec l’accord de
dominante au troisième renversement :

#+ATTR_HTML: :class plat
| S | : | ré  | sol |
| A | : | sol | sol |
| T | : | si  | do  |
| B | : | fa  | mi  |


** Septième sans fondamentale

L’accord de dominante peut être une septième sans fondamentale.
Exemples du troisième renversement en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | sol |
| T | : | ré | do  |
| B | : | fa | mi  |

et :

#+ATTR_HTML: :class plat
| S | : | ré | do  |
| A | : | ré | sol |
| T | : | si | do  |
| B | : | fa | mi  |


** Neuvième sans fondamentale

L’accord de dominante peut être une neuvième sans fondamentale.
Exemple du second renversement en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | ré      | mi |
| T | : | fa      | mi |
| B | : | si      | do |


* Demi-cadence

#+TOC: headlines 1 local

** Introduction

La *demi-cadence* est une cadence *ouverte* qui enchaîne un accord de
degré quelconque avec un accord de dominante :

#+begin_center
X  —  Dominante
#+end_center


** Sous-dominante

#+TOC: headlines 1 local

*** Introduction

Un choix fréquent de demi-cadence est celui où la sous-dominante
précéde la dominante. Exemple de réalisation en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la | sol |
| A | : | fa | ré  |
| T | : | do | si  |
| B | : | fa | sol |

Autre exemple, cette fois avec un accord de sous-dominante au premier
renversement, où la tonique est redoublée :

#+ATTR_HTML: :class plat
| S | : | fa | sol |
| A | : | do | ré  |
| T | : | do | si  |
| B | : | la | sol |


*** Cadence baroque

La *cadence baroque* est le plus souvent utilisée en mineur. Elle fait
suivre un accord parfait de sous-dominante au premier renversement
avec un accord parfait majeur à la dominante.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | ré | mi      |
| A | : | la | si      |
| T | : | la | sol^{#} |
| B | : | fa | mi      |

/Remarque/ : la cadence baroque peut être vue comme une évolution de
la cadence phrygienne (cadence modale).


*** Cadence fauréenne

La *cadence fauréenne* enchaîne un accord de sous-dominante dans son
second renversement avec un accord de dominante. L’accord de
sous-dominante est altéré si nécessaire afin d’obtenir les mêmes
écarts qu’une septième de dominante. Exemple en /la mineur/ :

#+begin_center
ré fa^{#} la do
#+end_center

La cadence s’écrit donc :

#+ATTR_HTML: :class plat
| S | : | fa^{#} | sol |
| A | : | ré     | mi  |
| T | : | do     | si  |
| B | : | la     | mi  |


** Dominante auxiliaire

#+TOC: headlines 1 local

*** Introduction

On associe souvent l’accord de dominante avec un accord de dominante
auxiliaire. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | ré | ré  |
| A | : | la | si  |
| T | : | fa | sol |
| B | : | ré | sol |

Autre exemple, cette fois avec une dominante auxiliaire sous la forme
d’un accord de septième altéré :

#+ATTR_HTML: :class plat
| S | : | do     | si  |
| A | : | la     | sol |
| T | : | ré     | ré  |
| B | : | fa^{#} | sol |


*** Sixte française

Parmi les accords de dominante auxiliaire, la sixte française, ici
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do     | si  |
| A | : | fa^{#} | sol |
| T | : | ré     | ré  |
| B | : | la^b   | sol |


*** Sixte italienne

Parmi les accords de dominante auxiliaire, la sixte italienne, ici
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do     | si  |
| A | : | fa^{#} | sol |
| T | : | do     | ré  |
| B | : | la^b   | sol |


*** Sixte allemande

Parmi les accords de dominante auxiliaire, la sixte allemande, ici
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do     | si  |
| A | : | fa^{#} | sol |
| T | : | mi^b   | ré  |
| B | : | la^b   | sol |


*** Napolitain

L’accord napolitain figure également parmi les dominantes secondaires.
Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | si^b | sol^{#} |
| A | : | fa   | mi      |
| T | : | ré   | si      |
| B | : | ré   | mi      |

Autre exemple, cette fois l’accord de dominante se présente sous la
forme d’une septième de dominante privée de sa quinte :

#+ATTR_HTML: :class plat
| S | : | si^b | sol^{#} |
| A | : | fa   | mi      |
| T | : | ré   | ré      |
| B | : | ré   | mi      |

L’accord de tonique au second renversement peut également faire
fonction de dominante :

#+ATTR_HTML: :class plat
| S | : | si^b | la |
| A | : | fa   | mi |
| T | : | ré   | do |
| B | : | ré   | mi |


** Sus-dominante

La sus-dominante peut également précéder la dominante. Voici un
exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do | si  |
| A | : | mi | sol |
| T | : | do | ré  |
| B | : | la | sol |


** Tonique

La tonique peut également précéder la dominante. Voici un exemple en
/do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do  | si  |
| A | : | sol | sol |
| T | : | do  | ré  |
| B | : | mi  | sol |


* Sous-demi-cadence

#+TOC: headlines 1 local

** Introduction

La *sous-demi-cadence* est une cadence *ouverte* qui enchaîne un
accord de degré quelconque avec un accord de sous-dominante :

#+begin_center
X   —  Sous-dominante
#+end_center


** Napolitain

L’accord napolitain peut également mener à une sous-dominante, exemple
en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | si^b | la |
| A | : | ré   | ré |
| T | : | fa   | fa |
| B | : | ré   | ré |

En mode majeur, deux notes sont modifiées. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | ré^b | do |
| A | : | fa   | fa |
| T | : | la^b | la |
| B | : | fa   | fa |


** Quinte augmentée

Comme cadence menant à une sous-dominante, notons aussi celle
utilisant un accord de tonique sous forme de quinte augmentée :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | mi      | fa |
| B | : | do      | do |


* Fermeture

#+TOC: headlines 1 local


** Introduction

Une demi-cadence est par nature une cadence ouverte. Il est toutefois
possible de la rendre conclusive en l’enchaînant à un accord de
tonique à l’état fondamental. Il se produit alors une cadence
parfaite :

#+begin_center
X  —  Dominante  —  Tonique
#+end_center

Ce procédé est appelé *fermeture*.

On peut généraliser ce processus à toute cadence qui se termine par un
accord faisant fonction de dominante ou de sous-dominante. Par
exemple, la fermeture d’une sous-demi-cadence nous donnerait :

#+begin_center
X  —  Sous-dominante   —  Tonique
#+end_center


** Cadence italienne

On peut voir une cadence italienne comme la fermeture d’une
demi-cadence où la dominante est amenée par une sous-dominante.

Exemple de réalisation en /do majeur/, avec un accord parfait sur la
dominante :

#+ATTR_HTML: :class plat
| S | : | do | si  | do  |
| A | : | la | sol | sol |
| T | : | fa | ré  | mi  |
| B | : | fa | sol | do  |

Autre exemple, avec cette fois un accord de septième de dominante :

#+ATTR_HTML: :class plat
| S | : | do | si  | do  |
| A | : | la | sol | sol |
| T | : | fa | fa  | mi  |
| B | : | fa | sol | do  |


* Étau

#+TOC: headlines 1 local


** Introduction

Certaines cadences permettent de mettre en évidence la suite mélodique
des degrés 2 et 7, ce qui suggère l’arrivée prochaine de la tonique.
Le degré 1 est donc en quelque sorte pris en étau. Dans les modes
majeur et mineur harmonique, on aura :

#+begin_center
sus-tonique  —  sensible inférieure  —  tonique
#+end_center

Exemple en /do majeur/ :

#+begin_center
ré  —  si  —  do
#+end_center

Si le mode est à double sensible, ou si le degré 2 est altéré afin de
se transformer en sensible supérieure, on aura alors :

#+begin_center
sensible supérieure  —  sensible inférieure  —  tonique
#+end_center

Exemple avec /la/ comme tonique :

#+begin_center
si^b  —  sol^{#}  —  la
#+end_center


** Généralisation

On peut bien entendu construire un étau autour de n’importe quelle
note de la gamme. On a alors le schéma générique :

#+begin_center
Note supérieure — Note inférieure — Note attendue
#+end_center


** Dominante auxiliaire

Considérons la fermeture d’une demi-cadence où la dominante est amenée
par une dominante auxiliaire. Nous disposons les accords de manière à
former un étau autour de la tonique. Exemple de réalisation en /do
majeur/, avec l’étau /ré — si — do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | la   | sol  | sol  |
| T | : | fa   | ré   | mi   |
| B | : | ré   | sol  | do   |

On remarque que la mise en place de l’étau nous oblige à disposer le
/ré/, note commune aux deux premiers accords, sur deux voix
différentes.

Si l’accord de dominante auxiliaire est au premier renversement, nous
avons :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | la   | sol  | sol  |
| T | : | ré   | ré   | mi   |
| B | : | fa   | sol  | do   |

En doublant la sous-dominante, nous avons :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | la   | sol  | sol  |
| T | : | fa   | ré   | mi   |
| B | : | fa   | sol  | do   |


** Accord napolitain

Considérons la fermeture d’une demi-cadence où la dominante est amenée
par un accord napolitain. Nous disposons les accords de manière à
mettre en évidence l’étau à double sensible qui entoure la tonique.
Exemple de réalisation en /la mineur/, avec l’étau
/si^b — sol^{#} — la/ :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /sol^{#}/ | /la/   |
| A | : | ré     | si        | do^{#} |
| T | : | fa     | mi        | mi     |
| B | : | ré     | mi        | la     |

On peut aussi doubler le /si^b/ et disposer l’accord de dominante au
troisième renversement :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /sol^{#}/ | /la/   |
| A | : | fa     | mi        | mi     |
| T | : | /si^b/ | si        | do^{#} |
| B | : | ré     | ré        | la     |

Autre exemple, cette fois l’accord de dominante se présente sous la
forme d’une septième de dominante privée de sa quinte :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /sol^{#}/ | /la/   |
| A | : | ré     | ré        | do^{#} |
| T | : | fa     | mi        | mi     |
| B | : | ré     | mi        | la     |

On peut intercaler un accord parfait de dominante :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /si/ | /sol^{#}/ | /la/   |
| A | : | ré     | mi   | ré        | do^{#} |
| T | : | fa     | sol  | mi        | mi     |
| B | : | ré     | mi   | mi        | la     |

ou un accord de tonique au second renversement :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /la/ | /sol^{#}/ | /la/   |
| A | : | ré     | mi   | ré        | do^{#} |
| T | : | fa     | do   | mi        | mi     |
| B | : | ré     | mi   | mi        | la     |


** Cadence plagale

La cadence plagale se présente parfois avec un accord intermédiaire du
degré 2 séparant les degrés 4 et 1. Cet accord permet de construire un
étau autour de la tierce de l’accord de tonique, c’est à dire le degré
3 de la gamme. Voici un exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | la   | la   | la   |
| T | : | fa   | fa   | mi   |
| B | : | ré   | ré   | la   |

On hausse alors parfois la tierce de l’accord de sous-dominante, afin
de mettre en évidence une descente chromatique jusqu’à la quinte de
l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /ré/     | /si/ | /do/ |
| A | : | la       | la   | la   |
| T | : | /fa^{#}/ | /fa/ | /mi/ |
| B | : | ré       | ré   | la   |

Voici le même exemple transposé en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /ré/   | /mi/  |
| A | : | do   | do     | do    |
| T | : | /la/ | /la^b/ | /sol/ |
| B | : | fa   | fa     | do    |


* Cadences irrégulières

#+TOC: headlines 1 local


** Introduction

Une *cadence irrégulière* est une cadence où l’accord final n’est pas
celui attendu.


** Cadence rompue

La *cadence rompue* est une cadence parfaite où l’accord de tonique
est remplacé par un accord de sus-dominante :

#+begin_center
Dominante   —  Sus-dominante
#+end_center


*** Majeur

En voici un exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | sol | mi |
| T | : | ré  | do |
| B | : | sol | la |

Autre exemple avec un accord de septième de dominante :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | fa  | mi |
| T | : | ré  | do |
| B | : | sol | la |

Autre exemple où la quinte de l’accord de dominante est supprimée :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | fa  | mi |
| T | : | sol | la |
| B | : | sol | do |


*** Mineur

En voici un exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | mi      | do |
| T | : | si      | la |
| B | : | mi      | fa |

Autre exemple avec un accord de septième de dominante :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | ré      | do |
| T | : | si      | la |
| B | : | mi      | fa |

Autre exemple où la quinte de l’accord de dominante est supprimée :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | ré      | do |
| T | : | mi      | fa |
| B | : | mi      | la |


** Sous-dominante

On peut aussi remplacer l’accord de tonique d’une cadence parfaite par
un accord de sous-dominante.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | ré  | fa |
| T | : | si  | do |
| B | : | sol | fa |

Autre exemple, avec septième de dominante sans la quinte :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | fa  | fa |
| T | : | si  | do |
| B | : | sol | fa |

Si on souhaite plutôt doubler la tonique afin de la mettre en
évidence, on a alors :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | ré  | do |
| T | : | si  | do |
| B | : | sol | fa |

On peut ajouter une cinquième voix afin d’introduire une descente de
quinte à la basse, rapprochant ainsi cette cadence de la cadence
parfaite :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| M | : | ré  | do |
| A | : | si  | do |
| T | : | sol | fa |
| B | : | sol | do |


** Médiante

On peut aussi remplacer l’accord de tonique d’une cadence parfaite par
un accord de médiante.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | sol | sol |
| A | : | ré  | mi  |
| T | : | si  | si  |
| B | : | sol | sol |

Autre exemple :

#+ATTR_HTML: :class plat
| S | : | fa  | mi  |
| A | : | si  | si  |
| T | : | sol | sol |
| B | : | ré  | sol |


* Cadences modulantes

#+TOC: headlines 1 local


** Introduction

Une *cadence modulante* est une cadence irrégulière qui dévie vers un
accord appartenant à une autre tonalité, ce qui peut provoquer une
modulation. On a alors le schéma :

#+begin_center
X  —  Y de Z
#+end_center

où /X/ peut être une fonction de dominante, de sous-dominante, etc.


** Sous-dominante

Il est possible de moduler en produisant un accord proche d’un accord
de tonique, mais altéré pour devenir un accord 5 de 4. Cet exemple
utilise un accord de dominante de /la mineur/ suivi d’un accord de
neuvième de dominante de /ré mineur/ :

#+ATTR_HTML: :class plat
| S | : | si      | si^b   |
| A | : | sol^{#} | sol    |
| T | : | ré      | do^{#} |
| B | : | mi      | la     |


** Relatif mineur

Il est possible de moduler au relatif mineur en faisant suivre
l’accord de dominante de la tonalité de départ par celui de la
tonalité relative mineure.

Voici un exemple qui part de /do majeur/ et qui module vers /la
mineur/ :

#+ATTR_HTML: :class plat
| S | : | fa  | mi      |
| A | : | ré  | ré      |
| T | : | si  | si      |
| B | : | sol | sol^{#} |


** Relatif majeur

Il est possible de moduler au relatif majeur en faisant suivre
l’accord de dominante de la tonalité de départ par celui de la
tonalité relative majeure.

Voici un exemple qui part de /la mineur/ et qui module vers /do
majeur/ :

#+ATTR_HTML: :class plat
| S | : | mi      | fa  |
| A | : | ré      | ré  |
| T | : | si      | si  |
| B | : | sol^{#} | sol |


* Amener les cadences

#+TOC: headlines 1 local

** Introduction

Certains enchaînements servent d’introduction à une cadence.


** Quarte et sixte cadentielle
:PROPERTIES:
:CUSTOM_ID: section:quarteEtSixteCadentielle
:END:

La *quarte et sixte cadentielle* enchaîne deux accords faisant
fonction de dominante : un [[file:musica-03-clavier.org::*Accord broderie][accord broderie]] du degré 1 au second
renversement et un accord du degré 5. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | sol | sol |
| A | : | mi  | ré  |
| T | : | do  | si  |
| B | : | sol | sol |

Cet enchaînement est parfois nommé *quarte et sixte de cadence*. On
peut le faire suivre de n’importe quelle cadence.
