
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 04 : Concert
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Introduction

#+ATTR_HTML: :class lettrine
La polyphonie médiévale a fait ses premiers pas en utilisant un
processus d’accompagnement simple, l’ *organum strict* : une voix
parallèle, appelée *voix organale*, était alors ajoutée à une mélodie
préexistante de référence, la *voix principale*. Au fil du temps, la
voix organale est devenue de plus en plus ornée et indépendante. On
tournait alors autour du parallélisme strict, ne revenant à
l’intervalle harmonique original (unisson, octave ou quinte) que lors
des convergences de fin de phrase. C’était l’époque du *déchant* et de
l’ *organum fleuri*. Plus tard, d’autres voix ont été ajoutées,
donnant ainsi naissance au *motet*. Les lignes mélodiques ont pris de
plus en plus d’indépendance, la cohérence de l’ensemble étant assurée
par les lois du contrepoint, ancêtre de l’harmonie, ainsi que par
l’échange de motifs mélodiques via des procédés d’imitation et de
variation. Le *ricercar* et la *fugue* ont abondamment utilisé ce type
de constructions. L’art de la polyphonie aboutit alors à des
merveilles : imaginez une pièce de théâtre où chaque voix musicale
représente un personnage ; tantôt en concorde, tantôt en discorde,
toute la troupe bouillonne de thèmes, d’idées qui se baladent de main
en main, tissant ainsi la trame de l’histoire. Lorsque les Muses
apparaîssent au centre de cette table ronde, une magie collective
émerge des voix, dans toute la splendeur de sa virtuosité collective.

Fidèle à cette riche tradition, ce chapitre introduit les concepts qui
vont nous permettre d’explorer la dualité, ce fragile mais féerique
équilibre entre les dimensions mélodiques et harmoniques d’une
polyphonie.

/Remarques/ :

  - la voix principale était aussi appelée *vox principalis*,
    *cantus*, *cantus firmus*, ou encore *plain-chant*

  - la voix organale était aussi appelée *vox organalis*

  - le terme de motet viendrait de *motetus*, le petit mot, en
    référence au texte ajouté sur la ou les voix supplémentaires


* Dualité

#+TOC: headlines 1 local


** Grille

On peut représenter une polyphonie comme une superposition de
mélodies, mais également comme une succession d’accords, chacun
d’entre-eux régnant un certain temps sur le déroulement musical avant
de laisser la place à son successeur. Le tableau suivant illustre
cette dualité dans le cas d’un septuor :

#+ATTR_HTML: :class plat
| S | : | (accord-1, note-1) | (accord-2, note-1) | (accord-3, note-1) | =...= |
| M | : | (accord-1, note-2) | (accord-2, note-2) | (accord-3, note-2) | =...= |
| A | : | (accord-1, note-3) | (accord-2, note-3) | (accord-3, note-3) | =...= |
| C | : | (accord-1, note-4) | (accord-2, note-4) | (accord-3, note-4) | =...= |
| T | : | (accord-1, note-5) | (accord-2, note-5) | (accord-3, note-5) | =...= |
| Y | : | (accord-1, note-6) | (accord-2, note-6) | (accord-3, note-6) | =...= |
| B | : | (accord-1, note-7) | (accord-2, note-7) | (accord-3, note-7) | =...= |

Cette représentation schématique a le mérite de n’intégrer que les
notes essentielles de la polyphonie, ce qui permet de visualiser du
premier coup d’oeil les évolutions des voix lors des changements
d’accords. Nous appelons *grille polyphonique*, ou plus simplement
*grille* une telle représentation schématique de la polyphonie.


** Notes

Les notes d’une polyphonie peuvent se scinder en deux catégories :

  - les *notes essentielles* sont les notes qui appartiennent à la
    grille polyphonique, et donc à un des accords qui la constituent

  - les *notes étrangères* sont les notes qui n’appartiennent pas à la
    grille polyphonique, et donc à aucun des accords qui la
    constituent

/Remarque/ : on utilise également les expressions *note réelle* et
*note constitutive* comme synonymes de note essentielle.


** Accords

On peut classer grossièrement les accords en deux catégories, suivant
leur importance :

  - Les accords *stratégiques* constituent la clef de voûte du
    discours musical

  - Les accords *de passage* ont pour fonction de permettre une
    transition fluide entre deux autres accords


** Enchaînement

On appelle *enchaînement* une suite formée de deux ou de plusieurs
accords consécutifs. Deux accords consécutifs sont dit *enchaînés*.


*** Changement d’harmonie

Une *harmonie* peut aussi désigner le règne d’un accord. On parle donc
de *changement d’harmonie* pour signaler un changement d’accord.


** Rythme harmonique

Le rythme auquel les accords se succèdent est appelé *rythme
harmonique*. Le rythme harmonique peut être régulier ou variable.

Chaque accord règne un certain temps sur la musique avant de laisser
la place à son successeur. Ce règne peut durer pendant :

  - une carrure (entière, 1/2, 1/4, =...=)

  - une oscillation

  - une pulsation

  - une mesure

  - un temps

  - =...=


** Rencontres

La perception du cadre harmonique est renforcée par des rencontres
entre les notes essentielles les plus importantes de chaque accord.
Ces notes sont alors jouées simultanément sur les différentes voix de
la polyphonie. Les rencontres peuvent se produire à un rythme régulier
ou variable. En fait, elles sont liées au rythme harmonique, l’idéal
étant de disposer au moins une rencontre par accord. Les cas les plus
courants sont :


  - une rencontre au début de chaque temps

  - une rencontre au début de chaque mesure

  - une rencontre au début de chaque pulsation

  - une rencontre au début de chaque oscillation

  - =...=


* Mouvements harmoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements harmoniques* analysent les modifications de
disposition des notes essentielles au cours du règne d’un même accord.


** Échange

L’ *échange* consiste à choisir deux notes essentielles et à
intervertir leurs voix.

Exemple d’échange :

#+ATTR_HTML: :class plat
| S | : | mi | do |
| B | : | do | mi |

L’échange peut utiliser un accord de passage intermédiaire afin
d’opérer par mouvements conjoints. Exemple :

#+ATTR_HTML: :class plat
| S | : | mi | ré | do |
| B | : | do | ré | mi |


** Changement

Le *changement* consiste à modifier une des voix pour jouer une autre
note de l’accord.

Exemple de changement, ici sur le soprano :

#+ATTR_HTML: :class plat
| S | : | mi | sol |
| B | : | do | do  |


* Mouvements polyphoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements polyphoniques* comparent les évolutions de deux voix
quelconques de la grille polyphonique lors d’un changement d’accord,
ce qui les place au croisement de l’harmonie et de la mélodie.


** Mouvement parallèle

Il se produit un mouvement *parallèle* lorsque les deux voix évoluent
dans la même direction en utilisant le même intervalle mélodique.

/Remarque/ : dans le cadre des mouvements polyphoniques, on ne fait
pas de distinction entre les intervalles majeurs et mineurs. Par
exemple, si une voix monte d’une seconde majeure pendant que l’autre
monte d’une seconde mineure, le mouvement sera considéré comme
parallèle.


*** Ascendant

Un mouvement *parallèle ascendant* est un mouvement parallèle où les
deux voix évoluent vers l’aigu.

Exemple de mouvement parallèle ascendant :

#+ATTR_HTML: :class plat
| S | : | ré | mi | (monte) |
| B | : | la | si | (monte) |


*** Descendant

Un mouvement *parallèle descendant* est un mouvement parallèle où les
deux voix évoluent vers le grave.

Exemple de mouvement parallèle descendant :

#+ATTR_HTML: :class plat
| S | : | ré | do  | (descend) |
| B | : | la | sol | (descend) |


*** Continuité

Un mouvement *parallèle conjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement conjoint.

Un mouvement *parallèle disjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement disjoint.


*** Mélodies parallèles

Le mouvement parallèle se rencontre entre-autres lorsque deux mélodies
évoluent parallèlement. Par analogie avec les premières formes de la
polyphonie, on parle alors :


  - d’ *organum* lorsque l’intervalle qui les sépare est une octave,
    une quinte ou une quarte


  - de *gymel*, ou de *faux-bourdon*, lorsque l’intervalle qui les
    sépare est une tierce ou une sixte


** Mouvement oblique

Il se produit un mouvement *oblique* lorsqu’une des deux voix reste
constante pendant que l’autre varie.

Le mouvement oblique se produit généralement lorsqu’une note commune à
deux accords consécutifs est disposée sur la même voix.


*** Ascendant

Un mouvement *oblique ascendant* est un mouvement oblique où la voix
mobile évolue vers l’aigu.

Exemple de mouvement oblique ascendant :


#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte)    |
| B | : | do | do  | (constant) |


*** Descendant

Un mouvement *oblique descendant* est un mouvement oblique où la voix
mobile évolue vers le grave.

Exemple de mouvement oblique descendant :

#+ATTR_HTML: :class plat
| S | : | fa | ré | (descend)  |
| B | : | do | do | (constant) |


*** Continuité

Un mouvement *oblique conjoint* est un mouvement oblique où la voix
mobile évolue par mouvement conjoint.

Un mouvement *oblique disjoint* est un mouvement oblique où la voix
mobile évolue par mouvement disjoint.


** Mouvement contraire

Il se produit un mouvement *contraire* lorsque les deux voix évoluent
dans des directions opposées : l’une monte, l’autre descend. C’est un
mouvement naturellement très équilibré.


*** Extérieur

Un mouvement *extérieur* est un mouvement *contraire* où la voix
supérieure monte, tandis que la voix inférieure descend.

Pour s’en souvenir, se rappeler que les voix d’un mouvement extérieur
se dirigent vers l’extérieur.

Exemple de mouvement extérieur :

#+ATTR_HTML: :class plat
| S | : | si  | do | (monte)   |
| B | : | sol | fa | (descend) |


*** Intérieur

Un mouvement *intérieur* est un mouvement *contraire* où la voix
supérieure descend, tandis que la voix inférieure monte.

Pour s’en souvenir, se rappeler que les voix d’un mouvement intérieur
se dirigent vers l’intérieur.

Exemple de mouvement intérieur :

#+ATTR_HTML: :class plat
| S | : | si | la | (descend) |
| B | : | mi | fa | (monte)   |


*** Continuité

Un mouvement *contraire conjoint* est un mouvement contraire où les
deux voix évoluent par mouvement conjoint.

Un mouvement *contraire disjoint* est un mouvement contraire où au
moins une des voix évolue par mouvement disjoint.


** Mouvement direct

Il se produit un mouvement *direct* lorsque les deux voix évoluent
dans la même direction, mais au moyen d’intervalles différents.


*** Ascendant

Un mouvement *direct ascendant* est un mouvement direct où les deux
voix évoluent vers l’aigu.

Exemple de mouvement direct ascendant :

#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte) |
| B | : | mi | si  | (monte) |


*** Descendant

Un mouvement *direct descendant* est un mouvement direct où les deux
voix évoluent vers le grave.

Exemple de mouvement direct descendant :

#+ATTR_HTML: :class plat
| S | : | fa  | mi | (descend) |
| B | : | sol | do | (descend) |


*** Continuité

Un *mouvement direct conjoint* est un mouvement direct où l’une des
voix évolue par mouvement conjoint tandis que l’autre évolue par
mouvement disjoint.

Un *mouvement direct disjoint* est un mouvement direct où les deux
voix évoluent par mouvement disjoint.


*** Bonne pratique

Le mouvement direct est le plus élégant lorsqu’une des voix évolue par
mouvement conjoint tandis que l’autre effectue un mouvement disjoint
(idéalement quarte ou quinte), l’idée étant que le contraste entre les
variations des deux voix le fasse ressembler à un mouvement oblique.


** Mouvement consécutif
:PROPERTIES:
:CUSTOM_ID: section:mouvementConsecutif
:END:


Il se produit un mouvement *consécutif* lorsque les deux voix
reproduisent un même intervalle harmonique à l’octave près, que ce
soit par mouvement parallèle, contraire ou direct.

Exemple de mouvement consécutif :

#+ATTR_HTML: :class plat
| S | : | mi | sol | (monte d’une 3ce ou descend d’une 6te) |
| B | : | do | mi  | (monte d’une 3ce ou descend d’une 6te) |


** Disposition des voix

Cette section analyse certaines configurations liées à la disposition
relative des voix.


*** Croisement

Un *croisement* se produit lorsqu’une note essentielle d’une voix
normalement plus grave croise à la hausse une note essentielle d’une
voix plus aiguë.

Afin de bien distinguer les lignes mélodiques constitutives d’une
polyphonie, le croisement est généralement à éviter. Certaines
circonstances, comme l’utilisation de timbres différents, permettent
toutefois d’éviter la confusion. Il peut arriver aussi qu’une
confusion fugitive soit souhaitée.


*** Chevauchement

Un *chevauchement* se produit lorsqu’une note essentielle d’une voix
plus grave croise à la hausse la note essentielle /précédente/ d’une
voix plus aiguë (ou vice versa).

Afin de bien distinguer les lignes mélodiques constitutives d’une
polyphonie, le chevauchement est généralement à éviter. Certaines
circonstances, comme l’utilisation de timbres différents, permettent
toutefois d’éviter la confusion. Il peut arriver aussi qu’une
confusion fugitive soit souhaitée.


*** Fausse relation


**** Chromatique

Une *fausse relation chromatique* se produit lorsque les trois notes
d’un mouvement chromatique ne sont pas toutes disposées sur la même
voix.


**** Triton

Une *fausse relation de triton* se produit lorsque deux notes :

  - appartenant à deux accords consécutifs

  - situées sur deux voix différentes

forment un intervalle de triton.


** Principes


*** Économie de mouvement

Le principe d’ *économie de mouvement* dit que les notes essentielles
doivent évoluer majoritairement par mouvement conjoint au cours d’un
changement d’accord, ce qui permet :

  - De distinguer plus aisément les différentes voix de la polyphonie

  - De distinguer les intervalles internes des accords (le plus
    souvent des tierces) des intervalles permettant l’enchaînement

Ce principe n’exige pas que toutes les variations doivent être
faibles : si une partie non négligeable des notes de l’ancien accord
progresse par mouvement conjoint, on peut largement se permettre des
quintes, des quartes, voire même des tierces sur les autres notes.

Ceci est également valable à l’échelle des mélodies de la grille
polyphonique, mélodies générées par la succession des accords :
chacune d’entre-elle doit évoluer majoritairement par mouvement
conjoint, ceci afin de permettre à l’oreille de discerner les
différentes voix qui composent la polyphonie. Cette continuité
majoritaire permet également d’accentuer aisément les fins de phrases
en utilisant le contraste qu’offrent alors les sauts discontinus des
mouvements disjoints.


*** Lignes mélodiques extrêmes

Les mouvements formés par les lignes mélodiques extrêmes (basse et
soprano) doivent être particulièrement soignés, car ce sont les voix
les plus évidentes pour l’oreille.


*** Mouvements, accords et dispositions

De nombreux accords et dispositions différentes peuvent assurer une
même fonction tonale, ce qui permet de les choisir au mieux afin
d’obtenir des mouvements élégants. L’harmonie est donc un cadre très
souple dans lequel viennent s’écouler les mélodies.


* Ornements

#+TOC: headlines 1 local


** Introduction

La modélisation d’une polyphonie sous la forme d’une suite d’accords
est d’une grande clarté et permet de cerner l’essentiel. Mais
l’essentiel n’est pas tout, et si la sobriété est très utile dans les
premières phases de la composition, on est amenés par la suite à
insérer des *ornements* afin de donner de la souplesse aux lignes
mélodiques ou d’enrichir la dynamique harmonique.

On appelle *note ornementale* une note constitutive d’un ornement.


** Ornements harmoniques


Ce chapitre analyse les ornements dont la fonction est essentiellement harmonique.


*** Arpège

Un *arpège* consiste à jouer consécutivement une partie ou la totalité
des notes de l’accord en cours. Chaque note peut être répétée, à
l’unisson où à l’octave près.

Les arpèges d’accords à base de tierces sont très utilisés dans la
construction de voix accompagnatrices d’une mélodie principale.

Les arpèges d’accords à base de quintes s’apparentent aux modes
pentaphoniques ou tétraphoniques. Ils sont donc très utilisés dans la
construction de mélodies blues, chinoises ou japonaises par exemple.


**** Accord brisé

Un *accord brisé* est une généralisation de l’arpège, où plusieurs
notes de l’accord peuvent être jouées simultanément. Les deux termes
sont parfois considérés comme synonymes.


*** Gamme

Jouer toutes les notes de la gamme courante (ton, mode) permet de
l’imposer comme référence. Les gammes jouées peuvent être ascendantes,
descendantes ou mixtes.


*** Pédale

Une *pédale* est une note qui reste obstinément constante,
indépendamment des accords qui se succèdent sur les autres voix.

Exemple de pédale, ici à la basse :

#+ATTR_HTML: :class plat
| S | : | la   | si   | mi   |
| A | : | fa   | sol  | do   |
| B | : | /do/ | /do/ | /do/ |

Plus généralement, une pédale est un objet harmonique qui reste
constant dans un environnement harmonique variable. Un accord maintenu
constant sur une partie des voix pendant que d’autres accords se
succèdent sur les autres voix est donc également une pédale.

Un exemple d’accord-pédale est celui où un même accord est arpégé
inlassablement sur une des voix.


*** Retard

Un *retard* est une note intégrée à un accord et qui se poursuit
au-delà du changement d’accord, empiétant sur le début du règne de
l’accord suivant.

Exemple de retard, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | do  |
| A | : | la   | sol  | sol |
| B | : | fa   | mi   | mi  |


*** Anticipation

Une *anticipation* est une note appartenant à un accord qui est
entamée avant la fin du règne de l’accord précédent.

Exemple d’anticipation, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


*** Appogiature

Une *appogiature* est une note arbitraire jouée au début du règne d’un
accord.


** Ornements mélodiques


Ce chapitre analyse les ornements dont la fonction est essentiellement
mélodique.


*** Note de passage

Une *note de passage* est une note ornementale permettant de relier
par mouvement conjoint deux notes appartenant à un même accord où à
deux accords différents. Exemple :

#+BEGIN_CENTER
do /si la/ sol
#+END_CENTER


*** Broderie

La *broderie* est une note conjointe qui quitte une note de l’accord
avant de la retrouver. Exemple :

#+BEGIN_CENTER
do /ré/ do
#+END_CENTER


**** Double

La *double broderie* combine une broderie vers le haut et une broderie
vers le bas. Exemple :

#+BEGIN_CENTER
do /ré si/ do
#+END_CENTER


*** Échappée

L’ *échappée* quitte une note conjointe de l’accord et est suivie par
une note disjointe du même accord ou de l’accord suivant. Exemple :

#+BEGIN_CENTER
sol /la/ ré
#+END_CENTER


** Ornements répétitifs


*** Trémolo

Un *trémolo* consiste à alterner deux notes. Exemple :

#+BEGIN_CENTER
do sol do sol do sol do sol
#+END_CENTER


*** Trille

Un *trille* consiste à alterner deux notes séparées par une seconde
majeure ou mineure. Exemple :

#+BEGIN_CENTER
do ré do ré do ré do ré
#+END_CENTER


*** Roulement

Un *roulement* consiste à répéter une même note. Exemple :

#+BEGIN_CENTER
do do do do do do do do
#+END_CENTER


* Accentuation

#+TOC: headlines 1 local


** Mélodie

Une mélodie est généralement accentuée par :

  - des paliers : notes de longue durée

  - des extrêmes : pics ou creux locaux

  - des virages : changements de direction, de pente

  - des sauts : mouvements disjoints dans une mélodie majoritairement
    conjointe


** Notes essentielles

Les accents mélodiques sont généralement disposés sur des notes
essentielles.


*** Discontinuités

Ceci est particulièrement vrai pour les discontinuités. Il est donc
rare d’observer un mouvement disjoint ne faisant intervenir aucune
note de l’accord.


** Indépendance

Les accents mélodiques des différentes voix de la polyphonie sont
indépendants. La plupart du temps, on s’arrange pour que ces accents
apparaissent à des instants différents sur chacune des voix, ceci afin
de les mettre tour à tour en évidence.

Il arrive toutefois que les accents mélodiques soient synchronisés
afin de donner à l’ensemble un effet de convergence et d’apothéose
très convaincant.


* Dynamique des ornements

#+TOC: headlines 1 local


** Pédale

Lorsqu’une *pédale* est présente, elle est en général alternativement
dissonante et consonante par rapport aux accords qui se succèdent sur
les autres voix.

Une pédale est souvent préparée en s’intégrant à un premier accord et
en perdurant après sa disparition. Le dernier accord qui se superpose
à une pédale lui est en général également consonant.

Autrement dit, une pédale est généralement préparée et résolue par
intégration.


** Retard

Un *retard* est une note constitutive d’un accord stable qui se
prolonge sur l’accord suivant où elle devient dissonante. Elle
redevient consonante en s’intégrant à un nouvel accord stable, le plus
souvent par mouvement conjoint. Par définition, un retard est donc
préparé par intégration.

Par exemple, dans l’enchaînement suivant, le /ré/ au soprano est un
retard qui se résout en descendant vers le /do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /do/ |
| A | : | la   | sol  | sol  |
| T | : | fa   | mi   | mi   |
| B | : | ré   | do   | do   |

Autre exemple où le /ré/ se résout en montant vers le /mi/

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | /mi/ |
| A | : | la   | la   | la   |
| B | : | fa   | do   | do   |


** Anticipation

Une *anticipation* est une note dissonante qui se résout par
intégration dans l’accord suivant. Par exemple, dans l’enchaînement
suivant, le /mi/ au soprano est une ancicipation :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


** Appogiature

Une *appogiature* est une note dissonante placée au début du règne d’un accord
harmonique. Elle se résout généralement en s’y intégrant par mouvement conjoint.

Contrairement au retard qui est préparé par intégration, l’appogiature
est généralement préparée par mouvement conjoint, mouvement polyphonique,
ou purement et simplement attaquée.


* Disposition

#+TOC: headlines 1 local


** Introduction

Ce chapitre donne une liste des dispositions musicales les plus
courantes. Ces arrangements sont supposées être mis en oeuvre par
défaut, dans un contexte dépourvu de toute particularité qui nous
permettrait d’orienter la musique vers une autre configuration. Il ne
s’agit donc pas de principes rigides, et il n’est pas rare qu’un
aspect musical élégant justifie largement l’emploi d’une disposition
alternative.


** Mélodie


*** Octave

L’octave mélodique est normalement :

  - précédée par un intervalle mélodique allant dans le sens opposé

  - suivie par un intervalle mélodique allant dans le sens opposé


*** En trois notes


**** Septièmes

Les septièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  - sixte mélodique puis seconde mélodique dans le même sens
  - octave mélodique puis seconde mélodique dans le sens opposé


**** Neuvièmes

Les neuvièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  - octave mélodique puis seconde mélodique dans le même sens

  - dixième mélodique puis seconde mélodique dans le sens opposé


**** Quarte augmentée

La quarte augmentée parcourue en trois notes est suivie de préférence
d’une seconde mineure de même direction, afin de former une quinte
juste en quatre notes.


** Voix


*** Écarts

Une disposition élégante consiste à suivre approximativement les
harmoniques naturelles, où les notes sont plus éloignées dans les
graves et plus proches dans les aiguë.

En appliquant ce principe à un quatuor, on obtient, par ordre
décroissant des écarts :

#+BEGIN_CENTER
basse — ténor   >   ténor — alto   >   alto — soprano
#+END_CENTER

Les dispositions les plus courantes sont les suivantes :

  - Intervalles à peu près égaux entre chaque paire de voix adjacentes

  - La basse éloignée, les autres voix resserrées

Dans le cas d’un quatuor, on utilise parfois la disposition suivante :

  - Octave entre alto et ténor

  - Tierce (ou moins) entre ténor et basse


**** Écart maximal

On convient généralement d’éviter un écart de plus d’une octave entre
voix adjacentes. Une exception à ce principe, qui découle des
harmoniques naturelles : l’intervalle entre la basse et la voix qui
lui est immédiatement supérieure (le ténor dans un quatuor) peut
dépasser une octave.


** Accords


*** Fondamentale

Si la fondamentale d’un accord remplit une fonction tonale, il s’agit
d’une note très importante à mettre en évidence. On peut donc la
doubler, la placer à la basse, ou, si l’accord est renversé, la
disposer au soprano.

Bien entendu, si la fondamentale de l’accord est entendue en tant que
pédale, il n’est pas nécessaire de l’accentuer davantage.

Les accords de sixte, premiers renversements des accords parfaits,
sont fréquemment disposés avec la fondamentale au soprano.


*** Cas particuliers


**** Neuvième de dominante

On veille en général à ce que la note de 9e de l’accord de neuvième de
dominante soit plus aiguë que la fondamentale, si celle-ci est
présente. Une 9e non préparée se place également au-dessus de la
sensible.


*** Intervalles entre notes essentielles

Un intervalle direct est un intervalle séparant deux notes
consécutives d’un accord. Exemple, /mi — sol/ dans :

#+BEGIN_CENTER
do mi sol si
#+END_CENTER

Un accord constitué d’intervalles directs identiques donne une
impression de confusion : il manque d’élan.

Un accord contenant au moins deux intervalles directs distincts
produit une tension, un élan musical. Attention toutefois : disposer
trop d’intervalles différents produit une direction floue et mène
également à la confusion.


** Mouvements


*** Oblique

On évite l’arrivée par mouvement oblique conjoint sur l’unisson.

/Pourquoi/ ? Vraisemblablement pour éviter l’intervalle harmonique de
seconde que ce mouvement implique.


*** Contraire

Si la basse évolue par mouvement conjoint et que les accords enchaînés
ne possèdent pas de note commune, on fait généralement évoluer les
autres voix par mouvement contraire. On conserve ainsi un certain
équilibre entre les voix.


*** Direct

L’arrivée sur unisson par mouvement direct est à éviter.

Lorsqu’un mouvement direct débouche sur une octave ou une quinte :

  - on veille généralement à ce que l’une des voix évolue par
    mouvement conjoint

  - si le mouvement direct à lieu entre les voix extrêmes, la voix
    conjointe sera de préférence le soprano.


*** Consécutif

Les unissons, octaves et quintes consécutives sont généralement
déconseillés dans les traités actuels d’harmonie, car la répétition de
ces intervalles est réputée « sonner creux ». Toutefois, ce conseil
est à relativiser :

  - certaines musiques traditionnelles utilisent a profusion les
    quintes et octaves consécutives

  - lorsque deux mélodies sont parallèles, l’une étant transposée
    suivant l’un de ces intervalles, on assiste naturellement à la
    formation d’unissons, d’octaves ou de quintes parallèles, et donc
    consécutives. L’organum strict, une des premières formes de
    polyphonie, a utilisé abondamment ce principe pendant plusieurs
    siècles.

La mise à l’écart de ces intervalles relève donc plutôt d’un effet de
mode que d’une réelle considération harmonique.

En pratique, si vous souhaiter utiliser des octaves ou quintes
consécutifs, vous pouvez :

  - les placer ouvertement aux voix les plus importantes

  - les placer dans les voix internes, plus discrètes, de la
    polyphonie


** Notes communes

Dans le cas où une note essentielle est commune à deux accords
consécutifs, on la place généralement sur une même voix afin de
respecter la philosophie de l’économie de mouvement. On génère alors
des mouvements obliques avec les autres voix.

Exemple de note commune disposée sur une même voix :

#+ATTR_HTML: :class plat
| S | : | la   | mi   |
| A | : | /do/ | /do/ |
| B | : | fa   | sol  |


*** Accords parfaits

Considérons l’enchaînement d’accords parfaits.

Lorsque la fondamentale des accords enchaînés monte ou descend d’une
/quinte/, les accords possèdent exactement /une/ note commune.
Celle-ci est alors généralement disposée sur une même voix.

Lorsque la fondamentale des accords enchaînés monte ou descend d’une
/tierce/, les accords possèdent exactement /deux/ notes communes. On
peut alors :

  - disposer chacune de ces notes communes sur une même voix

  - disposer une seule de ces notes communes sur une même voix

  - ne disposer aucune de ces notes communes sur une même voix

Lorsque la fondamentale des accords enchaînés monte ou descend d’une
/seconde/, les accords ne possèdent /aucune/ note commune.


** Suppressions

Les accords renversés ont généralement un caractère moins affirmé que
leurs homologues à l’état fondamental. Cette remarque est
particulièrement vraie pour les triades. Afin de ne pas les rendre
encore plus floues, on évite autant que possible de supprimer une note
d’une triade renversée.

Par contre, les accords renversés de quatre notes ou plus, et en
particulier la 7e et la 9e de dominante, peuvent s’employer sans
fondamentale ou sans quinte.

Il est parfois souhaitable ou nécessaire de supprimer une des notes
d’un accord donné. L’effet obtenu dépendra du choix de cette note.


*** Tétrades

Plaçons-nous par exemple en tonique /do/ afin d’illustrer le propos,
et examinons les accords de quatre notes. Si nous supprimons la
fondamentale d’un accord du degré 1 ou 5, on obtient un accord qui
peut être analysé comme étant du degré 3 ou 7 :

#+ATTR_HTML: :class plat
| do mi sol si | ⟼ | mi sol si |
| sol si ré fa | ⟼ | si ré fa  |

Nous obtenons alors l’effet particulier d’une fonction tonale
implicite 1 remplie par un degré 3, ou d’une fonction tonale implicite
5 remplie par un degré 7. Plus généralement, le degré est disposé à la
tierce supérieure par rapport à la fonction tonale implicite. Voyons à
présent ce qui se passe si on supprime la tierce :

#+ATTR_HTML: :class plat
| do mi sol si | ⟼ | do sol si |
| sol si ré fa | ⟼ | sol ré fa |

On supprime alors soit la médiante, qui détermine si le mode est
majeur ou mineur (/mi/ ou /mi^b/ dans notre exemple), soit la sensible
qui possède une importante fonction de résolution sur la tonique (le
/si/ est attiré par le /do/ dans notre exemple). Même en mineur, le
degré 7 est fréquemment haussé d’un demi-ton afin de le transformer en
sensible.

Il est donc tout à fait possible de supprimer la tierce afin de
produire volontairement un accord plus dépouillé, mais il faut savoir
que cette suppression va rendre le mode ambigu sur l’accord de tonique
et diminuer la tension de l’accord de dominante. Voyons à présent ce
qui se passe lorsqu’on supprime la quinte :

#+ATTR_HTML: :class plat
| do mi sol si | ⟼ | do mi si  |
| sol si ré fa | ⟼ | sol si fa |

La médiante et la sensible sont alors conservées. Enfin, lorsqu’on
supprime la septième, on se retrouve tout simplement avec un accord de
trois notes :

#+ATTR_HTML: :class plat
| do mi sol si | ⟼ | do mi sol |
| sol si ré fa | ⟼ | sol si ré |


*** Triades

Le constat est similaire aux accords de quatre notes. Exemples avec
suppression de la quinte :

#+ATTR_HTML: :class plat
| do mi sol    | ⟼ | do mi    |
| do mi sol do | ⟼ | do mi do |

Exemples avec suppression de la tierce :

#+ATTR_HTML: :class plat
| do mi sol    | ⟼ | do sol    |
| do mi sol do | ⟼ | do sol do |

Exemples avec suppression d’une doublure :

#+ATTR_HTML: :class plat
| do mi sol do | ⟼ | do mi sol |


**** À base de quintes

Pour les accords de double quinte et similaires, l’intervalle de
seconde entre la quarte et la quinte, ou entre la fondamentale et la
seconde contient la tension de l’accord. On peut la supprimer :

#+ATTR_HTML: :class plat
| do fa sol | ⟼ | do sol |
| do fa sol | ⟼ | do fa  |
| do ré sol | ⟼ | do sol |
| do ré sol | ⟼ | ré sol |

mais on supprime alors du même coup la possibilité de résolution vers
un accord parfait. Dans le cas où cette résolution est souhaitée, on
supprimera plutôt la quinte :

#+ATTR_HTML: :class plat
| do fa sol | ⟼ | do fa |
| do ré sol | ⟼ | do ré |

ou la fondamentale :

#+ATTR_HTML: :class plat
| do fa sol | ⟼ | fa sol |
| do ré sol | ⟼ | ré sol |


*** Pentades

En ce qui concerne les accords de cinq notes, les remarques sont
similaires aux accords de quatre notes : enlever la fondamentale rend
la fonction tonale implicite, supprimer la tierce rend le mode ambigu
et réduit la tension. Par contre, supprimer la quinte conserve les
propriétés de l’accord. Supprimer la septième :

#+ATTR_HTML: :class plat
| sol si ré fa la | ⟼ | sol si ré la |

diminue quelque peu la tension de l’accord de dominante, car la
sous-dominante est naturellement attirée par la médiante de résolution
(le /fa/ est attiré par le /mi/ dans notre exemple). Supprimer la
neuvième revient à produire un accord de quatre notes :

#+ATTR_HTML: :class plat
| sol si ré fa la | ⟼ | sol si ré fa |


*** Conclusion

De façon générale, la richesse harmonique (mode et tension) d’un
accord est tributaire au moins partiellement de la tierce.

Lorsqu’on souhaite conserver cette richesse, on préfère choisir la
quinte ou la fondamentale comme candidat à la suppression.

Si on souhaite par contre obtenir un effet de simplicité harmonique,
on supprime la tierce, mettant ainsi en évidence l’intervalle de
quinte. L’intervalle d’octave est également mis en évidence si une
doublure est présente.


** Dissonances

Une dissonance se trouve ordinairement sur la même voix que sa
résolution. On peut toutefois procéder à un échange de voix simultanée
à une résolution ordinaire, produisant ainsi un effet inattendu.


*** Résolution irrégulière

Lorsqu’il n’est pas possible de procéder à un mouvement obligé, il est
préférable de quitter la dissonance par mouvement conjoint.


*** Doublure

Supposons qu’une dissonance soit doublée. La double résolution
attendue provoque en ce cas des octaves consécutives, phénomène que
l’on souhaite généralement éviter. Exemple :

#+ATTR_HTML: :class plat
| S | : | si | do |
| B | : | si | do |

On évite donc généralement de doubler une note dissonante. Si l’on
souhaite malgré tout la doubler, ou qu’il n’est pas possible de faire
autrement, la dissonance et sa doublure sont de préférence :

  - amenées par mouvement contraire ou oblique

  - quittées par mouvement contraire


**** Préparation

Suivant ce même principe, si une éventuelle note destinée à préparer
une dissonance est doublée, on quitte cette note et sa doublure par
mouvement contraire ou oblique.


**** Résolution

Suivant ce même principe, si la note de résolution est doublée, on
amène cette note et sa doublure par mouvement contraire.

On note toutefois une certaine asymétrie dans ces conseils : mouvement
contraire ou oblique entre préparation et tension, mouvement contraire
uniquement entre tension et résolution.


** Ornements


*** Retard

Afin de ne pas gâcher l’effet de surprise, on évite habituellement de
faire entendre le retard en même temps que sa note de résolution.

On peut cependant l’envisager si :

  - la note de résolution est sous le retard
  - la note de résolution est placée sur une voix interne
  - l’intervalle harmonique entre retard et résolution est au moins égal à la septième


*** Notes de passage, broderies

On veille généralement à éviter l’intervalle harmonique de seconde
mineure (à l’octave près) entre une note de passage et une autre voix.
Il en va de même pour les broderies.


** Accords de passage


*** Échange fluide

Lorsqu’on souhaite échanger deux notes d’un accord tout en opérant par
mouvements conjoints, il est nécessaire d’intercaler un accord de
passage entre la disposition initiale et la disposition finale. Dans
cet exemple, on échange le soprano et la basse :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | do   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Autre exemple, avec un accord de 7e comme point de départ :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | si   | si   | si   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Enfin, l’accord final peut révéler une version 7e de l’accord de
départ :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | la   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |


*** Suites d’accords de passage

Il est possible d’enchaîner plusieurs accords ornementaux. On assiste
alors généralement à la formation de portions de gammes diatoniques ou
chromatiques sur une des voix.


* Stratification

#+TOC: headlines 1 local


** Gamme


*** Musique tonale

Lorsqu’une polyphonie est basée à chaque instant sur une unique gamme
de référence, on parle de *musique tonale*. Il existe donc à tout
moment un unique ton et un unique mode de référence.

La gamme de référence peut par contre varier au cours de la pièce, on
parle alors de *modulation*.

La musique tonale est de loin le style musical le plus répandu.

/Remarque/ : j’englobe dans ce style la musique pré-tonale qui répond
au même critère, à savoir une seule gamme de référence à un instant
donné. La musique antique, médiévale, et de la renaissance sont donc
inclues, même si la formalisation de l’accord est plus récente.


*** Polytonalité

Lorsqu’une polyphonie est constituée à chaque instant d’une série de
groupes de voix où chaque groupe possède sa propre gamme de référence,
distincte de celles des autres groupes, on parle de musique
polytonale.

Chaque groupe possède donc à tout instant son propre ton et son propre
mode. Les groupes et les gammes sont bien entendu libres d’évoluer au
fil du temps.

Par exemple, dans un quatuor, le soprano et l’alto peuvent être en /do
majeur/ tandis que le ténor et la basse sont basées sur une tonique
/mi/ et un mode /oriental/. Plus tard, le soprano et le ténor peuvent
être en /la mineur/ tandis que l’alto et la basse peuvent être en /ré
dorien/.


** Polyharmonie

Une polyharmonie se produit lorsque chaque groupe de voix joue à un
instant donné un accord distinct de ceux des autres groupes.


** Polyrythmie


*** Introduction

La polyrythmie analyse la superposition de deux rythmes simultanés, et
en particulier les configurations qui ne surchargent pas l’oreille.


*** Rythmes identiques

Les deux rythmes sont identiques. Exemple :

#+ATTR_HTML: :class plat
| S | : | B N | N N N | Bp |
| B | : | B N | N N N | Bp |


*** Rythmes contrastés

Un rythme est lent, l’autre est rapide. Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | Bp |   |   |
| B | : | N  | N | N | N  | N | N |


*** Rythmes dialogués

Les voix alternent rythmes rapides et lents, afin de laisser à chacune
un « temps de parole ». Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | N  | N | N |
| B | : | N  | N | N | Bp |   |   |


*** Rythmes décalés

Les deux rythmes sont décalés. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | — | — | N | — | — | N |


*** Rythmes hybrides

Il s’agit de rythmes alternativement synchronisés et décalés.
Exemples :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | N | — | N | N | — | N |

Le même en version fluide :

#+ATTR_HTML: :class plat
| S | : | N | B |   | N | B |   |
| B | : | B |   | N | B |   | N |


*** Rythmes convergents

Ce sont des rythmes contrastés, décalés ou hybrides qui convergent
l’un vers l’autre. Cette situation est très fréquente à l’approche des
fins de phrase, où toutes les voix finissent par ralentir. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | — | N | B |   | N | Bp |
| B | : | N | N | — | N | B |   | Bp |


*** Rythmes fleuris

Il est bien évident que chaque mélodie peut changer de rythme à tout
instant, modifiant du même coup la structure rythmique de la
polyphonie. Lorsqu’une superposition de rythmes fait entendre
successivement différentes configurations polyrythmiques, on parle de
style fleuri.


*** Rythmes polymétriques

Jusqu’à présent, nous avons considéré que la structure rythmique est
identique sur toutes les voix de la polyphonie. Il est cependant
possible de superposer des pyramides rythmiques de structures
différentes. On parle alors de polymétrie ou de rythmes polymétriques.


**** Rythmes hémiolés

Les rythmes *hémiolés* sont constitués de deux rythmes en relation
d’hémiole. Ils constituent donc un cas particulier de polymétrie.

La structure des pulsations et oscillations se présente alors comme
suit :

#+ATTR_HTML: :class plat
| X | : | § | χ | ¶ | χ | ¶ | χ |
| Y | : | § | χ | χ | ¶ | χ | χ |


*** Rythmes agrégés

Un rythme agrégé résulte de la condensation en une seule voix des
différents rythmes d’une polyphonie : chaque nouvelle note entamée sur
une des voix est également entamée sur le rythme agrégé. Considérons
par exemple la superposition :

#+ATTR_HTML: :class plat
| S | : | Np | C  |
| B | : | C  | Np |

Pour obtenir le rythme agrégé, on décompose le temps en suivant la
plus petite valeur commune, ici la croche, et on note le début de
chaque note sur le tableau correspondant :

#+ATTR_HTML: :class plat
|         |   | C | C | C | C |
| S       | : | X |   |   | X |
| B       | : | X | X |   |   |
| Agrégré | : | X | X |   | X |

On voit qu’aucune note n’est entamée à la troisième croche.
Le rythme agrégé associé est donc :

#+BEGIN_CENTER
C C cs C
#+END_CENTER

ou, en version fluide :

#+BEGIN_CENTER
C N C
#+END_CENTER

Pour condenser les rythmes de cet exemple :

#+ATTR_HTML: :class plat
| S | : | N  | B  |    |
| B | : | Np | Cp | Cp |

nous  utilisons un tableau de double-croches :

#+ATTR_HTML: :class plat
|         |   | dC | dC | dC | dC | dC | dC | dC | dC | dC | dC | dC | dC |
| S       | : | X  |    |    |    | X  |    |    |    |    |    |    |    |
| B       | : | X  |    |    |    |    |    | X  |    |    | X  |    |    |
| Agrégré | : | X  |    |    |    | X  |    | X  |    |    | X  |    |    |

Nous obtenons donc une première note qui occupe quatre double-croches,
une deuxième qui en occupe deux, et deux dernières qui en occupent
chacune trois. Le rythme agrégé s’écrit :

#+BEGIN_CENTER
N C Cp Cp
#+END_CENTER


**** Binaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| Ν N + Np C         | N C C           |
| Np C + C Np        | C N C           |
| N C C + C N C      | C C C C         |
| N N + C N C        | C C C C         |
|                    |                 |

**** Ternaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| B N + N B          | Ν N N           |
| N B + B C C        | N N C C         |
| N C N C + N N N    | N C C C C       |


**** Hybrides

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| N N N + Np Np      | N C C N         |
| B N + Np Np        | Np C N          |
| B C C + Np Np      | Np C C C        |
| N B + Np Cp Cp     | N C Cp Cp       |


*** Syncopes


**** Parties extrêmes

On évite généralement la syncope simultanée au soprano et à la basse,
car ce procédé perturbe la structure rythmique d’une polyphonie.


**** Retard harmonique

Un procédé élégant consiste à utiliser une syncope pour produire
un retard harmonique.


**** Syncope d’harmonie

La syncope d’harmonie est un accord entamé sur temps faible, ou partie
faible de temps, et poursuivi sur temps fort, ou partie forte de
temps. Ce procédé déstabilise la structure rythmique d’une polyphonie,
et est donc déconseillé.


**** Contraste

Il arrive souvent qu’on mette en relief une syncope en introduisant un
contraste voix syncopée — voix sans syncope. Dans ce cas, la tension
découle naturellement du contraste.
