
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 07 : Concert
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Cadences tonales

#+TOC: headlines 1 local

** Évolution

Nous avons abordé les différentes catégories de cadences dans l’ordre
historique de leur apparition :

  1. les cadences d’intervalles
  2. les cadences modales : moyen-âge, renaissance
  3. l’évolution des cadences modales, de plus en plus complexes

Nous allons à présent examiner les cadences tonales, ou cadences
d’accords, apparues pendant la période baroque.

Explorer ces différents types de cadences nous a permis de bien
comprendre leurs mécanismes de formation, mais aussi de nous
familiariser avec leurs caractéres, depuis la simplicité et la clarté
des cadences d’intervalles jusqu’à l’horlogerie des cadences
d’accords, en passant par la finesse et la richesse harmonique des
cadences modales.

On ajoutera que toutes ces catégories de cadences sont construites sur
le socle de mouvements polyphoniques élégants, et en particulier du
mouvement contraire conjoint. Cette constatation nous ouvre la voie à
une compréhension profonde de ces enchaînements musicaux.

Enfin, si cette évolution historique aboutit aux cadences tonales, qui
sont les plus utilisées aujourd’hui, les cadences modales sont au
coeur même de leur construction, et sont donc plus que jamais utiles à
la compréhension et à la composition musicale.

** Ouverture & conclusion

Les cadences tonales sont divisées en deux catégories :

  - les cadences *conclusives*, qui ponctuent la fin d’une phrase musicale
    + elles se terminent par un accord parfait du degré 1 à l’état fondamental
  - les cadences *ouvertes*, qui relancent la musique

En régle générale, les cadences conclusives sont celles qui se
terminent par un accord de tonique à l’état fondamental. Les autres
cadences sont ouvertes.

** Nouveau thème

Une cadence peut servir à introduire un nouveau thème.

Ce nouveau thème peut permettre de relancer la musique, même dans le
cas d’une cadence conclusive.

** Tuilage harmonique

Le *tuilage harmonique* est une technique qui consiste à décaler
l’enchaînement des thèmes mélodiques par rapport à l’enchaînement des
accords, en particulier lors des cadences. Il a pour effet de
distraire l’oreille par la mélodie, et donc de faire passer les
enchaînements d’accords en sourdine.

Le tuilage harmonique est donc une technique de [[file:musica-04-clavier.org::#heading:camouflage][camouflage]].

* Cadence parfaite

#+TOC: headlines 1 local

** Introduction

La *cadence parfaite*, aussi appelée *cadence authente*, est la
cadence conclusive la plus répandue. Elle enchaîne un accord de
dominante du degré 5 avec un accord de tonique du degré 1. L’accord de
dominante peut être un accord parfait, une septième ou une neuvième.
L’accord de tonique est un accord parfait à l’état fondamental.
L’accord de dominante peut être renversé sans remettre en cause le
caractère conclusif.

** Évolution depuis les cadences modales

Plaçons nous en /do majeur/ et considérons la
[[file:musica-04-clavier.org::#heading:cadenceIonienneQuatreVoix][cadence ionienne à quatre voix]] formée par
l’ajout d’une voix constante et d’une voix disjointe  :

#+ATTR_HTML: :class plat
| S | : | si   | do   |
| A | : | sol  | sol  |
| T | : | /ré/ | /do/ |
| B | : | sol  | do   |

Le mouvement conjoint descendant /ré — do/ peut être remplacé par un
mouvement conjoint ascendant pour arriver une tierce au-dessus de la
basse finale :

#+ATTR_HTML: :class plat
| S | : | si   | do   |
| A | : | sol  | sol  |
| T | : | /ré/ | /mi/ |
| B | : | sol  | do   |

Nous avons ainsi construit une cadence parfaite.

** Mode majeur

#+TOC: headlines 1 local

*** Introduction

Nous classons les différentes variantes de la cadence parfaite suivant
le type de l’accord de dominante.

*** Accord parfait

Nous prenons comme exemple la gamme de /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | sol | sol |
| T | : | ré  | mi  |
| B | : | sol | do  |

**** Renversements

Voici un exemple en /do majeur/ avec un accord de dominante au premier
renversement et doublure de la 5te :

#+ATTR_HTML: :class plat
| S | : | ré  | do  |
| A | : | sol | sol |
| T | : | ré  | mi  |
| B | : | si  | do  |

Voici un exemple en /do majeur/ avec un accord de dominante au second
renversement et doublure de la 5te :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | sol | sol |
| T | : | ré  | mi  |
| B | : | ré  | do  |

*** Quinte augmentée

La quinte de l’accord de dominante peut être augmentée afin de se
rapprocher de la tierce de l’accord de tonique. Nous prenons comme
exemple la gamme de /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si     | do  |
| A | : | sol    | sol |
| T | : | ré^{#} | mi  |
| B | : | sol    | do  |

*** Septième de dominante

#+TOC: headlines 1 local

**** Quatuor

Considérons le cas de l’accord de 7e de dominante et disposons-le sur
un quatuor. En /do majeur/, si on veut conserver les deux accords
complets, il faut écrire :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | mi  |
| T | : | ré  | sol |
| B | : | sol | do  |

On note la résolution du triton /fa — si/ vers la sixte /mi — do/,
caractéristique des cadences parfaites utilisant une septième de
dominante.

Cette disposition génère des quintes consécutives, ici entre le ténor
et la basse : /sol — ré/ est en effet suivie de /do — sol/. Si l’on
souhaite éviter cette disposition, on peut :

  - résoudre la note de 7e en montant vers la 5te de l’accord de
    tonique
  - faire monter la 5te de l’accord de dominante vers la 3ce de
    l’accord de tonique

Dans notre exemple, ces mouvements nous donnent:

#+ATTR_HTML: :class plat
| S | : | si   | do    |
| A | : | /fa/ | /sol/ |
| T | : | /ré/ | /mi/  |
| B | : | sol  | do    |

Il est aussi possible de supprimer une note d’un des deux accords, ou
de renverser l’accord de dominante.

***** Suppression de la quinte

Voici une variante d’une cadence parfaite en /do majeur/ où l’on a
supprimé la quinte de l’accord de septième de dominante, en la
remplaçant par une doublure de la fondamentale :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | mi  |
| T | : | sol | sol |
| B | : | sol | do  |

Voici une autre variante où c’est la quinte de l’accord de tonique qui
est supprimée :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | fa  | mi |
| T | : | ré  | do |
| B | : | sol | do |

***** Suppression de la tierce

On peut aussi :

  - faire évoluer la 7e de l’accord de dominante vers la 5te de
    l’accord de tonique
  - conserver le mouvement qui part de la 5te de l’accord de dominante
    vers la 1ale de l’accord de tonique

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | sol |
| T | : | ré  | do  |
| B | : | sol | do  |

On retrouve alors une [[file:musica-04-clavier.org::#heading:cadenceIonienneQuatreVoix][cadence ionienne à quatre voix]] formée en
ajoutant une voix disjointe et une voix conjointe montante.

***** Renversements

Certains renversements de l’accord de dominante permettent de
conserver les deux accords complets sur quatre voix sans générer de
quintes consécutives. Voici un exemple en /do majeur/ avec un premier
renversement :

#+ATTR_HTML: :class plat
| S | : | fa  | mi  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | si  | do  |

un autre avec un second renversement :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | mi  |
| T | : | sol | sol |
| B | : | ré  | do  |

et enfin un troisième renversement :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | fa  | mi  |

**** Quintette

Reprenons notre accord de 7e de dominante et disposons-le sur une
polyphonie de cinq voix ou plus. En /do majeur/, on peut écrire un
enchaînement du type :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| M | : | fa  | mi  |
| A | : | ré  | do  |
| T | : | sol | sol |
| B | : | sol | do  |

Cette fois, aucune quinte consécutive n’est observée.

Il s’agit d’une [[file:musica-04-clavier.org::#heading:cadenceIonienneCinqVoix][cadence ionienne à cinq voix]] formée en ajoutant une
voix disjointe, une voix constante et une voix conjointe descendante.

*** Septième sans fondamentale

L’accord de dominante peut être une septième sans fondamentale. Voici
un exemple du premier renversement en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | ré | do  |
| A | : | fa | mi  |
| T | : | ré | sol |
| B | : | si | do  |

Nous avons vu que l’accord de dominante sans fondamentale se dispose
de préférence sous la forme d’un
[[file:musica-06-partition.org::#heading:dispositionSeptièmeDominanteSansFondamentale][second renversement]].
En voici un exemple avec la quinte doublée :

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | mi  |
| T | : | ré | sol |
| B | : | ré | do  |

Si on double la septième, on aura :

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | mi  |
| T | : | fa | sol |
| B | : | ré | do  |
Il s’agit d’une [[file:musica-04-clavier.org::*Cadence ionienne à quatre voix][cadence ionienne à quatre voix]] formée en ajoutant une
voix conjointe montante et une voix conjointe descendante.

*** Neuvième de dominante

L’accord de dominante peut être une neuvième. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la  | sol |
| M | : | si  | do  |
| A | : | fa  | mi  |
| T | : | ré  | mi  |
| B | : | sol | do  |

*** Neuvième sans fondamentale

L’accord de dominante peut être une neuvième sans fondamentale.
Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la | sol |
| A | : | ré | mi  |
| T | : | fa | mi  |
| B | : | si | do  |

Cette disposition génère des quintes consécutives.

*** Neuvième sans quinte

L’accord de dominante peut être une neuvième sans quinte. Exemple
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la  | sol |
| A | : | si  | do  |
| T | : | fa  | mi  |
| B | : | sol | do  |

** Mode mineur

Les cadences parfaites du mode mineur sont similaires à celles du mode
majeur.

Il existe toutefois quelques nuances :

  - l’accord de dominante intègre généralement un degré 7 haussé d’un
    demi-ton afin de le transformer en sensible inférieure (mode
    mineur harmonique)
  - on peut aussi utiliser une tierce picarde sur l’accord de tonique
    lorsque ce procédé permet de renforcer la résolution

Exemple en /la mineur/, sur un quintette :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| M | : | ré      | do^{#} |
| A | : | si      | la     |
| T | : | mi      | mi     |
| B | : | mi      | la     |

On note l’utilisation de la sensible /sol^{#}/ et de la tierce picarde
/do^{#}/ afin de renforcer la résolution.

*** Neuvième de dominante

Autre exemple, avec une neuvième de dominante :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| M | : | ré      | do^{#} |
| A | : | fa      | mi     |
| T | : | si      | la     |
| B | : | mi      | la     |

* Cadence plagale

#+TOC: headlines 1 local

** Introduction

La *cadence plagale* est une cadence conclusive qui enchaîne un accord
de sous-dominante du degré 4 avec un accord de tonique du degré 1.
L’accord de tonique est un accord parfait à l’état fondamental.

** Quatuor

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | ré | do^{#} |
| A | : | la | la     |
| T | : | fa | mi     |
| B | : | ré | la     |

Remarquons que l’accord de sous-dominante peut être renversé sans
remettre en cause le caractère conclusif :

#+ATTR_HTML: :class plat
| S | : | ré | do^{#} |
| A | : | ré | la     |
| T | : | fa | mi     |
| B | : | la | la     |

** Quintette

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | ré | mi     |
| M | : | ré | do^{#} |
| A | : | la | la     |
| T | : | fa | mi     |
| B | : | ré | la     |

** Après une cadence parfaite

Une des utilisations possibles de la cadence plagale est de la placer
à la suite d’une cadence parfaite afin d’en renforcer le caractère
conclusif. Ce procédé est naturellement à réserver aux fins de
sections importantes d’une oeuvre musicale :

  - fin d’un mouvement
  - conclusion finale

* Autres cadences conclusives

#+TOC: headlines 1 local

** Introduction

Les cadences parfaite et plagale sont les cadences conclusives les
plus répandues, mais il en existe d’autres. En voici quelques unes.

** Cadence Bach

La *cadence Bach* est construite à partir d’une tonalité mineure, mais
elle suggére le relatif majeur. Par exemple, en /la mineur/, la
neuvième de dominante :

#+begin_center
mi sol^{#} si ré fa
#+end_center

contient les notes /fa/ et /si/ qui rappellent la cadence parfaite de
/do majeur/. On choisit d’utiliser le troisième renversement pour
obtenir le triton /fa — si/ et la note de 7e à la basse :

#+begin_center
ré fa mi sol^{#} si
#+end_center

La fondamentale de l’accord est supprimée, et nous obtenons :

#+begin_center
ré fa sol^{#} si
#+end_center

On enchaîne ensuite sur un accord de tonique à l’état fondamental, ce
qui nous donne par exemple :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | si      | do |
| T | : | fa      | mi |
| B | : | ré      | la |

Cette cadence combine l’évolution sensible inférieure — tonique
(/sol^{#} — la/), typique de la cadence parfaite, avec le saut
sous-dominante — tonique (/ré — la/) à la basse, typique de la cadence
plagale. On note aussi la résolution du triton /fa — si/ vers la sixte
/mi — do/, caractéristique du relatif /do majeur/.

*** Tierce picarde

La même cadence, avec tierce picarde :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | si      | do^{#} |
| T | : | fa      | mi     |
| B | : | ré      | la     |

** Cadence fauréenne modale

La *cadence fauréenne modale* est semblable à la cadence Bach, mais
elle n’utilise pas de sensible.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | si  | do |
| T | : | fa  | mi |
| B | : | ré  | la |

*** Tierce picarde

La même cadence, avec tierce picarde :

#+ATTR_HTML: :class plat
| S | : | sol | la     |
| A | : | si  | do^{#} |
| T | : | fa  | mi     |
| B | : | ré  | la     |

** Substitution tritonique

La *substitution tritonique* remplace le premier accord de la cadence
parfaite (dans sa version septième de dominante sur le degré 5) par un
accord respectant les mêmes écarts mais construit un triton plus bas,
sur le degré 2 abaissé d’un demi-ton (variante de l’accord
napolitain). Voici un exemple en /la mineur/ :

#+ATTR_HTML: :class plat

| S | : | la^b | la     |
| A | : | fa   | la     |
| T | : | ré   | do^{#} |
| B | : | si^b | la     |

On note que le /la^b/ est l’enharmonie de la sensible inférieure
/sol^{#}/. Présentée sous cette forme, il s’agit d’une cadence
parfaite utilisant une neuvième de dominante à quinte altérée, et sans
fondamentale :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la     |
| A | : | fa      | la     |
| T | : | ré      | do^{#} |
| B | : | si^b    | la     |

** Cadence italienne

La *cadence italienne* enchaîne les degrés forts de l’harmonie tonale,
en terminant par une cadence parfaite :

#+begin_center
4 — 5 — 1
#+end_center

Exemple de réalisation sur cinq voix, en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la | si  | do  |
| M | : | fa | fa  | mi  |
| A | : | fa | ré  | do  |
| T | : | do | sol | sol |
| B | : | fa | sol | do  |

*** Accord de tonique intercalé

Le degré 1 au second renversement est fréquemment intercalé entre
les degrés 4 et 5, donnant ainsi lieu à la suite d’accords :

#+begin_center
4 — 1 — 5 — 1
#+end_center

Exemple de réalisation sur cinq voix, en /do majeur/ :

#+ATTR_HTML: :class plat

| S | : | do | do  | si  | do  |
| M | : | la | sol | fa  | mi  |
| A | : | fa | mi  | ré  | do  |
| T | : | do | sol | sol | sol |
| B | : | fa | sol | sol | do  |

*** Dominante auxiliaire

La fonction de sous-dominante peut être assurée par un accord de
dominante auxiliaire. Nous avons alors la suite :

#+begin_center
2 — 5 — 1
#+end_center

Exemple de réalisation sur cinq voix, en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | la | si  | do  |
| M | : | fa | fa  | mi  |
| A | : | ré | ré  | do  |
| T | : | fa | sol | sol |
| B | : | ré | sol | do  |

**** Accord de tonique intercalé

Avec un accord de tonique intercalé :

#+begin_center
2 — 1 — 5 — 1
#+end_center

#+ATTR_HTML: :class plat
| S | : | ré | do  | si  | do  |
| M | : | la | sol | fa  | mi  |
| A | : | ré | mi  | ré  | do  |
| T | : | fa | sol | sol | sol |
| B | : | ré | sol | sol | do  |

* Cadence imparfaite

#+TOC: headlines 1 local

** Introduction

La *cadence imparfaite* est une cadence *ouverte* qui enchaîne une
dominante avec un *accord de tonique renversé*, ce qui permet de
relancer la musique.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | mi  |
| T | : | ré  | do  |
| B | : | sol | sol |

Autre exemple, avec l’accord de dominante au troisième renversement :

#+ATTR_HTML: :class plat
| S | : | ré  | sol |
| A | : | sol | sol |
| T | : | si  | do  |
| B | : | fa  | mi  |

** Résolution irrégulière

 Voici un exemple de résolution d’une 7e en /do majeur/, avec l’accord
de dominante au second renversement :

#+ATTR_HTML: :class plat
| S | : | si   | do    |
| A | : | /fa/ | /mi/  |
| T | : | sol  | sol   |
| B | : | ré   | mi    |

On remarque que la 3ce de l’accord de tonique est doublée. Si on
souhaité plutôt doubler la quinte, on aura la résolution irrégulière :

#+ATTR_HTML: :class plat
| S | : | si   | do    |
| A | : | /fa/ | /sol/ |
| T | : | sol  | sol   |
| B | : | ré   | mi    |

** Septième sans fondamentale

L’accord de dominante peut être une septième sans fondamentale.
Exemples du troisième renversement en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | sol |
| T | : | ré | do  |
| B | : | fa | mi  |

et :

#+ATTR_HTML: :class plat
| S | : | ré | do  |
| A | : | ré | sol |
| T | : | si | do  |
| B | : | fa | mi  |

** Neuvième sans fondamentale

L’accord de dominante peut être une neuvième sans fondamentale.
Exemple du second renversement en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | ré      | mi |
| T | : | fa      | mi |
| B | : | si      | do |

* Cadence plagale imparfaite

#+TOC: headlines 1 local

** Introduction

La *cadence plagale imparfaite* est une cadence *ouverte* qui enchaîne
une sous-dominante avec un *accord de tonique renversé*, ce qui permet
de relancer la musique.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | ré | do^{#} |
| A | : | ré | la     |
| T | : | la | la     |
| B | : | fa | mi     |

* Demi-cadence

#+TOC: headlines 1 local

** Introduction

La *demi-cadence* est une cadence *ouverte* qui enchaîne un accord de
degré quelconque avec un accord de dominante :

#+begin_center
X  —  Dominante
#+end_center

** Évolution depuis les cadences modales

Plaçons nous en /la mineur/ et considérons la
[[file:musica-04-clavier.org::#heading:cadencePhrygienneQuatreVoix][cadence phrygienne à quatre voix]]
formée par l’ajout de voix conjointes évoluant vers
la quinte et la tierce de l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | la | sol |
| A | : | ré | mi  |
| T | : | la | si  |
| B | : | fa | mi  |

Si nous haussons le /sol/ d’un demi-ton pour aboutir sur un accord
parfait majeur :

#+ATTR_HTML: :class plat
| S | : | la | sol^{#} |
| A | : | ré | mi      |
| T | : | la | si      |
| B | : | fa | mi      |

nous obtenons une des premières formes de demi-cadence, ici en /la mineur/.

** Sous-dominante

#+TOC: headlines 1 local

*** Introduction

Un choix fréquent de demi-cadence est celui où la sous-dominante
précéde la dominante. Exemple de réalisation en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do | si  |
| A | : | fa | sol |
| T | : | fa | ré  |
| B | : | la | sol |

Autre exemple, cette fois avec un accord de sous-dominante au premier
renversement, où la tonique est redoublée :

#+ATTR_HTML: :class plat
| S | : | do | si  |
| A | : | fa | sol |
| T | : | do | ré  |
| B | : | la | sol |

*** Cadence baroque

La *cadence baroque*, ou demi-cadence phrygienne, est le plus souvent
utilisée en mineur. Elle fait suivre un accord parfait de sous-dominante
au premier renversement avec un accord parfait majeur à la dominante.

Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | la | sol^{#} |
| A | : | ré | mi      |
| T | : | la | si      |
| B | : | fa | mi      |

/Remarque/ : la cadence baroque peut être vue comme une évolution de la
[[file:musica-04-clavier.org::#heading:cadencePhrygienneQuatreVoix][cadence phrygienne à quatre voix]].

*** Cadence fauréenne

La *cadence fauréenne* enchaîne un accord de sous-dominante dans son
second renversement avec un accord de dominante. L’accord de
sous-dominante est altéré si nécessaire afin d’obtenir les mêmes
écarts qu’une septième de dominante. Exemple en /la mineur/ :

#+begin_center
ré fa^{#} la do
#+end_center

La cadence s’écrit donc :

#+ATTR_HTML: :class plat
| S | : | fa^{#} | sol |
| A | : | do     | si  |
| T | : | ré     | mi  |
| B | : | la     | mi  |

** Dominante auxiliaire

#+TOC: headlines 1 local

*** Introduction

On associe souvent l’accord de dominante avec un accord de dominante
auxiliaire, formant ainsi une descente de quinte. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | ré | ré  |
| A | : | la | si  |
| T | : | fa | sol |
| B | : | ré | sol |

Autre exemple, cette fois avec une dominante auxiliaire sous la forme
d’un accord de septième altéré :

#+ATTR_HTML: :class plat
| S | : | fa^{#} | sol |
| A | : | do     | si  |
| T | : | ré     | ré  |
| B | : | la     | sol |

*** Sixte française

Parmi les accords de dominante auxiliaire, la sixte française, ici
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do     | si  |
| A | : | fa^{#} | sol |
| T | : | ré     | ré  |
| B | : | la^b   | sol |

*** Sixte italienne

Parmi les accords de dominante auxiliaire, la sixte italienne, ici
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do     | si  |
| A | : | fa^{#} | sol |
| T | : | do     | ré  |
| B | : | la^b   | sol |

*** Sixte allemande

Parmi les accords de dominante auxiliaire, la sixte allemande, ici
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do     | si  |
| A | : | fa^{#} | sol |
| T | : | mi^b   | ré  |
| B | : | la^b   | sol |

*** Napolitain

L’accord napolitain figure également parmi les dominantes secondaires.
Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | si^b | sol^{#} |
| A | : | fa   | mi      |
| T | : | ré   | si      |
| B | : | ré   | mi      |

Autre exemple, cette fois l’accord de dominante se présente sous la
forme d’une septième de dominante privée de sa quinte :

#+ATTR_HTML: :class plat
| S | : | si^b | sol^{#} |
| A | : | fa   | mi      |
| T | : | ré   | ré      |
| B | : | ré   | mi      |

L’accord de tonique au second renversement peut également faire
fonction de dominante, surtout si le degré 5 est doublé :

#+ATTR_HTML: :class plat
| S | : | si^b | la |
| A | : | fa   | mi |
| T | : | ré   | do |
| B | : | ré   | mi |

** Sus-dominante

La sus-dominante peut également précéder la dominante. Voici un
exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do | si  |
| A | : | mi | sol |
| T | : | do | ré  |
| B | : | la | sol |

** Tonique

La tonique peut également précéder la dominante. Voici un exemple en
/do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do  | si  |
| A | : | sol | sol |
| T | : | do  | ré  |
| B | : | mi  | sol |

* Sous-demi-cadence

#+TOC: headlines 1 local

** Introduction

La *sous-demi-cadence* est une cadence *ouverte* qui enchaîne un
accord de degré quelconque avec un accord de sous-dominante :

#+begin_center
X   —  Sous-dominante
#+end_center

** Napolitain

L’accord napolitain peut mener à une sous-dominante, exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | si^b | la |
| A | : | ré   | ré |
| T | : | fa   | fa |
| B | : | ré   | ré |

En mode majeur, deux notes sont modifiées. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | ré^b | do |
| A | : | fa   | fa |
| T | : | la^b | la |
| B | : | fa   | fa |

** Quinte augmentée

Comme cadence menant à une sous-dominante, notons aussi celle
utilisant l’accord de quinte augmentée placé sur la tonique. Exemple
en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| A | : | mi      | fa |
| B | : | do      | do |

* Fermeture

#+TOC: headlines 1 local

** Introduction

Une demi-cadence est par nature une cadence ouverte. Il est toutefois
possible de la rendre conclusive en l’enchaînant à un accord de
tonique à l’état fondamental. Il se produit alors une cadence
parfaite :

#+begin_center
X  —  Dominante  —  Tonique
#+end_center

Ce procédé est appelé *fermeture*.

On peut généraliser ce processus à toute cadence qui se termine par un
accord faisant fonction de dominante ou de sous-dominante. Par
exemple, la fermeture d’une sous-demi-cadence nous donnerait :

#+begin_center
X  —  Sous-dominante   —  Tonique
#+end_center

** Cadence italienne

On peut voir une cadence italienne comme la fermeture d’une
demi-cadence où la dominante est amenée par une sous-dominante.

Exemple de réalisation en /do majeur/, avec un accord parfait sur la
dominante :

#+ATTR_HTML: :class plat
| A | : | do | si  | do  |
| S | : | fa | ré  | mi  |
| T | : | fa | sol | sol |
| B | : | la | sol | do  |

Autre exemple, avec cette fois un accord de septième de dominante :

#+ATTR_HTML: :class plat
| S | : | do | si  | do  |
| A | : | fa | fa  | mi  |
| T | : | fa | sol | sol |
| B | : | la | sol | do  |

* Étau

#+TOC: headlines 1 local

** Introduction

Certaines cadences permettent de mettre en évidence la suite mélodique
des degrés 2 et 7, ce qui suggère l’arrivée prochaine de la tonique.
Le degré 1 est donc en quelque sorte pris en étau. Dans les modes
majeur et mineur harmonique, on aura :

#+begin_center
sus-tonique  —  sensible inférieure  —  tonique
#+end_center

Exemple en /do majeur/ :

#+begin_center
ré  —  si  —  do
#+end_center

Si le mode est à double sensible, ou si le degré 2 est altéré afin de
se transformer en sensible supérieure, on aura alors :

#+begin_center
sensible supérieure  —  sensible inférieure  —  tonique
#+end_center

Exemple avec /la/ comme tonique :

#+begin_center
si^b  —  sol^{#}  —  la
#+end_center

** Généralisation

On peut bien entendu construire un étau autour de n’importe quelle
note de la gamme. On a alors le schéma générique :

#+begin_center
Note supérieure — Note inférieure — Note attendue
#+end_center

** Dominante auxiliaire

Considérons la fermeture d’une demi-cadence où la dominante est amenée
par une dominante auxiliaire. Nous disposons les accords de manière à
former un étau autour de la tonique. Exemple de réalisation en /do
majeur/, avec l’étau /ré — si — do/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | fa   | ré   | mi   |
| T | : | la   | sol  | sol  |
| B | : | ré   | sol  | do   |

On remarque que la mise en place de l’étau nous oblige à disposer le
/ré/, note commune aux deux premiers accords, sur deux voix
différentes.

Si l’accord de dominante auxiliaire est au premier renversement, nous
avons :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | ré   | ré   | mi   |
| T | : | la   | sol  | sol  |
| B | : | fa   | sol  | do   |

En doublant la sous-dominante, nous avons :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | fa   | ré   | mi   |
| T | : | la   | sol  | sol  |
| B | : | fa   | sol  | do   |

** Accord napolitain

Considérons la fermeture d’une demi-cadence où la dominante est amenée
par un accord napolitain. Nous disposons les accords de manière à
mettre en évidence l’étau à double sensible qui entoure la tonique.
Exemple de réalisation en /la mineur/, avec l’étau
/si^b — sol^{#} — la/ :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /sol^{#}/ | /la/   |
| A | : | fa     | mi        | mi     |
| T | : | ré     | si        | do^{#} |
| B | : | ré     | mi        | la     |

On peut aussi doubler le /si^b/ et utiliser une septième de dominante
au troisième renversement :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /sol^{#}/ | /la/   |
| A | : | fa     | mi        | mi     |
| T | : | /si^b/ | si        | do^{#} |
| B | : | ré     | ré        | la     |

Autre exemple, cette fois l’accord de dominante se présente sous la
forme d’une septième de dominante privée de sa quinte :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /sol^{#}/ | /la/   |
| A | : | fa     | mi        | mi     |
| T | : | ré     | ré        | do^{#} |
| B | : | ré     | mi        | la     |

On peut intercaler un accord parfait de dominante :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /si/ | /sol^{#}/ | /la/   |
| A | : | fa     | sol  | mi        | mi     |
| T | : | ré     | mi   | ré        | do^{#} |
| B | : | ré     | mi   | mi        | la     |

ou un accord de tonique au second renversement :

#+ATTR_HTML: :class plat
| S | : | /si^b/ | /la/ | /sol^{#}/ | /la/   |
| A | : | fa     | do   | mi        | mi     |
| T | : | ré     | mi   | ré        | do^{#} |
| B | : | ré     | mi   | mi        | la     |

** Cadence plagale

La cadence plagale se présente parfois avec un accord intermédiaire du
degré 2 séparant les degrés 4 et 1. Cet accord permet de construire un
étau autour de la tierce de l’accord de tonique, c’est à dire le degré
3 de la gamme. Voici un exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /si/ | /do/ |
| A | : | la   | la   | la   |
| T | : | fa   | fa   | mi   |
| B | : | ré   | ré   | la   |

On hausse alors parfois la tierce de l’accord de sous-dominante, afin
de mettre en évidence une descente chromatique jusqu’à la quinte de
l’accord de tonique :

#+ATTR_HTML: :class plat
| S | : | /ré/     | /si/ | /do/ |
| A | : | la       | la   | la   |
| T | : | /fa^{#}/ | /fa/ | /mi/ |
| B | : | ré       | ré   | la   |

Voici le même exemple transposé en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | /fa/ | /ré/   | /mi/  |
| A | : | do   | do     | do    |
| T | : | /la/ | /la^b/ | /sol/ |
| B | : | fa   | fa     | do    |

* Cadences irrégulières

#+TOC: headlines 1 local

** Introduction

Une *cadence irrégulière* est une cadence où l’accord final n’est pas
celui attendu.

** Cadence rompue

La *cadence rompue* est une cadence parfaite où l’accord de tonique
est remplacé par un accord de sus-dominante :

#+begin_center
Dominante   —  Sus-dominante
#+end_center

En voici un exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | ré  | do |
| T | : | sol | mi |
| B | : | sol | la |

Autre exemple avec un accord de septième de dominante :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | ré  | do |
| T | : | fa  | mi |
| B | : | sol | la |

Autre exemple où la 5te de l’accord de dominante est supprimée
et remplacée par la fondamentale, produisant un saut de quinte
mélodique essentielle que l’on place à la basse :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| A | : | fa  | mi |
| T | : | sol | la |
| B | : | sol | do |

** Médiante

On peut remplacer l’accord de tonique d’une cadence parfaite par un
accord de médiante.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | sol | sol |
| A | : | ré  | mi  |
| T | : | si  | si  |
| B | : | sol | sol |

Autre exemple, avec une septième de dominante :

#+ATTR_HTML: :class plat
| S | : | fa  | mi  |
| A | : | si  | si  |
| T | : | sol | sol |
| B | : | ré  | sol |

** Sous-dominante

On peut remplacer l’accord de tonique d’une cadence parfaite par
un accord de sous-dominante.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | ré  | fa |
| T | : | si  | do |
| B | : | sol | fa |

Autre exemple, avec septième de dominante sans la quinte :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | fa  | fa |
| T | : | si  | do |
| B | : | sol | fa |

Si on souhaite plutôt doubler la tonique afin de la mettre en
évidence, on a alors :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | ré  | do |
| T | : | si  | do |
| B | : | sol | fa |

On peut ajouter une cinquième voix afin d’introduire une descente de
quinte à la basse, rapprochant ainsi cette cadence de la cadence
parfaite :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| M | : | ré  | do |
| A | : | si  | do |
| T | : | sol | fa |
| B | : | sol | do |

** Dominante auxiliaire

On peut remplacer l’accord de tonique d’une cadence parfaite en
grimpant le cycle des quintes jusqu’au degré 2, ce qui génère un
couple plagal.

L’idée est de produire une cadence plagale secondaire sur le degré 5.

Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | sol | fa |
| A | : | ré  | ré |
| T | : | si  | la |
| B | : | sol | ré |

* Amener les cadences

#+TOC: headlines 1 local

** Introduction

Certains enchaînements servent d’introduction à une cadence.

** Quarte et sixte cadentielle
:PROPERTIES:
:CUSTOM_ID: heading:quarteEtSixteCadentielle
:END:

La *quarte et sixte cadentielle* enchaîne deux accords faisant
fonction de dominante : un
[[file:musica-04-clavier.org::#heading:accordBroderie][accord broderie]]
du degré 1 au second
renversement et un accord du degré 5. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | do  | si  |
| A | : | sol | sol |
| T | : | mi  | ré  |
| B | : | sol | sol |

Cet enchaînement est parfois nommé *quarte et sixte de cadence*. On
peut le faire suivre de n’importe quelle cadence.

* Modulation

#+TOC: headlines 1 local

** Introduction

Une *modulation* est un changement de gamme de référence : on passe
d’une tonique /T1/ et d’un mode /M1/ à une tonique /T2/ et un mode
/M2/.

La modulation nécessite de transposer la gamme de départ de
l’intervalle qui sépare /T1/ de /T2/, puis à modifier les altérations
pour satisfaire le mode /M2/.

Pour qu’il y ait modulation, il ne suffit pas de modifier les notes
(altérations haussières ou baissières ajoutées ou annulées) afin de
s’insérer dans la nouvelle gamme, il faut également que la tonalité
/T2/ et le mode /M2/ soient clairement affirmés par des enchaînements
d’accords faisant intervenir :

  - les fonctions tonales de /T2/
  - le cycle tonal de /T2/ ou une de ses variantes
  - les notes, intervalles, accords différenciant le mode /M2/ de /M1/

*** Diatonique et chromatique

Il existe deux types de modulation :

  - si l’on enchaîne directement un accord appartenant clairement à la
    tonalité T1 avec un accord dont les altérations indiquent
    clairement la tonalité T2, le passage est net, il y a *modulation
    chromatique*.
  - si on intercale des accords pouvant appartenir à T1 ou à T2, la
    transition se fait en douceur, on parle de *modulation
    diatonique*.

Les accords provoquant une modulation chromatique sont dit *accords
chromatiques*. De même, les accords provoquant une modulation
diatonique sont dit *accords diatoniques*.

*** Pédale

Si il existe une pédale correspondant à la tonique ou à la dominante
de T1 avant la modulation, deux cas peuvent se présenter :

  - la pédale reste constante : la modulation est alors considérée
    comme passagère
  - la pédale s’arrête ou passe à la tonique ou à la dominante de T2 :
    la modulation est considérée comme importante

** Tonalités voisines

Lorsqu’il n’existe qu’une altération d’écart entre l’ancienne gamme et
la nouvelle, on parle de *modulation voisine*. Les gammes concernées
sont nommées *tons voisins*.

*** Quinte voisine

La modulation vers une quinte voisine s’effectue en transposant la
gamme de départ d’une quinte, ce qui ne produit qu’une seule
altération. Du point de vue des fonctions tonales, il s’agit de la
dominante et de la sous-dominante de la gamme de départ.

Exemples :

| Gamme     | Gamme      | Altération | Altérations |
| de départ | d’arrivée  | de départ  | d’arrivée   |
|-----------+------------+------------+-------------|
| do majeur | sol majeur |            | fa^{#}      |
| do majeur | fa majeur  |            | si^b        |
|-----------+------------+------------+-------------|
| la mineur | mi mineur  |            | fa^{#}      |
| la mineur | ré mineur  |            | si^b        |

**** Accords diatoniques & chromatiques

Considérons une modulation au ton voisin, par exemple /do majeur/ pour
T1 et /sol majeur/ pour T2. La seule altération intervenant est le
/fa^{#}/ du /sol majeur/. Les accords diatoniques sont donc les
accords qui ne font pas intervenir le /fa/ du /do majeur/ ou le
/fa^{#}/ du /sol majeur/. Les accords parfaits correspondant à cette
description sont :

  - la do mi
  - do mi sol
  - mi sol si
  - sol si ré

Par opposition, les accords chromatiques sont ceux où intervient un
/fa/ ou un /fa^{#}/, c’est-à-dire, aux altérations près :

  - si ré fa
  - ré fa la
  - fa la do

On peut appliquer le même raisonnement aux accords à base de quintes
ainsi qu’aux accords de quatre notes et plus.

*** Ton relatif

On peut moduler d’une gamme majeure au relatif mineur ou l’inverse. On
peut également imaginer de moduler à d’autres gammes relatives
correspondant aux autres modes naturels.

Ces modulations relatives ne modifient aucune note, à l’exception de
la sensible inférieure du mineur harmonique.

Exemples :

| Gamme     | Gamme     | Sensible  | Sensible  |
| de départ | d’arrivée | de départ | d’arrivée |
|-----------+-----------+-----------+-----------|
| do majeur | la mineur |           | sol^{#}   |
| la mineur | do majeur | sol^{#}   |           |

*** Quinte voisine & relatif

On peut moduler vers le relatif d’une quinte voisine, ou vice versa.

Exemples :

| Gamme     | Gamme      | Altérations | Altérations | Sensible  | Sensible  |
| de départ | d’arrivée  | de départ   | d’arrivée   | de depart | d’arrivée |
|-----------+------------+-------------+-------------+-----------+-----------|
| do majeur | mi mineur  |             | fa^{#}      | si        | ré^{#}    |
| do majeur | ré mineur  |             | si^b        | si        | do^{#}    |
|-----------+------------+-------------+-------------+-----------+-----------|
| la mineur | sol majeur |             | fa^{#}      | sol^{#}   | fa^{#}    |
| la mineur | fa majeur  |             | si^b        | sol^{#}   | mi        |

** Modulations éloignées

Une modulation vers une gamme autre qu’un ton voisin est dite
éloignée. Le procédé le plus naturel permettant de réaliser une
modulation éloignée est d’effectuer plusieurs modulations voisines
jusqu’à l’obtention du ton et du mode désiré. Mais il existe d’autres
procédés, tels que l’utilisation de pivots ou d’accords vagues, qui
font l’objet des sections suivantes.

** Pivots fonctionnels

Un *pivot fonctionnel* est un accord ou un groupe d’accords qui peut
s’intégrer dans deux logiques tonales différentes :

  - celle de la gamme que l’on quitte
  - celle de la gamme vers laquelle on module

Grâce à cette propriété, un pivot fonctionnel peut servir de
transition entre les deux gammes.

*** Couple tonal

Le couple tonal permet d’affirmer une nouvelle tonalité. Un des
accords joué peut être un pivot fonctionnel.

**** Accord de dominante

L’accord de septième de dominante de /do majeur/ peut être considéré
comme un accord du degré 3 sans fondamentale :

#+ATTR_HTML: :class plat
| sol si ré fa | <——>  | (mi) sol si ré fa |

Or, ce degré est la dominante d’une gamme dont la tonique serait une
quinte plus bas, à savoir le /la/, degré 6 de la gamme courante. Notre
accord de dominante permet donc de moduler vers le relatif /la mineur/
en jouant l’enchaînement :

#+ATTR_HTML: :class plat
| sol si ré fa | — | la do mi la |

Il est même possible d’altérer le premier accord pour faire entendre
la sensible inférieure /sol^{#}/ du mineur harmonique :

#+ATTR_HTML: :class plat
| sol^{#} si ré fa | — | la do mi la |

Lorsque le premier accord est préseenté sous la forme d’un permier
renversement, on fait apparaître le lien avec la
[[file:musica-04-clavier.org::#heading:cadenceIonienneQuatreVoix][cadence ionienne à quatre voix]].

**** Accord de dominante sans fondamentale

L’accord de dominante sans fondamentale de /do majeur/ :

#+ATTR_HTML: :class plat
| (sol) si ré fa | —> | si ré fa |

peut être également considéré comme un accord du degré 7, le /si/ dans
notre cas. Or, ce degré est la dominante d’une gamme dont la tonique
serait une quinte plus bas, à savoir le /mi/, degré 3 de la gamme
courante. Notre accord de dominante sans fondamentale permet donc de
moduler d’une tierce ascendante, il suffit de jouer l’enchaînement :

#+ATTR_HTML: :class plat
| si ré fa | — | mi sol si |

**** Sous-dominante

L’accord de sous-dominante :

#+begin_center
fa la do
#+end_center

peut être considéré comme la dominante d’une gamme dont la tonique
serait un /si^b/. On peut donc moduler vers /si^b majeur/ en jouant
l’enchaînement :

#+ATTR_HTML: :class plat
| fa la do | — | si^b ré fa |

**** Médiante

L’accord de degré 3 au second renversement de la gamme de /do
majeur/ :

#+begin_center
sol si mi (sol)
#+end_center

fait fonction de dominante de /do majeur/ de par la mise à la basse et
l’éventuelle doublure du /sol/, mais la fondamentale /mi/ est
également la dominante de la gamme de /la mineur/. On peut donc
moduler vers le relatif mineur en faisant entendre :

#+ATTR_HTML: :class plat
| sol si mi | — | la do mi |

**** Sous-médiante

L’accord de degré 6 renversé de la gamme de /do majeur/ :

#+begin_center
do mi la (do)
#+end_center

fait fonction de tonique de la tonalité en cours, mais comme sa
fondamentale est un /la/, il peut être vu comme la dominante d’une
gamme ayant /ré/ pour tonique. On peut donc moduler à la seconde
ascendante en jouant l’enchaînement :

#+ATTR_HTML: :class plat
| do mi la | — | ré fa la |

*** Couple plagal

Le couple plagal permet d’affirmer une nouvelle tonalité. Un des
accords joué peut être utilisé comme pivot.

**** Accord de dominante

L’accord de dominante de /do majeur/ :

#+begin_center
sol si ré fa
#+end_center

peut être vu comme l’accord de sous-dominante d’une gamme ayant /ré/
pour tonique. Pour moduler vers /ré dorien/, il suffit donc de faire
entendre :

#+ATTR_HTML: :class plat
| sol si ré fa | — | ré fa la ré |

Pour moduler vers /ré majeur/, il suffit d’ajouter les altérations
nécessaires :

#+ATTR_HTML: :class plat
| sol si ré fa | — | ré fa^{#} la ré |

*** Tonique

Un accord de tonique permet d’affirmer une nouvelle tonalité. L’accord
joué peut être utilisé comme pivot.

**** Sous-médiante

L’accord de degré 6 de /do majeur/ :

#+begin_center
do mi la (do)
#+end_center

fait fonction de tonique de part la mise à la basse et l’éventuelle
doublure du /do/, mais comme le /la/ est la fondamentale de l’accord,
il peut être également vu comme un accord de tonique de /la mineur/.

** Pivots polyphoniques

Un *pivot polyphonique* est un accord ou un groupe d’accords qui
s’intercale entre deux tonalités, de telle sorte que les enchaînements
soient constitués de mouvements polyphoniques élégants. Cet accord ou
groupe d’accords peut donc servir de transition entre les deux gammes.

#+begin_center
⁂
#+end_center

Considérons par exemple l’accord de tonique de la gamme de /mi
majeur/ :

#+begin_center
mi sol^{#} si
#+end_center

Cet accord est très semblable à l’accord de tonique de /do majeur/ au
premier renversement :

#+begin_center
mi sol do
#+end_center

L’enchaînement :

#+ATTR_HTML: :class plat
| S | : | si      | do  | (monte)    |
| A | : | sol^{#} | sol | (descend)  |
| B | : | mi      | mi  | (constant) |

permet donc de moduler par un simple mouvement contraire de /mi
majeur/ vers /do majeur/.

** Accords vagues

Les *accords vagues* sont des accords qui peuvent appartenir à
plusieurs tonalités différentes suivant l’enharmonie utilisée.

*** Septième diminuée

L’accord de septième diminuée peut être utilisé comme accord vague.

Par exemple, la septième diminuée suivante :

#+begin_center
sol^{#} si ré fa
#+end_center

peut être vue comme un accord de neuvième de dominante sans
fondamentale de la gamme de /la mineur harmonique/ :

#+ATTR_HTML: :class plat
| (mi) sol^{#} si ré fa | —> | sol^{#} si ré fa |

En utilisant l’enharmonie /sol^{#} = la^b/, cet accord peut se
réécrire :

#+begin_center
la^b si ré fa
#+end_center

dont l’état canonique est :

#+begin_center
si ré fa la^b
#+end_center

Ce dernier accord peut être analysé comme une neuvième de dominante
sans fondamentale de la gamme de /do mineur harmonique/ :

#+ATTR_HTML: :class plat
| (sol) si ré fa la^b | —> | si ré fa la^b |

Cet accord permet donc de moduler aisément à la tierce mineure. Il
permet même de moduler au triton si on l’écrit :

#+begin_center
do^b ré fa la^b
#+end_center

dont l’état fondamental est :

#+begin_center
ré fa la^b do^b
#+end_center

accord de neuvième de dominante sans fondamentale de la gamme de /mi^b
mineur harmonique/.

Cet accord permet donc de moduler aisément à la *tierce mineure* ou au
*triton*.

*** Quinte augmentée

L’accord de quinte augmentée peut être utilisé comme accord vague.

Par exemple, la quinte augmentée suivante :

#+begin_center
do mi sol^{#}
#+end_center

peut être vue comme un accord de septième sans fondamentale disposé
sur la tonique de /la mineur harmonique/ :

#+ATTR_HTML: :class plat
| (la) do mi sol^{#} | —> | do mi sol^{#} |

En utilisant l’enharmonie /sol^{#} = la^b/, cet accord peut se
réécrire :

#+begin_center
do mi la^b
#+end_center

dont l’état canonique est :

#+begin_center
la^b do mi
#+end_center

Ce dernier accord peut être analysé comme une septième sans
fondamentale disposée sur la tonique de /fa mineur harmonique/ :

#+ATTR_HTML: :class plat
| (fa) la^b dont mi | —> | la^b do mi |

Cet accord permet donc de moduler aisément à la *tierce majeure*.

*** Sixte allemande

L’accord de sixte allemande peut être utilisé comme accord vague.

Considérons par exemple la sixte allemande de /do majeur/ :

#+begin_center
la^b do mi^b fa^{#}
#+end_center

En utilisant l’enharmonie /fa^{#} = sol^b/, cet accord peut se
réécrire :

#+begin_center
la^b do mi^b sol^b
#+end_center

Ce dernier accord peut être analysé comme une septième de dominante de
la gamme de /ré^b majeur/.

Cet accord permet donc de moduler aisément à la *seconde mineure*.

*** Synthèse

Le tableau suivant nous livre un exemple des différentes écritures
possibles des accords vagues :

| Accords       | Orthographes         |
|---------------+----------------------|
| 7e dim        | sol^{#} si ré fa     |
|               | si ré fa la^b        |
|               | ré fa la^b do^b      |
|               | mi^{#} sol^{#} si ré |
| 5te aug       | la^b do mi           |
|               | do mi sol^{#}        |
|               | mi sol^{#} si^{#}    |
| 6te allemande | la^b do mi^b fa^{#}  |
|               | la^b do mi^b sol^b   |

* Cadences modulantes

#+TOC: headlines 1 local

** Introduction

Une *cadence modulante* est une cadence irrégulière qui dévie vers un
accord appartenant à une autre tonalité, ce qui peut provoquer une
modulation. On a alors le schéma :

#+begin_center
X  —  Y de Z
#+end_center

où /X/ peut être une fonction de dominante, de sous-dominante, etc.

** Sous-dominante

Il est possible de moduler en produisant un accord proche d’un accord
de tonique, mais altéré pour devenir la dominante d’une tonique
secondaire placée sur le degré 4. Si on choisit le cas le plus évident
du degré 5 pour assurer la fonction de dominante, on obtient un accord
5 de 4.

Cet exemple utilise un accord de dominante de /la mineur/ suivi d’un
accord de neuvième de dominante de /ré mineur/ :

#+ATTR_HTML: :class plat
| S | : | si      | si^b   |
| A | : | sol^{#} | sol    |
| T | : | ré      | do^{#} |
| B | : | mi      | la     |

** Relatif mineur

Il est possible de moduler au relatif mineur en faisant suivre
l’accord de dominante de la tonalité de départ par celui de la
tonalité relative mineure.

Voici un exemple qui part de /do majeur/ et qui module vers /la
mineur/ :

#+ATTR_HTML: :class plat
| S | : | fa  | mi      |
| A | : | ré  | ré      |
| T | : | si  | si      |
| B | : | sol | sol^{#} |

** Relatif majeur

Il est possible de moduler au relatif majeur en faisant suivre
l’accord de dominante de la tonalité de départ par celui de la
tonalité relative majeure.

Voici un exemple qui part de /la mineur/ et qui module vers /do
majeur/ :

#+ATTR_HTML: :class plat
| S | : | mi      | fa  |
| A | : | ré      | ré  |
| T | : | si      | si  |
| B | : | sol^{#} | sol |

* Complément sur les cadences modales

#+TOC: headlines 1 local

** Introduction

Les modes naturels ne permettent pas de couvrir toutes les
configurations possibles concernant l’arrivée par ton ou demi-tons sur
la basse, la quinte et l’octave. Nous utilisons ici d’autres modes
afin de compléter ces possibilités.

** Acoustique

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | si^b | do |
| B | : | ré   | do |

on remarque que les deux voix évoluent par ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | fa^{#} | sol |
| B | : | ré     | do  |

on remarque que la voix supérieure monte d’un demi-ton, tandis que la
voix inférieure descend d’un ton.

** Napolitain

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | ré^{#} | mi |
| B | : | fa     | mi |

on remarque que les deux voix évoluent par demi-ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | la | si |
| B | : | fa | mi |

on remarque que la voix supérieure monte d’un ton, tandis que la voix
inférieure descend d’un demi-ton.

** Tzigane avec seconde mineure

Il s’agit d’une variante du mode tzigane avec le degré 2 abaissé :

#+begin_center
la si^b do ré^{#} mi fa sol^{#} la
#+end_center

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| B | : | si^b    | la |

on remarque que les deux voix évoluent par demi-ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | ré^{#} | mi |
| B | : | si^b   | la |

on remarque que les deux voix évoluent par demi-ton. Notons aussi que
le premier intervalle harmonique est une tierce augmentée.

** Tableau récapitulatif

| Mode               | Intervalle  | Intervalle     | Intervalle    |
|                    | de la basse | vers la quinte | vers l’octave |
|--------------------+-------------+----------------+---------------|
| acoustique         | ton         | demi-ton       | ton           |
| napolitain         | demi-ton    | ton            | demi-ton      |
| tzigane avec 2de m | demi-ton    | demi-ton       | demi-ton      |

* Autres cadences remarquables

#+TOC: headlines 1 local

** Clausula vera à trois voix

Il s’agit d’une clausula vera à deux voix à laquelle on ajoute une
descente de quinte sur une troisième voix. Exemple :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| A | : | si  | la |
| B | : | mi  | la |

** Cadence plagale d’intervalles

Il s’agit d’une cadence intérieure où la basse évolue en montant
de la sous-dominante vers la tonique. Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | fa | mi |
| B | : | ré | la |

** Cadence anglaise

La cadence anglaise fait contraster la sous-tonique ave
la sensible inférieure. Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | si  | sol^{#} |
| A | : | mi  | ré      |
| T | : | sol | fa      |
| B | : | mi  | mi      |

** Cadence évadée

On part d’un accord parfait sur la dominante, qui évolue vers un
accord de septième de dominante en faisant descendre la basse par
mouvement conjoint. On enchaîne ensuite par un accord de tonique
renversé. Exemple en /do majeur/ :

#+ATTR_HTML: :class plat
| S | : | si  | si  | do  |
| A | : | sol | sol | sol |
| T | : | ré  | ré  | do  |
| B | : | sol | fa  | mi  |

** Cadence d’accords lydienne

Il s’agit d’une demi-cadence lydienne où le premier accord est
haussé d’un demi-ton. Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| S | : | la^{#} | sol^{#} |
| A | : | ré^{#} | mi      |
| T | : | la^{#} | si      |
| B | : | fa^{#} | mi      |

** Cadence bourguignonne

Cadence d’accords lydienne sans la fondamentale du premier accord.
Exemple en /la mineur/ :

#+ATTR_HTML: :class plat
| A | : | ré^{#} | mi |
| T | : | la     | si |
| B | : | fa^{#} | mi |
