
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 11 : Coda
#+AUTHOR: - chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Périodes

On distingue plusieurs périodes musicales  :

| Début |  Fin | Période             |
|-------+------+---------------------|
|     — |  500 | antique             |
|   500 | 1030 | pré-roman           |
|  1030 | 1163 | roman               |
|  1163 | 1245 | notre-dame          |
|  1245 | 1315 | ars antiqua         |
|  1315 | 1377 | ars nova            |
|  1377 | 1400 | ars subtilior       |
|  1400 | 1420 | contenance angloise |
|  1420 | 1600 | renaissance         |
|  1600 | 1750 | baroque             |
|  1750 | 1820 | classique           |
|  1820 | 1900 | romantique          |
|  1900 |    — | contemporain        |

Bien entendu, les styles de différents périodes ont pu coexister, et
les périodes de transition sont généralement plus longues qu’une
année. Les dates données ne sont qu’indicatives.


** Évolution

  - 8e siècle
    + apparition des modes grégoriens
  - 13e siècle
    + début des cadences d’intervalles
  - 14e siècle
    + premières durées séparées pour les notes
  - 1558
    + Zarlino : prototype de l’accord parfait
  - ca 1600
    + début de la basse continue
      * chiffrage sous la basse symbolisant l’accord à réaliser
      * continuo
	- 1 instrument pour la basse
	- 1 instrument pour le reste des accords
  - 1612
    + Lipius : accord parfait & renversements
  - 1722
    * Rameau
      - fondamentale
      - accords de 7e


* Grèce antique

#+TOC: headlines 1 local

** Modes

#+TOC: headlines 1 local

*** Introduction

La nomenclature médiévale provient d’une interprétation erronée des
modes grecs. Il est donc important de faire la distinction entre :

  - les modes de la Grèce antique d’une part
  - la terminologie médiévale des modes naturels, encore utilisée
    aujourd’hui comme référence, d’autre part

Ces deux nomenclatures utilisent les mêmes noms pour désigner des
ensembles de modes bien distincts.


*** Construction

La pensée musicale de la Grèce antique est basée sur :

  - une suite de notes descendante
  - le *tétracorde*, un ensemble de quatre notes qui se suivent dans
    une gamme

La combinaison de ces deux principes nous donne l’idée du *tétracorde
descendant*, c’est-à-dire un tétracorde qui évolue de l’aigu vers le
grave.

Une gamme se construit avec deux tétracordes descendants joints par
une note commune. Par exemple, si nous partons de /mi/, nous
obtenons :

#+begin_center
mi ré do si — la sol fa mi —> mi ré do si la sol fa mi
#+end_center

Cette pensée mélodique descendante explique à la fois les similarités
et les différences avec la théorie musicale actuelle :

  - la première note du premier tétracorde est la *note principale* de
    la gamme, et correspond à la tonique.

  - la première note du deuxième tétracorde, la *mèse*, est située une
    quinte plus bas et correspond à la sous-dominante

  - la musique grecque s’appuie donc sur la dualité descendante
    tonique — sous-dominante, à comparer avec la dualité ascendante
    tonique — dominante de la musique tonale

Il existe quatre gammes fondamentales correspondant à quatre modes
fondamentaux, que nous retrouvons dans le tableau suivant :

| Mode       | Tétracorde 1 | Tétracorde 2 | Principale | Mèse | Gamme                    |
|------------+--------------+--------------+------------+------+--------------------------|
| dorien     | mi ré do si  | la sol fa mi | mi         | la   | mi ré do si la sol fa mi |
| phrygien   | ré do si la  | sol fa mi ré | ré         | sol  | ré do si la sol fa mi ré |
| lydien     | do si la sol | fa mi ré do  | do         | fa   | do si la sol fa mi ré do |
| mixolydien | si la sol fa | mi ré do si  | si         | mi   | si la sol fa mi ré do si |

D’autres gammes peuvent être construites un tétracorde en-dessous
(préfixe hypo) ou un tétracorde au-dessus (préfixe hyper) de ces modes
fondamentaux. Trois nouveaux modes apparaissent alors :

| Mode         | Tétracorde 1 | Tétracorde 2 | Principale | Mèse | Gamme                     |
|--------------+--------------+--------------+------------+------+---------------------------|
| hypodorien   | la sol fa mi | ré do si la  | la         | ré   | la sol fa mi ré do si la  |
| hypophrygien | sol fa mi ré | do si la sol | sol        | do   | sol fa mi ré do si la sol |
| hypolydien   | fa mi ré do  | si la sol fa | fa         | si   | fa mi ré do si la sol fa  |

Les autres modes ne sont que des synonymes des modes déjà obtenus :

  - hypomixolydien = dorien
  - hyperdorien = mixolydien
  - hyperphrygien = hypodorien
  - hyperlydien = hypophrygien
  - hypermixolydien = hypolydien


*** Intervalles

Nous analysons la suite des intervalles séparant les notes au sein de
chaque tétracorde.

Par exemple, si nous exprimons les intervalles en demi-tons, la
structure interne du premier tétracorde du mode grec dorien s’écrit :

#+ATTR_HTML: :class plat
| mi |   | ré |   | do |   | si |
|    | 2 |    | 2 |    | 1 |    |

quant à celle du second :

#+ATTR_HTML: :class plat
| la |   | sol |   | fa |   | mi |
|    | 2 |     | 2 |    | 1 |    |

En répétant le même raisonnement pour chaque mode, nous obtenons le
tableau suivants :

| Mode         | Tétracorde 1 | Tétracorde 2 |
|--------------+--------------+--------------|
| Dorien       | 2 2 1        | 2 2 1        |
| Phrygien     | 2 1 2        | 2 1 2        |
| Lydien       | 1 2 2        | 1 2 2        |
| Mixolydien   | 2 2 2        | 2 2 1        |
| Hypodorien   | 2 2 1        | 2 1 2        |
| Hypophrygien | 2 1 2        | 1 2 2        |
| Hypolydien   | 1 2 2        | 2 2 2        |

On voit que les modes dorien, phrygien et lydien sont composés de deux
tétracordes de même structure.


*** Genres

Les notes centrales du deuxième tétracorde peuvent être altérée vers la note
principale, ce qui nous donne les genres :

  - diatonique : aucune altération
  - chromatique : la deuxième note est altérée
  - enharmonique : les trois dernières notes sont contenues dans un demi-ton

Par exemple, on a :

  - le dorien diatonique : mi ré do si la sol fa mi
  - le dorien chromatique : mi ré do si la sol^b fa mi
  - le dorien diatonique : mi ré do si la sol^bb (note entre fa et fa^b) mi


*** Correspondance avec les modes médiévaux


**** Tonique

Le tableau suivant compare les modes grecs avec les modes médiévaux en
se basant sur la note principale, ou tonique :

| Tonique | Grèce antique | Mode médiéval |
|---------+---------------+---------------|
| si      | Mixolydien    | Locrien       |
| mi      | Dorien        | Phrygien      |
| la      | Hypodorien    | Éolien        |
| ré      | Phrygien      | Dorien        |
| sol     | Hypophrygien  | Mixolydien    |
| do      | Lydien        | Ionien        |
| fa      | Hypolydien    | Lydien        |


**** Intervalles

On peut aussi comparer les modes grecs avec les modes médiévaux en se
basant sur les intervalles de tons ou demi-tons entre les notes
successives. Pour être considérés comme similaires, les intervalles
/descendants/ grecs doivent être égaux aux intervalles /ascendants/ de
la musique tonale.

Par exemple, si nous exprimons les intervalles en demi-tons, la
structure interne descendante du mode grec dorien s’écrit :

#+ATTR_HTML: :class plat
| mi |   | ré |   | do |   | si |   | la |   | sol |   | fa |   | mi |
|    | 2 |    | 2 |    | 1 |    | 2 |    | 2 |     | 2 |    | 1 |    |

ce qui est identique à la structure interne ascendante du mode
médiéval ionien :

#+ATTR_HTML: :class plat
| do |   | ré |   | mi |   | fa |   | sol |   | la |   | si |   | do |   |   |
|    | 2 |    | 2 |    | 1 |    | 2 |     | 2 |    | 2 |    | 1 |    |   |   |

En procédant au même raisonnement avec les autres modes, on obtient le
tableau suivant :

| Grèce antique | Principale | Intervalles   | Tonique | Mode médiéval |
|---------------+------------+---------------+---------+---------------|
| Hypolydien    | fa         | 1 2 2 1 2 2 2 | si      | Locrien       |
| Lydien        | do         | 1 2 2 2 1 2 2 | mi      | Phrygien      |
| Hypophrygien  | sol        | 2 1 2 2 1 2 2 | la      | Éolien        |
| Phrygien      | ré         | 2 1 2 2 2 1 2 | ré      | Dorien        |
| Hypodorien    | la         | 2 2 1 2 2 1 2 | sol     | Mixolydien    |
| Dorien        | mi         | 2 2 1 2 2 2 1 | do      | Ionien        |
| Mixolydien    | si         | 2 2 2 1 2 2 1 | fa      | Lydien        |

On remarque que le cycle des quintes des notes principales est inversé
par rapport au cycle des quintes des toniques.


** Genres

#+TOC: headlines 1 local

*** Ode

L’ode grecque est liée au théâtre, à la musique, à la poésie et à la
danse. Elle contient un ou plusieurs cycles. Chaque cycle se composait
de trois phases :

  - strophe
    + chanté et dansé
    + se danse de droite à gauche
  - antistrophe
    + même rythme que la strophe
    + chanté et dansé
    + se danse en sens inverse, de gauche à droite
  - épode
    + chanté
    + rythme différent


* Notation

#+TOC: headlines 1 local

** Durées
:PROPERTIES:
:CUSTOM_ID: heading:notation_durees
:END:

Au 14e siècle, les anciennes durées se nommaient, de la plus longue à
la plus courte :

  - la maxime
  - la longue
  - la brève
  - la semi-brève
  - la minime
  - la semi-minime

Elles étaient binaires ou ternaires suivant le contexte rythmiques. On
avait ainsi :

  - le maximodus
    + parfait : maxime = 3 longues
    + imparfait : maxime = 2 longues
  - le modus
    + parfait : longue = 3 brèves
    + imparfait : longue = 2 brèves
  - le tempus
    + parfait
      * brève = 3 semi-brèves
      * symbole : cercle en début de portée
    + imparfait
      * brève = 2 semi-brèves
      * symbole : demi-cercle en début de portée
  - la prolatio
    + majeure
      * semi-brève = 3 minimes
      * symbole
	- point au centre du cercle, ou cercle barré
	- point au centre du demi-cercle, ou demi-cercle barré
    + mineure
      * semi-brève = 2 minimes
      * symbole : sans point ni barré

Équivalent en notation moderne :

  - modus : carrure de 2 ou 3 mesures
  - tempus : mesure de 2 ou 3 temps
  - prolatio : temps binaire ou ternaire

Pendant la période baroque, la semi-brève devient la ronde actuelle.


* Consonance

#+TOC: headlines 1 local

** Introduction

Au cours des siècles, le caractère consonant ou dissonant des
intervalles harmoniques a beaucoup évolué. Ainsi, la musique de la
grèce antique se basait sur la spirale des quintes pures. La gamme
était alors pythagoricienne tandis que l’octave, la quinte, et la
quarte se partageaient la tribune des consonances. Johannes de
Garlandia, au 13e siècle, admet les tierces dans les consonances, mais
ce n’est qu’à partir de Johannes de Muris, au début du 14e siècle, que
les sixtes sont également considérées comme consonantes.


** Une histoire de quarte
:PROPERTIES:
:CUSTOM_ID: heading:consonanceQuarteHarmonique
:END:

#+TOC: headlines 1 local

*** Introduction

Aujourd’hui, la quarte harmonique conserve un statut ambigu :

  - elle est consonante dans n’importe quel intervalle ne faisant pas
    intervenir la basse
  - elle demande une « résolution » dans l’accord de quarte et sixte,
    vers un accord parfait à l’état fondamental
    + la quarte harmonique avec la basse est alors suivie d’une tierce

Nous proposons dans cette section deux démonstrations et autres
réflexions permettant de trancher définitivement la question.


*** Propriété intrinsèque

Le caractère consonant ou dissonant d’un intervalle harmonique doit
être une propriété intrinsèque de ce dernier, et ne peut dépendre de
son environnement. Si on considère que la quarte harmonique entre le
soprano et l’alto est consonante dans l’accord parfait à l’état
fondamental :

#+ATTR_HTML: :class plat
| S | : | /do/  |
| A | : | /sol/ |
| T | : | mi    |
| B | : | do    |

on doit également la considérer comme consonante en l’absence des deux
voix inférieures. L’alto joue alors le rôle de la basse, ce qui nous
donne :

#+ATTR_HTML: :class plat
| S | : | /do/  |
| A | : | /sol/ |


*** Harmoniques naturelles

Considérons la série des six premières harmoniques naturelles, à
laquelle on ajoute un redoublement d’octave :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | do |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |  8 |

Cette série est à la base de la classification des intervalles en
consonants et dissonants. À ce stade, il faut être cohérent :

  - soit on accepte que tous les intervalles de cette série sont
    consonants, et la quarte l’est aussi
  - soit on accepte uniquement comme consonants les intervalles
    incluant la basse

Dans ce dernier cas, les intervalles consonants sont :

| Intervalle     | Note I | Note II |
| harmonique     |        |         |
|----------------+--------+---------|
| unisson        |      1 |       1 |
| octave         |      1 |       2 |
| quinte         |      1 |       3 |
| tierce majeure |      1 |       5 |

Tous les autres intervalles doivent alors être considérés comme
dissonants, incluant :

  - la quarte
  - la tierce mineure
  - les sixtes

ce qui est musicalement inconcevable. Pire encore, l’accord parfait
mineur et les accords de sixte doivent alors être classés parmi les
accords dissonants, ce qui est d’une aburdité monumentale.
Arrêtons-nous là, la démonstration est faite.

Nous sommes donc amenés à revenir au choix le plus naturel, qui est de
considérer /tous/ les intervalles de la série :

#+ATTR_HTML: :class plat
| /Notes/   | : | do | do | sol | do | mi | sol | do |
| /Numéros/ | : |  1 |  2 |   3 |  4 |  5 |   6 |  8 |

comme consonants. Par conséquent, l’intervalle de quarte harmonique
est /toujours/ consonant.


*** Quarte et sixte

Il est abusif de parler de résolution de l’accord de quarte et sixte
vers l’accord parfait à l’état fondamental : il ne s’agit que d’un
accord ornemental enchaîné avec l’accord stratégique qu’il ornemente.


*** Cadence modale

Si la quarte est consonante, pourquoi utilise-t-on plutôt l’unisson,
l’octave et la quinte pour les cadences d’intervalles ? Simplement
parce que les consonances parfaites sont encore plus consonantes que
la quarte. En fait, si on devait établir un ordre décroissant des
consonances, on aurait :

#+begin_center
unisson > octave > quinte > quarte > tierces & sixtes
#+end_center

Raison pour laquelle les cadences d’intervalles suivantes sont très
utilisées :

  - extérieure conjointe depuis la sixte vers l’octave
  - intérieure conjointe depuis la tierce vers l’unisson


* Polyphonie

#+TOC: headlines 1 local

** Introduction

La polyphonie médiévale a fait ses premiers pas en utilisant un
processus d’accompagnement simple : une voix parallèle, appelée *voix
organale*, était alors ajoutée à une mélodie préexistante de
référence, la *voix principale*. Suivant l’intervalle utilisé, on
parle :

  - d’ *organum strict* : les voix sont séparées par une quinte ou une
    quarte

  - de *gymel*, ou de *faux-bourdon*, les voix sont séparés par une
    tierce ou une sixte

Au fil du temps, la voix organale est devenue de plus en plus ornée et
indépendante. On tournait alors autour du parallélisme strict, ne
revenant à l’intervalle harmonique original que lors des convergences
de fin de phrase. C’était l’époque du *déchant* et de l’
*organum fleuri*. Plus tard, d’autres voix ont été ajoutées, donnant
ainsi naissance au *motet*. Les lignes mélodiques ont pris de plus en
plus d’indépendance, la cohérence de l’ensemble étant assurée par les
lois du contrepoint, ainsi que par l’échange de motifs mélodiques via
des procédés d’imitation et de variation. Le *ricercar* et la *fugue*
ont abondamment utilisé ce type de constructions.

Suivant les époques :

  - la voix principale était aussi appelée *vox principalis*,
    *cantus*, *cantus firmus*, ou encore *plain-chant*

  - la voix organale était aussi appelée *vox organalis*, *discantus*
    ou *organum fleuri*

  - le terme de motet viendrait de *motetus*, le petit mot, en
    référence au texte ajouté sur la ou les voix supplémentaires


** Ligne du temps

Dans les organum, les voix se nommaient ainsi :

  - vox organale
  - vox principalis

Puis, dans le déchant :

  - discantus
  - cantus

Ensuite, du 11e au 13e siècle :

#+ATTR_HTML: :class plat
| quadriplum | = | soprano |
| triplum    | = | alto    |
| duplum     | = | ténor   |
| tenor      | = | basse   |

Au 16e siècle :

#+ATTR_HTML: :class plat
| superius           | = | soprano |
| contratenor        | = | alto    |
| tenor              | = | ténor   |
| contratenor bassus | = | basse   |

Variante allemande :

#+ATTR_HTML: :class plat
| superius | = | soprano |
| altus    | = | alto    |
| tenor    | = | ténor   |
| bass     | = | basse   |

Variante anglaise :

#+ATTR_HTML: :class plat
| superius     | = | soprano |
| countertenor | = | alto    |
| tenor        | = | ténor   |
| bassus       | = | basse   |

Variante italienne :

#+ATTR_HTML: :class plat
| superius  | = | soprano |
| contralto | = | alto    |
| tenor     | = | ténor   |
| basso     | = | basse   |

Variante française :

#+ATTR_HTML: :class plat
| superius     | = | soprano |
| haute-contre | = | alto    |
| ténor        | = | ténor   |
| basse        | = | basse   |

Époque baroque :

#+ATTR_HTML: :class plat
| contre-haut  |   |       |
| dessus       |   |       |
| contre-bas   |   |       |
| haute-contre |   |       |
| taille       | = | ténor |
| basse-contre | = | basse |


* Harmonie tonale

#+TOC: headlines 1 local

** Introduction

La théorie harmonique qui prédomine aujourd’hui est souvent nommée
*harmonie tonale*, ou encore *harmonie classique*. C’est elle qui est
utilisée dans la musique baroque, classique et romantique. Elle est
également omniprésente en jazz et en musique de variété, sous une
forme étendue où modes et accords prennent parfois des tournures
exotiques.


** Intéractions entre les voix

La musique polyphonique médiévale tient compte de tous les intervalles
formés par la superposition des mélodies. À quatre voix, on devra donc
tenir compte des écarts :

  - ténor - basse
  - alto - basse
  - soprano - basse
  - alto - ténor
  - soprano - ténor
  - soprano - alto

Pour un quatuor, la situation n’est pas encore trop complexe, mais il
faut savoir que le nombre de ces intéractions augmente rapidement avec
le nombre de voix présentes. Pour /N/ voix, on aura :

#+begin_center
N × (N - 1) / 2
#+end_center

intervalles distincts, ce qui nous donne par exemple :

|  Nombre |        Nombre |
| de voix | d’intervalles |
|---------+---------------|
|       2 |             1 |
|       3 |             3 |
|       4 |             6 |
|       5 |            10 |
|       6 |            15 |
|       7 |            21 |

La complexité de la tâche atteint donc rapidement des sommets.
L’harmonie tonale tente une autre approche en accordant une importance
prépondérante aux intervalles formés par une voix quelconque et la
basse. Le nombre d’intéractions à prendre en compte est donc réduit
à :

#+begin_center
N - 1
#+end_center

c’est-à-dire :

|  Nombre |        Nombre |
| de voix | d’intervalles |
|---------+---------------|
|       2 |             1 |
|       3 |             2 |
|       4 |             3 |
|       5 |             4 |
|       6 |             5 |
|       7 |             6 |

En contrepartie de ce gain en simplicité, les autres intervalles sont
quelque peu éclipsés. Ils ne sont toutefois pas complètement oubliés :

  - la consonance des intervalles est obtenue en considérant tous les
    intervalles internes du début de la série des harmoniques
    naturelles, et pas seulement ceux faisant intervenir la basse
  - les mouvements polyphoniques étudient les progressions de chaque
    couple de lignes mélodiques
  - les dispositions des accords sont étudiées en détail dans toutes
    les voix

L’harmonie tonale est donc une théorie qui a le mérite de rester
relativement simple tout en constituant une bonne approximation de la
réalité musicale.
