
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 02 : Partition
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1


* Mélodie, Harmonie, Rythme

#+TOC: headlines 1 local


** Introduction

Une *mélodie* est un ensemble de notes jouées *successivement*.

Une *harmonie* est un ensemble de notes jouées *simultanément*.

Un *rythme* est l’ensemble des durées d’une mélodie.


** Motif

Un *motif* est un fragment de mélodie jouée à un rythme
donné. Un motif résulte donc de l’association d’une structure
mélodique avec une structure rythmique.

Exemple de motif :

#+ATTR_HTML: :class plat
| Mélodie | : | do | ré | sol | fa |
| Rythme  | : | B  | B  | N   | N  |


*** Thème

Un *thème* est un motif élaboré et reconnaissable, qui revient à
plusieurs reprises pendant l’oeuvre musicale.


** Intervalles

Un *intervalle mélodique* est un intervalle dont les deux notes sont
jouées successivement.

Un *intervalle harmonique* est un intervalle dont les deux notes sont
jouées simultanément.


*** Unisson

Un *unisson mélodique* consiste à répéter la même note.

Un *unisson harmonique* consiste à faire jouer la même note au même
moment par deux instruments différents.


* Mouvements mélodiques

#+TOC: headlines 1 local


** Introduction

Les *mouvements mélodiques* analysent les intervalles
d’une mélodie.


** Direction

Un intervalle mélodique est dit :

  - *ascendant* si la deuxième note est plus aiguë que la première

  - *descendant* si la deuxième note est plus grave que la première


** Mouvement conjoint

Un mouvement *conjoint* est un intervalle mélodique d’unisson ou de
seconde. Rentrent donc dans cette catégorie :

  1. l’unisson mélodique, ou répétition d’une même note
  2. la seconde mineure mélodique
  3. la seconde majeure mélodique

Voici quelques exemples de mouvements conjoints :

  - Seconde majeure ascendante : do ré
  - Seconde mineure ascendante : mi fa
  - Unisson : sol sol
  - Seconde mineure descendante : fa mi
  - Seconde majeure descendante : ré do


*** Continuité

Une mélodie qui ne présente que des mouvements conjoints est dite
*continue*. Une mélodie constituée d’une majorité de mouvements
conjoints est dite majoritairement continue.


** Mouvement disjoint

Un mouvement *disjoint* est un intervalle mélodique non conjoint.
Rentrent donc dans cette catégorie :

  - les tierces
  - les quartes
  - les quintes
  - les sixtes
  - les septièmes
  - les octaves
  - les neuvièmes
  - =...=

et ce quel que soit leur qualificatif : juste, majeur, mineur,
augmenté, diminué, sur-augmenté ou sur-diminué.


*** Discontinuité

Un mouvement disjoint provoque un *saut*, une *discontinuité* dans une
mélodie.


** Mouvement chromatique

Un mouvement *chromatique* est constitué de trois notes. La première
fait partie de la gamme en cours (ton et mode), la seconde est altérée
d’un demi-ton et la troisième poursuit le mouvement d’un demi-ton dans
la même direction afin d’atteindre la note voisine de la gamme. Les
notes initiale et finale doivent donc être séparées d’un ton entier.

Exemple de mouvement chromatique ascendant en /do majeur/ :

#+BEGIN_CENTER
ré ré^{#} mi
#+END_CENTER

Exemple de mouvement chromatique descendant en /do majeur/ :

#+BEGIN_CENTER
la la^b sol
#+END_CENTER


* Portées

#+TOC: headlines 1 local


** Introduction

Une note de musique peut être représentée par un petit cercle dessiné
sur un ensemble de lignes horizontales parallèles appelé *portée*. Le
haut de la portée correspond aux notes les plus aiguës, et le bas aux
notes les plus graves. Les notes s’écrivent chronologiquement de
gauche à droite, en commençant par la portée en haut de la page, puis
la deuxième en partant du haut, etc. Il s’agit donc d’une convention
analogue à celle de l’écriture.


** Clefs

Une portée est généralement munie d’une *clef* permettant de repérer
une note de référence. Les autres notes de la portée s’en déduisent
alors aisément. Voici les différents types de clés utilisées :

  - une clé *d’ut* donne la position sur la portée du premier /do/ que
    l’on rencontre lorsqu’on descend du /la/ de référence, de
    fréquence 440 Hz

  - une clé de *sol* donne la position sur la portée du /sol/ situé
    une quinte plus haut que le /do/ de la clef d’ut

  - une clé de *fa* donne la position sur la portée du /fa/ situé une
    quinte plus bas que le /do/ de la clef d’ut

soit :

#+BEGIN_CENTER
si^b < fa < do < sol < la /de fréquence 440 Hz/
#+END_CENTER

En considérant des intervalles purs, on a :

  - le /do/ une sixte majeure plus bas que le /la/, de fréquence 440 x 3 / 5 = 264 Hz
  - le /sol/ une quinte plus haut que le /do/, de fréquence 264 x 3 / 2 = 396 Hz
  - le /fa/ une quinte plus bas que le /do/, de fréquence 264 x 2 / 3 = 176 Hz


*** Position de la clé

Suivant la position de la clé sur la portée, la hauteur des notes va
naturellement varier. Voici les principales clefs utilisées, ainsi que
leur position en partant du bas de la portée :

| Nom de la clef | Note de référence | Position   |
|----------------+-------------------+------------|
| Française      | Sol               | 1ère ligne |
| Aiguë          | Sol               | 2e ligne   |
| Soprano        | Do (Ut)           | 1ère ligne |
| Mezzosoprano   | Do                | 2e ligne   |
| Alto           | Do                | 3e ligne   |
| Ténor          | Do                | 4e ligne   |
| Baryton        | Fa                | 3e ligne   |
| Basse          | Fa                | 4e ligne   |
| Sous-basse     | Fa                | 5e ligne   |

La clef de /sol/ première ligne est celle qui permet de représenter
les notes les plus aiguës, tandis que la clef de /fa/ cinquième ligne
est celle qui permet de représenter les notes les plus graves.


** Système

Un système est un groupe de portées jouées simultanément par un ou
plusieurs instruments.


** Partition

Une partition est un ensemble de portées, ou de systèmes de portées,
contenant les notes et les indications grâce auxquelles les musiciens
vont pouvoir jouer une oeuvre musicale.


* Polyphonie

#+TOC: headlines 1 local


** Introduction

Une *polyphonie* est une superposition de plusieurs mélodies jouées
simultanément par différents instruments ou groupes d’instruments.
Chacune de ces mélodies est aussi appelée *voix*, *partie*, *ligne* ou
encore *ligne mélodique*.

/Remarque/ : attention à ne pas confondre la notion de voix, synonyme
de ligne mélodique, avec la voix humaine, qui peut être considérée
comme un instrument de musique. En tant que ligne mélodique, une voix
peut donc être interprétée par un instrument quelconque : violon, voix
humaine, flûte, guitare, etc.


** Horizontal & Vertical

La *mélodie* constitue la dimension *horizontale* d’une polyphonie, à
savoir les notes qui sont jouées consécutivement sur les voix.

L’ *harmonie* constitue la dimension *verticale* d’une polyphonie, à
savoir les groupes de notes qui sont jouées simultanément sur les
voix.

Dans une polyphonie, deux notes quelconques peuvent être jouées :

  - consécutivement (sur la même voix ou sur deux voix différentes)

  - simultanément (sur deux voix différentes)

  - avec simultanéité partielle :

    + les deux débutent au même moment, l’une s’arrête avant l’autre

    + les deux finissent au même moment, l’une débute avant l’autre

    + l’une débute avant et finit après l’autre


** Plages de notes

Un *registre* est une plage de notes.

Un *ambitus* est l’intervalle entre la note la plus aiguë et la note
la plus grave d’une mélodie.

Une *tessiture* est l’étendue de notes qu’un chanteur ou un instrument
est capable de jouer.


** Notation

Nous représentons une polyphonie par une *superposition* de voix. Il
s’agit en quelque sorte d’un *tableau* où chaque voix occupe une
ligne. Les voix sont disposées de la plus aiguë à la plus grave, de
haut en bas du tableau. Une voix située au-dessus d’une autre est donc
normalement plus aiguë. Précisons que chaque colonne du tableau
contient des notes jouées simultanément.

Voici un exemple :

#+ATTR_HTML: :class plat
| Va    | :     | a1    | a2    | a3    | a4    | =...= |
| Vb    | :     | b1    | b2    | b3    | b4    | =...= |
| Vc    | :     | c1    | c2    | c3    | c4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |

où :

  - Va, Vb, Vc, =...= sont les noms donnés à chacune des voix

  - a1, a2, a3, a4 ; b1, b2, b3, b4 ; c1, c2, c3, c4, =...= sont les notes jouées

Les notes a1, a2, a3, a4 sont donc jouées consécutivement tandis que
les notes a1, b1, c1 sont jouées simultanément.


*** Thèmes

On peut aussi représenter la musique comme une suite de thèmes
mélodiques, chacun étant constitué de plusieurs notes. Dans ce cas, on
symbolise chaque thème par une lettre majuscule et on représente la
polyphonie par :

#+ATTR_HTML: :class plat
| Va    | :     | A1    | A2    | A3    | A4    | =...= |
| Vb    | :     | B1    | B2    | B3    | B4    | =...= |
| Vc    | :     | C1    | C2    | C3    | C4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |

où :

  - Va, Vb, Vc, =...= sont les noms donnés à chacune des voix

  - A1, A2, A3, A4 ; B1, B2, B3, B4 ; C1, C2, C3, C4, =...= sont les
    noms donnés aux thèmes

Les thèmes A1, A2, A3, A4 sont donc joués consécutivement tandis que
les thèmes A1, B1, C1 sont joués simultanément.


*** Silences

Une voix momentanément silencieuse est représentée par un tiret, comme
la voix /V/ dans :

#+ATTR_HTML: :class plat
| V     | :     | A1    | —     | —     | A4    | =...= |
| W     | :     | B1    | B2    | B3    | B4    | =...= |
| =...= | =...= | =...= | =...= | =...= | =...= | =...= |


** Voix


*** Basse & Soprano

La voix la plus grave d’une polyphonie est nommée *basse*.

La voix la plus aiguë d’une polyphonie est nommée *soprano*.


*** Extrêmes & Internes

Le soprano et la basse sont les voix *extrêmes* d’une polyphonie.
Toutes les autres voix sont dites *internes*.


*** Importance

D’un point de vue harmonique, la *basse*, voix la plus grave, est la
plus importante d’une polyphonie. À l’extrême opposé, le *soprano*,
voix la plus aiguë, arrive en seconde. Les autres voix ont une
importance relative moins élevée. On a donc, par ordre décroissant
d’importance :

  - la basse (voix extrême inférieure)

  - le soprano (voix extrême supérieure)

  - les autres voix (voix internes)


*** Distinction

À un instant donné, les voix d’une polyphonie se distinguent en
général par :

  - le registre : une voix est plus aiguë ou plus grave qu’une l’autre

  - le rythme : une voix est plus rapide ou plus lente qu’une autre

  - le timbre : les voix sont jouées par des instruments de familles
    différentes, aux sons différenciables


*** Caractéristiques

Voici quelques caractéristiques propres à une polyphonie réussie :

  - *Cohérence* :

    + chaque voix fait entendre une mélodie cohérente

    + l’ensemble de la polyphonie doit être cohérent

  - *Clarté* : les voix superposées ne doivent pas surcharger
    l’oreille, on doit pouvoir entendre chacune d’entre-elles, ou du
    moins les plus importantes.

  - *Indépendance* : les voix sont indépendantes, elles alternent les
    phases de divergence et de convergence.

  - *Avant-plan* et *arrière-plan* : à tout instant, certaines voix
    sont mises en avant-plan et d’autres en arrière-plan. Le nombre de
    voix en avant-plan ne doit pas être trop élevé afin de ne pas
    surcharger l’oreille.

  - *Dialogue* : la succession des thèmes d’avant-plan mis bout à bout
    forme un ensemble cohérent qui se balade de voix en voix, donnant
    une impression de causerie où les voix se répondent.


*** Ajout et suppression

Le nombre de voix ne reste pas toujours constant tout le long d’une
pièce musicale. Une ou plusieurs voix peuvent être ajoutées ou
retirées. Dans le cas d’un ajout, on peut toujours considérer qu’une
voix préalablement silencieuse devient active. Dans le cas d’un
retrait, on peut considérer qu’une voix préalablement active devient
silencieuse.


**** Scission

La *scission* est un cas particulier d’ajout où la nouvelle voix
semble issue d’une ancienne comme une branche d’un arbre. Cet effet
est souvent obtenu en utilisant un mouvement pseudo-conjoint (à
l’octave près) entre les voix concernées. Exemple :

#+ATTR_HTML: :class plat
| S | : | do | ré |
| B | : | —  | si |

ou encore :

#+ATTR_HTML: :class plat
| S | : | —  | sol |
| B | : | fa | mi  |


**** Fusion

La *fusion* est un cas particulier de retrait, où l’ancienne voix
semble se fondre dans une autre avant de se taire. Cet effet est
souvent obtenu en utilisant un mouvement pseudo-conjoint entre les
voix concernées. Exemple :

#+ATTR_HTML: :class plat
| S | : | ré | do |
| B | : | si | —  |

ou encore :

#+ATTR_HTML: :class plat
| S | : | sol | —  |
| B | : | mi  | fa |


*** Groupes

Les voix d’une polyphonie peuvent être subdivisées en plusieurs
groupes. Les voix d’un même groupe possèdent généralement des
caractéristiques musicales communes, afin de les différencier des
autres voix. On parle alors de *groupe de voix*, de *plan sonore* ou
encore de *strate*.

Les groupes de voix ne sont pas figés :

  - chaque voix peut changer de groupe à tout moment

  - de nouveaux groupes peuvent être créés, d’anciens supprimés


**** Structure

Dans une structure stratifiée, chaque groupe de voix dispose de ses
propres motifs musicaux.

Dans une structure imitative, chaque groupe de voix reprend et varie
les thèmes des autres groupes.


** Ensembles


*** Duo

Un *duo* est une polyphonie à deux voix. Ces voix se nomment par
convention :

  - soprano
  - basse

de la plus aiguë à la plus grave. J’utilise comme abréviations : *S*
pour soprano et *B* pour basse, ce qui nous donne des tableaux de
cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| B | : | =...= |


*** Trio

Un *trio* est une polyphonie à trois voix. Ces voix se nomment par
convention :

  - soprano
  - alto
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le duo, avec en prime *A* pour l’alto, ce qui nous donne des
tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| B | : | =...= |


*** Quatuor

Un *quatuor* (aussi appelé *quartet*) est une polyphonie à quatre
voix. Ces voix se nomment par convention :

  - soprano
  - alto
  - ténor
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le trio, avec en prime *T* pour le ténor, ce qui nous donne des
tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| T | : | =...= |
| B | : | =...= |


*** Quintette

Un *quintette* (parfois orthographié *quintet*) est une polyphonie à
cinq voix. Ces voix se nomment par convention :

  - soprano
  - alto
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le quatuor, avec en prime *Y* pour le baryton, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| A | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |


*** Sextuor

Un *sextuor* (aussi appélé *sextet*, *sextette*) est une polyphonie à
six voix. Ces voix se nomment par convention :

  - soprano
  - mezzo-soprano
  - alto
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le quintettte, avec en prime *M* pour le mezzo-soprano, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| M | : | =...= |
| A | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |


*** Septuor

Un *septuor* (aussi appéles *septet*, *septette*) est une polyphonie à
sept voix. Ces voix se nomment par convention :

  - soprano
  - mezzo-soprano
  - alto
  - haute-contre
  - ténor
  - baryton
  - basse

de la plus aiguë à la plus grave. J’utilise les mêmes abréviations que
pour le sextuor, avec en prime *C* pour le haute-contre, ce qui nous
donne des tableaux de cette allure :

#+ATTR_HTML: :class plat
| S | : | =...= |
| M | : | =...= |
| A | : | =...= |
| C | : | =...= |
| T | : | =...= |
| Y | : | =...= |
| B | : | =...= |


/Remarque/ : la voix de haute-contre est aussi appelée, avec des
nuances, *contralto* ou *contreténor*.


*** Formation générique

Au-dessus de sept voix, on à la nomenclature :

  - Octuor, octet : 8 voix
  - Nonet, nonette : 9 voix
  - Dixtuor : 10 voix

On représente un ensemble contenant un nombre quelconque de voix par :

#+ATTR_HTML: :class plat
|     0 | : | =...= |
|     1 | : | =...= |
|     2 | : | =...= |
|     3 | : | =...= |
|     4 | : | =...= |
| =...= | : | =...= |
|   /M/ | : | =...= |

ou, si l’on souhaite faire ressortir les voix extrêmes :

#+ATTR_HTML: :class plat
|     S | : | =...= |
|     1 | : | =...= |
|     2 | : | =...= |
|     3 | : | =...= |
|     4 | : | =...= |
| =...= | : | =...= |
|   /N/ | : | =...= |
|     B | : | =...= |


* Accords

#+TOC: headlines 1 local


** Introduction

Un *accord* est un ensemble de notes qui sert pendant un certain
laps de temps de fondation au déroulement musical.

Cela ne signifie pas que toutes les notes jouées appartiennent à
l’accord, mais que la musique est élaborée à partir des notes qui le
constituent.

L’ajout de notes étrangères à l’accord se fait en général pour des
raisons de liaisons mélodiques entre les notes.


** Polyvalence

Les notes d’un accord peuvent être disposées suivant des
configurations très diverses. Il existe bien entendu des cas
extrêmes :

  - l’accord purement harmonique, où les notes sont jouées
    simultanément

  - l’accord purement mélodique, où les notes sont jouées les unes
    après les autres

mais la réalité est souvent plus complexe. La plupart du temps, la
musique explore les deux aspects, superposant et alignant les notes
d’un accord tout au long de son règne. Un accord est donc
une *entité abstraite* dont les *réalisations* constituent
le plus souvent un *hybride* d’harmonie et de mélodie.


*** Jargon

Les notes d’un accord mélodique ne sont en général pas jouées
consécutivement, d’autres notes pouvant être intercalées afin
d’affiner les lignes mélodiques. Lorsque les notes d’un accord
mélodique sont jouées consécutivement, on parle alors d’ *arpège*.

Lorsque les notes d’un accord sont jouées simultanément et sans ajout
de notes étrangères, on parle d’ *accord frappé* ou encore d’ *accord
plaqué*.

Enfin, on parle d’ *accumulation* lorsque les notes de l’accord sont
entamées consécutivement mais que chacune d’elle est maintenue jusqu’à
la fin de l’accord. Par exemple, avec l’accord /do mi sol/, on
commence par jouer le /do/, ensuite le /mi/ vient s’ajouter et on
entend simultanément les notes /do mi/, et finalement le /sol/ vient
s’ajouter et on entend simultanément les notes /do mi sol/.


** Octave

C’est avant tout l’ordre des notes, de la plus grave à la plus aiguë,
qui importe en théorie des accords. Leur octave précise n’est pas
prise en compte. Les notes et intervalles doivent donc s’entendre à
l’octave près.

Ce constat nous permet d’employer une notation allégée. Par
convention, nous représentons un accord par une suite de notes
croissantes en hauteur, ce qui nous permet d’omettre leurs octaves.
Ainsi, dans l’accord :

#+BEGIN_CENTER
sol si sol
#+END_CENTER

le second /sol/ doit être plus aigu que le /si/, lui-même strictement
plus aigu que le premier /sol/. Cette notation est donc équivalente
à :

#+BEGIN_CENTER
SOL SI sol
#+END_CENTER

ou plus généralement à :

#+BEGIN_CENTER
sol^M si^N sol^P
#+END_CENTER

où les octaves /M/, /N/, /P/ sont des entiers respectant la
contrainte :

#+BEGIN_CENTER
M ≤ N < P
#+END_CENTER


** État canonique

Un accord est défini par une suite de notes disposées dans un ordre de
référence appelé *état canonique*. La note la plus grave de l’état
canonique est appelée *fondamentale*. L’état canonique permet
également de nommer les notes de l’accord d’après l’intervalle qui les
sépare de la fondamentale.

Par exemple, dans l’accord défini par l’état canonique :

#+BEGIN_CENTER
do   mi   sol   si   ré   fa   la
#+END_CENTER

les notes reçoivent des noms repris dans le tableau ci-dessous :

| Notes | Noms         | Abréviations |
|-------+--------------+--------------|
| do    | fondamentale |         1ale |
| mi    | tierce       |          3ce |
| sol   | quinte       |          5te |
| si    | septième     |           7e |
| ré    | neuvième     |           9e |
| fa    | onzième      |          11e |
| la    | treizième    |          13e |

/Remarque/ : ne pas confondre le concept de /note/ fondamentale d’un
accord avec celui de /fréquence/ fondamentale d’un son.


** Degré

Le *degré* d’un accord est simplement le degré de sa fondamentale.

Par exemple :

  - un accord de degré 1, ou accord de tonique, est un accord dont la
    fondamentale est le degré 1 de la gamme

  - un accord de degré 5, ou accord de dominante, est un accord dont
    la fondamentale est le degré 5 de la gamme


** Empilement

L’état canonique de la plupart des accords est construit en empilant
des notes séparées par un intervalle constant donné. Cet intervalle
est généralement un des premiers que l’on rencontre dans la suite des
harmoniques naturelles, à savoir les tierces et les quintes.


*** Tierces

Les accords construits par empilement de tierces sont de loin les plus
fréquents, parce qu’ils sont intimement liés aux harmoniques
naturelles et sonnent donc particulièrement bien. Notons qu’un
accord à base de tierces peut aussi bien contenir des tierces
majeures que mineures. Exemples d’accords à base de tierces :

#+ATTR_HTML: :class plat
| ré | fa | la |    |    |     |    |
| ré | fa | la | do |    |     |    |
| ré | fa | la | do | mi |     |    |
| ré | fa | la | do | mi | sol |    |
| ré | fa | la | do | mi | sol | si |


*** Quintes

Les accords construits par empilement de quintes sont considérés comme
des altérations d’accords à base de tierces. On les utilise pour
donner une coloration alternative à la musique, ou encore pour
soutenir une mélodie issue d’un mode tétraphonique ou pentaphonique
(comme on en rencontre en blues et en jazz). Exemples d’accords à base
de quintes :

#+ATTR_HTML: :class plat
| fa | do | sol |    |    |    |    |
| fa | do | sol | ré |    |    |    |
| fa | do | sol | ré | la |    |    |
| fa | do | sol | ré | la | mi |    |
| fa | do | sol | ré | la | mi | si |

/Remarque/ : la théorie classique ne reconnaît que les accords
construits par empilement de tierces.


** Disposition

On nomme *disposition* d’un accord un agencement particulier de ses
notes intrinsèques. De nombreux événements peuvent modifier la
disposition : permutation, renversement, doublure, suppression, etc.


*** Permutations

On peut permuter l’ordre des notes d’un accord. Exemples :

#+ATTR_HTML: :class plat
| do mi sol | ⟼ | do sol mi |
| sol do fa | ⟼ | do fa sol |


*** Basse

La note la plus grave d’une permutation quelconque d’un accord est
appelée la *basse* de l’accord ainsi disposé. On dit aussi de cette
note qu’elle est mise *à la basse*.

Dans cet exemple, le /sol/ est à la basse :

#+BEGIN_CENTER
sol do mi
#+END_CENTER

Dans cet exemple, le /do/ est à la basse :

#+BEGIN_CENTER
do sol mi
#+END_CENTER


*** État fondamental et renversements

Lorsque les notes d’un accord sont permutées, il arrive que la note
mise à la basse ne soit pas la fondamentale. On dit alors que l’accord
est *renversé*.

Si c’est la deuxième note la plus grave de l’état canonique qui est à
la basse, on dit que l’accord est dans un premier *renversement*, ou
qu’il est *renversé* une fois.

Si c’est la troisième note la plus grave de l’état canonique qui est à
la basse, on dit que l’accord est dans un second renversement, ou
qu’il est renversé deux fois ; etc.

Qu’il soit permuté ou non, on dit qu’un accord est dans son *état
fondamental* lorsque la fondamentale est à la basse.

Exemple :

  - État fondamental :
    + État canonique : do mi sol
    + Permutation sans renversement : do sol mi
  - Renversements :
    + Premier renversement :
      * mi sol do
      * mi do sol
    + Second renversement :
      * sol do mi
      * sol mi do


*** Doublure

Une *doublure* est une note ajoutée à l’accord, identique à l’octave
près à une des notes de l’état canonique. La note originale est alors
dite *doublée* ou *redoublée*. Une doublure peut donc se faire :

  - une ou plusieurs octaves au-dessus de la note originale
  - à l’unisson de la note originale
  - une ou plusieurs octaves en-dessous de la note originale

Par exemple, si on redouble le /mi/ de l’accord /la do mi/, on
obtient :

#+BEGIN_CENTER
la mi do mi
#+END_CENTER

ou une quelconque permutation de cet accord. La note redoublée
correspond souvent, mais pas nécessairement, à une note importante que
l’on souhaite souligner, à la fondamentale ou à la basse de l’accord.

Quelques précisions :

  - L’ajout d’une doublure ne modifie pas l’état canonique de
    l’accord. Le nombre de notes intrinsèques reste donc inchangé.

  - Une même note peut être doublée plusieurs fois, à des octaves
    différentes ou identiques.


*** Suppression

On peut modifier un accord en supprimant une de ses notes.


**** Fondamentale

Pour éviter toute ambiguité, le nombre de renversements est toujours
évalué par rapport à l’ordre des notes dans l’état canonique de
l’accord /au complet/. Donc, si la fondamentale de :

#+BEGIN_CENTER
do mi sol si
#+END_CENTER

est supprimée, la disposition suivante :

#+BEGIN_CENTER
mi sol si
#+END_CENTER

est assimilée à un premier renversement, puisque c’est le /mi/,
deuxième note de l’état canonique, qui est à la basse. La disposition
suivante :

#+BEGIN_CENTER
sol si mi
#+END_CENTER

sera dans un deuxième renversement et celle-ci  :

#+BEGIN_CENTER
si mi sol
#+END_CENTER

dans un troisième.

Une conséquence importante de cette convention est qu’un accord privé
de sa fondamentale est toujours renversé.


*** Ajouts


**** Pédale

Une pédale est une note (ou un accord) qui reste constant sur une même
voix (ou groupe de voix) alors que plusieurs accords différents se
succèdent sur les autres voix.

Une pédale est placée le plus souvent à la basse ou à la voix la plus
aiguë (soprano), parfois aux voix intermédiaires

Lorsqu’une pédale est plaçée à la basse, c’est la voix directement
supérieure (le ténor dans un quatuor) qui accueille temporairement les
notes de basse des accords.


**** Fusion

Il est tout à fait possible de fusionner deux ou plusieurs accords
afin d’en construire un nouveau.


** Intervalle interne

Un *intervalle interne* d’un accord est un intervalle qui sépare deux
de ses notes.

Les intervalles internes les plus importants sont ceux qui séparent :

  - une note de l’accord avec la fondamentale
  - une note de l’accord avec la basse


** Harmoniques naturelles

On peut générer une suite de notes dont les fréquences respectent au
moins approximativement les ratios des harmoniques naturelles :

#+ATTR_HTML: :class plat
| 2 / 1 | — | 3 / 2 | — | 4 / 3 | — | 5 / 4 | — | 6 / 5 | — | 7 / 6 | — | 8 / 7 | — | 9 / 8 | — | =...= |

En partant d’un /do/, nous obtenons :

#+ATTR_HTML: :class plat
| do | do | sol | do | mi | sol | si^b  | do | ré | =...= |

On peut voir cette suite comme un accord placé dans une disposition
particulière : multiples doublures de la fondamentale /do/, doublure
de la quinte /sol/, intervalles larges dans les graves et plus
resserrés dans l’aigu, etc. Une disposition analogue aura donc de
bonnes chances d’asseoir confortablement un accord. On remarque aussi,
qu’abstraction faite des doublures, on obtient la suite de notes :

#+BEGIN_CENTER
do mi sol si^b ré
#+END_CENTER

La suite des harmoniques naturelles semble donc nous diriger vers des
accords construits par empilement de tierces majeures ou mineures.
Ceci explique la prédominance des accords à base de tierces.


** Nombre de notes

On nomme :

  - *dyade* un accord constitué de deux notes
  - *triade* un accord constitué de trois notes
  - *tétrade* un accord constitué de quatre notes
  - *pentade* un accord constitué de cinq notes

/Remarque/ : on parle ici du nombre de notes intrinsèques de l’accord,
sans tenir compte des éventuelles doublures, suppressions ou ajouts.

Le tableau suivant nous donne les abréviations de ces termes :

| Nom     | Abréviation |
|---------+-------------|
| Dyade   | 2ade        |
| Triade  | 3ade        |
| Tétrade | 4ade        |
| Pentade | 5ade        |


*** Accord et intervalle

On peut voir un accord comme un empilement d’intervalles.
Réciproquement, on peut voir un intervalle comme un accord constitué
de deux notes, c’est-à-dire une dyade.


* Pyramide rythmique

#+TOC: headlines 1 local


** Introduction

Une oeuvre musicale se base sur différentes *unités rythmiques*
fondamentales. La structure pyramidale qui en résulte provient des
principes complémentaires suivants :

  - plusieurs unités peuvent s’assembler pour constituer une unité plus longue
  - chaque unité rythmique est décomposable en unités plus courtes

Voici les unités les plus courantes, en commençant par les plus
courtes :

  - le *temps*
  - la *mesure*, qui regroupe plusieurs temps
  - la *carrure*, qui regroupe plusieurs mesures


** Structure interne

On dispose de qualificatifs permettant de préciser en combien de
sous-unités se décompose une unité rythmique donnée. Ainsi :

  - une unité rythmique *binaire* se décompose en *deux* sous-unités
  - une unité rythmique *ternaire* se décompose en *trois* sous-unités
  - une unité rythmique *quaternaire* se décompose en *quatre* sous-unités

Exemples :

  - une carrure quaternaire se compose de quatre mesures
  - une mesure ternaire se compose de trois temps


** Régularité

Une unité rythmique est dite *régulière* lorsqu’elle se décompose en
sous-unités de durées et structures identiques.

Une unité rythmique est dite *irrégulière* lorsqu’elle se décompose en
sous-unités de durées et structures différentes.


** Mesure

Les mesures se classent en deux catégories :

  - Les *mesures simples*
    + Une mesure simple est constituée d’un seul groupe de /N/ temps
    + Les plus courantes
      * Mesure simple à 2 temps
      * Mesure simple à 3 temps
      * Mesure simple à 4 temps
  - Les *mesures composées*
    + Une mesure composée est constituée de /M/ groupes de /N/ temps
    + Les plus courantes
      * 4 temps structurés en 2 groupes de 2 temps
      * 6 temps structurés en 2 groupes de 3 temps
      * 9 temps structurés en 3 groupes de 3 temps
      * 12 temps structurés en 4 groupes de 3 temps

Par exemple :

  - Le galop, la habanera et la polka sont basés sur une mesure simple
    à 2 temps

  - La valse, la chaconne et la sarabande sont basés sur une mesure
    simple à 3 temps

  - Le fameux "Take Five" de Dave Brubeck est basé sur une mesure
    simple à 5 temps

  - La sicilienne et la tarentelle sont basées sur une mesure composée
    à 6 temps


** Carrure

La *carrure* peut regrouper 2, 3, 4 mesures ou plus. La
*carrure royale* compte 8 mesures. Chaque carrure sert de support au
développement d’un mini-thème musical.


* Pulsations & Oscillations

#+TOC: headlines 1 local


** Pulsation

En plus de la structure écrite sur la partition, on dispose de la
notion de *pulsation*, battement fondamental que l’on ressent en
écoutant la musique. Une pulsation dure approximativement une seconde,
un peu plus dans les rythmes lents, et un peu moins dans les rythmes
rapides.


*** Mesures simples

La pulsation correspond en général à la durée d’une mesure simple, et
se décompose alors en 2, 3, 4 ou /N/ temps.


*** Mesures composées

Dans le cas d’une mesure composée, la pulsation correspond à la durée
d’un groupe de temps. Il y a donc :

  - 2 pulsations de 2 temps dans une mesure composée à 4 temps
  - 2 pulsations de 3 temps dans une mesure composée à 6 temps
  - 3 pulsations de 3 temps dans une mesure composée à 9 temps
  - 4 pulsations de 3 temps dans une mesure composée à 12 temps


*** Tactus

On utilisait autrefois un concept proche de la pulsation : le
*tactus*, unité de temps proche de la seconde à laquelle toutes les
durées se rapportaient. Tout comme pour la pulsation, des variantes de
tactus plus ou moins rapides existaient.


** Oscillation

L’effet de balancement produit par le regroupement de 2 pulsations ou
plus est appelé *oscillation*. On a donc :

  - la pulsation, dont la durée est approximativement égale à la
    seconde

  - l’oscillation, qui regroupe plusieurs pulsations

/Remarque/ : l’oscillation de 2 pulsations est de loin la plus fréquente.


*** Disposition sur les mesures

Une oscillation de 2 pulsations peut être formée de :

  - 2 mesures simples à 2, 3, 4 ou /N/ temps

  - 1 mesure composée de 6 temps, soit 2 groupes de 3 temps

Une oscillation de 3 pulsations peut être formée de :

  - 3 mesures simples à 2, 3, 4 ou /N/ temps

  - 1 mesure composée de 9 temps, soit 9 groupes de 3 temps

Une oscillation de 4 pulsations peut être formée de :

  - 4 mesures simples à 2, 3, 4 ou /N/ temps

  - 1 mesure composée de 12 temps, soit 4 groupes de 3 temps

En général, une oscillation de /M/ pulsations peut être formée de :

  - /M/ mesures simples à 2, 3, 4 ou /N/ temps

  - 1 mesure composée de /M × N/ temps, soit /M/ groupes de /N/ temps


** Notation

Nous utilisons les notations suivantes :

| Notation | Temps                                    |
|----------+------------------------------------------|
| §        | Premier temps de l’oscillation           |
| ¶        | Premier temps d’une pulsation, excepté § |
| χ        | Autres temps                             |

Voici quelques exemples de cette notation :

#+ATTR_HTML: :class plat
| Oscillation de 2 pulsations binaires  | : | § | χ | ¶ | χ |   |   |   |   |   |   |   |   |
| Oscillation de 3 pulsations binaires  | : | § | χ | ¶ | χ | ¶ | χ |   |   |   |   |   |   |
| Oscillation de 4 pulsations binaires  | : | § | χ | ¶ | χ | ¶ | χ | ¶ | χ |   |   |   |   |
| Oscillation de 2 pulsations ternaires | : | § | χ | χ | ¶ | χ | χ |   |   |   |   |   |   |
| Oscillation de 3 pulsations ternaires | : | § | χ | χ | ¶ | χ | χ | ¶ | χ | χ |   |   |   |
| Oscillation de 4 pulsations ternaires | : | § | χ | χ | ¶ | χ | χ | ¶ | χ | χ | ¶ | χ | χ |


* Mesures

#+TOC: headlines 1 local


** Mesure régulière

Une mesure *régulière* est une mesure composée de groupes
de temps de durées et structures identiques. Considérons
par exemple une mesure comptant en tout 6 temps. Elle peut
s’organiser en 2 groupes de 3 temps ou en 3 groupes de 2 temps :

#+ATTR_HTML: :class plat
| /Deux groupes ternaires/ | : | 3 + 3     |
| /Trois groupes binaires/ | : | 2 + 2 + 2 |

De même, une mesure de 12 temps peut se structurer en 4
temps ternaires ou en 3 temps quaternaires :

#+ATTR_HTML: :class plat
| /Quatre groupes ternaires/   | : | 3 + 3 + 3 + 3 |
| /Trois groupes quaternaires/ | : | 4 + 4 + 4     |


*** Généralisation

Si l’on souhaite une mesure composée de /M/ groupes de /N/ temps il
suffit de choisir une mesure de /M × N/ temps.


** Mesure irrégulière

Une mesure *irrégulière* est une mesure composée constituée de groupes
de temps de natures différentes. Voici quelques exemples de
décompositions irrégulières :

| Nombre de temps | Décomposition     |
|-----------------+-------------------|
|               5 | 2 + 3             |
|               7 | 3 + 4             |
|               7 | 2 + 3 + 2         |
|               7 | 3 + 2 + 2         |
|               8 | 3 + 2 + 3         |
|               9 | 3 + 2 + 4         |
|              10 | 4 + 3 + 3         |
|              11 | 4 + 4 + 3         |
|              12 | 3 + 4 + 2 + 3     |
|                 | 2 + 3 + 3 + 2 + 2 |

On retrouve des décompositions analogues dans [[file:litera-01-rimailleur.org::#section:coupesEtCesures][les coupes et césures poétiques]].


*** Pulsation

Les mesures irrégulières peuvent servir de support :

  - à une pulsation variable, qui correspond à la durée d’un groupe de
    temps de la mesure

  - à une pulsation constante, qui correspond à la durée d’une mesure

Considérons par exemple une mesure irrégulière de structure 2 + 3.

Une oscillation constitutée de deux pulsations variables sera alors
construite sur une mesure, comme suit :

#+ATTR_HTML: :class plat
| § | χ | ¶ | χ | χ |

tandis qu’une oscillation constitutée de deux pulsations constantes
sera alors construite sur deux mesures, comme suit :

#+ATTR_HTML: :class plat
| § | χ | χ | χ | χ | ¶ | χ | χ | χ | χ |

Voici quelques exemples de pulsations variables :

#+ATTR_HTML: :class plat
| 2 + 3     | : | § | χ | ¶ | χ | χ |   |   |   |   |
| 3 + 4     | : | § | χ | χ | ¶ | χ | χ | χ |   |   |
| 2 + 3 + 2 | : | § | χ | ¶ | χ | χ | ¶ | χ |   |   |
| 3 + 2 + 4 | : | § | χ | χ | ¶ | χ | ¶ | χ | χ | χ |

Voici quelques exemples de pulsations constantes :

#+ATTR_HTML: :class plat
| 2 + 3     | : | § | χ | χ | χ | χ | ¶ | χ | χ | χ | χ |   |   |   |   |
| 3 + 4     | : | § | χ | χ | χ | χ | χ | χ | ¶ | χ | χ | χ | χ | χ | χ |
| 2 + 3 + 2 | : | § | χ | χ | χ | χ | χ | χ | ¶ | χ | χ | χ | χ | χ | χ |


** Transition

Il est possible de réaliser des transitions naturelles entre mesures
composées de groupes binaires, ternaires et quaternaires :

  - Une mesure composée de 2 groupes de 3 temps peut être réorganisée
    en 3 groupes de 2 temps. Chaque groupe correspondant à une
    pulsation, on passe alors de 2 pulsations ternaires à 3 pulsations
    binaires

  - Une mesure composée de 4 groupes de 3 temps peut être réorganisée
    en 3 groupes de 4 temps. Chaque groupe correspondant à une
    pulsation, on passe alors de 4 pulsations ternaires à 3 pulsations
    quaternaires

En utilisant le même procédé, on peut réorganiser les pulsations dans
un groupe de mesures :

  - 2 mesures de 3 temps comptent en général une pulsation par mesure,
    c’est-à-dire une pulsation tout les 3 temps. On peut réorganiser
    le tout en plaçant une pulsation tous les 2 temps. On passe alors
    de 2 pulsations ternaires à 3 pulsations binaires.

  - 4 mesures de 3 temps comptent en général une pulsation par mesure.
    On peut réorganiser le tout en plaçant une pulsation tous les 4
    temps. On passe alors de 4 pulsations ternaires à 3 pulsations
    quaternaires.


** Temps forts et faibles

Tous les temps ne sont pas d’égale importance, il arrive que certains
soient plus accentués que d’autres. Lorsque c’est le cas, les temps
les plus accentués sont appelés *temps forts*, et les autres *temps
faibles*. On rencontre aussi des *temps médians*, dont l’accentuation
est intermédiaire entre celles des temps forts et faibles. Nous avons
donc finalement trois niveaux d’accentuation :

  - temps fort
  - temps médian
  - temps faible

Nous utilisons les abréviations suivantes :

| F | Temps fort   |
| M | Temps médian |
| f | Temps faible |

Le cas le plus fréquent est celui où temps forts et faibles sont
alternés. Les temps médians étant généralement assimilés à des temps
forts en ce qui concerne l’alternance, nous avons les structures de
base suivantes pour les mesures régulières :

| 2 temps | F f     |
| 3 temps | F f M   |
| 4 temps | F f M f |

Ces structures peuvent évidemment varier suivant les circonstances :
mesures irrégulières, etc.


*** Parties fortes et faibles

À cette hiérarchie des temps forts et faibles, vient s’ajouter celle
des parties fortes et faibles d’un temps. La *partie forte* d’un temps
correspond simplement au début du temps, et la *partie faible* à tout
le reste.


** Anacrouse

Lorsque la première mesure d’un morceau est incomplète, on la nomme
*anacrouse*. Cette première mesure est alors constituée de notes
précédent le premier temps fort de la musique, ce qui provoque un
décalage entre la mélodie et la structure rythmique.

Notons que l’anacrouse n’est pas obligatoire : un thème mélodique peut
démarrer au début d’une mesure.


* Carrures

#+TOC: headlines 1 local


** Oscillations

Le plus souvent, les carrures sont organisées de telle sorte qu’elles
respectent la structure des oscillations.


** Multi-niveaux

Il n’est pas rare qu’une carrure puisse être analysée sur plusieurs
échelles rythmiques. Par exemple, dans la carrure royale :

  - le groupe de 8 mesures peut se décomposer en 2 demi-carrures
    comptant chacune 4 mesures ou oscillations

  - chaque groupe de 4 mesures peut se subdiviser en 2 groupes de 2 mesures

  - le groupe de 8 mesures peut donc se décomposer en 4 quart de
    carrures comptant chacune 2 mesures ou oscillations


* Cellules rythmiques

#+TOC: headlines 1 local


** Introduction

Une *cellule rythmique* est un rythme basique occupant l’entièreté
d’une pulsation, soit :

  - une mesure simple
  - un groupe de temps dans une mesure composée


*** Décomposition et liaison

Une cellule rythmique quelconque peut être obtenue en décomposant la
durée de la pulsation en plusieurs unités, puis en liant entre-elles
certaines de ces unités. Par exemple, dans le cas où la pulsation est
décomposable en une série de 6 croches, nous pouvons modifier cette
série en :

#+BEGIN_CENTER
C‿C‿C C C‿C
#+END_CENTER

On obtient alors le rythme :

#+BEGIN_CENTER
Np C N
#+END_CENTER

Les rythmes les plus courants sont :

  - les rythmes binaires, obtenus en décomposant une pulsation binaire
    en 2, en 4, ou en 8

  - les rythmes ternaires, obtenus en décomposant une pulsation
    ternaire en 3, en 6, ou en 12.


*** Adaptation des durées

Il est possible d’adapter une cellule rythmique prévue pour une durée
/D/ afin qu’elle occupe une durée /M × D/. Il suffit pour cela
de multiplier la durée de chaque note par /M/.

Il est possible d’adapter une cellule rythmique prévue pour une durée
/D/ afin qu’elle occupe une durée /D / M/.  Il suffit
pour cela de diviser la durée de chaque note par /M/.


**** Triolet et duolet

Le triolet multiplie la durée par 2 / 3 et permet donc de placer un
rythme ternaire dans une pulsation binaire.

Le duolet multiplie la durée par 3 / 2 et permet donc de placer un
rythme binaire dans une pulsation ternaire.


**** Pointée : 3 / 2 ou 4 / 3

Le rapport :

#+BEGIN_CENTER
durée d’une blanche pointée / durée d’une blanche
#+END_CENTER

est de 3 / 2. Lors des variations de structure rythmique au sein d’un
même morceau, il est parfois souhaitable de disposer d’un rapport plus
proche de 1, comme le rapport :

#+BEGIN_CENTER
durée d’une noire pointée / durée d’une blanche
#+END_CENTER

qui nous donne 3 / 4. On divise alors par deux la durée de chaque
cellule rythmique occupant une blanche pointée afin qu’elle n’occupe
plus qu’une noire pointée. Ce procédé nous donne par exemple :

#+ATTR_HTML: :class plat
| Bp    | ⟼ | Np    |
| Ν N N | ⟼ | C C C |
| B N   | ⟼ | N C   |


*** Silences


**** Remplacement par un silence

On peut très bien remplacer une ou plusieurs notes d’une cellule
rythmique par des silences de mêmes durées. Par exemple, si on
escamote la première note de :

#+BEGIN_CENTER
N C N C
#+END_CENTER

on obtient :

#+BEGIN_CENTER
ns C N C
#+END_CENTER


**** Sécheresse & Fluidité

Les cellules rythmiques construites par décomposition et liaison
donnent des rythmes *fluides*, c’est-à-dire ne comprenant pas de
silences. On peut toutefois raccourcir les notes et intercaler des
silences afin de produire ce qu’on appelle un rythme *sec*. Par
exemple, on peut écourter les notes de :

#+BEGIN_CENTER
Np C N
#+END_CENTER

obtenant le rythme sec :

#+BEGIN_CENTER
C ns dC dcs C cs
#+END_CENTER


*** Combinaisons

Le rythme d’une oscillation peut être construit en combinant plusieurs
cellules rythmiques, à raison d’une cellule par pulsation.

Les cellules rythmiques binaires s’appliquent aux pulsations
binaires, tandis que les cellules rythmiques ternaires s’appliquent
aux pulsations ternaires.


** Classification

Les cellules rythmiques sont caractérisées par le nombre de notes
présentes après décomposition et liaison. Parmi celles-ci, on
distingue les notes « longues » des notes « brèves ». Il s’agit d’une
distinction approximative, deux notes classées dans la même catégorie
(longue ou brève) n’ayant pas forcément une durée exactement
identique. Il arrive que cette distinction n’ait pas lieu d’être,
toutes les notes ayant une durée identique. On parle alors de notes
« égales ». Nous utilisons les notations :

# symboles :
#
# &mdash; = —
# &union; = ∪
# &perp;= ⊥

| — | Note longue |
| ∪ | Note brève  |
| ⊥ | Note égale  |

Dans la suite, nous considérons une pulsation binaire de durée égale à
une blanche et une pulsation ternaire de durée égale à une blanche
pointée.

/Remarque/ : cette notion de contraste entre longues et brèves n’est
pas sans rappeler les syllabes lourdes et légères de la [[file:litera-01-rimailleur.org::#section:metriqueQuantitative][métrique
quantitative]] en poésie. Toutefois, la palette des durées musicales est
nettement plus nuancée que cette simple dualité, et permet donc des
possibilités beaucoup plus nombreuses, ainsi que nous allons le voir.


**** Une note

Le cas des celulles rythmiques ne contenant qu’une note est simple,
celle-ci doit occuper tout l’espace disponible dans la pulsation :

| Pulsation binaire | Pulsation ternaire |
|-------------------+--------------------|
| B                 | Bp                 |


**** Deux notes

Les structures les plus courantes sur deux notes sont :

| Notes égales      | ⊥ ⊥ |
| Longue puis brève | — ∪ |
| Brève puis longue | ∪ — |

ce qui nous donne par exemple :

| Structure | Pulsation binaire | Pulsation ternaire |
|-----------+-------------------+----------------|
| ⊥ ⊥       | Ν N               | Np Np          |
| — ∪       | Np C              | B N            |
|           | Npp dC            | B‿C C          |
|           | N‿dC Cp           | Np‿dC N‿dC     |
| ∪ —       | C Np              | N B            |


**** Trois notes

Les structures les plus courantes sur trois notes sont :

| Note égales         | ⊥ ⊥ ⊥ |
| 1 longue 2 brèves   | — ∪ ∪ |
| Brève longue brève  | ∪ — ∪ |
| 2 brèves 1 longue   | ∪ ∪ — |
| 1 brève 2 longues   | ∪ — — |
| Longue brève longue | — ∪ — |
| 2 longues 1 brève   | — — ∪ |

ce qui nous donne par exemple :

| Structure | Pulsation binaire | Pulsation ternaire |
|-----------+-------------------+--------------------|
| ⊥ ⊥ ⊥     | Cp C Cp           | Ν N N              |
| — ∪ ∪     | N C C             | B C C              |
| ∪ — ∪     | C N C             | C B C              |
|           | Cp N dC           | N Np C             |
| ∪ ∪ —     | C C N             | C C B              |
| ∪ — —     | dC Cp N           | C N Np             |
| — ∪ —     | N dC Cp           | Np C N             |
|           | Cp dC N           | N C Np             |
| — — ∪     | N Cp dC           | Np N C             |


**** Autres rythmes réguliers

Les autres rythmes approximativement réguliers les plus courants
sont :

| Nombre de notes | Structure   | Pulsation binaire | Pulsation ternaire |
|-----------------+-------------+-------------------+--------------------|
|               4 | ⊥ ⊥ ⊥ ⊥     | C C C C           | Cp Cp Cp Cp        |
|               6 | ⊥ ⊥ ⊥ ⊥ ⊥ ⊥ | C dC dC dC dC C   | C C C C C C        |


* Syncopes

#+TOC: headlines 1 local


** Introduction

Une *syncope* est une note entamée à l’intérieur d’une pulsation et
qui se prolonge au début de la pulsation suivante. On peut construire
une syncope en disposant deux cellules rythmiques sur deux pulsations
consécutives et en liant la dernière note de la première pulsation à
la première note de la seconde. Pour que la structure obtenue soit une
syncope, il faut que la première cellule rythmique compte au moins
deux notes. Voici quelques exemples où le temps dure une noire :

#+ATTR_HTML: :class plat
| Pulsation binaire (N N)    | : | N N‿N N     | ⟼ | N Β N     |
| Pulsation ternaire (Ν N N) | : | N N N‿N N N | ⟼ | Ν N B Ν N |

Le tableau suivant reprend quelques syncopes courantes basées sur des
pulsations de 2 ou 3 noires :

| Pulsation        | Liaison                 | Résultat              |
|------------------+-------------------------+-----------------------|
| Binaire : N N    | N N‿N N                 | N B N                 |
|                  | Np C‿Np C               | Np Β C                |
|                  | Np C‿N N                | Np Np N               |
|                  | N N‿C C C C             | N Np C C C            |
|                  | C C C C‿C C C C         | C C C N C C C         |
| Ternaire : N N N | B N‿B N                 | B Bp N                |
|                  | B N‿N N N               | B B Ν N               |
|                  | N N N‿N N N             | N N B N N             |
|                  | C C C C C C‿C C C C C C | C C C C C N C C C C C |
|                  | N N N‿C C C C C C       | N N Np C C C C C      |

Dans la suite, nous considérons une pulsation binaire de structure
/N N/ et une pulsation ternaire de structure /N N N/.


*** Prolongation

Il est possible de prolonger une syncope d’une ou de plusieurs
pulsations. Exemple sur une pulsation binaire :

#+ATTR_HTML: :class plat
| N N‿N N | ⟼ | N N‿B‿N N | = | N R N |


*** Syncopé

Dans le cas où plusieurs syncopes consécutives sont réalisées, on
parle de rythme syncopé. Exemple sur une pulsation binaire de
structure N N :

#+ATTR_HTML: :class plat
| N N‿N N‿N N | ⟼ | N B B N |


*** Syncope masquée

La syncope masquée est une note jouée juste avant le début de la
pulsation suivante, et qui se prolonge du début de celle-ci. Il faut
être très attentif à la mélodie pour se rendre compte du décalage, une
audition ordinaire produira juste une légère impression de balancement
supplémentaire au rythme régulier.


** Contretemps

Les contretemps sont similaires aux syncopes, mais au lieu de
prolonger la note, on place un silence sur le début de la pulsations
suivante. Voici quelques exemples de syncopes et de contretemps aux
structures équivalentes :

| Pulsation        | Syncope      | Contretemps  |
|------------------+--------------+--------------|
| Binaire : N N    | N N‿N N      | N N ns N     |
|                  | Np C‿Np C    | Np C nps C   |
| Ternaire : N N N | N N N, N N N | N N N ns N N |
|                  | B N‿B N      | B N bs N     |


** Implicite ou déplacement

Il existe deux méthodes permettant de relier syncope et mélodie :

  - Lorsque la syncope ou le contretemps est réalisé en supprimant une ou
    plusieurs notes par rapport à un thème de référence préalablement
    entendu ou simplement sous-entendu, on parle de *motif implicite*.

  - Par contre, si la syncope ou le contretemps est réalisé en
    déplaçant la suite du thème, on parle de *déplacement*.

Pour illustrer ces deux philosophies, partons du thème :

#+BEGIN_CENTER
do ré mi si la sol
#+END_CENTER

Un exemple de motif implicite sera alors :

#+BEGIN_CENTER
do ré mi—— la sol
#+END_CENTER

où le /mi——/ est soit prolongé, soit suivi par un silence, ce qui rend
le /si/ implicite. Le même exemple avec déplacement nous donne :

#+BEGIN_CENTER
do ré mi—— si la sol
#+END_CENTER

où la prolongation du /mi——/ reporte le dernier groupe de notes
/si la sol/. Notons qu'il est aussi possible de produire une syncope
en raccourcissant le /mi/. Un déplacement peut donc se produire par
*report* ou *anticipation*.


* Cellules composites

#+TOC: headlines 1 local


** Introduction

Considérons une combinaison de deux cellules rythmiques occupant
chacune une pulsation. Si nous divisons par deux la durée de chaque
note, la durée totale de la combinaison sera également divisée par
deux et n’occupera plus qu’une seule pulsation. Le résultat est une
nouvelle cellule rythmique composée de deux sous-cellules rythmiques
simples. Une telle construction est appelée *cellule composite*. On
peut généraliser ce principe en combinant /M/ cellules rythmiques et
en divisant la durée de chaque note par /M/ : on obtient alors une
cellule composite comptant /M/ sous-cellules rythmiques simples.

Dans la suite, nous considérons une pulsation binaire de structure
/N N/ et une pulsation ternaire de structure /N N N/.


** Synchrones

Lorsque les durées des cellules rythmiques juxtaposées ont la même
durée, on parle de *cellule composite synchrone*. Un petit exemple
trivial sur un rythme binaire :

#+ATTR_HTML: :class plat
| [ ( B ) ( B ) ] / 2 | ⟼ | ( N ) ( N ) | = | N N |

Autre exemple, cette fois sur un rythme ternaire :

#+ATTR_HTML: :class plat
| [ ( B N ) ( B N ) ] / 2 | ⟼ | ( N C ) ( N C ) | = | N C N C |


*** Doubles

En juxtaposant deux rythmes, on obtient des cellules composites dites
*doubles*. Le tableau suivant reprend quelques unes de ces
combinaisons :

| Structure 1 | Structure 2 | Binaire         | Ternaire    |
|-------------+-------------+-----------------+-------------|
| — ∪         | ⊥           | Cp dC N         | N C Np      |
| ⊥           | — ∪         | N Cp dC         | Np N C      |
| ⊥           | ∪ —         | N dC Cp         | Np C N      |
| — ∪         | — ∪         | Cp dC Cp dC     | N C N C     |
| — ∪         | ∪ —         | Cp dC dC Cp     | N C C N     |
| — ∪         | ⊥ ⊥         | Cp dC C C       | N C Cp Cp   |
| ⊥ ⊥         | — ∪         | C C Cp dC       | Cp Cp N C   |
| —           | ∪ ∪ ∪       | N C dC dC       | Np C C C    |
| ∪ ∪ ∪       | —           | C dC dC N       | C C C N     |
| — ∪         | ⊥ ⊥ ⊥       |                 | N C C C C   |
| ⊥ ⊥ ⊥       | — ∪         |                 | C C C N C   |
| ⊥ ⊥ ⊥       | ⊥ ⊥         |                 | C C C Cp Cp |
| ⊥           | ⊥ ⊥ ⊥ ⊥     | N dC dC dC dC   |             |
| ⊥ ⊥ ⊥ ⊥     | ⊥           | dC dC dC dC N   |             |
| — ∪ ∪       | ⊥ ⊥         | C dC dC C C     |             |
| — ∪         | ∪ ∪ —       | Cp dC dC dC C   |             |
| — ∪ ∪       | ∪ —         | C dC dC dC Cp   |             |
| — ∪ ∪       | ∪ ∪ —       | C dC dC dC dC C |             |


**** Triples

En juxtaposant trois rythmes, on obtient des cellules composites dites
*triples*. Soulignons que le rythme ainsi obtenu sera composé de trois
parties, et donc ternaire. Le tableau suivant reprend quatre unes de
ces combinaisons :

| Structure 1 | Structure 2 | Structure 3 | Binaire ⟼ Ternaire |
|-------------+-------------+-------------+--------------------|
| ⊥           | ⊥           | ⊥ ⊥         | N N C C            |
| ⊥           | — ∪         | ⊥           | Ν Cp dC N          |


*** Asynchrones

Lorsque les durées des cellules rythmiques juxtaposées n’ont pas la
même durée, on parle de *cellule composite asynchrone*. Voici un
exemple trivial de combinaison asynchrone :

#+ATTR_HTML: :class plat
| [ ( R ) ( B ) ] / 2 | ⟼ | ( B ) ( N ) | = | B N |


**** Swing

Une application particulièrement importante des combinaisons
asynchrones concerne les rythmes ternaires. Ceux-ci peuvent en effet
se voir décomposés suivant le schéma :

#+ATTR_HTML: :class plat
| 3 | = | 2 + 1 |

Cette décomposition produit un ressort musical très dansant, connu
dans le jazz sous le nom de swing. Voici un exemple de combinaison
asynchrone construite suivant ce principe :

#+ATTR_HTML: :class plat
| [ ( R ) ( N N ) ] / 2 | ⟼ | ( B ) ( C C ) | = | B C C |

Autre exemple :

#+ATTR_HTML: :class plat
| [ ( Bp N ) ( B ) ] / 2 | ⟼ | ( Np C ) ( N ) | = | Np C N |

Bien entendu, le même principe peut être appliqué aux rythmes
binaires, le décalage produit sera toutefois différent :

#+ATTR_HTML: :class plat
| 4 | = | 3 + 1 |


**** Exemples

Le tableau suivant reprend quelques combinaisons doubles :

| Structure 1 | Structure 2 | Ternaire  |
|-------------+-------------+-----------|
| ⊥           | ⊥ ⊥ ⊥ ⊥     | N C C C C |
| ⊥ ⊥ ⊥ ⊥     | ⊥           | C C C C N |

et triples :

| Structure 1 | Structure 2 | Structure 3 | Ternaire            |
|-------------+-------------+-------------+---------------------|
| ⊥           | ⊥           | ⊥ ⊥ ⊥       | C Cp dC dC dC       |
| — ∪         | ⊥           | ⊥ ⊥         | C dC Cp dC dC       |
| ⊥ ⊥ ⊥       | ⊥           | ⊥ ⊥ ⊥       | dC dC dC C dC dC dC |


*** Syncopées

En divisant par deux la durée d’un couple de cellules rythmiques
contenant une syncope, on obtient une *cellule composite syncopée*.
Voici les plus courantes :

| Structure        | Avant division | Après division | Forme équivalente |
|------------------+----------------+----------------+-------------------|
| Binaire : N N    | N N‿N N        | C C‿C C        | C N C             |
|                  | Np C‿Np C      | Cp dC‿Cp dC    | Cp N dC           |
| Ternaire : N N N | B N‿B N        | N C‿N C        | N Np C            |
|                  | N N N‿N N N    | C C C‿C C C    | C C N C C         |


*** Inverse

Prenons une cellule rythmique durant une pulsation et multiplions par
deux la durée de chaque note : on peut remplir deux pulsations avec le
rythme ainsi obtenu. En voici un exemple avec deux pulsations binaires
durant chacune une blanche :

#+ATTR_HTML: :class plat
| C N C | ⟼ | N B N |

Si nous multiplions par trois la durée de la cellule rythmique
initiale, nous pouvons remplir trois pulsations, si nous la
multiplions par /M/, nous pouvons remplir /M/ pulsations.


* Hémiole

#+TOC: headlines 1 local


** Introduction

L’hémiole est un procédé qui consiste à réorganiser une structure
rythmique du type :

#+ATTR_HTML: :class plat
| 2 x 3 | = | 2 entités décomposables en 3 |

en une structure alternative du type :

#+ATTR_HTML: :class plat
| 3 x 2 | = | 3 entités décomposables en 2 |

Le procédé inverse, à savoir réorganiser une structure du type /3 × 2/
en une structure alternative du type /2 × 3/, est également une
hémiole. Précisons que les structures /2 × 3/ et /3 × 2/ peuvent être
présentées consécutivement ou simultanément.

/Remarque/ : le terme hémiole provient du grec ancien et signifie
littéralement « un et demi », mathématiquement identique à 3 / 2.


** Échelles


*** Pulsation

Considérons par exemple une pulsation durant une blanche pointée, soit
6 croches. Ces 6 croches peuvent être regroupées en 2 temps de 3
croches durant chacun une noire pointée, ou en 3 temps de 2 croches
durant chacun une noire :

#+ATTR_HTML: :class plat
| (C C C) (C C C)   | ⟻⟼ | Np Np |
| (C C) (C C) (C C) | ⟻⟼ | N N N |


*** Oscillation

Considérons à présent une oscillation durant une ronde pointée, soit
six noires : on peut la considérer comme une succession de 2
pulsations durant chacune 3 noires, soit une blanche pointée, ou de 3
pulsations durant chacune 2 noires, soit une blanche :

#+ATTR_HTML: :class plat
| (N N N) (N N N)   | ⟻⟼ | Bp Bp |
| (N N) (N N) (N N) | ⟻⟼ | B B B |


*** Mesures simples

Dans le cas de mesures simples, l’hémiole se positionne sur plusieurs
mesures : 2 mesures de 3 temps peuvent être pensées comme 3 mesures de
2 temps, et vice versa.


** Generalisation

On peut appliquer le même procédé à 4 entités rythmiques décomposables
en 3, structure qui peut être réorganisée en 3 unités rythmiques
décomposables en 4, et vice versa.

Plus généralement, soit /M/ et /N/ deux nombres entiers strictement
positifs. On considère une structure rythmique formée par /M/ entités,
chacune de ces entités étant décomposable en /N/ sous-entités. La
structure compte donc en tout /M × N/ sous-entités. Comme :

#+ATTR_HTML: :class plat
| M × N | = | N × M |

on peut réorganiser l’ensemble en /N/ entités rythmiques décomposables
en /M/ sous-entités. On parle alors d’une hémiole de type (/M/, /N/).
