
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 04 : Clavier
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* Dualité

#+TOC: headlines 1 local


** Grille

On peut représenter une polyphonie comme une superposition de
mélodies, mais également comme une succession d’accords, chacun
d’entre-eux régnant un certain temps sur le déroulement musical avant
de laisser la place à son successeur. Le tableau suivant illustre
cette dualité dans le cas d’un septuor :

#+ATTR_HTML: :class plat
| S | : | (accord-1, note-1) | (accord-2, note-1) | (accord-3, note-1) | =...= |
| M | : | (accord-1, note-2) | (accord-2, note-2) | (accord-3, note-2) | =...= |
| A | : | (accord-1, note-3) | (accord-2, note-3) | (accord-3, note-3) | =...= |
| C | : | (accord-1, note-4) | (accord-2, note-4) | (accord-3, note-4) | =...= |
| T | : | (accord-1, note-5) | (accord-2, note-5) | (accord-3, note-5) | =...= |
| Y | : | (accord-1, note-6) | (accord-2, note-6) | (accord-3, note-6) | =...= |
| B | : | (accord-1, note-7) | (accord-2, note-7) | (accord-3, note-7) | =...= |

Cette représentation schématique a le mérite de n’intégrer que les
notes essentielles de la polyphonie, ce qui permet de visualiser du
premier coup d’oeil les évolutions des voix lors des changements
d’accords. Nous appelons *grille polyphonique*, ou plus simplement
*grille* une telle représentation schématique de la polyphonie.


** Notes

Les notes d’une polyphonie peuvent se scinder en deux catégories :

  - les *notes essentielles* sont les notes qui appartiennent à la
    grille polyphonique, et donc à l’un des accords qui la constituent

  - les *notes étrangères* sont les notes qui n’appartiennent pas à la
    grille polyphonique, et donc à aucun des accords qui la
    constituent

Les notes essentielles consitutent la fondation de la polyphonie,
tandis que les notes étrangères servent à compléter le discours
musical.

/Remarque/ : on utilise également les expressions *note réelle* ou
*note constitutive* comme synonymes de note essentielle.


** Mélodie

On distingue :

  - l’ *intervalle mélodique* en général, intervalle entre deux notes
    consécutives quelconques

  - l’ *intervalle mélodique essentiel*, intervalle entre deux notes
    essentielles consécutives

On utilise également l’expression *mouvement mélodique essentiel*
comme synonyme d’intervalle mélodique essentiel.

Il existe donc 4 possibilités de mouvement mélodique :

  1. note essentielle — note essentielle : intervalle mélodique essentiel
  2. note essentielle — note étrangère
  3. note étrangère — note essentielle
  4. note étrangère — note étrangère


** Harmonie

On distingue :

  - l’ *intervalle harmonique* en général, intervalle entre deux notes
    simultanées quelconques

  - l’ *intervalle harmonique essentiel*, intervalle entre deux notes
    essentielles simultanées

Il existe donc 4 possibilités d’intervalle harmonique :

  1. note essentielle — note essentielle : intervalle harmonique essentiel
  2. note essentielle — note étrangère
  3. note étrangère — note essentielle
  4. note étrangère — note étrangère


** Accords

On peut classer grossièrement les accords en deux catégories, suivant
leur importance :

  - les *accords stratégiques* constituent la clef de voûte du
    discours musical

  - les *accords ornementaux* ont pour but de fluidifier et
    d’ornementer les mélodies


** Enchaînement

Un *enchaînement* est une suite formée de deux intervalles ou de deux
accords consécutifs.

Deux accords consécutifs sont dit *enchaînés*.


*** Changement d’harmonie

Une *harmonie* peut aussi désigner le règne d’un accord.

On parle donc de *changement d’harmonie* pour signaler un changement
d’accord.


** Cadence

Une *cadence* est une suite d’intervalles ou d’accords qui ponctue le
discours musical.

Ce rôle de ponctuation est assuré par les caractèristiques des
intervalles ou accords impliqués, et peut être renforcé par :

 - une durée plus longue des notes
 - un rythme ralenti
 - etc


** Rythme harmonique

Le rythme auquel les accords se succèdent est appelé *rythme
harmonique*. Le rythme harmonique peut être régulier ou variable.

Chaque accord règne un certain temps sur la musique avant de laisser
la place à son successeur. Ce règne peut durer pendant :

  - une carrure (entière ou fraction)
  - une oscillation
  - une pulsation
  - une mesure
  - un temps
  - =...=


** Rencontres

Une rencontre est un instant /t/ où plusieurs notes essentielles de la
polyphonie sont entendues. Précisons que ces notes ne sont pas
forcément entamées ou terminées ensemble.

La perception du cadre harmonique est renforcée par des rencontres
entre les notes essentielles les plus importantes de chaque accord.

Les rencontres peuvent se produire à un rythme régulier ou variable.
En fait, elles sont liées au rythme harmonique, l’idéal étant de
disposer d’au moins une rencontre par accord.


* Mouvements harmoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements harmoniques* analysent les modifications de
disposition des notes essentielles au cours du règne d’un même accord.


** Échange

L’ *échange* consiste à intervertir les voix de deux notes
essentielles.

Exemple d’échange :

#+ATTR_HTML: :class plat
| S | : | mi | do |
| B | : | do | mi |


** Changement

Le *changement* consiste à modifier une des voix pour jouer une autre
note de l’accord.

Exemple de changement, ici sur le soprano :

#+ATTR_HTML: :class plat
| S | : | mi | sol |
| B | : | do | do  |


* Agencements polyphoniques

#+TOC: headlines 1 local

** Intervalles consécutifs
:PROPERTIES:
:CUSTOM_ID: section:intervallesConsecutifs
:END:

Il se produit des *intervalles consécutifs* lorsque deux intervalles
harmoniques :

  - essentiels
  - consécutifs
  - situés sur les mêmes voix

sont identiques à l’octave près.

Exemple de tierces consécutives :

#+ATTR_HTML: :class plat
| S | : | mi | la  | (monte d’une 4te ou descend d’une 5te) |
| B | : | do | fa  | (monte d’une 4te ou descend d’une 5te) |


** Intervalles rapprochés

Il se produit des *intervalles rapprochés* lorsque deux accords
consécutifs reproduisent, sur les mêmes voix et à l’octave près, un
même intervalle harmonique.


*** Rapprochés & consécutifs

Des intervalles consécutifs sont forcément rapprochés.

Par contre, des intervalles rapprochés ne sont pas forcément
consécutifs : une modification de la disposition du premier ou du
deuxième accord peut venir s’intercaler entre les deux intervalles.

Exemple de quintes rapprochées mais pas consécutives, entre le soprano
et la basse :

#+ATTR_HTML: :class plat
| S | : | /sol/ | mi  | /la/ |
| A | : | mi    | sol | fa   |
| B | : | /do/  | do  | /ré/ |

La première disposition produit la quinte /do — sol/ entre la basse et
le soprano. On a ensuite un échange de /do — mi — sol/ vers
/do — sol — mi/. L’accord suivant reproduit une quinte /ré — la/,
toujours entre la basse et le soprano.


** Croisement

Un *croisement* se produit lorsqu’une note essentielle d’une voix
normalement plus grave croise à la hausse une note essentielle d’une
voix plus aiguë.


** Chevauchement

Un *chevauchement* se produit lorsqu’une note essentielle d’une voix
plus grave croise à la hausse une note essentielle d’une voix plus
aiguë /de l’accord précédent/.


** Fausse relation

Une fausse relation est une association de deux notes disposées sur
des voix différentes.


*** Chromatique

Une *fausse relation chromatique* se produit lorsque les trois notes
d’un mouvement chromatique ne sont pas toutes disposées sur la même
voix.


*** Triton

Une *fausse relation de triton* se produit lorsque les deux notes d’un
intervalle de triton :

  - appartiennent à deux accords consécutifs
  - sont situées sur deux voix différentes


* Mouvements polyphoniques

#+TOC: headlines 1 local


** Introduction

Les *mouvements polyphoniques* comparent les évolutions de deux voix
quelconques de la grille polyphonique lors d’un changement d’accord,
ce qui les place au croisement de l’harmonie et de la mélodie.

On peut voir un mouvement polyphonique comme :

  - une superposition de deux intervalles mélodiques essentiels
  - un enchaînement de deux intervalles harmoniques essentiels

Les notes impliquées sont donc des notes essentielles, et les
intervalles mélodiques sont des intervalles mélodiques essentiels.


** Mouvement parallèle

Il se produit un mouvement *parallèle* lorsque les deux voix évoluent
dans la même direction en utilisant le même intervalle mélodique.

/Remarque/ : dans le cadre des mouvements polyphoniques, on ne fait
pas de distinction entre les intervalles majeurs et mineurs. Par
exemple, si une voix monte d’une seconde majeure pendant que l’autre
monte d’une seconde mineure, le mouvement sera considéré comme
parallèle.


*** Ascendant

Un mouvement *parallèle ascendant* est un mouvement parallèle où les
deux voix évoluent vers l’aigu.

Exemple de mouvement parallèle ascendant :

#+ATTR_HTML: :class plat
| S | : | ré | mi | (monte) |
| B | : | la | si | (monte) |


*** Descendant

Un mouvement *parallèle descendant* est un mouvement parallèle où les
deux voix évoluent vers le grave.

Exemple de mouvement parallèle descendant :

#+ATTR_HTML: :class plat
| S | : | ré | do  | (descend) |
| B | : | la | sol | (descend) |


*** Continuité

Un mouvement *parallèle conjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement conjoint.

Un mouvement *parallèle disjoint* est un mouvement parallèle où les
deux voix évoluent par mouvement disjoint.


** Mouvement direct

Il se produit un mouvement *direct* lorsque les deux voix évoluent
dans la même direction, mais au moyen d’intervalles différents.


*** Ascendant

Un mouvement *direct ascendant* est un mouvement direct où les deux
voix évoluent vers l’aigu.

Exemple de mouvement direct ascendant :

#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte) |
| B | : | mi | si  | (monte) |


*** Descendant

Un mouvement *direct descendant* est un mouvement direct où les deux
voix évoluent vers le grave.

Exemple de mouvement direct descendant :

#+ATTR_HTML: :class plat
| S | : | fa  | mi | (descend) |
| B | : | sol | do | (descend) |


*** Continuité

Un *mouvement direct conjoint* est un mouvement direct où l’une des
voix évolue par mouvement conjoint tandis que l’autre évolue par
mouvement disjoint.

Un *mouvement direct disjoint* est un mouvement direct où les deux
voix évoluent par mouvement disjoint.


** Mouvement oblique

Il se produit un mouvement *oblique* lorsqu’une des deux voix reste
constante pendant que l’autre varie.

Le mouvement oblique se produit généralement lorsqu’une note commune à
deux accords consécutifs est disposée sur la même voix.


*** Ascendant

Un mouvement *oblique ascendant* est un mouvement oblique où la voix
mobile évolue vers l’aigu.

Exemple de mouvement oblique ascendant :


#+ATTR_HTML: :class plat
| S | : | fa | sol | (monte)    |
| B | : | do | do  | (constant) |


*** Descendant

Un mouvement *oblique descendant* est un mouvement oblique où la voix
mobile évolue vers le grave.

Exemple de mouvement oblique descendant :

#+ATTR_HTML: :class plat
| S | : | fa | ré | (descend)  |
| B | : | do | do | (constant) |


*** Continuité

Un mouvement *oblique conjoint* est un mouvement oblique où la voix
mobile évolue par mouvement conjoint.

Un mouvement *oblique disjoint* est un mouvement oblique où la voix
mobile évolue par mouvement disjoint.


** Mouvement contraire

Il se produit un mouvement *contraire* lorsque les deux voix évoluent
dans des directions opposées : l’une monte, tandis que l’autre
descend.


*** Extérieur

Un mouvement *extérieur* est un mouvement contraire où la voix
supérieure monte, tandis que la voix inférieure descend.

Pour s’en souvenir, se rappeler que les voix d’un mouvement extérieur
se dirigent vers l’extérieur du premier intervalle harmonique.

Exemple de mouvement extérieur :

#+ATTR_HTML: :class plat
| S | : | si  | do | (monte)   |
| B | : | sol | fa | (descend) |


*** Intérieur

Un mouvement *intérieur* est un mouvement contraire où la voix
supérieure descend, tandis que la voix inférieure monte.

Pour s’en souvenir, se rappeler que les voix d’un mouvement intérieur
se dirigent vers l’intérieur du premier intervalle harmonique.

Exemple de mouvement intérieur :

#+ATTR_HTML: :class plat
| S | : | si | la | (descend) |
| B | : | mi | fa | (monte)   |


*** Continuité

Un mouvement *contraire conjoint* est un mouvement contraire où les
deux voix évoluent par mouvement conjoint.

Un mouvement *contraire disjoint* est un mouvement contraire où au
moins une des voix évolue par mouvement disjoint.

#+begin_center
⁂
#+end_center

Un mouvement *extérieur conjoint* est un mouvement extérieur où les
deux voix évoluent par mouvement conjoint.

Un mouvement *extérieur disjoint* est un mouvement extérieur où au
moins une des voix évolue par mouvement disjoint.

#+begin_center
⁂
#+end_center

Un mouvement *intérieur conjoint* est un mouvement intérieur où les
deux voix évoluent par mouvement conjoint.

Un mouvement *intérieur disjoint* est un mouvement intérieur où au
moins une des voix évolue par mouvement disjoint.


** Tableau récapitulatif

Lorsque les directions des voix sont représentées, on utilise la
convention suivante :

#+begin_center
direction de la voix supérieure : direction de la voix inférieure
#+end_center

Une double barre inclinée symbolise un intervalle mélodique plus grand
que la barre inclinée simple.

| Mouvement            | Sens    | Intervalles |  Nombre de |  Nombre de |
|                      |         | mélodiques  |       voix |       voix |
|                      |         |             | constantes | conjointes |
|----------------------+---------+-------------+------------+------------|
| parallèle            | =       | =           |          0 |            |
| parallèle ascendant  | / : /   | =           |          0 |            |
| parallèle descendant | \ : \   | =           |          0 |            |
| parallèle conjoint   | =       | =           |          0 |          2 |
| parallèle disjoint   | =       | =           |          0 |          0 |
|----------------------+---------+-------------+------------+------------|
| direct               | =       | pas =       |          0 |            |
| direct ascendant     | // : /  | pas =       |          0 |            |
|                      | / : //  | pas =       |          0 |            |
| direct descendant    | \\ : \  | pas =       |          0 |            |
|                      | \ : \\  | pas =       |          0 |            |
| direct conjoint      | =       | pas =       |          0 |          1 |
| direct disjoint      | =       | pas =       |          0 |          0 |
|----------------------+---------+-------------+------------+------------|
| oblique              |         | pas =       |          1 |            |
| oblique ascendant    | / : —   | pas =       |          1 |            |
|                      | — : /   | pas =       |          1 |            |
| oblique descendant   | \ : —   | pas =       |          1 |            |
|                      | — : \   | pas =       |          1 |            |
| oblique conjoint     |         | pas =       |          1 |          2 |
| oblique disjoint     |         | pas =       |          1 |          1 |
|----------------------+---------+-------------+------------+------------|
| contraire            | opposés |             |          0 |            |
| extérieur            | / : \   |             |          0 |            |
| intérieur            | \ : /   |             |          0 |            |
| contraire conjoint   | opposés | =           |          0 |          2 |
| contraire disjoint   | opposés |             |          0 |     1 ou 0 |
| extérieur conjoint   | / : \   | =           |          0 |          2 |
| extérieur disjoint   | / : \   |             |          0 |     1 ou 0 |
| intérieur conjoint   | \ : /   | =           |          0 |          2 |
| intérieur disjoint   | \ : /   |             |          0 |     1 ou 0 |


* Principes
:PROPERTIES:
:CUSTOM_ID: section:principes
:END:

#+TOC: headlines 1 local

** Introduction

Voici quelques caractéristiques propres à une polyphonie réussie :

  - cohérence
    + chaque voix fait entendre une mélodie cohérente
    + l’ensemble de la polyphonie est cohérent
  - clarté
    + on doit pouvoir discerner les voix les plus importantes
    + l’ensemble ne surcharge pas l’oreille
  - équilibre
    + les voix sont équilibrées
    + les mouvements polyphoniques sont variés
  - indépendance
    + les voix sont indépendantes
  - avant-plan et arrière-plan
    + à chaque instant, certaines voix sont mises en avant-plan et
      d’autres en arrière-plan
      * voix en avant-plan = personnages
      * voix en arrière-plan = décor
    + le nombre de voix en avant-plan n’est pas trop élevé afin de ne
      pas surcharger l’oreille
  - dialogue
    + la succession des thèmes d’avant-plan mis bout à bout forme un
      ensemble cohérent qui se balade de voix en voix, donnant une
      impression de causerie où les voix se répondent.


** Mélodie


*** Intervalles

On privilégie les intervalles mélodiques allant de l’unisson à la
sixte mineure, auxquels on ajoute l’octave :

  - l’unisson juste
  - les secondes majeure et mineure
  - les tierces majeure et mineure
  - la quarte juste
  - la quinte juste
  - la sixte mineure
  - l’octave juste

Les autres intervalles sont moins utilisés :

  - la sixte majeure
  - les septièmes majeure et mineure
  - les intervalles dépassant l’octave
  - les intervalles augmentés et diminués
  - les intervalles sur-augmentés et sur-diminués

Cette classification est lié à la musique vocale : les intervalles
au-dessus de la sixte mineure, octave excepté, sont considérés comme
difficiles à chanter. Toutefois, la musique traditionnelle utilise
abondamment les sauts mélodiques expressifs, et dépasse parfois la
sixte mineure. Citons comme exemple le chant « Deck the Hall », qui
utilise la sixte majeure dans son thème principal.

Plus généralement, l’intervalle mélodique maximal va dépendre de
l’instrument. Beaucoup d’entre-eux sont capables de produire des sauts
d’une grande amplitude :

  - instruments à clavier
  - famille des guitares
  - famille des violons
  - etc


*** Continuité

On privilégie les mouvements conjoints.

Les mouvements disjoints sont de préférence précédés ou suivis par un
intervalle mélodique allant dans le sens opposé du saut.


** Économie de mouvement


*** Changement d’accord

Le principe d’ *économie de mouvement* dit que les notes essentielles
doivent évoluer majoritairement par mouvement conjoint au cours d’un
changement d’accord, ce qui permet :

  - de distinguer plus aisément les différentes voix de la polyphonie

  - de distinguer les intervalles internes des accords (tierces,
    sixtes, etc) des intervalles permettant l’enchaînement

On priviligiera donc à chaque enchaînement, par ordre décroissant :

  1. le mouvement conjoint sur une majorité des voix
  2. le saut de quinte ou de quarte
  3. le saut de tierce ou de sixte

/Remarque/ : ce principe s’applique aux changements de notes
/essentielles/ lors du passage d’un accord à un autre. Il n’y a aucune
réserve à avoir concernant l’utilisation des tierces et des sixtes
mélodiques à l’intérieur du règne d’un même accord.


*** Mélodie

Le principe d’économie de mouvement est également valable dans la
dimension horizontale de la grille polyphonique générée par la
succession des accords.

Chaque mélodie de la polyphonie doit évoluer majoritairement par
mouvement conjoint, ceci afin de permettre à l’oreille de discerner
les différentes voix qui composent la polyphonie.

Cette continuité majoritaire permet également d’accentuer aisément
certains passages du discours musical (fin de phrase, mise en valeur
d’une émotion, etc) en utilisant le contraste qu’offrent alors les
sauts discontinus des mouvements disjoints.


** Agencements


*** Croisement & chevauchement

Le croisement et le chevauchement perturbent l’ordre naturel des
lignes mélodiques. Afin de bien les distinguer, ils sont donc à
utiliser avec modération.

Dans certains cas, ils se révèlent très utiles pour assurer une bonne
conduite des voix, qui sans eux serait difficile voire impossible.

Certains paramètres musicaux, comme l’utilisation de timbres
différents, permettent d’éviter la confusion des voix. Il peut aussi
arriver qu’une confusion fugitive soit souhaitée.


** Mouvements polyphoniques

Les mouvements polyphoniques à privilégier sont, par ordre
décroissant :

  1. le mouvement contraire
  2. le mouvement oblique
  3. le mouvement direct
  4. le mouvement parallèle

Ce classement ne doit toutefois pas empiéter sur les principes
d’équilibre et d’indépendance des voix qui demandent de varier les
mouvements.


*** Mouvement contraire

Le mouvement contraire contribue à l’équilibre et à l’indépendance des
voix.

Il est à privilégier autour des configuration musicales aisément
détectables par l’oreille : consonances parfaites, dissonances, etc.

Si le mouvement contraire permet d’affirmer ponctuellement
l’indépendance des voix impliquées, il ne faut toutefois pas en
abuser. Que l’on songe au cas extrême où deux voix données évoluent
constamment par mouvement contraire : chacune d’elle semble alors
devenir le reflet de l’autre, ce qui est à l’opposé de l’indépendance
recherchée.


*** Mouvement oblique

Tout comme le mouvement contraire, il est à privilégier autour des
consonances parfaites, dissonances, etc.


*** Mouvement direct

Le mouvement direct conjoint est le plus élégant : une des voix évolue
par mouvement conjoint tandis que l’autre effectue un mouvement
disjoint (idéalement quarte ou quinte), l’idée étant que le contraste
entre les variations des deux voix le fasse ressembler à un mouvement
oblique.


** Notes communes

#+TOC: headlines 1 local

*** Aucune note commune

Si la basse évolue par mouvement conjoint et que les accords enchaînés
ne possèdent aucune note commune, on essaie de faire évoluer les
autres voix dans l’autre sens, pour conserver un certain équilibre.
Lorsque ce n’est pas possible, on essaie malgré tout de réaliser un
mouvement contraire entre les voix extrêmes.

Comme toujours, on privilégie le mouvement conjoint.

#+begin_center
⁂
#+end_center

Les enchaînements d’accords parfaits où la fondamentale monte ou
descend d’une seconde ne possèdent aucune note commune.

Nous considérons des enchaînements :

  - à quatre voix
  - d’accords parfaits
  - à l’état fondamental
  - avec une basse conjointe
  - avec une doublure

Exemple avec une basse qui descend d’une seconde :

#+ATTR_HTML: :class plat
| S | : | ré | mi  | (monte)   |
| A | : | la | do  | (monte)   |
| T | : | fa | sol | (monte)   |
| B | : | ré | do  | (descend) |

Exemple avec une basse qui monte d’une seconde :

#+ATTR_HTML: :class plat
| S | : | ré | si  | (descend) |
| A | : | fa | mi  | (descend) |
| T | : | la | sol | (descend) |
| B | : | ré | mi  | (monte)   |


*** Une note commune

Lorsque deux accords consécutifs possèdent une seule note commune, on
la place généralement comme note constante sur une même voix afin de
respecter la philosophie de l’économie de mouvement. On génère alors
des mouvements obliques avec les autres voix.

On privilégie les mouvements conjoints, avec éventuellement un
mouvement disjoint.

#+begin_center
⁂
#+end_center

Les enchaînements d’accords parfaits où la fondamentale monte ou
descend d’une quinte possèdent une note commune. L’équilibre entre la
note commune et les deux nouvelles notes en font d’excellentes
progressions.

Nous considérons des enchaînements :

  - à quatre voix
  - d’accords parfaits
  - à l’état fondamental
  - avec une basse disjointe
  - avec une doublure

Lorsque la fondamentale descend d’une quinte, la basse du deuxième
accord fera entendre une nouvelle note, ce qui produira plus de
contraste.

Exemple :

#+ATTR_HTML: :class plat
| S | : | mi   | fa   |
| A | : | do   | ré   |
| T | : | /la/ | /la/ |
| B | : | la   | ré   |

Lorsque la fondamentale monte d’une quinte, la basse du deuxième
accord fera aussi entendre la note commune, ce qui produira moins de
contraste.

Exemple :

#+ATTR_HTML: :class plat
| S | : | /mi/ | /mi/ |
| A | : | do   | si   |
| T | : | la   | sol  |
| B | : | la   | /mi/ |


*** Deux notes communes

Lorsque deux accords consécutifs possèdent deux notes communes, on
place généralement chacune d’elle comme note constante sur une même
voix.

Les deux notes communes offrent un contraste moins prononcé qu’avec
une seule.

#+begin_center
⁂
#+end_center

Les enchaînements d’accords parfaits où la fondamentale monte ou
descend d’une tierce possèdent deux notes communes.

Nous considérons des enchaînements :

  - à quatre voix
  - d’accords parfaits
  - à l’état fondamental
  - avec une basse disjointe
  - avec une doublure

Lorsque la fondamentale descend d’une tierce, la basse du deuxième
accord fera entendre une nouvelle note, ce qui produira plus de
contraste.

Exemple :

#+ATTR_HTML: :class plat
| S | : | /la/ | /la/ |
| A | : | mi   | fa   |
| T | : | /do/ | /do/ |
| B | : | la   | fa   |

Lorsque la fondamentale monte d’une tierce, la basse du deuxième
accord fera entendre une des notes communes, ce qui produira moins de
contraste.

Exemple :

#+ATTR_HTML: :class plat
| S | : | la   | sol  |
| A | : | /mi/ | /mi/ |
| T | : | /do/ | /do/ |
| B | : | la   | /do/ |


*** Note commune sur deux voix distinctes

Un mouvement direct disjoint peut être amélioré si une note du premier
intervalle harmonique est réentendue à la même hauteur dans l’accord
suivant. Cette astuce crée une impression de continuité entre les deux
voix impliquées, et fait passer le mouvement direct à l’arrière-plan.

La deuxième audition de la note se fait normalement sur la voix
immédiatement supérieure ou inférieure.

Exemple de mouvement direct entre le soprano et l’alto, où la deuxième
audition du /mi/ se fait à la voix immédiatement inférieure :

#+ATTR_HTML: :class plat
| S | : | /mi/ | sol  | (monte) |
| A | : | la   | /mi/ | (monte) |
| T | : | do   | si   |         |
| B | : | la   | sol  |         |

Exemple de mouvement direct entre le ténor et la basse où la deuxième
audition du /la/ se fait à la voix immédiatement supérieure :

#+ATTR_HTML: :class plat
| S | : | mi   | fa   |           |
| A | : | la   | fa   |           |
| T | : | do   | /la/ | (descend) |
| B | : | /la/ | ré   | (descend) |


** Lignes mélodiques extrêmes

Les mouvements formés par les lignes mélodiques extrêmes (basse et
soprano) doivent être particulièrement soignés, car ce sont les voix
les plus évidentes pour l’oreille.


** Lien polyphonique

On dit qu’il existe un *lien polyphonique* entre deux accords s’il est
possible de les enchaîner en respectant les principes énoncés
jusqu’ici :

  - équilibre, mouvements polyphoniques variés
  - mouvement contraire > oblique > direct > parallèle
  - économie de mouvement, majorité de mouvement conjoint
  - note commune de préférence sur une même voix
  - etc


* Cadences d’intervalles

#+TOC: headlines 1 local

** Introduction

Une *cadence d’intervalles* est une cadence construite comme un
enchaînement d’intervalles harmoniques qui débouche sur une consonance
parfaite : unisson, octave ou quinte.


** Mouvement polyphonique associé

Les cadences d’intervalles sont nommées d’après le mouvement
polyphonique auquel elles sont associées. En voici quelques unes :

| Mouvement            | Cadence               |
|----------------------+-----------------------|
| contraire            | contraire             |
| extérieur            | extérieure            |
| intérieur            | intérieure            |
| contraire conjoint   | contraire conjointe   |
| extérieur conjoint   | extérieure conjointe  |
|----------------------+-----------------------|
| oblique              | oblique               |
| oblique conjoint     | oblique conjointe     |
| oblique disjoint     | oblique disjointe     |
|----------------------+-----------------------|
| direct               | directe               |
|----------------------+-----------------------|
| parallèle            | parallèle             |


** Classement

L’ordre de préférence est le même que pour les mouvements
polyphoniques, à la nuance près que les cadences contraire et oblique
sont de loin les plus utilisées :

#+begin_center
contraire > oblique >> directe > parallèle
#+end_center

Les plus appréciées sont les cadences contraires conjointes, et en
particulier :

  - la cadence extérieure conjointe arrivant sur
    + octave
    + quinte
  - la cadence intérieure conjointe arrivant sur unisson


** Contraire conjointe

#+TOC: headlines 1 local

**** Arrivée sur unisson

La cadence extérieure conjointe arrivant sur unisson nécessite un
croisement des voix et est donc à utiliser avec précaution. Exemple :

#+ATTR_HTML: :class plat
| S | : | sol | la | (monte)   |
| B | : | si  | la | (descend) |

Par contre, la cadence intérieure conjointe arrivant sur unisson part
d’une tierce, ce qui ne pose aucun problème. Exemple :

#+ATTR_HTML: :class plat
| S | : | si  | la | (descend) |
| B | : | sol | la | (monte)   |


**** Arrivée sur octave

La cadence extérieure conjointe arrivant sur octave part d’une sixte.
En voici un exemple :

#+ATTR_HTML: :class plat
| S | : | mi  | fa | (monte)   |
| B | : | sol | fa | (descend) |


**** Arrivée sur quinte

La cadence extérieure conjointe arrivant sur quinte part d’une tierce.
En voici un exemple :

#+ATTR_HTML: :class plat
| S | : | la | si | (monte)   |
| B | : | fa | mi | (descend) |


* Cadences modales

#+TOC: headlines 1 local

** Introduction

Une cadence construite à partir d’intervalles harmoniques possède une
couleur musicale caractéristique. Cette couleur musicale dépend des
intervalles mélodiques parcourus par les voix lors de l’enchaînement.
Or, ces intervalles mélodiques sont eux-mêmes tributaires de la basse
amenée par la cadence, note qui correspond généralement au mode
utilisé. Les cadences d’intervalles peuvent donc être associées au
mode en cours, formant ainsi les *cadences modales*.

#+begin_center
⁂
#+end_center

Les cadences d’intervalles utilisées sont généralement des cadences
extérieures conjointes.

Suivant la consonance parfaite obtenue%, trois cas peuvent se
présenter. Lors d’une arrivée sur :

  - unisson, la tonique est la note amenée par la cadence,
    identique sur les deux voix

  - octave, la tonique  est la note amenée par la cadence,
    identique à l’octave près sur les deux voix

  - quinte, la tonique est la basse amenée par la cadence

Pour les modes naturels, la basse sera un :

  - fa, pour une cadence lydienne
  - do, pour une cadence ionienne
  - sol, pour une cadence mixolydienne
  - ré, pour une cadence dorienne
  - la, pour une cadence éolienne
  - mi, pour une cadence phrygienne
  - si, pour une cadence locrienne


** Cadence lydienne

La *cadence lydienne* est liée au mode lydien, le mode de /fa/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| B | : | sol | fa |

on remarque que la voix supérieure monte d’un demi-ton, tandis que la
voix inférieure descend d’un ton.

On observe les mêmes intervalles mélodiques lors d’une arrivée sur
quinte, dont voici un exemple :

#+ATTR_HTML: :class plat
| S | : | si  | do |
| B | : | sol | fa |


** Cadence ionienne

La *cadence ionienne* est liée au mode ionien, le mode de /do/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | si | do |
| B | : | ré | do |

on remarque que la voix supérieure monte d’un demi-ton, tandis que la voix
inférieure descend d’un ton.

Lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | fa | sol |
| B | : | ré | do  |

on remarque que les deux voix évoluent par ton.


** Cadence mixolydienne

La *cadence mixolydienne* est liée au mode mixolydien, le mode de /sol/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | fa | sol |
| B | : | la | sol |

on remarque que les deux voix évoluent par ton.

Même constatation lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | do | ré  |
| B | : | la | sol |


** Cadence dorienne

La *cadence dorienne* est liée au mode dorien, le mode de /ré/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | do | ré |
| B | : | mi | ré |

on remarque que les deux voix évoluent par ton.

Même constatation lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| B | : | mi  | ré |


** Cadence éolienne

La *cadence éolienne* est liée au mode éolien, le mode de /la/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | sol | la |
| B | : | si  | la |

on remarque que les deux voix évoluent par ton.

Même constatation lors d’une arrivée sur quinte :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| B | : | si | la |


** Cadence phrygienne

La *cadence phrygienne* est liée au mode phrygien, le mode de /mi/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| B | : | fa | mi |

on remarque que la voix supérieure monte d’un ton, tandis que la voix
inférieure descend d’un demi-ton.

On observe les mêmes intervalles mélodiques lors d’une arrivée sur
quinte, dont voici un exemple :

#+ATTR_HTML: :class plat
| S | : | la | si |
| B | : | fa | mi |


** Cadence locrienne

La *cadence locrienne* est liée au mode locrien, le mode de /si/.

Dans cet exemple d’arrivée sur octave par une cadence extérieure
conjointe :

#+ATTR_HTML: :class plat
| S | : | la | si |
| B | : | do | si |

on remarque que la voix supérieure monte d’un ton, tandis que la voix
inférieure descend d’un demi-ton.

L’arrivée sur quinte n’est pas vraiment utilisée, car elle déboucherait
sur une quinte diminuée, intervalle instable qui ne convient pas à la
fin d’une cadence :

#+ATTR_HTML: :class plat
| S | : | mi | fa |
| B | : | do | si |


** Tableau récapitulatif

| Mode               | Intervalle  | Intervalle     | Intervalle    |
|                    | de la basse | vers la quinte | vers l’octave |
|--------------------+-------------+----------------+---------------|
| lydien             | ton         | demi-ton       | demi-ton      |
| ionien             | ton         | ton            | demi-ton      |
| mixolydien         | ton         | ton            | ton           |
| dorien             | ton         | ton            | ton           |
| éolien             | ton         | ton            | ton           |
| phrygien           | demi-ton    | ton            | ton           |
| locrien            | demi-ton    | demi-ton       | ton           |


** Sensible

Lorsqu’un mode naturel ne possède ni sensible inférieure, ni sensible
supérieure, il est d’usage de hausser le degré 7 d’un demi-ton lors
des cadences modales. On fait ainsi apparaître une sensible inférieure
temporaire.

Les modes concernés sont :

 - le mode mixolydien
 - le mode dorien
 - le mode éolien

Exemples de cadences avec sensible inférieure, la cadence mixolydienne :

#+ATTR_HTML: :class plat
| S | : | fa^{#} | sol |
| B | : | la     | sol |

la cadence dorienne :

#+ATTR_HTML: :class plat
| S | : | do^{#} | ré |
| B | : | mi     | ré |

le cadence éolienne :

#+ATTR_HTML: :class plat
| S | : | sol^{#} | la |
| B | : | si      | la |


** Transposition

Toute transposition exacte d’une cadence modale sera caractérisée par
les mêmes intervalles mélodiques que la cadence d’origine. La cadence
modale transposée pourra donc être associée au même mode que la
cadence originale.


* Évolution des cadences modales

#+TOC: headlines 1 local

** Combinaisons de cadences modales

En combinant deux cadences modales à deux voix, on obtient une cadence
à trois voix.


*** Cadence Machaut

La *cadence Machaut* résulte de l’association de deux cadences
lydiennes qui partagent une même basse. La première de ces cadences
débouche sur une octave et la seconde sur une quinte.

Voici un exemple de construction, avec tout d’abord l’arrivée sur
octave :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| B | : | sol | fa |

ensuite l’arrivée sur quinte :

#+ATTR_HTML: :class plat
| A | : | si  | do |
| B | : | sol | fa |

et la cadence combinée qui en résulte :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | si  | do |
| B | : | sol | fa |


*** Cadence Landini

La *cadence Landini* est une variante de la cadence Machaut. Une étape
intermédiaire est ajoutée, sous la forme d’une cadence oblique
conjointe arrivant sur quinte et faisant intervenir les voix extrêmes.
La basse et la voix médiane restent constantes durant cette étape, ce
qui nous donne :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  |
| A | : | si  | si  |
| B | : | sol | sol |

On retrouve ensuite les arrivées sur octave et sur quinte de la
cadence Machaut :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | fa |
| A | : | si  | si  | do |
| B | : | sol | sol | fa |


*** Cadence ionienne à trois voix
:PROPERTIES:
:CUSTOM_ID: section:cadenceIonienneTroisVoix
:END:

La *cadence ionienne à trois voix* résulte de l’association de deux
cadences ioniennes qui partagent une même basse. La première de ces
cadences débouche sur une octave et la seconde sur une quinte.

Voici un exemple de construction, avec tout d’abord l’arrivée sur
octave :

#+ATTR_HTML: :class plat
| S | : | si | do |
| B | : | ré | do |

ensuite l’arrivée sur quinte :

#+ATTR_HTML: :class plat
| A | : | fa | sol |
| B | : | ré | do  |

et la cadence combinée qui en résulte :

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | sol |
| B | : | ré | do  |


*** Cadence phrygienne à trois voix

La *cadence phrygienne à trois voix* résulte de l’association de deux
cadences phrygiennes qui partagent une même basse. La première de ces
cadences débouche sur une octave et la seconde sur une quinte.

Voici un exemple de construction, avec tout d’abord l’arrivée sur
octave :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| B | : | fa | mi |

ensuite l’arrivée sur quinte :

#+ATTR_HTML: :class plat
| A | : | la | si |
| B | : | fa | mi |

et la cadence combinée qui en résulte :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| A | : | la | si |
| B | : | fa | mi |


** Ajout de voix

Les cadences modales à trois voix et plus peuvent se construire en
ajoutant une ou plusieurs voix à une cadence contraire conjointe.

Voici un exemple d’ajout d’une voix conjointe variable (ici à l’alto)
à une cadence extérieure conjointe arrivant sur octave. La voix
supplémentaire évolue pour arriver une quinte au-dessus de la basse
finale :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | si  | do |
| B | : | sol | fa |

On peut aussi ajouter une voix constante (ici à l’alto). Dans
l’exemple suivant, la voix supplémentaire est choisie pour arriver une
quinte au-dessus de la basse finale :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | do  | do |
| B | : | sol | fa |

Enfin, on peut ajouter une voix disjointe (ici à la basse).
L’intervalles mélodique essentiel est souvent une quinte ou une quarte
pour contraster avec les mouvements conjoints sur les autres voix.
Dans l’exemple suivant, la voix supplémentaire descend d’une quinte
pour arriver une ou plusieurs octaves sous les autres notes finales :

#+ATTR_HTML: :class plat
| S | : | mi  | fa |
| A | : | sol | fa |
| B | : | do  | fa |


** Ajout de deux voix


*** Cadence ionienne à quatre voix
:PROPERTIES:
:CUSTOM_ID: section:cadenceIonienneQuatreVoix
:END:

Si nous partons d’une cadence ionienne et que nous ajoutons :

  - une voix disjointe à la basse, qui arrive sur la note
    correspondant au mode
  - une voix constante une quinte au-dessus de la basse finale

nous obtenons :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | sol | do  |

Si nous partons d’une cadence ionienne et que nous ajoutons :

  - une voix disjointe à la basse, qui arrive sur la note
    correspondant au mode
  - une voix conjointe montante arrivant une quinte au-dessus de la
    basse finale

nous obtenons :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| A | : | fa  | sol |
| T | : | ré  | do  |
| B | : | sol | do  |

Si nous partons d’une cadence ionienne et que nous ajoutons :

  - une voix conjointe montante arrivant une quinte au-dessus de la
    basse finale
  - une voix conjointe descendante arrivant une tierce au-dessus de la
    basse finale

#+ATTR_HTML: :class plat
| S | : | si | do  |
| A | : | fa | mi  |
| T | : | fa | sol |
| B | : | ré | do  |


*** Cadence phrygienne à quatre voix
:PROPERTIES:
:CUSTOM_ID: section:cadencePhrygienneQuatreVoix
:END:

Si nous partons d’une cadence phrygienne et que nous ajoutons :

  - une voix disjointe à la basse, qui arrive sur la note
    correspondant au mode
  - une voix constante une quinte au-dessus de la basse finale

nous obtenons :

#+ATTR_HTML: :class plat
| S | : | ré | mi |
| A | : | si | si |
| T | : | fa | mi |
| B | : | si | mi |

Si nous partons d’une cadence phrygienne et que nous ajoutons :

  - une voix conjointe montante arrivant une quinte au-dessus de la
    basse finale
  - une voix conjointe descendante arrivant une tierce au-dessus de la
    basse finale

nous obtenons :

#+ATTR_HTML: :class plat
| S | : | ré | mi  |
| A | : | la | sol |
| T | : | la | si  |
| B | : | fa | mi  |


** Ajout de trois voix


*** Cadence ionienne à cinq voix
:PROPERTIES:
:CUSTOM_ID: section:cadenceIonienneCinqVoix
:END:

Si nous partons d’une cadence ionienne et que nous ajoutons :

  - une voix disjointe à la basse
  - une voix conjointe descendante arrivant une tierce au-dessus de la
    basse finale
  - une voix constante une quinte au-dessus de la basse finale

nous obtenons :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| M | : | fa  | mi  |
| A | : | sol | sol |
| T | : | ré  | do  |
| B | : | sol | do  |

Si nous partons d’une cadence ionienne et que nous ajoutons :

  - une voix disjointe à la basse
  - une voix conjointe montante arrivant une quinte au-dessus de la
    basse finale
  - une voix conjointe descendante arrivant une tierce au-dessus de la
    basse finale

nous obtenons :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| M | : | fa  | mi  |
| A | : | fa  | sol |
| T | : | ré  | do  |
| B | : | sol | do  |


** Ajout de quatre voix


*** Cadence ionienne à six voix

Si nous partons d’une cadence ionienne et que nous ajoutons :

  - une voix disjointe à la basse
  - une voix conjointe montante arrivant une quinte au-dessus de la
    basse finale
  - une voix conjointe descendante arrivant une tierce au-dessus de la
    basse finale
  - une voix constante une quinte au-dessus de la basse finale

nous obtenons :

#+ATTR_HTML: :class plat
| S | : | si  | do  |
| M | : | fa  | mi  |
| A | : | sol | sol |
| T | : | fa  | sol |
| Y | : | ré  | do  |
| B | : | sol | do  |


* Ornements

#+TOC: headlines 1 local

** Introduction

La modélisation d’une polyphonie sous la forme d’une suite d’accords
est d’une grande clarté et permet de cerner l’essentiel. Mais
l’essentiel n’est pas tout, et si la sobriété est très utile dans les
premières phases de la composition, on est amenés par la suite à
insérer des *ornements* afin de donner de la souplesse aux lignes
mélodiques ou d’enrichir la dynamique harmonique.

On appelle *note ornementale* une note constitutive d’un ornement.


** Notes essentielles & étrangères

Parmi les notes ornementales, on distingue :

  - les *notes ornementales essentielles* : notes ornementales qui
    font partie de l’accord en cours

  - les *notes ornementales étrangères* : notes ornementales qui ne
    font pas partie de l’accord en cours


** Ornements harmoniques

#+TOC: headlines 1 local

*** Introduction

Cette section analyse les ornements dont la fonction est
essentiellement harmonique.


*** Pédale

Une *pédale* est une note qui reste obstinément constante,
indépendamment des accords qui se succèdent sur les autres voix.

Une pédale est placée le plus souvent à la basse ou au soprano, plus
rarement aux voix intermédiaires.

Exemple de pédale, ici à la basse :

#+ATTR_HTML: :class plat
| S | : | la   | si   | mi   |
| A | : | fa   | sol  | do   |
| B | : | /do/ | /do/ | /do/ |


*** Retard

Un *retard* est une note intégrée à un accord et qui se poursuit
au-delà du changement d’accord, empiétant sur le début du règne de
l’accord suivant.

Exemple de retard, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | /ré/ | /ré/ | do  |
| A | : | la   | sol  | sol |
| B | : | fa   | mi   | mi  |


*** Anticipation

Une *anticipation* est une note appartenant à un accord qui est
entamée avant la fin du règne de l’accord précédent.

Exemple d’anticipation, ici au soprano :

#+ATTR_HTML: :class plat
| S | : | fa | /mi/ | /mi/ |
| A | : | la | la   | sol  |
| B | : | ré | ré   | do   |


*** Appogiature

Une *appogiature* est une note arbitraire jouée au début du règne d’un
accord.


** Ornements mélodiques

#+TOC: headlines 1 local

*** Introduction

Cette section analyse les ornements dont la fonction est
essentiellement mélodique.


**** Économie de mouvement

Les ornements mélodiques permettent de rendre une mélodie continue là
où on le souhaite.

On les utilise plus particulièrement pour éviter les mouvements
disjoints (essentiels ou non) lors d’un changement d’accord.


*** Note de passage

Une *note de passage* est une note ornementale intermédiaire
permettant de relier par mouvement conjoint deux notes disjointes
appartenant à un même accord où à deux accords successifs.

Exemple, le /si/ dans :

#+begin_center
do /si/ la
#+end_center

Autre exemple, avec deux notes de passage consécutives :

#+begin_center
ré /do si/ la
#+end_center


*** Broderie

La *broderie* quitte une note de l’accord par mouvement conjoint et la
retrouve juste après.

On distingue :

  - la *broderie supérieure*, qui monte d’un degré avant de redescendre
  - la *broderie inférieure*, qui descend d’un degré avant de remonter

Exemple de broderie supérieure :

#+begin_center
do /ré/ do
#+end_center

Exemple de broderie inférieure :

#+begin_center
fa /mi/ fa
#+end_center


**** Double

La *double broderie* combine les broderies supérieure et inférieure.

Exemple :

#+begin_center
do /ré si/ do
#+end_center


*** Échappée

L’ *échappée* quitte une note de l’accord par mouvement conjoint puis
évolue par mouvement disjoint vers une note du même accord ou de
l’accord suivant.

Exemple, le /la/ dans :

#+begin_center
sol /la/ ré
#+end_center


*** Arpège

Un *arpège* consiste à jouer consécutivement une partie ou la totalité
des notes de l’accord en cours. Chaque note peut être répétée, à
l’unisson où à l’octave près.

Les arpèges d’accords à base de tierces sont très utilisés dans la
construction de voix accompagnatrices d’une mélodie principale.

Les arpèges d’accords à base de quintes s’apparentent aux modes
pentaphoniques ou tétraphoniques. Ils sont donc très utilisés dans la
construction de mélodies blues par exemple.


**** Accord brisé

Un *accord brisé* est une généralisation de l’arpège, où plusieurs
notes de l’accord peuvent être jouées simultanément. Les deux termes
sont parfois considérés comme synonymes.


** Ornements répétitifs


*** Trémolo

Un *trémolo* consiste à alterner deux notes. Exemple :

#+begin_center
do sol do sol do sol do sol
#+end_center


**** Basse de Murky

Il s’agit d’un trémolo en octave.


*** Trille

Un *trille* consiste à alterner deux notes séparées par un intervalle
de seconde. Exemple :

#+begin_center
do ré do ré do ré do ré
#+end_center


*** Roulement

Un *roulement* consiste à répéter une même note. Exemple :

#+begin_center
do do do do do do do do
#+end_center


** Combinaisons

Les ornements peuvent être combinés : broderie d’une note de passage,
retard d’une broderie, anticipation d’une note de passage, etc.


* Accords ornementaux

#+TOC: headlines 1 local

** Harmoniques


*** Accord pédale

Un *accord pédale* est un accord maintenu constant sur une partie des
voix pendant que d’autres accords se succèdent sur les autres voix.

Un exemple d’accord-pédale est celui où un même accord est arpégé
inlassablement sur une des voix.


** Mélodiques

#+TOC: headlines 1 local

*** Accord broderie
:PROPERTIES:
:CUSTOM_ID: section:accordBroderie
:END:

Un *accord broderie* est un accord dont au moins une des notes effectue
une broderie par rapport aux notes des accords environnant disposées
sur la même voix.

Le second renversement d’un accord de trois notes peut servir d’accord
de broderie. En effet, il est proche d’un accord dont la fondamentale
est située une quinte plus haut. On le fait donc souvent suivre et/ou
précéder par cet accord. On observe alors les intervalles suivant, par
rapport à la basse :

  - tierce —> quarte —> tierce
  - quinte —> sixte —> quinte

Exemple de broderie d’une triade de fondamentale /do/ :

#+ATTR_HTML: :class plat
| S | : | sol | la | sol |
| A | : | mi  | fa | mi  |
| B | : | do  | do | do  |


*** Accord de passage

Les *accords de passage* ont pour fonction de réaliser une transition
fluide, principalement par mouvements conjoints, entre deux autres
accords.

Exemple :

#+ATTR_HTML: :class plat
| S | : | mi  | ré  | do |
| A | : | sol | sol | la |
| T | : | do  | si  | la |
| B | : | do  | ré  | mi |


**** Échange

Lorsqu’on souhaite échanger deux notes d’un accord tout en opérant par
mouvements conjoints, il est parfois nécessaire d’intercaler un accord
de passage entre la disposition initiale et la disposition finale. À
deux voix, on a par exemple :

#+ATTR_HTML: :class plat
| S | : | mi | ré | do |
| B | : | do | ré | mi |

Dans cet exemple, on échange le soprano et la basse :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | do   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Autre exemple, avec un accord de quatre notes comme point de départ :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | si   | si   | si   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |

Enfin, l’accord final peut aussi comporter quatre notes :

#+ATTR_HTML: :class plat
| S | : | /do/ | /ré/ | /mi/ |
| A | : | do   | si   | la   |
| T | : | sol  | sol  | sol  |
| B | : | /mi/ | /ré/ | /do/ |


**** Suites d’accords de passage

Il est possible d’enchaîner plusieurs accords de passage. On assiste
alors généralement à la formation de portions de gammes diatoniques ou
chromatiques sur une des voix.


* Les consonances adoucissent les dissonances

#+TOC: headlines 1 local

** Introduction

Pour atténuer l’effet d’une note dissonance, on peut s’arranger pour
que cette note forme un intervalle consonant avec au moins une des
autres notes de l’accord.

Par exemple, pour atténuer l’effet du /fa/, qui forme une dissonance
de 7e mineure avec la fondamentale /sol/ dans :

#+ATTR_HTML: :class plat
| S | : | fa  |
| B | : | sol |

on peut ajouter un /ré/, qui est à la fois consonant avec le /fa/
(formant une tierce) et avec le /sol/ (formant une quinte) :

#+ATTR_HTML: :class plat
| S | : | fa  |
| A | : | ré  |
| B | : | sol |


** Accord pédale

Considérons :

  - un accord pédale /P/ consonant sur une partie des voix
  - un accord consonant /A/ sur les autres voix

Si les notes de /P/ ne forment que des consonances avec les notes de
/A/, l’ensemble est consonant.

Si les notes de /P/ forment au moins une dissonance avec les notes de
/A/, l’ensemble produit un effet de dissonance modérée, grâce aux
consonances internes de /P/ et de /A/.

Le résultat dépendra bien entendu du rapport entre le nombre de
consonances et le nombre de dissonances.


* Basse des accords

#+TOC: headlines 1 local

** Pédale

Lorsqu’une pédale est placée à la basse, c’est la voix directement
supérieure qui remplit temporairement le rôle de basse des accords.

Dans le cas d’un quatuor, si une pédale est à la basse ce sera le
ténor qui accueillera la basse des accords.


** Accord pédale

Dans le cas d’un accord pédale, c’est la voix la plus grave parmi
celles qui ne sont pas impliquées dans l’accord pédale qui remplit la
fonction de basse des accords.


* Camouflage
:PROPERTIES:
:CUSTOM_ID: section:camouflage
:END:

#+TOC: headlines 1 local

** Introduction

Il arrive qu’une disposition musicale génère un effet inhabituel,
voire étrange.

Lorsqu’on est confronté à une telle disposition, il existe alors trois
possibilités :

  1. l’éviter complètement
  2. l’appliquer malgré tout, car elle correspond à l’effet désiré
  3. s’arranger pour qu’elle reste discrète

Nous étudions dans ce chapitre les techniques d’insertion discrète
dans une polyphonie.


** Position

Les positions les plus discrètes sont :

  - les voix internes
  - les temps faibles
  - l’intérieur du règne d’un accord
    + éviter le début, au changement d’harmonie


** Diversion

La diversion fait intervenir un autre paramètre (mélodique,
harmonique, rythmique, etc) pour divertir l’oreille, qui prête alors
moins attention à l’agencement que l’on veut placer à l’arrière-plan.


*** Une quarte, ou plus

Lorsqu’on souhaite qu’un lien entre deux objets musicaux proches soit
masqué, on peut intercaler une note afin de produire un intervalle
mélodique important, une quarte ou plus, avec au moins une des notes
environnantes.

Utile pour masquer :

  - les intervalles rapprochés
  - les cadences d’intervalles directes ou parallèles
  - etc


** Asymétrie

Lorsqu’on souhaite qu’un lien entre deux objets musicaux soit discret,
on les place :

  - sur des temps différents dans leurs mesures
  - dans des motifs mélodiques distincts


** Intervalles harmoniques

Un intervalle harmonique sera toujours plus discret s’il n’est pas
plaqué. Il suffit pour cela de faire commencer une des deux notes
avant l’autre.

On peut même aller plus loin et éviter de produire cet intervalle
harmonique. On utilise alors une des techniques suivantes :

  - attendre la fin de la première note avant de jouer la deuxième
  - modifier la disposition de l’accord concerné
  - intercaler une modification de la disposition de l’accord
    + échange
    + changement
  - décaler une des deux notes à un autre moment du règne de l’accord


** Mouvements polyphoniques


*** Direct disjoint

Pour masquer un mouvement direct disjoint, on peut ajouter une ou
plusieurs notes de passage afin de produire un mouvement mélodique
conjoint. Le mouvement mélodique essentiel associé restera disjoint,
mais sera plus discret.

Exemple, on part de :

#+ATTR_HTML: :class plat
| S | : | si  | mi |
| B | : | sol | mi |

et on ajoute la note de passage /fa/, pour obtenir :

#+ATTR_HTML: :class plat
| S | : | si  |      | mi |
| B | : | sol | /fa/ | mi |


* Superposition rythmique

#+TOC: headlines 1 local

** Introduction

Ce chapitre analyse les configurations rythmiques que l’on rencontre
dans une polyphonie.


** Classification


*** Rythmes identiques

Les deux rythmes sont identiques. Exemple :

#+ATTR_HTML: :class plat
| S | : | B N | N N N | Bp |
| B | : | B N | N N N | Bp |


*** Rythmes contrastés

Un rythme est lent, l’autre est rapide. Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | Bp |   |   |
| B | : | N  | N | N | N  | N | N |


*** Rythmes dialogués

Les voix alternent rythmes rapides et lents, afin de laisser à chacune
un « temps de parole ». Exemple :

#+ATTR_HTML: :class plat
| S | : | Bp |   |   | N  | N | N |
| B | : | N  | N | N | Bp |   |   |


*** Rythmes décalés

Les deux rythmes sont décalés. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | — | — | N | — | — | N |


*** Rythmes hybrides

Il s’agit de rythmes alternativement synchronisés et décalés.
Exemples :

#+ATTR_HTML: :class plat
| S | : | N | N | — | N | N | — |
| B | : | N | — | N | N | — | N |

Le même en version fluide :

#+ATTR_HTML: :class plat
| S | : | N | B |   | N | B |   |
| B | : | B |   | N | B |   | N |


*** Rythmes convergents

Ce sont des rythmes contrastés, décalés ou hybrides qui convergent
l’un vers l’autre. Cette situation est très fréquente à l’approche des
fins de phrase, où toutes les voix finissent par ralentir. Exemple :

#+ATTR_HTML: :class plat
| S | : | N | — | N | B |   | N | Bp |
| B | : | N | N | — | N | B |   | Bp |


*** Rythmes fleuris

Il est bien évident que chaque mélodie peut changer de rythme à tout
instant, modifiant du même coup l’agencement rythmique de la
polyphonie. Lorsqu’une superposition de rythmes fait entendre
successivement différentes configurations, on parle de style fleuri.


** Rythmes agrégés

Un rythme agrégé résulte de la condensation en une seule voix des
différents rythmes d’une polyphonie : chaque nouvelle note entamée sur
une des voix est également entamée sur le rythme agrégé. Considérons
par exemple la superposition :

#+ATTR_HTML: :class plat
| S | : | Np | C  |
| B | : | C  | Np |

Pour obtenir le rythme agrégé, on décompose le temps en suivant la
plus petite valeur commune, ici la croche, et on note le début de
chaque note sur le tableau correspondant :

#+ATTR_HTML: :class plat
|        |   | C | C | C | C |
| S      | : | X |   |   | X |
| B      | : | X | X |   |   |
| agrégé | : | X | X |   | X |

On voit qu’aucune note n’est entamée à la troisième croche.
Le rythme agrégé associé est donc :

#+begin_center
C C cs C
#+end_center

ou, en version fluide :

#+begin_center
C N C
#+end_center


*** Binaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| Ν N + Np C         | N C C           |
| Np C + C Np        | C N C           |
| N C C + C N C      | C C C C         |
| N N + C N C        | C C C C         |
|                    |                 |

*** Ternaires

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| B N + N B          | Ν N N           |
| N B + B C C        | N N C C         |
| N C N C + N N N    | N C C C C       |


*** Hybrides

| Rythmes superposés | Rythmes agrégés |
|--------------------+-----------------|
| N N N + Np Np      | N C C N         |
| B N + Np Np        | Np C N          |
| B C C + Np Np      | Np C C C        |
| N B + Np Cp Cp     | N C Cp Cp       |


** Structure rythmique

Le moyen le plus simple permettant d’établir la structure rythmique
d’une polyphonie consiste à assigner un niveau rythmique différent à
chacune des voix. Par exemple, une voix peut jouer une note à chaque
oscillation, une autre à chaque mesure ou pulsation et une troisième à
chaque temps. Dans l’hypothèse d’un quatuor, cela laisse une voix au
rythme totalement libre.

Toutes les variantes de ce schéma sont possibles. Dans les cas
extrêmes, la structure rythmique est répartie sur toutes les voix, sur
une seule, voire sur aucune. Les rythmes eux-mêmes peuvent n’être
qu’approximativement réguliers : l’essentiel est qu’ils établissent
clairement les fondations rythmiques de la polyphonie.

De plus, les rôles des voix peuvent être permutés ou modifiés à tout
moment, ce qui permet de générer une musique vive et variée.


*** Ostinato

L’ostinato est un motif qui se répète en boucle. On peut l’utiliser
pour concentrer le support rythmique en une seule voix, ce qui libère
les rythmes du reste de l’ensemble.

Considérons par exemple une carrure composée de quatre oscillations.
Chaque oscillation est subdivisée en deux pulsations ternaires durant
chacune une blanche pointée. Cette structure correspond au schéma :

#+ATTR_HTML: :class plat
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |
| § | χ | χ | ¶ | χ | χ |

On peut lui associer l’ostinato suivant :

#+ATTR_HTML: :class plat
| Bp    | B N   |
| N N N | B N   |
| Bp    | B N   |
| N N N | N N N |

/Remarque/ : par son coté inlassable, constant dans un environnement
variable, on peut voir un ostinato comme une sorte de pédale rythmique.


*** Percussions

Un autre moyen de mettre en évidence la structure rythmique d’une
oeuvre est d’ajouter des percussions. Les rythmes des voix préalables sont
alors totalement libérés.


** Syncopes


*** Retard harmonique

Un procédé élégant consiste à utiliser une syncope pour produire
un retard harmonique.


*** Syncope d’harmonie

La syncope d’harmonie est un accord entamé sur temps faible, ou partie
faible de temps, et poursuivi sur temps fort, ou partie forte de
temps.
