
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 09 : La chambre des Muses
#+AUTHOR: - chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* De la théorie à la pratique

Ce tome contient quelques compléments d’information pouvant faciliter
le passage de la théorie musicale à la pratique de la composition.


* Composition

#+TOC: headlines 1 local

** Mélodie & rythme

Pour commencer :

  1. Penser un rythme régulier, comme un métronome
  2. Imaginer une mélodie fluide qui s’appuie sur ce rythme
  3. Développer par répétition & imitation

Exemple :

  - chantonner en scandant avec le pied
  - chantonner en marchant
    + chaque pas correspond à un temps

Imaginer :

  - un texte chanté : rythmé et avec une intonation mélodique
  - des sons naturels, avec rythme et mélodie

Phrasé :

  - pyramide rythmique, structure de la carrure
  - ouverture & conclusion

Chant :

  - lien entre la structure rythmique musicale et le phrasé du texte
  - paramètres littéraires et poétiques
  - penser chaque vers comme un parcours sinueux vers la note finale
    de la rime


Architecture :

  - variations
  - constructions
  - figures

Varier la structure rythmique : binaire/ternaire, nombre de temps,
longueur des carrures, etc.

Placer des marches harmoniques avec surprise.

Moduler.


** Harmonie

Choisir les accords permettant d’obtenir les mouvements polyphoniques
les plus élégants possible. Penser aux fonctions tonales et aux
degrés.


** Ornements

Ajouter les ornements mélodiques et harmoniques tout en améliorant la
qualité des lignes mélodiques et des enchaînements.


** Clarté

Pour garantir la clarté et la variété de l’ensemble

  - A chaque instant : un rythme lent, des intermédiaires, un rapide
  - Rythmes lents aux rimes puis anacrouses rapides


* Harmonie
:PROPERTIES:
:CUSTOM_ID: section:harmonie
:END:

#+TOC: headlines 1 local

** Introduction

Ce chapitre a pour but de nous aider à acquérir de bonnes habitudes
dans la pratique de l’écriture polyphonique. À cette fin, certaines
constructions musicales y sont privilégiées, d’autres sont
déconseillées.

Prenons garde toutefois à ne pas en faire des règles rigides : ces
principes sont supposés être mis en oeuvre par défaut, dans un
contexte dépourvu de toute particularité qui nous permettrait
d’orienter la musique vers une autre configuration. Il n’est pas rare
non plus qu’un aspect musical élégant justifie largement l’emploi
d’une disposition alternative.

L’important est de bien connaître l’effet que produira l’application
ou la transgression d’un de ces conseils, afin de pouvoir orienter la
musique dans la direction souhaitée. Une autre possibilité consiste à
faire passer un agencement déconseillé à l’arrière-plan en utilisant
les techniques de [[file:musica-03-clavier.org::#section:camouflage][camouflage]].


** Mélodie

#+TOC: headlines 1 local

*** Septièmes

Les septièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  - sixte mélodique puis seconde mélodique dans le même sens
  - octave mélodique puis seconde mélodique dans le sens opposé


*** Neuvièmes

Les neuvièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  1. octave mélodique puis seconde mélodique dans le même sens
  2. dixième mélodique puis seconde mélodique dans le sens opposé

Les intervalles mélodiques dépassant l’octave étant déconseillés, on
préférera la première solution.


*** Augmentés et diminués

La quarte augmentée parcourue en trois ou quatre notes est de
préférence précédée ou suivie d’une seconde mineure de même direction,
afin de former une quinte juste.


** Intervalles harmoniques

Les dissonances harmoniques équivalentes à l’octave près à la seconde
majeure, c’est-à-dire :

  - l’intervalle de seconde majeure harmonique
  - son renversement, l’intervalle de septième mineure harmonique
  - les redoublements de ces intervalles

ne posent pas de problème particulier.

#+begin_center
⁂
#+end_center

Les dissonances harmoniques équivalentes à l’octave près à la seconde
mineure, c’est-à-dire :

  - l’intervalle de seconde mineure harmonique
  - son renversement, l’intervalle de septième majeure harmonique
  - les redoublements de ces intervalles

sont susceptibles de provoquer des frottements désagréables, et sont
donc à surveiller.


** Écarts des voix

#+TOC: headlines 1 local

*** Harmoniques naturelles

Une disposition élégante consiste à suivre approximativement les
harmoniques naturelles, où les notes sont plus éloignées dans les
graves et plus proches dans les aiguës.

En appliquant ce principe à un quatuor, on obtient, par ordre
décroissant des écarts :

#+begin_center
basse — ténor   >   ténor — alto   >   alto — soprano
#+end_center


*** Écart maximal

On convient généralement d’éviter un écart de plus d’une octave entre
voix adjacentes. Une exception à ce principe, qui découle des
harmoniques naturelles : l’intervalle entre la basse et la voix qui
lui est immédiatement supérieure (le ténor dans un quatuor) peut
dépasser une octave.

Dans le cas d’un quatuor, si l’alto et le ténor sont séparés d’une
octave, on resserre le ténor et la basse à distance de tierce ou moins.


*** Dispositions courantes

Voici les dispositions de voix les plus courantes :

  - régulière : les intervalles sont à peu près égaux entre chaque
    paire de voix adjacentes.
  - basse éloignée, les autres voix resserrées.


** Dispositions


*** Intervalles consécutifs
:PROPERTIES:
:CUSTOM_ID: section:intervallesConsecutifs
:END:


**** Consonances parfaites

Les consonances parfaites consécutives sont généralement déconseillées
dans les traités d’harmonie, car la répétition de ces intervalles
diminue l’indépendance des voix. Cette règle est valable pour tous les
mouvements polyphoniques.

/Remarque/ : des unissons consécutifs entre interprètes se produisent
naturellement lorsque plusieurs chanteurs ou intrumentistes jouent la
même mélodie. Cette orchestration ne pose bien entendu aucun problème,
car ces intervalles sont confinés à l’intérieur d’une seule ligne
mélodique, et il n’y a donc pas réellement d’unissons consécutifs du
point de vue de la polyphonie.


**** Consonances imparfaites

Pour éviter la monotonie, on déconseille :

  - plus de trois tierces consécutives
  - plus de trois sixtes consécutives


*** Intervalles rapprochés

Il est déconseillé d’accentuer des consonances parfaites rapprochées.
On préfère les rendre discrètes en utilisant les techniques de
[[file:musica-04-clavier.org::#section:camouflage][camouflage]].


*** Fausse relation chromatique

La fausse relation chromatique a tendance à mêler les voix concernées
et est donc en général déconseillée. Il existe toutefois des
exceptions.


**** Relais

Lorsqu’on souhaite déplacer un développement mélodique d’une voix à
une autre, la fausse relation chromatique sert de [[file:musica-06-clechant.org::#section:relais][relais]].


**** Sixte napolitaine

La succession du degré 2 abaissé de la sixte napolitaine avec le degré
2 de l’accord de dominante ne pose pas de problème.


**** Septième de dominante

Si l’un des deux accords est une septième de dominante, la fausse
relation chromatique ne pose pas de problème.


*** Fausse relation de triton

La fausse relation de triton est déconseillée dans l’enchaînement des
degrés 5 — 4.

On peut bien sûr la placer discrètement.


** Mouvements

#+TOC: headlines 1 local

*** Parallèle

L’arrivée sur consonance parfaite par mouvement parallèle produit des
unissons, octaves ou quintes consécutives et est donc déconseillée.


*** Direct

L’arrivée sur unisson par mouvement direct est déconseillée.

Lorsqu’un mouvement direct débouche sur une octave ou une quinte, on
préconise les précautions suivantes :

  - si les deux voix sont extrêmes
    + le soprano évolue par mouvement conjoint
    + si le soprano est disjoint
      * la basse évolue par mouvement conjoint
      * le degré du deuxième accord est de préférence un degré fort
  - si au moins une des voix est interne
    + une des voix évolue par mouvement conjoint
    + sinon
      * une des notes de l’intervalle est entendue dans l’accord précédent

Par contre, quitter une consonance parfaite par mouvement direct ne
pose aucun problème.


*** Oblique

L’arrivée sur unisson par mouvement oblique conjoint est déconseillée.

Par contre, quitter un unisson par mouvement oblique conjoint ne pose
aucun problème.


** Accords

#+TOC: headlines 1 local

*** Accord de sixte

Les accords de sixte, premiers renversements des accords parfaits,
sont fréquemment disposés avec la fondamentale au soprano.


*** Septième de dominante

La 3ce est la sensible inférieure de la gamme, qui se résout
normalement en montant vers la tonique.

La 7e est une dissonance qui se résout par mouvement conjoint. Deux
cas sont possibles :

  - si on la fait descendre, on arrive sur la médiante, c’est la
    résolution la plus fréquente

  - si on la fait monter, on retombe sur la tonique, qui est déjà
    entendue dans le mouvement sensible inférieure — tonique

La 7e peut être agrémentée d’une broderie qui passe par la
fondamentale.

Par contre, il est déconseillé de procéder à un échange entre la 7e et
la fondamentale.


*** Neuvième de dominante majeure

La 9e est de préférence placée au-dessus :

  - de la fondamentale
  - de la sensible inférieure

Idéalement, elle forme au moins un intervalle de neuvième avec la
fondamentale.

Si la 9e est sous la sensible inférieure, on conseille de préparer une
des deux notes.

Si la 9e est à la basse, il est préférable de la préparer.

La 9e est une dissonance qui se résout généralement par mouvement
conjoint, en descendant vers la fondamentale.

L’arrivée sur la 9e par mouvement direct disjoint est déconseillée.

L’arrivée sur la 9e par mouvement direct conjoint est déconseillée si
l’accord est renversé.

La sensible inférieure et la 7e se résolvent comme dans l’accord de septième.


*** Neuvième de dominante mineure

Les conseils sont similaires à ceux de la neuvième majeure, avec
quelques nuances.

La 9e se place sans problème sous la sensible inférieure.

Lorsque la fondamentale est supprimée, on peut oublier les règles de
disposition concernant la 7e, la 9e et la sensible inférieure.

Échange fréquent : la 7e et la 9e, avec la fondamentale en note de
passage.


** Dissonances

#+TOC: headlines 1 local

*** Doublure

Supposons qu’une dissonance soit doublée. La double résolution
attendue provoque en ce cas des octaves consécutives, phénomène que
l’on souhaite généralement éviter. Exemple :

#+ATTR_HTML: :class plat
| S | : | si | do |
| B | : | si | do |

Il est donc déconseillé de doubler une note dissonante.

Pour la même raison, on évite de doubler :

  - une note altérée
  - une note intervenant dans un mouvement chromatique
  - une sensible
  - un retard
  - la 7e d’un accord de 4 notes ou plus
  - la 9e d’un accord de 5 notes ou plus
  - la 5te de l’accord de quinte diminuée

Si l’on souhaite malgré tout doubler une dissonance, ou qu’il est
difficile de faire autrement, il est préférable que la doublure
n’évolue pas vers la même note que l’originale.


*** Altérations

Il est déconseillé de faire entendre simultanément une note de la
gamme et son altération.

Il est déconseillé de produire une tierce diminuée par altération.

Dans les accords de sixte précédant une fonction de dominante, la
basse et la 6te sont propices aux altérations, produisant ainsi les
sixtes augmentées des accords de dominante auxiliaire.


** Ornements

#+TOC: headlines 1 local


*** Pédale

Pendant une pédale de dominante, on déconseille la modulation vers la
tonalité mineure ayant la dominante actuelle pour tonique, car on
perdrait ainsi la sensible inférieure et le rôle fonctionnel de
dominante de la pédale.


*** Retard

On peut faire entendre simultanément le retard et sa résolution dans
un des cas suivants :

  - la résolution est à la basse
  - le retard est au-dessus de la résolution et l’accord en cours est
    un accord de sixte

Dans tous les cas, on veille à maintenir une distance minimale entre
le retard et sa résolution :

  - neuvième pour le retard supérieur
  - septième pour le retard inférieur


*** Appogiature

Une appogiature est un retard non préparé. Les conseils sont les mêmes
que pour le retard.


*** Mélodiques

La dissonance harmonique équivalente à la second mineure entre un
ornement mélodique et une autre voix est déconseillée.


** Rythme


*** Syncope d’harmonie

La syncope d’harmonie est déconseillée car elle déstabilise la
structure rythmique d’une polyphonie.


*** Syncope des parties extrêmes

La syncope simultanée au soprano et à la basse est déconseillée, car
ce procédé perturbe la structure rythmique d’une polyphonie.


* Contrepoint

#+TOC: headlines 1 local

** Étymologie

Punctus contra punctum : point contre point, c’est-à-dire note contre
note, car les premières notations musicales utilisaient des points
pour les représenter.


** Principes
:PROPERTIES:
:CUSTOM_ID: section:contrepointPrincipes
:END:


Le *contrepoint* se distingue d’un style polyphonique plus libre en
insistant encore plus sur :

  - la clarté musicale
  - l’indépendance des lignes mélodiques
  - la continuité des lignes mélodiques
  - la minimisation des redondances

#+begin_center
⁂
#+end_center

Ces principes impliquent les règles suivantes :

  - clarté mélodique
    + des intervalles mélodiques justes, majeurs ou mineurs
  - clarté harmonique
    + nombre restreint d’accords
      * accords parfaits
      * 7e de dominante
    + dispositions des accords
      * aussi complets que possible
      * état fondamental ou premier renversement
    + rythme harmonique régulier
      * un accord par mesure
  - indépendance
    + mouvement contraire ou oblique —> consonance parfaite
  - continuité
    + autour des dissonances
  - minimisation des redondances
    + privilégier les variations aux répétitions exactes

Ces règles viennent s’ajouter aux recommandations mélodiques,
harmoniques et rythmiques de base. Gardez à l’esprit que rien ne vous
empêche d’adapter ce cadre à vos goûts particuliers : accords permis,
renversements, redondances, tout peut être considéré comme
paramétrable.


** Règles de base

#+TOC: headlines 1 local

*** Tonalité

On choisit une tonique et un mode naturel.

La première et la dernière note de la basse correspondent à la tonique
utilisée.

On n’emploie pas d’altération qui ferait sortir de la tonalité, sauf
éventuellement dans la cadence finale : si le mode ne possède aucune
sensible, on peut altérer le degré 7 pour faire entendre une sensible
inférieure.


*** Mélodie

  - pas d’unissons mélodiques consécutifs
    + pas plus de deux notes identiques consécutives
  - on ne dépasse pas la sixte mineure mélodique

On privilégie le mouvement conjoint :

  - lors de l’arrivée
    + sur unisson
    + sur octave
  - pour quitter
    + l’unisson
  - autour des dissonances


*** Harmonie

Un accord par mesure.

On emploie l’accord parfait aussi souvent que possible sur les temps
forts, idéalement :

  - complet
    + à partir de 3 voix
  - à l’état fondamental ou au premier renversement

Sur le premier temps de chaque mesure, on l’utilise :

  - complet
    + à partir de 3 voix
  - à l’état fondamental

Lorsque ce n’est pas possible, on peut le rendre incomplet et/ou
utiliser le premier renversement.

À la première et dernière mesure, on peut utiliser :

  - des consonances parfaites
  - un accord parfait de tonique en position fondamentale

A l’avant-dernière mesure :

  - si on utilise le degré 7, il doit être au premier renversement

Un contrepoint est principalement consonant, particulièrement aux
temps forts. Les dissonances ne peuvent apparaître que sur des
ornements :

  - sur temps fort
    + retard
  - sur temps faible ou médian
    + note de passage
    + broderie
  - en cas de pédale à la basse
    * consonant au premier et dernier temps de la pédale
    * consonant ou dissonant entre les deux


*** Dispositions


**** Consonances parfaites

Les consonances parfaites rapprochées doivent être séparées par au
moins le nombre de temps que dure une mesure, entre la fin du premier
intervalle harmonique et le début du deuxième. On peut les rapprocher
dans les cas suivants :

  - le second intervalle n’est pas plaqué
  - on arrive par mouvement contraire sur le second intervalle


**** Consonances imparfaites

Pour éviter la monotonie, on évite de faire entendre plus de trois
consonances imparfaites consécutives.


**** Dissonances

Les dissonances consécutives sont acceptées si le deuxième accord
produit une dissonance équivalente à la seconde majeure :

  - seconde majeure
  - septième mineure
  - neuvième majeure

On évite donc les dissonances harmoniques consécutives équivalentes à
la seconde mineure.


*** Mouvements


**** Consonances parfaites

On essaie autant que possible d’arriver sur une consonance parfaite
par mouvement contraire ou oblique. Les mouvements directs et
parallèles qui débouchent sur :

  - unisson
  - octave
  - quinte
  - un de leur redoublements

sont à éviter.

À deux voix, cette règle est a observer rigoureusement.

À trois voix et plus, un peu de souplesse est nécessaire : le
mouvement direct est autorisé s’il est utilisé avec discrétion et
modération.


**** Contraire disjoint

On évite :

  - le mouvement intérieur disjoint aboutissant sur
    + unisson
    + octave
  - le mouvement extérieur disjoint
    + partant d’un unisson et arrivant sur consonance


**** Direct

On évite le mouvement direct, particulièrement lorsqu’il débouche
sur :

  - une consonance parfaite
    + unisson
    + octave entre les voix extrêmes
    + quinte entre les voix extrêmes
  - une dissonance harmonique équivalente à la seconde mineure

Pour l’arrivée sur seconde majeure, on fait entendre une des deux
notes dans l’accord précédent.


** Espèces

#+TOC: headlines 1 local

*** Introduction

Les contrepoints sont classés en cinq espèces suivant le rythme
utilisé :

  1. rondes
  2. blanches
  3. noires
  4. syncopes
     + 2 blanches par mesure
     + la deuxième blanche de chaque mesure est prolongée par liaison
       avec la première blanche de la mesure suivante
  5. fleuri
     + blanches, noires, syncopes
     + croches, de temps en temps

La dernière mesure ne contient que des rondes à toutes les voix, dans
toutes les espèces.

En présence de rondes et de blanches, la mesure est à deux temps,
chaque temps durant une blanche :

  1. temps fort
  2. temps faible

Si des noires sont ajoutées, la mesure est à quatre temps, chaque
temps durant une noire :

  1. temps fort
  2. temps faible
  3. temps médian
  4. temps faible


*** Règles communes

Les règles suivantes sont d’application dans toutes les espèces :

 - les [[file:musica-04-clavier.org::#section:principes][principes polyphoniques]]
 - les conseils d’écriture en [[#section:harmonie][harmonie]]
 - les [[#section:contrepointPrincipes][principes du contrepoint]]


*** Blanches

Partie en blanches :

  - sur temps forts
    + notes essentielles
  - sur temps faibles
    + notes essentielles
    + notes de passage, broderies
  - première mesure
    + optionnel : une demi-pause avant la première blanche

Les grands intervalles mélodiques masquent :

  - les intervalles rapprochés
  - les arrivées sur consonance parfaite par mouvement direct ou parallèle

On accepte donc :

  - les octaves et quintes rapprochées situées sur les premiers temps
    de deux mesures consécutives, si les blanches de la première
    mesure sont séparées par au moins une quarte mélodique

  - les arrivées sur consonances parfaites qui seraient des cadences
    directes ou obliques sans la présence de la seconde blanche de la
    première mesure, mais qui grâce à celle-ci deviennent des cadences
    contraires ou obliques

    + les deux blanches de la première mesure doivent être séparées
      par au moins une quarte mélodique


*** Noires

Partie en noires :

  - temps forts
    + doivent être consonants
  - temps faibles
    + peuvent être dissonants
  - temps médian
    + peut être dissonant si les temps environnants sont consonants
  - éviter le mouvement disjoint aux changements d’accords
    + c’est-à-dire aux barres de mesures
  - mouvement disjoint accepté autour d’une dissonance
    + entre la deuxième et la troisième noire d’une mesure
      - même si la deuxième noire est dissonante
      - mais à condition que la troisième soit consonante
  - première mesure
    + optionnel : un soupir avant la première noire


*** Syncopes

Chaque blanche commence sur le temps faible de la mesure et est
prolongée par liaison avec une autre blanche sur le temps fort de la
mesure suivante.

La structure de la voix est retardée d’une demi-mesure : la blanche
sur temps faible se trouverait sur temps fort en l’absence de la
prolongation, et vice versa. C’est comme si toute une ligné mélodique
de rondes se trouvait retardée d’une blanche, faisant ainsi entendre
des retards, qui peuvent être consonants ou dissonants. En
conséquence :

  - la blanche sur temps faible doit être consonante
    + sauf si la basse reste constante, en mode pédale
  - la blanche sur temps fort peut être
    + un retard consonant
    + un retard dissonant

Si le retard est dissonant :

  - il se résout par mouvement conjoint
  - de préférence en descendant

Si la résolution est entendue en même temps que le retard :

  - la résolution est à la basse
  - l’intervalle entre retard et résolution est au moins d’une 9e

Autres règles :

  - éviter de produire des unissons ou octaves rapprochés
    + même si le retard s’intercale entre ces intervalles
    + les quintes rapprochées sont tolérées
  - on peut remplacer la liaison par deux blanches distinctes
    + une fois au cours de l’oeuvre
    + une fois à l’avant-dernière mesure
  - on peut aligner plus de trois 3ces ou 6tes consécutives


*** Fleuri

Sur la voix fleurie, on peut utiliser les rondes, blanches, noires et
syncopes, auxquelles on ajoute de temps en temps des croches, mais :

  - sur temps faibles
  - sur partie faible des temps
  - elles évoluent de préférence par mouvement conjoint avec les notes
    environnantes

Les règles en application sont :

  - les principes du contrepoint
  - les règles de base
  - les règles de l’espèce en cours d’utilisation à un instant donné

Une blanche occupant la seconde moitié d’une mesure peut se prolonger
en syncope à la mesure suivante par :

  - une blanche
  - une noire

Ces syncopes sont très élégantes. On peut faire une analogie avec les
mouvements contraire ou oblique, signe d’une indépendance mélodique là
où la syncope est l’illustration d’une indépendance rythmique.

Dans tous les cas, on a les règles suivantes dans la seconde mesure
de la syncope :

  - retard consonant
    + le troisième temps doit être une autre note de l’accord
    + on évite de broder en noires la consonance du premier temps
  - retard dissonant
    + la résolution se fait sur le troisième temps

Autres règles :

  - mesure de deux noires suivies d’une blanche
    + la blanche se prolonge en syncope à la mesure suivante
  - varier le rythme
    + deux mesures consécutives doivent avoir des rythmes différents

Enfin, la première mesure commence par :

  - une demi-pause
  - un soupir


** Deux voix

#+TOC: headlines 1 local

*** Introduction

Les exercices de contrepoint à deux voix sont classés en cinq espèces :

| Espèce | Voix 1 | Voix 2   |
|--------+--------+----------|
|      1 | rondes | rondes   |
|      2 | rondes | blanches |
|      3 | rondes | noires   |
|      4 | rondes | syncopes |
|      5 | rondes | fleuri   |

/Remarque/ : la voix 1 peut être plus grave ou plus aiguë que la voix 2


*** Règles générales à deux voix

  - intervalle harmonique de quarte
    + rappelle l’accord parfait au second renversement
    + on l’évite sur temps fort
  - début et fin : consonances parfaites


*** Rondes

Rondes contre rondes.

Cadence finale :

  - cadence extérieure conjointe : 6te M vers 8ve
  - cadence intérieure conjointe : 3ce m vers 1son
  - on hausse le degré 7 d’un demi-ton si nécessaire
    * produit une sensible inférieure


*** Blanches

Rondes contre blanches.

Cadence finale :

  - extérieure conjointe
    * avant-dernière mesure : 5te puis 6te M
    * dernière mesure : 8ve
  - intérieure conjointe
    * avant-dernière mesure : 5te puis 3ce m
    * dernière mesure : 1son


*** Noires

Rondes contre noires.

Cadence finale :

  - extérieure conjointe
    * avant-dernière mesure, 2 dernières notes : 5te puis 6te M
    * dernière mesure : 8ve
  - intérieure conjointe
    * avant-dernière mesure, 2 dernières notes : 4te puis 3ce m
    * dernière mesure : 1son


*** Syncopes

Rondes contre blanches syncopées.

Cadence finale :

  - extérieure conjointe
    * avant-dernière mesure, dernière note : 6te M
    * dernière mesure : 8ve
  - intérieure conjointe
    * avant-dernière mesure, dernière note : 3ce m
    * dernière mesure : 1son


*** Fleuri

Rondes contre fleuri.


** Trois voix

#+TOC: headlines 1 local

*** Introduction

Les exercices de contrepoint à trois voix sont classés comme suit :

|        Espèce | Voix 1 | Voix 2   | Voix 3   |
|---------------+--------+----------+----------|
|             1 | rondes | rondes   | rondes   |
|             2 | rondes | rondes   | blanches |
|             3 | rondes | rondes   | noires   |
|             4 | rondes | rondes   | syncopes |
|---------------+--------+----------+----------|
| petit mélange | rondes | blanches | noires   |
|               | rondes | noires   | syncopes |
|---------------+--------+----------+----------|
|        Fleuri | rondes | rondes   | fleuri   |
|               | rondes | fleuri   | fleuri   |


*** Règles générales à trois voix

Accord parfait :

  - sur le premier temps de chaque mesure
  - quand c’est possible
    + complet
    + à l’état fondamental
  - on peut doubler n’importe quelle note

Mouvements polyphoniques :

  - éviter le mouvement direct sur les trois voix en même temps

Première et dernière mesure :

  - consonances parfaites
  - accord complet ou incomplet

Entrée des voix :

  - blanches et noires : 8ve ou 5te de l’accord
  - rondes et syncopes : peuvent commencer par la 3ce de l’accord
  - les voix provisoirement les plus grave remplacent la basse
    + elles doivent correspondre à la fondamentale de l’accord

Cadence finale :

  - deux des trois voix évoluent comme dans une cadence à deux voix
  - on peut effectuer un mouvement disjoint sur la troisième voix
    + pour éviter une dissonance sur temps fort à l’avant-dernière mesure
  - les voix forment des intervalles d’1son, d’8ve ou de 5te avec la basse
    + une 3ce est parfois nécessaire

Il est plus aisé de commencer par former un intervalle de tierce avec
les deux premières voix. On dispose alors de quatre solutions pour la
troisième voix :

| 3e voix    | exemple : /do mi/ |
|------------+-------------------|
| 5te        | do mi sol         |
| 6te        | do mi la          |
| doublure 1 | do mi do          |
| doublure 2 | do mi mi          |

Bien entendu, l’ordre des voix peut être modifié pour assurer de bons
mouvements polyphoniques.

Il en va de même lorsque les deux premières voix sont à distance de sixte :

| 3e voix    | exemple : /do la/ |
|------------+-------------------|
| 3ce        | do mi la          |
| 4te        | do fa la          |
| doublure 1 | do do la          |
| doublure 2 | do la la          |

Par contre, si on commence par placer les deux premières voix à
distance de quinte, il ne reste que trois possibilités pour la
troisième voix :

| 3e voix    | exemple : /do sol/ |
|------------+--------------------|
| 3ce        | do mi sol          |
| doublure 1 | do sol do          |
| doublure 2 | do sol sol         |

Il en va de même si on place les deux premières voix à distance de
quarte :

| 3e voix    | exemple : /do fa/ |
|------------+-------------------|
| 6te        | do fa la          |
| doublure 1 | do fa do          |
| doublure 2 | do fa fa          |


*** Syncopes

Deux voix en rondes, une en syncopes.

Décalage :

  - la blanche sur temps faible doit faire partie de l’accord parfait
    présent sur le temps fort aux autres voix

Assouplissements :

  - les quintes rapprochées séparées par un retard sont autorisées


*** Fleuri

On ajoute la blanche pointée aux rythme du fleuri.


** Quatre voix

#+TOC: headlines 1 local

*** Introduction

Les exercices de contrepoint à quatre voix sont classés comme suit :

|        Espèce | Voix 1 | Voix 2   | Voix 3   | Voix 4   |
|---------------+--------+----------+----------+----------|
|             1 | rondes | rondes   | rondes   | rondes   |
|             2 | rondes | rondes   | rondes   | blanches |
|             3 | rondes | rondes   | rondes   | noires   |
|             4 | rondes | rondes   | rondes   | syncopes |
|---------------+--------+----------+----------+----------|
| petit mélange | rondes | rondes   | blanches | noires   |
|               | rondes | rondes   | noires   | syncopes |
|---------------+--------+----------+----------+----------|
| grand mélange | rondes | blanches | noires   | syncopes |
|---------------+--------+----------+----------+----------|
|        Fleuri | rondes | rondes   | rondes   | fleuri   |
|               | rondes | rondes   | fleuri   | fleuri   |
|               | rondes | fleuri   | fleuri   | fleuri   |


*** Règles générales à quatre voix

Disposition :

  - s’inspirer des harmoniques naturelles, voir [[file:musica-03-luth.org::#section:accordsParfaitsDispositions][disposition des accords parfaits]]

Autres règles :

  - éviter le mouvement direct sur les quatre voix en même temps
  - retard & résolution simultanés autorisés si
    + retard au-dessus de la résolution
    + les voix concernées procèdent par mouvement contraire conjoint

Doublure, par ordre décroissant de préférence :

  1. la basse
  2. la note située une tierce au-dessus de la basse
  3. une autre note


*** Syncopes

  - en cas de nécessité, on peut scinder une ronde en deux blanches
    pour maintenir la consonance entre une syncope sur temps faible et
    les autres voix en rondes


** Rythmes ternaires & binaires

Mesure à trois temps : fort - faible - faible

Les rythmes utilisés sont :

  - rondes pointées
  - blanches
  - noires
  - syncopes
     + 3 blanches par mesure
     + la dernière blanche de chaque mesure est liée à la première
       blanche de la mesure suivante, ne formant ainsi qu’une seule
       note qui traverse la barre de mesure
  - fleuri : blanches, noires, syncopes

La dernière mesure ne contient que des rondes pointées à toutes les voix.

Il s’agit d’une structure hybride ternaire et binaire :

  - 1 ronde pointée = 3 blanches
  - 1 blanche = 2 noires

On peut alors construire des espèces analogues aux espèces binaires :
il suffit de remplacer les rondes par des rondes pointées.


* Contrepoint renversable

#+TOC: headlines 1 local

** Introduction

Un contrepoint est *renversable* si ses mélodies peuvent changer de
voix sur la polyphonie tout en continuant à respecter les règles du
contrepoint.

L’opération de changement des voix est appelée *réversion*. Elle
demande une transposition d’au moins une des voix concernées pour
s’adapter à son nouveau registre.

On utilise un rythme fleuri.

Considérons un contrepoint renversable de mélodies /C/ et /R/. Voici
un exemple de réversion :

#+ATTR_HTML: :class plat
| S | : | C | =...= | R |
| B | : | R | =...= | C |

et un autre :

#+ATTR_HTML: :class plat
| S | : | C     | =...= | =...= |
| A | : | R     | =...= | R     |
| B | : | =...= | =...= | C     |

ou encore :

#+ATTR_HTML: :class plat
| S | : | =...= | =...= | R     |
| A | : | C     | =...= | C     |
| B | : | R     | =...= | =...= |


** Parallélisme

On peut ajouter une mélodie parallèle aux mélodies du contrepoint de
départ. Le résultat formera un contrepoint, grâce aux propriétés du
contrepoint renversable.

Considérons un contrepoint renversable de mélodies /C/ et /R/. Voici
un exemple d’ajout de voix parallèle après transposition :

#+ATTR_HTML: :class plat
| S | : | =...= | =...= | R |
| A | : | C     | =...= | C |
| B | : | R     | =...= | R |

et un autre :

#+ATTR_HTML: :class plat
| S | : | C     | =...= | C |
| A | : | R     | =...= | R |
| B | : | =...= | =...= | C |


** Fugué

Un *contrepoint fugué* est un contrepoint renversable composé de deux
mélodies similaires décalées.

Considérons un contrepoint fugué dont la mélodie est composée des
motifs /M/, /N/ et /P/. Voici un exemple d’arrangement :

#+ATTR_HTML: :class plat
| S | : | M | N | P | =...= |
| B | : | — | M | N | P     |

On peut pousser plus loin en utilisant le parallèlisme :

#+ATTR_HTML: :class plat
| S | : | — | — | M | N     | P     |
| A | : | M | N | P | =...= | =...= |
| B | : | — | M | N | P     | =...= |


** Nomenclature

Un contrepoint :

  - double est un contrepoint renversable à deux voix
  - triple est un contrepoint renversable à trois voix
  - quadruple est un contrepoint renversable à quatre voix


** Double

#+TOC: headlines 1 local

*** Introduction

Les deux voix d’un contrepoint double peuvent être permutées.

*** À l’octave

Chaque voix d’un contrepoint double à l’octave peut être élevée ou
abaissée d’une octave tout en continuant à respecter les règles du
contrepoint. Les rôles des voix sont alors inversés.

Voici les correspondances des intervalles, avant et après réversion :

#+ATTR_HTML: :class plat
| Avant | : | 1son | 2de | 3ce | 4te | 5te | 6te |  7e | 8ve  |
| Après | : | 8ve  |  7e | 6te | 5te | 4te | 3ce | 2de | 1son |

Elles sont identiques aux renversements des intervalles, qui les
complètent pour former une octave.

Règles :

  - on ne doit pas dépasser l’octave harmonique, pour ne pas faire
    entendre des intervalles harmoniques équivalents après réversion

  - on ne peut utiliser la 5te harmonique que lors des ornements, car
    elle deviendrait une 4te après réversion, ce qui suggèrerait
    l’accord parfait au second renversement

    + on peut l’utiliser lors d’un retard, d’une note de passage ou
      d’une broderie

  - on évite de faire entendre retard et résolution simultanément, car
    le retard passerait en-dessous de la résolution après réversion


*** À la dixième

Chaque voix d’un contrepoint double à la dixième peut être élevée ou
abaissée d’une dixième tout en continuant à respecter les règles du
contrepoint.

Voici les correspondances des intervalles, avant et après réversion :

#+ATTR_HTML: :class plat
| Avant | : | 1son | 2de | 3ce | 4te | 5te | 6te |  7e | 8ve |  9e |  10e |
| Après | : |  10e |  9e | 8ve |  7e | 6te | 5te | 4te | 3ce | 2de | 1son |

Voici les intervalles qui deviennent consonance parfaite après
réversion :

  - 10e —> 1son
  - 3ce —> 8ve
  - 6te —> 5te

La 10e est le redoublement de la 3ce, et lui est donc équivalente.

Règles :

  - on arrive par mouvement contraire ou oblique sur les intervalles
    qui sont des consonances parfaites ou qui le deviennent après
    réversion

    + 1son, 3ce, 5te, 6te, 8ve

    + on constate que tous les intervalles consonants acceptés sur
      temps forts ou après retard sont concernés

  - on évite les intervalles consécutifs qui deviendraient des
    consonances parfaites consécutives après réversion


*** À la douzième

Chaque voix d’un contrepoint double à la douzième peut être élevée ou
abaissée d’une douzième tout en continuant à respecter les règles du
contrepoint.

Voici les correspondances des intervalles, avant et après réversion :

#+ATTR_HTML: :class plat
| Avant | : | 1son | 2de | 3ce | 4te | 5te | 6te |  7e | 8ve |  9e | 10e | 11e |  12e |
| Après | : |  12e | 11e | 10e |  9e | 8ve |  7e | 6te | 5te | 4te | 3ce | 2de | 1son |

Voici les intervalles qui deviennent consonance parfaite après
réversion :

  - 12e —> 1son
  - 5te —> 8ve
  - 8ve —> 5te

Voici les intervalles consonants qui deviennent dissonant après
inversion des voix :

  - 6te —> 7e

Règles :

  - aux endroits consonants, on évite la 6te, car elle devient
    dissonante après réversion

  - le retard en 7e qui se résout sur une 6te deviendrait un retard en
    6te qui évolue vers une 7e, et est donc à éviter


*** Multiple

Il est possible de réaliser un contrepoint double qui soit renversable
par transposition de plusieurs intervalles, il suffit de respecter
simultanément les règles des intervalles souhaités : 8ve, 10e et/ou
12e.


* Fugue

#+TOC: headlines 1 local


** Étymologie

Fugere & fugare : fuir & poursuivre


** Introduction

La *fugue* développe un thème qui est présenté puis imité sur une
autre voix. L’imitation n’est pas obligatoirement exacte.

Lorsque l’imitation est exacte, on parle de *canon*.


** Sujet

Le thème imité est appelé *sujet*.

Un sujet peut se décomposer en plusieurs éléments :

  - *tête du sujet*

    + début du sujet

    + caractérisé par un motif facilement reconnaissable

  - *centre du sujet*

  - *coda*

    + fin du sujet

    + conçu pour faciliter l’entrée de la réponse

Un sujet est caractérisé par :

  - un rythme fleuri
  - un ambitus maximum de 6te M ou de 7e dim

On veille à :

  - commencer par la 1ale, 3ce ou 5te du ton principal
  - terminer par la 1ale ou 3ce du ton principal, ou sur la dominante


*** Multiple

Une fugue possède un ou plusieurs sujets.

Une fugue :

  - double possède deux sujets
  - triple possède trois sujets
  - etc


** Réponse

Pendant la coda, une autre voix fait entendre la *réponse*, thème qui
imite le sujet transposé.

La transposition s’effectue en général à la quinte supérieure ou à la
quarte inférieure. L’imitation peut être approximative.

Une réponse :

  - commence avec la dernière note du sujet ou juste après
  - entre à l’octave près sur 8ve, 5te, 3ce M/m, 6te M/m

Pour respecter la tonalité, on peut être amener à adapter le sujet
après transposition, en utilisant des [[file:musica-08-clechant.org::#section:mutation][mutations]].


** Contre-sujet

Pendant la réponse, un nouveau thème, appelé *contre-sujet*, est
entendu sur la voix qui a exposé le sujet.

Le contre-sujet est écrit comme un contrepoint de la réponse :

  - le rythme est fleuri
  - si on souhaite le réutiliser tel quel, il doit être renversable
  - l’ajout d’altérations peut être nécessaire


** Cadence

On peut utiliser une cadence pour servir d’entrée à un thème,
typiquement une cadence parfaite.


** Exposition

Une phase d’exposition fait entendre le ou les sujets de la fugue.

Une exposition d’un sujet ressemble à ce schéma :

#+ATTR_HTML: :class plat
| Va | : | tête de sujet | centre du sujet | coda    | contre-sujet | cadence |
| Vb | : |               |                 | réponse | réponse      | cadence |

Une fugue compte en général plusieurs expositions.


*** Contre-exposition

La contre-exposition est une exposition inversée, on fait entendre la
réponse puis le sujet, si possible dans des voix qui sont jusque là
restées silencieuses.


** Entrées


*** À quatre voix

La première entrée du sujet et de la réponse se fait généralement
comme suit :

  - soprano : sujet
  - alto : réponse
  - ténor : sujet
  - basse : réponse


** Autres éléments

  - divertissement modulant
  - strette
  - pédale
    + tonique ou dominante
    + dans la phase finale


** Accords utilisés

  - parfaits majeurs & mineurs
    + état fondamental ou premier renversement
    + second renversement : discrètement
  - accord de 5te dim
  - accord de 5te aug (sur le 3e degré en mineur)
  - accord de 7e diminuée


** Fugue minimaliste

  - exposition
    + sujet
    + réponse & contre-sujet
  - cadence sur la dominante
  - exposition
    + transposée sans altération
    + la réponse peut commencer avant la coda du sujet
  - cadence sur la médiante
  - exposition
    + la réponse commence juste après le début du sujet
  - cadence sur la tonique


** Fugue d’école

Schéma typique d’une fugue d’école :

  - exposition
  - divertissement modulant
  - contre-exposition
  - divertissement modulant
  - sujet au relatif majeur ou mineur
  - réponse à la dominante du relatif
  - divertissement modulant
  - sujet à la sous-dominante
  - réponse à la sous-dominante du relatif
  - divertissement modulant
  - sujet à la dominante
  - pédale de dominante
  - strette : exposition complète
  - divertissement modulant
  - strette du contre-sujet
  - strette plus serré
  - strette très serré : canon
    + dans le ton de l’exposition
  - dernier sujet : pédale de tonique


* Expérimentation personnelle

#+TOC: headlines 1 local

** Introduction

Avis personnels sur les règles présentées dans ce tome.


** Essais

Voici une liste des configurations réputées pour poser problème mais
qui, à mon humble avis, sonnent bien :

  - les consonances parfaites consécutives
    + bien sûr, il ne faut pas en répéter trop consécutivement, pour
      éviter la monotonie, mais c’est valable pour tous les intervalles
  - le départ d’un unisson par mouvement disjoint vers une autre consonance
  - l’arrivée sur consonance parfaite par mouvement direct
    + peut être du plus bel effet


** Conclusion

Si les règles de l’harmonie et du contrepoint sont suffisantes pour
garantir des bases solides, elles ne sont pas toujours nécessaires, et
il est possible de réussir de belles choses en dehors de celles-ci.
Ces règles sont donc d’une aide précieuse, mais ne doivent en aucun
cas constituer un blocage dans la recherche de solutions musicales
aucadieuses.

En résumé, les règles servent à :

  - garantir des enchaînements solides
  - acquérir de bonnes habitudes de base
  - stimuler l’imagination pour trouver des solutions qui respectent
    les règles tout en étant musicalement réussies

D’un autre côté, il ne faut pas hésiter à en sortir quand la fantaisie
vient nous taquiner, car :

  - on peut écrire de belles choses en dehors des règles
  - l’oreille peut aussi stimuler l’imagination dans la recherche de
    solutions créatives et réussies

La musique peut être d’une grande beauté, aussi bien à l’intérieur
qu’à l’extérieur des clôtures. À nous de savoir la reconnaître quand
elle se présente.


* Jazz


** Voicing

  - accord de 7e
    + la 5te peut être supprimée
  - au-dessus : teintures
    + une tierce au-dessus de la 7e : 9e
    + une tierce sous la fondamentae : 13e
  - une des teintures peut se glisser entre les notes de
    l’accord de 7e

Exemple avec /sol si ré fa/ :

  - sans 5te : /sol si fa/
  - au-dessus : /mi/ & /la/
  - résultat : /sol si fa mi la/
  - si on glisse /mi/ dans l’accord de 7e : /sol si mi fa la/


* Instruments

#+TOC: headlines 1 local


** Chant

De la tessiture la plus aiguë à la plus grave :

  - soprano
  - mezzo-soprano
  - alto
  - haute-contre, contralto, contreténor
  - ténor
  - baryton
  - basse


** Cordes

La famille des cordes se subdivise en plusieurs sous-familles :

  - cordes pincées
  - cordes frappées
  - cordes frottées


*** Cordes pincées

De type guitare :

  - guitare
  - mandoline
  - banjo
  - luth
  - théorbe
  - sitar indienne

Sur table :

  - cithare autrichienne
  - guzheng chinois

Avec clavier :

  - clavecin


*** Cordes frappées

  - cymbalum
  - clavicorde, ancêtre du piano
  - pianoforte : proche du piano moderne
  - piano


*** Cordes frottées

De la tessiture la plus aiguë à la plus grave :

  - violon
  - violon alto
  - violoncelle
  - contrebasse


** Bois

Les bois sont des instruments à vent. La famille des bois se subdivise
en plusieurs sous-familles :

  - biseau
  - anche libre
  - anche simple
  - anche double

De la tessiture la plus aiguë à la plus grave :

  - piccolo
  - flûte, flûte traversière
  - clarinette
  - hautbois
  - basson

Les haubois, de la tessiture la plus aiguë à la plus grave :

  - musette, ou hautbois piccolo
  - hautbois en ut
  - hautbois d’amour
  - cor anglais
  - hautbois baryton

Les hautbois baroques, de la tessiture la plus aiguë à la plus grave :

  - musette de cour
  - hautbois baroque
  - hautbois d’amour baroque
  - hautbois da caccia


*** Biseau

  - flûte
  - jeux à bouche d’orgue


*** Anche libre

  - harmonica
  - accordéon


*** Anche simple

  - clarinettes
  - saxophones

/Remarque :/ les saxophones possèdent un système de vibration à anche
simple comme les clarinettes. Bien que construits en métal, ils sont
donc placés parmi les bois


*** Anche double

  - hautbois
  - basson


** Cuivres

Les cuivres sont des instruments à vent qui utilisent la vibration des
lèvres dans une embouchure pour produire un son. La famille des
cuivres contient les trompettes, trombones, cors, clairons, tubas,
etc.

La famille des cuivres se subdivise en plusieurs sous-familles :

  - perce cylindrique
  - perce conique
  - perce hybride

De la tessiture la plus aiguë à la plus grave :

  - trompette
  - cor
  - trombone
  - tuba


*** Perce cylindrique

  - trompette
  - trombone


*** Perce conique

  - clairon
  - tuba


*** Perce hybride

  - cor
  - cornet à piston


** Percussions

Les percussions se caractérisent par leur son libre. Une fois le son
entamé, il est en effet impossible de le contrôler, et en particulier
de l’arrêter. La décroissance du volume dépend donc uniquement de
l’instrument.

Il existe plusieurs sous-famille de percussions :

  - membranophones, ou peaux

  - résonnants

  - bois

  - autres

La fonction principale des percussions est le support rythmique. Il
existe toutefois des instruments percussifs permettant de jouer des
mélodies, comme le xylophone, le balafon, ou le vibraphone.


*** Membraphones

  - tambours
  - caisses
  - tambourins
  - timbales


*** Résonnants

  - vibraphone
  - glockenspiel
  - célesta


*** Bois

  - xylophone
  - balafon
  - marimba


*** Autres

  - cymbales
  - claves
  - castagnettes
  - maracas


** Clavier

Les principaux instruments à clavier :

  - clavecin
  - clavicorde
  - pianoforte
  - piano
  - orgue

 Citons aussi :

  - l’accordéon, qui possède une sorte de clavier
  - le synthétiseur


* Formations musicales

#+TOC: headlines 1 local


** Choeur

Quatuor :

  - soprano
  - alto
  - ténor
  - basse

Septuor :

  - soprano
  - mezzo-soprano
  - alto
  - haute-contre, contralto, contreténor
  - ténor
  - baryton
  - basse


** Cordes frottées

Le célèbre quatuor à cordes :

  - 2 violons
  - violon alto
  - violoncelle

Les quintettes à corde :

  - variante 1
    + 2 violons
    + violon alto
    + violoncelle
    + contrebasse
  - variante 2
    + 2 violons
    + 2 violons alto
    + violoncelle
  - variante 3
    + 2 violons
    + violon alto
    + 2 violoncelles

Mais aussi, pourquoi pas :

  - violon
  - violon alto
  - violoncelle
  - contrebasse


** Bois

Quintette :

  - flûte
  - hautbois
  - clarinette
  - cor anglais
  - basson


** Hybride

Quatuor à cordes & piano :

  - 2 violons
  - violon alto
  - violoncelle
  - piano

Quintette à cordes & piano :

  - 2 violons
  - violon alto
  - violoncelle
  - contrebasse
  - piano


** Petits ensembles


*** Mélodie et Harmonie

Dans les petits ensembles de type quatuor, on peut répartir les rôles
comme suit :

  - par définition, la basse des accords à la Basse, ou une pédale le cas échéant
  - le reste des accords, plaqués ou arpégés, au Ténor
  - une première mélodie au Soprano
  - une seconde mélodie à l'Alto

Les deux voix les plus graves forment alors ce que l’époque baroque
appelait le *continuo*, tandis que les deux voix les plus aiguës
forment un duo mélodique.

Toutes les variantes de ce schéma sont possibles : les rôles des voix
peuvent être permutés à tout moment ; la Basse peut admettre d’autre
notes de l’accord, voire passer d’une fonction principalement
harmonique à un rôle mélodique, le Ténor également ; le Soprano et
l'Alto peuvent abandonner la mélodie pour faire entendre une pédale,
etc.

/Remarque/ : dans le cas où le ténor fait entendre des accords
plaqués, il peut y avoir plus de quatre voix simultanées. Ce n’est
plus alors un quatuor au sens strict, mais un ensemble de quatre
instruments. Dans la musique instrumentale de l’époque baroque, la
basse était jouée par un violoncelle, une contrebasse ou un basson et
le reste du continuo par un clavecin, un luth ou un orgue. Les autres
voix étaient interprétées par des violons ou des flûtes.


* Orchestration

#+TOC: headlines 1 local


** Voix humaine

La voix humaine évolue le plus aisément par mouvements conjoints, avec
de temps en temps des sauts de quinte, quarte ou tierce. Il faut
éviter les intervalles mélodiques de plus d’une sixte mineure, à
l’exception de l’octave qui est accepté.

Les chanteurs doivent respirer, il faut donc placer des silences
réguliers.

La voix humaine est principalement utilisée pour le chant, et
reproduit alors l’intonation naturelle ou expressive d’un texte.


** Guitares & Violons

Les guitares, violons et dérivés effectuent souvent des sauts entre
les cordes à partir d’une position des doigts fixe. Des lignes
composites se forment alors naturellement.


** Bois

Les bois doivent respirer, il faut donc placer des silences réguliers.


** Cuivres

Les cuivres sont à l’aise avec les répétitions de notes. Ils peinent
par contre à effectuer des sauts.

Ces instruments nécessitent beaucoup de souffle, il faut donc prévoir
des silences rapprochés.


* Enveloppe du son

L’enveloppe sonore est une modélisation approximative de l’évolution
du volume du son d’un instrument lorsqu’une note est jouée. Cette
modélisation se compose des étapes suivantes, par ordre
chronologique :

  - *entame* : appui sur une touche d’un clavier, pincement d’une
    corde de guitare, etc

  - *délai* avant que le son ne commence à se faire entendre
    (généralement nul)

  - *attaque* : temps que le son prend pour atteindre sa pleine
    puissance

  - *tenue* : temps durant lequel le son demeure à sa pleine puissance

  - *décrue* : temps pris par le son pour passer de sa pleine
    puissance à un niveau intermédiaire, appelé sous-tenue

  - *sous-tenue* : volume auquel le son demeure jusqu’à ce que le
    musicien arrête la note

  - *évanescence* : temps mis par le son pour devenir inaudible


** Claviers

Pour un piano, on a :

  - un délai nul
  - une attaque très courte
  - une tenue nulle, le son commence à décroître immédiatement
  - une décrue de quelques secondes
  - une sous-tenue nulle
  - une évanescence nulle

Pour un orgue, on a :

  - un délai nul

  - une attaque très courte

  - une tenue infinie, ce qui fait que la décrue et la sous-tenue
    n’apparaissent jamais

  - une évanescence nulle


** Hybride

L’avantage d’un instrument à cordes pincées ou frappées comme le
piano, le clavecin, la guitare, est qu’un accent est placé au début de
chaque note, ce qui permet de mieux les distinguer, surtout lors de
polyphonies rapides. Par contre, lors d’harmonies lentes, la tenue du
son n’est pas suffisante et un instrument comme l’orgue est mieux
adapté. On peut imaginer un instrument hybride, appelons le
*pianorgue*, permettant de s’adapter à ces deux situations :

  - délai nul
  - attaque très brève
  - tenue nulle
  - décrue lente
  - soutenue entre 50% et 90% de la pleine puissance
  - évanescence très brève

Ce genre d’instrument artificiel est notamment réalisable par
synthétiseur ou en musique assistée par ordinateur (MAO).
