
#+STARTUP: showall

#+TITLE: Eclats de vers : Musica 07 :  Chambre des Muses
#+AUTHOR: - chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

* De la théorie à la pratique

Ce tome contient quelques compléments d’information pouvant faciliter
le passage de la théorie musicale à la pratique de la composition.


* Composition

#+TOC: headlines 1 local


** État d’esprit

  - Rythme et mélodie
    1. Penser un rythme régulier, comme un métronome
    2. Imaginer une mélodie fluide qui s’appuie sur ce rythme
  - Imaginer
    + Un texte chanté : rythmé et avec une intonation mélodique
    + Des sons naturels, avec rythme et mélodie


** Harmonie

Penser en terme de fonctions tonales et de degrés. Choisir les accords
permettant d’obtenir les mouvements polyphoniques les plus élégants
possible.


** Ornements

Ajouter les arpèges, pédales, anticipations, retards, appogiatures
tout en améliorant la qualité des lignes mélodiques.

Ajouter les notes de passage, broderies, etc.

Ajouter les trémolos, trilles.


** Chant

Penser au lien entre la structure rythmique et le phrasé, aux
paramètres littéraires et poétiques.


** Architecture

Utiliser :

  - Variations
  - Constructions
  - Figures

Varier la structure rythmique : binaire/ternaire, nombre de temps,
longueur des carrures, etc.

Placer des marches harmoniques avec surprise.

Moduler.


* Conseils d’écriture
:PROPERTIES:
:CUSTOM_ID: section:conseilsDEcriture
:END:

#+TOC: headlines 1 local


** Introduction

Ce chapitre a pour but de nous aider à acquérir de bonnes habitudes
dans la pratique de l’écriture polyphonique. À cette fin, certaines
constructions musicales y sont privilégiées, d’autres sont
déconseillées.

Prenons garde toutefois à ne pas en faire des règles rigides : ces
principes sont supposés être mis en oeuvre par défaut, dans un
contexte dépourvu de toute particularité qui nous permettrait
d’orienter la musique vers une autre configuration. Il n’est pas rare
non plus qu’un aspect musical élégant justifie largement l’emploi
d’une disposition alternative.

L’important est de bien connaître l’effet que produira l’application
ou la transgression d’un de ces conseils, afin de pouvoir orienter la
musique dans la direction souhaitée. Une autre possibilité consiste à
faire passer un agencement déconseillé à l’arrière-plan en utilisant
les techniques de [[file:musica-03-clavier.org::#section:camouflage][camouflage]].


** Mélodie

#+TOC: headlines 1 local

*** Septièmes

Les septièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  - sixte mélodique puis seconde mélodique dans le même sens
  - octave mélodique puis seconde mélodique dans le sens opposé


*** Neuvièmes

Les neuvièmes parcourues en trois notes incluent de préférence un
mouvement conjoint. On dispose donc des solutions suivantes :

  1. octave mélodique puis seconde mélodique dans le même sens
  2. dixième mélodique puis seconde mélodique dans le sens opposé

Les intervalles mélodiques dépassant l’octave étant déconseillés, on
préférera la première solution.


*** Triton

La quarte augmentée parcourue en trois notes est suivie de préférence
d’une seconde mineure de même direction, afin de former une quinte
juste en quatre notes.


** Intervalles harmoniques

Les dissonances harmoniques équivalentes à l’octave près à la seconde
majeure, c’est-à-dire :

  - l’intervalle de seconde majeure harmonique
  - son renversement, l’intervalle de septième mineure harmonique
  - les redoublements de ces intervalles

ne posent pas de problème particulier.

#+begin_center
⁂
#+end_center

Les dissonances harmoniques équivalentes à l’octave près à la seconde
mineure, c’est-à-dire :

  - l’intervalle de seconde mineure harmonique
  - son renversement, l’intervalle de septième majeure harmonique
  - les redoublements de ces intervalles

sont à surveiller.


** Écarts des voix

#+TOC: headlines 1 local

*** Harmoniques naturelles

Une disposition élégante consiste à suivre approximativement les
harmoniques naturelles, où les notes sont plus éloignées dans les
graves et plus proches dans les aiguës.

En appliquant ce principe à un quatuor, on obtient, par ordre
décroissant des écarts :

#+begin_center
basse — ténor   >   ténor — alto   >   alto — soprano
#+end_center


*** Écart maximal

On convient généralement d’éviter un écart de plus d’une octave entre
voix adjacentes. Une exception à ce principe, qui découle des
harmoniques naturelles : l’intervalle entre la basse et la voix qui
lui est immédiatement supérieure (le ténor dans un quatuor) peut
dépasser une octave.

Dans le cas d’un quatuor, si l’alto et le ténor sont séparés d’une
octave, on resserre le ténor et la basse à distance de tierce ou moins.


*** Dispositions courantes

Voici les dispositions de voix les plus courantes :

  - régulière : les intervalles sont à peu près égaux entre chaque
    paire de voix adjacentes.
  - basse éloignée, les autres voix resserrées.


** Mouvements

#+TOC: headlines 1 local

*** Oblique

L’arrivée sur unisson par mouvement oblique conjoint est déconseillée.

Quitter l’unisson par mouvement direct (conjoint ou disjoint) ne pose
aucun problème.


*** Direct

L’arrivée sur unisson par mouvement direct est déconseillé.

Lorsqu’un mouvement direct débouche sur une octave ou une quinte :

  - on veille généralement à ce que l’une des voix évolue par
    mouvement conjoint

    + sinon, on fait entendre une des notes de l’intervalle dans
      l’accord précédent

  - si le mouvement direct à lieu entre les voix extrêmes, la voix
    conjointe est de préférence le soprano.


*** Consécutif
:PROPERTIES:
:CUSTOM_ID: section:conseilsMouvementConsecutif
:END:


**** Consonances parfaites

Les unissons, octaves et quintes consécutifs sont généralement
déconseillés dans les traités d’harmonie, car la répétition de ces
intervalles diminue l’indépendance des voix.

Toutefois, ce conseil est à relativiser : lorsque deux mélodies sont
parallèles, l’une étant transposée suivant l’un de ces intervalles, on
assiste naturellement à la formation d’unissons, d’octaves ou de
quintes parallèles, et donc consécutifs. L’organum strict, une des
premières formes de polyphonie, a utilisé abondamment ce principe
pendant plusieurs siècles

En pratique, si vous souhaiter utiliser des consonances parfaites
consécutives sans trop les exposer, vous pouvez utiliser les
techniques de [[file:musica-03-clavier.org::*Camouflage][camouflage]].


**** Consonances imparfaites

Pour éviter la monotonie, on déconseille :

  - plus de trois tierces consécutives
  - plus de trois sixtes consécutives


*** Fausse relation chromatique

La fausse relation chromatique a tendance à mêler les voix concernées
et est donc en général déconseillée. Il existe toutefois des
exceptions.


**** Relais

Lorsqu’on souhaite déplacer un développement mélodique d’une voix à
une autre, la fausse relation chromatique sert de [[file:musica-06-clechant.org::#section:relais][relais]].


**** Sixte napolitaine

La succession du degré 2 baissé de la sixte napolitaine avec le degré
2 de l’accord de dominante ne pose pas de problème.


**** Septième de dominante

Si l’un des deux accords est une septième de dominante, la fausse
relation chromatique ne pose pas de problème.


*** Fausse relation de triton

La fausse relation de triton est déconseillée dans l’enchaînement des
degrés 5 et 4.


** Harmonie

#+TOC: headlines 1 local

*** Accord de sixte

Les accords de sixte, premiers renversements des accords parfaits,
sont fréquemment disposés avec la fondamentale au soprano.

Les suppressions sont déconseillées.


*** Septième de dominante

La 3ce est la sensible inférieure de la gamme, qui se résout
normalement en montant vers la tonique.

La 7e est une dissonance qui se résout par mouvement conjoint. Deux
cas sont possibles :

  - si on la fait descendre, on arrive sur la médiante, c’est la
    résolution la plus fréquente

  - si on la fait monter, on retombe sur la tonique, qui est déjà
    entendue dans le mouvement sensible inférieure — tonique

La 7e peut être agrémentée d’une broderie qui passe par la
fondamentale.

Par contre, il est déconseillé de procéder à un échange entre la 7e et
la fondamentale.


*** Septième d’espèce

La préparation se fait de préférence par intégration. Idéalement, la
durée de la préparation est au moins égale à la durée de la note de 7e.


*** Neuvième de dominante majeure

La 9e est de préférence placée au-dessus :

  - de la fondamentale
  - de la sensible inférieure

Idéalement, elle forme au moins un intervalle de neuvième avec la
fondamentale.

Si la 9e est sous la sensible inférieure, on conseille de préparer une
des deux notes.

Si la 9e est à la basse, il est préférable de la préparer.

La 9e est une dissonance qui se résout généralement par mouvement
conjoint, en descendant vers la fondamentale.

L’arrivée sur la 9e par mouvement direct disjoint est déconseillée.

L’arrivée sur la 9e par mouvement direct conjoint est déconseillée si
l’accord est renversé.

La sensible inférieure et la 7e se résolvent comme dans l’accord de septième.


*** Neuvième de dominante mineure

Les conseils sont similaires à ceux de la neuvième majeure, avec
quelques nuances.

La 9e se place sans problème sous la sensible inférieure.

Lorsque la fondamentale est supprimée, on peut oublier les règles de
disposition concernant la 7e, la 9e et la sensible inférieure.

Échange fréquent : la 7e et la 9e, avec la fondamentale en note de
passage.


** Dissonances

#+TOC: headlines 1 local

*** Voix

Une dissonance se trouve habituellement sur la même voix que sa
résolution. On peut toutefois procéder à un échange de voix simultanée
à une résolution ordinaire, produisant ainsi un effet inattendu.


*** Résolution irrégulière

Lorsqu’il n’est pas possible de procéder à un mouvement obligé, il est
préférable de quitter la dissonance par mouvement conjoint.


*** Doublure

Supposons qu’une dissonance soit doublée. La double résolution
attendue provoque en ce cas des octaves consécutives, phénomène que
l’on souhaite généralement éviter. Exemple :

#+ATTR_HTML: :class plat
| S | : | si | do |
| B | : | si | do |

Il est donc déconseillé de doubler une note dissonante.

Pour la même raison, on évite de doubler :

  - une note altérée
  - une note intervenant dans un mouvement chromatique
  - une sensible
  - la 7e d’un accord de 4 notes ou plus
  - la 9e d’un accord de 5 notes ou plus
  - la 5te de l’accord de quinte diminuée

Si l’on souhaite malgré tout doubler une dissonance, ou qu’il est
difficile de faire autrement, il est préférable que la doublure
n’évolue pas vers la même note que l’originale.

La dissonance et sa doublure sont de préférence :

  - amenées par mouvement contraire ou oblique
  - quittées par mouvement contraire


**** Préparation

Si une note de préparation est doublée, on quitte de préférence cette
note et sa doublure par mouvement contraire ou oblique.


**** Résolution

Si la note de résolution est doublée, on amène de préférence cette
note et sa doublure par mouvement contraire.

L’arrivée sur résolution par mouvement oblique est déconseillée.


*** Altérations

Il est déconseillé de faire entendre simultanément une note de la gamme et son
altération.

Il est déconseillé de produire une tierce diminuée par altération.

Dans les accords de sixte précédant une fonction de dominante, la
basse et la 6te sont propices aux altérations, produisant ainsi les
sixtes augmentées des accords de dominante auxiliaire.


** Ornements

#+TOC: headlines 1 local


*** Pédale

Pendant une pédale de dominante, on déconseille la modulation vers la
tonalité mineure ayant la dominante actuelle pour tonique, car on
perdrait ainsi la sensible inférieure et le rôle fonctionnel de
dominante de la pédale.


*** Retard


**** Préparation

La préparation se fait de préférence par intégration.

Pendant l’accord de préparation, afin de ne pas gâcher l’effet de
surprise, il est déconseillé de faire entendre simultanément le retard
et sa note de résolution.

On peut cependant l’envisager si les conditions suivantes sont
réunies :

  - la note de résolution est sous le retard
  - la note de résolution est placée sur une voix interne
  - l’intervalle harmonique entre retard et résolution est au moins égal à la septième

Idéalement, la durée de la préparation est au moins égale à la durée
du retard.


**** Phase active

Il est déconseillé de jouer simultanément le retard et sa résolution,
sauf si le retard est au moins à distance de septième au-dessus de la
résolution et qu’une des conditions suivantes est respectée :

  - la résolution est à la basse
  - l’accord en cours est un accord de sixte


*** Appogiature

Une appogiature est un retard non préparé. Les conseils sont les mêmes
que pour la phase active du retard.


*** Mélodiques

La dissonance harmonique équivalente à la second mineure entre un
ornement mélodique et une autre voix est déconseillée.


** Rythme


*** Syncope d’harmonie

La syncope d’harmonie est déconseillée car elle déstabilise la
structure rythmique d’une polyphonie.


*** Syncope des parties extrêmes

La syncope simultanée au soprano et à la basse est déconseillée, car
ce procédé perturbe la structure rythmique d’une polyphonie.


* Contrepoint

#+TOC: headlines 1 local


** Introduction

Le *contrepoint* se distingue d’un style polyphonique plus libre par :

  - la clarté musicale
  - la continuité des lignes mélodiques
  - l’indépendance des lignes mélodiques
  - la minimisation des redondances

#+begin_center
⁂
#+end_center

Ces principes impliquent les règles suivantes :

  - la clarté mélodique
    + des intervalles mélodiques justes, majeurs ou mineurs
  - la clarté harmonique
    + nombre restreint d’accords : accords parfaits, 7e de dominante
    + accords aussi complets que possible
    + état fondamental ou premier renversement
    + rythme harmonique régulier (un accord par mesure)
  - la continuité
    + la prédominance du mouvement conjoint
  - l’indépendance des lignes mélodiques
  - la minimisation des redondances

Ces règles viennent s’ajouter aux recommandations mélodiques,
harmoniques et rythmiques de base. Gardez à l’esprit que rien ne vous
empêche d’adapter ce cadre à vos goûts particuliers : accords permis,
renversements, redondances, tout peut être considéré comme
paramétrable.


** Mélodie


*** Unisson

On évite de répéter une note, c’est-à-dire l’unisson mélodique.

À partir de cinq voix, on peut répéter une fois une note par voix.


*** Disjoint

Un mouvement disjoint est de préférence précédé par un intervalle
mélodique de sens contraire.

On évite l’excès de mouvements disjoints (et particulièrement les
tierces mélodiques) aux changements d’harmonie.

Le saut d’octave doit être précédé /et/ suivi par un mouvement
mélodique de sens contraire.


*** En trois notes

On évite de parcourir une septième ou une neuvième mélodique en trois notes.


*** Augmentés et diminués

On évite les intervalles mélodiques augmentés ou diminués.

Le triton mélodique (qu’il soit parcouru en trois ou quatre notes),
doit être précédé ou suivi d’un mouvement conjoint de même direction.

La quinte augmentée mélodique parcourue en quatre notes doit être
suivie par un mouvement conjoint de même direction.

La quinte augmentée parcourue en deux tierces mélodiques doit être évitée.


** Harmonie


*** Mesure

Un accord par mesure.

Premier temps de chaque mesure :

  - accord parfait
  - accord de quinte diminuée au premier renversement

Première et dernière mesure : accord parfait de tonique en position
fondamentale.

Avant dernière mesure :

  - accord de dominante
    + état fondamental
    + premier renversement
  - accord du degré 7 au premier renversement
  - accord du degré 2 avec sensible en note de passage


*** Unisson

L’unisson harmonique :

  - est à éviter au premier temps de chaque mesure
  - est autorisé à la première et à la dernière mesure
  - est autorisé dans le contrepoint à cinq voix


** Mouvements


*** Consécutif

Octaves et quintes consécutives doivent être séparée par au moins le
nombre de temps que dure une mesure. Autrement dit, il ne peut pas
réapparaître au même temps dans la mesure suivante, mais seulement au
temps qui suit, ou plus tard. On peut les rapprocher si :

  - le second intervalle n’est pas plaqué
  - on arrive par mouvement contraire sur le second intervalle

Les dissonances consécutives sont acceptées si le deuxième accord
produit une dissonance équivalente à la seconde majeure :

  - seconde majeure
  - septième mineure
  - neuvième majeure

On évite donc les dissonances harmoniques équivalentes à la seconde
mineure.

Pour éviter la monotonie, on évite de faire entendre plus de trois :

  - tierces consécutives
  - quartes consécutives
  - sixtes consécutives


*** Parallèle

Les arrivées sur consonance parfaite par mouvement parallèle sont des
cas particuliers d’unissons, octaves ou quintes consécutifs, et sont
donc déconseillées.


*** Direct

On évite le mouvement direct.

On l’évite encore plus lorsqu’il débouche sur :

  - une consonance parfaite
    + unisson
    + octave entre les voix extrêmes
    + quinte entre les voix extrêmes
  - une dissonance harmonique équivalente à la seconde mineure

Pour l’arrivée sur seconde majeure, on fait entendre une des deux
notes dans l’accord précédent.


*** Croisement

Le croisement est autorisé :

  - à partir de trois voix
  - pour des durées brèves


** Ornements

Ornements :

  - au premier temps de la mesure
    + retard supérieur
  - ensuite
    + note de passage
    + broderie


** Imitatif

Dans un contrepoint imitatif, les thèmes musicaux les plus marquants
sont repris de voix en voix, à l’état original ou sous forme de
variation. Ceci n’est nullement en contradiction avec l’esprit du
contrepoint du moment que les voix restent globalement indépendantes.


** Espèces


*** Rythmes binaires

Les rythmes utilisés sont :

  - rondes
  - blanches
  - noires
  - syncopes de blanches
  - fleuri : blanches, noires, syncopes de blanches

La dernière mesure ne contient que des rondes à toutes les voix, dans
toutes les espèces.

En présence de rondes et de blanches, la mesure est à deux temps :

  1. temps fort
  2. temps faible

Si des noires sont ajoutées, la mesure est à quatre temps :

  1. temps fort
  2. temps faible
  3. temps médian
  4. temps faible


*** Deux voix

Les exercices de contrepoint à deux voix sont classés en cinq espèces :

| Espèce | Voix 1 | Voix 2               |
|--------+--------+----------------------|
|      1 | rondes | rondes               |
|      2 | rondes | blanches             |
|      3 | rondes | noires               |
|      4 | rondes | syncopes de blanches |
|      5 | rondes | fleuri               |

/Remarque/ : la voix 1 peut être plus grave ou plus aiguë que la voix 2


Règles particulières à deux voix :

  - première mesure : consonance parfaite
  - dernière mesure : unisson on octave

Deuxième espèce :

  - partie en blanches
    + première mesure
      * un silence puis une consonance parfaite
    + sur temps forts : notes essentielles
    + sur temps faibles : notes de passage, broderies

Troisième espèce :

  - partie en noires
    + première mesure
      * un silence puis trois noires
      * la première noire forme une consonance parfaite avec l’autre voix

Quatrième espèce :

  - partie en blanches syncopées
    + première mesure
      * demi-pause puis blanche
    + chaque blanche commence sur le temps faible de la mesure et est
      liée à une autre blanche sur le temps fort de la mesure suivante
    + la partie sur le temps fort constitue de préférence
      * un retard supérieur résolu par mouvement conjoint descendant
      * une note réelle
      * un retard inférieur consonant
	- formant quinte avec l’autre voix
	- qui se résout en faisant sixte avec l’autre voix
    + on peut remplacer la syncope par deux blanches distinctes
      * une fois au cours de l’oeuvre
      * une fois à l’avant-dernière mesure
  - autres
    + si la résolution est entendue en même temps que le retard
      * la résolution est à la basse
      * l’intervalle entre retard et résolution est au moins d’une 9e
    + on peut aligner plus de trois 3ces ou 6tes consécutives

Fleuri :

  - varier le rythme
    + deux mesures consécutives doivent avoir des rythmes différents
  - mesure : 2 noires & 1 blanche
    + la blanche se prolonge en syncope à la mesure suivante


*** Trois voix

|        Espèce | Voix 1 | Voix 2   | Voix 3               |
|---------------+--------+----------+----------------------|
|             1 | rondes | rondes   | rondes               |
|             2 | rondes | rondes   | blanches             |
|             3 | rondes | rondes   | noires               |
|             4 | rondes | rondes   | syncopes de blanches |
|---------------+--------+----------+----------------------|
| Petit mélange | rondes | blanches | noires               |
|               | rondes | noires   | syncopes de blanches |
|---------------+--------+----------+----------------------|
|        Fleuri | rondes | rondes   | fleuri               |
|               | rondes | fleuri   | fleuri               |


Règles particulières à trois voix :

  - entrée des voix
    + blanches et noires : octave ou quinte de l’accord
    + rondes et syncopes : peuvent commencer par la tierce de l’accord
    + les basses provisoires doivent correspondre à la fondamentale
  - accord complet
    + sur le premier temps de chaque mesure
    + à l’avant-dernière mesure
  - accords incomplets
    + première et dernière mesure
      * on peut supprimer la quinte ou la tierce des accords
    + ailleurs, deux accords incomplets maximum dans l’oeuvre


*** Quatre voix

|        Espèce | Voix 1 | Voix 2   | Voix 3   | Voix 4               |
|---------------+--------+----------+----------+----------------------|
|             1 | rondes | rondes   | rondes   | rondes               |
|             2 | rondes | rondes   | rondes   | blanches             |
|             3 | rondes | rondes   | rondes   | noires               |
|             4 | rondes | rondes   | rondes   | syncopes de blanches |
|---------------+--------+----------+----------+----------------------|
| Petit mélange | rondes | rondes   | blanches | noires               |
|               | rondes | rondes   | noires   | syncopes de blanches |
|---------------+--------+----------+----------+----------------------|
| Grand mélange | rondes | blanches | noires   | syncopes de blanches |
|---------------+--------+----------+----------+----------------------|
|        Fleuri | rondes | rondes   | rondes   | fleuri               |
|               | rondes | rondes   | fleuri   | fleuri               |
|               | rondes | fleuri   | fleuri   | fleuri               |


*** Rythmes ternaires & binaires

Mesure à trois temps : fort - faible - faible

Les rythmes utilisés sont :

  - rondes pointées
  - blanches
  - noires
  - syncopes de blanches
  - fleuri : blanches, noires, syncopes de blanches

La dernière mesure ne contient que des rondes pointées à toutes les voix.

Il s’agit d’une structure hybride ternaire et binaire :

  - 1 ronde pointée = 3 blanches
  - 1 blanche = 2 noires

On peut alors construire des espèces analogues aux espèces binaires :
il suffit de remplacer les rondes par des rondes pointées.


** Renversable

Un contrepoint est renversable si on peut modifier l’ordre des voix
(de la plus grave à la plus aiguë) tout en continuant à respecter les
règles que l’on s’est fixé.

Ces contrepoints portent des noms particuliers suivant le nombre de
voix utilisées :

| Nombre de voix | Nom       |
|----------------+-----------|
|              2 | double    |
|              3 | triple    |
|              4 | quadruple |


* Fugue

#+TOC: headlines 1 local


** Exposition

#+ATTR_HTML: :class plat
| A | : | tête de sujet | sujet | coda    | contre-sujet |
| B | : |               |       | réponse | réponse      |


*** Sujet

  - Trois éléments

    + Tête du sujet : motif caractéristique

  - Unité rythmique : pas trop de rythmes différents

  - Ambitus maximum de 6te M ou de 7e dim

  - Clarté harmonique

  - Commence par la fondamentale, 3ce ou 5te du ton principal

  - Se termine par la fondamentale, 3ce du ton principal ou sur la dominante


*** Réponse

  - Commence avec la dernière note du sujet ou juste après

  - Entre sur 8ve, 5te, 3ce M/m, 6te M/m


**** Transposée

  - À la 5te supérieure

  - Mutation : notes transposées d’une 4te et non d’une 5te

    + Tête de sujet commençant par la dominante ou la sensible inférieure

    + Tête de sujet allant vers la dominante

    + Modulation à la dominante dans le sujet


*** Coda

Court passage qui peut être ajouté pour faciliter l’entrée de la réponse.


** Contre-exposition

Exposition inversée : réponse puis sujet dans des voix qui sont jusque
là restée silencieuses.

Optionnel.


** Autres éléments

  - Divertissement modulant
  - Strette
  - Pédale : tonique ou dominante



** Accords utilisés

  - Parfaits majeurs & mineurs

    + État fondamental ou premier renversement

    + Second renversement : discrètement

  - Accord de 5te dim

  - Accord de 5te aug (sur le 3e degré en mineur)

  - Accord de 7e diminuée


** Schéma

  - Exposition
  - Divertissement
  - Contre-exposition
  - Divertissement
  - Sujet au relatif majeur ou mineur
  - Réponse à la dominante du relatif
  - Divertissement
  - Sujet à la sous-dominante
  - Réponse à la sous-dominante du relatif
  - Divertissement
  - Sujet à la dominante
  - Pédale de dominante
  - Strette : exposition complète
  - Divertissement
  - Strette du contre-sujet
  - Strette plus serré
  - Strette très serré : canon
    + Dans le ton de l’exposition
  - Dernier sujet : pédale de tonique


* Jazz


** Voicing

  - Accord de 7e

    + La 5te peut être supprimée

  - Au-dessus : teintures

    + Une tierce au-dessus de la 7e : 9e

    + Une tierce sous la fondamentae : 13e

  - Une des teintures peut se glisser entre les notes de
    l’accord de 7e


Exemple avec /sol si ré fa/ :

  - Sans 5te : /sol si fa/

  - Au-dessus : /mi/ & /la/

  - Résultat : /sol si fa mi la/

  - Si on glisse /mi/ dans l’accord de 7e : /sol si mi fa la/


* Instruments

#+TOC: headlines 1 local


** Chant

De la tessiture la plus aiguë à la plus grave :

  - soprano
  - mezzo-soprano
  - alto
  - haute-contre, contralto, contreténor
  - ténor
  - baryton
  - basse


** Cordes

La famille des cordes se subdivise en plusieurs sous-familles :

  - cordes pincées
  - cordes frappées
  - cordes frottées


*** Cordes pincées

De type guitare :

  - guitare
  - mandoline
  - banjo
  - luth
  - théorbe
  - sitar indienne

Sur table :

  - cithare autrichienne
  - guzheng chinois

Avec clavier :

  - clavecin


*** Cordes frappées

  - cymbalum
  - clavicorde, ancêtre du piano
  - pianoforte : proche du piano moderne
  - piano


*** Cordes frottées

De la tessiture la plus aiguë à la plus grave :

  - violon
  - violon alto
  - violoncelle
  - contrebasse


** Bois

Les bois sont des instruments à vent. La famille des bois se subdivise
en plusieurs sous-familles :

  - biseau
  - anche libre
  - anche simple
  - anche double

De la tessiture la plus aiguë à la plus grave :

  - piccolo
  - flûte, flûte traversière
  - clarinette
  - hautbois
  - basson

Les haubois, de la tessiture la plus aiguë à la plus grave :

  - musette, ou hautbois piccolo
  - hautbois en ut
  - hautbois d’amour
  - cor anglais
  - hautbois baryton

Les hautbois baroques, de la tessiture la plus aiguë à la plus grave :

  - musette de cour
  - hautbois baroque
  - hautbois d’amour baroque
  - hautbois da caccia


*** Biseau

  - flûte
  - jeux à bouche d’orgue


*** Anche libre

  - harmonica
  - accordéon


*** Anche simple

  - clarinettes
  - saxophones

/Remarque :/ les saxophones possèdent un système de vibration à anche
simple comme les clarinettes. Bien que construits en métal, ils sont
donc placés parmi les bois


*** Anche double

  - hautbois
  - basson


** Cuivres

Les cuivres sont des instruments à vent qui utilisent la vibration des
lèvres dans une embouchure pour produire un son. La famille des
cuivres contient les trompettes, trombones, cors, clairons, tubas,
etc.

La famille des cuivres se subdivise en plusieurs sous-familles :

  - perce cylindrique
  - perce conique
  - perce hybride

De la tessiture la plus aiguë à la plus grave :

  - trompette
  - cor
  - trombone
  - tuba


*** Perce cylindrique

  - trompette
  - trombone


*** Perce conique

  - clairon
  - tuba


*** Perce hybride

  - cor
  - cornet à piston


** Percussions

Les percussions se caractérisent par leur son libre. Une fois le son
entamé, il est en effet impossible de le contrôler, et en particulier
de l’arrêter. La décroissance du volume dépend donc uniquement de
l’instrument.

Il existe plusieurs sous-famille de percussions :

  - membranophones, ou peaux

  - résonnants

  - bois

  - autres

La fonction principale des percussions est le support rythmique. Il
existe toutefois des instruments percussifs permettant de jouer des
mélodies, comme le xylophone, le balafon, ou le vibraphone.


*** Membraphones

  - tambours
  - caisses
  - tambourins
  - timbales


*** Résonnants

  - vibraphone
  - glockenspiel
  - célesta


*** Bois

  - xylophone
  - balafon
  - marimba


*** Autres

  - cymbales
  - claves
  - castagnettes
  - maracas


** Clavier

Les principaux instruments à clavier :

  - clavecin
  - clavicorde
  - pianoforte
  - piano
  - orgue

 Citons aussi :

  - l’accordéon, qui possède une sorte de clavier
  - le synthétiseur


* Formations musicales

#+TOC: headlines 1 local


** Choeur

Quatuor :

  - soprano
  - alto
  - ténor
  - basse

Septuor :

  - soprano
  - mezzo-soprano
  - alto
  - haute-contre, contralto, contreténor
  - ténor
  - baryton
  - basse


** Cordes frottées

Le célèbre quatuor à cordes :

  - 2 violons
  - violon alto
  - violoncelle

Les quintettes à corde :

  - Variante 1
    + 2 violons
    + violon alto
    + violoncelle
    + contrebasse
  - Variante 2
    + 2 violons
    + 2 violons alto
    + violoncelle
  - Variante 3
    + 2 violons
    + violon alto
    + 2 violoncelles

Mais aussi, pourquoi pas :

  - violon
  - violon alto
  - violoncelle
  - contrebasse


** Bois

Quintette :

  - Flûte
  - Hautbois
  - Clarinette
  - Cor anglais
  - Basson


** Hybride

Quatuor à cordes & piano :

  - 2 violons
  - violon alto
  - violoncelle
  - piano

Quintette à cordes & piano :

  - 2 violons
  - violon alto
  - violoncelle
  - contrebasse
  - piano


** Petits ensembles


*** Mélodie et Harmonie

Dans les petits ensembles de type quatuor, on peut répartir les rôles
comme suit :

  - par définition, la basse des accords à la Basse, ou une pédale le cas échéant
  - le reste des accords, plaqués ou arpégés, au Ténor
  - une première mélodie au Soprano
  - une seconde mélodie à l'Alto

Les deux voix les plus graves forment alors ce que l’époque baroque
appelait le *continuo*, tandis que les deux voix les plus aiguës
forment un duo mélodique.

Toutes les variantes de ce schéma sont possibles : les rôles des voix
peuvent être permutés à tout moment ; la Basse peut admettre d’autre
notes de l’accord, voire passer d’une fonction principalement
harmonique à un rôle mélodique, le Ténor également ; le Soprano et
l'Alto peuvent abandonner la mélodie pour faire entendre une pédale,
etc.

/Remarque/ : dans le cas où le ténor fait entendre des accords
plaqués, il peut y avoir plus de quatre voix simultanées. Ce n’est
plus alors un quatuor au sens strict, mais un ensemble de quatre
instruments. Dans la musique instrumentale de l’époque baroque, la
basse était jouée par un violoncelle, une contrebasse ou un basson et
le reste du continuo par un clavecin, un luth ou un orgue. Les autres
voix étaient interprétées par des violons ou des flûtes.


* Orchestration

#+TOC: headlines 1 local


** Voix humaine

La voix humaine évolue le plus aisément par mouvements conjoints, avec
de temps en temps des sauts de quinte, quarte ou tierce. Il faut
éviter les intervalles mélodiques de plus d’une sixte mineure, à
l’exception de l’octave qui est accepté.

Les chanteurs doivent respirer, il faut donc placer des silences
réguliers.

La voix humaine est principalement utilisée pour le chant, et
reproduit alors l’intonation naturelle ou expressive d’un texte.


** Guitares & Violons

Les guitares, violons et dérivés effectuent souvent des sauts entre
les cordes à partir d’une position des doigts fixe. Des lignes
composites se forment alors naturellement.


** Bois

Les bois doivent respirer, il faut donc placer des silences réguliers.


** Cuivres

Les cuivres sont à l’aise avec les répétitions de notes. Ils peinent
par contre à effectuer des sauts.

Ces instruments nécessitent beaucoup de souffle, il faut donc prévoir
des silences rapprochés.


* Enveloppe du son

L’enveloppe sonore est une modélisation approximative de l’évolution
du volume du son d’un instrument lorsqu’une note est jouée. Cette
modélisation se compose des étapes suivantes, par ordre
chronologique :

  - *entame* : appui sur une touche d’un clavier, pincement d’une
    corde de guitare, etc

  - *délai* avant que le son ne commence à se faire entendre
    (généralement nul)

  - *attaque* : temps que le son prend pour atteindre sa pleine
    puissance

  - *tenue* : temps durant lequel le son demeure à sa pleine puissance

  - *décrue* : temps pris par le son pour passer de sa pleine
    puissance à un niveau intermédiaire, appelé sous-tenue

  - *sous-tenue* : volume auquel le son demeure jusqu’à ce que le
    musicien arrête la note

  - *évanescence* : temps mis par le son pour devenir inaudible


** Claviers

Pour un piano, on a :

  - un délai nul
  - une attaque très courte
  - une tenue nulle, le son commence à décroître immédiatement
  - une décrue de quelques secondes
  - une sous-tenue nulle
  - une évanescence nulle

Pour un orgue, on a :

  - un délai nul

  - une attaque très courte

  - une tenue infinie, ce qui fait que la décrue et la sous-tenue
    n’apparaissent jamais

  - une évanescence nulle


** Hybride

L’avantage d’un instrument à cordes pincées ou frappées comme le
piano, le clavecin, la guitare, est qu’un accent est placé au début de
chaque note, ce qui permet de mieux les distinguer, surtout lors de
polyphonies rapides. Par contre, lors d’harmonies lentes, la tenue du
son n’est pas suffisante et un instrument comme l’orgue est mieux
adapté. On peut imaginer un instrument hybride, appelons le
*pianorgue*, permettant de s’adapter à ces deux situations :

  - délai nul
  - attaque très brève
  - tenue nulle
  - décrue lente
  - soutenue entre 50% et 90% de la pleine puissance
  - évanescence très brève

Ce genre d’instrument artificiel est notamment réalisable par
synthétiseur ou en musique assistée par ordinateur (MAO).
