
#+STARTUP: showall

#+TITLE: Eclats de vers : Noeuds 01 : Définitions
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+TAGS: noexport(n)
#+TAGS: derived(d)
#+TAGS: middle_rope(m)
#+TAGS: sliding(s) adjustable_grip(g)
#+TAGS: double_loop(2) triple_loop(3)
#+TAGS: quick_release(q)
#+TAGS: vibration_proof(v)

* Orientation

  - avant :: côté du noeud situé vers vous

  - arrière :: côté du noeud opposé à l’avant

  - poste :: objet auquel on attache la corde

    Peut être une barre, un anneau, ou une autre corde

  - avant du poste :: côté du poste situé vers vous

  - arrière du poste :: côté du poste opposé à l’avant du poste

  - gauche et droite :: sens usuels

  - haut et bas :: sens usuels


* Corde

  - extrémité :: en l’absence de plus de précision, il s’agit d’une
    extrémité de la corde

  - partie libre :: partie de la corde qui mène à l’extrémité sans
    rencontrer de croisement ou de noeud

  - partie de travail :: partie de la corde qui se déplace pour
    réaliser le noeud

    /Sauf mention contraire/ : lorsqu’on réalise une opération, c’est
    avec la partie de travail

  - partie statique :: partie statique de la corde

  - courant :: synonyme de partie de travail

  - dormant :: synonyme de partie statique

  - partie réglable :: partie de la corde permettant d’ajuster la
    taille de l’anse ou de la boucle d’un noeud en tirant

  - toronner :: assembler une corde plus épaisse à partir de cordes
    plus fines, en les faisant tourner les unes autour des autres en
    un mouvement hélicoïdal

  - corde toronnée :: corde complexe dont les éléments sont assemblés
    en mouvement hélicoïdal par torsion

  - toron :: élément d’une corde toronnée


* Anse

  - faire une anse :: faire demi-tour en dessinant une forme arrondie,
    revenir près de la partie statique, et la longer sur une certaine
    distance

    Ressemble vaguement à un champignon.

  - faire une anse, méthode du pliage :: si l’extrémité de la corde
    n’est pas accessible, il suffit de plier la corde à l’endroit
    voulu pour lui faire prendre la forme d’une anse

  - voûte de l’anse :: partie de l’anse où la corde fait demi-tour en
    dessinant une forme arrondie

    /Sauf mention contraire/ :

    + la voûte de l’anse est à l’arrière
    + pour les noeuds autour d’un poste horizontal : la voûte de
      l’anse est en haut

  - extrémité de l’anse :: synonyme de voûte de l’anse

  - base de l’anse :: partie de l’anse opposée à sa base

    La base est aussi la frontière entre l’anse et le reste de la
    corde.

    /Sauf mention contraire/ :

    + la base de l’anse est à l’avant
    + pour les noeuds autour d’un poste horizontal : la base de l’anse
      est en bas

  - bord de l’anse :: partie de l’anse située entre sa base et sa
    voûte

  - faire une anse horlogique :: faire une anse en tournant d’un
    demi-tour dans le sens horlogique

  - faire une anse anti-horlogique :: faire une anse en tournant d’un
    demi-tour dans le sens anti-horlogique

  - faire une anse, à droite :: faire une anse, partie de travail à
    droite

    Sauf mention contraire, la voûte est en arrière et cette anse est
    donc horlogique.

  - faire une anse, à gauche :: faire une anse, partie de travail à
    gauche

    Sauf mention contraire, la voûte est en arrière et cette anse est
    donc anti-horlogique.

  - faire une ganse :: dessiner une forme de cercle ouvert

    La ganse est en fait une anse large.

    Anse & ganse sont interchangeables, il suffit d’écarter un peu
    plus les bords d’une anse pour former une ganse.


** Passage

  - passer dans une anse :: passer au travers d’une anse

  - entrer dans une anse par au-dessus :: passer au travers d’une anse
    en entrant par au-dessus

    La sortie se fait forcément sous l’anse.

    L’endroit de la sortie peut être précisé, si nécessaire : bord
    gauche ou droite de l’anse, voûte, base, etc.

  - entrer dans une anse par en-dessous :: passer au travers d’une
    anse en entrant par en-dessous

    La sortie se fait forcément au-dessus de l’anse.

  - passer une anse *A* dans une anse *B* :: passer *A* au travers de *B*


** Méta-anse

  - faire une méta-anse à partir d’une anse :: faire une anse
    ordinaire *A*, puis faire une anse *M* à partir de la double corde
    formée par les bords de *A*


* Doubler une corde

  - faire une doublure :: faire une longue anse et placer les bords
    l’un contre l’autre

    Une doublure peut être utilisée comme partie de travail.

    Anse & doublure sont interchangeables, il suffit d’écarter les
    deux parties de corde d’une doublure pour former une anse.

  - faire une extrémité double :: placer les deux extrémités l’une
    contre l’autre, sur une certaine longueur

    Une extrémité double peut être utilisée comme partie de travail.


* Cercle

  - faire un cercle horlogique :: faire un cercle en tournant dans le
    sens horlogique

  - faire un cercle anti-horlogique :: faire un cercle en tournant
    dans le sens anti-horlogique

  - faire un demi-cercle horlogique :: faire un demi-cercle en
    tournant dans le sens horlogique

  - faire un demi-cercle anti-horlogique :: faire un demi-cercle en
    tournant dans le sens anti-horlogique



* Boucle

  - faire une boucle :: faire un tour complet en dessinant une forme
    arrondie, puis croiser la partie statique

    Ressemble à une lettre E minuscule.

  - faire une boucle, par pliage et torsion ::  si l’extrémité de la
    corde n’est pas accessible, il suffit de plier la corde à
    l’endroit voulu pour lui faire prendre la forme d’une anse, puis
    de faire tourner l’anse d’un demi-tour autour de l’axe reliant la
    base à la voûte pour créer une boucle

    Le sens de rotation détermine si la partie de travail se retrouve
    au-dessus ou en-dessous de la partie statique.

  - croisement de la boucle :: endroit où les deux parties de la corde
    se croisent pour former la boucle

    Le croisement est aussi la frontière entre la boucle et le reste
    de la corde.

    /Sauf mention contraire/ :

    + le croisement de la boucle est à l’avant
    + pour les noeuds autour d’un poste horizontal : le croisement de
      la boucle est en bas

  - base de la boucle :: synonyme de croisement de la boucle

  - voûte de la boucle :: partie de la boucle opposée à son croisement

    /Sauf mention contraire/ :

    + la voûte de la boucle est à l’arrière
    + pour les noeuds autour d’un poste horizontal : la voûte de la
      boucle est en haut

  - extrémité de la boucle :: synonyme de voûte de la boucle

  - bord de la boucle :: partie de la boucle située entre son
    croisement et sa voûte

  - faire une boucle horlogique :: faire une boucle en tournant dans
    le sens horlogique, puis en effectuant le croisement

  - faire une boucle anti-horlogique :: faire une boucle en tournant
    dans le sens anti-horlogique, puis en effectuant le croisement

  - faire une boucle, au-dessus :: faire un cercle, puis passer la
    partie de travail au-dessus de la partie statique pour effectuer
    le croisement

    En cas d’ambiguité, on précise : faire une boucle, partie de
    travail au-dessus.

  - faire une boucle, en-dessous :: faire un cercle, puis passer la
    partie de travail en-dessous de la partie statique pour effectuer
    le croisement

    En cas d’ambiguité, on précise : faire une boucle, partie de
    travail en-dessous.

  - faire une boucle, au-dessus vers *D* :: faire un cercle, puis
    passer la partie de travail au-dessus de la partie statique pour
    effectuer le croisement, de telle sorte que le croisement donne
    une direction *D* à la partie de travail

    En cas d’ambiguité, on précise : faire une boucle, partie de
    travail au-dessus vers *D*.

    On peut demander n’importe quelle direction pour la partie de
    travail : droite, gauche, avant, arrière, haut, bas, avant droit,
    arrière gauche, etc.

    /Sauf mention contraire/ : si la partie de travail part d’un côté,
    la partie statique provient du côté opposé. Par exemple, si la
    partie de travail part vers la droite, la partie statique provient
    plus ou moins de la gauche.

  - faire une boucle, en-dessous vers *D* :: faire un cercle, puis
    passer la partie de travail en-dessous de la partie statique pour
    effectuer le croisement, de telle sorte que le croisement donne
    une direction *D* à la partie de travail

    En cas d’ambiguité, on précise : faire une boucle, partie de
    travail en-dessous vers *D*.

  - faire une boucle, au-dessus vers la droite :: faire un cercle
    anti-horlogique, puis passer la partie de travail au-dessus de la
    partie statique pour effectuer le croisement, de telle sorte que
    la partie de travail parte vers la droite

    Sauf mention contraire, la voûte est en arrière et cette boucle
    est donc anti-horlogique.

  - faire une boucle, en-dessous vers la droite :: faire un cercle
    anti-horlogique, puis passer la partie de travail en-dessous de la
    partie statique pour effectuer le croisement, de telle sorte que
    la partie de travail parte vers la droite

    Sauf mention contraire, la voûte est en arrière et cette boucle
    est donc anti-horlogique.

  - faire une boucle, au-dessus vers la gauche :: faire un cercle
    horlogique, puis passer la partie de travail au-dessus de la
    partie statique pour effectuer le croisement, de telle sorte que
    la partie de travail parte vers la gauche

    Sauf mention contraire, la voûte est en arrière et cette boucle
    est donc horlogique.

  - faire une boucle, en-dessous vers la gauche :: faire un cercle
    horlogique, puis passer la partie de travail en-dessous de la
    partie statique pour effectuer le croisement, de telle sorte que
    la partie de travail parte vers la gauche

    Sauf mention contraire, la voûte est en arrière et cette boucle
    est donc horlogique.


** Torsion

  - tordre une anse :: faire tourner une anse d’un demi-tour autour de
    l’axe reliant la base à la voûte pour créer une boucle

  - faire une boucle en partant d’une anse :: synonyme de tordre une
    anse

  - tordre une boucle :: faire tourner la boucle autour de l’axe
    reliant sa base à son extrémité

    /Remarque/ :

    + si on se trompe de sens de rotation, la boucle se defait
    + une torsion d’un demi-tour transforme le croisement simple de la
      boucle en croisement double
    + une torsion de plusieurs demi-tours produit une boucle torsadée

  - torsader une boucle :: tordre une boucle de plusieurs demi-tours,
    ce qui produit une double hélice au niveau du croisement


** Passage

  - passer dans une boucle :: passer au travers d’une boucle

  - entrer dans une boucle par au-dessus :: passer au travers d’une
    boucle en entrant par au-dessus

    La sortie se fait forcément sous la boucle.

    L’endroit de la sortie peut être précisé, si nécessaire : bord
    gauche ou droite de la boucle, voûte, croisement, etc.

  - entrer dans une boucle par en-dessous :: passer au travers d’une
    boucle en entrant par en-dessous

    La sortie se fait forcément au-dessus de la boucle.

  - passer une anse *A* dans une boucle *B* :: passer *A* au travers de *B*

  - passer une boucle *B* dans une anse *A* :: passer *B* au travers de *A*

  - passer une boucle *B* dans une boucle *C* :: passer *B* au travers de *C*


* Bobine

  - faire une bobine :: superposer plusieurs cercles en effectuant
    plusieurs tours dans le même sens autour d’un axe de rotation
    commun

    /Remarques/ :

    + la forme obtenue est cylindrique
    + le premier cercle forme une boucle

  - faire une bobine de /N/ tours :: superposer /N/ cercles en
    effectuant /N/ tours dans le même sens autour d’un axe de rotation
    commun


* Lentille

  - lentille :: région située entre deux croisements de corde


* Binocle

  - faire un binocle :: faire une anse, puis faire tourner la voûte
    d’un demi-tour autour de l’axe qui relie les deux bords.

    L’axe de rotation est donc perpendiculaire à l’axe qui relie la
    base à la voûte.

    Ressemble à une paire de lunettes, d’où son nom.

  - boucles du binocle :: un binocle contient deux boucles
    symétriques

  - faire un binocle supérieur :: faire une anse, puis faire tourner
    la voûte d’un demi-tour :

    + autour de l’axe qui relie les deux bords
    + en commençant à tourner vers le haut et l’avant

  - faire un binocle inférieur :: faire une anse, puis faire tourner
    la voûte d’un demi-tour :

    + autour de l’axe qui relie les deux bords
    + en commençant à tourner vers le bas et l’avant

  - faire un binocle supérieur, méthode des deux boucles :: faire deux
    boucles comme suit :

    + faire une première boucle, au-dessus vers la droite, partie de
      travail venant de l’avant
    + faire une seconde boucle, juste à droite de la première, partie
      de travail en-dessous vers l’avant, partie statique venant de la
      gauche

  - faire un binocle inférieur, méthode des deux boucles :: faire deux
    boucles comme suit :

    + faire une première boucle, en-dessous vers la droite, partie de
      travail venant de l’avant
    + faire une seconde boucle, juste à droite de la première, partie
      de travail au-dessus vers l’avant, partie statique venant de la
      gauche


* Bretzel

  - faire un bretzel :: faire une boucle, puis faire tourner la voûte
    d’un demi-tour autour de l’axe qui relie les deux bords, de façon
    à englober le croisement de la boucle

    L’axe de rotation est donc perpendiculaire à l’axe qui relie le
    croisement à la voûte.

    Produit une forme comprenant deux boucles qui s’intersectent, avec
    une sorte de triangle au milieu. Ressemble à un huit couché et
    souligné, ou à un bretzel, d’où son nom.

  - boucles d’un bretzel :: un bretzel contient deux boucles qui
    s’intersectent

    Si on imagine un bretzel avec les voûtes à l’arrière, on a :

    + une première boucle avec la voûte en arrière à gauche et le
      croisement en avant à droite
    + une seconde boucle avec la voûte en arrière à droite et le
      croisement en avant à gauche

  - croisements d’un bretzel :: un bretzel contient trois
    croisements : un croisement par boucle, plus un croisement entre
    les bords des deux boucles

    Si on imagine un bretzel avec les voûtes en arrière, le troisième
    croisement s’effectue entre :

    + le bord droit de la boucle dont la voûte est en arrière à
      gauche
    + le bord gauche de la boucle dont la voûte est en arrière à
      droite

  - triangle d’un bretzel :: triangle dont les côtés relient les trois
    croisements du bretzel

    Le triangle est aussi l’intersection des deux boucles du bretzel.

  - oreille gauche d’un bretzel :: partie de la boucle gauche du
    bretzel qui n’est pas dans le triangle

  - oreille droite d’un bretzel :: partie de la boucle droite du
    bretzel qui n’est pas dans le triangle

  - faire un bretzel droit supérieur :: faire une boucle, au-dessus
    vers la droite, puis faire tourner la voûte d’un demi-tour :

    + autour de l’axe qui relie les deux bords
    + en commençant à tourner vers le haut et l’avant.
    + de façon à englober le croisement de la boucle

  - faire un bretzel droit inférieur :: faire une boucle, au-dessus
    vers la droite, puis faire tourner la voûte d’un demi-tour :

    + autour de l’axe qui relie les deux bords
    + en commençant à tourner vers le bas et l’avant
    + de façon à englober le croisement de la boucle

  - faire un bretzel gauche supérieur :: faire une boucle, au-dessus
    vers la gauche, puis faire tourner la voûte d’un demi-tour :

    + autour de l’axe qui relie les deux bords
    + en commençant à tourner vers le haut et l’avant
    + de façon à englober le croisement de la boucle

  - faire un bretzel gauche inférieur :: faire une boucle, au-dessus
    vers la gauche, puis faire tourner la voûte d’un demi-tour :

    + autour de l’axe qui relie les deux bords
    + en commençant à tourner vers le bas et l’avant
    + de façon à englober le croisement de la boucle


* Brezn

  - faire un brezn :: faire une boucle, puis faire un demi-cercle en
    tournant dans le même sens et repasser dans la boucle en alternant
    les croisements au-dessus et en-dessous

    Produit une forme comprenant deux boucles entrelacées, avec une
    sorte de triangle au milieu.

    /Exemple/ :

    + faire une boucle *A* anti-horlogique
      * partie de travail au-dessus vers l’arrière droite
      * partie statique vers l’avant droite
    + faire un demi-tour anti-horlogique
    + passer sous le bord arrière droit de *A*, vers l’avant gauche
    + passer au-dessus du bord avant de *A*, vers l’avant gauche

    Brezn et bretzel se ressemblent fort. Pour les différencier,
    remarquer que le bretzel ne respecte pas l’alternance des
    croisements au-dessus et en-dessous.

  - boucles d’un brezn :: un brezn contient deux boucles entrelacées

    Si on imagine un brezn avec les voûtes à l’arrière, on a :

    + une première boucle avec la voûte en arrière à gauche et le
      croisement en avant à droite
    + une seconde boucle avec la voûte en arrière à droite et le
      croisement en avant à gauche

  - croisements d’un brezn :: un brezn contient trois croisements : un
    croisement par boucle, plus un croisement entre les bords des deux
    boucles

    Si on imagine un brezn avec les voûtes en arrière, le troisième
    croisement s’effectue entre :

    + le bord arrière droit de la boucle dont la voûte est en arrière
      à gauche
    + le bord arrière gauche de la boucle dont la voûte est en arrière
      à droite

  - triangle d’un brezn :: triangle dont les côtés relient les trois
    croisements du brezn

    Le triangle est aussi l’intersection des deux boucles du brezn.

  - oreille gauche d’un brezn :: partie de la boucle gauche du brezn
    qui n’est pas dans le triangle

  - oreille droite d’un brezn :: partie de la boucle droite du brezn
    qui n’est pas dans le triangle

  - faire un brezn supérieur droit :: faire un brezn de telle sorte
    que la partie libre de droite soit au-dessus de la forme, tandis
    que la partie libre de gauche est en-dessous de la forme

    Détail :

    + faire une boucle *A* horlogique
      * partie de travail au-dessus vers l’arrière gauche
      * partie statique vers l’avant gauche
    + faire un demi-tour horlogique
    + passer sous le bord arrière gauche de *A*, vers l’avant droite
    + passer au-dessus du bord avant de *A*, vers l’avant droite
    + vérifier que la partie de travail est à droite de la partie
      statique

    Méthode réciproque :

    + faire une boucle *A* anti-horlogique
      * partie de travail en-dessous vers l’arrière droite
      * partie statique vers l’avant droite
    + faire un demi-tour anti-horlogique
    + passer au-dessus du bord arrière droit de *A*, vers l’avant
      gauche
    + passer sous le bord avant de *A*, vers l’avant gauche
    + vérifier que la partie de travail est à gauche de la partie
      statique

  - brezn inférieur gauche :: synonyme de brezn supérieur droit

  - faire un brezn supérieur gauche :: faire un brezn de telle sorte
    que la partie libre de gauche soit au-dessus de la forme, tandis
    que la partie libre de droite est en-dessous de la forme

    Détail :

    + faire une boucle *A* horlogique
      * partie de travail en-dessous vers l’arrière gauche
      * partie statique vers l’avant gauche
    + faire un demi-tour horlogique
    + passer au-dessus du bord arrière gauche de *A*, vers l’avant
      droite
    + passer sous le bord avant de *A*, vers l’avant droite
    + vérifier que la partie de travail est à droite de la partie
      statique

    Méthode réciproque :

    + faire une boucle *A* anti-horlogique
      * partie de travail au-dessus vers l’arrière droite
      * partie statique vers l’avant droite
    + faire un demi-tour anti-horlogique
    + passer sous le bord arrière droit de *A*, vers l’avant gauche
    + passer au-dessus du bord avant de *A*, vers l’avant gauche
    + vérifier que la partie de travail est à gauche de la partie
      statique

  - brezn inférieur droit :: synonyme de brezn supérieur gauche


* Huitain

  - faire un huitain :: faire une boucle, puis faire un demi-cercle en
    tournant dans l’autre sens, et croiser la partie statique un peu
    plus loin, de l’autre côté de la corde et dans la direction
    opposée

    Ressemble à un huit, d’où son nom. J’ai choisi le terme *huitain*
    pour ne pas confondre avec les noeuds en 8 (figure 8), mais cela
    n’a bien entendu rien à voir avec les strophes du même nom.

    /Exemple/ : faire un cercle horlogique, croiser la partie statique
    en-dessous vers la gauche, puis faire un demi-cercle
    anti-horlogique et croiser la partie statique au-dessus vers la
    droite.

  - faire un huitain, méthode de torsion :: faire une boucle, puis la
    tordre d’un demi-tour pour qu’elle prenne la forme d’un huit

    Le sens de rotation est le même que celui qui permet de passer
    d’une anse à la boucle.

    Il peut être nécessaire d’arranger les cordes pour que le huit
    apparaisse clairement.

    /Remarque/ : pour voir si la torsion s’est effectuée dans le bon
    sens, vérifier si, en partant de la partie statique, la corde
    passe alternativement en-dessous et au-dessus à chaque croisement
    rencontré

  - lentille d’un huitain :: partie du huitain située entre les deux
    croisements

  - boucle d’un huitain :: partie du huitain qui part de la voûte
    jusqu’au premier croisement rencontré

    Autrement dit, c’est ce qui reste du huitain lorsqu’on fait
    abstraction de sa lentille.

    Le huitain est donc composé :

    + d’une boucle
    + d’une lentille

  - croisement intérieur d’un huitain :: croisement qui sépare la
    boucle et la lentille du huitain

  - croisement interne d’un huitain :: synonyme de croisement
    intérieur

  - croisement extérieur d’un huitain :: croisement à la frontière
    entre la lentille du huitain et l’extérieur

  - croisement externe d’un huitain :: synonyme de croisement
    extérieur

  - faire un huitain supérieur :: faire un huitain de telle sorte que
    la partie de travail soit au-dessus de la partie statique dans le
    croisement extérieur

  - faire un huitain inférieur :: faire un huitain de telle sorte que
    la partie de travail soit en-dessous de la partie statique dans le
    croisement extérieur

  - faire un huitain supérieur, vers la droite :: faire un huitain
    supérieur de telle sorte que la partie de travail parte vers la
    droite après le croisement extérieur

    Détail : faire un cercle horlogique, croiser la partie statique
    en-dessous vers la gauche, puis faire un demi-cercle
    anti-horlogique et croiser la partie statique au-dessus vers la
    droite

  - faire un huitain inférieur, vers la droite :: faire un huitain
    inférieur de telle sorte que la partie de travail parte vers la
    droite après le croisement extérieur

    Détail : faire un cercle horlogique, croiser la partie statique
    au-dessus vers la gauche, puis faire un demi-cercle
    anti-horlogique et croiser la partie statique en-dessous vers la
    droite.

  - faire un huitain supérieur, vers la gauche :: faire un huitain
    supérieur de telle sorte que la partie de travail parte vers la
    gauche après le croisement extérieur

    Détail : faire un cercle anti-horlogique, croiser la partie
    statique en-dessous vers la droite, puis faire un demi-cercle
    horlogique et croiser la partie statique au-dessus vers la gauche.

  - faire un huitain inférieur, vers la gauche :: faire un huitain
    inférieur de telle sorte que la partie de travail parte vers la
    gauche après le croisement extérieur

    Détail : faire un cercle anti-horlogique, croiser la partie/
    statique au-dessus vers la droite, puis faire un demi-cercle
    horlogique et croiser la partie statique en-dessous vers la
    gauche.


* Esperluette

  - faire une esperluette :: faire une boucle, puis faire un
    demi-cercle en tournant dans l’autre sens, et croiser la partie
    statique un peu plus loin, du même côté de la corde mais dans la
    direction opposée

    Ressemble à une esperluette, d’où son nom.

    /Exemple/ : faire un cercle horlogique, croiser la partie statique
    au-dessus vers la gauche, puis faire un demi-cercle
    anti-horlogique et croiser la partie statique au-dessus vers la
    droite.

  - lentille d’une esperluette :: partie de l’esperluette située entre
    les deux croisements

  - boucle d’une esperluette :: partie de l’esperluette qui part de la
    voûte jusqu’au premier croisement rencontré

    Autrement dit, c’est ce qui reste de l’esperluette lorsqu’on fait
    abstraction de sa lentille.

    L’esperluette est donc composée :

    + d’une boucle
    + d’une lentille

  - croisement intérieur d’une esperluette :: croisement qui sépare la
    boucle et la lentille de l’esperluette

  - croisement interne d’une esperluette :: synonyme de croisement
    intérieur

  - croisement extérieur d’une esperluette :: croisement à la
    frontière entre la lentille de l’esperluette et l’extérieur

  - croisement externe d’une esperluette :: synonyme de croisement
    extérieur

  - faire une esperluette supérieure :: faire une esperluette, avec
    les deux passages de la partie de travail au-dessus de la partie
    statique

  - faire une esperluette inférieure :: faire une esperluette, avec
    les deux passages de la partie de travail en-dessous de la partie
    statique

  - faire une esperluette supérieure, vers la droite :: faire une
    esperluette supérieure, de telle sorte que la partie de travail
    parte vers la droite après le croisement extérieur

    Détail : faire un cercle horlogique, croiser la partie statique
    au-dessus vers la gauche, puis faire un demi-cercle
    anti-horlogique et croiser la partie statique au-dessus vers la
    droite.

  - faire une esperluette inférieure, vers la droite :: faire une
    esperluette inférieure, de telle sorte que la partie de travail
    parte vers la droite après le croisement extérieur

    Détail : faire un cercle horlogique, croiser la partie statique
    en-dessous vers la gauche, puis faire un demi-cercle
    anti-horlogique et croiser la partie statique en-dessous vers la
    droite.

  - faire une esperluette supérieure, vers la gauche :: faire une
    esperluette supérieure, de telle sorte que la partie de travail
    parte vers la gauche après le croisement extérieur

  - faire une esperluette inférieure, vers la gauche :: faire une
    esperluette inférieure, de telle sorte que la partie de travail
    parte vers la gauche après le croisement extérieur


* Esse

  - faire un esse :: faire une boucle, puis faire une anse en tournant
    dans l’autre sens, et croiser la partie statique au même endroit,
    mais de l’autre côté de la corde et dans la direction opposée

    Ressemble vaguement à une lettre S, ou à son reflet dans le
    miroir, d’où son nom.

    /Exemple/ : faire un cercle horlogique, croiser la partie statique
    en-dessous vers la gauche, puis faire une anse anti-horlogique et
    passer au-dessus du premier croisement, vers la droite.

  - boucle d’un esse :: c’est la boucle réalisée pour former le début
    du esse

  - anse d’un esse :: c’est l’anse réalisée pour former la suite du
    esse

    Autrement dit, c’est ce qui reste du esse lorsqu’on fait
    abstraction de sa boucle.

    Le esse est donc composé :

    + d’une boucle
    + d’une anse

  - croisement d’un esse :: c’est le double croisement commun à la
    boucle et à l’anse du esse

  - faire un esse supérieur :: faire un esse de telle sorte que le
    second croisement se fasse au-dessus du premier

  - faire un esse inférieur :: faire un esse de telle sorte que le
    second croisement se fasse en-dessous du premier

  - faire un esse supérieur, vers la droite :: faire un esse
    supérieur, de telle sorte que la partie de travail parte vers la
    droite après le second croisement

    Détail :

    + faire une boucle horlogique *A*, en-dessous vers la gauche
      * soit *X* le croisement de *A*
    + faire une anse anti-horlogique *B*, puis passer au-dessus de
      *X*, vers la droite

  - faire un esse inférieur, vers la droite :: faire un esse
    inférieur, de telle sorte que la partie de travail parte vers la
    droite après le second croisement

    Détail :

    + faire une boucle horlogique *A*, au-dessus vers la gauche
      * soit *X* le croisement de *A*
    + faire une anse anti-horlogique *B* et passer sous *X*, vers la
      droite

  - faire un esse supérieur, vers la gauche :: faire un esse
    supérieur, de telle sorte que la partie de travail parte vers la
    gauche après le second croisement

    Détail :

    + faire une boucle anti-horlogique *A*, en-dessous vers la droite
      * soit *X* le croisement de *A*
    + faire une anse horlogique *B* et passer au-dessus de *X*, vers
      la gauche

  - faire un esse inférieur, vers la gauche :: faire un esse
    inférieur, de telle sorte que la partie de travail parte vers la
    gauche après le second croisement

    Détail :

    + faire une boucle anti-horlogique *A*, au-dessus vers la droite
      * soit *X* le croisement de *A*
    + faire une anse horlogique *B* et passer sous *X*, vers la gauche


* Effe

  - faire un effe :: faire une première boucle, puis une seconde
    boucle qui partage le même croisement que la première, mais dont
    la voûte est dans la direction opposée. Les croisements doivent
    alterner les côtés dessus et dessous. Les sens de rotation des
    deux boucles sont opposés. Les directions de sortie des deux
    boucles sont les mêmes.

    Ressemble vaguement à une lettre F minuscule, ou à son reflet dans
    le miroir, d’où son nom.

    /Exemple/ : faire une boucle anti-horlogique, en-dessous vers la
    droite, puis faire un cercle horlogique et passer au-dessus du
    premier croisement, toujours vers la droite.

    /Attention/ à ne pas confondre effe et esse !

  - croisement d’un effe :: c’est le double croisement commun aux deux
    boucles du effe

  - faire un effe supérieur :: faire un effe de telle sorte que le
    croisement de la seconde boucle se fasse au-dessus du croisement
    de la première

  - faire un effe inférieur :: faire un effe de telle sorte que le
    croisement de la seconde boucle se fasse en-dessous du croisement
    de la première

  - faire un effe supérieur, vers la droite :: faire un effe
    supérieur, de telle sorte que la partie de travail parte vers la
    droite après le croisement de la seconde boucle

    Détail :

    + faire une boucle anti-horlogique *A*, en-dessous vers la droite
      * soit *X* le croisement de *A*
    + faire une boucle horlogique *B*, dont le croisement s’effectue
      en passant au-dessus de *X*, vers la droite

  - faire un effe inférieur, vers la droite :: faire un effe
    inférieur, de telle sorte que la partie de travail parte vers la
    droite après le croisement de la seconde boucle

    Détail :

    + faire une boucle anti-horlogique *A*, au-dessus vers la droite
      * soit *X* le croisement de *A*
    + faire une boucle horlogique *B*, dont le croisement s’effectue
      en passant sous *X*, vers la droite

  - faire un effe supérieur, vers la gauche :: faire un effe
    supérieur, de telle sorte que la partie de travail parte vers la
    gauche après le croisement de la seconde boucle

  - faire un effe inférieur, vers la gauche :: faire un effe
    inférieur, de telle sorte que la partie de travail parte vers la
    gauche après le croisement de la seconde boucle


* Glossaire anglais

  - working end / tail :: partie de la corde qui se déplace pour
    réaliser le noeud

  - standing part / lead rope :: partie statique de la corde

  - bight :: anse, doublure

  - knot :: noeud

  - quick release :: dénouage rapide

  - hand wrap :: enroulement autour de la main

  - loop :: boucle, peut désigner :

    + une boucle réalisée lors de la construction d’un noeud
    + un noeud terminé en forme de boucle ou d’anse

  - noose :: boucle réglable (noeud coulant)

  - adjustable grip :: boucle ajustable hors tension, mais fixe sous
    tension

  - coil :: bobine

  - bend :: noeud d’attache de deux cordes ou des deux extrémités
            d’une corde

  - hitch :: noeud d’attache à un objet, souvent une barre fixe

  - post :: objet auquel on attache une corde

  - gripping hitch :: hitch anti-glissement, pour traction en partie
    ou totalement parallèle au poste

  - lashing :: noeud d’attache de deux ou plusieurs objets

  - braid :: tresse

  - mat :: natte

  - ampersand :: esperluette
