
#+STARTUP: showall

#+TITLE: Eclats de vers : Noeuds 13 : Ornements
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+TAGS: noexport(n)
#+TAGS: derived(d)
#+TAGS: middle_rope(m)
#+TAGS: sliding(s) adjustable_grip(g)
#+TAGS: double_loop(2) triple_loop(3)
#+TAGS: quick_release(q)
#+TAGS: vibration_proof(v)

* Tresses
:PROPERTIES:
:CUSTOM_ID: section:tresses
:END:

#+TOC: headlines 1 local

** Introduction


*** Noeud initial

On commence généralement une tresse en nouant les cordes entre-elles.


*** Surliure

Pour empêcher la tresse de se défaire, terminer en utilisant une corde
plus fine pour feire une bobine à anse autour de la tresse.


*** Torsion

Dans le procédé permettant de toronner une corde, on voit que tordre
la corde dans un sens préalablement à une rotation dans l’autre sens
permet de renforcer la solidité de l’ensemble. Le procédé de tressage
étant similaire, on peut bien entendu utiliser cette même technique de
torsion pour renforcer la solidité de la tresse.


** Trois parties libres

  1. disposer les trois parties libres *A*, *B* et *C* de gauche à
     droite
  2. recommencer jusqu’à la longueur désirée
     1) passer la partie libre de gauche au-dessus de la corde
        centrale, vers la droite
     2) passer la partie libre de droite au-dessus de la partie libre
        centrale, vers la gauche
     3) serrer
  3. voici l’ordre des parties libres dans les premières phases
     1) *A* - *B* - *C*
     2) *B* - *A* - *C*
     3) *B* - *C* - *A*
     4) *C* - *B* - *A*
     5) *C* - *A* - *B*
     6) *A* - *C* - *B*
     7) *A* - *B* - *C*
     8) ...
  4. terminer par une surliure


** Quatre parties libres

Asymétrique.

  1. disposer les quatre parties libres *A*, *B*, *C* et *D*
     parallèlement, de gauche à droite
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) passer la partie libre de gauche au-dessus des deux parties
        libres immédiatement à sa droite
     2) passer la partie libre de droite au-dessus de la partie libre
        immédiatement à sa gauche
     3) serrer
  3. terminer par une surliure


** Cinq parties libres

  1. disposer les cinq parties libres parallèlement, de gauche à
     droite
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) passer la partie libre de gauche au-dessus des deux parties
        libres immédiatement à sa droite
     2) passer la partie libre de droite au-dessus des deux parties
        libres immédiatement à sa gauche
     3) serrer
  3. terminer par une surliure


** Six parties libres

Asymétrique.

  1. disposer les six parties libres parallèlement, de gauche à droite
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) passer la partie libre de gauche au-dessus des deux parties
        libres immédiatement à sa droite
     2) passer la partie libre de droite au-dessus des trois parties
        libres immédiatement à sa gauche
     3) serrer
  3. terminer par une surliure


** Sept parties libres

  1. disposer les sept parties libres parallèlement, de gauche à
     droite
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) passer la partie libre de gauche au-dessus des trois parties
        libres immédiatement à sa droite
     2) passer la parties libres de droite au-dessus des trois parties
        libres immédiatement à sa gauche
     3) serrer
  3. terminer par une surliure


** Scoubidou à quatre parties libres, rond

  1. disposer les quatre parties libres parallèlement, de gauche à
     droite
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) passer la partie libre de gauche en-dessous des deux parties
        libres immédiatement à sa droite, puis au-dessus de la partie
        libre immédiatement à sa gauche
     2) passer la partie libre de droite en-dessous des deux parties
        libres immédiatement à sa gauche, puis au-dessus de la partie
        libre immédiatement à sa droite
     3) serrer
  3. terminer par une surliure


** Scoubidou à huit parties libres, rond

  1. disposer les huit parties libres parallèlement, de gauche à
     droite
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) passer la partie libre de gauche au-dessus des quatre parties
        libres immédiatement à sa droite
     2) passer la partie libre de droite au-dessus des trois parties
        libres immédiatement à sa gauche
     3) passer la partie libre de gauche en-dessous des quatre parties
        libres immédiatement à sa droite
     4) passer la partie libre de droite en-dessous des trois parties
        libres immédiatement à sa gauche
     5) serrer
  3. terminer par une surliure


** Scoubidou rond

Utilise quatre parties libres.

  1. disposer les parties libres en étoile, au-dessus du noeud de
     départ
  2. recommencer jusqu’à la longueur désirée
     1) soit les parties libres *A*, *B*, *C* et *D*, dans le sens
        horlogique
	- *A* indique l’arrière
	- *B* indique la droite
	- *C* indique l’avant
	- *D* indique la gauche
     2) faire un demi-tour avec *A*, vers l’avant et légèrement à
        droite
     3) produit une boucle *L*
     4) passer au-dessus de la partie libre qui indique la droite
     5) faire un demi-tour avec *B*, vers la gauche et légèrement en
        avant
     6) passer au-dessus des deux parties libres qui indiquent l’avant
     7) faire un demi-tour avec *C*, vers l’arrière et légèrement à
        gauche
     8) passer au-dessus des deux parties libres qui indiquent la
        gauche
     9) faire un demi-tour avec *D*, vers la droite et légèrement à
        l’arrière
     10) passer au-dessus de la première parties libres qui indique
         l’arrière
     11) passer dans *L* en entrant par au-dessus
     12) serrer

Notons que les rôles et les noms des parties libres changent à chaque
étape.


** Scoubidou à chevrons

Même principe que le scoubidou rond, mais utilise une rotation en
hélice sur une étoile à six parties libres.

À chaque étape du processus, on passe au-dessus des deux parties
libres suivantes rencontrées dans le sens horlogique.


** Scoubidou carré

Utilise quatre parties libres. Même principe que le scoubidou rond,
mais on inverse le sens de rotation après chaque tour complet
effectué.


* Macramé

#+TOC: headlines 1 local


** Introduction

Mêmes principes que pour les [[#section:tresses][tresses]].


*** Deux parties libres par corde

Pour utiliser deux parties libres par cordes, une solution pratique
consiste à nouer un lark’s head par corde autour d’une barre commune à
toutes les cordes, de façon à disposer de toutes les parties libres,
parallèles et proches les unes des autres.


** Twirl

Utilise deux parties libres qui forment une série de overhand.

  1. disposer les deux parties libres parallèlement
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) soit *G* et *D* les deux parties libres, respectivement de
        gauche à droite
     2) passer *G* au-dessus de *D*, vers la droite
	- forme une boucle *B*
     3) passer *G* dans *B* en entrant par en-dessous, vers la gauche
     4) serrer
  3. au bout de quelques étapes, le noeud va commencer à prendre une
     forme hélicoïdale
  4. au bout d’un moment, il peut être nécessaire de faire tourner le
     macramé d’un tour complet avant de continuer

Notons que les rôles et les noms des parties libres changent à chaque
étape.


** Spiral knot

Utilise quatre parties libres :

  - deux parties libres neutres au centre
  - deux parties libres extérieures qui forment une série de overhand
    autour des parties libres centrales

Procédé :

  1. disposer les quatre parties libres parallèlement
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) soit *G*, *N1*, *N2* et *D* les quatre parties libres,
        respectivement de gauche à droite
	- *N1* et *N2* sont les parties libres neutres
     2) passer *G* au-dessus de *N1* et *N2*, vers la droite
	- forme une boucle *B* avec *N1*
     3) passer *D* au-dessus de *G*, vers l’avant
     4) passer *D* sous *N1* et *N2*, vers la gauche
     5) passer *D* dans *B* en entrant par en-dessous, vers l’arrière
	- sortir *D* de *B* par au-dessus, vers la gauche
     6) serrer
  3. au bout de quelques étapes, le noeud va commencer à prendre une
     forme hélicoïdale
  4. au bout d’un moment, il peut être nécessaire de faire tourner le
     macramé d’un tour complet avant de continuer

Notons que les rôles et les noms des parties libres changent à chaque
étape.


** Cyclonic bootlace

Utilise quatre parties libres :

  - deux parties libres neutres au centre
  - deux parties libres extérieures

L’idéal est d’alterner deux couleurs.

Procédé :

  1. disposer les quatre parties libres parallèlement
     - chaque partie libre va d’arrière en avant
  2. recommencer jusqu’à la longueur désirée
     1) soit *G*, *N1*, *N2* et *D* les quatre parties libres,
        respectivement de gauche à droite
	- *N1* et *N2* sont les parties libres neutres
     2) faire un demi-cercle horlogique avec *D*, et effectuer le
        croisement *Xarrière* au-dessus de *N1* et *N2*, vers la
        gauche
	- soit *Carrière* ce demi-cercle
	- ce demi-cercle se situe à droite des parties libres neutres
     3) faire un demi-cercle anti-horlogique avec *D*, et effectuer le
        croisement *Xavant* en-dessous de *N1* et *N2*, vers la droite
	- soit *Cavant* ce demi-cercle
	- ce demi-cercle se situe à gauche des parties libres neutres,
          plus en avant que *Carrière*
     4) faire un demi-cercle anti-horlogique avec *G*, et effectuer le
        croisement *Zarrière* au-dessus de *N1*, *N2* et *Xarrière*,
        vers la droite
	- soit *Uarrière* ce demi-cercle
	- ce demi-cercle se situe à gauche des parties libres neutres
          et de *Carrière*, et juste derrière *Cavant*
	- le croisement avec les parties libres neutres s’effectue au
          même endroit que pour *Carrière*, mais dans la direction
          opposée
     5) faire un demi-cercle horlogique avec *G*, et effectuer le
        croisement *Zavant* en-dessous de *N1*, *N2* et *Xavant*, vers
        la gauche
	- soit *Uavant* ce demi-cercle
	- ce demi-cercle se situe à droite des parties libres neutres
          et de *Cavant*, juste devant *Carrière*
	- le croisement avec les parties libres neutres s’effectue au
          même endroit que pour *Cavant**, mais dans la direction
          opposée
     6) passer *G* dans *Cavant*, en entrant par en-dessous, vers la
        gauche
     7) serrer

Notons que les rôles et les noms des parties libres changent à chaque
étape.


* Chaînes


** Caterpillar sinnet

Même principe que le [[file:noeuds-07-raccourcisseurs.org::#section:daisy_chain][daisy chain sinnet]], mais on serre l’anse autour
de la suivante à chaque étape. Noeud surtout décoratif.

  1. faire un slip knot, partie réglable du côté statique
  2. soit *I* l’anse du slip knot
  3. répétition
     1) faire une anse *II*
     2) passer *II* dans *I*
     3) serrer *I* autour de *II*
     4) faire une anse *III*
     5) passer *III* dans *II*
     6) serrer *II* autour de *III*
     7) faire une anse *IV*
     8) passer *IV* dans *III*
     9) serrer *III* autour de *IV*
     10) continuer jusqu’à la longueur désirée
  4. terminer en passant la partie de travail dans la dernière anse
     réalisée
  5. tendre la corde par les extrémités


* Cravate

  1. passer la cravate autour du cou
  2. faire une boucle *B* en passant la partie fine entre le torse et la
     partie large
  3. faire un tour complet *T* avec la partie large autour du
     croisement *C* de la boucle *B*
  4. passer la partie large dans la boucle, de bas en haut
  5. passer entre *C* et *T*, de haut en bas
  6. régler et serrer


* Autres

#+TOC: headlines 1 local


** Noeuds

  - Eternity knot
  - Ashley’s flower knot
  - Chinese flower knot
  - Celtic tree of life
  - Celtic heart knot
  - Celtic square knot
  - Witness of your splendor, celtic knot
  - Rising sun knot
  - Decorative paracord oriental pendant
  - Celtic pendant paracord necklace
  - Olias knot
  - Fleur de lis knot
  - Pipa knot
  - Celtic ring knot
  - Ashoka chakra knot
  - Turk’s head
  - Caterpillar sinnet
  - Spinal sinnet
  - Celtic bar
  - Snake knot
  - Two color snake weave
  - Snake knot viceroy
  - 2 color snake weave
  - Icelandic dream bar
  - Crooked river
  - Bridge wanderer
  - Crown sinnet
  - Single strand ringbolt hitch
  - Star string figure


** Tresses

  - Rope coaster (en 3 boucles)
  - Australian braid knot
  - 3 strand flat braid
  - 3 strand braid
  - 4 strand round braid
  - 5 strand braid


** Tapis

  - Round rope mat
  - Kringle mat
  - Thump mat
