
#+STARTUP: showall

#+TITLE: Eclats de vers : Noeuds 09 : Noeuds d’accroche
#+AUTHOR: chimay
#+EMAIL: or du val chez gé courriel commercial
#+LANGUAGE: fr
#+LINK_HOME: file:../index.html
#+LINK_UP: file:index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style/defaut.css" />

#+OPTIONS: H:6
#+OPTIONS: toc:nil

#+TAGS: noexport(n)

[[file:index.org][Index des Grimoires]]

#+INCLUDE: "../include/navigan-1.org"

#+TOC: headlines 1

#+TAGS: noexport(n)
#+TAGS: derived(d)
#+TAGS: middle_rope(m)
#+TAGS: sliding(s) adjustable_grip(g)
#+TAGS: double_loop(2) triple_loop(3)
#+TAGS: quick_release(q)
#+TAGS: vibration_proof(v)

* Introduction

Les noeuds d’accroche sont utilisés pour accrocher une corde à un
objet.

Dans ce chapitre, le poste est un objet de forme allongée, auquel on
souhaite attacher la corde. Le poste peut être :

  - une barre horizontale ou verticale
  - un poteau
  - un anneau
    + certains noeuds nécessitent toutefois l’accès à une extrémité du
      poste et ne pourront donc pas être noués autour d’un anneau
  - une planche
  - une autre corde
    + le noeud sert alors à attacher deux cordes ensemble avec la
      seconde corde qui effectue une traction perpendiculaire à la
      première
    + voir aussi le tome sur les [[file:noeuds-05-attaches-extremites.org][bend]] pour les tractions
      longitudinales

Généralités :

  - c’est la partie statique de la corde qui supporte en général
    l’essentiel de la traction
  - sauf mention contraire, la traction s’effectue perpendiculairement
    au poste


* Clove hitch
:PROPERTIES:
:CUSTOM_ID: section:clove_hitch
:END:

/alias/ : noeud de cabestan


** Standard

Le clove hitch simple peut se défaire en cas de charge changeante, il
est conseillé de lui préférer ses variantes plus robustes.


*** Méthode directe

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer un passage *D* au-dessus du poste, en diagonale vers
	l’arrière et la droite
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à droite de la
        partie statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer un passage *G* au-dessus de *D*, en diagonale vers
	l’arrière et la gauche
     2) vérifier que *D* et *G* forment une croix
     3) passer derrière le poste, vers le bas
     4) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
     5) passer devant le poste, vers le haut
  4. passer entre *G* et le poste en longeant la gauche de *D*
  5. serrer


*** Méthode des deux boucles                                    :middle_rope:

Nécessite d’avoir accès à une extrémité du poste.

  1. faire une boucle *A*, au-dessus vers la droite
  2. faire une boucle *B* à droite de *A*, partie de travail au-dessus
     vers la droite
  3. placer *B* en-dessous de *A*
  4. passer *A* et *B* autour du poste
  5. serrer


*** Méthode du effe

  1. faire un effe supérieur droit, formant ainsi
     - une boucle arrière *A*
     - une boucle avant *B*
  2. faire tourner *B*
     - autour d’un axe gauche - droite
     - en commençant vers l’arrière et le haut
     - pour amener *B* au-dessus de *A*
  3. passer *A* et *B* autour du poste
  4. serrer


** Spar hitch
:PROPERTIES:
:CUSTOM_ID: section:spar_hitch
:END:

Clove hitch amélioré.


*** Méthode directe

Bel exemple de [[file:noeuds-02-operations.org::#section:superposition_circulaire][superposition circulaire en pierre - papier - ciseaux]].

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer un passage *D* au-dessus du poste, en diagonale vers
	l’arrière et la droite
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à droite de la
        partie statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer un passage *G* au-dessus de *D*, en diagonale vers
	l’arrière et la gauche
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
     4) passer devant la partie statique, vers la droite
     5) passer devant le poste, vers le haut
  4. passer au-dessus de *G*, vers l’arrière
  5. passer entre *D* et le poste, vers la gauche
  6. serrer


*** Méthode de l’esperluette

  1. faire une esperluette supérieure droite, formant ainsi
     - une boucle *B*
     - une lentille *L*
     - un croisement intérieur *X*
  2. faire un demi-cercle anti-horlogique pour venir se positionner
     juste à droite de *B*
  3. passer dans *B*, contre *X*, en entrant par au-dessus, vers la
     gauche
  4. faire tourner *L*
     - autour d’un axe gauche - droite
     - en commençant vers le bas et l’arrière
     - pour l’amener sous *B*
  5. passer *B* et *L* autour du poste
  6. serrer


** Bag hitch

Spar hitch avec anse dans la phase finale pour un dénouage facile et
rapide.


** Picket line hitch

/alias/ : ground line hitch

Clove hitch amélioré.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer un passage *D* au-dessus du poste, en diagonale vers
	l’arrière et la droite
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à droite de la
        partie statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer un passage *G* au-dessus de *D*, en diagonale vers
	l’arrière et la gauche
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
     4) passer devant le poste, vers le haut
  4. passer au-dessus de *G* en longeant la gauche de *D*
  5. passer entre *D* et le poste, vers la droite
  6. serrer


** Snuggle hitch

Espèce de trident avec entrelacement.

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer le passage *A* au-dessus du poste, vers l’arrière
     2) passer derrière le poste, vers le bas
     3) passer sous le poste, vers l’avant, à droite de la partie
	statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer le passage *G* au-dessus de *A* et du poste, en
	diagonale vers l’arrière et la gauche
     2) passer derrière le poste, vers le bas
     3) passer sous le poste, vers l’avant, à gauche de la partie
	statique
     4) passer devant le poste, vers le haut
  4. troisième tour
     1. effectuer le passage *D*, en diagonale vers l’arrière et la
	droite
	1) en-dessous de *G*
	2) au-dessus de *A*
     2. passer derrière le poste, vers le bas
     3. passer sous le poste, vers l’avant, à droite de la partie
	statique
     4. passer devant le poste, vers le haut
  5. passer au-dessus du poste, en diagonale vers l’arrière et la
     gauche
     1) au-dessus de *D*
     2) en-dessous de *A*
  6. serrer


** Buntline hitch                                   :derived:vibration_proof:

Clove hitch autour de la partie statique d’une boucle.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. tour
     1) passer au-dessus du poste, vers arrière et la gauche
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
  3. effectuer le passage *P* devant la partie statique, vers la
     droite et le bas, formant ainsi une boucle *B* autour du poste
  4. passer derrière la partie statique, vers la gauche
  5. effectuer le passage *R* devant la partie statique et devant *P*,
     vers la droite et le haut
  6. passer dans *B*, vers la gauche
  7. passer entre *R* et la partie statique
  8. serrer


* Constrictor knot
:PROPERTIES:
:CUSTOM_ID: section:cosntrictor
:END:

Peut être difficile à désserrer. Envisager une variante avec anse dans
la phase finale, pour un dénouage plus facile.


** Standard


*** Méthode directe

Former une croix au-dessus du poste. Passer autour de la partie
statique et sous la croix.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer le passage *D* au-dessus du poste, en diagonale vers
	l’arrière et la droite
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à droite de la
        partie statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer le passage *G* au-dessus de *D* et du poste, en
        diagonale vers l’arrière et la gauche
     2) Vérifier que *D* et *G* forment une croix *X*
     3) passer derrière le poste, vers le bas
     4) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
  4. passer devant la partie statique, de gauche à droite
  5. passer entre *G* et le poste, à droite de *X*
  6. passer entre *D* et le poste, à droite de *X*
  7. serrer


*** Méthode du huitain                                          :middle_rope:

Nécessite d’avoir accès à une extrémité du poste.

  1. faire un huitain supérieur droit, formant ainsi
     - une boucle *B*
     - une lentille *L*
     - un croisement intérieur *X*
  2. faire un demi-cercle anti-horlogique pour venir se positionner
     juste à droite de *X*
  3. passer en-dessous de *X*, vers la gauche
  4. faire un demi-tour avec *B*
     - autour de l’axe gauche - droite
       + matérialisé par la partie de travail
     - en commençant vers le bas et l’avant
     - pour amener *B* en-dessous de *L*
  5. passer *L* et *B* autour du poste
  6. serrer


** Double

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer le passage *D* au-dessus du poste, en diagonale vers
	l’arrière et la droite
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à droite de la
        partie statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer le passage *G* au-dessus de *D* et du poste, en
        diagonale vers l’arrière et la gauche
     2) Vérifier que *D* et *G* forment une croix *X*
     3) passer derrière le poste, vers le bas
     4) passer en-dessous du poste, vers l’avant et à droite
	- on doit se retrouver à droite de la partie statique
     5) passer devant le poste, vers le haut
  4. troisième tour
     1) effectuer un passage *H* au-dessus du poste en longeant la
	gauche de *G*
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
  5. passer devant la partie statique, vers la droite
  6. passer entre *H* et le poste, à droite de *X*
  7. passer entre *G* et le poste, à droite de *X*
  8. passer entre *D* et le poste, à droite de *X*
  9. serrer


** Boa

Nécessite d’avoir accès à une extrémité du poste.

  1. faire une bobine de quelques tours
  2. tordre la bobine pour qu’elle prenne une forme de 8
  3. replier la première série de boucles de la bobine sur la seconde
     pour obtenir une double bobine *B*
  4. passer *B* autour du poste
  5. serrer


* Dérivé de l’ossel hitch


** Ossel hitch avec final dans la boucle

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. ossel hitch
     1) premier demi-tour
	1. passer au-dessus du poste, vers l’arrière
	2. passer derrière le poste, vers le bas
     2) anse autour de la partie statique
	1. passer en-dessous du poste, vers l’avant, à gauche de la
           partie statique
	2. passer devant la partie statique, vers la droite, complétant
           ainsi une boucle *B*
	3. passer en-dessous du poste, vers l’arrière
     3) deuxième demi-tour, en sens inverse
	1. passer derrière le poste, vers le haut
	2. passer au-dessus du poste, vers l’avant
     4) passer devant le poste, vers le bas
  3. phase finale
     1) passer en-dessous du poste, vers l’arrière
     2) passer dans *B*, vers la gauche
  4. serrer


** Backhand hitch                                                   :derived:

Ossel hitch avec serrage en two half hitches.

Si le poste est disposé horizontalement :

  1. faire un ossel hitch
     - soit *P* le passage autour de la partie statique
  2. faire two half hitches autour de la partie statique et contre
     *P*, en descendant
  3. serrer


** Scaffold hitch
:PROPERTIES:
:CUSTOM_ID: section:scaffold_hitch
:END:


*** Standard

Principalement utilisé pour attacher deux noeuds aux bords gauche et
droit du poste, ce qui permet de le suspendre avec les cordes.

Nécessite d’avoir accès à une extrémité du poste.

Si le poste est disposé horizontalement :

  1. première corde, près du bord droit du poste
     1) faire une bobine de trois tours autour du poste
	- en progressant vers la droite
     2) placer le tour de gauche au milieu, entre les deux autres
     3) passer le nouveau tour de gauche au-dessus des deux autres,
        vers la droite, puis autour de l’extrémité du poste
	1. vers le bas, à droite du bord droit du poste
	2. sous le poste, vers la gauche
     4) serrer en tirant sur les parties libres de la corde dans des sens
	opposés
     5) attacher les deux parties libres par un noeud d’ajut
  2. seconde corde, près du bord gauche du poste
     1) faire une bobine de trois tours autour du poste
	- en progressant vers la gauche
     2) placer le tour de droite au milieu, entre les deux autres
     3) passer le nouveau tour de droite au-dessus des deux autres,
        vers la gauche, puis autour de l’extrémité du poste
	1. vers le bas, à gauche du bord gauche du poste
	2. sous le poste, vers la droite
     4) serrer en tirant sur les parties libres de la corde dans des sens
	opposés
     5) attacher les deux parties libres par un noeud d’ajut


*** Simplifié

Espèce de double ossel hitch symétrique, où les parties libres de la
corde partent dans des sens opposés.


**** Méthode du esse

Si le poste est disposé horizontalement :

  1. faire un esse, à droite, vers l’arrière
  2. placer le esse en-dessous du poste
  3. utiliser la partie libre de gauche comme partie de travail
     1) passer au-dessus du poste, vers l’arrière
     2) passer dans l’anse gauche du esse
	- derrière le poste
	- en entrant par au-dessus
  4. utiliser la partie libre de droite comme partie de travail
     1) passer au-dessus du poste, vers l’avant
     2) passer dans l’anse de droite du *S*
	- devant le poste
	- en entrant par au-dessus
  5. serrer en tirant sur les parties libres de la corde dans des sens
     opposés


**** Méthode directe

Le noeud ne tient que si les deux parties libres sont tendues.

Si le poste est disposé horizontalement :

  1. placer la corde derrière le poste
  2. premier tour
     1) passer au-dessus du poste, vers l’avant
     2) passer devant le poste, vers le bas
     3) passer en-dessous du poste, vers l’arrière, à gauche de la
        partie statique
  3. effectuer le passage *P* derrière la partie statique, de gauche à
     droite
  4. deuxième tour, en sens inverse
     1. passer en-dessous du poste, vers l’avant
     2. passer devant le poste, vers le haut
     3. passer au-dessus du poste, vers l’arrière, à droite de la
        partie statique
  5. faire une anse horlogique *A*
  6. troisième tour, sens originel
     1. passer au-dessus du poste, vers l’avant
     2. passer devant le poste vers le bas
     3. passer sous le poste, vers l’arrière
     4. passer derrière le poste, vers le haut
  7. rentrer dans *A* par en-dessous
  8. serrer en tirant sur les parties libres de la corde dans des sens
     opposés

Cas d’un poste mobile : on peut compléter en nouant les terminus pour
former une grande boucle et attacher l’ensemble à un objet fixe.


* Dérivés du lark’s head


** Pedigree cow hitch
:PROPERTIES:
:CUSTOM_ID: section:pedigree_cow_hitch
:END:

Lark’s head avec final dans la double boucle qui entoure l’objet.

  1. faire un lark’s head autour de l’objet
  2. passer une des parties libres dans les deux boucles du lark’s
     head
  3. serrer en tirant sur les parties libres de la corde


** Camel hitch
:PROPERTIES:
:CUSTOM_ID: section:camel_hitch
:END:

Combinaison de bobine, lark’s head et de half hitch.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. faire une bobine de trois tours autour du poste
     - vers la droite
     - en commençant par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. lark’s head
     1) passer sous le poste, vers l’avant, à droite de la partie
        statique
     2) effectuer le passage *P* devant la partie statique, vers la
        gauche
     3) tour
	1. passer en-dessous du poste, vers l’arrière
	2. passer derrière le poste, vers le haut
	3. passer au-dessus du poste, vers l’avant
     4) passer entre *P* et le poste
	- en longeant la partie statique par la gauche
	- vers le bas
  4. half hitch
     1) effectuer le passage *R* en-dessous de *P*, vers la gauche
     2) passer en-dessous du poste, vers l’arrière
     3) passer derrière le poste, vers le haut
     4) passer au-dessus du poste, vers l’avant
     5) passer entre *R* et le poste
	- à gauche de *P*
	- vers le bas
  5. serrer


** Lobster Buoy hitch knot

Lark’s head autour de la partie statique d’une boucle.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. tour
     1) passer au-dessus du poste, vers l’arrière
     2) passer derrière le poste, vers le bas
     3) passer sous le poste, vers l’avant
  3. réaliser un lark’s head autour de la partie statique
  4. serrer


* Enroulement


** Anchor hitch
:PROPERTIES:
:CUSTOM_ID: section:anchor_hitch
:END:

Bobine de deux tours autour du bord d’une bobine de deux tours.

Si le poste est disposé horizontalement :

  1. placer la corde à l’avant du poste
  2. faire une bobine de deux tours *B* autour du poste
  3. faire une bobine de deux tours autour du bord avant de *B*
  4. serrer


** A round turn and two half hitches

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. faire une bobine de deux tours autour du poste
     - vers la droite
     - en commençant par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. faire two half hitches autour de la partie statique et contre la
     bobine, en descendant
  4. serrer


** Timber hitch
:PROPERTIES:
:CUSTOM_ID: section:timber_hitch
:END:

/alias/ : noeud de bois

Bobine à l’intérieur de la boucle principale.

Si le poste est disposé verticalement :

  1. faire une boucle *B* autour du poste, partie de travail au-dessus
     vers la droite
  2. passer en-dessous de la partie statique, vers la gauche
  3. faire une bobine de quelques tours autour du bord gauche de *B*,
     en partant du croisement et en progressant vers le poste
  4. serrer


* Réalisé avec une double corde


** Reinforced ring hitch

Passer une anse autour du poste, puis utiliser une partie libre double
comme partie de travail et faire un half hitch.

Si le poste est disposé horizontalement :

  1. demi-tour
     1) placer la corde devant le poste
     2) passer au-dessus du poste, vers l’arrière
     3) passer derrière le poste, vers le bas
  2. faire un terminus double et l’utiliser comme partie de travail
  3. faire un demi-cercle *D* anti-horlogique, derrière le poste, vers
     le haut
     - *D* est un double cercle, car on utilise un terminus double
  4. tour
     1) passer derrière le poste, vers le haut
     2) passer au-dessus du poste, vers l’avant
     3) passer devant le poste, vers le bas
     4) passer sous le poste, vers l’arrière
  5. passer dans *D*
  6. serrer en tirant sur les parties libres


* Gripping hitches

Noeuds anti-glissement : la traction peut s’effectuer parallèlement au
poste.


** Rolling hitch
:PROPERTIES:
:CUSTOM_ID: section:rolling_hitch
:END:

Clove hitch avec un tour supplémentaire au départ.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. faire une bobine *B* de deux tours autour du poste
     - vers la droite
     - en commençant à tourner par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. tour 1, vers la gauche
     1) passer sous le poste, vers l’avant
     2) passer devant le poste et la partie du noeud déjà réalisée, vers
	le haut et la gauche
     3) faire un passage *P* au-dessus du poste, vers l’arrière et la
	gauche
  4. tour 2
     1) passer derrière le poste, vers le bas
     2) passer en-dessous du poste, vers l’avant
     3) passer devant le poste, vers le haut
  5. passer entre *P* et le poste, à gauche de *B*, vers l’arrière
  6. serrer


** Boom hitch
:PROPERTIES:
:CUSTOM_ID: section:boom_hitch
:END:

Clove hitch doublé en parallèle.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer le passage *D* au-dessus du poste, en diagonale vers
	l’arrière et la droite
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à droite de la
        partie statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer le passage *G* au-dessus de *D*, en diagonale vers
        l’arrière et la gauche
     2) vérifier que *D* et *G* forment une croix
     3) passer derrière le poste, vers le bas
     4) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
     5) passer devant le poste, vers le haut
  4. troisième tour
     1) effectuer le passage *E* au-dessus de *G*, en longeant la
        gauche de *D*
     2) dans la suite, continuer à suivre la corde en la longeant
        par la gauche
     3) passer derrière le poste, vers le bas
     4) passer en-dessous du poste, vers l’avant, à droite de la
        partie statique
     5) passer devant le poste, vers le haut
  5. quatrième tour
     1) effectuer le passage *H* au-dessus de *E*, en longeant la
        gauche de *G*
     2) passer derrière le poste, vers le bas
     3) arrêter de suivre la corde par la gauche
     4) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
     5) passer devant le poste, vers le haut
  6. passer au-dessus de *H* en longeant la gauche de *E*, vers
     l’arrière et la droite
  6. passer entre *G* et le poste
  7. serrer


** Icicle hitch
:PROPERTIES:
:CUSTOM_ID: section:icicle_hitch
:END:


*** Standard


**** Méthode de l’anse autour d’une extrémité du poste

Bobine, puis anse passée devant les parties libres et autour d’une des
extrémités du poste.

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
     - près de l’extrémité gauche du poste
  2. faire une bobine *B* de quatre tours autour du poste
     - en progressant vers la droite
     - en commençant par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. faire une anse horlogique *A*
     - voûte en bas
     - partie de travail à gauche de la bobine, vers le haut, derrière
       le poste
  4. passer au-dessus du poste, vers l’avant
  5. longer la partie statique par la gauche, devant le poste, vers le
     bas
  6. passer *A* sous le poste
     - vers l’avant
     - à droite des parties libres
  7. passer *A* devant les parties libres, vers la gauche
  8. passer *A* autour de l’extrémité gauche du poste
  9. serrer


**** Méthode directe

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. faire une bobine de quatre tours autour du poste
     - en progressant vers la droite
     - en commençant par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. passage devant la partie statique
     1) passer sous le poste, vers l’avant, à droite de la partie
        statique
     2) effectuer le passage *P* devant la partie statique, vers la
        gauche
  4. tour
     1) passer devant le poste à la gauche du noeud, vers le haut
     2) passer au-dessus du poste, vers l’arrière
     3) passer derrière le poste, vers le bas
  5. demi-cercle autour de la partie statique
     1) passer sous le poste, vers l’avant, à gauche de la partie
        statique
     2) effectuer le passage *R* devant la partie statique, vers la
        droite
     3) passer sous le poste, vers l’arrière
  6. en longeant la partie statique par la gauche
     1) passer derrière le poste, vers le haut
     2) passer au-dessus du poste, vers l’avant
     3) passer entre *P* et le poste
     4) passer entre *R* et le poste
  7. serrer


*** Variante

Crédit : chaîne youtube TX Tool Crib.

Combinaison de bobine, ossel hitch et clove hitch.

  1. passer la corde devant le poste
  2. faire une bobine de quatre tours autour du poste
     - en progressant vers la droite
     - en commençant par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. ossel hitch
     1) passer sous le poste, vers l’avant
     2) effectuer le passage *P* devant la partie statique, vers la
	gauche
     3) passer sous le poste, vers l’arrière
  4. demi-tour
     1) passer derrière le poste, vers le haut
     2) passer au-dessus du poste, vers l’avant
  5. clove hitch
     1) effectuer le passage *R* devant la partie statique, vers le bas
	et la droite
     2) passer entre *P* et le poste, vers l’arrière
     3) en longeant la partie statique par la droite
	1. passer sous le poste, vers l’arrière
	2. passer derrière le poste, vers le haut
	3. passer entre *R* et le poste, à gauche de la partie statique
  6. passer entre *P* et le poste, vers le base
  7. serrer


** Pipe hitch

Combinaison de bobine et de two half hitches.

  1. passer la corde devant le poste
  2. faire une bobine de quatre tours autour du poste
     - en progressant vers la droite
     - en commençant par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. passage devant la partie statique
     1) passer sous le poste, vers l’avant, à droite de la partie
        statique
     2) effectuer le passage *P* devant la partie statique, vers la
	gauche
     3) passer devant le poste, vers le haut, un peu à gauche de la
	partie statique
  4. half hitch 1
     1) passer au-dessus du poste, vers l’arrière
     2) passer derrière le poste, vers le bas
     3) passer sous le poste, vers l’avant
     4) passer entre *P* et le poste, vers l’avant
     5) longer la partie statique par la gauche, devant le poste, vers le
	haut
     6) serrer
  5. half hitch 2
     1) effectuer le passage *R* au-dessus du poste, vers l’arrière et
        la gauche
     2) passer derrière le poste, vers le bas
     3) passer sous le poste, vers l’avant
     4) passer devant le poste, vers le haut
     5) passer entre *R* et le poste, vers l’arrière
     6) serrer


** Gripping sailor hitch

Combinaison de bobine, ossel hitch et constrictor.

  1. passer la corde devant le poste
  2. faire une bobine de quatre tours autour du poste
     - en progressant vers la droite
     - en commençant par le haut, vers l’arrière
     - en terminant par l’arrière, vers le bas
  3. passage en diagonale devant la partie statique
     1) passer sous le poste, vers l’avant
     2) passer devant la partie statique, vers le haut et la gauche
	- forme un croisement *X*
  4. tour 1
     1) passer au-dessus du poste, vers l’arrière
     2) passer derrière le poste, vers le bas
  5. ossel hitch
     1) passer sous le poste, vers l’avant, à gauche de la partie
        statique
     2) passer devant la partie statique, vers la droite
     3) passer sous le poste, vers l’arrière
  6. tour 2
     1) passer derrière le poste, vers le haut
     2) passer au-dessus du poste, vers l’avant
     3) passer entre *X* et le poste, vers le bas
  7. serrer en tirant
     - la partie de travail vers le haut
     - la partie statique vers le bas


* Quick release

Noeuds à dénouage rapide, en tirant sur la partie de travail.


** Quick release slip knot                                    :quick_release:

Slip knot à boucle principale gansée autour du poste.

  1. faire un slip knot, partie statique du côté réglable
  2. appelons *A* l’anse du slip knot
  3. faire un tour avec la partie de travail autour du poste
  4. faire une anse *B* avec la partie de travail
  5. passer *B* dans *A*
  6. serrer *A* en tirant sur la partie statique


** Exploding Mooring hitch
:PROPERTIES:
:CUSTOM_ID: section:exploding_mooring_hitch
:END:

Partie statique dans une boucle, puis anse dans la boucle.

Si le poste est disposé horizontalement :

  1. placer la corde derrière le poste
  2. demi-tour
     1) passer au-dessus du poste, vers l’avant
     2) passer devant le poste, vers le bas
  3. faire une boucle horlogique *B*, partie de travail derrière vers
     la droite, voûte vers la gauche
  4. placer *B* devant la partie statique
  5. tirer la partie statique dans *B* pour former une anse *A*
  6. faire une anse *S* avec la partie de travail
  7. passer *S* dans *B*
  8. serrer en tirant sur la partie statique


** Evenk hitch                                                :quick_release:
:PROPERTIES:
:CUSTOM_ID: section:evenk_hitch
:END:

/alias/ : siberian hitch

Noeud en huit avec anse de dénouage rapide autour de la partie
statique.

  1. passer la corde autour du poste
  2. former un figure 8 en faisant passer la deuxième boucle réalisée
     autour de la partie statique
     - terminer le figure 8 en faisant entrer une anse formée avec la
       partie de travail dans la première boucle
  3. serrer

Autrement dit, si le poste est disposé verticalement :

  1. faire une anse *N* autour du poste, partie de travail à droite
     - soit *S* le segment de la partie statique située à gauche du
       poste
     - soit *T* la position actuelle de la partie de travail
  2. faire une boucle anti-horlogique *B*
     - partie de travail au-dessus vers la gauche
     - voûte vers l’avant droite
  3. passer au-dessus de *S*, vers la gauche
  4. passer en-dessous de *S* puis de *T*, de gauche à droite, un peu
     plus en arrière
  5. faire une anse *A*
  6. passer *A* dans *B*, en entrant par au-dessus
  7. serrer *B* autour de *A* en tirant sur le bord droit de *N* et
     sur *A*


** Innomiknot quick release
:PROPERTIES:
:CUSTOM_ID: section:innomiknot_quick_release
:END:

Combinaison d’ossel hitch et de slip knot légèrement torsadé à boucle
principale autour du poste.

Si le poste est disposé horizontalement :

  1. demi-tour
     1) placer la corde derrière le poste
     2) passer au-dessus du poste, vers l’avant et la droite
     3) passer devant le poste, vers le bas
  2. soulever la partie de la corde située au-dessus du poste, pour
     former une anse *A*
  3. tordre *A*, qui devient une boucle *B*
     - la rotation se fait dans un sens horlogique vu du haut
  4. tordre *B* d’un demi-tour, en utilisant le même sens de rotation
  5. demi-cercle autour de la partie statique
     1) passer sous le poste, vers l’arrière, à droite de la partie
	statique
     2) passer derrière la partie statique, de droite à gauche
     3) passer sous le poste, vers l’avant
  6. passer devant le poste, vers le haut
  7. faire une anse *S*
  8. passer *S* dans *B*, en entrant par la gauche
  9. serrer en tirant sur la partie statique
     - peut nécessiter des ajustements internes au noeud


** Tumble hitch

Une anse dans une anse dans une anse, avec ossel hitch.

Si le poste est disposé horizontalement :

  1. faire une anse *A*
  2. placer *A* derrière le poste, voûte vers le haut, partie de
     travail à droite
  3. passer la partie de travail en-dessous du poste, vers l’avant
  4. passer devant le poste, vers le haut
  5. faire une anse *B*
  6. passer *B* dans *A*
  7. demi-cercle autour de la partie statique
     1) passer la partie de travail en-dessous du poste, vers l’arrière à
	gauche de la partie statique
     2) passer derrière la partie statique, de gauche à droite
     3) passer en-dessous du poste, vers l’avant
  8. passer devant le poste, vers le haut
  9. faire une anse *C*
  10. passer *C* dans *B*
  11. serrer


** High post hitch

Deux tours autour d’une boucle pour laisser un espace, puis passer une
anse dedans.

Si le poste est disposé verticalement :

  1. faire une boucle *B* autour du poste, au-dessus vers la droite
  2. passer sous le croisement de *B*, vers la gauche
  3. faire un tour *T* autour des bords de *B*, plus près de la voûte,
     laissant un espace *E* entre le croisement de *B* et *T*
  4. faire une anse *A*
  5. passer *A* dans *E* en entrant par au-dessus
  6. serrer


** Manger hitch

Même idée générale que le high post hitch, avec bobine en plus.

Si le poste est disposé verticalement :

  1. faire une boucle *B* autour du poset, partie de travail au-dessus
     vers la droite
  3. un peu plus près de la voûte de *B*, effectuer le passage *P*
     sous les bords de *B*, vers la gauche, laissant un espace *E*
     entre le croisement de *B* et *P*
  4. faire une bobine de deux tours autour des bords de *B*, en
     progressant vers le poste, et en terminant en-dessous, vers la
     gauche
  5. faire une anse *A*
  6. passer *A* dans *B*, en entrant par au-dessus
  7. serrer *B* autour


** Painter hitch

Une anse dans une anse dans une anse qui tourne autour du poste.

Si le poste est disposé horizontalement :

  1. faire une anse *A*
  2. placer *A* devant le poste, voûte vers le haut
  3. demi-tour avec *A*
     1) passer *A* au-dessus du poste, vers l’arrière
     2) passer *A* derrière le poste, vers le bas
     3) placer *A* derrière la partie statique
  4. faire une anse *B* avec la partie statique et la passer dans *A*,
     en entrant par l’avant et en ressortant par l’arrière
  5. tourner *B* vers la gauche puis l’avant
  6. faire une anse *C* avec la partie de travail
  7. passer *C* dans *B*
  8. serrer


** Getaway hitch                                              :quick_release:

Une anse dans une anse, avec une espèce d’ossel hitch autour de la
première anse.

Si le poste est disposé horizontalement :

  1. faire une anse *A* et la placer devant le poste, partie de
     travail à droite
  2. tourner *A* autour d’un axe reliant les bords pour placer la base
     au-dessus du poste
  3. passer sous le poste, vers l’arrière
  4. passer derrière le poste, vers le haut
  5. passer au-dessus de la base de *A*, de droite à gauche
  6. passer derrière le poste, vers le bas
  7. passer sous le poste, vers l’avant et à gauche de la partie
     statique
  8. passer devant le poste, vers le haut
  9. faire une boucle *B* et la passer dans *A*
  10. serrer


** Highwayman’s hitch                                         :quick_release:

Une anse dans une anse dans une anse, avec tours autour du poste des
parties statique et de travail.

Amusant, car il se défait très vite, mais il n’est pas très fiable.

Si le poste est disposé horizontalement :

  1. faire une anse *A*
  2. placer la base de *A* derrière le poste
  3. faire le tour du poste par le bas puis l’avant avec la partie
     statique
  4. faire une anse *S* avec la partie statique et la passer dans *A*
  3. faire le tour du poste par le bas puis l’avant avec la partie
     de travail
  5. faire une anse *T* avec la partie de travail et la passer dans
     *S*
  6. serrer


* Swing hitch

Combinaison de clove hitch et ossel hitch.

Si le poste est disposé horizontalement :

  1. faire un clove hitch, partie statique à l’avant du poste et
     partie de travail à l’arrière
     - soit *D*, le première passage du clove hitch en diagonale vers
       l’arrière droite
     - soit *G*, le deuxième passage du clove hitch en diagonale vers
       l’arrière gauche
     - soit *E*, le troisième passage du clove hitch en diagonale vers
       l’arrière droite
  2. séparer *D* et *E* pour créer un couloir *C* entre les deux
     - suffisamment pour que la partie de travail se retrouve à gauche
       de la partie statique
  3. demi-cercle autour de la partie statique
     1) passer sous le poste, vers l’avant
     2) passer devant la partie statique, vers la droite
     3) passer sous le poste, vers l’arrière
  4. passer derrière le poste, vers le haut
  5. passer dans *C*, vers l’avant
  6. passer sous *G*
  7. passer sous *D*
  8. serrer


* Vibration proof hitch knot                                :vibration_proof:

Si le poste est disposé horizontalement :

  1. placer la corde devant le poste
  2. premier tour
     1) effectuer un passage *G* au-dessus du poste, en diagonale vers
	l’arrière et la gauche
     2) passer derrière le poste, vers le bas
     3) passer en-dessous du poste, vers l’avant, à gauche de la
        partie statique
     4) passer devant le poste, vers le haut
  3. deuxième tour
     1) effectuer un passage *D* au-dessus de *G*, en diagonale vers
	l’arrière et la droite
     2) vérifier que *G* et *D* forment une croix *X* au-dessus du
        poste
     3) passer derrière le poste, vers le bas
     4) passer en-dessous du poste, vers l’avant, à droite de la partie statique
  4. passer devant la partie statique, vers la gauche
  5. passer entre *D* et le poste, devant *X*, vers la droite
  6. passer au-dessus de la partie statique, vers la droite
  7. passer au-dessus de la croix, vers l’arrière
  8. passer entre *D* et le poste, vers la droite
  9. serrer


* Figure 8 hitch

Figure 8 en réalisant la première boucle autour du poste et la seconde
autour de la partie statique.

Si le poste est disposé verticalement :

  1. faire une boucle *B* autour du poste, partie de travail au-dessus
     vers la droite
  2. passer sous la partie statique, vers la gauche, hors de la boucle
  3. entrer dans la boucle *B* par le haut à l’avant et ressortir par
     le bas en arrière
  4. serrer


* Halter hitch

  1. faire un high post hitch
  2. passer la partie de travail dans l’anse qui a terminé le high
     post hitch
  3. serrer cette anse


* Attaches de plusieurs objets (lashing)

#+TOC: headlines 1 local


** Round lashing

Pour fixer deux bâtons parallèlement.

  1. soit *i?* et *II* les deux bâtons
  2. disposer les deux bâtons parallèlement
  3. faire un clove hitch autour des deux bâtons
  4. faire une bobine autour des deux bâtons
  5. terminer par un clove hitch autour des deux bâtons


** Shear lashing

Pour fixer deux bâtons parallèlement.

  1. soit *i?* et *II* les deux bâtons
  2. disposer les deux bâtons parallèlement
  3. faire un clove hitch autour d’un des deux bâtons
  4. faire une bobine autour des deux bâtons
  5. frapping turns : faire quelques tours entre *I* et *II*
  6. terminer par un clove hitch autour d’un des deux bâtons


** Square lashing

/alias/ : brêlage carré

Pour fixer deux bâtons perpendiculairement.

  1. croiser les deux bâtons perpendiculairement
  2. soit *S* le bâton du dessus
  3. soit *I* le bâton du dessous
  4. attacher la corde à *I*, près de *S*
     - par exemple avec un clove hitch
  5. enrouler la partie courte de la corde autour de la partie longue
  6. recommencer 2 ou 3 fois
     1) passer au-dessus de *S*
	- en restant du même côté de *I*
     2) passer en-dessous de *I*
     3) repasser au-dessus de *S* dans l’autre sens
     4) passer en-dessous de *I*, dans l’autre sens
  7. chaque passage sous *I* se fait à l’intérieur, près du centre du
     croisement des bâtons
  8. chaque passage au-dessus de *S* se fait à l’extérieur
  9. frapping turns : faire quelques tours autour du croisement des
     bâtons, sous *S* mais au-dessus de *I*
  10. faire deux overhand autour d’un des deux bâtons


** Diagonal lashing

Pour fixer deux bâtons perpendiculairement.

Plus flexible que le square lashing.

  1. croiser les deux bâtons perpendiculairement
  2. soit *S* le bâton du dessus
  3. soit *I* le bâton du dessous
  4. attacher la corde à *I*, près de *S*
     - par exemple avec un clove hitch ou un timber hitch
  5. enrouler la partie courte de la corde autour de la partie longue
  6. choisir la partie longue comme partie de travail
  7. recommencer 2 ou 3 fois
     1) passer au-dessus de *S* en diagonale
	- en passant de l’autre côté de *I*
     2) passer en-dessous de *I*
     3) repasser au-dessus de *S* dans l’autre sens, toujours en diagonale
     4) passer en-dessous de *I*
  8. frapping turns : faire quelques tours autour du croisement des
     bâtons, entre *S* et *I*
  9. faire deux overhand autour d’un des deux bâtons


** Japanese square lashing

  1. enrouler autour des deux bâtons perpendiculaires comme avec le
     square lashing, mais en utilisant une doublure
  2. séparer les deux parties libres en les faisant passer de chaque
     côté d’un des deux bâtons
  3. faire des frapping turns avec les deux parties libres
  4. terminer par un square knot


** Transom knot

Sorte de constrictor pour deux bâtons perpendiculaires.

  1. croiser les deux bâtons perpendiculairement
  2. soit *S* le bâton du dessus
  3. soit *I* le bâton du dessous
  4. passer au-dessus de *S* en diagonale
     - en passant de l’autre côté de *I*
  5. passer en-dessous de *I*
  6. repasser au-dessus de *S* dans l’autre sens, toujours en diagonale
  7. passer en-dessous de *I*
  8. passer au-dessus de la partie statique
  9. passer sous la croix formée par les deux passages en diagonale


** Tripod lashing

Pour fixer trois bâtons.

  1. soit *I*, *II*, *III* les trois bâtons
  2. disposer les trois bâtons parallèlement
  3. attacher la corde à *I* par un clove hitch
  4. enrouler la partie courte de la corde autour de la partie longue
  5. choisir la partie longue comme partie de travail
  6. tisser autour des trois bâtons
     - alternativement au-dessus et en-dessous
     - arrivé au dernier bâton, repartir dans l’autre sens
  7. frapping turns
     1) faire quelques tours entre *I* et *II*
     2) faire quelques tours entre *II* et *III*
  8. terminer par un clove hitch autour d’un des bâtons
  9. les disposer en trois pattes


** Double floor lashing

Pour rangée de bâtons.

  1. support
     1) disposer deux bâtons parallèlement, écartés et d’avant en arrière
	+ soit *I* et *II* ces deux bâtons de support
  2. rangée
     1) disposer les autres bâtons
	- parallèlement entre-eux
	- serrés et de gauche à droite
	- perpendiculairement par rapport à *I* et *II*
     2) attacher la corde à *I*
	+ par exemple avec un clove hitch ou un timber hitch
     3) enrouler la partie courte de la corde autour de la partie longue
     4) choisir la partie longue comme partie de travail
     5) passer au-dessus du premier bâton de la rangée
     6) passer sous *I*, en diagonale
     7) passer au-dessus du premier bâton de la rangée, de l’autre côté
	de *I*
     8) passer sous *I*
     9) utilser le même principe avec les autres bâtons de la rangée
     10) terminer par un clove hitch
     11) recommencer de l’autre côté de la rangée avec une autre corde,
	 en remplaçant *I* par *II*


** Ladder lashing

  1. nécessite deux cordes
  2. faire un marlingspike sur la corde de gauche
  3. passer le bâton dedans
  4. faire un marlingspike sur la corde de droite
  5. passer le bâton dedans
  6. recommencer pour les autres bâtons
