# vim: set ft=make :

include ../../../../Makefile.inc

.DEFAULT_GOAL := all

#  phony {{{1

.PHONY: debug

.PHONY: html

.PHONY: sync-html

.PHONY: all install

.PHONY: clean clean-html wipe

# debug {{{1

debug:
	@echo $(SUBDIRS)

# all, install {{{1

all:
	@$(ECHO)

install: all

# clean, wipe {{{1

clean:
	@$(ECHO)

clean-html:
	@$(ECHO)

wipe:
	@$(ECHO)
